### PR TITLE
LPS-196393 Generate random companyIds to avoid collisions when migrating companies

### PR DESCRIPTION
**Pull request by susanchen3**
Manually forwarding as test failures are unrelated :heavy_check_mark: 

Sent from: https://github.com/liferay-uniform/liferay-portal/pull/1510

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/761aab440a...5583cfc54d

**Comment by brianchandotcom** [comment]
@achaparro see 5583cfc54db28c1722f209f25746c6570b53d728

The order here matters?

```		long counterCompanyId = _counterLocalService.increment() + 1;

		long[] companyIds = PortalInstances.getCompanyIds();

		Company company = addCompany(
			RandomTestUtil.randomString() + "test.com");

**Comment by achaparro** [comment]
Hi @brianchandotcom,

Yes, the order matters since we need to get the list of current companyids before adding the new one. In that way we can verify the new one does not match any of existing companyIds.

**Pull request closed without merging**
