### PR TITLE
LPS-105724 Fix styles to align labels with fields

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b6ed8b1ada...6f577557ca

**Comment by brianchandotcom** [comment]
@adolfopa see

```
junit.framework.AssertionFailedError: 
Duplicate entry 'com.liferay.adaptive.media.web' for key 'IX_8BD6BCA7'
	at com.liferay.portal.log.assertor.PortalLogAssertorTest.scanXMLLogFile(PortalLogAssertorTest.java:172)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:98)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:88)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at co
```

**Comment by adolfopa** [comment]
@austinchiang I'm unable to reproduce this locally. Do you know if this is a common CI failure?

**Comment by austinchiang** [comment]
Hey @adolfopa based on the test [history](https://testray.liferay.com/home/-/testray/case_results/919560011/history?tab=result&hideFilterPin=true) this is a rare failure, so this is probably a fluke/race condition

**Pull request closed without merging**
