### PR TITLE
LPS-125933. Add more info in TODO

### PR DESCRIPTION
**Pull request by david-gutierrez-mesa**
https://issues.liferay.com/browse/LPS-125933

### CODE REVIEW

**Comment by david-gutierrez-mesa** [comment]
This is just a stub for ConvertWidgetPageWithWebContentsToContentPage.

For SF see https://github.com/david-gutierrez-mesa/liferay-portal/pull/59

**Comment by david-gutierrez-mesa** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/06d2d9b4a2...36dfb38021

**Comment by brianchandotcom** [comment]
Nice @david-gutierrez-mesa ! Now we need 299 more of these.

**Pull request closed without merging**
