### PR TITLE
LPD-26927 Handcraft this hot user updateLastLogin sql, to avoid using…

### PR DESCRIPTION
**Pull request by shuyangzhou**
… hibernate's session update which requires a refresh from DB for detached user object from cache.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@tinatian @vicnate5 please backport for LXC, thanks!

@victorhcunha please run a check for login test case, thanks! CC @slnn

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/df1f502c77...cc45ee99a3

**Comment by brianchandotcom** [comment]
@shuyangzhou see cc45ee99a31ae9d8c375b4844b0f2103b7a93f56

**Comment by marco-leo** [comment]
@vicnate5 @brianchandotcom Looking at this PR, I am questioning why we need at all the last login date to be stored in the User Table. I find it as a duplicate of [this](https://github.com/brianchandotcom/liferay-portal/blob/cc45ee99a31ae9d8c375b4844b0f2103b7a93f56/modules/dxp/apps/portal-security-audit/portal-security-audit-event-generators/src/main/java/com/liferay/portal/security/audit/event/generators/internal/events/LoginPostAction.java#L63) and as well duplicate of AC functionality. @vicnate5 can we evaluate the effort of removing it at all, and what is the impact on  depending functionalities

**Comment by victorhcunha** [comment]
Hi @shuyangzhou !
Here are the results for login testcase


Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | DB CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | --
Baseline | bdae471 | 8865 | - | 285 | 5,5,6 | 89,88,88
PR | - | 9168 | 3.417935702 | 288 | 4,4,4 | 91,92,89

More details you can see in our [spreadsheet](https://docs.google.com/spreadsheets/d/1M6VK8GtY9kkv1EwhGW7vwrEENSzyT7zKz-wOh11ZHBo/edit#gid=2028262177) 

cc @slnn

**Comment by vicnate5** [comment]
Result of the discussion about the lastLoginDate in the user table can be seen at https://liferay.atlassian.net/browse/LPD-29293

**Pull request closed without merging**
