### PR TITLE
LPS-55590 Update struts paths

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pei-jung please resend using new MVCRenderCommand, MVCResourceCommand, and MVCActionCommand. It'll be a lot easier because each existing *Action can just be renamed. Search for MVC*Command and how they are used. It'll make things a lot easier. THx.

**Comment by brianchandotcom** [comment]
@pei-jung see https://github.com/brianchandotcom/liferay-portal/pull/27696

**Pull request closed without merging**
