### PR TITLE
LRQA-62567 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRQA-62567

This is only for master and 7.3.x. Thanks.

@david-gutierrez-mesa

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure task is not related to changes in PR.
See https://github.com/Tim-Cao/liferay-portal/pull/485
❌ ci:test:stable - 6 out of 7 jobs passed
❌ ci:test:relevant - 23 out of 25 jobs passed in 1 hour 33 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0e41806fc5...3cacffe370

**Comment by brianchandotcom** [comment]
@Tim-Cao I backported this pull to 7.3.x.

**Pull request closed without merging**
