### PR TITLE
Lps 60670

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@brianchiu this Poshi test is failing randomly a lot.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0f39b0da69...b5e5be328d

**Comment by shuyangzhou** [comment]
@brianchiu please send me an email with the manual test steps for the failing tests.

If there are many failing tests, send the most frequent ones first.

I will take a look when I get a chance. @brianchandotcom at this moment I don't know whether I will be able to go to work on Monday, I hope things will get better tomorrow. But I will see what I can do when I get a break time.

**Comment by brianchiu** [comment]
@shuyangzhou 

Will do. I'll send you manual steps (or I'll make videos) for failing tests.

For this particular failure that happened on this pull, though, I talked to Hashi and he said that this failure is caused by the VMs going to sleep sometimes. This is why the screenshot in the poshi report is black. Here is the ticket that they are fixing it on: https://issues.liferay.com/browse/LRQA-20016

CC @brianchandotcom @michaelhashimoto @kiyoshilee

**Comment by brianchiu** [comment]
@shuyangzhou 
I've added steps and videos to this ticket in case you wanted to take a look: https://issues.liferay.com/browse/LRQA-20146

**In short, the issue is that the test cannot find the success message that the portal displays after you assign a user to a site. And this is happening inconsistently**

For this particular failure though, the screenshots in the poshi report are black and don't show anything. Because of that, it's hard to tell if the issue is a poshi bug or potential portal bug. It could be an instability in the way that our tests select the user to be added, or it could be a portal bug.

According to Hashi, the black screenshot bug has been fixed yesterday (https://issues.liferay.com/browse/LRQA-20016). It might be a better idea to wait for the next time this failure occurs. I can look at it then and make a better assessment.

CC @brianchandotcom

**Comment by shuyangzhou** [comment]
Yeah, let's wait it to happen again to confirm it is really a portal side issue first. My current task queue won't allow me to get to this any time soon anyway.

Once you confirm it is a portal side bug, I could let one of my guys do some digging first.

**Pull request closed without merging**
