### PR TITLE
LPS-63809 add panel should remember if it was open in applications or content

### PR DESCRIPTION
**Pull request by juliocamarero**
welcome2_-_liferay

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @evannagayama now if you open "add > Applications". Next time you open the panel, it will remember it was in "applications" and not in "content". Not sure if this will break any test. I will forward this to you if that happens.

thanks!!

**Comment by sharonchoi** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@juliocamarero poshi errors... please resend @evannagayama

**Pull request closed without merging**
