### PR TITLE
LPS-71753 Do not exclude date filtering for categories and vocabularies

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by ealonso** [comment]
ci:retest

**Comment by jpince** [comment]
@Ithildir any ideas on these test failures?
run#1 testReleaseVersions
`Difference in Bundle-Version for portal-kernel between master (2.26.0, defined in bnd.bnd) and release (2.26.1, defined in bnd.bnd) branches is not allowed. Please update "Bundle-Version: 2.26.1" in portal-kernel/bnd.bnd for the master branch.`

run #2 testReleaseVersions
`Difference in Bundle-Version for modules/util/portal-tools-service-builder between master (1.0.151, defined in bnd.bnd) and release (1.0.152, defined in bnd.bnd) branches is not allowed. Please update "Bundle-Version: 1.0.152" in modules/util/portal-tools-service-builder/bnd.bnd for the master branch.`

both runs semver (but no semver change made)
```
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec]   com.liferay.portal.instances.service               UNCHANGED  1.0.1      1.0.0      1.0.0      EXCESSIVE VERSION INCREASE
     [exec] 	-   version    1.0.0
     [exec] 	+   version    1.0.1
```
I don't see these errors in any other master pulls.

**Comment by Ithildir** [comment]
Hi @jpince,
I think these are temporary problems. There's a small delay between when Brian publishes a module in `7.0.x` and when updates the versions in `master`.

**Comment by jpince** [comment]
thanks @Ithildir!

ci:retest

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/df6be15f58...3adf863d1f

**Pull request closed without merging**
