### PR TITLE
LPS-55315 Remove old language properties

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/76111fc44e...4fbbc8e2ae

**Comment by brianchandotcom** [comment]
Great job @epgarcia ! :)

**Comment by brianchandotcom** [comment]
And @ealonso  :)

**Pull request closed without merging**
