### PR TITLE
LPS-104618  Drag and drop items in a concrete position

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@julien real error, please resend:

TypeError: Cannot read property 'type' of undefined

**Comment by julien** [comment]
@brianchandotcom yes will do.
/cc @matuzalemsteles

**Comment by matuzalemsteles** [comment]
Resubmitted #81707

**Comment by julien** [comment]
Thanks @matuzalemsteles

**Pull request closed without merging**
