### PR TITLE
LPS-61400

### PR DESCRIPTION
**Pull request by vicnate5**
Fix for https://github.com/brianchandotcom/liferay-portal/pull/34167

@marcellustavares

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@marcellustavares BookmarksResultRowSplitter has new ResultRowSplitterEntry("folders"

See how it's a message key / lower case.

Compare to modules/apps/workflow/workflow-task-web/src/main/java/com/liferay/workflow/task/web/dao/search/WorkflowTaskResultRowSplitter.java

new ResultRowSplitterEntry(
					"Pending", workflowTaskPendingResultRows));

Please resend. Thx.

**Comment by brianchandotcom** [comment]
@marcellustavares I'm going to try and merge it anyways.. I'll just lower case it myself. Please send me a follow up pull if needed.

**Comment by brianchandotcom** [comment]
@marcellustavares actually, I'm getting some SF / possible conflicts with the other workflow pull. Can you rebase and resend? Thx.

**Comment by marcellustavares** [comment]
resent to https://github.com/brianchandotcom/liferay-portal/pull/34248

**Pull request closed without merging**
