### PR TITLE
Lps 69939 2

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/50d83d6da2...eb6813dcba

**Comment by brianchandotcom** [comment]
@shuyangzhou can you backport? Thanks.

**Comment by brianchandotcom** [comment]
@codyhoag @brunobasto See eb6813dcbae463f15d1f79e8a1e012c2f74edaef

There is documentation that gets removed during regeneration. We need to fix this and probably add document tation to util-taglib/src/com/liferay/taglib/liferay-aui.xml

Thx.

**Comment by brianchandotcom** [comment]
@shuyangzhou please remember to backport both LPS-61420 (2061d793ab89642eff6d84d0bcc3693a29ce5ec6) and LPS-69939

Thx!

**Comment by shuyangzhou** [comment]
@tomwang2011 backport please.

**Pull request closed without merging**
