### PR TITLE
LPS-82138 Removal of journal article images

### PR DESCRIPTION
**Pull request by achaparro**
cc/ @pavel-savinov

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:upgrade @vicnate5

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/daa8281345...e8896e6179

**Comment by brianchandotcom** [comment]
@pavel-savinov see rename e8896e6

**Pull request closed without merging**
