### PR TITLE
LPS-72041 Frontend SPA settings do not change unless page is refreshed

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @izaera @jorgeferrer @drewbrokke

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:stop

See this [loop post](https://loop.liferay.com/home/-/loop/feed/5474610) for more details.

**Comment by michaelhashimoto** [comment]
ci:retest

Sorry for any inconvenience.

**Comment by pei-jung** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1d3c470da4...51ca374309

**Comment by brianchandotcom** [comment]
@izaera @pei-jung see 51ca3743092fd38cfa365c830f677fa23c73f158

thx

**Pull request closed without merging**
