### PR TITLE
LPS-86473 Add dependency to OAuth2ApplicationLocalServiceImpl so that…

### PR DESCRIPTION
**Pull request by Preston-Crary**
… is waits for the PortalCapabilityLocator before being published. This is only safe because the tracker for this is always registered after the tracker in PortletRepositoryDefiner. A long term solution would be to pull out enough of the kernel repository services so normal service dependency resolution works.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
@brianchandotcom I was never able to replicate the problem locally and haven't tested this on the CI yet.  So until the tests pass we won't know 100% that this works.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
Thx @Preston-Crary ! @shinnlok fyi

**Comment by jpince** [comment]
TOCTOUTest failure caused by https://github.com/liferay/liferay-portal/commit/c5b5a1ffd1eaf552c9b13f2aed68c5bfafa21b99#diff-9571c3b753ff68344aa5b896f37cd957, Brian is reverting

**Comment by jpince** [comment]
correction: test was ignored in https://github.com/liferay/liferay-portal/commit/b12a3aefd3ff7c1e49c18acef971f0cb7d34ca7f per BChan, I emailed Stian & Carlos.

**Pull request closed without merging**
