### PR TITLE
LPS-91935 Update portal-impl packageinfo

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
Thanks for the heads up @pavel-savinov!

**Comment by kyle-miho** [comment]
@jkappler is going to push this upstream

**Comment by kyle-miho** [comment]
ci:close

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Muchas gracias @ruben-pulido!!!!

**Pull request closed without merging**
