### PR TITLE
LPS-151907 As a developer using headless endpoints, I'd like to get a country by countryId, a2, a3, countryName, and countryNumber

### PR DESCRIPTION
**Pull request by epark18**
Manual forward from [liferay-usm#541](https://github.com/liferay-usm/liferay-portal/pull/541).

https://issues.liferay.com/browse/LPS-151906
https://issues.liferay.com/browse/LPS-151907

### CODE REVIEW

**Comment by drewbrokke** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/116736

**Comment by drewbrokke** [comment]
ci:close

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/031851286b...a761cf6cbd

**Comment by brianchandotcom** [comment]
@epark18 @drewbrokke I made a lot of important changes. Please review in my origin. Thx!

**Comment by drewbrokke** [comment]
Got it, thanks Brian!

**Pull request closed without merging**
