### PR TITLE
LPS-77133 Set default default layout display style as miller style view

### PR DESCRIPTION
**Pull request by jkappler**
cc:// @anthony-chu

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test

**Comment by anthony-chu** [comment]
@jkappler it looks like there are still some fixes i'll need to make. i'll resend it after i make the needed poshi changes.

**Comment by anthony-chu** [comment]
ci:close

**Comment by jkappler** [comment]
Ok, thanks @anthony-chu!

**Pull request closed without merging**
