### PR TITLE
LPS-44217 Fix failing tests

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by brianchandotcom** [comment]
@adolfopa this is close.. can you resend on top of https://github.com/adolfopa/liferay-portal/pull/1160

1.)

MultiVirtualHostLocaleFilterTest

does not match package

com.liferay.portal.servlet.filters.multihost.locale.test

2.) Just within the files changed, I see a lot of:

TreeMap<String, String> virtualHostnames = getVirtualHostnames

Hence, the pattern "Hostname"

But site_url.jsp is

TreeMap<String, String> publicVirtualHosts = publicLayoutSet.getVirtualHostnames();

and SiteAdminPortlet.java has

String[] virtualHostNames

This is also bad:

String virtualHostLocale = virtualHostLocales[i];

Because we always do

Locale xyzLocale

not

String xyzLocale

So we have lots of tiny var name inconsistencies. Please meticulously review them and resend. This is a big change and I want to make sure that all the new nomenclature is conistent. Thx!

@rotty3000 fyi

**Pull request closed without merging**
