### PR TITLE
LPS-67352

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Fix for broken JavaSourceProcessorTest.testIncorrectIfStatement here: https://github.com/brianchandotcom/liferay-portal/pull/42669

**Comment by brianchandotcom** [comment]
@hhuijser this one is tricky.

When we do concats and just 3 strings, it's actually faster to use concat. But once we go past 3, then it's better to use SB.

See https://web.liferay.com/web/shuyang.zhou/blog/-/blogs/string-performance

**Comment by brianchandotcom** [comment]
@hhuijser so I"m not merging in this one.

**Comment by brianchandotcom** [comment]
Can you resend this, things that are 4 should be sent. Things that are 3 shouldn't.

**Pull request closed without merging**
