### PR TITLE
LPS-103802 saml-opensaml-integration: Use Bouncy Castle Provider 1.61

### PR DESCRIPTION
**Pull request by csierra**
/cc @lipusz

### CODE REVIEW

**Comment by csierra** [comment]
ci:test:saml

**Comment by yichenroy** [comment]
ci:test:saml
Test couldn't start due to network outage.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1665f2915d...50ab03098e

**Comment by lipusz** [comment]
Hello Brian, @brianchandotcom

Looks like this change is already in your origin for 7.1.x too though it has not been pushed to upstream yet.

Can you please do it so the ER guys can forward the backport for 7.0.x that is blocked currently because of this?

Thank you in advance.

Tibor

**Pull request closed without merging**
