### PR TITLE
Lps 74693

### PR DESCRIPTION
**Pull request by shuyangzhou**
@sergiogonzalez we are resuming the arquillian removal process. We believe the arquillian docker is no long used on CI since adaptive media is no longer a subrepo. Plus the docker image master git hash is ae2014bf020d5042231e0ea754f3fb5914a5130b , which was from Dec 2017, no way current adaptive media jar can still work on that old master, so my guess is you guys are not using it on your side either.

So to keep things simple, we are just removing the arquillian docker without providing replacement.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Hey @Preston-Crary I have this on my local branch, but I didn't push it up yet. I don't see modules/test/arquillian in 7.0.x or 7.1.x. So how will this new code get propagated to those older branches? I assume I publish this jar, but I didn't see anywhere in your code to force it to use the new jar?

Please send me a pull to use the new jar and I can ensure that part is backported. I can publish this for you first if you need me to (just tell me where to use the new jar, thx.)

**Comment by mtambara** [comment]
@brianchandotcom Since we're still using project dependencies in master, there is no commit in this pull to force master tests to use these changes, they'll just use them automatically. The process to make the older branches use these changes would be for you to publish and then to update the versions in 7.1.x and 7.0.x

We're going to be making a lot of changes to arquillian in the next few weeks though, so I don't know if you want to keep publishing a new jar for every pull or if you want to just wait until we're done and publish all at once.

**Comment by brianchandotcom** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@shuyangzhou @mtambara merged, I also published 1.0.9 and forced adaptive media in 7.1.x to use 1.0.9

Can you force all modules in master, 7.1 and 7.0 to use 1.0.9? Thx.

**Pull request closed without merging**
