### PR TITLE
LPS-75929 Applies automatic formatting to wiki-web (auto-generated)

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@jbalsas not merging.. this is going backwards..

```
				tempImages.forEach(
					node => {
						node.parentElement.remove();
					}
				);
```

is correct.

```
				tempImages.forEach(node => {
					node.parentElement.remove();
				});
```

is harder to read and breaks from our other existing non JS specific patterns.

Just like how in Java, we do:

```
    
if (true) {
    ...
}
else {
    ...
}

```

We can't have JS do

```
if (true) {
} else {
}

```

Please fix the auto formatting and resend.

**Comment by jbalsas** [comment]
Hey @brianchandotcom, see https://github.com/brianchandotcom/liferay-portal/pull/53142 👍

**Pull request closed without merging**
