### PR TITLE
LPS-48156 Add MustHavePermission inner exception to PrincipalException

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @JorgeFerrer @natecavanaugh

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Please resend based on https://github.com/pei-jung/liferay-portal/pull/43

**Pull request closed without merging**
