### PR TITLE
Lps 75997

### PR DESCRIPTION
**Pull request by shuyangzhou**
@brianchandotcom this one can technically be made backward compatible. But it will look very ugly and won't really make sense. To keep things simple, let's just not backport it, or just do it hoping no one is directly using the com.liferay.product.navigation.simulation.application.list.SimulationPanelCategory from the customer(which is most likely to be true, just we can not be sure).

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
