### PR TITLE
master-lps-62065

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LPS-62065

### CODE REVIEW

**Comment by evannagayama** [comment]
@brianchandotcom I noticed the below tests failing pretty consistently. We'll look at it asap tomorrow morning:
ApplicationdisplaytemplatesUsecase#ADTCategoriesNavigation
ApplicationdisplaytemplatesUsecase#ADTTagsNavigationPortlet

@brianwulbern
Could you please look at the failing PR tests and try to fix them asap since you get in earliest? Thanks!

**Comment by evannagayama** [comment]
@sharonchoi we modified your dm tests to be 1 column and removed the drag and drop. I had previously thought that they weren't affected, but they are :(

The ability to open both product menu + control menu at the same time breaks the drag and drop. We can try to fix it with another solution in the future.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/93205efe67...970be666f3

**Comment by brianwulbern** [comment]
@evannagayama 

Looking into them.

**Pull request closed without merging**
