### PR TITLE
LPS-194953 Add Feature Flag

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://liferay.atlassian.net/browse/LPS-194953

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:reopen

**Comment by mateussgn** [comment]
Resent from: https://github.com/brianchandotcom/liferay-portal/pull/140478

**Comment by brianchandotcom** [comment]
@mateussgn this is a bad title

Validation Client Extension

I have no idea if this is "email validation" or something else. Search for " Client Extension" and see the other FF titles.

**Comment by mateussgn** [comment]
Resent: https://github.com/brianchandotcom/liferay-portal/pull/140735

**Pull request closed without merging**
