### PR TITLE
LPS-56522 Load AccessControlUtil with OSGi

### PR DESCRIPTION
**Pull request by topolik**

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7b12b4fb29...6e5dd84e0a

**Pull request closed without merging**
