### PR TITLE
LPS-67119 Move Journal Article Images to Portlet File Repository

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
@marcellustavares could you please have a look at our changes regarding the usage of DDM? We are trying to use the standard code for images instead of having a custom code for journal. Thank you!

**Comment by kenjiheigel** [comment]
Looks like ApplicationdisplaytemplatesUsecase#AddRSSADTViaPortletConfiguration failed cause the internet was down: 
```
[exec] 14:56:15,975 INFO  [http-nio-8080-exec-1][RetryExec:159] I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://www.latimes.com:80: No route to host
[exec] 14:56:15,976 INFO  [http-nio-8080-exec-1][RetryExec:159] Retrying request to {}->http://www.latimes.com:80
```

The other test fails due to an SPA timeout issue. I'll be looking into that here: https://issues.liferay.com/browse/LRQA-27384.

**Comment by brianchandotcom** [comment]
@juliocamarero modules-int* broken. Please resend. Thx.

**Comment by juliocamarero** [comment]
I don't think the test failures are related to these changes: https://github.com/brianchandotcom/liferay-portal/pull/42704

**Pull request closed without merging**
