### PR TITLE
LPS-104666 Add test

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:reopen

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6db7596449...2f2128ce69

**Comment by brianchandotcom** [comment]
@epgarcia see 3a2a62d6d2f1d8ea299d7aa5dce0ddd17256cfce and 2f2128ce69dff34bbe4fab3a4296b5fd0925d48a thx

**Comment by brianchandotcom** [comment]
@pyoo47 lots of tmp file errors

**Pull request closed without merging**
