### PR TITLE
[See description] LPS-55285 LPS-55371

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey Brian,

There are 2 different LPS tickets in this pull but they are related, so you will need to update both in JIRA.

Thanks!

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @samuelkong

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@sergiogonzalez this is a bug in the test framework itself which we fixed. So you can ignore the failure

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/605b3b8364...c289150097

**Pull request closed without merging**
