### PR TITLE
LPS-182175 Remove orphaned partition when company creation fails

### PR DESCRIPTION
**Pull request by achaparro**
cc/ @javalosjr96

### CODE REVIEW

**Comment by achaparro** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e035aa4118...9fec09c814

**Comment by brianchandotcom** [comment]
@achaparro 

Shouldn't

```
			if (newDBPartitionAdded) {
				DBPartitionUtil.removeDBPartition(companyId);
			}
```

This be !newDBPartitionAdded instead of newDBPartitionAdded

See also 6192425d 1b118d88 and 9fec09c8

**Comment by achaparro** [comment]
Hey @brianchandotcom,

This is correct:
`			if (newDBPartitionAdded) {
				DBPartitionUtil.removeDBPartition(companyId);
			}
`

Because the boolean is set to true when the db partition is created, not when the company creation ends properly.

**Pull request closed without merging**
