### PR TITLE
LPS-67888 copy type settings to the target layout in copy applications action

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 what broke with Ruby here? It showed up as green?

**Comment by brianchandotcom** [comment]
@jhendley *ruby* showed as green and broken. Very strange.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/740f9a1a49...0388f0cfb8

**Comment by pyoo47** [comment]
@brianchandotcom There was some kind of problem going on with test-1-17. It seems like whatever it was, it's not happening anymore. The error looks like some kind of I/O issue that is interfering with the master communicating with the slaves.
```
Building remotely on cloud-10-0-112-93 in workspace /opt/dev/projects/github/liferay-jenkins-ee
Triggering 0,!master
0,!master completed with result SUCCESS
FATAL: channel is already closed
hudson.remoting.ChannelClosedException: channel is already closed
	at hudson.remoting.Channel.send(Channel.java:541)
	at hudson.remoting.Request.call(Request.java:129)
	at hudson.remoting.Channel.call(Channel.java:739)
	at hudson.Launcher$RemoteLauncher.kill(Launcher.java:918)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:552)
	at hudson.model.Run.execute(Run.java:1706)
	at hudson.matrix.MatrixBuild.run(MatrixBuild.java:306)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:232)
	at hudson.model.OneOffExecutor.run(OneOffExecutor.java:43)
Caused by: java.io.IOException
	at hudson.remoting.Channel.close(Channel.java:1027)
	at hudson.remoting.Channel.close(Channel.java:1009)
	at hudson.slaves.SlaveComputer.closeChannel(SlaveComputer.java:614)
	at hudson.slaves.SlaveComputer.access$600(SlaveComputer.java:88)
	at hudson.slaves.SlaveComputer$3.run(SlaveComputer.java:547)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Pull request closed without merging**
