### PR TITLE
LPS-70758 SF

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1650317488...fef3ed6d28

**Comment by brianchandotcom** [comment]
@jbalsas @sSpencerWoo please backport Thx.

**Comment by jbalsas** [comment]
Thanks Brian, backported! https://github.com/dustinryerson/liferay-portal-ee/pull/2928

**Pull request closed without merging**
