### PR TITLE
LPS-69147 1975 London Theme

### PR DESCRIPTION
**Pull request by kenjiheigel**
Resend of https://github.com/brianchandotcom/liferay-portal/pull/45043

cc-ing @jbalsas

### CODE REVIEW

**Comment by kenjiheigel** [comment]
> Hey Brian!
This is the final theme of the series, 1975-London.
I've sent the BPR to @ZoltanTakacs [here](https://github.com/ZoltanTakacs/liferay-portal-ee/pull/2144)
Please, let me know if you have any questions.
Thanks!

-Chema

**Comment by kenjiheigel** [comment]
@brianchandotcom, the build-app-module ant script wasn't looking for alphanumeric characters in the package.json for artifact name for themes, which is why the lpkg tests were failing in the previous pulls. I updated the ant script and have resent these pulls. 

Resend of ee-7.0.x backport: https://github.com/brianchandotcom/liferay-portal-ee/pull/15227.

**Comment by kenjiheigel** [comment]
ci:stop

**Comment by kenjiheigel** [comment]
ci:reopen

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
It passed in a pull to myself earlier: https://github.com/kenjiheigel/liferay-portal/pull/331.

**Comment by jbalsas** [comment]
Thanks a lot @kenjiheigel!!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/66cd0084d1...975b0cb478

**Pull request closed without merging**
