### PR TITLE
LPS-133735 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-133735

This is only for master.

@victorg1991

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure case is flaky issue.
See https://github.com/liferay-echo/liferay-portal/pull/5305
✔️ ci:test:stable - 10 out of 10 jobs passed
❌ ci:test:relevant - 22 out of 24 jobs passed in 1 hour 50 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/45b97eae38...2fbcaa9ccd

**Comment by brianchandotcom** [comment]
@NemethNorbert see 2fbcaa9ccd28a7725a90204a7104992a406f2f7e

**Pull request closed without merging**
