### PR TITLE
LPS-114729 Parameterize the generic type

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/1114

**Comment by ealonso** [comment]
ci:reopen

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/00f476af0e...6bd82c181f

**Comment by brianchandotcom** [comment]
@JorgeFerrer @ealonso see 6bd82c181f86826c47a145c76fb4065df11022a2

Sorry again guys for the trouble!

**Comment by JorgeFerrer** [comment]
Thanks Brian!

I'll try to send a pull tomorrow with some renames and movement of classes that we avoided trying to prevent rebase errors.

**Pull request closed without merging**
