### PR TITLE
Upgrade Process: Safe upgrade LastPublisDate

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by migue** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@brianchiu I think those are random test failures.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/44e0dbd7cd...16ad9474ab

**Comment by brianchandotcom** [comment]
@migue see 16ad9474ab482cab8a83225a14f19ae5bec6dd7d for my changes. Thx.

**Comment by brianchiu** [comment]
@sharonchoi
Can you take a look at these? The screenshots indicate potential bug.

**Comment by sharonchoi** [comment]
@brianchiu ok, investigating. https://issues.liferay.com/browse/LRQA-22762

**Pull request closed without merging**
