### PR TITLE
LPS-181170 Add clay to import maps

### PR DESCRIPTION
**Pull request by izaera**
Partial resend of https://github.com/brianchandotcom/liferay-portal/pull/133221

I'm skipping CI since the original PR passed the tests.

### CODE REVIEW

**Comment by izaera** [comment]
ci:reopen

**Comment by izaera** [comment]
Mmm, [this breaks CI](https://github.com/liferay-frontend/liferay-portal/pull/3232#issuecomment-1510934949), even though it didn't complain locally :thinking: 

I'll fix it and resend.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b45793ed50...97dfe2af6c

**Comment by brianchandotcom** [comment]
@izaera see 9da10530 febbbea7 97dfe2af 137f44d2 and 2673175a

**Comment by brianchandotcom** [comment]
@ling-alan-huang what shoudl we do with 97dfe2af

Thx

**Pull request closed without merging**
