### PR TITLE
LRAMF-410 Updating alloy framework for osgi support (round 3)

### PR DESCRIPTION
**Pull request by ethanbustad**

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:retest

**Comment by jpince** [comment]
ci:stop

**Comment by jpince** [comment]
@ethanbustad looks like the failing batch had an Out of Memory error unrelated to your pull, should be fine.

**Comment by ethanbustad** [comment]
Kk, thanks @jpince!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fe37bc7bb8...d821e7be4f

**Comment by brianchandotcom** [comment]
@ethanbustad please see my changes in upstream. Thx.

**Pull request closed without merging**
