### PR TITLE
LPS-65693 wrong deployment of dependencies

### PR DESCRIPTION
**Pull request by rotty3000**
/cc @mhan810 @shuyangzhou @Ithildir @CAustin582 @lionah @jrhoun

### CODE REVIEW

**Comment by sharonchoi** [comment]
@kenjiheigel @rotty3000 
There are console errors thrown, that say there are errors with resolving certain modules, which are causing our PortalSmoke#Smoke tests to fail.

**Comment by shuyangzhou** [comment]
The actual failure is,

```
     [exec] 15:50:25,318 ERROR [localhost-startStop-1][ModuleFrameworkImpl:962] org.osgi.framework.BundleException: Could not resolve module: org.apache.felix.dependencymanager.shell [13]
     [exec]   Unresolved requirement: Import-Package: org.apache.felix.service.command; status="provisional"; version="[0.10.0,1.0.0)"
     [exec] 
     [exec] org.osgi.framework.BundleException: Could not resolve module: org.apache.felix.dependencymanager.shell [13]
     [exec]   Unresolved requirement: Import-Package: org.apache.felix.service.command; status="provisional"; version="[0.10.0,1.0.0)"
     [exec] 
     [exec] 	at org.eclipse.osgi.container.Module.start(Module.java:429)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:421)
     [exec] 	at com.liferay.portal.bootstrap.ModuleFrameworkImpl._installInitialBundle(ModuleFrameworkImpl.java:915)
     [exec] 	at com.liferay.portal.bootstrap.ModuleFrameworkImpl._setUpInitialBundles(ModuleFrameworkImpl.java:1091)
     [exec] 	at com.liferay.portal.bootstrap.ModuleFrameworkImpl.startFramework(ModuleFrameworkImpl.java:400)
     [exec] 	at com.liferay.portal.module.framework.ModuleFrameworkUtilAdapter.startFramework(ModuleFrameworkUtilAdapter.java:93)
     [exec] 	at com.liferay.portal.spring.context.PortalContextLoaderListener.contextInitialized(PortalContextLoaderListener.java:253)
     [exec] 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812)
     [exec] 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255)
     [exec] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
     [exec] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
     [exec] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
     [exec] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
     [exec] 	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:585)
     [exec] 	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1794)
     [exec] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
     [exec] 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
     [exec] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [exec] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [exec] 	at java.lang.Thread.run(Thread.java:745)
```

@rotty3000 I think you missed some dependencies when moving org.apache.felix.dependencymanager.jar and org.apache.felix.dependencymanager.shell.jar to static.

**Comment by rotty3000** [comment]
I'll check, but felix DM has no external dependencies other than the core
framework.

On Mon, May 9, 2016 at 12:50 PM, Shuyang Zhou <notifications@github.com>
wrote:

> The actual failure is,
>
>      [exec] 15:50:25,318 ERROR [localhost-startStop-1][ModuleFrameworkImpl:962] org.osgi.framework.BundleException: Could not resolve module: org.apache.felix.dependencymanager.shell [13]
>      [exec]   Unresolved requirement: Import-Package: org.apache.felix.service.command; status="provisional"; version="[0.10.0,1.0.0)"
>      [exec]
>      [exec] org.osgi.framework.BundleException: Could not resolve module: org.apache.felix.dependencymanager.shell [13]
>      [exec]   Unresolved requirement: Import-Package: org.apache.felix.service.command; status="provisional"; version="[0.10.0,1.0.0)"
>      [exec]
>      [exec]     at org.eclipse.osgi.container.Module.start(Module.java:429)
>      [exec]     at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
>      [exec]     at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:421)
>      [exec]     at com.liferay.portal.bootstrap.ModuleFrameworkImpl._installInitialBundle(ModuleFrameworkImpl.java:915)
>      [exec]     at com.liferay.portal.bootstrap.ModuleFrameworkImpl._setUpInitialBundles(ModuleFrameworkImpl.java:1091)
>      [exec]     at com.liferay.portal.bootstrap.ModuleFrameworkImpl.startFramework(ModuleFrameworkImpl.java:400)
>      [exec]     at com.liferay.portal.module.framework.ModuleFrameworkUtilAdapter.startFramework(ModuleFrameworkUtilAdapter.java:93)
>      [exec]     at com.liferay.portal.spring.context.PortalContextLoaderListener.contextInitialized(PortalContextLoaderListener.java:253)
>      [exec]     at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812)
>      [exec]     at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255)
>      [exec]     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
>      [exec]     at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
>      [exec]     at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
>      [exec]     at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
>      [exec]     at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:585)
>      [exec]     at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1794)
>      [exec]     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
>      [exec]     at java.util.concurrent.FutureTask.run(FutureTask.java:262)
>      [exec]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
>      [exec]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
>      [exec]     at java.lang.Thread.run(Thread.java:745)
>
> @rotty3000 <https://github.com/rotty3000> I think you missed some
> dependencies when moving org.apache.felix.dependencymanager.jar and
> org.apache.felix.dependencymanager.shell.jar to static.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/39518#issuecomment-217921224>
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by rotty3000** [comment]
Oh, I know the issue... it's just ordering of the initial bundles. fixing!

**Comment by rotty3000** [comment]
ci:retest

**Comment by alee8888** [comment]
@rotty3000 
There are still unresolved requirements console errors on startup:
`[exec] 17:32:36,124 ERROR [localhost-startStop-1][ModuleFrameworkImpl:962] org.osgi.framework.BundleException: Could not resolve module: com.liferay.portal.osgi.web.wab.generator [27]
     [exec]   Unresolved requirement: Import-Package: com.liferay.petra.xml; version="[1.0.0,2.0.0)"
     [exec] 
     [exec] org.osgi.framework.BundleException: Could not resolve module: com.liferay.portal.osgi.web.wab.generator [27]
     [exec]   Unresolved requirement: Import-Package: com.liferay.petra.xml; version="[1.0.0,2.0.0)"
     [exec] 
     [exec] 	at org.eclipse.osgi.container.Module.start(Module.java:429)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:421)
     [exec] 	at com.liferay.portal.bootstrap.ModuleFrameworkImpl._installInitialBundle(ModuleFrameworkImpl.java:915)
     [exec] 	at com.liferay.portal.bootstrap.ModuleFrameworkImpl._setUpInitialBundles(ModuleFrameworkImpl.java:1091)
     [exec] 	at com.liferay.portal.bootstrap.ModuleFrameworkImpl.startFramework(ModuleFrameworkImpl.java:400)
     [exec] 	at com.liferay.portal.module.framework.ModuleFrameworkUtilAdapter.startFramework(ModuleFrameworkUtilAdapter.java:93)
     [exec] 	at com.liferay.portal.spring.context.PortalContextLoaderListener.contextInitialized(PortalContextLoaderListener.java:253)
     [exec] 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812)
     [exec] 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255)
     [exec] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
     [exec] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
     [exec] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
     [exec] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
     [exec] 	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:585)
     [exec] 	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1794)
     [exec] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
     [exec] 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
     [exec] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [exec] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [exec] 	at java.lang.Thread.run(Thread.java:745)
     [exec] 17:32:36,129 ERROR [localhost-startStop-1][ModuleFrameworkImpl:962] org.osgi.framework.BundleException: Could not resolve module: com.liferay.portal.osgi.web.wab.reference.support [28]
     [exec]   Unresolved requirement: Import-Package: com.liferay.portal.osgi.web.wab.generator; version="[1.0.0,2.0.0)"
     [exec]     -> Export-Package: com.liferay.portal.osgi.web.wab.generator; bundle-version="2.1.2"; bundle-symbolic-name="com.liferay.portal.osgi.web.wab.generator"; version="1.0.0"
     [exec]        com.liferay.portal.osgi.web.wab.generator [27]
     [exec]          Unresolved requirement: Import-Package: com.liferay.petra.xml; version="[1.0.0,2.0.0)"
     [exec] 
     [exec] org.osgi.framework.BundleException: Could not resolve module: com.liferay.portal.osgi.web.wab.reference.support [28]
     [exec]   Unresolved requirement: Import-Package: com.liferay.portal.osgi.web.wab.generator; version="[1.0.0,2.0.0)"
     [exec]     -> Export-Package: com.liferay.portal.osgi.web.wab.generator; bundle-version="2.1.2"; bundle-symbolic-name="com.liferay.portal.osgi.web.wab.generator"; version="1.0.0"
     [exec]        com.liferay.portal.osgi.web.wab.generator [27]
     [exec]          Unresolved requirement: Import-Package: com.liferay.petra.xml; version="[1.0.0,2.0.0)"
     [exec] 
     [exec] 	at org.eclipse.osgi.container.Module.start(Module.java:429)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:421)
     [exec] 	at com.liferay.portal.bootstrap.ModuleFrameworkImpl._installInitialBundle(ModuleFrameworkImpl.java:915)
     [exec] 	at com.liferay.portal.bootstrap.ModuleFrameworkImpl._setUpInitialBundles(ModuleFrameworkImpl.java:1091)
     [exec] 	at com.liferay.portal.bootstrap.ModuleFrameworkImpl.startFramework(ModuleFrameworkImpl.java:400)
     [exec] 	at com.liferay.portal.module.framework.ModuleFrameworkUtilAdapter.startFramework(ModuleFrameworkUtilAdapter.java:93)
     [exec] 	at com.liferay.portal.spring.context.PortalContextLoaderListener.contextInitialized(PortalContextLoaderListener.java:253)
     [exec] 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812)
     [exec] 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255)
     [exec] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
     [exec] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
     [exec] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
     [exec] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
     [exec] 	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:585)
     [exec] 	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1794)
     [exec] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
     [exec] 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
     [exec] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [exec] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [exec] 	at java.lang.Thread.run(Thread.java:745)
     [exec] 17:32:36,135 ERROR [localhost-startStop-1][ModuleFrameworkImpl:962] org.osgi.framework.BundleException: Could not resolve module: com.liferay.portal.osgi.web.wab.extender [29]
     [exec]   Unresolved requirement: Import-Package: com.liferay.osgi.util; version="[2.0.0,3.0.0)"`

**Comment by rotty3000** [comment]
Yup, patience!

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:stop

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:stop

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:stop

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
closing to clean up PR tester output

**Comment by sharonchoi** [comment]
POSHI test is failing due to a portal instance error, and is unrelated to changes made on this pull, will be investigating issue here: https://issues.liferay.com/browse/LRQA-25074 @kenjiheigel

**Pull request closed without merging**
