### PR TITLE
LPS-197569

### PR DESCRIPTION
**Pull request by alessandromalves**
https://issues.liferay.com/browse/LPS-197569

cc.: @ealonso @ccorreagg

### CODE REVIEW

**Comment by alessandromalves** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/14610

❌ ci:test:stable - 30 out of 31 jobs passed
❌ ci:test:relevant - 67 out of 73 jobs passed in 2 hours 15 minutes

**Comment by alessandromalves** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@ccorreagg @alessandromalves every Test in ResourceTest has to have an override annotation so I know which path you're testing.

**Comment by ccorreagg** [comment]
I commented the original PR with the same comment, but it seems it was too late

**Comment by ealonso** [comment]
see: https://github.com/brianchandotcom/liferay-portal/pull/144885

**Pull request closed without merging**
