### PR TITLE
LPS-97694 Add upgrade step for AB Testing

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@darquesdev for your case, can you make an UpgradeSchema.java class?

See

git ls-files **UpgradeSchema**

There are times we call a method upgradeSchema instead, and embed it in another Upgrade class, like 

apps/layout/layout-page-template-service/src/main/java/com/liferay/layout/page/template/internal/upgrade/v1_1_0/UpgradeLayoutPrototype.java#upgradeSchema

But I don't think that pattern is as good as the UpgradeSchema.java class because our update.sql file does quite a few tables (not just SegmentsExperience).

Please resend. Thx.

**Comment by darquesdev** [comment]
You're right. I was not very happy with the name either. I'll resend it today.

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
