### PR TITLE
Lps 52808

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
Fix for https://test-1-5.liferay.com/job/test-portal-pullrequest-backend%28master%29/group=6,label_exp=!test-1-5/149/testReport/junit/junit.framework/TestSuite/com_liferay_portal_kernel_nio_intraband_BaseIntrabandTest/

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
The previous failure is a known ElasticsearchSearchEngine OSGi registration race condition issue.

@mhan810 said we may get to it when we start to remove Lucene from codebase. So we can ignore it for now.

CC @rotty3000

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/743f6900ef...794c3434a2

**Pull request closed without merging**
