### PR TITLE
[TECHNICAL-SUPPORT] LPS-74998

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @chriskian @tinatian

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9d0ffb6941...0a09002f3b

**Comment by brianchandotcom** [comment]
@jonathanmccann @shuyangzhou doesn't that negatively affect performance? Since we're no longer caching by article,  but now by user and article. So if 1000 people view an article, we're now processing it in 1000 times.

**Comment by tinatian** [comment]
@brianchandotcom 
Yes, you are right, it causes performance regression, revert it in this pull : https://github.com/brianchandotcom/liferay-portal/pull/56200

**Pull request closed without merging**
