### PR TITLE
LPS-105156 

### PR DESCRIPTION
**Pull request by martamedio**
cc/ @stian-sigvartsen

### CODE REVIEW

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by martamedio** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/06666871c2...cb36696788

**Comment by brianchandotcom** [comment]
@martamedio @stian-sigvartsen see my changes in my origin.

Also, I don't think you should cache:

```
	@Activate
	protected void activate(Map<String, Object> properties) {
		OAuth2ProviderConfiguration oAuth2ProviderConfiguration =
			ConfigurableUtil.createConfigurable(
				OAuth2ProviderConfiguration.class, properties);

		int expiredAuthorizationsAfterlifeDuration =
			oAuth2ProviderConfiguration.
				expiredAuthorizationsAfterlifeDuration();

		_expiredAuthorizationsAfterlifeDurationMillis =
			expiredAuthorizationsAfterlifeDuration * Time.SECOND;
	}

	private long _expiredAuthorizationsAfterlifeDurationMillis;
```

Otherwise, when I change it in the GUI, it won't work until I reboot the server right?

**Comment by brianchandotcom** [comment]
@martamedio @stian-sigvartsen I suppose if it can't be updated from the GUI.. it's not that bad.. but if it can, it's a very strange user experience.

**Pull request closed without merging**
