### PR TITLE
LPS-196957 | Enable change tracking for country and region 

### PR DESCRIPTION
**Pull request by brookedalton**
https://liferay.atlassian.net/browse/LPS-196957

Manually forwarded from https://github.com/liferay-publications/liferay-portal/pull/716

[Test results](https://github.com/liferay-publications/liferay-portal/pull/716#issuecomment-1765513692):
✔️ ci:test:stable - 30 out of 30 jobs passed
❌ ci:test:relevant - 156 out of 209 jobs passed in 2 hours 49 minutes

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@brookedalton I don't see where the default is set to strict?

```Otherwise, the default value is STRICT.

See com.liferay.portal.kernel.change.tracking.CTColumnResolutionType for
available options.
````

Please resend.

**Comment by pei-jung** [comment]
@brianchandotcom the default is set to strict in the [ServiceBuilder](https://github.com/liferay/liferay-portal/blob/master/modules/util/portal-tools-service-builder/src/main/java/com/liferay/portal/tools/service/builder/ServiceBuilder.java#L6397-L6412).

```
<!--
The change-tracking-resolution-type value specifies how to resolve columns when
a modification conflict is detected when publishing. This value is only used
when change tracking is enabled for the entity. Some values are automatically
determined by column. Otherwise, the default value is STRICT.

See com.liferay.portal.kernel.change.tracking.CTColumnResolutionType for
available options.
-->
<!ATTLIST column
	change-tracking-resolution-type CDATA #IMPLIED
>
```

**Comment by pei-jung** [comment]
@brianchandotcom, the default is set in https://github.com/liferay/liferay-portal/blob/master/modules/util/portal-tools-service-builder/src/main/java/com/liferay/portal/tools/service/builder/ServiceBuilder.java#L6397-L6412. The value is hard-coded.

**Comment by pei-jung** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@brookedalton @pei-jung 

change-tracking-resolution-type="merge"

merge vs. STRICT

We should have the default and the value we set all be lower case or all upper case (lower case is probably prettier) and then we can upper case it during conversion.

Please resend.

**Pull request closed without merging**
