### PR TITLE
LPS-91413

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by jrao** [comment]
@adolfopa Let me know if you'd like me to refactor this to adhere to the SF rules about method names that are allowed to have a theme display parameter.

**Comment by adolfopa** [comment]
@jrao Sorry, missed the notification for this failure.

I'll send the changes myself. Thanks!

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/70112

**Pull request closed without merging**
