### PR TITLE
LPS-70253 Mark fields as required

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @ambrinchaudhary @sharonchoi

**Comment by ambrinchaudhary** [comment]
ci:reopen

**Comment by ambrinchaudhary** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@sergiogonzalez @ambrinchaudhary not merging, why can't the new Language.properties key be put in blogs-web instead of the global one? Please resend. Thx.

**Comment by ambrinchaudhary** [comment]
Resent: https://github.com/brianchandotcom/liferay-portal/pull/47457

**Pull request closed without merging**
