### PR TITLE
LPS-60022 move user links to the user tab

### PR DESCRIPTION
**Pull request by juliocamarero**
welcome_-_liferay

### CODE REVIEW

**Comment by juliocamarero** [comment]
@marcoscv-work I have added an "active" class to the link if we are in the Dashboard or the Profile but it doesn't have any effect. Could we add something to the theme?

**Comment by juliocamarero** [comment]
@evannagayama this is very likely to break functional tests, since the links to "Dashboard" "Profile" and "Sign out" are in a different location now.

**Comment by juliocamarero** [comment]
cc @ealonso

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1c730567b3...66f8c692a2

**Pull request closed without merging**
