### PR TITLE
LPS-55292

### PR DESCRIPTION
**Pull request by david-truong**
LPS-55292 sass-compiler-api

### CODE REVIEW

**Comment by david-truong** [comment]
ci:retest

**Comment by david-truong** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/16cf040559...03773a4f60

**Comment by brianchandotcom** [comment]
@david-truong please see my changes in upstream. Thx.

**Pull request closed without merging**
