### PR TITLE
LPS-81237 Rename methods, vars, keys ...

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by jpince** [comment]
@petershin why did this pass SF? I see this error at head:
```
     [java] 1: ./modules/apps/site/site-service/src/main/java/com/liferay/site/internal/initializer/SiteInitializerRegistryImpl.java expected:<...er> serviceWrapper :[ serviceWrappers) {]
     [java] 			SiteInitializer ...> but was:<...er> serviceWrapper :[
     [java] 				serviceWrappers) {
     [java] ]
     [java] 			SiteInitializer ...>
```
[Console](https://test-1-23.liferay.com/job/test-portal-acceptance-upstream-batch(master)/AXIS_VARIABLE=0,label_exp=!master/10457/console)

**Comment by petershin** [comment]
@jpince - It failed for me locally too.  Taking a closer look

**Comment by kyle-miho** [comment]
ci:stop

**Comment by petershin** [comment]
@jpince - Sent a patch to fix the SF issue: https://github.com/brianchandotcom/liferay-portal/pull/59244

**Pull request closed without merging**
