### PR TITLE
LPS-65512 Org list in 7 is flat, slow

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-65512](https://issues.liferay.com/browse/LPS-65512).<br><br>/cc @jorgeferrer @pei-jung

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:stop

**Comment by michaelhashimoto** [comment]
I broke this build and am restarting it.

Sorry for the inconveniences.

ci:restart

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/122e320af6...687931471f

**Comment by kenjiheigel** [comment]
@drewbrokke @JorgeFerrer, this causes quite a few test failures at head. @brianchandotcom said to revert the changes for now:
https://github.com/liferay/liferay-portal/compare/6a73b71a8452d3c452958bc085c265c7320669d1%5E...f84ce30d37adebd7053354e7ea5cffd144d3ad36

Please work with @alee8888 and @xbrianlee so that they can update the failing tests. Thanks!

**Comment by drewbrokke** [comment]
Will do.  Thanks @kenjiheigel.

**Pull request closed without merging**
