### PR TITLE
LPS-171748 It is no needed use ResourceBundleUtil since all of those keys are in portal-language-lang

### PR DESCRIPTION
**Pull request by alessandromalves**
This is only for master
https://issues.liferay.com/browse/LPS-171748
cc.: @ealonso @liulukiwi

### CODE REVIEW

**Comment by alessandromalves** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/10731

:heavy_check_mark: ci:test:stable - 28 out of 28 jobs passed
:x: ci:test:relevant - 237 out of 258 jobs passed in 3 hours 33 minutes

**Comment by alessandromalves** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/829c439332...0f143edf89

**Comment by brianchandotcom** [comment]
@ealonso see 0f143edf8936036061ffb510983924d3a9332b04

**Pull request closed without merging**
