### PR TITLE
LPS-56403

### PR DESCRIPTION
**Pull request by natecavanaugh**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@robertoDiaz 

PLease resend once

ResourceBundle resourceBundle = ResourceBundle.getBundle("content/Language", locale)

is automated via liferay-theme:defineObjects (I wrote about it in another pull)

Thx

**Comment by robertoDiaz** [comment]
Yes, i know, it's in my queue.

I hadn't send it to you that since it could produce rebase errors with other pulls de had sent you this week, and with other pulls se have in our local machines.

To avoid hard rebases I had planed to send this to you once all this code is pushed to máster.

Anyway, if you prefer to push that first, i'll prepare that on monday and I'll send it to you.

Sorry for the inconvenientes. ;)

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
