### PR TITLE
LPS-169220 No error message is displayed When a validation is not valid

### PR DESCRIPTION
**Pull request by diogomelo09**
[liferay-portal/pull/1447](https://github.com/liferay-objects/liferay-portal/pull/1447)

### CODE REVIEW

**Comment by diogomelo09** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c9e90dca28...7097160397

**Comment by brianchandotcom** [comment]
@diogomelo09 this doesn't make sense. Who is "us" that they are supposed to contact?

**Comment by brianchandotcom** [comment]
@diogomelo09 please resend, I did a partial merge. See my revert in 89d546439bf34ae978161d08087276b94ff8d5be

Please resend with a better message.

**Pull request closed without merging**
