### PR TITLE
COMMERCE-6312 Changed event name for DDMFormHandler as it was changed in DDMForm FE Impl

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:reopen

**Comment by gianmarcobrunialti** [comment]
Hey @brianchandotcom, this is a PR that I was requested to send directly to you by Rafaela Nascimento, in order to fix an event rename in the DDMForm implementation that was breaking Commerce FS options implementation. Thanks in advance!

**Comment by jpince** [comment]
@gianmarcobrunialti thank you!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a9386e7204...8a41a453ee

**Pull request closed without merging**
