### PR TITLE
LPS-105714 Update case to assert converted page type in view and edit mode

### PR DESCRIPTION
**Pull request by manoelcyreno**

### CODE REVIEW

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
ci:test:sf

**Comment by manoelcyreno** [comment]
ci:test:stable

**Comment by manoelcyreno** [comment]
Some errors are mapped to be fixed in the ticket: https://issues.liferay.com/browse/LRQA-54411

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7a2a59edc7...453ad0244a

**Pull request closed without merging**
