### PR TITLE
LPS-74831 Exports module packages

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6143d66dc0...b7f33bd247

**Comment by brianchandotcom** [comment]
@jbalsas merged, can you verify that b7f33bd247c2b89bd09b9a8cbba35e5596687a4f is OK? See comments. Thx.

**Comment by brianchandotcom** [comment]
Also, @jbalsas can you also rename this to frontend-chart/frontend-chart-taglib?

It feels better to me than just putting it as a generic charts app.

or even apps/foundation/frontend-taglib-chart

Actually, I'm going to roll this back in upstream until you resend it. Thx.

**Comment by brianchandotcom** [comment]
@jbalsas when you resend, please replay the original commits. Thx.

**Comment by jbalsas** [comment]
Hey @izaera, can you please apply this change and resend?

Thanks!

**Pull request closed without merging**
