### PR TITLE
master-en-682

### PR DESCRIPTION
**Pull request by evannagayama**
https://github.com/evannagayama/liferay-portal/pull/682

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 what happened here?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e5d0d3e331...31f64af953

**Comment by pyoo47** [comment]
This pull request test appears to have hung but there's no indication as to why.

@michaelhashimoto - The top-level build is still running. Can you take a look at see if there's any more information here that might reveal what happened? I don't think there's any but I don't think it hurts to leave it running a little longer so you have a chance to take look too.

**Comment by kiyoshilee** [comment]
@brianchandotcom @pyoo47 - yesterday the host for test-1-17, test-1-18, test-1-19, and test-1-20 went down. This pull was trying to download a json from test-1-19 and never received a response, it also never failed out for it. Those masters are back online now, but they also never would have sent a response back to this pull.

**Comment by michaelhashimoto** [comment]
@pyoo47 @brianchandotcom @kiyoshilee 

Sam Tran was able to fix it last night he said:
> the nic on that host malfunctioned, rebooting the host
> they're back online now

**Pull request closed without merging**
