### PR TITLE
[TS] LPS-195096 sort by title on Layout

### PR DESCRIPTION
**Pull request by joshuacords**
Tested here: https://github.com/liferay-search/liferay-portal/pull/1057

https://liferay.atlassian.net/browse/LPS-195096

**Author**: @joshuacords
**Reviewer**: @gustavolimav

For all Assets, [AssetEntryDocumentContributor](https://github.com/liferay/liferay-portal/blob/3eb74d2174290686650931d7518263eef612dbfd/modules/apps/asset/asset-service/src/main/java/com/liferay/asset/internal/search/AssetEntryDocumentContributor.java#L111-L116) will add the necessary localized_title_[locale]_sortable fields, but because Layouts aren't assets and don't use Titles, they need to be responsible for adding the field themselves.

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:test:reopen

**Comment by joshuacords** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f22cf4756f...7fa87c8fcb

**Comment by brianchandotcom** [comment]
@joshuacords see 7fa87c8fcbb40505665de442f6f49dd5abe9897c

**Pull request closed without merging**
