### PR TITLE
LPS-77325 Removes unnecessary default

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/64da95a83d...0caa4e7d7c

**Comment by brianchandotcom** [comment]
THanks @jbalsas for removing the unnecessary default :)

**Comment by jbalsas** [comment]
No problem! :)

**Pull request closed without merging**
