### PR TITLE
LPS-69271

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@shuyangzhou, I didn't get Java Heap error on my machine... I increased to 1024, we'll see if it passes on Jenkins now: https://github.com/brianchandotcom/liferay-portal/pull/44864/commits/4805c195eb733358b9658521ce3a535b352f9a90

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
@shuyangzhou, still Java Heap problem. Am I changing the wrong value?

**Comment by brianchandotcom** [comment]
@hhuijser I fixed the baseline for :apps:collaboration:document-library:document-library-web:baseline

Can you resend?

Thx.

**Comment by shuyangzhou** [comment]
@hhuijser you changed the wrong setting, it is in build.properties, junit.java.unit.gc=

**Pull request closed without merging**
