### PR TITLE
LPS-96424 Remove dead dynamic-data-mapping-form-renderer tests

### PR DESCRIPTION
**Pull request by wincent**
These tests were added in cf44741cebf77 ("LPS-71453 Add tests for dynamic-data-mapping-form-renderer", 2017-03-23) but depend on a gulpfile which no longer exists; seems that was removed in 80b970d0daefa ("LPS-71982 Remove gulp file and gulp dependencies from forms project to avoid node-sass dependency error", 2018-04-12).

I checked with @brunobasto and he confirmed for me that his team will soon be removing the code that these were testing, so these are safe to remove completely now.

### CODE REVIEW

**Comment by wincent** [comment]
Did "test:relevant" over here: https://github.com/brunobasto/liferay-portal/pull/1036 — only failure there is a pre-existing one.

**Comment by wincent** [comment]
ci:reopen

Reopening because SF failure is referring to a file that I didn't touch. Please let me know if I'm mistaken.

**Comment by wincent** [comment]
I believe the "test:relevant" failure is the same pre-existing one I've seen on other pulls today.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
