### PR TITLE
LPS-83560 - BaseLine

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test

**Comment by carloslancha** [comment]
ci:reopen

**Comment by carloslancha** [comment]
@john-co could you please take a look on this failure? It's working in local. Thx!

**Comment by john-co** [comment]
@carloslancha, QAE is looking into the npm failure. It's an error that has occured in other pulls recently so I don't think it's related. We'll recheck when the fix gets in.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8b3027cd83...d1e287da39

**Comment by brianchandotcom** [comment]
@carloslancha merged, I backported this to 7.1.x

**Pull request closed without merging**
