### PR TITLE
LPS-64094 Update assignee for KaleoLog

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
cc @marcellustavares

**Comment by pyoo47** [comment]
The above failure occurred because one of the slaves had a filesystem problem. I've reached out to IT and taken the slave offline. ci:retest

**Comment by marcellustavares** [comment]
thanks @leoadb

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3b2972c986...07b167185c

**Pull request closed without merging**
