### PR TITLE
LPS-89353 Bulk: Select All

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jbalsas there's a new var called "actionMode" but it's not read anywhere?

@ambrinchaudhary please resend. Thx.

**Comment by jbalsas** [comment]
Looks like @ambrinchaudhary and @4lejandrito went with a different one(`selectAll`) and didn't get rid of it in the form.

@ambrinchaudhary, @4lejandrito can you guys take care of that?

**Comment by 4lejandrito** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/67002.

**Pull request closed without merging**
