### PR TITLE
LPS-51819 Fix broken method comment links

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-51819](https://issues.liferay.com/browse/LPS-51819).<br><br>/cc @pei-jung

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/56623a402a...3da0ae5cf8

**Comment by brianchandotcom** [comment]
@drewbrokke nice job Drew, how did you even know there were problems?

**Comment by drewbrokke** [comment]
@brianchandotcom I was mostly getting irritated that there were still errors in my IDE :)

**Pull request closed without merging**
