### PR TITLE
LPS-109429 - Improve table-list css custom properties

### PR DESCRIPTION
**Pull request by edalgrin**
/cc @jbalsas @marcoscv-work

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:relevant

Restarting test, there was a network outage last night affecting CI.

**Comment by brianchandotcom** [comment]
@inacionery @shuyangzhou is this a workflow or an OSGi race condition error

https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/235307/AXIS_VARIABLE=0,label_exp=!master/testReport/junit/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_PortalSmokeUpgrade_ViewPortalSmokeArchiveAutoUpgrade730_/

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/36bbc3e9e7...0f5a6d22bc

**Comment by kenjiheigel** [comment]
@brianchandotcom, stable test failure is unrelated. PortalSmokeUpgrade#ViewPortalSmokeArchiveAutoUpgrade730 failure is caused by intermittent bug: [LPS-109105](https://issues.liferay.com/browse/LPS-109105)

**Pull request closed without merging**
