### PR TITLE
LPS-63659 WAB generator processing fails when WAR version is non-spec (e.g. maven syntax)

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ffb1b5538f...c9ee7b7a1c

**Comment by brianchandotcom** [comment]
@rotty3000 can we add a quick unit test for the tld and maven versions? Just so if support changes the regex in the future, we're protected.

Can you also resend c9ee7b7a1cb150c04dae332cbcc1ee557d5e76ac

Thx

**Comment by rotty3000** [comment]
what do you mean by tld?

**Comment by brianchandotcom** [comment]
@rotty3000 a test for _tldPackagesPattern and _versionMavenPattern

**Pull request closed without merging**
