### PR TITLE
LPS-190476 New type of Feature Flag: deprecation

### PR DESCRIPTION
**Pull request by thiago-buarqque**
Sending this directly because it has been weeks CI relevant doesn't pass (not related to my changes), stable is not stable, sometimes pass, sometimes don't, and SF test usually fails due to other people's changes (see [this](https://github.com/liferay-peds/liferay-portal/pull/235#issuecomment-1705322233) as example) and I have to wait until it's fixed to rebase, push it again and hopefully it passes.

Se previous PRs to check what I'm saying.

[#216](https://github.com/liferay-peds/liferay-portal/pull/216)
[#205](https://github.com/liferay-peds/liferay-portal/pull/205)

See [testray comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1693852357226&testrayRunIdA=2418030551&testrayRunIdB=2418438759) for more info regarding the errors

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:reopen

**Comment by thiago-buarqque** [comment]
Sending this directly because CI relevant doesn't pass for weeks (not related to my changes), stable is not stable, sometimes pass, sometimes don't, and SF test usually fails due to other people's changes (see [this](https://github.com/liferay-peds/liferay-portal/pull/235#issuecomment-1705322233) as example) and I have to wait until it's fixed to rebase, push it again and hopefully it passes.

**Comment by thiago-buarqque** [comment]
See [testray comparison run](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1693852357226&testrayRunIdA=2418030551&testrayRunIdB=2418438759) for more info regarding the errors

**Comment by brianchandotcom** [comment]
@thiago-buarqque @drewbrokke in a test, if you do

PrincipalThreadLocal.setName(user.getUserId());

you have to unset too

git grep original **Test.java

Or do it in a try finally since you only have one test

**Comment by thiago-buarqque** [comment]
ci:reopen

**Pull request closed without merging**
