### PR TITLE
LPS-74350 SF

### PR DESCRIPTION
**Pull request by inacionery**
/cc @jeyvison @vicnate5

### CODE REVIEW

**Comment by inacionery** [comment]
ci:test

**Comment by jpince** [comment]
ci:retest

**Comment by jeyvison** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/423484b2ea...af0b332172

**Comment by brianchandotcom** [comment]
Merged. See af0b332 thx.

**Pull request closed without merging**
