### PR TITLE
LPS-57982 fixes to the UI of the product menu

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @pat270

**Comment by brianchandotcom** [comment]
@juliocamarero smoke test is real. Please resend.

@marcoscv-work 

Thx

**Comment by pat270** [comment]
Including QA @kenjiheigel @brianwulbern

**Comment by brianwulbern** [comment]
@kenjiheigel @pat270 
I pushed the fix to @brianchiu here: https://github.com/brianchiu/liferay-portal/pull/629

**Comment by brianchiu** [comment]
I've pushed the changes to Brian Chan: https://github.com/brianchandotcom/liferay-portal/pull/29402

**Pull request closed without merging**
