### PR TITLE
LPS-87735 Pass mimeType param properly to the component and normalize it to supported canvas mimetypes

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:reopen

**Comment by jbalsas** [comment]
I think I closed it by mistake

**Comment by brianchandotcom** [comment]
@jbalsas please backport. Thx.

**Comment by jbalsas** [comment]
Sent -> https://github.com/liferay/liferay-portal-ee/pull/11285

**Pull request closed without merging**
