### PR TITLE
LPS-163216 Fix site templates content pages propagation

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-163216

@lfbesada

### CODE REVIEW

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/9758

:x: ci:test:stable - 24 out of 26 jobs passed
:x: ci:test:relevant - 172 out of 180 jobs passed in 3 hours 54 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/934412e127...2ad0a0aff3

**Comment by brianchandotcom** [comment]
@lfbesada for

```
			LayoutSet layoutSet = layout.getLayoutSet();

			if (layoutSet.isLayoutSetPrototypeLinkActive()) {
				UnicodeProperties updatedTypeSettingsUnicodeProperties =
					layout.getTypeSettingsProperties();

				if (originalTypeSettingsUnicodeProperties.containsKey(
						Sites.LAST_MERGE_LAYOUT_MODIFIED_TIME)) {

					updatedTypeSettingsUnicodeProperties.put(
						Sites.LAST_MERGE_LAYOUT_MODIFIED_TIME,
						originalTypeSettingsUnicodeProperties.getProperty(
							Sites.LAST_MERGE_LAYOUT_MODIFIED_TIME));
				}

				if (originalTypeSettingsUnicodeProperties.containsKey(
						Sites.LAST_MERGE_TIME)) {

					updatedTypeSettingsUnicodeProperties.put(
						Sites.LAST_MERGE_TIME,
						originalTypeSettingsUnicodeProperties.getProperty(
							Sites.LAST_MERGE_TIME));
				}
			}
```

do we need to call layout.setTypeSettings? Or is modifying the reference enough?

**Comment by lfbesada** [comment]
Hi @brianchandotcom 
When we modified the typeSettings the layout typeSettings is modified because its points to tha same memory position.
Regards

**Comment by brianchandotcom** [comment]
@lfbesada but isn't one a String and the other a Properties file? I assume it's because we're using the same LayoutImpl... and that it's not a DB issue.. just seems fishy.

I understand

```
	@Override
	public UnicodeProperties getTypeSettingsProperties() {
		if (_typeSettingsUnicodeProperties == null) {
			_typeSettingsUnicodeProperties = UnicodePropertiesBuilder.create(
				true
			).fastLoad(
				super.getTypeSettings()
			).build();
		}

		return _typeSettingsUnicodeProperties;
	}
```

in LayoutImpl. But we're not persisting this change. Changing _typeSettingsUnicodeProperties does not change LayoutImpl#typeSttings

This change only works because you're using a cached memory object. But should break on reboot of the portal (or if you clear the cache).

**Comment by lfbesada** [comment]
@brianchandotcom Yes, the layout type settings in memory are updated because of the LayoutImpl
I am sorry, I explained myself wrong. The typeSettingsProperties of LayoutImpl is updated when we update updatedTypeSettingsUnicodeProperties because it is the same memory location. But in the database, the layout is updated because, a few lines below, we are explicitly persisting the layout.
See: https://github.com/ozysouza/liferay-portal/blob/9745a2f3243f8843bddea313d6afd878508b5be7/modules/apps/layout/layout-content-page-editor-web/src/main/java/com/liferay/layout/content/page/editor/web/internal/portlet/action/PublishLayoutMVCActionCommand.java#L196

**Comment by brianchandotcom** [comment]
Got it. thanks @lfbesada !

**Pull request closed without merging**
