### PR TITLE
LPS-81343 Portlet 3.0: Support deployment of CDI bean portlets

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:reopen

**Comment by ngriffin7a** [comment]
ci:test:relevant

**Comment by ngriffin7a** [comment]
@brianchandotcom "This pull contains no unique failures."

**Comment by brianchandotcom** [comment]
@ngriffin7a see fa8a92d thx.

**Pull request closed without merging**
