### PR TITLE
LPS-84039

### PR DESCRIPTION
**Pull request by dejuknow**

### CODE REVIEW

**Comment by dejuknow** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@sergiogonzalez we may have a race condition, see

```
junit.framework.AssertionFailedError: 
Something went wrong attempting to register service method {contextName=sharing,contextPath=SharingEntry,actionObject=com.liferay.sharing.service.impl.SharingEntryServiceImpl@24eb1614,actionClass=class com.liferay.sharing.service.impl.SharingEntryServiceImpl,actionMethod=public void com.liferay.sharing.service.impl.SharingEntryServiceImpl.afterPropertiesSet(),path=/sharingentry/after-properties-set,method=POST} due to java.lang.NoSuchMethodException: com.sun.proxy.$Proxy621.afterPropertiesSet()
	at com.liferay.portal.log.assertor.PortalLogAssertorTest.scanXMLLogFile(PortalLogAssertorTest.java:174)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:100)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:90)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXMLLog(PortalLogAssertorTest.java:88)
```

**Comment by sergiogonzalez** [comment]
Hey @brianchandotcom this pull should fix it https://github.com/brianchandotcom/liferay-portal/pull/62198

**Comment by brianchandotcom** [comment]
@shuyangzhou I'm merging this to fix a race condition with the new sharing code, but can you review? I"m afraid it'll slow down the boot up time. Note this is master only.

@sergiogonzalez merged.

**Comment by brianchandotcom** [comment]
@shuyangzhou sorry for the noise, please review https://github.com/brianchandotcom/liferay-portal/pull/62198

**Comment by dejuknow** [comment]
resent: https://github.com/brianchandotcom/liferay-portal/pull/62204

**Pull request closed without merging**
