### PR TITLE
LPS-96012 HasColumnType should compare the type against the database

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
@brianchandotcom my guess is that module doesn't compile because the EE DB classes need to implement getSQLTypes() method and for that we have this pull:
https://github.com/brianchandotcom/liferay-portal-ee/pull/24891

**Comment by achaparro** [comment]
hey @jpince, should i send the reference to the master-private branch using the file git-commit-portal-private so that the test can pass?

Thanks

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6cabfc75f5...d22e01a9a7

**Comment by brianchandotcom** [comment]
@achaparro see my changes in upstream. I made quite a few tiny ones. Backported to 7.2.x, and I updated the hashes to private so we're good.

**Comment by jpince** [comment]
@achaparro in the future, yes you can do that in order to see passing tests. just write `DO NOT MERGE` or something obvious in the commit message, and BChan will drop that commit before he merges.

**Pull request closed without merging**
