### PR TITLE
LPS-107374 - Extract all IE-specific CSS to its own module

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by john-co** [comment]
ci:stop

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:sf

**Comment by brianchandotcom** [comment]
@julien please resend, keeps failing CI.

**Comment by julien** [comment]
@brianchandotcom yes of course. 
I'm surprised that those SF errors don't appear locally. I will check with @wincent

**Comment by wincent** [comment]
Added SF commit to @julien's fork here: https://github.com/julien/liferay-portal/commit/4207711e8d0649e5c9325e9cb178939ed710e90f

Sent https://github.com/brianchandotcom/liferay-portal/pull/85808 to eliminate the root cause (which led local project-level SF to appear fine to developer, but top-level SF in CI to disagree).

**Pull request closed without merging**
