### PR TITLE
COMMERCE-12621

### PR DESCRIPTION
**Pull request by Brunno0liveira**

### CODE REVIEW

**Comment by Brunno0liveira** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@brianikim @Brunno0liveira this looks wrong?

```
		String originalImgTag = StringBundler.concat(
			"<img alt=\"thumbnail\" class=\"aspect-ratio-bg-cover ",
			"aspect-ratio-item aspect-ratio-item-center-middle",
			"aspect-ratio-item-fluid card-type-asset-icon\" src=\"",
```

**Comment by brianikim** [comment]
@brianchandotcom ,

It looks correct to me.

**Comment by brianikim** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@brianchandotcom nope, it's wrong. Please resend. The code you sent won't make sense to a browser.

**Comment by brianikim** [comment]
Hi @brianchandotcom , I understand your concern and I tried my best to test the behavior.

I used both the screen-reader and inspected the HTML. It looks like the below in the HTML and the screen-reader acknowledged it just fine.

Am I missing something here in my testing?

```
<img alt="thumbnail" class="aspect-ratio-bg-cover aspect-ratio-item aspect-ratio-item-center-middleaspect-ratio-item-fluid card-type-asset-icon" src="/o/commerce-media/accounts/34010/images/34015?download=false">

```

**Comment by brianchandotcom** [comment]
@brianikim 

aspect-ratio-item-center-middleaspect-ratio-item-fluid

Is that right? If looks wrong to me.

**Comment by brianikim** [comment]
Hi @brianchandotcom , no that is 100% wrong. I am not sure how I missed that part. I was working under the impression of there being something wrong with my introduction of the `alt` tag. Let me resend right away.

**Comment by brianikim** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/143030

**Pull request closed without merging**
