### PR TITLE
[DO-NOT-MERGE] LPS-96627 Use our own annotations with graphQL

### PR DESCRIPTION
**Pull request by javiergamarra**
It was easier than I though, a couple of hours. LiferayArgumentBuilder is needed but LiferayBreadthFirstSearch and LiferayParentalSearch are due to a bug in the graphQL annotations library. I sent a PR, we will be able to remove those when, hopefully, he merges and releases a new minor version.

This has the drawback of having to support other annotations in the future but we are not generating more right now with the REST builder.

I want to check that all dependencies/test work fine. I can send 7.1 and other PRs.

### CODE REVIEW

**Comment by nhpatt** [comment]
Ok... failing because "com.liferay.portal.workflow.metrics", we'll have to change all modules at the same time, to remove the dependency with graphql annotations 7.0 now

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d2e2268834...20881750a3

**Comment by brianchandotcom** [comment]
I merged this and backported this to 7.2.x (but not to 7.1.x)

For 7.2.x, can you send me a revert of 8027e3fc6cd4140518cc46227ec78e6a059f1f61

I don't think that's needed anymore.

Can you send me a backport to 7.1.x? Thx.

**Comment by nhpatt** [comment]
Will do, thanks! :)

**Pull request closed without merging**
