### PR TITLE
LPS-78379 It should be add to Rest DropdownItem List

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by timpak** [comment]
@anthony-chu FYI, it looks like this will affect one of the POSHI test cases.

**Comment by anthony-chu** [comment]
thanks @timpak.

closing this pull request to test more locally. will resend with changes, if necessary.

cc @ealonso

**Comment by anthony-chu** [comment]
ci:close

**Comment by brianchandotcom** [comment]
@anthony-chu can you resend this to me with the Poshi changes? I'd like to get this in if possible. Thx.

**Comment by anthony-chu** [comment]
@brianchandotcom will do. i've let @ealonso know my findings on the pull. i'll send the changes once those findings are resolved.

**Pull request closed without merging**
