### PR TITLE
LPS-81769 As a Liferay administrator I want to import blogpost entries from my current system

### PR DESCRIPTION
**Pull request by alejandrohdezma**
Hey @brianchandotcom, I discussed with @JorgeFerrer this morning about how to deal with the "exposing the `userId`" situation and we came up with this proposal. For methods that are intended to be used for importing data into Liferay from our APIs, name them `import*` and don't expose them on JSON-WS. Then check the same permission we are using right now for the LAR export/import. What do you think?

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@ahdezma why don't you just call the Local service but do a permission check? 

You already have

```
	private void _checkViewPermission(
			Comment comment, PermissionChecker permissionChecker)
		throws PortalException {

		if (comment == null) {
			throw new NotFoundException();
		}
```

in CommentNestedCollectionResource

So in essence, you've already duplicated some of the permission checks. I think it's OK to do that to keep the *ServiceImpl leaner.

Now, BlogsEntryServiceImpl has:

```
	private static volatile PortletResourcePermission
		_portletResourcePermission =
			PortletResourcePermissionFactory.getInstance(
				BlogsEntryServiceImpl.class, "_portletResourcePermission",
				BlogsConstants.RESOURCE_NAME);
```
You'll have to rename that to the class you want to inject this instance into.

```
	private static volatile PortletResourcePermission
		_blogsPortletResourcePermission =
			PortletResourcePermissionFactory.getInstance(
				BlogPostingNestedCollectionResource.class, "_blogsPortletResourcePermission",
				BlogsConstants.RESOURCE_NAME);

```

Also, can you sort serviceContext.set* in your new code?

Thx.

**Comment by ahdezma** [comment]
ci:reopen

**Comment by ahdezma** [comment]
hey @brianchandotcom in the case of comments we had to perform the permission checker because the `CommentManager` does not perform permission checking: https://github.com/liferay/liferay-portal/blob/8fe6936c72cfc0e3370095e3eadd71d1482bf624/modules/apps/message-boards/message-boards-comment/src/main/java/com/liferay/message/boards/comment/internal/MBCommentManagerImpl.java#L134. The collab team told us that we have to do the permission checking in that case.

But this doesn't apply for this scenario, and it's going to be a common one with the new headless apis, so I don't think that separating the permission checking from the service implementation is a good idea for this cases.

Regarding your last recomendation I cannot understand what you are suggesting me to do, I didn't create that variable, that was already there in the service implementation. This is current master: https://github.com/liferay/liferay-portal/blob/8fe6936c72cfc0e3370095e3eadd71d1482bf624/modules/apps/blogs/blogs-service/src/main/java/com/liferay/blogs/service/impl/BlogsEntryServiceImpl.java#L794

Thanks :)

**Comment by brianchandotcom** [comment]
@ahdezma can you resend me this pull, but without adding any new methods to  BlogEntryServiceImpl. I'll add the permission check for you in the form while reusing their logic after you send me the pull. For now, just call the local.

Thx!

**Pull request closed without merging**
