### PR TITLE
LPS-71111 Use the proper property for the manual selection style

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:reopen

**Comment by matethurzo** [comment]
@brianchandotcom failing with unrelated problems.

**Comment by brianchandotcom** [comment]
@shuyangzhou major CI issues this morning :(

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/95d1ccecc0...30804f918b

**Comment by shuyangzhou** [comment]
@brianchandotcom yeah, I saw that, it killed my sync pull last night. It is some Kaleo failure. Did you push anything related last night?

**Pull request closed without merging**
