### PR TITLE
LPS-75316 SF

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @adolfopa

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d8c64f3f64...fa848ec50d

**Comment by brianchandotcom** [comment]
@sergiogonzalez @adolfopa please send me a backport. Thx.

**Pull request closed without merging**
