### PR TITLE
LPS-69826 Auto SF

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @carloslancha

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@alee8888 he default JVM time zone "America/Los_Angeles" is not UTC or GMT. this is happening in weblogic too. Please fix.

**Comment by brianchandotcom** [comment]
@sergiogonzalez please resend

modules/apps/collaboration/flags/flags-taglib/src/main/resources/content/Language.properties

has a lot of keys that are neither titles nor sentences.

Thx.

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
