### PR TITLE
LPS-97197 Regen

### PR DESCRIPTION
**Pull request by epgarcia**
@brianchandotcom @jpince do not backport

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
CC: @ealonso

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
See #75518

**Pull request closed without merging**
