### PR TITLE
LPS-101965 Increase service ranking.

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/be1094e385...78b0ed2dcb

**Comment by brianchandotcom** [comment]
@adolfopa can't this happen for all portlets?

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/82697

**Comment by brianchandotcom** [comment]
@adolfopa @cgoncas see better fix by @shuyangzhou in https://github.com/brianchandotcom/liferay-portal/pull/82697

**Pull request closed without merging**
