### PR TITLE
LPS-82568

### PR DESCRIPTION
**Pull request by Ithildir**
@petershin, can you please update the changelogs once this pull is merged? Thanks!

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:test

**Comment by Ithildir** [comment]
ci:reopen

**Comment by Ithildir** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@izaera I backported this to 7.1.x

7.0.x also uses the latest gradle plugins SDK, but I need you to backport any package*.json changes to 7.0.x

**Pull request closed without merging**
