### PR TITLE
LPS-77815 Renaming es.js file

### PR DESCRIPTION
**Pull request by 4lejandrito**
Hi @brianchandotcom,

The reason why I used underscores is because @natecavanaugh [changed it](https://github.com/brianchandotcom/liferay-portal/pull/55371/commits/7f89ae8a2396470e41549653b4f1313cbe94a7c6) in the initial pull request.

I have renamed it again using `lowercase and dashes` as it seems to be the pattern for `es.js` files that are not metal components ([example](https://github.com/liferay/liferay-portal/blob/master/modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-form-builder/src/main/resources/META-INF/resources/templates/data-provider-parameter.es.js#L27-L26)). Metal components are camel case ([example](https://github.com/liferay/liferay-portal/blob/master/modules/apps/web-experience/site-navigation/site-navigation-item-selector-web/src/main/resources/META-INF/resources/js/SelectSiteNavigationMenuItem.es.js#L24)). Also, amongst plain `*.js` files underscores are quite popular ([example](https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/navigation_interaction.js#L21)).

As you can see, naming `javascript` files is hard. Maybe @natecavanaugh can shed some light on this?

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c0b5ccd605...dcfdccd484

**Comment by brianchandotcom** [comment]
@natecavanaugh if I'm wrong, about the *.es.js file names, can you send a follow up pull?

@petershin can you double check that the dynamic include JSPs are in the right folder? Thx.

**Comment by natecavanaugh** [comment]
Heya guys, this one doesn't seem to be exporting a component (which we use CamelCasing to name), and instead appears to be a util type function being exported, in those cases, we use a dash-case to name the file. You can look at the [loop code](https://github.com/natecavanaugh/com-liferay-osb-loop-private/tree/7.0.x-private/osb-loop-web/src/main/js) to see how we handle the two cases. So this one is good to go :)

**Comment by petershin** [comment]
Hi @4lejandrito!

Regarding [BlogsAnalyticsFullContentJSPDynamicInclude.java](https://github.com/liferay/liferay-portal/blob/master/modules/apps/collaboration/blogs/blogs-analytics/src/main/java/com/liferay/blogs/analytics/internal/servlet/taglib/BlogsAnalyticsFullContentJSPDynamicInclude.java), since its hooking into another module, the jsp path should contain `com.liferay.blogs.web`

`/dynamic_include/com.liferay.blogs.web/full_content.jsp`

It'd also be better to extend the `BaseJSPDynamicInclude.java` to remove duplicate logic.

A good example of what it should look like is [GoogleNavigationPreJSPDynamicInclude.java](https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/login/login-authentication-google-web/src/main/java/com/liferay/login/authentication/google/web/internal/servlet/taglib/GoogleNavigationPreJSPDynamicInclude.java)

**Comment by 4lejandrito** [comment]
Hi @petershin,

After 9986efd00f3615756203e224ef0fb2bc4dd7d876 I thought this was the way to go and we have applied the same pattern for several analytics modules. 

Now I see the mistake was to use the same module id (com.liferay.blogs.analytics) instead of the one being contributed to (com.liferay.blogs.web). 

Next week I will change all the analytics modules to apply the correct pattern of adding the id of the module contributed to.

Thanks!

**Pull request closed without merging**
