### PR TITLE
LPS-63608 Update pages tree UI

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @evannagayama

**Comment by evannagayama** [comment]
@juliocamarero thank you!
@kmaria @asungutierrez this pr will change the way to add, edit, delete and also hide private pages unless it's added.

(see pr below for screenshots)
https://github.com/evannagayama/liferay-portal/pull/578

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5adb13a713...72c81b2503

**Comment by brianchandotcom** [comment]
@evannagayama I"m merging this in.. but this seems to break a few poshi tests, I'm not sure if those are random or not.

cc @brianchiu

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Pull request closed without merging**
