### PR TITLE
LPS-85157 If it is not necessary remove it instead of comment

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by ealonso** [comment]
cc: @jpince

**Comment by jpince** [comment]
ci:close @ealonso I'm fairly certain the smoke test failure is caused by this pull. PortalSmoke tests pass at head at the exact same commit that your pull rebased on https://test-1-1.liferay.com//userContent/jobs/test-portal-acceptance-upstream%28master%29/builds/4932/jenkins-report.html

@brianchiu @kyle-miho looks like a TF, can you please look into it?

**Comment by kyle-miho** [comment]
I'll look into this

**Pull request closed without merging**
