### PR TITLE
LPS-63588

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-63588.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by marcellustavares** [comment]
Thanks @jonmak08!

**Comment by jonmak08** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@jonmak08 too many broken poshi tests, please resend.

**Comment by jonmak08** [comment]
Sent to @kenjiheigel to update the Poshi tests.

New Pull Request: https://github.com/kenjiheigel/liferay-portal/pull/147

**Comment by kenjiheigel** [comment]
Resent:
https://github.com/brianchandotcom/liferay-portal/pull/36916

**Pull request closed without merging**
