### PR TITLE
LPS-62570 Upgrade lib sass

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
@david-truong @Ithildir after removing the wrong css everything seems to work fine in firefox too :)  :+1: 

welcome_-_liferay_and_1__node

**Comment by juliocamarero** [comment]
cc @clancha

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Hey @david-truong @Ithildir 

this seems to break a lot of things in the ci, but in my local machine everything looks fine and no errors...

**Comment by brianchandotcom** [comment]
@david-truong @juliocamarero @Ithildir  lots of errors :(

**Pull request closed without merging**
