### PR TITLE
LPS-61825 don't show actions in the tree that the user doesn't have permission to execute

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@juliocamarero this was green, but we have merge conflicts, rebase and resend? Thx.

**Pull request closed without merging**
