### PR TITLE
LPS-96209 Add upgrade process

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
cc: @achaparro

**Comment by achaparro** [comment]
@ealonso @jonathanmccann a loop of updates for those tables can be bad in performance, is there any way to do it in a single update?

Apart from this, and regarding the schemaVersion, the changes seem good to me but if we need to backport this (I guess we have to) we should backport this process first to 7.1:
https://github.com/brianchandotcom/liferay-portal/blob/edb8877c94ec6d412bb1b9df853eb5d5b12e407f/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/internal/upgrade/JournalServiceUpgrade.java#L189

This process is pending to be rebased (see https://issues.liferay.com/browse/BPR-22861) but @RobertoDiaz is in paternity leave we will need to take care of it. Please, @jonathanmccann come over when you have some time to discuss how to work on this.

Thanks.

**Comment by achaparro** [comment]
ci:reopen

**Comment by achaparro** [comment]
After talking to @jonathanmccann we don't expect to have a lot of records with / or . so there won't be performance issues.

We reopen the ticket.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
