### PR TITLE
LPS-54427

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@rotty3000, @shuyangzhou fyi

**Comment by brianchandotcom** [comment]
@mhan810 can you resend on top of https://github.com/mhan810/liferay-portal/pull/312

You added a bunch of code to PortalImpl that is never used. Not sure if that was on purpose or not.

**Comment by rotty3000** [comment]
Hey Mike, since you're starting vacation I can take care of this. I'll get
to it Monday.

On Fri, Mar 27, 2015 at 9:00 PM, Brian Chan <notifications@github.com>
wrote:

> Closed #25223
> <https://github.com/brianchandotcom/liferay-portal/pull/25223>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/25223#event-267406387>
> .
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by mhan810** [comment]
No it's ok I'll pull it down and take a look...still working tonight ;)



*From:* Raymond Augé [mailto:notifications@github.com]
*Sent:* Friday, March 27, 2015 8:05 PM
*To:* brianchandotcom/liferay-portal
*Cc:* Michael Han
*Subject:* Re: [liferay-portal] LPS-54427 (#25223)



Hey Mike, since you're starting vacation I can take care of this. I'll get
to it Monday.

On Fri, Mar 27, 2015 at 9:00 PM, Brian Chan <notifications@github.com>
wrote:

> Closed #25223
> <https://github.com/brianchandotcom/liferay-portal/pull/25223>.
>
> --
> Reply to this email directly or view it on GitHub
> <
https://github.com/brianchandotcom/liferay-portal/pull/25223#event-267406387
>
> .
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
(@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
(@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

--
Reply to this email directly or view it on GitHub
<https://github.com/brianchandotcom/liferay-portal/pull/25223#issuecomment-87135286>
.

**Pull request closed without merging**
