### PR TITLE
LPS-61533 dont' show personal menu when the user is not fully ready

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest (we just fixed a CI issue that wasn't retesting)

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@juliocamarero those poshi errors are real? Please resend.

**Pull request closed without merging**
