### PR TITLE
LPS-98616 Creates a new method on the layout data to get the JSONObject and move the code to it

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a2e971978c...c5622961e8

**Comment by brianchandotcom** [comment]
@ealonso please see my changes in upstream

@preston-crary can you review modules/apps/layout/layout-impl/src/main/java/com/liferay/layout/internal/template/util/LayoutConverterRegistryImpl.java from this pull? I have a feeling you're going to change the OSGi registration process a bit.

**Comment by brianchandotcom** [comment]
lbm:backport @CsabaTurcsan @jpince @zsoltbalogh

@ealonso I did not backport, leaving it to you.

**Comment by Preston-Crary** [comment]
@brianchandotcom is new in the pull and does not have any usages. I would just remove it and use a ServiceTrackerMap when we know where it'll be used instead of having the API.

**Comment by Preston-Crary** [comment]
@ealonso if it has more than one usage it's okay.  Can you use a ServiceTrackerMap instead of the component registration, see https://github.com/liferay/liferay-portal/blob/master/modules/apps/captcha/captcha-api/src/main/java/com/liferay/captcha/util/CaptchaUtil.java#L127 for an example.

**Pull request closed without merging**
