### PR TITLE
LPS-72732 Extract DLProcessorRegistryImpl into module

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by drewbrokke** [comment]
Hey @brianchandotcom, this pull is a prerequisite for me to finish https://issues.liferay.com/browse/LPS-69208.  If you have time, could you please review it soon?  Thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/082b4bc6b9...8b310bcb11

**Comment by brianchandotcom** [comment]
@drewbrokke I backported this.

**Comment by drewbrokke** [comment]
Thanks @brianchandotcom!

**Pull request closed without merging**
