### PR TITLE
Upgrades: extensible framework to provide connections to upgrades. This way we could move the SQL Server related code to the EE repo

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by migue** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ba0b92fc91...8b2238bdef

**Comment by brianchandotcom** [comment]
@cgoncas @migue please send me a pull for ee-7.0.x now. Thx.

**Comment by migue** [comment]
Sure, we already have done it

**Pull request closed without merging**
