### PR TITLE
LPS-99879, LPS-99221 Update dependencies

### PR DESCRIPTION
**Pull request by wincent**
Supersedes: https://github.com/brianchandotcom/liferay-portal/pull/77079

- Updates our react-dnd dependencies (going to the latest releases in the 7.x series) in order to obtain a bugfix as noted [here](https://github.com/liferay/liferay-frontend-guidelines/issues/64).
- And also forces clay-css v2.17.0 into the lockfile so that we can get access to newly added icons.

### CODE REVIEW

**Comment by wincent** [comment]
Note: the SF failures are expected because we are not supposed to add new devDependencies, except, of course, when we have to. @jbalsas approved this approach.

**Comment by brianchandotcom** [comment]
@hhuijser how can I merge this?

@wincent won't this mean SF will keep breaking once I merge in your fix? Please resend after coordinating with @hhuijser

**Comment by jbalsas** [comment]
We need to add the exclusion for this module, which should be okay since it's really needed here

**Comment by wincent** [comment]
I just sent https://github.com/brianchandotcom/liferay-portal/pull/77093 that suppresses this check for this file. I also created https://issues.liferay.com/browse/LPS-99901 to cover making the suppression more granular.

**Pull request closed without merging**
