### PR TITLE
Lpd 27237

### PR DESCRIPTION
**Pull request by shuyangzhou**
@tinatian @vicnate5 please backport for LXC, thanks!

@victorhcunha please run a check for login case, thanks!

CC @slnn

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5b2084e8fc...324dae7e90

**Comment by brianchandotcom** [comment]
@shuyangzhou can you resend this and move

portal-kernel/src/com/liferay/portal/kernel/template/LazyValue.java

to petra-function ? Perhaps call this SupplierValue or SupplierValueWrapper or SupplierWrapper

Why? I can see us using this in many places going forward.

Please resend on top of https://github.com/shuyangzhou/liferay-portal/pull/11523

Thx!

**Comment by victorhcunha** [comment]
Hi @shuyangzhou !
Here are the results for login testcase:

Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | DB CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | --
Baseline | 501f884 | 9516 | - | 295 | 3,5,3 | 93,93,92
PR | - | 9682 | 1.744430433 | 296 | 3,3,3 | 94,94.93

More details you can see in our [spreadsheet](https://docs.google.com/spreadsheets/d/1M6VK8GtY9kkv1EwhGW7vwrEENSzyT7zKz-wOh11ZHBo/edit#gid=147138594)

**Comment by shuyangzhou** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/150919

No need to rerun on your side @victorhcunha , thanks!

**Pull request closed without merging**
