### PR TITLE
LPS-130606 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-130606

This is only for master.

@victorg1991

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure cases are unrelated to changes in this PR.
See https://github.com/liferay-echo/liferay-portal/pull/5031
✔️ ci:test:stable - 10 out of 10 jobs passed
❌ ci:test:relevant - 20 out of 27 jobs passed in 1 hour 55 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1b422843df...7796a8fa06

**Comment by brianchandotcom** [comment]
@victorg1991 see 7796a8fa06fcf03f0a57ec57e4db9f701dd978d2 thx

**Pull request closed without merging**
