### PR TITLE
LPS-82961 Complete WebPageElement API

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bfe0d37cf2...04767664b8

**Comment by brianchandotcom** [comment]
@nhpatt see b035ea43a178461e0c82f2dedf26b1d0033b4f70 in master

also, note that I have to backport this to 7.1.x and the build.gradle points to released artifacts. this is getting more and more difficult for me to backport. fyi.

**Comment by nhpatt** [comment]
Thank you for the hard work :( 

We can do the cherrypick ourselves and send the PR to the 7.1.x branch if you want.

We don't have many more PRs with so many changes in the near future.

**Pull request closed without merging**
