### PR TITLE
Logical Partitioning: Upgrade process and default values for the companyId

### PR DESCRIPTION
**Pull request by migue**
/cc @cgoncas

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest (I"m just retesting to be safe, I'll ask Shuyang later what's wrong with the random Oracle PACL test)

**Comment by brianchandotcom** [comment]
That was a bad slave... ci:retest

@kiyoshilee can you see what's wrong with that slave? Thx.

**Comment by cgoncas** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@migue @cgoncas I didn't get a chance to do it today, but will tomorrow.

@migue there's also a rebase error, if you have time, can you rebase and resend. If not, don't worry, I'll take care of it tomorrow.

**Comment by migue** [comment]
@brianchandotcom We've already rebased, will send it again as soon as I can

**Pull request closed without merging**
