### PR TITLE
LPS-145145 search-experiences-web: Preview: render result title from calculated field "assetTitle"

### PR DESCRIPTION
**Pull request by thektan**
https://issues.liferay.com/browse/LPS-145145

cc @oliv-yu

### CODE REVIEW

**Comment by thektan** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/506b69d264...ba9d89baaf

**Comment by brianchandotcom** [comment]
@thektan please make sure any js unit tests pass or else stable won't sync.

**Comment by thektan** [comment]
@brianchandotcom Will do, they seem to be passing on my end, but I'll check again.

**Comment by brianchandotcom** [comment]
@thektan yeah, just me being paranoid.

**Pull request closed without merging**
