### PR TITLE
LRQA-36332 | master

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-36332

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:reopen

**Comment by xbrianlee** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@mtambara unit is always breaking now. I think its from your recent change.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/49e055aed0...7c7add12aa

**Pull request closed without merging**
