### PR TITLE
Review: timeout during setupInitialBundles

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by shuyangzhou** [comment]
@robertoDiaz @migue This is not the right solution.
With this change the latch will quietly open if initial bundles do not finish initialization after 30sec(which most likely could happen on CI due to its slowness). Then portal proceeds to startup which will lead to unpredictable state.

When the hanging happens, which just means something really bad happened in those initial bundles, which requires an immediate attention, we should not cover this by letting the portal to continue starting up.

In the original ticket, it did not say anything about why the hanging was happening at all. We should revert this change and look into the real cause about the hanging.

**Comment by brianchandotcom** [comment]
@shuyangzhou @robertoDiaz reverting...

**Pull request closed without merging**
