### PR TITLE
LPS-116922 - Test Scenarios Coverage | Backend 

### PR DESCRIPTION
**Pull request by liulukiwi**
//cc @ealonso @ruben-pulido

### CODE REVIEW

**Comment by liulukiwi** [comment]
For saving CI resource, send it directly to you, this is a resend for https://github.com/brianchandotcom/liferay-portal/pull/91605.

**Comment by liulukiwi** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/60a2548aa5...52b20c8c60

**Comment by brianchandotcom** [comment]
@liulukiwi see 52b20c8c605062e36e6902b69b41838db8afba14

**Pull request closed without merging**
