### PR TITLE
LPS-101274 Add support for domains in accounts to allow restricting user creation to specific domains

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by pei-jung** [comment]
Closing to fix conflicting error. Will resend

**Comment by pei-jung** [comment]
Resent as https://github.com/brianchandotcom/liferay-portal/pull/79965

**Pull request closed without merging**
