### PR TITLE
LPD-36689 Extract some properties/config into a separate entity

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@IstvanD @achaparro 1.) can you change

storage.*

to

document.library.storage.*

2.)

return "Unable to determine";

sounds weird (hope it's part of a sentence).

Please resend.

**Comment by achaparro** [comment]
ci:reopen

**Comment by achaparro** [comment]
@brianchandotcom reopened after our conversation in slack

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c7e1277d4f...363696a109

**Comment by brianchandotcom** [comment]
@IstvanD @achaparro just 543094ca9ff9f2969b205f465ffb8228767455fc and 363696a109e9d9eb505d34f691917cf0e28e0cc2

**Pull request closed without merging**
