### PR TITLE
LPS-77926 SF

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2ac24ced6c...53eedc4c48

**Comment by brianchandotcom** [comment]
See 53eedc4c481a7b90ea8dc92d53b56ec70d4dd3c2 thx.

**Comment by jbalsas** [comment]
Hey @brianchandotcom, the ellipsis was part of the message provided by UX. 

@julien, could you please send another commit re-adding them and making it clear in the commit message why we are doing it?

Thanks!

**Comment by julien** [comment]
@jbalsas yes of course.

I submitted it here https://github.com/brianchandotcom/liferay-portal/pull/56384

**Pull request closed without merging**
