### PR TITLE
LPS-80728 Use serviceBuilder to automatically generate the correct lang key for each UAD module

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-80728](https://issues.liferay.com/browse/LPS-80728).<br><br>Hey Brian, this is the last step in translating the application names for the UAD components.  It removes getApplicationName as an API method on the interface and instead relies on the new util in the web module.  It also copies the portlet title translations to the uad module of each app from its web module.  Please let me know if you have any questions.<br><br>/cc @pei-jung @dejuknow

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
