### PR TITLE
LPS-142544 Site Initializer - integration tests

### PR DESCRIPTION
**Pull request by joseabelenda**
- LPS-140847 Create _assertUpdateLayoutSet
- LPS-140847 Avoid NPE on delete objectDefinition
- LPS-140847 wrap GroupLocalServiceUtil.deleteGroup(group) and bundle.uninstall() in finally block
- LPS-140847 add LayoutSet resources
- LPS-140847 Rename _assertUpdateLayoutSets to _assertLayoutSets
- LPS-140847 Fix _assertLayoutSet
- LPS-140845 Create assertCPDefinitions
- LPS-140839 Create _assertRoles
- LPS-140847 Unused code removed
- LPS-140849 Create _assertJournalArticles
- LPS-140849 Simplify
- LPS-140840 Create _assetPermissions, _assertResourcePermissions
- LPS-140848 Create _assertAssetListEntries
- LPS-140848 Use Test Role 1
- LPS-140848 Sort
- LPS-140848 Rename
- LPS-140848 Nomenclature fixes
- LPS-142544 Create _assertCommerceNotificationTemplate Integration Test
- LPS-142544 Standardize
- LPS-142544 Rename
- LPS-142544 Singular

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a9262a7da8...82dbb876ed

**Comment by brianchandotcom** [comment]
Very very nice @joseabelenda @gleicelisbino @nicolas-sss !

Just 8be2a368debc069ea956e75ddd38b154ccb1a174 344c801490c2335fdad812807dc1f871deddc14a and 82dbb876edd927ad49fc1919e43fde6a4c3e0669

**Comment by nicolas-sss** [comment]
Thank you, @brianchandotcom !

**Comment by gleicelisbino** [comment]
Thank you very much, @brianchandotcom :)

**Pull request closed without merging**
