### PR TITLE
LPS-60740 DDM service upgrade

### PR DESCRIPTION
**Pull request by achaparro**
Already reviewed by @marcellustavares 

Tested with a customer database using Oracle.

Thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by marcellustavares** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/419e91e63f...9df3d8b3fb

**Pull request closed without merging**
