### PR TITLE
LPS-107646

### PR DESCRIPTION
**Pull request by petershin**
@amosfong @nhpatt

### CODE REVIEW

**Comment by amosfong** [comment]
thanks @petershin !

**Comment by brianchandotcom** [comment]
Nice @amosfong :)

**Comment by brianchandotcom** [comment]
Thx for the refactor @petershin !

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ae6b7c8461...3dda3a60c5

**Pull request closed without merging**
