### PR TITLE
LPS-55637

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/24ba478dc5...f61447d614

**Comment by brianchandotcom** [comment]
@mhan810 please review my changes in upstream? Thx.

**Comment by brianchandotcom** [comment]
@ehan there was a lot of unnecessary code. See upstream. Thx.

**Comment by mhan810** [comment]
Ah it was left over configs from service builder which I removed to
simplify.  Ed had migrated with SB which required those extra configs.  I
didn't remove those when I took out SB.

Sent from my mobile device.

**Pull request closed without merging**
