### PR TITLE
#ping1 [See description] LPS-57706 Message Boards follow up

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey Brian,

This pull is the follow up of Message boards.

It also includes 2 bug fixes in different LPS but I included them here because otherwise it may have conflict errors: https://issues.liferay.com/browse/LPS-57704 and https://issues.liferay.com/browse/LPS-57706

Thanks

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@sergiogonzalez regarding LPS-57706 can you proactively scan and see if we have others like it for those taglibs that are very similar? Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e7edd9fc18...b39e823f77

**Comment by brianchandotcom** [comment]
@sergiogonzalez please see my rename to MBPortletKeys.

We can still have MessageBoards*.java, but that's for things that are specific to the portlet named Message Boards or Message Boards Admin.

Thx.

**Comment by brianchandotcom** [comment]
@sergiogonzalez I also renamed MBWebUpgrade.. and noticed it's not wired for dependencies.

Can you check DLWebUpgrade as well. In all the other upgrades, we tell the Portlet to not launch until the Upgrade is launched. See AmazonRankingsPortlet.

Thx.

**Pull request closed without merging**
