### PR TITLE
COMMERCE-7583 Use languageIdMap instead

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by Commando18** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@Commando18 are there more cases like this?

**Comment by brianchandotcom** [comment]
fyi @marco-leo the language map was a bug. See fix by @Commando18 

I'm asking him to find other places like this.

**Comment by Commando18** [comment]
@brianchandotcom Yes, we have 1 occurrence for sure, since I copied it from an existing DTO converter. I will check them all, thanks.

**Pull request closed without merging**
