### PR TITLE
LPS-84292 Fix test after ca0350ca91d0d6c22539c61b5d9157e32a95cf0f

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@leoadb fyi

**Comment by jeyvison** [comment]
I'll take a look on these failures

**Comment by jpince** [comment]
@jeyvison please also fix semver
`com.liferay.dynamic.data.mapping.io                MINOR      1.0.0      1.0.0      1.1.0      VERSION INCREASE REQUIRED`

@tomwang2011 thanks!

**Pull request closed without merging**
