### PR TITLE
LPS-64421 PortletRequestDispatcher.forward(PortletRequest,PortletResponse) does not forward to the specified JSP

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by juangon** [comment]
BTW this pull fixes https://issues.liferay.com/browse/LPS-64649 and https://issues.liferay.com/browse/LPS-64726

**Comment by rotty3000** [comment]
Good point! attaching the PRs to those issues.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c6dfa24cde...03835f47c3

**Pull request closed without merging**
