### PR TITLE
LPS-66227 Source Formatting

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by pyoo47** [comment]
This pull request test was held up by a single axis that appears to have frozen while running the PACLAggregate test. I've manually aborted that test so the rest of the PR Test can complete normally.

**Comment by marcellustavares** [comment]
@pyoo47 😢

**Comment by brianchandotcom** [comment]
@marcellustavares those are unrelated, should be fixed in upstream already.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d10495d049...44f495f9bd

**Pull request closed without merging**
