### PR TITLE
LPS-61586 Update empty result message

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@ealonso resent it to myself here https://github.com/brianchandotcom/liferay-portal/pull/35173

**Pull request closed without merging**
