### PR TITLE
LPS-78288

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@arboliveira

See https://github.com/brianchandotcom/liferay-portal/pull/55832/commits/f0fc5acdd5e995ea3d4e389fa4a562ce973e2e25 and https://github.com/brianchandotcom/liferay-portal/pull/55832/commits/11fc5e44d8675bb9cfcfbfc86035c28668f506d1.
It looks like the order if those constants matter since CalendarBookingIndexerIndexedFieldsTest.testIndexedFields will fail if I order them. See https://github.com/brianchandotcom/liferay-portal/pull/55729

I looked into it a for a bit (not too long...)  and couldn't figure out why the ordering matters for that one.

**Comment by hhuijser** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@hhuijser can you send me a 7.0.x?

**Pull request closed without merging**
