### PR TITLE
LPS-101167 Using ClaySlider on AB Test UI

### PR DESCRIPTION
**Pull request by andresfulla**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/863c03c665...cf833e7934

**Comment by brianchandotcom** [comment]
@andresfulla 

```
import React from 'react';
import PropTypes from 'prop-types';
import ClaySlider from '@clayui/slider';
```

Can you send a follow up pull to sort these?

@jbalsas @wincent we should either sort imports, or add a line break if order matters. Please auto enforce everywhere.

@andresfulla also, your LPS ticket in this pull does not match the commit ID. In the future, they should match.

**Comment by dgarciasarai** [comment]
This is the LPS ticket: https://issues.liferay.com/browse/LPS-101765.

**Comment by jbalsas** [comment]
Hey @brianchandotcom! We have imports sorting lined up with some other auto-enforcements to apply them right after SP1. We’ll send a general PR soon after we cut SP1.

**Comment by andresfulla** [comment]
@brianchandotcom thanks, I messed those ticket ids up. I'll resend with sorted imports.

**Pull request closed without merging**
