### PR TITLE
liferay-aui.tld attribute description for translation manager - take 2

### PR DESCRIPTION
**Pull request by jhinkey**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7d18ad48f9...5bf851edf9

**Comment by brianchandotcom** [comment]
@jhinkey don't you have to change both files? Or regenerate?

**Comment by jhinkey** [comment]
Yes, you're absolutely right. I'll do that now and resend. Thanks, Brian.

**Comment by jhinkey** [comment]
The way I understand the AUI taglibs is that the developer has to add
the tag description to the aui.xml file. Then the build-taglibs target
generates the liferay-aui.tld. But no one ever added the
translation-manager tag to the aui.xml.

I'm following up with the developer on this.

Thanks,
Jim

On 2/3/2016 4:13 PM, Brian Chan wrote:
>
> @jhinkey <https://github.com/jhinkey> don't you have to change both
> files? Or regenerate?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/35482#issuecomment-179471254>.
>

-- 
Jim Hinkey
Sr. Knowledge Engineer
Liferay, Inc.
www.liferay.com <http://www.liferay.com>

Visit Us: www.liferay.com <http://www.liferay.com> | Like Us:
facebook.com/liferay <http://facebook.com/liferay> | Follow Us:
twitter.com/liferay <http://twitter.com/liferay>

**Pull request closed without merging**
