### PR TITLE
LPS-167797 Check the VIEW permission to allow "View Usages" action

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

cc @lfbesada 

Original comment:

https://issues.liferay.com/browse/LPS-167797

See: https://github.com/brianchandotcom/liferay-portal/pull/125912#issuecomment-1308483955

### CODE REVIEW

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/10228

:heavy_check_mark: ci:test:stable - 26 out of 26 jobs passed
:x: ci:test:relevant - 197 out of 201 jobs passed in 2 hours 35 minutes

**Comment by ozysouza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@lfbesada for

```
		if (ModelResourcePermissionUtil.contains(
				themeDisplay.getPermissionChecker(),
				layoutClassedModelUsage.getClassName(),
				layoutClassedModelUsage.getClassPK(), ActionKeys.VIEW)) {

			jsonObject.put(
				"viewUsagesURL",
				() -> PortletURLBuilder.create(
					PortletURLFactoryUtil.create(
						httpServletRequest,
						ContentPageEditorPortletKeys.
							CONTENT_PAGE_EDITOR_PORTLET,
						PortletRequest.RENDER_PHASE)
				).setMVCPath(
					"/view_layout_classed_model_usages.jsp"
				).setParameter(
					"className", layoutClassedModelUsage.getClassName()
				).setParameter(
					"classPK", layoutClassedModelUsage.getClassPK()
				).setWindowState(
					LiferayWindowState.POP_UP
				).buildString());
		}
```

When I said function, I meant

```
jsonObject.put(
	"viewUsagesURL",
	() -> {
		if (!ModelResourcePermissionUtil.contains(
				themeDisplay.getPermissionChecker(),
				layoutClassedModelUsage.getClassName(),
				layoutClassedModelUsage.getClassPK(), ActionKeys.VIEW)) {

				return null;
		}

		return PortletURLBuilder.create(
			PortletURLFactoryUtil.create(
				httpServletRequest,
				ContentPageEditorPortletKeys.
					CONTENT_PAGE_EDITOR_PORTLET,
				PortletRequest.RENDER_PHASE)
		).setMVCPath(
			"/view_layout_classed_model_usages.jsp"
		).setParameter(
			"className", layoutClassedModelUsage.getClassName()
		).setParameter(
			"classPK", layoutClassedModelUsage.getClassPK()
		).setWindowState(
			LiferayWindowState.POP_UP
		).buildString())
	};
```

That way, you can keep all the logic inside the put and it keeps it quite clean.

**Comment by brianchandotcom** [comment]
@lfbesada it allows you to keep chaining as well..

```
jsonObject.put(
).put(
).put(
)
```

**Comment by lfbesada** [comment]
Hi @brianchandotcom I didn't do that to prevent checking the Update permission twice, for editURL and editImage.
But I'll check it once and save it to a variable even though I do that outside of the function and then I will use the JSONUtil.
Thanks for the tips!

**Pull request closed without merging**
