### PR TITLE
[TS] LPS-168238 Site names' xml include incorrect locales configuration after upgrade if the site is configured to inherit locales from the instance

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

cc @jorgediaz-lr @ealonso

Original comment:

https://issues.liferay.com/browse/LPS-168238

The solution implemented in [LPS-146669](https://issues.liferay.com/browse/LPS-146669) is not correctly handling the site locales when they are inherited from the instance, it only works when the locale is not inherited

I have done following changes:

1. I have changed the SQL to include the companyId and the company default languageId. (_The company default languageId is retrieved from the default user of the company_)
2. By default, the site default language id and site locales are obtained from the instance
3. If **inheritLocales=false**, I am getting the site configuration from `typeSettingsUnicodeProperties`
4. If any data don't exist in the typeSettingsUnicodeProperties, as a fallback I am using the data obtained from the instance. (The [LPS-162783](https://issues.liferay.com/browse/LPS-162783) added as fallback a call to `LocaleUtil.getSiteDefault()` but that method always return en_US during upgrade process 😓

### CODE REVIEW

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/10243

:heavy_check_mark: ci:test:stable - 27 out of 27 jobs passed
:x: ci:test:relevant - 118 out of 168 jobs passed in 3 hours 51 minutes

**Comment by ozysouza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c53168ffd4...1ca5ef28db

**Comment by brianchandotcom** [comment]
Very nice @jorgediaz-lr can you send an integration test for this?

**Pull request closed without merging**
