### PR TITLE
Lps 64056

### PR DESCRIPTION
**Pull request by shuyangzhou**
@jorgeferrer please see https://github.com/brianchandotcom/liferay-portal/commit/5ed80aa0db124e74c74e31c0b1e5c52001ed90bb, I could not trace back who added that line for what reason, the git history stopped due to the project layout changes. Please check whether it will be a problem to remove it. I have to do it due to it embeds the Configurable class, which is not the one other modules use, which makes the ConfigurationUtil unusable. Portal is already providing all class it includes here, I don't see a reason that it has to keep a private copy, and CI does not complain it either. But please double check anyway.

CC @mhan810

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@Ithildir I think @shuyangzhou was referencing a commit you might have done as part of the Bnd optimization....

**Comment by brianchandotcom** [comment]
@jorgeferrer I was under the assumption that everyone who uses this would also portal-configuration-metatype

But if you look at the change from @shuyangzhou, almost every build.gradle that uses this switched from bnd.util to portal-configuration-metatype, which means they were never bundled together to begin with and should be separate modules.

See modules/apps/foundation/portal-configuration/portal-configuration-settings/build.gradle

But if you do really want it in this pull, please comment to @shuyangzhou  and let him know.

@shuyangzhou if @jorgeferrer really does want it split, can you move it to com.liferay.portal.configuration.metatype.bnd.util

That way it preserves the package/bundle name pattern we have. 

Thx

Also, @shuyangzhou in any case, can you send me a pull just to fix how you did bnd-util based on your earlier comments of removing the inclusion of its own bnd jar? Thx.

**Comment by Ithildir** [comment]
Hi @brianchandotcom, that line was already there when I made the Bnd changes: https://github.com/brianchandotcom/liferay-portal/commit/24bbfeee51a278f38c0356f0c8722129ec71ee23#diff-98551a2cec5855cf6a8f9dec197e5890R8

**Comment by JorgeFerrer** [comment]
Hey Brian,

The reason is that some of those usages are using OSGi's Config Admin through Declarative Services directly. That's possible when the scope is the whole system, but not when there is different configuration per company, group, etc. Eventually we will want to move more configuration to be scopeable.

For this reason I think it's better if all of our Configuration API is all in one single module. If you have system scope configuration you only use ConfigurableUtil, but once you need more you use ConfigurationProvider. Makes sense?

One thing I would suggest is to avoid creating the bnd.util package. Configurable is not exclusive of bnd, they just provide one implementation. OSGI Enterprise r6 also includes this feature out of the box. So if ours is another implementation I think it should go directly to com.liferay.portal.configuration.util

**Pull request closed without merging**
