### PR TITLE
LRQA-34625 Bug fixes and debug code

### PR DESCRIPTION
**Pull request by pyoo47**
Please publish after merging

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/dfa5074e18...aa67453642

**Comment by brianchandotcom** [comment]
@pyoo47 published a new jar.

**Pull request closed without merging**
