### PR TITLE
LPS-55209 - Create an ant task in modules that will deploy without running all dependent tasks

### PR DESCRIPTION
**Pull request by mjbradford89**
Hi Brian,

These changes have been rebased and conflicts resolved.

It doesn't duplicate work done in deploy, but it does duplicate a few lines in the "clean" task in tools/sdk/build-common.xml.

But this task more of a 'nice to have' feature for frontend-devs to make changes in alloy easier to test, so it's not entirely necessary.  I'm not sure it would be worth the trouble to have build-common call this task.

Please let me know if there are any issues.

Thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@mjbradford89 conflict again :( please resend.

**Comment by mjbradford89** [comment]
Sorry about that. New pull: https://github.com/brianchandotcom/liferay-portal/pull/26529

**Pull request closed without merging**
