### PR TITLE
LPS-74186 Make lpkg url portal profile awared

### PR DESCRIPTION
**Pull request by shuyangzhou**
@brianchandotcom @jpince this fixes the ee side lpkg build failures and the release night build issues.

The problem has always been there, but only started to be exposed by https://github.com/brianchandotcom/liferay-portal/pull/50900
Before that pull, ee only contained ee only themes. After that pull got cherrypicked to ee, ee started to contain both ce and ee themes, since they have the same symbolic name, they are conflicting with each other.

This fix is making the portal profile name part of the lpkg url query string, so that we can tell the difference between ce and ee themes.

But this does raise a question, do we really want ee release to contain ce only themes? What's the point?

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0ba6c4e255...9bc736d691

**Comment by jpince** [comment]
@shuyangzhou it's better (controller, override, and persistence passed), but maybe exposed another issue?
`java.lang.AssertionError: Missing WAR bundle for wrapper bundle Liferay CE Porygon-porygon-theme-wrapper_1.0.24 [795] with expected location webbundle:/Liferay+CE+Porygon-1.0.1/porygon-theme.war?Bundle-Version=1.0.24&Web-ContextPath=/porygon-theme&protocol=lpkg`

**Comment by shuyangzhou** [comment]
@jpince it is just some additional test assertion is not expecting the location having the portal profile names in it. The production code is fine, just the test has not been updated yet. @mtambara is fixing them now.

**Comment by jpince** [comment]
Thanks @shuyangzhou @mtambara!

**Pull request closed without merging**
