### PR TITLE
LPS-68227 | master

### PR DESCRIPTION
**Pull request by vicnate5**
@thiago-rocha @ctampoya

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:reopen

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8bff7955c6...d112c83154

**Pull request closed without merging**
