### PR TITLE
LPS-64562 Run buildSoy

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
cc @marcellustavares

**Comment by leoadb** [comment]
cc @brunobasto

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by sharonchoi** [comment]
investigating RecyclebinUsecase#RestoreDMDocumentFromFolderCP

**Comment by brianchiu** [comment]
The upgrade tests failed in this pull. On an immediate glance, I can't tell if this is a bug or not (but it those upgrade tests didn't fail on this pull https://github.com/brianchandotcom/liferay-portal/pull/38036)

@michaelhashimoto

The failure looks like this. The upgrade tests didn't run at all (build failure beforehand). And it didn't try to hit gogo shell after the upgrade but directly tried to merge results afterwards.
```
     [java] 18:01:05,237 INFO  [main][VerifyProcess:79] Completed verification process com.liferay.portal.security.service.access.policy.verify.SAPServiceVerifyProcess in 23ms
     [java] INFO - Completed verification process com.liferay.portal.security.service.access.policy.verify.SAPServiceVerifyProcess in 23ms
     [java] Loading bundleresource://292.fwk18752748/portlet.properties
     [java] Loading bundleresource://268.fwk18752748/portlet.properties
     [java] 
     [java] Completed Liferay core upgrade and verify processes in 1753 seconds
     [java] Running modules upgrades. Connect to your Gogo Shell to check the status.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20160323104651875.txt

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null2049095723
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 199ms
```

```
BUILD FAILED
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-test-portal-acceptance-pullrequest-batch.xml:332: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-portal/build-test-batch.xml:783: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-portal/build-test-batch.xml:538: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-portal/build-test-batch.xml:483: /opt/dev/projects/github/liferay-portal/build-test-batch.xml:540: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-portal/build-test-batch.xml:233: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-portal/build-test-batch.xml:542: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:48: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:56: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-portal/build-test.xml:7390: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-portal/build-test.xml:7840: Upgrade timeout error!
```

CC @brianchandotcom

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ba1ee80eae...5cb591b63d

**Comment by marcellustavares** [comment]
@leoadb, don't we have the same issue on other field types?

**Comment by leoadb** [comment]
@marcellustavares We don't. The others use the field's name as the "id" for the input tag. The name is unique.

**Comment by marcellustavares** [comment]
Awesome, thanks @leoadb

**Pull request closed without merging**
