### PR TITLE
LPS-75649 SF

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by topolik** [comment]
Hi @ealonso,

> LPS-75649 Permissions are not supported for tags df5f486

But permissions are supported ... https://github.com/ealonso/liferay-portal/blob/df5f48683d8c0bc2182f540caf1f38f6760c295a/portal-impl/src/com/liferay/portlet/asset/service/impl/AssetTagServiceImpl.java#L78-L79

Can you please describe what do you mean?

Thanks.

**Comment by ealonso** [comment]
Hey @topolik,

As part of https://issues.liferay.com/browse/LPS-52588 we decided to remove the permissions for Tags. In this commit f07cdd6, we removes the "asset.tag.permissions.enabled" property, as you can see in the old description the permissions were deprecated for 6.2:

```
    #
    # Set this to true to enable permissions for tags. Note that this feature
    # is deprecated and should only be enabled for backwards compatibility. If
    # there is a requirement to use permissions for tags, consider using
    # categories instead.
    #
    asset.tag.permissions.enabled=false
```
Please let me know if you have any other question.

Regards,
Eudaldo.

**Comment by ealonso** [comment]
cc: @jorgeFerrer

**Comment by topolik** [comment]
I see.

So wouldn't it be better to remove all permission checking rather to having this current inconsistent state?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/908b852eeb...9fcd571a29

**Comment by brianchandotcom** [comment]
@topolik @ealonso I renamed the method to "sanitize"

**Comment by ealonso** [comment]
Hey @topolik,

You are right, I didn't realize about those inconsistencies with tags, I've created a task for fix that:
https://issues.liferay.com/browse/LPS-75863

Thanks!!
Eudaldo

**Pull request closed without merging**
