### PR TITLE
LPS-99161 Fix missing value

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4a953becaf...742065e970

**Comment by brianchandotcom** [comment]
lbm:backport @CsabaTurcsan @jpince @zsoltbalogh

or else your future backports are going to be very difficult @p2kmgcl

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal-ee/pull/25872 for the backport.

**Pull request closed without merging**
