### PR TITLE
LPS-82470 Fix integration test - create layout to be sure that fragment entry link has correct class pk

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
cc @ealonso

**Comment by pavel-savinov** [comment]
c:reopen

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by jpince** [comment]
@pavel-savinov thanks for noticing and correcting the integration test failure from https://github.com/brianchandotcom/liferay-portal/pull/60702 :)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9ae81f9d38...d9aa32fb31

**Pull request closed without merging**
