### PR TITLE
LPS-52679 CXF Servlet, services extender and handlers tracking

### PR DESCRIPTION
**Pull request by csierra**
/cc @migue @topolik

hey Brian... this is the new pull rebased on top of what you sent me. I rebased it on top of today's master and I also squashed all the changes because there seemed to be too many file renames and the former pull looked very cluttered. I still have the original pull in case you prefer to merge it.

I haven't done any change on the (cxf.extension=true). As I explained in my former pull these extensions are "cxf only". AFAIK there is no such a thing as a JAX-WS extension. 

Oh... I also spoke with Miguel regarding better to try to put examples as tests instead of sample projects, so I removed the sample soap service from the pull.

### CODE REVIEW

**Comment by csierra** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Should we rename this then to portal-cxf-extender? just like how we have a portal-axis-extender? Since it's not a generic soap impl but a cxf one?

Please resend. Thx.

**Comment by csierra** [comment]
No @brianchandotcom, this is an implementation of the JAX-WS API, so it is generic. The services and the handlers follow the API and are not implementation aware. It is **only the extensions which are CXF specific** and that's why only the extensions have "cxf" on them. 

please see https://github.com/brianchandotcom/liferay-portal/pull/24434 it is the same pull.

**Comment by csierra** [comment]
@brianchandotcom as you say above, portal-axis-extender indeed is an axis only implementation and does not follow JAX-WS or other standard.

**Pull request closed without merging**
