### PR TITLE
LPS-74544

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:test

**Comment by petershin** [comment]
@hhuijser - This pull was accidentally closed by CI.  Resent it [here](https://github.com/brianchandotcom/liferay-portal/pull/53985).

The new pull also updates the [markdown](https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/documentation/gradle_versioning.markdown) file

**Comment by jpince** [comment]
@petershin why does this pull not include the change in `gradle_versioning.markdown`? I was going to reopen this one since it was already tested, but noticed that was missing

**Comment by petershin** [comment]
@jpince - You're right.  The new [pull](https://github.com/brianchandotcom/liferay-portal/pull/53985) includes that change.

**Pull request closed without merging**
