### PR TITLE
LPS-112763 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LPS-112763

Forwarded from https://github.com/wincent/liferay-portal/pull/241

Notes from @wincent:
New version release notes.

Brings in new lints from latest eslint-liferay-config release, specifically:

feat!: require blank lines before and after line comments
feat!: enforce standard formatting for deprecation annotations
This gets up 99% of the way to where we want to go, by which I meant that:

We put blank lines before and after line comments (//); and:
Blank lines before but not after block comments (/* ... */)
in 95% of places. The remaining 5% consists of points where ESLint and Prettier disagree about how a comment should be formatted; this specifically occurs at the beginning of objects, arrays, blocks etc. The first 95% was cheap to get (configuration only); the remaining 5% would be expensive (requiring hacking Prettier) so I stopped at this point for now.

I'll apply the autofixes (a hundred or so) and manual fixes (a couple) in separate commits to make the automated part of this update clear.

### CODE REVIEW

**Comment by john-co** [comment]
ci:reopen

**Comment by john-co** [comment]
Tested in https://github.com/wincent/liferay-portal/pull/241#issuecomment-621436548

heavy_check_mark ci:test:stable - 18 out of 18 jobs passed
x ci:test:relevant - 98 out of 101 jobs passed in 2 hours 10 minutes 54 seconds 554 ms

DMAutoTagging is fixed recently here: brianchandotcom#88158 , and confirmed fixed in upstream sync: https://testray.liferay.com/home/-/testray/cases/867508898

PagesFinder#AddChildPageViaPageFinder still looks like under investigation https://issues.liferay.com/browse/LRQA-58297 and is still failing in all other pulls: https://testray.liferay.com/home/-/testray/case_results/1135416126/history?tab=result&hideFilterPin=true

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/41f126fbc9...1f085b085d

**Comment by brianchandotcom** [comment]
@wincent one more 1f085b0

Thx!

**Pull request closed without merging**
