### PR TITLE
LPS-75176 HTML tags are displayed in blogs cover image caption

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:reopen

**Comment by adolfopa** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ad56ea3f6d...488375e4cb

**Comment by brianchandotcom** [comment]
@adolfopa the broken ServiceBuilder tests in this pull are real. I fixed it in 488375e4cbda8bbee702ad91b9c3255225c82917

See commit comments. Thx.

**Pull request closed without merging**
