### PR TITLE
LPS-102041 Updates package. ClaySelect* packages are now part of @clayui/form

### PR DESCRIPTION
**Pull request by jbalsas**
/cc @john-co, @andresfulla, @epgarcia, @brunofarache, @brunobasto, @adolfopa, @boton

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jpince** [comment]
cc/ @john-co

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
central requirements failure looks unique, but I can't tell if this is related to the pull:

Does a version need to be updated on nexus?

```
     [exec] * What went wrong:
     [exec] Execution failed for task ':baseline6'.
     [exec] > Could not resolve all files for configuration ':detachedConfiguration4'.
     [exec]    > Could not resolve com.liferay.portal:com.liferay.util.bridges:[6.0.0,7.0.0).
     [exec]      Required by:
     [exec]          project :
     [exec]       > Failed to list versions for com.liferay.portal:com.liferay.util.bridges.
     [exec]          > Unable to load Maven meta-data from http://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/portal/com.liferay.util.bridges/maven-metadata.xml.
     [exec]             > Could not get resource 'http://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/portal/com.liferay.util.bridges/maven-metadata.xml'.
     [exec]                > Could not GET 'http://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/portal/com.liferay.util.bridges/maven-metadata.xml'.
     [exec]                   > squid.lax.liferay.com: Name or service not known
```

Full log: https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/320563/consoleFull

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated.

Manually smoke tested bundle:
1. flagged a blog post - pass
2. created a segment - pass

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2b992108f9...eeffe2ae76

**Pull request closed without merging**
