### PR TITLE
LPS-56384 Deprecated unused taglib attribute

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
ci:test

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/44f31eb503...915c9b8713

**Pull request closed without merging**
