### PR TITLE
LPS-60861 Remove the deprecated isVisible method

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@JorgeFerrer @yxingwu please fix semantic error.

**Comment by JorgeFerrer** [comment]
@yxingwu Can you take care of that or do you want me to do it?

**Comment by yxingwu** [comment]
@JorgeFerrer  you can do it if you are free. Actually, I have no idea about fixing it util now. 
Thank you !

**Comment by JorgeFerrer** [comment]
Hey @yxingwu, 

Sorry, I've been sick and travelling and wasn't able to do this. It's a bit late now since GA1 is out, so this will have to wait for another time.

**Pull request closed without merging**
