### PR TITLE
Remove unneeded use of fully-qualified class names

### PR DESCRIPTION
**Pull request by jhinkey**
cc\ @codyhoag

### CODE REVIEW

**Comment by brianchandotcom** [comment]
A lot of these:

```
		File ejbFile = new File(
			_outputPath + "/service/http/" + entity.getName() +
				"ServiceSoap.java");

		writeFile(ejbFile, content, _author);
```

That turned to

```
		String ejbFilePath =
			_outputPath + "/service/http/" + entity.getName() +
			"ServiceSoap.java";

		File ejbFile = new File(ejbFilePath);

		writeFile(ejbFile, content, _author);

		_checkForUnnecessaryFullyQualifiedClassNames(ejbFilePath, content);
```

Could be simpler if we just had the check method take in a File object?

Please resend. Thx.

**Comment by jhinkey** [comment]
In https://github.com/jhinkey/liferay-portal/pull/191, Cody @codyhoag explained ...

"Notice that when checking for unnecessary fully qualified class names, I created a variable to hold the file path, and then used that variable to create the file and then pass it in the _checkForUnnecessaryFullyQualifedClassNames() method (e.g., lines 2128-2135). I had to do this because if I didn't use the EXACT same file path that was used to create the file, I was unable to rewrite the file. Therefore, using the getPath() method to simply retrieve the path was not an option."

But, we'll investigate further to see if we can use the File object.

**Comment by brianchandotcom** [comment]
Try file toString?

Thx

**Comment by codyhoag** [comment]
Thanks, Brian. I found the issue. The unique file name is required when creating the qdox JavaClass object, not to rewrite the file. The `_getJavaClass` method assumes the file path is formatted a specific way (because it checks for forward slashes in certain spots), so we'll need to account for that requirement. I'll make the necessary changes and send to Jim for review.

**Pull request closed without merging**
