### PR TITLE
LPS-56383 fix upgrade process in journal

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@epgarcia This will introduce a race condition no? This component is published immediately, with no dependencies.

In a brand new database, it is possible that the tables are created AFTER this event is executed.

It think this shouldn't be a separate event but should be in JournalServiceUpgrade as a method after the call to "_releaseLocalService.updateRelease"

Also, remember that in the old DBUpgrader code, we would call

CacheRegistryUtil.setActive(true)

To clear the cache. Now, your event code won't do that anymore. So we really need this inside the Upgrade class.

Please resend. Thx.

**Comment by epgarcia** [comment]
Ok understood. I'll do it that way. Thanks!

**Pull request closed without merging**
