### PR TITLE
LPS-73003

### PR DESCRIPTION
**Pull request by Ithildir**
Hi,
Please let this pull finish.

Thank you!

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b061473f4f...34656fb734

**Comment by brianchandotcom** [comment]
@Ithildir wow. Very nice.

**Comment by brianchandotcom** [comment]
@Ithildir can you backport this? Not able to cherry pick cleanly.

**Comment by Ithildir** [comment]
Done: https://github.com/brianchandotcom/liferay-portal/pull/49552

**Pull request closed without merging**
