### PR TITLE
LPS-111463 | master

### PR DESCRIPTION
**Pull request by vicnate5**
Manually forwarding this, the relevant run was using 125 servers, so it was heavy and more likely to hit a random failure. Frontend team is working on reducing the testing scope, the new test properties will help this in the future. @jonmak08

Forwarded from https://github.com/jonmak08/liferay-portal/pull/2116

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:reopen

**Comment by vicnate5** [comment]
@john-co

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/dd44096e03...ddf6cc8163

**Comment by brianchandotcom** [comment]
@vicnate5 great, we should roll out the new test.properties asap.

**Pull request closed without merging**
