### PR TITLE
New reference doc stylesheets

### PR DESCRIPTION
**Pull request by jhinkey**
https://issues.liferay.com/browse/LRDOCS-2232

cc/ @mwilliams2014, @CAustin582, @Ithildir

### CODE REVIEW

**Comment by jhinkey** [comment]
ci:retest

The failures were not related to any of these commits.

**Comment by jhinkey** [comment]
The failures are not related to this branch's changes.

**Comment by pyoo47** [comment]
This appears to be another case of a very large log file being generated by portal. ci:retest

**Comment by jhinkey** [comment]
Hi Brian,
This PR has passed all checks. If there's anything more you want me to do, please let me know.
Thank you,
Jim

**Comment by jhinkey** [comment]
I'll rebase and re send

**Pull request closed without merging**
