### PR TITLE
LPS-55526 Extract Stores to OSGi modules

### PR DESCRIPTION
**Pull request by mdelapenya**
cc/ @sergiogonzalez @csierra @migue

### CODE REVIEW

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by migue** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by migue** [comment]
ci:retest

**Comment by migue** [comment]
ci:retest

**Comment by migue** [comment]
ci:retest

**Comment by migue** [comment]
ci:retest

**Comment by migue** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by migue** [comment]
ci:retest

**Comment by migue** [comment]
ci:retest

**Comment by migue** [comment]
ci:retest

**Comment by migue** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@cgoncas @migue no need to rest this pull. It works. I"ll merge in tomorrow (we had some major CI issues today I had to work on so I didn't get time). Thx guys.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b14f670113...3071557ade

**Comment by brianchandotcom** [comment]
@migue questions:

see all files named ConfigurationAdminBundleActivator

all stores have one except for portal-store-db-test. Why is that?

Pushed upstream! Please see my changes. Thx.

**Comment by mdelapenya** [comment]
Hey @brianchandotcom, DBStore does not rely on any valid configuration, as it does not depend on external configuration via OSGi configurations (in tests), that's why it does not have it

**Comment by brianchandotcom** [comment]
Thank you @mdelapenya for the explanation. That makes a lot of sense.

**Pull request closed without merging**
