### PR TITLE
LPS-88706 Sub Aggregations

### PR DESCRIPTION
**Pull request by arboliveira**
**❌ ci:test:search - 14 out of 18 jobs passed in 1 hour 23 minutes 22 seconds 530 ms**
https://github.com/arboliveira/liferay-portal/pull/665#issuecomment-464890099

Branch `master` may be contaminated (awaiting confirmation.) Functional test regressions possibly caused by recent changes to the Asset Tags Selector, unrelated to Search. (https://github.com/liferay/liferay-portal/commit/44bcf2786fa5c6f8e9347510bcc4175b98e85a0e#commitcomment-32364705)
cc/ @ealonso @xbrianlee @joshchong

Authors: @mhan810 @rafaprax @inacionery
Reviewer: @arboliveira

_[Story] Sub Aggregations_
https://issues.liferay.com/browse/LPS-88706

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@arboliveira merged.. but that's a lot of duplicate code as highlighted by e9c826a906ff74d2c3a9bd5bc4153f0cc40389c5

@mhan810 fyi

**Comment by ealonso** [comment]
cc: @brianchiu @kyle-miho

**Comment by joshchong** [comment]
FYI @brianchiu @kyle-miho, tag select issues are addressed here: https://issues.liferay.com/browse/LPS-90734

**Comment by arboliveira** [comment]
Technical debt from https://github.com/brianchandotcom/liferay-portal/pull/68216#issuecomment-464984461 will be addressed by https://issues.liferay.com/browse/LPS-90871.

**Pull request closed without merging**
