### PR TITLE
LPS-182150 SF

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@MarinhoFeliphe this won't work if 2 different companies have 2 different keys.

Please resend.

**Comment by MarinhoFeliphe** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d5663a9d5b...0f4369aa39

**Pull request closed without merging**
