### PR TITLE
LPS-77260 Reuse

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
ci:test

**Comment by sergiogonzalez** [comment]
Hey @austinchiang @patriciajeanperez
This pull might also break some of our functional tests. This pull removes the 5 file selectors we had in message boards to add attachments and it replaces it with the multiple uploader used in other places such as Knowledge Base or wiki that doesn't have any restriction in the number of files that can be uploaded and it also supports drag and drop from the desktop.
Let me know if you guys have any question.
Thanks!

**Comment by patriciajeanperez** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3de9dbb600...c463b6998a

**Comment by brianchandotcom** [comment]
@sergiogonzalez see c463b69 thx

**Pull request closed without merging**
