### PR TITLE
LPS-142278 Remove portal lib dir property | 2022-1-25

### PR DESCRIPTION
**Pull request by dantewang**
Excluding DirectDeployTask after talking with Dev Tools Team. Dev Tools Team will determine whether this task is still supported for 7.4+ and make corresponding changes.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:reopen

**Comment by dantewang** [comment]
ci result see https://github.com/liferay-core-infra/liferay-portal/pull/188

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/41ead6f4ff...bbe3cda06a

**Comment by brianchandotcom** [comment]
@dantewang just 84c8c43

**Pull request closed without merging**
