### PR TITLE
LPS-165565 Make sure the object formula field should not be used as an object aggregation filter

### PR DESCRIPTION
**Pull request by seltong**
Related issues: https://issues.liferay.com/browse/LPS-165565 and https://issues.liferay.com/browse/LPS-166008

### CODE REVIEW

**Comment by seltong** [comment]
ci:reopen

**Comment by seltong** [comment]
The relevant failures [here](https://github.com/liferay-objects/liferay-portal/pull/1263) are not related

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/df17fafe82...92c172aad3

**Comment by brianchandotcom** [comment]
@seltong see 92c172aad38c159df0b38cfb4ed1b41a2a0e809d

**Pull request closed without merging**
