### PR TITLE
LPS-110276 Add IdempotentRetryAssert due to asynchronous search engine

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/93097a7e2a...7e0bd981d3

**Comment by brianchandotcom** [comment]
@shuyangzhou see this fix by @inacionery 7e0bd981d3433da5948a8f90b5187f85f88fc320

I think we have a root issue with search. I'm not sure if this is the best fix. Feel free to fix ti differenlty if you want to.

@inacionery can you give @shuyangzhou on the flakes?

**Comment by inacionery** [comment]
The issue is that Elasticsearch does not do the indexing immediately, you can search for the data and it is not there yet, even if the indexing request returns successfully. Maybe we need to set the flag [refresh_wait_for](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/docs-refresh.html#refresh_wait_for-force-refresh)

**Comment by inacionery** [comment]
Instead of using IMMEDIATE [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-search-elasticsearch6/portal-search-elasticsearch6-impl/src/main/java/com/liferay/portal/search/elasticsearch6/internal/search/engine/adapter/document/ElasticsearchBulkableDocumentRequestTranslator.java#L245) and [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-search-elasticsearch6/portal-search-elasticsearch6-impl/src/main/java/com/liferay/portal/search/elasticsearch6/internal/search/engine/adapter/document/BulkDocumentRequestExecutorImpl.java#L111) , we can use WAIT_UNTIL

**Comment by inacionery** [comment]
```
/**
 * Force a refresh as part of this request. This refresh policy does not scale for high indexing or search throughput but is useful
 * to present a consistent view to for indices with very low traffic. And it is wonderful for tests!
 */
IMMEDIATE("true"),
/**
 * Leave this request open until a refresh has made the contents of this request visible to search. This refresh policy is
 * compatible with high indexing and search throughput but it causes the request to wait to reply until a refresh occurs.
 */
WAIT_UNTIL("wait_for");
```

**Pull request closed without merging**
