### PR TITLE
LPS-73481 FIX MASTER VERSIONING ISSUE

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
cc/ @achaparro

hey @brianchandotcom

Let me know if i've made something wrong or if I've miss any change

Thanks!

**Comment by robertoDiaz** [comment]
ci:reopen

**Comment by achaparro** [comment]
@robertoDiaz, please, take a look at the failed test, maybe you need to add more changes.

**Comment by brianchandotcom** [comment]
Not merging. I rolled back all of LPS-73481.

In the future, if a pull shows it's completely broken in my PR, please close it for me. Thx.

**Pull request closed without merging**
