### PR TITLE
LPS-61970 Reuse nav

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
Aborted due to known start-up issue caused by https://github.com/liferay/liferay-portal/commit/d992d839572c70e1e93be6c97b1566069941a69f

After this <a href="https://github.com/brianchandotcom/liferay-portal/pull/34330">pull</a> is merged please re-run this particular pull request.

Sorry for the inconvenience.

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/067322804b...c85b373f33

**Comment by brianchandotcom** [comment]
@sergiogonzalez can you review my changes in upstream? Thx.

**Pull request closed without merging**
