### PR TITLE
LRQA-24340 Implemented file propagation logic to rapidly deploy files to all slaves.

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-24340

Please release a new jenkins results parser jar after merging.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by alee8888** [comment]
@brianchandotcom 
JBoss/Wildfly fails to deploy due to https://github.com/liferay/liferay-portal/commit/7678dda66dc5de1785b9a971b990a769f210083b. I have told Kiyoshi and he is working on it right now.

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d59f7913f7...ca0a806c40

**Pull request closed without merging**
