### PR TITLE
LPS-165399 Add aria-label to clay:dropdown-actions

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-165399

@p2kmgcl

### CODE REVIEW

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/10047

:heavy_check_mark: ci:test:stable - 28 out of 28 jobs passed
:x: ci:test:relevant - 564 out of 592 jobs passed in 3 hours 10 minutes

**Comment by ozysouza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3e11c63d0b...eaf4f8f176

**Comment by brianchandotcom** [comment]
@p2kmgcl we need to enforce this or it will quickly get out of sync.

Can we default it to show-actions ?

@ling-alan-huang or we SF this?

**Pull request closed without merging**
