### PR TITLE
LPS-99596 Redirect a jsp when creating a new Form View

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4196ff194f...0565a9ac57

**Pull request closed without merging**
