### PR TITLE
LPS-65376 Deprecate/copy FacetedSearcher from portal-kernel to portal-search-facet

### PR DESCRIPTION
**Pull request by arboliveira**
Addressing https://github.com/brianchandotcom/liferay-portal/pull/39174#issuecomment-215291706, moved FacetedSearcher to matching package "faceted.searcher" under larger facet infrastructure. (`com.liferay.portal.search.facet.faceted.searcher`)

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:stop (stopping due to issues with testray and NAS)

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@arboliveira 

In modules/apps/foundation/portal-search/portal-search/build.gradle

```
provided group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "[2.2.0,2.4.0)"
```

is very very special.

You must not just change that to "default".

It matches a bnd.bnd file 

```
Import-Package: com.liferay.portal.kernel.search;version="${range;[=,=+)}",*
```

The point is to say that for that we are binary compatible from 2.2.0 to just before 2.4.0.

Please resend and I'm not sure why you changed that file. I think you should change it to [2.4.0) since it is now binary with 2.4.0, but you should keep the ) for future reference.

Please resend. Thx.

**Comment by brianchandotcom** [comment]
@arboliveira I might take a stab at this...

**Comment by brianchandotcom** [comment]
Hmm.. I'll leave this back to you.. can you also fix

portal-impl/src/com/liferay/portal/service/impl/CompanySearcher.java

We don't have this pattern anywhere else I know of. service/impl/** should be *ServiceImpl and not have these searchers.

**Comment by arboliveira** [comment]
@brianchandotcom Sure, will do. The change to `default` was actually following your own post on Loop with instructions regarding `build.gradle` and `com.liferay.portal.kernel` (not a public post but you know which one.) The very very special format is something new, and I'm sure lots of developers are not yet aware of it. For the sake of consistency, can you please update your post (or publish a new one) detailing when we should use either format?

**Pull request closed without merging**
