### PR TITLE
LPS-48334

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-48334.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@jonmak08 we can't update the major version like that. Java must have no breaking changes. Please resend.

**Comment by jbalsas** [comment]
Hey @brianchandotcom, we're removing an editor, and sadly, it happens to have a hardcoded constant in `portal.kernel.servlet.PortalWebResourceConstants`... how should we proceed?

**Pull request closed without merging**
