### PR TITLE
Lps 68289 21

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @tinatian
@tomwang2011 backport please.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/eae4d5faa3...84f6d97847

**Comment by brianchandotcom** [comment]
@Preston-Crary please send me a pull to undo the portal-impl "default" change to the cache module. Thx.

**Comment by brianchandotcom** [comment]
@tomwang2011 all yours. Can you backport it as is? When @Preston-Crary sends me his change, I'll backport that one commit myself. THx.

**Comment by tomwang2011** [comment]
@brianchandotcom I was able to cherry-pick all but the system.packages.extra.mf commit (regenerated that one in ee-7.0.x), the backport is sent at https://github.com/dustinryerson/liferay-portal-ee/pull/2209

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/43677

**Pull request closed without merging**
