### PR TITLE
LPS-71202 Move form outside of other forms

### PR DESCRIPTION
**Pull request by robframpton**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by jpince** [comment]
ci:retest

**Comment by pyoo47** [comment]
Here's the failure from the dist job:
```
compile-common-jsp:
     [echo] Mar 14, 2017 4:55:09 AM org.apache.jasper.servlet.TldScanner scanJars
     [echo] INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
     [echo] org.apache.jasper.JasperException: file:/opt/dev/projects/github/liferay-portal/portal-web/docroot/html/taglib/ui/page_iterator/lexicon/start.jsp (line: 70, column: 1) No tag "html-bottom" defined in tag library imported with prefix "liferay-ui"
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1399: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:420: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-dist.xml:539: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build.xml:254: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-web/build.xml:326: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-web/build.xml:285: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-web/build.xml:124: JSPs failed to compile.
```

**Comment by jpince** [comment]
@Robert-Frampton see Peter's comment above

closing this pull

**Comment by jpince** [comment]
ci:close

**Pull request closed without merging**
