### PR TITLE
LPS-75276 Make sure the className is a valid ID

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @adolfopa

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6faffdc656...d722081e7f

**Pull request closed without merging**
