### PR TITLE
LPS-54068 better handling of exceptions for Journal

### PR DESCRIPTION
**Pull request by juliocamarero**
fyi @epgarcia @ealonso

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Please resend, real test failures?

**Comment by juliocamarero** [comment]
@Preston-Crary could you please have a look at the tests? It seems this pull breaks 62 tests....

**Comment by Preston-Crary** [comment]
https://github.com/juliocamarero/liferay-portal/pull/3286

**Pull request closed without merging**
