### PR TITLE
LPS-147709 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-147709

This is only for master.

@lfbesada
cc @ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/7289
❌ ci:test:stable - 34 out of 40 jobs passed
❌ ci:test:relevant - 34 out of 41 jobs passed in 2 hours 30 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a94542832d...798a2e8453

**Comment by brianchandotcom** [comment]
@lfbesada see 798a2e84532795d8aa5c1c50671f5bd4c9fd7825 and c8d0f9fa95c0be3682fd0fa083629fa74be5333e

**Pull request closed without merging**
