### PR TITLE
Lps 80401

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@Preston-Crary can you resend?

modules/apps/message-boards/message-boards-service/src/main/java/com/liferay/message/boards/internal/permission/MBPortletPermissionLogic.java
modules/apps/message-boards/message-boards-service/src/main/java/com/liferay/message/boards/internal/permission/MBPortletPermissionRegistrar.java

are in the wrong dir

MBPortletPermissionLogic.java should be in internal.security.permission.resource to match com.liferay.portal.kernel.security.permission.resource.PortletResourcePermissionLogic

Please fix else where. I suppose you should move the Registrar too.

**Comment by Preston-Crary** [comment]
@sergiogonzalez, can you resend with those changes since you put those classes there?

@hhuijser can we have a SF check so that anything ending in "PermissionRegistrar" or implementing implementing PortletResourcePermissionLogic or ModelResourcePermissionLogic is in the "internal.security.permission.resource" package and anything implementing PortletResourcePermissionDefinition or ModelResourcePermissionDefinition is in a "internal.security.permission.resource.definition" package?

**Comment by hhuijser** [comment]
@Preston-Crary adding to my list :)

**Comment by Preston-Crary** [comment]
@sergiogonzalez nevermind, I'll do it.

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/58446

**Comment by sergiogonzalez** [comment]
Hey @Preston-Crary thanks for doing the changes for me. Yesterday was holiday in Madrid and we didn't work. I was about to do the change and I saw you did it 😃

**Pull request closed without merging**
