### PR TITLE
LPS-100766

### PR DESCRIPTION
**Pull request by p2kmgcl**
/cc @ealonso

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:reopen

**Comment by sandrodw3** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e26b902156...92c68ced30

**Pull request closed without merging**
