### PR TITLE
LPS-97221 Delete record sets by structure id

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
cc @jeyvison

**Comment by jeyvison** [comment]
ci:retest

**Comment by jeyvison** [comment]
ci:stop

**Comment by jeyvison** [comment]
ci:stop

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@leoadb can you resend on top of https://github.com/leoadb/liferay-portal/pull/484 Thx!

**Pull request closed without merging**
