### PR TITLE
LPS-72409 add integration test

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:reopen

**Comment by gamerson** [comment]
ci:retest

**Comment by gamerson** [comment]
ci:retest

**Comment by gamerson** [comment]
ci:stop

**Comment by gamerson** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@gamerson this seems to break tests? See modules-int*.  Please resend. Thx.

**Pull request closed without merging**
