### PR TITLE
LPS-115713 Only serialize when in developer mode

### PR DESCRIPTION
**Pull request by csierra**
Hey Brian, 

unrelated failures here: https://github.com/liferay-appsec/liferay-portal/pull/82#issuecomment-682425128

### CODE REVIEW

**Comment by csierra** [comment]
ci:reopen

**Comment by csierra** [comment]
Unrelated failures here: https://github.com/liferay-appsec/liferay-portal/pull/82#issuecomment-682425128

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/aa0c123a00...ab04ce11af

**Comment by brianchandotcom** [comment]
@csierra see 7bc1c28b67535e679f8189d39df6b695d86f3c60 and ab04ce11af0de3265aa9b1bc5aebd28eb43b6e4b

**Comment by lipusz** [comment]
lbm:backport

**Pull request closed without merging**
