### PR TITLE
Use latest Shrink Wrap OSGi

### PR DESCRIPTION
**Pull request by cgoncas**
/cc @csierra @Ithildir @hhuijser

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:retest

**Comment by csierra** [comment]
thanks @cgoncas!

**Comment by cgoncas** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/80914517cf...c85c2e4e7f

**Pull request closed without merging**
