### PR TITLE
LRQA-55018 | master

### PR DESCRIPTION
**Pull request by vicnate5**
This only adds poshi code and the code is disabled for now, so I am manually forwarding. This will get enabled along with the ES Sidecar

Master only

@joshchong

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:reopen

**Comment by vicnate5** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ba79cf86f5...05de92f7b3

**Pull request closed without merging**
