### PR TITLE
LPS-94500 Use AssetEntryAssetCategoryRelLocalService instead of AssetEntryLocalService

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @SamZiemer,
I've just send your initial fix to Brian, sorry for bothering you with another fixes, this is the right one, sorry about that.
Thanks!!
Eudaldo.

**Comment by jpince** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
No worries @ealonso its always worth checking if other fixes work, thank you for your help!

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
