### PR TITLE
Lps 78269

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@shuyangzhou @mtambara build-app.xml is still synced with 7.0.x, so if we make this change, can you resend it with a corresponding 7.0.x pull? Thx.

**Comment by brianchandotcom** [comment]
@mtambara @shuyangzhou the 7.0.x pull only needs the changes for build-app.xml, not for actually changing things to subsystem for the other mods.

**Comment by shuyangzhou** [comment]
@brianchandotcom Yes, the change is backward compatible. It won't cause issues for 7.0.x, just there will be no use of it. @mtambara will resend.

**Comment by mtambara** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/55767
7.0.x here: https://github.com/brianchandotcom/liferay-portal-ee/pull/19474

**Pull request closed without merging**
