### PR TITLE
LPS-60867 SF

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @robertoDiaz  @ealonso

**Comment by brianchandotcom** [comment]
I found this weird.. how you flipped it from one way to another.

But you left a few out like checkboxCSSClass

Can we just go with imageURL and imageCSSClass?

Please resend. Thx.

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
@brianchandotcom I have resent here: https://github.com/brianchandotcom/liferay-portal/pull/32900

The reason why I rename those is because in every place we have them as imageURL and imageCssClass

We'll resend a pull tomorrow normalizing the values.

**Comment by robertoDiaz** [comment]
I'm implementing the solution.

Shouldn't we add the Jsp vars as JSP too?

2015-12-02 21:46 GMT+01:00 Sergio Gonzalez <notifications@github.com>:

> @brianchandotcom <https://github.com/brianchandotcom> I have resent here:
> #32900 <https://github.com/brianchandotcom/liferay-portal/pull/32900>
>
> The reason why I rename those is because in every place we have them as
> imageURL and imageCssClass
>
> We'll resend a pull tomorrow normalizing the values.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/32893#issuecomment-161429166>
> .
>



-- 
*Roberto Díaz*
Liferay Core Engineer


Liferay España y Portugal / Liferay Spain and Portugal
Tel. +34 917336343
www.liferay.com


Enterprise. Open Source. For Life.
Síguenos en  <http://www.facebook.com/pages/Liferay/45119213107>
<http://www.facebook.com/pages/Liferay/45119213107>
<http://www.twitter.com/%21/liferay_es>
<http://www.liferay.com/about-us/news>

Visit Us: www.liferay.com  |  Like Us: facebook.com/liferay  |  Follow Us:
twitter.com/liferay_es

*Aviso de Confidencialidad: *Este mensaje de correo electrónico, incluidos
los archivos adjuntos, enviados en nombre de Liferay SL es para el uso
exclusivo del destinatario (s) previsto y puede contener información
confidencial y privilegiada. Se prohíbe cualquier revisión no autorizada,
uso, copia, divulgación o distribución. Si usted no es el destinatario, por
favor póngase en contacto con el remitente por correo electrónico de
respuesta y destruir todas las copias del mensaje original. Gracias.

*Confidentiality Notice: *This e-mail message, including any attachments,
sent on behalf of Liferay SL is for the sole use of the intended
recipient(s) and may contain confidential and privileged information. Any
unauthorized review, use, copying, disclosure or distribution is
prohibited. If you are not the intended recipient, please contact the
sender by reply e-mail and destroy all copies of the original message. Thank
you.

**Pull request closed without merging**
