### PR TITLE
LPS-185674 Add Relationship, Position, and Linked Features to Model Builder

### PR DESCRIPTION
**Pull request by igor-franca**

### CODE REVIEW

**Comment by igor-franca** [comment]
ci:reopen

**Comment by igor-franca** [comment]
Sending directly because I did a Rebase with Brian/Master and there is an SF error that was not introduced in these commits and the forward force does not send the PR because of that.

More details [here](https://github.com/liferay-objects/liferay-portal/pull/2524#issuecomment-1707115848)

**Comment by brianchandotcom** [comment]
@igor-franca rebase error, please resend.

**Comment by igor-franca** [comment]
resent [here](https://github.com/brianchandotcom/liferay-portal/pull/140360)

**Pull request closed without merging**
