### PR TITLE
LPS-56372 Extend CommandAction framework to have better support for resourceURLs and renderURLs

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Hey @rotty3000 @peterfellwock @marcellustavares @brunobasto @leoadb @juliocamarero @epgarcia

I have extend the MVCPortlet framework regarding ActionCommand.java. Before we were using ActionCommand.java for both actionURL and resourceURL. I have splitted that in 2 different interfaces. Besides that, the ResourceCommand that will be used is based on resourceID and not based on ActionRequest.ACTION_NAME parameter.
I have also created a new one for renderURL using the mvcAction parameter so the render of the RenderCommand will be invoked based on mvcAction parameter.

I have modified all the uses that I could find in your plugins, so when ActionCommand were used for resourceURLs I have updated that to use ResourceCommand classes. I have done all the changes and you guys shouldn't need to do anything, I'm just ccing you so you're aware of the changes and you can check them or ask any question you may have.

@marcellustavares I have also done a fix for DDM in https://github.com/sergiogonzalez/liferay-portal/commit/ee5711e48a74bebf16f9ca4ca281fb2872775f83 because that URL wasn't pointing to any resource handling logic

Thanks

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Thanks @sergiogonzalez

**Comment by brunobasto** [comment]
Thank you, @sergiogonzalez!!

**Comment by sergiogonzalez** [comment]
cc/ @izaera @jorgeferrer

**Comment by rotty3000** [comment]
Good job @sergiogonzalez!

**Comment by brianchandotcom** [comment]
Hey @sergiogonzalez This is very good. Can you resend in separate pulls:

First pull:

1.) Rename "action.command.name" to "mvc.command.name" I think it's easier to comprehend at the OSGi @component level if we prefix everything wth mvc.*

2.) Rename "*ActionCommand*" to "*MVCActionCommand*" in preparation for "MVCRenderCommand" etc.

Second pull:

Add *Render* and *Resource* specific things.

Thx @sergiogonzalez

**Pull request closed without merging**
