### PR TITLE
 LRQA-43479 Copy the JUnit test report to be read by Jenkins

### PR DESCRIPTION
**Pull request by pyoo47**
http://issues.liferay.com/browse/LRQA-43479

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@pyoo47 published.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3030d82d94...95c56195d2

**Pull request closed without merging**
