### PR TITLE
Lps 76963

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fc04816978...b17d43fbdd

**Comment by brianchandotcom** [comment]
@lanceji92674957 can you backport this? I didn't merge in your commit to remove from the whitelist. Will do that after you send me the backport.

**Comment by lanceji92674957** [comment]
@brianchandotcom ok, working on it

**Comment by lanceji92674957** [comment]
@brianchandotcom there is no "portal-security-sso-openid-connect" on 7.0.x, so I think there won't be any backport to do?

**Pull request closed without merging**
