### PR TITLE
LPS-54630 SF

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
<p>The Pull Request Tester will be down until <strong>December 28, 2015 @ 5:00 PM PDT</strong>.</p>

<p>See this <a href="https://issues.liferay.com/browse/LRQA-18839">JIRA Ticket</a> for more information.</p>

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by inacionery** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/da96af578c...3c28a5a3f3

**Pull request closed without merging**
