### PR TITLE
LPS-164256 Remove text indicator and add visual indicator

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-164256

@veroglez

### CODE REVIEW

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/9768

:heavy_check_mark: ci:test:stable - 28 out of 28 jobs passed
:x: ci:test:relevant - 172 out of 181 jobs passed in 2 hours 41 minutes

**Comment by ozysouza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0fadd3c32b...f56b702700

**Comment by brianchandotcom** [comment]
@veroglez see f56b702700431e4702924d4740ab4021f95c911b

**Pull request closed without merging**
