### PR TITLE
LPS-61420

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@brianchandotcom 

This is what service.xml will look like when sorting all attributes...
Let me know what you think...

**Comment by brianchandotcom** [comment]
Looks nice! Thanks @hhuijser

**Comment by brianchandotcom** [comment]
@hhuijser can you send me a pull to fix service.xml in gradle-templates?

Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bb5d75f069...b5d71d4eee

**Pull request closed without merging**
