### PR TITLE
Lps 83300

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
CC @Ithildir

**Comment by brianchandotcom** [comment]
@ithildir fyi, they're reverting a change you made in 6643e364bfe2356279388c422c3fa5eb12bae15a I'm just trusting them for it

**Comment by brianchandotcom** [comment]
@tinatian can you explain in the LPS why your fix fixes it?

**Comment by tinatian** [comment]
@brianchandotcom @Ithildir 
The reason is simple, by using "-Djunit.code.coverage=true" we should add jacoco plugin, but with this simplify change, it is not working. I am not sure how gradle read properties in background, it works before simplify, so I reverted it.

Tina.

**Pull request closed without merging**
