### PR TITLE
LPS-78093 We don't need to invoke the clear cache method for every single page. See 3bdc69e

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @Preston-Crary

**Comment by Preston-Crary** [comment]
@sergiogonzalez Thanks, it looks like I missed two.

**Comment by sergiogonzalez** [comment]
Hey @Preston,
I’m going to resend the pull eith one commit I missed and I’ll include the moveNodeToTrash as part of it

**Comment by sergiogonzalez** [comment]
I just resent it here https://github.com/brianchandotcom/liferay-portal/pull/55715

**Pull request closed without merging**
