### PR TITLE
LPS-78099 Moves to context class

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by pyoo47** [comment]
ci:test

**Comment by kenjiheigel** [comment]
ci:test

**Comment by anthony-chu** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@ealonso rebase error, please resend? Thx.

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
