### PR TITLE
LPS-54590

### PR DESCRIPTION
**Pull request by mikakoivisto**
LPS-54590 filterFindBy performance fix as discussed between @rotty3000 and @sammso. If there's any changes you need please ping @sammso as I will be on vacation next two weeks.

### CODE REVIEW

**Comment by sammso** [comment]
More explanation is written to ticket it self.

https://issues.liferay.com/browse/LPS-54590?focusedCommentId=643675&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-643675

**Comment by mikakoivisto** [comment]
Hey @brianchandotcom is there an issue with this other than it doesn't merge any more? It's been sitting untouched for over 2 weeks. If there's something you need us to do differently please let us know it's important that this fix gets in.

**Comment by brianchandotcom** [comment]
Hey @mikakoivisto 

Sorry, was working on other pulls and this one got pushed down. I just reviewed it and sent changes to you and to @sammso 

see https://github.com/mikakoivisto/liferay-portal/pull/94 and https://github.com/sammso/liferay-portal/pull/20

Can you guys review it and send it back to me? Please correct my changes if they don't make sense.

Thx.

**Comment by sammso** [comment]
Thank you @brianchandotcom , I will check and test this tomorrow.

**Pull request closed without merging**
