### PR TITLE
LPS-58031 read and set admin*Name and companyName

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
@brianchandotcom Chatted with @david-truong and QA, we decided to at least fix 3 of the 4 fields on the setup wizard.  The admin email address is still not working but we can address it in a followup ticket here: https://issues.liferay.com/browse/LPS-61759

**Comment by gamerson** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/175adbb1ba...fba8e0ffdb

**Pull request closed without merging**
