### PR TITLE
LPS-60806

### PR DESCRIPTION
**Pull request by mikakoivisto**
LPS-60806 Upgrade groovy to fix it's java deserialization issue

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Thx @mikakoivisto

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/56c3cd3df0...b1f5a9cf16

**Comment by brianchandotcom** [comment]
You can bring up the * with @mhan810

I think he added it because it needs access to custom jars for the scripting engine to work.

**Comment by mhan810** [comment]
It's due to the groovy lib itself.  It's not a "proper" osgi jar so it's tougher for us to explicitly name all dependencies required to import.  That's why the DyanmicImport and the Import *

**Pull request closed without merging**
