### PR TITLE
LPS-63916

### PR DESCRIPTION
**Pull request by danielkocsis**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 no results here either?

**Comment by pyoo47** [comment]
This is also caused by the bug that we fixed earlier. ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e4e0eb7a42...9533f173f9

**Comment by brianchandotcom** [comment]
@danielkocsis is this 9533f173f930679b86fdcb11f81becae6d269487 OK?

**Pull request closed without merging**
