### PR TITLE
LPS-84262 If version=0.0, we get the last version

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:retest

**Comment by jkappler** [comment]
ci:reopen

**Comment by jkappler** [comment]
Hi @jpince, I don't know if my changes are causing this (I don't think so, but just wanted to be sure).

Thanks

**Comment by jpince** [comment]
@jkappler semver, service builder, and SF errors are known issues. The other two look unrelated.

Next time, you can just ci:test:relevant if CI fails. ci:retest will run the entire ci:test suite :)

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
