### PR TITLE
LPS-74571 - auto SF

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jpince** [comment]
@vicnate5 please review POSHI failures related to `Element is not visible at "//div[contains(@data-fieldname,'validation')]//span[@class='toggle-switch-bar']"`

@jbalsas closing until we can investigate further

**Comment by jpince** [comment]
ci:close

**Comment by vicnate5** [comment]
I need to investigate further. Nothing in the HTML changed, but our test cannot effectively click on navbar nav-tab after this change.

**Comment by jbalsas** [comment]
It's possible that it might not be visible for some css change so it's not clickable... @pat270, could you take a look at this failing test?

@vicnate5, @jpince, I didn't see it failing here... https://github.com/jbalsas/liferay-portal/pull/877 😢

**Comment by vicnate5** [comment]
@jbalsas The tests did not run on the previous pull (jbalsas#877) because portal compile failed. 

If you look at the CI comment on the previous pull, you will see the message, "0 out of 2 jobs PASSED". Only 2 jobs were executed. Here 127 jobs were executed.

The compile failure was due to a server connection issue and is not related to the change here.

**Comment by vicnate5** [comment]
Patrick fixed the issue

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/52596

**Pull request closed without merging**
