### PR TITLE
LPS-65291

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-65291

Rebased: https://github.com/brianchandotcom/liferay-portal/pull/41374#issuecomment-233155718

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:retest

**Comment by vicnate5** [comment]
Poshi test failures are unrelated to this pull. Test fix sent here https://github.com/brianchandotcom/liferay-portal/pull/41636

**Comment by vicnate5** [comment]
Poshi test failures are unrelated to this pull. Test fix sent here https://github.com/brianchandotcom/liferay-portal/pull/41636

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0a6c3ce4d5...151caf5e27

**Pull request closed without merging**
