### PR TITLE
LPS-62683 Unable to delete embedded portlet preferences

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @jcampoy

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c07774a59d...ee5eef0fd5

**Comment by brianchandotcom** [comment]
@jkappler @juliocamarero please see my changes in upstream. Thx.

**Comment by juliocamarero** [comment]
:+1:

**Pull request closed without merging**
