### PR TITLE
LPS-80199 Added style to hide items outline on focus

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
cc @p2kmgcl

**Comment by jpince** [comment]
@kyle-miho @brianchiu please look at POSHI failures
e.g. from smoke: `Element <div class="autofit-col flex-col flex-col-expand layout-column-item-title"></div> is not clickable at point (433, 282). Other element would receive the click`

**Comment by brianchiu** [comment]
Looking

**Comment by brianchiu** [comment]
@sandrodw3 
The test failures are real failures (currently looking to see if we just need to update the tests).

**Comment by brianchiu** [comment]
ci:close

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0eb68ea0a5...31ec5ef9b4

**Pull request closed without merging**
