### PR TITLE
LPS-103098 Success message when removing admin role of the last admin of the site

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-103098](https://issues.liferay.com/browse/LPS-103098).<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @robertoDiaz

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@drewbrokke @robertoDiaz can you resend on top of my changes at https://github.com/drewbrokke/liferay-portal/pull/924:

1.) 

```
			if ((administratorUserIds.length == 1) &&
				ArrayUtil.contains(administratorUserIds, user.getUserId()) &&
				!ArrayUtil.contains(roleIds, administratorRole.getRoleId())) {

				throw new RequiredRoleException.RequiredAdminRoleException();
			}
```

That is thrown in an Action class, but should be thrown in a *ServiceImpl (most likely). If you disagree, please give me reasons why.

2.) Please get rid of duplicate Language key since there's a chance the translator will do it differently.

3.) The exception names in RequiredGroupException are very different from the new ones you added in RequiredRoleException. May be change the names? See the other examples of subclasses inside a *Exception.java in that same package, find a pattern and resend it to me.

**Comment by robertoDiaz** [comment]
Hey @brianchandotcom, 

About:

> That is thrown in an Action class, but should be thrown in a *ServiceImpl (most likely). If you disagree, please give me reasons why.

The problem here is that the service API only receives a list of roles to set to the user, while in the action we have the roles we want to add and remove (then we mix them and we send it to the service). 

As i see it, to throw this exception in the service we have to change the API and pass 2 parameters in all the information to the service.

As additional information, the service also adds the "required roles" if it's not received it (see the uses of **com.liferay.users.admin.kernel.util.UsersAdminUtil#addRequiredRoles()** , so this situation is resolved here. Maybe we could add a warn or an info log when we add this required roles in order to add some feedback to admins and inform them about this.

@drewbrokke, @ChrisKian what do you think about this?

**Comment by robertoDiaz** [comment]
Just started reviewing :)

**Comment by drewbrokke** [comment]
@robertoDiaz we ended up going with throwing an exception in the ActionCommand class. The warn in UsersAdminImpl was causing a log assertion test failure, so we removed it.

See https://github.com/brianchandotcom/liferay-portal/pull/81209, specifically https://github.com/brianchandotcom/liferay-portal/commit/76ba5bb4cb11b12477ae9d9573e8ba1563a81c5f.

**Pull request closed without merging**
