### PR TITLE
LRQA-35268 Fix poshi validation | master

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-35268

@brianchandotcom This fixes the poshi validation error caused by https://github.com/brianchandotcom/liferay-portal/pull/51982, thanks!

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@brianchandotcom I merged this into upstream to fix the PR tester. I didn't merge it into liferay-portal-ee/master because I know the git sha's need to be the same, and I don't know how to do that.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@brianchiu I went ahead and synced them.

**Comment by brianchandotcom** [comment]
@brianchiu if you are in the liferay-portal-ee repo, and your branch is master, then type:

git pull /put/the/directory/of/liferay-portal master

That should keep the same hash.

**Comment by brianchiu** [comment]
@brianchandotcom Ohhh, got it. That makes sense. I'll know next time. Thanks!

**Pull request closed without merging**
