### PR TITLE
LPS-60774 There is a complex circular dependencies between DLFileEntr…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…yLocalServiceImpl and DLFileEntryServiceImpl around checkin/checkout, I don't want to risk breaking any logic, leaving it to DL experts.

Hey @sergiogonzalez and @adolfopa, same as https://github.com/brianchandotcom/liferay-portal/pull/32656

Can you try to do some clean up refactor to get rid of the circular dependencies?

Thanks

Shuyang

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@tinatian See https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=1,label_exp=!master/7585//testReport/com.liferay.portal.cluster.internal/ClusterMasterExecutorImplTest/classMethod should be a race condition in the test logic, please check and fix it.

**Comment by tinatian** [comment]
@shuyangzhou  I found that too yesterday, working on it, seems I did not figure out the root reason last time.

**Comment by sergiogonzalez** [comment]
Hey @shuyangzhou 

We'll start working on both of them and keep you update.
Thanks for bringing this up.

Sergio

**Comment by brianchandotcom** [comment]
@shuyangzhou I merged in https://github.com/shuyangzhou/liferay-portal/pull/2070

Can you still review in case there's something wrong (I just wanted tests green)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4cadb3785b...891c48e1b2

**Comment by shuyangzhou** [comment]
@sergiogonzalez Thanks!

@brianchandotcom I will recheck @tinatian 's change on master.

**Pull request closed without merging**
