### PR TITLE
LPS-94629 - petra-json-web-service-client - gradle baseline

### PR DESCRIPTION
**Pull request by ivicac**
Best Regards

@igorbeslic

### CODE REVIEW

**Comment by jhendley** [comment]
ci:test:sf

**Comment by jhendley** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@shuyangzhou lpkg error real?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cdd76736e7...8c50f412f9

**Comment by shuyangzhou** [comment]
It does not seem like a real one, @mtambara please scan the lpkg failure to be sure.

**Comment by brianchandotcom** [comment]
@ivicac I backported this to 7.1.x and 7.0.x (and published)

For master, it was already 12.0.0 (not published, and a major change, so no need to bump to 12.1.0 - I reverted that part in 6e0803e10397a61cd88ecc3d5cd87ed9ab16d599)

Please 7.2.x and 7.1.x works with latest LCS.

**Comment by mtambara** [comment]
Doesn't look like a real lpkg failure

**Pull request closed without merging**
