### PR TITLE
LPS-64865 Rename upgrade:dryRun command

### PR DESCRIPTION
**Pull request by achaparro**
Hi @brianchandotcom,

Modification approved by @csierra and @david-truong to reflect better the purpose of the command.

Thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7baf7ff39d...c6d4a63b21

**Comment by brianchandotcom** [comment]
@achaparro can we rename it to a "verb"?

The other commands are all verbs.. it'd be better if this one was a verb too?

@achaparro @david-truong fyi

**Comment by david-truong** [comment]
@brianchandotcom the others are a verb because they are an action.  This is a status check so nothing is executed so it wouldn't make sense as a verb.

**Comment by david-truong** [comment]
we could do something like listIncomplete if you would like a verb though

**Comment by brianchandotcom** [comment]
@david-truong why not call it "checkStatus"

**Comment by brianchandotcom** [comment]
or "listIncomplete" is fine too...

**Comment by brianchandotcom** [comment]
If you have one called "listIncomplete", then call the other "listXxx" that is the opposite of incomplete. This makes the commands obvious. thx.

**Comment by achaparro** [comment]
@brianchandotcom,@david-troung, what about upgrade:check to not modify list command just before releasing a new version?

**Pull request closed without merging**
