### PR TITLE
LPS-55540

### PR DESCRIPTION
**Pull request by matethurzo**
Hey Brian,

This is extending our test coverage with a new case using deletions. The test has been put to ignore for now, because @marcellustavares needs to implement some changes for the DDM staging to make it work.

He could use this test to see if his changes are valid or not, and we will enable it soon.

Thanks,

Máté

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/63f2ec026a...f0088369b6

**Comment by brianchandotcom** [comment]
@matethurzo in the future, please follow the directions from the failure message, it said.

"*To include a plugin fix for this test, please edit your git-commit-plugins. Click here for more details."

Please read https://in.liferay.com/web/global.engineering/blog/-/blogs/new-tests-for-the-pull-request-tester-

Thx

**Comment by matethurzo** [comment]
Thanks Brian, didn't know about this. Does this work with sending both plugins and plugins-ee pulls along with a portal one, or just for one?

**Pull request closed without merging**
