### PR TITLE
LPS-68268 SF

### PR DESCRIPTION
**Pull request by marcellustavares**
cc @inacionery

### CODE REVIEW

**Comment by jpince** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@marcellustavares please resend. Rebase error. Thx.

**Comment by marcellustavares** [comment]
Resent to https://github.com/brianchandotcom/liferay-portal/pull/43953

**Pull request closed without merging**
