### PR TITLE
LPS-75435 SF.

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by jpince** [comment]
ci:stop

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0de4c6dd09...b50b3f7b1e

**Comment by brianchandotcom** [comment]
@brandizzi did you really mean to remove the last "end" in the FTL? I readded it back. That seemed to be a mistake.

**Comment by brandizzi** [comment]
> @brandizzi did you really mean to remove the last "end" in the FTL? I readded it back. That seemed to be a mistake.

Uh, a terrible error of mine. Thanks!

**Pull request closed without merging**
