### PR TITLE
LPS-70813 Build lang

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:stop - One of the jenkins slaves crashed so the pull request test froze.

**Comment by pyoo47** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:reopen

**Comment by rafaprax** [comment]
ci:retest

**Comment by jpince** [comment]
@rafaprax the SF failure is consistent and looks like it has something to do with RecordSetSettingsRedirectURLException.java that you created.
```
     [java] package: ./modules/apps/forms-and-workflow/dynamic-data-lists/dynamic-data-lists-api/src/main/java/com/liferay/dynamic/data/lists/exception/RecordSetSettingsRedirectURLException.java
     [java] 
     [java] (<unknown>:6705): Gtk-WARNING **: Unable to locate theme engine in module_path: "clearlooks",
...
     [java] Gtk-Message: Failed to load module "canberra-gtk-module"
     [java] Gtk-Message: Failed to load module "pk-gtk-module"
     [java] Exception in thread "main" java.lang.Exception: package: ./modules/apps/forms-and-workflow/dynamic-data-lists/dynamic-data-lists-api/src/main/java/com/liferay/dynamic/data/lists/exception/RecordSetSettingsRedirectURLException.java
```
Closing this pull.

**Comment by jpince** [comment]
ci:close

**Comment by rafaprax** [comment]
Thx @jpince

**Pull request closed without merging**
