### PR TITLE
Lps 68951

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
@jorgediaz-lr @pei-jung the sybase failure is real, you have to fix it and resend.

**Comment by jorgediaz-lr** [comment]
@shuyangzhou 
The sybase failure is caused because of missing commit with sybase logic that was removed in previous pull by @pei-jung , see explanation:
  - https://github.com/shuyangzhou/liferay-portal/pull/3548#issuecomment-265979886
  - https://github.com/shuyangzhou/liferay-portal/pull/3548#issuecomment-266505835

**Comment by pei-jung** [comment]
@jorgediaz-lr you're right. we need that commit for sybase to work. I'll resend.

**Comment by jorgediaz-lr** [comment]
Resent in https://github.com/shuyangzhou/liferay-portal/pull/3558

**Pull request closed without merging**
