### PR TITLE
LPS-82043 Include oauth2 with portal bundles

### PR DESCRIPTION
**Pull request by petershin**
@jpince Removed the suppression file to simplify things.  I'll take a look and patch SF so that its easier for devs to add standalone apps in the future

@david-truong @jeffreyyang @xbrianlee

### CODE REVIEW

**Comment by jpince** [comment]
ci:close @brianchandotcom pushed upstream, needed for beta 3 per @xbrianlee

https://github.com/liferay/liferay-portal/compare/39efa43...1799056 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchandotcom** [comment]
@david-truong see my fix in 2d10f99fe236acfebd3a8feacabee879b07b73d9

@jpince fyi

**Comment by petershin** [comment]
@jeffreyyang - do we need 2d10f99?

**Comment by petershin** [comment]
@jeffreyyang - I saw Brian's commit message.  I'm going to update the SF check based on his changes

Please let me know if its not needed

**Comment by jeffreyyang** [comment]
@petershin Thanks! I'm checking with the patcher team to see if they need it.

**Pull request closed without merging**
