### PR TITLE
LPS-66396

### PR DESCRIPTION
**Pull request by Ithildir**
cc @david-truong, @codyhoag

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:reopen

**Comment by brianchiu** [comment]
Failing poshi tests are firefox connection issues.

QA Engineering is investigating right now. See: https://issues.liferay.com/browse/LRQA-28169

**Comment by brianchandotcom** [comment]
@codyhoag this is in upstream now. Thx.

**Comment by brianchandotcom** [comment]
@davidtruong I'm publishing now. It should be up there in a few minutes.

**Pull request closed without merging**
