### PR TITLE
LPS-54676 Update builds

### PR DESCRIPTION
**Pull request by marcellustavares**
Hi Brian, this is the first module extracted for DDL, just the tests for now.

I'll be committing the remaining modules in the next days.

cc @rotty3000

Thanks

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8872460420...20dd23db2f

**Comment by brianchandotcom** [comment]
@marcellustavares do note that you moved generated files too (*PersistenceTest) They should regenerate slightly differently (SF) when regenerating from modules (I know you manually modified them which should contain the main changes)

**Comment by marcellustavares** [comment]
Yeah @brianchandotcom, it was intentional. I'll regenerate them again once I have the services extracted out.

I just didn't want to create a huge commit with all the modules at the same time.

Thanks

**Pull request closed without merging**
