### PR TITLE
LPS-102655 | LPS-103339 Run `ant format-javadoc`

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/44b5d21f9a...ee2d87705f

**Comment by brianchandotcom** [comment]
@hhuijsier fyi he ran it for the whole tree

**Comment by brianchandotcom** [comment]
@hhuijser fyi he ran this for all of master

**Comment by vicnate5** [comment]
@inacionery @hhuijser This is causing Service Builder to regen some code
https://issues.liferay.com/browse/LPS-104586

Test log result from this PR
https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/293910/AXIS_VARIABLE=0,label_exp=!master/consoleText

**Pull request closed without merging**
