### PR TITLE
Lps 80310

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by ngriffin7a** [comment]
@brianchandotcom The commits in this PR cause the new com.liferay.portlet.dependency.factory.impl module to live in $LIFERAY_HOME/osgi/modules

But you might want to change it to live in $LIFERAY_HOME/osgi/portal -- whatever you think is best.

**Comment by ngriffin7a** [comment]
@brianchandotcom "This pull contains no unique failures."

**Comment by brianchandotcom** [comment]
@ngriffin7a I think this pull conflicts with https://github.com/brianchandotcom/liferay-portal/pull/60104

**Pull request closed without merging**
