### PR TITLE
LPS-59045 Fixing use of reference

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:retest

**Comment by migue** [comment]
Please do not use the com.liferay.registry.Registry classes when you are on a module! It is not intended to use at this places

Let me know if you need help!

**Comment by matethurzo** [comment]
@migue didn't know that, sorry. Let me rewrite and I'll cc you on my next pull.

**Comment by migue** [comment]
I know you've seen this on other modules, but I don't know why it has been merged :(

**Pull request closed without merging**
