### PR TITLE
LPS-106277 Add cases to assert display correctly in specific content display fragment

### PR DESCRIPTION
**Pull request by manoelcyreno**

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@manoelcyreno @Tim-Cao fragment.json is not formatted right.

@hhuijser please enforce in SF. See portal-web/test/functional/com/liferay/portalweb/dependencies/display-collection-name.zip/document-and-media/fragment.json in this pull.

**Comment by brianchandotcom** [comment]
@manoelcyreno the reason I care about the formatting for fragment.json is because diffing this in the future is going to be a pain if everything is in one line @Tim-Cao

**Comment by hhuijser** [comment]
@brianchandotcom, SF does enforce json formatting, but skips the entire `portal-web/test/functional/com/liferay/portalweb/dependencies` directory.

See https://github.com/liferay/liferay-portal/blob/master/source-formatter.properties#L16

**Pull request closed without merging**
