### PR TITLE
LPS-151745 | master

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-151745

cc: @holatuwol
cc: @lfbesada

### CODE REVIEW

**Comment by ozysouza** [comment]
ci:reopen

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/8008

ci:test:stable - 26 out of 27 jobs passed
ci:test:relevant - 166 out of 172 jobs passed in 2 hours 28 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2fe393bc9f...8bb3afc3f7

**Comment by brianchandotcom** [comment]
@lfbesada see 19bcb0dbf558c44f2d0399af61c52db660c79230

Thx!

**Pull request closed without merging**
