### PR TITLE
LPS-151909 As a developer using headless endpoints, I'd like to update a country by countryId via partial update and full replace

### PR DESCRIPTION
**Pull request by epark18**
Manual forward from [liferay-usm#562](https://github.com/liferay-usm/liferay-portal/pull/562)

https://issues.liferay.com/browse/LPS-151909

### CODE REVIEW

**Comment by epark18** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@epark18 @drewbrokke can you resend this and change

1.)

	protected void validate(
			String a2, String a3, long companyId, long countryId, String name,
			String number)
		throws PortalException {

to

	protected void validate(
			long countryId, long companyId, String a2, String a3, String name,
			String number)
		throws PortalException {

I believe that's how we do it in our other validate methods in *ServiceImpl.java


2.) Rename validate to _validate

3.) Change

	private boolean _isConflictingCountry(
		long curCountryId, Country testCountry) {

		if ((testCountry != null) &&
			(testCountry.getCountryId() != curCountryId)) {

			return true;
		}

		return false;
	}

to

	private boolean _isConflictingCountry(
		Country country, long countryId) {

Easier to read.

**Comment by brianchandotcom** [comment]
4.)

	public void testPutCountry() throws Exception {
		super.testPutCountry();

		Country country = _addCountry(randomCountry());
		Country existingCountry = _addCountry(randomCountry());

Is that true? Is it really an existingCountry?

@epark18 @drewbrokke Sorry, I hit enter too early. Please resend based on my 4 points. Thx.

**Comment by drewbrokke** [comment]
> Is that true? Is it really an existingCountry?

@brianchandotcom it's an existing country, yes. `randomCountry()` just generates an object in memory, but `_addCountry(randomCountry())` persists it.

**Pull request closed without merging**
