### PR TITLE
LPS-95299

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by jpince** [comment]
@adolfopa @robertoDiaz errors in `central-requirements`, `modules-semantic-versioning`, and `modules-unit` all look related to the changes here.

@patriciajeanperez if they aren't able to fix today, I recommend closing, since the central-requirements failure will fail in everyone's PRs. I can probably help you to fix that one and semver if you want, and we can probably wait until tomorrow for the modules-unit fix.

central-requirements
`Redundant dependency detected in modules/apps/wiki/wiki-editor-configuration/build.gradle expected:<compileOnly project(":core:petra:petra-string")> but was:<testCompile project(":core:petra:petra-string")>`

semver
```
     [exec] > Task :apps:wiki:wiki-api:baseline FAILED
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.wiki.configuration                     MINOR      1.0.3      1.0.3      1.1.0      VERSION INCREASE REQUIRED
     [exec] 	+   interface  com.liferay.wiki.configuration.WikiFileUploadConfiguration
...
     [exec] * com.liferay.wiki.exception                         MINOR      1.1.1      1.1.1      1.2.0      VERSION INCREASE REQUIRED
     [exec] 	+   class      com.liferay.wiki.exception.WikiAttachmentSizeException
```

modules-unit
```
     [exec] 
     [exec] > Task :apps:wiki:wiki-editor-configuration:compileTestJava
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/wiki/wiki-editor-configuration/src/test/java/com/liferay/wiki/editor/configuration/internal/WikiAttachmentImageCreoleEditorConfigContributorTest.java:104: error: cannot find symbol
     [exec] 		wikiAttachmentImageCreoleEditorConfigContributor.setItemSelector(
     [exec] 		                                                ^
     [exec]   symbol:   method setItemSelector(ItemSelector)
     [exec]   location: variable wikiAttachmentImageCreoleEditorConfigContributor of type WikiAttachmentImageCreoleEditorConfigContributor
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/wiki/wiki-editor-configuration/src/test/java/com/liferay/wiki/editor/configuration/internal/WikiAttachmentImageCreoleEditorConfigContributorTest.java:165: error: cannot find symbol
     [exec] 		wikiAttachmentImageCreoleEditorConfigContributor.setItemSelector(
     [exec] 		                                                ^
     [exec]   symbol:   method setItemSelector(ItemSelector)
     [exec]   location: variable wikiAttachmentImageCreoleEditorConfigContributor of type WikiAttachmentImageCreoleEditorConfigContributor
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/wiki/wiki-editor-configuration/src/test/java/com/liferay/wiki/editor/configuration/internal/WikiAttachmentImageCreoleEditorConfigContributorTest.java:204: error: cannot find symbol
     [exec] 		wikiAttachmentImageCreoleEditorConfigContributor.setItemSelector(
     [exec] 		                                                ^
     [exec]   symbol:   method setItemSelector(ItemSelector)
     [exec]   location: variable wikiAttachmentImageCreoleEditorConfigContributor of type WikiAttachmentImageCreoleEditorConfigContributor
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/wiki/wiki-editor-configuration/src/test/java/com/liferay/wiki/editor/configuration/internal/WikiAttachmentImageCreoleEditorConfigContributorTest.java:237: error: cannot find symbol
     [exec] 		wikiAttachmentImageCreoleEditorConfigContributor.setItemSelector(
     [exec] 		                                                ^
     [exec]   symbol:   method setItemSelector(ItemSelector)
     [exec]   location: variable wikiAttachmentImageCreoleEditorConfigContributor of type WikiAttachmentImageCreoleEditorConfigContributor
     [exec] 8 errors
     [exec] 
     [exec] > Task :apps:wiki:wiki-editor-configuration:compileTestJava FAILED
```

**Comment by patriciajeanperez** [comment]
ci:close

**Comment by patriciajeanperez** [comment]
Thanks @jpince! I'll see what I can do with some of the failures and send to Brian today :)

**Comment by adolfopa** [comment]
@patriciajeanperez @jpince See https://github.com/patriciajeanperez/liferay-portal/pull/220

**Pull request closed without merging**
