### PR TITLE
LRQA-32965 Ignore basedirs that do not exist

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRQA-32965

@stmerriss @jpince @brianchiu

Fix for this ticket:
https://issues.liferay.com/browse/LRQA-32926

These are updates to Poshi that will ignore the basedirs that do not exist.

@brianchandotcom 
If this looks okay, can we do a new Poshi Release?  Thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9d29d91d15...554cf6ff71

**Comment by brianchandotcom** [comment]
@michaelhashimoto published.

**Comment by brianchandotcom** [comment]
@michaelhashimoto published.

**Comment by michaelhashimoto** [comment]
@brianchandotcom - Thanks!

**Pull request closed without merging**
