### PR TITLE
LPS-63479 SF

### PR DESCRIPTION
**Pull request by marcellustavares**
Thanks @brandizzi!

### CODE REVIEW

**Comment by brianchiu** [comment]
623Upgrade - likely a bug (unrelated to this pull) that we are investigating. But I've removed that assertion for now.

CPSites / PGSitesdirectory - those tests have been removed from the PR tester for now.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ca9857f4fa...2b49b89cfd

**Comment by brianchandotcom** [comment]
@Preston-Crary fyi

**Comment by brianchandotcom** [comment]
@shuyangzhou fyi some kernel model changes caused this upgrade failure.

**Pull request closed without merging**
