### PR TITLE
LPS-85170 can't create Virtual Instances when there are legacy portlets that use non-system roles in security-role-ref

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-85170](https://issues.liferay.com/browse/LPS-85170).<br><br>Test results here: https://github.com/drewbrokke/liferay-portal/pull/737#issuecomment-461249977.<br><br>/cc @pei-jung @stsquared99 @alee8888 @ChrisKian @NorbertKocsis @holatuwol

Related PTR: https://issues.liferay.com/browse/PTR-414

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/883378fcb2...905e4f70a7

**Comment by brianchandotcom** [comment]
@NorbertKocsis @drewbrokke see my changes in upstream. Thx.

**Pull request closed without merging**
