### PR TITLE
LPS-131550 move TransformUtil from portal-vulcan to petra-function

### PR DESCRIPTION
**Pull request by matijapetanjek**
Hi Brian, after [multiple attempts](https://github.com/liferay-headless/liferay-portal/pull/809) I wasn't able to send this PR through CI, [QA confirmed the CI errors are not related to my changes](https://github.com/liferay-headless/liferay-portal/pull/809#issuecomment-1285453088) so I'm sending it directly. Please review, thank you!

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e89d777c42...698bdc181a

**Comment by brianchandotcom** [comment]
@ling-alan-huang we have some generated classes that still use com.liferay.portal.vulcan.util.TransformUtil

But all manual classes should use com.liferay.petra.function.transform.TransformUtil going forward (master only)

Can you SF enforce? Thx.

**Comment by brianchandotcom** [comment]
@matijapetanjek fyi 1584d9a98c325c67d7c15c6a5ae2d7adb3484572

**Comment by ling-alan-huang** [comment]
got it.

**Pull request closed without merging**
