### PR TITLE
LPS-106533

### PR DESCRIPTION
**Pull request by brandizzi**
<h3><g-emoji class="g-emoji" alias="x" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/274c.png">x</g-emoji> ci:test:search - 46 out of 50 jobs passed in 2 hours 7 minutes 44 seconds 411 ms</h3>

https://github.com/brandizzi/liferay-portal/pull/959#issuecomment-573218495

Unique failures are not related, are known issues on the front end outside Search.

Author: @brandizzi

https://issues.liferay.com/browse/LPS-106533

### CODE REVIEW

**Comment by joshchong** [comment]
@brandizzi @brianchandotcom 

The `IndexNotFoundException` above is an unrelated flaky failure happening upstream. QA will be investigating.

**Comment by brianchandotcom** [comment]
@joshchong thx for letting me know.

**Comment by brianchandotcom** [comment]
@brandizzi please sort

		RenderResponse renderResponse, SearchEngineAdapter searchEngineAdapter,
		Sorts sorts, SynonymSetIndexReader synonymSetIndexReader,
		SynonymSetIndexNameBuilder synonymSetIndexNameBuilder) {

You just added a new var, unsorted, to a sorted list.

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
