### PR TITLE
Lps lps 145190 part ii

### PR DESCRIPTION
**Pull request by arthurchan35**
@brianchandotcom I have added a commit to sort names I have run source formatter and tests locally

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@arthurchan35 please resend on top of https://github.com/arthurchan35/liferay-portal/pull/161

1.) Can you lower case all the txt files

2.) the protected methods in BaseClientTestCase and BaseTokenEndpointTestCase don't make any sense because they're only used in one test class. Please simplify. I usually don't even make a base class unless 2 classes extend them.

**Comment by arthurchan35** [comment]
Hey @brianchandotcom, just to make sure:
1. I assume the text files refering to, e.g. [JWT_Nonexistent_User.txt](https://github.com/brianchandotcom/liferay-portal/pull/115283/files#diff-5df37da533dce6c553ce571722d38e8d8c7108cbb83603655b8d89f15c876854) for functional tests?
2. Okay, I will put them into the concrete test class, but the reason I created the base is that there will be new concrete tests in the future.

**Comment by brianchandotcom** [comment]
1. Yes
2. Refactor when needed (don't pre-engineer)
3. See my other changes for tiny inconsistencies

@arthurchan35

**Pull request closed without merging**
