### PR TITLE
LPS-52435 don't show pages links when uers don't have pages enabled

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by lipusz** [comment]
@juliocamarero

I think this @daef814 won't work. When you you're on a page of a site and open the my account from the navbar, the "group" will be the one related to the current scope, not the user's group.

I've tested this and didn't work for me.

What do you think?

**Comment by juliocamarero** [comment]
@lipusz what about this?

**Comment by lipusz** [comment]
So, you are suggesting to fix this issue and then, use only one class in both cases?

**Comment by juliocamarero** [comment]
I would like to keep both together since that is easier to manage, but if it doesn't work it's not a big deal, I am ok with keeping two classes too.

**Comment by lipusz** [comment]
OK, give me some time (1-2 hours), and I'll take a look at this. I'm trying to finish it and let you know about the result before Brian starts working. :-)

Is that okay for you?

Thanks!

**Comment by juliocamarero** [comment]
absolutely. I can also send you the pull to you if you prefer to review it first.

**Comment by lipusz** [comment]
Great, thank you, Julio!

**Comment by juliocamarero** [comment]
https://github.com/lipusz/liferay-portal/pull/55

**Comment by lipusz** [comment]
The issue is caused by

````java
			Portlet myAccountPortlet = PortalUtil.getFirstMyAccountPortlet(
				themeDisplay);
````

in ServicePreAction.

For some reasons, themeDisplay.getScopeGroupId returns the groupId of the Global Group when I click on the "My Pages" tab in My Account.

I'm trying to figure out where this wrong groupId comes from... Any idea?

@juliocamarero

**Comment by lipusz** [comment]
Adding

````java
			urlControlPanelSitesPortlet = HttpUtil.setParameter(urlControlPanelSitesPortlet, "doAsGroupId", themeDisplay.getScopeGroupId());
````

to 

````java
			String urlControlPanelSitesPortlet = HttpUtil.setParameter(themeDisplay.getURLControlPanel(), "p_p_id", curPortletId);

			urlControlPanelSitesPortlet = HttpUtil.setParameter(urlControlPanelSitesPortlet, "controlPanelCategory", controlPanelCategory);

			urlControlPanelSitesPortlet = HttpUtil.setParameter(urlControlPanelSitesPortlet, "doAsGroupId", themeDisplay.getScopeGroupId());
````

https://github.com/liferay/liferay-portal/blob/master/portal-web/docroot/html/portal/layout/view/control_panel_nav_main.jspf

seems to solve the problem.

The background is that when we open the MyAccount portlet, it's like a ControlPanel scope, and

PortalImpl
````java
	@Override
	public long getScopeGroupId(
			HttpServletRequest request, String portletId,
			boolean checkStagingGroup)
		throws PortalException {
````

returns the groupId of the Global (Company) Group when "doAsGroupId" is not set in the request.

What do you think?

@juliocamarero

**Pull request closed without merging**
