### PR TITLE
LPS-76369 Portlet preferences are always stored in default scope, even when a custom page scope is created

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @IstvanD

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test

**Comment by pei-jung** [comment]
ci:reopen

**Comment by IstvanD** [comment]
Hello @pei-jung 

I was wondering if you could find time to review the pull request.
Please let me know if you need explanation for the fix.

Thank you and best regards,
István

**Comment by IstvanD** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f5d0e0e1f5...099c83e9a7

**Pull request closed without merging**
