### PR TITLE
LPS-71476

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
ci:retest

**Comment by xbrianlee** [comment]
The functional test failures above are unrelated to the changes made within this pull.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/152110b658...8133a67167

**Comment by brianchandotcom** [comment]
@mhan810 you can revert 086e72aa4e9514ce466931c2d02c8f9b5968e1df on ee-7.0.x to grab the other file, fyi.

**Comment by mhan810** [comment]
@brianchandotcom no worries, we are going to have a brand new file as well.

**Comment by brianchandotcom** [comment]
@ithildir can you mirrors cache

modules/apps/portal-mobile-device-recognition-provider-fiftyonedegrees/portal-mobile-device-recognition-provider-fiftyonedegrees/src/main/resources/META-INF/51Degrees-LiteV3.2.dat

I've mirrored it at mirrors/github.com/51Degrees/Device-Detection/raw/master/data/51Degrees-LiteV3.2.dat

If they're not behind our mirrors, they can use

https://github.com/51Degrees/Device-Detection/raw/master/data/51Degrees-LiteV3.2.dat

Thx!

**Comment by Ithildir** [comment]
Done: https://github.com/brianchandotcom/liferay-portal/pull/48227

**Pull request closed without merging**
