### PR TITLE
LPS-62276 Fix portlet name

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/767ec62643...c0aab06427

**Comment by brianchandotcom** [comment]
@matethurzo @akosthurzo do we still need

PortletKeys.EXPORT_IMPORT

or can we remove that now?

**Comment by matethurzo** [comment]
@brianchandotcom we still need that, some shared functionality is being registered with that

**Pull request closed without merging**
