### PR TITLE
Lps 58561

### PR DESCRIPTION
**Pull request by shuyangzhou**
@hhuijser please take a look at https://github.com/brianchandotcom/liferay-portal/commit/cf4855ee5470e71b01f1cef82759a1f156e25353, somehow SF is not picking it up.

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @shuyangzhou

Checking for incorrect tabbing in requires SF to keep track of all the parentheses, curly braces, brackets and much more (as there is much more logic that comes into play for this). I actually gave it a shot a while ago, but it ended up being much more complicated with the current design of SF and it just got out of hand...

SF does autofix tabbing in a few places where it's easier to do (like inside if statements), but not everywhere...

**Comment by shuyangzhou** [comment]
Thanks for the explanation @hhuijser ! That's fine, just want you to check it, if this is too difficult, then no need to deal with it.

**Comment by mdelapenya** [comment]
Hi @brianchandotcom, is there anything we can do with this?

**Comment by brianchandotcom** [comment]
Hey @mdelapenya sorry for dropping the ball on this. Can you resend on top of https://github.com/mdelapenya/liferay-portal/pull/488

There's a new Test class that Ray had added that conflicts with this pull. You'll see it in the compile errors.

Thx!

**Pull request closed without merging**
