### PR TITLE
LPS-71747 Supporting config for the empty category and any context

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
\cc @adolfopa

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@4lejandrito this phrase doesn't make sense and has improper grammar

WhenNoCategoryOrContextAreSpecifiedInTheConfig

Did you mean

when neither a category nor a context are specified in the config?

or

When no category or context is specified in the config?

But the current phrase contradicts itself. Thx.

**Comment by brianchandotcom** [comment]
@4lejandrito please resend. Thx.

**Pull request closed without merging**
