### PR TITLE
LPS-102897 SF

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:lima

**Comment by ambrinchaudhary** [comment]
@austinchiang there are poshi tests failing in the Lima suite, but shouldn't be failing because of this PR... could you have a quick look to see if we may need to change them? Thank you!

**Comment by ambrinchaudhary** [comment]
ci:test:lima

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
@ambrinchaudhary Can confirm, test failures are unrelated

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4af0aa3139...564284ba0c

**Pull request closed without merging**
