### PR TITLE
LPS-68294 As a developer I can write an extension point to execute code before or after a new configuration has been saved into Config Admin

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-68294](https://issues.liferay.com/browse/LPS-68294).<br><br>/cc @pei-jung @jorgeferrer

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest - Failed due to broken distribution node.

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@drewbrokke can you resend with

ConfigurationModelListener#on* instead of #do* 

That seems to fit the pattern more. See ModelListener*

We have a store and doStore method, and we use the do* pattern when the method signatures are the same.

Also, make it more clear what the method is doing.

onAfter... on after what?

Where's the pattern for modules/apps/static/portal-configuration/portal-configuration-persistence/src/main/java/com/liferay/portal/configuration/persistence/listener/ConfigurationModelListenerException.java

Can you indicate it in a commit comment? Specifically:

```
	public final String causeMessage;
	public final Class configurationClass;
	public final Class listenerClass;
	public final Dictionary properties;
```

**Comment by drewbrokke** [comment]
Resent as https://github.com/brianchandotcom/liferay-portal/pull/44182

**Pull request closed without merging**
