### PR TITLE
LPS-109515 Mocking ServiceTrackerFactory

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
@austinchiang can you please verify all affected tests are fixed by this?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6005249a57...5ee6a638b7

**Comment by brianchandotcom** [comment]
@4lejandrito I had to roll this back. Can you resend without using mockito?

gradlew :apps:portal-search:portal-search-test-util:javadoc

Gives me this error:

```

> Task :apps:portal-search:portal-search-test-util:javadoc FAILED
/home/brian/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/org.mockito/mockito-core/1.10.8/1447cf39e9d3fe35c10168a4b6ce1f8d688bd0e/mockito-core-1.10.8.jar(org/mockito/internal/junit/JUnitTool.java):7: error: cannot access ArgumentsAreDifferent
import org.mockito.exceptions.verification.ArgumentsAreDifferent;
                                          ^
  bad source file: /home/brian/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/org.mockito/mockito-core/1.10.8/1447cf39e9d3fe35c10168a4b6ce1f8d688bd0e/mockito-core-1.10.8.jar(org/mockito/exceptions/verification/ArgumentsAreDifferent.java)
    file does not contain class org.mockito.exceptions.verification.ArgumentsAreDifferent
    Please remove or make sure it appears in the correct subdirectory of the sourcepath.
1 error

```

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/85586.

**Pull request closed without merging**
