### PR TITLE
LPS-161083 No limitation in country name 

### PR DESCRIPTION
**Pull request by Sharryxue**
Manually forward for [liferay-usm#747](https://github.com/liferay-usm/liferay-portal/pull/747). No related issue found in origin pr.

cc @drewbrokke

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2634d8f6e5...964fc11dbb

**Comment by brianchandotcom** [comment]
Hmm... I wonder if this could all be generated

@drewbrokke just a thought.

**Comment by drewbrokke** [comment]
Yeah I can see it. It could all come off of an adjustment to the model hints.

**Pull request closed without merging**
