### PR TITLE
Lps 66858 Rebase

### PR DESCRIPTION
**Pull request by tinatian**
Hi Brian,

This is a rebase of #41790 (comment).

Thanks.
Tina

### CODE REVIEW

**Comment by tinatian** [comment]
cc @marianoalvarosaiz

**Comment by marianoalvarosaiz** [comment]
Hi @brianchandotcom,
 is there any update on this pull?
Thanks in advance!

**Comment by brianchandotcom** [comment]
@tinatian can you rebase now that FP1 is out? I can increment the kernel again. Thx.

**Comment by tinatian** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/42392

**Pull request closed without merging**
