### PR TITLE
LPS-94790 SF

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by jpince** [comment]
@andresfulla error in modules-compile, can you please take a look?
```
     [exec] ERROR: The @returns tag requires a value. File: segmentsExperiences.es.js, line: 291
     [exec] ERROR: The @returns tag requires a value. File: segmentsExperiences.es.js, line: 302
     [exec] 
     [exec] > Task :apps:layout:layout-content-page-editor-web:jsdoc FAILED
```
this line: https://github.com/brianchandotcom/liferay-portal/pull/73238/files#diff-9b2962cb20550503e6f7310da0d8614cR300

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@p2kmgcl see my fix in d173d1d

If that is wrong, please send a follow up pull.

**Comment by andresfulla** [comment]
https://github.com/brianchandotcom/liferay-portal/commit/d173d1dc162671f683b9313afb59c0a286c9d427 is correct. Many thanks!

**Pull request closed without merging**
