### PR TITLE
LPS-80956

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
This one makes my life easier when I add new checks. It shouldn't be used by others.

**Comment by brianchandotcom** [comment]
@gamerson that will be nice to integrate with Eclipse / IntelliJ for the single file support....

**Comment by hhuijser** [comment]
@brianchandotcom @gamerson
I'd say don't do that. This is really only for the sake of making life easier for Peter and myself when we add a check and want to quickly only want to apply that single check on all files.

This should not be for public use!
One check can make changes to a file which can trigger other checks make changes in return, so we really should be very careful with this one.

**Pull request closed without merging**
