### PR TITLE
LPS-202062 Send notification to instance admin users after reached maximum number of guest user object entry

### PR DESCRIPTION
**Pull request by guilhermedcamacho**
CI [errors](https://github.com/liferay-objects/liferay-portal/pull/2971#issuecomment-1865093327) are not related.
cc. @thallescezar

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@thallescezar @guilhermedcamacho there's no entity named "notification" or "administrator"

_sendNotificationToInstanceAdministrators

Please rename and resend.

**Comment by guilhermedcamacho** [comment]
ci:reopen

**Comment by guilhermedcamacho** [comment]
ci:close

**Comment by guilhermedcamacho** [comment]
ci:reopen

**Pull request closed without merging**
