### PR TITLE
LPS-55613 Rename ThumbnailCapability.fetchFileEntryByImageId() to ThumbnailCapability.fetchImageFileEntry

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7291210ebb...8a169da51b

**Comment by brianchandotcom** [comment]
@izaera 

1.) InitializedDocumentRepository is still hiding

public <T extends Capability> boolean isCapabilityProvided(

In my your previous pull, https://github.com/brianchandotcom/liferay-portal/pull/26826  I commented that both isCapabilityProvided and getCapability are hidden, but you only fixed one.

2.) In the future, if you have quick subsequent pulls, please add "#ping" to the pull title, and I'll #pong it back to you before lunch time my time so we can do this faster.

3.) The best thing to speed things up is to review my reviews and apply them proactively. For example, the renaming of fetchFileEntryByImageId is something I had mentioned in a previous pull to you, so that should have been done before sending to me.

4.) Also, if you look at https://github.com/brianchandotcom/liferay-portal/pull/26826 

You missed the changes from @adolfopa see how he had 3 more commits?

5.) @adolfopa I removed 2 of your commits, because they can still override the getDocumentRepository method, so I don't see how you're stopping subclasses from anything?

6.) Thx @izaera I love these changes, and they are architecturally great and innovative. It's something I could never do as well you. But I do want to see an improvement in small details. Please see upstream for my changes. Thx!

cc @sergiogonzalez

**Comment by izaera** [comment]
Hi @brianchandotcom:

To be honest, it's nearly magic that this PR has arrived at least half correct. I have had to rebase it like seven times for the last two weeks, and, as a final step I had to redo it entirely. This was due to some commits being mixed with @adolfopa PRs so we ended up moving a commit from my PR to his and then back again. Also, I planned to add some more things to the PR but in the last moment we decided to remove it so I had to redo all again.

That caused all the mess (in addition to parallel work). But I take note and will change my workflow accordingly.

Cheers,
Ivan

**Comment by izaera** [comment]
Regarding 5): 

Maybe we could make getDocumentRepository() a final method? That way there would be no way to change documentRepository from subclasses...

**Pull request closed without merging**
