### PR TITLE
LPS-102513 Disable toolbar if there are no items

### PR DESCRIPTION
**Pull request by inacionery**
/cc @barrosdennys could you please take a look on these poshi tests? Thanks!

### CODE REVIEW

**Comment by barrosdennys** [comment]
Although this is causing test failures, poshi tests need to be fixed.

**Comment by barrosdennys** [comment]
LRQA-53088 opened.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8201444be8...ec37745dd5

**Comment by brianchandotcom** [comment]
@inacionery see ec37745

**Pull request closed without merging**
