### PR TITLE
LPS-179453 Merge tests

### PR DESCRIPTION
**Pull request by Tim-Cao**
This is only for master.

https://issues.liferay.com/browse/LPS-179453

@jkappler

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/12498

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ae797d4daa...e86e06b169

**Comment by brianchandotcom** [comment]
@Tim-Cao just a4f8cbb64e5b9ffe5590b090e926a8ce5af5ec93

**Pull request closed without merging**
