### PR TITLE
LPS-63032

### PR DESCRIPTION
**Pull request by alee8888**

### CODE REVIEW

**Comment by alee8888** [comment]
This is a resend of https://github.com/brianchandotcom/liferay-portal/pull/36393

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@alee8888 resend? PoshiRunner.test[CPMessageboards#MoveToRecycleBinMBThread] 

Thx

**Pull request closed without merging**
