### PR TITLE
LPS-123758

### PR DESCRIPTION
**Pull request by hhuijser**
Reverting all the ones where we moved *Configuration to internal.
See https://issues.liferay.com/browse/LPS-124370

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/66a187e9ea...980fb33fbb

**Comment by brianchandotcom** [comment]
@hhuijser I need you to resend this to me. I was not able to cleanly cherry pick this to 7.3.x, and I don't know what got backported / didn't get backported at this point...

so some could have been released in 7.3.x's FP which may cause even more issues if we have to support both ids.

Please resend with 7.3.x and review what was in the FP already?

**Comment by hhuijser** [comment]
ci:test:sf

**Pull request closed without merging**
