### PR TITLE
LPS-56124 default createdate and modifieddate can not be overriden

### PR DESCRIPTION
**Pull request by juliocamarero**
already reviewed by @shuyangzhou and tested by @dantewang

cc @Preston-Crary

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@Preston-Crary see 37e7ba48fe816740f67032568d0fcebc8a55cb44

Can arguments ever be null?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7fe730f94c...37e7ba48fe

**Comment by Preston-Crary** [comment]
@brianchandotcom just tested that this morning, they can't be null.  I'll reopen the ticket and resend with a test, this causes the advice to become unregistered when it shouldn't.

**Comment by Preston-Crary** [comment]
https://github.com/jonathanmccann/liferay-portal/pull/738

**Pull request closed without merging**
