### PR TITLE
LRQA-35352 | master

### PR DESCRIPTION
**Pull request by kmaria**
https://issues.liferay.com/browse/LRQA-35352

### CODE REVIEW

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d5fce73af7...1a5960c1d8

**Pull request closed without merging**
