### PR TITLE
LPS-65153 Redeploy of com.liferay.portal.search.elasticsearch makes Search unusable

### PR DESCRIPTION
**Pull request by arboliveira**
Addressed https://github.com/brianchandotcom/liferay-portal/pull/39852#issuecomment-220097955.
Sorry about the Path vs String confusion. :pensive: Revised all ambiguous variable names.

### CODE REVIEW

**Comment by arboliveira** [comment]
Test failures seem unrelated.

Also, please notice 2 files in master breaking source formatter at this moment:

`modules/apps/collaboration/blogs/blogs-editor-configuration/src/main/java/com/liferay/blogs/editor/configuration/BlogsContentEditorConfigContributor.java`

`modules/apps/web-experience/export-import/export-import-resources-importer-test/src/testIntegration/resources/com/liferay/exportimport/resources/importer/test/dependencies/WEB-INF/liferay-plugin-package.properties`

**Comment by evannagayama** [comment]
ADT RSS failures unrelated. Should be merged soon https://github.com/brianchandotcom/liferay-portal/pull/39945

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b7fcabd01a...1d1b629b9a

**Comment by brianchandotcom** [comment]
Thx @arboliveira please see my changes in upstream. Much more clear this time!

**Pull request closed without merging**
