### PR TITLE
LPS-141509 SF

### PR DESCRIPTION
**Pull request by rodrigocunhaa**

### CODE REVIEW

**Comment by rodrigocunhaa** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@PauloVAS 

```
	macro addLayoutBlockViaUI {
        Click(locator1 = "ObjectAdmin#ADD_BLOCK_BUTTON");
            Type(
                locator1 = "ObjectAdmin#TAB_LABEL_NAME",
                value1 = "${blockName}");
            Click(
                key_tab = "Save",
                locator1 = "Button#TAB_SUBMIT_BTN");	
    }
```

@rodrigocunhaa please resend. This SF is even worse than before. Please fix.

**Comment by PauloVAS** [comment]
ci:reopen

**Comment by PauloVAS** [comment]
@brianchandotcom, fixed! [110440](https://github.com/brianchandotcom/liferay-portal/pull/110440)

**Pull request closed without merging**
