### PR TITLE
LPS-94612 Allow preview into asset publisher

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
cc: @jkappler

**Comment by jpince** [comment]
@ealonso @jkappler @brianchiu @kyle-miho didn't see these int test failures in upstream this morning, might be related?

**Comment by kyle-miho** [comment]
@jpince Investigating, I think its pretty likely its related

**Comment by kyle-miho** [comment]
Actually sorry, I cant investigate it currently, int tests cannot be run in Windows currently

**Comment by jkappler** [comment]
@kyle-miho, @jpince, will check

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
ci:close

**Pull request closed without merging**
