### PR TITLE
LPS-98280 | Apply new Portlet URL utilities in calendar-web

### PR DESCRIPTION
**Pull request by inacionery**
Hi @jbalsas ,

This is continuation of https://github.com/julien/liferay-portal/pull/153 and https://github.com/jbalsas/liferay-portal/pull/1930.

In this PR, we are defining base URLs in backend, and forwarding it to frontend, where it is modified. This practice is common throughout portal. The current solution, that we are replacing, relies on old `Liferay.PortletURL` utility to set a default base URL, a value [hardcoded in utility](https://github.com/liferay/liferay-portal/blob/7f73d850931e4e52b9ca9ee05b44282644a1ec24/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/portlet_url.js#L57). The new `Liferay.Util.PortletURL` utility does not have that hardcoded value, instead requiring base value as an argument.

The alternative to solution in this PR would be to re-introduce hardcoded default url to util, but I believe it makes more sense to standardize usage in the app, to get it from backend. This app is the only or one of two places in portal using the default value.

Please review the code.

Thank you!

/cc @kresimir-coko @inacionery

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1bd4c36fb1...34b0e2d1c2

**Comment by brianchandotcom** [comment]
@jbalsas I'm merging this.. please intercept if you disagree.

**Comment by jbalsas** [comment]
Thanks for the heads up, @brianchandotcom!

This one was already reviewed, we're trying to route PRs through the teams every time we can.

**Pull request closed without merging**
