### PR TITLE
LPS-64814

### PR DESCRIPTION
**Pull request by mikakoivisto**
LPS-64814 Verify process is required for existing installs as we need to provide a patch for all customers for this security issue as upgrade processes are not run when there is no version change.

### CODE REVIEW

**Comment by pyoo47** [comment]
[integration-hypersonic20-jdk7 AXIS_VARIABLE 1 ](https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3065/AXIS_VARIABLE=1,label_exp=!master/)build timed out after two hours because an error occurred during Portal startup.
```
    [junit] Executing verifiers registered for com.liferay.journal.service
    [junit] Executing verifiers registered for com.liferay.document.library.service
    [junit] transaction rollback: serialization failure
    [junit] transaction rollback: serialization failure
    [junit] 09:16:22,972 ERROR [main][JavaFieldsParser:74] Unable to load class com.liferay.social.kernel.model.SocialActivityConstants
    [junit] java.lang.ClassNotFoundException: com.liferay.social.kernel.model.SocialActivityConstants cannot be found by com.liferay.bookmarks.web_1.0.5
    [junit] 	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:444)
    [junit] 	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:357)
    [junit] 	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:349)
```

**Comment by brianchandotcom** [comment]
@ZoltanTakacs can you own this for master too? @mikakoivisto says we need it for Verify, but I remember another comment you made in ee-6.2.x where you didn't want a verify to happen for support?

@mikakoivisto if we had to have it in verify, we should make it lighter? Perhaps do a quick check to see if we even need to run it?

Thx

**Comment by lipusz** [comment]
Hi @brianchandotcom 

We talked about this with Zoltán.

When you say
>@mikakoivisto if we had to have it in verify, we should make it lighter? Perhaps do a quick check to see if we even need to run it?

do you mean, we should move the logic from the VerifyCompany to CompanyImpl.getKeyObj, catch the "InvalidKeyException" and do the update on-the-fly?

**Comment by ZoltanTakacs** [comment]
Hi @brianchandotcom,

@zsoltbalogh and I [discussed](https://github.com/brianchandotcom/liferay-portal-ee/pull/12989#issuecomment-214695866) this issue with the Security SME @lipusz, and he is working with @mikakoivisto and @topolik on an workaround for 6.2. 

https://issues.liferay.com/browse/LPS-64814 is also updated with the details.

- For master it's OK to add this verify as long as we clearly states for the users whose coming from 7.0 GA1 and wants to "upgrade" to 7.0 GA2 that they should use the Verify Processes. 
- Or revert this LPS entirely and proceed with another solution which would be lighter, something like which can be released for 6.2.

**Comment by mikakoivisto** [comment]
The verify was for existing envs where upgrade doesn't trigger because the db is already at that version. But since apparently that is something we can't have our customers run then we can ignore it.

**Pull request closed without merging**
