### PR TITLE
LPS-73472

### PR DESCRIPTION
**Pull request by Ithildir**
cc @jbalsas

### CODE REVIEW

**Comment by jbalsas** [comment]
Awesome, @Ithildir, thanks so much for this!! 🎉

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:reopen

**Comment by michaelhashimoto** [comment]
ci:stop

**Comment by michaelhashimoto** [comment]
ci:retest - https://loop.liferay.com/home/-/loop/feed/6170033

**Comment by Ithildir** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
