### PR TITLE
LPS-72638 Improve error messages

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest - https://loop.liferay.com/home/-/loop/feed/5383061

**Comment by adolfopa** [comment]
ci:reopen

**Comment by adolfopa** [comment]
ci:retest

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/49099

**Pull request closed without merging**
