### PR TITLE
LPS-67830 Allow administrators to configure captcha using System Settings, allowing export and import of configurations

### PR DESCRIPTION
**Pull request by pei-jung**
https://issues.liferay.com/browse/LPS-67830
https://issues.liferay.com/browse/LRQA-30920

/cc @xbrianlee @drewbrokke @jorgeferrer

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:reopen

**Comment by pei-jung** [comment]
ci:retest

**Comment by brianwulbern** [comment]
All three Poshi test failures are related to SPA loading issues
cc @jpince

@pei-jung SQLInstrTest.testInstrNotFound failed in the same way on both CI runs, with this output:
```
 [junit] Thread Thread[Framework Event Dispatcher: Equinox Container: b0c8bbfb-a50e-0017-1908-ae43a622fe2d,5,main] caught concurrent failure: java.lang.AssertionError: {level=ERROR, loggerName=osgi.logging.com_liferay_portal_osgi_web_portlet_tracker, message=FrameworkEvent ERROR 
    [junit] java.lang.AssertionError: {level=ERROR, loggerName=osgi.logging.com_liferay_portal_osgi_web_portlet_tracker, message=FrameworkEvent ERROR 
    [junit] 	at com.liferay.portal.test.rule.LogAssertionAppender.append(LogAssertionAppender.java:61)
```

**Comment by jpince** [comment]
@pei-jung here's the console output. Can you please look into this failure?
https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=4,label_exp=!master/81034/console

Closing this pull.

**Comment by jpince** [comment]
ci:close

**Comment by pei-jung** [comment]
Hey @jpince, the test failures don't seem related. I'll run the test again and see if the failures persist. PR resent here https://github.com/brianchandotcom/liferay-portal/pull/47776.

**Pull request closed without merging**
