### PR TITLE
Revert "LPS-70693 Ignore all adaptive-media tests until they are fixed"

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @brianchandotcom 

See commit https://github.com/liferay/com-liferay-adaptive-media/commit/bf4d4dfb9058991ff6519336e2aa403ce19bcaae in the Adaptive Media repo for the actual fix. The problem was a demo data creator module that had the .lfrbuild-portal file by mistake.

This reverts commit 9aafe42df62a5548862081a8e81a7f4d300bb53f.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:retest

**Comment by adolfopa** [comment]
ci:reopen

**Comment by adolfopa** [comment]
Everything passed on this PR https://github.com/adolfopa/liferay-portal/pull/566, and here it is failing only on Postgres.

**Comment by brianchandotcom** [comment]
AdaptiveMediaImageEnableConfigurationTest has a flaky test. Please fix.

```
test-portal-acceptance-pullrequest-batch(master)/modules-integration-postgresql94-jdk8

Job Results:

5988 Tests Passed.
8 Tests Failed.

AXIS_VARIABLE=0,label_exp=!master #119536
AdaptiveMediaImageEnableConfigurationTest.testDoesNotSendAMessageToTheMessageBusIfAlreadyEnabled
AdaptiveMediaImageEnableConfigurationTest.testEnableAllConfigurationEntries
AdaptiveMediaImageEnableConfigurationTest.testEnableConfigurationEntryWithExistingDisabledConfiguration
...
```

**Pull request closed without merging**
