### PR TITLE
LPS-99218 Prevent NPE when adding fragment through JSON WS call by skipping validation of HTML code

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3bb4924d4f...b2b26a6080

**Comment by brianchandotcom** [comment]
lbm:backport @CsabaTurcsan @jpince @zsoltbalogh

**Comment by brianchandotcom** [comment]
@jkappler @ruben-pulido I backported this... since it's a regression.

**Pull request closed without merging**
