### PR TITLE
LPS-73691 SF

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @sharonchoi @austinchiang @patriciajeanperez

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@sergiogonzalez @4lejandrito can you resend this?

1.) Is this supposed to be a sentence or a title? It's neither right now

mark-all-notifications-as-read=Mark all notifications as read

See titlecapitalization.com if it's supposed to be a title.

2.) I found it weird that you renamed all of markAsRead to markNotificationAsReadURL

But then you added a new class MarkAsReadPortletConfigurationIcon.

Doesn't it make things more inconsistent? Please resend. Thx.

**Comment by sergiogonzalez** [comment]
Resent here https://github.com/brianchandotcom/liferay-portal/pull/50546

**Pull request closed without merging**
