### PR TITLE
LPS-105027 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LPS-105027

### CODE REVIEW

**Comment by john-co** [comment]
cc/ @eduardoallegrini, @marcoscv-work

**Comment by marcoscv-work** [comment]
@john-co can I do something?

**Comment by john-co** [comment]
@marcoscv-work you can try resending the PR and hope we get lucky. There's a chance it can run into the same issue but I think that's all we could do until CI issue gets fixed.

**Comment by john-co** [comment]
resent in https://github.com/brianchandotcom/liferay-portal/pull/81727

cc/ @marcoscv-work

**Pull request closed without merging**
