### PR TITLE
master-lps-56435

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LPS-56435

@brianchandotcom 
Please review the code changes because this pull contains stuff from QA and from devs.

For this pull, the reason why it has Eudaldo's changes is because wcm team knew the change would break frontend tests so they wanted to commit the changes and test fixes at the same time.

CC @juliocamarero
CC @evannagayama 
CC @ealonso

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/48b6d4959b...7377c72839

**Comment by brianchandotcom** [comment]
@ealonso very very cool!

**Comment by brianchandotcom** [comment]
@evannagayama and you too bro :)

**Comment by juliocamarero** [comment]
@ZoltanTakacs could you please backport this one too? thanks! :+1:

**Pull request closed without merging**
