### PR TITLE
LPS-73224 Remove unnecessary usages of BeanParamUtil in blogs web.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@Preston-Crary please backport .Thx.

**Comment by brianchandotcom** [comment]
@Preston-Crary I take it back. Not merging.. this makes the code very hard to read.

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/49881

**Pull request closed without merging**
