### PR TITLE
[Remove Stream usages in method body:asset-test]Lps 175901 stream

### PR DESCRIPTION
**Pull request by dantewang**
FYI @shuyangzhou @tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a94dac72da...527ff72594

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5f7d0302a5...5f7d0302a5

**Comment by brianchandotcom** [comment]
@slnn see c2ac064fc71f1cceb232aa025b0c7f68479bf704

**Pull request closed without merging**
