### PR TITLE
LPS-67914 Move .gitignore into the theme

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jpince** [comment]
@brianchandotcom please merge this pull ASAP. All pulls are automatically closing until this fix is merged.

@jbalsas thanks for the fix!

**Comment by brianchiu** [comment]
@jbalsas The lpkg batches are also failing with this error. This also looks related?

````
/opt/dev/projects/github/liferay-portal/modules/build-app-module.xml:278: Warning: Could not find file /opt/dev/projects/github/liferay-portal/bundles/deploy/porygon-theme.war to copy.
````

**Comment by brianchiu** [comment]
CC @mtambara LPKG failures

**Comment by kenjiheigel** [comment]
@brianchandotcom, this should be merged as well: https://github.com/brianchandotcom/liferay-portal/pull/43711. That will disable the porygon theme from the build until the Windows issue (described in that pull) is fixed and the lpkg error in this pull is fixed.

**Comment by brianchandotcom** [comment]
@jbalsas we have a console.log('holakease');  as part of this? Is that on purpose?

I moved in the .gitignore but not the other stuff. Shouldn't the gulpfiles have some sort of reuse between the different themes?

**Comment by jbalsas** [comment]
Hey @brianchandotcom, so sorry about that 😱 

I'll remove and resend.

Yes, we have a plan to use some of the `liferay-theme-tasks` features to publish this gulp file as a module and reuse it across all of them. We're just trying to figure out the right build (like this missing pieces now) before extracting it into a separate module.

**Comment by brianchandotcom** [comment]
@jbalsas sounds good. Please extract one day :) When possible, DRY https://en.wikipedia.org/wiki/Don%27t_repeat_yourself

**Comment by jbalsas** [comment]
will do! 

/cc @Robert-Frampton

**Comment by Robert-Frampton** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/43719

**Pull request closed without merging**
