### PR TITLE
LPS-65017 Standardize shopping to new portlet structure

### PR DESCRIPTION
**Pull request by peterfellwock**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by peterfellwock** [comment]
@brianchandotcom these Poshi errors seem unrelated, but I think its the same issue as Polls where the Portlet Keys do not propagate to the running server.

**Comment by kenjiheigel** [comment]
Yeah, this one is related to the Portal Instance set up in the functional test. Sorry for the flakiness.

**Comment by brianchandotcom** [comment]
ci:retest (just for fun)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1c1c36d77e...2be9d8b3af

**Pull request closed without merging**
