### PR TITLE
LPS-69211 Move the User file uploads settings UI from Server Administration to System Settings

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-69211](https://issues.liferay.com/browse/LPS-69211).<br><br>/cc @jorgeferrer @pei-jung

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:retest

**Comment by drewbrokke** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@drewbrokke 

modules/apps/foundation/users-admin/users-admin-service/bnd.bnd

has a reference to 

Liferay-Require-SchemaVersion: 1.0.0

and 

modules/apps/foundation/users-admin/users-admin-service/build.gradle

has a reference to 

provided group: "com.liferay", name: "com.liferay.portal.upgrade", version: "2.0.0"

Please remove unused references. There may be more.

I'm not sure:

portal-kernel/src/com/liferay/users/admin/kernel/settings/UserFileUploadsSettings.java

should be in *.settings.* because it doens't use anything from the com.liferay.portal.kernel.settings.* API.

It's not like BlogsGroupServiceSettings

Please resend.

Thx.

**Comment by drewbrokke** [comment]
> provided group: "com.liferay", name: "com.liferay.portal.upgrade", version: "2.0.0"
So instead I should use 1.0.0? I do need the package - is this a case of "use the lowest possible version"?

> Liferay-Require-SchemaVersion: 1.0.0
This is not required for the UpgradeProcess to run?

**Comment by drewbrokke** [comment]
> I'm not sure:

> portal-kernel/src/com/liferay/users/admin/kernel/settings/UserFileUploadsSettings.java

> should be in .settings. because it doens't use anything from the com.liferay.portal.kernel.settings.* API.

I'm following the pattern of `portal-kernel/src/com/liferay/portal/kernel/security/ldap/LDAPSettings.java`, but I see what you mean - it's not in a *settings* package either.

**Pull request closed without merging**
