### PR TITLE
LPS-51081 Update recommended ANT_OPTS

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7b7d542b26...6dbaaa3d3e

**Comment by brianchandotcom** [comment]
@Ithildir @michaelhashimoto can you see what is wrong with Poshi? Thx.

**Comment by brianchandotcom** [comment]
@brianchiu we may need you to fix Poshi tests, master broken

**Comment by brianchandotcom** [comment]
@Ithildir @brianchiu @michaelhashimoto  nvm, another team found it. It was a true bug.

**Comment by brianchiu** [comment]
Ah ok.

**Pull request closed without merging**
