### PR TITLE
LPS-55479

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@brianchandotcom hey Brian, there are a lot of commits in this PR.  Let me know if you want Tina and I to squash it down or it's ok.

**Comment by mhan810** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4c82867a2a...ddf02d36e3

**Comment by brianchandotcom** [comment]
@tinatian @mhan810 I found a some typos / possible bugs in the BND file. Can you guys review my changes in upstream? Thx.

**Comment by tinatian** [comment]
Hi Brian, 
I checked the changes, everything is fine, thanks for fixing it.

Tina.

**Pull request closed without merging**
