### PR TITLE
LPS-85984 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-85984

### CODE REVIEW

**Comment by kyle-miho** [comment]
./cc @jkappler

**Comment by kyle-miho** [comment]
c

**Comment by brianchandotcom** [comment]
@hhuijser fyi

**Comment by kyle-miho** [comment]
@brianchandotcom doing some extra testing real quick first, to be sure its not used anywhere

**Comment by kyle-miho** [comment]
ci:stop

**Pull request closed without merging**
