### PR TITLE
Lps 80295

### PR DESCRIPTION
**Pull request by shuyangzhou**
@matethurzo @pavel-savinov @zoltancsaszi the pull https://github.com/brianchandotcom/liferay-portal/pull/59442 caused following test failures:
```
com.liferay.blogs.internal.exportimport.test.BlogsExportImportTest.testExportImportAssetLinks
com.liferay.blogs.internal.exportimport.test.BlogsExportImportTest.testExportImportDeletions
com.liferay.blogs.internal.exportimport.test.BlogsExportImportTest.testUpdateLastPublishDate
com.liferay.adaptive.media.journal.internal.exportimport.data.handler.test.AMJournalArticleStagedModelDataHandlerTest.testStagedModelDataHandler
```
See https://test-1-23.liferay.com/job/test-portal-acceptance-upstream-batch(master)/10708/ for more details.
Please fix those tests and resend.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by matethurzo** [comment]
hey @shuyangzhou @brianchandotcom thanks for letting me know. would it be possible next time to just ignore the test while we fix it?

i've reverted the reverts just to find out it's not allowed to do it by CI, now i have to redo the thing.
it would have been easier/faster just to fix the tests and enable them again.

also @jpince FYI the errors reported by Shuyang was fixed here: https://github.com/brianchandotcom/liferay-portal/pull/59572 Jason pushed it to upstream but today it was no sign of the code. Not sure what happened, but this is solving the problems.

re-sent the whole stuff here: https://github.com/brianchandotcom/liferay-portal/pull/59650

thanks again

**Comment by shuyangzhou** [comment]
@matethurzo you suppose to do a range cherry pick for the original commits, rather than revert the revert.

**Comment by matethurzo** [comment]
@shuyangzhou yeah i realized that now :) what i meant that generally from my perspective it would be simpler to ignore the tests so we can work on them, but i might be missing some context here.

**Comment by shuyangzhou** [comment]
@matethurzo we prefer revert over ignore in most cases. This is because during the ignore time, other regressions could sneak in and sometimes developers might even forget to turn a few of them back on (assuming there are multiple affected tests). Revert is generally a safer approach, and it only takes a bit effort to cherry pick them back when they get fixed.

**Comment by matethurzo** [comment]
@shuyangzhou got it, yes that's what i assumed being a concern. thanks

**Pull request closed without merging**
