### PR TITLE
LPS-84774 Construct a different URL depending on document type

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @adolfopa

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1df0315fc5...c98e64d4db

**Comment by brianchandotcom** [comment]
@adolfopa @sergiogonzalez see 0e4306a8834a65562cca01aec8a69db10553ed8b and c98e64d4db7b7a996f0be6257f3ca6dec2f03119

Thx!

**Pull request closed without merging**
