### PR TITLE
LRCI-2150 Remove deprecated file

### PR DESCRIPTION
**Pull request by vicnate5**
@john-co @kyle-miho @kenjiheigel @Tim-Cao 

This saves at least 68 hours of server time from upstream builds (for context, total server time is ~70 days for that build), and saves at least 10 hours of server time from acceptance builds (total server time is ~13 days). Also shaves off ~3 minutes from PortalSmoke#Smoke (without these changes, it takes ~8 minutes).

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/acdb994aed...306b8b9c81

**Comment by brianchandotcom** [comment]
Great job @Tim-Cao @vicnate5  this is a big deal!

**Comment by brianwulbern** [comment]
@vicnate5 can we backport this to 7.3, or are we reviewing test results for the change somewhere?

**Comment by brianwulbern** [comment]
https://github.com/brianwulbern/liferay-portal-ee/pull/831

**Pull request closed without merging**
