### PR TITLE
LPS-74801 Auto

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@ealonso minor change in upstream. fyi.

**Comment by brianchandotcom** [comment]
@ealonso can you avoid compound PKs? It makes upgrades very difficult.

See LayoutPageTemplateFragment, we should still give it an layoutPageTemplateFragmentId

Sorry I didn't catch it earlier.

Thx!

**Comment by ealonso** [comment]
see: https://github.com/brianchandotcom/liferay-portal/pull/51856

**Pull request closed without merging**
