### PR TITLE
LPS-75100 petra-nio

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
Here's a pull to fix the SF failure in upstream:
#52154

**Comment by brianchandotcom** [comment]
ci:retest just to be safe...

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8185ea15ab...21379e5da4

**Pull request closed without merging**
