### PR TITLE
LPS-72708 Improve performance upgrade method hasColumn & Unit and integration tests 

### PR DESCRIPTION
**Pull request by achaparro**
cc @marianoalvarosaiz
cc @NorbertKocsis

### CODE REVIEW

**Comment by achaparro** [comment]
ci:reopen

**Comment by achaparro** [comment]
Reopened since the failed tests doesn't seem to be related and it happens in other pulls:
https://github.com/brianchandotcom/liferay-portal/pull/49964

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by achaparro** [comment]
Hi @brianchandotcom,

Did you have the chance to review this pull? The two failed tests seem not to be related.

Thanks.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/391a05b59c...5fa7450ae3

**Comment by brianchandotcom** [comment]
@achaparro @marianoalvarosaiz @NorbertKocsis please see my changes in upstream. Thx.

**Pull request closed without merging**
