### PR TITLE
Lps 72604

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c850a42667...067e809875

**Comment by brianchandotcom** [comment]
@Preston-Crary @shuyangzhou please backport. Thx.

**Comment by shuyangzhou** [comment]
@tomwang2011 please add this to the backport queue, do this after the trash one.

**Comment by shuyangzhou** [comment]
@tomwang2011 I reverted this one for the concurrent bottleneck, hold off on backporting, until we find a fix and readd it in master first.

**Pull request closed without merging**
