### PR TITLE
LPD-25582 No matter how you paginate it, an empty result is always ju…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…st an empty result.

@tiantian @vicnate5 backport is needed for LXC, this is an important cache fix, please advise them to apply it asap. Thanks!

@victorhcunha this affects all test cases, and it should drop DB usages, please check.

CC @dantewang

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/730ec57f92...89baf08ab6

**Comment by slnn** [comment]
Update from @victorhcunha:
The partial results have been updated in:https://docs.google.com/spreadsheets/d/1ezAmM0O7Day3daNFM8laM4LUx6J2k7tdc6qcjo-qi10/edit#gid=0

**Comment by victorhcunha** [comment]
Hi @shuyangzhou !
You can see the results [here](https://docs.google.com/spreadsheets/d/1ezAmM0O7Day3daNFM8laM4LUx6J2k7tdc6qcjo-qi10/edit#gid=0)

I did not find any relevant differences in the DB us field generated by the benchmark during the tests, so I ran the all-sql-log (following the [comment](https://github.com/brianchandotcom/liferay-portal/pull/150240#issuecomment-2106221181)) for the login.

Please let me know if any other adjustments are needed.
cc @slnn

**Comment by slnn** [comment]
Hi @victorhcunha

Thanks for testing! 

I have checked test results,  your test results are right, you should not see any difference as the features that the pr will affect are disabled in our test configurations, I am working on removing these customized configurations, and I will let you  know when you can start to retest as soon as possible.

Lily

**Comment by victorhcunha** [comment]
Hi @shuyangzhou!
You can see the partial results here:

**Login Testcase**
Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | DB CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | --
Baseline | 624ebc3 | 7854 | - | 261 | 9,10,9 | 87,88,85
PR | - | 7978 | 1.578813344 | 259 | 9,9,10 | 87,89,88


**DocumentLibrary Testcase**
Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | Mean Time of Add DL File | DB CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | -- | --
Baseline | 624ebc3 | 5833 | - | 90.6 | 134 | 7,7,7 | 55,57,58
PR | - | 5845 | 0.2057260415 | 92 | 136 | 7,7,7 | 57,59,63



**WebContent Testcase**
Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | Mean Time of View Page | DB CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | -- | --
Baseline | 624ebc3 | 10820 | - | 133 | 32.6 | 3,3,3 | 66,73,74
PR | - | 10821 | 0.009242144177 | 147 | 43.2 | 3,3,3 | 66,70,73


The AssetPublisher testcase is still runing.

For more details you can check in this [google doc](https://docs.google.com/spreadsheets/d/1M6VK8GtY9kkv1EwhGW7vwrEENSzyT7zKz-wOh11ZHBo/edit#gid=289870423)

cc @slnn

**Pull request closed without merging**
