### PR TITLE
Lps 81651

### PR DESCRIPTION
**Pull request by shuyangzhou**
@slnn I think this may add some overhead due to the additional attribute fetching and setting, please verify.
@ngriffin7a in this case this adds a noticeable performance regression, we will disable it from liferay-portlet.tld, but keeping the java file changes.

### CODE REVIEW

**Comment by ngriffin7a** [comment]
@shuyangzhou liferay-portlet.tld should only be activated if a JSP opts-in to Portlet 3.0 with the "http://xmlns.jcp.org/portlet_3_0" taglib URI, see: https://github.com/liferay/liferay-portal/blob/master/util-taglib/src/META-INF/liferay-portlet.tld#L8

Legacy JSPs that use the "http://java.sun.com/portlet_2_0" taglib URI should activate the Portlet 2.0 version of the TLD here: https://github.com/liferay/liferay-portal/blob/master/util-taglib/src/META-INF/liferay-portlet_2_0.tld#L8

**Comment by shuyangzhou** [comment]
@ngriffin7a ok, that's good, so basically no one is using this now. @slnn, no need of testing then.

**Comment by brianchandotcom** [comment]
@ngriffin7a minor change in c8626b71d82d9f9bc8f955ec3753617c6823e99e

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
