### PR TITLE
LPS-139107 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-139107

This is only for master.

@vicnate5

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. No need to run ci:test:relevant. Additionally, ci:test:sf passed. Poshi validation passed and Case passed on local.
See https://github.com/liferay-echo/liferay-portal/pull/5819
✔️ ci:test:sf - 1 out of 1 jobs passed in 4 minutes

**Comment by Tim-Cao** [comment]
Hi @brianchandotcom, I didn't migrate script file related to information template in this PR since master code not synced yet. See https://github.com/brianchandotcom/liferay-portal/pull/106979
I will send follow up PR once master synced.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0c01fdab7f...9ed2b3bb1d

**Pull request closed without merging**
