### PR TITLE
LPS-170299 Implement merge of FDS Autocomplete and Selection filters

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://issues.liferay.com/browse/LPS-170299

### References

- [LPS-170299 Implement merge of FDS Autocomplete and Selection filters](https://issues.liferay.com/browse/LPS-170299)
- This is a followup on https://github.com/liferay-frontend/liferay-portal/pull/2893

### What is the goal of this PR?

Hey @liferay-objects ! We are merging Autocomplete and Selection FDS filters. They are very similar, with a lot of code duplication. After this PR, autocomplete will be a feature of `SelectionFilter`, with relevant UI activated by `autocompleteEnabled` prop. 

Original intention was to migrate filter usages in separate PRs, but there is a [problem with format of preloaded data](https://github.com/liferay-frontend/liferay-portal/pull/2893#pullrequestreview-1217656977). The format is currently different in Autocomplete and Selection filters. As this is currently used only in `objects-api`, it makes sense to make the migration along with the original changes in `frontend-data-set` modules. When we are already making the change, I took the opportunity to rename awkward `itemsValues` into `selectionFDSFilterItems`, changing the related code in `objects-api`.

**Please review the parts in `objects-api`**! If you wish, feel free to review the FI parts as well :slightly_smiling_face: 

Note that two filters in Objects scope, 'one-to-many' and 'create/modify' data, do not seem to get applied to data. This seems to be a bug in `master`. Filter odata string, before and after this PR, should be the same.

### What does it look like?

Some trivial changes in UI, padding of filter items.

screen

### Steps to reproduce

1. Deploy `frontend-data-set-sample-web`.
2. Place `Frontend Data Set Sample` widget on any page.
3. Create an Object, based on Frontend Data Set Samples
4. Create a View, with some preloaded values for filters

cc: @markocikos

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:reopen

**Comment by marcelabc** [comment]
Sending directly because the unique failures are flaky: https://testray.liferay.com/home/-/testray/case_results?tab=runs&testrayBuildId=2148928434

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c12145fb1c...ba2cd4460c

**Comment by brianchandotcom** [comment]
@markocikos @marcelabc see b00cf7b9

**Pull request closed without merging**
