### PR TITLE
LPS-96819 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-96819

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2477a0d680...1dc505bb09

**Comment by brianchandotcom** [comment]
@austinchiang do you know about this error

```
 
     [exec] Invalid property value 'Content Page Review' for property name 'testray.main.component.name'
     [exec] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/collaboration/notifications/ContentPageReviewNotifications.testcase:7
     [exec] 
     [exec] Invalid property value 'Content Page Review' for property name 'testray.main.component.name'
     [exec] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/experiencemanagement/ContentPageReview.testcase:6
     [exec] 
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':writePoshiProperties'.
     [exec] > Process 'command '/opt/java/jdk1.8.0_121-x64/bin/java'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':writePoshiProperties'.
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
     [exec] 	at org.
```

**Comment by austinchiang** [comment]
@brianchandotcom let me take a look

**Comment by austinchiang** [comment]
@brianchandotcom I added that property in a prior pull: https://github.com/brianchandotcom/liferay-portal/pull/77363/commits/5c56feb53b34e14fc246c65867887632f727ae51#diff-66d24afc65d5a682dc718d87a8b0adeeR2505 Everything should be passing when your origin is synced with upstream

**Pull request closed without merging**
