### PR TITLE
Lps 55991

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
Ugh, the error is not caused by this pull, should be caused by the previous snapshot changes.

Need to re-profile it, trying to take down the heap size.

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d2d7facd0d...3d5366d3cd

**Comment by brianchandotcom** [comment]
@willnewbury I merged it in, but it seems just as noisy as before?

**Comment by willnewbury** [comment]
@brianchandotcom @shuyangzhou there is another pull request that updates the plugins side - most of the output comes from there (this pull is mostly for consistency). Shuyang said that he sent it to you, but from what I can see there was a mixup - I'll send you it now.

Sending you a copy of pull request https://github.com/shuyangzhou/liferay-plugins/pull/56

**Pull request closed without merging**
