### PR TITLE
Upgrade Process: Safely upgrade Journal when running against certain databases as Oracle

### PR DESCRIPTION
**Pull request by migue**
@achaparro, @juliocamarero

### CODE REVIEW

**Comment by migue** [comment]
Not related but let's ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/99f24865aa...12a1e8bc68

**Comment by juliocamarero** [comment]
:+1:

**Comment by achaparro** [comment]
Great!

Thanks @migue!

**Pull request closed without merging**
