### PR TITLE
LPS-71181 SF

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7fdc8ca3f4...193ce65d0f

**Comment by brianchandotcom** [comment]
@jbalsas please backport. Thx.

**Comment by jbalsas** [comment]
Hey @brianchandotcom, these changes are master only. They affect a new feature that is not backported, so there's no need to backport ☺️

**Pull request closed without merging**
