### PR TITLE
LPS-65671

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Related to https://github.com/brianchandotcom/liferay-portal-ee/pull/13775

I'll think of a better way to deal with this, because we'll have more cases like these in the future.

**Comment by hhuijser** [comment]
@brianchandotcom 

Go ahead and reopen brianchandotcom/liferay-portal-ee#13775
That one is good to go.

**Comment by jpince** [comment]
Failed at      [exec] Synchronizing with GitHub. ("status":"queued"). ci:retest

**Comment by jpince** [comment]
looks good from a poshi perspective, failure related to [LRQA-26205](https://issues.liferay.com/browse/LRQA-26205)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/75f0f360a4...16f6af5946

**Pull request closed without merging**
