### PR TITLE
LPS-88323 Use ecma5

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@carloslancha merged.

**Comment by jpince** [comment]
@carloslancha @brianchiu @kyle-miho a lot of POSHI failures introduced by this pull failing `SitePages.configurePage`
```
Element is not present at "xpath=(//div | //li)[contains(@class,'open') or contains(@class,'show')]//*[normalize-space(text())='Configure']"
```

**Comment by brianchiu** [comment]
@carloslancha @jpince 
Unfortunately those failures are real. I am confirming to be sure, but I am pretty certain this causes quite a few bugs in pages administration (cannot configure pages or reorder pages), site navigation (cannot add items to nav menus), and fragments (cannot add fragments).

**Comment by brianchiu** [comment]
@carloslancha 
I reverted your commit for now because a lot of tests are failing. Here are gifs of the 3 issues that I saw.

**Comment by carloslancha** [comment]
@brianchiu @jpince I'm on it, just changed params.

**Comment by carloslancha** [comment]
@brianchiu @jpince https://github.com/brianchandotcom/liferay-portal/pull/66705

**Comment by brianchiu** [comment]
@carloslancha Thanks!

**Pull request closed without merging**
