### PR TITLE
OAUTH2-144 All DBs support CLOB, they just name it differently. That'…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…s one of the reasons why we use Hibnerate, to avoid handling those tiny DBMS difference. Do entity mapping rather than scalar mapping, so that we don't have to explicitly deal with the type.

CC @topolik @jpince

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by jpince** [comment]
cc/ @csierra

-- 
Jason Pince
Lead Test Engineer


Liferay Inc. | 1400 Montefino Avenue, Diamond Bar, CA 91765 USA |
877-543-3729 <(877)%20543-3729>
_____________________________________________________________________

*Confidentiality Notice:* This e-mail message, including any attachments,
is for the sole use of the intended recipient(s) and may contain
confidential and privileged information. Any unauthorized review, use,
copying, disclosure or distribution is prohibited. If you are not the
intended recipient, please contact the sender by reply e-mail and destroy
all copies of the original message.

**Comment by brianchandotcom** [comment]
@topolik @csierra fyi

**Comment by topolik** [comment]
Thanks @shuyangzhou !

**Pull request closed without merging**
