### PR TITLE
LPS-81467 Using the constant instead

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test

**Comment by achaparro** [comment]
@jpince can we reopen this pull?

Thanks

**Comment by jpince** [comment]
ci:test relevant

this is the part of the integration-mysql log I'm concerned about, as I don't see this error in upstream:
```

     [exec] com.liferay.portal.osgi.debug.spring.extender.test.SpringExtenderDependencyManagerTest > testSpringExtenderDependencyManagerUnresolvedDependencies STARTED
     [exec] 13:55:16,363 INFO  [RMI TCP Connection(6)-127.0.0.1][BundleStartStopLogger:35] STARTED com.liferay.portal.osgi.debug.spring.extender.test.bundle_1.0.0 [910]
     [exec] 13:55:17,455 INFO  [RMI TCP Connection(6)-127.0.0.1][BundleStartStopLogger:38] STOPPED com.liferay.portal.osgi.debug.spring.extender.test.bundle_1.0.0 [910]
     [exec] 
     [exec] com.liferay.portal.osgi.debug.spring.extender.test.SpringExtenderDependencyManagerTest > testSpringExtenderDependencyManagerUnresolvedDependencies PASSED
     [exec] 13:55:17,524 INFO  [RMI TCP Connection(6)-127.0.0.1][BundleStartStopLogger:38] STOPPED com.liferay.portal.osgi.debug.spring.extender.test_1.0.0 [909]
     [exec] :apps:portal-osgi-debug:portal-osgi-debug-spring-extender-test:stopTestableTomcat
     [exec] Jun 15, 2018 1:55:17 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
     [exec] WARNING: Problem with directory [/opt/dev/projects/github/liferay-portal/bundles/tomcat-9.0.6/lib/ext/global], exists: [false], isDirectory: [false], canRead: [false]
     [exec] Jun 15, 2018 1:55:17 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
     [exec] WARNING: Problem with directory [/opt/dev/projects/github/liferay-portal/bundles/tomcat-9.0.6/lib/ext/global], exists: [false], isDirectory: [false], canRead: [false]
     [exec] 15-Jun-2018 13:55:17.942 INFO [main] org.apache.catalina.core.StandardServer.await A valid shutdown command was received via the shutdown port. Stopping the Server instance.
     [exec] 15-Jun-2018 13:55:17.956 INFO [main] org.apache.coyote.AbstractProtocol.pause Pausing ProtocolHandler ["http-nio-8080"]
     [exec] 15-Jun-2018 13:55:17.958 INFO [main] org.apache.coyote.AbstractProtocol.pause Pausing ProtocolHandler ["ajp-nio-8009"]
     [exec] 15-Jun-2018 13:55:17.958 INFO [main] org.apache.catalina.core.StandardService.stopInternal Stopping service [Catalina]
     [exec] 15-Jun-2018 13:55:17.960 SEVERE [http-nio-8080-exec-4] org.apache.catalina.core.ApplicationContext.log Error during mapping
     [exec]  java.lang.NullPointerException
     [exec] 	at org.apache.catalina.mapper.Mapper.internalMapWrapper(Mapper.java:867)
     [exec] 	at org.apache.catalina.mapper.Mapper.map(Mapper.java:723)
     [exec] 	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:483)
     [exec] 	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:222)
     [exec] 	at com.liferay.friendly.url.internal.servlet.FriendlyURLServlet.service(FriendlyURLServlet.java:352)
     [exec] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
     [exec] 	at com.liferay.portal.servlet.ServletAdapter.service(ServletAdapter.java:98)
     [exec] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:
```

Will watch the test results to see if it reoccurs.

**Comment by jpince** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:reopen test failures consistent with those in upstream

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
