### PR TITLE
LPS-85972 Fix bug

### PR DESCRIPTION
**Pull request by cgoncas**
@ruben-pulido

### CODE REVIEW

**Comment by cgoncas** [comment]
@jpince Could it be possible to throw headless-apio tests with portal-odata changes?.

**Comment by jpince** [comment]
@cgoncas do you mean can headless-apio tests run when changes are made to portal-odata? If so, the answer is yes. You would just need to add a test.properties file with that module name. See example in [apio-architect/test.properties](https://github.com/liferay/liferay-portal/blob/master/modules/apps/apio-architect/test.properties#L12-L13)

**Comment by cgoncas** [comment]
@jpinceCan you review https://github.com/jpince/liferay-portal/pull/96, and let me know if it is ok?

**Comment by jpince** [comment]
@cgoncas yes, I will review

Also, will this pull resolve odata test failures? error looks similar
```
OrganizationODataRetrieverCustomFieldsTest.testGetOrganizationsFilterByCustomFieldWithEqualsAndBooleanKeywordType
java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.liferay.segments.odata.retriever.test.OrganizationODataRetrieverCustomFieldsTest.testGetOrganizationsFilterByCustomFieldWithEqualsAndBooleanKeywordType(OrganizationODataRetrieverCustomFieldsTest.java:136)
	a
```
I saw the odata failure in [this pull](https://github.com/brianchandotcom/liferay-portal/pull/65433#issuecomment-442727805).

**Comment by cgoncas** [comment]
@jpince , yeah!, we think this pull will fix that issue too.

**Comment by jpince** [comment]
sounds good, thanks!

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
