### PR TITLE
LPS-74544

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
/cc @petershin

7.0.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/19100

**Comment by hhuijser** [comment]
ci:test

**Comment by petershin** [comment]
@hhuijser - Sent pulls to update the subrepos:

https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/638
https://github.com/liferay/com-liferay-journal/pull/576
https://github.com/michaelhashimoto/com-liferay-poshi-runner/pull/5

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
