### PR TITLE
LPS-82128

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@brianchandotcom, let the tests finish first!!

@jrao, reverting your fix, it's breaking portal-spring.xml

@Preston-Crary added logic to detect unneeded references. Decided to warn instead of autofix, because running SB is still required after removing the reference

**Comment by hhuijser** [comment]
ci:test

**Comment by hhuijser** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/22aa37e437...e257c4d78a

**Pull request closed without merging**
