### PR TITLE
LPS-184932

### PR DESCRIPTION
**Pull request by Tim-Cao**
This is only for master.

https://issues.liferay.com/browse/LPS-184932

@lfbesada

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/12291

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/70e428d754...77f3bcde63

**Comment by brianchandotcom** [comment]
@lfbesada @sandrodw3 see 77f3bcde63448322ea75551ad52ef063cee8ee84

**Pull request closed without merging**
