### PR TITLE
LPS-189621

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:reopen

**Comment by marianoalvarosaiz** [comment]
Property weird cache removed, it is already done in DBManagerImpl

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6399ca0b7a...8cf5e56a6e

**Comment by brianchandotcom** [comment]
@marianoalvarosaiz see 8cf5e56a6e7874313c3ccfb47f432e144df55901

**Pull request closed without merging**
