### PR TITLE
LPS-54417 Support for creating OSGI modules that add friendly urls to a portlet

### PR DESCRIPTION
**Pull request by juliocamarero**
already reviewed by @migue

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@shuyangzhou I think that's a CI race condition bug. Just fyi.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6f800e6dfd...e58cf6481b

**Comment by shuyangzhou** [comment]
@brianchandotcom yeah, that looks like a search race condition, will dig into it.

**Comment by shuyangzhou** [comment]
See test fix at https://github.com/brianchandotcom/liferay-portal/pull/25058

**Pull request closed without merging**
