### PR TITLE
LPS-91984 JS functions got namespace

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fcadbca727...cdd76736e7

**Comment by brianchandotcom** [comment]
@zoltancsaszi @danielkocsis see my changes in 1a6a840406a3f57fae172a33eff6fefabbe02ebf and 84bbee80953a2fef51d9f2e515b0e7a35efaa53b

**Pull request closed without merging**
