### PR TITLE
LPS-91286 Auto

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by jpince** [comment]
ci:close @ealonso @pavel-savinov please look into upgrade test failures
```
     [java] 2019-02-28 09:03:27.838 ERROR [main][JDBCExceptionReporter:234] Unknown column 'this_.classNameId' in 'field list'
     [java] ERROR - Unknown column 'this_.classNameId' in 'field list'
     [java] 2019-02-28 09:03:27.840 ERROR [main][BasePersistenceImpl:437] Caught unexpected exception
     [java] org.hibernate.exception.SQLGrammarException: could not execute query
     [java] 	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:92)
     [java] 	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:66)
     [java] 	at org.hibernate.loader.Loader.doList(Loader.java:2545)
```
```
     [java] 2019-02-28 09:03:59.368 ERROR [main][JDBCExceptionReporter:234] Unknown column 'layoutimpl0_.classNameId' in 'field list'
     [java] ERROR - Unknown column 'layoutimpl0_.classNameId' in 'field list'
```
cc/ @kyle-miho @brianchiu

**Comment by brianchiu** [comment]
ci:test:bundle

**Comment by kyle-miho** [comment]
@jpince where are you seeing these failures? I don't see any. I just see "passed"

**Comment by jpince** [comment]
@kyle-miho https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=486100856&testrayComponentId=438902455&statuses=3

**Pull request closed without merging**
