### PR TITLE
LPS-105422 Add test case

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

@georgel-pop-lr 

Georgel's comment: Add test cases based on Brian request https://github.com/brianchandotcom/liferay-portal/pull/120574#issuecomment-1192140271

### CODE REVIEW

**Comment by ozysouza** [comment]
ci:reopen

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See [liferay-echo#7560](https://github.com/liferay-echo/liferay-portal/pull/9461)

:heavy_check_mark: ci:test:stable - 26 out of 26 jobs passed
:x: ci:test:relevant - 195 out of 201 jobs passed in 1 hour 28 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/250ce95800...b5a7767f66

**Comment by brianchandotcom** [comment]
@georgel-pop-lr @ozysouza see 2c7c71ef37fe67b0e54c77f013f5f4700b604d97

The methods were so long I couldn't understand what they meant anyways.

**Pull request closed without merging**
