### PR TITLE
LPS-183224

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@rafaprax @tinatian a provider needs to provide something

```
import com.liferay.portal.kernel.theme.ThemeDisplay;

import javax.portlet.PortletPreferences;

/**
 * @author Rafael Praxedes
 */
public interface UpdatePortletPreferencesProvider {

	public void updatePortletPreferences(
			String className, long classPK, String portletId,
			PortletPreferences portletPreferences, ThemeDisplay themeDisplay)
		throws Exception;
```

This is not providing anything. It doesn't even return an object. Suppose it returns a "User", then it'd be a UserProvider.

Please resend.

**Comment by rafaprax** [comment]
Hey @brianchandotcom,

In this case, I chose this name because it is "providing" a way to update the portletPreferences (even if it does not return anything) but I understood your point of view and will resend it soon.

Thanks

//cc @tinatian

**Comment by rafaprax** [comment]
resent here https://github.com/brianchandotcom/liferay-portal/pull/136734

**Pull request closed without merging**
