### PR TITLE
LPS-74258 Deactivating a site removes the users from the search for other sites as well

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-74258](https://issues.liferay.com/browse/LPS-74258).<br><br>/cc @ling-alan-huang, @hhuijser, @mhan810

### CODE REVIEW

**Comment by drewbrokke** [comment]
cc @pei-jung

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:retest

**Comment by drewbrokke** [comment]
Hey @brianchandotcom, is there anything we need to change about this pull?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1423b8d274...684fabe304

**Comment by brianchandotcom** [comment]
@drewbrokke please see my changes in upstream. Thx.

**Pull request closed without merging**
