### PR TITLE
Lps 70297

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5448a6e95e...4b04b8bc15

**Comment by brianchandotcom** [comment]
@shuyangzhou please backport? Thx.

**Comment by shuyangzhou** [comment]
@tomwang2011 backport please

**Pull request closed without merging**
