### PR TITLE
LPS-85797 SF

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by jpince** [comment]
ci:close @sergiogonzalez @adolfopa can you make sure these failures aren't related? I don't see them in upstream.

cc/ @austinchiang @patriciajeanperez

**Comment by jpince** [comment]
ci:reopen nevermind, I see this in [this upstream acceptance run](https://test-1-9.liferay.com/job/test-portal-acceptance-upstream-batch(master)/26872/) and another pull you sent https://github.com/brianchandotcom/liferay-portal/pull/63570. Will research the issue and email you about it.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a72c50394b...6d65335b2a

**Comment by brianchandotcom** [comment]
@adolfopa @sergiogonzalez are you guys sure this is right? It's weird to remove ticket and doAsUserId, as someone must have added it for a good reason in the past?

**Comment by brianchandotcom** [comment]
@adolfopa @sergiogonzalez I merged this to master only. If it should go back, please send support a pull for 7.1.x Thx.

**Comment by sergiogonzalez** [comment]
Hey @brianchandotcom that's not necessary anymore. Adolfo explained it in the commit message: 

This is not required anymore, as all supported browsers implement the
required APIs. This is only needed when falling back to flash (which
shouldn't happen anymore).

Thanks

**Pull request closed without merging**
