### PR TITLE
LPS-65885 ant build-lang

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by vicnate5** [comment]
@adolfopa The change in the name from "Comments" to "Comment" has caused the workflow poshi test to fail.

Would it be OK if I resent this pull for you with the poshi test fix needed?

The other poshi tests failures are not related to this pull.

**Comment by adolfopa** [comment]
Sure @vicnate5 go ahead.

Thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/77bc252329...e4a6af0c16

**Comment by vicnate5** [comment]
@adolfopa Fix sent https://github.com/brianchandotcom/liferay-portal/pull/40858

**Pull request closed without merging**
