### PR TITLE
LPS-89662 Add default segment 

### PR DESCRIPTION
**Pull request by darquesdev**

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@darquesdev @epgarcia can you resend this:

```
	public static final String DEFAULT_SEGMENTS_ENTRY_KEY = "default-segment";

	public static final String RESOURCE_NAME = "com.liferay.segments";

	public static final String SOURCE_ASAH_FARO_BACKEND = "ASAH_FARO_BACKEND";

	public static final String SOURCE_DEFAULT = "DEFAULT";
```

Previously, things were grouped XYZ_*

Now, you're adding a key that is *_XYZ

It's a bit confusing. Please rename and resend. Thx.

**Comment by brianchandotcom** [comment]
@darquesdev @epgarcia just in case you don't see it, contrast SOURCE_DEFAULT with DEFAULT_SEGMENTS_ENTRY_KEY

**Comment by darquesdev** [comment]
I got it ;) Thanks, I'm going to resend the PR

**Pull request closed without merging**
