### PR TITLE
LPS-97498 Ignore generated *.soy.js files

### PR DESCRIPTION
**Pull request by wincent**
Follow-up to:

https://github.com/brianchandotcom/liferay-portal/pull/75011

I don't believe the globs we're using will cause us to format any generated `*.soy.js` files. But in the name of robustness, this commit explicitly prevents Prettier and ESLint from *ever* considering such files, just in case future changes ever wind up putting some in places identified by globs.

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:test:relevant

**Comment by wincent** [comment]
Thanks @jpince: I hadn't noticed that the tests never started.

**Comment by brianchandotcom** [comment]
@wincent see 2547b2b

Can you follow up and make them full and complete sentences? See portal.properties. Thx.

**Comment by wincent** [comment]
Thanks @brianchandotcom. Follow-up is at https://github.com/brianchandotcom/liferay-portal/pull/75079

**Pull request closed without merging**
