### PR TITLE
LPS-97401 Update to liferay-npm-scripts v4.0.0

### PR DESCRIPTION
**Pull request by wincent**
Major version bump because this one does linting and formatting (previously it only did linting), so is technically a "breaking change" in the sense that a run of `yarn checkFormat` that previously passed could fail now. (Having said that, it doesn't actually fail because we previously dealt with pre-existing lints in LPS-97079).

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
@hhuijser, @petershin: Once this one goes in — or technically, even before it, seeing as there's no reason not to turn on the formatting checks even now — can you please help us with this ticket? https://issues.liferay.com/browse/LPS-97402

Basically, we want to run `yarn checkFormat` from the top-level "modules/" folder as part of CI runs. As @jbalsas [noted here](https://github.com/brianchandotcom/liferay-portal/pull/74563#issuecomment-503125802), the log shows us that it's currently not running:

```
format-source-all:
     [echo] 
     [echo] This target does not format .es.js files. Please run the following command from /opt/dev/projects/github/liferay-portal/modules to do so:
     [echo] 
     [echo] ../gradlew npmRunCheckFormat
     [echo] 				
[stopwatch] [run.batch.test.action: 3:18.158 sec]
```

My understanding is that it used to be too slow, but we think with the recent changes we've made — that allow us to run it globally, for instance — the "juice is now worth the squeeze", as the full formatting and linting run takes about 50 seconds on a developer laptop (possible faster in a beefy CI machine), and will catch a lot of issues for us.

I'll copy you all on an email about this anyway, but I wanted to include a comment here too for visibility.

**Comment by brianchandotcom** [comment]
Merged, @hhuijser please help @wincent . Thx.

**Comment by hhuijser** [comment]
@wincent 

Sorry for not getting back to you earlier.

I believe the main reason we turned js formatting off (except when running `ant format-source-all`) was speed of doing a run on all portal (from China, it was taking more than an hour at times).

Since running SF on all portal takes more than 6 minutes these days, we only execute SF on files that are changed in the branch you're working on by default (`ant format-source-current-branch`). This usually runs in way under 1 minute.

In the same way, CI only runs SF on current branch (unless it finds files that were changed in `modules/util/source-formatter`)

I am okay turning js formatting on by default for everyone, but like to do some testing on my end first to see how it affects performance.

**Comment by wincent** [comment]
> @wincent backported to 7.2.x for you.

Thanks @brianchandotcom.

> I am okay turning js formatting on by default for everyone, but like to do some testing on my end first to see how it affects performance.

Great. Thanks @hhuijser.

**Pull request closed without merging**
