### PR TITLE
LPS-102110 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LPS-102110

### CODE REVIEW

**Comment by john-co** [comment]
cc/ @jbalsas

**Comment by john-co** [comment]
Hi @eduardoallegrini, @marcoscv, there's a merge conflict with head. Could you please take a look?

cc/ @jbalsas

**Comment by brianchandotcom** [comment]
@jbalsas @eduardoallegrini, @marcoscv, please resend. Rebase error.

**Comment by jbalsas** [comment]
rebased and resent to https://github.com/brianchandotcom/liferay-portal/pull/79334

**Pull request closed without merging**
