### PR TITLE
LPS-63475 Extract Contacts Service to OSGi Module

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-63475](https://issues.liferay.com/browse/LPS-63475).<br><br>/cc @jorgeferrer @alee8888

### CODE REVIEW

**Comment by sharonchoi** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@drewbrokke I merged this in, but ContactsConstants.java, SocialRelationConstants.java and WebKeys.java are in the wrong place or named wrong. We have a new pattern once we modularize them. Please follow that new pattern. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e486dfaba3...f9075375e4

**Comment by brianchandotcom** [comment]
@drewbrokke also, compare the old modules/apps/platform/contacts/contacts-service/src/main/resources/META-INF/portlet-model-hints.xml

I think comments might have been different. You may need to update it and regenerate. Thx.

**Comment by brianchandotcom** [comment]
@drewbrokke 

```
		<field name="fullName" type="String">
			<validator name="required" />
		</field>
		<field name="emailAddress" type="String">
			<validator name="email" />
			<validator name="required" />
		</field>
		<field name="comments" type="String">
			<hint-collection name="TEXTAREA" />
		</field>

``` this all got lost. see that file in plugins.

**Pull request closed without merging**
