### PR TITLE
LPS-191037 Add vocabularyIds again

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://liferay.atlassian.net/browse/LPS-191037

@victorg1991

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/12992

**Comment by Tim-Cao** [comment]
Hi @victorg1991, would you mind resolve the conflict? Thanks

**Comment by brianchandotcom** [comment]
@Tim-Cao @victorg1991 rebase error, please resend.

**Pull request closed without merging**
