### PR TITLE
LPS-136032 portal-language

### PR DESCRIPTION
**Pull request by Preston-Crary**
@shuyangzhou, this solves the conflicting default resource bundles by forcing the migrating bundle to say it still needs it's own ResourceBundle in 8d1897e. In some ways this is cleaner because we only apply the backwards compatibility where we need it. I'm not sure if we want to continue with this fix or work out the details of why different default ResourceBundles were conflicting.

@brianchandotcom once we replace all the ResourceBundleUtil usages in change-tracking-web with LanguageUtil then we won't need 8d1897e anymore.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7868fe44a6...0314afc49b

**Comment by brianchandotcom** [comment]
@petershin fyi on needing https://github.com/brianchandotcom/liferay-portal/commit/8d1897e20dafedc2178693e3be161eacc234e652 for now but not later.

**Comment by brianchandotcom** [comment]
thx @Preston-Crary !

**Pull request closed without merging**
