### PR TITLE
LeslieWong92-Master-QA-19127

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-19127

### CODE REVIEW

**Comment by pyoo47** [comment]
discovered an error in one of my revisions.. I will resend.

**Comment by pyoo47** [comment]
Nevermind my earlier comment. My revision is OK. No changes needed. Reopening this pull.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5eac79e4c4...6482c66813

**Comment by brianchandotcom** [comment]
@kenjiheigel @pyoo47 published a new one

**Pull request closed without merging**
