### PR TITLE
Lps 80517 4

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@hhuijser @petershin please see @Preston-Crary 's email about the suppress

**Comment by shuyangzhou** [comment]
Thanks @petershin !

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@petershin this breaks

gradlew :apps:portal-settings:portal-settings-authentication-ldap-web:jar

For some reason, it creates this:

```
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.GradleException: Build has errors
     [exec] 	at org.dm.gradle.plugins.bundle.JarBuilder.build(JarBuilder.groovy:138)
     [exec] 	at org.dm.gradle.plugins.bundle.JarBuilder.writeManifestTo(JarBuilder.groovy:87)
     [exec] 	at com.liferay.gradle.plugins.LiferayOSGiPlugin$LiferayJarBuilder.writeManifestTo(LiferayOSGiPlugin.java:1209)
     [exec] 	at org.dm.gradle.plugins.bundle.ManifestSubstitute.writeTo(ManifestSubstitute.groovy:40)
     [exec] 	at org.gradle.jvm.tasks.Jar$1$1.execute(Jar.java:80)
     [exec] 	at org.gradle.jvm.tasks.Jar$1$1.execute(Jar.java:67)
     [exec] 	at org.gradle.api.internal.file.collections.MapFileTree$FileVisitDetailsImpl.copyTo(MapFileTree.java:182)
     [exec] 	at org.gradle.api.internal.file.collections.MapFileTree$FileVisitDetailsImpl.generateContent(MapFileTree.java:200)
     [exec] 	at org.gradle.api.internal.file.collections.MapFileTree$FileVisitDetailsImpl.updateFileOnlyWhenGeneratedContentChanges(MapFileTree.java:188)
     [exec] 	at org.gradle.api.internal.file.collections.MapFileTree$FileVisitDetailsImpl.getFile(MapFileTree.java:172)
     [exec] 	at org.gradle.api.internal.changedetection.state.AbstractFileCollectionSnapshotter$FileVisitorImpl.visitFile(AbstractFileCollectionSnapshotter.java:190)
     [exec] 	at org.gradle.api.internal.file.collections.MapFileTree$Visit.visit(MapFileTree.java:133)
     [exec] 	at org.gradle.api.internal.file.collections.MapFileTree.visit(MapFileTree.java:86)
     [exec] 	at org.gradle.api.internal.file.collections.MapFileTree.visitTreeOrBackingFile(MapFileTree.java:250)
     [exec] 	at org.gradle.api.internal.file.collections.FileTreeAdapter.visitTreeOrBackingFile(FileTreeAdapter.java:125)
     [exec] 	at org.gradle.api.internal.file.AbstractFileTree$FilteredFileTreeImpl.visitTreeOrBackingFile(AbstractFileTree.java:190)
     [exec] 	at org.gradle.api.internal.changedetection.state.AbstractFileCollectionSnapshotter.visitTreeOrBackingFile(AbstractFileCollectionSnapshotter.java:169)
     [exec] 	at org.gradle.api.internal.changedetection.state.AbstractFileCollectionSnapshotter$FileCollectionVisitorImpl.visitTree(AbstractFileCollectionSnapshotter.java:155)
     [exec] 	at org.gradle.api.internal.file.AbstractFileTree.visitRootElements(AbstractFileTree.java:143)
     [exec] 	at org.gradle.api.internal.file.CompositeFileCollection.visitRootElements(CompositeFileCollection.java:185)
     [exec] 	at org.gradle.api.internal.changedetection.state.AbstractFileCollectionSnapshotter.snapshot(AbstractFileCollectionSnapshotter.java:78)
     [exec] 	at org.gradle.api.internal.changedetection.rules.AbstractNamedFileSnapshotTaskStateChanges.buildSnapshots(AbstractNamedFileSnapshotTaskStateChanges.java:87)
     [exec] 	at org.gradle.api.internal.changedetection.rules.AbstractNamedFileSnapshotTaskStateChanges.<init>(AbstractNamedFileSnapshotTaskStateChanges.java:54)
     [exec] 	at org.gradle.api.internal.changedetection.rules.InputFilesTaskStateChanges.<init>(InputFilesTaskStateChanges.java:28)
     [exec] 	at org.gradle.api.internal.changedetection.rules.TaskUpToDateState.<init>(TaskUpToDateState.java:55)
     [exec] 	at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.getStates(DefaultTaskArtifactStateRepository.java:164)
     [exec] 	at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.isUpToDate(DefaultTaskArtifactStateRepository.java:79)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:51)
     [exec] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
     [exec] 	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
     [exec] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
     [exec] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
     [exec] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
     [exec] 	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
     [exec] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
     [exec] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
     [exec] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
     [exec] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
     [exec] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
     [exec] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
     [exec] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
     [exec] 	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
     [exec] 
```

I had to roll it back.

**Comment by petershin** [comment]
@Preston-Crary - This is from bnd and it's complaining that a dynamic reference is missing an unbind method

Should the reference policy be changed from dynamic to `ReferencePolicy.STATIC` ?

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/58862
@Ithildir do you know is it the standard bnd doing it? or it is one of our own plugins doing it?

**Comment by Ithildir** [comment]
Hi @shuyangzhou, I'm pretty sure it's just Bnd standard behavior!

**Pull request closed without merging**
