### PR TITLE
LPS-95667 Build lang

### PR DESCRIPTION
**Pull request by epgarcia**
@darquesdev @dgarciasarai

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/60c702527a...ff150a42e1

**Comment by jpince** [comment]
@vicnate5 looks like this may have introduced upgrade failures?
```
## 7 Liferay Exceptions were thrown
##

LIFERAY_ERROR: FrameworkEvent WARNING 
LIFERAY_ERROR: FrameworkEvent WARNING 
LIFERAY_ERROR: bundle com.liferay.segments.asah.connector:2.0.0 (855)[com.liferay.segments.asah.connector.internal.messaging.IndividualSegmentsMessageListener(4681)] : Could not get service from ref {com.liferay.segments.asah.connector.internal.messaging.IndividualSegmentsCheckerUtil}={service.id=6908, service.bundleid=855, service.scope=bundle, component.name=com.liferay.segments.asah.connector.internal.messaging.IndividualSegmentsCheckerUtil, component.id=4680} 
LIFERAY_ERROR: FrameworkEvent WARNING 
LIFERAY_ERROR: FrameworkEvent WARNING 
LIFERAY_ERROR: bundle com.liferay.segments.asah.connector:2.0.0 (855)[com.liferay.segments.asah.connector.internal.messaging.IndividualSegmentsMessageListener(4681)] : Could not get service from ref {com.liferay.segments.asah.connector.internal.messaging.IndividualSegmentsCheckerUtil}={service.id=6908, service.bundleid=855, service.scope=bundle, component.name=com.liferay.segments.asah.connector.internal.messaging.IndividualSegmentsCheckerUtil, component.id=4680} 
LIFERAY_ERROR: FrameworkEvent WARNING 
```

**Comment by epgarcia** [comment]
@jpince I'll take a look to it

**Comment by vicnate5** [comment]
Confirmed this is the cause.

**Comment by epgarcia** [comment]
I think I found the problem. I tested it locally, but I'm now testing it on a PR before sending it to Brian. See epgarcia/liferay-portal/pull/798

**Comment by vicnate5** [comment]
Thanks @epgarcia

**Comment by epgarcia** [comment]
@jpince @vicnate5 See #74264. Thanks

**Pull request closed without merging**
