### PR TITLE
LPS-56565

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@epgarcia fyi, we do not want to be publishing both TC and ehcache.

**Comment by epgarcia** [comment]
Thanks @mhan810, I was just checking why we were getting an error with terracota cache in journal-service during startup. I'm sorry, this is the only module (so far) with specific cache config and I didn't know we didn't want/we couldn't configure both eh and terracota.

**Comment by mhan810** [comment]
yep no worries, it's not like we document stuff ;)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/50a2d3cd34...4f58a39ea3

**Pull request closed without merging**
