### PR TITLE
LPS-63951 Auto

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:retest

**Comment by sharonchoi** [comment]
@evannagayama

Looking at the screenshots, it looks like it might be a bug with web content display, when selecting a Web Content.

**Comment by evannagayama** [comment]
@sharonchoi, thanks!

@ealonso it looks like there is probably a bug when selecting a web content in wcd. The test shows the window throws an error: "$processor.processMax()"

**Comment by ealonso** [comment]
Thanks @evannagayama, @sharonchoi for the feedback, I'm going to check it.

**Pull request closed without merging**
