### PR TITLE
LPS-75259 AssetPublisher exports portlet data in site template propagation

### PR DESCRIPTION
**Pull request by jkappler**
cc:// @JavierMoral, @ealonso

### CODE REVIEW

**Comment by jkappler** [comment]
Hi @austinchiang, are these real errors? We get them also when trying to merge journal into master.

Please let us know. Thanks!

**Comment by austinchiang** [comment]
Hi @jkappler, these do not appear to be related failures. I will quarantine those tests in LRQA-35555.

**Comment by jkappler** [comment]
Thanks @austinchiang!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f3a50971dc...d71909ace8

**Pull request closed without merging**
