### PR TITLE
LPS-138007 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-138007

This is only for master.

@ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure cases are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/5733
❌ ci:test:stable - 10 out of 11 jobs passed
❌ ci:test:relevant - 23 out of 27 jobs passed in 1 hour 43 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5fbcbfaecc...0f2cbf29b0

**Comment by brianchandotcom** [comment]
@ealonso sorted 0f2cbf29b03c632ba3ddf0ba6f3be127f877ea61

**Pull request closed without merging**
