### PR TITLE
LPS-59939 Remove calls to *ServiceUtil

### PR DESCRIPTION
**Pull request by jkappler**
Thanks @hhuijser!!!!

### CODE REVIEW

**Comment by jkappler** [comment]
CC: @juliocamarero

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@hhuijser when is it

```
@Reference(unbind = "-")
```

and when is it

```
@Reference
```

Can you SF enforce it? :) Thx bro.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d2a4534a0f...245d8a637e

**Comment by hhuijser** [comment]
@brianchandotcom 

We should be using @Reference(unbind = "-") if we don't have a unset/unbind associated with the set/bind method (which is for most of our cases).
When not specifying unbind, it expects there is a unset/unbind derived from the set/bind method name.

See https://osgi.org/javadoc/r5/enterprise/org/osgi/service/component/annotations/Reference.html#unbind%28%29

I can add that to SF

**Pull request closed without merging**
