### PR TITLE
LPS-70184

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@mhan810 this one is good..

@shuyangzhou I'm seeing BundleSupportCommandsTest.testInitBundleTarProxy randomly fail a lot.

Merging.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1e48bb3a4b...4b3f2cb42a

**Comment by shuyangzhou** [comment]
@Ithildir please come to me to talk about the BundleSupportCommandsTest failures.
We need to find a way to get rid off the network usages. But I need to understand the requirements of the test first.

**Pull request closed without merging**
