### PR TITLE
Lps 74083

### PR DESCRIPTION
**Pull request by shuyangzhou**
This is for the DefaultExportImportContentProcessorTest failure which was caused by https://github.com/brianchandotcom/liferay-portal/pull/52106

@matethurzo please fix the test and readd back your changes.

CC @preston-crary

### CODE REVIEW

**Comment by shuyangzhou** [comment]
Pushed upstream to fix CI

**Comment by shuyangzhou** [comment]
@mtambara please look into the adaptive media random failures. I am out of office in the morning, I will come back to check with you on this in the afternoon.

**Comment by shuyangzhou** [comment]
@mtambara I fixed https://github.com/brianchandotcom/liferay-portal/pull/52166
You just need to look into DLAppServiceTest$WhenAddingAFileEntry.shouldSucceedWithConcurrentAccess, it looks like a hsql thing.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
