### PR TITLE
LPS-97123 Auto SF

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @brianchandotcom,

We initially decided to put the `extractor` API under `info` but after discussing it now we agree with you and we think that it is best to place it under auto tagging.

Thanks!

**Comment by nhpatt** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Will fix the tests and resend.

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/74850.

**Pull request closed without merging**
