### PR TITLE
LPS-105380 BNDImportsCheck

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Tested [here](https://github.com/ling-alan-huang/liferay-portal/pull/451), unrelated failures.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:reopen

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/dd6524ae9d...7b2737c1fa

**Pull request closed without merging**
