### PR TITLE
LPS 189386

### PR DESCRIPTION
**Pull request by rotty3000**
- LPS-189386 fix field name
- LPS-189386 fix update
- LPS-189386 fix the scope
- LPS-189386 fix java logic
- LPS-189386 MUST NOT BLOCK
- LPS-189386 custom element
- LPS-189386 theme css

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:reopen

**Comment by rotty3000** [comment]
cc @gamerson @ipeychev

**Comment by yunlinsun** [comment]
hey @rotty3000 ,
Rebase error, please fix and resend, thanks.

cc @brianchandotcom

**Comment by yunlinsun** [comment]
ci:close

**Pull request closed without merging**
