### PR TITLE
LPS-68893

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@marcellustavares @mhan810 can you guys resend? Schema version and bnd bundle version are not tied together. They shouldn't be artificially pegged together. Thx.

**Comment by mhan810** [comment]
ci:reopen

**Comment by mhan810** [comment]
@brianchandotcom we need to do this because:
(1) prior to setting the required-schema-version, the bundle version would be used.  This could cause issues for customers that have installed other fix packs.  So we have no predictable way of knowing which number to use.
(2) we are setting the schema version to the latest unpublished bundle version to basically have a baseline.

Once we get this in, future schema and bundle versions can diverge.

**Comment by brianchandotcom** [comment]
@mhan810 @marcellustavares talked to Mike. Merging in as is.

**Comment by brianchandotcom** [comment]
Merged. Please backport.

**Pull request closed without merging**
