### PR TITLE
LPS-65819 Ordered as much as possible

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Hey @brianchandotcom , 
this is a resend of https://github.com/brianchandotcom/liferay-portal/pull/39774.
I've ordered as much as possible this ckeditor plugins configuration. Any other change causes several bugs when editing with AlloyEditor. As this is developed in top of CKEditor, there is no other solution for ordering it following our rules. 
Thanks!

### CODE REVIEW

**Comment by pyoo47** [comment]
The above test aborted while running SourceFormatter. ci:retest

```
     [exec] com.liferay.source.formatter.SourceFormatterTest > testSourceFormatter STARTED
     [exec] 
     [exec] com.liferay.source.formatter.SourceFormatterTest > testSourceFormatter STANDARD_OUT
     [exec]     Loading jar:file:/root/.m2/repository/com/liferay/portal/com.liferay.portal.impl/2.4.0-SNAPSHOT/com.liferay.portal.impl-2.4.0-SNAPSHOT.jar!/system.properties
     [exec]     Loading jar:file:/opt/dev/projects/github/liferay-portal/bundles/tomcat-8.0.32/webapps/ROOT/WEB-INF/lib/portal-impl.jar!/system.properties
Build timed out (after 120 minutes). Marking the build as aborted.
Build was aborted
```

**Comment by brianchandotcom** [comment]
@hhuijser SF can actually hang the build... see comments from @pyoo47 

Thx.

**Comment by brianchandotcom** [comment]
@ambrinchaudhary the code is not obvious.

Break up all the parts that have to go in a certain order in its own method?

sb.append("xxx")
sb.append(getXyz())
sb.append("yyy")
sb.append(getAbc())

Does "width" have to go before "height"? Also, please do it without reverting the previous commit.

Instead, move each part out to its own method and comment in the commit log why it has to be so.

Thx @ambrinchaudhary

**Comment by pyoo47** [comment]
@hhuijser Hugo, please note that I can't actually tell whether or not SF hung the build. That is what was running when the build timed out. It's possible that the build was just running very slowly and that's what was running when time ran out. This scenario, however, is extremely rare. It's usually the last thing that was running that hung and eventually timed out.

**Pull request closed without merging**
