### PR TITLE
LPS-121999 Update service.xml and add Upgrade processes

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-121999](https://issues.liferay.com/browse/LPS-121999).<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@drewbrokke I feel so bad about this....... my bad

```
		<column name="active" type="boolean" />
		<column name="countryId" type="long" />
		<column name="name" type="String" />
		<column name="position" type="double" />
		<column name="regionCode" type="String" />
		<column name="lastPublishDate" type="Date" />
```

Remember, we settled on PKs, and then columns, and then lastPublishDate

Should be

```
		<column name="countryId" type="long" />
		<column name="active" type="boolean" />
		<column name="name" type="String" />
		<column name="position" type="double" />
		<column name="regionCode" type="String" />
		<column name="lastPublishDate" type="Date" />
``

So it should go back to C_A and not A_C

Sorry! Please resend direct if you want to

**Comment by drewbrokke** [comment]
No problem. Ok so the ordering of fields is:

1. PK
2. Audit fields
3. Foreign PKs
4. Other fields, sorted alpha
5. lastPublishDate, status* fields

Correct?

**Comment by drewbrokke** [comment]
See https://github.com/drewbrokke/liferay-portal/pull/1224

**Pull request closed without merging**
