### PR TITLE
Lps 55038

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @mhan810

@dantewang @slnn this is a temporarily mapping table cache removal by default. (I will re-enable it when starting the tuning process for 7 release), but it will hurt your tests. To avoid the test results decline, add table.mapper.cache.mapping.table.names= in portal-ext.properties for benchmark, list out all the mapping table's names we are using during the tests. They can case sensitive, so for example, it should be something like:

table.mapper.cache.mapping.table.names=Users_Groups,Users_Orgs,Users_Roles, ......

As long as you cover all the tables the tests are using, this should not affect any performance number.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c2e322b2c7...e40e56e73d

**Pull request closed without merging**
