### PR TITLE
LPS-52734 use previous default language value for friendlyURLs when default language has changed

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Should we write an integration / unit for test this?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d570ba45fb...8af6a5b854

**Comment by juliocamarero** [comment]
Sure, we will write an integration test. @yuhai is aware of it. Thanks!

**Pull request closed without merging**
