### PR TITLE
LPS-156375 Upgrade report: add total upgrade time

### PR DESCRIPTION
**Pull request by achaparro**
LPS-156375

### CODE REVIEW

**Comment by achaparro** [comment]
ci:reopen

**Comment by achaparro** [comment]
Failed tests are unrelated

**Comment by achaparro** [comment]
cc/ @LuisOrtiz89

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7040cba4dc...269393859f

**Comment by brianchandotcom** [comment]
@LuisOrtiz89 @achaparro see 269393859f9b1a4cb93beb8abdc357cd251ccb9b

**Pull request closed without merging**
