### PR TITLE
LPS-44701 Do not overwrite existing parameters and merge params everytime we call toString()

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a02ef52643...1527496f33

**Comment by brianchandotcom** [comment]
@mdelapenya @topolik please review my changes in upstream. Thx.

**Comment by topolik** [comment]
Looks fine. Thanks @brianchandotcom and @mdelapenya!

**Pull request closed without merging**
