### PR TITLE
LRQA-30012, LRQA-30154, LRQA-30080, LRQA-30197 | 7.0.x

### PR DESCRIPTION
**Pull request by alee8888**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@shuyangzhou I've seen this randomnly a few times now. BundleSupportAntTest.testInitBundleTarProxy

**Comment by jpince** [comment]
I asked @Ithildir to look into this, not sure if he already sent a fix?

**Comment by Ithildir** [comment]
I'm looking into it.

**Comment by shuyangzhou** [comment]
@Ithildir let me know if you need help.

**Comment by Ithildir** [comment]
Thank you Shuyang! I sent [another pull](https://github.com/brianchandotcom/liferay-portal/pull/46322) that, hopefully, should fix the problem once and for all! Fingers crossed 😅

**Pull request closed without merging**
