### PR TITLE
LPS-113207 Regen

### PR DESCRIPTION
**Pull request by rodrigocunhaa**

### CODE REVIEW

**Comment by rodrigocunhaa** [comment]
Forwarded from https://github.com/inacionery/liferay-portal/pull/660#issuecomment-627577790. The same reason as https://github.com/brianchandotcom/liferay-portal/pull/88624.

**Comment by rodrigocunhaa** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@rafaprax @inacionery

```
OrderByComparator<WorkflowInstance> comparator
```

There may be other misnamed vars.

**Pull request closed without merging**
