### PR TITLE
LPD-41116 Update of client extensions through the UI can randomly fail in clustered environments

### PR DESCRIPTION
**Pull request by izaera**
This is a rebase of https://github.com/brianchandotcom/liferay-portal/pull/156270

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@izaera the unit test nice, but it doesn't give me confidence that this actually works. I need some sort of integration or functional test. And I know we've done clustering tests before, so I don't see why we can't do it now. The unit test just tells me you've ingrained your new behavior in stone (via a unit test). But it doesn't tell me that the new behavior is correct.

Please resend on top of https://github.com/izaera/liferay-portal/pull/180

**Comment by tinatian** [comment]
@brianchandotcom 

All current clustering tests are old poshi tests now, the plan is to add integration test support for clustering then move them to integration test, but core infra did not have bandwidth to do it yet, see https://liferay.atlassian.net/browse/LPD-40582.

So options to add clustering test now:
1. Add Poshi test
2. Wait for core infra's clustering integration support.

For this specific case, it is hard to add Poshi test, as it is a random issue, Poshi test did not provide anyway to control in that layer to make you write a test to expose the issue.


FYI @izaera @vicnate5

**Comment by vicnate5** [comment]
@izaera You can run our existing clustering scenarios with `ci:test:clustering`

**Comment by tinatian** [comment]
@brianchandotcom Yes, we have tests for normal cases, but those are only testing clustering framework basic behavior, not test how client extension is using cluster framework, and the changes here are all in client extension scope, thus, I do not think those can be used to tell regression, but it won't hurt anything if we trigger and verify tests by ci:test:clustering

**Comment by brianchandotcom** [comment]
@tinatian we need to add a client extension test to ```ci:test:... clustering```` or else the general tests are useless.

I need to know via automation that client extensions still work. I'm OK with not testing the edge case because it's hard to reproduce. But I need tok now the MAIN cases for client extensions works in a clustered env.

@vicnate5 @izaera fyi

**Pull request closed without merging**
