### PR TITLE
LPS-61759 Update default admin and company accounts within Setup Wizard, caused by b209bf2fa4b03738ee002ca64d7aac2e747cd37a

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by mdelapenya** [comment]
It's a weird error related to ElasticSearch:
````
com.liferay.poshi.runner.PoshiRunner > test[SetupWizard#HypersonicToHypersonic] STANDARD_OUT
     [exec]     LIFERAY_ERROR: failure in bulk execution:_[1]: index [20202], type [LiferayDocumentType], id [com.liferay.portal.kernel.model.Contact_PORTLET_20251], message [[20202][[20202][0]] CreateFailedEngineException[Create failed for [LiferayDocumentType#com.liferay.portal.kernel.model.Contact_PORTLET_20251]]; nested: NoSuchFileException[/opt/dev/projects/github/liferay-portal/bundles/data/elasticsearch/indices/LiferayElasticsearchCluster/nodes/0/indices/20202/0/index/_9.fdx];] [Sanitized]
     [exec]     This will shutdown the server at ${base_branch}-bundles\tomcat.
     [exec]     Buildfile: /opt/dev/projects/github/liferay-portal/build-test.xml
```

Not sure how this is affecting :(

**Comment by mdelapenya** [comment]
ci:retest

**Comment by alee8888** [comment]
@mdelapenya the Setup Wizard test that is failing is actually because Poshi is unable to find the email address field html locator which I believe is caused by your commit here: 17c7662. I am fetching your branch and will fix the functional test and can send a combined PR if you would like.

Also that shutdown error you see with Elasticsearch, we filed something similiar in LPS-57893 but I am looking into it right now. Thanks!

**Comment by mdelapenya** [comment]
Could it be related to https://issues.liferay.com/browse/LRQA-22072?

**Comment by alee8888** [comment]
The actual failure occurs here where Poshi tries to type 'test@liferay.com' to the email text field.

`<execute function="Type" locator1="TextInput#EMAIL" value1="${administratorEmail}" />`

Concerning LRQA-22072 the bundle is wiped clean before each test is run on the slave. So an existing portal-setup-wizard.properties in the bundle shouldn't be a problem.

**Comment by brianchandotcom** [comment]
@alee8888 @mdelapenya please resend. Thx.

**Pull request closed without merging**
