### PR TITLE
LPS-66577 Lexiconify error page

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
@brianchandotcom looks good from a functional test perspective. One test failed due to an occurrence of LPS-65961, the other two are flukes.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0085f116da...2c93d27310

**Comment by brianchandotcom** [comment]
See 2c93d27310e342dc57e9b96109adf43ad42d5136 thx

**Pull request closed without merging**
