### PR TITLE
LPS-88293

### PR DESCRIPTION
**Pull request by topolik**
Hi Brian,

https://issues.liferay.com/browse/LPS-88293

Thank you.

/cc @ivicac

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2be2dcee25...869c6f0f93

**Comment by brianchandotcom** [comment]
@topolik @ivicac backported and published new jars for you in 7.1.x and 7.0.x.

**Comment by topolik** [comment]
Thanks @brianchandotcom !

**Comment by ivicac** [comment]
thx @brianchandotcom

**Pull request closed without merging**
