### PR TITLE
LPS-161255 - Test Scenarios Coverage | Backend

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-161255

@ruben-pulido

### CODE REVIEW

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/9670

:heavy_check_mark: ci:test:stable - 28 out of 28 jobs passed
:x: ci:test:relevant - 181 out of 187 jobs passed in 2 hours 26 minutes

**Comment by ozysouza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/abafde024e...644ffd5143

**Comment by brianchandotcom** [comment]
@ozysouza @ruben-pulido see 9426f15c4656793b9e2c4a01fb0ff705320633db and 644ffd5143662cb4a084d8515aa4c5747d6c37d1

I had to fix a compile error.

**Pull request closed without merging**
