### PR TITLE
LPS-107895 count

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a387bf2c82...a4bbd79e00

**Comment by brianchandotcom** [comment]
@nhpatt @javierdearcos see a19c02327f55ac44292e7688ca791cbb1bb881f1

**Comment by nhpatt** [comment]
Thanks!

**Comment by javierdearcos** [comment]
Great!  Thank you very much @brianchandotcom 

My first attempt was:
queryPos.add(visible ? [$TRUE$] : [$FALSE$]);

I thought it was not possible to pass the boolean value directly and it was necessary to pass the placeholders to keep database compatibility.

I'll remember for the future

**Pull request closed without merging**
