### PR TITLE
Lps 65067 lpkg startup test

### PR DESCRIPTION
**Pull request by shuyangzhou**
Just a raw test to give us some protection, considering how complex the lpkg deploying logic is, it could easily break.

A more fine tuned arquillian test with detailed assertions will come soon.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/29bac6330d...677d904c87

**Comment by brianchandotcom** [comment]
@mtambara @shuyangzhou 

Can you guys add a quick "verfiy/assert" in the Ant target, to make sure that osgi/marketplace actually has LPKG files, and that osgi/modules and osgi/portal are empty?

@Ithildir fyi (we need your updates to get rid of deployed dependencies)

Thx.

**Comment by Ithildir** [comment]
I talked about removing the deployed dependencies to @rotty3000, he told me I can't do it :confused:

**Comment by brianchandotcom** [comment]
@Ithildir we have to, or else MP won't know who deployed X dependency. And we'd have to add a new way to map an LPKG jar to our own artifacts+ other dependencies. We either have to remove it or find a way for Chas to know to build it into the LPKG. Let's talk to @shuyangzhou and @rotty3000 tomorrow.

**Comment by shuyangzhou** [comment]
We will do the lpkg file scanning as part of the follow up arquillian test, more fine tuned assertions can be done by java code rather than ant script.

There must be ways to remove those 3rd party dependencies. And we should do it.

**Pull request closed without merging**
