### PR TITLE
LPS-82572 Baseline

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
Sent to 7.1.x here: https://github.com/brianchandotcom/liferay-portal-ee/pull/20616

cc:// @matethurzo

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@brianchandotcom, no major changes in package this time...

**Comment by jkappler** [comment]
ci:reopen

**Comment by jkappler** [comment]
resent to 7.1.x here: https://github.com/brianchandotcom/liferay-portal-ee/pull/20617

**Comment by jkappler** [comment]
@brianchiu: These issues doesn't seem to be related to the PR, just checking with you. Thanks!

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by jkappler** [comment]
sent to 7.1.x here: https://github.com/brianchandotcom/liferay-portal-ee/pull/20626

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@jkappler @brianchiu console errors related to kaleo are unrelated, Brian will have to look at the POSHI test failures

cc/ @anthony-chu

**Comment by brianchiu** [comment]
Those functional test failures are fine. They're all test fixes.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/74c6991f5c...f3659f9d33

**Pull request closed without merging**
