### PR TITLE
SYNC-1721

### PR DESCRIPTION
**Pull request by mikemanyoung**

### CODE REVIEW

**Comment by brianwulbern** [comment]
@sergiogonzalez same failure as on https://github.com/brianchandotcom/liferay-portal/pull/47429

**Comment by brianwulbern** [comment]
ci:reopen (failures unrelated to the pull)

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@dejuknow see my changes in upstream. Thx.

**Pull request closed without merging**
