### PR TITLE
LPS-58641 Get default values

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
cc /@juliocamarero

**Comment by robertoDiaz** [comment]
Hey @brianchandotcom, is there anything wrong with this pull?

We are waiting this code to be merged to include some changes.

Thanks!! :)

**Comment by brianchandotcom** [comment]
@sergiogonzalez @robertoDiaz sorry for dropping the ball on this one. Do you mind rebasing and resending? Merge conflict. Thx.

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
