### PR TITLE
LPS-69521

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@drewbrokke Try 2.0.0. If it doesn't work. All versions are here:

https://repository.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/portal/com.liferay.portal.kernel/

Try the largest number. If that doesn't work, then it should be "default" (basically, the unpublished local version)

If the largest number works, pick a middle number (so if 2.10.0 works, try 2.5.0). Eventually, with trial and error ,find the lowest number. :) Sorry. No easier way yet.

**Comment by mhan810** [comment]
@brianchandotcom @drewbrokke I already checked it :)  2.6 is the earliest one we can do this.

**Comment by brianchandotcom** [comment]
@drewbrokke 

From modules, I ran

gradlew :apps:foundation:configuration-admin:configuration-admin-web:clean :apps:foundation:configuration-admin:configuration-admin-web:compileJSP

portal-impl 2.5.0 failed, but 2.6.0 worked. So I know that's the lowest required version.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by drewbrokke** [comment]
@brianchandotcom @mhan810 thanks!  That link is solid gold 👍

**Pull request closed without merging**
