### PR TITLE
LPS-95667 Lazy service context initialization to avoid race condition.

### PR DESCRIPTION
**Pull request by epgarcia**
@jpince @vicnate5 This PR fixes the upgrade issues introduced by #74230.

### CODE REVIEW

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jpince** [comment]
@epgarcia thanks!

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@epgarcia See 2cbffa2a5a30f78860b6812ac6f150f2581de8a8

In general, *Util is for static classes. *Helper is for instantiated classes. In your case, I just dropped *Util.

@hhuijser can we SF enforce ?

**Comment by epgarcia** [comment]
OK, I had seen it in other non-static cases such as JournalDDMTemplateUtil, SharingUtil or AssetRSSUtil, but I'm fine with making it clearer via SF.

**Pull request closed without merging**
