### PR TITLE
LPS-76944 Utilities to handle encoding and decoding scoped PID strings

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-76944](https://issues.liferay.com/browse/LPS-76944).<br><br>/cc @pei-jung, @jorgeferrer

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test

**Comment by drewbrokke** [comment]
@brianchandotcom these are new tools, but there are no usages in this pull.  The tests for the larger parent pull passed here: https://github.com/brianchandotcom/liferay-portal/pull/54178#issuecomment-356147050.

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
@drewbrokke @pei-jung see my changes in upstream. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d6a36fbf97...8784a10947

**Pull request closed without merging**
