### PR TITLE
LPS-51344 set listable to true by default to all assets

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a760189fb4...d770ba317d

**Comment by brianchandotcom** [comment]
@juliocamarero @BryanEngler This contains changes to a modified file? *PersistenceImpl should not be modified except via a regeneration commit.

**Comment by brianchandotcom** [comment]
Also, @juliocamarero @BryanEngler that ticket is already closed and pushed to a released version. Please use a new LPS.

**Comment by BryanEngler** [comment]
@juliocamarero - ill send you a pr with the new LPS and the correct changes

**Comment by juliocamarero** [comment]
Thanks a lto @BryanEngler!

**Pull request closed without merging**
