### PR TITLE
Commerce 4862 commerce-order-content-web escape address fields

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/af822e8bbe...a93498ff90

**Comment by brianchandotcom** [comment]
@andrea-ale-sbarra see a93498ff906076df5d5cf91b07866be2d5f80587

**Comment by andrea-ale-sbarra** [comment]
thanks @brianchandotcom

**Comment by brianchandotcom** [comment]
@andrea-ale-sbarra @hhuijser I was wrong about a93498ff906076df5d5cf91b07866be2d5f80587

and I reverted it in d86a9a6995976904d823c68a2920a192a437f0f5

I didn't see the Html.escape. My bad.

**Pull request closed without merging**
