### PR TITLE
LPS-105235 wrong array naming

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2c5fa4cfba...9512d18e1a

**Comment by nhpatt** [comment]
Thanks!

**Comment by jpince** [comment]
@stsquared99 @yichenroy LRCI-881 was supposed to get rid of the `.gitrepo` file check in CI, and I see Sam did a new release under the same ticket number. Why did this pull autoclose with `error: Illegal change to a .gitrepo file.`?

**Comment by yichenroy** [comment]
@stsquared99 
I see the whitelist portion being added back in the release commit in liferay-subrepo-tools, could this be the reason the `.gitrepo` validation is still there?
https://github.com/liferay/liferay-subrepo-tools/commit/6e2ec8bfd172956786f3ac37bf2a2b83bb982d7d

**Comment by stsquared99** [comment]
Oh looks like that was by accident, I'll fix it real quick

**Comment by stsquared99** [comment]
@jpince @yichenroy Should be fixed now

**Comment by jpince** [comment]
@stquared99 thank you!

**Comment by yichenroy** [comment]
thank you @stsquared99!

**Pull request closed without merging**
