### PR TITLE
LPS-167062 Create Advanced tab when editing a field in the side panel

### PR DESCRIPTION
**Pull request by danvb112**
Related Issue: https://issues.liferay.com/browse/LPS-167062

### CODE REVIEW

**Comment by danvb112** [comment]
ci:reopen

**Comment by danvb112** [comment]
Hey @brianchandotcom , I'm submitting this PR directly after the original failed a lot in unrelated tests

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9aad769f12...3f09f52938

**Comment by brianchandotcom** [comment]
@danvb112 see ef9a7b7fe80acbca0d4a5c61848869defd84d616

**Pull request closed without merging**
