### PR TITLE
LPS-79473 Set ascending order for 'completed' field for WorkflowTaskDueDateComparator

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7962d74a4f...361f11963d

**Comment by brianchandotcom** [comment]
See 6443b44 thx

**Comment by JosemariaMunoz** [comment]
Ok, thank you.

**Comment by jeyvison** [comment]
Hi @brianchandotcom , Could you please explain why [this SF change](https://github.com/brianchandotcom/liferay-portal/commit/6443b444c6be74f3e3455196e0a13a1381a683ec) is better than the former way?

**Pull request closed without merging**
