### PR TITLE
Lps 103541

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/79948

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/41c3b09530...dead9b0e1a

**Comment by brianchandotcom** [comment]
@mtambara I backported this to 7.2.x, can you port to 7.1.x and 7.0.x if it will save us headache in the future?

**Comment by mtambara** [comment]
7.1.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/27244

7.0.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/27243

**Pull request closed without merging**
