### PR TITLE
LPS-71745 Fix temp directory cleanup for Windows

### PR DESCRIPTION
**Pull request by tomwang2011**
CC @shuyangzhou

Hi Brian, this is the resend of https://github.com/brianchandotcom/liferay-portal/pull/49850 after typo fix, thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@shuyangzhou can you take a look at this Adaptive Media issue?

I've brought it up with @ealonso and @adolfopa already

It's currently randomly breaking CI modules-int* tests. It's already broken it 4 out of 5 times here.

**Comment by shuyangzhou** [comment]
Ok, I will be on it soon.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d75ef9a9fe...d23c0aa7b5

**Comment by adolfopa** [comment]
@shuyangzhou This issue seems to be caused by the async processing done in Adaptive Media. Some tests create and delete file entries very fast; in the middle of the process, the adaptive media async processing kicks in and it fails when it cannot find the file entry that just got deleted.

I think this could be solved if we could somehow plug in the adaptive media destination into the Sync rule (there are potentially lots of tests that need this, so doing it on each individual test is going to be very tedious and error prone).

**Pull request closed without merging**
