### PR TITLE
OAUTH2-259 SF

### PR DESCRIPTION
**Pull request by csierra**
/cc @topolik @martamedio @stian-sigvartsen @ealonso

### CODE REVIEW

**Comment by jpince** [comment]
@xbrianlee @joshchong POSHI error, not sure if it's related

**Comment by xbrianlee** [comment]
ci:test:bundle

**Comment by joshchong** [comment]
Pre-emptive test fix for failing Poshi test sent here: https://github.com/brianchandotcom/liferay-portal/pull/72646

The change shouldn't affect test results before this PR is merged.
cc @xbrianlee

**Comment by brianchandotcom** [comment]
InvalidClientCredentialUserIdException was added but not used anywhere.

In any case, can you reanme it to OAuth2ApplicationClientCredentialUserIdException

**Comment by brianchandotcom** [comment]
@csierra please resend, see my comment above.

**Comment by csierra** [comment]
please see https://github.com/brianchandotcom/liferay-portal/pull/72718

**Pull request closed without merging**
