### PR TITLE
LPS-69814 Implement Validation Check for Manual File Upload

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@brianikim Merged, but you should have created a new ticket. https://issues.liferay.com/browse/LPS-69814 says it's already backported to 7.0.x, but in this case, it's not true because this new commit you've done hasn't been backported. Please ensure this goes back to 7.0.x. Thx.

**Pull request closed without merging**
