### PR TITLE
LPS-85311 Update bnd

### PR DESCRIPTION
**Pull request by jkappler**
Hi @brianchandotcom, this a follow up to the previous pull for upgrade process, but in this case, it cannot be backported (for 7.2)

As for the upgrade of layouts, I used service calls instead of a query to the DB since it's a table from the portal. I hope it makes sense. 

Please let me know if I should change anything. Thanks!

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by brianchandotcom** [comment]
@jkappler this is going to kill the DB

		List<Layout> layouts = _layoutLocalService.getLayouts(
			QueryUtil.ALL_POS, QueryUtil.ALL_POS);

Imagine 1 million layouts. Please resend on top of https://github.com/jkappler/liferay-portal/pull/262

Use ActionableDynamicQuery? Thx.

**Comment by jkappler** [comment]
ci:reopen

**Comment by jkappler** [comment]
@kyle-miho, @brianchiu, these issues don't seem to be related to the pull. Please let me know, thanks

**Comment by jkappler** [comment]
sorry, reopened the wrong one

**Comment by brianchiu** [comment]
ci:test:relevant

**Pull request closed without merging**
