### PR TITLE
LPS-66831 As a Roles Admin user, I would like to see the number of assignees for each role in the role search results

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-66831](https://issues.liferay.com/browse/LPS-66831).

All mentioned please see ddf36e0 and    54afe6b

@brianchandotcom @juliocamarero I sent a pull to `com-liferay-journal` with the dependency updates:
https://github.com/liferay/com-liferay-journal/pull/11.  Not sure if this is the right workflow, so let me know if there's anything else I should do :)  I'm assuming ci will fail since this pull doesn't include updates to journal-web.

Thanks!

/cc @juliocamarero @sergiogonzalez @marcellustavares @dejuknow @rotty3000 @arboliveira @pei-jung @lionah @jorgeferrer

### CODE REVIEW

**Comment by drewbrokke** [comment]
Closing until https://github.com/liferay/com-liferay-journal/pull/11 is merged.

**Comment by drewbrokke** [comment]
@jpince

**Comment by brianchandotcom** [comment]
@drewbrokke journal is merged. Please resend.

**Comment by drewbrokke** [comment]
@brianchandotcom Okay resent: brianchandotcom#43457

Where was it merged?  A different pull than mine?

**Pull request closed without merging**
