### PR TITLE
LRQA-57805 | master

### PR DESCRIPTION
**Pull request by nikki-pru**
https://issues.liferay.com/browse/LRQA-57805

### CODE REVIEW

**Comment by nikki-pru** [comment]
@brianchandotcom, this fixes the sync issue for master. Thanks.

**Comment by nikki-pru** [comment]
ci:open

**Comment by nikki-pru** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0446138eeb...3d6b011513

**Pull request closed without merging**
