### PR TITLE
LPS-67828 Apple push notification tokens should be deleted when they are invalid

### PR DESCRIPTION
**Pull request by brunofarache**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@brunofarache I see it here now. Thx!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5f3b7bbd59...d399a9b1d8

**Comment by vicnate5** [comment]
@brianchandotcom @brunofarache There is a startup error now occuring at head that looks to be caused by this pull.

```
     [exec] INFO - Completed verification process com.liferay.document.library.verify.DLServiceVerifyProcess in 81ms
     [exec] 23:32:45,742 INFO  [localhost-startStop-1][ServiceComponentLocalServiceImpl:317] Running PushNotifications SQL scripts
     [exec] 23:32:45,769 ERROR [localhost-startStop-1][com_liferay_push_notifications_sender_apple:97] [com.liferay.push.notifications.sender.apple.internal.messaging.ApplePushNotificationsMessagingConfigurator(1620)] The activate method has thrown an exception 
     [exec] java.lang.NullPointerException
     [exec] 	at com.liferay.push.notifications.sender.apple.internal.messaging.ApplePushNotificationsMessagingConfigurator.activate(ApplePushNotificationsMessagingConfigurator.java:48)
```

**Comment by brunofarache** [comment]
Thanks @vicnate5.

@brianchandotcom @Ithildir: how can I make sure [ApplePushNotificationsMessagingConfigurator.java](https://github.com/brianchandotcom/liferay-portal/blob/master/modules/apps/push-notifications/push-notifications-sender/push-notifications-sender-apple/src/main/java/com/liferay/push/notifications/sender/apple/internal/messaging/ApplePushNotificationsMessagingConfigurator.java) depends on [PushNotificationMessagingConfigurator.java](https://github.com/brianchandotcom/liferay-portal/blob/master/modules/apps/push-notifications/push-notifications-service/src/main/java/com/liferay/push/notifications/internal/messaging/PushNotificationMessagingConfigurator.java)?

More precisely, how can the push-notifications-sender-apple module depend on the push-notifications-service module?

**Comment by brunofarache** [comment]
I added this dependency to Apple Sender:

```
provided group: "com.liferay", name: "com.liferay.push.notifications.service", version: "1.0.0"
```

I undeployed "Liferay Push Notifications Service" but Gogo shell says Apple Sender is still "Activate", even when I restart the portal.

"Liferay Push Notifications Web" also depends on on it and went to "Resolved", as expected. 

There's something the Web module does that Apple's module is not doing.

**Comment by brunofarache** [comment]
OK, the guys here explained what's going on.

Even if I add a dependency to *-service in build.gradle, the bnd tool removes the import because I'm not directly referencing any class from it.

Because of this, I'll move the message bus destination configuration to the *-api module. 

Since *-service and *-sender-apple depend on *-api, they will register their message listener properly.

I will send a PR to fix this later today.

**Pull request closed without merging**
