### PR TITLE
LPS-69211 Move the User file uploads settings UI from Server Administration to System Settings

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-69211](https://issues.liferay.com/browse/LPS-69211).<br><br>/cc @pei-jung @jorgeferrer

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by drewbrokke** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@drewbrokke can you resend

```
public boolean getImageCheckToken
```

Should be an "is*" since it's a boolean.

Thx.

**Comment by drewbrokke** [comment]
@brianchandotcom good catch thank you :)

**Pull request closed without merging**
