### PR TITLE
LPS-63180

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@shuyangzhou hey you originally removed classloaders from the API, but with our OSGi move, we need to add them back and actually do the reverse (probably) deprecate the servlet context name param

**Comment by shuyangzhou** [comment]
@mhan810 this will fail the portal resiliency, as classloader is not serializable. We need a new way to look up osgi classloader by some sort of serializable id. But portal resiliency is broken anyway, we can do this for now, just by the time I fix this, I will have to change the interface again which won't be backward compatible.

**Comment by mhan810** [comment]
@shuyanhzhou OK let me change to using bundleId or something

Sent from my mobile device.

**Comment by shuyangzhou** [comment]
@mhan810 bundle is won't be reuseable across jvms, it depends on the installation ordering.

We should use symbolic name + version to id a bundle classloader.

**Pull request closed without merging**
