### PR TITLE
LPS-62556 Modules are not picking on the combine setting

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by marcellustavares** [comment]
Hey @jbalsas, it seems we have poshi failures regarding translations.

**Comment by jbalsas** [comment]
Yeah, funny enough, the tests are asserting the content is `show-more-options` instead of the key value :wink:

**Comment by marcellustavares** [comment]
got it :) I thought the exactly opposite, it's fine then. Please close this one @jbalsas. I'll fix the test.

**Comment by jbalsas** [comment]
All yours, then! Thanks! :wink:

**Pull request closed without merging**
