### PR TITLE
LPS-109260 Build lang

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/85328

**Pull request closed without merging**
