### PR TITLE
LPS-82717 SF

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @SamZiemer @brianikim @robertoDiaz

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianikim** [comment]
Hello @sergiogonzalez ,

To respond to your comment from here: https://github.com/sergiogonzalez/liferay-portal/pull/4510#issuecomment-403429112

> Documents and Media will try to obtain the extension from the file name uploaded and if it's not possible, it will try to obtain it from the title of the document as a fallback. We want to keep this behaviour.

Your fix definitely makes sense and thank you for the explanation of what the expected behavior should be.

However, it seems to suggest a liability in user experience as Documents and Media is described to be:

[`The Documents and Media library stores files on the server using the same type of structure that you use to store files locally.`](https://dev.liferay.com/en/discover/portal/-/knowledge_base/7-1/managing-documents-and-media)

I understand the fallback is harmless in that an empty file with any extension should be harmless, but I am still failing to understand why the fallback is necessary in the first place? The current behavior is that if you do not upload a file and name a file as "test.exe", an executable file will be downloaded because the title is being used as a fallback to determine the MimeType and Extension. 

If the primary purpose of Documents and Media is to act as a Storage for potential uploads by users, is there a valid use-case for us to ever use the title in deciding the MimeType and Extension of a Document?

Sincerely,
Brian Kim

**Comment by sergiogonzalez** [comment]
Hey @brianikim 

The title will be used as a fallback, so in most of the cases it won't be used, but if for any reason we cannot obtain it from the file, we decided to better use the title than not having that information at all.

**Pull request closed without merging**
