### PR TITLE
Lps 56976

### PR DESCRIPTION
**Pull request by shuyangzhou**
@mhan810

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ecc6865bd9...86997c0107

**Comment by brianchandotcom** [comment]
Nice job @shuyangzhou  :)

**Comment by brianchandotcom** [comment]
@shuyangzhou any way to "test" this?

**Comment by shuyangzhou** [comment]
Sure, I will add in a test for this a bit later.

**Pull request closed without merging**
