### PR TITLE
LRQA-68153 Add readme directory and make strict relationship to root directory

### PR DESCRIPTION
**Pull request by vicnate5**
@jhinkey @pyoo47

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:reopen

**Comment by vicnate5** [comment]
@pyoo47 changes to this property are painful to test because CI cannot be configured to run with modified `ci.properties` [for this check](https://github.com/liferay/liferay-jenkins-ee/blob/master/commands/build-test-portal-acceptance-pullrequest.xml#L1380), it is [hardcoded to use the file from head](https://github.com/liferay/liferay-portal/blob/master/modules/test/jenkins-results-parser/src/main/java/com/liferay/jenkins/results/parser/JenkinsResultsParserUtil.java#L1242-L1251).

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0017153a35...8adeb5fe30

**Comment by brianchandotcom** [comment]
Nice @vicnate5

**Comment by pyoo47** [comment]
> @pyoo47 changes to this property are painful to test because CI cannot be configured to run with modified `ci.properties` [for this check](https://github.com/liferay/liferay-jenkins-ee/blob/master/commands/build-test-portal-acceptance-pullrequest.xml#L1380), it is [hardcoded to use the file from head](https://github.com/liferay/liferay-portal/blob/master/modules/test/jenkins-results-parser/src/main/java/com/liferay/jenkins/results/parser/JenkinsResultsParserUtil.java#L1242-L1251).

@vicnate5, 
`ci.properties` contains sensitive CI control properties that  we would not really want to allow overriding by users in a pull request. That said, the properties are visible and may be changed if users submit their changes in a pull request which is reviewed and merged. In terms of testing these properties, these properties can usually be tested manually outside of CI. 

If you want to test the regular expressions in `ci.test.relevant.bypass.file.path.patterns` I can probably write a quick program for you that will apply the patterns to all the files in a given directory and list the matching ones so you can see if the pattern matches all the files you intended and doesn't include files that you did not intend to match.

**Comment by vicnate5** [comment]
@pyoo47 Thanks for explaining, I ended up writing a modified version of the beanshell script used by Jenkins and was able to test the pattern locally.

**Pull request closed without merging**
