### PR TITLE
LPS-98203 Frontend tests

### PR DESCRIPTION
**Pull request by brunofarache**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a785193feb...9a714241f3

**Comment by brianchandotcom** [comment]
@brunofarache can you sort this

```
Row key={row.id} data-testid='row'
```

to

```
Row data-testid='row' key={row.id}
```
and make sure to use " instead of '

@wincent can we auto enforce those 2 thigns (sorting of attributes and preferring " over ')? See modules/apps/app-builder/app-builder-web/src/main/resources/META-INF/resources/js/components/search-container/Table.es.js

**Comment by wincent** [comment]
@brianchandotcom: yes, we can autoenforce both those things. I created a draft PR showing what the change will look like here: https://github.com/wincent/liferay-portal/pull/42

- The use of double quotes in JSX property names comes via Prettier and will apply to all ".js" files.
- The sorting of properties comes via ESLint, and therefore only applies to "modern" (ie. ".es.js" files).

I'll send a real PR to your fork before the end of the day here (not sending that draft one because I may have other changes to make to `liferay-npm-scripts`).

**Comment by wincent** [comment]
PR for sorting and quoting is up here: https://github.com/brianchandotcom/liferay-portal/pull/75763

**Pull request closed without merging**
