### PR TITLE
LPS-79312 update test

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:reopen

**Comment by matethurzo** [comment]
@jpince this is definitely not related, how could this import be missing? there has been some refactoring?

**Comment by jpince** [comment]
@matethurzo I think you're right. In upstream, I see is that @cgoncas and @jkappler made some changes in that test module this morning, maybe another change is needed to update the dependency for your test? See https://github.com/brianchandotcom/liferay-portal/pull/62268

@cgoncas @jkappler you can cherry-pick https://github.com/jpince/liferay-portal/pull/70/commits/283d31d128107149063603252009598531605366 and ci:test to quickly verify against all integration tests in the modules folder (without running all of the tests).

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ff0dc01fac...2dc578f54a

**Pull request closed without merging**
