### PR TITLE
LPS-160851 Update upgrade process

### PR DESCRIPTION
**Pull request by seltong**

### CODE REVIEW

**Comment by seltong** [comment]
ci:reopen

**Comment by seltong** [comment]
The failures [here](https://github.com/liferay-objects/liferay-portal/pull/966) are not related.

**Comment by brianchandotcom** [comment]
@seltong avoid

```
storageType <>
```

We have it in a few places but I prefer not to use it if we don't have to. Please resend. Thx.

**Comment by seltong** [comment]
Resent [here](https://github.com/brianchandotcom/liferay-portal/pull/122240)

**Pull request closed without merging**
