### PR TITLE
Lps 73021

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
CC @tomwang2011

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1911a95d5d...02d6995065

**Comment by brianchandotcom** [comment]
@ithildir please review modules/apps/wiki-engine-mediawiki/wiki-engine-mediawiki/build.gradle

@shuyangzhou please backport? Thx.

**Comment by Ithildir** [comment]
The change in this pull is correct, but that file had a small SF problem, I sent you https://github.com/brianchandotcom/liferay-portal/pull/49553 to fix it.

**Pull request closed without merging**
