### PR TITLE
LPS-102576 blacklist

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/eeb8c6f3a9...af9b30d015

**Comment by brianchandotcom** [comment]
@nhpatt backported for you.

**Comment by brianchandotcom** [comment]
@nhpatt minor change in af9b30d0154cb8f73ee618bc586046d095f20092

**Comment by nhpatt** [comment]
Thank you :) :)

**Pull request closed without merging**
