### PR TITLE
LPS-84076 SF

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by vicnate5** [comment]
Tests are good.

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchandotcom** [comment]
@brunobasto 
can you resend:

```
		String mvcPath = ParamUtil.getString(
			actionRequest, "mvcRenderCommandName");
```

Lots of random var names need to be renamed properly @jeyvison

**Comment by brunobasto** [comment]
Hey @brianchandotcom, sure. Will do.

**Pull request closed without merging**
