### PR TITLE
LPS-102584 Create Configuration option for React-variant Page Editor

### PR DESCRIPTION
**Pull request by wincent**
This is a preliminary for the React-based prototype of layout-content-page-editor-web.

See https://github.com/wincent/liferay-portal/pull/67 for the work-in-progress on the React side of this.

### CODE REVIEW

**Comment by wincent** [comment]
cc @jbalsas @ealonso

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/af9b30d015...ac9d77f0eb

**Comment by brianchandotcom** [comment]
@wincent @ealonso @jbalsas

Why would we want to maintain both the Soy and the React variant? This is an internal implementation detail.

We should stick to one version and delete the other one. We don't even need to deprecate stuff like this.

@jbalsas please Slack me if I'm wrong.

@wincent merged.. please send a follow up pull.

**Comment by brianchandotcom** [comment]
@wincent @jbalsas my bad, I re-read your LPS comments. I assume this is just temporary. My bad!

**Comment by brianchandotcom** [comment]
@ealonso fyi.. I re-read the LPS, I see that this is just a temporary toggle.

**Pull request closed without merging**
