### PR TITLE
LPS-66636

### PR DESCRIPTION
**Pull request by lionah**

### CODE REVIEW

**Comment by lionah** [comment]
cc: @shuyangzhou, please review and sign off before @brianchandotcom merges.

**Comment by lionah** [comment]
Some assumptions I've made:

* Liferay Static does not return any installed bundle information from `LPKGDeployer.getDeployedLPKGBundles()`
* The list of bundles in the `Map` that is returned by `getDeployedLPKGBundles()` is not the same as the list returned from the `install(..)`method. More specifically, it doesn't contain the LPKG Bundle which is the key.

**Comment by shuyangzhou** [comment]
Just needs a tiny change, @lionah will add it.

**Comment by lionah** [comment]
Changed!

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c08ba91187...2ebda600c8

**Pull request closed without merging**
