### PR TITLE
LPS-60922

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
/cc @rotty3000 @shuyangzhou @Ithildir

Let's see if this passes the tests first...

**Comment by hhuijser** [comment]
@brianchandotcom 

I am not autofixing the bnd.bnd, because I don't want to potentially touch the same file at the same moment twice (BNDSourceProcessor and JavaSourceProcessor) and cause problems.

**Comment by hhuijser** [comment]
@brianchandotcom @rotty3000 @shuyangzhou

So, apparently the changes in the *ExportCapability and *ImportCapability classes are breaking the tests.

Do you think this is because:
1. We can't to this when the superclass is in a different module
2. We can't do this when we are calling super.setXXX in the method
3. Some other reason...

**Comment by brianchandotcom** [comment]
@hhuijser please resend after the guys help you with this. Thx.

**Comment by hhuijser** [comment]
@shuyangzhou

You have any idea why the changes in *ExportCapability and *ImportCapability classes are breaking the tests?

**Pull request closed without merging**
