### PR TITLE
Lps 76695 1 5

### PR DESCRIPTION
**Pull request by slnn**

### CODE REVIEW

**Comment by slnn** [comment]
ci:test

**Comment by slnn** [comment]
Cc: @4lejandrito

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/00f933c7f2...78efe46920

**Pull request closed without merging**
