### PR TITLE
LPS-147432 Enforce using Poshi Script instead of Poshi XML

### PR DESCRIPTION
**Pull request by ling-alan-huang**
https://issues.liferay.com/browse/LPS-147432
Tested [here](https://github.com/ling-alan-huang/liferay-portal/pull/666), unrelated failures.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5ef214414f...3b5cfe0822

**Pull request closed without merging**
