### PR TITLE
Lps 94207

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
CC @vicnate5

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/aa6c1ee46a...152cf38af2

**Comment by brianchandotcom** [comment]
@hhuijser please SF enforce 6bb098064ba04265395f7b1d1a7a64cbbe0e973b

@petershin can you fix the ModulesStructureTest failure?

@jpince fyi, this one is important.

**Comment by jpince** [comment]
@shuyangzhou @brianchandotcom why would you reopen/merge something that's going to cause everyone's pulls to auto-close? The issue should have been resolved _before_ merging to upstream.

**Comment by shuyangzhou** [comment]
Sorry, I did not realize it was caused by this pull, thought it was pre-exist. I will take care of it.

**Comment by jpince** [comment]
@shuyangzhou Peter already fixed it, see https://github.com/brianchandotcom/liferay-portal/pull/71787

**Comment by shuyangzhou** [comment]
oh, ok, great.

**Pull request closed without merging**
