### PR TITLE
LPS-71004

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@sergiogonzalez, see https://github.com/brianchandotcom/liferay-portal/pull/47267/commits/934f492760f0ebb66818b28d41cb20858b1ff3fc
BlogsTestUtil should be in package com.liferay.blogs.test.util instead of com.liferay.blogs.util.test (in order for the Export-Package to follow the Bundle-SymbolicName) but since comment module is using that class as well, we might not be able to change that?

@ealonso, see https://github.com/brianchandotcom/liferay-portal/pull/47267/commits/f40b7d4a70d51fec05e737e8f8f3d85f32201504 and https://github.com/brianchandotcom/liferay-portal/pull/47267/commits/8cb3d97eb354081b299e07663773592a6deec6cd
Export-Package is not matching Bundle-SymbolicName for those two. Can you look into those? Don't think we are supposed to use Export-Package from *-impl module?

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianwulbern** [comment]
@pyoo @jpince, the Calendar failure (SPA, page times out when loading) may be related to the timeouts you mentioned on https://github.com/brianchandotcom/liferay-portal/pull/47264

**Pull request closed without merging**
