### PR TITLE
Lps 58118

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
That node ran out of disk space.

**Comment by brianchandotcom** [comment]
@kiyoshilee please fix disk space usage. Thx.

**Comment by brianchandotcom** [comment]
Hey @shuyangzhou 

After your change, modules/apps/mobile-device-rules/mobile-device-rules-service/src/com/liferay/mobile/device/rules/service/persistence/impl/MDRRuleGroupPersistenceImpl.java and modules/apps/mobile-device-rules/mobile-device-rules-service/src/com/liferay/mobile/device/rules/service/persistence/impl/MDRRuleGroupInstancePersistenceImpl.java no longer regenerate proper SQL.

See 

```
	private static final String _FILTER_SQL_SELECT_MDRRULEGROUPINSTANCE_NO_INLINE_DISTINCT_WHERE_2 =
		") TEMP_TABLE INNER JOIN MDR_MDRRuleGroupInstance ON TEMP_TABLE.ruleGroupInstanceId = MDR_MDRRuleGroupInstance.ruleGroupInstanceId";
```

It shoudln't be namesapced with MDR_* and prior to your change, it wasn't.

Please resend? Thx.

**Comment by shuyangzhou** [comment]
@brianchandotcom if you see the ftl change, I did not touch anything about any field value generation. It was just casting changes.

Those changes must be someone else from previous changes that did not regenerate services.

And currently SB does not really work after gradle changes, you can drop off my last commit, run ant build-services under portal-impl, you will see nothing is regenerating. I did my regeneration by directly updated the ftl file in the SB jar file, as I did not change any java file.

But anyway, until the point that SB is fixed under gradle context, it is going to be very different to fix this irrelevant issue.

**Pull request closed without merging**
