### PR TITLE
LPS-71804 Remove unused code

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by anthony-chu** [comment]
@pavel-savinov the test failures are noted in this [Loop post](https://loop.liferay.com:443/home/-/loop/feed/4897317). The appropriate developer has been contacted regarding the compile error at head.

**Pull request closed without merging**
