### PR TITLE
Revert LPS-119582

### PR DESCRIPTION
**Pull request by vicnate5**
@pavel-savinov Causes LPS-122284 and LPS-122281. These failures should have been caught during QA analysis of the test results pre-merge, I will work with your QA team to make sure they know what to look for next time.

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:reopen

**Comment by pavel-savinov** [comment]
@vicnate5 @brianchandotcom Can we just fix LPS-122284 and LPS-122281 instead of reverting this? We still have time to before 7.4 release and those issues are WebSphere-specific and one test case for data partitioning enabled(BTW, manually it seems to be ok). And LPS-119582 is something that clients expect(no Websphere or DP).

**Comment by vicnate5** [comment]
@pavel-savinov Master is not the primary concern, the concern would be a regression for Websphere users when this is backported and sent in a fix pack.

**Comment by pavel-savinov** [comment]
@vicnate5 Got your point. Ok, let's revert then.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ec72df41cd...e2689f2201

**Pull request closed without merging**
