### PR TITLE
LPS-161025 Add integration test to Categorization layout box

### PR DESCRIPTION
**Pull request by seltong**

### CODE REVIEW

**Comment by seltong** [comment]
ci:reopen

**Comment by seltong** [comment]
The failures [here](https://github.com/liferay-objects/liferay-portal/pull/999) are not related

**Comment by brianchandotcom** [comment]
Merge ObjectLayoutBoxCommentsTypeException and ObjectLayoutBoxCategorizationTypeException into

ObjectLayoutBoxTypeException

Give it 2 different "static class" where one is for comments and the other is for categorization

@seltong @p-albuquerque

**Comment by seltong** [comment]
Resent [here](https://github.com/brianchandotcom/liferay-portal/pull/122634)

**Pull request closed without merging**
