### PR TITLE
Lps 82534

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b4bcf9193d...95ed825807

**Comment by brianchandotcom** [comment]
@shuyangzhou I backported all of this to 7.1.x

For 7.0.x, I only backported the references to the latest ant-bnd. You'll need to the update any other code if necessary.

ant-bnd is shared across all branches.

**Comment by shuyangzhou** [comment]
@brianchandotcom these don't have to be backported, they just small improvements for startup time. But if you want, we can still backport them.

**Pull request closed without merging**
