### PR TITLE
LPS-125034-141471 Edit Breaking Changes

### PR DESCRIPTION
**Pull request by mtokudome**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@mtokudome did @sez11a look at these?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7fd8675d1f...7224f6d5d6

**Comment by mtokudome** [comment]
@brianchandotcom No, do you want these edits to pass through Rich?

**Comment by brianchandotcom** [comment]
@mtokudome initially yes. Can you ask him to review your changes since they are already on master? Thx.

**Pull request closed without merging**
