### PR TITLE
LPS-63846 SF

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
Hey @brianchandotcom, @kenjiheigel, looks like different random test issues here...

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a071db5c8c...592bdb7d02

**Comment by kenjiheigel** [comment]
@jbalsas, 

One test was an upgrade start up issue. I've informed @brianchiu of this.

One of the test groups that failed wasn't able to grab a dependency. This could have been a network issue. We'll keep an eye out for further issues similar to this.

The other issue appears to be the issue described here: [https://issues.liferay.com/browse/LRQA-22776](LRQA-22776). Let me know if you see any other flaky tests and we'll look into them. Sorry for the inconsistencies in the test results. Makes us sad too :( but we're doing what we can to keep them as reliable as possible! 

Thanks Chema!

**Comment by jbalsas** [comment]
Hey @kenjiheigel, no problem at all. You guys are doing an awesome job here. Things are improving every da, and I know they'll just keep getting better :wink: 

Thanks for all the effort!

**Pull request closed without merging**
