### PR TITLE
LPS-142377, LPS-142378, LPS-142417, LPS-142508, LPS-143204, LPS-143222 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-142377
https://issues.liferay.com/browse/LPS-142378
https://issues.liferay.com/browse/LPS-142417
https://issues.liferay.com/browse/LPS-142508
https://issues.liferay.com/browse/LPS-143204
https://issues.liferay.com/browse/LPS-143222

This is only for master.

@lfbesada
@sandrodw3

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure case is unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/6595
✔️ ci:test:stable - 11 out of 11 jobs passed
❌ ci:test:relevant - 24 out of 29 jobs passed in 1 hour 45 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d1e5e83479...92174ae44b

**Comment by brianchandotcom** [comment]
@lfbesada see changes in my origin.

**Pull request closed without merging**
