### PR TITLE
LPS-60400 use a new object that keeps both maps synchronized

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by rotty3000** [comment]
These failures are not related to these changes. It's a JSP compilation failure in another module which has been showing up in other PRs for the past couple of days.

**Comment by rotty3000** [comment]
actually... hold on. I think there is a SF failure hidden in there somewhere...

**Comment by rotty3000** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Yes, I think SF makes a variable final.

**Comment by rotty3000** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7be1510ac1...0d0721cc0d

**Comment by brianchandotcom** [comment]
Nice job @rotty3000 @juliocamarero 

I'm glad the TCK tests helped!

**Pull request closed without merging**
