### PR TITLE
LPS-72750

### PR DESCRIPTION
**Pull request by Ithildir**
cc @brunobasto, @jbalsas, @julien

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@codyhoag fyi

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/34cd6a6753...fc5e621e97

**Pull request closed without merging**
