### PR TITLE
LPS-74544

### PR DESCRIPTION
**Pull request by petershin**
@hhuijser @jpince @JoyceWang08211

### CODE REVIEW

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
ci:reopen

**Comment by jpince** [comment]
pushed upstream per BChan: https://github.com/liferay/liferay-portal/commit/93b6986babfeb458e8118259acacf5ee40138f12

Thanks @petershin!
cc/ @hhuijser

**Comment by jpince** [comment]
ci:close

**Comment by jpince** [comment]
pushed upstream to 7.0.x: https://github.com/liferay/liferay-portal-ee/commit/e3fc1a6c24a5a0973036ebcefa3f16fb7b867d7a <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
