### PR TITLE
LPD-6875-6874 Add default utility pages - remove code unrelated to these tickets (rebased)

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Hi Brian. I am forwarding this manually because I had to tweak some commit messages after the last successful CI testing on  liferay-appsec/liferay-portal/pull/1685

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:reopen

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
@stian-sigvartsen I think this pr is breaking the sf, since in CreateAccountLayoutUtilityPageEntryViewRenderer you are defining _servletContext and it is not used at all.

**Comment by ealonso** [comment]
@stian-sigvartsen Also this change some logic in Utility Pages and it was not reviewed by Echo Team

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/34741c07aa...1d456f1386

**Comment by brianchandotcom** [comment]
@alvarosaugarlr @ealonso @stian-sigvartsen beautiful. No changes from me.

**Pull request closed without merging**
