### PR TITLE
LPS-84076 Get FormBuilderContext and MainRequire from DDMFormAdminDisplayContext

### PR DESCRIPTION
**Pull request by jeyvison**
cc/ @brunobasto 

Hi @brianchandotcom, about *formInstanceId* the only place i found it  being set as attribute was [here](https://github.com/liferay/liferay-portal/blob/7ac91d8dd89e2fd2bae4639bc7bb622a3a4be8fa/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-web/src/main/java/com/liferay/dynamic/data/mapping/form/web/internal/portlet/DDMFormPortlet.java#L212), and it is needed for saving operation when a form is published. It was introduced [here](https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/475/commits/b6e66946de06969e202a84302f76f9ca2c6196fb#diff-6e0fa998faaca5a8de009607364e2abeR215).

If you don't agree with this way, i'd like to treat it in a different PR since it's out of the scope of this one, if you don't mind.

### CODE REVIEW

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ab17f40624...3449ffca20

**Comment by brianchandotcom** [comment]
@jeyvison much much better. Thank you!

**Comment by brianchandotcom** [comment]
@jeyvison @brunobasto not backported.. if you want it backported, please send a pull to support.

**Pull request closed without merging**
