### PR TITLE
7.0.x-LRQA-21003 LRQA-26779 LRQA-26848

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-21003
https://issues.liferay.com/browse/LRQA-26779
https://issues.liferay.com/browse/LRQA-26848

cc-ing @anthony-chu @brianwulbern @koor4356

### CODE REVIEW

**Comment by kenjiheigel** [comment]
Cherry picked from https://github.com/brianchandotcom/liferay-portal/pull/41920

**Comment by brianchandotcom** [comment]
@kenjiheigel please resend. Seems wrong. Too many commits.

**Comment by kenjiheigel** [comment]
Ahh my bad. Will resend.

**Comment by kenjiheigel** [comment]
Resent: https://github.com/brianchandotcom/liferay-portal/pull/41923

**Pull request closed without merging**
