### PR TITLE
LPS-27599 As a web content admin, I can use "Sort by" menu to sort articles

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:/ @juliocamarero, @ealonso

**Comment by jkappler** [comment]
cc:/ @anthony-chu

**Comment by brianchandotcom** [comment]
a lot of errors..

ci:retest

**Comment by anthony-chu** [comment]
@jkappler thanks! looks good. Testray results don't reveal any frontend failures. :+1:

**Comment by brianchandotcom** [comment]
@jkappler @juliocamarero modules-int* CI tests consistently broken (just for this pull). Please resend. Thx.

**Pull request closed without merging**
