### PR TITLE
LPS-98111 Fix tests

### PR DESCRIPTION
**Pull request by wincent**
Update to liferay-npm-scripts v4.8.0, which fixes the test failures caused by the move of `debounce()` to frontend-js-web. Basically, before this version, we weren't able to do cross-project imports in the test suite, and now we can.

In the process of preparing the update I was able to standardize things a little and remove some redundant config as a result.

I updated the workspace globs in the top-level "package.json" because liferay-npm-scripts uses those globs to produce the mapping that allows us to do cross-project imports: we don't actually need or want an arbitrarily deep match there.

Also tested against "master-private" so will prepare a corresponding PR for that.

### CODE REVIEW

**Comment by wincent** [comment]
@andresfulla: liferay-npm-scripts v4.8.0 is now out if you wanted to use it locally until this gets merged. My next task is going to be updating the React testing libraries and I'll CC you on any PRs I make for that one.

@brunobasto: FYI all DDM tests are passing with these changes. I'm going to CC you on a separate ticket that I create for standardizing those package.json "main" entries.

**Comment by brunobasto** [comment]
Thx @wincent, I'll send you the follow up PR soon

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/47be13201c...b9183b9530

**Comment by wincent** [comment]
"master-private" analog of this PR: https://github.com/brianchandotcom/liferay-portal-ee/pull/25447

**Pull request closed without merging**
