### PR TITLE
LPS-86202 Create a utility to make it easier to conditionally add css class names to elements in a JSP

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-86202](https://issues.liferay.com/browse/LPS-86202).

Hey @brianchandotcom, this pull adds the following updates for the CSSClassNames utility:

1. Sorts and distincts the output
2. Forces the consumer pattern for the builder so that the caller never has to manually call `.build()`
3. Moves the class inside the *Util package
4. Adds test cases

/cc @pei-jung @stsquared99 @alee8888

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e53a60201e...e588c80303

**Comment by brianchandotcom** [comment]
@drewbrokke see my changes in upstream? Thx.

**Comment by brianchandotcom** [comment]
Can you move CSSClassNamesTest to a package that matches CSSClassNames Thx

**Comment by drewbrokke** [comment]
Yup, sorry it matched until I moved the util at the last minute

**Comment by drewbrokke** [comment]
@brianchandotcom https://github.com/brianchandotcom/liferay-portal/pull/63960

**Pull request closed without merging**
