### PR TITLE
LPS-126915 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-126915

This is only for master.

@david-gutierrez-mesa
@alexcandidos

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure case is unrelated to changes in PR.
See https://github.com/liferay-echo/liferay-portal/pull/3579
✔️ ci:test:stable - 9 out of 9 jobs passed
❌ ci:test:relevant - 21 out of 26 jobs passed in 2 hours 5 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a95f82655b...a586c3b0d3

**Comment by brianchandotcom** [comment]
@zmmarina please review changes.

**Pull request closed without merging**
