### PR TITLE
LPS-96698 implement missing tests

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
ci:test:relevant (just fixed upstream master), let's see if this is better

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7fe5b442ec...a404a1bf62

**Comment by nhpatt** [comment]
Thx!

**Pull request closed without merging**
