### PR TITLE
LPS-72919

### PR DESCRIPTION
**Pull request by bawachhe**
https://issues.liferay.com/browse/LPS-72919

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@bawachhe this is good, I'm merging it. the SF was from another pull that has since been fixed in upstream. Thx bro.

**Comment by bawachhe** [comment]
:+1: 
Cool :]  Thanks yourself.

**Comment by brianchandotcom** [comment]
@bawachhe 

1.) Avoid "latest.integration" in ivy.xml

2.) deploy-excludes is not consistent, please automate if possible

3.) Fix  Do not use com.liferay.util.ContentUtil in modules, see LPS-64335: ./docroot/init.jsp

4.) Ask Hugo to fix 3.) and how SF is inconsistent depending on whether you run it from portal-impl, Ant, or 

gw :apps:powwow/powwow-portlet:format-source

5.) powwowParticipantData vs. participantJSON

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/93e74f9d74...e22ac163cf

**Pull request closed without merging**
