### PR TITLE
LPS-56414 Remove ddl display bundle

### PR DESCRIPTION
**Pull request by marcellustavares**
Hi Brian, I'm moving back the old functionality and keys of DDL Display on this pull.

I had a different plan for it but due the release date it's safer just to keep the way it was before and deprecate it gracefully.

We'll just add new "user" features under ddl-form-web bundle.

Thanks

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@marcellustavares still has rebase errors.

**Comment by marcellustavares** [comment]
@brianchandotcom, it's conflicting the last commit sometimes b/c of the snapshot.properties that I just removed.

Sent you another on https://github.com/brianchandotcom/liferay-portal/pull/27422

Thanks

**Pull request closed without merging**
