### PR TITLE
[TS] LPS-69762 Unable to include .tpl file in a layout template (regression)

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-69762

Failures on https://github.com/brianchandotcom/liferay-portal/pull/46192 were caused by the missing update to system.packages.extra.mf so I updated it.

Author: @ugurcancetin
Reviewers: @lipusz, @stian-sigvartsen

### CODE REVIEW

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Tests passed on https://github.com/lipusz/liferay-portal/pull/162 should pass here also.

**Comment by brianchandotcom** [comment]
@lipusz 

can you make this a Set

```
	private static final List<String> _allowedLangTypes;

	static {
		_allowedLangTypes = new ArrayList<String>();

		_allowedLangTypes.add(TemplateConstants.LANG_TYPE_CSS);
		_allowedLangTypes.add(TemplateConstants.LANG_TYPE_FTL);
		_allowedLangTypes.add(TemplateConstants.LANG_TYPE_TPL);
		_allowedLangTypes.add(TemplateConstants.LANG_TYPE_VM);
		_allowedLangTypes.add(TemplateConstants.LANG_TYPE_XSL);
	}
```

Faster that way, and also inline it so it is just one line.

Use SetUtil or Arrays

Thx.

**Comment by lipusz** [comment]
Resent: https://github.com/brianchandotcom/liferay-portal/pull/46337

**Pull request closed without merging**
