### PR TITLE
LPS-68540 Adds missing resources importer marker

### PR DESCRIPTION
**Pull request by jbalsas**
Hey Brian, this already uses the `.lfrbuild-missing-resources-importer` mechanism that @ithildir will be adding shortly.

I'm sending it in ahead of time to see if build passes and you guys can merge after Andrea's gradle changes at the end of the day while I 😴 

Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:retes

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
@kenjiheigel, could you take a look at these failures, please?

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by kenjiheigel** [comment]
@jbalsas, failure was unrelated. And the changes were merged. I retriggered the other issue though.

**Pull request closed without merging**
