### PR TITLE
LPS-169166 Add help text

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-169166

@victorg1991

### CODE REVIEW

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/10384

:heavy_check_mark: ci:test:stable - 27 out of 27 jobs passed
:x: ci:test:relevant - 121 out of 127 jobs passed in 1 hour 12 minutes

**Comment by ozysouza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/83b75c14fe...4f2afff64e

**Comment by brianchandotcom** [comment]
@victorg1991 see ff03922c28dc4a75309b77123f4c356ccf7bf42d

**Pull request closed without merging**
