### PR TITLE
Lps 86473

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @shinnlok @preston-crary

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@shuyangzhou can you take a look at the tests that did break? It's been around for a while.. and I wonder if they are related to the AOP changes by @Preston-Crary

Thx

**Comment by Preston-Crary** [comment]
@brianchandotcom should be fixed by https://github.com/brianchandotcom/liferay-portal/pull/64337.  The NoSuchResourceActionException is the first one in the log, it looks like the other ones are caused by that one.

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1a04fb092f...2b90c5962b

**Comment by brianchandotcom** [comment]
@adolfo fyi changes to repository

**Pull request closed without merging**
