### PR TITLE
LPS-75010

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
See also https://github.com/brianchandotcom/liferay-portal-ee/pull/19858

**Comment by ethanbustad** [comment]
@hhuijser regarding "Turn on checks, since all violations have been fixed", is this meant to also include subrepos? https://issues.liferay.com/browse/TR-2587

**Comment by hhuijser** [comment]
@ethanbustad I had also sent pulls to the subrepos with the fixes.
I will look into this. If it's going to complain about everything until everything from the subrepos is merged, then this is not a good approach

**Pull request closed without merging**
