### PR TITLE
LPS-56245 Document Library Service initial pull

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Move stuff that is independent of the portlet (but can be extracted too) to Documents and Media service module.

More pulls coming after this one is merged.

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @marcellustavares

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@kiyoshilee any idea why we are not getting results for this?

**Comment by sergiogonzalez** [comment]
Hey @brianchandotcom I figured out where the test failure might be. I have resent here https://github.com/brianchandotcom/liferay-portal/pull/28715

**Comment by kiyoshilee** [comment]
@sergiogonzalez this pull never gave results because there were too many errors for a comment to post. In the future we're planning on limiting the number of failures that we post. Sorry for the inconvenience.

**Pull request closed without merging**
