### PR TITLE
Lps 73119

### PR DESCRIPTION
**Pull request by shuyangzhou**
Resent of https://github.com/brianchandotcom/liferay-portal/pull/49827 with one more commit https://github.com/shuyangzhou/liferay-portal/commit/01c0cf9b5233dfedc3c205d049a8c3ede8034118

@brianchandotcom this pull will fail SF, due the usage of "default" for portal-test-integration.
Can you publish a release for portal-test-integration? and change the version in those 2 build.gradle.

Thanks!
CC @drewbrokke

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@drewbrokke can you resend this to me in 2 steps? based on changes from @shuyangzhou 

First one should be the portal-test-integration changes. I'll merge that and then publish a new one.

Then you can send me the rest. less risky that way.

Thx

**Comment by drewbrokke** [comment]
Hey @brianchandotcom, just got back :)  Yes, I'll send the pulls today

**Comment by drewbrokke** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
