### PR TITLE
LPS-172417

### PR DESCRIPTION
**Pull request by tinatian**
FYI @shuyangzhou @vicnate5 This pull contains a fix for ComboServletTest

### CODE REVIEW

**Comment by tinatian** [comment]
ci:reopen

**Comment by vicnate5** [comment]
@kyle-miho This is the fix, but we still need to know why CI wasn't reporting this test's status and if it affects other tests.

**Comment by tinatian** [comment]
ci:reopen

**Comment by ChrisKian** [comment]
Hi @vicnate5,
Is your CI question the reason this ticket hasn't yet been merged into master?  If so, is there anything I can do on my end to help out?  Thanks!

CC @kyle-miho, @tinatian, @brianchandotcom, @shuyangzhou

**Comment by vicnate5** [comment]
This can be merged, the CI question is unrelated to the fix.

**Comment by brianchandotcom** [comment]
@ChrisKian can you resend:

1.)

```
		setUpPortalServletContext();

		setUpComboServlet();

		setUpPortalPortlet();

		setUpPluginServletContext();

		setUpTestPortlet();
```

Looks like it was sorted before, but not anymore. And it's not obvious why.

2.) Rename 

_testComboServletService

to

_testService to match public void testService*

Thx

**Comment by ChrisKian** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/129780

**Pull request closed without merging**
