### PR TITLE
LPS-67552 Remove "package" property, it's equal to "groupId" by default

### PR DESCRIPTION
**Pull request by Ithildir**
Hi!

Can you please publish all the `project-templates-*`, and also `project-templates`?

Thank you!

cc @david-truong, @gamerson, @lawrence-lee

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@Ithildir I'll do it next week? Give you guys a few days to think about it :)

**Comment by Ithildir** [comment]
Sounds good to me, but I don't know if @david-truong, @gamerson and @lawrence-lee need them for NAS :blush:

**Comment by brianchandotcom** [comment]
Ok.. I'll publish right now then!

**Comment by Ithildir** [comment]
Thank you!! :blush:

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
