### PR TITLE
LPS-71271 Use new linkData attributes in jspc

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @hhuijser

**Comment by sergiogonzalez** [comment]
cc/ @yuhai

**Comment by jpince** [comment]
@sergiogonzalez compile error
`     [exec] Caused by: org.apache.jasper.JasperException: file:/opt/dev/projects/github/liferay-portal/modules/apps/knowledge-base/knowledge-base-web/build/unzipped-jar/META-INF/resources/admin/common/article_attachments.jsp(47,5) PWC6131: Attribute dataLink invalid for tag horizontal-card according to TLD`
Maybe because these two lines have `dataLink` instead of `linkData`?
https://github.com/brianchandotcom/liferay-portal/pull/47734/files#diff-861d4374964e5c0772c5b4acf8249fdfR48
https://github.com/brianchandotcom/liferay-portal/pull/47734/files#diff-42ef9cc2d9b71161a9005d089534a844R389

**Comment by jpince** [comment]
ci:close

**Pull request closed without merging**
