### PR TITLE
LPS-49545

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@brianchandotcom those sass failures disappears with rebase.  See https://github.com/mhan810/liferay-portal/pull/1037#issuecomment-181654868

**Comment by brianchandotcom** [comment]
Yey, it's green :)

**Comment by brianchandotcom** [comment]
Published.

**Comment by mhan810** [comment]
:) let me know if there are issues, this one preventing us from moving portal-ldap

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e8de190705...f3a2aa4c47

**Comment by brianchandotcom** [comment]
@Ithildir please double check the Gradle changes for this ticket. Thx!

**Comment by Ithildir** [comment]
Done! https://github.com/liferay/liferay-portal/commit/285d19365d24dc53f28a8e0e107ceb281f247136

**Pull request closed without merging**
