### PR TITLE
LPS-66141 Update portal-kernel to default

### PR DESCRIPTION
**Pull request by matethurzo**
cc @danielkocsis, @mhan810

@migue this will probably solve at least partially LPS-65813

### CODE REVIEW

**Comment by kenjiheigel** [comment]
@brianchandotcom, there's no functional test failures. This pull is good to merge.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1c13e97abc...5c010b92cd

**Comment by brianchandotcom** [comment]
@matethurzo I merged this in without the change to c00058c454736a05f55298d3e94972f866eef848

I dont' see why it's needed?

@kenjiheigel can you verify that upstream still works since I only did a partial pull? Thx.

**Comment by kenjiheigel** [comment]
@brianchandotcom, I'll build a bundle at head right now and make sure it's good. Will keep an eye out for tests as well.

**Comment by kenjiheigel** [comment]
Liferay seems to start up fine as far as I can tell. Will continue to monitor the tests though.

**Pull request closed without merging**
