### PR TITLE
LPS-52265

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
Asking IT for CI server accessing, will do an online debugging if it still fails.

**Comment by brianchandotcom** [comment]
ci:retest should work now since LPS-52666

**Comment by shuyangzhou** [comment]
@brianchandotcom this is actually caused by a real bug, I talked to @mhan810 already. You can close this for now, mike will resend with fix.

**Comment by brianchandotcom** [comment]
Please resend, Shuyang made some changes to output more errors, see https://github.com/brianchandotcom/liferay-portal/pull/23249

Thx

**Pull request closed without merging**
