### PR TITLE
[TS] LPS-69480

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-69480

Hi Brian,

I'm resending with the [requested](https://github.com/brianchandotcom/liferay-portal/pull/45420#issuecomment-266583882) changes. I hope it looks good now.

Thanks,
Tibor

/cc @amadeafejes, @Preston-Crary

### CODE REVIEW

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
Failure is not related to this pull. SF error

```
org.junit.ComparisonFailure: ../../../modules/sdk/gradle-plugins-node/CHANGELOG.markdown expected:<...com/browse/LPS-69677[]> but was:<...com/browse/LPS-69677[
```

**Comment by brianchandotcom** [comment]
@lipusz I don't understand the order of

```
		ResourceTypePermissionLocalServiceUtil.deleteResourceTypePermission(
			_resourceTypePermission);

		ResourcePermissionLocalServiceUtil.deleteResourcePermission(
			_resourcePermission);

		UserLocalServiceUtil.deleteUser(_userGroupUser);

		GroupLocalServiceUtil.deleteGroup(_userGroupGroup);

		UserGroupLocalServiceUtil.deleteUserGroup(_userGroup);

		OrganizationLocalServiceUtil.deleteOrganization(_organization);

		GroupLocalServiceUtil.deleteGroup(_group);
```

What sorting is this? Please sort in a more straight forward way and resend. Thanks

**Comment by lipusz** [comment]
See: https://github.com/brianchandotcom/liferay-portal/pull/45620

**Pull request closed without merging**
