### PR TITLE
LPS-65111 SF

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @adolfopa

**Comment by sergiogonzalez** [comment]
@migue I resent it here because https://github.com/brianchandotcom/liferay-portal/pull/39065 no longer rebases

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0e7406629f...6683e838f8

**Comment by brianchandotcom** [comment]
@sergiogonzalez I merged this in.. it took so long to do because there was actually a breaking change in baseline that CI didn't catch, so I had to fix it manually.

**Comment by brianchandotcom** [comment]
@migue @robertoDiaz please see my changes to UpgradeModules in upstream to fix the breaking change that CI didn't catch.

**Pull request closed without merging**
