### PR TITLE
LPS-92198 Added method to load mapped field label

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by jpince** [comment]
ci:reopen

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:norebase

**Comment by brianchiu** [comment]
ci:stop

**Comment by brianchiu** [comment]
ci:test:relevant:norebase

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/83e74c23ce...c2df465d1f

**Pull request closed without merging**
