### PR TITLE
LPS-55591 - Users Admin portlet to OSGi module

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-55591](https://issues.liferay.com/browse/LPS-55591).<br><br>/cc @pei-jung, /cc @jorgeferrer

### CODE REVIEW

**Comment by juliocamarero** [comment]
Hey @drewbrokke 

I just realized that I added today a reference to the portlet MY_ACCOUNT in ThemeDisplay (method getURLMyAccount). It can be easily replaced by a call to a PortletProvider (see method getURLPageSettings). Can you please do update that?
The smoke tests should fail for this reason.... 
  thank you!

**Comment by brianchandotcom** [comment]
@drewbrokke @pei-jung please resend based on suggestions from @juliocamarero 

Thx

**Comment by pei-jung** [comment]
Hi @brianchandotcom @juliocamarero,

The MY_ACCOUNT portlet key is still in core so there's no effect to the reference added in ThemeDisplay. We didn't create a separate portlet key class for MyAccount because the mapping between PortletProvider and classname (for MyAccount, it's com.liferay.portal.model.User) must be 1 to 1, but the classname has already been used for the UsersAdmin portlet.

I think the failed tests are caused by something else. We made sure all the tests passed before sending it to Brian.

**Comment by juliocamarero** [comment]
Hey @pei-jung 

we have had this same issue in other situations, and we have created some "fake classnames" for this situations called ApplicationTypes.

I just sent a pull to Brian creating one for my account: https://github.com/brianchandotcom/liferay-portal/pull/29072

We should replace all the references to the portlet key by a portlet provider using this classname.

Let me know if that works.

Thank you!!

**Comment by pei-jung** [comment]
Hey @juliocamarero,

It works. I've made the changes and submitted a pull to Brian https://github.com/brianchandotcom/liferay-portal/pull/29112. Thanks!

**Pull request closed without merging**
