### PR TITLE
LPS-108562 Update the flag of Slovakia

### PR DESCRIPTION
**Pull request by antonio-ortega**
/cc @rolandpakai

### CODE REVIEW

**Comment by antonio-ortega** [comment]
brianchandotcom#86316

**Comment by rolandpakai** [comment]
Hi @antonio-ortega 

could you please let me known why this PR is closed?
I can not see it is merged to master.

Thanks, Roland

**Comment by antonio-ortega** [comment]
Closed by mistake. Sorry.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0902ba4d9a...bec446f4ba

**Pull request closed without merging**
