### PR TITLE
Lps 73853

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/25d9114618...2816a305fe

**Comment by brianchandotcom** [comment]
@Preston-Crary you need to deprecate the old key

63c380a0fedfc06e9b7fc5b9b996bca8eabf7356

I also moved the package to a better spot

see 

2816a305fe1c519e7097c2700342670763d7b3b6

Thx

**Comment by Preston-Crary** [comment]
:+1:

**Pull request closed without merging**
