### PR TITLE
LPS-57379 Renaming Settings API to Configuration API

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
@brianchandotcom, I imagined that that would be the case, since there are still people working on converting and/or updating the configuration of their modules.

I'll continue to rebase this pull daily and solving conflicts if I find some, so it's always up to date.

Thx

**Comment by jkappler** [comment]
CC:/ @JorgeFerrer

**Comment by brianchandotcom** [comment]
@jkappler I think there's still a confusion here based on the naming.

Previously, it was consistently *Settings.

Now, there is *Configuration and *ModuleConfiguration. Even though both are exactly the same thing.

We should either make everything *Configuration or make everything *ModuleConfiguration.

For example, the relationship between BlogsPortletInstanceConfiguration and ModuleConfigurationFactory is not immediately obvious.

Thx

**Comment by brianchandotcom** [comment]
@jkappler @JorgeFerrer we don't need to rename everything to ModuleConfiguration.

Why can't we just keep everything as *Configuration, and for the new classes, call it ConfigurationFactory?

I know it may be confused with our other Configuration class, but I find that less confusing than the inconsistency with BlogsPortletInstanceConfiguration and ModuleConfigurationFactory.

Thx.

**Pull request closed without merging**
