### PR TITLE
LPS-159751 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-159751

This is only for master.

@jkappler

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure cases are unrelated to changes.
See https://github.com/liferay-echo/liferay-portal/pull/9266
✔️ ci:test:stable - 27 out of 27 jobs passed
❌ ci:test:relevant - 173 out of 186 jobs passed in 3 hours 36 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8b5d289d05...05e2b0a9f9

**Comment by brianchandotcom** [comment]
@jkappler @Tim-Cao can we add a functional or integration test for this? Thx.

**Pull request closed without merging**
