### PR TITLE
LPS-73290

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by adolfopa** [comment]
ci:retest

**Comment by adolfopa** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3487d919e2...e78cceb250

**Comment by brianchandotcom** [comment]
@adolfopa see my changes in upstream? Thx.

**Pull request closed without merging**
