### PR TITLE
LPS-59561 Update cache

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
Brian... I was told to update the cache is the pull to make it work in the CI...

**Comment by brianchandotcom** [comment]
@csierra NPE in tests.

**Comment by csierra** [comment]
does it say "app server timeout"?

**Comment by csierra** [comment]
Ok... I see the error now... looking at it

**Comment by csierra** [comment]
please see https://github.com/brianchandotcom/liferay-portal/pull/32849

**Pull request closed without merging**
