### PR TITLE
master-sc-502

### PR DESCRIPTION
**Pull request by sharonchoi**
https://issues.liferay.com/browse/LRQA-22574

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@sharonchoi see Smoke failure?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a89bda93cf...dabc8983e9

**Comment by sharonchoi** [comment]
@brianchandotcom ok will do.

**Comment by sharonchoi** [comment]
CC @pyoo47 @michaelhashimoto @lesliewong92

The console output looks like the Wildfly bundle was deployed then undeployed, causing the Smoke test to fail.
` [exec] [0m[0m20:01:34,505 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-6) WFLYSRV0028: Stopped deployment ROOT.war (runtime-name: ROOT.war) in 72378ms
     [exec] [0m[0m20:01:34,686 INFO  [org.jboss.as.server] (DeploymentScanner-threads - 2) WFLYSRV0009: Undeployed "ROOT.war" (runtime-name: "ROOT.war")
     [exec] [0m[0m20:01:34,688 INFO  [org.jboss.as.server.deployment.scanner] (DeploymentScanner-threads - 1) WFLYDS0004: Found ROOT.war in deployment directory. To trigger deployment create a file called ROOT.war.dodeploy`

**Comment by michaelhashimoto** [comment]
@brianchandotcom @sharonchoi @brianchiu

We made a ticket to investigate this random error here:
https://issues.liferay.com/browse/LRQA-22624

**Pull request closed without merging**
