### PR TITLE
LRAC-5357

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
@ctang3 @rachaelkoestartyo, added suppressions, because SourceFormatter is complaining about unprocessed exceptions...

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3d18e1db11...2c70892b77

**Comment by brianchandotcom** [comment]
@@rachaelkoestartyo please fix.

**Pull request closed without merging**
