### PR TITLE
LPS-63587 Increase patch level

### PR DESCRIPTION
**Pull request by adolfopa**
@brianchandotcom It may be difficult to see why these changes are necessary. I've tried to explain it in the commit messages.

Thanks!

/cc @sergiogonzalez

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 hung build?

**Comment by pyoo47** [comment]
This looks like another case where the portal is throwing lots of exceptions and created a log file that was too big for the GitHubMessageUtil to handle. Kenji is investigating to try to figure out the cause of these sporadic incidents.

ci:retest

**Comment by kenjiheigel** [comment]
Failures are unrelated to this pull. Failing functional tests have been disabled in liferay@897964d^...03e5cb7.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fabf09bb30...af1b004624

**Comment by brianchandotcom** [comment]
@adolfopa please see my changes in upstream. Thx.

**Pull request closed without merging**
