### PR TITLE
LPS-82444 Update methods accordingly

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:close

**Pull request closed without merging**
