### PR TITLE
Lps 73908

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by tinatian** [comment]
@marianoalvarosaiz 
1. BaseClusterMasterTokenTransitionListener is not provided to serve scheduler, it is a framework support and you can add other usages base on this. It does not make sense to change the logging level because one of its usage needs, right? For the usage of scheduler, if you think it is really important, you should add more logging into scheduler itself, not to modify the framework support.
2. It is possible that no memory clustered jobs running in your cluster, right? If that's the case, your logging is kind of misunderstood by people. If there is something wrong, and a system admin is trying to find the problem, logging the count to job should also help.
3. if initMemoryClusteredJobs method fail, there should be exception thrown, and since we have modify the log4j of BaseClusterMasterTokenTransitionListener, there will be warning info.

Tina

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6dc214a1dc...2ba6cdbc9e

**Comment by almonwork** [comment]
Hi @tinatian 

Thank you very much for your explanation. However, there a few things I think that should not be just assumed.

1. It doesn't matter if it is a library, a framework or a single class. The framework does a job others depend on, and as such, it has to be done diligently. If it is an error, it is an error. Why should we hide that under the framework concept?

2. We have a customer claiming that a 0 jobs installation does not work properly. Do you have any example of an installation working properly with 0 jobs? How did you manage a growing thrash?

If we just print a number, how could anyone know if that given number is right or wrong? Have we documented how many jobs does Liferay create by default? A number is no more that data. To transform it into information, there has to be more context.

3. And what if BaseClusterMasterTokenTransitionListener changes? Aren't we coupling BaseClusterMasterTokenTransitionListener and ClusterSchedulerEngine in a very obscure way? Besides that, BaseClusterMasterTokenTransitionListener could log the stack trace, but what about other information about the jobs themselves? Again, we are just printing data, with no context, where it is quite hard to extract information.

Regards
  Alberto

**Comment by tinatian** [comment]
Hi @almonwork,
1. How do you know it is an error? From the framework point of view, it just allows you to throw exceptions. Not every exception means an error, right? 
2. I just mean it is possible that there is 0 job, even if we do not support it by default, but in theory it can be done by unregistering all the jobs programmingly, we can not assume what customer would do, thus we can not assume 0 job is a wrong status.
Logging is just a tool to help you gather info, it is you to do the judgement if this is a right or wrong status. In some cases, logging can also do some judgement instead of you, but this one is not that kind of case. Like you said, you don't know how many jobs in current bundle, then you won't know if the number print out is right or wrong. So it is your job to figure out how many jobs running, then you would know if the number print out is right or wrong. It is hard to make this kind of decision when we do logging. What we print out should always be right, if it is not sure, it is better we leave that job to people.
3. If you think using BaseClusterMasterTokenTransitionListener cause you problem, you can implments the interface directly, it will give you all the control. We are using BaseClusterMasterTokenTransitionListener as a simple way to help you, it is not a requirement to use it.

Tina.

**Comment by almonwork** [comment]
Hi @tinatian 

1. If it is an exception, it is something unexpected, so I would say it is closer to an error than something else.
2. Even if 0 jobs is theoretically possible, it is a highly unlikely situation. In fact, it was the clue that lead us to guess what was happening. So, I agree we can not signal it as an error, but now that we know it could (and it most likely be) a problem, I would add a WARN log message stating that 0 is a situation that requires attention. This simple trace could save weeks of debugging and diagnosis, and avoid hard to manage escalation. It's a win-win.
3. While I agree that something can be reimplemented to be improved, we can not expect every customer to develop their own customizations at this level. Liferay is valued for its extensibility, but it is also valued for the many things you don't have to develop because they are there out of the box. If you log the trace in the finally block, besides the stack trace, we will get other useful information for diagnosis purposes that, again, can save weeks and hard escalations.

Could you please reconsider adding some extra information for the sake of better supportability?

Thanks

**Comment by tinatian** [comment]
Hi @almonwork,
1. From the framework point of view, you can not assume an exception is closer to an error or not since you are missing the context. It is the user of the framework, like Scheduler, knows if it is closer to an error or not. So I would like to not touch framework part, cause it is used by others and customers might have its own usages and I do not want to take a risk to break their code.
2. For 0 job problem, if you really think it can save you time while diagnosing, I can accept to add it back. Please send me a pull about this.
3. In my last answer, I say you can implement the interface directly, I mean for scheduler usage, if you really think it should be logged as an error instead of an warning, you can achieve it by implementing the interface directly, this way you won't affect other usages of framework. Please send me a pull if you really think it is needed.

Thanks.
Tina.

**Comment by almonwork** [comment]
Hi @tinatian 

Thank you for your comments. We will send you a PR to add some more logging information.

Regards
  Alberto

**Pull request closed without merging**
