### PR TITLE
LPS-72042 Semver asset-published-web

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by Ithildir** [comment]
Hi @brianchandotcom,

I still receive messages about the semver failure for `asset-publisher-web` on `7.0.x`. Is there anything else I should do?

**Pull request closed without merging**
