### PR TITLE
LPS-109843 add dependencies

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@brianchandotcom I've applied for data layout first. If everything looks good to you then will do it for the others. Don't know why some files are conflicting, I did a rebase. Thanks!

@ealonso @brunofarache @jeyvison

**Comment by brianchandotcom** [comment]
@leoadb since it's DE*

DEDataLayout should follow the service builder naming conventions.

createDate vs. dateCreated etc.

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/brianchandotcom/liferay-portal/pull/85889

**Pull request closed without merging**
