### PR TITLE
LPS-56341 New modules for Product Menu and move common API to application-list module

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@juliocamarero We weren't able to stabilize the build until very late in the day, so I didn't get a chance to look at this til now. Will review it tomorrow. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/38c59cef0d...fff41d998e

**Comment by brianchandotcom** [comment]
@ealonso I merged it in:

1.) Can you review my changes? I renamed productivity-center-ui.tld and a few other things.

2.) How come ProductivityCenterWebKeys is in com.liferay.application.list.taglib.constants? Was that on purpose? I didn't touch that one because I wasn't sure.

**Comment by ealonso** [comment]
Hi Brian,

I've sent a new pull with the changes see https://github.com/brianchandotcom/liferay-portal/pull/27693

**Pull request closed without merging**
