### PR TITLE
LPS-90821 Ignoring due to known issue, will be fixed in LPS-92308

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:reopen

**Comment by matethurzo** [comment]
@brianchandotcom @jpince the format source error is unrelated

**Comment by jpince** [comment]
ci:close @matethurzo @luizfmarins please see https://github.com/brianchandotcom/liferay-portal/pull/69865 for SF fixes
1. Newline character at the end of the file https://github.com/brianchandotcom/liferay-portal/pull/69842/files#diff-6aafb0a90f396424efdcc8045c11ab62L8
2. This line is longer than 80 characters https://github.com/brianchandotcom/liferay-portal/pull/69842/files#diff-721e09559b11a63fd1b43b675206af71R45
3. SF is asking for this line to be broken up https://github.com/brianchandotcom/liferay-portal/pull/69842/files#diff-721e09559b11a63fd1b43b675206af71R127

SF automatically fixed the exceptions. Here's how to run it:
(root) $ ant setup-sdk
(root/portal-impl) $ ant format-source-current-branch

**Comment by matethurzo** [comment]
@jpince I know how to run SF :)

What I was implying though is that those SF errors have nothing to do with the code I've sent or we have done.
It seems like that somehow SF errors have been merged into master previously.

But sure we'll resend

**Comment by jpince** [comment]
@matethurzo I already resent the pull with SF fixes here https://github.com/brianchandotcom/liferay-portal/pull/69865

The instructions for SF were for @luizfmarins, if he's interested. I'm not sure if we request that devs outside of Liferay run SF, so that's why I resent it myself rather than sending it back to you/him. I did not encounter these errors when running SF at head.

**Pull request closed without merging**
