### PR TITLE
LPS-159876 Use CDATA when serializing url title map

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:reopen

**Comment by adolfopa** [comment]
See original pr https://github.com/liferay-lima/liferay-portal/pull/3395

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/960337ac3f...599e25b64d

**Comment by brianchandotcom** [comment]
@adolfopa I think I'm missing something? I don't see 

```
				if (cdata) {
					xmlStreamWriter.writeCData(
						XMLUtil.stripInvalidChars(entry.getValue()));
				}
```

used anywhere in this PR?

**Comment by brianchandotcom** [comment]
not merging, can you resend? @adolfopa see my comment above.

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122163

**Pull request closed without merging**
