### PR TITLE
Lps 178239

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@daiazius @tinatian these vars are wrong

```
	@Reference(
		target = "(model.class.name=com.liferay.dynamic.data.mapping.model.DDMTemplate)"
	)
	private ExportImportContentProcessor<String>
		_ddmTemplateExportImportContentProcessor;
```

Please resend.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cbe2de5c9f...71c26c0a43

**Comment by tinatian** [comment]
@brianchandotcom We want to keep the name to make it clear that this is a specific type of ExportImportContentProcessor filtered by the target.

Tina.

**Comment by tinatian** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
I merged this because @tinatian is right and I didn't see the target where it was a specifying a specific version. I'm fine with this pattern.

**Pull request closed without merging**
