### PR TITLE
LPS-123218 SAML Persistence Changes (follow up 2)

### PR DESCRIPTION
**Pull request by martamedio**
See: https://github.com/brianchandotcom/liferay-portal/pull/102020#issuecomment-844164581

### CODE REVIEW

**Comment by martamedio** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@martamedio @stian-sigvartsen reviewing it now

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b9f4570730...7a4fe4e5d2

**Comment by brianchandotcom** [comment]
@martamedio @stian-sigvartsen I merged this with changes in my origin. Please review. Also, @achaparro will reach out to you about the INDEX, he says it's not needed.

**Pull request closed without merging**
