### PR TITLE
LPS-70421 Javadoc

### PR DESCRIPTION
**Pull request by marcellustavares**
cc @leoadb @rafaprax

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@pyoo47 @michaelhashimoto can you guys look into modules/apps/opensocial/opensocial-portlet

I don't see it locally?

**Comment by brianchandotcom** [comment]
Merged.

**Comment by brianchandotcom** [comment]
@pyoo47 @michaelhashimoto nvm, I get the error message. It was just misleading.

@ealonso your change in f83c5162bbf7e46719b54252d32266fd52635e82 required a regen in 5878508602f91b2245209ef217073c8633709b82

**Pull request closed without merging**
