### PR TITLE
LPS-64196 buildLang

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:retest

**Comment by sharonchoi** [comment]
@alee8888 @evannagayama 

It looks like there are some search and site tests failures, would you guys mind taking a look at these when you get a chance?

For these tests, it looks like the iframe isn't exiting after clicking "Done", in this macro Site#addMemberCP.

**Comment by xbrianlee** [comment]
@alee8888 @evannagayama

@sharonchoi - Thanks Sharon! I believe Eudaldo's commit (bcd693e79fc95ec5ea191dc44f31c2d4d61ade39) will fix the test failures.

**Comment by evannagayama** [comment]
@sharonchoi looks like Eudaldo fixed the poshi tests on the last commit https://github.com/ealonso/liferay-portal/commit/bcd693e79fc95ec5ea191dc44f31c2d4d61ade39.

**Comment by brianchandotcom** [comment]
@ealonso can you resend..

This ordering seemed "off"

```
String className = ParamUtil.getString(request, "className");
String displayStyle = ParamUtil.getString(request, "displayStyle", "list");
String eventName = ParamUtil.getString(request, "eventName", renderResponse.getNamespace() + "selectSiteRole");

long groupId = ParamUtil.getLong(request, "groupId");

int roleType = ParamUtil.getInteger(request, "roleType", RoleConstants.TYPE_SITE);

```

and

```
portletURL.setParameter("className", className);
portletURL.setParameter("displayStyle", displayStyle);
portletURL.setParameter("eventName", eventName);
portletURL.setParameter("groupId", String.valueOf(groupId));
portletURL.setParameter("roleType", String.valueOf(roleType));

```

I also couldn't see how "className" is actually used? Please resend with an explanation.

Thx.

**Pull request closed without merging**
