### PR TITLE
Lps 156684

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7d2c4171e3...5cb5ff8675

**Comment by brianchandotcom** [comment]
@gleicelisbino see my renames in 30086e4cc97a0f254f8a764bc22795f069b27dae c0738ab69f46e997a601b3d4102ab67110b4fca2 and 07cf266f9bc99867ba35cfe1a02985595f3611cd

@shuyangzhou fyi thanks!

**Comment by gleicelisbino** [comment]
Thank you so much @brianchandotcom

**Pull request closed without merging**
