### PR TITLE
LPS-62553 Power user has 3 unidentified 'Add to Page' permissions defined

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-62553](https://issues.liferay.com/browse/LPS-62553).<br><br>/cc @juliocamarero @epgarcia @pei-jung @jorgeferrer

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/14e9b5efe3...807ea53a0b

**Comment by brianchandotcom** [comment]
@drewbrokke this is just a short term fix. Now it's not localizable.

Add it to Language.properties javax.portlet._......ControlMenuPortlet etc adn define the title. Then we're good for the long haul I think.

**Comment by juliocamarero** [comment]
Thanks for mentioning me @drewbrokke!! :+1: 

I like your change, we missed that. I think that making them localizable is not necessary since these portlets shouldn't show up anywhere.

I am going to send you a pull hiding them from the permissions UI too. If you see them somewhere else, let me know.

thanks a lot!!

**Comment by juliocamarero** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/35180

**Pull request closed without merging**
