### PR TITLE
LPS-64246 WeakHashMap is HashMap, it is not thread safe. To avoid dep…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…endency on kernel, to the manual WeakReference handling.

@csierra @michaelhashimoto @Ithildir @migue @rotty3000 @mhan810

### CODE REVIEW

**Comment by rotty3000** [comment]
I appreciate the effort to not couple. Thank you!

**Comment by shuyangzhou** [comment]
Yeah, ideally I want to pull out those memory/concurrent code out of kernel, as they only have jdk dependencies. Then registry can depend on that to avoid the "duplicated" code. But that can wait, this should be good enough for now.

**Comment by csierra** [comment]
hey @shuyangzhou... isn't this turning `addServiceTracker` into a potentially `O(n^k)` operation? Why is this better than simply synchronizing the map since the framework is **already** a global synchronization point?

**Comment by shuyangzhou** [comment]
The _serviceTrackerReferences is appending, it is O(1), the referenceQueue is polling, it is O(n), _serviceTrackerReferences removing is O(n'). The total clean up is O(n x n'), but that n is the number that people throw away ServiceTracker as garbage, which does not happen often, it is next to 0, so the O(n x n') is ignorable.

It is slower than the hash based removing, that's why I started with ConcurrentReferenceKeyHashMap. But that is not an option now, so this is the 2nd best choice we have.

**Comment by csierra** [comment]
It would be the total number of ServiceTracker registered to the number of thrown aways. But that's exactly my point... the operation does not happen often and it is already synchronized by the framework so why bother?

**Comment by shuyangzhou** [comment]
"the framework is already a global synchronization point? " not sure which piece of code you are referring? If there is any, we will have to deal with that too. We should at least try to remove every global synchronized point.

**Comment by csierra** [comment]
every time a ServiceTracker is open it synchronizes on the OSGi framework because it gets all the existing references which is a synchronized operation.

**Comment by shuyangzhou** [comment]
No, that's not the point.
"It would be the total number of ServiceTracker registered to the number of thrown aways." in the end, yes, on closing the registry.

But a synched map will also sync on creating registry. This queue solution will only have to deal with it on shutdown, which we won't care performance that much, at least not at the same level comparing to runtime.

**Comment by shuyangzhou** [comment]
"every time a ServiceTracker is open it synchronizes on the OSGi framework because it gets all the existing references which is a synchronized operation."
It is synching on itself, not the framework. There is not contention there.

**Comment by csierra** [comment]
no... it is syncing on the framework IIRC

I believe here org/eclipse/osgi/internal/serviceregistry/ServiceRegistry.java:993

**Comment by shuyangzhou** [comment]
That's very bad...

But see it this way, the syncing at least is only on creating, not closing, we at least have some paths saved.

And we actually defer the syncing to open time rather than creating time. If 2 threads are creating at the same time, there is still chances they open at slightly different time, at least we get another chance to ease the problem.

**Comment by csierra** [comment]
if you are OK I am OK... and the effort is already done and if the complexity is fine I am out of arguments here. 
I am just sorry that this happened because I forgot to synch the map in the first place and you had to dedicate time to this

**Comment by rotty3000** [comment]
Hey guys I think the issue that performance team has seen is because of
usages of the registry like so:

https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/events/EventsProcessorUtil.java#L104-L105

Normally the service registry (or "creation" of trackers) are not directly
in the call path of the business logic of the portal. However as you see
above that is directly in the call path, and while it's true that the
trackers are cached the initial creation might be noticeable and might be
one of the things noticed in performance testing.

@csierra, for that specific case the possible "keys" are limited by the
known LifecycleEvent integration points as a fixed number, Could you
pre-build those trackers to remove their lazy creation during request
processing?

**Comment by rotty3000** [comment]
Furthermore, we might only need a single MultiValue service tracker map on
they `key` property.

On Tue, Mar 15, 2016 at 2:00 PM, Raymond Auge <raymond.auge@liferay.com>
wrote:

> Hey guys I think the issue that performance team has seen is because of
> usages of the registry like so:
>
>
> https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/events/EventsProcessorUtil.java#L104-L105
>
> Normally the service registry (or "creation" of trackers) are not directly
> in the call path of the business logic of the portal. However as you see
> above that is directly in the call path, and while it's true that the
> trackers are cached the initial creation might be noticeable and might be
> one of the things noticed in performance testing.
>
> @csierra, for that specific case the possible "keys" are limited by the
> known LifecycleEvent integration points as a fixed number, Could you
> pre-build those trackers to remove their lazy creation during request
> processing?
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/30ff4928d4...f3b52b74f7

**Comment by brianchandotcom** [comment]
Thx @csierra @shuyangzhou @rotty3000 for working together to get this thing in..

**Comment by csierra** [comment]
@rotty3000 sure... I will have a look at it

@brianchandotcom thx to you guys!

**Comment by michaelhashimoto** [comment]
Thanks everyone! This should also make the pull request tester a little bit more predictable.

**Pull request closed without merging**
