### PR TITLE
LPS-75655 Add workflow definition link update handler for layout revisions to avoid stuck layout revisions in the workflow

### PR DESCRIPTION
**Pull request by matethurzo**
71x:https://github.com/brianchandotcom/liferay-portal-ee/pull/20875

### CODE REVIEW

**Comment by matethurzo** [comment]
the failures are not related

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a5370582cd...50db174e02

**Comment by brianchandotcom** [comment]
Hey @matethurzo we really need a test for this because your backport exposed a very very very dangerous bug.

See 240c0d8af545c435d68af64e40fb9b31dedf3b6f and 819584e8e74483938f91b8b815f612ac8a6d5244

**Comment by matethurzo** [comment]
thanks @brianchandotcom it's true, i didn't notice it. i'll check how can i write a test for it

**Pull request closed without merging**
