### PR TITLE
LPS-86006 Mouse over fragment to show header

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchiu** [comment]
I'll check the failures.

**Comment by brianchiu** [comment]
ci:close

**Comment by brianchiu** [comment]
@ealonso 

The display pages test failure is a bug =(. Web content friendly URLs lead to an "internal server error" page.

There is an error in the console:
```2018-10-16 16:45:38.551 ERROR [http-nio-8080-exec-2][status_jsp:?] java.lang.NullPointerException```

**Comment by jpince** [comment]
@brianchiu thanks for catching this

**Comment by brianchiu** [comment]
@ealonso There are some changes that, once bchan merges, will conflict with the test fixes I made in this pull (see: https://github.com/brianchandotcom/liferay-portal/pull/64270).

So, I've sent you a new pull that has those changes here: https://github.com/ealonso/liferay-portal/pull/1965

**Pull request closed without merging**
