### PR TITLE
LPS-102947 Site admins cannot search for global structures when creating a web content

### PR DESCRIPTION
**Pull request by BryanEngler**
**ci:test:search - 47 out of 51 jobs passed** https://github.com/BryanEngler/liferay-portal/pull/448#issuecomment-563505514
✅ The only failures unique to this pull are not caused by this pr, confirmed by @joshchong

Author(s): @rodrigopaulino
Reviewer(s): @BryanEngler

---
*[Regression Bug] Site admins cannot search for global structures when creating a web content*
https://issues.liferay.com/browse/LPS-102947

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/00f341ee97...a0b12dba4c

**Comment by brianchandotcom** [comment]
@rodrigopaulino @leoadb @BryanEngler see f1a6211cb1dbc64c1e37149ade360f2e356b3e06 and a0b12dba4c6d6a5f9a9759d09ab09faade7d372c

**Comment by brianchandotcom** [comment]
@BryanEngler @rodrigopaulino @leoadb I had to revert this as it was causing stable not to merge.

**Comment by xbrianlee** [comment]
Reopened LPS-102947. Re-running stable job tests now.

**Comment by xbrianlee** [comment]
Resent in https://github.com/brianchandotcom/liferay-portal/pull/81937

**Pull request closed without merging**
