### PR TITLE
LPS-76482 SF

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:reopen

**Comment by jbalsas** [comment]
Hey @hhuijser, any idea what's wrong here? 🤔

**Comment by hhuijser** [comment]
@jbalsas, should be good now: https://github.com/liferay/liferay-portal/commit/2483df1c8b81fc495a48082c288ceb9f16ec10ea

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7328155fc2...5403f26cec

**Comment by brianchandotcom** [comment]
@jbalsas @izaera please see my changes in upstream.. merged.. trusting you guys.

**Pull request closed without merging**
