### PR TITLE
LPS-69606

### PR DESCRIPTION
**Pull request by Ithildir**
@hhuijser: I added https://github.com/brianchandotcom/liferay-portal/commit/dcaa83ab3bd935b004b971c1d604ec7716db8000 only because SF was printing this error:

> There should be an empty line before line '601', as we finished referencing variable 'name': ./src/main/java/com/liferay/gradle/plugins/defaults/internal/LiferayRelengPlugin.java 601

..but you can see [here](https://github.com/brianchandotcom/liferay-portal/blob/dcaa83ab3bd935b004b971c1d604ec7716db8000/modules/sdk/gradle-plugins-defaults/src/main/java/com/liferay/gradle/plugins/defaults/internal/LiferayRelengPlugin.java#L605) that I'm still using the variable `name`.

### CODE REVIEW

**Comment by hhuijser** [comment]
@Ithildir 
For that case, the empty line as you added is right. I know it seems a bit weird, but that's how we've been formatting cases like that.

**Comment by brianchandotcom** [comment]
@Ithildir this got auto closed? Can you ci reopen if it's good?

**Comment by Ithildir** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
