### PR TITLE
LPS-69950 LPS-69792 In lps LPS-69792 the name of the editor was changed but it wasn't updated here.

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @adolfopa

**Comment by sergiogonzalez** [comment]
hey @robertoDiaz can you please take care of backporting this change as well if we backported LPS-69792 ?

Thanks!

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by robertoDiaz** [comment]
It seems that brian has backported it:

4cead7e

**Pull request closed without merging**
