### PR TITLE
LPS-197303 baseline

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:reopen

**Comment by victorg1991** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a0ac7f47c4...a34d5c3102

**Comment by brianchandotcom** [comment]
@victorg1991 0bb66cf8453b36219799b02a8dbd62a9f4c21825

**Pull request closed without merging**
