### PR TITLE
LPS-61782

### PR DESCRIPTION
**Pull request by matethurzo**
cc: @csierra

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@matethurzo known failures.. this is OK, I"m merging it in.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/63efc3ef9c...b207191bfc

**Comment by brianchandotcom** [comment]
@matethurzo can you modify modules/portal/portal-scheduler-quartz/src/main/java/com/liferay/portal/scheduler/quartz/upgrade/v1_0_0/UpgradeQuartz.java to just call the SQL file?

See UpgradeSchema.java in modules

Thx.

**Pull request closed without merging**
