### PR TITLE
LPS-84914 Using PipingServletResponse to work inside the buffer

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by mwilliams2014** [comment]
@jbalsas we're starting 7.2 docs very soon I believe, but there is not currently a workflow in place. For now, I can maintain it on a local branch. We do have the https://dev.liferay.com/en/develop/tutorials/-/knowledge_base/7-1/front-end-taglibs section in 7.1 and we currently have this ticket: https://issues.liferay.com/browse/LRDOCS-4424 (Using the Liferay Util Taglib 7.1 docs). I can start work on this and port it to 7.2, adding the new tag info there. Thanks!

**Comment by jbalsas** [comment]
Hey @mwilliams2014, sounds good. This one should go under https://dev.liferay.com/en/develop/tutorials/-/knowledge_base/7-1/liferay-frontend-cards

Let's get it drafted already and kept around so we can push it as soon as we start with `7.2`.

Thanks!

**Comment by brianchandotcom** [comment]
@4lejandrito can you resend the pull? these are named wrong.

```
	public Optional<DLPreviewRenderer> getPreviewRenderer(
		FileVersion fileVersion);

	public Optional<DLPreviewRenderer> getThumbnailRenderer(
```

@mwilliams2014 I backported the new frontend vertical card to 7.1.x. Please make your changes via https://issues.liferay.com/browse/LRDOCS-5670

**Pull request closed without merging**
