### PR TITLE
LPS-144442 | master

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LPS-144442

Bypassing ci:forward since this causes mass functional test failures for any functional test that utilize the Web Content Artcile content field. See this test run for example failures: https://github.com/xbrianlee/liferay-portal/pull/553#issuecomment-1033870013.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/73df813803...8e1dd1759e

**Comment by Tim-Cao** [comment]
Thanks @xbrianlee

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
I think revert this commit will cause SF failures.

**Pull request closed without merging**
