### PR TITLE
LPS-66144  Standardize google-maps-portlet to new portlet structure

### PR DESCRIPTION
**Pull request by peterfellwock**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
@brianchandotcom after the last retest, no functional test failures, other than a couple jenkins failures on tests that passed on the prior retest. Should be safe to merge.

**Comment by peterfellwock** [comment]
@brianchandotcom I will close pull, rebase and send back to you.

**Pull request closed without merging**
