### PR TITLE
LPS-152217: Expose ERC in WikiPageAttachment | master

### PR DESCRIPTION
**Pull request by liuxingye**
Hi guys, I've opened this PR because most of the service changes I've made are related to your components. I'm going to introduced what are the changes that you should reviewed. Our team has verified that the errors appearing in the CI are not related, but we still want your approval, you can see [here](https://github.com/liferay-frontend/liferay-portal/pull/2512). You can check the desciption in the link of the PR from frontend-infra. Let's give you a little context.

## Main Objective
The main of this PR is to expose `externalReferenceCode` in WikiPageAttachments. For that reason I have made some changes in the service part and in the API part.

## Service part
The main changes that you should review, are the following:

- Those changes related to `PortletFileRepository` in portal-kernel. These changes are related because we add the new argument using `externalReferenceCode`.
- In the same way, in those modules I have implemented a new method to obtain a DLFile usign the `externalReferenceCode`, which is `getPortletFileEntryByExternalReferenceCode` .
- As there are some changes that affect the service part of DLFile, I want to be sure that the Staging mode works correctly, some changes are added.

## API part
However, this part can be ignored, beause it is reviewed by our members of the team.

If you have any problem, or any doubt, please contact me :smiley: 

**JIRA TICKET**
https://issues.liferay.com/browse/LPS-152217

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:reopen

**Comment by liuxingye** [comment]
Hi @brianchandotcom,
Forwarding directly from https://github.com/liferay-lima/liferay-portal/pull/3358, due to the failures are unstable and unrelated. Thanks.

**Comment by brianchandotcom** [comment]
@sergiojimcos 

```
		<exception>NodeName</exception>
		<exception>NoSuchNode</exception>
		<exception>NoSuchPage</exception>
		<exception>NoSuchWikiAttachment</exception>
```

Nlotice how the new exception name doesn't match the patterns in Wiki?

Please resend. Thx.

**Comment by brianchandotcom** [comment]
@sergiojimcos I removed NoSuchNode and NoSuchPage in c5944fe2f0f92c428d5be02f308d5e5a0ca52835

Can you name this PageAttachmentException and register it as PageAttachment?

I don't want it mixed up with the other auto generated NoSuch** that match an actual entity like Node/Page ,etc.

**Pull request closed without merging**
