### PR TITLE
test- | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/test-

### CODE REVIEW

**Comment by kyle-miho** [comment]
Hey @brianchandotcom @pavel-savinov These commits break portal smoke, because the aui:input name=name field is invisible for widget pages, so we need to revert this to keep results clean. I believe it'll also be hidden for all content pages as well.

**Comment by kyle-miho** [comment]
chrome_2019-04-11_15-50-06

**Comment by kyle-miho** [comment]
After revert: 
chrome_2019-04-11_15-51-43

**Comment by brianchandotcom** [comment]
@kyle-miho merged, @pavel-savinov see revert.

**Pull request closed without merging**
