### PR TITLE
LPS-74063

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by pyoo47** [comment]
ci:retest (Bad slave failed many tests)

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@hhuijser can you send me a corresponding pull to ee-7.0.x in advance in the future? Thx.

**Comment by brianchandotcom** [comment]
@hhuijser interesting, I merged this, published, and used the latest on ee-7.0.x and it didn't give me any complaints.

I assume you'll send me more code for how you figured out to do

a62f832d4581c11e6767531f8b1a3fff6fa2a29a

?

Thx.

**Comment by brianchandotcom** [comment]
Ah.. I forgot to publish a new gradle plugins. Doing that now and then I'll work on the SF in ee-7.0.x.

**Comment by brianchandotcom** [comment]
Oh nvm, I'm glad that it was done via auto SF.. I was afraid that I had to do it manually. Nvm for all the fuss!

**Pull request closed without merging**
