### PR TITLE
LPS-81869 Add screens compatibility plugin and headless apio to the default bundle

### PR DESCRIPTION
**Pull request by javiergamarra**
We need an exception in source formatter to be able to deploy screens as a bundle + not belong to a suite.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@nhpatt can you resend? The app description grammar/format doesn't match our existing ones. You should send it to the MP team or the Docs team.

It also needs to be part of a suite if it's pre bundled.. so it should probably be part of foundation (both of them)

Thx

**Comment by brianchandotcom** [comment]
@nhpatt also, are you sure modules/apps/headless-apio/build.gradle is needed?

**Comment by nhpatt** [comment]
Ok, I'll resend to documentation, yes, the build.gradle is needed, this PR (https://github.com/brianchandotcom/liferay-portal/pull/59545) failed because it was missing.

**Pull request closed without merging**
