### PR TITLE
LPS-84065 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LPS-84065

### CODE REVIEW

**Comment by john-co** [comment]
sent with more robust test fixes for 7.1.x backport in regards to https://github.com/brianchandotcom/liferay-portal/pull/62560

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@john-co I'm not able to "resolve" https://issues.liferay.com/browse/LPS-84065 or to push it to PM.. it's open, can you fix the LPS workflow? Thx

**Comment by john-co** [comment]
It doesn't seem that have the permissions either, I'll look into it.

**Comment by john-co** [comment]
ci:reopen

**Pull request closed without merging**
