### PR TITLE
LRQA-27213 Throw the exception if we run out of retries.

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-27213

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@pyoo47 what's going on with CI?

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
@brianchandotcom I think there was some kind of github/local-git outage.. it appears to be working again now.

**Pull request closed without merging**
