### PR TITLE
LPS-56705 support for other technology than JSPs for asset renderers and workflow handlers

### PR DESCRIPTION
**Pull request by juliocamarero**
@sergiogonzalez @marcellustavares I have applied the pattern to your components too.

can you please have a look?

thanks!

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@juliocamarero the git commit plugins references a commit that is not available. Please resend. Thx.

**Pull request closed without merging**
