### PR TITLE
LPS-93950 Generate yarn.lock

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @brianchandotcom!

I've grouped here a couple of issues together to avoid conflicts with the lock updates (they all merged cleanly, but just in case). This contains:
- Update to `clay@2.14.0` for a bunch of fixes, ux and accessibility adjustments
- Reworked the way we load the icon fonts that was causing some CSS order-specific issues
- Removed some duplicated testing packages added last week (thanks @brunobasto!). I hope to be able to send you a PR today to start enabling SF rules to prevent accidental additions in the future.

Thanks!

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:relevant @jbalsas I'm sending examples like this to John. Random modules will fail on `npmRunBuild`, but we're not sure of the cause.

**Comment by jbalsas** [comment]
Thanks @jpince! This worked fine locally... if we could get a detailed stacktrace here we might be able to pinpoint the issue... 

@petershin, do you think this might be related with the yarn cache?

**Comment by jpince** [comment]
@jbalsas it's an intermittent issue, seems to happen randomly, so not related to this pull. See this pull also: https://github.com/brianchandotcom/liferay-portal/pull/71654#issuecomment-483579263

cc/ @john-co

**Comment by jbalsas** [comment]
Hey @jpince, from a quick glance, I see in this PR:

```
     [exec] events.js:174
     [exec]       throw er; // Unhandled 'error' event
     [exec]       ^
     [exec] Error: build/_css/clay.scss
     [exec] Error: File to import not found or unreadable: clay/atlas.
     [exec]         on line 4 of build/_css/clay.scss
     [exec] >> @import "clay/atlas";
     [exec]    ^
```

and in the other one you mentioned:

```
     [exec] events.js:174
     [exec]       throw er; // Unhandled 'error' event
     [exec]       ^
     [exec] Error: build/_css/clay/atlas/_variables.scss
     [exec] Error: File to import not found or unreadable: variables/_globals.
     [exec]         on line 3 of build/_css/clay/atlas/_variables.scss
     [exec]         from line 5 of build/_css/clay/atlas.scss
     [exec]         from line 1 of build/_css/clay.scss
     [exec] >> @import "variables/_globals";
     [exec] 
     [exec]    ^
```

So, there seems to be something wonky here... maybe in the parallelization Gradle is doing. It's hard to tell because the output is all garbled up. Could we determine if this always happens on themes?

**Comment by jbalsas** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by john-co** [comment]
> Hey @jpince, from a quick glance, I see in this PR:
> 
> ```
>      [exec] events.js:174
>      [exec]       throw er; // Unhandled 'error' event
>      [exec]       ^
>      [exec] Error: build/_css/clay.scss
>      [exec] Error: File to import not found or unreadable: clay/atlas.
>      [exec]         on line 4 of build/_css/clay.scss
>      [exec] >> @import "clay/atlas";
>      [exec]    ^
> ```
> and in the other one you mentioned:
> 
> ```
>      [exec] events.js:174
>      [exec]       throw er; // Unhandled 'error' event
>      [exec]       ^
>      [exec] Error: build/_css/clay/atlas/_variables.scss
>      [exec] Error: File to import not found or unreadable: variables/_globals.
>      [exec]         on line 3 of build/_css/clay/atlas/_variables.scss
>      [exec]         from line 5 of build/_css/clay/atlas.scss
>      [exec]         from line 1 of build/_css/clay.scss
>      [exec] >> @import "variables/_globals";
>      [exec] 
>      [exec]    ^
> ```
> So, there seems to be something wonky here... maybe in the parallelization Gradle is doing. It's hard to tell because the output is all garbled up. Could we determine if this always happens on themes?
> 
> This might be related to some weird `404` messages @john-co was trying to track down as well...

Hi @jbalsas, I think all the issues we noticed seem to be theme related except this one which was related to product-navigation: https://github.com/brianchandotcom/liferay-portal/pull/71584

cc/ @jpince

**Pull request closed without merging**
