### PR TITLE
LPS-103009 Update liferay-npm-scripts to v11.0.0

### PR DESCRIPTION
**Pull request by wincent**
The most relevant changes are:

- feat: updates js-toolkit modules to v2.13.3
- fix(scripts): disables useStrict in commonjs transform by default
- feat: cleans up rogue sourcemaps inside liferay-npm-bridge-generator output
- feat(scripts): support "export namespace from" in Babel

### CODE REVIEW

**Comment by wincent** [comment]
Corresponding "master-private" pull is here: https://github.com/brianchandotcom/liferay-portal-ee/pull/26946

**Comment by jbalsas** [comment]
I'll send this together with the last clay update

**Comment by jbalsas** [comment]
ci:close

**Comment by brianchandotcom** [comment]
@wincent @jbalsas I merged in the pull for master-private, even though this corresponding pull was closed. Hope that's OK.

**Pull request closed without merging**
