### PR TITLE
OAUTH2-276 Client Credentials fix

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
[OAUTH2-276](https://issues.liferay.com/browse/OAUTH2-276)

/cc @topolik @csierra

### CODE REVIEW

**Comment by jpince** [comment]
@stian-sigvartsen @csierra see semver error, looks related
```
     [exec] > Task :apps:oauth2-provider:oauth2-provider-api:baseline FAILED
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.oauth2.provider.exception              MAJOR      1.1.1      1.1.1      2.0.0      VERSION INCREASE REQUIRED
     [exec] 	>   class      com.liferay.oauth2.provider.exception.OAuth2ApplicationClientCredentialUserIdException
     [exec] 		+   field      clientCredentialUserId
     [exec] 			+   return     long
     [exec] 		+   field      clientCredentialUserScreenName
     [exec] 			+   return     java.lang.String
     [exec] 		+   field      userId
     [exec] 			+   return     long
     [exec] 		+   field      userScreenName
     [exec] 			+   return     java.lang.String
     [exec] 		-   method     <init>()
     [exec] 			-   return     void
     [exec] 		-   method     <init>(java.lang.String)
     [exec] 			-   return     void
     [exec] 		-   method     <init>(java.lang.String,java.lang.Throwable)
     [exec] 			-   return     void
     [exec] 		-   method     <init>(java.lang.Throwable)
     [exec] 			-   return     void
     [exec] 		+   method     <init>(long,java.lang.String,long,java.lang.String)
     [exec] 			+   return     void
```

**Comment by stian-sigvartsen** [comment]
Thanks @jpince . We will resend

**Comment by stian-sigvartsen** [comment]
Hey @jpince . Is a major version bump acceptable for a 7.2.x release at this stage?

**Comment by jpince** [comment]
@stian-sigvartsen for a packageinfo, yes. No for module version change bnd.bnd

**Comment by stian-sigvartsen** [comment]
Thanks @jpince

**Pull request closed without merging**
