### PR TITLE
Lps 68289 4

### PR DESCRIPTION
**Pull request by shuyangzhou**
@hhuijser you may have a better way to ignore the EE copied code. I just did this quick fix to make CI running. Please feel free to redo it your way, thanks!

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@brianchandotcom you merged in something that is bad formatted from https://github.com/brianchandotcom/liferay-portal/pull/43338
```
java.lang.Exception: There should be an empty line before line '54', as we finished referencing variable 'entry': ./modules/util/source-formatter/../../../modules/apps/collaboration/announcements/announcements-web/src/main/java/com/liferay/announcements/web/internal/portlet/action/ViewEntryMVCRenderCommand.java 54
```
Force pushed with SF

ci:reopen

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/43369

**Pull request closed without merging**
