### PR TITLE
LPS-91668 - SF

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by jpince** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/dba3bfeb0f...7b41c7ab46

**Comment by brianchandotcom** [comment]
@pat270 @marcoscv-work please review 53a3dc7 is it in the right place?

Also see a52d8ff and a838973

**Pull request closed without merging**
