### PR TITLE
LPS-75444 adding fullURL to layoutsTree's JSONObject

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:reopen

**Comment by ealonso** [comment]
ci:retest

**Comment by brianchiu** [comment]
CalendarConfiguration#ViewCalendarTimeZoneDefaults is failing due to an inconsistent Elasticsearch issue during portal startup.

We're investigating it here:
https://issues.liferay.com/browse/LRQA-35988

**Comment by brianchandotcom** [comment]
@ealonso can you resend? We have Portal#getLayoutFullURL

and layouts_tree.jsp already has "layoutURL", so we should be consistent in the naming. Please resend and rename the variable. Thx.

**Comment by ealonso** [comment]
Hey @balazssk,
Can we just use layoutURL parameter, instead of setting the fullURL?

Something like this:

`var NODE_LINK_TPL = '<a class="{cssClass}" data-layoutURL="{layoutURL}" data-url="{url}" data-uuid="{uuid}" href="{layoutURL}" id="{id}" title="{title}">{label}</a>';`

Regards,
Eudaldo.

**Comment by balazssk** [comment]
Hi @ealonso ,

Looking into it, thanks!

**Pull request closed without merging**
