### PR TITLE
OAUTH2-131 Add Oauth to build

### PR DESCRIPTION
**Pull request by csierra**
/cc @topolik @stian-sigvartsen

### CODE REVIEW

**Comment by csierra** [comment]
ci:test:relevant

**Comment by csierra** [comment]
ci:reopen

**Comment by csierra** [comment]
hey @brianchandotcom, 
that log message is OK. This pull adds a test to verify that OAuth2 and JSON WS work together. That message is the result of the control checking that the verifier is in place. This is the line https://github.com/brianchandotcom/liferay-portal/pull/59109/commits/42f6fd9549a217f7f4fe5a072018bc1a7deee624#diff-cfc7ddcfca0eb109c5eca9aa545ded1cR65

next the test verifies it can access using token.

**Comment by jpince** [comment]
ci:close @csierra can you please modify the test or app in a way that the error is not thrown, or is less severe? Otherwise, you can work with xbrianlee and Shuyang to ignore the error, but I don't think this is the right solution

**Comment by topolik** [comment]
Hi @jpince, yeah, it's a bug in portal, we should not throw exception and log error message during a standard request flow. Created https://issues.liferay.com/browse/LPS-81571 Thanks.

**Comment by csierra** [comment]
hey @jpince @brianchandotcom 
please see https://github.com/brianchandotcom/liferay-portal/pull/59170

thx!

**Pull request closed without merging**
