### PR TITLE
#Ping [See description] LPS-65767 Apply Settings to Knowledge Base

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey Brian,

This pull applies the Settings Framework to Knowledge Base.
It would be great if you could review this pull soon so I can send you some Lexicon changes in Knowledge Base.

Thanks!

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @robertoDiaz

**Comment by evannagayama** [comment]
This might be an issue. I'm going to check out the failing test ApplicationdisplaytemplatesUsecase#AddRSSADTViaPortletConfiguration

**Comment by evannagayama** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Hey @evannagayama this pull only modifies Knowledge Base module, so I don't think that it's related to Blogs ADT.
Let me know if you I can help you with anything.
Thanks!

**Comment by evannagayama** [comment]
@sergiogonzalez Yeah I think this issue is already in master...I'll try to figure out the issue. Thanks! 

@brianchandotcom I'm going to remove the test and find out the issue. It seems to already be in master and unrelated to this pr.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1d1b629b9a...534aea107d

**Pull request closed without merging**
