### PR TITLE
LPS-70549

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by matethurzo** [comment]
@brianchandotcom yes I've already asked @robertoDiaz to implement a test case, pushed it to you because it was urgent. But yes, we definitely need a test

**Comment by robertoDiaz** [comment]
I'll send the test ASAP. 

One cuestión @matethurdo. Where should we crrate the test. My fist though was create it for journal service, but since this logic affects a bunch of portlets maybe we should generify this?

Thanks!

**Comment by robertoDiaz** [comment]
@matethurzo and @brianchandotcom 

@mbowerman found a failing case and has fix it and add some tests [here](https://github.com/danielkocsis/liferay-portal/pull/604/commits/3f391ee3892c9013398df566855d7506c68ab309)

@matethurzo do you think they are enough or should we add more use cases??

Thanks!!!

**Pull request closed without merging**
