### PR TITLE
LPS-83072 Fix typo

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso, @brianchiu

**Comment by jpince** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchiu** [comment]
@jpince This one's probably good, right? lpkg base didn't fail on the last relevant test, and the functional test failure was a startup issue, but it passed in both of the previous relevant tests.

**Comment by jpince** [comment]
@brianchiu yes, if you dig into the log, it's the same issue in two different batches. Shuyang fixed the race condition here: [PR#61581](https://github.com/brianchandotcom/liferay-portal/pull/61581)

**Pull request closed without merging**
