### PR TITLE
LPS-98640 Build Rest

### PR DESCRIPTION
**Pull request by epgarcia**
@brianchandotcom @hhuijser This is the first time we document headers in the APIs. Maybe we can find a better format.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@epgarcia can you add #review so the docs team knows about it, and sort the headers?

@nhpatt can you review?

**Comment by nhpatt** [comment]
Will do! :)

**Comment by nhpatt** [comment]
Reviewed!

**Comment by dgarciasarai** [comment]
Thanks!

**Pull request closed without merging**
