### PR TITLE
LPS-63652

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
/cc @shuyangzhou

Basically preventing any class to call UpgradeProcess.upgradeTable directly... let me know if that sounds about right?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/36a7fb8941...c6a657f56e

**Comment by shuyangzhou** [comment]
@hhuijser That's right, but not complete. Someone could still run "alter_column_type" "alter_column_name" without using upgradeTable as fallback, that is wrong too. We should only use new alter method from now on.

**Comment by hhuijser** [comment]
@shuyangzhou 

Got it, will see if that can be added, looks like we'll need some pretty complex regex for that...

**Pull request closed without merging**
