### PR TITLE
LPS-65636

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@michaelhashimoto, can you take care of this one?: https://github.com/brianchandotcom/liferay-portal/pull/39458/commits/3b0f6d3ceec262b6871ebfd2ce6aaa784ef5e785

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/db7390f990...cb9001aaba

**Comment by michaelhashimoto** [comment]
@hhuijser I'll look into it.

Thanks!

**Comment by michaelhashimoto** [comment]
Here's a SF for the files you mentioned:
https://github.com/brianchandotcom/liferay-portal/pull/39487

**Pull request closed without merging**
