### PR TITLE
LPS-93347 changed the name of the var

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:reopen 

Failures not related

**Comment by brianchandotcom** [comment]
@AliciaGarciaGarcia see e46f8b8b3df016284416c3d6a980fce4e055e860

**Pull request closed without merging**
