### PR TITLE
LPS-80341 Extend ConfigurationFormRenderer to provide custom reads of the params so that the inputs can have any desired name

### PR DESCRIPTION
**Pull request by JorgeFerrer**
/cc @pei-jung @drewbrokke

### CODE REVIEW

**Comment by jpince** [comment]
ci:stop

**Comment by jpince** [comment]
ci:test

**Comment by JorgeFerrer** [comment]
ci:reopen

**Comment by JorgeFerrer** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/81614516d1...99bbffe059

**Comment by brianchandotcom** [comment]
@JorgeFerrer please follow my commits in upstream in case I made any mistakes... Thx.

**Comment by JorgeFerrer** [comment]
They look fine. Thanks Brian

**Pull request closed without merging**
