### PR TITLE
LPS-161459 Show Web Content Title when displayed in a Display Page Template

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-161459

@BarbaraCabrera 
@lfbesada

### CODE REVIEW

**Comment by ozysouza** [comment]
ci:Reopen

**Comment by ozysouza** [comment]
ci:reopen

**Comment by ozysouza** [comment]
The tests stable and relevant passed but the CI doesn't sent it. I'm sending the PR directly.
See https://github.com/liferay-echo/liferay-portal/pull/9463#issuecomment-1230571526

:heavy_check_mark: ci:test:stable - 25 out of 27 jobs passed
:heavy_check_mark: ci:test:relevant - 65 out of 69 jobs passed in 1 hour 46 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8afdecb5d5...40068e93d2

**Pull request closed without merging**
