### PR TITLE
Lps 73353

### PR DESCRIPTION
**Pull request by shuyangzhou**
@brianchandotcom @mhan810 @JorgeFerrer this is the jacoco integration, our part is complete after this pull. The rest will need to be done by Testray (with some help from QA)

Here are the steps for QA to continue the work:

    1) In upstream jobs, turn on jacoco by adding test.batch.code.coverage=true into test.properties
    2) After tomcat dist job, there will be one jar file created at ${project.dir}/jacoco/merged.jar, this file needs to be pushed to Testray. We only need this file for Testray, not for every test node, so no need to replicate it to all nodes.
    3) At the end of each test node job, must be after the test jvms all shutdown(jacoco only dumps session data during jvm shutdown, if we sample before the jvm is stopped, the session file will not be complete), there will be a file created at ${project.dir}/jacoco/liferay-jacoco.exec, this file needs to be pushed to Testray. This file is per test node, so there will be hundreds of them.
    4) CI must inform Testray the git hash id of the build, which I believe we must already have it.

Once Testray gets all the info above from CI, here are the steps to continue to generate the report:

    a) Checkout the given build git hash
    b) Put the merged.jar from 2) into somewhere local, let's say it is at $MERGED_JAR
    c) Put all collected liferay-jacoco.exec into one folder, Testray must rename them to avoid overwriting, they can be named in any way, as long as you keep the ".exec" extension. Let's say they are put at $EXEC_FOLDER
    d) Invoke the following ant target from portal repo root.
        ant generate-code-coverage-report - Djacoco.dump.file=$EXEC_FOLDER -Djacoco.merged.jar=$MERGED_JAR
    e) The html report will be generated at ${project.dir}/jacoco/html-report, Testray needs to host it somewhere, so that developers can look up the code coverage results.

As the report html size is very large, we will have to do some shrinking for long term archiving purpose. But let's worry about that after Testray and QA get the system up running first.

CC @pyoo47

@brianchandotcom not sure who from Testray you want to put on this task?

### CODE REVIEW

**Comment by shuyangzhou** [comment]
For developers local code coverage usage:
1) For unit test(including portal unit, module unit and portal-impl integration), just add -Djunit.code.coverage=true to your test command.
2) For module integration(aka Arquillian test), there are 2 ways.
    a) If you want to start tomcat manually, start it this way: "./catalina.sh jacoco run", then you can just run tests as you normally do
    b) If you want gradle to start the tomcat for you, run the test this way :
`gw testIntegration --tests YourTest --Dapp.server.start.executable.arg.line="jacoco run"`
3) Once your finish all your tests, to generate the report, run "ant generate-code-coverage-report" from project root. The report will be dumped at ${project.dir}/jacoco/html-report.

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
@tinatian please fix the jacoco license info, you can ask @tomwang2011 for details.

**Comment by brianchandotcom** [comment]
@tinatian please fix and resend? Thx.

**Comment by tinatian** [comment]
Done, please see https://github.com/brianchandotcom/liferay-portal/pull/50472

**Pull request closed without merging**
