### PR TITLE
LRQA-29131 Comment out test case affected by LPS-69254 | 7.0.x

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LRQA-29131

### CODE REVIEW

**Comment by jpince** [comment]
ci:stop

**Comment by jpince** [comment]
Run results in testray: https://testray.liferay.com/home/-/testray/runs?testrayBuildId=57531197. 100% passing on functional tests.

**Comment by brianchandotcom** [comment]
Merging. This is 7.0.x only? I don't see it for master.

**Comment by brianchiu** [comment]
@brianchandotcom Yes. Sorry. I forgot to mention it's only for 7.0.x.

**Pull request closed without merging**
