### PR TITLE
LPS-74197 gradlew npmShrinkwrap - collaboration

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey @sergiogonzalez,

Just regenerating the `npm-shrinkwrap.json` files in order to update `liferay-module-config-generator` to a more stable version.

### CODE REVIEW

**Comment by Robert-Frampton** [comment]
ci:reopen

**Comment by Robert-Frampton** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4aa36e5751...0363f34cd1

**Pull request closed without merging**
