### PR TITLE
LPS-169672 Provide users with clear information to register iFrame client extensions

### PR DESCRIPTION
**Pull request by john-co**
Resend of https://github.com/brianchandotcom/liferay-portal/pull/127864#issuecomment-1379844751

### CODE REVIEW

**Comment by dsanz** [comment]
ci:reopen

**Comment by dsanz** [comment]
Hi @brianchandotcom this one comes from https://github.com/brianchandotcom/liferay-portal/pull/127864#issuecomment-1379844751 I fixed the lang keys.

Thank you

**Comment by john-co** [comment]
Hi @brianchandotcom , can you review this when you get the chance? Thanks.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9b9e1615b2...d1cb63a277

**Pull request closed without merging**
