### PR TITLE
LPS-57200 fix asset renderer issue without changing the API

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@juliocamarero I made some changes that I'm testing on https://github.com/brianchandotcom/liferay-portal/pull/38212

Fyi.

**Comment by brianchandotcom** [comment]
Retrying https://github.com/brianchandotcom/liferay-portal/pull/38225

**Pull request closed without merging**
