### PR TITLE
LPS-165777  Options for Utility Pages Integration Tests

### PR DESCRIPTION
**Pull request by Tim-Cao**
This is only for master.

https://issues.liferay.com/browse/LPS-165777

@lfbesada

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/10712

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bd23bb913a...ab2e4084a2

**Comment by brianchandotcom** [comment]
@lfbesada just ab2e4084a222493ca716eb6028742fb121dc4627

**Pull request closed without merging**
