### PR TITLE
 Pull requests 23  Projects 0  Insights LPS-78086 LPS-78087 Modularize liferay-ui:social-activities, liferay-ui:rss, liferay-ui:rss-settings

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey Brian,

This pull contains 2 LPS tickets that are related:
LPS-78086 -> Modularizes liferay-ui:social-activities taglib.
LPS-78087 -> Modularizes liferay-ui:rss and liferay-ui:rss-settings taglib.

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @brandizzi @drewbrokke @pei-jung

I have updated your components (calendar-web and contacts-web) to use the new taglibs. You guys don't need to do anything, this is just a heads-up 👍 

Thanks!

**Comment by sergiogonzalez** [comment]
ci:test

**Comment by jpince** [comment]
ci:close

**Comment by jpince** [comment]
@sergiogonzalez compile error `Caused by: org.apache.jasper.JasperException: file:/opt/dev/projects/github/liferay-portal/modules/apps/collaboration/social/social-activities-taglib/build/unzipped-jar/META-INF/resources/init.jsp(22,61) PWC6188: The absolute uri: http://liferay.com/tld/rss cannot be resolved in either web.xml or the jar files deployed with this application`

**Comment by sergiogonzalez** [comment]
Thanks @jpince 
I resent it here https://github.com/brianchandotcom/liferay-portal/pull/55485

**Pull request closed without merging**
