### PR TITLE
Lps 68777

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @sergiogonzalez @mhan810

### CODE REVIEW

**Comment by shuyangzhou** [comment]
A lot of network failures, 
```
22:05:34,894 ERROR [localhost-startStop-1][DialectDetector:137] com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
```
what's going on? @michaelhashimoto and @pyoo47

All DBs are local, how could this happen? Someone is resetting the CI machines?

**Comment by pyoo47** [comment]
@shuyangzhou We've been rebuilding the slaves selectively due to problems with VNC. Sam has been using his slave rebuild script and we've recreated the working directories. Is there additional setup steps that we've been missing? We've used this procedure for a while now whenever we've had to rebuild slaves and haven't heard about any problems in the past.

**Comment by shuyangzhou** [comment]
@brianchandotcom just talked to @pyoo47 , it is a CI build issue, somehow every database batch job is using mysql. Because we only start the DB service for the one being tested, mysql service was not even up when it runs on other DB batches, therefore the jdbc connection can not be made. So basically we are randomly messing up with the test portal-ext.properties generation. @pyoo47 is going to look into this.

**Comment by pyoo47** [comment]
We took an initial look and didn't find anything that has changed recently. It's especially odd that it seems to be a sporadic problem. @michaelhashimoto is going to add some code to print out the portal-ext.properties file in the log so we can see what was there the next time it happens.

**Comment by brianchandotcom** [comment]
@pyoo47 should I merge this or not?

**Comment by shuyangzhou** [comment]
This pull is fine. The failure is a build issue. We can just retest it to be safe.

ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by pyoo47** [comment]
ci:retest

**Pull request closed without merging**
