### PR TITLE
LPS-89142 Early detection of runtime circular dependencies at compile time in Search unit tests

### PR DESCRIPTION
**Pull request by arboliveira**
Sending again, addressing concerns from https://github.com/brianchandotcom/liferay-portal/pull/66810#issuecomment-454964409. No more `1`'s in constructors 😃 

----

❌ **ci:test:search - 14 out of 16 jobs passed in 1 hour 31 minutes 17 seconds 325 ms**
https://github.com/arboliveira/liferay-portal/pull/649#issuecomment-455005763

**This pull contains no unique failures.**
Branch master is contaminated: https://github.com/brianchandotcom/liferay-portal/pull/66731#issuecomment-454468280 

*[Task] Early detection of runtime circular dependencies at compile time in Search unit tests*
https://issues.liferay.com/browse/LPS-89142

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@arboliveira you're not going to like this... but,

I find this very strange:

```
	protected static CreateSnapshotRepositoryRequestExecutor
		createCreateSnapshotRepositoryRequestExecutor(
			ElasticsearchClientResolver elasticsearchClientResolver1) {

		return new CreateSnapshotRepositoryRequestExecutorImpl() {
			{
				elasticsearchClientResolver = elasticsearchClientResolver1;
			}
		};
	}
```

It should be:

```
	protected static CreateSnapshotRepositoryRequestExecutor
		createCreateSnapshotRepositoryRequestExecutor(
			ElasticsearchClientResolver elasticsearchClientResolver) {

		return new CreateSnapshotRepositoryRequestExecutorImpl() {
			{
				setElasticsearchClientResolver(elasticsearchClientResolver);
			}
		};
	}

```

But that means refactoring

CreateSnapshotRepositoryRequestExecutorImpl

```
	@Reference
	protected ElasticsearchClientResolver elasticsearchClientResolver;
```

to

```
	@Reference
	private ElasticsearchClientResolver _elasticsearchClientResolver;
```

and adding just a setter.

```
setElasticsearchClientResolver(ElasticsearchClientResolver elasticsearchClientResolver) {
	_elasticsearchClientResolver = elasticsearchClientResolver;
}
```

I know this is more verbose and goes against having just fields vs. setters, but this is exactly why I prefer setters so that we don't have these random vars:

xyz1
xyz

Whenever I see xyz1, I immediately look for an xyz2, but in this case, they're declared in different scopes and very confusing.

Please resend, sorry!

**Comment by arboliveira** [comment]
ci:test:reopen

**Comment by arboliveira** [comment]
ci:reopen

**Comment by arboliveira** [comment]
@brianchandotcom As we discussed, please merge as is temporarily (so I can send other related pulls)  and @wcao20170619 will do your recommended changes immediately. Thanks! 😃

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by arboliveira** [comment]
Recommended coding convention will be applied by: https://issues.liferay.com/browse/LPS-89318

**Pull request closed without merging**
