### PR TITLE
LPS-73119 As a developer, I would like to have a way to temporarily set OSGi Configuration values in a test

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-73119](https://issues.liferay.com/browse/LPS-73119).<br><br>First pull request per your request here: https://github.com/brianchandotcom/liferay-portal/pull/49828#issuecomment-311742707<br><br>/cc @shuyangzhou

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fcb8c5c600...529b0f6ecb

**Comment by brianchandotcom** [comment]
@drewbrokke @shuyangzhou I merged this in, but I'm not sure whether this should be published from 7.0.x or master. Come grab me tomorrow so we can find out? Thx.

**Pull request closed without merging**
