### PR TITLE
LPS-86437 Regen

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d050fc046f...c3c10b0c90

**Comment by brianchandotcom** [comment]
@epgarcia merged in..

Regarding

```
	@Activate
	public void activate(BundleContext bundleContext) {
		_serviceTrackerMap = ServiceTrackerMapFactory.openSingleValueMap(
			bundleContext, ODataRetriever.class, "model.class.name");
	}
```

Unless we expect people to customize this and plug in additional ODataReceivers (vs. ones you hard code), we should avoid using OSGi (since it costs a few ms - they all add up). Just fyi.

You should have a 3 minute conversation with @preston-crary about how we're "conserving" OSGi usage to speed up runtime/boot up time

**Comment by Preston-Crary** [comment]
@epgarcia, the service tracker is fine as long as it's being used.  I much prefer using a service tracker map (like you have in this pull) then some of the things we've seen with BundleTrackers + ServiceTrackers.

Please avoid using String.format though, it's much heavier then most service trackers and very easy to replace with StringBundler.concat().

**Comment by epgarcia** [comment]
@Preston-Crary, thank you very much for the hints. I'll replace the String.format() with StringBundler.concat() where applicable. Regards!

**Pull request closed without merging**
