### PR TITLE
LPS-68989 Move code to CustomServletContextHelper so BundleUtil method does only what it is supposed to do

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest @shuyangzhou that's a strange test failure?

**Comment by shuyangzhou** [comment]
@brianchandotcom this is the one with last night's debug output, I will look into the thread dumps.

**Comment by shuyangzhou** [comment]
See the fix at https://github.com/brianchandotcom/liferay-portal/pull/44971

**Comment by rotty3000** [comment]
seems like a network or caching error from the maven repository.

ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2d7dff91e2...af2f5a46a3

**Pull request closed without merging**
