### PR TITLE
LPS-82226 SF

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:close @brianchiu @anthony-chu please investigate

@carloslancha there is a unique test failure in portal smoke, we will investigate and resend if it's just a test fix needed.
```
java.lang.Exception: Element <a aria-label="Add Page" class="btn btn-primary nav-btn nav-btn-monospaced" href="http://localhost:8080/group/site-name/~/control_panel/manage?p_p_id=com_liferay_layout_admin_web_portlet_GroupPagesPortlet&amp;p_p_lifecycle=0&amp;p_p_state=maximized&amp;p_p_mode=view&amp;_com_liferay_layout_admin_web_portlet_GroupPagesPortlet_mvcPath=%2Fselect_layout_page_template_entry.jsp&amp;_com_liferay_layout_admin_web_portlet_GroupPagesPortlet_navigation=public-pages&amp;_com_liferay_layout_admin_web_portlet_GroupPagesPortlet_redirect=%2Fgroup%2Fsite-name%2F%7E%2Fcontrol_panel%2Fmanage%3Fp_p_id%3Dcom_liferay_layout_admin_web_portlet_GroupPagesPortlet%26p_p_lifecycle%3D0%26p_p_state%3Dmaximized%26p_p_mode%3Dview%26_com_liferay_layout_admin_web_portlet_GroupPagesPortlet_mvcRenderCommandName%3D%252Flayout%252Fview%26_com_liferay_layout_admin_web_portlet_GroupPagesPortlet_tabs1%3Dpages%26_com_liferay_layout_admin_web_portlet_GroupPagesPortlet_navigation%3Dpublic-pages%26_com_liferay_layout_admin_web_portlet_GroupPagesPortlet_orderByCol%3Dcreate-date%26_com_liferay_layout_admin_web_portlet_GroupPagesPortlet_orderByType%3Dasc%26p_p_auth%3DxzBnKcF4&amp;_com_liferay_layout_admin_web_portlet_GroupPagesPortlet_backURL=%2Fgroup%2Fsite-name%2F%7E%2Fcontrol_panel%2Fmanage%3Fp_p_id%3Dcom_liferay_layout_admin_web_portlet_GroupPagesPortlet%26p_p_lifecycle%3D0%26p_p_state%3Dmaximized%26p_p_mode%3Dview%26_com_liferay_layout_admin_web_portlet_GroupPagesPortlet_mvcRenderCommandName%3D%252Flayout%252Fview%26_com_liferay_layout_admin_web_portlet_GroupPagesPortlet_tabs1%3Dpages%26_com_liferay_layout_admin_web_portlet_GroupPagesPortlet_navigation%3Dpublic-pages%26_com_liferay_layout_admin_web_portlet_GroupPagesPortlet_orderByCol%3Dcreate-date%26_com_liferay_layout_admin_web_portlet_GroupPagesPortlet_orderByType%3Dasc%26p_p_auth%3DxzBnKcF4&amp;_com_liferay_layout_admin_web_portlet_GroupPagesPortlet_groupId=37780&amp;p_r_p_selPlid=0&amp;p_r_p_privateLayout=false&amp;_com_liferay_layout_admin_web_portlet_GroupPagesPortlet_selectedTab=basic-pages&amp;p_p_auth=xzBnKcF4" title="Add Page"></a> is not clickable at point (1244, 143.5). Other element would receive the click: <div class="tooltip-inner"></div>
Command duration or timeout: 0 milliseconds
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
System info: host: 'cloud-10-0-19-226.lax.liferay.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'i386', os.version: '2.6.32-042stab127.2', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptSslCerts: true, applicationCacheEnabled: true, browserName: firefox, cssSelectorsEnabled: true, databaseEnabled: true, handlesAlerts: true, javascriptEnabled: true, locationContextEnabled: false, nativeEvents: false, platform: LINUX, platformName: LINUX, rotatable: false, takesScreenshot: true, version: 52.0.2, webStorageEnabled: true}
Session ID: a0728371-b45f-4956-b871-6eb1535112b5
```

**Comment by anthony-chu** [comment]
hey @carloslancha, it looks like the "Add" tooltip is not getting removed after initially interacting with the "Add" button in the management toolbar.

**Comment by carloslancha** [comment]
@anthony-chu I'm fixing that, thx!

**Comment by carloslancha** [comment]
@anthony-chu resent https://github.com/brianchandotcom/liferay-portal/pull/60141

**Pull request closed without merging**
