### PR TITLE
LPS-53821 Update dependencies and run setup-eclipse

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@robertoDiaz can you resend?

1.) modules/apps/document-library/document-library-item-selector-web/src/META-INF/resources/documents.jsp has a weird import

2.) Can you move 

portal-service/src/com/liferay/portal/kernel/util/ServiceReferenceMapperFactory.java to portal-service/src/com/liferay/portal/kernel/registry/ServiceReferenceMapperFactory.java

and

portal-service/src/com/liferay/portal/kernel/util/ServiceTrackerCustomizerFactory.java to portal-service/src/com/liferay/portal/kernel/registry/ServiceTrackerCustomizerFactory.java

please update references as well.

Thx

**Comment by robertoDiaz** [comment]
hey @brianchandotcom,

 should I move ServiceReferenceMapperFactory too?

**Pull request closed without merging**
