### PR TITLE
Lps 84682

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/49e46d3ca9...4be3a67aab

**Comment by brianchandotcom** [comment]
@sergiogonzalez I partially backported this to 7.1.x (just the permission contributor change).

**Comment by brianchandotcom** [comment]
@sergiogonzalez in the future, can you send those changes separately, with a different LPS. Thx!

I didn't backport the sharing changes.

**Comment by sergiogonzalez** [comment]
👍 thanks  @brianchandotcom

**Pull request closed without merging**
