### PR TITLE
LPS-76075 Change Blogs Configuration UI and update Social Bookmarks Settings

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @ealonso please see Asset Publisher changes in https://github.com/brianchandotcom/liferay-portal/pull/53374/commits/99b7937ceeea77689b5981d8a06929ca28cd457d https://github.com/brianchandotcom/liferay-portal/pull/53374/commits/3fdac80496928d78cf6b1b65b22e790dec984617 https://github.com/brianchandotcom/liferay-portal/pull/53374/commits/c666dad68973c9fe617ef1d839925d3561bba955 https://github.com/brianchandotcom/liferay-portal/pull/53374/commits/a19b7ce204ab54df42de41898d11dc96a9e46446 https://github.com/brianchandotcom/liferay-portal/pull/53374/commits/e43bce34f7eb3aaf4013652d4be5021797d31c5a

**Comment by jbalsas** [comment]
Looks good to me, @sergiogonzalez!

**Comment by sergiogonzalez** [comment]
Social Bookmarks has changed from this
image
to this
image

As you can see there's no longer an Enable switch. If admins want to disable Social Bookmarks they will need to move them from the current column to the available column. 
In addition, administrators can now decide the order that the social bookmarks will appear. This is  a new feature and it was not possible before. 
We have removed the Display Position select box. The social bookmarks position is no longer a setting and if somebody wants to change it they will need to create a new Application Display Template for that and they can place the social bookmarks wherever they prefer. By default we are displaying the Social Bookmarks in the bottom position.

There is an upgrade code that ensures that ensures that we keep the same behaviour as in 7 regarding the Enable/Disable Social Bookmarks. Since we have removed the switch and now we need to move social bookmarks to the available column, there's an upgrade process that in case the Social Bookmarks were disabled, all the social bookmarks will be moved to the available column to ensure that after the upgrade the behaviour will be the same (no social bookmarks will be displayed). This upgrade applies to Asset Publisher, Knowledge Base and Blogs.

**Comment by sergiogonzalez** [comment]
@austinchiang in addition to the social bookmarks changes, we have also reorganized the blogs configuration section and did some rewording on same of the labels. 

We changed:
- Enable Related Assets -> Show Related Assets
- Enable Comment Ratings -> Enable Ratings for Comments
- Enable Flags -> Enable Report Inappropriate Content

And we applied those language keys in every other portlet configuration that has the same labels, such as, bookmarks, documents and media, message boards, wiki.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/08ca93ddb9...5e051668ab

**Comment by brianchandotcom** [comment]
@sergiogonzalez merged.. can you backport the JS changes to

modules/apps/foundation/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/input_move_boxes.js

and probably the KB changes as well.

Thx @sergiogonzalez

**Comment by sergiogonzalez** [comment]
Sent here https://github.com/liferay/liferay-portal-ee/pull/3571

**Pull request closed without merging**
