### PR TITLE
latest-master

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@shuyangzhou

see OrganizationIndexerTest. I've seen that randomly in 2 branches.

See https://github.com/brianchandotcom/liferay-portal/pull/46239

**Comment by shuyangzhou** [comment]
@preston-crary I thought we applied the toString() on Hits globally? But this one does not have it in the assert log, it still only prints the useless count mismatch info.

But anyway, this looks like one of async index deleting issue you fixed before, should be something very similar. Please take care of it on Monday, and make sure we have all the Hits.toString() applied, and maybe find a centralized way to sync up all these kind of async index deleting issues.

**Comment by Preston-Crary** [comment]
@shuyangzhou This is a new test, added last month.

**Comment by Preston-Crary** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/3682, I didn't find the cause of the issue yet but it appears to me to be combination problem.  Hopefully fixing the assert will give us some useful information.

**Pull request closed without merging**
