### PR TITLE
LPS-76927 Tracking every small upgrade process in Core with a unique SchemaVersion and simplifying the release process

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test

**Comment by achaparro** [comment]
ci:reopen

**Comment by achaparro** [comment]
ci:test

**Comment by achaparro** [comment]
ci:stop

**Comment by achaparro** [comment]
ci:retest

**Comment by achaparro** [comment]
ci:test

**Comment by brianchandotcom** [comment]
I ran "git grep portal-data-release"

build-working-dir.xml:                  
build-working-dir.xml:                          replace.regex.file="sql/portal-data-release.sql"
portal-impl/build.xml:                          includes="portal-data-common.sql,portal-data-counter.sql,portal-data-release.sql,portal-tables.sql,indexes.properties,indexes.sql,sequences.sql,update-*.sql"
sql/portal.sql:@include portal-data-release.sql

There are still references to the removed file. Please resend

**Pull request closed without merging**
