### PR TITLE
LPS-78558 FindSecurityBugs tool improvements

### PR DESCRIPTION
**Pull request by topolik**
Hi Brian,

resending https://github.com/brianchandotcom/liferay-portal/pull/55960 with SF fix (I removed `/* @generated */` from patch file by accident)

PR already went through Andrea's review.

/cc @Ithildir - I had to change your last commits to adapt to master

Thanks.

### CODE REVIEW

**Comment by topolik** [comment]
No other unique CI failures beside SF ... https://github.com/brianchandotcom/liferay-portal/pull/55971#issuecomment-371482413

Let's wait for SF.

Thanks.

**Comment by brianchandotcom** [comment]
@codyhoag fyi

**Comment by brianchandotcom** [comment]
@topolik I backported most of the Gradle and third-party changes. But I skipped 25df727e9f20d96dbab7b26119fdd2d8644b89ed

Note that we only have one jar for modules/third-party/com-h3xstream-findsecbugs that is synced between 7.0.x and master, so I'm not sure if 084af8e98005f2c5a2befafc93b29fa1d51297ab is still valid.

Please review my changes in 7.0.x, it's all in one list. Thx.

@ithildir fyi as this will affect how we fork things.

**Comment by topolik** [comment]
Thanks @brianchandotcom, that's fine. When the definitions in 084af8e are not used in 7.0 there is no impact on execution. I count on that we have just one JAR in both. Thanks.

**Pull request closed without merging**
