### PR TITLE
LPS-173562 Adding Friendly URL redirect configuration for locale.prepend.friendly.url.style=2

### PR DESCRIPTION
**Pull request by adolfopa**
https://issues.liferay.com/browse/LPS-173562

Manually forwarded from https://github.com/liferay-lima/liferay-portal/pull/3965.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@adolfopa @danielmijarra this is strange.. a helper and a helper util for something used only in one place? Please resend. Thx.

**Comment by danielmijarra** [comment]
Hi @brianchandotcom,
We need to read the `com.liferay.friendly.url.internal.configuration.FriendlyURLRedirectionConfiguration` (it's in a module) in _I18nFilter_ in `portal-impl` so we have to expose it somehow.
We add the _FriendlyURLRedirectionConfigurationHelper_ in `portal-kernel`, using _UploadServletRequestConfigurationHelper_ as a model, to expose this configuration to _I18nFilter_.

**Comment by robertoDiaz** [comment]
cc @adolfopa

**Comment by adolfopa** [comment]
@danielmijarra Can you resend the pr to Brian's repo adding your comment to the description? Thanks!

**Pull request closed without merging**
