### PR TITLE
COMMERCE-276

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:test

**Comment by ZoltanTakacs** [comment]
ci:retest

**Comment by ZoltanTakacs** [comment]
Hi @brianchandotcom ,

Please let me know if there is anything that needs to be modified within the component to pass the review and I'll resend it to you accordingly.

Thank you,
Zoli

**Comment by marco-leo** [comment]
ci:retest

**Comment by ZoltanTakacs** [comment]
ci:retest

**Comment by ZoltanTakacs** [comment]
Hi @brianchandotcom,

I know that you are busy with several things, but I wanted to check if there is anything that I should do with this PR to pass the review?

Thanks,
Zoli

/cc @marco-leo

**Comment by ZoltanTakacs** [comment]
ci:close
I'm closing this since I've made some changes which will collide with this one if something needs to be modified. I will resend to @Ithildir .

**Pull request closed without merging**
