### PR TITLE
LPS-76354

### PR DESCRIPTION
**Pull request by drewbrokke**
@drewbrokke Sending this through you since it seems more related to Users than Announcements, but let me know if you'd like to have this go elsewhere.

Based off of LPS-216, it seems the Website option should always be checked, however, we're depending on disabled checkboxes to achieve that. Instead, we should enforce this rule in the backend so that it never changes.

I would have liked to remove the entire Website option since I don't see the use for it but that requires a major version increase to portal-kernel which I'd like to avoid.

Let me know if you have any questions.

### CODE REVIEW

**Comment by drewbrokke** [comment]
@brianchandotcom the initial comment is from Jonathan's original pull.

**Comment by drewbrokke** [comment]
ci:test

**Comment by brianchandotcom** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b7180525a8...ddb21198bb

**Pull request closed without merging**
