### PR TITLE
LPS-54852 don't need this anymore

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
Please don't close this as I'm reviewing the issue.

On Thu, Jul 23, 2015 at 11:01 AM, Liferay Continuous Integration <
notifications@github.com> wrote:

> Some tests FAILED!
>
> Build Time: 34 minutes 21 seconds
> Job Results:
>
> 8 Jobs Passed.
> 5 Jobs Failed.
> See the following links for more information.
>
>    - test-portal-acceptance-pullrequest(master)
>    <https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest(master)/677/>
>
>    Completed with the status of FAILURE.
>
>     -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat-mysql/portal-smoke
>    <https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1341/>
>    - test-portal-acceptance-pullrequest-batch(master)/integration-mysql
>    <https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1326/>
>    - test-portal-acceptance-pullrequest-batch(master)/integration-oracle
>    <https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1327/> Job
>    Results:
>
>    6805 Tests Passed.
>    2 Tests Failed.
>     - CounterLocalServiceTest.testConcurrentIncrement
>       <https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=2,label_exp=!master/1327//testReport/com.liferay.counter.service/CounterLocalServiceTest/testConcurrentIncrement>
>       - PACLAggregateTest.testPACLTests
>       <https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=2,label_exp=!master/1327//testReport/com.liferay.portal.security.pacl/PACLAggregateTest/testPACLTests>
>     -
>    test-portal-acceptance-pullrequest-batch(master)/integration-postgresql
>    <https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1344/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql
>    <https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1309/> Job
>    Results:
>
>    2451 Tests Passed.
>    1 Test Failed.
>    - PortalLogAssertorTest.testScanXmlLog
>       <https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=14,label_exp=!master/1309//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXmlLog>
>     -
>    test-portal-acceptance-pullrequest-batch(master)/modules-integration-oracle
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1326/> Job
>    Results:
>
>    2436 Tests Passed.
>    16 Tests Failed.
>     - PortalLogAssertorTest.testScanXmlLog
>       <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=0,label_exp=!master/1326//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXmlLog>
>       - PortalLogAssertorTest.testScanXmlLog
>       <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=1,label_exp=!master/1326//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXmlLog>
>       - PortalLogAssertorTest.testScanXmlLog
>       <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=10,label_exp=!master/1326//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXmlLog>
>       - PortalLogAssertorTest.testScanXmlLog
>       <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=11,label_exp=!master/1326//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXmlLog>
>       - PortalLogAssertorTest.testScanXmlLog
>       <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=12,label_exp=!master/1326//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXmlLog>
>       - ConfigurationPersistenceManagerTest.testPortalPersistenceManager
>       <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=13,label_exp=!master/1326//testReport/com.liferay.portal.configuration.persistence.test/ConfigurationPersistenceManagerTest/testPortalPersistenceManager>
>       - PortalLogAssertorTest.testScanXmlLog
>       <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=13,label_exp=!master/1326//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXmlLog>
>       - PortalLogAssertorTest.testScanXmlLog
>       <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=14,label_exp=!master/1326//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXmlLog>
>       - PortalLogAssertorTest.testScanXmlLog
>       <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=2,label_exp=!master/1326//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXmlLog>
>       - PortalLogAssertorTest.testScanXmlLog
>       <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=3,label_exp=!master/1326//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXmlLog>
>       - PortalLogAssertorTest.testScanXmlLog
>       <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=4,label_exp=!master/1326//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXmlLog>
>       - PortalLogAssertorTest.testScanXmlLog
>       <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=5,label_exp=!master/1326//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXmlLog>
>       - PortalLogAssertorTest.testScanXmlLog
>       <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=6,label_exp=!master/1326//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXmlLog>
>       - PortalLogAssertorTest.testScanXmlLog
>       <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=7,label_exp=!master/1326//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXmlLog>
>       - PortalLogAssertorTest.testScanXmlLog
>       <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=8,label_exp=!master/1326//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXmlLog>
>       - PortalLogAssertorTest.testScanXmlLog
>       <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=9,label_exp=!master/1326//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXmlLog>
>     -
>    test-portal-acceptance-pullrequest-batch(master)/modules-integration-postgresql
>    <https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1331/> Job
>    Results:
>
>    2451 Tests Passed.
>    1 Test Failed.
>    - PortalLogAssertorTest.testScanXmlLog
>       <https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=14,label_exp=!master/1331//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXmlLog>
>     - test-portal-acceptance-pullrequest-batch(master)/modules-unit
>    <https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1314/> Job
>    Results:
>
>    956 Tests Passed.
>    1 Test Failed.
>    - SourceFormatterTest.testSourceFormatter
>       <https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=3,label_exp=!master/1314//testReport/com.liferay.source.formatter/SourceFormatterTest/testSourceFormatter>
>     - test-portal-acceptance-pullrequest-batch(master)/plugins
>    <https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1342/>
>    - test-portal-acceptance-pullrequest-batch(master)/portal-web
>    <https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1327/>
>    - test-portal-acceptance-pullrequest-batch(master)/tck
>    <https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1328/>
>    - test-portal-acceptance-pullrequest-batch(master)/unit
>    <https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/1345/>
>    - test-portal-acceptance-pullrequest-source(master)
>    <https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-source(master)/701/>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/28529#issuecomment-124133122>
> .
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
.. I hate oracle DB. Why does it have to be so complicated!

still working on this btw.

**Comment by brianchandotcom** [comment]
Thx @rotty3000 sorry about Oracle... if you need help, ping it to Shuyang.. I'm going to close it on my side so you can keep track of it in your set of pulls. Thx

**Pull request closed without merging**
