### PR TITLE
LPS-86550 As a Marketer I can display the a picture of the author of a web content in a Display Page

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by jkappler** [comment]
cc:// @brianchiu

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9dfd3c543a...651a36a28b

**Comment by brianchandotcom** [comment]
@jkappler see 01edbaa8f940cf14131800b04f02542d6017f541 thx.

**Pull request closed without merging**
