### PR TITLE
LPS-103252

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/69507a014e...a664bc730f

**Comment by brianchandotcom** [comment]
@hhuijser I think this was better before this pull:

modules/apps/adaptive-media/adaptive-media-image-impl/src/main/java/com/liferay/adaptive/media/image/internal/handler/AMImageRequestHandler.java

```
		Map<String, String> properties = new HashMap<>();

		AMAttribute<Object, String> fileNameAMAttribute =
			AMAttribute.getFileNameAMAttribute();
```

vs.

```
		AMAttribute<Object, String> fileNameAMAttribute =
			AMAttribute.getFileNameAMAttribute();

		Map<String, String> properties = new HashMap<>();
```

Note that the main object here is properties and not fileNameAMAttribute

when it's used by

"new AMImage"

May be we need a PropertiesBuilder?

**Comment by brianchandotcom** [comment]
@hhuijser I reverted this pull, can you resend.

**Comment by hhuijser** [comment]
Hey @brianchandotcom 

You were looking at the first commit only.

You can see that the code changed as following over two commits:

```
Map<String, String> properties = new HashMap<>();

AMAttribute<Object, String> fileNameAMAttribute =
    AMAttribute.getFileNameAMAttribute();

properties.put(
    fileNameAMAttribute.getName(), fileVersion.getFileName());
```

Then:

```
AMAttribute<Object, String> fileNameAMAttribute =
    AMAttribute.getFileNameAMAttribute();

Map<String, String> properties = new HashMap<>();

properties.put(
    fileNameAMAttribute.getName(), fileVersion.getFileName());
```
And then:
```
AMAttribute<Object, String> fileNameAMAttribute =
    AMAttribute.getFileNameAMAttribute();

Map<String, String> properties = HashMapBuilder.put(
    fileNameAMAttribute.getName(), fileVersion.getFileName()
).build();
```

**Pull request closed without merging**
