### PR TITLE
LPS-131629 fix openapi

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/241478c4d1...a615ccb9df

**Comment by brianchandotcom** [comment]
@hhuijser @ling-alan-huang can we auto SF so that

baseURI: "/headless-commerce-punchout"

always starts with a /

We are already programatically fixing this.

**Comment by nhpatt** [comment]
Thanks!

**Comment by brianchandotcom** [comment]
@nhpatt I backported this wall the way to 7.1.x. Thank you for the fix!

**Comment by ling-alan-huang** [comment]
@hhuijser I will work on it.

**Pull request closed without merging**
