### PR TITLE
LPS-60316 Do not update the created and modified date

### PR DESCRIPTION
**Pull request by marcellustavares**
cc @inacionery

### CODE REVIEW

**Comment by marcellustavares** [comment]
c:reopen

**Comment by marcellustavares** [comment]
Not related to the fix, other CI report can be found at https://github.com/marcellustavares/liferay-portal/pull/1720

thx

**Comment by marcellustavares** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
