### PR TITLE
LPS-57905 Retry if database was not successfully dropped

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
This is fixing the Sybase issue at https://github.com/brianchandotcom/liferay-portal/pull/32197

**Comment by brianchandotcom** [comment]
Thx guys!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8caaa491ba...5c26e85e88

**Comment by shuyangzhou** [comment]
@brandocomando broken postgresql install on cloud-10-0-110-223

**Pull request closed without merging**
