### PR TITLE
Lps 61524

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
CC @tinatian

**Comment by tinatian** [comment]
Hi Shuyang,

For "portal-scheduler-cluster", there is a bug I found yesterday, I have send a pull request to you, please see https://github.com/shuyangzhou/liferay-portal/pull/2166.

Since you have removed "portal-scheduler-cluster" from master, I should send this pull to ee-7.0.x right? Well, this fix needs to add back a class in portal-service, it will make the code of portal-service in ee-7.0.x different from ce master, is that OK?

Tina

**Comment by shuyangzhou** [comment]
Yes, send it to me on ee-7.0.x.

Does it have to stay in portal-service?

**Comment by tinatian** [comment]
No, it doesn't. Since it is a general tool for Clusterable annotation, I put it in portal-service in case others might need it.

I will send a new pull about this to you in ee-7.0.x

Tina.

**Comment by shuyangzhou** [comment]
Thanks @tinatian !

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/04c1deed99...a8635cb0ed

**Pull request closed without merging**
