### PR TITLE
Lps 150808 3 31 1

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@julschong @shuyangzhou we can't do this because we will use http-invoker in many more modules. The current one was just a tester. Please resend.

**Comment by shuyangzhou** [comment]
@brianchandotcom do you mean stuff like this https://github.com/liferay/liferay-portal/blob/master/modules/apps/object/object-admin-rest-client/src/main/java/com/liferay/object/admin/rest/client/http/HttpInvoker.java ?
For all the client modules we are generating the HttpInvoker embedded into the module.

**Comment by brianchandotcom** [comment]
@shuyangzhou Ah yes.. it's the same class, but for our use case, we need it not attached to a specific generated rest client jar. It'd be weird to depend on object-admin-rest-client. So I want to keep the petra-http-invoker (may be move the dir).

**Pull request closed without merging**
