### PR TITLE
LPS-53025 Fix adding default permissions for staging site when we check permissions on the live site, see AdvancedPermissionChecker

### PR DESCRIPTION
**Pull request by rotty3000**
Nice work @Preston-Crary!

### CODE REVIEW

**Comment by Preston-Crary** [comment]
:-)

**Comment by brianchandotcom** [comment]
Very nice @Preston-Crary 

Can you also apply this to Wiki and Polls? Those were abstracted out to modules, so that's why you didn't see them. Also, please check plugins as the same pattern would have been used there before.

Thx!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8b02cc6dfc...e178f279e4

**Comment by brianchandotcom** [comment]
@Preston-Crary @rotty3000 I also see it in Bookmarks as well, besides Polls and Wiki. Please check all modules and plugins. Thx.

**Pull request closed without merging**
