### PR TITLE
LPS-52679 Make Symbolic and packages be named the same

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6e95e6b831...3e42438c92

**Comment by brianchandotcom** [comment]
@csierra The ExtensionManager is referencing soap.extension. Is that correct or an accident  from copying the one from soap-extender?

Also, is soap-extender going away?

**Comment by csierra** [comment]
hey @brianchandotcom, 

that "soap.extension" property was named "cxf.extension" before, but it was renamed. Maybe now it makes more sense to name it "cxf.extension" again, since it is inside portal-cxf-common.

Regarding soap-extender it is not going away. In the next pull It will start using this cxf-common and dependency-manager-tccl. Later will come rest-extender that will also reuse them.

**Pull request closed without merging**
