### PR TITLE
LPS-89875 The "edit user" view's site role display shows roles assigned to groups that are not sites

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-89875](https://issues.liferay.com/browse/LPS-89875).<br><br>/cc @pei-jung @stsquared99 @alee8888 @ChrisKian

### CODE REVIEW

**Comment by drewbrokke** [comment]
cc @marco

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@ChrisKian @drewbrokke please backport. Thx.

**Comment by drewbrokke** [comment]
Backport pull: https://github.com/liferay/liferay-portal-ee/pull/12627

**Pull request closed without merging**
