### PR TITLE
Data Engine app.bnd description

### PR DESCRIPTION
**Pull request by rbohl**
cc @jpince @jeyvison - added LPS to the commit message.

### CODE REVIEW

**Comment by jpince** [comment]
@rbohl your text editor probably added the newline character at the end of the file by default, see https://github.com/brianchandotcom/liferay-portal/pull/72506/commits/02bfa0a82c88f80287cc8a5d66898f5b7d1846b8#diff-d4d222af9f60bf2df6d0dbf9dc845e61R15. Make sure that's removed before you resend.

**Comment by jpince** [comment]
ci:stop

**Comment by jpince** [comment]
@rbohl nevermind, didn't realize Jeyvison already sent the SF fix https://github.com/brianchandotcom/liferay-portal/pull/72507#issuecomment-488037336

**Comment by rbohl** [comment]
Yeah, sorry, I have to start sending myself a PR so I can sort out any SF issues out before I send the final pull.

**Comment by rbohl** [comment]
ci:test:sf

**Pull request closed without merging**
