### PR TITLE
LPS-59242 DLFileEntryTypeFinder

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@sergiogonzalez this pull is very weird. It's timed out twice, both on Sybase. I'm going to ci:retest it now. If it fails again.. then something is wrong with Sybase.

**Comment by robertoDiaz** [comment]
It's weird... the pull I sent to @sergiogonzalez didn't failed (see https://github.com/sergiogonzalez/liferay-portal/pull/2672) and he didn't introduce any changes.

I'm going to retest it again.

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Since it's failing, closing the pull for now until we found out the reason.

**Comment by robertoDiaz** [comment]
As @migue sugestion i've manually rebase the pull and resent it to https://github.com/brianchandotcom/liferay-portal/pull/31824

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
