### PR TITLE
LPS-84352 register and unregister are used by GlobalStartupAction and…

### PR DESCRIPTION
**Pull request by shuyangzhou**
… GlobalShutdownAction, no need to go through registry.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@shuyangzhou will this break:

modules/private/apps/oauth/oauth-web/src/main/java/com/liferay/oauth/web/internal/auth/publicpath/AuthPublicPath.java

and

modules/private/apps/saml/saml-addon-keep-alive-web/src/main/java/com/liferay/saml/addon/keep/alive/web/internal/auth/publicpath/AuthPublicPath.java

and

modules/private/apps/saml/saml-web/src/main/java/com/liferay/saml/web/internal/auth/publicpath/AuthPublicPath.java

They all register into auth.public.path. Please resend.

**Comment by shuyangzhou** [comment]
@brianchandotcom they are fine. They go through the OSGi way, I was only changing the portal ones that are register/unregister via GlobalStartupAction and GlobalShutdownAction. This won't affect the osgi ones.

**Comment by shuyangzhou** [comment]
ci:reopen

**Pull request closed without merging**
