### PR TITLE
LPS-76148 Missing unique message when attempting to make first page of site of type Link to URL

### PR DESCRIPTION
**Pull request by jkappler**
cc:// @pavel-savinov, @ealonso

### CODE REVIEW

**Comment by jkappler** [comment]
ci:reopen

**Comment by jkappler** [comment]
ci:retest

**Comment by jpince** [comment]
ci:stop

**Comment by jpince** [comment]
@jkappler looks fine, test failures are unrelated.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f9cf1c6063...f6d6dc9ebf

**Pull request closed without merging**
