### PR TITLE
master-qa-25725

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LRQA-25725
https://issues.liferay.com/browse/LRQA-25446

@brianchandotcom 
The first commit is an ignore for https://issues.liferay.com/browse/LPS-66314, which we believe is related to why the sybase upgrade tests fail. We're fairly certain that once https://issues.liferay.com/browse/LPS-66314 is resolved, the sybase upgrade error will also be resolved.

The second commit is a SF commit for a poshi file that I saw when running format-source, and didn't think it was necessary to send another pull just for that.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by kenjiheigel** [comment]
@alee8888, JBoss fails and has some weird start up issues:

>      [exec] [0m[33m19:47:52,036 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry lib/ant.jar in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/truezip.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:52,037 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry lib/lcrypto-jdk14-135.jar in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/truezip.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:52,057 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry jaxb-api.jar in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/jaxb-impl.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:52,057 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry activation.jar in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/jaxb-impl.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:52,058 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry jsr173_1.0_api.jar in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/jaxb-impl.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:52,058 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry jaxb1-impl.jar in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/jaxb-impl.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:52,099 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry unidataCommon-4.2.20.jar in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/netcdf.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:52,100 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry jcip-annotations-1.0.jar in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/netcdf.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:52,100 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry slf4j-api-1.6.1.jar in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/netcdf.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:52,100 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry commons-httpclient-3.1.jar in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/netcdf.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:52,100 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry commons-logging-1.0.4.jar in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/netcdf.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:52,100 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry commons-codec-1.2.jar in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/netcdf.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:52,114 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry xmpcore-5.1.2.jar in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/metadata-extractor.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:52,280 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry jaxws-api.jar in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/jaxws-rt.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:52,280 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry jsr181-api.jar in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/jaxws-rt.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:52,280 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry jsr250-api.jar in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/jaxws-rt.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:52,281 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry jsr173_api.jar in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/jaxws-rt.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:52,281 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry sjsxp.jar in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/jaxws-rt.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:52,281 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry woodstox.jar in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/jaxws-rt.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:52,281 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry resolver.jar in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/jaxws-rt.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:52,281 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry jaxb-api.jar in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/jaxws-rt.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:52,281 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry activation.jar in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/jaxws-rt.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:52,282 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry stax-utils.jar in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/jaxws-rt.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:52,294 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry jmf.jar,jdom.jar,jai_codec.jar,jai_core.jar in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/monte-cc.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:52,304 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry activation.jar in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/saaj-impl.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:52,309 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry mchange-commons-java-0.2.9.jar in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/c3p0.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:52,322 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry unoloader.jar in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/jurt.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:52,322 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry ../../lib/ in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/jurt.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:52,322 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry ../bin/ in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/jurt.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:52,352 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry commons-cli.jar in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/xuggle-xuggler-noarch.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:52,353 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry logback-classic.jar in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/xuggle-xuggler-noarch.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:52,353 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry logback-core.jar in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/xuggle-xuggler-noarch.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:53,312 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry jaxp-api.jar in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/saaj-api.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:53,312 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry jax-qname.jar in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/saaj-api.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:53,312 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry activation.jar in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/saaj-api.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:53,312 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry servlet.jar in /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/deployments/ROOT.war/WEB-INF/lib/saaj-api.jar  does not point to a valid jar for a Class-Path reference.
>      [exec] [0m[33m19:47:58,160 WARN  [org.jboss.as.ee] (MSC service thread 1-2) WFLYEE0007: Not installing optional component org.springframework.http.server.ServletServerHttpAsyncRequestControl due to an exception (enable DEBUG log level to see the cause)
>      [exec] [0m[33m19:47:58,168 WARN  [org.jboss.as.ee] (MSC service thread 1-2) WFLYEE0007: Not installing optional component org.springframework.web.context.request.async.StandardServletAsyncWebRequest due to an exception (enable DEBUG log level to see the cause)

@brianchiu, one of the sybase upgrades failed:

>      [exec] 20:02:36,041 ERROR [localhost-startStop-1][MainServlet:237] java.lang.RuntimeException: You must first upgrade to Liferay Portal 7001
>      [exec] java.lang.RuntimeException: You must first upgrade to Liferay Portal 7001
>      [exec] 	at com.liferay.portal.tools.DBUpgrader.checkRequiredBuildNumber(DBUpgrader.java:85)
>      [exec] 	at com.liferay.portal.events.StartupAction.doRun(StartupAction.java:190)
>      [exec] 	at com.liferay.portal.events.StartupAction.run(StartupAction.java:85)
>      [exec] 	at com.liferay.portal.servlet.MainServlet.processStartupEvents(MainServlet.java:1290)
>      [exec] 	at com.liferay.portal.servlet.MainServlet.init(MainServlet.java:234)
>      [exec] 	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
>      [exec] 	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1238)
>      [exec] 	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1151)
>      [exec] 	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1038)
>      [exec] 	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4997)
>      [exec] 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5289)
>      [exec] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
>      [exec] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
>      [exec] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
>      [exec] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
>      [exec] 	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:585)
>      [exec] 	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1794)
>      [exec] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>      [exec] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>      [exec] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>      [exec] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>      [exec] 	at java.lang.Thread.run(Thread.java:745)
>      [exec] Stopping the server due to unexpected startup errors
>      [echo] The following error occurred while executing this line:
>      [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:237: The following error occurred while executing this line:
>      [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:582: The following error occurred while executing this line:
>      [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:48: The following error occurred while executing this line:
>      [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:56: The following error occurred while executing this line:
>      [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:8188: The following error occurred while executing this line:
>      [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:2815: The following error occurred while executing this line:
>      [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:2907: The following error occurred while executing this line:
>      [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:3255: The following error occurred while executing this line:
>      [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:3419: Unable to find startup message after 15 minutes.
>       [get] Getting: http://test-1-15/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/8402//consoleText
>       [get] To: /opt/dev/projects/github/liferay-portal/20160603131645069.txt
>       [delete] Deleting: /opt/dev/projects/github/liferay-portal/20160603131645069.txt

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@pyoo47
See the earlier retest where sybase failed (and this time it passed).

It's possible the sybase database is dropping the connection randomly.

```
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.exception.SystemException: java.sql.SQLException: JZ006: Caught IOException: com.sybase.jdbc4.jdbc.SybConnectionDeadException: JZ0C0: Connection is already closed.
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:91)
     [java] 	at com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil._upgradeProcess(UpgradeProcessUtil.java:175)
     [java] 	at com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil.upgradeProcess(UpgradeProcessUtil.java:143)
     [java] 	at com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil.upgradeProcess(UpgradeProcessUtil.java:125)
     [java] 	at com.liferay.portal.events.StartupHelper.upgradeProcess(StartupHelper.java:164)
     [java] 	at com.liferay.portal.events.StartupHelperUtil.upgradeProcess(StartupHelperUtil.java:81)
     [java] 	at com.liferay.portal.tools.DBUpgrader.upgrade(DBUpgrader.java:153)
     [java] 	at com.liferay.portal.tools.DBUpgrader.main(DBUpgrader.java:99)
     [java] Caused by: com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.exception.SystemException: java.sql.SQLException: JZ006: Caught IOException: com.sybase.jdbc4.jdbc.SybConnectionDeadException: JZ0C0: Connection is already closed.
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:91)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:115)
     [java] 	at com.liferay.portal.upgrade.UpgradeProcess_7_0_0.doUpgrade(UpgradeProcess_7_0_0.java:75)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:88)
     [java] 	... 7 more
     [java] Caused by: com.liferay.portal.kernel.exception.SystemException: java.sql.SQLException: JZ006: Caught IOException: com.sybase.jdbc4.jdbc.SybConnectionDeadException: JZ0C0: Connection is already closed.
     [java] 	at com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl.processException(BasePersistenceImpl.java:264)
     [java] 	at com.liferay.counter.service.persistence.impl.CounterFinderImpl.createCounterRegister(CounterFinderImpl.java:235)
     [java] 	at com.liferay.counter.service.persistence.impl.CounterFinderImpl.createCounterRegister(CounterFinderImpl.java:195)
     [java] 	at com.liferay.counter.service.persistence.impl.CounterFinderImpl.getCounterRegister(CounterFinderImpl.java:266)
     [java] 	at com.liferay.counter.service.persistence.impl.CounterFinderImpl.increment(CounterFinderImpl.java:108)
     [java] 	at com.liferay.counter.service.persistence.impl.CounterFinderImpl.increment(CounterFinderImpl.java:99)
     [java] 	at com.liferay.counter.service.persistence.impl.CounterFinderImpl.increment(CounterFinderImpl.java:94)
     [java] 	at com.liferay.counter.service.impl.CounterLocalServiceImpl.increment(CounterLocalServiceImpl.java:42)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.lang.reflect.Method.invoke(Method.java:497)
     [java] 	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:153)
     [java] 	at com.liferay.portal.spring.transaction.CounterTransactionExecutor.execute(CounterTransactionExecutor.java:66)
     [java] 	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:58)
     [java] 	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:127)
     [java] 	at com.liferay.portal.spring.aop.ServiceBeanAopProxy.invoke(ServiceBeanAopProxy.java:173)
     [java] 	at com.sun.proxy.$Proxy64.increment(Unknown Source)
     [java] 	at com.liferay.counter.kernel.service.CounterLocalServiceUtil.increment(CounterLocalServiceUtil.java:251)
     [java] 	at com.liferay.portal.dao.db.BaseDB.increment(BaseDB.java:209)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.increment(UpgradeProcess.java:448)
     [java] 	at com.liferay.portal.upgrade.v7_0_0.UpgradeDocumentLibrary.updateFileEntryTypeDDMStructureLinks(UpgradeDocumentLibrary.java:280)
     [java] 	at com.liferay.portal.upgrade.v7_0_0.UpgradeDocumentLibrary.doUpgrade(UpgradeDocumentLibrary.java:105)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:88)
     [java] 	... 10 more
     [java] Caused by: java.sql.SQLException: JZ006: Caught IOException: com.sybase.jdbc4.jdbc.SybConnectionDeadException: JZ0C0: Connection is already closed.
     [java] 	at com.sybase.jdbc4.jdbc.ErrorMessage.createIOEKilledConnEx(ErrorMessage.java:1080)
     [java] 	at com.sybase.jdbc4.jdbc.ErrorMessage.raiseErrorCheckDead(ErrorMessage.java:1121)
     [java] 	at com.sybase.jdbc4.tds.Tds.handleIOE(Tds.java:5105)
     [java] 	at com.sybase.jdbc4.tds.Tds.handleIOE(Tds.java:5050)
     [java] 	at com.sybase.jdbc4.tds.Tds.doLogin(Tds.java:681)
     [java] 	at com.sybase.jdbc4.tds.Tds.login(Tds.java:577)
     [java] 	at com.sybase.jdbc4.jdbc.SybConnection.tryLogin(SybConnection.java:419)
     [java] 	at com.sybase.jdbc4.jdbc.SybConnection.handleHAFailover(SybConnection.java:3325)
     [java] 	at com.sybase.jdbc4.jdbc.SybConnection.<init>(SybConnection.java:345)
     [java] 	at com.sybase.jdbc4.jdbc.SybConnection.<init>(SybConnection.java:250)
     [java] 	at com.sybase.jdbc4.jdbc.SybDriver.connect(SybDriver.java:232)
     [java] 	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:307)
     [java] 	at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:200)
     [java] 	at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:708)
     [java] 	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:642)
     [java] 	at org.apache.tomcat.jdbc.pool.ConnectionPool.getConnection(ConnectionPool.java:185)
     [java] 	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:127)
     [java] 	at com.liferay.portal.dao.jdbc.util.DataSourceWrapper.getConnection(DataSourceWrapper.java:37)
     [java] 	at com.liferay.portal.dao.jdbc.util.RetryDataSourceWrapper.getConnection(RetryDataSourceWrapper.java:41)
     [java] 	at org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy$LazyConnectionInvocationHandler.getTargetConnection(LazyConnectionDataSourceProxy.java:403)
     [java] 	at org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy$LazyConnectionInvocationHandler.invoke(LazyConnectionDataSourceProxy.java:376)
     [java] 	at com.sun.proxy.$Proxy3.prepareStatement(Unknown Source)
     [java] 	at com.liferay.counter.service.persistence.impl.CounterFinderImpl.createCounterRegister(CounterFinderImpl.java:209)
     [java] 	... 32 more
```

**Pull request closed without merging**
