### PR TITLE
LRQA-37062 Add ability to deploy a socks proxy run running functional tests | master

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRQA-37062

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test

**Comment by brianwulbern** [comment]
ci:reopen

**Comment by michaelhashimoto** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
