### PR TITLE
LPS-93441 Using consistent naming. This controls visibility

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
@drewbrokke these are the changes we both agreed on slack.

Thanks!

**Comment by drewbrokke** [comment]
@4lejandrito LGTM 👍

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@4lejandrito good job catching NLP vs. NPL.. I should have seen that!

**Pull request closed without merging**
