### PR TITLE
LPS-122590 regen

### PR DESCRIPTION
**Pull request by albinojunior**

### CODE REVIEW

**Comment by albinojunior** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5575b50529...51182af423

**Comment by brianchandotcom** [comment]
@albinojunior hey, this is not sorted.

Can we fix the code that generated

```
class="data-record-document-field mb-2 btn-group"
```

Thx.

**Comment by albinojunior** [comment]
@brianchandotcom this code is generated automatically and is used to compare with the content of the rendered component. The order is correct in the component we created, but `<ClayButton.Group>` is adding the `btn-group` css class during rendering. However, the order will always be wrong when rendering because of the concatenation of the css classes.

**Comment by brianchandotcom** [comment]
@albinojunior can you show me where the code is?

**Comment by albinojunior** [comment]
@brianchandotcom you can see [here](https://github.com/brianchandotcom/liferay-portal/blob/51182af42354a47b172d7075fd080788c1a27d82/modules/apps/app-builder/app-builder-web/src/main/resources/META-INF/resources/js/pages/entry/FieldPreview.es.js#L100).

**Pull request closed without merging**
