### PR TITLE
LPS-91873 Update and use the path the test originally used

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @brianchiu @kyle-miho,

Maybe we need to adjust some poshi tests? or those are not related with this pull?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f6d836642e...062effaa42

**Comment by brianchiu** [comment]
@kyle-miho can you check it out

**Comment by kyle-miho** [comment]
@ealonso @brianchiu I don't know if this is a test fix or a bug. It seems like changes were made for the view in context / show abstract button, but I do not know how to get the button to show up. Only a "Read More" button shows up

**Comment by ealonso** [comment]
Hey @kyle-miho @brianchiu,

We removed the view in context button for the read more, but in this one I made another change to put it on the title, https://github.com/slnn/liferay-portal/pull/361, it should be the place now of the link.

If you want, you can update the tests on the top of that pull and send it to me, once we check the performance is ok I'll send it to Brian.

Regards,
Eudaldo.

**Pull request closed without merging**
