### PR TITLE
LPS-61049 Removes empty option

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by anthony-chu** [comment]
@ealonso do you know if taking out the showEmptyOption parameter causes the app-loaded data-qa-id not to load? portal smoke is failing because it is not able to assert that the specified portlet (Hello World portlet) has the app-loaded data-qa-id.

**Comment by ealonso** [comment]
@anthony-chu those changes should not affect to data-qa-id, I've only removed the empty option when we are creating new layouts of type "Full Page Application", "Link to a Page of This Site" and "Copy of a Page of This Site".

**Comment by ealonso** [comment]
ci:retest

**Comment by anthony-chu** [comment]
@ealonso the same tests failed between the retests.

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:stop

**Pull request closed without merging**
