### PR TITLE
LPS-59152 remove leading and trailing quotes from the search keywords

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@kiyoshilee This one too, lots of broken VMs.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/028c228665...6cc9cd6cf6

**Pull request closed without merging**
