### PR TITLE
LPS-73455

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-73455.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
@vicnate5 @ctampoya same test failures on both runs. Can you follow up on this? I asked @pyoo47 about the selenium errors, here's what he said:
> I suspect that an entry field that was meant to have data entered into it didn’t appear so a null pointer exception was throws. I’ll follow up with Leslie when he gets in.
> 
> Caused by: java.lang.NullPointerException
>  at com.liferay.poshi.runner.selenium.BaseWebDriverImpl.typeKeys(BaseWebDriverImpl.java:2816)
>  at com.liferay.poshi.runner.selenium.BaseWebDriverImpl.type(BaseWebDriverImpl.java:2691)

**Comment by vicnate5** [comment]
https://issues.liferay.com/browse/LRQA-33630

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2fe878d1d0...18a02222cb

**Comment by brianchandotcom** [comment]
Reverted for now per request from @jpince

**Comment by vicnate5** [comment]
@jonmak08 I am following up on the test failures so we can get this merged.

**Pull request closed without merging**
