### PR TITLE
LRQA-30007 | master

### PR DESCRIPTION
**Pull request by vicnate5**
https://issues.liferay.com/browse/LRQA-30007

@jpince @ctampoya

### CODE REVIEW

**Comment by vicnate5** [comment]
Sent to 7.0.x https://github.com/brianchandotcom/liferay-portal/pull/45998

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
