### PR TITLE
[7.1] LPS-82046 Updates AlloyEditor to v1.5.8

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @brianchandotcom, this includes a list of various issues regarding wysiwyg editors. We've tried to fix them holistically and provide better stability to the editors in general, so this is both good for 7.1 and necessary for 7.0 backports.

Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@jbalsas see 032a1c6

**Comment by jbalsas** [comment]
Thanks a lot @brianchandotcom, that's a great catch, I totally missed it :(

**Pull request closed without merging**
