### PR TITLE
LPS-93275 Merge existing Google Drive configurations

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:reopen 

Failures related to workflow.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e0a6f4fe06...00f56735bc

**Comment by brianchandotcom** [comment]
@adolfopa @4lejandrito see 00f56735bc01604a1ef4530c8c021316a2557867

**Pull request closed without merging**
