### PR TITLE
Lps 116452

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4e43e0d99a...aeaadd1ec0

**Comment by brianchandotcom** [comment]
@pavel-savinov @shuyangzhou I made a lot of tiny changes in my origin since this is a new pattern.

@jorgeferrer it's in

**Comment by JorgeFerrer** [comment]
👏

**Pull request closed without merging**
