### PR TITLE
LPS-61142 replace old custom message with the new component

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @jbalsas

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f056b12eec...29a476edef

**Comment by brianchiu** [comment]
@sharonchoi
See recycle bin flaky test (in the first set of results)

**Comment by sharonchoi** [comment]
@brianchiu ok, looking into it.

**Pull request closed without merging**
