### PR TITLE
LPS-61420 SF

### PR DESCRIPTION
**Pull request by Ithildir**
Hi,
I'm not sure, do you think these `Import-Package` should be formatted this way?

Thanks!

cc @hhuijser

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/dd74d7ce7a...87b90e3fa1

**Comment by brianchandotcom** [comment]
@hhuijser I like the formatting from @Ithildir 

Can you add it to SF?

**Comment by hhuijser** [comment]
@Ithildir @brianchandotcom 

What about having multiple -removeheaders on a single line? Should we do the same for those. We got a bunch of those?

Example: https://github.com/liferay/liferay-portal/blob/master/modules/sdk/project-templates-mvc-portlet/bnd.bnd#L5

**Comment by Ithildir** [comment]
@hhuijser, IMHO they should be on separate lines 😊

**Pull request closed without merging**
