### PR TITLE
LRDOCS-11330 Wordsmith the Breaking Changes Document

### PR DESCRIPTION
**Pull request by rbohl**
Hi Brian, I Wordsmithed the document and synced it with Liferay Learn's version, which had some additional entries since some engineers stopped updating the portal breaking changes. Talking with @mtokudome and @sez11a, we'd like to get rid of the version in Liferay Learn and instead find a way to include the liferay-portal version in the site build. We'll tackle that once you approve these changes. https://issues.liferay.com/browse/LRDOCS-11330

### CODE REVIEW

**Comment by rbohl** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8b0cf5bbf9...1e60db658d

**Comment by brianchandotcom** [comment]
Great idea @rbohl about having Learn grab this version.

**Comment by rbohl** [comment]
This PR in liferay-learn follows up on de-duplicating content between the repos: https://github.com/brianchandotcom/liferay-learn/pull/28

**Pull request closed without merging**
