### PR TITLE
LPS-74455

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Can you resend this as PATTERN_*

We should also start enforcing the var names for the Pattern class, to be *_PATTERN or *PATTERN_ (both are fine), but not *Pattern now since it's an immutable object, like String and int.

Thx

**Comment by hhuijser** [comment]
@petershin I found a bug in your fix.
We have classes that have private patterns with the same name. We can potentially grab the wrong pattern from the cache.

Example: _IMPORTS_PATTERN is in BNDImportsCheck, FTLImportsFormatter and GradleImportsFormatter

**Comment by petershin** [comment]
@hhuijser - Will add the class name to the key and rename the private variable names to start with _PATTERN_*

**Comment by hhuijser** [comment]
@petershin You should a method in BaseFileCheck. There you can grab the name of the class where the call came from.

**Comment by petershin** [comment]
@hhuijser - Isn't the key generated from the regex string and the flags though?

Even if multiple patterns have the same name, I think it'd be ok.

**Comment by hhuijser** [comment]
if they both don't have any flags, but the same string, it breaks. I had it happen.

**Comment by petershin** [comment]
@hhuijser - Will take a closer look.  If you're able to consistently reproduce the problem, please send me the steps to replicate the issue on my laptop.

**Comment by hhuijser** [comment]
@petershin, it doesn't make sense what I am saying. It's not passing the pattern name, but the regex string. You are right, it shouldn't matter. However, it's breaking for me. I'll have a look and see if I can reproduce.

**Comment by hhuijser** [comment]
@petershin, I realize it has nothing to do with the regex stuff. It's caused by https://github.com/liferay/liferay-portal/commit/20d04a1a9af2e472e9ea714ca72bd581a348d9bb
We talked about that last week. StringUtil.splitLines trims the string first, so that the first line loses the indentation. I will get a fix in for that.

**Pull request closed without merging**
