### PR TITLE
LPS-65605 Remove not supported upgrade processes properties

### PR DESCRIPTION
**Pull request by achaparro**
Hi @brianchandotcom,

This modification has been approved by @migue. Semantic versioning is not affected by the remove of these upgrade classes.

Thanks.

### CODE REVIEW

**Comment by pyoo47** [comment]
This pull request test has hit an intermittent portal issue and will remain frozen until it times out so I am going to ci:stop it so it can be retested.

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
This PR Test failed due to an issue with the temp-map functionality. ci:retest

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9d8833e88f...dc5e037a9b

**Pull request closed without merging**
