### PR TITLE
LPS-122562 Extract portlet preferences XML into separate preference table

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ec084fb83e...81dda4b224

**Comment by brianchandotcom** [comment]
I merged this. Great job on this monstrous pull.

1.) Can you rename all references of "copyTable" to "TEMP_TABLE"

Type:

git grep TEMP_TABLE

2.) 

Can you change:

```
		<column name="portletPreferencesId" type="long" />
		<column name="name" type="String" />
		<column name="index" type="int" />
		<column name="smallValue" type="String" />
		<column name="largeValue" type="String" />
		<column name="readOnly" type="boolean" />
```

to

```
		<column name="portletPreferencesId" type="long" />
		<column name="index" type="int" />
		<column name="name" type="String" />
		<column name="largeValue" type="String" />
		<column name="readOnly" type="boolean" />
		<column name="smallValue" type="String" />
```

This is our new pattern. PKs, then sort most of the stuff. Please update the hand coded SQL to match this new order too.

Great job @Preston-Crary !

**Comment by Preston-Crary** [comment]
Please see https://github.com/Preston-Crary/liferay-portal/pull/1264

**Pull request closed without merging**
