### PR TITLE
LPS-139352 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-139352

This is only for master.

@ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure case is unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/5879
✔️ ci:test:stable - 10 out of 10 jobs passed
❌ ci:test:relevant - 20 out of 22 jobs passed in 2 hours 18 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/642435ee6d...24d029ebac

**Comment by brianchandotcom** [comment]
@ealonso you call

```
			DDMTemplate ddmTemplate = _ddmTemplateLocalService.addTemplate(
				themeDisplay.getUserId(), serviceContext.getScopeGroupId(),
				_portal.getClassNameId(InfoItemFormProvider.class), 0,
				_portal.getClassNameId(InfoItemFormProvider.class), nameMap,
				Collections.emptyMap(),
				DDMTemplateConstants.TEMPLATE_TYPE_DISPLAY, StringPool.BLANK,
				TemplateConstants.LANG_TYPE_FTL, _getScript(), serviceContext);

			serviceContext = ServiceContextFactory.getInstance(
				TemplateEntry.class.getName(), actionRequest);

			TemplateEntry templateEntry =
				_templateEntryLocalService.addTemplateEntry(
```

Does this need to be in tx? I suppose it doesn't really matter. But to be accurate, you should extend BaseTransactionalMVCActionCommand

**Pull request closed without merging**
