### PR TITLE
Lps 68616

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @achaparro @migue

### CODE REVIEW

**Comment by brianchandotcom** [comment]
I had asked @shuyangzhou to redo LPS-68616 based on my comments here: https://github.com/brianchandotcom/liferay-portal/pull/46907#issuecomment-281457208

**Comment by achaparro** [comment]
Thanks @shuyangzhou, @brianchandotcom

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3a2001cab0...7992cafbdb

**Comment by brianchandotcom** [comment]
@achaparro this is merged up, I also changed 7992cafbdbc01d64d3a0100984fde5275b2be552 since this logic is now assumed to always be available.

**Comment by achaparro** [comment]
Hi @brianchandotcom,

Why did you finally revert latest commit https://github.com/liferay/liferay-portal/commit/920dcbf997905aeffdca12ec48de515ff72f30c7?

I asked this since I realized that the original code it's not working since runSQLTemplateString method expects ";" at the end of the line to execute the SQL:
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/dao/db/BaseDB.java#L425

So your modification should fix this error.

Thanks!

**Pull request closed without merging**
