### PR TITLE
LRQA-30908 Additional repository name rule.

### PR DESCRIPTION
**Pull request by pyoo47**

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:reopen

**Comment by kenjiheigel** [comment]
This auto closed due to a flaky Elastic Search issue. @alee8888 and the search team are aware.

Error:
```Portal log assert failure, see above log for more information: 
[com.liferay.portal.search.internal.SearchEngineHelperImpl(1067)] The addSearchEngineConfigurator method has thrown an exception 
java.lang.RuntimeException: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip
	at org.elasticsearch.plugins.PluginManager.findPluginRoot(PluginManager.java:430)
	at org.elasticsearch.plugins.PluginManager.extract(PluginManager.java:218)
	at org.elasticsearch.plugins.PluginManager.downloadAndExtract(PluginManager.java:128)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a148d2efe8...346b7beb00

**Comment by brianchandotcom** [comment]
Merged.

**Pull request closed without merging**
