### PR TITLE
LPS-71473 Don’t fail on empty config.json files

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
Retry of previous https://github.com/brianchandotcom/liferay-portal/pull/47848 which experienced problems with automatic testing.

**Comment by shinnlok** [comment]
fyi, you need to go to:

https://github.com/orgs/liferay/people?utf8=%E2%9C%93&query=Ivan%20Zaera

and change private to public

**Comment by izaera** [comment]
thx @shinnlok . Let's try again

**Comment by izaera** [comment]
ci:retest

**Comment by izaera** [comment]
there it is \o/

**Comment by izaera** [comment]
FYI: @jpince see the final solution in @shinnlok's comment 👍

**Comment by brianchandotcom** [comment]
@izaera !!!!!

**Comment by jpince** [comment]
huzzah! thanks @shinnlok

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
@brianchandotcom this should resolve the FrameworkEvent error at master head

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
