### PR TITLE
LPS-67730 Dynamic Item Selector Return Types for Item Selector Views

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @juliocamarero we have modified the item selector views for journal, layouts, and sites, but it's a pretty straightforward change.

**Comment by sergiogonzalez** [comment]
cc/ @robertoDiaz

**Comment by brianchandotcom** [comment]
modules-int* broken. Please resend.

**Comment by juliocamarero** [comment]
👍

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
