### PR TITLE
LPS-91730 Hover fragments on mouseenter/leave

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@p2kmgcl is this in some sort of alphabetical order?

```
import '../fragments/FragmentsEditorSidebarCard.es';
import {FRAGMENTS_EDITOR_ITEM_TYPES} from '../../../utils/constants';
import {focusItem, removeItem, setIn} from '../../../utils/FragmentsEditorUpdateUtils.es';
import {getConnectedComponent} from '../../../store/ConnectedComponent.es';
import {CLEAR_HOVERED_ITEM, REMOVE_FRAGMENT_ENTRY_LINK, REMOVE_SECTION, UPDATE_ACTIVE_ITEM, UPDATE_HOVERED_ITEM, CLEAR_ACTIVE_ITEM} from '../../../actions/actions.es';

```

Please send me a follow up pull. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6b682f7f03...fcfadaca28

**Pull request closed without merging**
