### PR TITLE
LPS-63179

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-63179.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/14ea794b27...f1375781cc

**Comment by brianchandotcom** [comment]
@mjbradford89 do we need to do this for CSS too?

					stringFileContent = MinifierUtil.minifyCss(
						stringFileContent);


Can the same thing happen?

**Comment by mjbradford89** [comment]
@brianchandotcom hmm I don't think so.  But I will look into it to make sure.

**Pull request closed without merging**
