### PR TITLE
LPS-77215 Sets compatibility to 1.8

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jpince** [comment]
@ithildir should the default be set to 1.8 now?

**Comment by jpince** [comment]
@jbalsas thanks! 3 app servers built succesfully so far (including tomcat), and BChan asked me to push this up.

**Comment by jpince** [comment]
Pushed upstream: https://github.com/liferay/liferay-portal/compare/3a6588782a914968a6ec9fbeb2187f1e1ba01dc3...3e8817ec03c2edf08f8c6ba61575357f909cd3ef

**Comment by jpince** [comment]
ci:close

**Comment by Ithildir** [comment]
Hi @jpince,
Last time I asked @rotty3000 about it, he said to keep the default to 1.7 to avoid a major version increase. Maybe we can do it when we bump up all major versions?

**Comment by jpince** [comment]
@rotty3000 Brian said he is [doing major version increases](https://loop.liferay.com/home/-/loop/feed/9434884) now, should we increase the default compatibility version to 1.8?

**Pull request closed without merging**
