### PR TITLE
LPS-83222 SF

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by jpince** [comment]
ci:close @rotty3000 lpkg test failure, looks related
```
index-modules-and-app-lpkgs:
     [java] Exception in thread "main" java.lang.NoClassDefFoundError: com/liferay/portal/kernel/util/URLCodec
     [java] 	at com.liferay.portal.target.platform.indexer.internal.TargetPlatformIndexer._addBundle(TargetPlatformIndexer.java:186)
     [java] 	at com.liferay.portal.target.platform.indexer.internal.TargetPlatformIndexer.index(TargetPlatformIndexer.java:117)
     [java] 	at com.liferay.portal.target.platform.indexer.internal.TargetPlatformIndexerUtil.indexTargetPlatform(TargetPlatformIndexerUtil.java:94)
     [java] 	at com.liferay.portal.tools.target.platform.indexer.client.TargetPlatformIndexerClient._indexTargetPlatform(TargetPlatformIndexerClient.java:183)
     [java] 	at com.liferay.portal.tools.target.platform.indexer.client.TargetPlatformIndexerClient._index(TargetPlatformIndexerClient.java:129)
     [java] 	at com.liferay.portal.tools.target.platform.indexer.client.TargetPlatformIndexerClient.main(TargetPlatformIndexerClient.java:94)
     [java] Caused by: java.lang.ClassNotFoundException: com.liferay.portal.kernel.util.URLCodec
     [java] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
     [java] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
     [java] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
     [java] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     [java] 	... 6 more
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:340: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1410: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:2232: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/modules/build-app.xml:148: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/modules/build-app.xml:568: Java returned: 1
      [get] Getting: http://test-1-10/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/209680//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20180709143753245.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20180709143753245.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null2009843418.properties
```

cc/ @mtambara @shuyangzhou

**Comment by yuhai** [comment]
Hi @rotty3000,

Sorry, the PR will cause the test failed. Could you please check the below PR? https://github.com/rotty3000/liferay-portal/pull/1408.

Regards,
Hai

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/61181

**Comment by yuhai** [comment]
Thanks, @shuyangzhou

**Pull request closed without merging**
