### PR TITLE
LPS-65534 javax.portlet.portlet.name property not specified in some WCM portlets

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:/ @juliocamarero

**Comment by juliocamarero** [comment]
👍

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1691e781fb...97bac52c68

**Pull request closed without merging**
