### PR TITLE
Lps 70390

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @migue

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/98fe4c6c95...0b7e5de005

**Comment by brianchandotcom** [comment]
@shuyangzhou documenting our conversation: can you just move the Filter  so it's under the test package? thx.

**Comment by shuyangzhou** [comment]
Sent at https://github.com/brianchandotcom/liferay-portal/pull/48117

**Comment by shuyangzhou** [comment]
@hhuijser do you think we can SF this to make all classes for a module are within the module's bnd package? Should not be difficult, right? Thanks!

**Comment by hhuijser** [comment]
@shuyangzhou, will work on that at some later point. Right now in the process of doing a major refactor of SF.

**Comment by shuyangzhou** [comment]
Thanks @hhuijser ! Take your time, this one is not urgent at all.

**Pull request closed without merging**
