### PR TITLE
LPS-72343 Permissions must be pre filters before facets are counted

### PR DESCRIPTION
**Pull request by arboliveira**
Authors: @BryanEngler @arboliveira
Reviewer: @arboliveira

cc/ @Brandizzi please see https://github.com/brianchandotcom/liferay-portal/pull/49964/commits/2f8ec1071587ccde48479c84b4e408a11d7a8a84 and https://github.com/brianchandotcom/liferay-portal/pull/49964/commits/f11dd86be8392cf5f2f7ba163fc8a2c849d0436d

cc/ @MarcellusTavares please see https://github.com/brianchandotcom/liferay-portal/pull/49964/commits/af344a114322768a342a75414010bc6cd5c4b4ac

https://issues.liferay.com/browse/LPS-72343

### CODE REVIEW

**Comment by jpince** [comment]
ci:reopen

**Comment by arboliveira** [comment]
Legitimate test failures. (`UserIndexerTest`) Closing the pull request; will fix and resend.

**Comment by arboliveira** [comment]
ci:reopen

**Comment by arboliveira** [comment]
Reopening - hadn't noticed same test failures showing up in pull requests elsewhere.

**Pull request closed without merging**
