### PR TITLE
LPS-74373 SF

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:reopen

**Comment by izaera** [comment]
@brianchandotcom, @hhuijser this is failing because of a new header we have defined for the bnd file. I have added a commit for the source formatter to declare such header, but the CI is still failing 😕. However, if I run formatSource in my local project, it doesn't complain.

Any hint on how to make this pass? Thx :-)

**Comment by jpince** [comment]
@izaera have you rebuilt recently? Either ant all or `../../../gradlew deploy` from `modules/util/source-formatter`. This usually resolves any differences between CI and local SF

**Comment by jpince** [comment]
ci:close

**Pull request closed without merging**
