### PR TITLE
LPS-61501 minor fixes for the staging bar

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @matethurzo

**Comment by juliocamarero** [comment]
pushed to upstream. cc @brianchandotcom since this was blocking the staging team.

**Comment by matethurzo** [comment]
Thanks Julio, I've sent an SF commit here with an other fix: https://github.com/brianchandotcom/liferay-portal/pull/34237

**Comment by juliocamarero** [comment]
Yep, sorry. I also pushed that one earlier. thanks!

**Pull request closed without merging**
