### PR TITLE
LPS-72359 Support PortletFileEntry in ItemSelector

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4976071cb2...b66fcdc2f2

**Comment by brianchandotcom** [comment]
Yikes, I shouldn't have merged this! Compile error. Reverting. Also, see my change to the javadocs

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
