### PR TITLE
#Ping LPS-56893 Fix. Use the right init.jsp

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/02c76204e8...9040f6318c

**Comment by brianchandotcom** [comment]
@sergiogonzalez I didn't want for the tests to finish.. I assume this fix works since it's only 1 line, and you put #ping on it

**Comment by sergiogonzalez** [comment]
Thanks @brianchandotcom I appreciate the speed :)

**Pull request closed without merging**
