### PR TITLE
LPS-89154 Auto

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by jpince** [comment]
@brianchiu @kyle-miho see test errors `Unable to register portal instance`

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:close

**Comment by brianchiu** [comment]
@ealonso Going to rerun this.

**Comment by ealonso** [comment]
@brianchiu it is a real bug, I'm going to check it. Thanks!!

**Comment by brianchiu** [comment]
@ealonso Got it. Thanks, Eudaldo!

**Pull request closed without merging**
