### PR TITLE
LPS-102399 Fixes generated tplFn in IE11 where 'with(values) { return values; }' could cause rendering issues

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:bundle

**Comment by jbalsas** [comment]
not sure what's wrong with SF... will resend

**Comment by jbalsas** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/79044

**Comment by jbalsas** [comment]
ci:stop

**Pull request closed without merging**
