### PR TITLE
LPS-108770 Fix import

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
cc: @adolfopa @cgoncas

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
ci:test:rreopen

**Comment by cgoncas** [comment]
ci:test:reopen

**Comment by cgoncas** [comment]
ci:reopen

**Comment by cgoncas** [comment]
Resend to @brianchandotcom with the cherry-picks: https://github.com/brianchandotcom/liferay-portal/pull/84747

**Pull request closed without merging**
