### PR TITLE
LPS-54421 Assert.fail Rule

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@cgoncas please review my changes. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d44f8ccb53...5f831fcf1e

**Pull request closed without merging**
