### PR TITLE
LPS-188162 APIApplicationPublisher

### PR DESCRIPTION
**Pull request by 4lejandrito**
Related ticket -> [LPS-186786](https://liferay.atlassian.net/browse/LPS-186786)
___
## Purpose of the PR
The PR contains the exposure of an interface that allows publishing and unpublish REST APIs based on the API Definitions of the headless builder.
It also contains the implementation of the interface.

For now, it only publishes applications without resources.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/73cf354855...e481e3c0d7

**Comment by brianchandotcom** [comment]
@LuismiBarcos @4lejandrito see changes in my origin. I'm not sure why we need the base test case that does this:

```
		Bundle testBundle = FrameworkUtil.getBundle(BaseTestCase.class);

		BundleContext bundleContext = testBundle.getBundleContext();

		for (Bundle bundle : bundleContext.getBundles()) {
			if (Objects.equals(
					bundle.getSymbolicName(),
					"com.liferay.headless.builder.impl")) {

				CompletableFuture<Void> completableFuture =
					_batchEngineUnitProcessor.processBatchEngineUnits(
						_batchEngineUnitReader.getBatchEngineUnits(bundle));

				completableFuture.join();
			}
		}
```

**Comment by 4lejandrito** [comment]
That deploys the MSODs so that they are available for the tests (APIAPPlication, APISort, etc...). The reason is because they are behind a feature flag and are therefore not created at startup.

**Pull request closed without merging**
