### PR TITLE
Lps 76018 petra xml compat

### PR DESCRIPTION
**Pull request by tomwang2011**
CC @shuyangzhou

Hi Brian, resending this after creating a new fake gradle cache version, it should fix the 

>      [echo] Exception in thread "main" java.lang.NoClassDefFoundError: com/liferay/util/xml/XMLUtil
>      [echo] 	at com.liferay.util.xml.XMLSafeReader.<init>(XMLSafeReader.java:25)
>      [echo] 	at com.liferay.portal.tools.service.builder.ServiceBuilder.<init>(ServiceBuilder.java:626)
>      [echo] 	at com.liferay.portal.tools.service.builder.ServiceBuilder.main(ServiceBuilder.java:222)
>      [echo] Caused by: java.lang.ClassNotFoundException: com.liferay.util.xml.XMLUtil
>      [echo] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)

error, thanks!

### CODE REVIEW

**Comment by tomwang2011** [comment]
ci:test

**Comment by tomwang2011** [comment]
ci:reopen SF failed on the fake gradle cache commit

**Comment by brianchandotcom** [comment]
@tomwang2011 please resend.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/665117d59d...4f4e6786b2

**Pull request closed without merging**
