### PR TITLE
LRQA-53878 Improving tc DeleteFormViewFieldFromObject

### PR DESCRIPTION
**Pull request by alexcandidos**

### CODE REVIEW

**Comment by alexcandidos** [comment]
Test results of this PR on my branch: https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1062110193

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b7b5c3c25c...64666bb659

**Comment by brianchandotcom** [comment]
@alexcandidos this is bad spacing:

```
		FormViewBuilder.fieldEllipsisDelete(fieldLabel = "Text");
		FormViewBuilder.validateDeleteUsedObjectMessage();
		FormViewBuilder.validateUsedFormView(formViewName = "My Form View 1");
		FormViewBuilder.validateUsedFormView(formViewName = "My Form View 2");
		FormViewBuilder.validateUsedTableView(tableViewName = "My Table View");
		FormViewBuilder.deleteButtonInDeleteFromObject();
		FormViewBuilder.validateNoFieldLabel(fieldLabel = "Text");
		FormViewBuilder.validateNoObjectFieldName(fieldName = "Text");

```

In general, where order MATTERS, add a line break.

So:

Xyz.setAaa
Xyz.setBbb

Xyz.validateAaa
Xyz.validateAbb

Xyz.doSomething

@alexcandidos  @manoelcyreno fyi

Please send a follow up pull to fix this. Thx.

**Comment by alexcandidos** [comment]
Line breaks added here https://github.com/brianchandotcom/liferay-portal/pull/86655. Thanks for the feedback @brianchandotcom ! :)

**Pull request closed without merging**
