### PR TITLE
LPS-110166 We need that call earlier for search to identify those fields as sortable.

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @brianchandotcom,

See https://github.com/brianchandotcom/liferay-portal/pull/86084/commits/fe187be611b7e3048d6c35f9e536fa7c42d3c981. 

We need that call earlier to identify those fields as sortabled. Otherwise [this call](https://github.com/liferay/liferay-portal/blob/da0c9128e9d46900a24d57e955f6465d11b5c1e4/portal-kernel/src/com/liferay/portal/kernel/search/DocumentImpl.java#L873) will return false and search won't be sorted by those fields.

I think I was the first because there is no cases of sorting by `String` fields which are not the `name`.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2647cbea8a...795860a1f8

**Comment by brianchandotcom** [comment]
@4lejandrito please add a test to ensure no one changes this in the future.

**Comment by 4lejandrito** [comment]
Will do, thanks!

**Comment by 4lejandrito** [comment]
See https://issues.liferay.com/browse/LPS-110230.

**Pull request closed without merging**
