### PR TITLE
LPS-69375 Update tests

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
cc @thiago-rocha

**Comment by pyoo47** [comment]
ci:stop

The pull request test hung because one of the jenkins servers crashed.

**Comment by pyoo47** [comment]
ci:retest

**Comment by marcellustavares** [comment]
ci:reopen

**Comment by marcellustavares** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
