### PR TITLE
LPS-65373 Unable to add users after defining Default User Association to Org Site

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-65373](https://issues.liferay.com/browse/LPS-65373).<br><br>Hey Brian, I wanted to get this fix in ASAP since it's blocking the ee module CI integration.  I will send a test in a subsequent pull.<br><br>/cc @pei-jung @shuyangzhou @jorgeferrer @michaelhashimoto

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/857de628dc...160baf1442

**Comment by brianchandotcom** [comment]
@drewbrokke @kenjiheigel Poshi tests may be real?

**Comment by kenjiheigel** [comment]
Appears to be a flaky test, as it's been passing (more or less) after this was merged: https://testray.liferay.com/home/-/testray/case_results/45369186

The way it failed is quite strange though as it seems to think that the user has been created already (based off the screenshot). It doesn't seem like it's leftover data from the previous test (as no user is added in that test). I wonder if a database wasn't deleted correctly on the server? 

@alee8888 @xbrianlee, any thoughts?

**Comment by xbrianlee** [comment]
It does seem like the environment wasn't cleaned correctly before this test ran. We'll keep an eye out for any more of these failures.

**Pull request closed without merging**
