### PR TITLE
LPS-77225 Apply new NavigationBar pattern to roles-admin-web

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test

**Comment by jpince** [comment]
@alee8888 lexicon change

**Comment by brianchandotcom** [comment]
Can you resend based after applying the same changes I made in LPS-77555? Thx.

**Comment by pei-jung** [comment]
Resent as https://github.com/brianchandotcom/liferay-portal/pull/54934

**Pull request closed without merging**
