### PR TITLE
LPS-63572 Rename methods

### PR DESCRIPTION
**Pull request by jbalsas**
Hey Brian,

I've applied the changes you asked for in https://github.com/brianchandotcom/liferay-portal/pull/36717#issuecomment-189403692. 

I've also removed the last SF commit. All the files in the `.task-cache` folder are auto-generated, so sorting the `config.json` file will have no effect. We can try improving the [tool we use](https://github.com/liferay/liferay-module-config-generator) so it sorts the result, but this option is not available at the moment.

Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@jbalsas rebase error, can you resend?

**Comment by jbalsas** [comment]
resent https://github.com/brianchandotcom/liferay-portal/pull/36902

**Pull request closed without merging**
