### PR TITLE
LPS-169222 Auto SF

### PR DESCRIPTION
**Pull request by seltong**

### CODE REVIEW

**Comment by seltong** [comment]
ci:reopen

**Comment by seltong** [comment]
Unrelated failures [here](https://github.com/liferay-objects/liferay-portal/pull/1392)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fc6ffc2f3e...c42e72c790

**Comment by brianchandotcom** [comment]
Great job @seltong

**Pull request closed without merging**
