### PR TITLE
LPS-88702 SF

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:relevant

@john-co

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/23a1eea558...3f7e69867a

**Comment by brianchandotcom** [comment]
@fortunatomaldonado @jbalsas see 6cc076eb467c732df6607ac7fe454a07778cf20a 14baaf1add3f2c9d803426121ad91085e2709fae and 3f7e69867aa6bf0a852c7a016e0269f0d55039e8

**Comment by brianchandotcom** [comment]
@fortunatomaldonado also, if you call favicon with parameters/ a query string, your logic will break.

**Comment by brianchandotcom** [comment]
@fortunatomaldonado come find me so I can explain to you why the logic is broken.

**Comment by fortunatomaldonado** [comment]
@brianchandotcom okay, will come over now.

**Pull request closed without merging**
