### PR TITLE
LPS-65153 Redeploy of com.liferay.portal.search.elasticsearch makes Search unusable

### PR DESCRIPTION
**Pull request by arboliveira**
Re-sending https://github.com/brianchandotcom/liferay-portal/pull/39362#issuecomment-217446486 with an extra commit to deflake `FacetedSearcherTest.testSearchByKeywordsIgnoresInactiveSites` (works on my machine, breaks on CI) and more helpful assertion output in case it's still flaky.

Authors: @arturbr @arboliveira
Reviewer: @arboliveira

### CODE REVIEW

**Comment by arboliveira** [comment]
Failures seem unrelated. Identical to other pulls:
https://github.com/brianchandotcom/liferay-portal/pull/39581#issuecomment-218145122 
https://github.com/brianchandotcom/liferay-portal/pull/39590#issuecomment-218196692

**Comment by arboliveira** [comment]
Rebased on latest master.

ci:retest

**Comment by vicnate5** [comment]
Forms and Calendar Failures are unrelated. See https://github.com/brianchandotcom/liferay-portal/pull/39678.

**Comment by arboliveira** [comment]
Rebased on latest master.

ci:retest

**Comment by arboliveira** [comment]
Rebased on latest master.

ci:retest

**Comment by arboliveira** [comment]
Rebased on latest master.

ci:retest

**Comment by arboliveira** [comment]
Test failures seem unrelated.

**Comment by brianchandotcom** [comment]
@arboliveira I just had a chance to look at this pull

1.) Can you move test utils to *.test.util.* I think that's how it's done in other modules. Please double check.

2.) For things that return *Path[] can you rename the method to be getXyzPaths? This should be true for other complex objects other than java.util.List. In that case, if it's a List<Bob>, then the method will be getBobs().

Thx @arboliveira

**Pull request closed without merging**
