### PR TITLE
LPS-110469 Temporarily expose com.liferay.portal.kernel.service.persi…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…stence via bootdelegation. This is fixing release blocker caused by 6cd88061c455de707d0c83eba644b0b55b8745e1. That commit introduced a hidden dependency from com.liferay.portal.kernel.service to com.liferay.portal.kernel.service.persistence, which is not allowed by jdk11 during dynamic proxy creation. A proper right fix is simply to re-run the bnd processes for all modules to update the package imports, but considering we are already published all modules, using this hack as a workaround. Befcore next release publication, this MUST be reverted.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
CC @vicnate5

**Comment by shuyangzhou** [comment]
@preston-crary please remember to clean this up before next release, we do not want to carry on this hack for a long time.

**Comment by shuyangzhou** [comment]
@brianchandotcom you just need to re-publish portal-impl, then the blocker will be fixed.

**Comment by brianchandotcom** [comment]
ok, on it

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6eb0dcfd25...631f4f2611

**Comment by Preston-Crary** [comment]
@shuyangzhou I think we might be able to remove the "com.liferay.expando.kernel.model" one too.

**Comment by shuyangzhou** [comment]
yeah, that might be added for a similar reason. Anyway, just remember to do a scan and cleanup at some point after this release.

**Pull request closed without merging**
