### PR TITLE
Lps 170774

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
@111Anna this should have a very noticeable improvement

**Comment by 111Anna** [comment]
Hi @shuyangzhou, Yes, the startup time has been significantly improved, here is the test result:

Portal Version|GitId|Average Startup (ms)|%|Average Shutdown (ms)|%|Open File|Thread Create|Open  Prepared Statement|Open  SQL
--|--| --|--|--|--|--|--|--|--|
Baseline| 0d57d3e | 27916 |- |5539.3 |-| 1820 | 100 | 724 | 1141 |
Baseline+PR-127441 | - | 26993 |3.42%| 5378.6|2.99%| 1819 | 102 | 726 | 1140 |

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/19ee55abfc...cd54092810

**Comment by brianchandotcom** [comment]
@shuyangzhou fyi cd54092810588b0c14d8956c8c223a0673dac470

VERY nice job guys.

**Pull request closed without merging**
