### PR TITLE
LPS-87351 Journal doesn't validate file links to pdfs with an anchor to a page

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso, @pavel-savinov

**Comment by jkappler** [comment]
@brianchiu, @kyle-miho, this seems to be a common failure, but I'm not sure since we also touch export/import in this PR

**Comment by kyle-miho** [comment]
@jkappler I think this pull should be fine. Those failures are upstream. Usually, if you see "This pull contains no unique failures", we can be mostly sure this pull is relatively safe, because the git sha with this pull has the same failures as the upstream/master git sha.

**Comment by jkappler** [comment]
Ni @kyle-miho! Thanks!

**Comment by brianchandotcom** [comment]
@jkappler I agree with your decouping revert in 5bd1fd5dc3ed01a2b79e83e7d1c0612afe07e182
1b1b8ed64880734588388ca999b48d4a5dad6098

@robertoDiaz fyi

**Comment by ealonso** [comment]
cc: @matethurzo

**Pull request closed without merging**
