### PR TITLE
LPS-66986 SF - Reorder service.xml finders

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:retest

**Comment by adolfopa** [comment]
ci:retest

**Comment by adolfopa** [comment]
ci:retest

**Comment by adolfopa** [comment]
Rebased and push-forced. ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@adolfopa servicebuilder and other tests still seem to fail. Please resend. Thx.

**Pull request closed without merging**
