### PR TITLE
LPS-108633 SF - Rename test class

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@adolfopa test error.

**Comment by brianchandotcom** [comment]
@adolfopa 

```
Test Result (3 failures / +3)com.liferay.depot.internal.security.permissions.test.DepotPermissionCheckerWrapperTest.testIsGroupAdminWithDepotGroupAndDepotAdmincom.liferay.depot.internal.security.permissions.test.DepotPermissionCheckerWrapperTest.testIsGroupMemberWithDepotGroupAndDepotAdmincom.liferay.depot.internal.security.permissions.test.DepotPermissionCheckerWrapperTest.testIsGroupOwnerWithDepotGroupAndDepotAdmin
--


```

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/85401

**Pull request closed without merging**
