### PR TITLE
LPS-89229 Update alloy-editor to v1.5.19

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test

**Comment by julien** [comment]
ci:reopen

**Comment by julien** [comment]
/cc @jpince could you please help me identify what went wrong with this PR when you have a chance please?

Thanks

**Comment by julien** [comment]
@jpince ok thanks!

**Comment by brianchandotcom** [comment]
@julien please backport. Thx.

**Pull request closed without merging**
