### PR TITLE
LPS-61225 Fix dialog title

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c8afaa3690...b2b7c67f0e

**Comment by brianchandotcom** [comment]
@matethurzo I'm just going to merge this in.. hope no poshi errors

**Comment by matethurzo** [comment]
Thanks @brianchandotcom it's shouldn't break any poshi tests, but I'll keep an eye on it.

**Pull request closed without merging**
