### PR TITLE
LPS-104627 | master

### PR DESCRIPTION
**Pull request by liulukiwi**
https://issues.liferay.com/browse/LPS-104627

cc @ealonso

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@liulukiwi can you resend.. see https://github.com/brianchandotcom/liferay-portal/pull/81351

**Comment by brianchandotcom** [comment]
@ealonso rebase error from https://github.com/brianchandotcom/liferay-portal/pull/81351

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by liulukiwi** [comment]
resend:
https://github.com/brianchandotcom/liferay-portal/pull/81391

**Comment by ealonso** [comment]
see: https://github.com/brianchandotcom/liferay-portal/pull/81396

**Pull request closed without merging**
