### PR TITLE
LPS-106620 Change action command names from segments-experiment-web

### PR DESCRIPTION
**Pull request by dgarciasarai**
Follow up PR from https://github.com/brianchandotcom/liferay-portal/pull/83807#issuecomment-578959751

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
/segments_experiment/delete_rel 

that looks wrong

compare with

/segments_experiment/edit_segments_experiment

let's spell everything out.

**Comment by dgarciasarai** [comment]
Resent here https://github.com/brianchandotcom/liferay-portal/pull/83899

**Pull request closed without merging**
