### PR TITLE
LPS-53916 Blogs caption

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Resend of https://github.com/brianchandotcom/liferay-portal/pull/24585

Hey Brian, 

Tests are failing but they don't seem to be related to these changes.
Actually the are failing randomly, after every execution different tests failed.

Sergio

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @robertoDiaz @ambrinchaudhary

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Hey Brian, 

Tests are failing but they don't seem to be related to these changes.
Actually the are failing randomly, after every execution different tests failed.

Sergio

**Comment by brianchandotcom** [comment]
Can you resend but put coverImageCaption above coverImageFileEntryId (basically, let's sort coverImage*)

We know about the random OSGi related tests failing and are working on getting them more robust.

**Pull request closed without merging**
