### PR TITLE
LPS-143547

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
@brianchandotcom please publish SF

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/491fa5efe2...e443f58722

**Comment by brianchandotcom** [comment]
Publishing, thanks @hhuijser !

**Pull request closed without merging**
