### PR TITLE
LPS-73080 Fix Japanese translations

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @tsubasahomma

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/580d4212b5...7584261380

**Comment by brianchandotcom** [comment]
@tsubasahomma please backport.

**Comment by tsubasahomma** [comment]
Hi @brianchandotcom, I just sent https://github.com/ZoltanTakacs/liferay-portal-ee/pull/3070 for the backport. Thank you.

**Pull request closed without merging**
