### PR TITLE
LPS-53373 Add assign Default Portlet Data Handler when portlet does not declare one.

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
Hi @rotty3000,

I wasn't able to reproduce the test failure in brianchandotcom/liferay-portal/pull/24104 locally, so I sent this PR to Brian to check if the CI reproduced it. It seems all tests pass and I haven't performed any changes in my code from the previous pull request, so it seems it was not related to my changes after all :-)

Thanks!

**Comment by brianchandotcom** [comment]
Why is this code needed? See PortletLocalServiceImpl

```
		String portletDataHandlerClass = GetterUtil.getString(
			portletElement.elementText("portlet-data-handler-class"),
			portletModel.getPortletDataHandlerClass());

		if (Validator.isNull(portletDataHandlerClass)) {
			portletDataHandlerClass =
				DefaultConfigurationPortletDataHandler.class.getName();
		}

		portletModel.setPortletDataHandlerClass(portletDataHandlerClass);
```

We already default it. So the if else check you put in PortletBagFactory

```
String portletDataHandlerClass = portlet.getPortletDataHandlerClass();

		if (Validator.isNull(portletDataHandlerClass)) {
			portletDataHandlerClass =
				DefaultConfigurationPortletDataHandler.class.getName();
		}
```

Can never be reached. I think the only part of your code that is useful is 

```
		Map<String, Object> properties = new HashMap<>();

		properties.put("service.ranking", Integer.MIN_VALUE);

		portletDataHandlerInstances.add(portletDataHandlerInstance, properties);
```

Please resend.

Thx.

**Comment by rotty3000** [comment]
It's because in the case of OSGi portlets we never default classes since
instances are supposed to be published as services.

In most cases this is fine because we ignore the case where a portlet
doesn't have some impls...

However, I'm guessing that export/import needs an PDH impl. So why doesn't
it just provide it's own fallback to handle this case? Seems like business
logic to me!

**Comment by epgarcia** [comment]
Hey @brianchandotcom,

The if clause in the PortletBagFactory is redundant for legacy portlets (those deployed through the PortletContextListener - PortletHotDeployListener mechanism), because they pass through the PortletLocalServiceImpl logic. 

But OSGi portlets (those deployed through the PortletServiceTracker) do not pass through the PortletLocalServiceImpl logic and that's why LPS-53373 has been reported for the RSS portlet. It's indeed a regression caused by the modularization of the RSS portlet.

As Ray said, the non-explicit-PDH-declared case could be handled by the Export/Import logic in other ways, but I just thought that this approach was more consistent with the current one (i.e. the one in PortletLocalServiceImpl for legacy portlets). 

@juliocamarero, @matethurzo any thoughts?

Thanks

**Comment by matethurzo** [comment]
Hey guys,

In the meantime @danielkocsis started to change all the Portlet and StagedModelDataHandlers to make OSGi compatible and registered as normal OSGi services and one of his changes is overlapping with this , basically he deprecates this part completely. So in the future the different data handlers would be registered as services, independently from this.

Now thinking about it in the longer run I think it would be probably more easy to handle this is the staging scope instead of here, it's more localized and controllable for us.

Is it ok @epgarcia if I let Dani know about this and he can test his changes against this issue as well and he can solve it?

Thanks,

Máté

**Comment by epgarcia** [comment]
Hi @matethurzo,

Sure, I think it's better if he review it in the context of his long term changes. I'll assign the ticket to him.

Thanks!

**Comment by matethurzo** [comment]
Thank you!

**Pull request closed without merging**
