### PR TITLE
LPS-66570 is ActiveGroup to consider staging

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
The tests are falling because we executing some tests with ee modules from ee-7.0.x and we cannot change its module version dependences.
For example **com.liferay.portal.security.audit.storage.api** is a ee module:
````
   [java] 15:10:28,874 INFO  [main][BundleStartStopLogger:35] STARTED com.liferay.portal.language.extender_2.0.2 [45]
     [java] 15:10:28,879 ERROR [main][ModuleFrameworkImpl:1375] Unable to start bundle com.liferay.portal.security.audit.web
     [java] org.osgi.framework.BundleException: Could not resolve module: com.liferay.portal.security.audit.web [46]
     [java]   Unresolved requirement: Import-Package: com.liferay.portal.security.audit.storage.comparator; version="[1.0.0,2.0.0)"
     [java]     -> Export-Package: com.liferay.portal.security.audit.storage.comparator; bundle-symbolic-name="com.liferay.portal.security.audit.storage.api"; bundle-version="1.0.2"; version="1.0.0"; uses:="com.liferay.portal.kernel.util"
     [java]        com.liferay.portal.security.audit.storage.api [123]
     [java]          Unresolved requirement: Import-Package: com.liferay.portal.kernel.model; version="[1.0.0,1.1.0)"
     [java] 
     [java] 	at org.eclipse.osgi.container.Module.start(Module.java:429)
     [java] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
     [java] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:421)
     [java] 	at com.liferay.portal.bootstrap.ModuleFrameworkImpl._startDynamicBundles(ModuleFrameworkImpl.java:1372)
     [java] 	at com.liferay.portal.bootstrap.ModuleFrameworkImpl.startFramework(ModuleFrameworkImpl.java:415)
     [java] 	at com.liferay.portal.module.framework.ModuleFrameworkUtilAdapter.startFramework(ModuleFrameworkUtilAdapter.java:99)
     [java] 	at com.liferay.portal.util.InitUtil.initWithSpring(InitUtil.java:212)
     [java] 	at com.liferay.portal.util.InitUtil.initWithSpring(InitUtil.java:183)
     [java] 	at com.liferay.portal.tools.DBUpgrader.main(DBUpgrader.java:101)
     [java] 15:10:28,945 INFO  [Refresh Thread: Equinox Container: 703a560a-8c4e-0016-1728-fbfc144f1ce1][BundleStartStopLogger:35] STARTED com.liferay.portal.remote.soap.extender_2.0.2 [47]
     [java] 15:10:29,034 ERROR [main][ModuleFrameworkImpl:1375] Unable to start bundle com.liferay.portal.workflow.kaleo.designer.api
     [java] org.osgi.framework.BundleException: Could not resolve module: com.liferay.portal.workflow.kaleo.designer.api [48]
     [java]   Unresolved requirement: Import-Package: com.liferay.portal.kernel.model; version="[1.0.0,1.1.0)"
     [java] 
     [java] 	at org.eclipse.osgi.container.Module.start(Module.java:429)
     [java] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
     [java] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:421)
     [java] 	at com.liferay.portal.bootstrap.ModuleFrameworkImpl._startDynamicBundles(ModuleFrameworkImpl.java:1372)
     [java] 	at com.liferay.portal.bootstrap.ModuleFrameworkImpl.startFramework(ModuleFrameworkImpl.java:415)
     [java] 	at com.liferay.portal.module.framework.ModuleFrameworkUtilAdapter.startFramework(ModuleFrameworkUtilAdapter.java:99)
     [java] 	at com.liferay.portal.util.InitUtil.initWithSpring(InitUtil.java:212)
     [java] 	at com.liferay.portal.util.InitUtil.initWithSpring(InitUtil.java:183)
     [java] 	at com.liferay.portal.tools.DBUpgrader.main(DBUpgrader.java:101)
     [java] 15:10:29,037 INFO  [main][BundleStartStopLogger:35] STARTED com.liferay.portal.language.servlet.filter_2.0.2 [49]
     [java] 15:10:29,038 INFO  [main][BundleStartStopLogger:35] STARTED com.liferay.portal.settings.lang_1.0.3 [50]
     [java] 15:10:29,116 INFO  [main][BundleStartStopLogger:35] STARTED com.liferay.portal.scripting.ruby_2.0.5 [51]

**Comment by brianchandotcom** [comment]
@juliocamarero CI errors. Please resend.

**Comment by michaelhashimoto** [comment]
@brianchandotcom @jorgediaz-lr @shuyangzhou @pyoo47

I think we need to put a gatekeeper on that module.

Here's how we had to fix it for 'clustering' and 'caching':
https://github.com/brianchandotcom/liferay-portal-ee/pull/13440

Basically you need to:
<ol>
<li>Include a new <b>'ModulePortalProfile.java'</b> class that sets the 'PortalProfile' type. (In your case it'd probably be 'PORTAL_PROFILE_NAME_DXP')</li>
<li>Include all classes within your module that have an <b>@Component</b> to be marked within the 'ModulePortalProfile'.</li>
<li>Set <b>'enabled=false'</b> in all classes with <b>@Component</b></li>
</ol>

This should make it so that your module will only be loaded when running in DXP, even though it's been deployed.

I don't fully understand what is going on when this happens, so please put any questions you may have in here.  @shuyangzhou might know that answer.

Sorry it's so brief.. I'll try to post more information later.

Thanks!

**Comment by jorgediaz-lr** [comment]
After some investigations, I found following Jira tickets:
  - https://issues.liferay.com/browse/LRQA-22944
  - https://issues.liferay.com/browse/LRQA-25498

That LRQA tickets confirms that ee-7.0.x code is tested agains master, but the point is that this pull will break ee-7.0.x tests as we are changing `com.liferay.portal.kernel.model` package version

**Pull request closed without merging**
