### PR TITLE
LPS-85794 Avoid creating an unnecessary listener when the component doesn't exists

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
@brianchiu, not related to the PR. I've seen this error in other PR

**Comment by jkappler** [comment]
@jpince, this is happening in several pulls I believe

**Comment by brianchandotcom** [comment]
@jbalsas see these errors? Why is NPM constantly flaky like this? Or am I reading it wrong?

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by jbalsas** [comment]
I 'd say that during one of last weeks pushes and reverts, we have likely corrupted the CI cache for this module. @jpince?

**Comment by jpince** [comment]
@brianchandotcom @jkappler yes, it's an intermittent issue that we're looking into

**Pull request closed without merging**
