### PR TITLE
LPS-52240

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by mhan810** [comment]
ci:retest

**Comment by mhan810** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
So weird that the tests keep breaking? ci:retest

**Comment by mhan810** [comment]
Yea, what's odd is no one is even calling these new methods yet.  This is just an infrastructure commit.  It seems to be random modules running in arquillian :(

**Pull request closed without merging**
