### PR TITLE
LPS-119446

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
Unrelated failures only: https://github.com/hhuijser/liferay-portal/pull/5743

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7c69128e7c...f6b43a66e2

**Comment by brianchandotcom** [comment]
@hhuijser can you remove the "build" method all together so no one ever uses it?

**Pull request closed without merging**
