### PR TITLE
LPS-74452

### PR DESCRIPTION
**Pull request by jbalsas**
We've been getting a few support tickets recently where end users have aggressive caching *load balancers* (which in this case are essentially serving as a proxy), which is what motivates [LPS-74452](https://issues.liferay.com/browse/LPS-74452). Since it's happened more than once, it makes sense to me to try to at least change it for a future release, but an open question is whether we should also include it for past releases.

### CODE REVIEW

**Comment by jbalsas** [comment]
closed, missing breaking changes entry. will resend

**Comment by jbalsas** [comment]
ci:close

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cc511e61e7...98f5dea6ff

**Pull request closed without merging**
