### PR TITLE
LPS-139865 Fix PagintationBarTag server side rendering

### PR DESCRIPTION
**Pull request by john-co**
Manually forwarding since test failures are unrelated: https://github.com/liferay-frontend/liferay-portal/pull/1501#issuecomment-928496799

cc/ @julien

----

The PagintationBarTag wasn't rendering exactly the same html
as it's corresponsing Clay component, this change fixes that.

**Test plan**:
- Fetch this branch
- Deploy the `frontend-taglib-clay` OSGi module
- Assert that the PaginationBarTag renders the same html
  as the Clay component

### CODE REVIEW

**Comment by john-co** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/95d0574a67...85ebfa180b

**Comment by brianchandotcom** [comment]
@julien the variables name don't seem consistent

lastIndex, rightBufferStart, leftBufferEnd -> these all seem to be indexes to me.

itemsToRender, rightBuffer, leftBuffer -> they seem to be the same thing but all have different naming schemes. Please resend.

@john-co fyi

**Comment by brianchandotcom** [comment]
@julien we also need a test for this, or else if someone changes the JS... the JSP will once more be out of sync.

@jbalsas this breaks DRY.. we need a better solution for this.

**Comment by julien** [comment]
@brianchandotcom thanks, I will rename those variables. Concerning the tests, I'll investigate on what can be done.

**Comment by julien** [comment]
Hi again @brianchandotcom,

Concerning the tests, I (along with the other members of the team) agree that ideally this is something we should have, but it's not the case. With React we have no way to render our (JavaScript) components from the server, and to avoid a [flash of unstyled content](https://en.wikipedia.org/wiki/Flash_of_unstyled_content), we decided that we would render the minimum markup required from the tag to avoid those "visual glitches". This means that the markup generated by the tag is never exactly the same markup as the one generated by the tag's corresponding React component, once the JavaScript component has loaded, for example interactive elements don't have the same behavior or children. Building this infrastructure would require a lot of work and we don't think it would be worth the effort. This is something we discussed when switching away from metal.js+soy to React and we still have the same opinion today.

**Pull request closed without merging**
