### PR TITLE
LPS-68289 Fix the lock locking race condition and remove the debug ou…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…tput, but keeping the timeout test rule for a bit longer time, just in case.

CC @tinatian

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@tinatian this pull too.

**Comment by tinatian** [comment]
@brianchandotcom OK, got it.

**Comment by tinatian** [comment]
@brianchandotcom  See backport here: https://github.com/brianchandotcom/liferay-portal-ee/pull/15194

**Pull request closed without merging**
