### PR TITLE
LPS-101720 more obvious name and location?

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test:relevant

**Comment by csierra** [comment]
ci:test:stable

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6445f8a2cc...f11e0432d4

**Comment by brianchandotcom** [comment]
Nice job @csierra 

You'll want to change the reference to

/mfa/send_email_otp

in your next pull to match your other changes.

Thanks for upping your game in attention to details. Much appreciated! This pull was much easier to review.

**Pull request closed without merging**
