### PR TITLE
COMMERCE-7574 Add batch strategy to create method

### PR DESCRIPTION
**Pull request by javierdearcos**
The idea is to add different batch strategies to allow continuing after an error or not.

I've made the changes we talked about yesterday to avoid breaking REST Builder clients in old branches with Vulcan changes.

Original PR sent by Commerce here https://github.com/liferay-frontend/liferay-portal/pull/1948

### CODE REVIEW

**Comment by javierdearcos** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@javierdearcos can you rename

1.) ImportStrategy to BatchEngineImportStrategy, that trickles down

2.) BatchEngineTaskItemDelegate#setContextImportStrategy to

BatchEngineTaskItemDelegate#setBatchEngineImportStrategy

3.) contextBatchStrategy to contextBatchUnsafeConsumer

Thx @javierdearcos

**Comment by brianchandotcom** [comment]
@javierdearcos you also have to rename all the classes that extend BatchEngineImportStrategy to Xyz BatchEngineImportStrategy

**Comment by javierdearcos** [comment]
Sure. I'll do it and I will send it back to you

**Pull request closed without merging**
