### PR TITLE
master-lps-66524

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LPS-66524

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:stop

**Comment by kenjiheigel** [comment]
Just spoke with @brianchiu and we're going to quarantine all the failing tests together and push them upstream.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by kenjiheigel** [comment]
Forgot to post here yesterday. For reference, this is what was merged:
https://github.com/liferay/liferay-portal/compare/1d5cc0c4c6881388006e5cb0377cca23755f669d%5E...78ce1e4966aaff5bc92647e011bdf867b17bf319

**Pull request closed without merging**
