### PR TITLE
LPS-74415 Add ability to avoid serialization of Soy data

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:reopen

**Comment by leoadb** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4080e36a3d...f16e60405c

**Comment by brianchandotcom** [comment]
@leoadb see f16e60405c017f062b4c0a796d1fe33869915c3e

**Pull request closed without merging**
