### PR TITLE
LPS-98387 reindex fields

### PR DESCRIPTION
**Pull request by javiergamarra**
We can't use the annotation because we are not returning the same entity :(

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
Reviewed. No unique failures.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/960957fece...b104a206d2

**Comment by brianchandotcom** [comment]
@nhpatt can you send me a pull for 7.1.x? thx.

**Comment by nhpatt** [comment]
Thanks! Will do :)

**Pull request closed without merging**
