### PR TITLE
LPS-90354 Embed creator

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4831fbf4b7...71e2eb00c5

**Comment by brianchandotcom** [comment]
@victorg1991 see d81078447542aec98daa200182b7e34a38eeea6d and your bug in a2bfc1b48372ff95c42f183e1b5b26487b1e64b8

@ahdezma can you make your exception mappers smarter to know to unwrap RuntimeExceptions? See d81078447542aec98daa200182b7e34a38eeea6d and 71e2eb00c546a4b53132692a5030bd45870b0f8d

**Comment by victorg1991** [comment]
Thanks!!

**Comment by ahdezma** [comment]
Hey @brianchandotcom, `ExceptionMapper`s cannot throw another exception so there is no possibility to know which `ExceptionMapper` call after unwrapping the `RuntimeException#getCause`. Therefore, we cannot follow the pattern of wrapping the `Exception` on a `RuntimeException`. We should throw the desired JAX-RS exception in our business code.

**Pull request closed without merging**
