### PR TITLE
LPS-77279 Create a new UAD API: UADEntityDisplay.java

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-77279](https://issues.liferay.com/browse/LPS-77279).<br><br>Hey Brian, these are some basic stub implementations of the UADDisplay interface for a couple of the modules.  We will fill them out in future pulls.<br><br>/cc @pei-jung, @willnewbury, @noahsherrillwork

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test

**Comment by drewbrokke** [comment]
@brianchandotcom please allow the tests to finish

**Comment by brianchandotcom** [comment]
@drewbrokke should the descriptions be:

Announcements flag

or

Announcements Flag

Should it be a title or a phrase?

**Comment by drewbrokke** [comment]
@brianchandotcom They are placeholders at this point so a placeholder description would probably be "Announcements Flag description"

**Comment by drewbrokke** [comment]
@brianchandotcom this one should be a phrase.  This one looks right: https://github.com/brianchandotcom/liferay-portal/pull/54509/commits/434737043620b48bfc89389a7261186d59378eb9#diff-bdd9d2faa8fe21af307f79e9fd0d0427R77

**Pull request closed without merging**
