### PR TITLE
LPS-78082 Moving modules to the already existing social-bookmarks folder

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test

**Comment by 4lejandrito** [comment]
Hi @brianchandotcom,

I am now using plurals in every possible place. 

If I am correct, the only remaining elements in singular are the `PropKeys` which are all deprecated except for `SOCIAL_BOOKMARK_DISPLAY_STYLES` which I will deprecate in the next story (ready to be sent to you as soon as this one is merged). 

[This](https://github.com/4lejandrito/liferay-portal/blob/a623ee85fc9afd7b7b89d689e18fc8a0f4d112f5/modules/apps/social-bookmarks/social-bookmarks-taglib/src/main/java/com/liferay/social/bookmarks/taglib/servlet/taglib/SocialBookmarksTag.java#L61) should be the only place in which singular and plural don't match. As I said it, this will be fixed in the next set of changes.

Thanks for your patience!

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
Hi @jpince, @petershin,

can you guys verify that the PR failure is not related to my changes (lpkg stuff should not be related at all)?

Thanks!

**Comment by 4lejandrito** [comment]
That new failure does look like is caused by my changes 😢 I'll fix it and resend if necessary.

**Comment by jpince** [comment]
@4lejandrito yes, it does seem like the portal-license batch failure is related.
Here's the relevant part of the stacktrace for the lpkg failure, also looks related:
```
     [exec]  java.lang.RuntimeException: com.liferay.portal.lpkg.deployer.LPKGVerifyException: LPKG validation failed with {[missing requirement com.liferay.asset.publisher.web; version=2.0.0; type=osgi.bundle [caused by: Unable to resolve com.liferay.asset.publisher.web version=2.0.0: missing requirement &(osgi.extender=jsp.taglib)(uri=http://liferay.com/tld/social-bookmarks)]], [missing requirement com.liferay.blogs.web; version=2.0.4; type=osgi.bundle [caused by: Unable to resolve com.liferay.blogs.web version=2.0.4: missing requirement &(osgi.extender=jsp.taglib)(uri=http://liferay.com/tld/social-bookmarks)]]}
```
[Console](https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/221570//consoleText)

I'm going to close this pull for now so you have some time to think about it (and that way Brian won't merge it by accident, sometimes he'll miss comments like these)

**Comment by jpince** [comment]
ci:close

**Comment by 4lejandrito** [comment]
Thanks @jpince!

I moved my modules into an existing folder that turns out to be a `lab app`, and that is causing the failures. I'll see what's the best way to proceed and resend.

This is the never ending pull 😄 .

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/56140.

**Pull request closed without merging**
