### PR TITLE
LPS-110239 Remove ignore test: it is passing in the base class

### PR DESCRIPTION
**Pull request by dgarciasarai**
CI here https://github.com/dgarciasarai/liferay-portal/pull/181

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@dgarciasarai additional info from the log, maybe related?
```
    [junit] 13:48:14,953 INFO  [Arquillian-Connector-Thread][BundleStartStopLogger:46] STARTED com.liferay.segments.asah.rest.test_1.0.0 [1074]
...
    [junit] 13:48:20,929 WARN  [http-nio-8080-exec-10][GraphQL:543] Query failed to validate : 'query{experiment(experimentId:"38731"){id}}'
...
    [junit] 13:48:21,468 INFO  [Arquillian-Connector-Thread][BundleStartStopLogger:49] STOPPED com.liferay.segments.asah.rest.test_1.0.0 [1074]
```
If you open the log, the errors in between *`[AnalyticsConfigurationTrackerImpl:141] Unable to get configuration for company*` are probably unrelated.

https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/246750//consoleText

**Comment by dgarciasarai** [comment]
@jpince test:stable here was passing successfully https://github.com/dgarciasarai/liferay-portal/pull/181
I'll take a look, thanks.

**Comment by jpince** [comment]
@dgarciasarai the `ExperimentResourceTest` test class doesn't run in stable, it only runs in relevant.

@manoelcyreno @CarlosBrichete please educate the teams in Madrid about the differences between `ci:test:stable` and `ci:test:relevant`. Otherwise, devs will be wasting their time sending pulls to themselves and only running stable, only to have relevant fail when sending to BChan. A developer in Echo team did the same thing last week, and I'm sure there are others. This will be a big problem in 4 weeks when BChan wants to force teams to pass relevant in order to forward code.

If you don't understand the differences in how each test suite determines what tests to run, please talk to the other test leads.

**Comment by dgarciasarai** [comment]
@jpince thanks for the information. I'm going to talk with the Headless team and see what's happening with that test. I'll send it again if needed.

**Comment by dgarciasarai** [comment]
This is the trace:
```
     [exec] com.liferay.segments.asah.rest.resource.v1_0.test.ExperimentResourceTest > testGraphQLDeleteExperiment STARTED
     [exec] 13:48:20,929 WARN  [http-nio-8080-exec-10][GraphQL:543] Query failed to validate : 'query{experiment(experimentId:"38731"){id}}'
     [exec] 13:48:21,037 INFO  [com.liferay.segments.asah.rest.test-executor-thread][AnalyticsConfigurationTrackerImpl:141] Unable to get configuration for company 20098
     [exec] 13:48:21,292 INFO  [com.liferay.segments.asah.rest.test-executor-thread][AnalyticsConfigurationTrackerImpl:141] Unable to get configuration for company 20098
     [exec] 13:48:21,468 INFO  [Arquillian-Connector-Thread][BundleStartStopLogger:49] STOPPED com.liferay.segments.asah.rest.test_1.0.0 [1074]
     [exec] 
     [exec] com.liferay.segments.asah.rest.resource.v1_0.test.ExperimentResourceTest > testGraphQLDeleteExperiment PASSED
```

from https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/246750//consoleText

Apparently, the test is passing successfully but there is an error with the query, although it seems to be right...

/cc @javierdearcos

**Pull request closed without merging**
