### PR TITLE
Lps 73600

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@Preston-Crary can you resend this, with changes to ee-7.0.x and have SF changes sent to @hhuijser to send to me?

If I merge this, unless I make the changes to ee-7.0.x, that branch will have SF issues. Thx

**Comment by Preston-Crary** [comment]
@brianchandotcom okay, resent as three pulls:
https://github.com/brianchandotcom/liferay-portal/pull/50416
https://github.com/brianchandotcom/liferay-portal-ee/pull/17806
https://github.com/hhuijser/liferay-portal/pull/2918

**Pull request closed without merging**
