### PR TITLE
LPS-75449 Change the tab names to make their behaviour clearer

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @robertoDiaz

**Comment by jpince** [comment]
@austinchiang @patriciajeanperez please look into the POSHI failure

**Comment by patriciajeanperez** [comment]
Thanks, @jpince! The poshi failure is due to the UI changes introduced by this pull. I'll go ahead and fix our Announcements tests: https://issues.liferay.com/browse/LRQA-35765

**Comment by patriciajeanperez** [comment]
Resent sergiogonzalez#4087

**Pull request closed without merging**
