### PR TITLE
LPS-85765 Add portalArtifactsJar task

### PR DESCRIPTION
**Pull request by petershin**
Hi Brian, here's the command to run the task.

```
gw -b releng.gradle portalArtifactsJar
```

I just added sample values for the headers in `MANIFEST.MF`.

### CODE REVIEW

**Comment by petershin** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e390dba05c...0c33a66696

**Comment by brianchandotcom** [comment]
@ethanbustad can you work with Peter on this? Run it locally, and it'll make a fat jar for you. Then, use the physical jar (just point to it on the file system instead of pointing to Gradle/Nexus)

See how good or bad it is.

@petershin If it's useuless, then send me a pull to revert this. If it's good, let's keep pushing forward.

Let us know @ethanbustad !

**Comment by ethanbustad** [comment]
@brianchandotcom @petershin will do!

**Comment by ethanbustad** [comment]
@brianchandotcom looks great -- the compile task is no slower using the giant jar. There are a few missing classes tho -- @petershin is looking into it.

**Pull request closed without merging**
