### PR TITLE
Lps 64483

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @rotty3000, I don't know what jira tag to use. So just CC you here, in case you want to contribute it back.

CC @mhan810

CC @dantewang @slnn performance check please.

### CODE REVIEW

**Comment by rotty3000** [comment]
I'm all good the change. But to understand the issue here is it simply to reduce the memory cost of using exception as control flow?

**Comment by shuyangzhou** [comment]
Yes, in many cases the response is already committed, we are just creating IllegalStateException for no reason, it happens 20 times per login test iteration.

**Comment by shuyangzhou** [comment]
And if you check tomcat jasper impl, they don't have this issue. It uses a local char buffer to avoid dealing with the committed response.

**Comment by rotty3000** [comment]
Perfect! Thanks.

**Comment by shuyangzhou** [comment]
You are welcome, thank you for helping to contribute it back!

**Comment by shuyangzhou** [comment]
Force pushed for the SF error.

ci:retest

**Comment by shuyangzhou** [comment]
Sorry guys, did the logic wrong in the previous changes, fixed it now.

ci:retest

**Comment by rotty3000** [comment]
See https://java.net/jira/browse/JSP-51

**Comment by shuyangzhou** [comment]
Thanks @rotty3000 !

**Comment by brianchandotcom** [comment]
Thx @shuyangzhou @rotty3000

**Comment by brianchandotcom** [comment]
Merged upstream.

**Pull request closed without merging**
