### PR TITLE
COMMERCE-6399 Translated label for AccountSelector

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
A non-translated label in the AccountSelector component is having a functional test fail:
https://issues.liferay.com/browse/COMMERCE-6399

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:reopen

**Comment by gianmarcobrunialti** [comment]
@brianchandotcom @jpince Thanks in advance, hope this'll make it for GA1

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ade143d235...05684fc144

**Comment by jpince** [comment]
@gianmarcobrunialti we have already built and are currently testing a GA1 build. Is this commit required for GA1?

**Comment by gianmarcobrunialti** [comment]
@jpince Not a serious problem I suppose, but without this commit in master, functional test will fail, just consider this. :)

**Pull request closed without merging**
