### PR TITLE
LPS-59336 SF

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
I restarted this job on 10/15/15 at 12:15pm.

**Comment by michaelhashimoto** [comment]
This job got stuck.. so i made it unstuck. (I missed fixing a server before we restarted this job)

**Comment by michaelhashimoto** [comment]
I think this will likely finish in less than 20 minutes or so.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/369c481b0d...d7dbdcbc2b

**Pull request closed without merging**
