### PR TITLE
LPS-58210 use new api for obtaining apps in the roles admin and marketplace

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @drewbrokke @pei-jung @jorgeFerrer this modifies the rest of the roles app to use the new api.

@liona this modifies also the market place app to use the new api for obtaining apps in the control panel.

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
cc @lionah

**Comment by juliocamarero** [comment]
ci:retest

**Comment by JorgeFerrer** [comment]
Thanks Julio!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0c3a7ecc7d...8ff9daf17e

**Pull request closed without merging**
