### PR TITLE
LPS-54480 - extract JavaScript from portal-web into front end module

### PR DESCRIPTION
**Pull request by mjbradford89**
Hi Brian,

Attached is an update for https://issues.liferay.com/browse/LPS-54480.

Please let me know if there are any issues.

Thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by mjbradford89** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Retesting here https://github.com/brianchandotcom/liferay-portal/pull/25668

**Pull request closed without merging**
