### PR TITLE
Commerce 12722 - Checkout CX 2

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
In this one I got rid of the URL fields

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f92201f3fa...da206ab07c

**Comment by brianchandotcom** [comment]
@andrea-ale-sbarra see changes in my origin. Thx.

**Comment by andrea-ale-sbarra** [comment]
I've seen the chages, thank you @brianchandotcom .

**Pull request closed without merging**
