### PR TITLE
LPS-73185 Same logic with audios

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@ambrinchaudhary can you send a backport for this? The ticket is already backported, but the commits for this pull for this ticket are not backported.

Thx.

**Comment by robertoDiaz** [comment]
@ambrinchaudhary, if you could not backport it tomorrow, please, tell me and I'll handle it, 

A customer is waiting for this fix.

Thanks! 👍

**Comment by ambrinchaudhary** [comment]
@brianchandotcom @robertoDiaz here is the backport: https://github.com/liferay/liferay-portal-ee/pull/1086
Thank you!

**Comment by robertoDiaz** [comment]
Awesome!

Thank you @ambrinchaudhary 🔝

**Pull request closed without merging**
