### PR TITLE
liferay-aui.tld attribute description for translation manager

### PR DESCRIPTION
**Pull request by jhinkey**
cc/ @mwilliams2014

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/26038d6bec...0878cc9ff9

**Comment by brianchandotcom** [comment]
@jhinkey When you take all 3 commit in this pull, there are 0 changes?

**Comment by brianchandotcom** [comment]
@jhinkey please resend .. thx

**Comment by jhinkey** [comment]
Thanks, Brian. I didn't mean to delete that line. 

I sent a new pull to https://github.com/brianchandotcom/liferay-portal/pull/35482.

**Pull request closed without merging**
