### PR TITLE
[7.4-only] LPS-102104 LPS-125194 Remove $compat-navbar and $compat-basic-search

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LPS-102104
https://issues.liferay.com/browse/LPS-125194

This PR depends on #588. The classes `nav-link` and `nav-item` are added on the tag `aui:nav-item` there.

- Styled Theme removes compat navbar and compat basic-search
- liferay-ui:input-search updates input-group markup to Clay 3 and removes basic-search markup from lexicon view
- aui:nav-bar remove replace Clay 1 classes with Clay 3
   - removes Clay 1 class navbar-default
   - replace Clay 1 class navbar-toggle-left navbar-toggle-page-name with navbar-toggler navbar-toggler-link
   - use c-inner on toggler button to prevent focus outline on click
   - replace fontawesome icon with aui:icon
   - removes Clay 1 navbar-header element
- aui:nav lexicon view adds Liferay.MenuToggle to open and close collapsed navigation in mobile since we don't include Bootstrap 4 js by default
- aui:nav-item update markup to Clay 3
   - replaces Clay 1 class nav-item-label with navbar-text-truncate
   - use c-inner pattern for anchor tag
- liferay-ui:search-toggle lexicon and default view update markup to Clay 3
   - use Clay 3 input-group pattern
   - replace font awesome icons with Clay 3 svg icons
   - remove Clay 1 basic-search class
- Update markup in modules that use `aui:nav-bar` to use Clay 3 classes
    - Calendar
    - Export Import
    - Portal Workflow Kaleo
    - Staging
- Removes Clay 1 basic search pattern and replace with Clay 3 input-group pattern
   - Web Content
   - site-navigation-item-selector-web
   - Message Boards
- archived mail-reader-web
   - didn't touch this since it's not in use?

### CODE REVIEW

**Comment by john-co** [comment]
ci:reopen

**Comment by john-co** [comment]
Forwarded manually since multiple attempts have been affected by flaky test failures.

Unique failures verified as not related to PR in https://github.com/liferay-frontend/liferay-portal/pull/618#issuecomment-754923406

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
