### PR TITLE
SYNC-1607

### PR DESCRIPTION
**Pull request by Ithildir**
cc @shinnlok

### CODE REVIEW

**Comment by brianchiu** [comment]
The functional tomcat batches failed because of build failures.

```
/opt/dev/projects/github/liferay-portal/build-common-java.xml:269: java.util.zip.ZipException: The JAR/ZIP file (/opt/dev/projects/github/liferay-portal/.bnd/ant-baseline-cache/com.liferay.portal.impl-2.3.0.jar) seems corrupted, error: error in opening zip file
```

```
/opt/dev/projects/github/liferay-portal/build-common-java.xml:269: java.util.zip.ZipException: The JAR/ZIP file (/opt/dev/projects/github/liferay-portal/.bnd/ant-baseline-cache/com.liferay.portal.kernel-2.3.0.jar) seems corrupted, error: error in opening zip file
```

```
     [exec] Executing "git fetch --progress -v -f git@github.liferay.com:liferay/liferay-plugins.git cache-liferay-4fe36eb13a81789b605c2a1f0b3177eaf3d6e74f-liferay-4fe36eb13a81789b605c2a1f0b3177eaf3d6e74f:master-temp-20160527160614451" complete.
     [exec] Switched to branch 'master-temp-20160527160614451'
     [exec] error: branch '*' not found.
     [exec] Switched to branch 'master-temp-20160527160614451'
     [exec] error: branch '*' not found.
     [exec] error: Cannot delete the branch 'master-temp-20160527160614451' which you are currently on.
     [exec] error: Cannot delete the branch 'master-temp-20160527160614451' which you are currently on.
     [exec] Deleted branch master-temp-20160527160041138 (was 4fe36eb).
     [exec] Deleted branch temp-1464390871450960725 (was 4fe36eb).
```

**Comment by brianchiu** [comment]
ci:retest

**Comment by jpince** [comment]
@brianchandotcom no functional test failures

**Comment by Ithildir** [comment]
I fixed the rebase conflict and the semantic versioning error, resent at https://github.com/brianchandotcom/liferay-portal/pull/40327.

**Pull request closed without merging**
