### PR TITLE
LPS-87729

### PR DESCRIPTION
**Pull request by tinatian**
Hi guys @shuyangzhou @mhan810 @vicnate5 @jhinkey,

This pull is going to change how we use clustering on CE. 

After this pull we will have clustering features on CE by default. If you want to enable cluster on CE, the only thing needs to do is to set "cluster.link.enabled=true" in portal.properties.

After this pull, the difference between EE and CE is still same as before:
CE is using Ehcache's RMI to do cache replication across cluster
EE is using our own ClusterLink to do cache replication across cluster

Thanks.
Tina.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@mhan810 this came from bcheung and what we announced at dev con.

**Comment by vicnate5** [comment]
Thanks for letting us know @tinatian.

**Comment by vicnate5** [comment]
Please wait for test results, we may need to update the functional tests for this change.

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
additional testing https://github.com/vicnate5/liferay-portal/pull/1063

**Comment by tinatian** [comment]
Just FYI @shuyangzhou @brianchandotcom,
@lanceji92674957 did the performance test for startup with this pull and there is no regression.

Tina.

**Comment by brianchandotcom** [comment]
@tinatian ModuleConfigurationLocalizationTest.testConfigurationLocalization looks real.

Please resend on Monday? Thx!

@vicnate5 fyi.

**Comment by jhinkey** [comment]
@tinatian Thank you for letting me know.

**Pull request closed without merging**
