### PR TITLE
LPS-74139

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by Sharryxue** [comment]
- The DDL search icon related issue is addressed in [LPS-74153](https://issues.liferay.com/browse/LPS-74153)
- The Tag related issue is addressed in [LPS-74154](https://issues.liferay.com/browse/LPS-74154)
- jenkins_local_git.sh related issue is reported to QA engineer for further investigation
All failure shouldn't related to this commit.

**Comment by pyoo47** [comment]
ci:retest (Bad slaves spoiled the pull request test)

**Comment by lesliewong92** [comment]
ci:retest (Batches ran on bad jenkins server)

**Comment by hhuijser** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
