### PR TITLE
ISSITES-5983 Update app route implementation

### PR DESCRIPTION
**Pull request by ryanschuhler**

### CODE REVIEW

**Comment by ryanschuhler** [comment]
ci:reopen

**Comment by ryanschuhler** [comment]
@brianchandotcom Ray and Greg mentioned this is a better way to handle our routes. Let me know if you have any concerns with it

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c5b7ba9afb...b4e5856842

**Comment by brianchandotcom** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/aa26d58b81...741cf97348

**Comment by brianchandotcom** [comment]
@ryanschuhler just f2ec22ab and 741cf973

**Pull request closed without merging**
