### PR TITLE
LPS-46164 JDK8 Proxy generation compatibility issue

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@pyoo47 I think CI is doing some crazy, why is it commenting on this pull just now?

**Comment by shuyangzhou** [comment]
@pyoo47 I think it meant to comment it here? https://github.com/brianchandotcom/liferay-portal-ee/pull/18101

**Comment by shuyangzhou** [comment]
@pyoo47 It is same pull number, but on ee side. and more importantly it failed.

**Comment by pyoo47** [comment]
@shuyangzhou This happened because we had to make a quick adjustment to support pull requests for 7.0.x into liferay-portal-ee instead of liferay-portal. Our initial attempt to support 7.0.x into liferay-portal-ee had unintended side-effects that you saw in this pull. They have since been addressed. You shouldn't see this kind of behavior any more.

**Pull request closed without merging**
