### PR TITLE
LPS-90980 Fix bug in JournalArticleImpl to fetch template with proper className

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test:change-tracking

**Comment by matethurzo** [comment]
the error is not related to the change

**Comment by matethurzo** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@giros can you backport 98a9e2fc6603a9fd9dc6b46531ec60cc6c940075

ideally, using a new ticket.

**Pull request closed without merging**
