### PR TITLE
master-qa-22049

### PR DESCRIPTION
**Pull request by kiyoshilee**
https://issues.liferay.com/browse/LRQA-22049

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 hung again?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bcbd3576a8...4a62ef2224

**Comment by pyoo47** [comment]
This is a failure I've not seen before. It seems to have hung while shutting down the server.


```
clean-up-logs:
     [exec] 16-May-2016 19:19:41.281 INFO [main] org.apache.catalina.core.StandardServer.await A valid shutdown command was received via the shutdown port. Stopping the Server instance.
     [exec] 16-May-2016 19:19:41.282 INFO [main] org.apache.coyote.AbstractProtocol.pause Pausing ProtocolHandler ["http-nio-8080"]
     [exec] 16-May-2016 19:19:41.333 INFO [main] org.apache.coyote.AbstractProtocol.pause Pausing ProtocolHandler ["ajp-nio-8009"]
     [exec] 16-May-2016 19:19:41.388 INFO [main] org.apache.catalina.core.StandardService.stopInternal Stopping service Catalina
     [exec] 16-May-2016 19:19:41.708 INFO [localhost-startStop-2] org.apache.catalina.core.ApplicationContext.log Destroying Spring FrameworkServlet 'Remoting Servlet'
     [exec] java.lang.Exception
     [exec] 	at org.eclipse.equinox.http.servlet.internal.registration.Registration.destroy(Registration.java:45)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.destroy(EndpointRegistration.java:61)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.customizer.ContextServletTrackerCustomizer.removedService(ContextServletTrackerCustomizer.java:88)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.customizer.ContextServletTrackerCustomizer.removedService(ContextServletTrackerCustomizer.java:1)
     [exec] 	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerRemoved(ServiceTracker.java:967)
     [exec] 	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerRemoved(ServiceTracker.java:1)
     [exec] 	at org.osgi.util.tracker.AbstractTracked.untrack(AbstractTracked.java:341)
     [exec] 	at org.osgi.util.tracker.ServiceTracker.close(ServiceTracker.java:377)
```

**Comment by brianchandotcom** [comment]
It's happened a few times now right? I wonder if it's a new OSGi issue.. @mtambara can you take a look?

@shuyangzhou fyi

**Comment by pyoo47** [comment]
We've seen some issues during startup recently which @kenjiheigel has been looking into but this is a hangup during shutdown. It's possible that it's related but at this point, this is the first time I've seen it.

**Pull request closed without merging**
