### PR TITLE
LPS-59837 FIX Searching for any tag with quotes does not return results

### PR DESCRIPTION
**Pull request by arboliveira**
Re-sending https://github.com/brianchandotcom/liferay-portal/pull/49233#issuecomment-304755948. Using simple conditionals instead of switch cases. Thanks! 😃 

https://issues.liferay.com/browse/LPS-59837

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:reopen

**Comment by arboliveira** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/714b763c97...97afb06a3c

**Comment by brianchandotcom** [comment]
@arboliveira see c37741dfb17be0105269fcf8f743a958eadb589b Thx!

**Pull request closed without merging**
