### PR TITLE
[Please backport if possible] LPS-123274 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-123274

@jkappler

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure semantic versioning is not related to changes in PR.
See https://github.com/liferay-echo/liferay-portal/pull/2849
✔️ ci:test:stable - 9 out of 9 jobs passed
❌ ci:test:relevant - 20 out of 23 jobs passed in 1 hour 59 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/385b814886...5d019aadca

**Comment by brianchandotcom** [comment]
@hhuijser fyi.. you need to check JS as well for path changes

@jkappler @Tim-Cao backported to 7.3.x

**Pull request closed without merging**
