### PR TITLE
LRQA-42701 Add single module support for module unit test class group

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-42701

Please publish after merging

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0d0a76723e...bef7b4d633

**Comment by brianchandotcom** [comment]
@pyoo47 published.

**Pull request closed without merging**
