### PR TITLE
LPS-61860

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d851fe3f03...b250e7216b

**Comment by mhan810** [comment]
Hey @brianchandotcom we need to publish a new portal-kernel since I added a new method the to take executor

**Comment by brianchandotcom** [comment]
Ok, I'll publish a new one, but I was still able to compile modules/apps/platform/portal-background-task/portal-background-task-service even though it was still just referencing 1.0.1 kernel?

Are you actually using the new method in portal-background-task-service?

**Comment by mhan810** [comment]
Yep, I sent you the kernel changes first.  The actual use is in
portal-search.  I haven't sent the other half yet.  Waiting for the publish
to happen

Sent from my mobile device.

**Pull request closed without merging**
