### PR TITLE
LPS-61846 Theme Contributors

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @jorgeferrer, @natecavanaugh, @juliocamarero, @mjbradford89 this is adds the infrastructure for Theme Contributors we discussed.

Additionally, it creates two of them (Product Menu and Simulation Panel). We'll create the ControlMenu one later on, since it was recently refactored.

**Comment by mjbradford89** [comment]
This looks great!  Since we're not creating a control-menu contributor anymore, at least not yet, do we want to drop 5f18187 and d00416f for now?
Thanks again @jbalsas @csierra!

**Comment by jbalsas** [comment]
Oh, that's right, @mjbradford89!  I think it's okay to leave them anyway... we'll be moving that as soon as this gets in...

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@jbalsas weird error. Please resend. Thx.

**Comment by jbalsas** [comment]
Hey @mjbradford89, I'm out of office until tuesday... could you please take a look at what's going on and resend? You could drop the two `control-menu` related commits you mentioned while you're at it and we'll add those changes next week.

Thanks a lot!

**Comment by mjbradford89** [comment]
@jbalsas Sure thing, Have a good weekend!

**Comment by mjbradford89** [comment]
New pull: https://github.com/brianchandotcom/liferay-portal/pull/34477

**Pull request closed without merging**
