### PR TITLE
LPS-62485 Uses lang key from DDM

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 this hung?

ci:retest

**Comment by brunobasto** [comment]
ci:retest

**Comment by brunobasto** [comment]
@brianchandotcom,

This one will require the Source Formatter to understand that we are garbing the lang key from the module specified here: https://github.com/brunobasto/liferay-portal/commit/3dc12c33fd8440e9c5fd604c4e6bdc53384c0cbf#diff-cc7563b8900e50ee356c8c174b887bbcR37

**Comment by brunobasto** [comment]
@vicnate5,

Forms#PreviewAndPublishForm is the one you are going to fix, right?

**Comment by pyoo47** [comment]
@brianchandotcom The PR Tester hung due to the Jenkins bug that we've been dealing with since last week. The fix we did late last week has reduced the impact but some incidents slip by the fix. We tried backing out the plugin upgrade yesterday but it doesn't appear to be helping. We are currently looking into other possible solutions.

**Comment by brianchandotcom** [comment]
@brunobasto please send to @hhuijser to send to me with a SF fix. Otherwise, after I merge in this pull, all pulls will break.

**Comment by vicnate5** [comment]
@brunobasto Yes, sent fix for the Forms test at https://github.com/brianchandotcom/liferay-portal/pull/36836

**Pull request closed without merging**
