### PR TITLE
LPS-70099 | master

### PR DESCRIPTION
**Pull request by vicnate5**
@thiago-rocha @diogo-lins

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@thiago-rocha @vicnate5 see 60a797caa98b708b14912d6c5287d527a167bb05

**Pull request closed without merging**
