### PR TITLE
LPS-54860

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@mhan810 I merged this in, but...

1.)

Can we make the ivy.xml more minimalistic?

For ES, we do <dependency name="elasticsearch" org="org.elasticsearch" rev="1.3.4" /> and it grabs all the dependencies.

Can't we do that for Lucene? Specify one that is 3.5.0 and assume the rest will download? Right now, it's a bit fat.

```
<dependency name="lucene-analyzers" org="org.apache.lucene" rev="3.5.0" />
		<dependency name="lucene-core" org="org.apache.lucene" rev="3.5.0" />
		<dependency name="lucene-grouping" org="org.apache.lucene" rev="3.5.0" />
		<dependency name="lucene-highlighter" org="org.apache.lucene" rev="3.5.0" />
		<dependency name="lucene-icu" org="org.apache.lucene" rev="3.5.0" />
		<dependency name="lucene-join" org="org.apache.lucene" rev="3.5.0" />
		<dependency name="lucene-memory" org="org.apache.lucene" rev="3.5.0" />
		<dependency name="lucene-misc" org="org.apache.lucene" rev="3.5.0" />
		<dependency name="lucene-queries" org="org.apache.lucene" rev="3.5.0" />
		<dependency name="lucene-queryparser" org="org.apache.lucene" rev="3.5.0" />
		<dependency name="lucene-spellchecker" org="org.apache.lucene" rev="3.5.0" />
```

2.) Check out aadaa2d80d42bf5c8b4cd07c1f5ebc29ad1728d4 I think you had the wrong configurationPid

Thx!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/32c3b18174...55e8208ef8

**Comment by mhan810** [comment]
Hey Brian, I'm actually in the process of reworking the ES bnd and ivy
files.  I wanted to only include in bnd specific jars.  For ivy, we can
either do the minimalistic or have it reflect what's in the bnd.  You have
a pref?

Will check the commit

**Comment by mhan810** [comment]
Hey Brian, actually the ivy file for Lucene is correct.  Because it's a
search library, we need to specify what components we need to use.  The ES
file (see the one for LPS- 55071) specifies the higher level ES.

**Pull request closed without merging**
