### PR TITLE
COMMERCE-299

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:test

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
test failures unrelated

**Comment by brianchandotcom** [comment]
@ZoltanTakacs can you resend on top of https://github.com/ZoltanTakacs/liferay-portal/pull/44

1.) LiferayProvideConnectionProperties to LiferayConnectionPropertiesProvider

and LiferayProvideConnectionProperties#getConnectionProperties to

getLiferayConnectionProperties

2.) The line breaks in this pull are off.

From my pull to you (https://github.com/ZoltanTakacs/liferay-portal/pull/44), see my last few commits, can you apply what I was attempting to do and do it to the rest of the classes. Line breaks are important to communicate what you intend. Thx!

@Ithildir fyi

**Comment by brianchandotcom** [comment]
@ZoltanTakacs btw, we're close.. just a few of this SF and we're done. Thx.

**Comment by ZoltanTakacs** [comment]
Hi Brian,

Thank you for reviewing this PR, I've added the necessary changes in https://github.com/Ithildir/liferay-portal/pull/914

Thank you,
Zoli

**Pull request closed without merging**
