### PR TITLE
LPS-99294 Move classes to default packages

### PR DESCRIPTION
**Pull request by brunofarache**

### CODE REVIEW

**Comment by brunofarache** [comment]
@brianchandotcom failure not related to my changes.
@brunobasto can you or Aline take a look? Seems to be related to forms builder.

**Comment by brunobasto** [comment]
Done: https://github.com/brianchandotcom/liferay-portal/pull/77037

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e8e27733b8...6c0c4e63b2

**Comment by brianchandotcom** [comment]
@preston-crary can you take a look at ProductMenuAppDeployer

I have a feeling you may be opinionated about this.

**Comment by Preston-Crary** [comment]
@jeyvison thread safety part looks wrong. Using a ArrayList as a value in a ConcurrentHashMap is bad practice.  Maybe from the usage it's okay but it's better to use an array and once it's populated put it into the map (immutable = thread safe).  Also the get()/remove() for undeployment should only have a map.remove() and null check.  Can you make these changes and send it to me?  If you get stuck or are not sure what I mean IM me and I'll explain or make changes to the PR.

@brianchandotcom OSGi part looks okay, but there's no usage yet so I can't really judge that part fully.

**Comment by brianchandotcom** [comment]
Thx @Preston-Crary 

@brunofarache can you review it with @jeyvison ? Thx.

**Pull request closed without merging**
