### PR TITLE
LRQA-21857 Add tests back to PR tester

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
thanks @vicnate5

**Comment by vicnate5** [comment]
Test failures unrelated to this pull

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3e7c47fe47...bd2368ead4

**Comment by vicnate5** [comment]
Resent
https://github.com/brianchandotcom/liferay-portal/pull/35643

**Pull request closed without merging**
