### PR TITLE
LPS-65371

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@matethurzo fyi

**Comment by brianchandotcom** [comment]
@mhan810 unit test is unrelated, and I just fixed it in upstream. Merging.

**Comment by mhan810** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d95452accd...37d7180bf4

**Comment by brianchandotcom** [comment]
@mhan810 @igorarouca please see my changes in upstream

Thx

**Pull request closed without merging**
