### PR TITLE
Lps 52405

### PR DESCRIPTION
**Pull request by shuyangzhou**
Brian this pull will fail the CI build until you publish the pmd module, I don't know a better way to commit this without breaking the build.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
Hehe, I forgot to update the class file path in test.properties, which excludes PMDTest from running, then the build passed!

I am going to append a new commit to fix the file path, then the build should break on PMDTest.

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@rotty3000 no need to retest it, this pull contains the module it depends on. It won't pass the build until it is merged and the module is published.

**Comment by rotty3000** [comment]
I thought I saw the pmd module from liferay repo in a separate build which
is why I triggered this rebuild.

On Wed, Jan 7, 2015 at 12:02 PM, Shuyang Zhou <notifications@github.com>
wrote:

> @rotty3000 <https://github.com/rotty3000> no need to retest it, this pull
> contains the module it depends on. It won't pass the build until it is
> merged and the module is published.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/23083#issuecomment-69082481>
> .
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c7379b3e2c...d2deb82a5d

**Pull request closed without merging**
