### PR TITLE
LPS-69482 Remove the parameters p_p_col_id  p_p_col_pos and  p_p_col_count from every url because they are not necessary. Those parameters are only used when managing portlets in a page (adding a portlet in a page, moving a portlet to a different column, etc). Actually, those parameters are ignored by the friendly urls because they don't add value and the friendly urls are working (because those parameters are not necessary). The parameters are only used by UpdateLayoutAction and RenderPortletAction, and the latest one is only used to render portlets added to the page by drag and drop, refresh existing portlets, etc.

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@shuyangzhou what happened here?

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@sergiogonzalez thank you for the detailed description.

**Comment by shuyangzhou** [comment]
@brianchandotcom CI timed out, but we do have a lpkg failure inside, working on it.

**Pull request closed without merging**
