### PR TITLE
LPS-66950 Tag / Category resource permissions (first part)

### PR DESCRIPTION
**Pull request by Preston-Crary**
@pavel-savinov is a adding the required API before removing all the usages and creating the upgrade, so there will be 1-2 follow up pulls after this one.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:reopen

Just has this fail on a completely unrelated pull.

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
@brianchandotcom Rebased and resent here: https://github.com/brianchandotcom/liferay-portal/pull/45184

@Preston-Crary Could you please close this one since I've rebased and resent it? Thanks.

**Pull request closed without merging**
