### PR TITLE
LPS-66240 Use <liferay-ui:custom-attributes-available> to check for available custom fields

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Quite a few functional test errors, ci:retest

**Comment by brianchandotcom** [comment]
@pei-jung can you send this to QA? This one has many more functional test errors than the other pulls. Thx.

**Comment by drewbrokke** [comment]
@brianchandotcom sorry about that; this was supposed to go to @alee8888 first.

**Comment by pei-jung** [comment]
I've sent the PR to @alee8888 to update the functional tests https://github.com/alee8888/liferay-portal/pull/318. Thanks.

**Comment by JorgeFerrer** [comment]
Sorry guys, I didn't realize I should not have sent this to Brian yet.

**Pull request closed without merging**
