### PR TITLE
LPS-108206 Remove bundler loaders from dynamic-data-mapping-form-field-type package.json

### PR DESCRIPTION
**Pull request by wincent**
These packages were incorrectly added in dfb71a9dce492, causing duplication in the yarn.lock. If you run `yarn`, you wind up with multiple versions of these packages in the lockfile, and you see this (trimmed for brevity) in the output of `yarn why babel-plugin-normalize-requires`:

```
=> Found "babel-plugin-normalize-requires@2.17.0"
info Reasons this module exists
   - "_project_#babel-preset-liferay-standard" depends on it
=> Found "liferay-npm-bundler-loader-css-loader#babel-plugin-normalize-requires@2.17.1"
   - "_project_#dynamic-data-mapping-form-field-type#liferay-npm-bundler-loader-css-loader#liferay-npm-build-tools-common#liferay-npm-bundler-preset-standard#babel-preset-liferay-standard" depends on it
=> Found "liferay-npm-bundler-loader-style-loader#babel-plugin-normalize-requires@2.17.1"
   - "_project_#dynamic-data-mapping-form-field-type#liferay-npm-bundler-loader-style-loader#liferay-npm-build-tools-common#liferay-npm-bundler-preset-standard#babel-preset-liferay-standard" depends on it
```

These are "devDependencies" anyway, and should not have been added to "dependencies". And as "devDependencies", they are available transitively, and should not be declared.

Note also that the "leaflet" package, also added in dfb71a9dce492, was missing from the lockfile; I suspect that due to merge conflicts and/or rebase errors, that change got lost between when the commit was prepared and when it was merged -- note the long gap between the author and commit dates:

    Author:     marcelabc <mbc3@cin.ufpe.br>
    AuthorDate: Mon Jan 20 16:49:33 2020 -0300
    Commit:     Brian Chan <brian.chan@liferay.com>
    CommitDate: Wed Feb 5 13:51:18 2020 -0800

### CODE REVIEW

**Comment by wincent** [comment]
@hhuijser: would it be possible to prevent this kind of mistake again in the future in the `JSONPackageJSONCheck`? Basically, we should disallow anybody adding a dependency on packages matching the pattern `/^liferay-npm-bundler-loader-`.

cc @marcelabc @jbalsas

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/95b076a7f0...01cfbadfe2

**Comment by brianchandotcom** [comment]
@hhuijser it would be nice if this type of disallow was a property that @wincent could add himself going forward.

**Comment by brunobasto** [comment]
Hey @wincent, this broke Forms on master. If I remember correctly from the time Alexandre was working on this, using the `liferay-npm-bundler-loader-style-loader` was the only way to include css using the loader..

**Comment by brunobasto** [comment]
Actually, it was the only way he could find that worked.

**Comment by wincent** [comment]
More discussion on the revert PR: https://github.com/brianchandotcom/liferay-portal/pull/84336

I'll cc you @brunobasto when I send the follow-up.

**Comment by brunobasto** [comment]
Thanks, Greg! Got it. Yeah, we shouldn't have put dev dependencies as runtime dependencies. Alexandre was on a tight schedule, but I think the correct thing to do is that we should have communicated the need of the dev dependency to you guys and waited for the solution.

**Comment by wincent** [comment]
All that is true about dev dependencies, *but* I did a bit more digging and found that "The Right Fix™" here is to do this without style-loader at all. Once the new release of the bundler is out, containing [this fix](https://github.com/liferay/liferay-js-toolkit/commit/c0632cd851838f2e98827b4fd931a565197e2d8d), we can use css-loader (which is [already in liferay-portal](https://github.com/liferay/liferay-npm-tools/blob/290a1784c368d6882b0ea9e488f005f4bd470046/packages/liferay-npm-bundler-preset-liferay-dev/config.json#L276)). And of course, the fun fact is that the problem that prevented the use of css-loader and which led to that fix was [actually reported by your team](https://github.com/liferay/liferay-js-toolkit/issues/459) 🤦‍♂️.

So, once @izaera cuts the next bundler release (today, tomorrow, or very soon), will roll out "The Right Fix™".

**Comment by brunobasto** [comment]
Hum.. I guess we just didn't wait for the solution... 🙊

**Comment by wincent** [comment]
@brunobasto: The Right Fix™ is now up at https://github.com/brianchandotcom/liferay-portal/pull/84626

No need to use the style-loader any more, and we've added a lint to prevent it being accidentally added back.

**Comment by brunobasto** [comment]
Awesome!! Thank you

**Pull request closed without merging**
