### PR TITLE
LPS-86055 OpenSSO fix configuration default value

### PR DESCRIPTION
**Pull request by martamedio**
cc/ @stian-sigvartsen

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@stian-sigvartsen @martamedio I went ahead and did it for you, but next time, run

gradlew :apps:portal-security-sso:portal-security-sso-openid-api:baseline

**Comment by brianchandotcom** [comment]
@stian-sigvartsen @martamedio typo, should be 

gradlew  :apps:portal-security-sso:portal-security-sso-opensso-api:baseline

**Comment by stian-sigvartsen** [comment]
Thanks @brianchandotcom . Will take more care next time

**Pull request closed without merging**
