### PR TITLE
LPS-96637 Full support for relations in GraphQL

### PR DESCRIPTION
**Pull request by javiergamarra**
This allows us to do 1 to n relations like (all the comments of a blog):
```
getBlogPosting(blogPostingId: 37206){
    getBlogPostingCommentsPage {
      items {
        text
      }
    }
  }
```

Also 1 to 1 relations based on a path (rating of a blog):
```
getBlogPosting(blogPostingId: 37206){
    getBlogPostingMyRating {
      bestRating
    }
  }
```

And we also check for columns named like an entity (like messageBoardThreadId or contentStructureId) and do n to 1 to relations based on a property (Structure of a StructuredContent):
```
query{
  getStructuredContent(structuredContentId: 37275){
    getContentStructure {
      name
    }
  }
}
```

Next PR will rename the relations and properties do a GraphQL convention (getContentStructure -> contentStructure or getBlogPosting -> blogPosting) for Query class (Mutations are Ok right now).

### CODE REVIEW

**Comment by nhpatt** [comment]
Let's wait for the tests :)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e6d7d6b6f8...866518d318

**Comment by brianchandotcom** [comment]
@nhpatt I made some changes (squashed some regen commits) and pushed this upstream.

I saw that you closed your other graphql pull? Is that still coming in today?

**Comment by nhpatt** [comment]
Yes, I saw a baseline error and some test failing and I wanted to double check it. Will send in a bit, after dinner.

**Comment by brianchandotcom** [comment]
@nhpatt backported all to 7.2.x and 7.1.x

**Comment by nhpatt** [comment]
Thanks!

**Pull request closed without merging**
