### PR TITLE
LPS-78399 Create a new Configuration: OrganizationLinkConfiguration

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-78399](https://issues.liferay.com/browse/LPS-78399).<br><br>Hey Brian this is the first step in a new Organization link feature requested by commerce.  This adds a new configuration interface with no usages.<br><br>/cc @pei-jung, @marco-leo

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test

**Comment by drewbrokke** [comment]
@jpince are these errors mine?  They don't look like it but I'm not familiar with them.

**Comment by timpak** [comment]
@jpince @drewbrokke 

The SF errors are not related and the modules-integration failure appears to be a fluke. I'm not sure about the module-unit failures. I think it's an issue with the test themselves and I've reached out to the developer for help. I'll let you guys know when I get a response.

**Comment by timpak** [comment]
@drewbrokke the modules-unit failures are unrelated to your changes. Confirmed with the developer. 

@brianchandotcom please review.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2b25c77b42...b8faf4896b

**Pull request closed without merging**
