### PR TITLE
LPS-86699 Rename and avoid chaining

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:reopen

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jpince** [comment]
ci:close @epgarcia lpkg failures are related to this pull.

**Comment by jpince** [comment]
```
     [exec] 10:22:17,158 ERROR [main][org_apache_felix_scr:97] bundle org.apache.felix.scr:2.1.12 (54)Circular reference detected trying to get service {com.liferay.portal.kernel.model.ModelListener}={service.id=3784, service.bundleid=136, service.scope=bundle, component.name=com.liferay.segments.internal.model.listener.ExpandoColumnModelListener, component.id=470}
     [exec]  stack of references: ServiceReference: {com.liferay.portal.kernel.model.ModelListener}={service.id=3784, service.bundleid=136, service.scope=bundle, component.name=com.liferay.segments.internal.model.listener.ExpandoColumnModelListener, component.id=470}
     [exec]  
     [exec] java.lang.Exception: stack trace
     [exec] 	at org.apache.felix.scr.impl.ComponentRegistry.enterCreate(ComponentRegistry.java:485)
     [exec] 	at org.apache.felix.scr.impl.BundleComponentActivator.enterCreate(BundleComponentActivator.java:735)
     [exec] 	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:882)
     [exec] 	at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:212)
...
     [exec] 10:22:17,187 WARN  [Framework Event Dispatcher: Equinox Container: b8f2e352-9dba-475c-a61f-32dfa653e8a5][com_liferay_segments_service:103] FrameworkEvent WARNING 
     [exec] org.osgi.framework.ServiceException: org.apache.felix.scr.impl.manager.SingleComponentManager.getService() returned a null service object
...
     [exec] 10:22:17,198 ERROR [main][com_liferay_segments_service:97] bundle com.liferay.segments.service:1.0.0 (136)[com.liferay.segments.internal.model.listener.ExpandoColumnModelListener(470)] : The activate method has thrown an exception 
     [exec] java.lang.ExceptionInInitializerError
```
https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/238391/AXIS_VARIABLE=0,label_exp=!master/consoleFull

**Comment by epgarcia** [comment]
Thanks @jpince, working on it!

**Pull request closed without merging**
