### PR TITLE
LPS-68541 System Settings to override default Liferay field mappings

### PR DESCRIPTION
**Pull request by arboliveira**
Author: @BryanEngler
Reviewer: @arboliveira

cc/ @jordirodo @lipusz

https://issues.liferay.com/browse/LPS-68541

### CODE REVIEW

**Comment by lipusz** [comment]
Hi André,

Would it be possible to re-phrase the help message for the new property? Now it sounds like "you should never change it" and doesn't really clarify the purpose of the property.

What we should say sg like  "here, set this if you want to change analyzers or other metadata of fields in the default mappings and use the additionalTypeMappings" if you want to add new fields."

What I'd like to avoid is getting new issues because users get confused by the 2 very similar properties --> wrong usage of configurations.

What do you think?

@arboliveira

**Comment by arboliveira** [comment]
Hi Tibor,

The phrasing was chosen to discourage overriding default mappings without understanding the consequences (indeed, "you should never need to change it".) I feel it would prevent trouble if users restrained themselves from using this unless instructed by us, and only as a last resort when handling acknowledged Liferay issues - in which case a fix would follow and any overridden mappings would be cleared again.

There's lots of specific query programming logic in our Indexers and Searchers that rely on the default field mappings and analyzers as they are, and while I'm sure users may be able to fix some issues by tuning mappings only, more often than not the mismatch with code would cause even more search weirdness. Our default mappings are meant to work well out of the box; instead of having users experiment with full overrides by themselves, I believe it's safer to leave this in the hands of Technical Support Engineers who know what they're doing   😄 

@lipusz

**Comment by arboliveira** [comment]
ci:reopen

Test failed due to an infrastructure problem. `org.jboss.arquillian.container.spi.client.container.LifecycleException: Error connecting to Karaf MBeanServer`

**Comment by brianchandotcom** [comment]
@arboliveira can you resend with a better message, as @lipusz suggested? Thx.

**Comment by lipusz** [comment]
Hi André,

Thank you for the explanation. I generally agree with you, users should be careful when changing the default mappings.

However, it's 2 different things:
A) Adding the ability to do so
B) Knowing (the possible) impact of changes

In case A, it's a technical thing: you are or not able to do, but the purpose of the property should be clear. I think our user guide should be the place to tell customers how to use A properly otherwise they may hit problems of B.

**Pull request closed without merging**
