### PR TITLE
LPS-81982 Revert "LPS-80642 remove tab for document library for image field" This reverts commit 2d76a13

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
@linolaoj I had revert your commit because it causes LPS-81982. Ping me on Slack if you are sure that your changes are really necessary.

cc @ealonso @brianchiu

**Comment by linolaoj** [comment]
Hi @pavel-savinov, the idea was not letting user select documents and media images with the image field. Since there is documents and media field to cover this case.

**Comment by brianchandotcom** [comment]
@jpince can we undo a test ignore after this now? Merged.

**Comment by jpince** [comment]
@brianchandotcom I'm not aware of any backend test that was ignored for this.

**Pull request closed without merging**
