### PR TITLE
LPS-107420 Build Lang

### PR DESCRIPTION
**Pull request by dgarciasarai**
CI here: https://github.com/dgarciasarai/liferay-portal/pull/174
Failing tests are not ours, because we only changed files from `analytics-reports-web` module.
Thanks.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@leoadb please fix

```
     [exec] * What went wrong:
     [exec] Execution failed for task ':apps:dynamic-data-mapping:dynamic-data-mapping-form-field-type:packageRunTest'.
     [exec] > Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:dynamic-data-mapping:dynamic-data-mapping-form-field-type:packageRunTest'.

```

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/70c0327938...c4345340bc

**Comment by brianchandotcom** [comment]
@dgarciasarai please verify/fix any of my changes in 234329f2f1ed8761af4cd67c8b18cd79b8c64dd6 and c4345340bcea42a7e5104f0044c8107c7a68482f

**Comment by leoadb** [comment]
@marcelabc can you please help me with this? Thanks!

**Comment by dgarciasarai** [comment]
Looks good to me @brianchandotcom :) Thanks!

**Pull request closed without merging**
