### PR TITLE
LPS-165844 | master

### PR DESCRIPTION
**Pull request by liulukiwi**
https://issues.liferay.com/browse/LPS-165844

Failues at https://github.com/liferay-echo/liferay-portal/pull/10054 are not related to the pull after checking, so I send to you directly, thanks!

cc @sandrodw3

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:reopen

**Comment by liulukiwi** [comment]
ci:close

**Comment by liulukiwi** [comment]
ci:reopen

there's a test-fix in this pull, since I could not reproduce it in local, I will send it later.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fa95787d91...533b39ef6d

**Pull request closed without merging**
