### PR TITLE
LPS-95848 buildLang

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by jpince** [comment]
@ealonso this int test failure might be related? I don't see it in upstream.
```
DLFileEntryInfoDisplayContributorTest.testDLFileEntryInfoDisplayContributor
java.lang.AssertionError: expected:<> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.liferay.document.library.info.display.contributor.test.DLFileEntryInfoDisplayContributorTest.lambda$testDLFileEntryInfoDisplayContributor$1(DLFileEntryInfoDisplayContributorTest.java:130)
```
cc/ @brianchiu @kyle-miho @austinchiang @patriciajeanperez

**Comment by kyle-miho** [comment]
@jpince its likely related, I'll take a look

**Comment by kyle-miho** [comment]
ci:close

**Comment by kyle-miho** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by kyle-miho** [comment]
@jpince 
Pushed to https://github.com/ealonso/liferay-portal/pull/2391

2 issues with the integration tests
1) https://github.com/brianchandotcom/liferay-portal/pull/73625/commits/2ebc29ceeeef9f7dd4203149331b16b10f25485b 
Testfix, since we changed returning an empty json object to an empty string if there is no authorProfileImage, I updated the assertion to be correct. 
2) One of the asset contributor fields we removed here is the summary field, but we never added it back to each of the individual assets. We either need to re-add them (if that was a mistake), or we can just update the assertion in DLFileEntryInfoDisplayContributorTest.testDLFileEntryInfoDisplayContributor Line 130-131 
```
Assert.assertEquals(	StringPool.BLANK, infoDisplayFieldsValues.get("summary"));
```
I am not sure what is correct, so I did not touch it  @ealonso 
https://github.com/brianchandotcom/liferay-portal/pull/73625/commits/a1cb61a4e3e8167ee2c902eeb0b6fe979b6f9080

**Pull request closed without merging**
