### PR TITLE
LPS-67568

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pyoo47 what's up with CI? Lots of CI issues?

**Comment by pyoo47** [comment]
@brianchandotcom It looks like there was a temporary problem connecting with GitHub. I'm in the middle of a Jenkins reset so I am waiting to retest these after I'm done with the reset.

```
     [exec] Executing \"git fetch -v -f upstream\".
     [exec] ssh: Could not resolve hostname github.com: Temporary failure in name resolution
```

**Comment by ZoltanTakacs** [comment]
ci:retest

**Comment by alee8888** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by mhan810** [comment]
@brianchandotcom these test failures don't look to be related to this pull.  Do you want me to rebase and send again?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/be29c656ac...14ea32df93

**Pull request closed without merging**
