### PR TITLE
LPS-57379 Renaming Settings API to Configuration API

### PR DESCRIPTION
**Pull request by jkappler**
Hi @brianchandotcom, I made the changes according to your comments.

There is a package in DM that is settings.internal, but this is because it still uses the old settings, and will be migrated to the new one by the collaboration team later on.

Thx

### CODE REVIEW

**Comment by jkappler** [comment]
CC: @JorgeFerrer

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5ad7e44622...411f7d565e

**Comment by brianchandotcom** [comment]
Nice job on this major refactor @jkappler !

Can you keep tabs on the DM team to make sure they do it "right".

Also, please keep tabs on Settings/Configuration in general as ppl may still be sending me the old pattern for now until they start "copying" your new pattern.

Thx

**Comment by jkappler** [comment]
That's great @brianchandotcom! 

I'll keep checking configuration/settings to see that it follows the new convention.

Thx!!

**Pull request closed without merging**
