### PR TITLE
LPS-59039 fix objectClass case to match all others

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
@mhan810  will this mess anything up?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f845b4cc8b...2e3f28f121

**Comment by mhan810** [comment]
Greg those properties are for LDAP only and not for osgi

**Comment by gamerson** [comment]
Got it, so I'll send a pull to change them back since they are ldap only
and don't need to match the other osgi ones.

On Thu, Nov 19, 2015 at 7:08 PM, Michael Han <notifications@github.com>
wrote:

> Greg those properties are for LDAP only and not for osgi
>
> Sent from my mobile device.
> On Nov 19, 2015 12:24 PM, "Gregory Amerson" <notifications@github.com>
> wrote:
>
> > @mhan810 <https://github.com/mhan810> will this mess anything up?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/brianchandotcom/liferay-portal/pull/32390#issuecomment-158186716
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/32390#issuecomment-158248259>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by gamerson** [comment]
Actually Mike are you sure the _OBJECT_CLASS variable isn't used somewhere
in OSGi?  When I was writing my osgi tracker tracker app here, I found out
of 7,000 instances of objectClass filters in the osgi container there was
one instance of "objectclass".  Instead of "objectClass" when I went to
search the portal sourcecode, i found these two spots.

Could it be that first static variable is the one causing it?  Perhaps we
should just rollback the 2nd portal.properties change?

On Thu, Nov 19, 2015 at 11:15 PM, Greg Amerson <gregory.amerson@liferay.com>
wrote:

> Got it, so I'll send a pull to change them back since they are ldap only
> and don't need to match the other osgi ones.
>
> On Thu, Nov 19, 2015 at 7:08 PM, Michael Han <notifications@github.com>
> wrote:
>
>> Greg those properties are for LDAP only and not for osgi
>>
>> Sent from my mobile device.
>> On Nov 19, 2015 12:24 PM, "Gregory Amerson" <notifications@github.com>
>> wrote:
>>
>> > @mhan810 <https://github.com/mhan810> will this mess anything up?
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <
>> https://github.com/brianchandotcom/liferay-portal/pull/32390#issuecomment-158186716
>> >
>> > .
>>
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/brianchandotcom/liferay-portal/pull/32390#issuecomment-158248259>
>> .
>>
>
>
>
> --
> Greg Amerson
> Liferay Developer Tools
> Liferay, Inc. www.liferay.com
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Pull request closed without merging**
