### PR TITLE
LPS-105235 tests for permissions

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@wincent @jbalsas can you guys fix the JS SF? Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a162e7e620...09fe5571a2

**Comment by nhpatt** [comment]
Thanks!

**Comment by jbalsas** [comment]
Hey @ambrinchaudhary, @adolfopa, can you guys take a look at the SF error?

```
     [exec] apps/item-selector/item-selector-taglib/src/main/resources/META-INF/resources/repository_entry_browser/js/ItemSelectorRepositoryEntryBrowser.es.js: BAD
```

Ping us if you need help with it!

**Comment by ambrinchaudhary** [comment]
> Hey @ambrinchaudhary, @adolfopa, can you guys take a look at the SF error?
> 
> ```
> [exec] apps/item-selector/item-selector-taglib/src/main/resources/META-INF/resources/repository_entry_browser/js/ItemSelectorRepositoryEntryBrowser.es.js: BAD
> ```
> 
> Ping us if you need help with it!

Sure, I'll fix it, I introduced this yesterday :-(

**Comment by ambrinchaudhary** [comment]
Fix sent: https://github.com/brianchandotcom/liferay-portal/pull/83575

**Pull request closed without merging**
