### PR TITLE
Lps 75100

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
@brianchandotcom this new petra-nio is put into the new location, "core:petra:petra-nio". we did not move the exist ones, because petra-lang has not finished yet, once https://github.com/brianchandotcom/liferay-portal/pull/52014 is merged, there will be another follow up pull for petra-lang. Then it is done, we will move all "core" petra modules to the new location, thanks!

**Comment by brianchandotcom** [comment]
@shuyangzhou can you rebase and resend? Conflict. Thx.

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/52119

**Pull request closed without merging**
