### PR TITLE
LPS-92310 Implement OpenNLP auto tagger for documents

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@adolfopa @cgoncas 1.) we can't check in *.bin files like that.

See

modules/apps/portal-search-elasticsearch6/portal-search-elasticsearch6-impl/build.gradle

and

modules/private/apps/portal-mobile-device-detection-fiftyonedegrees-enterprise/portal-mobile-device-detection-fiftyonedegrees-enterprise/build.gradle

One has zip and the other gz

OpenNLP probably has one of those, and we need it in Maven. Ask Chas to put it in Maven if they don't have a public one already.

2.) For the prefix, let's keep it OpenNLP (see Tensorflow), we only did it for Google and Microsoft because theirs was very long (it had additional words after Google and Microsoft). Tenserflow and OpenNLP don't have those extra words so we don't need to shorten it.

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
continues in https://github.com/brianchandotcom/liferay-portal/pull/70578

**Pull request closed without merging**
