### PR TITLE
LPS-76536 Wrap the entire edit user page and form navigator as a screen navigation entry

### PR DESCRIPTION
**Pull request by pei-jung**
This is an update for [LPS-76536](https://issues.liferay.com/browse/LPS-76536).
This is an update for [LPS-76537](https://issues.liferay.com/browse/LPS-76537).
This is an update for [LPS-76540](https://issues.liferay.com/browse/LPS-76540).
This is an update for [LPS-76545](https://issues.liferay.com/browse/LPS-76545).

/cc @drewbrokke @jorgeferrer

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pei-jung did this already pass somewhere?

**Comment by pei-jung** [comment]
@brianchandotcom not yet. It has been tested in https://github.com/ksuetani/liferay-portal/pull/19, and I fixed the semver. I'll run the test again.

**Comment by pei-jung** [comment]
ci:test

**Comment by pei-jung** [comment]
ci:reopen

**Comment by drewbrokke** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c0fb488133...6f7e17f81f

**Pull request closed without merging**
