### PR TITLE
LRQA-35459 | master

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-35459

cc @jpince This refactoring of `Page#tearDownPG` fixes the teardown problem in `PortalSmoke#Smoke`.

### CODE REVIEW

**Comment by jpince** [comment]
@anthony-chu thank you!

**Comment by jpince** [comment]
@brianwulbern @ginsonren this might be good to backport?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/beaecfc0e5...153ff7b1a0

**Comment by brianwulbern** [comment]
Sent to 7.0: https://github.com/brianchandotcom/liferay-portal-ee/pull/18482

**Pull request closed without merging**
