### PR TITLE
LRQA-39683 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-39683

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:test

**Comment by austinchiang** [comment]
ci:open

**Comment by austinchiang** [comment]
ci:reopen

**Comment by austinchiang** [comment]
@brianchandotcom  test failures are unrelated.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5b6855b459...e2737f0cb6

**Pull request closed without merging**
