### PR TITLE
LPS-59032 escape JS in reset prototype URL instead of URL encoding

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
reviewed by @juliocamarero

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d0950e809b...60c9f1793b

**Pull request closed without merging**
