### PR TITLE
LPS-83811 Replace lodash from portal 

### PR DESCRIPTION
**Pull request by iiventura**

### CODE REVIEW

**Comment by iiventura** [comment]
@carloslancha

**Comment by carloslancha** [comment]
ci:test

**Comment by iiventura** [comment]
Hi @john-co, could you please check the failures?

**Comment by brianchandotcom** [comment]
@iiventura you should avoid using the ticket LPS-83811 but use the subticket instead. Please resend.

@jbalsas @iiventura @jonmak08 NOT merged, please resend with right ticket.

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/brianchandotcom/liferay-portal/pull/62784

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/brianchandotcom/liferay-portal/pull/62785

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/brianchandotcom/liferay-portal/pull/62786

**Pull request closed without merging**
