### PR TITLE
LPS-61709 Rename portlet as SystemSettings - Change class name

### PR DESCRIPTION
**Pull request by JorgeFerrer**
/cc @mhan810

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
ci:retest

**Comment by JorgeFerrer** [comment]
I just did a force push again, just so that you guys had another case to monitor ;)

**Comment by JorgeFerrer** [comment]
ci:retest

**Comment by pyoo47** [comment]
@brianchandotcom It looks like even the retries are not helping the 503 issue.

```
update-portal-to-pull-from-local-github:
[beanshell] toString() failed. Server returned HTTP response code: 503 for URL: http://cloud-10-0-0-10.lax.liferay.com/osb-github-web/proxy?url=api.github.com/repos/brianchandotcom/liferay-portal/pulls/34795 URL: http://cloud-10-0-0-10.lax.liferay.com/osb-github-web/proxy?url=api.github.com/repos/brianchandotcom/liferay-portal/pulls/34795
[beanshell] toString() failed. Server returned HTTP response code: 503 for URL: http://cloud-10-0-0-10.lax.liferay.com/osb-github-web/proxy?url=api.github.com/repos/brianchandotcom/liferay-portal/pulls/34795 URL: http://cloud-10-0-0-10.lax.liferay.com/osb-github-web/proxy?url=api.github.com/repos/brianchandotcom/liferay-portal/pulls/34795
[beanshell] toString() failed. Server returned HTTP response code: 503 for URL: http://cloud-10-0-0-10.lax.liferay.com/osb-github-web/proxy?url=api.github.com/repos/brianchandotcom/liferay-portal/pulls/34795 URL: http://cloud-10-0-0-10.lax.liferay.com/osb-github-web/proxy?url=api.github.com/repos/brianchandotcom/liferay-portal/pulls/34795
[beanshell] toString() failed. Server returned HTTP response code: 503 for URL: http://cloud-10-0-0-10.lax.liferay.com/osb-github-web/proxy?url=api.github.com/repos/brianchandotcom/liferay-portal/pulls/34795 URL: http://cloud-10-0-0-10.lax.liferay.com/osb-github-web/proxy?url=api.github.com/repos/brianchandotcom/liferay-portal/pulls/34795

BUILD FAILED
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-test-portal-acceptance-pullrequest-batch.xml:204: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-test-portal-acceptance-pullrequest-batch.xml:104: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:4770: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:3513: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:299: Sourced file: inline evaluation of: `` 				 					import org.json.JSONObject;  					public String fixURL(String url) {  . . . '' : Typed variable declaration : TargetError : at Line: 64 : in file: inline evaluation of: `` 				 					import org.json.JSONObject;  					public String fixURL(String url) {  . . . '' : throw e ; 

Called from method: toJSONObject : at Line: 83 : in file: inline evaluation of: `` 				 					import org.json.JSONObject;  					public String fixURL(String url) {  . . . '' : toJSONObject ( sb .toString ( ) ) 
Target exception: java.io.IOException: Server returned HTTP response code: 503 for URL: http://cloud-10-0-0-10.lax.liferay.com/osb-github-web/proxy?url=api.github.com/repos/brianchandotcom/liferay-portal/pulls/34795
```

**Comment by brianchandotcom** [comment]
@pyoo47 I upped the retry count to 5, and waited 5 seconds each time now. Let's see what happens now.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/eee492327f...61e0c09922

**Pull request closed without merging**
