### PR TITLE
LPS-58159

### PR DESCRIPTION
**Pull request by danielkocsis**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Instead of hard coding, can you add a reference to the persistence bean and call its getBadColumnNames?

Theoretically, all finder impls should link to their persistence impl and call their getBadColumnNames. Let's find a way to fix this globally.

Update ServiceBuilder to generate a XyzBaseFinderImpl that has the method getBadColumnNames filled in.

Update ServiceBuilder to auto replace XyzFinderImpl to extend from XyzBaseFinderImpl.

So the fix is just to regenerate and everyone gets it.

**Comment by danielkocsis** [comment]
Hey Brian,

I agree that a generic, autogenerated solution would be much better and more robust.

What do you think about, instead of inheritance, we introduce a new class, like XyzPersistenceHelper that holds this (and later maybe other information) and persistnceImpl and finderImpl both references this class? 

thanks,
Daniel

**Comment by brianchandotcom** [comment]
I think it'd be cleanest to:

Generate a new XyzBaseFinderImpl.

XyzFinderImpl will extend XyzBaseFinderImpl.

XyzBaseFinderImpl will have a method called getBadColumnNames. The logic of the method will delegate to XyzPersistence#getBadColumnNames (note it's the interface xyzPersistence and not the impl xyzPersistenceImpl).

Why?

In service.xml, you can override and set another instance of XyzPersistenceImpl. If you did, it'd now automatically be given to the XyzFinderImpl too.

This way, if

**Comment by brandizzi** [comment]
Hey Brian, Daniel.

We took this issue to us. Inácio (@inacionery) already sent me a fix for that and I'm testing it. Tomorrow @marcellus may help as well.

This bug is a blocker to Liferay 7.0 alpha release so we are doing everything possible to have it solved perfectly.

**Pull request closed without merging**
