### PR TITLE
LPS-79066 buildLang

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test

**Comment by matethurzo** [comment]
@brianchandotcom unrelated failure, retesting

**Comment by matethurzo** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@zoltancsaszi @matethurzo 

can you fix these keys:

```
x-export-layout-process-failed={0} Export process failed
x-export-layout-process-finished-successfully={0} Export process finished successfully
x-export-portlet-process-failed={0} Portlet Export process failed
x-export-portlet-process-finished-successfully={0} Portlet Export process finished successfully
x-import-layout-process-failed={0} Import process failed
x-import-layout-process-finished-successfully={0} Import process finished successfully
x-import-portlet-process-failed={0} Portlet Import process failed
x-import-portlet-process-finished-successfully={0} Portlet Import process finished successfully
x-is-staged={0} is staged.
x-publish-layout-local-process-failed={0} Local Publication process failed
x-publish-layout-local-process-finished-successfully={0} Local Publication process finished successfully
x-publish-layout-remote-process-failed={0} Remote Publication process failed
x-publish-layout-remote-process-finished-successfully={0} Remote Publication process finished successfully
x-publish-portlet-local-process-failed={0} Portlet Local Publication process failed
x-publish-portlet-local-process-finished-successfully={0} Portlet Local Publication process finished successfully
x-publish-portlet-process-failed={0} Portlet Publication process failed
x-publish-portlet-process-finished-successfully={0} Portlet Publication process finished successfully
x-publish-portlet-remote-process-failed={0} Portlet Remote Publication process failed
x-publish-portlet-remote-process-finished-successfully={0} Portlet Remote Publication process finished successfully
```

Everything should be a sentence (end in a period), or a book title. If a book title, see http://titlecapitalization.com (Chicago Manual of Style).

This is a good title:

view-page-staging-options=View Page Staging Options

This is a good sentence:

validate-layout-references-help=If checked, publishing or importing some types of content with text in it will cause Liferay to check the content for any links that reference one of the portal's virtual hosts, and ensure that each of these links points to a valid page within Liferay. Uncheck this if your virtual host has pages not in Liferay.

Please resend. Thx.

**Pull request closed without merging**
