### PR TITLE
LRQA-48202 | master

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LRQA-48202

This is only for master. Thanks.

/cc @brianwulbern

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by brianwulbern** [comment]
fyi @alexcandidos

**Comment by alexcandidos** [comment]
Thanks @liuxingye and @brianwulbern !

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
