### PR TITLE
LPS-92486 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-94286
cc: @jkappler @brianchiu

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Thanks for this @kyle-miho!

cc:/ @ealonso

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/715c2a0699...00d27c05c7

**Pull request closed without merging**
