### PR TITLE
LPS-108949 Update tests

### PR DESCRIPTION
**Pull request by dgarciasarai**
Failing tests fixed here: https://github.com/brianchandotcom/liferay-portal/pull/85393

/cc @darquesdev

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
Hey @brianchandotcom, I rebased this pull request and I ran the CI on my fork.
Here is the results: https://github.com/dgarciasarai/liferay-portal/pull/173
Thanks :)

**Comment by brianchandotcom** [comment]
@dgarciasarai 1.) I merged this, but can you rename

internal.data.model

to

internal.data.time

2.) Rename

public List<LocalDateTime> getIntervals()

Because it does not match

public LocalDateTime getEndLocalDateTime()

and

public LocalDate getEndLocalDate()

Otherwise, very good. Thanks @dgarciasarai

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fdf3daa0e2...12d6d50a3c

**Pull request closed without merging**
