### PR TITLE
SYNC-1807 This is not needed because customers in 6.2 (first version to be able to upgrade to 7.2 directly) are already in the schema version 1.2

### PR DESCRIPTION
**Pull request by achaparro**
Hi @brianchandotcom, @dejuknow,

I have removed the other execution of UpgradeSyncDLObject because it was in the step 1.0.2 and all customers from 6.2 (lowest version to be able to upgrade directly to 7.2) had executed that step so it's not needed anymore.

The last two upgrades are a bit weird but until we implement [this](https://issues.liferay.com/browse/LPS-101216), we don't have a better option for this specific case.

I will be on PTO until October 7 so please @dejuknow take care of the pull in case any change is required.

Thanks.
Best regards.

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
Reviewed. No unique failures.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fe6227aff3...75ad95a026

**Comment by brianchandotcom** [comment]
@achaparro @dejuknow I ported this to 7.2.x. If it needs to go farther back, send me a pull.

**Comment by brianchandotcom** [comment]
@achaparro @dejuknow I reverted this because of https://test-1-16.liferay.com/job/test-portal-testsuite-upstream-batch(7.2.x)/AXIS_VARIABLE=3,label_exp=!master/191/testReport/junit/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXMLLog/

```
Portal log assert failure, see above log for more information: 
Unable to register portal instance {mvccVersion=1, companyId=20102, accountId=20104, webId=liferay.com, key=KAI66ph5YI4J+SmvXSB/kA==, mx=liferay.com, homeURL=, logoId=0, system=false, maxUsers=0, active=true}
java.lang.IllegalStateException: The com.liferay.portal.kernel.dao.orm.FinderCache.com.liferay.sync.model.impl.SyncDLObjectImpl Cache is not alive (STATUS_SHUTDOWN)
	at net.sf.ehcache.Cache$CacheStatus.checkAlive(Cache.java:4104)
	at net.sf.ehcache.Cache.checkStatus(Cache.java:2792)
	at net.sf.ehcache.Cache.removeInternal(Cache.java:2406)
	at net.sf.ehcache.Cache.remove(Cache.java:2325)
	at net.sf.ehcache.Cache.remove(Cache.java:2244)
	at net.sf.ehcache.Cache.remove(Cache.java:2223)
	at com.liferay.portal.cache.ehcache.internal.EhcachePortalCache.doRemove(EhcachePortalCache.java:121)
	at com.liferay.portal.cache.BasePortalCache.remove(BasePortalCache.java:122)
	at com.liferay.portal.kernel.cache.PortalCacheHelperUtil.removeWithoutReplicator(PortalCacheHelperUtil.java:132)
	at com.liferay.portal.kernel.cache.transactional.TransactionalPortalCacheHelper$ValueEntry.commitToByRemove(TransactionalPortalCacheHelper.java:512)
	at com.liferay.portal.kernel.cache.transactional.TransactionalPortalCacheHelper$UncommittedB
```

**Comment by dejuknow** [comment]
@achaparro It looks like adding an UpgradeStep with a version greater than Liferay-Require-SchemaVersion causes this test failure. See my test here: https://github.com/dejuknow/liferay-portal/pull/121#issuecomment-534348227

Any ideas why this fails?

**Comment by dejuknow** [comment]
@SamZiemer Just realized Alberto is out on PTO. Can you help w/ looking into why the above test fails? Will reach out to you on Slack to fill you in.

**Comment by holatuwol** [comment]
@dejuknow : In theory, as long as it's not a major version change, it shouldn't have any problems due to the changes we made in [LPS-76926](https://issues.liferay.com/browse/LPS-76926).

As a sanity check, I've run `ci:test:bundle` on your test branch so I can see what's inside of the `OSGI-INF/context/context.dependencies` of the generated `com.liferay.sync.service` bundle.

**Comment by dejuknow** [comment]
@holatuwol @SamZiemer Took a look inside the `com.liferay.sync.service` bundle and didn't find a `context.dependencies`. Any ideas?

**Comment by holatuwol** [comment]
@dejuknow : I was looking at the wrong branch (7.0.x) so I didn't realize that com.liferay.sync.service had already switched to ds, so that file won't be there.

In theory, since it's a startup error, you should be able to reproduce it by starting up the bundle that was attached to the ticket, but everything's working fine for me, so CI is doing something different with the bundle than simply starting it up.

Would it be problematic to update the schema version in the bnd.bnd to match the last upgrade step?

**Comment by dejuknow** [comment]
@holatuwol Unfortunately, creating an upgrade step greater than the required schema version is the workaround for [SYNC-1807](https://issues.liferay.com/browse/SYNC-1807) (see description and link to Slack thread in comments for history).

Yeah, it works fine for me too when starting the bundle, so I’m not sure what CI is doing. =/

**Comment by dejuknow** [comment]
@achaparro Now that you're back from PTO 😁, any initial ideas why CI might be failing with the workaround of creating an upgrade step version higher than the required schema version?

**Comment by achaparro** [comment]
Hi @dejuknow,

I will take a look today. Maybe we will be able to change the tests because we don't need to take into account the micro versions for this check.

**Comment by achaparro** [comment]
Hi @dejuknow,

I am trying to find the error related to the _schemaVersion_ in https://github.com/dejuknow/liferay-portal/pull/126 I can't find it. Can you point to the link where I can see the stacktrace for that error?

Thanks.

**Comment by dejuknow** [comment]
@achaparro Unfortunately, I haven't had any luck finding the specific error either. 😞 All I know is that CI consistently fails even when the only changes are to the required schemaVersion and an DummyUpgradeStep https://github.com/dejuknow/liferay-portal/pull/126/files

**Comment by achaparro** [comment]
I have checked a few things:
- Possible tests that can fail with these changes
- Dependencies between the portlet and the schema version in the service

And I haven't found anything.

@victnate5, do you know what's the unique error caused by https://github.com/dejuknow/liferay-portal/pull/126?

Thanks.

**Comment by vicnate5** [comment]
@achaparro There is an intermittent startup WARN (matching https://github.com/brianchandotcom/liferay-portal/pull/78650#issuecomment-533844630). It is caught on the modules-integration tests, but I also see it during the portal startup on some of the functional tests. The issue does not occur consistently, possible race condition.

Full logs 
Modules-integration https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/327171/AXIS_VARIABLE=33,label_exp=!master/consoleText
Functional https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/322932/AXIS_VARIABLE=0,label_exp=!master/consoleText

**Comment by achaparro** [comment]
Thanks for the provided information @vicnate5 !

What I am thinking it's happening is the following: 
1- The module starts up and creates the tables defining as schemaVersion 1.0.5. The module is available to be use because it fulfills the release dependency (release.schemaVersion >= 1.0.0 and < 2.0.0 and status = ok)
2- However after that, the upgrade is processed and executed and during that time the module is not available because the status during that time is "in progress")
3- When the upgrade finishes, the module is available again.

My guess is that the race condition occurs when the portal accesses to the module before 1 and then those objects become unavailable.

Does it make sense @holatuwol and @dejuknow ?

If so, maybe we can add a static dependency with the schemaVersion 1.0.6 for the module so that the modules waits for the upgrade to be available. It's ugly but I hope that we can replace when this is available:
https://issues.liferay.com/browse/LPS-101216

**Comment by holatuwol** [comment]
> If so, maybe we can add a static dependency with the schemaVersion 1.0.6 for the module so that the modules waits for the upgrade to be available.

I think we'd be better off making it the upgrade process of a separate module.

**Comment by achaparro** [comment]
@holatuwol We also took into account that possibility but they need to execute direct SQL statements due to performance reasons. For that reason, we implemented it in the same module. Knowing that, do you still think that that's the best option?

**Comment by holatuwol** [comment]
> We also took into account that possibility but they need to execute direct SQL statements due to performance reasons. For that reason, we implemented it in the same module. Knowing that, do you still think that that's the best option?

@achaparro : Well, the way I see it is that the queries include the tables from the document library module. Once you've made assumptions about one set of tables that belong to a different module, making assumptions about another set of tables that belong to yet another module isn't too different.

**Comment by achaparro** [comment]
That's right @holatuwol.

In that case, how @dejuknow should implement the module so that it runs only for new customers, not for customers upgrading from previous versions, that's the requirement they have (more info in https://liferay.slack.com/archives/C03LW8NUK/p1567810917066300 and https://liferay.slack.com/archives/C03LW8NUK/p1567832342072600)

**Comment by holatuwol** [comment]
@achaparro : Based on the description in the Slack conversations, the requirement of "only run once" doesn't really solve any issues, because you can stop the sync modules at any time and then restart them, which means all of the tables would again be out of date at the time you restart.

So, I think it would be fine to just always run it once, regardless of the situation, and then provide an OSGi command so people can re-run the verify manually any time they've stopped the Sync modules for a period of time and then restarted them.

**Comment by achaparro** [comment]
I see @holatuwol,

Then the proposal should be:
1. Modify the logic to not create SyncObjects if they already exist on the table.
2. Move this logic to an OSGi command (see IndexUpdaterOSGiCommands for example) so that customers can execute this on-demand. We should document this process.

@dejuknow, is this enough for you to be able to complete the implementation?

**Comment by dejuknow** [comment]
@holatuwol @achaparro 

We actually have logic to update the tables w/ missed events when the sync modules activate (https://github.com/liferay/liferay-portal/blob/master/modules/apps/sync/sync-service/src/main/java/com/liferay/sync/internal/messaging/DLSyncEventMessageListener.java#L57-L90).

The problem with this approach for first-time installation is that performance can be quite bad with large record sets (though in theory we can still run into this problem even after deactivating the sync module, making lots of updates, then reactivating). The only purpose of running the "only run once" upgrade is to avoid this potential performance hit.

Moving the "only run once" logic to another module becomes problematic because I need it to run after the tables have been created by sync-service, but before the DLSyncEventMessageListener component is activated (and runs the logic to update missed events).

At this point, I'm leaning toward just releasing w/o the "only run once" upgrade step. Longer term, the better fix is to incorporate the performant logic into the module activation step.

**Comment by holatuwol** [comment]
> Moving the "only run once" logic to another module becomes problematic because I need it to run after the tables have been created by sync-service, but before the DLSyncEventMessageListener component is activated (and runs the logic to update missed events).

Since the two are related, you could move the `DLSyncEventMessageListener` to the new module, and then have it wait for that new module's upgrade process to complete.

**Comment by dejuknow** [comment]
@holatuwol: Talked to @achaparro this morning, and instead of shuffling a lot of code around, we agreed it's better to ship without the performance-focused one-time upgrade and implement it in the future when [LPS-101216](https://issues.liferay.com/browse/LPS-101216) is resolved (which @achaparro *promised* he'd implement by November 😉)

In the meantime, for customers with large doc repositories that may run into the slow upgrade issue, @jonathanmccann can provide customers with a Groovy script that runs the same performant upgrade process.

**Pull request closed without merging**
