### PR TITLE
LPS-73252 Product Menu Staging Variation dropdown should follow same pattern as other dropdowns in Product Menu

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@pyoo47 fyi, please see flaky errors

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/20c9452b15...096adb4ec8

**Comment by michaelhashimoto** [comment]
@brianchandotcom @pyoo47 - I think that we should be able to fix the random BladeSample test failures with this pull request:
https://github.com/brianchandotcom/liferay-jenkins-ee/pull/2347

I think there are stale results that are being pulled into the failure reports.

**Pull request closed without merging**
