### PR TITLE
Lps 86406

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
Resent of https://github.com/brianchandotcom/liferay-portal/pull/65337 , the SB gradle wiring was out of date, rebased.

@brianchandotcom this cleanup removes 16 exported packages from portal to spring extender, and reduces the portal/spring extender interaction down to just the new com.liferay.portal.spring.configurator.ConfigurableApplicationContextConfigurator (for spring parts, there is still some interactions for hibernate mapping, but that is not related to AOP. We can clean those up at a later time)
This will hide all the details in internal, leaving us the max freedom for future spring aop refactor. We will expose a new AOP api later when we are ready.

@inacionery please see 9eabe34 , it does not change any logic, and it is only a temporary solution, we will update it to use the new api once we have it ready.

@brianchandotcom when backport SB changes, please make sure you change spring.configurator.enabled to false in build.properties for older branches, and not backport this spring configurator change.
And once you release a new SDK zip, please go back master to regenerate for:
```
opensocial-portlet
powwow-portlet
tasks-portlet
```
CC @mhan810

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:reopen @michaelhashimoto @kenjiheigel @yichenroy please look into these failures?

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:reopen

**Comment by pyoo47** [comment]
It looks like something is broken with setup-sdk. I am able to recreate the problem locally.
```
pyoo-macbook-pro:pr pyoo$ ant setup-sdk
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
Buildfile: /Users/pyoo/dev/liferay-portal/pr/build.xml
  [taskdef] Could not load definitions from resource aQute/bnd/ant/taskdef.properties. It could not be found.
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /Users/pyoo/dev/liferay-portal/pr/null1095873570.properties

setup-sdk:
     [echo] 

BUILD FAILED
/Users/pyoo/dev/liferay-portal/pr/build.xml:1077: The following error occurred while executing this line:
/Users/pyoo/dev/liferay-portal/pr/build-common.xml:1460: The following error occurred while executing this line:
/Users/pyoo/dev/liferay-portal/pr/build-common.xml:847: /Users/pyoo/dev/liferay-portal/pr/build-common.xml:849: exec returned: 1
```

**Comment by jpince** [comment]
ci:close @shuyangzhou see Peter's comment above, looks like setup-sdk is broken

**Comment by jpince** [comment]
@vicnate5 fyi, big pull Shuyang's team is working on

**Comment by shuyangzhou** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/65365
It was still the out of date gradle wiring issue, I threw them away redid the whole updateFileVersions, should be fine now.

**Pull request closed without merging**
