### PR TITLE
[DO-NOT-BACKPORT-PLEASE] LPS-96705

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-96705

### CODE REVIEW

**Comment by kyle-miho** [comment]
Hey @brianchandotcom we don't want this backported to 7.2.x because of the huge risks it has.
cc: @jkappler

**Comment by kyle-miho** [comment]
ci:test

**Comment by jkappler** [comment]
Hey @brianchandotcom, it's as @kyle-miho said. This is the last pull from the ones I have been sending. I'll proceed next week to backport all three of them

Thanks again for everything

**Comment by kyle-miho** [comment]
fragment semvar / layout-seo-test failures are seperate

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/37614ec3c3...38b8eae13b

**Comment by brianchandotcom** [comment]
@jkappler smells good, trusting you! Not backported. Leaving it to you to do.

**Pull request closed without merging**
