### PR TITLE
LPS-57746 several fixes related to the product menu

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by kiyoshilee** [comment]
@juliocamarero the list of failures is too long to post. We're currently working on a way to truncate the failure message. For now, please see <a href="https://test-1-1.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/1008/jenkins-report.html">this link</a> for links to the tests that failed. You'll need to click <strong>Test Report</strong> for each AXIS_VARIABLE that is labeled <strong>UNSTABLE</strong> to see the tests that failed.

**Comment by brianchandotcom** [comment]
@juliocamarero please resend. Thx.

**Pull request closed without merging**
