### PR TITLE
LPS-67914 Adds missing resources importer marker

### PR DESCRIPTION
**Pull request by jbalsas**
Hey Brian, this already uses the `.lfrbuild-missing-resources-importer` mechanism that @ithildir will be adding shortly.

I'm sending it in ahead of time to see if build passes and you guys can merge after Andrea's gradle changes at the end of the day while I 😴 

Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
@kenjiheigel, could you take a look at these failures, please?

**Comment by kenjiheigel** [comment]
Local git was down earlier. Going to retrigger. 

ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/307d864f6a...7563dd0335

**Comment by brianchandotcom** [comment]
@codyhoag see modules/apps/frontend-theme-porygon/app.bnd

@jbalsas I merged this in, please see my changes in upstream.

Were the changes in

modules/apps/frontend-theme-porygon/frontend-theme-porygon/src/WEB-INF/liferay-plugin-package.properties

```
Liferay-JS-Config=/js/config.js
Provide-Capability=osgi.webresource;osgi.webresource=porygon-theme
```

intentional or accidental?

**Comment by jbalsas** [comment]
Hey @brianchandotcom, several of the changes you did upstream broke the build.

- All the marketplace themes have the `.gitignore` file: [westeros](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-theme-westeros-bank/frontend-theme-westeros-bank/.gitignore), [fjord](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-theme-fjord/frontend-theme-fjord/.gitignore)
- The `META-INF` folder is needed for the build process. I've tweaked the build to create it if it doesn't exist, but having a `META-INF/.touch` seemed easier at the time.
- The changes in `liferay-plugin-package.properties` were indeed intentional.
    - The `WabExtender` will get headers such as `Liferay-JS-Config` from there and not from a `bnd.bnd` file
    - The `Provide-Capability` is usually automatically added by our `NpmAnalyzer`, but themes don't go through that process, so we need to manually mark it as a webresource.

I've sent https://github.com/brianchandotcom/liferay-portal/pull/43696 with changes. Could you please Backport it automatically?

Thanks!

**Pull request closed without merging**
