### PR TITLE
LPS-81931 Search page template is not shown in global or when selecting a global template to create a new page

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9f33caa376...f779e0f034

**Comment by brianchandotcom** [comment]
@Preston-Crary @shuyangzhou see 9963a2fe5f053f09401cead9e131eeed2dc9520c I'm not sure if it's right

@jkappler I merged this, but I notified Preston and Shuyang in case your SF exclusion is just hiding a problem.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/60061

**Pull request closed without merging**
