### PR TITLE
LPS-68198

### PR DESCRIPTION
**Pull request by mikakoivisto**
LPS-68198 Allow only authenticated access to TunnelServlet

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest (we had to bounce all the ci servers)

**Comment by brianchandotcom** [comment]
Thx @mikakoivisto @topolik

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c0f29552c4...ea5dfcedef

**Pull request closed without merging**
