### PR TITLE
LPS-61577 Change references in last minute additions

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Fixing one true sf issue. The rest are due to the changes in SourceFormatter included in the pull.

**Comment by JorgeFerrer** [comment]
ci:retest

**Comment by brianchiu** [comment]
@vicnate5
The random error with the RepeatingTextField test is still happening where the "C" in "Created" gets cut off. Can you either add an explicit pause or find something else on the page to wait for?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/43c036b92c...1e965ab20b

**Pull request closed without merging**
