### PR TITLE
Lps 67049

### PR DESCRIPTION
**Pull request by shuyangzhou**
This is going to fail the SF test due to importing internal class.

@Ithildir you will continue this with move those constants class out of internal package and do a proper export as we talked last week, right?

CC @hhuijser

### CODE REVIEW

**Comment by Ithildir** [comment]
@shuyangzhou, if I remember correctly, didn't we talk about moving the unit tests out of the `-test` modules? So shouldn't `PingbackMethodImplTest` be moved to `blogs-service`?

**Comment by shuyangzhou** [comment]
Yes, I thought you are going to do it by some script? Or you want @tomwang2011 to do it manually? But before any of that, we are currently importing some internal classes, which is failing the SF test. Last time we talked, you are going to move those internal constants classes out again, and export them properly, right?

**Comment by shuyangzhou** [comment]
@tomwang2011 I talked to @Ithildir . He wants you to do this manually for moving the constants class back to exported package, and move the unit test classes into the service module. Please resend with those changes,

**Comment by Ithildir** [comment]
If you want, I can come up with a script to move the unit tests out of the `-test` modules :blush: But exporting the constant class is a manual process, I don't think I have simple ways to automate it, it's probably not worth it.

**Comment by shuyangzhou** [comment]
Yeah, don't bother, since we are doing this one by one anyway. @tomwang2011 can just do it manually.

**Pull request closed without merging**
