### PR TITLE
LPS-161819

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Manually forwarding because the [CI accused failure](https://github.com/liferay-objects/liferay-portal/pull/1017#issuecomment-1256085131) is not related to this.

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@rodrigopaulino @murilostodolni potential NPE

```
		ObjectRelationship objectRelationship =
			_objectRelationshipPersistence.fetchByObjectFieldId2(objectFieldId);

		if (StringUtil.equals(
				objectRelationship.getDeletionType(),
				ObjectRelationshipConstants.DELETION_TYPE_DISASSOCIATE) &&
			required) {
```

Please resend.

**Comment by rodrigopaulino** [comment]
Hey, @brianchandotcom. The idea is that this will only be executed if the field type is relationship, therefore there's always going to be a relationship linked to the field. Does it make any sense?

**Comment by rodrigopaulino** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4016b4cd4e...c73e2c384a

**Comment by brianchandotcom** [comment]
@rodrigopaulino @murilostodolni see changes in my origin. Thx.

**Pull request closed without merging**
