### PR TITLE
LPS-0 Revert baseline workaround

### PR DESCRIPTION
**Pull request by petershin**
Hi Brian, these fixes look like they're no longer needed.  The `baseline` task runs w/o any errors.

Regarding the `modules-semantic-versioning` failures in the `7.x` branches, the app server bundle wasn't being unzipped before the test was run and I think its needed for the `generateJSPJava` task.

The `LRCI` team added a patch to the relevant `Ant` task and is testing the fix.

### CODE REVIEW

**Comment by petershin** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5a7f4a69e5...aac4ba7c4d

**Comment by brianchandotcom** [comment]
@petershin can you Slack me if we should merge in https://github.com/brianchandotcom/liferay-portal/pull/78645

I"m afraid that as soon as I merge that one in, another fix will be required.

**Comment by petershin** [comment]
@brianchandotcom - Looking into it

**Comment by petershin** [comment]
@brianchandotcom - It looks like the root cause was cf4c63dc96c988f68f2c47137863c4966673044d.

I'm running baseline for all `apps`, `portal-impl` and `portal-kernel`  to see if anything else changes.

**Pull request closed without merging**
