### PR TITLE
Lps 82647

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by jpince** [comment]
ci:close @drewbrokke @shuyangzhou I'm nervous about all of the modules-integration test failures related to document library. Can you please take a look?

**Comment by shuyangzhou** [comment]
ci:reopen

@jpince not related, they were caused by 95fbdfe804da567b1a128a760d4085bda67641c5 and fixed by 72b8db5c35d09cbcffc020775d4cfae6c69610ee

**Comment by shuyangzhou** [comment]
ci:retest
Running again anyway

**Comment by jpince** [comment]
@shuyangzhou looks good, thanks

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7386a544d8...0480859969

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
