### PR TITLE
LPS-95937 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LPS-95937

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by john-co** [comment]
Hi @boton, it looks like https://github.com/brianchandotcom/liferay-portal/pull/73461 was the first PR that causes the js unit test to fail. Reverting the commits also resolves the issue. Please turn the test back on when it's fixed. Thank you.

cc/ @carloslancha @jbalsas

**Comment by john-co** [comment]
ci:reopen

**Comment by john-co** [comment]
@patriciajeanperez, @austinchiang

**Comment by john-co** [comment]
ci:test:relevant

**Comment by boton** [comment]
@john-co thanks, I will take a look

**Pull request closed without merging**
