### PR TITLE
LPS-99291 SF

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6cb1184ca7...0cd2f3bc71

**Comment by brianchandotcom** [comment]
@epgarcia I did not backport.

**Comment by dgarciasarai** [comment]
Thanks!

**Pull request closed without merging**
