### PR TITLE
LPS-61088 Remove classes and resources dir from Include-Resource

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@rotty3000 this is good.. I just fixed hte APE tests.. so please ignore failures.

**Comment by brianchandotcom** [comment]
@hhuijser can you enforce via SF? Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/eb72f50a34...1b0e1275bc

**Comment by brianchandotcom** [comment]
@hhuijser for bnd, can you also enforce SF so that if it's a one line item, it'll put it in one line.

See modules/util/sass-compiler-ruby/bnd.bnd

```
Include-Resource:\
	@lib/com.liferay.ruby.gems.jar
```

Should just be

Include-Resource: @lib/com.liferay.ruby.gems.jar

Thx

**Pull request closed without merging**
