### PR TITLE
LPS-52703 Copy Liferay AMD Loader from node_modules to the JAR and remove the manually added version.

### PR DESCRIPTION
**Pull request by ipeychev**

### CODE REVIEW

**Comment by ipeychev** [comment]
Hello @brianchandotcom,

This PR depends on https://github.com/brianchandotcom/liferay-plugins/pull/4767

Thanks,

**Comment by brianchandotcom** [comment]
@ipeychev still not working. For some reason it thinks it's Darwin and not CentOS.

Please resend. Thx.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Still broken, please resend.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/57e798bd85...eb80ebe296

**Comment by brianchandotcom** [comment]
@ipeychev pushed upstream. please see my changes. Thx.

**Pull request closed without merging**
