### PR TITLE
master-qa-21251

### PR DESCRIPTION
**Pull request by vicnate5**
https://issues.liferay.com/browse/LRQA-21251

Added a pause and a click to prevent test failures. The click is actually what a real user would need to do in order to input the name field. @brianchiu

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@brianchiu we still have this random SubmitForm failure.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/464eecac93...eb4c446f27

**Comment by vicnate5** [comment]
@brainchiu I will take another look at this.

**Comment by vicnate5** [comment]
Sent a better fix https://github.com/brianchandotcom/liferay-portal/pull/34629

**Pull request closed without merging**
