### PR TITLE
LPS-78459

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@brianchandotcom don't cherry pick this one. It's not going to work. I will send you a backport after this is in.

**Comment by hhuijser** [comment]
ci:test

**Comment by hhuijser** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@hhuijser can you resend this? I need a parallel pull for 7.0.x since this one doesn't cherry pick cleanly. Thx.

**Pull request closed without merging**
