### PR TITLE
LPS-47066 In-product links to the documentation in the Query Builder

### PR DESCRIPTION
**Pull request by oliv-yu**
From https://github.com/liferay-search/liferay-portal/pull/339

From QA: failures are happening upstream as well and are unrelated.

---
https://issues.liferay.com/browse/LPS-147066 - As a Blueprints user, I can see in-product links to the documentation in the Query Builder

Extra improvements / fixes to this ticket! Includes:
- Links will open a new tab instead of redirecting the page
- Period removed from `Learn how` in blueprint option's `Learn how to setup blueprint options`
- Removal of tooltips on clause contributors / indexer clauses 

@thektan @joshchong

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/10be0a19aa...7d49539fc7

**Comment by brianchandotcom** [comment]
@oliv-yu see 7d49539fc7a7eb934cef2780a434e28bef92c27a thx

**Comment by oliv-yu** [comment]
Hi @brianchandotcom ! We actually left the period out since it would look like this:

Screen Shot 2022-03-16 at 11 33 19 AM

But just discussed it with @rbohl and I'll just adjust this to become the full sentence to remain consistent 😸

**Comment by rbohl** [comment]
@oliv-yu while you're in there can we also use "set up" instead of "setup"?

**Pull request closed without merging**
