### PR TITLE
LPS-204785 Adds an UpgradeProcess for LPS-199595 to add the missing fragment link usages

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://liferay.atlassian.net/browse/LPS-204785
https://liferay.atlassian.net/browse/LPS-199595

@lfbesada

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/14852

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1d9cb29f17...26e514b4fc

**Comment by brianchandotcom** [comment]
@lfbesada just 26e514b4fc86c054b1f8a00f02d32c3f4a2219d5

**Pull request closed without merging**
