### PR TITLE
LPS-75902 Whenever one node clears the session, the other nodes shoul…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…d too

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@mbowerman please manually test that this does work, since MailService is a little different from all the other generated services, and I want to make sure it does pick up @Clusterable. Thx.

**Comment by shuyangzhou** [comment]
ci:reopen

@brianchandotcom I believe @mbowerman has tested it already. I asked @preston-crary to ask @mbowerman to test it.
And although mail service is hard coded , it is still a service, all the aops still apply.
So this should be fine.

And Happy Thanksgiving!

**Comment by brianchandotcom** [comment]
Merged. Thx!

**Pull request closed without merging**
