### PR TITLE
LPS-57746 filter panels of product menu

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@kiyoshilee is this a case where tests are so broken that it won't post the failure?

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by kiyoshilee** [comment]
@juliocamarero the list of failures can be seen <a href="https://test-1-2.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/1012/jenkins-report.html">here</a>. Here are the links to the failures for <a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/4979//testReport">integration-db2</a>, <a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/4993//testReport">integration-oracle</a>, <a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/5048//testReport">integration-postrgresql</a>, <a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/5030//testReport">modules-integration-db2</a>, <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/4967//testReport">modules-integration-mysql</a>, <a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/5041//testReport">modules-integration-oracle</a>, and <a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/4981//testReport">modules-integration-postgresql</a>.

**Comment by michaelhashimoto** [comment]
@brianchandotcom - I am running this pull request against a fix to truncate the unstable errors here:
https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest(master)/1026/

Here's the jenkins pull request that is trying to fix this issue:
https://github.com/brianchandotcom/liferay-jenkins-ee/pull/985

**Comment by brianchandotcom** [comment]
@juliocamarero please resend due to errors. Thx.

**Pull request closed without merging**
