### PR TITLE
LPS-87729 

### PR DESCRIPTION
**Pull request by tinatian**
Hi guys @shuyangzhou @mhan810 @vicnate5 @jhinkey,

This pull is going to make clustering same for EE and CE as we talked in email, including:
1) Remove ehcache RMI replication support
2) Remove all the single modules which works a place holder before
3) Copy portal-cache-mulitple from EE to CE, to use cluster link to do cache replication

Thanks.
Tina.

### CODE REVIEW

**Comment by vicnate5** [comment]
Test failures on this pull are unrelated.

One of the clustering tests failed because the elasticsearch server did not start. However, this looks like flakiness, because the other tests did not fail on this same step and configuration.

**Comment by tinatian** [comment]
Thanks @vicnate5 !

**Comment by brianchandotcom** [comment]
Merged. Thank you.

View just my changes: https://github.com/brianchandotcom/liferay-portal/compare/tinatian:38283a91a8...f6ce2796cb
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b9f365b74f...f6ce2796cb

**Comment by brianchandotcom** [comment]
Great job @tinatian and @vicnate5 !

**Pull request closed without merging**
