### PR TITLE
LPS-100592 Create the account-user association entity and API

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-100592](https://issues.liferay.com/browse/LPS-100592).

Hey Brian, this pull is just the basic generation of the `AccountEntryUserRel` entity and service.
- Define service.xml
- Autogenerated
- Auto SF

/cc @pei-jung @alee8888 @ChrisKian @dejuknow

### CODE REVIEW

**Comment by drewbrokke** [comment]
@pyoo47 is this a real failure?

**Comment by pyoo47** [comment]
@drewbrokke Looks real to me.
```
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/account/account-api/src/main/java/com/liferay/account/service/persistence/AccountEntryUserRelPK.java:17: error: package com.liferay.petra.lang does not exist
     [exec] import com.liferay.petra.lang.HashUtil;
     [exec]                              ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/account/account-api/src/main/java/com/liferay/account/service/persistence/AccountEntryUserRelPK.java:18: error: package com.liferay.petra.string does not exist
     [exec] import com.liferay.petra.string.StringBundler;
     [exec]                                ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/account/account-api/src/main/java/com/liferay/account/service/persistence/AccountEntryUserRelPK.java:122: error: cannot find symbol
     [exec] 		hashCode = HashUtil.hash(hashCode, accountEntryId);
     [exec] 		           ^
     [exec]   symbol:   variable HashUtil
     [exec]   location: class AccountEntryUserRelPK
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/account/account-api/src/main/java/com/liferay/account/service/persistence/AccountEntryUserRelPK.java:123: error: cannot find symbol
     [exec] 		hashCode = HashUtil.hash(hashCode, userId);
     [exec] 		           ^
     [exec]   symbol:   variable HashUtil
     [exec]   location: class AccountEntryUserRelPK
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/account/account-api/src/main/java/com/liferay/account/service/persistence/AccountEntryUserRelPK.java:130: error: cannot find symbol
     [exec] 		StringBundler sb = new StringBundler(6);
     [exec] 		^
     [exec]   symbol:   class StringBundler
     [exec]   location: class AccountEntryUserRelPK
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/account/account-api/src/main/java/com/liferay/account/service/persistence/AccountEntryUserRelPK.java:130: error: cannot find symbol
     [exec] 		StringBundler sb = new StringBundler(6);
     [exec] 		                       ^
     [exec]   symbol:   class StringBundler
     [exec]   location: class AccountEntryUserRelPK
     [exec] 6 errors
     [exec] 
     [exec] > Task :apps:account:account-api:compileJava FAILED
```

**Comment by drewbrokke** [comment]
Thanks!

**Comment by drewbrokke** [comment]
Looks like I accidentally left out a commit when switching branches.

**Comment by drewbrokke** [comment]
Resent as https://github.com/brianchandotcom/liferay-portal/pull/78026

**Pull request closed without merging**
