### PR TITLE
LPS-69483 Wrong url in email notification when impersonating user

### PR DESCRIPTION
**Pull request by sergiogonzalez**
https://github.com/sergiogonzalez/liferay-portal/pull/3805#issuecomment-282013771
@robertoDiaz

### CODE REVIEW

**Comment by robertoDiaz** [comment]
👍

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
