### PR TITLE
LPS-169282

### PR DESCRIPTION
**Pull request by eltonccdantas**
[Original PR ](https://github.com/liferay-frontend/liferay-portal/pull/3267)

**Motivation**
JAWS read the hidden legend as a navigable element
Link to story or ticket

**Proposed Solution**
The solution is the same we did for #3228. We have replaced the `<fieldset>` element with` <div role=“group”>` , removed the legend element and added an aria-label to the <div role=“group”> with the text that the legend had.

**Steps to Verify:**

1. Navigate to Site Builder->Pages and add a page
2. Navigation to Global templates
3. Add a new Global template
4. Input the page name
5. Navigate to the General tab
6. Use jaws
7. Using the arrow key to traverse the page

### CODE REVIEW

**Comment by eltonccdantas** [comment]
ci:reopen

**Comment by eltonccdantas** [comment]
ci:forward:force

**Comment by eltonccdantas** [comment]
ci:reopen

**Comment by eltonccdantas** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3bd66faa80...63e61a2553

**Pull request closed without merging**
