### PR TITLE
LPS-84119

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@brianchandotcom, please publish portal-impl

**Comment by hhuijser** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@hhuijser published portal-impl 2.53.0 that has your new method.

**Comment by jpince** [comment]
@hhuijser caused a semver failure, see test result and https://github.com/liferay/liferay-portal/commit/d1c044d19df4ed37db902243cd980ca4309b8b5f

**Pull request closed without merging**
