### PR TITLE
LPS-63233 Avoid fallback to a theme that is designed for control panel

### PR DESCRIPTION
**Pull request by epgarcia**
My proposal for LPS-63233 is to exclude control panel themes as fallback themes. The ThemeLocalServiceImpl#getTheme method does already exclude them in the first fallback:

```
if (theme != null) {
    return theme;
}

if (_log.isWarnEnabled()) {
    _log.warn(
        "No theme found for specified theme id " + themeId +
            ". Returning the default theme.");
}

themeId = ThemeFactoryUtil.getDefaultRegularThemeId(companyId);
```

But in the second fallback, any installed theme (including control panel themes) were included, which was not consistent.

@natecavanaugh
@jbalsas
@juliocamarero

### CODE REVIEW

**Comment by jbalsas** [comment]
We might still run into trouble after this, but I think it looks good enough for now. Thanks @epgarcia!!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/079f404104...8b592248c8

**Comment by epgarcia** [comment]
@ZoltanTakacs

**Comment by ZoltanTakacs** [comment]
Thank you @epgarcia. It's been merged to 7.0.x.

Please note that the backport workflow has been changed for the RCs. 
For the details please see @jhendley 's email or refer to this [document](https://docs.google.com/document/d/1A-EoPvI1KDDpUH2PAlKmpgUDb_2RFM4iwpB_4loQHFk/edit).

Thank you,
Zoltán

**Pull request closed without merging**
