### PR TITLE
LPS-76263 Adds missing build dependency

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jpince** [comment]
ci:close

**Comment by jpince** [comment]
@jbalsas @Robert-Frampton SF.
```
     [java] Incorrect line break: ./modules/apps/foundation/frontend-taglib/frontend-taglib/src/main/java/com/liferay/frontend/taglib/servlet/taglib/soy/DiffVersionComparatorTag.java 49
     [java] There should be a line break after '(': ./modules/apps/foundation/frontend-taglib/frontend-taglib/src/main/java/com/liferay/frontend/taglib/servlet/taglib/soy/DiffVersionComparatorTag.java 49
     [java] There should be a line break before 'throws': ./modules/apps/foundation/frontend-taglib/frontend-taglib/src/main/java/com/liferay/frontend/taglib/servlet/taglib/soy/DiffVersionComparatorTag.java 50
     [java] There should be an empty line before line '66', as we finished referencing variable 'timeDescription': ./modules/apps/foundation/frontend-taglib/frontend-taglib/src/main/java/com/liferay/frontend/taglib/servlet/taglib/soy/DiffVersionComparatorTag.java 66
     [java] Private constant 'languageKeys' must match pattern '^_[_a-zA-Z0-9]*$': ./modules/apps/foundation/frontend-taglib/frontend-taglib/src/main/java/com/liferay/frontend/taglib/servlet/taglib/soy/DiffVersionComparatorTag.java 247
```
The failure is listed under "Failures in common with acceptance upstream results", but I think that's because it compares the batch name, not the error message.

**Comment by jpince** [comment]
See the PMD failure, also :)

**Comment by jbalsas** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/53983

**Pull request closed without merging**
