### PR TITLE
LPS-74296

### PR DESCRIPTION
**Pull request by Ithildir**
cc @jpince

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by jpince** [comment]
@Ithildir are your changes missing something?
`/opt/dev/projects/github/liferay-portal/util-bridges/build.xml:21: Warning: Could not find file /opt/dev/projects/github/liferay-portal/lib/portal/portals-bridges.jar to copy.`

**Comment by Ithildir** [comment]
@jpince, I didn't change anything in the build scripts...

**Comment by Ithildir** [comment]
@brianchandotcom, @jpince, @kiyoshilee, I pushed https://github.com/liferay/liferay-portal/commit/10d6be507011e7523b9f7e28186a5039cf22febf to fix the CI problem.

**Comment by jpince** [comment]
@pyoo47 @michaelhashimoto fyi

**Pull request closed without merging**
