### PR TITLE
LPS-166931 Renamed last parameters

### PR DESCRIPTION
**Pull request by gislayne-vitorino**
This is an update related to [LPS-166931](https://issues.liferay.com/browse/LPS-166931). In order to undo some changes that have caused failures on users and accounts when trying to add a prefix and/or suffix

### CODE REVIEW

**Comment by gislayne-vitorino** [comment]
ci:reopen

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:reopen

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by gislayne-vitorino** [comment]
ci:reopen

**Comment by gislayne-vitorino** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d5e4ac9129...9583f7475e

**Pull request closed without merging**
