### PR TITLE
LPS-163792 Add pagination page link for Web Contents

### PR DESCRIPTION
**Pull request by jkappler**
[Jira issue](https://issues.liferay.com/browse/LPS-163792)

## Motivation

We'll render a button pointing to the main versions view for a web content.
This button is hidden if the number of versions of the asset is lower that the number of versions displayed by default in the tab.

## Solution proposed

The BE only sends the property `viewVersionsURL` with a value if the button needs to be render.
This way the FE knows how to properly build the UI.

## How to verify

- Create a web content
- Generate 11 versions, at least, for the asset
- Visit the Content Dashboard
- Click on the item info button in order to open the sidebar panel
- In the sidebar panel, click on Versions tab
**Expected**: a _View More_ button s shown at the bottom of the versions list, linking to the main versions list for the asset

image

### CODE REVIEW

**Comment by jkappler** [comment]
ci:reopen

**Comment by jkappler** [comment]
@brianchandotcom, sending you directly because of the issues with typescript. All relevant and stable tests pass: https://github.com/liferay-tango/liferay-portal/pull/2881

cc:// @beltranrengifo, @claraizquierdo, @cgoncas

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/527e32e624...93cfe4869a

**Comment by brianchandotcom** [comment]
@claraizquierdo @jkappler @beltranrengifo just 93cfe4869ab0342caa621437a242a3588012aea3

**Pull request closed without merging**
