### PR TITLE
LPS-61111 Unable to delete user from user group

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-61111](https://issues.liferay.com/browse/LPS-61111).<br><br>/cc @pei-jung

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@drewbrokke "PoshiRunner.test[CPUsersandorganizations#AddMember] - Poshi Report - Poshi Summary - Console Output" is real no?

**Comment by drewbrokke** [comment]
Looks very possible.  Investigating now... :)

**Comment by alee8888** [comment]
@brianchandotcom @drewbrokke 
Combined Drew's commits with Poshi functional test fixes for LPS-61111 in the following PR:
https://github.com/brianchandotcom/liferay-portal/pull/33375

**Pull request closed without merging**
