### PR TITLE
LPS-64666 Check if authentication is needed

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
cc @marcellustavares

**Comment by leoadb** [comment]
ci:retest

**Comment by marcellustavares** [comment]
thanks @leoadb

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b5ce9975a1...5d95fd67f1

**Pull request closed without merging**
