### PR TITLE
Lps 75757

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/46d35746d9...3176fe4e4a

**Comment by brianchandotcom** [comment]
@shuyangzhou see my baseline fix in dfa1d3dddb472c3c939756233cfee475f71c7415

**Comment by shuyangzhou** [comment]
Thanks @brianchandotcom !

**Pull request closed without merging**
