### PR TITLE
LPS-162366 Upgrade Process

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-162366

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:reopen

**Comment by p-albuquerque** [comment]
Fix order mentioned here: https://github.com/brianchandotcom/liferay-portal/pull/123634#issuecomment-1256960366

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ca1fd7b4aa...f8e120e0c9

**Comment by brianchandotcom** [comment]
@p-albuquerque see a9167b5c810da96727e1fbfcc1ca0de7c3f878be be540ba68d92995af636a80801d255a42a20e24a and f8e120e0c9aac55d84011b7a2bdc3745dcdd117b

**Pull request closed without merging**
