### PR TITLE
LPS-160268 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-160268

This is only for master.

@jkappler
cc @sandrodw3

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure cases are unrelated to changes.
See https://github.com/liferay-echo/liferay-portal/pull/9323
✔️ ci:test:stable - 27 out of 27 jobs passed
❌ ci:test:relevant - 167 out of 188 jobs passed in 2 hours 27 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3cb5191f1e...243917c1d0

**Comment by brianchandotcom** [comment]
@jkappler see a99de422f1e3ecbf0ad3a2cc80ee153bab6d3b25

**Pull request closed without merging**
