### PR TITLE
LPS-75306 Permission checkers

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Already somewhat passed here https://github.com/brianchandotcom/liferay-portal/pull/53496#partial-pull-merging ( just for logging)

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
@michaelhashimoto
Has someone in QA looked into this error:

```
Caused by: java.lang.IllegalArgumentException: Core threads must have nonzero keep alive times
	at java.util.concurrent.ThreadPoolExecutor.allowCoreThreadTimeOut(ThreadPoolExecutor.java:1642)
	at com.liferay.jenkins.results.parser.JenkinsResultsParserUtil.getNewThreadPoolExecutor(JenkinsResultsParserUtil.java:767)
	at com.liferay.jenkins.results.parser.TopLevelBuild.<clinit>(TopLevelBuild.java:1251)Caused by: java.lang.IllegalArgumentException: Core threads must have nonzero keep alive times
	at java.util.concurrent.ThreadPoolExecutor.allowCoreThreadTimeOut(ThreadPoolExecutor.java:1642)
	at com.liferay.jenkins.results.parser.JenkinsResultsParserUtil.getNewThreadPoolExecutor(JenkinsResultsParserUtil.java:767)
	at com.liferay.jenkins.results.parser.TopLevelBuild.<clinit>(TopLevelBuild.java:1251)
```

**Comment by brianchandotcom** [comment]
ci:test @Preston-Crary I think @pyoo47 fixed it?

I'm retesting just to be safe.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/5404

**Pull request closed without merging**
