### PR TITLE
LPS-89468 / LPS-90075 Let admins configure sharing status

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@nikki-pru @patriciajeanperez

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9ee099528d...82b66136ac

**Pull request closed without merging**
