### PR TITLE
LPS-79919

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:test (borrowing this pull to test upstream)

**Comment by hhuijser** [comment]
Related pulls:
https://github.com/brianchandotcom/liferay-portal-ee/pull/19944
https://github.com/brianchandotcom/liferay-portal-ee/pull/19945
https://github.com/brianchandotcom/liferay-portal-ee/pull/19946

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@shuyangzhou lpkg override error. fyi.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
