### PR TITLE
LRQA-64636 User longer term license

### PR DESCRIPTION
**Pull request by vicnate5**
@brianchandotcom This can also go back to 7.3.x. The license files we are committing here are invalid for any real release.

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:reopen

**Comment by vicnate5** [comment]
@kyle-miho Please send me a follow up to fix the tests I disabled https://github.com/brianchandotcom/liferay-portal/pull/99533/commits/dfbec7245f16e9a9862f42a0f7f0bb44d843d482

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ed63c9196d...1ff3351db4

**Comment by brianchandotcom** [comment]
@vicnate5 I backported this to 7.3.x.

It would be nice if

```
					<get-testcase-property property.name="commerce.enabled" />
					<get-testcase-property property.name="custom.commerce.license" />
```

Both of them started with commerce.*

So then the properties are grouped together. Can you try and come up with a better name?

**Pull request closed without merging**
