### PR TITLE
LPS-85462 Support for ge and le (greater or equals/ lower or equals) in filters

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
@cgoncas @ruben-pulido

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:close, looks like this has already been merged in https://github.com/brianchandotcom/liferay-portal/pull/63187

**Pull request closed without merging**
