### PR TITLE
LPS-57564 Create new portlet for the pages of the page templates and declare p_r_p to communicate product menu and layouts admin

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2d9068a4e5...39c4fa9ec6

**Comment by brianchandotcom** [comment]
@ealonso @juliocamarero did we forget the language key? See 7a690166c60bc91f4b9fbb5d44d1739c30272e00

Thx.

**Comment by juliocamarero** [comment]
@brianchandotcom the portlet is never shown in any UI. It's only used for showing entries in the product menu and the title is never visible. I think we shouldn't add the key.

**Comment by brianchandotcom** [comment]
@ealonso @juliocamarero I rolled back my lang key change.

Does modules/apps/layout/layout-admin-web/src/main/java/com/liferay/layout/admin/web/portlet/LayoutPrototypePagePortlet.java

need

"javax.portlet.resource-bundle=content.Language"

? It's in there right now.

**Comment by juliocamarero** [comment]
@brianchandotcom thanks a lot! Yes, that is needed for the keys used by the panels of the portlet. thanks!

**Pull request closed without merging**
