### PR TITLE
LPS-65862 Registered user is owner of own personal site

### PR DESCRIPTION
**Pull request by topolik**
Including again what was reverted in https://github.com/brianchandotcom/liferay-portal/pull/40095 (my personal record for number of reverts on a single change) :)

Fixed portlet-tck-bridge which silently expected permissions granted to Power User.

PR to myself had TCK tests green: https://github.com/topolik/liferay-portal/pull/347. The failing tests seems similar to other PRs today like in https://github.com/brianchandotcom/liferay-portal/pull/40129 :(

Thanks.

https://issues.liferay.com/browse/LPS-65862

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:stop (upstream had an issue)

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c24d657552...fac5c80ea6

**Comment by brianchandotcom** [comment]
@topolik instead of reverting a revert of a revert, I just cherry picked your original revert :)

**Comment by topolik** [comment]
:+1: :)

**Pull request closed without merging**
