### PR TITLE
LPS-62665

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 hung too

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by mhan810** [comment]
@brianchandotcom these seem unrelated

**Comment by mhan810** [comment]
was successful in https://github.com/mhan810/liferay-portal/pull/1104

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
Actually @mhan810 I closed the wrong pull, but I'm not able to rebase. Can you resend? Thx.

**Pull request closed without merging**
