### PR TITLE
LPS-105981 Fix master compile

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @jbalsas @pavel-savinov @leoadb @brunobasto

see: https://github.com/brianchandotcom/liferay-portal/pull/84686 

I decided to not deploy it for the moment since the portal don't compile.

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6afad2bcae...e857bc2ea5

**Comment by brianchandotcom** [comment]
@leoadb type:

gradlew :apps:journal:journal-article-dynamic-data-mapping-form-field-type:jar

and it breaks.

Merging in this exclude. Please fix.

**Pull request closed without merging**
