### PR TITLE
LPS-94368 Make it private

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
ci:test:relevant
Retesting, previous test encountered intermittent failure and is under investigation:
Execution failed for task ':apps:frontend-theme:frontend-theme-admin:npmRunBuild'

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7915c32414...89c797cb86

**Comment by brianchandotcom** [comment]
@leoadb @gabrielwas @brunofarache @jeyvison see 89c797c shortcut

**Comment by leoadb** [comment]
@brianchandotcom Thanks!!

**Pull request closed without merging**
