### PR TITLE
LPS-78272 Adjust timeline and buttons styles

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@pavel-savinov @ealonso see upstream for my changes?

@petershin we're close to getting green! Can you fix the SF error? Thx.

**Comment by petershin** [comment]
@brianchandotcom - @jeyvison is working on the fix for `Unprocessed exception 'WorkflowException'`

The other issue is fixed  by https://github.com/brianchandotcom/liferay-portal/pull/55792

**Comment by petershin** [comment]
Sent fixes: https://github.com/brianchandotcom/liferay-portal/pull/55797

**Pull request closed without merging**
