### PR TITLE
LPS-101887 Fix cancel check out.

### PR DESCRIPTION
**Pull request by cgoncas**
Hey @brianchandotcom!

With this escape, we can use " instead ' in the onClick attribute.

@jbalsas @adolfopa

Thanks!

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:onlineediting

**Comment by Hanlf** [comment]
ci:stop

**Comment by john-co** [comment]
Just started analyzing :)

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated.

Functional test WidgetPages#EditSitePage failed on network connection issue on yarnInstallPrivate task

```
    [exec] > Task :yarnInstallPrivate
     [exec] yarn install v1.13.0
     [exec] [1/4] Resolving packages...
     [exec] [2/4] Fetching packages...
     [exec] info There appears to be trouble with your network connection. Retrying...
     [exec] info There appears to be trouble with your network connection. Retrying...
     [exec] info There appears to be trouble with your network connection. Retrying...
     [exec] info There appears to be trouble with your network connection. Retrying...
     [exec] error An unexpected error occurred: "https://registry.yarnpkg.com/electron-to-chromium/-/electron-to-chromium-1.3.220.tgz: tunneling socket could not be established, cause=connect ETIMEDOUT 10.50.0.41:3128".
     [exec] info If you think this is a bug, please open a bug report with the information provided in "/opt/dev/projects/github/liferay-portal/modules/private/yarn-error.log".
     [exec] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
     [exec] 
     [exec] > Task :yarnInstallPrivate FAILED
```

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/aac4ba7c4d...6575657bfc

**Pull request closed without merging**
