### PR TITLE
LPS-102214 Match signature method for segments experiments creation with the one in SegmentsExperimentServiceImpl

### PR DESCRIPTION
**Pull request by darquesdev**
From https://github.com/brianchandotcom/liferay-portal/pull/78852#issuecomment-535121318

Hi @brianchandotcom, I've tried to match as much as possible the signature of method `com.liferay.segments.asah.connector.internal.client.model.util.ExperimentUtilTest#_createSegmentsExperiment `with `com.liferay.segments.service.impl.SegmentsExperimentServiceImpl#addSegmentsExperiment`. Did I get it correctly? 
As you can see, one method requires more parameters than other, which is ok for me (they're doing different things) . Let me know if it requires more changes. Thanks!

@epgarcia

### CODE REVIEW

**Comment by brianchandotcom** [comment]
public SegmentsExperiment updateSegmentsExperimentStatus(
			String segmentsExperimentKey, String winnerSegmentsExperienceKey,
			int status)
		throws PortalException {

See how 'winnerSegmentsExperienceKey'  is before 'status'

That is not true here

```
	private SegmentsExperiment _createSegmentsExperiment(
		long segmentsExperienceId, long classPK, String name,
		String description, String goal, String goalTarget, Date createDate,
		Date modifiedDate, String segmentsExperimentKey, int status,
		String winnerSegmentsExperienceKey) {
```

Please resend.

**Comment by brianchandotcom** [comment]
@darquesdev also note the order of

```
		Mockito.doReturn(
			classPK
		).when(
			segmentsExperiment
		).getClassPK();

		Mockito.doReturn(
			createDate
		).when(
			segmentsExperiment
		).getCreateDate();

		Mockito.doReturn(
			modifiedDate
		).when(
			segmentsExperiment
		).getModifiedDate();

		Mockito.doReturn(
			name
		).when(
			segmentsExperiment
		).getName();

		Mockito.doReturn(
			description
		).when(
			segmentsExperiment
		).getDescription();

		Mockito.doReturn(
			segmentsExperienceId
		).when(
			segmentsExperiment
		).getSegmentsExperienceId();

		Mockito.doReturn(
			segmentsExperimentKey
		).when(
			segmentsExperiment
		).getSegmentsExperimentKey();

		Mockito.doReturn(
			goal
		).when(
			segmentsExperiment
		).getGoal();

		Mockito.doReturn(
			goalTarget
		).when(
			segmentsExperiment
		).getGoalTarget();

		Mockito.doReturn(
			status
		).when(
			segmentsExperiment
		).getStatus();

		Mockito.doReturn(
			winnerSegmentsExperienceKey
		).when(
			segmentsExperiment
		).getWinnerSegmentsExperienceKey();

```

does not match the method

```
	private SegmentsExperiment _createSegmentsExperiment(
		long segmentsExperienceId, long classPK, String name,
		String description, String goal, String goalTarget, Date createDate,
		Date modifiedDate, String segmentsExperimentKey, int status,
		String winnerSegmentsExperienceKey) {
```

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
Please, review https://github.com/brianchandotcom/liferay-portal/pull/78917

**Pull request closed without merging**
