### PR TITLE
LPS-64531 SF - Invert condition

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@adolfopa rebase error, please resend. Thx. @robertoDiaz

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Resent [here](https://github.com/brianchandotcom/liferay-portal/pull/38233)

**Pull request closed without merging**
