### PR TITLE
LPS-75175

### PR DESCRIPTION
**Pull request by Ithildir**
cc @andywu2015

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:reopen

**Comment by pyoo47** [comment]
@stsquared99 Sam, I've been seeing this failure happening sporadically lately even though no .gitrepo files have changed? I think this error is being thrown by the lpush logic, can you take a look?

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@codyhoag fyi.

**Comment by stsquared99** [comment]
@pyoo47 The logic hasn't been changed for months.
What's this sha? 2a9185402f506f73381dd661deaf65474d12d2a4
I don't see it anywhere in this pull request, but it's supposed to be the sender sha

**Pull request closed without merging**
