### PR TITLE
master-qa-21393

### PR DESCRIPTION
**Pull request by vicnate5**
https://issues.liferay.com/browse/LRQA-21393

@marcellustavares @ctampoya

### CODE REVIEW

**Comment by sharonchoi** [comment]
looking

**Comment by sharonchoi** [comment]
@brianchandotcom please do not merge, as test has recently started failing due to an NPE. @vicnate5 FYI

**Comment by marcellustavares** [comment]
@vicnate5, I've pushed the fix at https://github.com/brianchandotcom/liferay-portal/pull/37684

Could you resend? Thanks for adding this!

**Comment by vicnate5** [comment]
@marcellustavares Thanks for the fix. I will resend once your pull goes in.

**Pull request closed without merging**
