### PR TITLE
LPS-73481 Set 7.1 in master

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:reopen

**Comment by achaparro** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop (this is good, I'm merging it)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/805fb9e1cc...ac3120091f

**Comment by brianchandotcom** [comment]
@achaparro can you send me a backport of 

dc7de51e7738b5c0e130757a1518d4391e2d9621
f2780b9d63420025d3491c6271d04bebb4887437

to 7.0.x and 7.0.x-private?

Thx.

**Comment by brianchandotcom** [comment]
@achaparro I already backported the parts that I know are the same (see upstream 7.0.x and my email)

**Pull request closed without merging**
