### PR TITLE
LPS-68886 Back port

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
cc @ZoltanTakacs @marcellustavares

**Comment by leoadb** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by ZoltanTakacs** [comment]
@leoadb @marcellustavares,

This backport won't be included in any fix-pack as we are working on portal-ee repository.
**Please send the backports to liferay-portal-ee:ee-7.0.x branch.**

- Moreover, is there any reason for the commits to be squashed?

We shouldn't squash commits for the backports, unless every commit would conflict when cherry-picking them. 

We should strive to be consistent with master as much as we can.

Please send **any** backports through the first reviewer on ee-7.0.x, namely @dustinryerson

References: https://grow.liferay.com/group/guest/people/-/wiki/Grow/ER+Processes#section-ER+Processes-Backport+Pull+Request+Workflow

/cc @zsoltbalogh @dustinryerson

**Comment by brianchandotcom** [comment]
@leoadb @marcellustavares @zsoltbalogh @dustinryerson @ZoltanTakacs

I rolled back these 2 commits as requested by @zsoltbalogh

**Comment by brianchandotcom** [comment]
@leoadb please resend to @ZoltanTakacs 

Thx

**Pull request closed without merging**
