### PR TITLE
LPS-75798

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@petershin, check the last 2 commits.

**Comment by hhuijser** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by petershin** [comment]
@hhuijser - Sent pulls to update the subrepos:

https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/505
https://github.com/liferay/com-liferay-journal/pull/521
https://github.com/liferay/com-liferay-portal-workflow/pull/242
https://github.com/liferay/com-liferay-osb-faro-private/pull/167
https://github.com/amosfong/com-liferay-osb-customer-private/pull/35
https://github.com/brianchandotcom/com-liferay-osb-lcs-private/pull/90

**Comment by hhuijser** [comment]
@petershin will you monitor those pulls and revert https://github.com/brianchandotcom/liferay-portal/pull/53012/commits/2644f8334a6696e74e41fb40192a04af4d74530b when those are merged?

**Comment by petershin** [comment]
@hhuijser - Yup, will revert the commit when the pulls are all merged

**Pull request closed without merging**
