### PR TITLE
LPS-190145 Create the structure to visualize the Model Builder screen

### PR DESCRIPTION
**Pull request by igor-franca**
Previous [PR](https://github.com/brianchandotcom/liferay-portal/pull/138033) with rebase error

### CODE REVIEW

**Comment by igor-franca** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@igor-franca there's no backend persistence for ObjectFolder?

**Comment by igor-franca** [comment]
It is being sent [here](https://github.com/liferay-objects/liferay-portal/pull/2349/commits)

**Comment by igor-franca** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@igor-franca resend it after at least the backend stubs are ready. Thx.

**Pull request closed without merging**
