### PR TITLE
LPS-58575 Language filter 

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by marcellustavares** [comment]
Woww! awesome @csierra thanks a lot! :)

**Comment by marcellustavares** [comment]
cc @inacionery @brandizzi

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a5efb15d04...a138cf71af

**Comment by brianchandotcom** [comment]
@csierra nice job on this. Please see my changes in upstream, especially 51dc42049735b23cbe6fde61caa164cce4f6b1b4 since I think without it, we introduce a lot of runtime errors.

**Comment by brianchandotcom** [comment]
@csierra also, why do we need the complicated tracker? see PortletTCKAutoLoginFilter.java

Can't we just do something like:

```
	property = {
		"servlet-context-name=", "servlet-filter-name=TCK Auto Login Filter",
		"url-pattern=/*"
	},
	service = Filter.class
```

**Comment by brianchandotcom** [comment]
@csierra NtlmFilter has dispatchers too

```
	property = {
		"dispatcher=FORWARD", "dispatcher=REQUEST", "servlet-context-name=",
		"servlet-filter-name=SSO Ntlm Filter", "url-pattern=/c/portal/login"
	},
```

**Comment by csierra** [comment]
@brianchandotcom 

with the current ways we need to get the ResourceBundles from the from the correponding OSGi bundles, this is why we instantiate a Filter for each ServletContextHelper... 

Is that what you meant?

**Comment by brianchandotcom** [comment]
Got it.. makes more sense now. It's because it's a complex filter that doesn't just use its own class loader. Thx @csierra

**Pull request closed without merging**
