### PR TITLE
LPS-89170 We don't need this as after LPS-90967 dropping stale indexes is automatically called during the upgrade

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LPS-89170

@brianchandotcom Please prioritize reviewing this when you can as this is urgent. Dave Truong and others are depending on this.

cc @danielkocsis @ealonso @david-truong

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@danielkocsis this is not right:

```

insert into LayoutSetVersion

select
	layoutSetId as layoutSetVersionId,
	1 as version,
	layoutSetId,
	groupId,
	companyId,
	createDate,
	modifiedDate,
	privateLayout,
	logoId,
	themeId,
	colorSchemeId,
	css,
	pageCount,
	settings_,
	layoutSetPrototypeUuid,
	layoutSetPrototypeLinkEnabled
from LayoutSet;

insert into Counter (name, currentId)

select
	'com.liferay.portal.kernel.model.LayoutSet' as name,
	max(layoutSetId) as currentId
from LayoutSet;

insert into Counter (name, currentId)

select
	'com.liferay.portal.kernel.model.LayoutSetVersion' as name,
	max(layoutSetVersionId) as currentId
from LayoutSetVersion;

```

Please resend following our normal upgrade processes.

@brianchiu this should be breaking all of our upgrade tests... 

@jhendley please talk to @brianchiu about this.

**Comment by brianchiu** [comment]
@brianchandotcom I'll take a look again

**Comment by brianchiu** [comment]
@brianchandotcom 
Our upgrades tests passed, and I'm not completely sure how to extend them to catch this issue. I'll come find you some time and ask you more about this.

**Comment by brianchiu** [comment]
Sent again here:
https://github.com/brianchandotcom/liferay-portal/pull/68744

**Pull request closed without merging**
