### PR TITLE
LPS-73786 com.liferay.portal.upgrade.v7_0_0.UpgradeSocial upgrade process is not setting the Counter value high enough

### PR DESCRIPTION
**Pull request by NorbertKocsis**
https://issues.liferay.com/browse/LPS-73786

### CODE REVIEW

**Comment by jpince** [comment]
@NorbertKocsis both PostgreSQL upgrade batches fail with this error:
`     [java] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.upgrade.UpgradeException: org.postgresql.util.PSQLException: Can't use query methods that take a query string on a PreparedStatement.`
https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/94194/consoleFull
closing this pull

**Comment by jpince** [comment]
ci:close

**Comment by lipusz** [comment]
I'll look into this as Norbi is on PTO next week.

**Comment by lipusz** [comment]
https://github.com/lipusz/liferay-portal/pull/191

**Pull request closed without merging**
