### PR TITLE
LPS-48334

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-48334.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:retest

**Comment by sharonchoi** [comment]
@brianchiu upgrade test failures due to https://issues.liferay.com/browse/LPS-64526
@kenjiheigel portal smoke failings due to https://issues.liferay.com/browse/LPS-64500

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f9dba816b6...65cceb3ff1

**Comment by brianchandotcom** [comment]
@blzaugg @jonmak08 you guys added the deprecation message to the autogenerated XML file. Instead, it should go in the Java file itself. See 0a66d17578a57c76dee5981f62b4c0220b9e2cf0

**Comment by jonmak08** [comment]
Thanks @brianchandotcom!

**Pull request closed without merging**
