### PR TITLE
LPS-64238  Duplicate dao orm CustomSQL to be used in module by modules

### PR DESCRIPTION
**Pull request by peterfellwock**

### CODE REVIEW

**Comment by peterfellwock** [comment]
@brianchandotcom https://github.com/peterfellwock/liferay-portal/pull/138 already running against my repo

**Comment by sharonchoi** [comment]
@evannagayama I think there might be a bug on this branch, bc the screenshots are showing Web Content in Site Admin as portlet unavailable. Can you take a look when you get a chance? Thanks!

**Comment by peterfellwock** [comment]
@sharonchoi and @evannagayama dont worry about this, I modified internal code that would affect why this screen is not showing up. The fix is here: https://github.com/brianchandotcom/liferay-portal/pull/37623/commits/3e8fd1fba016f3cb7d08fb639a78c8c654d7d779

**Comment by sharonchoi** [comment]
@peterfellwock awesome, thanks for the update!

**Comment by evannagayama** [comment]
Thank you both!

**Pull request closed without merging**
