### PR TITLE
Lps 180148

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2f55768834...d2dd7c5a39

**Comment by brianchandotcom** [comment]
@shuyangzhou just d2dd7c5a39b6c58c8557e9aa7917d7da7b712e0d thx

@ling-alan-huang can you SF enforce?

**Comment by rafaprax** [comment]
Ok, @shuyangzhou. I'll do that.

**Pull request closed without merging**
