### PR TITLE
LRQA-52887, LRQA-52785 | master

### PR DESCRIPTION
**Pull request by liulukiwi**
https://issues.liferay.com/browse/LRQA-52887
https://issues.liferay.com/browse/LRQA-52785

7.2.x: brianchandotcom/liferay-portal-ee#27142

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
Pushed to BChan.
brianchandotcom#79745

@Tim-Cao , there's change, see the pull

**Comment by liulukiwi** [comment]
close not on purpose, reopen it

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1e913b2989...e91f782b8a

**Pull request closed without merging**
