### PR TITLE
LPS-84683/LPS-85156 Removing an attachment on a Wiki Page/Message makes the changes of body disappear

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/01098a395c...d246519175

**Comment by brianchandotcom** [comment]
@ambrinchaudhary Please send a backport to support for 7.1.x  (like our normal support workflow). I'm no longer auto backporting pulls like this.

@jhendley @liferay @zsoltbalogh FYI.

Merged into master only.

**Comment by ambrinchaudhary** [comment]
@brianchandotcom thanks. Please @robertoDiaz or @IstvanD, could you please send the backport for 7.1? Thank you!

**Pull request closed without merging**
