### PR TITLE
master-qa-18257

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LRQA-18257

### CODE REVIEW

**Comment by brianchiu** [comment]
failure was due to out of memory error

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f669f535b9...89265cf493

**Comment by brianchandotcom** [comment]
@brianchiu don't retest these when it's just a memory error, it's happening 100% of the itme and it'll just use up resources.

**Comment by brianchiu** [comment]
@brianchandotcom 
Got it.

**Pull request closed without merging**
