### PR TITLE
LPS-97123 Fixing tests

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/74825#issuecomment-504469456.

**Comment by brianchandotcom** [comment]
This is good.. aiming to merge this weekend.

**Comment by brianchandotcom** [comment]
@4lejandrito can you make 2 changes:

make the package com.liferay.asset.auto.tagger.text.extractor (I'd like to namespace it)

Same for all the implementations, 

document-library/document-library-web/src/main/java/com/liferay/document/library/web/internal/asset/auto/tagger/extractor/DLFileEntryTextExtractor.java

should be

document-library/document-library-web/src/main/java/com/liferay/document/library/web/internal/asset/auto/tagger/text/extractor/DLFileEntryTextExtractor.java

For 

document-library/document-library-test/src/testIntegration/java/com/liferay/document/library/asset/auto/tagger/extractor/test/DLFileEntryTextExtractorTest.java

Can you make it

document-library/document-library-test/src/testIntegration/java/com/liferay/document/library/asset/auto/tagger/internal/text/extractor/test/DLFileEntryTextExtractorTest.java

I added the "internal" package so the Test matches the exact same package as the thing it tests (if it can't work, then go ahead and remove the internal)

Please resend. Thx!

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/74856.

**Pull request closed without merging**
