### PR TITLE
LPS-155969 Tables with ListType foreign key should use listTypeId as its column name

### PR DESCRIPTION
**Pull request by patriciajeanperez**
Manual forward from https://github.com/liferay-usm/liferay-portal/pull/698

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/87eb4dedad...f38b3df02a

**Comment by brianchandotcom** [comment]
@gislayne-vitorino can you send a follow up PR and change:

AddressImpl#getType()
AddressLocalServiceImpl#getTypeAddresses

Good job on making this inconsistent part of the code more consistent. Good job improving things.

See 6e5e0c8142cb0d3bb288ee02dac136796e9f1327 and c3a6b5d65d3c99e7daf4280d48a96c9f4f748061

**Comment by gislayne-vitorino** [comment]
Sure, I will do it. Thanks Brian.

**Pull request closed without merging**
