### PR TITLE
LPS-70240

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Can you rsend this @ehan @ChrisKian 

getLdapServerId

vs.

LDAPImportContext

Let's stick with LDAP vs. Ldap.

Thx.

**Comment by mhan810** [comment]
Hey @brianchandotcom, we do have some inconsistencies between use of LDAP
vs Ldap.  However, the way ldapServerId is used within this new class is
consistent with how ldapServerId is named elsewhere.  For instance
User.getLdapServerId.  If we go ahead and rename to
LDAPImportContext.getLDAPServerId, we would get more inconsistencies.
Either that or rename everywhere, but that would break bin compatibilities
too.



Sent from my mobile device.

On Feb 21, 2017 12:34 AM, "Brian Chan" <notifications@github.com> wrote:

Can you rsend this @ehan <https://github.com/ehan> @ChrisKian
<https://github.com/ChrisKian>

getLdapServerId

vs.

LDAPImportContext

Let's stick with LDAP vs. Ldap.

Thx.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/brianchandotcom/liferay-portal/pull/47030#issuecomment-281206097>,
or mute the thread

**Comment by mhan810** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1d3c201e7d...33def4dcab

**Comment by brianchandotcom** [comment]
@mhan810 @ChrisKian @ehan please see my changes in upstream. I changed the code a bit.

**Comment by brianchandotcom** [comment]
@mhan810 backported it for you

**Pull request closed without merging**
