### PR TITLE
LPS-85609 Gradle 4.10.2

### PR DESCRIPTION
**Pull request by petershin**
Hi Brian, the `gradle-plugins` tests were taking over 2 hours to run.  I'm working with QA to batch the tests into several groups.

I'll send seperate pulls later on to fix the deprecation warnings so we can upgrade to `Gradle 5.0` which provides [`Java 11 support`](https://docs.gradle.org/5.0-rc-1/release-notes.html).

### CODE REVIEW

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
ci:test:gradle-plugins

**Comment by brianchandotcom** [comment]
@petershin is this safe to merge? It looks pretty green. I suppose I should merge all except for the last commit "LPS-85609 Regen binaries file (CI TESTING ONLY)" ?

Leaving it open until you respond. Thx.

**Comment by petershin** [comment]
@brianchandotcom - Yup everything except the last commit. That file has already been pushed to the [liferay-binaries-cache-2017](https://github.com/liferay/liferay-binaries-cache-2017/commits/master) repo.

I've been testing this for awhile and can't think of anything else to check.  I'll run some more spot checks this weekend and follow up with Sam to update the subrepos on Monday.

**Comment by brianchandotcom** [comment]
Merged. Thank you.

View just my changes: https://github.com/brianchandotcom/liferay-portal/compare/petershin:a1d4bb0ba5...716b99334b
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/104ba04a0c...716b99334b

**Comment by brianchandotcom** [comment]
Thx @petershin ! I backported this as well to 7.1.x and 7.0.x. Thank you! Glad we're making progress on this.

**Pull request closed without merging**
