### PR TITLE
Lps 58672

### PR DESCRIPTION
**Pull request by shuyangzhou**
@tomwang2011 backport please.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 what happened to modules-unit here?

**Comment by shuyangzhou** [comment]
SF test timeout, not related to this pull.

**Comment by pyoo47** [comment]
Shuyang beat me to it.. Froze during testSourceFormatter and timed out. Here's the error from the console log.

```
     [exec] com.liferay.source.formatter.SourceFormatterTest > testSourceFormatter STARTED
     [exec] 
     [exec] com.liferay.source.formatter.SourceFormatterTest > testSourceFormatter STANDARD_OUT
     [exec]     Loading jar:file:/opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.impl/2.6.0/51dd0d720f3bb4aa9be024b48d73b69152bc93a9/com.liferay.portal.impl-2.6.0.jar!/system.properties
     [exec]     Loading jar:file:/opt/dev/projects/github/liferay-portal/bundles/tomcat-8.0.32/webapps/ROOT/WEB-INF/lib/portal-impl.jar!/system.properties
     [exec]     Loading file:/opt/dev/projects/github/liferay-portal/bundles/tomcat-8.0.32/webapps/ROOT/WEB-INF/classes/system-ext.properties
Build timed out (after 120 minutes). Marking the build as aborted.
Build was aborted
Recording test results
```

**Comment by shuyangzhou** [comment]
We will improve the exist CI timeout test rule soon, to prevent hanging. Then hanging JVM will be killed promptly with thread dump.

**Comment by brianchandotcom** [comment]
@tomwang2011  I already backported this one since it required a change to Gradle plugins.

**Pull request closed without merging**
