### PR TITLE
OAUTH2-236 SF

### PR DESCRIPTION
**Pull request by csierra**
/cc @stian-sigvartsen

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/97037202c9...114fb37b2c

**Comment by brianchandotcom** [comment]
@csierra please backport.

**Pull request closed without merging**
