### PR TITLE
LPS-75012 Refine spring extender debug output formatting

### PR DESCRIPTION
**Pull request by shuyangzhou**
@mhan810 @david-truong @jhinkey the output is like this now:
```
14:15:43,937 WARN  [Spring Extender Unavailable Component Scanner][UnavailableComponentScanner:174] Found unavailable component in bundle {id: 542, name: com.liferay.screens.service, version: 1.0.28}.
	Component with id 28 is unavailable due to missing required dependencies:
		ServiceDependency[interface com.liferay.blogs.service.BlogsEntryService null]
```

The component id can be further used in gogo:
```
g! dm ci 28
[542] com.liferay.screens.service
 [28] com.liferay.portal.spring.extender.internal.context.ModuleApplicationContextRegistrator unregistered
    com.liferay.asset.kernel.service.AssetEntryLocalService service required available
    com.liferay.asset.kernel.service.AssetEntryService service required available
    com.liferay.asset.kernel.service.persistence.AssetEntryPersistence service required available
    com.liferay.asset.publisher.web.util.AssetPublisherUtil service required available
    com.liferay.blogs.service.BlogsEntryService service required unavailable
    com.liferay.counter.kernel.service.CounterLocalService service required available
    com.liferay.document.library.kernel.service.DLAppLocalService service required available
........
```

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
@michaelhashimoto @pyoo47 what's going on here? I did not touch:
```
error: Illegal change to a .gitrepo file.
```

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
Looks like it passed this time
```
validate-pull-request-branch:
     [exec] /opt/dev/projects/github/liferay-subrepo-tools/bin/git-lpush -b master -o 8968950f17d8e07285ddf0e43c3e3b14f95bd148 -s a34e0407d44f4fa1acb9da428866ae758632f054 -r liferay-portal -v
     [exec] master: Verifying.
     [exec] master: Passed.
     [exec] 
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20170928223316831
```

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a5cc95fc53...c20666b5dd

**Pull request closed without merging**
