### PR TITLE
LPS-92053 Regenerate

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/aea1a7b4d2...f890223298

**Comment by brianchandotcom** [comment]
Thx @inacionery !

@nhpatt fyi

**Comment by brianchandotcom** [comment]
@nhpatt I backported this.

**Comment by nhpatt** [comment]
Thanks! :D

**Pull request closed without merging**
