### PR TITLE
LPS-57317 Only set serviceContext dates if they are not set already

### PR DESCRIPTION
**Pull request by izaera**
@brianchandotcom The test failure is a false positive. It is due to the WebDriverHelper commit that was pushed to fix a compilation error.

### CODE REVIEW

**Comment by izaera** [comment]
ci:retest

**Comment by izaera** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/984fc6f6b0...b927fc148e

**Pull request closed without merging**
