### PR TITLE
LRQA-57930 | master

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-57930

Bypassing `ci:forward` since these tests are failing consistently after https://github.com/brianchandotcom/liferay-portal/pull/87666

Backport PR:
7.2.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/30033

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:reopen

**Comment by xbrianlee** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bf239df6f8...474a2bdaca

**Pull request closed without merging**
