### PR TITLE
LRQA-25526

### PR DESCRIPTION
**Pull request by jpince**
https://issues.liferay.com/browse/LRQA-25526

### CODE REVIEW

**Comment by jpince** [comment]
@brianchandotcom please merge this ASAP, this should fix the 606Upgrade functional failure occuring on every pull per my comment on https://github.com/brianchandotcom/liferay-portal/pull/40205

**Comment by brianchiu** [comment]
@jpince @brianchandotcom 
I'm just going to remove the test (and i'll push it to upstream). We shouldn't even have the test if its not supported

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4ba6b67052...b9ded2f4be

**Comment by brianchiu** [comment]
oh nvm you got it

**Pull request closed without merging**
