### PR TITLE
LPS-78099 Moves to context class

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by timpak** [comment]
@michaelhashimoto @yichenroy @kenjiheigel FYI

[Console log](https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/195157//consoleText)

     [exec]      [echo] createdb: could not connect to database template1: FATAL:  role "root" does not exist
     [exec]      [exec] dropdb: could not connect to database template1: FATAL:  role "root" does not exist

**Comment by yichenroy** [comment]
@timpak 
It looks like there could be an issue with the slave that ran into the postgreSQL failure, regarding this issue please follow this ticket:
https://issues.liferay.com/browse/LRQA-38706

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/63e462c251...24e2155a40

**Pull request closed without merging**
