### PR TITLE
LRCI-93 Create kubernetes client tools from the kubernetes java API

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRCI-93

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:relevant
There was an upstream failure (now resolved) that causes the pullrequest test to run indefinitely.

**Comment by brianchandotcom** [comment]
@pyoo47 please review my changes in upstream. I made quite a few tiny ones.

**Comment by brianchandotcom** [comment]
@pyoo47 published.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/34e5909935...92a612bf33

**Pull request closed without merging**
