### PR TITLE
LPS-158069 Edit fieldSettings.d.ts

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**
Hi @brianchandotcom,

The failures [throwed here](https://github.com/liferay-objects/liferay-portal/pull/924#issuecomment-1227815426) are not related.

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@MarinhoFeliphe 

I see

```
		| ObjectFieldPicklistSetting
		| ObjectFieldFilterSetting[]
```

and

```
			| ObjectFieldFilterSetting[]
			| ObjectFieldPicklistSetting;
```

Please standardize and resend. Not sure what the order is. Thx.

**Comment by naraandrade** [comment]
ci:reopen

**Comment by naraandrade** [comment]
Hi Brian, we're having some problems with `.d.ts` files and SF, that's why those changes are not standardized. We already contacted the SF team and currently we're trying to get some help from Frontend Infra team, you can see this [thread](https://liferay.slack.com/archives/CNBG06JS3/p1661887030709989) on slack. In the meantime, could you accept this pull request?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b764a7b0fc...782d49a793

**Comment by brianchandotcom** [comment]
@MarinhoFeliphe @naraandrade see 7cdcfbc6e9effd593183367cc48da95c987d3676

I remember pinging about this a few weeks back for another PR where I stopped. We need to fix this soon. Or else it'll slow down PRs in the future.

**Pull request closed without merging**
