### PR TITLE
LRQA-52652 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-52652

### CODE REVIEW

**Comment by kyle-miho** [comment]
@brookedalton we should also look to avoid using the UI to import fragments from a dependency, using our API w/ our fragment files are much more reliable and quick (the method we use for configurable fragments tests). We already have tests for the FragmentsImporter so testing it would not be necessary

**Comment by kyle-miho** [comment]
@brookedalton Merge conflicts, I can't cherry pick this to 7.2.x, we'll probably have to start making changes to 7.2.x manually, but this is a test improvement and not a fix so it shouldn't be a big issue

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/db085dce90...e2f53f8b55

**Comment by brianchandotcom** [comment]
Thx @kyle-miho @brookedalton it may be a good idea to backport this to 7.2.x just for practice for @brookedalton thx!

**Pull request closed without merging**
