### PR TITLE
LPS-74375 Renames global file as portal.bundle.js tobe more clear about its purpose

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@izaera this code looks very weird:

```
		CompilerOptions compilerOptions = new CompilerOptions();

		compilerOptions.setLanguageIn(LanguageMode.ECMASCRIPT_NEXT);

		CompilationLevel.SIMPLE_OPTIMIZATIONS.setOptionsForCompilationLevel(
			compilerOptions);
		compilerOptions.setEmitUseStrict(false);
```

Why are we setting the compilerOptions.setEmitUseStrict AFTER we pass it into CompilationLevel.SIMPLE_OPTIMIZATIONS? There's no line break so I'm not sure if order matters.

@jbalsas 

can we sort:

```
	/liferay/portal.js,\
	/liferay/portlet.js,\
	/liferay/portal.bundle.js,\
	/liferay/workflow.js,\
```

Please resend. Thx.

**Comment by izaera** [comment]
@brianchandotcom I was going to say that order doesn't matter, but it's true that it does :-). So I guess we should add a line break 👍. Good catch.

**Comment by jbalsas** [comment]
resent: https://github.com/brianchandotcom/liferay-portal/pull/55663

**Pull request closed without merging**
