### PR TITLE
LPS-56339 remove my pages link from the product menu

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
@evannagayame this removes the entry "My Pages" in the "User Section" of the Product Menu. This could potentially break some tests.

thanks!

welcome_-_test_test_-_liferay

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@juliocamarero breaks PortalImplControlPanelFullURLTest.testMyAccountPortlet

Please resend.

**Comment by juliocamarero** [comment]
resent: https://github.com/brianchandotcom/liferay-portal/pull/31235

**Pull request closed without merging**
