### PR TITLE
LPS-58256 Also update gradle's ArrayUtil

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@Ithildir these connection errors are happening a lot

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8f5723cd50...f9c8e3a23c

**Comment by Ithildir** [comment]
Hi @brianchandotcom!

They happened because, for some reason, Gradle downloaded an old snapshot of `gradle-plugins`: by downloading it, it found a lot of dependencies (old versions of the other Gradle plugins) which are not in the cache, and so it tried to download them, randomly failing if the CDN wasn't able to answer all those requests.

Now that we're versioning `gradle-plugins`, there shouldn't be any problem. We just have to remember that, when we update the Gradle cache with the new version, both the JAR and the POM have to be published!

**Pull request closed without merging**
