### PR TITLE
Adolfopa pr 351

### PR DESCRIPTION
**Pull request by SamZiemer**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 what happened here?

@SamZiemer please resend. Thx.

**Comment by pyoo47** [comment]
@brianchandotcom I think there may be an problem with the code that deletes the local-git cached branch and retries the local-git sync when errors occur during local git sync. @michaelhashimoto is going to investigate.

**Comment by pyoo47** [comment]
@SamZiemer This failure is not related to your pull request. It is unlikely to happen again when you resend.

**Comment by SamZiemer** [comment]
reset https://github.com/brianchandotcom/liferay-portal/pull/43824

**Pull request closed without merging**
