### PR TITLE
LPS-94618 Remove unused code. This logic should be separated into renderer and menu item

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by jkappler** [comment]
cc:// @kyle-miho, @brianchiu

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@jkappler 

```
	public String getLabel(Locale locale) {
		return "Fragment Entry";
	}
```

Should we call LanguageUtil?

merged.

**Comment by brianchiu** [comment]
Follow up pull found here: https://github.com/brianchandotcom/liferay-portal/pull/72189

**Pull request closed without merging**
