### PR TITLE
OAUTH2-174 SF simplify

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@jeyvison see errors in this pull, it's happeing on all pulls. I think this is related to your recent changes?

**Comment by brianchandotcom** [comment]
@csierra nice job :)

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by jeyvison** [comment]
@brianchandotcom I'll take a look on it today.

**Pull request closed without merging**
