### PR TITLE
LPS-78772

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:test

**Comment by timpak** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by petershin** [comment]
@hhuijser - It looks like there is an extra whitespace before `http:\\`

https://github.com/brianchandotcom/liferay-portal/pull/56309/commits/c718318b281815115f6372dc1fbae115968a60cf#diff-d4c8818fe34d57edd6b8627aef58102cR8

**Comment by brianchandotcom** [comment]
@petershin can you send me a follow up pull? Thx.

**Comment by petershin** [comment]
Sent a fix: https://github.com/brianchandotcom/liferay-portal/pull/56349

**Pull request closed without merging**
