### PR TITLE
LPS-100124 Removes Slider from frontend-js-web exports

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
Hey @john-co, this is the resend from yesterday... based on what I'm seeing in other PRs, failure numbers seem within the acceptable range. Could you please verify?

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark:

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/54c37151f7...298c6b2fe5

**Pull request closed without merging**
