### PR TITLE
LPS-77683

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@shuyangzhou, @rotty3000 fyi this is similar to the bundle blacklisting

**Comment by mhan810** [comment]
ci:test

**Comment by mhan810** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@matethurzo a lot of these errors seem related to you?

**Comment by mhan810** [comment]
@brianchandotcom bizarre, the module I added doesn't come anywhere close to staging and import/export.  Were these breaking prior to this pull?

**Comment by brianchandotcom** [comment]
@mhan810 sent it to @shuyangzhou at https://github.com/shuyangzhou/liferay-portal/pull/5669

I asked @shuyangzhou to make it like portal-bundle-blacklist

I notice he had split it up into 3 separate modules.

**Pull request closed without merging**
