### PR TITLE
LPS-85507 Create ScreenNavigationEntry for General > Organization Site

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-85507](https://issues.liferay.com/browse/LPS-85507).<br><br>/cc @pei-jung @stsquared99 @alee8888 @alecsloan

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fb5dc7b10b...bb358345c8

**Comment by brianchandotcom** [comment]
See bb35834 thx.

**Comment by jpince** [comment]
@drewbrokke @alecsloan this broke 4 functional acceptance tests. The tests are still looking for the old dropdown instead of the new side menu. Please let me know if you plan to fix them today, else I'll just remove them from acceptance until you fix all of the tests in [LPS-85070](https://issues.liferay.com/browse/LPS-85070)
```
LocalFile.CPUsersandorganizations#EditOrganizationSite
LocalFile.CPUsersandorganizations#AddOrganizationTeam
LocalFile.StagingUsecaseWithOrganization#StagingOrganizations
LocalFile.CPSitememberships#OrganizationsView
```

cc/ @kmaria @reizero00

**Comment by drewbrokke** [comment]
@jpince go ahead and remove them from acceptance. Our plan is to fix them all at once in LPS-85070.

**Pull request closed without merging**
