### PR TITLE
LPS-62558 SF

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@marcellustavares poshi errors, please resend.

**Comment by csierra** [comment]
ci:retest

**Comment by marcellustavares** [comment]
I'll resend @csierra, I guess it was a random failure.

**Comment by csierra** [comment]
yes... because the one I sent you passed all tests

thx!

**Comment by marcellustavares** [comment]
resent to https://github.com/brianchandotcom/liferay-portal/pull/36109

**Pull request closed without merging**
