### PR TITLE
LPS-75124 Move UnsyncTeeWriter to SampleSQLBuilder.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/32f1197c79...3caef0ebed

**Comment by brianchandotcom** [comment]
@shuyangzhou @Preston-Crary can you move UnsyncTeeWriter and CharPipe into 

com.liferay.portal.tools.sample.sql.builder.internal.io or com.liferay.portal.tools.sample.sql.builder.io or something like that?

Thx.

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/52080

**Pull request closed without merging**
