### PR TITLE
LPS-198941 SXPElement Translations bug

### PR DESCRIPTION
**Pull request by gustavolimav**

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:reopen

**Comment by gustavolimav** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/144223#issuecomment-1823501566

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1d5319088e...a1e7e85db3

**Comment by brianchandotcom** [comment]
@gustavolimav precisamos um teste pra

SXPBlueprintLocalServiceImpl.java and SXPElementLocalServiceImpl.java
```
		if (GetterUtil.getBoolean(
				serviceContext.getAttribute(
					SXPBlueprintLocalServiceImpl.class.getName() +
						"#_validate"),
				true)) {
```

Fix the upgrade, make sure title description has the same type as fallback

**Pull request closed without merging**
