### PR TITLE
LPD-35168 Binding two trees into one using a relationship

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPD-35168](https://liferay.atlassian.net/browse/LPD-35168)

### CODE REVIEW

**Comment by gabrielwas** [comment]
Approved from Core Team here: https://github.com/liferay-core-infra/liferay-portal/pull/7496

**Comment by gabrielwas** [comment]
@tinatian here's the change (commit) we've made: https://github.com/brianchandotcom/liferay-portal/pull/154882/commits/221b0b79d03867e1f638192a0032f8c19de0ccfb

Thanks for the support!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/82c90b91c7...588424a3d2

**Comment by brianchandotcom** [comment]
@pedro-oliveira446 See 588424a3

**Pull request closed without merging**
