### PR TITLE
LPS-72606

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @tomwang2011

We have about 60 violations.
You can enable the check by setting checkUnprocessedThrownExceptions is true: See https://github.com/brianchandotcom/liferay-portal/pull/49023/commits/4dba7c3e255b3f399277bda96702a6ef63f4832f#diff-4d711d96d6590b803e3ffaf6d0526c9eR200

After you have fixed the violations, go ahead and revert https://github.com/brianchandotcom/liferay-portal/pull/49023/commits/4dba7c3e255b3f399277bda96702a6ef63f4832f

Thanks!

**Comment by hhuijser** [comment]
ci:reopen

**Comment by tomwang2011** [comment]
CC @shuyangzhou

@hhuijser Hi Hugo, do you think it would be possible to make an adjustment such that: if the exception caught is used anywhere in the catch brackets then we let it pass, so SF will only mark the classes that has a catch statement that doesn't contain any usage of the exception caught.

For example: we should not pick up the unused exception  in `portal-impl/src/com/liferay/portal/util/PortalImpl.java 1223`, as we have `Throwable cause = e.getCause();` that uses the exception e and then we do `throw new SystemException(cause); `

**Comment by brianchandotcom** [comment]
@hhuijser I"ll merge this after you make the change that @tomwang2011 is asking for. Thx.

**Pull request closed without merging**
