### PR TITLE
LPS-112983 Deprecate liferay-browser-selectors

### PR DESCRIPTION
**Pull request by wincent**
Manual forward from [wincent#296](https://github.com/wincent/liferay-portal/pull/296) because I don't want to waste CI resources re-running green tests after a trivial edit to a Markdown file (ci:test:sf passed on the edit).

Previous green test runs:

- [ci:test:relevant](https://github.com/wincent/liferay-portal/pull/296#issuecomment-634028594)
- [ci:test:sf](https://github.com/wincent/liferay-portal/pull/296#issuecomment-634101220)

Original message follows:

---

Previously:

- https://github.com/wincent/liferay-portal/pull/294
- https://github.com/wincent/liferay-portal/pull/291
- https://github.com/wincent/liferay-portal/pull/249

---

This is a follow up on #294, and is what I did since then:

- Fixed the source formatting for the files we mentioned [here](https://github.com/wincent/liferay-portal/pull/294#discussion_r430252746) 
- Deprecated the `liferay-browser-selectors` AUI module

I also checked for usages for the remaining css classes: 

For `.safari`:

I didn't find any usages in CSS, and for JavaScript usages, we have: 

https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/util.js#L305

- This doesn't depend on the classes added to `document.documentElement` by `Liferay.BrowserSelectors.run`, it uses `A.UA.safari` which is defined [here](https://github.com/yui/yui3/blob/25264e3629b1c07fb779d203c4a25c0879ec862c/src/yui/js/yui-ua.js#L116), and get's modified [here](https://github.com/yui/yui3/blob/25264e3629b1c07fb779d203c4a25c0879ec862c/src/yui/js/yui-ua.js#L318), and "reset" [here](https://github.com/yui/yui3/blob/25264e3629b1c07fb779d203c4a25c0879ec862c/src/yui/js/yui-ua.js#L389)
	
- It's in `frontend-js-aui-web` and we'll end up migrating or deprecating this function as well

For `.secure` this is the only usage I found:

https://github.com/liferay/liferay-portal/blob/8abc9337c7f4acd55e8ef803632f26090cafe3be/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/session.js#L362

- It doesn't depend on the classes added to `document.documentElement` by `Liferay.BrowserSelectors.run`, it uses `A.UA.secure` which is defined [here](https://github.com/yui/yui3/blob/25264e3629b1c07fb779d203c4a25c0879ec862c/src/yui/js/yui-ua.js#L231) and get's set [here](https://github.com/yui/yui3/blob/25264e3629b1c07fb779d203c4a25c0879ec862c/src/yui/js/yui-ua.js#L286) (and it looks like an "easy" replacement)
- It's in `frontend-js-aui-web` and we'll end up migrating or deprecating this function as well

For `.touch` as @jbalsas mentioned, we have 3 usages in CSS and the JS usages have been updated to use `UA.touchEnabled`.

Thanks again for your help on this one

### CODE REVIEW

**Comment by wincent** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b1f0707e97...4fba534a87

**Comment by brianchandotcom** [comment]
@hhuijser can you type:

git grep "implements TemplateContextContributor"

From this pull:

**Comment by brianchandotcom** [comment]
@hhuijser can you type:

git grep "implements TemplateContextContributor"

From this pull:

modules/apps/frontend-theme/frontend-theme-browser-support/src/main/java/com/liferay/frontend/theme/browser/support/internal/theme/contributor/BrowserTemplateContextContributor.java

But we have many other examples.

Since they all imlement

com.liferay.portal.kernel.template.TemplateContextContributor

They should be in 

com.liferay.frontend.theme.browser.support.internal.template instead of

com.liferay.frontend.theme.browser.support.internal.theme.contributor

Can you fix all of them and SF enforce?

@wincent @jbalsas fyi

**Comment by jbalsas** [comment]
Thanks @brianchandotcom!

**Pull request closed without merging**
