### PR TITLE
master-qa-27309

### PR DESCRIPTION
**Pull request by vicnate5**
https://issues.liferay.com/browse/LRQA-27309

@marcellustavares The DDL display template poshi test is flaky so I am moving it to quarantine. It will still run, but not be failing the pull requests. Do you know if we have an integration test for adding new templates? This poshi test has been difficult to maintain.

### CODE REVIEW

**Comment by vicnate5** [comment]
Sent to 7.0.x https://github.com/brianchandotcom/liferay-portal/pull/42600

**Comment by marcellustavares** [comment]
Hey @vicnate5, could you please explain me briefly what the test is doing? 

Thanks

**Comment by vicnate5** [comment]
@marcellustavares 
1. Add a new data definition
2. Save
3. Add a new blank display template for this definition
4. Save
5. Assert save is successful

**Comment by marcellustavares** [comment]
Got it, thx @vicnate5

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d272bad6b8...4a28ef7ebd

**Pull request closed without merging**
