### PR TITLE
Lps 169164

### PR DESCRIPTION
**Pull request by shuyangzhou**
@izaera your change in LPS-169164 caused 15% startup time regression, that's basically undoing our optimization from past 5 months.

The fix I did here is only delaying the calculation from startup to first page hit which means end user will still be impacted significantly by this. I highly suggest you to reconsider the need of this MessageDigest change. There must be a lighter way to do this.

In the future if you have change that adds significant calculation to startup, please send it through @liferay-core-infra for regression checking, thanks!

### CODE REVIEW

**Comment by izaera** [comment]
@shuyangzhou Mmm, we (me and @dsanz) thought about different ways to do it, but we couldn't find any that was valid for clustered environments :-(.

For non-clustered envs we may simply use a random UUID (instead of a hash) as before, but for clustered we need the hash to be the same in all nodes to avoid double requests/redirects.

@dsanz suggested to use the DB or cluster cache plus a random UUID to synchronize nodes, but I'm not 100% sure how/if it would work.

Another option would be storing the hash in the OSGi state to avoid having to compute it in each startup. This could work because it's not usual to deploy new things to production so the hash should be stable. However, after each deployment, it would still impact the startup.

We can also use dates instead of hashes, but I'm not sure how it would work. Can we get the last time an OSGi bundle was deployed from OSGi? Maybe we can simply compute a hash of such date...

@brianchandotcom @shuyangzhou As this is not urgent , we may revert it and try to find a different way if your prefer :thinking: I mean, it's a huge improvement for users and especially for CDNs, but if we rollback the portal will still work as before and no one has ever complained about it. Only one customer complained, but they were able to fix it with a simple servlet filter, so I guess it's safe to rollback.

**Comment by izaera** [comment]
We could maybe use a hash of the OSGi bundle versions too... That could be a proxy for the JAR file contents and as long as JAR files with same OSGi version numbers always contain the same contents, we would be fine. 

My biggest concern is to get this wrong and corrupt a bunch of CDN caches of our customers :grimacing: 

One more option could be using a CRC instead of a cryptographic hash function. It should be faster, in theory...

**Comment by izaera** [comment]
Any help with deciding what would be our best alternative is more than welcome! :hugs:

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/53699a3e6c...ee28af8366

**Comment by brianchandotcom** [comment]
@shuyangzhou I talekd to @izaera and he proposed just reverting the whole thing to find a better way to do this. So I just reverted it.

**Comment by shuyangzhou** [comment]
@izaera you could consider to use the extender bundle's Bundle.getLastModified(). In theory it is not 100% safe. But in practice, considering it is not possible for us to release frequent enough to cause any conflict. It would be the cheapest way to get your an unique id. Of course this is assuming all nodes within the cluster are deploying the exact same jar file for that bundle, which is the basic requirement we have for cluster.

**Comment by izaera** [comment]
@shuyangzhou That sounds good :+1: . I still need to check something related to React fragments, since they create virtual modules on the fly and that could break the id :-(.

Regarding:

>  this is assuming all nodes within the cluster are deploying the exact same jar file for that bundle

Yes, we assume that too. If different nodes have different content and there's no session affinity, JS code will be mixed and worse things than having an incorrect resolution will happen.

Thx for the hint :+1:

**Pull request closed without merging**
