### PR TITLE
LPS-91728 Move tree item label to separated template

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:open

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:open

**Comment by p2kmgcl** [comment]
ci:reopen

**Comment by jbalsas** [comment]
Hey, @petershin, I think this is an example of the broken caching mechanism and one of the main issues we have right now.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c2df465d1f...58f5c3763c

**Comment by brianchandotcom** [comment]
@p2kmgcl is this how we normally chain?

```
	_expandedNodes: Config
		.arrayOf(Config.string())
		.internal()
		.value(['root'])
```

You should run our CSF (@jbalsas please help him out)

Thx

**Comment by p2kmgcl** [comment]
@brianchandotcom I opened an issue in csf (https://github.com/liferay/liferay-frontend-source-formatter/issues/47), as we do not have a concrete rule for this chaining.

**Pull request closed without merging**
