### PR TITLE
LRCI-3638 Create a basic React Application that can be used to monitor projects & builds

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://liferay.atlassian.net/browse/LRCI-3638

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:reopen

@brianchandotcom - I tried the changes you mentioned locally in this comment:
https://github.com/brianchandotcom/liferay-portal/pull/136665#issuecomment-1600105894

I believe I still need the `.env` file, but I removed one of the properties.

And in regards to the [package.json](https://github.com/liferay/liferay-portal/blob/master/workspaces/liferay-sample-workspace/client-extensions/liferay-sample-custom-element-2/package.json) file it does match the one in `liferay-sample-custom-element-2` I just removed the `sass` plugin in the jethr0 `package.json`.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8bf99420ce...1cc9e5f8c7

**Comment by bryceosterhaus** [comment]
Hey @michaelhashimoto, I noticed that some changes you made here are failing SF for me. I am curious of your workflow here, did you happen to run this through `ci:test:sf` somewhere? OR what was the command you ran locally for SF?

Asking primarily because I want to make sure that SF is working properly both in CI and locally... We recently added formatting to the workspaces folder and have been seeing some inconsistencies with it.

**Comment by bryceosterhaus** [comment]
@michaelhashimoto you can probably disregard my previous comment. I think I actually found a bug in our `ci:test:sf` run and that it doesn't run format in `./workspaces` unless there are other changed detected in `./modules`. So I think your PR is fine here, it's just a bug  with how we check formatting. I'll work on a fix for that

**Pull request closed without merging**
