### PR TITLE
LPS-76604

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Same fix as [here](https://github.com/liferay/com-liferay-journal/commit/fb74817993d6b9c8ac8783222a41bc1b1bc5fe26) applied to other cases

**Comment by hhuijser** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@daviddotzhang @hhuijser LPS description didn't seem to be this ticket, but I trust you for this anyways. Merged, but NOT backported. Please backport. Thx.

**Pull request closed without merging**
