### PR TITLE
master-vw-85

### PR DESCRIPTION
**Pull request by vicnate5**
https://issues.liferay.com/browse/LRQA-19775

Hey @brianchandotcom, this fixes the issue with the PR tester. Please prioritize if you can.

### CODE REVIEW

**Comment by vicnate5** [comment]
@brianchiu

**Comment by brianchandotcom** [comment]
@vicnate5 this still seems to have errors?

**Comment by vicnate5** [comment]
@brianchandotcom The failure is a different issue:
https://github.com/brianchandotcom/liferay-portal/pull/31795

**Comment by brianchiu** [comment]
@brianchandotcom 
Those errors are different from the original error.

The first error is due to:
https://github.com/brianchandotcom/liferay-portal/pull/31795#issuecomment-154216760

The second error we'll have to look into. But I can guarantee it has nothing to do with Victor's pull because the poshi code that Victor's pull changes isn't even run in that failing. It most likely is a fluke. In the poshi report, the screenshots are black, so something may have happened to that slave.

CC @michaelhashimoto

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/aa1b6ccd2c...66942aee65

**Pull request closed without merging**
