### PR TITLE
LPS-77223 Apply new NavigationBar pattern to server-admin-web

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke, @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test

**Comment by pei-jung** [comment]
ci:reopen

**Comment by pei-jung** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7e2bdd76d1...7390e6db9b

**Comment by brianchandotcom** [comment]
@pei-jung please see my changes in upstream. Thx.

**Pull request closed without merging**
