### PR TITLE
LRQA-52981 Test fix Forms close sidebar

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRQA-52981

### CODE REVIEW

**Comment by cvanut** [comment]
Reviewed together with @joshitagaki

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/54e74b2405...2460e93c3e

**Comment by brianchandotcom** [comment]
@joshitagaki should this go in 7.2.x? If so ,please backport!

**Comment by brianchandotcom** [comment]
@joshitagaki test fixes can be sent to me directly.

**Pull request closed without merging**
