### PR TITLE
LPS-53373 Add assign Default Portlet Data Handler when portlet does not declare one.

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
@epgarcia can you take a look at the PollsVoteStagedModelDataHandlerTest.testStagedModelDataHandler failure? It seems related.

**Comment by epgarcia** [comment]
Ok, I will review it. Thanks

**Pull request closed without merging**
