### PR TITLE
LPS-144124 LRQA-73763

### PR DESCRIPTION
**Pull request by vicnate5**
@ling-alan-huang @zhangyan0701

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2251b86f4e...bf196dcfb8

**Comment by brianchandotcom** [comment]
@vicnate5 was this on purpose?

modules/apps/calendar/calendar-web-test/src/testFunctional/tests/dependencies/Calendar-empty-file.portlet.lar.portlet.lar/Calendar-empty-file.portlet.lar.portlet

@ling-alan-huang please fix that file?

I merged this but it seems wrong.

**Comment by ling-alan-huang** [comment]
@vicnate5 I don't understand what's happening here, do SF need to add other rules?

**Comment by zhangyan0701** [comment]
Hi @brianchandotcom @vicnate5 

This dependency is for testing in Calendar to check the error message when attempting import an empty lar file. So the file Calendar-empty-file.portlet.lar.portlet doesn't contain any valid data which is the purpose of the test.

**Pull request closed without merging**
