### PR TITLE
LPS-164359 | master

### PR DESCRIPTION
**Pull request by patriciajeanperez**
https://issues.liferay.com/browse/LPS-164359

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:reopen

**Comment by patriciajeanperez** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8cab233d60...6697a4731c

**Pull request closed without merging**
