### PR TITLE
LPS-56199 Extract Expando as an OSGi module

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
@drewbrokke, Could you check if those errors are caused by our commits?

**Comment by drewbrokke** [comment]
Hey @ealonso, I found the source of the errors.  I'll fix and resend to @brianchandotcom with your changes.

**Comment by brianchandotcom** [comment]
Thx @drewbrokke

**Pull request closed without merging**
