### PR TITLE
LPS-108722 Fix tests

### PR DESCRIPTION
**Pull request by adolfopa**
@brianchandotcom See discussion at https://github.com/brianchandotcom/liferay-portal/pull/85396 regarding the SF errors.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
@jbalsas @wincent see my comment https://github.com/brianchandotcom/liferay-portal/pull/85396#issuecomment-591886271

**Comment by wincent** [comment]
Replied over there.

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/85420

**Pull request closed without merging**
