### PR TITLE
LPS-61811

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@brianchandotcom i think these are known poshi failures

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9c312cfaa1...2ef2fba701

**Comment by brianchandotcom** [comment]
@sharonchoi the wiki poshi test failure is still happening

@brianchiu see CPUserGroups failure. Happening randomly too.

**Comment by brianchiu** [comment]
I see it.

**Pull request closed without merging**
