### PR TITLE
[TS] LPS-76286 FIX: Full reindex: progress bar stuck at 0% until complete

### PR DESCRIPTION
**Pull request by arboliveira**
Author: @yuhai 
Reviewer: @arboliveira

@tinatian FYI; regression in https://github.com/liferay/liferay-portal/commit/fd6e275727b1bb58389eeee03404e173759e9630 - diagnosis: https://github.com/hhuijser/liferay-portal/pull/3113#issue-279661377

https://issues.liferay.com/browse/LPS-76286

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:test

**Comment by arboliveira** [comment]
ci:test

**Comment by arboliveira** [comment]
ci:reopen

**Comment by arboliveira** [comment]
`source-format-jdk8` failure seems unrelated.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9cbb3d217f...f782e57bd4

**Pull request closed without merging**
