### PR TITLE
LPS-86006 Update structure when we are adding a page using a page template

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
cc @kyle-miho, @brianchiu

**Comment by jpince** [comment]
ci:close until POSHI failures are validated

**Comment by jpince** [comment]
@anthony-chu I see the fiftyonedegrees failure in lpkg-controller, along with a lot of other unresolved requirement errors. Not sure if it's related to what we saw in [LRQA-44032](https://issues.liferay.com/browse/LRQA-44032), I see [these commits](https://github.com/brianchandotcom/liferay-portal/pull/64080) merged, [this one](https://github.com/brianchandotcom/liferay-portal/pull/64093) on its way (looks like Ray's sending the commits from [64052](https://github.com/brianchandotcom/liferay-portal/pull/64052) in pieces). So I don't know if this is a fluke, or something we should be concerned about in the R7 implementation.
```
    [junit] 09:46:59,803 ERROR [main][ModuleFrameworkImpl:1701] Unable to start bundle com.liferay.portal.mobile.device.detection.fiftyonedegrees.enterprise
    [junit] org.osgi.framework.BundleException: Could not resolve module: com.liferay.portal.mobile.device.detection.fiftyonedegrees.enterprise [52]
    [junit]   Unresolved requirement: Import-Package: com.liferay.portal.mobile.device.detection.fiftyonedegrees.data; version="[1.0.0,2.0.0)"
```
https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/248291//consoleText

**Comment by anthony-chu** [comment]
@jpince it seems like 51degrees isn't the only module that's not starting up. checking with ray now about the pull for the R7 implementation.

**Comment by brianchiu** [comment]
@ealonso @jpince 
Looking.

**Pull request closed without merging**
