### PR TITLE
LPS-168506 Final fix for "Lock wait timeout exceeded" when trying to create a related entry using ERC as reference

### PR DESCRIPTION
**Pull request by guilhermedcamacho**
Unrelated CI errors [here](https://github.com/liferay-objects/liferay-portal/pull/1369#issuecomment-1318028924).

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:reopen

**Comment by guilhermedcamacho** [comment]
ci:close

**Comment by guilhermedcamacho** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ff484b7f5d...20c3a51c69

**Comment by brianchandotcom** [comment]
@guilhermedcamacho see 20c3a51c69216f20e288ac519bfe826920d0377e

@shuyangzhou is 0cad27ed that ok pattern?

**Pull request closed without merging**
