### PR TITLE
Lps 72406

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
Pushed upstream for CI

**Comment by jpince** [comment]
thanks @shuyangzhou!

**Comment by jpince** [comment]
@shuyangzhou can you also push upstream to ee-7.0.x? BChan already backported it https://github.com/liferay/liferay-portal-ee/commit/a45f5248482c4af60419b84460de2968251bec5f

**Comment by shuyangzhou** [comment]
@jpince pushed at https://github.com/liferay/liferay-portal-ee/commit/bd815c52ad0472e9be2838a0118b6b36a426d5e6

**Comment by jpince** [comment]
@brianwulbern @ginsonren

**Pull request merged**
