### PR TITLE
LPS-81854 FIX CI Failures and Performance Regression, caused by Search Options Portlet and Empty Search

### PR DESCRIPTION
**Pull request by arboliveira**
This pull fixes several problems caused by the recent addition of LPS-81854 and LPS-80940:

- A 7.9% performance regression: fix tested and confirmed by @slnn - Thanks again! (https://github.com/slnn/liferay-portal/pull/303#issuecomment-395312878)
- CI failures: `SearchDisplayContextTest` `testSearchKeywordsBlank`, `testSearchKeywordsSpaces` "org.mockito.exceptions.verification.NoInteractionsWanted"
- CI failures: `WikiPageUADAnonymizerTest`, `WikiNodeUADExporterTest` "com.liferay.portal.kernel.exception.NoSuchGroupException: No Group exists with the primary key 0"

Added new unit tests covering the root cause, to prevent new regressions.  cc/ @jpince

CI passed, false negatives only. (https://github.com/arboliveira/liferay-portal/pull/518#issuecomment-395311531)

- 1 database hiccup: `ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 104`
- several startup failures with error: `com.liferay.portal.lpkg.deployer.LPKGVerifyException: LPKG validation failed with {[missing requirement com.liferay.aggregate.rating.apio.api; version=1.0.0; type=osgi.bundle [caused by: Unable to resolve com.liferay.aggregate.rating.apio.api version=1.0.0:`

https://issues.liferay.com/browse/LPS-81854
https://issues.liferay.com/browse/LPS-80940

### CODE REVIEW

**Comment by jpince** [comment]
@arboliveira you forgot to revert https://github.com/arboliveira/liferay-portal/commit/696d1717b5a92990908bf8e2a1975c22ffb6e7d1. So the unit tests ran and passed, but you never tested the UAD integration tests :) I don't think that prevents this pull from being merged, but please also send that revert to Brian.

**Comment by arboliveira** [comment]
Ouch! Sorry about that 😅 

@brianchandotcom Having tested locally, I have high confidence this fix solves the issue with UAD integration tests. I'm running CI now on another branch with https://github.com/arboliveira/liferay-portal/commit/696d1717b5a92990908bf8e2a1975c22ffb6e7d1 reverted, but if you want to go ahead and revert it yourself while merging this pull, I'd appreciate it. 😄  I'll monitor the UAD tests afterwards.

**Comment by jpince** [comment]
@arboliveira I looked in upstream and saw that there are other wiki*UAD tests failing there (at least one per modules-int batch) that were not ignored yesterday. So since your test pull passed with 0 failures, this one should be good :)

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
