### PR TITLE
Lps 68289 35

### PR DESCRIPTION
**Pull request by shuyangzhou**
@brianchandotcom this is a bandaid fix for the DB2 company delete tx failure. By increasing DB2's tx buffer size.

Like we talked before, the right fix should be rewriting company deleting logic to do sql level table data sweeping by company id and a following cache reset. @drewbrokke , have you guys started on this yet? Let me know if you run into any issues.

CC @mhan810

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Bandaids are not always bad.. I use them when I have cuts.. thx @shuyangzhou

**Comment by brianchandotcom** [comment]
@tinatian please remember to remove the bandaid when we have the final fix. Thx!

**Comment by tinatian** [comment]
@brianchandotcom OK, I will.

**Comment by drewbrokke** [comment]
@shuyangzhou we have not started work on company deletion yet.  I will discuss priority with @jorgeferrer.

**Pull request closed without merging**
