### PR TITLE
LRQA-56998 Quarantine Staging flaky tests

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-56998

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:reopen

**Comment by xbrianlee** [comment]
cc/ @arboliveira @JoyceWang08211

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f16fb1278d...f16fb1278d

**Comment by JoyceWang08211** [comment]
@david-gutierrez-mesa This is a wcm testcase.

**Pull request closed without merging**
