### PR TITLE
LPS-68586 Updates npm-shrinkwrap.json

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @kenjiheigel, as expected, `node-sass` is missing for the new release 😢 

Could you please cache and retest?

Thanks!

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@jbalsas I backported this.

**Comment by kenjiheigel** [comment]
@jbalsas, yeah 😞. Just talked to Sam about it.

**Pull request closed without merging**
