### PR TITLE
LPS-67830 Allow administrators to configure captcha using System Settings, allowing export and import of configurations

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LPS-67830

### CODE REVIEW

**Comment by xbrianlee** [comment]
This pull combines the commits for LPS-67830 and Poshi functional test fixes. The last 3 commits fixes an issue our workflow test caught in brianchandotcom#47602.

cc: @alee8888 @ksuetani @pei-jung

**Comment by xbrianlee** [comment]
ci:reopen

**Comment by brianwulbern** [comment]
@xbrianlee @pei-jung can one of you resend?  Looks like the pull may have been force-pushed while closed.

**Comment by pei-jung** [comment]
@brianwulbern, I've resent it here https://github.com/brianchandotcom/liferay-portal/pull/47759.

**Pull request closed without merging**
