### PR TITLE
LPS-102577 fix wrong casting

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fbfc833d1d...ebd450814b

**Comment by brianchandotcom** [comment]
@nhpatt test?

**Comment by brianchandotcom** [comment]
@nhpatt there was nothing for me to backport because I had never backported the change that broke it ....

It was hidden in a regen commit in 395fae67

**Comment by nhpatt** [comment]
@brianchandotcom that's how I noticed, tests where failing (but now in the PR), sorry for the mess, I guess that one PR went without it, passed and the other with it, failed :(

**Pull request closed without merging**
