### PR TITLE
LPS-59706

### PR DESCRIPTION
**Pull request by natecavanaugh**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/43a084c767...5bfb7904b2

**Comment by brianchandotcom** [comment]
@jhinkey there are a lot of language keys here that sound weird. Can you coordinate with @brunobasto ? See LRDOCS-2050

Thx.

**Comment by jhinkey** [comment]
Yep. Will do. It'll be good to square things up with Bruno. - Jim

**Comment by brunobasto** [comment]
Thanks, @brianchandotcom 

@jhinkey, can you find Jadson Dantas on slack? He is the one defining these strings in his UX prototypes and documentations. If you could provide him with some suggestions, that would be great. Then he could update his specs of the app and then we can fix it on the code.

**Comment by brunobasto** [comment]
@jhinkey But I would be glad to help as well :)

**Comment by jhinkey** [comment]
Sounds good, @brunobasto :-)

**Comment by jhinkey** [comment]
I'm copying Russ Bohl as he's our KM person on the Business Productivity CF team.

/cc @rbohl

**Pull request closed without merging**
