### PR TITLE
LPS-77986 Move add button in bookmarks

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @jbalsas

**Comment by sergiogonzalez** [comment]
Hey @austinchiang @patriciajeanperez I don't know if these tests can break our functional tests. Can you guys take care of it in case it does?
The pull just moves the add button to the management bar as described in https://portalmigration.wedeploy.io/lexicon/add_menu.html
Thanks guys!

**Comment by austinchiang** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3fb3e0d6f8...e973a17383

**Pull request closed without merging**
