### PR TITLE
LPS-75473: bold text fix

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:reopen

**Comment by matethurzo** [comment]
@brianchandotcom @jpince I've analyzed the logs, but the portal-frontend-js-jdk8 seems related to Kaleo not this pull's code

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2424d7549d...3b223739f4

**Comment by jpince** [comment]
@matethurzo yes, we contacted the workflow team about the portal-frontend-js-jdk8 last Friday, they're looking into it

**Pull request closed without merging**
