### PR TITLE
LPS-97716

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@petershin, just FYI, this one was a result of LPS-97614

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
@jbalsas, @wincent, are these SF warning valid? Can you fix those?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f5dac394b3...eee9dfc2fb

**Comment by wincent** [comment]
@hhuijser: the warnings and errors are legit.

- The (many) warnings are being fixed as part of this epic: https://issues.liferay.com/browse/LPS-97459 — work has already started there; because this work will take a while these warnings just print to the console, they don't affect the exit status.
- The 3 errors are real and should be fixed, I'll send a PR for that.

I thought @petershin had turned off frontend linting in CI because it checks all files instead of just the files changed in the PR, so I am not sure how those errors got in. (In any case, I am glad we turned it back on, if we did. In the meantime, I have almost finished a PR that will enable us to run the frontend checks on changed files only.)

**Comment by wincent** [comment]
@hhuijser: I rolled the fixes for the 3 errors into https://github.com/brianchandotcom/liferay-portal/pull/75295

**Comment by petershin** [comment]
> @petershin, just FYI, this one was a result of LPS-97614
> 
> Should this be fixed like this: #75265 ?

@hhuijser - This has been fixed.  Sent a pull to reenable the test: https://github.com/brianchandotcom/liferay-portal/pull/75305

**Pull request closed without merging**
