### PR TITLE
LPS-69794

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:reopen

**Comment by Ithildir** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@Ithildir can we "ban" -SNAPSHOT via CI, particularly for com.liferay.*? or else ppl will keep doing it.

@marcellustavares fyi

**Pull request closed without merging**
