### PR TITLE
LPS-80100 Auto SFLPS-79875, LPS-80100, LPS-79876 Delete or move useless code for VerifyLayout

### PR DESCRIPTION
**Pull request by achaparro**
Hi @jonathanmccann,

Please verify that latest commits are ok.

Thanks!

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@achaparro I fixed the SF issue...

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2aeb24fb0c...7d84d45060

**Comment by achaparro** [comment]
Thanks @brianchandotcom !

**Pull request closed without merging**
