### PR TITLE
LPS-147774 Create test stubs

### PR DESCRIPTION
**Pull request by rodrigocunhaa**
https://github.com/rodrigocunhaa/liferay-portal/pull/1604#issuecomment-1046985347

### CODE REVIEW

**Comment by rodrigocunhaa** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a0a34e5987...bb19afac88

**Comment by brianchandotcom** [comment]
@rodrigocunhaa why didn't this go through CI? Ci is very fast if it's just test cases.

**Comment by rodrigocunhaa** [comment]
@brianchandotcom , tests passed but something wrong happened when trying to forward: https://github.com/rodrigocunhaa/liferay-portal/pull/1604#issuecomment-1046984401

`Unexpected errors occurred while attempting to forward pull request to 'brianchandotcom', please try again later or contact a CI Infrastructure member for assistance.
[Console](https://test-1-27.liferay.com/job/test-portal-source-format/1636//consoleFull)`

It happens some rare times.

**Comment by rodrigocunhaa** [comment]
I manually forwarded to save time.

**Pull request closed without merging**
