### PR TITLE
LPS-70479 SF

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@shuyangzhou

UserGroupsAdminPortletDataHandlerTest.testPrepareManifestSummary

That's strange (happened twice)

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by shuyangzhou** [comment]
Looks like a felix configadmin bug, @tinatian please a look.

**Comment by tinatian** [comment]
OK

**Pull request closed without merging**
