### PR TITLE
More liferay-ui.tld descriptions

### PR DESCRIPTION
**Pull request by jhinkey**
Here are some more descriptions from @westonhancock. /cc @mwilliams2014.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2ea373fcf0...57af57a58f

**Pull request closed without merging**
