### PR TITLE
LPS-73944 Update Organization verify test

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:stop - CI environment issues.

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/98d9c9a630...64ca228ca5

**Comment by brianchandotcom** [comment]
@ealonso see 64ca228ca56c16c237ba5a6b967efc4bd50f966b

Can you backport this? Looks like a useful extraction. Thx.

**Pull request closed without merging**
