### PR TITLE
LPS-65045 Standardize polls-web to new portlet structure

### PR DESCRIPTION
**Pull request by peterfellwock**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
This is a real failure, not sure whether a bug or test fix though. 

@peterfellwock, it looks like the "Community Site" site template is missing. Was that an intentional change? 

at head: 
screen shot 2016-04-29 at 3 43 41 pm

on this pull: 
screen shot 2016-04-29 at 3 43 23 pm

**Comment by peterfellwock** [comment]
@kenjiheigel no this was not the intended behavior of my changes. I changed the PollsPortletKeys for both Polls portlets. I have walked through the steps of the poshi manually and I cannot reproduce the error and I cannot get PoshiRunner to run on my machine. If you can reproduce the Poshi error locally I can look at the server logs and maybe figure out what is going on. In theory this should not happen since this functionality is intact, but since polls could be embedded in a community site it might be possible the error is related. In theory the changes that were made should propagate with no issue but I am just clueless as to why this is happening unless my changes to the PollsPortletKeys are not being used by the PoshiRunner.

**Comment by kenjiheigel** [comment]
@peterfellwock, Community Site displays for you in Site Templates when you build off this branch?

**Comment by kenjiheigel** [comment]
@peterfellwock, I'm going to try building on this branch real quick, but I may not be able to confirm til Monday. In the mean time, I'm going to rerun CI here. This way if it fails again, we'll know that it wasn't cause of a flaky test, and then we can debug it further. 

ci:retest

**Comment by kenjiheigel** [comment]
I built the bundle and just reproduced what the test screenshot is showing, and that the Community Site template is missing. 

@brianchandotcom, we should hold off on merging this pull.

**Comment by kenjiheigel** [comment]
ci:stop

**Comment by peterfellwock** [comment]
@kenjiheigel how can I look at your instance and the logs? Thank you.

**Comment by brianchandotcom** [comment]
@peterfellwock please resend after talking to @kenjiheigel ? Thx.

**Comment by kenjiheigel** [comment]
@peterfellwock, I'll ping you on Slack and we can coordinate.

**Pull request closed without merging**
