### PR TITLE
Update Arquillian Persistence Extension

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
Hey Brian,
   It is needed to publish this new version of the arquillian-extension in our nexus.
Thanks!!!

@csierra, @shuyangzhou, @JorgeFerrer, @mdelapenya

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/77e4a8f7fc...c847a431fd

**Comment by brianchandotcom** [comment]
Ok. I made some tiny changes and then merged it and published a new snapshot! Thx @cgoncas

**Pull request closed without merging**
