### PR TITLE
LPS-169827 Sort

### PR DESCRIPTION
**Pull request by kevenleone**

### CODE REVIEW

**Comment by kevenleone** [comment]
ci:reopen

**Comment by kevenleone** [comment]
Unrelated failures: https://github.com/pt-liferay-solutions/liferay-portal/pull/2863

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d5ee1df774...6ec25ca96a

**Comment by brianchandotcom** [comment]
@gleicelisbino just 6ec25ca96a57cb62407a23bf77dc360c39538509

**Pull request closed without merging**
