### PR TITLE
LRQA-40880 Format JSON String before sending to form builder editor

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-40880

### CODE REVIEW

**Comment by pyoo47** [comment]
There might be an issue with the corresponding 7.0.x pull request so I'm closing both pull requests for now.

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
The earlier issue in 7.0.x has been resolved. These pull requests are ready to be merged.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
