### PR TITLE
LPS-74104

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@pyoo47, Jenkins is not testing the last commit (same as in https://github.com/brianchandotcom/liferay-portal/pull/50857). If you compare the stacktrace with the code in SourceFormatter.java of the last commit, you can see it doesn't match.

**Comment by pyoo47** [comment]
@hhuijser I've been looking into this and so far I don't know why this is happening but let me tell you what I can see in the jenkins logs.

1. At the top level of the pull request test, we can see that the correct commits are being fetched, rebased and then cached as a cache branch on our local-git servers.
```
[beanshell] Fetching from git@github.com:hhuijser/liferay-portal.git refs/heads/LPS-74104_4:refs/heads/cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83
[beanshell] Executing commands: git fetch --progress -v -f git@github.com:hhuijser/liferay-portal.git refs/heads/LPS-74104_4:refs/heads/cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83
[beanshell] Finished executing Bash commands.
[beanshell] 
[beanshell] Fetch completed in 4 seconds 934 ms
[beanshell] Cleaning repository
[beanshell] Resetting HARD to HEAD
[beanshell] Fetching from git@github.com:liferay/liferay-portal.git
[beanshell] Executing commands: git fetch --progress -v -f git@github.com:liferay/liferay-portal.git +refs/heads/*:refs/remotes/upstream/*
[beanshell] Finished executing Bash commands.
[beanshell] 
[beanshell] Fetch completed in 5 seconds 33 ms
[beanshell] Creating branch temp-1502368746244 at starting point 5725f4eaff64041cecab8d5bd43b448a8bdd9afc
[beanshell] The current branch is master. Checking out branch temp-1502368746244.
[beanshell] Executing commands: git checkout -f temp-1502368746244
[beanshell] Deleting local branch master
[beanshell] Creating branch master at starting point 5725f4eaff64041cecab8d5bd43b448a8bdd9afc
[beanshell] The current branch is temp-1502368746244. Checking out branch master.
[beanshell] Executing commands: git checkout -f master
[beanshell] Deleting local branch temp-1502368746244
[beanshell] Creating branch cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83 at starting point 88f3fda4afcee633215fd846d5220a67af529c83
[beanshell] The current branch is master. Checking out branch cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83.
[beanshell] Executing commands: git checkout -f cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83
[beanshell] Executing commands: git rev-parse master
[beanshell] Rebasing master(5725f4eaff64041cecab8d5bd43b448a8bdd9afc) to cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83
[beanshell] Executing commands: git rebase master cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83
[beanshell] First, rewinding head to replay your work on top of it...
[beanshell] Applying: LPS-74104 SF
[beanshell] Applying: LPS-74104 Remove unused methods
[beanshell] Applying: LPS-69661 Change temporary property
[beanshell] Applying: LPS-69661 Exclude all files for now. Remove property when cases are fixed.
[beanshell] Applying: LPS-74104 Remove unused method
[beanshell] Applying: LPS-74104 Move base source-formatter.properties from portal-impl/src to root directory
[beanshell] Applying: LPS-74104 Update links
[beanshell] Applying: LPS-74104 Make sure that all properties only work for files in the directory of the properties file
[beanshell] Applying: LPS-74104 When running from module or subrepo, SF is grabbing incorrect file
[beanshell] Applying: LPS-74104 Rename
[beanshell] Applying: LPS-74104 Sort
[beanshell] Applying: LPS-74104 Add methods
[beanshell] Applying: LPS-74104 Change to set to avoid duplicates
[beanshell] Applying: LPS-74104 source-formatter.properties in root folder is read twice
[beanshell] Applying: LPS-74104 Move base checkstyle-suppressions.xml from portal-impl/src to root directory
[beanshell] Finished executing Bash commands.
[beanshell] 
[beanshell] Executing commands: git branch --contains 5725f4eaff64041cecab8d5bd43b448a8bdd9afc
[beanshell] * cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83
[beanshell]   master
[beanshell]   master-temp-20170810113553951
[beanshell] Finished executing Bash commands.
[beanshell] 
[beanshell] Pushing cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83 to git@cloud-10-0-0-11:liferay/liferay-portal.git cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83Pushing cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83 to git@cloud-10-0-0-12:liferay/liferay-portal.git cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83
[beanshell] Pushing cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83 to git@cloud-10-0-0-14:liferay/liferay-portal.git cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83
[beanshell] 
[beanshell] Pushing cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83 to git@cloud-10-0-0-15:liferay/liferay-portal.git cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83
[beanshell] Pushing cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83 to git@cloud-10-0-0-21:liferay/liferay-portal.git cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83
[beanshell] Pushing cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83 to git@cloud-10-0-0-18:liferay/liferay-portal.git cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83
[beanshell] Pushing cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83 to git@cloud-10-0-0-17:liferay/liferay-portal.git cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83
[beanshell] Pushing cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83 to git@cloud-10-0-0-23:liferay/liferay-portal.git cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83Pushing cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83 to git@cloud-10-0-0-24:liferay/liferay-portal.git cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83
[beanshell] 
[beanshell] Pushing cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83 to git@cloud-10-0-0-28:liferay/liferay-portal.git cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83Pushing cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83 to git@cloud-10-0-0-27:liferay/liferay-portal.git cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83
[beanshell] Pushing cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83 to git@cloud-10-0-0-25:liferay/liferay-portal.git cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83
[beanshell] 
[beanshell] Pushing cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83 to git@cloud-10-0-0-11:liferay/liferay-portal.git cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83-1502368756987
[beanshell] Pushing cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83 to git@cloud-10-0-0-15:liferay/liferay-portal.git cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83-1502368756987
[beanshell] Pushing cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83 to git@cloud-10-0-0-18:liferay/liferay-portal.git cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83-1502368756987
[beanshell] Pushing cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83 to git@cloud-10-0-0-17:liferay/liferay-portal.git cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83-1502368756987
[beanshell] Pushing cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83 to git@cloud-10-0-0-16:liferay/liferay-portal.git cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83-1502368756987
[beanshell] Pushing cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83 to git@cloud-10-0-0-13:liferay/liferay-portal.git cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83-1502368756987
[beanshell] Pushing cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83 to git@cloud-10-0-0-12:liferay/liferay-portal.git cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83-1502368756987
[beanshell] Pushing cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83 to git@cloud-10-0-0-27:liferay/liferay-portal.git cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83-1502368756987
[beanshell] Pushing cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83 to git@cloud-10-0-0-28:liferay/liferay-portal.git cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83-1502368756987
```

2. On the slave that ultimately experiences the failure, we can see that the cached branch is successfully fetched into a local temp branch prior to the start of the actual test.

```
     [exec] Executing "git fetch --progress -v -f git@github-dev.liferay.com:liferay/liferay-portal.git cache-liferay-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-liferay-5725f4eaff64041cecab8d5bd43b448a8bdd9afc:master".
     [exec] Warning: Permanently added 'github-dev.liferay.com,10.0.0.27' (RSA) to the list of known hosts.
     [exec] From github-dev.liferay.com:liferay/liferay-portal
     [exec]  = [up to date]      cache-liferay-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-liferay-5725f4eaff64041cecab8d5bd43b448a8bdd9afc -> master
     [exec] Executing "git fetch --progress -v -f git@github-dev.liferay.com:liferay/liferay-portal.git cache-liferay-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-liferay-5725f4eaff64041cecab8d5bd43b448a8bdd9afc:master" complete.
     [exec] Switched to branch 'master'
     [exec] Switched to branch 'master'
     [exec] HEAD is now at 5725f4e subrepo:ignore Update 'modules/apps/web-experience/layout/.gitrepo'.
     [exec] /opt/dev/projects/github/liferay-jenkins-ee/commands/git_custom_fetch.sh -f git@github-dev.liferay.com:liferay/liferay-portal.git cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83:master-temp-20170810123831699
     [exec] Executing "git fetch --progress -v -f git@github-dev.liferay.com:liferay/liferay-portal.git cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83:master-temp-20170810123831699".
     [exec] Warning: Permanently added 'github-dev.liferay.com,10.0.0.12' (RSA) to the list of known hosts.
     [exec] remote: Counting objects: 292, done.[K
     [exec] remote: Compressing objects:   1% (1/91)   [K
     [exec] remote: Compressing objects:   2% (2/91)   [Kremote: Compressing objects:   3% (3/91)   [Kremote: Compressing objects:   4% (4/91)   [Kremote: Compressing objects:   5% (5/91)   [Kremote: Compressing objects:   6% (6/91)   [Kremote: Compressing objects:   7% (7/91)   [Kremote: Compressing objects:   8% (8/91)   [Kremote: Compressing objects:   9% (9/91)   [Kremote: Compressing objects:  10% (10/91)   [Kremote: Compressing objects:  12% (11/91)   [Kremote: Compressing objects:  13% (12/91)   [Kremote: Compressing objects:  14% (13/91)   [Kremote: Compressing objects:  15% (14/91)   [Kremote: Compressing objects:  16% (15/91)   [Kremote: Compressing objects:  17% (16/91)   [Kremote: Compressing objects:  18% (17/91)   [Kremote: Compressing objects:  19% (18/91)   [Kremote: Compressing objects:  20% (19/91)   [Kremote: Compressing objects:  21% (20/91)   [Kremote: Compressing objects:  23% (21/91)   [Kremote: Compressing objects:  24% (22/91)   [Kremote: Compressing objects:  25% (23/91)   [Kremote: Compressing objects:  26% (24/91)   [Kremote: Compressing objects:  27% (25/91)   [Kremote: Compressing objects:  28% (26/91)   [Kremote: Compressing objects:  29% (27/91)   [Kremote: Compressing objects:  30% (28/91)   [Kremote: Compressing objects:  31% (29/91)   [Kremote: Compressing objects:  32% (30/91)   [Kremote: Compressing objects:  34% (31/91)   [Kremote: Compressing objects:  35% (32/91)   [Kremote: Compressing objects:  36% (33/91)   [Kremote: Compressing objects:  37% (34/91)   [Kremote: Compressing objects:  38% (35/91)   [Kremote: Compressing objects:  39% (36/91)   [Kremote: Compressing objects:  40% (37/91)   [Kremote: Compressing objects:  41% (38/91)   [Kremote: Compressing objects:  42% (39/91)   [Kremote: Compressing objects:  43% (40/91)   [Kremote: Compressing objects:  45% (41/91)   [Kremote: Compressing objects:  46% (42/91)   [Kremote: Compressing objects:  47% (43/91)   [Kremote: Compressing objects:  48% (44/91)   [Kremote: Compressing objects:  49% (45/91)   [Kremote: Compressing objects:  50% (46/91)   [Kremote: Compressing objects:  51% (47/91)   [Kremote: Compressing objects:  52% (48/91)   [Kremote: Compressing objects:  53% (49/91)   [Kremote: Compressing objects:  54% (50/91)   [Kremote: Compressing objects:  56% (51/91)   [Kremote: Compressing objects:  57% (52/91)   [Kremote: Compressing objects:  58% (53/91)   [Kremote: Compressing objects:  59% (54/91)   [Kremote: Compressing objects:  60% (55/91)   [Kremote: Compressing objects:  61% (56/91)   [Kremote: Compressing objects:  62% (57/91)   [Kremote: Compressing objects:  63% (58/91)   [Kremote: Compressing objects:  64% (59/91)   [Kremote: Compressing objects:  65% (60/91)   [Kremote: Compressing objects:  67% (61/91)   [Kremote: Compressing objects:  68% (62/91)   [Kremote: Compressing objects:  69% (63/91)   [Kremote: Compressing objects:  70% (64/91)   [Kremote: Compressing objects:  71% (65/91)   [Kremote: Compressing objects:  72% (66/91)   [Kremote: Compressing objects:  73% (67/91)   [Kremote: Compressing objects:  74% (68/91)   [Kremote: Compressing objects:  75% (69/91)   [Kremote: Compressing objects:  76% (70/91)   [Kremote: Compressing objects:  78% (71/91)   [Kremote: Compressing objects:  79% (72/91)   [Kremote: Compressing objects:  80% (73/91)   [Kremote: Compressing objects:  81% (74/91)   [Kremote: Compressing objects:  82% (75/91)   [Kremote: Compressing objects:  83% (76/91)   [Kremote: Compressing objects:  84% (77/91)   [Kremote: Compressing objects:  85% (78/91)   [Kremote: Compressing objects:  86% (79/91)   [Kremote: Compressing objects:  87% (80/91)   [Kremote: Compressing objects:  89% (81/91)   [Kremote: Compressing objects:  90% (82/91)   [Kremote: Compressing objects:  91% (83/91)   [Kremote: Compressing objects:  92% (84/91)   [Kremote: Compressing objects:  93% (85/91)   [Kremote: Compressing objects:  94% (86/91)   [Kremote: Compressing objects:  95% (87/91)   [Kremote: Compressing objects:  96% (88/91)   [Kremote: Compressing objects:  97% (89/91)   [Kremote: Compressing objects:  98% (90/91)   [Kremote: Compressing objects: 100% (91/91)   [Kremote: Compressing objects: 100% (91/91), done.[Kremote: Total 242 (delta 140), reused 201 (delta 99)[K
     [exec] Receiving objects:   0% (1/242)   
     [exec] Receiving objects:   1% (3/242)   Receiving objects:   2% (5/242)   Receiving objects:   3% (8/242)   Receiving objects:   4% (10/242)   Receiving objects:   5% (13/242)   Receiving objects:   6% (15/242)   Receiving objects:   7% (17/242)   Receiving objects:   8% (20/242)   Receiving objects:   9% (22/242)   Receiving objects:  10% (25/242)   Receiving objects:  11% (27/242)   Receiving objects:  12% (30/242)   Receiving objects:  13% (32/242)   Receiving objects:  14% (34/242)   Receiving objects:  15% (37/242)   Receiving objects:  16% (39/242)   Receiving objects:  17% (42/242)   Receiving objects:  18% (44/242)   Receiving objects:  19% (46/242)   Receiving objects:  20% (49/242)   Receiving objects:  21% (51/242)   Receiving objects:  22% (54/242)   Receiving objects:  23% (56/242)   Receiving objects:  24% (59/242)   Receiving objects:  25% (61/242)   Receiving objects:  26% (63/242)   Receiving objects:  27% (66/242)   Receiving objects:  28% (68/242)   Receiving objects:  29% (71/242)   Receiving objects:  30% (73/242)   Receiving objects:  31% (76/242)   Receiving objects:  32% (78/242)   Receiving objects:  33% (80/242)   Receiving objects:  34% (83/242)   Receiving objects:  35% (85/242)   Receiving objects:  36% (88/242)   Receiving objects:  37% (90/242)   Receiving objects:  38% (92/242)   Receiving objects:  39% (95/242)   Receiving objects:  40% (97/242)   Receiving objects:  41% (100/242)   Receiving objects:  42% (102/242)   Receiving objects:  43% (105/242)   Receiving objects:  44% (107/242)   Receiving objects:  45% (109/242)   Receiving objects:  46% (112/242)   Receiving objects:  47% (114/242)   Receiving objects:  48% (117/242)   Receiving objects:  49% (119/242)   Receiving objects:  50% (121/242)   Receiving objects:  51% (124/242)   Receiving objects:  52% (126/242)   Receiving objects:  53% (129/242)   Receiving objects:  54% (131/242)   Receiving objects:  55% (134/242)   Receiving objects:  56% (136/242)   Receiving objects:  57% (138/242)   Receiving objects:  58% (141/242)   Receiving objects:  59% (143/242)   Receiving objects:  60% (146/242)   Receiving objects:  61% (148/242)   Receiving objects:  62% (151/242)   Receiving objects:  63% (153/242)   Receiving objects:  64% (155/242)   Receiving objects:  65% (158/242)   Receiving objects:  66% (160/242)   Receiving objects:  67% (163/242)   Receiving objects:  68% (165/242)   Receiving objects:  69% (167/242)   Receiving objects:  70% (170/242)   Receiving objects:  71% (172/242)   Receiving objects:  72% (175/242)   Receiving objects:  73% (177/242)   Receiving objects:  74% (180/242)   Receiving objects:  75% (182/242)   Receiving objects:  76% (184/242)   Receiving objects:  77% (187/242)   Receiving objects:  78% (189/242)   Receiving objects:  79% (192/242)   Receiving objects:  80% (194/242)   Receiving objects:  81% (197/242)   Receiving objects:  82% (199/242)   Receiving objects:  83% (201/242)   Receiving objects:  84% (204/242)   Receiving objects:  85% (206/242)   Receiving objects:  86% (209/242)   Receiving objects:  87% (211/242)   Receiving objects:  88% (213/242)   Receiving objects:  89% (216/242)   Receiving objects:  90% (218/242)   Receiving objects:  91% (221/242)   Receiving objects:  92% (223/242)   Receiving objects:  93% (226/242)   Receiving objects:  94% (228/242)   Receiving objects:  95% (230/242)   Receiving objects:  96% (233/242)   Receiving objects:  97% (235/242)   Receiving objects:  98% (238/242)   Receiving objects:  99% (240/242)   Receiving objects: 100% (242/242)   Receiving objects: 100% (242/242), 22.29 KiB | 0 bytes/s, done.Resolving deltas:   0% (0/140)   
     [exec] Resolving deltas:   4% (6/140)   Resolving deltas:   5% (7/140)   Resolving deltas:   8% (12/140)   Resolving deltas:  10% (14/140)   Resolving deltas:  20% (29/140)   Resolving deltas:  30% (43/140)   Resolving deltas:  31% (44/140)   Resolving deltas:  32% (45/140)   Resolving deltas:  33% (47/140)   Resolving deltas:  34% (48/140)   Resolving deltas:  35% (49/140)   Resolving deltas:  36% (51/140)   Resolving deltas:  37% (52/140)   Resolving deltas:  38% (54/140)   Resolving deltas:  39% (55/140)   Resolving deltas:  40% (56/140)   Resolving deltas:  41% (58/140)   Resolving deltas:  42% (59/140)   Resolving deltas:  43% (61/140)   Resolving deltas:  44% (62/140)   Resolving deltas:  45% (63/140)   Resolving deltas:  46% (65/140)   Resolving deltas:  47% (66/140)   Resolving deltas:  57% (80/140)   Resolving deltas:  67% (95/140)   Resolving deltas:  77% (108/140)   Resolving deltas:  80% (112/140)   Resolving deltas:  86% (121/140)   Resolving deltas:  87% (123/140)   Resolving deltas:  90% (126/140)   Resolving deltas:  92% (129/140)   Resolving deltas:  93% (131/140)   Resolving deltas:  94% (132/140)   Resolving deltas:  95% (133/140)   Resolving deltas:  97% (137/140)   Resolving deltas: 100% (140/140)   Resolving deltas: 100% (140/140), completed with 41 local objects.From github-dev.liferay.com:liferay/liferay-portal
     [exec]  * [new branch]      cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83 -> master-temp-20170810123831699
     [exec] Executing "git fetch --progress -v -f git@github-dev.liferay.com:liferay/liferay-portal.git cache-brianchandotcom-5725f4eaff64041cecab8d5bd43b448a8bdd9afc-hhuijser-88f3fda4afcee633215fd846d5220a67af529c83:master-temp-20170810123831699" complete.
```

Theoretically, this should ensure that we are running the tests with the latest code but based on the stack trace, this does not seem to be the case. I am investigating whether or not it is possible that the test is somehow being run using the latest published SourceFormatter jar.

**Comment by Ithildir** [comment]
Hi @hhuijser,
The error on the `source-format-jdk8` batch is my fault, I'm going to fix it in the next few minutes.

For `modules-unit-jdk8`, instead, the problem is that running the unit tests in some of the `modules/util` modules starts the published SF version.. So you should probably use the *fake gradle cache* trick for this pull.

**Comment by Ithildir** [comment]
I sent a fix at https://github.com/brianchandotcom/liferay-portal/pull/50869.

**Comment by hhuijser** [comment]
Thanks @pyoo47 @Ithildir

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
ci:retest

**Comment by hhuijser** [comment]
@Ithildir, still failing. I will try sending a completely new pull...

**Comment by hhuijser** [comment]
new pull: https://github.com/brianchandotcom/liferay-portal/pull/50880

**Pull request closed without merging**
