### PR TITLE
Lps 76015

### PR DESCRIPTION
**Pull request by shuyangzhou**
@brianchandotcom please do not auto back this one, since it removes petra-content.
@preston-crary will do the backport to add it back into modules-compat.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
@shuyangzhou Talked with Brian about these changes, we're adding too much code duplication everywhere.  I'm going to resend just the fix for user's admin.

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/53544 for the fix to LoginConfigurationActionImpl.

**Comment by Preston-Crary** [comment]
ci:close

**Pull request closed without merging**
