### PR TITLE
master-qa-19225

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LRQA-19225

@brianchandotcom 
This is an upgrade test for the 6.2.3 data archive. I had to add a couple of conditions to the build-test.xml Ant in order for it to work.

This test will not pass right now (and it won't run as part of the PR tester), but I wanted to get it in in preparation for the upgrade fixes from Miguel to go in.

CC @jhendley @jpince @michaelhashimoto

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@brianchiu we have a lot unstable tests?

**Comment by brianchiu** [comment]
This is a bug caused by https://github.com/brianchandotcom/liferay-portal/pull/33646.

The issue is that the user avatar image becomes HTML.

This is what it should look like:

before-1

This is what it looks like after [LPS-60598](https://issues.liferay.com/browse/LPS-60598)

after

I reverted https://github.com/liferay/liferay-portal/commit/75643b60273f24cb20eed766685888e7a865f071 and was no longer able to reproduce this issue.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchiu** [comment]
hrm... looking at the new failures

**Comment by jhendley** [comment]
Thanks, Brian.

On Mon, Dec 21, 2015 at 10:35 PM, Brian Chiu <notifications@github.com>
wrote:

> hrm... looking at the new failures
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/33653#issuecomment-166529862>
> .
>



-- 
Joel Hendley
Director of QA
@jhendley <https://twitter.com/jhendley>

<http://liferay.com/>
Enterprise. Open Source. For Life
Check out Liferay in the latest Gartner Report
<https://www.liferay.com/about-us/awards/gartnermq-portals>.
Web <http://www.liferay.com/> | Facebook <http://facebook.com/liferay> |
Twitter <http://twitter.com/liferay>

**Comment by brianchiu** [comment]
The roles tests are failing because they can't find a vertical ellipsis when defining permissions for a role. It's hard for me to tell if it's a test fix or bug right off the bat because I don't know what it ought to look like.

The sample LAR test could be a fluke. It seems the test timed out waiting for the portlet to load.

The calendar tests are all failing because after adding an event a "portlet is unavailable" message displays. Since 4 calendar tests failed with that same failure, this one is likely a bug.

**Comment by brianchandotcom** [comment]
Let's do the rest tomorrow @brianchiu Get some rest man.

**Comment by daviddotzhang** [comment]
Thanks, guys,

I will check it, and update it accordingly.

On Tue, Dec 22, 2015 at 2:50 PM, Brian Chan <notifications@github.com>
wrote:

> Let's do the rest tomorrow @brianchiu <https://github.com/brianchiu> Get
> some rest man.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/33653#issuecomment-166531794>
> .
>



-- 
David

Jr. Engineer, Technical Support

Subscription Services

Liferay Dalian Software Co., Ltd.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/944a10a479...89748872f5

**Pull request closed without merging**
