### PR TITLE
LPS-78486 Adapt to new location and latest API changes

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:test

**Comment by ahdezma** [comment]
ci:test:sf

**Comment by ahdezma** [comment]
ci:test

**Comment by ahdezma** [comment]
ci:test:relevant

**Comment by ahdezma** [comment]
ci:test:relevant

**Comment by ahdezma** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f19088a86f...35c82c2ca8

**Pull request closed without merging**
