### PR TITLE
LPS-138590 Include the account-admin-web module in the release build

### PR DESCRIPTION
**Pull request by patriciajeanperez**
Manual forward from https://github.com/liferay-usm/liferay-portal/pull/248
https://issues.liferay.com/browse/LPS-138590
https://issues.liferay.com/browse/LRQA-63219

cc @pei-jung @drewbrokke

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:reopen

**Comment by patriciajeanperez** [comment]
ci:test:sf

**Comment by patriciajeanperez** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8058fd3f28...e6022242fe

**Pull request closed without merging**
