### PR TITLE
LPS-168288 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-168288

This is only for master.

@ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.
See https://github.com/liferay-echo/liferay-portal/pull/10278 
ci:test:stable - 28 out of 28 jobs passed
ci:test:relevant - 233 out of 241 jobs passed in 2 hours 29 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/caa4cf1485...f5f56346fe

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f5f56346fe...f5f56346fe

**Pull request closed without merging**
