### PR TITLE
LPS-71651 Deflake UserIndexerTest

### PR DESCRIPTION
**Pull request by arboliveira**
Author: @BryanEngler 
Reviewer: @arboliveira

https://issues.liferay.com/browse/LPS-71651

### CODE REVIEW

**Comment by arboliveira** [comment]
`ReleaseVersionsTest.testReleaseVersions` is **unstable** 

https://github.com/brianchandotcom/liferay-portal/pulls?utf8=%E2%9C%93&q=testReleaseVersions

**Comment by arboliveira** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@pyoo47 something is strange

```
junit.framework.AssertionFailedError: Difference in Bundle-Version for modules/apps/web-experience/rss/rss-util between master (1.0.7, defined in bnd.bnd) and release (1.0.8, defined in bnd.bnd) branches is not allowed. Please update "Bundle-Version: 1.0.8" in modules/apps/web-experience/rss/rss-util/bnd.bnd for the master branch.
	at com.liferay.portal.release.versions.ReleaseVersionsTest._checkReleaseVersion(ReleaseVersionsTest.java:244)
	at com.liferay.portal.release.versions.ReleaseVersionsTest.access$200(ReleaseVersionsTest.java:50)
	at com.liferay.portal.release.versions.ReleaseVersionsTest$1.preVisitDirectory(ReleaseVersionsTest.java:122)

```
But both say 1.0.8.. so not sure why we're getting some many of these errors.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a0f851b657...2b1aee642e

**Comment by brianchandotcom** [comment]
@arboliveira @BryanEngler please backport if it's better to. Thx.

**Pull request closed without merging**
