### PR TITLE
 LPS-161955 Rename

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-161955

@ealonso

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See [liferay-echo#7560](https://github.com/liferay-echo/liferay-portal/pull/9960)

:heavy_check_mark: ci:test:stable - 28 out of 28 jobs passed
:x: ci:test:relevant - 150 out of 199 jobs passed in 3 hours 14 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8db2d9092d...53fd596592

**Comment by brianchandotcom** [comment]
@ozysouza @ealonso see 53fd596592ef905b12147e1024619d5d19ff93e9

**Pull request closed without merging**
