### PR TITLE
LPS-67695

### PR DESCRIPTION
**Pull request by lionah**
Ive had to move around the upgrade code due to an incorrect assumption of starting version numbers. Please backport to 7.0.x. Thank you.

### CODE REVIEW

**Comment by jpince** [comment]
@lionah It looks like there is a SF error unique to this pull, can you please take a look?
```
org.junit.ComparisonFailure: ../../../modules/apps/marketplace/marketplace-service/src/main/java/com/liferay/marketplace/internal/upgrade/v0_0_1/UpgradeModule.java expected:<...
import com.liferay.[portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.upgrade.UpgradeProcess];

/**
 * @author Ry...> but was:<...
import com.liferay.[marketplace.util.ContextUtil;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.upgrade.UpgradeProcess;

import java.io.IOException;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException];

/**
 * @author Ry...>
```

**Comment by lionah** [comment]
Thanks @jpince, I've force pushed an update since this ticket is still open.

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ff44d60c3b...b32b4ec4d9

**Comment by brianchandotcom** [comment]
@lionah see b32b4ec4d92ec33631eb06a14c80b3f44574658d thx.

**Pull request closed without merging**
