### PR TITLE
LPS-98218 A/B Test Sidebar [DO NOT BACKPORT]

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
@andresfulla

**Comment by brianchandotcom** [comment]
@epgarcia can you resend?

SegmentsExperimentWebKeys should be for request or session attributes, and they're usually in the format of XYZ_ABC for the String value.

```
	public static final String SEGMENTS_EXPERIMENT_PANEL_STATE =
		"com.liferay.segments.experiment.web_panelState";
```

Doesn't fit that format. Please resend.

**Comment by epgarcia** [comment]
@brianchandotcom I copied this from com.liferay.product.navigation.product.menu.constants.ProductNavigationProductMenuWebKeys#PRODUCT_NAVIGATION_PRODUCT_MENU_STATE. In other cases with SessionClicks, we use the literal (instead of a constants) repeated multiple times. Should I follow that? Thanks!

**Comment by epgarcia** [comment]
@brianchandotcom I send an alternative without the webKey. See #75950.

**Pull request closed without merging**
