### PR TITLE
LPS-91295 Enable text autotagging for Journal

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:reopen

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Bravo... 0 changes from me.

Keep an eye out for common patterns between all of these auto* modules so that we have less code duplication in the future. Imagine as we start adding *-asset-auto-tagger-* for every thing... this is going to get very verbose very fast. I'm even thinking the Language keys is going to be a problem for translators.

The more you do this, the more patterns you'll see and then you can start experimenting with how to consolidate.

Again, very nicely done. @cgoncas @adolfopa

**Pull request closed without merging**
