### PR TITLE
Lps 75775

### PR DESCRIPTION
**Pull request by shuyangzhou**
This is constants relocating, which is safe, no need of modules-compat.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ad7d43a0a7...40c10086b3

**Comment by brianchandotcom** [comment]
@mtambara can you send me a backport to 7.0.x? I didn't merge in the whitelist since I couldn't easily CP it. You'll need to send me a commit with the whitelist and I'll frontport that.

**Comment by mtambara** [comment]
@brianchandotcom Backport sent at https://github.com/brianchandotcom/liferay-portal-ee/pull/18758

**Pull request closed without merging**
