### PR TITLE
LPS-171611 Rewrite actionableQuery to DSLQuery in UserExpandoColumnModelListener

### PR DESCRIPTION
**Pull request by GabrielHenriquedev**
hello braian, this pull request solves the problem of this [conversation ](https://github.com/brianchandotcom/liferay-portal/pull/128183)

Thanks for the guidance.

### CODE REVIEW

**Comment by GabrielHenriquedev** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/20e0bf9ab8...76df499c87

**Comment by brianchandotcom** [comment]
@GabrielHenriquedev 

What is wrong with this line?

```
			long organizationClassNameId =
				_classNameLocalService.getClassNameId(User.class.getName());
```

Details matter.

See 681726db c4a37616 and 76df499c

**Comment by GabrielHenriquedev** [comment]
Hello @brianchandotcom , I noticed the difference, I'll stay tuned for the next one.

**Pull request closed without merging**
