### PR TITLE
LPS-79976 Fix ignored line number

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test

**Comment by jkappler** [comment]
cc:// @kyle-miho, @pavel-savinov

**Comment by jkappler** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@shuyangzhou another Tika one

junit.framework.AssertionFailedError: 
Unable to extract text from Xz7E3ILZ
org.apache.tika.exception.TikaException: Failed to detect the character encoding of a document
	at org.apache.tika.detect.AutoDetectReader.detect(AutoDetectReader.java:76)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ea35a3821e...096effdadd

**Pull request closed without merging**
