### PR TITLE
LPS-99155 Making sure the asset type is lowercase

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6b7896e179...7efe252a7c

**Comment by brianchandotcom** [comment]
@4lejandrito I couldn't backport this because the key

there-are-no-comments-yet

is not in 7.2.x.

I think we have missing backports in 7.2.x. Can you send me this, along with whatever else is missing in 7.2.x? Sorry! Thx.

**Comment by 4lejandrito** [comment]
Will do. Thanks!

**Comment by brianchandotcom** [comment]
@4lejandrito I think it came from LPS-98812 from @ealonso

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal-ee/pull/25754. I didn't apply @ealonso's change. I will talk to him tomorrow and see if we can do a partial backport of his story.

**Pull request closed without merging**
