### PR TITLE
LPS-86223 Move to internal package

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cbb109086a...8666624a76

**Comment by brianchandotcom** [comment]
@jkappler see minor changes in upstream.

**Pull request closed without merging**
