### PR TITLE
LPS-61818 align the menus to the right direction

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @jbalsas I have deleted the remaining data-navigation in java.

@marcellustavares, there was a data-navigation in kaleo that I deleted. can you please have a look? thanks!

**Comment by marcellustavares** [comment]
Thanks @juliocamarero, I think we may need to still have something to workflow portlets to prevent SPA but I'll check with @brunobasto.

Regards,

**Comment by jbalsas** [comment]
Hey @marcellustavares, things have been working like that for a couple of weeks now, so chances are that if you haven't noticed, those places are now working just fine with SPA :wink: 

If not, the new selector to disable spa navigation is `data-senna="off"`

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/10d1a0ca94...3e2b762593

**Pull request closed without merging**
