### PR TITLE
LPS-75084 My Organizations Portlet leaks every organization within the portal

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @jonathanmccann @drewbrokke

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9eb856a0ca...586cbeee59

**Pull request closed without merging**
