### PR TITLE
LPD-26931 New naming for REST Client SAP entry

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Following up on https://github.com/brianchandotcom/liferay-portal/pull/152191#issuecomment-2220276880 and our call. Since then I have worked with the Headless team to agree this new name for the SAP entry which customers should easier relate to UI concepts and documentation.

I am manually forwarding this because general CI testing was done on previous PRs. This PR is only changing naming. 
I have however run ci:test:sf to check these tweaks on liferay-appsec/liferay-portal/pull/1843 .

cc @ChrisKian @4lejandrito

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/00ad4d1072...731d0dcf90

**Comment by brianchandotcom** [comment]
@stian-sigvartsen please review changes in my origin

**Comment by brianchandotcom** [comment]
@daiazius @stian-sigvartsen please review changes in my origin. Thx.

**Comment by brianchandotcom** [comment]
Speciifcally 9639adb7 @stian-sigvartsen @daiazius I'm not sure if my naming is consistent or not. But please review my other commits as well.

**Comment by stian-sigvartsen** [comment]
Thanks for catching those issue Brian!
With the change you made in f906ca0a1d60887018150bda76aacf4ca45c8cd1 I have some concerns that a future rename of `RESTClientHttpRequest` will cause a regression in REST Client handling (Headless API dispatch errors) so the Headless team may want to consider adding an integration test for that at some point. But I think the change itself is fine, and it allows us to evolve this easier over time.  cc @4lejandrito

**Pull request closed without merging**
