### PR TITLE
LPS-68664

### PR DESCRIPTION
**Pull request by danielkocsis**

### CODE REVIEW

**Comment by danielkocsis** [comment]
Test failures are probably unrelated

**Comment by jpince** [comment]
@pyoo47 @michaelhashimoto unit tests failed with a maven issue?

**Comment by pyoo47** [comment]
@jpince The maven failures are very suspicious in that they seem to suggest that something in the build scripts for these tests is not set up correctly. The fact that it mentions a project called, "foo" implies that a default setting that should have been customized was not customized.

```
[Test worker] ERROR org.apache.maven.cli.MavenCli - Failed to execute goal on project foo: Could not resolve dependencies for project com.test:foo:jar:1.0.0: Failed to collect dependencies at jstl:jstl:jar:1.2: Failed to read artifact descriptor for jstl:jstl:jar:1.2: Could not transfer artifact jstl:jstl:pom:1.2 from/to default (http://repository.liferay.com/nexus/content/groups/public): squid.lax.liferay.com: Unknown host squid.lax.liferay.com -> [Help 1]
```

The second failure is almost exactly the same except the project is called "portlet-portlet".

```
[Test worker] ERROR org.apache.maven.cli.MavenCli - Failed to execute goal on project portlet-portlet: Could not resolve dependencies for project com.test:portlet-portlet:jar:1.0.0: Failed to collect dependencies at jstl:jstl:jar:1.2: Failed to read artifact descriptor for jstl:jstl:jar:1.2: Could not transfer artifact jstl:jstl:pom:1.2 from/to default (http://repository.liferay.com/nexus/content/groups/public): squid.lax.liferay.com: unknown error: Unknown host squid.lax.liferay.com: unknown error -> [Help 1]
```

**Comment by jpince** [comment]
retesting this pull so see if the error reoccurs and work is needed on this backend test.
ci:retest
Pull looks fine from a testing perspective.

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@matethurzo @pavel-savinov @danielkocsis see a29bba276919a736d5d7063411147d25aea22b04

Thx.

**Pull request closed without merging**
