### PR TITLE
LPS-169559 Add LIst Type Entries ERC on Local Service and Rest Layers

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-169559

### CODE REVIEW

**Comment by mateussgn** [comment]
Sent directly because the tests had passed [here](https://github.com/liferay-objects/liferay-portal/pull/1558).

**Comment by mateussgn** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@mateussgn sometimes you use null


```
				listTypeEntryLocalService.addListTypeEntry(
					null, 
```

Sometimes

```
		return _listTypeEntryLocalService.addListTypeEntry(
			RandomTestUtil.randomString(), user.getUserId(),
```

Will null always work? If so, we should use null. Please find out where you copied this from and make those use cases identical too.

Thx.

**Comment by mateussgn** [comment]
Alright! I'll resend it.

**Comment by mateussgn** [comment]
Resent; https://github.com/brianchandotcom/liferay-portal/pull/128194

**Pull request closed without merging**
