### PR TITLE
LPS-104378 Using constants

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @brianchandotcom,

We want to build a page for depot in which users can configure which apps to include (DL, Journal... etc). 

This is the first step towards that goal.

**Comment by 4lejandrito** [comment]
@adolfopa

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
Failures not related.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5ba0154e9e...2083aa6588

**Pull request closed without merging**
