### PR TITLE
LPS-143349

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Unrelated failures: https://github.com/hhuijser/liferay-portal/pull/6094

**Comment by hhuijser** [comment]
@brianchandotcom please publish SF

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/62ca8cad83...8ebfcef547

**Comment by brianchandotcom** [comment]
@hhuijser published. Thanks Hugo!

**Pull request closed without merging**
