### PR TITLE
LPS-64198

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi Brian,

These changes has been reviewed by @migue [here](https://github.com/migue/liferay-portal/pull/729).

Thanks!

Regards,

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@shuyangzhou this shouldn't compile and should fail CI... our JSP compile task should use the jars described from the module....

**Comment by shuyangzhou** [comment]
The jsp compile task is only scanning all available jars to build a giant classpath and hope it includes everything it needs. It is too hard to figure out what a module needs to compile jsp during compile time. That's not something our current tools from ant can do.

**Comment by brianchandotcom** [comment]
Ok, we just fixed it in upstream via https://github.com/brianchandotcom/liferay-portal/pull/37798

I'm running ci:retest, JSP compile should fail now for this pull. @Ithildir

**Comment by brianchandotcom** [comment]
@antonio-ortega can you resend? JSP error has now been exposed.. but more than that, I don't think this is the right fix. If I go to portal.properties, I would not expect to see system.properties, but only the portal ones... please resend. Thx.

**Pull request closed without merging**
