### PR TITLE
LPS-100512

### PR DESCRIPTION
**Pull request by Preston-Crary**
CC @shuyangzhou

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/289f1db65e...632a84bc94

**Comment by brianchandotcom** [comment]
@Preston-Crary no upgrade needed right? tables will auto create?

@achaparro is this still true? If not, please send me an upgrade. Thx.

**Comment by Preston-Crary** [comment]
Liferay Service extender registers the 0.0.0 -> 0.0.1 upgrade.

**Comment by achaparro** [comment]
Hey @brianchandotcom,

Yeah, as @Preston-Crary, we generate automatically the Initial Database Creation upgrade from 0.0.0 to the required schema version, 1.0.0 in this case.

So, no need for an upgrade process.

Cheers!

**Pull request closed without merging**
