### PR TITLE
LPS-67777 Don't set status explicitly

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @adolfopa

**Comment by jpince** [comment]
@sergiogonzalez SF error unique to this pull
```
org.junit.ComparisonFailure: ../../../modules/apps/knowledge-base/knowledge-base-web/src/main/java/com/liferay/knowledge/base/web/internal/portlet/configuration/icon/MoveKBArticlePortletConfigurationIcon.java 

expected:
<...
import com.liferay.[]portal.kernel.langua...> 

but was:
<...
import com.liferay.[knowledge.base.web.internal.constants.KBWebKeys;
import com.liferay.]portal.kernel.langua...>
```

**Comment by brianchandotcom** [comment]
@jpince I fixed the SF.. will merge.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by sergiogonzalez** [comment]
thx @brianchandotcom @jpince

**Pull request closed without merging**
