### PR TITLE
LPS-117587 Fixing compile issue

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
@brianchandotcom this fixes the compile issue on your origin.

**Comment by ealonso** [comment]
cc: @jpince

**Comment by brianchandotcom** [comment]
@4lejandrito sorry! thx for catching this.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7b7adb893a...e1d71b2abd

**Pull request closed without merging**
