### PR TITLE
LRQA-33537 | master

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-33537

See corresponding ee-7.0.x PR [here](https://github.com/brianchandotcom/liferay-portal-ee/pull/17601).

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@xbrianlee can you resend this?

prepare-tomcat-root-xml should mention that it is preparing it for the ext env. Thx.

```
<condition property="ext.workaround.enabled">
					<not>
				    	<resourcecontains resource="${app.server.dir}/conf/Catalina/localhost/ROOT.xml" substring="ExtResourceSet" />
				    </not>
				</condition>

				<if>
					<equals arg1="${ext.workaround.enabled}" arg2="true" />
					<then>
						<antcall target="prepare-tomcat-root-xml" />
					</then>
				</if>
```

Should just be in that target call. If it's not needed, skip the logic. That way, it's all in one place and you don't have logic in 2 places.

Please resend.

**Comment by xbrianlee** [comment]
Resent https://github.com/brianchandotcom/liferay-portal/pull/49998

**Pull request closed without merging**
