### PR TITLE
master-en-253

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LPS-57564

### CODE REVIEW

**Comment by evannagayama** [comment]
This will have 2 poshi test failures because of these 2 commits were let through:
https://github.com/brianchandotcom/liferay-portal/pull/32319
https://github.com/brianchandotcom/liferay-portal/pull/32320

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1841a6170d...f840aed109

**Comment by juliocamarero** [comment]
@ZoltanTakacs can you please backport this pull? thanks a lot!

**Comment by ZoltanTakacs** [comment]
Hey @juliocamarero,

According to Josh @stattuskuo, "...this upcoming release will have backport requests in the branch as long as they were sent up until Tuesday (11/17). We would like to avoid additional backports unless completely necessary so that we can avoid last minute regression issues. However, if there is anything critical, please let us (or your team) know."

- Since it is quite a big change, do we really need this in Alpha 3?

Thanks for the clarification in advance,
Zoltán

/cc @jhendley

**Comment by juliocamarero** [comment]
I wanted this to be included so that beta testers could start playing with it as soon as possible and gather feedback sooner. But being strict it is not a bug fix and it can generate regressions.... therefore, I am ok with waiting to Alpha 4 to include this.

thanks!

**Comment by ZoltanTakacs** [comment]
Thank you Julio!

**Pull request closed without merging**
