### PR TITLE
LPS-117884 remove added lcs reference

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:reopen

**Comment by nhpatt** [comment]
I think the root cause could be the ant setup-profile-dxp script that keeps downloading lcs module when it shouldn't

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a20c7ad437...f9833279ea

**Comment by brianchandotcom** [comment]
My bad @nhpatt 

@hhuijser sorry!

**Pull request closed without merging**
