### PR TITLE
LPS-91058 Add tests

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f596e539ba...3d2c88a4e4

**Comment by brianchandotcom** [comment]
This is weird:

```
		_segmentsExperienceLocalService.fetchDefaultSegmentsExperience(
			_group.getGroupId(), _classNameId, _classPK, true);
		_addSegmentsExperience(serviceContext);
		_addSegmentsExperience(serviceContext);
```

Can you send a follow up pull? We're calling fetch but not assigning it to anything. Merged.

@epgarcia @darquesdev

**Comment by epgarcia** [comment]
Thanks @brianchandotcom, we'll send a follow up pull fixing this today.

**Comment by epgarcia** [comment]
See #68891

**Pull request closed without merging**
