### PR TITLE
LPS-110184 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LPS-110184
https://issues.liferay.com/browse/LRQA-57451

### CODE REVIEW

**Comment by john-co** [comment]
ci:reopen

**Comment by john-co** [comment]
Please push directly based on several ci test relevant testing finding unrelated test failures:

https://github.com/brianchandotcom/liferay-portal/pull/87110#issue-396895367

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/39664e9166...b46c624337

**Pull request closed without merging**
