### PR TITLE
LPS-166045 | LPS-167518 - Improvements in collection view

### PR DESCRIPTION
**Pull request by jkappler**
Follow up from https://github.com/brianchandotcom/liferay-portal/pull/125949

### CODE REVIEW

**Comment by jkappler** [comment]
ci:reopen

**Comment by jkappler** [comment]
Hi @brianchandotcom, corrected naming as you mentioned. Thx!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/99264aa301...d75ea54fef

**Comment by brianchandotcom** [comment]
@jkappler @sandrodw3 just d75ea54fef00c4862d09aa6991cfdd70403d1806 thx.

**Pull request closed without merging**
