### PR TITLE
LPS-69358 Move language key to portal. This key will be reference by reports module in ee branch. format-source is complaining about this key.

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@leoadb can't reports console engine reference portal-workflow-lang? Instead of moving this to core?

**Comment by brianchandotcom** [comment]
@leoadb please resend if you cannot have reports reference portal-workflow-lang.

**Comment by leoadb** [comment]
@brianchandotcom It's sound strange because reports module is not inside forms-and-workflow parent folder.

cc @marcellustavares

**Comment by leoadb** [comment]
ci:reopen

**Pull request closed without merging**
