### PR TITLE
LPS-135081 DB Partition: CompanyThreadLocal.lock tests and improvements

### PR DESCRIPTION
**Pull request by achaparro**
Sent directly because I modify a SF rule and then a SF issue is shown but it is not related.

Relevant tests passed here:
https://github.com/achaparro/liferay-portal/pull/955

### CODE REVIEW

**Comment by achaparro** [comment]
ci:reopen

**Comment by achaparro** [comment]
ci:open

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4b56b7b662...238f4c4a13

**Comment by brianchandotcom** [comment]
See 238f4c4a13d6db9ea711f5d1022d725f8f901e7f

**Comment by brianchandotcom** [comment]
@achaparro see 238f4c4a13d6db9ea711f5d1022d725f8f901e7f

**Pull request closed without merging**
