### PR TITLE
LPS-76585 Updates tests to use renamed methods

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by timpak** [comment]
ci:close

**Comment by timpak** [comment]
@jbalsas 

Hi, can you look into the following SF errors? Thanks!

     [java] 1: Line starts with '0' tabs, but '3' tabs are expected: ./modules/apps/foundation/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/servlet/taglib/util/DropdownItemList.java 62 (CheckStyle:IndentationCheck) 

     [java] 7: ./modules/apps/foundation/frontend-taglib/frontend-taglib-clay-sample-web/src/main/java/com/liferay/frontend/taglib/clay/sample/web/internal/display/context/NavigationBarsDisplayContext.java expected:<....util.NavigationItem[]List;
     [java] 
     [java] /**
     [java]  * @autho...> but was:<....util.NavigationItem[;
     [java] import com.liferay.frontend.taglib.clay.servlet.taglib.util.NavigationItem]List;
     [java] 
     [java] /**
     [java]  * @autho...>

     [java] 8: ./modules/apps/foundation/frontend-taglib/frontend-taglib-clay-sample-web/src/main/java/com/liferay/frontend/taglib/clay/sample/web/internal/display/context/CardsDisplayContext.java expected:<...ib.util.DropdownItem[List;
     [java] import com.liferay.portal.kernel.security.RandomUtil;
     [java] 
     [java] import java.util.ArrayList;
     [java] import java.util.HashMap;
     [java] import java.util.List;
     [java] import java.util.Map;
     [java] 
     [java] /**
     [java]  * @author Julien Castelain
     [java]  */
     [java] public class CardsDisplayContext {
     [java] 
     [java] 	public DropdownItemList getDefaultActionItems() {
     [java] 		if (_actionItems != null) {
     [java] 			return _actionItems;
     [java] 		}
     [java] 
     [java] 		_actionItems = new DropdownItemList() {
     [java] 			{
     [java] 				add(
     [java] 					dropdownItem -> {
     [java] 						dropdownItem.setHref("#1");
     [java] 						dropdownItem.setLabel("Edit");
     [java] 						dropdownItem.setSeparator(true);
     [java] 					});
     [java] 
     [java] 				add(
     [java] 					dropdownItem -> {
     [java] 						dropdownItem.setHref("#2");
     [java] 						dropdownItem.setLabel("Save");
     [java] 					});]
     [java] 			}
     [java] 		};
     [java] 
     [java] 		return...> but was:<...ib.util.DropdownItem[;
     [java] import com.liferay.frontend.taglib.clay.servlet.taglib.util.DropdownItemList;
     [java] import com.liferay.portal.kernel.security.RandomUtil;
     [java] 
     [java] import java.util.ArrayList;
     [java] import java.util.HashMap;
     [java] import java.util.List;
     [java] import java.util.Map;
     [java] 
     [java] /**
     [java]  * @author Julien Castelain
     [java]  */
     [java] public class CardsDisplayContext {
     [java] 
     [java] 	public DropdownItemList getDefaultActionItems() {
     [java] 		if (_actionItems != null) {
     [java] 			return _actionItems;
     [java] 		}
     [java] 
     [java] 		_actionItems = new DropdownItemList() {
     [java] 			{
     [java] 				add(
     [java] 					dropdownItem -> {
     [java] 						dropdownItem.setHref("#1");
     [java] 						dropdownItem.setLabel("Edit");
     [java] 						dropdownItem.setSeparator(true);
     [java] 					});
     [java] 
     [java] 				add(
     [java] 					dropdownItem -> {
     [java] 						dropdownItem.setHref("#2");
     [java] 						dropdownItem.setLabel("Save");
     [java] 					});
     [java] ]
     [java] 			}
     [java] 		};
     [java] 
     [java] 		return...>

     [java] 9: ./modules/apps/foundation/frontend-taglib/frontend-taglib-clay-sample-web/src/main/java/com/liferay/frontend/taglib/clay/sample/web/internal/display/context/ManagementToolbarsDisplayContext.java expected:<...taglib.util.Dropdown[]ItemList;
     [java] 
     [java] import ja...> but was:<...taglib.util.Dropdown[GroupItem;
     [java] import com.liferay.frontend.taglib.clay.servlet.taglib.util.DropdownItem;
     [java] import com.liferay.frontend.taglib.clay.servlet.taglib.util.Dropdown]ItemList;
     [java] 
     [java] import ja...>

     [java] 10: ./modules/apps/foundation/frontend-taglib/frontend-taglib-clay-sample-web/src/main/java/com/liferay/frontend/taglib/clay/sample/web/internal/display/context/DropdownsDisplayContext.java expected:<...taglib.util.Dropdown[ItemList];
     [java] 
     [java] /**
     [java]  * @author Ch...> but was:<...taglib.util.Dropdown[CheckboxItem;
     [java] import com.liferay.frontend.taglib.clay.servlet.taglib.util.DropdownGroupItem;
     [java] import com.liferay.frontend.taglib.clay.servlet.taglib.util.DropdownItem;
     [java] import com.liferay.frontend.taglib.clay.servlet.taglib.util.DropdownItemList;
     [java] import com.liferay.frontend.taglib.clay.servlet.taglib.util.DropdownRadioGroupItem;
     [java] import com.liferay.frontend.taglib.clay.servlet.taglib.util.DropdownRadioItem];
     [java] 
     [java] /**
     [java]  * @author Ch...>

     [java] 11: ./modules/apps/foundation/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/servlet/taglib/util/DropdownGroupItem.java expected:<...rvlet.taglib.util;
     [java] 
     [java] []/**
     [java]  * @author Carlo...> but was:<...rvlet.taglib.util;
     [java] 
     [java] [import java.util.List;
     [java] 
     [java] ]/**
     [java]  * @author Carlo...>

     [java] 12: ./modules/apps/foundation/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/servlet/taglib/soy/ManagementToolbarTag.java expected:<....string.StringPool;
     [java] []
     [java] /**
     [java]  * @author Carl...> but was:<....string.StringPool;
     [java] [import com.liferay.portal.kernel.theme.ThemeDisplay;
     [java] import com.liferay.portal.kernel.util.Validator;
     [java] import com.liferay.portal.kernel.util.WebKeys;
     [java] 
     [java] import java.util.Map;
     [java] ]
     [java] /**
     [java]  * @author Carl...>

     [java] 13: ./modules/apps/foundation/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/servlet/taglib/util/DropdownItemList.java expected:<...ownRadioGroupItem =
     [java] [			]new DropdownRadioGro...> but was:<...ownRadioGroupItem =
     [java] [            ]new DropdownRadioGro...>

**Comment by jbalsas** [comment]
Resent -> https://github.com/brianchandotcom/liferay-portal/pull/55567

**Pull request closed without merging**
