### PR TITLE
LPS-109256 Build lang

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/12d6d50a3c...5fc9a133a0

**Comment by brianchandotcom** [comment]
@adolfopa @cgoncas see 23098613cd68f4d041bc784520dfb5e1d6f357af and 5cd790a6c2956b13b3d57be3cf580824756b72ec

Hola!

**Pull request closed without merging**
