### PR TITLE
LPS-105959

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@brianchandotcom, we have a lot of ugly `if` statements in `gradle`.
I'll work on standardizing.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fc220e5c12...04cbe12d74

**Comment by gamerson** [comment]
hey @hhuijser  are you talking about the `#if` velocity ones in  the build.gradle?

**Comment by gamerson** [comment]
Regardless, please consult me or lawrence before making any changes to build.gradle, every file is very sensitve to the velocity scripts

**Pull request closed without merging**
