### PR TITLE
LPS-126342, LPS-126347 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-126342
https://issues.liferay.com/browse/LPS-126347

This is only for master.

@david-gutierrez-mesa
@alexcandidos

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure case is unrelated to changes in PR.
See https://github.com/liferay-echo/liferay-portal/pull/3654
✔️ ci:test:stable - 9 out of 9 jobs passed
❌ ci:test:relevant - 21 out of 25 jobs passed in 1 hour 57 minutes

**Comment by brianchandotcom** [comment]
@juliaduartelira @pedro-michel fyi

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8c9c630437...89ccd89033

**Pull request closed without merging**
