### PR TITLE
LRCI-3973 Add playwright batch support for additional test suites

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://liferay.atlassian.net/browse/LRCI-3973
https://liferay.atlassian.net/browse/LRCI-3974

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:reopen

**Comment by kenjiheigel** [comment]
Tested here:
https://github.com/kenjiheigel/liferay-portal/pull/1522#issuecomment-1861243715 (stable, unrelated failure)
https://github.com/kenjiheigel/liferay-portal/pull/1522#issuecomment-1861013726 (playwright suite)
https://github.com/kenjiheigel/liferay-portal/pull/1522#issuecomment-1860892025 (sf)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8adf0e5f55...7cc4338b36

**Comment by brianchandotcom** [comment]
@kenjiheigel see 7cc4338b3683e6d92371174d306f43d21c8c4406

**Pull request closed without merging**
