### PR TITLE
LPS-68593

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-68593.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:reopen

**Comment by jonmak08** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@jonmak08 @dustinryerson see my SF in a4a0d60d58d0fe697d7c767aa2b2fc7fda66a9c2 and 8600a3775edaefdda3b384b2d4fe5ae6c9aad39b

**Pull request closed without merging**
