### PR TITLE
LPS-71093 get friendly URL servlet as a service using service tracker

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8e72418a9a...ed3767eec2

**Comment by brianchandotcom** [comment]
@pavel-savinov @migue I merged this with minor changes in upstream. Please review.

Also, do we have to export FriendlyURLServlet? I'd rather keep it all private and internal if possible. I don't see why anyone would need to extend this. Is it for the test?

Thx.

**Pull request closed without merging**
