### PR TITLE
LPS-94581 SF

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by jpince** [comment]
ci:test @vicnate5 @brianchiu please keep an eye on this pull, makes changes to portal-impl

**Comment by ealonso** [comment]
ci:reopen

**Comment by vicnate5** [comment]
TCK failures are not related. going to ignore the continuously failing TCK tests for now until we can address them.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6d0499ac32...a2ad97da58

**Comment by brianchandotcom** [comment]
@jrao @ealonso see a2ad97da58eca3e7d89dcc15e20fc7e01e311643

**Pull request closed without merging**
