### PR TITLE
LPS-72983 Unable to delete a virtual instance that contains an user group site created with a site template

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by drewbrokke** [comment]
Good additions, @pei-jung 👍

**Comment by brianchandotcom** [comment]
@shuyangzhou something is still wrong with CI?

**Comment by shuyangzhou** [comment]
@brianchandotcom yes, it has nothing to do with @tomwang2011 's change, it should not be reverted. It is actually very complex issues go back months ago, when you get into office, we need to talk about, this is very ridiculous.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/837196de5c...e4668741a1

**Pull request closed without merging**
