### PR TITLE
LPS-126391 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-126391

This is only for master.

@david-gutierrez-mesa

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure case is unrelated to changes in PR.
See https://github.com/liferay-echo/liferay-portal/pull/3582
✔️ ci:test:stable - 9 out of 9 jobs passed
❌ ci:test:relevant - 21 out of 26 jobs passed in 1 hour 46 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8a59ea78c2...37225c438a

**Comment by brianchandotcom** [comment]
@gleicelisbino  make sure your team understands the changes made by others.

**Comment by gleicelisbino** [comment]
Thank you very much, @brianchandotcom. Let's do this today!

**Pull request closed without merging**
