### PR TITLE
COMMERCE-11180 Configuration of generic payment methods

### PR DESCRIPTION
**Pull request by luca-pellizzon**
@brianchandotcom 
constants changed to TYPE_FUNCTION_****
let me know about TYPE_INTERNAL_****
as said this is about osgi payment integrations

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e5edf8f3fd...7e55028a8d

**Comment by brianchandotcom** [comment]
@luca-pellizzon see changes in my origin. Also, I noticed that there are new columns you added to CommercePaymentEntry that are not even used (like commerceChannelId)?

**Comment by luca-pellizzon** [comment]
@brianchandotcom thanks.
Regarding `CommercePaymentEntry`, there are fields that will be used in osgi `CommercePaymentIntegration` implementations, but regarding for example commerceChannelId it is currently used by 
`FunctionCommercePaymentIntegration.java` like so:
```
CommerceChannel commerceChannel =
			_commerceChannelLocalService.getCommerceChannel(
commercePaymentEntry.getCommerceChannelId());
```

**Pull request closed without merging**
