### PR TITLE
LPS-108328 Revert Allow hotfix patterns

### PR DESCRIPTION
**Pull request by javiergamarra**
This reverts commit 9c332ad5658ca64aa28c6d5c471ec6f867432419.

/@holatuwol reverting (following BChan advice) because it breaks all API tests (bnd https://github.com/brianchandotcom/liferay-portal/blob/master/modules/apps/headless/headless-admin-user/headless-admin-user-test/bnd.bnd can't find client jar). Sorry :(

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@holatuwol please resend.

**Comment by brianchandotcom** [comment]
@petershin fyi

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9acaa5ad2d...e75ccbcf8d

**Comment by brianchandotcom** [comment]
@nhpatt can you give @holatuwol a link to the broken test results so he knows what he needs to fix? Thx.

**Comment by nhpatt** [comment]
Sure, @holatuwol some failures here: https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(7.2.x)/AXIS_VARIABLE=13,label_exp=!master/10373/consoleFull and all the tickets in JIRA here: https://issues.liferay.com/browse/LPS-108544

**Pull request closed without merging**
