### PR TITLE
Lps 63617

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @mhan810, @tinatian and @dantewang actually finished all upgrade/verify processes logging changes, but I refactor it a bit, this pull only contains the high priority ones. They will rebase and resend the rest later.

@tinatian and @dantewang please wait until @brianchandotcom merges this pull, all apply the same pattern to the rest changes you did and resend to me, thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@shuyangzhou can you resend and make it simply

try (LoggingTimer loggingTimer = new LoggingTimer()) {

if you don't pass in a method, get the calling method and log that automatically?

Thx. Please resend.

**Comment by brianchandotcom** [comment]
@shuyangzhou It should print out

com.liferay.xyz.VerifyXyz#blahBlah(java.lang.String)

Just like how we would Javadoc it. Thx.

**Comment by brianchiu** [comment]
@vicnate5
Can you look at these? All flaky tests that are BP related.

**Comment by shuyangzhou** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/36608

**Pull request closed without merging**
