### PR TITLE
LPS-65698 Oracle understand the = 160 as a number and throws an error

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8d3a69c7f4...dc70e04fc7

**Comment by brianchandotcom** [comment]
@jkappler wrapping it with 2 single quotes will do

See dc70e04fc795dd2ad2099557f077dd218a95b96e for my changes.

Thx.

**Comment by brianchandotcom** [comment]
@jhendley PR tester should fail without this pull (but it passed)... please fix. Thx.

**Pull request closed without merging**
