### PR TITLE
LPS-61857 Remote File Disclosure using PHPPortlet

### PR DESCRIPTION
**Pull request by topolik**
https://issues.liferay.com/browse/LPS-61857

### CODE REVIEW

**Comment by migue** [comment]
We are dropping the PHP support guys, FYI

**Comment by topolik** [comment]
Thanks Migue, we need to fix it in older versions though.

Are you going to remove PHPPortlet class?

-- tom +

**Comment by migue** [comment]
I think we'll delete it, yes!

On 3 March 2016 at 13:53, Tomáš Polešovský <notifications@github.com> wrote:

> Thanks Migue, we need to fix it in older versions though.
>
> Are you going to remove PHPPortlet class?
>
> -- tom +
>
> On Thu, Mar 3, 2016 at 1:51 PM, Miguel Ángel Pastor Olivar <
> notifications@github.com> wrote:
>
> > We are dropping the PHP support guys, FYI
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/brianchandotcom/liferay-portal/pull/37023#issuecomment-191750269
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/37023#issuecomment-191750749>
> .
>



-- 
Un saludo,

Migue

http://migue.github.io

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/592bdb7d02...2c7f6ad314

**Pull request closed without merging**
