### PR TITLE
LPS-79709 Rename BND key Liferay-Export-JS-Submodules to Liferay-JS-Submodules-Export

### PR DESCRIPTION
**Pull request by izaera**
Hi @brianchandotcom :

This is part 1 of https://github.com/brianchandotcom/liferay-portal/pull/58739#issuecomment-391146446

/CC @jbalsas

### CODE REVIEW

**Comment by izaera** [comment]
ci:test

**Comment by izaera** [comment]
The SF test seems to be an infrastructure failure.

**Comment by jpince** [comment]
@michaelhashimoto @kenjiheigel @yichenroy SF failure
`/opt/dev/projects/github/liferay-jenkins-ee/commands/build-test-portal-source-format.xml:16: Sourced file: inline evaluation of: `` 			 				import com.liferay.jenkins.results.parser.AntUtil; 				import com.lifer . . . '' : Undefined argument: localTempPrivateBranch  : at Line: 40 : in file: inline evaluation of: `` 			 				import com.liferay.jenkins.results.parser.AntUtil; 				import com.lifer . . . '' : ( localTempPrivateBranch )`

**Comment by jpince** [comment]
@izaera SF failure is because when any change is made in SF (see https://github.com/brianchandotcom/liferay-portal/pull/58898/commits/6a02328080d525e200bfac9c594caa04f6f519e7#diff-59303bbd9911ecbd09dcf01218299bc8), CI will rebuild the module and run a full SF test on master and master-private. This is so when Hugo and Peter make a change to the actual SF code, they can test their changes against all of portal.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
