### PR TITLE
LPS-79679

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Fix for violations in private: https://github.com/brianchandotcom/liferay-portal-ee/pull/20458

**Comment by hhuijser** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by jpince** [comment]
@hhuijser reverted https://github.com/liferay/liferay-portal/commit/af428f9  error is in the stacktrace above

**Comment by jpince** [comment]
@petershin I only reverted the commit causing the compile error, can you please reconcile the SF failure (patch SF? fix the error? not sure what the right approach would be)
See log with all errors in https://test-1-17.liferay.com/job/test-portal-acceptance-upstream-batch(master)/AXIS_VARIABLE=0,label_exp=!master/22989/console

**Comment by petershin** [comment]
@jpince - Sent a patch to Brian: https://github.com/brianchandotcom/liferay-portal/pull/60148

**Pull request closed without merging**
