### PR TITLE
LPS-110369 Remove extra input element

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hey @austinchiang,

There are some Poshi failures that should be easy to fix. Can you fix them when you have some time? 

I think this PR can go forward anyway but feel free to close it if you prefer so.

Thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b453bd4161...633ff0bfce

**Comment by brianchandotcom** [comment]
@ambrinchaudhary 72bc8a6cca0027ec88d34fcdcb79a1d29d30e972

**Comment by brianchandotcom** [comment]
@4lejandrito once relevant is enforced (shortly after stable next week with ci forward). Then these poshi issues will have to go through QA first.

**Comment by austinchiang** [comment]
They will be fixed in https://issues.liferay.com/browse/LPS-110014

**Pull request closed without merging**
