### PR TITLE
LPS-114024 Require cleanup to be enabled manually

### PR DESCRIPTION
**Pull request by vicnate5**
Upgrade tomcat version to latest. Passed CI acceptance testing (see https://github.com/brianchandotcom/liferay-portal/pull/93524#issue-476448056).
CC @gaborlovasdotcom @jpince @petershin @shuyangzhou @lipusz

Will send backports after we merge to master.

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:reopen

**Comment by lipusz** [comment]
Thank you, @vicnate5!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7454918f51...4a9dbcf71a

**Comment by brianchandotcom** [comment]
@vicnate5 I reverted

```
LPS-114024 Require cleanup to be enabled manually
```

If we don't want it to do that, just rip out the property and functionality. It'll end up being dead code if we don't have it on by default.

**Pull request closed without merging**
