### PR TITLE
SYNC-1360

### PR DESCRIPTION
**Pull request by mikemanyoung**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by mikemanyoung** [comment]
No errors on ant format-source, not sure what's wrong.

**Comment by shinnlok** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f1f05e22ea...f22e178650

**Pull request closed without merging**
