### PR TITLE
LPS-59265 Revert 83789997636bc048412da90e4e069d609b7c91fc (LPS-52772) because it makes the previous test fail

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey @yuhai @rotty3000 and @daledotshan

This pull reverts the changes done in https://github.com/liferay/liferay-portal/commit/83789997636bc048412da90e4e069d609b7c91fc because it creates a regression described in https://issues.liferay.com/browse/LPS-59265

I have created a test (https://github.com/sergiogonzalez/liferay-portal/commit/0d3b0a8e0258ee4ea6d142453e516b0aebb461d2) to prove that it creates the regression and it should also help you to do the right fix for LPS-52772.

Thanks!

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @yuhai @rotty3000 @daledotshan @jcampoy

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8d67d65d54...ab496e4423

**Comment by brianchandotcom** [comment]
@ZoltanTakacs @yuhai @daledotshan this was backported in ee-6.2.x We need to remove it. It causes a regression.

**Comment by ZoltanTakacs** [comment]
Hey guys,

Can we create a new ticket for the original issue instead of reopening it? We've already released it in a fix-pack and it's really hard to track the reopened LPSes which need to be backported again (I mean the new commits).

/cc @yuhai @daledotshan @sergiogonzalez

**Comment by jcampoy** [comment]
Ok @ZoltanTakacs , I am going to create a new one.

**Comment by jcampoy** [comment]
@ZoltanTakacs , the issue is already open, I think we can use the same issue but create a new LPE with the new fix, or may be create a new one as duplicate. Could you do that? I don't know which is the best way for tracking this.
Thanks!

**Comment by ZoltanTakacs** [comment]
@jcampoy I went ahead and created the ticket for the original issue here: [LPS-60800](https://issues.liferay.com/browse/LPS-60800) I left a note on the tickets about the reason.

Thank you,

**Pull request closed without merging**
