### PR TITLE
LPS-133634 | Master

### PR DESCRIPTION
**Pull request by Hanlf**
Hi @brianchandotcom 
resending this pull directly to you since after a few retries we confirmed this pull is not related to any of the failing tests in https://github.com/liferay-lima/liferay-portal/pull/1956, thanks!

https://issues.liferay.com/browse/LPS-133634

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/97b0832624...70917c81bd

**Comment by brianchandotcom** [comment]
@Hanlf see 70917c81bd23c55a48922444ff1ce9a5e098e64f thx

**Comment by brianchandotcom** [comment]
@AliciaGarciaGarcia this was a very good pull, just 70917c81bd23c55a48922444ff1ce9a5e098e64f

**Pull request closed without merging**
