### PR TITLE
Lps 75081

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5e5b10702c...e1c00682ba

**Comment by brianchandotcom** [comment]
@mbowerman beautifully done.. nice job.

**Comment by jpince** [comment]
@shuyangzhou @mbowerman @Preston-Crary fyi, https://github.com/liferay/liferay-portal/commit/3070c5c0803bcc725369c4fc637b79bd8c73aa59. Maybe caused by a bad rebase? (see https://github.com/brianchandotcom/liferay-portal/pull/55763#issuecomment-369350008)

**Comment by shuyangzhou** [comment]
@jpince Yeah, bad rebase, thanks @pavel-savinov !

**Comment by jpince** [comment]
@shuyangzhou can you please backport Pavel's fix to 7.0.x?

**Comment by Preston-Crary** [comment]
@jpince it's already backported to 7.0.x.

**Pull request closed without merging**
