### PR TITLE
Lps 63617

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c461116c4c...508f87261a

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
@brianchandotcom - This is likely due to fact that we updated FF during this time, i re-ran this pull to see if it still occurs.

**Comment by brianchandotcom** [comment]
@shuyangzhou please see my changes in 76364a6bcf38cdbf4ee127030940bbbc7ed33283 and 6727107f4dc78ca578336d30f3b081c7caa56faa

Thx

**Pull request closed without merging**
