### PR TITLE
LPS-100540 No needed

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
We either go with getXyzModel or getModelByXyzId in *ServiceImpl files. But we usually don't mix both.

getClassedModelFragmentEntryLinksCount already exists and so the new method getFragmentEntryLinksByFragmentEntryId doesn't fit. Please resend.

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Just started reviewing :)

**Pull request closed without merging**
