### PR TITLE
LPS-98032 Restructure JSP to avoid special cases

### PR DESCRIPTION
**Pull request by wincent**
As requested [here](https://github.com/brianchandotcom/liferay-portal/pull/79731#issuecomment-543483079), we remove the special cases by restructuring the JSP.

There were two files that we were excluding. I'll explain the simplest one as an example:

```jsp
{
	id: '<portlet:namespace />editAsset',
	portletAjaxable: true,

	<c:choose>
		<c:when test="<%= redirect != null %>">
			redirect: '<%= HtmlUtil.escapeJS(redirect) %>'
		</c:when>
		<c:otherwise>
			refresh: '<%= portletDisplay.getId() %>'
		</c:otherwise>
	</c:choose>
}
```

The problem there is that when the tags are temporarily removed to turn it into JS for formatting, you're left with an invalid object (note the lack of trailing commas):

```jsp
{
	id: '<portlet:namespace />editAsset',
	portletAjaxable: true,
	redirect: '<%= HtmlUtil.escapeJS(redirect) %>'
	refresh: '<%= portletDisplay.getId() %>'
}
```

We can't just put a trailing comma after both properties because IE 11 will crash if the last key-value pair has a comma.

They can be rewritten — with a temporary variable — like this:

```jsp
var data = {
	id: '<portlet:namespace />editAsset',
	portletAjaxable: true
};

<c:choose>
	<c:when test="<%= redirect != null %>">
		data.redirect = '<%= HtmlUtil.escapeJS(redirect) %>';
	</c:when>
	<c:otherwise>
		data.refresh = '<%= portletDisplay.getId() %>';
	</c:otherwise>
</c:choose>
```

which has the same behavior at runtime, but without the ~downside~ upside of being ~invalid~ valid (😂) JS once the tags are stripped. The other example is much more complex, so I'll let the diff speak for itself: it is basically doing the same thing though (creating a config object and mutating it rather than trying to do it all inline).

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:test:relevant

**Comment by wincent** [comment]
@john-co: can you please help us by analyzing those test results?

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
I'll want to manually verify ExportImport#ExportImportValidation from the compare:

https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=839186136&testrayRunIdA=839179453&statusB=2

The other test failures look unrelated based on known issues: 
- verify alert https://issues.liferay.com/browse/LRCI-683
- Smoke test https://issues.liferay.com/browse/LRQA-52723

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark:

**Comment by wincent** [comment]
Thanks a bunch @john-co!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bc5ffdbb50...727bc9eaaf

**Comment by brianchandotcom** [comment]
@wincent yup, we should always just refactor code this way. Thank you!

**Pull request closed without merging**
