### PR TITLE
LPS-96724 SF

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @brianchandotcom!

I'm resending this as is from https://github.com/brianchandotcom/liferay-portal/pull/76505 where you mentioned:

> Whenever you add new js docs with real text, add the @review so the docs team knows to update them. Please resend.

We're simply porting this over from our external metal repos, so these docs had already been reviewed over there and shouldn't need an additional pass. 

I can resend with the `@review` tag if you still think it's necessary to double-check those.

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @john-co, would you mind analyzing the test failures here to confirm they're unrelated, please?

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Hi @jbalsas, 
There's a bunch of modules-compile failures that are unique to this pull and not found in upstream or the pulls that were sent around the same time. The full console log can be found here: https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/68508/AXIS_VARIABLE=0,label_exp=!master/consoleFull

Here's a list of the module failures:
1.
```     [exec] > Task :apps:frontend-js:frontend-js-react-web:npmRunBuild FAILED
     [exec] { Error: Cannot find module 'liferay-npm-bundler-plugin-namespace-packages' from '/opt/dev/projects/github/liferay-portal/modules/node_modules/liferay-npm-bundler-preset-standard'
     [exec]     at Function.module.exports [as sync] (/opt/dev/projects/github/liferay-portal/modules/node_modules/resolve/lib/sync.js:71:15)
     [exec]     at configRequire (/opt/dev/projects/github/liferay-portal/modules/node_modules/liferay-npm-bundler/lib/config/internal/util.js:39:37)
     [exec]     at /opt/dev/projects/github/liferay-portal/modules/node_modules/liferay-npm-bundler/lib/config/internal/bundler.js:118:46
     [exec]     at Array.map (<anonymous>)
     [exec]     at instantiatePlugins (/opt/dev/projects/github/liferay-portal/modules/node_modules/liferay-npm-bundler/lib/config/internal/bundler.js:110:21)
     [exec]     at Object.getPlugins (/opt/dev/projects/github/liferay-portal/modules/node_modules/liferay-npm-bundler/lib/config/internal/bundler.js:85:9)
     [exec]     at /opt/dev/projects/github/liferay-portal/modules/node_modules/liferay-npm-bundler/lib/index.js:310:56
     [exec]     at new Promise (<anonymous>)
     [exec]     at processPackage (/opt/dev/projects/github/liferay-portal/modules/node_modules/liferay-npm-bundler/lib/index.js:308:9)
     [exec]     at /opt/dev/projects/github/liferay-portal/modules/node_modules/liferay-npm-bundler/lib/index.js:235:12 code: 'MODULE_NOT_FOUND' }
     [exec] Command /opt/dev/projects/github/liferay-portal/modules/node_modules/liferay-npm-scripts/node_modules/.bin/liferay-npm-bundler exited with code 1
```

2.
```     [exec] > Task :apps:frontend-taglib:frontend-taglib:npmRunBuild FAILED
     [exec] yarn run v1.13.0
     [exec] warning package.json: No license field
     [exec] $ liferay-npm-scripts build
     [exec] /bin/sh: liferay-npm-scripts: command not found
     [exec] error Command failed with exit code 127.
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] 
```
3. :apps:frontend-js:frontend-js-metal-web:npmRunBuild
```
     [exec] > Task :apps:frontend-js:frontend-js-metal-web:npmRunBuild FAILED
     [exec] { Error: Cannot find module 'liferay-npm-bundler-plugin-namespace-packages' from '/opt/dev/projects/github/liferay-portal/modules/node_modules/liferay-npm-bundler-preset-standard'
     [exec]     at Function.module.exports [as sync] (/opt/dev/projects/github/liferay-portal/modules/node_modules/resolve/lib/sync.js:71:15)
     [exec]     at configRequire (/opt/dev/projects/github/liferay-portal/modules/node_modules/liferay-npm-bundler/lib/config/internal/util.js:39:37)
     [exec]     at /opt/dev/projects/github/liferay-portal/modules/node_modules/liferay-npm-bundler/lib/config/internal/bundler.js:118:46
     [exec]     at Array.map (<anonymous>)
     [exec]     at instantiatePlugins (/opt/dev/projects/github/liferay-portal/modules/node_modules/liferay-npm-bundler/lib/config/internal/bundler.js:110:21)
     [exec]     at Object.getPlugins (/opt/dev/projects/github/liferay-portal/modules/node_modules/liferay-npm-bundler/lib/config/internal/bundler.js:85:9)
     [exec]     at /opt/dev/projects/github/liferay-portal/modules/node_modules/liferay-npm-bundler/lib/index.js:310:56
     [exec]     at new Promise (<anonymous>)
     [exec]     at processPackage (/opt/dev/projects/github/liferay-portal/modules/node_modules/liferay-npm-bundler/lib/index.js:308:9)
     [exec]     at /opt/dev/projects/github/liferay-portal/modules/node_modules/liferay-npm-bundler/lib/index.js:235:12 code: 'MODULE_NOT_FOUND' }
     [exec] Command /opt/dev/projects/github/liferay-portal/modules/node_modules/liferay-npm-scripts/node_modules/.bin/liferay-npm-bundler exited with code 1
     [exec] error Command failed with exit code 1.
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
4. 
```
     [exec] Execution failed for task ':apps:frontend-js:frontend-js-lodash-web:jar'.
     [exec] > Bundle com.liferay.frontend.js.lodash.web-3.0.0.jar has errors
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:frontend-js:frontend-js-lodash-web:jar'.
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
     [exec] 	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
     [exec] 	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
     [exec] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
```
5.
``` 
     [exec] > Task :apps:frontend-js:frontend-js-spa-web:npmRunBuild FAILED
     [exec] yarn run v1.13.0
     [exec] warning package.json: No license field
     [exec] $ liferay-npm-scripts build
     [exec] /bin/sh: liferay-npm-scripts: command not found
     [exec] error Command failed with exit code 127.
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command
```
6.
```
     [exec] > Task :apps:frontend-taglib:frontend-taglib-clay:npmRunBuild
     [exec] [BABEL] Note: The code generator has deoptimised the styling of "/opt/dev/projects/github/liferay-portal/modules/apps/frontend-taglib/frontend-taglib-clay/classes/META-INF/resources/node_modules/d3@5.9.2/dist/d3.js" as it exceeds the max of "500KB".
     [exec] Babel failed processing d3-array@1.2.4/rollup.config.js: it will be copied verbatim (see report file for more info)
     [exec] Babel failed processing d3-axis@1.0.12/rollup.config.js: it will be copied verbatim (see report file for more info)
     [exec] Babel failed processing d3-brush@1.0.6/rollup.config.js: it will be copied verbatim (see report file for more info)
     [exec] Babel failed processing d3-dispatch@1.0.5/rollup.config.js: it will be copied verbatim (see report file for more info)
     [exec] Babel failed processing d3-drag@1.2.3/rollup.config.js: it will be copied verbatim (see report file for more info)
     [exec] Babel failed processing d3-selection@1.4.0/rollup.config.js: it will be copied verbatim (see report file for more info)
     [exec] Babel failed processing d3-interpolate@1.3.2/rollup.config.js: it will be copied verbatim (see report file for more info)
     [exec] Babel failed processing d3-color@1.2.3/rollup.config.js: it will be copied verbatim (see report file for more info)
     [exec] { Error: Cannot find module 'liferay-npm-bundler-plugin-namespace-packages' from '/opt/dev/projects/github/liferay-portal/modules/node_modules/liferay-npm-bundler-preset-standard'
     [exec]     at Function.module.exports [as sync] (/opt/dev/projects/github/liferay-portal/modules/node_modules/resolve/lib/sync.js:71:15)
     [exec]     at configRequire (/opt/dev/projects/github/liferay-portal/modules/node_modules/liferay-npm-bundler/lib/config/internal/util.js:39:37)
     [exec]     at /opt/dev/projects/github/liferay-portal/modules/node_modules/liferay-npm-bundler/lib/config/internal/bundler.js:118:46
     [exec]     at Array.map (<anonymous>)
     [exec]     at instantiatePlugins (/opt/dev/projects/github/liferay-portal/modules/node_modules/liferay-npm-bundler/lib/config/internal/bundler.js:110:21)
     [exec]     at Object.getPlugins (/opt/dev/projects/github/liferay-portal/modules/node_modules/liferay-npm-bundler/lib/config/internal/bundler.js:85:9)
     [exec]     at /opt/dev/projects/github/liferay-portal/modules/node_modules/liferay-npm-bundler/lib/index.js:310:56
     [exec]     at new Promise (<anonymous>)
     [exec]     at processPackage (/opt/dev/projects/github/liferay-portal/modules/node_modules/liferay-npm-bundler/lib/index.js:308:9)
     [exec]     at /opt/dev/projects/github/liferay-portal/modules/node_modules/liferay-npm-bundler/lib/index.js:235:12 code: 'MODULE_NOT_FOUND' }
     [exec] Command /opt/dev/projects/github/liferay-portal/modules/node_modules/liferay-npm-scripts/node_modules/.bin/liferay-npm-bundler exited with code 1
     [exec] error Command failed with exit code 1.
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
7.  :apps:frontend-js:frontend-js-web:jsdoc
https://gist.github.com/john-co/d91ba02fcd13fc1cafa2f389b629b4c5


The failures for functional test batches are unrelated. The unique functional test failure is a flaky test.

https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=713792358&testrayRunIdA=714021509&statusB=2

**Comment by john-co** [comment]
ci:close

**Comment by john-co** [comment]
Closing. The failures in modules-compile are also observed in #76505.

cc/ @carloslancha @jbalsas

**Comment by jbalsas** [comment]
Hey @john-co, I don't see how those errors can be related... I've rebuilt again from scratch and everything works out just fine... maybe we had some corrupted caches or something on the CI side?

Trying again at https://github.com/brianchandotcom/liferay-portal/pull/76677

**Pull request closed without merging**
