### PR TITLE
LPS-59232 split card taglib into 2 taglibs (and apply it to journal)

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
@sergiogonzalez we have adapted the taglib in your apps too

**Comment by juliocamarero** [comment]
@natecavanaugh we have finally split cards into 2 taglibs since the behavior was too different between vertical and horizontal and not only the markup but the attributes were too different

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cc3e424f2e...d4e432ab6b

**Comment by brianchandotcom** [comment]
@carloslancha please see my changes in upstream.

**Pull request closed without merging**
