### PR TITLE
LPD-33439 Display template page implementation for orders

### PR DESCRIPTION
**Pull request by alessiorendina**
Hi @brianchandotcom 

I made the requested changes asked here https://github.com/brianchandotcom/liferay-portal/pull/153585

https://liferay.atlassian.net/browse/LPD-33439

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@alessiorendina Do you know why everything else is one char?

```
	public static final String URL_SEPARATOR_BLOGS_ENTRY = "/b/";

	public static final String URL_SEPARATOR_CALENDAR_BOOKING = "/h/";

	public static final String URL_SEPARATOR_COMMERCE_ORDER = "/order/";

	public static final String URL_SEPARATOR_CUSTOM_ASSET = "/e/";

	public static final String URL_SEPARATOR_FILE_ENTRY = "/d/";

	public static final String URL_SEPARATOR_JOURNAL_ARTICLE = "/w/";

	public static final String URL_SEPARATOR_KNOWLEDGE_BASE_ARTICLE = "/k/";

	public static final String URL_SEPARATOR_OBJECT_ENTRY = "/l/";
```

It feels very strange to break out to a new pattern.

**Comment by alessiorendina** [comment]
ci:reopen

**Comment by alessiorendina** [comment]
After a conversation on Slack, I reopened this one, thank you!

**Comment by brianchandotcom** [comment]
@alessiorendina hey, this is still in the wrong package CommerceOrderAssetDisplayPageFriendlyURLResolver

**Comment by alessiorendina** [comment]
@brianchandotcom I checked the other AssetDisplayPageFriendlyURLResolver and they are in the `*internal.asset.display.contributor.portlet` package

**Pull request closed without merging**
