### PR TITLE
master-lps-65811

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LPS-65811

@brianchandotcom 
This includes the fixes from https://issues.liferay.com/browse/LPS-65647 (https://github.com/brianchandotcom/liferay-portal/pull/40066) because they are needed for LPS-65811.

Anthony Chu tested it and it passed manually.

CC @juliocamarero @danielkocsis

### CODE REVIEW

**Comment by jpince** [comment]
@brianchandotcom did you mean to merge this?

**Comment by danielkocsis** [comment]
@jpince I have reviewed this change in the meantime and sent a new pull to @brianchandotcom (https://github.com/brianchandotcom/liferay-portal/pull/40119) 

Please close this pull request. My change contains a new test and an additional fix.

**Comment by jkappler** [comment]
@danielkocsis, we cannot close this PR. It contains changes that fix LPS-65647.

**Comment by danielkocsis** [comment]
No, it contains the fix for LPS-65811 only. So it is enough to remove (https://github.com/brianchandotcom/liferay-portal/pull/40116/commits/c3d2c083176c68c8bb60d3acd1e881c485e0fee3) commit from here.

**Comment by jkappler** [comment]
@brianchiu, I agree with @danielkocsis, this PR should address only one issue (fixes for LPS-65647), and his PR will take care of LPS-65811. So it is enough to remove c3d2c083176c68c8bb60d3acd1e881c485e0fee3 commit from here.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ade88b6847...fd584a2495

**Pull request closed without merging**
