### PR TITLE
LPS-74241 NPM package infrastructure does not work when isomorphic bundles are deployed

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:reopen

**Comment by izaera** [comment]
CI failed source format tests, but it looks like the problem is in another place of the portal (not the projects modified by this PR)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a574389206...9d5cf2cde1

**Comment by brianchandotcom** [comment]
Thx @izaera I added some more comments to your commit message so we know what caused it, and I linked the 2 tickets in the LPS.

See a4e1423ce773fe02497dc3791323a920d83f8cf3

**Pull request closed without merging**
