### PR TITLE
LRQA-40155 Enabled the TCK test class groups to account for Portal TCK 3.0

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-40155

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
@brianchandotcom - If this looks okay, can you do a new release with for these changes? Thanks!

**Comment by brianchandotcom** [comment]
@pyoo47 published...

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9019ac91b9...f48a3e29b5

**Pull request closed without merging**
