### PR TITLE
LPS-71378 Update build.gradle

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:retest

**Comment by leoadb** [comment]
@vicnate5 So weird. This doesn't break locally. :(

**Comment by vicnate5** [comment]
@leoadb I was able to reproduce the unit test failures

https://gist.github.com/vicnate5/66c2aef457e6a3d986c192a0949741c0

**Comment by leoadb** [comment]
@vicnate5 I got it. My fault! I've found the fix. Thanks!

**Pull request closed without merging**
