### PR TITLE
LPS-58603 Inconsistency in Layout Type Controller

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
CC: @mdelapenya, @epgarcia

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/54a66c9658...d95d2510af

**Comment by brianchandotcom** [comment]
@mdelapenya @jkappler please see my changes in upstream. There was one "bad" test. Thx.

**Comment by mdelapenya** [comment]
Hey @brianchandotcom, are you sure the test was wrong?
https://github.com/brianchandotcom/liferay-portal/compare/54a66c9658...d95d2510af#diff-1efa9a898c15d9ab229e5f65ee273430R187

The method verifies that calling isTypePortlet() with _type values different than portlet type, return false.

Now it verifies the call to isTypePanel is false, which is already tested in testIsTypePanelReturnsFalse() method.

**Pull request closed without merging**
