### PR TITLE
LPS-56422 After talking to frontend we won't return values for this types because they will be populated from the frontend side

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @robertoDiaz @ambrinchaudhary

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Hey @robertoDiaz 

Can you resend, first:

```
ResourceBundle resourceBundle = ResourceBundle.getBundle("content.Language", locale)
```

Remove all of those from modules. Let's add it to liferay-theme:defineObjects

If a module has content.Language, then we will implicity set "resourceBundle" as an object. We have it in too many places now.

Thx.

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
