### PR TITLE
LPS-62638 Move Add Button to the right side of the control menu

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pyoo47 what's up with these Jenkins failures?

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8844cc36bc...a4f0fb3d85

**Pull request closed without merging**
