### PR TITLE
LPS-143536 Add ObjectRelationship

### PR DESCRIPTION
**Pull request by joseabelenda**

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b1447d1cb2...0dc0ff84bf

**Comment by brianchandotcom** [comment]
@joseabelenda @gleicelisbino see changes in my origin -a bunch of tiny ones. Thx.

**Comment by gleicelisbino** [comment]
Okay.Thank you! @brianchandotcom

**Pull request closed without merging**
