### PR TITLE
LPS-84119

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
baseline not related

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/aad06b3751...0b44e1b3b2

**Comment by brianchandotcom** [comment]
@hhuijser 

	modified:   apps/blogs/blogs-web/src/main/java/com/liferay/blogs/web/internal/asset/model/BlogsEntryAssetRenderer.java
	modified:   apps/document-library/document-library-web/src/main/java/com/liferay/document/library/web/internal/info/display/contributor/DLFileEntryInfoDisplayContributor.java

Those 2 files had conflicts. Can you send me a pull to 7.2.x (I cherry picked the rest)

**Pull request closed without merging**
