### PR TITLE
LPS-74082 SF

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:retest

**Comment by brunobasto** [comment]
ci:retest

**Comment by jpince** [comment]
ci:stop

**Comment by jpince** [comment]
@brunobasto this pull is fine, the failures are unrelated

**Comment by brianchandotcom** [comment]
@shuyangzhou lpkg error is random

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a9e9cb439c...0eac48e717

**Comment by brianchandotcom** [comment]
@brunobasto please see my changes in upstream, specifically 303279bb93188196e8abe79ff78116499d4b7e6b

Can you backport too? Thx.

**Comment by brunobasto** [comment]
Backport sent: https://github.com/liferay/liferay-portal-ee/pull/2071

**Pull request closed without merging**
