### PR TITLE
LPS-75853 | master

### PR DESCRIPTION
**Pull request by sergiogonzalez**
https://issues.liferay.com/browse/LPS-75853

### CODE REVIEW

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
@sergiogonzalez error is related to your commit merged yesterday [c86f52f](https://github.com/liferay/liferay-portal/commit/c86f52f2e4ecd8325a377065edb067c926222ab0)
```
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/collaboration/message-boards/message-boards-test/src/testIntegration/java/com/liferay/message/boards/lar/test/MBPortletDataHandlerTest.java:26: error: cannot find symbol
     [exec] import com.liferay.message.boards.model.MBThread;
     [exec]                                        ^
     [exec]   symbol:   class MBThread
     [exec]   location: package com.liferay.message.boards.model
     [exec] 1 error
     [exec] :apps:collaboration:social:social-group-statistics-web:compileJSP
     [exec] :apps:collaboration:message-boards:message-boards-test:compileTestIntegrationJava FAILED
```
https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/125078//consoleText

**Comment by jpince** [comment]
nevermind, I see adolfo already fixed it here https://github.com/brianchandotcom/liferay-portal/pull/53097

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/85473ec6d8...0dabe9914d

**Pull request closed without merging**
