### PR TITLE
LPS-67667

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@brettswaim fyi

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c506da26f4...c1d4dcfc33

**Comment by brianchandotcom** [comment]
@tinatian test for this?

**Comment by tinatian** [comment]
Yes, I have tested this. Do you want me to create unit/integration test for this?

**Pull request closed without merging**
