### PR TITLE
LPS-93444 Follow service.xml order for updating the fields

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by jkappler** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4884ab5149...a10529a245

**Comment by brianchandotcom** [comment]
Thank you team!!!!

**Pull request closed without merging**
