### PR TITLE
LPS-76518 Fix very weak assertion, searching a large string containin…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…g random strings for '/de' can fail. This only improves the worst case, there are other cases in this test that can still randomly fail from all the contains checking but this is the most frequent failing assertion.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@matethurzo fyi

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/78baebf008...f55ad63ec3

**Comment by brianchandotcom** [comment]
@Preston-Crary  please backport. Thx

**Comment by Preston-Crary** [comment]
Backport:
https://github.com/brianchandotcom/liferay-portal-ee/pull/19003

**Comment by matethurzo** [comment]
hey @Preston-Crary thanks for the fix, but can you please provide a bit more context on how is this a solution to the problem? it still seems to searching the same big string, so I might be missing the context. thx

**Comment by Preston-Crary** [comment]
@matethurzo I made the content that was being searched the message in the assertion that was failing to help me understand why it was randomly failing and waited for it to fail again.  Here's part of the content that was being searched in the contains check when the test randomly failed on the CI after the change:

```
[[@data_handler_path_context@/en@data_handler_private_user_servlet_mapping@@data_handler_group_friendly_url@@/deg1mrn4@|Link]]
```

RandomTestUtil.randomString() creates an 8 character alpha-numeric string by calling PwdGenerator - in this case it generated "deg1mrn4", which matches the "/de" being searched for in the test.  In the test we're looking to make sure the locale has been changed by making sure "/de" is not in the content and "/en" is.  We can see from the content it has been changed to "/en" but we're still matching the "/de" from the randomString() call.

By including some non-alpha-numeric characters '@' that are used as delimiters or increasing the length to be over 8 characters we can avoid accidental matches to the random strings.  I did both, so this assertion should now be safe.

There are still some more contains checks that could fail, because they are within the 8 character limit. But with 62 characters to choose from it's much less likely to accidentally find "/web" (one in 238,328 chance) then "/de" (one in 3,844 chance).

Hope this helps

**Pull request closed without merging**
