### PR TITLE
LPS-163832

### PR DESCRIPTION
**Pull request by carolmariaabb**
Unrelated failures [here](https://github.com/liferay-objects/liferay-portal/pull/1171#issuecomment-1270517602)

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/12eacddd32...451ac21493

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/451ac21493...451ac21493

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/451ac21493...451ac21493

**Pull request closed without merging**
