### PR TITLE
LPS-73550 Use title instead of filename because it's the information we display in the ui. Filename is internal.

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test

**Comment by robertoDiaz** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/978bfe1750...1ea3516a7f

**Comment by brianchandotcom** [comment]
Minor SF in 1ea3516

**Pull request closed without merging**
