### PR TITLE
LPS-55621 portlet.resource.id.banned.paths.regexp can be bypassed with backslash

### PR DESCRIPTION
**Pull request by topolik**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ddf02d36e3...f767f1917e

**Comment by brianchandotcom** [comment]
@jonathanmccann this is easy to write a test for! Please send with a test to ensure it doens't get broken in the future.

**Comment by jonathanmccann** [comment]
Test - https://github.com/topolik/liferay-portal/pull/148

**Pull request closed without merging**
