### PR TITLE
LPS-65369

### PR DESCRIPTION
**Pull request by Ithildir**
cc @igorbeslic and @ivicac

### CODE REVIEW

**Comment by sharonchoi** [comment]
@vicnate5 @kenjiheigel

**Comment by vicnate5** [comment]
@kenjiheigel This looks like the same issue as https://github.com/brianchandotcom/liferay-portal/pull/39113#issuecomment-214802286

**Comment by brianchandotcom** [comment]
@Ithildir @igorbeslic @ivicac please use https://repository.liferay.com/nexus/content/repositories/liferay-snapshots-ce/com/liferay/com.liferay.lcs.api/1.0.0-SNAPSHOT/

Thx

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d9dd725d37...aef55b39c5

**Pull request closed without merging**
