### PR TITLE
Lps 135504

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f10da6c6f1...20e3315dcc

**Comment by brianchandotcom** [comment]
Beautiful @Preston-Crary @shuyangzhou 

Let's chat about this in tomorrow's meeting

@david-truong fyi

**Comment by brianchandotcom** [comment]
I made one important rename in ef696c7782eaa1202d97115b11445adf74001f4e

@Preston-Crary @shuyangzhou @david-truong fyi

**Pull request closed without merging**
