### PR TITLE
LPS-57657 staging panel hides after activating staging

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @matethurzo

**Comment by matethurzo** [comment]
:+1:

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/08c02347ba...1eddf1a3ed

**Pull request closed without merging**
