### PR TITLE
LPS-193510 Add permissions in REST builder

### PR DESCRIPTION
**Pull request by joseabelenda**
.

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@nNilton find all

_getExpandoBridgeAttributes

and make _createServiceContext

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/57ef040765...4ac9434c2e

**Comment by 4lejandrito** [comment]
@joseabelenda, @brianchandotcom next time please send it to us for review.

**Pull request closed without merging**
