### PR TITLE
LPS-92311 Creating an array with an empty element

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @brianchandotcom, @hhuijser,

SF will fail. The source formatter is replacing `Arrays.asList(new SharingEntryAction[] {null})` with `Arrays.asList(null)` which throws a null pointer exception therefore is not equivalent to the original code.

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ff3a328a8c...e86fea6c3e

**Comment by brianchandotcom** [comment]
@hhuijser please fix

@4lejandrito see my workaround in e86fea6c3ed4e295ebd0b81d5be478d68ae3b9bc

**Pull request closed without merging**
