### PR TITLE
LPS-72786 Initial file structure for OAuth2 Provider

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
ci:retest

**Comment by jpince** [comment]
ci:stop

**Comment by jpince** [comment]
@csierra looks fine, test failures unrelated

**Comment by csierra** [comment]
👍 thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/32af31b9aa...d22c2f9e47

**Comment by brianchandotcom** [comment]
@csierra please see my changes in upstream. Thx!

**Pull request closed without merging**
