### PR TITLE
LPS-71634 Regenerate npm-shrinkwrap.json file with newer npm package versions

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ea0f67edec...cae78432b6

**Comment by brianchandotcom** [comment]
@jbalsas backported.

**Comment by jbalsas** [comment]
Awesome, thanks so much @brianchandotcom!

**Pull request closed without merging**
