### PR TITLE
LPS-73140 SF

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LPS-73140

Resending https://github.com/brianchandotcom/liferay-portal/pull/50360.

### CODE REVIEW

**Comment by xbrianlee** [comment]
cc: @brunobasto @juliocamarero @jbalsas @lesliewong92

**Comment by xbrianlee** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brunobasto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
@jbalsas can you move modules/apps/foundation/portal-template/portal-template-soy/src/main/java/com/liferay/portal/template/soy/utils/SoyTemplateConstants.java to *.constants*

That's where we move most constants.

otherwise, looks good. THx.

**Comment by brianchandotcom** [comment]
@jbalsas the package should be

```
*.constants.*
```

See other packages. Please resend. Thx.

**Comment by jbalsas** [comment]
Thanks, @brianchandotcom! @brunobasto will take care of that!

**Pull request closed without merging**
