### PR TITLE
LPS-79883 Remove unnecessary verifications from VerifyRole added by LPS-7539 and LPS-8117. No longer necessary since the issue only exists in versions prior to 6.1.

### PR DESCRIPTION
**Pull request by achaparro**
Thanks @jonathanmccann !

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test

**Comment by achaparro** [comment]
ci:reopen

**Comment by achaparro** [comment]
errors not related

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
