### PR TITLE
LRQA-39424 | master

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-39424

@brianchandotcom Please let the tests finish. Thanks!

cc @timpak @jpince

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by anthony-chu** [comment]
@brianchandotcom sending a followup...

**Comment by anthony-chu** [comment]
follow-up sent here: https://github.com/brianchandotcom/liferay-portal/pull/56347

**Pull request closed without merging**
