### PR TITLE
LPS-53551 unit tests

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
Hey @brianchandotcom this failure has to do with unit test compilation.
It's not really broken.

/cc @shuyangshou @migue

**Comment by brianchandotcom** [comment]
No worries. I'll take a look at this and fix it.

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
I don't get this... all tests are passing for me!

**Comment by brianchandotcom** [comment]
I'll take a look at this. Probably some CI order of commands sequence...

**Comment by brianchandotcom** [comment]
Ok. I think I fixed it in https://github.com/brianchandotcom/liferay-portal/pull/24048

I"m testing it out now. Will close this pull.

**Pull request closed without merging**
