### PR TITLE
LPS-104996 Allow admin to add new segments via roles admin portlet

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-104996](https://issues.liferay.com/browse/LPS-104996).<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
WebKeys are for session attributes and request attributes - almost always upper case.

public class RolesAdminWebKeys {

	public static final String CURRENT_ROLE_TYPE = "CURRENT_ROLE_TYPE";

	public static final String MODAL_SEGMENT_STATE = "modalSegmentState";

	public static final String ROLE_TYPES = "ROLE_TYPES";

Please resend.

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
Resent as https://github.com/brianchandotcom/liferay-portal/pull/81745

**Pull request closed without merging**
