### PR TITLE
Lps 127067 2

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Hmm... @tinatian this logic doesn't work for GS clients. They're not in liferay-portal. We need a different mechanism.. OR, we make this fully backwards compatible.

**Comment by brianchandotcom** [comment]
@shuyangzhou see comment above.

**Comment by shuyangzhou** [comment]
@tinatian to make this backwards compatible you will have to use reflection to lookup whether log4j 1 is present during test execution time. Then base on the result to further reflect calling different versions of the methods.

**Pull request closed without merging**
