### PR TITLE
Lps 76672

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
CC @jrao just some clean up I would like to do before messagebus extraction. And I believe there are more things like this can be done first. Although I don't have the time to dig into them.

**Comment by shuyangzhou** [comment]
Passed CI test at https://github.com/shuyangzhou/liferay-portal/pull/5176#issuecomment-353469371

**Comment by brianchandotcom** [comment]
@stsquared99 can you redeploy our GH connector?

See dbbb4ec4123ddfd4c5334a3054e023b90579509c to fix funky char

**Comment by brianchandotcom** [comment]
@shuyangzhou this modifies a read only subrepo (portal-workflow) can you resend?

**Pull request closed without merging**
