### PR TITLE
LPS-135504

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
@brianchandotcom please publish after merging

**Comment by hhuijser** [comment]
@ling-alan-huang

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ada731081c...062fd4a706

**Pull request closed without merging**
