### PR TITLE
LPS-104321 friendlyURL for questions

### PR DESCRIPTION
**Pull request by javiergamarra**
Adds a column, an API and uses it in questions. It should not break anything from message but let's wait for the full tests :)

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@nhpatt a lot of failures? resend? Thx.

**Comment by nhpatt** [comment]
Will do!

**Pull request closed without merging**
