### PR TITLE
LPS-74705 Declare dependencies in WEM modules

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:stop

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f76aadcade...c50cc2545b

**Pull request closed without merging**
