### PR TITLE
LPS-57609 fix for portlet providers. Asset publisher can not vier or add anything, only assets

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @ealonso

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@juliocamarero true portal web smoke test failure. Please resend.

**Comment by brianchandotcom** [comment]
@juliocamarero nvm.. that's a weird error, I think it may be from another pull. Am digging in.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ok, trying again here: https://github.com/brianchandotcom/liferay-portal/pull/28924

**Pull request closed without merging**
