### PR TITLE
LPS-68041 the transparent portlets should always be visible in desktop since we can't do toggle edit controls. In mobile, they can be toggled using the eye icon.

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:reopen

**Comment by juliocamarero** [comment]
Source formatter issue is not related to these changes.

**Comment by jpince** [comment]
@kenjiheigel maybe the SF error was triggered due to the nature of [marcos' commit](https://github.com/brianchandotcom/liferay-portal/pull/45344/commits/c468c7010c09fb90c0a15a1cb95944939a5a3883)? Can you please investigate?
```
java.lang.Exception: Missing @Override: ../../../modules/test/poshi-runner/src/main/java/com/liferay/poshi/runner/selenium/BaseMobileDriverImpl.java 66
Missing @Override: ../../../modules/test/poshi-runner/src/main/java/com/liferay/poshi/runner/selenium/BaseMobileDriverImpl.java 181
Missing @Override: ../../../modules/test/poshi-runner/src/main/java/com/liferay/poshi/runner/selenium/BaseMobileDriverImpl.java 208
Missing @Override: ../../../modules/test/poshi-runner/src/main/java/com/liferay/poshi/runner/selenium/BaseMobileDriverImpl.java 212
Missing @Override: ../../../modules/test/poshi-runner/src/main/java/com/liferay/poshi/runner/selenium/BaseMobileDriverImpl.java 216
Missing @Override: ../../../modules/test/poshi-runner/src/main/java/com/liferay/poshi/runner/selenium/BaseMobileDriverImpl.java 234
```
See https://github.com/liferay/liferay-portal/blob/22c180155e047551aec27df2c1abcf4a0cf1d753/modules/test/poshi-runner/src/main/java/com/liferay/poshi/runner/selenium/BaseMobileDriverImpl.java#L66

I don't see this failing in other pulls.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
