### PR TITLE
LPS-89176 Add column in upgrade process

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3d5a61a672...4bd1497cbb

**Comment by brianchandotcom** [comment]
Very nice @jkappler :)

**Comment by jkappler** [comment]
cc:// @brianchiu

**Pull request closed without merging**
