### PR TITLE
[PLEASE DO NOT BACKPORT] - LPS-99619 We don't want to show the usages for the moment

### PR DESCRIPTION
**Pull request by jkappler**
Hey @brianchandotcom, this is a follow up to Victors pulls. We'll take care of the backport since some small finishing details and testing are required.

Thanks

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by jkappler** [comment]
cc:// @victorg1991, @ealonso

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0cb8e87e21...c3bfbaa443

**Comment by brianchandotcom** [comment]
@jkappler I did not backport.

**Pull request closed without merging**
