### PR TITLE
LPS-56418 git-commit-plugins

### PR DESCRIPTION
**Pull request by matethurzo**
@ZoltanTakacs

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/18f01ec54e...f32bcc90d2

**Comment by brianchandotcom** [comment]
@matethurzo please see my changes in upstream. I made a decent amount. Thx for the pull!

**Comment by brianchandotcom** [comment]
@matethurzo I'm going to trust you even more now :) I realized the DLFileEntry != FileEntry thing... just reverted those bugs I added. Thx @matethurzo

**Comment by matethurzo** [comment]
Thanks @brianchandotcom, yes those were left that way on purpose, next time I should probably highlight it some way :)

**Pull request closed without merging**
