### PR TITLE
LPS-74206 Remote publication fails with missing comments reference at an approved asset

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:reopen

**Comment by adolfopa** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c077588956...81f0c9d4cb

**Comment by brianchandotcom** [comment]
@adolfopa @matethurzo see 81f0c9d4cbb432831a18efbc149930ebcfb1c2d2 thx.

**Pull request closed without merging**
