### PR TITLE
LRQA-44772 | master

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LRQA-44772

7.1.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/22392

cc @kmaria This moves the staging team tests out of the wem team folder.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
You should probably reorg the WEM structure in 7.1.x too.. otherwise, just going to be a backport issue in the future (if things haven't changed much yet)

**Comment by brianchiu** [comment]
@brianchandotcom Got it. That makes sense.

**Comment by brianchiu** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:close already in master upstream https://github.com/liferay/liferay-portal-ee/compare/5420ca38cd6af49360fe12c273406455253e55b4%5E...968cc530516c054b086c85482f92cadc104b0fdf

**Pull request closed without merging**
