### PR TITLE
LPS-80681 Update to latest snapshot

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
ci:reopen

**Comment by csierra** [comment]
failures seem unrelated?

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@csierra we may eventually have to cache this snapshot.. since snapshots get deleted after X number of days usually.

@ithildir can you work with @CAustin582 to cache this on com.liferay? Thx.

**Comment by Ithildir** [comment]
@csierra, are you planning on changing this snapshot any time soon?

**Comment by Ithildir** [comment]
Done: https://github.com/brianchandotcom/liferay-portal/pull/60652

**Pull request closed without merging**
