### PR TITLE
LPS-77840

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:test

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
@petershin 

I'm not able to publish, I get an infinite loop now:

Hangs on...

```
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - Finished at: 2018-02-08T15:18:46-08:00
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - Final Memory: 20M/856M
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - ------------------------------------------------------------------------
:util:source-formatter:formatXML
:util:source-formatter:formatSource
/home/brian/dev/projects/github/liferay-portal/modules/util/source-formatter/src/main/resources/META-INF/maven/com.liferay/com.liferay.source.formatter/plugin-help.xml (SourceCheck:XMLEmptyLinesCheck)
/home/brian/dev/projects/github/liferay-portal/modules/util/source-formatter/src/main/resources/META-INF/maven/plugin.xml (SourceCheck:XMLEmptyLinesCheck)
/home/brian/dev/projects/github/liferay-portal/modules/util/source-formatter/src/main/resources/checkstyle.xml (SourceCheck:XMLEmptyLinesCheck)
/home/brian/dev/projects/github/liferay-portal/modules/util/source-formatter/src/main/resources/checkstyle.xml (SourceCheck:XMLWhitespaceCheck)
/home/brian/dev/projects/github/liferay-portal/modules/util/source-formatter/src/main/resources/sourcechecks.xml (SourceCheck:XMLEmptyLinesCheck)
/home/brian/dev/projects/github/liferay-portal/modules/util/source-formatter/src/main/resources/sourcechecks.xml (SourceCheck:XMLWhitespaceCheck)
                       Exception in thread "main" java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Unable to format ./src/main/java/com/liferay/source/formatter/BNDImportsFormatter.java
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:301)
        at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:216)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Unable to format ./src/main/java/com/liferay/source/formatter/BNDImportsFormatter.java
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.liferay.source.formatter.BaseSourceProcessor.format(BaseSourceProcessor.java:125)
        at com.liferay.source.formatter.SourceFormatter._runSourceProcessor(SourceFormatter.java:676)
        at com.liferay.source.formatter.SourceFormatter.access$000(SourceFormatter.java:64)
        at com.liferay.source.formatter.SourceFormatter$1.call(SourceFormatter.java:287)
        at com.liferay.source.formatter.SourceFormatter$1.call(SourceFormatter.java:283)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Unable to format ./src/main/java/com/liferay/source/formatter/BNDImportsFormatter.java
        at com.liferay.source.formatter.BaseSourceProcessor._performTask(BaseSourceProcessor.java:655)
        at com.liferay.source.formatter.BaseSourceProcessor.access$000(BaseSourceProcessor.java:68)
        at com.liferay.source.formatter.BaseSourceProcessor$1.call(BaseSourceProcessor.java:114)
        at com.liferay.source.formatter.BaseSourceProcessor$1.call(BaseSourceProcessor.java:110)
        ... 4 more
Caused by: java.lang.NoClassDefFoundError: com/liferay/petra/string/StringBundler
        at com.liferay.source.formatter.parser.JavaClassParser.parseJavaClass(JavaClassParser.java:82)
        at com.liferay.source.formatter.checks.util.SourceChecksUtil.processSourceChecks(SourceChecksUtil.java:135)
        at com.liferay.source.formatter.BaseSourceProcessor._processSourceChecks(BaseSourceProcessor.java:665)
        at com.liferay.source.formatter.BaseSourceProcessor.format(BaseSourceProcessor.java:298)
        at com.liferay.source.formatter.JavaSourceProcessor.format(JavaSourceProcessor.java:74)
        at com.liferay.source.formatter.BaseSourceProcessor._format(BaseSourceProcessor.java:546)
        at com.liferay.source.formatter.BaseSourceProcessor._performTask(BaseSourceProcessor.java:643)
        ... 7 more
Caused by: java.lang.ClassNotFoundException: com.liferay.petra.string.StringBundler
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 14 more

```

**Comment by brianchandotcom** [comment]
Sorry @ptershin This comment was meant for https://github.com/brianchandotcom/liferay-portal/pull/55223

**Comment by Ithildir** [comment]
ci:reopen

**Pull request closed without merging**
