### PR TITLE
LPS-88832

### PR DESCRIPTION
**Pull request by petershin**
@gamerson

### CODE REVIEW

**Comment by petershin** [comment]
ci:reopen

**Comment by jpince** [comment]
@petershin is this not a concern? `Project 'src' not found in project ':sdk:project-templates:project-templates-service-builder'.`

**Comment by gamerson** [comment]
Hey @jpince  that looks like indeed a concern.  I looked up in the error log and the problem is coming just after the `:modules:util:portal-tools-service-builder:jar` task, so perhaps its somehow related?

```
  [exec] 
     [exec] > Task :util:portal-tools-service-builder:buildCSS NO-SOURCE
     [exec] > Task :util:portal-tools-service-builder:processResources
     [exec] > Task :util:portal-tools-service-builder:transpileJS SKIPPED
     [exec] > Task :util:portal-tools-service-builder:configJSModules SKIPPED
     [exec] > Task :util:portal-tools-service-builder:copyLibs SKIPPED
     [exec] > Task :util:portal-tools-service-builder:replaceSoyTranslation NO-SOURCE
     [exec] > Task :util:portal-tools-service-builder:wrapSoyAlloyTemplate SKIPPED
     [exec] > Task :util:portal-tools-service-builder:classes
     [exec] > Task :util:portal-tools-service-builder:autoUpdateXml SKIPPED
     [exec] > Task :util:portal-tools-service-builder:jar
     [exec] 
     [exec] > Task :util:portal-tools-service-builder:deploy
     [exec] Files of project ':util:portal-tools-service-builder' deployed to /opt/dev/projects/github/liferay-portal/tools/sdk/dependencies/com.liferay.portal.tools.service.builder/lib
     [exec] 
     [exec] > Task :util:portal-tools-service-builder:deployDependencies NO-SOURCE
     [exec] 
     [exec] BUILD SUCCESSFUL in 15s
     [exec] 46 actionable tasks: 6 executed, 40 up-to-date
     [exec] Gradle build finished at 2019-01-07 18:29:02.008.
     [exec] 
     [echo] Executing Gradle tasks: :sdk:project-templates:project-templates-service-builder:src:main:resources:archetype-resources:__artifactId__-service:buildService
     [exec] Using proxy squid.lax.liferay.com:3128.
     [exec] Configuration on demand is an incubating feature.
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Project 'src' not found in project ':sdk:project-templates:project-templates-service-builder'.
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.execution.taskpath.ProjectFinderByTaskPath$ProjectLookupException: Project 'src' not found in project ':sdk:project-templates:project-templates-service-builder'.
     [exec] 	at org.gradle.execution.taskpath.ProjectFinderByTaskPath.findProject(ProjectFinderByTaskPath.java:47)
     [exec] 	at org.gradle.execution.taskpath.TaskPathResolver.resolvePath(TaskPathResolver.java:49)
     [exec] 	at org.gradle.execution.T
```

I know there were some very recent changes to service builder.  But you can see in that error log snippet, somone or some task is decending into the service builder project template archetype and trying to run `buildService` on the archetype project itself which is incorrect.  

So I know that nothing in the PR has caused this issue as it isn't related, but perhaps its some recent changes in the `modules:util:portal-tools-service-builder`?

**Comment by gamerson** [comment]
Specicially this line should be be getting executed:
```[echo] Executing Gradle tasks: :sdk:project-templates:project-templates-service-builder:src:main:resources:archetype-resources:__artifactId__-service:buildService
     ```
That is executing a buildService task on a project that doesn't exist.  (its inside of the archetypeResources of that project template).  Not for sure who is calling that.  @petershin  any ideas?

**Comment by petershin** [comment]
@jpince, @gamerson - It seems like the project was included in the `service-builder-jdk8` test due to [ServiceBuilderBatchTestClassGroup.java#L100-L111](https://github.com/liferay/liferay-portal/blob/master/modules/test/jenkins-results-parser/src/main/java/com/liferay/jenkins/results/parser/test/clazz/group/ServiceBuilderBatchTestClassGroup.java#L100-L111).

There's also a property that can be set to exclude this project.  Will resend the pull

**Comment by petershin** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/66411

**Pull request closed without merging**
