### PR TITLE
LPS-171863 Semver

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:reopen

**Comment by kiwm** [comment]
Just starting reviewing :)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/046fe31b52...36045dbc00

**Comment by brianchandotcom** [comment]
@MarinhoFeliphe see e3fe90f1fc22d8bd1f06e9d05564982bee8e4448 2ec734fef19358415c4acbbad31f96c1baac293d e92131eef47b50a3bff9c2641facb589c56c6010 and 36045dbc00346c95e0a2b84a0d44a4aac6018129

**Pull request closed without merging**
