### PR TITLE
LPS-61505 Improve the user experience of "Plugins Configuration" by applying a lexicon patterns, rename it and move it under the Configuration

### PR DESCRIPTION
**Pull request by alee8888**

### CODE REVIEW

**Comment by alee8888** [comment]
@brianchandotcom @JorgeFerrer 
No Poshi functional test broke but through a brief exploratory testing, LPS-61567, was filed. Thanks.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/83d30af402...d85532411e

**Comment by brianchandotcom** [comment]
@jhinkey see https://issues.liferay.com/browse/LRDOCS-2125 and d85532411e119f88e3585d2baac3ce6e1a0af9ac

The text from Jorge sounded weird in English. Please rephrase. Thx.

**Comment by JorgeFerrer** [comment]
Thanks @alee8888, that was known and Nate was on it, but there was no bug yet so thanks for creating it.

**Pull request closed without merging**
