### PR TITLE
LRQA-71742 Skip failing test on form-web

### PR DESCRIPTION
**Pull request by diegonvs**
When runing this test on Node 16, some async errors occurs and it doesn't affect ShareFormModal usage on the UI

Link to the error: https://gist.github.com/diegonvs/760127cba03205261bdc2522c50bea80

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:reopen

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by diegonvs** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8a3ecbec8f...b9de46083a

**Pull request closed without merging**
