### PR TITLE
LPS-84119

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
SF failures unrelated to this pull

**Comment by hhuijser** [comment]
SF failures related to https://github.com/liferay/liferay-portal/commit/e8d046e7bcc3b9813edf1b30f1b7ce6eae6edbec
Notified @shuyangzhou already

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
