### PR TITLE
LPS-75066 Cover edge cases where _layouts is empty and the property h…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…as been set to some other negative value.

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c9ca68c4db...b0013b13d3

**Pull request closed without merging**
