### PR TITLE
LPD-11975: Apply Single Containers in API Builder

### PR DESCRIPTION
**Pull request by 4lejandrito**
## Motivation
The idea of this PR is to allow users to POST and GET Object Entries whose APISchema can contain Single Containers. With this, an user can POST using a request schema which contains a Single Container associated to several API Properties. However, if an user modifies the body Request Schema with a random Single Container, a Bad Request will be thrown because an API Property is not assigned to that Single Container. As well as, this PR is to model the new APIProperty type: `singleContainer`, establishing several validations about that and show it in the OpenAPI of API Builder.

**What's new?**
- Modify `EndpointHelper` class to include single containers in the response Schema and in the request Schema.
- Add test cases for post and get Schemas with several single container structures.
- Some changes in the headless-builder.batch-engine-data.json in order to create a new property called `API Property Type` which will have three values: `arrayContainer`, `normal` and `singleContainer`.
- Create a new method in `APIApplicationImpl` in order to retreive the ERC of the related APIProperty, this will be useful in order to represent it in the OpenAPI and in the Endpoints.
- Create new method to represent all the APIProperties in the OpenAPI.
- Create some integration and unitary tests.
- Create some validations in for single Container and those normal APIProperties that are related to a single Container
- Update Poshi macro
- Add new feature flag for containers
- Add new method in APIPropertyObjectDefinitionDeployer in order to update those existent API Properties and set them the new PickList value as 'normal'

**JIRA Related Ticket**
https://liferay.atlassian.net/browse/LPD-11975
https://liferay.atlassian.net/browse/LPD-11973
https://liferay.atlassian.net/browse/LPD-15435
https://liferay.atlassian.net/browse/LPD-15453

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
1.) HeadlessBuilderOpenAPIResourceTest.java#setup

2.) The grammar in the error sounds wrong.

3.)

```
X
	value
	record
array of X
```

**Comment by sergiojimcos** [comment]
Sent here: https://github.com/brianchandotcom/liferay-portal/pull/147108

**Pull request closed without merging**
