### PR TITLE
LPS-79976 Moves code to a method

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @matethurzo,

Is there any other way to do that? Do we need to calculate the group if we have staging activate?

Regards,
Eudaldo

**Comment by ealonso** [comment]
ci:test:sf

**Comment by matethurzo** [comment]
@ealonso @pavel-savinov we have added a StagingGroupHelper API to make this more easier, it could do a huge set of calculations on staging and live groups. Should be easy to use but let me know if you have any questions

**Comment by ealonso** [comment]
@matethurzo Thanks!! We are going to take a look at it

**Pull request closed without merging**
