### PR TITLE
LPS-58379 Move bundle config servlet to its own module

### PR DESCRIPTION
**Pull request by jbalsas**
/cc @csierra @ipeychev @rotty3000

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/dea31c1bc5...7b30f7b752

**Comment by brianchandotcom** [comment]
@jbalsas 

In Details

name = "%JS

Is the % on purpose? What does it mean? Please ask @liferay-continuous-integration 

Thx

**Comment by jbalsas** [comment]
Hey Brian,

- The `%` indicates that the field value can be __localized__. We usually put keys in there and point to the `content/Language.properties` for the value to get resolved.

- In this case, we just brought it over from the original @rotty3000 implementation of [Details.java](https://github.com/liferay/liferay-portal/blob/master/modules/portal/portal-js-loader-modules-extender/src/com/liferay/portal/js/loader/modules/extender/Details.java#L24) in the `portal-js-loader-modules-extender` module.

We could either __localize them, or simply remove the `%`__. 

What do you think?

**Pull request closed without merging**
