### PR TITLE
SYNC-12

### PR DESCRIPTION
**Pull request by mikemanyoung**

### CODE REVIEW

**Comment by mikemanyoung** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@shuyangzhou I found an example of how OSGi doesn't always load properly.. but it's very random. See how it only affected one node?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/eb1a406d29...9aa33b0f90

**Comment by shuyangzhou** [comment]
@brianchandotcom this is odd, as far as I know marketplace service does not use screen impl. It should not have that import, and my local marketplace service jar's MANIFEST does not have that import either. I think we might have a build bnd issue somehow.

**Pull request closed without merging**
