### PR TITLE
LPS-102842 Unify autoUpgrade feature

### PR DESCRIPTION
**Pull request by achaparro**
Hi @brianchandotcom,

The default value for autoUpgrade is false but because for EE and the first GA in CE we need in this way. Before releasing the next GA, we can change it so we don't need the upgrade tool between CE releases.

@vicnate5, after approving this, we need to modify our test using the autoUpgrade feature.

Thanks!

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test:upgrade-client

**Comment by vicnate5** [comment]
@achaparro Automation test for the autoUpgrade behavior is here
https://github.com/liferay/liferay-portal/blob/3b64a805ea2934fe1baa811619485895917ccdc6/modules/util/portal-tools-db-upgrade-client/src/testFunctional/ant/build-test-db-upgrade-client.xml#L386

**Comment by brianchandotcom** [comment]
@achaparro please fix tests and resend.

**Comment by vicnate5** [comment]
@achaparro I will resend this once I confirm the test fix is working.

**Pull request closed without merging**
