### PR TITLE
master-sc-414

### PR DESCRIPTION
**Pull request by sharonchoi**
https://issues.liferay.com/browse/LPS-62231

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
thx @sharonchoi !

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@sharonchoi not able to merge, please resend.

**Comment by sharonchoi** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/35591
cc @sergiogonzalez @brianchandotcom

**Pull request closed without merging**
