### PR TITLE
Lps 52273

### PR DESCRIPTION
**Pull request by shuyangzhou**
A follow up change.
CC @topolik

### CODE REVIEW

**Comment by pyoo47** [comment]
This PR Test failed because of the network outage. ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
@pyoo47 @brianchandotcom we should completely remove the auto close for now, it gets super annoying. CI is far away from being stable enough to do this. Let's hold off on it until it is more stable.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
