### PR TITLE
LPS-73996

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@drewbrokke, @jorgeferrer fyi

**Comment by mhan810** [comment]
@topolik fyi moving to extender pattern vs inheritance.  See https://github.com/brianchandotcom/liferay-portal/pull/50736/commits/136b1d7eb570eea6ebacf6ccee732a5da9d8d1f3 and https://github.com/brianchandotcom/liferay-portal/pull/50736/commits/379324cba2e4e8b7f0a8d01c73e7ff6e5312b4cb

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/819bf29f09...4950475f57

**Comment by brianchandotcom** [comment]
@mhan810 @topolik can you guys work on backporting this? I assume this is really a bug fix.

**Comment by mhan810** [comment]
@brianchandotcom it's a missing feature.  will work w/ ER to backport.

**Pull request closed without merging**
