### PR TITLE
LPS-76045 Fix schema tests

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test

**Comment by matethurzo** [comment]
@brianchandotcom I've analysed the failures but none of them are related

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c19413c156...003633c818

**Comment by brianchandotcom** [comment]
@matethurzo please see my changes in upstream. Thx.

**Pull request closed without merging**
