### PR TITLE
LPS-55159 SF

### PR DESCRIPTION
**Pull request by shuyangzhou**
Seem there is some sort of inter-methods dependencies causing the failure.

Let me know with this SF, does it still fail for you?

I will dig into it to figure this out.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
Appended a new commit to fix the root cause. There should be no more inter-methods dependencies any more.

Let me know if it still fails for you locally.

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6a53ae9c92...06312062ef

**Comment by brianchandotcom** [comment]
@shuyangzhou I fixed the MB errors.. not related to your pull but was from my SF.

**Pull request closed without merging**
