### PR TITLE
LPS-90259 Create hidden pages for user apps belonging with Dashboard theme

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @stsquared99 @alee8888 @ChrisKian

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:reopen

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2d7d66c592...49bcacf7c4

**Comment by brianchandotcom** [comment]
@pei-jung @stsquared99  see my changes in upstream. Quite a few. Thx.

**Pull request closed without merging**
