### PR TITLE
LPS-65079 Upgrades - AssetPublisherPortletToolbarContributor error appears after upgrading from 6.1 to 7.0

### PR DESCRIPTION
**Pull request by jkappler**
@marcellustavares: thanks!!!!! 🎉 🎉 🎉 🎉 🎉 🎉

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@marcellustavares @jkappler Test failures with upgrade?

**Comment by jkappler** [comment]
Hi @brianchandotcom, @marcellustavares asked @vicnate5 about it and he said that the test failure was not caused by the pull.

**Comment by marcellustavares** [comment]
@leoadb, could you resend this? I think we need to update the DDM upgrade tests. 

Thanks

**Comment by vicnate5** [comment]
@jkappler @marcellustavares @brianchandotcom These are different test failures compared to the last pull I looked at.

**Comment by jkappler** [comment]
@vicnate5, sorry my bad :(

**Comment by marcellustavares** [comment]
resent to https://github.com/brianchandotcom/liferay-portal/pull/39066

**Pull request closed without merging**
