### PR TITLE
LPS-70000 Regenerate

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@marcellustavares

**Comment by marcellustavares** [comment]
hey @leoadb @rafaprax, why are we reverting those commits? didn't get it

**Comment by marcellustavares** [comment]
Got it, the reason is documented in the thread https://github.com/dustinryerson/liferay-portal-ee/pull/2250

Thanks @rafaprax

**Comment by leoadb** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
