### PR TITLE
LPS-96186 Avoid NullPointerException

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jeyvison this looks good. Can you resend this pull with the SPI moves? I just want to avoid 2 breaking changes . Thx.

**Comment by jeyvison** [comment]
ci:reopen

**Comment by jeyvison** [comment]
@brianchandotcom CI is complaining about the rest-client dependency. We used compileInclude and are using now -includeResource. Local is working. Not sure how to add it differently.

**Comment by brianchandotcom** [comment]
@leoadb @jeyvison I can work on the CI issue later, but we have a deeper problem:

```
		DataRecordResource dataRecordResource = DataRecordResource.builder(
		).build();

		DataRecord dataRecord = dataRecordResource.getDataRecord(dataRecordId);

```

This is going to call data resource via REST.. which needs authentication. Right now, you're going to localhost:8080 with test@liferay.com/ test

@brunofarache we need to solve this ....

**Pull request closed without merging**
