### PR TITLE
LPS-55229 return 404 for requested urls with non-valid locales

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
@sergiosanchez I have set the default to false in master since this will improve SEO
 thanks! :+1:

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d3e57a1c08...2663cf2adb

**Comment by brianchandotcom** [comment]
@sergiosanchez please see my changes. Thx.

**Comment by brianchandotcom** [comment]
@sergiosanchez @juliocamarero also, we should have a unit test for this... since this changes behavior of things.

Thx

**Pull request closed without merging**
