### PR TITLE
LPS-73854

### PR DESCRIPTION
**Pull request by Ithildir**
Rebased on top of https://github.com/brianchandotcom/liferay-portal/pull/50480 to avoid conflicts.

cc @jbalsas, @Robert-Frampton

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6f84bbefd8...8a470dfc0f

**Comment by brianchandotcom** [comment]
@jbalsas merged, and I backporetd this to 7.0.x so lang keys are synced.

**Comment by brianchandotcom** [comment]
@jbalsas note that @Ithildir used the wrong key (I just realized this after pushing it up)

He used the nonexistent LPS-73854 instead of LPS-72854

In any case, I backported it, so it's in 7.0.x.

**Comment by brianchandotcom** [comment]
@codyhoag fyi changelog

**Comment by jbalsas** [comment]
Thanks for noticing and pushing it forward, @brianchandotcom! And thanks a lot @Ithildir for the help!

**Pull request closed without merging**
