### PR TITLE
LPS-61420

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
All the SF commits already done in previous commits.

I am making this configurable (and disabled by default) for now, as I want to monitor for a bit and get the bugs out without getting angry emails from everyone...

**Comment by hhuijser** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@hhuijser weird error, please resend?

**Comment by hhuijser** [comment]
@brianchandotcom 

Think someone forgot to run SB for some commit, so SB is modifying files, but Jenkins only picks it up now since I am making changes to build.xml.
Got a feeling it will happen again if I resend

**Comment by brianchandotcom** [comment]
@hhuijser is your SF modifying generated files?

**Comment by hhuijser** [comment]
Testing it right now (it was just a guess)

**Comment by hhuijser** [comment]
Think I know what it is... I'll work on it

**Comment by hhuijser** [comment]
@brianchandotcom

When I run SB it's not modifying any of the files that Jenkins talks about it in the error log... the only file changed is CalEventFinderBaseImpl.java

I am going to send the same pull again and see what happens.

**Pull request closed without merging**
