### PR TITLE
LPS-75281 Using documents and media tab by default

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a0b492edd1...320403bd17

**Pull request closed without merging**
