### PR TITLE
LPS-73178

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
This one fixes all case in collaboration, if this looks okay to you, I can apply everywhere else

**Comment by sergiogonzalez** [comment]
👍

**Comment by brianchandotcom** [comment]
@hhuijser this looks good. Can you backport this? Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5936cfa2cd...b823a5eed9

**Comment by hhuijser** [comment]
@brianchandotcom 
I'll apply to other modules as well and then backport the whole bunch in one go

**Pull request closed without merging**
