### PR TITLE
LPS-76561 Uses inject annotation

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1973140cb9...88fd6a23d3

**Comment by brianchandotcom** [comment]
@ealonso please backport this

@shuyangzhou fyi

**Comment by ealonso** [comment]
@brianchandotcom this is no needed, because those changes are not in ee-7.0-x

**Pull request closed without merging**
