### PR TITLE
LPS-62049 ant format-source

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1a1b0d9d3b...9963c21c5c

**Comment by brianchandotcom** [comment]
@adolfopa please see my changes in upstream.

**Pull request closed without merging**
