### PR TITLE
LPS-139131 Merge remote apps and custom elements(+widgets) in just one module: remote apps

### PR DESCRIPTION
**Pull request by izaera**
This implements the minimum features to begin testing remote apps based on custom elements.

We will send more PRs after this one to enhance the feature with:

1. Per portlet instance configuration
2. Ability to choose a portlet category
3. Minor enhancements from [originating PR's feedback](https://github.com/liferay-frontend/liferay-portal/pull/1462)

Note that the original PR (https://github.com/liferay-frontend/liferay-portal/pull/1462) failed CI because it needed another round of `gradle buildService` but I've fixed that. I don't expect any other CI failure :crossed_fingers: .

### CODE REVIEW

**Comment by izaera** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Very nice.. on it

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/721ad8112b...685ac44f80

**Comment by brianchandotcom** [comment]
@jbalsas @izaera ok, I merged this with a ton of tiny changes.

@izaera please review in my origin.

ponging this back to you

1.) permissions

2.) fix iFrameURL in the JSP (I renamed the var so need you to do your magic)

3.) Isn't this

```
			String customElementURLs = remoteAppEntry.getCustomElementURLs();

			document.addText(
				Field.URL, customElementURLs.split(StringPool.NEW_LINE)[0]);
```

a potential index out of bound exceptions?

**Pull request closed without merging**
