### PR TITLE
Lps 204685

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@shuyangzhou not sure if the same stuff is in modules/apps/portal-search-opensearch2/portal-search-opensearch2-impl

but i also notified Petteri about this.

**Comment by shuyangzhou** [comment]
@brianchandotcom you mean 

https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-search-opensearch2/portal-search-opensearch2-impl/src/main/java/com/liferay/portal/search/opensearch2/internal/configuration/OpenSearchConfigurationWrapperImpl.java#L122

https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-search-opensearch2/portal-search-opensearch2-impl/src/main/java/com/liferay/portal/search/opensearch2/internal/search/engine/adapter/document/BulkDocumentRequestExecutorImpl.java#L205

 https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-search-opensearch2/portal-search-opensearch2-impl/src/main/java/com/liferay/portal/search/opensearch2/internal/search/engine/adapter/document/BulkDocumentRequestExecutorImpl.java#L214 

right? Those 3 usages are actually in components with @Modified method, so they have a reason to be there.

**Comment by brianchandotcom** [comment]
Ok, so we're good then. Thx @shuyangzhou

**Pull request merged**
