### PR TITLE
LRQA-44689 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-44689

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@austinchiang and 7.1.x?

**Comment by brianchandotcom** [comment]
I cherry picked it to 7.1.x for you.

**Comment by austinchiang** [comment]
@brianchandotcom Thanks. Got distracted with something

**Pull request closed without merging**
