### PR TITLE
LPS-55175

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @natecavanaugh @jbalsas @robertoDiaz @ambrinchaudhary

**Comment by brianchandotcom** [comment]
ci:retest (sorry sergio, this was my fault, retesting)

**Comment by brianchandotcom** [comment]
@sergiogonzalez can you rebase and resend? I didn't have time today to work on it since it came later during the day. Thx!

**Comment by sergiogonzalez** [comment]
Done https://github.com/brianchandotcom/liferay-portal/pull/26452

Thanks!

**Pull request closed without merging**
