### PR TITLE
LPS-59342 Apply usage

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Adding a link to https://github.com/brianchandotcom/liferay-portal/pull/32191 to preserve the conversation.

**Comment by brianchandotcom** [comment]
Hey @csierra 

I'm going to merge in your version of the pull, but I didn't get time to finish it. I hope to have it by tomorrow. Thanks for the conversation with @shuyangzhou . I really appreciate what both of you guys spoke on. Passion and intellect are rare to find. Thank you guys.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/048a2b989d...161e44a81e

**Comment by brianchandotcom** [comment]
Thx @csierra !

**Pull request closed without merging**
