### PR TITLE
LPS-165581 Modified alignmentPosition property

### PR DESCRIPTION
**Pull request by vngoliveira**
Related issue [LPS-165581](https://issues.liferay.com/browse/LPS-165581)
Last pull request closed by conflict [PR LPS-165581](https://github.com/brianchandotcom/liferay-portal/pull/128495)

### CODE REVIEW

**Comment by vngoliveira** [comment]
ci:reopen

**Comment by vngoliveira** [comment]
ci:test:sf

**Comment by vngoliveira** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5ead13141b...6963c22bed

**Pull request closed without merging**
