### PR TITLE
LPS-88665

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@Preston-Crary @brianchandotcom this sure ain't pretty, but since it's temporary code, looks fine to me

@brianchandotcom Please wait for the tests. I assume, SB test will fail since we need to publish portal-impl first?

**Comment by hhuijser** [comment]
ci:test:sf

**Comment by hhuijser** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
@Preston-Crary compile errors are related to your commits. Can you merge my pull and take care of that?

**Comment by Preston-Crary** [comment]
@hhuijser Yes, on it thanks!

**Pull request closed without merging**
