### PR TITLE
LPS-63232 Manually remove SQL with old namespace

### PR DESCRIPTION
**Pull request by adolfopa**
@brianchandotcom I had to manually remove some SQL that kept using the old namespace (see last commit). Not sure if this is the correct way of doing that, or if there may be some other files that need to be modified; I didn't found anything more, but I'm mentioning it just in case I missed something.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:reopen

**Comment by anthony-chu** [comment]
These Poshi failures are due to a VNC failure that has been reported under [LRQA-28169](https://issues.liferay.com/browse/LRQA-28169), and this causes Firefox not to start on these nodes. This issue is currently being investigated and worked on.

**Comment by brianchandotcom** [comment]
@adolfopa manual remove is correct. Thanks! Merged.

Did you account for upgrades? Thx.

**Comment by adolfopa** [comment]
Yes, there's already an upgrade to change SO -> IM. See com.liferay.invitation.invite.members.internal.upgrade.v1_0_0.UpgradeNamespace.

Thanks!

**Pull request closed without merging**
