### PR TITLE
LPS-76778 - SF

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:stop

**Comment by jbalsas** [comment]
ci:stop

**Comment by jbalsas** [comment]
Tests already ran at https://github.com/jbalsas/liferay-portal/pull/1019#issuecomment-366786708

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@jbalsas see 24be481 ? Thx.

**Comment by jbalsas** [comment]
Looks good, thanks @brianchandotcom!

**Pull request closed without merging**
