### PR TITLE
LPS-56703 Blogs Settings

### PR DESCRIPTION
**Pull request by sergiogonzalez**
This is a resend of https://github.com/brianchandotcom/liferay-portal/pull/28505#event-362485965

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @JorgeFerrer

**Comment by JorgeFerrer** [comment]
Closing due to another JSP compilation error. Will resend.

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Replaced with https://github.com/brianchandotcom/liferay-portal/pull/28516

**Pull request closed without merging**
