### PR TITLE
LPS-149104 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-149104

This is only for master.

@ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure test is unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/7483
❌ ci:test:stable - 9 out of 10 jobs passed
❌ ci:test:relevant - 9 out of 11 jobs passed in 3 hours 14 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6a9ba686cc...7c5f3bc68c

**Comment by brianchandotcom** [comment]
@ealonso bravo for this clean up!

**Pull request closed without merging**
