### PR TITLE
LPS-198054 As a System Administrator I want to change the default expiration date of the access token

### PR DESCRIPTION
**Pull request by JoyceWang08211**
[LPS-198054](https://liferay.atlassian.net/browse/LPS-198054)

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f21311b747...2d1e71a129

**Comment by brianchandotcom** [comment]
@JoyceWang08211 see 2d1e71a129705d415fcf7e3f99a589bf93e1e097

**Comment by JoyceWang08211** [comment]
cc @oliverkecskemety

**Pull request closed without merging**
