### PR TITLE
LPS-84119

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@shinnlok

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e1eb57db30...92e72172fe

**Comment by brianchandotcom** [comment]
@hhuijser this was a better fix https://github.com/liferay/com-liferay-osb-asah-private/commit/af070439ccf162b6cb74e704db25dbfa3dc8deae

@shinnlok fyi

In short,

```
"values", JSONUtil.putAll(minValue, maxValue)
```

instead of 

```
					"values",
					JSONUtil.put(
						minValue
					).put(
						maxValue
					)
```

**Comment by hhuijser** [comment]
@brianchandotcom, yup, enforcing that too

**Pull request closed without merging**
