### PR TITLE
LPS-89415 Fix property names

### PR DESCRIPTION
**Pull request by petershin**
See https://github.com/liferay/liferay-portal/commit/8ee9621<br /><br />@ling-alan-huang

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@igorbeslic @marcoleo fyi

@petershin how will this affect Commerce?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/28a967208b...43c39b36ca

**Comment by brianchandotcom** [comment]
@shinnlok does this 9b08d1551d735ace7878bcbf2c37508f2ec93648 break your code?

**Comment by shinnlok** [comment]
@brianchandotcom no

**Comment by petershin** [comment]
@brianchandotcom - this is a breaking change for `commerce`. To disable this check, the commerce team can add the line below to the `rest-config.yaml`

```
forcePredictableSchemaPropertyName: false
```

@igorbeslic @marcoleo

**Pull request closed without merging**
