### PR TITLE
LPS-100565 The cache usage change from LPS-100352 is making this poss…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…ible. When a lock removal and lock creation is overlapped, due to the transactional cache commiting is not atomic, the creator may see the removed lock from FinderCache, but EntityCache won't be able to load it due it was already removed from DB. The solution is simply going on with another retry which will most likely see fully updated caches.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
CC @dantewang @tinatian @preston-crary

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/af79d4574c...cad5654a12

**Comment by shuyangzhou** [comment]
Trying to solve this in a more general way for all Finder/EntityCache out of sync problem.

**Comment by brianchandotcom** [comment]
Not merged, please resend.

**Pull request closed without merging**
