### PR TITLE
LPS-77243 Using clay:navigation-bar

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by jpince** [comment]
ci:test

**Comment by jpince** [comment]
@austinchiang @patriciajeanperez please look for the result of this test

**Comment by patriciajeanperez** [comment]
Looks good https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=167390235 @jpince @austinchiang

**Comment by brianchandotcom** [comment]
Can you resend based after applying the same changes I made in LPS-77555? Thx.

**Pull request closed without merging**
