### PR TITLE
LRQA-64237 Added missing syntax

### PR DESCRIPTION
**Pull request by nkkwon**

### CODE REVIEW

**Comment by nkkwon** [comment]
ci:open

**Comment by nkkwon** [comment]
ci:reopen

**Comment by nkkwon** [comment]
@brianchandotcom This fixes the error blocking stable

**Comment by nkkwon** [comment]
ci:test:sf

**Comment by nkkwon** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/48216e6ea6...97f8a8e625

**Pull request closed without merging**
