### PR TITLE
LPS-122718 Update icon for Antivirus configuration category

### PR DESCRIPTION
**Pull request by patriciajeanperez**
Manually forwarded from: https://github.com/pei-jung/liferay-portal/pull/723

✔️ ci:test:stable - 14 out of 14 jobs passed
❌ ci:test:relevant - 30 out of 32 jobs passed in 1 hour 37 minutes

Failure is a race condition reported in LPS-122481

7.3.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/32021

@pei-jung

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/82b10ceb49...c5458fa687

**Comment by brianchandotcom** [comment]
@pei-jung is "shield-check" available in 7.2.x and 7.1.x? If so, can you send me pulls there? Thx.

**Comment by pei-jung** [comment]
Hi @brianchandotcom, the icon is not available in 7.2.x and 7.1.x. I've asked the lexicon team to add it. Will send you pulls once they've been added.

**Comment by jbalsas** [comment]
See https://github.com/brianchandotcom/liferay-portal-ee/pull/32824 for the `7.3.x` backport for now

**Pull request closed without merging**
