### PR TITLE
LPS-80281

### PR DESCRIPTION
**Pull request by Ithildir**
Hi,
Please let this pull finish. Also, can you please publish a new `gradle-plugins-workspace`? Thanks!

Thank you!

@petershin, once you update the changelog for `gradle-plugins`, can you please https://github.com/brianchandotcom/liferay-portal/commit/b966aed614bc4acd48e3247784a38d866239932e with the correct LPS? Thanks!! 😊 

cc @timpak, @gamerson, @lawrence-lee

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:test

**Comment by petershin** [comment]
@Ithildir - Yup, will fix the changelogs

**Comment by brianchandotcom** [comment]
@codyhoag see changelog. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c9941d3d4e...7f67e5f43c

**Pull request closed without merging**
