### PR TITLE
LPS-65390 Explicitly include transitive dependencies

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @adolfopa

**Comment by adolfopa** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Nice @adolfopa 

Now we're just missing

**/modules/apps/knowledge-base/knowledge-base-web/src/main/resources/META-INF/resources/display/configuration.jsp,\

Thx!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/47210121d5...ef3c1fb0fc

**Pull request closed without merging**
