### PR TITLE
LPS-71251 Moving check up in the call stack (because fetch*() methods of other services always throw this exception).

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by eperezg** [comment]
ci:retest

**Comment by brandizzi** [comment]
ci:retest

**Comment by brandizzi** [comment]
ci:retest

**Comment by eperezg** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by eperezg** [comment]
ci:retest

**Comment by eperezg** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
