### PR TITLE
LPS-76263 SF

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b26950d331...0f3a8bf5aa

**Comment by brianchandotcom** [comment]
@jbalsas I made some SF changes, see upstream.

I think I also caught a potential typo/error:

```
			sourceURL.setParameter(
				"targetVersion", String.valueOf(_targetVersion));
```

and

```
			targetURL.setParameter(
				"sourceVersion", String.valueOf(_sourceVersion));
```

looks wrong/swapped to me.

**Comment by jbalsas** [comment]
Thanks @brianchandotcom!

This doesn't seem like a type but just how the urls are constructed. Code currently in `7.0.x` does the same:

https://github.com/liferay/liferay-portal-ee/blob/7.0.x/modules/apps/foundation/frontend-taglib/frontend-taglib/src/main/resources/META-INF/resources/diff_version_comparator/page.jsp#L63

and 

https://github.com/liferay/liferay-portal-ee/blob/7.0.x/modules/apps/foundation/frontend-taglib/frontend-taglib/src/main/resources/META-INF/resources/diff_version_comparator/page.jsp#L104

**Pull request closed without merging**
