### PR TITLE
LPS-61003 The current user group and assigned user that is added does not display in the portlet after clicking Save on Windows

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke

### CODE REVIEW

**Comment by drewbrokke** [comment]
@pei-jung this ended up being the same root cause as the User Groups user search bug?  Seemed like it, but I wasn't sure.

**Comment by pei-jung** [comment]
@drewbrokke: Yeah, it's the same root cause. I applied the same fix to users and user groups search.

**Comment by drewbrokke** [comment]
@pei-jung Very cool.  We'll have to make sure to update Roles Admin once it gets merged.

**Comment by lesliewong92** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pei-jung rebase error, please resend.

**Comment by pei-jung** [comment]
resent as https://github.com/brianchandotcom/liferay-portal/pull/35730.

**Pull request closed without merging**
