### PR TITLE
Lps 75485

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:stop

**Comment by brianchiu** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@shuyangzhou will resend.

**Comment by shuyangzhou** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/52959

**Pull request closed without merging**
