### PR TITLE
LPS-165523 Remove majority of the modules from LXC blacklist

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:reopen

**Comment by jkappler** [comment]
@brianchandotcom, sending you directly since the CI is acting weird. Should be safe since we remove the blacklisted bundles

**Comment by jkappler** [comment]
ci:close

**Comment by jkappler** [comment]
ci:reopen

**Comment by jkappler** [comment]
cc:// @zsoltbalogh

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e413c49155...a0aaf587c9

**Pull request closed without merging**
