### PR TITLE
LPS-109579 Apply only to journal tbar

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e801525a0b...c116c19b13

**Comment by brianchandotcom** [comment]
@ealonso great job splitting up those requests.

**Comment by brianchandotcom** [comment]
splitting up those commits I mean.

**Pull request closed without merging**
