### PR TITLE
LPS-71381 As a developer, I would like to be able to get System-scoped configurations using the ConfigurationProviderUtil

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-71381](https://issues.liferay.com/browse/LPS-71381).<br><br>/cc @pei-jung @jorgeferrer

### CODE REVIEW

**Comment by drewbrokke** [comment]
Hey @brianchandotcom, this pull adds a method that will speed up development on a few of our other stories.  If you could take a look at this soon, it would help us a lot.  Thanks!

**Comment by drewbrokke** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/44b4b65717...ddea4117cd

**Comment by brianchandotcom** [comment]
@drewbrokke is this safe to backport? If so, please do so. Thx.

**Comment by brianchandotcom** [comment]
@jorgeferrer this looks safe to me, and I can imagine other modules needing something like this.

@drewbrokke if it's not, just leave it as master only.

Thx

**Comment by JorgeFerrer** [comment]
My main doubt is, what are the consequences to increasing the minor number in the portal-kernel version?

**Comment by drewbrokke** [comment]
@JorgeFerrer I don't think this would increase `portal-kernel`'s verison.  We're only updating packageinfo files.  Am I missing something?

**Comment by JorgeFerrer** [comment]
Hmm, but you are adding a method to an existing interface (ProviderType) of the API. Shouldn't that force you to change the minor version of the module?

**Comment by drewbrokke** [comment]
My understanding is no, since the increased minor versions of the packages do not surpass the minor version of the module itself.  

If they were not ProviderType, then it would be a larger version increase (I just tested on a non-ProviderType class, and it was a major package increase), but it is still not guaranteed to bump the module version.

I may be mis-remembering how the package to module versioning relationship works, but in any case the versioning is automated when building `portal-kernel`.

**Comment by drewbrokke** [comment]
Hey Brian, Zoltan is asking why this one should be backported.  He's not sure it meets the requirements.  https://github.com/dustinryerson/liferay-portal-ee/pull/2785#issuecomment-294748268.  Why do you want to backport this story?  I'm just not sure what to tell him right now, since I don't think it's totally necessary (but would be nice to have).

**Comment by JorgeFerrer** [comment]
Hey Drew,

I don't think this is a must, but it adds value since the API was
incomplete without this method (so it could be considered a perceived bug).
Also it seems to have a very low risk, doesn't it?

Why does Zoltan believe that it does not meet the criteria?

**Comment by drewbrokke** [comment]
I believe it was mostly because the ticket was not classified as a bug.  I think they're (rightfully) wary of backporting stories if they don't have to.  Thanks for your comment on the pull.

**Pull request closed without merging**
