### PR TITLE
LPS-63481 Fix integration test

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @marcellustavares @inacionery @mdelapenya

**Comment by marcellustavares** [comment]
Thanks @sergiogonzalez @mdelapenya :+1:

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1c4f0dd0ca...1ea2a3c1d2

**Comment by brianchandotcom** [comment]
@inacionery nice job!

**Comment by inacionery** [comment]
:smile:

**Pull request closed without merging**
