### PR TITLE
LPS-92195 Remove portal-workflow-rest

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:reopen

**Comment by inacionery** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@inacionery can you fix that unit test. Thx.

**Comment by inacionery** [comment]
Hey @brianchandotcom,

This is not related.

Thanks!

**Comment by inacionery** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
merged.

**Pull request closed without merging**
