### PR TITLE
LPS-58871 Fixes for Solr schema.xml: docValues, enablePositionIncrements

### PR DESCRIPTION
**Pull request by arboliveira**
Authors: @mhan810 @gallindo 
Reviewer: @arboliveira

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/73a24ea3eb...c5dd6de340

**Comment by brianchandotcom** [comment]
@arboliveira can we do a quick test for this? Thx.

**Comment by brianchandotcom** [comment]
@arboliveira also, can you resend  the Eclipse fixes to @Ithildir

I'm not sure how he wants to fix them. Should they just be runtime? Thx.

**Comment by brianchandotcom** [comment]
@arboliveira I had rolled back your Eclipse fixes.

**Comment by arboliveira** [comment]
@brianchandotcom Had already ran and passed all Search tests we have (integration and Arquillian) with Solr 5 before sending the PR  :)  

No problem, I'll send the Eclipse fixes to @Ithildir.

**Pull request closed without merging**
