### PR TITLE
LPS-81769 As a Liferay administrator I want to import blogpost entries from my current system

### PR DESCRIPTION
**Pull request by alejandrohdezma**

### CODE REVIEW

**Comment by ahdezma** [comment]
ci:test

**Comment by ahdezma** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@ahdezma can you resend without adding a new method to BlogsEntryServiceImpl, I'd rather go the other route and have BlogPostingNestedCollectionResource pass in more variables. Thx.

**Comment by pyoo47** [comment]
ci:test

**Comment by ahdezma** [comment]
hey @brianchandotcom, the new route exposes the `userId` which is needed for the scenario of importing/exporting from a external system

**Comment by ahdezma** [comment]
ci:reopen

**Comment by ahdezma** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@ahdezma our pattern is to never expose "userId" from *ServiceImpl, because that can be called remotely.

You'll need to find a way to fake the userId another way. Ask Sergio and Adolfo. You can do it via service context, or a thread local, but exposing userId on a remote method is not allowed.

**Pull request closed without merging**
