### PR TITLE
LPS-64157 - Update markup to match Lexicon guidelines

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by vicnate5** [comment]
This needs a poshi test fix for the DM info panel. @sharonchoi can your team take a look at this?

**Comment by brianchandotcom** [comment]
@sharonchoi please resend with a poshi fix. Thx.

**Comment by sharonchoi** [comment]
Ok will do.

**Comment by sharonchoi** [comment]
Resent with poshi fixes here: 
https://github.com/brianchandotcom/liferay-portal/pull/38439

**Pull request closed without merging**
