### PR TITLE
ISSD-4005 [Testray] Build Autofill

### PR DESCRIPTION
**Pull request by joseabelenda**
.

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:roepen

**Comment by joseabelenda** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/15b82d7d39...b6dcb13e9e

**Comment by brianchandotcom** [comment]
@joseabelenda see b6dcb13e9ec1fb6419265a832ed81cd14cde2238

**Pull request closed without merging**
