### PR TITLE
LPS-115019 Factories, impls, adapter

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:reopen

**Comment by ngriffin7a** [comment]
@brianchandotcom I sent this through the normal ci:forward process but ci:test:relevant had a hiccup -- @vicnate5 said that it was not my fault and unrelated, and that I could pass this on to you.

See Victor's comments here: https://github.com/ngriffin7a/liferay-portal/pull/130#issuecomment-687293303

This PR contains the two commits related to "Can be generated" from the PR that's been in your queue for a few days, but also contains the remaining implementation code.

Thanks in advance, Neil.

**Comment by ngriffin7a** [comment]
@brianchandotcom Kindly ask that this PR be considered for 7.4 :)

**Comment by brianchandotcom** [comment]
@ngriffin7a can you resend after rebase? Thx!

**Comment by ngriffin7a** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/100518 for the master (7.4) rebased branch

**Pull request closed without merging**
