### PR TITLE
Lps 127030

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2c0f2ac584...ea2f07ef2b

**Comment by brianchandotcom** [comment]
@mtambara 

		HttpUtil httpUtil = new HttpUtil();

		httpUtil.setHttp(new HttpImpl());


		HtmlUtil htmlUtil = new HtmlUtil();

		htmlUtil.setHtml(new HtmlImpl());

Can we auto those 2 also?

@ling-alan-huang you're going to SF this right?

**Comment by mtambara** [comment]
@brianchandotcom Sure, I can add those after I do the initial backports

**Pull request closed without merging**
