### PR TITLE
LPS-86324 Localized tests

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by jpince** [comment]
@anthony-chu more unresolved requirement errors in this one. Not sure if it's due to piecemeal implementation, or if this is a real issue.
Note references to `org.apache.felix.scr` in the log
https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/263183//consoleText

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0878181db0...cbb1d8ccf3

**Comment by brianchandotcom** [comment]
@cgoncas see minor changes in upstream. Thx.

**Pull request closed without merging**
