### PR TITLE
LPS-95723 Fix PATCH in HttpInvoker

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
Hi @brianchandotcom!

It looks like this refactor https://github.com/brianchandotcom/liferay-portal/commit/278c35909bd6f8de3b28e5dc8f12d8c97c257efc broke the logic.

An IllegalAccessException was being thrown regardless of the JDK used as you can see here:
- https://gist.github.com/ruben-pulido/380b06424f431671856df46e03a3d42d#file-bug-out-java-8-txt
- https://gist.github.com/ruben-pulido/380b06424f431671856df46e03a3d42d#file-bug-out-java-9-txt
Output obtained using:
- https://gist.github.com/ruben-pulido/380b06424f431671856df46e03a3d42d#file-httpinvokerwithbugmain-java
and passing as program argument the id of an existing DocumentFolder.


After this commit https://github.com/brianchandotcom/liferay-portal/pull/73365/commits/00b9045b59357977ff11e774e7588e874bf50ab7 I have tested that PATCH works using JDK-8, 9, 10 and 11.
With JDK-9, 10 and 11, a warning is issued, but the result is still correct, as you can see in:
- https://gist.github.com/ruben-pulido/380b06424f431671856df46e03a3d42d#file-out-java-8-txt
- https://gist.github.com/ruben-pulido/380b06424f431671856df46e03a3d42d#file-out-java-9-txt
- https://gist.github.com/ruben-pulido/380b06424f431671856df46e03a3d42d#file-out-java-10-txt
- https://gist.github.com/ruben-pulido/380b06424f431671856df46e03a3d42d#file-out-java-11-txt

Output obtained using:
- https://gist.github.com/ruben-pulido/380b06424f431671856df46e03a3d42d#file-httpinvokermain-java
and passing as program argument the id of an existing DocumentFolder.

In the future, when we no longer support JDK-8, we could switch to using the new HttpClient:
https://docs.oracle.com/en/java/javase/11/docs/api/java.net.http/java/net/http/HttpClient.html

**Comment by brianchandotcom** [comment]
Thank you @ruben-pulido  Merged.

Will this code work in JDK 9? Ppl can use JDK 8 and above. So we need to make sure this code works for all JDK 8 and above.

**Comment by ruben-pulido** [comment]
Hi @brianchandotcom
I have tested that it works using JDK-8, 9, 10 and 11.
With JDK-9, 10 and 11, a warning is issued, but the result is still correct.
You can see the warning in the gists I linked above

**Pull request closed without merging**
