### PR TITLE
LPS-181930 Take into account custom fields, meta tags and page definition when creating a page

### PR DESCRIPTION
**Pull request by jkappler**
https://issues.liferay.com/browse/LPS-181930

### CODE REVIEW

**Comment by jkappler** [comment]
ci:reopen

**Comment by jkappler** [comment]
@alessandromalves, @ealonso, @ruben-pulido

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a9d46744a2...d3f36aa728

**Comment by brianchandotcom** [comment]
@alessandromalves, @ealonso, @ruben-pulido @jkappler see d3f36aa728706aca03eb81b8b6a8ba5ef081b2a5

**Pull request closed without merging**
