### PR TITLE
LPS-59972 - Moving image to being in the CSS so that it's easier to theme

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @evannagayama,

This pull brokes many functional test regarding the empty result message from portlets, because we added a image, so now we have the image and a text. Could you take a look into this?. Let me know if you need some changes to fix the test.

temp

Thanks you very much!!!

**Comment by ealonso** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/31718 for the test failures

**Comment by evannagayama** [comment]
@ealonso I'll fix the tests right now. Do you want me to push them to you? Or push all your commits and my test fixes to BChan?

**Comment by ealonso** [comment]
Please push it to BChan, I'm going to close this one.

Thanks you very much!!!

**Comment by evannagayama** [comment]
Ok thanks!

**Comment by evannagayama** [comment]
@ealonso just wondering, will this also change all the other content messages as well. Right now it seems to only affect blogs, sites, and recycle bin. Thanks

**Pull request closed without merging**
