### PR TITLE
LPS-105038 buildLang

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
@boton, @ambrinchaudhary

**Comment by 4lejandrito** [comment]
Hey @austinchiang,

This pull might (or might not) break sharing autocomplete functional tests.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7427b6cd64...1f223b9434

**Comment by austinchiang** [comment]
ci:test:sharing

**Pull request closed without merging**
