### PR TITLE
LPS-190596 Allow users to define sorts

### PR DESCRIPTION
**Pull request by sergiojimcos**
Jira issue: [LPS-190596](https://liferay.atlassian.net/browse/LPS-190596)

cc/ @cgmonte @naraandrade

### CODE REVIEW

**Comment by sergiojimcos** [comment]
Rebase from: https://github.com/liferay-headless/liferay-portal/pull/1576

**Comment by sergiojimcos** [comment]
ci:reopen

**Comment by cgmonte** [comment]
Hi @brianchandotcom, this PR is part of headless' API Builder initiative.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9a51297413...2a35268014

**Comment by brianchandotcom** [comment]
@cgmonte see 66d721fe52f4c404730d7e373bf7f3944bcfb9e6

**Pull request closed without merging**
