### PR TITLE
LPS-87928

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-87928.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3c429fd7e8...43675a8841

**Comment by brianchandotcom** [comment]
@jonmak08 please backport. Thx.

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/liferay/liferay-portal-ee/pull/11292

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/liferay/liferay-portal-ee/pull/11298

**Pull request closed without merging**
