### PR TITLE
LPS-139768 Change additional instance of previously changed macro

### PR DESCRIPTION
**Pull request by nikki-pru**
http://issues.liferay.com/browse/LPS-139768

This change unblocks the sync to master.

cc @rodrigocunhaa, @andreefarias

### CODE REVIEW

**Comment by nikki-pru** [comment]
ci:reopen

**Comment by nikki-pru** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3ea77d2b26...1a29a0fff1

**Pull request closed without merging**
