### PR TITLE
LPS-89890 Apply new vertical cards

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by ealonso** [comment]
cc @brianchiu, @kyle-miho

**Comment by brianchiu** [comment]
@ealonso 
I'll take a look at this one too.

**Comment by brianchiu** [comment]
ci:close

**Comment by brianchiu** [comment]
Testing here:
https://github.com/brianchiu/liferay-portal/pull/1771

**Pull request closed without merging**
