### PR TITLE
LPS-95667 Fix test

### PR DESCRIPTION
**Pull request by epgarcia**
For the cookie naming, see https://github.com/liferay/liferay-portal/blob/master/modules/apps/analytics/analytics-client-js/src/analytics.js#L27

### CODE REVIEW

**Comment by epgarcia** [comment]
@dgarciasarai

**Comment by brianchandotcom** [comment]
@epgarcia how come some are camel cased and some not?

```
	public static final String AC_CLIENT_USER_ID = "ac_client_user_id";

...
	public static final String DEVICE_BRAND = "deviceBrand";

	public static final String DEVICE_MODEL = "deviceModel";

	public static final String DEVICE_SCREEN_RESOLUTION_HEIGHT =
		"deviceScreenResolutionHeight";

	public static final String DEVICE_SCREEN_RESOLUTION_WIDTH =
		"deviceScreenResolutionWidth";

	public static final String LANGUAGE_ID = "languageId";

	public static final String LAST_SIGN_IN_DATE_TIME = "lastSignInDateTime";
```

Please resend? Thx.

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
Hi @brianchandotcom,

Sorry, we mixed the cookie name (which is snake case, as defined by [analytics](https://github.com/liferay/liferay-portal/blob/master/modules/apps/analytics/analytics-client-js/src/analytics.js#L27), with the context accessor, which are camel case. We fixed this and took the chance to decouple the Asah logic even more. See #74230.

Thanks

**Pull request closed without merging**
