### PR TITLE
LPS-65693 move to static

### PR DESCRIPTION
**Pull request by rotty3000**
This one works in both modes (bundles or lpkgs). /cc @mhan810 @shuyangzhou @Ithildir @CAustin582 @lionah @jrhoun

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
`ant test-class-group -Dtest.class.group.index=0` had zero errors for me with the lpkg files. testing without them....

**Comment by rotty3000** [comment]
`gw :apps:social-networking:social-networking-test:testIntegration` also passed with no errors with lpkg files

**Comment by rotty3000** [comment]
`ant test-class-group -Dtest.class.group.index=0` had zero errors for me with normal bundle deployment!

**Comment by rotty3000** [comment]
`gw :apps:social-networking:social-networking-test:testIntegration` passed again with no errors with standard bundle deployment

**Comment by brianchandotcom** [comment]
@rotty3000 will resend (based on Skype log). Almost there bro! You can do it :)

**Pull request closed without merging**
