### PR TITLE
LPS-163347 Add terms as a MUST clause to filter hits

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-163347

@JavierMoral 
@ealonso

### CODE REVIEW

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/9685

:heavy_check_mark: ci:test:stable - 26 out of 26 jobs passed
:x: ci:test:relevant - 70 out of 75 jobs passed in 1 hour 43 minutes

**Comment by ozysouza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/590dc9b6c7...8d84bc2275

**Comment by brianchandotcom** [comment]
@JavierMoral see 4f54c85b63d772f247b3196a66f9d7461e34b80b

**Pull request closed without merging**
