### PR TITLE
LPS-183643 Order needs to match service.xml or table.sql

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/33d00b054c...65aa8b6901

**Comment by brianchandotcom** [comment]
@MarinhoFeliphe do we need 65aa8b6901fde94012ab93578fbfac2439565106  ?

**Comment by MarinhoFeliphe** [comment]
@brianchandotcom we need, otherwise, the creation date of the original object will be replicated.

**Pull request closed without merging**
