### PR TITLE
LPS-201681 Enable image AI-creator from instance & site settings (From Roberto)

### PR DESCRIPTION
**Pull request by JamesAGarcia**
Here is Roberto's code along with the wordsmithed language properties, per your request (https://github.com/brianchandotcom/liferay-portal/pull/143870).

After reading your discussion in https://github.com/brianchandotcom/liferay-portal/pull/143849, I would suggest this text:
> To enable ChatGPT for this site, first enable it for your instance.
> To enable DALL-E for this site, first enable it for your instance.

This condenses the original message and avoids the confusion Roberto mentioned.

If you don't like it, let me know and I can update it to this shorter alternative:

> Enable ChatGPT in instance settings to use it for this site.
> Enable DALL-E in instance settings to use it for this site.

Hope this helps. 

(cc [robertoDiaz](https://github.com/robertoDiaz))

### CODE REVIEW

**Comment by JamesAGarcia** [comment]
ci:reopen

**Comment by robertoDiaz** [comment]
Thank you @JamesAGarcia!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cd4dc25921...a18f8f6eb1

**Comment by brianchandotcom** [comment]
@robertoDiaz @JamesAGarcia I just found one typo in e1897eb190538b1a78f35506fe4b3e3ed7b8a109

Thx guys

**Comment by robertoDiaz** [comment]
Thank you @brianchandotcom

**Pull request closed without merging**
