### PR TITLE
LPS-66662

### PR DESCRIPTION
**Pull request by dejuknow**

### CODE REVIEW

**Comment by brianchiu** [comment]
Xss and Wiki failures are most likely due to a bug (but not related to this pull because they're failing in other pulls).

@sharonchoi @nikki-pru @patriciajeanperez @austinchiang Can you all take a look?

after3

**Comment by brianchandotcom** [comment]
@ZoltanTakacs @zsoltbalogh I backported this since the Sync team knows this piece very well.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5aeba085ac...9d7df18d3b

**Comment by ZoltanTakacs** [comment]
Thank you!

**Pull request closed without merging**
