### PR TITLE
LPS-67367 use default portal kernel version

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
cc @ericyanLr

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by ericyanLr** [comment]
Hey @pavel-savinov @brianchandotcom,

After taking a closer look at the solution, it kind of looks strange that the last forward request is returned for the method: **getOriginalServletRequest**.

Since we are mainly trying to get the last forward request for the Nested Portlets, do you think it would be better to create a new util class under the Nested Portlets to provide this last forward request?

The main goal of the fix is to get the last FORWARD request, so it retains the parameters provided by the FriendlyURLServlet. 

The reason it was originally placed in **getOriginalServletRequest** was to try to prevent writing duplicate code, but it may cause confusion in the long run.  Also, retrieving the last FORWARD request in this manner seems to only be needed by the Nested portlet for now.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7124d704d6...0cfeccb529

**Comment by brianchandotcom** [comment]
@pavel-savinov see instructions from @ericyanLr please resend? Thx.

**Pull request closed without merging**
