### PR TITLE
LPS-146600 Fix Test

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**
Hi @brianchandotcom,

The failures [throwed here](https://github.com/liferay-workflow/liferay-portal/pull/790) are not related.

Thank you!

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@MarinhoFeliphe 

doesn't changing

```
				new WorkflowLog() {
					{
						commentLog = StringPool.BLANK;
						description = _language.format(
							LocaleUtil.getDefault(),
							"x-assigned-the-task-to-himself",
							_portal.getUserName(
								TestPropsValues.getUserId(), StringPool.BLANK),
							false);
						state = "review";
```

to

```
				new WorkflowLog() {
					{
						commentLog = StringPool.BLANK;
						description = _language.format(
							LocaleUtil.getDefault(),
							"x-assigned-the-task-to-himself",
							_portal.getUserName(
								TestPropsValues.getUserId(), StringPool.BLANK),
							false);
						state = "Review";
```

break backwards compatibility at the REST tier?

**Comment by MarinhoFeliphe** [comment]
@brianchandotcom,

It's not a break change for us, I've checked all places that we're using this resource and this changes are not break our side,

do you believe that create a stateLabel property is a good approach to avoid break changes outside the liferay?

**Comment by MarinhoFeliphe** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
We can either 1.) expand the API or 2.) make the API degrade gracefully.

Otherwise, when we upgrade a client, this will very painful.

@MarinhoFeliphe

**Pull request closed without merging**
