### PR TITLE
Lps 70889

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@shuyangzhou I only see this error in this pull. Please resend. Thx.

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
ci:retest

I don't think they are related. Try again.

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest one more time

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@tinatian please review my changes in upstream. Thx.

**Comment by tinatian** [comment]
@brianchandotcom  The change is OK, since UsersTemplateContextContributor is always invoked before init.ftl if it exists, the order of properties won't matter.

Tina.

**Pull request closed without merging**
