### PR TITLE
LPS-59742 Do not process Document type image fields as Journal images

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
@marcellustavares, we have added the item selector to keep the behavior from 6.2 in Journal when uploading images (you probably remember the regression created by the changes to DDM Image uploader in 7). However, uploaded images to Journal were also added to the document library. These changes allow us to differentiate if the image is a JournalImage or a DL Image and do not upload the image twice.

Can you please review our changes ant let us know what you think?

thank you!

**Comment by juliocamarero** [comment]
ci:retest

**Comment by marcellustavares** [comment]
This is awesome Julio :) thanks @epgarcia for taking care of this!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/435e6e1b7f...780101caf6

**Pull request closed without merging**
