### PR TITLE
LPS-94765 Rename CustomPropertyUtil

### PR DESCRIPTION
**Pull request by jeyvison**
Hey @brianchandotcom . Not sure about the names in 0ac0512 . Could you please, take a look? Thanks!

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@petershin @pyoo47 see SF error?

**Comment by pyoo47** [comment]
@brianchandotcom Seems like a fluke error caused by GitHub. You can see in the log where we are trying to get the ref JSON Object from the GitHub API but it keeps failing.

```
[beanshell] Retrying https://api.github.com/repos/liferay/liferay-binaries-cache-2017/git/refs/heads/master in 5 seconds
[beanshell] Retrying https://api.github.com/repos/liferay/liferay-binaries-cache-2017/git/refs/heads/master in 5 seconds
[beanshell] Retrying https://api.github.com/repos/liferay/liferay-binaries-cache-2017/git/refs/tags/master in 5 seconds
[beanshell] Retrying https://api.github.com/repos/liferay/liferay-binaries-cache-2017/git/refs/tags/master in 5 seconds
[beanshell] 4137 GitHub API calls out of 5000 remain. GitHub API call limit will reset in 26 minutes 3 seconds 259 ms.
[beanshell]     https://api.github.com/repos/liferay/liferay-binaries-cache-2017/git/refs/tags/master
The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:5912: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:1554: Sourced file: inline evaluation of: `` 				 					import com.liferay.jenkins.results.parser.JenkinsResultsParserUtil;   . . . '' : TargetError : at Line: 40 : in file: inline evaluation of: `` 				 					import com.liferay.jenkins.results.parser.JenkinsResultsParserUtil;   . . . '' : throw new FileNotFoundException ( "Unable to find reference " + ref + " within " + username + "/" + repository ) ; 

Target exception: java.io.FileNotFoundException: Unable to find reference master within liferay/liferay-binaries-cache-2017
```

**Comment by jpince** [comment]
@jeyvison please fix semver error
```
      [exec] > Task :apps:data-engine:data-engine-rest-api:baseline FAILED
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.data.engine.rest.dto.v1_0              MAJOR      1.0.0      1.0.0      2.0.0      VERSION INCREASE REQUIRED
```
https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/293631//consoleText

**Pull request closed without merging**
