### PR TITLE
LPS-127843 Flip IndexableAdvice to do sync indexing by default, and add a manual switch to allow override.

### PR DESCRIPTION
**Pull request by patriciajeanperez**
This is an update for [LPS-127843](https://issues.liferay.com/browse/LPS-127843).

/cc @drewbrokke @pei-jung @alee8888 @ChrisKian @dejuknow

cc @shuyangzhou @arboliveira

Manual forward from https://github.com/drewbrokke/liferay-portal/pull/1313
✔️ ci:test:stable - 9 out of 9 jobs passed
❌ ci:test:relevant - 21 out of 23 jobs passed in 1 hour 53 minutes

Functional test failure not related

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/91b812c23e...027324b6f3

**Comment by brianchandotcom** [comment]
@drewbrokke can you start sending some examples of removing the SafeClosable in all of our portlet and action commands?

@arboliveira some background

```
		try (SafeClosable safeClosable =
				ProxyModeThreadLocal.setWithSafeClosable(true)) {
```

Our guys kept adding these to our *Portlet.java and *MVC**.java

git grep SafeClosable **MVCAction**.java

This was costing us a lot of man hours. Someone in QA would report a flake (we added a user, then list the user but the user is not there etc.). The developer would deny it and say they couldn't reproduce it. It'll go back and forth for a few weeks. Then the guy would add this SafeClosable. The cycle is even worse when a customer / support is involved.

This preapplies the SafeClosable solution so that we stop wasting so many man hours.

**Comment by brianchandotcom** [comment]
@drewbrokke @shuyangzhou I backported this to 7.3.x.

**Pull request closed without merging**
