### PR TITLE
LPS-90290

### PR DESCRIPTION
**Pull request by topolik**
Hi Brian,

resending, based on https://github.com/brianchandotcom/liferay-portal/pull/69257#issuecomment-471722164

> OAuth2RestSAPEntryActivator should be REST also.

Renamed ... f74cebb

For the record - here are others: 

```
git ls-files *Rest[A-Z]*.java
modules/apps/oauth2-provider/oauth2-provider-rest/src/main/java/com/liferay/oauth2/provider/rest/internal/endpoint/constants/OAuth2ProviderRestEndpointConstants.java
modules/apps/oauth2-provider/oauth2-provider-rest/src/main/java/com/liferay/oauth2/provider/rest/internal/security/auth/verifier/OAuth2RestAuthVerifier.java
modules/apps/portal-remote/portal-remote-rest-extender-test/src/main/java/com/liferay/portal/remote/rest/extender/test/internal/activator/configuration/RemoteRestExtenderTestBundleActivator.java
modules/apps/portal-remote/portal-remote-rest-extender/src/main/java/com/liferay/portal/remote/rest/extender/configuration/RestExtenderConfiguration.java
modules/apps/portal-remote/portal-remote-rest-extender/src/main/java/com/liferay/portal/remote/rest/extender/internal/RestExtender.java
modules/sdk/project-templates/project-templates-rest/src/main/java/com/liferay/project/templates/rest/internal/RestProjectTemplateCustomizer.java
```

But renaming RestExtenderConfiguration would break existing deployments, so I touched only OAuth2RestSAPEntryActivator.

> git ls-files Activator.java
> Follow the pattern and package for this new bundle activator.

OAuth2RestSAPEntryActivator is not bundle activator, I kept it. See similar:
```
git ls-files *SAPEntryActivator.java
modules/apps/asset/asset-service/src/main/java/com/liferay/asset/internal/security/service/access/policy/AssetEntrySAPEntryActivator.java
modules/apps/calendar/calendar-service/src/main/java/com/liferay/calendar/internal/security/service/access/policy/CalendarSAPEntryActivator.java
modules/apps/oauth2-provider/oauth2-provider-jsonws/src/main/java/com/liferay/oauth2/provider/jsonws/internal/service/access/policy/OAuth2JSONWSSAPEntryActivator.java
modules/apps/sync/sync-security/src/main/java/com/liferay/sync/security/service/access/policy/SyncSAPEntryActivator.java
```
----

https://issues.liferay.com/browse/LPS-90290

Thank you.

/cc @csierra

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/43a2d3103d...4da59d7539

**Comment by brianchandotcom** [comment]
Thanks for the comments @topolik You're always so good!

**Comment by brianchandotcom** [comment]
@topolik can you send me a rename for the other Rest* (We just won't backport it) and how bad is it for the upgrade?

Please email me. Thx.

**Comment by topolik** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/69659.

**Pull request closed without merging**
