### PR TITLE
LPS-70623 Avoid split package problems

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
that failure seems to be unrelated ci:retest

**Comment by matethurzo** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@matethurzo can you resend?

Shouldn't modules/apps/web-experience/export-import/export-import-service/src/main/java/com/liferay/exportimport/staged/model/repository/helper/StagedModelRepositoryHelperImpl.java

go in an internal package? To avoid the split package problem.

Thx.

**Pull request closed without merging**
