### PR TITLE
LPS-67838 Semver

### PR DESCRIPTION
**Pull request by matethurzo**
cc @danielkocsis

### CODE REVIEW

**Comment by jpince** [comment]
SF issue has been resolved
ci:reopen

**Comment by pyoo47** [comment]
ci:reopen

**Comment by jpince** [comment]
@matethurzo the SF failure is unique to this pull. Here's the error:
```
org.junit.ComparisonFailure: ../../../portal-kernel/src/com/liferay/exportimport/kernel/controller/ExportController.java expected:<...ation.ProviderType;
[
]import com.liferay.e...> but was:<...ation.ProviderType;
[]import com.liferay.e...>
```
I think it might want an additional new line after https://github.com/brianchandotcom/liferay-portal/pull/43383/files#diff-ea2ba90b37bd10a714b4296c8db1e989R17?

[SourceFormatterTest jenkins log](https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/41351/AXIS_VARIABLE=4,label_exp=!master/testReport/junit/com.liferay.source.formatter/SourceFormatterTest/testSourceFormatter/)

The functional test failure looks unrelated, likely a database was not properly cleared.
ci:close

**Comment by jpince** [comment]
ci:close

**Pull request closed without merging**
