### PR TITLE
master-vw-182

### PR DESCRIPTION
**Pull request by vicnate5**
@rafaprax @marcellustavares re-send

### CODE REVIEW

**Comment by marcellustavares** [comment]
cc @fernandosouza

**Comment by brianchandotcom** [comment]
Rebase error, please resend.

**Comment by vicnate5** [comment]
Forwarded to @marcellustavares for correct rebase
https://github.com/marcellustavares/liferay-portal/pull/1171

**Comment by marcellustavares** [comment]
Resent to https://github.com/brianchandotcom/liferay-portal/pull/35740

**Pull request closed without merging**
