### PR TITLE
[See Description] LPS-53136 Auto SF

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey Brian,

It seems that the pull is failing because of jsp compilation but it doesn't seem like a real bug to us

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Asking @shuyangzhou to take a look before I merge it in.

**Comment by brianchandotcom** [comment]
ci:retest

Shuyang may have fixed this in https://github.com/brianchandotcom/liferay-plugins/pull/4532 (retesting now)

**Comment by shuyangzhou** [comment]
@brianchandotcom I need to change the build.xml to add the property to fix this, will send you a pull for this.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/26091

**Comment by shuyangzhou** [comment]
@brianchandotcom you can close this pull now, it won't pass.
Just see https://github.com/brianchandotcom/liferay-portal/pull/26091, if it passes, you can merge that one which contains everything from here.

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/26091

**Pull request closed without merging**
