### PR TITLE
LPS-100972 Add a displayType Open Graph to preview component

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fce44307ab...939a1f9f88

**Comment by brianchandotcom** [comment]
@boton can you use HashMapBuilder?

@hhuijser see

```
			Map<String, Object> dataOG = new HashMap<>();

			dataOG.put(
				"targets",
				JSONUtil.putAll(
					JSONUtil.put(
						"defaultValue", layoutsAdminDisplayContext.getOpenGraphImageURL()
					).put(
						"id", "openGraphImageURL"
					).put(
						"type", "imgUrl"
					),
					JSONUtil.put(
						"defaultValue", layoutsAdminDisplayContext.getCanonicalLayoutURL()
					).put(
						"id", "canonicalURL"
					).put(
						"type", "canonicalURL"
					),
					JSONUtil.put(
						"id", "openGraphDescription"
					).put(
						"type", "description"
					),
					JSONUtil.put(
						"defaultValue", layoutsAdminDisplayContext.getPageTitle()
					).put(
						"id", "openGraphTitle"
					).put(
						"type", "title"
					)));

			dataOG.put("displayType", "og");
			dataOG.put("titleSuffix", layoutsAdminDisplayContext.getPageTitleSuffix());
```

in seo.jsp

Can you enforce HashMapBuilder for JSP too? This would make this super pretty.

**Comment by boton** [comment]
> @boton can you use HashMapBuilder?

I'll refactor this in the next issue.

**Pull request closed without merging**
