### PR TITLE
LPS-67462

### PR DESCRIPTION
**Pull request by lionah**
Also for 7.0.x please

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 what's going on with the pulls?

**Comment by brianchandotcom** [comment]
Not thread safe. Please resend. See https://github.com/brianchandotcom/liferay-plugins-ee/pull/19248

**Comment by lionah** [comment]
Got it, thanks.

**Comment by yurybutrymovich** [comment]
https://github.com/lionah/liferay-portal/pull/48

**Pull request closed without merging**
