### PR TITLE
LPS-67303

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by jpince** [comment]
@migue lpkg test failures that look unique to this pull. all of them have this error message:
```
[echo] /opt/dev/projects/github/liferay-portal/modules/build-app.xml:362: Unable to load file: java.io.FileNotFoundException: /opt/dev/projects/github/liferay-portal/modules (Is a directory)
```
closing this pull due to lpkg test failures

**Comment by jpince** [comment]
ci:close

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
LPKG issues look real? Please resend.

**Comment by jpince** [comment]
@Ithildir ReleaseVersionsTest.testReleaseVersions has different error messages on each test run. Is that an issue with the test or the pull?
https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=0,label_exp=!master/49819//testReport/com.liferay.portal.release.versions/ReleaseVersionsTest/testReleaseVersions
https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=0,label_exp=!master/6145//testReport/com.liferay.portal.release.versions/ReleaseVersionsTest/testReleaseVersions

**Comment by Ithildir** [comment]
Hi @jpince,

The test fails at the first error it encounters. It uses `walkFileTree`, which is [non-deterministic](https://docs.oracle.com/javase/tutorial/essential/io/walk.html#order) on the order it reads directories at the same level.

I don't think the failure is caused by this pull. Do we have other pulls failing?

**Comment by jpince** [comment]
@Ithildir yes, but only in master. See this pull for a similar failure https://github.com/brianchandotcom/liferay-portal/pull/44142

**Comment by jpince** [comment]
@migue @SamZiemer for the code in this pull, this is the spot where the build consistently fails: 
`     [echo] /opt/dev/projects/github/liferay-portal/modules/build-app.xml:362: Unable to load file: java.io.FileNotFoundException: /opt/dev/projects/github/liferay-portal/modules (Is a directory)`
which refers to build-app.xml line 362:
```
		<loadproperties srcFile="${app.bnd.file}">
			<filterchain>
				<linecontains>
					<contains value="Liferay-Releng-App-Title" />
				</linecontains>
			</filterchain>
		</loadproperties>
```
So maybe something needs to be renamed? I was told @peterfellwock recently encountered something similar and got some help from Shuyang to troubleshoot.

**Comment by peterfellwock** [comment]
@migue @SamZiemer @jpince look at the app.bnd at the top of your project.

**Comment by migue** [comment]
The changes @SamZiemer has done in this pull cannot cause any problem in the modules directories because he's just touched a couple of files in the portal-impl folder (related to the upgrades).

**Comment by SamZiemer** [comment]
Hi @migue @peterfellwock @jpince,

Is there something that needs to be done to make this pull committable? Currently the LPS has been closed as fixed, but no commit has been made in master under this LPS number.

**Comment by jpince** [comment]
You would have to ask Peter or Shuyang, my understanding of the issue stops at what I posted above.

**Pull request closed without merging**
