### PR TITLE
LPS-84119

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@jbalsas, see https://github.com/brianchandotcom/liferay-portal/pull/68020/commits/c478d1d786c3803422ced8487b6ffdc59fc8a086

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by jbalsas** [comment]
Thanks @hhuijser, we're working on those last 2!

**Comment by hhuijser** [comment]
@jbalsas, should this be backported to 7.1?

**Comment by jbalsas** [comment]
No, @hhuijser, just `master` for now. I'm not sure we've been backporting the build changes to `7.1`, but I'll take a look to see if it's doable and would be good to do it.

**Pull request closed without merging**
