### PR TITLE
LPS-73900

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@arboliveira fyi

**Comment by mhan810** [comment]
ci:reopen

**Comment by alee8888** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest (test-1-14 crashed)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d21fe7e95a...2ba60ca7e5

**Comment by brianchandotcom** [comment]
@mhan810 Merged.

@arboliveira fyi

**Pull request closed without merging**
