### PR TITLE
LPS-106612 Patch bcmail.jar and bcprov.jar | resend

### PR DESCRIPTION
**Pull request by dantewang**
Resend according to https://github.com/brianchandotcom/liferay-portal/pull/83423#issuecomment-575450555 cc @tinatian @shuyangzhou

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ea70d2bd6c...0ddca00b26

**Comment by brianchandotcom** [comment]
@dantewang @ChiZelin I backported this all the way to 7.1.x for you.

**Comment by brianchandotcom** [comment]
@dantewang @ChiZelin you guys may need to send this to support for 7.0.x because I could not cherry pick it.

**Comment by ChiZelin** [comment]
Hi @brianchandotcom, I rechecked it. 7.0.x don't need this fix.
cc @dantewang

**Comment by ChiZelin** [comment]
Hi @brianchandotcom I will send this to support for 7.0.x after finishing LPS-104661 backport to 7.0.x
cc @dantewang

**Pull request closed without merging**
