### PR TITLE
LPS-137592 Integrate Picklist with Forms

### PR DESCRIPTION
**Pull request by carolmariaabb**
CI results [here](https://github.com/carolmariaabb/liferay-portal/pull/479#issuecomment-921808297)

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/79c7238234...b215567fcd

**Comment by brianchandotcom** [comment]
@carolmariaabb @mateussgn can you rename ```**Picklist**.java``` etc to ```*ListType*```

Picklist is the marketing name.

ListType is the code name. We should always call it ListType in code.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8c8703de01...5cd24885ff

**Pull request closed without merging**
