### PR TITLE
LPS-172417

### PR DESCRIPTION
**Pull request by ChrisKian**
Resent from https://github.com/brianchandotcom/liferay-portal/pull/129562 with changes made.  Specifically, I've included [this commit](https://github.com/brianchandotcom/liferay-portal/pull/129780/commits/c40d26a8b4ced4fddaa553033d1c54f53ac8dd5d) which details why the ordering for the `setUp*` methods was changed, and I've renamed the `_testComboServletService()` method to just `_testService()`.  Thanks!

CC @tinatian

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/27d179a5e8...9b9e1615b2

**Comment by brianchandotcom** [comment]
@ChrisKian see changes in my origin. They explain what I was looking for. Please review (and retest). Thx!

**Comment by ChrisKian** [comment]
> @ChrisKian see changes in my origin. They explain what I was looking for. Please review (and retest). Thx!

Your changes work as expected, thanks!

**Pull request closed without merging**
