### PR TITLE
LPS-59429

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by kenjiheigel** [comment]
@mhan810, thanks for working on this and resending this! For some context, portal instances can be leveraged in our functional tests so that we can run multiple functional tests cleanly and sequentially on the PR tester, and minimize server usage time. 

@brianchandotcom @pyoo47, this pull should address the portal instance issues I referred to on Friday. I'll begin testing once this is merged. 

cc: @alee8888

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/671c49f7e3...639a89fe77

**Comment by brianchandotcom** [comment]
@mhan810 I made a few changes in upstream. Please review. Thx.

@kenjiheigel @pyoo47 can you guys try your slimmed down poshi tests now that this is in? Thx.

**Comment by kenjiheigel** [comment]
@brianchandotcom, I'll begin testing with this today. Will keep you posted.

**Pull request closed without merging**
