### PR TITLE
LPS-67718

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-67718.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey guys, this is modifying the `layouts_tree` taglib. Could you please run it by the WEM team first?

/cc @juliocamarero, @carloslancha

**Comment by jonmak08** [comment]
Sending to @juliocamarero instead

**Comment by jbalsas** [comment]
Thanks a lot, @jonmak08!

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/juliocamarero/liferay-portal/pull/4263

**Pull request closed without merging**
