### PR TITLE
LPS-176080 Test for create batch actions automatically with REST Builder

### PR DESCRIPTION
**Pull request by 4lejandrito**
https://issues.liferay.com/browse/LPS-176080

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
Commit messages fixed from https://github.com/brianchandotcom/liferay-portal/pull/130493.

**Comment by brianchandotcom** [comment]
@4lejandrito will resend based on our meeting. He has notes.

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130600.

**Pull request closed without merging**
