### PR TITLE
LPS-57159 SF and naming

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@peterfellwock see the portal web smoke test failure. It's a real test failure. That smoke test is consistently working for all other pulls.

**Comment by brianchandotcom** [comment]
A quick look @peterfellwock points to you forgetting to update a permission XML file...

**Comment by peterfellwock** [comment]
Ok. Will do first thing tomorrow.

**Pull request closed without merging**
