### PR TITLE
LPS-61560 Move to the right place

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
cc @sergiogonzalez , @jbalsas

**Comment by brianchandotcom** [comment]
@robertoDiaz I didn't get a chance to merge this in.... but hope to tomorrow.

This pull is good, I'm just borrowing it to test upstream. ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3f2145aaa3...613874809c

**Comment by brianchandotcom** [comment]
@robertoDiaz @sergiogonzalez sorry it took so long, it was mainly f0d22df319c5364d87268c6ab83ae4e0a66f6e15

**Pull request closed without merging**
