### PR TITLE
LPS-64981 make the fragments regular bundles

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @rotty3000, if we are now just tracking bundles with a `*taglib-mapping.properties`, could we move those files from the `*freemarker-contributor` bundles into the taglib ones and get rid of them?

**Comment by rotty3000** [comment]
We could. I wanted to keep the minimum change for the moment, but if we
feel it will help we could do that as a cleanup task.

**Comment by jbalsas** [comment]
Sounds good. I can take care of cleaning that up after this gets merged.

Thanks a lot for working on this!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/98e6e62bbc...f7fc4e48d7

**Pull request closed without merging**
