### PR TITLE
LPS-150754 master

### PR DESCRIPTION
**Pull request by tinatian**
FYI @shuyangzhou @vicnate5 @dnebing

### CODE REVIEW

**Comment by tinatian** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b5da9e676f...82d43e9744

**Comment by brianchandotcom** [comment]
@dantewang @tinatian I think you forgot a091b713

**Comment by brianchandotcom** [comment]
@shuyangzhou @vicnate5 @dnebing this will be in Update 19 slated for April 8.

**Comment by tinatian** [comment]
> @dantewang @tinatian I think you forgot https://github.com/brianchandotcom/liferay-portal/commit/a091b713c9a46a87eb222655c99fdc92076fe9dc

**Comment by brianchandotcom** [comment]
my bad, I'll revert it right away @tinatian

**Pull request closed without merging**
