### PR TITLE
LPS-67828 Reference Destination directly to avoid the MessageBus look…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…up race condition.

@brianchandotcom this fixes all the CI failures caused by https://github.com/brianchandotcom/liferay-portal/pull/43044

CC @brunofarache

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brunofarache** [comment]
That's great, thanks @shuyangzhou!

I have question, on this commit:

https://github.com/brianchandotcom/liferay-portal/pull/43044/files#diff-729bcc4f7b82a384bc2bf3ca0a8cefa1L129

I removed the reference to _messageBus because it wasn't being used anywhere. But now I'm wondering if this was added by @mhan810 because he wanted the Message Bus to be loaded before that module.

Should I add it back? How can we make sure the Message Bus is loaded before it?

**Comment by shuyangzhou** [comment]
@brunofarache 
No, the _messageBus was there so that it can use it to lookup the destination. The destination is what you really need, to register a listener on it. But the lookup is broken, due it runs asyncly against the destination registration, you don't know which one happens first. And actually with the current codebase, the lookup always beats the registration, causing NPE. So the fix is to remove the lookup, if you want the destination, just ask for it, not to look up it.

You don't need to add it back.

**Comment by brunofarache** [comment]
Thanks @shuyangzhou! I got it, I'm asking about this other class now:

[PushNotificationMessagingConfigurator.java](https://github.com/liferay/liferay-portal/blob/master/modules/apps/push-notifications/push-notifications-service/src/main/java/com/liferay/push/notifications/internal/messaging/PushNotificationMessagingConfigurator.java).

This is the component that actually creates the Destination and used to have a reference to _messageBus.

The component you just fixed is a different one [ApplePushNotificationsSenderConfiguration.java](https://github.com/liferay/liferay-portal/blob/master/modules/apps/push-notifications/push-notifications-sender/push-notifications-sender-apple/src/main/java/com/liferay/push/notifications/sender/apple/internal/configuration/ApplePushNotificationsSenderConfiguration.java).

**Comment by brunofarache** [comment]
Ah OK!

This other class has this reference:

```java
@Reference
private DestinationFactory _destinationFactory;
```

Which probably means the Message Bus is already initialized by then.

**Comment by shuyangzhou** [comment]
@brunofarache 

No, having :
```
@Reference
private DestinationFactory _destinationFactory;
```
Does not mean it has MessageBus ready.

PushNotificationMessagingConfigurator does not need MessageBus to be ready at all.

Its job is only to register a Destination into OSGi service registry, it does not care whether MessageBus is ready or not. All it needs to know is, when MessageBus is ready, the previous published Destination will be picked up by it.

**Pull request closed without merging**
