### PR TITLE
LPS-155155 Fix URL fields

### PR DESCRIPTION
**Pull request by izaera**
This is a followup of Friday's PR https://github.com/brianchandotcom/liferay-portal/pull/119053

### CODE REVIEW

**Comment by izaera** [comment]
ci:reopen

**Comment by izaera** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/571e7f94f2...add7ff197b

**Comment by brianchandotcom** [comment]
@izaera nice!

**Pull request closed without merging**
