### PR TITLE
LPS-84497

### PR DESCRIPTION
**Pull request by danielkocsis**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@danielkocsis @zoltancsaszi please resend.. looks like a real test integration failure.

**Comment by brianchandotcom** [comment]
@brunofarache @inacionery your change to workflow-metrics could be affecting this.. this is similar to the "key_' issue before from earlier this week.

``
java.lang.AssertionError: Thread Thread[com.liferay.portal.workflow.metrics.internal.petra.executor.WorkflowMetricsPortalExecutor-2,5,main] caught concurrent failure: java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.portal.workflow.metrics.internal.petra.executor.WorkflowMetricsPortalExecutor, message=java.lang.RuntimeException: org.elasticsearch.index.engine.VersionConflictEngineException: [workflow-metrics-processes/DPOCUWKJRSiVewTCiR9Kmg][[workflow-metrics-processes][0]] VersionConflictEngineException[[WorkflowMetricsProcessType][WorkflowMetricsProcess_PORTLET_139f6e2571a0b2f3bc98029ebf3c4c602c9a169e75daf296f80ee2cbf2dfd680]: version conflict, current version [2] is different than the one provided [1]]
java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.portal.workflow.metrics.internal.petra.executor.WorkflowMetricsPortalExecutor, message=java.lang.RuntimeException: org.elasticsearch.index.engine.VersionConflictEngineException: [workflow-metrics-processes/DPOCUWKJRSiVewTCiR9Kmg][[workflow-metrics-processes][0]] VersionConflictEngineException[[WorkflowMetricsProcessType][WorkflowMetricsProcess_PORTLET_139f6e2571a0b2f3bc98029ebf3c4c602c9a169e75daf296f80ee2cbf2dfd680]: version conflict, current version [2] is different than the one provided [1]]
	at com.liferay.portal.test.rule.LogAssertionAppender.append(LogAssertionAppender.java:60)
	at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
	at org.apache.log4j.helpers.AppenderAtta...
```

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d13abec28c...70967cd7d3

**Comment by brianchandotcom** [comment]
@zoltancsaszi @danielkocsis I merged it and backported it to 7.2.x

**Pull request closed without merging**
