### PR TITLE
LPS-70824 Control Panel elements are not responsive to role permission definition toggles

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-70824](https://issues.liferay.com/browse/LPS-70824).

This pull only does the work of wiring up the ACCESS_IN_CONTROL_PANEL permission to the User role.  It does not hide any of the other checkboxes.

/cc @jorgeferrer @pei-jung @ChrisKian

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@drewbrokke I had to roll it back d91f06eab99c1ce93b71f80229749667a4243b87 for now

I know why it broke for Shopping. I'll explain tomorrow. In short:

```
Building ShoppingCart
Building ShoppingCategory
Building ShoppingCoupon
Building ShoppingItem
Building ShoppingItemField
Building ShoppingItemPrice
Building ShoppingOrder
Unable to find Subscription in Account,Address,BrowserTracker,ClassName,ClusterGroup,Company,Contact,Country,EmailAddress,Group,Image,Layout,LayoutBranch,LayoutFriendlyURL,LayoutPrototype,LayoutRevision,LayoutSet,LayoutSetBranch,LayoutSetPrototype,LayoutTemplate,ListType,MembershipRequest,Organization,OrgGroupRole,OrgLabor,PasswordPolicy,PasswordPolicyRel,PasswordTracker,Permission,Phone,PluginSetting,Portal,PortalPreferences,Portlet,PortletItem,PortletPreferences,RecentLayoutBranch,RecentLayoutRevision,RecentLayoutSetBranch,Region,Release,Repository,RepositoryEntry,Resource,ResourceAction,ResourceBlock,ResourceBlockPermission,ResourcePermission,ResourceTypePermission,Role,ServiceComponent,SystemEvent,Team,Theme,Ticket,User,UserGroup,UserGroupGroupRole,UserGroupRole,UserIdMapper,UserNotificationDelivery,UserNotificationEvent,UserTracker,UserTrackerPath,VirtualHost,WebDAVProps,Website,WorkflowDefinitionLink,WorkflowInstanceLink
Exception in thread "main" com.liferay.portal.tools.service.builder.ServiceBuilderException: Unable to find Subscription in Account,Address,BrowserTracker,ClassName,ClusterGroup,Company,Contact,Country,EmailAddress,Group,Image,Layout,LayoutBranch,LayoutFriendlyURL,LayoutPrototype,LayoutRevision,LayoutSet,LayoutSetBranch,LayoutSetPrototype,LayoutTemplate,ListType,MembershipRequest,Organization,OrgGroupRole,OrgLabor,PasswordPolicy,PasswordPolicyRel,PasswordTracker,Permission,Phone,PluginSetting,Portal,PortalPreferences,Portlet,PortletItem,PortletPreferences,RecentLayoutBranch,RecentLayoutRevision,RecentLayoutSetBranch,Region,Release,Repository,RepositoryEntry,Resource,ResourceAction,ResourceBlock,ResourceBlockPermission,ResourcePermission,ResourceTypePermission,Role,ServiceComponent,SystemEvent,Team,Theme,Ticket,User,UserGroup,UserGroupGroupRole,UserGroupRole,UserIdMapper,UserNotificationDelivery,UserNotificationEvent,UserTracker,UserTrackerPath,VirtualHost,WebDAVProps,Website,WorkflowDefinitionLink,WorkflowInstanceLink
        at com.liferay.portal.tools.service.builder.ServiceBuilder.getEntity(ServiceBuilder.java:1113)
        at com.liferay.portal.tools.service.builder.ServiceBuilder.getEntity(ServiceBuilder.java:1198)
        at com.liferay.portal.tools.service.builder.ServiceBuilder._resolveEntity(ServiceBuilder.java:5727)
        at com.liferay.portal.tools.service.builder.ServiceBuilder.<init>(ServiceBuilder.java:738)
```

**Comment by jpince** [comment]
@drewbrokke see semver issue

**Comment by jpince** [comment]
ci:close

**Comment by drewbrokke** [comment]
Pull resent as https://github.com/brianchandotcom/liferay-portal/pull/48083.

**Pull request closed without merging**
