### PR TITLE
LRQA-29852 | master

### PR DESCRIPTION
**Pull request by vicnate5**
https://issues.liferay.com/browse/LRQA-29852

### CODE REVIEW

**Comment by vicnate5** [comment]
Sent to ee-7.0.x
https://github.com/brianchandotcom/liferay-portal-ee/pull/16274

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged.

@vicnate5 note the backport had 25 commits and the one to master has 26 commits. not sure if that was intentional or not.

**Comment by vicnate5** [comment]
@brianchandotcom I am aware of the difference. Extra commit was needed on master to sync the tests.

**Pull request closed without merging**
