### PR TITLE
LPS-170938 Remove duplicate logic in unlink relationship test cases

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What is new?**
- Update all test cases related to unlink Object Relationship to remove duplicate logic. Just providing the endpoint in every test case
- Brian requested changes in https://github.com/brianchandotcom/liferay-portal/pull/127857#issuecomment-1358018055

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-170938

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:reopen

**Comment by sergiojimcos** [comment]
Manual forwarding from: https://github.com/liferay-headless/liferay-portal/pull/939

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/da2f7440e5...381cfcc355

**Comment by brianchandotcom** [comment]
@sergiojimcos see 381cfcc355a336b21d1f712086ec8850b68d3e03

**Pull request closed without merging**
