### PR TITLE
LPS-88832

### PR DESCRIPTION
**Pull request by petershin**
@gamerson @jpince

### CODE REVIEW

**Comment by lawrence-lee** [comment]
@petershin @michaelhashimoto Is there something else we need to do to get the `test.properties` excludes to work for service builder?

**Comment by petershin** [comment]
@lawrence-lee - QA sent a patch for this bug.  See https://github.com/pyoo47/liferay-portal/pull/933

**Comment by lawrence-lee** [comment]
ci:test:relevant

**Comment by lawrence-lee** [comment]
@petershin can we reopen or resend this PR?

**Comment by petershin** [comment]
@lawrence-lee - Its been merged into upstream.  See https://github.com/brianchandotcom/liferay-portal/pull/66475

**Pull request closed without merging**
