### PR TITLE
LPS-93960 Simplify

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@brunobasto minor SF here 74bea4c79d1d734414a22786b02e2d69ca8a0398 thank you!

**Comment by brianchandotcom** [comment]
@brunobasto thank you for working hard to get this thing done man... much appreciated. I see it.

**Comment by brunobasto** [comment]
Thanks, @brianchandotcom! We can do it!

**Pull request closed without merging**
