### PR TITLE
Lps 83935

### PR DESCRIPTION
**Pull request by shuyangzhou**
@rotty3000 this is one of the efforts we made to make sure the OSGi/state is portable. The goal is to release with a pre-populated osgi/state to speed up the first bootup. If by any chance you can bring this back to eclipse that will be great, that way we don't have to carry on this patch. Thanks!

CC @mhan810

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@mtambara can you guys resend, somehow this patched third party never followed our normal "patch" behavior.

See modules/third-party/org-hibernate-core/patches/*.patch and modules/third-party/org-hibernate-core/build.gradle

you'll need to make patch files for LPS-80352 as well as for this ticket.

Please resend. Thx!

fyi @shuyangzhou

**Comment by brianchandotcom** [comment]
@mtambara make sure the patch files also add the key "@generated"

**Comment by mtambara** [comment]
@brianchandotcom We can't use our normal patching strategy for org-eclipse-osgi because eclipse doesn't release source jars

**Comment by mtambara** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.

View just my changes: https://github.com/brianchandotcom/liferay-portal/compare/shuyangzhou:f1c8f3f811...566f56b8db
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/33d6ddef7b...566f56b8db

**Pull request closed without merging**
