### PR TITLE
LPS-91342 bulk

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/400c36505f...c246ebd968

**Comment by brianchandotcom** [comment]
@nhpatt see 95eb6e0575d559b9016f286e69b6852efc945fdf and c246ebd968722a05c73dfd28bab98aa80377260c

**Comment by nhpatt** [comment]
Yep, it's true, I don't know what I was thinking... the path is generated based on the config file.

**Pull request closed without merging**
