### PR TITLE
LPS-65450 SF

### PR DESCRIPTION
**Pull request by marcellustavares**
cc @rafaprax

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 no results?

**Comment by kevin-yen** [comment]
@brianchandotcom Its failing because we didn't update the stop job util code in Jenkins. We already fixed it and increased the timeout. However, the build started before we pushed in the fix. It should be okay in subsequent pulls.

**Comment by kevin-yen** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9533f173f9...5fadacad22

**Pull request closed without merging**
