### PR TITLE
LPS-58593 Export restrictions for journal folders

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @matethurzo

**Comment by matethurzo** [comment]
Thanks, great stuff @ealonso. Good to see that the staging API gets more clean so people start using it! :+1:

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9be2b5d46e...de4aade273

**Comment by brianchandotcom** [comment]
Nice job @ealonso @matethurzo

**Pull request closed without merging**
