### PR TITLE
LPS-109525 Semver

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by brianchandotcom** [comment]
@adolfopa I've seen this else where

com.liferay.blogs.search.test.BlogsEntryMultiLanguageSearchTest.testEnglishTitle

@arboliveira can you help with that fix?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5f90212e8d...c4e29c0250

**Comment by brianchandotcom** [comment]
@adolfopa much much better

@SamZiemer see c4e29c02507af5e154e1bfd831c11e7622dfa94e

dynamicQuery.set* , then line break, then dynamicQuery.perform*

**Pull request closed without merging**
