### PR TITLE
LPS-92129 Taxonomy rename

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9ffeba0846...41c4b2fcf0

**Comment by brianchandotcom** [comment]
@nhpatt you lost some code that I readded. See upstream. Thx.

Good job on the rename!

**Comment by nhpatt** [comment]
Ups, forgot the customization in the tests. I have to be more careful with it.

**Comment by brianchandotcom** [comment]
@nhpatt I just ran the tests, and you also forgot bdb81c99dd1d92a0cb1f56ff4a98b2bdf0da7001

All good now though!

**Pull request closed without merging**
