### PR TITLE
LPS-68100 Remove RestrictPortletServletRequestFilter which is a deadc…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…ode, it is always merging the same Mergeable object to itself which is designed to be a NOP

CC @dantewang @slnn performance check please.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by tomwang2011** [comment]
Hi @slnn, can you run this pull with blogs test and cc me with the results too? I want to compare the results against the machines here in Diamond Bar. Thanks!

**Comment by slnn** [comment]
Hi @tomwang2011 , OK when I get the results I will cc you

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
