### PR TITLE
LPS-109810 Patch Elasticsearch 6.8.6 PainlessLookupBuilder

### PR DESCRIPTION
**Pull request by BryanEngler**
The new jar will be needed in 7.2.x. Will send another pr updating the dependencies later.

Also see https://github.com/BryanEngler/liferay-portal/pull/488#issuecomment-595464401

**ci:test:search - 38 out of 51 jobs passed** https://github.com/BryanEngler/liferay-portal/pull/488#issuecomment-594991621
✅ The only failures unique to this pull are not caused by this pr, confirmed by @joshchong

Author(s): @BryanEngler

---
*[Task] Patch Elasticsearch 6.8.6 PainlessLookupBuilder*
https://issues.liferay.com/browse/LPS-109810

### CODE REVIEW

**Comment by petershin** [comment]
@brianchandotcom - Do you have the patch executable installed?

```
patch -version
```

**Comment by petershin** [comment]
https://savannah.gnu.org/projects/patch/

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/403919095b...53de5380af

**Comment by brianchandotcom** [comment]
Sorry guys! I'm on a new desktop :(

Added patch to my autoinstall scripts.

@BryanEngler see 1606ee8356850f3c74cc7279aa01ecc2557f45d4 and 53de5380af8b40c77deb454328e888477a67a687

**Pull request closed without merging**
