### PR TITLE
master-qa-25153

### PR DESCRIPTION
**Pull request by vicnate5**
https://issues.liferay.com/browse/LRQA-25153

https://github.com/brianchandotcom/liferay-portal/pull/39618 introduces an instance-specific regression affecting Forms and Calendar ([LPS-65774](https://issues.liferay.com/browse/LPS-65774)). The tests that run into the bug have more value if we workaround the bug and have the tests only run without instances.

cc @marcellustavares @brandizzi @brianchiu

### CODE REVIEW

**Comment by vicnate5** [comment]
My change revealed another test that is affected by this bug.

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6789437875...566414df6e

**Pull request closed without merging**
