### PR TITLE
Lps 81218

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by ngriffin7a** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/14a2b24287...78c04ac07e

**Comment by brianchandotcom** [comment]
@ngriffin7a please see my tiny changes in usptream.

**Pull request closed without merging**
