### PR TITLE
LPS-78259 As a developer, I want to have a transnational mvc action command

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-76027](https://issues.liferay.com/browse/LPS-76027).
This is an update for [LPS-77754](https://issues.liferay.com/browse/LPS-77754).
This is an update for [LPS-77756](https://issues.liferay.com/browse/LPS-77756).
This is an update for [LPS-78259](https://issues.liferay.com/browse/LPS-78259).

Hey Brian, this pull adds transaction boundaries to the action commands as you requested here: https://github.com/brianchandotcom/liferay-portal/pull/55642#issuecomment-368389297.

/cc @willnewbury, @noahsherrillwork, @pei-jung, @JorgeFerrer

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Very interesting idea with "TransactionalMVCActionCommand".

Can you move that to the same package as MVCActionCommand and make it a first class citizen.

Though, I generally think this pattern should only be used for one off things. In your case, I think you're hiding logic inside your TransactionalMVCActionCommand that won't be exposed an api easily. I think that's bad, but I'm fine with it.

**Comment by JorgeFerrer** [comment]
This is interesting but Brian brings up a good point.

Why is there a need to make the action transactional?
Isn't it possible to move the logic inside a service method to make it both transactional and reusable?

**Comment by drewbrokke** [comment]
@JorgeFerrer @brianchandotcom Just so I'm clear, it's preferable in this case to create a new service method for each piece of risky logic that could end up with bad data if interrupted?  

I can imagine that the a reason that the `TransactionalMVCActionCommand` doesn't already exist is because we have a better pattern in place to begin with.  Is this the case here?

If so, are there other possible cases where we have an ActionCommand performing service calls in sequence that should consider moving their logic into a separate service call?

cc @willnewbury

**Comment by JorgeFerrer** [comment]
IMHO, the answer is yes to all the questions.

To be more specific:
> It's preferable in this case to create a new service method for each piece of risky logic that could end up with bad data if interrupted?
I haven't seen the code, but every case I've seen a similar situation in the past could be cleanly solved that way.

> If so, are there other possible cases where we have an ActionCommand performing service calls in sequence that should consider moving their logic into a separate service call?
Yes, there are quite a few that could be improved that way.

**Comment by willnewbury** [comment]
So if we are going to be updating the services instead of chaining them together, what is our policy when chaining service calls from various places? For instance, we are deactivating a user and then reactivating their group so that their personal site is still reviewable. Would I just be adding that to user service?

**Comment by JorgeFerrer** [comment]
Hey Will,

Any logic that is not related to handling the request or passing down information to the view should not be in the ActionCommand but in a Service method. That way it's reusable and transactional.

The example you provide seems to fit into this, right? Do you see any drawback in moving the logic to a service method?

Jorge

**Comment by drewbrokke** [comment]
@JorgeFerrer I suppose the one major drawback with placing this kind of logic in a service method is that this logic is very specific to this situation.  We are doing very non-standard things to be able to both disable a user but still access their personal site.  AFAICT this is the only situation where that's desirable, but if we put the logic in the service layer it's basically advertised as a feature to any dev who might be crawling through the source.

That being said, I still think we should put it in the service layer, but with documentation to indicate that it really shouldn't be used, haha.

**Pull request closed without merging**
