### PR TITLE
LPS-59828

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@hhuijser poshi failures? I think these are real.

**Comment by hhuijser** [comment]
I'll look into that

**Comment by michaelhashimoto** [comment]
@hhuijser 

If you look <a href="https://test-1-3.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/1570/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=RecyclebinWebcontent%23RestoreWebcontent,label_exp=!master/functional-tomcat-mysql/2/summary.html">here</a> it looks like the 'Web Content' portlet is gone.

Just click on the screenshots at the bottom of the page.

**Comment by hhuijser** [comment]
ci:retest

**Pull request closed without merging**
