### PR TITLE
LPS-74212

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@shuyangzhou, reverting your commit, because it's breaking stuff in SF.

The reason I cannot always use StringUtil.splitLines is because of https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/util/StringUtil.java#L3982
This causes the indentation of the first line to get stripped.

We can:
1. Leave as is and use UnsyncBufferedReader
2. Add method StringUtil.splitLines with an extra parameter to make stripping indentation of first line configurable (kinda dumb, but it would work).
3. Change the method StringUtil.splitLines and never strip indentation of first line (I don't really get the benefit of that). We might (and probably will) break stuff elsewhere if we do this.

What do you think?

/cc @petershin

**Comment by shuyangzhou** [comment]
@hhuijser that StringUtil.splitLines should not have done that. But it is there already, we can not just remove it. I would prefer to create a new version of it, name it a bit differently, let's say splitByLines, which does not trim. And deprecate the old one, update all exist usages to the new one.

**Comment by hhuijser** [comment]
@shuyangzhou, makes sense, I'll take care of that. For the cases where we call it now, we do have to look case by case if that change would mess things up.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
