### PR TITLE
LPS-92299

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:reopen

**Comment by adolfopa** [comment]
SF issues unrelated to this pull.

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7f7c3cbdd7...0f5ba17be4

**Pull request closed without merging**
