### PR TITLE
LPS-159219 Use the correct type for Integer

### PR DESCRIPTION
**Pull request by guilhermedcamacho**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/18d6082929...370501f258

**Comment by brianchandotcom** [comment]
@guilhermedcamacho we need tests :)

**Comment by guilhermedcamacho** [comment]
I'm working on it @brianchandotcom :+1:

**Pull request closed without merging**
