### PR TITLE
LPS-82010 Change default locale provider to CLDR

### PR DESCRIPTION
**Pull request by jhendley**

### CODE REVIEW

**Comment by jpince** [comment]
ci:test @brianchiu @kyle-miho @vicnate5 locale provider change, not sure what kind of impact this will have

**Comment by vicnate5** [comment]
Thanks @jpince https://issues.liferay.com/browse/LRQA-49014

**Comment by jpince** [comment]
@vicnate5 @brianchiu any concerns with this pull? Joel said it's not a `7.2-must`, so if we need more time to evaluate, we can do so at a later time. Please reopen if this is good to merge.

**Comment by anthony-chu** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
@jpince Our concern with this pull is that it would introduce this bug for most users (before it was isolated to JDK11):
https://issues.liferay.com/browse/LPS-87191

**Comment by jpince** [comment]
@vicnate5 thanks!

**Pull request closed without merging**
