### PR TITLE
LPS-73397 Adding the test from the jira ticket to ensure this never happens again for message boards

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7813b5fc34...faa5f483b7

**Pull request closed without merging**
