### PR TITLE
LPS-171960 and LPS-171959 Check the form permissions depending on the view mode

### PR DESCRIPTION
**Pull request by Tim-Cao**
This is only for master.

https://issues.liferay.com/browse/LPS-171960
https://issues.liferay.com/browse/LPS-171959

@lfbesada

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/10769

**Comment by brianchandotcom** [comment]
@lfbesada is this p_l_mode namespaced?

		getPreviewLayoutURL.setParameter("p_l_mode", Constants.PREVIEW);

Seems off to do it like this?

**Comment by lfbesada** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@lfbesada just 1cbb34b351aa75c614226c7ed3ac66337c5e9910

**Pull request closed without merging**
