### PR TITLE
LPS-108138 | LPS-108514 buildLang

### PR DESCRIPTION
**Pull request by inacionery**
Nice job @gabrielpramos! 😄

### CODE REVIEW

**Comment by inacionery** [comment]
Hey @rodrigocunhaa

Do we have tickets to fix these flaws? WorkflowMetrics#ViewWorkloadByAssigneeCard 
 and WorkflowMetrics#ViewTopAsigneePerformance

Thanks!

**Comment by rodrigocunhaa** [comment]
Hi @inacionery 

I will investigate!

Thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/eca772ed80...6996a66891

**Pull request closed without merging**
