### PR TITLE
LPS-77686 Not needed

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0385dad623...4b4208c692

**Comment by brianchandotcom** [comment]
Nice job @jkappler @ealonso

**Pull request closed without merging**
