### PR TITLE
LPS-72221

### PR DESCRIPTION
**Pull request by Ithildir**
Hi,
Please let this pull finish.

Thank you!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/86672f7a8b...b6ea8a49a0

**Comment by brianchandotcom** [comment]
@Ithildir I assume we're still forcing them to be sorted right? Thx.

**Comment by brianchandotcom** [comment]
@juliocamarero fyi

**Comment by Ithildir** [comment]
Yes, they still have to be sorted.

**Comment by juliocamarero** [comment]
Great. Thank you! We will apply this in the next days to all our repos.

**Comment by juliocamarero** [comment]
cc @ruben-pulido

**Pull request closed without merging**
