### PR TITLE
LPS-70941

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@hhuijser I merged this. How come you did a fake gradle cache?

**Comment by brianchandotcom** [comment]
Merged.

**Comment by Ithildir** [comment]
Hi @hhuijser!

You don't need a `FAKE GRADLE CACHE` commit to test your SF:

- on CI for `master`, it already deploys the SF jar and then uses it
- locally: run `gradlew deploy` in the SF dir, then `ant format-source` or `gradlew formatSource -Pcom.liferay.source.formatter.ignore.local=false`

**Comment by hhuijser** [comment]
@Ithildir @brianchandotcom 

I did fake gradle cache because I also made changes to modules/sdk/gradle-plugins.
That one would not compile without it?

Please correct me if I am wrong. I just try stuff and see what works usually :)

**Comment by Ithildir** [comment]
Oh,  you're absolutely right! 👍

**Comment by hhuijser** [comment]
@Ithildir 

How come it still didn't compile properly? What did I do wrong?

**Comment by Ithildir** [comment]
In this case, you'd have to do:

1. `gradlew installCache updateFileVersions` in `modules/util/source-formatter`
2. commit changes
3. `gradlew installCache updateFileFileVersions` in `modules/sdk/gradle-plugins-source-formatter`
4. commit changes
5. `gradlew installCache updateFileFileVersions` in `modules/sdk/gradle-plugins`
6. commit changes
7. `gradlew installCache updateFileFileVersions` in `modules/sdk/gradle-plugins-defaults`
8. commit changes

**Comment by hhuijser** [comment]
Got it!

I'll make sure to write that down somewhere for next time...

**Pull request closed without merging**
