### PR TITLE
LPS-72343 Facet counts show hits for articles that user does not have permission to view

### PR DESCRIPTION
**Pull request by arboliveira**
Authors: @BryanEngler @arboliveira
Reviewer: @arboliveira

cc/ @Brandizzi please see https://github.com/brianchandotcom/liferay-portal/pull/50016/commits/2f8ec1071587ccde48479c84b4e408a11d7a8a84 and https://github.com/brianchandotcom/liferay-portal/pull/50016/commits/7b514d43900c6cca53b4db05ba051e2f12a2da91

cc/ @MarcellusTavares please see https://github.com/brianchandotcom/liferay-portal/pull/50016/commits/af344a114322768a342a75414010bc6cd5c4b4ac

https://issues.liferay.com/browse/LPS-72343

### CODE REVIEW

**Comment by arboliveira** [comment]
Test failures seem unrelated.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@adolfopa @sergiogonzalez see Adaptive Media flukes? Thx.

**Comment by brianchandotcom** [comment]
@arboliveira @BryanEngler 

getParentEntryClassName returns an Optional

The method name should reflect that. Please resend. Thx.

**Pull request closed without merging**
