### PR TITLE
LPS-117975 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LPS-117975

Original message from @petershin

> Hi Brian, the mergeLang task is used in a lot of commerce projects and its not cacheable.
> 
> I'll send pulls to see if all the usages can be safely replaced and then remove the task from the build.

### CODE REVIEW

**Comment by john-co** [comment]
ci:reopen

**Comment by john-co** [comment]
Reviewed tests in https://github.com/petershin/liferay-portal/pull/1131#issuecomment-665850517

Manually forwarding to avoid retesting large amount of passing tests again due to a known issue in upstream. https://issues.liferay.com/browse/LPS-118112 will follow up with quarantine.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d5b3948679...f02b3a07f3

**Comment by brianchandotcom** [comment]
thx @petershin trusting you!

**Pull request closed without merging**
