### PR TITLE
LRQA-35030 Account for multiple levels of poshi path inheritance

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-35030

### CODE REVIEW

**Comment by kevin-yen** [comment]
ci:reopen
ci:retest

**Comment by kevin-yen** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f8c28b0fe6...3d62c3b7ce

**Comment by brianchandotcom** [comment]
@lesliewong92 @pyoo47 see 3d62c3b7ce1a64fdd81735272708f01c49cae5b2

**Pull request closed without merging**
