### PR TITLE
LPS-101232 buildLang

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
//cc @pavel-savinov

**Comment by ruben-pulido** [comment]
//cc @ealonso <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/632a84bc94...97361b82c5

**Comment by brianchandotcom** [comment]
@ruben-pulido I think we have functional test failures, can you have someone fix them? Thx.

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
@kyle-miho, could you please take a look at those failing POSHIs? I couldn't reproduce that on my local machine.

**Pull request closed without merging**
