### PR TITLE
LPS-66420 Bump version

### PR DESCRIPTION
**Pull request by marcellustavares**
cc @leoadb

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@marcellustavares can you resend?

DDMFormFieldRuleType type / getType should not be named that.

Thx.

**Comment by marcellustavares** [comment]
@leoadb, could you resend?

**Comment by marcellustavares** [comment]
Also for the class attributes

**Comment by leoadb** [comment]
@marcellustavares OK

**Pull request closed without merging**
