### PR TITLE
LPS-60471 Use metal-dropdown in liferay-ui:icon-menu

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @brianchandotcom, I see the addDocument error failing consistently across PRs, so it shouldn't be related to this one.

About the PortalSmoke test, I've talked to @mairatma and @eduardolundgren and the warning error shouldn't be an issue. We'll look into it, but it shouldn't block getting this in. @sharonchoi, is there a way to ignore this particular warning? Also... which version of Firefox do we use in the CI for testing?

**Comment by mairatma** [comment]
Yes, the warning isn't an issue. It's complaining about a feature [babel](https://babeljs.io/) uses because of compatibility with IE <= 10, so it's necessary and it's not actually slow for us, specially since we're only doing this once, on first load.

**Comment by sharonchoi** [comment]
Hey @jbalsas I'll look into the addDocument test, it seems like a test fix that I will need to make. I'll ask @kenjiheigel about the PortalSmoke test failing from the warning, and if we can ignore it or not. CI should be using FF38 for testing.

**Comment by sharonchoi** [comment]
@jbalsas Nevermind...it looks like Roberto's pr here: https://github.com/brianchandotcom/liferay-portal/pull/35290 got merged, which caused the addDocument test failure. He'll be sending in a bug fix soon.

**Comment by brianchandotcom** [comment]
ci:retest I pushed up Roberto's changes, but I want to make sure the smoke test isn't real.

**Comment by brianchandotcom** [comment]
@jbalsas smoke broke twice :( @sharonchoi can you fix and resend? Or send to @kenjiheigel? Thx.

**Comment by sharonchoi** [comment]
@brianchandotcom ok will do. @kenjiheigel is out today, so I'll take a look.

**Comment by jbalsas** [comment]
Hey @brianchandotcom, the test indeed breaks, but afaict it is because it's doing a wrong assert on a browser-based warning message. We need to update the test to ignore these warning for now since:

- This is a known and accepted tradeoff we're doing in order to support IE10<
- The warning is Firefox-only
- It's not even an error

Thanks @sharonchoi and @kenjiheigel for looking into it!

**Comment by sharonchoi** [comment]
This should fix the PortalSmoke#Smoke test https://github.com/brianchandotcom/liferay-portal/pull/35338

**Comment by jbalsas** [comment]
Thanks a lot, @sharonchoi!!!

I've resent to https://github.com/brianchandotcom/liferay-portal/pull/35356 and it is ok now :relaxed:

**Pull request closed without merging**
