### PR TITLE
LPS-53894

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Please resend, why are we changing 6.2 too?

Also, can you sort the attributes alphabetically? max should go before min.

Thx

**Comment by brianchandotcom** [comment]
@awagnerur @mhan810 see my comment above. Thx.

**Comment by mhan810** [comment]
Brian, they need it for the EVP upgrade.  It's safe to make this change.
The schema changes are optional



*From:* Brian Chan [mailto:notifications@github.com]
*Sent:* Wednesday, April 8, 2015 10:45 AM
*To:* brianchandotcom/liferay-portal
*Cc:* Michael Han
*Subject:* Re: [liferay-portal] LPS-53894 (#25471)



@awagnerur <https://github.com/awagnerur> @mhan810
<https://github.com/mhan810> see my comment above. Thx.

--
Reply to this email directly or view it on GitHub
<https://github.com/brianchandotcom/liferay-portal/pull/25471#issuecomment-90956007>
.

**Comment by awagnerur** [comment]
Brian, thanks for your comment! The min and max occurrences are sorted logically throughout the files instead of alphabetically. Do you want me to change this sorting for all the descriptors to be alphabetical instead or was it a specific place where sorting was inconsistent?

**Comment by mhan810** [comment]
@awagnerur can you take care of the sorting and etc?  As long as you're not changing the meat of the schema, just cc me on the pr to bc

**Comment by awagnerur** [comment]
@mhan810 will do

**Pull request closed without merging**
