### PR TITLE
LPS-156293 Replace `href="javascript:;"` with `href="javascript:void(…

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
…0);"` for better compatibility between browsers

Based on https://github.com/liferay-frontend/liferay-portal/pull/2379#issuecomment-1163810155 manually forward

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:reopen

**Comment by georgel-pop-lr** [comment]
ci:reopen

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:open

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c140c1c8ba...de0a95d28e

**Pull request closed without merging**
