### PR TITLE
LPS-45934 Fix activities upgrade issue

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @dsanz

**Comment by sergiogonzalez** [comment]
cc/ @jhinkey regarding https://github.com/sergiogonzalez/liferay-portal/commit/2b3d27c0709db9ecd787a70f1f399c50582b76d1

**Comment by brianchiu** [comment]
Judging from later pulls (links below), this is probably not a flaky test failure.

The 623 Upgrade test is failing due to a bug.

The other 2 tests are likely UI changes.
https://github.com/brianchandotcom/liferay-portal/pull/36510
https://github.com/brianchandotcom/liferay-portal/pull/36520

**Comment by brianchiu** [comment]
623Upgrade - likely a bug (unrelated to this pull) that we are investigating. But I've removed that assertion for now.

CPSites / PGSitesdirectory - those tests have been removed from the PR tester for now.

**Comment by dsanz** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@dsanz please resend

SF

```
format-source:
     [java] Loading file:/Users/brian/dev/projects/github/liferay-portal/portal-impl/classes/system.properties
     [java] line break: ./portal-impl/src/com/liferay/portal/upgrade/v6_2_0/UpgradeSocial.java 378
     [java] line break: ./portal-impl/src/com/liferay/portal/upgrade/v6_2_0/UpgradeSocial.java 379
     [java] line break: ./portal-impl/src/com/liferay/portal/upgrade/v6_2_0/UpgradeSocial.java 446
     [java] line break: ./portal-impl/src/com/liferay/portal/upgrade/v6_2_0/UpgradeSocial.java 447
     [java] line break: ./portal-impl/src/com/liferay/portal/upgrade/v6_2_0/UpgradeSocial.java 504
     [java] line break: ./portal-impl/src/com/liferay/portal/upgrade/v6_2_0/UpgradeSocial.java 505
     [java] line break: ./portal-impl/src/com/liferay/portal/upgrade/v6_2_0/UpgradeSocial.java 553
     [java] line break: ./portal-impl/src/com/liferay/portal/upgrade/v6_2_0/UpgradeSocial.java 554
     [java] line break: ./portal-impl/src/com/liferay/portal/upgrade/v6_2_0/UpgradeSocial.java 611
     [java] line break: ./portal-impl/src/com/liferay/portal/upgrade/v6_2_0/UpgradeSocial.java 612
     [java] line break: ./portal-impl/src/com/liferay/portal/upgrade/v6_2_0/UpgradeSocial.java 727
     [java] line break: ./portal-impl/src/com/liferay/portal/upgrade/v6_2_0/UpgradeSocial.java 728
     [java] line break: ./portal-impl/src/com/liferay/portal/upgrade/v6_2_0/UpgradeSocial.java 771
     [java] line break: ./portal-impl/src/com/liferay/portal/upgrade/v6_2_0/UpgradeSocial.java 772
     [java] line break: ./portal-impl/src/com/liferay/portal/upgrade/v6_2_0/UpgradeSocial.java 831
     [java] line break: ./portal-impl/src/com/liferay/portal/upgrade/v6_2_0/UpgradeSocial.java 832
```

Also, 

```
		updateJournalActivities();
		updateSOSocialActivities();
		updateActivities();
```

Does order matter or can we sort it? If one group has to go after another, use a line break to make that knowmn.

@sergiogonzalez fyi.

Please resend. Thx.

**Pull request closed without merging**
