### PR TITLE
LPS-63791 Update Tomcat from 8.0.30 to 8.0.32

### PR DESCRIPTION
**Pull request by alee8888**

### CODE REVIEW

**Comment by alee8888** [comment]
This is a resend of https://github.com/brianchandotcom/liferay-portal/pull/36860#issuecomment-190469243. Forgot to include git-commit-plugins, sorry.

**Comment by alee8888** [comment]
@brianchandotcom 
The changes I made shouldn't have caused this functional test failure.

@vicnate5
Can you please take another look at CPDynamicdatalists#AddDisplayTemplateVelocity that failed? I recalled seeing a fix go in but it looks to have gotten possibly unstable again. I have created the following LRQA ticket and assigned it to you. Can you please prioritize this higher? Thank you!
https://issues.liferay.com/browse/LRQA-22738

**Comment by vicnate5** [comment]
@alee8888 The test is failing at a later point. I am working on a fix right now.

**Comment by vicnate5** [comment]
The failing test Passed on the previous pull for this change https://test-1-14.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1175/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/functional-tomcat8-mysql56-jdk7/1/

**Comment by vicnate5** [comment]
@alee8888 Sent fix https://github.com/brianchandotcom/liferay-portal/pull/36928

**Pull request closed without merging**
