### PR TITLE
LPS-190734 Exclude props with default value when creating pages

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://liferay.atlassian.net/browse/LPS-190734

@DiegoHu97

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/12949

**Comment by brianchandotcom** [comment]
@ling-alan-huang we need to auto SF this.

**Comment by brianchandotcom** [comment]
@ling-alan-huang ignore my comment, my bad! I thought this was something else.

**Pull request merged**
