### PR TITLE
LPS-68923 KB DataHandlers

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@Preston-Crary please resend? I already merged in https://github.com/brianchandotcom/liferay-portal/pull/44595

**Comment by Preston-Crary** [comment]
@brianchandotcom Oh, didn't see that.  We're good then.

**Comment by jpince** [comment]
@Preston-Crary have all the needed commits been backported? I saw at least some in [ee-7.0.x](https://github.com/liferay/liferay-portal-ee/commits/ee-7.0.x)

**Comment by Preston-Crary** [comment]
@jpince Yes.

**Comment by jpince** [comment]
@Preston-Crary great, thank you for your work!

**Comment by jpince** [comment]
@brianchandotcom can you please publish?

**Pull request closed without merging**
