### PR TITLE
LPS-89415 Apply new logic for only post methods

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
@brianchandotcom - Let me know if you want me to send this to Victor Galan instead to see where the new check should be applied.

**Comment by brianchandotcom** [comment]
@victorg1991  this is fixed in upstream now.

**Comment by victorg1991** [comment]
Thanks a lot @petershin I will review the test to use this new methods

**Comment by victorg1991** [comment]
I think it's not correct yet. Look at this for example:

our code:
```
@Override
	protected Comment testPostBlogPostingComment_addComment(Comment comment)
		throws Exception {

		BlogsEntry blogsEntry = _addBlogsEntry();

		return invokePostBlogPostingComment(blogsEntry.getEntryId(), comment);
	}
```

generated: 
```
protected Comment testPostBlogPostingComment_addComment(Comment comment)
		throws Exception {

		return invokePostCommentComment(
			testGetCommentCommentsPage_getParentCommentId(), comment);
	}
```

**Pull request closed without merging**
