### PR TITLE
LPS-89546 When Page Versioning is active, use modifiedDate value of the wrapped LayoutRevision, instead of the Layout.

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test:staging

**Comment by jpince** [comment]
@vendeltoreki @matethurzo I am concerned about the int test failures in this pull (both test suites), but I'm not sure if it's related to this pull. can you please take a look?
```
     [exec] 12:16:49,583 ERROR [RMI TCP Connection(2)-127.0.0.1][JDBCExceptionReporter:234] Unknown column 'DDLRecordSet.description_' in 'where clause'
     [exec] Unknown column 'DDLRecordSet.description_' in 'where clause'
     [exec] 12:16:49,587 ERROR [RMI TCP Connection(2)-127.0.0.1][GroupLocalServiceImpl:4213] Unable to delete data for portlet null in group 38244
     [exec] com.liferay.exportimport.kernel.lar.PortletDataException: com.liferay.portal.kernel.dao.orm.ORMException: org.hibernate.exception.SQLGrammarException: could not execute query
```
https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/218677/AXIS_VARIABLE=0,label_exp=!master/consoleFull
https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/239674/AXIS_VARIABLE=0,label_exp=!master/consoleFull

I also see this error that I don't see in upstream `Unable to include JSP /article/structure_template.jsp`

**Comment by jpince** [comment]
@vendeltoreki @matethurzo nevermind, these errors are all in upstream, hopefully they will be fixed by https://github.com/brianchandotcom/liferay-portal/pull/67880

**Comment by matethurzo** [comment]
@jpince lot of errors on CI today but unrelated to what we have been doing

**Comment by jpince** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/573b046d4f...818072625e

**Pull request closed without merging**
