### PR TITLE
Revert "LPS-76237 Using the right blogs model class name"

### PR DESCRIPTION
**Pull request by shuyangzhou**
This reverts commit 41cdc363e6f867899e63cd91400344a20dbbaeed.

@brianchandotcom this is fixing another CI failure. It got merged in by https://github.com/brianchandotcom/liferay-portal/pull/53431

The subrepo change https://github.com/liferay/com-liferay-adaptive-media/commit/143085c8d49ebc46784094d208a694496bc405e5#diff-2240d7120a23a5437d9e8f230c01ebeb is not in, but the portal one got merged. That's why this is failing.

At this phase considering CI is in really bad shape. We should not force merge subrepo, as it might add other issues.

QA must provide a way to synchronously change matching parts from portal and subrepos, otherwise we can never safely merge this kind of changes.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
CC @sergiogonzalez @4lejandrito

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by shuyangzhou** [comment]
@sergiogonzalez @4lejandrito you need to redo your change after CI is getting stable. Unfortunately we don't have a git-commit-subrepos file yet to allow you make synced changes in PR. You just have to make sure everything gets stable first, then tell Brian your changes are safe to merge. And the 2 pulls must be merged together to prevent it from breaking other people's pulls.

**Comment by 4lejandrito** [comment]
Hi @shuyangzhou, 

Thanks for spotting this issue.

The problem here is that our master branch in adaptive media is not in sync with liferay-portal. 

I don't really know how subrepo syncing works (who, why, when, how often...) but we must make sure that the next time adaptive media and portal are synced your revert is reverted back so everything is consistent again. 

How can we know when this happens so that we can remind you to undo the revert?

Thansk!

**Comment by shuyangzhou** [comment]
@4lejandrito you will just have to pay attention to the pulls you send out. Making sure it is all merged properly, and after that upstream is still in good shape. It is a lot of extra manual work, but that the price for subrepos.

**Pull request closed without merging**
