### PR TITLE
LPS-172794

### PR DESCRIPTION
**Pull request by jeffwu0724**

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:reopen

**Comment by jeffwu0724** [comment]
Hi @brianchandotcom , may I ask what is the "rest-client" you refer to, please? Does it mean all the "*-client" module that we add `compileOnly project(":core:petra:petra-function")`? 
If so, in this case, will it be better to use for loop instead of TransformUtil?
Thanks!

**Comment by brianchandotcom** [comment]
*-client is meant to be used outside of the portal. To keep things simple, we don't want any dependencies except for Java 8. @jeffwu0724

**Comment by jeffwu0724** [comment]
@brianchandotcom copy that, thank you sir! I will fix it and resend.

**Pull request closed without merging**
