### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
Unrelated failures: https://github.com/hhuijser/liferay-portal/pull/5673

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6476d7e1cb...ab5c895f94

**Comment by brianchandotcom** [comment]
@hhuijser match method name see ffa6b91aaff96394fb4e1f1e0b7ac31e0cd84f1f

**Pull request closed without merging**
