### PR TITLE
LPS-86332 Use latest snapshot

### PR DESCRIPTION
**Pull request by petershin**
@csierra

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:reopen

**Comment by petershin** [comment]
Fixed conflicts: https://github.com/brianchandotcom/liferay-portal/pull/64254

**Comment by brianchandotcom** [comment]
Merged. Thank you.

View just my changes: https://github.com/brianchandotcom/liferay-portal/compare/petershin:538cec26bb...d35d263cd2
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1b06d3691b...d35d263cd2

**Comment by brianchandotcom** [comment]
@codyhoag merged this, please review changelog.

**Pull request closed without merging**
