### PR TITLE
LRCI-766 Update poshi runner version to 1.0.243

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRCI-766

### CODE REVIEW

**Comment by kenjiheigel** [comment]
@brianchandotcom, please publish the poshi runner gradle plugin and gradle defaults plugin after merging. Thank you!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2bb748e57b...f62428024c

**Comment by brianchandotcom** [comment]
@kenjiheigel I updated it up to 7.0.x. What about the older 6.2 6.1 branches?

**Comment by kenjiheigel** [comment]
@brianchandotcom, there's no need actually. A while back, I updated the legacy branches for Poshi to use the latest gradle plugins version, so once you release on master, every branch is automatically pulling the whatever latest version I've specified in the poshi runner extension.

**Pull request closed without merging**
