### PR TITLE
LPS-64370 replace legacy property with new api

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Hey @hhuijser

it seems there is a problem with the deprecated javadocs in constants with the source formatter. thank you!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/69575a3b74...447373e4c1

**Comment by brianchandotcom** [comment]
@juliocamarero @adolfopa please see my changes in upstream.

@juliocamarero I easily fixed the SF.. it was just a typo.

I would also recommend moving asset categories validator to its own module. Can you do that @juliocamarero ? That'll mean I can keep incrementing it without incrementing all of asset-categories-service.

Thx

**Pull request closed without merging**
