### PR TITLE
LPS-65114 Hides unnecessary outline for element

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:stop (upstream has some DXP/ee issues, will retrigger)

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by sharonchoi** [comment]
The ApplicationdisplaytemplatesUsecase#AddRSSADTViaPortletConfiguration failure is unrelated and has been failing multiple pulls. 
https://testray.liferay.com/home/-/testray/case_results/40139533

Test has been disabled at head:
liferay@6fd2f84

WEM QA will look into the issue and restore the test LRQA-24557.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a0fe0d8836...a17a83f5c9

**Pull request closed without merging**
