### PR TITLE
LPS-78292 Always fetch head revision during publishing the layout, regardless of user's recent objects

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by jpince** [comment]
@Ithildir do you know why CI is asking for this? `[exec] Caused by: org.gradle.api.GradleException: Please create marker file /opt/dev/projects/github/liferay-portal/modules/test/shrinkwrap-osgi/.lfrbuild-portal`

**Comment by Ithildir** [comment]
Gradle is complaining because a module contains an integration test which depends from `test/shrinkwrap-osgi`, but `test/shrinkwrap-osgi` is never deployed during `ant all`. Is that okay? Otherwise, we have to add an exception in https://github.com/liferay/liferay-portal/blob/master/modules/sdk/gradle-plugins-defaults/src/main/java/com/liferay/gradle/plugins/defaults/internal/LiferayCIPlugin.java#L303.

**Pull request closed without merging**
