### PR TITLE
LPS-61577 format-source

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
@brianchandotcom This pull changes the name of an annotation that is used in SourceFormatter. I have changed source formatter (in a separate commit so that it's easy to find), but the CI will fail since it doesn't have that change installed yet.

Also. Once you merge this in, could you publish version 1.0.0 of portal-metatype? We need that to perform further changes.

@migue This is the pull we reviewed today. It includes the final naming changes we discussed
@rotty3000 These are the changes to avoid undesired dependencies from portal to apps that we talked about today

**Comment by brianchandotcom** [comment]
@JorgeFerrer compile error.

**Comment by migue** [comment]
Seems not all the modules have been updated to reflect the new packaging

On 15 January 2016 at 01:19, Brian Chan <notifications@github.com> wrote:

> Closed #34416
> <https://github.com/brianchandotcom/liferay-portal/pull/34416>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/34416#event-515660890>
> .
>



-- 
Un saludo,

Migue

http://migue.github.io

**Comment by JorgeFerrer** [comment]
Argh! Sorry about that.

It's weird. It seems the rebase that I did last night to fix the merge error has lost many of the changes. Have no idea how that has happened but will need to redo it more carefully.

It will have to be on Monday since I gotta head to the airport right now.

**Comment by JorgeFerrer** [comment]
It was not such a big deal after all. Just a few new classes referencing the annotation that I had renamed that were added after I did my changes.

New pull resent as https://github.com/brianchandotcom/liferay-portal/pull/34565

**Pull request closed without merging**
