### PR TITLE
LPS-106196 Select conjunction

### PR DESCRIPTION
**Pull request by dgarciasarai**
/cc @andresfulla

### CODE REVIEW

**Comment by dgarciasarai** [comment]
I'm going to send another PR fixing the tests.

**Comment by dgarciasarai** [comment]
CI passing here https://github.com/dgarciasarai/liferay-portal/pull/138. It's this pull with tests fixed (https://github.com/brianchandotcom/liferay-portal/pull/82428)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cbf8a24844...cc4a7b877b

**Comment by dgarciasarai** [comment]
Thanks!

**Pull request closed without merging**
