### PR TITLE
LPS-92053 Override getEntityFields for resources with creator schema

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
@jpince these failures are related? Thanks!

**Comment by jpince** [comment]
@inacionery no, the upgrade failures are ci-related

**Comment by jpince** [comment]
@inacionery but now there is a merge conflict :(

**Comment by inacionery** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/73959

**Pull request closed without merging**
