### PR TITLE
LPS-50795

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-50795](https://issues.liferay.com/browse/LPS-50795).<br><br>@JorgeFerrer

### CODE REVIEW

**Comment by kiyoshilee** [comment]
@drewbrokke in order for your pull request to be tested you will need to publicize your association with the liferay organization on your github profile. Please see this <a href="https://help.github.com/articles/publicizing-or-concealing-organization-membership/"> link</a> for details on how to do so.

**Comment by drewbrokke** [comment]
@kiyoshilee I have updated my membership visibility. Thanks for the heads up!

**Comment by kiyoshilee** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ce3fceee17...486a2f5c31

**Comment by mikakoivisto** [comment]
@drewbrokke In the future please at least CC me on the pull request if you are not sending it to me for review as I asked so that I know to look it over. We should apply the same thing for password reset as was discussed in email. Are you doing this in some other ticket?

**Comment by drewbrokke** [comment]
@mikakoivisto Thanks for pointing that out. My apologies. I'll make sure to CC you on any relevant pull I don't send to you directly. I'll create a new ticket for applying the changes to the password resets, then send you a pull.

**Comment by drewbrokke** [comment]
@mikakoivisto Here is the new ticket: https://issues.liferay.com/browse/LPS-53691.

**Pull request closed without merging**
