### PR TITLE
LPS-84219 We don't always want to default to true, only if we are importing a layout

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by jkappler** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:test:relevant @jkappler I know the semver failure isn't related, just want to retest to see if the test is flaky...

**Comment by jkappler** [comment]
Got it @jpince, thanks!

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
