### PR TITLE
LPS-101411 buildLang

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
@boton

**Comment by 4lejandrito** [comment]
@ambrinchaudhary

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/78834.

**Pull request closed without merging**
