### PR TITLE
Upgrade Process: Disable upgrade execution on portal startup

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7e058c0fe8...517b23f03e

**Comment by brianchandotcom** [comment]
@cgoncas @migue please see my renames in 517b23f03e37ed9b3b784d921aa5e1e674700758

**Comment by ZoltanTakacs** [comment]
Thank you @migue. It's been merged to 7.0.x.

Please note that the backport workflow has been changed for the RCs. 
For the details please see @jhendley 's email or refer to this [document](https://docs.google.com/document/d/1A-EoPvI1KDDpUH2PAlKmpgUDb_2RFM4iwpB_4loQHFk/edit).

Thank you,
Zoltán

**Pull request closed without merging**
