### PR TITLE
Lps 75391

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by ctampoya** [comment]
ci:reopen

**Comment by ctampoya** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7206f095ab...07dcccbfa3

**Comment by brianchandotcom** [comment]
@shuyangzhou @tinatian I reverted the build.gradle change in 07dcccbfa39ec98360759681efb303ca7891fac6

I don't see we would, in a compile dependency, ever specify a micro version?

**Comment by tinatian** [comment]
@brianchandotcom Yes, you are right!  Thanks Brian!

**Pull request closed without merging**
