### PR TITLE
LPS-74544

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:test

**Comment by hhuijser** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by petershin** [comment]
@hhuijser - Sent pulls to update the subrepos:

https://github.com/liferay/com-liferay-adaptive-media/pull/207
https://github.com/liferay/com-liferay-analytics/pull/49
https://github.com/liferay/com-liferay-poshi-runner/pull/1
https://github.com/liferay/com-liferay-osb-faro-private/pull/232
https://github.com/liferay/com-liferay-osb-pulpo-engine-contacts-private/pull/298
https://github.com/liferay/com-liferay-osb-testray-private/pull/17
https://github.com/liferay/com-liferay-pulpo-connector-de-private/pull/122

I'll send one more pull to update the [com-liferay-osb-lcs-private](https://github.com/liferay/com-liferay-osb-lcs-private) subrepo

**Pull request closed without merging**
