### PR TITLE
LPS-108231 Suppress SF error in CCR app.bnd temporarily

### PR DESCRIPTION
**Pull request by lipusz**
Hey Brian,

This is related to https://github.com/brianchandotcom/liferay-portal/pull/84344#issuecomment-584240063.

Thanks,
Tibor

/cc @BryanEngler @jpince

### CODE REVIEW

**Comment by lipusz** [comment]
I believe the relevant and stable tests could be stopped here to save time and resources.

**Comment by brianchandotcom** [comment]
ci:test:stop

**Comment by brianchandotcom** [comment]
@lipusz how is the other module being excluded? Please exclude it the same way and resend.

Not merging.

**Comment by lipusz** [comment]
Brian: I copy-pasted the "pattern" from the elasticsearch7 module. See

https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-search-elasticsearch7/source-formatter-suppressions.xml#L5

Sent from mobile
--
Project Manager, Search & App Security SME @ Product Care

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
Let me know if you still want me to handle it differently. Thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a80635d478...f4e6de8611

**Comment by brianchandotcom** [comment]
My bad @lipusz 

I ran "git grep BNDBundleCheck" and saw the one instance but I was expecting two because I thought I had your branch open.

My bad. Merged.

**Comment by lipusz** [comment]
Thanks! :-)

**Pull request closed without merging**
