### PR TITLE
LPS-64027 Site Role with General Permissions cannot access those options for those portlets in Site Administration

### PR DESCRIPTION
**Pull request by topolik**
https://issues.liferay.com/browse/LPS-64027

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ef04d2232b...2abab8ca3f

**Comment by brianchandotcom** [comment]
@drewbrokke please coordinate with QA on this. They need to add a functional test.

**Comment by xbrianlee** [comment]
@drewbrokke @brianchandotcom
I've created the following new automated test ticket regarding for this bug.
https://issues.liferay.com/browse/LRQA-24683

**Comment by drewbrokke** [comment]
Thanks @xbrianlee!

**Pull request closed without merging**
