### PR TITLE
LPS-106321 Cleanup portal-dao-db build.gradle

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/650d0f7deb...591a9cb6b3

**Comment by brianchandotcom** [comment]
@shuyangzhou I'm reverting this.. compile failure is real..

See https://test-1-23.liferay.com/job/test-portal-testsuite-upstream(master)/146/console

Happening in upstream.

**Comment by shuyangzhou** [comment]
This is weird, anything special about this module's compile on CI? It works fine locally, and it is the only one doing this special thing which is some kind of leftover.
@petershin

**Comment by shuyangzhou** [comment]
@petershin it must be caused by the .lfrbuild-app-server-lib. somehow the module was compiled before portal kernel and portal important snapshots were installed. Can you find out why this is happening? And make sure the snapshot installation happenings first?

**Comment by petershin** [comment]
@shuyangzhou - See https://github.com/brianchandotcom/liferay-portal/pull/82492

**Comment by shuyangzhou** [comment]
Thanks @petershin !

**Pull request closed without merging**
