### PR TITLE
LPS-67352

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@brianchandotcom

I didn't force using curly braces when the lambda expression goes over single line.
SF is not smart enough to know when it is a function and requires to return a value.
See PostgreSQLTransformerLogic.java

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@hhuijser I thought about it some more, and for

modules/apps/foundation/portal-search/portal-search-web/src/main/java/com/liferay/portal/search/web/internal/search/request/SearchRequestImpl.java

```
		SearchSettingsImpl searchSettingsImpl = new SearchSettingsImpl(
			searchContext);

		_searchSettingsContributors.forEach(
			searchContributor -> searchContributor.contribute(
				searchSettingsImpl));
```

I think if we treat -> like an =, it does make sense and it 's OK the way it was.

I do prefer the way it is now vs.

```
		SearchSettingsImpl searchSettingsImpl = new SearchSettingsImpl(
			searchContext);

		_searchSettingsContributors.forEach(
			searchContributor ->
				searchContributor.contribute(searchSettingsImpl));
```

Can you resend, and also send me a backport if there are still changes? Thx.

**Comment by hhuijser** [comment]
@brianchandotcom, will resend

**Pull request closed without merging**
