### PR TITLE
LPS-68670 Move test to blogs-service

### PR DESCRIPTION
**Pull request by shuyangzhou**
@tomwang2011 backport please.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pyoo47 what happened here? I've seen this type of error a few times now.

**Comment by shuyangzhou** [comment]
```
     [exec] com.liferay.source.formatter.SourceFormatterTest > testSourceFormatter STARTED
     [exec] 
     [exec] com.liferay.source.formatter.SourceFormatterTest > testSourceFormatter STANDARD_OUT
     [exec]     Loading jar:file:/opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.impl/2.6.0/51dd0d720f3bb4aa9be024b48d73b69152bc93a9/com.liferay.portal.impl-2.6.0.jar!/system.properties
     [exec]     Loading jar:file:/opt/dev/projects/github/liferay-portal/bundles/tomcat-8.0.32/webapps/ROOT/WEB-INF/lib/portal-impl.jar!/system.properties
     [exec]     Loading file:/opt/dev/projects/github/liferay-portal/bundles/tomcat-8.0.32/webapps/ROOT/WEB-INF/classes/system-ext.properties
Build timed out (after 120 minutes). Marking the build as aborted.
Build was aborted
Recording test results
```
SF test timeout. Not related to this pull. It is a known problem, just don't have the time to work on it yet.

**Comment by pyoo47** [comment]
One of the modules-unit-jdk8 axes aborted because sourceformatter froze and the build timed out.

```
     [exec] com.liferay.source.formatter.SourceFormatterTest > testSourceFormatter STARTED
     [exec] 
     [exec] com.liferay.source.formatter.SourceFormatterTest > testSourceFormatter STANDARD_OUT
     [exec]     Loading jar:file:/opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.impl/2.6.0/51dd0d720f3bb4aa9be024b48d73b69152bc93a9/com.liferay.portal.impl-2.6.0.jar!/system.properties
     [exec]     Loading jar:file:/opt/dev/projects/github/liferay-portal/bundles/tomcat-8.0.32/webapps/ROOT/WEB-INF/lib/portal-impl.jar!/system.properties
     [exec]     Loading file:/opt/dev/projects/github/liferay-portal/bundles/tomcat-8.0.32/webapps/ROOT/WEB-INF/classes/system-ext.properties
Build timed out (after 120 minutes). Marking the build as aborted.
Build was aborted
Recording test results
```

**Comment by shuyangzhou** [comment]
Most likely it is some kind of deadlock, maybe it is better to have @hhuijser check on it first, I have a very long queue now. It is going to take a long time before I can get on to it.

**Comment by brianchandotcom** [comment]
@hhuijser please fix deadlock. I've seen it a few times. Merged. Thx.

**Comment by hhuijser** [comment]
Hey @shuyangzhou 
I have seen the issue on the CI server a number of times, but never experienced the deadlock on my machine. Any suggestions on how to go about it regarding debugging this?

**Pull request closed without merging**
