### PR TITLE
LPS-64991

### PR DESCRIPTION
**Pull request by Ithildir**
Hi!
In this pull, I re-added the SDK zip without dependencies in order to avoid the download problems in China. Then some Gradle code parses the `ivy.xml` files and copies the jars from the `.gradle` dir.

What do you think of this approach? In addition, maybe we could also consider the SDK zip as a Gradle dependency: we publish it and let Gradle download it and cache it in the `.gradle` dir...

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 seems to have hung?

**Comment by pyoo47** [comment]
It looks like it ran into an out of memory error while generating the GitHub message. I'm going to ci:retest to see if it happens again.

**Comment by pyoo47** [comment]
@Ithildir It appears that there was a huge log file (over 300 MB) generated during the test at http://test-1-10/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=3,label_exp=!master/1907/. The job variant is functional-tomcat8-mysql56-jdk7/6. GitHubMessageUtil attempted to load the log file into memory so it could generate a code snippet but ran out of memory due to its large size.

Here's the first stack trace that got printed by portal in the log.
```
     [exec] 11-May-2016 00:18:56.803 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
     [exec] 11-May-2016 00:18:56.803 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 161564 ms
     [exec] 00:19:01,366 ERROR [http-nio-8080-exec-1][FreeMarkerManager:193] Unable to add taglib portlet to context
     [exec] FreeMarker template error:
     [exec] freemarker.template.TemplateModelException: Error while loading tag library for URI "/META-INF/liferay-portlet.tld" from TLD location "servletContext:/META-INF/liferay-portlet.tld"; see cause exception.
     [exec] 	at freemarker.ext.jsp.TaglibFactory.get(TaglibFactory.java:260)
     [exec] 	at com.liferay.portal.template.freemarker.FreeMarkerManager$TaglibFactoryWrapper.get(FreeMarkerManager.java:633)
     [exec] 	at com.liferay.portal.template.freemarker.FreeMarkerManager.addTaglibSupport(FreeMarkerManager.java:189)
     [exec] 	at com.liferay.taglib.util.ThemeUtil.doIncludeFTL(ThemeUtil.java:274)
     [exec] 	at com.liferay.taglib.util.ThemeUtil.doDispatch(ThemeUtil.java:157)

...

     [exec] Caused by: java.io.IOException: Resource not found: servletContext:/META-INF/liferay-portlet.tld
     [exec] 	at freemarker.ext.jsp.TaglibFactory$ServletContextTldLocation.newResourceNotFoundException(TaglibFactory.java:1249)
     [exec] 	at freemarker.ext.jsp.TaglibFactory$ServletContextTldLocation.getInputStream(TaglibFactory.java:1238)
     [exec] 	at freemarker.ext.jsp.TaglibFactory$Taglib.parseToTagsAndFunctions(TaglibFactory.java:1505)
     [exec] 	at freemarker.ext.jsp.TaglibFactory$Taglib.<init>(TaglibFactory.java:1490)
     [exec] 	at freemarker.ext.jsp.TaglibFactory.loadTaglib(TaglibFactory.java:846)
     [exec] 	at freemarker.ext.jsp.TaglibFactory.get(TaglibFactory.java:256)
     [exec] 	... 239 more
     [exec] 00:19:01,372 ERROR [http-nio-8080-exec-1][FreeMarkerManager:
```

**Comment by Ithildir** [comment]
I'll rebase and resend!

**Comment by Ithildir** [comment]
@pyoo47: do you think all those errors were caused by my pull, or you've seen them already?

**Comment by pyoo47** [comment]
This is the only pull where I’ve seen this happen so far.

Peter

**Comment by Ithildir** [comment]
Very strange, because I already tried in another pull and it didn't break so badly :sweat_smile: I'll test it locally once again! Thank you! :blush:

**Comment by Ithildir** [comment]
Rebased and sent to https://github.com/brianchandotcom/liferay-portal/pull/39685.

**Pull request closed without merging**
