### PR TITLE
LPS-57362 Update test

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:retest

**Comment by marcellustavares** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9493eb7f36...61fd847332

**Comment by brianchandotcom** [comment]
@BryanEngler I merged this in, but can you update the test?

You should test for Name1 and name1 (to ensure that it's not only picking up a lower cased duplicate)

Thx

**Pull request closed without merging**
