### PR TITLE
LPS-79700 SF

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@pyoo47 what is this error?

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by pyoo47** [comment]
@brianchandotcom This appears to be a race condition. I've created a ticket to address it https://issues.liferay.com/browse/LRQA-40608

**Pull request closed without merging**
