### PR TITLE
LPS-56017 due to current dependencies deploy this to modules until refactor happens

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
That's a known random failure. I'll merge this in and work with Shuyang to fix it.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f9409d328e...0236f2553d

**Comment by brianchandotcom** [comment]
@rotty3000 can you double check my tiny changes in upstream? Thx.

**Pull request closed without merging**
