### PR TITLE
LPS-71763 replace instances of xlink:href with data-href to avoid cross origin errors

### PR DESCRIPTION
**Pull request by robframpton**
/cc @Ithildir @jbalsas

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@jbalsas please backport? Thx.

**Comment by Robert-Frampton** [comment]
@jbalsas I'll take care of it

**Comment by jbalsas** [comment]
Thanks @Robert-Frampton!

**Pull request closed without merging**
