### PR TITLE
LPS-102062 Fix.

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:reopen

**Comment by cgoncas** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b8214fc6ab...e32cde275c

**Comment by brianchandotcom** [comment]
@cgoncas great job on the test!

**Pull request closed without merging**
