### PR TITLE
master-qa-19706

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LRQA-19706

### CODE REVIEW

**Comment by evannagayama** [comment]
will update right now

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/32d4bd7983...409c0377d6

**Comment by brianchandotcom** [comment]
@evannagayama isn't this just a workaround?

**Comment by evannagayama** [comment]
@brianchandotcom yes it is for now, but it's a fluke that's only happening in the pr tester. It can't be reproduced on our end and a the same time it's not a very important assertion. I emailed Shuyang about it to see if he has any insights.

**Comment by brianchandotcom** [comment]
It must be some race condition either with the browser .. or for how things are loaded via OSGi which a customer could end up seeing. I think it may be important becaues of how the sessions are talking to each other/passing the message around. So it may be real bug in the backend. 

fyi @shuyangzhou

**Pull request closed without merging**
