### PR TITLE
LRQA-80963 TF

### PR DESCRIPTION
**Pull request by gaborlovasdotcom**
[LRQA-80963](https://liferay.atlassian.net/browse/LRQA-80963)

### CODE REVIEW

**Comment by gaborlovasdotcom** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@gaborlovasdotcom @JoyceWang08211 this feels out of place

```
	<target name="return-head-info">
		<exec executable="curl" outputproperty="curl.output">
			<arg value="-X" />
			<arg value="HEAD" />
			<arg value="-I" />
			<arg value="${baseURL}" />
		</exec>

		<echo file="${liferay.home}/head-info.txt">${curl.output}</echo>
	</target>
```

Can't we just use Poshi's JSONCurlUtil ?

Please resend.

**Comment by JoyceWang08211** [comment]
> JSONCurlUtil

Hi @brianchandotcom, [JSONCurlUtil](https://github.com/liferay/liferay-portal/blob/master/modules/test/poshi/poshi-runner/src/main/java/com/liferay/poshi/runner/util/JSONCurlUtil.java) doesn't support HEAD request.

**Comment by JoyceWang08211** [comment]
> @gaborlovasdotcom @JoyceWang08211 this feels out of place
> 
> ```
> 	<target name="return-head-info">
> 		<exec executable="curl" outputproperty="curl.output">
> 			<arg value="-X" />
> 			<arg value="HEAD" />
> 			<arg value="-I" />
> 			<arg value="${baseURL}" />
> 		</exec>
> 
> 		<echo file="${liferay.home}/head-info.txt">${curl.output}</echo>
> 	</target>
> ```
> 
> Can't we just use Poshi's JSONCurlUtil ?
> 
> Please resend.

Hi @brianchandotcom,
As [JSONCurlUtil](https://github.com/liferay/liferay-portal/blob/master/modules/test/poshi/poshi-runner/src/main/java/com/liferay/poshi/runner/util/JSONCurlUtil.java) doesn't support HEAD request, the curl will be executed twice when we use JSONCurlUtil to send HEAD request.
e.g. [Jenkins log](https://testray.liferay.com/reports/production/logs/2023-06/test-1-26/test-portal-acceptance-pullrequest(master)/9678/functional-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz?authuser=0):

     [exec]     Executing commands: curl -X POST -X 'HEAD' -I http://localhost:8080
     [exec]     HTTP/1.1 301 
     [exec]     X-Content-Type-Options: nosniff
     [exec]     X-Frame-Options: SAMEORIGIN
     [exec]     Set-Cookie: JSESSIONID=685CC00630243A55DE10B25E29AAF5A0; Path=/; HttpOnly
     [exec]     Location: http://localhost:8080/web/guest
     [exec]     Content-Type: text/html;charset=ISO-8859-1
     [exec]     Transfer-Encoding: chunked
     [exec]     Date: Wed, 07 Jun 2023 06:54:14 GMT
     [exec] 
     [exec]     Finished executing commands.
     [exec] 
     [exec]     Content-Security-Policy: img-src domain.liferay.com
     [exec]     HTTP/1.1 301 
     [exec]     X-Content-Type-Options: nosniff
     [exec]     X-Frame-Options: SAMEORIGIN
     [exec]     Set-Cookie: JSESSIONID=685CC00630243A55DE10B25E29AAF5A0; Path=/; HttpOnly
     [exec]     Location: http://localhost:8080/web/guest
     [exec]     Content-Type: text/html;charset=ISO-8859-1
     [exec]     Transfer-Encoding: chunked
     [exec]     Date: Wed, 07 Jun 2023 06:54:14 GMT
     [exec] 
     [exec]     Finished executing commands.
    Then means it will return two responses as above. Poshi will retrieve the first response but we need to compare the expected CSP header(aka Content-Security-Policy: img-src domain.liferay.com) with the second response.
That's the reason why it failed on Jenkins: https://testray.liferay.com/home/-/testray/case_results/2342707448 
cc @gaborlovasdotcom

**Comment by brianchandotcom** [comment]
@gaborlovasdotcom @JoyceWang08211 I just added support https://github.com/brianchandotcom/liferay-portal/commit/d7cba7c5037f0dc5f40bdbb9b14f0575b565ca9d

I prefer to improve our tools rather than working around them. Making an Ant call when can just do it all in Poshi is not ideal.

Work with the Poshi team to update to the latest runner.

**Comment by JoyceWang08211** [comment]
> @gaborlovasdotcom @JoyceWang08211 I just added support [d7cba7c](https://github.com/brianchandotcom/liferay-portal/commit/d7cba7c5037f0dc5f40bdbb9b14f0575b565ca9d)
> 
> I prefer to improve our tools rather than working around them. Making an Ant call when can just do it all in Poshi is not ideal.
> 
> Work with the Poshi team to update to the latest runner.

Thanks for adding the support. Actually, I added the exact same method in JSONCurlUtil for head request. But poshi test failed when executing [JSONCurlUtil.head](https://testray.liferay.com/reports/production/logs/2023-06/test-1-37/test-portal-acceptance-pullrequest(master)/12184/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.ContentSecurityPolicy_VerifyCSPCouldConfiguredToBlockImageSource/index.html.gz?authuser=0):
[Jenkins log](https://testray.liferay.com/reports/production/logs/2023-06/test-1-37/test-portal-acceptance-pullrequest(master)/12184/functional-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz?authuser=0):
[exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.ContentSecurityPolicy#VerifyCSPCouldConfiguredToBlockImageSource] STANDARD_ERROR
     [exec]     java.lang.Exception: Unable to find method 'head' of class 'com.liferay.poshi.runner.util.JSONCurlUtil' with parameter types: (class java.lang.String)
     [exec]     Valid methods with the same name:
     [exec]     NONE

So I workaround for this failure. 
Off course you're right. It's better to improve our tools rather than working around them.
cc @gaborlovasdotcom

**Comment by brianchandotcom** [comment]
@JoyceWang08211 can you fix the util, I didn't run the tests, my bad. But let's fix the root issue.

**Comment by JoyceWang08211** [comment]
> @JoyceWang08211 can you fix the util, I didn't run the tests, my bad. But let's fix the root issue.

Hi @brianchandotcom ,
I can try my best. But to be honest, I have no idea how to fix this issue. That's the reason why I choose the second [solution](https://liferay.atlassian.net/browse/LRQA-80963?focusedCommentId=1687241). 
Do you have any suggestion? @gaborlovasdotcom

**Comment by kenjiheigel** [comment]
@JoyceWang08211, adding it and testing it won't work right away because we have to publish a new poshi release for those changes to be usable. 

> [exec] java.lang.Exception: Unable to find method 'head' of class 'com.liferay.poshi.runner.util.JSONCurlUtil' with parameter types: (class java.lang.String)

This might not be until next week at earliest though because we have some bigger changes we need to test out.

For testing purposes on CI in the mean time though, you can update the lines in this file: 
https://github.com/liferay/liferay-portal/blob/master/portal-web/build-test.gradle#L47-L49

with: 
```
poshiRunner {
	openCVVersion = "2.4.10-0.10"
	version = "1.0.437"
}
```

**Pull request closed without merging**
