### PR TITLE
LPS-54515 SF

### PR DESCRIPTION
**Pull request by rotty3000**
Nice  @pei-jung!

### CODE REVIEW

**Comment by pei-jung** [comment]
It's actually @holatuwol's work. Thanks Minhchau!

**Comment by rotty3000** [comment]
Ooops! Sorry! Good work to EVERYONE involved!!!!

**Comment by pei-jung** [comment]
Thanks, Ray! :)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bf59052c57...ce970dd9ab

**Comment by brianchandotcom** [comment]
Beautiful job guys.

I made a tiny change with using the DeleteAfterTestRun annotation. See 

Thx guys.

**Pull request closed without merging**
