### PR TITLE
LPS-64196 Allow assigning multiple roles to users and user groups

### PR DESCRIPTION
**Pull request by alee8888**

### CODE REVIEW

**Comment by alee8888** [comment]
@brianchandotcom @ealonso @evannagayama
This PR combines the commits from LPS-64196 and Poshi functional test fixes (LRQA-23298).

**Comment by evannagayama** [comment]
Thanks Albert!

**Comment by ealonso** [comment]
cc @pei-jung

**Comment by pyoo47** [comment]
ci:retest

**Comment by sharonchoi** [comment]
@brianchiu upgrade test failures due to https://issues.liferay.com/browse/LPS-64526
@kenjiheigel portal smoke failings due to https://issues.liferay.com/browse/LPS-64500

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/212b1f4f69...f9dba816b6

**Pull request closed without merging**
