### PR TITLE
LPS-69271

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@shuyangzhou, in order to retrieve extended/implemented classes, I added all the modules jars found in tools/sdk/dist to the classloader that I then pass to JavaDocBuilder. It works and performance doesn't get hit too hard: https://github.com/brianchandotcom/liferay-portal/pull/44838/commits/cf911461d4d4af0d092dbf3e8cb0528cd27d7153
It's not very pretty, but I can't think of a better way.

BTW, this is not a qdox specific problem. Any javaparser needs those classes to be loaded first before having 'access' to the extended/implemented classes (I tested with github.javaparser also)

@brianchandotcom, for files that extend/implement module files, this only works after running ant all, since the tools/sdk/dist needs to be populated

**Comment by hhuijser** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
Yes, @hhuijser , we do similar stuff to modules' jsp precompile. There is no other way to do it.

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
ci:retest

**Comment by hhuijser** [comment]
ci:retest

**Comment by hhuijser** [comment]
@shuyangzhou, looks like this is causing a "java.lang.OutOfMemoryError: Java heap space"

Is this a matter of increasing the memory on Jenkins or should we reconsider the adding-all-jars-approach?

**Comment by shuyangzhou** [comment]
@hhuijser Try increase the heap size yourself, let me know how much more memory can make this go away. Then we decide what solution to choose.

**Comment by brianchandotcom** [comment]
SourceFormatterTest.testSourceFormatter still broken. Please resend.

**Pull request closed without merging**
