### PR TITLE
LPS-182317 Implement utility page for internal server error

### PR DESCRIPTION
**Pull request by alessandromalves**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-182317)

Adds utility page for error 500

## Rant

* It only works for guest site at the moment, since the error could be thrown anywhere and we don't have information where it happens
* Error has to be thrown by hand to make it work
* Everything is behind a FF, and component is disabled

## How to make it work 

* Enable ff for LPS-165914
* Enable component: `scr:enable com.liferay.layout.utility.page.status.internal.InternalServerErrorLayoutUtilityPageEntryViewRenderer`
* After this, the utility page templates for error 500 can be created through the interface

cc.: @jkappler

### CODE REVIEW

**Comment by alessandromalves** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/11981

:heavy_check_mark: ci:test:stable - 29 out of 29 jobs passed
:x: ci:test:relevant - 263 out of 306 jobs passed in 1 hour 59 minutes

**Comment by alessandromalves** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e455e7fc5e...86bb481c22

**Comment by brianchandotcom** [comment]
@alessandromalves @jkappler see 86bb481c222a04bf633ff4a3c1fac186e4b9cf60

**Pull request closed without merging**
