### PR TITLE
LPS-75936 Dead code in master/7.1. Do not backport to 7.0.x

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by lipusz** [comment]
Hi Brian,

Please, do not merge it to 7.0.x automatically. We want to wait until QA can test it properly on master and then backport following the standard process. @topolik will handle it later.

Thank you for you consideration!

Br,
Tibor

**Comment by lipusz** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@pedroqueiroz94 @lipusz I haven't seen all of modules-int* fail in a way. Please resend? Thx.

**Comment by brianchandotcom** [comment]
@lipusz PublicRenderParameterTest.testWithModuleLayoutTypeController looks related.

**Comment by topolik** [comment]
@lipusz I take care of it.

**Comment by topolik** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/53839

**Comment by topolik** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/53841

**Pull request closed without merging**
