### PR TITLE
LPD-15162 Java 21

### PR DESCRIPTION
**Pull request by petershin**
CI tests passed here:

https://github.com/petershin/liferay-portal/pull/2200
https://github.com/petershin/liferay-portal-ee/pulls

@vicnate5
@ling-alan-huang

### CODE REVIEW

**Comment by petershin** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f08ff12d95...fcb09c466a

**Comment by brianchandotcom** [comment]
@ling-alan-huang @petershin see fcb09c466a91772dab6610f137d15472c924a041

I'm not sure if what I did there was right.

I merged all the backports and used the latest published SDK.

**Comment by petershin** [comment]
@brianchandotcom Its a rare edge case, I forgot to add a temp SF suppression for it

@ling-alan-huang Thank you for your help adding the new JDK 21 SF rule!

**Pull request closed without merging**
