### PR TITLE
LPS-93464 Fix duplicate operationIds

### PR DESCRIPTION
**Pull request by petershin**
@dgarciasarai

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by dgarciasarai** [comment]
Great job! Super fast @petershin! Thanks :)

**Comment by petershin** [comment]
@yichenroy - Can you freeze just this server so I can look into the CI failure?

**Comment by yichenroy** [comment]
@petershin - I took this server offline.

**Pull request closed without merging**
