### PR TITLE
LPS-74098 Add null check to avoid NPE because there are no system events in local staging environment

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
cc @jkappler

**Comment by jkappler** [comment]
Hi @matethurzo, we are unsure if this would be the right fix for this or if it would create issues in live with trash entries. Please let us know what you think. Now it returns null since there's a group validation for system entries (06352141b18e434c33d1c71e55bfcc8e3a24bce0)

**Comment by matethurzo** [comment]
@jkappler this looks okay, but can you please find out why the trash entry is storing a reference to the system event itself? is it being used somewhere else later? I think there can be some more potential NPEs

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f21dbf434b...cc6037ce4f

**Pull request closed without merging**
