### PR TITLE
LPS-114165 - Quarantine failing tests with flakiness

### PR DESCRIPTION
**Pull request by rodrigocunhaa**

### CODE REVIEW

**Comment by rodrigocunhaa** [comment]
ci:reopen

**Comment by jpince** [comment]
@rodrigocunhaa based on your query in portal-workflow/test.properties, your change won't actually exclude the tests from pull requests, because acceptance is still true.
```
    test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant]=\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names ~ "Workflow") OR \
            (testray.main.component.name ~ "Kaleo Designer") OR \
            (testray.main.component.name ~ "Kaleo Forms Admin") OR \
            (testray.main.component.name ~ "Workflow")\
        )
```

cc/ @alexcandidos @palomanunes do we need a review process for newer hires?

**Comment by inacionery** [comment]
Hey @jpince, new hires have a review process, but @rodrigocunhaa is no longer a new hired and is aware of their changes.

**Comment by jpince** [comment]
@inacionery agreed, sorry for my mistake. I was incorrect in my understanding of the new logic, and Rodrigo was kind enough to explain that to me. No change in process is needed.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/80f1230edf...144ed97f71

**Comment by alexcandidos** [comment]
Hi folks, I'm glad we are all on the same page now!
Thanks, @rodrigocunhaa for sharing your knowledge helping @jpince to understand better how the queries are working after the "ci forward" process changes. :)

**Pull request closed without merging**
