### PR TITLE
LPS-58210 Removes dockbar

### PR DESCRIPTION
**Pull request by juliocamarero**
@brianchandotcom , the error in plugins about so-porltet/user-bar/view.jsp is not real. That code doesn't exist anymore.

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @ealonso

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@juliocamarero That error went away because I updated git-commit-plugins. You guys need to update the pull in the future to point to that pull.

See https://in.liferay.com/web/global.engineering/blog/-/blogs/new-tests-for-the-pull-request-tester-

Thx

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/70ad2cca8f...8e406ed7dc

**Pull request closed without merging**
