### PR TITLE
Revert "LPS-108283 Don't export content pages which never were published before"

### PR DESCRIPTION
**Pull request by jkappler**
Hey @brianchandotcom, this is actually not needed, and it's causing regressions with Display Pages. So it's safe to revert. Already checked that everything works out with workflow + staging + export/import

### CODE REVIEW

**Comment by jkappler** [comment]
@ealonso, @jpince

**Comment by jkappler** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/00360fa575...fbc0f2520a

**Pull request closed without merging**
