### PR TITLE
LRQA-50061 | master

### PR DESCRIPTION
**Pull request by vicnate5**
Master ONLY https://issues.liferay.com/browse/LRQA-50061

### CODE REVIEW

**Comment by vicnate5** [comment]
Related to https://github.com/brianchandotcom/liferay-portal/pull/75953

**Comment by vicnate5** [comment]
@lawrence-lee

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1711c05d31...3425830243

**Comment by brianchandotcom** [comment]
@vicnate5 @john-co beautiful! Nicely done.

**Pull request closed without merging**
