### PR TITLE
COMMERCE 6098 1

### PR DESCRIPTION
**Pull request by ivicac**

### CODE REVIEW

**Comment by ivicac** [comment]
hi @brianchandotcom ,
can you please merge this PR as it fixes the broken "Commerce Details Page". CI is currently not working properly, that is why I am sending you PR directly.

cc @marco-leo

**Comment by ivicac** [comment]
ci:reopen

**Comment by ivicac** [comment]
ci:test:sf

**Comment by ivicac** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1da460e9bd...2a04e7eef8

**Pull request closed without merging**
