### PR TITLE
Lps 106966

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by jpince** [comment]
ci:test

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
@vicnate5 @austinchiang a lot more int test failures here compared to upstream master, not sure if they're related to this change.

@joshchong synonymns console errors (probably unrelated to this pull?)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8ad0f59c23...423c373cd0

**Comment by joshchong** [comment]
@jpince yeah the synonyms errors are fixed by this PR:
https://github.com/brianchandotcom/liferay-portal/pull/83263

**Comment by vicnate5** [comment]
@shuyangzhou @mtambara @jbalsas Some integration failures do look related
```
    [exec] com.liferay.exportimport.lifecycle.test.ExportImportLifecycleEventTest > classMethod FAILED
     [exec]     org.osgi.framework.BundleException: Could not resolve module: com.liferay.exportimport.test [1050]
     [exec]       Unresolved requirement: Import-Package: com.liferay.bookmarks.model
     [exec]         at org.eclipse.osgi.container.Module.start(Module.java:444)
     [exec]         at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
     [exec]         at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:447)
     [exec]         at com.liferay.arquillian.extension.junit.bridge.connector.FrameworkCommand.lambda$startBundle$37e16ea2$1(FrameworkCommand.java:46)
     [exec]         at com.liferay.arquillian.extension.junit.bridge.connector.ArquillianConnectorThread.run(ArquillianConnectorThread.java:82)
```

https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/286750/AXIS_VARIABLE=12,label_exp=!master/testReport/junit/com.liferay.exportimport.data.handler.test/DummyFolderStagedModelDataHandlerTest/classMethod/

**Comment by mtambara** [comment]
Revert sent at https://github.com/brianchandotcom/liferay-portal/pull/83295

**Pull request closed without merging**
