### PR TITLE
LPS-86554 Avoid creating component and use a class with static methods instead

### PR DESCRIPTION
**Pull request by jkappler**
Hi @brianchandotcom, we avoid using a component as you mentioned (last commit). It was needed previously, but when moving the code to the base class it's not needed anymore. We went ahead an fixed it since we don't want to bother @preston-crary too much with it. 

Please let us know what you think. Thanks!

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by jkappler** [comment]
@brian-chiu, the failures appear to not be related to the PR (or so it seems). Just double checking with you. Thanks

**Comment by Preston-Crary** [comment]
@jkappler since it's static and only used in the base, can't we just inline AssetDisplayContributorFieldHelperUtil into the base class?  Also the ResourceBundle lookups for each key is a bit slow and causes some duplication, can we pass in the resource bundle so we can reuse them for the same contributors (it's a little tricky since you'd need to know where all of them are getting their translations and do them is groups)?

**Comment by brianchandotcom** [comment]
@jkappler I merged this, but I don't like how

com/liferay/asset/display/internal/asset/display/contributor/field/AssetEntryAuthorNameAssetDisplayContributorField.java

is in "asset.display.contributor.field", even though 

AssetDisplayContributorField is just in

com.liferay.asset.display.contributor.AssetDisplayContributorField

So can you move

com.liferay.asset.display.contributor.AssetDisplayContributorField to

com.liferay.asset.display.contributor.field.AssetDisplayContributorField

or, move 

git grep "asset\.display\.contributor\.field" **.java into

just plain old asset.display.contributor.field (without the field package)

Please do that in a follow up pull. This is merged.

Thx!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e84026e4e5...df54a2fbd2

**Comment by jkappler** [comment]
Hi @Preston-Crary, sorry, was ooo last week.  For what you mentioned about the ResourceBundle, I'll take a look asap. I'll travel today to the devcon but will be still available through the week.

Thanks for the suggestions!

**Pull request closed without merging**
