### PR TITLE
LRQA-48400, LRQA-48404 | master

### PR DESCRIPTION
**Pull request by kmaria**
https://issues.liferay.com/browse/LRQA-48400
https://issues.liferay.com/browse/LRQA-48404

master only

### CODE REVIEW

**Comment by kmaria** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@shuyangzhou can you fix this?

```
   [exec] org.osgi.framework.BundleException: Could not resolve module: samplemvc [986]
     [exec]   Unresolved requirement: Import-Package: com.liferay.portal.kernel.portlet.bridges.mvc; version="[1.6.0,2.0.0)"
     [exec] 
     [exec] 	at org.eclipse.osgi.container.Module.start(Module.java:444)
    
```

**Comment by shuyangzhou** [comment]
@brianchandotcom to fix it, we need to update the kernel dependency from project-templates to latest kernel release, which we don't have yet.

**Comment by shuyangzhou** [comment]
@petershin I am trying to create a 7.2 branch here https://github.com/liferay/liferay-portal/blob/master/modules/sdk/project-templates/project-templates-mvc-portlet/src/main/resources/archetype-resources/build.gradle#L28 to make kernel dependency to default.
However the generated modules/sdk/project-templates/project-templates-mvc-portlet/build/samplemvc/build.gradle is unable to pick the local "${codebase}/.m2" repo, how should I configure it to do so?

Or anyway, @brianchandotcom if you want to publish a kernel snapshot, we can use it for now.

**Comment by petershin** [comment]
@shuyangzhou - Try adding the code below:

```
repositories {
	mavenLocal()
}
```

Please check w Greg Amerson about the change too.  It may have been excluded intentionally.

**Comment by shuyangzhou** [comment]
I tried that, it does not work, see only picking ${user.home}/.m2, not the repo local one.

**Comment by petershin** [comment]
From the command line try passing a system property to override the default value`-Dmaven.repo.local=...`  It's usually set by the property here: [build.properties#L268](https://github.com/liferay/liferay-portal/blob/master/build.properties#L268)

Or hardcode the directory inside `build.gradle`

```
repositories {
	maven {
		url portalMavenLocalRepositoryDir
	}
}
```

**Comment by shuyangzhou** [comment]
The generated project is using a different settings, it does not have that variable.
```
Build file '/home/trunks/git/liferay-portal/modules/sdk/project-templates/project-templates-mvc-portlet/build/samplemvc/build.gradle' line: 7

* What went wrong:
A problem occurred evaluating root project 'samplemvc'.
> Could not get unknown property 'portalMavenLocalRepositoryDir' for repository container of type org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

**Comment by shuyangzhou** [comment]
@petershin "-Dmaven.repo.local=" does not work either, still running bnd with the old kernel.

**Comment by petershin** [comment]
@shuyangzhou - Here's a more complete example

```
repositories {
	File dir = rootProject.projectDir

	while (dir != null) {
		File mavenLocalRepositoryDir = new File(dir, ".m2")

		if (mavenLocalRepositoryDir.exists()) {
			maven {
				url mavenLocalRepositoryDir
			}
		}

		dir = dir.getParentFile();
	}
}
```

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/71815

**Pull request closed without merging**
