### PR TITLE
LPS-99354 Fix memory leak

### PR DESCRIPTION
**Pull request by brunofarache**

### CODE REVIEW

**Comment by brunofarache** [comment]
@andresfulla there is a nasty memory leak happening on all react portlets because of senna. it happens on segments, workflow metrics and app builder, we need to unmount the root component when portlet is destroyed, like in this PR.

here's how you reproduce it:

https://recordit.co/Sgk0qFoI7x

cc @wincent could we make a generic solution would prevent this to happen?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2f40c39be6...82a9c9c134

**Comment by wincent** [comment]
Thanks @brunofarache. I created https://issues.liferay.com/browse/LPS-99399 to track this.

**Comment by jbalsas** [comment]
Hey @brunofarache, this is the expected behaviour and we already have lifecycle inside the `Liferay.component` API to help with these type of situations. We should standardize around this.

For example, using `Liferay.component(...)` to register your component will ensure that a `destroy` method is called on navigation where you can take care of any necessary cleanup tasks.

**Pull request closed without merging**
