### PR TITLE
LPS-93729 Update liferay-theme-tasks to v9.0.0

### PR DESCRIPTION
**Pull request by wincent**
Test plan:

In "modules/apps":

```
for X in admin classic; do
  (cd frontend-theme/frontend-theme-$X && gradlew clean deploy)
done

for X in fjord westeros-bank porygon; do
  (cd frontend-theme-$X/frontend-theme-$X && gradlew clean deploy)
done
```

### CODE REVIEW

**Comment by jpince** [comment]
ci:reopen

cc/ @john-co something about a test plan in the description, don't know if that's for you

**Comment by wincent** [comment]
@jpince: not specifically for @john-co; I usually include a test plan where I just write what I did to verify that the change works, so anybody looking at the PR can do the same if they want to (or for myself, if I come back to look at a PR days, weeks or months later).

**Comment by jpince** [comment]
@wincent nice! Glad you're thinking about testing :) Do you think it would be beneficial to put that information in the JIRA ticket also? I usually look in the ticket for test steps, rather than the PR or commit description. And this is how some other teams are using JIRA tickets also.

**Comment by wincent** [comment]
@jpince: yeah, it probably wouldn't hurt.

**Comment by brianchandotcom** [comment]
@jpince please work with @wincent to automate this if it makes sense. Shoudn't this be part of the js-unit test group? 

Automation > documentation

**Comment by jpince** [comment]
@john-co please see BChan's comment and evaluate need. thanks!

**Comment by wincent** [comment]
@jpince: FWIW I think it would be redundant to test this at a higher level because those commands I ran in the test plan occur as part of the build anyway — if they don't work, then the build won't work.

**Comment by wincent** [comment]
I'll make a new PR tomorrow that replaces this. As part of [this PR](https://github.com/liferay/liferay-npm-tools/pull/73) to liferay-npm-scripts, liferay-theme-tasks is going to become a transitive dependency.

**Comment by wincent** [comment]
Replacement pull is new: https://github.com/brianchandotcom/liferay-portal/pull/71318

**Pull request closed without merging**
