### PR TITLE
LPS-111138 Fix errors in GraphQL autogenerated tests

### PR DESCRIPTION
**Pull request by javierdearcos**

### CODE REVIEW

**Comment by javierdearcos** [comment]
ci:reopen

**Comment by jpince** [comment]
Just started reviewing :)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/13da7a32d2...eae3afc608

**Comment by brianchandotcom** [comment]
@javierdearcos please talk to @leoad for long term fix.

**Pull request closed without merging**
