### PR TITLE
LPS-103034 Add companyId field where it is missing

### PR DESCRIPTION
**Pull request by achaparro**
@brianchandotcom, rebase from:
https://github.com/brianchandotcom/liferay-portal/pull/80029#issuecomment-547183332

cc/ @vicnate5

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@inacionery see MetricResourceTest.testGetProcessMetric

**Comment by inacionery** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by inacionery** [comment]
Hey @brianchandotcom,

seems to be an unrelated flaw in CI, but I'll take a look to see if there is any improvement to be made.

Thanks!

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Guys, I just reviewed this... so this doesn't seem to ensure that new rows of these tables include companyId.

For example, KaleoProcessLink now has a companyId. Nothing was changed in KaleoProcessLinkLocalServiceImpl or equivalent to ensure that new rows of KaleoProcessLink actually populate companyId. So, over time... we will get very bad data.

@achaparro please let me know if I'm missing something. But this would be a very bad bug if I allowed this in (I think).

**Pull request closed without merging**
