### PR TITLE
LRQA-50455 Eliminate duplicate locator key in Button.path

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-50455
@liuxingye @Hanlf This locator key was duplicated, I kept the older one from https://issues.liferay.com/browse/LPS-98021

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@pyoo47 these errors make no sense?

**Comment by yichenroy** [comment]
@brianchandotcom 
I rebased this pullrequest off of the `brianchandotcom` origin so it contains commits not available on the `liferay` user. The duplicate locator key issue is preventing the stable job from merging into `liferay`.

The validate-pull-request error happens because we're validating against `liferay` so the commits that do not yet exist on `liferay` are checked.

cc @jpince @victorg1991

**Comment by yichenroy** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ff555e865f...84528b341b

**Comment by jpince** [comment]
@brianchandotcom the error in SF is the helpful one
```
Target exception: java.lang.RuntimeException: Unable to create local branch temp-master-private1562881059903 at 8ef663032572870f43650fb53daec8e3295f97e1
fatal: Not a valid branch point: '8ef663032572870f43650fb53daec8e3295f97e1'.
```

@yichenroy the relevant test failure is what makes this confusing and difficult to understand what the issue is `Illegal change to a .gitrepo file.` Ideally, it should fail with the same error as SF, or some error indicating that CI can't find the hash.

**Comment by yichenroy** [comment]
@jpince got it, I'll discuss this with @pyoo47

**Pull request closed without merging**
