### PR TITLE
LPS-66460 Allow for numeric user screen names without any limitations

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-66460](https://issues.liferay.com/browse/LPS-66460).<br><br>Hey Brian, this is our proposed implementation.  It does not yet include the update to the "breaking changes" document or an Upgrade process since we would like to make sure we have the right solution first. 

Key points:

1. This pull does not add an extra portal property
2. The default friendlyURL for a group being updated with a blank friendlyURL field is now "group-{groupId}", e.g. group-12345
3. The `users.screen.name.allow.numeric` now defaults to true
4. A group will no longer be accessible by using its groupId as the friendlyURL in any case (since we are removing this "feature" _completely_)

Please let us know what you think. Thanks!

/cc @pei-jung, @jorgeferrer

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:retest

**Comment by drewbrokke** [comment]
Hey @brianchandotcom, do you need anything else from us for this pull?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0be5fb844e...5a94ab70f1

**Pull request closed without merging**
