### PR TITLE
LPS-54970 CSS Builder

### PR DESCRIPTION
**Pull request by Ithildir**
First part of brianchandotcom#26256.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@Ithildir I know this works, I'm just using this pull to test the latest master.

ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by david-truong** [comment]
@brianchandotcom hey brian how much longer for this pull?  Some people are waiting for us to remove the old ruby compiler so they can move out the scripting executor.  We can just switch to the new one for the old code if this is going to take awhile longer.

**Comment by brianchandotcom** [comment]
@david-truong Sorry I didn't get to this til now. But how is CSSBuilder different from SassToCssBuilder?

We already have a "build-css" that calls SassToCssBuilder So what will call CSSBuilder?

I need to know the relationship of CSSBuilder to SassToCssBuilder before merging it in.

Thx.

**Comment by david-truong** [comment]
@brianchandotcom This is a complete replacement for SassToCssBuilder.  It was rewritten because of the following reasons:

First it was renamed to CSSBuilder because the class actually does more than compiles sass files.  It also does RTL conversion and parses tokens.  

Second SassToCssBuilder is also heavily reliant on classes within portal-impl.  CSSBuilder currently only relies on two classes from portal but with a few more easy optimizations it can completely break free of any portal dependencies which is huge for our dev tools.

Third CSSBuilder is easy to follow.  Anyone who has tried to fix anything in SassToCssBuilder will quickly discover the circular dependencies between classes and overly complex implementation.  This is more important because Nate and I have discussed further optimizations to our css files but it is currently too difficult with SassToCssBuilder.

The current unit tests compares the css files parsed using SassToCssBuilder to CSSBuilder to show that everything is working like the old way.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Talked to @david-truong he will resend.

**Pull request closed without merging**
