### PR TITLE
LPS-107191 | Adding charts for views metric

### PR DESCRIPTION
**Pull request by andresfulla**
Hi Brian, quick note on the language keys. We are using views-metric (translated as Views) to keep this term within our module. The key views in portal-impl does not entirely relate to our term, even though is translated as Views in English (I took a look at the Spanish translation, Accesos, which doesn't make sense in our use case).

Hope this makes sense.

cc/ @dgarciasarai

### CODE REVIEW

**Comment by dgarciasarai** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/83c0d6ceab...1623f2bf49

**Comment by brianchandotcom** [comment]
@wincent see yarn.lock

```
balanced-match@^0.4.2:
  version "0.4.2"
  resolved "https://registry.yarnpkg.com/balanced-match/-/balanced-match-0.4.2.tgz#cb3f3e3c732dc0f01ee70b403f302e61d7709838"
  integrity sha1-yz8+PHMtwPAe5wtAPzAuYddwmDg=

balanced-match@^1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/balanced-match/-/balanced-match-1.0.0.tgz#89b4d199ab2bee49de164ea02b89ce462d71b767"
  integrity sha1-ibTRmasr7kneFk6gK4nORi1xt2c=

```

Is that bad?

**Comment by brianchandotcom** [comment]
@andresfulla thanks for the info on the keys. It's probably OK. I'll leave it to the product  managers.

**Comment by wincent** [comment]
@brianchandotcom: We want to avoid duplication in the dependency graph as much as *practically* possible, which means that in practice we have to tolerate *some* duplication.

@jbalsas and I keep an eye on PRs that change the `yarn.lock` (at least, all the ones we detect) to try and catch problematic examples; if we had a tool like [Herald](https://secure.phabricator.com/book/phabricator/article/herald/) this is exactly the kind of thing we'd set up a rule for (eg. "When affected path matches `yarn.lock` add X and Y as reviewers" etc).

In this specific case, [`balanced-match`](https://www.npmjs.com/package/balanced-match) is a tiny package (less than 100 lines) that brings no other dependencies with it, so this is one of those examples of "tolerable duplication". From time to time packages we depend on update their own dependencies, and that presents us with an opportunity to rollback the duplication, so hopefully that will happen in this case too.

**Pull request closed without merging**
