### PR TITLE
LPS-64310 Fix markup to work with look and feel js that manages "same for all" switches

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
These might be valid issues... retesting and looking into them at the same time.

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
issues confirmed, @carloslancha will look into them

**Comment by evannagayama** [comment]
@carloslancha I pushed it in with fixes here: https://github.com/brianchandotcom/liferay-portal/pull/39752

**Comment by jbalsas** [comment]
Awesome! Thanks so much @evannagayama!!

**Pull request closed without merging**
