### PR TITLE
LPS-109492 Uses allowSuccessPage instead of successPageSettings.enabled (which was meant for actually displaying or not a success page on the form instead of controlling wether it's possible or not to add one)

### PR DESCRIPTION
**Pull request by natocesarrego**
From @brunobasto:

> It seems that the regression was caused by a confusion on what `successPageSettings.enabled` actually does. The `successPageSettings` configuration of the Form Builder has the following structure:
> ```
> {
>     body: "A success message to the end user",
>     title: "A success message title to the end user",
>     enabled: true // or false
> }
> ```
> The `enabled` property tells the Form Builder if the success page feature is currently enabled in the form. That is: When a user (**End User**) submits a response to a form he/she will be redirected to this success page.
> 
> Recently we needed a feature that would say if the **Form Builder User** (the user that actually creates the form) is able to define a success page to a form or not. That feature was added by reusing the `successPageSettings.enabled` flag and that is what caused the confusion.
> 
> I've now added a new configuration called `allowSuccessPage` that's meant to remove the "Add Success Page" option from the Form Builder when set to `false`.

@brunobasto, I re-based your fix for the LPS-109492 and now I'm sending it again to see if we win this arm-wrestle against the CI unrelated failures. 🙂 

Best.

### CODE REVIEW

**Comment by natocesarrego** [comment]
ci:reopen

**Comment by natocesarrego** [comment]
Hi @brianchandotcom,

I'm sorry but I'm a little tired to try to send pulls through `ci:forward` and it doesn't work since last week for different unrelated failures, thus I decided to forward this pull to you once the last execution succeed but the pull wasn't forwarded. 😞 Please see CI results associated to this pull [here](https://github.com/natocesarrego/liferay-portal/pull/421).

Thanks.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e04d864620...9099700467

**Pull request closed without merging**
