### PR TITLE
Lps 94307

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
CC @lanceji92674957 another small one, just keep the data point before/after.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/839244a014...c3ecfa89be

**Comment by lanceji92674957** [comment]
@shuyangzhou comparing it with yesterday's baseline now

**Pull request closed without merging**
