### PR TITLE
LPS-91342

### PR DESCRIPTION
**Pull request by petershin**
@nhpatt

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5f88de0c63...19f6593fec

**Comment by brianchandotcom** [comment]
@nhpatt I fixed the generator for the tests @petershin see upstream.

@4lejandrito please see my changes.

Thx everyone!

**Comment by nhpatt** [comment]
Thanks! :)

**Pull request closed without merging**
