### PR TITLE
Lps 183421 redo

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Thank you @shuyangzhou !!!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/aae750d4c4...3a61f3ec22

**Comment by brianchandotcom** [comment]
@shuyangzhou I kept 278eb7bae4fa794e0ba9de1f5753fdbf052adc3f

**Pull request closed without merging**
