### PR TITLE
Lps 72981

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/49672

**Comment by shuyangzhou** [comment]
@brianchandotcom this is very annoying, I think the pull is closed due to https://github.com/brianchandotcom/liferay-portal/pull/49669/commits/f093e516201faea643afbcc8c0f61dab536fdb43

That means when subrepo auto merge runs, we are not scanning for commits ticket numbers. So not until you push your origin, everyone will have to discard commits locally before sending you pulls to avoid this auto close. I think we should do the same scanning for subrepo auto merge pulls, for merges that contain commits like https://github.com/brianchandotcom/liferay-portal/pull/49669/commits/f093e516201faea643afbcc8c0f61dab536fdb43, the auto merge pull should be rejected.

**Comment by brianchandotcom** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@tomwang2011 can you backport the changes? Thx.

**Comment by brianchandotcom** [comment]
@stsquared99 see comment from @shuyangzhou 

Can you add that to our check? Thx.

**Pull request closed without merging**
