### PR TITLE
LPD-25668 Use binary sass compiler from npmscripts and/or node-scripts

### PR DESCRIPTION
**Pull request by izaera**
Rebase of https://github.com/brianchandotcom/liferay-portal/pull/151699

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:sf

**Comment by brianchandotcom** [comment]
@izaera hey Ivan, let 's chat because I have some doubts due to

sass.compiler.class.name

Thx

**Comment by izaera** [comment]
Closing. Will resend renaming the keys to `node.sass`

**Comment by izaera** [comment]
Resent as https://github.com/liferay-frontend/liferay-portal/pull/4278 instead of directly because I want to check SF and see if removing the build properties may cause any issue in the CI (I doubt it, but just in case).

**Pull request closed without merging**
