### PR TITLE
LPS-61465 small UI fix for product menu

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @marcoscv-work

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@brianchiu see random failing tests (julio fixed it by testing a few times, but that's not ideal)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/817c9dbd32...261ea9d4db

**Comment by brianchiu** [comment]
@alee8888 - Can you look at the Users and Orgs failure?

@evannagayama - Can you look at the web content failure?

**Pull request closed without merging**
