### PR TITLE
LPS-168569

### PR DESCRIPTION
**Pull request by david-gutierrez-mesa**
cc/ ealonso

### CODE REVIEW

**Comment by david-gutierrez-mesa** [comment]
Sending manually since failures are not related. SF here: https://github.com/liferay-echo/liferay-portal/pull/10304#issuecomment-1316558448

**Comment by david-gutierrez-mesa** [comment]
ci:reopen

**Comment by david-gutierrez-mesa** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4d37541f13...5c55f5dfbf

**Pull request closed without merging**
