### PR TITLE
LPS-166118

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
Sorry about the tests!

**Comment by carolmariaabb** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8fe5373948...19c05030af

**Comment by brianchandotcom** [comment]
Thanks @carolmariaabb much better

See 19c05030af25e5b1209794cc0a394e586b147751

**Pull request closed without merging**
