### PR TITLE
[Phase 1] LPS-173369 Remove Stream and Optional for module: search-web-api part 1

### PR DESCRIPTION
**Pull request by dantewang**
FYI @shuyangzhou @tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@dantewang @julschong see 8fe3a66c8025121dea2ee7347161b316c1fed871

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8fe3a66c80...9ef43ee9d6

**Comment by brianchandotcom** [comment]
@dantewang @julschong wrong PR comment earlier, see 9ef43ee9d65847018feafc58522e73b7634ce7da

**Pull request closed without merging**
