### PR TITLE
LPS-85195 Removing unique from the finder

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @brianchandotcom,

I have removed everything from `*ToUserSharingEntriesUnique` to `*UniqueToUserSharingEntries` in https://github.com/brianchandotcom/liferay-portal/pull/63672/commits/aa5f1ff2f0414d8bcb12a6d9350297aeff53fd9e.

I have also removed the word `unique` from the finder in https://github.com/brianchandotcom/liferay-portal/pull/63672/commits/f47b6cc488c3c585ea58e3f40c38b1e44616610f as you requested. However I think that we should keep it to clarify the purpose of the finder method. In the future someone might want to use that finder method without realizing it won't yield every single result. If you agree with me just remove the last commit, otherwise merge it all.

Thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fa1d0d42da...5e938ab3c8

**Comment by brianchandotcom** [comment]
See 5e938ab3c8512dea82ed915061dcb40c22aa9d4d

Can you also rename "public int count*" in SharingEntryLocalServiceImpl.java to "public int get*Count". I didn't catch that until now. That will make it match our other service impl's.

Thx.

**Comment by 4lejandrito** [comment]
Hi @brianchandotcom,

I was out of the office today. Will get this done tomorrow morning.

Thanks!

**Pull request closed without merging**
