### PR TITLE
LPS-78082 Using plurals everywhere

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
Hi @jpince,

SF keeps failing for unrelated causes (or so I believe), can you please have a look?

Thanks!

**Comment by jpince** [comment]
@4lejandrito looks fine, thanks for bringing this up

@petershin can you investigate why SF has an issue with that file? I can't figure out a reason.

**Comment by petershin** [comment]
@jpince @4lejandrito - The `KeyValuePairComparator` was used on [social_bookmarks_settings/page.jsp#L55](https://github.com/liferay/liferay-portal/blob/master/portal-web/docroot/html/taglib/ui/social_bookmarks_settings/page.jsp#L55).  This file was removed in this pull so SF is removing the import from [common/init.jsp#L119](https://github.com/liferay/liferay-portal/blob/master/portal-web/docroot/html/common/init.jsp#L119).

Adding that change to this pull will fix the SF issue.

**Comment by jpince** [comment]
ci:close

**Comment by jpince** [comment]
@petershin thank you!

**Comment by 4lejandrito** [comment]
Thanks @petershin! I will resend in a minute.

Would you mind explaining to me why running `ant format-source-current-branch` inside `portal-impl` didn't catch this issue locally?

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/56107.

**Comment by 4lejandrito** [comment]
ci:close

**Comment by petershin** [comment]
@4lejandrito - Sure, glad to explain it a bit more.  When `ant format-source-current-branch` is run, SF gets a list of the added and modified files for the branch by running this command:

```git diff --diff-filter=AM --name-only 63becb8353e57714bf179233e4b54ad73d6919b1 97679d9ee281868350b757457c74804861cd5f13```

I think SF needs to be updated to get the list of deleted files (possibly by removing the diff-filter option) and then checking references to the deleted files.  I'll look into this a little more and see if it can catch these changes too.  Hope this helps!

**Comment by 4lejandrito** [comment]
It does help :) 

Thanks @petershin!

**Pull request closed without merging**
