### PR TITLE
LPS-79442

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test

**Comment by matethurzo** [comment]
ci:reopen

**Comment by matethurzo** [comment]
@brianchandotcom I've crunched the failed test and they are not related to this change

**Comment by brianchandotcom** [comment]
@matethurzo please resend on top of https://github.com/matethurzo/liferay-portal/pull/1999

1.) What's the difference between 

```
T relationshipBase

T t

T relationBaseModel
```

What's the difference between

```
RelatedModel
Base
ClassedModel
RelationshipBase
```

There is quite a bit of inconsistency still in the naming of the vars that makes the API confusing for me.

2.) Can you rename

com.liferay.portal.relationship.impl.internal

to

com.liferay.portal.relationship.internal


See

modules/apps/foundation/portal-cache/portal-cache-api
modules/apps/foundation/portal-cache/portal-cache-impl
modules/apps/foundation/user-groups-admin/user-groups-admin-api
modules/apps/foundation/user-groups-admin/user-groups-admin-impl

That's our standard module *-impl pattern. It nicely matches with the *-api pattern.

Thx!

**Pull request closed without merging**
