### PR TITLE
LPS-68268 SF

### PR DESCRIPTION
**Pull request by marcellustavares**
cc @inacionery

### CODE REVIEW

**Comment by anthony-chu** [comment]
@ctampoya It appears there's a missing form not published warning.

**Comment by ctampoya** [comment]
@marcellustavares This failure seems to only be happening on this pull. I was not able to reproduce it on master GIT ID 62810df7910e0685249e100764e409b132b084fd Could you take another look at it? Thanks!

**Comment by marcellustavares** [comment]
@inacionery, could you please double check that? 

thx @ctampoya

**Comment by brianchandotcom** [comment]
@marcellustavares please resend.

**Comment by brianchandotcom** [comment]
@jhendley @pyoo47 another reason to add a retry right now.

**Comment by inacionery** [comment]
Hey @marcellustavares these error are not related see https://github.com/inacionery/liferay-portal/pull/80#issuecomment-253623258 

/cc @ctampoya

**Pull request closed without merging**
