### PR TITLE
LPS-102764 Include confirmation message to publish a variant (A/B Testing)

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
@andresfulla

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e91776fe75...d57fa8067c

**Comment by brianchandotcom** [comment]
@epgarcia @andresfulla  minor cosmetic d57fa8067c7d7a227ee7eeb20a8f0921a290dd7e

**Comment by andresfulla** [comment]
I'll keep that in mind for future PRs
Thanks!

**Pull request closed without merging**
