### PR TITLE
LPS-54640 test jmx whiteboard support from the core

### PR DESCRIPTION
**Pull request by rotty3000**
Please note I accidentally close the PR over here https://github.com/brianchandotcom/liferay-portal/pull/25272

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@rotty3000 can we safely rename all jmx.objectname to jmx.object.name ? If so, can you do it and resend? Thx!

**Comment by rotty3000** [comment]
That will not be compatible with ARIES jmx.

Raymond Augé

**Comment by rotty3000** [comment]
Can you please reopen and merge this PR?

Thanks

**Comment by brianchandotcom** [comment]
Reopened and will merge.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/97bc645061...ffd5357b34

**Pull request closed without merging**
