### PR TITLE
Lps 56627

### PR DESCRIPTION
**Pull request by shuyangzhou**
@brianchandotcom This is the extra protection layer I have talked to you.

I just ran it once by pulling myself, it was all green. But I am sure we still have some random logs from tomcat, just hope they are not that often at this moment.

Whenever you see one, let me know, I reply to you fast for whether it is caused by the pull first, if not, just let the pull go, we will deal with the error separately. Otherwise reject the pull as it adds more tomcat warn/error logs.

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b33975b799...744b46f76c

**Comment by brianchandotcom** [comment]
@shuyangzhou do we also need to delete the log <jvmarg value="-Dliferay.log.dir=${liferay.home}/logs" /> in the SDK version of junit?

**Comment by shuyangzhou** [comment]
No, we don't. Only portal side CI build script starts tomcat. Sdk never needs to so that.

**Pull request closed without merging**
