### PR TITLE
LPS-82539 Unrelated buildLang

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:reopen

**Comment by matethurzo** [comment]
@brianchandotcom @hhuijser @jpince the SF task seems to be hanging on the generated lang files. locally i don't get these errors, but it seems to be a problem in the buildLang task.

**Comment by matethurzo** [comment]
ci:test:relevant

**Comment by matethurzo** [comment]
it seems like CI completely failed

**Comment by jpince** [comment]
@ealonso see https://github.com/brianchandotcom/liferay-portal/pull/61000/commits/2683fba650e1157f2f85e0311c4834363dd8eccb. Missed one?

**Comment by jpince** [comment]
ci:close @matethurzo it's a merge conflict caused by the buildlang you did (which is unfortunate, because I know you were trying to help). If you remove that commit and resend, it should be fine

```
liferay@jpince MINGW64 /l/CE/m (master)
$ gh pr 61000 -u brianchandotcom
Fetching pull request #61000 into branch pr-61000
remote: Counting objects: 272, done.
remote: Compressing objects: 100% (2/2), done.
Receiving objects:  90% (245/272)   d 171 (delta 167), pack-reused 100 eceiving objects:  89% (243/272)
Receiving objects: 100% (272/272), 37.16 KiB | 0 bytes/s, done.
Resolving deltas: 100% (168/168), completed with 75 local objects.
From github.com:matethurzo/liferay-portal
 * [new branch]      pr-2166    -> pr-61000
Switched to branch 'pr-61000'
[hook] gh pr 61000 --user brianchandotcom --repo liferay-portal --comment 'Just started reviewing :)'
' was unexpected at this time.

l:\CE\m>  "C:\Users\liferay\AppData\Roaming\npm\\node.exe"  "C:\Users\liferay\AppData\Roaming\npm\\node_modules\gh\bin\gh.js" pr 61000 --user brianchandotcom --repo liferay-portal --comment 'Just started reviewing :)'

liferay@jpince MINGW64 /l/CE/m (pr-61000)
$ git rebase master
First, rewinding head to replay your work on top of it...
Applying: LPS-82539 Web Content Service Configuration added - SAP Folder Version History
Applying: LPS-82539 JournalFolder single asset publish fix
Applying: LPS-82539 DLFolder single asset publish fix - fileEntry exportable status check
Applying: LPS-82539 SF and minor refactor - no need to keep a reference locally
Applying: LPS-82539 No reason to keep local reference
Applying: LPS-82539 Refactor to a method
Applying: LPS-82539 Wordsmith
Applying: LPS-82539 buildLang
Applying: LPS-82539 changeset taglib replaced with custom 'Publish to Live' icon, MVCAction added
Applying: LPS-82539 Refactor to display context as code is mostly shared
Applying: LPS-82539 Account for workflow statuses
Applying: LPS-82539 Unrelated buildLang
Using index info to reconstruct a base tree...
M       modules/apps/journal/journal-lang/src/main/resources/content/Language_nl_BE.properties
Falling back to patching base and 3-way merge...
Auto-merging modules/apps/journal/journal-lang/src/main/resources/content/Language_nl_BE.properties
CONFLICT (content): Merge conflict in modules/apps/journal/journal-lang/src/main/resources/content/Language_nl_BE.properties
error: Failed to merge in the changes.
Patch failed at 0012 LPS-82539 Unrelated buildLang
```

**Comment by matethurzo** [comment]
@jpince thanks!

**Pull request closed without merging**
