### PR TITLE
LPS-92299 Remove no longer needed test

### PR DESCRIPTION
**Pull request by patriciajeanperez**
The class under test was removed in
0f5ba17be44ae4d9336cd6519d089ed883592eb2.

### CODE REVIEW

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:reopen @michaelhashimoto @yichenroy does sf rebase to upstream/master head? The SF failure looks like an issue they were having with SF yesterday, I think BChan published a new version to resolve.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by yichenroy** [comment]
@jpince 
Yes, ci:test:sf rebases to the upstream sha, this latest ci:test:sf rebases to this commit:
https://github.com/liferay/liferay-portal/commits/4a958544752b050e1319f78744e636d498e3a96d

**Comment by patriciajeanperez** [comment]
thanks for reopening @jpince!

**Pull request closed without merging**
