### PR TITLE
LPS-73189 SF

### PR DESCRIPTION
**Pull request by 4lejandrito**
@jkappler this one must be one...

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@shuyangzhou PortletContainerUtil.java NPE I'm seeing it a lot now

**Comment by brianchandotcom** [comment]
@4lejandrito one of the classes says:

```
As of 1.2.0, as of 7.0.0 replaced by {@link #AttachmentContentUpdater}
```

Doesn't make sense to me. Please resend.

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
