### PR TITLE
LPS-171382 Add Remove Thumbnail for Utility Pages

### PR DESCRIPTION
**Pull request by alessandromalves**
This is only for master
https://issues.liferay.com/browse/LPS-171382
cc.: @lfbesada @BarbaraCabrera

### CODE REVIEW

**Comment by alessandromalves** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/10673

:x: ci:test:stable - 26 out of 28 jobs passed
:x: ci:test:relevant - 160 out of 173 jobs passed in 1 hour 42 minutes

**Comment by alessandromalves** [comment]
ci:reopen

**Comment by lfbesada** [comment]
I will resend this PR with changes

**Comment by lfbesada** [comment]
ci:close

**Pull request closed without merging**
