### PR TITLE
LPS-68298 Add protected setter again for testing only

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by jbalsas** [comment]
ci:reopen

**Comment by jbalsas** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@jbalsas @Ithildir I think breakage is real. Please resend.

**Comment by kenjiheigel** [comment]
@jbalsas, there's a source formatter issue and it's throwing a lot of console errors after start up: 

>      [exec] 19:40:55,944 ERROR [http-nio-8080-exec-7][ComboServlet:89] java.lang.IllegalArgumentException: Path frontend-js-spa-web/liferay/init.es.js does not start with a "/" character
     [exec] java.lang.IllegalArgumentException: Path frontend-js-spa-web/liferay/init.es.js does not start with a "/" character
     [exec] 	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:454)
     [exec] 	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:221)
     [exec] 	at com.liferay.portal.servlet.ComboServlet.getResourceRequestDispatcher(ComboServlet.java:409)
     [exec] 	at com.liferay.portal.servlet.ComboServlet.doService(ComboServlet.java:221)
     [exec] 	at com.liferay.portal.servlet.ComboServlet.service(ComboServlet.java:86)
     [exec] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
     [exec] 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:119)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:188)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:96)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:142)
     [exec] 	at com.liferay.portal.servlet.filters.language.LanguageFilter.processFilter(LanguageFilter.java:82)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:112)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:142)
     [exec] 	at com.liferay.portal.servlet.filters.gzip.GZipFilter.processFilter(GZipFilter.java:125)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:112)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:142)
     [exec] 	at com.liferay.portal.servlet.filters.cache.CacheFilter.processFilter(CacheFilter.java:428)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:112)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:142)
     [exec] 	at com.liferay.portal.servlet.filters.etag.ETagFilter.processFilter(ETagFilter.java:86)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:112)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:142)
     [exec] 	at com.liferay.portal.servlet.filters.header.HeaderFilter.processFilter(HeaderFilter.java:96)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:112)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:142)
     [exec] 	at com.liferay.portal.sharepoint.SharepointFilter.processFilter(SharepointFilter.java:88)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:112)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:142)
     [exec] 	at com.liferay.portal.servlet.filters.virtualhost.VirtualHostFilter.processFilter(VirtualHostFilter.java:257)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:112)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:188)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:96)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:168)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:96)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:168)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:96)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:188)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:96)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilter.doFilter(InvokerFilter.java:99)
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
     [exec] 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
     [exec] 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
     [exec] 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
     [exec] 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
     [exec] 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
     [exec] 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
     [exec] 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
     [exec] 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
     [exec] 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
     [exec] 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
     [exec] 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
     [exec] 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
     [exec] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [exec] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [exec] 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
     [exec] 	at java.lang.Thread.run(Thread.java:745)
     [exec] 19:40:56,942 ERROR [http-nio-8080-exec-7][status_jsp:950] Path frontend-js-spa-web/liferay/init.es.js does not start with a "/" character
     [exec] 19:40:59,085 ERROR [http-nio-8080-exec-10][ComboServlet:89] java.lang.IllegalArgumentException: Path frontend-js-spa-web/liferay/init.es.js does not start with a "/" character
     [exec] java.lang.IllegalArgumentException: Path frontend-js-spa-web/liferay/init.es.js does not start with a "/" character
     [exec] 	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:454)
     [exec] 	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:221)
     [exec] 	at com.liferay.portal.servlet.ComboServlet.getResourceRequestDispatcher(ComboServlet.java:409)
     [exec] 	at com.liferay.portal.servlet.ComboServlet.doService(ComboServlet.java:221)
     [exec] 	at com.liferay.portal.servlet.ComboServlet.service(ComboServlet.java:86)
     [exec] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
     [exec] 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:119)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:188)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:96)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:142)
     [exec] 	at com.liferay.portal.servlet.filters.language.LanguageFilter.processFilter(LanguageFilter.java:82)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:112)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:142)
     [exec] 	at com.liferay.portal.servlet.filters.gzip.GZipFilter.processFilter(GZipFilter.java:125)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:112)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:142)
     [exec] 	at com.liferay.portal.servlet.filters.cache.CacheFilter.processFilter(CacheFilter.java:428)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:112)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:142)
     [exec] 	at com.liferay.portal.servlet.filters.etag.ETagFilter.processFilter(ETagFilter.java:86)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:112)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:142)
     [exec] 	at com.liferay.portal.servlet.filters.header.HeaderFilter.processFilter(HeaderFilter.java:96)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:112)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:142)
     [exec] 	at com.liferay.portal.sharepoint.SharepointFilter.processFilter(SharepointFilter.java:88)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:112)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:142)
     [exec] 	at com.liferay.portal.servlet.filters.virtualhost.VirtualHostFilter.processFilter(VirtualHostFilter.java:257)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:112)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:188)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:96)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:168)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:96)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:168)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:96)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:188)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:96)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilter.doFilter(InvokerFilter.java:99)
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
     [exec] 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
     [exec] 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
     [exec] 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
     [exec] 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
     [exec] 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
     [exec] 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
     [exec] 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
     [exec] 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
     [exec] 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
     [exec] 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
     [exec] 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
     [exec] 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
     [exec] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [exec] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [exec] 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
     [exec] 	at java.lang.Thread.run(Thread.java:745)
     [exec] 19:40:59,186 ERROR [http-nio-8080-exec-10][status_jsp:950] Path frontend-js-spa-web/liferay/init.es.js does not start with a "/" character
     [exec]     LIFERAY_ERROR: java.lang.IllegalArgumentException: Path frontend-js-spa-web/liferay/init.es.js does not start with a "/" character
     [exec]     LIFERAY_ERROR: Path frontend-js-spa-web/liferay/init.es.js does not start with a "/" character
     [exec]     LIFERAY_ERROR: java.lang.IllegalArgumentException: Path frontend-js-spa-web/liferay/init.es.js does not start with a "/" character
     [exec]     LIFERAY_ERROR: Path frontend-js-spa-web/liferay/init.es.js does not start with a "/" character
     [exec] 19:41:01,223 ERROR [http-nio-8080-exec-3][ComboServlet:89] java.lang.IllegalArgumentException: Path frontend-js-spa-web/liferay/init.es.js does not start with a "/" character
     [exec] java.lang.IllegalArgumentException: Path frontend-js-spa-web/liferay/init.es.js does not start with a "/" character
     [exec] 	at org.apache.catalina.core.ApplicationContext.getRequestDispatcher(ApplicationContext.java:454)
     [exec] 	at org.apache.catalina.core.ApplicationContextFacade.getRequestDispatcher(ApplicationContextFacade.java:221)
     [exec] 	at com.liferay.portal.servlet.ComboServlet.getResourceRequestDispatcher(ComboServlet.java:409)
     [exec] 	at com.liferay.portal.servlet.ComboServlet.doService(ComboServlet.java:221)
     [exec] 	at com.liferay.portal.servlet.ComboServlet.service(ComboServlet.java:86)
     [exec] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
     [exec] 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:119)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:188)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:96)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:142)
     [exec] 	at com.liferay.portal.servlet.filters.language.LanguageFilter.processFilter(LanguageFilter.java:82)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:112)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:142)
     [exec] 	at com.liferay.portal.servlet.filters.gzip.GZipFilter.processFilter(GZipFilter.java:125)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:112)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:142)
     [exec] 	at com.liferay.portal.servlet.filters.cache.CacheFilter.processFilter(CacheFilter.java:428)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:112)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:142)
     [exec] 	at com.liferay.portal.servlet.filters.etag.ETagFilter.processFilter(ETagFilter.java:86)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:112)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:142)
     [exec] 	at com.liferay.portal.servlet.filters.header.HeaderFilter.processFilter(HeaderFilter.java:96)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:112)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:142)
     [exec] 	at com.liferay.portal.sharepoint.SharepointFilter.processFilter(SharepointFilter.java:88)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:112)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:142)
     [exec] 	at com.liferay.portal.servlet.filters.virtualhost.VirtualHostFilter.processFilter(VirtualHostFilter.java:257)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:112)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:188)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:96)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:168)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:96)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:168)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:96)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:188)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:96)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilter.doFilter(InvokerFilter.java:99)
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
     [exec] 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
     [exec] 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
     [exec] 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
     [exec] 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
     [exec] 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
     [exec] 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
     [exec] 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
     [exec] 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
     [exec] 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
     [exec] 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
     [exec] 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
     [exec] 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
     [exec] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [exec] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [exec] 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
     [exec] 	at java.lang.Thread.run(Thread.java:745)

**Comment by jbalsas** [comment]
I'm checking this... it was working the day before: https://github.com/jbalsas/liferay-portal/pull/650 😢

**Comment by jbalsas** [comment]
Okay, figured it out... it was an issue with the configuration. I've resent to @Ithildir at https://github.com/ithildir/liferay-portal/pull/528 to re-apply the gradle changes and resend.

Thanks!

**Pull request closed without merging**
