### PR TITLE
LPS-74544

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Let the test finish!

Last pull for portal!!

**Comment by hhuijser** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@hhuijser can you send a follow up pull:

InetAddress localHost = InetAddress.getLocalHost

should be:

InetAddress inetAddress = InetAddress.getLocalHost

or

InetAddress localHostInetAddress = InetAddress.getLocalHost

Thx

**Comment by brianchandotcom** [comment]
@hhuijser same for RichTextString richStringCellValue

it should be

*RichTextString

I only do this for complex objects that are not Lists, etc.

Thx

**Pull request closed without merging**
