### PR TITLE
LPS-58210 delete a bunch of code

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
fyi @jorgeFerrer

**Comment by JorgeFerrer** [comment]
Looks great @juliocamarero Removing this code will make maintenance much easier.

You should ask the WCM test engineers to keep a close eye on potential issues caused by this. There shouldn't be any, but when removing code it's hard to be 100% sure.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d975dbea27...deeb75fc30

**Comment by brianchandotcom** [comment]
Nice job @juliocamarero

**Pull request closed without merging**
