### PR TITLE
Lps 75858

### PR DESCRIPTION
**Pull request by shuyangzhou**
@brianchandotcom please do a portal-impl release after merge, thanks!

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1aca85929c...a7ea4d959d

**Comment by brianchandotcom** [comment]
@shuyangzhou published a new jar, 2.23.0, for you.

**Comment by shuyangzhou** [comment]
Thanks @brianchandotcom !

**Pull request closed without merging**
