### PR TITLE
LPS-69934 Add missing Git files

### PR DESCRIPTION
**Pull request by Ithildir**
cc @jpince and @stsquared99

### CODE REVIEW

**Comment by jpince** [comment]
@brianchandotcom please merge asap! All pulls on master are currently auto-closing

@stsquared99 do you need to commit these files in the future?

**Comment by jpince** [comment]
Thanks @Ithildir!

**Comment by Ithildir** [comment]
I pushed it on `master`: https://github.com/liferay/liferay-portal/commit/46f94ee0913150a1f236142b51ed7864499ebce8

**Comment by Ithildir** [comment]
ci:stop

**Pull request closed without merging**
