### PR TITLE
LPS-64093 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by rotty3000**
/cc @juangon @ngriffin7a

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@rotty3000 I sent it back to Vernon https://github.com/vsingleton/liferay-portal/pull/2 I tried cleaning it up as much as I could.. thx.

**Comment by rotty3000** [comment]
Why? It was working perfectly!

On Wed, Mar 30, 2016 at 11:16 PM, Brian Chan <notifications@github.com>
wrote:

> @rotty3000 <https://github.com/rotty3000> I sent it back to Vernon
> vsingleton#2 <https://github.com/vsingleton/liferay-portal/pull/2> I
> tried cleaning it up as much as I could.. thx.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/38331#issuecomment-203732833>
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by brianchandotcom** [comment]
See comment in https://github.com/vsingleton/liferay-portal/pull/2

The variable names in OrderUtil were practically obfuscated....

**Comment by brianchandotcom** [comment]
I've spent like 2 hours today fixing/cleaning up that pull already.. (while waiting for GA1 to upload)

OrderUtil was just messy...

**Comment by juangon** [comment]
@brianchandotcom OrderUtil was a copy/paste of what Vernon did for Liferay Faces (which works even better than Oracle's JSF ordering). So you just want to rename things there right? I wouldn't touch any of the logic as it had been deeply tested.

**Comment by brianchandotcom** [comment]
@juangon Ah... makes a lot of sense now.. I thought Vernon wrote it and then passed it to you.

Don't change any logic.. just renaming so everything is clear...

Thx @juangon

**Pull request closed without merging**
