### PR TITLE
LRQA-62735 | master

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://issues.liferay.com/browse/LRQA-62735

Note: No need to run ci:forward.

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/948a1968f9...19d7b9fb5d

**Comment by brianchandotcom** [comment]
@JoyceWang08211 please send backports to 7.3.x and beyond.

**Comment by JoyceWang08211** [comment]
7.3.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/32056
7.2.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/32057
7.1.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/32058
7.0.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/32059

**Pull request closed without merging**
