### PR TITLE
LPS-91441 gradle baseline

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:test

**Comment by izaera** [comment]
relevant tests failed but comment says "This pull contains no unique failures."

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6fbca1b904...21cdf2f1bb

**Comment by brianchandotcom** [comment]
@izaera Nice. See 21cdf2f

**Pull request closed without merging**
