### PR TITLE
LPS-86506 Fail search organization with tag

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by stsquared99** [comment]
@drewbrokke

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/baa8da71b4...a5f8acd783

**Comment by brianchandotcom** [comment]
Nice job @stsquared99  :)

**Comment by brianchandotcom** [comment]
@stsquared99 please backport. Thx.

**Pull request closed without merging**
