### PR TITLE
LPS-193390 Merge DirectServletRegistry interface and impl into Util in kernel

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:reopen

**Comment by julschong** [comment]
this pr is rebased onto brianchandotcom/master

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fc38e08015...e86ef4fbdb

**Comment by brianchandotcom** [comment]
@julschong see e86ef4fbdb33d951342b32f8c348ff6b209c9e9b

**Pull request closed without merging**
