### PR TITLE
LPS-75131

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:reopen

**Comment by ChrisKian** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
I think this may be real? Please resend @matethurzo @ChrisKian

**Comment by brianwulbern** [comment]
@matethurzo @ChrisKian any update on the resend?

**Comment by ChrisKian** [comment]
Hey @brianchandotcom and @brianwulbern,  

I don't believe these errors are due to my code changes.  All the failed tests on occur "when adding a file entry", however, my changes only affect the layout import process during file validation.

Further, the only way my changes would appear is [through a LARTypeException](https://github.com/brianchandotcom/liferay-portal/pull/52167/commits/2be6b94851fbaf1da8d00e659a1a284f495a3c1f#diff-22362941cbc7cc6db8a7a04ebac3ae64R934), or the lack of one.  Once we pass or fail [this check](https://github.com/brianchandotcom/liferay-portal/pull/52167/commits/2be6b94851fbaf1da8d00e659a1a284f495a3c1f#diff-22362941cbc7cc6db8a7a04ebac3ae64R934), my changes no longer have any effect.

Please let me know what you think.  I'd be happy to rebase the solution for you if needed.  Thanks!

**Comment by brianwulbern** [comment]
@ChrisKian CI agrees with you.  See Mate's resend here: https://github.com/brianchandotcom/liferay-portal/pull/52584

**Pull request closed without merging**
