### PR TITLE
Upgrade Process: Apply pattern to Lock Service and Kaleo Workflow Service

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by migue** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@migue I think this is good to go. The other error messages were fixed by Shuyang in another pull.

I'm going to ci:retest just to be safe.

**Comment by migue** [comment]
Just a failure connecting to the mail server ... Nothing related but running the tests again
ci:retest

**Comment by brianchandotcom** [comment]
Thx @migue I asked them to fix the root cause of the postfix server dying, so hopefully that false positive won't come up again. I'll merge this in asap.

**Comment by brianchandotcom** [comment]
@migue can you send a follow up pull to fix the issue with 82dfc5e20c947e84d2515c0db2beb26efb3b1cc8

I don't think the MVCC part is right. I merged in the rest. Thx @migue 

I'm really happy with this new pattern you've come up with.

**Pull request closed without merging**
