### PR TITLE
[FWD-PORT] LPS-65589 Shorten the URL if larger than max size

### PR DESCRIPTION
**Pull request by adolfopa**
This is a forward port of https://github.com/brianchandotcom/liferay-plugins-ee/pull/18475.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/83bd72e697...37b6ba5430

**Comment by brianchandotcom** [comment]
@adolfopa see 37b6ba54300186acf04f2454362046ca665779ad thx

**Comment by brianchandotcom** [comment]
@shuyangzhou Split package randomly breaks.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/39889

**Pull request closed without merging**
