### PR TITLE
LPS-85359 Update test snapshots

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:retest

**Comment by brunobasto** [comment]
ci:reopen

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/98b5793cb4...dfe3fe7ee4

**Pull request closed without merging**
