### PR TITLE
Lps 65086 counter local service test

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0eb7c4fb5f...b6614d6d91

**Comment by sharonchoi** [comment]
The ApplicationdisplaytemplatesUsecase#AddRSSADTViaPortletConfiguration failure is unrelated and has been failing multiple pulls. 
https://testray.liferay.com/home/-/testray/case_results/40139533

Test has been disabled at head:
liferay@6fd2f84

WEM QA will look into the issue and restore the test LRQA-24557.

**Pull request closed without merging**
