### PR TITLE
LRQA-32801-1 Readable poshi translator: Add basic support for 'for' loops and conditionals

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-32801

#### Changes in this pull: 
* Trim strings where possible
* Uncouple logic - split the readable blocks into a list, then parse through that list instead of line by line.
* Add support for _for_ tags
* Add basic support (no nesting or logical operators) for _if, then, else, isset, equals, condition_ tags. 

#### Translation status
On master:
```
1163 / 2135 (54%) test commands were successfully translated
11 / 2135 test commands fail due to setup failures
1402 / 2135 test commands fail due to teardown failures
92 / 337 (27%) test files were successfully translated with 157 tests
Test commands that fail two way conversion: 428
```
With this pull: 
```
1414 / 2135 (66%) test commands were successfully translated
8 / 2135 test commands fail due to setup failures
108 / 2135 test commands fail due to teardown failures
182 / 337 (54%) test files were successfully translated with 520 tests
Test commands that fail two way conversion: 177
```

#### Preview Link
https://github.com/kenjiheigel/liferay-portal/commit/9e01be181b74cdbf2fd67ef96d7f44e825474285

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:reopen

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/07a33635ec...d905e2decc

**Comment by brianchandotcom** [comment]
@kenjiheigel @pyoo47 nice job

See d905e2decced8ebe00c7a08c042db5de26a2f3d8 thx

**Pull request closed without merging**
