### PR TITLE
Lps 195671 merge users admin 9 13 1

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@julschong @shuyangzhou this seems very strange

import com.liferay.portlet.usersadmin.util.UsersAdminUtil

That's exported via portal-impl?

It seems like we're going backwards? Please resend.

**Comment by brianchandotcom** [comment]
@julschong @shuyangzhou I'm ok with changes like in this PR https://github.com/brianchandotcom/liferay-portal/pull/141443 for portal-kernel/src/com/liferay/portal/kernel/util/DateFormatFactoryUtil.java

because at least it's still in kernel.

**Comment by julschong** [comment]
@brianchandotcom Hi Brian, 
per my discussion with Shuyang, 
our goal for this long task of [removing spring beans](https://liferay.atlassian.net/browse/LPS-190426) and cleaning the dependencies between kernel and impl is to prepare to merge kernel and impl into one. And we think that we most likely will be merging kernel classes into impl since kernel has less file counts. So our workflow now is moving these Utils to impl if there is no other kernel usages.
Thanks

**Comment by julschong** [comment]
ci:reopen

**Comment by julschong** [comment]
reopening PR so our discussion is more visible

**Comment by brianchandotcom** [comment]
@julschong @shuyangzhou got it.......

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/790353a20e...dff05c862a

**Pull request closed without merging**
