### PR TITLE
LPS-157670 Recover logic to upgrade from 6.1

### PR DESCRIPTION
**Pull request by achaparro**
LPS-157670

### CODE REVIEW

**Comment by achaparro** [comment]
ci:reopen

**Comment by achaparro** [comment]
Tests passed:
https://github.com/liferay-uniform/liferay-portal/pull/502#issuecomment-1186040499

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/13937620c2...920a5899be

**Comment by brianchandotcom** [comment]
Thx @achaparro !!!

See c2766c83be89ca0a4954767f0dc0a35fdf3399c7 4ea8212238f7cfa396360a626b8213de58cc7b66 and 920a5899be5e1e0f8374d265273cb7da6e9382e3

I noticed this bug 640d462f7582a5eb638a5ef13b1ef657757b8e94 yesterday when testing upgrades from 6.1.x

**Pull request closed without merging**
