### PR TITLE
LPS-79503 Explicitly listing out what you want to import is generally…

### PR DESCRIPTION
**Pull request by shuyangzhou**
… a bad idea in most cases. And here it breaks the DeleteAfterTestRun, as test.rule package is not included.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
CC @arboliveira

**Comment by brianchandotcom** [comment]
@arthurchan35 looks like you didn't cause the regression via LPS-79348 like I thought, so I'm recommitting LPS-79348

**Comment by brianchandotcom** [comment]
@ealonso fyi.. fixed it now, not related to you.

**Comment by arboliveira** [comment]
@shuyangzhou Understood. I'd very much prefer to have separate test util modules for integration and unit tests. The `Import-Package` clause in this module's `bnd.bnd` degraded over time as a consequence of successive changes by many developers, adding more test utilities while still attempting to preserve the ability to share between integration and unit tests.

**Comment by tomwang2011** [comment]
@brianchandotcom @arthurchan35 LPS-79348 still causes integration failures not related to this pull, the failures are: https://test-1-11.liferay.com/job/test-portal-acceptance-upstream-batch(master)/21156/ 

Thanks!

**Comment by arboliveira** [comment]
I was already fixing a random failure condition in `CalendarBookingIndexerIndexedFieldsTest.testIndexedFields`, reported earlier by BChan, but it's most likely an unrelated problem.

**Comment by arthurchan35** [comment]
@tomwang2011, @arboliveira, @brianchandotcom,
The newly reported one test failure of _CalendarBookingIndexerIndexedFieldsTest.testIndexedFields_ was indeed caused by my fix, I have pull request ready here:
https://github.com/brianchandotcom/liferay-portal/pull/57461

**Pull request closed without merging**
