### PR TITLE
LPS-103465 We cannot use PortletFileRepositoryUtil because of LPS-103720, so we create repository and folder by hand

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso, @ruben-pulido

**Comment by jkappler** [comment]
hey @jpince, first time I see the issue. Will take a closer look tomorrow and see if I can fix and send to BChan

**Comment by brookedalton** [comment]
Hey @jkappler I created https://issues.liferay.com/browse/LPS-103754 for this issue

**Comment by jpince** [comment]
Thank you both :)

**Comment by brianchandotcom** [comment]
This seems weird... @jkappler can you resend this to @shuyangzhou and talk about the chicken egg problem.

They've been working on a lot of these issues for Repository right now so they have context. Thx.

**Pull request closed without merging**
