### PR TITLE
LPS-71107 Update npm-shrinkwrap (auto-generated)

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest - Source build timed out while waiting for local-git synchronization.

**Comment by brianchandotcom** [comment]
@pyoo47 hung again?

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@jbalsas can you backport this? Thx.

**Comment by brianchandotcom** [comment]
@jbalsas nvm, I just did it.

**Comment by jbalsas** [comment]
Thanks a lot @brianchandotcom!

**Pull request closed without merging**
