### PR TITLE
LPS-200940 Widget content is lost during content page reindex

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://liferay.atlassian.net/browse/LPS-200940

@lfbesada

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/14560

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/18a5f3a50e...01c1dfddf9

**Comment by brianchandotcom** [comment]
@lfbesada just 01c1dfddf9c025a37c0736750f348e722da1deeb

**Pull request closed without merging**
