### PR TITLE
LPS-82444 SF

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Sent to 7.1.x here: https://github.com/brianchandotcom/liferay-portal-ee/pull/20625

**Comment by jkappler** [comment]
ci:reopen

**Comment by brianchiu** [comment]
That functional test failure is fine. It's also happening in upstream.

**Comment by brianchandotcom** [comment]
@jkappler conflict with your other pull.  Please resend.

**Pull request closed without merging**
