### PR TITLE
LRQA-28693 Redownload any invalid .zip file. 

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-28693

This pull reverts all the previous changes that only tested certain zip files in favor of new changes that will automatically test all .zip files that are downloaded via mirrors-get.

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:reopen

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pyoo47 mirrors-get is doing too much. Let's turn it into an Ant task that others can just share. Thx.

**Pull request closed without merging**
