### PR TITLE
LPS-75065 Uses new class

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
@kenjiheigel I've seen inconsistent failures in PoshiElementFactoryTest.testPoshiToReadableToXML (another example in this [adaptive media pull](https://github.com/liferay/liferay-portal/pull/2031#issuecomment-333694662)). Can you please look into this?

**Comment by kenjiheigel** [comment]
@jpince, I looked into it and found that it's been something happening inconsistently. I couldn't reproduce this locally, so I updated those tests to give us more information about the failure. Once my pull to Peter goes in, it should shed a bit more light into why this is failing. 

https://github.com/pyoo47/liferay-portal/pull/444

**Comment by brianchandotcom** [comment]
@ealonso aren't these test related to the asset changes? Please resend?

**Pull request closed without merging**
