### PR TITLE
LPS-102405 Get article for specified groupId because resource primary key is equal in live and in staging

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:staging

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ae508581ad...0e46def498

**Comment by brianchandotcom** [comment]
@pavel-savinov see 0044b26bce48063d4b998585d668d0229e0489e3

**Pull request closed without merging**
