### PR TITLE
Fix project template tests

### PR DESCRIPTION
**Pull request by lawrence-lee**
@brianchandotcom Can you please publish a new version of `gradle-plugins-workspace`? It should be version `1.10.0`

I also skipped the tests because the results are here: https://github.com/lawrence-lee/liferay-portal/pull/75

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:stop

**Comment by lawrence-lee** [comment]
ci:stop

**Comment by lawrence-lee** [comment]
test results are here: https://github.com/lawrence-lee/liferay-portal/pull/75

**Comment by lawrence-lee** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:stop per Lawrence's comment

**Pull request closed without merging**
