### PR TITLE
LPS-80795 Uses new keys

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by ealonso** [comment]
ci:reopen

**Comment by ealonso** [comment]
Hey @brianchandotcom,

I don't know what happened with this code, but seems to be not merge.

Regards,
Eudaldo.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/986e87cbf0...074b6bce3f

**Pull request closed without merging**
