### PR TITLE
LPS-140253 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-140253

This is only for master.

@jkappler
@ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
I'm sending the PR directly. The sf failure is unrelated to the changes in this PR.
See https://github.com/liferay-echo/liferay-portal/pull/6501
❌ ci:test:sf - 0 out of 1 jobs passed in 14 minutes
✔️ ci:test:stable - 11 out of 11 jobs passed
✔️ ci:test:relevant - 26 out of 31 jobs passed in 2 hours 10 minutes

**Comment by brianchandotcom** [comment]
@jkappler 

we can't do this

for-example,-if-the-virtual-host-is-www.helloworld.com-and-the-friendly-url-is-/helloworld=For example, if the virtual host is <strong>www.helloworld.com</strong> and the friendly URL is <strong>/helloworld</strong>, <strong>{0}://www.helloworld.com</strong> is mapped to <strong>{1}/helloworld</strong>.

The other keys are old. In your case, you need to pass in {0} and {1} when caling the key. We want to ensure that translators cannot break the example. Please resend. Thx.

**Comment by brianchandotcom** [comment]
@jkappler So pass in www.helloworld.com and /helloworld as parameters as well

**Pull request closed without merging**
