### PR TITLE
LPS-94845 Baseline

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso, @jorgeFerrer, @brianchiu

**Comment by jpince** [comment]
ci:test:wem-msb

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a2ad97da58...6c64127571

**Comment by brianchandotcom** [comment]
@jkappler see 6c64127571e3f17baea38e96175b67ee80531c38 and 73459f8adfe8f1c903c7f11dd92e9da63bc716e5

**Pull request closed without merging**
