### PR TITLE
LPS-66495 Set tooltips for the theme icon in the fullscreen source editor

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
cc/ @sergiogonzalez

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a2bfd22c58...9610dd2b0b

**Comment by brianchandotcom** [comment]
@jbalsas fyi as well

**Comment by jbalsas** [comment]
👍, thanks @brianchandotcom, @ambrinchaudhary!

**Pull request closed without merging**
