### PR TITLE
 LPS-94222 Bundle and minify frontend-js-jquery-web

### PR DESCRIPTION
**Pull request by wincent**
As part of the front-end performance audit, noticed that this module was causing three separate requests for unminified files. With this PR, when in `JsFastLoad` mode, we instead serve a minimized and bundled response, dropping us from 3 requests to 1, and from about about 271k down to 55k.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1fad1ba99c...b6dd7bbd9a

**Comment by brianchandotcom** [comment]
Nice job @wincent ! See my changes in usptream.

@shuyangzhou can someone from your team look at 3630b3e35ccaaa9566e41578c86465457c28b392

I think they're using "volatile" and OSGi setters in a way you do not agree with. Please have someone fix and notify @wincent and @izaera

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/71793

**Comment by wincent** [comment]
Thanks @brianchandotcom, @shuyangzhou for those follow-ups.

**Pull request closed without merging**
