### PR TITLE
LPS-74544

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
cc @petershin @shuyangzhou @tomwang2011 @Preston-Crary @lanceji92674957

**Comment by hhuijser** [comment]
pull for 7.0.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/19746

**Comment by hhuijser** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
