### PR TITLE
LPS-89234 Lambda friendly internal signatures without checked exceptions

### PR DESCRIPTION
**Pull request by arboliveira**
❌ **ci:test:search - 12 out of 16 jobs passed in 1 hour 31 minutes 51 seconds 741 ms**
https://github.com/arboliveira/liferay-portal/pull/650#issuecomment-455650136

Branch `master` is contaminated. "Failures unique to this pull" are unrelated to Search.

https://github.com/giros/liferay-portal/pull/77 is addressing *Error message: Unable to find user 0* 

Functional tests: `Search#SearchDeletedWebContent` AND `Search#ViewStagedAndLiveContentInSearchResults` due to issue with deleting web content articles. Thanks @xbrianlee @joshchong

*[Task] Lambda friendly internal signatures without checked exceptions*
https://issues.liferay.com/browse/LPS-89234

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jbalsas can you check out the JS unit failure? Thx.

merged @arboliveira

**Comment by jbalsas** [comment]
Hey @brianchandotcom, there is an error in `portal-workflow-reports-web`, not sure who owns that module so they can take a look, maybe @inacionery or @rafaprax?

@vicnate5, @john-co could we please prioritize the changes in QA engineering we've been asking about this to avoid this from happening over and over? The very least... could we share this with all QAs so they own their own js unit failures so this don't continuously get ignored and bumped to me?

Thanks!

**Comment by inacionery** [comment]
Hey @jbalsas,

This issue has already been fixed here https://github.com/brianchandotcom/liferay-portal-ee/pull/23047
But this SF https://github.com/brianchandotcom/liferay-portal-ee/commit/7f8fbbb98fd1d8b6e065e63c16b8499069d1b020 broke again, I just sent the fix https://github.com/brianchandotcom/liferay-portal-ee/pull/23053

Thx!

**Comment by john-co** [comment]
> Hey @brianchandotcom, there is an error in `portal-workflow-reports-web`, not sure who owns that module so they can take a look, maybe @inacionery or @rafaprax?
> 
> @vicnate5, @john-co could we please prioritize the changes in QA engineering we've been asking about this to avoid this from happening over and over? At the very least... could we share this with all QAs so they own their own js unit failures so this don't continuously get ignored and bumped up to us?
> 
> Thanks!

@jbalsas, the requirements needed to reorgnize js tests are still assigned to @bryceosterhaus.
https://issues.liferay.com/browse/LRQA-45747, once required updates on liferay-jest-junit-reporter are complete it should create better visibility on which specific component's test is failing.

**Pull request closed without merging**
