### PR TITLE
[TS]

### PR DESCRIPTION
**Pull request by david-gutierrez-mesa**
Hi, this is related to https://issues.liferay.com/browse/PTR-3457. 

@lfbesada has the full context and we have already discussed the fix :)
cc/ crodriguezy

### CODE REVIEW

**Comment by david-gutierrez-mesa** [comment]
Sending manually since failures are not related https://github.com/liferay-echo/liferay-portal/pull/10308#issuecomment-1317670864

SF here: https://github.com/liferay-echo/liferay-portal/pull/10308#issuecomment-1316808876

**Comment by david-gutierrez-mesa** [comment]
ci:reopen

**Comment by david-gutierrez-mesa** [comment]
ci:reopen

**Comment by lfbesada** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/edea3691db...f24c95d56b

**Comment by brianchandotcom** [comment]
@david-gutierrez-mesa can you send a test for this? Thx.

**Comment by ealonso** [comment]
@crodriguezy I think the previous message about test is for you

**Pull request closed without merging**
