### PR TITLE
LPS-89891 Adds filters to global templates

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
cc: @brianchiu @kyle-miho

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchiu** [comment]
@ealonso 
I'll take a look!

**Comment by brianchiu** [comment]
ci:close

**Comment by brianchiu** [comment]
Testing here:
https://github.com/brianchiu/liferay-portal/pull/1769

**Comment by brianchiu** [comment]
Pull request sent back to Eudaldo with feedback.
https://github.com/ealonso/liferay-portal/pull/2134

**Pull request closed without merging**
