### PR TITLE
LPS-166501 fixed management bar tooltip message

### PR DESCRIPTION
**Pull request by kevenleone**

### CODE REVIEW

**Comment by kevenleone** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a8b00a8fd2...2c26d3bb8b

**Comment by bryceosterhaus** [comment]
Hey @kevenleone, I saw that this PR caused failures for CI on upstream. I am wondering why this PR was forwarded to Brian from [here](https://github.com/liferay/liferay-portal/pull/5068) without any sort of CI pass or QA approval?

Anything forwarded should have passing CI for `ci:test:sf` and `ci:test:relevant` (that's the reason for [this message](https://github.com/liferay/liferay-portal/pull/5068#issuecomment-1303589756)), or if for some reason those tests are flakey you can get a QA approval by having someone verify the failures of those CI tests.

**Comment by kevenleone** [comment]
@bryceosterhaus I tried using CI but was not triggering, I was not expecting to cause any problems, for that I'm sorry.

I built this module from scratch and I was not aware that a test was written using that selector

I can revert the commit and send it throw CI and ask to someone fix the test if necessary.

Thanks.

**Comment by bryceosterhaus** [comment]
> I tried using CI but was not triggering, I was not expecting to cause any problems

If this is the case, we still can't forward to Brian without proper QA checks. If for some reason CI is not working, you need to contact a member from QA and have them sign off on the changes and have them run the tests locally. Even if we don't expect problems of the changes are really minuscule, we still need to get the green light from QA or CI tests to ensure quality, otherwise we can not only cause issues for our own projects but we cause issues for all of engineering at Liferay.

**Pull request closed without merging**
