### PR TITLE
LPS-52990 ran ant build-wsdd

### PR DESCRIPTION
**Pull request by marcellustavares**
Hey Brian, The `PortalClientBuilderTest` seems to have an issue. I'm not sure what it checks exactly but the test is raising `Could not build http://localhost:8080/Portal_ClassNameService?wsdl`.

I've fixed the DDM wsdd but the ClassName problem still persists locally.

Regards

### CODE REVIEW

**Comment by brianchandotcom** [comment]
I'll fix it @marcellustavares and show you what the problem is

**Comment by marcellustavares** [comment]
Thanks a lot @brianchandotcom, will check your commit.

**Comment by brianchandotcom** [comment]
Actually, I'll pass it to @shuyangzhou since he recently added the test.

**Comment by brianchandotcom** [comment]
@shuyangzhou will send it to matt or william to resend to me. Thx.

**Comment by marcellustavares** [comment]
@brianchandotcom, do you want me to send a PR to Shuyang?

**Comment by brianchandotcom** [comment]
@marcellustavares no. He's pulling it from me.

**Comment by willnewbury** [comment]
ci:retest

**Pull request closed without merging**
