### PR TITLE
LPS-92361 Uses a new param to show the selected roles when we are unassigning them or show not selected roles when we are assigning them

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@john-co I see the startup error from yesterday in this pull `No theme found for specified theme id admin_WAR_admintheme. Returning the default theme.` But it's strange that I don't see it in other pulls or in upstream acceptance. Maybe the slave didn't rebase to head properly. Can you and @kyle-miho @brianchiu please keep an eye on the retest?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/36e2511792...4acbf5bc4c

**Comment by brianchandotcom** [comment]
@ealonso see upstream for my changes.

**Comment by john-co** [comment]
@jpince looks like the error was not reproducible in the retest.

cc/ @kyle-miho, @brianchiu

**Pull request closed without merging**
