### PR TITLE
LPS-74672 Conversions with permission

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @IstvanD @topolik

**Comment by topolik** [comment]
@sergiogonzalez I think this is already in 6.2 so 85e427f might be needed.

**Comment by brianchandotcom** [comment]
@shuyangzhou I've seen this UTC error many times.. can you take a look? It's quite random.

**Comment by shuyangzhou** [comment]
@brianchandotcom this is in @alee8888 's queue. We need to add "-Duser.timezone=GMT" to websphere's jvm start script.

**Comment by sergiogonzalez** [comment]
Hey @topolik thanks for bringing that up. I talked to @IstvanD about it but we didn't find the reason why that should be there, but what you says makes sense.
I'll remove that commit and resend to Brian.
Thanks!

**Comment by sergiogonzalez** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/52329

**Pull request closed without merging**
