### PR TITLE
master-qa-25808

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LRQA-25808

### CODE REVIEW

**Comment by jpince** [comment]
@brianchandotcom this is to resolve the sites failures introduced in https://github.com/brianchandotcom/liferay-portal/pull/40533

**Comment by brianchandotcom** [comment]
Thx @jpince

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
