### PR TITLE
COMMERCE-10711

### PR DESCRIPTION
**Pull request by brianikim**
Resent from: https://github.com/brianchandotcom/liferay-portal/pull/130432

https://issues.liferay.com/browse/COMMERCE-10711

@brianchandotcom , this should be the exception because we are handling `Rel` updates in headless API, but we do not provide their own classes to handle this. We already have examples in code where we have `RelExceptionMappers` that are not dependent on the REST tier names.

At best, we can do following:
`NoSuchOptionExceptionMapper.java`
`NoSuchOptionRelExceptionMapper.java`
`NoSuchOptionValueRelExceptionMapper.java`

### CODE REVIEW

**Comment by brianikim** [comment]
ci:reopen

**Comment by brianikim** [comment]
@brianchandotcom , let me know if you still require changes on this PR.

**Comment by brianchandotcom** [comment]
@brianikim I'd rather do the NoSuchOption* approach. Please resend. Thx.

**Comment by brianikim** [comment]
ci:reopen

**Comment by brianikim** [comment]
@brianchandotcom , the changes have already been made on the PR.

**Comment by brianchandotcom** [comment]
@brianikim @baharturk the new NoSuch exceptions need to match existing NoSuch exceptions

See NoSuchSkuContributorCPDefinitionOptionRelExceptionMapper

It uses getErrorDescription and has a better error description than the ones in this PR.

Please resend. Thx.

**Comment by brianchandotcom** [comment]
@brianikim @baharturk contrast with all the NoSuch in the same existing package (and see my previous comment). Thx.

**Comment by brianikim** [comment]
ci:reopen

**Comment by brianikim** [comment]
for your request:

> the new NoSuch exceptions need to match existing NoSuch exceptions
> 
> See NoSuchSkuContributorCPDefinitionOptionRelExceptionMapper
> 
> It uses getErrorDescription and has a better error description than the ones in this PR.
> 
> Please resend. Thx.

The existing mappers such as NoSuchSkuContributorCPDefinitionOptionRelExceptionMapper are actually outdated because it is using :

`com.liferay.headless.commerce.core.exception.mapper.BaseExceptionMapper`

We want to use:

`com.liferay.portal.vulcan.jaxrs.exception.mapper.BaseExceptionMapper`

At best, I can make the message more detailed, but the current implementation in that PR is the one we want. I am going to re-open the PR. If you want me to make the messages more detailed, let me know, but the current implementation is the "correct" one.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4003f4ecce...30a7083523

**Comment by brianchandotcom** [comment]
Thx for the explanation @brianikim @baharturk I missed the import.

See f0794a2c987d0136b74f44970e41f7a637a77174 and 30a7083523813d2c121faecc52992fa66fc6d17c

Can you get rid of com.liferay.headless.commerce.core.exception.mapper.BaseExceptionMapper?

Thx.

**Pull request closed without merging**
