### PR TITLE
LPS-68542 Semver

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by jpince** [comment]
@sergiogonzalez I don't see this integration test failure in other pulls, can you please look into it?
```
com.liferay.portal.kernel.process.ProcessException: java.lang.AssertionError: Thread Thread[elasticsearch[Black Widow][http_server_worker][T#12],5,] caught concurrent failure: java.lang.AssertionError: Uncaught exception in Thread[elasticsearch[Black Widow][http_server_worker][T#12],5,main], java.lang.LinkageError: org/jboss/netty/util/internal/ByteBufferUtil
java.lang.AssertionError: Uncaught exception in Thread[elasticsearch[Black Widow][http_server_worker][T#12],5,main], java.lang.LinkageError: org/jboss/netty/util/internal/ByteBufferUtil
	at com.liferay.portal.test.rule.LogAssertionUncaughtExceptionHandler.uncaughtException(LogAssertionUncaughtExceptionHandler.java:49)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.lang.Thread.dispatchUncaughtException(Thread.java:1952)
Caused by: java.lang.LinkageError: org/jboss/netty/util/internal/ByteBufferUtil
	at org.jboss.netty.channel.socket.nio.SocketSendBufferPool.releaseExternalResources(SocketSendBufferPool.java:380)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
I'm going to close this pull. Please reopen if you think this is a fluke and CI will retest it.

**Comment by jpince** [comment]
ci:close

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by jpince** [comment]
@shuyangzhou @mtambara inconsistent failure for PACLAggregateTest.testPACLTests

**Comment by brianchandotcom** [comment]
@adolfopa rebase error, please resend. Thx.

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/43889

**Pull request closed without merging**
