### PR TITLE
LPS-122448 - Add delegate util

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Sent at https://github.com/brianchandotcom/liferay-portal/pull/95426 but had wrong format for commits.

Tested and forward from 
https://github.com/liferay-frontend/liferay-portal/pull/439

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9f6e7d76f5...129e70af39

**Comment by brianchandotcom** [comment]
@bryceosterhaus master only.

**Comment by brianchandotcom** [comment]
@bryceosterhaus please send me backports if relevant

**Pull request closed without merging**
