### PR TITLE
LRQA-31089

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-31089

### CODE REVIEW

**Comment by kenjiheigel** [comment]
@brianchandotcom, there are multiple pulls across branches to keep this consistent. Please note that for master and 7.0.x, only one commit is necessary. For the older branches I had to update build-common.xml to use an attribute we already have in master and 7.0. Let me know if you have any questions. Thanks! 

7.0.x: https://github.com/brianchandotcom/liferay-portal/pull/47494
ee-6.2.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/16250
ee-6.2.10: https://github.com/brianchandotcom/liferay-portal-ee/pull/16251
ee-6.1.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/16246
ee-6.1.30: https://github.com/brianchandotcom/liferay-portal-ee/pull/16247

**Comment by kenjiheigel** [comment]
@brianchandotcom, not sure why this failed.. but something went wrong in the top level, and it aborted the other jobs. We'll keep an eye out for failures like this.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
