### PR TITLE
LPS-126667 Update Translations

### PR DESCRIPTION
**Pull request by BryanEngler**
needed asap for CCR releases, sending directly because ci:forward failed with flaky tests, only changes are translations
ci:test:sf passes here https://github.com/BryanEngler/liferay-portal/pull/556#issuecomment-767794533

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:reopen

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:reopen

**Comment by timpak** [comment]
Backport PRs:
7.3.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/33114
7.2.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/33115
7.1.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/33116

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1d2925d463...862747f452

**Pull request closed without merging**
