### PR TITLE
LPS-106152 Baseline

### PR DESCRIPTION
**Pull request by inacionery**
/cc @rafaprax

### CODE REVIEW

**Comment by barrosdennys** [comment]
The unique flaky poshi failure is not related to this PR.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e43628fdd8...5293673f68

**Comment by brianchandotcom** [comment]
@inacionery But please send a follow up pull and utilize portal-kernel/src/com/liferay/portal/kernel/version/Version.java. It can hide this complexity:

```
	public int compare(
		WorkflowMetricsSLADefinitionVersion
			workflowMetricsSLADefinitionVersion1,
		WorkflowMetricsSLADefinitionVersion
			workflowMetricsSLADefinitionVersion2) {

		int value = 0;

		String version1 = workflowMetricsSLADefinitionVersion1.getVersion();
		String version2 = workflowMetricsSLADefinitionVersion2.getVersion();

		int[] versionParts1 = StringUtil.split(version1, StringPool.PERIOD, 0);
		int[] versionParts2 = StringUtil.split(version2, StringPool.PERIOD, 0);

		if ((versionParts1.length != 2) && (versionParts2.length != 2)) {
			value = 0;
		}
		else if (versionParts1.length != 2) {
			value = -1;
		}
		else if (versionParts2.length != 2) {
			value = 1;
		}
		else if (versionParts1[0] > versionParts2[0]) {
			value = 1;
		}
		else if (versionParts1[0] < versionParts2[0]) {
			value = -1;
		}
		else if (versionParts1[1] > versionParts2[1]) {
			value = 1;
		}
		else if (versionParts1[1] < versionParts2[1]) {
			value = -1;
		}

		if (_ascending) {
			return value;
		}

		return -value;
	}
```

**Comment by inacionery** [comment]
Follows https://github.com/brianchandotcom/liferay-portal/pull/83456

**Pull request closed without merging**
