### PR TITLE
LPS-103362 Update product-navigation:personal-menu tag to use React

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @jbalsas @drewbrokke @alee8888

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f00dfe17d7...ca8e8165a2

**Comment by brianchandotcom** [comment]
@pei-jung see 359749f8988af67546de7cea120f8027d07bc5b2 11cffcc12027c89e9269aaeb4d2b9b879af14ee8 and ca8e8165a236d4ca91f6f030d5232274b75fb8cf

@jbalsas fyi

**Comment by brianchandotcom** [comment]
@pei-jung @jbalsas had to revert because of upgrade failures - origin wasn't syncing with upstream.

**Comment by jbalsas** [comment]
Hey @john-co, can you take a look at this? It's probably just test updates that are needed... @pei-jung, @drewbrokke, do you have a QA that can help @john-co figure this out?

**Comment by drewbrokke** [comment]
@jbalsas we can ask @patriciajeanperez to talk with @john-co about this.

**Comment by john-co** [comment]
ci:test:bundle

**Comment by patriciajeanperez** [comment]
ci:close

**Pull request closed without merging**
