### PR TITLE
LPS-61733 Bookmarks Lexicon

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey Brian,

This pull contains different LPS but they are all related to Bookmarks lexicon and they modify the same jsps, that's why they are in the same pull.

Thanks!

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @sharonchoi @austinchiang @jbalsas @juliocamarero

**Comment by brianchandotcom** [comment]
@sergiogonzalez no need to resend. I'll merge this in.

**Comment by sergiogonzalez** [comment]
thx @brianchandotcom

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6b0c65e120...b8440afd7a

**Pull request closed without merging**
