### PR TITLE
LPS-106145 Remove VerifyGroupedModel and VerifiableGroupedModel

### PR DESCRIPTION
**Pull request by achaparro**
cc/@samziemer

### CODE REVIEW

**Comment by achaparro** [comment]
ci:close

**Comment by achaparro** [comment]
@samziemer, tomorrow we can talk about the progress of these tasks but can you check the verify test error? It seems caused by us.

Thanks!

**Comment by SamZiemer** [comment]
Hi @achaparro,

It looks like I forgot to remove https://github.com/achaparro/liferay-portal/blob/453842cdabdede2bfcdd92b67789978430e26153/modules/apps/message-boards/message-boards-test/src/testIntegration/java/com/liferay/message/boards/verify/test/MessageBoardsServiceVerifyProcessTest.java which is leading to the NPE thrown by the test.

**Comment by achaparro** [comment]
Hey @SamZiemer,

Can you remove it and send it to Brian?

Thanks

**Comment by SamZiemer** [comment]
Hi @achaparro, yes I have resent it here: https://github.com/brianchandotcom/liferay-portal/pull/82832

**Pull request closed without merging**
