### PR TITLE
LPS-90872 portal-search-admin-web: New dependency due to 54350c4e86cbf3c88136578627d06d75c758d51c.

### PR DESCRIPTION
**Pull request by brandizzi**
<h3>:x: ci:test:search - 13 out of 17 jobs passed in 1 hour 25 minutes 16 seconds 410 ms</h3>

https://github.com/brandizzi/liferay-portal/pull/672#issuecomment-478782420

All failures are know according to https://docs.google.com/spreadsheets/d/1cDzu4itg1XPtK4EyuwWB3MBwK3m7MpT3LqLcXltx9QA/edit#gid=0 Also clearly unrelated: this PR just shows content, it does not change any behavior in Search beyond adding a new screen. The only suspicious failure was LocalFile.Search#ViewFacetPersistence , that is a known issue.

Authors: @foshiro
Reviewer: @brandizzi

[Story] As a Search Admin I want to view effective Field Mappings, as reported by the search engine, from within Portal UI
https://issues.liferay.com/browse/LPS-90872

### CODE REVIEW

**Comment by ccohick** [comment]
ci:test:bundle

**Comment by xbrianlee** [comment]
ci:test:bundle

**Comment by brianchandotcom** [comment]
@brandizzi please fix bad names:

```
IndicesAdminClient indices = getIndicesAdminClient();

		GetFieldMappingsRequest request = new GetFieldMappingsRequest();
```

**Comment by brandizzi** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
