### PR TITLE
LPS-66534 Image Editor Capability Process Testing

### PR DESCRIPTION
**Pull request by kenjiheigel**
@brianchandotcom, this is a resend of https://github.com/brianchandotcom/liferay-portal/pull/40699. @jbalsas has added frontend javascript tests that run via karma for Image Editor. I've added the infrastructure to run these tests and produce an output on the pull request tester. The Frontend Infrastructure team wants these tests to be an example for how other teams can add frontend tests to their components. Let us know if you have any questions. Thanks! Additionally, this pull also includes a resend of https://github.com/brianchandotcom/liferay-portal/pull/43449, which is required for our CI infrastructure to work with the frontend tests. 

cc-ing @brunobasto, @jonmak08, @ithildir, @jpince, @brianchiu, @pyoo47, @michaelhashimoto

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@kenjiheigel can you resend as a new pull? I just want to be super safe that this is clean before merging. Thx.

**Comment by kenjiheigel** [comment]
Resent: 
https://github.com/brianchandotcom/liferay-portal/pull/43522

**Pull request closed without merging**
