### PR TITLE
Lps 61952 sb

### PR DESCRIPTION
**Pull request by shuyangzhou**
@brianchandotcom this is the ServiceBuilder support for split package fix. In this pull we only include the SB changes, without an actual usage. We did this to keep the pull small. The 1st sample usage will be on Announcements, which will come later, but if you prefer to see the usage together with the SB changes, I can resend to include it.

### CODE REVIEW

**Comment by willnewbury** [comment]
@brianchandotcom As Shuyang is out today (1/25) I am going to be in charge of pushing this out piece by piece. If there's any questions/changes/problems with the pull let me know

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1cbe75806e...5bc77520cf

**Comment by brianchandotcom** [comment]
@willnewbury sorry it took so long. Just pushed it up. I got confused because of Shuyang's other 2 changes to replace '.' with  "."

I just kept them all as strings for now and I didn't merge in Shuyang's other 2 commits.

**Comment by willnewbury** [comment]
@brianchandotcom It looks like something went wrong with the publishing of the new version of service builder - if you ant all on latest master, api-package-path doesn't seem to be in

**Comment by willnewbury** [comment]
never mind, false alarm

**Pull request closed without merging**
