### PR TITLE
LPS-76324 Increase test coverage for areas that break under Elasticsearch 6

### PR DESCRIPTION
**Pull request by arboliveira**
Authors: @BryanEngler @wcao20170619 @arboliveira
Reviewer: @arboliveira

https://issues.liferay.com/browse/LPS-76324

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:test

**Comment by arboliveira** [comment]
ci:test <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/924fbc4e63...db3521740e

**Comment by jpince** [comment]
@BryanEngler this pull caused a SF error, can you please resolve? I think SF wants this part: `	@Rule
	public TestName testName = new TestName();` to be above `	protected void assertAnalyzer(String field, String analyzer)`
```
     [java] Exception in thread "main" com.liferay.source.formatter.SourceMismatchException: ./modules/apps/foundation/portal-search/portal-search-elasticsearch/src/test/java/com/liferay/portal/search/elasticsearch/internal/index/LiferayTypeMappingsPortugueseTest.java expected:<..."portuguese");
     [java] 	}
     [java] 
     [java] 	[@Rule
     [java] 	public TestName testName = new TestName();
     [java] 
     [java] 	protected void assertAnalyzer(String field, String analyzer)
     [java] 		throws Exception {
     [java] 
     [java] 		_liferayIndexFixture.assertAnalyzer(field, analyzer);
     [java] 	}]
     [java] 
     [java] 	private LiferayIn...> but was:<..."portuguese");
     [java] 	}
     [java] 
     [java] 	[protected void assertAnalyzer(String field, String analyzer)
     [java] 		throws Exception {
     [java] 
     [java] 		_liferayIndexFixture.assertAnalyzer(field, analyzer);
     [java] 	}
     [java] 
     [java] 	@Rule
     [java] 	public TestName testName = new TestName();]
     [java] 
     [java] 	private LiferayIn...>
```

**Comment by jpince** [comment]
here's the console log: https://test-1-12.liferay.com/job/test-portal-acceptance-upstream-batch(master)/AXIS_VARIABLE=0,label_exp=!master/10339/console

**Comment by arboliveira** [comment]
@BryanEngler @jpince I ran Source Formatter yesterday before submitting the pull, and again right now with current master, and both times it did _not_ catch this formatting problem. I'll reorder the `public` and `protected` declarations; let's hope nothing else is missed.

**Comment by jpince** [comment]
@arboliveira Peter already fixed it https://github.com/brianchandotcom/liferay-portal/pull/53545#issuecomment-350063227

**Comment by jpince** [comment]
@arboliveira have you built SF recently? you can ant all or gradlew deploy that module

**Comment by arboliveira** [comment]
I didn't realize I already had Peter's fix when I ran it this morning, so I'm assuming SF is okay and it was my mistake yesterday actually.

**Pull request closed without merging**
