### PR TITLE
LPS-105855 make changes needed to release Data Engine as part of core

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
cc @jeyvison @jpince @brunofarache @marcelabc

**Comment by jpince** [comment]
@leoadb semver failure unrelated (in upstream)

@vicnate5 can someone please validate the `lpkg-base` failure? `lpkg-controller` passed, but I want to make sure, since this PR moves a standalone app to be a core module. Thank you!
```
     [exec]     BUILD FAILED: Element is present at "//button[contains(.,'Sign In')] | //button[contains(.,'Acceder')] | //button[contains(.,'Anmelden')] | //button[contains(.,'????????????')] | //button[contains(.,'??????')]"
     [exec]     /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/macros/SignIn.macro[_signIn]:30
     [exec]     /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/macros/SignIn.macro[signIn]:55
     [exec]     /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/macros/SignIn.macro[signInTestSetup]:129
     [exec]     /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/portalsmoke/PortalSmoke.testcase[set-up]:13
```

**Comment by vicnate5** [comment]
Poshi log is missing but startup looks clean. Going to re-run while we check manually.

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@vicnate5 thanks!

**Comment by vicnate5** [comment]
Test passed on new run

**Comment by brianchandotcom** [comment]
@leoadb I thought we were going to do this afterward.. like in March. Why did we do this now?

I don't want to bring this in until after we have the testing framework in place. If you do really want this in now, just tell me why now.

Also, when you say, copy from 7.2.x, is that liferay-portal/7.2.x or liferay-portal-ee/7.2.x. (Ideally, you tell me the exact hash from 7.2.x that you got this from. I'm going to check that 7.2.x, and rsync it myself to make sure the copy was correct).

@jeyvison fyi.

Please resend.

**Pull request closed without merging**
