### PR TITLE
Lps 83801

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d00e49a2de...efa62c7d34

**Comment by brianchandotcom** [comment]
@topolik @csierra please see my changes in upstream. Thx.

**Comment by topolik** [comment]
Looks fine, thanks all for cooperation! @shuyangzhou @csierra @brianchandotcom

**Pull request closed without merging**
