### PR TITLE
Revert "LPS-75100 Create petra module group."

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pyoo47 can you ci:stop this? I can't f ind a way to do it on Jenkins

Trying to save on resources.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/44fb5958bd...228f130cc6

**Comment by pyoo47** [comment]
@brianchandotcom I've stopped it

**Pull request closed without merging**
