### PR TITLE
LPS-80193 Removing semicolon causes an error after recent changes processing SQL Table templates

### PR DESCRIPTION
**Pull request by achaparro**
cc/@ricardocousolr

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test

**Comment by achaparro** [comment]
ci:reopen

**Comment by achaparro** [comment]
errors are not related

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@ricardocousolr this doesn't make sense...

public static final String TABLE_SQL_DROP = "drop table BookmarksEntry";

doesn't have a semicolon. So why would some TABLE_SQL_* have it and some not. We need to fix the other part to add the ; when it's called. Not change how these static classes are made.

Please resend. @achaparro

**Comment by ricardocousolr** [comment]
Thanks for you comment @brianchandotcom. 

I'll send a new pr to @achaparro improving the method `runSQLTemplateString` to ensure that the sql's have the appropriate semicolon.

**Pull request closed without merging**
