### PR TITLE
master-lps-59067

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LPS-59067

@brianchandotcom 
This ticket caused a build failure in Jenkins, (see [LPS-59233](https://issues.liferay.com/browse/LPS-59233)) so I want to temporarily revert this until Michael Bradford sends the fix so that we can have test results. I've already talked with Michael Bradford and he said this was ok, and he can recommit LPS-59067 when he sends the fix.

There was also something regarding our jenkins configuration, which is why this passed in the pull request tester but failed in test-2-1. I don't know the full details for that, but Kenji and Kiyoshi should know.

CC @mjbradford89 @jhendley @kenjiheigel @kiyoshilee @vicnate5 @Ithildir

### CODE REVIEW

**Comment by mjbradford89** [comment]
Hey @brianchiu,

If we can get this into master: https://github.com/natecavanaugh/liferay-portal/pull/3537,  The ruby sass compilation failure should be resolved.  These changes create a small other issue with DDM UI, but I figured for now it's important we get the tests working again.  I will create another ticket for the small UI issue that gets created.

**Comment by brianchandotcom** [comment]
See https://github.com/natecavanaugh/liferay-portal/pull/3537

**Comment by brianchandotcom** [comment]
@brianchiu can we get this into the smoke test, or at least get more UI tests as part of PR? Then stuff like this won't happen.

**Comment by jhendley** [comment]
@brianchandotcom this failure happened because of a difference between the two environments - the PR environment was using the native sass compiler during the build, but on test-2, it’s using the ruby sass compiler. No amount of UI tests would have caught this. We are working to make sure the environments are aligned.

**Comment by jhendley** [comment]
It's compile time. I will work with the team on seeing what we can do to
test both, but I think our functional test compile should be the same as
the PR test compile. Thanks!

On Tuesday, October 6, 2015, Liferay Continuous Integration <
notifications@github.com> wrote:

> Is this runtime or compile time native vs ruby?
>
> Since it's an change end users can set, we ought to test both.
>
> Thx
>
> > On Oct 6, 2015, at 6:24 PM, Joel Hendley <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > @brianchandotcom this failure happened because of a difference between
> the two environments - the PR environment was using the native sass
> compiler during the build, but on test-2, it’s using the ruby sass
> compiler. No amount of UI tests would have caught this. We are working to
> make sure the environments are aligned.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/30815#issuecomment-146054923>
> .
>


-- 
Joel Hendley
Director of QA
@jhendley <https://twitter.com/jhendley>

<http://liferay.com/>
Enterprise. Open Source. For Life
Web <http://www.liferay.com/> | Facebook <http://facebook.com/liferay> |
Twitter <http://twitter.com/liferay>

**Comment by brianchiu** [comment]
@brianchandotcom 
Got it. Yeah, we wouldn't have caught it if we had added more tests.

Thanks for merging https://github.com/natecavanaugh/liferay-portal/pull/3537

**Comment by kenjiheigel** [comment]
I sent a pull to @michaelhashimoto that can be used to test the building of CSS using the ruby sass compiler: 
https://github.com/michaelhashimoto/liferay-portal/pull/852

**Pull request closed without merging**
