### PR TITLE
LPS-169954 buildLang

### PR DESCRIPTION
**Pull request by naraandrade**

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:reopen

**Comment by naraandrade** [comment]
Hi @brianchandotcom, I'm sending this directly to you because the failures [here](https://github.com/liferay-objects/liferay-portal/pull/1446) are not related.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/275ed32e82...e1683d62a6

**Comment by brianchandotcom** [comment]
@naraandrade see e1683d62

**Pull request closed without merging**
