### PR TITLE
LRCI-891 Remove unneeded logic for Gradle 4.10.2

### PR DESCRIPTION
**Pull request by petershin**
@yichenroy

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:bundle

**Comment by brianchandotcom** [comment]
Woo hoo @petershin !

**Comment by brianchandotcom** [comment]
@petershin not sure if I should merge this..

**Comment by petershin** [comment]
@brianchandotcom - Ok, we can wait until the CDN is up again to check the test results

**Comment by petershin** [comment]
ci:reopen

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
ci:test:relevant

@petershin is this safe?

**Comment by brianchandotcom** [comment]
All tests passed.. so safe to merge.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b2a0fde77d...356d50ee17

**Pull request closed without merging**
