### PR TITLE
LPS-73414 Pass the arguments and ensure that they are not translated

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @mmariuzzo

**Comment by brianchandotcom** [comment]
@hhuijser @petershin more random SF issues.

**Comment by brianchandotcom** [comment]
@mmariuzzo @sergiogonzalez you misunderstood what I mean

1.) get-url=Get <a class="{0}" href="{1}">URL</a>.

should be

get-url=Get {0}URL{1}.

2.) get-url-or-webdav-url=Get <a class="{0}" href="{1}">URL</a> or <a class="{2}" href="{3}">WebDAV URL</a>.

should be

get-url-or-webdav-url=Get {0}URL{1} or {2}WebDAV URL{3}.

Please resend. Thx.

**Comment by sergiogonzalez** [comment]
Hey Brian,

There are several places that they all have the same structure I applied in my commits. Please see the following as examples:

https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/content/Language.properties#L1115
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/content/Language.properties#L1168
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/content/Language.properties#L4787
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/content/Language.properties#L5026
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/content/Language.properties#L5064
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/content/Language.properties#L5532
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/content/Language.properties#L5655
https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/server/server-admin-web/src/main/resources/content/Language.properties#L66
https://github.com/liferay/liferay-portal/blob/master/modules/apps/web-experience/site/site-admin-web/src/main/resources/content/Language.properties#L3

**Comment by brianchandotcom** [comment]
@sergiogonzalez yeah, it's an old style I"m trying to get rid of since it caused a lot of problems. So for now, whenever I see a modified or new key, I push it to follow the new pattern.

@hhuijser can you add an SF to enforce it in the future (not for now since we haven't migrated all the keys yet) to avoid HTML markup in Language keys since we have to test every language translation.

Thx.

**Pull request closed without merging**
