### PR TITLE
LPS-55497 Not needed

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@marcellustavares I merged this in, but I need you to make the following changes.

1.) In modules/app/***.java search for

javax.portlet.name=" + PortletK

You will notice in only exists in the modules you moved out.

If a portlet key is part of that existing module, it ought to use the local constant *PortletKeys. See AssetTagsNavigationPortletKeys. It doesn't extend PortletKeys.

If a portlet key is reused by another module, have that other module depend on this module and export the package.

If it's used in core, or in the old plugins, then leave it in the core PortletKeys.

2.) Should we rename PORTLET_DISPLAY_TEMPLATES should it a new var? Should it be plural? Or can it just be DYNAMIC_DATA_MAPPING (to match the new portlet java name)

3.) In the future, make the pulls by smaller by sending just the migration to MVCPortlet first (without extracting) the portlet. Then when that's in, then send me other pulls. It makes it easier for me. Otherwise, these pulls are so big.

Thx @marcellustavares

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/401a02d8e1...0cd8dcb5fb

**Comment by marcellustavares** [comment]
Thanks @brianchandotcom, I'll make these changes and send you smaller pulls for the next ones.

**Comment by marcellustavares** [comment]
Hi @brianchandotcom,

- I've just double checked and all our references to PortletKeys are because the key is still being used in core. Probably some of them will be removed as other parts of core get extracted out.
- I've sent you a pull key names in the singular, https://github.com/brianchandotcom/liferay-portal/pull/26729 and https://github.com/brianchandotcom/liferay-portal/pull/26730

ADT is in DDM for now but it's temporary. @epgarcia has plans to update the portlet views and once that happens the PortletDisplayTemplatePortlet will be moved out dynamic-data-mapping-web to portlet-display-template-web.

Thanks Brian.

**Pull request closed without merging**
