### PR TITLE
Data Partitioning: new files hierarchy

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by migue** [comment]
everything was ok on my pull request tester ... ci:retest

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
Is there anything we can do for this pull? We'd like to add the support for EE db's and for that reason we'd need this pull for that.

Thanks!

**Comment by brianchandotcom** [comment]
@mdelapenya I talked to @migue and pushed up my changes to upstream in c702cb56d6d58bc50496f0c8e66010dc8fcdda9f

Sorry it took so long! I was concentrating on the release.

fyi @jorgeferrer

**Comment by brianchandotcom** [comment]
@mdelapenya for now, just follow the example in modules/util/saas-compiler-*

I'll move it to its own repo later.

**Comment by JorgeFerrer** [comment]
Thanks Brian!

**Pull request closed without merging**
