### PR TITLE
LPS-189564

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:reopen

**Comment by tinatian** [comment]
FYI @gabrielwas

**Comment by brianchandotcom** [comment]
@JanisZhang EDIT_PORTLET_DISPLAY_CONTEXT should not be in WebKeys. We don't use that pattern in other places (we usually leave it in the module since it's only used inside the module)

**Comment by brianchandotcom** [comment]
@tinatian see my comment above.

**Pull request closed without merging**
