### PR TITLE
CLDSVCS-2922 petra-json-web-service-client baseline

### PR DESCRIPTION
**Pull request by ivicac**
Hi Brian,
can you please publish a new version?

Best Regards

@mladencikara @igorbeslic

### CODE REVIEW

**Comment by ivicac** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
@ivicac I'll publish a new version later today.. merging in for now.

**Pull request closed without merging**
