### PR TITLE
LPS-63640 use ServletContext classloader when available

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
That was strange.. we haven't had a pull time out in quite a while @pyoo47 fyi

ci:retest

**Comment by pyoo47** [comment]
Looks like a bunch of PACL tests ran very slowly and the job aborted itself after two hours. The logs look like it was still working when it timed out.
```
     [junit] [PACLTestSuite]journal.transformer.regex.replacement.0=production.sample.com[PACLTestSuite]
    [junit] [PACLTestSuite]junit.delay.factor=1[PACLTestSuite]
    [junit] [PACLTestSuite]portal.url=http://localhost:8080[PACLTestSuite]
    [junit] [PACLTestSuite]user.password=test[PACLTestSuite]
    [junit] [PACLTestSuite]
    [junit] 18:54:20,901 ERROR [com.liferay.portal.kernel.process.local.LocalProcessExecutor-1][LocalProcessExecutor:399] Abort subprocess piping
    [junit] java.lang.ClassCastException: cannot assign instance of com.liferay.portal.security.pacl.PACLAggregateTest$ProcessBridgeRunListener$1 to field com.liferay.portal.security.pacl.PACLAggregateTest$ProcessBridgeRunListener$1.val$methodName of type java.lang.String in instance of com.liferay.portal.security.pacl.PACLAggregateTest$ProcessBridgeRunListener$1
    [junit] 	at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2083)
    [junit] 	at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1261)
    [junit] 	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1996)
    [junit] 	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
    [junit] 	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
    [junit] 	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
    [junit] 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
    [junit] 	at com.liferay.portal.kernel.process.local.LocalProcessExecutor$SubprocessReactor.call(LocalProcessExecutor.java:329)
    [junit] 	at com.liferay.portal.kernel.process.local.LocalProcessExecutor$SubprocessReactor.call(LocalProcessExecutor.java:262)
    [junit] 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    [junit] 	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask._runTask(ThreadPoolExecutor.java:756)
    [junit] 	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask.run(ThreadPoolExecutor.java:667)
    [junit] 	at java.lang.Thread.run(Thread.java:745)
    [junit] Abort subprocess piping
Build timed out (after 120 minutes). Marking the build as aborted.
```

**Comment by brianchandotcom** [comment]
@rotty3000 This is slowing down the pull to 2 hours+ vs finishing in 45 minutes... can you fix and resend? thx.

**Comment by rotty3000** [comment]
yup

**Pull request closed without merging**
