### PR TITLE
LPS-59787 Make denied events strikethrough and fainter.

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brandizzi** [comment]
Hey @brianchandotcom! I did not see these fixes in master? Are they going to be merged into liferay-portal master later?

Thank you!

**Comment by brandizzi** [comment]
ci:reopen

Hey Brian! Sorry for bothering you a bit more but this fixed seems to not be in master.

Thank you for your time!

**Comment by brianchandotcom** [comment]
Hmm... merging again. My bad.

**Pull request closed without merging**
