### PR TITLE
LPS-65647 Unable to publish and save web content draft after upgrading from 6.x

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by sharonchoi** [comment]
investigating poshi error

**Comment by sharonchoi** [comment]
ci:retest

**Comment by vicnate5** [comment]
@brianchandotcom This fixes a high priority Upgrade bug with Web Content. QA already pulled this code and tested it manually.

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/40116

**Pull request closed without merging**
