### PR TITLE
LPS-72685 Sync

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @ealonso

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4fab9a35ec...b31fabd96d

**Comment by brianchandotcom** [comment]
@ealonso please backport this as well.

I'm going to try to merge in https://github.com/brianchandotcom/liferay-portal-ee/pull/17334 as well today if it passes.

**Comment by ealonso** [comment]
Thanks @brianchandotcom, I've send a new pull request with more test see: https://github.com/brianchandotcom/liferay-portal-ee/pull/17391

**Pull request closed without merging**
