### PR TITLE
LPS-101565 SF

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
@Preston-Crary, @adolfopa

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b57f56bd2c...8663e74053

**Comment by brianchandotcom** [comment]
@4lejandrito I deleted your IMPORTANT.txt file in b404ef553db78679e55f70c3e028422125dd3df3

Why? As the code evolves, there's nothing that tells a future developer they have to modify that file. Therefore, over time, that text file will become wrong/irrelevant.

Find the piece in the code that would most tell 'future self' that something is important, and just add

// LPS-xxxx

So when we look at that code, we'll go 'hmm.... I wonder why this is here', and then we'll click on the LPS, and then read that big important message you have.

Better yet, also, when you add the comment // LPS-xxxx, in the commit message, add a long message about why this is important.

Please send me a follow up pull. Thx.

**Comment by 4lejandrito** [comment]
Hi @brianchandotcom,

That file wasn't supposed to be committed. It was work in progress of a jira comment totally unrelated. My bad.

Thanks for getting rid of it, and sorry!

**Pull request closed without merging**
