### PR TITLE
LPS-78082 Deprecating the rest of social bookmarks properties

### PR DESCRIPTION
**Pull request by 4lejandrito**
Hi @brianchandotcom,

I am now using plurals in every possible place. 

If I am correct, the only remaining elements in singular are the `PropKeys` which are all deprecated except for `SOCIAL_BOOKMARK_DISPLAY_STYLES` which I will deprecate in the next story (ready to be sent to you as soon as this one is merged). 

[This](https://github.com/4lejandrito/liferay-portal/blob/a623ee85fc9afd7b7b89d689e18fc8a0f4d112f5/modules/apps/social-bookmarks/social-bookmarks-taglib/src/main/java/com/liferay/social/bookmarks/taglib/servlet/taglib/SocialBookmarksTag.java#L61) should be the only place in which singular and plural don't match. As I said it, this will be fixed in the next set of changes.

Thanks for your patience!

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test

**Comment by jpince** [comment]
@4lejandrito Looks like the failures are not caused by this pull. 👍

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e278aceb72...79065bdf9f

**Comment by brianchandotcom** [comment]
Thx @4lejandrito for making this happen. Just a few minor changes in upstream.

**Pull request closed without merging**
