### PR TITLE
LPS-70486

### PR DESCRIPTION
**Pull request by Ithildir**
Hi @brianchandotcom,

Can you please publish a new `gradle-plugins-workspace` if you haven't done it yet today? @david-truong needs the changes introduced by [LPS-70510](https://issues.liferay.com/browse/LPS-70510).

Thanks!

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/22e5d581aa...03c555cabd

**Comment by brianchandotcom** [comment]
@codyhoag changelogs. fyi.

**Comment by brianchandotcom** [comment]
@Ithildir @gamerson

published a new jar.

**Pull request closed without merging**
