### PR TITLE
LPS-91749

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by jpince** [comment]
@adolfopa @4lejandrito semver
```
     [exec] > Task :apps:document-library:document-library-api:baseline FAILED
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.document.library.util                  MINOR      1.0.1      1.0.1      1.1.0      VERSION INCREASE REQUIRED
     [exec] 	+   interface  com.liferay.document.library.util.DLAssetHelper
     [exec] 		+   access     abstract
     [exec] 		+   method     getAssetClassPK(com.liferay.portal.kernel.repository.model.FileEntry,com.liferay.portal.kernel.repository.model.FileVersion)
     [exec] 			+   access     abstract
     [exec] 			+   return     long
```
cc/ @austinchiang

**Comment by 4lejandrito** [comment]
Resending in a bit.

**Comment by 4lejandrito** [comment]
ci:close

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/74647.

**Comment by 4lejandrito** [comment]
Thanks @jpince!

**Pull request closed without merging**
