### PR TITLE
LPS-69013

### PR DESCRIPTION
**Pull request by Ithildir**
Hi,
Please let this pull finish. Then, if everything is okay, can you please publish the following modules?

- `jasper-jspc`
- `gradle-plugins`
- `gradle-plugins-defaults`

Thank you!

cc @shuyangzhou

cc @mladencikara: please try to run `compileJSP` after this pull gets merged, no changes in your module should be needed.

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
@pyoo47 wrong DB issue again.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@Ithildir can you fix upstream change logs? Didn't merge easily.

**Pull request closed without merging**
