### PR TITLE
LRQA-26584 Turn on Firefox 45 on master

### PR DESCRIPTION
**Pull request by kevin-yen**
https://issues.liferay.com/browse/LRQA-26584

### CODE REVIEW

**Comment by kevin-yen** [comment]
@brianchandotcom @pyoo47 we also need to back port this to 7.0.x

**Comment by vicnate5** [comment]
@kevin-yen Looks like the browser crashed on the `CPDynamicdatalists#EditListRecord` test?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5e279c8b96...09eab2a23f

**Comment by brianchandotcom** [comment]
@kevin-yen what about ee-6.2.x and ee-6.1.x? Can you send me pulls there? thx.

**Comment by kevin-yen** [comment]
@brianchandotcom we're working through an issue for one of the 6.2 fixpack jobs. We don't believe its due to Firefox 45 but I'm going to wait until we verify that. Sometime this week.

**Pull request closed without merging**
