### PR TITLE
LPS-95742 Update url to show a border to highlight the web content

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
@jbalsas Could you please take a look to 421425b?

**Comment by jbalsas** [comment]
LGTM, @ealonso! I don't think anyone will be using that module, but in case they do, maybe we'd need to think of a way to keep it around, or document that it's getting removed?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/056bda5d7d...4360877ea7

**Comment by brianchandotcom** [comment]
@ealonso can you sort this in DLFileEntryInfoDisplayContributorTest.java:

```
				Assert.assertEquals(
					DLFileEntryConstants.getClassName(),
					_infoDisplayContributor.getClassName());

				Assert.assertEquals(
					"/d/", _infoDisplayContributor.getInfoURLSeparator());

				Assert.assertEquals(
					"Document",
					_infoDisplayContributor.getLabel(LocaleUtil.getDefault()));

				Map<String, Object> infoDisplayFieldsValues =
					_infoDisplayContributor.getInfoDisplayFieldsValues(
						fileEntry, LocaleUtil.getDefault());

				Assert.assertEquals(
					StringPool.BLANK, infoDisplayFieldsValues.get("summary"));
				Assert.assertEquals(
					fileEntry.getFileName(),
					infoDisplayFieldsValues.get("fileName"));

				Format dateFormatDateTime =
					FastDateFormatFactoryUtil.getDateTime(
						LocaleUtil.getDefault());

				Assert.assertEquals(
					dateFormatDateTime.format(fileEntry.getModifiedDate()),
					infoDisplayFieldsValues.get("publishDate"));

				Assert.assertEquals(
					_dlurlHelper.getDownloadURL(
						fileEntry, fileEntry.getFileVersion(), null,
						StringPool.BLANK),
					infoDisplayFieldsValues.get("downloadURL"));
				Assert.assertEquals(
					fileEntry.getDescription(),
					infoDisplayFieldsValues.get("description"));
				Assert.assertEquals(
					fileEntry.getMimeType(),
					infoDisplayFieldsValues.get("mimeType"));
				Assert.assertEquals(
					fileEntry.getTitle(), infoDisplayFieldsValues.get("title"));
				Assert.assertEquals(
					fileEntry.getVersion(),
					infoDisplayFieldsValues.get("version"));
				Assert.assertEquals(
					StringPool.BLANK, infoDisplayFieldsValues.get("tagNames"));
				Assert.assertEquals(
					StringPool.BLANK,
					infoDisplayFieldsValues.get("authorProfileImage"));
				Assert.assertEquals(
					TextFormatter.formatStorageSize(
						fileEntry.getSize(), LocaleUtil.getDefault()),
					infoDisplayFieldsValues.get("size"));
				Assert.assertEquals(
					fileEntry.getUserName(),
					infoDisplayFieldsValues.get("authorName"));
				Assert.assertEquals(
					StringPool.BLANK,
					infoDisplayFieldsValues.get("categories"));
```

**Pull request closed without merging**
