### PR TITLE
LPS-86134

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@nikki-pru @patriciajeanperez please look into POSHI test failures, potentially caused by this pull?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7aff0fd6ab...c390600f26

**Comment by brianchandotcom** [comment]
@bryceosterhaus @jbalsas see my changes in upstream. Thx.

**Comment by jbalsas** [comment]
Got it @brianchandotcom!

/cc @diegonvs, see https://github.com/brianchandotcom/liferay-portal/commit/bdba3a1f8a8b2608904146c486c666d7e30f16c2

**Pull request closed without merging**
