### PR TITLE
LPS-56778 Move sections from site settings to layouts

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/572d868cd0...165e551feb

**Comment by brianchandotcom** [comment]
@ealonso we a lost a lot of translations in this pull. I fixed it in 165e551febb214fdb73a6edec1ff79dac9d30d1e

I made a quick bash script (I called it merge_language_properties.sh)

```
#!/bin/sh

DESTINATION_DIR=~/dev/projects/github/liferay-portal/modules/apps/layout/layout-admin-web/src/content
SOURCE_DIR=~/dev/projects/github/liferay-portal/modules/apps/site/site-admin-web/src/content

for file in ${SOURCE_DIR}/Language_*.properties
do
	fileName="${file##*/}"

	echo "" >> ${DESTINATION_DIR}/${fileName}

	cat ${DESTINATION_DIR}/${fileName} ${SOURCE_DIR}/${fileName} > ${DESTINATION_DIR}/${fileName}.new

	mv ${DESTINATION_DIR}/${fileName}.new ${DESTINATION_DIR}/${fileName}
done
```

Then I ran "ant build-lang" in both modules. Now no translations are lost.

**Comment by brianchandotcom** [comment]
@juliocamarero see my previous comment about not losing translations. Thx.

**Comment by juliocamarero** [comment]
Awesome @brianchandotcom! Thanks a lot! :+1:

**Pull request closed without merging**
