### PR TITLE
LPS-137077 Add label field to ObjectDefinition and ObjectField in REST layer

### PR DESCRIPTION
**Pull request by guilhermedcamacho**
Related ticket: https://issues.liferay.com/browse/LPS-137077

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:reopen

**Comment by guilhermedcamacho** [comment]
Hey @brianchandotcom , I'm sending this directly to you because de CI keeps showing errors not related. I tried twice yesterday in these PRs [26](https://github.com/liferay-objects/liferay-portal/pull/26) and [29](https://github.com/liferay-objects/liferay-portal/pull/29)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b7b941dc07...e4e81566e9

**Comment by brianchandotcom** [comment]
@guilhermedcamacho I merged this, but I think your solution is not right

git grep i18n **yaml

```
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                title_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                contentFieldValue_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                label_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                title_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                description_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                name_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                label_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                            label_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                predefinedValue_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                description_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                name_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                value_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                data_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                        description_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                        name_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                name_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                value_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                value_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                        value_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                countryName_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                name_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                link_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                name_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                description_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                title_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                contentTemplateName_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                customCanonicalURL_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                description_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                htmlTitle_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                robots_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                seoKeywords_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                friendlyUrlPath_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                title_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                description_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                friendlyUrlPath_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                title_i18n:
modules/apps/headless/headless-delivery/headless-delivery-impl/rest-openapi.yaml:                taxonomyCategoryName_i18n
```

See the label one?

I thought the pattern was i18n?

**Pull request closed without merging**
