### PR TITLE
LPS-64098 update ant-bnd dependency

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@rotty3000 see c453f750e7c056d0b8571d5172339b702f2e3f19 and 67bfd67e54843ba9981065dfd283e8170d51da17 and 568d4d9c1e8f7feb46d51895e5eca9ad62f48294

Thx.

**Pull request closed without merging**
