### PR TITLE
LPS-87824

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
ci:test:sf

**Comment by mhan810** [comment]
ci:test:relevant

**Comment by mhan810** [comment]
@brianchandotcom ci:test:search is green according to: https://github.com/mhan810/liferay-portal/pull/1469

**Comment by xbrianlee** [comment]
Failure above is intermittent and caused by https://issues.liferay.com/browse/LPS-87886. TS is developing a fix.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7123da78f5...af64283b14

**Pull request closed without merging**
