### PR TITLE
LPS-75677 - Test class adjustments

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:reopen

**Comment by rafaprax** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2e13a4d36d...1c64ac834f

**Pull request closed without merging**
