### PR TITLE
LPS-58597 As a developer I want to mark my portlet as a full page application app

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
CC:/ @epgarcia, @Ithildir

**Comment by jkappler** [comment]
Not getting any source formatting errors on my local, even after updating to latest head

**Comment by brianchandotcom** [comment]
@jkappler I like where this is going, but I'm a bit confused now.

In the backend, we have "portlets". In the frontend, we call that an "application".

But now in the backend, we will also have an "application", what will that be called in the frontend? Please resend with a new name that won't cause confusion.

Thx.

**Comment by JorgeFerrer** [comment]
Hey @brianchandotcom,

This usage of the word "application" is independent of any terminology in the UI. The reason why we use this word instead of portlet is because we want to allow development of applications for Liferay that are not portlets. In fact, the next pull after this one will include a property to allow applications to provide a custom LayoutTypeController to make this very flexible.

Makes sense?

**Comment by brianchandotcom** [comment]
@jkappler can you resend and change com.liferay.portal.application.type to com.liferay.portal.kernel.application.type

I want to know immediately from the package that it's not one of the newere "com.liferay.application.list" etc.

Eventually, when we move com.liferay.portal.kernel.application.type out of portal-service, then it can have the shorter com.liferay.portal.application.type

I assume that "application.type" is like "application.list" at least. If it's 2 separate ideas, please don't use the same word "application". But if it does make sense and they are of the same thing, then we're good.

Thx

cc @JorgeFerrer

**Comment by JorgeFerrer** [comment]
Yes, it's the same meaning as in com.liferay.application.list so let's go with your proposal.

**Pull request closed without merging**
