### PR TITLE
LPS-142557 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-142557

This is only for master.

@ruben-pulido
@p2kmgcl

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure task is unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/6738
✔️ ci:test:stable - 11 out of 11 jobs passed
❌ ci:test:relevant - 23 out of 29 jobs passed in 1 hour 35 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/454ce5d9e3...b01d2fa99f

**Comment by brianchandotcom** [comment]
@ruben-pulido see b01d2fa99f1df9b6e83e28de938557d15c859061

**Pull request closed without merging**
