### PR TITLE
LPS-142224: Export for SXPElement and SXPBlueprint

### PR DESCRIPTION
**Pull request by peerkar**
3 first commits are there for history only as I assigned this to myself from Bryan.
/cc and thanks @BryanEngler

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/de1eff9f72...89f123c54f

**Comment by brianchandotcom** [comment]
@BryanEngler see changes by @peerkar 

@peerkar thansk for getting rid of the optionals. We've Vulcan mind melded.

**Comment by peerkar** [comment]
@brianchandotcom to be fair with @BryanEngler, I've a small hunch those optionals and the initial code in this PR was taken from the original code by me... I in turn adapted the practise because of its usage in some places of Liferay code. But after taking a long learning journey and encountering ~~at project~~ on planet Vulcan, good things happen :)

**Comment by brianchandotcom** [comment]
Nice @peerkar ! :) made me laugh

**Pull request closed without merging**
