### PR TITLE
LPS-171084 The same Utility Page cannot be copied more than once if it has a thumbnail

### PR DESCRIPTION
**Pull request by liulukiwi**
This is only for master.

https://issues.liferay.com/browse/LPS-171084

@lfbesada

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:reopen

**Comment by liulukiwi** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/10670

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7636a976e3...27d8727041

**Comment by brianchandotcom** [comment]
@lfbesada see 27d8727041b628ae9fc284d17c270f321cc8cc61

**Pull request closed without merging**
