### PR TITLE
LPS-191031: Create new validations for APIProperty and APISchema 

### PR DESCRIPTION
**Pull request by LuismiBarcos**
Sent from https://github.com/liferay-headless/liferay-portal/pull/1414

Original description:
Rebased PR from https://github.com/liferay-headless/liferay-portal/pull/1395

Original description:
**What is new?**
- Create new `APIPropertyRelevantModelListener` to add some validations about related `APISchema` and `ObjectFieldERC` property must belong to its `schemaId`.
- Add new validation in `APISchema` where an `Object Definition ERC` must belong to a valid Object Definition.
- Add ObjectDefintionTestUtil for further use in API Builder tests
- Add some test cases to cover this new validations

**NOTE** I think that this PR is not going to pass SF due to there are some changes in the SF rules

**How to deploy it?**
- Deploy `headless-builder-api`
- Deploy `headless-builder-impl`

**JIRA Related Tickets**
https://liferay.atlassian.net/browse/LPS-191031

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
ci:reopen

**Comment by LuismiBarcos** [comment]
Manually sent here https://github.com/brianchandotcom/liferay-portal/pull/138889

**Comment by LuismiBarcos** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@sergiojimcos see changes in my origin. Thx.

**Pull request closed without merging**
