### PR TITLE
 LRQA-47143 | master

### PR DESCRIPTION
**Pull request by liulukiwi**
https://issues.liferay.com/browse/LRQA-47143

cc @brianwulbern

7.2.x:https://github.com/brianchandotcom/liferay-portal-ee/pull/25475
7.1.x:https://github.com/brianchandotcom/liferay-portal-ee/pull/25474

### CODE REVIEW

**Comment by brianwulbern** [comment]
@hhuijser @ling-alan-huang can we skip the SF check in `./portal-web/test/functional/com/liferay/portalweb/dependencies`?

**Comment by ling-alan-huang** [comment]
I will look at it if I finished my task on hand.
Reported in https://issues.liferay.com/browse/LPS-98433.

**Comment by ling-alan-huang** [comment]
`class-site-template-7.2.lar` on this pull is a folder,
but `class-site-template-7.0.lar` is a file.

**Comment by brianwulbern** [comment]
Yeah, Brian requested that we explode the lar files as well:
https://github.com/brianchandotcom/com-liferay-poshi-runner/pull/231
https://issues.liferay.com/browse/LRCI-462

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
Thanks @brianwulbern,

That is the reason why SF is complaining.

For now， SF only skips files in `dependencies` directory, don't skip files in sub-directories.
So, do want SF also skip some sub-directories in `dependencies` directory?

If yes, can you give the pattern for the sub-directories?

**Comment by brianwulbern** [comment]
Hi @ling-alan-huang,

Can we skip every file and sub-directory within the `dependencies` folder - is it possible to tell SF essentially, "don't format in here"?

`dependencies/class-site-template-7.2.lar/` is the sub-dir we really want to ignore.  But as you can tell from [the commit](https://github.com/brianchandotcom/liferay-portal/pull/75865/commits/b61551ddb84ad125e9e942ad4895b2fa1e301d7d), there's a bunch of sub-dirs (this is why I want to skip files and folders within `dependencies`).

If we *must* specify each individual sub-dir, I can list them out.  But we should keep in mind that we'll need to add ignore patterns each time we want to add a new exploded `*.lar` or `*.zip` file.

**Comment by ling-alan-huang** [comment]
Thanks @brianwulbern,
I am going to change the SF rule to skip everything in `dependencies` folder.

**Comment by ling-alan-huang** [comment]
Sent to Hugo for review: https://github.com/hhuijser/liferay-portal/pull/3666

**Pull request closed without merging**
