### PR TITLE
LPS-58526

### PR DESCRIPTION
**Pull request by matethurzo**
Hey Brian,

This contains adding a new SMDH for the staged version of asset links. More code related to this coming up, and also test.

Thanks,

Máté

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9a18c5ce5c...ba479cd280

**Comment by brianchandotcom** [comment]
@matethurzo are you stil going to move *.lar.* in modules to *.exportimport.lar.*? I remember it was on your todo.

**Comment by matethurzo** [comment]
@brianchandotcom yes indeed I'm still about to do that

**Pull request closed without merging**
