### PR TITLE
LPD-25581 Avoid bloating search index document with empty values, the…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…y will be stripped away when building json string anyway, putting them into document will only generate garbage objects.

@tiantian @vicnate5 please backport for LXC, thanks!

@victorhcunha this change should reduce portal side GC activity a bit when testing under same amount load for test cases with heavy search indexing behavior. Since we use out of box settings now, even login an user will have to reindex the user for the last login date change. @slnn please pick another test case that does more indexing (adding new entries of data for sure will lead to indexing)

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7cbd6973ba...0617a8858a

**Comment by slnn** [comment]
Hi @shuyangzhou 

Do we have any requirements about JDK version and GC algorithm for this pull? 

Lily

**Comment by shuyangzhou** [comment]
no, just whatever is default in benchmark repo is fine.

**Comment by slnn** [comment]
Hi @victorhcunha

Please run a comparison for this pull on the test case Login and DocumentLibrary.

In order to keep same amount load, you can do like these:

Steps for Login:
1> Update the master branch of benchmark project and create a new branch to apply the change in this pull https://github.com/slnn/liferay-benchmark-ee/pull/276 then switch to the new branch;

 2> Get the count of successful tests for test step _Log in_ from the test results of daily monitor testing, you can find it in **_/grinder/logs/grinder.log_** , please pick the number in the last sample;
For example, here is the last sample of Login test case, then the count of successful tests for test step Log in is _**627396**_,
```
****************************
This is Sample :10
Fri May 10 15:01:54 UTC 2024
****************************

Type   	Allowed Session Count	Current Session Count	Session Polling Time	Session Waiting Time	
Instant	14134                	14124                	83                  	-3                  	
Average	14134                	14128                	83                  	2                   	

Description    	Successful Tests	Errors	Mean Time	Mean Time Standard Deviation	TPS 	Peak TPS	
Home Page      	627478          	0     	108      	47.9                        	396 	466     	
View Login Page	627427          	0     	154      	89.6                        	396 	472     	
Log in         	627396          	0     	247      	111                         	396 	462     	
Log out        	627167          	0     	60.0     	37.4                        	396 	450     	
Total          	2509468         	0     	142      	104                         	1580	1800 
```   
3>Apply Login's benchmark-ext.properties that you used to get the count of successful tests for test step Log in,  set the count to property `grinder.thread.run`s in benchmark-ext.properties to override the default value 0, For example, based on the number we got in step 2> set **grinder.thread.runs=620000** for test case Login;

4>After applying `grinder.thread.runs`, run a runtime performance test, you can get the elapsed time for each grinder worker process from grinder agent output files, then pick the biggest one. For example, if we use 2 agents,  5 processes per agent, then you can find totally 10  grinder agent output files for the 2 agents under these path **/grinder/logs/m3agent1 and /grinder/logs/m3agent2** , these output files should be named like these:
out_m3agent1-0.log, out_m3agent1-1.log, out_m3agent1-2.log, out_m3agent1-3.log, out_m3agent1-4.log, out_m3agent2-0.log, out_m3agent2-1.log, out_m3agent2-2.log, out_m3agent2-3.log,  out_m3agent2-4.log, you can find output like` elapsed time is XXX ms` in each file, then pick the biggest one for current test case; By the way, m3agent1 and m3agent2 is the host name of the agent machine, it depends on which env you are using.

5>Based on the benchmark-ext.properties in step 3>,  set the value you got in step 4> to property `sample.gc.log.initdelay` in benchmark-ext.properties to override the default value;

6>Run runtime performance test;

7>Upload test result zip you got in step 6>

Please repeat the steps to run runtime performance test for test case Documentlibrary, for the value  `grinder.thread.runs` you can also use the count of successful tests for test step _Log in_ in DocumentLibrary test, for example:  here is the last sample of DocumentLibrary test case, then the count of successful tests for test step Log in is **95903**, then you can set `grinder.thread.runs=95000` for test case DocumentLibrary

````
****************************
This is Sample :8
Fri May 10 15:49:09 UTC 2024
****************************

Type   	Allowed Session Count	Current Session Count	Session Polling Time	Session Waiting Time	
Instant	9916                 	9886                 	111                 	72                  	
Average	9923                 	9910                 	111                 	19                  	

Description            	Successful Tests	Errors	Mean Time	Mean Time Standard Deviation	TPS 	Peak TPS	
Home Page              	96080           	0     	85.7     	125                         	71.5	113     	
View Login Page        	96008           	0     	126      	226                         	71.4	129     	
Log in                 	95903           	0     	230      	342                         	71.4	160     	
View DL Page           	95687           	0     	167      	169                         	71.2	152     	
View DL Folder         	95047           	0     	195      	189                         	70.7	146     	
View DL File           	84826           	0     	169      	174                         	63.1	133     	
Read DL File           	84118           	0     	66.7     	116                         	62.6	137     	
View Add DL File Editor	9449            	0     	137      	157                         	7.03	21.0    	
Add DL File            	9247            	0     	425      	364                         	6.88	20.0    	
Log out                	93212           	0     	63.7     	118                         	69.4	149     	
Total                  	759577          	0     	142      	210                         	565 	805 
```

**Comment by slnn** [comment]
Hi @victorhcunha

If you do not `see elapsed time is XXX ms`  from the output log of grinder in test result zip, this is may be caused by our sample stop earlier than grinder finished the fixed count run,  you can try this: if the last sample is 10, the use the sample 9 to get the count of successful tests for test step Log in

I am running this for Login, when I finished it, please finish tests on DocumentLibrary.

Lily

**Comment by slnn** [comment]
Hi  @victorhcunha

I update the previous steps about calculating the value for **grinder.thread.runs**, the original way will make the test run a very long time then you can see` the elapsed time is XXX ms` from the output log of grinder in test result zip, please follow the new way.

Lily

**Comment by slnn** [comment]
Hi @shuyangzhou 

Here are test results for portal GC log on test case Login with same amount load:

Portal Version | Git Id | grinder.thread.runs | TotalAllocations (MB) | Average Allocation Rate (MB/S) | Total G1 Evacuation Pause Count | Total Concurrent GC count | Max Young GC Pause Time (ms)
-- | -- | -- | -- | -- | -- | -- | --
Baseline | 624ebc3 | 275 | 1033701 | 1166.097362 | 205 | 0 | 138.707
PR | - | 275 | 1033657 | 1128.821137 | 205 | 0 | 156.894


More details please see: https://docs.google.com/spreadsheets/d/1M6VK8GtY9kkv1EwhGW7vwrEENSzyT7zKz-wOh11ZHBo/edit?usp=sharing

Lily

**Comment by slnn** [comment]
Here are my steps for Login:

Steps for Login:
1> Update the master branch of benchmark project and create a new branch to apply the change in this pull slnn/liferay-benchmark-ee#276 then switch to the new branch. _(you can find the local branch named as **same-amount-load** in Main3 env)_

2> Get the count of successful tests for test step Log in from the test results of daily monitor testing, you can find it in /grinder/logs/grinder.log , I pick the first sample, (I have tried with the last sample, it will make test cost a longer time)

For example, here is the first sample of Login test case, then the count of successful tests for test step Log in is 113847,

```
****************************
This is Sample :1
Thu May 16 06:53:52 UTC 2024
****************************

Type   	Allowed Session Count	Current Session Count	Session Polling Time	Session Waiting Time	
Instant	8076                 	8108                 	88                  	13                  	
Average	8053                 	8047                 	88                  	11                  	

Description    	Successful Tests	Errors	Mean Time	Mean Time Standard Deviation	TPS	Peak TPS	
Home Page      	113668          	0     	74.0     	85.6                        	227	333     	
View Login Page	113791          	1     	52.3     	78.4                        	227	400     	
Log in         	113847          	0     	248      	216                         	227	355     	
Log out        	113305          	0     	48.7     	63.8                        	226	352     	
Total          	454611          	1     	106      	151                         	907	1190    
```
3>Apply Login's benchmark-ext.properties that you used to get the count of successful tests for test step Log in, set the count to property `grinder.thread.runs` in benchmark-ext.properties to override the default value 0, For example, based on the number we got in step 2>, the count of successful tests for test step Log in is **113847**, then we can choose **110000**, use this formula: `the value of grinder.thread.runs * the value of grinder.processes * the value of  grinder.threads * the agent count = 110000` to calculate the number for `grinder.thread.runs` for test case Login;
From the benchmark-ext.properties,` grinder.processes=2 grinder.threads=100, the agent count is 2`, then the value of  `grinder.thread.runs` = 110000/2*2*100=**275**

4>After applying **grinder.thread.runs=275**, run a runtime performance test, then I got the max elapsed time is 901841 ms, here is the output log of Grinder: https://gist.github.com/slnn/57e05e687de64118f1c18c191f7aeb0f

5>Add `sample.gc.log.initdelay=901841` to benchmark-ext.properties

**5-1>New steps here: in order to make sure tests are running under same amount load we need to use fixed grinder.thread.runs to make sure Grinder will run same iteration and on the other hand we do not want to increase the test time, let's do this:** 

According to the max elapsed time: 901841 ms we can know that Grinder will finish all these iterations after 901841 ms, then make sure our test will run a little longer than the 901841 ms as we will sample the gc log of portal afert test running 901841 ms  (see the value of sample.gc.log.initdelay=901841), I do this for Login by these:

In this performance comparison, We do not care about how many samples in grinder.log, we just want to make sure the gc log of portal will be sampled after test running 901841 ms and then stop the test, so I just make test run about 100 + 910 = 1010 seconds

#Change the value for sample.initdelay to make we will start the sample after test running 100 second
sample.initdelay=100
#Sample 10 times, the interval is 91 seconds
sample.interval=91
sample.repeattimes=10

#Make Grinder calculate statistics data at once, the default value of it is 1200,  the unit is second,  it means that Grinder will calculate statistics data after test running 1200 seconds, here we do not care about the result of Grinder, we just want to make we do not sample empty value
sample.agent.statistics.initdelay=0


6>Run runtime performance test;

7>Record the results in /portal/logs/portal-gc.log.results  and upload test result zip you got in step 6>

**Comment by victorhcunha** [comment]
Here are the results for **Document Library** testcase:

Portal Version | Git Id | grinder.thread.runs | TotalAllocations (MB) | Average Allocation Rate (MB/S) | Total G1 Evacuation Pause Count | Total Concurrent GC count | Max Young GC Pause Time (ms)
-- | -- | -- | -- | -- | -- | -- | --
Baseline | 624ebc3 | 35 | 943783 | 918.1036412 | 187 | 0 | 141.839
PR | - | 35 | 943878 | 916.9454774 | 187 | 0 | 141.97

More details please see: https://docs.google.com/spreadsheets/d/1M6VK8GtY9kkv1EwhGW7vwrEENSzyT7zKz-wOh11ZHBo/edit?usp=sharing

**Pull request closed without merging**
