### PR TITLE
LPS-120065 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-120065

This is only for master.

@pavel-savinov

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. There is no unique failure in PR.
See https://github.com/liferay-echo/liferay-portal/pull/2117
✔️ ci:test:stable - 21 out of 21 jobs passed
❌ ci:test:relevant - 75 out of 81 jobs passed in 1 hour 59 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4e6e0c4c14...18e80e371a

**Comment by brianchandotcom** [comment]
@pavel-savinov see 866404d

**Pull request closed without merging**
