### PR TITLE
LPS-86806

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @brianchandotcom this one is related to your comment here: https://github.com/brianchandotcom/liferay-portal/pull/65914

Personally, I think always starting a new class instantiation on a new line is cleaner, but I am fine with your preference as well.

**Comment by jpince** [comment]
@lawrence-lee is this a real error?

**Comment by lawrence-lee** [comment]
@jpince, The output seems different than what I'm expecting, but the files that were change also seem unrelated. Can we re-reun `ci:test:relevant` to be safe?

**Comment by brianchandotcom** [comment]
@hhuijser I like it this way more, I'd like to keep treating it the way we do for methods and var declarations. Thx!

**Comment by brianchandotcom** [comment]
@hhuijser I backported to 7.1.x.

**Pull request closed without merging**
