### PR TITLE
LPS-57625

### PR DESCRIPTION
**Pull request by shinnlok**

### CODE REVIEW

**Comment by shinnlok** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5563d52ecb...5c4d0ab466

**Comment by brianchandotcom** [comment]
@shinnlok @ChrisKian I think we need to do 5b13c35a1d320c8725372586031e6a7cb7ad8517 to ensure it works in all databases.

**Comment by brianchandotcom** [comment]
@shinnlok @ChrisKian see 8df58fe8125e52d5eee748e49cceb5c3f61d78d6 too thx

**Pull request closed without merging**
