### PR TITLE
LPS-59732

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-59732.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:retest

**Comment by pyoo47** [comment]
I've aborted this build temporarily so I can reset the PR Tester. I will retest this soon.

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9735dd068b...34a7f2353a

**Comment by brianchandotcom** [comment]
@jonmak08 @blzaugg please see my changes. Thx.

**Comment by jonmak08** [comment]
Thanks for catching all that @brianchandotcom!

**Pull request closed without merging**
