### PR TITLE
LPS-56339 remove my pages link from the product menu

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
@evannagayama this removes the entry "My Pages" in the "User Section" of the Product Menu. This could potentially break some tests.

thanks!

welcome_-_test_test_-_liferay

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9e64d2e932...90c47788cb

**Comment by evannagayama** [comment]
@juliocamarero thanks, we'll make sure to account for it

**Pull request closed without merging**
