### PR TITLE
Lps 152126 v 1 

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Hi Brian. Following up on https://github.com/brianchandotcom/liferay-portal/pull/124037#issuecomment-1266931685

This is "REST scaffolding and regen"

I left the `.lfrbuild-releng-ignore` files in the sub-directories because we do not want to prevent releasing the existing SAML modules?

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Duh @stian-sigvartsen thx , my bad about the releng. Reviewing.

**Comment by stian-sigvartsen** [comment]
So sorry, there is an upstream change to REST Builder affecting the regen. I have fixed it here: brianchandotcom/liferay-portal/pull/124076

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9ac04da69a...892eb3bc05

**Comment by brianchandotcom** [comment]
@stian-sigvartsen see my changes.

**Comment by stian-sigvartsen** [comment]
Thanks @brianchandotcom . I've sent a follow up to adjust the path instead of the `operationIds`. Because otherwise it will show as simply "Provider" on the "Entity Types" dropdown in Import/Export Centre. This will be confusing when we add different kinds of providers like OIDC. Please see brianchandotcom/liferay-portal/pull/124123

**Pull request closed without merging**
