### PR TITLE
LPS-105103 Build Lang

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:reopen

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e3c74585d6...f36f1d9912

**Comment by brianchandotcom** [comment]
@epgarcia see upstream for my changes. Thx.

**Comment by epgarcia** [comment]
Thanks @brianchandotcom. Happy New Year 🎉

**Pull request closed without merging**
