### PR TITLE
LPS-63501 Add test

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest @pyoo47 can you see why results never came?

**Comment by JorgeFerrer** [comment]
It may have been related to the fact that I did a push -f after doing a git rebase master just 1 min after the original pull request.

**Comment by JorgeFerrer** [comment]
ci:retest

**Comment by pyoo47** [comment]
This appears to have somehow gotten hung during the PR Tester reset. I'm going to abort this and retest later.

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Hey @JorgeFerrer in the future, just do another push to upstream (without force) and retrigger the CI, the original one will run with the old hash and the new trigger will one with the new hash... and nothing will clobber (otherwise it can hang).

**Comment by JorgeFerrer** [comment]
Ok, will do.

Regarding the code changes, do they look ok?

**Comment by pyoo47** [comment]
Regarding why the first result never came... It appears that this was a casualty of the PR Tester reset yesterday. The top-level job was trying to read a json file for a downstream job that ran on another slave. Unfortunately, when the read was attempted, that slave was in the middle of being reset so it did not respond.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5a6ff1930c...3ae0dbaaa5

**Comment by JorgeFerrer** [comment]
Thanks for the renames Brian, I like them.

**Pull request closed without merging**
