### PR TITLE
LPS-60935 Update usages

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
/cc @jbalsas @david-truong

This is the pull that provides support to RTL for css that don't come rtled in the bundle

**Comment by csierra** [comment]
@brianchandotcom 
it looks like rtl-css is still being used in the build...

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2cac398d22...86d6637237

**Comment by brianchandotcom** [comment]
@csierra @david-truong @jbalsas please verify upstream changes. Thx.

**Pull request closed without merging**
