### PR TITLE
LPS-55812

### PR DESCRIPTION
**Pull request by shinnlok**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f01a4c3bae...e31284e5a7

**Comment by brianchandotcom** [comment]
I merged this in @shinnlok but it's technically still wrong. We only want to delete the image IF the add image succeeds.

**Comment by brianchandotcom** [comment]
@shinnlok see upstream for my changes. Thx.

**Comment by shinnlok** [comment]
Makes sense. Thanks!

**Pull request closed without merging**
