### PR TITLE
LPS-103170 Add task setup-profile-dxp

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6f6d4fc967...8d167fb942

**Comment by brianchandotcom** [comment]
Super nice ;) backported all the way to 7.0.x thanks peter!

**Comment by jpince** [comment]
@topolik @csierra this was chosen over the [previous solution](https://github.com/brianchandotcom/liferay-portal/pull/79365#issuecomment-540661570), see [LPS-102998](https://issues.liferay.com/browse/LPS-102998)

 Can you please review the changes made in [LPS-103170](https://issues.liferay.com/browse/LPS-103170)? (there were several pulls) I think what are specifically relevant are the commands `setup-profile-dxp` and `setup-profile-portal`. Peter also made some changes to the gradle plugin, not sure how relevant those would be for you to review. Thank you!

cc/ @xbrianlee

**Comment by topolik** [comment]
Looks good, thanks @jpince

**Pull request closed without merging**
