### PR TITLE
LPS-164955 Adapt EditObjectField to support new Formula Field and Create Formula Card with ExpressionBuilder

### PR DESCRIPTION
**Pull request by danvb112**
Related Issues:

https://issues.liferay.com/browse/LPS-164955
https://issues.liferay.com/browse/LPS-164951

### CODE REVIEW

**Comment by danvb112** [comment]
ci:reopen

**Comment by danvb112** [comment]
Hey @brianchandotcom, sorry for the last PRs, I misinterpreted what you asked, but now I've reviewed all the language keys in the Formula with Design field and fixed it.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3a66f4732c...892fa8e514

**Comment by brianchandotcom** [comment]
Great job @danvb112 looks much better this time!

Just 892fa8e51485afe901057d1eb740bbb2e518f1e0

**Pull request closed without merging**
