### PR TITLE
LPS-102048 FIX: Elasticsearch 7: IllegalArgumentException[Can only use phrase prefix queries on text fields - not on [properties] which is of type [keyword]]

### PR DESCRIPTION
**Pull request by arboliveira**
Needed in DXP 7.2 SP1 for the upcoming Elasticsearch 7 Connector in Marketplace.

----

❌ **ci:test:search - 21 out of 24 jobs passed in 1 hour 11 minutes 8 seconds 566 ms**
https://github.com/arboliveira/liferay-portal/pull/770#issuecomment-533759913

Only 1 unique failure; CI infra hiccup with fix sent upstream already.
`LocalFile.Elasticsearch6#ElasticsearchRemoteClusterSmokeTest`
Fixed by: https://github.com/brianchandotcom/liferay-portal/pull/78689
Reference: https://issues.liferay.com/browse/LRQA-52265

----

Author: @BryanEngler 
Reviewer: @arboliveira

_[Bug] Elasticsearch 7: IllegalArgumentException[Can only use phrase prefix queries on text fields - not on [properties] which is of type [keyword]]_
https://issues.liferay.com/browse/LPS-102048

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a5296f7b87...911341c924

**Comment by brianchandotcom** [comment]
@arboliveira this shows

In this pull

https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/79778/ 

Test Result (1 failure / +1)
com.liferay.portal.search.facet.faceted.searcher.test.FolderFacetTest.testAggregation

In my origin

https://test-1-23.liferay.com/job/test-portal-testsuite-upstream-batch(master)/AXIS_VARIABLE=5,label_exp=!master/1558/

com.liferay.portal.search.facet.faceted.searcher.test.CategoryFacetTest.testAggregation

I may need to revert this change since I'm publishing jars for SP1 right now

@jpince fyi

**Comment by brianchandotcom** [comment]
@arboliveira I'm reverting it...

**Comment by brianchandotcom** [comment]
@arboliveira oh, when I mentioned "in my origin", that was after I merged this, and pushed it to my origin, but stable wasn't syncing.. and I dug around and found that the failures were related to this pull.

**Comment by arboliveira** [comment]
@brianchandotcom Fair call. For what it's worth, both tests passed in my original self pull. Investigating if this change adds some sort of flakeness.

https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=8,label_exp=!master/314528/testReport/com.liferay.portal.search.facet.faceted.searcher.test/

**Pull request closed without merging**
