### PR TITLE
DO NOT MERGE -- Do not pin classloader

### PR DESCRIPTION
**Pull request by csierra**
/cc @topolik

### CODE REVIEW

**Comment by csierra** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@csierra did you mean to send to someone else?

**Comment by tinatian** [comment]
Hi @csierra,
If you are seeing a leaking caused by this, most probably there is a missing invocation to unregister. 
From the API's point of view, the map here has a register method to put, and a corresponding unregister to remove, it should be fine, in this case, we must call the unregister somewhere at sometime.
It should not need ConcurrentReferenceKeyHashMap to help cleaning, normally we use ConcurrentReferenceKeyHashMap when there is no way to do cleaning or we do not know when to do cleaning.

Tina.

**Comment by csierra** [comment]
Hi @tinatian,

yes... that's what I thought but I couldn't tell if the call to unregister was possible on every expected usage. 

Thx for clarifying.

Carlos.

**Pull request closed without merging**
