### PR TITLE
LPS-87545

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Thanks @Preston-Crary!

**Comment by 4lejandrito** [comment]
Hi @Preston-Crary, @brianchandotcom,

I was following the pattern found in many `ServletContextUtil` classes. (`git grep "_instance._getServletContext()"). We might want to change those too.

**Comment by brianchandotcom** [comment]
@Preston-Crary can you do a few and then notify @hhuijser to follow this new pattern?'

Thx @4lejandrito

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/7286

**Pull request closed without merging**
