### PR TITLE
LPS-61440

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@brianchandotcom this SF failure isn't related to the commit.  It's from a build.gradle in asset-test

**Comment by brianchandotcom** [comment]
@mhan810 I sent to @briangreenwald  at https://github.com/briangreenwald/liferay-portal/pull/7

1.) LegacyTokenPropsKeys#TOKEN_KEYS_SHIBBOLETH, TOKEN_KEYS_SITEMINDER and LegacyOpenIdPropsKeys#OPENID_KEYS are inconsistent

2.) LegacyLDAPPropsKeys#NONPOSTFIXED_LDAP_KEYS  and LegacyLDAPPropsKeys#SERVER_ID_POSTFIXED_KEYS are inconsistent.

They should all be consistently named.

3.) Avoid

Dynamic-Import: *
Import-Package: *

@rotty3000 doesn't like those. Please resend.

Thx

**Comment by mhan810** [comment]
K I resend later.  Prob faster for me to punch thru it tonight.

The dynamic import is necessary B/c of the way the config invocation
handler is using classes from other libs that cannot be statically imported
@ build time.  This is similar to the issues with the scripting libs

-m

Sent from my mobile device.

**Comment by brianchandotcom** [comment]
Got it.. as long as it's intentional and not a shortcut. Thx @mhan810

**Pull request closed without merging**
