### PR TITLE
LPS-86125 Reorder by path, feel free to remove this commit if you prefer order by module name

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by jpince** [comment]
@brianchiu @kyle-miho POSHI failures

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@ealonso I liked your change to sort by path, but there were poshi failures, and I think I fixed them in 4c9d194 (real bug)

**Comment by ealonso** [comment]
@brianchandotcom Thanks you very much!!

**Pull request closed without merging**
