### PR TITLE
LPS-71131

### PR DESCRIPTION
**Pull request by danielkocsis**

### CODE REVIEW

**Comment by danielkocsis** [comment]
ci:reopen

**Comment by danielkocsis** [comment]
Hey @pyoo47, @michaelhashimoto and @alee8888,

could you guys take a look on this? The errors seems unrelated from the change, but they are always present after the CI execution.

thanks,
Daniel

**Comment by jpince** [comment]
@danielkocsis here is the actual test that's failing:
`     [exec] com.liferay.calendar.util.test.CalendarUtilTest > testToCalendarBookingJSONObjectWorksWithoutManageBookingsPermission STARTED
     [exec] 13:15:50,050 WARN  [liferay/mail-1][MailEngine:631] Unable to connect to a valid mail server. Please make sure one is properly configured: Could not connect to SMTP host: localhost, port: 3241`
@vicnate5 @marcellustavares @leodb can you provide any insight on why this is failing?

Closing this pull until investigation is complete.

**Comment by jpince** [comment]
ci:close

**Comment by danielkocsis** [comment]
Hey @jpince,

do you have any update on this?

thanks,
Daniel

**Comment by vicnate5** [comment]
Hey @danielkocsis,

Sorry for the delay, but I was informed that this issue was fixed by https://github.com/liferay/liferay-portal/commit/8b16848639cb328b720a2e76139e3fa1ae0795a4.

You should be able to resend this now.

CC @jpince

**Comment by jpince** [comment]
ci:reopen

**Pull request closed without merging**
