### PR TITLE
LPS-191475 Add a method and a specific exception to handle the layout lock

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://liferay.atlassian.net/browse/LPS-191475

@lfbesada

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/12983

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c84d8e1584...40bce77748

**Comment by brianchandotcom** [comment]
@lfbesada the exception is never used? Is that on purpose? I merged this, but it seems very strange to not use the exception.

**Pull request closed without merging**
