### PR TITLE
LPS-100756 Changes signature to take container instead of containerId in advance of future work

### PR DESCRIPTION
**Pull request by jbalsas**
Replacement for: #77735

This is an intermediate step towards wrapping up existing React set-up in JSP files inside a `<react:component />` tag. This is why you see changes like the following in this PR:

Before:

```javascript
export default function(id, props) {
  render(
    <Component {...props} />,
    document.getElementById(id)
  );
}
```

Intermediate (this PR):

```javascript
function renderComponent(props) {
  return <Component {...props} />;
}

export default function(id, data) {
  render(renderComponent, data, id);
}
```

Which looks like an unnecessary layer of indirection, but the eventual end state will be that people use `<react:component />` in their JSP, and these JS files will simplify as follows:

```javascript
export default function(props) {
  return <Component {...props} />;
}
```

ie. `renderComponent` will become the new default export, and the old default export will be deleted.

cc: @epgarcia, @andresfulla, @adolfopa, @boton, @brunofarache, @brunobasto

Also, @arboliveira, @thektan, note that this change will break portal-search-tuning-rankings-web until the corresponding master-private PR goes in: thektan/liferay-portal-ee#34

Reviewed here: wincent#59

/cc @wincent, rebased from https://github.com/brianchandotcom/liferay-portal/pull/77741

### CODE REVIEW

**Comment by jbalsas** [comment]
Unique failure looks unrelated

/cc @john-co

**Comment by jbalsas** [comment]
FYI, @adolfopa, @boton, @epgarcia, @andresfulla, @brunobasto, @brunofarache, @arboliveira, @thektan, @wincent you can take a peak at the expected final outcome at: https://github.com/jbalsas/liferay-portal/pull/1904

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a427b826b9...c69dd7792e

**Comment by brianchandotcom** [comment]
@jbalsas @wincent can you send a follow up pull and sort this:

```
					props: {
						initialSegmentsVariants: <%= segmentsExperimentDisplayContext.getSegmentsExperimentRelsJSONArray(locale) %>,
						segmentsExperiences: <%= segmentsExperimentDisplayContext.getSegmentsExperiencesJSONArray(locale) %>,
						segmentsExperiment: <%= segmentsExperimentDisplayContext.getSegmentsExperimentJSONObject(locale) %>,
						segmentsExperimentGoals: <%= segmentsExperimentDisplayContext.getSegmentsExperimentGoalsJSONArray(locale) %>,
						selectedSegmentsExperienceId: '<%= segmentsExperimentDisplayContext.getSelectedSegmentsExperienceId() %>'
					},
					context: {
```

context should go before props? I'd really like to sort anything that can be sorted. Thx!

**Comment by brianchandotcom** [comment]
@jbalsas @wincent I sorted it c9a673a9e04fab9da8fccb52c80f55c62fbb0f93

**Comment by jbalsas** [comment]
Thanks a lot @brianchandotcom, I missed that one!

We should be removing all that code inside the jsps shortly. Hopefully in the next few days we can send your way a better approach with less boilerplate!

**Comment by wincent** [comment]
In addition to what @jbalsas said, we are currently working on [running Prettier on the JS inside JSP files](https://github.com/liferay/liferay-npm-tools/issues/98); that should be able to handle the presentational aspects, and we might be able to pass JS-in-JSP through ESLint as well, which would [catch sorting problems](https://github.com/liferay/eslint-config-liferay/pull/63).

**Pull request closed without merging**
