### PR TITLE
digital signature

### PR DESCRIPTION
**Pull request by joseabelenda**

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bed469d638...22c17d008f

**Comment by brianchandotcom** [comment]
@joseabelenda see 22c17d008f4cc8479ca4ec9401b01b4634b9ae88

Thx!

**Comment by joseabelenda** [comment]
I saw @brianchandotcom 

Thx!

**Pull request closed without merging**
