### PR TITLE
LPS-54611 Avoid circular property definition

### PR DESCRIPTION
**Pull request by CAustin582**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Thx Chas, how come liferay.home=${liferay.home} is OK? in the line right above it?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ea6a11b9c1...b8cde5a707

**Comment by CAustin582** [comment]
Probably because liferay.home is always set

**Comment by CAustin582** [comment]
In other words, Ant is trying to resolve the unset property by looking at the definition in the same file on the same line, where it finds the initial reference to the property again

**Pull request closed without merging**
