### PR TITLE
#ping LPS-56372 MVC Extension -> ResourceURLs

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @izaera

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/09590aae7b...a8700d3034

**Comment by brianchandotcom** [comment]
@sergiogonzalez I added a marker interface. please see my changes in upstream. Thx.

**Pull request closed without merging**
