### PR TITLE
LPS-112548

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@hhuijser can you resend? rebase error.

**Comment by brianchandotcom** [comment]
@hhuijser see my change in 9a6bea1

But it looks weird to me. Not sure why it's asking me for a line break.

**Comment by jpince** [comment]
@hhuijser resent https://github.com/brianchandotcom/liferay-portal/pull/88250/commits/65c9837b239f45729aeda9b07672995ec8b8e2de here: https://github.com/brianchandotcom/liferay-portal/pull/88260

**Pull request closed without merging**
