### PR TITLE
LPS-70631

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-70631

Reviewed by @sergiogonzalez in https://github.com/sergiogonzalez/liferay-portal/pull/3798 and https://github.com/jorgediaz-lr/liferay-portal/pull/132

He asked to test his SF changes and send to you

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:reopen

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
See 62691b594eb85a36075f1269ee70698e6760a58e Thx

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
