### PR TITLE
LPS-131285 add batch support to object endpoints

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d6ee131993...12c8987210

**Comment by brianchandotcom** [comment]
@nhpatt can you validate my logic check in

12c8987210750e74de3a78dd29cfdb122e988853

```
(parameterValue.length() > 2)
```

Not sure if that should be 2 or 3.

Thx.

**Comment by nhpatt** [comment]
Will do, have to change something :)

**Pull request closed without merging**
