### PR TITLE
LPS-77530

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
ci:test

**Comment by mhan810** [comment]
@brianchandotcom failure not related to this pull, in screens repo

**Comment by mhan810** [comment]
@brianchandotcom all the failures from full run are not related to this pull.  
(1) SF failure due to microblogs, 
(2) functional due to forms, 
(3) central due to screens

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/449fbd19b9...fa941ad67a

**Comment by brianchandotcom** [comment]
@mhan810 minor changes in upstream to match another class you wrote a while ago.

**Pull request closed without merging**
