### PR TITLE
LPS-180487 Use learnMessage to render link

### PR DESCRIPTION
**Pull request by larissacribeiro**
Resent from here: https://github.com/brianchandotcom/liferay-portal/pull/138342
I've talked to the team and they've changed the message

### CODE REVIEW

**Comment by larissacribeiro** [comment]
ci:reopen

**Comment by yunlinsun** [comment]
hey @larissacribeiro ,
rebase error, please fix and resend, thanks.

cc @brianchandotcom

**Comment by yunlinsun** [comment]
ci:close

**Comment by larissacribeiro** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/138607

**Pull request closed without merging**
