### PR TITLE
COMMERCE-10535 Enable customised cookie configuration modal for product comparison

### PR DESCRIPTION
**Pull request by dsanz**
### References

- https://issues.liferay.com/browse/COMMERCE-10535
- This PR is forwarded from https://github.com/liferay-frontend/liferay-portal/pull/2938 which has non-related test failures, verified both from Commerce and FI QA

### What is the goal of this PR?
To make product comparison feature to obey user consent for functional cookies. This feature requires a non-essential cookie which must be accepted by users.

In doing so, we added a DXP JS api to handle cases like this in the future, so that other applications don't need to reinvent the wheel when some feature requires cookie acceptance

Before this change, it was possible to select products for comparison, and the minicompare component was rendered. Also, the `COMMERCE_COMPARE_cpDefinitionIds_*` cookie was created and stored in the user's device.

After this change, the product selection process ensures functional cookies are accepted before setting `COMMERCE_COMPARE_cpDefinitionIds_*` cookie. Also, product comparison widget is not displayed until user these cookies are accepted. Cookie consent modal is shown to allow user to give consent.

### CODE REVIEW

**Comment by dsanz** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@dsanz @bryceosterhaus the language keys seem off to me.

Please fix and resend. Thx.

**Comment by dsanz** [comment]
Please see https://github.com/liferay/liferay-portal/pull/5209

**Comment by dsanz** [comment]
pls see https://github.com/brianchandotcom/liferay-portal/pull/128796

**Pull request closed without merging**
