### PR TITLE
Lps 176579

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6b2d49f412...3bd2a8c842

**Comment by brianchandotcom** [comment]
@ling-alan-huang

git ls-files **DTOConverterConstants**

Files are not in the same package. Please move them and SF enforce. Thx!

**Comment by ling-alan-huang** [comment]
SF rule: https://issues.liferay.com/browse/LPS-184431

**Pull request closed without merging**
