### PR TITLE
LPS-74471 portal-search-web: gw buildLang

### PR DESCRIPTION
**Pull request by thektan**
http://issues.liferay.com/browse/LPS-74471

Updated to a complete sentence with help from @rbohl

cc: @BryanEngler

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fb7bf57942...1971b9f0ff

**Comment by brianchandotcom** [comment]
@BryanEngler see b1ea6dda9c2c6f032848f421cc1360ea776f4cb3

**Comment by brianchandotcom** [comment]
@BryanEngler also 1db03e2

**Comment by lipusz** [comment]
Testing something with Csaba. Will trigger backport.

**Comment by lipusz** [comment]
lbm:backport

**Pull request closed without merging**
