### PR TITLE
LPS-110622 remove possible garbage for previous tests

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/33b47e58d0...1a83585a70

**Comment by brianchandotcom** [comment]
@leoadb I merged this.. but this is still not the best fix. We should fix the other tests that are populating this table and delete it there...

And your upgrade test may still fail another test populates another bad table. They key is to fix the other tests that are not cleaning up.

**Comment by leoadb** [comment]
@brianchandotcom I know this, we already created tasks to check all the integration tests we have. Thanks!

**Pull request closed without merging**
