### PR TITLE
LPS-87755 buildLang

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by jpince** [comment]
@kyle-miho @brianchiu see POSHI failures

**Comment by brianchiu** [comment]
@sandrodw3 @jpince 
This looks like the tests might need to be updated. Will take a look.

**Comment by brianchiu** [comment]
ci:close

**Comment by brianchiu** [comment]
Sent with test fix here:
https://github.com/brianchandotcom/liferay-portal/pull/65905

**Pull request closed without merging**
