### PR TITLE
LPS-109177

### PR DESCRIPTION
**Pull request by p2kmgcl**
/cc @ealonso
/cc @NemethNorbert

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:sf @yichenroy tests didn't automatically initiate?

**Comment by jpince** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:close

**Comment by p2kmgcl** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/85755

**Pull request closed without merging**
