### PR TITLE
LPS-58260

### PR DESCRIPTION
**Pull request by Ithildir**
cc @jbalsas :blush:

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f1b045ee86...924e5fccad

**Comment by Ithildir** [comment]
Hi @brianchandotcom!

For this PR, would you please publish `gradle-plugins-js-module-config-generator` (1.0.5), `gradle-plugins-js-transpiler` (1.0.7) and the usual snapshot of `gradle-plugins`?

In order to update the Gradle cache for `gradle-plugins`, I would try to delete `.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.gradle.plugins`, go into any module and try something like `../../gradlew classes`: that should download the new snapshot from the repo!

Thank you!! :blush:

**Comment by brianchandotcom** [comment]
@Ithildir I tried downloading a new gradle-plugins snapshot, but it kept giving me an old one? And this is after published a new gradle-plugins snapshot. Could it be a CDN cache?

**Comment by Ithildir** [comment]
Maybe, yes... I could add an option to bypass the CDN and go straight to http://repository.liferay.com :confused:

**Pull request closed without merging**
