### PR TITLE
LPS-58324

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@Ithildir can you see what @mhan810  did in this pull?

I wanted to merge it in, but there's no easy to ensure javax.mail is done properly in the future. The goal would be to remove it from the list of normal compile, so that people have to explicity add javax.mail (or else it won't compile)

@Ithildir can you fix and resend? Thx.

**Comment by mhan810** [comment]
Brian, Andrea and I talked about this change.  He was going to remove the
mail jar from base in another ticket

Sent from my mobile device.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/36fe984b4a...8f5723cd50

**Comment by brianchandotcom** [comment]
Got it.. @mhan810 

@Ithildir I merged this in. Please remove mail.jar from main.

**Pull request closed without merging**
