### PR TITLE
Data Partitioning SQL Builder: move classes around

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 see weird error?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/98112b8f41...06159c42b8

**Comment by pyoo47** [comment]
It looks like the portal instance failed to start up but recent changes seems to have worked so it timed out faster this time. There's a Jstack trace in the log so I can ask Shuyang to take a look.

**Comment by pyoo47** [comment]
I take back my previous comment about jstack. There is no jstack trace in the log.

**Comment by pyoo47** [comment]
It looks like the portal instance started up but immediately started throwing errors. I'll run it by Shuyang.

```
 [exec] 17-Mar-2016 14:54:09.763 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 113607 ms
     [exec] 17-Mar-2016 14:54:14.945 SEVERE [http-nio-8080-exec-1] org.apache.catalina.core.ApplicationDispatcher.invoke Servlet.service() for servlet jsp threw exception
     [exec]  FreeMarker template error:
     [exec] The following has evaluated to null or missing:
     [exec] ==> liferay_util  [in template "_SERVLET_CONTEXT_/classic/templates/portal_normal.ftl" at line 12, column 11]
     [exec] 
     [exec] ----
     [exec] Tip: If the failing expression is known to be legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
     [exec] ----
     [exec] 
     [exec] ----
     [exec] FTL stack trace ("~" means nesting-related):
     [exec] 	- Failed at: @liferay_util["include"] page=top_hea...  [in template "_SERVLET_CONTEXT_/classic/templates/portal_normal.ftl" at line 12, column 9]
     [exec] ----
     [exec] 
     [exec] Java stack trace (for programmers):
     [exec] ----
     [exec] freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
     [exec] 	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:131)
     [exec] 	at freemarker.core.DynamicKeyName._eval(DynamicKeyName.java:54)
     [exec] 	at freemarker.core.Expression.eval(Expression.java:78)
     [exec] 	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:74)
     [exec] 	at freemarker.core.Environment.visit(Environment.java:324)
     [exec] 	at freemarker.core.MixedContent.accept(MixedContent.java:54)
     [exec] 	at freemarker.core.Environment.visit(Environment.java:324)
     [exec] 	at freemarker.core.Environment.process(Environment.java:302)
     [exec] 	at freemarker.template.Template.process(Template.java:325)
     [exec] 	at com.liferay.portal.template.freemarker.FreeMarkerTemplate.processTemplate(FreeMarkerTemplate.java:121)
     [exec] 	at com.liferay.portal.template.AbstractSingleResourceTemplate.processTemplate(AbstractSingleResourceTemplate.java:78)
     [exec] 	at com.liferay.taglib.util.ThemeUtil.doIncludeFTL(ThemeUtil.java:285)
     [exec] 	at com.liferay.taglib.util.ThemeUtil.doDispatch(ThemeUtil.java:156)
     [exec] 	at com.liferay.taglib.util.ThemeUtil.includeFTL(ThemeUtil.java:100)
     [exec] 	at com.liferay.taglib.util.ThemeUtil.include(ThemeUtil.java:82)
     [exec] 	at com.liferay.taglib.theme.IncludeTag.doEndTag(IncludeTag.java:34)
     [exec] 	at org.apache.jsp.html.common.themes.portal_jsp._jspx_meth_liferay_002dtheme_005finclude_005f1(portal_jsp.java:758)
     [exec] 	at org.apache.jsp.html.common.themes.portal_jsp._jspService(portal_jsp.java:695)
     [exec] 	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
     [exec] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
     [exec] 	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:438)
     [exec] 	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
     [exec] 	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
     [exec] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
     [exec] 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
```

**Pull request closed without merging**
