### PR TITLE
OAUTH2-157 Resent without language key changes - 2

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Hi Brian. This is a resend of brianchandotcom/liferay-portal/pull/60431 with fixed tests.

CI has already verified here: stian-sigvartsen/liferay-portal/pull/106

/cc @topolik @csierra

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
"This pull contains no unique failures."

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/024af976f2...00821aaeab

**Comment by brianchandotcom** [comment]
@natecavaugh modules/apps/oauth2-provider/oauth2-provider-web/src/main/resources/META-INF/resources/css/main.scss still seems to be off? Can you send me a fix? This pull is in upstream.

**Comment by natecavanaugh** [comment]
@brianchandotcom for some reason it didn't notify me on this pull.

I'll resend my changes, but it looked like Jason reverted it before the release. I'm guessing it was just never brought back in? I'll send it again right now :)

**Comment by stian-sigvartsen** [comment]
@natecavanaugh following the revert it was merged into master, at least. Thanks for looking into this!

**Comment by natecavanaugh** [comment]
@stian-sigvartsen Hmm... it's not showing up for me in master, but I went ahead and sent the pull here: https://github.com/brianchandotcom/liferay-portal/pull/60660

Let me know if you guys need anything else :)

**Comment by topolik** [comment]
Thanks a lot @natecavanaugh!

**Pull request closed without merging**
