### PR TITLE
LPS-104957 These factories must be automatically activated or the renderers won't be registered

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
@adolfopa @cgoncas

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/63ff32c440...6db7596449

**Comment by brianchandotcom** [comment]
@preston-crary this looks like a race condition no?

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/8578

**Pull request closed without merging**
