### PR TITLE
LRAC-5230

### PR DESCRIPTION
**Pull request by rachaelkoestartyo**
/cc @shinnlok

### CODE REVIEW

**Comment by shinnlok** [comment]
@tainguyen100

**Comment by brianchandotcom** [comment]
@shinnlok you sure this will fix it? I'm going to wait til we are synced again before merging this.

SF issue is not related and I'm fixing in my origin right now.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2ee8e2e1b9...a3d34f3989

**Comment by brianchandotcom** [comment]
Ok, upstream and origin synced, so now I'm merging this.

**Comment by brianchandotcom** [comment]
@rachaelkoestartyo this is in 7.2.x. I just need pulls for 7.1.x and 7.0.x

**Comment by rachaelkoestartyo** [comment]
@brianchandotcom will send both soon

**Pull request closed without merging**
