### PR TITLE
Lps 84256

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
CC @hudakl

**Comment by brianchandotcom** [comment]
@pyoo47 what happened here?

@shuyangzhou also, I don't think we can get rid of PropertyFieldAccessor because that's is used in 7.0.x.

The generated code goes back to 7.0.x since it uses Gradle. Can you resend without removing option of using PropertyFieldAccessor in hbm.xml for older bundles? 7.1.x and master can use the newer one.

**Comment by hudakl** [comment]
Hi Shuyang,

Looking at your changes I was wondering if they should be handled on a separate ticket. My original fix resolved the issue described on LPS-84256 and yours seem to add further improvements which are not strictly related to the issue. I think that could lead to confusion regarding the bugfix.
I believe handling this on a separate ticket would make the backport more seamless, since it appears, based on Brian's comment, that some of these changes couldn't be applied on 7.0.x.

Please correct me if I misunderstood something.

Thank you,
Laci

**Comment by shuyangzhou** [comment]
@hudakl I put it in the same ticket because they need to either be backported together or not backported at all for 7.1.x. For 7.0.x, backporting this change will make no difference in terms of caches. Since SB is not going to regenerate the new code for 7.0.x. But at least this way the codebase is still in sync with 7.1.x and master.

**Comment by hudakl** [comment]
Thank you for the explanation.

**Pull request closed without merging**
