### PR TITLE
LPS-164761 Search first published layout

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-164761

@ealonso

### CODE REVIEW

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/9892

:heavy_check_mark: ci:test:stable - 27 out of 27 jobs passed
:x: ci:test:relevant - 124 out of 169 jobs passed in 3 hours 9 minutes

**Comment by ozysouza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/48934ae60e...d347ff29b0

**Comment by brianchandotcom** [comment]
@ealonso see 169be4ec4f770f4da5f301e6506586620432adaf thx

**Comment by brianchandotcom** [comment]
@ealonso and 9b5832cae7df72b60db7bc17c1239e715e47d7e8

**Pull request closed without merging**
