### PR TITLE
LPS-58116

### PR DESCRIPTION
**Pull request by natecavanaugh**

### CODE REVIEW

**Comment by mjbradford89** [comment]
Hey @brianchandotcom, whoops these failures are my fault.  I forgot to mention that because I made changes to com.liferay.gradle.plugins (e9a7f6ada5a5c0020cd236afafdf4ada5cbc2c4f), we're going to have to update that jar in the gradle cache.

Locally I've just been running `../../../gradlew install` from modules/sdk/gradle-plugins, and upping the version number in modules/build.gradle.  And that works but obviously only locally since it goes into my local maven repo.  I'm not sure the best way to handle this for the pull request tester.

**Comment by brianchandotcom** [comment]
@mjbradford89 can you resend just the gradle changes?

Then I'll publish them and you can resend the rest.

**Comment by mjbradford89** [comment]
@brianchandotcom Sure. Sending now

**Comment by mjbradford89** [comment]
Just the gradle changes: https://github.com/brianchandotcom/liferay-portal/pull/29951

**Pull request closed without merging**
