### PR TITLE
Lps 61271

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @rotty3000 @Preston-Crary

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@michaelhashimoto @Ithildir what is this?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bdcb13644e...6904788f16

**Comment by Ithildir** [comment]
@shuyangzhou: The log has this error:
```
1 errors in POSHI
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
     [exec] 
     [exec] Invalid path locator ControlMenu#EDIT_COG
     [exec] 
     [exec] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/macros/SitePage.macro:262
```

**Comment by kenjiheigel** [comment]
Fixed at head:
https://github.com/liferay/liferay-portal/commit/1a2500d591286e5e7a4869f4593e7aa336801b92

**Pull request closed without merging**
