### PR TITLE
LPS-108211 Control possible NPE (one never knows)

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
Thanks @IstvanD, @dacousalr!

@ealonso

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2bade355db...8769806ef6

**Pull request closed without merging**
