### PR TITLE
LPS-77392 Point old loader to CDN

### PR DESCRIPTION
**Pull request by izaera**
Hey Brian!

We have had tons of URL-generation issues in the past few years (forgetting to concatenate proxy, or cdn settings...). With this, we are trying to introduce a single point of URL generation moving forward.

Once we agree on the pattern and API we want, we will proceed to update usage throughout portal to make sure URL generation is consistent and behaves according to the expectations.

What do you think?

Thanks!

### CODE REVIEW

**Comment by izaera** [comment]
Resend of https://github.com/brianchandotcom/liferay-portal/pull/55712

**Comment by izaera** [comment]
See tests in https://github.com/jbalsas/liferay-portal/pull/1039#issuecomment-368886073

**Comment by brianchandotcom** [comment]
This looks nice @izaera 

I need a day more to digest it. Thx.

**Comment by brianchandotcom** [comment]
@jbalsas I talked to @izaera 

He will resend it not in kernel, but in a module as:

modules/apps/foundation/portal-url-builder

bundle com.liferay.portal.url.builder.api exporting com.liferay.portal.url.builder

bundle com.liferay.portal.url.builder.impl with com.liferay.portal.url.builder.internal.* as its packages

Thank you for making sure this was unblocked. My bad.

**Comment by jbalsas** [comment]
No worries, @brianchandotcom, thanks for your input!! ☺️

**Pull request closed without merging**
