### PR TITLE
LPS-62636 buildLang

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/63e6ad6e46...68dabc9863

**Comment by brianchandotcom** [comment]
@pavel-savinov @ealonso please see my changes in upstream.

**Pull request closed without merging**
