### PR TITLE
LRCI-433 ant logic changes for db2 on k8s jenkins

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRCI-433

@pyoo47 https://github.com/pyoo47/liferay-portal/pull/1078 (Relevant PASSED)

### CODE REVIEW

**Comment by kenjiheigel** [comment]
Backports: 
https://github.com/brianchandotcom/liferay-portal-ee/pull/25515 (7.1.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/25516 (7.0.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/25517 (ee-6.2.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/25518 (ee-6.2.10)
https://github.com/brianchandotcom/liferay-portal-ee/pull/25519 (ee-6.1.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/25520 (ee-6.1.30)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a47bd277f0...ff1842c131

**Comment by brianchandotcom** [comment]
@kenjiheigel Can you send me a backport to 7.0.x? The link you sent me for 7.0.x is actually for 7.1.x.

And the link you sent for 7.1.x was not even your pull.

Thx.

**Comment by kenjiheigel** [comment]
Oh woops! I missed a rebase error locally on 7.0.x. Thanks for catching! Sent here:
https://github.com/brianchandotcom/liferay-portal-ee/pull/25534

**Pull request closed without merging**
