### PR TITLE
LPS-108261 Add available fragment compositions to the components sidebar

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
ci:test:sf

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:relevant - We aborted all master pull request jobs.  However, we decided to re-run all pulls in @brianchandotcom queue.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c627564918...048253f52b

**Pull request closed without merging**
