### PR TITLE
LPS-90204 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LPS-90204

### CODE REVIEW

**Comment by john-co** [comment]
ci:reopen

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/69ae929d5d...6eeea9163a

**Pull request closed without merging**
