### PR TITLE
LPS-92335 Update asset tests + fix semver in portal-search-test-util (Additional commits)

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-92335

Follow-up on https://github.com/brianchandotcom/liferay-portal/pull/69724#issuecomment-474557437. Regression in Blogs discovered by the new test reported in https://issues.liferay.com/browse/LPS-92385.

Regards,
Tibor

/cc @adolfopa, @arboliveira

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
Sorry for the doubled test invocations. I was not aware of this changes to your PRs.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d668aa1778...03bb33d4eb

**Comment by lipusz** [comment]
Fixing the remaining ones. Sorry, I got back different results from CI when testing today for myself.

**Comment by lipusz** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/69812

**Pull request closed without merging**
