### PR TITLE
LPS-74544

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@petershin

**Comment by hhuijser** [comment]
Pull for 7.0.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/18978

**Comment by petershin** [comment]
@hhuijser - Sent pulls to update the subrepos:

https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/577
https://github.com/liferay/com-liferay-pulpo-connector-de-private/pull/119

Checked the subrepos for changes in these pulls:

https://github.com/brianchandotcom/liferay-portal/pull/53609, https://github.com/brianchandotcom/liferay-portal/pull/53643, https://github.com/brianchandotcom/liferay-portal/pull/53647, https://github.com/brianchandotcom/liferay-portal/pull/53648, https://github.com/brianchandotcom/liferay-portal/pull/53651

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a45e7111df...610907a59f

**Pull request closed without merging**
