### PR TITLE
LPS-76168 Instead of displaying pages blank page is shown

### PR DESCRIPTION
**Pull request by jkappler**
cc:// @pavel-savinov, @ealonso

### CODE REVIEW

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
@pyoo47 @michaelhashimoto this pull didn't run any int or unit tests... not sure if this is a concern

**Comment by jpince** [comment]
ci:stop

**Comment by jpince** [comment]
nevermind, only change made was in portal-web

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a77cc7d4ec...51d831aa89

**Comment by brianchandotcom** [comment]
@pavel-savinov @jkappler see 51d831aa89fa0110f564cf8a4cf2c4a215f8d7fd for my Git command and why I renamed the namespace input. Thx.

**Pull request closed without merging**
