### PR TITLE
LPS-65191

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@matethurzo fyi

**Comment by mhan810** [comment]
@brianchandotcom SF errors are unrelated

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ddbd1a1313...3675b864ca

**Comment by brianchandotcom** [comment]
@matethurzo need tests for resources-importer :) other folks are making changes... fyi.

**Pull request closed without merging**
