### PR TITLE
LPS-56222 Fix tests

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@sergiogonzalez I'll fix the SF..
don't worry about it.

**Comment by sergiogonzalez** [comment]
Thanks a lot @brianchandotcom I was just about to update it.

**Comment by brianchandotcom** [comment]
I resent it to myself here https://github.com/brianchandotcom/liferay-portal/pull/27208

**Comment by adolfopa** [comment]
Thanks a lot @brianchandotcom

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9586f10d45...417f2f3c23

**Pull request closed without merging**
