### PR TITLE
LPS-151909 As a developer using headless endpoints, I'd like to update a country by countryId via partial update and full replace

### PR DESCRIPTION
**Pull request by epark18**
Manual forward from [liferay-usm#563](https://github.com/liferay-usm/liferay-portal/pull/563).

https://issues.liferay.com/browse/LPS-151909

Update to [brianchandotcom#117304](https://github.com/brianchandotcom/liferay-portal/pull/117304).

### CODE REVIEW

**Comment by epark18** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ef9ba9e67b...b732db2fe7

**Comment by brianchandotcom** [comment]
@epark18 @drewbrokke see 8049bb6df5c6ead40546f111e1ef4abe7228e983 89c4955ed4cc8b38e72adb7ebb6ec40e04792eb5 and b732db2fe71a121e6964de16d295ac296e385b17

Please validate that I didn't break anything with 89c4955ed4cc8b38e72adb7ebb6ec40e04792eb5 thx

**Comment by drewbrokke** [comment]
@brianchandotcom Should be fine, thanks!

**Pull request closed without merging**
