### PR TITLE
LPS-102711 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-102711

This is only for master.

@ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure case is a flaky issue
See https://github.com/liferay-echo/liferay-portal/pull/4421
✔️ ci:test:stable - 9 out of 9 jobs passed
❌ ci:test:relevant - 23 out of 28 jobs passed in 2 hours 30 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.

**Comment by brianchandotcom** [comment]
@ealonso 

1.) Can we deprecate or remove

modules/apps/site/site-admin-web/src/main/java/com/liferay/site/admin/web/internal/frontend/taglib/form/navigator/BaseSiteFormNavigatorEntry.java

2.) Type:

git ls-files **/sites_admin/**.jsp

We need to update those as well to the new pattern right?

3.) There seems to be more duplicate code now too. The JSPs and Edit*.java seem to have a lot of boiler plate code. Perhaps they can go in a Base class or some init JSPs

I merged this because this was a big pull and we can make progress cleaning this up after it's merged in.

**Pull request closed without merging**
