### PR TITLE
Lps 75859

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b5716be5ad...9e83024f56

**Comment by brianchandotcom** [comment]
@Preston-Crary can you figure out why we still have ServiceClp files? Thx.

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/53329

**Pull request closed without merging**
