### PR TITLE
LPS-74544

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@hhuijser I do want to format package.json though? So that things are sorted and tabbed properly. Not merging this in, please resend if I misunderstood?

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
@brianchandotcom, tabbing and sorting still happening. We only exclude package.json for single check.

**Comment by brianchandotcom** [comment]
Got it.. thx.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
