### PR TITLE
LPS-68988 Remove exceptions to avoid breaking the API for backward compatibility

### PR DESCRIPTION
**Pull request by pei-jung**
https://github.com/brianchandotcom/liferay-portal-ee/pull/15498

/cc @jorgediaz-lr @ZoltanTakacs

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:reopen

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@jorgediaz-lr @pei-jung not merging. I don't understand why we need to do this. Why would we have a backwards compat issue if baseline is not complaining? Please consult @rotty3000 and then send it back to me. Doesn't seem to make sense.

Thx

**Comment by jorgediaz-lr** [comment]
Hi @brianchandotcom 

I sent a pr with the backport of this LPS-68988 to ee-7.0.x but @ZoltanTakacs told me to not add new checked exceptions declared as thrown because it breaks contract compatibility, see: https://github.com/ZoltanTakacs/liferay-portal-ee/pull/2116#issuecomment-261545177

So I changed the code only for ee-7.0.x, maintaining unchanged the thrown clauses, see: https://github.com/brianchandotcom/liferay-portal-ee/pull/15498

In that pull request you asked to maintain the compatibility in master, so I was sending this pull request, reverting the API changes.

I don't know why baseline is not complaining but in my opinion, adding a new throws clauses in a method should be detected as a API change because we force to catch it to people that is using the method.

/cc @rotty3000 @migue @dsanz

**Comment by migue** [comment]
Hello guys,

Adding and deleting checked exceptions declared as thrown by an API method does not break binary compatibility, that's the reason why the semantic versioning tool does not complain. However, it breaks contract compatibility.

We shouldn't allow this kind of changes to be back ported nor to be added to the master branch of development if we want to be backwards compatible.

**Pull request closed without merging**
