### PR TITLE
Revert LRQA-32827, LRQA-32829, LRQA-32898, LRQA-32891, LRQA-33007, LRQA-33005, LRQA-33306, LRQA-33433, LRQA-33326, LRQA-33332, LRQA-33333 | master

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LRQA-33480

We decided to keep conditionals in our tests so that ee-7.0.x and master tests are more similar. As of right now, conditionals were only removed from the master tests and not the ee-7.0.x ones.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2f1d5c20c4...30aa8bf489

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:stop

**Comment by brianchiu** [comment]
wrong pull

**Comment by brianchiu** [comment]
ci:stop

**Pull request closed without merging**
