### PR TITLE
LPS-64674 service.ranking shouldn't be used for ordering navigation entries and categories

### PR DESCRIPTION
**Pull request by juliocamarero**
fyi @sergiogonzalez

Brian, we haven't found another way to use the existing comparators because they are in modules and this registry is in the core :(

We have made them private so that we can removed once this registry is extracted in the future.

thanks!

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9b4ca7335b...8e651df773

**Comment by brianchandotcom** [comment]
@juliocamarero see my documentation in 8e651df773fe8aa9ad577fba5369ca679b683cac

Thx

**Pull request closed without merging**
