### PR TITLE
LPS-101361 buildService

### PR DESCRIPTION
**Pull request by brunofarache**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.

**Comment by brianchandotcom** [comment]
@brunofarache I merged this ,but not a big fan of compileInclude of so many things.

**Comment by brunofarache** [comment]
@gabrielwas why are we using compileInclude in this case?

**Comment by gabrielwas** [comment]
@brunofarache We have Jsonpath being used in dynamic-data-mapping-data-provider-impl, and its library is included with compileInclude. I wondered if we could have a direct dependency to this library or if it is already inside bundle. So, I decided to keep the compileInclude. But I think we can change it to compileOnly.

**Pull request closed without merging**
