### PR TITLE
LPS-61347 Implement validateImportedStagedModel method for journal staging tests

### PR DESCRIPTION
**Pull request by matethurzo**
cc @juliocamarero

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
ci:retest

**Comment by juliocamarero** [comment]
:+1:

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8291e7244f...842b08a426

**Pull request closed without merging**
