### PR TITLE
LPS-75010 Petra StringPool collaboration

### PR DESCRIPTION
**Pull request by tomwang2011**
CC @shuyangzhou

Hi Brian, this is the resend of https://github.com/brianchandotcom/liferay-portal/pull/54140 after rebasing, please let the CI finish incase anything is broken, thanks!

### CODE REVIEW

**Comment by tomwang2011** [comment]
ci:test

**Comment by brianchandotcom** [comment]
ci:test

**Comment by tomwang2011** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@tomwang2011 please backport. Thx.

**Pull request closed without merging**
