### PR TITLE
LPS-73788 Extract the releaseResourceBlock to avoid creating a new transaction

### PR DESCRIPTION
**Pull request by inacionery**
/cc @topolik @lipusz @marcellustavares @vicnate5

### CODE REVIEW

**Comment by inacionery** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@inacionery this doesn't look right to me. I'm not sure annotations in private methods do anything.

@shuyangzhou, can you look at this and resend, or reopen it and let me know it's OK? Thx.

**Comment by shuyangzhou** [comment]
@inacionery this will break tx model of resourceblock, as the annotation is not doing anything, the only reason it fixes the issue is because you stopped launching a new tx.

For now we will try to migrate the usages back to standard resource permission. Once the usage is gone, the company deleting process won't have to delete anything for resource block. then the deadlock will go away.

**Comment by inacionery** [comment]
Hi @shuyangzhou, we already have an issue for this change? Because it's a dependency of a customer related issue (LPS-55244). Thanks!

/cc @lipusz

**Comment by shuyangzhou** [comment]
Without a proper tx model, all the resource block reference count will be broken under concurrent load.

**Comment by inacionery** [comment]
Hey @shuyangzhou, i understand that, but we have an issue to migrate the usages back to standard resource permission?

Thx!

**Comment by shuyangzhou** [comment]
an issue? what issue?

**Comment by shuyangzhou** [comment]
you meant ticket?

**Comment by inacionery** [comment]
Sorry, a ticket of jira.

**Comment by shuyangzhou** [comment]
no, we don't. We don't know for sure that's our best option yet, still investigating now.

**Pull request closed without merging**
