### PR TITLE
LPS-73803 Theme setting keys were updated but implementation was not

### PR DESCRIPTION
**Pull request by robframpton**
/cc @ealonso

### CODE REVIEW

**Comment by Robert-Frampton** [comment]
ci:reopen

**Comment by Robert-Frampton** [comment]
ci:retest

**Comment by Robert-Frampton** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d732fb365d...fc8c14bcb5

**Pull request closed without merging**
