### PR TITLE
LRQA-40635, LRQA-41421 | master

### PR DESCRIPTION
**Pull request by GinsonRen**
https://issues.liferay.com/browse/LRQA-41421
https://issues.liferay.com/browse/LRQA-40635

This is only for master. Thanks.

### CODE REVIEW

**Comment by GinsonRen** [comment]
ci:reopen

**Comment by JoyceWang08211** [comment]
The functional smoke failure is related to a regression occurred on startup, it has been fixed on master head.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@GinsonRen master and 7.1.x are still identical for now, so backporting.

**Pull request closed without merging**
