### PR TITLE
LRQA-34313 Add virtual.hosts.default.site.name property to have '/web/guest' in URL on virtual instances

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-34313

### CODE REVIEW

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/liferay-portal/pull/51928

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/275c9cd828...8f3296c2c8

**Comment by brianchandotcom** [comment]
@pyoo47 @pcwhite one minor change in 8f3296c2c83d3986a3633582f59a0c9e8c674643

Thx.

**Comment by pyoo47** [comment]
@anthony-chu FYI

**Pull request closed without merging**
