### PR TITLE
LPS-91442 Adding test cases for null object

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/78c94d9c84...50cf3287cc

**Comment by brianchandotcom** [comment]
@balazssk I merged this, but I want you to send me a follow up pull:

git ls-files ***ClassTypeReader**

Move all of them to *.asset.model.* from just *.asset.* since they all extend com.liferay.asset.kernel.model.BaseDDMStructureClassTypeReader

Thx!

**Comment by balazssk** [comment]
Thank you for the feedback @brianchandotcom ,

I've found that other classes from com.liferay.asset.kernel.model are also extended in just .asset packages.
Good examples are com.liferay.asset.kernel.model.BaseAssetRendererFactory<T> or com.liferay.asset.kernel.model.BaseAssetRenderer<T> having all of their subclasses are in .asset packages.
Should I also move all subclasses of com.liferay.asset.kernel.model classes?

**Comment by brianchandotcom** [comment]
@balazssk Yes, do it for those as well. But, you don't have to do them all at once.

Send me one PR for ClassTypeReader, another PR for *AssetRenderer* etc. Why? Continual improvement is good enough.

I havne't figured out how to filter out GH comments.. so I get flooded with them. Email or Skype is safer. Thx.

**Comment by brianchandotcom** [comment]
@zsoltbalogh fyi

**Comment by zsoltbalogh** [comment]
Thank you, @brianchandotcom! We ask support to reach out to you in e-mail if we have questions about a PR.

**Pull request closed without merging**
