### PR TITLE
LPS-82401 Fix JSP compilation

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @brianchandotcom, this provides a generic mechanism to address what we discussed in https://github.com/brianchandotcom/liferay-portal/pull/60235#issuecomment-397014632

We'd like to have this backported, but since it's a moderately complicated PR, we wanted to get it by you first. I'll take care of the backport and send it to `7.1.x` once this is processed.

**Comment by izaera** [comment]
ci:reopen

**Comment by izaera** [comment]
@jpince Can you please have a look at this? I'm trying to reproduce poshi failures locally and I don't see any error...

Thx :-).

/CC @jbalsas

**Comment by brianchandotcom** [comment]
@izaera @jbalsas I went ahead and merged this, and backported it to 7.1.x, and published the artifacts. So we're good. Thx guys

**Pull request closed without merging**
