### PR TITLE
[MOSTLY FEEDBACK - BUT MERGE AT WILL] LPS-90890 Clay taglib contributor

### PR DESCRIPTION
**Pull request by izaera**
Resend of https://github.com/brianchandotcom/liferay-portal/pull/68419

/CC @jbalsas

### CODE REVIEW

**Comment by izaera** [comment]
ci:test

**Comment by izaera** [comment]
Hey @john-co. Can you please have a look at the CI tests? I don't think they are related to the PR... 
Thx :-)

**Comment by john-co** [comment]
@izaera, the errors look unlreated to the PR.

**Comment by izaera** [comment]
Will resend

**Pull request closed without merging**
