### PR TITLE
LPS-77311 Create bundle and entity-type uad composites

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-77311](https://issues.liferay.com/browse/LPS-77311).<br><br>Hey Brian, this is a resend per your request here: https://github.com/brianchandotcom/liferay-portal/pull/54645#issuecomment-359967424.<br><br>/cc @pei-jung, @willnewbury, @noahsherrillwork

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by drewbrokke** [comment]
@alee8888 are these test failures related?

**Comment by drewbrokke** [comment]
@brianchandotcom I saw those failures in another pull: https://github.com/alee8888/liferay-portal/pull/532#issuecomment-360033488

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/733f294904...6efdeabcd8

**Pull request closed without merging**
