### PR TITLE
[READ DESCRIPTION] LPS-78253 Rename dropdownItems to items

### PR DESCRIPTION
**Pull request by carloslancha**
Due `DropdownGroupItem` utility is serialized to be passed to `clay` components we need this property to be named `items` to follow with the `clay-dropdown` external API.

```
active: bool,
disabled: bool,
icon: string,
items: list<[
  active: bool,
  disabled: bool,
  icon: string,
  label: string,
  type: string,
],
label: string,
type: string,
```

### CODE REVIEW

**Comment by carloslancha** [comment]
cc @jbalsas

**Comment by carloslancha** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@jbalsas we're forcing one standard to fit another standard. Eventually, there will be a conflict. Suppose you want to call something "default" but Java just won't allow it, then what? Does that mean we change Clay to fit Java?

The better way is to improve the annotations so that you can add hints and say this getter goes to this field. (i.e. use an annotation).

Can you resend with an annotation hint for the serializer? Thx.

**Comment by carloslancha** [comment]
resent -> https://github.com/brianchandotcom/liferay-portal/pull/55673

**Comment by jbalsas** [comment]
Hey @brianchandotcom, makes total sense, I personally wasn't aware of this pattern. It's definitely a very useful tool!

Thanks @carloslancha for sending it over!

**Pull request closed without merging**
