### PR TITLE
LRQA-32386 Use the command line to do git fetches instead of JGit

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-32386

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/924ba3c135...ceaa8c5a71

**Comment by brianchandotcom** [comment]
@pyoo47 published.

**Comment by pyoo47** [comment]
@michaelhashimoto I've pushed the new jar into liferay-jenkins-ee upstream.

**Comment by michaelhashimoto** [comment]
@pyoo47 - Thanks! :D

**Pull request closed without merging**
