### PR TITLE
Lps 67018

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by mtambara** [comment]
cc @mhan810

To overwrite a jar or war from any LPKG other than the Static LPKG, first create a folder named "overwritten" in the `osgi/marketplace` folder. Drop the the jar into this folder, making sure it's name is the same as a jar in the original LPKG minus the version info (i.e, if I want to overwrite `com.liferay.amazon.rankings.web-1.0.5.jar` from Liferay CE Amazon Rankings.lpkg, I would put a jar named `com.liferay.amazon.rankings.web.jar` into the `osgi/marketplace/overwritten`

Overwriting jars from the Static LPKG works the same way, but overwriting jars go into the `osgi/static` folder instead (i.e, if I want to overwrite `com.liferay.portal.profile-1.0.3.jar`, I would put a jar named `com.liferay.portal.profile.jar` into the `osgi/static` folder.

To undo these changes, simply delete the overwriting jar and the portal will use the original LPKG jar on next startup.

Note that adding and removing jars must be done while the portal is shut down. Changes will take place the next time the portal is started. 

Let me know if you have any additional questions.

**Comment by mhan810** [comment]
@rotty3000 FYI this should be the work around that would work for the ce issue?

**Comment by brianchandotcom** [comment]
@shuyangzhou lpkg-startup failure :( can you resend.

**Comment by mtambara** [comment]
Re-sent at https://github.com/brianchandotcom/liferay-portal/pull/41583

**Pull request closed without merging**
