### PR TITLE
LPS-86677 Write Baseline Asset List Staging Integration Tests

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
Thanks for this @kyle-miho!

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@kyle-miho, relaunching tests, just fyi

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c363574138...4692410ab0

**Pull request closed without merging**
