### PR TITLE
LPS-98874 Checks for the field defensively. Rich Text fields are governed by different rules and not subject to be disabled, so there's no need for this generalization

### PR DESCRIPTION
**Pull request by jbalsas**
/cc @antonio-ortega, @john-co

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
No unique failures/regressions based on CI results, and fixes original issue described in https://issues.liferay.com/browse/LPS-98874 :tada:

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5ab024bd7f...9b4dc34a96

**Pull request closed without merging**
