### PR TITLE
LPS-61457 fix missing checkboxes from osgi modules

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @jbalsas

**Comment by jbalsas** [comment]
:+1:

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/19faac7c0b...98dd523d7b

**Comment by brianchandotcom** [comment]
@juliocamarero see my changes 98dd523d7b915a008af060d2740d5f058ae5a9f5

**Pull request closed without merging**
