### PR TITLE
LPS-77161 Single Asset Publish - bookmarks example

### PR DESCRIPTION
**Pull request by matethurzo**
cc @sergiogonzalez

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test

**Comment by matethurzo** [comment]
@brianchandotcom the failures are unrelated

**Comment by brianchandotcom** [comment]
@jpince can you figure out what's going on with the frontend tests? Thx.

@pyoo47 how is this "greeen" if it has broken tests.

**Comment by brianchandotcom** [comment]
@matethurzo can you send a follow up pull to log the exception? In general, not printing anything is bad. Thx.

**Pull request closed without merging**
