### PR TITLE
LPS-71653 Add tests

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
cc @marcellustavares

**Comment by jpince** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a9b34f22b8...07969743c1

**Comment by jpince** [comment]
@leoadb see also https://github.com/liferay/liferay-portal/commit/dfa2eae8af1dbb1769326d9fe1cce7df8fe069af

**Pull request closed without merging**
