### PR TITLE
LPS-57533 Create jenkins-core module to patch JUnitResultArchiver to …

### PR DESCRIPTION
**Pull request by shuyangzhou**
…skip CheckPoint

### CODE REVIEW

**Comment by shuyangzhou** [comment]
Just a network failure, once check in ivy cache it won't happen again. Jenkins has very large dependencies.

**Comment by brianchandotcom** [comment]
@shuyangzhou is the portal web smoke test real? That test has been very stable otherwise.

**Comment by shuyangzhou** [comment]
It is not caused by this pull for sure. I only added a new module, which is not used anywhere yet. The only way it could affact the build is failing the compile because of ivy fetch failure.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1af01cb2d7...3a9ed9ff47

**Pull request closed without merging**
