### PR TITLE
LPS-65736 Update repository URLs

### PR DESCRIPTION
**Pull request by CAustin582**

### CODE REVIEW

**Comment by pyoo47** [comment]
No CI failure that I could see here. These failures appear to be valid.

**Comment by CAustin582** [comment]
@pyoo47 could we retest this? I just built it locally and had no issues during the deploy target.

**Comment by pyoo47** [comment]
sure ci:retest

**Comment by CAustin582** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pyoo47 that was weird? ci retest worked .

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/26f1a77747...c8eeb55162

**Comment by CAustin582** [comment]
It was failing due to a configuration problem with the new snapshots repository. @pyoo47 you can disregard the failure; it had nothing to do with the CI server.

**Pull request closed without merging**
