### PR TITLE
LPS-109280 The wrapper is already rendered by the original tag

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by pyoo47** [comment]
fetchCacheBranchFromGitHubDev

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/adeec361ec...dd80e038df

**Comment by brianchandotcom** [comment]
@ambrinchaudhary @4lejandrito see a9b3d44f13f1f90f364adb1350914c777281020a and https://issues.liferay.com/browse/LRDOCS-7667

**Pull request closed without merging**
