### PR TITLE
LPS-85301 Simplify template to prevent error statements in the console

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@petershin what's up with the Gradle tests? Please take a look. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/84fb665f57...14b6c2e034

**Comment by brianchandotcom** [comment]
@ruben-pulido backported for you.

**Comment by jpince** [comment]
@petershin I'll send you & Greg's team an email with a few more examples, it's failing intermittently

**Pull request closed without merging**
