### PR TITLE
LPD-21008 Frontend CX is not registered when deployed from workspace and only enabled via the Feature Flags UI in Instance Settings.

### PR DESCRIPTION
**Pull request by ethib137**
Resent from: https://github.com/brianchandotcom/liferay-portal/pull/148514

@brianchandotcom is this the change you're looking for?

@ethib137
@liferay-frontend

Original pull request comment:
https://liferay.atlassian.net/browse/LPD-21008

CompanyId is needed for instance scoped feature flags.

### CODE REVIEW

**Comment by ethib137** [comment]
ci:reopen

**Comment by izaera** [comment]
@ethib137 :ok_hand:

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b575003146...025add4314

**Comment by brianchandotcom** [comment]
@ethib137 Yes, this is safe now. See also 025add4314ff759b4c4dc258d2173f3c2bd0b092 for minor SF.

**Pull request closed without merging**
