### PR TITLE
LPS-54156 don't swallow exceptions

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by rotty3000** [comment]
Weird!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0343cef616...ec6c042542

**Comment by brianchandotcom** [comment]
Oh, you can ignore it, it was a plugins bug. We're in the middle of adding support of ensuring that  changes in core don't break plugins. Just fixed it and pushed it upstream.

**Pull request closed without merging**
