### PR TITLE
LPS-67289 Uses form navigator entry taglib for configuration views | master

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LPS-67289

@brianchandotcom 
This pull is coming from me because Patrick wanted it to go through QA first.

CC @pat270

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@brianchiu see 38bf387393814a3da565f2d7a018a42921317f6c from auto SF

**Comment by anthony-chu** [comment]
@brianwulbern @GinsonRen @liulukiwi

This resolves the Asset Publisher configuration iframe footer bug.

**Comment by brianchiu** [comment]
@brianchandotcom 
Got it. I missed that. Sorry.

**Pull request closed without merging**
