### PR TITLE
Revert "LPS-57482 keep java generated from JSPs by default"

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@mhan810 fyi, Ray reverted your commit to keep java generated code by default.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/80731ddec4...aa0de917e4

**Comment by brianchandotcom** [comment]
@rotty3000 wouldn't it be better to keep the compiled code by default? What's the disadvantage?

**Comment by rotty3000** [comment]
Files, the compilation produces many files at runtime!

Plus there's already a configuration option to enabled it.

See https://issues.liferay.com/browse/LPS-56866

On Tue, Aug 11, 2015 at 3:47 PM, Brian Chan <notifications@github.com>
wrote:

> @rotty3000 <https://github.com/rotty3000> wouldn't it be better to keep
> the compiled code by default? What's the disadvantage?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/29189#issuecomment-130041102>
> .
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by mhan810** [comment]
BC, since there’s a global setting for it then we can remove my change it’s
fine.



Cheers,



-m



*From:* Raymond Augé [mailto:notifications@github.com]
*Sent:* Tuesday, August 11, 2015 2:57 PM
*To:* brianchandotcom/liferay-portal <liferay-portal@noreply.github.com>
*Cc:* Michael Han <michael.han@liferay.com>
*Subject:* Re: [liferay-portal] Revert "LPS-57482 keep java generated from
JSPs by default" (#29189)



Files, the compilation produces many files at runtime!

Plus there's already a configuration option to enabled it.

See https://issues.liferay.com/browse/LPS-56866

On Tue, Aug 11, 2015 at 3:47 PM, Brian Chan <notifications@github.com>
wrote:

> @rotty3000 <https://github.com/rotty3000> wouldn't it be better to keep
> the compiled code by default? What's the disadvantage?
>
> —
> Reply to this email directly or view it on GitHub
> <
https://github.com/brianchandotcom/liferay-portal/pull/29189#issuecomment-130041102
>
> .
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
(@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
(@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

—
Reply to this email directly or view it on GitHub
<https://github.com/brianchandotcom/liferay-portal/pull/29189#issuecomment-130045111>
.

**Comment by brianchandotcom** [comment]
Got it.. @rotty3000 

@mhan810 see https://issues.liferay.com/browse/LPS-56866 for Ray's explanation. Thx.

**Pull request closed without merging**
