### PR TITLE
LPS-64383 TEMP GRADLE CACHE

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by marcellustavares** [comment]
thanks @rotty3000! cc @leoadb

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/be2bcfdb4a...04ee171a05

**Comment by brianchandotcom** [comment]
@rotty3000 @marcellustavares we never update build.gradle with micro versions because those are provided jars, so it a micro version wouldn't make a difference.

**Comment by rotty3000** [comment]
Somewhere here things got messed up because somehow the last micro release
had MINOR changes. Without updating the reference compilation will fail.

On Tue, Mar 29, 2016 at 1:24 PM, Brian Chan <notifications@github.com>
wrote:

> @rotty3000 <https://github.com/rotty3000> @marcellustavares
> <https://github.com/marcellustavares> we never update build.gradle with
> micro versions because those are provided jars, so it a micro version
> wouldn't make a difference.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/38257#issuecomment-203010224>
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by xbrianlee** [comment]
Hey @brianchandotcom,  I'm getting compile errors at b83c10950f98510d8b012c499d5c3efa8b770f13, I believe, due to this pull. See my error log [here].(https://gist.github.com/xbrianlee/31ad6df75e6294007b49762ff0c11a5c).

**Comment by rotty3000** [comment]
yes it's for exactly the reason I explained above.

On Tue, Mar 29, 2016 at 2:42 PM, Brian Lee <notifications@github.com> wrote:

> Hey @brianchandotcom <https://github.com/brianchandotcom>, I'm getting
> compile errors at b83c109
> <https://github.com/brianchandotcom/liferay-portal/commit/b83c10950f98510d8b012c499d5c3efa8b770f13>,
> I believe, due to this pull. See my error log [here].(
> https://gist.github.com/xbrianlee/31ad6df75e6294007b49762ff0c11a5c).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/38257#issuecomment-203043800>
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Pull request closed without merging**
