### PR TITLE
LPS-76298 instanceId is 12 characters and Long.MAX_VALUE is 19 characters

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@mbowerman a test would be nice for this.. merging.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/59a5d01294...55bbeafe26

**Comment by brianchandotcom** [comment]
@mbowerman see f66ebfae2ac35a4d01db8c4acd954de088f9fc57

**Comment by mbowerman** [comment]
@brianchandotcom Please see https://ideone.com/j6rDQb, the parentheses affects the order of operations unless if ideone is using a different version of Java than Liferay uses.

Also, if it is true that the parentheses aren't doing anything, then we should change all the +'s to -'s, rather than simply removing the parentheses.

**Pull request closed without merging**
