### PR TITLE
LRCI-2973 Enable downstream builds for plugins jobs

### PR DESCRIPTION
**Pull request by michaelhashimoto**
http://issues.liferay.com/browse/LRCI-2973

@brianchandotcom - If this looks good can this be backported to `7.3.x`, `7.2.x`, `7.1.x`, `7.0.x`, `ee-6.2.x`, `ee-6.2.10`, `ee-6.1.x`, & `ee-6.1.30`?

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:reopen

**Comment by michaelhashimoto** [comment]
This should be fine to merge, it was only failing due to the licensing issue:
https://github.com/michaelhashimoto/liferay-portal/pull/2314

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/19bcb0dbf5...a8aef96e42

**Comment by brianchandotcom** [comment]
@michaelhashimoto backported all the way to ee-6.1.30

**Pull request closed without merging**
