### PR TITLE
LPS-66431 Support multiple root directories

### PR DESCRIPTION
**Pull request by Ithildir**
cc @david-truong and @gamerson

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@Ithildir published a new jar @david-truong @gamerson

**Comment by gamerson** [comment]
@Ithildir how does this feature work in practice, having multiple root directories?

**Comment by Ithildir** [comment]
You can enter a comma-delimited list of paths (relative to the workspace root dir) in the `liferay.workspace.modules.dir`, `liferay.workspace.plugins.sdk.dir` and `liferay.workspace.themes.dir` properties.

**Pull request closed without merging**
