### PR TITLE
LPS-69244 Enable Gatekeeper for my-subscriptions-web

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
@pyoo47 what is this failure?

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
@shuyangzhou We had a bug in our jenkins-ee code that got merged a little while ago. We've reverted it for now so my retest should work.

**Comment by shuyangzhou** [comment]
@slnn I already pushed up the benchmark side change to blacklist my subscriptions, you should see the regression have been fixed, please recheck. Thanks!

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
