### PR TITLE
LPS-104364 SF

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d55f965826...1adc11143e

**Comment by brianchandotcom** [comment]
@adolfopa can you rename getHref?

This is the first instance of this in any *DisplayContext.java

git grep "String getHref" **DisplayContext.java

This returns a few more

git grep "String getHref" **.java

But I still think you should follow existing patterns where possible.

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/80911

**Pull request closed without merging**
