### PR TITLE
LPS-83966 SF

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test

**Comment by julien** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a80398a469...7e639dcb0c

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/72789

**Pull request closed without merging**
