### PR TITLE
LPS-72021 Remove redundant unbind methods

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by jpince** [comment]
@ambrinchaudhary this looks like it might be related to one of your [changes](https://github.com/brianchandotcom/liferay-portal/pull/50166/files#diff-3cbaa64d0c9437572c43e42e6e0925f7R23) in knowledge-base-item-selector-web?
`     [exec] org.gradle.api.GradleException: Could not copy MANIFEST.MF to '/opt/dev/projects/github/liferay-portal/modules/apps/knowledge-base/knowledge-base-item-selector-web/build/tmp/jar/MANIFEST.MF'.`

cc/ @Ithildir

Closing this pull for now.

**Comment by jpince** [comment]
ci:close

**Comment by Ithildir** [comment]
I think this is the error Bnd is complaining about:
```
[In component class com.liferay.knowledge.base.item.selector.web.internal.KBAttachmentItemSelectorView, reference DLMimeTypeDisplayContext is dynamic but has no unbind method.]
```

**Comment by jpince** [comment]
Thanks @Ithildir :)

**Comment by ambrinchaudhary** [comment]
Thanks @Ithildir, I think the last commit was the one causing the failure. I removed it and sent again the PR: https://github.com/brianchandotcom/liferay-portal/pull/50190

**Pull request closed without merging**
