### PR TITLE
LPS-61820 PortletConfigurationIconLocator for MVCCommand and backwards compatibility

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @ealonso @robertoDiaz

**Comment by brianchandotcom** [comment]
We may have a dead server that's causing all this outage/slowness.. Sam Tran is looking into it.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
@brianchandotcom @sergiogonzalez 

These tests seemed to fail due to a firefox issue.  I think when we reset jenkins the firefox didn't install correctly.

See these 2 offline nodes for more details:
* https://test-1-10.liferay.com/computer/cloud-10-0-19-171/
* https://test-1-10.liferay.com/computer/cloud-10-0-19-173/

**Comment by brianchandotcom** [comment]
ci:retest @michaelhashimoto please coordinate with Brandon to fix.

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d61cc18e90...09f505f4d3

**Comment by brianchandotcom** [comment]
@sergiogonzalez quite nice. Any way to "test" it? to ensure all of them are constantly run? Thx.

**Comment by sergiogonzalez** [comment]
I'll take a look at it and let you know @brianchandotcom

**Pull request closed without merging**
