### PR TITLE
LPS-181918 Support default value

### PR DESCRIPTION
**Pull request by achaparro**
Hi @sofiamendozalr @luisortiz89,

Please check my changes. I simplified the code a bit and after that I think makes sense to use columnDef [here](https://github.com/brianchandotcom/liferay-portal/pull/136541/commits/39e96006d4427224d5101d1d8abc206813dd0fc8#diff-05477ecd6375c26fe1c6967cbe1a06891296f77f6cf8ed5d3b81e2557c277924R112) since it is what the DatabaseMetadata returns but I am not totally confident about what Brian will do.

On the other hand, @sofiamendozalr is there any reason to not add Hypersonic tests? We do not support upgrades with Hypersonic but maybe this API can be used in another context. This is not relevant but I just wanted to know.

Thanks!

### CODE REVIEW

**Comment by sofiamendozalr** [comment]
Hi @achaparro, I checked all the changes, thank you!

From my side, I did not add Hypersonic tests because when we talked about unit tests, I understood it was not necessary for this database, but I can add it.

**Comment by achaparro** [comment]
@sofiamendozalr It is true that we do not support upgrades for Hypersonic but, since the check default value is not strictly tied to upgrades and we already have Unit tests for this DB, we can add tests for it too.

Anyway, this is far less important that the current LPSs related to the virtual instance migration tool you are working on, so just keep it in mind to implement it when you finish with that.

Thanks.

**Comment by sofiamendozalr** [comment]
@achaparro Okay, I will do it after the other tickets. Thank you!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ff71a088b0...78b0cdbe2c

**Pull request closed without merging**
