### PR TITLE
LPS-58100 use portletInstance with shared plid for embedded portlets

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@juliocamarero @jkappler 

Please resend. Jorge added a new PortletInstance class.

It has portletInstanceKey, portletName, and instanceId.

Adding "portletInstanceId" is confusing because I'm confused as to it means in contrast to our existing vars.

Please resend. Thx. 

cc @jorgeferrer

**Comment by JorgeFerrer** [comment]
Agreed, it should be renamed.

**Pull request closed without merging**
