### PR TITLE
Lps 75075

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/82faff4ea5...4b43e87b3b

**Comment by brianchandotcom** [comment]
@shuyangzhou safe to publish? Please skype me if so. Thx.

**Pull request closed without merging**
