### PR TITLE
LPS-86795 Fix Clay design inconsistencies in screen navigation taglib

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/75a632c2b1...4e59cc776f

**Comment by stsquared99** [comment]
FYI @marco-leo

**Comment by marco-leo** [comment]
@stsquared99 Can we backport to 7.1.x?

**Comment by stsquared99** [comment]
@marco-leo Yep, I am taking care of it immediately

**Comment by marco-leo** [comment]
@stsquared99 Thanks!

**Pull request closed without merging**
