### PR TITLE
LPS-171226 When select a object that has a relationship with another object, and we go to the layout of that other related object and come back, the context is lost

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
ORIGINAL PR : https://github.com/liferay-objects/liferay-portal/pull/1570
LPS : https://issues.liferay.com/browse/LPS-171226

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:reopen

**Comment by naraandrade** [comment]
ci:close

**Comment by p-albuquerque** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/463887070c...ac2b1239e4

**Pull request closed without merging**
