### PR TITLE
LPS-63052 session should always be the portal one

### PR DESCRIPTION
**Pull request by juliocamarero**
Hey @rotty3000 @migue 

this change seems to fix the issues with the multi session messages! :D

could you please have a look? 

thank you!

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@shuyangzhou fyi

Good job @juliocamarero  :)

**Comment by brianchandotcom** [comment]
@juliocamarero what about SessionErrors?

**Comment by brianchandotcom** [comment]
@juliocamarero can you resend this with SessionErrors as well? Make sure it works there too. Thx.

**Comment by juliocamarero** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/36072

**Pull request closed without merging**
