### PR TITLE
[7.4.x only] LRQA-62801, LRQA-62830, LRQA-62834, LRQA-62836 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRQA-62801
https://issues.liferay.com/browse/LRQA-62830
https://issues.liferay.com/browse/LRQA-62834
https://issues.liferay.com/browse/LRQA-62836

This is only for master.

@david-gutierrez-mesa

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure cases is caused by https://issues.liferay.com/browse/LPS-123172
See https://github.com/Tim-Cao/liferay-portal/pull/504
✔️ ci:test:stable - 2 out of 2 jobs passed
❌ ci:test:relevant - 4 out of 6 jobs passed in 1 hour 31 minutes

**Comment by brianchandotcom** [comment]
@Tim-Cao master only.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1ae283de04...c9cde442a7

**Pull request closed without merging**
