### PR TITLE
Lps 72687

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@marcellustavares @leoadb fyi

**Comment by brianchandotcom** [comment]
@ealonso fyi as well.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/051f0ae8a0...0c86b08f45

**Comment by brianchandotcom** [comment]
@tomwang2011 does it have to be last in AggregrateTestRule? Also, can you backport? Thx.

@hhuijser can we SF enforce to force ppl to use the new class instead of the duplicate code? Thx.

**Comment by tomwang2011** [comment]
@brianchandotcom I put this test rule last so that it will be applied to the test last, which would be the same as the original logic and known to not have any errors, thanks!

**Pull request closed without merging**
