### PR TITLE
LPS-81792 Custom Facet Portlet configured with non-keyword field crashes all portlets in Search Page

### PR DESCRIPTION
**Pull request by arboliveira**
CI stable: 3 "Failures unique to this pull", all false negatives.
https://github.com/arboliveira/liferay-portal/pull/537#issuecomment-403139868

* `ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 104`

* `Could not GET 'http://repository.liferay.com/nexus/service/local/repo_groups/private/content/com/liferay/com.51degrees.dat.test/3.2/com.51degrees.dat.test-3.2.gz'. Received status code 502 from server: Bad Gateway`

* `message-boards-api` `Semantic versioning is incorrect`

Unrelated `ci test relevant` failure in this pull.  (JavaScript test failure in `frontend-editor-alloyeditor-web`)

@xbrianlee FP5 for 7.1-FP1.

Author: @brandizzi 
Reviewer: @arboliveira

https://issues.liferay.com/browse/LPS-81792

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:reopen

**Comment by arboliveira** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@arboliveira see 6ad5c59 thx.

**Pull request closed without merging**
