### PR TITLE
LPS-62710 Build Lang

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/03610a7dd6...5491642939

**Comment by brianchandotcom** [comment]
@jorgeferrer When we split repos, we're going to need @jhinkey to either proactively or reactively review language keys. It's not the fault of @inacionery since English is not his native language, but when Americans see bad grammar, it makes the product look bad.

I rephrased:

There is not form yet. Click on blue plus button to add the first one!

to

There are no forms. Click on the plus button to add the first one.

**Comment by marcellustavares** [comment]
Thanks @brianchandotcom, I think there was communication failure between Jadson and Russel.

He has being reviewing all our lang keys but I think we missed this.

Regards

**Comment by JorgeFerrer** [comment]
Hey @brianchandotcom,

I would propose using the process followed by Screens, where in order to merge a pull there needs to be an approval (+1) by the team's technical writer if there are any language keys or documentation. This requires a different way of doing pulls than what we do in portal so that several people can review a pull at once though.

**Pull request closed without merging**
