### PR TITLE
LPS-71636 SF - Simplify control flow

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
cc/ @adolfopa

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pyoo47 what's wrong with NPM? @ithildir ?

**Comment by Ithildir** [comment]
It looks like a problem with the NPM mirror... @stsquared99, do you notice any issue?

**Comment by brianchandotcom** [comment]
@stsquared99 is out for one more week.

Anything we can do in the meantime?

**Comment by Ithildir** [comment]
I'll try to disable it just for `dynamic-data-mapping`, I don't think it's really needed.

**Comment by pyoo47** [comment]
I don't know if disabling it for dynamic data mapping will do it.. I'm guessing that's just the first one it hit.

```
     [exec] npm ERR! <blockquote id="error">
     [exec] npm ERR! <p><b>Connection to 172.16.168.221 failed.</b></p>
     [exec] npm ERR! </blockquote>
```

**Comment by Ithildir** [comment]
But those modules use a different approach, most of the other ones already have their `node_modules` dir cached.

**Comment by jpince** [comment]
it fails on `foundation/frontend-js` in ee-7.0.x. If we approach it this way, we may end up chasing modules all day?

**Comment by pyoo47** [comment]
I was able to contact Sam P. He's looking into the outage right now.

**Comment by Ithildir** [comment]
In the meantime, I sent https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/156 to fix it there. @brianchandotcom, I tried to push those 2 commits directly, but I'm not authorized to do it.

**Comment by pyoo47** [comment]
ci:retest - Sam P. got the NPM Sinopia service back up.

**Comment by pyoo47** [comment]
ci:retest - NPM server went down again but it's fixed now.

**Comment by brianchandotcom** [comment]
@robertoDiaz service builder issue looks unique to this pull, please resend. Thx.

**Pull request closed without merging**
