### PR TITLE
LPS-58993 Add missing clean up

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
CC: @robertoDiaz, @sergiogonzalez

**Comment by sergiogonzalez** [comment]
thx @jkappler!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/311f08a406...2142021f4e

**Comment by brianchandotcom** [comment]
Good job catching it.

**Pull request closed without merging**
