### PR TITLE
master-bc-782

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LRQA-18113
https://issues.liferay.com/browse/LRQA-18111
https://issues.liferay.com/browse/LRQA-17905
https://issues.liferay.com/browse/LRQA-17904

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b16986e823...1a6d19b3a6

**Comment by jhendley** [comment]
@ZoltanTakacs
Please merge into 7.0.x - This can be merged in even before alpha. Thanks.

**Comment by ZoltanTakacs** [comment]
@jhendley, I'm OoO right now. I will be able to do this on Monday at the earliest. /Sent from mobile

**Comment by jhendley** [comment]
No problem. Thanks.

On Fri, Sep 25, 2015 at 9:45 AM, Zoltán Takács <notifications@github.com>
wrote:

> @jhendley <https://github.com/jhendley>, I'm OoO right now. I will be
> able to do this on Monday at the earliest. /Sent from mobile
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/30528#issuecomment-143274857>
> .
>



-- 
Joel Hendley
Director of QA
@jhendley <https://twitter.com/jhendley>

<http://liferay.com/>
Enterprise. Open Source. For Life
Web <http://www.liferay.com/> | Facebook <http://facebook.com/liferay> |
Twitter <http://twitter.com/liferay>

**Pull request closed without merging**
