### PR TITLE
LPS-64822

### PR DESCRIPTION
**Pull request by topolik**
Hi Brian,

https://issues.liferay.com/browse/LPS-64822

Thank you.

/cc @martamedio

### CODE REVIEW

**Comment by topolik** [comment]
ci:reopen CI Failure

**Comment by jpince** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@joshchong @xbrianlee can you keep an eye on these results? I don't think it'll fail, but just in case

**Comment by pyoo47** [comment]
I found this in the console log. Not sure if it's an upstream issue or not.
```
     [exec] src/main/resources/META-INF/resources/js/AutoField.soy.js -> classes/META-INF/resources/js/AutoField.soy.js
     [exec] SyntaxError: src/main/resources/META-INF/resources/js/CategorySelector.soy.js: Unterminated string constant (64:10)
     [exec]   62 |   $render.soyTemplateName = 'com.liferay.asset.list.web.CategorySelector.render';
     [exec]   63 | }
     [exec] > 64 | tor.render';
     [exec]      |           ^
     [exec]   65 | }
     [exec]   66 | 
     [exec]   67 | exports.render.params = ["index","namespace"];
     [exec] npm ERR! code ELIFECYCLE
     [exec] npm ERR! errno 1
     [exec] npm ERR! asset-publisher-web@3.0.0 compile: `cross-env NODE_ENV=production babel --source-maps -d classes/META-INF/resources src/main/resources/META-INF/resources`
     [exec] npm ERR! Exit status 1
     [exec] npm ERR! 
     [exec] npm ERR! Failed at the asset-publisher-web@3.0.0 compile script.
     [exec] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d84f34f83e...bb6b69e770

**Pull request closed without merging**
