### PR TITLE
LPS-69599

### PR DESCRIPTION
**Pull request by Preston-Crary**
cc @blzaugg

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:retest

**Comment by jonmak08** [comment]
ci:reopen

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/54715e1909...ac4905c1b3

**Comment by brianchandotcom** [comment]
@Preston-Crary @jonmak08 please see my changes in upstream. Thx.

**Pull request closed without merging**
