### PR TITLE
master-qa-21547

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-21547

### CODE REVIEW

**Comment by kenjiheigel** [comment]
@brianchandotcom @brianchiu @jpince, I happened to check my pull just now and realized I caused some tests to fail before I left. It was a quick fix, so it should fix the two failing calendar tests that fail in the PR tests: 

Calendar#ViewCalendarTimeZoneDefaults
WorkflowCalendar#ApproveEventWithInvitedUser

Sorry about this!

**Comment by vicnate5** [comment]
Test failure on this pull is unrelated.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/454c273417...ad1eedbb60

**Comment by brianchandotcom** [comment]
@kenjiheigel   I've given you push rights. In the future, if you catch something like this at night, it's better for you to just push it up, that way, all of my pulls the next day won't have those same errors.

Thx bro.

**Comment by kenjiheigel** [comment]
Thanks @brianchandotcom

**Pull request closed without merging**
