### PR TITLE
Lps 81336

### PR DESCRIPTION
**Pull request by shuyangzhou**
@mhan810

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Hey @shuyangzhou 

I'd like to generate this. "externalReferenceCode" sounds very very similar to uuid. I can see us one day wanting this for many more every service.xml entities.

Can you talk to @Preston-Crary

I'd like to add a new ServiceBuilder attribute called "external-reference-code=true/false"

We used to have an upgrade class that made it very easy to add the uuid column to certain tables. Let's do the same thing for externalReferenceCode. That code may only be in 6.2.x since it may have been removed for 7.0.x.

Add this new column after uuid and uuid-accessor in ServiceBuilder.

Auto generate the fetch by method (assume it's always namespaced by companyId)

We'll leave the upsert as manual.. but send those in a separate pull/commit.

Thx

fyi @mhan810

**Comment by shuyangzhou** [comment]
Yes, we could switch from manual to generate after release. The output binary should be the same.
@brianchandotcom can we bring this in as it is? We can make the SB change for this later.

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@mhan810 I talked to @shuyangzhou and he's going to resend it to me before Tuesday...

**Pull request closed without merging**
