### PR TITLE
LPS-102664 | LPS-105732 Bump

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/da96d214f2...82b0068198

**Comment by brianchandotcom** [comment]
@rafaprax @inacionery thanks for this pull.

This pull contains a "regen" in commit in https://github.com/brianchandotcom/liferay-portal/pull/83385/commits/11ed32955d09be0ade50d6cd827036e10c64223b

But it was not truly a regen commit. See 855d059812148377e0eb023a691f8e8f7549eca9 in my origin that split that manually modified file out of the regen commit.

Also fixed a typo in 174c7331ea98412e2a7beb64fbd89fc4d7f2ac37

Other than that, very good feature. Thx guys.

**Comment by inacionery** [comment]
@brianchandotcom thanks a lot!! Sorry for "regen" I missed it.

**Comment by rafaprax** [comment]
@brianchandotcom My bad. Sorry.

**Pull request closed without merging**
