### PR TITLE
LPS-74532 Setting virtual host fields as Varchar(200)

### PR DESCRIPTION
**Pull request by achaparro**
cc/ @jcampoy

### CODE REVIEW

**Comment by achaparro** [comment]
Tests seem unrelated.

**Comment by achaparro** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by achaparro** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/13452e2048...b0ab47f7b1

**Pull request closed without merging**
