### PR TITLE
Lps 63730

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @csierra

### CODE REVIEW

**Comment by csierra** [comment]
I would have preferred that you had not reverted all the previous commits. Your change is really small and is just changing the locks for synchronize blocks. Looking at this pull looks like the previous structure of the code was wrong, while it is indeed preserved.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/440d173e1f...4ee399f7b3

**Comment by shuyangzhou** [comment]
Sorry, @csierra revert does not necessarily mean they are wrong. Just for the sake of clean history.

When someone goes back to review history of this piece, he/she would prefer to see the net changes from one point to another point, other than the middle changes. Before you started your changes, after my reverts, that's one section, it has 0 net change. One can easily see that. Then the next section is my changes that starting from scratch, not on top of your changes, easier to focus on what is really changing.

**Comment by brianchandotcom** [comment]
@shuyangzhou this doesn't compile..

```
				serviceRegistrar.registerService(
					Portlet.class, this,
					Collections.singletonMap(
						"javax.portlet.name", getPortletName()));
```

Also, you need to update registry-api to 1.1.0

Please resend? Thx.

**Comment by shuyangzhou** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/38877, that's a jdk8 vs jdk7 generic capture difference.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4ee399f7b3...4ee399f7b3

**Pull request closed without merging**
