### PR TITLE
LPS-99064 Content Pages not being included in sitemap

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
Thanks for this one @jgarcialr!

**Comment by jkappler** [comment]
CI:reopen

**Comment by jkappler** [comment]
@kyle-miho, this is weird

**Comment by jkappler** [comment]
CI:reopen

**Comment by jkappler** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/07a244fd83...c0901bd8fc

**Comment by brianchandotcom** [comment]
@jkappler I backported this.. we had a CI issue..

**Comment by jkappler** [comment]
thanks @brianchandotcom!

**Pull request closed without merging**
