### PR TITLE
LPS-196306: Tags and Categories are not linked when adding Account Nested objects via API

### PR DESCRIPTION
**Pull request by ccorreagg**
Forwarded manually from: https://github.com/liferay-headless/liferay-portal/pull/1539

cc/ @sergiojimcos

---

**What is new?**
- Create ServiceContextUtil in order to reuse it in the `ObjectRelationshipExtensionProvider` and `DefaultObjectEntryManager`.
- Update `_getDefaultDTOConverterContext` in order to set the userId, this ie because the keywords properties is going to be added depending from the value of the userId from the `DTOConverterContext` that is going to be injected in the `ObjectRelationshipExtensionProvider`

**How to test this**
1. Create one new object: “Sample” with a field “sampleField” and enable categorization for this Object.
2. Create one Vocabulary with one Category (ID=12345 as example)
3. Create relationship Account ← 1:n (oneToMany) → Sample. Relationship named “accountSamples”
4. Access the headless-commerce-admin-account API:/o/api/?endpoint=http://localhost:8080/o/headless-commerce-admin-account/v1.0/openapi.json
5. Execute this payload:

```json
{
    "active": true,
    "externalReferenceCode": "TEST01",
    "name": "TEST01",
    "root": true,
    "type": 2,
    "accountSamples": [
      {
        "externalReferenceCode": "SAMPLE01",
        "name": "SAMPLE01",
        "sampleField": "A value 01"
        "taxonomyCategoryIds": [12345],
        "keywords": ["tag example"]
      }
    ]
  }

```
**JIRA Related TIcket**
https://liferay.atlassian.net/browse/LPS-196306 

cc/ @sergiojimcos

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:reopen

**Comment by ccorreagg** [comment]
ci:close

**Comment by ccorreagg** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7c90f35712...988f1c9a68

**Pull request closed without merging**
