### PR TITLE
LPS-114731 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-114731

This is only for master.

@JorgeFerrer
@jkappler

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure cases are caused by ci issue.
See https://github.com/liferay-echo/liferay-portal/pull/1766
✔️ ci:test:stable - 21 out of 21 jobs passed
❌ ci:test:relevant - 92 out of 95 jobs passed in 2 hours 33 minutes

**Comment by jkappler** [comment]
@4lejandrito, thanks for your help with this LPS!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7cd5bc56be...45f2eaa22f

**Comment by brianchandotcom** [comment]
Thx @Tim-Cao 

@jkappler @4lejandrito please see my changes

**Pull request closed without merging**
