### PR TITLE
LPS-89415 This try-catch is no longer needed

### PR DESCRIPTION
**Pull request by alejandrohdezma**

### CODE REVIEW

**Comment by ahdezma** [comment]
ci:close

**Comment by brianchandotcom** [comment]
@ahdezma I"m already reviewing this right now.. are you going to send me a new pull? if not, I"ll cherry pick whatever I can from this pull.

**Comment by brianchandotcom** [comment]
@ahdezma just read this https://www.baeldung.com/java-constructors-vs-static-factory-methods to understand why you went with .of( vs. constructor. Looks good to me.

**Comment by brianchandotcom** [comment]
@ahdezma I merged in most of this pull 

See 6b027bfad159e1e57f431ea9dbc7e5d5c7a05867 to bcbc566c5308b41e54b8c0ebb47c329070483487

I don't see the value in 64596cd9340057bcf3076014dc1c479d5c4c15ba

I find the "transform" method less verbose, and performance wise, should be the same since this the implementation of TransformUtil.

```
		Stream<T> stream = list.stream();

		return stream.map(
			transformFunction
		).collect(
			Collectors.toList()
		);
```

**Pull request closed without merging**
