### PR TITLE
LPS-96546 locale

### PR DESCRIPTION
**Pull request by javiergamarra**
Thanks Preston-Crary for helping avoid more dependencies :)

Will break with #74337, I'll rebase it as needed :D

-- baseline

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1f55525193...b22a6208ce

**Comment by nhpatt** [comment]
Thanks! :D

**Comment by brianchandotcom** [comment]
@nhpatt backported all the way to 7.1.x as well. Thank you!

**Comment by nhpatt** [comment]
Thanks! :)

**Pull request closed without merging**
