### PR TITLE
COMMERCE-299

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
https://issues.liferay.com/browse/COMMERCE-299

Hi Brian,

I've modified the variables name as per the suggestion in https://github.com/brianchandotcom/liferay-portal/pull/56141#issuecomment-373958598

Also checked the JSON files with https://github.com/dzhibas/SublimePrettyJson but they were already prettified so it didn't modify anything in them.

Should anything need to be changed / modified, please let me know.

Thank you!
Zoli

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/24e3829486...03a359a24e

**Comment by brianchandotcom** [comment]
@ZoltanTakacs merged, please see my changes in upstream.

1.) Also, can you change  *.png that uses dashes to use underscore? So x-y.png should be x_y.png in your module. Unless, Talend doesn't allow it.

2.) JSONLDConstants should be in *.constants.*. Same with HydraConstants.

3.) Should RestClient by RESTClient?

4.) Can you rename the methods in ApioResponse

so that if it returns a JsonNode, that the method names are get*JsonNode?

Same with ApioResourceCollection*getNode should be *getJsonNode.

In fact, check for all your uses of get*Node

5.) Can you sort the toString  in ApioException so the attributes are always sorted.

Thx!

**Comment by ZoltanTakacs** [comment]
Thanks for the suggestions!

Follow-up PR: https://github.com/brianchandotcom/liferay-portal/pull/56368

Thank you,
Zoli

**Pull request closed without merging**
