### PR TITLE
LPS-134343 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-134343

This is only for master.

@ruben-pulido

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure cases are unrelated to changes in this PR.
See https://github.com/liferay-echo/liferay-portal/pull/5034
✔️ ci:test:stable - 9 out of 9 jobs passed
❌ ci:test:relevant - 21 out of 24 jobs passed in 1 hour 31 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/879e5ea59f...8215f0ece6

**Comment by brianchandotcom** [comment]
@ruben-pulido minor changes in 8215f0ece6273e311fa8d40bda9427d0b0dd994d

**Pull request closed without merging**
