### PR TITLE
Lps 81528

### PR DESCRIPTION
**Pull request by shuyangzhou**
@ngriffin7a I removed the null -> new String[0] conversion here https://github.com/brianchandotcom/liferay-portal/commit/48fe6b74a5ce7bb869ebd89cb90cf8bd3a68d53d

If it does break some tck tests, please let me know, we can dig into it. In the mean while, I made many changes, it will be better to run through the tck test suite on your side to make sure I did not break anything. 

We still have time before flipping on portlet 3 support to public, so just let it baking through master.

### CODE REVIEW

**Comment by ngriffin7a** [comment]
ci:reopen

**Comment by ngriffin7a** [comment]
ci:test:relevant

**Comment by ngriffin7a** [comment]
@brianchandotcom "This pull contains no unique failures."

**Comment by brianchandotcom** [comment]
@ngriffin7a can you resend, we usually don't call abstract classes *Base, we usually call the Base*

See how abstract class BaseModelHintsImpl implements ModelHints

The *Impl part is optional

Compare with BaseImporter imlements Importer

In any case, please resend. Thx.

**Comment by ngriffin7a** [comment]
@brianchandotcom I renamed the classes as you requested and sent a follow-up PR: https://github.com/brianchandotcom/liferay-portal/pull/61362

**Pull request closed without merging**
