### PR TITLE
LRQA-40608 GitWorkingDirectory.getRemotes() sometimes throws false IllegalArgumentExceptions

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-40608

Please publish after merging

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@pyoo47 what happened with that flake Tomcat?

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
