### PR TITLE
LPS-81954 Use new method to take in account selected site navigation menu type

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
cc @ealonso

**Comment by pavel-savinov** [comment]
c:reopen

**Comment by pavel-savinov** [comment]
c:reopen

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by jpince** [comment]
@brianchiu @anthony-chu not sure if this failure is related `NavigationMenu#EditNavigationMenuPageItemName`

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchiu** [comment]
@jpince 
That failure shows up in other places. It's a test fix, thankfully.

**Pull request closed without merging**
