### PR TITLE
LPS-98327 Force secondary button color here to avoid control menu styles usage

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
ci:test:stable

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/da2c662ac8...5037a97d52

**Comment by brianchandotcom** [comment]
@pavel-savinov see 5037a97

**Pull request closed without merging**
