### PR TITLE
LPS-69814 Restrict upload based on extensions in item selector

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @ambrinchaudhary

**Comment by sergiogonzalez** [comment]
cc/ @jbalsas

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@pavel-savinov @sergiogonzalez please see my changes in upstream.

Also, why call it "validExtensions" in some places and "extensions" in other places?

We should be consistent.

Please see upstream and send a follow up pull if necessary. Thx.

**Pull request closed without merging**
