### PR TITLE
LPS-51039 remove runtime sass parsing

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/12c0ecb124...2ad9447f14

**Pull request closed without merging**
