### PR TITLE
LPS-19939 Clean up user group assignments in organization

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @jorgeferrer @drewbrokke

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6223ec8e32...afabd2db13

**Comment by brianchandotcom** [comment]
@pei-jung in the future, make a new LPS, because that LPS says it was shipped in 6.1.x :)

**Comment by pei-jung** [comment]
ok, will do :)

**Pull request closed without merging**
