### PR TITLE
LPS-90813 Fix upgrade issue with some databases

### PR DESCRIPTION
**Pull request by epgarcia**
@jpince

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:test

**Comment by jpince** [comment]
@epgarcia thanks!

**Comment by jpince** [comment]
ci:reopen @michaelhashimoto @yichenroy @kenjiheigel looks like a CI fluke? Can this be caught in the generic CI-related exception?

**Comment by yichenroy** [comment]
@jpince 
I created a ticket for catching closed channel exceptions as CI failure:
 https://issues.liferay.com/browse/LRCI-17

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
