### PR TITLE
LPS-77526 Updates positioning class

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @brianchandotcom, @ithildir, after this gets merged (if tests are ok), we need to publish the following artifacts so this can be used by the Commerce team in their subrepo:
- An npm snapshot release of `frontend-theme-unstyled` and `frontend-theme-styled`
- A snapshot of `frontend-taglib`

Thanks!

/cc @marco-leo

**Comment by jbalsas** [comment]
ci:test

**Comment by kenjiheigel** [comment]
ci:stop

This will fail out later because of an issue in Jenkins. Going to restart this.

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/dfc97af40a...122216872c

**Comment by brianchandotcom** [comment]
@jbalsas See 206b34cf19fc9b2dab6ac1fbcbccadda25bba2e6 can you send me a follow up pull if needed? Thx.

**Comment by jbalsas** [comment]
Hey @brianchandotcom, that was the right call, thanks! 👍

**Pull request closed without merging**
