### PR TITLE
COMMERCE-5727 emergency fix to unblock CI - thank you

### PR DESCRIPTION
**Pull request by igorbeslic**

### CODE REVIEW

**Comment by igorbeslic** [comment]
ci:reopen

**Comment by igorbeslic** [comment]
related to this https://github.com/brianchandotcom/liferay-portal/pull/98965

**Comment by igorbeslic** [comment]
ci:test

**Comment by igorbeslic** [comment]
ci:test:relevant

**Comment by igorbeslic** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
