### PR TITLE
LPS-57375

### PR DESCRIPTION
**Pull request by danielkocsis**

### CODE REVIEW

**Comment by danielkocsis** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/af0b23fd8e...44106c1d2d

**Comment by brianchandotcom** [comment]
@danielkocsis I noticed that JournalWebUpgrade upgrades the portlet id, but WikiServiceUpgrade also upgrades the portlet id.

We should be consistent and always do it with a service module (if possible) and always do it via a web module (if no service module exists)

Can you search through *Upgrade.java and make this consistent change?

Thx @danielkocsis

**Comment by danielkocsis** [comment]
Hi Brian,

I have to finish some modularization taks before the deadline, but after that I'll check it and send the pull to you!

thanks,
Daniel

**Pull request closed without merging**
