### PR TITLE
LPS-65410 check for empty and null

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
I had to stop and retest this pull because a recent CI pull that got merged into upstream broke the PR tester. The source of this problem has been reverted.

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Hey @brianchandotcom 

can you help us with the semantic versioning here? I am not sure why it keeps failing...

**Comment by brianchandotcom** [comment]
"default" only works for portal-kernel/impl and other outer artifacts.

testIntegrationCompile group: "com.liferay", name: "com.liferay.journal.api", version: "default"

doesn't work.

You need to change it to use project dependencies (dir based)

Can you resend? Thx.

**Comment by juliocamarero** [comment]
Another attempt here: https://github.com/brianchandotcom/liferay-portal/pull/39369

**Pull request closed without merging**
