### PR TITLE
LPS 122247 replace deprecated taglib

### PR DESCRIPTION
**Pull request by jhanda**
Replacing <liferay-ui:custom-attribute> with  <liferay-expando:custom:attribute> in the expando help text.  Also passing in the taglib usage directly into the key.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jhanda is there an LPS ticket for this?

**Comment by brianchandotcom** [comment]
Nvm, I see it in the title. I'll redo the  commits to show the proper LPS.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/45de7f32d3...3b49a725eb

**Comment by brianchandotcom** [comment]
@jhanda I backported this to 7.3.x for you. For master, see c43b8389e39d426ac6498ceca31cddafd4387446 and 3b49a725eb2c964c55e622f72cb6612f87046fc1

I rewrote the Git commits to include the LPS

**Comment by jhanda** [comment]
Shoot, sorry I missed that and thanks for showing me the right way.

**Pull request closed without merging**
