### PR TITLE
LPS-102058 Check if the log directory exists before attempting to ope…

### PR DESCRIPTION
**Pull request by SamZiemer**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@brianchandotcom SF fails here.

**Comment by jpince** [comment]
@vicnate5 please monitor stable results from this PR, BChan reapplied LPS-101810 and merged this change as well https://github.com/brianchandotcom/liferay-portal/compare/29d704dea07e23468ef11cb90da07e377c530280...8684141f64fa1bb96ab4808e48b765e2487549b2
If it fails upgrades again, please ping BChan directly

This PR showed a merge conflict (Sam probably didn't reapply the commits from LPS-101810), so I don't think we'll get results from `ci:test:relevant` or your test suite

**Comment by vicnate5** [comment]
SF fixed by https://github.com/brianchandotcom/liferay-portal/commit/8684141f64fa1bb96ab4808e48b765e2487549b2

**Comment by vicnate5** [comment]
Testing at https://github.com/vicnate5/liferay-portal/pull/1283

**Pull request closed without merging**
