### PR TITLE
OAUTH2-215 buildService

### PR DESCRIPTION
**Pull request by csierra**
/cc @topolik

### CODE REVIEW

**Comment by pyoo47** [comment]
@PeterShin Looks like SF is hanging here

https://test-1-5.liferay.com/job/test-portal-source-format/221/console

```
format-source-all:
     [java] Exception in thread "main" java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Unable to format ./modules/apps/oauth2-provider/oauth2-provider-service/src/main/java/com/liferay/oauth2/provider/internal/upgrade/OAuth2ServiceUpgrade.java
     [java] 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
     [java] 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:321)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:234)
     [java] Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Unable to format ./modules/apps/oauth2-provider/oauth2-provider-service/src/main/java/com/liferay/oauth2/provider/internal/upgrade/OAuth2ServiceUpgrade.java
     [java] 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
     [java] 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor.format(BaseSourceProcessor.java:137)
     [java] 	at com.liferay.source.formatter.SourceFormatter._runSourceProcessor(SourceFormatter.java:785)
     [java] 	at com.liferay.source.formatter.SourceFormatter.access$000(SourceFormatter.java:68)
     [java] 	at com.liferay.source.formatter.SourceFormatter$1.call(SourceFormatter.java:307)
     [java] 	at com.liferay.source.formatter.SourceFormatter$1.call(SourceFormatter.java:303)
     [java] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] Caused by: java.lang.RuntimeException: Unable to format ./modules/apps/oauth2-provider/oauth2-provider-service/src/main/java/com/liferay/oauth2/provider/internal/upgrade/OAuth2ServiceUpgrade.java
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor._performTask(BaseSourceProcessor.java:754)
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor.access$000(BaseSourceProcessor.java:77)
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor$1.call(BaseSourceProcessor.java:126)
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor$1.call(BaseSourceProcessor.java:122)
     [java] 	... 4 more
     [java] Caused by: java.io.FileNotFoundException: https://raw.githubusercontent.com/liferay/liferay-portal/master,master/modules/apps/oauth2-provider/oauth2-provider-service/src/main/resources/META-INF/sql/tables.sql
     [java] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)
     [java] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
     [java] 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
     [java] 	at java.net.URL.openStream(URL.java:1045)
     [java] 	at com.liferay.source.formatter.checks.BaseSourceCheck.getPortalContent(BaseSourceCheck.java:434)
     [java] 	at com.liferay.source.formatter.checks.BaseSourceCheck.getPortalContent(BaseSourceCheck.java:407)
     [java] 	at com.liferay.source.formatter.checks.JavaUpgradeVersionCheck._hasColumnTypeAlteration(JavaUpgradeVersionCheck.java:480)
     [java] 	at com.liferay.source.formatter.checks.JavaUpgradeVersionCheck._hasColumnTypeAlteration(JavaUpgradeVersionCheck.java:453)
     [java] 	at com.liferay.source.formatter.checks.JavaUpgradeVersionCheck._adjustIncrementTypeForJava(JavaUpgradeVersionCheck.java:119)
     [java] 	at com.liferay.source.formatter.checks.JavaUpgradeVersionCheck._adjustIncrementType(JavaUpgradeVersionCheck.java:105)
     [java] 	at com.liferay.source.formatter.checks.JavaUpgradeVersionCheck._getExpectedIncrementType(JavaUpgradeVersionCheck.java:300)
     [java] 	at com.liferay.source.formatter.checks.JavaUpgradeVersionCheck._checkLatestUpgradeVersion(JavaUpgradeVersionCheck.java:196)
     [java] 	at com.liferay.source.formatter.checks.JavaUpgradeVersionCheck.doProcess(JavaUpgradeVersionCheck.java:69)
     [java] 	at com.liferay.source.formatter.checks.BaseJavaTermCheck._walkJavaClass(BaseJavaTermCheck.java:135)
     [java] 	at com.liferay.source.formatter.checks.BaseJavaTermCheck.process(BaseJavaTermCheck.java:41)
     [java] 	at com.liferay.source.formatter.checks.util.SourceChecksUtil._processJavaTermCheck(SourceChecksUtil.java:331)
     [java] 	at com.liferay.source.formatter.checks.util.SourceChecksUtil.processSourceChecks(SourceChecksUtil.java:145)
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor._processSourceChecks(BaseSourceProcessor.java:764)
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor.format(BaseSourceProcessor.java:325)
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor.format(BaseSourceProcessor.java:307)
     [java] 	at com.liferay.source.formatter.JavaSourceProcessor.format(JavaSourceProcessor.java:70)
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor._format(BaseSourceProcessor.java:644)
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor._performTask(BaseSourceProcessor.java:742)
     [java] 	... 7 more
```

**Comment by brianchandotcom** [comment]
@csierra backported.

**Comment by petershin** [comment]
@pyoo47 - Looking into it

**Comment by petershin** [comment]
@pyoo47 - I'm unable to reproduce the issue. From the logs it looks like a `source-formatter.properties` file has this line `git.liferay.portal.branch=master,master` and its causing SF to retrieve content from a bad url.

This property is only needed for subrepositories and valid values are public branch names from liferay-portal (i.e. `master`, `7.0.x`, etc)

**Comment by petershin** [comment]
I found a bug that could be causing this issue. If there are multiple `source-formatter.properties` files that contain `git.liferay.portal.branch`, SF will concatenate all the values together with a comma.

Sent a patch: https://github.com/brianchandotcom/liferay-portal/pull/61806

**Comment by pyoo47** [comment]
@petershin Thanks Peter!

**Pull request closed without merging**
