### PR TITLE
LPS-96203 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LPS-96203

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by john-co** [comment]
Hi @brunobasto, I'm temporarily disabling the test for now. Please re-enable when fixed. Thank you.

cc/ @jbalsas

**Comment by john-co** [comment]
cc/ @alexcandidos

**Comment by brunobasto** [comment]
Hey @john-co, Brian already merged the fix moments ago

**Pull request closed without merging**
