### PR TITLE
LPS-98143 SF, remove unnecessary attribues

### PR DESCRIPTION
**Pull request by csierra**
/cc @stian-sigvartsen @topolik

hi @tinatian, thx a lot for the PR, it looks good. 

I have just one concern with this approach, though, and it is that in this case it works because we have gone through the implementation and we have seen it is safe to update the list of handlers. As a general approach I would avoid to do this since we won't know how the third party (in this case CXF) will use the collection (if it caches it, handles it to other components, etc). 
It might vary from version to version of the third party library too, which might silently introduce bugs after future updates.

### CODE REVIEW

**Comment by tinatian** [comment]
@csierra 
Yes, I agree with you, and totally understand your concern, the fight between performance and robustness is always there, especially when we are using third-party libs. 

Doing things like this is not the first time, we have done same thing for core libs like spring, hibernate and others to cut off unnecessary burden, and we also patched a lot of third-party libs for performance. We all know that this kind of tuning is risky, but sometimes we have to do.

For this particular change, it is for sure an improvement according to code, but this one is not showing significant improvement according to our test,  so I do not insist that this must be merged.

If you think this is over your line of robustness based on the frequency of upgrading third-party jars and the hardness of debugging potential bugs, please go ahead to close this pull, I am totally OK with it.

Thanks.
Tina.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f9f1848a8b...b53a1c1a75

**Comment by brianchandotcom** [comment]
@csierra @tinatian I went ahead and merged it... 

Won't our tests break on upgrade?

**Comment by csierra** [comment]
hey @brianchandotcom, 
they might or might not, because they would probably be concurrency related. 
And even it they do we might already have forgotten about this by that time 😅.
But I believe this should be fine. 
Thx.

Carlos.

**Pull request closed without merging**
