### PR TITLE
LPS-88381 Removing unsupported upgrade paths for 7.2

### PR DESCRIPTION
**Pull request by achaparro**
cc/ @shuyangzhou @ealonso

### CODE REVIEW

**Comment by achaparro** [comment]
Hi @jpince, @vicnate5, @brianwulbern,

The two first tests which are failing (**functional-upgrade-tomcat90-mysql57-jdk8/5** and **functional-upgrade-tomcat90-mysql57-jdk8/6**) are related to upgrades from 6.1.x and below. Since we remove the 6.1.x path in this pull the error shown in those tests is perfectly fine, look for this in the log:
```
     [java] You must first upgrade to Liferay Portal 6200
     [java] java.lang.RuntimeException: You must first upgrade to Liferay Portal 6200
     [java] 	at com.liferay.portal.tools.DBUpgrader.checkRequiredBuildNumber(DBUpgrader.java:90)
     [java] 	at com.liferay.portal.tools.DBUpgrader.upgrade(DBUpgrader.java:148)
     [java] 	at com.liferay.portal.tools.DBUpgrader.main(DBUpgrader.java:107)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [java] 	at com.liferay.portal.tools.db.upgrade.client.DBUpgraderLauncher.main(DBUpgraderLauncher.java:55)
```
Upgrades from those versions must return this error.

For the latest failing test (**functional-upgrade-tomcat90-mysql57-jdk8/7**) I think we just need to modify the expected output (now is _You must first upgrade to Liferay Portal 6200_)

Please, update those tests accordingly.

Thanks.
Best regards.

cc/  @brianchandotcom

**Comment by jpince** [comment]
@achaparro thanks for letting us know. I'll let the other guys figure out what to do for the test. I'm not sure that we can assert for this failure in POSHI, because it occurs in the CI infrastructure set up before the test even starts.

**Comment by vicnate5** [comment]
I can take care of updating the tests. Will resend

**Comment by vicnate5** [comment]
ci:close

**Comment by vicnate5** [comment]
Resent with test fixes https://github.com/brianchandotcom/liferay-portal/pull/66374

**Pull request closed without merging**
