### PR TITLE
LPS-91222 Reenable org test

### PR DESCRIPTION
**Pull request by javiergamarra**
We think it's an issue with existing organizations and the indexer, this commits clears the existing organizations. We can also force a reindex.

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@nhpatt thx for the fix..

**Comment by brianchandotcom** [comment]
@nhpatt I still get this with your changes

```
com.liferay.headless.foundation.resource.v1_0.test.OrganizationResourceTest > testGetOrganizationsPage FAILED
    com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'No': was expecting 'null', 'true', 'false' or NaN
     at [Source: UNKNOWN; line: 1, column: 3]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:703)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2853)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2831)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._matchToken(ReaderBasedJsonParser.java:2612)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1876)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:757)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4141)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4000)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3023)
        at com.liferay.headless.foundation.resource.v1_0.test.BaseOrganizationResourceTestCase.invokeGetOrganizationsPage(BaseOrganizationResourceTestCase.java:468)
        at com.liferay.headless.foundation.resource.v1_0.test.BaseOrganizationResourceTestCase.testGetOrganizationsPage(BaseOrganizationResourceTestCase.java:233)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$2.evaluate(TestExecutorRunnable.java:181)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.test.rule.LiferayIntegrationTestRule$1$1.evaluate(LiferayIntegrationTestRule.java:154)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:118)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.test.rule.LiferayIntegrationTestRule$1$1.evaluate(LiferayIntegrationTestRule.java:154)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:156)
        at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:77)
        at java.lang.Thread.run(Thread.java:745)

com.liferay.headless.foundation.resource.v1_0.test.OrganizationResourceTest > testGetOrganizationsPageWithFilterDateTimeEquals STARTED

com.liferay.headless.foundation.resource.v1_0.test.OrganizationResourceTest > testGetOrganizationsPageWithFilterDateTimeEquals PASSED

com.liferay.headless.foundation.resource.v1_0.test.OrganizationResourceTest > testGetOrganizationsPageWithFilterStringEquals STARTED

com.liferay.headless.foundation.resource.v1_0.test.OrganizationResourceTest > testGetOrganizationsPageWithFilterStringEquals PASSED

com.liferay.headless.foundation.resource.v1_0.test.OrganizationResourceTest > testGetOrganizationsPageWithPagination STARTED

com.liferay.headless.foundation.resource.v1_0.test.OrganizationResourceTest > testGetOrganizationsPageWithPagination FAILED
    com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'No': was expecting 'null', 'true', 'false' or NaN
     at [Source: UNKNOWN; line: 1, column: 3]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:703)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2853)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2831)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._matchToken(ReaderBasedJsonParser.java:2612)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1876)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:757)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4141)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4000)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3023)
        at com.liferay.headless.foundation.resource.v1_0.test.BaseOrganizationResourceTestCase.invokeGetOrganizationsPage(BaseOrganizationResourceTestCase.java:468)
        at com.liferay.headless.foundation.resource.v1_0.test.BaseOrganizationResourceTestCase.testGetOrganizationsPageWithPagination(BaseOrganizationResourceTestCase.java:321)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$2.evaluate(TestExecutorRunnable.java:181)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.test.rule.LiferayIntegrationTestRule$1$1.evaluate(LiferayIntegrationTestRule.java:154)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:118)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.test.rule.LiferayIntegrationTestRule$1$1.evaluate(LiferayIntegrationTestRule.java:154)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:156)
        at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:77)
        at java.lang.Thread.run(Thread.java:745)

com.liferay.headless.foundation.resource.v1_0.test.OrganizationResourceTest > testGetOrganizationsPageWithSortDateTime STARTED

com.liferay.headless.foundation.resource.v1_0.test.OrganizationResourceTest > testGetOrganizationsPageWithSortDateTime FAILED
    com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'No': was expecting 'null', 'true', 'false' or NaN
     at [Source: UNKNOWN; line: 1, column: 3]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:703)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2853)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2831)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._matchToken(ReaderBasedJsonParser.java:2612)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1876)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:757)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4141)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4000)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3023)
        at com.liferay.headless.foundation.resource.v1_0.test.BaseOrganizationResourceTestCase.invokeGetOrganizationsPage(BaseOrganizationResourceTestCase.java:468)
        at com.liferay.headless.foundation.resource.v1_0.test.BaseOrganizationResourceTestCase.testGetOrganizationsPageWithSortDateTime(BaseOrganizationResourceTestCase.java:376)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$2.evaluate(TestExecutorRunnable.java:181)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.test.rule.LiferayIntegrationTestRule$1$1.evaluate(LiferayIntegrationTestRule.java:154)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:118)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.test.rule.LiferayIntegrationTestRule$1$1.evaluate(LiferayIntegrationTestRule.java:154)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:156)
        at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:77)
        at java.lang.Thread.run(Thread.java:745)

com.liferay.headless.foundation.resource.v1_0.test.OrganizationResourceTest > testGetOrganizationsPageWithSortString STARTED

com.liferay.headless.foundation.resource.v1_0.test.OrganizationResourceTest > testGetOrganizationsPageWithSortString FAILED
    com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'No': was expecting 'null', 'true', 'false' or NaN
     at [Source: UNKNOWN; line: 1, column: 3]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:703)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2853)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2831)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._matchToken(ReaderBasedJsonParser.java:2612)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1876)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:757)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4141)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4000)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3023)
        at com.liferay.headless.foundation.resource.v1_0.test.BaseOrganizationResourceTestCase.invokeGetOrganizationsPage(BaseOrganizationResourceTestCase.java:468)
        at com.liferay.headless.foundation.resource.v1_0.test.BaseOrganizationResourceTestCase.testGetOrganizationsPageWithSortString(BaseOrganizationResourceTestCase.java:416)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$2.evaluate(TestExecutorRunnable.java:181)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.test.rule.LiferayIntegrationTestRule$1$1.evaluate(LiferayIntegrationTestRule.java:154)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:118)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.test.rule.LiferayIntegrationTestRule$1$1.evaluate(LiferayIntegrationTestRule.java:154)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:156)
        at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:77)
        at java.lang.Thread.run(Thread.java:745)

com.liferay.headless.foundation.resource.v1_0.test.OrganizationResourceTest > testGetUserAccou
```

**Comment by brianchandotcom** [comment]
@nhpatt I added the ignore again, please fix and resend.

**Comment by nhpatt** [comment]
Sorry for your time :(

 I think it's an indexer issue (I had Sarai and Victor launch it without issues). Will recheck, force an index, and resend.

**Pull request closed without merging**
