### PR TITLE
LPS-76927 Tracking every small upgrade process in Core with a unique SchemaVersion and simplifying the release process

### PR DESCRIPTION
**Pull request by achaparro**
Hi @brianchandotcom,

This is the final pull with the changes you suggested here:
https://github.com/brianchandotcom/liferay-portal/pull/57020

Thanks!

cc/ @shuyangzhou

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test

**Comment by achaparro** [comment]
sf errors seem unrelated

**Comment by achaparro** [comment]
ci:reopen

**Comment by michaelhashimoto** [comment]
ci:stop

**Comment by michaelhashimoto** [comment]
ci:test

@achaparro - Sorry, I have to restart this one.  There was something wrong with CI.

**Comment by brianchandotcom** [comment]
@michaelhashimoto how did this pull get that stale SF error? What was wrong with CI?

**Comment by brianchandotcom** [comment]
@achaparro please resend on top of https://github.com/achaparro/liferay-portal/pull/155

Please review my changes.

Also, portal-data-release.sql, but, that file is still referenced in

build-working-dir.xml
modules/core/slim-runtime/src/main/java/com/liferay/slim/runtime/internal/service/SlimRuntimeReleaseLocalServiceImpl.java
portal-impl/build.xml
sql/portal.sql

Type "git grep portal-data-release"

Please resend. Thx.

**Comment by michaelhashimoto** [comment]
@brianchandotcom - It's because we need to change how it's identifying "source-formatter" module changes.  This pull had a change to a "source-formatter-suppressions.xml" file, which made it run against all source code instead of just the current branch.

Basically instead of this:
<pre><code>&lt;contains string="${git.diff}" substring="source-formatter" /&gt;</code></pre>

We need to filter using this:
<pre><code>&lt;contains string="${git.diff}" substring="modules/util/source-formatter" /&gt;</code></pre>

This change needs to happen here:
https://github.com/liferay/liferay-portal/blob/master/build-test-batch.xml#L3399-L3404

I passed this information along to @cesar-polanco to add to the updates the to "SF" job.

**Comment by achaparro** [comment]
Hi @brianchandotcom,

A new pull has been sent here:
https://github.com/brianchandotcom/liferay-portal/pull/57075

Thanks!

**Pull request closed without merging**
