### PR TITLE
POSHI-64 Release poshi runner 1.0.261

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/POSHI-64 

@brianchandotcom, once the new gradle plugin is published, this will enable Poshi test retries in CI. Here's some basic information:
1. Only tests using virtual instances will be retried (they have a valid teardown). Tests running individually will not be retried.
2. Retry attempts are set in liferay-jenkins-ee (I conservatively set it to: 1 retry per test, 3 retries in the test group). 
3. If a test is retried and found flaky (fail then pass), a notification will be sent to #qa-flaky-tests (~I need to fix something in liferay-jenkins-ee, but should be working later this afternoon or so~ fixed)

### CODE REVIEW

**Comment by kenjiheigel** [comment]
Tested heavily here: 
https://github.com/kenjiheigel/liferay-portal/pull/573 (against all functional tests) 
https://github.com/kenjiheigel/liferay-portal/pull/576#issuecomment-607500710 (SF)

**Comment by kenjiheigel** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f7d9ceec65...70063c0eaa

**Comment by brianchandotcom** [comment]
@kenjiheigel very nice !

**Pull request closed without merging**
