### PR TITLE
LPS-135170 - Add Tests

### PR DESCRIPTION
**Pull request by ethib137**

### CODE REVIEW

**Comment by ethib137** [comment]
ci:reopen

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b8edd88a0b...9ceaf0eb7d

**Comment by brianchandotcom** [comment]
Nice @dantewang @ethib137 see 9ceaf0eb7d1179a41d5245260934d3b2b4070251

**Pull request closed without merging**
