### PR TITLE
LPS-57374 Use Set instead of List to avoid duplicates

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c262d3b8ff...e5ed765d1a

**Comment by brianchandotcom** [comment]
@JorgeFerrer please see my changes in upstream. Specifically, I had to prevent hackers from hijacking your new placeholder role name.

Thx

**Comment by brianchandotcom** [comment]
@JorgeFerrer please add more tests around the hijacking part. Thx.

**Pull request closed without merging**
