### PR TITLE
LPS-61772 When reindex one special model, all portlets get reindexed

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @jorgeferrer @drewbrokke

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pei-jung the param should be "className". Please resend. Thx.

**Comment by drewbrokke** [comment]
I'm curious how that works.  The request is getting the param from a data attribute (data-classname) which apparently automatically makes everything lower case.  Is there a way to return the attribute name to camelCase?

**Comment by pei-jung** [comment]
The custom data attribute is defined here as https://github.com/liferay/liferay-portal/blob/master/modules/apps/server-admin/server-admin-web/src/main/resources/META-INF/resources/resources.jsp#L151. From what I know, all data attribute names should be lower case, and that's why we need to use lowercase name in the param to retrieve the value. If we want to use camelCase for the param, I think we will need to do some conversion in the js (https://github.com/liferay/liferay-portal/blob/master/modules/apps/server-admin/server-admin-web/src/main/resources/META-INF/resources/js/main.js#L70) when processing the form.

/cc @natecavanaugh to see if Nate has any idea on this.

**Comment by natecavanaugh** [comment]
@pei-jung What I would recommend is inside of the JS creating a map constant, like so:
```js
var MAP_DATA_PARAMS = {
    classname: 'className'
};
```

and [inside of the loop](https://github.com/liferay/liferay-portal/blob/d0ec9a7637cb40ef9609dd239b9f8c08fb38a7ad/modules/apps/server-admin/server-admin-web/src/main/resources/META-INF/resources/js/main.js#L78), before the `nsKey` assignment, do:

```js
key = MAP_DATA_PARAMS[key] || key;
```

This will let you scale it so that if there are any other data attributes that end up needing to have their casing changed (or even remapped to something else entirely), you can just keep adding to that map.

Hopefully that makes sense, but let me know if you have any questions on it :)

**Comment by pei-jung** [comment]
Hey @natecavanaugh,

That makes sense. I sent you a pr with the changes you suggested. See https://github.com/natecavanaugh/liferay-portal/pull/3758. Thanks!

**Pull request closed without merging**
