### PR TITLE
LPS-105380 Fix compilation error

### PR DESCRIPTION
**Pull request by brittneyq**
Hi @brianchandotcom, this should fix the stable compilation error! It should fix the reference to the date class that was removed.

### CODE REVIEW

**Comment by brittneyq** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@hhuijser fyi

**Comment by brianchandotcom** [comment]
@hhuijser I ended up just removing the line since createDate should be "now" anyways.

**Comment by brianchandotcom** [comment]
@hhuijser my fix d1b082dc6a2ddb9011dcc9de2d9ef84211a5ea1e

**Pull request closed without merging**
