### PR TITLE
Lps 109734

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@slnn this merges CSSBuilder back to gradle daemon

**Comment by michaelhashimoto** [comment]
ci:test:relevant - We aborted all master pull request jobs.  However, we decided to re-run all pulls in @brianchandotcom queue.

**Comment by slnn** [comment]
Hi @shuyangzhou 

Run ant all monitor test on this pull, no CSSBuilder process be found in test report. 

Detaile report please see: https://gist.github.com/slnn/4869338e4ff1f287974e3991171c147b

Regards
Lily

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/85748 to drop the CI CSSBuilder jvm forking settings

**Pull request closed without merging**
