### PR TITLE
LPS-83841 Add test to Structured Content APIO

### PR DESCRIPTION
**Pull request by cgoncas**
Hi Brian,

We try to use the "-conditionalpackage:" in bnd.bnd. But this was not a good approach for us, since we need to register the component so we could test it.

Another problem that we found is that if we make public the method _getPageItems, the SF complains no matter if it is inside a internal package.

With all these issues, and as our only goal is to test the _getPageItem method, we decide that maybe we could use reflection to solve this issue.

Here you could check the new pull that add test for the _getPageItem method. What do you think?

Thanks a lot,
Cristina

@juliocamarero

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6c7180fbb2...a46fb783f4

**Comment by brianchandotcom** [comment]
@cgoncas @juliocamarero this is much much much better. Simple, no over engineering.

Please see my changes in upstream. I made a bunch of tiny ones over 5 commits. Please review.

Thx!

**Comment by brianchandotcom** [comment]
@cgoncas also, as we write more tests for headless apio, I have a feeling we'll be using a lot more of PaginationTestUtil, so we'll probably want to move that somewhere else in the future, just fyi.

**Comment by cgoncas** [comment]
Thanks a lot @brianchandotcom, we know probably we would need to extract PaginationTestUtil, we are going to wait until we need it in another API.

**Pull request closed without merging**
