### PR TITLE
LPS-173383 Update Integration Test

### PR DESCRIPTION
**Pull request by diogomelo09**
[liferay-portal/pull/1931](https://github.com/liferay-objects/liferay-portal/pull/1931)

### CODE REVIEW

**Comment by diogomelo09** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@diogomelo09 @kiwm @MarinhoFeliphe this is not prefixed properly the constants file
```
	public static final String PK_OBJECT_FIELD_DB_COLUMN_NAME_1 =
		"pkObjectFieldDBColumnName1";

	public static final String PK_OBJECT_FIELD_DB_COLUMN_NAME_2 =
		"pkObjectFieldDBColumnName2";
```

Please resend.

**Comment by brianchandotcom** [comment]
@diogomelo09 @kiwm @MarinhoFeliphe  ci:reopen sorry, my previous comment was for a different PR

**Comment by diogomelo09** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@diogomelo09 @kiwm @MarinhoFeliphe this PR does not compile.

**Pull request closed without merging**
