### PR TITLE
LPS-171258

### PR DESCRIPTION
**Pull request by murilostodolni**
Hi Brian

Folow-up: https://github.com/brianchandotcom/liferay-portal/pull/127878

cc @danvb112 @naraandrade

### CODE REVIEW

**Comment by murilostodolni** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@danvb112 @murilostodolni rebase error, please resend.

**Comment by brianchandotcom** [comment]
@naraandrade @danvb112 @murilostodolni actually, I'm merging this since it's a blocker, please resend LPS-170680, I reverted that ticket instead.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3f5898df94...7e589f2eed

**Comment by brianchandotcom** [comment]
@murilostodolni just 7e589f2eed6720b97e6877fa6ea5896fa5c13b68

**Pull request closed without merging**
