### PR TITLE
LPS-64609 extended is obsolete

### PR DESCRIPTION
**Pull request by matethurzo**
@brianchandotcom I was updating the tld doc and the other part of this change is being sent to @codyhoag. In the meantime I realized that we have some obsolete attributes so I removed those.

### CODE REVIEW

**Comment by matethurzo** [comment]
unrelated test failures

**Comment by brianchiu** [comment]
Yep. Those poshi failures are unrelated. They started happening because liferay.com changed from "http" to "https" so the bookmarks test assert URL step failed. @kenjiheigel has disabled the tests here: https://github.com/liferay/liferay-portal/commit/6c21532fc314f15e56b7a73e4e938cb989666478

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9c8be595ac...bf88904b71

**Comment by brianchandotcom** [comment]
@matethurzo see 9c89f6f0951695a15e4bb70304eeaadbe29d8abe

**Comment by matethurzo** [comment]
@brianchandotcom thanks Brian for the version update. I'll keep that in mind next time!

**Pull request closed without merging**
