### PR TITLE
LPS-110284 Autogenerated

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:backend

**Comment by vicnate5** [comment]
@kyle-miho where are we at the with the databases here? (See the integration results)

**Comment by kyle-miho** [comment]
@vicnate5 the integration failures seem to all be unrelated, this pull should be pretty safe

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7b8253e02e...de16875835

**Pull request closed without merging**
