### PR TITLE
OAUTH2-131 SF

### PR DESCRIPTION
**Pull request by csierra**
/cc @topolik

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7f5a3bb86c...69235dc314

**Comment by brianchandotcom** [comment]
@csierra please see my changes in upstream. Thx!

**Comment by csierra** [comment]
thx Brian... please see follow up pull with the rest of the tests https://github.com/brianchandotcom/liferay-portal/pull/59425

**Comment by csierra** [comment]
thx Brian... please see follow up pull with the rest of the tests https://github.com/brianchandotcom/liferay-portal/pull/59426

**Pull request closed without merging**
