### PR TITLE
LPS-121824/LPS-121466

### PR DESCRIPTION
**Pull request by petershin**
Manual forward: https://github.com/petershin/liferay-portal/pull/1246

LPS-121824: avoid chicken and egg scenario for the 7.4 changes in master-private
LPS-121466: fix regression on master

@jpince

### CODE REVIEW

**Comment by petershin** [comment]
ci:reopen

**Comment by jpince** [comment]
@brianchandotcom I reviewed the test result in [Peter's pull](https://github.com/petershin/liferay-portal/pull/1246#issuecomment-705817837), failure was an unrelated jenkins issue. Please merge with the other pulls for LPS-121842:
https://github.com/brianchandotcom/liferay-portal/pull/94869
https://github.com/brianchandotcom/liferay-portal-ee/pull/31776

**Comment by jpince** [comment]
Just started reviewing :)

**Comment by brianchandotcom** [comment]
@petershin please review my changes for LPS-121824 in liferay-portal-ee 7.2.x, 7.1.x, and 7.0.x

They were all a tiny bit different. Thx.

**Pull request closed without merging**
