### PR TITLE
Lps 112054

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@dantewang 

Type:

git grep resource.actions.configs  **portlet.properties

Notice that *-web does not have META-INF, the other ones do have it.

Your change to modules/apps/mobile-device-rules/mobile-device-rules-web/src/main/resources/portlet.properties seems inconsistent.

Can you review the usages to make sure it's consistent and resend? Thx.

@tinatian fyi.

**Comment by dantewang** [comment]
@brianchandotcom Basically it's inconsistent across the portal. Many modules put it in META-INF while many other don't. I'll move all the resource-actions out of META-INF as described in the document: https://help.liferay.com/hc/zh-cn/articles/360029045331-Defining-Resources-and-Permissions

> You define resources and their permissions using an XML file. By convention, this file is called default.xml and exists in a module’s src/main/resources/resource-actions folder.

**Comment by dantewang** [comment]
Fetched

**Pull request closed without merging**
