### PR TITLE
LPS-52934 Proper initialization of the test

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d981ef30eb...14532c5a9b

**Comment by brianchandotcom** [comment]
Hey @sergiogonzalez 

If we needed to add this code, then how was it working before even if it was "improper"? Thx.

**Comment by sergiogonzalez** [comment]
Hey @brianchandotcom 

We needed this change for this pull: https://github.com/brianchandotcom/liferay-portal/pull/23448

Because otherwise the test would fail because of the initialization of the PortletToolbar because the registry is not set at that point.

Thanks!

**Comment by brianchandotcom** [comment]
Got it. Thx.

**Pull request closed without merging**
