### PR TITLE
master-qa-19417

### PR DESCRIPTION
**Pull request by michaelhashimoto**
http://issues.liferay.com/browse/LRQA-19417

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
@brianchandotcom - As I was testing the new release I ran into this issue as well. So.. unfortunately we'll need to do another release of poshi runner before it can be applied.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/907bc8d40b...875eaafa87

**Comment by brianchandotcom** [comment]
@michaelhashimoto published a new one

**Comment by michaelhashimoto** [comment]
@brianchandotcom - Thanks! I'm testing it out here and here:
https://test-3-3.liferay.com/job/test-portal-branch-user(master)/11/
https://github.com/michaelhashimoto/liferay-portal/pull/885

**Pull request closed without merging**
