### PR TITLE
LPS-55600 use same sql for count and find methods

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/eee4cca211...620fdacc0a

**Comment by brianchandotcom** [comment]
@arbetts this is easy to write an integration test for.. just do a count and a find and ensure the size and count are the same.. please send a test. Thx.

**Comment by arbetts** [comment]
@brianchandotcom 

will follow up with test, thanks

**Comment by arbetts** [comment]
verified that test already exists in master

**Pull request closed without merging**
