### PR TITLE
LPS-105567 Better package naming

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3b97b8a294...d7aeeb713e

**Comment by brianchandotcom** [comment]
@4lejandrito can you get someone to fix the Poshi errors

Thx.

**Comment by 4lejandrito** [comment]
Hi @austinchiang,

Can you have a look at the poshi failures? They should not be related.

Thanks!

**Comment by austinchiang** [comment]
The failing tests do not belong to our team. I'll escalate this to others

**Pull request closed without merging**
