### PR TITLE
LPS-166123 baseline

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-166123

@ealonso

### CODE REVIEW

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/9997

:x: ci:test:stable - 27 out of 28 jobs passed
:x: ci:test:relevant - 292 out of 300 jobs passed in 3 hours 50 minutes

**Comment by ozysouza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6def0503a3...2f1d6dc782

**Comment by brianchandotcom** [comment]
@ealonso just 2f1d6dc7821322bb2aeadcce59617e1131e3a88a

**Pull request closed without merging**
