### PR TITLE
LPS-67510 regenerate service code for renamed entity

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:reopen

**Comment by adolfopa** [comment]
ci:retest

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
@adolfopa I just did the same thing with someone else's pull, I guess the "missing reference" auto-close doesn't work the same as the others, where it won't auto-close after a ci reopen. It keeps closing because BChan's branch isn't updated to include https://github.com/liferay/liferay-portal/commit/18c8547ca2cb9e3914b3ed8c56d74f2014a8dd02

**Comment by brianchandotcom** [comment]
ci:retest (I pushed my change to upstream)

**Comment by jpince** [comment]
ci:reopen @brianchandotcom I don't think updating your branch will change the commits listed above - in order for the PR Tester to run, I think those commits would need to be resent

**Comment by adolfopa** [comment]
ci:retest

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/46923

**Pull request closed without merging**
