### PR TITLE
LPS-196062 - [Add support for system ObjectActions] Integration Test

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://liferay.atlassian.net/browse/LPS-196062
Unrelated failures: https://github.com/liferay-objects/liferay-portal/pull/2661

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@G-Sa @marcelabc come find me on Monday to talk about the comments. Some of them don't make sense to me.

**Comment by brianchandotcom** [comment]
@G-Sa @marcelabc I explained to Gabriel why this was strange to me. He'll resend.

**Comment by gabrielwas** [comment]
resent here https://github.com/brianchandotcom/liferay-portal/pull/143168

**Pull request closed without merging**
