### PR TITLE
LPS-60502 Provide a way to go back from a search

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
That's a lot of scan log errors. Rerunning

ci:retest

**Comment by brianchandotcom** [comment]
@JorgeFerrer poshi and scan xml log errors are real. Please resend.

**Comment by JorgeFerrer** [comment]
Hey Brian,

I've been looking at the errors and it seems there are two different ones, both related by classes that have not been modified in this pull. In any case, this pull is not super urgent and these issues need to be fixed anyway. Here are the errors:

1) OCD Error

This is the root cause of many of the errors. It's well described here: https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/10983/AXIS_VARIABLE=3,label_exp=!master/testReport/junit/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanOSGiLog/
!MESSAGE Missing element "AD" of parent element "OCD" with ID "com.liferay.portal.js.bundle.config.extender.BundleConfigServlet" in metadata XML at "bundleentry://91.fwk9921696/OSGI-INF/metatype/com.liferay.portal.js.bundle.config.extender.Details.xml" for bundle ID "91" with symbolic name "com.liferay.portal.js.bundle.config.extender".

@csierra Can you take a look at it? It seems to be related to com.liferay.portal.js.bundle.config.extender.Details and you seem to be the author

2) Invalid LDAP baseDN

This can be seen, for example, in this error: https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/19638/testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXMLLog/

It looks like a problem with the default values in the associated config classes. @mhan810 or @topolik can you take a look?

**Comment by csierra** [comment]
Hey @JorgeFerrer, 

please see https://github.com/JorgeFerrer/liferay-portal/pull/627

**Pull request closed without merging**
