### PR TITLE
LPS-98387 expose viewcount

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cc4d7488ee...186aec6b07

**Comment by nhpatt** [comment]
Thanks!

**Pull request closed without merging**
