### PR TITLE
LPS-67918 fix regression caused by 90d80bbb58903e771120333ac23b78837cf4d498, use appropriate group to perform control panel check when showing porlet permissions icon

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
cc: @juliocamarero

**Comment by ealonso** [comment]
cc: @pei-jung

**Comment by ealonso** [comment]
ci:reopen

**Comment by anthony-chu** [comment]
This failure is due to a VNC failure that has been reported under [LRQA-28169|https://issues.liferay.com/browse/LRQA-28169].

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
