### PR TITLE
LPS-134096, LPS-111992 | master

### PR DESCRIPTION
**Pull request by Sharryxue**
https://issues.liferay.com/browse/LPS-134096
https://issues.liferay.com/browse/LPS-111992 

/cc @ChrisKian @drewbrokke 
No specific failure found on original pr, manual forward the commits.
Origin pr for [LPS-134096](https://issues.liferay.com/browse/LPS-134096) [liferay-usm/liferay-portal#112](https://github.com/liferay-usm/liferay-portal/pull/112)
Origin pr of an update for [LPS-111992](https://issues.liferay.com/browse/LPS-111992). [liferay-usm/liferay-portal#79](https://github.com/liferay-usm/liferay-portal/pull/79)

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@ChrisKian please resend without adding the new methods.

User user = userPersistence.findByPrimaryKey(userId); 

so I don't see how this can make things any faster.

@drewbrokke @Sharryxue fyi

**Comment by Sharryxue** [comment]
Thanks for reviewing the commits @brianchandotcom.
Resend the the pr only with commit for [LPS-111992](https://issues.liferay.com/browse/LPS-111992) [brianchandotcom/liferay-portal#103883](https://github.com/brianchandotcom/liferay-portal/pull/103883)

**Comment by drewbrokke** [comment]
@brianchandotcom the new methods have a different return type. They return a boolean: `true` if changes were made, `false` if nothing changed. We use this to determine whether or not a reindex is needed.

**Comment by drewbrokke** [comment]
@ChrisKian after chatting with Brian, let's just change the current methods to return a boolean. He's ok with a breaking change, just be sure to document it in the `readme/BREAKING_CHANGES.markdown` file.

**Comment by ChrisKian** [comment]
Resent here: https://github.com/liferay-usm/liferay-portal/pull/129

**Pull request closed without merging**
