### PR TITLE
LPS-49545 LDAPFilterValidator fix

### PR DESCRIPTION
**Pull request by vilmospapp**
Hi Brian,

You already reviewed most commits of this issue, but you asked Marcellus to move it to a module. He asked me to do it, and meanwhile the LDAP related functionalities were moved to modules/portal/portal-ldap, so I discussed it with Miguel, and instead of creating a new module for this validator, I moved it to the LDAP module. After Miguel reviewed and corrected my changes, he agreed that I can send it to you.

Please review the changes.

Regards,
Vilmos

### CODE REVIEW

**Comment by kiyoshilee** [comment]
@vilmospapp in order for your pull request to be tested you will need to publicize your association with the liferay organization on your github profile. Please see this <a href="https://help.github.com/articles/publicizing-or-concealing-organization-membership/"> link</a> for details on how to do so.

**Comment by vilmospapp** [comment]
Hi @kiyoshilee 

Done, but I don't really understand what was the problem with the default private setting. It worked fine since we moved from SVN to GIT.

**Comment by kiyoshilee** [comment]
ci:retest

**Comment by kiyoshilee** [comment]
@vilmospapp Brian made a few changes to how we test pull requests that are opened to him. This is what he sent in an email last month

<blockquote>
We need everyone who wishes to have their pull requests tested by the CI server to publicly put on their GitHub profile that they belong to the Liferay org.

If you don't, then when you send a pull, the CI server will assume it's malicious and not test the pull. We have to use this public info so that our CI servers run with an unprivileged account.
</blockquote>

**Comment by vilmospapp** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Please resend? Test failures. Thx.

**Pull request closed without merging**
