### PR TITLE
LPD-25577 When the current live group is already at HEAD, no need to …

### PR DESCRIPTION
**Pull request by shuyangzhou**
…save the same PortalPreferences value back to DB, it is purely a waste of time.

@tinatian @vicnate5 backport is needed for LXC, thanks!

@slnn this should drop DB usages on all test cases, please guide @victorhcunha to run through a runtime performance compare on all test cases, thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c70ecaca06...6dc47a2e61

**Comment by slnn** [comment]
Hi @victorhcunha

Steps to run through a runtime performance comparison on pull request

**Way 1 (If the pull request does not be merged)**

1. Update the master of portal, pick the current head of master as the baseline portal version
2. Run performance tests on all test cases with the baseline portal version
3. Record test results for baseline
4. Create a new branch based on the baseline portal version and apply the pull request to make sure the change in the pull request we want to compare is the only difference between the new branch and baseline portal version
6. Run performance tests on all test cases with the new branch which contains the change of the pull request
7. Record test results for the pull request

**Way 2 (If the pull request has been merged to master)**

1. Update the master of portal
2. Create a branch before the change of the pull request, and use it as the baseline portal version
3. Run performance tests on all test cases with the baseline portal version
4. Record test results for baseline
5. Create a new branch based on the last commit of the pull request
6. Run performance tests on all test cases with the new branch which contains the change of the pull request
8. Record test results for the pull request


**Here is what needs to be recorded for each test:**

1. **Session count**: pick the instant current session count of the last sample
2. **Meantime**,  For Login: the meantime of Log in, For Web Content: the meantime of Log in and View Page, For Document Library: the meantime of Log in and Add DL File, For AssetPublisher: the meantime of Log in and View Page with Filter

Session Count and Meantime are the basic data we need to compare, but sometimes we may not see noticeable difference on them, then we can compare other data in test result zip, here we should compare the db cpu usage, please list the db cpu usage for baseline and pull request, go to this file /database/logs/db-vmstat.log and record the value of us, as our test will do many times sample,  you can pick three data points from these sample: begin, middle, end.

By the way, if you find any other noticeable differences on the test results between baseline and pull request, you can also list them.

Lily

**Comment by slnn** [comment]
Update from @victorhcunha: 
The partial results have been updated in 
https://docs.google.com/spreadsheets/d/1y74gSLgbOmaX9oLYrBbiQd0TEL9nEQ2sXpxvql6yY24/edit?usp=sharing

**Comment by slnn** [comment]
Hi @victorhcunha

I have checked test results in the google doc, I just see test results for baseline, please let me know if you encounter any problems when running tests, according to the config files, one test costs about 1 hour,  we only have four test cases so I expect you can get all test results for baseline and at least another two test results on the pr within one day.

Thanks
Lily

**Comment by victorhcunha** [comment]
Hi @slnn,
Some tests for the PR were still running. I waited for everyone's test cases to finish before starting to fill in the spreadsheet.

**Comment by victorhcunha** [comment]
Hi @shuyangzhou !
The results are available: [Benchmark Compare for LPD-25577](https://docs.google.com/spreadsheets/d/1y74gSLgbOmaX9oLYrBbiQd0TEL9nEQ2sXpxvql6yY24/edit#gid=0) (the results files are available in the spreadsheet too)

Please let me know if any other adjustments are needed.
cc @slnn

**Comment by slnn** [comment]
Hi @victorhcunha

Thanks @victorhcunha! 

Next time you do not need to wait for all tests to be finished and then update test results,  just update what you have got at the end of your day, for example,  if two tests of the four tests for pr are finished at the end of your day,  just update the two test results, you can update the other two test results next day.  Because if we find something wrong in one test, we do not need to run tests on other test cases.

Lily

**Comment by victorhcunha** [comment]
Hi @shuyangzhou !
Here are the partial results with the new config folowing #150165 cc @slnn 

**Login Testcase**
Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | DB CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | --
Baseline | 624ebc3 | 7854 | - | 261 | 9,10,9 | 87,88,85
PR | - | 8087 | 2.966641202 | 270 | 11,9,9 | 86,89,87


**WebContent Testcase**
Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | Mean Time of View Page | DB CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | -- | --
Baseline | 624ebc3 | 10820 | - | 133 | 32.6 | 3,3,3 | 66,73,74
PR | - | 10823 | 0.02772643253 | 144 | 39 | 3,3,3 | 66,73,76

**AssertPublisher Testcase**
Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | Mean Time of View Page with Filter | DB CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | -- | --
Baseline | 624ebc3 | 6145 | - | 291 | 182 | 4,4,5 | 95,95,96
PR | - | 6355 | 3.417412531 | 295 | 179 | 5,4,4 | 96,95,95



The DL testcase is still runing

More details you can check in this [google doc](https://docs.google.com/spreadsheets/d/1M6VK8GtY9kkv1EwhGW7vwrEENSzyT7zKz-wOh11ZHBo/edit#gid=289870423)

**Comment by shuyangzhou** [comment]
Thanks @victorhcunha !

**Pull request closed without merging**
