### PR TITLE
LPS-74404 Stores redirectPath in the state for the next pop action, since we likely don't want to resubmit an action

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@jpince we're getting close to getting it green

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3f00a19583...e8674ca27f

**Pull request closed without merging**
