### PR TITLE
LPS-60355 Use correct TCCL and load correct xalan

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by juangon** [comment]
ci:retest

**Comment by csierra** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@csierra poshi errors, please resend.

**Comment by csierra** [comment]
ci:retest

**Comment by alee8888** [comment]
@csierra It looks these are actual functional test failures caused by your changes. A couple of failures I see looking at the Poshi Report is:

1. Unable to add the Asset Publisher and the Tags Navigation portlet
2. Something is broken with workflow when you navigate to My Workflow Tasks (it navigate to a blank page)

Please let me know if you need help with discerning the functional test failures.

**Comment by csierra** [comment]
thanks @alee8888... looking into it! :eyes:

**Pull request closed without merging**
