### PR TITLE
LPS-75579 Adds SynchronousDestinationTestRule

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@shuyangzhou fyi.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b840ed4145...db6605fec9

**Pull request closed without merging**
