### PR TITLE
LPS-66853

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
ci:retest

**Comment by jpince** [comment]
@hhuijser I don't see this error anywhere else
`     [exec] 11-Jan-2017 08:10:39.032 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class com.liferay.portal.spring.context.PortalContextLoaderListener`
`     [exec]  org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.liferay.document.library.kernel.util.DLFileVersionPolicy' defined in class path resource [META-INF/util-spring.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.liferay.document.library.kernel.service.DLFileEntryMetadataLocalService' defined in class path resource [META-INF/portal-spring.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.liferay.document.library.kernel.service.persistence.DLFileEntryMetadataPersistence' defined in class path resource [META-INF/portal-spring.xml]: Instantiation of bean failed; nested exception is java.lang.ExceptionInInitializerError`

**Comment by jpince** [comment]
ci:close

**Pull request closed without merging**
