### PR TITLE
Lps 79799

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@Preston-Crary can you resend this with a pull to 7.0.x since ServiceBuilder is not forked and I need to keep them in sync? (i.e. you're making changes to Layout*advice etc.)

**Pull request closed without merging**
