### PR TITLE
LPS-92446 Move generic code from asset display to info module

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @jorgeferrer

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/119a1deaaa...49f01eb6f2

**Comment by brianchandotcom** [comment]
@jorgeferrer this has className classPK for Info, not sure if that is right.. but I merged this.

**Comment by JorgeFerrer** [comment]
Thanks Brian.

This is fine, in fact I worked with Jürgen on this pull. While the Info framework has to be as agnostic as possible, we still need some way to refer to specific "things". We decided to try and use the className - classPK pattern for that, since it's pretty generic and is not necessarily tied to db objects. 

The main doubt is with classPK being a long. We might need to change that, but I prefer to go step by step, always starting from known and proofed patterns and make changes to them as we confirm that we must.

**Pull request closed without merging**
