### PR TITLE
LPS-167907 We are not caching fragments on display pages, before 4a565f60 we were using FragmentEntryLinkConstants.ASSET_DISPLAY_PAGE as mode, so the first "if" was returning false because the mode wasn't "view mode", see:

### PR DESCRIPTION
**Pull request by ealonso**
see: https://github.com/brianchandotcom/liferay-portal/pull/126087#issuecomment-1311003966

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d2ddade441...bc414f89ba

**Comment by brianchandotcom** [comment]
@ealonso can you send a follow up and sort

```
					if (_fragmentEntryProcessorHelper.isMappedDisplayPage(
							editableValueJSONObject)) {

						fieldId = editableValueJSONObject.getString(
							"mappedField");
					}
					else if (_fragmentEntryProcessorHelper.isMapped(
								editableValueJSONObject)) {

						fieldId = editableValueJSONObject.getString("fieldId");
					}
					else {
						fieldId = editableValueJSONObject.getString(
							"collectionFieldId");
					}
```

like I did with 0343a1f88ed9934cb86997b0ffcb652e0e6c47e5 if that's OK?

thx @ealonso

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/10244

**Pull request closed without merging**
