### PR TITLE
LPS-57562 SF - move logic to the backend

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Build 1-11 (504) failed most of functional tests.

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
@brianchandotcom @brianchiu can you help me with the errors? I suspect they might not be real failures....

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@juliocamarero 
There seem to be rebase errors. Could you update your branch? There were some UI changes that went in today as well that I would want to be included when we look at your branch.

CC @evannagayama @brianwulbern

**Comment by brianchandotcom** [comment]
@juliocamarero please resend. Thx.

**Pull request closed without merging**
