### PR TITLE
LPS-141045 Edit blueprint and element pages

### PR DESCRIPTION
**Pull request by thektan**
Adds in the edit blueprint and edit element jsp pages. 

A handful commits, but the first bunch are only adding in React components.

I'm also leaving the javascript test command disabled for now as the frontend will still be undergoing updates.

### CODE REVIEW

**Comment by thektan** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/dfefea33f2...33bc0fa985

**Comment by brianchandotcom** [comment]
@thektan This is beautiful. I wanted to cry.

Merged!

**Comment by brianchandotcom** [comment]
@oliv-yu thank you too!!!!

Sorry, just saw both your faces in the Git log.

@thektan cc

**Pull request closed without merging**
