### PR TITLE
LPS-120877 Discussion support for publications

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LPS-120877

`stable` and `relevant` pass in [this PR](https://github.com/Preston-Crary/liferay-portal/pull/1317#issuecomment-822756273), but `ci:forward` failed multiple times due to [LPS-130876](https://issues.liferay.com/browse/LPS-130876).

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@Preston-Crary can we fix

```
long commentId = ParamUtil.getLong(resourceRequest, "commentId");
```

and a few others in the *Command.java

Feel free to send it to me directly. Thx!

**Comment by Preston-Crary** [comment]
@stsquared99 please take care of the ParamUtil usages. Thanks!

**Comment by stsquared99** [comment]
Resent: https://github.com/brianchandotcom/liferay-portal/pull/100996

**Pull request closed without merging**
