### PR TITLE
LPS-96443 Use randomString instead of fixed name, since it's never checked

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
//cc @kyle-miho <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ruben-pulido** [comment]
//cc @ealonso <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/75fef62291...4a07beaa4a

**Comment by brianchandotcom** [comment]
Nice job guys.. @ruben-pulido @kyle-miho see 03ba5e47bce6900d5a8abef18e52a3ab6dc6cbdf

Type:

git grep _read\( **Test.java

That is used far more than _getFileContent (unless we manipulate the content before returning it)

**Pull request closed without merging**
