### PR TITLE
LPS-88440 Auto

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
cc: @brianchiu @kyle-miho

**Comment by jpince** [comment]
The ClassicTheme test is failing in upstream https://testray.liferay.com/home/-/testray/case_results/446143457/history?tab=result&hideFilterPin=true cc/ @john-co

**Comment by john-co** [comment]
Failure is unrelated to code changes. https://issues.liferay.com/browse/LRQA-45632 will fix the breaking test in upstream.

**Comment by john-co** [comment]
@brianchiu @kyle-miho
Looks like there was a new breadcrumb modification that is affecting how public pages are displayed. I discussed the issue with Kyle. I'll assign LRQA-45632 to WEM since the issue was caused by breadcrumbs change.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/35ba4e4d11...6b1157ad5f

**Pull request closed without merging**
