### PR TITLE
LPS-69949 Fix double escaping

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @adolfopa

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9b0c323479...bfa109dfe5

**Pull request closed without merging**
