### PR TITLE
LPS-70451 Lib portal jars to dependencies

### PR DESCRIPTION
**Pull request by tomwang2011**
CC @shuyangzhou

Hi Brian, this is the resend of https://github.com/brianchandotcom/liferay-portal/pull/47979 after fixing the SF errors, thanks!

### CODE REVIEW

**Comment by tomwang2011** [comment]
ci:reopen Not sure why CI source formatter failed here, there is no new line at the end of lib/versions.xml when looking at the changed files in this pull, thanks!

**Comment by brianchandotcom** [comment]
@tomwang2011 THere's still a CI SF error? Please resend.

**Comment by michaelhashimoto** [comment]
ci:reopen - @brianchandotcom it seems that this particular pull is related to an issue that QA Engineering is looking to resolve.  I looked at Tom's code, and it seems like the error mentioned in SF about ```</versions>``` is not caused by his code.

@pyoo47 @kenjiheigel

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by pyoo47** [comment]
@hhuijser This appears to be the same the source format problem that we've been experiencing in liferay-jenkins-ee.

**Comment by brianchandotcom** [comment]
ci:retest (I just pushed up a new SF)

**Comment by brianchandotcom** [comment]
@hhuijser I can't merge this because of an SF issue, but it only happens on CI and not locally. Can you fix SF for this issue? Thx.

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:stop

**Comment by kenjiheigel** [comment]
The last retest encountered the bug from SF version 1.0.379. This should be fixed in 1.0.380 (https://github.com/liferay/liferay-portal/commit/db45bedad6f1a301c89cd459c73735c610d32ef0). 

I'm retesting only the source-format batch here to save CI resources:
https://github.com/kenjiheigel/liferay-portal/pull/360

**Comment by brianchandotcom** [comment]
@kenjiheigel Going to merge this...

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0d5978311e...f152d90503

**Comment by kenjiheigel** [comment]
@brianchandotcom, just fyi source-format passed on kenjiheigel#360. I think Peter's update yesterday worked (https://github.com/brianchandotcom/liferay-portal/pull/48093/commits/5e78e5b60644d47ec03861ec42b3015921f70551).

**Pull request closed without merging**
