### PR TITLE
LRQA-21240 Update wiki page header

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey Brian,

This is a resend of https://github.com/brianchandotcom/liferay-portal/pull/34709#issuecomment-173405986

Thx!

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @sharonchoi @austinchiang @robertoDiaz

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9c6f1190d1...b4388add08

**Comment by brianchandotcom** [comment]
@sergiogonzalez @robertoDiaz kind of strange we have a "display.context.impl".. since this is the first one. Does it really need to be an "impl" since the packages are different from where it's used?

@sergiogonzalez can you resend without it? Thx.

**Pull request closed without merging**
