### PR TITLE
[TS] LPS-75264

### PR DESCRIPTION
**Pull request by arboliveira**
https://issues.liferay.com/browse/LPS-75264

/cc @ealonso

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:reopen

**Comment by arboliveira** [comment]
Unrelated `java.lang.AssertionError: [Parsing error: /tmp/KEI9Frxu/com/liferay/source/formatter/dependencies/AnnotationParameterImports.java] expected:<0> but was:<1>`

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/43fe198760...f794635211

**Pull request closed without merging**
