### PR TITLE
Lps 74772

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@Preston-Crary rebase error, please resend. Thx.

**Comment by Preston-Crary** [comment]
@lanceji92674957 please rebase this pull.

**Comment by shuyangzhou** [comment]
I just did it here https://github.com/brianchandotcom/liferay-portal/pull/52012

**Comment by lanceji92674957** [comment]
Thank you!

**Pull request closed without merging**
