### PR TITLE
LPD-25578 Avoid the cacheless DynamicQuery

### PR DESCRIPTION
**Pull request by shuyangzhou**
@tinatian @vicnate5 please backport for LXC, thanks!

@victorhcunha This is supposed to drop DB usages on all test cases too, please check.
Also I need the sql log profile for login test case with this fix, @slnn please guide @victorhcunha to do this, thanks!

### CODE REVIEW

**Comment by slnn** [comment]
Hi @victorhcunha

For tests, you can follow the steps in https://github.com/brianchandotcom/liferay-portal/pull/150234#issuecomment-2105458459

For SQL log, you can follow these:

**Steps to do sql log profile with benchmark tools on specific portal version**

1. Apply corresponding benchmark-ext.properties for specific test case in benchmark project (you can just apply the property file that you use to run daily performance testing)
2. Run ant clean-database clean-portal clean-grinder clean-sample reload-warmup-database all-sql-log

Please do SQL logs for Login on the baseline and this pull request.

By the way, the portal version for the test and sql log should be the same one, for example, if you pick version A as baseline to run test, also use it to do the sql log.

Lily

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0617a8858a...bb4295be84

**Comment by slnn** [comment]
Update from @victorhcunha:
The partial results have been updated in
https://docs.google.com/spreadsheets/d/1y74gSLgbOmaX9oLYrBbiQd0TEL9nEQ2sXpxvql6yY24/edit?usp=sharing

**Comment by victorhcunha** [comment]
Hi @shuyangzhou !
The results are available: [Benchmark Compare for LPD-25578](https://docs.google.com/spreadsheets/d/1y74gSLgbOmaX9oLYrBbiQd0TEL9nEQ2sXpxvql6yY24/edit#gid=409304089) (the results files are available in the spreadsheet too)

Please let me know if any other adjustments are needed.
cc @slnn

**Comment by shuyangzhou** [comment]
@victorhcunha @slnn why the tests are still using the old benchmark settings? check your portal-ext.properties, it still disables tons of stuff. We must test with out of box settings.

**Comment by victorhcunha** [comment]
Hi @shuyangzhou! Here are the new results:

**Login Testcase**
Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | DB CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | --
Baseline | 624ebc3 | 7854 | - | 261 | 9,10,9 | 87,88,85
PR | - | 8002 | 1.88439012 | 248 | 10,10,10 | 85,84,86

**DocumentLibrary Testcase**
Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | Mean Time of Add DL File | DB CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | -- | --
Baseline | 624ebc3 | 5833 | - | 90.6 | 134 | 7,7,7 | 55,57,58
PR | - | 5828 | -0.08571918395 | 91.2 | 134 | 7,7,7 | 54,55,59

**WebContent Testcase**
Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | Mean Time of View Page | DB CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | -- | --
Baseline | 624ebc3 | 10820 | - | 133 | 32.6 | 3,3,3 | 66,73,74
PR | - | 10829 | 0.0831792976 | 170 | 53 | 3,3,3 | 70,75,81

**AssertPublisher Testcase**
Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | Mean Time of View Page with Filter | DB CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | -- | --
Baseline | 624ebc3 | 6145 | - | 291 | 182 | 4,4,5 | 95,95,96
PR | - | 6029 | -1.887713588 | 305 | 187 | 4,4,5 | 95,95,94


More details you can check in this [google doc](https://docs.google.com/spreadsheets/d/1M6VK8GtY9kkv1EwhGW7vwrEENSzyT7zKz-wOh11ZHBo/edit#gid=1938286587) (with the files for SQL log)

cc @slnn

**Comment by shuyangzhou** [comment]
The sql log can confirm:
`2024-05-16T07:39:24.654059Z	    9 Query	select this_.accountEntryUserRelId as accounte1_2_0_, this_.mvccVersion as mvccvers2_2_0_, this_.companyId as companyi3_2_0_, this_.accountEntryId as accounte4_2_0_, this_.accountUserId as accountu5_2_0_ from AccountEntryUserRel this_ where this_.accountUserId=296`
is indeed removed.

But the profile snapshot is broken, both before/after is showing "CPU was not profiled" and nothing was recorded.

Please check and fix it. @victorhcunha  @slnn

**Comment by slnn** [comment]
OK, got it

**Comment by slnn** [comment]
Hi @shuyangzhou 

The cpu sampling issue has been fixed in https://github.com/dantewang/liferay-benchmark-ee/pull/719

By the way, I also checked for cpu tracing, memory profile, all of  them work well.

Lily

**Comment by victorhcunha** [comment]
Hi @shuyangzhou !
Here are the new sql logs for Login: [spreadsheet](https://docs.google.com/spreadsheets/d/1M6VK8GtY9kkv1EwhGW7vwrEENSzyT7zKz-wOh11ZHBo/edit#gid=1938286587)

When the [PR](https://github.com/dantewang/liferay-benchmark-ee/pull/719) is merged, I will add the SQL log record to the daily Login monitoring in our spreadsheet.

**Pull request closed without merging**
