### PR TITLE
[See description] LPS-58828 LPS-58833 LPS-58619 LPS-58840 Blogs Lexicon

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey Brian,

This pull has multiple LPS but all of them are related to applying Lexicon to blogs. I have assigned all the related tickets to you.

Thanks!
Sergio

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @natecavanaugh

**Comment by sergiogonzalez** [comment]
cc/ @sharonchoi @nikki-pru @austinchiang

This is the pull applying Lexicon to Blogs.

**Comment by brianchandotcom** [comment]
This pull is good. @sergiogonzalez I fixed those errors in another pull. I'll merge this in a bit.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d87025de54...dc98de4253

**Pull request closed without merging**
