### PR TITLE
LPS-59939 remove usage of Registry in journal

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
fyi @hhuijser (we are not done yet, but we made some progress :)

**Comment by juliocamarero** [comment]
ci:retest

**Comment by jkappler** [comment]
Please close, will resend

**Comment by brianchandotcom** [comment]
@jkappler @juliocamarero rebase error, please resend? Thx.

**Comment by juliocamarero** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/31731

**Pull request closed without merging**
