### PR TITLE
LPS-90058 Uses <liferay-ui:icon-menu since we cannot use <clay:dropdown-actions because of a performance issue with clay components

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
cc: @brianchiu @kyle-miho

**Comment by brianchiu** [comment]
@ealonso I'm going to close this one for now. I think we need to update the tests. We'll resend it.

**Comment by brianchiu** [comment]
ci:close

**Comment by brianchiu** [comment]
ci:test:bundle

**Comment by brianchiu** [comment]
ci:test:bundle

**Comment by brianchiu** [comment]
@ealonso Sorry. I'll have to finish this tomorrow. The updates for the tests are more complicated than I originally thought. Many tests use asset publisher.

**Pull request closed without merging**
