### PR TITLE
LPS-57746 always open Site Administration in the site itself [PING]

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
We can ignore that Oracle error. Reviewing now.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/45d218e32d...02ebf92282

**Comment by brianchandotcom** [comment]
@juliocamarero please see my changes in upstream. Thx.

**Comment by juliocamarero** [comment]
@ZoltanTakacs can we please backport this? thank you!

**Pull request closed without merging**
