### PR TITLE
LPS-85247 Resolved should work with the unauthenticated user

### PR DESCRIPTION
**Pull request by interaminense**
cc: @marcellustavares

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c84b19ff64...4740b8e74d

**Comment by brianchandotcom** [comment]
@interaminense @adolfopa please see my changes in upstream. Thx.

**Comment by brianchandotcom** [comment]
@interaminense please send me a backport to 7.0.x, with my changes. Thx!

**Comment by interaminense** [comment]
Right @brianchandotcom, I'll do this.

**Pull request closed without merging**
