### PR TITLE
LPS-99415 Rename

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3b89bd1613...ca59404773

**Comment by brianchandotcom** [comment]
@preston-crary I merged this.. but its usage of ConstraintViolationException worries me. Can you review? Thx.

**Comment by Preston-Crary** [comment]
@vendeltoreki please send through @achaparro.  It seems really weird that this is an upgrade ticket and we're modifying some StagedModelDataHandler to catch ConstraintViolationException.

I think we need to have a new upgrade so that customers who have already upgraded have their data fixed. Is that what the ConstraintViolationException thing is for?

If we already have this object we should update it instead of deleting and recreating it?  But we shouldn't even have to catch this exception here anyway if we fixed the customer's data.

**Comment by brianchandotcom** [comment]
@jkappler @vendeltoreki I reverted it based on recommendation by @Preston-Crary

**Pull request closed without merging**
