### PR TITLE
LPS-121078 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-121078

This is only for master.

@victorg1991
@p2kmgcl

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tasks are caused by bundle version and startTestableTomcat.
See https://github.com/liferay-echo/liferay-portal/pull/2386
✔️ ci:test:stable - 21 out of 21 jobs passed
❌ ci:test:relevant - 76 out of 79 jobs passed in 3 hours 37 minutes

**Comment by brianchandotcom** [comment]
@victorg1991 @p2kmgcl rebase error, please resend.

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/94365

**Pull request closed without merging**
