### PR TITLE
Pr liferay core infra 5522 lps 167246 9 11 1

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/667c699a2f...84132f47c9

**Comment by brianchandotcom** [comment]
@W2jx can we make

```
		_testDestination = new TestDestination(
			_destinationFactory.createDestination(
				new DestinationConfiguration(
					DestinationConfiguration.DESTINATION_TYPE_SYNCHRONOUS,
					DestinationNames.SUBSCRIPTION_SENDER)));

		_serviceRegistration = _bundleContext.registerService(
			Destination.class, _testDestination,
			HashMapDictionaryBuilder.<String, Object>put(
				"destination.name", DestinationNames.SUBSCRIPTION_SENDER
			).put(
				"service.ranking", Integer.MAX_VALUE
			).build());

		_ctCollection = _ctCollectionLocalService.addCTCollection(
			null, TestPropsValues.getCompanyId(), TestPropsValues.getUserId(),
			0, CTMessageBusInterceptorTest.class.getSimpleName(), null);
```

into

```
		_ctCollection = _ctCollectionLocalService.addCTCollection(
			null, TestPropsValues.getCompanyId(), TestPropsValues.getUserId(),
			0, CTMessageBusInterceptorTest.class.getSimpleName(), null);

		_testDestination = new TestDestination(
			_destinationFactory.createDestination(
				new DestinationConfiguration(
					DestinationConfiguration.DESTINATION_TYPE_SYNCHRONOUS,
					DestinationNames.SUBSCRIPTION_SENDER)));

		_serviceRegistration = _bundleContext.registerService(
			Destination.class, _testDestination,
			HashMapDictionaryBuilder.<String, Object>put(
				"destination.name", DestinationNames.SUBSCRIPTION_SENDER
			).put(
				"service.ranking", Integer.MAX_VALUE
			).build());
```

If so, please send me a PR direclty.

@shuyangzhou @dantewang fyi

**Comment by W2jx** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/140755

**Pull request closed without merging**
