### PR TITLE
LPS-87577 Use service instead of direct inserts to the table which belongs to another module

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by jpince** [comment]
ci:close @pavel-savinov semver `com.liferay.journal.service                        MINOR      2.4.0      2.4.0      2.5.0`

@brianchiu @kyle-miho please check functional test failures

**Comment by kyle-miho** [comment]
Looking at this right now.

**Comment by jpince** [comment]
@kyle-miho semver failure is in upstream, unrelated to this pull. please reopen if the functional tests are good.

**Comment by kyle-miho** [comment]
@pavel-savinov @vendeltoreki We need to be sure to use the correct classNameId when executing addAssetDisplayEntry(). I am pretty sure we are using the old classNameId, maybe this needs to be executed after we update the table of classNameIds? Or maybe it is some other issue. But this is breaking WC completely as we cannot load the correct WC template classes anymore.

2018-11-30 18:52:06.392 ERROR [http-nio-8080-exec-1][BasePersistenceImpl:264] Caught unexpected exception
java.lang.RuntimeException: Unable to get class name from id 28403
        at com.liferay.portal.util.PortalImpl.getClassName(PortalImpl.java:1595)
        at com.liferay.portal.kernel.util.PortalUtil.getClassName(PortalUtil.java:602)
        at com.liferay.dynamic.data.mapping.model.impl.DDMTemplateImpl.getResourceClassName(DDMTemplateImpl.java:75)
        at com.liferay.dynamic.data.mapping.model.impl.DDMTemplateModelImpl.toCacheModel(DDMTemplateModelImpl.java:1559

**Pull request closed without merging**
