### PR TITLE
LPS-45934

### PR DESCRIPTION
**Pull request by dsanz**
Brian,

I found LPS-63617 which made this one non mergeable. I'm resending, now I made it compatible with LPS-63617

Thx

### CODE REVIEW

**Comment by dsanz** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@dsanz can you resend? (Sorry, rebase error). Is there any way to simplify this pull? Thx.

**Comment by dsanz** [comment]
Hi Brian, I've made it more understandable, and rebased them to use try with resources.

This PR has 3 parts:
1. Add a micro framework to generate extra data for social activities
2. Change existing logic to use the fw, thus solving root cause
3. Add missing logic which did not exist before and it's needed

Do you want me to send 3 separate PRs and go one after another, or just send one?

Thx

**Pull request closed without merging**
