### PR TITLE
Shard Tool: move to its own folder hierarchy

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by mdelapenya** [comment]
Passing here: https://github.com/migue/liferay-portal/pull/666#issuecomment-183307472

**Comment by brianchandotcom** [comment]
@mdelapenya I think Mike wanted to rename it and remove the word Shard from it? Can you check with @mhan810

We also have the pattern com.liferay.portal.tools.* which this fits with (ServiceBuilder, UpgradeTable, WDSD etc...) I'm hesitant to move it to portal-shard because it makes me think it's a runtime thing now. It needs the package "tools" in there somewhere.

**Comment by mhan810** [comment]
@mdelapenya We have communicated to the market that we are removing "sharding" because we no longer need it and moving instead to "data-partitioning" so it will be very weird to have a "Shard Tool".  Can we call this Data Partition Tool?

@migue fyi

**Comment by mdelapenya** [comment]
Yes, @migues's pool has the right name

**Pull request closed without merging**
