### PR TITLE
LPS-103074 Autogenerated

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @brianchandotcom,

See my comment: https://github.com/brianchandotcom/liferay-portal/pull/79456#issuecomment-541722789. I applied all the changes but the rename. I can send the rename afterwards when we decide the best naming (today if I have time, otherwise tomorrow). 

Regardless of the rename, it would be awesome for us to have this PR merged so that we can start working on top of it tomorrow.

Thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4da5d97f89...0e5261a421

**Comment by brianchandotcom** [comment]
@4lejandrito see upstream for my changes (your latest pull didn't compile - *Test referenced old exception name)

**Comment by 4lejandrito** [comment]
Oops. Thank you @brianchandotcom!

**Pull request closed without merging**
