### PR TITLE
LPS-95225 Tracks Liferay portlet services rather than javax.portlet instances

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-95225](https://issues.liferay.com/browse/LPS-95225).<br><br>Hey Brian, this solves a race condition where multiple javax.portlet.Portlet trackers would call back in the wrong order. Only PortletTracker should track javax.portlet.Portlet instances, and every other tracker should track com.liferay.portal.kernel.model.Portlet.  That way there is a guarantee that all the portlet setup logic has run first, and in this case it guarantees that the portlet has been persisted to the Portlet table.

@hhuijser is it reasonable to add a SF rule for this?

/cc @pei-jung @stsquared99 @alee8888 @ChrisKian @dejuknow @ctampoya

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@preston-crary fyi on PortletTracker.

**Comment by hhuijser** [comment]
@drewbrokke what's the rule?
If a class implements `ServiceTrackerCustomizer` and `Portlet` is one of the generic types?

**Comment by drewbrokke** [comment]
@hhuijser that's correct, but specifically:
`com.liferay.portal.kernel.model.Portlet` is allowed
`javax.portlet.Portlet` is NOT allowed, except in `PortletTracker`

**Comment by hhuijser** [comment]
@drewbrokke should this be backported?

**Comment by drewbrokke** [comment]
@hhuijser do you mean should the SF rule be backported, or the changes in this pull?

**Comment by hhuijser** [comment]
@drewbrokke 
Should we only check for this on master or also check and fix any cases in other branches?

**Comment by drewbrokke** [comment]
Ah, I see.  I think it makes sense to check other branches.  Since we're backporting the fix on this one, we can backport the check also.

**Pull request closed without merging**
