### PR TITLE
master-bc-1043

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LRQA-20425

### CODE REVIEW

**Comment by brianchiu** [comment]
@brianchandotcom 
These failures are happening across the board right now and are happening as a result of [LPS-61367](https://issues.liferay.com/browse/LPS-61367). The failure is that the ellipsis is missing for items in tables.

However, the pull that Eudaldo sent for LPS-61367 didn't have these failures (See: https://github.com/brianchandotcom/liferay-portal/pull/33439)

So I think it may have been caused by your commit here: https://github.com/liferay/liferay-portal/commit/318a260a5cdab242c9d7d474b03ee91a34e9ec2c. I don't have time to verify that right now. But I was able to reproduce the issue on that commit and I was unable to reproduce the issue on the commit prior to the first commit for LPS-61367.

Here's how it ought to look:

how it should look

Here's how it looks after LPS-61367:

after lps-61367


CC @ealonso @kenjiheigel @anthony-chu

**Comment by brianchandotcom** [comment]
@brianchiu I rolled back my commit that broke it.

**Comment by brianchandotcom** [comment]
@brianchiu good job in identifying the problem and letting me know what to do. That was invaluable.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a5b9f2d379...1522796f5d

**Comment by brianchiu** [comment]
No problem =)

@kenjiheigel @anthony-chu also helped to figure it out.

**Pull request closed without merging**
