### PR TITLE
LPS-105625 Fallback to user's companyId in case when there is no service context set

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pavel-savinov see ServiceContext

	public Date getModifiedDate(Date defaultModifiedDate) {
		if (_modifiedDate != null) {
			return _modifiedDate;
		}
		else if (defaultModifiedDate != null) {
			return defaultModifiedDate;
		}

		return new Date();
	}

Can you add this logic to getCompanyId(long defaultCompanyId) 

I have a feeling we're going to be doing this a lot more in the future.

Please resend. Thx.

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by pavel-savinov** [comment]
Hi @brianchandotcom, we can't use the same approach with the company ID for this particular case. In this case, we want company ID to be 0 explicitly, to make those fragments available system-wide.

**Comment by brianchandotcom** [comment]
Merged. Thank you.

**Comment by brianchandotcom** [comment]
Ok @pavel-savinov you've established a new pattern I will enforce that everyone now follows.

See d6552fd8cb289a50fa9e373a64d4fdc5296acbda

**Pull request closed without merging**
