### PR TITLE
LPS-78379 SF - Rename methods

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by ealonso** [comment]
@carloslancha @jbalsas

**Comment by ealonso** [comment]
@anthony-chu

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:reopen

**Comment by anthony-chu** [comment]
@ealonso It looks like there are failures that are unique to this pull. Closing it to take a look at it, and will resend with necessary poshi changes.

**Comment by anthony-chu** [comment]
ci:close

**Pull request closed without merging**
