### PR TITLE
LPS-67752 Test for [$NULL_DATE$] placeholder

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @brianchandotcom 

About the `[$NULL_DATE$]` placeholder, I've talked with @migue about it and he thinks there's no other general solution cleaner than that.

For the test, I've tried to follow the patterns already in use (see SQLInstrTest in portal-impl). In the test method there are no assertions as the failure is triggered by an SQLException, so the contents of the ResultSet are not important.

Also, note that I've squashed all SF commits into one (76f8841).

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:retest

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest just to be safe

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@adolfopa unit still keeps breaking. SQL test. Please resend.

**Pull request closed without merging**
