### PR TITLE
LRQA-49768 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-49768

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:test:blogs

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@austinchiang rebase error, please resend? Thx.

**Comment by Hanlf** [comment]
@austinchiang ,
I sent a fix about it under https://issues.liferay.com/browse/LRQA-49715 yesterday, yeah, the same fix. And ran a ci tester about blog, looks good!

cc/ @patriciajeanperez

**Pull request closed without merging**
