### PR TITLE
LPS-102577 change to existing injected contexts

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e39c420501...6a5a4a02af

**Comment by brianchandotcom** [comment]
@nhpatt see d31d7274440f7d72a2fc8f26c74f0542b7282118 auto Sf removed what I thought was just generated....

see 1bcab453f0324474cd1361d0e218f513276c027d

I'm not fond of

String mediaType = contextHttpServletRequest.getHeader(HttpHeaders.CONTENT_TYPE);

Since it's called HttpHeaders.CONTENT_TYPE

But I'm also not found of:

	private String _getContentType(String contentType) {
		if (contentType.equals(MediaType.APPLICATION_JSON)) {
			return "json";
		}
		else if (contentType.equals("application/x-ndjson")) {
			return "jsonl";
		}
		else if (contentType.equals("text/csv")) {
			return "csv";
		}

		return contentType;
	}

Since it confuses what's going on. Can you rename the vars?

Thx.

**Comment by nhpatt** [comment]
Will do! 

The sf is wrong in that one, those are valid formats, shouldn't be deleted.

**Comment by nhpatt** [comment]
Sorry, sf is Ok, just deleted duplicated entries. Everything is Ok.

**Pull request closed without merging**
