### PR TITLE
LPS-77313 Consolidate UADExporter test logic

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @willnewbury

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by pei-jung** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5b0587e617...f08b940c85

**Pull request closed without merging**
