### PR TITLE
LPS-74457 Disable language keys check

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by brianwulbern** [comment]
@brianchandotcom can you please backport these commits to 7.0.x as well?  Thanks.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e0b96825e4...237d6ee752

**Pull request closed without merging**
