### PR TITLE
LPS-61860

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@brianchandotcom please don't close ticket, this is first part of commit

@juliocamarero see https://github.com/mhan810/liferay-portal/commit/d9dd7bad84e2aa8dd426a54c978331c3a3717a63 which removes dependency on internal impl classes

**Comment by juliocamarero** [comment]
Thanks @mhan810!

Mike, most of the ControlMenuEntries are now in their respective modules (not in control-menu-web anymore). Would it be possible to move this class to a module related to search that contributes this control menu entry?

**Comment by mhan810** [comment]
Sure, can you do that after the pull goes in or you want the search team to
do that?


We can perhaps move it to apps/search

**Comment by juliocamarero** [comment]
Yep, I can do that after your pull goes and I will send the pull to Andre.

**Comment by brianchandotcom** [comment]
@mhan810 test failure is a known random poshi failure. I'll merge this in.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/96e05adae0...78f8dc04a3

**Comment by brianchandotcom** [comment]
@juliocamarero can you make the control menu change like you said. This is in upstream now. Thx bro.

**Comment by juliocamarero** [comment]
@mhan810 @brianchandotcom done! https://github.com/arboliveira/liferay-portal/pull/81

**Pull request closed without merging**
