### PR TITLE
Lps 98796

### PR DESCRIPTION
**Pull request by shuyangzhou**
@petershin @gamerson the back end support for jsp overwrite is complete now, we will move on to the js and css part.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2782d7f871...9a57217732

**Comment by brianchandotcom** [comment]
@shuyangzhou @mtambara Please review my changes in upstream. Backported to 7.2.x.

@mtambara I need your help with 7.1.x and 7.0.x for the backports.

**Comment by mtambara** [comment]
7.1.x sent here: https://github.com/brianchandotcom/liferay-portal-ee/pull/25752

**Comment by mtambara** [comment]
7.0.x sent here: https://github.com/brianchandotcom/liferay-portal-ee/pull/25756

**Pull request closed without merging**
