### PR TITLE
LRQA-22944 Reference the 'ee-7.0.x' branch

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRQA-22944

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:stop (will redo this when jenkins-ee change is done)

**Comment by michaelhashimoto** [comment]
ci:stop

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by kenjiheigel** [comment]
Failure is unrelated and has been failing multiple pulls. 
https://testray.liferay.com/home/-/testray/case_results/40139533

Test has been disabled at head:
https://github.com/liferay/liferay-portal/commit/6fd2f8414f4f928fde477715966fafed67534f87

WEM QA will look into the issue and restore the test [LRQA-24557](https://issues.liferay.com/browse/LRQA-24557).

**Pull request closed without merging**
