### PR TITLE
LPS-56819 Update DTD

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@marcellustavares I merged this in, but

PortletLocalServiceImpl still has

```
		portletModel.setDDMDisplayClass(
			GetterUtil.getString(
				portletElement.elementText("ddm-display"),
				portletModel.getDDMDisplayClass()));

```

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/38ffd4a997...3c8b1ad2f0

**Comment by marcellustavares** [comment]
I missed this @brianchandotcom, will send you the fix rt now.

Thx

**Pull request closed without merging**
