### PR TITLE
LPS-62342 Simplify markup by not using app-view-entry and remove unnecessary css class.

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pyoo47 happened here too (the random JSON error)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f18685dddb...067125d832

**Pull request closed without merging**
