### PR TITLE
LPS-58563 move modules into product navigation (no changes)

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@michaelhashimoto the ORACLE_HOME issue is happening again.

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
@shuyangzhou - okay it should be fixed again. thanks!

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b4603a3951...e65e578957

**Pull request closed without merging**
