### PR TITLE
LPS-81561 Fix test

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@jpince fyi

**Comment by jpince** [comment]
@zoltancsaszi @adolfopa make sure to look for the @ignore when fixing a test... that way the test will actually run in ci:test:relevant. See https://github.com/brianchandotcom/liferay-portal/pull/65766.

**Pull request closed without merging**
