### PR TITLE
COMMERCE-12157

### PR DESCRIPTION
**Pull request by ghost**
resend on top
https://github.com/CrescenzoRegaLF/liferay-portal/pull/26#issuecomment-1725491693

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:reopn

**Comment by CrescenzoRegaLF** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8489378312...9c7c8635ed

**Comment by brianchandotcom** [comment]
@CrescenzoRegaLF see changes in my origin. Thx.

**Pull request closed without merging**
