### PR TITLE
LPS-56601 - Source formatting

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brunobasto** [comment]
Hey @brianchandotcom, this pull request is 100% JavaScript and CSS. The only thing the CI could catch would be source formatting errors from Nate's check-source-format, but Nate already reviewed.

Just so that you don't worry about it breaking the back-end tests

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1eb49fd44c...36b6acbd97

**Comment by brianchandotcom** [comment]
Thx @brunobasto for the info!

**Comment by brunobasto** [comment]
No problem! :)

**Pull request closed without merging**
