### PR TITLE
LPS-176815 Get parents' info field set

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:reopen

**Comment by MarinhoFeliphe** [comment]
ci:close

**Comment by MarinhoFeliphe** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c832c57951...30d65e7d44

**Pull request closed without merging**
