### PR TITLE
LPS-143422 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-143422

This is only for master.

@ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tasks are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/6609
❌ ci:test:stable - 10 out of 11 jobs passed
❌ ci:test:relevant - 26 out of 34 jobs passed in 1 hour 46 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4a41439a0d...aa94657780

**Comment by brianchandotcom** [comment]
Thx @ealonso just aa94657780105dedc884715511f5edb290c0430c

**Pull request closed without merging**
