### PR TITLE
LPS-102820 Rename to reflect the meaning because LayoutTemplate is a different entity

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
Hey @kyle-miho, please let us know if there are some POSHI-tests we want to change for this pull. Relevant tests passed [here](https://github.com/kyle-miho/liferay-portal/pull/243) so there should be no problems, but just in case. Thanks.

/cc @ealonso

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
ci:close

**Comment by kyle-miho** [comment]
ci:stop

**Comment by kyle-miho** [comment]
Testing this pull on my branch, ci:test:relevant is not always accurate

**Pull request closed without merging**
