### PR TITLE
LPD-19869

### PR DESCRIPTION
**Pull request by tinatian**
FYI @shuyangzhou, Add a new StopWatch to petra-lang according to BChan's requirement at https://github.com/brianchandotcom/liferay-portal/pull/148137#issuecomment-1996545397

### CODE REVIEW

**Comment by tinatian** [comment]
ci:report

**Comment by tinatian** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
Just use the time as long, no need to create another stop watch class for it.

**Comment by shuyangzhou** [comment]
ci:close

**Comment by shuyangzhou** [comment]
@brianchandotcom the StopWatch class has no reason to exist, it is literally just a long with basic "-" operation, we prefer to not carry on this unnecessary baggage.

**Pull request closed without merging**
