### PR TITLE
LPS-65493 Add success message for update structure and add/update template

### PR DESCRIPTION
**Pull request by rafaprax**
/cc @linolaoj @marcellustavares

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3b69a88c16...91ca56af13

**Comment by evannagayama** [comment]
@rafaprax @linolaoj  I believe this pr cause this issue: https://issues.liferay.com/browse/LPS-65873. Could you please take a look at it. Thanks!

**Comment by rafaprax** [comment]
@evannagayama I fix https://issues.liferay.com/browse/LPS-65873 in https://github.com/brianchandotcom/liferay-portal/pull/39821. Thx

**Comment by evannagayama** [comment]
@rafaprax thanks!

**Pull request closed without merging**
