### PR TITLE
LPS-206312 The order is important here. If this be sorted, some properties will be overrided and the fix won't work

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-206312

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:reopen

**Comment by p-albuquerque** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/146381

**Comment by p-albuquerque** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6de60d75df...0c5053a2eb

**Pull request closed without merging**
