### PR TITLE
LPS-84125 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-84125

### CODE REVIEW

**Comment by kyle-miho** [comment]
./cc @jpince @ealonso @brianchiu

**Comment by kyle-miho** [comment]
tested here: https://github.com/kyle-miho/liferay-portal/pull/86

**Comment by brianchandotcom** [comment]
@ealonso since we're in Journal, all references to "structure" ought to be DDMStructure. Currently, service.xml has DDMStructureKey.. not structureId. So if we add "structure", we must prefix it everywhere it's used in Journal (so copy_structure, needs to be copy_ddm_structure, etc..) Please resend. Thx.

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
