### PR TITLE
LPS-184802 Revert breaking changes from SF

### PR DESCRIPTION
**Pull request by ryanschuhler**

### CODE REVIEW

**Comment by ryanschuhler** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@ryanschuhler you and @bryceosterhaus keep clobbering each other on this.

@bryceosterhaus can you review?

**Comment by ryanschuhler** [comment]
ci:reopen

**Comment by ryanschuhler** [comment]
Discussed with Bryce and said we are good to revert these changes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/70decd0291...929659a13d

**Pull request closed without merging**
