### PR TITLE
Lps 66013

### PR DESCRIPTION
**Pull request by CAustin582**

### CODE REVIEW

**Comment by CAustin582** [comment]
ci:retest

**Comment by CAustin582** [comment]
@brianchandotcom this is the same as https://github.com/brianchandotcom/liferay-portal/pull/40807 except with another commit added to fix the previous issues.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/58711b7369...27a366ae37

**Pull request closed without merging**
