### PR TITLE
LPS-63462 We can't use MetaType's translation system

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
Hey @brianchandotcom, 

here you have the pull... but it might break tests until the rest is merged

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0d3497e916...3b31684093

**Comment by brianchandotcom** [comment]
@hhuijser can you SF enforce this?

Thx!

**Comment by hhuijser** [comment]
Hey @csierra 

What exactly is the rule for this?
You mention we should use latin-1 encoding or am I interpreting your comment message wrong?
% is part of the latin-1 character set: https://en.wikipedia.org/wiki/ISO/IEC_8859-1

**Comment by csierra** [comment]
Hey @hhuijser, 

maybe I did not explain the issue properly. 

When using the `%` character in _MetaType's_ `name` or `description` fields, as the first character, it triggers _MetaType's_ translation system so it is _MetaType_, and not Liferay, who translates the keys. This does so using OSGi _standard_ internationalization system, which uses Java default properties encoding, which is Latin. Initially we relied on this but, since we use UTF-8, we can't use the same bundles for Liferay and for MetaType. 
Furthermore, the only contribution mechanism in OSGi standard for bundles is using fragments, so it was not possible for the modules to share keys with the portal. This is why we resorted to abandon _MetaType's_ localization system, even though our bundles are not going to be portable, and use our system. 

Bests.

**Comment by hhuijser** [comment]
@csierra 

Thanks for the clear explanation!
I can add that to SF

**Pull request closed without merging**
