### PR TITLE
LPS-83991 Portlet 3.0: Develop the bean portlet API

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by jpince** [comment]
passed tests (with 100% green!) here: https://github.com/shuyangzhou/liferay-portal/pull/6531#issuecomment-409055273

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c90c0dc85a...ca8cb4f7a7

**Comment by brianchandotcom** [comment]
@shuyangzhou @ngriffin7a published the jar for you.

**Comment by ngriffin7a** [comment]
@brianchandotcom Thank you for publishing the jar! :)

**Pull request closed without merging**
