### PR TITLE
LPS-103255 Buildlang

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/59d82c2477...15865dd6b8

**Comment by brianchandotcom** [comment]
@pavel-savinov sort 15865dd

@wincent @hhuijser can we enforce 15865dd ? Thx.

**Comment by brianchandotcom** [comment]
@pavel-savinov see 15865dd6b8e3c90b797880da56343d331c1faf60 @wincent @hhuijser can we enforce 15865dd6b8e3c90b797880da56343d331c1faf60 (I pushed a proper link now)

**Comment by wincent** [comment]
@brianchandotcom: Yes, we should be able to do that with ESLint. I created this ticket to track the implementation: https://github.com/liferay/eslint-config-liferay/issues/108

**Pull request closed without merging**
