### PR TITLE
[TS] LPS-81949 User Group settings do not update from Instance Settings, only after Reindex.

### PR DESCRIPTION
**Pull request by drewbrokke**
https://issues.liferay.com/browse/LPS-81949

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@NorbertKocsis is the bug that we have to call reindex after calling addDefaultGroups?

Or only after calling addDefaultGroups, addDefaultRoles, and addDefaultUserGroups?

If it's after calling each one, we should move the reindex logic into UserLocalServiceImpl.

We end up regenerating 3 times, but we never know if any of the methods may be called only by itself (someone may just call addDefaultGroups and need to reindex, so the fix to reindex should go in addDefaultGroups)

Or, we can make a new method, that does all 3 things, and reindexes afterward.

In any case, I merged in your fix, but it feels wrong.

```
				UserLocalServiceUtil.addDefaultGroups(userId);
				UserLocalServiceUtil.addDefaultRoles(userId);
				UserLocalServiceUtil.addDefaultUserGroups(userId);

				Indexer userIndexer = IndexerRegistryUtil.getIndexer(
					User.class.getName());

				userIndexer.reindex(User.class.getName(), userId);
```

**Comment by NorbertKocsis** [comment]
I was hesitating myself too, but I didn’t want to do a reindex 3 times :s However it’s needed in both cases as neither of those methods trigger a reindex. But I thougth its better this way and we should just pay attention to reindex because at user crearion it would mean 4 reindexes... I don’t like that.

Br,
Norbert

**Comment by NorbertKocsis** [comment]
Also it wouldn’t look nice as thos methods doesn’t return the user so we couldn’t just annotate them.

Br,
Norbert

**Pull request closed without merging**
