### PR TITLE
LPS-108724 Adds missing source format surpression for new petra module

### PR DESCRIPTION
**Pull request by jkappler**
Hey @brianchandotcom, the supression for the check was missing. I added it. Let us know if it's okay. Thanks!

### CODE REVIEW

**Comment by jkappler** [comment]
@ruben-pulido, @ealonso

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/94062a6ada...7935d0fb93

**Comment by brianchandotcom** [comment]
@ruben-pulido beautiful! Can you add a task to backport this to 7.2.x and 7.1.x after 7.3 GA2 is released?

This will be helfpul. Thx!

**Comment by ruben-pulido** [comment]
Tasks created:
https://issues.liferay.com/browse/LPS-108840
https://issues.liferay.com/browse/LPS-108839

**Pull request closed without merging**
