### PR TITLE
LPS-105179 Update resource implementation

### PR DESCRIPTION
**Pull request by rafaprax**
/cc @inacionery

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@rafaprax please fix

junit.framework.AssertionFailedError: 
Duplicate entry '20096-com.liferay.portal.workflow.kaleo.designer-4-com.liferay.p' for key 'IX_A9FF4B2C'
	at com.liferay.portal.log.assertor.PortalLogAssertorTest.scanXMLLogFile(PortalLogAssertorTest.java:172)
	

and resend.

**Comment by rafaprax** [comment]
Hey @brianchandotcom,

I took a look and this is an intermittent failure that occurs on some prs with other components as well.  I tried reproduce this locally but I could not. Here is a list with same failure in others prs.

- https://github.com/brianchandotcom/liferay-portal/pull/80978#issuecomment-554002759
- https://github.com/brianchandotcom/liferay-portal/pull/80813#issuecomment-552492436
- https://github.com/brianchandotcom/liferay-portal/pull/80654#issuecomment-551253098

Thx

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@rafaprax @inacionery we still need to fix the test...

Please spend 1 day or 2 fixing it and resend this to me. That bug has been open too long.

**Comment by inacionery** [comment]
Hey @Preston-Crary

Could you please give us any tips on what could be causing this error?

Thanks!

**Comment by Preston-Crary** [comment]
@shuyangzhou looks like this is a random test failure maybe related to the retry advice?  Do we need to suppress the logs somehow on the CI?

**Pull request closed without merging**
