### PR TITLE
LPS-103574 render only the active page in tabbed mode to prevent components from being destroyed

### PR DESCRIPTION
**Pull request by matuzalemsteles**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@matuzalemsteles if you have to add so many

eslint-disable-next-line react/no-string-refs

Something is wrong...

Please talk to @jbalsa @wincent and do this the right way

@brunofarache fyi

**Comment by matuzalemsteles** [comment]
@brianchandotcom the `eslint-disable-next-line react/no-string-refs` rules do not apply to Metal.js applications. As I did not want to disable this rule throughout the module this was the most viable solution. as it is likely that in the future we will have more React components in this module.

@wincent Let me know if we have any other solutions.

**Comment by wincent** [comment]
We only need suppressions like these in modules which use a *mix* of Metal and React, so I expect these to be temporary (like @matuzalemsteles says, Metal usage will go down, React usage will go up).

It's good to make suppressions as narrow as possible (so as not to accidentally suppress actual errors), but in this case, I'd recommend doing file-level suppressions instead of line-level suppressions. We're never going to have a mix of React and Metal in the same file, after all. So for example, in this PR instead of having 9 `eslint-disable-next-line` suppressions, you could have 4 `eslint-disable` suppressions at the file level.

If we still consider this to be too much noise, we have some options:

- We could turn off the rule entirely (at the expense of safety).
- We could fork the rule and make a custom version of it that doesn't warn unless React is in scope (at the expense of engineering work); but I don't think that would be very hard to do — I'm going to add a comment to https://github.com/liferay/eslint-config-liferay/issues/107 suggesting that we consider doing this (that issue is about making the "React" preset the default across all of liferay-portal).

**Comment by matuzalemsteles** [comment]
Thanks @wincent for the explanations, I'll send another PR to Brian by adding `eslint-disable` to the file level of these files to reduce noise.

**Pull request closed without merging**
