### PR TITLE
LPS-65133 No point to manually clean up session attribute, as session…

### PR DESCRIPTION
**Pull request by shuyangzhou**
… is destroying all attributes will be cleared.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/32a439e24e...8b3a0f4e88

**Comment by sharonchoi** [comment]
@vicnate5 some calendar/workflow poshi failures

**Comment by vicnate5** [comment]
@sharonchoi my team is looking into these. Thanks!

**Comment by vicnate5** [comment]
@brandizzi The Calendar tests are now failing if they are run between 10pm and 11pm because of https://issues.liferay.com/browse/LPS-65154

**Pull request closed without merging**
