### PR TITLE
LPS-50675 Use the Log Executor propertly

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
1) Sorry Brian, I broke it during rebase :(. Now it is fixed.

2) The difference between those clases is that the *Arquillian classes use the Arquillian events, not static calls. If we use static calls instead of events, it is more complicated to replace this behaviour in other extensions.

@csierra

**Comment by brianchandotcom** [comment]
Hey @cgoncas 

I merged this in, but I would like to move Log*Arquillian to its own package underneath internal.log or something.. to show that they are of the same time. Also, one is called "*InArquillian" and the other is "Arquillian" I still find it confusing because I'm expecting the object type to be Arquillian, but it's not. It's  "AppenderSkeleton" for example.

Can you send me another pull to refactor that package to make it cleaner? In any case. I merged it and published it.

**Comment by brianchandotcom** [comment]
I also did make some tiny changes, please review.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/79de88d20b...3c88bef1e7

**Pull request closed without merging**
