### PR TITLE
LPS-77886 Update resources copied into jar file

### PR DESCRIPTION
**Pull request by petershin**
@igorbeslic @jpince @hhuijser

### CODE REVIEW

**Comment by petershin** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@jbalsas this jspc error was you I think....

fixing in usptream.

**Comment by brianchandotcom** [comment]
@jbalsas see 68c2641b546946525b24f8be36cb63c4a1323d80

**Comment by brianchandotcom** [comment]
@ptershin not merging.. I'm not able to publish SF now, see https://github.com/brianchandotcom/liferay-portal/pull/55227

**Comment by jbalsas** [comment]
Thx, @brianchandotcom, sorry about that!

**Comment by jbalsas** [comment]
I think it's also in the `shopping-web` one and causing CI issues. I'll send a PR fixing it. Why isn't 1.8 the default by now?

**Comment by jbalsas** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/55246

**Pull request closed without merging**
