### PR TITLE
LPS-83339

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/99f7fc963f...901f4d0a7b

**Comment by brianchandotcom** [comment]
@adolfopa I merged the first few commits of this pull, but then stopped because this looks very wrong:

```
		Class<? extends ModelResourcePermission> clazz =
			_modelResourcePermission.getClass();

		try {
			Field field = clazz.getDeclaredField(
				"_modelResourcePermissionLogics");

			field.setAccessible(true);

			List<ModelResourcePermissionLogic> modelResourcePermissionLogics =
				(List<ModelResourcePermissionLogic>)field.get(
					_modelResourcePermission);

			modelResourcePermissionLogics.add(0, _modelResourcePermissionLogic);
		}
		catch (IllegalAccessException | NoSuchFieldException e) {
			_log.error(
				"Unable to include sharing permission check for DLFileEntry");
		}
```

@Preston-Crary can you guys work this out so we don't use reflection?

See modules/apps/sharing/sharing-document-library/src/main/java/com/liferay/sharing/document/library/internal/security/permission/resource/SharingEntryDLFileEntryModelResourcePermissionRegistrar.java @Preston-Crary

**Comment by Preston-Crary** [comment]
@adolfopa just publish a new ModelResourcePermission with a higher service ranking and delegate to the old ModelResourcePermission.  Send me an email if you run into problems doing that.

**Comment by sergiogonzalez** [comment]
Hey @Preston-Crary 
That was our initial approach, but if we do that there are lot of places in Liferay where we're using `@Reference` and, since those references are already satisfied, they won't use the new ModelResourcePermission since they are not dynamic/greedy. We would need to change everywhere where those modelResourcePermission are being injected. Is there anything we can do to avoid this?

**Comment by Preston-Crary** [comment]
@brianchandotcom @sergiogonzalez I think that anywhere we think we are holding a reference a customer would want to override should be changed to dynamic greedy.  Otherwise we say everything has extension points through OSGi but in reality the only way to get it to work is refreshing the bundles that we want to be updated by the changed after deploying the replacement service.  The only work around I know is to update the bundle or change the API to instead track the logic classes.

**Pull request closed without merging**
