### PR TITLE
LPS-87867 Add mapping for boolean

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by jpince** [comment]
@epgarcia these two tests are still failing:
SegmentsEntryProviderTest.testGetSegmentsEntryClassPKsWithMultipleCriterion
SegmentsEntryProviderTest.testGetSegmentsEntryIdsWithMultipleCriterion
```
     [exec] com.liferay.segments.provider.test.SegmentsEntryProviderTest > testGetSegmentsEntryClassPKsWithMultipleCriterion FAILED
     [exec]     com.liferay.portal.kernel.exception.PortalException: Unable to retrieve users count: Unknown property.
     [exec]         at com.liferay.segments.internal.odata.retriever.UserODataRetriever.getResultsCount(UserODataRetriever.java:143)
     [exec]         at com.liferay.segments.internal.provider.SegmentsEntryProviderImpl.getSegmentsEntryClassPKsCount(SegmentsEntryProviderImpl.java:125)
     [exec]         at com.liferay.segments.provider.test.SegmentsEntryProviderTest.testGetSegmentsEntryClassPKsWithMultipleCriterion(SegmentsEntryProviderTest.java:97)
```
https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/259566/AXIS_VARIABLE=0,label_exp=!master/consoleFull
Not sure if this will be fixed by https://github.com/brianchandotcom/liferay-portal/pull/65442

**Comment by jpince** [comment]
The same test are failing in https://github.com/brianchandotcom/liferay-portal/pull/65452.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by epgarcia** [comment]
@jpince We think that those errors should be fixed by #65442. If they still occur, please let us know and we will send a first PR ignoring them and a second with the fix. Thanks!
@darquesdev

**Comment by epgarcia** [comment]
@jpince Please see #65502

Regards

**Pull request closed without merging**
