### PR TITLE
LPS-65012

### PR DESCRIPTION
**Pull request by Ithildir**
Hi,
Please let this pull finish!

Thank you!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d25a3fd815...d7fee9c317

**Comment by brianchandotcom** [comment]
@Ithildir can you make the build fail if bnd finds these errors? Don't let it just warn us but fail them? I assume that's how you found them (from bnd warnings?)

**Comment by Ithildir** [comment]
No, Bnd doesn't even throw warnings, maybe there are cases where it makes sense to export empty packages... @rotty3000, what do you think about it?

**Comment by rotty3000** [comment]
depends what you mean by empty packages?

**Comment by rotty3000** [comment]
a package with only resources is probably still a valid export.

**Comment by Ithildir** [comment]
No, I mean a package that has no Java classes or resources.

**Comment by rotty3000** [comment]
Can you tell who is causing it to be exported? Was it accidentally done by a developer? Or did an automated process cause it to be exported?

**Comment by Ithildir** [comment]
I think they are all developer mistakes while writing the `bnd.bnd`:
* sometimes they're packages that don't exist (anymore?): for example, https://github.com/brianchandotcom/liferay-portal/pull/40153/commits/8fc1c674257584e9db626cd891c25fd7d7e2da76#diff-d1d977fcbeab926aa5858536b8da61f3L6
* sometimes they exported the main package of the module, plus one or more child packages; but the main package does not have Java or resource files, only child packages: for example, https://github.com/brianchandotcom/liferay-portal/pull/40153/commits/8fc1c674257584e9db626cd891c25fd7d7e2da76#diff-dd363b2876a464f989ba71ce6c844ee3L5

**Comment by rotty3000** [comment]
Then I guess it would be fine to automate the check... but I think bnd
already contains such a check.

Ironically it's called:

-check

You use it like

- check: ALL # options are ALL, IMPORTS, EXPORTS

with that, exporting an empty package will result in an error.

**Comment by Ithildir** [comment]
Great! :smile: I can change `gradle-plugins` and add it to the Bnd instructions.

**Pull request closed without merging**
