### PR TITLE
LPS-144003 Fix broken docs path in learn-resources

### PR DESCRIPTION
**Pull request by jrhoun**

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:reopen

**Comment by susanchen3** [comment]
Hi Brian, this should fix a failing test on Acceptance Analysis. Thanks! :D
https://testray.liferay.com/home/-/testray/case_results/1593419328

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/56729a1530...a2325e3d55

**Comment by brianchandotcom** [comment]
@susanchen3 @jrhoun done, and I updated S3

**Pull request closed without merging**
