### PR TITLE
LRQA-51588 SF

### PR DESCRIPTION
**Pull request by alexcandidos**

### CODE REVIEW

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated

ContentPagesWithStaging#PublishContentPage is a unique failure but I don't see how the commits could be related to this failure. The changes are only adding code for a new poshi testcase for App Builder.

**Comment by alexcandidos** [comment]
Thanks for the double-check @john-co ! :)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/78b5898ccd...619a17821e

**Comment by brianchandotcom** [comment]
@alexcandidos all of your appbuilder tests should be in modules/apps/app-builder

Please move them out of portal-web

@vicnate5 please show them how. Thx

**Comment by brianchandotcom** [comment]
@alexcandidos see LRQA-52098 and LRQA-52073

I asked @patriciajeanperez to do the same thing recently.

**Comment by alexcandidos** [comment]
Thanks @brianchandotcom ! Hey @vicnate5, I just sent you a PR https://github.com/vicnate5/liferay-portal/pull/1282, could you please double-check?

**Pull request closed without merging**
