### PR TITLE
LPS-69406 | master

### PR DESCRIPTION
**Pull request by jpince**
https://issues.liferay.com/browse/LPS-69406

@matethurzo I'm assuming that git-lpush checks the code one commit at a time (instead of everything at once), so that's why it didn't like your second try. I used fixup to put the two commits together, hopefully that is acceptable to you, @zoltancsaszi, and CI!

reference: https://github.com/brianchandotcom/liferay-portal/pull/52171

@stsquared99 can lpush check everything at once? In the last pull (52171), Mate added a commit to remove a change to a sub repo, but it was still rejected. Or is it something else?

### CODE REVIEW

**Comment by stsquared99** [comment]
@jpince No, the files can't be touched at all, it interferes with the syncing mechanism.
Thanks

**Comment by jpince** [comment]
@stsquared99 thanks

@matethurzo @zoltancsaszi I also sent the workflow portion to their sub repo: https://github.com/liferay/com-liferay-portal-workflow/pull/199

**Comment by matethurzo** [comment]
thanks @jpince I figured that's the case wanted to send it but you saved me some time thx!

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
@matethurzo happy to help :)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/dbb78f9ad7...1fbd1c376c

**Pull request closed without merging**
