### PR TITLE
LPS-53578 don't show borders for embedded portlets

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
@juliocamarero are you sure this has the correct LPS ticket associated with it?

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@juliocamarero please resend since @rotty3000 wasn't sure if the LPS was correct, and you had a minor SF. I would have fixed the SF for you, but I want to make sure this is the right LPS. Thx.

**Comment by rotty3000** [comment]
Hey @juliocamarero did you see this? I wouldn't want you to forget.

**Comment by juliocamarero** [comment]
Sure, it's here now: https://github.com/brianchandotcom/liferay-portal/pull/24987

thanks a lot Ray! :+1:

**Pull request closed without merging**
