### PR TITLE
LPS-71771 User Facet Portlet

### PR DESCRIPTION
**Pull request by arboliveira**
Authors: @linolaoj @arboliveira
Reviewer: @arboliveira

cc/ @mhan810

https://issues.liferay.com/browse/LPS-71771

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest @pyoo47 ?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/24d263166b...360e4a46f4

**Comment by brianchandotcom** [comment]
Merged.

@arboliveira Suggestion, can you rename "paramName" and "paramValue" to "parameterName" "parameterValue"?

Thx.

**Comment by arboliveira** [comment]
Thanks! Will do. Just avoiding changing code of classic Search Portlet in the same pull requests that introduce the new Search Portlets, but already using the "parameter*" convention in them.

**Pull request closed without merging**
