### PR TITLE
LPS-74544 Format '.npmbridgerc' files

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by jpince** [comment]
@petershin are those SF failures at head?

**Comment by petershin** [comment]
@jpince - Hugo fixed these issues last night:

https://github.com/liferay/liferay-portal-ee/commit/7a96d052a4fc0e3b3fd7a89e081c04c32387f6f1
https://github.com/liferay/liferay-portal-ee/commit/107998352228647c7ab89873352981e61d4b1899

**Comment by jpince** [comment]
@petershin ok, didn't notice those were all for private modules. Brian probably just needs to update git-commit-portal-private, then.

**Pull request closed without merging**
