### PR TITLE
[7.1] LPS-82593 SF

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @brianchandotcom, this is an important fix for the layout feature in IE11, necessary for 7.1.

Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:reopen

**Comment by kyle-miho** [comment]
@jbalsas The failures caused due to upstream error, I am going to re-run the tests

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
