### PR TITLE
LPS-98656

### PR DESCRIPTION
**Pull request by danielkocsis**

### CODE REVIEW

**Comment by danielkocsis** [comment]
ci:test:change-tracking

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/678e3608b3...d83e7e31c1

**Comment by jpince** [comment]
@xbrianlee @joshchong it looks like neither relevant nor ci:test:change-tracking ran any POSHI tests.
relevant - no `test.properties` file in the change-tracking dir
ci:test:change-tracking - query looks ok in [test.properties](https://github.com/liferay/liferay-portal/blob/master/test.properties#L1562)

I'm interested because running POSHI tests in this PR might have caught https://issues.liferay.com/browse/LPS-98800

**Comment by joshchong** [comment]
@jpince thanks for catching this. [The functional batch wasn't included](https://github.com/liferay/liferay-portal/blob/4006e0bf7d5a181090f808f97b2ac9d8f2066a9d/test.properties#L1553-L1560) in that suite for some reason. [Created a ticket to add it in](https://issues.liferay.com/browse/LRQA-50986).

**Pull request closed without merging**
