### PR TITLE
LPS-60172

### PR DESCRIPTION
**Pull request by Ithildir**
Hi!

Could you please publish the new `css-builder`, `gradle-plugins-css-builder` and `gradle-plugins`?

Thank you! :blush:

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e08b86ee47...d944f625a5

**Comment by brianchandotcom** [comment]
Published new jars.

**Comment by brianchandotcom** [comment]
@david-truong can you sort this:

modules/util/css-builder/src/test/resources/com/liferay/css/builder/dependencies/css/test.css

```
	padding-left: 0px;
	padding-right: 1px;
	text-align:left;
	line-height: $val;
```

All the attyributes were alphabetized until you added this new one. Kind of dirty now.

I merged it in for the sake of time, but please send a follow up pull. Thx!

**Comment by david-truong** [comment]
tests fixed here: https://github.com/brianchandotcom/liferay-portal/pull/32861

**Pull request closed without merging**
