### PR TITLE
LPS-189793

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@dantewang don't we need to write an upgrade for this? @tinatian fyi

**Comment by dantewang** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/325eecd82c...0d1cdcce0b

**Comment by tinatian** [comment]
@brianchandotcom No, confirmed with @achaparro that we do not need an upgrade.  @achaparro could you please add more details why we do not need it?

**Comment by achaparro** [comment]
The upgrade was not required since the previous records are not valid anymore since the build.namespace is different and new records will created however we want to keep them for sometime as backup. We may need a clean-up upgrade in the future. Remember that this is only used in dev environments.

cc/ @tinatian @brianchandotcom

**Pull request closed without merging**
