### PR TITLE
LPS-88407 more specific path

### PR DESCRIPTION
**Pull request by matethurzo**
@brianchandotcom added a new test suite for pr tester to be able to run the change tracking related tests specifically. We will monitor these tests and keep them green and we will inform others teams too to keep it green

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test:change-tracking

**Comment by jpince** [comment]
@kmaria @matethurzo glad to see you're able to use this framework!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e8a765d495...9c40e7bba6

**Comment by brianchandotcom** [comment]
@jpince @matethurzo @kmaria see 9c40e7bba6db1f2a4cfb3df1ec387bec808fb73f

You guys put the properties in the wrong location. Fyi.

But it is nice that devs are able to add specific tests themselves!

**Pull request closed without merging**
