### PR TITLE
LPS-54009 Remove some warnings due to generics

### PR DESCRIPTION
**Pull request by robertoDiaz**
hey @brianchandotcom 
About https://github.com/brianchandotcom/liferay-portal/pull/27137, This broken test I think is a false positive.

In this pull I delete this bundle (dl-item-selector-api), but folder remains, so the test fails. If the folder is manually deleted the test passes.

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest (this should pass now, we broke something in gradle-plugins)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/221f70e963...43d03ea1aa

**Pull request closed without merging**
