### PR TITLE
COMMERCE-6570 CDN Attachments

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by Commando18** [comment]
ci:reopen

**Comment by Commando18** [comment]
Hey @brianchandotcom,
I made the changes requested here: #104888 
Let me know if everything looks good.
Thanks,
Alessio

**Comment by andrea-ale-sbarra** [comment]
resend of https://github.com/brianchandotcom/liferay-portal/pull/104888

**Comment by brianchandotcom** [comment]
Remote services must not allow anyone to pass in any user ID.

**Pull request closed without merging**
