### PR TITLE
LPS-59967 Rather than throwing IllegalArgumentException, we should simply not set a parameter if it has a null value

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@dustinryerson I made it protected instead of public because I didn't want to expose it.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3834e2800b...3a93703813

**Comment by dustinryerson** [comment]
Sounds good, thanks @brianchandotcom!

**Pull request closed without merging**
