### PR TITLE
LPS-60744

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@matethurzo are we going to be removing a bunch of JSPs as well? A lot of this looks like stuff from other modules? Or am I missing something?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/41df3a5e3d...a3e467f2e9

**Comment by matethurzo** [comment]
@brianchandotcom yes, we are in the process of cleaning up and reorganizing, so your observation is absolutely correct. @LeventeHudak already sent me a cleanup pull, I'll review it today probably. Thank you

**Pull request closed without merging**
