### PR TITLE
LPS-57210 MDR Web extraction

### PR DESCRIPTION
**Pull request by matethurzo**
cc @mhan810 @jorgeferrer

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
Sorted out all the related test failures, these seem to be unrelated

**Comment by brianchandotcom** [comment]
@matethurzo can you resend?

1.) We use DDLWebKeys for DDL, so can you rename MobileDeviceRulesWebKeys to match.. see DDL as an example for portlet names as well.

2.) You forgot to migrate out the portlet title, long title, and description from Language.properties.

Thx.

**Pull request closed without merging**
