### PR TITLE
LPS-60852 ant build-service

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bc0d71e48e...97b70b842e

**Comment by brianchandotcom** [comment]
@adolfopa nice job!

For WikiUtil

Can we change

```
	static {
		Bundle bundle = FrameworkUtil.getBundle(WikiUtil.class);

		_wikiEngineServiceTracker = ServiceTrackerFactory.open(
			bundle, WikiEngineTracker.class);
		_wikiImporterServiceTracker = ServiceTrackerFactory.open(
			bundle, WikiImporterTracker.class);
	}
```

To just 
```
		_wikiEngineServiceTracker = ServiceTrackerFactory.open(WikiEngineTracker.class);
		_wikiImporterServiceTracker = ServiceTrackerFactory.open(WikiImporterTracker.class);
```

Does it have to be tracked on WikiUtil.class?

**Comment by brianchandotcom** [comment]
Can you send a follow up pull to change it if it's possible? Thx. @adolfopa

**Comment by brianchandotcom** [comment]
@adolfopa also, please check plugins. Thx.

**Comment by adolfopa** [comment]
Hi @brianchandotcom 

About the explicit use of `FrameworkUtil` in WikiUtil and all other handcrafted Util classes, technically, it is not required, as right now the Util class and the interface live in the same bundle in all cases (so we could apply the changes you suggest). At the time, I spoke with @migue about that, and we decided to get the Util class bundle explicitly, just to make sure things still work even if the Util class is moved into another bundle. While it is improbable that that would happen given our current code conventions, those classes are not autogenerated, and so we cannot be 100% sure things won't break in the future.

In any case, I don't have a strong opinion about that, so if you feel it's better to use the simpler method, I'll make those changes and send them to you (I'll wait for your confirmation).

In the meantime, I'll apply the changes to plugins.

Thanks!

**Pull request closed without merging**
