### PR TITLE
LRQA-67615

### PR DESCRIPTION
**Pull request by CalumR23**
Combined PR for [LRQA-67501](https://issues.liferay.com/browse/LRQA-67501)

### CODE REVIEW

**Comment by CalumR23** [comment]
ci:reopen

**Comment by CalumR23** [comment]
Passes CI on tests but fails due to unrelated relevant failure
https://github.com/CalumR23/liferay-portal/pull/21

**Comment by brianchandotcom** [comment]
<name>Single Approver</name>

vs.

<name>multi_task_process</name>

Stick with the same syntax please. Thx.

**Comment by brianchandotcom** [comment]
@CalumR23 

Single Approver

vs.

multi_task_process

Stick with the same syntax please. Thx.

**Pull request closed without merging**
