### PR TITLE
LRQA-60854 | master

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-60854

This PR just disables a test that's been failing on our suites. Low risk change.

7.2.x backport: https://github.com/brianchandotcom/liferay-portal-ee/pull/31218

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:reopen

**Comment by xbrianlee** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4a9de41a0e...1f95fdf368

**Pull request closed without merging**
