### PR TITLE
LPS-62118 improve look and feel and experience of pages admin and product menu

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@juliocamarero the CPUsersandorganizations keeps happening? I think it's related? Please resend.

**Comment by brianchandotcom** [comment]
@juliocamarero nvm, I see it here too https://github.com/brianchandotcom/liferay-portal/pull/34497

So I think it's unrelated it. I'm going to risk it and merge this in.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/378a6fdc10...10cb8a52e5

**Pull request closed without merging**
