### PR TITLE
LPS-84859 Auto SF

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9cecd43edb...d00e49a2de

**Comment by brianchandotcom** [comment]
@Preston-Crary can you take a quick look and see if the new permissions classes are right? Thx!

**Comment by Preston-Crary** [comment]
@jkappler @brianchandotcom looks good!

**Pull request closed without merging**
