### PR TITLE
LPS-76522

### PR DESCRIPTION
**Pull request by lionah**

### CODE REVIEW

**Comment by lionah** [comment]
Hey Brian,

Here are some I found that are odd (I'll continue to update the comments as I find them):

/Users/rpark/Projects/liferay-master/portal/modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_ja.properties (I though the export was bad but this is in Pootle this way)
/Users/rpark/Projects/liferay-master/portal/modules/apps/collaboration/document-library/document-library-web/src/main/resources/content/Language_nl.properties (Same lang keys, proper export of HTML but swapping args for direct HTML)
/Users/rpark/Projects/liferay-master/portal/modules/apps/collaboration/invitation/invitation-invite-members-web/src/main/resources/content/Language_ca.properties (Sentence gets lower cased)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7c12b9e4fe...ce26a8dd44

**Comment by brianchandotcom** [comment]
@lionah I wasn't able to merge this because it modified a read only repo. 

error: Illegal change to a pull-only subdir modules/apps/forms-and-workflow/dynamic-data-mapping.

Please resend.

**Comment by lionah** [comment]
@enochchu  I think you missed a few dirs?

**Comment by lionah** [comment]
@enochchu Sorry actually they were introduced when I ran the `gw buildLang`.

**Pull request closed without merging**
