### PR TITLE
LPS-63937

### PR DESCRIPTION
**Pull request by natecavanaugh**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@brunobasto  this is calling downloadNode. Please resend with cache.

cc @natecavanaugh

**Comment by brunobasto** [comment]
@natecavanaugh, just as an FYI, when we change a ES6 file, we need to do a deploy in order for the build to create the task cache. If the cache is outdated, the CI is gonna have to download node to be able to transpile those files. And that can take forever.

/cc @brianchandotcom

**Comment by brunobasto** [comment]
Reent at https://github.com/brianchandotcom/liferay-portal/pull/37165

**Pull request closed without merging**
