### PR TITLE
LPS-74895 petra-reflect

### PR DESCRIPTION
**Pull request by Preston-Crary**
CC @shuyangzhou

### CODE REVIEW

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
@Preston-Crary missed one?
`     [exec] Could not resolve all dependencies for configuration ':core:portal-bootstrap:compileClasspath'.`
`     [exec] > Could not find com.liferay:com.liferay.petra.reflect:1.0.0.`
https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-dist(master)/AXIS_VARIABLE=tomcat,label_exp=!master/1790/console

**Comment by jpince** [comment]
ci:close

**Comment by Preston-Crary** [comment]
@jpince somehow I missed https://github.com/brianchandotcom/liferay-portal/pull/52607/commits/acc07e7080d6955e2a94f4c2fcebb09e89c585c2

Please see https://github.com/brianchandotcom/liferay-portal/pull/52660

**Pull request closed without merging**
