### PR TITLE
LPS-60705 Remove Software Catalog (take 2)

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
I've gone over the test failures and I can't find any relationship with the changes in this pull. Let's see if they keep happening...

**Comment by JorgeFerrer** [comment]
ci:retest

**Comment by JorgeFerrer** [comment]
I looked at the failing tests and they were of two types:
1) Related to the marketplace module
2) A functional test failure with Site Memberships

I couldn't figure out any relationship with my changes and I know that both portlets are under active development so I tend to think these errors are unrelated to this pull.

**Comment by brianchandotcom** [comment]
@JorgeFerrer they're related to this pull because it's only happening on this pull. My other pulls are all clean.

@shuyangzhou can you point Jorge in the right direction? This is a good example so he understands what many of the Spanish engineers have been struggling through (and can perhaps give us suggestions on how to improve things).

 Thx.

**Comment by brianchandotcom** [comment]
@JorgeFerrer shuyang is out sick today (son has fever). Can you ask Miguel / Carlos to help you parse through the logs? They should know by now and be able to help.

**Pull request closed without merging**
