### PR TITLE
LPS-62669 prep next

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
ci:retest

**Comment by csierra** [comment]
ci:retest

**Comment by csierra** [comment]
ci:retest

**Comment by csierra** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c29f8256e9...97a60de2dc

**Pull request closed without merging**
