### PR TITLE
Lps 75832

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e54ed9e0ce...bc0797447b

**Comment by brianchandotcom** [comment]
@mtambara I think you  forgot to remove the export from bnd.bnd?

**Comment by brianchandotcom** [comment]
@mtambara can you also backport this? I believe the original files you are copying from are different between the branches. So you should sync them up first (if possible) and then backport. Thx.

**Comment by shuyangzhou** [comment]
@brianchandotcom there are subrepo usages of those exports. We will send in subrepo changes soon. Once they are merged, we can remove the export here.

**Pull request closed without merging**
