### PR TITLE
LPS-54198 Deprecate exception types improving error reporting in RequiredStructureException

### PR DESCRIPTION
**Pull request by pei-jung**
Hi Brian,

I've fixed the issues you mentioned in this pull https://github.com/brianchandotcom/liferay-portal/pull/24840. Please let me know if there're other issues. Thanks!

/cc @marcellustavares

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Hey @pei-jung 

I find the old way actually gives more info. For example,

RequiredStructureException.REFERENCED_STRUCTURE_LINK clearly means that this is a required structure that is referenced by a structure link

RequiredStructureException.REFERENCED_STRUCTURE means that this is a required structure referenced by another structure

RequiredStructureException.REFERENCED_TEMPLATE means that this is a required structure referenced by a template

Now, the new way..
```
				throw new RequiredStructureException.
					MustNotDeleteReferencedStructureLink(
						structure.getStructureId());

				throw new RequiredStructureException.
					MustNotDeleteReferencedStructure(
						structure.getStructureId());

				throw new RequiredStructureException.
					MustNotDeleteStructureReferencedByTemplates(
						structure.getStructureId());
```

does not give that same info. In this case, the MustNotDeleteStructureReferencedByTemplates throws the previous 2 methods into doubt, when in actually, the only difference is that it has to do with a template that is referencing it.

We need to be very very very careful about naming. Bad naming adds more confusion. Please resend

@pei-jung  please resend. Thx!

cc: @iobrist @jorgeferrer

**Comment by pei-jung** [comment]
Hi Brian,

That makes sense. Thanks for pointing that out. New pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/24932. =)

**Pull request closed without merging**
