### PR TITLE
master-qa-26400

### PR DESCRIPTION
**Pull request by vicnate5**
https://issues.liferay.com/browse/LRQA-26400

Adds test for Forms Captcha to the CI @marcellustavares @natocesarrego

### CODE REVIEW

**Comment by vicnate5** [comment]
Sent to 7.0.x - https://github.com/brianchandotcom/liferay-portal/pull/41276

**Comment by sharonchoi** [comment]
POSHI failures due to a regression merged upstream, documented here: https://issues.liferay.com/browse/LPS-66985

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6674ac800c...fefe9e04b9

**Comment by natocesarrego** [comment]
Thanks @vicnate5!

**Comment by marcellustavares** [comment]
Awesome, thanks @natocesarrego @vicnate5!

**Pull request closed without merging**
