### PR TITLE
LPS-74331 Sets servletContext

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by pyoo47** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5eedf6f0a6...c803483335

**Comment by brianchandotcom** [comment]
@ealonso see c803483335c2f3a4a9632133b3f2d4445e761a01

thx

**Pull request closed without merging**
