### PR TITLE
LPS-91856 Rename last missing reference to "Fragment entry type" instead of the desired "Fragment type"

### PR DESCRIPTION
**Pull request by JorgeFerrer**
/cc @ealonso

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
@brianchandotcom I changed the constant that you mentioned and also searched across the source code for any other usage of fragment-entry-type, fragmentEntryType, fragment_entry_type or other forms of "fragment entry type". I didn't find any other. So it should now be fine. 

As I mentioned in the other pull, We believe it's better to say Fragment Type instead of FragmentEntry Type because a FragmentEntry represents an entry in the database and precisely that's just one type of fragment (static). The other type (dynamic) doesn't have an associated FragmentEntry.

**Comment by jpince** [comment]
ci:close @JorgeFerrer please see errors in modules-compile, they look related
```
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/fragment/fragment-renderer-api/src/main/java/com/liferay/fragment/renderer/FragmentRenderer.java:17: error: package com.liferay.fragment.constants does not exist
     [exec] import com.liferay.fragment.constants.FragmentTypeConstants;
     [exec]                                      ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/fragment/fragment-renderer-api/src/main/java/com/liferay/fragment/renderer/FragmentRenderer.java:34: error: cannot find symbol
     [exec] 		return FragmentTypeConstants.TYPE_COMPONENT;
     [exec] 		       ^
     [exec]   symbol:   variable FragmentTypeConstants
     [exec]   location: interface FragmentRenderer
     [exec] 2 errors
```

**Comment by JorgeFerrer** [comment]
Thanks Jason! I will take care of it

**Comment by JorgeFerrer** [comment]
Resent as https://github.com/brianchandotcom/liferay-portal/pull/70623

**Pull request closed without merging**
