### PR TITLE
LRQA-28515, LRQA-28516 | master

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LPS-48219 / https://issues.liferay.com/browse/LRQA-28515
https://issues.liferay.com/browse/LPS-57989 / https://issues.liferay.com/browse/LRQA-28516

These tests have been failing for more than a year due to these LPS tickets. We're removing them for now so those test failures won't be noise for the testers. We'll re-add when the tickets are fixed. I've committed the test removals under the LPS tickets.

### CODE REVIEW

**Comment by brianchiu** [comment]
cc @alee8888 @brianwulbern

**Comment by brianchiu** [comment]
cc @alee8888 @brianwulbern @sharonchoi

**Comment by brianwulbern** [comment]
@pyoo47 @michaelhashimoto two weird things happened on that failed test (in test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk8/17).  It's [pointing](https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=4,label_exp=!master/45692/) to a pull sent by Ginson Ren.  And all the linked tests in Axis-4 passed.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
