### PR TITLE
LPS-95857 buildLang

### PR DESCRIPTION
**Pull request by p2kmgcl**
Here is the missing language key: https://github.com/liferay/clay/blob/2.x-develop/packages/clay-autocomplete/src/ClayAutocomplete.soy#L255

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
Can you resend:

no-records-were-found=No records were found.
no-results-found=No results found.
no-results-were-found=No results were found.
no-reviewers-were-found=No reviewers were found.


The usage of:

no-results-found=No results found.

should be:

no-results-were-found=No results were found.

we need the verb. Please fix the usages.

**Comment by p2kmgcl** [comment]
@brianchandotcom sure, I'm sending those changes to Clay

**Comment by p2kmgcl** [comment]
@brianchandotcom done https://github.com/liferay/clay/pull/2011

**Pull request closed without merging**
