### PR TITLE
Default Configurations: create default configurations using a declarative approach

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by migue** [comment]
Tomas (@topolik) , now we can create the default configs using a declarative approach, as I promised you.

Carlos (@csierra) , do you want me to apply it to the work we've done with the JAX stuff

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7fcd52845d...29fdf42208

**Comment by brianchandotcom** [comment]
@migue I really like these .cfg files. Very very nice.

**Comment by csierra** [comment]
@migue I prefer to do it myself so I can learn

**Comment by topolik** [comment]
@migue Thanks, looks very good!

**Pull request closed without merging**
