### PR TITLE
LPS-129367 Remove all .npmbundlerrc files and pass their config to npmscripts.config.js

### PR DESCRIPTION
**Pull request by izaera**
This is a manual forward of https://github.com/liferay-frontend/liferay-portal/pull/938 after a [QA analysis of CI runs](https://github.com/liferay-frontend/liferay-portal/pull/938#issuecomment-827849135).

As it is very prone to conflicts because it changes all `.npmbundlerrc` and `npmscripts.config.js` files, it would be great to prioritize it.

---

The goal of the PR is to remove all traces of webpack federation and coalesce all imports configuration in the main `npmscripts.config.js` file at `modules`. This should ease build configuration.

All decissions of the PR are based on [this doc](https://docs.google.com/document/d/1RxjjzTaPpUun6YfzxWjL244j6IlEsgHZGztf6mta0Q8/edit#).

### CODE REVIEW

**Comment by izaera** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e18bbe8a64...a6fdcdc617

**Comment by brianchandotcom** [comment]
@izaera I merged this, but you sent me JS files with lots of duplicate copyright headers. See a6fdcdc617d2d34359aade86b1dfdf353aaed36a

@hhuijser please auto SF them? We should never have more than 2 Liferay copyrights in 1 file (java or JS).

**Comment by wincent** [comment]
We have a ticket open for dealing with this, [LPS-131310](https://issues.liferay.com/browse/LPS-131310), with some noted likely causes. I think the fix should be pretty trivial on the JS side (maybe just a config tweak). I would advise against having Java SF touching copyright headers in JS files, so that we don't have two tools competing to do the same thing.

**Comment by ling-alan-huang** [comment]
Thanks @wincent I will look into it.

**Comment by wincent** [comment]
@ling-alan-huang: Probably makes sense for us (Frontend Infra) to handle this one, as we maintain all the ESLint-related tooling (eg. [`@liferay/eslint-config`](https://github.com/liferay/liferay-frontend-projects/tree/master/projects/eslint-config), [`@liferay/npm-scripts`](https://github.com/liferay/liferay-frontend-projects/tree/master/projects/npm-tools/packages/npm-scripts), as well as the integration of those in `liferay-portal`). I can take a quick look this afternoon even.

**Comment by ling-alan-huang** [comment]
@wincent sounds good, thanks.

**Comment by wincent** [comment]
Fix will be headed to Brian soon — currently sitting at: https://github.com/liferay-frontend/liferay-portal/pull/1027

**Pull request closed without merging**
