### PR TITLE
LRQA-36000 | master

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LRQA-36000

cc @austinchiang @patriciajeanperez

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:stop

**Comment by brianchiu** [comment]
ci:reopen

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cde0bc2c94...a6b425ddd3

**Pull request closed without merging**
