### PR TITLE
LPS-74741 Unchecked null case in DDMTemplate

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Merged!! Thanks!!

**Comment by ealonso** [comment]
Close by mistake

**Comment by ealonso** [comment]
ci:reopen

**Comment by ealonso** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/aaf317904f...9e172d7e29

**Pull request closed without merging**
