### PR TITLE
LPS-80429

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@brianchandotcom, tried to SF enforce this, but SF won't be able to do this. Just fixing the cases I am finding now (all of those increase performance as they are used after a return, continue or throw statement, which means they might not be needed).

**Comment by hhuijser** [comment]
@brianchandotcom, tried to SF enforce this, but SF won't be able to do this. Just fixing the cases I am finding now (all of those increase performance as they are used after a `return`, `continue` or `throw` statement, which means they might not be needed).

**Comment by hhuijser** [comment]
ci:test

**Comment by hhuijser** [comment]
Please let the test finish first!

**Comment by brianchandotcom** [comment]
@shuyangzhou GREEN!

**Pull request closed without merging**
