### PR TITLE
LPS-161065 Walkthrough in Site Initializer as site settings

### PR DESCRIPTION
**Pull request by jkappler**
- LPS-161065 We can achieve this with site settings, so modify to adapt to it
- LPS-161065 There are cases were we can specify json string is properties. propertiesJSONObject.toMap() will throw an error. Change so that we read and change the values to string. This way we can also have a readable format in our site-setting.json files instead of a big string that is unfriendly to the user

### CODE REVIEW

**Comment by jkappler** [comment]
ci:reopen

**Comment by jkappler** [comment]
@brianchandotcom, this has been stuck in the CI for quite a while, sending directly.
 
cc:// @joseabelenda

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ef8b34ab80...a201be7659

**Comment by brianchandotcom** [comment]
Thx @jkappler see a201be7659086c9f4969c95fe2ae9f5580f6c6f4

@joseabelenda fyi

**Pull request closed without merging**
