### PR TITLE
LRQA-29376 Make mirrors-get task JDK6 compatible.

### PR DESCRIPTION
**Pull request by pyoo47**
Please publish a new mirrors-get jar after merging this pull request.

CC: @holatuwol

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@pyoo47 republished.

**Comment by brianchandotcom** [comment]
@pyoo47 I haven't upgraded any of the jars to use 1.0.3. I'll let you send me a pull for that.

**Pull request closed without merging**
