### PR TITLE
LPS-90112 Take local live groups or remote live group (in live database) if it does not have local live associated

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test:staging

**Comment by matethurzo** [comment]
@achaparro can you confirm the two poshi failures are related or not?

**Comment by achaparro** [comment]
Hey @matethurzo, let's wait for the staging tests here:
https://github.com/brianchandotcom/liferay-portal/pull/67879

I am almost sure that they are not related but let's wait a bit for it if you agree (the logic is exactly the same but instead of processing all groups, we process just live groups)

Thanks.

**Comment by achaparro** [comment]
Hey @matethurzo,

The errors also occur here:
https://github.com/brianchandotcom/liferay-portal/pull/67877

So I think the changes are unrelated

**Comment by achaparro** [comment]
Regarding the staging tests, the errors seem the same than the ones we get here:
https://github.com/brianchandotcom/liferay-portal/pull/67879

**Comment by jpince** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/19f53f12a3...6bdd3c165c

**Pull request closed without merging**
