### PR TITLE
LPS-191346: Set a page size limit for the GraphQL requests

### PR DESCRIPTION
**Pull request by sergiojimcos**
## Motivation
This PR allows the user to set the page limit for GraphQL request using the Headless Configuration, which is the same that uses the Headless APIs. This means that we could have duplicated code, so the aim of this PR is to create a component that shares the same functionality for Headless APIs and apply it also in GraphQL. To reach this, a `PaginationConfigurationProvider` component is going to be created to allow to set the limit page for both cases.

**What is new?**
- Creation of a new component `PaginationConfigurationProvider` for sharing `getPagination` logic.
- Apply this to PaginationContextProvider and GraphQLDataFetcher implementations.
- Create a PaginationConfigurationTestUtil to set the HeadlessConfiguration limit pages in tests cases and applies it in `PaginationContextProviderTest` and `GraphQLPaginationServletTest`
- Create some test cases.

**Which modules need to be deployed?**
- Deploy `portal-vulcan-impl`

**Related JIRA Ticket**
https://liferay.atlassian.net/browse/LPS-191346

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:reopen

**Comment by sergiojimcos** [comment]
Sent from here: https://github.com/liferay-headless/liferay-portal/pull/1607

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0d9e685010...4fc8beb6b2

**Comment by brianchandotcom** [comment]
@sergiojimcos just 4fc8beb6b27e2f6f264b751fa809e6b9408ea64c

**Pull request closed without merging**
