### PR TITLE
LPS-109809 the order matters

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
cI:reopen

**Comment by leoadb** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1a83585a70...71fa511a9a

**Comment by brianchandotcom** [comment]
@leoadb like this:

```
		_dataDefinitionContentTypesByClassNameId.remove(
			_classNameIds.get(contentType));

		_classNameIds.remove(contentType);
		_dataDefinitionContentTypesByContentType.remove(contentType);
```

So you can see where order matters and where order does not matter. See  71fa511a9ac3fc2c2a98efdae8acdac3152f2a7c

**Pull request closed without merging**
