### PR TITLE
LPS-75598 Create a framework that allows applications to provide their data erasure implementations

### PR DESCRIPTION
**Pull request by pei-jung**
This is an update for [LPS-75598](https://issues.liferay.com/browse/LPS-75598).
This is an update for [LPS-76024](https://issues.liferay.com/browse/LPS-76024).
This is an update for [LPS-76025](https://issues.liferay.com/browse/LPS-76025).

Hey Brian, these are the initial commits for the GDPR changes. The API is subject to change, but we need this as a base to work off of.

/cc @JorgeFerrer, @drewbrokke , @willnewbury, @noahsherrillwork

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test

**Comment by pei-jung** [comment]
ci:reopen

**Comment by drewbrokke** [comment]
ci:test

**Comment by pei-jung** [comment]
Hey @brianchandotcom,

When you get a chance, can you review this pull request? Please let us know if you have any questions. Thanks!

**Comment by brianchandotcom** [comment]
@pei-jung @drewbrokke @willnewbury 

Can you split com.liferay.user.associated.data.model into:

com.liferay.user.associated.data.aggregator
com.liferay.user.associated.data.anonymizer
com.liferay.user.associated.data.entity
com.liferay.user.associated.data.exporter

Thx

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1b562c66ff...b62b2b1220

**Comment by drewbrokke** [comment]
@brianchandotcom I'll go ahead and take care of it

**Pull request closed without merging**
