### PR TITLE
LPS-55754 Extract Journal tests

### PR DESCRIPTION
**Pull request by epgarcia**
@juliocamarero

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:retest

**Comment by epgarcia** [comment]
ci:retest

**Comment by epgarcia** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f54bf79bd5...291de7793e

**Comment by brianchandotcom** [comment]
@epgarcia please see my changes in upstream. Can you make sure to ping Cristina to fix the Arquillian issue? Thx :) I don't like losing tests. I used @Ignore to temporarily disable them.

**Pull request closed without merging**
