### PR TITLE
LPS-75499

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by jpince** [comment]
@brianchandotcom looks good from a functional test perspective.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9d997ad16c...5c86e96a2b

**Comment by brianchandotcom** [comment]
@mhan810 merged, but not backported as this is a master only issue. Please send me a backport if I'm wrong.

**Comment by mhan810** [comment]
You’re right.  I’m still working on fixing a series of other items for a
backport pull for 7.0.x



*From:* Brian Chan [mailto:notifications@github.com]
*Sent:* Thursday, November 2, 2017 5:21 PM
*To:* brianchandotcom/liferay-portal <liferay-portal@noreply.github.com>
*Cc:* Michael Han <michael.han@liferay.com>; Mention <
mention@noreply.github.com>
*Subject:* Re: [brianchandotcom/liferay-portal] LPS-75499 (#52499)



@mhan810 <https://github.com/mhan810> merged, but not backported as this is
a master only issue. Please send me a backport if I'm wrong.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/brianchandotcom/liferay-portal/pull/52499#issuecomment-341575368>,
or mute the thread

**Pull request closed without merging**
