### PR TITLE
LPS-118437 Use StringUtil.merge instead

### PR DESCRIPTION
**Pull request by carolmariaabb**
Changes made as requested [here](https://github.com/brianchandotcom/liferay-portal/pull/92360#issuecomment-670163398).

I'm sending this fix straight because the tests have already been executed on this [PR](https://github.com/brianchandotcom/liferay-portal/pull/92360) and this issue is classified as a blocker.
 
Related issue: https://issues.liferay.com/browse/LPS-118437

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/497890818e...89ee2eaa04

**Comment by brianchandotcom** [comment]
@carolmariaabb see 89ee2ea

**Pull request closed without merging**
