### PR TITLE
LPS-73224 Remove unnecessary usage of BeanParamUtil in blogs web.

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
ci:retest

@Preston-Crary you made a change to blogs and all of blogs modules-int is break. So that makes me weary for merging this...

But, the change you made is to a JSP.. so that doesn't make sense

Retesting to find out what's going on

**Comment by Preston-Crary** [comment]
Pretty sure the NoSuchFileException, was not caused by my change.

**Comment by brianchandotcom** [comment]
@Preston-Crary please backport. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1ad506da83...5005969e18

**Comment by brianchandotcom** [comment]
@Preston-Crary nvm, I backported it.

**Pull request closed without merging**
