### PR TITLE
LPS-58412 minor fixes to web content priority

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
@brianwulbern this adds a new field in the web content > categorization category called priority.

**Comment by juliocamarero** [comment]
Hey @ZoltanTakacs,

could you please backport this when Brian merges it? 

thanks!

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@juliocamarero 

I didn't merge this because ServiceContextFactory#getAssetPriority is reading from "priority". 

Imagine if I edit a Layout and it sets "priority", and somehow, ServiceContextFactory#getAssetPriority returns that same value. It'd be confusing.

Can you resend? Thx.

Thx.

**Pull request closed without merging**
