### PR TITLE
LPS-54341 Config Editors

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Hey Sergio,

One more change:

```
public void populateConfigJSONObject(
		JSONObject jsonObject, Map<String, Object> inputEditorTaglibAttributes,
		ThemeDisplay themeDisplay,
		LiferayPortletResponse liferayPortletResponse) {
```

Can we remove themeDisplay and pass in liferayPortletRequest?

Same for 

```
public EditorConfig getEditorConfig(
		String portletName, String editorConfigKey, String editorImpl,
		Map<String, Object> inputEditorTaglibAttributes,
		ThemeDisplay themeDisplay,
		LiferayPortletResponse liferayPortletResponse) {
```

We don't need portletName either since that can be read from the request.

We can then have a BaseEditorConfigFactory that implements EditorConfigFactory

All of the instances can extend BaseEditorConfigFactory which will then have a getPortletId(liferayPortletRequest) etc and will still keep things lean.

Thx!

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@sergiogonzalez please see my minor changes in upstream. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e427c912db...82deefc3e9

**Pull request closed without merging**
