### PR TITLE
[PING] LPS-58563 extract the control menu into modules[PONG]

### PR DESCRIPTION
**Pull request by juliocamarero**
Resent. See email about #3. thanks!

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retes

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
