### PR TITLE
Lrqa 51349

### PR DESCRIPTION
**Pull request by CAustin582**

### CODE REVIEW

**Comment by CAustin582** [comment]
ci:test:relevant

**Comment by CAustin582** [comment]
ci:test:stable

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1e674ec8f1...8b1e7a27f1

**Comment by brianchandotcom** [comment]
Thx @CAustin582 I was able to backport this all the way to 7.0.x.

**Pull request closed without merging**
