### PR TITLE
LPS-63355 SF

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
@brianchandotcom - This one is running, and the results should be returning soon.

The 'source' job took 41 minutes so that backlogged this pull a bit. (This is the one that syncs with local git)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/65c6f38469...5cceb0d0c3

**Comment by brianchandotcom** [comment]
@marcellustavares can we get rid of the key? there-are-no-templates

**Pull request closed without merging**
