### PR TITLE
Lps 74276

### PR DESCRIPTION
**Pull request by shuyangzhou**
@mhan810 @david-truong this is the debug support for unsatisfied DS component.
@jhinkey document please.

CC @gamerson

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@brianchandotcom the disabled test will be enabled once sub-repos are fixed for their unsatisfied components.

**Comment by brianchandotcom** [comment]
@shuyangzhou can you resend this part

```
	private static void _collectUnsatisfiedReferences(
		ComponentDescriptionDTO componentDescriptionDTO,
		ComponentConfigurationDTO componentConfigurationDTO, StringBundler sb) {

		sb.append("\n\tDeclarative Service: id=");
		sb.append(componentConfigurationDTO.id);
		sb.append(",name=");
		sb.append(componentDescriptionDTO.name);
		sb.append(",unsatisfied references=");

		for (UnsatisfiedReferenceDTO unsatisfiedReferenceDTO :
				componentConfigurationDTO.unsatisfiedReferences) {

			sb.append("{name: ");
			sb.append(unsatisfiedReferenceDTO.name);
			sb.append(", target: ");
			sb.append(unsatisfiedReferenceDTO.target);
			sb.append("}");
		}
	}
```
The output doesn't seem to match our existing patterns? Thx.

**Comment by shuyangzhou** [comment]
@brianchandotcom it matches https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/portal-osgi-debug/portal-osgi-debug-spring-extender/src/main/java/com/liferay/portal/osgi/debug/spring/extender/internal/UnavailableComponentScanner.java#L127 , how do you want to change it? And do you want to change both of them?

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0fa2b2226e...b4786b2cd8

**Pull request closed without merging**
