### PR TITLE
LPS-100427 site external code

### PR DESCRIPTION
**Pull request by javiergamarra**
/cc @jorgeferrer

### CODE REVIEW

**Comment by nhpatt** [comment]
sf error is fixed here: https://github.com/brianchandotcom/liferay-portal/pull/77951 & https://github.com/brianchandotcom/liferay-portal/pull/77964

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/16ac2c2bf3...c0824f940e

**Comment by brianchandotcom** [comment]
@nhpatt see c0824f940e943f74eb23a2e53f6671a3d3c0a5e6 thx!

**Comment by brianchandotcom** [comment]
@nhpatt I forgot this ada81a56b92d82a5b2632f35c790faeaa80eee36

**Pull request closed without merging**
