### PR TITLE
LPS-110184 Fix Treeview Items Styling

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @brianchandotcom, sending this directly after several days struggling to see green in tests. Everytime we quarantine one, another 3 fail...

This PR:
- Modifies the TreeView component Item markup
- Fixes the TreeView nodes selector to account for the markup changes

See analysis [here](https://github.com/wincent/liferay-portal/pull/193)

Could you please push this directly? That's what @manoelcyreno suggested.

/cc @john-co, @manoelcyreno, @wincent, @eduardoallegrini

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:reopen

**Comment by john-co** [comment]
will resend with some modifications due to https://github.com/brianchandotcom/liferay-portal/pull/87102

**Comment by john-co** [comment]
ci:close

**Comment by john-co** [comment]
resent in https://github.com/brianchandotcom/liferay-portal/pull/87133

**Pull request closed without merging**
