### PR TITLE
LPS-66486

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@brianchandotcom I switched tcserver to use tomcat

**Comment by brianchiu** [comment]
Poshi failures are unrelated.

@michaelhashimoto
There are several build failures here due to:
```
[copy] Warning: Could not find file /opt/dev/projects/github/liferay-portal/test.generated.properties to copy.
```

The rest of the poshi failures are because portal is randomly shutting off or not connecting or something. This is starting to happen multiple times per pull request, so we really gotta figure out what's causing it.

before1

**Comment by pyoo47** [comment]
Hashi has been trying to narrow down the commits that introduced this issue. I'm hoping he will have something for us tomorrow.

**Comment by brianchandotcom** [comment]
@david-truong  can you resend it as "server.detector.server.id" (see how that method is not called server.id anymore in upstream)

**Comment by brianchandotcom** [comment]
@david-truong nvm, I just went ahead and did it...

**Comment by michaelhashimoto** [comment]
@brianchiu - we should have fixed it now.

**Pull request closed without merging**
