### PR TITLE
LPS-90897 Apply minor view logic adjustment to journal

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test:change-tracking

**Comment by matethurzo** [comment]
@brianchandotcom @jpince the test is broken because Brian did some refactoring, but not applied correctly. We are sending the fix, but this failure is unrelated to this code

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e9d94dc77f...99e760ba4d

**Comment by brianchandotcom** [comment]
@matethurzo see minor fixes in upstream.

**Pull request closed without merging**
