### PR TITLE
LPS-81724 Use this instead of super to keep Element functionality

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
@brianchandotcom Could you please publish patched Jsoup JAR once again? I've forgotten to include jsoup classes and it is necessary to use "this" instead of "super" in the new constructor to maintain existing Element functionality. Thanks!

**Comment by brianchandotcom** [comment]
@pavel-savinov published..  it's now *-2, see 153eb15

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Pull request closed without merging**
