### PR TITLE
LPS-74666

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@arboliveira fyi

**Comment by mhan810** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
@mhan810 is this related?
`    [junit] Testcase: testGetFullQueryWithAttachments(com.liferay.portal.kernel.search.BaseIndexerGetFullQueryTest):	Caused an ERROR`
`    [junit] Service must contain a related.entry.indexer.class.name`

**Comment by mhan810** [comment]
Yep close it and I'll take a look

**Comment by jpince** [comment]
ci:close

**Pull request closed without merging**
