### PR TITLE
LPS-71855 Sets the value if val is called as a setter

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e951d99c40...0b3b2046e3

**Comment by brianchandotcom** [comment]
@jbalsas please backport if necessary? Thx.

**Comment by jbalsas** [comment]
Done! https://github.com/dustinryerson/liferay-portal-ee/pull/2812

**Pull request closed without merging**
