### PR TITLE
LPS-105193 propagate descriptions

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7c86b73790...f2c5b5f42f

**Comment by brianchandotcom** [comment]
@nhpatt published new REST builder.

**Comment by brianchandotcom** [comment]
@nhpatt see 0cfb65d

From portal, type:

ant setup-profile-dxp && ant setup-sdk

then go to modules/dxp/apps and run

gw buildREST

**Comment by brianchandotcom** [comment]
@nhpatt hash now works see 0cfb65d41e39d61c653635cf6a7900b07a46323f

**Comment by nhpatt** [comment]
Thanks! :) Will do next time!

**Pull request closed without merging**
