### PR TITLE
LPS-169503 - Add new dropdown options

### PR DESCRIPTION
**Pull request by liulukiwi**
This is only for master.

https://issues.liferay.com/browse/LPS-169503

@ruben-pulido

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:reopen

**Comment by liulukiwi** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/10698

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a5a1b8d610...4637e6842c

**Comment by brianchandotcom** [comment]
@ruben-pulido @veroglez just 4637e6842ca5f472a02b2ab9749150e61111bdf1

**Pull request closed without merging**
