### PR TITLE
LPS-102083 Make fragment name also draggable in topper

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
@brianchandotcom could you please backport this? we would like to have it included in SP1, as it solves several usability issues that we detected these days. Thank you!

**Comment by victorg1991** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by victorg1991** [comment]
ci:close @brianchandotcom we are going to send another one right away, with one quick fix

**Pull request closed without merging**
