### PR TITLE
LPS-94882 Load fields on item change

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:relevant @jrhoun @jhendley @brianchiu @kyle-miho @reizero00

**Comment by brianchiu** [comment]
ci:test:bundle

**Comment by brianchiu** [comment]
Confirmed manually that this fixes LPS-94882.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
