### PR TITLE
Lps 72507

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@tomwang2011 please fix Service Builder test. Thx.

**Comment by shuyangzhou** [comment]
ci:reopen
@brianchandotcom this is a CI issue, not caused by the pull.

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7fce89a486...9f31802393

**Comment by brianchandotcom** [comment]
@tomwang2011 can you backport this to ee-7.0.x (please fix EE only plugins too)

Thx

**Pull request closed without merging**
