### PR TITLE
LPS-74749 Excludes temporary compat layer from SF

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jbalsas why would we exclude the temp compat layer? That layer will be part of the release for at least one version no? Please reopen with an explanation (no need to retest). Thx.

**Comment by jbalsas** [comment]
Hey @brianchandotcom, the compatibility layer will not be part of the release. We are planning to offer it as a temporary help during upgrades, but is, in no way, something meant for a production environment. 

We are spending a couple of weeks fixing stuff around in the compat layer so we have properly documented and controlled as many annoyances and breaking changes as possible, both to document them and facilitate an upgrade.

After we stabilize it, we'll start working with the teams on updating the necessary frontend pieces for the new framework and UX patterns, slowly stripping pieces from the bundled compat layer until we can completely remove it for our official release and provide it as an upgrade tool only.

Hope it makes sense!

**Comment by jbalsas** [comment]
we can skip formatting in more specific sections (third parties such as fontawesome or glyphicons) if you feel more comfortable with it

**Comment by jbalsas** [comment]
ci:reoen

**Pull request closed without merging**
