### PR TITLE
LPS-59564

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@shuyangzhou pacl test

**Comment by shuyangzhou** [comment]
@rotty3000 this is the same felix cm osgi security issue. Last time you said you will look into it, have you done it yet? If you don't have time for it any time soon, I will start on it. This is getting often enough to show up almost everyday.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4afe31b722...e727d0431d

**Comment by brianchandotcom** [comment]
@shuyangzhou @rott3000 it's shown up several times for me today. And it ends up confusing some of the other developers.

@hhuijser @Ithildir I published the new jars that were part of this pull.

**Comment by shuyangzhou** [comment]
@rotty3000 it is ok if you don't have time for it, I can take over. But can you at least update https://github.com/liferay/liferay-portal/blob/master/modules/core/required-depedencies/build.gradle to not use any SNAPSHOT versions? They are causing a lot of troubles for debugging, as I can not find the exact matched sources.

**Pull request closed without merging**
