### PR TITLE
LPS-138539 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-138539

This is only for master.

@victorg1991
@jkappler

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure is unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/5706
✔️ ci:test:stable - 11 out of 11 jobs passed
❌ ci:test:relevant - 22 out of 25 jobs passed in 2 hours 5 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/02cadc374c...c277770ec8

**Comment by brianchandotcom** [comment]
@victorg1991 see c277770

**Pull request closed without merging**
