### PR TITLE
LPS-96546 locale in graphql

### PR DESCRIPTION
**Pull request by javiergamarra**
I'm using the function to avoid adding a dependency in the API projects (to be able to cast to GraphQLContext) and to not expose AcceptLanguage constructors.

I'm afraid adding graphl-java is needed to be able to inject the DataFetchingEnvironment with the HttpRequest (unless we provide our own graphql-servlet). A compileInclude can't work because the library is doing a instanceOf check inside (portal-vulcan-impl != headless-api modules, or we change the classLoader). I can add the dependencies to the static module if this solution is valid.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
@nhpatt can you send this to me but add a example usage of the new generated API and a way to test it?

I'll refactor the pull so we don't have to export all the graphql jars.

**Comment by nhpatt** [comment]
ci:stop

**Comment by nhpatt** [comment]
Yeah, sure :)

I can also do it if you point me to the right direction :D

**Comment by Preston-Crary** [comment]
@nhpatt, I would point you in the right direction but I have to find it first :)

If you send me an example I can find the right thing to do.

**Comment by nhpatt** [comment]
Ok! Sent you the PR here: https://github.com/Preston-Crary/liferay-portal/pull/781 with the steps to test it manually. I can prepare an automatic test tomorrow (CEST time) if you prefer it.

**Pull request closed without merging**
