### PR TITLE
Lps 68681

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @sergiogonzalez @mhan810

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@tomwang2011 backport please

**Comment by shuyangzhou** [comment]
Force pushed a harmless javadoc SF fix. No need to rerun the tests.

**Comment by brianchandotcom** [comment]
@shuyangzhou please resend.

*Helper java classes should not contain static methods. Those should be called *Util. *Helper is the pattern that is like Util except it's an instanceable class.

Thx.

**Comment by shuyangzhou** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/43901 with a rename commit.

**Pull request closed without merging**
