### PR TITLE
Add Schema Version to Release

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pyoo47 another build hung earlier

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/15b09785f9...ba09ac4950

**Comment by ZoltanTakacs** [comment]
Thank you @cgoncas. It's been merged to 7.0.x.

Please note that the backport workflow has been changed for the RCs. 
For the details please see @jhendley 's email or refer to this [document](https://docs.google.com/document/d/1A-EoPvI1KDDpUH2PAlKmpgUDb_2RFM4iwpB_4loQHFk/edit).

Thank you,
Zoltán

**Pull request closed without merging**
