### PR TITLE
LPS-73467

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Andrea says to leave this open. He's working on a fix for the exception.

**Comment by Ithildir** [comment]
@hhuijser, please retest this pull once https://github.com/brianchandotcom/liferay-portal/pull/50118 is merged. Thanks!

**Comment by Ithildir** [comment]
ci:retest

**Comment by hhuijser** [comment]
Thanks @Ithildir

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b3db219fe3...399d3c571f

**Pull request closed without merging**
