### PR TITLE
LPS-73350 Build formValues from request and set it in the form redering context

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:reopen

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
I've created a ticket to fix the CI failure. https://issues.liferay.com/browse/LRQA-33901

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/83e7827f86...68700443a9

**Pull request closed without merging**
