### PR TITLE
LPS-84804 Build lang

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
@jpince, it's weird, but the test didn't run when I sent the PR

**Comment by jkappler** [comment]
cc:// @ealonso, @brianchiu

**Comment by jpince** [comment]
@jkappler thanks for reporting. Sometimes the hook misses a pull, looks like all other pulls are fine. I will keep an eye out to make sure test runs are initiating.

**Comment by jpince** [comment]
ci:close @jkappler failure in modules-compile
```
     [exec] :apps:asset:asset-list-web:generateJSPJava FAILED
     [exec] Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
     [exec] 	at com.liferay.jasper.jspc.JspC.main(JspC.java:52)
     [exec] Caused by: java.lang.reflect.InvocationTargetException
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at com.liferay.jasper.jspc.JspC._runWithClassPath(JspC.java:168)
     [exec] 	at com.liferay.jasper.jspc.JspC.main(JspC.java:46)
     [exec] Caused by: java.lang.NoClassDefFoundError: com/liferay/frontend/taglib/soy/servlet/taglib/TemplateRendererTag
     [exec] 	at java.lang.ClassLoader.defineClass1(Native Method)
     [exec] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
     [exec] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
     [exec] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
     [exec] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
     [exec] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
     [exec] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
     [exec] 	at java.security.AccessController.doPrivileged(Native Method)
     [exec] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
     [exec] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
     [exec] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     [exec] 	at java.lang.ClassLoader.defineClass1(Native Method)
     [exec] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
     [exec] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
     [exec] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
     [exec] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
     [exec] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
     [exec] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
     [exec] 	at java.security.AccessController.doPrivileged(Native Method)
     [exec] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
     [exec] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
     [exec] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
     [exec] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
     [exec] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     [exec] 	at org.apache.jasper.compiler.Parser.parseCustomTag(Parser.java:1426)
     [exec] 	at org.apache.jasper.compiler.Parser.parseElements(Parser.java:1680)
     [exec] 	at org.apache.jasper.compiler.Parser.parseBody(Parser.java:1911)
     [exec] 	at org.apache.jasper.compiler.Parser.parseOptionalBody(Parser.java:1164)
     [exec] 	at org.apache.jasper.compiler.Parser.parseCustomTag(Parser.java:1481)
     [exec] 	at org.apache.jasper.compiler.Parser.parseElements(Parser.java:1680)
     [exec] 	at org.apache.jasper.compiler.Parser.parse(Parser.java:185)
     [exec] 	at org.apache.jasper.compiler.ParserController.doParse(ParserController.java:244)
     [exec] 	at org.apache.jasper.compiler.ParserController.parse(ParserController.java:145)
     [exec] 	at org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:212)
     [exec] 	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:451)
     [exec] 	at org.apache.jasper.JspC.processFile(JspC.java:1178)
     [exec] 	at org.apache.jasper.JspC.execute(JspC.java:1345)
     [exec] 	... 6 more
     [exec] Caused by: java.lang.ClassNotFoundException: com.liferay.frontend.taglib.soy.servlet.taglib.TemplateRendererTag
     [exec] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
     [exec] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
     [exec] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     [exec] 	... 43 more
```
I think it's failing this batch and not failing the whole build because you haven't included .lfrbuild-portal yet.

**Comment by jkappler** [comment]
thanks for closing it @jpince, will resend

**Pull request closed without merging**
