### PR TITLE
LRCI-699

### PR DESCRIPTION
**Pull request by petershin**
Hi Brian, it might be better to rename the files to `.lfrbuild-portal` so the projects are deployed on both private and public branches when `build.profile=dxp`

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:sharepoint

**Comment by brianchandotcom** [comment]
ci:stop

Can you resend as .lfrbuild-portal

Thx

**Comment by brianchandotcom** [comment]
Should all .lfrbuild-portal-private just be .lfrbuild-portal ?

**Comment by petershin** [comment]
The `.lfrbuild-portal-private` files in the `dxp` directory should be renamed to `.lfrbuild-portal`

**Pull request closed without merging**
