### PR TITLE
LPS-158561 New VHost properties

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:reopen

**Comment by jkappler** [comment]
@brianchandotcom, have been trying to send this for quite a while, no unique failues (https://github.com/jkappler/liferay-portal/pull/1073)

@yang-cao, fyi

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f4d1cb4dc7...1939b1c518

**Comment by brianchandotcom** [comment]
@jkappler see minor changes in my origin.

**Pull request closed without merging**
