### PR TITLE
LPS-81499 Update Clay to v2.1.4

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by jpince** [comment]
Clarification: it's specific to this pull, as far as I can tell. All other pulls are passing, and looks fine in test-6-1-2

**Comment by anthony-chu** [comment]
@jpince - looking at the branch now. based on the base SHA for this pull, it's the same as test-6-1-2 and the latest nightly build. they both display "Filter and Order" instead of "filter-and-order".

**Comment by anthony-chu** [comment]
ci:test:relevant

**Comment by anthony-chu** [comment]
@carloslancha i was taking a look at the update from `v2.0.2` to `v2.1.4`, and it looks like the "Filter and Order" string was moved from a static string to a localizable string [here](https://github.com/liferay/clay/commit/a3f9c8e767d2f80dde90aa147348cc7656c1cdb6). does that mean there will need to be a language key in portal to handle the translation of `filter-and-order`?

**Comment by carloslancha** [comment]
Resent https://github.com/brianchandotcom/liferay-portal/pull/59136

**Comment by carloslancha** [comment]
@anthony-chu yes, all the static strings in clay now are localizable so there should be a language key in portal for each one. I added `filter-and-order` key to `portal-impl/Language.properties` in the new pr. Thanks!

**Pull request closed without merging**
