### PR TITLE
Lps 104116 2

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d38ab47dd4...85adb2648f

**Comment by brianchandotcom** [comment]
@jorgediaz-lr please backport all the way back to 7.0.x.

Thx.

**Comment by brianchandotcom** [comment]
@jorgediaz-lr I backported it to 7.2.x, but can you send me pulls for 7.1.x and 7.0.x

**Comment by jorgediaz-lr** [comment]
Hi @brianchandotcom 

I wasn't able to send you the PR to 7.0.x and 7.1.x branches, PR is autoclosed and automatic message says I am not allowed, see: https://github.com/brianchandotcom/liferay-portal-ee/pull/27699#issuecomment-556085518

I have sent both backports to **liferay** user, following standard backport workflow, see:

- 7.1.x PR: https://github.com/liferay/liferay-portal-ee/pull/17122
- 7.0.x PR: https://github.com/liferay/liferay-portal-ee/pull/17123

Regards,
Jorge Díaz

**Pull request closed without merging**
