### PR TITLE
COMMERCE-618 Liferay component installer for Talend Open Studio (GoLang) v2

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
https://issues.liferay.com/browse/COMMERCE-618

Resend of https://github.com/brianchandotcom/liferay-portal/pull/62859

### CODE REVIEW

**Comment by ZoltanTakacs** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@ZoltanTakacs this is actually helpful for me to see this.

Can you resend it without the cached resources? I assume the stuff in _resources can be downloaded from the Internet.

Thank you!

**Comment by ZoltanTakacs** [comment]
Resent on https://github.com/brianchandotcom/liferay-portal/pull/62988

**Pull request closed without merging**
