### PR TITLE
LPS-82850 Prevent wrong versions from being imported

### PR DESCRIPTION
**Pull request by csierra**
thanks for catching this one @topolik

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by csierra** [comment]
@jpince I am looking at the failures from porta-remote-soap-extender-test

**Comment by csierra** [comment]
@jpince they work in isolation but fail if executed after some other test

**Comment by csierra** [comment]
@jpince they seem to be failing randomly, I guess some waiting condition has changed for some reason

**Comment by jpince** [comment]
@csierra thanks

**Pull request closed without merging**
