### PR TITLE
[RESEND] LPS-75190 This needs to be public because it is used from MainServlet (see description of pull, please)

### PR DESCRIPTION
**Pull request by izaera**
Hey @brianchandotcom, you were right: there was no need to change build.gradle files. It was a leftover of previous attempts. I have removed that commit and made a constant public (because it is necessary).

Cheers.

### CODE REVIEW

**Comment by izaera** [comment]
ci:reopen

**Comment by izaera** [comment]
ci:retest

**Comment by izaera** [comment]
ci:retest

**Comment by jpince** [comment]
@izaera this pull should be fine. All of the errors in the last result look CI-related.

**Comment by izaera** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
