### PR TITLE
LPS-74375 Ignores JSDOC warnings

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4bae928303...f52c5faaf4

**Comment by brianchandotcom** [comment]
@jbalsas see f52c5faaf4b6efdd73019a35746f0190e3e7b1ad thx

**Comment by jbalsas** [comment]
Looks good, @brianchandotcom! I didn’t realize. 

I’ll probably consolidate all those 4 other global files in just this new one in followup PRs

**Pull request closed without merging**
