### PR TITLE
Use latest workspace plugin in Project Template Test

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
Tests have passed here: https://github.com/Ithildir/liferay-portal/pull/1040#issuecomment-397688572

**Comment by lawrence-lee** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@lawrence-lee this is already in...

**Pull request closed without merging**
