### PR TITLE
LRQA-36267 | master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-36267

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:reopen

**Comment by austinchiang** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1b0267c8e3...c36eabd2c0

**Pull request closed without merging**
