### PR TITLE
LRQA-71567 | master

### PR DESCRIPTION
**Pull request by bbqbronson**
https://issues.liferay.com/browse/LRQA-71567

### CODE REVIEW

**Comment by bronsonsoda** [comment]
ci:reopen

**Comment by bronsonsoda** [comment]
ci:test:sf

**Comment by bronsonsoda** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bd9713b524...bd4fcb46ee

**Pull request closed without merging**
