### PR TITLE
LPS-164095 Build Service

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:reopen

**Comment by MarinhoFeliphe** [comment]
Hey @brianchandotcom

I did the changes requested [here](https://github.com/brianchandotcom/liferay-portal/pull/125788#issuecomment-1303696482) in these commits below:

[60b123f](https://github.com/brianchandotcom/liferay-portal/pull/125833/commits/60b123f99b4351ecc3608e4a7fe9e3c2abb88070)
[9a71268](https://github.com/brianchandotcom/liferay-portal/pull/125833/commits/9a71268ecfa64044850f307f6b310e66bc07e077)
[278ac04](https://github.com/brianchandotcom/liferay-portal/pull/125833/commits/278ac04fba02abbac62cc7802bbb78073a82e9e4)
[01edf51](https://github.com/brianchandotcom/liferay-portal/pull/125833/commits/01edf5154e2c5147b9bcaeebb2be99acc431c735)
[95c7fb8](https://github.com/brianchandotcom/liferay-portal/pull/125833/commits/95c7fb8ef29461782653b175ba8bd7c86799573a)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/855ffe842d...77219f9239

**Comment by brianchandotcom** [comment]
@MarinhoFeliphe just 77219f9239c028a6a49a979c880bf01daf7b946f

**Pull request closed without merging**
