### PR TITLE
LPS-73465

### PR DESCRIPTION
**Pull request by Ithildir**
Rebased on top of https://github.com/brianchandotcom/liferay-portal/pull/50288 to avoid conflicts.

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@codyhoag fyi

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/39bfbcbe0a...fa626ab0df

**Pull request closed without merging**
