### PR TITLE
LPS-168575 Copy possible error messages and exceptions from /data_layout_builder/end.jsp, also do the following logic:

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

cc @ealonso @IstvanD 

Orignal comment:

Dear Team,

Could you please review this pull request?

Motivation
=======
If importing a Web Content Structure fails, the error message "Error: The structure was not successfully imported." isn't descriptive enough, as the failure could have many reasons. If information about the root cause can be extracted from the exception, at least some of it should be part of the error message presented to the user. 
https://issues.liferay.com/browse/LPS-168575

Proposed Solution
========
If the exception has a message, it is forwarded to the UI to be displayed.

Steps to Verify
========
Please consult the linked LPS for reproduction steps.

Thank you and best regards,
István

### CODE REVIEW

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See [liferay-echo#7560](https://github.com/liferay-echo/liferay-portal/pull/10322)

:heavy_check_mark: ci:test:stable - 28 out of 28 jobs passed
:x: ci:test:relevant - 77 out of 80 jobs passed in 2 hours 6 minutes

**Comment by ozysouza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@IstvanD can you sort the exceptions and resend? Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bccab7449a...6a6e60b2b2

**Pull request closed without merging**
