### PR TITLE
LPS-57919 show category open if there is only one in the product menu

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bc541560a4...60bfbb462a

**Comment by brianchandotcom** [comment]
@juliocamarero please see my changes in upstream. Thx.

**Pull request closed without merging**
