### PR TITLE
LPS-59167 Additional mappings for LiferayDocumentType via config admin and contributor interface

### PR DESCRIPTION
**Pull request by arboliveira**
Re-sending https://github.com/brianchandotcom/liferay-portal/pull/34778. Style concerns from https://github.com/brianchandotcom/liferay-portal/pull/34778#issuecomment-174005417 addressed in https://github.com/arboliveira/liferay-portal/commit/3e8d652fb5de5cf9cd9630e070df1e4a35c36439; closer to original formatting now.

No \ is needed before logExceptionsOnly because since it's the beginning of an entirely new property, just the regular "invisible" line break is fine.

Authors: @arturbr @arboliveira
Reviewer: @mhan810

https://issues.liferay.com/browse/LPS-59167

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:retest

**Comment by arboliveira** [comment]
Rebased.

ci:retest

**Comment by arboliveira** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/927525874b...0e77cea759

**Pull request closed without merging**
