### PR TITLE
LPS-60743 Token whitelists

### PR DESCRIPTION
**Pull request by topolik**
Hi Brian,

I added changes based on https://github.com/brianchandotcom/liferay-portal/pull/34166#issuecomment-171110276 and some more:
- deprecation
- typo
- bug fix with service tracker customizer

Thank you.

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
Aborted due to known start-up issue caused by https://github.com/brianchandotcom/liferay-portal/commit/d992d839572c70e1e93be6c97b1566069941a69f

After this <a href="https://github.com/brianchandotcom/liferay-portal/pull/34330">pull</a> is merged we can re-run this particular pull request.

Sorry for the inconvenience.

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@topolik true test failure. Please resend.

**Comment by topolik** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/34366.

**Pull request closed without merging**
