### PR TITLE
Lps 102160

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by jpince** [comment]
@adolfopa @4lejandrito @austinchiang DLAppTestUtil

@ChiZelin @dantewang can you please notify the product teams when making changes to their modules? I don't usually review pull requests :)

**Comment by jpince** [comment]
@shuyangzhou @dantewang @ChiZelin failures look related
1. semver
```
     [exec] > Task :apps:document-library:document-library-test-util:baseline FAILED
...
     [exec] * com.liferay.document.library.test.util             MINOR      1.0.0      1.0.0      1.1.0      VERSION INCREASE REQUIRED
     [exec] 	+   class      com.liferay.document.library.test.util.DLAppTestUtil
...
```

2. integration test compile failure
```
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/headless/headless-delivery/headless-delivery-test/src/testIntegration/java/com/liferay/headless/delivery/resource/v1_0/test/DocumentFolderResourceTest.java:18: error: package com.liferay.document.library.test.util does not exist
     [exec] import com.liferay.document.library.test.util.DLAppTestUtil;
     [exec]                                              ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/headless/headless-delivery/headless-delivery-test/src/testIntegration/java/com/liferay/headless/delivery/resource/v1_0/test/CommentResourceTest.java:20: error: package com.liferay.document.library.test.util does not exist
     [exec] import com.liferay.document.library.test.util.DLAppTestUtil;
     [exec]                                              ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/headless/headless-delivery/headless-delivery-test/src/testIntegration/java/com/liferay/headless/delivery/resource/v1_0/test/DocumentFolderResourceTest.java:56: error: cannot find symbol
     [exec] 		DLAppTestUtil.addFileEntryWithWorkflow(
     [exec] 		^
     [exec]   symbol:   variable DLAppTestUtil
     [exec]   location: class DocumentFolderResourceTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/headless/headless-delivery/headless-delivery-test/src/testIntegration/java/com/liferay/headless/delivery/resource/v1_0/test/CommentResourceTest.java:143: error: cannot find symbol
     [exec] 		return DLAppTestUtil.addFileEntryWithWorkflow(
     [exec] 		       ^
     [exec]   symbol:   variable DLAppTestUtil
     [exec]   location: class CommentResourceTest
     [exec] Note: Some input files use or override a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] 4 errors
     [exec] 
     [exec] > Task :apps:headless:headless-delivery:headless-delivery-test:compileTestIntegrationJava FAILED
```

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4ff4ad5315...b1d6ff027f

**Comment by dantewang** [comment]
Hi @jpince 
The SemVer was bumped in another pull so it should be fine on latest master.
The compile error has been fixed and sent to https://github.com/tinatian/liferay-portal/pull/1513

**Comment by tinatian** [comment]
@jpince See https://github.com/brianchandotcom/liferay-portal/pull/78955.

**Pull request closed without merging**
