### PR TITLE
LPS-76747

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@shuyangzhou
Using the enhanced for-loop definitely looks better than the general form when iteratin over arrays or collections, but I believe it's also faster?
Can you correct me if I am wrong?

Oracle recommends using the enhanced for-loop: https://docs.oracle.com/javase/tutorial/java/nutsandbolts/for.html

/cc @petershin

**Comment by hhuijser** [comment]
ci:test

**Comment by hhuijser** [comment]
Pull for 7.0.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/19082

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by hhuijser** [comment]
Sounds good. Thanks @shuyangzhou

**Pull request closed without merging**
