### PR TITLE
LPD-42541 When DB Partition is enabled, portal caches should be sharded by default. It is safer and never hurts 

### PR DESCRIPTION
**Pull request by achaparro**
When DB Partition is enabled, most of the portal caches should be sharded. Developers with no sharded caches should indicate it explicitly.

cc/ @tinatian

### CODE REVIEW

**Comment by achaparro** [comment]
Tests passed here: https://github.com/liferay-database-infra/liferay-portal/pull/2431

**Comment by tinatian** [comment]
@achaparro Could you please add test to cover this change? The test should be at cache framework layer which is independent of any specific usage.

**Comment by achaparro** [comment]
Hi @tinatian,

Sure. I already asked Luis here:
https://github.com/brianchandotcom/liferay-portal/pull/156324#issuecomment-2489672468

We will send it today. We had to send the fix first since we had an issue in SaaS with the fragments cache.

Thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1f7b4775e9...3d011d891c

**Pull request closed without merging**
