### PR TITLE
Lps 72240

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @Preston-Crary @shuyangzhou,

From WEM Team, we are trying to have our board up to date, and we've seen that this pull is still waiting to be review for 27 days, Do you have any information about this one?, or Do you know why this one still waiting for review?

Please let us know if we can help you with anything.

Regards,
Eudaldo.

**Comment by Preston-Crary** [comment]
@ealonso,

not sure why it's still in review.

**Comment by ealonso** [comment]
@Preston-Crary,

Could you talk with @brianchandotcom about it? or resend?

**Comment by ealonso** [comment]
@Preston-Crary, hey preston I've rebased the pull and resend here: https://github.com/brianchandotcom/liferay-portal/pull/49458

**Comment by ealonso** [comment]
ci:close

**Pull request closed without merging**
