### PR TITLE
LRQA-34620 Replace ee-7.0.x related jenkins-results-parser unit tests

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-34620

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:reopen

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/609e5b0c0d...f2f1cda7fe

**Pull request closed without merging**
