### PR TITLE
CSS was not extracted with PasswordPoliciesAdminPortlet

### PR DESCRIPTION
**Pull request by JorgeFerrer**
/cc @natevacanaugh, I'm assuming you've seen this but just in case

### CODE REVIEW

**Comment by drewbrokke** [comment]
@natecavanaugh

**Comment by brianchandotcom** [comment]
@drewbrokke does this mean we have duplicate CSS now? Or did we remove, but forgot to readd?

Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8806043a96...2fb4e70745

**Comment by drewbrokke** [comment]
We have duplicate CSS at the moment.

**Comment by brianchandotcom** [comment]
What's the long term goal?

**Comment by drewbrokke** [comment]
After talking with Nate, we may need to wait on this.  I'm going to ask around to make sure there's not a better existing pattern, or if we need to figure out a new way to avoid redundant CSS.

**Pull request closed without merging**
