### PR TITLE
[TOP PRIORITY]LPS-59939 Remove calls to Registry in Journal [PING]

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
cc @jkappler :clap: :clap:  :clap:

**Comment by juliocamarero** [comment]
cc @hhuijser

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/db7335b60e...61c92ea546

**Pull request closed without merging**
