### PR TITLE
LPS-79755

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@hhuijser I cherry picked what I could as you requested.

**Comment by brianchandotcom** [comment]
@ahdezma as you requested. It's published now.

**Comment by ahdezma** [comment]
@hhuijser @brianchandotcom I think the new version hasn't been published yet :)

**Pull request closed without merging**
