### PR TITLE
LPS-79385 Rename UADEntityAnonymizer to UADAnonymizer

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-79385](https://issues.liferay.com/browse/LPS-79385).<br><br>Hey Brian, this changes all instances of UADEntityAnonymizer to UADAnonymizer.  Please allow the tests to finish<br><br>/cc @pei-jung @willnewbury @dejuknow

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test

**Comment by timpak** [comment]
@kenjiheigel @michaelhashimoto @yichenroy FYI. Test report wasn't generated.

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by drewbrokke** [comment]
@alee8888 are these failures related?  They don't seem related to me.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9617ddf318...9d1cbf7288

**Pull request closed without merging**
