### PR TITLE
Lps 200501

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @marianoalvarosaiz @achaparro

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by achaparro** [comment]
Hi @shuyangzhou,

We thought about implementing this logic before but it was a bit weird to have a forEach method that executes the logic even when there were not elements to iterate. 

Anyways, since this case for new DBs when the default company is not loaded, just a few calls are affected by this and are maintaining by us, so maybe we can assume this behavior. It makes the code cleaner too.

Something I have realized is that we don't need a consumer for this case, the companyId as parameter can't be used when DBPartition is not enabled or companies are not loaded, should we change it to use Runnable?

Thanks.

cc/ @marianoalvarosaiz @luisortiz89

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e0326a7488...b8826697b2

**Comment by brianchandotcom** [comment]
@shuyangzhou see b8826697b2de2c60ba8facc4489e4008e01fc943 I think we can just reuse this?

**Pull request closed without merging**
