### PR TITLE
LPS-74101

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@brianchiu @nicolelau fyi

**Comment by jpince** [comment]
@mhan810 
`    [junit] org.osgi.framework.BundleException: Could not resolve module: com.liferay.portal.security.wedeploy.auth.test [131]`
`    [junit]   Unresolved requirement: Import-Package: com.liferay.arquillian.extension.junit.bridge.junit`

**Comment by mhan810** [comment]
@jpince thx i saw earlier.

**Comment by jpince** [comment]
@yichenroy console snippet should include one more line at the top, in this case `[junit] org.osgi.framework.BundleException: Could not resolve module: com.liferay.portal.security.wedeploy.auth.test [131]`

**Comment by yichenroy** [comment]
@jpince thanks for reporting, I will make a ticket and make the change

**Comment by jpince** [comment]
@yichenroy thanks. not a critical priority, since the error i quoted is
repeated a few lines down, just want to see it at the top :)

**Pull request closed without merging**
