### PR TITLE
LRCI-699 Update DXP build marker files

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:sharepoint

**Comment by brianchandotcom** [comment]
@petershin is this safe to merge? See CI error. Probably a bad rebase by you?

**Comment by brianchandotcom** [comment]
@petershin please resend. Thx.

**Comment by yichenroy** [comment]
@petershin 
Looks like it was a fluke, network issue:
`ssh: Could not resolve hostname github.com: Name or service not known
fatal: Could not read from remote repository.`

**Pull request closed without merging**
