### PR TITLE
LRQA-63123, LRQA-63131, LRQA-63167, LRQA-63168 | master

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://issues.liferay.com/browse/LRQA-63123
https://issues.liferay.com/browse/LRQA-63131
https://issues.liferay.com/browse/LRQA-63167
https://issues.liferay.com/browse/LRQA-63168

7.3.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/32337

Note: Only need to backport LRQA-63167 to 7.3.x, thx.

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:reopen

**Comment by JoyceWang08211** [comment]
ci:test:sf

**Comment by JoyceWang08211** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d05c09b36b...ae4cadc8d9

**Pull request closed without merging**
