### PR TITLE
LRQA-37766 Use the invoked time for data points instead of start time

### PR DESCRIPTION
**Pull request by pyoo47**
LRQA-37766 Use the invoked time for data points instead of start time

Please publish after merging

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test

**Comment by brianchandotcom** [comment]
I stopped it on Jenkins... we have a lot of traffic

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@pyoo47 published...

**Pull request closed without merging**
