### PR TITLE
LPS-73336 SF

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/99ee72499d...2809be327d

**Comment by robertoDiaz** [comment]
Hey @yuhai, 

Can you backport this?

Thanks!

**Comment by yuhai** [comment]
Hi @robertoDiaz 

Yes, I will do this.

Regards,
Hai

**Pull request closed without merging**
