### PR TITLE
LPS-77163 SF sample code

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f85f293bbf...9a38a1cbd5

**Comment by brianchandotcom** [comment]
@jbalsas you're getting good.. really good :)

**Comment by jbalsas** [comment]
Thanks @brianchandotcom! I'm pretty much just proxying stuff, everyone is getting on board and contributing more and more, which is definitely starting to show ;)

**Pull request closed without merging**
