### PR TITLE
LPD-41445 Update app.bnd-localization for OpenSearch (Prep for Marketplace release)

### PR DESCRIPTION
**Pull request by lipusz**
https://liferay.atlassian.net/browse/LPD-41445

Hi Brian,

Resending https://github.com/brianchandotcom/liferay-portal/pull/156687 with a simplified version.

Thanks,
Tibor

cc: @rbohl

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6a71843483...392e25a701

**Comment by brianchandotcom** [comment]
@lipusz just a0c3cfbdefccfb5dc9f0618ab26013d13a1180c5

**Comment by lipusz** [comment]
Thanks!

**Pull request closed without merging**
