### PR TITLE
LPS-65616 Two "Content Display Page" page templates display after upgrading from 6.2 to 7.0

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:/ @juliocamarero

**Comment by juliocamarero** [comment]
👍

**Comment by brianchandotcom** [comment]
@shuyangzhou see random FTL error, I've seen this a few times now.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7d397162b9...5ab0020ce1

**Pull request closed without merging**
