### PR TITLE
LPS-160997 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-160997

This is only for master.

@ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure cases are unrelated to changes.
See https://github.com/liferay-echo/liferay-portal/pull/9353
✔️ ci:test:stable - 27 out of 27 jobs passed
❌ ci:test:relevant - 898 out of 956 jobs passed in 2 hours 50 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9f2e30e91a...a622b83976

**Comment by brianchandotcom** [comment]
@ealonso I'm going to have @ling-alan-huang rename these packages

```
package com.liferay.site.memberships.web.internal.servlet.taglib.clay;

import com.liferay.frontend.taglib.clay.servlet.taglib.BaseBaseClayCard;
import com.liferay.frontend.taglib.clay.servlet.taglib.VerticalCard;
import com.liferay.portal.kernel.dao.search.RowChecker;
import com.liferay.portal.kernel.language.LanguageUtil;
import com.liferay.portal.kernel.model.Role;
import com.liferay.portal.kernel.theme.ThemeDisplay;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.WebKeys;

import javax.portlet.RenderRequest;

import javax.servlet.http.HttpServletRequest;

/**
 * @author Eudaldo Alonso
 */
public class RoleVerticalCard extends BaseBaseClayCard implements VerticalCard {
```

Should be package com.liferay.site.memberships.web.internal.frontend.taglib.clay.servlet.taglib

**Pull request closed without merging**
