### PR TITLE
LPS-61420

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by evannagayama** [comment]
@brianchandotcom @hhuijser 
This PR seems to have introduced functional issues.
Test results here: https://testray.liferay.com/home/-/testray/runs/47239534
image

**Comment by brianchiu** [comment]
@evannagayama 
Can you double check? If it's an issue with navigating to the product menu, it should've failed all the functional batches.

**Comment by evannagayama** [comment]
ci:retest

I'll build and investigate it

**Comment by evannagayama** [comment]
@brianchandotcom looks ok to merge. We'll keep an eye on these tests. Thanks!

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
