### PR TITLE
[Static Reference] LPS-182296 UploadImageUtil

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4ae234fb0d...6376840c85

**Comment by brianchandotcom** [comment]
@slnn @dantewang are you sure this is right?

```
	public static final String TEMP_IMAGE_FILE_NAME = "tempImageFileName";

	public static final String TEMP_IMAGE_FOLDER_NAME = "java.lang.Class";
```

Where did java.lang.Class come from?

**Comment by brianchandotcom** [comment]
@dantewang @slnn see my fixes in 8c9a9d7a to match the original logic at

```
	public static String getTempImageFolderName() {
		Class<?> clazz = UploadImageUtil.class.getClass();

		return clazz.getName();
	}
```

I ended up inlining it all at 9ad6ce2436720c434e57490281d89e8f7f428bb3

**Pull request closed without merging**
