### PR TITLE
LRQA-41602 Use test suite 'relevant' for central merge pull requests

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-41602

7.0.x https://github.com/brianchandotcom/liferay-portal-ee/pull/20455

Please publish **com.liferay.jenkins.results.parser.jar** after merging

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@pyoo47 published.

**Pull request closed without merging**
