### PR TITLE
LPS-76373

### PR DESCRIPTION
**Pull request by matethurzo**
@brianchandotcom next up is the addAssetLinks method in the addClassedModel

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a3c9f41e8b...90229a2c0e

**Comment by brianchandotcom** [comment]
@matethurzo I merged this, but can you change it to asset-entry-priority? Especially since we'll have asset-link?

Thx.

**Comment by matethurzo** [comment]
@brianchandotcom sure i'll send a follow up pull

**Pull request closed without merging**
