### PR TITLE
LPS-59692

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cb20d730e4...9d50deb1f5

**Comment by brianchandotcom** [comment]
@shuyangzhou see 18b0149f88589ef0028216ce1906c37d3ab82d30

Not sure if you'd approve

@danielkocsis why is it an ORM exception? I thought those were all caught and replaced with SystemExceptions?

**Comment by shuyangzhou** [comment]
This does not look right.
@danielkocsis what kind of error you are seeing? And how to reproduce it?

Please let us know the detail, I will have @mtambara take a closer look on this.

**Comment by danielkocsis** [comment]
Hi @shuyangzhou,

Based on mysql deadlock log the problem is that private and public layout set publication fires 2 separate Background tasks and those 2 tries to acquire a lock which ends up in update/add operations on the Lock table what triggers index updates in the exact same moment and this is what causes a deadlock ORMException. This code piece is prepared for these race conditions with the re-try logic, but only in case of SystemExceptions. So that is the reason why I changed catch here.

To reproduce the issue you have to create a site, add 1 public and 1 private layout and try to turn local staging on.

Please let me know your findings!

**Comment by shuyangzhou** [comment]
Ok, thanks @danielkocsis !

@mtambara please get it reproduced locally first, then we start to look into this issue.

**Comment by mtambara** [comment]
@brianchandotcom @danielkocsis We looked into the deadlock and the proposed solution of looping on ORMExceptions is correct. Looks good!

**Comment by shuyangzhou** [comment]
This is actually a design flaw of LockLocalService that is throwing inconsistent type of exceptions. Without fixing LockLocalService, this is the only way to do it. I will revisit this a bit later to make LockLocalService behaves consistently, so that this won't be needed any more, and I will revert it after that.

**Pull request closed without merging**
