### PR TITLE
LPS-58298 Rename view to markupView on taglibs

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@ealonso can you send a follow up pull?

markupView="<%= view

portal-web/docroot/html/taglib/portlet/icon_options/page.jsp

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7ede44ae4e...91512d4b53

**Comment by brianchandotcom** [comment]
@ealonso besides markupView="<%= view, can you also see 91512d4b5300e19a2f252223a4840a4ef79a0351

And see if that is still needed? Thx.

**Pull request closed without merging**
