### PR TITLE
Revert LPD-30790

### PR DESCRIPTION
**Pull request by JerryAdrianoo**
I'm reversing it because it needs a new design.

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
@JerryAdrianoo The reason of the revert is to follow a different approach and avoid service.ranking, not because of regressions.

**Comment by JerryAdrianoo** [comment]
> @JerryAdrianoo The reason of the revert is to follow a different approach and avoid service.ranking, not because of regressions.

Default message 😅 
Fixed! Thanks.

**Comment by marianoalvarosaiz** [comment]
Thanks a lot @JerryAdrianoo !

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fe6c405a4c...48c459da33

**Pull request closed without merging**
