### PR TITLE
LPS-62767 Senna update

### PR DESCRIPTION
**Pull request by kenjiheigel**
Resend of https://github.com/brianchandotcom/liferay-portal/pull/36322

### CODE REVIEW

**Comment by kenjiheigel** [comment]
@brianchandotcom, this is the SPA update that @brunobasto, @jbalsas, and @eduardolundgren have been working on. Some tests will fail due to this addition, but I've discussed this with @brianchiu and @jpince and we have decided to disable those tests for now and will work on getting those working after this has been added to master. If there are additional failures in this pull, I will disable those tests as well. Let me know if you have any questions, thanks!

**Comment by kenjiheigel** [comment]
I have disabled the following tests that fail due to the SPA update in https://github.com/kenjiheigel/liferay-portal/commit/adc9d3311d78ea5243a30671d0f8aa8671c929c4 and https://github.com/kenjiheigel/liferay-portal/commit/df272c06e066f8308a29e9e78af7387852b52b9a. I'll be working to get them passing again and will keep you updated. Let me know if you have additional questions, thanks!

@evannagayama:
WebcontentpublicationUsecase#AssetPublisherSiteAndGlobalScopeAccessibility

@kmaria: 
ExportImport#ExportImportSampleLARPortlet
PGStaging#ActivateRemoteStaging
PGStaging#StagingPublishPortlet

@vicnate5:
PGDynamicdatalists#ConfigureSpreadsheetListPG
WorkflowForms#ViewDateAssetDetails
WorkflowadminPGPagerevision#ApprovePageRevisionPG
WorkflowadminPGPagerevision#RejectPageRevisionPG

@alee8888:
CPMydashboard#JoinSitePrivateNo
CPUsergroups#AddMember
CPUsergroups#DeleteUserGroup
CPSitememberships#RemoveMember
CPSitememberships#AddMembersSiteUser
PasswordpoliciesUsecase#ViewUserAccountLockout
PortalconfigurationUsecase#DefaultPortalLandingPage
RecyclebinUsecase#RestoreDMDocumentFromFolderCP

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/61aa5ae9f1...d09d63b7fd

**Comment by brianchandotcom** [comment]
@Ithildir can you review modules/frontend/frontend-js-spa-web/build.gradle

@brunobasto @kenjiheigel good job guys :) 

cc @eduardolundgren

**Comment by Ithildir** [comment]
I see that there's no `.task-cache`, so CI tries to download Node and NPM modules every time. I'm working on it...

**Comment by Ithildir** [comment]
I sent a pull with minor Gradle fixes and the task cache configuration at https://github.com/brianchandotcom/liferay-portal/pull/36372.

**Pull request closed without merging**
