### PR TITLE
LPS-71224

### PR DESCRIPTION
**Pull request by Ithildir**
Rebased on top of https://github.com/brianchandotcom/liferay-portal/pull/47517 to avoid conflicts.

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:retest

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@codyhoag fyi

**Pull request closed without merging**
