### PR TITLE
LPS-60471 Remove arrows until position is fixed

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @sharonchoi, these tests keep failing, but I'm not sure why... I've tried locally both in Chrome and Firefox, and what I see in the Poshi screenshots does not match what I'm seeing here. Could you please investigate?

Thanks a lot!

**Comment by sharonchoi** [comment]
hey @jbalsas, yeah, sorry I wasn't able to push a test fix in to you yesterday. I'll try to work on them today.

**Comment by jbalsas** [comment]
@sharonchoi that's fine, let me know if there's something I should do. Thanks so much!! :relaxed:

**Comment by sharonchoi** [comment]
@jbalsas So it looks like, the tests are failing due to some slow loading issues, that may/may not be caused by a javascript error that's being thrown. 

`JAVA_SCRIPT_ERROR: mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create [http://localhost:8080/combo/?browserId=firefox&minifierType=&languageId=en_US&b=7000&t=1453909263158&/o/frontend-js-metal-web-1.0.0/metal/src/core.js&/o/frontend-js-metal-web-1.0.0/metal/src/object/object.js&/o/frontend-js-metal-web-1.0.0/metal/src/disposable/Disposable.js&/o/frontend-js-metal-web-1.0.0/metal/src/events/EventHandle.js&/o/frontend-js-metal-web-1.0.0/metal/src/events/DomEventHandle.js&/o/frontend-js-metal-web-1.0.0/metal/src/dom/dom.js&/o/frontend-js-metal-web-1.0.0/metal-position/src/Geometry.js&/o/frontend-js-metal-web-1.0.0/metal-position/src/Position.js&/o/frontend-js-metal-web-1.0.0/metal-position/src/Align.js&/o/frontend-js-metal-web-1.0.0/metal/src/events/EventHandler.js&/o/frontend-js-metal-web-1.0.0/metal/src/array/array.js&/o/frontend-js-metal-web-1.0.0/metal/src/string/string.js&/o/frontend-js-metal-web-1.0.0/metal/src/dom/features.js&/o/frontend-js-metal-web-1.0.0/metal/src/eval/globalEval.js&/o/frontend-js-metal-web-1.0.0/metal/src/html/html.js&/o/frontend-js-metal-web-1.0.0/metal/src/events/EventEmitter.js&/o/frontend-js-metal-web-1.0.0/metal/src/async/async.js&/o/frontend-js-metal-web-1.0.0/metal/src/attribute/Attribute.js&/o/frontend-js-metal-web-1.0.0/metal/src/component/ComponentRegistry.js&/o/frontend-js-metal-web-1.0.0/metal/src/component/ComponentCollector.js&/o/frontend-js-metal-web-1.0.0/metal/src/component/ComponentRenderer.js&/o/frontend-js-metal-web-1.0.0/metal/src/events/EventEmitterProxy.js&/o/frontend-js-metal-web-1.0.0/metal/src/component/EventsCollector.js&/o/frontend-js-metal-web-1.0.0/metal/src/component/SurfaceCollector.js&/o/frontend-js-metal-web-1.0.0/metal/src/component/Component.js&/o/frontend-js-metal-web-1.0.0/metal/src/soy/SoyTemplates.js&/o/frontend-js-metal-web-1.0.0/metal/src/soy/SoyAop.js&/o/frontend-js-soyutils-web/soyutils.js&/o/frontend-js-metal-web-1.0.0/metal/src/soy/SoyRenderer.js&/o/frontend-js-metal-web-1.0.0/metal-dropdown/src/Dropdown.soy.js&/o/frontend-js-metal-web-1.0.0/metal-jquery-adapter/src/JQueryAdapter.js&/o/frontend-js-metal-web-1.0.0/metal-dropdown/src/Dropdown.js:6]`

For the announcements test, there seems to be a bug with the ellipsis icon not loading after a user marks an announcement as read. The only workaround so far, is to refresh the page, so that the icon appears again, so that's why the dropdown isn't displaying.

**Comment by jbalsas** [comment]
Hi @sharonchoi, thanks for investigating... I've pushed an additional commit, trying to see if it helps...

**Comment by jbalsas** [comment]
ci:retest

**Comment by sharonchoi** [comment]
@jbalsas Ok, I do see one test fix so far, and am still analyzing the others to narrow it down some more, so I'll resend w/ the test fixes as needed, after confirming results from the retest.

**Comment by sharonchoi** [comment]
@jbalsas So it looks like these tests will require test fixes:
PGDocumentsandmedia#EditDocumentType
CPCustomfields#EditCustomFieldUserBoolean

These are the tests that exposed a bug w/ the missing ellipsis icon, not appearing until after a page refresh:
PGAnnouncements#HideAnnouncementsEntry
PGTags#RemoveTagVia Blogs

All tests failing from pr-tester are still getting the js errors mentioned in the earlier comments.

Going to ask @brianchandotcom to please close this pr. 

We'll send in test fixes on a separate pull. @alee8888 @evannagayama @vicnate5

Thanks!

**Comment by brianchandotcom** [comment]
Please resend. Thx.

**Comment by sharonchoi** [comment]
@jbalsas Ok, I sent one test fix for `PGDocumentsandmedia#EditDocumentType` here: https://github.com/brianchandotcom/liferay-portal/pull/35093

Let me know if you still need help narrowing down the other issues.

**Comment by jbalsas** [comment]
Hi @sharonchoi, thanks a lot!

I'll try again, but from what I saw, those changes are CI-only, so I'll be definitely needing some help to fix the tests. Who should I ask?

**Pull request closed without merging**
