### PR TITLE
LPS-58473 SF

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @arthurchan35

**Comment by jpince** [comment]
@pyoo47 @michaelhashimoto the PR test results got stuck?

**Comment by jpince** [comment]
ci:retest

**Comment by pyoo47** [comment]
@jpince Seems like the results came up OK.  Maybe it was just slow for some reason? The failure was because one of the modules-integration tests froze and timed out.
```
     [exec] com.liferay.arquillian.extension.junit.bridge.junit.test.ArquillianTest > testBeforeAfterClass STARTED
     [exec] 
     [exec] com.liferay.arquillian.extension.junit.bridge.junit.test.ArquillianTest > testBeforeAfterClass STANDARD_ERROR
     [exec]     SLF4J: Class path contains multiple SLF4J bindings.
     [exec]     SLF4J: Found binding in [jar:file:/opt/dev/projects/github/liferay-portal/bundles/tomcat-8.0.32/webapps/ROOT/WEB-INF/lib/util-slf4j.jar!/org/slf4j/impl/StaticLoggerBinder.class]
     [exec]     SLF4J: Found binding in [jar:file:/opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-log4j12/1.5.11/c3fbec782ff5fc7fa50cfeeb67502ded9efd58d9/slf4j-log4j12-1.5.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
     [exec]     SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
     [exec]     SLF4J: Actual binding is of type [com.liferay.util.sl4fj.LiferayLoggerFactory]
     [exec] 
     [exec] com.liferay.arquillian.extension.junit.bridge.junit.test.ArquillianTest > testBeforeAfterClass STANDARD_OUT
     [exec]     Loading jar:file:/opt/dev/projects/github/liferay-portal/bundles/tomcat-8.0.32/webapps/ROOT/WEB-INF/lib/portal-impl.jar!/system.properties
     [exec]     Loading file:/opt/dev/projects/github/liferay-portal/bundles/tomcat-8.0.32/webapps/ROOT/WEB-INF/classes/system-ext.properties
Build timed out (after 120 minutes). Marking the build as aborted.
Build was aborted
```

**Comment by jpince** [comment]
@pyoo47 it passed, good enough for me. thanks!

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
