### PR TITLE
PHP Portlets: remove runtime support

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@migue I'll fix LibraryReferenceTest errors.

**Comment by migue** [comment]
@brianchandotcom Thanks a lot. I didn't know we had this kind of tests :(

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/44a0cce5d2...f740b0f298

**Comment by brianchandotcom** [comment]
@migue please see my changes in upstream. Thx.

**Pull request closed without merging**
