### PR TITLE
LPS-67996

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by hhuijser** [comment]
@Ithildir compile error because gradle-plugins calls new method in SF.
I thought this one would fix that, but I guess it didn't: https://github.com/brianchandotcom/liferay-portal/pull/42911/commits/d2a7edc30243189293712d15819a0afbe2546d5b

**Comment by Ithildir** [comment]
Hi @hhuijser! You added a new method in `FormatSourceTask` that you're trying to use in `gradle-plugins`, right? Then you have to publish a fake `gradle-plugins-source-formatter` (please update the `CHANGELOG.markdown file) and update the `gradle-plugins` dependency.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@hhuijser I merged this, but can you update the changelog? Thx.

**Comment by Ithildir** [comment]
@hhuijser, can you please also update the [readme](https://github.com/liferay/liferay-portal/blob/master/modules/sdk/gradle-plugins-source-formatter/README.markdown)? Thank you! :blush:

**Pull request closed without merging**
