### PR TITLE
LPS-61343 Delete method and tests.

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
@brandizzi, can we remove the other constructor?

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brandizzi** [comment]
@marcellustavares I don't think so, the other constructor is used a lot elsewhere (and is the most natural constructor after all.)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/539ce29229...62ecfb8ba4

**Pull request closed without merging**
