### PR TITLE
LPS-94990 Move also contributor fields their corresponding package and propagate changes accordingly

### PR DESCRIPTION
**Pull request by jkappler**
Hey @brianchandotcom, fixed rebase isssues from the previous pull.

I moved the interfaces to new packages, so we shouldn't get the issues we were getting. I left fragments for another pull because I have some doubts about it.

Sice InfoDisplayObject is linked to InfoDisplayContributor, I left it out of refactoring, since one cannot exist without the other.

The last commit is optional, in case we want a separate package for fields (but it can be left out). I still moved them.

I also changed the bnd files that you changed, so as not to add version ranges.

Please let me know what you thing.

Thanks

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @pavel-savinov

**Comment by pavel-savinov** [comment]
Hi @brianchandotcom, taking into account what we've just talked about, we still need this PR  to have our interfaces in the appropriate packages. Thanks!

**Comment by brianchandotcom** [comment]
This looks very good @pavel-savinov @jkappler 

I hope to be able to merge it tomorrow. Been swamped and this one is super tricky to backport.

**Comment by brianchandotcom** [comment]
@jkappler @pavel-savinov this was crazy to backport. For your edification:

13512e484a4ee358f69d73dd6843b9ebb0dd98c0
4488ea26f2f2f7e293ed7d0181c0ef32a3c8fb5b
6045024ea0f01b8a12f7f1f4db4081f797ead80b
18f3879014283d0eb22e3cc5975e0a2a84500d5e in 7.2.x

and 

2ae7d7a8c8deb9c25d6e21bf8a801d1cb7bfff76 in 7.1.x.

Just so you have an idea.. I'd never expect you guys to pull this off.

**Pull request closed without merging**
