### PR TITLE
LPS-74457

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@petershin, I sent pulls to add the property `git.liferay.portal.branch` to the subrepos for portal. Can you check with Shinn and do the same for the private ee ones?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/98bba70430...10f28b2bd4

**Comment by petershin** [comment]
@hhuijser - Sent pulls to update the 7.0.x-private subrepos

**Pull request closed without merging**
