### PR TITLE
LPS-54170

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@hhuijser instead of skipping those files in 6c42723c4a41e148df7518bcd442471d1b64d507

Can you run "ant format-javadoc -Dlimit=WikiGroupServiceConfiguration" on those broken files and keep removing parts of the file until we find out exactly which lines are breaking it, and then just manually SF them to fix it?

Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/168a135c78...5a50e68cd6

**Comment by hhuijser** [comment]
Hey @brianchandotcom 

I know why it's breaking... it's not incorrect formatting, just something qdox can't handle:

WikiGroupServiceConfiguration.java line 130 and 141
PortletViewController.java line 15

**Comment by brianchandotcom** [comment]
I rolled back just that part in bb48e663b251f92930bc5f5f9e99d4dc7d62f568

**Comment by brianchandotcom** [comment]
I actually just ran it on WikiGroupServiceConfiguration and it worked for me?

**Pull request closed without merging**
