### PR TITLE
LPS-57864

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@mhan810 that test failure seems real. Didn't happen except with this pull. Please resend. Thx.

**Comment by brianchandotcom** [comment]
@mhan810 I'm reopening this because it may have been fixed by https://github.com/brianchandotcom/liferay-portal/pull/29291

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by mhan810** [comment]
@brianchandotcom this failure's completely unrelated.  It's similar to the one from for PollsStagedModelDataHandler a few weeks ago.  The error is the timestamp is 1s off between the expected and the actual model object.

I'll rebase and resend again just in case

**Comment by shuyangzhou** [comment]
Hey Guys,

@mhan810 is right, this is the exact same error that @willnewbury fixed a couple days ago for Polls, it must be caused by some similar reason. Some broken export/import timestamp. 

But I don't get why it is very consistent here as it supposes to be random. But anyway, I don't see how it could be directly caused by this pull, but might indirectly the persistenceimpl change somehow expose it to be consistent.

@mhan810 if this is not in hurry, I can have @willnewbury to resend your pull to @brianchandotcom with fix to this failure. He is on something else, should able to start on this a bit later today.

**Comment by mhan810** [comment]
Unfortunately, it’s relative urgent since I need it to get the background
task in.



I’m running a debugger right now between my calls



*From:* Shuyang Zhou [mailto:notifications@github.com]
*Sent:* Friday, August 14, 2015 1:11 PM
*To:* brianchandotcom/liferay-portal <liferay-portal@noreply.github.com>
*Cc:* Michael Han <michael.han@liferay.com>
*Subject:* Re: [liferay-portal] LPS-57864 (#29289)



Hey Guys,

@mhan810 <https://github.com/mhan810> is right, this is the exact same
error that @willnewbury <https://github.com/willnewbury> fixed a couple
days ago for Polls, it must be caused by some similar reason. Some broken
export/import timestamp.

But I don't get why it is very consistent here as it supposes to be random.
But anyway, I don't see how it could be directly caused by this pull, but
might indirectly the persistenceimpl change somehow expose it to be
consistent.

@mhan810 <https://github.com/mhan810> if this is not in hurry, I can have
@willnewbury <https://github.com/willnewbury> to resend your pull to
@brianchandotcom <https://github.com/brianchandotcom> with fix to this
failure. He is on something else, should able to start on this a bit later
today.

—
Reply to this email directly or view it on GitHub
<https://github.com/brianchandotcom/liferay-portal/pull/29289#issuecomment-131197682>
.

**Comment by shuyangzhou** [comment]
Ok, if that's the case we will leave it to you.

Just this might help, see https://github.com/liferay/liferay-portal/commit/50037b522af57771d02f30cb37888c7a003f0aeb

It could be as dumb as another *StagedModelDataHandler with wrong date setting.

**Comment by mhan810** [comment]
Yep it is as simple as that.  In the MBMessageStagedModeDH, we’re calling:



_mbMessageLocalService.updateAnswer(
   importedMessage, message.isAnswer(), false);





After we’ve imported the model.  So of course, we have a race condition L



*From:* Shuyang Zhou [mailto:notifications@github.com]
*Sent:* Friday, August 14, 2015 1:19 PM
*To:* brianchandotcom/liferay-portal <liferay-portal@noreply.github.com>
*Cc:* Michael Han <michael.han@liferay.com>
*Subject:* Re: [liferay-portal] LPS-57864 (#29289)



Ok, if that's the case we will leave it to you.

Just this might help, see liferay@50037b5
<https://github.com/liferay/liferay-portal/commit/50037b522af57771d02f30cb37888c7a003f0aeb>

It could be as dumb as another *StagedModelDataHandler with wrong date
setting.

—
Reply to this email directly or view it on GitHub
<https://github.com/brianchandotcom/liferay-portal/pull/29289#issuecomment-131199962>
.

**Comment by shuyangzhou** [comment]
Great, you found it:)

**Pull request closed without merging**
