### PR TITLE
LPS-135465 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-135465

This is only for master.

@jkappler

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure case is unrelated to changes in this PR.
See https://github.com/liferay-echo/liferay-portal/pull/5143
✔️ ci:test:stable - 9 out of 9 jobs passed
❌ ci:test:relevant - 20 out of 22 jobs passed in 2 hours 17 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/81bcf8b5d6...160fdfbbba

**Comment by brianchandotcom** [comment]
@jkappler see 4b1d33f2d639d4006d85401a5f8edf7a9dce8319

Also, shouldn't this be the default behavior for all "url". It seems like we're overriding something that should be part of the default validator for urls.

**Pull request closed without merging**
