### PR TITLE
LPS-89711

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:sf

**Comment by brianchandotcom** [comment]
@ruben-pulido can you resend after you have basic CRUD. Afterwards, let's write one small test that creates, reads, updates, and deletes. Then, I'd like to generate tests for them. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7b33f9191c...ef0c1b0f41

**Comment by brianchandotcom** [comment]
@ruben-pulido @adolfopa I did a partial merge. See upstream and my previous comment. Thx.

**Pull request closed without merging**
