### PR TITLE
LPS-65078 Workflow is not usable after upgrade from ee-6.1 to 7.0 DXP

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by jhendley** [comment]
Stopping because something is wrong here. Will restart. ci:stop

**Comment by jhendley** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@shuyangzhou db2 log error? fyi.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4c5a74a5dd...144ed49faa

**Comment by shuyangzhou** [comment]
@brianchandotcom it is actually a search failure. @arboliveira can you take a look? Thanks
```
  [junit] 22:28:46,438 WARN  [liferay/search_writer/SYSTEM_ENGINE-10][ProxyMessageListener:84] com.liferay.portal.kernel.search.SearchException: Unable to delete document com_liferay_configuration_admin_web_portlet_SystemSettingsPortlet_PORTLET_com.liferay.portal.search.configuration.IndexWriterHelperConfiguration
    [junit] com.liferay.portal.kernel.search.SearchException: Unable to delete document com_liferay_configuration_admin_web_portlet_SystemSettingsPortlet_PORTLET_com.liferay.portal.search.configuration.IndexWriterHelperConfiguration
    [junit] 	at com.liferay.portal.search.elasticsearch.internal.ElasticsearchIndexWriter.deleteDocument(ElasticsearchIndexWriter.java:135)
    [junit] 	at sun.reflect.GeneratedMethodAccessor1412.invoke(Unknown Source)
    [junit] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit] 	at java.lang.reflect.Method.invoke(Method.java:606)
    [junit] 	at com.liferay.portal.kernel.messaging.proxy.ProxyRequest.execute(ProxyRequest.java:86)
    [junit] 	at com.liferay.portal.kernel.messaging.proxy.ProxyMessageListener.receive(ProxyMessageListener.java:54)
    [junit] 	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:74)
    [junit] 	at com.liferay.portal.kernel.messaging.ParallelDestination$1.run(ParallelDestination.java:52)
    [junit] 	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask._runTask(ThreadPoolExecutor.java:756)
    [junit] 	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask.run(ThreadPoolExecutor.java:667)
    [junit] 	at java.lang.Thread.run(Thread.java:745)
    [junit] Caused by: java.lang.IllegalStateException: Future got interrupted
    [junit] 	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:44)
    [junit] 	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:67)
    [junit] 	at com.liferay.portal.search.elasticsearch.internal.ElasticsearchIndexWriter.deleteDocument(ElasticsearchIndexWriter.java:123)
    [junit] 	... 10 more
    [junit] Caused by: java.lang.InterruptedException
    [junit] 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:996)
    [junit] 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1303)
    [junit] 	at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:276)
    [junit] 	at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:116)
    [junit] 	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:42)
    [junit] 	... 12 more
    [junit] 22:28:46,438 WARN  [liferay/search_writer/SYSTEM_ENGINE-5][ProxyMessageListener:84] com.liferay.portal.kernel.search.SearchException: Unable to delete document com_liferay_configuration_admin_web_portlet_SystemSettingsPortlet_PORTLET_com.liferay.portal.search.configuration.IndexStatusManagerConfiguration
    [junit] com.liferay.portal.kernel.search.SearchException: Unable to delete document com_liferay_configuration_admin_web_portlet_SystemSettingsPortlet_PORTLET_com.liferay.portal.search.configuration.IndexStatusManagerConfiguration
    [junit] 	at com.liferay.portal.search.elasticsearch.internal.ElasticsearchIndexWriter.deleteDocument(ElasticsearchIndexWriter.java:135)
    [junit] 	at sun.reflect.GeneratedMethodAccessor1412.invoke(Unknown Source)
    [junit] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit] 	at java.lang.reflect.Method.invoke(Method.java:606)
    [junit] 	at com.liferay.portal.kernel.messaging.proxy.ProxyRequest.execute(ProxyRequest.java:86)
    [junit] 	at com.liferay.portal.kernel.messaging.proxy.ProxyMessageListener.receive(ProxyMessageListener.java:54)
    [junit] 	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:74)
    [junit] 	at com.liferay.portal.kernel.messaging.ParallelDestination$1.run(ParallelDestination.java:52)
    [junit] 	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask._runTask(ThreadPoolExecutor.java:756)
    [junit] 	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask.run(ThreadPoolExecutor.java:667)
    [junit] 	at java.lang.Thread.run(Thread.java:745)
    [junit] Caused by: java.lang.IllegalStateException: Future got interrupted
    [junit] 	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:44)
    [junit] 	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:67)
    [junit] 	at com.liferay.portal.search.elasticsearch.internal.ElasticsearchIndexWriter.deleteDocument(ElasticsearchIndexWriter.java:123)
    [junit] 	... 10 more
    [junit] Caused by: java.lang.InterruptedException
    [junit] 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:996)
    [junit] 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1303)
    [junit] 	at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:276)
    [junit] 	at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:116)
    [junit] 	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:42)
    [junit] 	... 12 more
    [junit] 22:28:46,438 WARN  [liferay/search_writer/SYSTEM_ENGINE-9][ProxyMessageListener:84] com.liferay.portal.kernel.search.SearchException: Unable to delete document com_liferay_configuration_admin_web_portlet_SystemSettingsPortlet_PORTLET_com.liferay.portal.search.configuration.IndexerRegistryConfiguration
    [junit] com.liferay.portal.kernel.search.SearchException: Unable to delete document com_liferay_configuration_admin_web_portlet_SystemSettingsPortlet_PORTLET_com.liferay.portal.search.configuration.IndexerRegistryConfiguration
    [junit] 	at com.liferay.portal.search.elasticsearch.internal.ElasticsearchIndexWriter.deleteDocument(ElasticsearchIndexWriter.java:135)
    [junit] 	at sun.reflect.GeneratedMethodAccessor1412.invoke(Unknown Source)
    [junit] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit] 	at java.lang.reflect.Method.invoke(Method.java:606)
    [junit] 	at com.liferay.portal.kernel.messaging.proxy.ProxyRequest.execute(ProxyRequest.java:86)
    [junit] 	at com.liferay.portal.kernel.messaging.proxy.ProxyMessageListener.receive(ProxyMessageListener.java:54)
    [junit] 	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:74)
    [junit] 	at com.liferay.portal.kernel.messaging.ParallelDestination$1.run(ParallelDestination.java:52)
    [junit] 	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask._runTask(ThreadPoolExecutor.java:756)
    [junit] 	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask.run(ThreadPoolExecutor.java:667)
    [junit] 	at java.lang.Thread.run(Thread.java:745)
    [junit] Caused by: java.lang.IllegalStateException: Future got interrupted
    [junit] 	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:44)
    [junit] 	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:67)
    [junit] 	at com.liferay.portal.search.elasticsearch.internal.ElasticsearchIndexWriter.deleteDocument(ElasticsearchIndexWriter.java:123)
    [junit] 	... 10 more
    [junit] Caused by: java.lang.InterruptedException
    [junit] 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:996)
    [junit] 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1303)
    [junit] 	at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:276)
    [junit] 	at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:116)
    [junit] 	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:42)
    [junit] 	... 12 more
    [junit] 22:28:46,438 WARN  [liferay/search_writer/SYSTEM_ENGINE-8][ProxyMessageListener:84] com.liferay.portal.kernel.search.SearchException: Unable to delete document com_liferay_configuration_admin_web_portlet_SystemSettingsPortlet_PORTLET_com.liferay.asset.categories.navigation.web.configuration.AssetCategoriesNavigationPortletInstanceConfiguration
    [junit] com.liferay.portal.kernel.search.SearchException: Unable to delete document com_liferay_configuration_admin_web_portlet_SystemSettingsPortlet_PORTLET_com.liferay.asset.categories.navigation.web.configuration.AssetCategoriesNavigationPortletInstanceConfiguration
    [junit] 	at com.liferay.portal.search.elasticsearch.internal.ElasticsearchIndexWriter.deleteDocument(ElasticsearchIndexWriter.java:135)
    [junit] 	at sun.reflect.GeneratedMethodAccessor1412.invoke(Unknown Source)
    [junit] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit] 	at java.lang.reflect.Method.invoke(Method.java:606)
    [junit] 	at com.liferay.portal.kernel.messaging.proxy.ProxyRequest.execute(ProxyRequest.java:86)
    [junit] 	at com.liferay.portal.kernel.messaging.proxy.ProxyMessageListener.receive(ProxyMessageListener.java:54)
    [junit] 	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:74)
    [junit] 	at com.liferay.portal.kernel.messaging.ParallelDestination$1.run(ParallelDestination.java:52)
    [junit] 	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask._runTask(ThreadPoolExecutor.java:756)
    [junit] 	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask.run(ThreadPoolExecutor.java:667)
    [junit] 	at java.lang.Thread.run(Thread.java:745)
    [junit] Caused by: java.lang.IllegalStateException: Future got interrupted
    [junit] 	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:44)
    [junit] 	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:67)
    [junit] 	at com.liferay.portal.search.elasticsearch.internal.ElasticsearchIndexWriter.deleteDocument(ElasticsearchIndexWriter.java:123)
    [junit] 	... 10 more
    [junit] Caused by: java.lang.InterruptedException
    [junit] 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:996)
    [junit] 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1303)
    [junit] 	at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:276)
    [junit] 	at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:116)
    [junit] 	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:42)
    [junit] 	... 12 more
    [junit] 22:28:46,438 WARN  [liferay/search_writer/SYSTEM_ENGINE-6][ProxyMessageListener:84] com.liferay.portal.kernel.search.SearchException: Unable to delete document com_liferay_configuration_admin_web_portlet_SystemSettingsPortlet_PORTLET_com.liferay.portal.search.configuration.QueryPreProcessConfiguration
    [junit] com.liferay.portal.kernel.search.SearchException: Unable to delete document com_liferay_configuration_admin_web_portlet_SystemSettingsPortlet_PORTLET_com.liferay.portal.search.configuration.QueryPreProcessConfiguration
    [junit] 	at com.liferay.portal.search.elasticsearch.internal.ElasticsearchIndexWriter.deleteDocument(ElasticsearchIndexWriter.java:135)
    [junit] 	at sun.reflect.GeneratedMethodAccessor1412.invoke(Unknown Source)
    [junit] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit] 	at java.lang.reflect.Method.invoke(Method.java:606)
    [junit] 	at com.liferay.portal.kernel.messaging.proxy.ProxyRequest.execute(ProxyRequest.java:86)
    [junit] 	at com.liferay.portal.kernel.messaging.proxy.ProxyMessageListener.receive(ProxyMessageListener.java:54)
    [junit] 	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:74)
    [junit] 	at com.liferay.portal.kernel.messaging.ParallelDestination$1.run(ParallelDestination.java:52)
    [junit] 	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask._runTask(ThreadPoolExecutor.java:756)
    [junit] 	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask.run(ThreadPoolExecutor.java:667)
    [junit] 	at java.lang.Thread.run(Thread.java:745)
    [junit] Caused by: java.lang.IllegalStateException: Future got interrupted
    [junit] 	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:44)
    [junit] 	at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:67)
    [junit] 	at com.liferay.portal.search.elasticsearch.internal.ElasticsearchIndexWriter.deleteDocument(ElasticsearchIndexWriter.java:123)
    [junit] 	... 10 more
    [junit] Caused by: java.lang.InterruptedException
    [junit] 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:996)
    [junit] 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1303)
    [junit] 	at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:276)
    [junit] 	at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:116)
    [junit] 	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:42)
    [junit] 	... 12 more
```

**Pull request closed without merging**
