### PR TITLE
LPS-76234 SF - Rename

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0f755ced49...b971c24a21

**Comment by brianchandotcom** [comment]
@ealonso @jkappler see b971c24a21c5629016112703ce8d1093d2320a37

**Comment by brianchandotcom** [comment]
@ealonso more here e6c2764 can you apply else where? Thx.

**Pull request closed without merging**
