### PR TITLE
LPS-104193 Unifying inputs markup between sites and depot

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
cc/ @adolfopa

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/956cff0e5a...6711b116bc

**Pull request closed without merging**
