### PR TITLE
LPS-60186

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@JorgeFerrer there is a compile error in this pull you sent me.

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Argh, I missed one build.gradle file. Is this module not compiled when doing "ant all" because it is in "test"?

I've resent it as https://github.com/brianchandotcom/liferay-portal/pull/32157

**Pull request closed without merging**
