### PR TITLE
LPS-75031 DLSync OSGi

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @adolfopa @4lejandrito

**Comment by sergiogonzalez** [comment]
cc/ @dejuknow this is the pull that extracts DLSyncEvent to its own OSGi module. 
We have a dependency in document-library-service in PortalCapabilityLocatorImpl.java class to ensure that it will always be satisfied when the document library service is enabled.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/31c1397822...04137cfda7

**Comment by brianchandotcom** [comment]
@adolfopa @sergiogonzalez  can you send a follow up pull and rename

DLSync#syncEventId to dlSyncEventId ?

Thx

**Pull request closed without merging**
