### PR TITLE
LRQA-32732, LRQA-32604 | master

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LRQA-32732
https://issues.liferay.com/browse/LRQA-32604

### CODE REVIEW

**Comment by brianchiu** [comment]
The failure doesn't have anything to do with Maria's changes.

'''
junit.framework.AssertionFailedError: 
The default JVM time zone "US/Pacific-New" is not UTC or GMT. Please review the JVM property "user.timezone".
	at com.liferay.portal.log.assertor.PortalLogAssertorTest.scanXMLLogFile(PortalLogAssertorTest.java:168)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:100)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:90)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXMLLog(PortalLogAssertorTest.java:88)
'''

**Comment by brianchandotcom** [comment]
@shuyangzhou does this have to do with your new time zone changes?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d0c8b0ec54...22e39c1f34

**Comment by shuyangzhou** [comment]
@brianchandotcom it was fine when you merged it here https://github.com/brianchandotcom/liferay-portal/pull/49170 and the pull support sent to me here https://github.com/shuyangzhou/liferay-portal/pull/4331, someone must have modified something for the tcserver test since that point.

**Pull request closed without merging**
