### PR TITLE
LPS-114252 Upgrade process for FragmentEntry and FragmentEntryVersion

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/1127

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d74f4dfa2c...67048d57ab

**Comment by brianchandotcom** [comment]
@sandrodw3 @ealonso @ruben-pulido I made a lot of changes in my origin. Please review.

**Pull request closed without merging**
