### PR TITLE
LPS-133532

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-133532.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:reopen

**Comment by jonmak08** [comment]
Manually forward because there is a bug in blogs that is failing the PR on CI.  Confirmed by @zhangyan0701

**Comment by jonmak08** [comment]
ci:test:sf

**Comment by jonmak08** [comment]
ci:test:relevant

**Comment by jonmak08** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/06fe1f4a91...94020f9c55

**Pull request closed without merging**
