### PR TITLE
LPS-109790 Also on depot

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hey @brianchandotcom,

I fixed those commands and also the ones in depot (https://github.com/brianchandotcom/liferay-portal/pull/86018/commits/dbdd3de60d00539abfe6a29d99dd3b4acaf7d9a5).

It would be awesome for us if you could merge this as soon as possible. I have more stuff on top of this but I don't want to send a huge pull request to you. Also it will help us parallelise more work.

Thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9ea991f67f...5e1db137a3

**Comment by brianchandotcom** [comment]
@4lejandrito see my changes in my origin thx.

**Comment by 4lejandrito** [comment]
Thanks @brianchandotcom!

**Pull request closed without merging**
