### PR TITLE
LRQA-25479 Look for the startup message before hitting liferay portal

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRQA-25479

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:stop (upstream had an issue)

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:stop

Need to increase the timeout for starting up the portal.

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e028f64f30...bc85fd85cd

**Pull request closed without merging**
