### PR TITLE
LPS-107666 Port portal-search-web tests from Karma to Jest

### PR DESCRIPTION
**Pull request by wincent**
This is one of the three places in liferay-portal where we were using Karma. We'd like to move away from Karma because it has not proved to be very reliable in our experience, as described in [IFI-1371](https://issues.liferay.com/browse/IFI-1371).

Note that in porting this to Jest I re-enabled one test that has been marked as "skipped" since 560b35a0749a7faa3 (July 2019, LRQA-50065, "LRQA-50065 Quarantine search js unit test"). It passes fine under Jest, so I presume that it was disabled precisely because of the Karma-related flakiness that is mentioned above.

As a bonus, moving to Jest makes these tests run about 25% faster (5 seconds, down from 6.5 seconds), because we avoid the overhead of spinning up a full headless browser.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/489efaf667...21f2e37f26

**Comment by brianchandotcom** [comment]
@thektan @arboliveira please enforce in your team

@wincent please automate and disallow karma

**Comment by brianchandotcom** [comment]
@hhuijser can you work with @wincent on banning Karma. It could be done easily in SF vs. lint since we're already reading package.json and you can error if the word karma is in it.

**Comment by wincent** [comment]
@brianchandotcom: We probably don't need any additional enforcement. Once I've removed the two other usage sites (working on it now), we'll eliminate it from the top-level package.json and there are already measures in place to prevent it being added back (we don't allow per-project `devDependencies`, and [the global, top-level `devDependencies` is strictly controlled](https://github.com/liferay/liferay-portal/blob/8cfa3581acfeb1c0831998f5b04272c607212498/modules/package.json#L2-L13)).

**Pull request closed without merging**
