### PR TITLE
LPS-92211 SF

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test:change-tracking

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/be34e3cc13...035db894e0

**Comment by brianchandotcom** [comment]
@rolandpakai can you talk to @jbalsas about running our CSF lint? See 035db894e03b280e86ff685e765d9aa2b3b1aa46 thx.

**Comment by rolandpakai** [comment]
Sure, Thanks @brianchandotcom !

**Pull request closed without merging**
