### PR TITLE
LPS-144888 Use isSet() to check whether a variable was set, instead of an old pattern by using contains() 

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Tested [here](https://github.com/ling-alan-huang/liferay-portal/pull/592), unrelated failures.

https://issues.liferay.com/browse/LPS-144888

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:reopen

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4b8a8a122f...b7a80e2f31

**Pull request closed without merging**
