### PR TITLE
LPS-65407 Image Editor in Documents and Media

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey Brian,

This is a resend of https://github.com/brianchandotcom/liferay-portal/pull/39617#issuecomment-218353429 including frontend in the package and the module name (we forgot to include it).

Thanks!

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @ambrinchaudhary

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8868ac570b...305c27ac1b

**Comment by brianchandotcom** [comment]
Thx @sergiogonzalez please see my changes in upstream. @ambrinchaudhary

**Comment by brianchandotcom** [comment]
@sergiogonzalez this pull actually had a JSPc error in it. I didn't catch it until after I merged this pull and this error showed up in other pulls. I just fixed it via

3958250542b644aae948c6cc8176f01c4d2df819

**Pull request closed without merging**
