### PR TITLE
LPS-72691

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@shuyangzhou can you take a look at the modules-int* consistent failing now. I don't think it's related to this.

**Comment by brianchandotcom** [comment]
@brandizzi can you resend and rename

setTermDisplayContexts and getTermDisplayContexts

to getFolderSearchFacetTermDisplayContexts and setFolderSearchFacetTermDisplayContexts?

Thx. Please do it with changes from @mhan810

**Comment by shuyangzhou** [comment]
@brianchandotcom it should be fine after this https://github.com/brianchandotcom/liferay-portal/pull/56854

**Pull request closed without merging**
