### PR TITLE
LPS-126305 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-126305

This is only for master.

@david-gutierrez-mesa
@alexcandidos

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure case is unrelated to changes in PR.
See https://github.com/liferay-echo/liferay-portal/pull/3602
✔️ ci:test:stable - 9 out of 9 jobs passed
❌ ci:test:relevant - 21 out of 26 jobs passed in 1 hour 52 minutes

**Comment by brianchandotcom** [comment]
@Tim-Cao rebase error, please resend?

**Comment by Tim-Cao** [comment]
Resent to https://github.com/brianchandotcom/liferay-portal/pull/98359

**Pull request closed without merging**
