### PR TITLE
LRQA-62408 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRQA-62408

This is only for master.

@david-gutierrez-mesa

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure case is not related to changes in PR.
See https://github.com/Tim-Cao/liferay-portal/pull/478
✔️ ci:test:stable - 7 out of 7 jobs passed
❌ ci:test:relevant - 28 out of 31 jobs passed in 1 hour 47 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bb4e3dc19a...5b335a225c

**Comment by brianchandotcom** [comment]
@Tim-Cao can you send me pulls to expand portal-web/test/functional/com/liferay/portalweb/dependencies/test-theme.war in all branches? Yucky that it's a black box like this.

**Comment by brianchandotcom** [comment]
@Tim-Cao all branches should include 7.3.x. Thx!

**Comment by Tim-Cao** [comment]
@brianchandotcom This change only for 7.4 since the liferay version is defined in liferay-plugin-package.properties. However, that war includes lots of files. Should I expand or not?

**Comment by brianchandotcom** [comment]
@Tim-Cao yes, so for master, 7.3.x, 7.2.x (and any other branch), send me pulls to expand the WAR.

So in the future, it'll just be a tiny change to a few files in the WAR. I dont' like updating an entire 3 megabyte war (while hiding changes in the WAR from Git history).

**Comment by Tim-Cao** [comment]
Got it. I will do that. Thanks

**Comment by brianchandotcom** [comment]
@Tim-Cao and in the future, if you see binary blobs that can be easily expanded, please proactively do so because it's much better for Git history. Thx!

**Pull request closed without merging**
