### PR TITLE
LPS-169211 Add support for Freemarker script in the notification template

### PR DESCRIPTION
**Pull request by danvb112**
Related Issues:

https://issues.liferay.com/browse/LPS-169045
https://issues.liferay.com/browse/LPS-169211
https://issues.liferay.com/browse/LPS-168333

### CODE REVIEW

**Comment by danvb112** [comment]
ci:reopen

**Comment by danvb112** [comment]
Hey @brianchandotcom, this PR is related to GIVI's high priority story, which is FreeMarker in the notification template, I'm submitting it directly after our QA team reviews the unrelated fails in the original PR

**Comment by brianchandotcom** [comment]
@danvb112 wrong package for NotificationTemplateFTLElementsMVCResourceCommand

Compare to all other MVCResourceCommands

Type: g ls-files **MVCResourceCommand**

**Comment by gabrielwas** [comment]
resent here: https://github.com/liferay-objects/liferay-portal/pull/1414

**Pull request closed without merging**
