### PR TITLE
LPS-56953 Adding export-import-api module

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/527da2a9ce...62b3872b25

**Pull request closed without merging**
