### PR TITLE
master-qa-24346

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LRQA-24346
https://issues.liferay.com/browse/LRQA-24360
https://issues.liferay.com/browse/LRQA-24361

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:stop

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fdc4f01d64...025a8ad97a

**Comment by pyoo47** [comment]
@brianchandotcom  Hashi and Leslie already made a change to fix this issue. The failure that you seeing above is the github message for the first pull request test that Hashi had stopped (which is why the top-level build states that it was aborted. There should be another GitHub message posted for the retest that Hashi initiated after he committed the fix.

**Pull request closed without merging**
