### PR TITLE
LPS-66856

### PR DESCRIPTION
**Pull request by samuelkong**

### CODE REVIEW

**Comment by samuelkong** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pyoo47 nodes are randomly dying? See how plugins-compile failed once and worked afterward.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a23d8367e5...8ae3f725f2

**Comment by pyoo47** [comment]
@brianchandotcom An out of memory error occurred while compiling the sample-hibernate-portlet the first time but it didn't happen the second time. I'll talk to Leslie to see if we can reduce the memory footprint during plugins-compile.

**Pull request closed without merging**
