### PR TITLE
LPS-89658 Extract common code

### PR DESCRIPTION
**Pull request by cgoncas**
@brianchandotcom, @ahdezma

I have implemented a fix for the tests, in order to add the SortContextProviderTest, but for me, it is totally OK if you think another fix it is better :).

Thanks!

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:reopen

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f24abe8087...c79c693f05

**Comment by brianchandotcom** [comment]
@cgoncas this is perfect. I would have never figured that out. Good job!

@ahdezma fyi.

**Pull request closed without merging**
