### PR TITLE
Lps 57004

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@michaelhashimoto can you check what's going on in the previous aborted build.

For example in https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-backend%28master%29/408/AXIS_VARIABLE=14,label_exp=!master/consoleFull

test-class-group:
[ivy:resolve] :: Apache Ivy 2.4.0 - 20141213170938 :: http://ant.apache.org/ivy/ ::
[ivy:resolve] :: loading settings :: file = /opt/dev/projects/github/liferay-portal/tools/sdk/ivy-settings.xml
Build timed out (after 60 minutes). Marking the build as aborted.
Build was aborted
Recording test results
No test report files were found. Configuration error?

Looks like an ivy resolving timeout?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/77be87f724...a85f76f155

**Comment by brianchandotcom** [comment]
I undid the merge.. until this is stable.

**Comment by brianchandotcom** [comment]
NIce. this pull works. Just the same issues as before.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/36b6acbd97...ee4c39942c

**Pull request closed without merging**
