### PR TITLE
LPS-71050

### PR DESCRIPTION
**Pull request by danielkocsis**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by Alec-Shay** [comment]
ci:retest

**Comment by holatuwol** [comment]
Connection closed error might be fixed by [LPS-71736](https://issues.liferay.com/browse/LPS-71736), so retesting to confirm.

**Comment by Alec-Shay** [comment]
Re-sent at: https://github.com/brianchandotcom/liferay-portal/pull/48269

**Pull request closed without merging**
