### PR TITLE
LPS-100864 Update tests for SingleUpdateDueDateModal

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by jpince** [comment]
@yichenroy 
```
[beanshell] java.util.concurrent.TimeoutException: Timeout occurred while executing Bash commands: [git ls-remote -h git@cloud-10-0-0-14:liferay/liferay-portal-ee.git cache-liferay-3838dac2ae9689eceb6374dee03b44cf836abfdb-liferay-3838dac2ae9689eceb6374dee03b44cf836abfdb]
[beanshell] 	at com.liferay.jenkins.results.parser.JenkinsResultsParserUtil.executeBashCommands(JenkinsResultsParserUtil.java:383)
[beanshell] 	at com.liferay.jenkins.results.parser.GitUtil.executeBashCommands(GitUtil.java:414)
[beanshell] 	at com.liferay.jenkins.results.parser.GitUtil.getRemoteGitRefs(GitUtil.java:227)
[beanshell] 	at com.liferay.jenkins.results.parser.GitUtil.getRemoteGitBranches(GitUtil.java:132)
[beanshell] 	at com.liferay.jenkins.results.parser.GitWorkingDirectory.getRemoteGitBranches(GitWorkingDirectory.java:1504)
[beanshell] 	at com.liferay.jenkins.results.parser.GitWorkingDirectory.getRemoteGitBranch(GitWorkingDirectory.java:1454)
[beanshell] 	at com.liferay.jenkins.results.parser.GitWorkingDirectory.getRemoteGitBranch(GitWorkingDirectory.java:1426)
[beanshell] 	at com.liferay.jenkins.results.parser.GitHubDevSyncUtil.fetchCacheBranchFromGitHubDev(GitHubDevSyncUtil.java:128)
```

**Comment by jpince** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
@jpince looks like the error was due to network issues with connection to our local github nodes:
```
 [parallel] java.lang.RuntimeException: Unable to get remote refs from git@cloud-10-0-0-11:liferay/liferay-portal-ee.git
 [parallel] packet_write_wait: Connection to 10.0.0.11 port 22: Broken pipe
 [parallel] fatal: Could not read from remote repository.
```

We're seeing this on a lot of pull request tests from the past hour, we'll investigate and let IT know if necessary.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/259947811d...3e9d16642e

**Pull request closed without merging**
