### PR TITLE
LPS-78548 Hydrates components if they have a data attribute too

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
Hey @brianchandotcom, after this, could you please do a snapshot release of all the themes?

We are trying to get the theme tooling ready for the Beta program and Milestone 1 of 7.1.

Thanks!

**Comment by brianchandotcom** [comment]
@jbalsas can you resend, rebase error.  Thx.

**Comment by jbalsas** [comment]
Done -> https://issues.liferay.com/browse/LPS-78548

**Pull request closed without merging**
