### PR TITLE
LPS-75389 Add integration test

### PR DESCRIPTION
**Pull request by inacionery**
/cc @brandizzi

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest (Jenkins master went down)

**Comment by jpince** [comment]
@brianchandotcom looks good from a functional test perspective.

**Comment by brianchandotcom** [comment]
@inacionery conflict, please resend? thx.

**Comment by inacionery** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/52729

**Pull request closed without merging**
