### PR TITLE
Lps 74863

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
@pyoo47

What's going on here? There is no subrepo change.

```
/opt/dev/projects/github/liferay-subrepo-tools/bin/git-lpush -b master -o 66c7a5f29a25ae31578879e29d3a248ffeb8769f -s ffe366b8656207f007e210a4a43126170a251df1 -r liferay-portal -v
master: Verifying.
error: Illegal change to a .gitrepo file.
```

**Comment by pyoo47** [comment]
@shuyangzhou We're investigating this issue. We will let you know

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
@shuyangzhou I just pushed up a fix for this.. hopefully this issue is resolved. I'll be watching the progress of this pull.

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/039365af90...8185ea15ab

**Pull request closed without merging**
