### PR TITLE
LPS-74288 Updates npm-shrinkwrap (auto-generated)

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b656484339...bc72ff1430

**Comment by brianchandotcom** [comment]
@jbalsas @brunobasto please backport. Thx.

**Comment by jbalsas** [comment]
Hey @brianchandotcom, this adds a new feature not meant to be backported

**Pull request closed without merging**
