### PR TITLE
LPS-55545

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-55545](https://issues.liferay.com/browse/LPS-55545).<br><br>

### CODE REVIEW

**Comment by drewbrokke** [comment]
See my comment [here](https://github.com/brianchandotcom/liferay-portal/pull/26851#issuecomment-106485760).

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/861cf783b0...a699ceb6ee

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/861cf783b0...5437225526

**Comment by brianchandotcom** [comment]
Minor changes in upstream. Thx.

**Pull request closed without merging**
