### PR TITLE
LRQA-60385 | master

### PR DESCRIPTION
**Pull request by rodrigocunhaa**
Tested here: https://github.com/rodrigocunhaa/liferay-portal/pull/196

I'm manually sending it to save CI resource since the fail is not related.

### CODE REVIEW

**Comment by rodrigocunhaa** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e8879a9db7...ab5d02b166

**Comment by brianchandotcom** [comment]
@rodrigocunhaa I backported this to 7.3.x for you.

**Comment by rodrigocunhaa** [comment]
Thanks @brianchandotcom

**Pull request closed without merging**
