### PR TITLE
Lps 72742

### PR DESCRIPTION
**Pull request by shuyangzhou**
@juliocamarero I have redone your change for LPS-60400 from https://github.com/brianchandotcom/liferay-portal/pull/32088 , see https://github.com/brianchandotcom/liferay-portal/commit/738a4a8bcfbd01b5d99fd6f2f502d1be36a934f2 and https://github.com/brianchandotcom/liferay-portal/commit/ce84540325178141607e4470cc63f403ea8bb1aa

@pavel-savinov I rewrote your solution by reusing the PRP processing logic from PortletContainerImpl, otherwise we would have a big chunk of duplicated code which is very hard for long term maintain. See https://github.com/brianchandotcom/liferay-portal/commit/b0516cc6ab355f722c421473e6c0ac22cd4fcb0d and https://github.com/brianchandotcom/liferay-portal/commit/f7cb9e2f1b0881caca642d26a96b94b34a76090c

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@shuyangzhou can you take a look  at

DocumentLibraryConvertProcessTest.testMigrateDLAndKeepFilesInSourceStore

Somehow it crept in? I'm not sure if it's because the CI changed or some env changed. I don't recall merging in a pull to cause this.

**Comment by shuyangzhou** [comment]
@brianchandotcom this is how it crept in https://github.com/liferay/liferay-portal/pull/1510
@stsquared99 why you stopped that merge pull and force merged it? It would fail the merge test and be rejected. Now master is broken.

@brianchandotcom the issue is at https://github.com/liferay/liferay-portal/blob/master/modules/apps/adaptive-media/adaptive-media-document-library-thumbnails/src/main/java/com/liferay/adaptive/media/document/library/thumbnails/internal/AdaptiveMediaImageEntryProcessor.java it overwrites the buildin https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/documentlibrary/util/ImageProcessorImpl.java but on purposely avoid delegating some of its methods (according to its commit message https://github.com/liferay/liferay-portal/commit/735bcd47b763e6b26ab2b4a9e1916e57ec29e4f6). A simple fix would be delegating all methods to ImageProcessorImpl, but I don't think that's what adaptive-media team wants.

So either we have adaptive-media team fixing this by their business logic, or we rollback the whole auto merge (which should not happen in the first place), if there is a way to do so.

**Comment by shuyangzhou** [comment]
@brianchandotcom and there is more, see https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/118076/AXIS_VARIABLE=0,label_exp=!master/testReport/ the adaptive-media's own tests are failing too.

We really should roll this back if it is doable. The code quality is not good enough to be merged into master yet.

**Comment by shuyangzhou** [comment]
@brianchandotcom the SplitPackagesTest is caused by adaptive-media too, see https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/111119/AXIS_VARIABLE=0,label_exp=!master/testReport/. 

And it is not lpkg buildable at see :
```
move-artifact:
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:240: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1101: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1317: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/modules/build-app.xml:75: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/modules/build-app.xml:77: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/modules/build-app.xml:180: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/modules/build-app-module.xml:292: Warning: Could not find file /opt/dev/projects/github/liferay-portal/bundles/osgi/modules/com.liferay.adaptive.media.demo.jar to copy.
```
That's why all the lpkg tests are failing.

**Comment by stsquared99** [comment]
@shuyangzhou @brianchandotcom
I forced the merge at BChan's request

**Comment by juliocamarero** [comment]
thanks @shuyangzhou!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6680a54998...3e32cfb3cd

**Pull request closed without merging**
