### PR TITLE
LPS-169086 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-169086

This is only for master.

@lfbesada
cc @ruben-pulido

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.
See https://github.com/liferay-echo/liferay-portal/pull/10476
ci:test:stable - 27 out of 28 jobs passed
ci:test:relevant - 161 out of 192 jobs passed in 2 hours 3 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6e1264e64b...a2c0a025ce

**Comment by brianchandotcom** [comment]
@lfbesada see e7fd63e86ec6f53ff559cdb4d9fd367b09b211cd and a2c0a025cef97d78c9557baca474ba7a29349cae

**Pull request closed without merging**
