### PR TITLE
LRQA-51488 Run buildLang

### PR DESCRIPTION
**Pull request by brianwulbern**

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:reopen (lang key update, don't need to run the full suite of tests)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7666609c76...5495dc0ff1

**Comment by brianchandotcom** [comment]
Thanks @brianwulbern for catching that!

**Comment by brianwulbern** [comment]
@brianchandotcom I have some good translators in my corner :)

**Pull request closed without merging**
