### PR TITLE
LPS-62369 This needs to be greedy to avoid issues with the startup order of the modules

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @robertoDiaz @nikkiprudencio

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3670bfb384...604ce75b67

**Comment by brianchandotcom** [comment]
@rotty3000 in case this is not kosher

**Comment by rotty3000** [comment]
@brianchandotcom it's not that it's really "wrong" however...

@sergiogonzalez I think you could have made this  simpler by just doing
```
	@Reference(cardinality = ReferenceCardinality.AT_LEAST_ONE)
```
this way the component won't start until there's one, and since you only care for one, don't worry about being dynamic.

**Comment by brianchandotcom** [comment]
@sergiogonzalez please update based on best practice from @rotty3000 ? Thanks.

**Comment by sergiogonzalez** [comment]
Hey @rotty3000 the thing is that we want this component to start even if there's no item selector, that's why we marked this as optional. The issue here was that as it didn't have GREEDY it wasn't wired when the component item selector was available. 

I guess that we could set AT_LEAST_ONE but then we would need to check whether BlogsItemSelectorHelper is null (in case that it hasn't started) in EditEntryMVCRenderCommand and we would have the same issue but in a different class, right?

Thx!

**Comment by rotty3000** [comment]
Why do you want the component to start? It's a no op without an item
selector!

**Comment by rotty3000** [comment]
However, with AT_LEAST_ONE + DYNAMIC or MULTIPLE + DYNAMIC, you don't need
GREEDY.

**Comment by rotty3000** [comment]
I got it btw.

@brianchandotcom understanding their use case the change is fine the way it is. It's good that they have understood the usage. Thanks @sergiogonzalez

**Comment by rotty3000** [comment]
@brianchandotcom I think you can reopen and merge this PR.

**Pull request closed without merging**
