### PR TITLE
Lps 86820 2

### PR DESCRIPTION
**Pull request by shuyangzhou**
10sec now

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1631a092a6...ed175bc06c

**Comment by brianchandotcom** [comment]
@shuyangzhou I backported this to 7.2.x, but was not able to cherry pick to 7.1.x. Can you send me a pull?

**Comment by brianchandotcom** [comment]
@shuyangzhou I made tiny changes in upstream too.

**Pull request closed without merging**
