### PR TITLE
master-vw-414

### PR DESCRIPTION
**Pull request by vicnate5**
@brandizzi @brunobasto @achaparro @ctampoya

Resend of https://github.com/brianchandotcom/liferay-portal/pull/41020

No 7.0.x backported needed at this time

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
@achaparro After talking to @brandizzi we are thinking this might be needed in 7.0.x
Can you confirm that it is needed in 7.0.x or is not needed?

I will resend this again based on your response.

**Comment by achaparro** [comment]
Hey @vicnate5,

Yes, we need these changes in 7.0.x and 6.2.x too (it comes from a customer issue). Let me know if you need some help to do those backports.

Thanks!

**Comment by vicnate5** [comment]
Resent https://github.com/brianchandotcom/liferay-portal/pull/41119

**Pull request closed without merging**
