### PR TITLE
LPS-66430 User Group search in Role assignment searches all user groups instead of currently assigned user groups

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-66430](https://issues.liferay.com/browse/LPS-66430).

### CODE REVIEW

**Comment by vicnate5** [comment]
Poshi test failures are unrelated to this pull. Test fix sent here https://github.com/brianchandotcom/liferay-portal/pull/41636

**Comment by brianchandotcom** [comment]
@drewbrokke can you send me a follow up pull:

```
	@BeforeClass
	public static void setUpClass() throws Exception {
		_role = RoleTestUtil.addRole(RoleConstants.TYPE_REGULAR);

		_companyId = _role.getCompanyId();

		_count = UserGroupLocalServiceUtil.searchCount(
			_companyId, null, new LinkedHashMap<String, Object>());

		_userGroup1 = UserGroupTestUtil.addUserGroup();
		_userGroup2 = UserGroupTestUtil.addUserGroup();

		GroupLocalServiceUtil.addRoleGroup(
			_role.getRoleId(), _userGroup1.getGroupId());
	}

	@AfterClass
	public static void tearDownClass() throws Exception {
		RoleLocalServiceUtil.deleteRole(_role);
		UserGroupLocalServiceUtil.deleteUserGroup(_userGroup1);
		UserGroupLocalServiceUtil.deleteUserGroup(_userGroup2);
	}
```

use DeleteAfterTestRun instead of manually deleting them. But you'll need to change setUpClass to setUp I believe.

2.) Also, I renamed PARAM_KEYS_USER_GROUP_FINDER to PARAM_KEYS. I think that's good enough? If you disagree, send me a change. Thx.

**Comment by drewbrokke** [comment]
@brianchandotcom will do.

**Comment by drewbrokke** [comment]
Follow-up pull: brianchandotcom#41646

**Pull request closed without merging**
