### PR TITLE
LPS-86121 SF

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by jpince** [comment]
@brianchiu @kyle-miho see failure in `PortalSmoke#SmokeWithDeveloperProperties`, not sure if it's related or a fluke

**Comment by kyle-miho** [comment]
looking rn

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
@jpince I am inclined to say that the error is not a fluke, likely because of the javascript error that occurs:
`JAVA_SCRIPT_ERROR: TypeError: n is undefined [http://localhost:8080/combo/?browserId=firefox&minifierType=&languageId=en_US&b=7200&t=1544473457391&/o/layout-taglib/layouts_tree/js/layouts_tree.js&/o/layout-taglib/layouts_tree/js/layouts_tree_node_radio.js&/o/layout-taglib/layouts_tree/js/layouts_tree_radio.js&/o/layout-taglib/layouts_tree/js/layouts_tree_node_task.js&/o/layout-taglib/layouts_tree/js/layouts_tree_selectable.js&/o/frontend-js-web/liferay/translation_manager.js&/o/dynamic-data-mapping-web/js/ddm_form.js&/o/journal-web/js/main.js&/o/frontend-js-web/aui/aui-ace-editor/aui-ace-editor-min.js&/o/frontend-js-web/liferay/source_editor.js&/o/frontend-js-`
I don't want to have to resort rebuild my portal with these changes to investigate further, as this is a front-end-infrastructure story and I should be focusing/investigating on current WEM issues, so I will end my investigation here.

**Comment by jpince** [comment]
ci:close @kyle-miho thanks

@john-co can you please investigate the failure in `PortalSmoke#SmokeWithDeveloperProperties`?

cc/ @vicnate5

**Comment by jpince** [comment]
@john-co @jbalsas I think all this test does is add `include-and-override=portal-developer.properties` to portal-ext, which brings in the properties from https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/portal-developer.properties. So maybe there is something set in portal-developer.properties that doesn't play nicely with these changes?

**Comment by vicnate5** [comment]
@koor is looking into this since John Co is out.

**Comment by jbalsas** [comment]
Hey @jpince, based on the output, that test should actually be doing the opposite, as a `combo` url is being requested. That's actually the contrary to developer environment

**Comment by koor4356** [comment]
@jbalsas when "include-and-override=portal-developer.properties" is set in portal-ext, web content is gray out and javascript type error "n is undefined" is displayed.
screen shot 2018-12-11 at 10 06 59 am

**Comment by jbalsas** [comment]
Hey @jpince, @koor4345, @vicnate5, I’ll check with these exact settings, but they’re inherently wrong.

In https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/portal-developer.properties, `javascript.fast.load` should be set to `false` as opposed to the default value which is true.

Could you make that change and retest to see if we still reproduce? Looks like there might be something there, but might be due to a missconfiguration rather than a real error.

**Comment by koor4356** [comment]
hey @jbalsas, 
These properties "`javascript.fast.load=true`" and "`minifier.enabled=false`" are set respectively to true and false in portal-developer.properties. If these properties are set in portal-ext as true and false respectively, the issue with "include-and-override=portal-developer.properties" is reproduced. Therefore, the combination of "`javascript.fast.load=true`" and "`minifier.enabled=false`" causes web content to gray out when creating article.

**Comment by jbalsas** [comment]
Hey guys, I can't reproduce this in any way

**Comment by jbalsas** [comment]
ci:reopen

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
ci:close

**Comment by koor4356** [comment]
@jbalsas, here are the steps:
1. Copy "`javascript.fast.load=true`" and "`minifier.enabled=false`" from portal-developer.properties into portal-ext
2. Start tomcat on clean database ( I am using Tomcat 9.0.10 + MySQL 5.7)
3. Login after appserver start up
4. Navigate to Content > Web Content in the Site Administration
5. Try to create web content article

You will notice that web content fields are gray out and `javascript TypeError: n is undefined` is displayed in the developer console. You may not reproduce this if you repeat 4 & 5.

**Comment by jbalsas** [comment]
Hey @koor4356, I've done this several times. I've re-run ant all and wiped out my database several times. I still can't hit this error. Everything loads properly.

The fact that you mention "this may not reproduce if you repeat 4 & 5" makes me even more suspicious of this.

Can you provide some consistent way so we can investigate, or try to provide more information into the error? Otherwise, there's literally nothing more we can do about this.

**Comment by jbalsas** [comment]
Apparently, this only happens on Firefox and on first database initialization...

**Comment by jbalsas** [comment]
I kinda managed to track this down. https://github.com/brianchandotcom/liferay-portal/pull/65930#issuecomment-447302384

**Pull request closed without merging**
