### PR TITLE
LPS-56465 pacl IVY references

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8f2886569e...36746c5ff0

**Comment by brianchandotcom** [comment]
@rotty3000 aren't all packages private by default? How come we have to explicity make it private?

**Comment by rotty3000** [comment]
Code predates awareness of that fact.

**Pull request closed without merging**
