### PR TITLE
LPS-83038 Semantic versioning

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
cc @matethurzo

**Comment by matethurzo** [comment]
👍

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@pavel-savinov see 02c31c1 and 76b4d40 in master

and bc39ffdce4ef5b16bc64ee4d5c8ced6d5f846103 in my 7.1.x backport (additional commit to get this to work)

@matethurzo fyi.

**Pull request closed without merging**
