### PR TITLE
LPS-61584 return only 2 initials

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @ealonso

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest I just fixed the unrelated jspc error

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/39037ca13c...98afec27ea

**Pull request closed without merging**
