### PR TITLE
master-qa-18581

### PR DESCRIPTION
**Pull request by michaelhashimoto**
http://issues.liferay.com/browse/LRQA-18581

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@michaelhashimoto looks like something hung?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/218b15b6a9...f5a8918700

**Comment by brianchandotcom** [comment]
@michaelhashimoto @kenjiheigel please resend.. seems to have hung on ee-6.2.x and ee-6.1.x too

**Comment by michaelhashimoto** [comment]
@brianchandotcom - i'll look into it.

**Comment by michaelhashimoto** [comment]
I am re-running this job using this new jenkins branch:
michaelhashimoto:master-qa-18898

**Pull request closed without merging**
