### PR TITLE
LPS-169089 Allow use index with empty search

### PR DESCRIPTION
**Pull request by Tim-Cao**
This is only for master.

https://issues.liferay.com/browse/LPS-169089

@ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/10693

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/269e60402b...f06e2c365d

**Comment by brianchandotcom** [comment]
@ealonso see 280f7a811323d1dd569bd51d9b7de7fce71b89cd

**Pull request closed without merging**
