### PR TITLE
LPS-61791  Eliminate init.jsp from root dir

### PR DESCRIPTION
**Pull request by peterfellwock**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c01baf6b32...3370274535

**Comment by brianchandotcom** [comment]
@shuyangzhou this pull actually had a jspc error, which I fixed in a5a85ff58eb8859fea3c0877b829bd86a4288b1a

Since your refactor, jsps in portal-web are not precompiled. They used to be on "ant deploy" of portal-web. Can you readd that? Thx.

**Comment by shuyangzhou** [comment]
@brianchandotcom The jspc on CI is running in a batch called "compile-jsp", somehow this pull is not triggering that batch. I guess it is only changing front end code, we have some CI logic to only run certain batches on seeing this right?
I am not sure where that logic is, but we should fix it there to include "compile-jsp" batch for front end only pulls.

CC @michaelhashimoto

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/34481

**Pull request closed without merging**
