### PR TITLE
LPS-59105

### PR DESCRIPTION
**Pull request by shinnlok**

### CODE REVIEW

**Comment by shinnlok** [comment]
ci:retest

**Comment by shinnlok** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@shinnlok can we add test coverage? See UploadServletRequestImplTest .

Thx

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/de29e629a2...7acc4d7593

**Pull request closed without merging**
