### PR TITLE
LPS-69331 The Contacts, Social Private Messaging, and Chat servies are not included in the _CONVERTED_LEGACY_MODULES constant in UpgradeModules

### PR DESCRIPTION
**Pull request by pei-jung**
Hi @brianchandotcom,

This needs to be included in the fix pack for the private messaging and chat releases. Can you give priority to this? Thanks!

/cc @drewbrokke @miguel

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@pei-jung merged and backported

**Comment by pei-jung** [comment]
Thanks @brianchandotcom!

**Pull request closed without merging**
