### PR TITLE
LPS-61091 Use bndlib instead of bnd for API reference

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3db3b341e9...7b9e9cd594

**Comment by brianchandotcom** [comment]
ant-bnd was spared and is using:

compile group: "biz.aQute.bnd", name: "biz.aQute.bnd", version: "2.4.1"

I suppose that one makes sense since it needs more than just the api?

**Comment by rotty3000** [comment]
Correct!

**Pull request closed without merging**
