### PR TITLE
LPS-74314

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
fyi @ithildir @petershin

**Comment by hhuijser** [comment]
@brianchandotcom, right now this only works when using the gradle task `formatSource`

To make this work for running SF on entire portal, we can:
- make gradle task `formatSource` available in root dir
- run SF via gradle when running `ant format-source`
- try make it work via `ant` (not likely, I looked into this quite a bit)

What do you think?

**Comment by Ithildir** [comment]
@hhuijser, I'm going to take your pull, fix the semver problem and resend it 😊

**Comment by brianchandotcom** [comment]
Thx @Ithildir

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/51171. I'm still thinking of the best way to have the status updates enabled for the whole portal...

**Pull request closed without merging**
