### PR TITLE
Lps 151092

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1d396daae3...37677c9de8

**Comment by brianchandotcom** [comment]
Thank you @shuyangzhou !

@jcampoy fyi on 5d6499b0 and 37677c9d

**Comment by jcampoy** [comment]
I tested with a real upgrade and it worked fine! thank you @shuyangzhou

**Pull request closed without merging**
