### PR TITLE
LPS-61592 set errorSection attribute to null to expand correct panel or tab with validation error

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
@brianchandotcom Failed tests have nothing to deal with the PR.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1f225544bf...e858028f67

**Comment by brianchandotcom** [comment]
@pavel-savinov can you apply this to plugins as well? And once you do, let's change errorSection to ERROR_SECTION in WebKeys? And then document it in breaking changes. Thanks @pavel-savinov

**Pull request closed without merging**
