### PR TITLE
LRQA-38385 | master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-38385

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by jpince** [comment]
@stsquared99 did CI miss this pull? I don't see the "To conserve resources..." message, and ci:test did nothing

All the other pulls I checked looked fine.

**Comment by jpince** [comment]
@austinchiang thanks!

**Comment by stsquared99** [comment]
@jpince  Github deprecated a protocol, which we soon fixed on our side. Thanks

**Pull request closed without merging**
