### PR TITLE
Lps 50802

### PR DESCRIPTION
**Pull request by shuyangzhou**
@rotty3000 this is a follow up to ef4b718db93867dbb74764cca85b3572a0900faa , I assume you still need to keep StringUtil out of GetterUtil, right? Then we will have to just copy in the method we need here.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
CC @dantewang @slnn performance check please.

**Comment by rotty3000** [comment]
:+1:  It would be great to separate them. 

However the issue will only totally be solved when it's in its own package. But it's not critical for the release.

**Comment by shuyangzhou** [comment]
Yes, of course. There is no hurry to move them out at this moment, let's just duplicate the code for now.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3c1c2de4fa...5d5e31e6de

**Comment by brianchandotcom** [comment]
@shuyangzhou I documented it here eab2c256a5156159704fa2c6409c3b29669e0087

**Pull request closed without merging**
