### PR TITLE
LPS-87746 Update test

### PR DESCRIPTION
**Pull request by inacionery**
Hey @brianchandotcom,

Please do not do the backport.

Thanks!

/cc @mhan810

### CODE REVIEW

**Comment by lipusz** [comment]
@inacionery Please see https://issues.liferay.com/browse/LPS-87746?focusedCommentId=1638546&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1638546

**Comment by topolik** [comment]
Thanks @inacionery for fixing the tests!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2b1dbe338d...f2ed9f060d

**Comment by brianchandotcom** [comment]
@inacionery didn't backport. Thx.

**Pull request closed without merging**
