### PR TITLE
LRQA-57093 - fix source format issue in source-formatter-suppressions.xml

### PR DESCRIPTION
**Pull request by rodrigocunhaa**

### CODE REVIEW

**Comment by rodrigocunhaa** [comment]
ci:reopen

**Comment by rodrigocunhaa** [comment]
@jpince

**Comment by rodrigocunhaa** [comment]
@brianchandotcom I sent this directly to you because it's a quick fix caused by https://github.com/brianchandotcom/liferay-portal/pull/86806 and making SF failing in some PRs such the ones that I mentioned above.

**Comment by rodrigocunhaa** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/556b529e46...33b47e58d0

**Pull request closed without merging**
