### PR TITLE
LPS-75692 This is no longer necessary since the container is inline-block. Now we could prevent words to be broken without break the original case that force us to introduce this css rule (that messages with @nbsp weren't able to broke the line and shown in a single line overflowing the container)

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:reopen

**Comment by robertoDiaz** [comment]
This pull changes a css rule and errors doesn't seem to be related with it.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/416ce41d93...594091551d

**Pull request closed without merging**
