### PR TITLE
LPS-61559

### PR DESCRIPTION
**Pull request by natecavanaugh**

### CODE REVIEW

**Comment by kiyoshilee** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b4388add08...02a6d63450

**Pull request closed without merging**
