### PR TITLE
master-qa-16761

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LRQA-16761

Context: https://github.com/brianchandotcom/liferay-portal/pull/28161#issuecomment-120488494

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a6174a65d4...8ceb71e5ae

**Comment by brianchandotcom** [comment]
@kenjiheigel **/*.sh may leave out *.sh because it doesn't start with a /

So you may need to send another update

**Comment by kenjiheigel** [comment]
@brianchandotcom ,

Sorry that I didn't see this til now as I was on EVP last week. Using ant, the ```**/*``` notation will work correctly for the files within the given directory. The ```**``` will match zero or more directories, meaning that when app.server.weblogic.instance.dir is the base directory, any file or folder that matches the .sh extension within that directory will be included. 

I also confirmed this manually by checking the permissions after running the ant script. So no further changes are necessary. Let me know if you have any additional questions. 

Ref: 
https://ant.apache.org/manual/Types/fileset.html

**Pull request closed without merging**
