### PR TITLE
Lps 71619

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:reopen

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
Please ignore the result above. It makes it look like my retest has failed but it's actually still running. There should be a new result after this comment.

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@tinatian can you backport this to ee-7.0.x?

@hhuijser can we auto SF this?

**Comment by tinatian** [comment]
Backport to ee-7.0.x, see https://github.com/brianchandotcom/liferay-portal-ee/pull/16589

**Pull request closed without merging**
