### PR TITLE
LPS-84523 If there's no sharing permission checker we cannot share

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@Preston-Crary can you take a quick look at this ticket (already in upstream). It added a few permission files and it may not be in the location that you like most. If so, please move them and send me a subsequent pull. Thx!

**Comment by pyoo47** [comment]
ci:test:sf (testing something)

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/62197

**Comment by jpince** [comment]
@sergiogonzalez looks like this pull caused a startup error
`Something went wrong attempting to register service method {contextName=sharing,contextPath=SharingEntry,actionObject=com.liferay.sharing.service.impl.SharingEntryServiceImpl@77b7e784,actionClass=class com.liferay.sharing.service.impl.SharingEntryServiceImpl,actionMethod=public void com.liferay.sharing.service.impl.SharingEntryServiceImpl.afterPropertiesSet(),path=/sharingentry/after-properties-set,method=POST} due to java.lang.NoSuchMethodException: com.sun.proxy.$Proxy488.afterPropertiesSet()`

**Pull request closed without merging**
