### PR TITLE
Lps 107255

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c466e33506...bd77befa4d

**Comment by brianchandotcom** [comment]
@rolandpakai I'm not merging this.. it seems wrong.

1.) why not just update the implementation in TextFormatter?

2.) You're not accounting for 

10 KB

or

KB 10

in some languages (left to right vs. right to left).

Please resend. I think we can just update the existing logic.

@shuyangzhou fyi

**Comment by shuyangzhou** [comment]
@brianchandotcom we can not change it inside TextFormatter, it will require localization support (by LanguageUtil which is initialized by spring) inside TextFormatter. TextFormatter is used by tools, it should not require a spring injection to use.

**Comment by shuyangzhou** [comment]
@rolandpakai can you look into the ordering for the localization? If it is real, we will need to deal with it.

**Comment by rolandpakai** [comment]
Hi @shuyangzhou , @brianchandotcom 

i checked the Arabic and the Hebrew language and it seems the KB is on the correct side of the number. So, we dont need to deal with it in LanguageUtil.

I will resend the PR.

image

**Comment by rolandpakai** [comment]
Resent: https://github.com/shuyangzhou/liferay-portal/pull/8845

**Pull request closed without merging**
