### PR TITLE
LPS-92452 Generating the URLs with the portlet providers

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
`java.lang.ClassNotFoundException: com.liferay.portal.kernel.util.NaturalOrderStringComparator` when running `buildService`. Not related to our changes.

**Comment by brianchandotcom** [comment]
That was strange.. I ran

:apps:sharing:sharing-service:buildService

and didn't get any errors.. merging.

@pyoo47 what's up with this?

**Comment by brianchandotcom** [comment]
@4lejandrito see upstream for my changes.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f00ce15f42...0774c76378

**Pull request closed without merging**
