### PR TITLE
OAUTH2-241 Do not prefix scopes with application name

### PR DESCRIPTION
**Pull request by csierra**
/cc @topolik @stian-sigvartsen @petershin @xbrianlee

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:sf

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e0e89afb1a...f14f485391

**Comment by brianchandotcom** [comment]
Thanks @csierra I merged and backported.

**Pull request closed without merging**
