### PR TITLE
LPS-72843 Fix the test

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:reopen

**Comment by leoadb** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:reopen

**Comment by leoadb** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@leoadb this may make the test pass:

```
		HtmlUtil htmlUtil = new HtmlUtil();
		HtmlImpl htmlImpl = new HtmlImpl();

		htmlUtil.setHtml(htmlImpl);
```

But it's very very weird, especially since you use "_html" a few lines later.

Please fix properly. Thx.

**Pull request closed without merging**
