### PR TITLE
LPS-65546 Clean up inclusion of State and Credit Card utilities specific to Shopping

### PR DESCRIPTION
**Pull request by peterfellwock**
@brianchandotcom fixed wiring, this should pass now. com.liferay.shopping.util is found in shopping-service and the State and Credit Card utils belong in shopping-api. As two modules cannot export the same packages, I added a package com.liferay.shopping.api to accommodate such duplication. Ideally if any users want to use these deprecated APIs they can just reference shopping-api instead of shopping-service.

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:stop

**Comment by michaelhashimoto** [comment]
I broke this build and am restarting it.

Sorry for the inconveniences.

ci:restart

**Comment by brianchandotcom** [comment]
@michaelhashimoto it's ci:retest (not ci:restart)

**Comment by peterfellwock** [comment]
ci:IHopeThisPasses

**Comment by brianchandotcom** [comment]
@peterfellwock can you resend? Still has test failures, I'm  not sure if they are your fault or not.

In any case, don't use "shopping.api" as a real package. Put it in in shopping.credit.card or shopping.util.

Thx.

**Comment by kenjiheigel** [comment]
@peterfellwock, didn't get to look at all the failures, but I believe the majority of them are not related. Some changes went in that caused a few test failures that have since been reverted.

**Comment by peterfellwock** [comment]
@kenjiheigel nevermind these errors, I am working with @brianchandotcom to change this structure.

**Pull request closed without merging**
