### PR TITLE
LPS-61420

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Split up the pull that is giving the SB error to see what part if causing it.
See https://github.com/brianchandotcom/liferay-portal/pull/34225

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by hhuijser** [comment]
Go ahead and review this one... the problem is with the changes in ToolsUtil which I left out of this branch.

**Comment by hhuijser** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1ae5ff0389...718457b5e3

**Pull request closed without merging**
