### PR TITLE
LPS-72773

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
ci:retest

**Comment by jpince** [comment]
@mhan810 @lipusz errors unrelated, see https://loop.liferay.com/home/-/loop/feed/5491564

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4b4e9649b3...989983d227

**Pull request closed without merging**
