### PR TITLE
LPS-60218 S3Store specific test names must be exactly the same as parent class

### PR DESCRIPTION
**Pull request by mdelapenya**
Otherwise, base class tests will fail when executed on S3, as S3Store does not throws the NoSuchFileException. cc/ @preston-crary

### CODE REVIEW

**Comment by Preston-Crary** [comment]
@mdelapenya 
if we are going to exclude the S3Store from these tests we should make what we are doing more obvious by just overriding the methods and adding an @Ignore to the empty methods.  Otherwise we should just have the S3Store throw the exception as well.

**Comment by mdelapenya** [comment]
But we aren't ignoring the test, we are assuming that S3 is not configured. If it is configured (via OSGi props built on CI time) they will be executed.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fd1c11a21e...abcf5a6614

**Comment by brianchandotcom** [comment]
@mdelapenya see abcf5a6614b54f2e5fa07413050a1d3e692f8cb1 (and resend that part) thx.

**Pull request closed without merging**
