### PR TITLE
Lps 70069

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by jpince** [comment]
@shuyangzhou SourceMismatchException in RenderResponseImpl.java. The error is not really helpful, so I'm not sure how to fix it.
`     [java] /opt/dev/projects/github/liferay-portal/portal-impl/src/com/liferay/portlet/RenderResponseImpl.java
     [java] Exception in thread "main" com.liferay.source.formatter.SourceMismatchException`
Closing this pull.

**Comment by jpince** [comment]
ci:close

**Comment by jpince** [comment]
nevermind, bchan might have fixed this already

**Comment by jpince** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
