### PR TITLE
LPS-92236 Prevent extra renders

### PR DESCRIPTION
**Pull request by p2kmgcl**
@brianchandotcom I ordered SCSS variables here: https://github.com/brianchandotcom/liferay-portal/pull/69789/commits/76f1da3c723a32498382893ecb1d38ad80de3602, now they are grouped by type: generic, sizing, borders, transitions, z-index and colors. I hope I can do some cleanup soon.

Also, I have here 3 different LPS, but all of them were in review and conflicts appeared.

/cc @ealonso
/cc @sandrodw3 
/cc @carloslancha 
/cc @pavel-savinov 
/cc @jkappler

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:reopen

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:stop

**Comment by jpince** [comment]
ci:test:relevant @p2kmgcl fix pushed upstream a few minutes after your retest

**Comment by brianchandotcom** [comment]
@p2kmgcl rebase error, can you resend? Thx.

**Pull request closed without merging**
