### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
See https://github.com/hhuijser/liferay-portal/pull/4246
No unique failures... been trying for two weeks now :(

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1262b22340...35eef99944

**Comment by brianchandotcom** [comment]
@jpince can you dig into https://github.com/hhuijser/liferay-portal/pull/4246 to see why QA wasn't able to disable the flaky tests? Please coordinate with @hhuijser so we can discuss tomorrow. I'm curious why it took 2 weeks and @hhuijser had to go direct. Thx.

**Comment by brianchandotcom** [comment]
@hhuijser are you working on fixing 35eef999 ?

**Comment by brianchandotcom** [comment]
@hhuijser I'm kind of scared of merging this pull because of d07e85047db298eebf7a3460cae856039adc65b8

Can you send this in smaller chunks ? Please coordinate with QA to resend. Sorry!

**Comment by brianchandotcom** [comment]
@hhuijser it's better to add @Ignore than to remove @Test to a test method because then we know we need to remove @Ignore

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8f72036df9...be1363857d

**Comment by jpince** [comment]
@brianchandotcom 
Issues in upstream that caused `ci:forward` to fail in previous pulls:
[LPS-113128](https://issues.liferay.com/browse/LPS-113128) - flaky search int (occurred in ~40% of tests)
[LRQA-57722](https://issues.liferay.com/browse/LRQA-57722) - flaky search unit
[LPS-113409](https://issues.liferay.com/browse/LPS-113409) - app builder js-unit snapshots needed regen
[LPS-113451](https://issues.liferay.com/browse/LPS-113451) caused by [LPS-113218](https://issues.liferay.com/browse/LPS-113218)

Issues related to his changes:
Several days and retests needed to resolve unresolved requirement errors https://github.com/brianchandotcom/liferay-portal/pull/88657/commits/c7ab56495997d79d499a7ed6021744fe4894e984
2 days to identify and fix SB failure

**Pull request closed without merging**
