### PR TITLE
LPS-93509 Poshi Script SF: Enforce new lines between commands

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LPS-93509

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@kenjiheigel can you resend? @hhuijser see error.

**Comment by kenjiheigel** [comment]
@brianchandotcom, might have to wait for Alan on this one. I'll coordinate with him. 

@ling-alan-huang, I reproduced the failures locally. I tried debugging the assertions, but the values appear to be the same when I printed them out.

**Comment by ling-alan-huang** [comment]
@kenjiheigel, our team made some structural changes to SF yesterday, I will resend to you later.

**Comment by ling-alan-huang** [comment]
@kenjiheigel, I've just resent to you, https://github.com/kenjiheigel/liferay-portal/pull/494

**Pull request closed without merging**
