### PR TITLE
LPS-65441 Leave the logic as before because we only want to execute the upgrade if it doesn't exist any record with TIKARAWMETADATA and the classNameId RawMetadataProcessor

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @migue @marcellustavares

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
I had to stop and retest this pull because a recent CI pull that got merged into upstream broke the PR tester. The source of this problem has been reverted.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/72e2fa8be3...8b8fcaad0f

**Pull request closed without merging**
