### PR TITLE
LPS-109921

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@izaera, let me know if you want rules in place for when build is `liferay-npm-bundler`

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3195214078...afed5e7d7a

**Comment by brianchandotcom** [comment]
@hhuijser I published this, can send me a pull to remove  the suppression file?

**Comment by izaera** [comment]
@hhuijser Please see:

* https://github.com/brianchandotcom/liferay-portal/pull/86095#issuecomment-598075715
* https://github.com/brianchandotcom/liferay-portal/pull/86095#issuecomment-598078091

Thx :-)

**Pull request closed without merging**
