### PR TITLE
LPS-62907 Move control menu into product navigation

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juangon** [comment]
Hey @juliocamarero están moviendo todos los packages de portal-service, asi que creo que habrá que cambiar esos import.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/40726d5091...bbfead56fd

**Comment by brianchandotcom** [comment]
@juliocamarero I merged this in, but should we namespace the JS:

liferay-control-menu* ? to liferay-product-navigation-control-menu* ?

And for Java, we have both *ControlMenu* and *ProductNavigationControlMenu*

I'd prefer to be consistent with the latter. I know it's long, but it makes things obvious.

Then the implementing classes will have the package product.navigation.control.menu vs. just control.menu

I know it's long, but it makes it super clear.

Can you send a follow up pull? Thanks @juliocamarero

**Comment by brianchandotcom** [comment]
@juliocamarero fyi, I'll leave the ticket open for now until you send it. Thx  bro.

**Pull request closed without merging**
