### PR TITLE
Lps 71441

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianwulbern** [comment]
The Poshi tests all fail from SPA-related loading issues, that will be resolved under [LPS-71120](https://issues.liferay.com/browse/LPS-71120)

**Comment by brianchandotcom** [comment]
@Preston-Crary @shuyangzhou please backport. Thx.

**Comment by shuyangzhou** [comment]
@preston-crary since this one is quite complex, it will better if you do the backport by yourself to be safe, thanks!

**Comment by Preston-Crary** [comment]
Please see https://github.com/dustinryerson/liferay-portal-ee/pull/2717

**Pull request closed without merging**
