### PR TITLE
LPS-68025 Update module version

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
cc @sergiogonzalez

**Comment by sergiogonzalez** [comment]
Hey @brianchandotcom this is the resend of the story that was rollbacked.

**Comment by brianchandotcom** [comment]
Got it. What made it "work" this time compared to last time? Merged.

**Comment by ambrinchaudhary** [comment]
@brianchandotcom the version was not updated in the _package.json_ file, that is why it failed last time

**Pull request closed without merging**
