### PR TITLE
[TECHNICAL-SUPPORT] LPS-76519

### PR DESCRIPTION
**Pull request by sergiogonzalez**
/cc @ChrisKian

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a551e7f0b0...b8436566b1

**Comment by brianchandotcom** [comment]
@ChrisKian is this OK? b8436566b1de88027958dc86d811ce25da81bcbe

**Comment by ChrisKian** [comment]
@brianchandotcom, that should be fine, thanks!

**Pull request closed without merging**
