### PR TITLE
LPS-97345 SCIM implemention - Part 2 (user provisioning + Charon lib integration) - Make Headless = Java API

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Hi Brian. Following up on https://github.com/brianchandotcom/liferay-portal/pull/143008#issuecomment-1788111218 . I have preserved the previous commits, adding new ones only so you can see the change.

- `scim-client` merged into `scim-rest-impl`
- `scim-impl` merged into `scim-charon-integration`
- `scim-api` greatly reduced because the headless API is now the Java API. I aim to try to remove this module altogether once we look at integrating the next batch of commits from the team
- But @rafaprax and I feel strongly that we need to keep the `scim-charon-integration` separate from the `scim-rest-impl` for maintainability, so I've introduced a `UserResourceHandler` SPI in `scim-rest-api`. We hoped to re-use the REST Builder generated `UserResource` interface, but it has a lot of unrelated methods to do with Headless implementation detail (`scope = ServiceScope.PROTOTYPE`)
- Lots of interfaces **removed** from `scim-api` as requested
  - `UserResource`
  - `ScimUserManager`
  - `ScimUser` moved to internal package in scim-charon-integration (final API uses Headless DTOs)

cc @oliverkecskemety @alvarosaugarlr

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:reopen

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by oliverkecskemety** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@rafaprax @stian-sigvartsen @oliverkecskemety for this first pass, move 

scim-charon-integration into scim-rest-impl. We can move it out in the future if necessary. I dont' want to over engineer. I believe we are because com.liferay.scim.rest.internal.resource.v1_0 is a 1 to 1 map to UserResourceHandler

Unless we have "many" integrations, this separate layer is not needed.

Please simplify and resend.

**Pull request closed without merging**
