### PR TITLE
LPS-71473 Don’t fail on empty config.json files

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
Hey @brianchandotcom, feels good to be back again :-)

Forgive me if I have forgotten some of the formatting rules: I will try to remember everything quickly ;-)

**Comment by jpince** [comment]
@izaera please make sure your github account is added to the Liferay organization so your pulls will be tested by CI. Thanks!

**Comment by izaera** [comment]
They added me yesterday. Is It failing?

**Comment by izaera** [comment]
@jpince

>

**Comment by jpince** [comment]
it's not running at all. You may have to join manually? https://github.com/liferay
Liferay should appear in your profile under organizations
image

**Comment by izaera** [comment]
Oh, it may be that it is not the organization, but the company field of the profile... Let me check it.

I currently belong to Liferay organization, according to my settings: 

image

**Comment by izaera** [comment]
Try again @jpince . I have set @liferay in my profile's Company field.

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
not sure if this will work, you may have to resend the pull in order to test

**Comment by jpince** [comment]
or just wait until the next one, this doesn't seem like a major change?

**Comment by izaera** [comment]
Well, it was a 5. I'll resend it, better.

**Pull request closed without merging**
