### PR TITLE
LPS-95775

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-95775.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
Will resend.

**Comment by jonmak08** [comment]
ci:retest

**Comment by jonmak08** [comment]
Closing will resend.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
