### PR TITLE
LPS-164375 Follow portal patterns

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-164375

@balazssk 
@ealonso

### CODE REVIEW

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/9784

:x: ci:test:stable - 27 out of 28 jobs passed
:x: ci:test:relevant - 169 out of 179 jobs passed in 4 hours 4 minutes

**Comment by ozysouza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e933593539...62a3bd06af

**Comment by brianchandotcom** [comment]
@ozysouza @balazssk just 62a3bd06af825ad0388605260bb88f932c85dfbb

**Pull request closed without merging**
