### PR TITLE
LPS-56341 Register categories and panels for the Product Menu (still not visible changes)

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@ealonso 

The folder and bnd names don't match our existing standard.

See modules/apps/site and modules/apps/site-navigation

See how modules inside site-navigation start with site-navigation-*

Same with dynamic-data-mapping/*

Thx

**Pull request closed without merging**
