### PR TITLE
Lps 102243

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3120d8e8d7...72476fc1e2

**Comment by brianchandotcom** [comment]
@shuyangzhou @ChiZelin @dantewang I'm not sure if I can merge this. If I publish a new Gradle plugins sdk, this will affect all branches. Will that break other branches?

Also, since this is a big change, I need to see it green before merging (even if it's just at your origin).

Please resend.

**Comment by tinatian** [comment]
Hi @petershin,
Could you please add the protection to make gradle plugins work? Basically we need:
1) When portal-test-integration is there, same logic as before
2) When portal-test-integration is not there, do nothing.

Thanks.
Tina.

**Comment by petershin** [comment]
@tinatian - Taking a look

**Pull request closed without merging**
