### PR TITLE
LPS-103874 accept all languages

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8bba39214f...15b1c03385

**Comment by brianchandotcom** [comment]
@nhpatt I think this should go back to 7.2.x and 7.1.x. Can you send me a backport?

**Comment by nhpatt** [comment]
Will do! :)

**Pull request closed without merging**
