### PR TITLE
LPS-61420

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@brianchandotcom

I checked sorting *-spring.xml files, but I am not sure if we follow some sort of logical order for those.
For example modules\portal\portal-spring-extender\src\main\resources\META-INF\spring\parent\base-spring.xml is completely unalphabetically sorted?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/076e3ca244...46ce2453ac

**Comment by brianchandotcom** [comment]
Yeah, that file is tough, may be do a source-formatter off on that file (by text in the file vs in the exclusion file), sort of like @generated but closer to the formatter:off syntax for that file

**Comment by hhuijser** [comment]
I'll see if I can find some kind of pattern to see what files should be ignored when ordering...

**Pull request closed without merging**
