### PR TITLE
LPS-76256

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@juliocamarero @ealonso see https://github.com/brianchandotcom/liferay-portal/pull/53419/commits/2e1cb9a7d75f408da0df1ee0fb90be28345116e3 and my comment here https://github.com/brianchandotcom/liferay-portal/pull/53404#issuecomment-348839959

/cc @petershin

**Comment by hhuijser** [comment]
ci:reopen

**Comment by ealonso** [comment]
Hey @hhuijser,

Once this pull https://github.com/brianchandotcom/liferay-portal/pull/53423 is merged I think the exclusion 2e1cb9a is not needed.

**Comment by hhuijser** [comment]
@ealonso, yup, that's correct. I'll monitor and make sure to revert that one it if it does get merged in.

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
