### PR TITLE
LPS-99526 - Use correct heading tags instead of <span />; Source format code using prettier

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c1a7c301d7...09b0a7e8ac

**Comment by john-co** [comment]
ci:test:sf:norebase

**Comment by john-co** [comment]
For some reason these SF errors haven't showed up on upstream PRs but it shows up in our daily upstream runs.

**Comment by john-co** [comment]
ci:test:sf

**Pull request closed without merging**
