### PR TITLE
LPS-171292

### PR DESCRIPTION
**Pull request by tinatian**
FYI @shuyangzhou

### CODE REVIEW

**Comment by tinatian** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/49090f8e97...8b6f95592a

**Comment by brianchandotcom** [comment]
@julschong @tinatian please use TransformUtil and ListUtil see d18051b22a1ba97f4a2fa33bdc0f69f081ce10ac

Thx

**Comment by julschong** [comment]
@brianchandotcom Hi Brian, 
Thanks for tips! This will be really helpful for our Stream Optional tasks

**Pull request closed without merging**
