### PR TITLE
LPS-56893 Add resource bundle to portlet

### PR DESCRIPTION
**Pull request by adolfopa**
@brianchandotcom I'm sending this before the package rename to avoid rebase conflicts. (@sergiogonzalez has already reviewed it).

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test

**Comment by adolfopa** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@adolfopa shouldn't it be com.liferay.page.flags.web vs. com.liferay.flags.page.flags.web

Instead of a new "flags" dir, shoudln't it be a new "page" dir? To extract out: Page Flags, Page Ratings, and Page Comments?

Please resend on top of https://github.com/adolfopa/liferay-portal/pull/101

I didn't make the change yet to "page" vs "flags"

**Comment by brianchandotcom** [comment]
Nvm, I just saw https://github.com/brianchandotcom/liferay-portal/pull/28256 so I see that you're going to move Page Comments/Page Ratings/Page Flags to different places.

Will merge this in.

**Comment by brianchandotcom** [comment]
@adolfopa see upstream for my changes. Thx!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/834188aca5...ddc704a2e3

**Pull request closed without merging**
