### PR TITLE
LPS-75377 Backend changes

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test

**Comment by JorgeFerrer** [comment]
ci:retest

**Comment by JorgeFerrer** [comment]
ci:reopen

**Comment by JorgeFerrer** [comment]
@pei-jung.lan could you check if the failures are real and help merge this into master?

**Comment by JorgeFerrer** [comment]
Cc @pei-jung

**Comment by pei-jung** [comment]
The SF failure is not related and is fixed by https://github.com/liferay/liferay-portal/commit/3a809e743a72957b636b8be785b30af4ed71c245.

**Comment by pei-jung** [comment]
ci:retest

**Comment by JorgeFerrer** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pei-jung @JorgeFerrer merged..

@pei-jung can you rename *.categories.* to ".category."

We call it *.constants.* because each Class in that package is actually a plural of constants.

In this case, each category class is just one category, hence the singular form.

Thx.

**Comment by pei-jung** [comment]
Renamed package and sent to https://github.com/brianchandotcom/liferay-portal/pull/55225.

**Pull request closed without merging**
