### PR TITLE
LPS-57605 fix of some product menu urls

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
@ZoltanTakacs can we add this one to 7.0.x ?

it is a bug in the product menu, thanks!

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7f42177ad9...534379f2ab

**Pull request closed without merging**
