### PR TITLE
LPS-181216 SF check to migrate variable references from Velocity to FreeMarker

### PR DESCRIPTION
**Pull request by kevhlee**
Pull request tested here: <https://github.com/kevhlee/liferay-portal/pull/52>. Unrelated SF failures.

> Ticket: https://issues.liferay.com/browse/LPS-180537
> 
> Hi Kevin!
> 
> This is a check for the migration from Velocity to FreeMarker. This pattern is for variable reference inside of the template, this check is covering all cases found so far in the client, please look at the `UpgradeVelocityMigrationCheck-testvm/testftl` files for a better example.

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:reopen

**Comment by kevhlee** [comment]
ci:close

**Comment by kevhlee** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d3e530d61c...edb7dbbcce

**Comment by brianchandotcom** [comment]
@kevhlee @nicolas-sss the name
```
public class UpgradeVelocityVariableReferenceMigrationCheck
	extends BaseUpgradeVelocityMigrationCheck {
```
is wrong

It should be AbcXyz extends bBaseXyz

Please resend. THx.

**Comment by nicolas-sss** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c7ab58f906...bdf6406438

**Pull request closed without merging**
