### PR TITLE
Lps 69090 passing

### PR DESCRIPTION
**Pull request by shuyangzhou**
@brianchandotcom https://github.com/brianchandotcom/liferay-portal/pull/44514 meant to fail, and CI will close it, merge this one instead.

@mhan810 all the details are in https://github.com/brianchandotcom/liferay-portal/pull/44514 in case you want to know.
Otherwise, you just need to see the fix commit at https://github.com/brianchandotcom/liferay-portal/commit/0253d970b71b972ce735ce911232d431365154c4

Basically preload the class before shutdown starts, as elasticsearch shutdown calls netty which does interruption, and equinox ModuleClassLoader is poorly designed on interruption handling, it simply aborts the ongoing loading by throwing a LinkageError. Base on the code inside elasticsearch/netty, org.jboss.netty.util.internal.ByteBufferUtil is the only class could ever possibly be a new load after shutdown, so preloading just that one should be enough, unless they change their code in the future release. Then we may have to find other ways.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@Ithildir can you help me to take a look at this?

Seems that the "ci profile" change you showed me requires at least one module has the marker somehow, otherwise it is failing with this. As a comparison, you can see https://github.com/brianchandotcom/liferay-portal/pull/44514, that pull works (I mean it builds, it is failing the tests on purpose). And the only real difference from this to that is, this one removes the only ".lfrbuild-ci".

**Comment by shuyangzhou** [comment]
ci:retest

@Ithildir I added https://github.com/brianchandotcom/liferay-portal/pull/44515/commits/7646fd60dcb6dbfd21f780d4ce699e23daed6104 to prove my guess, if it builds now, then we have an issue inside gradle-execute marker file support. If so, please fix it in the right way and revert my workaround commit, thanks!

**Comment by Ithildir** [comment]
Hi @shuyangzhou,
Unfortunately I don't think there's a Gradle-only solution to this: if no projects have that marker file, no projects will be included in the build, and Gradle will fail because it can't find `deploy` anywhere. The commit you added is totally fine IMHO, I hope it doesn't make things slower.

But is there a reason why modules with the CI marker can appear and disappear? Once you added at least one, isn't it there to stay?

**Comment by shuyangzhou** [comment]
All ci modules are for debug purpose, once the bug is fixed, the module will be disabled or removed. I kept this one as a template so later people can copy the structure of it.

If you say it is a grade limitation, I am totally fine with the ant hack I have now. Thanks @Ithildir !

**Comment by brianchandotcom** [comment]
Thx @shuyangzhou ! Merged.

**Pull request closed without merging**
