### PR TITLE
LPS-70031 Entries on the Organization_ table do not always have full tree paths

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-70031](https://issues.liferay.com/browse/LPS-70031).

Hey @brianchandotcom, do we need to put any special guards into place for the test at 0a469b7? If it throws the exception then we're good (it's expecting an exception).  However, if the test "fails" then the application will just hang (see the "Actual Result" of [LPS-69881](https://issues.liferay.com/browse/LPS-69881)).  I just don't want to cause CI to hang when it doesn't have to :).

/cc @pei-jung @jorgeferrer @shinnlok @SpencerWoo @jonathanmccann

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by drewbrokke** [comment]
ci:retest

**Comment by drewbrokke** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
