### PR TITLE
LPS-74375 SF

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by lesliewong92** [comment]
Running pull on test-5 to see if the big console log issue that occurred on https://github.com/brianchandotcom/liferay-portal/pull/55651 happens again. And if it does happen, check if it causes issues for Jenkins again.

**Comment by lesliewong92** [comment]
The changes within this pull seem to be causing a repeating error on portal startup. Please see https://gist.github.com/pyoo47/720c4f1ce197ef37221fed01f20e6d48 for the error. Alternatively, you can view the full console log [here](https://test-5-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/9794/consoleText).

**Comment by lesliewong92** [comment]
ci:close

**Comment by michaelhashimoto** [comment]
Please don't retest this pull, if you need to test it again please contact someone on [QAE](https://loop.liferay.com/web/guest/home/-/loop/teams/_QA+Engineering).  We can rerun it on our staging environment for you.   Thanks!

**Comment by xbrianlee** [comment]
@jbalsas We're going to aim to investigate the cause of the large logs within the next two days

**Pull request closed without merging**
