### PR TITLE
LPS-67914 Enable build

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @brianchandotcom,

This uses @ithildir new task to autogenerate the `npm-srhinkwrap.json` file in a way that doesn't affect the build on windows (and it is sorted and formatted!! 🎉 ), so it's safe to enable it in the build again.

Could you please backport this to ee-7.0.x in preparation for the marketplace release?

Thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
@brianchandotcom, @ithildir, looking into the failure.

**Comment by kenjiheigel** [comment]
Sam has added the new node-sass version on mirrors.

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
