### PR TITLE
LPS-78950 The isMale field in Users does not offer all the options that are often needed

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-78950](https://issues.liferay.com/browse/LPS-78950).

Hey Brian, this pull does the following things:

1. Defaults the value of `field.enable.com.liferay.portal.kernel.model.Contact.male` to `false`
2. Adds a new default user image named "user_portait.png" (in addition to "user_male_portrait.png" and "user_female_portrait.png")
3. Adds a new portal property to reference the new image
2. Adds a method to `ImageTool` called `getDefaultUserPortrait` that will return the new default user portrait
5. Adds branching logic inside `UserConstants.getPortraitURL` that will path towards "user_portrait.png" when the value of `field.enable.com.liferay.portal.kernel.model.Contact.male` is `false`

Full test results here: https://github.com/drewbrokke/liferay-portal/pull/712#issuecomment-452952291

Please let me know if you have any questions. Thanks!

@pei-jung @stsquared99 @alee8888 @ChrisKian @JorgeFerrer

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
It appears that GitHub was producing some invalid responses to their API calls when this pull request was originally submitted. They appear to have fixed the issue now.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4b27a057b4...bbc783a3f0

**Comment by brianchandotcom** [comment]
@drewbrokke can you work with @sez11a for the documentation? Thx.

**Pull request closed without merging**
