### PR TITLE
LPS-104523 regen

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@inacionery can you get someone to fix the poshi test? Thx.

**Comment by brianchandotcom** [comment]
@inacionery @JavierMoral I'm hesitant to merge this in because we're just retrying something that may be bad. I'm asking @preston-crary to look at this.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/8541

**Comment by inacionery** [comment]
Hey @barrosdennys could please take a look on these poshi failure? 

[LocalFile.WorkflowWebContent#EditWebContentInReviewProcess](https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/338706//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_WorkflowWebContent_EditWebContentInReviewProcess_)

Thanks

**Comment by inacionery** [comment]
Thanks @Preston-Crary!

**Comment by barrosdennys** [comment]
@inacionery @brianchandotcom 
It is a bug: https://issues.liferay.com/browse/LPS-104725

In the meantime, I'll disable _WorkflowWebContent#EditWebContentInReviewProcess_ from relevant tests until this bug is fixed.

Thanks

**Comment by inacionery** [comment]
Thanks @barrosdennys

**Comment by barrosdennys** [comment]
Refer to: https://github.com/brianchandotcom/liferay-portal/pull/81130

**Pull request closed without merging**
