### PR TITLE
LPS-69815

### PR DESCRIPTION
**Pull request by mikemanyoung**

### CODE REVIEW

**Comment by dejuknow** [comment]
ee-6.2.x bp: https://github.com/brianchandotcom/liferay-plugins-ee/pull/20743

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@dejuknow @mikemanyoung see fb3d96cdb9d3b0fc07b014d90a4d57bf02a7dcf1

**Comment by brianchandotcom** [comment]
@dejuknow @mikemanyoung I meant d620a50681de982df6f5d2ccc3e7c9d640573749

**Pull request closed without merging**
