### PR TITLE
LPS-96186 Remove includeresource instruction

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:reopen

**Comment by leoadb** [comment]
@petershin Can you please help me with this?

**Comment by leoadb** [comment]
cc @jeyvison

**Comment by petershin** [comment]
Hi @leoadb, I sent a new pull to fix the build problem: https://github.com/brianchandotcom/liferay-portal/pull/75138

Will cc you on that pull

**Comment by petershin** [comment]
ci:close

**Pull request closed without merging**
