### PR TITLE
LPS-162822

### PR DESCRIPTION
**Pull request by murilostodolni**
Hi Brian,

As discussed, follow adjusted PR. Thanks

Related: https://issues.liferay.com/browse/LPS-162822

### CODE REVIEW

**Comment by murilostodolni** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4d6ab9bdbd...a85d649aa6

**Comment by brianchandotcom** [comment]
@murilostodolni just a85d649aa6ab88812055555da2efc9038ed6a64a

Can you send an integration test? Thx.

**Comment by murilostodolni** [comment]
Hi @brianchandotcom, ok! I will work in integration test

**Pull request closed without merging**
