### PR TITLE
LPS-68092 - Regen npm-shrinkwrap.json files of foundation themes

### PR DESCRIPTION
**Pull request by robframpton**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @Robert-Frampton, we're missing here the themes living directly in `modules/apps`

- [Fjord](https://github.com/liferay/liferay-portal/tree/master/modules/apps/frontend-theme-fjord)
- [Westeros Bank](https://github.com/liferay/liferay-portal/tree/master/modules/apps/frontend-theme-westeros-bank)

Can you apply the changes to those as well?

Thanks a lot!! ☺️ 

@brianchandotcom, although not necessary, would be good to backport this as well

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
@Robert-Frampton, not sure what went wrong initially, but we'll see what happens with the retest

**Comment by michaelhashimoto** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@Robert-Frampton please resend based on comments from @jbalsas

**Pull request closed without merging**
