### PR TITLE
LPS-55518 Specify clearly in which context the code is injected

### PR DESCRIPTION
**Pull request by jbalsas**
Hey Brian,

We think it's very important to make the context where the code will be injected as explicit as possible. This will help avoid people injecting html where js is exepected, for example.

I've renamed the keys so `com.liferay.frontend.editors.web#editorName#onEditorCreate` becomes `com.liferay.frontend.editors.web#editorName#js#onEditorCreate`.

Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a8700d3034...899d1e08d4

**Comment by brianchandotcom** [comment]
@jbalsas will there be more than just JS? Like FTL or something?

**Comment by jbalsas** [comment]
Yes, possibly some HTML points and maybe even CSS. We also have the `DynamicIncludeTag` mechanism, but we'd need to apply some enhancements there.

We're still trying to figure out how to make the editors as modular and extensible as possible.

**Pull request closed without merging**
