### PR TITLE
LPS-69389 SF

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:reopen

**Comment by brunobasto** [comment]
Failure seems unrelated to the changes in this PR

**Comment by brianchandotcom** [comment]
@brunobasto not merging, please fix semantic error, probably came from another pull? @jbalsas fyi

**Comment by brunobasto** [comment]
Resent: https://github.com/brianchandotcom/liferay-portal/pull/45094

**Pull request closed without merging**
