### PR TITLE
LPS-98965 Fix test.

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/037b7f47c3...8af2c4bd02

**Comment by brianchandotcom** [comment]
@cgoncas backported for you.

**Comment by brianchandotcom** [comment]
@cgoncas also, see 418a8c561c8d389999459961145d376bc1dcd3d5

**Pull request closed without merging**
