### PR TITLE
Revert "LPS-84119 Move variable declaration inside if/else statement …

### PR DESCRIPTION
**Pull request by Preston-Crary**
…for better performance"

This reverts commit a8034306dbe3093e9572c93b8516cf3d8b00225c.

CC @shuyangzhou

@hhuijser I think the problem is with a side effect in ResourceActionsImpl._readModelResource() method.

@brianchandotcom this fixed the NoSuchResourceActionException during startup.

### CODE REVIEW

**Comment by jpince** [comment]
@Preston-Crary thank you!

**Comment by jpince** [comment]
ci:test

**Comment by jpince** [comment]
test failures are unrelated

**Comment by brianchandotcom** [comment]
@hhuijser fyi

Thanks @Preston-Crary 

fyi @shuyangzhou

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e6ce262319...9e24d5f998

**Pull request closed without merging**
