### PR TITLE
LPS-71329 Improve PortalImpl.getStaticResourceURL() performance

### PR DESCRIPTION
**Pull request by Preston-Crary**
cc @shuyangzhou

Only commit that's changed is 36717f0, previously it was 73be21d.  It's more complex but keeps the previous order.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@Preston-Crary I like your changes. I prefer keeping the order the same just in case someone depended on that ordering. Imagine if someone (unsafely) did a string indexOf, I don't want that code to break.

See 25541d358d8d712806af40dab697ca7a4ca82d59 for my minor changes.

**Pull request closed without merging**
