### PR TITLE
LPS-67352

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@brianchandotcom
 
Resending without changing anything.

Regarding you comment here: https://github.com/brianchandotcom/liferay-portal/pull/45872

Those 3 lines in FileUtil all moved one tab to the right because of the incorrect indentation on line 163. That last line (165) now goes over 80 chars and had to be broken up.

**Comment by hhuijser** [comment]
Already passed tests

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ccc101d4a1...3ddc23ca24

**Comment by brianchandotcom** [comment]
@hhuijser please backport? thx.

**Pull request closed without merging**
