### PR TITLE
LRCI-844 Fix for commerce

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d043e7235d...124015ad0d

**Comment by petershin** [comment]
@yichenroy - Please send the relevant backport pulls to Brian

**Comment by brianchandotcom** [comment]
@yichenroy  I need help with the changes to 7.0.x

I backported the rest to 7.1.x and 7.2.x already (but not the changes to build-test.xml)

**Comment by yichenroy** [comment]
As a reference, backport to 7.0.x has been sent here: https://github.com/brianchandotcom/liferay-portal-ee/pull/27997

**Pull request closed without merging**
