### PR TITLE
master-qa-39795

### PR DESCRIPTION
**Pull request by kiyoshilee**
https://issues.liferay.com/browse/LRQA-39795

### CODE REVIEW

**Comment by kiyoshilee** [comment]
ci:test

**Comment by kiyoshilee** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@kiyoshilee master only?

**Comment by kiyoshilee** [comment]
@brianchandotcom 7.1 as well. I can backport and send it to you if you want.

**Pull request closed without merging**
