### PR TITLE
LPS-77404 expand timer action and nofication elements so that they accept task execution type to match frontend

### PR DESCRIPTION
**Pull request by rafaprax**
\cc @jeyvison

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test

**Comment by kenjiheigel** [comment]
ci:stop

This will fail later due to an issue in Jenkins. Restarting the tests, as the issue has been reverted.

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Please resend @arthurchan35 

Are you sure we should change all of the old DTDs too? Please resend if changing all of the old DTDs was intentional.

**Pull request closed without merging**
