### PR TITLE
LPD-6611 listen to ThemeCSSCET service, register its FrontendTokenDefinition in memory

### PR DESCRIPTION
**Pull request by thiago-buarqque**
Follow up of LPD-6611 big PR.

Last PR #147906

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@thiago-buarqque 

modules/apps/frontend-token/frontend-token-definition-test/src/testIntegration/resources/WEB-INF/frontend-token-definition.json

vs.

modules/apps/frontend-token/frontend-token-definition-test/src/testIntegration/resources/com/liferay/frontend/token/definition/test/dependencies/frontend-token-definition.json

Why do we have the same file checked in twice?

**Comment by thiago-buarqque** [comment]
@brianchandotcom 

The file on `modules/apps/frontend-token/frontend-token-definition-test/src/testIntegration/resources/WEB-INF/frontend-token-definition.json` is going to be loaded once the test bundle is deployed ([see](https://github.com/thiago-buarqque/liferay-portal/blob/4d645091b6a6e551a5d61252d9a39c2082f4cf37/modules/apps/frontend-token/frontend-token-definition-impl/src/main/java/com/liferay/frontend/token/definition/internal/FrontendTokenDefinitionRegistryImpl.java#L254)).

`modules/apps/frontend-token/frontend-token-definition-test/src/testIntegration/resources/com/liferay/frontend/token/definition/test/dependencies/frontend-token-definition.json` is for the Client Extension ([see](https://github.com/brianchandotcom/liferay-portal/pull/147996/commits/f230e828e9cc2cfcc044df513c57499e3ee3f5f2#diff-3d1baa8db710ca803671c0bbcf7e0377f525c4c8d9726e908f28261fb11f7362R94))

It's kind of weird but it's the accurate way of testing a frontend token definition added when a bundle is deployed and throught a client extension

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a052c09ec2...58e5ea67fb

**Pull request closed without merging**
