### PR TITLE
Lps 125550

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@shuyangzhou has a conflict with 7470982e7d90cbd3d70dade0a51a5efa7e56205b and I'm not sure what to do with the plugins SDK. I think we should get rid of it for master.

**Comment by brianchandotcom** [comment]
@shuyangzhou @yuhai @tinatian I did cherry pick b86c534f18f301f9142a66accd9abe6eef71e2f9 and I did publish those jars. So no need for the fake gradle cache for the next pull.

**Comment by dantewang** [comment]
@brianchandotcom See https://github.com/brianchandotcom/liferay-portal/pull/100213

**Pull request closed without merging**
