### PR TITLE
ISSITES-5725 Add styles for Liferay Learn site

### PR DESCRIPTION
**Pull request by allen-ziegenfus**
@brianchandotcom  I wasn't sure how to run the source formatter on this client extension since the gradle task does not exist.

### CODE REVIEW

**Comment by allen-ziegenfus** [comment]
@brianchandotcom  Do I need to update anything in this pull so you can review / merge it?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7981e83f80...ab1c1c125c

**Comment by brianchandotcom** [comment]
@allen-ziegenfus sorry took so long, reviews and merged. Is our SF running for this?

**Comment by allen-ziegenfus** [comment]
@brianchandotcom I added that here: https://github.com/brianchandotcom/liferay-portal/pull/126499

**Pull request closed without merging**
