### PR TITLE
LRQA-43884 | master

### PR DESCRIPTION
**Pull request by vicnate5**
https://issues.liferay.com/browse/LRQA-43884

Backport +1 https://github.com/brianchandotcom/liferay-portal-ee/pull/23591

### CODE REVIEW

**Comment by vicnate5** [comment]
@christianstokes

**Comment by vicnate5** [comment]
compile failure not related

**Comment by vicnate5** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
