### PR TITLE
LPS-58188 Show the User name and photo as the personal tab of the product menu

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
@marcoscv-work I am going to need your help tomorrow with 3 things related to this:
- Use the proper markup to center the user avatar
- Make the product menu look good when the user can only see 1 tab
- Use the elipsis when the user name is too long to fit in the tab

@ealonso we need to apply your taglib here tomorrow

**Comment by juliocamarero** [comment]
@evannagayama this may break some functional tests since we are replacing the tab called "my space" by the name of the user. See this picture:

thanks!

users_and_organizations_-_control_panel_-_liferay

**Comment by juliocamarero** [comment]
cc @natecavanugh

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/74bb2176f2...b0a200a88a

**Comment by marcoscv-work** [comment]
Hey Julio,

About center markup, no problem.
About 1tab: Do we need actually show the tab when the user can only see 1 tab? we can show only the content of that tab.
About elipsis, It will be done in next Lexicon versión.

**Pull request closed without merging**
