### PR TITLE
LPS-90102 Include a line break when combining already minified files

### PR DESCRIPTION
**Pull request by epgarcia**
@NemethNorbert

### CODE REVIEW

**Comment by gergelyszaz** [comment]
@NemethNorbert @epgarcia 
Is 7.1.x affected as well?
https://issues.liferay.com/browse/LPS-89615 is already merged there.

**Comment by NemethNorbert** [comment]
Thanks @epgarcia for taking care of this issue. I saw the problem is we do more then reminifying the files in that if statement. I also noticed, we 'used to' update the relative urls for .min.css files. Here: https://github.com/brianchandotcom/liferay-portal/blob/f6e5512d06d91a4618a3a83121c465903e6544bd/portal-impl/src/com/liferay/portal/servlet/ComboServlet.java#L344-L371
I'm not sure we need that part as well, but I figured it's better if I point it out.

Thanks,

**Comment by epgarcia** [comment]
@gergelyszaz In our case, we only need this to be fixed on master. 
@NemethNorbert Yes, we found this side-effect of your change, but there might be others. In any case we really do need that break line when combining the JS files.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by NemethNorbert** [comment]
https://github.com/liferay/liferay-portal-ee/pull/12444

**Pull request closed without merging**
