### PR TITLE
LPS-87237 Upgrade group.typesettings field for missing portlets

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
Hi @brianchandotcom,

We duplicated the class to UpgradePortletId here: https://github.com/brianchandotcom/liferay-portal/pull/65549#issuecomment-443920028

To avoid a major change in semantic versioning since we need to change the class from which it extends (see https://github.com/brianchandotcom/liferay-portal/pull/65569/commits/4d4886ecfc0b9f0bf972c707f8a3cf633fca6edc#diff-5a4d993a6a42f07139e1f8736c362c52R23). Anyway, we can proceed with this change in master and backport it duplicating the class (or the parent class code) in 7.1.x and 7.0.x.

Let me know what you think.

Thanks.

cc/ @balazssk

**Comment by jpince** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@kmaria I can't tell if the failure in `StagingUsecaseWithVersioning#StagingBlogsCP` is real/caused by this pull, please follow up if it causes a real issue.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/79d08dd3eb...32f71869c0

**Comment by brianchandotcom** [comment]
@achaparro for the 7.1.x backport, go ahead and call it UpgradePortletIds so we don't trigger a major version bump

**Pull request closed without merging**
