### PR TITLE
LPS-164393, LPS-165177, LPS-164647

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-164393
https://issues.liferay.com/browse/LPS-165177
https://issues.liferay.com/browse/LPS-164647

This is only for master.

@ruben-pulido
@sandrodw3
@p2kmgcl

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.
See https://github.com/liferay-echo/liferay-portal/pull/10147
ci:test:stable - 28 out of 28 jobs passed
ci:test:relevant - 216 out of 221 jobs passed in 1 hour 34 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5346fe7562...718d73bd60

**Comment by brianchandotcom** [comment]
@sandrodw3 just d8b2b75a and 718d73bd

**Pull request closed without merging**
