### PR TITLE
LPS-68947 Pass function references only and check if they exist in runtime only

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @kenjiheigel, these issues look honest to me.. could you please take a look?

**Comment by vicnate5** [comment]
@jbalsas @kenjiheigel,

This does look like a legit failure. The paragraph field is not rendering the correct body value. @brunobasto do you know if the changes here could have affected this?

**Comment by vicnate5** [comment]
ci:close

**Comment by brunobasto** [comment]
@vicnate5, It could. I'll ask someone on the Forms team to have a look at it.

Thanks,

**Comment by diogo-lins** [comment]
@jbalsas @vicnate5 @brunobasto guys, I fix this Poshi error in this PR https://github.com/jbalsas/liferay-portal/pull/648

**Comment by diogo-lins** [comment]
@jbalsas @vicnate5 @brunobasto guys, I fix this Poshi error in this PR https://github.com/jbalsas/liferay-portal/pull/649

**Pull request closed without merging**
