### PR TITLE
Lps 130748

### PR DESCRIPTION
**Pull request by mtambara**
@hhuijser

### CODE REVIEW

**Comment by mtambara** [comment]
ci:reopen

**Comment by mtambara** [comment]
ci:test:sf

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by mtambara** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a874252d8f...4321f4cead

**Pull request closed without merging**
