### PR TITLE
LPS-72471

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/08efb9680d...be4a800827

**Comment by brianchandotcom** [comment]
@Ithildir can you backport to ee-7.0.x and 7.0.x? Thx.

**Comment by brianchandotcom** [comment]
@Ithildir I cherry picked what I could.

**Pull request closed without merging**
