### PR TITLE
master-bc-1115

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LRQA-21165
https://issues.liferay.com/browse/LRQA-21167
https://issues.liferay.com/browse/LRQA-21168
https://issues.liferay.com/browse/LRQA-20845

### CODE REVIEW

**Comment by brianchiu** [comment]
CC @kiyoshilee

**Comment by brianchiu** [comment]
per Kiyoshi I'll retest it

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/51823fa7b5...bb895f7978

**Pull request closed without merging**
