### PR TITLE
Lps 80554

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@michaelhashimoto @pyoo47 what is this?

**Comment by pyoo47** [comment]
@shuyangzhou We're having problems with GitHub when we try to update the label. Our short term solution is to catch the failure and prevent it from bringing down the whole CI build.

**Comment by shuyangzhou** [comment]
Thanks @pyoo47 !

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9115d89332...b23567d1e7

**Pull request closed without merging**
