### PR TITLE
LPS-100679 | LPS-103933 Fix parameters

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@inacionery lots of upgrade failures here. I don't see it in other pulls. Please resend.

**Comment by brianchandotcom** [comment]
@inacionery I think those spa failures may not be from you.. I"m merging this.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/939a1f9f88...30da40cbf5

**Comment by inacionery** [comment]
Thanks!

**Pull request closed without merging**
