### PR TITLE
LPS-61099

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b6d7a522d0...db14490128

**Comment by brianchandotcom** [comment]
@wesleygong @eddieolson "bookmarks" is ready for you. I've synced it to 7.0.x, but I haven't updated it to the subrepo because only Sam can do that.

**Pull request closed without merging**
