### PR TITLE
LPS-73137

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest (I had pushed a tiny change to upstream)

**Comment by brianchandotcom** [comment]
@shuyangzhou @mtambara see new lpkg error

**Comment by brianchandotcom** [comment]
@matethurzo please resend on top of https://github.com/matethurzo/liferay-portal/pull/1708

Can you make the package

"system.event" vs. "systemevent"

Also, this package

com.liferay.systemevent.internal.verify

Looks wrong? Please resend. Thx.

**Comment by shuyangzhou** [comment]
@brianchandotcom those are not lpkg failure but AppResolverHook failure, AppResolverHook is not prepared for concurrent bundles uninstallation.
@amosfong AppResolverHook most likely needs some refactor to better handle this kind of concurrent uninstalling case.

**Comment by amosfong** [comment]
@shuyangzhou, are you installing and immediately uninstalling a bundle before it resolves?

**Comment by shuyangzhou** [comment]
@amosfong The lpkg override cleanup logic is just uninstall orphan bundles as soon as it sees them, which is part of the startup process.

**Comment by shuyangzhou** [comment]
@amosfong as far as I can tell, the resolve hook runs asyncly, which is the root problem, by the time your code receives the notice, lpkg cleanup logic has wiped out all orphan bundles long time ago.
So either we figure out a way to make it running in a sync way, or at least be prepared to see a concurrent uninstalling and not freak out on it.

**Comment by amosfong** [comment]
ok, I think this should fix it
https://github.com/brianchandotcom/liferay-portal-ee/pull/17824

I don't think it can be made synchronous, so I opted to just lower the log level on the exception. No other logic should depend on the bundle existing right now, but it could in the future. I don't want to lower the log level over everything because it's important to see any errors that might come up.

**Comment by shuyangzhou** [comment]
Thanks @amosfong !

**Comment by brianchandotcom** [comment]
Merged in fix from @amosfong 

@matethurzo please resend thx.

**Pull request closed without merging**
