### PR TITLE
LPS-134760 Page audit error handling

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
Hi @brianchandotcom, CI has been very unstable for this PR for unrelated reasons.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a2e49843a1...430f7aa57f

**Comment by brianchandotcom** [comment]
@4lejandrito @beltranrengifo see 86bd723c29aae45f66088b0a246887f63da3be29 and 430f7aa57f598ec36cea82fc649282e5a14980cd

**Pull request closed without merging**
