### PR TITLE
LPS-69309 Add category to Configuration Objects so they appear in System Settings portlet

### PR DESCRIPTION
**Pull request by peterfellwock**

### CODE REVIEW

**Comment by peterfellwock** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@peterfellwock this looks good. I'm merging...

**Comment by brianchandotcom** [comment]
Merged.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0fb03af57c...523ae4dd7f

**Comment by peterfellwock** [comment]
@brianchandotcom thnx

**Pull request closed without merging**
