### PR TITLE
LPS-139107 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-139107

This is only for master.

@vicnate5

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. No need to run ci:test:relevant. Additionally, ci:test:sf passed. Poshi validation passed and Case passed on local.
See liferay-echo#5865
✔️ ci:test:sf - 1 out of 1 jobs passed in 4 minutes

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure task is unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/5861
❌ ci:test:stable - 10 out of 11 jobs passed
❌ ci:test:relevant - 24 out of 27 jobs passed in 3 hours 40 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e503a26bbc...f9b9b388a9

**Pull request closed without merging**
