### PR TITLE
LPS-74544 Auto SF

### PR DESCRIPTION
**Pull request by petershin**
Fixed compile errors<br /><br />@jpince @hhuijser

### CODE REVIEW

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
Pull to fix modules-unit-jdk8: https://github.com/hhuijser/liferay-portal/pull/3147

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/13c9fbf7f9...4e30e41052

**Comment by brianchandotcom** [comment]
@petershin merged.. leaving it to fix them properly / permanently

**Comment by petershin** [comment]
Sent proper fixes:

https://github.com/brianchandotcom/liferay-portal/pull/54637
https://github.com/brianchandotcom/liferay-portal/pull/54613
https://github.com/brianchandotcom/liferay-portal/pull/54648
https://github.com/rafaprax/liferay-portal/pull/265

**Pull request closed without merging**
