### PR TITLE
LPS-80777 Use grid view only for layout prototypes

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jkappler merged, but this pull contradicts (not conflicts with 583102d14bdf28f6cb9670b09328833efaf46637 from @ahdezma

@jkappler please send a follow up pull after talking to @ahdezma 

@jorgeferrer can you coordinate @jkappler and @ahdezma since both are in the same office but missed this even though they are working on similar code.

I've also asked @drewbrokke (over a week ago) to create an abstract/base class display context that is geared for manage tool bar so all this UI logic can be consolidated. Once Drew has bandwidth, he'll read through our existing uses and come up with a way to consolidate them.

Thx everyone.

**Comment by ahdezma** [comment]
hey @brianchandotcom I think this is not me, but @4lejandrito :)

**Comment by 4lejandrito** [comment]
Indeed :) I will talk to @jkappler tomorrow and make sure we do things in the same way. 

Regarding the consolidation that is something I was planning to address once all toolbars have been migrated. It is good to know you guys are planning to do it, feel free to use our help if you need to.

**Comment by ealonso** [comment]
@brianchandotcom @jkappler @4lejandrito @jorgeFerrer

See: https://github.com/brianchandotcom/liferay-portal/pull/58639

**Pull request closed without merging**
