### PR TITLE
LPD-33314 | Master - Follow Up

### PR DESCRIPTION
**Pull request by interaminense**

### CODE REVIEW

**Comment by interaminense** [comment]
Hi @brianchandotcom, this is a follow up after this request change https://github.com/brianchandotcom/liferay-portal/pull/154669

**Comment by interaminense** [comment]
Old: Check back later to verify if data has been received from your data sources.

New: Check back later to see if your data sources have received the data.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e5b321b395...69e1b94b6e

**Comment by brianchandotcom** [comment]
@interaminense see 15c956e48fef60af6d04a59284e0e1834100813e

**Pull request closed without merging**
