### PR TITLE
Lps 68289 58

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@hhuijser please see https://github.com/brianchandotcom/liferay-portal/pull/44890/commits/46af042804e9167345c6586cda51b3adc2c7e37a

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/aa586ae44f...d1a4cd839b

**Comment by brianchandotcom** [comment]
@tinatian can you backport to ee-7.0.x for me?

Thanks.

**Comment by tinatian** [comment]
Sure, I will

**Comment by tinatian** [comment]
See backport here: https://github.com/brianchandotcom/liferay-portal-ee/pull/15194

**Pull request closed without merging**
