### PR TITLE
LPS-55690 Wrong assert usage

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by kiyoshilee** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
Ok, seems working fine now.

@hhuijser, please SF this. Basically preventing people from using org.testng.Assert completely, we should always use org.junit.Assert

**Comment by shuyangzhou** [comment]
@mhan810 forgot to cc you, CI should be fine right now. you can go ahead with your pulls:)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/27e79b8046...0a3330fb03

**Pull request closed without merging**
