### PR TITLE
LPS 115230 6

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7679b1669a...bab0c5680f

**Comment by brianchandotcom** [comment]
@4lejandrito 1.) see aa9a1043 and f0fa4703 Can you apply.

2.) Also, InfoFieldSet has a toString but InfoForm does not. Can you go around and make sure they all have toString

**Comment by 4lejandrito** [comment]
Will do, thanks @brianchandotcom!

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/434.

**Pull request closed without merging**
