### PR TITLE
LPS-71582 SF

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by jpince** [comment]
@leoadb should this have gone to the sub-repo?

**Comment by leoadb** [comment]
@jpince we don't have a subrepo for DDL

**Comment by jpince** [comment]
oh, sorry, I saw a sub-repo exists, but it's in push mode right now (not in use)

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:reopen

**Comment by leoadb** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0b7e5de005...fe3e3ce03c

**Pull request closed without merging**
