### PR TITLE
LPS-53927 pass info along to the SDK

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
I will need to make a couple of changes in the SDK once this is in.

**Comment by rotty3000** [comment]
BTW, it's expected that two files fail on the Source formatting due to their license because I couldn't apply the Liferay license to them. You'll see why.

**Comment by hhuijser** [comment]
Hey @rotty3000 

Should those files completely be ignored by SF?
If so, you can add those to source-formatter.properties#source.formatter.excludes

**Comment by rotty3000** [comment]
Good idea! They probably should be ignored completely.

**Comment by rotty3000** [comment]
I'll update the PR

**Comment by rotty3000** [comment]
ci:retest

**Comment by hhuijser** [comment]
Hey @rotty3000 

I think you should do **/src/com/liferay/ant/bnd/BaselineProcessor.java instead of modules/sdk/ant-bnd/src/com/liferay/ant/bnd/BaselineProcessor.java.
Otherwise it will not properly exclude when running SF from inside the module

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
hmm, ok

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bf873dbf59...fa57a3a135

**Comment by brianchandotcom** [comment]
Hey @rotty3000 

I made some tiny changes in upstream. Ready for the SDK pull. Thx!

**Pull request closed without merging**
