### PR TITLE
LPS-93045 LPS-91645 LPS-91343 | master

### PR DESCRIPTION
**Pull request by jpince**
@preston-crary @4lejandrito @brianchandotcom administrative fixes

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jpince nice!

**Comment by jpince** [comment]
@john-co new js-unit failure? I have not checked upstream results yet
`Execution failed for task ':apps:layout:layout-content-page-editor-web:npmRunTest'.`

**Comment by john-co** [comment]
@jpince, I don't see it in this one that just finished: https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master-private)/7066/AXIS_VARIABLE=0,label_exp=!master/console

**Comment by john-co** [comment]
@jpince confirmed new js unit failure locally at master head.

**Pull request closed without merging**
