### PR TITLE
LPS-59894 Fix performance issues with page versioning and admin user's preferences

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e930ab6f2b...1d4c614b9f

**Comment by brianchandotcom** [comment]
@Preston-Crary please see my changes in upstream. Thx.

**Pull request closed without merging**
