### PR TITLE
LPS-75798

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@ealonso, see https://github.com/brianchandotcom/liferay-portal/pull/53190/commits/1cccb5042ea23b7341f09273c43b74c07e0bcb2a
Basically, have a bunch of methods in DLFileEntryTypeFinderImpl with an obc parameter that is not being used. You can decide if you want to deprecate all of that.

@petershin

**Comment by ealonso** [comment]
cc: @sergiogonzalez

**Comment by petershin** [comment]
@hhuijser - There were no changes in the subrepos.  I'll enable the checks once https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/515 is merged

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/91d29397d3...387c7569df

**Pull request closed without merging**
