### PR TITLE
LPS-100552

### PR DESCRIPTION
**Pull request by adolfopa**
@brianchandotcom This is a new extension point we need for master-private. We
need a way to handle custom exceptions in our JSPs for the O365 integration.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4e12720e31...8f8b145c4f

**Comment by brianchandotcom** [comment]
@AliciaGarciaGarcia @adolfopa see 3c28ca4babb55330619c003d58c43a1cae94e14d

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal-ee/pull/26413

**Pull request closed without merging**
