### PR TITLE
LPS-52273

### PR DESCRIPTION
**Pull request by topolik**
Hi Brian,

fixes for https://github.com/brianchandotcom/liferay-portal/pull/43151 regressions

1, broken test (PropsUtil was moved to class initialization which breaks the test)
2, for the URL length check we need to check URI (including path parameters) and query string

/cc @shuyangzhou

Thanks.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
Thanks @topolik !

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
Removed printStackTrace bd5237f5109b7ba4bc486b86509ebf27c80ce12f @topolik

**Comment by brianchandotcom** [comment]
See bd5237f5109b7ba4bc486b86509ebf27c80ce12f

**Comment by brianchandotcom** [comment]
See https://github.com/liferay/liferay-portal/commit/bd5237f5109b7ba4bc486b86509ebf27c80ce12f

**Pull request closed without merging**
