### PR TITLE
Lps 72046 master 2

### PR DESCRIPTION
**Pull request by SamZiemer**
@migue @achaparro

Resending with the changes requested here: https://github.com/brianchandotcom/liferay-portal/pull/48680#event-1062817984.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
The sites.kernel.util version change is unrelated to the changes in this pull request.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f9ca86bba6...c8370cfc99

**Comment by brianchandotcom** [comment]
@SamZiemer I squashed this to make the backport more manageable.

**Comment by brianchandotcom** [comment]
@achaparro @migue @SamZiemer isn't this just fixing the symptom, and not the root cause? I thought upgrade scripts should only run once, and then the system should know not to run them anymore? I didn't think the individual upgrade scripts needed to manage that?

**Comment by achaparro** [comment]
Hi @brianchandotcom,

You are right, this issue doesn't solve the root cause. However we needed a quick fix for now and redesign the upgrade process to be executed just once, for that reason I have opened the following story:
https://issues.liferay.com/browse/LPS-72339

Thanks!

**Pull request closed without merging**
