### PR TITLE
LPS-90308 Assert copied fragment's contents too

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LPS-90308

This is for master only.

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:reopen

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@brianchiu lots of broken frontend tests? Merged.

**Comment by brianchiu** [comment]
@brianchandotcom They weren't caused by this pull. I'm trying to figure out where they came in.

**Pull request closed without merging**
