### PR TITLE
Arquillian Extension

### PR DESCRIPTION
**Pull request by cgoncas**
Alquilan Extension to configure test environment

### CODE REVIEW

**Comment by cgoncas** [comment]
Hey Brian,
   It is needed to publish this new version of the arquillian-extension in our nexus.
Thanks!!!

@csierra, @shuyangzhou, @JorgeFerrer, @mdelapenya

**Comment by shuyangzhou** [comment]
Can this pull run the integration tests in modules yet?

**Comment by cgoncas** [comment]
No @shuyangzhou , this pull only updates the arquillian-extension, so the test of the portal can be executed in Alquillian, so we can measure how much slower this approach is.

Tomorrow I will sent you a pull that shows how the persistence tests can be executed in modules. But I need to do a big rebase first, and today I don't have the time :(.

Thanks!!!

**Comment by shuyangzhou** [comment]
Sure, tomorrow please provide a pull that contains everything that is needed to run integration tests in modules, so that I can see how it is working and how my changes are breaking on this, in order to find a way to fix it. Thanks!

**Comment by brianchandotcom** [comment]
Please resend on top https://github.com/cgoncas/liferay-portal/pull/92

1.) The PMD failure is real.

LiferayEventTestRunnerAdapter gets a "deleteAfterTestExecutor" but doesn't do anything with it. It looks like you forgot to execute that instance like you do with the other methods.

2.) Why are some of the classes in com.liferay.arquillian.extension.internal.log *Arquillian but not all. I couldn't see the rationale behind what made one class different from the other as far as grouping goes.

Thx

**Pull request closed without merging**
