### PR TITLE
LPS-106537 Implement adding EmailAddress through the Organization POST endpoint

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-106537](https://issues.liferay.com/browse/LPS-106537).<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bff0b0017d...6b61c5a07f

**Comment by brianchandotcom** [comment]
@drewbrokke see 14c406b4fd41416f3e71e3d12f0f1f3752148df6 and 6bc8abb

@achaparro what's up with LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive621021

**Comment by achaparro** [comment]
Hey @brianchandotcom,

It seems that LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive621021 is not related and it's an intermittent issue I usually see in other pulls.

cc/ @drewbrokke

**Pull request closed without merging**
