### PR TITLE
LPS-66013 Some values from test.properties are needed

### PR DESCRIPTION
**Pull request by CAustin582**

### CODE REVIEW

**Comment by CAustin582** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@CAustin582 it's weird that one needs test.* and the other needs release.*

Shouldn't we just have both load both?

**Comment by CAustin582** [comment]
That wouldn't hurt anything, but they each utilize different properties. One needs a couple properties from test and the other needs a property from release.

**Pull request closed without merging**
