### PR TITLE
LPS-68655 Wordsmith

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @jonathanmccann

**Comment by jpince** [comment]
VNC failure, see [LRQA-28169](https://issues.liferay.com/browse/LRQA-28169) @pyoo47 @michaelhashimoto
retesting for backend failures

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
Looks good from a functional test perspective

@shuyangzhou @mtambara inconsistent integration test failures:
PACLAggregateTest.testPACLTests (MySQL)
PACLAggregateTest.testPACLTests (Oracle)
StagingLocalizationTest.testUpdateToTheSameLocale (db2105)
AuditEventPersistenceTest.classMethod (db2105)

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
