### PR TITLE
LPS-202774 add openliberty to app.server.properties

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by vicnate5** [comment]
Per discussion between @marco-leo and @david-truong this adds open liberty build support, but no automation coverage. Open Liberty gives us leverage to drop Websphere and JDK8

**Comment by marco-leo** [comment]
HEy @vicnate5 This is different than a simple ant script as Dave described me. We won't merge

**Comment by brianchandotcom** [comment]
Here's the argument:

Add OpenLiberty (just an Ant script) so that WebSphere folks can move to it. Then, we can drop JDK 8 suppoprt.

My counter argument:

WebSphere to Open Liberty will never work without significant effort in testing Open Liberty. Therefore, it's not just an Ant script.

Instead, just drop JDK 8 support. Existing WebSphere users must migrate out. This is an OK risk even for existing WebSphere lovers, because even they are being pressured to move to the Cloud/Docker. Therefore, Docker+Tomcat+Liferay is good enough.

Just drop JDK 8.

@vicnate5 @marco-leo @david-truong fyi

**Comment by david-truong** [comment]
@brianchandotcom  that is exactly the plan. We are just preparing for the worst case scenario because I have spoken to different stakeholders in existing Websphere projects and the initial impression was that they would not move to docker.

@marco-leo sorry I forgot to tell @vicnate5 to drop the java class. We were too focused on how to ensure there would be no testing done for the PR

**Pull request closed without merging**
