### PR TITLE
LPS-79983 Add implementing relationship resources for ddm - journal

### PR DESCRIPTION
**Pull request by matethurzo**
@brianchandotcom the reason I've organized the module this way is that I wanted to avoid cross LPKG references between foundation/ddm/journal. I decided to follow the APIO approach where the api is in foundation and the actual implementations are at the same level.
let me know if this is a good approach or you prefer something else

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test

**Comment by matethurzo** [comment]
ci:reopen

**Comment by matethurzo** [comment]
the failures are not related to this change

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2d8aa718fe...2d4c7833ea

**Pull request closed without merging**
