### PR TITLE
LPS-165118 Add validation picklist default value

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
Original PR :  https://github.com/liferay-objects/liferay-portal/pull/1248 .

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@pedro-oliveira446 This seems weird because validation methods do not usually change data

```
	private Map<String, Serializable> _validatePicklistDefaultValue(
		List<ObjectField> objectFields, Map<String, Serializable> values) {

		for (ObjectField objectField : objectFields) {
			if (Objects.equals(
					objectField.getBusinessType(),
					ObjectFieldConstants.BUSINESS_TYPE_PICKLIST) &&
				!values.containsKey(objectField.getName())) {

				values.put(
					objectField.getName(), objectField.getDefaultValue());
			}
		}

		return values;
	}

```

Please resend. Thx.

**Comment by gabrielwas** [comment]
@pedro-oliveira446 this isn't a validation. This method fills missing values with a default value. You can name it `_fillPicklistDefaultValue`

**Comment by pedro-oliveira446** [comment]
@gabrielwas I already sent another PR changing the name to `_addDefaultValueFromPicklistRemoved`. Should I change?

**Comment by gabrielwas** [comment]
@pedro-oliveira446 no no. That's ok too!

**Comment by gabrielwas** [comment]
@pedro-oliveira446 could you resent it? Thx!

**Comment by pedro-oliveira446** [comment]
@gabrielwas done ! Thx!

**Pull request closed without merging**
