### PR TITLE
LPS-74405 Liferay Forms radio button options don't submit properly on IE11

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e2614a2953...b683a41ba1

**Comment by brianchandotcom** [comment]
@hhuijser see SF unit test error  @petershin

I temporarily ignored it in b683a41ba1d2f4d30b968ce4f41b29fa4f80d786

Please fix. Thx.

**Comment by hhuijser** [comment]
@petershin, got the fix in here: https://github.com/brianchandotcom/liferay-portal/pull/51393

**Pull request closed without merging**
