### PR TITLE
LPS-143592 Fix bug getting the aggregations value in GraphQL query

### PR DESCRIPTION
**Pull request by javierdearcos**
Checking the usage of aggregations in GraphQL I've detected this bug.

I send you the fix directly to save time and get the GraphQL aggregations working

### CODE REVIEW

**Comment by javierdearcos** [comment]
ci:reopen

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by javierdearcos** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6872211269...3b00a6d66a

**Pull request closed without merging**
