### PR TITLE
Lps 75293

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/efeb211250...d8c64f3f64

**Comment by brianchandotcom** [comment]
@tinatian @lanceji92674957 please backport to 7.0.x. Thx.

**Comment by tinatian** [comment]
@brianchandotcom Done, please see https://github.com/brianchandotcom/liferay-portal-ee/pull/18661

**Pull request closed without merging**
