### PR TITLE
LPS-108756 SF

### PR DESCRIPTION
**Pull request by inacionery**
/cc @BryanEngler

### CODE REVIEW

**Comment by barrosdennys** [comment]
Some search tests didn't start to run. The failures are not related to this PR.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e19cf8b8dd...0921029e3c

**Comment by brianchandotcom** [comment]
Beautiful @inacionery I'm leaving the LPS tickets to you.

**Comment by inacionery** [comment]
Thanks @brianchandotcom

**Pull request closed without merging**
