### PR TITLE
LPS-88733 Headless Forms Client Tests

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c66ee77143...5fabc3b64d

**Comment by brianchandotcom** [comment]
@cgoncas I assume these cannot be sorted since order matters?

```
		).body(
			"hasFormRules", isBoolean()
		).body(
			"showLabel", isBoolean()
		).body(
			"repeatable", isBoolean()
		).body(
			"required", isBoolean()
		);
```

**Comment by cgoncas** [comment]
Hey @phcp , Do you think we can sort it?

**Comment by phcp** [comment]
Yeah, we can sort it @cgoncas, the order doesn't matter in this case.

**Pull request closed without merging**
