### PR TITLE
LPS-104376 buildLang

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ee6369d1df...131e54fee7

**Comment by brianchandotcom** [comment]
@4lejandrito merged, but can you fix:

```
DepotPanelAppControllerTest.testGetPanelAppsDoesNotShowTheConfigurationCategoryForADepotGroup
```

Also, make a method called DepotEntryGroupRelLocalServiceImpl#updateSearchable(long depotEntryGroupRelId, boolean searchable)

This matches our pattern for UserLocalServiceImpl#updatePassword

Also, make a remote DepotEntryGroupRelServiceImpl#updateSearcheable

And then, make sure EditDepotEntryGroupRelMVCActionCommand is calling that one instead of _depotEntryGroupRelLocalService.updateDepotEntryGroupRel(. Otherwise, a hacker can mess things up.

**Comment by 4lejandrito** [comment]
Hi @brianchandotcom,

The test should have been fixed by https://github.com/brianchandotcom/liferay-portal/pull/82027.

We were planning to handle permissions in a separate story (we need new roles to update depot entries and rels). 

I'll send `updateSearchable` in a follow up pull.

Thanks!

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/82120.

**Pull request closed without merging**
