### PR TITLE
LPS-76842 Add a new field nameTreePath to the Organization Indexed document

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @marco-leo @drewbrokke @arboliveira

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test

**Comment by jpince** [comment]
@pei-jung I see the following backend tests failing in modules-int* batches. Can you please take a look?
```
com.liferay.blogs.internal.exportimport.portlet.preferences.processor.test.BlogsAggregatorExportImportPortletPreferencesProcessorTest.testProcessOrganizationId
com.liferay.organizations.service.test.OrganizationLocalServiceTest.testSearchOrganizationsAndUsers
com.liferay.organizations.service.test.OrganizationLocalServiceTest.testSearchOrganizationsAndUsersWhenNoUsers
com.liferay.users.admin.indexer.test.OrganizationIndexerTest.testEmptyQuery
com.liferay.users.admin.indexer.test.OrganizationIndexerTest.testName
com.liferay.users.admin.indexer.test.OrganizationIndexerTest.testNameMultiword
com.liferay.blogs.recent.bloggers.internal.exportimport.portlet.preferences.processor.test.RecentBloggersExportImportPortletPreferencesProcessorTest.testProcessOrganizationId
com.liferay.organizations.service.test.OrganizationLocalServiceTreeTest.testRebuildTree
```

**Comment by jpince** [comment]
ci:close

**Comment by marco-leo** [comment]
@jpince @pei-jung sent to https://github.com/brianchandotcom/liferay-portal/pull/54116

**Pull request closed without merging**
