### PR TITLE
LPS-76591 Remove tests and references to DDL Form Web portlet

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
cc.: @leoadb

**Comment by pedroqueiroz94** [comment]
ci:test

**Comment by vicnate5** [comment]
@pedroqueiroz94 Unique failures here

**Comment by vicnate5** [comment]
ci:close

**Comment by vicnate5** [comment]
Sent fix https://github.com/pedroqueiroz94/liferay-portal/pull/39

**Pull request closed without merging**
