### PR TITLE
LPS-201191 Add Object Definitions test cases to be exported in CSV

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What is new?**
- Create some tests cases to export Object Definition in a default company and in a new one.
- Add new CSV file to compare with the exported one.

**JIRA Related Ticket**
https://liferay.atlassian.net/browse/LPS-201191

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:reopen

**Comment by sergiojimcos** [comment]
Forwarded from: https://github.com/liferay-headless/liferay-portal/pull/1669

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a18f8f6eb1...5fe511d562

**Comment by brianchandotcom** [comment]
@sergiojimcos @4lejandrito see minor changes in my origin. Thx.

**Pull request closed without merging**
