### PR TITLE
LPS-82242 Adding back the right translations

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jorgeferrer @martamedio Hey guys, @4lejandrito is fixing your pull from

https://github.com/brianchandotcom/liferay-portal/pull/59868

I'm not sure what else may be broken from:

https://github.com/brianchandotcom/liferay-portal/pull/59868

and

https://github.com/brianchandotcom/liferay-portal/pull/59869

@martamedio please go through the keys and fix. Thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/49af57e425...1e04f72793

**Comment by brianchandotcom** [comment]
@martamedio @jorgeferrer specifically https://github.com/brianchandotcom/liferay-portal/pull/59868/commits/f201b73dc6010f35b698b4379ed4eb8701b12cb8

**Comment by martamedio** [comment]
I checked it with @4lejandrito this morning and I think with this fix everything is all right.

Thanks!

**Pull request closed without merging**
