### PR TITLE
LRQA-34969

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-34969

### CODE REVIEW

**Comment by jpince** [comment]
thanks @anthony-chu!

**Comment by anthony-chu** [comment]
ci:reopen

**Comment by jpince** [comment]
SF fix: https://github.com/liferay/liferay-portal/commit/0d58dde45271e175f7e1071bfc92da42aeeebd9c

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4da22aac08...90efac9c9f

**Pull request closed without merging**
