### PR TITLE
OAUTH2-241 Do not prefix scopes with application name

### PR DESCRIPTION
**Pull request by csierra**
/cc @topolik @stian-sigvartsen @petershin @xbrianlee

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@csierra I'm a bit confused, if I merge this, does that mean *all* headless apps that use portal-vulcan share one namespace, or will I still be able to configure each headless app separately?

**Comment by topolik** [comment]
Oops, sorry, didn't notice @csierra already answered :)

**Comment by brianchandotcom** [comment]
Very nice. Thx @csierra can you resend and sort the *.config entries, and also sort inside:

mapping=["GET\,HEAD\,OPTIONS\=everything.read","PUT\,POST\,PATCH\,DELETE\=everything\,everything.write","everything.write\=everything\,everything.write"]

Thx!

**Comment by csierra** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/67751

**Pull request closed without merging**
