### PR TITLE
SYNC-1615

### PR DESCRIPTION
**Pull request by shinnlok**

### CODE REVIEW

**Comment by brianchiu** [comment]
Xss and Wiki failures are most likely due to a bug (but not related to this pull because they're failing in other pulls).

@sharonchoi @nikki-pru @patriciajeanperez @austinchiang Can you all take a look?

after3

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a508098fbc...5c140bfa22

**Comment by brianchandotcom** [comment]
@ZoltanTakacs @zsoltbalogh I backported this because sync-engine is not actually part of MP.

**Comment by ZoltanTakacs** [comment]
Thank you

**Pull request closed without merging**
