### PR TITLE
Lps 77361 rebase

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@michaelhashimoto @pyoo47 what's up with these crazy SF errors that aren't right? Are you sure you're testing the right hash?

@kiyoshilee fyi.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cc313ed6a3...33826b084d

**Comment by pyoo47** [comment]
@brianchandotcom The SF failure is actually a valid failure in liferay-portal-ee(master-private) upstream. It got flagged as a failure here because git-commit-portal-private was modified to use a pull request. Including a pull request as the git-commit-portal-private caused SF to check the private modules and it encountered the failure. The failure did not get marked as an upstream failure because liferay-portal pull request tester only checks for liferay-portal upstream failures. I'm not really sure exactly how or why we include the private modules when we use a pull request as the git-commit-portal-private. If you want to stop that behavior I can create a ticket and get that implemented since the liferay-portal-ee pull request should be tested on its own anyway.

**Pull request closed without merging**
