### PR TITLE
LPS-103966 Improve build times

### PR DESCRIPTION
**Pull request by petershin**
Hi Brian, these changes saved about 1 min or 5%.

Tests passed here: https://github.com/petershin/liferay-portal/pull/773#issuecomment-548523090

@jbalsas @john-co

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c14ecfaf6c...b7d7263512

**Comment by brianchandotcom** [comment]
@jbalsas can you send me a backport to 7.2.x? All of us working on 7.2.x will thank you!

**Comment by brianchandotcom** [comment]
@jbalsas for your backport, please include fixes from @petershin

**Comment by jbalsas** [comment]
Hey @brianchandotcom, backported for you here -> https://github.com/brianchandotcom/liferay-portal-ee/pull/27377

**Pull request closed without merging**
