### PR TITLE
LPS-92716 Stylistic fixes

### PR DESCRIPTION
**Pull request by bryceosterhaus**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/45049b82b4...41ce96335a

**Comment by brianchandotcom** [comment]
@bryceosterhaus @dgarciasarai see 667b7ee4586cb0abd2c51a1a39469643a1db5d32

**Comment by brianchandotcom** [comment]
@dgarciasarai @bryceosterhaus I had to revert this as this build does not compile

```
$ gw :apps:segments:segments-web:buildCSS
Configuration on demand is an incubating feature.

> Task :apps:segments:segments-web:buildCSS FAILED
Using native Sass compiler
Exception in thread "main" com.liferay.sass.compiler.jni.internal.JniSassCompilerException: Error: Undefined operation: "gap times 2".
        on line 22 of src/main/resources/META-INF/resources/css/_conjunction.scss
>> 	margin-top: gap * 2;
   -------------^

	at com.liferay.sass.compiler.jni.internal.JniSassCompiler.compileFile(JniSassCompiler.java:164)
	at com.liferay.css.builder.CSSBuilder._parseSass(CSSBuilder.java:380)
	at com.liferay.css.builder.CSSBuilder._parseSassFile(CSSBuilder.java:394)
	at com.liferay.css.builder.CSSBuilder.execute(CSSBuilder.java:160)
	at com.liferay.css.builder.CSSBuilder.main(CSSBuilder.java:79)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':apps:segments:segments-web:buildCSS'.
> Process 'command '/opt/java/jdk1.8.0_121/bin/java'' finished with non-zero exit value 1

* Try:

```

Please resend.

**Comment by dgarciasarai** [comment]
I'll resend. Thanks.

**Pull request closed without merging**
