### PR TITLE
Lps 74937

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:test

**Comment by brianchandotcom** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e4b4efa182...a7e9a71153

**Comment by brianchandotcom** [comment]
@slnn @shuyangzhou please see my changes in upstream. Thx.

**Pull request closed without merging**
