### PR TITLE
LPS-95246 Fix multiple user regression on UI

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:stop

**Comment by matethurzo** [comment]
ci:stop

**Comment by jpince** [comment]
@danielkocsis @matethurzo can you please also forward https://github.com/brianchandotcom/liferay-portal/pull/73844/commits/10a3bd9ecd728abdf4ff80e6065c7eaea35c407e?

**Comment by jpince** [comment]
@danielkocsis @matethurzo or something that will satisfy SF.
`     [java] 1: SQL '(BackgroundTask.status = ?) AND' does not exist in the custom-sql file: ./modules/apps/change-tracking/change-tracking-service/src/main/java/com/liferay/change/tracking/service/persistence/impl/CTProcessFinderImpl.java 116 (SourceCheck:JavaFinderImplCustomSQLCheck)`

**Comment by danielkocsis** [comment]
@jpince the fix is included here: https://github.com/brianchandotcom/liferay-portal/pull/73836 in the last commit.

**Comment by jpince** [comment]
great, thanks!

**Pull request closed without merging**
