### PR TITLE
LPS-105225 add full URL

### PR DESCRIPTION
**Pull request by javiergamarra**
This
`resourceMethodInfoDTO.path = applicationDTO.base + resourceMethodInfoDTO.path;`

is not an issue because I'm iterating through _resourceMethodInfoDTO_

`for (ResourceMethodInfoDTO resourceMethodInfoDTO : resourceDTO.resourceMethods) {`

So a different DTO object is used every time, I don't reuse the same instance in each loop cycle.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:test:stop

Ok, merging!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9d104d7ab4...c7958b6722

**Comment by brianchandotcom** [comment]
@nhpatt what about multiple threads? new RuntimeDTO per thread?

**Comment by nhpatt** [comment]
@brianchandotcom JAX-RS resources are thread safe, a new instance is created per every request, so the method should be single threaded.

**Pull request closed without merging**
