### PR TITLE
master-vw-551

### PR DESCRIPTION
**Pull request by vicnate5**
@diogo-lins @brunobasto

### CODE REVIEW

**Comment by stsquared99** [comment]
ci:close

**Comment by stsquared99** [comment]
ci:reopen

**Comment by stsquared99** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/18d51d180c...75b6752ccc

**Comment by brianchiu** [comment]
Compile failure caused by: https://github.com/liferay/liferay-portal/commit/021b6419149bffbf434d9cb378955d99735b2745

Fixed by: https://github.com/liferay/liferay-portal/commit/72367fb0957b15da3f48524d639248270cc61b26

I'm retesting this pull.

**Comment by brianchiu** [comment]
ci:retest

**Pull request closed without merging**
