### PR TITLE
LPS-66668 This page was not created in this test.

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by vicnate5** [comment]
Hey @brandizzi there is an issue with the new test. If you close this, I can resend with the fix.

**Comment by vicnate5** [comment]
@brianchandotcom Please do not merge yet.

**Comment by brianchandotcom** [comment]
@vicnate5 please resend. Thx.

**Pull request closed without merging**
