### PR TITLE
LPS-67021

### PR DESCRIPTION
**Pull request by natecavanaugh**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by sharonchoi** [comment]
There is currently a regression bug that was merged, and we're currently investigating here: https://issues.liferay.com/browse/LPS-67065, which causes these Staging POSHI tests to fail.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3f8a30df9d...d67e4b952b

**Comment by brianchandotcom** [comment]
Hey @marcoscv-work @natecavanaugh 

Thanks for this new theme.

1.) Missed gulfpile.js d28352534df52b2fbff77f1814dfda3de28d8465 without it, Gradle won't see it as a theme.

2.) The task cache contained the war for product-app-theme.war. We can't cheat like that :) See my proper regen in d67e4b952b67074c41399f480cafd77d5e9b422e

Thx guys.

**Comment by marcoscv-work** [comment]
I see @brianchandotcom thank you!

**Pull request closed without merging**
