### PR TITLE
LPS-159739 Hide Theme JS option since it is not used for now

### PR DESCRIPTION
**Pull request by david-gutierrez-mesa**
https://issues.liferay.com/browse/LPS-159739

### CODE REVIEW

**Comment by david-gutierrez-mesa** [comment]
Send directly to BChan since tests failing in the [original PR](https://github.com/liferay-echo/liferay-portal/pull/9198) are not related.

✔️ ci:test:stable - 27 out of 27 jobs passed
❌ ci:test:relevant - 53 out of 56 jobs passed in 1 hour 34 minutes
[Click here for more details.](https://github.com/liferay-echo/liferay-portal/pull/9198#issuecomment-1206221966)

**Comment by david-gutierrez-mesa** [comment]
Also, SF passed:
✔️ ci:test:sf - 1 out of 1 jobs passed in 3 minutes
[Click here for more details.](https://github.com/liferay-echo/liferay-portal/pull/9198#issuecomment-1206141067)

**Comment by david-gutierrez-mesa** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d987112388...7d35ae8bb0

**Comment by brianchandotcom** [comment]
@victorg1991 @david-gutierrez-mesa see 7d35ae8bb0634a9c0fef295ecdeb9686b8bcb88f easier that way

**Pull request closed without merging**
