### PR TITLE
LPS-66853

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
See https://github.com/liferay/com-liferay-journal/pull/2

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@hhuijser what about 7.0.x? Can you send me a port there too?

**Comment by hhuijser** [comment]
@brianchandotcom 

You can go ahead and cherry pick this to ee-7.0.x
Additional commit: https://github.com/brianchandotcom/liferay-portal-ee/pull/14184

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
