### PR TITLE
Lps 59342

### PR DESCRIPTION
**Pull request by shuyangzhou**
@csierra @migue Sorry for the long delay on the review, it has been a busy week.

I have made quite a few changes in this pull, I am trying my best to make sure no logic has changed, I kept most of your tests to make sure it. All the changes I made here are about simplifying the structure and design.

If by any chance I broke the logic, please let me know, I will fix it. Or if you don't like the design changes, we can talk about it.

Thanks

Shuyang

### CODE REVIEW

**Comment by csierra** [comment]
hey @shuyangzhou @migue 

yes, if you have the time I would like to discuss the changes you made. There are some use cases we originally had that are gone now. They may not be coded into the tests and that may be why you were not aware of them. 

Thx.

**Comment by csierra** [comment]
I will try to summarize here the whys of the proposed architecture:
**`Supplier<Dictionary<String, Object>`**: the `Supplier<T>` interface is introduced as a way to lazily provide the dictionary of strings to the framework. Given the nature of the configurator it is only going to kick in the first time a bundle is deployed on the system, and never more, so it is unnecessary to parse hundreds of property files (or something else, since this behavior is pluggable) to be discarded later. Using `Supplier<T>`, or any other equivalent, is a good way of only parsing the properties when they are truly needed.

**`BundleStorage`**: `Bundle` interface has too many methods. Among them you can `start()` or `stop()` the bundle, access the `BundleContext` and install services on behalf of that bundle or resolve services or install new bundles. Since the framework is meant to be extended so the clients can provide their own ways of providing default values I believe it is wise to limit the scope of what is expected from the framework, and provide nothing more.

**`Factory` and `SingleConfigurationDescription`**: these classes are part of a model to be used by the clients extending the framework. I believe it is better not to rely on null values and use them as a switch in the API. If these were internal classes I would not mind but, being these part of an API, I strongly prefer to keep two classes instead of one class and pass nulls around. 

**`ConfigurationContent` and `ConfigurationDescription`**: the purpose of these classes is to make it easier for clients of the framework to provide extensions by decoupling the location of the configuration from the actual format of the configuration. The default behavior looks for configurations in a directory pointed by a header in the bundle, but a client might want to extend this by using a fixed directory and skip the header, but they might still want to use a property file. Another client might want to keep the lookup strategy but use JSON as their format for their configuration. With the first architecture our provided classes only took into account the clasess of the model they knew. If a customer wanted to use the property format (including the name parsing for differentiating factories from single configurations) but with a different location they only needed to return a `PropertiesFileNamedConfigurationContent` and our provided Factory will take care of it. If the class is different our factory will not process it, thus allowing a third party provided service to do the job without issuing an error. 

I hope these explanations are good enough to shed some light on my original intentions and we can think about the design again taking them into account. 

Bests. 

Carlos.

**Comment by shuyangzhou** [comment]
> Supplier<Dictionary<String, Object>: the Supplier<T> interface is introduced as a way to lazily provide the dictionary of strings to the framework. Given the nature of the configurator it is only going to kick in the first time a bundle is deployed on the system, and never more, so it is unnecessary to parse hundreds of property files (or something else, since this behavior is pluggable) to be discarded later. Using Supplier<T>, or any other equivalent, is a good way of only parsing the properties when they are truly needed.

This is an extender, which means it is only called on bundle deployment, for this part, it is already lazied, does not have anything to do with Supplier.

The extender on seeing a "ConfigurationPath" in the incoming bundle header, always load and configure the bundle, there is nothing lazy here. Before my changes, the only actual usage is in the 2 _process() methods inside ConfiguratorExtension, they always call "Supplier.get()" right after the Supplier's creation, this is not a lazy creation but an additional unnecessary data wrapper. 
Please correct me if I misread the code.

>BundleStorage: Bundle interface has too many methods. Among them you can start() or stop() the bundle, access the BundleContext and install services on behalf of that bundle or resolve services or install new bundles. Since the framework is meant to be extended so the clients can provide their own ways of providing default values I believe it is wise to limit the scope of what is expected from the framework, and provide nothing more.

If this is a public api that some other bundle is going to use, I will totally agree with you. But it is not, BundleStorage is only used for bundle internal usage, since it is internal, we control all code's behavior, there is no reason we setup rules for ourselves to forbid things that we will never do. Just simply use the Bundle interface, that will make thing cleaner and simpler.

>Factory and SingleConfigurationDescription: these classes are part of a model to be used by the clients extending the framework. I believe it is better not to rely on null values and use them as a switch in the API. If these were internal classes I would not mind but, being these part of an API, I strongly prefer to keep two classes instead of one class and pass nulls around.

The way I am doing this is exactly how the OSGi configadmin api is doing it. It is a much uniformed api, that we don't have to do instance of on usage. I don't think people will be confused by the null factoryPid, for anyone who will use this api must already know the standard OSGi configadmin api, keep them in the same style will keep things consistent and easier for other developers to understand.

>ConfigurationContent and ConfigurationDescription: the purpose of these classes is to make it easier for clients of the framework to provide extensions by decoupling the location of the configuration from the actual format of the configuration. The default behavior looks for configurations in a directory pointed by a header in the bundle, but a client might want to extend this by using a fixed directory and skip the header, but they might still want to use a property file. Another client might want to keep the lookup strategy but use JSON as their format for their configuration. With the first architecture our provided classes only took into account the clasess of the model they knew. If a customer wanted to use the property format (including the name parsing for differentiating factories from single configurations) but with a different location they only needed to return a PropertiesFileNamedConfigurationContent and our prov ided Factory will take care of it. If the class is different our factory will not process it, thus allowing a third party provided service to do the job without issuing an error.

I get what you are saying, but, the reason that I merged them is because the current impl is too simple, the properties locating has some real complex logic, but the properties parsing logic is literally a single line of code. I bet the JSON version you are talking about will also have no more than just a couple lines.

So the main logic is just about the propreties locating, not the parsing part. And there is no way to reuse the locating logic, a new extension will have to rewrite its locating logic anyway, then it can just add in its couple lines of parsing by the way.

The point is, by far, we don't have any extensions, they are all imaginary ones. In case we never really have them, have these unecessary "flexible" api now is just adding complexity. In case we really need to add them, I believe it will be the case I described, which is new extension can easily rewrite both locating and parsing logic. Even if it is not, it won't be difficult to split them and add in the flexible api by that time.

There is no reason to pay all the design complexity up front, there is a good chance we will never need them. If we really do, we can always refactor later, with better insight of the problems.

These are just how I am understanding the problems, which you may not agree, but that's fine. We can talk more on Monday if you prefer(You can ping me anytime tomorrow). Or if you really want it in your way, that's fine too. We can just use this pull as a new base (assuming I did not break any logic, and this is a bare minimal/clean version of what you want), to add back in the requirements you want, but please do them one by one, so that we will have a better view of what they are and whether we really want them.

**Comment by csierra** [comment]
hey @shuyangzhou 

>Before my changes, the only actual usage is in the 2 _process() methods inside ConfiguratorExtension, they always call "Supplier.get()" right after the Supplier's creation, this is not a lazy creation but an additional unnecessary data wrapper. 
Please correct me if I misread the code.

the `Supplier<Dictionary<String, Object>>` is only invoked after `_configurationExists()` as you can see [here](https://github.com/shuyangzhou/liferay-portal/commit/9b2c960c910ea1d77bfa782fb8d271ad9730a77f#diff-cb309585fb9d6aecaa11f73172039b34R132) or [here](https://github.com/shuyangzhou/liferay-portal/commit/9b2c960c910ea1d77bfa782fb8d271ad9730a77f#diff-cb309585fb9d6aecaa11f73172039b34R166). So we almost never call `Supplier.get()`. Most of the time there will exist a `Configuration` already for the given description so there is no need to parse any file, hence the `Supplier`, to ask for the properties only when the framework finds it suitable. This is very common indeed and I don't really think it is such a burden. 

>If this is a public api that some other bundle is going to use, I will totally agree with you. But it is not, 

How come it is not!? `NamedConfigurationContentFactories` are injected and used as you can see [here](https://github.com/shuyangzhou/liferay-portal/commit/9b2c960c910ea1d77bfa782fb8d271ad9730a77f#diff-09e850db0e9fb8bbbce1fdab3a69536eR78) and [here](https://github.com/shuyangzhou/liferay-portal/commit/9b2c960c910ea1d77bfa782fb8d271ad9730a77f#diff-09e850db0e9fb8bbbce1fdab3a69536eR105). This was originally designed with extensibility in mind, hence the `BundleStorage`. If, as you said, you agree it is a good idea if this is a public API then we should keep it because this is indeed a public API. 

>The way I am doing this is exactly how the OSGi configadmin api is doing it. It is a much uniformed api,
that we don't have to do instance of on usage. I don't think people will be confused by the null factoryPid, for anyone who will use this api must already know the standard OSGi configadmin api, keep them in the same style will keep things consistent and easier for other developers to understand.

The users of the API don't need to know how ConfigAdmin API works. We might enter a styles battle here. It is my opinion, and others', that using nulls in APIs is a very very bad idea. I can't see why any developer would find it more difficult to understand a two classes hierarchy than to have to pass null to the first parameter in a constructor. I actually find it weird and error prone. Why can I null the first parameter in the constructor and not the rest of them? 

>So the main logic is just about the propreties locating, not the parsing part. And there is no way to reuse the locating logic, a new extension will have to rewrite its locating logic anyway, then it can just add in its couple lines of parsing by the way.

But why coupling? If these are separate concerns we should keep them separated. No matter how many lines it takes to implement. 

>The point is, by far, we don't have any extensions, they are all imaginary ones. In case we never really have them, have these unecessary "flexible" api now is just adding complexity. In case we really need to add them, I believe it will be the case I described, which is new extension can easily rewrite both locating and parsing logic. Even if it is not, it won't be difficult to split them and add in the flexible api by that time.

Of course we don't have any extensions, we haven't even released this! This is a chicken and egg problem... if you don't release an extensible API how is it going to be extended? This is meant to be extended by third parties and developers not necessarily ourselves. 

> There is no reason to pay all the design complexity up front, there is a good chance we will never need them. If we really do, we can always refactor later, with better insight of the problems.

But what complexity are we paying? I totally disagree here. Two classes and one interface is not complex to me. Coupling and nulls are. It is not the number of things you have that create complexity, but the way they relate and intertwine. Having clean separation of concerns and clean API's is *"cheaper"*.

>These are just how I am understanding the problems, which you may not agree, but that's fine. We can talk more on Monday if you prefer(You can ping me anytime tomorrow). Or if you really want it in your way, that's fine too. We can just use this pull as a new base (assuming I did not break any logic, and this is a bare minimal/clean version of what you want), to add back in the requirements you want, but please do them one by one, so that we will have a better view of what they are and whether we really want them.

We really prefer the pull as we originally sent it. I have taken your contributions to the tests and formatting. Please see https://github.com/brianchandotcom/liferay-portal/pull/32216 as the pull we want to be merged since it has all the originally intended features. 

Thx for your time.

**Comment by shuyangzhou** [comment]
I guess we just have to agree to disagree on this. When it comes to design, there are many directions, I am always leaning to the simplest one. Over the years, I slowly realize nothing will cost you more than the maintain overheads.

Since this is your code, and you insist it in your way, I won't block you.

But I just feel this can be handled in a better way than bypassing this pull to send another one.

No hard feeling, at least we agree on the functions, just disagree on the impls. In the future if you don't want your impl to be changed, please state it first, that way we can both save some effort. Otherwise things pass my review will need to meet my standards.

**Comment by csierra** [comment]
hey @shuyangzhou 

> In the future if you don't want your impl to be changed, please state it first, that way we can both save some effort

I did that in the original pull I sent you... I asked you to review the six last commits regarding the tests because that was something you and Will worked with in the past. This all ended up in your plate because of the failing tests in the CI. Giving you extra work can't be further from my intention. 

My mistake was not to state that again in the latest pull. I can not expect you to remember the context of everything you work with everyday.

> Otherwise things pass my review will need to meet my standards

This makes me sad. I will really would like to be able to collaborate more with you and send code back and forth. The fact that you change most of what I make and send it to Brian to merge is not a confortable situation for me. I would rather be I hope you realize this. I really wish we can learn to work together and feel respected.

> But I just feel this can be handled in a better way than bypassing this pull to send another one.

You might be right here... but this had been waiting long time to get to master and I did not want you to waste more time on this. I would have preferred that you had sent the pull back to me instead of Brian. I felt bypassed too and that my opinion on the matter did not count. 

> No hard feeling

Same thing here. I never wanted to hurt your feelings or make you waste time. I just try to make things better for everybody. If by chance I have offended I apologize and will try to make things better in the future. 

Bests.

**Comment by shuyangzhou** [comment]
Yeah, no worries, let's turn this page over and do better in the future.

**Pull request closed without merging**
