### PR TITLE
LPS-61818 fix branch selector

### PR DESCRIPTION
**Pull request by juliocamarero**
Hey @matethurzo, I have applied the same UI of the scope selector

web_content_-_sample_-_liferay

### CODE REVIEW

**Comment by juliocamarero** [comment]
Hey @matethurzo, 

now I see the picture I think the variation should be below the public pages link, right?
variations only affect a layoutset... am I right?

**Comment by juliocamarero** [comment]
Ok, now it looks like this. We can remove the last commit otherwise. thanks!

web_content_-_sample_-_liferay

**Comment by juliocamarero** [comment]
ci:retest

**Comment by matethurzo** [comment]
@juliocamarero yes the variation is either layout set or layout. definitely not above.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b3b6675d4d...dc5894a026

**Pull request closed without merging**
