### PR TITLE
LPS-60027

### PR DESCRIPTION
**Pull request by danielkocsis**
cc'-ing: @csierra and @matethurzo

### CODE REVIEW

**Comment by danielkocsis** [comment]
It has a lot of test failures because of an issue on master we have today (SocialActivityConstants
 and Bookmarks), but it is unrelated from the change.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@danielkocsis errors are unrelated.. except for "ModulesStructureTest.testScanBuildScripts" I'll fix them.

**Comment by brianchandotcom** [comment]
@danielkocsis please resend. "test.war" needs to be made at test time... cannot be just a black box.

Please send it to @Ithildir to send it to me.

Ideally, I'd like to see a commit of the "old" test war source into here so I know what was copied and what is new.

Thx.

**Pull request closed without merging**
