### PR TITLE
LPS-75377 Remove code that is no longer needed

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
ci:test

**Comment by JorgeFerrer** [comment]
ci:reopen

**Comment by alee8888** [comment]
@JorgeFerrer these will cause Poshi test failures. Can we please discuss this further? Thanks!

**Comment by JorgeFerrer** [comment]
@alee8888 as we've discussed, Brian Lee has already adapted the Poshi tests and his commits are part of the pull.

**Pull request closed without merging**
