### PR TITLE
LPS-79146 Revert "LPS-75962 Stop deploying this module unstill the jvm shutdown hanging issue is fixed."

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:test

**Comment by timpak** [comment]
ci:retest

**Comment by timpak** [comment]
@kenjiheigel @michaelhashimoto @yichenroy

some of the functional test cases are failing with the following error:
java.lang.IllegalStateException: Specified firefox binary location does not exist or is not a real file: /opt/firefox-52.0.2esr/firefox

See: 
[functional-tomcat80-hypersonic20-jdk8/0](https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/150573/) 
[functional-tomcat80-mysql56-jdk8/1](https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/150573/)

**Comment by timpak** [comment]
@marcellustavares @brunobasto 

I believe this is what's causing the critical failure: 
     [exec] Error: Exception thrown by the agent : java.rmi.server.ExportException: Port already in use: 8099; nested exception is: 
     [exec] 	java.net.BindException: Address already in use (Bind failed)

I've seen this before and I don't think it's related to your pull so I'm retesting it.

@jpince FYI

**Comment by timpak** [comment]
ci:reopen

**Comment by marcellustavares** [comment]
hey @timpak, I think the results are valid for this pull, I've sent another pull request to Brian at https://github.com/brianchandotcom/liferay-portal/pull/56745 and I got different failures.

Will close this one for now. thx

**Comment by yichenroy** [comment]
@timpak 
`java.lang.IllegalStateException: Specified firefox binary location does not exist or is not a real file: /opt/firefox-52.0.2esr/firefox`

Firefox 52 may not have been installed on some of the slaves causing this failure, @kenjiheigel might know more about this issue.

**Pull request closed without merging**
