### PR TITLE
LPS-74362 User menus do not appear to non-admin users on virtual instances before restarting server

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-74362](https://issues.liferay.com/browse/LPS-74362).<br><br>Hey Brian, I still included the changes to build.gradle for the IDE but they are more accurate version numbers this time.<br><br>/cc @pei-jung

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a44423101c...7302810801

**Comment by brianchandotcom** [comment]
@drewbrokke do you have to registerTestPortlet before registerTestPanelApp?

See this:

```
		_registerTestPortlet(_testPortletId);

		long defaultCompanyId = TestPropsValues.getCompanyId();

		Assert.assertFalse(
			_hasMyAccountPermission(defaultCompanyId, _testPortletId));

		long testCompanyId = _testCompany.getCompanyId();

		Assert.assertFalse(
			_hasMyAccountPermission(testCompanyId, _testPortletId));

		_registerTestPanelApp(

```

And my changes in upstream. Thx.

**Comment by brandizzi** [comment]
@drewbrokke  @pei-jung Thank you, people! :clap:

**Pull request closed without merging**
