### PR TITLE
LPS-74289 Uses 'ref' instead of 'key' so that we don't need to use the compatibility mode anymore

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b84975b226...e84541a3f0

**Comment by brianchandotcom** [comment]
@jbalsas should we backport this?

**Comment by brunobasto** [comment]
Hey @brianchandotcom, for what I've talked to @jbalsas, this is not something we should backport cause it will break Image Editor on 7.0.x.

**Comment by jbalsas** [comment]
Hey @brianchandotcom, as @brunobasto mentioned, this removes a compatibility setting we had to prevent breaking changes, so it would potentially break things for customers if backported. It is only meant for future releases.

**Pull request closed without merging**
