### PR TITLE
LPS-64093 SF

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by juangon** [comment]
alee8888 CI logs seems to be SUCCESS right?

**Comment by juangon** [comment]
ooops forget @alee8888 seems a source formatter error. Thanks.

**Comment by rotty3000** [comment]
ci:retest

**Comment by juangon** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
@brianchandotcom  - I re-ran this pull request here:
https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest(master)/1215/

**Comment by brianchandotcom** [comment]
@juangon @rotty3000 there are too many changes going on here to get in for the release.

@juangon can you take the work from Ray and resend it to me in smaller pieces? Most of it just had to do with the naming of things.

getOrder( should never return a list of WebXMLDefintions, if so, it should be getOrdereedWebXMLDefinitions etc.

It's too much for me to do right now. Ray also made some refactor changes, can you take and see what he did and resend those to me a wave at a time that simply moves things around before even sending the logic for this.

Thx.

**Pull request closed without merging**
