### PR TITLE
LPS-64378 build.modules.excludes

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @jorgeFerrer

**Comment by anthony-chu** [comment]
@pyoo47 The test fails to assert a locator is visible, but the screenshot returns a black screen.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2e18480761...88a3fd87a0

**Comment by evannagayama** [comment]
@sharonchoi Microblogs failure. Maybe a locator changed?

**Comment by pyoo47** [comment]
@anthony-chu This sometimes happens because VNC fails in the middle of a run. This has happened a lot less since we started restarting VNC every day as a part of the daily maintenance job but it looks like it still happened here. I'll track down the slave and invoke daily-maintenance against it to try to prevent this from happening again.

**Comment by pyoo47** [comment]
After taking a closer look, I found that the daily maintenance job failed to run for the past 8 days on this slave because the previous job had failed to terminate. I've rectified the situation for now on that slave and I've created a ticket to find a way to prevent this from happening in the future.

**Pull request closed without merging**
