### PR TITLE
Lps 62447

### PR DESCRIPTION
**Pull request by shuyangzhou**
@brianchandotcom the PortletRequestDispatcherImplTest failures are from https://github.com/liferay/liferay-portal/commit/b2f9235a3bd071860b5ed343c3a5824d8308dbd3, it has nothing to do with @Preston-Crary 's fix.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
Seems CI no longer does the auto rebase before running tests?

**Comment by brianchandotcom** [comment]
@shuyangzhou weird. I'm just going to trust you and merge this in.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2783cb0069...afb249a998

**Pull request closed without merging**
