### PR TITLE
LPS-201181 fragment video streaming 2

### PR DESCRIPTION
**Pull request by marcogalluzzi**
Follow up from https://github.com/brianchandotcom/liferay-portal/pull/143689

Changes:

* New commit adding WebKeys [a909672](https://github.com/brianchandotcom/liferay-portal/pull/143712/commits/a9096723633d54b6915d5a985a5d33b0d942dacb)

@ambrinchaudhary

### CODE REVIEW

**Comment by marcogalluzzi** [comment]
ci:reopen

**Comment by marcogalluzzi** [comment]
Sending this PR directly to save time with CI (SF test already passed [here](https://github.com/liferay-lima/liferay-portal/pull/4894)). This feature need to be reviewed as demo urgently. Improvements will follow.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0751c78582...ab7855e8ae

**Comment by brianchandotcom** [comment]
@marcogalluzzi @ambrinchaudhary see ab7855e8ae895eb5a882d1218873e5ab75eb8a25

**Pull request closed without merging**
