### PR TITLE
LPS-68814 Add missing test property

### PR DESCRIPTION
**Pull request by Ithildir**
Hi,
Sorry, I didn't know about this property. With this pull, we have a new test batch that tries to run `build-wsdds`.

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:stop

**Comment by Ithildir** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest - Failed due to broken distribution node.

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
