### PR TITLE
LPS-53966 Apply same fix to Journal

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4456caddd9...a808b9cdf4

**Comment by brianchandotcom** [comment]
@westonhancock I decided not to merge this in. Wouldn't it simply be easier to just namespace the cur param with renderResponse.getNamespace()?

**Comment by westonhancock** [comment]
Hey @brianchandotcom,

Namespacing (or giving the cur param any unique name) would not address the issue. This issue exists because there are two paginators that can show up at the same time in the same portlet. What happens as a result if the cur params have the same name is they are both activated by each other since the url that is generated will apply to both paginators. If they have unique names, two urls are generated (one for each paginator) and whatever url is generated second is the page that the user will see (this is always the url that corresponds to the paginator being used at the time). This is a problem because the paginator that is not being used will end up without a cur or delta param in the rendered url and will be reset to the default settings (1st page and 20 items per page) even if the user previously set that paginator to something else. That is why it is necessary get the "Entry" curParam and deltaParam when using the "Folder" paginator and vice versa. 

I hope that helps. If you have any other questions or still want it fixed a different way, just let me know.

**Comment by sergiogonzalez** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/24760

**Pull request closed without merging**
