### PR TITLE
LPS-66381 Update build.gradle files

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@marcellustavares CI is not liking it :(

**Comment by marcellustavares** [comment]
@brianchandotcom @pyoo47 I have no clue what's happening to this pull :(

**Comment by pyoo47** [comment]
@marcellustavares Looks like portal is not starting up at all. All the failures are basically reporting that portal failed to start. Here's what looks like the first error that was thrown during startup.

```
junit] 19:56:28,698 INFO  [Start Level: Equinox Container: 80b3d274-202c-0016-11de-f622f29c880c][BundleStartStopLogger:35] STARTED com.liferay.util.taglib_2.4.0 [1]
    [junit] 19:56:28,719 ERROR [localhost-startStop-1][PortalContextLoaderListener:135] java.lang.NullPointerException
    [junit] java.lang.NullPointerException
    [junit] 	at com.liferay.portal.kernel.servlet.DirectServletRegistryUtil.clearServlets(DirectServletRegistryUtil.java:27)
    [junit] 	at com.liferay.portal.spring.context.PortalContextLoaderListener.contextDestroyed(PortalContextLoaderListener.java:132)
    [junit] 	at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4859)
    [junit] 	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5478)
    [junit] 	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:224)
    [junit] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:159)
    [junit] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
    [junit] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
    [junit] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
    [junit] 	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:585)
    [junit] 	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1794)
    [junit] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    [junit] 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    [junit] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    [junit] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    [junit] 	at java.lang.Thread.run(Thread.java:745)
    [junit] 19:56:28,721 ERROR [localhost-startStop-1][PortalContextLoaderListener:142] java.lang.NullPointerException
```

**Comment by marcellustavares** [comment]
Thank @pyoo47, will try to reproduce this locally.

Regards

**Comment by pyoo47** [comment]
Here's a different error that happened on another node..
```
[exec] 19:54:52,048 INFO  [localhost-startStop-1][BundleStartStopLogger:35] STARTED com.liferay.portal.security.audit.api_2.0.2 [138]
     [exec] 19:54:52,049 WARN  [fileinstall-/opt/dev/projects/github/liferay-portal/bundles/osgi/portal][org_apache_felix_fileinstall:103] Error while starting bundle: file:/opt/dev/projects/github/liferay-portal/bundles/osgi/portal/com.liferay.portal.settings.web.jar 
     [exec] org.osgi.framework.BundleException: Could not resolve module: com.liferay.portal.settings.web [165]_  Unresolved requirement: Require-Capability: osgi.extender; filter:="(&(osgi.extender=jsp.taglib)(uri=http://liferay.com/tld/ddm))"_    -> Provide-Capability: osgi.extender; osgi.extender="jsp.taglib"; uri="http://liferay.com/tld/ddm"; version:Version="2.0.3"_       com.liferay.dynamic.data.mapping.taglib [428]_         Unresolved requirement: Import-Package: com.liferay.dynamic.data.mapping.service.permission; version="[1.0.0,2.0.0)"_           -> Export-Package: com.liferay.dynamic.data.mapping.service.permission; bundle-version="2.1.2"; bundle-symbolic-name="com.liferay.dynamic.data.mapping.service"; version="1.0.0"; uses:="com.liferay.dynamic.data.mapping.model,com.liferay.dynamic.data.mapping.service,com.liferay.dynamic.data.mapping.util,com.liferay.osgi.service.tracker.collections.map,com.liferay.portal.kernel.exception,com.liferay.portal.kernel.security.permission,org.osgi.framework"_              com.liferay.dynamic.data.mapping.service [440]_                Unresolved requirement: Import-Package: com.liferay.dynamic.data.mapping.model; version="[1.2.0,1.3.0)"_ [Sanitized]
     [exec] 	at org.eclipse.osgi.container.Module.start(Module.java:429)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1252)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1224)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:512)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:361)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:313)
     [exec] 19:54:52,048 INFO  [fileinstall-/opt/dev/projects/github/liferay-portal/bundles/osgi/modules][BundleStartStopLogger:35] STARTED com.liferay.bookmarks.api_2.0.2 [208]
     [exec] 19:54:52,050 ERROR [fileinstall-/opt/dev/projects/github/liferay-portal/bundles/osgi/portal][org_apache_felix_fileinstall:112] Exiting the JVM 
     [exec] org.osgi.framework.BundleException: Could not resolve module: com.liferay.portal.settings.web [165]_  Unresolved requirement: Require-Capability: osgi.extender; filter:="(&(osgi.extender=jsp.taglib)(uri=http://liferay.com/tld/ddm))"_    -> Provide-Capability: osgi.extender; osgi.extender="jsp.taglib"; uri="http://liferay.com/tld/ddm"; version:Version="2.0.3"_       com.liferay.dynamic.data.mapping.taglib [428]_         Unresolved requirement: Import-Package: com.liferay.dynamic.data.mapping.service.permission; version="[1.0.0,2.0.0)"_           -> Export-Package: com.liferay.dynamic.data.mapping.service.permission; bundle-version="2.1.2"; bundle-symbolic-name="com.liferay.dynamic.data.mapping.service"; version="1.0.0"; uses:="com.liferay.dynamic.data.mapping.model,com.liferay.dynamic.data.mapping.service,com.liferay.dynamic.data.mapping.util,com.liferay.osgi.service.tracker.collections.map,com.liferay.portal.kernel.exception,com.liferay.portal.kernel.security.permission,org.osgi.framework"_              com.liferay.dynamic.data.mapping.service [440]_                Unresolved requirement: Import-Package: com.liferay.dynamic.data.mapping.model; version="[1.2.0,1.3.0)"_ [Sanitized]
     [exec] 	at org.eclipse.osgi.container.Module.start(Module.java:429)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1252)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1224)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:512)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:361)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:313)
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:237: The following error occurred while executing this line:
```

**Comment by marcellustavares** [comment]
wow that is clear! it seems when I bumped the module the dependents missed it.

Thanks @pyoo47

**Pull request closed without merging**
