### PR TITLE
Lps 73567

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e505b7f63b...2b7e4cba0b

**Comment by brianchandotcom** [comment]
@mtambara @shuyangzhou see 2b7e4cba0b8573aef6edfa168c8526a06253d842

Thx

**Comment by jpince** [comment]
@mtambara @shuyangzhou does this need to be backported?

**Comment by shuyangzhou** [comment]
Yes, it must be.

**Pull request closed without merging**
