### PR TITLE
LPS-70043 SF

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @4lejandrito

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
ci:retest

Jus fixed upstream. Testing again.

**Comment by 4lejandrito** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/47077

**Comment by sergiogonzalez** [comment]
Resent here https://github.com/brianchandotcom/liferay-portal/pull/47077

**Pull request closed without merging**
