### PR TITLE
LPS-66396

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ac1f0c9a90...b19366152d

**Comment by brianchandotcom** [comment]
@Ithildir please send a follow up pull and fix modules/sdk/gradle-plugins-theme-builder/src/gradleTest/smoke/src/main/webapp/fonts/.gitkeep

Thx.

**Comment by Ithildir** [comment]
@codyhoag, can you please review the `CHANGELOG` and `README` in modules/sdk/gradle-plugins-theme-builder? Thank you! 😊

**Pull request closed without merging**
