### PR TITLE
LPS-61443

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/197ef56d0f...0dd50f674b

**Comment by brianchandotcom** [comment]
Very very nice @hhuijser 

Is this smart enough for the module based taglibs too? See *.tld in modules/**/

**Comment by alee8888** [comment]
Looking into the two test failures:
CPPortalSettings#EnterReservedEmailAddress 
CPRolesCPWebcontent#AddStructureSiteRole

**Comment by xbrianlee** [comment]
The two test failures listed above were caused by [LPS-64940](https://issues.liferay.com/browse/LPS-64940). This SPA refresh issue is currently affecting many tests across components (see a list of affected tests [here](https://issues.liferay.com/browse/LRQA-24142)).

**Comment by hhuijser** [comment]
@brianchandotcom 

Yup, it deals with the taglibs in modules as well. Those were the main reason for changing the logic to retrieve from *.tld

**Pull request closed without merging**
