### PR TITLE
LPS-64528 Default to Integer.MAX_VALUE if the property is not set b/c we're using ascending by default

### PR DESCRIPTION
**Pull request by marcellustavares**
cc @leoadb

### CODE REVIEW

**Comment by leoadb** [comment]
@marcellustavares Thanks !!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/365f972c8e...486b3c5a2f

**Comment by brianchandotcom** [comment]
@marcellustavares @leoadb please see my changes in upstream? Thx.

**Comment by marcellustavares** [comment]
thx @brianchandotcom :+1:

**Pull request closed without merging**
