### PR TITLE
Lps 89140

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@Preston-Crary @shuyangzhou we have left over files in

portal-impl/src/com/liferay/portlet/messageboards/dependencies/

Can you guys remove them? Thx.

**Comment by Preston-Crary** [comment]
@brianchandotcom those are still in use.

**Pull request closed without merging**
