### PR TITLE
LPS-62327 build-wsdds

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by epgarcia** [comment]
I think this time the test failures are not related to my changes.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7d524b8d75...47c6eb2500

**Pull request closed without merging**
