### PR TITLE
LPS-69881 Assigning a Parent Organization to a non-immediate child will cause an infinite loop

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-69881](https://issues.liferay.com/browse/LPS-69881).<br><br>/cc @jorgeferrer, @pei-jung, @jonathanmccann, @SpencerWoo

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by pei-jung** [comment]
This fix doesn't look right to me. If parentOrganizationId is not in the organization's tree path, it won't be in the organization's parent tree path since the parent organization's tree path is just the organization's tree path minus the organization.

                 1
                / \
               2   3
                   |
                   4

For example, if we want to avoid circular reference by assigning 4 as the parent of 2, we need to check if 2 is among the parent orgs of 4 with `isParentOrganization(2, 4)`. With the changes here, it will first check if 2 is in the tree path of 4, which is `/1/3/4/`. Then it checks if 2 is in the tree path of `/1/3/` then `/1/`. Then it returns false, which is wrong.

What we should check instead is if the parent of 2 belongs to the parent organizations of 4. The recursive call should be `isParentOrganization(parentOrganizaiton.getParentOrganizationId(), organizationId)`

**Comment by drewbrokke** [comment]
Hey @pei-jung, the way the `isParentOrganization` is being called is by passing the `organizationId` as the _parent_, and the `parentOrganizationId` as the _child_ (see [here](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/service/impl/OrganizationLocalServiceImpl.java#L2263)), essentially swapping them.  

The reason why this code failed in the first place is because the tree path for _any_ organization, no matter the depth, is at most _2 ids_ in length.  We don't record the entire ancestry in the treepath, but instead rely on a series of relationships to paint the full picture, hence the need for recursion.

Because we're testing the main organization as a _potential parent_ of the given parent organization, it needs to remain constant while we test it against all members of the potential parent's ancestry.

In your example above, I think it is correct that the check of `isParentOrganization(2, 4)` would return false, because 2 is not in any way a parent of 4.  The check would return false, the assignment would complete, and the new tree structure would be 1-3-4-2 (1 would no longer be the direct parent of 2, but now an ancestor).

Hope this helps! :)

**Comment by pei-jung** [comment]
Hey @drewbrokke, thanks for the clarification! I see it now. The fix is right.

**Pull request closed without merging**
