### PR TITLE
LPS-56237 Update tests

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Are the entries in

portal-impl/test/unit/com/liferay/portlet/dynamicdatamapping/io/dependencies/ddm-form-json-serializer-test-data.json

sorted in any meaningful fashion? Just curious. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/db96657596...beb538c5a6

**Comment by marcellustavares** [comment]
Not the entries @brianchandotcom, however we're sorting the properties alphabetically.

We're disabling the JSONAssert strict property, so it does not complain about any order.

Regards,

**Pull request closed without merging**
