### PR TITLE
LPS-96415 Increase coverage of Prettier-based formatting and linting

### PR DESCRIPTION
**Pull request by wincent**
The principal change is that we now format `test/**/*.js` as well; previously we only targeted `src/**/*.js`.

Additionally, in the top-level config we had only formatting configured but not linting.

So update liferay-npm-scripts to get the broader globbing and update the top-level config as well.

The three files with my changes are ".prettierrc.js", "npmscripts.config.js", and "package.json" in the top-level "modules/" directory: everything else (apart from the "yarn.lock" update) is Prettier.

### CODE REVIEW

**Comment by wincent** [comment]
The "test:relevant" failure is a known issue, I believe.

**Comment by brianchandotcom** [comment]
@wincent for mass changes like this, feel free to push it directly to upstream (you have write access).

This will prevent others from getting their pulls killed in case of conflicts.

@jbalsas fyi

**Comment by brianchandotcom** [comment]
@wincent minor wordsmith in 18c4ff89efa9ab9dda867d2294269ab12624b7e4

**Comment by wincent** [comment]
> @wincent minor wordsmith in 18c4ff8

Got it. Thank you.

**Comment by wincent** [comment]
@hhuijser: this is probably the last big Prettier diff. I'll tag you on any other tweaks moving forward.

**Pull request closed without merging**
