### PR TITLE
LPS-61111 Unable to delete user from user group

### PR DESCRIPTION
**Pull request by alee8888**

### CODE REVIEW

**Comment by alee8888** [comment]
@brianchandotcom @drewbrokke @xbrianlee 
This combines Drew's commits for LPS-61111 and fixes for the Poshi functional test that broke.

**Comment by brianchiu** [comment]
@alee8888 
That looks like a test fix. Please look into it.

**Comment by kiyoshilee** [comment]
@brianchandotcom the no workspace failure might occur on other pulls as well, but we fixed the slave that was causing it so any pull requests that trigger moving forward should not have that error.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by alee8888** [comment]
Closing this PR and will resubmit. The functional test that failed was an actual failure.

**Comment by alee8888** [comment]
Resent in https://github.com/brianchandotcom/liferay-portal/pull/33408.

**Pull request closed without merging**
