### PR TITLE
LPS-62839 revert optimization since it caused regressions

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
@tina.tian we have had to revert your commit since it caused the product menu not to be recognised as an embedded portlet. That caused the css not to load and breaks most pages. You can read the LPS for more details.

thanks!

**Comment by jpince** [comment]
@juliocamarero I believe [LPS-62776](https://issues.liferay.com/browse/LPS-62776) is supposed to fix this issue, it's currenly waiting for @jonmak08 to review [here](https://github.com/jonmak08/liferay-portal/pull/1459)

**Comment by juliocamarero** [comment]
@jpince thanks a lot for letting us know! I think our pull should be merged first to avoid more people reporting this issue, and then yours should be merged afterwards reverting our commit once Tina has reviewed it.

thanks a lot!

**Comment by jpince** [comment]
@juliocamarero agreed, thank you

**Comment by jonmak08** [comment]
Pull request for fix sent to @brianchandotcom at https://github.com/brianchandotcom/liferay-portal/pull/35509.

**Comment by tinatian** [comment]
@juliocamarero  @jpince @jonmak08  

Sorry guys for the inconvenience, next time I would send a pull request to you to review first.

Tina.

**Comment by brianchandotcom** [comment]
@juliocamarero @tinatian merged in https://github.com/brianchandotcom/liferay-portal/pull/35509 in favor of this pull since it keeps Tina's optimizations.

**Pull request closed without merging**
