### PR TITLE
LPS-79582 Removing pages from different groups

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@shuyangzhou can you take a look at this CI upgrade error? I think it snuck in yesterday. Thx.

@4lejandrito see 028f03e. Also, the proper fix would be to find out which test group is adding stale data, and removing it... right now, you're just hiding the CI problem by making your test more stable (which is good), but you're also not really fixing the root cause which is someone else's (or yours) bad test. The best scenario is to make your test more robust, and fix the leaky data.

**Comment by brianchandotcom** [comment]
@4lejandrito if it can fail in 7.0.x randomly, please backport as well. Thx.

**Comment by shuyangzhou** [comment]
@brianchandotcom see https://github.com/brianchandotcom/liferay-portal/pull/57098

**Comment by 4lejandrito** [comment]
Hi @brianchandotcom,

You are definitely right, this is just a workaround to avoid random failures. Since we couldn't reproduce it locally it is hard to know which test is leaking but we will spend some time on it as soon as we can.

Thanks!

**Pull request closed without merging**
