### PR TITLE
LPS-69269 Register all listeners,servlets and filters even if they are already instantiated

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
Strange.. non of the batches failed.

**Comment by juangon** [comment]
ci:retest

**Comment by juangon** [comment]
@brianchandotcom I made a format-source before sending.

**Comment by juangon** [comment]
ci:reopen

**Comment by juangon** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
