### PR TITLE
LPS-98801

### PR DESCRIPTION
**Pull request by samuelkong**
@arthurchan35

### CODE REVIEW

**Comment by arthurchan35** [comment]
Seems like we have a unrelated SF issue about jackson databind version 2.9.9

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Ah.. that is from master-private. Fixed the databind issue in my origin.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
