### PR TITLE
LPS-79653 Portlet 3.0: Upgrade to the Portlet 3.0.0 API

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@ngriffin7a compile error :(

**Comment by brianchandotcom** [comment]
@ngriffin7a actually, nvm, that's for the master-private stuff... I think this pull will work.

**Comment by ngriffin7a** [comment]
@brianchandotcom Yep, that's master-private. FWIW. I ran `ant all` locally, ran it locally, and set a breakpoint in `NavigationItem.setHref(Object)` and it worked well when trying to write a blog (the blog JSP has a lambda in it that hits the breakpoint)

**Comment by brianchandotcom** [comment]
Great.. thanks @ngriffin7a I'm running "ant all" locally as well and will push it up in a few. Thx @ngriffin7a !

**Comment by ngriffin7a** [comment]
@brianchandotcom Thank you!

**Comment by brianchandotcom** [comment]
@ithildir can you review

9d7b2ce403294425fce09ec09acf849e834e6396

and

045479bf7c32b75c980f772e09a34f0c5bcd3a48

@ngriffin7a please see my tiny changes in upstream. Thx.

**Pull request closed without merging**
