### PR TITLE
LPS-70669 FIX LanguageImpl returns every possible locale for groups in secondary companies, localized_title gets indexed into too many fields

### PR DESCRIPTION
**Pull request by arboliveira**
Authors: @jorgediaz-lr @rodrigopaulino
Reviewer: @arboliveira

https://issues.liferay.com/browse/LPS-70669

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
@arboliveira this has a real Language test error. See logs. Thx.

**Pull request closed without merging**
