### PR TITLE
LPS-62689 Update web content links

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
FriendlyURLServletTest.testGetRedirectWithI18nPath seems to be failing in every pull, not only in this one.

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest after cherry pick commit from Shuyang that fixes the issue

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0f9ef1908e...e079199586

**Comment by brianchandotcom** [comment]
@juliocamarero we lost a lot of translations. I fixed them in e079199586fba1821101e7ffb36738fda5f0ded5

See my hack

```
#!/bin/sh

DESTINATION_DIR=~/dev/projects/github/liferay-portal/portal-impl/src/content
#SOURCE_DIR=~/dev/projects/github/liferay-portal/modules/apps/site/site-admin-web/src/main/resources/content

SOURCE_DIRS=(modules/apps/site/site-memberships-web/src/main/resources/content)

for SOURCE_DIR in ${SOURCE_DIRS[@]}
do
	SOURCE_DIR=~/dev/projects/github/liferay-portal/${SOURCE_DIR}

	for file in ${SOURCE_DIR}/Language_*.properties
	do
		fileName="${file##*/}"

		echo "" >> ${DESTINATION_DIR}/${fileName}

		cat ${DESTINATION_DIR}/${fileName} ${SOURCE_DIR}/${fileName} > ${DESTINATION_DIR}/${fileName}.new

		mv ${DESTINATION_DIR}/${fileName}.new ${DESTINATION_DIR}/${fileName}
	done
done
```

**Pull request closed without merging**
