### PR TITLE
LPS-103658 Delete instance cause portal broken when site team assigned to site

### PR DESCRIPTION
**Pull request by jkappler**
Hey @brianchandotcom, had to catch the exception here, because: company is removed, then the teams are removed, which triggers an update in the group, and then the company is checked for groupKey (and fails). This should be safe, since we are only checking for the group key at that moment. Still, let me know if it would be better to find another solution.

Thanks

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8273a482b0...ee4ecdef77

**Comment by brianchandotcom** [comment]
@JoyceWang08211 fyi, I reverted LRQA-53037 in master and 7.2.x after this pull.

@jkappler  I backported this to 7.2.x

**Comment by JoyceWang08211** [comment]
@jkappler Thanks for the fix.
@brianchandotcom Thanks for the revert.

**Pull request closed without merging**
