### PR TITLE
LPS-148662 Migrate confirm uses cases to use openConfirmModal on JSPs

### PR DESCRIPTION
**Pull request by diegonvs**
**QA Approval**: https://github.com/liferay-frontend/liferay-portal/pull/2576#issuecomment-1233395784
**Reason**: I'm sending it manually because I'm getting many unrelated failures since this PR contains changes around many modules.

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@diegonvs don't we need to namespace this?

git grep "button onClick"

Shows

```
modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/edit_template.jsp:             <aui:button onClick='<%= liferayPortletResponse.getNamespace() + "saveAndContinueTemplate();" %>' value='<%= LanguageUtil.get(resourceBundle, "save-and-continue") %>' />

```

We have many other examples with namespacing.

Please resend.

**Comment by diegonvs** [comment]
> @diegonvs don't we need to namespace this?

You're correct. Changing!

**Comment by diegonvs** [comment]
> You're correct. Changing!

I was revisiting, nope. I took a look inside every case of the `git grep "button onClick"` to see if I missed namespace something, but everything looks ok.

> @diegonvs, don't we need to namespace this?

Also, I would know what you mean by this. Is the openConfirmModal? If you mean this, no, it doesn't make any sense.  

Did you mean https://github.com/diegonvs/liferay-portal/blob/119a666b3995c46142fa629080270388c70318aa/modules/apps/portal-settings/portal-settings-web/src/main/resources/META-INF/resources/configuration/screen/entry.jsp#L60 this use case? If so, I can change.

**Comment by diegonvs** [comment]
Finally, I found three use cases where we need to change. I'll push and run the CI again on liferay-frontend repo.

**Comment by brianchandotcom** [comment]
@diegonvs 

see

```
<aui:button onClick='<%= liferayPortletResponse.getNamespace() + "saveAndContinueTemplate();" %>'
```

See how that method is namespaced? Otherwise, 2 portlets can clobber each other.

**Pull request closed without merging**
