### PR TITLE
LPS-104700 Reactivate the compat-dropdowns layer in the classic and admin themes

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:test:stable

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
rerunning tests

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/96f34f9c35...a7cd1800c7

**Pull request closed without merging**
