### PR TITLE
Lps 75078

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@shuyangzhou backported. Please have someone review that there are no extra ussages in 7.0.x that were not in master. Thx.

**Comment by shuyangzhou** [comment]
@tomwang2011 please make sure 7.0.x's usages are all updated, thanks!

**Comment by tomwang2011** [comment]
@brianchandotcom @shuyangzhou Just confirmed there are no additional usages on 7.0.x and 7.0.x-private for `com.liferay.portal.kernel.executor.PortalExecutorManager`, thanks!

**Pull request closed without merging**
