### PR TITLE
LRQA-17279

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LRQA-17279.

NOTE: I was not sure how we can localize the language key's used in the `index.html` file so I kept them hard coded in the file for now.  The only way I thought of doing it was by using `Liferay.Language.get(...)` and putting the language keys in the `Language.properties` file, but that did not seem ideal either.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by AngeloYoun** [comment]
Hey Brian,

The Poshi Logger runs separately from Liferay so therefore it does not have access to taglibs/language keys. The button label in question also has an icon so users who cannot understand english can still figure out the functionality. (The button pauses and unpauses the test)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1af519a5f0...fc73fffd46

**Comment by brianchandotcom** [comment]
@jonmak08 @AngeloYoun no need to localize. It's just us using it.

Minor change here fc73fffd46943bd17d7b6a663d927931f8f5bfcc

**Pull request closed without merging**
