### PR TITLE
LPS-193991 Add Locked Pages Instance Settings configuration

### PR DESCRIPTION
**Pull request by alessandromalves**
https://liferay.atlassian.net/browse/LPS-193991

cc.: @lfbesada

### CODE REVIEW

**Comment by alessandromalves** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/13378

✔️ ci:test:stable - 30 out of 30 jobs passed
❌ ci:test:relevant - 295 out of 335 jobs passed in 3 hours 53 minutes

**Comment by alessandromalves** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ec435681ed...420e46e0f9

**Comment by brianchandotcom** [comment]
@lfbesada see changes in my origin. Thx.

**Pull request closed without merging**
