### PR TITLE
[TS] LPS-180084 | master

### PR DESCRIPTION
**Pull request by samanzanedo**
@brianchandotcom 
As requested on https://github.com/brianchandotcom/liferay-portal/pull/141322#issuecomment-1736019275 , I refactored the PR. 
Finally I decided to create a new class to implement the particular test method against an Oracle database, instead of adding it in the existing class.

Kind regards

References:
https://liferay.atlassian.net/browse/LPS-180084
https://github.com/brianchandotcom/liferay-portal/pull/141322

### CODE REVIEW

**Comment by samanzanedo** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f2e744b4a7...11252cb4d5

**Comment by brianchandotcom** [comment]
@samanzanedo see 0e90b7b6 and 11252cb4

**Comment by samanzanedo** [comment]
@brianchandotcom 
commit https://github.com/brianchandotcom/liferay-portal/commit/11252cb4d573089d4d188dea09cfb330c6abb8a5 changes comparation order so it is not correct: we must check sqlException1 is 12899 and then sqlException2 is 0001.

**Pull request closed without merging**
