### PR TITLE
LPS-121091 Update bom-all ant task

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@petershin this task is so nice!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3d2962b668...bb9e8649a8

**Comment by brianchandotcom** [comment]
@petershin just a minor SF in bb9e864

**Pull request closed without merging**
