### PR TITLE
LPS-78293 Disabled checkboxes are always interpreted as false by the backend even if checked. Setting the right value via javascript before submitting the form

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@matethurzo failure not related.. merging.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f05097cbc8...a2363f8e03

**Comment by brianchandotcom** [comment]
@rodrigopaulino @matethurzo see a2363f8 thx

**Pull request closed without merging**
