### PR TITLE
LPS-55874 Fixing tests.

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
ci:stop

**Comment by jpince** [comment]
ci:stop

**Comment by jpince** [comment]
@marcellustavares can you please resend? Per BChan, CI is supposed to reject pulls that have additional commits pushed after the initial pull request is created (to prevent untested commits from getting in)

Thanks!

**Comment by jpince** [comment]
ci:close

**Comment by marcellustavares** [comment]
@jpince not sure what happened here. sorry about that

**Comment by jpince** [comment]
@marcellustavares not a problem, thanks!

**Comment by marcellustavares** [comment]
@jpince I think there's a github issue here, I opend this pull today.

**Comment by jpince** [comment]
yes, I saw the same effect on the resend. I asked IT about it, because I don't see this in other people's pulls. You could try rebasing your branch? Else we can wait to see what IT says.

**Comment by marcellustavares** [comment]
thanks @jpince, it's very weird, see https://github.com/brianchandotcom/liferay-portal/pull/47420

every comment I do is from 23 days ago 😨

**Comment by jpince** [comment]
@marcellustavares similar problem here, except i needed to go into the commit view to see it. All your commit dates are showing in the future, which is why our comments appear above the commits
image

**Comment by jpince** [comment]
Reproduced on this pull also https://github.com/brianchandotcom/liferay-portal/pull/47414#commits
image

**Pull request closed without merging**
