### PR TITLE
LPS-69673

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@brianchandotcom 

I didn't apply to modules for now.
Let me know if this looks okay first.
I'll have someone in the LA office work on doing the same for modules.
Running SB or JavadocFormatter in modules pretty tough from China....

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@hhuijser the logic for this is slightly off.

For example, portal-impl's written BND version may be 2.10.0, but that version has not yet been released and may not be released at all.

We may decide to bump it up to 3.0.0 before actually publishing.

So if a deprecated method is included as part of a released version, it would be safe to set the version to the actually released version, which could be 2.9.0, or 2.9.5.

For things that we just add to deprecation, that have not yet been included as part of a release, it would be -NEXT. That would then serve as a placeholder.

Once we publish, Andrea's code would search and replace -NEXT with the actual bundle version at the time of the release.

Please resend? Thanks bro.

**Pull request closed without merging**
