### PR TITLE
LPS-111325 Skip .lfrbuild-releng-ignore projects

### PR DESCRIPTION
**Pull request by petershin**
@CAustin582 @jpince

### CODE REVIEW

**Comment by petershin** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ab382e8a34...9a5998685a

**Comment by brianchandotcom** [comment]
@petershin also, when I run "publish" via

writeArtifactPublishCommands -DwriteArtifactPublishCommands.force=true

I only want it to force "stale". Right now, it's still adding lfreleng-ignore which I still want to continue to ignore. I've been manually removing them every time I need to mass force republish. Make sense? If not, please Slack me.

The reason I ended up publishing those jars accidentally was because I was force publishing everything, and I manually removed "1.0.0". However, this jar was 1.0.o (O, not 0). So my search and replace didn't see it.. so I ended up accidentally releasing it.

Theoretically, this workaround would not even be needed if the force publish script was smart enough to only force "staleness".

**Comment by brianchandotcom** [comment]
@petershin I'm going to revert this commit since the proper fix in the publish script would ensure this scenario never happens again.

@jpince see my comment above as well.

**Comment by jpince** [comment]
@brianchandotcom it's a temporary workaround so we can build the fat jar. This is the easiest way to do it without rebuilding GA3. We'll revert Peter's commit after GA3 is out.

**Comment by brianchandotcom** [comment]
@petershin ok, temporarily merging this in.

Please send me a revert when it's no longer needed.

@jpince fyi

**Pull request closed without merging**
