### PR TITLE
Lps 64551 Part 1(Create PortletURL by Layout rather than plid whenever possible to gain performance)

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7a4009ab80...7a40be2d9a

**Comment by brianchandotcom** [comment]
@tinatian for the next pull, can you use another LPS ticket but link it to this ticket? Thx.

**Comment by brianchandotcom** [comment]
@tinatian I renamed the description of https://issues.liferay.com/browse/LPS-64551 too.

**Comment by tinatian** [comment]
OK, please see https://github.com/brianchandotcom/liferay-portal/pull/41265

**Pull request closed without merging**
