### PR TITLE
LPS-77260 Reuse

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
ci:test

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Tasks portlet wasn't modified in this pull.

**Comment by brianchandotcom** [comment]
This ServiceBuilder error only happens for this pull.. please resend.

**Comment by brianchandotcom** [comment]
Also, the modules-int* errors is coming from the sharepoint-rest fix that I need you to help me frontport to master-private.

**Pull request closed without merging**
