### PR TITLE
LPD-16060: Allow to PATCH Object Entries External Reference Code using REST API

### PR DESCRIPTION
**Pull request by sergiojimcos**
## Motivation
The idea of this PR is to allow users to PATCH Object Entries External Reference Code using REST APIs. This operation is supported for PATCH Object Entries by Id and `External Reference Code`

**What is new?**
- Allow to Patch Object Entries External Reference Codes in `ObjectEntryManager` implementations.
- Add test cases for that.

**Steps to reproduce**
1. Create a Custom Object Entry called Student and publish it
2. Create a Student Object Entry with ERC: `Student1`
3. Execute this query:

```curl
curl -X 'PATCH' \
  'http://localhost:8080/o/c/students/by-external-reference-code/Student1' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -u 'test@liferay.com:test' \
  -d '{
"externalReferenceCode": "NewStudent1"
}'
```

**After PR**
The External Reference Code will be updated with the new one: `NewStudent1`

**Before PR**
The External Reference Code is not being updated.

**JIRA Related Tickets**
https://liferay.atlassian.net/browse/LPD-16060

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:reopen

**Comment by sergiojimcos** [comment]
Forwarding from: https://github.com/liferay-headless/liferay-portal/pull/1859

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3e0e25a4ba...56d2467a9d

**Comment by brianchandotcom** [comment]
@sergiojimcos see 56d2467a9d61dae86d2cd794900269027d9270ab

**Pull request closed without merging**
