### PR TITLE
LPS-92663 More

### PR DESCRIPTION
**Pull request by matethurzo**
@preston-crary this might be interesting. we have a bunch of NPEs when the drafts are being published because there is a delete is happning and the model listeners are being invoked. Seems like a more deep solution would be required.

### CODE REVIEW

**Comment by jpince** [comment]
@brianchiu @kyle-miho POSHI failures

**Comment by kyle-miho** [comment]
Breadcrumb failure seems like a fluke, other issues are unrelated

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5e23fd4f58...6f04299a19

**Comment by brianchandotcom** [comment]
Merged with minor change in upstream

@preston-crary can we fix the generator so we can revert parts of this pull?

**Pull request closed without merging**
