### PR TITLE
Lps 57905

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@brianchandotcom this is the last known real test failure on Sybase.
Right now the only thing that prevents us from turning it on is the random service start/stop and database populating failure, which we are digging into it now. Hopefully we can turn it on soon.

**Comment by brianchandotcom** [comment]
@shuyangzhou for all the log captures in MBMessageServiceTest, if they are Sybase only, it'd be good if there was some way to group it so we'd know. Otherwise, it's hard to make sense of it in the future.

Thx

cc @mtambara

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7c37f02227...774dc2af1b

**Comment by shuyangzhou** [comment]
Sure, @mtambara is on it.

**Pull request closed without merging**
