### PR TITLE
LPS-80410 Drag and drop on site navigation menus

### PR DESCRIPTION
**Pull request by p2kmgcl**
/cc @jkappler
/cc @ealonso

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test

**Comment by jkappler** [comment]
ci:reopen

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
@anthony-chu, would you be so kind as to check if this is our issue? Doesn't seem like it but you never know.

Thanks!

**Comment by jkappler** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
@lanceji92674957 log this one, we will need to take care of this.

**Comment by jkappler** [comment]
Thanks for taking a look at it @jpince!

**Comment by lanceji92674957** [comment]
@shuyangzhou ok, will do when ci is recovered

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:reopen - Sorry.. there's something strange going on here with the SF job. It should be failing out and it should not be autoclosing over an over. I'll be investigating this issue.

**Comment by jkappler** [comment]
Thanks for taking a look at it @pyoo47! This fix is actually quite important for us

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by pyoo47** [comment]
@jkappler @p2kmgcl Seems like the failure is occurring because the branch name contains a "/" character. I need to do more investigation to determine exactly what needs to be done to prevent this in the future. For now, I suggest avoiding the use of "/" characters in branch names.

@brianchandotcom Please consider this pull request as ci:test:sf PASSED. You can see the actual sf test result here: https://github.com/pyoo47/liferay-portal/pull/637

I've created a ticket to fix this issue https://issues.liferay.com/browse/LRQA-40750

**Comment by pyoo47** [comment]
I've sent in a fix for this issue: https://github.com/brianchandotcom/liferay-portal/pull/58339

**Pull request closed without merging**
