### PR TITLE
LPS-74152 As a developer I would like to support scoped configuration without needing to declare a metatype as a factory

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-74152](https://issues.liferay.com/browse/LPS-74152).<br><br>Hey Brian, this pull allows reading configurations that are scoped at different levels per this proposal: https://github.com/drewbrokke/liferay-portal/pull/319.  There will be additional changes that facilitate saving configurations at different scopes, and also a database upgrade for the Configuration table to represent scoping data.  The idea is to support scoping any configuration without requiring that it is declared as a factory metatype.  Please let me know if you have any questions.<br><br>/cc @pei-jung, @jorgeferrer, @stian-sigvartsen

### CODE REVIEW

**Comment by drewbrokke** [comment]
@brianchandotcom I have written tests for these changes as well. They all pass locally but have issues while on CI.  I can send those in a separate pull.

**Comment by drewbrokke** [comment]
ci:test

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Can you resend? PMD failure in your new code.

**Comment by drewbrokke** [comment]
PR resent as: https://github.com/brianchandotcom/liferay-portal/pull/53817

**Pull request closed without merging**
