### PR TITLE
Lps 139131

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cad66c0fae...069b548d60

**Comment by brianchandotcom** [comment]
@izaera here's the integration test! Yeah, it's insane.

**Comment by izaera** [comment]
@brianchandotcom Seen it :sweat_smile:

**Pull request closed without merging**
