### PR TITLE
master-vw-182

### PR DESCRIPTION
**Pull request by vicnate5**
@rafaprax @marcellustavares there was also a Forms regression on this pull due to a jsp change. But I fixed that too

### CODE REVIEW

**Comment by vicnate5** [comment]
Unrelated poshi failure

**Comment by vicnate5** [comment]
@brianchiu,
@sharonchoi says we can remove this test: PGDocumentsandmedia#AddDocument

**Comment by brianchandotcom** [comment]
@vicnate5 can you resend with fixed poshi? Thx.

**Comment by vicnate5** [comment]
Resent
https://github.com/brianchandotcom/liferay-portal/pull/35643

**Pull request closed without merging**
