### PR TITLE
LPS-95924 Use client resource where possible in DocumentResourceTest

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1f51bb5b60...202a2ce955

**Comment by jpince** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@nhpatt can you help me sync headless in master with 7.1.x? I did an rsync and we're a bit behind. I think the best thing to do is to rsync it, commit the generated files, and then manually revert the deltas for now.

@ruben-pulido See b39cf53f31a379346d8a76a9804ee54e19a892eb to 3e9652f003c3186c8828aa814f3422b4a23b5362

I temporarily disabled 2 tests. Can you help me add "addHeader" to the new HttpInvoker?

We used to have

```
		Http.Options options = new Http.Options();

		options.addHeader("Accept", "application/json");
		options.addHeader(
			"Accept-Language", LocaleUtil.toW3cLanguageId(testLocale));
```

I basically need to be able to add headers as well so I can fix StructuredContentResourceTest.java

Thx.

**Comment by nhpatt** [comment]
Will do! :)

**Pull request closed without merging**
