### PR TITLE
LPS-78312

### PR DESCRIPTION
**Pull request by hhuijser**
@lionah @petershin

### CODE REVIEW

**Comment by hhuijser** [comment]
@ealonso, see https://github.com/brianchandotcom/liferay-portal/pull/55735/commits/083d4b8241acd3b30d6b05ffc076a8469a06928d

**Comment by hhuijser** [comment]
ci:test

**Comment by lionah** [comment]
Thanks @hhuijser!

**Comment by kenjiheigel** [comment]
@hhuijser, these types of failures are actually related to a gradle setting. This will actually fail even if you try to compile it locally using _../../../gradlew classes_
```
     [exec] /opt/dev/projects/github/liferay-portal/modules/util/source-formatter/src/main/java/com/liferay/source/formatter/checks/LanguageKeysCheck.java:286: error: method references are not supported in -source 1.7
     [exec] 			for (File subdirectory : directory.listFiles(File::isDirectory)) {
     [exec] 			                                                   ^
     [exec]   (use -source 8 or higher to enable method references)
     [exec] :apps:collaboration:document-library:document-library-api:jar
```
To use JDK8, please add the following properties to modules/util/source-formatter/build.gradle:
```
sourceCompatibility = "1.8"
targetCompatibility = "1.8"
```
Example:
https://github.com/liferay/liferay-portal/blob/master/modules/util/css-builder/build.gradle#L8-L9

Let me know if you have any questions!

**Pull request closed without merging**
