### PR TITLE
LPS-65516

### PR DESCRIPTION
**Pull request by Ithildir**
cc @mhan810

### CODE REVIEW

**Comment by pyoo47** [comment]
restarting this pull to try to rebalance some of the load. ci:stop

**Comment by pyoo47** [comment]
ci:restart

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/821f8039a5...b3f46efc08

**Pull request closed without merging**
