### PR TITLE
LPS-82345 adaptive media changes

### PR DESCRIPTION
**Pull request by javiergamarra**
/cc @dgarciasarai notice the generics!... in the end I removed the method although it could be more readable with lower variables/static imports/other formatting

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/35609191c3...882b65e297

**Comment by brianchandotcom** [comment]
@nhpatt see 7ee9d5c71d5bb372d6eb2f2dcbb9f6c22498122c

**Comment by nhpatt** [comment]
Thanks! I made Sarai change it to adaptiveMedias but I also read that media is a plural by itself (of medium) so I made her change it back :)

**Comment by dgarciasarai** [comment]
Thanks 👍

**Pull request closed without merging**
