### PR TITLE
LPS-54816 Time

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
FYI when this SF failure comes up `Constructor parameter order propsUtil: portal-impl/src/com/liferay/portal/tools/servicebuilder/ServiceBuilder.java` I really don't know how to fix it. I think it's a bug in SF.

**Comment by brianchandotcom** [comment]
Yup, no worries about SF bug. I got it.

**Comment by shuyangzhou** [comment]
This is a valid SF error.

It is because in ServiceBuilder's constructor, you added new parameter permissionModels, but not using it by order as it appears in the parameter list. 

It is an SF enhancement @hhuijser made in 34b22e7e341c232a96a70bec8c5086f10607133d

**Comment by rotty3000** [comment]
The error message is just too obscure to get that information out of it.

**Comment by shuyangzhou** [comment]
haha, all the sf message is "obscure", just you got used to others, but not this one.

**Comment by rotty3000** [comment]
Actually... I'm not sure why these things are not done automatically by a
post commit hook. It's actually super frustrating that this is done by CI
wasting countless hours of our lives.

Why isn't someone writing git commit hooks for this instead of spending
time writing code that checks this in the most inefficient way possible?

**Comment by shuyangzhou** [comment]
SF takes about 1 min to finish.

Are you telling me you want every commit takes 1 min to get in? :)

**Comment by rotty3000** [comment]
Are you telling me that you couldn't figure out how to check only checked
in files?

**Comment by shuyangzhou** [comment]
That is only the simple normal case. Think about the change to sf itself, can you only check the files changed in the current commit?

And sf can only auto fix very limited types of formating issues. People will start to see a lot of committing failures that they don't know how to deal with, like you did not know how to fix this one. And they can not even send a pull to ask for help, as they can not even commit.

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Very nice Ray. Only minor changes in upstream!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e5a327fe56...f8ac947bba

**Pull request closed without merging**
