### PR TITLE
LPS-73023 Deprecate unused methods

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@mbowerman can you resend?

1.) replace( should be REPLACE(. see SQLTransformer. I think it uses the upper case.

2.) Can you add "_supportsUpdateRow" to DB.java? See isSupports*

I'd rather not use an exception to determine it but proactively state it in the specific DB impl.

Thx. @holatuwol @rotty3000 fyi

**Comment by mbowerman** [comment]
@brianchandotcom I can do (1), but I am not sure about (2). Isn't it a driver-specific thing whether or not ResultSet.updateRow is supported, rather than a database-specific thing?

**Comment by mbowerman** [comment]
@brianchandotcom 

Another thought I had regarding _supportsUpdateRow is that we could make it static, so only one exception ever has to be generated if it should be false. However, it is possible for someone to write their own upgrade process that extends BaseUpgradePortletId that interfaces with an external database using a different database driver. So if we make it static, there is a (very small) possibility that the variable will be set to false in a case that it should be set to true. However, this wouldn't cause any functional problems - it just would mean that our performance in this case isn't optimized. What do you think?

**Pull request closed without merging**
