### PR TITLE
LPS-66831 As a Roles Admin user, I would like to see the number of assignees for each role in the role search results

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-66831](https://issues.liferay.com/browse/LPS-66831).<br><br>/cc @pei-jung @jorgeferrer @holatuwol @alee8888

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:retest

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cfeef7cc83...08caed8618

**Pull request closed without merging**
