### PR TITLE
LPS-89889 buildLang

### PR DESCRIPTION
**Pull request by matethurzo**
@brianchandotcom last one for the weekend :)

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test:change-tracking

**Comment by brianchandotcom** [comment]
@matethurzo :)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d9d5c6d569...83f4339024

**Comment by brianchandotcom** [comment]
@matethurzo see changes in upstream. I fixed a few minor things.

**Pull request closed without merging**
