### PR TITLE
[TECHNICAL-SUPPORT] LPS-77964

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@jpince do we know about these functional errors?

**Comment by jpince** [comment]
@brianchandotcom yes, I pushed the fixes in just after this pull started https://github.com/liferay/liferay-portal/compare/627202eb4d952085f7d21b8385ab5bf6955d41cc...f4d70f87598db80ffb1394a3ddb07404bb7902de

**Pull request closed without merging**
