### PR TITLE
LPS-87135 Add styling for navigation arrows

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/29ca0ff99b...3221276896

**Comment by brianchandotcom** [comment]
@jbalsas please backport. Thx.

**Comment by brianchandotcom** [comment]
@jbalsas nvm, this one is just css, I went ahead and did it.

**Comment by jbalsas** [comment]
Thanks @brianchandotcom!

**Pull request closed without merging**
