### PR TITLE
Lps 66013

### PR DESCRIPTION
**Pull request by CAustin582**

### CODE REVIEW

**Comment by CAustin582** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchiu** [comment]
All the tests are failing with this right now:

```
File '${project.dir.unix}/portal-web/test-ignorable-error-lines.xml' does not exist
```

**Comment by michaelhashimoto** [comment]
We need the 'project.dir.unix' property in these lines:
https://github.com/liferay/liferay-portal/blob/master/build-test.xml#L5468-L5480

So we can potentially replace those if we want to get rid of them.

The main reason we used that particular property was because it forced the slashes to always use "/".

So we need a property that still does that replace to be used in the code within 'build-test.xml'

**Comment by brianchandotcom** [comment]
@CAustin582 please resend. See errors. Thx.

**Pull request closed without merging**
