### PR TITLE
LPS-74897 Remove deprecated usages

### PR DESCRIPTION
**Pull request by tomwang2011**
CC @shuyangzhou @Preston-Crary

Hi Brian, here are two remaining deprecated usages that needs to be replaced with the petra version, thanks!

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
Here's a pull to fix the SF failure:
https://github.com/brianchandotcom/liferay-portal/pull/52154

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c85e97bd48...cf3f5ede55

**Comment by brianchandotcom** [comment]
@tomwang2011 done. Please include this in your backport.

**Pull request closed without merging**
