### PR TITLE
LPS-106443 add better support with timezones

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/17d45748ea...65364c457d

**Comment by brianchandotcom** [comment]
Backported all the way to 7.1.x for you.

**Comment by nhpatt** [comment]
Thanks!

**Pull request closed without merging**
