### PR TITLE
LPS-161398 Create editable of type date-time

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-161398

@DiegoHu97 
@ruben-pulido

### CODE REVIEW

**Comment by ozysouza** [comment]
The tests stable and relevant passed but the CI doesn't sent it. I'm sending the PR directly.
See https://github.com/liferay-echo/liferay-portal/pull/9426#issuecomment-1228826502

:heavy_check_mark: ci:test:stable - 25 out of 26 jobs passed
:heavy_check_mark: ci:test:relevant - 114 out of 118 jobs passed in 5 hours 4 minutes

**Comment by ozysouza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/aae06d1502...a331f88edd

**Comment by brianchandotcom** [comment]
@DiegoHu97 see a331f88edda0857aa2525f791f406d8cd86f8b8e

**Pull request closed without merging**
