### PR TITLE
LPS-109642 & LPS-109706 & LPS-109709

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
//cc @ealonso

**Comment by ruben-pulido** [comment]
The baseline error is not related to this PR. It's fixed here: https://github.com/brianchandotcom/liferay-portal/pull/85778

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/730e0015a6...c6a91e29c8

**Comment by brianchandotcom** [comment]
@ruben-pulido can you send a follow up pull and change

"title": "My example1 background image title",

Make it a title? My Examp;le1 Background Image Title

Thx

**Comment by ruben-pulido** [comment]
Follow PR sent here: https://github.com/brianchandotcom/liferay-portal/pull/85788

**Pull request closed without merging**
