### PR TITLE
LPS-89415 Add missing media type check

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8b76c63232...1ef9156d35

**Comment by brianchandotcom** [comment]
@nhpatt I'm generating a lot more test methods whenever we have a POST /site/{siteId}/something

Our manual tests are smaller now:

4ab3a91bfb1c8ade7ea1a3d50ebff45eb12bfae9 and f011f9dc2c54a4df151f2d5b44838a1ed78a912b

See my regen at 1ef9156d35e2eae0371acceee4f0725343f8074d

I haven't applied them everywhere yet. On my todo.. but if you guys could take a look at tests for me, that would be nice. basically, if tests have siteId in them, then it's probably not needed.

**Comment by nhpatt** [comment]
@brianchandotcom we'll do it right now :)

**Comment by victorg1991** [comment]
@brianchandotcom I've started to migrate these, but some of the generated code are wrong

For example in KnowledgeBaseArticleResourceTest

We have overriden the `testPostKnowledgeBaseArticleKnowledgeBaseArticle_addKnowledgeBaseArticle` to create a KBArticle as a child of a KBArticle, like this:

```
@Override
	protected KnowledgeBaseArticle
			testPostKnowledgeBaseArticleKnowledgeBaseArticle_addKnowledgeBaseArticle(
				KnowledgeBaseArticle knowledgeBaseArticle)
		throws Exception {

		return invokePostKnowledgeBaseArticleKnowledgeBaseArticle(
			testGetKnowledgeBaseArticleKnowledgeBaseArticlesPage_getParentKnowledgeBaseArticleId(),
			knowledgeBaseArticle);
	}
```

But the generator is generating the following (note that is creating a KBArticle not as a child but directly in the site):

```
protected KnowledgeBaseArticle
			testPostKnowledgeBaseArticleKnowledgeBaseArticle_addKnowledgeBaseArticle(
				KnowledgeBaseArticle knowledgeBaseArticle)
		throws Exception {

		return invokePostSiteKnowledgeBaseArticle(
			testGroup.getGroupId(), knowledgeBaseArticle);
	}
```
@petershin

**Comment by petershin** [comment]
Sent patch to Brian: https://github.com/brianchandotcom/liferay-portal/pull/71361

**Comment by petershin** [comment]
Sent patch to Brian: https://github.com/brianchandotcom/liferay-portal/pull/71361

**Pull request closed without merging**
