### PR TITLE
LPS-171665 Import the Thumbnail when importing Utility Pages

### PR DESCRIPTION
**Pull request by liulukiwi**
This is only for master.

https://issues.liferay.com/browse/LPS-171665

@lfbesada

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:reopen

**Comment by liulukiwi** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/10695

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f999d9239c...7dd3e9eacb

**Comment by brianchandotcom** [comment]
@lfbesada see 7dd3e9eacb94a06c4a2cf77396f73e643e2526b4

I found 

```
	private long _getPreviewFileEntryId(
			String className, long groupId, long classPK, ZipEntry zipEntry,
			ZipFile zipFile)
		throws Exception {
```

strange so I changed it in 7dd3e9eacb94a06c4a2cf77396f73e643e2526b4 to match 

```
		fileEntry = _portletFileRepository.addPortletFileEntry(
			groupId, serviceContext.getUserId(), className, classPK,
			LayoutAdminPortletKeys.GROUP_PAGES, repository.getDlFolderId(),
			bytes, imageFileName, MimeTypesUtil.getContentType(imageFileName),
			false);

```

**Pull request closed without merging**
