### PR TITLE
LPS-102211 Fix appDeployment update

### PR DESCRIPTION
**Pull request by brunofarache**

### CODE REVIEW

**Comment by brunofarache** [comment]
cc @jeyvison @gabrielwas

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9c1dfd722d...f4a7681135

**Comment by jpince** [comment]
@brunofarache is this int test failure related?
`AppResourceTest.testPutApp`
```
java.lang.AssertionError: Thread Thread[http-nio-8080-exec-10,5,main] caught concurrent failure: java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.portal.vulcan.internal.jaxrs.exception.mapper.ExceptionMapper, message=java.lang.NullPointerException
java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.portal.vulcan.internal.jaxrs.exception.mapper.ExceptionMapper, message=java.lang.NullPointerException
```

**Comment by brunofarache** [comment]
@jpince probably yes, thanks for catching, will send a fix.

**Comment by brunofarache** [comment]
@jpince fixed at: https://github.com/brianchandotcom/liferay-portal/pull/78825

**Pull request closed without merging**
