### PR TITLE
LPS-99657

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@brianchandotcom @austinchiang
Pretty sure the failure is caused by these two

**Comment by hhuijser** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@hhuijser please resend, do I still need this? See fix by @csierra in
d7958a13acfab76968749129f7099150a91d7afb

@austinchiang fyi

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/479600eade...106497fe00

**Comment by brianchandotcom** [comment]
@hhuijser fyi, I did not merge this.

**Comment by hhuijser** [comment]
@austinchiang, can you check if failures have been resolved with @scierra's fix?

**Comment by austinchiang** [comment]
Yup @hhuijser I'll check it out

**Comment by austinchiang** [comment]
This fix resolved the issues.

**Pull request closed without merging**
