### PR TITLE
Lps 81018

### PR DESCRIPTION
**Pull request by shuyangzhou**
@Ithildir please help us to cache 
```
compileOnly group: "p2", name: "org.eclipse.equinox.http.servlet", version: "1.5.0.v20180501-1936"
```
on our servers, thanks!
@rotty3000 see my changes at https://github.com/brianchandotcom/liferay-portal/commit/d297e03d2803f917d2456f67622b739073dda43b, the other 2 commits are just SF, no logic change.

@dantewang @slnn I think you guys have previously verified the performance for this jar upgrade, right? Please double check whether the current version is the same you verified against, if not, please do it again.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by Ithildir** [comment]
@shuyangzhou, done: https://repository.liferay.com/nexus/content/groups/public/com/liferay/org.eclipse.equinox.http.servlet/1.5.0.v20180501-1936-LIFERAY-CACHED/

**Comment by shuyangzhou** [comment]
Thanks @Ithildir !

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@michaelhashimoto ci relevant is still picking up the wrong test classes to run.

**Comment by slnn** [comment]
Hi @shuyangzhou,
We have verified the jar upgrade in LPS-69930, but the version is not same as the current version, will check it.

Lily

**Comment by rotty3000** [comment]
The version is not the same but only because of the eclipse release
process, if you diff the jars you will find no (or irrelevant) source
changes.

**Comment by brianchandotcom** [comment]
@shuyangzhou I used the cached jar now in 5bc0a7d

Thanks @Ithildir and @rotty3000

**Comment by slnn** [comment]
Hi @shuyangzhou 

Here are test results on Login

Portal Version | Git Id | Session Count | Mean Time of Login
-- | -- | -- | --
Before-LPS-81018 | ea4f668 | 50295 | 279
On-LPS-81018 | 5bc0a7d | 49964 | 289

Lily

**Comment by michaelhashimoto** [comment]
@shuyangzhou - We are looking into the ignore list still, sorry for the delays.  Here's the ticket for this fix:
https://issues.liferay.com/browse/LRQA-40951

**Pull request closed without merging**
