### PR TITLE
LPS-157215

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Manually forwarding because the [failures](https://github.com/rodrigopaulino/liferay-portal/pull/83#issuecomment-1250362273) pointed by CI are unrelated

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/312f1ff504...f0ba4e32de

**Comment by brianchandotcom** [comment]
@rebsilva why are we setting

```
		newObjectField.setExternalReferenceCode(externalReferenceCode);
		newObjectField.setLabelMap(labelMap, LocaleUtil.getSiteDefault());

```

twice?

@rodrigopaulino please resend.

not merged

**Comment by rodrigopaulino** [comment]
This is probably a rebase error, @brianchandotcom. I'll resend.

**Comment by rodrigopaulino** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/123326

**Pull request closed without merging**
