### PR TITLE
LPS-76045 Avoid failing tests for other classes does not have implementation for these yet

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test

**Comment by matethurzo** [comment]
@brianchandotcom @jpince APIO seems to trigger auto close, it's not in the allowed list

**Comment by jpince** [comment]
@stsquared99 can you please add the APIO project to the allowed list? 

https://issues.liferay.com/secure/RapidBoard.jspa?rapidView=2795&projectKey=APIO

**Comment by jpince** [comment]
ci:reopen

**Comment by matethurzo** [comment]
@jpince thanks! i've re-sent the code already

**Comment by jpince** [comment]
@matethurzo haha yes, I figured that was the case. I think the allowed
projects is determined on the IT side (CI bot), so that's why I asked Sam
to look into it.

**Comment by stsquared99** [comment]
@jpince This isn't the CI bot, it's just reading the list of allowed projects from central.

**Comment by jpince** [comment]
@stsquared thanks, I'll send a pull to BChan for this change in
[ci.properties](
https://github.com/liferay/liferay-portal/blob/master/ci.properties)

**Pull request closed without merging**
