### PR TITLE
LRCI-940 Don't fail out for SQL2555I when importing older DB2 databases

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRCI-940

### CODE REVIEW

**Comment by kenjiheigel** [comment]
Backports:
https://github.com/brianchandotcom/liferay-portal-ee/pull/28635 (7.2.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/28636 (7.1.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/28637 (7.0.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/28638 (ee-6.2.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/28639 (ee-6.2.10)
https://github.com/brianchandotcom/liferay-portal-ee/pull/28640 (ee-6.1.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/28641 (ee-6.1.30)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c6e2514fb2...5a20e88abe

**Comment by brianchandotcom** [comment]
@kenjiheigel see 5ec67818b60f62ce06e7ff9ce9b3a53b8462df32

**Comment by brianchandotcom** [comment]
Sorry @kenjiheigel see this link instead 5ec67818b60f62ce06e7ff9ce9b3a53b8462df32

**Pull request closed without merging**
