### PR TITLE
LPS-57952 show labels for asset metadata

### PR DESCRIPTION
**Pull request by juliocamarero**
assetp 1

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @natecavanaugh could you please have a look at the css changes? thank you!

**Comment by juliocamarero** [comment]
assetp 1

**Comment by brianchandotcom** [comment]
THis pull is good. I'll merge it in. No need to retest.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/10f6a64208...ccad33e5ff

**Pull request closed without merging**
