### PR TITLE
Lps 71863

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Group group = layout.getGroup(); 

has a potential NPE in 

public String getLayoutFriendlyURL(Layout layout) {

also, can you backport? Since 

Group group = layout.getGroup(); 

throws an exception in 7.0.x

Merged. Thx.

**Comment by brianchandotcom** [comment]
@Preston-Crary fyi, I did a partial backport so I could release portal-kernel soon. Please backport the rest. Thx. See comment above.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/4108

**Comment by Preston-Crary** [comment]
Backport https://github.com/dustinryerson/liferay-portal-ee/pull/2805

**Pull request closed without merging**
