### PR TITLE
Custom SQL Queries per database

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/759ef45d78...2c6df3f61a

**Comment by brianchandotcom** [comment]
@migue @marianoalvarosaiz I renamed a bunch of classes. Please see upstream. Thx!

**Pull request closed without merging**
