### PR TITLE
LPS-137441 - Icon Provisioning

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Hey @brianchandotcom, I applied the TODO comments you noted. Thanks for the feedback and let me know if you see anything else that I missed. I think I am slowly starting to recognize the patterns you are pointing out.

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ffb0a4742e...3c4448c77e

**Comment by brianchandotcom** [comment]
@bryceosterhaus can you review a4d12075 not sure if that is right. See also my other changes in my origin. Thx.

**Comment by bryceosterhaus** [comment]
@brianchandotcom yeah those all look great. Thanks!

**Pull request closed without merging**
