### PR TITLE
LPS-102633 Escapes title within ariaLabel to prevent XSS

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
@john-co, can you confirm if these failures are related?

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

Details:
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=830026735&testrayRunIdA=830023729&statusB=2

- ContentPages are most likely associated with https://issues.liferay.com/browse/LPS-103210
- Smoke test looks like a fluke

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5d268c81c9...e198c4ae88

**Pull request closed without merging**
