### PR TITLE
LPS-87669

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b45ed84a14...16dfeddb12

**Comment by brianchandotcom** [comment]
@topolik @Preston-Crary I made some more changes in 16dfeddb129a751bf961724258ff83dcdc5718ef

**Comment by brianchandotcom** [comment]
@topolik please backport. Thx.

**Comment by topolik** [comment]
Thanks guys!

**Pull request closed without merging**
