### PR TITLE
LPS-63190 rename language key

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b6cfa23409...e3415a3fc6

**Comment by brianchandotcom** [comment]
@pyoo47 @Ithildir what happened to Julio's pull? I merged this in because I don't see how his changes could have caused this Node issue. Is it a Gradle or CI env random issue?

Thx.

**Comment by juliocamarero** [comment]
@brianchandotcom @pyoo47 @Ithildir it was because I hadn't included the autogenerated files from the themes. Once those are updated the pull passes.. sorry I forgot to update the pull. Here is the missing commit: https://github.com/brianchandotcom/liferay-portal/pull/36590

thanks Brian!

**Comment by Ithildir** [comment]
Hi @juliocamarero! I already pushed the task cache upstream: https://github.com/liferay/liferay-portal/commit/8fde92e9065329ae091993c9a3456b942ae0bbfe

**Comment by juliocamarero** [comment]
Thanks a lot @Ithildir !! :+1:

**Pull request closed without merging**
