### PR TITLE
LRQA-67407 Increase version in app.properties

### PR DESCRIPTION
**Pull request by carolmoreschi**

### CODE REVIEW

**Comment by jpince** [comment]
@carolmoreschi thank you!

**Comment by jpince** [comment]
@carolmoreschi is there a reason why your username isn't attached to the commit? maybe check your .git/config file and make sure your Git username is there?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/887e9bc5af...6ee5a0e9eb

**Comment by brianchandotcom** [comment]
@carolmoreschi I manualy applied the changes you wanted in this commit via 5ed564fae8bedc72e7b509ac1007a3de5a570562

I did that because I had to do a revert in eca94a3d26bbfcfb0ace87599279cf465f75f34d

**Pull request closed without merging**
