### PR TITLE
LPS-172881 search-experiences-service: Fix keywords clean-up

### PR DESCRIPTION
**Pull request by joshchong**
Covers:

https://issues.liferay.com/browse/LPS-172881
https://issues.liferay.com/browse/LPS-173239

Tested in: https://github.com/liferay-search/liferay-portal/pull/743
Failures are unrelated

### CODE REVIEW

**Comment by joshchong** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/01bc8c03fb...39523f32b3

**Comment by brianchandotcom** [comment]
@peerkar can we add a test for this?

And if order matters, please add a line break

For example, Sublime sort changes

```

		keywords = keywords.replaceAll("\\\\", "&#92;");
		keywords = keywords.replaceAll("/", "&#8725;");
		keywords = keywords.replaceAll("\"", "\\\\\"");
		keywords = keywords.replaceAll("\\[", "&#91;");
		keywords = keywords.replaceAll("\\]", "&#93;");
		keywords = keywords.replaceAll("\\$", "&#36;");
```

to

```
		keywords = keywords.replaceAll("/", "&#8725;");
		keywords = keywords.replaceAll("\"", "\\\\\"");
		keywords = keywords.replaceAll("\\$", "&#36;");
		keywords = keywords.replaceAll("\\[", "&#91;");
		keywords = keywords.replaceAll("\\\\", "&#92;");
		keywords = keywords.replaceAll("\\]", "&#93;");
```

Can I make that change? I assume no. If not, and order matters, add line breaks.

**Comment by peerkar** [comment]
@brianchandotcom I'll send a follow up with a test and an order change

**Pull request closed without merging**
