### PR TITLE
LPS-82420 Auto SF

### PR DESCRIPTION
**Pull request by petershin**
@jpince

### CODE REVIEW

**Comment by jpince** [comment]
@petershin thanks!

**Comment by petershin** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@petershin I reverted e4082d0d997e641db592b1aeb5553e701b81521a and reverted your suppression. I have no idea why it keeps making the packageinfo. Can you find out why? I didn't do it on purpose. It was a script that did it. Either SF or the baseline task. Talk to @ithildir about it. Thx.

**Pull request closed without merging**
