### PR TITLE
LPS-72525

### PR DESCRIPTION
**Pull request by matethurzo**
@brianchandotcom this is a bigger bugfix we didn't want to risk in the release

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test:relevant

**Comment by matethurzo** [comment]
@brianchandotcom the test failures seem unrelated

**Comment by jpince** [comment]
@vicnate5 do you have time to fix these tests? else, maybe exclude from https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/test.properties#L19 for now?

**Comment by vicnate5** [comment]
Test failures are unrelated, due to another bug. However, our team wants to leave the tests turned on.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5f12fac84f...46fcbfded6

**Comment by brianchandotcom** [comment]
@matethurzo can you resend on top of https://github.com/matethurzo/liferay-portal/pull/2217

The LPS ticket said this is already all the way back in 7.0.x which will make things hard for support if you reuse this LPS ticket.

Please resend with a new ticket.

**Pull request closed without merging**
