### PR TITLE
LPS-63680 Source Formatting

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
Why are all my builds being aborted!!!

**Comment by brianchandotcom** [comment]
@rotty3000 I'm checking with Sam Tran right now,  we found that some of storage on GH was very slow (and you may be one one of those nodes).

**Comment by michaelhashimoto** [comment]
ci:retest

This one failed due to a Jenkins bug.  We can retest this one, it should be okay in the next run.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/70a5e8840c...3ac07669cf

**Pull request closed without merging**
