### PR TITLE
master-en-279

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LPS-60764

### CODE REVIEW

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@evannagayama what's up with the random poshi errors? We should fix those. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/29bd13edb7...ceaaaad3b7

**Comment by evannagayama** [comment]
@brianchandotcom I'm not sure.. We are randomly getting fluke failures. I'll try to look into it more and let qa engineering know.

**Pull request closed without merging**
