### PR TITLE
LPS-66094 Add upgrade properties for supported paths - 6.0.12 and 6.2.10

### PR DESCRIPTION
**Pull request by achaparro**
Hi @brianchandotcom,

We need to include this for DXP release, approved by @miguel

Thanks!

### CODE REVIEW

**Comment by achaparro** [comment]
ci:restart

**Comment by vicnate5** [comment]
I have tested this pull and am able to upgrade to master from 6.0, 6.1, and 6.2 without issue. Please merge as it will improve our customer's experience upgrading to 7.0.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by achaparro** [comment]
Thanks @brianchandotcom and @vicnate5!

**Pull request closed without merging**
