### PR TITLE
LPS-169605 Set notification configuration

### PR DESCRIPTION
**Pull request by murilostodolni**
Errors in https://github.com/liferay-objects/liferay-portal/pull/1644#issuecomment-1398784277 are not related.

### CODE REVIEW

**Comment by murilostodolni** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@murilostodolni rebase error, please resend.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ca6b1cc5c3...5ea0af162a

**Comment by brianchandotcom** [comment]
@murilostodolni Nvm, I rebased it. See changes in my origin. Thx.

**Comment by murilostodolni** [comment]
Thank you @brianchandotcom

**Pull request closed without merging**
