### PR TITLE
Revert "portal-lpkg-deployer 2.0.20 apply"

### PR DESCRIPTION
**Pull request by mtambara**
This reverts commit 5484d678e06f3820e8886006d753e7c5aea287bf.

The test needs to have a project dependency because it is bnd including an internal class from portal-lpkg-deployer. Without this the test will not be able to compile.

@shuyangzhou

### CODE REVIEW

**Comment by mtambara** [comment]
ci:reopen

**Comment by mtambara** [comment]
ci:retest

**Comment by mtambara** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/51187

**Comment by brianchandotcom** [comment]
Thx.. merged.

**Pull request closed without merging**
