### PR TITLE
Lps 76527

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by tomwang2011** [comment]
ci:test

**Comment by tomwang2011** [comment]
ci:retest

**Comment by tomwang2011** [comment]
ci:reopen the FileImplExtractTest failure should be fixed by https://github.com/brianchandotcom/liferay-portal/pull/53756

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7705bf341f...4e1f8fe97f

**Pull request closed without merging**
