### PR TITLE
LPS-74831 SF

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@juliocamarero fyi

AnalyticsClientTest.testAnalyticsEventCreation is failing randomly

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/66465b15d5...4d9d665558

**Comment by brianchandotcom** [comment]
@jbalsas see 4d9d665558fdcd92044a4b911c5b18bac5a7d210

**Comment by juliocamarero** [comment]
@brianchandotcom I know why, LCS gateway was down every time it failed. We will change the test to avoid the dependency on a remote server. cc @epgarcia

thanks!

**Pull request closed without merging**
