### PR TITLE
LPS-67115 SF

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @robertoDiaz @stian-sigvartsen

**Comment by jpince** [comment]
poshi failure unrelated, being investigated under [LRQA-27384](https://issues.liferay.com/browse/LRQA-27384)

**Comment by brianchandotcom** [comment]
@sergiogonzalez @robertoDiaz @stian-sigvartsen please see my changes in upstream. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/dae2acad9e...48c48a1e5c

**Pull request closed without merging**
