### PR TITLE
LPS-77875

### PR DESCRIPTION
**Pull request by petershin**
Sent pulls to update `liferay-plugins` and `liferay-plugins-ee`:

https://github.com/brianchandotcom/liferay-plugins/pull/5422
https://github.com/brianchandotcom/liferay-plugins-ee/pull/23122

@Ithildir

### CODE REVIEW

**Comment by petershin** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by petershin** [comment]
Followed up w William Forsyth and Jeff Handa.  They were ok with using the non *-cdn url

Will cherry-pick the relevant commits here and send it in one new pull

**Comment by petershin** [comment]
The url below works differently, so will wait for William to remove the redirect before resending this pull

https://releases.liferay.com/portal/7.0.4-ga5/liferay-ce-portal-tomcat-7.0-ga5-20171018150113838.zip

**Comment by petershin** [comment]
@brianchandotcom - Will send a pull to update the cdn urls tomorrow morning

William is planning on removing the SourceForge redirects tomorrow morning ~7am

**Pull request closed without merging**
