### PR TITLE
Lps 164521 74x 3

### PR DESCRIPTION
**Pull request by javalosjr96**
Previous PR to master:
https://github.com/brianchandotcom/liferay-portal/pull/128088

Notes from Alvaro:

> 
> Previous pr with the changes - https://github.com/liferay-appsec/liferay-portal/pull/945
> 
> Changes to reduce the size of the index. They were too big and were throwing errors in Oracle.
> 
> Changes
> As discussed Uniform team and AppSec team in the pr https://github.com/liferay-appsec/liferay-portal/pull/865, we have made the changes to reduce the size of the SamlPeerBinding table indexes:
> 
> IX_E642E1AE
> IX_81ACF542
> IX_BC82BDFC
> Steps performed:
> 
> delete index - (index.sql)
> modify finder (service.xml)
> create custom finder to filter by fields removed from index - (SamlPeerBindingFinderImpl.java)
> make changes to the calls in the portal (*LocalServiceImpl.java)
> These steps have been applied for finders (service.xml):
> 
> C_D_SNIF_SNINQ_SNIV_SPEI
> C_U_D_SNIF_SNINQ_SPEI
> The removal of the indexes has been included as part of the upgrade process, and before altering the field size.
> 
> Test
> manually tested. For the configuration the [documentation](https://liferay.atlassian.net/wiki/spaces/ENGAPPSECURITY/pages/1591215588/Collection+of+common+test+setups+for+Application+Security#SAML%5BhardBreak%5D) has been used. Entries have also been added in the database table (SamlPeerBinding) with different values to ensure that the desired values are returned
> Running SamlPeerBindingPersistenceTest

Liferay Uniform PR Review:
https://github.com/liferay-uniform/liferay-portal/pull/887

Changes Made:
Removed FinderImpl from previous PR and moved logic to SamlPeerBindingLocalServiceImpl

### CODE REVIEW

**Comment by javalosjr96** [comment]
ci:reopen

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:reopen

**Comment by javalosjr96** [comment]
@brianchandotcom 
Hey Brian,
can you check this out?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9c2de4f56c...9130ef197f

**Comment by brianchandotcom** [comment]
Merged to U58 as well. @javalosjr96 see changes in my origin.

**Pull request closed without merging**
