### PR TITLE
LPS-66503 Rename before.upgrade to before.lpkg.upgrade

### PR DESCRIPTION
**Pull request by shuyangzhou**
Let me know if this is not good enough.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@shuyangzhou lpkg startup still breaking. fyi. Thx.

**Comment by shuyangzhou** [comment]
@brianchandotcom it is not the test failing, but the lpkg creation logic is broken.

```
move-artifact:
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:237: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:777: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/modules/build-app.xml:66: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/modules/build-app.xml:68: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/modules/build-app.xml:169: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/modules/build-app-module.xml:267: Warning: Could not find file /opt/dev/projects/github/liferay-portal/bundles/osgi/portal/com.liferay.portal.dao.db.jar to copy.
      [get] Getting: http://test-1-1/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/11709//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20160613142946340.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20160613142946340.txt
```

@Ithildir any update on the fix? This is the same issue I showed you in the morning.

**Comment by Ithildir** [comment]
I think it has been fixed by https://github.com/brianchandotcom/liferay-portal/pull/40749.

**Comment by shuyangzhou** [comment]
Great! Thanks @Ithildir!
@brianchandotcom https://github.com/brianchandotcom/liferay-portal/pull/40749 is clean on lpkg test. We should be good now.

**Pull request closed without merging**
