### PR TITLE
LPS-74161 Invoke normalizer on each try

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @adolfopa

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7e29cbb217...8d349a8e17

**Pull request closed without merging**
