### PR TITLE
LPS-90548 Add defaultSegmentId when SEGMENTS_SEGMENTATION_ENABLED is not true

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso, @epgarcia, @darquesdev, @brianchiu

**Comment by epgarcia** [comment]
@brianchandotcom I'm working on a follow-up PR to make segmentation enabled by default and also define it as an application property rather than a portal property. Please review and merge this changes first, and then I'll send mine on a separate LPS and rebased to master.

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fd70c211ab...92f47d260e

**Pull request closed without merging**
