### PR TITLE
LPS-76576 Injects default tiles

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:reopen

**Comment by jbalsas** [comment]
/cc @hhuijser

I guess it's because the `APIO-` commits replace `VULCAN-`, but those are in upstream master... 🤷‍♂️

**Comment by brianchandotcom** [comment]
@jbalsas it's cause it's not in my origin.. we're fixing the check so it won't happen in the future.. merging.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c925f6ddf3...3d79a8ad8e

**Pull request closed without merging**
