### PR TITLE
LPS-69271

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@shuyangzhou, see https://github.com/brianchandotcom/liferay-portal/pull/44908/commits/c29c6cac24b6f691b570165ebf249217d65ee67b

**Comment by hhuijser** [comment]
ci:reopen

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by hhuijser** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@hhuijser Can you fix some of the auto SF in ee-7.0.x? I ported what I could. Thx.

**Pull request closed without merging**
