### PR TITLE
LPS-64034 avoid duplicate groups

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by sharonchoi** [comment]
@evannagayama Poshi failure at `<executemacro="AssetPublisherPortlet#configureAddSiteScopes"> `

**Comment by brianchandotcom** [comment]
@evannagayama  please resend with a fix for poshi?

@juliocamarero fyi

**Comment by evannagayama** [comment]
Looking into this issue right now. Thanks!

**Comment by juliocamarero** [comment]
https://github.com/evannagayama/liferay-portal/pull/663

**Pull request closed without merging**
