### PR TITLE
LPS-115798 Renames module as portal-user-locale-options-web

### PR DESCRIPTION
**Pull request by jbalsas**
From https://github.com/brianchandotcom/liferay-portal/pull/90575#event-3478672922, renamed module to `portal/portal-user-locale-options-web`.

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:reopen

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:reopen

**Comment by john-co** [comment]
Validated the fix locally by fetching this PR - it works
Fixes: https://issues.liferay.com/browse/LPS-115890 and https://issues.liferay.com/browse/LPS-115798

cc/ @zhangyan0701 , please validate and close out tickets when this syncs to upstream.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/495e78d383...1e2f5fddd0

**Pull request closed without merging**
