### PR TITLE
LPS-142948 Round #2: Update SF rules and enforce `enabled = false` on @Components

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-142948

Thanks, Brian!

/cc shout-out to @tinatian :+1: 

/cc @BryanEngler @arboliveira @peerkar @gustavolimav @joshuacords @wcao20170619 Fyi.

### CODE REVIEW

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
Running SF here: https://github.com/liferay-search/liferay-portal/pull/236
Passed locally. :white_check_mark:

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/56d45cd518...cc7b569b31

**Pull request closed without merging**
