### PR TITLE
LPS-105851 Implements react editor render

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @brookedalton,

Could you please take a look at LocalFile.WidgetPages#DeleteSitePages? I think it is not related with this pull.

Regards,
Eudaldo.

**Comment by brookedalton** [comment]
ci:test:relevant

**Comment by brookedalton** [comment]
Hey @ealonso you are right - there have been some issues with the poshi sign in macro that are being investigated https://issues.liferay.com/browse/LRQA-54483

**Comment by brianchandotcom** [comment]
@ealonso can you resend, I think both can be *TypeConstants

LayoutConverterTypeConstants vs. LayoutDataItemTypesConstants

**Pull request closed without merging**
