### PR TITLE
LPS-60823 Adapt horizontal card to lexicon markup

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @sharonchoi,

Could please take a look to this poshi error?

Thanks you very much!!!

**Comment by sharonchoi** [comment]
Hey @ealonso, let me fetch your branch and see, it seems like it's not recognizing the html element of the checkbox, with the new horizontal card layout.

**Comment by sharonchoi** [comment]
Hey @ealonso, I just pushed in a test fix on top of your commits here: https://github.com/brianchandotcom/liferay-portal/pull/32757

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/32757

**Pull request closed without merging**
