### PR TITLE
LRQA-40314 | master

### PR DESCRIPTION
**Pull request by Sharryxue**
https://issues.liferay.com/browse/LRQA-40314

/cc @xbrianlee

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
fyi your pull here https://github.com/brianchandotcom/liferay-portal-ee/pull/22247 has 2 tickets..

**Comment by brianchandotcom** [comment]
@Sharryxue I front ported 9f4ea4e3a2080e6db3479957c0b99e15ca9e55bd because it looked like it was a mistake on your part to not include it.

@Jpince fyi.

**Comment by brianwulbern** [comment]
Thanks, @jpince.  I'll make sure the team understands that this is crucial.

**Pull request closed without merging**
