### PR TITLE
LPS-101932 Allow importing org.slf4j classes as they are needed

### PR DESCRIPTION
**Pull request by izaera**
Hey @brianchandotcom , the headers I'm removing in this PR were added in this other PR -> https://github.com/brianchandotcom/liferay-portal-ee/pull/19044 by @shuyangzhou.

Letting those packages be imported again makes the RTL servlet work, but it is very strange that those headers have been around so much time without making anything fail so I suspect that the LPS can be caused by some other change in a different place. However, I don't have information to propose another candidate as the cause.

Maybe any of you (@brianchandotcom , @shuyangzhou) can think of some other reason. If not, I would say just use my PR as it fixes the LPS and doesn't seem to break anything else.

Cheers.

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Reviewed. Failures unrelated

Issue described in LPS-101932 is fixed in test bundle.

**Comment by shuyangzhou** [comment]
The regression was caused by https://github.com/brianchandotcom/liferay-portal/commit/fa6865310ecd3bb6367c37478b5b06c4b3c4edb6

This module was doing compile include slf4j, which had to exclude the import. That commit changed it to compile only, therefore it needs the import. @brianchandotcom this change is fine, you can merge it.

**Comment by jpince** [comment]
@john-co @shuyangzhou thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/edb007d062...af723ee7ec

**Pull request closed without merging**
