### PR TITLE
LPS-52139 SF

### PR DESCRIPTION
**Pull request by rotty3000**
@juliocamarero would you please take a brief look here to make sure it's not breaking anything?

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cb0dbfc184...e1046f326d

**Comment by brianchandotcom** [comment]
Thx Ray.. nicely done.

**Comment by peterfellwock** [comment]
@juliocamarero @rotty3000 @brianchandotcom verified freemarker using portlets I know. Works! Thank you Ray

**Comment by juliocamarero** [comment]
sure, testing.....

**Pull request closed without merging**
