### PR TITLE
LPD-15357 Backend test coverage for LPD-9592 & LPD-9247 (Company Admins can access Index Actions and reindex when granted) - Dev FF

### PR DESCRIPTION
**Pull request by gustavolimav**
https://liferay.atlassian.net/browse/LPD-15357

Author: @gustavolimav
Reviewer: @joshuacords

Tests looks good forwarding it manually.

Tested here https://github.com/liferay-search/liferay-portal/pull/1253.

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@gustavolimav can you do it like this

modules/apps/document-library/document-library-web-test/src/testIntegration/java/com/liferay/document/library/web/internal/portlet/action/test/EditFileEntryMVCActionCommandTest.java

I'm not a big fan on unit tests. They run faster but they are brittle and not always "real"

I want to see what they look like as real tests.

**Comment by brianchandotcom** [comment]
@gustavolimav also, this is not sorted

```
	private void _setUpPermissionChecker(
		boolean omniadmin, boolean companyAdmin) {

		Mockito.doReturn(
			omniadmin
		).when(
			_permissionChecker
		).isOmniadmin();

		Mockito.doReturn(
			companyAdmin
		).when(
			_permissionChecker
		).isCompanyAdmin();
	}
```

**Comment by gustavolimav** [comment]
> @gustavolimav can you do it like this
> 
> modules/apps/document-library/document-library-web-test/src/testIntegration/java/com/liferay/document/library/web/internal/portlet/action/test/EditFileEntryMVCActionCommandTest.java
> 
> I'm not a big fan on unit tests. They run faster but they are brittle and not always "real"
> 
> I want to see what they look like as real tests.

For sure I can try to do that, thx for the reference.

**Pull request closed without merging**
