### PR TITLE
LPS-89617 Semantic versioning

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7e640b0573...eb80d6d465

**Comment by brianchandotcom** [comment]
See eb80d6d

**Pull request closed without merging**
