### PR TITLE
COMMERCE-6312 Fix event name for DDMForm to store product options attachments refs

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
Hello @brianchandotcom, this is a relevant fix that's still related to https://github.com/brianchandotcom/liferay-portal/pull/100337 and that was hiding in the forest of our JSP's. I'm not sure if we're still in time for the release. :/

Thanks in advance.

**Comment by gianmarcobrunialti** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1643e060ec...bfb2777321

**Comment by brianchandotcom** [comment]
@gianmarcobrunialti this will make it to 7.4 GA1

**Comment by justmerge** [comment]
@brianchandotcom Many thanks!

**Comment by gianmarcobrunialti** [comment]
@brianchandotcom Many thanks!

**Pull request closed without merging**
