### PR TITLE
Master | LRQA-57276, LRQA-57266, LRQA-57245, LRQA-57210

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LRQA-57276
https://issues.liferay.com/browse/LRQA-57266
https://issues.liferay.com/browse/LRQA-57245
https://issues.liferay.com/browse/LRQA-57210

This is only for master. Thanks.

cc/ @austinchiang

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:reopen

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a6d33ee152...14dd2b4137

**Pull request closed without merging**
