### PR TITLE
LPS-65067 Don't try to start fragment bundles

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
With this lpkg the whole system excluding wars works fine. I will continue to work on the Bundle wrapper for war bundles this afternoon.

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Very nice @shuyangzhou :)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/62663edb1d...e6a303b394

**Pull request closed without merging**
