### PR TITLE
Lps 75364

### PR DESCRIPTION
**Pull request by shuyangzhou**
@mtambara your OSGiServiceUtil change is good to go on top of this.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/de9071039a...1025a2ddc5

**Comment by brianchandotcom** [comment]
@shuyangzhou backported. Please have someone review that there are no extra ussages in 7.0.x that were not in master. Thx.

**Comment by shuyangzhou** [comment]
@tomwang2011 please make sure 7.0.x's usages are all updated, thanks!

**Comment by tomwang2011** [comment]
@brianchandotcom @shuyangzhou Just confirmed there are no additional usages on 7.0.x and 7.0.x-private for `com.liferay.portal.kernel.util.UnsafeConsumer`, thanks!

**Pull request closed without merging**
