### PR TITLE
LRQA-57212 Adding failed tc to acceptance quarantine

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:reopen

**Comment by leoadb** [comment]
@brianchandotcom I am sending this directly to you because it is prohibiting Commerce release. I already run tests on my repo and unrelated errors came up, as you can see here https://github.com/leoadb/liferay-portal/pull/762 . I've put that failing test in quarantine. Thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/59c7e03f2f...b1ae87c02d

**Comment by brianchandotcom** [comment]
@leoadb see my changes in my origin. Can you send a backport to 7.2.x?

@marcoleo @jpince @reizero00 fyi

**Pull request closed without merging**
