### PR TITLE
LPS-105165 Wordsmith SAML Language Properties

### PR DESCRIPTION
**Pull request by sez11a**
Modified one of @stian-sigvartsen's keys. @csierra

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7001ea495c...69d4a10839

**Comment by brianchandotcom** [comment]
Slight change in b0f5c5ad7c1923a880de4420884c6cf88f885657 @sez11a

**Comment by sez11a** [comment]
Okay. We abbreviate it IdP, so it seemed like it needed to be capitalized.

**Comment by brianchandotcom** [comment]
URL..

universal resource locator.

I just assumed it wasn't a proper name. We can Slack talk about this.

**Pull request closed without merging**
