### PR TITLE
LPS-160326 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-160326

This is only for master.

@olafk
@ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure cases are unrelated to changes.
See https://github.com/liferay-echo/liferay-portal/pull/9284
✔️ ci:test:stable - 27 out of 27 jobs passed
❌ ci:test:relevant - 64 out of 69 jobs passed in 2 hours 20 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/80e298ff15...6e3f299498

**Comment by brianchandotcom** [comment]
@olafk @ealonso see 6e3f299498470dee3bec01aa0f3468aa255dd212

**Pull request closed without merging**
