### PR TITLE
LPS-92096 API for Message Boards

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/95a9ea1dad...177b040ca6

**Comment by brianchandotcom** [comment]
@nhpatt this is a partial merge.. see upstream for my reverts that I need your help with. Thx.

**Comment by nhpatt** [comment]
Yes, those urls are strange (and duplicated). Removing them, will talk with Pablo.

**Pull request closed without merging**
