### PR TITLE
LPS-53262 ant format-source

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pei-jung can you resend? We don't have this "warning" pattern anywhere else. See WebFormPortlet to see how we set error / warning keys. And then have the key to display in the front end.

Feel free to send it back to me directly. Thx.

**Comment by pei-jung** [comment]
Hi Brian,

I understand that the key should be more expressive, but this is for default/generic warning messages that will be handled by portlet_messages.jspf. We don't have anything that will display default warning message in the front-end so I added a new case in the error taglib to handle this. As long as default error messages is enabled, the warning message will get shown even when it's not explicitly declared in the JSP. I see a couple places in the portal where we just use `error` for the key (https://github.com/liferay/liferay-plugins/blob/master/portlets/web-form-portlet/docroot/WEB-INF/src/com/liferay/webform/portlet/WebFormPortlet.java#L219), so I think we can follow the same pattern for general warning messages.

Please let me know if there are any issues with this implementation. Thanks!

**Comment by JorgeFerrer** [comment]
Hey Brian,

I'm with Pei-Jung here. It is true that this is not done anywhere, but it's a reasonable need: to be able to show a (warning) message in every single view of a portlet. The alternative would be to add it to every single JSP of that portlet, but that's error prone and requires duplication.

This solution is based on providing an special error key, warning, that allows showing a message in any view. I think this will be useful in other portlets as well.

Jorge

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d935b5df19...7e148693ca

**Pull request closed without merging**
