### PR TITLE
Revert LPS-75780 | master

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LPS-75780

@brianchandotcom 
Most recent pulls are starting to have all functional tests fail (and all pulls will auto-close), and I'm fairly certain it was caused by this pull:
https://github.com/brianchandotcom/liferay-portal/pull/52860

I've sent a revert here to confirm, but I won't be around to check to see if it really worked.
@brianwulbern Can you keep an eye on this pull too? You can ci close it if it doesn't solve anything.

The issue is that the sign in portlet is greyed out, so none of the tests are actually able to sign in.

before4

cc @jonmak08

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4575fca0b8...7464fa1cad

**Comment by brianchandotcom** [comment]
Thx @brianchiu @jonmak08 fyi on the revert

**Comment by brianwulbern** [comment]
@brianchiu, looks like the smoke test is passing again after the revert.  Thanks.

cc @jpince

**Comment by brianchiu** [comment]
@brianchandotcom 
No prob. I know the PR tester is a little flaky right now so it's harder to tell what's good and what isn't, but if the majority of the batches fail (like in https://github.com/brianchandotcom/liferay-portal/pull/52860 only 28 out of 126 passed), then it's safe to assume that you shouldn't merge it.

**Comment by jonmak08** [comment]
Updated pull request: https://github.com/brianchandotcom/liferay-portal/pull/52888

**Pull request closed without merging**
