### PR TITLE
LPS-96376 The Liferay.Language.get() operation in javascript requires that the key and call of the operation be on the same line

### PR DESCRIPTION
**Pull request by inacionery**
/cc @wincent

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@jbalsas @wincent can you guys auto enforce?

**Comment by brianchandotcom** [comment]
meaning, we need to make sure running prettier again won't break this stuff @jbalsas @wincent

**Comment by wincent** [comment]
Possible mitigations:

- (Temporary) add `// prettier-ignore` comment before each of these to stop Prettier from touching it.
- (Hacky) Increase maximum line width setting to reduce likelihood of unwanted line breaks.
- Adjust `Liferay.Language.get` regex to match across lines.
- (Difficult) Make `Liferay.Language.get` substitution work in terms of AST instead of regular expressions.
- Patch Prettier to avoid touching these AST nodes (basically a hard-coded version of `prettier-ignore`).

There might be others but that's what comes to mind for now. @jbalsas and I can discuss and let you know what we come up with.

**Comment by wincent** [comment]
@brianchandotcom @inacionery: we're prioritizing https://issues.liferay.com/browse/LPS-97016 to make sure this doesn't happen again.

**Comment by jbalsas** [comment]
Hey @hhuijser, this PR should've failed `ci:sf` since it's actually breaking our formatting. Inspecting the log, we see that:

```
format-source-all:
     [echo] 
     [echo] This target does not format .es.js files. Please run the following command from /opt/dev/projects/github/liferay-portal/modules to do so:
     [echo] 
     [echo] ../gradlew npmRunCheckFormat
     [echo] 				
[stopwatch] [run.batch.test.action: 3:18.158 sec]
```

I assume we've never really enabled top-level format-source checks for frontend. We've provided top-level scripts that can be run (rather than per-project) so we can enable this.

Could you please reach out to us for more details so we can enable this and make sure we're properly testing this on CI?

Thanks!

**Comment by hhuijser** [comment]
Not sure why this was disabled in `format-source-all` target. Guess because it used to be super slow?

Should be easy to change by making some changes to the ant target in `portal-impl/build.xml`

**Pull request closed without merging**
