### PR TITLE
LPS-56162 Portlet Configuration - Scope selection saves but the the saved configuration is not retrieved correctly

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
@ZoltanTakacs could you please include this in the millestone?

thanks!

**Comment by ZoltanTakacs** [comment]
Hey @juliocamarero,

Sure, I'll do the necessary steps as soon as it gets merged to master. 

Thank you,
Zoltán

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b3058dd7b7...a7d00f65ec

**Pull request closed without merging**
