### PR TITLE
LPS-64098 update ant-bnd dependency

### PR DESCRIPTION
**Pull request by rotty3000**
/cc @vsingleton @ngriffin7a

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 what's going on with Git? I've seen this error a few times today

**Comment by pyoo47** [comment]
ci:retest

**Comment by sharonchoi** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
ci:retest

Not sure if

```
java.lang.AssertionError: Liferay CE JavaScript Scripting was not uninstalled for upgrade
```

Was real or not for the LPKG error.

**Pull request closed without merging**
