### PR TITLE
LPS-99898

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4fbd7fc562...3d6206c955

**Comment by brianchandotcom** [comment]
So nice @hhuijser :)

**Comment by brianchandotcom** [comment]
@hhuijser can you double check to see where modules.properties might be used/read? Just in case we forgot to update those places.

@petershin this change is important. See changes to modules.properties. Can you also check to see where else it might be currently used? Thx.

**Comment by jbalsas** [comment]
Nice @hhuijser, thanks! 

/cc @wincent

**Comment by petershin** [comment]
@brianchandotcom - Checking. Will send a follow up pull if needed

**Pull request closed without merging**
