### PR TITLE
LPS-92069 Use the the classPK if it is also the AssetEntry's entryId.  Otherwise use the AssetEntry's classPK.

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:reopen

**Comment by inacionery** [comment]
Failed unrelated, working to fix this!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/afbc1f32d4...86b392c221

**Comment by brianchandotcom** [comment]
@jrao @inacionery @rafaprax see 86b392c

Isn't this the same thing?

**Comment by inacionery** [comment]
Hey @brianchandotcom,

It's not the same :(

**Pull request closed without merging**
