### PR TITLE
LPS-61372 ContextUserReplace does not work with bundles.

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brandizzi** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
Aborted due to known start-up issue caused by https://github.com/brianchandotcom/liferay-portal/commit/d992d839572c70e1e93be6c97b1566069941a69f

After this <a href="https://github.com/brianchandotcom/liferay-portal/pull/34330">pull</a> is merged we can re-run this particular pull request.

Sorry for the inconvenience.

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@brandizzi do I still need this pull?

I'm closing this pull since https://github.com/brianchandotcom/liferay-portal/pull/34383 may be all we need? Please resend if we still need this.

**Pull request closed without merging**
