### PR TITLE
LPS-150190 - Create clay icon set module

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Manual forward from https://github.com/liferay-frontend/liferay-portal/pull/2107

CI passed both SF and relevant, manually forwarding due to a small merge conflict fix.

---------------

https://issues.liferay.com/browse/LPS-150190

This provides a new mechanism that allow osgi modules to contribute their own icon packs. The primary goal of this feature was to separate clay icons into their own module which deploys an icon pack.

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fbe46507fc...3acad49934

**Comment by brianchandotcom** [comment]
@bryceosterhaus see changes in my origin

also, this kind of threw me off

```
			String iconsPath = headers.get("Liferay-Icons-Path");
			String name = headers.get("Liferay-Icons-Pack-Name");
```

Is that consistent?

**Comment by bryceosterhaus** [comment]
@brianchandotcom I will take another look at that.

My thought was that `path` was too generic for `iconsPath`.

And then for `name`, that is how we pass it into the FrontendIconsResource class, so I didn't want to name it `iconsName` to confuse that it was any different. But I will take another look and see what other modules do.

**Comment by brianchandotcom** [comment]
@bryceosterhaus yeah, it just feels inconsistent. Because one is name and the other is iconsPath.

**Pull request closed without merging**
