### PR TITLE
LPS-75415

### PR DESCRIPTION
**Pull request by marco-leo**
Fix organization selector 

cc @JorgeFerrer @drewbrokke

### CODE REVIEW

**Comment by marco-leo** [comment]
ci:test

**Comment by marco-leo** [comment]
@brianchandotcom looks that this error is not related to the changes in this pull

**Comment by brianchandotcom** [comment]
@brandizzi looks like one of the calendar tests fail due to time zone, so it'll fail randomly depending on what time of day the test is run.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/df1b6a1b19...264fa76d55

**Comment by brandizzi** [comment]
Thanks @brianchandotcom! I generally don't work on calendar since I'm in the Search team. But luckily those are failures on search tests as well, we worked on them recently, so I'll check that.

cc @arboliveira @jeyvison.

**Pull request closed without merging**
