### PR TITLE
[FWD PORT] LPS-65589 cover all possible scenarios

### PR DESCRIPTION
**Pull request by adolfopa**
This is a forward port of https://github.com/brianchandotcom/liferay-plugins-ee/pull/18743

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@adolfopa @amosfong this was an incorrect frontport.

See 5e9349c1bdbd8cc416b407eecef867b764a8fc52 for my fix.

**Comment by adolfopa** [comment]
Sorry, my fault @brianchandotcom @amosfong

**Pull request closed without merging**
