### PR TITLE
LPS-67499 Inactive instances still serve static content

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-67499](https://issues.liferay.com/browse/LPS-67499).<br><br>/cc @mhan810

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:retest

**Comment by drewbrokke** [comment]
ci:start

**Comment by drewbrokke** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/23b4d2e6ba...7298c881b5

**Pull request closed without merging**
