### PR TITLE
LPD-16467 | LPD-16977: Allow users to import and export Aggregation, Formula, Encrypted and Boolean fields in CSV

### PR DESCRIPTION
**Pull request by sergiojimcos**
## Motivation
The aim of this PR is to allow users to import and export Aggregation, Formula, Encrypted and Boolean fields in CSV. As well as, this implies to import and export using the UI.

**What is new?**
- Restricted some Object Fields under Feature Flag.
- Add integration test case.
- Update functional tests

**JIRA Related Tickets**
https://liferay.atlassian.net/browse/LPD-16467
https://liferay.atlassian.net/browse/LPD-16977
https://liferay.atlassian.net/browse/LPD-17104

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:reopen

**Comment by sergiojimcos** [comment]
Forwarded from: https://github.com/liferay-headless/liferay-portal/pull/1854

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/17f1201dc4...e2475c6d6b

**Comment by brianchandotcom** [comment]
@sergiojimcos just e2475c6d6b5bbe856f4d1f0d5c85c6ab1edab1fb

**Pull request closed without merging**
