### PR TITLE
LPS-63194 fix translations in Portlet Icon Configurations

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
@matethurzo, @sergiogonzalez @marcellustavares @lionah @drewbrokke @pei-jung @jorgeFerrer this should fix all the not translated labels in the icon menus. Please, review the changes in those commits affecting your components just in case we missed something (we have put the name of the component in the commit message so that you can just review yours). 

As you can see, now each component is rensponsible of translating its messages. You can easily use the resourceBundle from the portal, the one from your module or even agregate both as needed. Feel free to reach me if you still see some not translated labels in the portlet action menu.

thanks!

**Comment by brianchandotcom** [comment]
@juliocamarero I'm fixing the PMD error because it caught a bug.. no need to resend.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0240fad538...92398da7d2

**Comment by brianchandotcom** [comment]
@juliocamarero see 92398da7d273966a12acf961f493a62af9b402aa for my PMD fix.

also 68adf12d7053142132f38a34b8b9a5ebc3dcd48b for SF

**Comment by lionah** [comment]
@juliocamarero looks good on our end!

**Pull request closed without merging**
