### PR TITLE
LPS-99823 baseline

### PR DESCRIPTION
**Pull request by darquesdev**
@ealonso @epgarcia @victorg1991

[this change](https://github.com/brianchandotcom/liferay-portal/pull/77096/commits/2245d874583f86a75f7b6e5323bc8fccc6a94b33) was already included in a [previous PR](https://github.com/brianchandotcom/liferay-portal/pull/77062/commits/51ab3d0b00f4525e2a783b59f1b658b16019a6f2) by @victorg1991

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/23298eb256...401a4285d7

**Comment by brianchandotcom** [comment]
@darquesdev the LPS in JIRA says it is a 7.2.x regression? If so, please send me (directly) a pull for 7.2.x.

**Comment by darquesdev** [comment]
Hi @brianchandotcom this PR was created in order [to fix this](https://issues.liferay.com/browse/LPS-99806) which is not a 7.2.x regression, I included the baseline commit to prevent tests to fail (my bad). The LPS created to solve the semantic versioning [is here](https://issues.liferay.com/browse/LPS-99823), and @victorg1991 already [sent a PR](https://github.com/brianchandotcom/liferay-portal/pull/77062). He is going to take care of the BPR too. Let me know if it's ok. Thanks and sorry for the inconvenience

CC: @ealonso

**Comment by victorg1991** [comment]
Backport sent https://github.com/brianchandotcom/liferay-portal-ee/pull/26038

**Pull request closed without merging**
