### PR TITLE
LPS-77886 Use portal kernel (see bnd.bnd)

### PR DESCRIPTION
**Pull request by petershin**
@hhuijser

### CODE REVIEW

**Comment by petershin** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@petershin it's still hanging for me?

```
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - Total time: 2.849 s
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - Finished at: 2018-02-09T12:30:25-08:00
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - Final Memory: 18M/580M
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - ------------------------------------------------------------------------
:util:source-formatter:formatXML
:util:source-formatter:formatSource
/home/brian/dev/projects/github/liferay-portal/modules/util/source-formatter/src/main/resources/META-INF/maven/com.liferay/com.liferay.source.formatter/plugin-help.xml (SourceCheck:XMLEmptyLinesCheck)
/home/brian/dev/projects/github/liferay-portal/modules/util/source-formatter/src/main/resources/META-INF/maven/plugin.xml (SourceCheck:XMLEmptyLinesCheck)
/home/brian/dev/projects/github/liferay-portal/modules/util/source-formatter/src/main/resources/checkstyle.xml (SourceCheck:XMLEmptyLinesCheck)
/home/brian/dev/projects/github/liferay-portal/modules/util/source-formatter/src/main/resources/checkstyle.xml (SourceCheck:XMLWhitespaceCheck)
/home/brian/dev/projects/github/liferay-portal/modules/util/source-formatter/src/main/resources/sourcechecks.xml (SourceCheck:XMLEmptyLinesCheck)
/home/brian/dev/projects/github/liferay-portal/modules/util/source-formatter/src/main/resources/sourcechecks.xml (SourceCheck:XMLWhitespaceCheck)
                       Exception in thread "main" java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Unable to format ./src/main/java/com/liferay/source/formatter/BNDImportsFormatter.java
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:301)
        at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:216)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Unable to format ./src/main/java/com/liferay/source/formatter/BNDImportsFormatter.java
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.liferay.source.formatter.BaseSourceProcessor.format(BaseSourceProcessor.java:125)
        at com.liferay.source.formatter.SourceFormatter._runSourceProcessor(SourceFormatter.java:676)
        at com.liferay.source.formatter.SourceFormatter.access$000(SourceFormatter.java:64)
        at com.liferay.source.formatter.SourceFormatter$1.call(SourceFormatter.java:287)
        at com.liferay.source.formatter.SourceFormatter$1.call(SourceFormatter.java:283)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Unable to format ./src/main/java/com/liferay/source/formatter/BNDImportsFormatter.java
        at com.liferay.source.formatter.BaseSourceProcessor._performTask(BaseSourceProcessor.java:655)
        at com.liferay.source.formatter.BaseSourceProcessor.access$000(BaseSourceProcessor.java:68)
        at com.liferay.source.formatter.BaseSourceProcessor$1.call(BaseSourceProcessor.java:114)
        at com.liferay.source.formatter.BaseSourceProcessor$1.call(BaseSourceProcessor.java:110)
        ... 4 more
Caused by: java.lang.NoClassDefFoundError: com/liferay/petra/string/StringBundler
        at com.liferay.source.formatter.parser.JavaClassParser.parseJavaClass(JavaClassParser.java:82)
        at com.liferay.source.formatter.checks.util.SourceChecksUtil.processSourceChecks(SourceChecksUtil.java:135)
        at com.liferay.source.formatter.BaseSourceProcessor._processSourceChecks(BaseSourceProcessor.java:665)
        at com.liferay.source.formatter.BaseSourceProcessor.format(BaseSourceProcessor.java:298)
        at com.liferay.source.formatter.JavaSourceProcessor.format(JavaSourceProcessor.java:74)
        at com.liferay.source.formatter.BaseSourceProcessor._format(BaseSourceProcessor.java:546)
        at com.liferay.source.formatter.BaseSourceProcessor._performTask(BaseSourceProcessor.java:643)
        ... 7 more
> Building 18% > :util:source-formatter:formatSource
```

Do I need to force publish this?

**Comment by petershin** [comment]
Adding @Ithildir

@brianchandotcom - I think so

**Pull request closed without merging**
