### PR TITLE
LPS-63613 Basic tests for permission framework

### PR DESCRIPTION
**Pull request by topolik**
Hi Brian,

we don't have any tests for permission framework. I created several tests to cover basic scenarios we use in portal:
1. Default resources for portlet
2. Root model-resource, most common scenario is site level
3. Entity model-resources
4. Tests for portlet that is not scoped to site
5. Tests for missing SCOPE_INDIVIDUAL permissions

Beside tests I added one more related commit 372201e (the first one). We use Omniadmin for all tests and so permission checking is ignored in most tests, so I moved the omniAdmin check after regular permission checks to reveal permission issues in tests (these are already fixed and merged).

This PR contains commits from https://github.com/brianchandotcom/liferay-portal/pull/36571

Thanks.

https://issues.liferay.com/browse/LPS-63613

### CODE REVIEW

**Comment by topolik** [comment]
Failed tests are real - another bug in Upgrade processes - we don't create appropriate permission resources for DDMTemplate.

> There is no com.liferay.journal.model.JournalArticle-com.liferay.dynamic.data.mapping.model.DDMTemplate with primary key 177 and companyId 20155

**Comment by topolik** [comment]
Brian,

@marcellustavares is going to fix the upgrade bug. I leave it up to you to decide whether merge or not to merge, i.e. wait for Marcellus to fix that and merge later.

Thanks.

**Comment by brianchandotcom** [comment]
@marcellustavares can you fix the bug and resend this pull? Thx.

**Comment by topolik** [comment]
Please see
* https://github.com/brianchandotcom/liferay-portal/pull/36630 - the bug fix
* https://github.com/brianchandotcom/liferay-portal/pull/36649 - this pull, resent

Thank you.

**Pull request closed without merging**
