### PR TITLE
LPS-55647 portal-scripting-javascript bundle throws errors in init

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b6b3ad9010...43f439785b

**Comment by brianchandotcom** [comment]
@shuyangzhou is there any way for us to make sure that init errors like the one that Ray caught are rejected by the CI in the future?

Thx.

**Comment by shuyangzhou** [comment]
A bit more input? What init error? From tomcat console log?

**Comment by brianchandotcom** [comment]
I think when you deploy the module it has an init error. (before Ray's fix)

**Comment by shuyangzhou** [comment]
Hmm, CI already caught it at https://github.com/brianchandotcom/liferay-portal/pull/26542, that's how @rotty3000 came out with this fix, right?

**Comment by shuyangzhou** [comment]
but not really sure why it did not break on others' pulls.

**Comment by shuyangzhou** [comment]
Ah, I see, https://github.com/brianchandotcom/liferay-portal/pull/26542 adds some new tests, which got grouped into the PACL tests group that exposed this issue. Before https://github.com/brianchandotcom/liferay-portal/pull/26542, the problem was still there, just no one ran into it.

This is actually something @cgoncas and I have planned to work on, basically we are not asserting the log during tomcat boot up, and it will cover this case, as it dumps out tons of error log during boot up, but does not really affect the test results, that's why CI was not complaining.

@cgoncas, any progress on the log interceptor solution?

**Pull request closed without merging**
