### PR TITLE
Lps-137699 Upgrade Report: new features

### PR DESCRIPTION
**Pull request by achaparro**
@samziemer

### CODE REVIEW

**Comment by achaparro** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/15221b97dc...2698f7cb31

**Comment by brianchandotcom** [comment]
@achaparro @SamZiemer can you review my changes? and fix any tests I may have broken? I didn't have time to run them but wanted to get this in. Thx

**Comment by SamZiemer** [comment]
Hi @brianchandotcom, I reviewed your changes and ran the tests locally, everything looks good and still functions as intended, thank you.

**Pull request closed without merging**
