### PR TITLE
LPS-60598 Escape title on related assets

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by neilking** [comment]
It had been fixed like this before, but it caused over escape issues. Check this link https://github.com/brianchandotcom/liferay-portal/pull/33653

**Comment by ealonso** [comment]
I think this is the correct fix for that, and the issue you mentioned is related with the user avatar not with the related assets.

**Comment by ealonso** [comment]
ci:retest

**Comment by neilking** [comment]
Hi Eudaldo, this is was the fix that has been revered. https://github.com/brianchandotcom/liferay-portal/pull/33646
Seems it relates the nav_item change.

**Comment by ealonso** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/85af674bfa...67790c429c

**Comment by brianchandotcom** [comment]
@ealonso see 3e25fffd56d6d4720ab728f8561046ae4f38c40d and 67790c429c8617970ad44d0edd4fa07611723cdf

@neilking thanks for the comments

**Pull request closed without merging**
