### PR TITLE
LPS-98654

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by IstvanD** [comment]
Hi @brianchandotcom 

The language keys were designed following the pattern in `AMImageConfiguration.java`where each configuration option has their name and description encoded with language keys.

Is there a way to translate these strings other than language resources?

Thank you and best regards,
István

**Comment by IstvanD** [comment]
Hey @adolfopa 

Could you please take a look at @brianchandotcom's comment?

Thank you and best regards,
István

**Comment by adolfopa** [comment]
Sorry guys, missed the previous notifications. I'll update the keys and resend the PR.

**Comment by IstvanD** [comment]
Thank you, @adolfopa !

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/77917

**Pull request closed without merging**
