### PR TITLE
LPS-77109 Fix ConfigurationTemporarySwapper race condition

### PR DESCRIPTION
**Pull request by shuyangzhou**
@drewbrokke this fixes the random ConfigurationTemporarySwapperTest failure, which is a real problem.

CC @preston-crary

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Bravo @shuyangzhou 

Can you explain in the LPS how this fix works? How did you even find it? Fyi @drewbrokke

Merged.

**Comment by brianchandotcom** [comment]
@shuyangzhou can you send me a backport to 7.0.x?

@drewbrokke can you send me pulls to  "unignore" the broken tests in master and 7.0.x

**Comment by drewbrokke** [comment]
@brianchandotcom sounds good.

@shuyangzhou if this works as you explained, it actually makes the entire `_validateService ` method completely unnecessary.  I'll send a follow-up pull removing it.

**Comment by shuyangzhou** [comment]
@tomwang please backport, thanks!

**Comment by shuyangzhou** [comment]
Actually Tom is on PTO today, @preston-crary please backport this, thanks!

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal-ee/pull/19191

**Comment by drewbrokke** [comment]
@brianchandotcom pull sent: https://github.com/brianchandotcom/liferay-portal/pull/54383

**Pull request closed without merging**
