### PR TITLE
LPS-97858 Fix order of polyfills

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test

**Comment by julien** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@petershin see Maven central lag.. can we binary cache this?

**Comment by brianchandotcom** [comment]
@julien the right way e649d2b6ad5e34c91136f2f6706ece502ee38e68 so we don't affect runtime performance.

**Comment by julien** [comment]
@brianchandotcom ok, thanks for the tip. I'll bookmark this for my future self.

**Comment by petershin** [comment]
@brianchandotcom - Looking into configuring `Maven`.  Will send a pull

**Pull request closed without merging**
