### PR TITLE
LPS-157460 | master

### PR DESCRIPTION
**Pull request by carolmariaabb**
/cc @TaiPhamLR

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@carolmariaabb @TaiPhamLR it should be

The structure was imported without a custom view.

OR

The structure was imported without custom views.

I couldn't tell which one it should be. Please resend.

**Comment by TaiPhamLR** [comment]
Hi @carolmariaabb, Could you help me to consider which message should be, and resend PR? Thanks a lot.

**Comment by carolmariaabb** [comment]
Hi @TaiPhamLR , could you send us a message in the #help-objects slack channel? This way we can ask the design team for their opinion. Thanks!

**Pull request closed without merging**
