### PR TITLE
LPS-109607 Ability to drag&drop fragment composition from the sidebar to the content page	

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
//cc @ealonso

**Comment by ruben-pulido** [comment]
//cc @pavel-savinov

**Comment by ruben-pulido** [comment]
//cc @jkappler

**Comment by ruben-pulido** [comment]
//cc @p2kmgcl

**Comment by psavinov** [comment]
ci:test:stable

**Comment by pavel-savinov** [comment]
ci:test:stable

**Comment by kenjiheigel** [comment]
Stable failure is unrelated. @psavinov, @pavel-savinov 
* Failing test is `com.liferay.portal.workflow.metrics.service.internal.search.index.test.SLAInstanceResultWorkflowMetricsIndexerTest.testReindex` in the modules-integration-mysql57-jdk8 batch. This issue is caused by [LPS-108756](https://issues.liferay.com/browse/LPS-108756).

**Comment by jkappler** [comment]
thanks @kenjiheigel!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/63dd7ea3c0...be719fa7c8

**Pull request closed without merging**
