### PR TITLE
Lps 68816

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @sergiogonzalez @mhan810

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@peterfellwock, can you take a look at those elasticsearch unit test failures? They have been showing up lately and very annoying.

**Comment by shuyangzhou** [comment]
@peterfellwock you can talk to @arboliveira, he wrote those tests, he should be able to help you on this.

**Comment by brianchandotcom** [comment]
@peterfellwock @arboliveira usually sits a few seats in front of you.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by peterfellwock** [comment]
@brianchandotcom Spoke with @arboliveira and he will be sending you a pull to stop this issue.

**Pull request closed without merging**
