### PR TITLE
Revert "LPS-189124 It shouldn't be needed"

### PR DESCRIPTION
**Pull request by ealonso**
This reverts commit b97424c1fa6a98c448ec5742e99e4a6cd17ed11f.

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/500594ffc5...d3cdd97b67

**Comment by brianchandotcom** [comment]
@ealonso can you break it up and make it so the stuff that has to happen first does so via a different if else block?

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/12691

**Pull request closed without merging**
