### PR TITLE
LPS-93201 Regen

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by darquesdev** [comment]
CC: @epgarcia

**Comment by jpince** [comment]
ci:close @ealonso @epgarcia @darquesdev please look into upgrade failures
```
LIFERAY_ERROR: Table 'lportal.LayoutPageTemplateStructureRel' doesn't exist: create unique index IX_BB165B45 on LayoutPageTemplateStructureRel (layoutPageTemplateStructureId, segmentsExperienceId);
LIFERAY_ERROR: Table 'lportal.LayoutPageTemplateStructureRel' doesn't exist: create index IX_6F8B3413 on LayoutPageTemplateStructureRel (uuid_, companyId);
LIFERAY_ERROR: Table 'lportal.LayoutPageTemplateStructureRel' doesn't exist: create unique index IX_2467A355 on LayoutPageTemplateStructureRel (uuid_, groupId);
```
https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/155959/consoleFull

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
@jpince Thanks for the catch! We'll fix this and send a new PR.

**Pull request closed without merging**
