### PR TITLE
Lps 74693

### PR DESCRIPTION
**Pull request by shuyangzhou**
@mhan810 @david-truong this is the beginning of our preparation for arquillian removal.
The plan for preparation is to inline and simplify all the arquillian extensions we have. Basically going back to the initial version of arquillian junit bridge I did 2+ years ago. Then we will only have a clean dependency against arquillian. Then we can actually start to plan to replace it. There are quite a few extensions we have, this preparation phase may last quite a while.

@brianchandotcom to reduce the risk of this migration, we want a milestone release after inlining each dependency and widely applying them, including subrepos, so that we know the infrastructure is still in a good shape. So please do a release after merging this, then I will send out the subrepo usages update pulls.

CC @Preston-Crary

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a1f959688d...226bad407c

**Comment by brianchandotcom** [comment]
@shuyangzhou @Preston-Crary please backport. Thx.

**Comment by Preston-Crary** [comment]
Sub repo pulls:
https://github.com/shuyangzhou/com-liferay-adaptive-media/pull/4
https://github.com/shuyangzhou/com-liferay-dynamic-data-mapping/pull/6
https://github.com/shuyangzhou/com-liferay-journal/pull/51
https://github.com/shuyangzhou/com-liferay-portal-workflow/pull/4

**Pull request closed without merging**
