### PR TITLE
LPS-107723 SF. No need to define variable

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
//cc @ealonso

**Comment by ruben-pulido** [comment]
//cc @jkappler

**Comment by brianchandotcom** [comment]
@ruben-pulido CI issues. Please fix and resend.

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
@ruben-pulido, I will resend

**Pull request closed without merging**
