### PR TITLE
LPS-69171 SF

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@ChrisKian I sorted the finder columns so they match the order that they show up in service.xml. Please resend on top of https://github.com/ChrisKian/liferay-portal/pull/9

Thx

**Comment by ChrisKian** [comment]
Regenerated, see https://github.com/brianchandotcom/liferay-portal/pull/45316.  Thanks!

**Pull request closed without merging**
