### PR TITLE
LPS-86125 SF

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by jpince** [comment]
@kyle-miho @brianchiu POSHI failures

**Comment by brianchiu** [comment]
We'll take a look.

**Comment by brianchiu** [comment]
ci:close

**Comment by brianchiu** [comment]
Tested here: https://github.com/brianchiu/liferay-portal/pull/1748
Everything passed (had to fix a rebase error). 

Pull sent to BChan here:
https://github.com/brianchandotcom/liferay-portal/pull/65997

**Pull request closed without merging**
