### PR TITLE
LPS-51081 Gradle scripts for modules/util

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9fd750dbee...1f326333ee

**Pull request closed without merging**
