### PR TITLE
LPS-86910 Use aria-label with localized value of Close

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test

**Comment by julien** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/372410b3ef...d7c26db42d

**Comment by brianchandotcom** [comment]
@julien @ricardocousolr please backport. Thx.

**Pull request closed without merging**
