### PR TITLE
LPS-75889

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ae37b94141...3bb1369dae

**Comment by brianchandotcom** [comment]
@izaera see my changes in 3bb1369daec3a1e5d8aa4f88316a746e8ad31f55 

@jbalsas can we auto SF these .ts files too? I know they're just for Angular, but they're essentially JS and should follow the same .es.js format.

@Ithildir @petershin @hhuijser fyi

**Comment by Ithildir** [comment]
@brianchandotcom, should we also add an empty line in https://github.com/liferay/liferay-portal/blob/master/modules/apps/collaboration/flags/flags-taglib/src/main/resources/META-INF/resources/flags/Flags.es.js#L280-L281? This is just an example, there are a lot of `.es.js` files with this same comment.

**Comment by jbalsas** [comment]
hey @brianchandotcom, @Ithildir, the tool we use supports most frontend languages, so we'll apply it to autoformat `.ts` as well

The line between statements is **not autoformatable**. We can enforce it on the `lint` level setting the proper `padding-line-between-statements` configuration. I'll look into it.

**Pull request closed without merging**
