### PR TITLE
LPS-66646

### PR DESCRIPTION
**Pull request by kenjiheigel**
@brianchandotcom, @juliocamarero

This pull updates some taglib attributes in portal-web which require changes across multiple modules including journal. Sending the non-journal changes will break functionality for journal, but since that cannot be merged together, I will send a follow up pull to the journal subrepo. In the mean time, I'm quarantining the broken tests in this pull and will remove them from quarantine once this pull and the journal pull are both merged into liferay-portal. Shuyang has told me this would be the best course of action in this situation. 

I have tested all the changes together (including the journal changes) here: https://github.com/kenjiheigel/liferay-portal/pull/320

Let me know if you have any questions. Thanks\! 

cc-ing @jonmak08 @zxdgoal @jbalsas

### CODE REVIEW

**Comment by kenjiheigel** [comment]
@anthony-chu

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
Journal pull: 
https://github.com/liferay/com-liferay-journal/pull/48

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/eb7cefcdba...8f4dabe261

**Comment by brianchandotcom** [comment]
@jonmak08 @zxdgoal see d55b5d96fa355dd7d1e46dd603435372d3799a62 and bfdf75de7078ca7b38b39f420a9e0769d0c5d4a9

Thx

**Comment by kenjiheigel** [comment]
Tests turned back on in:
https://github.com/brianchandotcom/liferay-portal/pull/44932

**Pull request closed without merging**
