### PR TITLE
Simplify paths and update Gradle files

### PR DESCRIPTION
**Pull request by kellylisbino**

### CODE REVIEW

**Comment by gleicelisbino** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/31cfb25e33...ba8429aa05

**Comment by brianchandotcom** [comment]
Thx @gleicelisbino all republished.

**Comment by gleicelisbino** [comment]
Thank you so much @brianchandotcom

**Pull request closed without merging**
