### PR TITLE
LPS-84279 SF

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:reopen

**Comment by jeyvison** [comment]
Smoke test failure doesn't seem to be related.

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fb8ecc90f4...92b511059b

**Pull request closed without merging**
