### PR TITLE
LRQA-44612 - Regen package-lock files

### PR DESCRIPTION
**Pull request by bryceosterhaus**
cc @jbalsas

### CODE REVIEW

**Comment by jbalsas** [comment]
Awesome job pushing this @bryceosterhaus, @john-co!

@brianchandotcom, this is a big PR with high risk of confoicts. Please, could you process it as soon as you can and merge if possible? We can send followup ones with additional changes.

The goal here is to finally centralize all frontend related build to offer consistency and simplify the setup of new modules. Once all looks good to you, we will proceed to enforce through sourceformatter, and all future changes will happen globally (like gradle plugins).

Let us know what you think!

Thanks!

**Comment by bryceosterhaus** [comment]
new pr https://github.com/brianchandotcom/liferay-portal/pull/67391

**Comment by jpince** [comment]
@bryceosterhaus @john-co this pull caused a failure in `js-unit`. I suspect BChan merged #67391 and forgot to comment. Please follow up, as it's failing in everyone's pull requests. 

@john-co If it cannot be fixed within an hour, please remove the batch from relevant (add a # in front of this line https://github.com/liferay/liferay-portal/blob/master/test.properties#L1616). I don't have time to do this myself right now.

cc/ @vicnate5

**Comment by john-co** [comment]
@jpince This is due to a forms issue that has been failing prior to this pull.
please see: https://github.com/brianchandotcom/liferay-portal/pull/67417#issuecomment-459387735

cc/ @vicnate5

**Pull request closed without merging**
