### PR TITLE
LPS-128283 Add a smoke test about WC, WC Structure, and WC Template into DE test suite

### PR DESCRIPTION
**Pull request by david-gutierrez-mesa**
https://issues.liferay.com/browse/LPS-128283

cc @emanuelfisilva

### CODE REVIEW

**Comment by david-gutierrez-mesa** [comment]
Resend of https://github.com/brianchandotcom/liferay-portal/pull/99216

**Comment by david-gutierrez-mesa** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@david-gutierrez-mesa one more change

Type:

git grep "@description = \"LPS-"

and follow existing pattern.

**Comment by david-gutierrez-mesa** [comment]
Sure! I'm taking a look and sending a PR with a sentence following the pattern!

Thanks!

**Pull request closed without merging**
