### PR TITLE
LPS-51819

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-51819](https://issues.liferay.com/browse/LPS-51819).<br><br>

### CODE REVIEW

**Comment by drewbrokke** [comment]
@JorgeFerrer @natecavanaugh @pei-jung

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Please resend. Unable to rebase and test.

**Pull request closed without merging**
