### PR TITLE
LPS-61420

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Got a feeling this might still be breaking stuff...

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
I had to stop and retest this pull because a recent CI pull that got merged into upstream broke the PR tester. The source of this problem has been reverted.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by hhuijser** [comment]
@brianchandotcom 

Closed as order matters in spring.xml.
Will look into this more, but for now not really sure which bean is depending on what and therefore is breaking the tests.

**Pull request closed without merging**
