### PR TITLE
LPS-70092

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by brunobasto** [comment]
Hey @Ithildir,

Were you able to test it to make sure it's working? I'm asking because I didn't know how to test it.

**Comment by Ithildir** [comment]
Yeah, `Footer.soy.js` in `hello-soy-web` has now:
```javascript
      var MSG_EXTERNAL_2986127772961742460 = Liferay.Language.get('this-portlet-was-written-using-soy-templates');
MSG_EXTERNAL_2986127772961742460 = MSG_EXTERNAL_2986127772961742460.replace(/{|}/g,'x01');
```

**Comment by brunobasto** [comment]
hm, I'm not sure that's correct. It should output: `.replace(/{|}/g,'\x01')` I think I forgot a `\`.

Adding the Soy Portlet to a page should show 'Welcome to Liferay ...' instead of 'Welcome to {0}'.

**Comment by Ithildir** [comment]
ci:stop

**Comment by Ithildir** [comment]
@brunobasto, now that I'm thinking about it... what if the translated string includes `{` or `}`?

**Comment by brunobasto** [comment]
hm.. not sure. We usually use {0}, {1}, ... {n} in our Language.properties for parameters. We could improve the replace regex to only replace those { and } which match {\d+} pattern..

**Comment by Ithildir** [comment]
Yeah, I think that would be better! What should I write then?

**Comment by brunobasto** [comment]
Quickly tested here, looks like `.replace(/{(\d+)}/g, '\x01$1\x01')` should work

**Pull request closed without merging**
