### PR TITLE
Gradle Plugin Change Logs

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0082749354...5727210b79

**Comment by brianchandotcom** [comment]
@codyhoag fyi

**Pull request closed without merging**
