### PR TITLE
LPS-92703 Provide explanatory help message

### PR DESCRIPTION
**Pull request by JorgeFerrer**
/cc @ealonso

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
ci:reopen

**Comment by JorgeFerrer** [comment]
The reason for the failure is not related to this pull and is fixed by https://github.com/brianchandotcom/liferay-portal/pull/70455

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/49bcacf7c4...2eb6c51d6f

**Comment by brianchandotcom** [comment]
@JorgeFerrer minor wordsmithing 2eb6c51d6f9badf8cb6e5d25fb01169b9390f4dc

**Pull request closed without merging**
