### PR TITLE
LPS-55533 SF

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@sergiogonzalez 

1.) Can you add a BaseEditor that all Editor's extend from? For the path, we should just return "/editors/tinymce_simple.jsp" (too much duplicated logic now)

```
ThemeDisplay themeDisplay = (ThemeDisplay)request.getAttribute(
			WebKeys.THEME_DISPLAY);

		return themeDisplay.getPathEditors()
```

2.) Editor and EditorUtil are too confusing (I immediately think that EditorUtil is a static class that only calls methods available in Editor.

Thx!

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Hey @brianchandotcom, does WYSIWYGEditor.java sound good for you?

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
