### PR TITLE
LPS-106251 | LPS-106288 | LPS-106245 | LPS-106278 Revert

### PR DESCRIPTION
**Pull request by dgarciasarai**
Revert these PRs:
- https://github.com/brianchandotcom/liferay-portal/pull/82403
- https://github.com/brianchandotcom/liferay-portal/pull/82428
- https://github.com/brianchandotcom/liferay-portal/pull/82407
- https://github.com/brianchandotcom/liferay-portal/pull/82432

Since @hhuijser reverted his changes:

- https://github.com/brianchandotcom/liferay-portal/pull/82424

Hugo's PR causes LPS-106251, LPS-106288, LPS-106245, and LPS-106278. HashMapBuilder didn't allow the `null` parameter. Maybe in the future, if Hugo's change goes back to master, we can talk about how to resolve it together.

/cc @epgarcia @andresfulla @hhuijser @darquesdev

CI passing here https://github.com/dgarciasarai/liferay-portal/pull/140

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@hhuijser fyi

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d2860df864...99c0a6368c

**Comment by brianchandotcom** [comment]
@hhuijser please coordinate with @dgarciasarai .. I actually think we should not allow null in the long run since that is the direction of Maps in general. It would be nice for our MapBuilder to follow the newer conventions.

@dgarciasarai if your changes are "safe", I'd like you to resend it to me, because assuming null is generally a bad idea.

**Comment by brianchandotcom** [comment]
@dgarciasarai basically, calling remove("key") will return null for both the case where the value is null, and where it never existed in the first place. Which is why the Maps in the jdk are moving toward not allowing null.

**Comment by dgarciasarai** [comment]
Hey @brianchandotcom,
First of all thanks for your comments :)
We changed this fast to fix the errors, but since the changes were reverted we decided to revert ours too to find a better solution. For this, we will contact Hugo, explain our use cases and find the best approach. Thanks.

**Comment by hhuijser** [comment]
Hey @dgarciasarai 

Thanks for fixing my mess :)

Not allowing `null` values is something we want to enforce. I have been working on that for a while (checking all the CI logs and catching/fixing NPEs, before making the changes to *MapBuilder), but it seems it wasn't that straightforward as there are a bunch of failing tests where the NPE does not show in the log, so I reverted my changes in the end.

Ideally, we'd fix all the failing tests and recommit the logic in *MapBuilder.
We can talk about how we can do this after the New Year

**Pull request closed without merging**
