### PR TITLE
LPS-66820 SF - add override

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
cc @epgarcia

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@pavel-savinov can you fix the SF error, and also fix the usage of "assetPublisherCustomizer" as a request attribute? Thanks.

**Comment by pavel-savinov** [comment]
@brianchandotcom SF error comes from another bundle, frontend-editor-tinymce-web, which has nothing to deal with changes I made. I'll fix the usage of the attribute and resend. Thanks!

**Pull request closed without merging**
