### PR TITLE
Lps 71722

### PR DESCRIPTION
**Pull request by shuyangzhou**
@brianchandotcom please release a new kernel snapshot after merge. We need that to continue journal side usage applying.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@Preston-Crary can you retest with my changes in https://github.com/Preston-Crary/liferay-portal/pull/293

@shuyangzhou fyi

**Comment by Preston-Crary** [comment]
Retested with your changes, please see https://github.com/brianchandotcom/liferay-portal/pull/48274

**Pull request closed without merging**
