### PR TITLE
LPS-155004 Fixing integration test due to behavior of the log4j library when setting additivity on logger

### PR DESCRIPTION
**Pull request by LuisOrtiz89**
LPS-155004

### CODE REVIEW

**Comment by LuisOrtiz89** [comment]
ci:reopen

**Comment by LuisOrtiz89** [comment]
Failed tests are unrelated

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1fae5b2b07...9210063e65

**Comment by brianchandotcom** [comment]
@LuisOrtiz89 see 9210063e65e222c4ad4cd1f9466af3048e75c858

**Pull request closed without merging**
