### PR TITLE
COMMERCE-584 Show only the ID of the Website

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
https://issues.liferay.com/browse/COMMERCE-584

siteid

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/28e487ab1f...1435df4a90

**Comment by brianchandotcom** [comment]
Nice job @ZoltanTakacs !

**Comment by ZoltanTakacs** [comment]
Thank you! :)

**Pull request closed without merging**
