### PR TITLE
LPS-93221 Move CaptchaFieldType to rest resource

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci: reopen

**Comment by jeyvison** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4abe078ec1...00c8a05d77

**Comment by brianchandotcom** [comment]
@marcelabc @jeyvison @brunofarache Please, please, read my commits in upstream. I was fairly upset that 99bc9abdaeb6495f54ef20af5858002dbf148465 and 680df98e28e1d208870fb222935c94c65a3f009f that were not caught in the review process. The rest, I could understand. But those 2 commits, I could not understand how that got to me.

Marcela, do not be discouraged. This pull had lots of good logic in it, but it was dirty. It is not your fault - the mistakes should have been caught by your team mentors. Please learn from my comments so that the code is cleaner.

Jeyvison, please dig in to other people's code when you are reviewing them. Look at the log and see how much time I spent on this. Why? Because I'm trying to train you to do that for your team.

Bruno, please help Jeyvison. Be kind to him the way I've always been kind to you.

Thanks everyone.

**Pull request closed without merging**
