### PR TITLE
LPS-69211 Move the User file uploads settings UI from Server Administration to System Settings

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-69211](https://issues.liferay.com/browse/LPS-69211).<br><br>/cc @pei-jung @jorgeferrer

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:reopen

**Comment by drewbrokke** [comment]
@brianchandotcom I'll re-send

**Comment by drewbrokke** [comment]
new pr here: https://github.com/brianchandotcom/liferay-portal/pull/46513

**Pull request closed without merging**
