### PR TITLE
LPS-73502 Only clear placeholder for textarea and use String.equals for checking type

### PR DESCRIPTION
**Pull request by robframpton**

### CODE REVIEW

**Comment by Robert-Frampton** [comment]
ci:stop

**Comment by Robert-Frampton** [comment]
ci:restart

**Comment by brianchandotcom** [comment]
ci:retest (retest, not restart)

**Comment by alee8888** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pyoo47 fyi

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/202659393d...ccfb8e83e8

**Comment by brianchandotcom** [comment]
@Robert-Frampton @dustinryerson minor change in ccfb8e83e81c85739c4be03561dc14fb09e97f14

**Pull request closed without merging**
