### PR TITLE
LPS-57861 fix UI in search portlet

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @ealonso fyi

**Comment by brianchandotcom** [comment]
@juliocamarero I merged this in, but I"m pretty sure Nate would not have called it:

```
var publicPages = $('#<portlet:namespace />publicLayoutSetPrototypeId');
var privatePages = $('#<portlet:namespace />privateLayoutSetPrototypeId');

```

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e9015211a8...6af73827d7

**Comment by juliocamarero** [comment]
@brianchandotcom I didn't write any code! Just cut and paste :)

**Comment by juliocamarero** [comment]
@ZoltanTakacs can we please backport this? thank you!

**Pull request closed without merging**
