### PR TITLE
LPS-85709 forms api changes

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
The failing test is fixed here: https://github.com/brianchandotcom/liferay-portal/pull/63507

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/baf06ab8c9...03e288cc4f

**Pull request closed without merging**
