### PR TITLE
Commerce 1079

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/321590b328...978707f631

**Comment by brianchandotcom** [comment]
@shuyangzhou @ethanbustad please review my changes in my origin.. I sorted a bunch of stuff

**Comment by ethanbustad** [comment]
@brianchandotcom alright, I'm pretty sure some of those sorts will cause failures -- [this one](https://github.com/liferay/liferay-portal/commit/38f33d6d97bf4e8a6aeca0dfeab1e503d014dc01) will, and the other two might. We'll try to test it out and see

**Pull request closed without merging**
