### PR TITLE
LPS-77343

### PR DESCRIPTION
**Pull request by Ithildir**
Hi @brianchandotcom,
Please don't publish this plugin yet, @gamerson and I are still working on it. Thanks!

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:test

**Comment by Ithildir** [comment]
ci:test

**Comment by pyoo47** [comment]
ci:test

**Comment by pyoo47** [comment]
ci:test (Bad slave caused the previous test to abort)

**Comment by brianchandotcom** [comment]
@codyhoag fyi.

**Pull request closed without merging**
