### PR TITLE
LRQA-28701 Remove unneeded properties

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRQA-28701

@brianchandotcom - There are no additional properties that are needed within 'liferay-jenkins-ee'.

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
@shuyangzhou - we moved the autoclose list to jenkins, so if you need to add more let us know.

thanks!

**Comment by shuyangzhou** [comment]
Why did we move it? It is more flexible to keep stuff like this in portal codebase, where developers can tweak when needed.

**Comment by michaelhashimoto** [comment]
@shuyangzhou - here's a ticket to potentially move it back to portal:
https://issues.liferay.com/browse/LRQA-28711

**Comment by shuyangzhou** [comment]
Thanks @michaelhashimoto !

**Comment by michaelhashimoto** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bd7816a15a...e39f22b6e8

**Pull request closed without merging**
