### PR TITLE
LPS-75323 Update changelog

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/693eb2aac0...8d2b6e2054

**Comment by brianchandotcom** [comment]
@Ithildir any way my script to upload/publish the jars can auto update this changelog? Saves you from sending me these pulls since it's a script you run anyways right?

**Comment by Ithildir** [comment]
I think it's possible but not very easy, especially when you bundle multiple changes into a single release. I didn't want to spend a lot of time working on it, but I can think about it and see if I can come up with something simple.

**Pull request closed without merging**
