### PR TITLE
LPS-98031 Use common asset selector instead of mapping panel template

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
Hi @brianchandotcom,
This pull has no conflicts with your origin, I just had to cherry-pick my previous commits once again, because you merged them and reverted them yesterday. Now it is ok, rebased with liferay/master.

Thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/89c081f67e...4dd1efaf4e

**Comment by brianchandotcom** [comment]
lbm:backport @CsabaTurcsan @jpince @zsoltbalogh

@pavel-savinov please backport to 7.2.x

**Comment by brianchandotcom** [comment]
@pavel-savinov backport the dependency as well, 
```
Error in plugin 'metal-tools-soy'
Message:
    Compile error:
errors during Soy compilation
src/main/resources/META-INF/resources/js/components/floating_toolbar/link/FloatingToolbarLinkPanel.soy:185: error: Undefined template 'com.liferay.layout.content.page.editor.web.AssetSelector.render'.
			{call com.liferay.layout.content.page.editor.web.AssetSelector.render}
   ^
1 error
```
Don't just fork it to make it work in 7.2.x. Whatever is missing in 7.2, bring it back from master. Thx!

**Pull request closed without merging**
