### PR TITLE
LPS-56124 Revert test changes from LPS-55246

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Hey @akosthurzo could you please submit your test when you have a chance to confirm this fixes your issue?

**Comment by juliocamarero** [comment]
Hey @shuyangzhou can you please confirm this looks good to you? I wonder if this could have any impact in performance.

thank you!

**Comment by juliocamarero** [comment]
cc @Preston-Crary

**Comment by shuyangzhou** [comment]
This looks very heavy, please hold off on it. Send the pull to @dante.wang first to run through our performance regression tests.

**Comment by juliocamarero** [comment]
ok, sent: https://github.com/dantewang/liferay-portal/pull/90

**Comment by shuyangzhou** [comment]
@dantewang, start an email thread to show us all test cases' results, once you get them. It is an aop change, will affact all test cases.

**Pull request closed without merging**
