### PR TITLE
LPS-82491 update changelog and readme

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
hey @brianchandotcom  could you review while Andrea is gone? He already gave his review here:

https://github.com/Ithildir/liferay-portal/pull/1061

**Comment by gamerson** [comment]
And could you please publish these?

`gradle-plugins-target-platform`
`gradle-plugins-workspace`

Thanks

**Comment by brianchandotcom** [comment]
@gamerson can you resend it to @Ithildir to send to me? It'll end up being about 10 days from now, but I'd rather wait unless this is very pressing. Thx!

**Comment by gamerson** [comment]
hey @brianchandotcom , this is not pressing,this can wait for Andrea.  However, we do have some pressing changes needed for BOM changes that happened during release, so we will need your help this week to push those.

Thx

**Pull request closed without merging**
