### PR TITLE
LPS-171491 baseline

### PR DESCRIPTION
**Pull request by ealonso**
No unique failures please see: https://github.com/liferay-lima/liferay-portal/pull/3872#issuecomment-1364501763

From original pr

## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-171491)

Remove old TrashService from portal-kernel and portal-impl

## Proposed solution

In order to remove old TrashService move related logic from portal-kernel and portal-impl to wrapper classes. Also create some necessary methods to make it possible.

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9696f40d48...6c6955587d

**Comment by brianchandotcom** [comment]
Very nice @ealonso just 50d7838c812123e4fbb0a05366d34c1d68618c63

Merry Christmas!

**Comment by ealonso** [comment]
@brianchandotcom Merry Christmas! 🎄

**Pull request closed without merging**
