### PR TITLE
LPS-144799, LPS-145202 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-144799
https://issues.liferay.com/browse/LPS-145202

This is only for master.

@lfbesada
@sandrodw3

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure task is unrelated to this PR.
See
✔️ ci:test:stable - 11 out of 11 jobs passed
❌ ci:test:relevant - 30 out of 34 jobs passed in 2 hours 11 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2453a86489...229ee37878

**Comment by brianchandotcom** [comment]
Looks good. Thank you @lfbesada @sandrodw3

**Pull request closed without merging**
