### PR TITLE
LPS-127005 Followup

### PR DESCRIPTION
**Pull request by csierra**
tested here: https://github.com/liferay-appsec/liferay-portal/pull/240 failures are unrelated

### CODE REVIEW

**Comment by csierra** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/183d79bcfc...0ef5359612

**Comment by brianchandotcom** [comment]
@csierra see 0ef5359612dbb2e1400d3966fc242fe9e37e75d2

I just wan't sure why it was | vs. ||

So I'm fine with || since that's more commonly used.

**Comment by brianchandotcom** [comment]
@csierra I also backported this to 7.3.x, 7.2.x, and 7.1.x.

**Pull request closed without merging**
