### PR TITLE
LPS-71394 | master

### PR DESCRIPTION
**Pull request by vicnate5**
@diogo-lins @thiago-rocha @leoadb

### CODE REVIEW

**Comment by leoadb** [comment]
ci:retest

**Comment by pedroqueiroz94** [comment]
ci:reopen

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fb163ed19a...dc561fe6a9

**Pull request closed without merging**
