### PR TITLE
LPS-99379 Clear search input when user clicks on clean

### PR DESCRIPTION
**Pull request by brunofarache**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d1a26942a8...f1cc206b03

**Comment by jpince** [comment]
@brunofarache @alexcandidos SF failure? Not sure if it's related to this pull or in upstream.

**Comment by brunofarache** [comment]
@jpince could be related but can't reproduce locally.

@jbalsas @wincent any idea about what might be wrong here? I ran:

`liferay-npm-scripts check --production false`

And runs successfully.

**Comment by jbalsas** [comment]
Hey @brunofarache, there was a SF error in https://github.com/brianchandotcom/liferay-portal/pull/76874/files#diff-db028f68edce06d898767d3c59d89f5eR45

```
  45:31  error  Expected object keys to be in natural ascending order. 'isLoading' should be before 'type'  sort-keys
```

You were running locally but we had push the update earlier in the day, so you were still running on old rules.

Some other were also merged upstream as @jpince points out. I'll send a followup asap

**Comment by wincent** [comment]
@jbalsas: A related question though is why didn't we see any error output from the source-format job in CI:

     [exec] Prettier checked 13 files
     [exec] 
     [exec] FAILURE: Build failed with an exception.

I would have expected to see some output there before `FAILURE`. Running locally on this commit, I *do* see the output:

```
yarn run v1.17.3
$ liferay-npm-scripts check
Prettier checked 1547 files

/Users/greghurrell/code/portal/liferay-portal/modules/apps/app-builder/app-builder-web/src/main/resources/META-INF/resources/js/components/list-view/ListView.es.js
  45:31  error  Expected object keys to be in natural ascending order. 'isLoading' should be before 'type'  sort-keys

✖ 1 problem (1 error, 0 warnings)

ESLint checked 641 files, found 1 error, found 0 warnings
1 of 2 jobs failed
error Command failed with exit code 1.
```

I was wondering whether this might be a stdout vs stderr thing in CI, but I just checked and confirmed that the script only outputs to stdout, not to stderr (ie. it is not the case that one of the streams is being filtered: it just looks like stdout is getting truncated in CI).

**Comment by jbalsas** [comment]
Followup PR sent to https://github.com/brianchandotcom/liferay-portal/pull/76890

@petershin, @john-co, the output for the task seems to be cut off, which makes it hard to understand on PRs... could you take a look to see if we could provide a longer output for this task?

**Comment by petershin** [comment]
@jbalsas - I ran a test ([liferay-portal/pull/631](https://github.com/petershin/liferay-portal/pull/631#issuecomment-520848594)) and it seems to work the way @wincent mentioned.

If possible, please send me a pull that reproduces this issue on CI.  I tried to use the changes in this pull, but the SF test passed.  See [liferay-portal/pull/632](https://github.com/petershin/liferay-portal/pull/632)

**Comment by john-co** [comment]
Hi @petershin, I ran test https://github.com/john-co/liferay-portal/pull/156/ and reproduced the undesired SF output. 

I'm not able to directly push to you since I had to resolve some conflicts on the branch.

cc/ @hhuijser maybe you could provide some insight?

**Pull request closed without merging**
