### PR TITLE
LPS-72118 Wordsmith

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by pyoo47** [comment]
Not going to retest this one.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by yuhai** [comment]
ci:reopen

**Comment by yuhai** [comment]
ci:retest

**Comment by jpince** [comment]
@yuhai @jbalsas the semver issue is real, please resolve.
```
     [exec] :apps:foundation:frontend-taglib:frontend-taglib:baseline
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] [Baseline Warning] Bundle Version Change Recommended: 2.3.0
```
Closing this pull.

**Comment by jpince** [comment]
ci:close

**Comment by jpince** [comment]
@hhuijser SF failures above are not consistent, SF looks like it's asking for a newline at the end of the file, but it's a different file in each run (and I'm pretty sure we don't put a newline at the end of the file). Can you please take a look at this?

**Comment by jbalsas** [comment]
Thanks @jpince, I thought we had avoided those... @dacousalr, can you double check?

**Comment by hhuijser** [comment]
@jpince is this the only pull we are having this issue?

**Comment by hhuijser** [comment]
Just looking at the changed files on this pull and it does like there were a bunch of newlines (accidentally?) added: https://github.com/brianchandotcom/liferay-portal/pull/49107/files

**Comment by jpince** [comment]
oh, maybe it fails on a different file because that's what it finds first. I do see the newlines that were, as you said, probably unintentionally added. Thanks!

**Comment by hhuijser** [comment]
@jpince, correct. When SF throws a SourceMismatchException, we only show the first file that had issues. (so we don't clutter the log when we have lots of violations). Since SF uses threading, the order of files being processed by SF is inconsistent.

**Pull request closed without merging**
