### PR TITLE
LPS-88164 Add create/update test

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Please rename getDateModified to getModifiedDate, and getDateCreated to getCreatedDate and resend. Thx.

**Comment by brianchandotcom** [comment]
@victorg1991 in general, for classes like Date, I try to make the var names xyzDate, abcDate.

I generally don't do this for primitives or Lists/Collections, but I do it for Dates and other more complext objects. Thx.

**Comment by victorg1991** [comment]
@brianchandotcom got it, I'll send a new one, thanks!

**Pull request closed without merging**
