### PR TITLE
LPS-83949 SF

### PR DESCRIPTION
**Pull request by izaera**
@brianchandotcom this one is related to https://github.com/brianchandotcom/liferay-portal/pull/68872 but both can be merged independently

### CODE REVIEW

**Comment by izaera** [comment]
ci:test

**Comment by izaera** [comment]
ci:reopen

**Comment by izaera** [comment]
@brianchandotcom  Relevant failed because of infrastructure issues. The complete CI suite has failed for other reasons, but I doubt they have something to do with URLs since I'm only renaming things.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9ac3269ba5...9ad421335e

**Comment by brianchandotcom** [comment]
Nice.. thanks for breaking it up like this.

**Pull request closed without merging**
