### PR TITLE
LPS-65362

### PR DESCRIPTION
**Pull request by Ithildir**
Hi!
I guess I should also remove the `web` from the packages `com.liferay.frontend.taglib.web.*`... but I don't know if it's a (major?) change we want to do now.

cc @hhuijser

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/91e5df3e41...05e824177f

**Comment by brianchandotcom** [comment]
@Ithildir I might deprecate the package :( then it won't be a major release.

**Comment by brianchandotcom** [comment]
@Ithildir or just pay the cost and release it again.... as major.

**Pull request closed without merging**
