### PR TITLE
LPS-79971 SF

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @yasuflatland-lf

**Comment by sergiogonzalez** [comment]
ci:test

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@sergiogonzalez see 68dd2786dd9cf07bb8fbaa85bb348abba47bb37c

@austinchiang please send me the fixes asap. This is already upstream. Thx.

**Pull request closed without merging**
