### PR TITLE
LPS-178557 fix Headless client fails when receiving an HTML

### PR DESCRIPTION
**Pull request by albertojml**
**What's new:**
- Added to HttpResponse class (located in HTTPInvoker.java) a _contentType parameter and it's respective setter and getter.
- Added to client_resource.ftl a condition that checks the response Content-Type to prevent the client from crashing when recieving an HTML response.
- Executed buildREST on /module/apps 
- Jira ticket: https://issues.liferay.com/browse/LPS-178557

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3cb5998872...e2a7523e50

**Comment by brianchandotcom** [comment]
@jalber786 @sergiojimcos see 1618db41 fa9b9592 9dc767e2 63356cb0 and 77be409a

**Comment by brianchandotcom** [comment]
@jalber786 @sergiojimcos see 1618db41 fa9b9592 9dc767e2 63356cb0 and 77be409a (with correct links this time)

**Pull request closed without merging**
