### PR TITLE
LPS-139131 If the service is unregistered due to bundle stopping, the…

### PR DESCRIPTION
**Pull request by shuyangzhou**
… BundleContext is expected to be invalid.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b90fb90241...ec079fd543

**Comment by brianchandotcom** [comment]
@shuyangzhou can we add a test for this? it'd be good to show how to test it so that @izaera can learn from it too

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/107631

**Pull request closed without merging**
