### PR TITLE
Lps 63495

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @Ithildir

Turns out this is a CI infrastructure issue, there is some instability of the network drive.

Under frequent write (The theme has too many image folders, each one becomes a sprite image that needs to write), the mounted drive will become unaccessable for a short period of time, probably due to some network syncing delay.

There is nothing at code level that I can fix for the network drive. I can only simply redirect it to a different location that is on local drive.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/200d312364...f72de9c506

**Comment by brianchandotcom** [comment]
@jorgeferrer new theme is in.. fyi

**Comment by alee8888** [comment]
@vicnate5 can you take a look at the failing calendar test? It looks to be a fluke as I didn't see them fail in subsequent PRs.

**Comment by JorgeFerrer** [comment]
Awesome, thanks a lot @brianchandotcom

**Pull request closed without merging**
