### PR TITLE
master-qa-20324

### PR DESCRIPTION
**Pull request by michaelhashimoto**
http://issues.liferay.com/browse/LRQA-20324

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest (just borrowing this pull to test master). I wanted to chat with Kevin and Hashi before merging this in.

**Comment by brianchandotcom** [comment]
@kevin-yen @michaelhashimoto please resend. See LPS-55691. We have a com.liferay.ant.build.logger that looks very similar to your com.liferay.ant.logger.

**Pull request closed without merging**
