### PR TITLE
7.0.x-qa-28033

### PR DESCRIPTION
**Pull request by vicnate5**
Backport of https://github.com/brianchandotcom/liferay-portal/pull/44380

### CODE REVIEW

**Comment by brianchiu** [comment]
@vicnate5 
Source formatter error.

```
org.junit.ComparisonFailure: ../../../portal-web/test/functional/com/liferay/portalweb/macros/ee/ReportsAdmin.macro expected:<...	<command name="view[DefinitionParameterFields">
		<execute function="AssertElementPresent" locator1="ReportsAdminEditReportDefinition#REPORT_DEFINITION_PARAMETERS_KEY" />
		<execute function="AssertElementPresent" locator1="ReportsAdminEditReportDefinition#REPORT_DEFINITION_PARAMETERS_VALUE" />
		<execute function="AssertElementPresent" locator1="ReportsAdminEditReportDefinition#REPORT_DEFINITION_PARAMETERS_TYPE" />
	</command>

	<command name="viewNoReportEntryFile">
		<var name="key_reportsFileName" value="${reportsFileName}" />

		<execute function="AssertElementNotPresent" locator1="ReportsAdminViewReportEntry#ENTRY_FILE_TABLE_FILE" />
	</command>

	<command name="viewReportEntry">
		<var name="key_reportsDefinitionName" value="${reportsDefinitionName}" />

		<execute function="AssertClick" locator1="ReportsAdmin#REPORTS_ENTRY_TABLE_DEFINITION_NAME" value1="${reportsDefinitionName}]" />
	</command>

	<...> but was:<...	<command name="view[NoReportEntryFile">
		<var name="key_reportsFileName" value="${reportsFileName}" />

		<execute function="AssertElementNotPresent" locator1="ReportsAdminViewReportEntry#ENTRY_FILE_TABLE_FILE" />
	</command>

	<command name="viewReportEntry">
		<var name="key_reportsDefinitionName" value="${reportsDefinitionName}" />

		<execute function="AssertClick" locator1="ReportsAdmin#REPORTS_ENTRY_TABLE_DEFINITION_NAME" value1="${reportsDefinitionName}" />
	</command>

	<command name="viewDefinitionParameterFields">
		<execute function="AssertElementPresent" locator1="ReportsAdminEditReportDefinition#REPORT_DEFINITION_PARAMETERS_KEY" />
		<execute function="AssertElementPresent" locator1="ReportsAdminEditReportDefinition#REPORT_DEFINITION_PARAMETERS_VALUE" />
		<execute function="AssertElementPresent" locator1="ReportsAdminEditReportDefinition#REPORT_DEFINITION_PARAMETERS_TYPE]" />
	</command>

	<...>
```

**Comment by brianchiu** [comment]
ci:close

**Comment by brianchiu** [comment]
@vicnate5 
I resent them with a format source here:
https://github.com/brianchandotcom/liferay-portal/pull/44393
https://github.com/brianchandotcom/liferay-portal/pull/44394

**Comment by vicnate5** [comment]
Thanks for taking care of this @brianchiu

**Pull request closed without merging**
