### PR TITLE
LPS-99884 AB Testing

### PR DESCRIPTION
**Pull request by darquesdev**
@dgarciasarai @epgarcia @andresfulla

### CODE REVIEW

**Comment by darquesdev** [comment]
Hi @brianchandotcom, could you please review? It is blocking a couple of PR. Let me know if it requires some change. Sorry for being that insistent but It would be great if it gets merged for next week.

Thanks in advance!

**Comment by darquesdev** [comment]
please, mention @dgarciasarai

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
@brianchandotcom Thanks for the feedback. I'll send a follow up PR with the changes.

**Pull request closed without merging**
