### PR TITLE
LPS-102427 Set PropsKeys.SCHEDULER_ENABLED to True because of the restriction imposed here https://github.com/liferay/liferay-portal/blob/9ccf657b00c67feee6977ebb1f29a1b74124ba71/portal-test/src/com/liferay/portal/kernel/test/rule/SynchronousDestinationTestRule.java#L153, some cases the tests are running asynchronously causing failures.

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@shuyangzhou can someone from your team look at this? not sure if this hack is right. Thx.

**Comment by shuyangzhou** [comment]
@tinatian please take this over, thanks!

**Comment by xbrianlee** [comment]
@inacionery @barrosdennys I revised the ticket to reflect the issue that should be resolved. The issue in LPS-102250 is NLR.

**Comment by inacionery** [comment]
Forwarded to https://github.com/tinatian/liferay-portal/pull/1529

**Pull request closed without merging**
