### PR TITLE
LPS-99334 Regen

### PR DESCRIPTION
**Pull request by darquesdev**

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6a8911c9c7...e801b1d257

**Comment by brianchandotcom** [comment]
@darquesdev see e801b1d

**Pull request closed without merging**
