### PR TITLE
LPS-59462

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
@brianchandotcom the log says there are build service changes but I've committed everything. Do you know maybe what can be the problem?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/81f0adbc18...002f265c88

**Comment by brianchandotcom** [comment]
@matethurzo 

The CI will first go to modules/util/portal-tools-service-builder and run "gradlew deploy". This will ensure the latest SB is being used.

Then it will regenerate, and if it sees any files other than "service.properties" modified, it fails the pull.

So I went ahead and deployed the latest service builder (and published it) and then regenerated.

The culprit for why CI failed was fixed in 008337151edb0324d785f57faadbabd80dfa1a02

**Comment by matethurzo** [comment]
Thank for the the help @brianchandotcom!

**Pull request closed without merging**
