### PR TITLE
LPS-53547 Autogenerated

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @brianwulbern,

I cannot reproduce the smoke test manually, Could you help me?

It seems to be the same smoke test that we have in the other pull: https://github.com/brianchandotcom/liferay-portal/pull/30249

Thanks,
Eudaldo.

**Comment by brianwulbern** [comment]
@ealonso @juliocamarero, Trying to make it wait longer in this pull: https://github.com/brianchiu/liferay-portal/pull/739

@brianchiu can push it to BChan, if it passes...we've been having intermittent timeout failures waiting for WC to load recently.

**Comment by brianchiu** [comment]
@ealonso @juliocamarero @brianwulbern 

I've already sent a pull to increase the wait. I only applied it to the smoke test because we don't see it happen on any other tests. Joel and Shuyang also have suspicions that this is happening because the VMs are maxing out on memory.
https://github.com/brianchandotcom/liferay-portal/pull/30242

**Comment by brianchiu** [comment]
@brianchandotcom 
Can you hold off on closing this pull? I'd want to run a retest on it after https://github.com/brianchandotcom/liferay-portal/pull/30242 gets in.

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@brianwulbern 
Can you keep an eye on this?

**Comment by brianchiu** [comment]
yay!

**Comment by brianwulbern** [comment]
:+1:

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/db164e70a5...c2019056ec

**Pull request closed without merging**
