### PR TITLE
LPS-121988 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-121988

This is only for master.

@jkappler

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure case is not related to changes in PR.
See https://github.com/liferay-echo/liferay-portal/pull/2621
✔️ ci:test:stable - 14 out of 14 jobs passed
❌ ci:test:relevant - 54 out of 56 jobs passed in 1 hour 40 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/871a4103d0...4aa21b17b6

**Comment by brianchandotcom** [comment]
@Tim-Cao @jkappler I backported this to 7.3.x too

**Pull request closed without merging**
