### PR TITLE
LPS-106127 If the field has a itemSelectorURL use it

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @brianchandotcom, `stable` seems to be not stable right now :(

@john-co, @jpince, @manoelcyreno, could you please check these 2 different results:
[✔️ ci:test:stable - 9 out of 9 jobs passed in 1 hour 2 minutes 59 seconds 773 ms](https://github.com/jbalsas/liferay-portal/pull/2072#issuecomment-569120448)
[❌ ci:test:stable - 7 out of 8 jobs passed](https://github.com/jbalsas/liferay-portal/pull/2072#issuecomment-569122908)

First one is from a direct `ci:test:stable` invocation. Second one comes from a `ci:test:relevant` call.

**Comment by jpince** [comment]
@jbalsas summary: the code is fine, this is due to a CI limitation. I will try to explain it below, let me know if you'd like a short call to explain more (I work Mon, Thur, Fri this week and next).

When you run `ci:test:relevant`, CI will also report on `ci:test:stable` _based on the results from `ci:test:relevant`_ (CI does _not_ start a separate test run for `ci:test:stable`). This works out well for batches like smoke, because they just run one test. But for batches like `modules-integration-*`, CI doesn't know which individual tests are a part of stable - it can only report the test results for the entire batch. `OpenGraphTopHeadDynamicIncludeTest` runs in `ci:test:relevant` because it exists within `modules/apps/layout` and this PR makes changes to that app. Those tests are also currently failing in upstream. Thus, the failures display under `ci:test:stable` results. It's not ideal, but that's how it currently works.

@manoelcyreno please contact whoever needs to fix or ignore this test class so other teams aren't affected in this way :).

@yichenroy @pyoo47 example of confusion caused by the CI limitation.

**Comment by jbalsas** [comment]
@jpince can we reopen this, then? Or are we stuck until CI gets fixed?

**Comment by jpince** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/125b0703f1...7fb53b1c03

**Pull request closed without merging**
