### PR TITLE
LRQA-65549 | Quarantines flaky test CPCommerceChannels#CreateNewNotificationTemplate

### PR DESCRIPTION
**Pull request by john-co**
**Description**
Quarantines flaky test CPCommerceChannels#CreateNewNotificationTemplate

**JIRA ticket**
https://issues.liferay.com/browse/LRQA-65549

### CODE REVIEW

**Comment by john-co** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ba4712b3ce...1db5c1ecd8

**Comment by marco-leo** [comment]
Hey @john-co @brianchandotcom that is not a flaky tests it is actually a real bug.  @andrea-ale-sbarra please revert this commit and ensure it all is ok.  @john-co please rich out Commerce QA before quarantine tests or at least notify  on p-commerce channel or via a jira ticket, so they can actually look on it

**Comment by john-co** [comment]
Hi @marco-leo , whether it is flaky or a real bug, something should be done with the test so that it will be excluded from `ci:test:relevant` so it doesn't affect other team's PRs. I've identified the test as flaky since it failed 35 out of the last ~200 tests [here](https://github.com/liferay-frontend/liferay-portal/pull/839#issuecomment-789985625). We can't let tests that are expected to fail continue to be run in acceptance affecting other cross-cutting teams for 2 weeks. I had mentioned the issue to @lorenzolapescara [here](https://github.com/liferay-frontend/liferay-portal/pull/839#issuecomment-789983359).

If it's a real bug then the test QA usually recommends the test be disabled/ignored so it doesn't run at all until the issue is fixed. I usually leave that up to the team that owns the test. On the other hand, quarantining the test still allows the test to run on a daily routine and can be monitored by QA, while it unblocks the affected team with `ci:forward` process.

cc/ @iovaneale

**Pull request closed without merging**
