### PR TITLE
LPS-77769 Publication fails when image is defined in the component structure and content is modified

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by jkappler** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@shuyangzhou I've seen this Concurrent Counter test error a few times now fyi.

**Comment by shuyangzhou** [comment]
@brianchandotcom they are Oracle database failed to start, it is env issue. QA or IT should take a look.

**Pull request closed without merging**
