### PR TITLE
LPS-70914 NPE is thrown when deactivate user signing in

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-70914](https://issues.liferay.com/browse/LPS-70914).<br><br>Hey Brian, this is a quick NPE check.  I believe this maintains the behavior introduced in https://issues.liferay.com/browse/LPS-70765.<br><br>/cc @shuyangzhou @pei-jung @sheltonz

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by shuyangzhou** [comment]
@drewbrokke Thanks, I was making the same change :)

**Pull request closed without merging**
