### PR TITLE
LPS-162975 let the user know about the sort action in sortable columns

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by crodriguezy** [comment]
ci:reopen

**Comment by crodriguezy** [comment]
coming from https://github.com/liferay-frontend/liferay-portal/pull/2767

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cde69b88e8...af6e4cf335

**Comment by brianchandotcom** [comment]
@crodriguezy @jcampoy just a78e5c57ac71dd8eb567930765cedc392e418014 thx

**Pull request closed without merging**
