### PR TITLE
LPS-94325 Keep the same namespace for fragment entry links in staging/export-import

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/73459f8adf...bb4a8b7943

**Comment by brianchandotcom** [comment]
@pavel-savinov can you deprecate all the other addFragmentEntryLink methods? I think only the big one is used right?

**Pull request closed without merging**
