### PR TITLE
COMMERCE-10657

### PR DESCRIPTION
**Pull request by brianikim**
Resent from: https://github.com/brianchandotcom/liferay-portal/pull/129453#event-8402135193

Exact same PR except correct naming as requested by @brianchandotcom : https://github.com/brianchandotcom/liferay-portal/pull/129453#issuecomment-1410784555

### CODE REVIEW

**Comment by brianikim** [comment]
ci:reopen

**Comment by brianikim** [comment]
@brianchandotcom , I am sending you this PR directly since the change requested was a simple name change. The forwarded test results should still be valid.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8f9984181d...fe66b60dfb

**Comment by brianchandotcom** [comment]
@brianikim see fe66b60dfb479e4bd8428c8bf9eb06d16116a157

**Pull request closed without merging**
