### PR TITLE
master-sc-873

### PR DESCRIPTION
**Pull request by sharonchoi**
https://issues.liferay.com/browse/LRQA-27530

### CODE REVIEW

**Comment by vicnate5** [comment]
Thanks so much @sharonchoi!

**Comment by brianchandotcom** [comment]
1.) Forms SF issue.

portal-web/test/functional/com/liferay/portalweb/tests/enduser/webformsanddatalists/forms/Forms.testcase2

2.) modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-type-checkbox-multiple/portal.build

Please rename that stale file.

3.) modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/internal/upgrade/v1_0_2/UpgradeCheckboxFieldToCheckboxMultipleField.java

If you have a ps2, please rename ps to ps1.

Please resend. Thx.

**Comment by marcellustavares** [comment]
cc @ctampoya, @sharonchoi

**Comment by ctampoya** [comment]
cc @vicnate5

**Comment by ctampoya** [comment]
@marcellustavares I can fix the Forms.testcase SF. Can you take a look at the other 2?

**Comment by ctampoya** [comment]
Sent to https://github.com/marcellustavares/liferay-portal/pull/1597

**Pull request closed without merging**
