### PR TITLE
LPS-53998

### PR DESCRIPTION
**Pull request by gamerson**
I'm working on a companion PR that I'm working on for maven over here: https://github.com/liferay/liferay-maven-support/compare/master...gamerson:MAVEN-139

Its not ready there yet but I have tried it out enough to know that the changes here in portal are working as expected, at least for ServiceBuilder and LangBuilder.

### CODE REVIEW

**Comment by gamerson** [comment]
ci:retest

**Comment by gamerson** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
I'm not sure we need this Greg?

Why don't we just use failonerror="false" or use the try catch tasks? http://ant-contrib.sourceforge.net/tasks/tasks/trycatch.html

It also seems like it should be part of the tooling's Java executor. You could have that thread change System.out to something else, hold all the output, etc.

**Comment by gamerson** [comment]
Hey Brian,

The main reason I need this is so that when IDE executes
liferay-maven-plugin goals like "build-service" or "build-wsdd" we can
capture the exception if any are thrown by ServiceBuilder or WSDDBuilder.
Right now there is no way to capture them since all the *Builders catch all
exceptions.  However, I could look into redirecting System.out and
System.err and then parsing the output for stacktraces.  It just seems so
much more straight forward and simple to allow the *Builders to throw the
exceptions when requested.  So I added the argument parsing so that by
default the behavior would be the same as it always is, and just for
liferay-maven-plugin executions we could pass in the additional argument
for throwing exceptions.  All other invocations would be same behavior as
before.

On Sat, Mar 7, 2015 at 5:50 AM, Brian Chan <notifications@github.com> wrote:

> Closed #24579
> <https://github.com/brianchandotcom/liferay-portal/pull/24579>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/24579#event-247814957>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by brianchandotcom** [comment]
I see... reviewing again..

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/88f78dabf5...f1c99059d1

**Pull request closed without merging**
