### PR TITLE
Lps 89637

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@david-truong @mhan810 this is the new AOP support for SB. And Blogs has been applied as example(Blogs is spring-free now).
We are technically done with aop refactor now. Except we need to spend more time to globally apply it to all SB modules, there are manual changes required to update exist code.

@brianchandotcom wants us to still leave a couple spring based ones just to make sure we are testing its support properly. But future SB modules (up to the owners)and most exist ones (we will take care of them)should be migrated to this new solution.

Another less important pending task is, pulling advices from portal to modules. As for now we don't really see a need for it, we will defer this task and to focus on the usage apply and GraphQL stuff.

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
@adolfopa @4lejandrito I believe you guys own Blogs now, right? If not, please help me at the right person, thanks!

**Comment by 4lejandrito** [comment]
Hi @shuyangzhou,

Yes, we own blogs. We will look into this on Monday. Let us know if you need anything on our side.

Regards

**Comment by mhan810** [comment]
@shuyangzhou moving the aop impl out of portal-impl would primarily help us from a bug fixing and future release perspective.  We haven't had to adjust those AOP impl in a long time so I think we should be ok.

For applying the new AOP, I would prioritize it by product area.  For instance, if we want to take all of workflow and forms or WEM this release.  It's tech debt we need to pay at some point but is it something we must pay before May?

I'd like to deal with the GraphQL but probably just as important, improve our integration testing perf (e.g. rip or update arquillian, etc)

**Comment by shuyangzhou** [comment]
@mhan810 applying new aop imp is not really required, as we are still supporting the spring way and planning to keep it for a long time. It is only necessary to apply a bit more to make sure we are really using it in production and we can ensure its coverage. Besides that, globally applying it open a new chance for us to optimize startup performance, that's something Brian prefers. But yeah, we don't have to do them all before May, if we don't have enough time. When we do we will select them by production area.

We are currently already doing graphql and arquillian removal concurrently, so they won't bother each other too much. And although we are still far away from replacing out arquillian, due to the already done cleanup, our integration tests are already faster than before (there is a lot more we can do, after replacing it out) and more stable.

**Comment by brianchandotcom** [comment]
@Preston-Crary 

1.) PersistenceDSConstants vs. PersistenceConstants (

```

	private void _createPersistenceDSConstants() throws Exception {
		if (!_ds) {
			return;
		}

		File file = new File(
			StringBundler.concat(
				_outputPath, "/service/persistence/impl/constants/",
				_portletShortName, "PersistenceConstants.java"));

```

Rename persistence_ds_*.ftl to persistence_*.ftl

2.) Spell out "ds" in *.ftl (too short, scares me, harder to search and replace, and reminds me of dataSource)

May be dependencyInjectorDS

Can you resend on top of https://github.com/Preston-Crary/liferay-portal/pull/688

**Pull request closed without merging**
