### PR TITLE
LPS-74849

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@brianchandotcom, can you try to cherry pick as much as possible? If you can't cherry pick all commits, I'll do the rest manually, it should not break any tests

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
ci:retest

**Comment by jpince** [comment]
@hhuijser there is a consistent failure. The only piece I found that might be helpful is the following:
`Caused by: org.osgi.framework.BundleException: Unable to resolve com.liferay.portal.configuration.extender [5](R 5.0): missing requirement [com.liferay.portal.configuration.extender [5](R 5.0)] osgi.wiring.package; (osgi.wiring.package=com.liferay.petra.concurrent) Unresolved requirements: [[com.liferay.portal.configuration.extender [5](R 5.0)] osgi.wiring.package; (osgi.wiring.package=com.liferay.petra.concurrent)]`
http://test-1-16/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=9,label_exp=!master/171207//consoleText

@shuyangzhou any ideas?

**Comment by jpince** [comment]
ci:close

**Comment by jpince** [comment]
cc/ @petershin

**Comment by petershin** [comment]
Hi @hhuijser,

It looks like some classes were moved out from portal-kernel to the petra module

I think the fix is to add these lines to build.gradle and test-bnd.bnd for each module you're updating.

```gradle
testLibs group: "com.liferay", name: "com.liferay.petra.concurrent", version: "1.0.0"
testLibs group: "com.liferay", name: "com.liferay.petra.memory", version: "1.0.0"
```

```bnd
@test-lib/com.liferay.petra.concurrent.jar,\
@test-lib/com.liferay.petra.memory.jar,\
```

**Comment by hhuijser** [comment]
@petershin, thanks for figuring that out.
Let's just add it to the module that's failing the test and see what happens

**Pull request closed without merging**
