### PR TITLE
LPS-70371 In https://issues.liferay.com/browse/PTR-14 PR team decided to deprecate CMISStore in DXP 7.0. Changing the message to reflect this.

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
cc/ @almonwork

Hey @brianchandotcom 

I think that the final message didn't reflect the decisions made in https://issues.liferay.com/browse/PTR-14 (deprecate the CMISStore for current version) 

It's a small change that could avoid customer's misunderstanding.

Are you ok with this??

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9c083c537b...375f2d648f

**Comment by brianchandotcom** [comment]
Got it. I didn't understand that part earlier (thx @robertoDiaz )

**Comment by robertoDiaz** [comment]
Thanks @brianchandotcom :)

**Pull request closed without merging**
