### PR TITLE
LPS-72834

### PR DESCRIPTION
**Pull request by JoshuaStClair**
In reference to PR https://github.com/brianchandotcom/liferay-portal/pull/49982, StagingBarPortlet's request.setAttribute's were changed to use [StagingProcessesWebKeys, ](https://github.com/JoshuaStClair/liferay-portal/commit/a39dfa05be7b8985070a3b7b6809aa2a019f4fe4#diff-c2e25e0973f8dae50a598ccd2f67f6f2R27) or [WebKeys](https://github.com/JoshuaStClair/liferay-portal/commit/68b9db370b3ac5d4c7ab140e383c4e924ae623fd#diff-61a5377d82a1e1e054ecf01791e791ddR165) when possible. By updating StagingProcessesWebKeys though, staging-bar-web relied on an updated version of [staging-api](https://github.com/JoshuaStClair/liferay-portal/commit/f4a4b1fcd0ee544715b41a6bbb7f29572c89beca#diff-5fa43ac9c2e7c8a3c13e9af3a0e9cf95L7), so the build.gradle had to be updated in order to deploy correctly.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by JoshuaStClair** [comment]
ci:reopen

**Comment by JoshuaStClair** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/afccd03146...2baeccaa3f

**Pull request closed without merging**
