### PR TITLE
LPS-70066 | master

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
https://issues.liferay.com/browse/LPS-70066

Hi @brianchandotcom,

We've asked Andrea ( @Ithildir ) to help us with creating a new ant target which can be invoked from the repository's root and iterates through on those modules where there was a change in the current branch and runs the baseline gradle task there.

This would be great help for Support Engineers.

If you have any questions, please let us know.

/cc @zsoltbalogh

Thank you,

### CODE REVIEW

**Comment by ZoltanTakacs** [comment]
ci:retest

**Comment by ZoltanTakacs** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Going to compare with https://github.com/brianchandotcom/liferay-portal/pull/46240

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@Ithildir see d422de196f1ddab6322c0dcde3a5ac8ff61fb019

Just a styling preference I've always had to not leave a var undeclared.

**Pull request closed without merging**
