### PR TITLE
LPS-77556 Inline by default everywhere

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test

**Comment by 4lejandrito** [comment]
Depends on https://github.com/brianchandotcom/liferay-portal/pull/56232.

**Comment by brianchandotcom** [comment]
@4lejandrito compile error? see details.

**Comment by 4lejandrito** [comment]
Hi @brianchandotcom,

Those modules did deploy and run correctly but they failed the `compileJsp` task, my bad for not running it. 

This should be fine: https://github.com/brianchandotcom/liferay-portal/pull/56253.

:)

**Pull request closed without merging**
