### PR TITLE
POSHI-258 Fix windows issue and release poshi update

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/POSHI-258 

Tested here: https://github.com/kenjiheigel/liferay-portal/pull/983#issuecomment-1055746460, but unrelated failures. Please publish poshi-core, poshi-runner, gradle-plugin-poshi-runner, and gradle-plugins-defaults after merging, thanks!

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5f3a451390...4f2486f8b7

**Comment by brianchandotcom** [comment]
@kenjiheigel published all.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f486ecbd61...6a36537f13

**Pull request closed without merging**
