### PR TITLE
LPS-54198 Apply new exception pattern to RequiredStructureException

### PR DESCRIPTION
**Pull request by pei-jung**
Hi Brian,

After a deeper look into the code, I realized that we should throw `RequiredFileEntryTypeException` instead of `RequiredStructureException` in `DLFileEntryTypeLocalServiceImpl`. So I removed commits https://github.com/pei-jung/liferay-portal/commit/81e549fb1b5fbd0bf5366a85f79273e923c105e1 and https://github.com/pei-jung/liferay-portal/commit/a8d0b8aacb4b41efa674b55f0559bb20ec674a2f.

/cc @marcellustavares

### CODE REVIEW

**Comment by kiyoshilee** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Very close, but 

MustNotDeleteStructureReferencedByStructureLink

makes me think a structure can only have one structure link, is that on purpose?

MustNotDeleteStructureReferencedByTemplates

makes me think a structure can have more than one template (which makes sense)

yet

the-selected-structure-cannot-be-deleted-because-it-is-required-by-one-or-more-structure-links=The selected structure cannot be deleted because it is required by one or more structure links.

Uses plural.

We need to be very detail oriented and make sure that every character adds information (and not misinformation). So there's a discrepancy I see right now. There may be more. Please review thoroughly.

Thx!

**Comment by pei-jung** [comment]
Resent as https://github.com/brianchandotcom/liferay-portal/pull/24954

**Pull request closed without merging**
