### PR TITLE
Lps 53221

### PR DESCRIPTION
**Pull request by shuyangzhou**
Just moving classes to different packages to prevent osgi split package issues, as we are making both portal-test and portal-test-internal as bundles and going to consume them from modules' integration tests.

There is no logic change in this pull.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
hmm, missed some file in modules, will resend.
Really need to fix the build script for module after this, it is too easy to miss compile some files in modules.

**Comment by shuyangzhou** [comment]
It weird, the error does not make sense, I think I sent this pull too fast that my previous pull was not in upstream yet. Just reopen to try it again.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8b5c4c5a01...bad003bdb5

**Comment by brianchandotcom** [comment]
Hey @shuyangzhou I merged this in, and also gave you push rights to upstream. If this pull is broken, just push a fix to upstream. Thx bro!

**Comment by shuyangzhou** [comment]
Awesome, thanks Brian!

**Comment by shuyangzhou** [comment]
Sorry, it was actually my fault, somehow made the portal-test-internal bnd an empty file, probably did something stupid during the rebase.
Pushed it to upstream https://github.com/liferay/liferay-portal/commit/abe15e35a088b68a1365911ec9b2d7fd53db91f9
Need to sleep now, I trend to make more mistakes while being sleepy :(

Will try to get the prototype ready tomorrow and talk to you.

**Pull request closed without merging**
