### PR TITLE
LPS-182089 The publish-sample-workspace.yaml workflow triggers for all repositories

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-182089](https://issues.liferay.com/browse/LPS-182089).

/cc @gamerson @lawrence-lee

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ec421d0251...1c6d6547fb

**Comment by brianchandotcom** [comment]
@drewbrokke Can I rename this to c7ebb2f9728248ea0991e0f255decf749aeb9ad6 ?

**Comment by drewbrokke** [comment]
Yup you can rename it. Thanks for the heads up.

**Pull request closed without merging**
