### PR TITLE
Lps 69436

### PR DESCRIPTION
**Pull request by shuyangzhou**
@brianchandotcom I am reverting this because it caused a significant performance regression on MB and Blogs, it is so big that we could not even measure how much exactly. 

@jbalsas please readd these and send your follow up fix to @slnn . She can help you make sure the issue is completely solved before sending this back to @brianchandotcom .

CC @ambrinchaudhary @migue @sergiogonzalez @brunobasto @dantewang @tomwang2011

### CODE REVIEW

**Comment by jbalsas** [comment]
We're testing the infrastructure changes in https://github.com/migue/liferay-portal/pull/967. We'll resend through @slnn as soon as those are in.

**Comment by brianchandotcom** [comment]
@pyoo47 why are we checking out 7.0.x? on master?

**Comment by pyoo47** [comment]
@brianchandotcom We need the 7.0.x branch so we can compare the 7.0.x modules to the master modules.

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cfcd2cb373...31d82ac844

**Pull request closed without merging**
