### PR TITLE
Lps 56271

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
CI is hanging on test results publishing...

@michaelhashimoto and @kiyoshilee

**Comment by shuyangzhou** [comment]
ok, not really hanging, but very very slow, NFS is full or down again?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d183a30f6b...9133888e40

**Comment by kiyoshilee** [comment]
@shuyangzhou looking at the pull requests that tested around it, this pull request did take longer than the others, however all the more recent pulls on this server took about 40 minutes. I'm guessing that there may have been a queue on the server when your pull was triggered, but I can't know for certain without having seeing it at the time. We'll keep an eye out for things like this though.

**Pull request closed without merging**
