### PR TITLE
LPS-75876 Use CKEditor webjar instead

### PR DESCRIPTION
**Pull request by Ithildir**
cc @jonmak08

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:test

**Comment by jonmak08** [comment]
Something went wrong with the webjar.  I will need to push up a new one since the current one is 7MBs.

**Comment by jonmak08** [comment]
ci:close

**Comment by Ithildir** [comment]
@jonmak08, I compared the jars before and after this change, but I didn't see any difference, apart from the encoding of the `.js` files. True, the webjar contains way more stuff that I had to exclude via Gradle, but the end result looks fine IMHO. Can you please double-check?

Thanks!

**Comment by jonmak08** [comment]
Hey @Ithildir,

The size difference was on the webjar that I pushed up to maven.  You can see my tests at https://repository.liferay.com/nexus/content/repositories/liferay-public-snapshots/com/liferay/webjars/com.liferay.webjars.ckeditor/4.6.0-SNAPSHOT/.  The ones I was pushing originally were 7MBs but it should have only been 2MBs so I had to retest the webjar I was pushing which was why I closed the pull request for now.

I will resend it to @brianchandotcom when I have fixed the issues.

Please let me know if you have any questions. Thanks!

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/brianchandotcom/liferay-portal/pull/54213

**Pull request closed without merging**
