### PR TITLE
LPS-67399 As a developer I can invoke a method that returns a paginated and ordered unified lists of both organizations and users

### PR DESCRIPTION
**Pull request by pei-jung**
Hey @brianchandotcom,

I tried to get the users that are assigned to a specific organizaiton with DynamicQuery but encountered an issue. The user-organization relationship is in the mapping table "Users_Orgs". There doesn't seem to exists a class representing the data in Users_Orgs, so I don't know how to initialize the query.

`DynamicQueryFactoryUtil.forClass(???.class, getClassLoader());`

I've looked into DynamicQuery usages in different places but still can't find a way to do it. Sorry if I missed it. If you really want this do be done in DynamicQuery, I'll keep looking.

/cc @jorgeferrer @drewbrokke

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:reopen

**Comment by alee8888** [comment]
ci:reopen

**Comment by michaelhashimoto** [comment]
ci:reopen

**Comment by kenjiheigel** [comment]
ci:reopen

**Comment by stsquared99** [comment]
ci:help

**Comment by stsquared99** [comment]
ci:reopen

**Pull request closed without merging**
