### PR TITLE
LPS-86125 Reorder by path, feel free to remove this commit if you prefer order by module name

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:close

**Comment by brianchiu** [comment]
@ealonso I need to take a look. From preliminary looks at the screenshots, clicking the plus button in the fragment side bar does not add the fragment. So there may be a bug. I will check it.

**Comment by brianchiu** [comment]
@ealonso The console error from (https://gist.github.com/brianchiu/ddd1d5cee5f302a1a7ce283fb493687e) is fixed. However, there is a bug in this pull. I cannot add fragments in the page template and display page editor. It works fine in the content page editor.



Can you take a look?

**Comment by brianchiu** [comment]
cc @jbalsas

**Pull request closed without merging**
