### PR TITLE
LPS-102829 Added explanation about using key in ClayIcon

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/62cc7f7c85...5aff3ed7a3

**Comment by brianchandotcom** [comment]
@sandrodw3 can you send this commit 5aff3ed7a3e2cdbff9f32ebc13ac1bca99786039 to @wincent and talk to him about it. thx.

**Comment by wincent** [comment]
@brianchandotcom:

> can you resend that to greg? I thought he had a specific way of doing comments like this.

I don't know if we have a rigorous format for these kind of special cases yet, but it might be good to link to an LPS or GitHub ticket that provides context. Do you think something like that would fit well here? eg.

```
/**
 * Key required to force icon to redraw when symbol changes.
 *
 * @see: https://github.com/clay/issues/NNN
 */
const iconKey = icon;
```

(For context, the use of the `key` property here is unusual, and somebody may look at it and say, "you don't need a key here, let's just remove it", which would be a regression. 🤞  that that doesn't happen.)

**Pull request closed without merging**
