### PR TITLE
LPS-108925 Check length of instances array instead of its existence because it always exists

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
@marcelabc Could you please take a look? Thanks!

/cc @ealonso

**Comment by ealonso** [comment]
cc: @jbalsas, @wincent, @julien

**Comment by pavel-savinov** [comment]
ci:stop

**Comment by pavel-savinov** [comment]
Resent https://github.com/brianchandotcom/liferay-portal/pull/84987 in the appropriate branch.

**Comment by wincent** [comment]
> cc: @jbalsas, @wincent, @julien

Commented over on the re-send: https://github.com/brianchandotcom/liferay-portal/pull/84987/files

**Pull request closed without merging**
