### PR TITLE
LPS-97915 Add configuration

### PR DESCRIPTION
**Pull request by cgoncas**
@adolfopa @AliciaGarciaGarcia

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
I think the failed test is not related to this pull.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2dafe05924...fc65955a40

**Comment by brianchandotcom** [comment]
@cgoncas ignored it for now fc65955a40fc2822f37774e51b9eeb13c38a0cbb

**Pull request closed without merging**
