### PR TITLE
LPS-55563 Fixing Typo

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
I merged this anyways @shuyangzhou . I'lll let Hashi know.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2a15dbbe6f...c48abf12d3

**Comment by brianchandotcom** [comment]
@vilmospapp shouldn't this be "startsWith"

Why would an attribute name ever be

"PORTLET_RENDER_PARAMETERS_" ? and end with an _

I think it shouldn't be an equals... please double check.

**Comment by brianchandotcom** [comment]
@vilmospapp I did another fix. Please see upstream and apply everywhere.

See e977a8ab61b741671689d8e5d7da502aeb91cd39 and 45fd1acd60222817b588223448d55e5eb7dc4581

**Comment by shuyangzhou** [comment]
@brianchandotcom This strange name came from https://issues.liferay.com/browse/LPS-14861 https://github.com/liferay/liferay-portal/commit/9da941c6b366d1e59ed66b7bee681a5caaaef63f

I did not look deep enough on the original issue, but I do feel we probably can redo a better fix to avoid the unusual naming.

**Comment by brianchandotcom** [comment]
@vilmospapp I readded _, please see why we have a weird _ in the attribute name. Thx.

**Pull request closed without merging**
