### PR TITLE
 LPS-198338 Adds readonly attribut to infoField

### PR DESCRIPTION
**Pull request by liulukiwi**
https://liferay.atlassian.net/browse/LPS-198338

@jkappler

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:reopen

**Comment by liulukiwi** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/13960

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ea476c1335...9f819f2bdc

**Comment by brianchandotcom** [comment]
@veroglez @jkappler see 9f819f2bdc1aca23c8e843e5c877ab5fa12f6572

**Pull request closed without merging**
