### PR TITLE
LPS-164939 SF

### PR DESCRIPTION
**Pull request by naraandrade**

### CODE REVIEW

**Comment by naraandrade** [comment]
Hi Brian, the PR was tested [here](https://github.com/liferay-objects/liferay-portal/pull/1342) and the failures are not related.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d752927f71...d484e3a8ee

**Comment by brianchandotcom** [comment]
Good job @naraandrade mentoring

Good job @GabrielHenriquedev on this PR

**Comment by naraandrade** [comment]
Just started reviewing :)

**Pull request closed without merging**
