### PR TITLE
LPS-63181 Fix persistence tests - need permission checker to be initialized

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@brianchiu flaky test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/aedd087f6e...7cd927de63

**Comment by brianchandotcom** [comment]
@topolik do we need to reset on tearDown?

**Comment by topolik** [comment]
@brianchandotcom No, there was no PermissionChecker initialized, any code depending on in would (A) already fail on NPE or (B) is initializing own version of permissionChecker

**Pull request closed without merging**
