### PR TITLE
LPS-108851 Semantic Versioning.

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fd7003047e...02c11b4cb1

**Comment by brianchandotcom** [comment]
@marianoalvarosaiz @ealonso I forget, do we need an upgrade or do indexes get automatically added (they used to)

**Comment by brianchandotcom** [comment]
@marianoalvarosaiz please test this on a vanilla 7.3 GA1 and see if the index gets automatically added.

**Comment by marianoalvarosaiz** [comment]
No @brianchandotcom , it doesn't. Only if there's an upgrade step pending the indexes are updated. See https://github.com/brianchandotcom/liferay-portal/pull/85227. Besides I'll work with @achaparro in https://issues.liferay.com/browse/LPS-109189 so that module indexes can get updated via portal.properties property.

**Pull request closed without merging**
