### PR TITLE
LPS-57470 apply lexicon to icon view of web content

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
@brianwulbern this may break some tests. thanks!

**Comment by brianwulbern** [comment]
@juliocamarero thanks for the heads up!  We'll keep tabs on it. :)

**Comment by brianchandotcom** [comment]
portal smoke seems fine, but precompile breaks. I'm going to try and fix it.. @juliocamarero

**Comment by brianchandotcom** [comment]
I fixed the jspc errors, but there may be others. So I sent it back to @carloslancha via https://github.com/carloslancha/liferay-portal/pull/12

**Pull request closed without merging**
