### PR TITLE
Commerce 9935

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
Forward failed to open the PR to this repo even if test suites passed. 
See here: https://github.com/liferay-commerce/liferay-portal/pull/3469#issuecomment-1462427977

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@andrea-ale-sbarra @CrescenzoRegaLF let's go over this PR tomorrow? I'll send you guys an invite

modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-account-client/fsb-exclude.xml
modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-catalog-client/fsb-exclude.xml
modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-catalog-v2-client/fsb-exclude.xml
modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-channel-client/fsb-exclude.xml
modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-inventory-client/fsb-exclude.xml
modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-order-client/fsb-exclude.xml
modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-pricing-client/fsb-exclude.xml
modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-site-setting-client/fsb-exclude.xml
modules/apps/commerce/headless/headless-commerce/headless-commerce-delivery-cart-client/fsb-exclude.xml
modules/apps/commerce/headless/headless-commerce/headless-commerce-delivery-catalog-client/fsb-exclude.xml
modules/apps/commerce/headless/headless-commerce/headless-commerce-delivery-order-client/fsb-exclude.xm

Seem all to be obsolete. This is our first v2 that's a separate module  so I want to do this right. Thx.

**Comment by brianchandotcom** [comment]
@andrea-ale-sbarra @CrescenzoRegaLF 

PR 1
    Use the fixed rest-openapi.yaml that has FORCE = true
    forcePredictableOperationId: true
    forcePredictableSchemaPropertyName: true

    This has no breaking changes because it's just operationId which is
    just our Java code

PR 2
```
        SkuOption:
            properties:
                key:
                    type: string
                optionId:
                    example: 31130
                    format: int64
                    minimum: 0
                    type: integer
                optionValueId:
                    example: 31130
                    format: int64
                    minimum: 0
                    type: integer
                value:
                    type: string
            type: object

    SkuOptionResourceTest

    @Override
    @Test
    public void testPostSkuOption {
        super.testPostSkuOption();

        _http.post(JSONUtil.make the old format)
    }```

**Comment by smottal** [comment]
Hi @brianchandotcom, if FORCE = true changes operationId I think that graphql calls change. Isn't it?
We are already in contact with headless team on this. Can we just send you the functional change(on V1 without force=true)  and when we get a possible solution we will send a follow up PR with the force true changes. 

@andrea-ale-sbarra @riccardo-alberti

**Pull request closed without merging**
