### PR TITLE
LPS-86699 Support filtering by String Custom fields indexed as keyword

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:reopen

**Comment by epgarcia** [comment]
ci:relevant

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Can you resend?

_getUserEntityField(expandoColumn).ifPresent(

Avoid chaining, and also call it 

_getUserEntityFieldOptional

Thx

**Comment by epgarcia** [comment]
See brianchandotcom#64769 Thanks!

**Pull request closed without merging**
