### PR TITLE
LPS-90058 Adds style

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
cc: @brianchiu @kyle-miho

**Comment by brianchiu** [comment]
ci:close

**Comment by brianchiu** [comment]
Need to fix the tests because lots of our tests and collab tests will fail.

New way in this pull to view content is to click "View in Context" or "Show Full Content"

**Comment by brianchiu** [comment]
ci:test:bundle

**Comment by brianchiu** [comment]
Pull request sent to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/68793

**Pull request closed without merging**
