### PR TITLE
LPS-61359  Apply localizable configuration names that are easier to understand

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
@migue @juliocamarero @sergiogonzalez This is as we agreed (The "Default Values" flag will be added later in a new column)
@marcellustavares Please review yours. There are only 3 and are pretty straight forward

**Comment by marcellustavares** [comment]
:+1:

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@brianchiu @sharonchoi what's up with the flaky Poshi tests?

**Comment by brianchiu** [comment]
@sharonchoi
Can you fix the BookmarksFolder#gotoPG? Webdriver is inconsistently not waiting long enough for SPA to load (after the lexicon update I think). Webdriver thinks the page has finished loading and tries to interact with an element, but because the page is still loading it gets messed up.

This is a problem we did not have in the past.

Make sure there is an assertion that waits for the breadcrumb.

after0 1

CC @brianchandotcom

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fea5e17751...b6eb9dff8d

**Comment by brianchandotcom** [comment]
@JorgeFerrer I had to make a few changes in upstream. Please see changes. Thx.

**Comment by JorgeFerrer** [comment]
Thanks @brianchandotcom All changes look good, except for the one related to the OpenSSO configuration. Why did you add the key in the core Language.properties file instead of leaving it in the module?

**Pull request closed without merging**
