### PR TITLE
LPS-0 Build Lang

### PR DESCRIPTION
**Pull request by petershin**
@jhendley

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@jhendley can you work with @petershin and @Lionah so that lang keys are built automatically and sent every morning (via the normal lang key push process). Thx.

**Comment by jhendley** [comment]
@brianchandotcom yes

**Comment by lionah** [comment]
I'll go ahead and add it to the scope of work for when we begin automatically back porting language keys.

**Comment by petershin** [comment]
@lionah - Regarding the questions from our meeting:

- I just ran `gradlew buildLang` from `portal/modules`
- the `buildLang` task doesn't work when you run it from `src/main/resources/content` 😞

**Pull request closed without merging**
