### PR TITLE
LPS-70677

### PR DESCRIPTION
**Pull request by Ithildir**
cc @david-truong

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:reopen

**Comment by Ithildir** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@codyhoag fyi

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/66d26d26d8...f4cf815d68

**Pull request closed without merging**
