### PR TITLE
Lps 64261

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by pyoo47** [comment]
TempMap failure.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0bb6d0ed2a...a3c88969c5

**Comment by brianchandotcom** [comment]
@Preston-Crary please see my minor changes in upstream. Thx.

**Pull request closed without merging**
