### PR TITLE
LPS-96578 Factory classes modified to static util

### PR DESCRIPTION
**Pull request by zoltancsaszi**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by zoltancsaszi** [comment]
ci:reopen

**Comment by zoltancsaszi** [comment]
ci:test:sf

**Comment by zoltancsaszi** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@zoltancsaszi 1.) can you rename ProcessCollectionNotFoundException to match

/change-tracking-rest-impl/**/NoSuchCompanyExceptionMapper.java

So it should be NoSuchProcessCollectionException and NoSuchProcessCollectionExceptionMapper.

2.) The static utils are not in the right package. Please follow my instructions in the other pull for the right package to match CreatorUtil. Thx.

**Comment by zoltancsaszi** [comment]
Hi @brianchandotcom ,

As I can see, ProcessCollectionNotFoundException is no longer needed, so I removed it.

https://github.com/brianchandotcom/liferay-portal/pull/74968

**Pull request closed without merging**
