### PR TITLE
LPS-76252 Auto

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b495882a83...8083b2bbe1

**Comment by brianchandotcom** [comment]
@ealonso does AssetTagStatsServiceUpgrade.java really depend on LockManager, or was that a cut and paste error? Thx.

**Pull request closed without merging**
