### PR TITLE
Database Support: proper way to deal with the indexes while updating column names

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@marianoalvarosaiz can you resend on top of https://github.com/marianoalvarosaiz/liferay-portal/pull/10

I found some inconsistencies in the names of things.

"Column" should refer to a composed column.

"Column name" is the name.

See my renames. Can you go through the test method names and ensure consistency (and clarity). Verbosity is OK as long as it adds clarity. Thx.

**Comment by marianoalvarosaiz** [comment]
@brianchandotcom changes seem right for me. Resent pull, see https://github.com/brianchandotcom/liferay-portal/pull/44736

**Pull request closed without merging**
