### PR TITLE
LPS-127677 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-127677

This is only for master.

@victorg1991

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure task is unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/5813
❌ ci:test:stable - 10 out of 11 jobs passed
❌ ci:test:relevant - 22 out of 24 jobs passed in 3 hours 20 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/166ec5bccf...2b51181bc2

**Comment by brianchandotcom** [comment]
@victorg1991 i merged this, but this will be hard to backport because all we see is 2 reverts

your last commit should not have been a revert

**Pull request closed without merging**
