### PR TITLE
LPS-66486

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@david-truong this won't work.. it has to be hard coded to match ServerDetector. For example, there isn't one for tcserver.

**Comment by brianchiu** [comment]
@david-truong 
FYI those failures are unrelated to your pull. Upgrade failures are happening across the board, and the portal smoke failure happened because portal randomly disconnected. We're trying to figure out why this is happening.

**Pull request closed without merging**
