### PR TITLE
LPS-63037 backend changes for the layout customizations

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Weird that it worked this last time, did you rewrite the pull history?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7b62030b77...41233f131f

**Comment by juliocamarero** [comment]
No, there is a commit I added that fixed the issue. Although I had to execute the tests several times until they passed. thanks!

**Pull request closed without merging**
