### PR TITLE
LPS-70200

### PR DESCRIPTION
**Pull request by danielkocsis**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@hhuijser I didn't merge in d3a5ebac0aca9a74bcc8a2984a88c6b952aebf92

I see why @danielkocsis added it, but I don't seem to need it? I ran it locally without his commit and it didn't give me an SF warning?

What's going on? Thx @hhuijser

Merged.

**Comment by hhuijser** [comment]
@brianchandotcom 

We don't need to specify those lines with long method names in source-formatter.properties anymore since https://github.com/liferay/liferay-portal/commit/7254cd124b0ec6a9d81d7871badbac2dc3014aed

btw. how did you catch that?

**Comment by danielkocsis** [comment]
@hhuijser

I put this there becouse for me, locally, source formatter warned this line. Maybe it used wrong version of source formatter by default what did not contain this logic?

**Comment by hhuijser** [comment]
@danielkocsis 
Probably when you tested, the code wasn't there yet. I only added that code last week.

**Pull request closed without merging**
