### PR TITLE
LPS-100639 AB Test - display test settings in sidebar when test is running

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Can you resend

SegmentsExperimentLocalServiceTest.testGetSegmentsExperiments

fails...

Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/67dabf63f8...24ed947053

**Comment by brianchandotcom** [comment]
@epgarcia I merged this, but it looks like there may be a flaky test in segments. Please fix test. Thx.

**Comment by epgarcia** [comment]
Thanks @brianchandotcom, I'll send a follow up PR fixing the test.

**Comment by epgarcia** [comment]
See #77808. Thanks

**Pull request closed without merging**
