### PR TITLE
LPS-68917 don't specify test class since it isn't currently supported

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:stop

**Comment by gamerson** [comment]
cc @Ithildir @david-truong

If everything passes, @brianchandotcom  can can you publish the following modules?

```
project-templates
project-templates-activator
project-templates-api
project-templates-content-targeting-report
project-templates-content-targeting-rule
project-templates-content-targeting-tracking-action
project-templates-control-menu-entry
project-templates-fragment
project-templates-mvc-portlet
project-templates-panel-app
project-templates-portlet
project-templates-portlet-configuration-icon
project-templates-portlet-provider
project-templates-portlet-toolbar-contributor
project-templates-service
project-templates-service-builder
project-templates-service-wrapper
project-templates-simulation-panel-entry
project-templates-template-context-contributor
project-templates-theme
project-templates-workspace
```

Thanks!

**Comment by gamerson** [comment]
ci:retest

**Comment by gamerson** [comment]
ci:reopen

**Comment by gamerson** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/48dd4a4eaf...3a1f2210fa

**Comment by brianchandotcom** [comment]
merged and published. Thx @gamerson !

**Pull request closed without merging**
