### PR TITLE
LPS-54041 Portal Service Access Control Profile

### PR DESCRIPTION
**Pull request by mikakoivisto**
First little background on what we are doing. We are creating a way for portal administrator to create predefined service access control profiles that declare what services or service methods can be called. Basically this is creating a more fine grained control than what we already have in OAuth where you can only define either READ or WRITE. This will also be completely separate from OAuth and can be attached to any Remote API authorisation method. These profiles can the be granted to different applications. Enforcing the profiles will be done by a new AccessControlPolicy.

This module will provide the backend implementation for the public API we'll be creating in portal-service com.liferay.portal.security.ac where two new interfaces will be added: ServiceAccessControlProfile and ServiceAccessControlProfileService. Each profile is tied to a portal instance.

This module really belongs to /modules/portal but haven't been able to get CI build to pass there yet and I really need to get the service.xml reviewed before I can make any progress else where so feel free to not merge it but do let me know what changes you want in regards to service.xml and naming.

### CODE REVIEW

**Comment by mikakoivisto** [comment]
This same exact branch just built successfully when I sent it to @mhan810

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Hey Mika,

I was in the middle of merging this in, just need to find a better name for the module.. so I need one more day. So just fyi. Thx.

**Comment by brianchandotcom** [comment]
@mikakoivisto I renamed the app and removed the impl just to get the pull merged in.

Can you resend the impl? Also, what is stored in the allowedServices?

Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4cbad2da8e...6f225904d4

**Comment by brianchandotcom** [comment]
Btw, I followed the naming for DDL etc.

**Pull request closed without merging**
