### PR TITLE
LPS-99660 Fix compileJSP task

### PR DESCRIPTION
**Pull request by petershin**
@vicnate5 @alecsloan

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:backend-hypersonic

**Comment by vicnate5** [comment]
Thanks @petershin!

**Comment by alecsloan** [comment]
@marco-leo

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/51d34375a1...795e0a6a97

**Pull request closed without merging**
