### PR TITLE
LPS-62002 Lexicon in Live Site in Message Boards

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @sharonchoi

**Comment by sharonchoi** [comment]
@brianchandotcom Please close, I will resend with the test fixes, as there are UI changes.

**Comment by brianchandotcom** [comment]
Thx @sharonchoi

**Comment by sharonchoi** [comment]
@sergiogonzalez 

I found a bug on this branch with Message Boards. If you navigate to Site Admin, and add a MB Thread, publishing the thread will only display the success message and nothing else. Refreshing the page will not show the portlet contents, and only when a user navigate to Message Boards through the Product Menu, will they be able to see the threads and categories in Site Admin.

**Comment by sergiogonzalez** [comment]
Working on it @sharonchoi thx!

**Pull request closed without merging**
