### PR TITLE
LPS-70932

### PR DESCRIPTION
**Pull request by danielkocsis**

### CODE REVIEW

**Comment by danielkocsis** [comment]
ci:reopen

**Comment by danielkocsis** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@danielkocsis test? Thx.

**Comment by danielkocsis** [comment]
@brianchandotcom the exact same fix has already committed to the DefaultExportImportContentProcessor (https://github.com/brianchandotcom/liferay-portal/pull/47704) along with tests. We need this code change only because not all the components have been able to adopt to this change.

**Pull request closed without merging**
