### PR TITLE
LPS-71651 De-randomize test as a temporary measure to investigate flakiness

### PR DESCRIPTION
**Pull request by arboliveira**
Current random failure needs more information:

`expected:<[[oqyhylqk]]> but was:<[[1xxz3pp4, 8ntefeit, edczvst5, gekzuo25, jxkt7hmr, qqjzmlzg, shrlu9c3, tb0bcu89, ujbtrhkm, wk8jt0uy]]>`

https://github.com/liferay/liferay-portal/pull/1464#issuecomment-301219613

cc/ @marcellustavares @Preston-Crary

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/669c7cbf66...2077727186

**Comment by brianchandotcom** [comment]
@arboliveira We have a specific random generator for screen names.

@shuyangzhou can you point @arboliveira to that piece of code? Thx.

**Comment by shuyangzhou** [comment]
@arboliveira see https://github.com/liferay/liferay-portal/blob/master/portal-impl/test/integration/com/liferay/portal/search/SearchPaginationTest.java#L81

**Comment by shuyangzhou** [comment]
@arboliveira you never send up a follow up pull for this? @tomwang2011 please clean up UserIndexerTest, we will to wipe this clean for syncing portal-test-integration.

**Pull request closed without merging**
