### PR TITLE
LRQA-40712 Make sure ci:test:relevant for WEM has the appropriate WEM tests

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LRQA-40712

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@brianchiu you should sort things like this

```
            (testray.main.component.name ~ "Layout Page Templates") OR \
            (testray.main.component.name ~ "Content Pages")\
```

Please send me an updated pull.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d73fbfb2d6...ae65559e9d

**Comment by brianchiu** [comment]
Fixed here: https://github.com/brianchandotcom/liferay-portal/pull/58666#issuecomment-390082364

**Pull request closed without merging**
