### PR TITLE
LPS-68035

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by jpince** [comment]
@hhuijser this is better, but I still see
```
java.lang.Exception: Use SecureXMLBuilderUtil.newDocumentBuilderFactory instead of DocumentBuilderFactory.newInstance: ../../../modules/private/apps/spi/spi-provider-web/docroot/WEB-INF/src/com/liferay/portal/resiliency/spi/provider/tomcat/TomcatRemoteSPI.java
```

**Comment by jpince** [comment]
@hhuijser just saw your email, ignore the above

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
