### PR TITLE
LPS-108771 - Update uses of @clayui/* dependencies

### PR DESCRIPTION
**Pull request by bryceosterhaus**
https://issues.liferay.com/browse/LPS-108771

### CODE REVIEW

**Comment by john-co** [comment]
ci:reopen

**Comment by john-co** [comment]
I think once Brian's origin gets merged into upstream this should work. Will need to rerun tests at that point.

**Comment by vicnate5** [comment]
Brian's origin is currently broken due to https://github.com/brianchandotcom/liferay-portal/pull/84723

**Comment by brianchandotcom** [comment]
Yikes...

@pyoo47 @vicnate5 @kenjiheigel I"m getting rid of poshi-runner as a subrepo. Not buying us much. See b383f188d200f12e70d360da39cef982f1257bd0

@hhuijser no need to worry about this. I got rid of the subrepo.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b383f188d2...d70aa692c4

**Pull request closed without merging**
