### PR TITLE
LPS-84376 Regenerate service

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
@brianchiu Could you please take a look? This is new functionality and there is no integration points yet, test failures seem to be unrelated to this pull.

**Comment by jpince** [comment]
@brianchiu startup errors are known, please check functional test failure(s)

**Comment by brianchiu** [comment]
Ok. checking right now.

**Comment by brianchandotcom** [comment]
@pavel-savinov thank you, this is not getting backported... merged.

**Pull request closed without merging**
