### PR TITLE
LPS-83149 User API improvements

### PR DESCRIPTION
**Pull request by javiergamarra**
Hi! It's sorted alphabetically by the key as the other representors (unless I'm missing something), do you want to sort it by day of the week? (monday to sunday or sunday to saturday?)

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:reopen

**Comment by nhpatt** [comment]
ci:retest

**Comment by nhpatt** [comment]
ci:test:sf

**Comment by nhpatt** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.

View just my changes: https://github.com/brianchandotcom/liferay-portal/compare/nhpatt:3eeb027df9...adf96e4fee
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/decde1f99e...adf96e4fee

**Comment by brianchandotcom** [comment]
@nhpatt backported.. and I updated build.gradle to use the latest published portal-kernel

**Pull request closed without merging**
