### PR TITLE
LPS-76719 Removing old fix for non ASCII chars

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test

**Comment by jpince** [comment]
@4lejandrito I don't see these failures elsewhere. Going to retest and see if they reoccur.

**Comment by jpince** [comment]
ci:close

**Comment by jpince** [comment]
ci:retest

**Comment by 4lejandrito** [comment]
Hi @jpince,

These failures seem unrelated to me but let's wait for the build to finish.

Thanks!

**Comment by jpince** [comment]
@4lejandrito the only failure I'm concerned about is portal-license ([console log](https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/187182/AXIS_VARIABLE=0,label_exp=!master/console)). This test checks if any of the modified files in the commits affect license, if there are any then it runs a dist on portal using the build script in liferay-release-tool-ee to check if the license can still be applied correctly.
Changes in at least one of these files caused the failure:
```
portal-impl/src/com/liferay/portal/util/PropsValues.java
portal-kernel/src/com/liferay/portal/kernel/util/PropsKeys.java
```
Beyond that, I'm not sure why it failed or how to fix it... @CAustin582 or @amosfong can either of you help with this?

**Comment by 4lejandrito** [comment]
Hmmm @jpince I only added a property to those files... I don't see how that can affect the license. I am curious to know.

Thanks for the explanation 🙂 .

**Comment by amosfong** [comment]
These changes shouldn't have affected licensing. Is there any way to rerun the licensing tests only?

**Comment by jpince** [comment]
@amosfong not sure why I got a rebase error trying to send to your master branch... sent a pull to myself so you can see the result of just the license test https://github.com/jpince/liferay-portal/pull/32

**Comment by amosfong** [comment]
my branch is pretty far out of date....ok, thanks!

**Comment by jpince** [comment]
ci:retest fixed per Chas

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
@4lejandrito there were issues that Chas and QA Engineering needed to fix (the latter is still in progress). So, your pull helped identify those issues, thanks!

So, given that you and Amos don't think this pull is a risk to licensing, I've reopened it to be reviewed & merged. Thanks for your patience!

**Comment by 4lejandrito** [comment]
Thanks a lot @jpince!

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@4lejandrito shouldn't you add an entry in portal.properties with the default values?

**Comment by 4lejandrito** [comment]
Hi @brianchandotcom,

I added the default value in [PropsValues](https://github.com/liferay/liferay-portal/blob/a30112d0cbcbabd75d75ffda6fca78b869a50e91/portal-impl/src/com/liferay/portal/util/PropsValues.java#L1889).

You are right though, the pattern seems to be to add it in `portal.properties`  I'll send the change next year 🙂 .

**Pull request closed without merging**
