### PR TITLE
LPS-87545 SF

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
@ambrinchaudhary

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7b1ccf2005...4f623b7f7d

**Comment by brianchandotcom** [comment]
@ambrinchaudhary @4lejandrito @jbalsas fyi, see 4f623b7 I don't believe this is needed anymore.

@Preston-Crary can you review modules/apps/document-library/document-library-web/src/main/java/com/liferay/document/library/web/internal/bulk/selection/BulkSelectionRunnerUtil.java

Not sure if that is strange for you. Thx.

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/66801

**Comment by jbalsas** [comment]
Hey @ambrinchaudhary, as @brianchandotcom said, it's no longer necessary to add the `npmResolvedPackageName` there. I assume this was on its way at the same time that got merged. 

However, it should be `module="document_library/bulk/BulkStatus.es"` without the leading `/`. Could you guys fix that, verify it and send a followup with it?

**Pull request closed without merging**
