### PR TITLE
LPS-104246 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-104246

### CODE REVIEW

**Comment by kyle-miho** [comment]
@brianchandotcom didnt have time to test, but this should fix stable, if not then reverting this pull should fix it. A change was made to site page creation redirects, so all of our tests need to now reflect that
https://github.com/brianchandotcom/liferay-portal/pull/81404

**Comment by kyle-miho** [comment]
cc: @adolfopa

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/601a92d329...f1ff2dd0b7

**Comment by brianchandotcom** [comment]
@adolfopa fix didn't work, reverted LPS-104246

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones: <br><br>Sent from GitHub :octocat:

**Comment by austinchiang** [comment]
@brianchandotcom  Portal#Smoke was [fixed](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=893053086) by @kyle-miho's pull, so I think this should have been good. The other test failures don't look related. I'll resend the pull

**Comment by austinchiang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/81440

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones: <br><br>Sent from GitHub :octocat:

**Pull request closed without merging**
