### PR TITLE
LPS-61354 Contribute taglibs defined in the Frontend Taglib module through a fragment mechanism. This will allow us to deocuple our Freemarker support from the JSP API and modules can use this pattern to make their taglibs available within the Freemarker context

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by kiyoshilee** [comment]
The same issue occurred as the one on https://github.com/brianchandotcom/liferay-portal/pull/33380

**Comment by kiyoshilee** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/506ed40afe...e774e5513e

**Pull request closed without merging**
