### PR TITLE
LRQA-29642 | 7.0.x

### PR DESCRIPTION
**Pull request by vicnate5**
Backport of https://github.com/brianchandotcom/liferay-portal/pull/45399

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

https://loop.liferay.com/home/-/loop/feed/3506548

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
