### PR TITLE
LPS-65036 SF

### PR DESCRIPTION
**Pull request by marcellustavares**
cc @rafaprax

### CODE REVIEW

**Comment by vicnate5** [comment]
@marcellustavares These poshi failures are real. The web content is not displaying after an upgrade, and I think the locator for Web Content inputs needs to be updated.

**Comment by brianchandotcom** [comment]
@marcellustavares please resend. Thx.

**Comment by marcellustavares** [comment]
Thx @vicnate5, will resend.

**Comment by marcellustavares** [comment]
Resent to https://github.com/brianchandotcom/liferay-portal/pull/39781

**Pull request closed without merging**
