### PR TITLE
LRQA-64448 Do not run with baseline smoke

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/13fca4e06d...f8d5126170

**Comment by brianchandotcom** [comment]
Yes, this will save a lot @vicnate5  can you send me backports?

**Comment by vicnate5** [comment]
@brianchandotcom Backports not needed. This test is master only.

**Pull request closed without merging**
