### PR TITLE
LPS-98298 SF - Rename constant

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
That's a strange fatal error? @pyoo47

**Comment by brianchandotcom** [comment]
@cgoncas that error may be because my origin hasn't synced with upstream yet (should be there in an hour if there are no major errors in my origin)

**Comment by cgoncas** [comment]
@brianchandotcom , thanks for the explanation :).

**Comment by cgoncas** [comment]
ci:test:relevant:norebase

**Comment by yichenroy** [comment]
Hello @cgoncas,
I believe this pullrequest was rebased off of Brian's origin so it contained commits that were not yet available in upstream at the time of your first test, so Brian was right about the reason for the fatal error.

We'll work on improving the failure message for invalid master-private commits so the failure message is less confusing.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/00453eaea8...ffeb6975e9

**Comment by brianchandotcom** [comment]
lbm:backport @CsabaTurcsan @jpince @zsoltbalogh

@cgoncas can you backport this to the "liferay" user when it's all ready? The new 365 opener should be part of 7.2 SP1.

See ffeb6975e9b72fcb6f1e321a5a8db473f345eb41 for my tiny changes as well. Thx.

**Comment by cgoncas** [comment]
@Brian Chan <2@liferay.com> , perfect, I will backport everything once we
finish the ticket.

Cristina González
Senior Software Engineer
Liferay España y Portugal

Tel. +34 917336343
www.liferay.com

<http://liferay.com/es>Enterprise. Open Source. For Life
Follow us on Twitter <https://twitter.com/liferay_es> | LinkedIn
<http://www.linkedin.com/company/liferay-inc-/> | Facebook
<https://www.facebook.com/liferay/>

Confidentiality and Privacy Notice: This e-mail, including the attached
files, sent on behalf of Liferay, S.L. is for the exclusive use of the
expected recipient(s) and may contain confidential and privileged
information, as well as data of personal nature. Therefore, according to
the rules on the protection of personal data and confidentiality
commitments concerning company data, they may not be used for purposes
other than maintain professional or commercial relationships and provide
the agreed service or the collection of information related to the activity
of the Liferay Group of companies, with the consent of the interested party.

No data will be transferred to third parties, except with express
authorization or as a result of a legal obligation. The Liferay Group is a
global corporation, composed by affiliated companies from several
countries. You agree that, to the extent needed, these data may be
communicated to other entities of the Liferay Group, only for the purpose
previously indicated, as well as to third parties acting on behalf of
Liferay, including the transfer to servers and data bases located outside
of the country in which you provided your personal data to Liferay. The
said transfers may include transfers and/or communications of data outside
of the European Economic Area.

You may exercise your rights to access, modify, cancel, and oppose or limit
the processing of your personal data, and your rights to transparency and
portability, and not to be subject to individual automated decisions, by
sending communications via mail to Liferay, S.L., Paseo de la Castellana 280
<https://maps.google.com/?q=Paseo+de+la+Castellana+280&entry=gmail&source=g>,
Module B
<https://maps.google.com/?q=Paseo+de+la+Castellana+280+,+Module+B&entry=gmail&source=g>,
First floor, 28046, Madrid, or via email to data-es@liferay.com, attaching
a copy of your national ID card or equivalent document as proof of your
identity.

For additional information, please check our Privacy Policy:
https://www.liferay.com/en/privacy-policy.

In case you have received this message by error, you must not disclose,
copy, distribute, or use it in any manner. We kindly ask you to inform the
sender and delete the message and any document attached to it, without
reading it or making use of any data they may contain. You accept the
consequences that the misuse of said data may entail.

**Pull request closed without merging**
