### PR TITLE
LPS-87560 Update poshi tests

### PR DESCRIPTION
**Pull request by rafaprax**
//cc @inacionery @jpince

### CODE REVIEW

**Comment by rafaprax** [comment]
Hey @jpince
Can you please check my changes in fdb9b70? In this pr I change the position and Portlet names from workflow components in the Control Panel. 

Thx

**Comment by jpince** [comment]
@rafaprax looks ok from a quick look, would have to see all of the upstream tests run to fully evaluate it.

@kmaria fyi, makes a staging test change

cc/ @brianchiu @vicnate5 @alexcandidos @austinchiang @xbrianlee new product menu names for workflow

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9a866204ea...77c92453dc

**Comment by brianchandotcom** [comment]
@jpince I merged this, fyi.

**Pull request closed without merging**
