### PR TITLE
LPS-78136 Throws exception instead use try/catch block

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/12ab89369f...015dbac212

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/55730

**Comment by brianchandotcom** [comment]
@rafaprax @linolaoj see https://github.com/brianchandotcom/liferay-portal/pull/55730

**Pull request closed without merging**
