### PR TITLE
COMMERCE 6557 COMMERCE 6561 2

### PR DESCRIPTION
**Pull request by ivicac**
master

### CODE REVIEW

**Comment by ivicac** [comment]
ci:reopen

**Comment by ivicac** [comment]
ci:test:sf

**Comment by ivicac** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/156bf87f16...ee405ab126

**Comment by ivicac** [comment]
cc @alecsloan

**Pull request closed without merging**
