### PR TITLE
LPS-75962 Stop deploying this module unstill the jvm shutdown hanging…

### PR DESCRIPTION
**Pull request by shuyangzhou**
… issue is fixed.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c36a192811...78a5d4bccb

**Comment by brianchandotcom** [comment]
@marcellustavares fyi

**Comment by brianchandotcom** [comment]
@shuyangzhou the test is still running so we'll get results.. I did merge this and closed the PR.

**Pull request closed without merging**
