### PR TITLE
LPS-110361 Set correct title for each button

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
```
  PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
= ================================================== ========== ========== ========== ========== ==========
* com.liferay.ratings.taglib.servlet.taglib          MAJOR      1.2.0      1.2.0      2.0.0      VERSION INCREASE REQUIRED
	>   class      com.liferay.ratings.taglib.servlet.taglib.RatingsTag
		+   method     setInTrash(boolean)
			+   return     void
		-   method     setInTrash(java.lang.Boolean)
			-   return     void
[Baseline Warning] Bundle Version Change Recommended: 2.0.0
[Baseline Report] Mode: diff (persisted)

> Task :apps:ratings:ratings-taglib:syncVersions

```

**Comment by brianchandotcom** [comment]
@ambrinchaudhary I'm fine with the breaking change since this is a new module.. BUT, you need to tell me in the pull. Right now, it seems you guys were not aware. Please run baseline and resend.

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/86424.

**Pull request closed without merging**
