### PR TITLE
LPS-64669 Avoid repeatedly loading the same class name ids at runtime.

### PR DESCRIPTION
**Pull request by shuyangzhou**
@dantewang @slnn performance check please.

### CODE REVIEW

**Comment by sharonchoi** [comment]
@alee8888 Poshi test failure bc the test didn't wait long enough for the page to finish loading.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@sharonchoi that poshi test failure was random, please check it out? Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/08430857b9...076c48b935

**Pull request closed without merging**
