### PR TITLE
LPS-155149 Intermittent failures occurring on com.liferay.document.library.social.test.DLFileEntryActivityInterpreterTest

### PR DESCRIPTION
**Pull request by adolfopa**
- LPS-155149 Removed use of time and refactored check of renaming
- LPS-155149 Passing info of original activities to better check renaming
- LPS-155149 Fix: the implemented method addActivities() should effectively add activities
- LPS-155149 Simplified main test method

The original code relied on the time of inserted records. I wanted to avoid this as it could been the source of the intermittent errors. At the same time I've corrected another test using the fixed based class, as it wasn't adding activities in the implemented method addActivities(). I've corrected this method based on 2 similar implementations: `DLFolderActivityInterpreterTest` and `JournalFolderActivityInterpreterTest`.  When creating a "folder" no activity is added, so a simple way to add activities is to move to trash and restore from trash. As an example see the implementation for the `JournalFolderActivityInterpreterTest` below:

https://github.com/liferay/liferay-portal/blob/3da9eed4d2559fd367ddbd08534bea4bc1ee05fd/modules/apps/journal/journal-test/src/testIntegration/java/com/liferay/journal/social/test/JournalFolderActivityInterpreterTest.java#L49

### CODE REVIEW

**Comment by adolfopa** [comment]
Manually forwarded from https://github.com/liferay-lima/liferay-portal/pull/3536

**Comment by adolfopa** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cbb5023890...527e32e624

**Comment by brianchandotcom** [comment]
Very nice @marcogalluzzi @adolfopa

**Pull request closed without merging**
