### PR TITLE
LPS-64318 Simplify

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2fd6cb40a1...c9877a9e07

**Comment by brianchandotcom** [comment]
@amosfong fyi

**Comment by brianchandotcom** [comment]
@shuyangzhou fyi

**Pull request closed without merging**
