### PR TITLE
master-vw-375

### PR DESCRIPTION
**Pull request by vicnate5**
@marcellustavares @brunobasto @rafaprax

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bf54281f69...b2cd71781a

**Pull request closed without merging**
