### PR TITLE
LPS-88947 Separates jquery into its own module

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a6047b5704...0f531ab8a6

**Comment by brianchandotcom** [comment]
@julien @jbalsas please see my tiny changes in upstream.

**Comment by jbalsas** [comment]
Looks good, @brianchandotcom, thanks, and thanks for applying it to the lodash one as well! :)

**Comment by julien** [comment]
@brianchandotcom thanks!

**Pull request closed without merging**
