### PR TITLE
LPS-88674 Sample theme to test headless APIs

### PR DESCRIPTION
**Pull request by javiergamarra**
It's a demo site to allow easy testing/reviewing of the APIs for end users (just install the demo site and check the results). We can reference it in the documentation instead of forcing users to create content from scratch.

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:reopen

**Comment by nhpatt** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:close @nhpatt please fix modules-compile error

```
     [exec] > Task :apps:headless-apio:structured-content:structured-content-apio-impl:compileJava
...
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/headless-apio/headless-apio-demo/src/main/java/com/liferay/headless/apio/demo/internal/HeadlessDemo.java:90: error: cannot find symbol
     [exec] 			_group = _createDemoGroup(company, user);
     [exec] 			                                   ^
     [exec]   symbol:   variable user
     [exec]   location: class HeadlessDemo
     [exec] 1 error
```

**Comment by jpince** [comment]
cc/ @cgoncas see error above

**Comment by nhpatt** [comment]
Thanks, I'll check it :)

**Comment by nhpatt** [comment]
Fixed here (https://github.com/brianchandotcom/liferay-portal/pull/66342), sorry for breaking it :(

**Pull request closed without merging**
