### PR TITLE
LPS-147579 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-147579

This is only for master.

@laszlopap
cc @ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure test is unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/7307
❌ ci:test:stable - 24 out of 27 jobs passed
❌ ci:test:relevant - 24 out of 28 jobs passed in 2 hours 10 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/674cd5bd1a...82a78a17dd

**Comment by brianchandotcom** [comment]
@laszlopap see a4e8429cc240a0d10a99004145797125c5a2c8f3

**Comment by brianchandotcom** [comment]
@ealonso @laszlopap see a4e8429cc240a0d10a99004145797125c5a2c8f3

**Pull request closed without merging**
