### PR TITLE
LPS-70156 Temporarily disable aspectj advices on the CI until the hea…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…p memory usage can be reduced.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@shuyangzhou I've seen this BundleSupportAntTest.testInitBundleTarProxyAuthenticated a few times now, randomly.

**Comment by brianchandotcom** [comment]
Merged.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
