### PR TITLE
LPS-107058 Adding resources

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0b986d9187...23fd70a438

**Comment by brianchandotcom** [comment]
@wincent fyi Liferay_KaleoDesignerXMLDefinitionSerializer."before all" hook

@inacionery please fix JS issue

**Comment by brianchandotcom** [comment]
See c6b09bf

**Comment by wincent** [comment]
@brianchandotcom: That test passes locally without timing out, so it is either a spurious temporary failure, or something that is non-spurious and doesn't like our CI environment. @4lejandrito: did you see this pass in CI before sending?

**Comment by 4lejandrito** [comment]
Hi @wincent, that failure is unrelated to these changes. Maybe @austinchiang can help you get to the root of it.

**Comment by wincent** [comment]
Well, I wasn't going to investigate it further because it is not clear to me whether it is an ephemeral issue, and if not, when it started (and therefore what might have broken it).

**Pull request closed without merging**
