### PR TITLE
LPS-90027 SF

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:reopen

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@alexcandidos

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d771272e49...399e1b734a

**Comment by brianchandotcom** [comment]
@jpince some tests were ignored for this, can you make sure our process knows how to unignore them. Thx.

**Comment by jpince** [comment]
@john-co

**Comment by john-co** [comment]
two of the three ddm modules tests have been unignored.

@brunobasto fyi, dynamic-data-mapping-form-web js test is still disabled.
https://github.com/john-co/liferay-portal/pull/56/commits/25b08f272cd556a111c589d2edc4d53ab6d35942

I'm not sure if the changes include a fix for this test yet, but if it does please unignore the test as well.

**Comment by brunobasto** [comment]
Oh, I think I let that slide. Will send an update. Thx

**Pull request closed without merging**
