### PR TITLE
LPS-70736 As a developer, I'd like to have an API to help display international address in proper formats

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @jorgeferrer @drewbrokke

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest - https://loop.liferay.com/home/-/loop/feed/6170033

**Comment by brianchandotcom** [comment]
@pei-jung please resend

We already have

com.liferay.portal.kernel.format


for phone numbers

We shouldn't use

com.liferay.address.formatter

But instead, something like:

com.liferay.xyz.formatter.phone
com.liferay.xyz.formatter.address

Thx.

**Comment by pei-jung** [comment]
Hey @brianchandotcom,

How about
com.liferay.**data.localization**.formatter?

so we can have
com.liferay.**data.localization**.formatter.address
com.liferay.**data.localization**.formatter.phone

The module structure will be
```
├── data-localization
│   ├── data-localization-formatter
│   ├── data-localization-taglib
```
Any thoughts @drewbrokke @jorgeferrer?

**Comment by pei-jung** [comment]
hey @brianchandotcom, did you get a chance to look at my suggestion for the rename?

**Pull request closed without merging**
