### PR TITLE
LPS-151956 Fix error in build-test.xml

### PR DESCRIPTION
**Pull request by david-gutierrez-mesa**
https://issues.liferay.com/browse/LPS-151956

### CODE REVIEW

**Comment by david-gutierrez-mesa** [comment]
Test cases failing here not related: https://github.com/liferay-echo/liferay-portal/pull/7873#issuecomment-1105772557
SF passed here: https://github.com/liferay-echo/liferay-portal/pull/7873#issuecomment-1105459998

**Comment by david-gutierrez-mesa** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bbd405cb97...21c61b806e

**Comment by brianchandotcom** [comment]
@david-gutierrez-mesa see my simplification in 858079741983cffb213091f895eae9a0a2b0ea2d

**Pull request closed without merging**
