### PR TITLE
LPS-81567 generated

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
@hhuijser it seems like there is a problem in the SB - I've generated the services and it has removed a bunch of beans from the portal-spring.xml that's causing the test failure. I can't see any errors in the SB log, only this: ```[echo] ["=",<110> [102:138-102:139]]```

FYI @brianchandotcom @jpince

**Comment by jpince** [comment]
@michaelhashimoto @kenjiheigel @yichenroy the SB error is because it needs to be rebuilt... reproducible locally only on an old version. Does ci:test:relevant account for this?

**Comment by jpince** [comment]
@matethurzo @zoltancsaszi I see this error in this pull and the previous one sent to Mate, and haven't seen it anywhere else this morning. Can you please take a look? Failing this way in smoke, lpkg, and modules-integration batches. 
```
     [exec] 11-Jun-2018 12:42:05.719 INFO [main] org.apache.catalina.core.ApplicationContext.log Initializing Spring root WebApplicationContext
     [exec] 12:42:08,320 ERROR [main][PortalBeanLocatorUtil:72] BeanLocator is null
     [exec] 12:42:08,323 ERROR [main][ContextLoader:225] Context initialization failed
     [exec] org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.liferay.document.library.kernel.util.DLFileVersionPolicy' defined in class path resource [META-INF/util-spring.xml]: Initialization of bean failed; nested exception is com.liferay.portal.kernel.bean.BeanLocatorException: BeanFactory could not find bean: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'com.liferay.document.library.kernel.service.DLFileEntryMetadataLocalService' is defined
     [exec] 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:687)
     [exec] 	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1168)
     [exec] 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:281)
     [exec] 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
     [exec] 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:272)
     [exec] 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
     [exec] 	at com.liferay.portal.spring.bean.BeanReferenceAnnotationBeanPostProcessor._autoInject(BeanReferenceAnnotationBeanPostProcessor.java:136)
```
As a suggestion, I noticed lines in your code like [this one](https://github.com/brianchandotcom/liferay-portal/pull/60129/files#diff-f7d5c3cab3a747977f4c57631f31a12bL237). Hugo's SF rule that requires this caused a compile failure last night, so it may not be correct to implement this way. Here's an example of how Peter fixed [the compile error](https://github.com/brianchandotcom/liferay-portal/pull/60148/commits/236cdf18ff49ee501cdf9e10bc83492b74e991c4). I may be totally wrong as to the cause, so please ignore this section if I'm incorrect :)

**Comment by hhuijser** [comment]
@matethurzo, that was caused by an earlier change to SB for LPS-72445. I reverted that on Monday. Latest SB should be good to go.

**Pull request closed without merging**
