### PR TITLE
master-qa-20119

### PR DESCRIPTION
**Pull request by vicnate5**
https://issues.liferay.com/browse/LRQA-20124
https://issues.liferay.com/browse/LRQA-20119
https://issues.liferay.com/browse/LRQA-20115
https://issues.liferay.com/browse/LRQA-20104
https://issues.liferay.com/browse/LRQA-20103
https://issues.liferay.com/browse/LRQA-20098

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@vicnate5 please resend. Too many poshi failures.

**Comment by vicnate5** [comment]
@brianchandotcom These poshi failures are not due to this pull and will be occurring on all pulls at the moment. This is caused by changes in https://github.com/brianchandotcom/liferay-portal/pull/33121 where the PR tester first showed these failures. It is not a bug, the tests needed to be updated.

I will send to the fix ASAP.

CC @brianchiu

**Comment by vicnate5** [comment]
Sent fix https://github.com/brianchandotcom/liferay-portal/pull/33138

**Comment by vicnate5** [comment]
Resent this pull https://github.com/brianchandotcom/liferay-portal/pull/33150

**Pull request closed without merging**
