### PR TITLE
LPS-66727 | master

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-29851 / https://issues.liferay.com/browse/LPS-66727

See 7.0.x pull here: https://github.com/brianchandotcom/liferay-portal/pull/45695

cc @vicnate5 @ctampoya
The LPS was closed as Won't Fix, so we'll probably have to update the tests on master & 7.0.x.  We can help with that tomorrow, as the need arises.

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:reopen

**Comment by vicnate5** [comment]
@brianwulbern Thanks. We may need to remove some of the tests because they will not no longer applicable if we cannot edit the default single approver definition in Kaleo Designer.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianwulbern** [comment]
Nice, thanks @vicnate5!

**Pull request closed without merging**
