### PR TITLE
LPS-81714 Fixes test locator

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @jpince, this is our biggest missing UX change. I think all it requires are test fixes. Could you expedite test analysis and fixes for this? If we could merge and fix later, it'd be even better, as this is a very big PR and chances of conflict are growing :(

Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jpince** [comment]
ci:close @jbalsas will talk about how we want to handle this with the other leads. Will look to get it in today.

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:close pushed upstream https://github.com/liferay/liferay-portal/compare/8b4891c...93d548a <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
