### PR TITLE
LPS-162507 New upgrade steps aren't executed for com.liferay.client.extension.service

### PR DESCRIPTION
**Pull request by susanchen3**
Manually forwarding as test failures are [unrelated](https://github.com/liferay-uniform/liferay-portal/pull/654#issuecomment-1255451378)

Fixes blocker: https://issues.liferay.com/browse/LPS-162507

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:reopen

**Comment by vicnate5** [comment]
FYI @tinatian @shuyangzhou

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8b6306ce5c...969ee565ee

**Comment by shuyangzhou** [comment]
This is wrong, you can not run the upgrade logic in activate method. https://github.com/brianchandotcom/liferay-portal/pull/123577/files#diff-f655ddab9dcc7509a546aaf31c881fd05c47e627e9e13b48c640dc47638efd6a

**Comment by brianchandotcom** [comment]
@marianoalvarosaiz I reverted based on SZ's comments.

**Comment by achaparro** [comment]
@brianchandotcom @shuyangzhou I don't agree with that. We are not running upgrade logic in the activate method, it's only the release renaming.

In the same way we can't run "upgrade logic" in the initial deployment process as it is now. Only data loading (although we use the upgrade framework)

**Pull request closed without merging**
