### PR TITLE
LPS-126238

### PR DESCRIPTION
**Pull request by emanuelfisilva**
[LPS-126238](https://issues.liferay.com/browse/LPS-126238) - _Create test and macro to validate the creation of web content using a structure that was upgraded_

### CODE REVIEW

**Comment by emanuelfisilva** [comment]
For SF please check: https://github.com/emanuelfisilva/liferay-portal/pull/63#issuecomment-789983746

**Comment by emanuelfisilva** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@ViniLopes20 fyi

**Comment by brianchandotcom** [comment]
@emanuelfisilva can you resend? rebase error with another pull.

**Comment by emanuelfisilva** [comment]
Resent https://github.com/emanuelfisilva/liferay-portal/pull/71

**Pull request closed without merging**
