### PR TITLE
LPD-34076

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4e0f0f621a...d0fe917f08

**Comment by brianchandotcom** [comment]
@gabrielwas 1.) See d0fe917f08ac2c29c2809d0c3cce85a7ecde56ee

2.) Can you rename

commerce_order_notification_template_body.ftl
object_entry_notification_template_body.ftl

to

notification_template_body_*.ftl

This way they'll all be grouped together if we have more types in the future. 

@victorKammerer fyi

**Comment by gabrielwas** [comment]
It makes sense! Thx!

Just sent the follow up here: https://github.com/brianchandotcom/liferay-portal/pull/154750

**Comment by gabrielwas** [comment]
@brianchandotcom  It makes sense! Thx!

Just sent the follow up here: https://github.com/brianchandotcom/liferay-portal/pull/154750

**Pull request closed without merging**
