### PR TITLE
LPS-80826 Removing id

### PR DESCRIPTION
**Pull request by 4lejandrito**
Hi @brunobasto,

I have removed the document library changes from [your original pull](https://github.com/4lejandrito/liferay-portal/pull/108) since we still don't know the strategy for that.

We will send those as part of a separate ticket once we agree on the final solution.

Thanks!

@sergiogonzalez @adolfopa

### CODE REVIEW

**Comment by jpince** [comment]
@4lejandrito is this a real error?
`Module not found: Error: Can't resolve '../utils/assets' in '/opt/dev/projects/github/liferay-portal/modules/apps/analytics/analytics-client-js/src/plugins'`

**Comment by jpince** [comment]
ci:close will close and wait for retest, unless I hear back from Alex

**Comment by jpince** [comment]
ci:test:relevant

**Comment by brunobasto** [comment]
It probably is. Let;'s close this for now and I'll resend.

Thanks

**Pull request closed without merging**
