### PR TITLE
LPS-52271

### PR DESCRIPTION
**Pull request by danielkocsis**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@michaelhashimoto @kiyoshilee Do you know why there are no test results? I tried retesting it already. Thx.

**Comment by kiyoshilee** [comment]
ci:retest

**Comment by kiyoshilee** [comment]
@brianchandotcom I'm not sure why this one is not triggering. I've checked the entire cohort and the job is not being scheduled for this particular pull request.

**Comment by danielkocsis** [comment]
I think the problem was my membership of the Liferay org was private, now it should be public. Please try to retest.

**Comment by kiyoshilee** [comment]
ci:retest

**Comment by kiyoshilee** [comment]
@brianchandotcom @danielkocsis That seemed to have been the issue. The pr is now being tested on <a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest(master)/77/">test-1-2</a>.

**Comment by brianchandotcom** [comment]
Thx @danielkocsis

**Pull request closed without merging**
