### PR TITLE
[DO NOT BACKPORT] LPS-100021 Disables Font Awesome by default

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @brianchandotcom!

This disables Font Awesome by default and would be a breaking change in `7.2.x`. This is `7.3-only`, so pelase, **do NOT backport**.

I prepared the `BREAKING_CHANGES` for `7.3` and added this as the first one.

Let me know if there's anything else that needs to be done here.

Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:reopen

**Comment by jbalsas** [comment]
I don't think `apps:product-navigation:product-navigation-control-menu-web:packageRunBuild` is related to this PR...

/cc @john-co?

**Comment by john-co** [comment]
Just started analyzing :)

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
@jbalsas looks like it was a fluke. Build passed locally and build looks like it went through on the pending ci test relevant.

**Comment by john-co** [comment]
js-unit test failures are unrelated.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b3cf6ae539...1dd6de6091

**Comment by brianchandotcom** [comment]
@codyhoag fyi.. we split the breaking_changes.readme here. Can you verify? Thx.

**Comment by codyhoag** [comment]
@brianchandotcom looks OK to me! The `7.2.x` branch now contains the 7.2 Breaking Changes. I'll begin tracking the `master` version for 7.3 changes. Thanks!

**Pull request closed without merging**
