### PR TITLE
LPS-61311

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6e7d5f1aba...8878ba2892

**Comment by brianchandotcom** [comment]
@pyoo47 can you see why this pull hung?

**Comment by mhan810** [comment]
Was talking to @shuyangzhou.  Seems like we are exposing some leaks and etc
with some of these pulls (e.g. like with LPS-61095).  I will try to
reproduce locally later as well.

-m

**Comment by shuyangzhou** [comment]
@mhan810 this pull is due to PACL hanging, I will be on it soon.

**Pull request closed without merging**
