### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:reopen

**Comment by ling-alan-huang** [comment]
SF failure is not related to this pull.

**Comment by ling-alan-huang** [comment]
The failures are not related to this pull.

**Comment by jpince** [comment]
@hhuijser @ling-alan-huang fyi, `ci:forward` will start tomorrow and affect you guys
https://liferay.slack.com/archives/C03BTCQBQ/p1584941216034600

Post in [#ci ](https://liferay.slack.com/archives/C19PWQ74J) if you have a feature request or idea that will help your workflow.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a7adeee8ff...0176e79d8c

**Pull request closed without merging**
