### PR TITLE
LPS-58044 SF

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
/cc @migue 

reverted the version change in dependent libraries. 
The problem we seem to have is SCR 1.8.2 performs an action that the security manager forbids. 
The problem is that 1.8.3-SNAPSHOT (the one in master) does not properly recreate the component instances associated to configuration factories that are persisted. This basically means that the state of the components that depend on the configuration admin is not restored properly after portal reboot. 

Bests.

**Comment by csierra** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d15f49f5af...84611bcc47

**Comment by brianchandotcom** [comment]
Thx @csierra

**Comment by brianchandotcom** [comment]
@csierra I made some minor changes in upstream. Please review. Thx.

**Pull request closed without merging**
