### PR TITLE
LPS-70902 Standardize Facet creation via *FacetFactory instead of FacetFactoryUtil

### PR DESCRIPTION
**Pull request by arboliveira**
https://issues.liferay.com/browse/LPS-64398

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by arboliveira** [comment]
I'll rebase and resend 👍

**Pull request closed without merging**
