### PR TITLE
LPS-90507 Applies Default Event Handler to Management Toolbar Event Handlers

### PR DESCRIPTION
**Pull request by patriciajeanperez**
https://issues.liferay.com/browse/LPS-90507

cc @jbalsas @adolfopa

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:close

**Comment by patriciajeanperez** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a210101b91...00bb3b455d

**Comment by brianchandotcom** [comment]
@ealonso can you see my change in 00bb3b4

Can you apply it everywhere, type:

git grep "Context.getDisplayStyle();"

**Pull request closed without merging**
