### PR TITLE
master-sc-208

### PR DESCRIPTION
**Pull request by sharonchoi**
https://issues.liferay.com/browse/LRQA-19277

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/83ee1563d6...2941f35f9a

**Comment by brianchandotcom** [comment]
@sharonchoi @evannagayama @brianchiu the DeleteCalendarEventRegular test always breaks around this time of the day. See:

https://github.com/brianchandotcom/liferay-portal/pull/32953

https://github.com/brianchandotcom/liferay-portal/pull/32956

Please fix. It's been happening a few days now.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2941f35f9a...2941f35f9a

**Comment by vicnate5** [comment]
@sharonchoi @evannagayama @brianchiu I can take care of this.

**Pull request closed without merging**
