### PR TITLE
LPS-200121 | master

### PR DESCRIPTION
**Pull request by SylviaLuan**
Manually forwarding after CI issues in https://github.com/liferay-lima/liferay-portal/pull/4834

### CODE REVIEW

**Comment by SylviaLuan** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b5b57f56f7...8996785b98

**Comment by brianchandotcom** [comment]
@robertoDiaz please verify my changes in 8996785b9821515489d2bf32a2dd02d759a4692a

**Comment by robertoDiaz** [comment]
Hey @brianchandotcom 

Seems to be ok.

Thank you for taking care.

**Pull request closed without merging**
