### PR TITLE
Lps 54998

### PR DESCRIPTION
**Pull request by shuyangzhou**
Major performance regression affects all test cases, login is 10+ times slower than before.

We need to address this asap while it is still a simple revertable change, before other things start to build on top this.

@mjbradford89 please feel free to resend this with fix to @dantewang @slnn or @tomwang2011 to recheck your change before sending to @brianchandotcom 

And if you need @dantewang @slnn can provide all the info you might need to solve this like test results, thread dump, profiles, system infos, etc.

CC @peterfellwock

### CODE REVIEW

**Comment by peterfellwock** [comment]
Will work with @rotty3000 and @mjbradford89 to resolve this first thing.
Question is without this fix does it still under perform?

**Comment by mjbradford89** [comment]
Thanks for catching this. I think I can already see the flaw causing the performance hit. I'll get to this first thing tomorrow.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@shuyangzhou please resend? broke twice.

**Comment by rotty3000** [comment]
@shuyangzhou @petterfellwock @mjbradford89 I'm not even sure why this
change is required?

Ultimately checking for existance of some resource is only a concern where
those resources can "change" such as in the portal-web where there's things
like JSP Hooks.

However, in a static module which is itself a singlton "resources" can't to
away on their own! So the need for an "available" check is moot.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by mjbradford89** [comment]
Hey @rotty3000 

I had originally thought it was necessary because of the InputEditorTag (https://github.com/liferay/liferay-portal/blob/master/util-taglib/src/com/liferay/taglib/ui/InputEditorTag.java#L268) checking availability for all editor jsps.  So I thought instead of removing the check (that was now failing due to the migration) I should have it check in the bundle also.

But if you think the check is moot, maybe we should just remove it all together.

**Comment by rotty3000** [comment]
Hey @brianchandotcom this pull should go in. It's the correct thing to do.

Can you reopen?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5afd7c5eb2...cac8567e11

**Comment by brianchandotcom** [comment]
@rotty3000 @shuyangzhou isn't this technically needed though?

Right now, they can ask, FileAvailabilityUtil.isAvailable("goodpath/veryverybadpath") and it'll return true even though it's not an available file..

**Comment by rotty3000** [comment]
> Right now, they can ask, FileAvailabilityUtil.isAvailable("goodpath/veryverybadpath") and it'll return true even though it's not an available file..

@brianchandotcom at which point the include will fail! that's perfectly fine! Nobody should try to include anything from a module that doesn't exist without getting an error!

Furthermore, what if the include is a Servlet? It'll already return false on perfectly legitimate path!

**Comment by mjbradford89** [comment]
Hey @rotty3000 @brianchandotcom @shuyangzhou @peterfellwock   I just sent a fix (https://github.com/dantewang/liferay-portal/pull/87) to @dantewang for the performance regression, so he can test and ensure the caching brings the performance back to acceptable levels.

**Comment by mjbradford89** [comment]
Hey guys,

I sent a new pull with a fix to the performance regression to Ray here https://github.com/rotty3000/liferay-portal/pull/823

Lily Chi confirmed that these changes improved the performance back to normal.

**Comment by shuyangzhou** [comment]
Thanks @mjbradford89

**Comment by peterfellwock** [comment]
To actual normal?

**Comment by mjbradford89** [comment]
@peterfellwock Yes. Here are the results: 

image


Which I understand to be within normal range.

**Comment by peterfellwock** [comment]
Then, great job @mjbradford89!

**Pull request closed without merging**
