### PR TITLE
LPS-196413 Create a constant for strings like designConfigurationModified and published

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://liferay.atlassian.net/browse/LPS-196413

@Mikellorza

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/13798

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/06f752b4c0...f3846940fa

**Comment by brianchandotcom** [comment]
@Mikellorza I merged this, but can you rename the vars in here

```
public class LayoutTypeSettingsConstants {

	public static final String DESIGN_CONFIGURATION_MODIFIED =
		"designConfigurationModified";

	public static final String PUBLISHED = "published";

```

to start with KEY_ 

I'm afraid that one day we'll add a specific value and it'll be confusing if ti's all mixed together.

**Comment by brianchandotcom** [comment]
@Mikellorza actually, just resend, I didn't merge this.

**Pull request closed without merging**
