### PR TITLE
LPS-80565 use pattern from aui BaseInputTag for remembering checkbox set

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by jpince** [comment]
@michaelhashimoto @kenjiheigel @yichenroy `StagingGroupHelperTest.tearDown` fails in Mate's pulls (see also https://github.com/brianchandotcom/liferay-portal/pull/58245), but not in [upstream](https://test-1-1.liferay.com//userContent/jobs/test-portal-acceptance-upstream%28master%29/builds/3788/jenkins-report.html). Can you please take a look?

**Comment by jpince** [comment]
@matethurzo Hashi said he was able to reproduce the failure locally. Still not sure why it's not failing at head, but can you try it and see if a fix is needed?

**Comment by michaelhashimoto** [comment]
@jpince @matethurzo - After investigating it a little bit more I was able to figure out how to consistently reproduce this test failure.

Here's the command I was using to reproduce this failure:
<pre>/opt/dev/projects/github/liferay-portal/modules/apps/staging $ ../../../gradlew testIntegration --tests com.liferay.staging.test.StagingGroupHelperTest</pre>

I noticed that it only fails if you DO NOT already have a portal bundle started.  It will only pass if in another terminal the bundle is already running.

Hopefully this information is helpful.  Thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3435fea8ae...2846a37154

**Comment by brianchandotcom** [comment]
@matethurzo please fix the test, see comment from @michaelhashimoto !

Merged this pull since the failure is related to the module, but not to this pull specifically.

**Comment by matethurzo** [comment]
@brianchandotcom @michaelhashimoto investigating

**Pull request closed without merging**
