### PR TITLE
LPS-101773 Experiments history (AB Testing)

### PR DESCRIPTION
**Pull request by dgarciasarai**
@andresfulla @darquesdev

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ad98caebf2...d125851c47

**Comment by brianchandotcom** [comment]
@dgarciasarai see my changes in upstream. Thx.

**Comment by dgarciasarai** [comment]
Thanks! I'll take into account those changes for the future :)

**Pull request closed without merging**
