### PR TITLE
LPS-75587

### PR DESCRIPTION
**Pull request by Ithildir**
Hi,
Please let this pull finish.

Thank you!

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:stop

**Comment by Ithildir** [comment]
ci:reopen

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by Ithildir** [comment]
Hi @brianchandotcom! Can you please publish a new `project-templates`? Also, all the other `project-templates-*` must be published first.

Thank you very much!

**Comment by brianchandotcom** [comment]
@Ithildir I published all of project-templates**

In the future, can we move all of those files into its own subdir inside sdk? That way, I can just go to that subfolder and not do any have to make a funky script.  Thx.

**Comment by brianchandotcom** [comment]
@Ithildir or.. perhaps give me a command to wildcard publish? Thx.

**Pull request closed without merging**
