### PR TITLE
LPS-60358

### PR DESCRIPTION
**Pull request by mikakoivisto**
LPS-60358 Protection against Java deserialization vulnerability

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Sent it to @shuyangzhou at https://github.com/shuyangzhou/liferay-portal/pull/2109

**Comment by shuyangzhou** [comment]
@topolik @mikakoivisto All restricted classes in the list are in full class names, can we just do class name equals check, rather than regex matching?

I think even in the future when you extend this list with new classes, it will still be case by case. If it turns out to really need a true regex later, we can always add it in by that time.

**Comment by topolik** [comment]
@shuyangzhou I believe we can.

**Comment by shuyangzhou** [comment]
Awesome! Thanks @topolik !

I will go ahead simplify it to do simple equals check. This would not affect any api, if it turns out we do need regex some time later, it will just be an internal impl change, we can apply it at anytime.

**Pull request closed without merging**
