### PR TITLE
LPS-138673

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
Unrelated failure: https://github.com/hhuijser/liferay-portal/pull/5887

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7b5ae149ad...0253e1d801

**Comment by brianchandotcom** [comment]
@hhuijser thx!

**Pull request closed without merging**
