### PR TITLE
LPS-95749 SF

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@ealonso can you resend and move

modules/apps/asset/asset-list-service/src/main/java/com/liferay/asset/list/internal/DDMIndexerUtil.java

to

modules/apps/asset/asset-list-service/src/main/java/com/liferay/asset/list/internal/dynamic/data/mapping/util/DDMIndexerUtil.java

Thx.

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/73449

**Pull request closed without merging**
