### PR TITLE
LPS-70212 Update dependencies

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @jonathanmccann

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@sergiogonzalez @jonathanmccann can you resend and change the delete logic in the handler to

```
		_kbArticleLocalService.deleteGroupKBArticles(
			portletDataContext.getScopeGroupId());
		_kbFolderLocalService.deleteKBFolders(
			portletDataContext.getScopeGroupId());
		_kbTemplateLocalService.deleteGroupKBTemplates(
			portletDataContext.getScopeGroupId());
```

Basically sort, and add a line break only if order really matters. I have a feeling it may not. If it does, please note that in the commit message that it was purposeful.

Thx.

**Comment by jonathanmccann** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/46456

**Pull request closed without merging**
