### PR TITLE
LPS-105081 Update 'List' view icon to Clay

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4fd1e45c25...e4d5bb84a6

**Comment by brianchandotcom** [comment]
@shuyangzhou see equinox issue, coming up quite a bit.

**Comment by shuyangzhou** [comment]
@brianchandotcom that is because of https://github.com/liferay/liferay-portal/blob/master/modules/apps/depot/.lfrbuild-releng-ignore

depot is not part of the release. but there are release included modules using it, in this failure case is :
```
modules/apps/trash/trash-web/src/main/java/com/liferay/trash/web/internal/depot/application/TrashDepotApplication.java:import com.liferay.depot.application.DepotApplication;
```
So the question is, why depot is not release ready but still used by released modules?

**Comment by brianchandotcom** [comment]
@4lejandrito @adolfopa I had to revert 312f85bae6c0d18adcdf22d0028f688e988963af because it's causing many stable job errors. This is on almost every pull:

```
AXIS_VARIABLE=0,label_exp=!master #290093
Startup error: Unresolved Requirement(s)

     [exec] 14:43:09,884 DEBUG [Start Level: Equinox Container: 14de3da5-4996-41ef-9c7e-030972ca21be][BundleStartStopLogger:48] STARTED com.liferay.journal.terms.of.use_5.0.0 [519]
[exec] 14:43:09,895 DEBUG [Start Level: Equinox Container: 14de3da5-4996-41ef-9c7e-030972ca21be][BundleStartStopLogger:48] STARTED com.liferay.staging.bar.web_4.0.0 [522]
[exec] 14:43:09,906 DEBUG [Start Level: Equinox Container: 14de3da5-4996-41ef-9c7e-030972ca21be][BundleStartStopLogger:48] STARTED com.liferay.staging.processes.web_4.0.0 [527]
[exec] 14:43:09,923 DEBUG [Start Level: Equinox Container: 14de3da5-4996-41ef-9c7e-030972ca21be][BundleStartStopLogger:48] STARTED com.liferay.analytics.settings.web_1.0.0 [543]
[exec] 14:43:09,924 DEBUG [Start Level: Equinox Container: 14de3da5-4996-41ef-9c7e-030972ca21be][BundleStartStopLogger:48] STARTED com.liferay.analytics.web_3.0.0 [544]
[exec] 14:43:09,954 DEBUG [Start Level: Equinox Container: 14de3da5-4996-41ef-9c7e-030972ca21be][BundleStartStopLogger:48] STARTED com.liferay.rss.web_6.0.0 [554]
[exec] 14:43:09,955 DEBUG [Start Level: Equinox Container: 14de3da5-4996-41ef-9c7e-030972ca21be][BundleStartStopLogger:48] STARTED com.liferay.frontend.compatibility.ie_4.0.0 [556]
[exec] 14:43:10,010 DEBUG [Start Level: Equinox Container: 14de3da5-4996-41ef-9c7e-030972ca21be][BundleStartStopLogger:48] STARTED com.liferay.message.boards.web_4.0.0 [567]
[exec] 14:43:10,012 DEBUG [Start Level: Equinox Container: 14de3da5-4996-41ef-9c7e-030972ca21be][BundleStartStopLogger:48] STARTED com.liferay.asset.taglib_5.0.0 [594]
[exec] 14:43:10,017 DEBUG [Start Level: Equinox Container: 14de3da5-4996-41ef-9c7e-030972ca21be][BundleStartStopLogger:48] STARTED com.liferay.portal.workflow.kaleo.designer.web_4.0.0 [601]
[exec] 14:43:10,017 DEBUG [Start Level: Equinox Container: 14de3da5-4996-41ef-9c7e-030972ca21be][BundleStartStopLogger:48] STARTED com.liferay.document.library.analytics_4.0.0 [608]
[exec] 14:43:10,018 DEBUG [Start Level: Equinox Container: 14de3da5-4996-41ef-9c7e-030972ca21be][BundleStartStopLogger:48] STARTED com.liferay.document.library.asset.auto.tagger.google.cloud.vision_2.0.0 [609]
[exec] 14:43:10,019 DEBUG [Start Level: Equinox Container: 14de3da5-4996-41ef-9c7e-030972ca21be][BundleStartStopLogger:48] STARTED com.liferay.document.library.asset.auto.tagger.microsoft.cognitive.services_2.0.0 [610]
```
See comment by @shuyangzhou

**Comment by 4lejandrito** [comment]
Hi @brianchandotcom,

I sent https://github.com/austinchiang/liferay-portal/pull/639 this morning fixing that. Now some modules depend on depot so we can no longer ignore it. Just what you found out.

Thanks!

**Pull request closed without merging**
