### PR TITLE
LRQA-51488 Rein in some

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-51488

@brianchandotcom, the wide nature of this typo fixing pull [dogged it](https://github.com/brianwulbern/liferay-portal/pull/265#issuecomment-606449028) with unrelated flaky test failures.  I was able to find and quarantine quite a few in the process, though!

I rebased this on top of your origin, so it should be clear of conflicts until your morning.

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:reopen

**Comment by brianwulbern** [comment]
ci:test:sf

**Comment by brianwulbern** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c2ca13d354...5abc32183f

**Pull request closed without merging**
