### PR TITLE
OAUTH2-232 Dynamic Client Registration Protocol

### PR DESCRIPTION
**Pull request by topolik**
https://github.com/brianchandotcom/liferay-portal/pull/64524

Fixed JSP compilation dependencies.

### CODE REVIEW

**Comment by topolik** [comment]
@xbrianlee we need to update the poshi tests, now we have 2 items in the "add" dropdown.

**Comment by xbrianlee** [comment]
@topolik I'll work on the fix this morning. You can track[LRQA-44364](https://issues.liferay.com/browse/LRQA-44364).

**Comment by topolik** [comment]
@xbrianlee thanks. Please monitor https://github.com/topolik/liferay-portal/pull/641, namely look at https://github.com/topolik/liferay-portal/pull/641/commits/ffbfa82cbb8cb62051b7397a6906c3969e34edbe I tried to run tests but it didn't run oauth2 tests so now I'm running everything.

**Comment by xbrianlee** [comment]
@topolik That's expected since we haven't implemented those suites. You can track [LRQA-44066](https://issues.liferay.com/browse/LRQA-44066) for progress. @joshchong will be working on those suites shortly. In the meantime, we do have `ci:test:security` but this was designed more for QA in mind since it runs all security tests.

**Pull request closed without merging**
