### PR TITLE
Shard Tool: MySQL support

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by migue** [comment]
ci:retest

**Comment by migue** [comment]
ci:retest

**Comment by migue** [comment]
ci:retest

**Comment by migue** [comment]
ci:retest

**Comment by migue** [comment]
This is an standalone tool which is not even deployed into the runtime. How is this possible that the functional tests are failing?

**Comment by brianchandotcom** [comment]
@migue you're right, it shouldn't be happening. Working with QA to solve these flaky tests.

**Comment by migue** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/afabd2db13...63e74f17d7

**Comment by brianchandotcom** [comment]
@mdelapenya sorry it took so long, can you review my changes and send me the next set? Will review them right away. Thx.

**Pull request closed without merging**
