### PR TITLE
Lps 106079

### PR DESCRIPTION
**Pull request by shuyangzhou**
See https://github.com/shuyangzhou/liferay-portal/pull/8638#issuecomment-567142055

@brianchandotcom can you have the data-engine and oauth2-provider owners fix the wrong SPI usages ?
```
Do not expose 'SPIDataDefinitionField' in 'api' module: C:/github/liferay-portal/modules/apps/data-engine/data-engine-api/src/main/java/com/liferay/data/engine/field/type/FieldType.java (SourceCheck:JavaModuleExposureCheck)
Do not expose 'SPIDataDefinitionField' in 'api' module: C:/github/liferay-portal/modules/apps/data-engine/data-engine-api/src/main/java/com/liferay/data/engine/rule/function/DataRuleFunction.java (SourceCheck:JavaModuleExposureCheck)
Do not expose 'SPIDataDefinitionField' in 'api' module: C:/github/liferay-portal/modules/apps/data-engine/data-engine-api/src/main/java/com/liferay/data/engine/rule/function/DataRuleFunctionResult.java (SourceCheck:JavaModuleExposureCheck)
Do not expose 'SPIDataDefinitionField' in 'api' module: C:/github/liferay-portal/modules/apps/data-engine/data-engine-api/src/main/java/com/liferay/data/engine/field/type/BaseFieldType.java (SourceCheck:JavaModuleExposureCheck)
Do not expose 'ApplicationDescriptor' in 'api' module: C:/github/liferay-portal/modules/apps/oauth2-provider/oauth2-provider-scope-liferay-api/src/main/java/com/liferay/oauth2/provider/scope/liferay/ApplicationDescriptorLocator.java (SourceCheck:JavaModuleExposureCheck)
Do not expose 'ScopeDescriptor' in 'api' module: C:/github/liferay-portal/modules/apps/oauth2-provider/oauth2-provider-scope-liferay-api/src/main/java/com/liferay/oauth2/provider/scope/liferay/ScopeDescriptorLocator.java (SourceCheck:JavaModuleExposureCheck)
```
We have 3 SPI interfaces that are exposed, SPIDataDefinitionField, ApplicationDescriptor, ScopeDescriptor. It is not easy for me to tell what's their intention. Once they are fixed, we can enable this SF rule.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/48a801c50d...4eb04ea675

**Comment by brianchandotcom** [comment]
@jeyvison @csierra

We're adding a new SF rule to ensure that *-api never depends on *-spi. 

API is for external users, SPI is for us.. we should never mix the two.

One violation is in oauth, and the other in data-engine. Please fix the usages. See this pull for reference.

**Comment by jeyvison** [comment]
Adding @leoadb

**Comment by csierra** [comment]
hey @shuyangzhou, 
in the case of ```oauth2-provider``` I can try to explain the rationale. in this case we have:

```
  oauth2-provider-scope-api
  oauth2-provider-scope-spi
  oauth2-provider-scope-liferay-api
```
so `oauth2-provider-scope-api` and `oauth2-provider-scope-spi` are _paired_ and follow the rules as you described above. They also don't enter into any Liferay specific concept. 
Then we have `oauth2-provider-scope-liferay-api`, which is _Liferay aware_, and depends on both `oauth2-provider-scope-api` and `oauth2-provider-scope-spi` and it is for _internal_ use inside Liferay.

So it made a lot of sense for us back in the days, but everything is subject to change. I was wondering if it would make sense to enforce the rule for modules that have the same prefix but allow dependencies for modules that are named differently, or if this would still be a problem.

Carlos.

**Comment by leoadb** [comment]
@brianchandotcom In order to remove that dependency I would need to remove the interfaces **com.liferay.data.engine.field.type.FieldType** and **com.liferay.data.engine.rule.function.DataRuleFunction**. That's ok regarding version 2 of the REST API, but that will break when we put version 1 back. How you want to proceed with this? Thanks

**Comment by shuyangzhou** [comment]
@csierra when you say oauth2-provider-scope-liferay-api is "for internal use inside Liferay", it is making oauth2-provider-scope-liferay-api a "client" of oauth2-provider-scope-api and oauth2-provider-scope-spi. By definition, spi is not supposed to be used by "client" code. Therefore it is no longer a spi, you should consider to promote it to become api.

I am still missing a lot context here, can not say for sure this is the right thing to do. But the general rule is simple, as long as the code is required by any "client" code, it is an API. If the code is only for internal implementation/extension purpose, it is a SPI. SPI can depend on API freely, API can not depend on SPI. You can decide which way to go base on the business logic.

**Comment by brianchandotcom** [comment]
@leoadb For data engine v1, we are only enforcing REST backwards compat, not OSGi backwards compat so you can change it and it's fine.

**Comment by csierra** [comment]
hey @shuyangzhou, 

so then I guess we can extract `ApplicationDescriptorLocator` and `ScopeDescriptorLocator` to a new `oauth2-provider-scope-liferay-spi` and it should be fine then...

/cc @martamedio

**Pull request closed without merging**
