### PR TITLE
LPS-59912 Portlet Tracker throws error on startup

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/64f4d0fd5a...baa1b885e7

**Comment by brianchandotcom** [comment]
@shuyangzhou isn't our portal log assert supposed to catch these?

**Comment by shuyangzhou** [comment]
I don't get this error locally or on any CI log.

@rotty3000 how to reproduce this? And can you paste the stack trace on the ticket just for future reference.

**Comment by rotty3000** [comment]
@shuyang this error must happen because of lines:

https://github.com/liferay/liferay-portal/blob/master/util-java/src/com/liferay/util/log4j/Log4JUtil.java#L101-L116

And the portlet-tracker clearly didn't include the inner classes which
would/should have resulted in a ClassDefNotFound error on execution.

On Wed, Oct 28, 2015 at 1:57 AM, Shuyang Zhou <notifications@github.com>
wrote:

> I don't get this error locally or on any CI log.
>
> @rotty3000 <https://github.com/rotty3000> how to reproduce this? And can
> you paste the stack trace on the ticket just for future reference.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/31516#issuecomment-151733872>
> .
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by rotty3000** [comment]
Note, this was a change you made yourself 6 weeks ago at
bebb84e72e7d517f45325cba47d1f83b3e8c57ef

On Wed, Oct 28, 2015 at 9:22 AM, Raymond Auge <raymond.auge@liferay.com>
wrote:

> @shuyang this error must happen because of lines:
>
>
> https://github.com/liferay/liferay-portal/blob/master/util-java/src/com/liferay/util/log4j/Log4JUtil.java#L101-L116
>
> And the portlet-tracker clearly didn't include the inner classes which
> would/should have resulted in a ClassDefNotFound error on execution.
>
> On Wed, Oct 28, 2015 at 1:57 AM, Shuyang Zhou <notifications@github.com>
> wrote:
>
>> I don't get this error locally or on any CI log.
>>
>> @rotty3000 <https://github.com/rotty3000> how to reproduce this? And can
>> you paste the stack trace on the ticket just for future reference.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/brianchandotcom/liferay-portal/pull/31516#issuecomment-151733872>
>> .
>>
>
>
>
> --
> *Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
>  (@rotty3000)
> Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
>  (@Liferay)
> Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org>
> (@OSGiAlliance)
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by shuyangzhou** [comment]
@rotty3000 Please paste the error stack.

As mush as I know, there is no module with portlets also has "META-INF/portal-log4j.xml", the logic is always shortcuted inside Log4JUtil.configureLog4J(URL url), as the url is null. Unless you are creating a new module with that file, otherwise this is impossible.

@brianchandotcom I am sure the tomcat log scanner is working as expected, CI has never seen this error.

As a matter of fact, the usage of Log4JUtil.configureLog4J() inside PortletTracker is wrong, for 2 reasons:
1) For all modules, the log4j configuration is done inside Log4jExtender, there is no reason that PortletTracker needs to do it again.
2) All log4j xml for module should be called module-log4j.xml and module-log4j-ext.xml. 

Don't worry, I am going to clean up PortletTracker for the log4j configuration logic.

**Comment by rotty3000** [comment]
Can you also remove Log4jUtil from all the other modules that embed it if
this is the case as well?

On Wed, Oct 28, 2015 at 11:30 AM, Shuyang Zhou <notifications@github.com>
wrote:

> @rotty3000 <https://github.com/rotty3000> Please paste the error stack.
>
> As mush as I know, there is no module with portlets also has
> "META-INF/portal-log4j.xml", the logic is always shortcuted inside
> Log4JUtil.configureLog4J(URL url), as the url is null. Unless you are
> creating a new module with that file, otherwise this is impossible.
>
> @brianchandotcom <https://github.com/brianchandotcom> I am sure the
> tomcat log scanner is working as expected, CI has never seen this error.
>
> As a matter of fact, the usage of Log4JUtil.configureLog4J() inside
> PortletTracker is wrong, for 2 reasons:
> 1) For all modules, the log4j configuration is done inside Log4jExtender,
> there is no reason that PortletTracker needs to do it again.
> 2) All log4j xml for module should be called module-log4j.xml and
> module-log4j-ext.xml.
>
> Don't worry, I am going to clean up PortletTracker for the log4j
> configuration logic.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/31516#issuecomment-151882463>
> .
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by shuyangzhou** [comment]
yes, I will clean them up too.

**Pull request closed without merging**
