### PR TITLE
LPS-89897 Apply new lexicon cards to My Sites functional tests

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LPS-89897

This is for master only.

cc @ealonso

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchiu** [comment]
ci:test:relevant:norebase

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
