### PR TITLE
LPS-69446 Servlet Context Name no longer stripped of all non-alphanumeric characters

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by NolanChan** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/dd1433cc01...7bab581217

**Comment by brianchandotcom** [comment]
@NolanChan please backport. Thx.

**Comment by brianchandotcom** [comment]
@NolanChan please send to @ZoltanTakacs

thx

**Pull request closed without merging**
