### PR TITLE
LPS-57603 - Remove the UMD wrapper

### PR DESCRIPTION
**Pull request by ipeychev**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b4d2327e6f...c37e4b6bc2

**Comment by brianchandotcom** [comment]
@ipeychev how are we going to "log" this and remember to do this on our next upgrade?

**Comment by ipeychev** [comment]
Hello Brian,

You mean when we upgrade from 6.2 to 7? If so, there will be nothing to upgrade, this code is new, we didn't have it in 6.2. Or you meant something else?

@brianchandotcom

**Comment by brianchandotcom** [comment]
No, I mean when we upgrade Jquery. If we modify their code... we won't know to reapply this change.

**Comment by ipeychev** [comment]
Oh, I see (I will answer in the email thread you sent)

**Pull request closed without merging**
