### PR TITLE
LPS-78438

### PR DESCRIPTION
**Pull request by marco-leo**
Using liferay-ui:page-iterator and passing a url without parameters will break the urls generated for the selection of the delta.

### CODE REVIEW

**Comment by marco-leo** [comment]
ci:test

**Comment by marco-leo** [comment]
Hey @jpince .  I don't think those test failing are related to the pull.  What do you think?

**Comment by marco-leo** [comment]
ci:retest

**Comment by marco-leo** [comment]
@brianchandotcom The test that is failing doesn't looks related to my changes /cc  @jpince

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fd3cf0c988...8c45d69313

**Comment by brianchandotcom** [comment]
@marco-leo I found this line weird:

```
String href = url = HttpUtil.removeParameter(url, curParam);
```

So I fxied it in 23d8623d471f74af26a7d90c5eadc459275c7bcb

Fyi.

**Comment by marco-leo** [comment]
@brianchandotcom thanks!

**Pull request closed without merging**
