### PR TITLE
LPS-97644 Update liferay-npm-scripts to v4.3.0

### PR DESCRIPTION
**Pull request by wincent**
Two major changes:

1.  Support `async`/`await` in tests.

2.  Reimplement linting to handle all globbing internally and operate via JS APIs rather than forking external processes.

    The motivation for this change is so that we can run "checkFormat" in CI only on a subset of the files that were changed in a given PR, instead of across all front-end files. This would be pretty awkward to do if we don't handle the globbing.

    Bonuses:

    - This is much faster even without running against a subset (full runs have dropped from about 50s to 25s on my laptop).
    - We have uniform globbing now (instead of being beholden to the idiosyncrasies of how Prettier and ESLint handle globs), which means that we can expand our coverage a little bit.
    - Because we read the .eslintignore and .prettierignore files directly, we can permit a more flexible structure (eg. ignoring leading whitespace), which means that we can indent the sections within those files to match the pattern in "portal-impl/src/portal.properties".

    So, this PR also includes the fixes for the lint errors reported here:

    https://github.com/brianchandotcom/liferay-portal/pull/75268

    and for the files which weren't previously covered but now are.

I'll work with @hhuijser and @petershin to figure out the best way to set up the file-subsetting behavior in CI runs.

### CODE REVIEW

**Comment by wincent** [comment]
```
ssh: Could not resolve hostname github.com: Name or service not known
fatal: Could not read from remote repository.
```

😂

**Comment by wincent** [comment]
ci:reopen

**Comment by wincent** [comment]
ci:test:sf

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@pyoo47 see all the random SSH errors. Thx.

**Pull request closed without merging**
