### PR TITLE
LPS-71971

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/07fbac48db...8cf5739423

**Comment by brianchandotcom** [comment]
@mhan810 please backport? Thx.

**Comment by mhan810** [comment]
Will do

**Comment by mhan810** [comment]
@brianchandotcom hey this is a new feature and we don't need to backport this.

**Pull request closed without merging**
