### PR TITLE
LPS 179794

### PR DESCRIPTION
**Pull request by rotty3000**
- LPS-179794 Allow batch client extensions to have any name
- LPS-179796 Define an instance configuration client extension which allows setting Liferay Virtual Instance settings
- LCD-24326 align workspace terms with documentation
- LPS-179794 add the batch client extension type and the oauth required for LXC

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:reopen

**Comment by rotty3000** [comment]
cc @gamerson

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b23c0802bb...616cf2e938

**Comment by brianchandotcom** [comment]
@rotty3000 see 2a9bf09e91433e57554ad5e498acba748364f419 and 8dfb55452410f8adfb2e7bd855746c4f065cfb87

**Pull request closed without merging**
