### PR TITLE
LPS-102664 | LPS-105732 Bump

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by jpince** [comment]
@cvanut another one `FormRules#ConfigureCalculateRule`

**Comment by jpince** [comment]
@inacionery semver errors, including a breaking change (`Bundle Version Change Recommended: 6.0.0`). I don't know if BChan will allow the breaking change.
```
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.kernel.workflow                 MAJOR      9.0.0      9.0.0      10.0.0     VERSION INCREASE REQUIRED
     [exec] 	>   class      com.liferay.portal.kernel.workflow.WorkflowTaskManagerUtil
     [exec] 		-   method     search(long,long,java.lang.String,java.lang.String,java.lang.String[],java.lang.Long[],java.util.Date,java.util.Date,java.lang.Boolean,java.lang.Boolean,java.lang.Boolean,int,int,com.liferay.portal.kernel.util.OrderByComparator)
     [exec] 			-   access     static
     [exec] 			-   return     java.util.List
     [exec] 		+   method     search(long,long,java.lang.String,java.lang.String[],java.lang.String[],java.lang.Long[],java.lang.Long[],java.util.Date,java.util.Date,java.lang.Boolean,java.lang.Boolean,java.lang.Long[],java.lang.Boolean,int,int,com.liferay.portal.kernel.util.OrderByComparator)
     [exec] 			+   access     static
     [exec] 			+   return     java.util.List
     [exec] 		-   method     searchCount(long,long,java.lang.String,java.lang.String,java.lang.String[],java.lang.Long[],java.util.Date,java.util.Date,java.lang.Boolean,java.lang.Boolean,java.lang.Boolean)
     [exec] 			-   access     static
     [exec] 			-   return     int
     [exec] 		+   method     searchCount(long,long,java.lang.String,java.lang.String[],java.lang.String[],java.lang.Long[],java.lang.Long[],java.util.Date,java.util.Date,java.lang.Boolean,java.lang.Boolean,java.lang.Long[],java.lang.Boolean)
     [exec] 			+   access     static
     [exec] 			+   return     int
     [exec] 	>   interface  com.liferay.portal.kernel.workflow.WorkflowTaskManager
     [exec] 		-   method     search(long,long,java.lang.String,java.lang.String,java.lang.String[],java.lang.Long[],java.util.Date,java.util.Date,java.lang.Boolean,java.lang.Boolean,java.lang.Boolean,int,int,com.liferay.portal.kernel.util.OrderByComparator)
     [exec] 			-   return     java.util.List
     [exec] 		+   method     search(long,long,java.lang.String,java.lang.String[],java.lang.String[],java.lang.Long[],java.lang.Long[],java.util.Date,java.util.Date,java.lang.Boolean,java.lang.Boolean,java.lang.Long[],java.lang.Boolean,int,int,com.liferay.portal.kernel.util.OrderByComparator)
     [exec] 			+   return     java.util.List
     [exec] 		-   method     searchCount(long,long,java.lang.String,java.lang.String,java.lang.String[],java.lang.Long[],java.util.Date,java.util.Date,java.lang.Boolean,java.lang.Boolean,java.lang.Boolean)
     [exec] 			-   return     int
     [exec] 		+   method     searchCount(long,long,java.lang.String,java.lang.String[],java.lang.String[],java.lang.Long[],java.lang.Long[],java.util.Date,java.util.Date,java.lang.Boolean,java.lang.Boolean,java.lang.Long[],java.lang.Boolean)
     [exec] 			+   return     int
     [exec] [Baseline Warning] Bundle Version Change Recommended: 6.0.0
```
there are other semver errors, please see the log or run baseline

**Comment by inacionery** [comment]
Hey @jpince,

We are trying to merge it since https://github.com/brianchandotcom/liferay-portal/pull/82559, these breaking change happened because the artifacts were published yesterday. 

@brianchandotcom, should I send you a PR with the bumps? Or could you please republish the artifacts with these changes?

Thanks!

**Comment by jpince** [comment]
@inacionery talked to BChan about this, he said resend with all bumps, including the version increase in `bnd.bnd`. Republishing with the same major version number isn't an option.

**Comment by inacionery** [comment]
@jpince Thanks! I'll send tomorrow

**Pull request closed without merging**
