### PR TITLE
LPS-75798

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@petershin

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
Closing until the performance issue with the other custom-sql logic has been resolved

**Comment by petershin** [comment]
@hhuijser - Sent pulls to update the subrepos:

https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/515
https://github.com/liferay/com-liferay-journal/pull/525

**Pull request closed without merging**
