### PR TITLE
LPS-63232 Fix module references in build files

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7efb42ca9a...cb3cfeebc2

**Comment by brianchandotcom** [comment]
@adolfopa bravo!

@peterfellwock fyi this is a really good example of taking an existing plugin WAR structure and merging it in as a module

@cgoncas can you update Adolfo's upgrade? He didn't apply the latest patterns and has a few errors.

@jorgeferrer cc

Thx everyone!

**Comment by peterfellwock** [comment]
@adolfopa great job, nice pattern to follow.

**Pull request closed without merging**
