### PR TITLE
Lps 70607

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@brianchandotcom, @stsquared99 should be added to the allowed user list for commits without ticket info, right?

**Comment by stsquared99** [comment]
@shuyangzhou I can fix that next week (waiting on another fix from Brian), sorry for the trouble.

**Comment by stsquared99** [comment]
@shuyangzhou This should be fixed now.
Thanks

**Comment by shuyangzhou** [comment]
Thanks @stsquared99 !

**Pull request closed without merging**
