### PR TITLE
LPS-67650

### PR DESCRIPTION
**Pull request by matethurzo**
cc @danielkocsis

Brian I've notified the area leaders in a slack channel about this.

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
the failed tests are unrelated

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b24b1fb1ea...0c9303c642

**Comment by brianchandotcom** [comment]
@matethurzo I made a few changes  in upstream. Thx.

**Pull request closed without merging**
