### PR TITLE
LPS-70873 Unable to save configurations if user locale and company locale do not match

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-70873](https://issues.liferay.com/browse/LPS-70873).<br><br>Hey Brian, this reverts a change that should only have been merged into the ee branch.  See https://github.com/brianchandotcom/liferay-portal-ee/pull/16000#issuecomment-281669460.  Thanks!<br><br>/cc @dacousalr @stattuskuo

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@dacousalr what about 7.0.x? I'm leaving it in there. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by dacousalr** [comment]
@brianchandotcom leave it there, please.

Thanks

**Pull request closed without merging**
