### PR TITLE
LPS-66016 Portlets added to Nested Portlets are not carried over to 7.0

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:/  @jhendley

**Comment by pyoo47** [comment]
One of the tests froze during portal startup (modules-integration-hypersonic)

```
     [exec] 09:00:22,161 INFO  [fileinstall-/opt/dev/projects/github/liferay-portal/bundles/osgi/war][ThemeHotDeployListener:94] Registering themes for user-dashboard-theme
     [exec] 09:00:22,524 INFO  [fileinstall-/opt/dev/projects/github/liferay-portal/bundles/osgi/war][ThemeHotDeployListener:109] 1 theme for user-dashboard-theme is available for use
     [exec] 09:00:22,683 INFO  [fileinstall-/opt/dev/projects/github/liferay-portal/bundles/osgi/war][BundleStartStopLogger:35] STARTED user-dashboard-theme_7.0.1 [521]
Build timed out (after 120 minutes). Marking the build as aborted.
Build was aborted
Recording test results
Liferay patched class hudson.tasks.junit.JUnitResultArchiver
No test report files were found. Configuration error?
```

**Comment by jkappler** [comment]
ci:retest

**Comment by jkappler** [comment]
thanks @pyoo47, retesting

**Comment by jpince** [comment]
no relevant functional failures, 606Upgrade is still running in Postgre despite c41e978, will send another pull to remove.
@brianchandotcom please merge

**Comment by brianchandotcom** [comment]
@jkappler Thanks for catching my mistake!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/57a70b6101...5ef3e72fda

**Comment by pyoo47** [comment]
ci:stop

**Pull request closed without merging**
