### PR TITLE
LPS-85585 Pages are not visible after selecting fjord template

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jpince** [comment]
ci:close @jkappler functional tests are stalling when trying to hit localhost `Waiting for http://localhost:8080/web/guest to load`

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:reopen

**Comment by brianchiu** [comment]
I tested this pull and was not able to reproduce the failures in CI. I also validated that the pull fixes the bug it was intending to fix. I am reopening this pull.
expected

**Comment by jkappler** [comment]
@brianchiu, I see a NPE, will fix on Monday

**Pull request closed without merging**
