### PR TITLE
LPS-75071 Simplifies logic

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @sergiogonzalez, I see a spike in failing tests in https://github.com/sergiogonzalez/liferay-portal/pull/4153#issuecomment-351381856. Might be good to hold this off and bring in QA to make sure it's not breaking anything else.

**Comment by sergiogonzalez** [comment]
Hey @austinchiang @patriciajeanperez can you guys take a look at it to see if this pull actually breaks some tests?
Considering the stauts of the CI and the number of failing tests it's hard for us to tell...

**Comment by patriciajeanperez** [comment]
Hey @sergiogonzalez, I re-ran the tests with these changes and got the same failures from https://github.com/sergiogonzalez/liferay-portal/pull/4153#issuecomment-351381856. The smoke tests are failing due to a javascript exception: `JAVA_SCRIPT_ERROR: TypeError: a is null`. It occurs when you view a document. Let me know if you have any questions/concerns!

**Comment by brianchandotcom** [comment]
@sergiogonzalez please have QA resend it to me. Thx.

**Comment by sergiogonzalez** [comment]
Hey @marianoalvarosaiz can you take a look at the javascript issue? Thanks!

**Comment by marianoalvarosaiz** [comment]
see https://github.com/jbalsas/liferay-portal/pull/924

**Pull request closed without merging**
