### PR TITLE
LPS-62741

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/04b719886e...ff546f3a06

**Comment by brianchandotcom** [comment]
@hhuijser public will still go before protected and private right? This is just sorting with those right?

**Comment by hhuijser** [comment]
@brianchandotcom 

Right now, this is a temp fix and it will skip sorting those files all together.
I'll work on a proper fix later that will only skip sorting the methods with the @Meta.AD annotation

**Comment by brianchandotcom** [comment]
Thx @hhuijser

**Pull request closed without merging**
