### PR TITLE
LPS-92554 Using pathModule in BulkStatus too

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @brianchandotcom,

With this we use the new bulk REST APIs for tags. Next week we will migrate categories which is a bit more complicated and remove the old APIs.

**Comment by 4lejandrito** [comment]
@nhpatt

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c532634b49...3a12ee07ac

**Comment by brianchandotcom** [comment]
Very very nice. I'm glad we're doing it in phases like this.

**Pull request closed without merging**
