### PR TITLE
Lps 61095

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @mhan810

@dantewang @slnn please run a performance check for LPS-61095, it drops memory footprint by 50MB, should make some difference.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
Hmm @mhan810, the UserImporter.class dependency exposes more issues. For example, the failing LayoutTypePortletImplTest is about the test needs to access LoginPortlet, but there is no explicit waiting for it, it is just assuming the portlet is there. And somehow the UserImporter.class dependency defers the LoginPortlet compoment activation. Creating this race condition that randomly the test sees/not sees the portlet.

I think we need to revisit this throughly again. For now, I am only keeping the UTF8Control changes, as it is not strictly tied to this pull and it drops the memory footprint. I will do more digging on those failures later.

ci:retest

**Comment by shuyangzhou** [comment]
@mhan810 I dug a little deeper,this is what I found.

The UserImporter dependency defers the company initialization a bit. And inside PortletTracker.addingPortlet() line 330, we only really deploy the portlet if there is any company at all. So this company initialization deferring made the PortletTracker.addingPortlet() a nop.

No sure how to deal with it though, as the exist MainServlet.initCompanies() has this same problem already, just the new UserImporter dependency makes it having better chance to show up.

**Comment by shuyangzhou** [comment]
@brianchandotcom This pull is good to go, I will work with mike for the rest part.

**Comment by mhan810** [comment]
Ugh k let's do it on Mon.

Sent from my mobile device.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1d2c0e6c67...789a13d5d4

**Pull request closed without merging**
