### PR TITLE
LPS-79679 Fix incorrect naming

### PR DESCRIPTION
**Pull request by petershin**
@hhuijser @jpince

### CODE REVIEW

**Comment by petershin** [comment]
ci:test

**Comment by jpince** [comment]
Pushed upstream: https://github.com/liferay/liferay-portal/commit/13c6a6b4f26effb5d42e82db120c60a8698ae071

@petershin thanks <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jpince** [comment]
ci:close <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by michaelhashimoto** [comment]
ci:test

**Pull request closed without merging**
