### PR TITLE
LPD-17797: Improve the performance using the set(UnsafeSupplier) method by replacing any set(<Class>) usage of the setter DTO method

### PR DESCRIPTION
**Pull request by 4lejandrito**
## Motivation
Create a SF rule in order to use the `setUnsafeSupplier` instead of using the `set(<Class>)` DTO methods in liferay-portal. You can check the [gist](https://gist.github.com/ling-alan-huang/94f38f9a8be0892023bad4364bba7c51) where SF rule applies and fails.
cc/ @ling-alan-huang

**JIRA Related Ticket**
https://liferay.atlassian.net/browse/LPD-17797

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@4lejandrito @sergiojimcos @ling-alan-huang we have too many unnecessary  finals?

For example:

```
	private void _uniquifyDataDefinitionFields(
		DataDefinitionField dataDefinitionField) {

		String dataDefinitionFieldName = dataDefinitionField.getName();

		dataDefinitionField.setName(() -> "CopyOf" + dataDefinitionFieldName);
```

dataDefinitionField can get inlined.

Please simplify and only add "final" for things that need to be changed and resend (we should still inline anything that can be inlined). Thx.

**Comment by sergiojimcos** [comment]
ci:close

**Comment by sergiojimcos** [comment]
Sent here: https://github.com/brianchandotcom/liferay-portal/pull/149398

**Pull request closed without merging**
