### PR TITLE
LPS-66570 create isActiveGroup method (WAITING FOR master-private feature)

### PR DESCRIPTION
**Pull request by juliocamarero**
This pull requires this other pull to be merged to pass the tests: brianchandotcom/liferay-portal-ee#13959

### CODE REVIEW

**Comment by juliocamarero** [comment]
@michaelhashimoto @brianchandotcom it seems the problem is in the parent-branch-name?

**Comment by juliocamarero** [comment]
cc @jorgediaz-lr

**Comment by brianchandotcom** [comment]
@michaelhashimoto is this a bug in our Jenkins scripts?

**Comment by michaelhashimoto** [comment]
@juliocamarero @brianchandotcom 

This particular commit is trying to reference a commit based in 'master-private':
* [LPS-66570 Update git commit portal ee](https://github.com/brianchandotcom/liferay-portal/pull/42436/commits/0fd9e3a4222d985832034b1b88a34c876ccbccdd)

---

The 'git-commit-portal-ee' file should only be pointing to commits based in 'ee-7.0.x'.

For example it could be a [pull request](https://github.com/brianchandotcom/liferay-portal-ee/pull/13957):
<pre>https://github.com/brianchandotcom/liferay-portal-ee/pull/13957</pre>

Or it could be a git commit within '[ee-7.0.x](https://github.com/liferay/liferay-portal-ee/commits/ee-7.0.x)' ([93fceff](https://github.com/liferay/liferay-portal-ee/commit/93fceff009474ed40dd35a4809567e456fd0c105)):
<pre>93fceff009474ed40dd35a4809567e456fd0c105</pre>

---

I think eventually we should shift over to 'master-private', but right now this feature is not supported.

We are still using the functionality specified in this [blog entry](https://in.liferay.com/web/global.engineering/blog/-/blogs/new-tests-for-the-pull-request-tester-).

**Comment by jorgediaz-lr** [comment]
Hi @michaelhashimoto 

I cannot commit my changes to ee-7.0.x, because I am changing version info of ee modules due to a portal-master API version change, If I commit that version change to ee-7.0.x branch, that modules will not work with portal-7.0 API versions.

We talked this with @zsoltbalogh in the past and he sent a email about this:

> On Fri, Jul 22, 2016 at 12:56 PM, Zsolt Balogh <zsolt.balogh@liferay.com> wrote:
> 
>     Hey Brian, Hashi,
> 
>     The Spanish team told me that we are testing master compatibility with ee-7.0.x:
>     https://github.com/brianchandotcom/liferay-portal/pull/41706
>     https://issues.liferay.com/browse/LRQA-22944
> 
>     I believe that we should not do this and close the master PRs just because they would break the ee-7.0.x compatibility. We are creating a messy policy and create some confusion. I would not like people adjusting ee-7.0.x requirements just to be able to push through master commits.
> 
>     What do you think?
> 
>     Thank you,

And @brianchandotcom said that we should use master and master-private, instead using ee-7.0.x

> On 22/07/2016 22:08, Brian Chan wrote:
> 
>     Oh, that's a mistake. They should be testing it with master with master-private and 7.0.x with 7.0.x-private (or ee-7.0.x) for now.
> 
>     I'll work on fixing that.
    
I was out of office last two weeks, so perhaps I am not updated, is this information correct or we should commit it in other way?

Thank you

@juliocamarero  @kiyoshilee @pyoo47

**Comment by michaelhashimoto** [comment]
@brianchandotcom - Is it possible to just merge this one in for now?

We probably won't be able to get to making the shift to 'master-private' until next week.

We're still working on the Subrepository PR Tester.

**Comment by michaelhashimoto** [comment]
@brianchandotcom - However, we need to make sure to revert the 'git-commit-portal-ee' file.

**Comment by michaelhashimoto** [comment]
@jorgediaz-lr @brianchandotcom - We actually need to wait for the 'master-private' feature to get in before we merge this pull.  So we'll try to get that working early next week.

**Comment by jorgediaz-lr** [comment]
@michaelhashimoto don't worry, we can wait.

Thank you

**Comment by brianchandotcom** [comment]
Please resend after master-private changes. Thx @jorgediaz-lr

**Comment by jorgediaz-lr** [comment]
@michaelhashimoto do you have any estimated date about tests changes from ee-7.0.x to master-private?

Thank you

**Comment by michaelhashimoto** [comment]
@jorgediaz-lr 

Here is the plan we figured out with BChan:

1. We need to copy in all the existing ee-7.0.x private modules into master and still remain green.
 - See this [ticket](https://issues.liferay.com/browse/LRQA-27247) for more information.
 - We are going to work with Shuyang's team to make sure we can safely add all of the private modules into master.
1. Once ee-7.0.x to be green, we'll split 'ee-7.0.x pr tester' into '7.0.x and 7.0.x-private pr tester'.
 - This will prove that the splitting within jenkins works.
1. Once master to be green, we'll split 'master pr tester' into 'master and master-private pr tester'.

Sorry, we have to wait on these updates before moving onto this split.

**Comment by jorgediaz-lr** [comment]
Hi @michaelhashimoto 

Thank you for the info, I will watch the LRQA-27247 ticket

**Pull request closed without merging**
