### PR TITLE
LPS-74459 Unable to grant roles to user who belongs to multiple sites when SPA is disabled

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-74459](https://issues.liferay.com/browse/LPS-74459).<br><br>/cc @pei-jung @hhuijser @arthurchan35

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:retest

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@petershin @hhuijser I'm not able to duplicate this SF error locally?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6462e2620c...2da3f25bc0

**Pull request closed without merging**
