### PR TITLE
 LPS-79686 Turn failing tests off to investigate

### PR DESCRIPTION
**Pull request by patriciajeanperez**
cc @4lejandrito

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:test

**Comment by patriciajeanperez** [comment]
ci:reopen

**Comment by patriciajeanperez** [comment]
from @4lejandrito (https://github.com/brianchandotcom/liferay-portal/pull/57913):

> Hi @brianchandotcom,
> 
> I am not sure why the CI is complaining about baseline. The problem is a change from 2.2.0 to 2.3.0 but the latter is already the version on master (see d8fce30).
> 
> I get no errors running gradlew baseline locally inside modules/apps/collaboration/document-library.
> 
> Thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5909844d6d...c934e3343e

**Comment by brianchandotcom** [comment]
@patriciajeanperez wow, you're right. I wasn't able to reproduce it either. Pushing it to upstream and will monitor what happens to other pulls.

**Comment by patriciajeanperez** [comment]
cc @liuxingye

**Pull request closed without merging**
