### PR TITLE
LPS-53235 Registry.getService() and @Inject

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/41443be0dc...68a284194d

**Comment by brianchandotcom** [comment]
@ithildir is this right ? modules/core/registry-test/build.gradle

@Preston-Crary can you backport this?

**Comment by brianchandotcom** [comment]
@petershin see  modules/core/registry-test/build.gradle

**Comment by Preston-Crary** [comment]
Backport:
https://github.com/brianchandotcom/liferay-portal-ee/pull/18175

**Pull request closed without merging**
