### PR TITLE
LPS-53855 Update com.liferay.ant.bnd to bnd 2.4.1

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
Hey @brianchandotcom could you please update the SDK with this version of ant-bnd and then the core with the updated SDK? thx.

**Comment by rotty3000** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Shuyang is working on a fix for these random OSGi errors, see https://github.com/brianchandotcom/liferay-portal/pull/24362

Hopefully it'll at least make CI more stable, but we'll need to figure out how to shutdown and fix the osgi state properly in real life.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8fd430edd4...f7ed2a48b6

**Pull request closed without merging**
