### PR TITLE
LPS-91017 Replace journal article references first because ddm form processor is waiting for the json object

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
/cc @ealonso

@brianchiu Is it possible to add a test for this case? It seems to be broken for a long time already...

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@pavel-savinov we need a test for this or some future dev is going to change the order again.

**Comment by brianchiu** [comment]
@pavel-savinov 
Yep. We can make a test for this.

**Pull request closed without merging**
