### PR TITLE
LPS-64939 Move tests from portal-impl to portal-search-test

### PR DESCRIPTION
**Pull request by arboliveira**
Re-sending https://github.com/brianchandotcom/liferay-portal/pull/38117 in smaller pieces.

### CODE REVIEW

**Comment by arboliveira** [comment]
Test failures seem unrelated.

**Comment by brianchandotcom** [comment]
@shuyangzhou this SQLTest has been failing a lot lately, like more than 50% of the time.

**Comment by shuyangzhou** [comment]
Checking on it...

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c7536a1cec...a6c4c6270a

**Comment by brianchandotcom** [comment]
@marcellustavares I've seen you use a PermissionChecker pattern before that is similar to DummyPermissionChecker... perhaps help @arboliveira if he can't find it a simpler way.

**Comment by brianchiu** [comment]
@alee8888

See the test failure.

**Comment by alee8888** [comment]
@brianchiu 
I looked at the test failure and it looks to be a fluke. I checked Testray (http://tinyurl.com/gmu7aau) and it has only failed 1 in 75 times. It is very similar to the errors in LPS-64940 that was recently filed for ee-7.0.x.

**Pull request closed without merging**
