### PR TITLE
LPS-197582: RestBuilder doesn't create a body with Content-Type is 0 when there is no body

### PR DESCRIPTION
**Pull request by sergiojimcos**
## Motivation
The aim of this PR is to set Content Length equal to 0 for all the methods that have several several parameter but it doesn't have any Request Schema or no request body.

**What is new?**
- Define an empty List in the `client_resource.ftl`.
- buildREST in all modules.

**JIRA Related Ticket**
https://liferay.atlassian.net/browse/LPS-197582

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:reopen

**Comment by sergiojimcos** [comment]
Rebase form here: https://github.com/liferay-headless/liferay-portal/pull/1557

**Comment by brianchandotcom** [comment]
Merged. Thank you.

**Comment by brianchandotcom** [comment]
@sergiojimcos see my simplification in 32abf16a9de11fcbfba53f1fa4b18abb19ffe3ee

**Pull request closed without merging**
