### PR TITLE
LPS-107548 SF

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:stable

**Comment by 4lejandrito** [comment]
Hey @austinchiang,

I fixed the related failures in the previous pull. I don't think the ones we are having now are related by I cannot tell with confidence. Could you please have a look?

Thanks!

**Comment by austinchiang** [comment]
@4lejandrito 3 tests were fixed:
```
com.liferay.portal.kernel.language.LanguagePropertyTest.testValidKeyLineBegin
com.liferay.portal.kernel.language.LanguagePropertyTest.testValidKeyDir
com.liferay.portal.kernel.language.LanguagePropertyTest.testValidKeyLineEnd
```

The rest are still failing with the same errors:
```
com.liferay.portal.kernel.language.LanguagePropertyTest.testValidKeyUserDefaultPortrait
com.liferay.portal.kernel.language.LanguagePropertyTest.testUserNameRequiredFieldNamesSubsetOfUserNameFieldNames
com.liferay.portal.kernel.language.LanguagePropertyTest.testValidKeyUserInitialsFieldNames
com.liferay.portal.kernel.language.LanguagePropertyTest.testValidKeyUserNameFieldNames
com.liferay.portal.kernel.language.LanguagePropertyTest.testValidKeyUserNameRequiredFieldNames```
The latest Master Acceptance run showed the same results as above:
https://testray.liferay.com/home/-/testray/case_results/1024780466
https://testray.liferay.com/home/-/testray/case_results/1024749069
https://testray.liferay.com/home/-/testray/case_results/1024775018
https://testray.liferay.com/home/-/testray/case_results/1024753626
https://testray.liferay.com/home/-/testray/case_results/1024759904

Hope it helps

**Comment by 4lejandrito** [comment]
@austinchiang can we than say that this is safe to merge?

**Comment by brianchandotcom** [comment]
@drewbrokke please fix the Language tests. Thx!

**Comment by austinchiang** [comment]
@4lejandrito The failing tests were not caused by this pull. They are documented in https://issues.liferay.com/browse/LPS-108624

**Comment by 4lejandrito** [comment]
Safety is an illusion. Thanks @austinchiang!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b24c402f38...06694fef3e

**Comment by brianchandotcom** [comment]
@austinchiang see d0131f4d6560ee2a1760edbd8131ce86ab762860 and 7fea84825d6d53269ee5df89fac23a551b380bb7

**Pull request closed without merging**
