### PR TITLE
LPS-63228 buildLang

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
cc @marcellustavares

**Comment by marcellustavares** [comment]
Awesome @leoadb :+1:

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/dc1c689df5...3d2db38640

**Comment by brianchandotcom** [comment]
Thx @leoadb !

**Pull request closed without merging**
