### PR TITLE
LPS-79447 Use new configuration logic for validation in the test

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@rafaprax 

```
does-not-contain=Does Not Contain
does-not-match=Does Not Match
is-greater-than=Is greater than
is-greater-than-or-equal-to=Is greater than or equal to
is-less-than=Is less than
is-less-than-or-equal-to=Is less than or equal to
is-not-email=Is Not Email
is-not-empty=Is not empty
is-not-equal-to=Is not equal to
is-not-url=Is Not URL
```

is-not-url=Is Not URL

and 

is-not-email=Is Not Email

are not consistent with the rest. Should they be sentences, or titles, or phrases?

Sentence: This is a sentence.
Title: A Very Fun Game
Phrase: I like you

In general, I avoid phrases. There are exceptions where when it makes sense on the UI.

In general, I prefer sentences or titles.

Please fix other lang keys that are part of this pull. Thx.

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Hello @brianchandotcom , thank you a lot for the clarification! For the ui context, it makes more sense to be a Phrase. I will send another PR with the changes. Thank you!

**Comment by rafaprax** [comment]
@brianchandotcom Thanks for the clarification.

**Pull request closed without merging**
