### PR TITLE
LPS-78368 Apply new ManagementToolbar pattern to roles-admin-web

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
Tests passed here with no unique failures https://github.com/alee8888/liferay-portal/pull/590#issuecomment-393007686

**Comment by jpince** [comment]
@yichenroy @michaelhashimoto @kenjiheigel looks like the ci bot is removing the `ci:test:sf - pending` label without replacing it with `ci:test:sf - success`. Looks like it's happening in all pulls. 

This pull also removed `ci:test:relevent - pending` before the tests finished. I don't see this in other pulls.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by pyoo47** [comment]
@jpince Regarding the ci:test:sf labels, this is a known issue. As far as we can tell, we think it is a problem on the GitHub side. We know it's not because we are running out of api calls but aside from that we don't know what the problem is. We've deprioritized this issue because the sf build at least runs and reports its results in the pr message.

**Pull request closed without merging**
