### PR TITLE
master-bc-1230

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LRQA-22520

### CODE REVIEW

**Comment by brianchiu** [comment]
@alee8888 @vicnate5
I'm removing the calendar test from the PR tester. It's failing too often (potentially a consistent failure but I haven't looked through all the pulls yet)

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/33bf4a49a1...e57dd7a226

**Comment by brianchandotcom** [comment]
@brianchiu @alee8888 @vicnate5 that calendar test always fails in the afternoon... but not in the morning. It's a time zone test, so I bet you it's a time zone issue.

**Pull request closed without merging**
