### PR TITLE
LPS-139169 Fix broken SF

### PR DESCRIPTION
**Pull request by mbowerman**
Hi @brianchandotcom,

The SF is failing right now because Test methods annotated with the `@Test` annotation must begin with the word "test" (see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/java/com/liferay/source/formatter/checks/JavaTestMethodAnnotationsCheck.java#L60).

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:reopen

**Comment by mbowerman** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@mbowerman my  bad!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c16d38dbdf...f8ab27036a

**Pull request closed without merging**
