### PR TITLE
Lps 85005 2

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@tomwang2011 is going to resend.

I read that while "zip" may honor timestamp, there are still unzip ones (notably native Windows) that won't honor timestamps.

We have to move to 7z. I called him and let Tom know to change our <zip calls to <7z

There is a 7z library for Ant.

**Comment by tomwang2011** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2f0cd41abb...7775810d9c

**Comment by brianchandotcom** [comment]
@tomwang2011 minor changes in upstream.

**Pull request closed without merging**
