### PR TITLE
LPS-74728 Pass the fieldSetClassNameId to the form-builder taglib

### PR DESCRIPTION
**Pull request by rafaprax**
\cc @leoadb

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:reopen

**Comment by rafaprax** [comment]
ci:retest

**Comment by jpince** [comment]
@rafaprax POSHI error: `java.lang.Exception: Element is not present at "//div[contains(@class,'col col-md-12')]//button[contains(@class,'add-button-large')]/span"`

cc/ @vicnate5 @rodrigo-e-c-souza

**Comment by jpince** [comment]
ci:close

**Comment by vicnate5** [comment]
@rafaprax Form builder does not load on this pull.

**Comment by rafaprax** [comment]
I'll take a look on that

**Comment by rafaprax** [comment]
resent at https://github.com/brianchandotcom/liferay-portal/pull/52475

**Pull request closed without merging**
