### PR TITLE
pr-3251

### PR DESCRIPTION
**Pull request by gabrielwas**
From @ealonso original PR:

Motivation
---
Fix some issues related with objects and collections. There are 3 bug fixes in this pr.

[Link to the issue](https://issues.liferay.com/browse/LPS-167929) 

Proposed solution
---
1. Avoid null pointer exception when there are no object entries in table renderer.
2. Change log level, since objectLayout can not exist and we are logging unnecessary errors always.
3. Uses correct classNames, that means use `com.liferay.object.model.ObjectDefinition#objectDefinitionId` instead of `ObjectEntry.class.getName()`.

Steps to reproduce
---
**For 1 and 2:**

1. Menu > Control Panel > Picklists
2. Create a Custom Picklist
3. Add fields on Custom Picklist
4. Menu > Control Panel > Objects
5. Create a Custom Object
6. On Custom Object, add Custom Field (Picklist) related to the Custom Picklist
7. Publish it
8. Go to Menu side > Site builder > Pages
9. Add a new page (Blank)
10. Go to Fragments and Widgets
11. Search for Collection Display
12. Select collection > Collection Providers > Custom Object
13. Change Style Display to Table
14. View table

**For 3:**

1. Create a simple Object (e.g.: Bookmark)
2. Add a text field
3. Save and Publish this Object
4. Go to the page editor
5. Add a Collection Display
6. Go to Collections → Collection Provider
7. Select Bookmarks as Collection Provider

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:reopen

**Comment by gabrielwas** [comment]
BPM QAs checked the unique failures and they are not related to the changes. 

Original PR: https://github.com/liferay-objects/liferay-portal/pull/1362

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/30abd7ac86...17cecf0849

**Comment by brianchandotcom** [comment]
@gabrielwas @ealonso @DiegoHu97 see 17cecf08498123476648f41eef78afdcdf9b5bad

**Pull request closed without merging**
