### PR TITLE
LPS-68901

### PR DESCRIPTION
**Pull request by vicnate5**
7.0.x branches Only. Portlet is not present on master. 

CC @marcellustavares @ctampoya

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:reopen

**Comment by marcellustavares** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@vicnate5 @marcellustavares please resend. CI errors.

**Comment by vicnate5** [comment]
ci:reopen

This is for 7.0.x Some of the backend tests are broken but they are not related to this pull. We cannot send this to master because the portlet does not exist there.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
