### PR TITLE
LPS-76173 Auto

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by jpince** [comment]
@ealonso SF issue
`     [java] Exception in thread "main" java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Unable to format ./modules/apps/web-experience/asset/asset-category-property-service/src/main/java/com/liferay/asset/category/property/service/persistence/impl/AssetCategoryPropertyFinderImpl.java`

@petershin @hhuijser any ideas for this failure? I've never seen this one before

**Comment by petershin** [comment]
@jpince @hhuijser Sent a fix for the issue. See https://github.com/brianchandotcom/liferay-portal/pull/53408

**Comment by jpince** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8c9d921c64...d0e89d0ad6

**Comment by hhuijser** [comment]
Hey @juliocamarero @ealonso

The NPE in SF actually reveals something.
We have these two statics pointing to non-existing custom SQL: https://github.com/liferay/liferay-portal/blob/master/modules/apps/web-experience/asset/asset-category-property-service/src/main/java/com/liferay/asset/category/property/service/persistence/impl/AssetCategoryPropertyFinderImpl.java#L40-L44

These custom queries were removed for LPS-52588 (https://github.com/liferay/liferay-portal/commit/61e408c49be7283cfc53b7bb1c780cd6820829d3), but the AssetCategoryPropertyFinder* classes were not deprecated?

Should these classe be deprecated (all the other AssetCategoryProperty were deprecated on LPS-52588)?

**Comment by ealonso** [comment]
Hey @hhuijser,

I think I removed those custom SQL by mistake, I've readded here https://github.com/brianchandotcom/liferay-portal/pull/53423.

Thanks you very much!!!

Eudaldo

**Pull request closed without merging**
