### PR TITLE
LPS-72656

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@juliocamarero, about 90% sure this fixes the Jenkins issue here https://github.com/liferay/com-liferay-osb-faro-site-private/pull/80

**Comment by juliocamarero** [comment]
👏 👏 👏 👏 👏 👏

**Comment by juliocamarero** [comment]
fyi @epgarcia

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
