### PR TITLE
LPS-97078 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-97078

### CODE REVIEW

**Comment by austinchiang** [comment]
@manoelcyreno FYI I've added a new test file for Canonical URLs in the WEM directory since the feature is under the `WCM > SEO` component in JIRA, but categorized it under the [Collaboration component](https://github.com/brianchandotcom/liferay-portal/pull/76084/commits/7ec53223b109aca20eed00ad6b19105a2761b92f#diff-7a40367ab2f1ed029554a7d14c20086bR1) since my team will be maintaining the cases

**Comment by brianchandotcom** [comment]
@austinchiang can I backport this to 7.2.x even though the SEO stuff is not in 7.2.x yet? We will backport it shortly and I'd like to keep things in sync if possible. Well, it's backported. if it breaks in 7.2.x - please send me a pull to add @Ignore

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c21772b37c...3eef8c3dd1

**Comment by austinchiang** [comment]
Sounds good @brianchandotcom. I'll send you future tests for SEO stuff on both branches

**Pull request closed without merging**
