### PR TITLE
Site Initializer - _addTaxonomyVocabularies

### PR DESCRIPTION
**Pull request by joseabelenda**

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1ac31316e4...0aa32a4ec9

**Comment by brianchandotcom** [comment]
@joseabelenda @nicolas-sss 

https://github.com/joseabelenda/liferay-portal/commit/cbd7142b485ee66c3b6e9d24d99e44ca2fcf4667

is modifying a generated file. You can see it because of this line https://github.com/joseabelenda/liferay-portal/blob/cbd7142b485ee66c3b6e9d24d99e44ca2fcf4667/modules/apps/headless/headless-admin-taxonomy/headless-admin-taxonomy-impl/src/main/java/com/liferay/headless/admin/taxonomy/internal/resource/v1_0/factory/TaxonomyVocabularyResourceFactoryImpl.java#L55

It has the Generated annotation. It's generated by REST Builder. I want to show you tomorrow how I fixed it, but you can see it now in 9b90e1e9 and c85c7260

Good job finding the bug though.

See 4b554bd4270e3f78771132c82bcfc3872c164175 and 0aa32a4ec9952bded5e37c35c562821a92c1144e

I'd like to explain the yoga thing tomorrow.

**Comment by joseabelenda** [comment]
@brianchandotcom 
Just to show you and talk when is possible.

Thanks!

**Comment by joseabelenda** [comment]
Thanks and congrats @nicolas-sss

**Pull request closed without merging**
