### PR TITLE
LPS-103012 Fix lint issues

### PR DESCRIPTION
**Pull request by wincent**
Some formatting issues, some problems identified by ESLint, and some dead code (the "test" ref was removed in 8585a2dfd0d9f51e2c8cb02).

### CODE REVIEW

**Comment by wincent** [comment]
cc @ambrinchaudhary for the changes to the item-selector-taglib

**Comment by ambrinchaudhary** [comment]
Thank you @wincent, I was trying to send the fix to Brian but still were getting errors: https://github.com/brianchandotcom/liferay-portal/pull/79392

**Comment by wincent** [comment]
Resent as: https://github.com/brianchandotcom/liferay-portal/pull/79402

**Comment by wincent** [comment]
@ambrinchaudhary It looks like there was a bad whitespace character in one of the files, which Prettier doesn't complain about but [the Java source formatter does](https://github.com/brianchandotcom/liferay-portal/pull/79401#issuecomment-540516633). I think #79402 should be good though.

You can't see it if you look with GitHub, but if you look at the bytes in the file you can see it's a C2 OA (non-breaking space in UTF-8).

**Pull request closed without merging**
