### PR TITLE
LPS-52768 We need to wait until the portlet is registered

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/73c8b93c75...74ab6cccd7

**Comment by brianchandotcom** [comment]
@ealonso please see my changes in upstream. I renamed the method. Thx.

**Pull request closed without merging**
