### PR TITLE
LPS-71050

### PR DESCRIPTION
**Pull request by danielkocsis**

### CODE REVIEW

**Comment by danielkocsis** [comment]
ci:reopen

**Comment by danielkocsis** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@danielkocsis can you move this logic to the Base* class

```
	public default boolean isSupportsDataStrategyCopyAsNew() {
		return true;
	}

	public default boolean isSupportsDataStrategyMirrorWithOverwriting() {
		return true;
	}
```

I'd like to keep the interfaces free from implementations, even default ones.

Thx.

**Comment by holatuwol** [comment]
@brianchandotcom, no matter how we analyze it, this is a `ConsumerType` interface, so if we modify it without providing a default implementation, it will result in a major version increase which means if we fix it without a default implementation, it can never be backported.

Is there a reason we want to keep the interfaces free from implementations?

**Comment by holatuwol** [comment]
ci:open

**Comment by holatuwol** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f8b0cec6fb...4c87e4de8f

**Comment by brianchandotcom** [comment]
In general, I prefer a clean interface with a Base implementation. I find that less complicated. But if it messes up baseline, then we can go with your solution.

Merging as is.

Thx @holatuwol

**Pull request closed without merging**
