### PR TITLE
LPS-98857 SF

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@leoadb @cleydyr I sent this to @tinatian in https://github.com/tinatian/liferay-portal/pull/1488

It seems strange to me.

@shuyangzhou fyi.

**Comment by tinatian** [comment]
@brianchandotcom 
The changes looks good to me, even though the first commit is kind of confusing, @leoadb makes it more clear.

When using thread local cache, you need to fetch the cache each time you use it instead of fetching and storing it for later use, cause it is related to thread, the one you fetched earlier may not be the right one for current thread.

Tina.

**Comment by cleydyr** [comment]
Hi, @brianchandotcom 

Will we proceed with this PR or are we waiting for validation of the fix by Shuyang as well? Is there anything pending on my side or Leo's?

Thank you

**Pull request closed without merging**
