### PR TITLE
OAUTH2-251 Scope aliases to application permissions table loses information - resent

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Hi Brian. We've peer reviewed everything now and I am sending on top of https://github.com/stian-sigvartsen/liferay-portal/pull/151 as you requested https://github.com/brianchandotcom/liferay-portal/pull/71608#issuecomment-483356265.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c1cf8c9a6d...81be1ad32c

**Comment by brianchandotcom** [comment]
@hhuijser we need to standardize our JAXRS application names.

See 81be1ad32c32c7fd7001f74e29cbead604e919cf

@csierra @stian-sigvartsen please see how I'm naming them for Headless, see the commit 81be1ad32c32c7fd7001f74e29cbead604e919cf

I want you guys to come up with a naming standard for all your jax rs apps.

@hhuijser we should enforce this before the release. Need help. Thx.

**Comment by stian-sigvartsen** [comment]
Thanks @brianchandotcom . We also need to provide language keys for each jax-rs app. Scopes and application names. I've been discussing it with @nhpatt today

**Comment by hhuijser** [comment]
@stian-sigvartsen can you email me the rules?

**Pull request closed without merging**
