### PR TITLE
LPS-134658 | master

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-134658

Hi @brianchandotcom 
Resending this pull directly to you since after a few retries we confirmed this pull is not related to any of the failing tests in https://github.com/liferay-lima/liferay-portal/pull/2059, thanks!

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a1b5924cf5...b2b9b91314

**Comment by brianchandotcom** [comment]
@liuxingye see bcdb6e2296959fb24a0f4befe203273b147f83e8

**Pull request closed without merging**
