### PR TITLE
LRAMF-410 Updating alloy framework for osgi support (round 2)

### PR DESCRIPTION
**Pull request by ethanbustad**

### CODE REVIEW

**Comment by ethanbustad** [comment]
ci:stop

**Comment by ethanbustad** [comment]
ci:retest
Looks like a test failure...

**Comment by ethanbustad** [comment]
ci:retest

**Comment by ethanbustad** [comment]
@jpince any idea where this error is coming from? I don't see it on other PRs -- is one of my changes causing it?

**Comment by ethanbustad** [comment]
ci:retest

**Comment by jpince** [comment]
@ethanbustad failure is unrelated, fixed as of https://github.com/liferay/liferay-portal/commit/579c24a5bbaa2b5010627a3e56cb2ce7f1654b26

**Comment by ethanbustad** [comment]
@jpince alright, thanks!!

**Comment by ethanbustad** [comment]
ci:stop

**Comment by ethanbustad** [comment]
Fixed issues and resent to: https://github.com/brianchandotcom/liferay-portal/pull/51830.

**Pull request closed without merging**
