### PR TITLE
LPS-989513 Define userId variable right before it is used

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
//cc @ealonso

**Comment by ruben-pulido** [comment]
//cc @dgarciasarai

**Comment by dgarciasarai** [comment]
Baseline fixed here https://github.com/brianchandotcom/liferay-portal/pull/81017

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4492f65148...6e56242b9a

**Comment by brianchandotcom** [comment]
@dgarciasarai beautiful.. please backport to 7.2.x and 7.1.x (if relevant)

**Comment by dgarciasarai** [comment]
Thanks Brian :)

**Comment by dgarciasarai** [comment]
Hey Brian, sorry for the delay, I was in DEVCON and on PTO.  I backported this to:
- 7.1.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/27786
- 7.2.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/27787

Thanks :)

**Pull request closed without merging**
