### PR TITLE
LPS-60502

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@JorgeFerrer fyi

**Comment by JorgeFerrer** [comment]
:+1: didn't have time to finish my pull as I intended (too many meetings), so I'll rebuild on top of this.

**Comment by mhan810** [comment]
@brianchandotcom I can't reproduce the SF error locally so have to guess @ what the real error is.

**Comment by brianchandotcom** [comment]
@mhan810 ok, don't worry about the SF. I'll fix it.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/29c41e5a5a...886b21bd4b

**Pull request closed without merging**
