### PR TITLE
LPS-98476 Rename fragmentCollections to fragmentCollectionIds

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
//cc @kyle-miho <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ruben-pulido** [comment]
Thanks @kyle-miho!

Sent to Brian with some minor changes: https://github.com/brianchandotcom/liferay-portal/pull/76037

**Comment by kyle-miho** [comment]
@ruben-pulido Thanks for the sf catches! i wasn't careful enough in this one (trying to just get these in)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/61bdeb6f31...a61317b93e

**Comment by brianchandotcom** [comment]
@kyle-miho see a61317b93e685d7a5c8c92872a0ed5ee3641b3d0

Imagine if you did

```
xyz1
xyz2
xyz3
```

No need for line breaks.

**Comment by brianchandotcom** [comment]
@ruben-pulido good job on a true review!

**Pull request closed without merging**
