### PR TITLE
LPS-98033 Add test for react component

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @brianchandotcom!

This is the first full replacement of a Soy tag in favour of a React-based one. 

We've kept the Soy Java tag around so we keep binary compatibility, but the tld changes to use the React one by default.

/cc @boton, @wincent, @4lejandrito, @ambrinchaudhary

### CODE REVIEW

**Comment by boton** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9f17117114...c1760d7879

**Comment by brianchandotcom** [comment]
Wow @jbalsas @boton this is pretty cool.

**Comment by brianchandotcom** [comment]
@jbalsas I backported this to 7.2.x

**Comment by jbalsas** [comment]
> I backported this to 7.2.x

Great, thanks a lot! 

FYI @4lejandrito, @boton!

**Pull request closed without merging**
