### PR TITLE
Upgrade Process: proper way to hook into the verifiers infra

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by migue** [comment]
Guys, FYI
@juliocamarero, @marcellustavares

**Comment by migue** [comment]
missed @sergiogonzaled , sorry dude

**Comment by marcellustavares** [comment]
@migue, what about DDMServiceVerify?

**Comment by brianchandotcom** [comment]
@marcellustavares those errors I think are real? Please resend. Thx.

**Pull request closed without merging**
