### PR TITLE
LPS-57997 remove code not needed anymore

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by BryanEngler** [comment]
i think the LPS number is wrong in the commit message for this fix

**Comment by brianchandotcom** [comment]
@BryanEngler what should the LPS be?

**Comment by BryanEngler** [comment]
i just did a jira search and it looks like it should be LPS-57977... basically i was working on LPS-57997 and noticed julio was "reviewing" it but i had never sent a pull request...

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6020db7da7...f666a48acc

**Comment by brianchandotcom** [comment]
@juliocamarero @BryanEngler @carloslancha I rebased and changed the ticket to LPS-57977 vs. LPS-57997 (incorrect)

Thx

**Comment by brianchandotcom** [comment]
@BryanEngler good job catching that, no way I would have seen that.

**Comment by brianchandotcom** [comment]
@carloslancha in the future, please cut and paste to avoid these possible mistakes. Thx! Good job on the fix.

**Pull request closed without merging**
