### PR TITLE
LPS-55175

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey Brian,

This is a rebase and resend of https://github.com/brianchandotcom/liferay-portal/pull/26438

Thanks

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6ae51731f7...71ec2aa464

**Comment by brianchandotcom** [comment]
@sergiogonzalez please review my changes. Thx.

**Comment by sergiogonzalez** [comment]
Hey @brianchandotcom I sent you a fix here https://github.com/brianchandotcom/liferay-portal/pull/26492 for commit https://github.com/brianchandotcom/liferay-portal/commit/d13ef31eceecba320fd55b6f5dec98f95a2481b8

Thanks

**Pull request closed without merging**
