### PR TITLE
LPS-76717 Auto

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by ealonso** [comment]
ci:reopen

**Comment by ealonso** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7be59bc8ab...549d277441

**Comment by brianchandotcom** [comment]
@ealonso see my minor changes in upstream. Thx.

**Pull request closed without merging**
