### PR TITLE
LPS-85783 SF

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/af0540e425...53655f74ce

**Comment by brianchandotcom** [comment]
Please send a backport to support for 7.1.x (like our normal support workflow). I'm no longer auto backporting pulls like this.

@jhendley @liferay @zsoltbalogh FYI.

Merged into master only.

**Comment by jpince** [comment]
@pavel-savinov @ealonso pretty sure this caused a startup error, Brian is going to revert for now. Can you please look into this?
```
     [exec] 17:15:29,656 ERROR [http-nio-8080-exec-4][PortletServlet:112] javax.portlet.PortletException: java.lang.StackOverflowError
     [exec] javax.portlet.PortletException: java.lang.StackOverflowError
...
com.liferay.asset.categories.internal.service.AssetEntryAssetCategoryRelAssetCategoryLocalServiceWrapper._getAssetCategoriesByEntryId(AssetEntryAssetCategoryRelAssetCategoryLocalServiceWrapper.java:252)
     [exec] 	at com.liferay.asset.categories.internal.service.AssetEntryAssetCategoryRelAssetCategoryLocalServiceWrapper.getAssetEntryAssetCategories(AssetEntryAssetCategoryRelAssetCategoryLocalServiceWrapper.java:146)
```
See [this gist](https://gist.github.com/jpince/2c2d029b41a0911e427bff5869f81107#file-log-L4609) for the full log.

**Comment by pavel-savinov** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
