### PR TITLE
LPS-109772 Refactor. Rename invalidLayoutPageTemplateImporterResultEntries to notImportedLayoutPageTemplateImporterResultEntries

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
//cc @ealonso

**Comment by ruben-pulido** [comment]
//cc @jkappler

**Comment by jkappler** [comment]
ci:close

**Comment by jkappler** [comment]
was resent in another PR

**Pull request closed without merging**
