### PR TITLE
Lps 93514

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/aed94b1d14...f4d6b04ef9

**Comment by brianchandotcom** [comment]
@dantewang can you send me a backport to 7.2.x with changes from @shuyangzhou ? Thx.

**Comment by brianchandotcom** [comment]
@dantewang send it to me directly. It doesn't cherry pick easily Thx.

**Comment by dantewang** [comment]
@brianchandotcom Got it. @ChiZeLin is on it.

**Pull request closed without merging**
