### PR TITLE
LPS-75606 This is not necessary because it's never executed

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @adolfopa

**Comment by austinchiang** [comment]
ci:reopen

**Comment by austinchiang** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9dde06c650...3bd02276e4

**Pull request closed without merging**
