### PR TITLE
LRQA-33833 Fix PatchingTool#RevertFixPack for FP/HF Testing | master

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRQA-33833

@yunlinsun @brianwulbern @yichenroy

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@michaelhashimoto merged.. not stopping test so you get results. Fairly sure this will work.

**Comment by brianwulbern** [comment]
@michaelhashimoto all the functional tests are all running into the issue you're investigating in [LRQA-36681](https://issues.liferay.com/browse/LRQA-36681)

**Comment by brianwulbern** [comment]
fix for the issue sent on: https://github.com/brianchandotcom/liferay-portal/pull/53809

**Pull request closed without merging**
