### PR TITLE
OAUTH2-263 Make sure scope finder is fully registered before invoking PortalLifecycle

### PR DESCRIPTION
**Pull request by stian-sigvartsen**

### CODE REVIEW

**Comment by csierra** [comment]
ci:retest

**Comment by csierra** [comment]
ci:reopen

**Comment by csierra** [comment]
ci:stop

**Comment by csierra** [comment]
ci:test:sf

**Comment by csierra** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
