### PR TITLE
COMMERCE-6494 Data Exchange Manager (aka Import/Export) - service.xml with entity names

### PR DESCRIPTION
**Pull request by igorbeslic**
Hi @brianchandotcom in this ticket usage for all entities is described: https://issues.liferay.com/browse/COMMERCE-6494

Please, be aware that gradle buildService is not run and stable test at CI would fail (it complains on buildWSDL) if you do not run it.

Thank you very much.

### CODE REVIEW

**Comment by igorbeslic** [comment]
ci:open

**Comment by igorbeslic** [comment]
ci:help

**Comment by igorbeslic** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
BatchPlannerLog
BatchPlannerMapping
BatchPlannerPolicy

modules/batch-engine
modules/batch-planner

**Pull request closed without merging**
