### PR TITLE
LPS-64798 Fix gradle dependency

### PR DESCRIPTION
**Pull request by marcellustavares**
@vicnate5, could you please enable the test after this fix gets merged?

cc @pedroqueiroz94

Thanks

### CODE REVIEW

**Comment by vicnate5** [comment]
@marcellustavares Sounds good. Need to check the tests for stability after this goes in, then I will add 2 more tests to the PR tester under https://issues.liferay.com/browse/LRQA-24953

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/593ab60401...d4b695bba1

**Comment by brianchandotcom** [comment]
@inacionery I reverted d117de52f71688f93a68d82c7ce4f1e9f66a5810

I don't see why we need it? It compiles fine without it?

**Comment by inacionery** [comment]
@brianchandotcom ,

I did that because here https://github.com/liferay/liferay-portal/blob/master/modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-test/src/test/java/com/liferay/dynamic/data/mapping/render/DDMFormFieldValueRendererTest.java#L219, here https://github.com/liferay/liferay-portal/blob/master/modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-test/src/test/java/com/liferay/dynamic/data/mapping/render/DDMFormFieldValueRendererTest.java#L231, here https://github.com/liferay/liferay-portal/blob/master/modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-test/src/test/java/com/liferay/dynamic/data/mapping/storage/GeolocationFieldRendererTest.java#L57, here https://github.com/liferay/liferay-portal/blob/master/modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-test/src/test/java/com/liferay/dynamic/data/mapping/storage/GeolocationFieldRendererTest.java#L73 and here https://github.com/liferay/liferay-portal/blob/master/modules/apps/web-experience/application-list/application-list-test/src/testIntegration/java/com/liferay/application/list/deploy/hot/test/LegacyPortletPanelAppHotDeployListenerTest.java#L152 are using methods introduced in com.liferay.portal.kernel version: 2.2.0

**Pull request closed without merging**
