### PR TITLE
LPS-88763 Retrieve members from AC segments

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
Reviewed ;)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f5ea892548...90ffa3ec6c

**Comment by brianchandotcom** [comment]
@epgarcia can you send a follow up pull and fix

```
		String asahFaroBackendDataSourceId = System.getProperty(
			"asah.faro.backend.dataSourceId");
```

We should use PropsUtil? Or PortletPropsUtil? If it was in portal.properties, then in Docker, we automatically generate  the equivalent env var. Search for the word "ENV" in portal.properties.

I'm not sure if we do that for PortletPropsUtil already, but system props are not the way to go.

Please send a follow up pull. Merged. Thx.

**Comment by brianchandotcom** [comment]
@preston-crary can you also look at modules/apps/segments/segments-service/src/main/java/com/liferay/segments/internal/asah/client/AsahFaroBackendClientImpl.java

Not sure if 

```
@Component(factory = "AsahFaroBackendClient", service = {})
public class AsahFaroBackendClientImpl implements AsahFaroBackendClient {
```

is acceptable. Thx.

**Comment by epgarcia** [comment]
@Preston-Crary @brianchandotcom This is based on https://github.com/liferay/liferay-portal/blob/master/modules/apps/petra/petra-json-web-service-client/src/main/java/com/liferay/petra/json/web/service/client/internal/JSONWebServiceClientImpl.java

**Comment by Preston-Crary** [comment]
Please see https://github.com/epgarcia/liferay-portal/pull/649

**Pull request closed without merging**
