### PR TITLE
LPS-86413

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@brianchandotcom, Please let the tests finish first!!

This is work in progress:
- Need to update *.ftl as well
- Still a few cases that SF does not fix yet
- Can apply to other cases as well (Comparator, for example)

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
Are these failures cause by this pull?

**Comment by jpince** [comment]
@hhuijser looks fine from a quick glace, we'll fix them afterwards if there are new failures

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
