### PR TITLE
LPS-76272 Fix modules' Gradle files

### PR DESCRIPTION
**Pull request by Ithildir**
Hi,
Please let this pull finish.

Thank you!

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:test

**Comment by Ithildir** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/626ed8eb74...f222b94276

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
