### PR TITLE
Master core 1147

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@tinatian sent to you at

Because this modifies 2 generated files

```
	modified:   src/com/liferay/portal/service/persistence/impl/VirtualHostPersistenceImpl.java
	modified:   ../portal-kernel/src/com/liferay/portal/kernel/model/VirtualHostModel.java

```

@shuyangzhou @vicnate5 fyi

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121339

**Comment by brianchandotcom** [comment]
@tinatian those 2 files are auto generated by ServiceBuilder. They have the @generated tag on the file.

So when I run Service Builder and run "ant build-service-portal", they undo your changes.

**Comment by tinatian** [comment]
@brianchandotcom I changed the service builder code at https://github.com/brianchandotcom/liferay-portal/pull/121144/commits/3128928d85568fb05c898ee555f022290d0ddf95, you need to rebuild your service builder locally to see the changes.

**Comment by tinatian** [comment]
ci:reopen

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
