### PR TITLE
LPS-67881 Prepare Fjord Theme for Marketplace

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c0931bc451...288c7123d8

**Comment by brianchandotcom** [comment]
@jbalsas I backported this to 7.0.x and ee-7.0.x.

**Comment by jbalsas** [comment]
Great, thanks a lot! 

@zsoltbalogh could you please verify that that this indeed fixes the fix pack issues?

**Pull request closed without merging**
