### PR TITLE
Lps 100436 2

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:close

**Comment by vicnate5** [comment]
@shuyangzhou @Preston-Crary Upgrade failures are real
https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/337523//consoleText

Steps to Reproduce:
1. Import database from https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/7.0.10.6/data-archive/data-archive-portal-mysql.zip
2. Execute Upgrade client

**Comment by Preston-Crary** [comment]
@vicnate5 Thanks!

Fixed by https://github.com/brianchandotcom/liferay-portal/pull/78815

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.

**Comment by brianchandotcom** [comment]
@Preston-Crary @shuyangzhou sorry it took so long! merged and in my origin.

Only real change was in PortalUpgradeProcessRegistryImpl.java at 79d39c7a98d486007fbac476ba4ce2723de7f9ba due to a rebase error, so I moved around the versions.

Otherwise, mainly just SF from me.

**Pull request closed without merging**
