### PR TITLE
LPS-126331, LPS-126334, LPS-126338, LPS-126355 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-126331
https://issues.liferay.com/browse/LPS-126334
https://issues.liferay.com/browse/LPS-126338
https://issues.liferay.com/browse/LPS-126355

This is only for master.

@david-gutierrez-mesa
@alexcandidos

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure cases are unrelated to changes in PR.
See https://github.com/liferay-echo/liferay-portal/pull/3639
✔️ ci:test:stable - 9 out of 9 jobs passed
❌ ci:test:relevant - 23 out of 26 jobs passed in 3 hours 12 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f6edba419b...75cbaae33e

**Comment by brianchandotcom** [comment]
@ViniLopes20 please review changes.

**Pull request closed without merging**
