### PR TITLE
LPS-54963 ruby sass compiler

### PR DESCRIPTION
**Pull request by david-truong**
ci:retest

### CODE REVIEW

**Comment by david-truong** [comment]
Yay fixed it!

On Thu, Apr 16, 2015 at 2:08 PM, Liferay Continuous Integration <
notifications@github.com> wrote:

> All tests PASSED!
>
> Build Time: 44 minutes 9 seconds
> See the following links for more information.
>
>    -
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest(master)/590/>
>    https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest(master)/590/
>    -
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-githubpost-start(master)/590/>
>    https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-githubpost-start(master)/590/
>    -
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-source(master)/589/>
>    https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-source(master)/589/
>    -
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-backend(master)/514/>
>    https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-backend(master)/514/
>    -
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-plugins(master)/514/>
>    https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-plugins(master)/514/
>    -
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-githubpost-stop(master)/589/>
>    https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-githubpost-stop(master)/589/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/25757#issuecomment-93817523>
> .
>



-- 
David Truong
Product Manager
david.truong@liferay.com
Liferay, Inc

**Comment by brianchandotcom** [comment]
Yey! What was wrong?

**Comment by david-truong** [comment]
JRuby's scripting container does weird things to the classloader it seems?
I made the class closable and close it after it's done...

On Thu, Apr 16, 2015 at 2:43 PM, Brian Chan <notifications@github.com>
wrote:

> Yey! What was wrong?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/25757#issuecomment-93823894>
> .
>



-- 
David Truong
Product Manager
david.truong@liferay.com
Liferay, Inc

**Comment by brianchandotcom** [comment]
I just renamed com.liferay.sass.compiler  to com.liferay.sass.compiler.jni so that this ruby is distinguished from it. Using this same pull to just retest upstream.

ci:retest

**Comment by brianchandotcom** [comment]
Ok, it's published! See https://repository.liferay.com/nexus/content/repositories/liferay-snapshots-ce/com/liferay/com.liferay.sass.compiler.ruby/1.0.0-SNAPSHOT/com.liferay.sass.compiler.ruby-1.0.0-SNAPSHOT.pom

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4f32505267...cbf40f57fb

**Pull request closed without merging**
