### PR TITLE
master-vw-328

### PR DESCRIPTION
**Pull request by vicnate5**
@brunobasto @thiago-rocha

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@shuyangzhou EditorConfigTransformerTest* is still happening?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e55bb28814...0c073efa70

**Comment by shuyangzhou** [comment]
Ugh, sorry, @brianchandotcom I only fixed EditorConfigContributorTest, there is another one EditorConfigTransformerTest, on it now.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/39478

**Pull request closed without merging**
