### PR TITLE
LPS-101483 Simplify conditionals

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:test:sharepoint

**Comment by austinchiang** [comment]
ci:test:bundle

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/05fb679e87...c3ae843e33

**Comment by brianchandotcom** [comment]
@adolfopa we should probably use  a new ticket next time. This was already partially ported to 7.2.x. Please send this to support.

**Comment by adolfopa** [comment]
I'll do. Thanks!

**Pull request closed without merging**
