### PR TITLE
LPS-75598 Create a framework that allows applications to provide their data erasure implementations

### PR DESCRIPTION
**Pull request by pei-jung**
This is an update for [LPS-75598](https://issues.liferay.com/browse/LPS-75598).
This is an update for [LPS-76024](https://issues.liferay.com/browse/LPS-76024).
This is an update for [LPS-76025](https://issues.liferay.com/browse/LPS-76025).

Hey Brian, these are the initial commits for the GDPR changes. The API is subject to change, but we need this as a base to work off of.

/cc @JorgeFerrer, @drewbrokke , @willnewbury, @noahsherrillwork

### CODE REVIEW

**Comment by pei-jung** [comment]
@JorgeFerrer 

From @drewbrokke 

> This pull does not include the frontend changes. @willnewbury and @noahsherrillwork are also looking possible solutions for the scalability issues you noted on my pull.

**Comment by pei-jung** [comment]
ci:test

**Comment by drewbrokke** [comment]
ci:close
Closing to fix failures

**Comment by pei-jung** [comment]
Resent as https://github.com/brianchandotcom/liferay-portal/pull/53802.

**Pull request closed without merging**
