### PR TITLE
LPS- 69797 Updates in Demo Data Creator for Document Library

### PR DESCRIPTION
**Pull request by alejandrohdezma**

### CODE REVIEW

**Comment by ahdezma** [comment]
ci:reopen

**Comment by ahdezma** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@ahdezma @sergiogonzalez please see my changes in upstream. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f563a2a0f8...162a8ff63c

**Pull request closed without merging**
