### PR TITLE
LPS-89456 Fix broken tests

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by jpince** [comment]
@ealonso thanks!

@vicnate5 can you please work with @tinatian to resolve the upgrade test failures as well? From previous pull https://github.com/brianchandotcom/liferay-portal/pull/67864#issuecomment-462651825

**Comment by anthony-chu** [comment]
ci:test:bundle

**Comment by brianchandotcom** [comment]
@tinatian fyi.

**Comment by tinatian** [comment]
Thanks @ealonso and @brianchandotcom !

**Pull request closed without merging**
