### PR TITLE
LPS-79062 Updates year and removes unnecessary space

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jpince** [comment]
@jbalsas thanks!

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@jbalsas this shouldn't be hard coded

The old FTL themes used to grab the year based on the date, so it's always fresh and latest.

**Comment by brianchandotcom** [comment]
Or at least grab it from ReleaseInfo.getBuildDate and get that year...

**Pull request closed without merging**
