### PR TITLE
LPS-58680 Annotate WikiGroupServiceConfiguration

### PR DESCRIPTION
**Pull request by izaera**
/CC: @JorgeFerrer @rotty3000

Hi Brian:

This is a PR to define an ExtendedMetaTypeService that wraps OSGi's standard MetaTypeService. Its future use is to rely on it to be able to tweak our Configuration Admin to fit our needs (for example: intelligent fields that are automagically populated, typed fields like localized values or dates, and so on).

This PR defines and implements the service based on Equinox and on runtime annotations. In the end we will use Equinox, but with the annotations implementation we are able to continue development based on this, until we finally integrate BND 3 into the build (which is not so easy right now).

The last commit is an example of how it would be used to group configurations by category. It may be not pushed if you don't want to, but it won't do any harm if it is.

Please tell me what do you think or if you find something you don't like.

Cheers,
Ivan

### CODE REVIEW

**Comment by izaera** [comment]
ci:retest

**Comment by izaera** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@izaera can you resend on top of : https://github.com/izaera/liferay-portal/pull/171

1.) Do you have the XSD for http://www.liferay.com/xsd/meta-type-hints_7_0_0 ?

2.) Did you comment out ExtendedMetaTypeService on purpose in EquinoxExtendedMetaTypeService?

3.) Should constants in ConfigurationAdmin be moved to a constants class inside a *.constants.* package?

I would also prefix the constant keys because it's not obvious how they are grouped together.

i.e. TYPE_X and TYPE_Y, STATUS_A and STATUS_B

Thx!

**Comment by izaera** [comment]
@brianchandotcom:

> 1.) Do you have the XSD for http://www.liferay.com/xsd/meta-type-hints_7_0_0 ?

No. Is it really needed? The XML will always be generated by BND so I'm not sure if anyone will need to validate it in the future. But I will take a look at it.

> 2.) Did you comment out ExtendedMetaTypeService on purpose in EquinoxExtendedMetaTypeService?

Yes. It is commented out so that we fallback on AnnotationsExtendedMetaTypeService until we fix the BND 3 issues. After BND 3 is integrated in the build we can get rid of AnnotationsExtendedMetaTypeService and uncomment EquinoxExtendedMetaTypeService.

> 3.) Should constants in ConfigurationAdmin be moved to a constants class inside a .constants. package?

Not sure. I really prefer to have them nested in ConfigurationAdmin as they won't be shared by any other class and they logically belong to it. I think that what leads you to confusion is the fact that I'm using `http://www.liferay.com/xsd/meta-type-hints_7_0_0` as namespace, when it should be something like `http://www.liferay.com/xsd/configuration-admin/meta-type-hints_7_0_0` or similar (one XSD per annotation class, not one for the whole Liferay). Is that the real problem?

>I would also prefix the constant keys because it's not obvious how they are grouped together.
>i.e. TYPE_X and TYPE_Y, STATUS_A and STATUS_B

OK.

**Pull request closed without merging**
