### PR TITLE
LPS-99774 Update liferay-npm-scripts to v7.1.0

### PR DESCRIPTION
**Pull request by wincent**
This is "defense in depth", [making sure](https://github.com/liferay/liferay-npm-tools/pull/198) that liferay-npm-scripts always uses the "test" environment when running Jest, even if passed an incorrect NODE_ENV.

### CODE REVIEW

**Comment by wincent** [comment]
Corresponding master-private PR is: https://github.com/brianchandotcom/liferay-portal-ee/pull/26015

@petershin, @jbalsas: We may want to consider a couple of follow-up items here:

1. #76997 was good mitigation for the test failures that we were seeing, but technically we don't *need* it any more (after this change goes in) and I'm wondering if we should revert that PR for a couple of reasons:
    - It might be surprising/confusing for people to see that any `nodejs.node.env=` setting in `build.properties` (or even passed in via `ant -Dnodejs.node.env=...` or `gradlew -Pnodejs.node.env=...`) gets silently overridden for a specific hardcoded script name ("test")).
    - Because the script name is hardcoded, the behavior won't be applied to closely-related script names like "test:watch" (unlike the fix in this PR would work for any script which ends up calling `liferay-npm-scripts test --watch` etc).
2. We might way to consider defaulting `nodejs.node.env` and `nodejs.ci.node.env` to "empty", to keep the behavior a little closer to how it used to be before those settings were added; specifically:
    - In the absence of an explicit `NODE_ENV`, we build "production" artifacts.
    - You could, if you wanted to, perform a temporary override by launching any command (`yarn`, `ant`, `gradlew` etc) with a `env NODE_ENV=...` prefix; this was pretty nice because it didn't require you to have to remeber tool-specific options (like `-P` or `-D`), nor worry about your "temporary" override getting cached somewhere like `.gradle/build.properties` and then applying to subsequent runs.

    (I'm not suggesting removing the properties — because they are still very useful for setting a persistent "development" setting — just defaulting them to "empty".)

What do you think?

**Comment by petershin** [comment]
@wincent, @jbalsas - That sound good to me.  I'll send a pull with those changes later today after this pull is merged

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/316560d989...ef59383f18

**Comment by brianchandotcom** [comment]
@jbalsas @wincent  I'm only autobackporting to 7.2.x

I need you guys to do it for 7.1.x.

**Comment by brianchandotcom** [comment]
@wincent @jbalsas you can send me the 7.1.x pulls directly.

**Comment by wincent** [comment]
7.1.x backport sent here: https://github.com/brianchandotcom/liferay-portal-ee/pull/26040

**Pull request closed without merging**
