### PR TITLE
LPS-88240 UpgradeOrganization fails from 6.1/6.2 to master/7.2 on some databases

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @ChrisKian

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:upgrade

**Comment by brianchandotcom** [comment]
@inacionery is this from you? See 

```
junit.framework.AssertionFailedError: 
Unable to process message {destinationName=destination.workflow_reports, response=null, responseDestinationName=null, responseId=null, payload={date=2018-12-13T03:03:43.515Z, eventId=PROCESS_CREATE, companyId=20099, processId=35203, active=false, description=A single approver can approve a workflow content., applicationId=workflow:1.0.0, title=<?xml version='1.0' encoding='UTF-8'?><root available-locales="en_US" default-locale="en_US"><title language-id="en_US">Single Approver</title></root>, userId=20103, version=1}, values={defaultLocale=en_US, companyId=20099, groupId=0}}
com.liferay.portal.kernel.messaging.MessageListenerException: [workflow-events] IndexNotFoundException[no such index]
	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:32)
	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:74)
	at com.liferay.portal.kernel.messaging.ParallelDestination$1.run(ParallelDestination.java:52)
	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask._runTask(ThreadPoolExecutor.java:752)
	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask.run(ThreadPoolExecutor.java:664)
	at java.lang.Thread.run(Thread.java:745)
Caused by: [workflow-events] IndexNotFoundException[no such index]
	at org.elasticsearch.cluster.metadata.IndexNameExpressionResolver.concreteIndices(IndexNameExpressionResolver.java:182)
	at org.elasticsearc...
```

**Comment by brianchandotcom** [comment]
@ChrisKian please backport. Thx.

**Comment by inacionery** [comment]
Hey @brianchandotcom,

It was me, but the fix is already merged.

https://github.com/brianchandotcom/liferay-portal-ee/pull/22691

**Pull request closed without merging**
