### PR TITLE
[DO NOT MERGE THIS] Opening just for feedback

### PR DESCRIPTION
**Pull request by victorg1991**
Hey Brian,

We had to do a workaround for a bug in the search framework that is now resolved. This code is extracted in SearchUtil.

Now, I've to change this code to use the search framework in the "normal" way. Instead of returning the Hits, I've created a method that returns the searchContext, because right now, we have to make two calls using this searchContext `indexer.search(searchContext)` and ìndexer.searchCount(searchContext)`. 

I've to apply the change across all APIs so I wanted to obtain your feedback about this approach first, what do you think?

Thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@victorg1991 If I like this, can I merge it?

**Comment by brianchandotcom** [comment]
Oh I see, we have to apply this everywhere all at once...

**Comment by victorg1991** [comment]
ci:reopen
@brianchandotcom my idea was to get some feedback about it, is that ok? or do you prefer a working example that you can merge if you like? 

Thanks

**Comment by brianchandotcom** [comment]
@victorg1991 This is good..

Call it createSearchContext instead of buildSearchContext.

and sort

```
		searchContext.setGroupIds(new long[] {contentSpaceId});
		searchContext.setAttribute("searchPermissionContext", StringPool.BLANK);
		searchContext.setCompanyId(contextCompany.getCompanyId());
```

I go by searchContext.*

Can you also make Page.of smarter

Math.toIntExact(indexer.searchCount(searchContext))

So we don't have to type Math.toIntExact every time?

May be add another method that takes a long and does the conversion for us.

Thx @victorg1991

**Comment by victorg1991** [comment]
Thanks!

**Pull request closed without merging**
