### PR TITLE
LPS-58854 These parameters are not used in journal in any place and they are no longer necessary since now they are automatically sent by the searchcontainer

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by juliocamarero** [comment]
@sergiogonzalez can you please send this pull to @evannagayama?  thank you!

**Comment by juliocamarero** [comment]
@evannagayama, this shouldn't change any feature. It should just fix the move problem. I wonder if there are regressions created by it or if some markup has changed that breaks the tests....

**Comment by brianwulbern** [comment]
@sergiogonzalez @juliocamarero @evannagayama

Site and Page Templates are both broken in this pull.  Looking at the Poshi Report for [AddSitePageTemplate](https://test-1-6.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/1614/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=CPPagetemplates%23AddSitePageTemplate,label_exp=!master/functional-tomcat-mysql/1/screenshots/before1.jpg), or [AddSiteTemplate](https://test-1-6.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/1614/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=CPSitetemplates%23AddSiteTemplate,label_exp=!master/functional-tomcat-mysql/4/screenshots/before1.jpg), you'll see the portlet is missing.

**Comment by jbalsas** [comment]
Hey @brianchandotcom, @brianwulbern, @juliocamarero,

Other changes went in using an API that we were changing here, so we hadn't had the chance to update those. Some jsps were failing to compile, unfortunately we no longer can detect that in compile time, I think :cry: 

I've updated and reset to https://github.com/brianchandotcom/liferay-portal/pull/32406

**Comment by brianwulbern** [comment]
@jbalsas Thanks, man!

**Comment by pyoo47** [comment]
ci:retest (the logs got erased from the jenkins servers so I'm try to regenerate them)

**Pull request closed without merging**
