### PR TITLE
LPS-55233 Regen WSDD

### PR DESCRIPTION
**Pull request by epgarcia**
@juliocamarero
@marcellustavares

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:retest

**Comment by epgarcia** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@epgarcia please see my renames to match existing usage of:

List<DDMStructure> ddmStructures = JournalFolderServiceUtil.getDDMStruc

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b11869401a...1287dc4c9e

**Pull request closed without merging**
