### PR TITLE
Integration test for the AuthToken registry

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by migue** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:retest

**Comment by migue** [comment]
Not sure what's happening, but some random tests are failing ...

**Comment by brianchandotcom** [comment]
ci:retest

So weird... trying again (Shuyang is going to investigate a lot of these issues).

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@mdelapenya this pull consistently breaks.. I've tried retesting multiple times. It doesn't happen with any other pull, so I don't think it's safe to merge in. Please resend. Thx.

**Comment by mdelapenya** [comment]
Not sure what is happening here, it fails with a different OSGi module that is not present on classpath each time:
* com/liferay/site/map/web/configuration/SiteMapWebConfigurationValues
* org/owasp/html/HtmlPolicyBuilder
* com/liferay/language/web/configuration/LanguageWebConfigurationValues

We followed the same pattern as https://github.com/brianchandotcom/liferay-portal/pull/24221, that was added 13 days ago, but we also noticed that the same problem happened with this pull: https://github.com/brianchandotcom/liferay-portal/pull/24496 (2 days ago)

On the other hand, we cannot make ResourceLocalServiceTest to fail locally, even executing all integration tests in a row, so we would love to hear a little more feedback about this problem, although we're still investigating what could be the root cause, maybe infrastructure problems.

Thanks!

**Comment by mdelapenya** [comment]
Extrange...

The tests failed (https://github.com/brianchandotcom/liferay-portal/pull/24573#issuecomment-77513938) and passed (https://github.com/brianchandotcom/liferay-portal/pull/24573#issuecomment-77552797) without doing anything!

**Pull request closed without merging**
