### PR TITLE
LPS-66646 - Add missing var

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:close

**Comment by anthony-chu** [comment]
@brunobasto @jonmak08 @zxdgoal I'm closing this pull request because it causes intentional Poshi test failures. I will resend this pull request with the necessary Poshi changes on top.

**Comment by jonmak08** [comment]
Thanks @anthony-chu!

**Comment by jbalsas** [comment]
Hey @anthony-chu, any update on this?

**Comment by kenjiheigel** [comment]
hey @jbalsas, I'll actually be working on this since it's frontend related. I talked to @jonmak08, and let him know that I'll get to this within the next week or so. He said priority isn't high, but the longer it takes there's greater risk of rebase errors. I can prioritize this higher if you need it though. 

https://issues.liferay.com/browse/LRQA-28703

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
Resent:
https://github.com/brianchandotcom/liferay-portal/pull/44846
https://github.com/liferay/com-liferay-journal/pull/48

**Pull request closed without merging**
