### PR TITLE
LPS-74034

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by shinnlok** [comment]
@hhuijser 

Location check was added by @ithildir here:

https://github.com/brianchandotcom/liferay-portal/pull/50738

**Comment by hhuijser** [comment]
@brianchandotcom can you merge all commit except for https://github.com/brianchandotcom/liferay-portal/pull/50757/commits/fa686d9a9b5e8ae7de1774c3c085d25b7cfe521d

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
