### PR TITLE
LPS-60759

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@hhuijser how come? Can you explain? Thx.

**Comment by hhuijser** [comment]
@brianchandotcom 

From Jon Mak:

In looking at the code, I think this is something we should fix with the source formatter since we changed our requirement for if statements.

It used to be:

if (a && (a == b)) {...}

but not we changed it to allow as well

if (a && a == b) {...}

It is no longer a necessity to have the statement conditions wrapped in parenthesis unless you are explicit about your order of evaluation.  That said, Nate mentioned a good point about the ant format-source in that we are not sure if it will differentiate JS if statements in JSP vs JSP if statements.  I think BChan wants the parenthesis wrapping the statement conditions in JSP code.

**Comment by hhuijser** [comment]
Forwarded you the email as well

**Comment by brianchandotcom** [comment]
Got it.. so leave JS to the JS formatter. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4e877c28ef...e965157a5b

**Pull request closed without merging**
