### PR TITLE
LPS-104525 disable GraphQL APIs

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@nhpatt master only? If it should go back, please send backports.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c5db570744...ddeeddc658

**Comment by brianchandotcom** [comment]
@nhpatt I kind of think this is a bad idea.. I'd rather force ppl to fix validation errors than queue them up and never be able to fix them because ti's too many. Reverted...

**Comment by nhpatt** [comment]
Ok, I'll look for another way.

**Pull request closed without merging**
