### PR TITLE
LPS-96616

### PR DESCRIPTION
**Pull request by petershin**
@gamerson

### CODE REVIEW

**Comment by petershin** [comment]
@lawrence-lee can you take a look at the failures?

**Comment by lawrence-lee** [comment]
@petershin, I'll take a look 
can you close this for now? dont want it getting merged.

**Comment by petershin** [comment]
Sure.  Its odd that it failed b/c Greg mentioned it passed here: https://github.com/gamerson/liferay-portal/pull/281#issuecomment-501070221

**Comment by lawrence-lee** [comment]
Ah! i think i know the problem. i'll send a fix

**Pull request closed without merging**
