### PR TITLE
LRQA-18698

### PR DESCRIPTION
**Pull request by pyoo47**
Removed ability to download test data for an entire pull request. Instead, you must specify the build url for a specific run of test on a slave. Also did some more refactoring based on input from Brian.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest (I'm just borrowing this pull to test the latest master)

**Comment by pyoo47** [comment]
I've added a commit to move the dependency root folder. I wanted to isolate the dependency root folder for each test class in the package.

**Comment by pyoo47** [comment]
added junit tests for JenkinsResultParserUtil

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/42a8c4358a...5345229613

**Pull request closed without merging**
