### PR TITLE
LPS-112475 Updates clay:alert and clay:stripe tag implementation and usages

### PR DESCRIPTION
**Pull request by jbalsas**
Manual forward from https://github.com/wincent/liferay-portal/pull/349 after
- ci:test:relevant - 148 out of 157 jobs passed in 2 hours 22 minutes
- ci:test:relevant - 152 out of 155 jobs passed in 1 hour 28 minutes
- ci:test:relevant - 159 out of 163 jobs passed in 1 hour 56 minutes
- ci:test:relevant - 160 out of 163 jobs passed in 1 hour 48 minutes

All with no unique or unrelated failures.

--- 

This PR updates the implementation of both `AlertTag` and `StripeTag` inside `frontend-taglib-clay` so they're rendered directly from Java (no Soy dependency).

It includes:

### `clay:alert`
- Tag migration
- Legacy tag attribute deprecation 
- Legacy tag implementation deprecation

### `clay:stripe`
- Tag migration
- Legacy tag attribute deprecation 
- Legacy tag implementation deprecation

Visually, output is the same, but added a couple of modifications over the previous implementation:
- The `title` value is inferred from `displayType` if no specific `title` is passed (this removes a lot of boilerplate)
- The `message` and `title` attributes are translated inside the tag (no longer needed to pass them already translated if one doesn't want to). This is more in line with the rest of tags.
- Inlined `onclick` method in the close button in the case of `dismissible` alerts to avoid having to rehydrate the markup with our React component (trying to push this to the last moment...)

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/68ef655961...9113701494

**Comment by brianchandotcom** [comment]
@vicnate5 @reizero00 fyi so we can better help @jbalsas and @wincent

**Comment by brianchandotcom** [comment]
@kenjiheigel fyi need help with flakiness

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

not flaky, failing tests exist in upstream with same error at f21ec71:
- https://testray.liferay.com/home/-/testray/cases/865155623
- https://testray.liferay.com/home/-/testray/cases/865155635
- https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/400594/

**Comment by reizero00** [comment]
Thanks for jumping on this @john-co

**Pull request closed without merging**
