### PR TITLE
LPS-75522 Modify only Liferay tables and moving verify logic into an upgrade for better supportability in the future

### PR DESCRIPTION
**Pull request by achaparro**
@amadeafejes

### CODE REVIEW

**Comment by achaparro** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0807503237...b5d190457b

**Comment by brianchandotcom** [comment]
Wow @amadeafejes very good job! This is a very good pull.. and usually, when new engineers send me pulls, it's not like this. So good  job.

**Comment by brianchandotcom** [comment]
@amadeafejes just one minor change in b5d190457bd2478a6dee3c611f899b6ba11c1fdd :)

**Comment by brianchandotcom** [comment]
@achaparro @amadeafejes oh, we're also missing some tables from plugins (chat_entry, chat_status)...

**Comment by brianchandotcom** [comment]
@achaparro @amadeafejes you should add the plugins to the list, and.. this may be better as a property in case we need to change it.

So add a property in portal.properties, add a line break via \ for each table name so it's obvious what's happening.

Thx

**Comment by amadeafejes** [comment]
Hi Brian,

Thank you for your praising words. The property you asked is in progress:
https://github.com/achaparro/liferay-portal/pull/93

**Comment by shuyangzhou** [comment]
@brianchandotcom @jpince this is the cause of all the SQLDateTest failures.

@achaparro @amadeafejes you can not just remove the verify process for mysql date without update the sql generation logic. We generate it by the pre-5.6.4 formatting. For all new mysql/mariadb instance, we are relying on this verify process to fix the datetime datetype to behave properly.

See fix at https://github.com/brianchandotcom/liferay-portal/pull/53121

**Comment by achaparro** [comment]
Hi @shuyangzhou, @jpince,

Could you specify the exact version of MariaDb and Mysql databases we use ti execute the tests where the SQLDateTest were failing?

In DXP/Master we only support Mysql 5.6 and above (the first GA is 5.6.10, see https://dev.mysql.com/doc/relnotes/mysql/5.6/en/news-5-6-10.html) and there were no reason to fail in those versions (the problem just can happen in 5.6.3 and below) because of this:
https://github.com/liferay/liferay-portal-ee/commit/ddee0f3d7604963a47997aa1f53f486dfab2affc#diff-383dec7bab764a8820ea59830fe64d0dL143

It's important to clarify this as soon as possible to be able to know if we can backport this to 7.0.x:
https://github.com/liferay/liferay-portal-ee/pull/3355

Thanks.

@amadeafejes, @CsabaTurcsan, @lipusz

**Comment by jpince** [comment]
@achaparro CI runs the following patch versions:

MariaDb 10.0.20
MySQL 5.6.38 (some slaves are still being transitioned from older versions, the oldest version is 5.6.34)

**Comment by achaparro** [comment]
Thanks @jpince, honestly I don't know why the error happens for MySQL since the it can only occur for MySQL 5.6.3 and 5.6.34 is newer.

We will try to investigate it.

**Comment by shuyangzhou** [comment]
@achaparro https://github.com/brianchandotcom/liferay-portal/pull/53121 is the fix of this. You guys won't need to do anything more.
If you want to know why CI (customer potentially too, only when they starting with brand new DB like CI does all the time)was failing on this,  I can explain this to you in today's meeting.

**Pull request closed without merging**
