### PR TITLE
LPS-92471 Establish as size of the array again

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by jkappler** [comment]
cc:// @brianchiu, @kyle-miho

**Comment by jkappler** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cac265b747...aa616f0890

**Comment by brianchandotcom** [comment]
@jkappler see upstream changes. Thx.

**Pull request closed without merging**
