### PR TITLE
LPS-78511 Auto

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test

**Comment by pavel-savinov** [comment]
cc @ealonso

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/75923b88a5...8b15c4ed0f

**Comment by brianchandotcom** [comment]
@pavel-savinov @jkappler see 8b15c4ed0f93c2820284bf9fd4bb6c992af8addb thx

**Pull request closed without merging**
