### PR TITLE
LPS-56383 Extract Journal API and Services to OSGi modules

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
@brianchandotcom I rebased with the latest changes from master and it seems there are no errors. Maybe something related has been fixed :)

@juliocamarero

**Comment by juliocamarero** [comment]
:tada:

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e36eef43cf...3865ed0e7f

**Comment by brianchandotcom** [comment]
@epgarcia can you fix getInstance() see ab454619a2cb771eed29a9f72587a871b600b8e5

I may have missed a few. Can you check all modules and rename the getInstance() pattern. It should say the class name that it's returning.

Thx.

**Comment by epgarcia** [comment]
Sure I'll review it right now. Thanks!

**Pull request closed without merging**
