### PR TITLE
LPS-56015 Fixed rebase error

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@natecavanaugh see change to util.js ? Thx

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e9b0d0d1c3...b462064b11

**Pull request closed without merging**
