### PR TITLE
Lps 68956

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@tinatian @shuyangzhou I've seen testHikariCP break at least 5 times today, just fyi. thx.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by tinatian** [comment]
@brianchandotcom  with this change : https://github.com/brianchandotcom/liferay-portal/pull/45820 The error should not come up again. I will take a look into this

**Comment by shuyangzhou** [comment]
@brianchandotcom you merged the fix already in https://github.com/brianchandotcom/liferay-portal/pull/45820

**Pull request closed without merging**
