### PR TITLE
LPS-100001 | master

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LPS-100001

Forgot to add the lfrbuild marker file for LTR.

Corresponding 7.2 PR: https://github.com/brianchandotcom/liferay-portal-ee/pull/27321

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:stop

**Comment by xbrianlee** [comment]
cc/ @suilin @brandizzi

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7ad663c806...ea68239987

**Comment by xbrianlee** [comment]
ci:stop

**Pull request closed without merging**
