### PR TITLE
COMMERCE-6011 DISPATCH EXECUTOR SAMPLE - renamed and sent directly to you - thank you!

### PR DESCRIPTION
**Pull request by igorbeslic**

### CODE REVIEW

**Comment by igorbeslic** [comment]
ci:open

**Comment by igorbeslic** [comment]
ci:open

**Comment by igorbeslic** [comment]
ci:help

**Comment by igorbeslic** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ef2eab19db...73cce523ed

**Comment by brianchandotcom** [comment]
@igorbeslic see 73cce523ed63838d31c4ae3e09c677d476021bfd and e130297e8331f05ffe781c648f7ae152512a30b9

**Pull request closed without merging**
