### PR TITLE
LPS-75036 | master

### PR DESCRIPTION
**Pull request by vicnate5**
@leoadb

### CODE REVIEW

**Comment by leoadb** [comment]
ci:reopen

**Comment by leoadb** [comment]
ci:retest

**Comment by vicnate5** [comment]
@brianchandotcom Test failures not related to this pull

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0231cd0e64...e05726ec39

**Comment by brianchandotcom** [comment]
@leoadb can you send a follow up pull to sort?

```
						'liferay-ddl-portlet': {
							path: 'form_portlet.js',
							requires: [
								'liferay-ddm-form-builder',
								'liferay-ddm-form-builder-definition-serializer',
								'liferay-ddm-form-builder-layout-serializer',
								'liferay-ddm-form-builder-rule-builder',
								'liferay-portlet-base',
								'liferay-util-window'
							]
						},
						'liferay-ddl-form-builder-copy-publish-form-url-popover': {
							path: 'form_builder_copy_publish_form_url_popover.js',
							requires: [
								'aui-popover'
							]
						}
```

Thx.

**Comment by leoadb** [comment]
@brianchandotcom Done! Sent to https://github.com/brianchandotcom/liferay-portal/pull/52060

**Brian, my sincere condolences for your loss. I prayed to god to give comfort to you and your family. I'm a father too and can't imagine what you and your family have being through. I wish the best for you and your family.**

**Pull request closed without merging**
