### PR TITLE
LPS-184588 [Marketplace] Add Commerce Order Type through Site Initializer

### PR DESCRIPTION
**Pull request by joanagrego**
Original pull request: [PR](https://github.com/pt-liferay-solutions/liferay-portal/pull/4085)
Hi [@brianchandotcom](https://github.com/brianchandotcom), I'm manually forwarding this because @joseabelenda's PR had conflicts with the master.

### CODE REVIEW

**Comment by joanagrego** [comment]
co:reopen

**Comment by joanagrego** [comment]
ci:reopen

**Comment by nNilton** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9434e1cd02...6862b3167f

**Pull request closed without merging**
