### PR TITLE
LPS-80060 Fix naming

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
Can you resend @pedroqueiroz 

DDLWebConfigurationActivator is in the wrong dir. See other examples. And it should be internal no?

Not sure why we are exporting that class.

**Comment by brianchandotcom** [comment]
@pedroqueiroz I think that whole configuration dir should be internal...

@hhuijser see 

modules/apps/forms-and-workflow/dynamic-data-lists/dynamic-data-lists-web/src/main/java/com/liferay/dynamic/data/lists/web/configuration/

Not sure why that isn't complaining in SF,

**Comment by pedroqueiroz** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/57757. Thanks!

**Pull request closed without merging**
