### PR TITLE
LPS-64001 Unused

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
cc /@jbalsas

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/76ce6e27bf...ce039d34a4

**Comment by brianchandotcom** [comment]
@robertoDiaz see 145371d9050dd9ad93214984677f643b6385bd7d

I think this is what you meant?

**Comment by robertoDiaz** [comment]
Yep, it is. 

Thank you @brianchandotcom

**Pull request closed without merging**
