### PR TITLE
LPS-138755 | LPS-138752 | LPS-138753

### PR DESCRIPTION
**Pull request by guilhermedcamacho**
CI already ran successfully in this [PR](https://github.com/liferay-objects/liferay-portal/pull/92), I just did a tiny change.

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0982ca40c7...a12015e074

**Comment by brianchandotcom** [comment]
@guilhermedcamacho in the future, can you make sure the 3rd commit in here separated the generated REST builder code from the other code?

Otherwise, just a12015e07454455d59be2d784720b7bad4918740

**Comment by guilhermedcamacho** [comment]
> @guilhermedcamacho in the future, can you make sure the 3rd commit in here separated the generated REST builder code from the other code?
> 
> Otherwise, just [a12015e](https://github.com/brianchandotcom/liferay-portal/commit/a12015e07454455d59be2d784720b7bad4918740)

Sure! my bad, sorry!! 
I was confused because we copied and pasted some classes from Commerce with the help of Marco Leo, so it mixed.

**Pull request closed without merging**
