### PR TITLE
LPS-68460 Enforce restriction in the backend

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by BryanEngler** [comment]
@adolfopa just fyi, this solution does not let you "unmark" the thread as a question... after creating the original thread, go to edit, uncheck "mark as a question" and save... the thread will still be a question

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
This is still running. Only three batches remain:
http://test-1-4/job/test-portal-acceptance-pullrequest-batch%28master%29/52227/
http://test-1-12/job/test-portal-acceptance-pullrequest-batch%28master%29/7293/
http://test-1-4/job/test-portal-acceptance-pullrequest-batch%28master%29/52229/

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by adolfopa** [comment]
@BryanEngler It looks like a bug to me (why don't let users unmark the 'question' check when creating the thread to later allow it when editing?) I think we should either enforce it always (i.e. disabling it both when adding and editing) or let users change it no matter if they're adding or editing.

For us it makes sense for threads inside the "question" category to be marked as questions, so we'll enforce it always (even when editing).

Thanks for noticing!

**Pull request closed without merging**
