### PR TITLE
LPS-56199

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-56199](https://issues.liferay.com/browse/LPS-56199).<br><br>@ealonso, @jorgeferrer, @pei-jung

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/500a3cc353...9fee649087

**Comment by brianchandotcom** [comment]
@drewbrokke please see my changes in upstream. Thx.

**Comment by drewbrokke** [comment]
Thanks!

**Pull request closed without merging**
