### PR TITLE
LPS-62926 fix look and feel window

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Hey @evannagayama

we realized the "look and feel" UI was not working at all (it didn't update the styles of the app and it didn't save them properly). Do we have functional any tests for it? If we do, we should probably move at least one to the pull requests tester.

Otherwise, we should add one for this, it is too visible to have it broken.

thanks a lot!

**Comment by evannagayama** [comment]
@juliocamarero @kenjiheigel

The Look and Feel falls under UI. I talked to Kenji and he's going to add a test to the UI acceptance layer. LRQA-22085. Thanks!

**Comment by juliocamarero** [comment]
Ok, that's cool :)

we inherited that component, so technically it belongs to WCM now... but whatever rocks your boat... :D

**Comment by evannagayama** [comment]
hahaha didn't know that... in that case we'll write it :)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4eae66acdd...87cf392765

**Pull request closed without merging**
