### PR TITLE
LPS-74356 DB Upgrade client: Update and improve help messages

### PR DESCRIPTION
**Pull request by achaparro**
cc @csierra

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest (due to a bad slave on test-1-3)

**Comment by alee8888** [comment]
There is only a single functional test failure, WorkflowForms#ViewDateAssetDetails, that is failing upstream and not related to the commits in this pull.

**Comment by nicolelau** [comment]
@brianchandotcom - Can you please review? We would like this commit to be included before you publish for the DB Upgrade Tool tomorrow. Thank you!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/11e71edf61...b77ad44939

**Comment by brianchandotcom** [comment]
@achaparro please review my changes in upstream. Thx.

**Pull request closed without merging**
