### PR TITLE
LPS-65323

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
please do have a close look at the changes in the Auto SF commit...
A lot of attributes get sorted...

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/72fc38fb43...5710ff6f6d

**Comment by brianchandotcom** [comment]
@hhuijser see 9c48ff4ac8656e92010cbacf0664ab84600d4a4f

We had to fix SBbuilder

**Comment by hhuijser** [comment]
my bad... never thought about these...

**Pull request closed without merging**
