### PR TITLE
LPS-57542

### PR DESCRIPTION
**Pull request by mikakoivisto**
LPS-57542 Guest user incorrectly identified as authenticated. CC @ZoltanTakacs

### CODE REVIEW

**Comment by ZoltanTakacs** [comment]
Hi @mikakoivisto,

The latest date for backports was 8/14 for M7.
Please contact Joshua Kuo or Esther Sanz if it's urgent.

Thanks,

**Comment by mikakoivisto** [comment]
As long as it makes it's way to actual release I don't care if a milestone release has a huge security hole.

**Comment by ZoltanTakacs** [comment]
I'll talk to them regarding this fix.

Thanks,

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/96dfdf78c8...2d9fd2383b

**Pull request closed without merging**
