### PR TITLE
LPS-62956 move language keys to the module

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/483bf74765...77f0fae7f2

**Comment by brianchandotcom** [comment]
@jkappler good job not losing translations.

**Pull request closed without merging**
