### PR TITLE
LPS-106529 Fix tests and launch headless tests with changes in segments

### PR DESCRIPTION
**Pull request by dgarciasarai**
See https://github.com/dgarciasarai/liferay-portal/pull/146

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/eeaa3f479b...bfeecaedf0

**Comment by brianchandotcom** [comment]
@dgarciasarai see b808f484cc16e118ddea30e6be5da95e189ddcac and bfeecaedf0e596d049bdb68ba6331d4ab348a7c1

and can you fix:

```
	@Ignore
	@Test(expected = NotFoundException.class)
	public void testGetSegmentUserAccountsPageWithNonexistingSegmentId()
		throws Exception {

		segmentUserResource.getSegmentUserAccountsPage(
			RandomTestUtil.randomLong(), null);
	}
```

**Comment by dgarciasarai** [comment]
Hey @brianchandotcom,
There is an error with the autogenerated client and that test is failing. Because of that, I ignored it.
I created a ticket to resolve it https://issues.liferay.com/browse/LPS-106646.
Thanks.

**Pull request closed without merging**
