### PR TITLE
LPS-96186 Set authentication and endpoint

### PR DESCRIPTION
**Pull request by leoadb**
cc @jeyvison

@brianchandotcom Please see your comments in #74943.

### CODE REVIEW

**Comment by jpince** [comment]
ci:close @leoadb @jeyvison please fix compile error, looks related
```
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/data-engine/data-engine-taglib/src/main/java/com/liferay/data/engine/taglib/servlet/taglib/util/DataLayoutTaglibUtil.java:17: error: package com.liferay.data.engine.rest.client.dto.v1_0 does not exist
     [exec] import com.liferay.data.engine.rest.client.dto.v1_0.DataRecord;
     [exec]                                                    ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/data-engine/data-engine-taglib/src/main/java/com/liferay/data/engine/taglib/servlet/taglib/util/DataLayoutTaglibUtil.java:18: error: package com.liferay.data.engine.rest.client.resource.v1_0 does not exist
     [exec] import com.liferay.data.engine.rest.client.resource.v1_0.DataRecordResource;
     [exec]                                                         ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/data-engine/data-engine-taglib/src/main/java/com/liferay/data/engine/taglib/servlet/taglib/util/DataLayoutTaglibUtil.java:170: error: cannot find symbol
     [exec] 		DataRecordResource dataRecordResource = DataRecordResource.builder(
     [exec] 		^
     [exec]   symbol:   class DataRecordResource
     [exec]   location: class DataLayoutTaglibUtil
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/data-engine/data-engine-taglib/src/main/java/com/liferay/data/engine/taglib/servlet/taglib/util/DataLayoutTaglibUtil.java:170: error: cannot find symbol
     [exec] 		DataRecordResource dataRecordResource = DataRecordResource.builder(
     [exec] 		                                        ^
     [exec]   symbol:   variable DataRecordResource
     [exec]   location: class DataLayoutTaglibUtil
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/data-engine/data-engine-taglib/src/main/java/com/liferay/data/engine/taglib/servlet/taglib/util/DataLayoutTaglibUtil.java:178: error: cannot find symbol
     [exec] 		DataRecord dataRecord = dataRecordResource.getDataRecord(dataRecordId);
     [exec] 		^
     [exec]   symbol:   class DataRecord
     [exec]   location: class DataLayoutTaglibUtil
     [exec] 5 errors
     [exec] Note: Some input files use or override a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] Note: /opt/dev/projects/github/liferay-portal/modules/apps/contacts/contacts-web/src/main/java/com/liferay/contacts/web/internal/portlet/ContactsCenterPortlet.java uses unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 
     [exec] > Task :apps:data-engine:data-engine-taglib:compileJava FAILED
```

@reizero00 I recommend re-enabling auto-close for compile failures

**Comment by jeyvison** [comment]
ci:reopen

**Comment by jeyvison** [comment]
Hi @jpince , Brian will handle this compilation error. it only happens in CI.

**Comment by jpince** [comment]
@petershin ideas on how to make this work in a Pull Request?
Comment from the [previous pull](https://github.com/brianchandotcom/liferay-portal/pull/74943#issuecomment-505608862):
> CI is complaining about the rest-client dependency. We used compileInclude and are using now -includeResource. Local is working. Not sure how to add it differently.

**Comment by petershin** [comment]
@jpince, @jeyvison - It looks like its missing this line in `build.gradle`

```
dependencies {
	...
	compileOnly project(":apps:data-engine:data-engine-rest-client")
	...
}
```

**Comment by jpince** [comment]
Just started reviewing :)

**Comment by jpince** [comment]
ci:close @leoadb @jeyvison BChan and I discussed a solution, I will resend this pull after I test it locally.

**Comment by jpince** [comment]
@leoadb @jeyvison needs further changes from Peter to make this work, see https://github.com/petershin/liferay-portal/pull/560

**Pull request closed without merging**
