### PR TITLE
LPS-63073 Show errors in the UI, Brian could you please run the buildLang this time?

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
Jenkins is currently being rebuilt follow this post for more details.
https://status.liferay.com/incidents/chgjmpmmcbjg

Thanks!

**Comment by michaelhashimoto** [comment]
ci:retest

Jenkins has rebuild has completed.

See this post for more details.
https://status.liferay.com/incidents/chgjmpmmcbjg

**Comment by brianchandotcom** [comment]
@marcellustavares please resend.

**Comment by marcellustavares** [comment]
resent to https://github.com/brianchandotcom/liferay-portal/pull/35951

**Pull request closed without merging**
