### PR TITLE
LPS-75930 Fixes static analysis errors in flags-taglib

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @jbalsas

**Comment by jpince** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/614caba90c...204ff3cba8

**Comment by brianchandotcom** [comment]
@sergiogonzalez @jbalsas I rolled this back in upstream. See my emails and comments in https://github.com/brianchandotcom/liferay-portal/pull/53044

Thx.

**Comment by jbalsas** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/53143

**Pull request closed without merging**
