### PR TITLE
LPS-110491 Use value from dataDefinitionField otherwise this operation is pointless

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/99c1b4b52e...cec56eb309

**Comment by brianchandotcom** [comment]
ci:test:stop

**Comment by brianchandotcom** [comment]
@brunobasto I saw it passed else where already.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cec56eb309...cec56eb309

**Comment by brunobasto** [comment]
Yes. I sent it myself and checked the results with our QA @alexcandidos. We also ran the poshi tests locally to double check.

**Pull request closed without merging**
