### PR TITLE
LPS-158214 Expose extended properties in OpenAPI for schemas/DTOs that are extended by ExtensionProviders

### PR DESCRIPTION
**Pull request by ccorreagg**
Related PR: https://github.com/brianchandotcom/liferay-portal/pull/120638

Resent because of the conflicts with a bnd.bnd file

---

This PR contains the code to expose the Extended Properties in the OpenAPI file. Those properties are exposed in the Schemas whose DTO class is extended by a list of ExtensionProvider.

For that, the functionality has been included in the existing method of the implementation of the OpenAPIResource Vulcan Interface.

An **OpenAPISchemaFilter** object is created if there are extended properties to include. If there are not properties defined for any of the DTO classes, the `OpenAPISchemaFilter` parameter is passed as null to the getOpenAPI method, so no new field or Schema will be created.

```
@Override
public Response getOpenAPI(
		Set<Class<?>> resourceClasses, String type, UriInfo uriInfo)
	throws Exception {

	OpenAPISchemaFilter openAPISchemaFilter = null;

	// Create a OpenAPISchemaFilter if there are extended properties to include

	return getOpenAPI(openAPISchemaFilter, resourceClasses, type, uriInfo);
}
```
---
In order to maintain the same method header to avoid breaking changes, a new interface (and its implementation) has been created: `JaxRsResourceRegistry`. This registry will return, given a JaxRs resource class name and a property name, its value in case it exists. If not, null will be returned. This will be used to recover the external DTO class name, having the name of the JaxRs Resource.

---
Based on the `PropertyDefinition` objects returned by the `ExtensionProvider` interfaces, the properties will be exposed in the OpenAPI as follows:

- For "basic" properties (`PropertyType in [BIG_DECIMAL, BOOLEAN, DATE_TIME, DECIMAL, DOUBLE, INTEGER, LONG, TEXT]`): the property will be added to the current Schema with the name provided by the field `PropertyDefinition.propertyName`.

- For a Single element property (`PropertyType == SINGLE_ELEMENT`) (for example, a Custom Object related to a System Object with a 1toM or 1to1 relationship):
  - A schema will be created with the name provided by the field `PropertyDefinition.propertyClassName` (or with the prefix "C." in case there is another existing Schema with that name). 
  - A property with type = "object" with a reference to the recently created schema and whose name is provided by the field `PropertyDefinition.propertyName`.

- For a Multiple element property (`PropertyType == MULTIPLE_ELEMENT`) (for example, a Custom Object related to a System Object with a Mto1 or MtoM relationship):
  - A schema will be created with the name provided by the field `PropertyDefinition.propertyClassName` (or with the prefix "C." in case there is another existing Schema with that name). 
  - A property with type = "array" with a reference to the recently created schema and whose name is provided by the field `PropertyDefinition.propertyName`.

---

### Example with a possible Extension with Objects:

Given an ExtensionProvider for managing Objects, and the System Object **UserAccount** of the **Headless Admin User** API, having the following fields and relationships:
- `additionalName_ext`: String field
- `emailAddress_ext`: String field
- `givenName_ext`: String field
- `uuid_ext`: String field
- `universityUsers`: 1 to Many relationship between the Custom Object `University` and the System Object `UserAccount`
- `usersSubjects`: Many to Many relationship between the Custom Object `Subject` and the System Object `UserAccount`.

For that case:

1. The fields `additionalName_ext`, `emailAddress_ext`, `givenName_ext` and `uuid_ext` are added to the existing schema `UserAccount` in the OpenAPI
2. A new Schema `University` is created with the properties of the Custom Object `University`.
image
3. A new Schema `Subject` is created with the properties of the Custom Object `Subject`.
image
4. A new field `universityUsers` of type `object` is added to the existing Schema `UserAccount` in the OpenAPI.
5. A new field `usersSubjects` of type `array` is added to the existing Schema `UserAccount` in the OpenAPI.

image

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0646de52e6...0e860340bd

**Comment by brianchandotcom** [comment]
Very very nice @ccorreagg no changes from me. I'll backport the regeneration for older branches.

**Comment by ccorreagg** [comment]
Perfect. Thanks!

**Pull request closed without merging**
