### PR TITLE
ISSITES 5302 updates

### PR DESCRIPTION
**Pull request by allen-ziegenfus**

### CODE REVIEW

**Comment by allen-ziegenfus** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Thx. I'll review this tonight @allen-ziegenfus asynchronously

**Comment by allen-ziegenfus** [comment]
sounds good @brianchandotcom  - I'm happy to meet tonight if you'd like, but tomorrow I have PTO so I won't be available.

**Comment by allen-ziegenfus** [comment]
Closing this for now as I have a better approach - will resend

**Pull request closed without merging**
