### PR TITLE
LPS-91698 Fix after rebase

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:reopen

**Comment by matethurzo** [comment]
@brianchandotcom unrelated SB error

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8b16f141f2...7dac01dc59

**Comment by brianchandotcom** [comment]
@matethurzo @danielkocsis See my fixes in upstream (you guys missed a few).

There may be a few more missed, I recommend you going to the change-tracking directory, and running "git grep resourcePrimKey" and same for classNameId and classNamePK so you can see all the usages.

Thx.

**Pull request closed without merging**
