### PR TITLE
LPS-68480 No longer necessary

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @jonathanmccann @ealonso

**Comment by jpince** [comment]
Integration test failure, see error below:
```
com.liferay.portal.kernel.dao.orm.ORMException: org.hibernate.exception.GenericJDBCException: could not delete: [com.liferay.portal.model.impl.ResourcePermissionImpl#34722]
```
I'm going to close this pull. If you feel this error is unrelated, please reopen to retest.

**Comment by jpince** [comment]
ci:close

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
