### PR TITLE
LPS-132912 refactor toJSONObject

### PR DESCRIPTION
**Pull request by joseabelenda**

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/88c323f4d2...cb7b5cc1ce

**Comment by jpince** [comment]
@joseabelenda you can't add digital signature into anything outside that app until you actually include it into the release build (remove [lrbuild-releng-ignore](https://github.com/liferay/liferay-portal/blob/master/modules/apps/digital-signature/.lfrbuild-releng-ignore) and follow steps). Otherwise, the release build will have startup errors (because digital signature is missing).

**Comment by joseabelenda** [comment]
@jpince
The commit [59808ca](59808ca230b2d327f2410350a93dd0441b27da87) reverts this operation until GA2 release.
Was previously aligned.

Thank you!

**Pull request closed without merging**
