### PR TITLE
LPS-176087  Remove FF of Bookmarks and Modifiable as system object

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
Issues : 

[LPS-176087](https://liferay.atlassian.net/browse/LPS-176087)
[LPS-197882](https://liferay.atlassian.net/browse/LPS-197882)

PR original : 
https://github.com/liferay-objects/liferay-portal/pull/2650

### CODE REVIEW

**Comment by pedro-oliveira446** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@pedro-oliveira446 this doesn't make any sense. If you remove the FF for bookmarks, but also remove modules/apps/object/object-service/src/main/resources/com/liferay/object/internal/batch/bookmarks.batch-engine-data.json, then what are we enabling???

**Comment by gabrielwas** [comment]
Hey @brianchandotcom 

When we started developing Modifiable System Objects, we were using the Bookmarks feature flag for this feature. That's why those two FFs are tight to each other and should be removed together. 

For now, we want to release just the Modifiable System Object feature (there are other modules creating modifiable system objects), but we don't want to release Bookmarks anymore (at least, yet)

**Comment by gabrielwas** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/39ce9c42b6...11fa8bf356

**Pull request closed without merging**
