### PR TITLE
Lps 67078

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@Preston-Crary can you look at this? Thx. See unit failure.

cc @shuyangzhou

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/533b1644d9...88bc72c690

**Comment by Preston-Crary** [comment]
@brianchandotcom Yes, I'll add it to the list.

**Comment by shuyangzhou** [comment]
@brianchandotcom it is caused by the CI build replicating which was turned on this morning. The reason is unit test requires an in-complete build, it assumes osgi/static folder is empty and util-taglib.jar is missing. And the replication is a complete build, so it breaks the unit test. @kiyoshilee is fixing it now.

**Comment by shuyangzhou** [comment]
This should fix it https://github.com/brianchandotcom/liferay-portal/pull/42662

**Pull request closed without merging**
