### PR TITLE
LPS-58597 As a developer I want to mark my portlet as a full page application app

### PR DESCRIPTION
**Pull request by jkappler**
@brianchandotcom, the package was moved as mentioned. Let us know what you think.

thx

### CODE REVIEW

**Comment by jkappler** [comment]
CC:/ @JorgeFerrer, @epgarcia

**Comment by jkappler** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1a613fe64d...a43ef295a9

**Comment by brianchandotcom** [comment]
@jkappler I made a few relevant changes in upstream. Can you review? Thx.

**Comment by jkappler** [comment]
@brianchandotcom It works great.

Thanks!

**Pull request closed without merging**
