### PR TITLE
LPS-118906 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-118906

This is only for master.

@jkappler

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tasks are not related to changes in PR.
See https://github.com/liferay-echo/liferay-portal/pull/1915
✔️ ci:test:stable - 21 out of 21 jobs passed
❌ ci:test:relevant - 95 out of 100 jobs passed in 1 hour 41 minutes

**Comment by brianchandotcom** [comment]
@jkappler 

httpServletRequest.setAttribute(

We usually sort by keys

Can you burrito

modules/apps/asset/asset-display-page-api/src/main/java/com/liferay/asset/display/page/portlet/BaseAssetDisplayPageFriendlyURLResolver.java

and make sure they keys are sorted and by usage. Thx.

**Comment by brianchandotcom** [comment]
@jkappler if what I said doens't make sense, I can do a screen share and do a few with you tomorrow. Thx.

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
