### PR TITLE
LPS-98640 Build Rest

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@hhuijser can you and @ling-alan-huang work on this pull and send it back to me? Basically, I'd like to keep the proper order. The way they break it into multiple lines is a good idea. We should come up with a standard line break length. You guys can decide. Thx!

@epgarcia fyi @hhuijser will resend to me. Thx!

**Comment by dgarciasarai** [comment]
Thanks @brianchandotcom @hhuijser @ling-alan-huang :)
Let me know when you resend these changes.

**Comment by ling-alan-huang** [comment]
I will start to work on this.

**Comment by ling-alan-huang** [comment]
Sent SF pull request to Hugo for review: https://github.com/hhuijser/liferay-portal/pull/3808

**Comment by ling-alan-huang** [comment]
Sent fix on buildREST to Peter for review: https://github.com/petershin/liferay-portal/pull/741

**Pull request closed without merging**
