### PR TITLE
LPS-109794 Add api for remote cluster alias

### PR DESCRIPTION
**Pull request by BryanEngler**
**ci:test:search-es7 - 47 out of 52 jobs passed** https://github.com/BryanEngler/liferay-portal/pull/487#issuecomment-594810659
✅ The only failures unique to this pull are also failing on the upstream canary https://github.com/xbrianlee/liferay-portal/pull/369#issuecomment-594807029

Author(s): @BryanEngler

---
*[Task] Add api for remote cluster alias*
https://issues.liferay.com/browse/LPS-109794

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@BryanEngler Beginning next week, I will no longer merge any pull requests where stable is not green on my PR.

This is in preparation for moving to the CI forward infrastructure in 3 weeks.

Pleas talk to @arbolibeira

Passing somewhere else will no longer be good enough starting next week.

@jpince fyi

**Comment by brianchandotcom** [comment]
@BryanEngler there are a lot of search related upgrade issues in this pull. Please resend.

**Comment by joshchong** [comment]
Hey @brianchandotcom @BryanEngler I confirmed that all of unique search functional failures in the `ci:test:relevant` run were caused by a non-search related bug that was introduced today as described in this ticket: https://issues.liferay.com/browse/LPS-109811

Also in the `ci:test:relevant` run, no stable tests actually failed. The results comment just miscategorized those tests as stable tests.

**Comment by joshchong** [comment]
ci:reopen

**Pull request closed without merging**
