### PR TITLE
LPS-96736

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:test:sharing

**Comment by brianchandotcom** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/397e215b43...2431dade5b

**Comment by brianchandotcom** [comment]
lbm:backport @jpince @adolfopa this one is big... and is all yours.

**Pull request closed without merging**
