### PR TITLE
OAUTH2-241 Update tests to ignore default configurations

### PR DESCRIPTION
**Pull request by csierra**
/cc @topolik @stian-sigvartsen @petershin

this pull needs https://github.com/brianchandotcom/liferay-portal/pull/67670

@jpince @xbrianlee

### CODE REVIEW

**Comment by csierra** [comment]
@brianchandotcom here you can see a snapshot of how the scopes are correctly prefixed with the application name using the defaults in this pull
captura de pantalla 2019-02-06 a las 17 38 06

**Comment by xbrianlee** [comment]
Failures above should be resolved by #67670 as Carlos indicated

FYI @joshchong

**Comment by xbrianlee** [comment]
ci:close

@csierra I re-ran our tests with commits from both PRs but our functional test is still failing. I'll ping you about the issue we're running into.

**Comment by csierra** [comment]
hey @xbrianlee, yes... it is expected that the global scopes tab go away because with this configuration all application scopes are prefixed so no scopes are global.

**Pull request closed without merging**
