### PR TITLE
LRQA-31956 | master

### PR DESCRIPTION
**Pull request by sharonchoi**
https://issues.liferay.com/browse/LRQA-31956

ee-7.0.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/16766

### CODE REVIEW

**Comment by sharonchoi** [comment]
ci:reopen

**Comment by sharonchoi** [comment]
ci:retest

**Comment by vicnate5** [comment]
Poshi test failure being investigated under https://issues.liferay.com/browse/LRQA-31609

**Comment by vicnate5** [comment]
Test fix sent https://github.com/brianchandotcom/liferay-portal/pull/48539

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9114991ab4...041ac9d1f2

**Pull request closed without merging**
