### PR TITLE
[TS] LPS-69480 (Fixed sorting)

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-69480

Hi Brian,

Resending https://github.com/brianchandotcom/liferay-portal/pull/45548#issuecomment-267513700.

This is the most straightforward sorting I could come up with for methods ```setUpClass``` and ```tearDown``` by also considering the dependencies between the entities (so not deleting something earlier than it's allowed) and the general "define close to usage" coding guideline.

Happy Holidays!

Regards,
Tibor

----
Author: @amadeafejes
Reviewers: @NorbertKocsis, @Preston-Crary, @lipusz

### CODE REVIEW

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@lipusz please resend. See comment:

```
Closing pull request because pull requests sent to this user may not be updated. Please resend this pull request.
```

You need to resend to ensure a clean retest. Thx.

**Comment by lipusz** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/45646

**Pull request closed without merging**
