### PR TITLE
OAUTH2-174 Try original.service.bundleid first

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@csierra I merged this, but I don't like the name

```
Object property
```

We also have

```
String serviceProperty
```

Is "Object property'" a serviceProperty, a propertyKey? or a propertyValue? I merged it, but please send a follow up pull and clarify the var name. Thx.

**Comment by csierra** [comment]
hi @brianchandotcom, 

let me know if this is better https://github.com/brianchandotcom/liferay-portal/pull/60692
Thx.

**Pull request closed without merging**
