### PR TITLE
LPS-67049

### PR DESCRIPTION
**Pull request by Ithildir**
@tomwang2011: do you remember if this test compiled correctly when you sent https://github.com/brianchandotcom/liferay-portal/pull/41919?

cc @pyoo47

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:retest

**Comment by tomwang2011** [comment]
@Ithildir Thanks for catching that Andrea, I thought it was fine when module-unit passed, but now I think about it, it is probably because we are not running unit tests on the non-test modules.

**Comment by Ithildir** [comment]
It's failing now on master, so CI tries to run unit tests anyway, even if they're not part of a test module. I really can't figure out why your pull didn't fail, @pyoo47 is investigating.

**Comment by brianchandotcom** [comment]
@tomwang2011 please resend. Thx.

**Pull request closed without merging**
