### PR TITLE
Lps 81336 3

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @jpince

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by jpince** [comment]
@shuyangzhou thanks!

cc/ @mhan810 @achaparro @dylan-rebelak

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by jpince** [comment]
@shuyangzhou pull results will show failures in FileSystemStoreTest and service builder that have already been addressed
see https://loop.liferay.com/home/-/loop/feed/11941378

**Comment by jpince** [comment]
@shuyangzhou also found some errors in modules-integration-postgresql, I let Carlos know in [LRQA-41337](https://issues.liferay.com/browse/LRQA-41337?focusedCommentId=1346745&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1346745)

**Comment by jpince** [comment]
@shuyangzhou Peter already fixed the SF error in upstream. Everything else looks consistent with failures I've already ignored and/or asked for help to fix.

**Comment by shuyangzhou** [comment]
That's good, thanks @jpince !

**Comment by jpince** [comment]
@shuyangzhou Brian never pushed this up, I did it just now https://github.com/liferay/liferay-portal/compare/1473ec26a603dc9cf620ee1761baf256836c57e2...513974fe1bdafc152a58356d5836f01af468ad52

**Pull request closed without merging**
