### PR TITLE
LPS-75995 Enable export-import tests

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:relevant (Some Jenkins masters crashed..)

**Comment by brianchandotcom** [comment]
Nice @matethurzo

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5b96184c4f...d51040227c

**Comment by brianchandotcom** [comment]
@matethurzo @kmaria I backported this to 7.1.x. Please review to make sure they don't break 7.1.x. I also need you guys to help me backport to 7.0.x if needed. Thx.

**Pull request closed without merging**
