### PR TITLE
[TS] LPS-173082 SAML stuck in redirect loop with site virtual host - renames

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Hi Brian. Following up on https://github.com/brianchandotcom/liferay-portal/pull/129349#issuecomment-1407283052

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:reopen

**Comment by stian-sigvartsen** [comment]
cc @jpince

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/237b6fa8a8...08f41d2f5f

**Comment by melodywu** [comment]
ci:test:bundle

**Pull request closed without merging**
