### PR TITLE
Lps 138315

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPS-138315

Forwarding from https://github.com/liferay-upgrades/liferay-portal/pull/25, confirmed the test failures were not related to this fix and this can be manually forwarded with @vicnate5

/cc @achaparro

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by vicnate5** [comment]
@brianchandotcom Fixes a release blocker

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6194add670...fe591cf609

**Comment by brianchandotcom** [comment]
@SamZiemer see fe591cf6091d0dae433649838c3a2e4cd2299a4d

**Pull request closed without merging**
