### PR TITLE
[See comments inside] LPS-69436 Update Flags-Taglib with Metal.js and Soy

### PR DESCRIPTION
**Pull request by jbalsas**
Hey Brian,

I'm resending https://github.com/brianchandotcom/liferay-portal/pull/48044 after going over your [comments](https://github.com/brianchandotcom/liferay-portal/pull/48044#issuecomment-291379328). Some clarifications:
- When **deploying the flags module, nothing breaks in runtime**. All applications using the taglib keep working normally.
- We **have transitive dependencies disabled** in the build. This forces everyone using the taglib to also declare its transitive dependencies (in order to be able to compile) now, but it is an expected build update
- For CI, we have `compileJSP` enabled, that's what surfaces the build error in our case.

As far as we see, there's nothing else we can do, nor should we.

/cc @ambrinchaudhary, @sergiogonzalez, @migue

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:reopen

**Comment by jpince** [comment]
@brianchandotcom SF is complaining about a newline at the end of message-boards-web/build.gradle, but no change was made, and this file looks the same as any other build.gradle.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6d39c21770...b6a18dcf00

**Comment by brianchandotcom** [comment]
@jbalsas thank you for explaining this in detail. You understood my objections and your statements make perfect sense.

@jpince the CI issue is an issue with how we are using JGit in CI.

@pyoo47 has a fix for that CI issue which I've merged in https://github.com/brianchandotcom/liferay-portal/pull/48093

**Comment by brianchandotcom** [comment]
@ambrinchaudhary one minor SF change in c054e427243ae4df65d58dc9d3be8277e71e6574

**Comment by jbalsas** [comment]
No problem! thanks a lot @brianchandotcom!

**Pull request closed without merging**
