### PR TITLE
LPS-64569 register ALL WAB contexts

### PR DESCRIPTION
**Pull request by rotty3000**
/cc @marcellustavares

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:retest

**Comment by sharonchoi** [comment]
investigating RecyclebinUsecase#RestoreDMDocumentFromFolderCP

**Comment by sharonchoi** [comment]
@brianchandotcom @brianchiu For RecyclebinUsecase#RestoreDMDocumentFromFolderCP see: https://github.com/brianchandotcom/liferay-portal/pull/38063

Test will be turned off until bug is fixed.

**Comment by rotty3000** [comment]
All, I've rebased and updated. I'll let you trigger a CI retest.

**Comment by rotty3000** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@rotty3000 

VelocityTemplateTest.classMethod
VelocityTemplateTest.classMethod
FreeMarkerTemplateTest.testGet

Those test failures look real? Please resend. Thx.

**Pull request closed without merging**
