### PR TITLE
LPS-68336 Add upgrade process

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@marcellustavares modules-int-* broken. please resend.

**Comment by marcellustavares** [comment]
@brianchandotcom this is not related.

**Comment by marcellustavares** [comment]
ci:reopen

**Comment by marcellustavares** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@marcellustavares please resend. Thx.

**Comment by marcellustavares** [comment]
resent to https://github.com/brianchandotcom/liferay-portal/pull/43819

**Pull request closed without merging**
