### PR TITLE
LPS-96722 - Use clipboardjs instead metal-clipboard

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by carloslancha** [comment]
@brunobasto when you remove the unused file `copy_form_publish_url` in `ddm-form-web` please remember to remove `metal-clipboard` dependency from `package.json`. Thx!

**Comment by carloslancha** [comment]
ci:reopen

**Comment by carloslancha** [comment]
ci:sf

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:reopen

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by brianchandotcom** [comment]
@carloslancha this can't be right, I see the word

```
debugger
```

Please resend.

**Comment by carloslancha** [comment]
Resent https://github.com/brianchandotcom/liferay-portal/pull/75247

**Pull request closed without merging**
