### PR TITLE
LPS-173665 New configuration for managing asset.categories.search.hierarchical property at instance level and using the UI

### PR DESCRIPTION
**Pull request by Tim-Cao**
This is only for master.

https://issues.liferay.com/browse/LPS-173665

@lfbesada

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/10934

**Comment by ealonso** [comment]
@lfbesada There are conflicts, Could you please rebase and resend?

**Comment by ealonso** [comment]
ci:close

**Pull request closed without merging**
