### PR TITLE
LPS-58100 use portletInstance with shared plid for embedded portlets

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @jkappler @jorgeFerrer

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by jkappler** [comment]
The error: :apps:document-library:document-library-web:generateJSPJava FAILED is already fixed in master

**Comment by juliocamarero** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7fc71b2d7f...50ea7b36e6

**Comment by brianchandotcom** [comment]
@juliocamarero please review my changes in upstream. Thx.

**Pull request closed without merging**
