### PR TITLE
LPS-65233 encode url in test to comform with RFC 3986

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:stop

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@juliocamarero merged. This is good. Fixed the CI issue in upstream.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/698d3f6892...3adb43ee0f

**Comment by brianchandotcom** [comment]
@ealonso can you backport this test to 7.0.x?

**Comment by ealonso** [comment]
sure

**Pull request closed without merging**
