### PR TITLE
LPS-93391 Overriding comment email templates through portal properties does not work

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by jpince** [comment]
@adolfopa @IstvanD @robertoDiaz I don't see these int test failures in upstream, can you please take a look?

com.liferay.comment.notifications.test.CommentUserNotificationTest.testAddUserNotificationWhenDiscussionEmailPortalPropertyDisabled
com.liferay.comment.notifications.test.CommentUserNotificationTest.testUpdateUserNotificationWhenDiscussionEmailPortalPropertyDisabled
https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/294262/AXIS_VARIABLE=0,label_exp=!master/consoleFull

cc/ @austinchiang @patriciajeanperez

**Comment by robertoDiaz** [comment]
@adolfopa and @IstvanD 

I've seen that we miss that this tests are using the old properties (see com/liferay/comment/notifications/test/CommentUserNotificationTest.java:194) :

```
protected PortletPreferences
			givenThatDiscussionEmailCommentsAddedIsDisabled()
		throws Exception {

		PortletPreferences portletPreferences = PrefsPropsUtil.getPreferences(
			user.getCompanyId(), false);

		portletPreferences.setValue(
			PropsKeys.DISCUSSION_EMAIL_COMMENTS_ADDED_ENABLED,
			Boolean.FALSE.toString());

		portletPreferences.store();

		return portletPreferences;
	}
```

@IstvanD are you able to handle that??

**Comment by robertoDiaz** [comment]
ci:close

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

Sure.
Should the configuration be mocked, as in KBArchiveFactoryTest?

Thank you,
István

**Comment by robertoDiaz** [comment]
Hi @IstvanD 

Yes, I think that this should work.

Regards

**Pull request closed without merging**
