### PR TITLE
Remove Sharding related code

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@mdelapenya should we drop the Shard table in an upgrade?

Great job on this pull.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4ac360a34d...c1270c34b5

**Comment by migue** [comment]
Let's keep the table so far. We are building a tool to help the client to
move from logical partitioning to a physical one.

Once we are done with the tool we'll take a decision

**Pull request closed without merging**
