### PR TITLE
LPS-93529 New debug traces in checkArticlesByDisplayDate, checkArticlesByExpirationDate and checkArticlesByReviewDate methods

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci test errors seems to be unrelated to my change as I am just adding some debug traces to JournalArticleLocalServiceImpl class.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@jorgediaz-lr see my wordsmithing in upstream.

**Pull request closed without merging**
