### PR TITLE
LPS-68317

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@ithildir all these tests failed because repo1.maven.org was down. Can you fix so we don't go to it for every test? Thx.

**Comment by Ithildir** [comment]
It doesn't seem Gradle related, the errors are like if Arquillian was trying to download dependencies from Maven... I'll keep looking.

**Comment by Ithildir** [comment]
I wrote @csierra and @pyoo47 about what I found.

**Pull request closed without merging**
