### PR TITLE
[BLOCKER] Revert LPS-143631

### PR DESCRIPTION
**Pull request by vicnate5**
@julschong Reverting due to multiple regressions CC @jkappler @ozysouza @ealonso

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:reopen

**Comment by vicnate5** [comment]
Fixes https://issues.liferay.com/browse/LPS-166067

**Comment by julschong** [comment]
@vicnate5 Hi Victor, as per our discussion, 
[Fix missing reference PR2](https://github.com/liferay-core-infra/liferay-portal/pull/2134) along with Catarine's [Fix missing reference PR1](https://github.com/liferay-echo/liferay-portal/pull/9979) should fix the issue of missing reference annotation.

It is currently testing full ci test to make sure the regressions are resolved.
if it is resolved, we won't need to revert the original commits.

CC @jkappler @ozysouza @ealonso

**Comment by vicnate5** [comment]
New solution passed testing. Closing.

**Comment by vicnate5** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/124914

**Pull request closed without merging**
