### PR TITLE
LPS-85055 Add testUrl to jest config

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by carloslancha** [comment]
Hey @john-cu I think this failures has nothing to do with this pr changes. Could you please check it? Thx!

**Comment by carloslancha** [comment]
Hey @john-co I think this failures has nothing to do with this pr changes. Could you please check it? Thx!

**Comment by john-co** [comment]
@carloslancha, the unique failures are flukes. The failing CI tests are unrelated to the new code.

The existing export/import functional tests may need to be updated if this becomes a frequent error in CI. The unique functional tests are failing because the tool-tip icon lingers and thus covers the add button on the next page rendering. Unable to consistently reproduce issue with Poshi run locally.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9206c55b15...df11b3b92f

**Pull request closed without merging**
