### PR TITLE
master-vw-507

### PR DESCRIPTION
**Pull request by vicnate5**
@fernandosouza @brunobasto @pedroqueiroz94

### CODE REVIEW

**Comment by fernandosouza** [comment]
cc. @leoadb

**Comment by vicnate5** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/42474

**Comment by vicnate5** [comment]
Did not mean to close this.

**Comment by vicnate5** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
@vicnate5 lpkg startup, can you resend?

**Comment by vicnate5** [comment]
Resent https://github.com/brianchandotcom/liferay-portal/pull/42487

**Pull request closed without merging**
