### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
@brianchandotcom, I like this better. It matches the way we do things  here: https://github.com/liferay/liferay-portal/blob/master/modules/apps/bookmarks/bookmarks-web/src/main/resources/META-INF/resources/bookmarks/info_panel.jsp#L69-L79

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/450a61885e...c1dd94877f

**Comment by brianchandotcom** [comment]
Sounds good to me. Can you also update app-builder 

git grep HashMapBuilder modules/apps/app-builder/**.jsp

I've been using 

modules/apps/app-builder/app-builder-web/src/main/resources/META-INF/resources/view.jsp:                        HashMapBuilder.<String, Object>put(
modules/apps/app-builder/app-builder-web/src/main/resources/META-INF/resources/view_apps.jsp:                   HashMapBuilder.<String, Object>put(

as my template.

**Comment by brianchandotcom** [comment]
@hhuijser forgot to notify  you (see comment above)

**Pull request closed without merging**
