### PR TITLE
LPS-70045 No permission check exists for attachments

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:reopen

**Comment by adolfopa** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest - https://loop.liferay.com/home/-/loop/feed/5383061

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/24c136c885...052a7fb4f4

**Comment by brianchandotcom** [comment]
@IstvanD please backport. Thx.

**Pull request closed without merging**
