### PR TITLE
LPS-63362 Update constants

### PR DESCRIPTION
**Pull request by marcellustavares**
cc @mhan810

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
@brianchandotcom - This one is running, and the results should be returning soon.

**Comment by marcellustavares** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Will resend this. Failing tests.

**Pull request closed without merging**
