### PR TITLE
LPS-105341 Moving itemSelector injection

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hey @austinchiang,

These failures seem not related to my changes. Can you please have a look?

Thanks!

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
@4lejandrito @brianchandotcom  Functional test failures are unrelated.

SF failures are caused by https://github.com/brianchandotcom/liferay-portal/pull/82519. Looks intentional though

**Comment by 4lejandrito** [comment]
Thanks @austinchiang!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1daffd0b06...e2a83aaede

**Pull request closed without merging**
