### PR TITLE
LRQA-22944 Add in the 'modules/ee' folder from ee-7.0.x

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRQA-22944

@brianchandotcom @pyoo47 @jhendley

Here's the change to copy in the 'modules/ee' folder.

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
@brianchandotcom 

This pull is currently stuck on the PACL tests here:
* [PACL Test #1](http://test-1-16/job/test-portal-acceptance-pullrequest-batch%28master%29/504/AXIS_VARIABLE=2,label_exp=!master/console)
* [PACL Test #2](http://test-1-16/job/test-portal-acceptance-pullrequest-batch%28master%29/504/AXIS_VARIABLE=4,label_exp=!master/console)

**Comment by michaelhashimoto** [comment]
When running the tests with the 'modules/ee' folder added it will timeout on the PACL test.

Here's an example [failure](http://test-1-16/job/test-portal-acceptance-pullrequest-batch%28master%29/504/AXIS_VARIABLE=2,label_exp=!master/console) that I pulled the jstacks of all java processes running on '[cloud-10-0-111-28](http://test-1-16/computer/cloud-10-0-112-18/)'
* [JUnitTestRunner.txt](https://github.com/brianchandotcom/liferay-portal/files/215767/JUnitTestRunner.txt)
* [Launcher.txt](https://github.com/brianchandotcom/liferay-portal/files/215766/Launcher.txt)
* [LocalProcessLauncher.txt](https://github.com/brianchandotcom/liferay-portal/files/215768/LocalProcessLauncher.txt)

**Comment by brianchiu** [comment]
@michaelhashimoto 
These failures are the same as from your previous pull:
https://github.com/brianchandotcom/liferay-portal/pull/38697#issuecomment-209062574

We don't see those failures elsewhere, so it must have something to do with pulling in the ee modules.

**Comment by brianchiu** [comment]
@michaelhashimoto @kenjiheigel

**Comment by michaelhashimoto** [comment]
@brianchiu @kenjikeigel 

We are going to have shuyang look into these failures.

**Pull request closed without merging**
