### PR TITLE
LPS-97123 Keeping naming consistent

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @brianchandotcom, @JorgeFerrer,

This is the follow up of https://github.com/brianchandotcom/liferay-portal/pull/74419#issuecomment-502611476.

With these changes we are merging the 3 OpenNLP auto tag providers into [a single one](https://github.com/brianchandotcom/liferay-portal/pull/74757/files#diff-4c9013b43a4b63c3f069b59e0ec2cb11).

The text extraction logic is now extracted to [its own API ](https://github.com/brianchandotcom/liferay-portal/pull/74757/files#diff-dd4815776ba4e538c13bf908f10e287c) and implemented for each type of asset in their respective modules.

Since we've unified the configuration too, we've had to extend the configuration framework to allow for dynamic options in dropdowns (a776f2278a15ecc704fd2cef7476eed5f3dc32e9 and 18b56a0d5559abaea1bc937d1be01b4739de1e38). @drewbrokke please review those.

This is ready to be merged in if everyone is happy. Once we all agree on the final solution and it gets merged I will send 2 follow up pulls, one adding tests and another one performing the same changes for the GCloud natural language provider.

Thanks!

**Comment by drewbrokke** [comment]
@4lejandrito just one small nitpick at https://github.com/brianchandotcom/liferay-portal/commit/a776f2278a15ecc704fd2cef7476eed5f3dc32e9#r34015862, but otherwise it looks good (and helpful!). Thanks!

**Comment by 4lejandrito** [comment]
Will resend.

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/74779.

**Pull request closed without merging**
