### PR TITLE
LPS-74157 Fix NPE: Reuse lazy initialization of Date Format singleton

### PR DESCRIPTION
**Pull request by arboliveira**
Author: @natocesarrego
Reviewer: @arboliveira

https://issues.liferay.com/browse/LPS-74157

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5b383c2b43...9c054df575

**Comment by brianchandotcom** [comment]
@arboliveira I merged this, please see my change in 9c054df575a39504051f5ebdf11145d5726e1408

However, do we have to do this?

```
testIntegrationCompile group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
```

If it's just compile, can't we just keep the old dependency? You didn't change any signatures.

Thx

**Comment by arboliveira** [comment]
With the original `version: "2.36.0"` the unit test goes red under Eclipse (`gw eclipse` adds `com.liferay.portal.kernel-2.36.0.jar` to `.classpath`, so this jar is the one used by the test.)

With `version: "default"` instead, `gw eclipse` adds `com.liferay.portal.kernel-2.50.0-SNAPSHOT.jar` to `.classpath` and the unit test under Eclipse goes green ✅

**Pull request closed without merging**
