### PR TITLE
LPS-107468 Use consistent, longer timeouts in Karma test runs

### PR DESCRIPTION
**Pull request by wincent**
As per this [comment](https://github.com/brianchandotcom/liferay-portal/pull/83566#issuecomment-576797790), this is another example of an unstable test, like the one we ameliorated in c652366bf373ed12f224eb50a5bcc7de6c1047a0. The related console output is:

> timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

In this commit I am raising the timeouts across the board in the 3 places where we are currently using Karma. I'm not putting this config in [the "liferay-karma-config" package](https://www.npmjs.com/package/liferay-karma-config), because it is in a non-org repo, was last published 3 years ago, is only used in 2 of the 3 Karma usage sites, and we don't think we actually want to encourage further use of Karma precisely because of these kinds of stability issues.

Note that in addition to lifting the Mocha timeout, which is noted as [defaulting to 2000ms here](http://blog.jonathanargentiero.com/overriding-karma-mocha-default-timeout-2000ms/), I'm also lifting the `browserDisconnectTimeout`, because that's the other potential culprit here, as the only [other possible configuration value that defaults to 2000ms](http://karma-runner.github.io/4.0/config/configuration-file.html).

### CODE REVIEW

**Comment by wincent** [comment]
Those test failures look unrelated (in modules not touched by this PR), so I'm going to trigger another run.

**Comment by wincent** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2282a4e8ea...7931b92d00

**Comment by wincent** [comment]
@brianchandotcom: The "right" fix here is to move us away from Karma (I created https://github.com/liferay/liferay-npm-tools/issues/351 for that and will look at it today).

I don't think we need to add enforcement (eg. that the `package.json` files don't contain a `test` script containing the word `karma`) because once we've removed the Karma dependencies from the top-level it won't be possible to use them (or add them back, because we prohibit the addition of new `devDependencies`).

**Pull request closed without merging**
