### PR TITLE
LPS-74849

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by jpince** [comment]
@petershin @hhuijser same error as the previous pull https://github.com/brianchandotcom/liferay-portal/pull/52544#issuecomment-340621783 `java.lang.IllegalStateException: java.lang.ClassNotFoundException: com.liferay.portal.configuration.extender.internal.test.ConfiguratorExtensionTest`

**Comment by petershin** [comment]
Thank you Jason for letting us know!

Hi @hhuijser, I sent a [pull](https://github.com/hhuijser/liferay-portal/pull/3053) to you.  Hopefully the Jenkins tests finish by the time you see this.

**Pull request closed without merging**
