### PR TITLE
LPS-63358 Add additional information to the portal.property description

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @robertoDiaz @topolik

**Comment by sergiogonzalez** [comment]
cc/ @jhinkey can you take a look at the javadoc in  https://github.com/sergiogonzalez/liferay-portal/commit/612b6231ea7a58623fc5832cd8c52d98e7cdec18 ? Thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/41324153ec...abca107821

**Comment by brianchandotcom** [comment]
I made https://issues.liferay.com/browse/LRDOCS-2216 for Jim

**Comment by jhinkey** [comment]
Yes, indeed @sergiogonzalez. Can track via
https://issues.liferay.com/browse/LRDOCS-2216.
- Jim

On 3/2/2016 6:05 PM, Sergio Gonzalez wrote:
>
> cc/ @jhinkey <https://github.com/jhinkey> can you take a look at the
> javadoc in sergiogonzalez@612b623
> <https://github.com/sergiogonzalez/liferay-portal/commit/612b6231ea7a58623fc5832cd8c52d98e7cdec18>
> ? Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/36994#issuecomment-191484067>.
>

-- 
Jim Hinkey
Sr. Knowledge Engineer
Liferay, Inc.
www.liferay.com <http://www.liferay.com>

Visit Us: www.liferay.com <http://www.liferay.com> | Like Us:
facebook.com/liferay <http://facebook.com/liferay> | Follow Us:
twitter.com/liferay <http://twitter.com/liferay>

**Pull request closed without merging**
