### PR TITLE
LPS-94158 Upgrade FindSecurityBugs to 1.9.0

### PR DESCRIPTION
**Pull request by topolik**
Hi Brian,

https://issues.liferay.com/browse/LPS-94158

Thanks.

ci:test:relevant run here https://github.com/topolik/liferay-portal/pull/736 with no related failure

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1d4af98d08...f78ea420aa

**Pull request closed without merging**
