### PR TITLE
COMMERCE 5954 1

### PR DESCRIPTION
**Pull request by ivicac**

### CODE REVIEW

**Comment by ivicac** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b215930ce7...2ab1f9e4d4

**Comment by brianchandotcom** [comment]
@alecsloan can we go over the JSONUtil changes? Basically, 1.) I think some of the naming is wonky and we need to improve it so it fits with the existing JSONUtil methods. 2.) We need to add tests in  JSONUtilTest for the new methods.

**Comment by alecsloan** [comment]
Hey @brianchandotcom, sure thing. We did have some existing test coverage I missed in porting over. I'll get that to you asap tomorrow.

**Pull request closed without merging**
