### PR TITLE
LPS-106492 Define JSON schema for PageDefinition

### PR DESCRIPTION
**Pull request by ruben-pulido**
Hi @brianchandotcom 
I'm including commits related to LPS-108724 which have already been merged by you to master since they haven't made it to upstream yet.

### CODE REVIEW

**Comment by ruben-pulido** [comment]
//cc @ealonso

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/795df2effe...e063a649f3

**Comment by brianchandotcom** [comment]
Merged, but any way to make this simpler:

```
	testCompile classifier: "classic", group: "org.joda", name: "joda-convert", version: "2.2.1"
	testCompile group: "com.damnhandy", name: "handy-uri-templates", version: "2.1.7"
	testCompile group: "com.github.everit-org.json-schema", name: "org.everit.json.schema", version: "1.11.1"
	testCompile group: "com.google.re2j", name: "re2j", version: "1.2"
	testCompile group: "joda-time", name: "joda-time", version: "2.9.1"
	testCompile group: "org.json", name: "json", version: "20180813"
```

I can imagine we're going to add this in many more places.

**Comment by brianchandotcom** [comment]
@ruben-pulido also, should we suffix

String pageDefinition

to be

String pageDefinitionJSON

or 

Thx.

**Pull request closed without merging**
