### PR TITLE
LPS-60186 Categorize Configuration objects

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
@sergiogonzalez @marcellustavares @juliocamarero This pull categorizes all the existing configuration objects (including those owned by your team) as discussed by email. Please follow this pattern going forward whenever a new configuration object is created.

@mhan810 once this is in master you can use this as the basis to add support for search. Follow the Lexicon tutorial to add the right markup

**Comment by marcellustavares** [comment]
:+1:

**Comment by mhan810** [comment]
@jorgeferrer Prob better for one of the UI guys to add the front end
stuff.  I'll put in all the search API calls and etc

**Comment by JorgeFerrer** [comment]
Resent as https://github.com/brianchandotcom/liferay-portal/pull/32168

**Comment by JorgeFerrer** [comment]
@mhan810 Really? It's just three lines of code at most that you just have
to copy and paste. But don't worry, I can do it for you ;)
Will send you a pull once Brian merges this in.

On Fri, Nov 13, 2015 at 3:04 PM, Michael Han <notifications@github.com>
wrote:

> @jorgeferrer Prob better for one of the UI guys to add the front end
> stuff. I'll put in all the search API calls and etc
>
> Sent from my mobile device.
> On Nov 13, 2015 8:21 AM, "Jorge Ferrer" <notifications@github.com> wrote:
>
> > @sergiogonzalez <https://github.com/sergiogonzalez> @marcellustavares
> > <https://github.com/marcellustavares> @juliocamarero
> > <https://github.com/juliocamarero> This pull categorizes all the
> existing
> > configuration objects (including those owned by your team) as discussed
> by
> > email. Please follow this pattern going forward whenever a new
> > configuration object is created.
> >
> > @mhan810 <https://github.com/mhan810> once this is in master you can use
> > this as the basis to add support for search. Follow the Lexicon tutorial
> to
> > add the right markup
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/brianchandotcom/liferay-portal/pull/32157#issuecomment-156430345
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/32157#issuecomment-156439349>
> .
>



-- 
Jorge Ferrer
Vice President, Engineering
@jorgeferrer <https://twitter.com/jorgeferrer>

*Liferay Inc*
Web <http://www.liferay.com> | Facebook <http://facebook.com/liferay> |
Twitter <http://twitter.com/liferay>


*Aviso de Confidencialidad: *Este mensaje de correo electrónico, incluidos
los archivos adjuntos, enviados en nombre de Liferay SL es para el uso
exclusivo del destinatario (s) previsto y puede contener información
confidencial y privilegiada. Se prohíbe cualquier revisión no autorizada,
uso, copia, divulgación o distribución. Si usted no es el destinatario, por
favor póngase en contacto con el remitente por correo electrónico de
respuesta y destruir todas las copias del mensaje original. Gracias.

*Confidentiality Notice: *This e-mail message, including any attachments,
sent on behalf of Liferay SL is for the sole use of the intended
recipient(s) and may contain confidential and privileged information. Any
unauthorized review, use, copying, disclosure or distribution is
prohibited. If you are not the intended recipient, please contact the
sender by reply e-mail and destroy all copies of the original message. Thank
you.

**Comment by mhan810** [comment]
You know what I say to UI stuff ;)

**Pull request closed without merging**
