### PR TITLE
Lps 69939

### PR DESCRIPTION
**Pull request by shuyangzhou**
Resend of https://github.com/brianchandotcom/liferay-portal/pull/45953

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@brandizzi this new test CalendarBookingLocalServiceTest.testAddAllDayCalendarBooking is breaking during the night but not during the morning.  Time zone issue. Please fix. Thx.

**Comment by brianchandotcom** [comment]
@Preston-Crary not merging. You manually modified an @generated file?

See 029970b73f19d0728fc7f8a3ea9d8e963c409046

Have we done that else where? Please resend.

**Comment by Preston-Crary** [comment]
@brianchandotcom Yes, we have done that elsewhere... see 92ed7b1.  Both of these changes were reverting generated changes.

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/45986

**Pull request closed without merging**
