### PR TITLE
LPS-53988 Add tests for AuthTokenUtil extension point

### PR DESCRIPTION
**Pull request by mdelapenya**
Please see https://github.com/brianchandotcom/liferay-portal/pull/24573 cc/ @migue

### CODE REVIEW

**Comment by mdelapenya** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Can you try resending this? Shuyang fixed a bunch of the OSGi tests @mdelapenya 

Thx

**Pull request closed without merging**
