### PR TITLE
master-qa-22797-new

### PR DESCRIPTION
**Pull request by vicnate5**
https://issues.liferay.com/browse/LRQA-22797
https://issues.liferay.com/browse/LRQA-27310

CC @marcellustavares Adds tests to the PR tester

### CODE REVIEW

**Comment by vicnate5** [comment]
@ctampoya

**Comment by vicnate5** [comment]
Sent to 7.0.x https://github.com/brianchandotcom/liferay-portal/pull/44167

**Comment by michaelhashimoto** [comment]
ci:retest - Failed due to broken distribution node.

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
