### PR TITLE
LPS-85974 Covers gap with dropdown menu to prevent mouse from leaving the trigger and hiding the dropdown

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
hey @jpince, sourceformatter is wrong here, can you figure this one out, please?

**Comment by jpince** [comment]
@john-co please look into SF error. build failure looks like a network issue.

**Comment by jbalsas** [comment]
As I said, this is probably for @hhuijser to figure out

**Comment by john-co** [comment]
@jbalsas @jpince, 
Based on the conversation trail, I'll let @hhuijser look into it since it seems like he was intended to be tagged in the first place and not jpince. If you still want me to look into this, please let me know and I'll check it out.

**Pull request closed without merging**
