### PR TITLE
LPS-61340

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8eadfcbc51...175adbb1ba

**Comment by brianchandotcom** [comment]
@topolik can you fix SanitizerUtilTest. Lots of deprecated usage now.

**Comment by topolik** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/33986. Thank you.

**Pull request closed without merging**
