### PR TITLE
LPS-196957 Update dtd description for change-tracked columns

### PR DESCRIPTION
**Pull request by brookedalton**
Follow up to https://github.com/brianchandotcom/liferay-portal/pull/142556

cc: @pei-jung @david-truong

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:reopen

**Comment by brookedalton** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4e50e1ea85...20e1638aa5

**Comment by brianchandotcom** [comment]
@brookedalton minor changes in 20e1638aa57e74c8458fcc0ba3cabd573dbf27cd

**Pull request closed without merging**
