### PR TITLE
LPS-55497 Update references

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/61fcb98e2c...cfa2edd507

**Comment by brianchandotcom** [comment]
@marcellustavares what about also using the local *PortletKeys. Within the module, we should use its own. Eventually, the PortletKeys in portal will go away.

**Comment by brianchandotcom** [comment]
@marcellustavares com_liferay_dynamic_data_mapping_web_portlet_PortletDisplayTemplatePortlet inside the ddm web module should use its own DDMPortletKeys.

**Comment by marcellustavares** [comment]
Sounds good @brianchandotcom! I'll update that.

thx

**Pull request closed without merging**
