### PR TITLE
LPS-88707 SF

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
cc @linolaoj

**Comment by linolaoj** [comment]
ci:reopen

**Comment by clovisdasilvaneto** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/54e3e7afce...54e3e7afce

**Comment by brianchandotcom** [comment]
@brunobasto I think I already merged this

**Comment by brunobasto** [comment]
Hey @brianchandotcom, yeah you did. I resent cause this was had an SF failure, but didn't have time to talk to Leo to close this one.

**Pull request closed without merging**
