### PR TITLE
LPS-171363 Widget Pages run into conflicts in a publication too easily

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LPS-171363

Tested in https://github.com/liferay-publications/liferay-portal/pull/365. Manually forwarding due to unrelated failures in `relevant`.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/61b39c0f97...61b39c0f97

**Comment by mbowerman** [comment]
@david-truong @xbrianlee What happened here? This does not appear to be the same set of changes as on https://github.com/liferay-publications/liferay-portal/pull/365.

**Comment by david-truong** [comment]
Oh we made additional changes after we discovered additional conflicts we didn't see from the first test case.  I will backport the second set of changes later today.

**Comment by david-truong** [comment]
@mbowerman sorry i didn't understand what you meant at first... I see that @xbrianlee sent a different one probably because of the same reason.

**Comment by david-truong** [comment]
manually forwarded the second half: https://github.com/brianchandotcom/liferay-portal/pull/128782

**Pull request closed without merging**
