### PR TITLE
LPS-88402 Reorder

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
cc: @achaparro

**Comment by jpince** [comment]
@kyle-miho @brianchiu please look into POSHI failures

**Comment by kyle-miho** [comment]
Looking through this currently!

**Comment by kyle-miho** [comment]
ci:close @ealonso @pavel-savinov @jpince Pretty sure there is an issue here, I'll report my testing to Eudaldo and Pavel when I finish

**Comment by pavel-savinov** [comment]
Hey @kyle-miho, yep, my fault, sorry. I've just sent you a PR here: https://github.com/kyle-miho/liferay-portal/pull/122
Thanks!

**Pull request closed without merging**
