### PR TITLE
LPS-65158 Redirect to correct page

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@ealonso are the poshi tests related? Should I merge this? @evannagayama?

**Comment by evannagayama** [comment]
Seems like the functional tests passed https://testray.liferay.com/home/-/testray/runs/40552201, but there are some errors in the console: https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=4,label_exp=!master/2780//console

**Comment by ealonso** [comment]
I think those errors could be related with this pull.

@evannagayama, Could you please take a look at poshi errors? or Could you talk with the QA engineer for collaboration team?

**Comment by evannagayama** [comment]
Yeah will do, thanks

**Comment by evannagayama** [comment]
@ealonso the issue seems to be with a recycle bin warning message and the browser speed. Can you send me this pr and we'll fix the functional test? Thanks!

ref:
https://testray.liferay.com/home/-/testray/case_results/40565158

**Comment by kevin-yen** [comment]
@evannagayama @ealonso I'm looking into the problem with the incorrect links. I'm run this pull again on my custom Jenkins branch so I have more data on exactly what the problem is.

**Comment by brianchandotcom** [comment]
Ok. Closing this pull for myself then.

**Comment by evannagayama** [comment]
@ealonso I fetched this branch, updated the tests and pushed it here: https://github.com/brianchandotcom/liferay-portal/pull/38954

You changed the warning message to an error message, so our test just needed to be updated. Thanks!

**Pull request closed without merging**
