### PR TITLE
LPS-169826 Set listTypeDefinitionId to ObjectField when importing an Object Definition

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-169826

### CODE REVIEW

**Comment by mateussgn** [comment]
Tests had successfully passed: https://github.com/liferay-objects/liferay-portal/pull/1677

**Comment by mateussgn** [comment]
ci:reopen

**Comment by mateussgn** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/695f911050...908dbbe703

**Pull request closed without merging**
