### PR TITLE
LPS-86090 Make the method name clearer

### PR DESCRIPTION
**Pull request by achaparro**
@shuyangzhou

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.

View just my changes: https://github.com/brianchandotcom/liferay-portal/compare/achaparro:d6b999a0ed...47f1059cf7
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bc7c11c420...47f1059cf7

**Comment by brianchandotcom** [comment]
@achaparro minor change in upstream. Backported to 7.1.x for you since this is so easy. Please backport to 7.0.x

**Comment by brianchandotcom** [comment]
@achaparro also, I assume you'll send me a pull for master-private now so we fix this for SQL Server and not just MySQL? Thx.

**Comment by achaparro** [comment]
Hi @brianchandotcom,

Here it is the master-private pull:
https://github.com/brianchandotcom/liferay-portal-ee/pull/21937

Thanks!

**Comment by achaparro** [comment]
Sorry this one:
https://github.com/brianchandotcom/liferay-portal-ee/pull/21938

**Pull request closed without merging**
