### PR TITLE
LPS-76644

### PR DESCRIPTION
**Pull request by Ithildir**
Hi @brianchandotcom,
This pull enables the publishing of most of our Gradle plugins to https://plugins.gradle.org/. We need to get credentials from https://login.gradle.org/user/login and set them in `build.*.properties`:
```properties
gradle.publish.key=
gradle.publish.secret=
```
Do you want to create a company account with a password of your choice, or you want me to do it?

Thanks!

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:test

**Comment by Ithildir** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@Ithildir Conflict, please resend? Also, can you make a liferay account and send me the credentials? Thx.

**Comment by Ithildir** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/54024.

**Pull request closed without merging**
