### PR TITLE
LPS-190314 Rename to ObjectDefinitionScoped

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3e360e4254...379d5d45bc

**Comment by brianchandotcom** [comment]
@MarinhoFeliphe your changes are nice. See 379d5d45bc941efe624948991865b40fe63e5c14

Integration tests?

**Comment by MarinhoFeliphe** [comment]
We're gonna do that,

Thanks

**Pull request closed without merging**
