### PR TITLE
LPS-103035 Add companyId to primarykeys and unique indexes

### PR DESCRIPTION
**Pull request by achaparro**
cc/@preston-crary @vicnate5 @kyle-miho

### CODE REVIEW

**Comment by vicnate5** [comment]
@achaparro 

Service builder changes
```
     [echo] diff --git a/modules/apps/depot/depot-service/src/main/resources/META-INF/sql/indexes.sql b/modules/apps/depot/depot-service/src/main/resources/META-INF/sql/indexes.sql
     [echo] index 1d6483c462ef..0205131ac863 100644
     [echo] --- a/modules/apps/depot/depot-service/src/main/resources/META-INF/sql/indexes.sql
     [echo] +++ b/modules/apps/depot/depot-service/src/main/resources/META-INF/sql/indexes.sql
     [echo] @@ -1,4 +1,4 @@
     [echo] -create unique index IX_884D6226 on DepotEntry (groupId);
     [echo] +create unique index IX_38B9EE42 on DepotEntry (groupId, companyId);
```

I also want to run the full test suite since this is a big change.

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:close

**Comment by vicnate5** [comment]
@achaparro Some failures that might be related

**PMD**
https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/216683/AXIS_VARIABLE=0,label_exp=!master/testReport/junit/com.liferay.jenkins/Jenkins/test_portal_acceptance_pullrequest_batch_master__AXIS_VARIABLE_0_label_exp__master_pmd_jdk8/

**HSQL**
https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/315113/AXIS_VARIABLE=34,label_exp=!master/testReport/junit/com.liferay.portal.workflow.kaleo.forms.internal.upgrade.v1_0_2.test/UpgradeKaleoProcessTemplateLinkTest/testCreateKaleoProcessLink/

https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/315113/AXIS_VARIABLE=0,label_exp=!master/testReport/junit/com.liferay.account.service.test/AccountRoleLocalServiceTest/testSearchAccountRolesWithPagination/

https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/315113/AXIS_VARIABLE=25,label_exp=!master/testReport/junit/com.liferay.portal.lock.service.test/LockLocalServiceTest/testLock/

https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/315113/AXIS_VARIABLE=25,label_exp=!master/testReport/junit/com.liferay.portal.lock.service.test/LockLocalServiceTest/testMutualExcludeLockingParallel/

**MariaDB/MySQL**
https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/350236/AXIS_VARIABLE=33,label_exp=!master/testReport/junit/com.liferay.portal.upgrade.test/UpgradePrimaryKeyTest/testAddStringColumnAsPrimaryKey/

https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/224751/AXIS_VARIABLE=33,label_exp=!master/testReport/junit/com.liferay.portal.upgrade.test/UpgradePrimaryKeyTest/testAddStringColumnAsPrimaryKey/

**Oracle**
https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/284446/AXIS_VARIABLE=34,label_exp=!master/testReport/junit/com.liferay.portal.workflow.kaleo.forms.internal.upgrade.v1_0_2.test/UpgradeKaleoProcessTemplateLinkTest/testCreateKaleoProcessLink/

**PostgreSQL**
https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/104955/AXIS_VARIABLE=34,label_exp=!master/testReport/junit/com.liferay.portal.workflow.kaleo.forms.internal.upgrade.v1_0_2.test/UpgradeKaleoProcessTemplateLinkTest/testCreateKaleoProcessLink/

**Comment by achaparro** [comment]
Thanks a lot @vicnate5, I will check it right now

**Pull request closed without merging**
