### PR TITLE
LPD-24922 Optimize bundle checksum handling

### PR DESCRIPTION
**Pull request by shuyangzhou**
@victorhcunha please run a startup time compare for this pull.

Also do a cpu profile compare, highlight the difference in "Events -> File -> (all sub items)". This pull is meant to remove many "Open/Read/Close"

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b63deb4403...003ea80c83

**Comment by brianchandotcom** [comment]
@shuyangzhou can we sort:

```
		_fileInstallers.close();

		_checksumRandomAccessFile.close();
```

I left it as is. If sorting doesn't hurt, please send me a PR. Thx.

**Comment by shuyangzhou** [comment]
@brianchandotcom the order matters, it is on purpose.

**Comment by victorhcunha** [comment]
Hi @shuyangzhou !
The results are available: [Time and Profile Compare for LPD-24922](https://docs.google.com/spreadsheets/d/15OvJdthowjgcCzK9MBMUZU2Sd6jjH8ZlGL7QHbRTlVw/edit?usp=sharing)
For now, the available values are from m1console3 (different from m1console2, which runs the daily tests and is currently busy with them). Let me know if you also need the results from m1console2.

**Comment by shuyangzhou** [comment]
@victorhcunha this is fine. I am working on reducing and stabilizing the file related metrics, if they can get to a stable point, we will need to add them to daily monitoring. There will be more pulls about files soon. Thanks!

**Pull request closed without merging**
