### PR TITLE
LRDOCS-4155 Edit Javadoc

### PR DESCRIPTION
**Pull request by codyhoag**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@codyhoag please backport if possible/relevant. Thx

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a3d10fdb5c...f127c6acac

**Comment by brianchandotcom** [comment]
@codyhoag in the future, can you commit with the LPS as well? That way, if the original fix is backported, we know to backport the javadoc too. Thx

**Comment by codyhoag** [comment]
@brianchandotcom sure thing!

**Pull request closed without merging**
