### PR TITLE
Lps 74143

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/809bb64bbf...9a0c21d809

**Comment by brianchandotcom** [comment]
@Preston-Crary I've merged this and backported it. Can you remove any files that need to be deleted? thx.

**Comment by Preston-Crary** [comment]
@brianchandotcom I'm planning on removing all the usages in another ticket see https://issues.liferay.com/browse/LPS-74348

**Pull request closed without merging**
