### PR TITLE
LPS-74994

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by gamerson** [comment]
cc @jbalsas 

Thanks Andrea for the review!

**Comment by gamerson** [comment]
hey @brianchandotcom  could you publish project templates 3.0.3 once you merge this?  We need this new version available for DevCon.  Thanks!

**Comment by gamerson** [comment]
actually hold off perhaps, there are some more changes I will likely need.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4fb1d8c760...b5965278ba

**Comment by brianchandotcom** [comment]
@izaera @Ithildir should presets like this be sorted?

modules/sdk/project-templates-npm-react-portlet/src/main/resources/archetype-resources/.babelrc

```
{
	"presets": ["es2015", "react", "liferay-project"]
}
```

Thx.

**Comment by izaera** [comment]
@brianchandotcom @Ithildir The order is important, because they are applied in the order they are configured. It must be preserved.

**Pull request closed without merging**
