### PR TITLE
7.0.x-qa-29184

### PR DESCRIPTION
**Pull request by ctampoya**
https://issues.liferay.com/browse/LRQA-29184

CC @jpince @brianchiu

### CODE REVIEW

**Comment by ctampoya** [comment]
@brianchandotcom This should fix the poshi-validation errors occurring on ee-7.0.x branch

**Comment by ctampoya** [comment]
Updated pull to remove extra space before end tag.

**Comment by brianchiu** [comment]
I pushed this up to 7.0.x and ee-7.0.x

https://github.com/liferay/liferay-portal/commit/70d0863b75385bcee3093f0b151f4ff714d753ea
https://github.com/liferay/liferay-portal-ee/commit/2769a906e343d6ce2025d63ea566d85a5706686a

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
