### PR TITLE
Lpd 23927

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@victorhcunha please run a before/after compare on cpu profile for `Exceptions -> Group by "Exception Class" -> java.lang.NoSuchMethodException` count, thanks!

CC @rafaprax

**Comment by victorhcunha** [comment]
Sure! I will do it

**Comment by victorhcunha** [comment]
Hi @shuyangzhou !
The results are available: [java.lang.NoSuchMethodException Count](https://docs.google.com/spreadsheets/d/1fMijKcVOn85iVpqa5a0VN6dWDqgFL5Mh_AJiQL24gPo/edit?usp=sharing)
Snapshot files are also available.

**Comment by shuyangzhou** [comment]
Thanks @victorhcunha ! Everything looks right.

**Comment by brianchandotcom** [comment]
@shuyangzhou "spring.jndi.ignore" and "spring.beaninfo.ignore" are real Spring keys. If you google them, it shows up in their code/documentation.

I couldn't find spring.beanfactory.strict.lifecycle.enabled

We should add it to portal.properties

```
##
## Spring
##

````

We have a spring section there too. Please resend. Thx.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/149519

**Pull request closed without merging**
