### PR TITLE
LPS-91476 Avoid NPE with DLFile titles during the upgrade

### PR DESCRIPTION
**Pull request by achaparro**
cc/ @jcampoy

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by brianchandotcom** [comment]
@brianchiu what's up with all the broken upgrade tests? A lot....

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchiu** [comment]
@brianchandotcom thanks for the heads up. Seems we have a bad locator...

**Pull request closed without merging**
