### PR TITLE
LPS-161084 Cover aggregation object field by using integration tests

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/35bf6524a0...f892fabea9

**Comment by MarinhoFeliphe** [comment]
ci:reopen

**Comment by MarinhoFeliphe** [comment]
ci:close

**Pull request closed without merging**
