### PR TITLE
LPS-61680

### PR DESCRIPTION
**Pull request by samuelkong**

### CODE REVIEW

**Comment by samuelkong** [comment]
ci:retest

**Comment by samuelkong** [comment]
ci:retest

**Comment by samuelkong** [comment]
ci:retest

**Comment by samuelkong** [comment]
Don't think CI failures are related to changes. Tests keep failing at different points.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e9935e29e3...671c49f7e3

**Pull request closed without merging**
