### PR TITLE
New reference doc stylesheets

### PR DESCRIPTION
**Pull request by jhinkey**
cc/ @mwilliams2014, @CAustin582, @Ithildir

### CODE REVIEW

**Comment by jhinkey** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2b8e30d77d...639c498ac3

**Comment by brianchandotcom** [comment]
@jhinkey I merged this in, but for

tools/styles/taglibs/stylesheet.css

where did 

BODY and TableHeadingColor come from? Are those standard names or names we came up with?

**Comment by mwilliams2014** [comment]
@brianchandotcom I copied those from the old javadoc.css file.

**Pull request closed without merging**
