### PR TITLE
[See desc] LPS-66213 Add release in missing portlet

### PR DESCRIPTION
**Pull request by sergiogonzalez**
From @adolfopa 

In commit a7f3af0, I created a util class with two constructors that may look a bit weird. That is needed because:

At the point where it is used by the UpgradeWebPluginRelease, the BeanLocator is not initialized (but the services are ready). This means we cannot use DB as in the upgrades, as DBImpl invokes the CounterLocalService methods using the *Util class.
In the UpgradeModules class the DB constructor is used, as I didn't want to make the upgrade depend on a service builder service.
Thanks!

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @adolfopa

**Comment by adolfopa** [comment]
@sergiogonzalez @brianchandotcom Could you please remove the last commit? `MicroblogsStatusUpdatePortlet` inherits from `MicroblogsPortlet` (which has the `Release` dependency). Bnd is choking because we have enabled annotation inheritance, and it's finding a duplicate dependency.

If you prefer me to resend the pr, I'll do so.

Thanks!

**Comment by adolfopa** [comment]
Nevermind. I'll resend without the last commit.

Thanks!

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/40339

**Comment by sergiogonzalez** [comment]
Closing it in favor of https://github.com/brianchandotcom/liferay-portal/pull/40339.
Thanks @adolfopa

**Pull request closed without merging**
