### PR TITLE
LPS-65693 fix the copy bug

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:stop

**Comment by rotty3000** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@rotty3000 yey it worked :)

**Comment by brianchandotcom** [comment]
@shuyangzhou this pull from @rotty3000 seems to work?

**Comment by shuyangzhou** [comment]
This is one verison of it. This one validates all indexes all together. It does work, but that is not what we would expect to happen normally in production mode.

@rotty3000 's the other pull to me https://github.com/shuyangzhou/liferay-portal/pull/2950 still failed. Apprently, when we validate the index file one by one even 2 hours is not enough. We need to make the one by one version working first, before we can do the marketplace integration.

**Comment by rotty3000** [comment]
That scenario is not a good test for the individual validation. I think we
should not rely on it. We should simply add a new scenario to the lpkg test
with a specific case for verifying a single lpkg, just like the marketplace
would attempt.

**Comment by rotty3000** [comment]
@shuyangzhou would that be reasonable?

**Comment by shuyangzhou** [comment]
I guess the real question is, in the real world, when we roll out an upgrade, how many lpkgs in average we will include?

At least on ci I know the 1st lpkg took about 7mins, and we have 21 of them. So if they all take about 7mins, with the current solution, if we roll out 5 lpkgs in an upgrade, that will be over 30mins, which is obviously too much.

The goal will be to make the upgrade time acceptable.

**Comment by rotty3000** [comment]
I don't think we need for it to operate that way.

The upgrade could be indexed all together just like our simulation with the
new code is doing.

a) index all the new lpkg files
b) validate everything is ok

Would that be reasonable?

So regardless of the number of lpkg files, we still only validate once with
everything together.


On Wed, May 25, 2016 at 10:38 AM, Shuyang Zhou <notifications@github.com>
wrote:

> I guess the real question is, in the real world, when we roll out an
> upgrade, how many lpkgs in average we will include?
>
> At least on ci I know the 1st lpkg took about 7mins, and we have 21 of
> them. So if they all take about 7mins, with the current solution, if we
> roll out 5 lpkgs in an upgrade, that will be over 30mins, which is
> obviously too much.
>
> The goal will be to make the upgrade time acceptable.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/40154#issuecomment-221596638>
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by shuyangzhou** [comment]
Ok, that could work for fixpack bulk upgrade. As long as we don't copy around the index files before they all pass the validation.

But we still need to think about marketplace, I think it is possible to people to click several lpkgs for install/ upgrade, then what do we do? Can we still validate them all together?

I think the biggest question is, why the performance diff is so significant? Validating eveything together is 2mins. Validating 1 is 7mins. I think we need to figure out what exactly is happening here to know sure we are doing the right things.

**Comment by rotty3000** [comment]
Yup, I understand and I'm writing a simulation for the scenario with a
single lpkg now. I hope to find the reason it takes so long.

On Wed, May 25, 2016 at 11:13 AM, Shuyang Zhou <notifications@github.com>
wrote:

> Ok, that could work for fixpack bulk upgrade. As long as we don't copy
> around the index files before they all pass the validation.
>
> But we still need to think about marketplace, I think it is possible to
> people to click several lpkgs for install/ upgrade, then what do we do? Can
> we still validate them all together?
>
> I think the biggest question is, why the performance diff is so
> significant? Validating eveything together is 2mins. Validating 1 is 7mins.
> I think we need to figure out what exactly is happening here to know sure
> we are doing the right things.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/40154#issuecomment-221607297>
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by shuyangzhou** [comment]
Oh, one more thing. When we upgrade lpkg, the old file simply got overwritten. We don't explicitly uninstall the old one. And the new one will have higher version number.

In that case, what will happen to the old index file? Who is going to remove it? (I assume you put version info in the file name, right? So it won't be overwritten in the way lpkg would be)

And we do allow user to explicitly uninstall a lpkg too, do we already have the logic to remove the corresponding index file?

**Comment by rotty3000** [comment]
it's too bad the index file isn't inside the lpkg file...

we will make sure the index is removed

On Wed, May 25, 2016 at 11:53 AM, Shuyang Zhou <notifications@github.com>
wrote:

> Oh, one more thing. When we upgrade lpkg, the old file simply got
> overwritten. We don't explicitly uninstall the old one. And the new one
> will have higher version number.
>
> In that case, what will happen to the old index file? Who is going to
> remove it? (I assume you put version info in the file name, right? So it
> won't be overwritten in the way lpkg would be)
>
> And we do allow user to explicitly uninstall a lpkg too, do we already
> have the logic to remove the corresponding index file?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/40154#issuecomment-221617278>
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by shuyangzhou** [comment]
I am always in favour of holding index info in memory. But that requires the reconstruction is super cheap.

**Comment by brianchandotcom** [comment]
@rotty3000 I can ask @lionah to add the index inside the LPKG?

**Comment by rotty3000** [comment]
give me a little bit, I am very close to reducing the validation time down to ~20 seconds per lpkg.

**Comment by brianchandotcom** [comment]
Going to close this pull since @rotty3000 will send a new one.

**Pull request closed without merging**
