### PR TITLE
LPS-182579 Add integration test to validate the related object entries (custom and system) returned by using nestedFields query parameter

### PR DESCRIPTION
**Pull request by ccorreagg**
Forwarded from: https://github.com/brianchandotcom/liferay-portal/pull/134477

---

This PR contains the integration test to validate:

- Related Custom Object Entries related to a Custom Object by using `nestedFields` and `nestedFieldsDepth` query parameters.
- Related System Object Entries related to a Custom Object by using `nestedFields` and `nestedFieldsDepth` query parameters (under the FF `LPS-165819`).

Furthermore, two classes have been added:

- `ObjectFieldTestUtil`: Test Util class to manage custom object fields
- `UserAccountTestUtil`: Test Util class to generate random UserAccount and to manage the creation and update of a UserAccount

---

How to launch the tests:

- `cd modules/apps/object/object-rest-test`
- `gw tI --tests ObjectEntryRelatedObjectsResourceTest`
- `gw tI --tests ObjectEntryResourceTest`

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/033ba56cc9...7a9d68004c

**Comment by brianchandotcom** [comment]
@ccorreagg see changes in my origin. Specifically, I'm not sure if 25d763cabf37843b61714dd53604029cb6403264 is right

**Comment by ccorreagg** [comment]
Thanks! I checked with QA and the commit is right! Nothing else to do

**Pull request closed without merging**
