### PR TITLE
LPS-82668

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:test

**Comment by hhuijser** [comment]
@brianchandotcom, let the test finish, please!!

**Comment by brianchandotcom** [comment]
@hhuijser I assume you will SF enforce this, because there are probably a few that were added in between pulls.

We also have some complex ones that will grab the portal one too and a few others, those should no longer need the portal one, so you should make your query look for how we looked for the portal resource bundle and fix those as well.

Merged. Thx.

**Comment by hhuijser** [comment]
@brianchandotcom, yup this is work in progress

**Pull request closed without merging**
