### PR TITLE
LPS-76272

### PR DESCRIPTION
**Pull request by Ithildir**
Hi,
@michaelhashimoto will take care of removing `poshi.toggle` and `test.properties` if they are not needed.

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@petershin there's a conflict here with your changes, can you take this pull and send it back to me? Thx.

**Comment by Ithildir** [comment]
Hi @brianchandotcom,
This pull is from me, not from @petershin 😊 I'll take care of it!

**Comment by Ithildir** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/54644.

**Pull request closed without merging**
