### PR TITLE
COMMERCE-4766 ForceSync for Product Specification Options Portlet

### PR DESCRIPTION
**Pull request by dsitu**
Sending this and a few other PRs manually so we dont have to wait on CI since its failing from unrelated test.
Original PR: https://github.com/liferay-commerce/liferay-portal/pull/179

### CODE REVIEW

**Comment by dsitu** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f4cbe0f469...70a1336244

**Comment by brianchandotcom** [comment]
@gianmarcobrunialti @dsitu don't you have to do a try / finally?

@shuyangzhou this smells fishy to me, can you take a look and possibly send me a fix?

@marco-leo fyi

**Comment by shuyangzhou** [comment]
@gianmarcobrunialti what are you trying to sync? The search indexing or there is some db persistence logic is async in this request processing?
I tried to follow the ticket steps, I don't see the problem on clean master.
Please provide details about what's the problem you are trying to solve. In general, you should not use that ProxyModeThreadLocal in normal production code, it is mainly for framework code usage.

**Comment by brianchandotcom** [comment]
@dsitu can you work with you @shuyangzhou and @gianmarcobrunialti about this issue. This is a deeper problem.

@marco-leo we need a true fix. Please coordinate.

**Comment by marco-leo** [comment]
Hey @shuyangzhou , this is connected to PTR-1919. After that action is performed, the UI try to reload the data set updated in a new call, and in that call the data is still not updated. As those are using search filters, we are forced to go to the indexer.  This workaround wants to ensure that the indexer is in sync.  We know is not the right fix, and we are waiting for guidance from search team. I am open to talk on this topic.

**Comment by shuyangzhou** [comment]
@marco-leo ok, that's what I guessed why you guys want this. So essentially you want to have "searchContext.setCommitImmediately(true);" for your indexing, because you need to see the changes right after the changes are made, right? Search must provide you a way to set it cleanly. "ProxyModeThreadLocal.isForceSync()" is the wrong choice here, because it is not only used by search indexing, many other async logic depends on it too, you don't want to change them in most cases.

**Comment by marco-leo** [comment]
@shuyangzhou agree, we opened that PTR for it. If you agree we can keep this solution in the while they provide a better way, this code is in admin portlet, so we don’t expect many requests on it. Is it ok for you?

**Comment by shuyangzhou** [comment]
@marco-leo if you are under release pressure, I don't want to be in your way. Just some one needs to be on top of this to remove this ProxyModeThreadLocal usage in the near future. If we don't get this solved properly, this weird usage will eventually be buried up, and then some day later it will bite us back in an unexpected way.

**Comment by marco-leo** [comment]
@shuyangzhou yes, as soon as we get the proper way to do it from search team we will change it, I will copy this conevrsation in the PRT ticket.  Thanks a lot for your help

**Pull request closed without merging**
