### PR TITLE
LPS-99625 Change operation to change the experiment status to POST and use a JSON body

### PR DESCRIPTION
**Pull request by dgarciasarai**
See https://github.com/dgarciasarai/liferay-portal/pull/93

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/890b15fd3e...62fa1e8ffe

**Comment by brianchandotcom** [comment]
@nhpatt is this acceptable:

```
        Status:
            properties:
                status:
                    type: string
            type: object
```

Where the model and one of the fields is the same thing? Do we do this else where?

I merged this @dgarciasarai but can you double check with @nhpatt?

**Comment by dgarciasarai** [comment]
Yes, we can double check that :)
Thanks @brianchandotcom

**Comment by nhpatt** [comment]
We have another similar use case, bulk-rest that has a Status object that returns actionInProgress. We could avoid the entity in the OpenAPI all together by defining it inline in the path, the generator would/should generate similar code as it is now, an entity with the name of the property.

**Pull request closed without merging**
