### PR TITLE
LPS-57562 Display notifications in product menu [PING PONG]

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @jkappler

**Comment by juliocamarero** [comment]
@brianchandotcom all the functional tests are passing!!! Only all the integration tests are failing for an external reason to this pull request. thank you!!

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by jkappler** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a59ea6d46a...4fe296cd6a

**Pull request closed without merging**
