### PR TITLE
LPS-91859 Add create and update FormRecord

### PR DESCRIPTION
**Pull request by victorlaerte**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jpince here's a hash for you :)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2b5700b727...2f4b552917

**Comment by brianchandotcom** [comment]
@victorlaerte see my changes in upstream. Also, 6516c96203a5076e4fe9a0dfd88daca47f511ba8 should be 2 commits (one for the YAML change and one for regeneration)

Thx.

**Comment by victorlaerte** [comment]
@brianchandotcom I got it. Thanks for the feedback.

**Pull request closed without merging**
