### PR TITLE
LPS-90750 Add layout page template entry after transaction commit to avoid problems when transaction cache is disabled

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@shuyangzhou I merged this, but I have a feeling it may be wrong. Can you take a quick look at LPS-90750, just one small commit.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/68588

**Comment by brianchandotcom** [comment]
@pavel-savinov @jkappler see shuyang's fix in https://github.com/brianchandotcom/liferay-portal/pull/68588

**Pull request closed without merging**
