### PR TITLE
LPS-84351 Fix syntax error

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test

**Comment by jpince** [comment]
ci:test:sf

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/93195ae165...9fc6f02d53

**Comment by brianchandotcom** [comment]
@julien see my changes in upstream. Thx.

**Pull request closed without merging**
