### PR TITLE
LPS-60779 - rename trash taglibs

### PR DESCRIPTION
**Pull request by mjbradford89**
Hey Brian,

Attached are the changes for renaming `liferay-trash:trash-undo` and `liferay-trash:trash-empty` taglibs to just `liferay-trash:*`.

There was also one instance where I found a file still using the liferay-ui:trash namespace, so I updated that one as well.

Please let me know if there are any issues

Thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/67f5dd6f5f...04c1deed99

**Comment by brianchandotcom** [comment]
@mjbradford89 can you rename TrashUndoTag.java as well as TrashEmptyTag.java

Thx. Please send a follow up pull.

**Comment by brianchiu** [comment]
@mjbradford89 
We've rolled this back because we think it may have caused the calendar frontend test failures you see in the result.

Can you resend this to Brian Chan?

CC @brianchandotcom

**Comment by mjbradford89** [comment]
@brianchiu That's strange.  It doesn't look like any trash tags are even used by the calendar.

@brianchandotcom Sure, I will include the rename of those files with the rest when I resend this one.

Thanks!

**Comment by mjbradford89** [comment]
new pull submitted here: https://github.com/brianchandotcom/liferay-portal/pull/33665

**Pull request closed without merging**
