### PR TITLE
LPS-65432 Uses last version of control menu api

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
cc: @juliocamarero

**Comment by ealonso** [comment]
ci:retest

**Comment by evannagayama** [comment]
@kenjiheigel portal instance setup issue?

**Comment by kenjiheigel** [comment]
@evannagayama, appears to be so. I've seen this fail from time to time.. but I haven't been able to figure out why at this point. I'm going to update the set up macro soon so it can give us more information when it fails like this.

**Comment by brianchandotcom** [comment]
Ok. I'll merge this.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8f4e3b0c66...47139d51c2

**Comment by brianchandotcom** [comment]
Very nice @ealonso

**Pull request closed without merging**
