### PR TITLE
COMMERCE-548 Use the new design for the component icons

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
https://issues.liferay.com/browse/COMMERCE-548

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
@michaelhashimoto @yichenroy @kenjiheigel CI error
`build-common.xml:2233: Property 'TEST_CLASS_GROUP_0' is not defined.`

**Comment by jpince** [comment]
occurs in both modules-int and modules-unit in this pull

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@jpince can't be related.. it's just changing icons...

We have another issue going on, please talk to @pyoo47 thx

**Comment by yichenroy** [comment]
@jpince 
The issue is not reproduced when it was ran here (only tested the two failing batches to reduce load): https://github.com/yichenroy/liferay-portal/pull/73 
The most recent liferay-jenkins-ee changes may have remedied the problem, let us know if similar error occurs again.

**Pull request closed without merging**
