### PR TITLE
LPS-52963 Fix ClusterExecutorImpl, forgot to set thread local to avoid c...

### PR DESCRIPTION
**Pull request by shuyangzhou**
...ircular invoking.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f55ff591ae...695d6d37cb

**Comment by brianchandotcom** [comment]
@tinatian do we have a test for this? it shouldn't be green if it was broken before. Thx.

**Comment by brianchandotcom** [comment]
Nvm... I see it was just a try catch.. @tinatian

**Comment by shuyangzhou** [comment]
I already asked @tinatian to update the unit test to catch this case. She should send it soon.

**Pull request closed without merging**
