### PR TITLE
LPS-108921 Select web content doesn't display Scheduled WC article in WCD portlet

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
@ealonso, @adolfopa

**Comment by jkappler** [comment]
@brianchandotcom, issues not related to this PR

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a901ae046f...5c4d9f72c2

**Comment by brianchandotcom** [comment]
@adolfopa @jkappler see 5c4d9f72c2fe9cb23bfd2a8db9d7b4be9e3c96cf

**Pull request closed without merging**
