### PR TITLE
LPS-70426 Add resource command to retrieve a list of roles

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@marcellustavares

**Comment by lesliewong92** [comment]
Pull request triggered on a bad server.

**Comment by lesliewong92** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3fd4106851...289f962eeb

**Comment by brianchandotcom** [comment]
@leoadb I made some changes in upstream.

**Comment by brianchandotcom** [comment]
@leoadb please review my renames in upstream. Thx.

**Pull request closed without merging**
