### PR TITLE
LPS-79882 VerifyGroup Refactor

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@shuyangzhou is it OK to use PortalUtil.getClassNameId inside portal-impl/src/com/liferay/portal/upgrade/v6_2_0/UpgradeGroup.java

I assume we should not use Portal reference since it's not available (in any case, SF didn't complain)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/10289a7da0...35a00bbe3b

**Comment by shuyangzhou** [comment]
@brianchandotcom DBUpgrader initializes the spring context first, which is setting PortalImpl into PortalUtil from util-spring.xml. This should be fine.

**Pull request closed without merging**
