### PR TITLE
LPS-72999

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-72999.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:reopen

**Comment by brunobasto** [comment]
Hey @jonmak08, not sure if this is gonna make Poshi tests fail, but we might need to update here: https://github.com/brunobasto/liferay-portal/blob/master/modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/js/custom_fields.js#L1179

I think this should refer to DatePickerDeprecated instead of DatePicker. The new DatePicker does not have the .render() method as far as I know.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e21deb4041...71f15d8d76

**Comment by jonmak08** [comment]
Hey @brunobasto,

I have sent the additional fix at https://github.com/brianchandotcom/liferay-portal/pull/52836.

Please let me know if you have any questions. Thanks!

**Pull request closed without merging**
