### PR TITLE
OAUTH2-111 Update JavaDoc

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
ci:test

**Comment by csierra** [comment]
ci:retest

**Comment by topolik** [comment]
ci:reopen

This pull contains no unique failures.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9b30a65f04...8ccf13a134

**Pull request closed without merging**
