### PR TITLE
LRIS-25643

### PR DESCRIPTION
**Pull request by lionah**

### CODE REVIEW

**Comment by lionah** [comment]
ci:reopen

**Comment by lionah** [comment]
@jpince check pls?

**Comment by jpince** [comment]
@lionah @suprithas 
```
java.io.IOException: Start of bundle with id 630 failed with message: Could not resolve module: com.liferay.portal.security.wedeploy.auth.test [630]
  Unresolved requirement: Import-Package: com.liferay.portal.security.wedeploy.auth.exception
```
click on any modules-integration batch > click on failing test (`com.liferay`...`WeDeployAuthAppPersistenceTest.classMethod`) > error message is displayed. you can click on "console log" on the left-hand side for the extended log.

If the integration batch failures `OrganizationLocalServiceTest.testGetNoAssetOrganizations` are the same as the last pull, then those need to be resolved as well (haven't seen these failing elsewhere). You'd have to contact the author/recent contributor to the test if you have any specific questions.

tck failure looks like a fluke.

**Comment by jpince** [comment]
ci:close

**Comment by lionah** [comment]
ci:reopen

**Comment by lionah** [comment]
There has to be something else wrong then. I've loaded the modules and I'm not seeing that missing dependency issue.

**Pull request closed without merging**
