### PR TITLE
LPS-83135 Using null for modules with no tables

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by jpince** [comment]
@adolfopa @4lejandrito please look into this failure?
```
     [exec] com.liferay.deprecated.modules.upgrade.test.DeprecatedModulesUpgradeTest > testDeprecatedModulesInvitation FAILED
     [exec]     org.springframework.dao.DataIntegrityViolationException: Could not execute JDBC batch update; SQL [insert into Release_ (mvccVersion, createDate, modifiedDate, servletContextName, schemaVersion, buildNumber, buildDate, verified, state_, testString, releaseId) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
...
     [exec]             Caused by:
     [exec]             java.sql.BatchUpdateException: Duplicate entry 'com.liferay.wysiwyg.web' for key 'IX_8BD6BCA7'
...
     [exec]                 Caused by:
     [exec]                 java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'com.liferay.wysiwyg.web' for key 'IX_8BD6BCA7'
```

cc/ @yvonnehan

**Comment by 4lejandrito** [comment]
I will, thanks!!

**Comment by jpince** [comment]
cc/ @hanlf

**Comment by jpince** [comment]
cc/ @vicnate5 @timpak

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/75062.

**Pull request closed without merging**
