### PR TITLE
LPS-107564 Match with other test classes

### PR DESCRIPTION
**Pull request by darquesdev**
@ealonso @dgarciasarai @andresfulla

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:stable

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f14c1f8d21...4301b9fd67

**Pull request closed without merging**
