### PR TITLE
LRIS-30978 License validation for 7.1

### PR DESCRIPTION
**Pull request by wesleygong**
cc @amosfong 
"Hey Brian,

- Processor cores are being added to license.xml validation
- This is the same method the LCS portlet uses to get the processor core count.
- It uses a pretty ugly dependency "sigar" (which looks like a dead project) and requires loading a dll/so JNI library depending on which OS you're on. I believe this may only be needed for accurate CPU counts for windows (and possibly solaris) on docker environments.
- I unload the JNI library after I'm done so LCS portlet can use Sigar for other stuff because a JNI library can only be loaded by one classloader.
"

Please backport to 7.1 thanks!

### CODE REVIEW

**Comment by wesleygong** [comment]
ci:test

**Comment by wesleygong** [comment]
@amosfong looks like junit test failure during setup.  Whoever gets to it first on monday can look into it: https://github.com/liferay/liferay-portal/blob/master/portal-impl/test/unit/com/liferay/portal/util/BaseLicenseUtilTestCase.java#L45

**Comment by brianchandotcom** [comment]
Please fix unit test. Thx @wesleygong @amosfong

**Comment by amosfong** [comment]
@wesleygong I'll take a look

**Comment by amosfong** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/59589

**Pull request closed without merging**
