### PR TITLE
LPS-86390 SF

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by jpince** [comment]
ci:close
@4lejandrito this failure looks related, can you please look into it? It's in the lpkg batch, so you won't be able to reproduce it locally.
```
    [junit] 10:10:54,268 WARN  [liferay/document_library_raw_metadata_processor-1][RawMetadataProcessorMessageListener:38] Unable to save metadata for file version 37308
    [junit] java.lang.NullPointerException
    [junit] 	at com.liferay.portlet.documentlibrary.util.RawMetadataProcessorImpl.saveMetadata(RawMetadataProcessorImpl.java:188)
    [junit] 	at com.liferay.document.library.kernel.util.RawMetadataProcessorUtil.saveMetadata(RawMetadataProcessorUtil.java:113)
    [junit] 	at com.liferay.portlet.documentlibrary.messaging.RawMetadataProcessorMessageListener.doReceive(RawMetadataProcessorMessageListener.java:34)
```

**Comment by jpince** [comment]
ci:test:relevant retesting to make sure failure is consistent

**Comment by jpince** [comment]
@4lejandrito @austinchiang I see a similar lpkg-controller failure in [this pull](https://github.com/brianchandotcom/liferay-portal/pull/64559#issuecomment-433241923). So maybe this is an inconsistent issue? Can you please look into this?
```
junit.framework.AssertionFailedError: 
Unable to save metadata for file version 36622
java.lang.NullPointerException
	at com.liferay.portlet.documentlibrary.util.RawMetadataProcessorImpl.saveMetadata(RawMetadataProcessorImpl.java:188)
	at com.liferay.document.library.kernel.util.RawMetadataProcessorUtil.saveMetadata(RawMetadataProcessorUtil.java:113)
	at com.liferay.portlet.documentlibrary.messaging.RawMetadataProcessorMessageListener.doReceive(RawMetadataProcessorMessageListener.java:34)
	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:26)
	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:74)
	at com.liferay.portal.kernel.messaging.SerialDestination$1.run(SerialDestination.java:58)
	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask._runTask(ThreadPoolExecutor.java:752)
	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask.run(ThreadPoolExecutor.java:664)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by brianchandotcom** [comment]
@4lejandrito besides issues pointed out by @jpince 

I'm also confused by

```
	private boolean _isExpandoUpdated(
		DLFileVersion previousDLFileVersion, DLFileVersion nextDLFileVersion) {

		ExpandoBridge lastExpandoBridge =
			previousDLFileVersion.getExpandoBridge();
		ExpandoBridge latestExpandoBridge =
			nextDLFileVersion.getExpandoBridge();

		Map<String, Serializable> lastAttributes =
			lastExpandoBridge.getAttributes();
		Map<String, Serializable> latestAttributes =
			latestExpandoBridge.getAttributes();

		if (!lastAttributes.equals(latestAttributes)) {
			return true;
		}

		return false;
	}

```

We use previous/next, last, latest very mixed. Can we come up with consistent names please.

**Pull request closed without merging**
