### PR TITLE
LPS-91291 Use experiences associated with the published layout when exists

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
FYI @epgarcia @darquesdev https://github.com/brianchandotcom/liferay-portal/pull/69378/commits/ec723358d7254622e3c5bcfa0c0613b96e2e3e18

**Comment by jkappler** [comment]
ci:close

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
