### PR TITLE
Lps 75733

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 why do we get random failures like this? What does this mean?

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/98bba70430...98bba70430

**Pull request closed without merging**
