### PR TITLE
LPS-92272 Hide select box in toolbar

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
@brianchiu, @kyle-miho, this is a new module....just in case we see some failing tests here...

**Comment by brianchiu** [comment]
@brianchandotcom 
ci test relevant tests are upgrades test failures, which are due to [LPS-92283](https://issues.liferay.com/browse/LPS-92283). They are unrelated to this pull.

cc @jkappler @kyle-miho

**Comment by brianchandotcom** [comment]
Why is modules/apps/layout/layout-portlets-web/bnd.bnd 3.0.0?

I also find the usage of the word "Portlet" and the word "Portlets" inconsistent.

LayoutPortletsPortlet vs. PortletDisplayNameComparator is this right? It may be.

I"m not sure... please resend.

**Comment by JorgeFerrer** [comment]
Hey Brian, we will review all usages of the terms "Portlet" and "Portlets" to be sure it's correct.

I believe that the specific example that you mention is indeed correct. We are using the plural in LayoutPortletsPortlet because this is a portlet to manage many other portlets. On the other side PortletDisplayNameComparator is consistent with all of our other comparators which use the singular form in their name such as PortletNameComparator, ArticleDisplayNameComparator, TeamNameComparator, etc.

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Resent as https://github.com/brianchandotcom/liferay-portal/pull/69798

**Pull request closed without merging**
