### PR TITLE
LPS-103475 Update central requirements tests

### PR DESCRIPTION
**Pull request by petershin**
@nikki-pru

### CODE REVIEW

**Comment by jpince** [comment]
@petershin should the class `isInDXPModulesDir` also be available to other tests? I feel like this would be helpful?

**Comment by petershin** [comment]
@jpince - Which tests are you referring to?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/266a9f076e...18b81d649c

**Comment by jpince** [comment]
@petershin not sure exactly which ones, but I feel like there are tests that need to know whether it's a CE or DXP build. And maybe even for CI Infrastructure. I will ask QA.

**Pull request closed without merging**
