### PR TITLE
master-qa-22605

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-22605

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by brianchiu** [comment]
@brianchandotcom 

I've talked this over with Kenji. Don't merge this pull (which adds the upgrade tests back into the PR tester). We've found that the upgrade process itself has become flaky at some point today. I was also able to reproduce this locally but not consistently. But it seems to happen on average 1 out of every 3 or so times. But we need some time to investigate this.

This is happening during the upgrade process:
```
     [java] 01:40:43,086 INFO  [pool-4-thread-19][UpgradeCompanyId:99] Adding column companyId to table RatingsStats
     [java] 01:40:43,086 INFO  [pool-4-thread-18][UpgradeCompanyId:99] Adding column companyId to table PortletPreferences
     [java] 01:40:43,086 INFO  [pool-4-thread-17][UpgradeCompanyId:99] Adding column companyId to table PasswordTracker
     [java] 01:40:43,086 INFO  [pool-4-thread-31][UpgradeCompanyId:99] Adding column companyId to table UserTrackerPath
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.upgrade.UpgradeException: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 18
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:88)
     [java] 	at com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil._upgradeProcess(UpgradeProcessUtil.java:184)
     [java] 	at com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil.upgradeProcess(UpgradeProcessUtil.java:152)
     [java] 	at com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil.upgradeProcess(UpgradeProcessUtil.java:134)
     [java] 	at com.liferay.portal.events.StartupHelper.upgradeProcess(StartupHelper.java:164)
     [java] 	at com.liferay.portal.events.StartupHelperUtil.upgradeProcess(StartupHelperUtil.java:81)
     [java] 	at com.liferay.portal.tools.DBUpgrader.upgrade(DBUpgrader.java:147)
     [java] 	at com.liferay.portal.tools.DBUpgrader.main(DBUpgrader.java:67)
     [java] Caused by: com.liferay.portal.kernel.upgrade.UpgradeException: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 18
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:88)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:112)
     [java] 	at com.liferay.portal.upgrade.UpgradeProcess_7_0_0.doUpgrade(UpgradeProcess_7_0_0.java:73)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:85)
     [java] 	... 7 more
     [java] Caused by: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 18
     [java] 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
     [java] 	at java.util.concurrent.FutureTask.get(FutureTask.java:188)
     [java] 	at com.liferay.portal.upgrade.util.UpgradeCompanyId.doUpgrade(UpgradeCompanyId.java:63)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:85)
     [java] 	... 10 more
     [java] Caused by: java.lang.ArrayIndexOutOfBoundsException: 18
     [java] 	at com.zaxxer.hikari.util.FastList.remove(FastList.java:129)
     [java] 	at com.zaxxer.hikari.pool.ProxyConnection.untrackStatement(ProxyConnection.java:168)
     [java] 	at com.zaxxer.hikari.pool.ProxyStatement.close(ProxyStatement.java:73)
     [java] 	at com.liferay.portal.upgrade.util.UpgradeCompanyId$TableUpdater.getCompanyIds(UpgradeCompanyId.java:131)
     [java] 	at com.liferay.portal.upgrade.util.UpgradeCompanyId$TableUpdater.getSelectSQL(UpgradeCompanyId.java:140)
     [java] 	at com.liferay.portal.upgrade.util.UpgradeCompanyId$TableUpdater.getUpdateSQL(UpgradeCompanyId.java:178)
     [java] 	at com.liferay.portal.upgrade.util.UpgradeCompanyId$TableUpdater.update(UpgradeCompanyId.java:115)
     [java] 	at com.liferay.portal.upgrade.util.UpgradeCompanyId$TableUpdater.call(UpgradeCompanyId.java:104)
     [java] 	at com.liferay.portal.upgrade.util.UpgradeCompanyId$TableUpdater.call(UpgradeCompanyId.java:73)
     [java] 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] 01:40:45,202 INFO  [main][UpgradeProcess:94] Completed upgrade process com.liferay.portal.upgrade.v7_0_0.UpgradeCompanyId in 2128ms
     [java] 01:40:45,202 INFO  [main][UpgradeProcess:94] Completed upgrade process com.liferay.portal.upgrade.UpgradeProcess_7_0_0 in 11917ms
     [java] Java Result: 1
```

CC @kenjiheigel @jhendley

**Comment by brianchandotcom** [comment]
@kenjiheigel please resend based on comment by @brianchiu thx.

**Pull request closed without merging**
