### PR TITLE
LPS-73286 CAPTCHA does not display when creating account

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @JorgeFerrer @tomwang2011

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:reopen

**Comment by pei-jung** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d22df55d8b...3c57f2523c

**Pull request closed without merging**
