### PR TITLE
LPS-106285 Regenerate service

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:stable

**Comment by ealonso** [comment]
cc: @pavel-savinov

**Comment by ealonso** [comment]
ci:reopen

**Comment by ealonso** [comment]
ci:test:stable

**Comment by ealonso** [comment]
ci:test:stable

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6755788479...187ae73b51

**Comment by brianchandotcom** [comment]
@ealonso @pavel-savinov I had to revert this.. causing stable to not sync. See Ci errors here as well.

**Pull request closed without merging**
