### PR TITLE
LPS-59709 Redirect loop when signing in using action attribute url

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d6856d8668...1fb51bd1a7

**Comment by brianchandotcom** [comment]
So we're ignoring all last paths that are actions now? I suppose that makes sense.

**Comment by brianchandotcom** [comment]
@jonathanmccann see my comment. Thx.

**Comment by jonathanmccann** [comment]
@brianchandotcom Yup, that's it.

**Pull request closed without merging**
