### PR TITLE
LPS-93101 Update asset url separators

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @brianchiu, @kyle-miho

**Comment by brianchandotcom** [comment]
@ealonso can you email me a sample of the new URLs?

I'm not fond of /b/ /d/ /wc/ because it hides so much. But you may have a different view and a reason for wanting to keep it short.

Please email me the new list and tell me why you want it so short. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b9cb3970fa...251e5e828b

**Comment by brianchandotcom** [comment]
@jkappler see minor changes in upstream.

**Pull request closed without merging**
