### PR TITLE
LPS-161451

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:reopen

**Comment by victorg1991** [comment]
test failures are not related

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f812288aff...3a72fcdfe3

**Comment by brianchandotcom** [comment]
@victorg1991 just 0305fc78bfdc2cfabaca0bcbe21ddd7e3a4a5217 fyi

**Pull request closed without merging**
