### PR TITLE
LPS-67080 Web Content missing after upgrade.

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:/ @juliocamarero

**Comment by jkappler** [comment]
cc:/ @Ithildir

**Comment by vicnate5** [comment]
ci:retest

**Comment by Ithildir** [comment]
Thank you @jkappler! My fault, that string totally slipped out, and the CI tests didn't catch the problem :disappointed:

**Comment by vicnate5** [comment]
@Ithildir The CI did show this regression on the original pulls (https://github.com/Ithildir/liferay-portal/pull/440 and https://github.com/brianchandotcom/liferay-portal/pull/41426). I could show you how I was able to see this on the CI if that would help in the future.

**Comment by vicnate5** [comment]
@brianchandotcom From poshi test standpoint, this looks good to merge.

**Comment by Ithildir** [comment]
Oh, I guess it's this:

```
[exec] Caused by: java.lang.NullPointerException
     [exec] 	at java.io.Reader.<init>(Reader.java:78)
     [exec] 	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
     [exec] 	at com.liferay.portal.kernel.util.StringUtil.read(StringUtil.java:2236)
     [exec] 	at com.liferay.journal.internal.upgrade.v0_0_4.UpgradeSchema.doUpgrade(UpgradeSchema.java:30)
     [exec] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:88)
     [exec] 	... 95 more
```

My bad, sorry! :disappointed:

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b0976173c2...0644cbfead

**Comment by brianchandotcom** [comment]
@jkappler see 909825f9f4852ceadecc49765972a005ce450d89

Thx.

**Pull request closed without merging**
