### PR TITLE
LPD-15321 Adapt sample Custom Element 1 to support the new caching mechanism

### PR DESCRIPTION
**Pull request by bryceosterhaus**
resent and reviewed from https://github.com/brianchandotcom/liferay-portal/pull/147150

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:reopen

**Comment by bryceosterhaus** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/aa0c44bd3f...157c5df16a

**Comment by brianchandotcom** [comment]
@izaera @bryceosterhaus the file workspaces/liferay-sample-workspace/README.markdown

```
- *liferay-sample-custom-element-1*

	A custom element can be self contained (i.e. does not depend on any external packages).
```

is this still true?

**Comment by izaera** [comment]
@brianchandotcom Yes it is. We just changed the way it is built, not how it depends on external libraries during runtime. 

The fact that it needs `devDependencies` has nothing to do with the fact that it `does not depend on any external packages` because that's referring to, for example, `sample-custom-element-4` using `react` from portal:

image

whereas `sample-custom-element-1` does not use anything that comes from outside.

**Pull request closed without merging**
