### PR TITLE
LPS-48156 Introduce ConfigurationException class

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @JorgeFerrer @natecavanaugh

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pei-jung this is too big too. The exception should be broken down for each one. also has SF issue. Please resend. Thx.

**Pull request closed without merging**
