### PR TITLE
LRQA-42130 | master

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-42130

Fixes `PortalLogAssertorTest` failures for the following integration tests:
- com.liferay.oauth2.provider.client.test.TokenExpeditionTest
- com.liferay.oauth2.provider.client.test.NarrowDownScopeClientTest
- com.liferay.oauth2.provider.client.test.GrantedFlowsTest
- com.liferay.oauth2.provider.client.test.GrantAuthorizationCodePKCEKillSwitchTest
- com.liferay.oauth2.provider.client.test.GrantAuthorizationCodeKillSwitchTest

Passes testing in https://github.com/xbrianlee/liferay-portal/pull/224#issuecomment-402199853.

### CODE REVIEW

**Comment by xbrianlee** [comment]
cc/ @csierra @jpince

**Comment by jpince** [comment]
@xbrianlee thanks!

**Comment by csierra** [comment]
thanks @xbrianlee 
/cc @topolik

**Comment by brianchandotcom** [comment]
Why don't we always use this log4j setting?

**Pull request closed without merging**
