### PR TITLE
LPS-74128 Fix registration of language ResourceBundles that was causing LanguageFilter not to find the correct language properties.

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:reopen

**Comment by izaera** [comment]
ci:retest

**Comment by izaera** [comment]
Can anyone explain why this PR is failing? I don't know what's going on: I get different failures each time...

**Comment by brianchandotcom** [comment]
ci:stop (@izaera, we had a broken test in upstream with the lpkg-release) that is now fixed.

**Comment by brianchandotcom** [comment]
@izaera can you rename

StringBundler filterString

to

StringBundler filterSB

and can you also sort the logic in here that can be sorted

```
				filterSB.append("(&");
				filterSB.append("(|");
				filterSB.append("(bundle.symbolic.name=");
				filterSB.append(bundle.getSymbolicName());
				filterSB.append(")");
				filterSB.append("(&");
				filterSB.append("(servlet.context.name=");
				filterSB.append(contextName);
				filterSB.append(")");
				filterSB.append("(service.bundleid=0)");
				filterSB.append(")");
				filterSB.append(")");
				filterSB.append("(objectClass=");
				filterSB.append(ResourceBundleLoader.class.getName());
				filterSB.append(")");
				filterSB.append("(resource.bundle.base.name=*)");
				filterSB.append(")");
```

Thx.

**Pull request closed without merging**
