### PR TITLE
maste-qa-55212

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LRQA-55212

This is for master only.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d5dcd10102...e01e52dbcf

**Comment by brianchandotcom** [comment]
@john-co is it our policy to remove tests when a module is deprecated? That doesn't make much sense? Since it can still break? We should probably only remove things when they are removed from Git.

Come find me so we can talk about it.  Thx.

**Comment by john-co** [comment]
Hi @brianchandotcom,
The wysiwyg module was moved to archived https://github.com/liferay/liferay-portal/tree/master/modules/apps/archived so it's not available in portal anymore. Other usages of the editor still have test coverage.

**Pull request closed without merging**
