### PR TITLE
LPS-175946 BuildLang

### PR DESCRIPTION
**Pull request by liulukiwi**
This is only for master.

https://issues.liferay.com/browse/LPS-175946

@victorg1991

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:reopen

**Comment by liulukiwi** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/11170

**Comment by victorg1991** [comment]
There are some things missing in this pr, sorry @liulukiwi forget to stop the pr!

**Comment by victorg1991** [comment]
ci:stop

**Comment by liulukiwi** [comment]
ci:close

**Pull request closed without merging**
