### PR TITLE
master-qa-14401

### PR DESCRIPTION
**Pull request by michaelhashimoto**
http://issues.liferay.com/browse/LRQA-14401

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/90834d4525...60ff823000

**Comment by brianchandotcom** [comment]
This @michaelhashimoto see upstream for a better fix. If that still doesn't work, then add your fix to this.

Thx.

**Comment by brianchandotcom** [comment]
I went ahead and did another one at ca915006c3f43dda447ca409f9ba688b10a05011

**Comment by michaelhashimoto** [comment]
@brianchandotcom - That 2nd one worked!  Thanks!

**Pull request closed without merging**
