### PR TITLE
LPS-76517

### PR DESCRIPTION
**Pull request by jeyvison**
cc: @inacionery @pcwhite

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f4fd5166a4...1973140cb9

**Comment by brianchandotcom** [comment]
@jeyvison see 219e8918296e2215b9a9bdf554814654c66beb99 and 1973140cb952f959c20d926ebdf2f62e5ae4b03f

@hhuijser fyi

thx

**Comment by jeyvison** [comment]
@brianchandotcom Got it, thanks.

**Pull request closed without merging**
