### PR TITLE
LPS-61088

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@shuyangzhou

Recommitting the logic.
Right now, it seems it's not breaking any *.bnd files (looks like Ray has changed the *bnd files since then).
We'll see if it breaks something again in the future and deal with it then...

**Comment by shuyangzhou** [comment]
Ok, thanks @hhuijser !

**Comment by brianchandotcom** [comment]
@hhuijser can you resend.. we changed the syntax

Can you catch 8acaec48dfcdcfabcc5e7d91ea10fcf6ffd6bf7f too? 

THx.

**Comment by hhuijser** [comment]
oops... my bad

**Pull request closed without merging**
