### PR TITLE
LPS-98177 SF

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/67af1f462f...87d817be69

**Comment by brianchandotcom** [comment]
@sandrodw3 please resend:

```
See      [exec] ERROR: Unable to parse /opt/dev/projects/github/liferay-portal/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/js/components/toolbar/Experiments/ExperimentsDropdown.es.js: Unexpected token (43:3)
     [exec] ERROR: The @returns tag requires a value. File: segmentsExperiments.es.js, line: 20
     [exec] ERROR: The @returns tag requires a value. File: segmentsExperiments.es.js, line: 32
     [exec] ERROR: The @returns tag requires a value. File: ConnectedComponent.es.js, line: 93
     [exec] ERROR: The @returns tag requires a value. File: ConnectedComponent.es.js, line: 101
     [exec] 
     [exec] > Task :apps:layout:layout-content-page-editor-web:jsdoc FAILED
     [exec] > Task :apps:layout:layout-content-page-editor-web:jarSources
     [exec] > Task :apps:layout:layout-content-page-editor-web:jarSourcesCommercial
     [exec] 362 actionable tasks: 362 executed
     [exec] Gradle build finished at 2019-07-12 14:42:32.508.
     [exec] 
     [exec] FAILURE: Build completed with 2 failures.
     [exec] 

```

@epgarcia @wincent fyi

**Comment by victorg1991** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by wincent** [comment]
@sandrodw3: I'm looking into these errors now. I think they're unrelated to your pull. The bad `@returns` tags went in in these commits:

- f013be5e0a4b7 ("LPS-97526 React connection for the Store")
- b07c702c52bb5 ("LPS-97526 Listing and creating experiments")

And a think the "bad" syntax is likely `<>`/`</>` shorthand that went in in b07c702c52bb5 too.

I'll send a PR to fix both of those this morning.

**Comment by wincent** [comment]
PR with fixes is up at: https://github.com/brianchandotcom/liferay-portal/pull/75691

cc @andresfulla

**Comment by sandrodw3** [comment]
Great! thanks @wincent!

**Pull request closed without merging**
