### PR TITLE
LPS-84119

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:reopen

**Comment by ling-alan-huang** [comment]
Reopened, SF failures are not related to this pull.

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/93f670b2e6...5a8dc2a8a5

**Pull request closed without merging**
