### PR TITLE
LPS-69329 Delete duplicate DLFileEntryMetadata before doing the renaming

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @migue

**Comment by sergiogonzalez** [comment]
cc/ @sammonsjl This fixes one of the issues with the social office upgrade.

**Comment by sammonsjl** [comment]
@sergiogonzalez Thank you!

**Comment by brianchandotcom** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@sergiogonzalez do you mind resending? We fixed a few CI issues.  Thx.

**Comment by sergiogonzalez** [comment]
Resent here https://github.com/brianchandotcom/liferay-portal/pull/44961

**Pull request closed without merging**
