### PR TITLE
LPS-109066 document-library-web - Use availableLocales attribute to define the list of custom attributes' available locales as the ones available for the dlfileentrytype

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Pull request closed without merging**
