### PR TITLE
LPS-101450 Wrong comparing

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by reizero00** [comment]
ci:test:bundle

**Comment by brianchandotcom** [comment]
@achaparro fyi

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7c69243857...5dcd5c204e

**Comment by shuyangzhou** [comment]
Sent to @achaparro https://github.com/achaparro/liferay-portal-ee/pull/59

**Pull request closed without merging**
