### PR TITLE
Lps 57377

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
CI got reseted, better to retest it to be safe

ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@daledotshan your code never worked

See DataSourceFactoryImpl#isPropertyC3PO

Please retest on top of https://github.com/daledotshan/liferay-portal/pull/283 and resend. Thx.

**Comment by daledotshan** [comment]
Hey Brian,
Actually that property works for c3p0 but it cause set a invalid property for  HikariCP
Thanks for Brian catching this issue


Thanks,
Dale

**Pull request closed without merging**
