### PR TITLE
LPS-74800 Semver

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by jpince** [comment]
ci:stop

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fe15bef26c...b846437b98

**Comment by brianchandotcom** [comment]
@pavel-savinov can you send me a pull and deprecate the method if it's no longer used? Thx.

**Comment by pavel-savinov** [comment]
@brianchandotcom We still need the method(I think you mentioned [this](https://github.com/brianchandotcom/liferay-portal/pull/51798/commits/2d96eee25b4d9b9e7cd61c4fb3888d50f94b6e04) method?), we just wanted to use it's default implementation in Base class, which just returns true.

**Pull request closed without merging**
