### PR TITLE
LPS-53235 SF

### PR DESCRIPTION
**Pull request by Ithildir**
cc @petershin

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
@petershin can you add this to our auto SF? THx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/223bb5cc0d...9e163b20be

**Comment by petershin** [comment]
https://github.com/hhuijser/liferay-portal/pull/3001

**Pull request closed without merging**
