### PR TITLE
LPS-74649 Route /favicon.ico request through a servlet

### PR DESCRIPTION
**Pull request by brunobasto**
/cc @SpencerWoo @gregory-bretall

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:reopen

**Comment by brunobasto** [comment]
ci:retest

**Comment by jpince** [comment]
ci:stop

**Comment by jpince** [comment]
@brunobasto errors are unrelated, this pull looks fine, errors are related to commerce. https://loop.liferay.com/home/-/loop/feed/7360779

**Comment by brunobasto** [comment]
Thx, @jpince!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4b9757e08f...2881c2165c

**Pull request closed without merging**
