### PR TITLE
LPD-18347: Update tool tip text for unsupported types when exporting in CSV

### PR DESCRIPTION
**Pull request by sergiojimcos**
## Motivation
The idea of this PR is to update the `ClayTootipProvider` message when an user wants to export an Object Entry in CSV format.

**After PR**
Screenshot from 2024-02-21 13-51-08

**JIRA Related Ticket**
https://liferay.atlassian.net/browse/LPD-18347

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:reopen

**Comment by sergiojimcos** [comment]
Manual forwarding from here: https://github.com/liferay-headless/liferay-portal/pull/1892

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/88ad5b0e01...fb66eecd80

**Comment by brianchandotcom** [comment]
@sergiojimcos is this accurate? 2652008e70fda1b28b14deea00ed95b9a0256c77

**Comment by sergiojimcos** [comment]
Yes, it is accurate. I will send you a follow up PR to update the Poshi test

**Comment by sergiojimcos** [comment]
New PR to update Poshi test: https://github.com/brianchandotcom/liferay-portal/pull/147539

**Pull request closed without merging**
