### PR TITLE
LPS-68635 Missing language keys for KB content in Export/Import

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @jonathanmccann

**Comment by jpince** [comment]
@pyoo47 @michaelhashimoto VNC issue
ci:retest for backend failures

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
Looks good from a functional test perspective

@pyoo47 @michaelhashimoto VNC issue

@shuyangzhou @mtambara inconsistent integration test failures:
com.liferay.portal.security.pacl.PACLAggregateTest.testPACLTests (from TEST-com.liferay.portal.security.pacl.PACLAggregateTest-hypersonic)
```
com.liferay.portal.kernel.process.ProcessException: java.lang.AssertionError: Thread Thread[elasticsearch[Shatterstar][http_server_worker][T#16],5,] caught concurrent failure: java.lang.AssertionError: Uncaught exception in Thread[elasticsearch[Shatterstar][http_server_worker][T#16],5,main], java.lang.LinkageError: org/jboss/netty/util/internal/ByteBufferUtil
java.lang.AssertionError: Uncaught exception in Thread[elasticsearch[Shatterstar][http_server_worker][T#16],5,main], java.lang.LinkageError: org/jboss/netty/util/internal/ByteBufferUtil
```
com.liferay.portal.security.pacl.PACLAggregateTest.testPACLTests (from TEST-com.liferay.portal.security.pacl.PACLAggregateTest-oracle)
```
com.liferay.portal.kernel.process.ProcessException: java.lang.AssertionError: Thread Thread[elasticsearch[Nezarr the Calculator][http_server_worker][T#8],5,] caught concurrent failure: java.lang.AssertionError: Uncaught exception in Thread[elasticsearch[Nezarr the Calculator][http_server_worker][T#8],5,main], java.lang.LinkageError: org.jboss.netty.util.internal.ByteBufferUtil
java.lang.AssertionError: Uncaught exception in Thread[elasticsearch[Nezarr the Calculator][http_server_worker][T#8],5,main], java.lang.LinkageError: org.jboss.netty.util.internal.ByteBufferUtil
```
com.liferay.portlet.documentlibrary.service.DLFileVersionLocalServiceTreeTest.testFileVersionTreePathWhenMovingSubfolderWithFileVersion (from TEST-com.liferay.portlet.documentlibrary.service.DLFileVersionLocalServiceTreeTest-sybase)
```
com.liferay.exportimport.kernel.lar.PortletDataException: com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: org.hibernate.StaleStateException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1
```

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
