### PR TITLE
master-qa-20745

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LRQA-20745
https://issues.liferay.com/browse/LRQA-20741
https://issues.liferay.com/browse/LRQA-20744

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@evannagayama can you dig into that weird Wiki test? I'm seeing it fail randomly.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/58a2482314...450519b9ba

**Comment by evannagayama** [comment]
@austinchiang & collab can you look into this failing wiki test? Thanks!

**Comment by austinchiang** [comment]
@evannagayama  Will do.

**Pull request closed without merging**
