### PR TITLE
LPS-65946 We're evolving the schema, your services should depend on the proper version

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop (upstream had an issue)

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by adolfopa** [comment]
ci:retest

**Comment by adolfopa** [comment]
ci:retest

**Comment by adolfopa** [comment]
ci:retest

**Comment by adolfopa** [comment]
ci:retest

**Comment by adolfopa** [comment]
ci:retest

**Comment by jpince** [comment]
@brianchandotcom this pull looks free of functional test failures, please merge.
cc/ @jrhoun @jhendley @brianchiu 
thanks for your help @kenjiheigel

**Comment by adolfopa** [comment]
Thank god, this was driving me crazy. Thanks a lot for looking into this guys !

**Comment by brianchiu** [comment]
Upgrades failure is OK -> it was a fluke with a success message. @kenjiheigel is stabilizing it.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8d198dbc12...85cc4fe97f

**Comment by brianchandotcom** [comment]
@jhendley we need tests for this.

**Pull request closed without merging**
