### PR TITLE
LPS-70667 Before falling back to visible-only calendars, check if there is a manageable calendar from the group. Otherwise, the user would not be able to add events to an an available, non-default group calendar.

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brandizzi** [comment]
ci:retest

**Comment by brandizzi** [comment]
ci:reopen

**Comment by brandizzi** [comment]
@brianchandotcom if I'm right, the breaking test is not related to the fix, given that the second test run passed.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7bee9bb7e0...d29dd2bbc1

**Pull request closed without merging**
