### PR TITLE
LPS-59564 sdk

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/91c10fe62f...0a2b466965

**Comment by brianchandotcom** [comment]
@Ithildir I published a new ant-bnd. I also published a new gradle-plugins that uses the new ant-bnd.

Can you send me a pull to "use" the new gradle-plugins. Thx.

**Pull request closed without merging**
