### PR TITLE
LPS-60646 Assign site roles views - Supports multiple selection

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @evannagayama,

Could you take a look into the poshi errors?

Thanks!!!

**Comment by ealonso** [comment]
I think the problem in some test is because I've moved the Add Member action from: 

site_memberships_-_liferay

to inside each tab:

site_memberships_-_restricted_site_-_liferay

**Comment by brianchandotcom** [comment]
@evannagayama plaese resend? Thx.

**Comment by evannagayama** [comment]
@brianchandotcom ok we'll work on it, thanks! @ealonso next time, after it fails can you send the pull request to me, then we'll work on it? It's just easier to track, thanks!

**Comment by evannagayama** [comment]
@brianwulbern, please take a look at this and make test fixes. Thank you!

**Comment by evannagayama** [comment]
@koor4356, please take a look at this and make test fixes. Thank you!

**Comment by ealonso** [comment]
Hey,
@evannagayama @anthony-chu, any update of test fixes? Let me know if I can help you with anything.

**Comment by evannagayama** [comment]
Hey @ealonso, it's in my pull queue https://github.com/evannagayama/liferay-portal/pull/258. There were some failures, but I think it's something with jenkins. I'm going to retest it now.

**Comment by evannagayama** [comment]
@ealonso pushed here https://github.com/brianchandotcom/liferay-portal/pull/32461

**Pull request closed without merging**
