### PR TITLE
LPS-96968 admin user tests for GraphQL

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ae037d5334...46fe290276

**Comment by brianchandotcom** [comment]
I merged most of this except for the manual test changes. Can you update:

```

		pageGraphQLFields.add(new GraphQLField("page"));
		pageGraphQLFields.add(new GraphQLField("totalCount"));
		pageGraphQLFields.add(
			new GraphQLField(
				"items", graphQLFields.toArray(new GraphQLField[0])));
```

and sort that in UserAccountGraphQLTest

and then resend the pull? Thx!

**Comment by brianchandotcom** [comment]
@nhpatt was this the right ticket? https://issues.liferay.com/browse/LPS-96968

Looks wrong?

**Comment by nhpatt** [comment]
Argh, last commit number is wrong, it is LPS-96698 (https://issues.liferay.com/browse/LPS-96698)

**Pull request closed without merging**
