### PR TITLE
LPS-81411 Smart Facet Selections with Solr

### PR DESCRIPTION
**Pull request by arboliveira**
CI was too unstable to analyze (https://github.com/arboliveira/liferay-portal/pull/543#issuecomment-399312036) but locally, ran our full Search TCK and all tests passed.

@xbrianlee `7.1-MustFix`. (only 1 more to go)

@marco-leo `SimpleFacet` and `MultiValueFacet` working as expected, see: 
https://github.com/arboliveira/liferay-portal/blob/411b9bded48d1f9e7bbfe916174dcd4d7175fab5/modules/apps/portal-search/portal-search-test-util/src/main/java/com/liferay/portal/search/test/util/facet/BaseSimpleFacetTestCase.java 
and 
https://github.com/arboliveira/liferay-portal/blob/411b9bded48d1f9e7bbfe916174dcd4d7175fab5/modules/apps/portal-search/portal-search-test-util/src/main/java/com/liferay/portal/search/test/util/facet/BaseMultiValueFacetTestCase.java

Author: @BryanEngler 
Reviewer: @arboliveira

https://issues.liferay.com/browse/LPS-81411

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by jpince** [comment]
@jbalsas this is a strange error in portal-frontend-js... and I don't think search changes would have affected this? Have not seen this anywhere else yet.
```
     [exec]  FAIL  test/liferay/portlet/PortletHub.es.js (5.476s)
     [exec]   ??? Portlet Hub ??? onStateChange without render data ??? is not passed a RenderData object
     [exec] 
     [exec]     Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
     [exec]       
     [exec]       at pTimeout (node_modules/jest-jasmine2/build/queueRunner.js:53:21)
     [exec]       at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
     [exec]       at ontimeout (timers.js:482:11)
     [exec]       at tryOnTimeout (timers.js:317:5)
     [exec]       at Timer.listOnTimeout (timers.js:277:5)
```

**Comment by jpince** [comment]
@jbalsas I actually see the same error in upstream, can you please take a look? going to ignore in upstream for now
https://test-1-9.liferay.com/job/test-portal-acceptance-upstream-batch(master)/AXIS_VARIABLE=0,label_exp=!master/22022/console

**Comment by jpince** [comment]
Ignored in https://github.com/liferay/liferay-portal/commit/88a11cfc5220691756414f08636fbcb92f1084d2
cc/ @julien

**Comment by jbalsas** [comment]
Thanks @jpince, we'll take a look asap!

**Pull request closed without merging**
