### PR TITLE
LPS-97329 Show error message to the user

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @pavel-savinov

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/abbe6862c2...b6292ae0d3

**Comment by vicnate5** [comment]
@jkappler The test results here show passing, but maybe  due to the delay in merge, this causes a Semver issue at head.

```
    [echo]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [echo] = ================================================== ========== ========== ========== ========== ==========
     [echo] * com.liferay.asset.kernel.exception                 MAJOR      1.2.1      1.3.0      2.0.0      VERSION INCREASE REQUIRED
     [echo] 	-   class      com.liferay.asset.kernel.exception.InvalidAssetCategoryException
     [echo] 		-   extends    com.liferay.portal.kernel.exception.NestableException
     [echo] 		-   extends    com.liferay.portal.kernel.exception.PortalException
     [echo] 		-   extends    java.lang.Exception
     [echo] 		-   extends    java.lang.Throwable
     [echo] 		-   implements java.io.Serializable
     [echo] 		-   field      CANNOT_MOVE_INTO_CHILD_CATEGORY
     [echo] 			-   access     final
     [echo] 			-   access     static
     [echo] 			-   constant   1
     [echo] 			-   return     int
     [echo] 		-   field      CANNOT_MOVE_INTO_ITSELF
     [echo] 			-   access     final
     [echo] 			-   access     static
     [echo] 			-   constant   2
     [echo] 			-   return     int
     [echo] 		-   method     <init>(long,int)
     [echo] 			-   return     void
     [echo] 		-   method     addSuppressed(java.lang.Throwable)
     [echo] 			-   access     final
     [echo] 			-   return     void
     [echo] 		-   method     clone()
     [echo] 			-   access     protected
     [echo] 			-   return     java.lang.Object
     [echo] 		-   method     equals(java.lang.Object)
     [echo] 			-   return     boolean
     [echo] 		-   method     fillInStackTrace()
     [echo] 			-   return     java.lang.Throwable
     [echo] 		-   method     finalize()
     [echo] 			-   access     protected
     [echo] 			-   return     void
     [echo] 		-   method     getCategoryId()
     [echo] 			-   return     long
     [echo] 		-   method     getCause()
     [echo] 			-   return     java.lang.Throwable
     [echo] 		-   method     getLocalizedMessage()
     [echo] 			-   return     java.lang.String
     [echo] 		-   method     getMessage()
     [echo] 			-   return     java.lang.String
     [echo] 		-   method     getMessageArgument(java.util.Locale)
     [echo] 			-   return     java.lang.String
     [echo] 		-   method     getMessageKey()
     [echo] 			-   return     java.lang.String
     [echo] 		-   method     getStackTrace()
     [echo] 			-   return     java.lang.StackTraceElement[]
     [echo] 		-   method     getSuppressed()
     [echo] 			-   access     final
     [echo] 			-   return     java.lang.Throwable[]
     [echo] 		-   method     hashCode()
     [echo] 			-   return     int
     [echo] 		-   method     initCause(java.lang.Throwable)
     [echo] 			-   return     java.lang.Throwable
     [echo] 		-   method     printStackTrace()
     [echo] 			-   return     void
     [echo] 		-   method     printStackTrace(java.io.PrintStream)
     [echo] 			-   return     void
     [echo] 		-   method     printStackTrace(java.io.PrintWriter)
     [echo] 			-   return     void
     [echo] 		-   method     setStackTrace(java.lang.StackTraceElement[])
     [echo] 			-   return     void
     [echo] 		-   method     toString()
     [echo] 			-   return     java.lang.String
     [echo] 		-   annotated  org.osgi.annotation.versioning.ProviderType
     [echo] 	+   version    1.2.1
     [echo] 	-   version    1.3.0
     [echo] * com.liferay.portal.kernel.service                  MAJOR      2.1.0      2.2.0      3.0.0      VERSION INCREASE REQUIRED
     [echo] 	>   class      com.liferay.portal.kernel.service.GroupLocalServiceUtil
     [echo] 		-   method     fetchGroup(long,long,long)
     [echo] 			-   access     static
     [echo] 			-   return     com.liferay.portal.kernel.model.Group
     [echo] 	>   class      com.liferay.portal.kernel.service.GroupLocalServiceWrapper
     [echo] 		-   method     fetchGroup(long,long,long)
     [echo] 			-   return     com.liferay.portal.kernel.model.Group
     [echo] 	>   interface  com.liferay.portal.kernel.service.GroupLocalService
     [echo] 		-   method     fetchGroup(long,long,long)
     [echo] 			-   access     abstract
     [echo] 			-   annotated  com.liferay.portal.kernel.transaction.Transactional
     [echo] 				-   property   propagation='SUPPORTS'
     [echo] 				-   property   readOnly=true
     [echo] 			-   return     com.liferay.portal.kernel.model.Group
     [echo] 	+   version    2.1.0
     [echo] 	-   version    2.2.0
```

**Comment by jkappler** [comment]
hey @vicnate5, it's weird, I ran baseline at HEAD today and I didn't get that issue

**Comment by vicnate5** [comment]
@jkappler confirmed this is NLR at head. Change was made with portal.kernal.service in another commit (b2106f4671014fb75436a8933c8636a147b3a847)

**Comment by jkappler** [comment]
thanks @vicnate5, was getting worried that something was wrong in my local branch 😄

**Pull request closed without merging**
