### PR TITLE
LPS-59133

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-59133.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
SF issue persists, please resend

```
java.lang.Exception: missing language key: share-this-application-on-any-website: ../../../modules/apps/web-experience/portlet-configuration/portlet-configuration-sharing-web/src/main/resources/META-INF/resources/view.jsp
Stacktrace

java.lang.Exception: missing language key: share-this-application-on-any-website: ../../../modules/apps/web-experience/portlet-configuration/portlet-configuration-sharing-web/src/main/resources/META-INF/resources/view.jsp

	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:241)
	at com.liferay.source.formatter.SourceFormatterTest.testSourceFormatter(SourceFormatterTest.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)

````

**Comment by jonmak08** [comment]
Hey @brianchandotcom,

I saw that issue and fixed it.  On the subsequent test, that SF issue did not exist.  I will resend another pull.

Please let me know if you have any questions. Thanks!

**Comment by jonmak08** [comment]
Retesting again: https://github.com/jonmak08/liferay-portal/pull/1610

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/brianchandotcom/liferay-portal/pull/42696

**Pull request closed without merging**
