### PR TITLE
LRAC-13485 Follow Up Master

### PR DESCRIPTION
**Pull request by interaminense**

### CODE REVIEW

**Comment by interaminense** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/11b5b41f48...7c228a9a88

**Comment by brianchandotcom** [comment]
@interaminense see b32f615bf62b4d0abcf34f7e2bb8fae577480f67

**Pull request closed without merging**
