### PR TITLE
LPS-92609 SF

### PR DESCRIPTION
**Pull request by jbalsas**
Hey Brian!

I've been throwing a bit of incremental work into the build process today. I can send separately if you prefer, but seeing as they build on each other, didn't want to risk them getting merged in a weird order.

This PR includes:
- Small consolidation of dependencies and removal of unnecessary files and configuration (more coming)
- Almost complete removal of `replaceSoyTranslation` usage in favour of our builtin capabilities, so we don't need to spawn another task. Translations in soy are already handled in the same step
- JS tests fixes. All frontend tests should be running after this (more consolidation work coming).

@diegonvs is working with me on continuing to consolidate all build scripts so we see a coherent and single approach throughout projects and @petershin is working on the caching mechanism and we should be sending a pr soon about it.

That's it for now!

/cc @jpince

### CODE REVIEW

**Comment by john-co** [comment]
rerunning select functional smoke tests here: https://github.com/john-co/liferay-portal/pull/97
to check if `LIFERAY_ERROR: {code="404", msg="ProxyServlet: /liferay/o/admin-theme/images/lexicon/icons.svg", uri=/liferay/o/admin-theme/images/lexicon/icons.svg}` persists

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
ci:reopen

**Comment by john-co** [comment]
Failures are not related to this pull based on john-co#97 results. Will follow up on a minor test fix.

**Comment by brianchandotcom** [comment]
@jbalsas I got a conflict! Can you resend and I'll merge asap.

**Pull request closed without merging**
