### PR TITLE
LPS-53780 No need to show site name in breadcrumb when selecting folder

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by zxdgoal** [comment]
@ealonso 

Just wanna confirm how you test journal.

I did test the select folder in web content, finding there is no site name in breadcrumb when selecting parent fold.

Thanks
John.

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
Hi @zxdgoal,

If you want to test it, you should modify the liferay-portlet.xml to allow to put the journal portlet into a page.

Regards,
Eudaldo.

**Comment by zxdgoal** [comment]
Got it.

Even couldn't figure this out.

Thanks.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1544fbd919...52e809650e

**Pull request closed without merging**
