### PR TITLE
LPS-154677 Move the code LocalizedMapUtil from object-api and notification-api to Vulcan

### PR DESCRIPTION
**Pull request by murilostodolni**
The errors https://github.com/liferay-objects/liferay-portal/pull/1595#issuecomment-1382508677 are not related with this code.

Issue: https://issues.liferay.com/browse/LPS-172407

### CODE REVIEW

**Comment by murilostodolni** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/96afdd7974...e6cc8b9e36

**Comment by brianchandotcom** [comment]
Very well done @murilostodolni !

**Comment by murilostodolni** [comment]
Thank you @brianchandotcom

**Pull request closed without merging**
