### PR TITLE
LPS-107610 Fix empty editor styles

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:Test:sf

**Comment by victorg1991** [comment]
@ealonso

**Comment by brianchandotcom** [comment]
@pyoo47 hey, network issue again. Please fix.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b833948df5...86b62c067e

**Pull request closed without merging**
