### PR TITLE
LPS-50757 more renaming

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
@brianchandotcom Is there anything I can help with this?

**Comment by brianchandotcom** [comment]
No, it looks good. On todo. Thx.

**Comment by rotty3000** [comment]
Great! :)

**Comment by brianchandotcom** [comment]
I sent this to @marcellustavares to finish up my changes. Part of is it that it does use DDMForm and I wanted him to see it, and part of it was just so he can finish up applying my SF. Thx.

See https://github.com/marcellustavares/liferay-portal/pull/402

**Comment by brianchandotcom** [comment]
I ended up merging at least the mass changes to *-web that you did, and then resent it to Marcellus so that we at least made some progress. Thx.

https://github.com/marcellustavares/liferay-portal/pull/403

**Pull request closed without merging**
