### PR TITLE
LPS-58529 Apply everywhre

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3d96e6cb51...904646f60d

**Comment by brianchandotcom** [comment]
@izaera please double check my work. Thx.

**Comment by brianchandotcom** [comment]
@hhuijser can you add a rule in SF to force people to only use our own ResourceBundleUtil? It'll prevent a lot of UTF8 bugs.

@izaera  fyi

**Comment by izaera** [comment]
@brianchandotcom Your changes look good. I also thought about creating a method receiving the Class instead of the ClassLoader, but decided not do it. Nevertheless, after the "apply everywhere" commit it makes sense, as we are passing the Class' ClassLoaders 99% of the time.

**Pull request closed without merging**
