### PR TITLE
LPS-105510 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LPS-105510

### CODE REVIEW

**Comment by john-co** [comment]
Reverting this fixes a few acceptance testcases. 
/cc @jbalsas, @izaera, @joshchong, @alexcandidos

**Comment by john-co** [comment]
Reviewed ci tests in https://github.com/brianchandotcom/liferay-portal/pull/81770. Test failures are unrelated.

**Comment by brianchandotcom** [comment]
@wincent fyi

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3359a6807d...868b941fad

**Comment by brianchandotcom** [comment]
@john-co I linked LPS-105510 to LPS-105362

**Pull request closed without merging**
