### PR TITLE
LPS-171587 Add step to adapt new behavior

### PR DESCRIPTION
**Pull request by Tim-Cao**
This is only for master.

https://issues.liferay.com/browse/LPS-171587

@ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/10701

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ecf7ef3667...0114e23e04

**Comment by brianchandotcom** [comment]
@ealonso see 0114e23e04d71340dc5134403476722b5609d1b3

**Pull request closed without merging**
