### PR TITLE
LPS-70451 cache

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @brianchandotcom, @Ithildir, the state of https://issues.liferay.com/browse/LPS-70451 is a bit confusing... it makes you think this was already commited to both master and ee-7.0.x, but I don't think so.

I'm keeping it open, but feel free to close/change as needed.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
Thx @jbalsas 

It's cause it's a long running ticket that we're just reusing for moving a bunch of these zip files to Gradle.

In any case, I backported this (cherry picked cleanly)

**Comment by jbalsas** [comment]
Great, @brianchandotcom, thanks for the explanation and the backport! :)

**Pull request closed without merging**
