### PR TITLE
Upgrade Class Names: Basic support

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by migue** [comment]
FYI
/cc @mhan810 @juliocamarero @sergiogonzalez @marcellustavares

**Comment by brianchandotcom** [comment]
This is good.. not need to retest.

**Comment by brianchandotcom** [comment]
@Preston-Crary does this conflict with your upgrade class ?

**Comment by Preston-Crary** [comment]
@brianchandotcom Yes, I have a pull that updates all of them. See: https://github.com/shuyangzhou/liferay-portal/pull/2511

**Comment by Preston-Crary** [comment]
@brianchandotcom Also note that it will need to be the first upgrade or the other ones will likely fail.

**Comment by brianchandotcom** [comment]
Waiting on https://github.com/shuyangzhou/liferay-portal/pull/2536 then will ask @Preston-Crary which pull to merge (likely a combo of both)

**Comment by brianchandotcom** [comment]
@migue @Preston-Crary is testing this further and will have something for tomorrow.. We couldn't get it in today.

**Comment by brianchandotcom** [comment]
@migue a version of this is now pushed to upstream

see fbe8b4a50c7bacf92790c43239716766540c812d to 8d550e53c4b37f8a4f7148c1eaecaea4be566abf

This pull helped catch some errors in code from @Preston-Crary

**Pull request closed without merging**
