### PR TITLE
LPS-57746 make panels adapt to the width of the container depending on the number of panels visible

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci: retest

**Comment by juliocamarero** [comment]
@ZoltanTakacs can we please backport this? thank you!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fe24e94978...dbb879fe29

**Comment by juliocamarero** [comment]
@ZoltanTakacs can we please backport this? thank you!

**Comment by ZoltanTakacs** [comment]
@juliocamarero sure, it will be in M7.

Thank you

**Pull request closed without merging**
