### PR TITLE
LPS-71243 Auto

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:retest

**Comment by jpince** [comment]
@ealonso These look like real failures
`[exec] com.liferay.document.library.trash.test.DLFolderTrashHandlerTest > testTrashParentAndBaseModel FAILED`
`[exec]     java.lang.Exception: Unexpected exception, expected<com.liferay.trash.exception.TrashEntryException> but was<com.liferay.trash.kernel.exception.TrashEntryException>`
https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=14,label_exp=!master/117126/console

`[exec] com.liferay.message.boards.trash.test.MBThreadTrashHandlerTest > classMethod FAILED`
`[exec]     java.lang.RuntimeException: Could not create statement`
`[exec]         java.lang.TypeNotPresentException: Type com.liferay.trash.exception.TrashEntryException not present`
https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=14,label_exp=!master/76715/console
Similar failure for `BlogsEntryTrashHandlerTest `
https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=12,label_exp=!master/117610/console

**Comment by jpince** [comment]
ci:close

**Pull request closed without merging**
