### PR TITLE
LPS-88988 Registering events for initial capabilities

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
@4lejandrito

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/43f6409143...2bc4218f00

**Comment by brianchandotcom** [comment]
@ruben-pulido can you backport this (at least the test part, not sure about the other ticket)

Send it to me directly.

Thx

**Comment by 4lejandrito** [comment]
Hi @brianchandotcom, @ruben-pulido,

The other 2 commits are not meant to be backported. They rely on a set of fairly big changes we made for 7.2.

**Comment by ruben-pulido** [comment]
Hi @brianchandotcom 
PR with backport sent [here](https://github.com/brianchandotcom/liferay-portal-ee/pull/22975)

**Pull request closed without merging**
