### PR TITLE
LPS-60474

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/241e07b738...1578f47c37

**Comment by brianchandotcom** [comment]
@hhuijser can you distinguish taglibs and regular markup?

Regular markup is OK

```
<a href="<%= "x" + "y" %>"
```

Taglib mark up is not

```
<aui:a href="<%= "x" + "y" %>"
```

and must be changed to

```
<aui:a href='<%= "x" + "y" %>'
```

**Comment by hhuijser** [comment]
@brianchandotcom 

Think that's already the case?
The regex _jspTagAttributes looks for that colon: "<[-\\w]+:[-\\w]+ (.*?[^%])>"

Do you have cases where it's doing it wrong right now?

**Comment by hhuijser** [comment]
Ah, I think we have cases like that where it's incorrectly giving warning when the taglib is mutiline.

Are the first two fixes here wrong? https://github.com/hhuijser/liferay-portal/commit/2c2e3bb550fb2b69283f4f7c4d23db0045ccf665

**Comment by brianchandotcom** [comment]
Yes, those fixes are wrong. They can stay " since it's not a taglib.

--
Brian Chan
Chief Software Architect
Liferay, Inc.
Enterprise. Open Source. For Life.
(626) 806-1190

**Comment by hhuijser** [comment]
Okay, will work on that and change those back

**Comment by brianchandotcom** [comment]
Thx bro

--
Brian Chan
Chief Software Architect
Liferay, Inc.
Enterprise. Open Source. For Life.
(626) 806-1190

**Pull request closed without merging**
