### PR TITLE
LPS-189834 Expire info is missing in Content Display

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://liferay.atlassian.net/browse/LPS-189834

@BarbaraCabrera

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/12753

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ab6ed9072f...150dfc7267

**Comment by brianchandotcom** [comment]
@BarbaraCabrera @Tim-Cao this should be the same logic, but simpler 63958c09a76386505dd83b8ba8a16535c50f9328

Please review and apply else where. Thx.

**Pull request closed without merging**
