### PR TITLE
master-qa-22085

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LRQA-22085

### CODE REVIEW

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
hmm i think it triggered 2 runs when i reopened the branch and then with the retest after the new commit. I'll retest once more to be sure...

ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f29d0266ff...4cc8580ada

**Comment by brianchandotcom** [comment]
Well, at least one of them passed so I'm merging this in. Please track this pull.

**Pull request closed without merging**
