### PR TITLE
LPS-147083 Migrate Feeds Type To Asset Categories 

### PR DESCRIPTION
**Pull request by Tim-Cao**
This is only for master.

https://issues.liferay.com/browse/LPS-147083

@lfbesada

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/11280

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/237dd70ef4...9163bcaa9b

**Comment by brianchandotcom** [comment]
@lfbesada @georgel-pop-lr see minor changes in d4dd2b80 and 9163bcaa thx.

**Pull request closed without merging**
