### PR TITLE
LPS-71594 Add to forms portlet a URL to retrieve available functions

### PR DESCRIPTION
**Pull request by diogo-lins**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by diogo-lins** [comment]
ci:reopen

**Comment by diogo-lins** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a6ff9b2115...dd74d7ce7a

**Comment by brianchandotcom** [comment]
@diogo-lins @leoadb see dd74d7ce7a9b8053bad58c78953b1c90d9d29435

**Pull request closed without merging**
