### PR TITLE
LPS-96717 Fix frontend-js-web version

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test

**Comment by jpince** [comment]
@julien this seems like something that could easily be checked by SF... you can write an lps task ticket and email it to Hugo Huijser if you're interested.

**Comment by brianchandotcom** [comment]
master-private as well?

@hhuijser please SF enforce this. Thx.

**Comment by julien** [comment]
@brianchandotcom I also submitted this here https://github.com/liferay/liferay-portal-ee/pull/14603

**Comment by hhuijser** [comment]
@julien when do we need `^`?

**Comment by julien** [comment]
Hi @hhuijser ,

`^` is used for  "minor releases": I think this [article](https://docs.npmjs.com/about-semantic-versioning) will be more useful that my comment.

**Comment by ling-alan-huang** [comment]
Hi @julien,
I am working on SF with @hhuijser,
Should SF just enforce adding `^` for `frontend-js-web`?

**Comment by julien** [comment]
Hi @ling-alan-huang ,

Yes please.

Thanks!

**Pull request closed without merging**
