### PR TITLE
LPS-68581 Update npm-shrinkwrap (autogenerated)

### PR DESCRIPTION
**Pull request by jbalsas**
/cc @ithildir

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:stop

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
Hey @kenjiheigel, this includes some changes in AlloyEditor that might be breaking the Selenium locators... could you please take a look?

Thanks!

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
@jbalsas, strange that it only failed on the lpkg.. I'll make sure there's no issues and keep you posted.

**Comment by ealonso** [comment]
Hey @kenjiheigel,

Do you have any update about it?

Thanks!!!

**Comment by kenjiheigel** [comment]
Hi @ealonso, it's been really hard to narrow down as I think it's something happening only on CI. 

Here's what I know so far:
* The lpkg test fails when loading portal and trying to add Web Content because the AlloyEditor is not available. It also throws this javascript error: https://gist.github.com/kenjiheigel/083d87b90def1c6f575e14900e493cee. Note that this lpkg test will create a bundle using osgi jars that have been reorganized into lpkg files. 
* It starts happening with AlloyEditor 1.2.4
* I can't reproduce it locally using the lpkg process. 

I've been trying to isolate the issue here:
https://github.com/kenjiheigel/liferay-portal/pull/315

Once I get the issue isolated and reproducible, I can ask @jbalsas to take a look. Sorry that it's taking a while! It's quite a strange issue.

**Comment by daledotshan** [comment]
Hey @kenjiheigel 
Any update for this issue?

Thanks,
Dale

**Comment by kenjiheigel** [comment]
Hi @daledotshan, not yet. I tried a few things from @jbalsas, but haven't managed to make progress. Going to try a bit more this afternoon. Sorry for the delay!

**Comment by kenjiheigel** [comment]
Resent to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/44520

**Comment by kenjiheigel** [comment]
Original issue was that the lpkg jobs were running poshi tests on FF38, not FF45. The fix is on the jenkins side. 

Jenkins fix:
https://github.com/liferay/liferay-jenkins-ee/commit/24cd78e17b6dce554fcfff6ba84880da0ca0e790

**Pull request closed without merging**
