### PR TITLE
LPS-57396 Add test

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/54bfeb84b9...1a5ff23dae

**Comment by brianchandotcom** [comment]
@marcellustavares we allow OSGi properties to go beyond 80

see 1a5ff23daea9a4769ab29be6aef11dbd9e24d903

Thx!

**Comment by marcellustavares** [comment]
Nice, thx @brianchandotcom

**Pull request closed without merging**
