### PR TITLE
LPS-169953 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-169953

This is only for master.

@BarbaraCabrera
@lfbesada

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure case is unrelated to changes in this PR.
See https://github.com/liferay-echo/liferay-portal/pull/10531
ci:test:stable - 28 out of 28 jobs passed
ci:test:relevant - 165 out of 179 jobs passed in 2 hours 33 minutes

**Comment by brianchandotcom** [comment]
@BarbaraCabrera @lfbesada see

```
there-is-already-an-organization-type-with-the-name-x=There is already an organization type with the name: {0}.
```

The key

```
already-exist-another-utility-page-with-this-name=Already exist another Utility Page with this name.
```

sounds strange.

@lfbesada please resend on top of https://github.com/lfbesada/liferay-portal/pull/119

**Comment by lfbesada** [comment]
Hi @brianchandotcom ,

I have resent on top of https://github.com/lfbesada/liferay-portal/pull/119 here https://github.com/liferay-echo/liferay-portal/pull/10536

I have reverted your last commit because the name is needed to get the copied previewFileEntryId due to the new folder's name.

Regards

cc: @BarbaraCabrera

**Pull request closed without merging**
