### PR TITLE
LPS-61714 avoid ArrayIndexOutOfBoundException

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @austinchiang this should fix https://issues.liferay.com/browse/LPS-62568

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b9e82d6afa...159dc2f799

**Comment by brianchandotcom** [comment]
@sergiogonzalez we need to do this check in a few places.

I asked @juliocamarero to abstract it out to a util. Otherwise, you're still going to run into Array exceptions.

Please abstract out to common method? Thx.

**Comment by juliocamarero** [comment]
Hi @brianchandotcom 

no need no check it anywhere else, this is the only place where we obtain the initials from a String. The other place you mean is UserImpl.getInitials() but there we obtain the name from the first name and last name in a different way.

Let us know if you have any idea to encapsulate that.

thank you!!

**Pull request closed without merging**
