### PR TITLE
LPS-88707 SF

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7ec1ca668b...d0357c0288

**Comment by brianchandotcom** [comment]
@preston-crary this is in upstream, but its usage of OSGi in DDMFormFieldTypesDynamicIncludeHelper seems wrong to me (since it's a component that is only used in this submodule)

Can you fix this ticket in upstream and notify @brunobasto and @leoadb 

Thx

**Comment by Preston-Crary** [comment]
@brianchandotcom I'll take a look.

**Comment by Preston-Crary** [comment]
@brianchandotcom it's weird but we have quite a few like that.  If we're able to create a strategy for all of them we'll go through and remove ones like this.

@shuyangzhou and I have talked about ones like this before but have always had to do situational solutions.  I see a way to resolve this one but it requires a small runtime performance cost instead of a small startup time cost (both are very cheap), we usually prefer the startup cost over the runtime cost.

**Comment by shuyangzhou** [comment]
@Preston-Crary just fix it for this case, make the DDMFormFieldTypesDynamicIncludeHelper a real static util class. Let the caller to collect DDMFormFieldTypeServicesTracker and DDMFormFieldTypesSerializerTracker, then pass them in as parameters.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/7249

**Pull request closed without merging**
