### PR TITLE
LPS-94565 Also need to include the other packages in org.eclipse.osgi…

### PR DESCRIPTION
**Pull request by shuyangzhou**
….jar

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@tinatian can you send me a pull and sort

```
			packageNames[files.length] = "org.apache.felix.resolver.";
			packageNames[files.length + 1] = "org.eclipse.equinox.";
			packageNames[files.length + 2] = "org.eclipse.core.";
			packageNames[files.length + 3] = "org.osgi.";
```

Thx!

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/72125

**Pull request closed without merging**
