### PR TITLE
LPS-52675

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@hhuijser I can't move this yet, because if I do, I need your help with backporting Prestn's big pull a few days ago to ee-7.0.x (and you haven't sent me part of it yet)  I emailed yesterday about it. I'll get a conflict. Please resend. Thx.

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
Should be okay to backport now...

**Comment by brianchandotcom** [comment]
@hhuijser This still has a SF test error? Please resend. Thx.

**Pull request closed without merging**
