### PR TITLE
LPS-58330

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Okay, think this is the last one...

ant format-source-current-branch

Takes into account all the files in the current branch compared to the working branch (which is master for trunk).
This one expects master to to up-to-date, but even if it isn't, it shouldn't do harm, it will just format more commits than needed.

it simply runs "git log master..head" and formats all files in these commits.

**Comment by shuyangzhou** [comment]
Nice :) Thanks @hhuijser !

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3f11541c9c...0c444594f9

**Comment by brianchandotcom** [comment]
Nice job @hhuijser  :)

**Pull request closed without merging**
