### PR TITLE
LPS-67503

### PR DESCRIPTION
**Pull request by Ithildir**
To generate the parent themes digests, please go to `modules/apps/foundation/frontend-theme`, delete `settings.gradle` and then run:

```
gradlew writeParentThemesDigest
```

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:stop

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
