### PR TITLE
LPS-99884  - Lock AB Test 

### PR DESCRIPTION
**Pull request by darquesdev**
@dgarciasarai

### CODE REVIEW

**Comment by darquesdev** [comment]
Hi @brianchandotcom, could you please review? It is needed to do the last task for running a AB Test. Thanks in advance!

**Comment by brianchandotcom** [comment]
See portal-impl/src/com/liferay/portlet/asset/service/impl/AssetEntryLocalServiceImpl.java

int[] statuses

I typed

git grep "int\[\]" **ServiceImpl.java

Please resend. Thx.

**Comment by darquesdev** [comment]
Hi @brianchandotcom, 

I took the name from this example:
`com.liferay.knowledge.base.service.persistence.impl.KBArticleFinderImpl#countByUrlTitle`

which is doing something very similar what I needed it. 
Indeed, if you search "int[] status" there are several examples too.

But I can resend if you want! please, let me know. Thanks!

**Comment by darquesdev** [comment]
Please, see #77367

thanks

**Pull request closed without merging**
