### PR TITLE
LPS-70885 Review

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by brianwulbern** [comment]
LanguageUsecase test failure is flaky, but also failing here: https://github.com/brianchandotcom/liferay-portal/pull/47276#issuecomment-283778826

**Comment by migue** [comment]
ci:reopen

**Comment by migue** [comment]
ci:retest

**Comment by migue** [comment]
The original pull request ran smoothly https://github.com/migue/liferay-portal/pull/949

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1df8778d68...87843ea082

**Pull request closed without merging**
