### PR TITLE
LPD-40716 - Add react-compiler-eslint-plugin

### PR DESCRIPTION
**Pull request by bryceosterhaus**
@brianchandotcom 

Just to give context on this. When we started working on the upgrade to React 18, we noticed inconsistencies and poorly written react code in DXP across several teams. A lot of these issues stemmed from developers not following the ["rules of react"](https://react.dev/reference/rules) which are pretty standard for react development.

It wasn't feasible for us to go through and update all this code, as it would take large refactors. So instead, we thought it best to adopt react's new eslint-plugin which essentially shows errors for places where react is written improperly.

Adding this new eslint plugin and rule to liferay-portal resulted in 600+ failures. So we devised a way to simultaneously keep SF stable, while also surfacing these errors to developers in their code.

This is why we have the `suppressed_errors.txt` file. This contains a list of files and errors we expect to currently fail, and this keeps SF stable. However, developers will see the errors in their IDEs and should cause some friction for them to clean up their improper react code. Also, any new code that breaks the react rules should be caught now by SF.

We don't expect `suppressed_errors.txt` to grow and should be a one time static file to keep track of which errors to suppress for SF. Eventually, this file can be removed as errors are addressed.

Let me know if you see any issues with this approach.

Also, for context, by adopting this eslint plugin from react, it will pave a way for us to use the react-compiler for building JS. This will allow us to remove hundreds/thousands of lines of boilerplate react code.

---------------

This adds two new flags, one intended to only be used by us (which is why it isn't listed in the "help" command)

- `--emit-suppressed` this will show all eslint errors, included any we have suppressed

So with this approach we get a few things

- CI remains stable even with existing failures
- Existing failures can be see via `yarn format --emit-suppressed`
- Existing errors will still show up in your IDE(these are not suppressed)

Editor example:
Screenshot 2024-10-29 at 12 24 44 PM

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
manual forward from https://github.com/liferay-frontend/liferay-portal/pull/4521, ci wasn't forwarding

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5fd5f3e468...bc425dc709

**Comment by brianchandotcom** [comment]
@bryceosterhaus this is OK as a stop gap. I'm fine with "grandfathering" the older files, BUT, I want you to push the teams to clean them up, and give them a date (4 weeks from now) - add it to your calendar where you'll remove the file.

You got the teams to add their names to the codeowners, so I have confidence you can get them to clear out these errors.

If I do a get a PR that adds suppressed_errors.txt, I'll reject the PR.

**Comment by bryceosterhaus** [comment]
@brianchandotcom sounds good. I am going to wait to add a date until we finish the react 18 epic, which is in review by other teams at the moment

Once that is through, I will work with PM to try and push fixing these errors.


> If I do a get a PR that adds suppressed_errors.txt, I'll reject the PR.

That'd be great. Thanks

**Pull request closed without merging**
