### PR TITLE
LPS-54646 fix issue about inheriting locales from a language code

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@fafonso @juliocamarero Please see my refactors in upstream. I wrote lots of messages to communicate future changes.

@fafonso It'd also be good to add a test for this. Please send a follow up test to replicate the bug that this fixes. Thx!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c101f8818b...0621052d5f

**Comment by shuyangzhou** [comment]
@fafonso I am doing a following up clean up to LanguageImpl to fix all the thread safety issues. Please hold until my changes go in, then continue with the test, otherwise there might be some conflicts.

**Comment by fafonso** [comment]
Tests implemented and in review.

**Pull request closed without merging**
