### PR TITLE
LPS-73915

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by NorbertKocsis** [comment]
Hi,

Sorry, I didn't realized someone fixed in the meantime on LPS-73272.

Br,
Norbert

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
HI @NorbertKocsis 

Are you sure you wanted to write LPS-73272? That ticket has nothing to do with LDAP. Can you please update it and close this one if it's already fixed by another ticket?

Thanks,
Tibi

**Comment by brianchandotcom** [comment]
@NorbertKocsis please resend with correct ticket? Thx.

**Pull request closed without merging**
