### PR TITLE
LPS-73723, LPS-73762

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-73723 and https://issues.liferay.com/browse/LPS-73762.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:reopen

**Comment by jonmak08** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e1e7bae679...954d49d02b

**Pull request closed without merging**
