### PR TITLE
LPS-60142 Unwrap control panel group back to fix the permission checks

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest @brianchiu is this a real test failure for poshi?

**Comment by brianchiu** [comment]
This shouldn't be a real test failure because more tests would have failed if that were the case.

@vicnate5 @ctampoya
Can you two look into this?

**Comment by brianchiu** [comment]
@evannagayama @brianwulbern

Can you resend this in the event it's not a real test failure?

**Comment by vicnate5** [comment]
@brianchiu This looks to be caused by https://issues.liferay.com/browse/LRQA-19152. Should pass on next run.

**Comment by brianchandotcom** [comment]
@vicnate5 any idea on how we're going to prevent these random failures?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e05c0fb121...32454e9e97

**Comment by vicnate5** [comment]
@brianchandotcom This is a question for @michaelhashimoto's team. The issue is being tracked at https://issues.liferay.com/browse/LRQA-19152.

**Pull request closed without merging**
