### PR TITLE
LPS-126305, LPS-126304, LPS-126292, LPS-126283 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-126283
https://issues.liferay.com/browse/LPS-126292
https://issues.liferay.com/browse/LPS-126304
https://issues.liferay.com/browse/LPS-126305

This is only for master.

@david-gutierrez-mesa
@alexcandidos

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure case is unrelated to changes in PR.
See https://github.com/liferay-echo/liferay-portal/pull/3603
✔️ ci:test:stable - 9 out of 9 jobs passed
❌ ci:test:relevant - 21 out of 26 jobs passed in 1 hour 58 minutes

**Comment by brianchandotcom** [comment]
@brunoquei2105 please review changes.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3ffd5f14b1...c898505757

**Pull request closed without merging**
