### PR TITLE
LPS-78876 Fix gradle file

### PR DESCRIPTION
**Pull request by pei-jung**
Hey Brian,

This fixes the failure in https://github.com/brianchandotcom/liferay-portal/pull/56306#issuecomment-374076567.

/cc @jpince

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@pei-jung thank you!

**Comment by jpince** [comment]
@arboliveira can you please look into this failure? I haven't seen it in other pulls, but it has nothing to do with Pei's changes, so I'm assuming it's failing at head.
`junit.framework.AssertionFailedError: Forbidden modules/private/apps/portal-search-elasticsearch6-xpack-monitoring/gradle.properties`

cc/ @xbrianlee @ithildir

**Comment by arboliveira** [comment]
On it.

cc/ @BryanEngler

**Comment by arboliveira** [comment]
https://github.com/brianchandotcom/liferay-portal-ee/pull/19618

Thanks @petershin!!  👍 👍

**Pull request closed without merging**
