### PR TITLE
Lps 70822

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@mtambara this is not friendly for backwards compatible. Imagine if I use just one Marketplace app that expects USER and not USER_ID. Unless that code is changed, I can never update this property in my other code.

Or worse, one app expects USER and another expects USER_ID.

Instead of having the property, set both attributes and we'll slowly move everyone toward USER.

Please resend. Thx.

**Comment by brianchandotcom** [comment]
@shuyangzhou see my comment. Didn't merge this.

**Comment by shuyangzhou** [comment]
@brianchandotcom the goal is to remove as many session attributes as possible to reduce the memory footprint, having them both will make things worse. If that's the case, it would be better to not change anything, that means we will get stuck on the duplicated session attributes info forever, as we can never assume third party code would change at all.

**Pull request closed without merging**
