### PR TITLE
Lps 92147

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3bbc29afa6...e715e88c99

**Comment by brianchandotcom** [comment]
@tinatian I backported to 7.1.x

Can we sort?

```
Bundle.STARTING | Bundle.ACTIVE
```

Please backport to 7.0.x if relevant (seems to be)

Thx

fyi @shuyangzhou

**Comment by tinatian** [comment]
@brianchandotcom 
Yes, we can sort, do you need me send a new pull?
Yes, need to backport 7.0.x, will send out a pull.

Tina.

**Comment by tinatian** [comment]
Please see https://github.com/brianchandotcom/liferay-portal-ee/pull/23537.

Tina

**Comment by tinatian** [comment]
Backport to 7.0.x resend at : https://github.com/brianchandotcom/liferay-portal-ee/pull/23538

**Pull request closed without merging**
