### PR TITLE
LPS-73189 Better naming

### PR DESCRIPTION
**Pull request by 4lejandrito**
@jkappler

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:test

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
ci:test can you take a look at the frontend tests? @jpince

**Comment by jpince** [comment]
@brianchandotcom failures are unrelated as far as I can tell. Brian Lee is looking into why CI is having trouble clicking on kebabs, the issue is not reproducible locally.

**Comment by brianchandotcom** [comment]
@4lejandrito can you resend this?

Please follow the pattern:

UnsafeFunction xyzUnsafeFunction

Thx.

**Pull request closed without merging**
