### PR TITLE
Lps 73327

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @ithildir

### CODE REVIEW

**Comment by Ithildir** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/49939/commits/9697e8590be666955bedf3a350d0d5de5ae9a138 doesn't have the correct LPS number in the `CHANGELOG.markdown` file. I'll fix it after this pull is merged, no problem 😊

**Comment by shuyangzhou** [comment]
@arboliveira elasticsearch has a lot of race conditions during shutdown, I think this would at least cover the one from yesterday for the jvm assert failure and the one now with the threadpool shutdown rejection error log during tomcat shutdown. I can only fix them by adding external synchronization points, which is not pretty and hard to maintain, if we have ways to contribute to their code, we can talk about it to do this in a more elegant way.

CC @mhan810

**Comment by shuyangzhou** [comment]
Thanks @Ithildir ! I did not notice there is one inside the markdown file, sorry about that.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4bc1fe5528...caad8c5d15

**Comment by arboliveira** [comment]
@shuyangzhou Elastic does not support Elasticsearch in embedded mode, and (sad to say) they already officially stated that contributions from the community intended to fix problems that only happen in embedded mode won't be accepted anymore.

**Comment by shuyangzhou** [comment]
@arboliveira this is not just for embedded mode, I am fixing it here because we only use embedded connection in our test, the issue is inside the shutdown process of Node.

**Comment by Ithildir** [comment]
ci:reopen

**Comment by Ithildir** [comment]
Sorry, I didn't know the pull was already merged!

**Pull request closed without merging**
