### PR TITLE
LPS-154730 | master

### PR DESCRIPTION
**Pull request by liuxingye**
## Main Objective
The main of this PR is to expose `externalReferenceCode` in DocumentsFolder. For that reason I have made some changes in the service part and in the API part.

## Service part
The main changes that you should review, are the following:

- Those changes related to `documentlibrary` in portal-impl. These changes are related because we add the new argument using `externalReferenceCode`.
- In the same way, in those modules I have implemented two new methods to obtain a DLFolder usign the `externalReferenceCode`, which are `fetchFolderByExteranlReferenceCode` and `getFolderByExteranlReferenceCode`.
- As there are some changes that affect the service part of DLFolder, I want to be sure that the Staging mode works correctly, some changes are added.
- New Upgrade process, if the `externalReferenceCode` is `null` or "", the data base will save the `externalReferenceCode` using the `UUID`.
- Update Poshi tests.
- Requested changes in: https://github.com/brianchandotcom/liferay-portal/pull/121934#issuecomment-1221215791
- Requested changes in: https://github.com/brianchandotcom/liferay-portal/pull/122794 (delete `addFolder` old method)

## API part
However, this part can be ignored, beause it is reviewed by our members of the team.

If you have any problem, or any doubt, please contact me :smiley: 

**JIRA TICKET**
https://issues.liferay.com/browse/LPS-154730

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:reopen

**Comment by liuxingye** [comment]
Forwarding this directly from https://github.com/liferay-lima/liferay-portal/pull/3495 since the failures are unrelated to the changes.

**Comment by sergiojimcos** [comment]
Closing this PR because it is outdated. Creating new one: https://github.com/brianchandotcom/liferay-portal/pull/124242

**Comment by sergiojimcos** [comment]
ci:close

**Pull request closed without merging**
