### PR TITLE
master-qa-17091

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LRQA-17091
https://issues.liferay.com/browse/LRQA-17100
https://issues.liferay.com/browse/LRQA-17066

CC @ZoltanTakacs Can we backport this to the 7.0.x branch when it goes in?

### CODE REVIEW

**Comment by ZoltanTakacs** [comment]
Hi @brianchiu,

Sure, when it gets committed I'll backport this. :)

Thanks,
Zoli

**Comment by brianchiu** [comment]
@ZoltanTakacs

Thanks! These commits are only frontend test fixes.

**Comment by brianchandotcom** [comment]
@brianchiu rebase error, please resend. Thx.

**Comment by ZoltanTakacs** [comment]
@brianchiu please mention me on the PR when you resend so I can include those commits in 7.0.x.

Thank you,

**Comment by brianchiu** [comment]
Thanks Zoli.

I've resent this in:
https://github.com/brianchandotcom/liferay-portal/pull/28904

**Pull request closed without merging**
