### PR TITLE
master-vw-412

### PR DESCRIPTION
**Pull request by vicnate5**
@brianchandotcom Can you please prioritize this pull as it is needed by support to deliver a patch to one of our customers

cc @zsagia @juliocamarero @brunobasto @thiago-rocha

### CODE REVIEW

**Comment by vicnate5** [comment]
@brunobasto Writing a poshi test for this would be really easy, but this looks like a case where we can just javascript test it (js might be faster and more reliable). What do you think?

**Comment by vicnate5** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@jasonpince @brianchiu can I merge this?

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@brianchandotcom 
From a poshi point of view, yes this is safe to merge.

There are two backend test failures with ConcurrentIncrement that look like this, but I have also seen it fail on other pulls.
```
junit.framework.AssertionFailedError: Thread Thread[liferay/hot_deploy-1,5,main] caught concurrent failure: java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.portal.kernel.messaging.SerialDestination, message=Unable to process message {destinationName=liferay/hot_deploy, response=null, responseDestinationName=null, responseId=null, payload=null, values={defaultLocale=en_US, groupId=0, command=deploy, companyId=20116, servletContextName=product-app-theme}}
	at com.liferay.portal.test.rule.callback.LogAssertionTestCallback.endAssert(LogAssertionTestCallback.java:101)
	at com.liferay.portal.test.rule.callback.LogAssertionTestCallback.afterClass(LogAssertionTestCallback.java:162)
	at com.liferay.portal.test.rule.callback.LogAssertionTestCallback.afterMethod(LogAssertionTestCallback.java:170)
	at com.liferay.portal.test.rule.callback.LogAssertionTestCallback.afterMethod(LogAssertionTestCallback.java:50)
	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:64)
	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:61)
	at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:81)
	at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:81)
	at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:81)
	at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:81)
	at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:81)
	at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:81)
	at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:81)
	at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:81)
	at com.liferay.portal.test.rule.LiferayIntegrationTestRule$1$1.evaluate(LiferayIntegrationTestRule.java:140)
	at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:81)
	at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:81)
```

**Comment by brianchandotcom** [comment]
@thiago-rocha I sent it back to @brunobasto 

can you guys resend it after reviewing https://github.com/brunobasto/liferay-portal/pull/647 ?

Thx.

**Pull request closed without merging**
