### PR TITLE
LPS-85726 avoid NPE return empty list

### PR DESCRIPTION
**Pull request by matethurzo**
@ChrisKian when merged please backport to the appropriate branches also highlighted in the LPS ticket: 7.0x, 7.1.x

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/04e480d71b...fbb6ae416e

**Comment by brianchandotcom** [comment]
@ChrisKian @matethurzo see my changes in upstream.

@ChrisKian please backport. Thx.

**Comment by brianchandotcom** [comment]
@ChrisKian @matethurzo had to roll it back

@anthony-chu told me it causes lots of frontend regressions, he can explain more.

**Comment by anthony-chu** [comment]
@matethurzo @ChrisKian

```
junit.framework.AssertionFailedError: 
Caught unexpected exception
java.lang.IllegalStateException: No current transaction executor
	at com.liferay.portal.dao.orm.hibernate.VerifySessionFactoryWrapper._verify(VerifySessionFactoryWrapper.java:127)
	at com.liferay.portal.dao.orm.hibernate.VerifySessionFactoryWrapper.openSession(VerifySessionFactoryWrapper.java:94)
	at com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl.openSession(BasePersistenceImpl.java:258)
	at com.liferay.portal.service.persistence.impl.WorkflowDefinitionLinkPersistenceImpl.countByG_C_C(WorkflowDefinitionLinkPersistenceImpl.java:1171)
	at com.liferay.portal.service.impl.WorkflowDefinitionLinkLocalServiceImpl.hasWorkflowDefinitionLink(WorkflowDefinitionLinkLocalServiceImpl.java:269)
	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:153)
	at com.liferay.portal.spring.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:55)
	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:130)
	at com.liferay.portal.spring.aop.ServiceBeanAopProxy.invoke(ServiceBeanAopProxy.java:123)
	at com.sun.proxy.$Proxy70.hasWorkflowDefinitionLink(Unknown Source)
	at com.liferay.portal.kernel.service.WorkflowDefinitionLinkLocalServiceUtil.hasWorkflowDefinitionLink(WorkflowDefinitionLinkLocalServiceUtil.java:351)
	at org.apache.jsp.edit_005farticle_jsp._jspService(edit_005farticle_jsp:614)
	at org.apache.ja...
```

An `IllegalStateException` was thrown when attempting to add a new Web Content article in the admin portlet.

**Comment by ChrisKian** [comment]
Resent with fixes.  See https://github.com/jonathanmccann/liferay-portal/pull/1702

**Pull request closed without merging**
