### PR TITLE
COMMERCE-10054

### PR DESCRIPTION
**Pull request by brianikim**
Resent from: https://github.com/brianchandotcom/liferay-portal/pull/130032

@brianchandotcom ,

> 
> https://issues.liferay.com/browse/COMMERCE-10054
> 
> Sending you this one directly from : https://github.com/brianikim/liferay-portal/pull/57
> 
> Could not go the forward route due to the POSHI changes causing rebase errors.
> 
> Included new commit for the teardown.

Sincerely,
Brian I. Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:reopen

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f3621aeef4...c9fca74eda

**Pull request closed without merging**
