### PR TITLE
#Ping [See description] LPS-56703 Document Library web module

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey Brian,

There's one strange case with this pull regarding format source. It will modify 2 init.jsp files and it will remove some imports and a variable. Both the imports and the variables are needed because otherwise you'll get a jspc error.
The place where those variables and imports are used is in a jspf file, so I guess that the format source it's failing when scanning/detecting usages in those jspf files. 

I'll send another pull tomorrow modifying the portletId and replacing the usages in portal. 

Thanks!

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @marcellustavares with this pull the jsps are in an OSGi module so I assume that you guys can declare the taglib and start using it using OSGi?

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by marcellustavares** [comment]
sure @sergiogonzalez, we'll update it as soon it gets merged. Thx

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8d2a931e9c...3517014bf1

**Comment by brianchandotcom** [comment]
@sergiogonzalez 

Bravo! I replayed this pull commit by commit and it was very easy to review. This is one of the best pulls by anyone that I've received this year.

1.) Regarding e47b744aea011fc07b3bace47eaaf6ae0b8914fb, see 6d87fc20c2a60e59c310e29f6b8f3d63da289c83

2.) Can you update VerifyProperties for the moved property "dl.display.templates.config" and "dl.temporary.file.entries.check.interval"

3.) I renamed DLSystemConfiguration to DLConfiguration. Did you have plans for a DLConfiguration already?

4.) Please apply LPS-57556, see ModuleServiceLifecycle and how it's used (or ask Miguel)

5.) SF picked up these errors:

```
     [java] missing language key: documents-and-media ./modules/apps/dynamic-data-mapping/dynamic-data-mapping-web/src/META-INF/resources/js/main.js
     [java] missing language key: there-are-no-documents-or-media-files-in-this-folder ./modules/apps/document-library/document-library-item-selector-web/src/META-INF/resources/documents.jsp
     [java] missing language key: documents-and-media ./modules/apps/site/site-admin-web/src/com/liferay/site/admin/web/servlet/taglib/ui/SiteDocumentsAndMediaFormNavigatorEntry.java
     [java] missing language key: default-workflow-for-this-folder-x ./modules/apps/journal/journal-web/src/META-INF/resources/edit_folder.jsp
     [java] missing language key: documents-and-media ./modules/apps/site/site-admin-web/src/META-INF/resources/site/documents_and_media.jsp
     [java] missing language key: documents-and-media ./portal-web/docroot/html/portlet/admin/server/file_uploads.jsp
```
I moved those keys back to core in 0e4e3c02b9ad60accd1b1af4225045341366d982

6.) Running ant build-lang in modules/apps/document-library/document-library-web also revealed

```
build-lang-cmd:
     [java] Loading jar:file:/Users/brian/dev/bundles/master/tomcat-7.0.62/webapps/ROOT/WEB-INF/lib/portal-impl.jar!/system.properties
     [java] Duplicate key num-of-documents
```

That key is in both the modules and in portal-impl, but is only used in modules. So I fixed that in 3517014bf19de47957248619f047ded9198e31a7

Thanks @sergiogonzalez please review my other changes. Great job on this pull.

**Pull request closed without merging**
