### PR TITLE
LPS-98114 Create proper "main" entry points in DDM package.json files

### PR DESCRIPTION
**Pull request by wincent**
Original goal here was to fix the non-standard entry points in two DDM "package.json" files, as explained in [LPS-98114](https://issues.liferay.com/browse/LPS-98114).

Along the way, however, I discovered other inconsistencies with the way we were importing compiled Soy files, and JS files in general, so I fixed those up and added a lint to prevent them from creeping back in again.

Tested here: https://github.com/wincent/liferay-portal/pull/127

### CODE REVIEW

**Comment by wincent** [comment]
@john-co: please let me know if you think anything looks off here with those "ci:test:relevant" failures — this is a rebase of [the one you checked out yesterday](https://github.com/wincent/liferay-portal/pull/127).

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

known test flakiness:
LRQA-55096
LRQA-50324

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bc1275dedf...9fa8357648

**Comment by brianchandotcom** [comment]
Woo hoo @wincent I love the way you're fixing and preventing.

@john-co please fix the flaky tests (wasting ppl's time).

**Comment by wincent** [comment]
Thanks for checking @john-co!

**Pull request closed without merging**
