### PR TITLE
LPS 104728

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/443018cc6c...d55f15d006

**Comment by brianchandotcom** [comment]
@julien can you sort these? or add line breaks?

```
@import './PageEditor';
@import './Sidebar';
@import './Toolbar';
@import './Topper';
@import './DragDrop';
@import './FloatingToolbar';
```

@wincent fyi see modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/App.scss

Can you enforce this somehow?

@julien also, see

```

import {BackgroundColorConfigurationPanel} from '../../../app/components/BackgroundColorConfigurationPanel';
import {LayoutBackgroundImageConfigurationPanel} from '../../../app/components/LayoutBackgroundImageConfigurationPanel';
import {SpacingConfigurationPanel} from '../../../app/components/SpacingConfigurationPanel';
import {LAYOUT_DATA_FLOATING_TOOLBAR_BUTTONS} from './layoutDataFloatingToolbarButtons';

```

in modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/config/constants/floatingToolbarConfigurations.js

Should that be sorted? Thx.

**Comment by wincent** [comment]
@brianchandotcom: We are currently prettifying (just visual formatting) but not linting (ie. sorting) in SCSS files. The ticket for that is https://issues.liferay.com/browse/IFI-956 — when we do this, we'll have to be quite conservative because order can affect the cascade.

About the sorting of the JS imports, they already are sorted: the sort key is the module name after the "from".

**Comment by julien** [comment]
@brianchandotcom until we have linting in master for SCSS files, I'll make sure we sort import in those files and also communicate it to the the rest of the team, Thanks.

/cc @p2kmgcl 
/cc @sandrodw3
/cc @victorg1991
/cc @matuzalemsteles
/cc @diegonvs
/cc @mateomustapic

**Pull request closed without merging**
