### PR TITLE
Lps 75874

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@lanceji92674957 please send me a backport.

@shuyangzhou fyi

**Comment by lanceji92674957** [comment]
done, please check https://github.com/brianchandotcom/liferay-portal-ee/pull/18909

**Pull request closed without merging**
