### PR TITLE
LPS-102645 React treeview

### PR DESCRIPTION
**Pull request by wincent**
This implements a new React-powered treeview component and uses it in asset-categories-selector-web. It is designed to be flexible enough to be used in various contexts, so we've moved it into a new module, frontend-js-components-web, where we will be accumulating components that are useful across liferay-portal, but which are higher-level than what we provide in Clay. Later PRs will use the component in more places.

Originally reviewed at: https://github.com/wincent/liferay-portal/pull/70 and https://github.com/jbalsas/liferay-portal/pull/2056

### CODE REVIEW

**Comment by sandrodw3** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchandotcom** [comment]
Very nice.. rebase error though , please resend. thx.

**Comment by jbalsas** [comment]
Hey @brianchandotcom, I've rebased this (added a little commit) and resent to https://github.com/brianchandotcom/liferay-portal/pull/81432 after testing it builds and works.

**Comment by john-co** [comment]
Hi @jbalsas,

I can't tell if this modules-unit-jdk8 test is related to the PR. I didn't see it on upstream test. We can see if it comes up again in #81432 

```
  [exec] com.liferay.asset.auto.tagger.google.cloud.natural.language.internal.util.GCloudNaturalLanguageUtilTest > testTruncateToSizeTextGreaterThanMaxWithTwoWordsSmallerThanSize FAILED
     [exec]     org.junit.ComparisonFailure: expected:< []> but was:< [ ]>
     [exec]         at org.junit.Assert.assertEquals(Assert.java:115)
     [exec]         at org.junit.Assert.assertEquals(Assert.java:144)
     [exec]         at com.liferay.asset.auto.tagger.google.cloud.natural.language.internal.util.GCloudNaturalLanguageUtilTest.testTruncateToSizeTextGreaterThanMaxWithTwoWordsSmallerThanSize(GCloudNaturalLanguageUtilTest.java:170)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
     [exec]         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
     [exec]         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
     [exec]         at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
     [exec]         at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]         at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
     [exec]         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
     [exec]         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
     [exec]         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
     [exec]         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
     [exec]         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
     [exec]         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
     [exec]         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
     [exec]         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:106)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
     [exec]         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
     [exec]         at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
     [exec]         at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
     [exec]         at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
     [exec]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:117)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
     [exec]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
     [exec]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
     [exec]         at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
     [exec]         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
     [exec]         at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
     [exec]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [exec]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [exec]         at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
     [exec]         at java.lang.Thread.run(Thread.java:745)
```

**Pull request closed without merging**
