### PR TITLE
LPS-92053 add support for arrays

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/db4cc6ccf4...7754dda87f

**Comment by brianchandotcom** [comment]
@nhpatt does this need to be ported to client_resource.ftl?

@ruben-pulido what's the status on the multipart? are you going to send me another pull on it? Just checking. Thx.

**Comment by brianchandotcom** [comment]
See 4a67fac261bd1b89e458742ecc3a061f441f1d75

**Comment by nhpatt** [comment]
Yeah, needs to be ported, will sent PR right now.

**Pull request closed without merging**
