### PR TITLE
LPS-63462 Not needed

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
this seems unrelated

**Comment by csierra** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@csierra can you resend on top of https://github.com/csierra/liferay-portal/pull/195

1.) I'd like to do the removal of % on *Configuration.java as a separate pull. Fix that first then send this complicated one, otherwise, ti's very hard to merge.

2.) for LanguageExtension, please fix "TODO" and also "String filter" should be String filterString"

Thx

**Pull request closed without merging**
