### PR TITLE
LPS-57676 update lexicon markup for product menu [PING]

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Weird that the CI is not testing this pull... @kiyoshilee any idea why?

**Comment by brianchandotcom** [comment]
nvm.. just took a few seconds to kick in @kiyoshilee

**Comment by juliocamarero** [comment]
@brianchandotcom it was being tested and the tests passed, but I just added 1 more commit and asked for the retest :+1:

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5cdd78dbd2...1c33bba439

**Comment by juliocamarero** [comment]
@ZoltanTakacs can we please backport this? thank you!

**Pull request closed without merging**
