### PR TITLE
LPS-59561 Update cache

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@csierra repeated test error.

**Comment by brianchandotcom** [comment]
actualy, ay be fixed in https://github.com/brianchandotcom/liferay-portal/pull/32851

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@csierra how come we're including just one class in BundleUtil?

We're going to deploy osgi-util. So I'd rather just name it as a depedency rather than manually including one class. Seems more brittle that way.

Can you resend and just declare a version that is needed for osgi-util? Thx.

**Comment by csierra** [comment]
hey @brianchandotcom,

we are including only some utility classes in other bundles. Since I did not know whether we were going to deploy osgi-util just now I opted to include the util class. Here I send you a new pull that deploys osgi-util https://github.com/brianchandotcom/liferay-portal/pull/32869

Bests.

**Pull request closed without merging**
