### PR TITLE
LPS-131054 Fix failing tests

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-131054

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:reopen

**Comment by austinchiang** [comment]
@brianchandotcom this fixes a blocker for the release. There was a commerce test failure blocking this pull from being forwarded but it's unrelated so I am sending this directly to you. Thanks!

@adolfopa

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/48d85e4101...6db2c45f06

**Comment by brianchandotcom** [comment]
@adolfopa see 6db2c45f06e4bf3a1982a1eb34467143ad490c37

1.) Do we need to delete the temp file?

File destinationFile = FileUtil.createTempFile(format);

2.)

Can you sort the usage?

```
"ffmpeg", "-y", "-i", file.getAbsolutePath(), "-b:a",
				String.valueOf(
					_getProperty(
						audioProperties,
						PropsKeys.DL_FILE_ENTRY_PREVIEW_AUDIO_BIT_RATE, format,
						_AUDIO_BIT_RATE_DEFAULT)),
				"-ar",
				String.valueOf(
					_getProperty(
						audioProperties,
						PropsKeys.DL_FILE_ENTRY_PREVIEW_AUDIO_SAMPLE_RATE,
						format, _AUDIO_SAMPLE_RATE_DEFAULT)),
				destinationFile.getAbsolutePath()));
```

by flag (alphabetically)

Thx

**Pull request closed without merging**
