### PR TITLE
LPS-67437 User with Site Member role cannot access private page, this…

### PR DESCRIPTION
**Pull request by Preston-Crary**
… should have been the Group classNameId not the UserGroup classNameId. I confused the UserGroup's template Group with the UserGroup's membership (aka Groups_UserGroups).

cc @shuyangzhou

### CODE REVIEW

**Comment by daledotshan** [comment]
Hey Brian,
Could you help to review this fix? it is for a ee customer
Thanks

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by mhan810** [comment]
@brianchandotcom the test failures are not related to this commit.  We need to merge this in for the next SP.  it's pretty severe

**Comment by brianchandotcom** [comment]
@mhan810 merged and backported

**Pull request closed without merging**
