### PR TITLE
LPS-160422 Move Container, Grid, Form and Collection Display fragments to backend

### PR DESCRIPTION
**Pull request by ozysouza**
https://issues.liferay.com/browse/LPS-160422

Previous PR: https://github.com/brianchandotcom/liferay-portal/pull/122093

See: https://github.com/brianchandotcom/liferay-portal/pull/122093#issuecomment-1225755766

cc: @sandrodw3

@lfbesada

### CODE REVIEW

**Comment by ozysouza** [comment]
ci:reopen

**Comment by ozysouza** [comment]
The tests stable and relevant passed but the CI doesn't sent it. I'm sending the PR directly.
See https://github.com/liferay-echo/liferay-portal/pull/9431#issuecomment-1228468051

:heavy_check_mark: ci:test:stable - 27 out of 27 jobs passed
:heavy_check_mark: ci:test:relevant - 182 out of 189 jobs passed in 2 hours 21 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c29bcb4182...b499020475

**Comment by brianchandotcom** [comment]
Thank you @lfbesada @ozysouza very consistent names now

**Pull request closed without merging**
