### PR TITLE
LPS-68359 Fix dependencies in intelliJ modules

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b8d4ba79cb...53e7910f74

**Comment by brianchandotcom** [comment]
@juliocamarero merged...

**Pull request closed without merging**
