### PR TITLE
LPS-66078 Fix other test

### PR DESCRIPTION
**Pull request by csierra**
/cc @topolik

### CODE REVIEW

**Comment by jhendley** [comment]
ci:stop - aborting last 4 AXIS due to Freeze in PACL Tests. Will analyze results when they come back.

**Comment by marcellustavares** [comment]
thanks @csierra, @topolik!

**Comment by brianchiu** [comment]
I'll take a look at this in the moment.

**Comment by brianchiu** [comment]
There doesn't seem to be a discernible reason why this build timed out. I'm going to try it again.

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
The time outs seemed to have happened on security tests.

```
    [junit] TEST com.liferay.portal.security.membershippolicy.UserGroupMembershipPolicyFactoryImplTest FAILED
    [junit] Running com.liferay.portal.security.pacl.PACLAggregateTest
    [junit] Testsuite: com.liferay.portal.security.pacl.PACLAggregateTest
    [junit] Running in CI mode with 2/5
    [junit] [PACLTestSuite]Loading jar:file:/opt/dev/projects/github/liferay-portal/portal-impl/portal-impl.jar!/system.properties[PACLTestSuite]
    [junit] [PACLTestSuite]Loading file:/opt/dev/projects/github/liferay-portal/portal-impl/test-classes/integration/system-ext.properties[PACLTestSuite]
    [junit] [PACLTestSuite]Loading jar:file:/opt/dev/projects/github/liferay-portal/portal-impl/portal-impl.jar!/portal.properties[PACLTestSuite]
    [junit] [PACLTestSuite]Loading file:/opt/dev/projects/github/liferay-portal/portal-test-integration/classes/com/liferay/portal/test/rule/pacl-test.properties[PACLTestSuite]
    [junit] [PACLTestSuite]Loading file:/opt/dev/projects/github/liferay-portal/portal-impl/test-classes/integration/portal-test.properties[PACLTestSuite]
    [junit] [PACLTestSuite]Loading file:/opt/dev/projects/github/liferay-portal/portal-impl/test-classes/integration/portal-test-ext.properties[PACLTestSuite]
    [junit] [PACLTestSuite]Loading file:/root/../opt/dev/projects/github/liferay-portal/portal-test-integration/classes/com/liferay/portal/test/rule/pacl-test.properties[PACLTestSuite]
    [junit] [PACLTestSuite]16:47:28,736 ERROR [main][DialectDetector:137] java.sql.SQLException: JZ006: Caught IOException: java.net.ConnectException: Connection refused
    [junit] java.sql.SQLException: JZ006: Caught IOException: java.net.ConnectException: Connection refused
```

**Comment by brianchiu** [comment]
@brianchandotcom 

This is safe to merge.

The reason why the time outs happened previously is because the tests were trying to connect to sybase but were unable to (for this I am not sure why).

However, on the retest, those PACL tests passed. So the sybase connection issue was a fluke.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d4285f0eac...51cf2abc78

**Comment by brianchandotcom** [comment]
@shuyangzhou fyi, regarding the sorting of resource action names.

**Pull request closed without merging**
