### PR TITLE
LPS-67367 us last forward request to avoid losing of friendly URL parameters

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
cc @ericyanLr

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by pavel-savinov** [comment]
CI does not work properly due to yesterday changes.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4780225b01...7af59e621e

**Comment by brianchandotcom** [comment]
@pavel-savinov I documented it in 7af59e621ecb42e6930edc7b61e84e057937bd3a

**Pull request closed without merging**
