### PR TITLE
LPD-1558 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ce4cc71aa2...03c6f52afe

**Comment by brianchandotcom** [comment]
@tinatian @jeffwu0724 see 03c6f52afea60ac9f72b82ddced373f341ce6860

Can you change

```
		if (cmd.equals("cacheDb") || cmd.equals("cacheMulti") ||
			cmd.equals("cacheServlet") || cmd.equals("cacheSingle") ||
			cmd.equals("cleanUpAddToPagePermissions") ||
			cmd.equals("cleanUpOrphanedPortletPreferences") ||
			cmd.equals("cleanUpLayoutRevisionPortletPreferences") ||
			cmd.startsWith("convertProcess.") ||
			cmd.equals("dlDeletePreviews") ||
			cmd.equals("dlGeneratePDFPreviews") || cmd.equals("gc") ||
			cmd.equals("runScript") || cmd.equals("shutdown") ||
			cmd.equals("threadDump") || cmd.equals("updateExternalServices") ||
			cmd.equals("updateMail") ||
			cmd.equals("verifyMembershipPolicies")) {

			CaptchaUtil.check(actionRequest);
		}
```

I'm afraid someone will add a new tab and not register it here.

I'd rather exclude than include what should be tested. It's safer that way. Thx.

**Comment by jeffwu0724** [comment]
Please also see https://github.com/brianchandotcom/liferay-portal/pull/148993

**Pull request closed without merging**
