### PR TITLE
LPS-59761 use attribute instead of custom js code

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @jbalsas

**Comment by juliocamarero** [comment]
@sergiogonzalez @marcellustavares we have removed all our calls to the Liferay.Util.openWindow method in order to avoid having js in our views. Now the taglib handles that.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3bd6b24068...208f83e5f2

**Comment by marcellustavares** [comment]
Thanks @juliocamarero, I was about to commit something using the old pattern :)

**Pull request closed without merging**
