### PR TITLE
LPS-64014 Fix references to packages in pre 7.0 upgrades

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/be0866e5df...2938db48d3

**Comment by adolfopa** [comment]
@brianchandotcom These test failures seem real. I think the changes in UpgradeCustomizablePortlets broke them (not sure why, though).

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/37346

**Pull request closed without merging**
