### PR TITLE
LPS-126353 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-126353

This is only for master.

@david-gutierrez-mesa
@alexcandidos

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure case is unrelated to changes in PR.
See https://github.com/liferay-echo/liferay-portal/pull/3581
✔️ ci:test:stable - 9 out of 9 jobs passed
❌ ci:test:relevant - 20 out of 25 jobs passed in 1 hour 53 minutes

**Comment by brianchandotcom** [comment]
@nicolas-sss please review changes.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/37225c438a...617ab87671

**Pull request closed without merging**
