### PR TITLE
LPS-161366 Fix Private Pages indexation when request or response is not available 

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-161366

Previous PR: https://github.com/brianchandotcom/liferay-portal/pull/122172
See: https://github.com/brianchandotcom/liferay-portal/pull/122172#issuecomment-1227288626

@brianchandotcom 

Thank you very much for this tip

> _If you're not sure what a var name should be, "git grep" that method and we've probably mocked it else where in the code base and you can hose those names._

Naming is so much easier that way and for sure the results will be better. ❤️

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:reopen

**Comment by dnebing** [comment]
Setting up the theme display is missing the use of the configuration details for the crawler as used here: https://github.com/liferay/liferay-portal/blob/master/modules/apps/layout/layout-impl/src/main/java/com/liferay/layout/internal/crawler/LayoutCrawlerImpl.java#L136-L146

The configuration overrides the defaults (i.e using https or not, protocol in the portal-ext.properties might be set to true when https is terminated at the web server, but tomcat itself may only be using http to access itself.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6ac6cc650b...7d3e0d616d

**Comment by brianchandotcom** [comment]
Thx @lfbesada ! See tiny change in 9c960606bd3ee0ba042547c4beb5b2ce16cd822f

Can you send a backport? Please send it to me directly and just ci reopen it. Thx.

**Pull request closed without merging**
