### PR TITLE
LPS-49566 Too late to get attributes

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by rotty3000** [comment]
Strangely the report for test-portal-acceptance-pullrequest-batch(master)/functional-tomcat8-mysql56-jdk7/24 actually shows SUCCESS as the final status.

**Comment by rotty3000** [comment]
same for https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=0,label_exp=!master/36046//console

**Comment by rotty3000** [comment]
apparently the full test run didn't finish... So ci:retest

**Comment by brianchiu** [comment]
I've turned off the CPMydashboard tests.

However, all 3 upgrade tests failed with this error:
```
BUILD FAILED
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-test-portal-acceptance-pullrequest-batch.xml:332: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-portal/build-test-batch.xml:783: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-portal/build-test-batch.xml:538: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-portal/build-test-batch.xml:483: /opt/dev/projects/github/liferay-portal/build-test-batch.xml:540: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-portal/build-test-batch.xml:233: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-portal/build-test-batch.xml:542: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:48: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:56: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-portal/build-test.xml:7390: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-portal/build-test.xml:7840: Upgrade timeout error!
```

This is the same failure as here:
https://github.com/brianchandotcom/liferay-portal/pull/38043

@michaelhashimoto

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d95c8ff7ac...e7b9cc5103

**Pull request closed without merging**
