### PR TITLE
LPS-110898

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@brianchandotcom, can we put something in place that catches the cases when your commits violate SF?
These happen a bit too frequent these days and are a pain for me, since my pulls are blocked by these...

**Comment by hhuijser** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/266e24f395...0a703614b5

**Comment by brianchandotcom** [comment]
Got it... thinking... I need to add it to my workflow...

**Comment by jpince** [comment]
@hhuijser not sure if you are already doing this, but you can also cherry-pick the SF fix commit on top of every pull you're sending that day. Git will know to remove it when BChan cherry-picks to his master branch.

**Pull request closed without merging**
