### PR TITLE
LPS-106199 Single experience mode

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
Thanks /cc @andresfulla @julien @p2kmgcl

**Comment by brianchandotcom** [comment]
@dgarciasarai rebase error, please resend.

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
@dgarciasarai see: https://github.com/brianchandotcom/liferay-portal/pull/83875

**Pull request closed without merging**
