### PR TITLE
LPS-107703 New APIs

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
//cc @ealonso

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/72ad7cd132...10e55fa091

**Comment by brianchandotcom** [comment]
@nhpatt @ruben-pulido ok, trusting you guys with all these names!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/10e55fa091...10e55fa091

**Comment by nhpatt** [comment]
Thanks!

**Pull request closed without merging**
