### PR TITLE
master-en-728

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LRQA-21576

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:stop

**Comment by michaelhashimoto** [comment]
I broke this build and am restarting it.

Sorry for the inconveniences.

ci:restart

**Comment by brianchandotcom** [comment]
@michaelhashimoto we have too much traffic.. so for these, I'm just bringing it in

ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/40a73e008c...122e320af6

**Pull request closed without merging**
