### PR TITLE
Lps 71925

### PR DESCRIPTION
**Pull request by shuyangzhou**
@brianchandotcom we changed to a different solution. Please let's know if you are ok with this.

### CODE REVIEW

**Comment by brianwulbern** [comment]
Not sure if it's related.  `modules-integration-sybase` tests failing on:

/cc @jpince
```
 [exec] 05:05:36,964 INFO  [localhost-startStop-1][BundleStartStopLogger:35] STARTED com.liferay.frontend.js.web_1.0.35 [323]
     [exec] 05:05:37,052 ERROR [localhost-startStop-1][com_liferay_frontend_taglib_form_navigator:97] BundleComponentActivator : Bundle [324] Unexpected failure enabling component holder com.liferay.frontend.taglib.form.navigator.internal.osgi.commands.FormNavigatorOSGiCommands 
     [exec] java.lang.IllegalStateException: The service has been unregistered
     [exec] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getReferenceImpl(ServiceRegistrationImpl.java:285)
     [exec] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getReference(ServiceRegistrationImpl.java:274)
     [exec] 	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceReference(SingleComponentManager.java:541)
     [exec] 	at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:321)
     [exec] 	at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:108)
     [exec] 	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:906)
     [exec] 	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:879)
     [exec] 	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:748)
     [exec] 	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:674)
     [exec] 	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:429)
     [exec] 	at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:657)
     [exec] 	at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:341)
     [exec] 	at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:403)
     [exec] 	at org.apache.felix.scr.impl.Activator.access$200(Activator.java:54)
     [exec] 	at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:278)
     [exec] 	at org.apache.felix.utils.extender.AbstractExtender.createExtension(AbstractExtender.java:259)
     [exec] 	at org.apache.felix.utils.extender.AbstractExtender.modifiedBundle(AbstractExtender.java:232)
     [exec] 	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:482)
     [exec] 	at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:1)
     [exec] 	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232)
     [exec] 	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:444)
     [exec] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:905)
     [exec] 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
     [exec] 	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:165)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:75)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:67)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:102)
     [exec] 	at org.eclipse.osgi.container.Module.publishEvent(Module.java:461)
     [exec] 	at org.eclipse.osgi.container.Module.start(Module.java:452)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:421)
     [exec] 	at com.liferay.portal.bootstrap.ModuleFrameworkImpl._startDynamicBundles(ModuleFrameworkImpl.java:1500)
     [exec] 	at com.liferay.portal.bootstrap.ModuleFrameworkImpl.startFramework(ModuleFrameworkImpl.java:415)
     [exec] 	at com.liferay.portal.module.framework.ModuleFrameworkUtilAdapter.startFramework(ModuleFrameworkUtilAdapter.java:99)
     [exec] 	at com.liferay.portal.spring.context.PortalContextLoaderListener.contextInitialized(PortalContextLoaderListener.java:255)
     [exec] 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812)
     [exec] 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255)
     [exec] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
     [exec] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
     [exec] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
     [exec] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
     [exec] 	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:585)
     [exec] 	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1794)
     [exec] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
     [exec] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [exec] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [exec] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [exec] 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by jpince** [comment]
@brianwulbern that issue should be fixed by https://github.com/brianchandotcom/liferay-portal/pull/48426

@brianchandotcom please revert https://github.com/liferay/liferay-portal/commit/725247edd8763d8c920d900c54131c02300669ef with these commits

**Comment by jpince** [comment]
@brianchandotcom please don't revert yet, Preston let me know the following:
> The problem is that the commerce module has columns that are over 30 characters in length on 7.0.x, which won't change until they run build-service, this fix just makes it so they can use a db-name element to build service
> they have not run build service
> or change the service.xml, so they're still over the 30 character limit

@ithildir @marco-leo can you build service after this has been merged? then we can revert https://github.com/liferay/liferay-portal/commit/725247edd8763d8c920d900c54131c02300669ef

**Comment by brianchandotcom** [comment]
@jpince this is merged now.

@ithildir can you guys regen? Thx.

**Pull request closed without merging**
