### PR TITLE
LRQA-22280 Wait before expanding panel

### PR DESCRIPTION
**Pull request by alee8888**

### CODE REVIEW

**Comment by alee8888** [comment]
This is a resend of https://github.com/brianchandotcom/liferay-portal/pull/36397.I checked the errors in the previous pull for PoshiRunner.test[CPMessageboards#MoveToRecycleBinMBThread] and it looks to be a fluke as that test has not previously failed. I will keep an eye out and make the test more robust if I see it come up again.

**Comment by alee8888** [comment]
Closing at potential test failure in Calendar#ViewCalendarTimeZoneDefaults

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f225411f2b...06689040b3

**Comment by brianchiu** [comment]
@alee8888 
Can you look at this pull more closely? The signs point to this pull as having caused the repeated calendar failures.

I've assigned this to you.
https://issues.liferay.com/browse/LRQA-22547

**Pull request closed without merging**
