### PR TITLE
LPS-102577 use body in batch

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by nhpatt** [comment]
Thanks!

**Comment by brianchandotcom** [comment]
Also, see e39c420501fa3e2577587125e489bcfaabf59004 it regenerated 

modules/apps/headless/headless-batch-engine/headless-batch-engine-impl/rest-openapi.yaml

Not sure if that is correct or not.

**Comment by nhpatt** [comment]
Yeah, it's Ok, the XML reader will convert it.

**Pull request closed without merging**
