### PR TITLE
LPS-63190 rename key

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Hey @pyoo47 is this error happening also in other pulls? the error is really weird to me... but it seems to happen consistently...

**Comment by pyoo47** [comment]
Julio, I think this error was happening late last week (Thursday or Friday?) but I only see it in this pull now. Let me see if I can find some examples from last week.

**Comment by pyoo47** [comment]
Here's one from 4 days ago that Andrea submitted.
https://github.com/brianchandotcom/liferay-portal/pull/36394

It looks like he closed this pull and resubmitted it
https://github.com/brianchandotcom/liferay-portal/pull/36395

The second pull did not have the errors.

**Comment by juliocamarero** [comment]
Hehe, the second pull had a very suspicious commit :)

https://github.com/Ithildir/liferay-portal/commit/88a19e5a89122230a0e077962c5ec9ddb77e47d0

**Comment by pyoo47** [comment]
You could try closing this pull and resending it. retest doesn't automatically rebase anymore unless you make a change to your branch.

**Comment by brianchandotcom** [comment]
@juliocamarero can you resend? Thx.

**Pull request closed without merging**
