### PR TITLE
LPS-60532 Fix bnd for users admin

### PR DESCRIPTION
**Pull request by matethurzo**
@brianchandotcom this was failing with poshi stuff earlier, but I managed to fix it. according to @cgoncas  there are some test failures but those are unrelated to this pull.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9fa28e629d...a413ae2f1f

**Comment by brianchandotcom** [comment]
Hey @matethurzo can you send a follow up pull and rename the *-service modules that do NOT have service.xml into *-impl. Please update bnd as well to reflect it.

That's our usual pattern. We usually only call something -service if it has service.xml in it. See document-library-repository-cmis-*

Thx

**Comment by matethurzo** [comment]
I was on vacation @brianchandotcom but I'll send the follow up pull soon.

**Pull request closed without merging**
