### PR TITLE
LPS-109082 Convert fragment fields of type HTML

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
//cc @ealonso

**Comment by ruben-pulido** [comment]
//cc @jkappler

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@ruben-pulido rebase error.

**Pull request closed without merging**
