### PR TITLE
Simpler SASS support in modules (only on those modules which really need Sass compilation process)

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
I'm half way done with a cleaner way of doing this. Will push it up tomorrow.

**Comment by brianchandotcom** [comment]
@migue @rotty3000

I put all the logic to do this automatically https://github.com/brianchandotcom/liferay-plugins/commit/856a9c3d4873424043781475ac27f8aa31911509

Please read the comments. It's just a temp hack but it automates everything. I wanted to do it automatically because some of the portlets, like social-*web have many css directories in them, and it was getting ugly.

Ray, I need your help to do it "right" as a BND plugin. I also need your help getting to work for bookmarks-web so we can gut out runtime CSS to SASS translation. I think it's a bug in BND.

@juliocamarero 

I pushed up the fix for portal master in 2d66e1092af4bb3eec845638d8a33232db93377c

If I broke it, please revert my changes and let me know how to reproduce them.

Thx everyone

**Comment by rotty3000** [comment]
>Ray, I need your help to do it "right" as a BND plugin. I also need your help getting to work for bookmarks-web so we can gut out runtime CSS to SASS translation. I think it's a bug in BND.

Can you explain what you mean here? What's the bnd bug?

**Comment by brianchandotcom** [comment]
Hey Ray,

So, when I run "ant jar" for quick-note-web, it is smart enough to to map /css/.sass-cached/ to /css/

So when I open up the output jar, and look at /css/main.css, it is the translated version.

Now, when I do the exact same thing for bookmarks-web, it doesn't work. Why is it supposed to work?

I use the exact same way of manipulating Include-Resource to add the mappings at the very end, but because bookmarks-web is a "-wab", it must have another process that shoves the contents of docroot back in and overwrites my Include-Resource.

So this makes me think it's a bug in Bnd. I can show you over Skype if it doesn't make sense. Feel free to ping me. Thx bro.

**Comment by rotty3000** [comment]
It's not a bug.. bnd simply was not told to copy all resources into the
bundle.

**Pull request closed without merging**
