### PR TITLE
LPS-74571 Management Bar Collapse with dropdowns should be clickable in mobile

### PR DESCRIPTION
**Pull request by robframpton**
/cc @pat270 @jbalsas

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:reopen

**Comment by jbalsas** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Can you fix the comments?

```
@import "components/_navigation-bar";
@import "components/_management-bar"; // Should win over Navs and Navbar
@import "components/_multi-step-nav";
```

We always alphabetize and use line breaks to show that kind of info.

Thx

**Pull request closed without merging**
