### PR TITLE
LPS-61129 ant format-source

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/78d30f5028...71ca6f9cee

**Comment by brianchandotcom** [comment]
@marcellustavares didn't you make something similar to this? See ContextUserReplace/ContextUserReplacer

Perhaps your tests could use it too

Thx

**Comment by marcellustavares** [comment]
Sure thing, thanks @brianchandotcom!

**Pull request closed without merging**
