### PR TITLE
Lps 108310

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/39debb141c...9d2a5069b0

**Comment by brianchandotcom** [comment]
@arboliveira @BryanEngler 

@tinatian can you document in the LPS the purpose of this? Thx!

**Comment by BryanEngler** [comment]
im not sure that i agree with this... i think it should be up to the api consumer to decide exactly what settings are used to create the index. andre?

**Comment by arboliveira** [comment]
@tinatian, @shuyangzhou, I'm afraid @BryanEngler is right... we need to revert. Please see my comments at: https://issues.liferay.com/browse/LPS-108310?focusedCommentId=2079218&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2079218

**Comment by tinatian** [comment]
Sent revert pull here https://github.com/brianchandotcom/liferay-portal/pull/84569

**Pull request closed without merging**
