### PR TITLE
LPS-178565 AddFieldInHeadlessMyUserNotification - revert

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
This PR revert the changes made on https://github.com/liferay-lima/liferay-portal/pull/4109 to remove the unwanted field

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:open

**Comment by AliciaGarciaGarcia** [comment]
ci:reopen

**Comment by AliciaGarciaGarcia** [comment]
Hi @brianchandotcom 

As the team talked with you, this is the revert asked

Thanks!!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d364222f54...648743181f

**Pull request closed without merging**
