### PR TITLE
LPS-60642 support for control menu in velociy

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @jbalsas @natecavanaugh

**Comment by brianchandotcom** [comment]
ci:retest not sure why addSiteRole broke

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ff02ecf071...903ed58a01

**Comment by brianchandotcom** [comment]
@juliocamarero can you resend 903ed58a0109c977f28df5e378b972b7bf41c32f to jim hinkey? It didn't sound right to me. Thx.

**Comment by juliocamarero** [comment]
https://github.com/jhinkey/liferay-portal/pull/319

**Pull request closed without merging**
