### PR TITLE
LPS-86335

### PR DESCRIPTION
**Pull request by Preston-Crary**
CC @4lejandrito @adolfopa

@brianchandotcom I think it's okay for sharing to use the .security.permission package.  If they were extending or using portal-kernel's .security.permission.resource API I would say to put it there but this is a whole separate API.

The current design is to create java code to map the different services permissions using in memory maps and wrapping the permission logic, see DLFileEntrySharingPermissionChecker.  If sharing is only going to be for document library then this is good enough.

But if we plan on doing this for multiple modules I think a better design would be to just interact with the ResourcePermission API and have an update and reset implementation for sharing (copy the changes made to the ResourcePermission into a sharing table, updating the ResourcePermission table and undo the change when sharing expires or is revoked).  Doing it this way would mean you could share anything with permissions.

These are some small changes I made while reading the code in the pull.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/581d4d71ee...01665f3590

**Comment by brianchandotcom** [comment]
Thank you @Preston-Crary ! @4lejandrito @adolfopa please review. Thx.

**Comment by 4lejandrito** [comment]
Hi @Preston-Crary,

Thanks for your feedback. 

The Sharing API is intended to be used by different modules in the future therefore I agree with you. The permissions logic should be handled in a more generic way to make it as transparent as possible. 

However, as far as I understand, the ResourcePermission API is **role** based and what we need is a **user** based check. We want to know if a specific user can perform an action on a specific resource. I don't see how we could leverage the current ResourcePermission table for that.

I've been having a look at the code and [this](https://github.com/liferay/liferay-portal/blob/3638a992b8125be842a132ce2e1f251086f559d2/portal-impl/src/com/liferay/portal/service/impl/ResourceLocalServiceImpl.java#L408-L407) looks like a good place to add the extension. At that point we have the userId and we could query our SharingEntry table. I am not very familiar with how permissions work at a low level so I am sure I am missing something. 

It'd be very helpful if you could help us provide a cleaner implementation for this. I know Sergio considered different options and ended up implementing it the way it is for a good reason but sadly he is no longer in the company :(

**Comment by Preston-Crary** [comment]
Hi @4lejandrito,

I'll send you an email about this, we can try to come up with a better solution there.

**Pull request closed without merging**
