### PR TITLE
LPS-166930 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-166930

This is only for master.

@p2kmgcl
cc @alessandromalves

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.
See https://github.com/liferay-echo/liferay-portal/pull/10495
ci:test:stable - 25 out of 27 jobs passed
ci:test:relevant - 44 out of 49 jobs passed in 1 hour 6 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/68fb637b78...b69bd6a04f

**Comment by brianchandotcom** [comment]
@p2kmgcl fyi b69bd6a04fa27629d64448389d92bf7743e4b008

@ling-alan-huang please enforce b69bd6a04fa27629d64448389d92bf7743e4b008

**Pull request closed without merging**
