### PR TITLE
LPS-115687 | master

### PR DESCRIPTION
**Pull request by vicnate5**
From https://github.com/shuyangzhou/liferay-portal/pull/9176, no unique failures

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9bc648d2ad...12b79e73cd

**Comment by brianchandotcom** [comment]
@tinatian you need to add checks in the Service Builder FTL to only remove the check for 7_3_0 and above.

Otherwise, the generated code will get backported to 7.2.x and 7.1.x and 7.0.x.

Please resend directly to me.

**Comment by brianchandotcom** [comment]
@vicnate5 @shuyangzhou see comment above.

**Comment by brianchandotcom** [comment]
@tinatian see "serviceBuilder.isVersionGTE_7_3_0" in

src/main/resources/com/liferay/portal/tools/service/builder/dependencies/service_base_impl.ftl

**Comment by tinatian** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/90481

**Pull request closed without merging**
