### PR TITLE
LPS-64961

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:stop

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e60044dbfd...2279b981f7

**Pull request closed without merging**
