### PR TITLE
LPS-104274 Fetch loop-independent variables only once

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@ealonso can you rename

javax.portlet.Portlet portlet

to

javax.portlet.Portlet jxPortlet

since we also have

Portlet portle

in the same class. That's our usual pattern.

git grep " = jxP" **.java

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Pull request closed without merging**
