### PR TITLE
LPS-160028 AC Segments are not being sync with DXP

### PR DESCRIPTION
**Pull request by cgoncas**
Motivation
=======
AC Segments are not being sync with DXP[Link to story or ticket](https://issues.liferay.com/browse/LPS-160028)

Proposed Solution
========
We need to set **CheckIndividualSegmentsMessageListener** as **immediate**.

There is no tracker/service looking for this message listener, so as no other OSGi service looks up for it,  it never activates, so the Job that syncs the AC segments is never registered.

Steps to Verify:
----------------
1. Create a Segment at AC
1. Update synchronization time to 1 minute
1. Check segment's admin
1. The segment should be visible in DXP after 1 minute

Notes:
----------------

No integration test has been included, since we can't test that the job is correctly executed.

Original PR: https://github.com/liferay-tango/liferay-portal/pull/3133
Failing tests not related with this PR, that is the reason we are sending directly to Brian.

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8e451bf5b4...b6ec29885b

**Comment by brianchandotcom** [comment]
@shuyangzhou fyi on immediate

**Comment by shuyangzhou** [comment]
@RenanUmV this is from https://github.com/liferay/liferay-portal/commit/4e921ead , please make sure to single out all MessageListener changes to a separated commit, that way this can be easily caught during review.
CC @rafaprax

**Pull request closed without merging**
