### PR TITLE
pr-290_noornajj_LPS-162885

### PR DESCRIPTION
**Pull request by suilin**
https://issues.liferay.com/browse/LPS-162885
https://issues.liferay.com/browse/LPS-163875

### CODE REVIEW

**Comment by suilin** [comment]
ci:reopen

**Comment by suilin** [comment]
Forward it directly due to https://github.com/liferay-publications/liferay-portal/pull/274#issuecomment-1257528297 the relevant failures are not related to the changes, thanks.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a8618ccbb6...93cf31854e

**Comment by brianchandotcom** [comment]
@suilin @noornajj this needs an integration OR poshi test.

Please send a follow up PR.

**Pull request closed without merging**
