### PR TITLE
LPS-82609 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-82609

### CODE REVIEW

**Comment by kyle-miho** [comment]
@ealonso @p2kmgcl

**Comment by kyle-miho** [comment]
backport to `7.1.x` -> [brianchandotcom/liferay-portal-ee #20577](https://github.com/brianchandotcom/liferay-portal-ee/pull/20577)

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
Backport is good. Thanks @kyle-miho

**Pull request closed without merging**
