### PR TITLE
LPS-99067 Allow import LayoutPageTemplateEntry when is Created as New

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a450b7bea7...4580814503

**Comment by brianchandotcom** [comment]
@hhuijser can you fix this in LayoutPageTemplateEntryStagedModelDataHandler.java:

```

				if ((existingLayoutPageTemplateEntry.
						getLayoutPageTemplateEntryId() !=
							importedLayoutPageTemplateEntry.
								getLayoutPageTemplateEntryId()) &&
```

Too nested.

**Comment by brianchandotcom** [comment]
lbm:backport @CsabaTurcsan @jpince @zsoltbalogh

**Pull request closed without merging**
