### PR TITLE
LPS-61795 SF

### PR DESCRIPTION
**Pull request by matethurzo**
Rebased and re-sent, cc @topolik

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:retest

**Comment by juangon** [comment]
ci:retest

**Comment by topolik** [comment]
Hi @brianchandotcom,

I know you are good at reading code, however I add a bit of information to clarify the things.

This is a second part of local staging permissions fixes you reviewed a couple months ago (https://github.com/topolik/liferay-portal/pull/228), you asked to move it into a module. You merged the first part here: https://github.com/brianchandotcom/liferay-portal/pull/34136

In local staging we use always live groupId for permission checking.
=> Based on a discussion with Ray, any Group related roles and site/organization/UserGroup assignments must be done using live groupId, otherwise permission framework won't find them.

(1) The core idea is to make sure API consumers use live groupId for roles assignments and site/organization/UserGroup/Role memberships. 
(2) Next idea is to harden portal framework instead of fixing portlets and API consumers.

A commit by commit explanation:

**LPS-61795 Move existing user/organization/user-group assignments (9670498)**

A VerifyProces that rewrites existing staging groupIds into live groupIds in Organization,Site,UserGroup and Role.

**LPS-61795 Fix ULSI to allow advices to intercept the calls (359e786)**

Make sure the call goes through advices stack

**LPS-61795 Create Spring advices around portal API (98291a0)**

Advices to replace groupId in portal API calls.

`LiveGroupStagingAdvice` is a parent for all advices which:
1, when invoked, iterates over registered *LocalService methods to replace the groupId, if needed
2, registers *LocalService methods that were generated by ServiceBuilder and are related to Group entity
3, supports registering of custom methods that developers introduced

The other `*StagingAdvices` implementations provide details about respective LocalService methods to register.

If a method doesn't exist an exception is thrown in runtime during advices initialization.

**LPS-61795 Poor man coverage check to warn developers (b82d761)**

Processes the related `LocalService`s and checks if there is a method we forget to cover or is a new one.

Also throws a runtime exception during advices initialization.

**LPS-61795 (1) First remove roles relations and after then the group … (a29c1cf)**

Bug fix - avoid NPE caused by incorrect order of entities removal.

**LPS-61795 Register Spring Advices onto corresponding Spring services (5113c01)**

This was a hard one because we don't have any support for portal advices in modules.

Basically hooks into each `LocalService` proxy to add the new advice.

**SF by Mate**

Made my code almost perfect :)

HTH. Thanks!

**Comment by topolik** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Rebase error, please resend.

**Comment by topolik** [comment]
Hi @matethurzo, 

I'm first, I won! I take it and rebase ;)

Thanks.

**Comment by topolik** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/35810. Thanks.

**Pull request closed without merging**
