### PR TITLE
LPS-73070

### PR DESCRIPTION
**Pull request by Ithildir**
Hi,
Please let this pull finish.

Thank you!

Rebased on top of https://github.com/brianchandotcom/liferay-portal/pull/51228 to avoid conflicts.

cc @jbalsas, @robert-frampton

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c44d4d20cd...275ecb69d9

**Comment by brianchandotcom** [comment]
@jbalsas @Robert-Frampton I need you guys to backport 17db82bce294ae5274cb39afd961b356234b42ac to 137a98b37c1829b61f48ca665ec1edea060547de

I only backported the Gradle changes.

Thx.

**Comment by jbalsas** [comment]
Hey @brianchandotcom, we are still sending bits of this story. It's also not clear if we should backport all of it or not. I'll think about it once it's completely and everything has been merged and backport if appropriate.

Thanks!

**Pull request closed without merging**
