### PR TITLE
LPD-20211 OAuth 2.0 callback URI reseted in a LXC SaaS

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:reopen

**Comment by rotty3000** [comment]
@brianchandotcom this is needed for SaaS and it should be backported, though it should be accompanied by LPD-17826 in that case.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/59566644cd...4c473fafa2

**Comment by brianchandotcom** [comment]
@rotty3000 see 658f5f1852411814792a2c07eae289d2d9d2becc and 4c473fafa2033239d673eacdc4a93be410c4b448

**Pull request closed without merging**
