### PR TITLE
LPS-56932 create 2 new type of columns for search container: icon and image

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cf41813ec2...29d70169ca

**Comment by brianchandotcom** [comment]
@juliocamarero please see my changes in upstream. Thx.

**Pull request closed without merging**
