### PR TITLE
LPS-69285 fix wrong groupId

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:reopen

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@juliocamarero @dustinryerson @Alec-Shay see 0c8b7dc2a1f9a9e3db7bb2a6c63cb653aa9a4803

**Pull request closed without merging**
