### PR TITLE
LPS-124898 OIDC reimplement refresh token mechanism

### PR DESCRIPTION
**Pull request by arthurchan35**
Passed manual test.

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@arthurchan35 @stian-sigvartsen any way to send this in layers? So big...

Ideally, service.xml for new modules

and then rename things 

For example, if

modules/apps/portal-security-sso/portal-security-sso-openid-connect-impl/src/main/java/com/liferay/portal/security/sso/openid/connect/internal/OpenIdConnectServiceHandlerImpl.java

and

modules/apps/portal-security-sso/portal-security-sso-openid-connect-impl/src/main/java/com/liferay/portal/security/sso/openid/connect/internal/OpenIdConnectAuthenticationHandlerImpl.java


are similar, it's faster for me to review if I see it as a rename vs. Git showing me as an add/delete right now.

We really need to chunk this down so that I can merge this.

Thx.

**Comment by brianchandotcom** [comment]
@arthurchan35 @stian-sigvartsen also, 

should be

UnsafeConsumer<Long, Exception> userIdUnsafeConsumer

instead of

UnsafeConsumer<Long, Exception> userIdConsumer

**Pull request closed without merging**
