### PR TITLE
COMMERCE 1489 1

### PR DESCRIPTION
**Pull request by ivicac**
master

### CODE REVIEW

**Comment by ivicac** [comment]
ci:reopen

**Comment by ivicac** [comment]
ci:test:sf

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5d5c45e088...1487c65cb3

**Comment by brianchandotcom** [comment]
@ivicac @CrescenzoRegaLF see 6eda30203fb63ea2d2c817764766cf1eeb969ceb and b538345d607185126630a9da7a9c89a4708d6353

**Pull request closed without merging**
