### PR TITLE
OAUTH2-144 Semver

### PR DESCRIPTION
**Pull request by csierra**
/cc @topolik

### CODE REVIEW

**Comment by csierra** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@topolik @csierra see 60cb8412d0a80d8a31f9ba450def871547e60bab

Thx!

**Comment by topolik** [comment]
Whops, didn't know about this. Thanks @brianchandotcom !

**Pull request closed without merging**
