### PR TITLE
LPS-91420

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@crodriguezy, this one should fix LPS-91485

@brianchandotcom, need to publish SF only

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
@jpince `apps:headless:headless` error seems to show up in other pulls as well: https://github.com/brianchandotcom/liferay-portal/pull/68937

**Comment by brianchandotcom** [comment]
ok, only published SF.

**Pull request closed without merging**
