### PR TITLE
LPS-118339 Fix harmless typo in regex pattern match

### PR DESCRIPTION
**Pull request by wincent**
This was a copy-paste error from another place where we had this pattern:

    /\.tsx?$/

(ie. to match ".ts" or ".tsx"). We deleted the "x" because this module only has ".ts" files, but we should have deleted the "?" as well, otherwise the pattern matches both ".ts" and ".t" (the latter of which is not a valid extension).

### CODE REVIEW

**Comment by wincent** [comment]
Sorry, wrong fork, will re-send via liferay-frontend.

**Comment by martamedio** [comment]
@wincent What a shame! It's PR number 100000, it would have been nice to see it merged 😝

**Comment by brianchandotcom** [comment]
@wincent you were pull 100000!

**Comment by wincent** [comment]
Could be luck, could be skill... could be cheating! Hard to say... 🤔

**Pull request closed without merging**
