### PR TITLE
LPS-94646 Regenerates lock file

### PR DESCRIPTION
**Pull request by jbalsas**
/cc @arboliveira

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by jpince** [comment]
@john-co js-unit. not sure if it's cause by this pull

**Comment by john-co** [comment]
@jpince reviewing

**Pull request closed without merging**
