### PR TITLE
LRQA-32083 | master

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-32083

See corresponding ee-7.0.x changes [here](https://github.com/brianchandotcom/liferay-portal-ee/pull/16764).

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ba90e1e548...da2b5575f5

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
@xbrianlee can you backport this to ee-7.0.x? I assume you notified @shuyangzhou about reverting his SPA change in build-test.xml? Thx.

**Comment by xbrianlee** [comment]
@brianchandotcom I sent the ee-7.0.x backport [here](https://github.com/brianchandotcom/liferay-portal-ee/pull/16764).
We agreed on reverting his SPA change since it doesn't effect the functional test timeouts we've been seeing on the EE PR tester. We'll be discussing with QA Engineering about increasing the POSHI timeout to prevent the timeouts instead.

**Pull request closed without merging**
