### PR TITLE
LPS-103409 Regen

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
@jpince could you please confirm if these errors are unique to this PR? Thanks!

**Comment by jpince** [comment]
@epgarcia I asked QA for help https://liferay.slack.com/archives/CL84ZPHAT/p1572457359129500

**Comment by patriciajeanperez** [comment]
Failures are unrelated :) @epgarcia

**Comment by brianchandotcom** [comment]
@epgarcia can you resend, rebase error. Thx.

**Pull request closed without merging**
