### PR TITLE
LPS-74544

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
@pyoo47, it's complaining about violations in `master-private`, but I had a list of exceptions committed there: https://github.com/brianchandotcom/liferay-portal-ee/commit/798291a62de1bebfccb57f55853fad05be8acb94

So either, it's not taking latest `master-private` or that file is not being copied over?

You know what's going on?

**Comment by brianchandotcom** [comment]
@hhuijser may be I didn't update the hash to master-private? I'm going to do that now then. Merged.

**Comment by pyoo47** [comment]
@hhuijser @brianchandotcom Brian is correct, the sha for master-private that was used at the time did not contain source-formatter-api-signature-check-exceptions.txt.

**Comment by pyoo47** [comment]
ci:test:sf

**Pull request closed without merging**
