### PR TITLE
LPS-85711 Fix integration tests

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by jpince** [comment]
ci:close @kyle-miho @brianchiu the breadcrumb tests have similar failures, might need a TF?
Breadcrumb#DisableShowCurrentSite
`Element is not present at "//li[contains(@class,'list-group-item')][div/h4[normalize-space()='Parent Page Name']]//a[*[name()='svg'][contains(@class,'icon-plus')]]"`
Breadcrumb#DisableShowPage
`Element is not present at "//li[contains(@class,'list-group-item')][div/h4[normalize-space()='Welcome']]//a[*[name()='svg'][contains(@class,'icon-plus')]]"`

the other test failures look unrelated, but please verify :)

**Comment by jpince** [comment]
ci:reopen nevermind, I see the breadcrumb failures in this pull, too https://github.com/brianchandotcom/liferay-portal/pull/63841#issuecomment-427308386

**Comment by brianchiu** [comment]
We'll take a look

**Comment by brianchiu** [comment]
The other test failures do look unrelated (they have to do with the sign in button again).

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b48f8ed5ad...3030d82d94

**Pull request closed without merging**
