### PR TITLE
LRCI-2052 Add test suites for portal releases | master

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-2052

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:reopen

**Comment by michaelhashimoto** [comment]
@brianchandotcom - I wanted to save resource, so I just sent it directly to you.

**Comment by brianchandotcom** [comment]
Thx @michaelhashimoto !

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9c0925aba7...564b142778

**Pull request closed without merging**
