### PR TITLE
LPS-104107 Use default values in case when type options don't exist

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
@brianchandotcom @jpince Exactly the same branch passes ci:stable and ci:relevant here https://github.com/pavel-savinov/liferay-portal/pull/483
We really have to do something with our CI.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@pavel-savinov thanks for letting me know it passed in your branch. we're having some flaky network issues because we upgraded it over the new year.

**Pull request closed without merging**
