### PR TITLE
LPS-70052

### PR DESCRIPTION
**Pull request by matethurzo**
@brianchandotcom this is reverting something I've done earlier, because it's breaking SB on 7.0.x. After the revert, I'll do a different solution.

### CODE REVIEW

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
@matethurzo not sure why it's failing, but I don't see this error in other master pulls.

Closing this pull.

**Comment by jpince** [comment]
ci:close

**Comment by matethurzo** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
ci:stop

**Comment by jpince** [comment]
@matethurzo ok, I see what you mean. Your changes for journal are in central https://github.com/liferay/liferay-portal/commit/379e75c57dc2c7185b573eafcb5de8e99c081d65, but dynamic-data-mapping has not yet been updated.

@marcellustavares @leodb @vicnate5 are you guys able to push https://github.com/liferay/com-liferay-dynamic-data-mapping to master so this pull can pass? thanks!

**Comment by brianchandotcom** [comment]
Please resend after subrepos are done. Or else I won't be able to take in any other pulls.

**Comment by brianchandotcom** [comment]
@matethurzo merged.

**Comment by matethurzo** [comment]
@brianchandotcom i was about to check if the subrepos has been merged, and noticed your comment. Saved me some work! Thank you!

**Pull request closed without merging**
