### PR TITLE
LPS-61319 Users in a User Group do not inherit role permissions

### PR DESCRIPTION
**Pull request by topolik**
Hi Brian,

https://issues.liferay.com/browse/LPS-61319

Reviewed by @@drewbrokke and @pei-jung.

Thanks.

/cc @JorgeFerrer

### CODE REVIEW

**Comment by drewbrokke** [comment]
@brianchandotcom @topolik the only addition I would make is to add a test or two to ensure that UserGroup permissions are indeed honored.  That way we can avoid this kind of regression in the future.

**Comment by brianchandotcom** [comment]
@topolik please rebase and resend so I have test results. Thx.

**Comment by topolik** [comment]
@drewbrokke There is a test for it, it was removed together with the functionality. We cannot avoid this kind of regression in the future :)

**Comment by topolik** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/42249. Thanks.

**Pull request closed without merging**
