### PR TITLE
LPS-73367

### PR DESCRIPTION
**Pull request by adolfopa**
@brianchandotcom This is related to LPS-73131. I'll backport this to EE when it gets merged.

### CODE REVIEW

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by adolfopa** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/39ca22ad51...ffb2cea752

**Comment by brianchandotcom** [comment]
@adolfopa please backport? Thx.

**Pull request closed without merging**
