### PR TITLE
Lps 66470

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
@shuyangzhou 

Should

```
			if (_log.isInfoEnabled()) {
				_log.info("Error opening connection", e);
			}
```

be a log.error? I left it as info but reworded the comment.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2374dd7644...3852cb473e

**Comment by shuyangzhou** [comment]
Yeah, should be error. Want to me change it?

**Comment by shuyangzhou** [comment]
Sent at https://github.com/brianchandotcom/liferay-portal/pull/40618

**Pull request closed without merging**
