### PR TITLE
LPS-83662 Use ActionableDynamicQuery instead of traversing through the KaleoTaskAssignments

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
@drewbrokke FYI

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e06fd208b2...586376826c

**Comment by brianchandotcom** [comment]
@jeyvison Please send a backport to support for 7.1.x and 7.0.x (like our normal support workflow). I'm no longer auto backporting pulls like this.

@jhendley @liferay @zsoltbalogh FYI.

Merged into master only.

**Pull request closed without merging**
