### PR TITLE
LPS-85828 Create custom action: change transition

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:test

**Comment by nhpatt** [comment]
ci:stop

**Comment by nhpatt** [comment]
ci:stop

**Comment by nhpatt** [comment]
ci:test:sf

**Comment by nhpatt** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0023ec392d...0941e2e74c

**Comment by nhpatt** [comment]
Thanks! :D

**Pull request closed without merging**
