### PR TITLE
LPS-93537 Autogenerated

### PR DESCRIPTION
**Pull request by victorg1991**
Hey @brianchandotcom 

Here is the follow-up PR about the test problems for User. Now I made the tests a bit stronger because previously it failed if you already had a user created in the system

### CODE REVIEW

**Comment by jpince** [comment]
@victorg1991 @nhpatt failure in `headless-foundation-test:compileTestIntegrationJava`, looks like [some lines were deleted](https://github.com/brianchandotcom/liferay-portal/pull/71340/files#diff-3d8206f2a51ac2682f2b43c1b2a9ad6dL850), causing issues in the overrides in [OrganizationResourceTest.java](https://github.com/liferay/liferay-portal/blob/master/modules/apps/headless/headless-foundation/headless-foundation-test/src/testIntegration/java/com/liferay/headless/foundation/resource/v1_0/test/OrganizationResourceTest.java#L106-L114)
```
     [exec] > Task :apps:headless:headless-foundation:headless-foundation-test:compileTestIntegrationJava
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/headless/headless-foundation/headless-foundation-test/src/testIntegration/java/com/liferay/headless/foundation/resource/v1_0/test/OrganizationResourceTest.java:105: error: method does not override or implement a method from a supertype
     [exec] 	@Override
     [exec] 	^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/headless/headless-foundation/headless-foundation-test/src/testIntegration/java/com/liferay/headless/foundation/resource/v1_0/test/OrganizationResourceTest.java:113: error: method does not override or implement a method from a supertype
     [exec] 	@Override
     [exec] 	^
```

**Comment by nhpatt** [comment]
Fixed here: https://github.com/brianchandotcom/liferay-portal/pull/71372

Some PRs got merged partially :(

Un saludo,

Javier Gamarra

**Comment by brianchandotcom** [comment]
@victorg1991 still breaks for me

```

com.liferay.headless.foundation.resource.v1_0.test.UserAccountResourceTest > testGetUserAccountsPage FAILED
    com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'No': was expecting 'null', 'true', 'false' or NaN
     at [Source: UNKNOWN; line: 1, column: 3]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:703)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2853)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2831)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._matchToken(ReaderBasedJsonParser.java:2612)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1876)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:757)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4141)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4000)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3023)
        at com.liferay.headless.foundation.resource.v1_0.test.BaseUserAccountResourceTestCase.invokeGetUserAccountsPage(BaseUserAccountResourceTestCase.java:756)
        at com.liferay.headless.foundation.resource.v1_0.test.UserAccountResourceTest.testGetUserAccountsPage(UserAccountResourceTest.java:104)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$2.evaluate(TestExecutorRunnable.java:181)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at com.liferay.portal.test.rule.LiferayIntegrationTestRule$1$1.evaluate(LiferayIntegrationTestRule.java:154)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:54)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:118)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at com.liferay.portal.test.rule.LiferayIntegrationTestRule$1$1.evaluate(LiferayIntegrationTestRule.java:154)
        at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:71)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:156)
        at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:77)
        at java.lang.Thread.run(Thread.java:745)

com.liferay.headless.foundation.resource.v1_0.test.UserAccountResourceTest > testGetUserAccountsPageWithFilterDateTimeEquals STARTED

com.liferay.headless.foundation.resource.v1_0.test.UserAccountResourceTest > testGetUserAccountsPageWithFilterDateTimeEquals PASSED

com.liferay.headless.foundation.resource.v1_0.test.UserAccountResourceTest > tes
```

**Comment by brianchandotcom** [comment]
@victorg1991 no need to resend, tests pass in upstream now. I had a bad db/index.

**Pull request closed without merging**
