### PR TITLE
LPS-66831 As a Roles Admin user, I would like to see the number of assignees for each role in the role search results

### PR DESCRIPTION
**Pull request by alee8888**

### CODE REVIEW

**Comment by alee8888** [comment]
@drewbrokke @brianchandotcom 
This combines the commits for LPS-66831 and Poshi functional test fixes.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@alee8888 rebase error, can you resend? Thx.

**Comment by alee8888** [comment]
Resent here https://github.com/brianchandotcom/liferay-portal/pull/42851.

**Pull request closed without merging**
