### PR TITLE
LPS-57486 Fix NPE in DynamicCSSUtil.replaceToken

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/46217dd9b2...d6d1705403

**Comment by brianchandotcom** [comment]
@izaera great job on finding this fix. I just read through the LPS log...

**Comment by izaera** [comment]
:-)

**Comment by nikki-pru** [comment]
@ZoltanTakacs, please backport this commit to 7.0.x as it fixes an issue we're encountering with adding some portlets to a page. I have tested this commit on 7.0.x and it works. Thank you!

**Pull request closed without merging**
