### PR TITLE
LPS-90886 Show web content title

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@ealonso see a1572ddc63bf6c755054cd8c50b066779b0a4585 and my other changes in upstream.

**Comment by brianchandotcom** [comment]
Woops, my other changes are in a wrong ticket 724e7e6242170aacb98075af75ea61d500d27fd7 and 566e30f0e31bff65d426c58c54cf9591f1bd51f5

**Pull request closed without merging**
