### PR TITLE
LPS-104849 Build lang

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @brianchandotcom 

I've kept everything in the layout-seo module (instead of a new site-seo-* one) as the LayoutSEOSiteEntry model does not contain data about the site itself, but only default values for the layouts in a site (we'll use this config. values in an upcoming pull request).

PS: I've rebased and squashed everything to make the review easier.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by brianchandotcom** [comment]
@adolfopa can we call it LayoutSEOSite? We only made the first one LayoutSEOEntry so it's not LayoutSEO

Please resend. Sorry about that! If it's confusing, call me on Skype/Slack real quick.

**Comment by adolfopa** [comment]
Makes perfect sense. See https://github.com/brianchandotcom/liferay-portal/pull/81578

Thanks!

**Pull request closed without merging**
