### PR TITLE
LPS-199722 Implement Import Export for page rules

### PR DESCRIPTION
**Pull request by alessandromalves**
https://liferay.atlassian.net/browse/LPS-199722

cc.: @lfbesada

### CODE REVIEW

**Comment by alessandromalves** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/14100

❌ ci:test:stable - 30 out of 31 jobs passed
❌ ci:test:relevant - 199 out of 211 jobs passed in 2 hours 21 minutes

**Comment by alessandromalves** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@lfbesada are you sure this is thread safe?

```
		if (_layoutsImporterResultEntries == null) {
			_layoutsImporterResultEntries = new ArrayList<>();
		}
```

LayoutsImporterImpl.java is a shared component?

**Comment by lfbesada** [comment]
Hi @brianchandotcom 
Thank you very much for the review!
I totally agree, that this class is not thread-safe.
That commit is not related to this PR, it's just a bug I found while developing, and that's why I created a specific bug to deal with it. I have sent a fix [here](https://github.com/liferay-echo/liferay-portal/pull/14140) that transforms the class into thread-safe in addition to fixing the NPE.
I have resent the rest of this PR [through the echo repo](https://github.com/liferay-echo/liferay-portal/pull/14141) so that it can re-visit CI without that commit.
Thank you very much for the heads-up!

**Pull request closed without merging**
