### PR TITLE
LPS-73481 Set 7.1.0 in master

### PR DESCRIPTION
**Pull request by achaparro**
It depends on:
brianchandotcom/liferay-plugins#5404
brianchandotcom/liferay-portal-ee#18287

### CODE REVIEW

**Comment by achaparro** [comment]
Hi @jpince,

The errors:
`java.lang.RuntimeException: com.liferay.portal.kernel.upgrade.UpgradeException: java.sql.SQLSyntaxErrorException: ORA-00972: identifier is too long` seem unrelated and I saw it in previous pulls, what do you think?

Thanks.

**Comment by achaparro** [comment]
ci:reopen

**Comment by jpince** [comment]
@achaparro yes, you're correct, those failures are unrelated to your pull. You can follow the [#PullRequestTester](https://loop.liferay.com/web/guest/home/-/loop/topics/_PullRequestTester) topic on loop so you know what errors you can ignore.

@brianchandotcom this pull looks good from an automated test perspective.

**Comment by jpince** [comment]
@brianchandotcom can you please review this pull? the merge conflict is for the dependency on brianchandotcom/liferay-plugins#5404 and brianchandotcom/liferay-portal-ee#18287, not an issue with the code

**Comment by jpince** [comment]
ci:retest

**Comment by achaparro** [comment]
Closed, see:
https://github.com/brianchandotcom/liferay-portal/pull/51808
https://github.com/brianchandotcom/liferay-portal-ee/pull/18377
https://github.com/liferay/com-liferay-commerce-private/pull/196

@jpince @brianchandotcom

**Pull request closed without merging**
