### PR TITLE
Ability to pass a listener to run some custom logic when a service is bucketed

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by migue** [comment]
ci:retest

**Comment by migue** [comment]
ci:retest

**Comment by migue** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/34623f70a0...c6a99f1fe3

**Comment by brianchandotcom** [comment]
@migue @csierra please see my changes in upstream. Thx.

**Pull request closed without merging**
