### PR TITLE
LPS-77699

### PR DESCRIPTION
**Pull request by lionah**
Manual Sync

### CODE REVIEW

**Comment by lionah** [comment]
@jhendley

**Comment by lionah** [comment]
ci:reopen

**Comment by jhendley** [comment]
ci:close

**Comment by jhendley** [comment]
I closed this because we need to look at the error before merging. Thanks.

**Comment by brianchandotcom** [comment]
@lionah @jhendley I cherry picked the keys to 7.1.x that were identical.

**Pull request closed without merging**
