### PR TITLE
LPS-107165 Add permission checker to test

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@wincent @jbalsas fyi

```
AXIS_VARIABLE=0,label_exp=!master #248320
Liferay_Search_SearchBar _getKeywords.returns the keywords
```
Can you guys take a look? Thx

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/09cdeaf01b...8626d7ee0d

**Comment by brianchandotcom** [comment]
@cgoncas see f86edee8112ae8621d58f2082d03bf49be81556e

**Comment by wincent** [comment]
@brianchandotcom: sent follow-up here: https://github.com/brianchandotcom/liferay-portal/pull/83631

**Pull request closed without merging**
