### PR TITLE
Lps 133600

### PR DESCRIPTION
**Pull request by marco-leo**

### CODE REVIEW

**Comment by marco-leo** [comment]
Schermata 2021-07-09 alle 00 12 36
Schermata 2021-07-09 alle 00 12 42
Schermata 2021-07-09 alle 00 13 20
Schermata 2021-07-09 alle 00 12 31
Schermata 2021-07-09 alle 00 04 40

**Comment by marco-leo** [comment]
ci:reopen

**Comment by gabrielwas** [comment]
Just started reviewing :)

**Comment by gabrielwas** [comment]
I'll create permissions on top of it (I'll need the portlet constants, etc)

**Comment by interaminense** [comment]
Just started reviewing :)

**Pull request closed without merging**
