### PR TITLE
LPS-99075 Need to use original context path in LastPath, this is a bug introduced by LPS-68241(ad5a20740e4b59865d62b32d7b91a94e7cb42718)

### PR DESCRIPTION
**Pull request by martamedio**
cc/ @tinatian

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/06913f9175...f5e495e863

**Comment by brianchandotcom** [comment]
@izaera @martamedio fyi - can you guys get a test / poshi for this?

@jpince fyi

**Comment by jpince** [comment]
cc/ @john-co

**Comment by john-co** [comment]
Ticket created for new automation test: https://issues.liferay.com/browse/LRQA-51300

**Pull request closed without merging**
