### PR TITLE
LPS-96040

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/65081cb2f6...d18d9e33b3

**Comment by brianchandotcom** [comment]
@nhpatt @ivicac see upstream for my many changes ( took me a while because things just looked a bit off)

@ivicac please review.. should have kept 99% of your intention. I just grouped things differently.

**Pull request closed without merging**
