### PR TITLE
LPS-99220 Split constants file and create one for experiences

### PR DESCRIPTION
**Pull request by dgarciasarai**
Please see: https://github.com/brianchandotcom/liferay-portal/compare/0a8577be44...7ac054a02a

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@dgarciasarai can you resend? Rebase error. THx!

**Comment by dgarciasarai** [comment]
Resent here https://github.com/brianchandotcom/liferay-portal/pull/76562

**Pull request closed without merging**
