### PR TITLE
[DO NOT MERGE, PLEASE READ COMMENT] LPS-59672 Move frontend 3rd party dependencies out of core

### PR DESCRIPTION
**Pull request by jbalsas**
Hey Brian, this moves all the frontend 3rd party dependencies out of core.

For some reason, looks like a failed artifact request for `lexicon@0.1.27` is cached in our nexus server and it won't resolve it properly anymore. However, it is properly published in [Maven Central](http://search.maven.org/#artifactdetails%7Corg.webjars.bower%7Clexicon%7C0.1.27%7Cjar)

This works because I downloaded the Maven Central one and we use the gradle cache in the CI, but it will fail when running locally...

How often is the nexus cache cleared? Is there something we could do?

Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@jbalsas is it broken on cdn.repository.liferay.com or on repository.liferay.com?

I can have @petershin clear the CDN right now, but for repository.liferay.com (our Nexus itself), that is @CAustin582 and I'm not sure we can clear it

The best thing to do is to publish a new version @jbalsas 

Please resend.

**Comment by jbalsas** [comment]
Ok, @natecavanaugh is bumping the version right now. I'll test and resend later.

Thanks!

**Comment by petershin** [comment]
@brianchandotcom purged the cache for cdn.repository.liferay.com

**Comment by jbalsas** [comment]
Thanks for that, @petershin. I tried after that but it didn't look like that solved the issue. From what I've read, I think we have to remove the cached artifact somehow... 

Anyway, we published a new version and resent to https://github.com/brianchandotcom/liferay-portal/pull/33754

Thanks!

**Pull request closed without merging**
