### PR TITLE
LPS-68711 Add unit tests

### PR DESCRIPTION
**Pull request by marcellustavares**
This fix the issue 4 of https://github.com/ctampoya/liferay-portal/pull/24

cc @thiago-rocha @ctampoya

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by marcellustavares** [comment]
ci:retest

**Comment by jpince** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@marcellustavares this keeps failing. Please resend.

**Comment by marcellustavares** [comment]
another attempt sent to https://github.com/brianchandotcom/liferay-portal/pull/44043

**Pull request closed without merging**
