### PR TITLE
LPS-63857

### PR DESCRIPTION
**Pull request by Ithildir**
Hi!
Can you please publish a new `gradle-plugins`?

Thanks!

cc @rotty3000

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/320ca70375...94f5658154

**Comment by brianchandotcom** [comment]
@Ithildir can you apply this to EE plugins as well? Thx.

**Comment by brianchandotcom** [comment]
@Ithildir I mean, EE branch. Thx.

**Comment by Ithildir** [comment]
Checked, there are no dependencies from `jsp-api` in the EE modules :blush:

**Pull request closed without merging**
