### PR TITLE
LPS-74544

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Pull for 7.0.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/19632

**Comment by brianchandotcom** [comment]
ci:reopen @hhuijser can you help me fix master-private? Thx.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@hhuijser nvm, I fixed the master-private SF issue.

**Pull request closed without merging**
