### PR TITLE
LPS-109844 Expose utils files in headless-delivery

### PR DESCRIPTION
**Pull request by LuismiBarcos**
Send directly to Brian (more info [here](https://github.com/brianchandotcom/liferay-portal/pull/101413#issuecomment-832746443))

This is the first pull of the two requested. In this one, we refactor the StructuredContentResourceImpl to extract and expose the common methods that we will need in the next PR and, with this, avoid duplicate code.

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
ci:reopen

**Comment by LuismiBarcos** [comment]
FYI @nhpatt

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3c1a68c768...cafc245ef4

**Comment by brianchandotcom** [comment]
@LuismiBarcos see 2be109726b43b39112f157f3edf7b89c5afc0892 and cafc245ef43f9966a88f0c89bc2a5f9ea33c11df

**Pull request closed without merging**
