### PR TITLE
LPS-83949 Add an object to hold information about JS module resolutions

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:test

**Comment by izaera** [comment]
@brianchandotcom this is a followup of yesterday's pulls. It introduces new classes and auxiliary services we will be using in following PRs to implement JS modules resolution. 

The idea is to keep adding functionality "in the shadow" until we have everything set up and then, switch from the older JS module resolution to this new one.

As I said, this PR adds all needed dependencies to make JS module resolution and I will send the algorithm implementation tomorrow.

**Comment by izaera** [comment]
Even though I don't expect to break any test, this PR may break something because I have changed some public APIs, so please don't merge it without having a look at the tests if they fail :-). 

I will try to add my comments later should that happen.

**Comment by izaera** [comment]
OK, I have tested deployment and some navigation locally and everything seems to be OK, so I don't expect the PR to break anything. 

If it broke something it would be catastrophic and easily visible given that I'm changing core JS module resolution code.

**Comment by brianchandotcom** [comment]
@izaera see my changes in upstream. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e1d47072c6...db57f72efd

**Pull request closed without merging**
