### PR TITLE
LPS-67377 IE is not compatible with uploading a bmp file for the user portrait

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
rebased to get missing commit, push force'd and ci:retest, please

**Comment by brianchandotcom** [comment]
ci:retest (there was something wrong with CI and diffing pulls)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0daf60dcc9...c8e0dab2bc

**Comment by brianchandotcom** [comment]
Nice job @jbalsas @adolfopa

**Pull request closed without merging**
