### PR TITLE
COMMERCE-618

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
https://issues.liferay.com/browse/COMMERCE-618

Resend of https://github.com/brianchandotcom/liferay-portal/pull/63010

Addresses the concerns you've raised on https://github.com/brianchandotcom/liferay-portal/pull/63010#issuecomment-422466053

Please let me know if you'd like me to change something else for the installer.

Thank you,

### CODE REVIEW

**Comment by jpince** [comment]
@ZoltanTakacs @pyoo47 yes, this was resolved by https://github.com/brianchandotcom/liferay-portal/pull/65369. Please try again in a couple hours after a new upstream acceptance build finishes.

**Comment by ZoltanTakacs** [comment]
ci:retest:relevant

**Comment by jpince** [comment]
ci:test:relevant @pyoo47 Zoltan's ci command at 12:20 am PST did not initiate (data for your investigation)

**Comment by marco-leo** [comment]
Hi @brianchandotcom can you please give us feedback on this pull? Is there a why for not merging it ? Do you want us to change things? //cc @ZoltanTakacs

**Comment by ZoltanTakacs** [comment]
Hi @brianchandotcom , is there anything that I can do for help the review process? Thank you

**Comment by brianchandotcom** [comment]
Superceded by https://github.com/brianchandotcom/liferay-portal/pull/65736

Will merge the other pull soon.

**Pull request closed without merging**
