### PR TITLE
LPS-69203 Reuse the same instance since we can't change the tracked object

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by migue** [comment]
ci:reopen

**Comment by migue** [comment]
This pull ran perfectly fine, no test failures, https://github.com/migue/liferay-portal/pull/918 and nothing has changed

**Comment by brianchandotcom** [comment]
@shuyangzhou I see a lot of random failures with DataSourceFactoryImplTest.testHikariCP

Merged.

**Comment by shuyangzhou** [comment]
@tinatian please take care of this

**Comment by tinatian** [comment]
@shuyangzhou OK, I will.

**Pull request closed without merging**
