### PR TITLE
Lps 61952 backgroundtask

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@Preston-Crary I think that ExportImportSampleLARPortlet test failure may be real. ci:retest

**Comment by Preston-Crary** [comment]
Same test didn't fail on the pull to I sent Shuyang.

**Comment by brianchandotcom** [comment]
@brianchiu see random failing poshi tests. Please fix.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b2defb5e33...767ec62643

**Comment by brianchandotcom** [comment]
@shuyangzhou can you also add a section in readme/7.0/BREAKING_CHANGES.markdown

Basically, explain the split path issue. We only need one section that lists out the packages of what they were renamed from and to. Then, for each subsequent pull, just keep documenting the packages.

Can you go through and do the old ones (please task this to someone on your team)

Thx

**Comment by shuyangzhou** [comment]
Sure, will add that in the next pull.

**Comment by brianchiu** [comment]
@brianchandotcom 
I see it. Thanks.

**Pull request closed without merging**
