### PR TITLE
LPS-106474 Using mime types instead of extensions

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-106474

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f1f7de9f88...bfa0ac1fa2

**Comment by brianchandotcom** [comment]
@4lejandrito see 37762b314fc5c574b69152ce79fd644415705b91

@jbalsas @wincent fyi:

```
TypeError: Liferay.component is not a function
    at component (item-selector/item-selector-taglib/src/main/resources/META-INF/resources/item_selector_preview/js/ItemSelectorPreview.es.js:66:11)
    at commitHookEffectList (/opt/dev/projects/github/liferay-portal/modules/node_modules/react-dom/cjs/react-dom.development.js:19986:26)
    at commitPassiveHookEffects (/opt/dev/projects/github/liferay-portal/modules/node_modules/react-dom/cjs/react-dom.development.js:20016:11)
    at HTMLUnknownElement.callCallback (/opt/dev/projects/github/liferay-portal/modules/node_modules/react-dom/cjs/react-dom.development.js:347:14)
    at invokeEventListeners (/opt/dev/projects/github/liferay-portal/modules/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
    at HTMLUnknownElementImpl._dispatch (/opt/dev/projects/github/liferay-portal/modules/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
    at HTMLUnknownElementImpl.dispatchEvent (/opt/dev/projects/github/liferay-portal/modules/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
    at HTMLUnknownElementImpl.dispatchEvent (/opt/dev/projects/github/liferay-portal/modules/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
    at HTMLUnknownElement.dispatchEvent (/opt/dev/projects/github/liferay-portal/modules/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
    at Object.invokeGuardedCallbackDev (/opt/dev/projects/github/liferay-portal/m...
```

**Comment by jbalsas** [comment]
mmm... that's weird... 🤔 

@adolfopa, @ambrinchaudhary, can you take a look at this and reach out if you need help figuring out why those tests are failing?

**Comment by ambrinchaudhary** [comment]
I'll check it @jbalsas @adolfopa!

**Comment by ambrinchaudhary** [comment]
Failing test resolved here: https://github.com/brianchandotcom/liferay-portal/pull/82872. 
Sorry, my mistake!

**Pull request closed without merging**
