### PR TITLE
LPS-77926 Exports link.browse capability

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f8a644a9dd...a37616f9a2

**Pull request closed without merging**
