### PR TITLE
LPS-92553 Correct test

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
sorry about this @jpince....

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@petershin what's going on with SF?

**Comment by jpince** [comment]
@jkappler will this resolve the failure in `ModulesStructureTest.testScanGradleFiles`?
```
junit.framework.AssertionFailedError: Incorrect configuration of dependency {compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"} in modules/apps/asset/asset-display-test/build.gradle, use one of these instead: "testIntegrationCompile", "testIntegrationRuntime"
```
https://github.com/brianchandotcom/liferay-portal/pull/70843#issuecomment-480038299

**Comment by jpince** [comment]
cc/ @brianchiu asking Jurgen about the failure in central-requirements (ModulesStructureTest) above

**Comment by petershin** [comment]
@brianchandotcom - The Jenkins logs are deleted.  If you see this issue on a different pull, please cc me on the new pull.

**Comment by jpince** [comment]
@jkappler oh I see, this was to fix the PMD error
```
     [echo] PMD VIOLATION: /opt/dev/projects/github/liferay-portal/modules/apps/asset/asset-display-test/src/testIntegration/java/com/liferay/asset/display/test/AssetDisplayContributorTest.java:62 > Do not call Assert#fail improperly. (PMD Rule: AssertFailJUnitRule)
```
can you please take a look at the central-requirements (ModulesStructureTest) failure as well?

**Comment by jpince** [comment]
@petershin https://test-1-10.liferay.com/job/test-portal-source-format/534/console

**Comment by petershin** [comment]
@jpince - Appreciate it!

@brianchandotcom - I think its because that file has non ASCII characters. Taking a closer look

**Comment by petershin** [comment]
Sent a patch: https://github.com/Preston-Crary/liferay-portal/pull/735

**Pull request closed without merging**
