### PR TITLE
LPS-69139

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:reopen

**Comment by Ithildir** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
@Ithildir Shuyang knows about TestSuite.com.liferay.portlet.PortletPreferencesFactoryImplGetPreferencesIdsTest

No idea how it snuck in but he's working on a fix

**Comment by brianchandotcom** [comment]
@codyhoag fyi

**Pull request closed without merging**
