### PR TITLE
LPS-172038 Refactor Facets tests to use a common base file

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LPS-172038

`search`, `relevant`, and `sf` passed testing in https://github.com/liferay-search/liferay-portal/pull/756. Manually forwarding these changes since `relevant` failed due to unrelated failures.

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d3c0ac523f...910bcca323

**Comment by brianchandotcom** [comment]
Very nice @kungfumanda @gustavolimav I didn't smell anything bad. All good.

**Comment by brianchandotcom** [comment]
@kungfumanda @gustavolimav hey, just one thing

Change

```
	protected void testOrderBy(
			String[] terms, int[] frequencies, String order,
			String[] expectedTerms, int[] expectedFrequencies)
		throws Exception {

		throw new UnsupportedOperationException();
	}

```

to an abstract method to force the subclasses to implement this method.

And sort the params. Thx.

**Pull request closed without merging**
