### PR TITLE
Lps 69306

### PR DESCRIPTION
**Pull request by shuyangzhou**
This is a partially redo for https://github.com/brianchandotcom/liferay-portal/pull/46582
The changes to lock service in that pull has several issues(only some of them are caused by that pull, others have been there since beginning)

1. LDAPUserImporterImpl could unlock a lock that it did not lock in the first place.
		The end result could be, one ongoing import is running, another invoker tries to import again, it will be rejected as expected, but it unlocks the lock in the finally. Then if there is another invoker trying to import again, it will proceed since the lock has been removed. 

2. There is no concurrent import protection for the same user.
		The logic only handles concurrent import protection from different users. When the same user tries to concurrently do the import, we will end up actually importing it multiple times.

3. There are many usages to the deprecated apis.
		The general rule for this is, we should never use our own deprecated api, unless the invoker has been deprecated as well. The reason for this is, later in the next major release, we can easily remove all the deprecated code without any refactor.

4. The auto renew logic is broken.
		We end up always renewing the lock expiration time, which is wrong in many usages.

5. Some other broken logic that would cause mvcc and unique index failures.

@csierra @migue
CC @preston-crary

### CODE REVIEW

**Comment by csierra** [comment]
hey @shuyangzhou @preston-crary 

thank you for the update. I still have one concern though, and it is that IMHO the API is still very error prone and the user can very likely use the API in the wrong way (i.e. failing to check if the lock is new, for example). 

Wouldn't is be possible to only return the lock handle when the current thread has been granted the lock so there exists no possible ambiguity?

That was the main intention of the former lock. Alas we were not aware of all the other problems the API had, as you guys are, so we were not addressing those. 

Bests.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cb4883de69...9b64f6610a

**Comment by shuyangzhou** [comment]
@csierra I agree the current api is not the best we can do. But it is not a simple thing to change either. 
As for your question, 

> Wouldn't is be possible to only return the lock handle when the current thread has been granted the lock so there exists no possible ambiguity? 

The tricky part is, sometimes we allow reentrant to the lock, something we don't. We have 2 options here, one is the current isNew hack solution. Another would be add another parameter to control it. I prefer the current solution, just because in some locations the expected behavior changes between runs. It would be cumbersome to add if-else to those cases. It is better to enclose the state in the return value.

I would say we keep things as simple as possible for now to get over the ldap issue. If you really feel this is necessary, we can do a refactor to lock service later. It will keep thing easier to separate bug fix from design refactor. This way we can focus on what we are really doing, to make sure everything is on the right direction.

**Comment by migue** [comment]
Hello guys,

If we decide to just solve the LDAP issue for now, why don't we just keep
the Lock API in its original form, and put the original "hasLock and lock"
combo of the LDAP importer into a synchronized block?

This should solve the issue for the LDAP importer with no changes in the
Lock.

We could revisit the Lock API in the future

On Feb 8, 2017 18:28, "Shuyang Zhou" <notifications@github.com> wrote:

@csierra <https://github.com/csierra> I agree the current api is not the
best we can do. But it is not a simple thing to change either.
As for your question,

Wouldn't is be possible to only return the lock handle when the current
thread has been granted the lock so there exists no possible ambiguity?

The tricky part is, sometimes we allow reentrant to the lock, something we
don't. We have 2 options here, one is the current isNew hack solution.
Another would be add another parameter to control it. I prefer the current
solution, just because in some locations the expected behavior changes
between runs. It would be cumbersome to add if-else to those cases. It is
better to enclose the state in the return value.

I would say we keep things as simple as possible for now to get over the
ldap issue. If you really feel this is necessary, we can do a refactor to
lock service later. It will keep thing easier to separate bug fix from
design refactor. This way we can focus on what we are really doing, to make
sure everything is on the right direction.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/brianchandotcom/liferay-portal/pull/46702#issuecomment-278399609>,
or mute the thread

**Comment by shuyangzhou** [comment]
@migue that won't work, like I said in the first comment, there are many issues for the LDAP case, not all of them are from your changes, some of them have been there since beginning.

We have to change lock service to fix those. I only meant to not changing the design style in a bug fix, but we still have to fix the bug.

**Pull request closed without merging**
