### PR TITLE
Full Revert LPS-69892 | 7.0.x

### PR DESCRIPTION
**Pull request by brianwulbern**
**This is 7.0 only**

Affected LPS:
https://issues.liferay.com/browse/LPS-69892

Associated BPR:
https://issues.liferay.com/browse/BPR-8370

QA Roll back ticket:
https://issues.liferay.com/browse/LRQA-30267

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:stop

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@brianwulbern we can't revert this since it's already gone out.

@jonmak08 we need a fix/update for this asap.

Thx.

**Comment by jonmak08** [comment]
I will send an update AUI release for this issue.  It is a minor revert in AUI.

Please let me know if you have any questions. Thanks!

**Comment by jonmak08** [comment]
I have just reverted the CSS changes in AUI for this issue and have created new AUI releases and sent those to @brianchandotcom  for final review.

master: https://github.com/brianchandotcom/liferay-portal/pull/46734
ee-7.0.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/15893
ee-6.2.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/15890

**Pull request closed without merging**
