### PR TITLE
LPS-66831 As a Roles Admin user, I would like to see the number of assignees for each role in the role search results

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-66831](https://issues.liferay.com/browse/LPS-66831).

/cc @juliocamarero @sergiogonzalez @marcellustavares @dejuknow @rotty3000 @arboliveira @pei-jung @lionah @jorgeferrer

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:stop

**Comment by jpince** [comment]
@drewbrokke I don't see your other pull's commits in either master or the journal sub-repo... I was hoping to see the results of this pull in case BChan knows something we don't?

**Comment by drewbrokke** [comment]
@jpince I think he was talking about something else.  We can close this for now.  Thanks!

**Comment by jpince** [comment]
Sounds good. Will look forward to the next resend... :)

**Pull request closed without merging**
