### PR TITLE
LPS-102627 Add tests

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e45058f1d9...6cbd9c571a

**Comment by brianchandotcom** [comment]
@leoadb see 6cbd9c571a0d5888887a7ed728a6779df2b88e48

**Pull request closed without merging**
