### PR TITLE
LPS-104958 buildLang

### PR DESCRIPTION
**Pull request by brunofarache**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@brunofarache lots of errors, please resend.

**Comment by brunofarache** [comment]
@alexcandidos
Can you please take a look on this CI error? It's not related to my code changes, not sure why it happened, looks like a CI failure:

/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:11298: Sourced file: inline evaluation of: `` 							 								import com.liferay.jenkins.results.parser.Build; 								import . . . '' : Typed variable declaration : Class: Build not found in namespace : at Line: 6 : in file: inline evaluation of: `` 							 								import com.liferay.jenkins.results.parser.Build; 								import . . . '' : Build 


cc @jpince

**Comment by jpince** [comment]
ci:test:relevant

**Comment by brunofarache** [comment]
@jpince looks like CI is having internet connection issues?

**Comment by jpince** [comment]
@brunofarache yes, but almost half of the batches passed, so it wouldn't be a full squid outage. @alexcandidos will need to work this out with CII team.

In the meantime, you are welcome to ci:reopen and see if BChan will accept the results as they are so this code doesn't remain in limbo. It seems clear to me that the errors are unrelated, the only problem is that not all tests have successfully run against this code.

**Comment by jpince** [comment]
ci:test:relevant

**Comment by alexcandidos** [comment]
@brunofarache your assumption is right, I've asked at CI channel on slack and they confirm CI Network issues (https://loop.liferay.com/pt/home/-/loop/feed/20287376). So I think it is okay to reopen as @jpince said. Thanks!

**Pull request closed without merging**
