### PR TITLE
LPS-79709 Makes sure replaceSoyTranslation happens after building files

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:reopen

**Comment by jbalsas** [comment]
(unrelated SF error)

**Comment by jpince** [comment]
test results are consistent with those in upstream, @brianchandotcom please review

**Comment by brianchandotcom** [comment]
@jbalsas rebase error. .can you resend in 2 steps..

First one is to just rename the old existing JS key. SF should enforce the new key, BUT, the code that reads the key should be smart enough to read the old and new key for backwards compat. I'll backport that.

Once that is done, then send me the new JS keys and the new code.

THx.

**Comment by izaera** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
