### PR TITLE
LPS-55355 SF

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
@peterfellwock could you investigate the Poshi failure above? Maybe ask someone in the office? I'm not that familiar with it. I think we'd be good after fixing that.

**Comment by peterfellwock** [comment]
@rotty3000 the Poshi failure is something in master that is broken, basically:

    Open browser to '/web/guest/home' --> PASSED
    Open browser to '/web/guest/home' --> PASSED
    Type to 'EMAIL_ADDRESS' the value 'test@liferay.com' --> PASSED
    Type to 'PASSWORD' the value 'test' --> PASSED
    Click on 'SIGN_IN' that should have a value of 'Sign In' --> PASSED
    Click on 'I_AGREE' that should have a value of 'I Agree' --> PASSED
    Type to 'ANSWER' the value 'test' --> PASSED
    Click on 'SAVE' that should have a value of 'Save' --> FAILED

**Comment by brianchandotcom** [comment]
@peterfellwock this is a real bug in the Shopping extraction.

Some module is not loading right

```
java.lang.Exception: Unable to include /META-INF/resources/content/content.jsporg.apache.jasper.JasperException: java.lang.NullPointerException
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:440)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at com.liferay.portal.servlet.jsp.compiler.JspServlet.service(JspServlet.java:243)
	at com.liferay.portal.servlet.jsp.compiler.JspServlet.service(JspServlet.java:254)
	at org.eclipse.equinox.http.ser
```

which is causing the Smoke test to break. That test is consistently working in all other pulls.

**Comment by peterfellwock** [comment]
@brianchandotcom when I finish the plugins_admin MVC I will pull down and test to see what is actually breaking.

**Pull request closed without merging**
