### PR TITLE
LPS-68852 Remove unused styles

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @ambrinchaudhary @patrickyeo

**Comment by brianchandotcom** [comment]
@sergiogonzalez @ambrinchaudhary failed tests. Please resend.

**Comment by sharonchoi** [comment]
@ambrinchaudhary @sergiogonzalez Will fix POSHI tests associated with the updated UI bug fix on this pull and resend here: https://issues.liferay.com/browse/LRQA-28731

**Comment by sharonchoi** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/44345

**Pull request closed without merging**
