### PR TITLE
LPS-80024 Update blogs compat

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jpince does this fix our semantic versioning error? If so, can you undo it? Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fb8abdd7fe...ca719d4fc4

**Comment by tomwang2011** [comment]
@brianchandotcom @jpince this is the fix for the semantic versioning error, it was due to newly added methods in 7.0.x portal-kernel during service builder regen, the compat module was retrieving an older version of portal-kernel so baseline thinks we are deleting the changes done causing the baseline error, thanks!

**Comment by jpince** [comment]
@tomwang2011 thanks!

**Pull request closed without merging**
