### PR TITLE
LPS-171977 - Page Tree loses selected page after navigating to it

### PR DESCRIPTION
**Pull request by Tim-Cao**
This is only for master.

https://issues.liferay.com/browse/LPS-171977

@ruben-pulido

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/10762

**Comment by ruben-pulido** [comment]
ci:close

**Comment by ruben-pulido** [comment]
ci:reopen

**Comment by ruben-pulido** [comment]
ci:close

**Pull request closed without merging**
