### PR TITLE
LPS-97276

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by jpince** [comment]
ci:close @cgoncas @adolfopa startup errors. They are also present in the previous pull to Adolfo https://github.com/adolfopa/liferay-portal/pull/1037#issuecomment-505392651
```
     [exec] 10:18:03,085 WARN  [main][PortalInstanceLifecycleListenerManagerImpl:175] Unable to register portal instance {mvccVersion=1, companyId=20101, accountId=20103, webId=liferay.com, key=z8JJHKFabc4tnH8LL1WZwA==, mx=liferay.com, homeURL=, logoId=0, system=false, maxUsers=0, active=true}
     [exec] java.lang.NullPointerException
     [exec] 	at com.liferay.oauth2.provider.service.impl.OAuth2ApplicationLocalServiceImpl.updateIcon(OAuth2ApplicationLocalServiceImpl.java:314)
```
Maybe portletFileRepository is needed by other modules? You might consider getting help from Shuyang or someone on his team.
```
     [exec] Bundle {id: 316, name: com.liferay.upload.web, version: 4.0.0}
     [exec] 	Declarative Service {id: 1203, name: com.liferay.upload.web.internal.HTMLImageAttachmentElementReplacer, unsatisfied references: 
     [exec] 		{name: PortletFileRepository, target: null}
     [exec] 	}
     [exec] 	Declarative Service {id: 1202, name: com.liferay.upload.web.internal.HTMLImageAttachmentElementHandler, unsatisfied references: 
     [exec] 		{name: _attachmentElementReplacer, target: (&(format=html)(html.tag.name=img))}
     [exec] 	}
```
cc/ @austinchiang

**Comment by jpince** [comment]
cc/ @Hanlf @liuxingye

**Comment by cgoncas** [comment]
Ci:test:relevant

**Comment by cgoncas** [comment]
Just started reviewing :)

**Comment by cgoncas** [comment]
Continue in https://github.com/cgoncas/liferay-portal/pull/395. I thought this error was fixed in: https://github.com/brianchandotcom/liferay-portal/pull/74925

**Pull request closed without merging**
