### PR TITLE
LPS-99306 Add tests back

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/57e65ede22...d52b87e956

**Comment by brianchandotcom** [comment]
@nhpatt I merged this pull from @brunofarache but I"m not 100% comfortable with it:

```
		String sessionId = CookieKeys.getCookie(
			contextHttpServletRequest, CookieKeys.JSESSIONID);

		DataListViewResource dataListViewResource =
			DataListViewResource.builder(
			).endpoint(
				_portal.getHost(contextHttpServletRequest),
				contextHttpServletRequest.getServerPort(),
				contextHttpServletRequest.getScheme()
			).header(
				"Cookie", "JSESSIONID=" + sessionId
			).parameter(
				"p_auth", AuthTokenUtil.getToken(contextHttpServletRequest)
			).build();
```

See AppResourceImpl.java

I remember you were about to add something similar to jsessionid, but you ended up needing 2 vars.. I don't know what they are, but I'd like to compare what your calls would be like compared to his (which uses p_auth). Can you send me a pull?

@brunofarache also, why did we go with jsessionid instead of like how DataLayoutTaglibUtil does it? Please Slack me or send me a pull as well. 

Thx!

**Comment by brunofarache** [comment]
@brianchandotcom @nhpatt @leoadb,

I followed Brian's instructions to use this instead of session cookies:

```java
PermissionChecker permissionChecker =
	PermissionThreadLocal.getPermissionChecker();

User user = permissionChecker.getUser();

DataListViewResource dataListViewResource =
	DataListViewResource.builder(
	).authentication(
		user.getEmailAddress(), user.getPassword()
	).endpoint(
		_portal.getHost(contextHttpServletRequest),
		contextHttpServletRequest.getServerPort(),
		contextHttpServletRequest.getScheme()
	).parameter(
		"p_auth", AuthTokenUtil.getToken(contextHttpServletRequest)
	).build();
```

However, `user.getPassword()` returns the password hash and not the password in plain text and authentication fails because of that.

@leoadb, check if `DataLayoutTaglibUtil` is working properly.

There is probably a a better way to do server to server authentication, in this specific case, the request is made by the same server that receives it, it should trust itself and it would only need userId for permission checking.

**Comment by leoadb** [comment]
@brunofarache I'm using cookies now. I'll send the PR to BChan with some other changes.

**Comment by nhpatt** [comment]
@brianchandotcom The vars we needed were those 2, jsessionid and p_auth. I talked with Carlos and to do client requests with autentication either we have the plain password and use basic (it's ok if we hardcode for tests, but invalid in other cases but we can't extract the password from the hashed getPassword() in user), use OAuth or cookies.

I remember you were about to add something similar to jsessionid, but you ended up needing 2 vars.. I don't know what they are, but I'd like to compare what your calls would be like compared to his (which uses p_auth). Can you send me a pull?

@brunofarache also, why did we go with jsessionid instead of like how DataLayoutTaglibUtil does it? Please Slack me or send me a pull as well.

**Pull request closed without merging**
