### PR TITLE
LPS-97404 buildService

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
@ealonso @ruben-pulido

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/brianchandotcom/liferay-portal/pull/75142

**Comment by ealonso** [comment]
ci:close

**Pull request closed without merging**
