### PR TITLE
LPS-61064 Adds icon parameter to IconTag to support new Icons

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
cc @natecavanaugh

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@brianchiu see this randomly breaking Poshi test.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/819ebc60a2...f11fd19e58

**Comment by brianchiu** [comment]
@brianchandotcom 
Thanks. Keep cc'ing me on these.

**Pull request closed without merging**
