### PR TITLE
LPS-55156 - Migrate html/css/common into css module

### PR DESCRIPTION
**Pull request by mjbradford89**
Hey Brian,

Attached is an update for https://issues.liferay.com/browse/LPS-55156.

Please let me know if there are any issues.

Thanks!

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by mjbradford89** [comment]
By looking at the error message, it looks like jenkins isn't using the SDK linked in git-commit-plugins. `build-common.xml:206: Sass to CSS Builder generated exceptions.`, when if you look at build-common.xml in the updated sdk, that message is at line 248 (https://github.com/mjbradford89/liferay-plugins/blob/22a7604fe6aa69c7f39db3f67c3afceda3ac548c/build-common.xml#L248).

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@mjbradford89 build errors. Please resend.

**Pull request closed without merging**
