### PR TITLE
LPS-165625 BuildLang

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@ealonso @veroglez this used to be a title case

```
				<ClayButton
					className="btn-monospaced"
					displayType="secondary"
					small
				>
					<ClayIcon symbol={languageIcon} />

					<span className="sr-only">
						{sub(
							Liferay.Language.get(
								'select-a-language.-current-language-x'
							),
							w3cLanguageId
						)}
					</span>
				</ClayButton>
```

**Comment by brianchandotcom** [comment]
@ealonso @veroglez 

But now it's a sentence. Can we find a way to keep a title case or is a sentence case the better one? We usually don't do sentences for "buttons" though.

Please resend. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/df2c9fc5ac...5ca35cf1ce

**Pull request closed without merging**
