### PR TITLE
7.0.x-vw-493

### PR DESCRIPTION
**Pull request by vicnate5**
Backport of https://github.com/brianchandotcom/liferay-portal/pull/42212

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@vicnate5 I merged this, but lots of failures, can you look into it? Thx.

**Comment by vicnate5** [comment]
This one is just a build abort. ci:retest

**Comment by pyoo47** [comment]
We’ve discovered a problem in 7.0.x pull request tester that is causing pull requests to abort when there is a lot of traffic on the cohort. We’re working on a fix and should have something in place soon.

**Pull request closed without merging**
