### PR TITLE
LPS-125162 Fix mismatch between count and find. Use left join to make…

### PR DESCRIPTION
**Pull request by Preston-Crary**
… the results unique and preserve title sorting option.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
@marianoalvarosaiz Please send a follow up pull with a test to cover this case.

You can improve future pulls by doing these things:
- Fix the problem, then make things more maintainable. Because several steps where skipped, there was a bug with sorting by titles and another with permissions not being checked.
- Never add methods to a low level API when there's only 1 usage, those APIs have many users and can easily grow to having too many methods making usage and maintenance more difficult.
- Adding Locale to the method signatures was too risky because content and users may have multiple Locales.
- DSL SPI is meant to be used for query execution and parsing. Only use DSL SPI for query building when there's no other option (which is very rare).

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/08c60278b5...46dac80a10

**Comment by marianoalvarosaiz** [comment]
Hi @Preston-Crary ,

 thanks a lot for your suggestions, but this pull is incorrect due to several reasons:

1. The approach from a code perspective is simple, but from a functional point of view it doesn't make sense. If you have several translations and you want to filter by, for example title, it doesn't make sense to filter among all languages. The same thing happens with the sort option, what's the point among sorting between titles in many different languages? Besides, the query isn't correct, it only uses to filter the first translation provided. So if you, for example, provide a JournalArticle with translations in English (default) and Spanish, it will only be able to find the English translations.
2. Also, because it doesn't use the language as filter in JournalArticleLocalization, it generates a dangerous query involving a Full Scan, see:

```id	select_type	table	partitions	type	possible_keys	key	key_len	ref	rows	filtered	Extra
1	SIMPLE	JournalArticle	NULL	ref	IX_D3ACAD4A,IX_AAF3B581,IX_6D9F9567,IX_F12AB4A3,IX_F97E5289,IX_62EBBA43,IX_70325BE2,IX_6A6363AF,IX_E10314FA,IX_9E386BE0,IX_8A0FEBBE,IX_20E66853,IX_E748358,IX_6CA45D20,IX_1ED664C3,IX_8868DCD0,IX_74060760,IX_D36D9846,IX_E6BD667C,IX_E107E2A9,IX_254CBF60,IX_E7C5046,IX_E20FD06D,IX_B2F1D3FD	IX_D3ACAD4A	9	const	2	50.00	"Using index condition; Using where; Using temporary; Using filesort"
1	SIMPLE	tempJournalArticle	NULL	ref	IX_D3ACAD4A,IX_62EBBA43,IX_70325BE2,IX_6A6363AF,IX_E10314FA,IX_9E386BE0,IX_8A0FEBBE,IX_20E66853,IX_E748358,IX_6CA45D20,IX_1ED664C3,IX_8868DCD0,IX_74060760,IX_D36D9846,IX_E6BD667C,IX_E107E2A9,IX_254CBF60,IX_E7C5046,IX_E20FD06D,IX_B2F1D3FD	IX_D3ACAD4A	237	const,master.JournalArticle.articleId	2	50.00	"Using where; Not exists"
1	SIMPLE	JournalArticleLocalization	NULL	ALL	IX_5593D868,IX_E69312A1,IX_F1F3A975,IX_429AC23C	NULL	NULL	NULL	3	100.00	"Using where; Using join buffer (Block Nested Loop)"
1	SIMPLE	tempJournalArticleLocalization	NULL	ref	PRIMARY,IX_5593D868,IX_E69312A1,IX_429AC23C	IX_5593D868	9	master.JournalArticleLocalization.articlePK	1	33.33	"Using where; Not exists; Using index"
```

The query should be fixed with our previous approach, adding the locale to filter. As it was it only made sense with the previous approach when we were saving the translations in XML inside JournalArticle and we had no clear way to filter based on language, but now that we kind of normalize it, we must filter by language. And that implies adding a new finder or use DSL.

**Comment by marianoalvarosaiz** [comment]
So @Preston-Crary, could we consider following the approach of my pull (adding a new DSL finder including locale) and fixing the problems you encountered on it?

**Comment by Preston-Crary** [comment]
Big picture there wasn't a big problem with _what_ you did.  There was a problem with _how_ you did it.  Change the existing code into what you want instead of creating new code and replacing the usage - that way it's more clear what is being changed and less error prone.  So switch to DSLQuery in the finder impl, or add the locale to the finder impl first.  Don't do both together and move the code outside the finder impl at the same time.  Those 3 steps should be done sequentially.  It's way safer to make big changes in steps like this.  It is slower to make the change, but safety is more important since this finder has had several errors for a long time.

@marianoalvarosaiz Before making this change though we have to figure out if an article doesn't have a translation for the user's locale, do we want it to show up?  Right now it does and I think we do want something to be included in the results when the keyword matches the default locale for the article and not the user's.  For example, I could have a locale that doesn't show any articles even though several articles match my search (because of a missing translation) - that seems wrong to me.

If you change it so if falls back to default locale search as well then I'm fine with the change as long as we change it in the finder impl instead of replacing the call all at once.

I would be happy to review these changes if you can work on them.

**Comment by marianoalvarosaiz** [comment]
@Preston-Crary adding a new finder, with locale as a new parameter (so that queries can filter based on a specific locale), was the initial idea, but it was discarded, see https://github.com/brianchandotcom/liferay-portal/pull/97345#issuecomment-755201216 That's why the approach of adding a new DSLQuery was followed. 

The old method was going to be removed and deprecated for backports calling the new method with the most relevant locale as in https://issues.liferay.com/browse/LPS-84771

**Pull request closed without merging**
