### PR TITLE
LPS-83690 Auto

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/63cc309c84...3648f7125d

**Comment by brianchandotcom** [comment]
@ealonso I fixed your semantic error in 3648f71

**Comment by brianchandotcom** [comment]
@ealonso this also caused a breaking change in site-navigation-api!

In this case, I'm bumping up the version 7.1.x from 1.1.* to 2.0.* and bumping up the version in master (7.2.x) to 3.0.*

If this module was also in 7.0,x, then I couldn't do this.. in general, I do not like major version bumps

**Comment by ealonso** [comment]
@brianchandotcom Thanks you very much!! and this module is only in 7.1.x

**Pull request closed without merging**
