### PR TITLE
WCM-626

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by jpince** [comment]
@brianchandotcom the only poshi failures were due to sybase errors that we are looking into. Good from a functional test perspective.

**Comment by gamerson** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/41f4844dbc...42b5650de0

**Comment by brianchandotcom** [comment]
@juliocamarero @gamerson I'm not the biggest fan of "context" as a request attribute, but I merged it and published a new JAR for you guys anyways.

I also removed the Language.properties keys. That should go in a shared module or else someone will have to translate it every time for every module.

Please see upstream for my changes. Thx.

**Pull request closed without merging**
