### PR TITLE
LPS-95357 Extract upgrade methods from OAuth2ServiceUpgrade to util in upgrade module

### PR DESCRIPTION
**Pull request by topolik**
Hi Brian,

follow up of https://github.com/brianchandotcom/liferay-portal/pull/72823#issuecomment-491030864
> 2.) I like getAddColumnsUpgradeProcess, getDropColumnsUpgradeProcess, and getRunSQLUpgradeProcess. Can you move it to a factory/util/builder in com.liferay.portal.upgrade so that everyone can start copying your pattern? Feel free to rename the methods to make it fit your new factory/util/builder.

/cc @csierra 

Did you mean portal-kernel or this portal-upgrade-api module? Also it's in API module but contains reference to UpgradeProcess which is actually an impl.

Thanks.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/109777082f...b7a8885875

**Comment by brianchandotcom** [comment]
@topolik beautiful

**Comment by Preston-Crary** [comment]
@csierra @topolik this causes SplitPackagesTest to fail on upstream because portal-impl is exporting the same package: com.liferay.portal.upgrade.util.

@michaelhashimoto why is there no test results for unit-jdk8 even though it's listed in test.batch.names[relevant]? I think there's an off by one bug where we're reading this property since it's the last one.

**Comment by csierra** [comment]
please see https://github.com/brianchandotcom/liferay-portal/pull/73445

**Comment by csierra** [comment]
please see https://github.com/brianchandotcom/liferay-portal/pull/73447

**Pull request closed without merging**
