### PR TITLE
LPS-102998 Add a way for users to locally store generic private repo …

### PR DESCRIPTION
**Pull request by CAustin582**
…credentials

### CODE REVIEW

**Comment by CAustin582** [comment]
ci:test:relevant

**Comment by topolik** [comment]
Hi @CAustin582, 

1, Can this be improved to support credentials rotation? E.g. have some public https://files.liferay.com/.DXP_CREDENTIALS.sha512 file with a fingerprint of the private file content and if it doesn't match then ask again to download it?

2, Instead of asking the username & password from a command line, can we instruct user to open the file in a browser and download to a proper place? I don't trust cmd line, it shows password and password manager talks to browsers better.

Thanks.

**Comment by topolik** [comment]
Btw. the best solution would be to have okta integration with nexus. Then we could auto-provision user accounts into nexus and rely on OAuth2 instead of user credentials.

This way when the .DXP_CREDENTIALS leaks (forgotten/stolen) laptop we would not need to rotate it for every developer, just rotate one user access token.

Just saying.

**Comment by jpince** [comment]
BChan said he will work with @petershin on Monday (Oct 14) on option #1 that @topolik suggested

**Comment by CAustin582** [comment]
@topolik 
1. Sure, we can do something like that

2. This script will not display your password in the command line

**Comment by CAustin582** [comment]
ci:test:relevant

**Comment by CAustin582** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@CAustin582 we found a different way to do this.. @petershin has more details.

**Pull request closed without merging**
