### PR TITLE
LPS-71361 SF

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianwulbern** [comment]
"Unable to Fetch with GIT custom fetch" error reported here: https://issues.liferay.com/browse/LRQA-31429

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
ci:stop

**Comment by brianwulbern** [comment]
@rafaprax the other error looks related to the changes:
```
[exec] * What went wrong:
[exec] Could not copy MANIFEST.MF to '/opt/dev/projects/github/liferay-portal/modules/apps/forms-and-workflow/dynamic-data-lists/dynamic-data-lists-test/build/tmp/jar/MANIFEST.MF'.
[exec] > Build has errors
```

**Comment by rafaprax** [comment]
cc @leoadb

**Pull request closed without merging**
