### PR TITLE
Sync 1337

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @shinnlok

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e67aa1f73b...d045743d76

**Comment by shinnlok** [comment]
@shuyangzhou,
What is failing for the need of the second commit?

**Comment by shuyangzhou** [comment]
FileUtilTest.testIsIgnoredFilePath()

**Comment by shuyangzhou** [comment]
So basically, the escape call is not needed, as the input string is already escaped, with that call, it double escaped it, causing the test to fail.

**Comment by shuyangzhou** [comment]
In 16eec9bb6ab0c3116b2fb6ff85c3bcddb5bdd73f, the properties file change you made, the value is already escaped.

**Pull request closed without merging**
