### PR TITLE
master-bw-58

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-28405

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@brianwulbern master only? Thx.

**Comment by brianwulbern** [comment]
@brianchandotcom Sorry, yes, master only.

**Comment by vicnate5** [comment]
@brianwulbern Can you resend?

**Comment by brianwulbern** [comment]
@vicnate5 working on it.

**Comment by brianwulbern** [comment]
@Sharryxue @vicnate5 Resent here: https://github.com/brianchandotcom/liferay-portal/pull/44456

**Pull request closed without merging**
