### PR TITLE
LPS-57247

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
ci:retesst

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by matethurzo** [comment]
rebased and pushed up again. ci:retest

**Comment by matethurzo** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6f84f60336...56b4a40506

**Comment by brianchandotcom** [comment]
Great job guys

**Pull request closed without merging**
