### PR TITLE
LPS-157551 Use value from Freemarker context when rendering text and numeric input fragments

### PR DESCRIPTION
**Pull request by ruben-pulido**
Resend of https://github.com/brianchandotcom/liferay-portal/pull/120303 after solving rebase errors

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:reopen

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@ruben-pulido 1.) can you make

InfoFormConstants.INFO_FORM_PARAMETER_MAP

just a String and remove the constant

I generally only use constants for request / session attributes. In this case, it's just an attribute of the error map, which we usually use strings for

2.) 

			infoFieldValues =
				_infoRequestFieldValuesProviderHelper.getInfoFieldValues(
					httpServletRequest);

and

source-formatter-suppressions.xml

is strange.

Can we remove source-formatter-suppressions.xml and change your code so infoFieldValues is set first? Thx.

Thx

**Pull request closed without merging**
