### PR TITLE
LPS-91961 Set the proper extension for images during the upgrade

### PR DESCRIPTION
**Pull request by achaparro**
cc/ @jcampoy

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
ci:reopen

**Comment by achaparro** [comment]
Errors are unrelated

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/03bb33d4eb...ea9e9da93c

**Pull request closed without merging**
