### PR TITLE
LPD-38877 Prefer TableMapper lookup over DSL.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@tinatian @vicnate5 please backport, thanks!

**Comment by brianchandotcom** [comment]
@shuyangzhou can you rename

staging.groups.in.memory.filter.limit
virtual.hosts.per.company.in.memory.filter.limit
roles.mapping.table.query.limit

to something

xyz.abc.*

I'd like to group all these properties together.

Right now, the hardest part is just the naming.

I'm even with calling it something really stupid like

xyz.blah..limit.LPD-3235=
xyz.blah.limit.LPD-8983=

It's just the naming that's very hard to see.

Thx

**Comment by brianchandotcom** [comment]
@shuyangzhou let's also get rid of the PropsKeys / PropsValues for this and just treat it like feature.flag.LPD-7822.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/155015

**Pull request closed without merging**
