### PR TITLE
LPS-100290 buildService

### PR DESCRIPTION
**Pull request by marcosapmf**

### CODE REVIEW

**Comment by marcosapmf** [comment]
PR reviewed by @brunofarache and @natocesarrego

**Comment by brianchandotcom** [comment]
@marcosapmf @brunofarache please resend:

git grep DDMFormInstanceStagingHelper

modules/apps/dynamic-data-mapping/dynamic-data-mapping-api/src/main/java/com/liferay/dynamic/data/mapping/staging/DDMFormInstanceStagingHelper.java
modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-web/src/main/java/com/liferay/dynamic/data/mapping/form/web/internal/display/context/DDMFormDisplayContext.java
modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-web/src/main/java/com/liferay/dynamic/data/mapping/form/web/internal/portlet/DDMFormPortlet.java
modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-web/src/test/java/com/liferay/dynamic/data/mapping/form/web/internal/display/context/DDMFormDisplayContextTest.java
modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/staging/impl/DDMFormInstanceStagingHelperImpl.java


We are putting something in in api/service that is only ever going to be used in one *-web

So let's just make it a static util in *-web. Please resend.

**Comment by marcosapmf** [comment]
Hi @brianchandotcom ,

We created these classes because we needed to use a method of 

modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/service/http/DDMFormInstanceServiceHttp.java 

and the Source Formatter ask us to call it by the api module instead of do that directly by service module.

Best regards

**Comment by brunofarache** [comment]
@marcosapmf me chama se tiveres precisando de ajuda nisso. brian geralmente não lê comentários em PRs depois de fechados.

**Comment by natocesarrego** [comment]
@brunofarache, eu vou falar direto com Brian no Slack sobre este pull. 😉

**Pull request closed without merging**
