### PR TITLE
LPS-66882 Skip validation of default locale for doUpdateStructure since the default locale is coming from the pre-existing structure anyway

### PR DESCRIPTION
**Pull request by epgarcia**
@marcellustavares @matethurzo

### CODE REVIEW

**Comment by marcellustavares** [comment]
@epgarcia, tests are missing for this pull, could you please send it to me so we can add it?

Thanks

**Comment by epgarcia** [comment]
Sure thing! Thanks @marcellustavares !

**Comment by epgarcia** [comment]
See marcellustavares/liferay-portal/pull/1521 Thanks!

**Comment by marcellustavares** [comment]
thanks @epgarcia!

**Pull request closed without merging**
