### PR TITLE
LRQA-49755 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-49755

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:test:documents

**Comment by austinchiang** [comment]
ci:test:blogs

**Comment by austinchiang** [comment]
ci:test:messageboards

**Comment by austinchiang** [comment]
ci:test:knowledgebase

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
