### PR TITLE
Lps 76783

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@mtambara please backport with changes from @shuyangzhou

**Comment by brianchandotcom** [comment]
@mtambara I didn't remove this module from the whitelist since it's not backported yet.

**Comment by mtambara** [comment]
@brianchandotcom Alright, I'll remove it when I do the backport

**Pull request closed without merging**
