### PR TITLE
LPS-97197 AB Testing - Initial Entity Model

### PR DESCRIPTION
**Pull request by epgarcia**
@marcellustavares

### CODE REVIEW

**Comment by epgarcia** [comment]
@brianchandotcom @jpince please do not backport this. We'll be performing adjustments on the model and services, and once it's stable we'll request their backport.

**Comment by brianchandotcom** [comment]
Thanks @epgarcia @darquesdev Meregd, but I didn't backport

I find the word "Experiment" and "Experience" kind of hard to read (they look too similar)

Can we use a different word? See https://www.thesaurus.com/browse/experiment

Perhaps SegmentsTrial SegmentsTryout SegmentsDryRun 

Feel free to use the existing one if you feel it is best, or Skype me if you need help deciding.

@angeloyoun fyi

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e0e0c5ca4d...64f44fb2d9

**Comment by AngeloYoun** [comment]
Definitely not SegmentsTrial or SegmentsTryout... the concept has nothing to do with a segment. If anything Test could work but that can be confused with our QA tests. 

At least on our customer-facing interfaces, we will most likely refer to the concept as an A/B test or experiment.

**Comment by epgarcia** [comment]
Hi @brianchandotcom,

@marcellustavares and I have the same question about this. Experiment is the only word that semantically reflected the purpose of the entity, given that Test is a reserved word for actual tests. AC is using the same naming on their side. If we find a better name, we'll change it on both sides.

Regards

**Pull request closed without merging**
