### PR TITLE
LPS-66333 buildLang

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by evannagayama** [comment]
@ealonso @brianchandotcom Looks like test fixes are needed. #koor4356 can you look into this and make test fixes? Thanks!

**Comment by brianchandotcom** [comment]
@koor4356 please resend with test fixes.

@ealonso fyi

**Comment by koor4356** [comment]
@ealonso @brianchandotcom I've sent test fixes to @evannagayama here https://github.com/evannagayama/liferay-portal/pull/750. Thanks!

**Pull request closed without merging**
