### PR TITLE
LPS-145876 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-145876

This is only for master.

@ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure test is unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/7274
❌ ci:test:stable - 27 out of 33 jobs passed
❌ ci:test:relevant - 27 out of 34 jobs passed in 2 hours 35 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3860b4af5d...7183d43a0f

**Comment by brianchandotcom** [comment]
@ealonso just 7183d43a0f797f554f660f4e9752d75a30c4ab42 thx

**Pull request closed without merging**
