### PR TITLE
Lps 78901

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7e420df75a...34cb8b8d0f

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@lawrence-lee @gamerson can you guys update the Blade samples? The latest Service Builder will require one less build.gradle dependency (osgi.util). Having it won't hurt, but will pollute the samples.

Please update the project-templates. Thx @lawrence-lee

**Comment by brianchandotcom** [comment]
@ithildir fyi my comment to:

@lawrence-lee @gamerson can you guys update the Blade samples? The latest Service Builder will require one less build.gradle dependency (osgi.util). Having it won't hurt, but will pollute the samples.

Please update the project-templates. Thx @lawrence-lee

**Comment by gamerson** [comment]
Will do.

**Pull request closed without merging**
