### PR TITLE
LPS-59485 User with permission to add user group cannot add one

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-59485](https://issues.liferay.com/browse/LPS-59485).<br><br>Hey Brian, I think these are good changes to start with.  In regards to the PermissionUtils that take an ID instead on an entity, there are a few:
- UserGroupPermissionUtil.java
- RolePermissionUtil.java
- LayoutSetPrototypePermissionUtil.java
- LayoutPrototypePermissionUtil.java
- EmailAddressPermissionUtil.java

I looked at them, and they neither extract the groupId from an entity or get the entity from the ID.  As far as optimization goes, I don't see any benefit to changing the permission check to use the entity.  Thoughts?

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3c97c7d223...9ed72c4465

**Comment by brianchandotcom** [comment]
Nice job on this @drewbrokke 

You actually unintentionally fixed a bug in modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/service/impl/DDMStructureServiceImpl.java

it was calling

DDMStructure ddmStructure = ddmStructurePersistence.fetchByG_C_S(groupId, classNameId, structureKey

and now it calls

DDMStructure ddmStructure = ddmStructureLocalService.fetchStructure(groupId, classNameId, structureKey

In the LocalService, we normalize structureKey before do the fetch.

Can you check liferay-plugins as well? Thx.

**Comment by drewbrokke** [comment]
Will do.  Thanks @brianchandotcom!

**Pull request closed without merging**
