### PR TITLE
LPS-68054 SF

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ef25642b76...293cd4ea5e

**Comment by brianchandotcom** [comment]
@adolfopa can you backport? Specifically, see modules/private/post-upgrade-fix/post-upgrade-fix-LPS_66133/src/main/java/com/liferay/post/upgrade/fix/LPS_66133/PostUpgradeFixOSGiCommands.java

Thx.

**Comment by brianchandotcom** [comment]
@ZoltanTakacs  fyi

**Comment by adolfopa** [comment]
@jorgediaz-lr will take care of that. When he's finished he'll send a PR to @ZoltanTakacs.

See https://github.com/jorgediaz-lr/liferay-portal-ee/pull/96

Thanks!

**Pull request closed without merging**
