### PR TITLE
LPS-95409 Add languageId parameter so that CSSs are reloaded by senna

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:test

**Comment by jpince** [comment]
ci:test:wem-msb

**Comment by pyoo47** [comment]
```
The CI test suite 'wem-msb' is not a valid test suite.
```

**Comment by jpince** [comment]
@brianchiu @kyle-miho has the wem-msb test suite worked before? Not sure if it just needs to be added to `ci.properties`?

**Comment by jpince** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
@jpince it worked a month ago
https://github.com/brianchiu/liferay-portal/pull/1870

**Comment by pyoo47** [comment]
@kyle-miho We recently added some validation logic to check whether or not the test-suite name provided is valid. Prior to that, using an invalid test-suite name would just trigger the default test-suite. The test that ran in https://github.com/brianchiu/liferay-portal/pull/1870 was most likely just the default test.

CC:@yichenroy

**Comment by yichenroy** [comment]
@jpince @kyle-miho 
The suite validation checks [ci.properties](https://github.com/liferay/liferay-portal/blob/master/ci.properties) for a list of valid suites. Jason is right, if the suite worked before then you just need to make sure the name is also added to [ci.properties](https://github.com/liferay/liferay-portal/blob/master/ci.properties) when you add/test the new suite.

cc @pyoo47

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
