### PR TITLE
LPS-78082 Adding language files

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by jpince** [comment]
@petershin can't find the reason for this error, please help?

**Comment by petershin** [comment]
@jpince - Looking into it

**Comment by 4lejandrito** [comment]
Hi @jpince , @petershin,

Please let me know if I can do something to push this forward.

The error: 

` Missing language key 'configuration-kb-object': ./modules/apps/knowledge-base/knowledge-base-web/src/main/resources/META-INF/resources/display/configuration.jsp (SourceCheck:JSPLanguageKeysCheck)`

is unrelated to my changes if it helps.

Thanks!

**Comment by petershin** [comment]
@4lejandrito - Appreciate the help!  It seems like this file should be ignored.  [knowledge-base/source-formatter.properties#L9](https://github.com/liferay/liferay-portal/blob/master/modules/apps/knowledge-base/source-formatter.properties#L9)

The problem is the SF module doesn't honor exclusions when running `format-current-branch`.  I'm just checking whether this is intentional before changing it.

**Comment by hhuijser** [comment]
ci:retest

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@4lejandrito can you resend?

1.) Please rename getPostUrl to getPostURL

2.) There's a lot of inconsistency in how you use the plural for bookmarks, vs. bookmark that I find very confusing.

For example:

modules/apps/knowledge-base/knowledge-base-web/src/main/resources/META-INF/resources/admin/common/article_social_bookmarks.jsp

SocialBookmarksUtil.getSocialBookmarkTypes(socialBookmarksTypes)

vs.

modules/apps/knowledge-base/knowledge-base-web/src/main/java/com/liferay/knowledge/base/web/internal/social/SocialBookmarksUtil.java

getSocialBookmarkTypes(String socialBookmarkTypes)

So is it socialBookmarkTypes or socialBookmarksTypes?

I see it in many many places where the usage of the plural and singular is not consistent.

Please fix and resend.

**Pull request closed without merging**
