### PR TITLE
Lps 83456 fix

### PR DESCRIPTION
**Pull request by arthurchan35**
@brianchandotcom ,
Sorry I didnt want to send you pull directly, but it's been few days that one of the layout test just cannot start testable tomcat
https://github.com/liferay-appsec/liferay-portal/pull/118#issuecomment-698114127

This pull has been reviewed by @shuyangzhou, and it was previous passing all tests:
https://github.com/shuyangzhou/liferay-portal/pull/9451

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by arthurchan35** [comment]
@brianchandotcom
CI finally passes all tests again:
https://github.com/liferay-appsec/liferay-portal/pull/119
Same pull

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2f68e17e63...7af809f2c9

**Comment by brianchandotcom** [comment]
@arthurchan35 please see changes in my origin.

**Pull request closed without merging**
