### PR TITLE
LPS-86377 resolution failures and deadlocks during startup

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:test

**Comment by rotty3000** [comment]
ci:reopen

**Comment by rotty3000** [comment]
@brianchandotcom I see there are conflicts here... this PR was the fix and it looked good.

**Comment by brianchandotcom** [comment]
Hey @rotty3000 

I rolled back the changes because we're getting too close to the release.

Can you resend this pull, along with the reverts (undo them) from b72cedad4d466784e58a0c36bde0175daa4f303a to 6abfeb15a4b4cee459015d20cdf90cdaa028225e (you could even squash and do one commit)

Then we could test them all together more robustly. Can you send it to @shuyangzhou (consolidated pull)

Thx!

**Pull request closed without merging**
