### PR TITLE
LPS-128928 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-128928

This is only for master.

@lfbesada

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tasks are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/6613
✔️ ci:test:stable - 10 out of 10 jobs passed
❌ ci:test:relevant - 15 out of 20 jobs passed in 2 hours 10 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9a020c84b2...568c7b13ca

**Comment by brianchandotcom** [comment]
@lfbesada see cf511b7d2f498ed841409ae95670b0dbe56ce0e2 if I'm wrong, please send me a revert

**Comment by brianchandotcom** [comment]
@lfbesada and ec9777dfe3f6edf5e2f3ae91314bac79090d266d too

**Pull request closed without merging**
