### PR TITLE
LPS-61748 gradle cache

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by rotty3000** [comment]
I hope we can declare victory in this!

**Comment by rotty3000** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
I think we're actually good. I've seen those fail randomly before.

But just for fun.. ci:retest

**Comment by brianchandotcom** [comment]
Yey! It's green @rotty3000 !!!

I'm publishing the jars and will push everything up.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/283ee59ad4...18a567b82f

**Pull request closed without merging**
