### PR TITLE
LPS-61820 MVCCommand locator for ConfigurationIcons

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @ealonso @robertoDiaz

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
@brianchandotcom this is a real test failure. I'll work on that and resend a pull.

**Pull request closed without merging**
