### PR TITLE
LPS-172619 Make IdP redirect message hidable

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Hi Brian. Forwarding liferay-appsec/liferay-portal/pull/974 direct because getting unrelated `ci:test:relevant` failures and `ci:forward:force` appears to require that to pass. Thanks!

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@stian-sigvartsen @mbowerman can we make this a Configuration so it can be toggled from a GUI rather than a bnd property?

If I'm missing some context, Slack me.

Please resend. Thx.

**Comment by stian-sigvartsen** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@stian-sigvartsen please resend with a portal.property.

**Pull request closed without merging**
