### PR TITLE
LPS-62787 need to explicitly set osgiModule true to work across both workspace and non-workspace external modules

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
@brianchandotcom this should be all of the changes we need to get a new blade-cli released that works for all of our templates both in and outside of workspace.  once these changes are published as `com.liferay.gradle.templates:1.0.3` then I can release blade-cli 1.0.0 over on `releases.liferay.com/tools/blade-cli/1.0.0`

thanks

**Comment by gamerson** [comment]
ci:retest

**Comment by gamerson** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/37dd42be71...804a7a1349

**Comment by brianchandotcom** [comment]
@gamerson I made a few changes and published a new jar for you. See upstream. Thx!

**Pull request closed without merging**
