### PR TITLE
Lps 70241

### PR DESCRIPTION
**Pull request by shuyangzhou**
Resent of https://github.com/brianchandotcom/liferay-portal/pull/46357 with more changes

### CODE REVIEW

**Comment by tinatian** [comment]
cc @slnn

**Comment by tinatian** [comment]
@shuyangzhou Just confirm with Lily, Assetpublisher test does not work right with this change, she will work on this.

**Comment by brianchandotcom** [comment]
@shuyangzhou @tinatian I will merge after Asset publisher test works.

Please resend.

**Comment by shuyangzhou** [comment]
ci:reopen it is actually working.

**Comment by slnn** [comment]
@shuyangzhou @tinatian 

Test this pull in benchmark env,  Asset publisher worked well

Thanks
Lily

**Comment by brianchandotcom** [comment]
@shuyangzhou can you resend but avoid chaining?

${dataFactory.getCSVWriter("blog").write(

Thx.

**Comment by brianchandotcom** [comment]
@shuyangzhou merged. Can you backport this? I think this will actually mean fewer deviations between the branches.

**Comment by shuyangzhou** [comment]
@tomwang2011 backport please.

**Pull request closed without merging**
