### PR TITLE
master-qa-28968

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LPS-69128

@brianchandotcom This is a **master only** change as #44602 was merged only to master. Backport to 7.0.x will be handled under [BPR-7599](https://issues.liferay.com/browse/BPR-7599).

### CODE REVIEW

**Comment by anthony-chu** [comment]
@brianchandotcom unrelated failure.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@anthony-chu how did it break twice? We test every broken batch twice. We may have a fluke test.

**Comment by anthony-chu** [comment]
@brianchandotcom that test belonged to a batch that had a failure. `CPPagetemplates#AddPageTemplate` passed on the first run but failed on the second run.

**Pull request closed without merging**
