### PR TITLE
[See description] LPS-66029 Lexicon Knowledge Base main view

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey Brian,

I sent you a mail about this pull. It seems that it doesn't compile in the CI but it compiles locally when running "ant all".

I don't know what could be the reason...

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @robertoDiaz

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@sergiogonzalez will resend.

**Pull request closed without merging**
