### PR TITLE
LPS-60606 Move configuration icon logic to their own portlets

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
Reviewed by: @juliocamarero

CC:/ @matethurzo

**Comment by juliocamarero** [comment]
:+1:

**Comment by matethurzo** [comment]
Thank you @jkappler and @juliocamarero, muy bien, sehr gut :)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d30b7827cb...f69628fb00

**Comment by brianchandotcom** [comment]
@jkappler see f69628fb00a0fc35f7e25462e720f04cb7a6ebd3 I moved it to a different package to be consistent with existing classes.

**Pull request closed without merging**
