### PR TITLE
LPS-74951 Enable Adaptive Media tests

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:stop (The build is frozen)

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest https://loop.liferay.com/home/-/loop/feed/7636012

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
ci:retest

**Pull request closed without merging**
