### PR TITLE
LPS-83949 Create a servlet to be able to invoke the resolution service from the browser

### PR DESCRIPTION
**Pull request by izaera**
This PR finishes all the core code we need to resolve modules. We need another one to switch the old stuff by the new one, but it will be more pipe changing than real logic.

### CODE REVIEW

**Comment by izaera** [comment]
@brianchandotcom this is missing the movement of servlets from `internal` to `internal.servlet`, but I will do it in the following PR

**Comment by izaera** [comment]
CI looks broken :grimacing:

**Comment by brianchandotcom** [comment]
```
					String errorMessage = StringBundler.concat(
						":ERROR:Missing version constraints for ",
						dependencyPackageName, " in package.json of ",
						jsPackage.getResolvedId());
```

Is :ERROR: some kind of well known pattern? Just curious. See JSLoaderModulesServlet and JSBrowserModule (please email me back)

merged.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9ef646b13e...e5ebe34cb0

**Comment by brianchandotcom** [comment]
@izaera also, I did make one change in e5ebe34cb042a652200808eb93b042803fd64a62

**Comment by brianchandotcom** [comment]
@izaera and 6b2b55e..

**Pull request closed without merging**
