### PR TITLE
LPS-57859 Remove doAsGroupId from all unnecessary places (scopeGroupId). Replace with the right url from PortalUtil in the rest of places.

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
cc @jorgeFerrer @sergiogonzalez @marcellustavares @pei-jung @drewbrokke

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/198b7660f2...e713a42d6d

**Comment by brianchandotcom** [comment]
Very nice @juliocamarero

**Pull request closed without merging**
