### PR TITLE
LPS-195626 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://liferay.atlassian.net/browse/LPS-195626

@ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/13631

**Comment by brianchandotcom** [comment]
@ealonso conflcit, can you rebase and resend it to me directly ? Thx.

**Comment by ealonso** [comment]
resend here: https://github.com/brianchandotcom/liferay-portal/pull/140740

**Pull request closed without merging**
