### PR TITLE
LPS-74242 Auto

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
ci:retest (for the lpkg startup error)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ede7bdeb7d...65b5484d58

**Comment by brianchandotcom** [comment]
@ealonso please see my changes in upstream. Thx.

**Pull request closed without merging**
