### PR TITLE
Lps 56544

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5b69e80e41...e890ca34e2

**Comment by brianchandotcom** [comment]
Very nice @shuyangzhou I assume osgi/static is on purpose? Thx.

**Comment by brianchandotcom** [comment]
@rotty3000 see shuyang's changes to improve Log4j. I worked with him on this one. Thx.

**Comment by shuyangzhou** [comment]
Yes, this bundle is started by ModuleFrameworkImpl, not but fileinstall, we need it to start before every other bundles that created by us (whom could possibly having a META-INF/module-log4j.xml)

**Comment by rotty3000** [comment]
I'm ok with the design. It's fine starting where it is.

However, there are ways to make it so this not necessarily have to start
earlier. All you need is a Provide-Capability header on this bundle and
generate a peer Require-Capability header on bundles that have the log
configuration files.

Just sayin'

**Comment by shuyangzhou** [comment]
Sure, that could work (in a sense), but the problem we had here is, before the change, we already have 4 modules having the portal-log4j.xml, but not declaring any way to get it loaded. People copy and paste things, and assume it would just work. Require-Capability will work, but just a different way for declaration.

If people already forget to declare ServiceConfigurator in the past, I am sure someone will keep forgetting Require-Capability in the future. The static pre-start is indeed a bit "overkilled", but at least, no one will forget about it as there is nothing they need to remember, just keep copy and paste the module-log4j.xml, it will automatically work.

**Comment by rotty3000** [comment]
You missed part of the my comment. Generate the header!

**Comment by shuyangzhou** [comment]
Ok, I missed that. That will take away the manual declare overhead.

But, just to clear out one thing, once Require-Capability is used. If for any reason the log4j configurator bundle is missing, will those bundles with "Require-Capability" still start?
It will be too strict to reject a bundle just because its customized logging level can not be configured.

**Comment by rotty3000** [comment]
That's a fair point.

**Comment by rotty3000** [comment]
Actually, I have one caveat with that... does this mean it can NEVER be
started later?

What if it's restarted/updated?

**Comment by shuyangzhou** [comment]
Do you mean the log4j extender or the bundles with module-log4j.xml?

They all can, just the log4j extender has to be manually managed, as it is not managed by fileinstall.

Rerun log4j configuration is always safe, the worst case is losing manual settings via control panel, they are not persistented anyway.

The only thing we need to ensure is, on portal boot up, the configurator needs to run first. Before other bundle prints out any log. The reason that I started this whole thing is to mute spring extender's annoying log from bundle activator. That's why I am tracking starting, rather than active state.

**Pull request closed without merging**
