### PR TITLE
Lps 81670 2

### PR DESCRIPTION
**Pull request by shuyangzhou**
@hhuijser bad SF check, please fix it.
```
     [java] No need to use static block for method call '_portalServletURLPatterns.addAll'. See https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/documentation/static_block.markdown: ./portal-impl/src/com/liferay/portlet/AsyncPortletServletRequest.java 194 (Checkstyle:StaticBlockCheck)
```
@dantewang see https://github.com/brianchandotcom/liferay-portal/commit/444ce085377a0eece918f7e0f6efb73aca015ac5, if necessary send me a follow up.

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fb50fd4a0f...2165451755

**Comment by brianchandotcom** [comment]
@shuyangzhou SF is right. See fix in 285a85682155211d5bb647e72b6948591d514b5f

@hhuijser fyi

**Comment by shuyangzhou** [comment]
@brianchandotcom that's not right, we should not make that change. We are creating a new class for no reason.

**Pull request closed without merging**
