### PR TITLE
LPS-79815 Keeping the data-fileEntryId in export/import

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test

**Comment by timpak** [comment]
ci:close

**Comment by timpak** [comment]
@4lejandrito there is a modules-unit and modules-integration-* failure that look related to this PR. Can you take a look into them please?

**modules-integration failure**
AMJournalArticleStagedModelDataHandlerTest > testExportFailsWithInvalidReferences
java.lang.AssertionError: Expected exception: com.liferay.portal.kernel.exception.PortalException

**modules-unit failure**
AMBackwardsCompatibilityHtmlContentTransformerTest > testReplacesImageTagsWithLegacyContent
org.junit.ComparisonFailure: expected:<<p>Prefix[[REPLACED]]Suffix</p>> but was:<<p>Prefix[]Suffix</p>>

**Comment by 4lejandrito** [comment]
Hi @timpak,

See https://github.com/brianchandotcom/liferay-portal/pull/57469.

Thanks!

**Pull request closed without merging**
