### PR TITLE
LPS-73737 SF

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by anthony-chu** [comment]
@brianchandotcom poshi fix submitted here: https://github.com/brianchandotcom/liferay-portal/pull/51910

**Comment by brianchandotcom** [comment]
@inacionery can you resend? Rebase error. Thx.

**Comment by inacionery** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/51914

**Pull request closed without merging**
