### PR TITLE
LPS-112992 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-112992

This is only for master.

@ealonso
@manoelcyreno

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources more than they already are, I'm sending the commit directly.
See https://github.com/liferay-echo/liferay-portal/pull/861 Reference the last report from the same PR
https://testray.liferay.com/home/-/testray/case_results/1202311538

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4e75168cb6...a9b0b50993

**Comment by brianchandotcom** [comment]
Thx @Tim-Cao for making the right call.

**Comment by Tim-Cao** [comment]
@brianchandotcom  You're very welcome.

**Pull request closed without merging**
