### PR TITLE
LPS-124743 Change top referral help messages accordingly to the actual number of pages/domains, 10

### PR DESCRIPTION
**Pull request by darquesdev**
Hi @brianchandotcom, manually forwarding because of unrelated failing test in the original PR. Please, see:
- https://github.com/liferay-tango/liferay-portal/pull/666
- And https://liferay.slack.com/archives/C19PWQ74J/p1607606653244500

**Motivation**:
Update the number of pages/domains in the help messages with the right value of **10**. Currently, the info is wrong:

Top referring pages from 30 to 10
image

Top referring domains from 5 to 10
image

**Solution**: 
[Change copies
](https://github.com/liferay-tango/liferay-portal/pull/666/commits/d928d62d9880fdd765e8bf7991a291434d758a1e)

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:reopen

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c8ae69d407...c1512b1bc3

**Pull request closed without merging**
