### PR TITLE
LPS-69125

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-69125.

NOTE: We will be updating and standardizing the HTML markup in the info panel sidebar using https://issues.liferay.com/browse/LPS-69337.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by jonmak08** [comment]
ci:reopen

**Comment by jonmak08** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@shuyangzhou I've seen unit-jdk8 time out twice now

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
