### PR TITLE
LPS-61825 add delete button for pages in the product menu

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @matethurzo this will add the delete icon for pages in live

**Comment by matethurzo** [comment]
Thank you!

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/734de4cd8b...e5cac4d0a8

**Pull request closed without merging**
