### PR TITLE
LPS-79248

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@shuyangzhou, turns out we had this check all along, problem was that this was done before we modularized portal, so it was only working for `portal-kernel`

**Comment by shuyangzhou** [comment]
@hhuijser good, then we just need to port it to modules too, right?

**Comment by hhuijser** [comment]
@shuyangzhou, this pull should be enough

**Comment by hhuijser** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
