### PR TITLE
LPS-64277 ant build-service

### PR DESCRIPTION
**Pull request by adolfopa**
@brianchandotcom This is the main KB pull, where I move everything into an OSGi module. I've left out a bunch of important stuff (mainly upgrades), because the pull is already huge. I'll send the rest in upcoming PRs.

Sorry for this gigantic monster, but I couldn't make it smaller without breaking things.

Thanks!

/cc @sergiogonzalez

### CODE REVIEW

**Comment by adolfopa** [comment]
btw, I've also included here the fwd port for LPS-65200, that I sent earlier today for 6.2.x. Thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5b07d9b29c...9d1526c6a1

**Comment by brianchandotcom** [comment]
Very nice job on this @adolfopa 

1.) For 4d77d37d2074eb8b798789012ab25b05c192dddd can you undo that and follow the pattern of putting the references in the Base*.java class. Then change bnd.bnd and add "-dsannotations-options: inherit"

Then it'll inherit the references so you don't have to have all that duplicate and you can just use the "protected varNameHere".

2.) @hhuijser Can you 2 of the SF bugs

./modules/apps/knowledge-base/knowledge-base-service/src/main/resources/portlet.properties

and

missing language key: configuration-kbobject ./modules/apps/knowledge-base/knowledge-base-web/src/main/resources/META-INF/resources/display/configuration.jsp

3.) @hhuijser also, he has some duplicated Language keys.

I temporarily ignored all of knowledge-base from SF to get this pull in.

4.)  @Ithildir the commit log is a good/fun read for how to port a portlet in case you're curious.

**Comment by brianchandotcom** [comment]
@adolfopa you also need to remove the inclusion of RSS via util-java.jar. We have a petra jar for that now. So no need for Rome, or the other dependencies either. Search for petra-rss and see how the other modules use it.

Thx @adolfopa

**Comment by shuyangzhou** [comment]
@brianchandotcom this pull caused 3 sybase nodes broken and hang. Now every pull is hanging for 2 hours.

**Pull request closed without merging**
