### PR TITLE
Revert "LPS-88492 Add test for pages admin table display style"

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LPS-91271
https://issues.liferay.com/browse/LPS-88492

This is for master only. Removing the test since flattened view was removed.

### CODE REVIEW

**Comment by jpince** [comment]
ci:reopen @brianchiu please retest if needed

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:stop

**Pull request closed without merging**
