### PR TITLE
LPS-171602

### PR DESCRIPTION
**Pull request by tinatian**
FYI @shuyangzhou

### CODE REVIEW

**Comment by tinatian** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c25222a2a9...0d488f2a27

**Comment by brianchandotcom** [comment]
@tinatian see 0d488f2a27ddb3c72ac4686379e82e271ddd5f7b

**Comment by brianchandotcom** [comment]
@LuisOrtiz89 see 0d488f2a27ddb3c72ac4686379e82e271ddd5f7b

**Pull request closed without merging**
