### PR TITLE
LPS-52966 OSGIfy AssetEntryQueryProcessors

### PR DESCRIPTION
**Pull request by juliocamarero**
@csierra

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3c0e53b6f5...8e08451204

**Comment by brianchandotcom** [comment]
Wow. This is amazing.. and this pull is another prime example of why moving to osgi is the right decision @rotty3000

**Pull request closed without merging**
