### PR TITLE
LPS-58119

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@Ithildir FYI

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/241c20c4b3...cb9743bbd3

**Comment by brianchandotcom** [comment]
@ehan please see my changes in upstream.

Good job on the refactor to the new API...

**Pull request closed without merging**
