### PR TITLE
LPS-57564 control panel entries shouldn't skip the logic from the base unless really needed

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @ealonso

**Comment by juliocamarero** [comment]
@marcellustavares can you please review my changes in the WorkflowControlPanelEntries? I think they should behave this way but I would like you to confirm. thanks!

**Comment by juliocamarero** [comment]
@sergiogonzalez can you please review my changes in the SocialActivityControlPanelEntry? I think it should behave this way but I would like you to confirm. thanks!

**Comment by juliocamarero** [comment]
@drewbrokke @pei-jung can you please review my changes in the UsersControlPanelEntry? I think they should behave this way but I would like you to confirm. thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9c023852d1...53b2a8f460

**Pull request closed without merging**
