### PR TITLE
LPS-101832 baseline

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jpince** [comment]
@brookedalton are all of these tests failing in upstream?

**Comment by brianchandotcom** [comment]
@ealonso I'm merging this, and I'm allowing the breaking change in the API (it's not a true breaking change)

I'm going to publish new jars in 7.1.x and 7.2.x to ensure backwards compat.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f73df48bd6...386423ab23

**Pull request closed without merging**
