### PR TITLE
LPS-53730 remove PortletURL from the indexers in order to decouple the portlets from the indexer

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/caf45ea78d...da172c8e85

**Comment by brianchandotcom** [comment]
@ealonso can you fix plugins (they should be broken now). Thx.

**Comment by brianchandotcom** [comment]
Woops. I merged this in before checking for test results. Hope I didn't break master!

**Pull request closed without merging**
