### PR TITLE
LPS-157985 Modify path in macro to select structure on template modal

### PR DESCRIPTION
**Pull request by ealonso**
Manually forward since the tests failures are not related with the code in this pr, please see: https://github.com/liferay-lima/liferay-portal/pull/3240#issuecomment-1186028472

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/80e9c102dc...fd09a8c088

**Comment by brianchandotcom** [comment]
@ealonso just fd09a8c0883ce0ad1164249517355b9050befe38 thx

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c0c97cae37...c0c97cae37

**Pull request closed without merging**
