### PR TITLE
LRQA-53203 | master

### PR DESCRIPTION
**Pull request by GinsonRen**
https://issues.liferay.com/browse/LRQA-53203

### CODE REVIEW

**Comment by jpince** [comment]
@GinsonRen thank you!

@kenjiheigel

**Comment by jpince** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@GinsonRen I merged this.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/58740553bc...673b809bc8

**Pull request closed without merging**
