### PR TITLE
LPD-25316 Skip NPMRegistryUpdatesListener notifying on deactivation.

### PR DESCRIPTION
**Pull request by shuyangzhou**
@victorhcunha similar to previous pulls, but this time do the **SHUTDOWN** profile "Events -> File -> (all sub items)" compare, thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4d5e7ac280...b255d927a4

**Comment by victorhcunha** [comment]
Hi @shuyangzhou !
The results are available: [Time and Profile Compare for LPD-25316](https://docs.google.com/spreadsheets/d/182Rm0bde55BD0mxgNcY0W02kyZYRQ3BiBJkodBD5vVs/edit#gid=0)

For the shutdown profile we config the Yourkit following this [steps 1-6](https://liferay.atlassian.net/wiki/spaces/ENGCOREINFRA/pages/2775973982/Setting+Up+YourKit+to+Collect+Profiling+Results#%5BhardBreak%5DSetup-YourKit) and with the (warmed) portal running, we run the tracing profile with the settings `walltime=*` and `adaptive=false` to collect the shutdown data.

When the tests were running the last PR ( #150049) had not yet synced with the Master.

Let me know if any adjustments to the test are needed.


cc/ @TitoKenzo

**Comment by shuyangzhou** [comment]
@victorhcunha no, this is not right, the shutdown profile should be automated from the benchmark tool.

@tinatian @dantewang, when I originally sent the auto profile code to Anna, the whole process was automated. Right after startup is done, it captures snapshot, does a data clear to wipe out all data collected for startup, then continue with shutdown, then automatically captures a shutdown snapshot from jvm exit. So basically every profile run should capture 2 snapshots. Please confirm this is in benchmark tool, if not it needs to be added.

**Comment by victorhcunha** [comment]
Oh! Sure, I can see now
The snapshot file for shutdown is saved in a different directory.
I updated the [spreadsheet](https://docs.google.com/spreadsheets/d/182Rm0bde55BD0mxgNcY0W02kyZYRQ3BiBJkodBD5vVs/edit#gid=1452227918) with the right results.

**Comment by shuyangzhou** [comment]
ok, this looks correct now, thanks!

**Pull request closed without merging**
