### PR TITLE
LPS-73765 

### PR DESCRIPTION
**Pull request by ctampoya**
https://issues.liferay.com/browse/LPS-73675

cc @leoadb @rafaprax @vicnate5

### CODE REVIEW

**Comment by leoadb** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:reopen

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bb2694c91b...3fd344bfab

**Pull request closed without merging**
