### PR TITLE
LPS-62553 make these portlets system so that they don't show up in the permissions UI

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @jorgeFerrer @drewbrokke

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5720ca3fb6...31f3e80b98

**Pull request closed without merging**
