### PR TITLE
LPS-61420

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@brianchandotcom

That last commit shows exactly why it's too dangerous for SF to do this :)
(and it proves our tests are doing a great job...)

**Comment by hhuijser** [comment]
ci:retest

**Comment by hhuijser** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@hhuijser this one still has an SF error, can you resend? Thx.

**Comment by hhuijser** [comment]
@brianchandotcom 

You mind reopening? This was already fixed in last commit (which I guess came just after the test had started)

**Comment by hhuijser** [comment]
ci:retest

**Comment by hhuijser** [comment]
nvm, I'll just resend...

**Pull request closed without merging**
