### PR TITLE
Lps 72631

### PR DESCRIPTION
**Pull request by shuyangzhou**
@brianchandotcom this is for the lpkg-override CI hanging debug, and we actually already got a hit, and we know it is caused by https://github.com/brianchandotcom/liferay-portal/pull/49007 https://github.com/brianchandotcom/liferay-portal/pull/49007/commits/235906bb1e319ced52af6342dd2842e2cb33cff4
That pull was tested 3 times, and they were all hung on the lpkg-override-jdk8 batch.

@mtambara is working on a solution now.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/859d1fad77...593fb63e88

**Comment by brianchandotcom** [comment]
@shuyangzhou @mtambara see 593fb63e88cf6c7674d476f9ee8ca71e0c46521e

I merged it in for you already

**Comment by brunobasto** [comment]
Hey @shuyangzhou @mtambara, let us know if there's anything we can help with. Me and @rafaprax  are also trying to figure out what in our changes could have caused that.

**Comment by shuyangzhou** [comment]
@brunobasto see fix at https://github.com/brianchandotcom/liferay-portal/pull/49052

**Comment by brunobasto** [comment]
Thank you!

**Pull request closed without merging**
