### PR TITLE
LPS-52826 Add Ant target for executing node and npm commands

### PR DESCRIPTION
**Pull request by ipeychev**

### CODE REVIEW

**Comment by ipeychev** [comment]
Hello Brian,

This PR depends on [that one](https://github.com/brianchandotcom/liferay-plugins/pull/4153). Also, a new copy of the SDK should be added in Portal.

Credits to @csierra, who helped me a lot with these Ant tasks.

Thanks,

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ad8cc2ceac...81d3916eec

**Comment by brianchandotcom** [comment]
@ipeychev can you test with my changes? thx.

**Pull request closed without merging**
