### PR TITLE
LPS-84119

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by jpince** [comment]
@xbrianlee @joshchong please look into OAuth2 POSHI test failure

**Comment by xbrianlee** [comment]
@jpince Team is investigating https://issues.liferay.com/browse/OAUTH2-237

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@hhuijser can you start sending pulls to 7.1.x? These are getting harder to cherry pick now.

**Pull request closed without merging**
