### PR TITLE
LPS-72999

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-72999.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@jonmak08 that needs to go to the subrepo com-liferay-dynamic-data-mapping

Please resend to the subrepo.

**Comment by jonmak08** [comment]
Thanks for clarifying @brianchandotcom! 

New Pull Request: https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/490

**Comment by jonmak08** [comment]
Thanks for clarifying @brianchandotcom! 

New Pull Request: https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/490

**Comment by jonmak08** [comment]
Thanks for clarifying @brianchandotcom! 

New Pull Request: https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/490

**Pull request closed without merging**
