### PR TITLE
LPS-72116 portal-search-test-util: DocumentFixture must not truncate sortable fields at zero chars

### PR DESCRIPTION
**Pull request by arboliveira**
https://issues.liferay.com/browse/LPS-72116

### CODE REVIEW

**Comment by arboliveira** [comment]
Failure seems unrelated.

Portal startup appears to have randomly halted on `Initializing Spring root WebApplicationContext`; I got the same problem yesterday working on something else. After a lot of investigation, was able to get unstuck by deleting `osgi/state` as suggested here:

https://github.com/liferay/liferay-portal/commit/7f3b799a4a837b01c3a64e30ff66041aa423ba60

It does look like a timeout + warning combo like that one could be helpful during development and tests?

**Comment by arboliveira** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@arboliveira should this be backported? If so, please send.

**Pull request closed without merging**
