### PR TITLE
LPS-59288 Get locale from group's default language before calculating it from company's default.

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
I restarted this test on 10/15/15 at 12:20pm.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a9955bc02c...78adb02559

**Comment by brianchandotcom** [comment]
@zxdgoal please add an integration test. Thx.

**Comment by zxdgoal** [comment]
I will take care of it.

**Pull request closed without merging**
