### PR TITLE
LPS-86455

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
This doesn't make any sense to me? I don't see FileVersionPreviewEventListener in 7.1.x or 7.0.x

Or DLFileEntryPreviewType in 7.1.x or 7.0.x?. Please resend.

**Comment by zsoltbalogh** [comment]
@adolfopa, please let me know if you need some help with this PR. It has a long history I haven't had a chance to review yet, but happy to help if you are stuck.

**Comment by AngeloJ** [comment]
@adolfopa, we discussed with Shuyang today and are working on a solution that may not need a commit in master. For now please hold off on working on this.  If you have any questions please message me. 
Thanks

**Comment by adolfopa** [comment]
@AngeloJ @zsoltbalogh Sorry guys, I missed Brian's response.  I'll wait until Angelo pings me.

Thanks!

**Pull request closed without merging**
