### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:close

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
Checked with QA if modifying `test.properties` was okay

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c1b8488296...0689d62ebf

**Pull request closed without merging**
