### PR TITLE
LPS-66437

### PR DESCRIPTION
**Pull request by natecavanaugh**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pei-jung there is too much code duplication here. See UserImpl#getPortraitURL

Please resend.

**Comment by pei-jung** [comment]
Added new method in OrganizationImpl and resent as https://github.com/brianchandotcom/liferay-portal/pull/42430. Thanks!

**Pull request closed without merging**
