### PR TITLE
LPS-109377 Create AccountRole assignment POST and DELETE endpoints

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-109377](https://issues.liferay.com/browse/LPS-109377).<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by kenjiheigel** [comment]
Stable failure is unrelated to this pull. Fails to due [LPS-109105](https://issues.liferay.com/browse/LPS-109105)

**Comment by drewbrokke** [comment]
Resent as https://github.com/brianchandotcom/liferay-portal/pull/85913

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2e16cbf191...f8a9f74cfe

**Comment by brianchandotcom** [comment]
@drewbrokke can we just use the annotation for

```
private final List<AccountUser> _accountUsers = new ArrayList<>();
```

I only want to avoid using the annotation only when we cannot use it.

**Comment by brianchandotcom** [comment]
@drewbrokke also see f8a9f74cfe9b2d2aa07233e87ac1a71c69f7f091

**Pull request closed without merging**
