### PR TITLE
LPS-64196 buildLang

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by alee8888** [comment]
Looking into the failures for the 3 failing tests for CPRolesCPWebcontent#AddTemplateSiteRole.

**Comment by ealonso** [comment]
Hey @alee8888,  @anthony-chu

We've removed the options for add user roles and users group roles on kebap menu:

site_memberships_-_liferay

Now if you want to select the site roles for a user or user group, you should go to users or user groups view and click on the users or user group that you want, and then in the management bar appears a new button to select the roles, so now you need to click there.

site_memberships_-_liferay

Regards,
Eudaldo.

**Comment by alee8888** [comment]
@brianchandotcom 
Can you please close this PR? I will resend a PR that combines Eudaldo's commits and test fixes for the breaking tests. Thank you.

**Comment by evannagayama** [comment]
@ealonso thanks for letting us know!

**Comment by ealonso** [comment]
Hey @alee8888, @evannagayama, @anthony-chu,

Do you have any update?, Can I help you with something else?

Please let me know if you need anything else.

Regards,
Eudaldo.

**Comment by alee8888** [comment]
Resent in https://github.com/brianchandotcom/liferay-portal/pull/37965

**Pull request closed without merging**
