### PR TITLE
LPS-138566 Add support for AssetCategoryProperties in Headless Admin Taxonomy alternative

### PR DESCRIPTION
**Pull request by javierdearcos**
I've tried to make the changes as we agreed, changing the java class name to TaxonomyCategoryProperty and leaving the property name as "properties", but there is a bug in REST Builder generation that doesn't allow it (I'll figure out what's happening tomorrow)

I've made an alternative implementation changing both, the Java class name to "TaxonomyCategoryProperty" and the property name to "taxonomyCategoryProperties"

I leave you both PRs open to let you decide if it's worth merging any of these today or if it is better to wait until tomorrow to see if I can detect the REST Builder bug and it is possible to change only the Java class name to TaxonomyCategoryProperty and leave the property name as "properties"

### CODE REVIEW

**Comment by javierdearcos** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a9bf1187ca...1d1d11568e

**Comment by brianchandotcom** [comment]
@javierdearcos I actually think this version is the best. I wouldn't change it to just "properties". This is good to go.

**Comment by brianchandotcom** [comment]
@javierdearcos please review my tiny changes in my origin.

**Pull request closed without merging**
