### PR TITLE
LPS-101336 Updates usage of ClayPaginationWithBar that is now a properly controlled component

### PR DESCRIPTION
**Pull request by jbalsas**
/cc @brunofarache, @brunobasto, @matuzalemsteles

@thektan, I'll be sending the `master-private` PR shortly

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
Hey @john-co is `js-unit` failing in upstream , or caused by this? If it is by this, I'll work with @andresfulla tomorrow to figure it out.

/cc @epgarcia

**Comment by jbalsas** [comment]
See https://github.com/brianchandotcom/liferay-portal-ee/pull/26475 for the `master-private` bits

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f83b9a61c5...9b2bc0cbce

**Pull request closed without merging**
