### PR TITLE
LRQA-36096 Add needed properties and batches to fix our queries | master

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRQA-36096

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test

**Comment by michaelhashimoto** [comment]
ci:reopen

**Comment by michaelhashimoto** [comment]
@brianchandotcom - I don't think the SF is related to my pull request.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2208588932...183fcb68ab

**Pull request closed without merging**
