### PR TITLE
LPS-86010 Move possible objects involved in workflow inside "object" key

### PR DESCRIPTION
**Pull request by javiergamarra**
/cc @dgarciasarai

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9eba12e97e...6b50be3439

**Comment by brianchandotcom** [comment]
See my changes in upstream @nhpatt thx!

**Comment by nhpatt** [comment]
Thanks! :D

**Comment by dgarciasarai** [comment]
Thanks!

**Pull request closed without merging**
