### PR TITLE
LPS-113847 viewMode should be true when using the form renderer

### PR DESCRIPTION
**Pull request by alexcandidos**
@alexcandidos @cvanut please test this fix on app builder and forms to see if there was any side effect.

cc @alinedoleron

### CODE REVIEW

**Comment by alexcandidos** [comment]
See https://github.com/alexcandidos/liferay-portal/pull/165#issuecomment-630812189

**Comment by alexcandidos** [comment]
ci:reopen

**Comment by alexcandidos** [comment]
cc: @jpince @brunofarache @jeyvison

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a163b1192d...68812b1fc3

**Pull request closed without merging**
