### PR TITLE
LPS-70501 Able to remove membership from site memberships if the user is assigned to an organization instead of an organization site

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-70501](https://issues.liferay.com/browse/LPS-70501).<br><br>/cc @pei-jung @stsquared99 @alee8888 @pavel-savinov @jkappler

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by drewbrokke** [comment]
@jpince I don't think these errors are related.  Can you confirm?

**Comment by jpince** [comment]
@drewbrokke yes, looks unrelated. thanks for bringing this to my attention, looking into it

**Comment by jpince** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8726be5abe...a810fb2737

**Comment by brianchandotcom** [comment]
@drewbrokke Please send a backport to support for 7.1.x and 7.0.x (like our normal support workflow). I'm no longer auto backporting pulls like this.

@jhendley @liferay @zsoltbalogh FYI.

Merged into master only.

**Pull request closed without merging**
