### PR TITLE
LPS-81229 We don't want to throw an exception here, just notify the user of the error

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:reopen

**Comment by jkappler** [comment]
cc:// @jpince

**Comment by jpince** [comment]
ci:close <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jpince** [comment]
pushed upstream https://github.com/liferay/liferay-portal/commit/6077b17e26bdb2d9821b6a4b72ef65ab222bc953 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
