### PR TITLE
LRQA-39303 Add a method for overriding the poshi query against different suites

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-39303

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@pyoo47 this is a very expensive "test" no? Can we find a way to run tests just for poshi... since it can never break anything else.

**Comment by brianchandotcom** [comment]
@pyoo47 I mean, jenkins results parser

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/28a254b541...fde498684a

**Pull request closed without merging**
