### PR TITLE
LPS-60186 missing import

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Crossing my fingers on this one, It already passed all tests in a pr to myself (https://github.com/jorgeferrer/liferay-portal/pull/602)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5867ee7c22...8e45927ff0

**Comment by brianchandotcom** [comment]
@JorgeFerrer I only made minor tweaks in upstream.

**Comment by brianchandotcom** [comment]
@hhuijser can you add a rule in SF so that all configuration classes now need to specify a category?

See how @JorgeFerrer added a new ConfigurationAdmin class. It's always used for config classes that have @Meta.OCD

Thx @hhuijser

**Comment by JorgeFerrer** [comment]
Looks good, thanks Brian :+1:

**Pull request closed without merging**
