### PR TITLE
LPS-76895

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test

**Comment by matethurzo** [comment]
@brianchandotcom test failures are unrelated

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a73da3574c...08f28c9ea6

**Comment by brianchandotcom** [comment]
@matethurzo see upstream for my changes. Thx.

**Pull request closed without merging**
