### PR TITLE
LPS-152594 Fixed upgrade for com.liferay.client.extension.internal.upgrade.ClientExtensionInitialUpgradeStepRegistrator when concurrency for database partitioning is enabled

### PR DESCRIPTION
**Pull request by LuisOrtiz89**
LPS-152594

### CODE REVIEW

**Comment by LuisOrtiz89** [comment]
Hi @brianchandotcom, I included a new commit to remove the check from the test as disussed by Slack

**Comment by LuisOrtiz89** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8c76e7837f...e9f0025dde

**Comment by brianchandotcom** [comment]
@tinatian fyi @LuisOrtiz89 turned it back on by default, but also fixed the problem.

**Pull request closed without merging**
