### PR TITLE
LPS-63057 Uses btn-lg only for principal buttons

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@shuyangzhou see the 113 broken integration tests, I"ve seen it fail randomly like this. Can you see if it's some OSGi thing? THx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/24ba003892...a86d23c609

**Pull request closed without merging**
