### PR TITLE
Lps 72481

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by jpince** [comment]
@shuyangzhou @brianchandotcom since this is a high-risk pull, can we wait to backport until we see results in master?

**Comment by shuyangzhou** [comment]
@jpince we did many manual tests to make this safer, but I can not guarantee this is completely safe. PR tester has already passed in my own pulls. Do we have any other non-PR functional tests or manual tests to run by QA? If so, we should run them first before backport. If not, holding the backport won't really help much since we don't have ways to test more.

**Comment by jpince** [comment]
@shuyangzhou we can run this through the gauntlet (~1800 functional tests) if it's in a pull to ee-7.0.x and @brianchandotcom approves

cc/ @sharonchoi

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/28f8a40731...56ad5b8751

**Comment by brianchandotcom** [comment]
@jpince it's in 7.0.x. Should be part of daily guantlet.

**Pull request closed without merging**
