### PR TITLE
LPS-45199

### PR DESCRIPTION
**Pull request by mikakoivisto**

### CODE REVIEW

**Comment by juangon** [comment]
@brianchandotcom this is a feature that was in queue for many months (even years). As it's enabled by properties I think is safe to merge. It enables a useful feature for changing the url port, protocol and host name by request headers instead of fixed properties (using X-Forwarded-***), adding a lot of flexibility to users when having web server proxies (like nginx, apache, haproxy, etc).
Anyway, it will be fine too if you don't want to merge for this release.

**Comment by juangon** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/657523b907...5af5498042

**Comment by brianchandotcom** [comment]
@juangon I merged in MOST of this pull, but not all. Please see upstream for my changes, and send a follow up pull for 33aa6694a2940c78184ee8bdb0fcde5a34b7807d and 5af5498042d316cf36ae15e628a735508c231adc

Thx!

**Pull request closed without merging**
