### PR TITLE
LPS-68040 default language should also be indexed with suffix locale (consistent with JournalArticleIndexer)

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by jpince** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@marianoalvarosaiz please resend:

```
	private void _addLocalizedField(
		Document document, String field, Locale siteDefaultLocale,
		Map<Locale, String> map) {

		for (Entry<Locale, String> entry : map.entrySet()) {
			Locale locale = entry.getKey();

			if (locale.equals(siteDefaultLocale)) {
				document.addText(field, entry.getValue());
			}

			String languageId = LocaleUtil.toLanguageId(locale);

			document.addText(
				LocalizationUtil.getLocalizedName(field, languageId),
				entry.getValue());
		}
	}
```

See https://en.wikipedia.org/wiki/Don%27t_repeat_yourself

@juliocamarero fyi

**Pull request closed without merging**
