### PR TITLE
LPS-91113 Fix tests. Deploy portlet as method is now taking it to account if portlet is deployed or not.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@marianoalvarosaiz see changes in upstream. Thx.

**Comment by brianchandotcom** [comment]
@shuyangzhou fyi

**Comment by shuyangzhou** [comment]
@marianoalvarosaiz base on the ticket description, this should be a performance ticket, why is it a security ticket?
And all performance changes need to run through a performance check to be sure it is really doing what you think it is doing.

@slnn please run a regression check against it.

**Comment by slnn** [comment]
OK, got it and will update test results when I got them.

**Comment by marianoalvarosaiz** [comment]
Hi @shuyangzhou,
 I marked it as a security issue because it seems really easy to create a script with a counter making a huge number of calls changing the p_p_id, that will end with lots of queries to a heavy table like PortletPreferences (since the portletId changes and will not be cached) hence causing a DB DoS
Anyway I've marked it as a Performance issue also.
Kind regards.

/cc @topolik

**Comment by slnn** [comment]
Hi @shuyangzhou,

Here are test results:
Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count Changes
-- | -- | -- | -- | -- | --
BaseLine | 8e1001f | 15850 | 262 | 64.1 | 
PR-69619 | - | 15968 | 283 | 71.7 | 0.7444794953

WebContent:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page | Session Count Changes
-- | -- | -- | -- | -- | --
BaseLine | 8e1001f | 21128 | 402 | 151 |  
PR-69619 | - | 20637 | 393 | 149 | -2.323930329

MessageBoard:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Session Count Changes
-- | -- | -- | -- | -- | --
BaseLine | 8e1001f | 7597 | 221 | 374 |  
PR-69619 | - | 7577 | 118 | 285 | -0.2632618139

Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count Changes
-- | -- | -- | -- | -- | --
BaseLine | 8e1001f | 5219 | 67 | 283 |  
PR-69619 | - | 5198 | 75.6 | 296 | -0.4023759341

Document Library:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File | Session Count Changes
-- | -- | -- | -- | -- | --
BaseLine | 8e1001f | 8680 | 568 | 882 |  
PR-69619 | - | 8742 | 315 | 629 | 0.7142857143

Wiki:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page | Session Count Changes
-- | -- | -- | -- | -- | --
BaseLine | 8e1001f | 5596 | 356 | 562 |  
PR-69619 | - | 5435 | 397 | 591 | -2.877055039

AssetPublisher:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of VIew Page with Filter | Session Count Changes
-- | -- | -- | -- | -- | --
BaseLine | 8e1001f | 9172 | 143 | 158 |  
PR-69619 | - | 9113 | 132 | 154 | -0.643262102

**Comment by shuyangzhou** [comment]
@slnn since this is mainly for dB. Please modify the result comment to include dB side CPU usage diff.

@marianoalvarosaiz as you can see, this is not improve anything, at least from the overall performance's point of view. And webcontent and wiki seem to be a lost, although this could still be within noise range. Once lily attaches dB CPU usages, we can have a better understanding. The point is, there should be no guess work when doing performance changes. Common sense usually fails here, only the changes backed by test results can be trusted.

**Comment by slnn** [comment]
Hi @shuyangzhou,

Update the DB CPU usage be finished.

**Comment by shuyangzhou** [comment]
@marianoalvarosaiz there is no real noticeable diff in general. All diff are within noise range. Although they are towarding to be slightly loss.
In this case there is no immediate pressure of making further changes. But it will help the future if you can create a test to secure your expected logic. And when we get more bandwidth we can revisit the issue using your test as acceptance test to make more performance improvements if that is ever needed.

Thanks!

**Pull request closed without merging**
