### PR TITLE
LPS-167695 Add list type with external reference code

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-167695

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2b51c7f0fb...43bdf02025

**Comment by brianchandotcom** [comment]
@mateussgn see 24a08af1 and you forgot these 43bdf020

**Comment by mateussgn** [comment]
Thank you, Brian!
I had changed the _randomString()_ calls with _null_, but somehow it wasn't committed.

**Pull request closed without merging**
