### PR TITLE
LPS-67752 Add [$NULL_DATE$] placeholder to SQLTransformer

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@adolfopa I backported this. Please send the actual fix with another ticket. Thx!

**Comment by brianchandotcom** [comment]
@adolfopa note that I resolved https://issues.liferay.com/browse/LPS-67752

can you update that ticket to talk about the SQL Null Date

And then send the actual fix in another ticket? Thx.

**Comment by brianchandotcom** [comment]
@adolfopa I also renamed the test. See upstream. Thx.

**Comment by adolfopa** [comment]
Done. The new ticket for the rest of the changes is https://issues.liferay.com/browse/LPS-68939.

Thanks!

**Pull request closed without merging**
