### PR TITLE
LPS-73661 Add user with regular Portal Content Reviewer role to Data Creator module

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:reopen

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f2f1cda7fe...4213f29494

**Comment by brianchandotcom** [comment]
@pei-jung see 4213f29

thx

**Pull request closed without merging**
