### PR TITLE
LPS-95096

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by jpince** [comment]
@hhuijser can you please run service builder? It's passing in upstream, and the failures look SF-related, fixing line breaks
example:
```
     [echo] -	 * Returns the number of all the record sets belonging the group and associated with the DDMStructure.
     [echo] +	 * Returns the number of all the record sets belonging the group and
     [echo] +	 * associated with the DDMStructure.
```
https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/49514/AXIS_VARIABLE=0,label_exp=!master/console

**Comment by brianchandotcom** [comment]
Published.

**Comment by brianchandotcom** [comment]
@jpince I regenerated that module. If there are more, let me know.

**Comment by hhuijser** [comment]
@jpince ran SB here: https://github.com/brianchandotcom/liferay-portal/pull/72731

**Pull request closed without merging**
