### PR TITLE
LRQA-38648 Add new test suite for ci:test:sf | master

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRQA-38648

@brianchiu @jpince

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1ec794a063...7903e1e451

**Comment by brianchandotcom** [comment]
@michaelhashimoto see my changes in upstream? Thx.

@petershin @hhuijser fyi!

**Comment by brianchiu** [comment]
ci:test:sf

**Pull request closed without merging**
