### PR TITLE
LPS-72409 uninstall the theme test bundle

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:reopen

**Comment by gamerson** [comment]
ci:retest

**Comment by jpince** [comment]
@gamerson this is a known issue, see https://loop.liferay.com/home/-/loop/feed/5782156

**Comment by gamerson** [comment]
thanks for the update @jpince  I think that means everything is clear for this one then.

**Comment by gamerson** [comment]
hey @brianchandotcom  these all seem due to
```
Unable to connect to a valid mail server. Please make sure one is properly configured: Could not connect to SMTP host: localhost, port: 3241
```

**Comment by brianchandotcom** [comment]
@pyoo47 can you take a look?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1007e295a5...b5ed91b2dc

**Comment by brianchandotcom** [comment]
@gamerson see b5ed91b2dc23b1e77ba7b7dfe3b1b9d098041489

Thx.

**Comment by brianchandotcom** [comment]
@gamerson see b5ed91b2dc23b1e77ba7b7dfe3b1b9d098041489 (now with proper link)

**Pull request closed without merging**
