### PR TITLE
LPS-65686 Explain that customer's database data partitioning module m…

### PR DESCRIPTION
**Pull request by jhinkey**
…ust be present on execution classpath

cc/ @mdelapenya

### CODE REVIEW

**Comment by sharonchoi** [comment]
Virtual instance error, @kenjiheigel will investigate more.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8b73626d4f...d66cb78859

**Comment by brianchandotcom** [comment]
See 1e5bd4c2fdd6d25811e8e58ca03b3944f5aa6f81

**Comment by jhinkey** [comment]
Thanks, Brian.

**Pull request closed without merging**
