### PR TITLE
Lps 87037

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/76b56e0070...257e7bd612

**Comment by brianchandotcom** [comment]
@marianoalvarosaiz please send a backport to support.

**Comment by brianchandotcom** [comment]
@marianoalvarosaiz can we sort

resource.bundle.aggregate:String="(bundle.symbolic.name=com.liferay.portal.settings.lang),(bundle.symbolic.name=com.liferay.login.authentication.google.web)";\

Or does the aggregation order matter? Please send me a pull to sort the symbolic names.

I backported this to 7.1.x for you, but not 7.0.x.

**Comment by marianoalvarosaiz** [comment]
@brianchandotcom normally order matters, but in this case where there aren't common keys between both modules is irrelevant, so I sent  you a new pull: https://github.com/brianchandotcom/liferay-portal/pull/65697

**Pull request closed without merging**
