### PR TITLE
LPS-41324 avoid exception when importing lar files

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/51072c452f...8806043a96

**Comment by brianchandotcom** [comment]
@juliocamarero great job on the tests

**Pull request closed without merging**
