### PR TITLE
LPS-63192

### PR DESCRIPTION
**Pull request by samanzanedo**
Hello Brian.

This PR has been checked by @sergiogonzalez 

Thanks.
Sergio.

### CODE REVIEW

**Comment by samanzanedo** [comment]
ci:retest

**Comment by samanzanedo** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b9f3d1ccbe...7d89731ed5

**Comment by brianchandotcom** [comment]
@samanzanedo @sergiogonzalez please see my changes in upstream. Thx.

**Pull request closed without merging**
