### PR TITLE
LPS-67947 Send user to generic error page

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by vicnate5** [comment]
ci:reopen

**Comment by vicnate5** [comment]
Hey @sergiogonzalez 

This issue with the pull requests is no longer occuring, but there doesn't seem to be a way to reopen the pulls affected by it. Could you rebase & resend this pull request?

Thanks!

**Comment by sergiogonzalez** [comment]
Thanks @vicnate5 I have resent the pull here https://github.com/brianchandotcom/liferay-portal/pull/43652

**Pull request closed without merging**
