### PR TITLE
LPS-101831 We don't support repeatable DDM image fields now

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by patriciajeanperez** [comment]
Reviewed. No unique failures.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/dc88fd0828...e849dbb81c

**Pull request closed without merging**
