### PR TITLE
LPS-91856 Add dependency with fragment-api

### PR DESCRIPTION
**Pull request by JorgeFerrer**
/cc @ealonso

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:reopen

**Comment by ealonso** [comment]
Hey @jpince,

Do you know if those problems are related with this pull?

Thanks!!
Eudaldo

cc: @kyle-miho, @brianchiu

**Comment by jpince** [comment]
@ealonso don't worry about the second result, unrelated issue in upstream. here's my analysis on the first result:

js-unit - looks related @john-co can you please verify?
```
     [exec] FAIL test/js/reducers/segmentsExperiences.test.js
     [exec]   ??? segments experiences reducers ??? createSegmentsExperienceReducer communicates with API and updates the state
     [exec] 
     [exec]     expect(jest.fn()).toHaveBeenCalledWith(expected)
     [exec] 
     [exec]     Expected mock function to have been called with:
     [exec]       [StringContaining "", {"active": true, "classNameId": "test-class-name-id", "classPK": "test-class-p-k", "nameMap": "{\"en_US\":\"test experience name\"}", "segmentsEntryId": "test-segment-id"}, ObjectContaining {}, ObjectContaining {}]
     [exec]     But it was not called.
     [exec] 
     [exec]       92 | 					);
     [exec]       93 | 
     [exec]     > 94 | 				expect(spy).toHaveBeenCalledWith(
     [exec]          | 				            ^
     [exec]       95 | 					expect.stringContaining(''),
     [exec]       96 | 					liferayServiceParams,
     [exec]       97 | 					expect.objectContaining({}),
     [exec] 
     [exec]       at Object.toHaveBeenCalledWith (test/js/reducers/segmentsExperiences.test.js:94:17)
     [exec] 
     [exec]   ??? segments experiences reducers ??? createSegmentsExperienceReducer communicates with API and updates the state
     [exec] 
     [exec]     expect.assertions(4)
     [exec] 
     [exec]     Expected four assertions to be called but received one assertion call.
     [exec] 
     [exec]       83 | 				};
     [exec]       84 | 
     [exec]     > 85 | 				expect.assertions(4);
     [exec]          | 				       ^
     [exec]       86 | 
     [exec]       87 | 				createSegmentsExperienceReducer(prevState, CREATE_SEGMENTS_EXPERIENCE, payload)
     [exec]       88 | 					.then(
     [exec] 
     [exec]       at Object.assertions (test/js/reducers/segmentsExperiences.test.js:85:12)
     [exec] 
     [exec] PASS test/js/utils/fragmentMigrator.test.js
     [exec] 
```
upgrades - unrelated
modules-int - unrelated (Jurgen said he would fix this test)
functional - not sure, @brianchiu or @kyle-miho would know

**Comment by john-co** [comment]
@jpince @ealonso 
The js-unit error is unrelated. The layout-content-page-editor-web js-test has been disabled and got merged a few minutes ago. https://issues.liferay.com/browse/LRQA-47907

**Comment by brianchandotcom** [comment]
@JorgeFerrer @ealonso see my changes in https://github.com/JorgeFerrer/liferay-portal/pull/862 (especially https://github.com/JorgeFerrer/liferay-portal/pull/862/commits/148c1f50b0df29159f690afb595bd93be26aa100)

We're using the names in a confusing manner. Please review my changes, and perhaps rename things so they are all the same word in all contexts.

Perhaps, fragmentRendererType and fragmentRendererKey everywhere.... (or something else)

**Comment by kyle-miho** [comment]
Everything is unrelated. this  pull should be good.

**Pull request closed without merging**
