### PR TITLE
LPS-82444 Auto SF

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @brianchiu

**Comment by jkappler** [comment]
@brianchandotcom, just testing 7.1.x before sending

**Comment by jkappler** [comment]
sent to 7.1.x here: https://github.com/brianchandotcom/liferay-portal-ee/pull/20650

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b78c0e639b...51cd3c4a94

**Pull request closed without merging**
