### PR TITLE
LRQA-51878 Fix WorkflowForms#ViewDateAssetDetails

### PR DESCRIPTION
**Pull request by barrosdennys**

### CODE REVIEW

**Comment by barrosdennys** [comment]
ci:test:workflow

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1234d319e2...02c690ecf5

**Comment by brianchandotcom** [comment]
I merged this, but it still has workflow poshi errors. Please fix @barrosdennys

**Comment by barrosdennys** [comment]
I'm on it. Thank you, Brian!

**Pull request closed without merging**
