### PR TITLE
LPS-77018 Add maxLength to make sure the name is less than 200 characters

### PR DESCRIPTION
**Pull request by matethurzo**
tests were executed here: https://github.com/matethurzo/liferay-portal/pull/1898

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jonathanmccann if we update it to 175 or 225 in the future, we'll have to update it in a lot of places. Is there somewhere (like some model hint) that already specifies 200? If so, I'd like to make a call to the source of "truth" that already specifies 200 so we don't duplicate that code. Please resend. Thx.

See

```
		int maxLength = ModelHintsUtil.getMaxLength(
			KBArticle.class.getName(), "urlTitle");
```

in KBArticleLocalServiceImpl

and

```
ModelHintsUtil.getMaxLength(KBArticle.class.getName(), "urlTitle")
```

in modules/apps/knowledge-base/knowledge-base-web/src/main/resources/META-INF/resources/admin/common/edit_article.jsp

Thx @jonathanmccann

**Comment by jonathanmccann** [comment]
This works easily for ```export-import-web```, but accessing the BackgroundTask in ```staging-processes-web``` will require a new dependency on the ```com.liferay.portal.background.task.api```.

@matethurzo Do you mind the new dependency or would you rather approach it in a different way?

**Comment by matethurzo** [comment]
@jonathanmccann staging-processes-web can depend on the background task api. I'm sort of surprised there is no dependency yet :)

**Comment by jonathanmccann** [comment]
@matethurzo Thanks for confirming. I'll work on getting this resent.

**Comment by jonathanmccann** [comment]
https://github.com/matethurzo/liferay-portal/pull/1906

**Comment by jonathanmccann** [comment]
@brianchandotcom It looks like the other usages of ```maxlength="200"``` are for virtual host URLs:

https://github.com/liferay/liferay-portal/blob/master/modules/apps/web-experience/site/site-admin-web/src/main/resources/META-INF/resources/site/site_url.jsp#L123

Let me know if you want those cleaned up as well and I can make a new LPS for it.

**Pull request closed without merging**
