### PR TITLE
LPS-60595 checks for null on configurationCategories

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Hey @ZoltanTakacs,

I think it would be great if you could backport this change. It may not be critical for the release since it only affects one portlet (SystemSettings), but the effect is quite bad and the changes to fix it are quite simple and only affect a JSP in that portlet.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3860eb33b8...4f0e34b247

**Comment by brianchandotcom** [comment]
@drewbrokke I think you meant to check 4f0e34b247567ed69ccffb39d62084e3f5561112 instead

**Comment by ZoltanTakacs** [comment]
Thanks for the explanation @JorgeFerrer, I've sent the backport to Brian here: https://github.com/brianchandotcom/liferay-portal/pull/32369

**Pull request closed without merging**
