### PR TITLE
LPS-54284

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @moltam89

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@moltam89 this is the wrong fix no? Shouldn't that logic be encapsulated in getBody? See the logic that is already there. It just needs to be updated. Thx.

**Comment by sergiogonzalez** [comment]
Hey @moltam89 I just talked to @brianchandotcom and I'll send him a pull request tomorrow with a different fix.

Thanks!

**Pull request closed without merging**
