### PR TITLE
LPS-62774

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@brianchandotcom please don't close the ticket

**Comment by mhan810** [comment]
@brianchandotcom should be unrelated

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fd00c8624d...b186c5510c

**Comment by brianchandotcom** [comment]
@mhan810 synced with 7.0.x

**Pull request closed without merging**
