### PR TITLE
LPS-74104

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@tomwang2011

See https://github.com/brianchandotcom/liferay-portal/pull/50857/commits/b1d9b5d9400cb717d2295d705a2a33849a570c83 and https://github.com/brianchandotcom/liferay-portal/pull/50857/commits/6788c649923b5bb9a108b412df02a8d77f0af2ea

Is this still on your radar?

**Comment by hhuijser** [comment]
ci:retest

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
FYI @pyoo47

Strange one, the stacktrace of the NPE shows it's breaking on https://github.com/brianchandotcom/liferay-portal/pull/50857/commits/2e1eaff8a81ba28f4e8fb31b183ac7ac576c36f6
Somehow, the last three commit didn't get tested?

Retesting...

**Comment by Sharryxue** [comment]
@hhuijser 
Hello Hugo, would you please look into the issue further, since the failures are constant from previews runs. I saw most of the failures are related to the SF, and I saw your commits related more to the SF file. Thanks.
```
     [exec] Goal prefix is specified as: 'db-support'. Maven currently expects it to be 'com.liferay.portal.tools.db.support'.
```

**Comment by hhuijser** [comment]
Sent new pull https://github.com/brianchandotcom/liferay-portal/pull/50864

**Pull request closed without merging**
