### PR TITLE
Poshi 254 Poshi Release Version 1.0.336

### PR DESCRIPTION
**Pull request by CalumR23**
https://issues.liferay.com/browse/POSHI-254
@brianchandotcom may you please publish the gradle plugin? Thank you!

### CODE REVIEW

**Comment by CalumR23** [comment]
ci:reopen

**Comment by CalumR23** [comment]
ci:test:sf

**Comment by CalumR23** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5eb67324b0...83995352ac

**Pull request closed without merging**
