### PR TITLE
LRQA-43681, LRQA-43693, LRQA-43718 | master

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LRQA-43681
https://issues.liferay.com/browse/LRQA-43693
https://issues.liferay.com/browse/LRQA-43718

7.1.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/21774

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@brianchiu master only?

**Comment by brianchiu** [comment]
@brianchandotcom Nope. 7.1.x also. I was just about to edit the description with the pull from 7.1.x

**Comment by brianchiu** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Thx @brianchiu

**Comment by brianchiu** [comment]
cc @kmaria

See https://github.com/brianchandotcom/liferay-portal/pull/63418/commits/d8db36fc986911913da6d8aaf7d42059561b5eb7

**Pull request closed without merging**
