### PR TITLE
    LPS-57946  NoSuchResourceActionException for com_liferay_blogs_web_portlet_BlogsAdminPortlet#ADD_TO_PAGE when adding a page on a different portal instance

### PR DESCRIPTION
**Pull request by peterfellwock**
The fix keeps the exception from being thrown and uncaught upstream. The test will fail if the the hasPermission throws an exception, in theory a boolean method should not be throwing exceptions.

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@peterfellwock test needs to be better. You need to have a case where the debug statement is outputted. And you need to use a test logger to ensure the log statement is logged.

Please resend. Search our tests and you'll find cases where it looks for a specific log output. Thx.

**Comment by brianchandotcom** [comment]
@peterfellwock clue is look for *Test.java with Shuyang in it

**Pull request closed without merging**
