### PR TITLE
LPS-77909 Create a UserActionContributor entry for the UAD portlet

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-77909](https://issues.liferay.com/browse/LPS-77909).<br><br>Hey Brian, this is the UserActionMenuContributor for the UAD portlet (so we can actually navigate to it).  It's using the new API you merged today.  There is a new language key in this pull - can you please run buildLang?  Thanks!<br><br>/cc @pei-jung @willnewbury @noahsherrillwork

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test

**Comment by jpince** [comment]
ci:retest

**Comment by drewbrokke** [comment]
closing to rebase and re-send

**Comment by drewbrokke** [comment]
ci:stop

**Pull request closed without merging**
