### PR TITLE
LPS-109256 Build lang

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
@jbalsas @wincent there seems to be something wrong with Js SF. It is going back and forth, adding/removing trailing commas.

It is also happening in https://github.com/brianchandotcom/liferay-portal/pull/85395

**Comment by wincent** [comment]
@jkappler was seeing the same thing. He noticed that when he runs SF at the project level, the Java source formatter strips the commas. When run from the top (eg. `cd portal-impl && ant format-source-current-branch`) it correctly leaves the commas intact. His theory was that the version of the source formatter used in the project case is stale and will require an update. For reference, the commit that stops the Java source formatter from messing with JS commas is [this one](https://github.com/brianchandotcom/liferay-portal/pull/85346/commits/515fbb523f231e06aa28f7f0660e0513911003d0) (and minor follow-up in https://github.com/brianchandotcom/liferay-portal/pull/85346/commits/8a9440e41a2cc854267cc5ef29a9f802736f0466).

@jkappler: were you able to confirm your theory about the staleness?

@adolfopa: in the interim, a `portal-impl`-level `ant format-source-current-branch` may do what you want.

**Comment by adolfopa** [comment]
For me, it always happens when running from portal-impl. Every time I run it, it goes back and forth, adding/removing the commas, so I don't think it is a staleness issue.

Anyway, I'll send the changes without the trailing commas and hope for the best :-)

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/85404

**Comment by jkappler** [comment]
@adolfopa, @wincent, seems to be happening across all of the portal. The theory as @wincent mentioned is that the version of the SF that we are using is different than the updated one in CI

**Comment by wincent** [comment]
What I used yesterday when testing the source-formatter changes, replacing whatever locally cached version may exist:

```
cd modules/util/source-formatter
gradlew clean deploy
```

As @jkappler showed me in the logs, CI looks to build a clean copy of source-formatter at the beginning of each SF run:

```
ant -f commands/build-common.xml run-ant-target -Dant.file.name=build-test-portal-source-format.xml -Dant.target= -lib commands/../lib/jenkins
``` 

@hhuijser: is there somewhere we need to update so that people running `formatSource` locally get the new logic? Seems last publish was in 168850d83e82853bb10b781d8f540f043b4d3575 by @ling-alan-huang

**Comment by hhuijser** [comment]
@wincent, I told Brian to publish SF

**Comment by wincent** [comment]
Thanks @hhuijser!

**Pull request closed without merging**
