### PR TITLE
LPS-44958

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/77e3da8041...006f9a4414

**Comment by brianchandotcom** [comment]
Hey Mike,

Please see my changes in upstream.

**Comment by brianchandotcom** [comment]
Also, if you look in modules/**/portlet.properties

You can see that we've migrated a bunch from portal.properties to portlet.properties, and we even move the documentation.

You're the only one who's been semi moving them to *Configuration but then just commenting out the values in portal.properties. We should ideally just move them.

Thx.

**Comment by mhan810** [comment]
Hey Brian, I didn't want to move the properties to a properties file just
yet.  I wanted to see how we get the configuration UI done for these
non-portlet assets first.



Once we get that done, we'll go through another round of cleanups.  This
round is to focus on extraction.



*From:* Brian Chan [mailto:notifications@github.com]
*Sent:* Thursday, January 29, 2015 12:20 PM
*To:* brianchandotcom/liferay-portal
*Cc:* Michael Han
*Subject:* Re: [liferay-portal] LPS-44958 (#23612)



Also, if you look in modules/**/portlet.properties

You can see that we've migrated a bunch from portal.properties to
portlet.properties, and we even move the documentation.

You're the only one who's been semi moving them to *Configuration but then
just commenting out the values in portal.properties. We should ideally just
move them.

Thx.

--
Reply to this email directly or view it on GitHub
<https://github.com/brianchandotcom/liferay-portal/pull/23612#issuecomment-72075789>
.

**Pull request closed without merging**
