### PR TITLE
Revert "LPS-97719 SF"

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9bbc1feff2...0fb3fcead4

**Comment by brianchandotcom** [comment]
@wincent this was very weird. My commit in 09c887f9c5f5258b14b35c0dd0bb685d7593e4c0 was done when I ran "ant format-source" or an "ant all"

@carloslancha reverted my commit, I assume it broke stuff.

I readded the review tag in 0fb3fcead4561fff9cd92f0244b2e7b3dedeee7d

@wincent I'll watch to see if 'ant all' or 'ant format-source' auto modifies this file again. If it does, we'll have to fix this another way.

@carloslancha next time, please comment on the pull letting me know why you're reverting. I'm just guessing here.

@jbalsas fyi

**Comment by jpince** [comment]
@brianchandotcom I could not reproduce by running `ant format-source-all` after reverting 09c887f.

**Comment by wincent** [comment]
@brianchandotcom: I've seen this before a few times now with some folks in the Madrid office. When I sit down with them, the problem goes away after a `git clean -fdx`. It could be a bug, but from the console output it looks like some very old formatting code is running out of the Gradle cache (for example, I've seen what appeared to be `csf` running (!!!), even though we switched away from that many weeks ago now); I don't really understand how that can happen because my Gradle knowledge is limited. If I can catch this happening again for anyone, I'll do some forensics to try and see exactly how what's going on.

The reason why 09c887f had to be reverted is that it changed ES5 object property syntax to the more modern ES6 object shorthand property syntax. That would be fine everywhere except IE. Prettier won't make that kind of ES5 → ES6 change; ESLint *would* make it, but we only run ESLint on "modern" files (ie. with an ".es.js" extension), and Babel transpiles those which makes them safe for consumption on IE.

**Pull request closed without merging**
