### PR TITLE
LPS-112222 In CI docker containers, time drifting happens randomly. D…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…B2 jdbc driver seems having a timestamp base queue to communicate to DB2 server. When CI time drifting happens, we may see the index creation statement got an earlier timestamp comparing to the corresponding table creation statement, causing the very confusing "SQLCODE=-204, SQLSTATE=42704". This fix wraps up the DataSource on CI to detect time drifting on db accessing. Once detected time drifting, delay the execution to catch up the previous sampled time. Also on seeing "SQLCODE=-204, SQLSTATE=42704" together with time drifting, retry the failed sql statement to recover.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by vicnate5** [comment]
FYI @yuhai

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/20becbd0d4...2a2461d07b

**Comment by brianchandotcom** [comment]
Thx @shuyangzhou just 2a2461d07b6dedbf446621885224f35e91dbd1cf

@yuhai @vicnate5 fyi

**Pull request closed without merging**
