### PR TITLE
LPS-83379 Enabled by default

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @shuyangzhou ,

I'll do after @brianchandotcom merges it if that's ok. 

Regards

**Comment by shuyangzhou** [comment]
Yeah, that's fine. Just add it to your queue and make sure it goes in before next fix pack release. Thanks!

**Comment by 4lejandrito** [comment]
Cool, I'll do it tomorrow most likely. Just for your info, this is a new feature for 7.2 so it won't make it to any fix pack for the moment.

**Comment by shuyangzhou** [comment]
Hmm, Brian is still auto back porting to 7.1, right? If it goes into master, it means going in 7.1 too.

**Comment by 4lejandrito** [comment]
Nothing related to this new autotagging feature has been backported. @sergiogonzalez told us that he had green light from @brianchandotcom to start sending new features as long as they were in separate modules. Maybe @brianchandotcom can clarify this just in case.

**Comment by shuyangzhou** [comment]
OK, that's good! Then you have plenty time to work on it.

**Comment by brianchandotcom** [comment]
Merged. Thank you.

View just my changes: https://github.com/brianchandotcom/liferay-portal/compare/4lejandrito:7d1cafe184...37194b9f2d
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/12fb903936...37194b9f2d

**Comment by brianchandotcom** [comment]
@4lejandrito I made a lot of changes in upstream. I also used a new ticket for 4e789e621fc8f43f314334c8aa4188ffd5c15b65 and backported it since it doesn't necessarily have anything to do with this ticket.

@petershin see fa22b37 not sure why SF didn't catch that

**Comment by petershin** [comment]
@brianchandotcom - There isn't a check to auto sort language keys.  Will send a patch

**Comment by jpince** [comment]
@4lejandrito I see this error in the upgrade console log, can you please resolve? Looks like it only affects upgrades.
```
     [exec] 14:01:36,882 ERROR [main][com_liferay_document_library_asset_auto_tagger_tensorflow:97] [com.liferay.document.library.asset.auto.tagger.tensorflow.internal.util.InceptionImageLabeler(1646)] The activate method has thrown an exception 
     [exec] java.nio.file.FileAlreadyExistsException: /opt/dev/projects/github/liferay-portal/bundles/osgi/state/org.eclipse.osgi/400/data/tensorflow-workdir/libtensorflow-1.8.0.jar
```
[Console Log](https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/226078/AXIS_VARIABLE=0,label_exp=!master/consoleFull)

cc/ @austinchiang (this is master-only. Doesn't fail test but errors are present in the log.)

**Comment by jpince** [comment]
additional logs:
[CalendarUpgrade#ViewCalendarArchive612](https://testray.liferay.com/reports/production/logs/test-1-1/1532833471434/test-portal-upstream(master)/448/functional-tomcat90-postgresql94-jdk8/29/0/jenkins-console.txt.gz)
[WorkflowUpgrade#ViewWorkflowArchive704](https://testray.liferay.com/reports/production/logs/test-1-1/1532869348328/test-portal-upstream(master-private)/42/functional-tomcat90-mariadb100-jdk8/76/0/jenkins-console.txt.gz)

**Comment by shuyangzhou** [comment]
it is a dirty shutdown in the upgrade, that is still a problem, this fix is only making sure we can peacefully recover from it.

**Pull request closed without merging**
