### PR TITLE
LPS-60605 Remove no longer necessary alert container in wiki

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by carloslancha** [comment]
cc @jbalsas @robertoDiaz

**Comment by jbalsas** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@brianchiu 2 random failures here.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/16deddef55...6a839cef9d

**Comment by brianchiu** [comment]
@sharonchoi
See bookmarks failure in the first test

@evannagayama
See web content failure after the retest

**Pull request closed without merging**
