### PR TITLE
LPS-80155

### PR DESCRIPTION
**Pull request by topolik**
Hi Brian,

https://issues.liferay.com/browse/LPS-80155

Thank you.

/cc @yxingwu @samuelkong

### CODE REVIEW

**Comment by topolik** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8579a7d16b...67f039ee1e

**Comment by brianchandotcom** [comment]
@topolik @yxingwu @samuelkong see c9ab1a4 thx.

**Comment by brianchandotcom** [comment]
@topolik @yxingwu @samuelkong wrong ref, here's the correct one 67f039ee1ec1e3439d5488532082099d1fba9dc0

**Pull request closed without merging**
