### PR TITLE
LPS-57517

### PR DESCRIPTION
**Pull request by natecavanaugh**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/426c334349...1a25e6d910

**Comment by brianchandotcom** [comment]
@jbalsas can you resend? I rolled it back..

Reason is I searched for <liferay-util:dynamic-include and didn't see anything that looked like yours. They all went based on the JSP name.

I'm ok with your new convention, but I need to know why... and the rationale behind it.

Thx.

**Comment by brianchandotcom** [comment]
@jbalsas so please resend with an argument of one way or the other. Thx.

**Comment by jbalsas** [comment]
Resent with some comments to https://github.com/brianchandotcom/liferay-portal/pull/28762

**Pull request closed without merging**
