### PR TITLE
[Read Inside] LPS-74571 Apply Clay and Bootstrap4

### PR DESCRIPTION
**Pull request by jbalsas**
/cc @Robert-Frampton @vicnate5 @jpince @pat270 @marcoscv-work

From https://github.com/brianchandotcom/liferay-portal/pull/51485, rebased and resent

Hey @brianchandotcom. This is a rather large update for LPS-74571. It is the first step in migrating our theme infrastructure to the latest Lexicon design patterns and Bootstrap 4.

We are expecting a lpkg-release test failure on this PR, it is a known issue and will be addressed once the commerce subrepo is merged (liferay/liferay-portal-ee#2401).

**Note**: since this this marks a divergence from 7.0 themes, we do not want to bump the bnd versions of the **frontend-theme-styled** and **frontend-theme-unstyled** base themes yet, as there will be more stabilizing changes coming down the pipeline. This is why I've temporarily disabled npm publishing for those packages. Once they are ready, we'll need to do a major version increase.

Please let me know if you have any questions.

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:reopen

**Comment by jbalsas** [comment]
Hey @vicnate5, @jpince, all these errors are happening across PRs, other than the `lpkg-release`. We already merged the `commerce` subrepo but it isn't being merged to `central`, so not sure how can we fix that. Can we simply push that change so all these stop auto-closing?

Thanks!

**Comment by jpince** [comment]
@brianchandotcom all upgrade test failures are in upstream, I emailed you about this.
We expect lpkg-release to fail until the lotus theme is fixed by @marcoscv-work:
`Warning: Could not find file /opt/dev/projects/github/liferay-portal/bundles/deploy/commerce-theme-lotus.war to copy.`

**Comment by jbalsas** [comment]
Thanks @jpince! We've already started working on that!

**Comment by jpince** [comment]
@jbalsas Brian is ok with ignoring the lotus theme, but doesn't want an additional failure in CI, so he wants Commerce to merge before this pull.
We're waiting to see if the latest commerce pull https://github.com/liferay/liferay-portal-ee/pull/2421 is good. It looks ok so far since it got past the [compile error from yesterday](https://github.com/liferay/liferay-portal-ee/pull/2401#issuecomment-328576688), but Brian will only force merge if it doesn't introduce any new failures.

**Comment by brianchandotcom** [comment]
@jbalsas 

Se

```
Liferay-Top-Head-Authenticated-JS-Resources:\
	/aui/async-queue/async-queue.js,\
	/aui/base-build/base-build.js,\
	/aui/cookie/cookie.js,\
	/aui/event-touch/event-touch.js,\
	/aui/overlay/overlay.js,\
	/aui/querystring-stringify/querystring-stringify.js,\
	/aui/widget-child/widget-child.js,\
	/aui/widget-position-align/widget-position-align.js,\
	/aui/widget-position-constrain/widget-position-constrain.js,\
	/aui/widget-position/widget-position.js,\
	/aui/widget-stack/widget-stack.js,\
	/aui/widget-stdmod/widget-stdmod.js,\
	/aui/aui-aria/aui-aria.js,\
	/aui/aui-io-plugin-deprecated/aui-io-plugin-deprecated.js,\
	/aui/aui-io-request/aui-io-request.js,\
	/aui/aui-loading-mask-deprecated/aui-loading-mask-deprecated.js,\
	/aui/aui-overlay-base-deprecated/aui-overlay-base-deprecated.js,\
	/aui/aui-overlay-context-deprecated/aui-overlay-context-deprecated.js,\
	/aui/aui-overlay-manager-deprecated/aui-overlay-manager-deprecated.js,\
	/aui/aui-overlay-mask-deprecated/aui-overlay-mask-deprecated.js,\
	/aui/aui-parse-content/aui-parse-content.js,\
	/liferay/layout_exporter.js,\
	/liferay/session.js,\
	/liferay/deprecated.js
Liferay-Top-Head-JS-Resources:\
	/jquery/jquery.js,\
	/clay/bootstrap.js,\
	/loader/config.js,\
	/loader/loader.js,\
	/lodash/lodash.js,\
	/aui/aui/aui.js,\
	/aui/aui-base-html5-shiv/aui-base-html5-shiv.js,\
	/liferay/browser_selectors.js,\
	/liferay/modules.js,\
	/liferay/aui_sandbox.js,\
	/clay/collapsible-search.js,\
	/clay/side-navigation.js,\
	/jquery/fm.js,\
	/jquery/form.js,\
	/lodash/util.js,\
	/misc/svg4everybody.js,\
	/aui/arraylist-add/arraylist-add.js,\
	/aui/arraylist-filter/arraylist-filter.js,\
	/aui/arraylist/arraylist.js,\
	/aui/array-extras/array-extras.js,\
	/aui/array-invoke/array-invoke.js,\
	/aui/attribute-base/attribute-base.js,\
	/aui/attribute-complex/attribute-complex.js,\
	/aui/attribute-core/attribute-core.js,\
	/aui/attribute-observable/attribute-observable.js,\
	/aui/attribute-extras/attribute-extras.js,\
	/aui/base-base/base-base.js,\
	/aui/base-pluginhost/base-pluginhost.js,\
	/aui/classnamemanager/classnamemanager.js,\
	/aui/datatype-xml-format/datatype-xml-format.js,\
	/aui/datatype-xml-parse/datatype-xml-parse.js,\
	/aui/dom-base/dom-base.js,\
	/aui/dom-core/dom-core.js,\
	/aui/dom-screen/dom-screen.js,\
	/aui/dom-style/dom-style.js,\
	/aui/event-base/event-base.js,\
	/aui/event-custom-base/event-custom-base.js,\
	/aui/event-custom-complex/event-custom-complex.js,\
	/aui/event-delegate/event-delegate.js,\
	/aui/event-focus/event-focus.js,\
	/aui/event-hover/event-hover.js,\
	/aui/event-key/event-key.js,\
	/aui/event-mouseenter/event-mouseenter.js,\
	/aui/event-mousewheel/event-mousewheel.js,\
	/aui/event-outside/event-outside.js,\
	/aui/event-resize/event-resize.js,\
	/aui/event-simulate/event-simulate.js,\
	/aui/event-synthetic/event-synthetic.js,\
	/aui/intl/intl.js,\
	/aui/io-base/io-base.js,\
	/aui/io-form/io-form.js,\
	/aui/io-queue/io-queue.js,\
	/aui/io-upload-iframe/io-upload-iframe.js,\
	/aui/io-xdr/io-xdr.js,\
	/aui/json-parse/json-parse.js,\
	/aui/json-stringify/json-stringify.js,\
	/aui/node-base/node-base.js,\
	/aui/node-core/node-core.js,\
	/aui/node-event-delegate/node-event-delegate.js,\
	/aui/node-event-simulate/node-event-simulate.js,\
	/aui/node-focusmanager/node-focusmanager.js,\
	/aui/node-pluginhost/node-pluginhost.js,\
	/aui/node-screen/node-screen.js,\
	/aui/node-style/node-style.js,\
	/aui/oop/oop.js,\
	/aui/plugin/plugin.js,\
	/aui/pluginhost-base/pluginhost-base.js,\
	/aui/pluginhost-config/pluginhost-config.js,\
	/aui/querystring-stringify-simple/querystring-stringify-simple.js,\
	/aui/queue-promote/queue-promote.js,\
	/aui/selector-css2/selector-css2.js,\
	/aui/selector-css3/selector-css3.js,\
	/aui/selector-native/selector-native.js,\
	/aui/selector/selector.js,\
	/aui/widget-base/widget-base.js,\
	/aui/widget-htmlparser/widget-htmlparser.js,\
	/aui/widget-skin/widget-skin.js,\
	/aui/widget-uievents/widget-uievents.js,\
	/aui/yui-throttle/yui-throttle.js,\
	/aui/aui-base-core/aui-base-core.js,\
	/aui/aui-base-lang/aui-base-lang.js,\
	/aui/aui-classnamemanager/aui-classnamemanager.js,\
	/aui/aui-component/aui-component.js,\
	/aui/aui-debounce/aui-debounce.js,\
	/aui/aui-delayed-task-deprecated/aui-delayed-task-deprecated.js,\
	/aui/aui-event-base/aui-event-base.js,\
	/aui/aui-event-input/aui-event-input.js,\
	/aui/aui-form-validator/aui-form-validator.js,\
	/aui/aui-node-base/aui-node-base.js,\
	/aui/aui-node-html5/aui-node-html5.js,\
	/aui/aui-selector/aui-selector.js,\
	/aui/aui-timer/aui-timer.js,\
	/liferay/dependency.js,\
	/liferay/dom_task_runner.js,\
	/liferay/events.js,\
	/liferay/language.js,\
	/liferay/liferay.js,\
	/liferay/util.js,\
	/liferay/portal.js,\
	/liferay/portlet.js,\
	/liferay/workflow.js,\
	/liferay/address.js,\
	/liferay/form.js,\
	/liferay/form_placeholders.js,\
	/liferay/icon.js,\
	/liferay/menu.js,\
	/liferay/notice.js,\
	/liferay/poller.js
```

The entries should be sorted. If they are not sorted because order matters. Then, you should sort what you can into blocks, and use a line separator to say that this block must go before this block, and sort within a block.

Then resend..

```
Liferay-Top-Head-JS-Resources:\
	/jquery/jquery.js,\
	/clay/bootstrap.js,\
	/loader/config.js,\
```

is wrong, should be like this if order doesn't mater for this block

```
Liferay-Top-Head-JS-Resources:\
	/clay/bootstrap.js,\
	/jquery/jquery.js,\
	/loader/config.js,\
```

or like this if jquery has to come first, but clay and loader can be sorted

```
Liferay-Top-Head-JS-Resources:\
	/jquery/jquery.js,\
        \
	/clay/bootstrap.js,\
	/loader/config.js,\
```

or like this if jquery has to come first, then clay, and then loader.

```
Liferay-Top-Head-JS-Resources:\
	/jquery/jquery.js,\
        \
	/clay/bootstrap.js,\
        \
	/loader/config.js,\
```
Please fix and resend. Thx.

**Comment by Robert-Frampton** [comment]
@brianchandotcom resent at https://github.com/brianchandotcom/liferay-portal/pull/51506.

**Pull request closed without merging**
