### PR TITLE
LPS-108954 fixes empty state description color

### PR DESCRIPTION
**Pull request by fapires**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:close

**Comment by jeyvison** [comment]
ci:reopen

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7cfb585a8c...d1f517b3a6

**Pull request closed without merging**
