### PR TITLE
LPS-52728 Structure field types are not sorted correctly in the Asset Publisher

### PR DESCRIPTION
**Pull request by arboliveira**
Author: @Preston-Crary 
Reviewer: @arboliveira

### CODE REVIEW

**Comment by kiyoshilee** [comment]
ci:retest

**Comment by kiyoshilee** [comment]
@arboliveira I believe you will need to publicly set on your profile that you belong to the Liferay organization. This was from Brian's email earlier:

We need everyone who wishes to have their pull requests tested by the CI server to publicly put on their GitHub profile that they belong to the Liferay org.

If you don't, then when you send a pull, the CI server will assume it's malicious and not test the pull. We have to use this public info so that our CI servers run with an unprivileged account.

For steps in how to do this please see this <a href="https://help.github.com/articles/publicizing-or-concealing-organization-membership/">link</a>.

After you have finished doing this please add a comment with ci:retest in order to retest this pull request.

**Comment by brianchandotcom** [comment]
@arboliveira please resend. See coments from @kiyoshilee

**Comment by arboliveira** [comment]
Done, Liferay membership now public on GitHub :smiley:

Re-sent as https://github.com/brianchandotcom/liferay-portal/pull/24122.

**Pull request closed without merging**
