### PR TITLE
LPS-76089 Auto

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by jpince** [comment]
@pyoo47 @michaelhashimoto jenkins failures?

**Comment by pyoo47** [comment]
@jpince Looks like the slave died.

**Comment by brianchandotcom** [comment]
@ealonso @jkappler I see why you put it in "internal.access.policy" and that makes sense, but that sort of corrects the fact that LayoutTypeAccessPolicy is in model and not in access.policy.

I'm not fond of "correcting" the kernel path from a module unless we correct the kernel path.

Can you resend and put it in the package model to match the class it extends? If you disagree, resend in the form you believe is best (or that adheres to other patterns already in the codebase).

**Comment by brianchandotcom** [comment]
@ealonso @jkappler I see why you put it in "internal.access.policy" and that makes sense, but that sort of corrects the fact that LayoutTypeAccessPolicy is in model and not in access.policy.

I'm not fond of "correcting" the kernel path from a module unless we correct the kernel path.

Can you resend and put it in the package model to match the class it extends? If you disagree, resend in the form you believe is best (or that adheres to other patterns already in the codebase).

**Pull request closed without merging**
