### PR TITLE
Runtime Support: proper URLs when running under Windows systems

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by migue** [comment]
This was a subtle one ...

@lionah This should solve your problem (I tested it under a windows machine and everything seems to be working properly fine)

@jorgeferrer FYI since you ask me to take a look :D

**Comment by JorgeFerrer** [comment]
Thanks a lot Miguel!

**Comment by lionah** [comment]
:+1: :tada: Thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3bdeeeedec...f560701dfa

**Comment by brianchandotcom** [comment]
Thx @migue !

**Pull request closed without merging**
