### PR TITLE
LPS-102447 Fix enum field names

### PR DESCRIPTION
**Pull request by petershin**
@amosfong

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/09259f172b...28a967208b

**Comment by brianchandotcom** [comment]
@amosfong I'm going to publish a new REST builder in a few minutes

**Comment by amosfong** [comment]
thanks @petershin @brianchandotcom !

**Comment by brianchandotcom** [comment]
@amosfong published.

**Pull request closed without merging**
