### PR TITLE
Lps 73830 

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:reopen

**Comment by tinatian** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest - Jenkins master had to be restarted.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c64d47bb72...a558ad7649

**Pull request closed without merging**
