### PR TITLE
LPS-129049 | master

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LPS-129049

**Summary:**
This is followup to https://github.com/brianchandotcom/liferay-portal/pull/100963. This PR 1) adds a few basic Click to Chat tests, 2) adds a new `click-to-chat` test suite, and 3) adds Click to Chat relevant suite functional tests (not enabled yet as we monitor these tests for stability).

**Test Results:**
[ci:test:relevant - 20 out of 22 jobs passed in 2 hours 5 minutes](https://github.com/xbrianlee/liferay-portal/pull/587#issuecomment-825988615)
The only test failure is unrelated to the changes in this PR.

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:reopen

**Comment by xbrianlee** [comment]
cc/ @joseabelenda @Paulovcaselli

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/06dcbe7819...706438ccd1

**Comment by brianchandotcom** [comment]
@xbrianlee @Paulovcaselli see 706438ccd19981de320660fb91fef95f4969771a

This is so good now.

**Comment by brianchandotcom** [comment]
@joseabelenda first tests checked in now

**Comment by joseabelenda** [comment]
Nice!

Thanks @brianchandotcom @xbrianlee @Paulovcaselli

**Pull request closed without merging**
