### PR TITLE
LPS-90257 Add dropdown menu to the User Personal Bar

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @stsquared99 @alee8888 @ChrisKian

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:reopen

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
ci:test:relevant (We had a jspc error that was fixed)

**Comment by jpince** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jpince** [comment]
ci:test:sf could not reproduce errors locally <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5d90ee0a92...8550797763

**Comment by brianchandotcom** [comment]
@pei-jung I made a few minor changes, I believe Registry classes usually just go next to what they register.

**Pull request closed without merging**
