### PR TITLE
LPS-107659 Renames Theme Name from Latin to English: Chameleon

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@marcoscv-work there are still references to the old value, type:

git grep "hamaeleon"

**Comment by jbalsas** [comment]
Ugh, that's my fault, I somehow forgot to commit the changes or something... I'll resend :(

**Comment by brianchandotcom** [comment]
@jbalsas I asked @marcoscv-work to do it this time since there are still typos.

**Comment by brianchandotcom** [comment]
@jbalsas no no, delegate!

**Comment by jbalsas** [comment]
👍

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/84260

**Pull request closed without merging**
