### PR TITLE
LPS-79514 Add configuration category to Analytics

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f758f39c37...fd856eeb36

**Comment by brianchandotcom** [comment]
@jorgeferrer see my changes for consistency in 1cb873017e2bddd6e599c9d5ec7e3dc47fcc4fbe and fd856eeb36d699148c29f9a9cce5e1ffa3f550bd

Thx

**Comment by JorgeFerrer** [comment]
Thanks @brianchandotcom. I had already noticed some of those inconsistencies and was on my TODO list to fix them, so one less thing to do :)
There a couple others (such as with locale vs languageId) that I'll fix in my next pulls.

**Pull request closed without merging**
