### PR TITLE
LPS-85721 New service methods for user data sync does not handle optional values

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-85721](https://issues.liferay.com/browse/LPS-85721).<br><br>/cc @pei-jung @stsquared99 @alee8888

### CODE REVIEW

**Comment by drewbrokke** [comment]
cc @shinnlok

**Comment by shinnlok** [comment]
Thanks @drewbrokke!!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/50532088a2...108a9596c4

**Comment by brianchandotcom** [comment]
Very nice job @drewbrokke !

**Pull request closed without merging**
