### PR TITLE
Lps 69939

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pyoo47 lots of errors here. What happened? I'm closing. @shuyangzhou please coordinate with @pyoo47 to see why this pull had so many errors. Thx.

**Comment by shuyangzhou** [comment]
Some sort of NPM failure.
```
     [exec] * What went wrong:
     [exec] A problem occurred configuring project ':apps:collaboration:wiki:wiki-web'.
     [exec] > Version in npm-shrinkwrap.json must match project version
```

**Comment by shuyangzhou** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/45967

**Pull request closed without merging**
