### PR TITLE
LPS-102810 Add date fields to ratingStats

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4694200a89...6ea567b75e

**Comment by brianchandotcom** [comment]
@nhpatt not backporting this to 7.2.x

This means our new forums app is really for 7.3.x - and that's OK. We'll target a January release.

**Comment by nhpatt** [comment]
Thanks!

**Pull request closed without merging**
