### PR TITLE
LPS-175292

### PR DESCRIPTION
**Pull request by marinaasant0s**

### CODE REVIEW

**Comment by marinaasant0s** [comment]
The SF is failing due an unrelated error https://github.com/pt-liferay-solutions/liferay-portal/pull/3434#issuecomment-1460922017

**Comment by marinaasant0s** [comment]
ci:reopen

**Comment by marinaasant0s** [comment]
ci:test:sf

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5c895fdfc9...22753df398

**Pull request closed without merging**
