### PR TITLE
LPS-59561 Fix returning directories

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
Awesome @csierra, thanks a lot for the quick fix!!! :+1::+1::tada::tada:

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6683f9760d...bc0d71e48e

**Comment by brianchandotcom** [comment]
@csierra @jkappler I upgraded the other modules to use the latest published module now.

**Comment by csierra** [comment]
Thanks Brian!

**Pull request closed without merging**
