### PR TITLE
LPS-79703 Auto

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by timpak** [comment]
ci:close

**Comment by timpak** [comment]
@ealonso looks like the build failure is related. can you look into this please? Thanks!

`     [exec] > Project with path ':test:arquillian-extension-junit-bridge' could not be found in project ':apps:web-experience:asset:asset-display-page-test'.`

**Comment by ealonso** [comment]
ci:reopen

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
@timpak I've tried it locally and everything works fine, I'm going to execute the test again

**Comment by ealonso** [comment]
@timpak Do you know why this is happening here? locally it is working fine

**Comment by ealonso** [comment]
ci:test

**Comment by timpak** [comment]
hi @ealonso, @jpince and I are going to investigate this.

**Comment by jpince** [comment]
@ealonso I'm pretty sure the *-test directory should not include a [.lfrbuild-portal file](https://github.com/ealonso/liferay-portal/commit/9b0d7c6d60bf71c0f9316cbce0197c77c658d315#diff-8b4cf147e32f2e11a2f62e2f87e75290). I'm not sure why this doesn't fail locally for you, but I'm pretty sure that's why the pull is failing.

**Pull request closed without merging**
