### PR TITLE
LPS-70347 Use released version

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchandotcom** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@sergiogonzalez I'll fix the SF.

**Comment by brianchandotcom** [comment]
@sergiogonzalez does it have to be 2.0.2 or can it be 2.0.0? Why are we using a minor version?

**Comment by 4lejandrito** [comment]
@brianchandotcom I did fix the SF here: https://github.com/brianchandotcom/liferay-portal/pull/46470.

We can carry on with the conversation there or close it.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/12ef939a72...77600d3db8

**Pull request closed without merging**
