### PR TITLE
LPS-106614

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-106614](https://issues.liferay.com/browse/LPS-106614).<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez @petershin

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
This pull is intended to fix the upstream failures in `LanguagePropertyTest`

**Comment by drewbrokke** [comment]
@pyoo47 can I manually invoke the tests for `portal-kernel` or will they be part of `relevant`?

**Comment by pyoo47** [comment]
@drewbrokke I don't think there's a test-suite for portal-kernel. I think relevant will run at least some of them.

**Comment by pyoo47** [comment]
ci:help

**Comment by brianchandotcom** [comment]
Very nice @drewbrokke !

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/978d9a10f4...20e55d58a8

**Pull request closed without merging**
