### PR TITLE
LRCI-484, LRCI-492, LRCI-494 ant updates for k8s

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRCI-484
https://issues.liferay.com/browse/LRCI-492
https://issues.liferay.com/browse/LRCI-494
https://issues.liferay.com/browse/LRCI-487

### CODE REVIEW

**Comment by kenjiheigel** [comment]
Backports:
https://github.com/brianchandotcom/liferay-portal-ee/pull/25679 (7.1.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/25680 (7.0.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/25681 (ee-6.2.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/25682 (ee-6.2.10)
https://github.com/brianchandotcom/liferay-portal-ee/pull/25683 (ee-6.1.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/25684 (ee-6.1.30)

**Comment by kenjiheigel** [comment]
@brianchandotcom, you'll be seeing double in these sets of pulls because we're testing out the k8s Jenkins master (test-4-1), you can ignore failures from there for now...

**Comment by kenjiheigel** [comment]
cc-ing: @pyoo47, @michaelhashimoto

**Comment by kenjiheigel** [comment]
Actually going to kill the test-4-1 run. It's gonna pull too many resources from current testing.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/26c0d0a231...ee855ee859

**Pull request closed without merging**
