### PR TITLE
Lps 56171 Revert changes about cache API

### PR DESCRIPTION
**Pull request by tinatian**
cc @mhan810 @shuyangzhou

Hi Brian,

I am sorry to bother you to revert all the changes I made about cache API yesterday, I did not think too much about the upgrade and backwards compatibility for customers. 

In this pull, I reverted all the changes I made, will redo the harmless ones later.

Sorry again about this.

Tina.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@tinatian the packages are already different since we moved them to a module. It's already not backwards compat even with this revert? I think it's OK with the rename especially since this is 7.0?

**Comment by tinatian** [comment]
Yes, we did some refactoring for 7.0, while I changed API which may cause a lot of unnecessary code conflicts when doing upgrade, like PortalCache.getName to PortalCache.getPortalCacheName, I did not think too much about this at the beginning, Michael called my attention to this, so I am thinking to downsize the changes, so that we do not need to document all the API changes and might be easier for customers to upgrade their own customized code. 

What do you think?

Tina.

**Comment by brianchandotcom** [comment]
I I think it's OK for clarity's sake. I would document it in readme/7.0/BREAKING_CHANGES.markdown

As you can tell, it's already very large. I would change the code and optimize for clarity and moving forward. We've already done so many changes for this release to make things better.

**Comment by mhan810** [comment]
@brianchandotcom these are core caching APIs for MultiVMPool and etc.  Its
not a good idea to do this especially since we have quite a few customers
using them and this is just a renaming for renaming sake, not because we
are adding features or correcting bad API.

**Pull request closed without merging**
