### PR TITLE
LPS-77909 Create a UserActionContributor entry for the UAD portlet

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-77909](https://issues.liferay.com/browse/LPS-77909).<br><br>Hey Brian, this is the UserActionMenuContributor for the UAD portlet (so we can actually navigate to it). It's using the new API you merged yesterday. There is a new language key in this pull - can you please run buildLang? Thanks!<br><br>/cc @pei-jung @willnewbury @noahsherrillwork

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@sergiogonzalez this is related to Sharepoint for master-private, can you guys fix this? @adolfopa Thx

**Comment by brianchandotcom** [comment]
@drewbrokke merged..

**Comment by adolfopa** [comment]
@brianchandotcom Is this still happening? The build is complaining about a missing .lfrbuild-portal, but the files are there (I've checked both on master-private and 7.0.x-private). Also, I've run the integration tests locally, and everything seems fine.

No idea what may be happening here :-(

**Pull request closed without merging**
