### PR TITLE
Lps 58134

### PR DESCRIPTION
**Pull request by shuyangzhou**
@csierra please see my commit message at https://github.com/brianchandotcom/liferay-portal/commit/8924b0354d00e6344052826c5c0e432b83b3d19d

So even with this fix, it only lower the chance of seeing a real race condition, it does not eliminate it.

We should avoid doing this kind of System.out/System.err swapping at all cost for production code.

I don't know what was the original requirement that led you to this solution. Please fill me in about why we need this, I will try to find out a way to avoid doing this.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/348a912b4d...18c31b3f88

**Comment by brianchandotcom** [comment]
@shuyangzhou how did you even know there was a problem? Did it show up in a CI test somehwere?

fyi @csierra @jorgeferrer

**Comment by shuyangzhou** [comment]
@brianchandotcom I caught it during code review for https://github.com/shuyangzhou/liferay-portal/pull/1918
We did not have any test that can cover it, therefore there was no error.
If you undo the code fix, but keep the new unit test I created here, you will see how it fails.
System.out/System.err are global resources that can be accessed by anyone within the jvm at anytime. Even we can ensure we never race with ourselves, portal does not own the jvm, it is just a webapp inside the appserver, the appserver itself or any other webapps inside could "randomly" do outputs while we swapped it, causing mixed output collecting result, which will be totally meaningless.

**Comment by csierra** [comment]
hey @shuyangzhou, 

this was intended to be used in the upgrade processes and DB processes that are (or at least were) intended to be run offline using the upgrade tool.

**Comment by shuyangzhou** [comment]
@csierra

Does offline here mean running out side portal jvm?
Or it just means it runs before portal start to receive requests?

If it is out side portal jvm, and we have control over everything, this is fine, but we should move it close to it usage. Currently it is a kernel util, which can be used for wrong purpose in the future.

If it is just before request serving, then it is not ok, we have to remove it. As portal is not ready, does not mean other webapps in the same appserver are not ready. They could race with us.

Can you show me a usage of it? What exact output we are trying to collect here?

Thanks

Shuyang

**Comment by csierra** [comment]
@shuyangzhou 

offline meant outside the portal jvm... but yes, I agree it could be misused in the future being there. 
The offline tool uses gogo shell to launch the upgrades and verifiers and this tool was intended to collect the output of UpgradeProcesses that were not upgraded to the new interface UpgradeStep (which receives a context that contains an OutputStream for reporting). Some of our colleagues asked for this to be able to store in different temp files (for instance) the output of the upgrade processes.

The intention was to migrate the UpgradeProcesses to the new interface.

If this is not happening and/or the Upgrades are to be run inside the portal jvm then I agree we need to do something different or drop the feature.

**Comment by shuyangzhou** [comment]
Thanks for the explanation @csierra !

If I am understanding right, what you really want to intercept is the logger output from some UpgradeProcesses, right?

It just happens to be our logger default to output to std out, but logger is configurable, it can be configured to only log to file, not system.out. Then this feature is going to break.

What we really need here is a way to intercept logger output, as we have it already for test only purpose. It should be very easy to refine it a bit to make it production ready.

Can you show me an use case that we currently have? What do I do to actually use this? I can try to redo the feature via the logger interception.

**Comment by csierra** [comment]
Hey @shuyangzhou, 

thank you for you offer. We are still discussing whether we are going to allow db intensive processes to be run alongside the portal. If we decide to keep the ability to run them within the portal we can reimplement this feature using the logger interception. We know you are a busy man so I believe there is no need to bother you with this. 

Bests.

Carlos.

**Comment by shuyangzhou** [comment]
Ok, then I will leave it to you @csierra , thanks for the explanation, and let me know if you need help.

**Pull request closed without merging**
