### PR TITLE
LPS-106125 Wait for a task to arrive before updating the instance

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:test:stop

**Comment by brianchandotcom** [comment]
@rafaprax @inacionery since this is a new module, can we prefix ddm* for the vars?

See DDMFormInstanceDemoDataCreatorImpl.java

```
		DDMStructure structure = _ddmStructureDemoDataCreator.create(
			groupId, userId);

		DDMFormValues ddmFormValues
```

This is new, so we can always go with the longer more consistent naming for everything.

**Comment by inacionery** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by inacionery** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/84197

**Pull request closed without merging**
