### PR TITLE
LPS-53994 Make arquillian-extension-junit-bridge depends on arquillian-c...

### PR DESCRIPTION
**Pull request by shuyangzhou**
...ontainer-liferay and arquillian-deployment-generator-bnd, so that the modules need arquillian test only needs to depend on arquillian-extension-junit-bridge

@brianchandotcom please publish this module first, then I will send the usage apply pull.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
Those are the known random failing OSGi related errors. I will get to them some time later.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/83c2d5fbbf...4a163cf836

**Comment by brianchandotcom** [comment]
Done. Published a new snapshot.

**Pull request closed without merging**
