### PR TITLE
LPS-95734 Buildlang

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
@drewbrokke could you please take a look at [this](https://github.com/brianchandotcom/liferay-portal/pull/73299/commits/c1575c2ce9e0b2adb5baaea6a9b4d8e74926f852) commit?

/cc @JorgeFerrer

**Comment by jpince** [comment]
@pavel-savinov I don't see the fragment int test failures in upstream, can you please take a look?

cc/ @brianchiu @kyle-miho

**Comment by brianchandotcom** [comment]
@pavel-savinov FreeMarker, not Freemarker. I fixed this a few days ago and just fixed it again today.

From a few days ago d208b5548059cda2f21e01454aef9787a5f59024

Today's change bfe8fef788f49341f63135143c5a22c8238cbf8b 

Just fyi @pavel-savinov thx

**Comment by drewbrokke** [comment]
@pavel-savinov if I'm reading this correctly, it looks like that commit covers the case where the `Meta.AD` annotation has both an `id` attribute and a `deflt` attribute with a value of "true".  If so then it looks fine to me.  `Configurable` does the same thing internally, so it makes sense to have our InvocationHandler do the same thing.

**Pull request closed without merging**
