### PR TITLE
LPS-80286

### PR DESCRIPTION
**Pull request by bawachhe**
https://issues.liferay.com/browse/LPS-80286

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d6ef0f2011...4eb2a023ef

**Comment by brianchandotcom** [comment]
@jonmak08 I backported to 7.1.x. If these need to go to 7.0.x, a pull needs to be sent to support.

**Comment by jonmak08** [comment]
Hey @brianchandotcom,

Yup, I have it in the queue.  Just waiting for QA to test and close it out first.  Thanks!

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/brianchandotcom/liferay-portal-ee/pull/21708

**Pull request closed without merging**
