### PR TITLE
LPS-66216

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @jorgediaz-lr @robertoDiaz @ealonso

**Comment by jpince** [comment]
@brianchandotcom poshi errors are unrelated, good to merge from a poshi perspective.

**Comment by jorgediaz-lr** [comment]
This LPS was commited to master:
   - https://github.com/liferay/liferay-portal/commit/e74d5ba69bff00c8b5a59f08c6b98d28fb81d45f
   - ticket is in resolved status: https://issues.liferay.com/browse/LPS-66216

So this pull can be closed

**Comment by sergiogonzalez** [comment]
Closing. Thanks @jorgediaz-lr

**Pull request closed without merging**
