### PR TITLE
LPS-62075 Message Boards Portlet Configuration Icons for categories

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4f442c4e92...7cbb6c4627

**Comment by brianchandotcom** [comment]
Very nice @sergiogonzalez

**Pull request closed without merging**
