### PR TITLE
LPS-55566 Apply naming pattern proposed by Brian

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/869ec7986f...ae66b94b05

**Comment by brianchandotcom** [comment]
@izaera 

You missed quite a few. See upstream for my changes. Also, this is much cleaner now because it matches with existing methods in DLApp*

See

```
	protected LocalRepository getFileEntryLocalRepository(long fileEntryId)
		throws PortalException {

		try {
			return RepositoryProviderUtil.getFileEntryLocalRepository(
				fileEntryId);
		}
```

Very clean now. In your initial pull, you had getFileEntryLocalRepository in one place, but getLocalRepositoryByFileEntryId in another place. I bring this up so you proactively apply these type of consistent patterns to code you started from scratch (like Settings).

**Pull request closed without merging**
