### PR TITLE
LPS-91343

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@petershin, there is no better way to do this? https://github.com/brianchandotcom/liferay-portal/pull/68745/commits/b54030f88d04c34debc326ea2ab06ef064fa8630

@brianchandotcom, will deprecated logic in ToolsUtil after also applying to `InstanceWrapperBuilder.java

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
@petershin, why is it not using latest SB?

**Comment by brianchandotcom** [comment]
Well, this beats the record of number of lines changed in 1 pull...

I'll be regenerating the other branches...

**Pull request closed without merging**
