### PR TITLE
LPS-64075

### PR DESCRIPTION
**Pull request by natecavanaugh**

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
I'm re-running it by rebasing off of f91842db236545afdb2ce4ba80dcccb6acf0f8db

**Comment by brianchandotcom** [comment]
@pat270 please resend, see broken poshi.

**Comment by sharonchoi** [comment]
@kenjiheigel this might have something to do w/ your updating all the table locators?

**Comment by kenjiheigel** [comment]
@natecavanaugh @pat270, I'll take a look at this.

**Comment by kenjiheigel** [comment]
Pushed to @pat270 
https://github.com/pat270/liferay-portal/pull/160

There's rebase errors now, so Patrick will resend to BChan.

**Pull request closed without merging**
