### PR TITLE
LPS-73488 Add WebXML30Descriptor to handle "async-supported" element …

### PR DESCRIPTION
**Pull request by shuyangzhou**
…ordering

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:stop

**Comment by michaelhashimoto** [comment]
ci:retest - https://loop.liferay.com/home/-/loop/feed/6170033

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3a2e9a5051...254765b4cc

**Pull request closed without merging**
