### PR TITLE
LPS-74839 (required changes applied, unit tests can't be moved to test subpackage) As Developer I need Petra JSON WS Client to properly handle 202 and 204 HTTP Status

### PR DESCRIPTION
**Pull request by igorbeslic**
Hi Brian please review. Thank you. @mladencikara @ivicac

### CODE REVIEW

**Comment by igorbeslic** [comment]
ci:reopen

**Comment by igorbeslic** [comment]
Hi @brianchandotcom please review this one. Thank you!

PS. tests in this PR are unit tests. If I move them into test subpackage source formatter would complain. Unit tests in petra modules are not placed into test subpackage too.

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5438f48236...0ba7859279

**Pull request closed without merging**
