### PR TITLE
LPS-58897

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@brianchandotcom the problem is the need to publish out the portal-cache-test-common module since the portal-cache modules depend upon it.  Once the module gets published it these will clear

**Comment by brianchandotcom** [comment]
@mhan810 @tinatian can you resend and have it depend on it via a compile project(":portal-cache:portal-cache")

I'm weary of merging this and then publishing it. If it has an error, it'll affect all other programmers.

Thx.

**Comment by mhan810** [comment]
Yep that works will do later today



*From:* Brian Chan [mailto:notifications@github.com]
*Sent:* Friday, October 16, 2015 12:39 PM
*To:* brianchandotcom/liferay-portal <liferay-portal@noreply.github.com>
*Cc:* Michael Han <michael.han@liferay.com>
*Subject:* Re: [liferay-portal] LPS-58897 (#31107)



@mhan810 <https://github.com/mhan810> @tinatian
<https://github.com/tinatian> can you resend and have it depend on it via a
compile project(":portal-cache:portal-cache")

I'm weary of merging this and then publishing it. If it has an error, it'll
affect all other programmers.

Thx.

—
Reply to this email directly or view it on GitHub
<https://github.com/brianchandotcom/liferay-portal/pull/31107#issuecomment-148781231>
.

**Comment by tinatian** [comment]
Resend, please see https://github.com/brianchandotcom/liferay-portal/pull/31264

**Pull request closed without merging**
