### PR TITLE
LPS-205243

### PR DESCRIPTION
**Pull request by Mikellorza**

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3e152f4f5a...b0252039a0

**Comment by brianchandotcom** [comment]
@Mikellorza Hey, I found some code that was not logical. See 1f42347f and other changes in my origin.

**Comment by Mikellorza** [comment]
@brianchandotcom thanks

**Pull request closed without merging**
