### PR TITLE
Lps 100348

### PR DESCRIPTION
**Pull request by shuyangzhou**
Hystrix has some very bad ThreadLocal usage and weird threadpool usage. This fixes the problem, but I really doubt we have enough reason to use Hystrix in the first place. The logic we need could be easily changed to an explicit threadpool usage.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Thx @shuyangzhou !

fyi @leoadb @rodrigopaulino

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b71eb99d9f...8cc4287f0c

**Comment by brianchandotcom** [comment]
@shuyangzhou this causes a smoke error (see CI results here)

Rolled back. Please resend.

**Comment by shuyangzhou** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/77707

**Pull request closed without merging**
