### PR TITLE
LPS-54053 [WARING] TESTING PORPOUSES--> WORK IN PROGRESS (reactivation of wiki tests)

### PR DESCRIPTION
**Pull request by robertoDiaz**
@brianchandotcom NOT TO REVIEW

I'm working on this and this is only for testing

Thx!

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Can you resend when you want me to merge this in? Thx.

**Comment by robertoDiaz** [comment]
Sure,  we wanted to test the whole portal test set in the CI 

Thx

**Comment by robertoDiaz** [comment]
ci:retest

**Pull request closed without merging**
