### PR TITLE
LPS-173768 Fix compile issue

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:reopen

**Comment by jkappler** [comment]
@ealonso

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b96c637189...2fa1f9659a

**Comment by brianchandotcom** [comment]
My bad @jkappler @ealonso ! Thank you guys!

**Pull request closed without merging**
