### PR TITLE
LPS-79711 Fixing images paths everywhere

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1b46f98434...705e3d5e3a

**Comment by brianchandotcom** [comment]
@4lejandrito I wanted to make some progress, so I partially merged in this pull.

I ddin't merge in https://github.com/brianchandotcom/liferay-portal/pull/57314/commits/009f42759cb3b1d04ea5ea016afe163394029c48

It doesnt make sense to me why we can't sort the html attributes.. why does it have to be in that order? I'm worried it's from a hashed list, in which case it may work just in some cases and will break in the future.

I'll merge in https://github.com/brianchandotcom/liferay-portal/pull/57314/commits/61f87b5684dc972565f6cb4e585efc7db3afa72f once you send me a pull with a clean run.

Merged everything else.

Thx.

**Comment by brianchandotcom** [comment]
@4lejandrito you'll need to backport this whole ticket too once it's done. Thx.

**Pull request closed without merging**
