### PR TITLE
LPS-61969 move control menu entry to its right owner

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@brianchiu nothing is green. Need help. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/533ecf802f...714eb9a702

**Comment by brianchiu** [comment]
@brianchandotcom 

The failure on here was fixed with: https://github.com/brianchandotcom/liferay-portal/pull/34533. It started happening because of a UI change.

So things SHOULD be green now.

**Pull request closed without merging**
