### PR TITLE
Lps 143575 2

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by amosfong** [comment]
@jpince mentioned we wait for thursday to merge for maximum time for testing?

**Comment by shuyangzhou** [comment]
@amosfong I did not get the message, where he said it? So you want to take this pull off for now?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9babcdd860...dc85c3e1a0

**Comment by brianchandotcom** [comment]
@amosfong @shuyangzhou 3 days of testing should be enough.

But I did limit this to just 7.4.x. See ce84481dd077f4c65a10234c9496fde6d7be8221

**Pull request closed without merging**
