### PR TITLE
LPS-77756 As a developer I need to have a way of deleting or resetting public and private site data without harming a user

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-77756](https://issues.liferay.com/browse/LPS-77756).<br><br>Hey Brian, this covers the case where we couldn't delete a user's personal site because it belongs to a user group.<br><br>/cc @pei-jung @willnewbury

### CODE REVIEW

**Comment by drewbrokke** [comment]
cc @dejuknow

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by dejuknow** [comment]
@drewbrokke I get a "User Associated Data is temporarily unavailable." message and the following exception when trying to test this: https://pastebin.com/raw/F70Z6ywR

**Comment by drewbrokke** [comment]
Hey @dejuknow, could you come up with some steps to reproduce this and file a ticket and assign it to me?  I'm not able to reproduce right now, so doing that would help me figure out what's going on.  I see NPE's at the JSP level, but I'll need to be able to reproduce locally to get any further.

**Comment by dejuknow** [comment]
@drewbrokke Actually, this no longer occurs after updating to master and resetting my db today. thx.

**Pull request closed without merging**
