### PR TITLE
LPS-191424 fix: Suitable but non-accessible field error in class RoleNotificationRecipientBuilder

### PR DESCRIPTION
**Pull request by dantewang**
FYI @tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0ef915a9ee...b453efa663

**Comment by brianchandotcom** [comment]
@dantewang should we SF enforce this? There are rules for when they can be protected and when they can be private right ? @ling-alan-huang fyi.

**Comment by dantewang** [comment]
@brianchandotcom @ling-alan-huang Generally if a `@Component` has subclass which is also `@Component`, and the module they are in has `-dsannotations-options: inherit`, then it should have all its `@Reference` fields protected.

**Pull request closed without merging**
