### PR TITLE
LPS-86137 Check in case cssStyle.rules is null

### PR DESCRIPTION
**Pull request by p2kmgcl**
/cc @brianchiu
/cc @kyle-miho 
/cc @pavel-savinov 
/cc @ealonso

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@kyle-miho @brianchiu POSHI failures

**Comment by kyle-miho** [comment]
@jpince Failures look unrelated. The ContentPage failures are my fault, sending a pull in for those soon.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bd70fbc2ce...7dab7edd59

**Comment by brianchandotcom** [comment]
@p2kmgcl can we change the ' to " in background_image_field_template.tmpl

If so, can you send a pull to modify:

url('[#if field_name??]${field_name}[/#if]')

I want to use double quotes.

Thx.

**Pull request closed without merging**
