### PR TITLE
LPS-131281 Object actions permissions

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/32e642fe7a...2a510d1b1b

**Comment by brianchandotcom** [comment]
@javierdearcos @nhpatt fyi 2a510d1

**Comment by nhpatt** [comment]
Thanks!

**Pull request closed without merging**
