### PR TITLE
LPS-100148 portal-kernel test fix (sorry, I missed this error)

### PR DESCRIPTION
**Pull request by igorbeslic**
Hi Brian please review, thank you!

### CODE REVIEW

**Comment by igorbeslic** [comment]
@amosfong

**Comment by jpince** [comment]
@kenjiheigel @pyoo47 `ci:test:relevant` failure on the test-4-1 run

**Comment by pyoo47** [comment]
@jpince, We are seeing network drops from time to time on test-4.  We've actually also seen them on test-1 but not as frequently.

```
[exec]       > Could not resolve com.liferay:com.liferay.poshi.runner:1.0.232.
[exec]          > Could not get resource 'https://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/com.liferay.poshi.runner/1.0.232/com.liferay.poshi.runner-1.0.232.pom'.
[exec]             > Could not GET 'https://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/com.liferay.poshi.runner/1.0.232/com.liferay.poshi.runner-1.0.232.pom'.
[exec]                > repository-cdn.liferay.com: Name or service not known
```

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8ac542430f...c71edff724

**Pull request closed without merging**
