### PR TITLE
LPS-58330

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
cc @shuyangzhou

**Comment by shuyangzhou** [comment]
Awesome, thanks @hhuijser !

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7ae40fa3dc...3a44ff547d

**Comment by shuyangzhou** [comment]
@hhuijser I have tried this after Brian merged it in, for me both the format-source and format-source-local-changes are taking about 44sec on a clean repo, format-source-local-changes is not any faster than format-source, that does not seem right.

And I tried to commit in a SF issue, then run format-source-local-changes, it is still picking up the committed issue. Seems something went wrong about the local changes selecting logic.

**Comment by hhuijser** [comment]
I'll look into that tomorrow. For me it took only a couple of seconds and did in fact ignore the other files.

**Comment by hhuijser** [comment]
@shuyangzhou, guess it's windows vs Linux thing. Will have one of the guys in my team test tomorrow on their machine.

**Comment by hhuijser** [comment]
Hey @brianchandotcom @shuyangzhou @Ithildir 

So, this is interesting.

After an "ant all" I experience the same thing as Shuyang: both ant format-source and ant format-source-local-changes seem to SF all files.

However, after I do the following (without making any changes to SF), ant format-source-local-changes does work properly and ignores files that were not added/modified.

1. In modules/util/source-formatter: ..\..\..\gradlew install -Psnapshot
2. Change in gradle.properties to "com.liferay.source.formatter.version=1.0.50-SNAPSHOT"
3. ant setup-sdk

Shuyang, can you double check that this works for you as well?

Thanks

**Comment by shuyangzhou** [comment]
@hhuijser Yes, with your steps, the "format-source-local-changes" returns in about 2s on clean repo which is awesome!

@brianchandotcom I think we have a broken out of date publish for SF jar, can you republish it?

**Comment by brianchandotcom** [comment]
I *think* I just fixed the publish etc.

Please try again. Thx.

**Pull request closed without merging**
