### PR TITLE
LPS-81238 Adds Westeros fragment editor css only if the theme is available

### PR DESCRIPTION
**Pull request by jbalsas**
See `7.1.x` PR -> https://github.com/brianchandotcom/liferay-portal-ee/pull/20896

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7d69747697...ec1135bfa0

**Comment by brianchandotcom** [comment]
@jbalsas the name *top-head-dynamic-include seems a bit heavy handed. It's not bad, considering this is all this module does. I'm taking it as is but noting that I would have preferred a different more generic name.

@ealonso fyi.

Also, for your backport to 7.1.x, you need to change project dependencies (where possible) to artifacts. See 46e5b89 and 19a452c and 48f89da in 7.1.x only.

**Comment by brianchandotcom** [comment]
@jbalsas one argument is.. couldn't this just have been shoved into the site-initializer?

**Pull request closed without merging**
