### PR TITLE
LPS-56784 SF

### PR DESCRIPTION
**Pull request by topolik**

### CODE REVIEW

**Comment by topolik** [comment]
Wrong LPS ticket in description, closing.

**Comment by topolik** [comment]
Whops, I was wrong, it's correct :)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/21eacc1b89...b45373541a

**Comment by brianchandotcom** [comment]
@topolik please see my changes in upstream. Thx.

**Pull request closed without merging**
