### PR TITLE
LPS-58899

### PR DESCRIPTION
**Pull request by matethurzo**
cc @juliocamarero and @zoltantakacs for backporting

### CODE REVIEW

**Comment by ZoltanTakacs** [comment]
When it gets merged to master, I'll backport it to 7.0.x.

Thank you

**Comment by matethurzo** [comment]
ci:retest

**Comment by ZoltanTakacs** [comment]
As per the discussion with @jhendley this fix did not make the cut for the Alpha release.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/82f07ce93b...f21b5d51c3

**Pull request closed without merging**
