### PR TITLE
LPS-120846 Additional updates to the bundle localizations for the renamed LES apps | master

### PR DESCRIPTION
**Pull request by joshchong**
https://issues.liferay.com/browse/LPS-120846

This PR adds a few changes on top of https://github.com/brianchandotcom/liferay-portal/pull/95661

Manually forwarding since ci:forward failed to pass here: https://github.com/liferay-search/liferay-portal/pull/51#issuecomment-723010331

**Unique test failure analysis**: 
Search#NavigateToSearchResultsViaURL - Failed due to a bug that has just been fixed in [LPS-123169](https://issues.liferay.com/browse/LPS-123169)
SearchRequestBuilderTest.testAddPostFilterQueryPartAdditive - Flaky test failure that is being addressed here: [LPS-123052](https://issues.liferay.com/browse/LPS-123052)

7.3.x PR: https://github.com/brianchandotcom/liferay-portal-ee/pull/32202
7.2.x PR: https://github.com/brianchandotcom/liferay-portal-ee/pull/32205

cc @lipusz

### CODE REVIEW

**Comment by joshchong** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/75fd64746f...c0d7f3e4e3

**Comment by lipusz** [comment]
lbm:backport

**Comment by lipusz** [comment]
@joshchong Testing lbm:backport with this PR. The guys have recently [updated](https://issues.liferay.com/browse/LBM-1067) it to support 7.3.x. If it works, let's go with this so you don't need to send a PR for 7.3.x.

/cc @adambalazs-lr fyi

**Comment by lipusz** [comment]
@joshchong We ran into some issues with LBM, so I think it's faster if you just submit a PR to Brian for 7.3.x manually. Thanks!

**Comment by joshchong** [comment]
@lipusz the 7.3.x PR was sent here: https://github.com/brianchandotcom/liferay-portal-ee/pull/32202

**Pull request closed without merging**
