### PR TITLE
LPS-193386 Create Integration tests for Object Validation Rules Registry

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://liferay.atlassian.net/browse/LPS-193386

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:reopen

**Comment by mateussgn** [comment]
Resent based on [this comment](https://github.com/brianchandotcom/liferay-portal/pull/139912#issuecomment-1698028235).

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/be53fea63b...deff76670f

**Comment by brianchandotcom** [comment]
@mateussgn see deff76670f226fc969ebaa7236d5df6ac0497284

**Comment by mateussgn** [comment]
Thanks, Brian!

**Pull request closed without merging**
