### PR TITLE
Database Support: remove comercial databases from the CE code

### PR DESCRIPTION
**Pull request by migue**
@mdelapenya Could you make me a pull on the EE repo readding this properties, please

### CODE REVIEW

**Comment by mdelapenya** [comment]
test fixed in upstream

**Comment by brianchandotcom** [comment]
@mdelapenya no need to send it to ee-7.0.x. We're keeping the lang and portal.properties similar. Only new modules are in EE only.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8b2238bdef...e4d957b5e8

**Comment by brianchandotcom** [comment]
@mdelapenya i.e. I did a partial merge of your pull and didn't merge in the removal commits.

**Comment by mdelapenya** [comment]
Thanks Brian!

**Pull request closed without merging**
