### PR TITLE
Lps 70968

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @preston-crary

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

Those aborted nodes has never ran anything, what is going on @pyoo47 ?

**Comment by pyoo47** [comment]
@shuyangzhou rsync seems to be failing sporadically between slaves. I'll talk to Sam to see if there's anything going on with the network.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
