### PR TITLE
LPS-165519 Instead of removing the InfoItemReference after iterate the collection, restore the previous one

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-165519

@lfbesada

### CODE REVIEW

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See [liferay-echo#7560](https://github.com/liferay-echo/liferay-portal/pull/10196)

:heavy_check_mark: ci:test:stable - 28 out of 28 jobs passed
:x: ci:test:relevant - 203 out of 208 jobs passed in 3 hours 47 minutes

**Comment by ozysouza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a53de5e6be...5092addbc4

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5092addbc4...ce5474fd1b

**Comment by brianchandotcom** [comment]
@lfbesada see ce5474fd1b9bb851067c3c98c88ac263e3f02f04

**Pull request closed without merging**
