### PR TITLE
LPS-66439 DDL Web Content field not showing selected Web Content

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@tomwang2011

See :apps:collaboration:wiki:wiki-test:compileTestIntegrationJava

**Comment by tomwang2011** [comment]
@brianchandotcom 

wiki-test is using wiki-web-2.0.0 after https://github.com/liferay/liferay-portal/commit/b70cc79e0c0258e2fb1d26a512857688463a78c1 and the imported class has been moved into internal, I will send a pull to export that class and correct the import.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
