### PR TITLE
LPS-91364 Rename preferences and settings parameters of npm-extended portlets to configuration

### PR DESCRIPTION
**Pull request by izaera**
/CC @jbalsas

### CODE REVIEW

**Comment by izaera** [comment]
ci:test

**Comment by izaera** [comment]
@brianchandotcom I doubt that the CI errors are related to the PR given what it does and where the errors appear. However I have launched a full CI test to compare both results.

Don't know if that is the best way to differentiate it... :thinking:

**Comment by vicnate5** [comment]
@izaera took a look. Functional failures here are not related to this pull.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/333080b266...b088e0cacf

**Comment by brianchandotcom** [comment]
@izaera @jbalsas see b088e0c

**Pull request closed without merging**
