### PR TITLE
LPS-69208 Allow administrators to configure File Uploads using System Settings, allowing export and import of configurations

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-69208](https://issues.liferay.com/browse/LPS-69208).<br><br>/cc @pei-jung, @jorgeferrer, @alee8888

### CODE REVIEW

**Comment by drewbrokke** [comment]
Resent as https://github.com/brianchandotcom/liferay-portal/pull/50687.

**Comment by pyoo47** [comment]
ci:stop (This test is frozen)

**Pull request closed without merging**
