### PR TITLE
LPS-84523 Inmediately initialize the component

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Fix https://github.com/brianchandotcom/liferay-portal/pull/62196#issuecomment-413681630

### CODE REVIEW

**Comment by jpince** [comment]
@sergiogonzalez thanks!

**Comment by jpince** [comment]
@sergiogonzalez there's still a buildWSDD failure, this is also reproducible after your original pull. Can you please resolve this tomorrow?
```
     [exec] :apps:sharing:sharing-document-library:assemble
     [exec] Note: /opt/dev/projects/github/liferay-portal/modules/apps/sharing/sharing-service/src/main/java/com/liferay/sharing/service/persistence/impl/SharingEntryPersistenceImpl.java uses unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec]   java.lang.NoClassDefFoundError: javax/portlet/PortletResponse
```
https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/171313//consoleText
this is the WSDD batch that's failing in upstream:
https://test-1-21.liferay.com/job/test-portal-acceptance-upstream-batch(master)/AXIS_VARIABLE=0,label_exp=!master/21382/console

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by sergiogonzalez** [comment]
Hey @jpince this should fix it https://github.com/brianchandotcom/liferay-portal/pull/62212

**Pull request closed without merging**
