### PR TITLE
LPS-58846 Fix signature of method postProcessSearchQuery.

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5e349e980f...7f624c358a

**Comment by brianchandotcom** [comment]
@inacionery @leoadb do we need to do this to our other *Indexers as well?

**Comment by inacionery** [comment]
@brianchandotcom yes, but I did a search and this was the only one who had not yet been migrated.

**Comment by brianchandotcom** [comment]
@inacionery can you also search liferay-plugins master and liferay-plugins-ee ee-7.0.x? I have a feeling those may have been left out.

**Comment by inacionery** [comment]
@brianchandotcom yes, i can, if i find some will open an issue to fix.

**Comment by inacionery** [comment]
@brianchandotcom i created this https://github.com/leoadb/liferay-plugins/pull/1 to @leoadb and when integrated in master i'll do backport to ee.

**Pull request closed without merging**
