### PR TITLE
Lps 198716

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@MrJohn1911 see a3e89520a8fbf446615a08ad5b59ac3accd1168b

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c9389b532b...a061b884c6

**Comment by brianchandotcom** [comment]
@MrJohn1911 see 5a465e2d0fa88dc15544b9f13205842aa4586141 and a061b884c60f2318079265c1a7472c575cbd38dc

**Pull request closed without merging**
