### PR TITLE
LRQA-50040 | master

### PR DESCRIPTION
**Pull request by patriciajeanperez**
https://issues.liferay.com/browse/LRQA-50040

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by patriciajeanperez** [comment]
@sharry-xue

**Comment by patriciajeanperez** [comment]
@sharryxue Hi Sharry! It seems like tests would still fail because of missing success message. I couldn't reproduce it manually though. I will take a look when I get the chance!

**Comment by Sharryxue** [comment]
Hello @patriciajeanperez ,
Thanks for the heads up Patty, I've addressed the issue in LRQA-50276. We can tracking the issue on it.

**Pull request closed without merging**
