### PR TITLE
LPS-69383 Extract Captcha to OSGi module

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-69383](https://issues.liferay.com/browse/LPS-69383).

Hey Brian, this is part 1 a prerequisite pull extracting Captcha into a module (https://issues.liferay.com/browse/LPS-67830).

The only question I have is how to effectively deprecate CaptchaUtil (see e7147c9).  That commit is done to maintain backwards-compatibility, but ideally we want to create a class called CaptchaProvider to do what CaptchaUtil is now doing, since we are using it to retrieve service-tracked instances of Captcha.  That's on the roadmap for the next half, but is there an example of this kind of deprecation/transition?  Thanks!

/cc @pei-jung @jorgeferrer

### CODE REVIEW

**Comment by vicnate5** [comment]
The poshi test failed because 2 forms were created instead of 1 on the Form save. The test history shows this test needs to be re-run regularly because this happens on some runs. I am going to quarantine the test.

The failure is not related to this pull.

**Comment by drewbrokke** [comment]
ci:retest

**Comment by drewbrokke** [comment]
ci:retest

**Comment by jpince** [comment]
ci:retest

**Pull request closed without merging**
