### PR TITLE
LPS-61077 Don't use icon cog as default for icon menu tag

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/46223cde15...8b12e42020

**Comment by brianchandotcom** [comment]
@sharonchoi @brianchiu this calendar bug always happens this time of the day.

**Comment by vicnate5** [comment]
@brianchandotcom @brianchiu @alee8888 The test failure here looks like a one-off failure due to the user settings not loading, [test screenshot](https://test-1-17.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/463/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=PGCalendar%23ViewCalendarTimeZoneDefaults,label_exp=!master/functional-tomcat-mysql/4/index.html). Not sure it makes sense for us to write our tests around portal intermittently not loading user settings. This has been a reoccurring, though inconsistent, issue. See [LPS-59395](https://issues.liferay.com/browse/LPS-59395) and [LPS-57929](https://issues.liferay.com/browse/LPS-57929).

This failure has nothing to do with Calendar and the test that failed is not the same test that was regularly failing around 7-8pm at night (which was fixed by https://github.com/brianchandotcom/liferay-portal/pull/32975).

I don't see any other instances of calendar test failures at this time since the fix. I found another instance of this same test failing recently (https://github.com/brianchandotcom/liferay-portal/pull/33061), but this again was due to Users and Organizations failing to fully load user information.

**Comment by brianchiu** [comment]
@brianchandotcom 

I need to follow up with @shuyangzhou. This failure happened in the past, and Shuyang said that this failure is a bug and that he would look for a frontend dev to take care of it.

**Pull request closed without merging**
