### PR TITLE
LPS-90753 Regen

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Can you resend and rename

experiencesIds

to

segmentsExperiencesIds

I assume that experiencesId == segmentsExperiencesId

based on 

long[] experiencesIds = GetterUtil.getLongValues(request.getAttribute(SegmentsWebKeys.SEGMENTS_EXPERIENCE_IDS), new long[0]);

Thx

**Comment by ealonso** [comment]
cc: @darquesdev @epgarcia @andresfulla

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
Please, see #69032

**Pull request closed without merging**
