### PR TITLE
LRQA-28693 Replace mirrors-get macrodef with custom task.

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-28693

### CODE REVIEW

**Comment by pyoo47** [comment]
I found a small problem in the mirrors-get task. I'm closing this pull until after the fix has been merged to upstream and published.
https://github.com/brianchandotcom/liferay-portal/pull/44765

**Comment by pyoo47** [comment]
ci:retest

Fix has been merged to upstream and published.

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pyoo47 backported to ee-7.0.x and 7.0.x. Can you backport to ee-6.2.x? and ee-6.1.x? Thx.

**Pull request closed without merging**
