### PR TITLE
LPS-52978 Exclude mentions-editor-config module from automatic deployment for now because it needs the old mentions-portlet and that cannot be auto-deployed. (This partially reverts commit af61aa72d2000b1a91bb6247d72e8cde8e87c60d)

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
/CC @sergiogonzalez @zxdgoal 

See related conversation: https://github.com/zxdgoal/liferay-portal/pull/6#issuecomment-87569609

**Comment by zxdgoal** [comment]
@izaera

I believe you need to include the same changes in moudles/build.xml; Otherwise, your fix will not be applied by ant all.

Thanks
John

**Comment by izaera** [comment]
@zxdgoal I've done a push force to apply the change you mentioned. Thanks.

**Comment by kiyoshilee** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c7df47e376...05d780b235

**Pull request closed without merging**
