### PR TITLE
LPS-87269 Rename portletPreferences to preferences to honor Javascript API

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@izaera are these safe to merge? Lots of frontend broken.

@jpince please give insight.

**Comment by jpince** [comment]
@john-co please analyze, maybe just needs a retest after WEM merges their fix(es)

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@john-co @jpince please let me know whether this is clear to merge or not. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c030618de1...d585ddb03c

**Comment by brianchandotcom** [comment]
@izaera I just merged it. Tests looked good to me.

```
initializer(
					{
						configuration: settings,
						contextPath: '[$CONTEXT_PATH$]',
						portletElementId: '[$PORTLET_ELEMENT_ID$]',
						portletNamespace: '[$PORTLET_NAMESPACE$]',
						preferences: JSON.parse('[$PORTLET_PREFERENCES$]'),
						settings: settings
					});
```
We can't call preferences portletPreferences? Whose api is that? We can't change it?

**Comment by izaera** [comment]
@brianchandotcom 

> We can't call preferences portletPreferences? Whose api is that? We can't change it?

I read this, but it's unclear now if we can change it. Will tell you when it's decided :+1:

**Pull request closed without merging**
