### PR TITLE
LPS-69400

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-69400.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jonmak08 merged.

**Comment by brianchandotcom** [comment]
@jonmak08 I didn't merge this after all. The breaking change should be in 7.0. I'd like you to backport this pull. Thanks.

**Comment by jonmak08** [comment]
Hey @brianchandotcom,

We should be putting this into master/7.1.x since this is a deprecation for the next release.  Since 7.0.x is already released, we can backport this to 7.0.x as well, but shouldn't we just make this change for 7.1.x instead and if support needs, we can backport it to 7.0.x?

Can you please clarify your comments since I am a bit confused.  Thanks!

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/brianchandotcom/liferay-portal/pull/45750 

New Pull Request: https://github.com/brianchandotcom/liferay-portal-ee/pull/15542

**Pull request closed without merging**
