### PR TITLE
LPS-66252 Add schemaVersion header

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by adolfopa** [comment]
@brianchandotcom I had to put 2.0.1 in the header because that is the release number that people with a GA1 will have.

**Comment by pyoo47** [comment]
ci:retest There was a failure while communicating with the local git servers.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1d5e907411...bc90cb4fe6

**Pull request closed without merging**
