### PR TITLE
LPS-158690

### PR DESCRIPTION
**Pull request by patriciajeanperez**
Manual forward from https://github.com/liferay-usm/liferay-portal/pull/755

> https://issues.liferay.com/browse/LPS-158690
> 
> @drewbrokke @pei-jung, follow-up pull from https://github.com/liferay-usm/liferay-portal/pull/742 (this time, w/o the Language.properties file copies). Let me know if there's anything else I should change. Thanks!

We have the go-ahead from @david-truong and Corbin to add these

cc @brianwulbern

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6b3fd88191...64b0a64025

**Comment by brianchandotcom** [comment]
@patriciajeanperez @brianwulbern thanks team! Fitting that I'm merging this PR while in Spain...

Just 64b0a64025ff82aac121917ff4997be81ecd36fd

**Comment by brianwulbern** [comment]
Thanks @brianchandotcom!  I'll send the appropriate backport pulls for this, get it running on Crowdin, then let our UG know they can start using it.

**Comment by brianwulbern** [comment]
Follow-up pull to bump the versions so the language files will be created upon regen https://github.com/brianchandotcom/liferay-portal/pull/123932

**Pull request closed without merging**
