### PR TITLE
[PING] LPS-58563 create control-menu api. Same pattern as module application-list [PONG]

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7868931010...d25b96e2a5

**Comment by brianchandotcom** [comment]
Thx @juliocamarero I did this as soon as I saw it

**Pull request closed without merging**
