### PR TITLE
LPS-90079 Update alloy-editor to v2.0.0-alpha.2

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
@julien please fix SF error

**Comment by brianchandotcom** [comment]
@julien see 6e240e1a97c2d22d1fbcb38d7bc2fe1884bcd12b

**Comment by brianchandotcom** [comment]
@julien also, see f77e5d64201a595741a3e566e9c57bc202c0c2e4 thx

**Comment by julien** [comment]
@brianchandotcom @jpince thanks!

**Pull request closed without merging**
