### PR TITLE
LPS-98372 Revert "LPS-98372 LPS-100662 Temporarily remove from acceptance"

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Relevant tickets:
https://issues.liferay.com/browse/LPS-98372
https://issues.liferay.com/browse/LPS-100662

Reverting commit as requested: https://github.com/brianchandotcom/liferay-portal/pull/77750#issue-312775819

cc/ @jpince @leoadb @alexcandidos

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fc3aa629e2...720692b0ac

**Comment by brianchandotcom** [comment]
@rodrigopaulino I merged this, but it still looks wrong.

@brunofarache can you talk to Rodrigo, shouldn't we use [$TRUE$] and [$FALSE$] so it uses the right term per db?

**Comment by leoadb** [comment]
@brianchandotcom I'll help Rodrigo.

**Comment by rodrigopaulino** [comment]
> @rodrigopaulino I merged this, but it still looks wrong.
> 
> @brunofarache can you talk to Rodrigo, shouldn't we use [$TRUE$] and [$FALSE$] so it uses the right term per db?

@brianchandotcom thanks a lot for your comment and I understand your concerns, but I didn't send this before running the suggested test `ci:test:environments` (https://github.com/rodrigopaulino/liferay-portal/pull/20#issuecomment-527230773) and checking if this was causing upgrade processes to fail in different databases. Also I was under the impression that [Jason's comment](https://issues.liferay.com/browse/LPS-98372?focusedCommentId=1941561&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1941561) was only a suggestion as he told me to look for the correct solution on my own.

**Pull request closed without merging**
