### PR TITLE
LPS-70519 portal-kernel 2.11.0 apply

### PR DESCRIPTION
**Pull request by arboliveira**
2.11.0 should also be safe enough to cherry backport.

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@pyoo47 what's happening to modules-unit and these SSH keys?

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by pyoo47** [comment]
@brianchandotcom The issue that you're seeing is related to the git fetch bug. Sam's custom fetch script doesn't clear the known hosts file when git fetch freezes retries the fetch from liferay.github.com. On the next attempt, it's connecting to a different node than the one from the previous attempt. This causes the warning saying that the RSA host key has changed. It seems to be happening more frequently lately possibly due to the high load coming from hotfix tests. We could modify the custom fetch command to clear the known hosts file between retries but it wouldn't fix the real problem. The real problem is the fact that it tries to do the git fetch 3 times and it fails all three times so the build aborts.

**Pull request closed without merging**
