### PR TITLE
LPS-61508

### PR DESCRIPTION
**Pull request by natecavanaugh**

### CODE REVIEW

**Comment by brianchiu** [comment]
@brianchandotcom 
I believe the poshi failure (it's happening consistently in all pulls) is due to a portal bug. I'm confirming right now.

**Comment by brianchiu** [comment]
@brianchandotcom 
Alright yep. The Forms failure is happening due to a bug where the validation options for Forms is missing.

This is what it looks like on: http://master.liferay.org.es/

working

This is what it currently looks like at HEAD (1829d53091d017bcfe5f2385e3cf2979e75c4301)

broken

**Comment by brianchiu** [comment]
The cause is LPS-61303. Sent a pull to revert here:
https://github.com/brianchandotcom/liferay-portal/pull/34571

**Comment by thiago-rocha** [comment]
cc @brunobasto

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5915b08cef...121f06a0df

**Pull request closed without merging**
