### PR TITLE
master-lps-58504

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LPS-58504

This pull has both dev commits and qa test fixes.

@epgarcia @marcoscv-work

### CODE REVIEW

**Comment by kiyoshilee** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Nice job @epgarcia @marcoscv-work @brianchiu @brianwulbern  :)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/18f4ac8d14...c357a11611

**Pull request closed without merging**
