### PR TITLE
LPS-74544

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@juliocamarero

**Comment by juliocamarero** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@juliocamarero not merging.. this is ugly.

Class<?> clazz = new Class();

clazz.xyz...

We should not chain on this class. @hhuijser

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
@brianchandotcom, emailed you details on this one

**Comment by brianchandotcom** [comment]
@hhuijser I don't see an email?

**Comment by hhuijser** [comment]
```
Hey Brian,

Looks like my commit message was a bit confusing.

What that commit does is allow something like:

SearchQuery searchQuery = new NativeSearchQueryBuilder(
).withIndices(
    _indexName
).withQuery(
    queryBuilder
).withTypes(
    Individual.DOCUMENT_TYPE
).withPageable(
    new PageRequest(0, 1)
).build();

But... only for classNames that are specified in the checkstyle.xml as allowedClassNames: https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/checkstyle.xml#L91

So this code would be allowed, because NativeSearchQueryBuilder is in allowedClassNames.

This is not about chainging on the class Class

I reopened the pull.
```

**Comment by brianchandotcom** [comment]
Got it. My bad. Merging.

**Pull request closed without merging**
