### PR TITLE
LPS-80386 Merge UADAggregator into UADDisplay

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-80386](https://issues.liferay.com/browse/LPS-80386).<br><br>Hey Brian, this is a resend of https://github.com/brianchandotcom/liferay-portal/pull/57899 that fixes the rebase errors (per your comment here: https://github.com/brianchandotcom/liferay-portal/pull/57899#issuecomment-386189512)<br><br>/cc @pei-jung @willnewbury

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test

**Comment by drewbrokke** [comment]
ci:retest

**Comment by jpince** [comment]
@drewbrokke pushed https://github.com/liferay/liferay-portal-ee/commit/8dbfdfdca2c1a9b1887d81ec7786bdf60d11ec66 upstream but realized that CI needs [git-commit-portal-private](https://github.com/liferay/liferay-portal/blob/master/git-commit-portal-private) updated too and I don't have the time to update that as well. If you really need to test it, you can send a pull to yourself and add a temp commit referencing 8dbfdfdca2c1a9b1887d81ec7786bdf60d11ec66.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0b290fcffe...2c209436e4

**Pull request closed without merging**
