### PR TITLE
LPS-82022 Rename Adaptive Media

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@JorgeFerrer I"ll take care of this.

It's because the committer regenerated language files that conflict with what our paid translators are doing..

**Comment by brianchandotcom** [comment]
@JorgeFerrer @martamedio See bb49e6f906e54c724653fe2bb768a29ca7f732ac

Don't regenerate in the future because it'll conflict with our translation team.

@petershin can you regenerate for me? Since the translations were already pushed this morning. Thx.

**Comment by JorgeFerrer** [comment]
Got it, thanks for fixing it. 

I had already warned David that this would happen so that they can manage it with the paid translators (who will have to translate again)

**Comment by petershin** [comment]
@brianchandotcom - Yup, will send a pull

**Pull request closed without merging**
