### PR TITLE
LPS-89615 Update ComboServlet with .min.js and .min.css suffix

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/baa744bb15...82c157ca28

**Comment by brianchandotcom** [comment]
@NemethNorbert @jbalsas see my changes in upstream. Thx. backported just to 7.1.x. Please send me a pull for 7.0.x

**Comment by jbalsas** [comment]
Looks good, thanks @brianchandotcom!

**Comment by NemethNorbert** [comment]
https://github.com/liferay/liferay-portal-ee/pull/12345

**Pull request closed without merging**
