### PR TITLE
master-qa-18452

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LRQA-18452

@brianchandotcom 
This is a test that adds Juan's test parent portlet, clicks the execute button on it, and asserts the success message.

I wasn't sure if you wanted this in the PR tester as well. I've included a commit to put it there, but if you'd rather not have it in the PR tester you can just ignore the second commit.

CC @juangon @jhendley

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1e2966d289...c3fa900aaf

**Comment by brianchandotcom** [comment]
@brianchiu Eventually, I'd like to add more and more things to the PR tester. Is it part of smoke?

**Comment by brianchiu** [comment]
@brianchandotcom 
The test for Juan's portlets isn't part of main portal smoke. I wrote it as a separate test. So I added a property to toggle it so that it would run as part of the PR tester.

**Comment by juangon** [comment]
Thanks @brianchiu !

**Pull request closed without merging**
