### PR TITLE
LPS-78135 Provide API and Tag for clay:geomap

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test

**Comment by petershin** [comment]
Hi @julien!

The [source-format-jdk8](https://github.com/brianchandotcom/liferay-portal/pull/55557#issuecomment-367391921) Jenkins test failed because its trying to format geomap.geo.json

If you add a source-formatter.properties file to the [frontend-taglib](https://github.com/liferay/liferay-portal/tree/master/modules/apps/foundation/frontend-taglib) directory with the code below I think it'll fix the issue.

```
source.formatter.excludes=\
	modules/apps/foundation/frontend-taglib/frontend-taglib-chart-sample-web/src/main/resources/META-INF/resources/geomap.geo.json
```

**Comment by brianchandotcom** [comment]
@julien see https://github.com/julien/liferay-portal/pull/17

Please continue my changes.

Also, it's better not to add an SF exclude, but instead, format it properly.

**Comment by julien** [comment]
@brianchandotcom ok
thanks

**Pull request closed without merging**
