### PR TITLE
LPS-109406 Add cases to assert behaviors when switch Toggle Controls

### PR DESCRIPTION
**Pull request by manoelcyreno**

### CODE REVIEW

**Comment by manoelcyreno** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b3546db36f...ef81c93750

**Pull request closed without merging**
