### PR TITLE
LPS-82343

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:test

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:close

**Comment by jpince** [comment]
@hhuijser integration test errors look related to your change in https://github.com/brianchandotcom/liferay-portal/pull/60948/files#diff-f376d993e04301ce83a15edd786c349aR234. Can you please take a look?

cc/ @petershin

```
java.lang.NullPointerException
	at com.liferay.portal.kernel.util.PortalUtil.getResourceBundle(PortalUtil.java:1691)
	at com.liferay.portal.kernel.util.ResourceBundleUtil.getBundle(ResourceBundleUtil.java:122)
	at com.liferay.portal.kernel.util.ResourceBundleUtil.getBundle(ResourceBundleUtil.java:99)
	at com.liferay.portal.kernel.util.ResourceBundleUtil.getBundle(ResourceBundleUtil.java:92)
	at com.liferay.dynamic.data.mapping.form.evaluator.internal.DDMFormEvaluatorHelper.createResourceBundle(DDMFormEvaluatorHelper.java:234)
	at com.liferay.dynamic.data.mapping.form.evaluator.internal.DDMFormEvaluatorHelper.<init>(DDMFormEvaluatorHelper.java:105)
	at com.liferay.dynamic.data.mapping.form.evaluator.internal.DDMFormEvaluatorImpl.evaluate(DDMFormEvaluatorImpl.java:45)
	at com.liferay.dynamic.data.mapping.form.renderer.internal.DDMFormPagesTemplateContextFactory._createDDMFormEvaluationResult(DDMFormPagesTemplateContextFactory.java:346)
	at com.liferay.dynamic.data.mapping.form.renderer.internal.DDMFormPagesTemplateContextFactory.create(DDMFormPagesTemplateContextFactory.java:86)
	at com.liferay.dynamic.data.mapping.form.renderer.internal.DDMFormPagesTemplateContextFactoryTest.testExtractHTMLTagsFromCheckboxMultipleFieldTemplateContext(DDMFormPagesTemplateContextFactoryTest.java:203)
```

**Comment by hhuijser** [comment]
@jpince thanks for catching that. I did look at the test results, but I guess I missed that one.

**Pull request closed without merging**
