### PR TITLE
LPS-102791

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-102791.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0a37c30806...59526d063a

**Comment by brianchandotcom** [comment]
@jonmak08 please send a backport to support.

**Comment by jonmak08** [comment]
Will do @brianchandotcom.  Thanks!

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/liferay/liferay-portal-ee/pull/16604

**Pull request closed without merging**
