### PR TITLE
LPS-137127 | master

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://issues.liferay.com/browse/LPS-137127

master only, thx

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e4e81566e9...f81fd276b0

**Comment by brianchandotcom** [comment]
@JoyceWang08211 should be "specific" and not "specified"

Same for deploy-specified-plugins

Can you update those names? I think the grammar is off.

Talk to @brianwulbern to be sure. Thx.

**Comment by JoyceWang08211** [comment]
Thanks for the reminder. I'll fix the grammar issue for master and all the other legacy branches under 
https://issues.liferay.com/browse/LPS-137192

@brianchandotcom  and @brianwulbern

**Pull request closed without merging**
