### PR TITLE
LPS-78213

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test

**Comment by pyoo47** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6aa36cce06...486fb6731a

**Comment by brianchandotcom** [comment]
@matethurzo please see my changes in 486fb6731ab87862f2ceb4692f4ac3c21856bb17

thx

**Pull request closed without merging**
