### PR TITLE
LPS-90281 Uses clay button

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
cc: @brianchiu @kyle-miho

**Comment by brianchiu** [comment]
This pull is good to go.

For the 2 "unique" failures:
1) The upgrade failure is the same failure that happens sporadically in upstream.
2) The unresolved requirement doesn't seem to be related to this pull.
```
     [exec] 11:22:07,798 ERROR [Framework Event Dispatcher: Equinox Container: 99e0066b-b1dd-4bbe-bb07-6e7a7417bce5][com_liferay_headless_collaboration_impl:97] FrameworkEvent ERROR 
     [exec] org.osgi.framework.BundleException: Could not resolve module: com.liferay.headless.collaboration.impl [657]
     [exec]   Unresolved requirement: Import-Package: com.liferay.oauth2.provider.scope; version="[1.0.0,2.0.0)"
     [exec] 
     [exec] 	at org.eclipse.osgi.container.Module.start(Module.java:444)
     [exec] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1682)
     [exec] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1662)
     [exec] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1624)
     [exec] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1555)
     [exec] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
     [exec] 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
     [exec] 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
     [exec] 11:22:07,800 ERROR [Framework Event Dispatcher: Equinox Container: 99e0066b-b1dd-4bbe-bb07-6e7a7417bce5][com_liferay_headless_collaboration_impl:112] Exiting the JVM 
     [exec] org.osgi.framework.BundleException: Could not resolve module: com.liferay.headless.collaboration.impl [657]
     [exec]   Unresolved requirement: Import-Package: com.liferay.oauth2.provider.scope; version="[1.0.0,2.0.0)"
     [exec] 
     [exec] 	at org.eclipse.osgi.container.Module.start(Module.java:444)
     [exec] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1682)
     [exec] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1662)
     [exec] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1624)
     [exec] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1555)
     [exec] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
     [exec] 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
     [exec] 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
```

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7d6753328d...2f29e57b58

**Comment by kyle-miho** [comment]
ci:test

**Pull request closed without merging**
