### PR TITLE
Lps 81861 7

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by kzhang-dsg** [comment]
Hi @shuyangzhou and @brianchandotcom,

A quick question: What is the purpose of the following code in `PortletRequestImpl.java`? It is causing issues in JSF portlets because `null` and `empty string` are treated differently in JSF ACE libraries. Technically `null` and `empty string` are different. Why does Liferay set empty string as null value in the code below, and just for the portlet 3.0?

```
			if ((values != null) && (portletSpecMajorVersion == 3)) {
				for (int i = 0; i < values.length; i++) {
					if ((values[i] != null) && values[i].isEmpty()) {
						values[i] = null;
					}
				}
			}
```

**Comment by brianchandotcom** [comment]
@ngriffin7a can you chime in? Thx.

**Comment by ngriffin7a** [comment]
@kzhang-dsg This code was added to fulfill a new requirement in Portlet 3.0. If my memory is correct, it is associated with requirements in the new `javax.portlet.PortletParameters` interface:
https://docs.liferay.com/portlet-api/3.0/javadocs/javax/portlet/PortletParameters.html
Specifically, I think the code might be associated with the `PortletParameters.getValue(String)` method Javadoc:
> Note that `null` is a valid parameter value. To determine whether a parameter is present, use the `Set.contains(Object)` method on the set returned by `getNames()`.

This should only be an issue if an ICEfaces portlet has opted-in to Portlet 3.0:
https://help.liferay.com/hc/en-us/articles/360044149512-Portlet-3-0-API-Opt-In

**Comment by kzhang-dsg** [comment]
Hi @ngriffin7a,

Thanks a lot for the clarification!

I looked into the JSR-362 specification and found the reference:

image

I may be wrong but here is my thought for your consideration. Apologize if it does not make sense to you.

1. By reading the JSR-362 specification, to me it looks like the `null` value is more like a note for the `MutablePortletParameters.setValue(null)`. Stating that `Setting a parameter value to null does not remove the parameter`. It is not meant for converting the empty string value as a `null` value.
2. For the current implementation, It is inconsistent between the PortletRequest and HttpServletRequest for treating the parameters with empty strings. It may lead to confusion and unexpected bugs.
3. If the logic is not for a specific issue, but just to comply with (maybe ambiguous) specifications, is there a chance that we can re-think this logic and keep the parameters as is? In other words, keep the empty string as an empty string since it does not break anything but brings in more consistently?  

Thanks!

**Comment by ngriffin7a** [comment]
@kzhang-dsg Apologies for taking so long to get back to you. Thank you for taking the time to conduct your analysis -- it is indeed correct. I have documented the bug in [LPS-133689](https://issues.liferay.com/browse/LPS-133689) and am currently testing a fix that I plan to submit for review to @shuyangzhou early next week. Kind Regards, Neil

**Comment by ngriffin7a** [comment]
@kzhang-dsg FYI: The fix for this issue has been merged:
https://github.com/brianchandotcom/liferay-portal/pull/103140#issuecomment-860334944

**Pull request closed without merging**
