### PR TITLE
LPD-19497 the friendly url must return a value for the default language not the site default language

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
sent from https://github.com/liferay-content-management/liferay-portal/pull/5198 

- **LPD-19497 when adding the journal article on the test allow to set the default language**
- **LPD-19497 add test to check that the site default language is not generated if the default language is different on the creation of the**
- **LPD-19497 the default locale should be the one that not can be null**
- **LPD-19497 autoSF**
- **LPD-19497 restore the original Site Default Locale on the test**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:open

**Comment by jkappler** [comment]
ci:reopen

**Comment by jkappler** [comment]
Test failures are not related to the changes. Force forward is not working because of baseline issues in commerce/kernel

**Comment by brianchandotcom** [comment]
@AliciaGarciaGarcia see 0cf957e44149e4de71d7be23abd6e8b21070c4de

**Pull request closed without merging**
