### PR TITLE
LPS-162830 Support automatic registration of ConfigurationBeanDeclaration services

### PR DESCRIPTION
**Pull request by patriciajeanperez**
Manual forward from https://github.com/liferay-usm/liferay-portal/pull/830

> This is an update for [LPS-162830](https://issues.liferay.com/browse/LPS-162830).
> 
> tl;dr: You do not have to create `ConfigurationBeanDeclaration` classes anymore. Just write your `*Configuration.java` class and it will automatically work with `ConfigurationProvider`.
> 
> This removes `ConfigurationBeanDeclaration` from `liferay-portal`.
> 
> It has been replaced by a `BundleTracker` that will check each bundle as it is registered for Metatype information. If found, it will attempt to load each configuration class using the bundle's classloader. Any loaded classes that do not contain the proper annotations (`Meta.OCD` and `Meta.AD` with `required = false`) will be ignored. Otherwise, the relevant `ManagedService` and `ManagedServiceFactory` services will be registered.
> 
> On bundle deactivation, the services will be un-registered.
> 

cc @drewbrokke

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0adc8b0008...ae84854dfd

**Comment by brianchandotcom** [comment]
Very nice @drewbrokke ! See ae84854dfdcbd7122d648b7b0b1abfd8d56f3402

@ling-alan-huang can you SF enforce 4dea8423

**Comment by drewbrokke** [comment]
@brianchandotcom we shouldn't need to SF enforce it because the class is gone, so the code wouldn't compile anyways.

**Comment by brianchandotcom** [comment]
@ling-alan-huang my bad about the SF!

**Pull request closed without merging**
