### PR TITLE
LRCI-382 & LRCI-226 Rename docker classes & add resource monitor

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRCI-382
https://issues.liferay.com/browse/LRCI-226

Please publish after merging

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
Resting due to temporary internet outage

**Comment by pyoo47** [comment]
Found one more change that needs to be made.. I will resend.

**Comment by pyoo47** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
already published,  see 7f56fc1053d38ec04185001dcd07557bb6c7b253 and 530eefd68f1d2ffc794891910079c375f621e291

**Pull request closed without merging**
