### PR TITLE
LPS-62597

### PR DESCRIPTION
**Pull request by natecavanaugh**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@fernandosouza @natecavanaugh @brunobasto broken poshi, Please resend. Thx.

**Comment by brunobasto** [comment]
@vicnate5 can this be due to button label changing from "Save" to "Add"?

**Comment by vicnate5** [comment]
@brunobasto Yep. The failures are due to the button change. Should be a quick fix. We can take care of this and resend.

**Comment by brunobasto** [comment]
Thanks!

**Comment by ctampoya** [comment]
@natecavanaugh @brunobasto @vicnate5 making test fix in https://issues.liferay.com/browse/LRQA-22557

**Comment by vicnate5** [comment]
Resent https://github.com/brianchandotcom/liferay-portal/pull/36618

**Pull request closed without merging**
