### PR TITLE
LPS-67510 regen

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @pavel-savinov @adolfopa

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by jpince** [comment]
@sergiogonzalez thanks for fixing the SF issue https://github.com/liferay/liferay-portal/commit/5128d9d761859a4b8bd992cde8f5db018586b48e

@ithildir does Sergio's SF fix need to be backported?

**Comment by Ithildir** [comment]
Hi @jpince,
I think `7.0.x` is already okay, when I sent the pull yesterday there were no failures.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
