### PR TITLE
LPS-55859 Simplify

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by shinnlok** [comment]
@sergiogonzalez ,

If we go with your route, do you think we should leave undo the rename of RepositoryModelNameComparator for backwards compatibility?

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8a169da51b...af1608461f

**Pull request closed without merging**
