### PR TITLE
LPS-104604 - Result Rankings: Change several protected methods into private

### PR DESCRIPTION
**Pull request by thektan**
http://issues.liferay.com/browse/LPS-104604

✔️ ci:test:sf - 1 out of 1 jobs passed in 2 minutes 16 seconds 506 ms
❌ ci:test:search - 46 out of 51 jobs passed in 1 hour 12 minutes 45 seconds 352 ms

No related failures.

@oliv-yu

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d34f044e5b...d72c5acf75

**Comment by brianchandotcom** [comment]
See d72c5acf7584a28ae1a2602950de962130758a90

**Comment by brianchandotcom** [comment]
@oliv-yu see d72c5acf7584a28ae1a2602950de962130758a90 thx

**Comment by oliv-yu** [comment]
lbm:backport

**Pull request closed without merging**
