### PR TITLE
[Method References 2] LPS-165273 convert method reference to ServiceTrackerMap in module portal-security-audit-router

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6112cb146e...e0f3354ed6

**Comment by brianchandotcom** [comment]
@JanisZhang @W2jx @dantewang see 2e1381f9732e18b04de4b7dc3a469e54e197217d

**Comment by brianchandotcom** [comment]
@JanisZhang @W2jx If there are more like https://github.com/brianchandotcom/liferay-portal/commit/2e1381f9732e18b04de4b7dc3a469e54e197217d that you remember, please fix them manually. Thx.

**Pull request closed without merging**
