### PR TITLE
LPS-119068 Fix Page Audit and enable it

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
Hi @brianchandotcom,

This fixes the weird issue we experienced last week with a blank page. See https://github.com/brianchandotcom/liferay-portal/pull/101252/commits/28c7f0e840c5a0d5e9e9da97527c231144ac3ffe. (It was cause by the refactor to use the StringBundler).

We had an almost clean CI run but some weird DNS issue occurred. We've decided to send it directly to you.

Thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/dc838e427f...5e2c7b1a05

**Comment by brianchandotcom** [comment]
Wow @4lejandrito my bad about the StringBundler change!

See tiny change in 23fbff67c5d5eb64292b86cff8f0953a9a8da8e0

**Pull request closed without merging**
