### PR TITLE
LPS-68934 buildLang

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by marcellustavares** [comment]
@brianchandotcom, I've just renamed the portlet title on this pull.

Thanks

**Comment by jpince** [comment]
@brianchandotcom looks ok from a functional test perspective. The weblogic and upgrade failures are known issues that we're working to resolve.

**Comment by brianchandotcom** [comment]
@marcellustavares why is it only breaking on this pull? My other pulls are all green. Can you resend? Every time I hit retest on this pull, something breaks. Not happening anywhere else.

@pyoo47 could this be a Git caching issue?

**Comment by pyoo47** [comment]
@brianchandotcom I'm not seeing any git caching issues here. I have seen this failure during portal startup in a couple of places.. This issue appears to be intermittent within this pull.

CC: @marcellustavares 

```
    [junit] java.lang.IllegalStateException: Wrong current transaction manager. Current session factory classes metadata: {com.liferay.portal.model.impl.BrowserTrackerImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.BrowserTrackerImpl), com.liferay.portal.model.impl.UserNotificationDeliveryImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.UserNotificationDeliveryImpl), com.liferay.portal.model.impl.LayoutBranchImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.LayoutBranchImpl), com.liferay.portal.model.impl.ResourceTypePermissionImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.ResourceTypePermissionImpl), com.liferay.portal.model.impl.PortletImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.PortletImpl), com.liferay.portlet.messageboards.model.impl.MBMessageImpl=SingleTableEntityPersister(com.liferay.portlet.messageboards.model.impl.MBMessageImpl), com.liferay.portal.model.impl.LayoutSetImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.LayoutSetImpl), com.liferay.portlet.announcements.model.impl.AnnouncementsEntryImpl=SingleTableEntityPersister(com.liferay.portlet.announcements.model.impl.AnnouncementsEntryImpl), com.liferay.portlet.asset.model.impl.AssetVocabularyImpl=SingleTableEntityPersister(com.liferay.portlet.asset.model.impl.AssetVocabularyImpl), com.liferay.portlet.trash.model.impl.TrashVersionImpl=SingleTableEntityPersister(com.liferay.portlet.trash.model.impl.TrashVersionImpl), com.liferay.portlet.messageboards.model.impl.MBDiscussionImpl=SingleTableEntityPersister(com.liferay.portlet.messageboards.model.impl.MBDiscussionImpl), com.liferay.portal.model.impl.ServiceComponentImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.ServiceComponentImpl), com.liferay.portlet.asset.model.impl.AssetCategoryPropertyImpl=SingleTableEntityPersister(com.liferay.portlet.asset.model.impl.AssetCategoryPropertyImpl), com.liferay.portlet.asset.model.impl.AssetTagImpl=SingleTableEntityPersister(com.liferay.portlet.asset.model.impl.AssetTagImpl), com.liferay.portlet.messageboards.model.impl.MBThreadImpl=SingleTableEntityPersister(com.liferay.portlet.messageboards.model.impl.MBThreadImpl), com.liferay.portlet.social.model.impl.SocialActivityImpl=SingleTableEntityPersister(com.liferay.portlet.social.model.impl.SocialActivityImpl), com.liferay.portal.model.impl.PortletItemImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.PortletItemImpl), com.liferay.portal.model.impl.GroupImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.GroupImpl), com.liferay.portlet.ratings.model.impl.RatingsStatsImpl=SingleTableEntityPersister(com.liferay.portlet.ratings.model.impl.RatingsStatsImpl), com.liferay.portlet.asset.model.impl.AssetCategoryImpl=SingleTableEntityPersister(com.liferay.portlet.asset.model.impl.AssetCategoryImpl), com.liferay.portlet.announcements.model.impl.AnnouncementsDeliveryImpl=SingleTableEntityPersister(com.liferay.portlet.announcements.model.impl.AnnouncementsDeliveryImpl), com.liferay.portal.model.impl.TeamImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.TeamImpl), com.liferay.portlet.social.model.impl.SocialRelationImpl=SingleTableEntityPersister(com.liferay.portlet.social.model.impl.SocialRelationImpl), com.liferay.portlet.documentlibrary.model.impl.DLFolderImpl=SingleTableEntityPersister(com.liferay.portlet.documentlibrary.model.impl.DLFolderImpl), com.liferay.portal.model.impl.WorkflowDefinitionLinkImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.WorkflowDefinitionLinkImpl), com.liferay.portal.model.impl.MembershipRequestImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.MembershipRequestImpl), com.liferay.portlet.social.model.impl.SocialRequestImpl=SingleTableEntityPersister(com.liferay.portlet.social.model.impl.SocialRequestImpl), com.liferay.portal.model.impl.CountryImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.CountryImpl), com.liferay.portal.model.impl.LayoutSetBranchImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.LayoutSetBranchImpl), com.liferay.portal.model.impl.ContactImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.ContactImpl), com.liferay.portal.model.impl.UserGroupGroupRoleImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.UserGroupGroupRoleImpl), com.liferay.portal.model.impl.WorkflowInstanceLinkImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.WorkflowInstanceLinkImpl), com.liferay.portlet.documentlibrary.model.impl.DLFileVersionImpl=SingleTableEntityPersister(com.liferay.portlet.documentlibrary.model.impl.DLFileVersionImpl), com.liferay.portal.model.impl.ReleaseImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.ReleaseImpl), com.liferay.portal.model.impl.ResourcePermissionImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.ResourcePermissionImpl), com.liferay.portal.model.impl.TicketImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.TicketImpl), com.liferay.portal.model.impl.PortalPreferencesImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.PortalPreferencesImpl), com.liferay.portlet.expando.model.impl.ExpandoRowImpl=SingleTableEntityPersister(com.liferay.portlet.expando.model.impl.ExpandoRowImpl), com.liferay.portlet.blogs.model.impl.BlogsEntryImpl=SingleTableEntityPersister(com.liferay.portlet.blogs.model.impl.BlogsEntryImpl), com.liferay.portal.model.impl.PasswordPolicyRelImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.PasswordPolicyRelImpl), com.liferay.portal.model.impl.UserTrackerPathImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.UserTrackerPathImpl), com.liferay.portlet.ratings.model.impl.RatingsEntryImpl=SingleTableEntityPersister(com.liferay.portlet.ratings.model.impl.RatingsEntryImpl), com.liferay.portlet.documentlibrary.model.impl.DLSyncEventImpl=SingleTableEntityPersister(com.liferay.portlet.documentlibrary.model.impl.DLSyncEventImpl), com.liferay.portlet.messageboards.model.impl.MBThreadFlagImpl=SingleTableEntityPersister(com.liferay.portlet.messageboards.model.impl.MBThreadFlagImpl), com.liferay.portal.model.impl.ImageImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.ImageImpl), com.liferay.portlet.blogs.model.impl.BlogsStatsUserImpl=SingleTableEntityPersister(com.liferay.portlet.blogs.model.impl.BlogsStatsUserImpl), com.liferay.portlet.announcements.model.impl.AnnouncementsFlagImpl=SingleTableEntityPersister(com.liferay.portlet.announcements.model.impl.AnnouncementsFlagImpl), com.liferay.portlet.documentlibrary.model.impl.DLFileEntryTypeImpl=SingleTableEntityPersister(com.liferay.portlet.documentlibrary.model.impl.DLFileEntryTypeImpl), com.liferay.portal.model.impl.RepositoryImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.RepositoryImpl), com.liferay.portlet.asset.model.impl.AssetLinkImpl=SingleTableEntityPersister(com.liferay.portlet.asset.model.impl.AssetLinkImpl), com.liferay.portal.model.impl.RoleImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.RoleImpl), com.liferay.portal.model.impl.VirtualHostImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.VirtualHostImpl), com.liferay.portal.model.impl.LayoutPrototypeImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.LayoutPrototypeImpl), com.liferay.portal.model.impl.UserTrackerImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.UserTrackerImpl), com.liferay.portlet.asset.model.impl.AssetTagStatsImpl=SingleTableEntityPersister(com.liferay.portlet.asset.model.impl.AssetTagStatsImpl), com.liferay.document.library.kernel.model.DLContentDataBlobModel=SingleTableEntityPersister(com.liferay.document.library.kernel.model.DLContentDataBlobModel), com.liferay.portal.model.impl.AccountImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.AccountImpl), com.liferay.portal.model.impl.LayoutImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.LayoutImpl), com.liferay.portlet.social.model.impl.SocialActivityCounterImpl=SingleTableEntityPersister(com.liferay.portlet.social.model.impl.SocialActivityCounterImpl), com.liferay.portal.model.impl.RepositoryEntryImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.RepositoryEntryImpl), com.liferay.portal.model.impl.ListTypeImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.ListTypeImpl), com.liferay.portal.model.impl.LayoutFriendlyURLImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.LayoutFriendlyURLImpl), com.liferay.portal.model.impl.AddressImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.AddressImpl), com.liferay.portal.model.impl.OrgLaborImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.OrgLaborImpl), com.liferay.portal.model.impl.OrgGroupRoleImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.OrgGroupRoleImpl), com.liferay.portlet.social.model.impl.SocialActivityAchievementImpl=SingleTableEntityPersister(com.liferay.portlet.social.model.impl.SocialActivityAchievementImpl), com.liferay.portlet.social.model.impl.SocialActivitySettingImpl=SingleTableEntityPersister(com.liferay.portlet.social.model.impl.SocialActivitySettingImpl), com.liferay.portlet.expando.model.impl.ExpandoValueImpl=SingleTableEntityPersister(com.liferay.portlet.expando.model.impl.ExpandoValueImpl), com.liferay.portal.model.impl.WebDAVPropsImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.WebDAVPropsImpl), com.liferay.portlet.trash.model.impl.TrashEntryImpl=SingleTableEntityPersister(com.liferay.portlet.trash.model.impl.TrashEntryImpl), com.liferay.portlet.documentlibrary.model.impl.DLContentImpl=SingleTableEntityPersister(com.liferay.portlet.documentlibrary.model.impl.DLContentImpl), com.liferay.counter.model.impl.CounterImpl=SingleTableEntityPersister(com.liferay.counter.model.impl.CounterImpl), com.liferay.portlet.documentlibrary.model.impl.DLFileRankImpl=SingleTableEntityPersister(com.liferay.portlet.documentlibrary.model.impl.DLFileRankImpl), com.liferay.portal.model.impl.PortletPreferencesImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.PortletPreferencesImpl), com.liferay.portal.model.impl.LayoutSetPrototypeImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.LayoutSetPrototypeImpl), com.liferay.portal.model.impl.SubscriptionImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.SubscriptionImpl), com.liferay.portal.model.impl.SystemEventImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.SystemEventImpl), com.liferay.portal.model.impl.PluginSettingImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.PluginSettingImpl), com.liferay.portal.model.impl.UserGroupRoleImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.UserGroupRoleImpl), com.liferay.portal.model.impl.ResourceActionImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.ResourceActionImpl), com.liferay.portlet.messageboards.model.impl.MBBanImpl=SingleTableEntityPersister(com.liferay.portlet.messageboards.model.impl.MBBanImpl), com.liferay.portal.model.impl.UserImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.UserImpl), com.liferay.portlet.expando.model.impl.ExpandoColumnImpl=SingleTableEntityPersister(com.liferay.portlet.expando.model.impl.ExpandoColumnImpl), com.liferay.portal.model.impl.RecentLayoutRevisionImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.RecentLayoutRevisionImpl), com.liferay.portlet.documentlibrary.model.impl.DLFileShortcutImpl=SingleTableEntityPersister(com.liferay.portlet.documentlibrary.model.impl.DLFileShortcutImpl), com.liferay.portal.model.impl.UserGroupImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.UserGroupImpl), com.liferay.portlet.asset.model.impl.AssetEntryImpl=SingleTableEntityPersister(com.liferay.portlet.asset.model.impl.AssetEntryImpl), com.liferay.portal.model.impl.ClassNameImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.ClassNameImpl), com.liferay.portlet.messageboards.model.impl.MBMailingListImpl=SingleTableEntityPersister(com.liferay.portlet.messageboards.model.impl.MBMailingListImpl), com.liferay.portlet.documentlibrary.model.impl.DLFileEntryMetadataImpl=SingleTableEntityPersister(com.liferay.portlet.documentlibrary.model.impl.DLFileEntryMetadataImpl), com.liferay.portal.model.impl.ResourceBlockImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.ResourceBlockImpl), com.liferay.portal.model.impl.PasswordPolicyImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.PasswordPolicyImpl), com.liferay.portal.model.impl.PhoneImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.PhoneImpl), com.liferay.portlet.messageboards.model.impl.MBCategoryImpl=SingleTableEntityPersister(com.liferay.portlet.messageboards.model.impl.MBCategoryImpl), com.liferay.portlet.expando.model.impl.ExpandoTableImpl=SingleTableEntityPersister(com.liferay.portlet.expando.model.impl.ExpandoTableImpl), com.liferay.portal.model.impl.ResourceBlockPermissionImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.ResourceBlockPermissionImpl), com.liferay.portal.model.impl.UserNotificationEventImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.UserNotificationEventImpl), com.liferay.portlet.social.model.impl.SocialActivitySetImpl=SingleTableEntityPersister(com.liferay.portlet.social.model.impl.SocialActivitySetImpl), com.liferay.portal.model.impl.CompanyImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.CompanyImpl), com.liferay.portlet.messageboards.model.impl.MBStatsUserImpl=SingleTableEntityPersister(com.liferay.portlet.messageboards.model.impl.MBStatsUserImpl), com.liferay.portlet.exportimport.model.impl.ExportImportConfigurationImpl=SingleTableEntityPersister(com.liferay.portlet.exportimport.model.impl.ExportImportConfigurationImpl), com.liferay.portal.model.impl.OrganizationImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.OrganizationImpl), com.liferay.portal.model.impl.ClusterGroupImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.ClusterGroupImpl), com.liferay.portal.model.impl.EmailAddressImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.EmailAddressImpl), com.liferay.portlet.documentlibrary.model.impl.DLFileEntryImpl=SingleTableEntityPersister(com.liferay.portlet.documentlibrary.model.impl.DLFileEntryImpl), com.liferay.portal.model.impl.LayoutRevisionImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.LayoutRevisionImpl), com.liferay.portal.model.impl.PasswordTrackerImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.PasswordTrackerImpl), com.liferay.portal.model.impl.RecentLayoutBranchImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.RecentLayoutBranchImpl), com.liferay.portal.model.impl.RecentLayoutSetBranchImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.RecentLayoutSetBranchImpl), com.liferay.portal.model.impl.RegionImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.RegionImpl), com.liferay.portal.model.impl.UserIdMapperImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.UserIdMapperImpl), com.liferay.portal.model.impl.WebsiteImpl=SingleTableEntityPersister(com.liferay.portal.model.impl.WebsiteImpl), com.liferay.portlet.social.model.impl.SocialActivityLimitImpl=SingleTableEntityPersister(com.liferay.portlet.social.model.impl.SocialActivityLimitImpl)}, target session factory classes metadata: {com.liferay.dynamic.data.mapping.model.impl.DDMDataProviderInstanceLinkImpl=SingleTableEntityPersister(com.liferay.dynamic.data.mapping.model.impl.DDMDataProviderInstanceLinkImpl), com.liferay.dynamic.data.mapping.model.impl.DDMStructureImpl=SingleTableEntityPersister(com.liferay.dynamic.data.mapping.model.impl.DDMStructureImpl), com.liferay.dynamic.data.mapping.model.impl.DDMDataProviderInstanceImpl=SingleTableEntityPersister(com.liferay.dynamic.data.mapping.model.impl.DDMDataProviderInstanceImpl), com.liferay.dynamic.data.mapping.model.impl.DDMTemplateLinkImpl=SingleTableEntityPersister(com.liferay.dynamic.data.mapping.model.impl.DDMTemplateLinkImpl), com.liferay.dynamic.data.mapping.model.impl.DDMStorageLinkImpl=SingleTableEntityPersister(com.liferay.dynamic.data.mapping.model.impl.DDMStorageLinkImpl), com.liferay.dynamic.data.mapping.model.impl.DDMTemplateImpl=SingleTableEntityPersister(com.liferay.dynamic.data.mapping.model.impl.DDMTemplateImpl), com.liferay.dynamic.data.mapping.model.impl.DDMStructureLayoutImpl=SingleTableEntityPersister(com.liferay.dynamic.data.mapping.model.impl.DDMStructureLayoutImpl), com.liferay.dynamic.data.mapping.model.impl.DDMTemplateVersionImpl=SingleTableEntityPersister(com.liferay.dynamic.data.mapping.model.impl.DDMTemplateVersionImpl), com.liferay.dynamic.data.mapping.model.impl.DDMStructureLinkImpl=SingleTableEntityPersister(com.liferay.dynamic.data.mapping.model.impl.DDMStructureLinkImpl), com.liferay.dynamic.data.mapping.model.impl.DDMContentImpl=SingleTableEntityPersister(com.liferay.dynamic.data.mapping.model.impl.DDMContentImpl), com.liferay.dynamic.data.mapping.model.impl.DDMStructureVersionImpl=SingleTableEntityPersister(com.liferay.dynamic.data.mapping.model.impl.DDMStructureVersionImpl)}
    [junit] 	at com.liferay.portal.dao.orm.hibernate.VerifySessionFactoryWrapper._assertFailure(VerifySessionFactoryWrapper.java:93)
    [junit] 	at com.liferay.portal.dao.orm.hibernate.VerifySessionFactoryWrapper._verify(VerifySessionFactoryWrapper.java:122)
    [junit] 	at com.liferay.portal.dao.orm.hibernate.VerifySessionFactoryWrapper.openSession(VerifySessionFactoryWrapper.java:75)
    [junit] 	at com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl.openSession(BasePersistenceImpl.java:252)
    [junit] 	at com.liferay.dynamic.data.mapping.service.persistence.impl.DDMStructurePersistenceImpl.fetchByUUID_G(DDMStructurePersistenceImpl.java:755)
    [junit] 	at com.liferay.dynamic.data.mapping.service.persistence.impl.DDMStructurePersistenceImpl.fetchByUUID_G(DDMStructurePersistenceImpl.java:697)
    [junit] 	at com.liferay.dynamic.data.mapping.service.persistence.DDMStructureUtil.fetchByUUID_G(DDMStructureUtil.java:289)
    [junit] 	at com.liferay.asset.publisher.web.internal.exportimport.portlet.preferences.processor.AssetPublisherExportImportPortletPreferencesProcessor.getImportPortletPreferencesNewValue(AssetPublisherExportImportPortletPreferencesProcessor.java:434)
    [junit] 	at com.liferay.exportimport.portlet.preferences.processor.base.BaseExportImportPortletPreferencesProcessor.updateImportPortletPreferencesClassPKs(BaseExportImportPortletPreferencesProcessor.java:131)
    [junit] 	at com.liferay.asset.publisher.web.internal.exportimport.portlet.preferences.processor.AssetPublisherExportImportPortletPreferencesProcessor.updateImportPortletPreferences(AssetPublisherExportImportPortletPreferencesProcessor.java:934)
    [junit] 	at com.liferay.asset.publisher.web.internal.exportimport.portlet.preferences.processor.AssetPublisherExportImportPortletPreferencesProcessor.processImportPortletPreferences(AssetPublisherExportImportPortletPreferencesProcessor.java:149)
    [junit] 	at com.liferay.exportimport.controller.PortletImportController.importPortletPreferences(PortletImportController.java:964)
    [junit] 	at com.liferay.exportimport.controller.LayoutImportController.doImportFile(LayoutImportController.java:806)
    [junit] 	at com.liferay.exportimport.controller.LayoutImportController.importFile(LayoutImportController.java:225)
    [junit] 	at com.liferay.portlet.exportimport.service.impl.ExportImportLocalServiceImpl.importLayouts(ExportImportLocalServiceImpl.java:185)
    [junit] 	at com.liferay.portlet.exportimport.service.impl.ExportImportLocalServiceImpl.importLayouts(ExportImportLocalServiceImpl.java:217)
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    [junit] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit] 	at java.lang.reflect.Method.invoke(Method.java:497)
```

**Comment by marcellustavares** [comment]
resent to https://github.com/brianchandotcom/liferay-portal/pull/44411

**Pull request closed without merging**
