### PR TITLE
LPS-89896 Implements vertical cards for select site roles

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:relevant

@brianchiu @kyle-miho

**Comment by brianchiu** [comment]
ci:close

**Comment by brianchiu** [comment]
Going to close for now until we see the results. I'm pretty sure we need to update the tests along with this pull.

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
Need to update the tests for Site.assignSiteRoleCP

**Comment by brianchiu** [comment]
@ealonso 
Pull sent to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/67935

**Pull request closed without merging**
