### PR TITLE
LPS-65305 Escaping character U+2028

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @topolik

**Comment by juliocamarero** [comment]
ci:retest

**Comment by topolik** [comment]
Thanks Julio for cc, it looks fine :)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7968ef3e30...8936ef5c07

**Pull request closed without merging**
