### PR TITLE
LRQA-71406 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/LRQA-71406

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:reopen

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/214ee2e68b...17d7f542ce

**Pull request closed without merging**
