### PR TITLE
Lps 102243 2

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@ChiZelin 

MBUserNotificationTest.testAddUserNotificationWhenEmailNotificationsDisabled

Please resend.

**Comment by brianchandotcom** [comment]
@shuyangzhou fyi test failure.

**Comment by shuyangzhou** [comment]
ci:reopen

@brianchandotcom Those failures already happen in upstream, see https://test-1-18.liferay.com/job/test-portal-acceptance-upstream-batch(master)/19693/AXIS_VARIABLE=21,label_exp=!master/testReport/com.liferay.message.boards.notifications.test/MBUserNotificationTest/testAddUserNotificationWhenEmailNotificationsDisabled/ for example.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/db015b1e63...f602b83ec1

**Comment by vicnate5** [comment]
@adolfopa is working on the MB test failures under https://issues.liferay.com/browse/LPS-106362

**Pull request closed without merging**
