### PR TITLE
LPS-59726

### PR DESCRIPTION
**Pull request by natecavanaugh**

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3cba58931e...cd018677fe

**Comment by brianchandotcom** [comment]
@brunobasto see f22cf0ef29410738682d0793ef3560976e406747

**Comment by brunobasto** [comment]
Sorry, @brianchandotcom. :/

**Pull request closed without merging**
