### PR TITLE
LPS-84236 A user without UPDATE permission can navigate to the edit view for a password policy

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-84236](https://issues.liferay.com/browse/LPS-84236).<br><br>/cc @pei-jung @stsquared99

### CODE REVIEW

**Comment by drewbrokke** [comment]
@brianchandotcom please wait for the functional tests to finish.

**Comment by drewbrokke** [comment]
@alee8888 if there are functional test failures can you please take a look at what changes we'll need to make?  Thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/712daf910b...1f134cee29

**Comment by brianchandotcom** [comment]
@drewbrokke see 1f134cee29515d50beb0857b842d84e8e31c446b

**Pull request closed without merging**
