### PR TITLE
LPS-92920 Update alloy-editor to v2.0.0-beta.6

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test

**Comment by julien** [comment]
ci:reopen

**Comment by jpince** [comment]
@john-co @michaelhashimoto @yichenroy is this flakiness or a real error? Just two batches failed for this, but it's the exact same failure, so that's concerning for me...
```
     [exec] > Task :setUpYarn
     [exec] yarn install v1.13.0
     [exec] [1/4] Resolving packages...
     [exec] [2/4] Fetching packages...
     [exec] info There appears to be trouble with your network connection. Retrying...
     [exec] info There appears to be trouble with your network connection. Retrying...
     [exec] info There appears to be trouble with your network connection. Retrying...
     [exec] info There appears to be trouble with your network connection. Retrying...
     [exec] error An unexpected error occurred: "https://registry.yarnpkg.com/alloyeditor/-/alloyeditor-2.0.0-beta.6.tgz: tunneling socket could not be established, cause=connect ECONNREFUSED 172.16.171.31:3128".
     [exec] info If you think this is a bug, please open a bug report with the information provided in "/opt/dev/projects/github/liferay-portal/modules/yarn-error.log".
```

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@jbalsas @petershin we need to turn the cache on.

**Comment by jbalsas** [comment]
Hey @brianchandotcom, we do have the cache turned on since late last week... whenever a change in the `yarn.lock` file is committed, the cache should be regenerated. Otherwise, we run the `setup-yarn` target with the `--ofline` argument forcing yarn to just use what's in the cache.

@jpince, could you point me to the other PRs where it failed?

**Comment by jpince** [comment]
@jbalsas I've only seen it in this pull. Other pulls sent after this was merged seem to be fine.

**Comment by jpince** [comment]
@jbalsas I was referring to the two batches that failed in ci:test:relevant in _this pull_, lpkg-base-jdk8 and unit-jdk8

**Comment by jbalsas** [comment]
Hey @petershin, I think we might be hitting yarn registry directly when we should be configuring our own proxy server... ping me when you get back from PTO to look into this!

Thanks!

**Pull request closed without merging**
