### PR TITLE
LPS-75257 Increase OSGi version numbers

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@sergiogonzalez @adolfopa see DLApp test failures. I see them randomly in a lot of pulls. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2f9c7eace2...76d52ce3f1

**Comment by brianchandotcom** [comment]
@izaera see 76d52ce3f1d4c1eaac9302ed688b03532f5711fc

**Pull request closed without merging**
