### PR TITLE
LPS-96376 Update to liferay-npm-scripts v2.1.0 (prettier)

### PR DESCRIPTION
**Pull request by wincent**
We've now updated liferay-npm-scripts to use Prettier (https://prettier.io/) for JS source formatting. This commit updates our dependency and runs `yarn format` on every project that has a "package.json" file, as well as from the top level "modules/" folder to cover everything else.

I used [this Bash](https://gist.github.com/wincent/6eb84ca6e5f7185eb8049e4bd04805f7) script to find all the package.json files that have a "liferay-npm-scripts format" key, and run `yarn format` from those places, verifying that they work if run independently.

Note that because "modules/" has such a package.json file, this means that I effectively confirmed that formatted everything from the top-level as works as well.

I had to add a three "npmscripts.config.js" files to locations where we either don't have any JS source files (and therefore have to instruct Prettier to not run), or where we need to pass a special glob (this is the case at "modules/" because we want to format everything, even JS that may not have a corresponding "package.json" file, but we want to exclude stuff under "classes/"). Includes a `.prettierrc.js` config file which should be picked up by most people's editors. This merely exposes the definitive config from liferay-npm-scripts.

I deleted some malformed files that were test fixtures and which Prettier would otherwise reject; these actually became unreferenced in 8e62321471f6b7d373 anyway:

- modules/apps/frontend-js/frontend-js-loader-modules-extender/src/test/resources/com/liferay/frontend/js/loader/modules/extender/internal/dependencies/config1.js
- modules/apps/frontend-js/frontend-js-loader-modules-extender/src/test/resources/com/liferay/frontend/js/loader/modules/extender/internal/dependencies/config2.js
- modules/apps/frontend-js/frontend-js-loader-modules-extender/src/test/resources/com/liferay/frontend/js/loader/modules/extender/internal/dependencies/empty.js
- modules/apps/frontend-js/frontend-js-loader-modules-extender/src/test/resources/com/liferay/frontend/js/loader/modules/extender/internal/dependencies/malformed.js

I also removed non-standard ESLint config from a couple of places (segments-web and analytics-client-js). All of this is going to go through liferay-npm-scripts, where we will configure it in such a way that it leaves the formatting-related aspects to prettier and only deals with non-presentational code issues.

### CODE REVIEW

**Comment by wincent** [comment]
Just sent this as #74029 but it got closed due to touch a "pull-only" dir (modules/test/poshi-runner), so I backed out the changes to that. However, it's dying again with the same failure. @john-co: any idea why that might be? I'll resubmit if I can figure out why that's happening.

In any case, John, as this is a pretty big change I'd appreciate your help with any other failures that crop up. When I tested it locally (https://github.com/wincent/liferay-portal/pull/27) the SF test had some failures which I think are unrelated (in `build.gradle` files, none of which I touched). Doing some manual QA, everything in the portal seems to work great.

cc @jbalsas

**Comment by wincent** [comment]
On the suspicion that this might be closed because the first commit touches that path (even though the second one reverts the change), I squashed the two commits together and resubmitted here: https://github.com/brianchandotcom/liferay-portal/pull/74033

**Comment by yichenroy** [comment]
Hi @wincent,
your suspicion is correct, the validation lists modified files for each commit in the pull request so even if the commit is reverted it is still being treated as if it was changed.

cc  @john-co

**Comment by wincent** [comment]
Thanks for confirming @yichenroy. That makes sense.

**Pull request closed without merging**
