### PR TITLE
LPS-55065

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@Preston-Crary test failures. Please resend.

**Comment by Preston-Crary** [comment]
@brianchandotcom these are the same test failures in other pulls this morning, see https://github.com/brianchandotcom/liferay-portal/pull/30897

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/304d98c1b7...33a0e3afe4

**Comment by brianchandotcom** [comment]
@natecavanaugh can you check out the CSS changes in this pull? Thx. I pushed it to upstream.

**Pull request closed without merging**
