### PR TITLE
LPS-90529 Improve experience of selecting custom field input type

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @stsquared99 @alee8888

### CODE REVIEW

**Comment by alee8888** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
You have

ExpandoColumn column

and

ExpandoColumn expandoColumn

in the same JSP.. very weird. Please resend.

fyi @drewbrokke @stsquared99 @alee8888

**Comment by brianchandotcom** [comment]
Also, change it to "Text and Numbers"

**Comment by pei-jung** [comment]
Resent as https://github.com/brianchandotcom/liferay-portal/pull/69915

**Pull request closed without merging**
