### PR TITLE
LPS-64522 Return whatever locale exists if the default returns nothing

### PR DESCRIPTION
**Pull request by javiergamarra**
The information in the form fields could be stored in a different locale than the default of the form or the fields (for example with a portal with default locale pt_BR and form locale en_US).

In the case that the field has something stored but it's not the mobile locale or the field locale we want to return whatever value is stored.

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:retest

**Comment by nhpatt** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f788175296...963af58639

**Comment by brianchandotcom** [comment]
@nhpatt thanks for the forward port.

**Pull request closed without merging**
