### PR TITLE
LPS-56791 As a developer I would like inherit resourceBundle from defineTag

### PR DESCRIPTION
**Pull request by peterfellwock**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/039dde2fbb...cfa02fe81d

**Comment by brianchandotcom** [comment]
@robertodiaz @sergiogonzalez

Hey guys, @peterfellwock told me that when he added "resourceBundle" to defineObjects, that it actually picked up the right class loader from the module. He said he tested it and it works.

See upstream. Thx.

**Comment by robertoDiaz** [comment]
Eso estoy haciendo

Eso es justamente lo mismo que hice yo y no me funciono

**Comment by peterfellwock** [comment]
Lo confirme con el item selector de blogs. Con tal que el themeDisplay que
se pasa al DisplayTag es el del bundle debe funcionar. Donde no funciona y
yo investigo?

**Comment by robertoDiaz** [comment]
I doesn't seem to work for me

just put this line  in this jsp (blogs attachments.jsp)

<%= LanguageUtil.get(resourceBundle, "there-are-no-blog-attachments") %>

and the key appears like this:

there-are-no-blog-attachments

**Comment by robertoDiaz** [comment]
The problem i found was that the method getBundle:

 public static final ResourceBundle getBundle(String baseName,
                                                 Locale locale)
    {
        return getBundleImpl(baseName, locale,
                             /* must determine loader here, else we break stack invariant */
                             getLoader(Reflection.getCallerClass()),
                             Control.INSTANCE);
    }

gets the loader of the caller class. If we call it from the jsp the caller class is in the bundle classloader.

If we call it from DefineObjectsTag the caller is in the portal and the classloader is wrong

Can you check if I am missing something?

**Pull request closed without merging**
