### PR TITLE
LPS-661610 Fix User Admin 'sites' section to be able to work with no selected user

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by sharonchoi** [comment]
Tags tests are failing due to bug: https://issues.liferay.com/browse/LPS-66724

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:stop

**Comment by lipusz** [comment]
Hi Pei-Jung,

Can you please rebase and push your branch so might be able to pass CI?

Thanks,
Tibor

@pei-jung

**Comment by pei-jung** [comment]
rebased and updated branch
ci:retest

**Comment by jpince** [comment]
Smoke failure is due to a known issue, no functional test failures.

**Comment by michaelhashimoto** [comment]
<h4>Known Random Failures:</h4>
<ul>
<li>This <a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=1,label_exp=!master/13279/">failure</a> seems to be due to this server randomly disconnecting</li>
<li>This <a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=1,label_exp=!master/13279/">failure</a> seems to be due to this server randomly disconnecting</li>
</ul>

<h4>Failed Unit/Integration Tests:</h4>
<ul>
<li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=4,label_exp=!master/13285/testReport/com.liferay.portal.dao.orm/SQLNullTest/testBlankStringNotEqualsNull/">SQLNullTest.testBlankStringNotEqualsNull</a></li>
<li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/15040/testReport/com.liferay.portal.format/InternationalPhoneNumberFormatImplTest/testInvalidPhoneNumbers/">InternationalPhoneNumberFormatImplTest.testInvalidPhoneNumbers</a></li>
</ul>

I'm unsure if these are important though..

**Comment by lipusz** [comment]
These failures are unrelated and cannot be caused by LPS-66160.

**Comment by lipusz** [comment]
Hi Brian,

How should we proceed with this pull? These failures occur on other pulls also.

@brianchandotcom

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a565860357...b3efb5ded0

**Pull request closed without merging**
