### PR TITLE
LPS-93452 Autogenerated

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@victorg1991 you're not setting "viewableBy" in the resourceimpl, that's weird no?

**Comment by victorg1991** [comment]
@brianchandotcom It's a writeonly property, we use it only at creation time

**Pull request closed without merging**
