### PR TITLE
LPS-138282 Add a method to build a Filter from a filterString in every Resource

### PR DESCRIPTION
**Pull request by javierdearcos**

### CODE REVIEW

**Comment by javierdearcos** [comment]
ci:reopen

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by javierdearcos** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@javierdearcos 
```
	protected ExpressionConvert<Filter> expressionConvert;
	protected FilterParserProvider filterParserProvider;
```

Won't those be NPEs?

How are you setting those?

Plese resend. Thx @javierdearcos

**Pull request closed without merging**
