### PR TITLE
LPS-68909 gradlew buildLang

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brandizzi** [comment]
@tsubasahomma it is related to [that other PR of yours](https://github.com/brandizzi/liferay-portal/pull/409). You may want to backport it as well if you got some customer complaints about date presentation in Japanese.

**Comment by tsubasahomma** [comment]
Hi @brandizzi, I've already sent pr for the backport on https://github.com/dustinryerson/liferay-portal-ee/pull/2967. Is there anything I should do for the backport?

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brandizzi** [comment]
Hey @tsubasahomma! Brian Suh asked me for some more changes over that others. I applied them in this PR. If the other fix is enough for your situation, that is ok, but I imagine you would like to include these other fixes (from the commits above) as well.

**Comment by tsubasahomma** [comment]
Hi @brandizzi, this PR looks good to me because my commit is only for Language_ja.properties. Thank you for confirming :D

**Pull request closed without merging**
