### PR TITLE
LPS-55166 plugins dependency pull request

### PR DESCRIPTION
**Pull request by rotty3000**
Nice work @mjbradford89!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c217558433...b72926e83d

**Pull request closed without merging**
