### PR TITLE
LPS-192060 Rename layoutReportsTabsURL and segmentExperienceSelectorData

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://liferay.atlassian.net/browse/LPS-192060

@veroglez

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/13252

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/85d34e7b3c...0aabafba21

**Comment by brianchandotcom** [comment]
@Mikellorza see 0aabafba217aaacee7e7b9f62c30bf8529955b95

**Pull request closed without merging**
