### PR TITLE
LPS-77201 Apply new clay:navigation-bar to site-my-sites-web

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by anthony-chu** [comment]
@ealonso i'll take a look at this pull. it looks like there will be some poshi changes that need to be made for the nav-bar and search fields. thanks!

**Comment by anthony-chu** [comment]
ci:close

**Comment by ealonso** [comment]
@anthony-chu, Thanks you very much!!

**Comment by anthony-chu** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/54556

**Pull request closed without merging**
