### PR TITLE
LPS-69400 removing unnecessary file

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Please resend as

```
<liferay-expando:custom-attribute-list
```

Rename modules/apps/foundation/expando/expando-custom-field-ui-taglib

to

modules/apps/foundation/expando/expando-taglib

Unless we're planning to have a lot of expando taglibs, let's keep it simple.

Thx. @linolaoj

**Comment by linolaoj** [comment]
Here it is https://github.com/brianchandotcom/liferay-portal/pull/45418.
Thanks!

**Pull request closed without merging**
