### PR TITLE
LPS-65786 servicereferences need a type

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
FYI, I've actually run through the WSRP tutorial as well on dev.liferay.com and everything worked.

**Comment by shuyangzhou** [comment]
@rotty3000 overall this looks good, it covers everything we talked about, thanks!
Just a few detail questions.
1) See https://github.com/brianchandotcom/liferay-portal/pull/44606/commits/a8c3fbbc63735e0dffa21c6cae6c87eb9ac39674#diff-28e3cf259d89b86f287fb1efd5d889dfR103
If I read the DS 1.3 spec right, isn't the singleton default value when not specifying scope?
From the spec:
```
If not specified (and the deprecated servicefactory() element is not specified), the singleton service
scope is used. If the factory() element is specified or the immediate() element is specified with true,
this element can only be specified with the singleton service scope.
```
2) For the all the IllegalStateException catches in ServletContextHelperRegistrationImpl.close(), when will they really happen? 

https://github.com/brianchandotcom/liferay-portal/pull/44606/commits/a8c3fbbc63735e0dffa21c6cae6c87eb9ac39674#diff-8d1d42a9c98af739de7a8b8eb8e5bde3R116

I thought it would only happen when you unregister an already unregistered registration, right? If that's the case, they are never supposed to happen as we guard all the registration references as internal usage, an IllegalStateException could be a sign to show someone modified the code in an unexpected way. If so I think we should bubble up the exception rather than swallowing them, or at least do an error log as someone should really take a look at it. What do you think?

**Comment by rotty3000** [comment]
Done!

**Comment by rotty3000** [comment]
This is how proper collaboration is support to take place. It takes more time but it's worth the effort! We both would have provided a wrong solution since neither of us realized that the ConsumerPortlet was not even needed by the service and so the circular dependency was a superficial problem. We only achieved this together! Let's please keep working in this manner from now on.

**Comment by rotty3000** [comment]
ci:stop

**Comment by rotty3000** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
Thanks @rotty3000 !

**Comment by brianchandotcom** [comment]
Great job @rotty3000 AND @shuyangzhou ... team work :)

**Comment by brianchandotcom** [comment]
@rotty3000 this is good.. I'll be merging it soon.

**Comment by brianchandotcom** [comment]
@rotty3000 Merged. See upstream for my tiny changes. Thx Ray!

@peterfellwock  see upstream. fyi.

**Pull request closed without merging**
