### PR TITLE
LPS-89423 Rename

### PR DESCRIPTION
**Pull request by epgarcia**
@darquesdev @andresfulla

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
Hey @brianchandotcom, those keys are automatically generated from the field name (e.g. languageId -> language-id). Initially we translated them accordingly (e.g. language-id=Language ID) but now that we have more friendly inputs (drop-downs, selectors) we also wanted more friendly names (e.g. Language instead of Language ID). However, I agree this can be confusing for translators. I'll add a namespace to these keys so that their function is more clear. Let me send you a follow up PR later today with it. Thanks!

**Pull request closed without merging**
