### PR TITLE
LPS-68423

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-68423.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@jonmak08 can you send this to Preston? I thought he was using a compat jar to do this now for deprecated taglibs? Thx.

**Comment by jonmak08** [comment]
Ok will do.  Thanks!

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/Preston-Crary/liferay-portal/pull/264

**Pull request closed without merging**
