### PR TITLE
LPS-179146 Add ability to send email notifications when web content expires

### PR DESCRIPTION
**Pull request by alessandromalves**
This is only for master
https://issues.liferay.com/browse/LPS-179146
cc.: @jkappler

### CODE REVIEW

**Comment by alessandromalves** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/11494

:heavy_check_mark: ci:test:stable - 27 out of 27 jobs passed
:x: ci:test:relevant - 148 out of 201 jobs passed in 2 hours 57 minutes

**Comment by alessandromalves** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c9721b1a1a...794a6c3f9e

**Comment by brianchandotcom** [comment]
@alessandromalves 6cfc9bc3

**Pull request closed without merging**
