### PR TITLE
LPS-56692

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@brianchandotcom let me know when you've pushed up snapshots for these jars

**Comment by david-truong** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by david-truong** [comment]
ci:retest

**Comment by david-truong** [comment]
ci:retest

**Comment by david-truong** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@david-truong where are these samples coming from? It's very weird to me we're duplicating so much test data. Ideally, we should be grabbing them from somewhere (like we do the other tests). And at the very least, between 2 modules with the same data, have one copy it from the other on compile. Too much duplicate code here.

**Pull request closed without merging**
