### PR TITLE
Upgrades: Fix some issues in UpgradeKernelPackages

### PR DESCRIPTION
**Pull request by cgoncas**
/cc @migue

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2da583763d...64858408ab

**Comment by brianchandotcom** [comment]
@cgoncas can you send a follow up pull:

I want to avoid confusion for when ordering matters in upgrades. For example, in BookmarksServiceUpgrade,

```
			new UpgradeClassNames(), new UpgradePortletId(),
			new UpgradeLastPublishDate(),
			new UpgradePortletSettings(_settingsFactory));
```

I only happen to know that UpgradePortletId has to go before UpgradeLastPublishDate because it's out of order. But if UpgradePortletId wasn't in the list

```
			new UpgradeClassNames(),
			new UpgradeLastPublishDate(),
			new UpgradePortletSettings(_settingsFactory));
```

There's no way I would know that UpgradeClassNames also has to go before everything else.

So I want to propose a new rule.

Anytime something cannot be ordered.. you break it up

So it should be

```

		registry.register(
			"com.liferay.bookmarks.service", "0.0.1", "1.0.0",
			new UpgradeClassNames());

		registry.register(
			"com.liferay.bookmarks.service", "0.0.1", "1.0.0",
			new UpgradePortletId());

		registry.register(
			"com.liferay.bookmarks.service", "0.0.1", "1.0.0",
			new UpgradeLastPublishDate(),
			new UpgradePortletSettings(_settingsFactory));
```

This assumes that UpgradePortletId has to run after UpgradeClassNames. If not, you can group them together. Also, for the numbers.. I didn't change them, you would have to increment them.

See CalendarServiceUpgrade

```
		registry.register(
			"com.liferay.calendar.service", "1.0.2", "1.0.3",
			new UpgradeClassNames(),
			new UpgradeCalendarResource(
				_classNameLocalService, _companyLocalService,
				_userLocalService),
```

There are a lot like this.

Can you go through and send me a subsequent pull? You don't have to do them all in one day. Just do whatever you can and then send it to me (since they are per module anyways). But I'd like this done by Tuesday next week if you can latest.

Thank you @cgoncas

**Pull request closed without merging**
