### PR TITLE
LPS-72155 Show Site Selector when there are recent sites to select

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@ithildir is this a cache issue?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2838ebdc5c...dd83dadf92

**Comment by Ithildir** [comment]
I'll check, maybe there's a problem with the Squid proxy.

**Pull request closed without merging**
