### PR TITLE
LPS-58126

### PR DESCRIPTION
**Pull request by shinnlok**
@Preston-Crary,

It looks like you are trying to clean things up and this isn't related to your ticket. Are you actually fixing anything with this?

The parameters that you are removing are being depended on by JSONWebServiceActionParameters#_collectFromRequestParameters.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/234d1cb839...0dc86746f4

**Comment by brianchandotcom** [comment]
@Preston-Crary please write a test if you want to enforce this change. Thx.

**Comment by brianchandotcom** [comment]
@shinnlok may be you can update an existing json test to ensure preston doesn't do this too. Thx.

**Comment by Preston-Crary** [comment]
@shinnlok 
I was fixing something with that. I remember it had to do with form submissions causing exceptions but not the exact steps.

**Pull request closed without merging**
