### PR TITLE
LPS-57981

### PR DESCRIPTION
**Pull request by LeventeHudak**

### CODE REVIEW

**Comment by pyoo47** [comment]
Looks like one of the Jenkins jobs is completely missing from Jenkins. I'll work with Hashi to see if we can figure out what happened to it.

```
[beanshell] Downloading http://test-1-20/job/test-portal-acceptance-pullrequest-batch%28master%29/11533//api/json
[beanshell] Retry in 5 seconds
[beanshell] Downloading http://test-1-20/job/test-portal-acceptance-pullrequest-batch%28master%29/11533//api/json
[beanshell] Retry in 5 seconds
[beanshell] Downloading http://test-1-20/job/test-portal-acceptance-pullrequest-batch%28master%29/11533//api/json
[beanshell] Retry in 5 seconds
[beanshell] Downloading http://test-1-20/job/test-portal-acceptance-pullrequest-batch%28master%29/11533//api/json

BUILD FAILED
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-test-portal-acceptance-pullrequest.xml:284: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:3083: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:2515: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:2529: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:2414: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:438: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:650: Sourced file: inline evaluation of: `` 				 					import com.liferay.jenkins.results.parser.JenkinsResultsParserUtil;   . . . '' : Typed variable declaration : Method Invocation JenkinsResultsParserUtil.toJSONObject : at Line: 103 : in file: inline evaluation of: `` 				 					import com.liferay.jenkins.results.parser.JenkinsResultsParserUtil;   . . . '' : JenkinsResultsParserUtil .toJSONObject ( JenkinsResultsParserUtil .getLocalURL ( jenkinsJobURL + "/api/json" ) ) 

Target exception: java.io.FileNotFoundException: http://test-1-20/job/test-portal-acceptance-pullrequest-batch%28master%29/11533//api/json

	at bsh.BSHMethodInvocation.eval(Unknown Source)
	at bsh.BSHPrimaryExpression.eval(Unknown Source)
	at bsh.BSHPrimaryExpression.eval(Unknown Source)
	at bsh.BSHVariableDeclarator.eval(Unknown Source)
	at bsh.BSHTypedVariableDeclaration.eval(Unknown Source)
```

**Comment by pyoo47** [comment]
I spoke with Hashi and it seems that test-1-20 and test-1-19 crashed yesterday. This would explain the missing job data. Hashi restarted them a little before 1pm yesterday.

**Comment by brianchandotcom** [comment]
@juliocamarero we have a rebase error (I was afraid of merging it because of a CI issue). Can you resend? Thx.

**Comment by juliocamarero** [comment]
@LeventeHudak can you please resend? thanks a lot!

**Pull request closed without merging**
