### PR TITLE
Issd 26

### PR DESCRIPTION
**Pull request by ryanschuhler**

### CODE REVIEW

**Comment by ryanschuhler** [comment]
ci:reopen

**Comment by ryanschuhler** [comment]
Works in conjunction with https://github.com/brianchandotcom/liferay-learn/pull/97

**Comment by brianchandotcom** [comment]
@ryanschuhler please resend, I think this hides the logic in setup.sh so it's not in this repo.

**Comment by ryanschuhler** [comment]
closing for https://github.com/brianchandotcom/liferay-portal/pull/147453

**Pull request closed without merging**
