### PR TITLE
LPS-80861 Not needed

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by jpince** [comment]
@jbalsas I think this commit https://github.com/brianchandotcom/liferay-portal/pull/58381/commits/4f5bc555e7e91006c30060693ee9de89ea120c95 caused a compile failure in user-groups-admin, can you please take a look?

```
     [exec] :apps:user-associated-data:user-associated-data-web:compileJSP
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/user-groups-admin/user-groups-admin-web/build/jspc/org/apache/jsp/view_jsp.java:793: error: cannot find symbol
     [exec]           _jspx_th_liferay$1ui_user$1group$1search$1container$1results_0.setSearchTerms( searchTerms );
     [exec]                                                                                          ^
     [exec]   symbol:   variable searchTerms
     [exec]   location: class view_jsp
```

cc/ @drewbrokke @pei-jung

**Comment by jbalsas** [comment]
Should be fixed in https://github.com/brianchandotcom/liferay-portal/pull/58387, thanks @ealonso!

**Comment by jpince** [comment]
@jbalsas the change in https://github.com/brianchandotcom/liferay-portal/pull/58381/commits/a888ddfa032cd02be9d125f211d9351f5883f78c#diff-320a1eda0393f697073dcf8ebfbfb0f1 caused functional tests to fail, requiring this test fix https://github.com/liferay/liferay-portal/commit/9e3f8126fbb5487281b7efd64f5cd6979ea5a3ed. @kyle-miho fixed the locator to be a little less fragile, but can you please let us know when you're making this kind of portal-wide change so we can update tests appropriately? Thanks!

**Comment by jbalsas** [comment]
Apologies about this @jpince. I honestly didn't expect this to break tests, otherwise I would've pinged you :(

I'll try to be more alert in the future.

**Comment by jpince** [comment]
@jbalsas no worries, thanks for being aware of this in the future. And if you're not sure, you can always mention me on the pull to investigate, that way it's on me and not you :P

**Pull request closed without merging**
