### PR TITLE
LRQA-53057 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-53057
https://issues.liferay.com/browse/LRQA-52996

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:test:depot

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@austinchiang please resend, doens't seem to work. See CI errors.

**Comment by austinchiang** [comment]
@brianchandotcom Sure, I'll resend. I think the tests ran, but here's what happened:
- We didn't have any tests that fit the query for `ci:test:relevant` so that's probably why that suite failed (we're making sure tests are stable first before adding them to acceptance)
- The test results for the other suite that ran can be seen [here](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=848210907). Most ran and passed. The ones that failed were due to known issues

Anyway, I'll resend this pull and send the `test.properties` commit in a different ticket later when we have acceptance tests for Depot.

**Pull request closed without merging**
