### PR TITLE
LPS-202881

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/322e2b5f72...ee10c8ee99

**Comment by brianchandotcom** [comment]
@ealonso can you sort all the

if (value instanceof 

in FragmentEntryProcessorHelperImpl.java

Whatever can be sorted can be in if, else if.

For anything that requires a specific order, you can add a line break and start a new if block.

See also ee10c8ee99122da2ab9de2ee11fb5c38322c2d30

Thx

**Comment by ealonso** [comment]
see: https://github.com/brianchandotcom/liferay-portal/pull/145686

**Pull request closed without merging**
