### PR TITLE
LPS-71624

### PR DESCRIPTION
**Pull request by mbowerman**
Hi @brianchandotcom,

This pull request has already been reviewed by @rotty3000 (among others). However, there was an issue when he forwarded the pull request to you, so I am submitting the pull request to you directly instead.

See https://github.com/rotty3000/liferay-portal/pull/1296 for where he reviewed it.

/cc @ChrisKian

### CODE REVIEW

**Comment by mbowerman** [comment]
Irrelevant test failure; this exact same failure also happened on https://github.com/brianchandotcom/liferay-portal/pull/48400.

**Comment by jpince** [comment]
@mbowerman yes, should be resolved by https://github.com/brianchandotcom/liferay-portal/pull/48426

**Comment by mbowerman** [comment]
ci:retest

**Comment by mbowerman** [comment]
Thanks @jpince!

**Comment by mbowerman** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Thx @mbowerman 

I'm glad you were able to make sense and fix some of my old code!

**Pull request closed without merging**
