### PR TITLE
LPS-98083 scope can be negative

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
Reviewed by @jeyvison .

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a1ddfc3431...b1e706e85b

**Comment by brianchandotcom** [comment]
@marcelabc @jeyvison @brunofarache this pull was very good. I made a few tiny changes, but overall, I was still very impressed. Good job @marcelabc

**Pull request closed without merging**
