### PR TITLE
LPS-68369 Use the local service so the advice can wrap the layout

### PR DESCRIPTION
**Pull request by matethurzo**
cc @shuyangzhou a regression caused by a refactor. We need to call the local service instead of the persistence as there is an advice class hooked on it, handling the page versioning

 @pavel-savinov the bug was this regression, the advice was not called for the layout. The advice always wraps the layout object this is how the page versioning is handled

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@matethurzo merged.

**Comment by brianchandotcom** [comment]
@matethurzo the SF error was real and caused by this pull, I fixed it in upstream. See:

```
java.lang.Exception: Do not use *ServiceUtil in *ServiceImpl class, create a reference via service.xml instead: ../../../portal-impl/src/com/liferay/portal/service/impl/PortletPreferencesLocalServiceImpl.java
Stacktrace

java.lang.Exception: Do not use *ServiceUtil in *ServiceImpl class, create a reference via service.xml instead: ../../../portal-impl/src/com/liferay/portal/service/impl/PortletPreferencesLocalServiceImpl.java

	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:264)
	at com.liferay.source.formatter.SourceFormatterTest.testSourceFormatter(SourceFormatterTest.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at com.liferay.portal.kernel.test.rule.TimeoutTestRule$1.evaluate(TimeoutTestRule.java:91)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at 
```

**Comment by matethurzo** [comment]
@brianchandotcom yes, I've re-sent it with the correct changes

**Pull request closed without merging**
