### PR TITLE
LPS-69675

### PR DESCRIPTION
**Pull request by holatuwol**
Resend of https://github.com/brianchandotcom/liferay-portal/pull/48019, because this repository isn't caught up with upstream and so the PR tester auto-closed my request.

Again, resending #47934 to see if pull request tester bug has been resolved. It's reporting that there is a new line at the end of service.xml, but checking out the branch locally, no such new line exists, and the commit history doesn't show a new line being added either.

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:retest

**Comment by holatuwol** [comment]
testray marks all of the failed tests as, "The build failed prior to running the test." I'm assuming that it's fine to retest in this case, because the only explanation that comes to mind is a network connectivity issue between the server running the test and testray.

**Comment by vicnate5** [comment]
@holatuwol https://loop.liferay.com/web/guest/home/-/loop/feed/4718528

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ef21219046...f900cc3129

**Pull request closed without merging**
