### PR TITLE
Lps 94393

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @lanceji92674957 run a compare, please.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/dd0be1d01c...c3bb02bdc8

**Comment by brianchandotcom** [comment]
@shuyangzhou I published this. But you didn't apply the new jar.. so I did it here c9e0d0a37f56ff4872e565a000bdfae1ae043c1b and 82a3c67ad856f5f42dfe59dcc0e40b8539f90ab3  @lanceji92674957 fyi

**Comment by shuyangzhou** [comment]
Thanks @brianchandotcom !

**Comment by lanceji92674957** [comment]
ok, running with all changes now

**Pull request closed without merging**
