### PR TITLE
LPS-190136 Create an Object Validation Client Extension Sample

### PR DESCRIPTION
**Pull request by guilhermedcamacho**
CI [errors](https://github.com/liferay-objects/liferay-portal/pull/2475#issuecomment-1690385623) are unrelated.

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/301b9c4b6a...c60452ae3a

**Comment by brianchandotcom** [comment]
@guilhermedcamacho @mateussgn see c60452ae3a4b25d27ae984f077efa2dcb66aa13a

Also, instead of adding the build.gradle commit and then reverting it, I just removed it from history all together before merging this PR.

**Comment by guilhermedcamacho** [comment]
cc @MarinhoFeliphe

**Pull request closed without merging**
