### PR TITLE
LPS-83106 Makes Classic Theme a CE profile only so it can be overriden by a more specific profile counterpart

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@jbalsas in 7.0.x, we had many themes with 

liferay-portal-profile-names=CE

I assume for 7.1.x, it'll just be this one.

**Comment by jbalsas** [comment]
I was hoping just this one... but maybe we need to have a similar one for `admin`, to also overlay the favicon.

The other two we had were removed in `7.1.x` and those pages will use `classic` instead.

**Comment by jbalsas** [comment]
I've sent https://github.com/brianchandotcom/liferay-portal/pull/60977 for `admin` as well and I hope to finish up the overlay for `7.1.x` for both shortly 🤞

**Pull request closed without merging**
