### PR TITLE
LPS-164268 buildLang

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-164268

@p2kmgcl

### CODE REVIEW

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See [liferay-echo#7560](https://github.com/liferay-echo/liferay-portal/pull/9801)

:heavy_check_mark: ci:test:stable - 28 out of 28 jobs passed
:x: ci:test:relevant - 180 out of 237 jobs passed in 1 hour 59 minutes

**Comment by ozysouza** [comment]
ci:repen

**Comment by ozysouza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f2bdda87fd...ea4644fb48

**Pull request closed without merging**
