### PR TITLE
LPS-79487 We should revert it when creation menu clay component is merged

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/56ab7b9a78...b1d54887c7

**Comment by brianchandotcom** [comment]
@ealonso @adolfopa please see my changes in upstream

@hhuijser please enforce my change in 4a7692e1c832b0308ddcddbfde2bbad6fb9d3abe via SF.

Thx

**Pull request closed without merging**
