### PR TITLE
LPS-99047

### PR DESCRIPTION
**Pull request by petershin**
@holatuwol

### CODE REVIEW

**Comment by petershin** [comment]
@pyoo47 - Just fyi, the `CKEditor` was updated to `v4.11.3` and a file needs to be added to mirrors

```
[exec] Trying to download http://mirrors.lax.liferay.com/ckeditor.com/cke4/sites/default/files/wsc/releases/wsc_4.11.3.zip to /root/.liferay/mirrors/ckeditor.com/cke4/sites/default/files/wsc/releases/wsc_4.11.3.zip.tmp
[exec] Trying to download https://ckeditor.com/cke4/sites/default/files/wsc/releases/wsc_4.11.3.zip to /root/.liferay/mirrors/ckeditor.com/cke4/sites/default/files/wsc/releases/wsc_4.11.3.zip.tmp
```

**Comment by pyoo47** [comment]
@petershin I submitted a ticket to IT: https://issues.liferay.com/browse/LRIT-14838

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/eb6622ae77...bac9a9a3bc

**Comment by brianchandotcom** [comment]
@petershin @holatuwol I backported this all the way back to 7.0.x

@holatuwol can you Slack me how much time this saves? Thx.

**Pull request closed without merging**
