### PR TITLE
LPS-76629 Update usages

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by jpince** [comment]
@michaelhashimoto @kenjiheigel @yichentsai jenkins failure?
```
BUILD FAILED
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-test-portal-acceptance-pullrequest.xml:701: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:7017: Sourced file: inline evaluation of: `` 				 					import com.liferay.jenkins.results.parser.AutoCloseRule; 					import  . . . '' : TargetError : at Line: 646 : in file: inline evaluation of: `` 				 					import com.liferay.jenkins.results.parser.AutoCloseRule; 					import  . . . '' : throw e ; 

Target exception: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Unable to get build JSON
```

**Comment by jpince** [comment]
oops, meant to include @yichenroy, not yichentsai

**Comment by jpince** [comment]
ci:retest

**Comment by yichenroy** [comment]
@jpince It seems like there may have been a brief network outtage causing the error:
`Caused by: java.net.UnknownHostException: test-1-20
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)`

The retest seems be running fine.

**Comment by brianchandotcom** [comment]
Can you resend? I see "FragmentRenderUtil.renderFragment"

But I also see "render_fragment_entry", do you want to render a fragment, or a fragment entry?

I'd like the objects/and methods to be consistent.

renderFragment(long fragmentInstanceId, long fragmentEntryId) should probably be

renderFragmentEntry(long fragmentEntryId, long fragmentInstanceId)

Please resend. Thx.

**Pull request closed without merging**
