### PR TITLE
Lps 64246

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @csierra this is caused by liferay@1372a7e

CC @michaelhashimoto

@brianchandotcom https://github.com/brianchandotcom/liferay-portal/commit/11e54051d0fdab22358685bdecd5aab22541d7c4 is a temp work around.

registry-impl needs the portal-kernel dependency to get over this infinite loop thread safety issue.

Later, either we have @Ithildir working out a proper auto replace build script logic, or @csierra rewrite those tests to do our arquillian way in a real tomcat, or we break down kernel into many many modules.

It is up to you @brianchandotcom to take which route.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by csierra** [comment]
/cc @migue @rotty3000 

If I remember correctly we should not couple Registry to portal kernel...

**Comment by rotty3000** [comment]
The only possible way to use the kernel API here is if the code is embedded into the registry library. Otherwise it creates a circular dependency since the RegistryImpl is a transitively depended upon by kernel.

**Comment by shuyangzhou** [comment]
ok, let's not embedded the code, it is not 1 or 2 classes we are talking about here. We will end up including 10~20 classes. Our perm/ meta space has grown rapidly due to all sorts of bnd includes. 

Ideally those kernel code we use here can be pulled out as a module which only has jdk dependency, then registry can safely use it, but it is too late for that, and I don't have the bandwidth for it.

Let's find a middle ground. I am going to rewrite that ServiceTracker tracking logic a bit, still reference based, but directly using jdk code. It is techinically duplicating whay kernel is doing, but in the most simplified way, at least this should only have minimal perm/meta space impact.

I will start on it once I get in office.

**Comment by csierra** [comment]
hey @shuyangzhou,

I was actually going to propose to use a plain syncronizedMap... it should not be such a burden since it is  *only* affecting when ServiceTrackers are created or portal is shutdown. Since ServiceTrackers already are blocking on creation it should not be such a difference

please see https://github.com/brianchandotcom/liferay-portal/pull/37607

**Comment by shuyangzhou** [comment]
Don't do it, that's wrong. It creates a gloabl synchronized point.

I will fix it once I get into office.

**Comment by shuyangzhou** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/37617

**Pull request closed without merging**
