### PR TITLE
LPS-101280 Use "directoryName, fileName" File constructor to avoid pa…

### PR DESCRIPTION
**Pull request by CAustin582**
…th typos

### CODE REVIEW

**Comment by CAustin582** [comment]
ci:reopen
ci:retest

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by CAustin582** [comment]
ci:retest

**Comment by CAustin582** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1ee245534e...cdf6950888

**Pull request closed without merging**
