### PR TITLE
master-sc-575

### PR DESCRIPTION
**Pull request by sharonchoi**
https://issues.liferay.com/browse/LRQA-23326
https://issues.liferay.com/browse/LRQA-23347
https://issues.liferay.com/browse/LRQA-23357
https://issues.liferay.com/browse/LRQA-23369
https://issues.liferay.com/browse/LRQA-23370
https://issues.liferay.com/browse/LRQA-23372

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 what happened here?

ci:retest

**Comment by pyoo47** [comment]
The LoadBalancer failed to communicate with all the masters so it threw an exception. I'll check with Sam P. to see if there have been any issues with the NAS today.

**Comment by pyoo47** [comment]
No load balancer issue with the current test. Barring any other external anomalies, this test should complete normally.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/36bf8d280e...347a57e72e

**Pull request closed without merging**
