### PR TITLE
LPS-60216 Creates a new filter for status

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc: @juliocamarero, @ealonso

**Comment by jkappler** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f5937959fe...dba0b00c3d

**Comment by jkappler** [comment]
Hi @brianchandotcom, sorry, I thought the change that you mentioned was in the taglib, now I know what you meant....

**Pull request closed without merging**
