### PR TITLE
LPS-108270 Create a set of settings to control AUI addition to pages

### PR DESCRIPTION
**Pull request by markocikos**
Hey @brianchandotcom ,

Followup on https://github.com/brianchandotcom/liferay-portal/pull/85319, with conflicts fixed.

The conflicts were there because of the portal-wide trailing commas change.

Please review the code.

Thank you!

/cc @izaera @wincent @jbalsas

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@markocikos I got SF errors in 

```
  2623:5  error  Expected object keys to be in natural ascending order. 'line' should be before 'name'.  sort-keys
  2625:26  error  Expected object keys to be in natural ascending order. 'column' should be before 'line'.  sort-keys
  2626:6  error  Expected object keys to be in natural ascending order. 'end' should be before 'start'.  sort-keys
  2626:24  error  Expected object keys to be in natural ascending order. 'column' should be before 'line'.  sort-keys
  2631:5  error  Expected object keys to be in natural ascending order. 'line' should be before 'name'.  sort-keys
  2633:26  error  Expected object keys to be in natural ascending order. 'column' should be before 'line'.  sort-keys
  2634:6  error  Expected object keys to be in natural ascending order. 'end' should be before 'start'.  sort-keys
  2634:24  error  Expected object keys to be in natural ascending order. 'column' should be before 'line'.  sort-keys
  2639:5  error  Expected object keys to be in natural ascending order. 'line' should be before 'name'.  sort-keys
  2641:26  error  Expected objecterror Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

> Task :apps:frontend-js:frontend-js-aui-web:packageRunFormat FAILED


FAILURE: Build failed with an exception.

* What went wrong:

```
can you resend on top of https://github.com/markocikos/liferay-portal/pull/180

**Comment by wincent** [comment]
@brianchandotcom: Did you see those SF errors while running from *inside* the `frontend-js-aui-web` folder? If so, I think you might be running into a bug where the linter is incorrectly looking at files in "tmp/" instead of just "src/" and "test/" — I created [LPS-109461](https://issues.liferay.com/browse/LPS-109461) for that and will send a fix today.

**Comment by wincent** [comment]
Sent https://github.com/brianchandotcom/liferay-portal/pull/85486 to make sure we don't see this kind of spurious SF in the future. Had to tweak the default globs because they were inappropriately matching build artifacts like "tmp/META-INF/resources/aui/test/test-min.js" and friends.

**Comment by markocikos** [comment]
> Sent #85486 to make sure we don't see this kind of spurious SF in the future. 

I'll resend https://github.com/markocikos/liferay-portal/pull/180 after this is merged.

**Pull request closed without merging**
