### PR TITLE
LPS-65974

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
ci:stop

**Comment by mhan810** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/94aa5885d1...38b9997fe2

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
@mhan810 @dylan-rebelak see 38b9997fe21f17c4c70db9879bf38e61ee305499

**Pull request closed without merging**
