### PR TITLE
LPS-56228 ant format-source

### PR DESCRIPTION
**Pull request by adolfopa**
@brianchandotcom This is a followup to https://github.com/brianchandotcom/liferay-portal/pull/28326

I couldn't push all `RequestBackedPortletURLFactory` parameters to the end consistently because the `ItemSelector.getItemSelectorURL()` has a varargs argument (and those must go at the end). Moving it to the front didn't look right either, so I've tried to follow two rules of thumb:
1. In the ItemSelector API, the factory takes at the rightmost possible position, but before any item selector specific parameters (itemSelectorEventName, itemSelectorCriteria).
2. In the Editor API, it goes at the end (except when rule #1 applies), and always after `ThemeDisplay`.

This way, we avoid breaking related parameters in the middle (see `ItemSelector.getItemSelectorURL`), and we push the factory as far as possible to the right.

I'm not entirely convinced about this, so if you don't like it, I can send you another PR where I break rule #1 (thus pushing the factory to the end no matter what).

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b17a6b9512...bfb3cfe313

**Comment by brianchandotcom** [comment]
@adolfopa I like your decision, we can never make anything perfect, but it's good. Previously, it seemed more random. At least now, there's more consistency. I'm trusting you to enforce that consitency going forward.

Can you document your rule in the LPS for easy reference in the future?

Thx

**Pull request closed without merging**
