### PR TITLE
LPS-57199

### PR DESCRIPTION
**Pull request by danielkocsis**

### CODE REVIEW

**Comment by danielkocsis** [comment]
ci:retest

**Comment by danielkocsis** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0661374e1f...560d72fda8

**Comment by brianchandotcom** [comment]
@danielkocsis nice job bro. I created a common init.jsp. See upstream. Thx.

**Pull request closed without merging**
