### PR TITLE
LPS-89493 buildLang

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test:change-tracking

**Comment by matethurzo** [comment]
@jpince here too, it's originating from not being able to delete a group. @kmaria verified manual deletion of a site is also not possible. I think many tests are failing due to this, but I'm not sure what caused it, our changes are unrelated

**Comment by jpince** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1bb7c85131...19f53f12a3

**Pull request closed without merging**
