### PR TITLE
LPS-54567 LiferayCacheManagerPeerProviderFactory incorrectly loads portalPropertyKey

### PR DESCRIPTION
**Pull request by shuyangzhou**
@brianchandotcom this is another ancient old bug, it got exposed by LPS-54410's fix. It is really funny to see how a bug covers another bug and made it working...

@tinatian This should fix your cache configuration issue about reading "ehcache.multi.vm.config.location.peerProviderProperties"

@mtambara please backport this one, also the commits under LPS-54410, thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f6712ed3ed...cc7c13342e

**Comment by brianchandotcom** [comment]
@mtambara please see backport my SF changes as well. Thx.

**Comment by brianchandotcom** [comment]
also @shuyangzhou should we do a simple unit test for this? Prevent future guys from breaking this. Thx.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/25189

**Pull request closed without merging**
