### PR TITLE
LPS-75798

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@brianchandotcom, this one fixes the performance issue in MB we talked about. Please backport as well.

/cc @slnn

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/19ee9c801d...b9357fd908

**Comment by brianchandotcom** [comment]
@hhuijser we can simplify the SF logic and ALWAYS add ()

so it's always like:

if (true) {
}

Which in our case is:

where (xyz == true)

I'd prefer that because it's safest.

**Comment by brianchandotcom** [comment]
Actually.. nevermind, I see that we needed to NOT have the ()..

I'll leave it to you to decide what is best for this.

**Comment by brianchandotcom** [comment]
@hhuijser but why would adding () break performance? Is it because of our search and replace no longer able to search and replace the sql?

**Pull request closed without merging**
