### PR TITLE
LPS-54791 Apply Settings pattern to Breadcrumb

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e74f60fb3b...7f4eac9a13

**Comment by brianchandotcom** [comment]
@jkappler we have both BreadcrumbPortletInstanceConfiguration and BreadcrumbPortletInstanceSettings referenced. I renamed it to *Configuration.

Can you review my change in 51a2e59cb4348c75e871c190f336a2211c7b471a

Thx

**Comment by jkappler** [comment]
@brianchandotcom yes, thx

**Pull request closed without merging**
