### PR TITLE
LPS-77373 Make toolbar items default to empty arrays in FragmentEditor

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
cc:@jbalsas

**Comment by ealonso** [comment]
Tests: https://github.com/ealonso/liferay-portal/pull/1439

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2fde8158a0...109e8b873e

**Comment by brianchandotcom** [comment]
@pavel-savinov @p2kmgcl @ealonso see 7c19d965ad77f4bbc4c0f8d3138b5299bf756743 and http://titlecapitalization.com/ (Chicago style)

**Pull request closed without merging**
