### PR TITLE
LPS-61501 not needed, use the one from the base

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@juliocamarero we had major CI issues (just fixed it). I'm ci:retest ing now

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
@brianchandotcom @juliocamarero 

The modules-integration-postgresql failure is happening because of this Jenkins plugin failure:
{code}Liferay patched class hudson.tasks.junit.JUnitResultArchiver
ERROR: Failed to archive test reports
java.io.IOException: remote file operation failed: /opt/dev/projects/github/liferay-jenkins-ee at hudson.remoting.Channel@63981fd8:cloud-10-0-111-51
	at hudson.FilePath.act(FilePath.java:916)
	at hudson.FilePath.act(FilePath.java:893)
	at hudson.tasks.junit.JUnitParser.parse(JUnitParser.java:87)
	at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:119)
	at hudson.tasks.junit.JUnitResultArchiver.perform(JUnitResultArchiver.java:133)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:756)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:182)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:669)
	at hudson.model.Run.execute(Run.java:1731)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:232)
Caused by: java.io.IOException: Remote call on cloud-10-0-111-51 failed
	at hudson.remoting.Channel.call(Channel.java:748)
	at hudson.FilePath.act(FilePath.java:909)
	... 13 more{code}

Here's a ticket for that particular failure:
https://issues.liferay.com/browse/LRQA-20933

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
