### PR TITLE
LPS-59815 Update AlloyEditor to 0.6.0

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e38bf64f55...3a986c6fb3

**Comment by brianchandotcom** [comment]
@ithildir can you review the build.gradle changes?

**Comment by brianchandotcom** [comment]
@ithildir there are definiltey some formatting issues here

```
from { zipTree(configurations.alloyEditor.singleFile) } {
```

and not sure about configurations

**Pull request closed without merging**
