### PR TITLE
Lps 54663

### PR DESCRIPTION
**Pull request by shuyangzhou**
@arbetts please check my changes, especially the https://github.com/brianchandotcom/liferay-portal/commit/8409ff308b1f2ce9b7ad3fc270e18778a71b40b9

### CODE REVIEW

**Comment by arbetts** [comment]
thanks @shuyangzhou 
I think i've learned a bit through your changes. "use a factory instead of inheritance for a data container class if we need to add some common logic"

why defer the double casting?

**Comment by shuyangzhou** [comment]
The defer casting is not something necessary, but better to have.
The goal to keep method input/output as clean as possible, even it is only a protected method, it is just easier to read.
In this case, the input are actually all int/long, as they are from counting. The output is just an int number with 0~100. The double is only needed during the calculation, not as input/output. Keep them in original form can help people to understand the code, and supposely making runtime method frame(the stack it pushes during the method call) smaller, as int takes 4 bytes, double takes 8 bytes. But the performance difference is too small, can be ignored (although it technically does exist), the main point is reduce the noise, to let people see what they really need to see.

Hope that makes sense to you.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@arbetts can you resend on top of https://github.com/arbetts/liferay-portal/pull/33

1.) 
```
		message.put(
			"backgroundTaskId",
			BackgroundTaskThreadLocal.getBackgroundTaskId());
		message.put(ReindexBackgroundTaskConstants.PHASE, phase);
		message.put(ReindexBackgroundTaskConstants.COMPANY_ID, companyId);
		message.put(ReindexBackgroundTaskConstants.COMPANY_IDS, companyIds);
```

Shoudl "backgroundTaskId" be a constant too? If not, why not?

2.) modules/portal/portal-search/src/main/java/com/liferay/portal/search/internal/background/task/ReindexBackgroundTaskStatusMessageTranslator.java

When I see "int completedCompanies" I expect a List<Company>

Please make it obvious it's a count, or a total at the very end. Thx.

**Comment by arbetts** [comment]
@brianchandotcom 

will apply the changes and resend on top of arbetts#33 

1) make backgroundTaskId a constant

2) make count / total more obvious

**Pull request closed without merging**
