### PR TITLE
LPS-190134 Implements ObjectValidationRuleEngine interface to allow Object Validations Client Extensions be used

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-190134

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:reopen

**Comment by mateussgn** [comment]
Tests passed here: https://github.com/liferay-objects/liferay-portal/pull/2367

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4456949c2c...48df262ee8

**Comment by brianchandotcom** [comment]
@mateussgn see 48df262ee81e3f40d463a4361b6644a05ef68d48

**Pull request closed without merging**
