### PR TITLE
LPS-79495

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by gamerson** [comment]
hey guys @hhuijser  @brianchandotcom   Can we merge this?  We need this for another PR that we are working on https://github.com/Ithildir/liferay-portal/pull/1002

**Comment by petershin** [comment]
ci:reopen

**Comment by petershin** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:reopen

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
