### PR TITLE
LPS-64625 SF

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @robertoDiaz

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
cc/ @jbalsas

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/923f532f3a...83fcb5049c

**Comment by brianchandotcom** [comment]
@sergiogonzalez potential fix for pre? 83fcb5049cc54a186911e5c0f105440699ce4e1f

**Pull request closed without merging**
