### PR TITLE
LPS-65528

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
/cc @Ithildir

@Preston-Crary

Can you take care of https://github.com/brianchandotcom/liferay-portal/pull/39321/commits/a84855aa99af8d4b056a877f6c2788a880f0ded2 and https://github.com/brianchandotcom/liferay-portal/pull/39321/commits/e6d113c02a818569c7cf447aa55f7d5f7b4bfdab

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
I had to stop and retest this pull because a recent CI pull that got merged into upstream broke the PR tester. The source of this problem has been reverted.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/12030e76c1...a0596673eb

**Pull request closed without merging**
