### PR TITLE
LPS-166626 Use showTitle param instead of windowState for rendering web content title

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-166626

@beltranrengifo @ealonso

### CODE REVIEW

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/10230

:heavy_check_mark: ci:test:stable - 28 out of 28 jobs passed
:x: ci:test:relevant - 77 out of 80 jobs passed in 1 hour 40 minutes

**Comment by ozysouza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d0b23d1a19...c85d245673

**Comment by brianchandotcom** [comment]
@ozysouza see 5df576f7d53a1851fcecdb1a2abfe7969a6bcd79

**Pull request closed without merging**
