### PR TITLE
Lps 149266

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3c7c8f9583...cb15117702

**Comment by brianchandotcom** [comment]
@jeffwu0724 I made quite a few changes in my origin. Please review.

**Comment by jeffwu0724** [comment]
@brianchandotcom Got it, I will learn from the changes and make my PR better next time, thanks Brian!😃

**Pull request closed without merging**
