### PR TITLE
LPS-68988 Regen

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jpince** [comment]
hey guys, I see a compile error that seems unique to this pull. Can you please take a look and resend?
```
build-common-java.compile:
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-portal/portal-impl/classes
    [javac] Compiling 2865 source files to /opt/dev/projects/github/liferay-portal/portal-impl/classes
    [javac] /opt/dev/projects/github/liferay-portal/portal-impl/src/com/liferay/portal/verify/VerifyGroup.java:409: error: unreported exception PortalException; must be caught or declared to be thrown
    [javac] 				UserLocalServiceUtil.addGroupUser(
    [javac] 				                                 ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1371: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:412: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build.xml:140: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-common-java.xml:52: Compile failed; see the compiler error output for details.
```
closing this pull.

**Comment by jpince** [comment]
ci:close

**Comment by pei-jung** [comment]
Fixed compile error and resent here https://github.com/brianchandotcom/liferay-portal/pull/44570. Thanks @jpince!

**Pull request closed without merging**
