### PR TITLE
LPS-60557

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by mhan810** [comment]
ci:retest

**Comment by mhan810** [comment]
@brianchandotcom the only failing test is a poshi test. there's some inconsistency in the KaleoTaskAssignmentInstancePersistenceTest.testActionableDynamicQuery.  The failure was not due to the changes, but due to the inability for the CustomSQL loader to load in a scheduled job in the blogs.  It's not consistently reproducible locally or in the CI.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7a5801f7a3...f7fdfda0e8

**Pull request closed without merging**
