### PR TITLE
Lps 71722

### PR DESCRIPTION
**Pull request by shuyangzhou**
@brianchandotcom please release a new kernel snapshot after merge, so that we can apply this to journal.

@pavel-savinov this is the portal side support code for SB localization feature. The example usage we are going to show you is inside journal. I will mention you again on the journal side pull. And after that @preston-crary will send you an email to explain how this is applied to journal. Then you should take this design into your friendly url case.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@Preston-Crary @shuyangzhou localized-using-extra-table=

**Comment by brianchandotcom** [comment]
localized="true/false/extra-table"

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/4084

**Pull request closed without merging**
