### PR TITLE
LPS-83949 Optimize loader

### PR DESCRIPTION
**Pull request by izaera**
Resending https://github.com/brianchandotcom/liferay-portal/pull/68382#issuecomment-466709045

### CODE REVIEW

**Comment by izaera** [comment]
ci:test

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
Verifying possible related failing tests

**Comment by john-co** [comment]
ci:reopen

**Comment by john-co** [comment]
ci:close

**Comment by john-co** [comment]
@izaera, I was able to reproduce these errors when rerunning the PR tests, so the issues are likely related to this pull:
PortalContextPath#Smoke
https://testray.liferay.com/home/-/testray/case_results/482170840?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D482168438%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc

ContentPagesWithStaging#PublishEditedContentPage
ContentPagesWithStaging#PublishEditedContentPage
ContentPagesWithStaging#PublishEditedContentPage
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=482168438

I will manually verify these tests and follow up with you on what I find.

cc/ @jbalsas

**Comment by john-co** [comment]
@izaera 
Confirmed PortalContextPath#Smoke bug manually. Unable to click on any Site Template on Add Site Menu

Steps to reproduce:
1. Set portal context to different name other than ROOT
(ie: can follow steps 1 thru 8 in LPS-89190 to set Portal context to something other than ROOT https://issues.liferay.com/browse/LPS-89190?filter=17480&jql=reporter%20%3D%20%22Koor%20Gai%22%20ORDER%20BY%20created%20DESC)
2. Navigate to CP > Sites > Add
3. Click on any Site Template
4. Assert Site Template cards are not clickable/selectable

For the ContentPagesWithStaging#PublishEditedContentPage error, it seems like an inconsistent error on PR tester. I am not able to reproduce manually. It's most likely unrelated to the PR.

cc/ @jbalsas

**Pull request closed without merging**
