### PR TITLE
LPS-63190 add a setting to the theme to choose if the maximize/minimize icons are shown (false by default, configurable in classic theme, visible in user-theme)

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @marcoscv-work @natecavanaugh

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@juliocamarero please resend? Too many failures. Thx.

**Pull request closed without merging**
