### PR TITLE
LPS-115709

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
Passed tests here: https://github.com/hhuijser/liferay-portal/pull/5081

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/745e9b95ed...f26d0ce56f

**Comment by brianchandotcom** [comment]
@thektan fyi 
@hhuijser 

I backported this to 7.3.x.

**Pull request closed without merging**
