### PR TITLE
LPS-112620 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LPS-112620

### CODE REVIEW

**Comment by john-co** [comment]
ci:reopen

**Comment by john-co** [comment]
Tested in https://github.com/wincent/liferay-portal/pull/245#issuecomment-623652482

**:heavy_check_mark:  ci:test:stable - 18 out of 18 jobs passed
:heavy_multiplication_x: ci:test:relevant - 116 out of 118 jobs passed in 2 hours 5 minutes**

- **modules-integration test batch** [Not Related] -
-- DLAdminDisplayContextTest failing in upstream: https://test-1-21.liferay.com/job/test-portal-acceptance-upstream-batch(master)/49351/AXIS_VARIABLE=12,label_exp=!master/testReport/com.liferay.document.library.web.internal.display.context.test/DLAdminDisplayContextTest/testGetSearchContainer/ and should be fixed by https://issues.liferay.com/browse/LPS-112874
-- known intermittent issue https://issues.liferay.com/browse/LPS-110102

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5763cc334c...5b860b7128

**Comment by brianchandotcom** [comment]
@jbalsas nicely done! And hope you're feeling better!

See 1f088f045e3954c0811997e152a4cae3abb385dd and 5b860b7128e3611c4b8ac72a277a278ccdb3fd3a

**Pull request closed without merging**
