### PR TITLE
Commerce 1067 5

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by jpince** [comment]
@petershin can you please review? It looks like they're trying to create a module within a module, but maybe this is intentional/allowed?

I noticed this because of the failure in `ModulesStructureTest.testScanBuildScripts`:
`junit.framework.AssertionFailedError: Forbidden modules/apps/batch-engine/headless/build.gradle`

**Comment by petershin** [comment]
@jpince - The `build.gradle` file should be deleted.

@ivicac @shuyangzhou - Would it make sense to move this project to the directory below.  It matches the naming pattern of projects in that directory.

`portal/modules/apps/headless/`

**Comment by shuyangzhou** [comment]
Yes, I will move them, thanks @petershin !

**Comment by shuyangzhou** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/78798

**Pull request closed without merging**
