### PR TITLE
LPS-109102 User Segment specific Assets Lists are not correctly published to live site

### PR DESCRIPTION
**Pull request by vendeltoreki**
cc: @laszlopap , @darquesdev

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@vendeltoreki @dgarciasarai not merging, I posted for help at https://liferay.slack.com/archives/CL84ZPHAT/p1584464789179800

**Comment by austinchiang** [comment]
ci:reopen

**Comment by austinchiang** [comment]
This was fixed and merged about an hour ago: https://github.com/brianchandotcom/liferay-portal/pull/86374/commits/2f0d85672c47adfd34051bb89cd8dca8aacee673

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/631f4f2611...8ece00704c

**Pull request closed without merging**
