### PR TITLE
LPS-74544

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
ci:test

**Comment by hhuijser** [comment]
@pyoo47, SF test should not fail. It seems like SF test is not taking into account the changes on SF from this commit?

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
@hhuijser - I'm trying it out again here:
https://github.com/michaelhashimoto/liferay-portal/pull/1191

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a762ff8c38...c0c5de90bd

**Comment by michaelhashimoto** [comment]
@hhuijser @pyoo47 - This should not happen in the future after these pulls are merged:
* https://github.com/brianchandotcom/liferay-portal/pull/56299
* https://github.com/brianchandotcom/liferay-portal-ee/pull/19603

Thanks for the help @petershin!

**Comment by hhuijser** [comment]
Thanks @michaelhashimoto !

**Pull request closed without merging**
