### PR TITLE
LPS-126827, et al. | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-126827
https://issues.liferay.com/browse/LPS-126842
https://issues.liferay.com/browse/LPS-126854
https://issues.liferay.com/browse/LPS-127162
https://issues.liferay.com/browse/LPS-127163
https://issues.liferay.com/browse/LPS-127164
https://issues.liferay.com/browse/LPS-126845
https://issues.liferay.com/browse/LPS-126824
https://issues.liferay.com/browse/LPS-126882
https://issues.liferay.com/browse/LPS-126847

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:reopen

**Comment by austinchiang** [comment]
@brianchandotcom test failures here are unrelated https://github.com/liferay-lima/liferay-portal/pull/1457. Resending to you to unblock DE test writing work

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6da360cd79...f6edba419b

**Comment by brianchandotcom** [comment]
@juliaduartelira @ThalitaCeli @juliaduartelira @zmmarina please review changes.

**Comment by ThalitaCeli** [comment]
Ok. Thanks!

Em qui., 4 de fev. de 2021 às 11:22, Brian Chan <notifications@github.com>
escreveu:

**Pull request closed without merging**
