### PR TITLE
Change Log Edits

### PR DESCRIPTION
**Pull request by codyhoag**
@Ithildir Thanks for your help!

### CODE REVIEW

**Comment by Ithildir** [comment]
Thanks to you @codyhoag! 😊

**Comment by Ithildir** [comment]
Hi,
I sent another pull (https://github.com/brianchandotcom/liferay-portal/pull/43861) on top of this one.

**Comment by anthony-chu** [comment]
These poshi test failures are because Poshi was unable to connect to the Firefox binary to due a VNC failure. QA Engineering is currently investigating this under [LRQA-28169](https://issues.liferay.com/browse/LRQA-28169).

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
