### PR TITLE
LRQA-49705 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-49705

### CODE REVIEW

**Comment by kyle-miho** [comment]
cc: @Tim-Cao good job, mainly sf fixes

**Comment by kyle-miho** [comment]
Tested Here: https://github.com/kyle-miho/liferay-portal/pull/298

**Comment by brianchandotcom** [comment]
Good job @Tim-Cao @kyle-miho !

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9ce4dee3e4...212a6c6d46

**Pull request closed without merging**
