### PR TITLE
LPS-65685

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by sharonchoi** [comment]
It appears that portal is not started up/broken for this pull:
before4

**Comment by brianchandotcom** [comment]
@hhuijser see comments from QA? thx.

**Comment by hhuijser** [comment]
@epgarcia, would you mind having a look at this one?

I am pretty sure I need to make changes to a build.gradle to use latest version of journal.service.
However, I have a hard time figuring out which one it is and Brian wants to keep the changes to a minimal and only change those that are required: https://github.com/brianchandotcom/liferay-portal/pull/39776

**Comment by epgarcia** [comment]
Hey @hhuijser,

I think the issue with the themes is fixed with this commit brianchandotcom/liferay-portal/pull/39830 and it has nothing to do with the journal-service dependencies. I've resent the PR to you to confirm that the tests are passing. See hhuijser/liferay-portal/pull/2652.

Regards

**Pull request closed without merging**
