### PR TITLE
LPS-69876 Blogs demo

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @ahdezma

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
@Ithildir any idea why ReplaceTranslationTaskTest.java was flagged? Passed in the first test run, and no change has been made in several days...

**Comment by jpince** [comment]
ci:reopen

**Comment by Ithildir** [comment]
@jpince: maybe SF changed... @hhuijser, any ideas?

**Comment by jpince** [comment]
ci:retest

**Comment by hhuijser** [comment]
@Ithildir @jpince 

The SF check for missing @Override is tricky.
We use qdox to find extended classes and we load all jars from tools/sdk/dist to do so. If you haven't run ant all, that directory is empty and it won't find the class and won't detect it needs @Override.

So, the warning is valid, SF just not warning if dist folder is empty.

**Comment by brianchandotcom** [comment]
@sergiogonzalez can you resend on top of https://github.com/sergiogonzalez/liferay-portal/pull/3746

1.) For the *.txt files, can you rename them to xyz_1.txt vs. xyz1.txt.

2.) LoremIpsumBlogsEntryDemoDataCreatorImpl#_getAllLines, can't we use StringUtil#read and then StringUtil#split?

Thanks.

**Pull request closed without merging**
