### PR TITLE
Verifiers review follow up

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by migue** [comment]
ci:retest

**Comment by migue** [comment]
ci:retest

**Comment by migue** [comment]
Brian,

All the tests are passing, just getting an OutOfMemory while the server is trying to log the end of the build. I don't think there is nothing I can do on mi side. Let me know if I could. Thx!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6b59497477...bf3d023a2d

**Pull request closed without merging**
