### PR TITLE
LPS-133933 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-133933

This is only for master.

@jkappler
@veroglez

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure cases are unrelated to changes in this PR.
See https://github.com/liferay-echo/liferay-portal/pull/5030
❌ ci:test:stable - 9 out of 10 jobs passed
❌ ci:test:relevant - 20 out of 25 jobs passed in 2 hours 5 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8215f0ece6...b724805913

**Comment by brianchandotcom** [comment]
@jkappler @veroglez fyi b724805913b3b283ce84bfd3737bd18d97bac3d0

**Pull request closed without merging**
