### PR TITLE
LPD-25445 User and Contact have a 1:1 relationship. And User's contac…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…t is very likey to be cached already, even not, the Contact fetching from User is based on PK. It is way faster than the non-cached multi column based where clause selecting by DynamicQuery.

@tinatian @vicnate5 backport is needed for LXC, thanks!

Also this is going to help login test case, since we are by default updating user login date/ip upon login now, which leads to user reindex. Before this fix, the reindex is pulling from DB for Contact unconditionally without cache, and using a relatively slow where clause. With this change, the DB cpu usage will drop a bit for all test cases we have, since the Contact is in cache already, no DB query is needed. Even we miss the cache due to expiration, the fetch will be based on PK, which is much faster.

Search has this bad XYZBatchReindexer pattern, which all suffer from this DynamicQuery usage. I am only fixing the one I can see from thread dumps. If search cares about this, they should do the cleanup, or I will take on them whenever we run into them from our test cases or real world cases.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/624ebc3137...b2aabec751

**Comment by shuyangzhou** [comment]
@victorhcunha @slnn we need to run a performance check for this too. thanks!

**Comment by slnn** [comment]
Hi @shuyangzhou 

Here are test results for this pull on Login, we can see 5.98% improvement on Session Count


Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | DB CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | --
Baseline | 624ebc3 | 7854 | - | 261 | 9,10,9 | 87,88,85
PR | - | 8324 | 5.984211867 | 267 | 9,10,9 | 86,87,90

More details you can check in this google doc: https://docs.google.com/spreadsheets/d/1M6VK8GtY9kkv1EwhGW7vwrEENSzyT7zKz-wOh11ZHBo/edit?usp=sharing


Lily

**Comment by shuyangzhou** [comment]
Thanks @slnn ! It looks right.

**Pull request closed without merging**
