### PR TITLE
LPS-73459 gradlew npmShrinkwrap

### PR DESCRIPTION
**Pull request by robframpton**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:reopen

**Comment by jbalsas** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/19ddd0857a...50439faee6

**Comment by brianchandotcom** [comment]
@Robert-Frampton please backport. Thx.

**Pull request closed without merging**
