### PR TITLE
LRQA-68365 Remove LCS smoke test

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:reopen

**Comment by vicnate5** [comment]
@zhangyan0701 Please send a follow up to remove all test scripts supporting LCS

**Comment by vicnate5** [comment]
Backports
https://github.com/brianchandotcom/liferay-portal-ee/pull/34976
https://github.com/brianchandotcom/liferay-portal-ee/pull/34977
https://github.com/brianchandotcom/liferay-portal-ee/pull/34978
https://github.com/brianchandotcom/liferay-portal-ee/pull/34979

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a83f7e4df5...639df45675

**Pull request closed without merging**
