### PR TITLE
LPS-62881 Not needed

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Thanks a lot @marcellustavares!! :+1:

**Comment by juliocamarero** [comment]
fyi @epgarcia

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Resent to https://github.com/brianchandotcom/liferay-portal/pull/36384

@juliocamarero waiting for test results there.

**Pull request closed without merging**
