### PR TITLE
LPS-105235 Source formatting

### PR DESCRIPTION
**Pull request by brunofarache**

### CODE REVIEW

**Comment by brunofarache** [comment]
ci:test:relevant:app-builder

**Comment by brunofarache** [comment]
@nhpatt thanks for your dedication and for being available all the time for my questions, you are an inspiration to me.

there's a minor change we need to make in the generated code: getPermissionCheckerActionsResourceName, getPermissionCheckerPortletName, getPermissionCheckerResourceName should all throw Exception. 

With this, I will be able to avoid try/catch when implementing them.

**Comment by nhpatt** [comment]
@brunofarache sent here: https://github.com/brianchandotcom/liferay-portal/pull/83723 :) Thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/650fcb63d3...c09832acaa

**Comment by brianchandotcom** [comment]
@brunofarache very nice job guys!

I also applied e8b990a6380795c8042063668c07e13703be52df

thank you @nhpatt @brunofarache !

**Pull request closed without merging**
