### PR TITLE
LPS-71052

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by NolanChan** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pyoo47 what happened here?

**Comment by pyoo47** [comment]
@brianchandotcom Looks like compile failure..
```
/opt/dev/projects/github/liferay-portal/build-common-java.xml:45: Compile failed; see the compiler error output for details.
```

**Comment by pyoo47** [comment]
Here's the compile error from the log:
```
build-common-java.compile:
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-portal/portal-impl/classes
    [javac] Compiling 2834 source files to /opt/dev/projects/github/liferay-portal/portal-impl/classes
    [javac] /opt/dev/projects/github/liferay-portal/portal-impl/src/com/liferay/portal/security/sso/SSOUtil.java:43: error: cannot find symbol
    [javac] 			Validator.isNull(ssoSessionExpirationRedirectURL)) {
    [javac] 			^
    [javac]   symbol:   variable Validator
    [javac]   location: class SSOUtil
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1399: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:426: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build.xml:189: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-common-java.xml:45: Compile failed; see the compiler error output for details.
```

**Comment by pyoo47** [comment]
I created a ticket to fix the code snippet in the GitHub message.
https://issues.liferay.com/browse/LRQA-31223

**Pull request closed without merging**
