### PR TITLE
LPS-59342 Add missing required property

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@csierra Same JaxWs tests as a the previous pull.

**Comment by csierra** [comment]
yeah... but those don't fail on my machine... :anguished:

**Comment by brianchandotcom** [comment]
Sorry @csierra I don't  know why. .b ut it's consistenlty failing.. so it could be a Linux env issue or how the modules are wired.. meaning the CI is catching something that would show up for a customer.

**Comment by csierra** [comment]
sure sure... I am not saying the CI is not caching something real... it is just that I don't know why it is failing because I can't make it fail locally. I will keep looking into this.

**Comment by brianchandotcom** [comment]
from what @shuyangzhou has taught me, 90% of the time, it's some OSGi dependency not loading in the proper order. He usually looks at the console.out or adds System.out messages in there (and sends himself a pull), to see why a NPE or some other exception is thrown.

Try looking at the console.out in the Jenkins servers.

**Pull request closed without merging**
