### PR TITLE
Lps 121470

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by tinatian** [comment]
@shuyangzhou @brianchandotcom Is there any reason this pull is closed?

Tina.

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
@tinatian it was a manual sent, I must forget to reopen it.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2401421d22...b707456cd0

**Comment by brianchandotcom** [comment]
@tinatian @shuyangzhou I backported this to 7.3.x

Can you see d33eaaaae683b8ea05f32a84740bdc2a204eef55 and send me a follow up pull based on my comment (if needed? ) thx.

**Pull request closed without merging**
