### PR TITLE
LPS-153120 Max file size vs. Mime type size limits

### PR DESCRIPTION
**Pull request by Hanlf**
Original pull request comment:

> Fix comment on https://github.com/brianchandotcom/liferay-portal/pull/122497 rebase error

@brianchandotcom resending this pull directly to you since after a few retries we confirmed this pull is not related to any of the failing tests in https://github.com/liferay-lima/liferay-portal/pull/3442.

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/35b803419a...1137d174a9

**Comment by brianchandotcom** [comment]
@thienquach87 see 3f2cb218bd0f30bd65b2d12aee3efdb10c03a896

**Comment by thienquach87** [comment]
thank you!

**Pull request closed without merging**
