### PR TITLE
LPS-78038

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test

**Comment by jpince** [comment]
ci:retest

**Comment by petershin** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by jpince** [comment]
@petershin I see the same failure in `ReflectionServiceTracker.java` in this pull and https://github.com/brianchandotcom/liferay-portal/pull/55408#issuecomment-365812017 but nowhere else, so I think it's something exposed by your change. Can you please look into it?

**Comment by jpince** [comment]
@yichenroy @michaelhashimoto when pasting a stacktrace for SF, can we have CI look for this line? `Exception in thread "main" java.lang.Exception: Found {x} formatting issues:` and then everything up to `at com.liferay.source.formatter.SourceFormatter.main` (or as many lines as we can allow). lmk if you have questions on this

**Comment by petershin** [comment]
@jpince - You're right. :sweat_smile:  Sent a fix: https://github.com/brianchandotcom/liferay-portal/pull/55422

**Comment by michaelhashimoto** [comment]
@jpince - Here's a ticket for this feature:
https://issues.liferay.com/browse/LRQA-38683

**Pull request closed without merging**
