### PR TITLE
LPS-61984 use pipingServletResponse so that the html is rendered in the right place

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@shuyangzhou fyi.. not sure how this may affect performance.

**Comment by brianchandotcom** [comment]
Nvm, it only affects the terms of use page...

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/afb634f390...f52fe35374

**Comment by shuyangzhou** [comment]
Yeah, this is harmless.

**Pull request closed without merging**
