### PR TITLE
LPS-62947 build-lang

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@topolik This should fix LPS-63224.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c71402e844...1a56550001

**Comment by brianchandotcom** [comment]
@leoadb @marcellustavares @adolfopa

Why do we need a change in this LPS to core Language.properties for permissions? Can the language key sit in the module instead?

cc @juliocamarero

Thx.

**Comment by leoadb** [comment]
@marcellustavares @adolfopa @brianchandotcom @juliocamarero

I'll move that key to a module in my next PR. Thanks @brianchandotcom !!!

**Pull request closed without merging**
