### PR TITLE
LPS-65528

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7eab3dc20e...ee83c4b872

**Comment by Ithildir** [comment]
I'm taking care of those SF errors, I'll send another pull.

**Comment by Ithildir** [comment]
I pushed the SF fix: https://github.com/liferay/liferay-portal/commit/3bbe945c4687bbf2c039e21121ab44643f84ceae.

**Pull request closed without merging**
