### PR TITLE
Lps 132259

### PR DESCRIPTION
**Pull request by shuyangzhou**
@brianchandotcom this pull adds the configurator support, and migrates exist default factory configurations to json configuration resources inside the owner bundles. Customers can create the same pid config file in osgi/config to overwrite builtin json configuration resources values.

However configurator does not have an effective way to "remove" or "disable" bundled default factory configuration. Blacklist the owner bundle is not doable in most cases, since owner bundle might have more than one configuration resources and export packages (for example, an API bundle with configuration resources), blacklisting the whole bundle is going to be way overkilled.

This will require each team who owns those default factory configuration to add an "enabled" key in their configuration, and update their business logic to respect the new key. Basically customer can not remove default configuration instance, but they can disable it.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/413be9f142...5b7f2176eb

**Comment by brianchandotcom** [comment]
@ericyan fyi

**Comment by brianchandotcom** [comment]
@ericyan please make sure this satisfies your needs

@tinatian can you work with @hhuijser to add the new SF enforcement?

@tinatian also, what about

```
modules/sdk/project-templates/project-templates-workspace/src/main/resources/archetype-resources/configs/prod/osgi/configs/com.liferay.portal.search.elasticsearch.configuration.ElasticsearchConfiguration.config
modules/sdk/project-templates/project-templates-workspace/src/main/resources/archetype-resources/configs/uat/osgi/configs/com.liferay.portal.search.elasticsearch.configuration.ElasticsearchConfiguration.config
```

**Comment by tinatian** [comment]
@brianchandotcom 
The two config files you mentioned should not move to json file. 

They are not default factory configurations which should not be changed by customer, they are there to show people how to config remote ES and most probably customers will change them.

Tina.

**Pull request closed without merging**
