### PR TITLE
LPS-77658

### PR DESCRIPTION
**Pull request by matethurzo**
cc @sergiogonzalez

single asset publish for blogs (publish is only present when staging is enabled)

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test

**Comment by matethurzo** [comment]
@brianchandotcom unrelated failures

**Comment by jpince** [comment]
ci:retest

**Comment by austinchiang** [comment]
ci:reopen

**Comment by austinchiang** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e973a17383...0779a56c9c

**Pull request closed without merging**
