### PR TITLE
LPS-83333 Update UI tests

### PR DESCRIPTION
**Pull request by matethurzo**
71x: https://github.com/brianchandotcom/liferay-portal-ee/pull/21027

### CODE REVIEW

**Comment by matethurzo** [comment]
seems unrelated

**Comment by matethurzo** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@matethurzo @kmaria the failure in ActivateRemoteStaging seems related... 
Maria updated the locator here: https://github.com/brianchandotcom/liferay-portal/pull/61365/files#diff-2df74d7235dea59eb9730fb44633e06bR55 from input to span
This is the html at head, can't tell if this pull changes it `<input class="field form-control" id="_com_liferay_staging_configuration_web_portlet_StagingConfigurationPortlet_remoteAddress" name="_com_liferay_staging_configuration_web_portlet_StagingConfigurationPortlet_remoteAddress" type="text" value="" size="20" autocomplete="off">`
I'm not going to close this, but just wanted to let you know.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by kmaria** [comment]
thank you, @jpince 
fixing it here https://github.com/brianchandotcom/liferay-portal/pull/61394

**Pull request closed without merging**
