### PR TITLE
LPS-102389 Change associated-to to associated-with

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
@ealonso FYI, please see 9571d23.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d44994e1fa...2123ff024c

**Comment by brianchandotcom** [comment]
@pei-jung see 7e632dfd9f550222a398c7bba25945eff14bd44b

I typed 'git grep "associated to"'

and looked for it in Poshi tests

**Comment by pei-jung** [comment]
Ah ok. I was only looking for usages in Language.properties 

Thanks for catching that.

**Pull request closed without merging**
