### PR TITLE
LPS-78896 General SF

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @brianchandotcom, this PR does 2 things:
- Reverts the removal of marketplace themes
- Updates fjord to 7.1 (updates for the other teams will follow)

After some feedback from other departments (GS, Marketing, Sales-Eng...), we decided we should bring the themes back for 7.1. 

The only change other than the minor version adjustments is that we'll explore a different way to present the content, away from resources importer. @JorgeFerrer will explore the possibility of leveraging the new Fragments API for this.

/cc @alee8888

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/69423eed0d...06122c538a

**Comment by brianchandotcom** [comment]
@jbalsas I merged all, but I reverted one commit in 06122c538aa1a30e548ddd1c1db6ebfe4a2c902e

The themes themselves may be for 7.1.0 only, but the DTD can be a 7.0.0 DTD. Those are 2 separate things. That version is specifying the schema of the XML file, which actually hasn't changed, so we can use a lower number.

**Comment by brianchandotcom** [comment]
@jbalsas good job coordinating with GS and sales. thx.

**Comment by jbalsas** [comment]
Hey @brianchandotcom, makes sense, for tooling purposes, that is: newly created themes and 
upgraded themes, should we target the `7.0.0` DTD or the `7.1.0`?

/cc @natecavanaugh

**Pull request closed without merging**
