### PR TITLE
LRDOCS-9554 Explain the CDN

### PR DESCRIPTION
**Pull request by jhinkey**

### CODE REVIEW

**Comment by jhinkey** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0c79b5f56c...3d81186d60

**Comment by brianchandotcom** [comment]
Also, perhaps mention that the server caches it for a few hours too

```

##
## Learn Tag Library
##

    #
    # Set this to true to read Learn resources from the CDN.
    #
    # Env: LIFERAY_LEARN_PERIOD_RESOURCES_PERIOD_CDN_PERIOD_ENABLED
    #
    learn.resources.cdn.enabled=true

    #
    # Set this to true to enable reading Learn resources. Setting this to false
    # essentially disables the Learn tag library.
    #
    # Env: LIFERAY_LEARN_PERIOD_RESOURCES_PERIOD_ENABLED
    #
    learn.resources.enabled=true

    #
    # Set the refresh time in milliseconds. The default value is 4 hours. Set
    # the value to 0 disable caching.
    #
    # Env: LIFERAY_LEARN_PERIOD_RESOURCES_PERIOD_REFRESH_PERIOD_TIME
    #
    learn.resources.refresh.time=14400000
    #learn.resources.refresh.time=0
```

See portal.properties.

**Comment by jhinkey** [comment]
Will do. Thanks!

**Pull request closed without merging**
