### PR TITLE
Lps 74807

### PR DESCRIPTION
**Pull request by shuyangzhou**
@rotty3000 @jrao @mhan810 @david-truong
This is the first extraction of core petra modules. Petra memory and part of petra concurrent.
This is focusing on petra memory, which has no dependency other than JDK. The reason part of petra concurrent is here, is those classes use petra memory directly. I will follow up to do a full extraction for petra concurrent.

The reason why I am not using the exist petra extraction ticket is, I have a different layout for the petra modules. The one really matters here is, I don't have a concurrent-memory, just memory and concurrent.

@brianchandotcom please see the last commit https://github.com/brianchandotcom/liferay-portal/commit/168504ba0a4b11923f90f90ad6c08792f5bb8866 . After you merge this, please release kernel 2.48.0 on https://github.com/brianchandotcom/liferay-portal/commit/691749841eee83eef7f98777b7149fa7ad6b1a3e, then you can just throw away the last commit. It is here just for CI to pass. We need to make sure the compat classes are the deprecated ones, that why you need to release right after the deprecation but before the removal.
I send everything as a whole to give the full picture. But if you prefer, I can break the pull at https://github.com/brianchandotcom/liferay-portal/commit/691749841eee83eef7f98777b7149fa7ad6b1a3e, so that you can merge and release first, then I follow up with compat changes. We can talk in office later today.

And this pull contains https://github.com/brianchandotcom/liferay-portal/pull/51637

Thanks!

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by jpince** [comment]
@shuyangzhou rebase errors

**Comment by jpince** [comment]
ci:close

**Comment by shuyangzhou** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/51696

**Pull request closed without merging**
