### PR TITLE
LPS-72854 SF - language keys, use http://titlecapitalization.com/ for titles

### PR DESCRIPTION
**Pull request by ealonso**
cc @jbalsas @marcoscv

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by ealonso** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@ealonso 1.) someone has to translate

use-a-retina-logo
show-main-navigation-in-full-screen

and a few other keys many times. That's painful for translators.

Please copy it to a common lang file or move it to portal-impl

2.) For *Url in text, it should be *URL

So

Twitter Icon Link Url

Should be

Twitter Icon Link URL

Please resend. Thx.

**Comment by ealonso** [comment]
@jbalsas

**Pull request closed without merging**
