### PR TITLE
LPS-69162 Add alter table commands

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
cc @marcellustavares

**Comment by marcellustavares** [comment]
ci:reopen

**Comment by marcellustavares** [comment]
ci:retest

**Comment by marcellustavares** [comment]
ci:stop

**Comment by leoadb** [comment]
@brunobasto I tend to think it's related to something we merged recently. Could you please take a look?

**Comment by leoadb** [comment]
ci:retest

**Comment by marcellustavares** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a67248b0de...abe6b74f98

**Pull request closed without merging**
