### PR TITLE
LPS-89795 Control AssetTag exceptions

### PR DESCRIPTION
**Pull request by alejandrohdezma**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d2202ab11f...5bf1330539

**Comment by brianchandotcom** [comment]
@petershin can you fix ade60014239a69b54e8828a9ffaa06df241405a2 the delete method is not getting generated. Could be generator or bad yaml file.

**Comment by nhpatt** [comment]
@brianchandotcom It's the plural issue, should be fixed with the tags PR

**Comment by brianchandotcom** [comment]
Thx @nhpatt ! @petershin fyi

**Pull request closed without merging**
