### PR TITLE
[TS]LPS-88011 Basic Authentication fails with a password containing ":" character

### PR DESCRIPTION
**Pull request by topolik**
Hi Brian,

https://issues.liferay.com/browse/LPS-88011

Thanks.

/cc @NorbertKocsis

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9c40e7bba6...003629d38e

**Comment by brianchandotcom** [comment]
@topolik  can you send a follow up pull and sort the params in

```
		String[] digestParams = {
			"username=\"Mufasa\"", "realm=\"testrealm@host.com\"",
			"nonce=\"dcd98b7102dd2f0e8b11d0f600bfb0c093\"",
			"uri=\"/dir/index.html\"", "qop=auth", "nc=00000001",
			"cnonce=\"0a4f113b\"",
			"response=\"6629fae49393a05397450978507c4ef1\"",
			"opaque=\"5ccc069c403ebaf9f0171e9517f40e41"
		};
```

@NorbertKocsis fyi

**Comment by brianchandotcom** [comment]
@topolik nvm, I went ahead and did it in 424d679

**Pull request closed without merging**
