### PR TITLE
APIO-171 APIO-168 Adapt Headless APIO apis so they can work as real APIs

### PR DESCRIPTION
**Pull request by alejandrohdezma**

### CODE REVIEW

**Comment by ahdezma** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ec905dda77...eeef7fba5e

**Comment by brianchandotcom** [comment]
@ahdezma I merged this.. but I do not like the design of HasPermissionImpl.

It won't scale as you plug in different types of assets both in the way things are named and for more complex checks. You need to rethink that class.

@jorgeferrer fyi..

**Comment by JorgeFerrer** [comment]
@ahdezma I fully agree with Brian. It does not make sense to have in Apio Architect a fixed set of methods, some of which that are clearly tied to Liferay Portal.

Let's talk about alternatives

**Comment by ZoltanTakacs** [comment]
Just FYI: we've already started to talk about alternatives :) https://liferayeng.slack.com/archives/C5E1CRLJY/p1523905889000551

**Comment by ahdezma** [comment]
@brianchandotcom @JorgeFerrer @ZoltanTakacs FYI: The `HasPermission` class has been refactored into a better and modular approach: https://issues.liferay.com/browse/LPS-81326

**Pull request closed without merging**
