### PR TITLE
LPS-65303 Hide simulation icon when we are simulating

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @jbalsas

**Comment by juliocamarero** [comment]
ci:stop

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Awww... no dream within a dream...

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ef3c1fb0fc...84ced447f3

**Comment by juliocamarero** [comment]
@brianchandotcom 😂  😂  😂

**Pull request closed without merging**
