### PR TITLE
LPD-19802 Adding method to download the site initializer

### PR DESCRIPTION
**Pull request by 4lejandrito**
https://liferay.atlassian.net/browse/LPD-19802

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
@ealonso @brianchandotcom this adds the GET. It is unimplemented but all the tests are passing.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/974263ec4b...1e9fbef924

**Comment by brianchandotcom** [comment]
@brianchandotcom very very nice I had to revert 5c95c2082419cd73e21ca5158b5daa01e57c2fd8 since that file is generated and I did it like this e788a9a3151bb339c9c2568900ed876ddb78fdb6

**Pull request closed without merging**
