### PR TITLE
[TS] [Urgent] LPS-200518 When upgrading from before U84 to U84+, existing Object Collection Provider configurations become invalid

### PR DESCRIPTION
**Pull request by liulukiwi**
https://liferay.atlassian.net/browse/LPS-200518

@mbowerman

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:reopen

**Comment by liulukiwi** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/14170

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5a4bdb19f9...b8c0949502

**Comment by brianchandotcom** [comment]
@mbowerman see b8c094950206d3c31450c1c57ae40d519ac620bc

**Pull request closed without merging**
