### PR TITLE
LRQA-36021, LRQA-36022, LRQA-36023 Optimize post-build and fix jenkins report bug

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-36021
https://issues.liferay.com/browse/LRQA-36022
https://issues.liferay.com/browse/LRQA-36023

Please publish after merging.

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@pyoo47 published.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/322e512c76...de9cdcbcff

**Pull request closed without merging**
