### PR TITLE
LPS-60201 Apply Lexicon to the current Config Admin UI and rename as System Settings

### PR DESCRIPTION
**Pull request by alee8888**

### CODE REVIEW

**Comment by alee8888** [comment]
@brianchandotcom @JorgeFerrer 
Jorge asked if any functional test would break from the renaming of Configuration Admin to System Settings in the Control Panel. Thus, I am combining the functional test updates alongside Jorge commits for LPS-60201 to eliminate any possible functional tests failure.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by JorgeFerrer** [comment]
Thanks Albert!

**Comment by brianchandotcom** [comment]
Merged. Thx

**Pull request closed without merging**
