### PR TITLE
LPS-96376

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
This test was broken because almost all checks for *.js or *.css were disabled. See https://github.com/brianchandotcom/liferay-portal/pull/74033

@wincent, for future reference, could you keep me in the loop for changes like these? (rather during the process, instead of after the fact with a loop post)

@brianchandotcom, I guess I should strip all the js/css checks from SF?

/cc @ling-alan-huang

**Comment by ling-alan-huang** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@hhuijser disabling of JS and CSS is temporary (like 6 months max). Please add a note to reenable it in 6 months.

One of the things I most dislike about Prettier in JS is how it deals with "if else" statements and how it deals line breaks on functions.

I told @jbalsas it was OK to move to Prettier first, but that within 6 months, we'll need a way to hack Prettier via plugins to get us back closer to our original formatting.

@wincent fyi

@jbalsas promised it to me as a Christmas gift!

**Comment by hhuijser** [comment]
@brianchandotcom, understood.
For now, we'll keep our hands off any formatting for css/js.

**Comment by jbalsas** [comment]
Hey @hhuijser, @ling-alan-huang, thanks for this and apologies for the lack of notice! I'll ping you offline so we can coordinate our future steps!

@brianchandotcom, already briefed @wincent. We'll work to roll out prettier and then add the rest of linting rules on top as a first phase. Once everything's settled, we'll tackle the missing formatting issues in phase 2, well before Christmas 😉

**Comment by wincent** [comment]
@hhuijser: I'm sorry for the breakage. I'll try to communicate any big changes like earlier in the future. Thanks for the feedback. I actually tried to deactivate the overlapping JS and CSS checks as part of #74033 with this change to "modules/util/source-formatter/src/main/resources/sourcechecks.xml":

```diff
diff --git a/modules/util/source-formatter/src/main/resources/sourcechecks.xml b/modules/util/source-formatter/src/main/resources/sourcechecks.xml
index 782a789c77f0..d216d98ac90d 100644
--- a/modules/util/source-formatter/src/main/resources/sourcechecks.xml
+++ b/modules/util/source-formatter/src/main/resources/sourcechecks.xml
@@ -62,11 +62,17 @@
        </source-processor>
        <source-processor name="CSSSourceProcessor">
                <check name="CSSCommentsCheck" />
-               <check name="CSSEmptyLinesCheck" />
-               <check name="CSSHexColorsCheck" />
+               <check name="CSSEmptyLinesCheck">
+                       <property name="enabled" value="false" />
+               </check>
+               <check name="CSSHexColorsCheck">
+                       <property name="enabled" value="false" />
+               </check>
                <check name="CSSImportsCheck" />
                <check name="CSSPropertiesOrderCheck" />
-               <check name="CSSWhitespaceCheck" />
+               <check name="CSSWhitespaceCheck">
+                       <property name="enabled" value="false" />
+               </check>
        </source-processor>
        <source-processor name="DockerfileSourceProcessor">
                <check name="DockerfileEmptyLinesCheck" />
@@ -387,8 +393,12 @@
                <check name="JSLodashDependencyCheck">
                        <property name="enabled" value="false" />
                </check>
-               <check name="JSStylingCheck" />
-               <check name="JSWhitespaceCheck" />
+               <check name="JSStylingCheck">
+                       <property name="enabled" value="false" />
+               </check>
+               <check name="JSWhitespaceCheck">
+                       <property name="enabled" value="false" />
+               </check>

                <!-- Portal checks -->

```

My understanding is that we had a Java test failure that was exposed by the PR, but it's been fixed now. I'll also look into [the other one that you flagged](https://github.com/brianchandotcom/liferay-portal/pull/74058#issuecomment-498525162) @hhuijser; that one looks like it's legitimately flagging a source-formatting issue in that code (fixable with `yarn format` in that module). There are still some gaps in our config (files that aren't yet checked/formatted) that I am going to chase down today, and hopefully iron out any remaining kinks.

@brianchandotcom: That error shows that even though we've disabled the existing JS/CSS checks, we do have alternate checks in place — so we're not flying blind. 😎

Ideally we'll be able to make changes to the Prettier output with a minimally invasive approach — ideally a plug-in — but if we have to, we'll consider forking it.

**Comment by hhuijser** [comment]
@wincent 
I did see that you had disabled those checks, although that change was a bit buried in that massive commit :)
I am fine with your changes. Please tag me in any future commits that have to do with your work on Prettier.
For now, I will leave JS/CSS files alone. When the Prettier integration is completed, we can see how SF can step in.

**Pull request closed without merging**
