### PR TITLE
LPS-85392 Unsubscribe button is displayed when user is already unsubscribed to comments and vice versa

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @jonathanmccann

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@jonathanmccann Please send a backport to support for 7.1.x and/or 7.0.x (like our normal support workflow). I'm no longer auto backporting pulls like this.

@jhendley @liferay @zsoltbalogh FYI.

Merged into master only.

**Pull request closed without merging**
