### PR TITLE
LPS-126440, LPS-126454 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-126440
https://issues.liferay.com/browse/LPS-126454

This is only for master.

@david-gutierrez-mesa
@alexcandidos

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure case is unrelated to changes in PR.
See https://github.com/liferay-echo/liferay-portal/pull/3610
✔️ ci:test:stable - 9 out of 9 jobs passed
❌ ci:test:relevant - 18 out of 25 jobs passed in 6 hours 32 minutes
See https://github.com/liferay-echo/liferay-portal/pull/3608
✔️ ci:test:stable - 9 out of 9 jobs passed
❌ ci:test:relevant - 20 out of 25 jobs passed in 4 hours 56 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/06b572e674...2ffdb308a9

**Comment by brianchandotcom** [comment]
@gabrielargomes @antonioalmeidab please review changes.

**Pull request closed without merging**
