### PR TITLE
LPS-75766 Return default asset publisher customiser in case when there is no customiser for the portlet

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
cc @epgarcia @ealonso @ctampoya

**Comment by epgarcia** [comment]
Thanks @pavel-savinov! I think it's better if it gets fixed portal-side. This way any app customizing the Asset Publisher benefits from it (and not only Audience Targeting).

**Comment by ctampoya** [comment]
Thank you @pavel-savinov! 

/cc @brianchandotcom @ZoltanTakacs Here is the fix for WCM-1394. I have asked @pavel-savinov to also send a BPR.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3ad9823522...8189751f79

**Comment by brianchandotcom** [comment]
Thx @pavel-savinov backported..

**Pull request closed without merging**
