### PR TITLE
LPS-69673

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@brianchandotcom

What about this?
It will set the version to "NEXT-VERSION" when the version equals or exceeds the current version from the *.bnd.
This way I don't need to go to repository.liferay.com to grab the latest released version.

Right now, it will set every single deprecated version to NEXT-VERSION in portal-impl, portal-kernel, etc.
If we want the correct deprecated version, we'd have to do a big manual exercise. We'd need to find a volunteer to do that, since I don't have the bandwidth :)

**Comment by brianchandotcom** [comment]
@ithildir see these errors for npm-shrinkwrap? See my fix in 5c734242b52c54bc93a02e613dc0e585f03c5fc7

The problem is that those files don't exist in 7.0.x, so when I cherry pick, it's not applied.

For your tool, I need it to run the logic to replace those JSON files if they exist. This is similar to "apply".

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by hhuijser** [comment]
ci:reopen

**Pull request closed without merging**
