### PR TITLE
LPS-78050 Gradle dependencies

### PR DESCRIPTION
**Pull request by petershin**
@tomwang2011 @hhuijser

### CODE REVIEW

**Comment by petershin** [comment]
ci:test

**Comment by pyoo47** [comment]
ci:stop (Temp map server has been restarted)

**Comment by pyoo47** [comment]
ci:test

**Comment by petershin** [comment]
There was a regression bug: 3c6a6e21e1da17b2f1704ed0dacba44a7eb49eac

Sent a fix: https://github.com/brianchandotcom/liferay-portal/pull/55947

**Comment by petershin** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/45966bccbd...6c976e3a41

**Pull request closed without merging**
