### PR TITLE
LPS-162857 Cover FileEntry's Link DTO by using integration tests

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/07a94cd13a...638670eeb6

**Comment by brianchandotcom** [comment]
@MarinhoFeliphe see 2931f7115d932fa14b087871f9387b11a1a8aff5 and 638670eeb6b3cb317dd4e094402faae4f24b21ed

**Comment by naraandrade** [comment]
Just started reviewing :)

**Pull request closed without merging**
