### PR TITLE
LPS-140522 Relationship deletion should validate if there are related entries between objects

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-140522

### CODE REVIEW

**Comment by mateussgn** [comment]
Sending you directly because the [test failures](https://github.com/liferay-objects/liferay-portal/pull/1083) are not related to my changes.

**Comment by brianchandotcom** [comment]
@mateussgn the impl is a bit strange..... I'm trying to put my finger on it to see how we can impl it differently.

**Comment by mateussgn** [comment]
Hey @brianchandotcom,
I can seek another approach and send you a new pull request if I reach a better one. It is not a problem.

**Comment by brianchandotcom** [comment]
@mateussgn still seems off, please resend.

**Pull request closed without merging**
