### PR TITLE
LPS-84879 SF

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/879b9ad94a...abca74cbfa

**Comment by brianchandotcom** [comment]
Hey guys, this ticket contains

LPS-84879, which was already backported by support. Please do not forget to backport these changes too!

@brunobasto fyi!

**Comment by brunobasto** [comment]
Hey @brianchandotcom, LPS-84879 is a story ticket. It's not supposed to go to 7.1.x. Did you misspelled the ticket number?

**Comment by jpince** [comment]
@brunobasto @clovisdasilvaneto I'm pretty sure this pull broke frontend-js, can you please take a look?
A lot of the errors look like this:
```
     [exec]     -     <input class="form-control" name="textField" type="text" disabled="disabled" value="">
     [exec]     +     <input class="form-control" name="textField" type="text" value="">
```
https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/263037//consoleText

**Comment by brunobasto** [comment]
Fix sent here: https://github.com/brianchandotcom/liferay-portal/pull/64113

**Pull request closed without merging**
