### PR TITLE
LPS-69532 | master

### PR DESCRIPTION
**Pull request by vicnate5**
@inacionery @marcellustavares

### CODE REVIEW

**Comment by inacionery** [comment]
ci:reopen

**Comment by inacionery** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@vicnate5 @inacionery I rolled this back. See comment  from @shuyangzhou

**Comment by shuyangzhou** [comment]
@vicnate5 @inacionery this does not look right, the new test rule is duplicating most code from SynchronousDestinationTestCallback. It should not be done this way.
Please come to me to let me know what do you really need, we can do this in some other ways.

**Pull request closed without merging**
