### PR TITLE
LPS-198209 Add context title to back button in Asset

### PR DESCRIPTION
**Pull request by alessandromalves**
## Motivation

[Link to ticket](https://liferay.atlassian.net/browse/LPS-198209)

### Changes

Add the back URL title for back buttons in Assets.

## Test scenario 1

1. Create a Vocabulary.
2. Check the back button title. Should follow the pattern "Go to Categories".

 `edit_asset_voc`
image

3. Add a Category.
4. Check the back button title. Should follow the pattern "Go to Categories".

 `details`
image

5. Select the category clicking in the checkbox.
6. Go to the kebab menu and click on Assign Display Page Template.
7. Check the back button title. Should follow the pattern "Go to Categories".

`set_asset_category_display_page_template`
image

## Test scenario 2
1. Create a new Dynamic Collection.
2. Check the back button title. Should follow the pattern "Go to Collections".

`edit_asset_list_entry_dynamic`
image

3. Do the same for a Manual Collection.

`edit_asset_list_entry_manual`
image

## Test scenario 3
1. Create a Tag.
2. Check the back button title. Should follow the pattern "Go to Tags".

image

3. Merge the tagand check it again.

image

## Test scenario 4
1. You should have created some web contents (WC) with a Display page Template related and a Page Collection with those Web Contents.
2. Now, go topage tree and being in any page you can click on the kebab menu for the collection page and click on "View Collection Items".
3. Once the modal it's open you can choose for any WC in the kebab menu the "View Dsiplay Page" action.
4. Check the back button. It should follow the pattern "Go to x" wher the x it's tha name of the page you where in.

https://github.com/liferay-echo/liferay-portal/assets/93203423/016bd17d-d18f-446b-9ec0-6e39fbc54742

5. In Miller Columns, go to the kebab menu for the collection page and click on "View Collection Items".
6. Once the modal it's open you can choose for any WC in the kebab menu the "View Dsiplay Page" action.
7. Check the back button. It should follow the pattern "Go to Pages".
8. Look for your Page Collection in the search container and re-do steps from 5-7.

image

9. Go into the edit mode of the Page Collection and click on the button next to the name "[x items]".
10.  Once the modal it's open you can choose for any WC in the kebab menu the "View Dsiplay Page" action.
11. Check the back button. It should follow the pattern "Go to x", where x is the name of the page collection.

https://github.com/liferay-echo/liferay-portal/assets/93203423/bd525061-ed63-40de-9efc-78986ba1403f

## Notes:

**It's not necessary add the back URL title in:**
`edit_asset_list_entry`
`view_content`

### CODE REVIEW

**Comment by alessandromalves** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/13939

❌ ci:test:stable - 29 out of 30 jobs passed
❌ ci:test:relevant - 238 out of 255 jobs passed in 2 hours 51 minutes

**Comment by alessandromalves** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1a3d417ea7...5d190def7b

**Comment by brianchandotcom** [comment]
@BarbaraCabrera yey, you've learned all the weird Liferay naming / sorting / naming conventions :)

**Pull request closed without merging**
