### PR TITLE
Lps 65510

### PR DESCRIPTION
**Pull request by shuyangzhou**
@brianchandotcom this only includes the part that we activate wab war (including theme war, but in general can be applied to any wab war) based on profile matching. So that we can reach the goal that, on CE platform, we don't activate ee theme, or on EE platform, we don't activate ce theme. Or base on any other user defined profile matching combination.

Once after you have the frontend team moved out the "classic" and "admin" buildin themes as modules, I can continue on the servletContextName specifying support, so that EE themes can automatically gain the same theme ids as CE counterparts without any additional parameter swapping.

CC @jorgeferrer

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Thanks Shuyang, this looks very cool!

I'd like to document it to distribute the knowledge of how it works. Is it mature enough for that or should I wait?

**Comment by shuyangzhou** [comment]
Please wait for the 2nd piece is done. I am waiting on the frontend team to clean out the 2 buildin themes. Once that is done, it might take me half day to get the 2nd piece done, then this will be ready to qa through test and documenting.

**Comment by JorgeFerrer** [comment]
Sounds good. I'll wait.

On Fri, May 13, 2016 at 3:05 PM, Shuyang Zhou <notifications@github.com>
wrote:

> Please wait for the 2nd piece is done. I am waiting on the frontend team
> to clean out the 2 buildin themes. Once that is done, it might take me half
> day to get the 2nd piece done, then this will be ready to qa through test
> and documenting.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/39758#issuecomment-219037077>
>



-- 
Jorge Ferrer
Vice President, Engineering
@jorgeferrer <https://twitter.com/jorgeferrer>

*Liferay Inc*
Web <http://www.liferay.com> | Facebook <http://facebook.com/liferay> |
Twitter <http://twitter.com/liferay>


*Aviso de Confidencialidad: *Este mensaje de correo electrónico, incluidos
los archivos adjuntos, enviados en nombre de Liferay SL es para el uso
exclusivo del destinatario (s) previsto y puede contener información
confidencial y privilegiada. Se prohíbe cualquier revisión no autorizada,
uso, copia, divulgación o distribución. Si usted no es el destinatario, por
favor póngase en contacto con el remitente por correo electrónico de
respuesta y destruir todas las copias del mensaje original. Gracias.

*Confidentiality Notice: *This e-mail message, including any attachments,
sent on behalf of Liferay SL is for the sole use of the intended
recipient(s) and may contain confidential and privileged information. Any
unauthorized review, use, copying, disclosure or distribution is
prohibited. If you are not the intended recipient, please contact the
sender by reply e-mail and destroy all copies of the original message. Thank
you.

**Comment by brianchandotcom** [comment]
Merged!

**Pull request closed without merging**
