### PR TITLE
COMMERCE-5205 Refactor inventory engine to make it extensible

### PR DESCRIPTION
**Pull request by luca-pellizzon**
Hello @brianchandotcom sending this directly to you because of issues with CI builds.
I asked our commerce's QA team to check the PR failures and looks like none of them is related to it.
Can you please have a look at and merge if ok?
Many Thanks

cc @victoroscuro @riccardo-alberti

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/db1bf5fed7...3c5ca44e80

**Comment by brianchandotcom** [comment]
@alessiorendina @luca-pellizzon just 3c5ca44e80f7c6f76b76a337efb0d5368be418e0

also, this can be a backwards compat issue for those with config files right?

**Comment by luca-pellizzon** [comment]
@brianchandotcom yes it is indeed a breaking change. But it is necessary to allow customers/partners to create more easily a "remote inventory" integration. Something like SAP or similars

**Pull request closed without merging**
