### PR TITLE
LPS-84653 Avoid exception

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/43bed1e922...638dfbeb7b

**Comment by brianchandotcom** [comment]
@pedroqueiroz Please send a backport to support for 7.1.x (like our normal support workflow). I'm no longer auto backporting pulls like this.

@jhendley @liferay @zsoltbalogh FYI.

Merged into master only.

**Comment by pedroqueiroz** [comment]
Backport was sent here: https://github.com/brianchandotcom/liferay-portal-ee/pull/21636.

**Pull request closed without merging**
