### PR TITLE
LPS-97276 Extract PortletFilerepository to a module

### PR DESCRIPTION
**Pull request by cgoncas**
/cc @adolfopa

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Hey @jpince, are these Test Failures related with this pull?

**Comment by jpince** [comment]
@cgoncas they look unrelated

**Comment by brianchandotcom** [comment]
Can you resend, rename

repository.portletfilerepository

to

repository.portlet.file.repository

Same for bnd and folder name.

This matches com/liferay/portlet/documentlibrary (old) with com/liferay/...../document/library (new)

Thx!

**Comment by cgoncas** [comment]
Continues in: https://github.com/brianchandotcom/liferay-portal/pull/75036

**Pull request closed without merging**
