### PR TITLE
LPS-103035 Adding companyId to primaryKey and unique indexes

### PR DESCRIPTION
**Pull request by achaparro**
Hi @brianchandotcom,

This is the first and most complex task for data partitioning that we were talking about. I have been testing it for several weeks with QA and Preston and it seems complete now. Please, let me know if you have any questions so we can solve it soon since every rebase is hard due to the number of modified files.

Thanks.

cc/ @vicnate5 @Preston-Crary @kyle-miho

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:test:stable

**Comment by jpince** [comment]
@vicnate5 took a quick look at the int test failures, some look related, e.g. `
java.lang.AssertionError: CompanyId must be always the last column in the primary key`. DL**TrashHandler tests are not failing in upstream

I didn't look at any other tests.

**Comment by vicnate5** [comment]
ci:close

**Comment by vicnate5** [comment]
@achaparro Confirmed what Jason noticed, failures in
https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/325855/#showFailuresLink
```
com.liferay.portal.upgrade.test.UpgradeCompanyIdPrimaryKeyTest.testAddColumnAsPrimaryKeyAfterCompanyId
com.liferay.portal.upgrade.test.UpgradeCompanyIdPrimaryKeyTest.testAddCompanyIdAsPrimaryKey
com.liferay.portal.upgrade.test.UpgradeCompanyIdPrimaryKeyTest.testAddExistingCompanyIdAsPrimaryKey
```

**Pull request closed without merging**
