### PR TITLE
LPS-93526 We want common tags, not collected tags.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@shuyangzhou how did you even now this was a problem?

**Comment by brianchandotcom** [comment]
@4lejandrito fyi

**Comment by 4lejandrito** [comment]
I pointed him to the root cause: https://github.com/brianchandotcom/liferay-portal/pull/71010#issuecomment-480929949. 

Thanks @shuyangzhou, @brianchandotcom.

**Comment by brianchandotcom** [comment]
Thx guys fro collaborating!

**Pull request closed without merging**
