### PR TITLE
LPS-7415 RepositoryException thrown when adding sharepoint repository

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d1c6aebb6a...fdb8e8d1a0

**Comment by brianchandotcom** [comment]
@ithildir when should I use Include-Resource, and when should I use -includeresource?

Can you send a follow up pull to fix modules/third-party/com-microsoft-schemas-sharepoint/bnd.bnd since it uses both?

Perhaps also check other bnd.bnd files and then come up with an SF rule? Thx.

**Comment by Ithildir** [comment]
I don't think there's a particular reason to use `Include-Resource` instead of `-includeresource` in `com-microsoft-schemas-sharepoint`. The only exception is `*-test` modules because of the Arquillian integration IIRC.

@sergiogonzalez, why did you use `Include-Resource` here? Can I safely change it to `-includeresource`, or you're going to read the manifest header at runtime?

**Comment by adolfopa** [comment]
@Ithildir No special reason. I'll send the fix to Brian.

Thanks!

**Pull request closed without merging**
