### PR TITLE
Lps 71133

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@ithildir please review modules/apps/static/portal-osgi-web/portal-osgi-web-jasper-plugins/build.gradle

Thx.

**Comment by Ithildir** [comment]
It looks good to me! I worked on it yesterday with Preston 😊

**Pull request closed without merging**
