### PR TITLE
LPS-107326 remove code duplication

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4e6e6fdba6...acc1baee9c

**Comment by brianchandotcom** [comment]
@nhpatt please backport if applicable.

**Comment by brianchandotcom** [comment]
@nhpatt nvm, I did the backport (cherry picked cleanly).

**Comment by nhpatt** [comment]
Thanks! :)

**Pull request closed without merging**
