### PR TITLE
LRQA-35970 | master

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-35970

Sorry, this should have been included in my previous PR. Additional commits on top of https://github.com/brianchandotcom/liferay-portal/pull/52856.

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:stop

Conserving resources

**Comment by xbrianlee** [comment]
ci:stop

Conserving resources

**Comment by xbrianlee** [comment]
ci:stop

Conserving resources

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
