### PR TITLE
LPS-79679

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@jeyvison, can you fix these? https://github.com/brianchandotcom/liferay-portal/pull/61081/commits/920fc8c1348cc203068360209dbff20204865fc7

**Comment by hhuijser** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by jeyvison** [comment]
@hhuijser Fixed. See [this pull](https://github.com/brianchandotcom/liferay-portal/pull/61110#issuecomment-403039698)

**Pull request closed without merging**
