### PR TITLE
LPS-90254 Make System Settings portlet renderable at different scopes

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-90254](https://issues.liferay.com/browse/LPS-90254).<br><br>/cc @pei-jung @stsquared99 @alee8888 @ChrisKian

### CODE REVIEW

**Comment by drewbrokke** [comment]
@jpince is this a real failure?

**Comment by jpince** [comment]
ci:reopen @drewbrokke no, this one is an intermittent CI issue

**Comment by drewbrokke** [comment]
thanks @jpince!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b8ad9115ce...a1f0849941

**Comment by brianchandotcom** [comment]
Please fix those 3 files. Thx!

**Pull request closed without merging**
