### PR TITLE
LPS-66857 updates test

### PR DESCRIPTION
**Pull request by JorgeFerrer**
Hey Brian,

I'm not a fan of the changes to the addContact() and updateContact() methods, but I don't really know what's best. Those methods are inherited from the base service and in reality should not even exist.

The automatic creation of these add and update methods by service builder is actually a bad thing that we should fix since those methods will not contain any of the business logic and thus will cause potentially big problems if they are invoked at all.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6620d8ea8a...c4890ca346

**Comment by brianchandotcom** [comment]
@sherlyliu Should we also call validate(className, classPK)?

@JorgeFerrer I agree with you, but it's difficult to change at this point.

Initially, we didn't have the autogenerated methods for precisely the reasons you mentioned. But we use them a lot because it's a quick way to add a row to the database (though it can have unintended consequences).

**Comment by brianchandotcom** [comment]
@drewbrokke please see my test changes

**Comment by drewbrokke** [comment]
Got it thanks @brianchandotcom

**Pull request closed without merging**
