### PR TITLE
LPS-77223 Apply new NavigationBar pattern to server-admin-web

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
@alee8888 fyi, clay change

**Comment by brianchandotcom** [comment]
Can you resend based after applying the same changes I made in LPS-77555? Thx.

**Comment by pei-jung** [comment]
Resent as https://github.com/brianchandotcom/liferay-portal/pull/54932

**Pull request closed without merging**
