### PR TITLE
LPS-65179

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by brianchiu** [comment]
Functional test failures will be fixed by https://github.com/brianchandotcom/liferay-portal/pull/39048

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b8b7b7f569...3e065da566

**Comment by brianchandotcom** [comment]
@Ithildir Hmm.. that settings.gradle is getting a bit verbose?

**Comment by Ithildir** [comment]
I know :disappointed: I'll see what I can do...

**Pull request closed without merging**
