### PR TITLE
LPS-67399 As a developer I can invoke a method that returns a paginated and ordered unified lists of both organizations and users

### PR DESCRIPTION
**Pull request by pei-jung**
Hey @brianchandotcom,

I tried to get the users that are assigned to a specific organizaiton with DynamicQuery but encountered an issue. The user-organization relationship is in the mapping table "Users_Orgs". There doesn't seem to exists a class representing the data in Users_Orgs, so I don't know how to initialize the query.

`DynamicQueryFactoryUtil.forClass(???.class, getClassLoader());`

I've looked into DynamicQuery usages in different places but still can't find a way to do it. Sorry if I missed it. If you really want this do be done in DynamicQuery, I'll keep looking.

/cc @jorgeferrer @drewbrokke

### CODE REVIEW

**Comment by brianchandotcom** [comment]
DynamicQueryFactoryUtil.forClass(???.class, getClassLoader());

You can just pass in the Portal Class Loader? That is a hack but should work.

Please resend.

**Comment by brianchandotcom** [comment]
@jorgeferrer See my explanation.

Originally, @drewbrokke sent me a pull for LPS-66831 in https://github.com/brianchandotcom/liferay-portal/pull/42851

I found it quite ugly and unnecessary to use the Custom SQL pattern there. I asked @drewbrokke to resend it, and he did in https://github.com/brianchandotcom/liferay-portal/pull/43321

Both @drewbrokke and I agree that the new way, using Dynamic Query, is much cleaner.

I also got the pull https://github.com/brianchandotcom/liferay-portal/pull/42897 around the same time, and since @drewbrokke and @pei-jung sit next to each other, I asked @pei-jung to also use the Dynamic Query pattern.

The other reason I didn't merge this was that it never followed our existing Custom SQL pattern exactly. See DLFolderFinderImpl, MBCategoryFinderImpl, SocialActivityCounterFinderImpl, and BookmarksFolderFinderImpl.

Every method has:

findX_ByABC

OrganizationFinderImpl semi mimics this pattern, but leaves plenty of findByABC mixed with findX_ByABC.

I don't want to mimic a pattern halfway. We either go all the way, or use another existing pattern like Dynamic Query.

Hope that's more informative.

Thx.

**Comment by pei-jung** [comment]
Thanks for the explanation @brianchandotcom. That makes sense.

I agree the code looks cleaner with the use of DynamicQuery. I'd like to use the Dynamic Query pattern if possible. The challenge I'm facing with DynamicQuery is creating a dynamic query which depends on the mapping table `Users_Orgs`.

```
SELECT
    User_.userId
FROM
    User_
INNER JOIN
    Users_Orgs ON (Users_Orgs.userId = User_.userId)
WHERE
    Users_Orgs.organizationId = ?
```

Every [DynamicQueryFactoryUtil.forClass](https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/dao/orm/DynamicQueryFactoryUtil.java#L24-L42) method requires the `Class` param, so we can't just pass in the portal class loader. The only way I can think of to get access to the `Users_Orgs` table is to create a service for it. Adding the following to the service.xml

```
<entity name="Users_Orgs" local-service="true" remote-service="false">
  <column name="userId" type="long" primary="true" />
  <column name="organizationId" type="long" />
</entity>
```

so that we can do something like

`DynamicQuery dynamicQuery = DynamicQueryFactoryUtil.forClass(Users_Orgs.class, PortalClassLoaderUtil.getClassLoader());`

However, this is not something we've done in Liferay before. I don't know if this approach is right, and it seems too much to create a new service just for doing a query. I think it's more straightforward to do this kind of queries with Custom SQL.

**Comment by brianchandotcom** [comment]
@pei-jung Come find me tomorrow? I see your point about it needing a real ".class" and not just a class loader.

Then let's find the cleanest way of updating the existing finder methods. Thx.

**Comment by pei-jung** [comment]
Sure, I'll go talk to you tomorrow. Thanks, @brianchandotcom!

**Pull request closed without merging**
