### PR TITLE
LPS-118935 BaseCTDisplayRenderer

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
See https://github.com/Preston-Crary/liferay-portal/pull/1142#issuecomment-675643692

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@Preston-Crary can you run "gw buildLang" on the 2 modules, and also BaseCTDisplayRenderer to com.liferay.change.tracking.spi.display

It doesn't need to be in a base package.

Thx @Preston-Crary

**Comment by Preston-Crary** [comment]
Please see https://github.com/Preston-Crary/liferay-portal/pull/1147

**Pull request closed without merging**
