### PR TITLE
Lps 72928

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@david-truong @anitaderiane @mhan810
Please see my comment at https://issues.liferay.com/browse/LPS-72928?focusedCommentId=1069442&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1069442

Since this is all about being developer friendly, it is hard to say how friendly is friendly enough. To me this is enough, but you may think otherwise. Please try it out and let me know if anything else is needed.

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@shuyangzhou something broke after the CSS Builder change.

I thought I merged it in properly, can you take a look? Thx.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/50189

**Comment by shuyangzhou** [comment]
ci:retest

**Pull request closed without merging**
