### PR TITLE
LPS-78772

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@michaelhashimoto @petershin, this one should be failing SF test, but it's not (I committed changes to SF without the `auto SF` commit)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/107748a456...d10645cb79

**Comment by brianchandotcom** [comment]
@hhuijser I published this, ran "ant setup-sdk", but somehow Gradle is not picking up the new SF because it's not changing anything?

@ithildir fyi

**Comment by petershin** [comment]
@brianchandotcom - You'll also need to run the commands that Hashi added to [build-test-batch.xml](https://github.com/liferay/liferay-portal/blob/master/build-test-batch.xml#L3151-L3155)

```
portal: ant compile install-portal-snapshots
portal/modules/util/source-formatter: ..\..\..\gradlew deploy
```

**Comment by michaelhashimoto** [comment]
@petershin @hhuijser - Yeah, <code>ci:test:sf</code> is only running against code that was changed based off of this line:
https://github.com/liferay/liferay-portal/blob/master/build-test-batch.xml#L3281

Is there a way to change it to check everything on SF module changes?

**Comment by petershin** [comment]
Sent a patch to Hugo: https://github.com/hhuijser/liferay-portal/pull/3214

**Pull request closed without merging**
