### PR TITLE
LPS-109192 batch generator

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@mtambara @shuyangzhou this is new:

```
    [exec] java.lang.NoClassDefFoundError: org/springframework/web/context/support/ServletContextAwareProcessor
     [exec] 	at org.springframework.web.context.support.AbstractRefreshableWebApplicationContext.postProcessBeanFactory(AbstractRefreshableWebApplicationContext.java:169)
     [exec] 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:529)
     [exec] 	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401)
     [exec] 	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292)
     [exec] 	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
     [exec] 	at com.liferay.portal.spring.context.PortalContextLoaderListener.lambda$contextInitialized$0(PortalContextLoaderListener.java:290)
     [exec] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [exec] 	at java.lang.Thread.run(Thread.java:745)
     [exec] Caused by: java.lang.ClassNotFoundException: Illegal access: this web application instance has been stopped already. Could not load [org.springframework.web.context.support.ServletContextAwareProcessor]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
     [exec] 	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1373)
     [exec] 	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1224)
     [exec] 	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1186)
     [exec] 	... 8 more
     [exec] Caused by: java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [org.springframework.web.context.support.ServletContextAwareProcessor]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
     [exec] 	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1383)
     [exec] 	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1371)
     [exec] 	... 10 more
     [echo] Waiting for ht
```

LPKG error on startup. I wonder if it had to do with the ASM change.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@nhpatt I backported this to 7.1.x.

**Comment by nhpatt** [comment]
Thanks!

**Comment by shuyangzhou** [comment]
@brianchandotcom see https://github.com/brianchandotcom/liferay-portal/pull/85935, caused by https://github.com/brianchandotcom/liferay-portal/commit/cd2b15b8e72a11dcd6b835a83e1336e471d7eee0

**Pull request closed without merging**
