### PR TITLE
Lps 86406

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8dd49ce966...066405be42

**Comment by brianchandotcom** [comment]
@Preston-Crary please backport! Thx.

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/65369

**Pull request closed without merging**
