### PR TITLE
LPS-90749 SF

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @brianchandotcom,

@ambrinchaudhary needs to add stuff to the `bulk-rest` api. As soon as the new api's are ready and merged (@nhpathh) we will sync them with the new features and delete the old ones.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ca41c4e242...c8bdb06f67

**Comment by brianchandotcom** [comment]
@ambrinchaudhary see 7e6d34af2bf8926aa89d9cd5e6465669ef300992 and c8bdb06f671161d6d98acd5c9b956a900cd09ec2

**Pull request closed without merging**
