### PR TITLE
LPS-77721 It should be true by default

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by pyoo47** [comment]
ci:test

**Comment by pyoo47** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7a13bf9adb...f52727aae8

**Comment by brianchandotcom** [comment]
@ealonso this looks wrong to me:

```
href="/o/layout-taglib/contextual_sidebar/ContextualSidebar.css
```

We always prefix with the PortalUtil.getStaticResourceURL or themeDisplay.getCDNHost()

In ContextualSidebarTag.java, we use:

```
		sb.append("<link data-senna-track=\"temporary\" href=\"");
		sb.append(PortalUtil.getPathModule());
		sb.append("/layout-taglib/contextual_sidebar/ContextualSidebar.css");
		sb.append("\" rel=\"stylesheet\">");
```

I wonder if getPathModule is what you want?

**Comment by jbalsas** [comment]
Hey @brianchandotcom, @ealonso, we will move this ourselves as we transfer the tag into either `frontend-taglib` or `clay-taglib`.

We couldn't do it last week because it was going to conflict with other incoming PRs, but we will take care of it before the end of the week, so that link will be gone soon.

Thanks!

**Pull request closed without merging**
