### PR TITLE
LPS-67399 Part 1 - Rename organization finder methods to match findX_ByABC

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @jorgeferrer @drewbrokke

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:close

**Comment by brianchiu** [comment]
@pei-jung @drewbrokke

I've closed this because all the functional batches and many other batches have failed. There is a version mismatch of some sort causing a startup error.

````
     [exec] org.osgi.framework.BundleException: Could not resolve module: com.liferay.wiki.service [503]
     [exec]   Unresolved requirement: Import-Package: com.liferay.exportimport.content.processor.base; version="[2.0.0,3.0.0)"
     [exec]     -> Export-Package: com.liferay.exportimport.content.processor.base; bundle-symbolic-name="com.liferay.exportimport.service"; bundle-version="4.0.0"; version="2.0.0"; uses:="com.liferay.exportimport.content.processor,com.liferay.exportimport.kernel.lar,com.liferay.portal.kernel.exception,com.liferay.portal.kernel.model,com.liferay.portal.kernel.repository.model,com.liferay.portal.kernel.util"
     [exec]        com.liferay.exportimport.service [334]
     [exec]          Unresolved requirement: Import-Package: com.liferay.portal.kernel.service.persistence; version="[1.3.0,2.0.0)"
     [exec] 
     [exec] 	at org.eclipse.osgi.container.Module.start(Module.java:429)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1252)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1224)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:512)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:361)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:313)
     [exec] 00:40:42,747 ERROR [fileinstall-/opt/dev/projects/github/liferay-portal/bundles/osgi/modules][org_apache_felix_fileinstall:112] Exiting the JVM 
     [exec] org.osgi.framework.BundleException: Could not resolve module: com.liferay.wiki.service [503]
     [exec]   Unresolved requirement: Import-Package: com.liferay.exportimport.content.processor.base; version="[2.0.0,3.0.0)"
     [exec]     -> Export-Package: com.liferay.exportimport.content.processor.base; bundle-symbolic-name="com.liferay.exportimport.service"; bundle-version="4.0.0"; version="2.0.0"; uses:="com.liferay.exportimport.content.processor,com.liferay.exportimport.kernel.lar,com.liferay.portal.kernel.exception,com.liferay.portal.kernel.model,com.liferay.portal.kernel.repository.model,com.liferay.portal.kernel.util"
     [exec]        com.liferay.exportimport.service [334]
     [exec]          Unresolved requirement: Import-Package: com.liferay.portal.kernel.service.persistence; version="[1.3.0,2.0.0)"
     [exec] 
     [exec] 	at org.eclipse.osgi.container.Module.start(Module.java:429)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1252)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1224)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:512)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:361)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:313)
````

**Comment by pei-jung** [comment]
Thanks for pointing that out, @brianchiu. I'll take a look at it.

**Pull request closed without merging**
