### PR TITLE
LPS-91222 attachment tests

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by nhpatt** [comment]
Hi @jpince! Why did it closed directly?

**Comment by nhpatt** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Very nice @nhpatt see ab65edb952ace971d69a80ddcb5ef6da0f8fc669 eb2772c28b664b03839bc752bef61f1c1ed6ff5d 77c0957d59595972bb3ded8cbc68ffb3eb7315f4 and a2b0fe060551140ea3294093a37ea2354b81bac8

I backported the HttpImpl changes to 7.1.x and 7.0.x, and the Vulcan changes to 7.1.x.

**Comment by nhpatt** [comment]
Thanks! :D

**Pull request closed without merging**
