### PR TITLE
LPS-60657 Require link in link to layout page type

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@evannagayama please fix poshi and resend? Thx.

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
@epgarcia this one actually looks like a bug. I'll email you.

**Comment by epgarcia** [comment]
Ok, I'll take a look to it! Thanks!

**Pull request closed without merging**
