### PR TITLE
LRQA-46603 | master

### PR DESCRIPTION
**Pull request by patriciajeanperez**
https://issues.liferay.com/browse/LRQA-46603

Master only

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:reopen

**Comment by jpince** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jpince** [comment]
ci:close @brianchandotcom pushed upstream https://github.com/liferay/liferay-portal/compare/3f2fba5a30e48de070f006e5aabe4afc936d4598...a50180db50f53f86c6a96fadb396d5a7fce4a645

@patriciajeanperez thanks

**Pull request closed without merging**
