### PR TITLE
LPS-84974 Auto SF

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso, @pavel-savinov

**Comment by jkappler** [comment]
ci:reopen

**Comment by jkappler** [comment]
Hi @brianchiu, @kyle-miho, the error doesn't seem to be related to the PR, would you mind taking a look please?

Thanks!

**Comment by kyle-miho** [comment]
ci:test:relevant

**Pull request closed without merging**
