### PR TITLE
LPS-152441 Create foundations for managing cache mechanisms in composed URLs

### PR DESCRIPTION
**Pull request by john-co**
Manually forwarded since `ci:forward` attempts encountered unrelated test failures in https://github.com/liferay-frontend/liferay-portal/pull/2165#issuecomment-1123075800

cc/ @izaera

### CODE REVIEW

**Comment by izaera** [comment]
@brianchandotcom This is a revamp of the AbsoluteURLBuilder API in the hope that we can boost it to create proper URLs from now on, and keep augmenting it as we use it. Hopefully we willl grow a central place to decide how URLs are composed and thus remove a lot of the issues that appear, from time to time, related to this.

**Comment by brianchandotcom** [comment]
@izaera let's chat Monday morning BRL time to go over this PR. I sent you an invite.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c983064cc7...e64e97af31

**Comment by brianchandotcom** [comment]
@izaera just minor changes in upstream

**Pull request closed without merging**
