### PR TITLE
LRQA-66289 Use higher memory slaves when testing clustering

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:reopen

**Comment by vicnate5** [comment]
Backports
https://github.com/brianchandotcom/liferay-portal-ee/pull/34185
https://github.com/brianchandotcom/liferay-portal-ee/pull/34186
https://github.com/brianchandotcom/liferay-portal-ee/pull/34187

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3f812f2068...8e80ff99fe

**Comment by brianchandotcom** [comment]
@vicnate5 can you send me a follow up pull to sort this?

```
(testray.main.component.name == "Clustering" AND license.required != "true") OR \
```

**Pull request closed without merging**
