### PR TITLE
LPS-103034 Add companyId field where is missing

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
The same error in the CI is happening in other pulls such as https://github.com/brianchandotcom/liferay-portal/pull/79859

it seems an error creating the Oracle database.

**Comment by jpince** [comment]
@vicnate5

**Comment by brianchandotcom** [comment]
@achaparro please resend with fix by @vicnate5 (too scary to merge otherwise)

**Comment by vicnate5** [comment]
Will test before we resend

**Pull request closed without merging**
