### PR TITLE
LPS-66359 Update Wiki macro to use Panel#expand macro for Configuration panel

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:retest

**Comment by sharonchoi** [comment]
POSHI failures unrelated to pull, and should pass now that chat has been temporarily disabled here: https://github.com/liferay/liferay-portal/commit/254875003fc7747c1398497f246e0241a2c7a756

ci:retest

**Comment by brianchandotcom** [comment]
@adolfopa this doesn't make sense to me why we need to manually namespace anything? The goal of the taglibs were to namespace them for us so we would never have to manually namespace.

Can you Skype me to explain why we need to do this? Thx.

**Pull request closed without merging**
