### PR TITLE
LPS-56692

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@brianchandotcom thanks for the help

**Comment by brianchandotcom** [comment]
We can ignore the test. It's not from this. I"ll look at merging this.

**Comment by brianchandotcom** [comment]
@david-truong can you resend on top of https://github.com/david-truong/liferay-portal/pull/46

See 

```
			String includeDirNames =
				includeDirName + File.pathSeparator + new File(
					inputFileName).getParent();
```

Avoid all chaining. Thx.

**Comment by david-truong** [comment]
Sorry that line has existed since the beginning of the class and has always
bothered me but it passed through like a million SF without you changing so
I thought maybe that didn't count... good to know that's not allowed.

On Wed, Sep 23, 2015 at 10:39 PM, Brian Chan <notifications@github.com>
wrote:

> @david-truong <https://github.com/david-truong> can you resend on top of
> david-truong#46 <https://github.com/david-truong/liferay-portal/pull/46>
>
> See
>
>             String includeDirNames =
>                 includeDirName + File.pathSeparator + new File(
>                     inputFileName).getParent();
>
> Avoid all chaining. Thx.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/30453#issuecomment-142799051>
> .
>



-- 
David Truong
Product Manager
david.truong@liferay.com
Liferay, Inc

**Pull request closed without merging**
