### PR TITLE
LPS-100673 (+2 issues) FIX Ids Query is disregarding boost attribute

### PR DESCRIPTION
**Pull request by arboliveira**
**❌ ci:test:search - 19 out of 22 jobs passed in 1 hour 7 minutes 13 seconds 957 ms**
https://github.com/arboliveira/liferay-portal/pull/768#issuecomment-526367120

The single failure reported as unique is unrelated to this pull.

```
     [exec] Execution failed for task ':apps:flags:flags-taglib:packageRunTest'.
     [exec] > java.io.IOException: Process '[/opt/dev/projects/github/liferay-portal/build/node/bin/node, /opt/dev/projects/github/liferay-portal/modules/yarn-1.13.0.js, --production, false, --registry, http://mirrors.lax.liferay.com:4873, run, test]' finished with non-zero exit value 1
```

----

Authors: @BryanEngler @arboliveira
Reviewer: @arboliveira

----

_[Story] Search API: Additive Complex Query Parts_
https://issues.liferay.com/browse/LPS-100667

_[Bug] Ids Query is disregarding boost attribute_
https://issues.liferay.com/browse/LPS-100673

_[Bug] SearchResponseImpl is not null safe under certain API usage scenarios, leading to NullPointerException_
https://issues.liferay.com/browse/LPS-100676

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0d24581461...5d6a7038f4

**Comment by brianchandotcom** [comment]
@arboliveira see 5d6a7038f4e178a55bd66c0ebcc52d125d36c1ba

what about ES7?

**Comment by arboliveira** [comment]
@BryanEngler Can you side-port this to ES7 please? I'd probably just introduce a ton of conflicts with all the changes you're making locally. Thanks!

**Comment by BryanEngler** [comment]
will do, also FYI i have a task in the Elastic 7 epic to make sure that we side-port everything before we make the switch https://issues.liferay.com/browse/LPS-99681

**Pull request closed without merging**
