### PR TITLE
LRQA-53281 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-53281

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:test:depot

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1089c1b97a...39a35b722c

**Comment by brianchandotcom** [comment]
@austinchiang can we fix the existing broken Depot Poshi tests? We just added these and they're already broken. Thx.

**Comment by austinchiang** [comment]
@brianchandotcom Yep, on it today. There were several UX changes that went in last week that broke the tests

**Pull request closed without merging**
