### PR TITLE
LPS-56006 Update version

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
/cc @cgoncas @riccardo-ferrari @ivicac

hey @brianchandotcom, could you please also release a new version of the module to the repository?

For those of you who were having trouble trying tests with 6.2 this should fix it.

Feedback is welcome.

Thx to all.

**Comment by csierra** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Hi @csierra 

Pushed a new 1.0.1 release up. (the previous release was 1.0.0)

https://repository.liferay.com/nexus/content/repositories/liferay-releases-ce/com/liferay/com.liferay.ant.arquillian/

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/95d25a20ba...e9ba5a068a

**Comment by brianchandotcom** [comment]
@csierra I couldn't reference where this is being used?

**Comment by csierra** [comment]
This is used to test plugins, like calendar-portlet. I still see version 1.0.2 in the bnd, is that correct so any further development is made to 1.0.2?

/cc @riccardo-ferrari it is going to be 1.0.1 in the end, so don't use 1.0.2.

Thx.

**Pull request closed without merging**
