### PR TITLE
LPS-54852 prevent security checks from leaking out

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest (rerunning now that we have DB2 in place)

**Comment by rotty3000** [comment]
Please retry with this parameter added to the DB2 connection url

`allowNextOnExhaustedResultSet=true`

**Comment by rotty3000** [comment]
@shuyangzhou can you try the suggestion above please?

**Comment by rotty3000** [comment]
FYI, you can refer to this IBM report: http://www-01.ibm.com/support/docview.wss?uid=swg21461670

**Comment by shuyangzhou** [comment]
ci is fetching jdbc urls from test.properties, you can go there do any change you want then resend, next run will use the new url.

**Comment by rotty3000** [comment]
ok, great! I will try that!

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:retest

**Pull request closed without merging**
