### PR TITLE
LPS-74084

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-74084.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jpince** [comment]
ci:stop

**Comment by jpince** [comment]
ci:retest https://github.com/liferay/liferay-portal/commit/10d6be507011e7523b9f7e28186a5039cf22febf was needed in upstream for this pull to pass, sorry for the inconvenience

**Comment by jpince** [comment]
@jonmak08 there you go, got a green for you 👍

**Comment by jonmak08** [comment]
Thanks @jpince!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a30511a3b3...9d34e02c96

**Pull request closed without merging**
