### PR TITLE
LPS-59407 Redirect to the edit_entry or edit_folder in case of error so the values are still there and the user can correct those

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
I restarted this job on 10/15/15 at 12:32pm.

**Comment by michaelhashimoto** [comment]
This job got stuck.. so i made it unstuck. (I missed fixing a server before we restarted this job)

**Comment by michaelhashimoto** [comment]
I think this will likely finish in less than 20 minutes or so.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/93496f4b2f...9a9fe0a07e

**Comment by brianchandotcom** [comment]
Thx @izaera @sergiogonzalez

**Pull request closed without merging**
