### PR TITLE
LPD-18769 Workflow definition that use groovy script in any part of its content should not be published when script content are not allowed on its system

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@MarinhoFeliphe this can be JSON no?

```
		String content = definition.getContent();

		if (!_scriptManagementConfigurationHelper.
				isAllowScriptContentBeExecutedOrIncluded() &&
			content.contains("<script-language>groovy</script-language>")) {

```

Please talk to Praxedes because we made this JSON as well.

**Comment by MarinhoFeliphe** [comment]
> this can be JSON no?

Hey @brianchandotcom at this point the content always will be a XML due to [this line](https://github.com/liferay/liferay-portal/blob/1cac6c960563b9973b6347a63cd43b0d98cd58a9/modules/apps/portal-workflow/portal-workflow-kaleo-definition-impl/src/main/java/com/liferay/portal/workflow/kaleo/definition/internal/parser/XMLWorkflowModelParser.java#L89)

**Comment by MarinhoFeliphe** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@MarinhoFeliphe can you rename DefaultWorkflowValidator to XMLWorkflowValidator so it matches XMLWorkflowModelParser

Thx

**Comment by MarinhoFeliphe** [comment]
@brianchandotcom totally makes sense, resent here: https://github.com/brianchandotcom/liferay-portal/pull/148773

Thank you!

**Pull request closed without merging**
