### PR TITLE
LPS-96519 include graphql servlets in auth verifier filter tracker

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c97f4d3beb...ffa6355c1f

**Comment by nhpatt** [comment]
Thanks! :)

**Comment by brianchandotcom** [comment]
@nhpatt I backported this to 7.1.x (except for the change to AuthVerifierTest since it's not in 7.1.x)

Please test 7.1.x. Thx!

**Comment by nhpatt** [comment]
Will do! :)

**Comment by nhpatt** [comment]
@brianchandotcom works perfectly in 7.1 :D Thank you so much for the backport! :)

**Pull request closed without merging**
