### PR TITLE
LPS-43691 Rename feedLink and feedLinkMsg attributes for consistency

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e65e578957...fa41264223

**Pull request closed without merging**
