### PR TITLE
LPS-164281 Add the InfoPermissionProvider implementation for Objects

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-164281

@lfbesada 
@ealonso

### CODE REVIEW

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See [liferay-echo#7560](https://github.com/liferay-echo/liferay-portal/pull/9794)

:heavy_check_mark: ci:test:stable - 28 out of 28 jobs passed
:x: ci:test:relevant - 208 out of 224 jobs passed in 2 hours 25 minutes

**Comment by ozysouza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6c6b1fb39f...44acc6d2d6

**Comment by brianchandotcom** [comment]
@lfbesada just 44acc6d2d67d94f6ad88a74ab7740eb5c031ea2e

**Pull request closed without merging**
