### PR TITLE
LRQA-48331 | master

### PR DESCRIPTION
**Pull request by kmaria**
https://issues.liferay.com/browse/LRQA-48331

Backported to 7.1.x https://github.com/brianchandotcom/liferay-portal-ee/pull/24096

### CODE REVIEW

**Comment by kmaria** [comment]
ci:test:sf

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@kmaria you had one extra SF commit here that was not backported to 7.1.x. I went ahead and did it.

**Comment by kmaria** [comment]
@brianchandotcom  thank you

**Pull request closed without merging**
