### PR TITLE
LPS-96095

### PR DESCRIPTION
**Pull request by samuelkong**
@arthurchan35

### CODE REVIEW

**Comment by samuelkong** [comment]
ci:reopen

**Comment by samuelkong** [comment]
The SF errors should be resolved once https://github.com/brianchandotcom/liferay-portal-ee/pull/24946 is merged.

**Comment by jpince** [comment]
@samuelkong central-requirements error
`Redundant dependency detected in modules/apps/portal-search-solr7/portal-search-solr7-impl/build.gradle expected:<compileOnly group: "org.slf4j", name: "slf4j-api", version: "1.7.26"> but was:<testCompile group: "org.slf4j", name: "slf4j-api", version: "1.7.26">`

@vicnate5 if merged, this will cause a failure in central-requirements in all PRs. Options I see:
1. Close this pull and https://github.com/brianchandotcom/liferay-portal-ee/pull/24946 and wait until tomorrow
2a. Allow the pulls to merge and remove central-requirements from relevant
2b. Allow the pulls to merge and ask someone (e.g. Andre) to fix it in upstream

**Comment by vicnate5** [comment]
ci:close

**Comment by vicnate5** [comment]
@samuelkong Closed this and https://github.com/brianchandotcom/liferay-portal-ee/pull/24946 due to acceptance test failures above, please resend.

**Pull request closed without merging**
