### PR TITLE
Lps 90257

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
Reverted due to large performance regression.
@drewbrokke @pei-jung please rework on this and resend it through @slnn , thanks!
CC @dantewang @tinatian

**Comment by pei-jung** [comment]
Thanks @shuyangzhou

We need to revert the test as well https://github.com/brianchandotcom/liferay-portal/pull/68612.

**Comment by vicnate5** [comment]
ci:close

**Comment by vicnate5** [comment]
Resent with test change revert https://github.com/brianchandotcom/liferay-portal/pull/68712

**Pull request closed without merging**
