### PR TITLE
LPS-43624

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@brandizzi good find.  I added javadocs to clarify the original intent of those methods

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by mhan810** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b2e400355c...d9022abf86

**Comment by brianchandotcom** [comment]
@jhinkey will readd javadoc via LRDOCS-2137

**Pull request closed without merging**
