### PR TITLE
LPS-101135 | Avoiding global fetch on segments-web

### PR DESCRIPTION
**Pull request by andresfulla**
@jbalsas

### CODE REVIEW

**Comment by andresfulla** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Hey @andresfulla, I'm going to pick this up and push it in a different PR so I can enable the rule and see `sf` green without having to wait for those 2 to get synced!

**Comment by jbalsas** [comment]
ci:close

**Comment by jbalsas** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/78071!

**Pull request closed without merging**
