### PR TITLE
[TECHNICAL-SUPPORT] LPS-76708

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by jonathanmccann** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/62d3c030e1...7c79e0310f

**Pull request closed without merging**
