### PR TITLE
LPS-77132 Create a Util to facilitate saving and deleting ConfigAdmin configurations during tests

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-77132](https://issues.liferay.com/browse/LPS-77132).<br><br>@brianchandotcom please wait for the tests to finish<br><br>/cc @pei-jung, @Preston-Crary

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/79a506dc80...8b59fafa31

**Pull request closed without merging**
