### PR TITLE
LPS-78957

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test

**Comment by matethurzo** [comment]
failure is unrelated

**Comment by matethurzo** [comment]
ci:reopen

**Comment by matethurzo** [comment]
the failures are not related

**Comment by brianchandotcom** [comment]
@matethurzo sorry, one more thing

for 

```
public JSPNavigationItemList getJSPNavigationItemList() {
		String activeTab = ParamUtil.getString(_request, "tabs1", "processes");

		PortletURL renderURL = _renderResponse.createRenderURL();

		renderURL.setParameter("tabs1", "processes");

		NavigationItem processesNavigationItem = _createNavigationItem(
			activeTab.equals("processes"), renderURL,
			LanguageUtil.get(_request, "processes"));

		renderURL.setParameter("tabs1", "scheduled");

		NavigationItem scheduledProcessesNavigationItem = _createNavigationItem(
			activeTab.equals("scheduled"), renderURL,
			LanguageUtil.get(_request, "scheduled"));

		JSPNavigationItemList navigationItemList = new JSPNavigationItemList(
			_pageContext);

		navigationItemList.add(processesNavigationItem);
		navigationItemList.add(scheduledProcessesNavigationItem);

		return navigationItemList;
	}

```

It should be

public List<NavigationItems> getNavigationItems() {

as the method name.

The implementation should make use of the constructor so that each item is very lean.

"git grep new NavigationItem" and you'll see how it's used. Btw, JSPNavigationItemList should only be used in JSPs. This is a frontend java object, but it should use NavigationItemList where possible.

@hhuijser we need to SF enforce this.

See modules/apps/web-experience/staging/staging-processes-web/src/main/java/com/liferay/staging/processes/web/internal/display/context/StagingProcessesWebDisplayContext.java in this pull so that SF will enforce it in the future.

Thx

**Pull request closed without merging**
