### PR TITLE
Lps 68210

### PR DESCRIPTION
**Pull request by shuyangzhou**
@dantewang @slnn this should fix the MB performance regression, please check, thanks!

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by slnn** [comment]
Yes, it fix the performance regression on MB, detail test results please see email.

@shuyangzhou @dantewang

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
