### PR TITLE
LPS-81572 Replace search container and adapt view accordingly

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by jpince** [comment]
ci:close @brianchiu @anthony-chu please verify test failures

**Comment by ealonso** [comment]
ci:reopen

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@jpince, the issues in the PR are from a fix that was merged earlier today. I'm running relevant tests.

**Pull request closed without merging**
