### PR TITLE
LPS-70670

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@csierra fyi. We need a way to shutoff RTL for specific modules.  Arises from your change to: https://github.com/brianchandotcom/liferay-portal/pull/33718/commits/c844c05c8255781a9d260c5de6fda51f78ab2bfa

@hhuijser I need to add Liferay-RTL-Support-Required as a bnd header.  Where can we make that change?

@jbalsas, @dylan-rebelak @arboliveira fyi

**Comment by mhan810** [comment]
ci:retest

**Comment by csierra** [comment]
sure @mhan810... thx for the info 👍

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cf9857adc1...c0b7dc0a87

**Pull request closed without merging**
