### PR TITLE
LPS-82828

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
FYI @JorgeFerrer

**Comment by JorgeFerrer** [comment]
Hey @hhuijser, thanks for letting me know. I believe this is something that would be interesting to notify everybody in Engineering through loop and slack.

**Comment by hhuijser** [comment]
@brianchandotcom, please publish SB

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/72a12a0eb8...e3d8a02072

**Comment by brianchandotcom** [comment]
Very nice!!!

**Comment by brianchandotcom** [comment]
@hhuijser published ServiceBuilder.

**Comment by jpince** [comment]
@petershin I think this pull caused a semver failure, can you please run baseline?
```
     [echo]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [echo] = ================================================== ========== ========== ========== ========== ==========
     [echo] * com.liferay.portal.kernel.util                     MAJOR      8.0.0      8.0.0      9.0.0      VERSION INCREASE REQUIRED
     [echo] 	<   class      com.liferay.portal.kernel.util.ArrayUtil_IW
     [echo] 		+   method     split(java.lang.Object,int)
     [echo] 			+   return     java.lang.Object
     [echo] 	<   class      com.liferay.portal.kernel.util.StringUtil_IW
     [echo] 		+   method     equalsIgnoreCase(char,char)
     [echo] 			+   return     boolean
     [echo] 		+   method     read(java.lang.Class,java.lang.String)
     [echo] 			+   return     java.lang.String
     [echo] 	>   class      com.liferay.portal.kernel.util.Validator_IW
     [echo] 		-   method     isNotNull(java.lang.Object[])
     [echo] 			-   return     boolean
     [echo] 		-   method     isNull(java.lang.Object[])
     [echo] 			-   return     boolean
```

**Pull request closed without merging**
