### PR TITLE
LPS-118748 disable rest builder while we find a solution to the test …

### PR DESCRIPTION
**Pull request by javiergamarra**
…issue and publishing

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@nhpatt see c3793b78dea3915a2949e22b956a2b2c30b3dc74

**Comment by brianchandotcom** [comment]
@nhpatt waiting for your better fix

**Comment by nhpatt** [comment]
Yes, I'm checking how to skip it in this case.

**Pull request closed without merging**
