### PR TITLE
APIO-134 Restore existing APIs

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:test

**Comment by nhpatt** [comment]
ci:retest

**Comment by nhpatt** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@nhpatt can you resend on top of https://github.com/nhpatt/liferay-portal/pull/13

I see a lot of "Long classNameClassPK", but those are not the ClassNameClassPK object, so I'm not sure why it's called that or what the var name should be instead.

Please resend. Thx.

**Pull request closed without merging**
