### PR TITLE
LPS-109417 Missing data visualization

### PR DESCRIPTION
**Pull request by dgarciasarai**
CI here: https://github.com/andresfulla/liferay-portal/pull/223

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jpince can you have someone from QA look into

https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/369973/AXIS_VARIABLE=0,label_exp=!master/testReport/junit/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_PortalSmokeUpgrade_ViewPortalSmokeArchive7210_/

I'm seeing that a lot.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4e4588576a...5f90212e8d

**Comment by brianchandotcom** [comment]
@dgarciasarai see b7fc2ecd2eed5b891535c7551d2d116f1b9574c1

**Comment by jpince** [comment]
@brianchandotcom see https://issues.liferay.com/browse/LPS-109522, Search team will make improvements this week

**Comment by dgarciasarai** [comment]
Thanks! :)

**Pull request closed without merging**
