### PR TITLE
LPS-67986

### PR DESCRIPTION
**Pull request by Ithildir**
Hi,
Please let this pull finish.

Thank you!

### CODE REVIEW

**Comment by Ithildir** [comment]
@codyhoag: more changelogs, thank you! :blush:

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@codhoag this is pushed to upstream. Please see change logs. Thx!

**Comment by brianchandotcom** [comment]
@codyhoag this is pushed to upstream. Please see change logs. Thx!

**Pull request closed without merging**
