### PR TITLE
LPS-63716 rename tab in look and feel (from portlet configuration to general) 

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Hey @evenagayama

I have updated the functional tests here myself. can you please review and send to Brian any change?

thanks a lot!

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f627c3d73b...816e010059

**Comment by brianchandotcom** [comment]
Wiki test failure seems unrelated. @brianchiu

**Pull request closed without merging**
