### PR TITLE
LPS-106245 HashMapBuilder doesn't allow null. Fix in EditSegmentsEntryDisplayContext

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
I'm going to send another PR fixing the tests.

**Comment by dgarciasarai** [comment]
CI here https://github.com/dgarciasarai/liferay-portal/pull/139. It's this pull with tests fixed (https://github.com/brianchandotcom/liferay-portal/pull/82428)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c63e7634cb...709df226c9

**Comment by brianchandotcom** [comment]
@hhuijser fyi

**Pull request closed without merging**
