### PR TITLE
LPS-96566

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@wincent @jbalsas @ling-alan-huang

Disabling JSONPackageJSONCheck, because SF is complaining about pretty much every single `package.json` as a result of LPS-96566.
Do we still need that check? If so, how should we update the rules?

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by wincent** [comment]
@hhuijser:

> Disabling JSONPackageJSONCheck, because SF is complaining about pretty much every single `package.json` as a result of LPS-96566.
> Do we still need that check? If so, how should we update the rules?

I think we still need the check. Note that I actually updated the rules in that PR:

- In [JSONPackageJSONCheck.java](https://github.com/brianchandotcom/liferay-portal/pull/74436/files#diff-50a7550b55b533eabfc38a956b222fdf) I changed the check to verify the presence of `liferay-npm-scripts check` and `liferay-npm-scripts fix` (previously these were `liferay-npm-scripts lint` and `liferay-npm-scripts format`, respectively).
- If you look at all the package.jsons in that PR (eg. [this one](https://github.com/brianchandotcom/liferay-portal/pull/74436/files#diff-93afeb3d462a8838f79db1835d9e6f87)), `liferay-npm-scripts lint` and `liferay-npm-scripts format` changed correspondingly to `liferay-npm-scripts check` and `liferay-npm-scripts fix`.

So it's not clear to me why things would be failing. What's your analysis @hhuijser?

One other question while I have your attention. Does `JSONPackageJSONCheck` run as part of `ci:test:sf`?  (Because that was [green](https://github.com/brianchandotcom/liferay-portal/pull/74436#issuecomment-501345976) on my PR.)

**Comment by hhuijser** [comment]
Hey @wincent 

My bad! Sorry about that.
I did not see your changes to `JSONPackageJSONCheck` and I was running the previous version of SF on my end (which explains that your pull the test was green).

Can you split up your pulls in multiple commits next time, so changes like that are better visible?

**Comment by hhuijser** [comment]
I'll revert my commit.

**Comment by hhuijser** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/74474

**Comment by wincent** [comment]
@hhuijser: Ah, that explains it. Thanks for clarifying that.

Good point about small commits. In this case I wanted the change to be atomic so that there would be no intermediate broken states (like I would have had if I'd updated the test before the package.json files, or the package.json files before the test) — I think that's pretty important for bisectability and revertability — but I could have (should have) highlighted the change to `JSONPackageJSONCheck.java` in the PR summary.

One remaining issue: that check is probably failing/noisy in "master-private" right now — although I not sure if that turns up anywhere in our CI or if anybody is looking at it — and will be until we move the package.json scripts in that branch over to liferay-npm-scripts. We're planning on doing that once we've got Yarn working in "master-private" (imminently).

**Pull request closed without merging**
