### PR TITLE
LPS-59286 PACL test should allow postgresql driver to read system pro…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…perties

Fix for SQLTest failure in https://github.com/brianchandotcom/liferay-portal/pull/30836#issuecomment-146284983

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Thx @shuyangzhou how come it happens randomly?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bac6b1d3fc...4694e1a9e1

**Comment by shuyangzhou** [comment]
It depends on when the JDBC connection is created. Normally it should happen at an early phase, before PACL stuff kicks in, and it gets reused via the pool. But in that failure run, looks like it ended up requesting a new connection(for some reason the pool is not recycled in a timely manner), therefore tries to read the property again, then PACL rejected it.

Anyway, jdbc pool supposes to create new connections in the long run, the connection in pool won't live for ever. So that means, the same failure could happen in real system with postgresql driver. So making PACL to allow it reading postgresql system properties is the right thing to do.

**Comment by brianchandotcom** [comment]
Thx for the explanation @shuyangzhou

**Pull request closed without merging**
