### PR TITLE
LPS-68860 - Update Japanese translation

### PR DESCRIPTION
**Pull request by marcellustavares**
thx @daviddotzhang

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
This test is still running. Only 2 batches remain.
http://test-1-4/job/test-portal-acceptance-pullrequest-batch%28master%29/52221/
http://test-1-4/job/test-portal-acceptance-pullrequest-batch%28master%29/52219/

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by daviddotzhang** [comment]
@marcellustavares 

I saw you have rebased the build lang, could you share me how to configure the auto translations ?

**Comment by marcellustavares** [comment]
@daviddotzhang, you need to set up the Microsoft Translator for auto translations.

http://msdn.microsoft.com/en-us/library/hh454950

**Pull request closed without merging**
