### PR TITLE
LPS-86142 Live pages in Navigation Menu redirect to Staging site

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
cc:// @dacousalr, @ealonso

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
I'm going to try to trigger the pull request tests manually...

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0863376917...0a2e630d86

**Comment by brianchandotcom** [comment]
@laszlopap @jkappler Please send a backport to support for 7.1.x (like our normal support workflow). I'm no longer auto backporting pulls like this.

@jhendley @liferay @zsoltbalogh FYI.

Merged into master only.

**Pull request closed without merging**
