### PR TITLE
LPS-99197 Disconnect FragmentEntryLinksWithComments

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b4ef559d5c...8f375ac389

**Comment by brianchandotcom** [comment]
@4lejandrito Can you backport this?

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal-ee/pull/25811.

**Pull request closed without merging**
