### PR TITLE
LPS-76891

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test

**Comment by matethurzo** [comment]
@brianchandotcom test failures are not unique

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e98189338c...413d3ce818

**Comment by brianchandotcom** [comment]
@palius @matethurzo please review my changes in upstream f26681002d423209c8179c6134ad4fd9ba5274df and 413d3ce81831fbc1c2229320a2e737d64fe69630

thx

**Pull request closed without merging**
