### PR TITLE
LPS-73178

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@brianchandotcom this is the last batch.
These keys don't have a corresponding key in Language.properties

**Comment by hhuijser** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1b0ca90eff...a52ae42684

**Comment by brianchandotcom** [comment]
@hhuijser Not able to cherry pick.

**Pull request closed without merging**
