### PR TITLE
LPS-99736 - Replace icons in sync web

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f6cfd9f666...a67377588d

**Comment by brianchandotcom** [comment]
@jbalsas @marcoscv this broke my origin.. and doesn't compile. I reverted it in 1c6bc45

```
		<liferay-frontend:management-bar-button
			markupView="lexicon"
		/>
```

That tag does not have markupView

Please resend 

@jpince @randolph-do fyi

**Comment by jbalsas** [comment]
Hey @brianchandotcom, so sorry about that! We sent so many similar PRs that we missed this one. 

I've sent a proper fix to https://github.com/brianchandotcom/liferay-portal/pull/77136.

Thanks!

/cc @marcoscv-work

**Pull request closed without merging**
