### PR TITLE
Change "Show Steps Titles" to "Show Step Titles"

### PR DESCRIPTION
**Pull request by sez11a**
Noticed a bad button label in the [doc](https://github.com/sez11a/liferay-learn/pull/1440) from @ericthmoritsuka.

### CODE REVIEW

**Comment by sez11a** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6e080c8723...087246153c

**Comment by brianchandotcom** [comment]
@sez11a see 40951bca7865e67d5028595dd385c299266dcc13

**Comment by brianchandotcom** [comment]
@sez11a see 40951bca7865e67d5028595dd385c299266dcc13

Next time, please include an LPD.

**Comment by sez11a** [comment]
Won't https://github.com/brianchandotcom/liferay-portal/commit/40951bca7865e67d5028595dd385c299266dcc13 break the UI with a mismatched language key?

**Pull request closed without merging**
