### PR TITLE
LPS-71420 Regenerate rules

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by csierra** [comment]
will send back to @adolfopa

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/47968

**Pull request closed without merging**
