### PR TITLE
Lps 203939

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by lipusz** [comment]
Thank you for taking care of it, @shuyangzhou! :+1:

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f809529dd0...946214a01d

**Comment by brianchandotcom** [comment]
@ling-alan-huang can you SF enforce this change by @shuyangzhou ? Thx.

**Pull request closed without merging**
