### PR TITLE
LRQA-52072 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LRQA-52072

### CODE REVIEW

**Comment by john-co** [comment]
This allows js-unit and js-unit-private test batches to display individual jest failures on PR tester.

cc/ @jbalsas

**Comment by john-co** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8663e74053...fa869734a3

**Comment by brianchandotcom** [comment]
@john-co @petershin I didn't/couldn't backport the changes to build-test-batch.xml to 7.1.x

**Comment by brianwulbern** [comment]
yep, working on it.

**Comment by brianwulbern** [comment]
Sent here
https://github.com/brianchandotcom/liferay-portal-ee/pull/26585
https://github.com/brianchandotcom/liferay-portal-ee/pull/26592

**Pull request closed without merging**
