### PR TITLE
LPS-75798

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@brianchandotcom 

Reason for fix:
If we format custom sql and do simple SF adding/removing line breaks, stuff like this would break:
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/service/persistence/impl/OrganizationFinderImpl.java#L1179-L1185

**Comment by hhuijser** [comment]
ci:retest

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
Looks like test failures are showing up in other pulls as well?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b2e709a6f4...56d1868f51

**Pull request closed without merging**
