### PR TITLE
LPS-112628 Replace usages of div class="container" with clay:container in JSPs

### PR DESCRIPTION
**Pull request by wincent**
Manual foward from: https://github.com/wincent/liferay-portal/pull/258 (only [remaining CI failures](https://github.com/wincent/liferay-portal/pull/258#issuecomment-627418640) are marked as not unique).

Original message follows:

---

Hey @wincent, picking up from @eduardoallegrini here...

### In this PR

- As it stands from the Title, replace all occurrences of `div class="container*"` with our new `clay:container` tag.

### Context

Followup of https://github.com/brianchandotcom/liferay-portal/pull/88326 which was in itself https://github.com/wincent/liferay-portal/pull/245 and contained these key parts:

- [Implement clay:container tag](https://issues.liferay.com/browse/LPS-112620). Up to the final specs discussed at https://github.com/marcoscv-work/liferay-portal/pull/316#issuecomment-621905296 and based on [Define clay:container tag](https://issues.liferay.com/browse/LPS-112361)
- [Replace usages of aui:container with clay:container](https://issues.liferay.com/browse/LPS-112626).

#### History

Older than the universe, in fact, but here's a summary 😂 

- **Initial attempts**
    - https://github.com/eduardoallegrini/liferay-portal/pull/64
    - https://github.com/eduardoallegrini/liferay-portal/pull/65
    - https://github.com/eduardoallegrini/liferay-portal/pull/66
    - https://github.com/eduardoallegrini/liferay-portal/pull/67
    - https://github.com/eduardoallegrini/liferay-portal/pull/68
    - https://github.com/eduardoallegrini/liferay-portal/pull/69
    - https://github.com/eduardoallegrini/liferay-portal/pull/70
- **Split into modules**
    - [Part 1](https://github.com/eduardoallegrini/liferay-portal/pull/71)
    - [Part 2](https://github.com/eduardoallegrini/liferay-portal/pull/72)

### CODE REVIEW

**Comment by wincent** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c956589142...dc406dea9d

**Comment by brianchandotcom** [comment]
@jbalsas see dc406dea9d031fd3209834c64a6e1857faa9c69d we can just use liferayPortletResponse it works in all cases.

**Comment by brianchandotcom** [comment]
@jbalsas in case you're curious - util-taglib/src/com/liferay/taglib/portlet/DefineObjectsTag.java is the Java class that wires all the vars. You can take a peek there.

**Comment by jbalsas** [comment]
Thanks @brianchandotcom! Sent you some comments offline in case you want to followup on that one!

**Pull request closed without merging**
