### PR TITLE
SYNC-1418

### PR DESCRIPTION
**Pull request by mikemanyoung**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e018778406...b5345a286e

**Comment by brianchandotcom** [comment]
@shinnlok do you want me to do a releaes? If so, please email. Thx.

**Comment by brianchandotcom** [comment]
Nvm, you guys do your own releases right?

**Comment by shinnlok** [comment]
Yup, it's already released.

**Pull request closed without merging**
