### PR TITLE
LPS-148662 Migrate confirm uses cases to use openConfirmModal on JSPs

### PR DESCRIPTION
**Pull request by diegonvs**
Came from: https://github.com/brianchandotcom/liferay-portal/pull/122542
QA Approval: https://github.com/liferay-frontend/liferay-portal/pull/2691#issuecomment-1238659124
Added https://github.com/diegonvs/liferay-portal/commit/a6e35dd8481c2fe5f7da340abd734b0a99d65350, https://github.com/brianchandotcom/liferay-portal/commit/e4f6473108c3a1dcd96a866312b0f7c48d41fa16

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:reopen

**Comment by diegonvs** [comment]
Wait

**Comment by diegonvs** [comment]
ci:reopen

**Comment by diegonvs** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/41e0a3334b...dc40e79acf

**Comment by brianchandotcom** [comment]
@diegonvs see 22d7a4b0a9ad497ec4d21b0ccc7728ee779bb83e and dc40e79acfac1a79872f3b708d7b757df9f05ed8

@ling-alan-huang I believe we are sometimes escaping unnecessarily. See dc40e79acfac1a79872f3b708d7b757df9f05ed8

**Pull request closed without merging**
