### PR TITLE
LPS-95545 Remove renamed exception

### PR DESCRIPTION
**Pull request by brunofarache**

### CODE REVIEW

**Comment by brunofarache** [comment]
ci:reopen

**Comment by brunofarache** [comment]
ci:test:sf

**Comment by brunofarache** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by brunofarache** [comment]
ci:reopen

**Comment by brunofarache** [comment]
ci:test:sf

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e063a649f3...a5c83dfb88

**Comment by brianchandotcom** [comment]
@brunofarache much better, see a5c83df

**Pull request closed without merging**
