### PR TITLE
LPS-66570 add isActive method (third different approach to introduce this method)

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:reopen

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pyoo47 @michaelhashimoto @robert-frampton what's going on here? It's happening in every pull.

**Comment by pyoo47** [comment]
@brianchandotcom I think it's some kind of sass failure in the porygon theme.

```
     [exec] make: Leaving directory `/opt/dev/projects/github/liferay-portal/modules/apps/frontend-theme-porygon/frontend-theme-porygon/node_modules/gulp-metal/node_modules/node-sass/build'
     [exec] ../src/libsass/src/units.hpp:10: warning: 'Sass::PI' defined but not used
     [exec] make: *** [Release/obj.target/libsass/src/libsass/src/ast.o] Error 1
     [exec] gyp ERR! build error 
     [exec] gyp ERR! stack Error: `make` failed with exit code: 2
     [exec] gyp ERR! stack     at ChildProcess.onExit (/opt/dev/projects/github/liferay-portal/modules/apps/frontend-theme-porygon/frontend-theme-porygon/node_modules/gulp-metal/node_modules/node-gyp/lib/build.js:276:23)
     [exec] gyp ERR! stack     at emitTwo (events.js:106:13)
     [exec] gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
     [exec] gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
     [exec] gyp ERR! System Linux 2.6.32-042stab111.11
     [exec] gyp ERR! command "/opt/dev/projects/github/liferay-portal/modules/apps/frontend-theme-porygon/frontend-theme-porygon/build_gradle/node/bin/node" "/opt/dev/projects/github/liferay-portal/modules/apps/frontend-theme-porygon/frontend-theme-porygon/node_modules/gulp-metal/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
     [exec] gyp ERR! cwd /opt/dev/projects/github/liferay-portal/modules/apps/frontend-theme-porygon/frontend-theme-porygon/node_modules/gulp-metal/node_modules/node-sass
     [exec] gyp ERR! node -v v6.6.0
     [exec] gyp ERR! node-gyp -v v3.4.0
     [exec] gyp ERR! not ok 
     [exec] Build failed
```

**Comment by brianchandotcom** [comment]
@jorgediaz-lr can you rename:

GroupLocalServiceUtil#isActive(Group)

It is not immediately obvious from the method name how it is different from Group#isActive

Please rename GroupLocalServiceUtil#isActive(Group) to GroupLocalServiceUtil#isXYZActive(Group) where XYZ denotes the meaning of this method.

@juliocamarero fyi, clarity is important. Thx.

**Comment by brianchandotcom** [comment]
@pyoo47 we have a cache, and a version is missing. Can you bring it up to @stsquared99 asap? He needs to fix our local cache.

**Comment by stsquared99** [comment]
The cache has been updated. For future, I would recommend verifying the cache integrity before updating to new version.
Thanks

**Pull request closed without merging**
