### PR TITLE
LPS-62253 Apply lexicon to File entry types

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
cc @marcellustabares

**Comment by marcellustavares** [comment]
@rafaprax, can you check this commit? guess it's the same you have on your branch.

**Comment by marcellustavares** [comment]
Thanks for letting us know @robertoDiaz

**Comment by robertoDiaz** [comment]
Hey @marcellustavares, I'm also adding a new method to DDMDisplay interface (so implementations could pass the title)

**Comment by marcellustavares** [comment]
hey @robertoDiaz, could you double check https://github.com/marcellustavares/liferay-portal/pull/1160? I guess we fix the same thing :)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e4226e472f...495dcb9bd0

**Pull request closed without merging**
