### PR TITLE
WebSockets support: support for encoders/decoders

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by jpince** [comment]
ci:reopen

**Comment by brianchiu** [comment]
Failing poshi tests are firefox connection issues.

QA Engineering is investigating right now. See: https://issues.liferay.com/browse/LRQA-28169

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e08cb06b24...8eb326fc56

**Comment by brianchandotcom** [comment]
@migue @cgoncas please see my changes in upstream. Thx.

**Pull request closed without merging**
