### PR TITLE
LPS-63037 improvements for the customized layouts

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0a78675814...d76ff52ca7

**Comment by brianchandotcom** [comment]
@juliocamarero please see my changes in upstream. THx.

**Pull request closed without merging**
