### PR TITLE
LPS-65107 fix ordering by publishDate in asset publisher

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:stop

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Test failures. Please resend. @juliocamarero @eperezg Thx.

**Pull request closed without merging**
