### PR TITLE
LPS-145324 Remove aditional configs

### PR DESCRIPTION
**Pull request by kevenleone**

### CODE REVIEW

**Comment by kevenleone** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/112192

Without .env changes

**Comment by kevenleone** [comment]
ci:reopen

**Comment by kevenleone** [comment]
Both configs are a helper for development, but not required.

FAST_REFRESH=false
WDS_SOCKET_PORT=3000

We can discuss that later @brianchandotcom , @jairmedeiros if we really need to put this on .env

For now it's ok!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b93b3c600a...efadbdb8e4

**Comment by brianchandotcom** [comment]
@kevenleone see

```
	"name": "@liferay/site-initializer-customer-portal",
	"private": true,
	"scripts": {
		"build": "react-scripts build",
		"format": "eslint src --ext js --fix",
		"run-serve": "yarn build && npx serve ./build",
		"serve": "npx serve ./build",
		"start": "react-scripts start"
	},

```

vs.

```
	"name": "@liferay/site-initializer-raylife-d2c",
	"private": true,
	"scripts": {
		"build": "react-scripts build",
		"mock": "json-server -p 3333 -d 200 ./mock/db.json --routes ./mock/routes.json",
		"run": "yarn build && npx serve ./build",
		"serve": "npx serve ./build",
		"start": "react-scripts start"
	},
```

Should we make Raylife and OSB Customer Portal more similar?

**Pull request closed without merging**
