### PR TITLE
LPS-96625 Not needed

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
Just started reviewing :)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/82d9173622...79e72163dd

**Comment by brianchandotcom** [comment]
Merged and pushed upstream..

@4lejandrito there sure is a lot of duplicate code in here? I wish we could more easily add this to each module without duplicating so much code.

@jorgeferrer do you mind taking a quick look at how we're doing auto tagging? something seems off.

**Comment by JorgeFerrer** [comment]
Sure.

@4lejandrito <https://github.com/4lejandrito> let's look at this together
on Monday

**Comment by JorgeFerrer** [comment]
Hey @brianchandotcom ,
I went over this today with @4lejandrito and we both agreed that there is too much duplication. The root cause is that we have to account for all the combination of values of two independent variables: the type of service (GCloud, NLP, ...) and the type of asset (Blog Entry, File Entry, Journal Article). That means that when a new value for any of these variables appears, we have to create N classes (one for each of the values of the other variable).

How do we solve this? We need to change the implementation a bit so that we avoid having to create a class for each point in the matrix. We started writing the solution and have it almost working. The keys are:

1. We will have just one class to implement each type of service. It will be tied to AssetEntry so that the companyId can obtained from it.
2. We will have just one class for each asset type, which is able to extract the text out of it. 

We can then have code in one single place which creates all the combination of the two.

We still have one pending challenge though: the configuration. We are currently providing users with an option to enable or disable all possible combinations of the matrix and we want to continue providing that option. To do that, we need to do some improvements to the configuration framework so that it can be more dynamic and show all available options without needing a specific Configuration interface for them. We believe this shouldn't be too hard and Alejandro is going to do some research to find out how to do it.

Makes sense?

**Pull request closed without merging**
