### PR TITLE
LPS-78037

### PR DESCRIPTION
**Pull request by Ithildir**
Hi,
Please let this pull finish.

Thank you!

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@jbalsas @natecavanaugh any progress on the consistent failure in test-portal-acceptance-pullrequest-batch(master)/portal-frontend-js-jdk8 ?

**Comment by brianchandotcom** [comment]
Merged..

**Comment by jbalsas** [comment]
Hey @brianchandotcom, it should've been fixed in https://github.com/brianchandotcom/liferay-portal/pull/56814. Tests started here before the other got merged. It should be green now.

**Pull request closed without merging**
