### PR TITLE
LPS-138329 Patch the module-info.class file out of

### PR DESCRIPTION
**Pull request by shuyangzhou**
jackson-annotations.jar and jackson-core.jar to avoid failed startups on
older (but supported) versions of JBoss/Wildfly that can't handle .jars
with module-info.class files in them.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ad97957a23...5cbf9f3fa0

**Comment by brianchandotcom** [comment]
@mbowerman @shuyangzhou see 519fd653 for naming

@shuyangzhou do we really need the transitive setting? 7259b521 @mbowerman can you double check?

@shuyangzhou if we don't need it, can you remove the transitive: false except for where we really do need it (please assign it to someone in your team)

@mbowerman I assume you will reference this jar in an older branch?

**Comment by shuyangzhou** [comment]
@brianchandotcom the "transitive false" is not required in this case, because jackson-core and jackson-annotations just happen to be not having any dependencies. I think @mbowerman copy and paste it from other third party module.
But for other cases where the patching lib does have dependencies, this is required. It is because of logic like this https://github.com/liferay/liferay-portal/blob/master/modules/third-party/asm-analysis/build.gradle#L23 the ```zipTree``` needs the target to be a single file, when dependencies are present, it will be multiple files. In this asm-analysis case, if you remove it, it will fail with:
```
* What went wrong:
Could not determine the dependencies of task ':third-party:asm-analysis:jarPatched'.
> Expected configuration ':third-party:asm-analysis:compileOnly' to contain exactly one file, however, it contains more than one file.
```

**Comment by mbowerman** [comment]
> @mbowerman I assume you will reference this jar in an older branch?
Yes, I will send a pull request to 7.1.x to replace the existing jackson-annotations and jackson-core jars in lib/portal with this one.

@shuyangzhou Thanks for the detailed explanation about "transitive". I didn't understand what it was doing, as you said I just copied/pasted it from elsewhere where we were doing something similar.

**Comment by mbowerman** [comment]
Sent 7.1.x pull request here: https://github.com/liferay/liferay-portal-ee/pull/27027

**Comment by brianchandotcom** [comment]
@shuyangzhou so technically, having transitive: false EVERYWHERE in third-party is the best option right?

Should I ask alan to SF enforce this to always add transitive false?

**Comment by shuyangzhou** [comment]
yes, probably better to default to transitive false for third party patch modules.

**Comment by ling-alan-huang** [comment]
Sent SF changes to @shuyangzhou for review: https://github.com/shuyangzhou/liferay-portal/pull/10580

**Pull request closed without merging**
