### PR TITLE
LPS-63695 SCOPE_GROUP root model-resource is missing by default, custom plugins will fail permission checking 

### PR DESCRIPTION
**Pull request by topolik**
Hi Brian,

resending https://github.com/brianchandotcom/liferay-portal/pull/38485. 

https://issues.liferay.com/browse/LPS-63695

It wasn't system.packages.extra.mf this time but `com.liferay.portal.kernel.security.permission` super-package version change. 

Staging-security module implements PermissionChecker from that package and need to update referenced version to be compatible with what is provided in runtime.

Thanks.

### CODE REVIEW

**Comment by topolik** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop (I'm already merging this)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2b3c832509...4e7ad03b36

**Comment by brianchandotcom** [comment]
@topolik see 4e7ad03b3669f8f5a0c268de22b1c81e983f255b

We didn't need to make the build.gradle change. See my other changes in upstream as well. Thx!

**Comment by brianchandotcom** [comment]
Weird.. your last commit was needed

Fixed it in 95a8c1150a2f7319544b84411d32c4c1a6329e39 with a slightly different syntax

**Comment by topolik** [comment]
@brianchandotcom: an explanation if you want to understand - thanks to `system.packages.extra.mf` system bundle exports the package as 1.1.0 now,  1.0.0 is no longer available in runtime. Therefore bnd must use latest portal-kernel.jar to generate correct version import for staging-security or it won't start because it won't find 1.0.0. bnd also cannot create version range to fix it because staging-security implements PermissionChecker so even `minor` change to `com.liferay.portal.kernel.security.permission` package is breaking change - only `micro` version range can be supported ... [1.1.0,1.2.0)

**Pull request closed without merging**
