### PR TITLE
LPS-60194

### PR DESCRIPTION
**Pull request by natecavanaugh**

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
i got these ones unstuck. One of our servers was causing this to stall.

Results should be up soon.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@brunobasto @inacionery @brianchiu lots of broken Poshi tests. Please resend.

**Comment by brianchiu** [comment]
@kenjiheigel
Can you help out Nate with this one?

**Comment by vicnate5** [comment]
@kenjiheigel @brianchiu @brunobasto It is a calendar locator issue. I can take care of it.

**Comment by vicnate5** [comment]
@brunobasto @inacionery This pull actually causes a regression. The user can no longer add an event by clicking on the scheduler. 

Can you guys take another look at this before fixing the locators?

The reason the tests are failing is a separate issue, the path file https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/paths/plugin/calendar/Calendar.path needs to be updated with the correct locators for the `SCHEDULER_EVENT_*` paths. It looks like `//div[contains(@class,'calendar-portlet-event')` is now found at to `//div[contains(@class,'scheduler-event')`.

**Pull request closed without merging**
