### PR TITLE
LPS-60636 Fix Test

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:retest

**Comment by zxdgoal** [comment]
ci:retest

**Comment by zxdgoal** [comment]
@epgarcia Thank you for correcting the test case for me.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/52a613b160...dee18ec874

**Pull request closed without merging**
