### PR TITLE
LPS-64875 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by jbalsas**
Hi Brian,

This would require publishing new versions of `gradle-plugins-js-transpiler` and `gradle-plugins`.

Thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jbalsas I merged this in, but with a real gradle cache now. Also, even in your fake cache, you didn't need to make one for the soy bridge since no one references it directly.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c9a7e1d370...ad554cf650

**Comment by jbalsas** [comment]
Thanks a lot, @brianchandotcom! 

Sorry about that, I was actually on another branch where I needed the soy bridge... that actually reminds me that we should probably commit the soy-portlet demo asap, so I'll see to it.

Thanks again!

**Pull request closed without merging**
