### PR TITLE
LPS-56271 Turn on postgresql integration

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @willnewbury @mtambara  and @tomwang2011

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a37650bf7a...72e3f0b473

**Comment by shuyangzhou** [comment]
@brianchandotcom just making an example, see https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-backend%28master%29/168/group=37,label_exp=!test-1-2/testReport/com.liferay.portal.service/RoleLocalServiceTest/

You should see every test method show up twice, if you click inside, you should the db type as postfix. Like TEST-com.liferay.portal.service.RoleLocalServiceTest-mysql and TEST-com.liferay.portal.service.RoleLocalServiceTest-postgresql

So on seeing a failing test, click inside will talk you which DB it is failing against.

**Comment by brianchandotcom** [comment]
It went fairly fast? 35 min? The other SF failure I just fixed.

**Comment by shuyangzhou** [comment]
Well, currently we only do the portal-impl integration test, once we add in the arquillian one, we will see a huge build time bump up.

**Comment by brianchandotcom** [comment]
Got it... thx Shuyang

**Pull request closed without merging**
