### PR TITLE
LPS-82444 Baseline

### PR DESCRIPTION
**Pull request by jkappler**
Hi @brianchandotcom, we had to change the model of this module for some changes that we have to make. Since the jars are already published a major version increase was requested. Is there any way to avoid this since no one uses version 1?

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by brianchandotcom** [comment]
Hey @jkappler 

you're sending this to 7.1.x too right?

**Comment by jkappler** [comment]
yes, in a couple of minutes @brianchandotcom

**Comment by brianchandotcom** [comment]
Thanks @jkappler 

If you major version change 7.1.x, I need you to major version change master even more

Master is already one major version greater than 7.1.x, so we have to keep that delta.

**Comment by jkappler** [comment]
so this should be 3.0.0 instead of 2.0.0 @brianchandotcom? And the one for 7.1.x should be 2.0.0?

**Pull request closed without merging**
