### PR TITLE
Lps 194989 9 1

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c0df4a2537...1808c8131c

**Comment by brianchandotcom** [comment]
@slnn @shuyangzhou see changes in my origin. Can you retest?

**Comment by slnn** [comment]
Hi @brianchandotcom 

I have tested this pull it worked well on my side.

/cc @shuyangzhou 

Thanks
Lily

**Pull request closed without merging**
