### PR TITLE
LPS-99957 Update to alloyeditor v2.0.9

### PR DESCRIPTION
**Pull request by wincent**
Includes bugfixes described here:

https://github.com/liferay/alloy-editor/releases/tag/v2.0.9

- feat: run formatting and lint checks in CI
- fix: check whether height and width style exist before using
- fix: make IE also preserve other browers' image height styling

### CODE REVIEW

**Comment by wincent** [comment]
@john-co: I've tested this locally and think it's good to merge, but seeing as you've recently been working on updated editor QA test plans, this might be one to put through its paces (especially given the discussion about round-tripping to/from IE over on [this PR](https://github.com/brianchandotcom/liferay-portal-ee/pull/26040)).

**Comment by john-co** [comment]
ci:test:bundle

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/32f6e192e8...e6bf0d1d1c

**Comment by john-co** [comment]
Thanks @wincent! Looks good to me.

**Comment by wincent** [comment]
Great, thanks @john-co.

**Pull request closed without merging**
