### PR TITLE
LPS-61501 use liferay-ui:icon to avoid custom js code

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest still seems broken

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bad37c102c...df09ebaea5

**Pull request closed without merging**
