### PR TITLE
LPS-142121 - Site initializer asset vocabulary integration tests

### PR DESCRIPTION
**Pull request by joseabelenda**

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/96ca188e31...058ecd7563

**Comment by brianchandotcom** [comment]
@joseabelenda see my changes in https://github.com/brianchandotcom/liferay-portal/commits/058ecd7563194eec7772f30d4d3721a35b807ca8

**Comment by joseabelenda** [comment]
@nicolas-sss

**Pull request closed without merging**
