### PR TITLE
LPS-58862 better break than deprecate in this situation

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
I restarted this job on 10/15/15 at 12:24pm.

**Comment by michaelhashimoto** [comment]
This job got stuck.. so i made it unstuck. (I missed fixing a server before we restarted this job)

**Comment by michaelhashimoto** [comment]
I think this will likely finish in about an hour cause the one that got stuck was a long job.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/338858e88d...93496f4b2f

**Pull request closed without merging**
