### PR TITLE
LPS-68118 Move MDR tests

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
not related ci:reopen

**Comment by matethurzo** [comment]
ci:reopen

**Comment by anthony-chu** [comment]
These Poshi failures are due to a VNC failure that has been reported under [LRQA-28169](https://issues.liferay.com/browse/LRQA-28169), and this causes Firefox not to start on these nodes. This issue is currently being investigated and worked on.

**Comment by brianchiu** [comment]
@alee8888
XSS failure is not a firefox connection issue and could be real. Can you take a look?

**Comment by alee8888** [comment]
The XSS failure looks like a fluke. The test failed the success message assertion but no alert dialog box was caught and no exceptions were thrown in the console.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
