### PR TITLE
LPS-60781 Remove redundant add menu and change '+' button to go to the form to add a role with the role type on the current tab

### PR DESCRIPTION
**Pull request by alee8888**

### CODE REVIEW

**Comment by alee8888** [comment]
@brianchandotcom @pei-jung 
This is combined PR for roles admin changes (LPS-60781) and Poshi function test fixes (LRQA-22476).

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/45b7421342...55c4be5398

**Pull request closed without merging**
