### PR TITLE
LPS-94624 SF

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test

**Comment by julien** [comment]
ci:reopen

**Comment by julien** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:close @julien @izaera @eduardoallegrini please fix:
1. semver errors
```
[exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS
[exec] = ================================================== ========== ========== ========== ========== ==========
[exec]   com.liferay.portal.util                            UNCHANGED  4.0.0      3.1.0      3.1.0      EXCESSIVE VERSION INCREASE
[exec] 	-   version    3.1.0
[exec] 	+   version    4.0.0
```
2. sf errors - newline characters added
```
     [java] 1: ./portal-kernel/src/com/liferay/portal/kernel/util/packageinfo expected:<version 10.0.0[]> but was:<version 10.0.0[
     [java] ]>
     [java] 2: ./portal-impl/src/com/liferay/portal/util/packageinfo expected:<version 4.0.0[]> but was:<version 4.0.0[
     [java] ]>
```
3. I am also concerned about the compile error, as I don't see it anywhere else
```
     [exec] > Task :apps:change-tracking:change-tracking-rest:compileJava FAILED
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/change-tracking/change-tracking-rest/src/main/java/com/liferay/change/tracking/rest/internal/resource/CTEntryResource.java:167: error: incompatible types: inferred type does not conform to equality constraint(s)
     [exec] 		return Page.of(
     [exec] 		              ^
     [exec]     inferred: Object
     [exec]     equality constraints(s): Object,CTEntryModel
```

Please feel free to reach out to @john-co if you need help interpreting test results

**Comment by jpince** [comment]
oh, I just noticed the ci:test results, so I guess the compile error isn't an issue

**Comment by izaera** [comment]
@jpince We have reviewed (@julien and me) that error but we don't see why it is complaining. I think we haven't changed anything in portal-impl or portal-kernel :thinking: .

**Comment by izaera** [comment]
I meant the semver error.

**Comment by izaera** [comment]
Sorry, actually the `packageinfo` files have been changed, but for some reason we didn't see those files before in github :man_shrugging:

**Pull request closed without merging**
