### PR TITLE
LPS-67830 Allow administrators to configure captcha using System Settings, allowing export and import of configurations

### PR DESCRIPTION
**Pull request by alee8888**
@pei-jung @drewbrokke @jorgeferrer
This combines the commits for LPS-67830 and Poshi functional test fixes.

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by alee8888** [comment]
Test aborted at the top level job at here, so going to retrigger a retest.

```
Build "test-portal-acceptance-pullrequest-batch(master)" completed at https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/86954/. UNSTABLE
java.io.IOException: Server returned HTTP response code: 401 for URL: https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/86954/testReport/api/json?tree=childReports%5Bchild%5Burl%5D,result%5Bsuites%5Bcases%5BclassName,name,status%5D%5D%5D%5D
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1627)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at com.liferay.jenkins.results.parser.JenkinsResultsParserUtil.toString(JenkinsResultsParserUtil.java:971)
	at com.liferay.jenkins.results.parser.JenkinsResultsParserUtil.toJSONObject(JenkinsResultsParserUtil.java:840)
	at com.liferay.jenkins.results.parser.JenkinsResultsParserUtil.toJSONObject(JenkinsResultsParserUtil.java:831)
	at com.liferay.jenkins.results.parser.JenkinsResultsParserUtil.toJSONObject(JenkinsResultsParserUtil.java:804)
	at sun.reflect.GeneratedMethodAccessor67.invoke(Unknown Source)
```

**Comment by alee8888** [comment]
ci:retest

**Comment by brianwulbern** [comment]
ci:reopen

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@alee8888, these results look more realistic

**Comment by alee8888** [comment]
Closing as it looks like additional test fixes will be needed.

**Pull request closed without merging**
