### PR TITLE
LPS-176887 - Revert of LPS-173047

### PR DESCRIPTION
**Pull request by lucasperj**
[LPS-173047](https://issues.liferay.com/browse/LPS-173047) caused [LPS-176887](https://issues.liferay.com/browse/LPS-176887) that modified the logic that adds anonymous users. 

Getting : 
> LIFERAY_ERROR: HHH000315: Exception executing batch [java.sql.BatchUpdateException: Duplicate entry '20099-Anonymous20099_1@liferay.com-0' for key 'IX_6C9F41D8'], SQL: insert into User_ (mvccVersion, ctCollectionId, uuid_, externalReferenceCode, companyId, createDate, modifiedDate, defaultUser, contactId, password_, passwordEncrypted, passwordReset, passwordModifiedDate, digest, reminderQueryQuestion, reminderQueryAnswer, graceLoginCount, screenName, emailAddress, facebookId, googleUserId, ldapServerId, openId, portraitId, languageId, timeZoneId, greeting, comments, firstName, middleName, lastName, jobTitle, loginDate, loginIP, lastLoginDate, lastLoginIP, lastFailedLoginDate, failedLoginAttempts, lockout, lockoutDate, agreedToTermsOfUse, emailAddressVerified, status, userId) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
[exec] LIFERAY_ERROR: Duplicate entry '20099-Anonymous20099_1@liferay.com-0' for key 'IX_6C9F41D8'
[exec] LIFERAY_ERROR: Duplicate entry '20099-Anonymous20099_1@liferay.com-0' for key 'IX_6C9F41D8' 

Observed at : 

- Websphere 9.0 + Chrome 100.0 + MySQL 5.7 + Oracle JDK 8 64-Bit + CentOS 7 64-Bit
- JBoss 7.3 + Chrome 100.0 + MySQL 5.7 + Oracle JDK 8 64-Bit + CentOS 7 64-Bit
- Weblogic 12c + Chrome 100.0 + MySQL 5.7 + Oracle JDK 8 64-Bit + CentOS 7 64-Bit
- Tomcat 9.0 + Chrome 100.0 + MySQL 5.7 + Oracle JDK 8 64-Bit + CentOS 7 64-Bit
- Tomcat 9.0 + Chrome 100.0 + Microsoft SQL Server 2017 + Oracle JDK 8 64-Bit + CentOS 7 64-Bit
- Tomcat 9.0 + Chrome 100.0 + MariaDB 10.2 + Oracle JDK 8 64-Bit + CentOS 7 64-Bit

### CODE REVIEW

**Comment by lucasperj** [comment]
ci:reopen

**Comment by vicnate5** [comment]
@istvansajtos

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/de06a50d7c...1eae19a581

**Comment by brianchandotcom** [comment]
I reverted this in the U66 temp branch too.

**Pull request closed without merging**
