### PR TITLE
LPS-126352 Automate Test Scenario 14.08

### PR DESCRIPTION
**Pull request by emanuelfisilva**
[LPS-126352](https://issues.liferay.com/browse/LPS-126352) - Create a test for validate the translations on a Web Content created with all fields including nested ones

### CODE REVIEW

**Comment by emanuelfisilva** [comment]
For SF please check https://github.com/emanuelfisilva/liferay-portal/pull/59#issuecomment-789712357

**Comment by emanuelfisilva** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@thaisfrota @MoryAlvesBR fyi

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1db5c1ecd8...58df846617

**Pull request closed without merging**
