### PR TITLE
LPS-193342

### PR DESCRIPTION
**Pull request by alessandromalves**
https://issues.liferay.com/browse/LPS-193342

cc.: @ealonso

### CODE REVIEW

**Comment by alessandromalves** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/13307

✔️ ci:test:stable - 31 out of 31 jobs passed
❌ ci:test:relevant - 428 out of 516 jobs passed in 5 hours 16 minutes

**Comment by alessandromalves** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1fd4d19238...667f071793

**Comment by brianchandotcom** [comment]
@ealonso @alessandromalves see 667f071793414235c4260590d6dd62bf47b7ac98

**Pull request closed without merging**
