### PR TITLE
LPS-64627

### PR DESCRIPTION
**Pull request by natecavanaugh**

### CODE REVIEW

**Comment by dustinryerson** [comment]
Hey @natecavanaugh, a previous commit for this fix also used ```isNaN()```: https://github.com/brianchandotcom/liferay-portal/pull/39338/commits/09e1ea2f44233c8d20351e46b2fbbc3a1f4cc528#diff-1ad2f307ca967b71dac6d9fa38581166R327

Would you like me to send a separate pull to fix that usage?

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0c999c1f93...927f5e971d

**Comment by brianchandotcom** [comment]
@dustinryerson can you send another pull/backport what's needed for isNaN?

**Pull request closed without merging**
