### PR TITLE
LPS-55278 SF

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@inacionery @brunobasto jsp test error in modules-unit. Please resend.

**Comment by brunobasto** [comment]
@brianchandotcom Sorry, my source formatter wasn't working by the time was reviewing this pull request. Will resend.

**Comment by brunobasto** [comment]
Resent: https://github.com/brianchandotcom/liferay-portal/pull/30072

**Pull request closed without merging**
