### PR TITLE
LPS-67352

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@brianchandotcom

This one only changes private vars.
I have a pull ready that also does this for public/protected vars.

It touches about 15 files or so. All it does is adding 'final' or 'static' to constants.
It would cause me to change the version numbers (semantic versioning issue), but it wouldn't break API?

What do you think?

Example: https://github.com/liferay/liferay-portal/blame/master/modules/apps/push-notifications/push-notifications-api/src/main/java/com/liferay/push/notifications/util/comparator/PushNotificationsDevicePlatformComparator.java#L27

**Comment by hhuijser** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/99992a61cb...b878a0858a

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
