### PR TITLE
LPS-117004 Remove validation of empty data list view

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:reopen

**Comment by jeyvison** [comment]
@cvanut as we talked, i'm sending this directly because of the failure in the forms test.

cc:/ @alexcandidos

**Comment by brianchandotcom** [comment]
```
JSONObject page = (JSONObject)jsonArray.get(0);

				JSONArray rows = (JSONArray)page.get("rows");

```

Please resend. THx.

**Pull request closed without merging**
