### PR TITLE
LPS-160475 Fix the cascade deletion type for M-M relationship

### PR DESCRIPTION
**Pull request by marcelabc**
Follow up: https://github.com/brianchandotcom/liferay-portal/pull/122899
Objects PR: https://github.com/liferay-objects/liferay-portal/pull/1040

Some tests failed after the review, I fixed :+1: 
I'm sending directly since there are integration tests failing.
The CI reported 1 test, and it is flaky: https://testray.liferay.com/home/-/testray/case_results?tab=runs&testrayBuildId=1974482296

Thank you!

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:reopen

**Comment by marcelabc** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2cebf0b31f...4acfb3ed1e

**Comment by brianchandotcom** [comment]
@marcelabc see 4acfb3ed1e31069a4acea33367f5d5df63fb8549

**Comment by brianchandotcom** [comment]
@marcelabc I need you to help me write a test for 

```
			PersistedModelLocalService persistedModelLocalService =
				_persistedModelLocalServiceRegistry.
					getPersistedModelLocalService(
						_systemObjectDefinitionMetadata.getModelClassName());

			for (BaseModel<T> baseModel : relatedModels) {
				persistedModelLocalService.deletePersistedModel(
					(PersistedModel)baseModel);
			}
```

Because not all system objects may have implemented the delete method properly.

**Pull request closed without merging**
