### PR TITLE
LPS-130446 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-130446

This is only for master.

@ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure cases are unrelated to changes in this PR.
See https://github.com/liferay-echo/liferay-portal/pull/5048
❌ ci:test:stable - 9 out of 10 jobs passed
❌ ci:test:relevant - 21 out of 26 jobs passed in 1 hour 57 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/254fdf5199...880952a2ef

**Comment by brianchandotcom** [comment]
@ealonso see 4d0ab89f263ffefd303ce658d9f9681f636c870e and 880952a2ef107ca6d98c9988da04a18fd51b5a55

**Pull request closed without merging**
