### PR TITLE
LPS-202774 add openliberty to app.server.properties

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:reopen

**Comment by vicnate5** [comment]
@david-truong @petershin

**Comment by brianchandotcom** [comment]
@david-truong @vicnate5 Who is the product manager sponsoring this? I think this goes against the direction of having fewer app servers. @marco-leo fyi

I'd also want to push toward JDK 11 and up only now.

**Comment by david-truong** [comment]
This is part of that movement.  OpenLiberty is the new version of Websphere. Legacy Websphere is stuck on JDK8.  The goal is to support this and drop Websphere.

**Pull request closed without merging**
