### PR TITLE
LPS-53064

### PR DESCRIPTION
**Pull request by epgarcia**
@marcellustavares (first commit)
@matethurzo (second commit)

### CODE REVIEW

**Comment by matethurzo** [comment]
:+1:

**Comment by matethurzo** [comment]
Hey @epgarcia,

The ExportImportHelperUtil test seems to be failing because of this, can you please check it? Thanks!

**Comment by brianchandotcom** [comment]
Not merging @epgarcia 

Genuine test failure. Thx

**Comment by epgarcia** [comment]
Ok, I'll check it! Thanks!

**Pull request closed without merging**
