### PR TITLE
LPS-73140 Puts propagated request param under "requestParams" injected data

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brunobasto** [comment]
Hey @xbrianlee, the failing unit tests don't look like they are related to this pull. They look like failures on the database/indexing layers. Is that right?

**Comment by xbrianlee** [comment]
ci:reopen

Hi @brunobasto, I don't think your changes caused the failures in this pull. But I haven't seen any UserIndexerTest failures recently, so just to be safe I'm going to retest.

**Comment by xbrianlee** [comment]
ci:retest

Please wait for this retest to finish before merging.

**Comment by brunobasto** [comment]
Thanks, @xbrianlee!

**Comment by xbrianlee** [comment]
ci:close

Closing until we figure out why these integration tests are failing.

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
hey @xbrianlee, do you have any idea why this is failing? Is it safe to merge?

**Comment by xbrianlee** [comment]
Hi @jbalsas,
The failures in https://github.com/brianchandotcom/liferay-portal/pull/49887#issuecomment-311460405 were caused by orphaned data that didn't get cleaned up, so search is finding results when its not supposed to find anything. I'm not sure why this is happening with the changes in this PR.

However, I did notice one thing. The PR tests were taking 5 hours to run with these commits (compare to only 2 hours on other PRs). Also locally running source-format takes an extremely long time (I left it running for 20 minutes before aborting).

I'll test this branch again this morning.

**Comment by xbrianlee** [comment]
@jbalsas This PR isn't safe to merge. These changes are still causing test to take very long to run. Source-format takes longer than 30 minutes locally.

**Comment by jbalsas** [comment]
Thanks Brian, I'll take a look to figure out why tomorrow!

**Comment by jbalsas** [comment]
@xbrianlee, I've contacted @hhuijser to ask about it, since sourceformatter gets stuck in the `portal-soy-template` module, but I don't really know why :/

**Pull request closed without merging**
