### PR TITLE
LPS-95687 Avoid repeated Class.getSimpleName() calls.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
CC @slnn

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@pyoo47 what's going on?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bc88dc30ad...3b153a9626

**Comment by brianchandotcom** [comment]
@shuyangzhou renamed in 3b153a9

**Comment by brianchandotcom** [comment]
@pyoo47 I figured out the SF issue.. I just had to publish a new one. Please ignore error.

**Pull request closed without merging**
