### PR TITLE
LPS-71476

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest (the LPKG errors may be unique to this pull)

**Comment by mhan810** [comment]
ci:reopen

Unrelated failures

**Comment by brianchandotcom** [comment]
@mhan810 LPKG errors happened twice now, and only for this pull. Please resend? @shuyangzhou Mike may need your help. Thx.

**Comment by jpince** [comment]
Here's the error:
```
init-build-app:
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:240: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:805: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1299: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/modules/build-app.xml:50: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/modules/build-app.xml:52: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/modules/build-app.xml:365: Unable to load file: java.io.FileNotFoundException: /opt/dev/projects/github/liferay-portal/modules (Is a directory)
```
I see the same error in all 3 of the failing lpkg tests.

https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/99260/AXIS_VARIABLE=0,label_exp=!master/consoleFull

**Comment by shuyangzhou** [comment]
@mhan810  seems you added a top level apps folder "modules/apps/portal-mobile-device-recognition-provider-fiftyonedegrees", for all top level ones, we need an "app.bnd" for lpkg generation. So the missing file is "modules/apps/portal-mobile-device-recognition-provider-fiftyonedegrees/app.bnd".
Every other apps folder has it, you can just copy one to modify its content.

**Comment by mhan810** [comment]
@shuyangzhou cool will give that a try.


Cheers,



-m

**Pull request closed without merging**
