### PR TITLE
LPS-56851

### PR DESCRIPTION
**Pull request by samuelkong**

### CODE REVIEW

**Comment by samuelkong** [comment]
**6.2.x:** https://github.com/brianchandotcom/liferay-portal-ee/pull/10598

**Comment by samuelkong** [comment]
ci:retest

**Comment by samuelkong** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/561d4e1902...cf6bd63631

**Pull request closed without merging**
