### PR TITLE
LPS-92452 Generating the URLs with the portlet providers

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @patriciajeanperez, @austinchiang,

I've done some renaming in sharing. I've applied it to your tests too (https://github.com/brianchandotcom/liferay-portal/pull/69883/commits/450853f691951bbf711d1ed5d38d9facc690c61c). Hopefully they'll keep working.

**Comment by 4lejandrito** [comment]
Fixing conflicts and resending in 3, 2, 1...

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/69891.

**Comment by austinchiang** [comment]
Nice job @4lejandrito !!!

**Pull request closed without merging**
