### PR TITLE
LPS-75064 Apache Tika parsing runs for uploaded LAR files

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey @sergiogonzalez 

Following your suggestion in https://github.com/IstvanD/liferay-portal/pull/48#issuecomment-341443336 I have added initialization to MimeTypesImplTest's setUp, and the test is passing now.

Best regards,
István

### CODE REVIEW

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@sergiogonzalez minor SF in 3d3efc7b9397bda08a867f058f1c11f162c5752f @IstvanD fyi

**Pull request closed without merging**
