### PR TITLE
LPS-67658

### PR DESCRIPTION
**Pull request by Ithildir**
Hi,
Please let this pull finish.

Thank you!

### CODE REVIEW

**Comment by Ithildir** [comment]
Hi @brianchandotcom and @codyhoag,

I started adding `CHANGELOG.markdown` files for the Gradle plugins, what do you think?

**Comment by codyhoag** [comment]
Hey @Ithildir 

My two cents...

As far as the change log formatting is concerned, I think it is OK. Two minor things I'd suggest with the two change logs in this PR:

- I would punctuate with a period after every bullet. The link you referred to does this, and I personally like finishing off bullet points for consistency.
- Remove the comma after `Gradle 2.14` in both change logs. 

I'd be happy to make these changes once the change logs are merged, if need be. :smiley:

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/92a3190401...b218eb3342

**Comment by brianchandotcom** [comment]
@codyhoag can you update the change logs? Thx. I pushed it upstream.

**Comment by codyhoag** [comment]
@brianchandotcom sure thing. I'll have those edits sent ASAP.

**Pull request closed without merging**
