### PR TITLE
LPS-76693 buildLang

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4b4208c692...7d05f63bf9

**Comment by jpince** [comment]
@ealonso @pavel-savinov this pull caused a compile failure. It was obscured in this pull request because of another failure in OAuth that was later resolved. Brian said he plans to revert the changes in this pull.
`     [exec] Caused by: org.apache.jasper.JasperException: file:/opt/dev/projects/github/liferay-portal/modules/apps/web-experience/site-navigation/site-navigation-menu-web/build/unzipped-jar/META-INF/resources/view.jsp(21,0) PWC6130: According to the TLD or the tag file, attribute siteNavigationMenuId is mandatory for tag navigation-menu`
[Console](https://test-1-22.liferay.com/job/test-portal-acceptance-upstream-dist(master)/AXIS_VARIABLE=tomcat,label_exp=!master/35/console)

**Comment by brianchandotcom** [comment]
@ealonso I didn't catch that this doesn't compile. Reverting... can you resend @ealonso ? Thx.

**Pull request closed without merging**
