### PR TITLE
Pr/21 lps 47199

### PR DESCRIPTION
**Pull request by arbetts**

### CODE REVIEW

**Comment by arbetts** [comment]
ci:retest

**Comment by arbetts** [comment]
ci:retest

**Comment by arbetts** [comment]
ci:retest

**Comment by arbetts** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/477fd02f26...54bfeb84b9

**Comment by brianchandotcom** [comment]
Woops. I meant great job on this pull! :)

**Pull request closed without merging**
