### PR TITLE
LPS-84376 Add build files

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
cc @Preston-Crary

**Comment by Preston-Crary** [comment]
Can we leave out 7b02b31 and update your code to keep it as languageId.  We want to get away from having all of the Locale -> languageId transformations.  We know we're going to the Database, let's just use the languageId. That way you can use the generated updateAssetListEntryLocalizations method without having to copy the map.

**Comment by jkappler** [comment]
Hi @preston-crary. We'll have to do the transformation at some point since we get a Map<Locale, String> from the service context. Also, there are other places when we do the transformation at service level. Would that mean that we have to change those too in the future for consistency?

I'll close the PR to avoid it being merged for the moment

**Comment by jkappler** [comment]
ci:close

**Comment by jkappler** [comment]
Btw, will send a follow up to FriendlyURLEntryLocalServiceImpl since it doesn't use the methods to update localizations

**Comment by Preston-Crary** [comment]
HI @jkappler,

"We'll have to do the transformation at some point since we get a Map<Locale, String> from the service context."

I'm not seeing any Map<Locale, String> in ServiceContext, can you link the location?

Ideally, performance wise we would remove all the Map<Locale, String> usages.  Locale has a slow hashCode() implementation compared to String and anytime we want to interact with the database we need the String instead.  It's also faster to get the Locale from the String then the other way around.  We may never get to the point where everything is consistent but to me it's better to have some inconsistency and be heading a good direction then enforce consistency in a bad direction.

@brianchandotcom The performance impact isn't huge so if we really want the consistency over performance I can update the ServiceBuilder to generate Map<Locale, String> methods.

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Hey @preston-crary. We won't localize the entity after all, after talks with our UX. Sorry for all the back-and-forth

**Pull request closed without merging**
