### PR TITLE
LPS-194196

### PR DESCRIPTION
**Pull request by liulukiwi**
https://liferay.atlassian.net/browse/LPS-194196

@ealonso

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:reopen

**Comment by liulukiwi** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/13401

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/11c857d847...315361e466

**Comment by brianchandotcom** [comment]
@ealonso see 315361e46639ba6ef0750b24c456b5f01bbcad25

**Pull request closed without merging**
