### PR TITLE
LPS-68336 Revert "LPS-64206 Create new command to upgrade events."

### PR DESCRIPTION
**Pull request by marcellustavares**
Brian this is the upgrade from events-display to calendar, master version.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by marcellustavares** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@marcellustavares please resend

```
SourceFormatterTest.testSourceFormatter
```

**Comment by marcellustavares** [comment]
resent to https://github.com/brianchandotcom/liferay-portal/pull/43806

**Pull request closed without merging**
