### PR TITLE
master-bc-3319

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LIFERAYQA-12650

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@kiyoshilee @michaelhashimoto

Source formatter is catching something in the portal-ext.properties?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b1c0ac6e41...3d880d9d5d

**Comment by michaelhashimoto** [comment]
@brianchiu - we removed this update. thanks for letting us know!

**Pull request closed without merging**
