### PR TITLE
LPS-75055 Auto

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/38d95de48d...ee80f57c9f

**Comment by brianchandotcom** [comment]
@ealonso see 3aa3a14f583f94a11bdff263d1afa12ab9485995

@shuyangzhou this lpkg error is happening a lot, fyi.

**Comment by shuyangzhou** [comment]
@brianchandotcom it is caused by this https://github.com/brianchandotcom/liferay-portal/pull/51923

the new bnd update costs a lot more memory. Do we really need this? I have been very busy with the petra-concurrent thread pool rewriting these couple days. I am having Matt to try to play with CI heap settings to overcome this, but it might not be doable since we are really low on usable memory.

Can we go back to the old version for now? I will need a while before I can dig into this to see why bnd is costing this much more memory.

**Pull request closed without merging**
