### PR TITLE
LPS-80370 Autogenerated

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test

**Comment by matethurzo** [comment]
@brianchandotcom the errors are not related

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d28aceab47...2f9ab2a056

**Comment by brianchandotcom** [comment]
@matethurzo see my changes in upstream. I made one important rename.

Thx.

**Pull request closed without merging**
