### PR TITLE
LPS-74379 Make test pass

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:retest

**Comment by izaera** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@shuyangzhou more DLApp test failures.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/072924d935...1554a27bc7

**Comment by brianchandotcom** [comment]
@izaera 

Please see upstream for my changes. Also, I backported 3cc0064cece43ed904fc0dd43dca878cee87f114 to 7.0.x because I believe it's a real bug fix.

Thx.

**Comment by shuyangzhou** [comment]
@brianchandotcom this was caused by https://github.com/brianchandotcom/liferay-portal/pull/52102
And there is no easy fix of it, as there is a design problem here.
It was ok due to syn-event was inside portal context, meaning it was used portal tx manager. Now as a standalone module, it has its own tx manager. (Just as any other sb enabled module, so this change by itself is not a problem).

But dl-sync-event has this special things:
1) https://github.com/liferay/liferay-portal/blob/master/modules/apps/collaboration/document-library/document-library-sync-service/service.xml#L34 a single column unique finder
2) https://github.com/liferay/liferay-portal/blob/master/modules/apps/collaboration/document-library/document-library-sync-service/src/main/java/com/liferay/document/library/sync/service/impl/DLSyncEventLocalServiceImpl.java#L38 a fetch protection to make difference between add and update.
This combination will lead to row level locking, and on DBs with MVCC like HSQL will result in a fast failure on concurrent fetching.

Although logically this failure is correct, but in pratice it is too overkilled. As under concurrent adding with different entries, we know they will never conflict with each other, but the db does not know. And when they overlap on flushing with selecting, DB's MVCC will reject the selecting, resulting in this HSQL serializatin failure.

To me, the most logical thing to do is to remove DLSyncEventLocalServiceImpl.addDLSyncEvent()'s fetch protection. It is no longer working properly due to the OSGi extraction. But that will affect exist usages, and I think we should leave this decision to sync team.

CC @adolfopa @sergiogonzalez @dejuknow

**Pull request closed without merging**
