### PR TITLE
LPS-172424 Remove Stream usages in portal-search-elasticsearch7-impl part 1

### PR DESCRIPTION
**Pull request by dantewang**
FYI @shuyangzhou @tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/eb7d5deb25...fe85effd11

**Comment by brianchandotcom** [comment]
@julschong @dantewang can we use TransformUti.transformToArray here?

```
		Object[] elasticsearchValues = new Object[values.size()];

		for (int i = 0; i < values.size(); i++) {
			elasticsearchValues[i] = _toElasticsearchValue(values.get(i));
		}

		xContentBuilder.array(field.getName(), elasticsearchValues);
```

**Comment by julschong** [comment]
@brianchandotcom Hi Brian,
[I orignally used transformToArray here, but it failed unit test here: DefaultElasticsearchDocumentFactoryTest.testNullValues](https://github.com/liferay-core-infra/liferay-portal/pull/3156#issuecomment-1404347308) because transformToArray method does not add in null values and in this use case, we want to add in the null values

**Pull request closed without merging**
