### PR TITLE
LPS-147705 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-147705

This is only for master.

@victorg1991

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure cases are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/7936
❌ ci:test:stable - 31 out of 37 jobs passed
❌ ci:test:relevant - 31 out of 38 jobs passed in 2 hours 52 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4acfa45f1e...334658e3a3

**Comment by brianchandotcom** [comment]
@victorg1991 @Tim-Cao see 580806e7

**Pull request closed without merging**
