### PR TITLE
LPS-70397 Let Guest access discussion struts paths

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @adolfopa

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d490fa0fd3...0ba1d290ce

**Comment by brianchandotcom** [comment]
@adolfopa @sergiogonzalez see 0ba1d290ceb20e4b92c52d5e3518e6dd1ff9778d

Can you change *AuthPublicPath* to "*.internal.auth.public.path"

That's the safest.

We have lots of uses of *.portlet.path" so I forced *.action.path" to also be *.portlet.path", but both are wrong.

The good news is that they are all internal packages right now, so your change should be easy. Please send a follow up pull @adolfopa 

Thx.

**Comment by adolfopa** [comment]
Sure. See https://github.com/brianchandotcom/liferay-portal/pull/46753

**Pull request closed without merging**
