### PR TITLE
LPS-63568

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 fyi?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1d9f2cdbbc...6bdba966e5

**Comment by pyoo47** [comment]
Not sure how this happened. I've created a [ticket](https://issues.liferay.com/browse/LRQA-22938) to resolve this issue.

**Comment by pyoo47** [comment]
I'm borrowing this pull to do some testing.. please ignore any further results posted here.

**Pull request closed without merging**
