### PR TITLE
LPS-81805

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@brianchandotcom the failure is not related to pull

**Comment by jpince** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1c73f7bebd...3cc908e951

**Comment by brianchandotcom** [comment]
Thx @mhan810 !

**Pull request closed without merging**
