### PR TITLE
LPS-155004 Adding context thread information on upgrade logs for LXC to identify those lines

### PR DESCRIPTION
**Pull request by LuisOrtiz89**
LPS-155004Properties

### CODE REVIEW

**Comment by LuisOrtiz89** [comment]
ci:reopen

**Comment by LuisOrtiz89** [comment]
Hi @brianchandotcom, check this comment https://github.com/liferay-uniform/liferay-portal/pull/446#issuecomment-1169351727 where @kyle-miho reviewed the failures in the CI.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f463f1592c...ff9224a8c2

**Comment by brianchandotcom** [comment]
Very nice @LuisOrtiz89 see my many tiny changes. Thx.

**Pull request closed without merging**
