### PR TITLE
LPS-162282 User enumeration attack with password expiration.

### PR DESCRIPTION
**Pull request by ces-totrinh**
I create this PR based on the [comment](https://github.com/liferay-appsec/liferay-portal/pull/834#issuecomment-1242044821).
Please help take a look. Thanks.
Ticket: https://issues.liferay.com/browse/LPS-162282
cc @arthurchan35 @chileces

### CODE REVIEW

**Comment by tototrinh** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@tototrinh can you add an integration test?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a05ff186bc...bb35d0aa9f

**Comment by brianchandotcom** [comment]
@tototrinh I reverted this

```
<column name="maxFailure" type="int" />
```

Doesn't your change render that column useless?

**Pull request closed without merging**
