### PR TITLE
LPS-138581 Site Initializer - _addCPDefinitions

### PR DESCRIPTION
**Pull request by joseabelenda**

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/af6d5403eb...ccd61e4810

**Comment by brianchandotcom** [comment]
ci:reopen 

Very nice, let's review tomorrow.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5334250bdc...83780a02d7

**Pull request closed without merging**
