### PR TITLE
LPS-102248 | master

### PR DESCRIPTION
**Pull request by ces-sontruong**
Hi @brianchandotcom, This PR is resent based on your comment at #123346. Please help me to review it again. Thank you!

### CODE REVIEW

**Comment by sontruongces** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@sontruongces I didn't mean WebKeys literally. I mean use that pattern.

This WebKeys should be part of that module only

See modules/apps/site-navigation/site-navigation-item-selector-web/src/main/java/com/liferay/site/navigation/item/selector/web/internal/constants/SiteNavigationItemSelectorWebKeys.java

type:

git ls-files **WebKeys**

**Comment by brianchandotcom** [comment]
@sontruongces please resend, see my change above. May be it should even be a getter/setter and not a webkey.

**Comment by sontruongces** [comment]
Hi @brianchandotcom, So I should declare this WebKey here: modules/apps/user-associated-data/user-associated-data-web/src/main/java/com/liferay/user/associated/data/web/internal/constants/UADWebKeys.java. But I little bit confused about your comment: 
`May be it should even be a getter/setter and not a webkey.`
I asked my team but they have no idea. Could you be more detail?
Sorry for bothering you!

Thanks!

**Pull request closed without merging**
