### PR TITLE
Lps 75969

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/68c08a1a8d...46408f3d5c

**Comment by brianchandotcom** [comment]
@Preston-Crary please backport. Thx.

**Comment by brianchandotcom** [comment]
@Preston-Crary I didn't remove the commit to remove from whitelist since it hasn't been backported to 7.0.x yet

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal-ee/pull/19193

**Pull request closed without merging**
