### PR TITLE
LPS-103170 Publish dxp demo projects to the public repository

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/196c532f22...2c464573b9

**Comment by brianchandotcom** [comment]
@inacionery this will fix publication.. but it won't take effect until GA5

Can we wait til then for the demo or is it pressign?

**Comment by inacionery** [comment]
Yes, we can wait. For now I can do it manually.

**Pull request closed without merging**
