### PR TITLE
LPS-89877 Maps are not supported in IE. Use simple objects instead

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by jpince** [comment]
ci:close @ambrinchaudhary @julien please resolve SF error - new line character removed https://github.com/brianchandotcom/liferay-portal/pull/72840/files#diff-63ad529436dbfc93832f069966f66a94L307

**Comment by julien** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:close @julien maybe you didn't see my earlier comment... the SF error is real, I also reproduced it locally. The new line character was errantly added and needs to be removed. https://github.com/brianchandotcom/liferay-portal/pull/72840/files#diff-63ad529436dbfc93832f069966f66a94L307. Please do not reopen this pull - resend with the fix.
```
     [java] 1: ./modules/apps/frontend-compatibility/frontend-compatibility-ie/build.gradle expected:<... version: "0.10.0"
     [java] }[]> but was:<... version: "0.10.0"
     [java] }[
     [java] ]>
```

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
