### PR TITLE
LPS-87146

### PR DESCRIPTION
**Pull request by petershin**
@jpince

### CODE REVIEW

**Comment by jpince** [comment]
@petershin thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/24b52b79fc...104ba04a0c

**Comment by brianchandotcom** [comment]
@petershin see 721f2b4a75743f96fd322135fa0222e01ad0a904

Action<...> should always be xyzAction

This way

CopySpec copySpec

is not confused with

Action<CopySpec> copySpec

Because we should call it 

Action<CopySpec> copySpecAction

**Comment by brianchandotcom** [comment]
@hhuijser see my comment above this comment. This is why I care about var names. Thx!

**Pull request closed without merging**
