### PR TITLE
LPS-67303 Review

### PR DESCRIPTION
**Pull request by migue**
Apoligies, it's been my fault. I had been helping the AT project and I had the supbrepo cloned. Somehow I didn't notice that I included the empty folder within my latest commit of my review. Sorry for the confusion, it should work now ...

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cdd89cea5b...52251f8cdd

**Comment by brianchandotcom** [comment]
@ZoltanTakacs I backported this one since it looks important for upgrades and it's only setting a thread local company ID var in a very narrow scope. Also, the ticket used was already included for 7.0.x so I didn't want to cause confusion.

**Comment by ZoltanTakacs** [comment]
Hi @brianchandotcom ,

I think in this case for the portal core upgrades we need to create a post upgrade fix as well according to @achaparro 's announcement: https://loop.liferay.com/home/-/loop/feed/3067204
https://github.com/liferay/liferay-portal-ee/tree/ee-7.0.x/modules/private/post-upgrade-fix

Alberto, can you please confirm this?

**Comment by achaparro** [comment]
Hey @ZoltanTakacs,

You're right, this is good example where a post upgrad fix could be needed. However the need of creating it depends on the third point in the documentation:

> If it's a critical issue or your customer needs it

So it depends if the customer needs it or they don't because they can repeat the upgrade or they have a workaround with the same final results. I'm going to send an email to @SamZiemer (you will be in cc) to answer this question in private.

Thanks.

**Comment by achaparro** [comment]
@ZoltanTakacs, in the future, and to reduce the effort, we can review the backports of these kind of issues in this way:
- if someone tries to include this into a verify, we have to discard it and ask him to create a post upgrade fix instead.
- If we realized that it's a critical issue, we can ask the backporter to create a post upgrade fix too (we can also do it on demand)

Thanks.

**Comment by ZoltanTakacs** [comment]
Thank you @achaparro ! I'll do this way from now on.

**Pull request closed without merging**
