### PR TITLE
Lps 105915

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
The regression is from https://github.com/liferay/liferay-portal/commit/ee7a7fd40dd966c5686d6eaa0099257e76a608af

**Comment by shuyangzhou** [comment]
@kyle-miho @vicnate5 this could expose more failures. The UserSetDigestTest issue is causing the entire batch to fail, which won't generate junit report on all DBs. This was basically blinding us one batch of tests.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cf3148ac7f...c1f343d6b1

**Comment by brianchandotcom** [comment]
@stian-sigvartsen  @csierra fy... bad UserSetDigestTest

**Pull request closed without merging**
