### PR TITLE
LPS-89869 Web content folder names can be created with invalid character

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@topolik Should we use

```
StringEscapeUtils.unescapeJava 
```

like this? is it better to use one of our unescape utils?

@brianikim please consult with @topolik thx.

**Comment by brianikim** [comment]
Hello @brianchandotcom ,

Thanks for pointing that out. I will wait for @topolik's opinion here and make necessary changes if required.

Sincerely,
Brian Kim

**Comment by topolik** [comment]
Hi @brianikim,

I'd focus on why the configuration has the values double-escaped in the first place?

https://github.com/liferay/liferay-portal/blob/6db10e7e56171d7b12886a81a32b91dc794683a2/modules/apps/journal/journal-api/src/main/java/com/liferay/journal/configuration/JournalServiceConfiguration.java#L41

It can be seen in the error message too - `\' \\ \"`:
```The Folder Name cannot contain the following invalid characters: & \' @ \\ ] } : = > / < [ { % + # ` ? \" ; * ~.```

When I tried with:
```
	@Meta.AD(
		deflt = "&|'|@|\\|]|}|:|=|>|/|<|[|{|%|+|#|`|?|\"|;|*|~",
		description = "specifcy-characters-that-are-not-allowed-in-journal-folder-names",
		name = "characters-blacklist", required = false
	)
	public String[] charactersblacklist();
```
then the error and validation routine works correctly: ```The Folder Name cannot contain the following invalid characters: & ' @ \ ] } : = > / < [ { % + # ` ? " ; * ~.```

The only problem is with the System Settings configuration UI that is unable to render the `\` option correctly. I guess some bug during transfer from the Configuration -> DDM -> UI. Try to go this path ;)

**Pull request closed without merging**
