### PR TITLE
Lps 80180

### PR DESCRIPTION
**Pull request by shuyangzhou**
@brianchandotcom this fixes the LDAP issue in modules-integration tests

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@shuyangzhou who caused the regression? Just curious. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/127e8b884e...b4fc0627fa

**Comment by brianchandotcom** [comment]
@michaelhashimoto does this mean we can get rid of the SOCKS hack now?

**Comment by brianchandotcom** [comment]
@mtambara you'll have to backport this so we can disable socks for our tests in 7.0.x too. Thx.

**Comment by shuyangzhou** [comment]
@brianchandotcom the issue is always there, but the logger was set ERROR level, and the log message is at WARN. So we never know, until https://github.com/liferay/liferay-portal/commit/3c6a5cb94277e7158464cfd2f280d47cd465246d change the logger level to WARN.

**Comment by michaelhashimoto** [comment]
@brianchandotcom  - I don't think this is the fix.  I think we still need the socks proxy module.

**Comment by shuyangzhou** [comment]
@brianchandotcom this has nothing to do with the socks issue.

**Comment by mtambara** [comment]
@brianchandotcom Backport sent at https://github.com/brianchandotcom/liferay-portal-ee/pull/20007

**Pull request closed without merging**
