### PR TITLE
COMMERCE-618

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
https://issues.liferay.com/browse/COMMERCE-618

Resend of https://github.com/brianchandotcom/liferay-portal/pull/62865

Hi Brian,

I tried to avoid commiting the cached resources here, so I've put up a gradle script which can download the necessary 3rd party dependencies for the installer.

Please let me know what do you think about it.

Thanks,
Zoli

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@ZoltanTakacs you should really run ModulesStructureTest locally before submitting a pull.

How did you download those dependencies? Did you do it manually before? Please resend. Thx!

**Comment by ZoltanTakacs** [comment]
@petershin can you please let me know how I can run the ModulesStructureTest on my local environment?

**Comment by ZoltanTakacs** [comment]
@petershin thank you! For now I'm getting compile errors for `import com.liferay.petra.string.StringPool`, but will do a full `ant all` that might help. Thanks!

**Comment by ZoltanTakacs** [comment]
Resent on https://github.com/brianchandotcom/liferay-portal/pull/63010

**Pull request closed without merging**
