### PR TITLE
LPS-66149

### PR DESCRIPTION
**Pull request by natecavanaugh**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Hi guys, 

I am a little bit concerned about this change for several reasons:

1) I am afraid some of the translations may stop working after this change since the logic for calculating where to obtain the translation from is quite complex and moving it to inside the taglib in a different module may make some translations fail. Have you tested all the replaced lines?

2) Since calculating the place to obtain the translation from has become so much more complex now with the different osgi contexts and modules with the translations split between them, I thought this was a new approach we planned to go with from now on which consisted on accepting the parameters already translated instead of trying to calculate the translation by ourselves inside which has already proven to be hard (or even impossible) in many cases.

what do you guys think?  @jbalsas @brunobasto

Thank you!

**Comment by brianwulbern** [comment]
@juliocamarero As a side note, all the failing Poshi tests are when trying to add a Blank Site, but the span for that is untranslated, and reads "blank-site"

**Comment by jonmak08** [comment]
Hey @juliocamarero,

Maybe we should close this issue and continue our discussion on a new pull request since it seems like there is some hesitancy about this change.  I will resend a new pull request to @jbalsas for this where we can continue our discussion rather than keeping this issue open in @brianchandotcom's queue.

Please let me know if you have any questions. Thanks!

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/jbalsas/liferay-portal/pull/550

**Comment by juliocamarero** [comment]
Thanks a lot @jonmak08!

**Pull request closed without merging**
