### PR TITLE
LPS-66608 ant format-source

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @samanzanedo

**Comment by jonathanmccann** [comment]
Thanks for pushing this forward @sergiogonzalez !

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a672c0738f...f20251806f

**Comment by brianchandotcom** [comment]
@sergiogonzalez can you and @jonathanmccann please send me a backport for this? Thx.

We're in the middle of moving all the lib/** jars out to Gradle.

Thx.

**Pull request closed without merging**
