### PR TITLE
COMMERCE-7217 | COMMERCE-7218 Part 1

### PR DESCRIPTION
**Pull request by alessiorendina**
Hey @brianchandotcom,
Resending #107331 without conflicts. We are moving shop-by-diagram services and APIs out of the DXP modules.
Regards,
Alessio

### CODE REVIEW

**Comment by Commando18** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0d300d0923...051793b599

**Comment by brianchandotcom** [comment]
well done @Commando18 not many can do big refactors like this in a clean way

**Comment by Commando18** [comment]
Thanks @brianchandotcom

**Pull request closed without merging**
