### PR TITLE
Lps 64106 upgrade modules indexers configurable

### PR DESCRIPTION
**Pull request by mdelapenya**
cc/ @arbetts @migue @matethurzo

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b95400e8c4...74890be372

**Pull request closed without merging**
