### PR TITLE
COMMERCE-8005 Replacement SBD product APIs (Resend)

### PR DESCRIPTION
**Pull request by alessiorendina**
Resending #111667

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/adad0cb6aa...54fbbeec59

**Comment by brianchandotcom** [comment]
Thx @alessiorendina !

**Comment by brianchandotcom** [comment]
@alessiorendina just 54fbbeec595aba4ea60d5e9703d3ea16db5c8152

**Pull request closed without merging**
