### PR TITLE
LPS-63169 fix taglib name and resolve validator method ambiguity

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @jbalsas

**Comment by juliocamarero** [comment]
cc @sergiogonzalez

**Comment by jbalsas** [comment]
Looks good, thanks @pavel-savinov, @juliocamarero!

**Comment by juliocamarero** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/30823c62bf...d9310a98e8

**Pull request closed without merging**
