### PR TITLE
LPS-70016 | master

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
https://issues.liferay.com/browse/LPS-70016

Hi @brianchandotcom,

We need to publish a new module version for My Account Web as well because it uses resources from Users Admin Web where these files have been updated.

- Can you think of a better way of handling this kind of dependency issues in the future or should we check and update the dependent module versions manually?

Please see my explanation in the [comment](https://issues.liferay.com/browse/LPS-70016?focusedCommentId=948671&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-948671) of the LPS.

/cc @zsoltbalogh

### CODE REVIEW

**Comment by ZoltanTakacs** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Bumping it up to 1.0.6 is the wrong idea because 1.0.5 hasn't been released yet. The last release was 1.0.4.

I"ll manually release this again.

**Comment by brianchandotcom** [comment]
@ZoltanTakacs I published a new one for you.

**Comment by zsoltbalogh** [comment]
@brianchandotcom, it was my idea to bump up the version number, but now I realize that we automatically bump up. Do you think there's a way for us to trigger the re-release of these modules? I'm foreseeing issues like this in the future and it would be a good idea to have a set process.

**Pull request closed without merging**
