### PR TITLE
LPS-53139 Comment

### PR DESCRIPTION
**Pull request by epgarcia**
@juliocamarero

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/69d821ddf7...d1cd406542

**Comment by brianchandotcom** [comment]
Should we write an integration / unit for test this?

**Comment by epgarcia** [comment]
I will write it! Thanks!

**Comment by epgarcia** [comment]
See brianchandotcom/liferay-portal/pull/23810

**Pull request closed without merging**
