### PR TITLE
LPS-69389 baseline

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:retest

**Comment by brunobasto** [comment]
@kenjiheigel Can you help me interpret this failures?

Thx

**Comment by kenjiheigel** [comment]
@brunobasto, taking a look.

**Comment by kenjiheigel** [comment]
@brunobasto, it's a start up error. 

>      [exec] 01:49:15,301 WARN  [fileinstall-/opt/dev/projects/github/liferay-portal/bundles/osgi/modules][org_apache_felix_fileinstall:103] Error while starting bundle: file:/opt/dev/projects/github/liferay-portal/bundles/osgi/modules/com.liferay.hello.soy.web.jar 
>      [exec] org.osgi.framework.BundleException: Could not resolve module: com.liferay.hello.soy.web [509]
>      [exec]   Unresolved requirement: Import-Package: com.liferay.portal.portlet.bridge.soy; version="[2.0.0,3.0.0)"
>      [exec]     -> Export-Package: com.liferay.portal.portlet.bridge.soy; bundle-symbolic-name="com.liferay.portal.portlet.bridge.soy"; bundle-version="3.1.0"; version="2.0.0"; uses:="com.liferay.portal.kernel.portlet.bridges.mvc,com.liferay.portal.kernel.template,javax.portlet"
>      [exec]        com.liferay.portal.portlet.bridge.soy [148]
>      [exec]          Unresolved requirement: Import-Package: com.liferay.portal.template.soy.utils; version="[1.0.0,2.0.0)"
>      [exec] 
>      [exec] 	at org.eclipse.osgi.container.Module.start(Module.java:429)
>      [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
>      [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1252)
>      [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1224)
>      [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:512)
>      [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:361)
>      [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:313)
>      [exec] 01:49:15,303 ERROR [fileinstall-/opt/dev/projects/github/liferay-portal/bundles/osgi/modules][org_apache_felix_fileinstall:112] Exiting the JVM 
>      [exec] org.osgi.framework.BundleException: Could not resolve module: com.liferay.hello.soy.web [509]
>      [exec]   Unresolved requirement: Import-Package: com.liferay.portal.portlet.bridge.soy; version="[2.0.0,3.0.0)"
>      [exec]     -> Export-Package: com.liferay.portal.portlet.bridge.soy; bundle-symbolic-name="com.liferay.portal.portlet.bridge.soy"; bundle-version="3.1.0"; version="2.0.0"; uses:="com.liferay.portal.kernel.portlet.bridges.mvc,com.liferay.portal.kernel.template,javax.portlet"
>      [exec]        com.liferay.portal.portlet.bridge.soy [148]
>      [exec]          Unresolved requirement: Import-Package: com.liferay.portal.template.soy.utils; version="[1.0.0,2.0.0)"
>      [exec] 
>      [exec] 	at org.eclipse.osgi.container.Module.start(Module.java:429)
>      [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
>      [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1252)
>      [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1224)
>      [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:512)
>      [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:361)
>      [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:313)

Full console log: https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/63749/AXIS_VARIABLE=5,label_exp=!master/consoleFull
How to navigate to the console log: https://drive.google.com/file/d/0BySFfOWPyNghRXV2R0dUSDRyLUE/view

Let me know if you need anything else!

**Comment by brunobasto** [comment]
Thanks, @kenjiheigel! I've resent it here: https://github.com/brianchandotcom/liferay-portal/pull/45135

**Pull request closed without merging**
