### PR TITLE
LPS-94301

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@Preston-Crary, just the changes to SF from this pull (which had conflicts: https://github.com/brianchandotcom/liferay-portal/pull/71893)

Will try to rebase the other stuff and send in another pull

**Comment by hhuijser** [comment]
@Preston-Crary... ugh, not going to fix conflicts from https://github.com/brianchandotcom/liferay-portal/pull/71893

This one (https://github.com/liferay/liferay-portal/commit/46e6ffcd00364200b68f204325e73bc5f0876bb5) messing up everything, so better to start from scratch

**Comment by hhuijser** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
@hhuijser okay, I'll take care of it when I get a chance.

**Comment by Preston-Crary** [comment]
Just disable the check for now and I'll do the apply.

**Comment by hhuijser** [comment]
@Preston-Crary already redid the non-configuration ones in `-web`. See https://github.com/hhuijser/liferay-portal/pull/3521
Will send to Brian if it passes the tests

**Comment by brianchandotcom** [comment]
@hhuijser publishing..

**Pull request closed without merging**
