### PR TITLE
Lps 53219

### PR DESCRIPTION
**Pull request by shuyangzhou**
I think I got them all this time, hopefully...

### CODE REVIEW

**Comment by shuyangzhou** [comment]
force updated to fix the rule ordering issue

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
Yeah, it is good to go now, sorry for those mistakes.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0e3c448474...8b5c4c5a01

**Comment by brianchandotcom** [comment]
Thx @shuyangzhou looks great!

**Pull request closed without merging**
