### PR TITLE
LPS-96911

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
Looking into the `npmRunCheckFormat` failure

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by hhuijser** [comment]
@petershin, when I run from my local machine, it runs fine. Any ideas?

**Comment by petershin** [comment]
@hhuijser - See https://github.com/brianchandotcom/liferay-portal/pull/74964

**Pull request closed without merging**
