### PR TITLE
LPS-65802 Avoid add an empty condition.

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@marcellustavares @inacionery @topolik build.gradle changes seem wrong. It's for compile time, but there doesn't seem to be compile time changes. Please resend.

**Comment by marcellustavares** [comment]
hey @brianchandotcom, I think @inacionery changed the build.gradle to make the changes in portal-impl visible to DDM module?

**Comment by inacionery** [comment]
@marcellustavares @brianchandotcom I changed the build.gradle to make the changes in portal-impl visible to DDM module also the portal-kernel because this method "ResourceActionsUtil.getCompositeModelName" in https://github.com/brianchandotcom/liferay-portal/pull/41252/commits/63590d714426ca05f7a7fffd6bbe74c5b407d82cR227

**Comment by brianchandotcom** [comment]
@inacionery but why did *-service have to change? I can see the test. But I don't see any changes in the service that require it.

**Comment by inacionery** [comment]
@brianchandotcom, The dynamic-data-mapping-service must use the new code(https://github.com/brianchandotcom/liferay-portal/pull/41252/commits/4174c002894f29beef28a04ba9d0e48084366f91) to fix the problem, so i update the portal-impl to default version.

**Pull request closed without merging**
