### PR TITLE
LPS-101720 Add Email One-Time password checker

### PR DESCRIPTION
**Pull request by csierra**
/cc @arthurchan35

hi @brianchandotcom,
follow up pull after our conversation this morning. This is the same pull we had sent before with the code adapted to current master. 
Thx again. 

Carlos.

### CODE REVIEW

**Comment by csierra** [comment]
ci:test:stable

**Comment by csierra** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/21ab666171...6153067ca6

**Comment by brianchandotcom** [comment]
@csierra @arthurchan35 see my changes from 950d69498a9b8d3c54bda5e1b6e9fde47789c8a7 to 6153067ca6f12f990b730018416ca4a0230a7c84

About 26 small commits in an hour. Hope the changes make sense.. it's more smell and style than anything else, but overtime, it matters. The logic you guys did is good.. just needs good naming.

Thx @csierra @arthurchan35

**Pull request closed without merging**
