### PR TITLE
LPS-82345 First draft of Adaptive Media API

### PR DESCRIPTION
**Pull request by javiergamarra**
/cc @dgarciasarai

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/59a76b69d8...bf0b36de01

**Comment by nhpatt** [comment]
Thanks! :D

**Comment by dgarciasarai** [comment]
Thanks! 😃

**Pull request closed without merging**
