### PR TITLE
LPS-83949 Add new method to resolve relative dependency paths

### PR DESCRIPTION
**Pull request by izaera**
@brianchandotcom This is the first of a series of pulls related to the LPS. I'll send it in small chunks to ease CI testing

### CODE REVIEW

**Comment by izaera** [comment]
The relevant failed tests are not related. They are the ones that have something to do with the search

**Comment by izaera** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/59c04611ed...e6fa3fbb2c

**Comment by brianchandotcom** [comment]
Thx @izaera merged. Minor change in e6fa3fbb2ce3dae7048701e828c2934652369ec0

**Pull request closed without merging**
