### PR TITLE
LPS-71107 Replace endsWith (ie11 does not support that)

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by sharonchoi** [comment]
Hey @brianchandotcom,

Do you mind backporting this pull to ee-7.0.x? (as the ticket was reopened and this commit was added to it) It's currently a blocker for FP13. Thank you!

fyi @jbalsas

**Comment by jbalsas** [comment]
Hey @sharonchoi, @brianchandotcom, I realized this was introduced later on, in an LPS that is yet to be backported https://github.com/dustinryerson/liferay-portal-ee/pull/2667

This shouldn't be affecting or blocking ee at all at this point.

**Comment by sharonchoi** [comment]
Hey @brianchandotcom,

After discussing with @jbalsas, it turns out that there was a bit of a mixup between the two LPS's. So please, if you can:

Backport https://github.com/dustinryerson/liferay-portal-ee/pull/2667 FIRST, and then https://github.com/brianchandotcom/liferay-portal/pull/47555/commits/1910368eb5524ef82b5b28a9b8aacfe2cfc1d94a

as, this commit, is dependent on Dustin's pull. Thanks!

**Pull request closed without merging**
