### PR TITLE
LPS-97596 Global Site is not ordered correctly when displayed in Japanese

### PR DESCRIPTION
**Pull request by Tim-Cao**
This is only for master.

https://issues.liferay.com/browse/LPS-97596

@jkappler

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/11092

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7ba9ed4121...cf51bf5965

**Comment by brianchandotcom** [comment]
@jkappler see cf51bf596533be0bc7d5ac8c3426310628e1cc77

**Pull request closed without merging**
