### PR TITLE
LPS-100427 add site key for graphql

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@nhpatt I published a new REST builder.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/861c704dad...6485a8d3d7

**Comment by nhpatt** [comment]
Thanks!

**Comment by nhpatt** [comment]
Ok, I see :)

**Pull request closed without merging**
