### PR TITLE
LPS-52935 Iframe portlet vulnerable to password theft attack if an untrusted user configures it

### PR DESCRIPTION
**Pull request by topolik**
https://issues.liferay.com/browse/LPS-52935

### CODE REVIEW

**Comment by topolik** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9203a99f86...6493a3b17a

**Comment by brianchiu** [comment]
@kenjiheigel
Can you take a look?

There's flakiness in portal instance set up. This is the only test in its group so it's not because the previous test had issues.

**Comment by kenjiheigel** [comment]
@brianchiu, I'm working on an update that will run single tests normally, without a portal instance. It was working at some point before we enabled sequential test runs, but I think I broke it when fixing other issues and making the update.

**Pull request closed without merging**
