### PR TITLE
LPS-61671 Hack into Sun javac to let BundleJavaFileManager directly r…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…eturns the ZipFileIndexFileObject's simple name to avoid the complex full class name construction. This is working because, in side Sun Javac even it is asking the JavaFileManager for full class name, it is only to strip off the package name to only use the simple name, so it is better to avoid the heavy ZipFileIndexFileObject full class name construction to directly return what it is needed.

CC @rotty3000 @mhan810

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ac38ce47d1...c769788a6a

**Comment by brianchandotcom** [comment]
@shuyangzhou I made a few changes in uptsream.

**Comment by shuyangzhou** [comment]
@brianchandotcom this is only known to work with sun javac, I have no idea what will happen when we use this logic on other jdks. Are we assuming oracle jdk only from now on?

**Comment by brianchandotcom** [comment]
no.. but if we force ppl to have to modify the property, that's a bad experience, can't we use JavaDetector? like we do for OSDetector etc?

**Comment by shuyangzhou** [comment]
Even for sun javac, we are hacking into its internal impl. Which means they can change it in the future, I think it is safer to leave a switch here. In case it is still sun javac, but they change something internally which breaks this hack. Then customers can just turn off this hack without waiting for us to release a new fix.

**Comment by brianchandotcom** [comment]
Ok, can we do both? Use JavaDetector, then use property (which defaults to true)? let's make the property more specific, to show it has to do with that module. A generic "sun.javac.hack" is a bit weird to me. Thx

**Comment by shuyangzhou** [comment]
Sure, I will readd it a bit later today.

**Pull request closed without merging**
