### PR TITLE
LPS-77071 Allows adding an input-search inside the management bar

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @brianchandotcom, this shouldn't need tests, as it is just preparatory work for some Lexicon changes.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6064fe14bf...e958fd8f7d

**Comment by brianchandotcom** [comment]
@jbalsas I ran SF and it auto fixed e958fd8f7d24a80e2b5625f7293344fbf173a4c9

Please run "ant format-source-current-branch" in portal-impl

**Comment by jbalsas** [comment]
Thanks @brianchandotcom! I usually catch them fast when tests run... I'll make sure I always double check if I don't run them now. Sorry about that!

**Pull request closed without merging**
