### PR TITLE
LPS-101274 Add support for domains in accounts to allow restricting user creation to specific domains

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @alee8888

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by patriciajeanperez** [comment]
ci:close

**Comment by patriciajeanperez** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6933f8db9a...af93ddc773

**Comment by brianchandotcom** [comment]
@pei-jung rename domainNames to domains

ask @jbalsa to expose 

// Email domain regex from aui-form-validator.js

so you don't have to copy it.

**Comment by pei-jung** [comment]
Rename change sent to https://github.com/brianchandotcom/liferay-portal/pull/80194

**Pull request closed without merging**
