### PR TITLE
LPS-69208 Move the Documents and Media file uploads settings UI from Server Administration to System Settings

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-69208](https://issues.liferay.com/browse/LPS-69208).<br><br>/cc @pei-jung, @alee8888, @xbrianlee, @jorgeferrer

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0bc517061f...e2e786be56

**Comment by drewbrokke** [comment]
Thanks @brianchandotcom :)  One of these properties is also in `liferay-journal`.  Do we need to publish a new version of `document-library-api` in order to use the new configuration value there?

**Comment by drewbrokke** [comment]
@brianchandotcom nevermind - I can do it without needing the new version

**Pull request closed without merging**
