### PR TITLE
[TS] Lps 93905 92581

### PR DESCRIPTION
**Pull request by balazssk**
Hi @brianchandotcom 

Followup of https://github.com/brianchandotcom/liferay-portal/pull/71439

Found the change which was missing sem ver and created it: 
https://issues.liferay.com/browse/LPS-92581

> This is the second PR of package refactoring. This time com.liferay.asset.kernel.model.AssetRenderer 's implementations are moved from *.asset to *.asset.model pacakges
> 
> Can you please review?
> https://issues.liferay.com/browse/LPS-93905

Thanks,

### CODE REVIEW

**Comment by balazssk** [comment]
ci:reopen

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
reopened as it was closed by a timeout error

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b08d4b49bf...5ac597b49c

**Comment by brianchandotcom** [comment]
@shuyangzhou 

modules/apps/blogs/blogs-web/src/main/java/com/liferay/blogs/web/asset/BlogsEntryAssetRendererFactory.java

should all be internal

I thought we had a test for this? Can you fix it and notify @hhuijser to make sure we enforce the package names to be internal?

**Comment by brianchandotcom** [comment]
@balazssk can you send me stuff for master-private too? Thx.

**Pull request closed without merging**
