### PR TITLE
LPS-188946 Replace alert divs with clay:alert taglib in asset-publisher-web

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://liferay.atlassian.net/browse/LPS-188946

@DiegoHu97
cc @victorg1991

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/12715

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d5dc45b1cd...4cc6ae4ca3

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4cc6ae4ca3...4cc6ae4ca3

**Pull request closed without merging**
