### PR TITLE
LPS-109828 Auto SF

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
Hi @brianchandotcom, renamed finders as requested [here](https://github.com/brianchandotcom/liferay-portal/pull/85975#issuecomment-596824035).
Thanks.

/cc @ealonso

**Comment by pavel-savinov** [comment]
ci:stop

**Comment by pavel-savinov** [comment]
ci:test:stable

**Comment by brianchandotcom** [comment]
@pavel-savinov sorry one more change:

git grep "List<Object>" **ServiceImpl.java

I think we should call them delete_objects

so you have objects (generic, and then fragment entries and fragment composites)

Right now you have "entries" vs. "fragment entries" and "fragment composites"

I think that's more confusing (i.e. DeleteEntriesMVCActionCommand.java).

**Pull request closed without merging**
