### PR TITLE
LPS-54662

### PR DESCRIPTION
**Pull request by kenjiheigel**
This fix was sent from @csierra and fixes a jscompiler memory leak error that occurs upon shutdown

### CODE REVIEW

**Comment by brianchiu** [comment]
@brianchandotcom 
Here is the ticket; I've assigned it to you.
https://issues.liferay.com/browse/LPS-54662

cc @csierra 
cc @kenjiheigel

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6a447b4a23...f26daa74f5

**Comment by brianchandotcom** [comment]
Very nice @csierra

**Comment by csierra** [comment]
Thanks... :blush: kudos to @kenjiheigel & Co. for spotting this out

**Pull request closed without merging**
