### PR TITLE
LPS-143989 Create PATCH UserGroup by ExternalReferenceCode for User Group Headless API

### PR DESCRIPTION
**Pull request by epark18**
Manual forward from: [liferay-usm#437](https://github.com/liferay-usm/liferay-portal/pull/437)

https://issues.liferay.com/browse/LPS-143989

### CODE REVIEW

**Comment by epark18** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7f199c6b4d...d9b29461e3

**Comment by brianchandotcom** [comment]
@drewbrokke @erickmonteiroo can you guys add

forcePredictableOperationId: true

to rest-openapi.yaml

@drewbrokke can you work with @petershin on this? Should sound familiar, but I'd like to make the paths consistent.

**Comment by drewbrokke** [comment]
@brianchandotcom sounds good, will do

**Pull request closed without merging**
