### PR TITLE
LPS-188958 add aria-labelledby attribute to checkbox in taglib search iterator

### PR DESCRIPTION
**Pull request by thiago-buarqque**
**>> Sending manually since the forward command is failing due `An error has occurred: com.liferay.jenkins.results.parser.GitHubSecondaryRateLimitRuntimeException.`**

# Description in the original PR

Ticket: [LPS-188958](https://liferay.atlassian.net/browse/LPS-188958)

Motivation
=======
The checkbox in taglib search iterator component has no row information associated with its aria-label attribute. Because of that, screen readers such as JAWS can't tell the user any information that might help making the decision of checking that row.

Proposed Solution
========
After a long discussion (see it [here](https://liferay.slack.com/archives/C04A7NLM7L1/p1691584013482139?thread_ts=1690227135.868729&cid=C04A7NLM7L1)), it was decided to add the `aria-labelledby="rowId"` to the row checkbox attribute. 

The **proposed solution** makes the screen reader say something like (consider that the row info is for a web content) "select web_content_name web_content_description column_3 column_4 actions". Yes, it says more than it's needed. See 
Alternative Solutions that were discarded section below for more context.

Alternative Solution that was discarded
========
The best scenario would be to have the `aria-label="select web_content_name"` attribute in the checkbox, that way the screen readers would say "select my content 1", simple, clean and useful. The problem with this approach is the way the search-iterator works:

1. The client (any JSP page in the portal) calls the search-container component, which uses the search-iterator. For each result from the SearchContainer (passed by the client code), it creates a ResultRow object instance and give it to the client clode (see an example [here](https://github.com/liferay/liferay-portal/blob/ece66430e068f9d986100c239e5c49e66f11a079/modules/apps/document-library/document-library-web/src/main/resources/META-INF/resources/document_library/select_file_entry_type.jsp#L58));
2. For each row, the client code might pass additional data, it would in there where the client code would pass the objectModel.getTitle() (or name). But even if we do that, we couldn't use it inside `*RowChecker.java` without changing the API ([see](https://github.com/liferay/liferay-portal/blob/ece66430e068f9d986100c239e5c49e66f11a079/portal-kernel/src/com/liferay/portal/kernel/dao/search/RowChecker.java#L259)). Changing the API was already rejected by Brian ([see](https://github.com/brianchandotcom/liferay-portal/pull/140663#issuecomment-1719786698)). Also, doing that would require to change 350+ files and future files could just not add this information to the row data.

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:reopen

**Comment by thiago-buarqque** [comment]
@brianchandotcom this a new fix for the related bug since the [original proposal was rejected](https://github.com/brianchandotcom/liferay-portal/pull/140663#issuecomment-1719786698) because it changed the kernel API.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4a34c2b87f...ab090c3633

**Comment by brianchandotcom** [comment]
@thiago-buarqque soooo much better.

 See my changes in a822d4aafcb32402c55b5fa6a2170279e46f79b0 0cc4b79263cd1070134ded100ecb6910ef5bf105 and ab090c36336fba35432d946605331c2ed72942c9

**Comment by thiago-buarqque** [comment]
@brianchandotcom Thanks haha and thanks for the SF

**Pull request closed without merging**
