### PR TITLE
LPS-142380 Use ReflectionUtil to keep the exception instead of wrapping it in a RuntimeException; in this change's case, the UI won't be able to show the error message if the exception is rethrown as RuntimeException.

### PR DESCRIPTION
**Pull request by jgarcialr**
- LPS-142380 Add validation in ExpandoColumnLocalServiceImpl
- LPS-142380 Add test
- LPS-142380 Use proper method to add the attribute with default value to make sure validation is executed before creating the value
- LPS-142380 Show error message on UI
- LPS-142380 buildLang
- LPS-142380 SV
- LPS-142380 SF, inline
- LPS-142380 SF, remove unnecessary try-rethrow
- LPS-142380 Use ReflectionUtil to keep the exception instead of wrapping it in a RuntimeException; in this change's case, the UI won't be able to show the error message if the exception is rethrown as RuntimeException.
- LPS-142380 SV
- LPS-142380 rename exceptions
- LPS-142380 Add validation in ExpandoValueLocalServiceImpl
- LPS-142380 remove calls to ValueDataException and use new static exceptions

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:reopen

**Comment by crodriguezy** [comment]
Hi @brianchandotcom , does this look good to you? Coming from #https://github.com/brianchandotcom/liferay-portal/pull/122803

**Comment by brianchandotcom** [comment]
@jgarcialr @crodriguezy Please resend on top of https://github.com/jgarcialr/liferay-portal/pull/63

1.) This sentence sounds weird

```
please-enter-a-value-also-for-default-locale=Please enter a value also for the default locale.
```

2.) See portal-kernel/src/com/liferay/portal/kernel/exception/UserPasswordException.java

See how the inner classes have constructors with specific types, and not with just "String msg". You construct the message in the exception. This is also how you have it with:

```
		public MustInformDefaultLocale(Locale locale) {
			super(
				"A value for the default locale (" + locale.getLanguage() +
					") must be defined");
		}
```

3.) Please see my changes to the tst.

**Comment by crodriguezy** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/123808

**Pull request closed without merging**
