### PR TITLE
LPS-174420 Send the script as a file to avoid having to parse it as a base64

### PR DESCRIPTION
**Pull request by alessandromalves**
This is only for master
https://issues.liferay.com/browse/LPS-174420
cc.: @victorg1991

### CODE REVIEW

**Comment by alessandromalves** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/11060

:heavy_check_mark: ci:test:stable - 27 out of 28 jobs passed
:x: ci:test:relevant - 71 out of 79 jobs passed in 1 hour 22 minutes

**Comment by alessandromalves** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@matthiasblaesing @alessandromalves @victorg1991 how come we are doing

```
\r\n
```

Isn't that Windows specific?

```
			StringPool.DOUBLE_DASH, boundary,
			"\r\nContent-Disposition:form-data;name=\"scriptContent\";",
			"filename=\"scriptContent\";\r\nContent-type:application/json",
			"\r\n\r\n");

```

Please resend.

**Comment by victorg1991** [comment]
Hey @brianchandotcom 

It seems that it is mandatory to add CRLF in the mulitpart format

https://www.rfc-editor.org/rfc/rfc7231#section-3.1.1.4

> The message body is itself a protocol element; a sender MUST
   generate only CRLF to represent line breaks between body parts.

**Comment by victorg1991** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/63b80e33d2...7800c31a86

**Pull request closed without merging**
