### PR TITLE
LPS-76419 Upgrade to remove no longer valid permissions

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test

**Comment by 4lejandrito** [comment]
ci:test

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@4lejandrito see upstream for my changes and fixes? Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/88aa90972c...b8e84c249f

**Pull request closed without merging**
