### PR TITLE
master-qa-24993

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LRQA-24993

### CODE REVIEW

**Comment by evannagayama** [comment]
@pyoo47 pr tester doesn't like me... should i retest?

**Comment by brianchandotcom** [comment]
@pyoo47 please help @evannagayama thx.

**Comment by pyoo47** [comment]
It may just be bad luck.. let me try retest once more... ci:retest

**Comment by pyoo47** [comment]
@evannagayama I've been watching this one and it's gotten past the point where it failed the other two times. I think this test will work. I think you just had bad luck in getting hit by this issue twice in a row.

**Comment by evannagayama** [comment]
Thanks @pyoo47. resent: https://github.com/brianchandotcom/liferay-portal/pull/39475

**Pull request closed without merging**
