### PR TITLE
Lps 69736

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @migue please see https://github.com/shuyangzhou/liferay-portal/commit/d371928a6c6ed6b2552569bbca96fbc9985d3740 and https://github.com/shuyangzhou/liferay-portal/commit/8848a5a1289ee40e8d023788832e5299ec6bad87

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@shuyangzhou can you backport this? Not able to cherry pick

**Comment by shuyangzhou** [comment]
@tomwang2011 please do the backport, thanks!

**Comment by tomwang2011** [comment]
@brianchandotcom @shuyangzhou Partial backport sent to: https://github.com/dustinryerson/liferay-portal-ee/pull/2404

**Pull request closed without merging**
