### PR TITLE
LPS-70736 As a developer, I'd like to have an API to help display international address in proper formats

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-70736](https://issues.liferay.com/browse/LPS-70736).<br><br>This is a resend of https://github.com/brianchandotcom/liferay-portal/pull/51232 with the SF changes<br><br>/cc @pei-jung @jorgeferrer

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Nicely done @drewbrokke !

I made a few minor changes in upstream. Please review. Thx.

**Comment by drewbrokke** [comment]
Thanks!  Almost got 'em all ;)

**Comment by drewbrokke** [comment]
@pei-jung helped me catch a few, too!

**Pull request closed without merging**
