### PR TITLE
LPS-60295

### PR DESCRIPTION
**Pull request by natecavanaugh**

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
i got these ones unstuck. One of our servers was causing this to stall.

Results should be up soon.

**Comment by michaelhashimoto** [comment]
This particular pull request has been stuck right here for a while:
<pre>    [junit] Running com.liferay.portlet.social.service.persistence.test.SocialActivitySetPersistenceTest
    [junit] Testsuite: com.liferay.portlet.social.service.persistence.test.SocialActivitySetPersistenceTest
    [junit] Tests run: 25, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.285 sec
    [junit] Tests run: 25, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.285 sec
    [junit] 
    [junit] Running com.liferay.portlet.softwarecatalog.service.persistence.test.SCFrameworkVersionPersistenceTest
    [junit] Testsuite: com.liferay.portlet.softwarecatalog.service.persistence.test.SCFrameworkVersionPersistenceTest
    [junit] Tests run: 23, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.213 sec
    [junit] Tests run: 23, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.213 sec
    [junit] 
    [junit] Running com.liferay.portlet.trash.service.TrashEntryLocalServiceCheckEntriesTest
    [junit] Testsuite: com.liferay.portlet.trash.service.TrashEntryLocalServiceCheckEntriesTest</pre>

See this <a href="http://test-1-20/job/test-portal-acceptance-pullrequest-batch%28master%29/4933/AXIS_VARIABLE=2,label_exp=!master/console">link</a> for a full printout.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@natecavanaugh @brianchiu this breaks a lot of poshi tests. Please resend.

**Comment by brianchiu** [comment]
@kenjiheigel
Can you help out Nate with this one?

**Comment by kenjiheigel** [comment]
Appears to require a test fix. Will confirm the fix and resend to BChan with the test updates.

**Comment by kenjiheigel** [comment]
I fixed and reran it, but there were new failures. 
https://github.com/kenjiheigel/liferay-portal/pull/65

Will need to look into it more tomorrow morning.

**Pull request closed without merging**
