### PR TITLE
LPS-64686 Remove unnecessary inclusion in bnd

### PR DESCRIPTION
**Pull request by peterfellwock**
@brianchandotcom from what I can gather, this inclusion was left behind and its not being used. Its a small change, lets see what the ci tests say.

### CODE REVIEW

**Comment by peterfellwock** [comment]
@brianchandotcom marketplace-test???

**Comment by brianchandotcom** [comment]
Looking into it @peterfellwock

**Comment by peterfellwock** [comment]
@brianchandotcom thank you sir

**Comment by brianchandotcom** [comment]
Fixed in 60d4f09d8a86a07a0b76cf17682d0a6e2104ef8b

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Blah, not testing this one.. it should work. Merging it in.

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/60d4f09d8a...9156b427b4

**Comment by peterfellwock** [comment]
@brianchandotcom hahahahaha

**Pull request closed without merging**
