### PR TITLE
LPS-93598 Changing name in tests too

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
@patriciajeanperez keep an eye on the tests, I did some changes (see https://github.com/brianchandotcom/liferay-portal/pull/71605/commits/ef31a9f9bd7e79c873f2cad1025bcda9bd4d5097).

**Comment by patriciajeanperez** [comment]
ci:test:sharing

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9ee952a53c...18d92a32ce

**Comment by brianchandotcom** [comment]
@4lejandrito see upstream for my changes? Thx.

**Pull request closed without merging**
