### PR TITLE
LPS-142384 Headless Digital Signature

### PR DESCRIPTION
**Pull request by joseabelenda**

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:reopen

**Comment by joseabelenda** [comment]
@victortrajano

**Comment by brianchandotcom** [comment]
@victortrajano @joseabelenda 1.) for rest-config.yaml

forcePredictableSchemaPropertyName: true

It'll force certain names

2.) for rest-openapi.yaml

envelopes should be ds-envelopes

envelopeId should be dsEnvelopeId

Please resend.

**Comment by joseabelenda** [comment]
resent:https://github.com/brianchandotcom/liferay-portal/pull/110088

**Pull request closed without merging**
