### PR TITLE
LPS-103714 Prune unnecessary lines from eslintignore

### PR DESCRIPTION
**Pull request by wincent**
- We no longer need "apps/chat" and "apps/mail-read" (they have been moved into "apps/archived").
- And we no longer need the negation for the configuration files (as of acd128235c413836fd66, we lint basically ".js" files instead of just the ".es.js" ones).

### CODE REVIEW

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark:

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4901fb430d...03907dbbe9

**Comment by brianchandotcom** [comment]
@wincent can you backport this to 7.2.x since we have archived there too

**Comment by wincent** [comment]
Backport sent here: https://github.com/brianchandotcom/liferay-portal-ee/pull/27308

**Pull request closed without merging**
