### PR TITLE
Lps 68838

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@peterfellwock compile error? Please resend.

```
 /opt/dev/projects/github/liferay-portal/modules/apps/social-networking/social-networking-test/src/testIntegration/java/com/liferay/social/networking/service/persistence/test/MeetupsEntryPersistenceTest.java:35: error: cannot find symbol
     [exec] import com.liferay.portal.test.rule.TransactionalTestRule;
     [exec]                                    ^
     [exec]   symbol:   class TransactionalTestRule
     [exec]   location: package com.liferay.portal.test.rule
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/social-networking/social-networking-test/src/testIntegration/java/com/liferay/social/networking/service/persistence/test/MeetupsRegistrationPersistenceTest.java:35: error: cannot find symbol
     [exec] import com.liferay.portal.test.rule.TransactionalTestRule;
     [exec]                                    ^
     [exec]   symbol:   class
```

**Comment by shuyangzhou** [comment]
@brianchandotcom this must be a build problem. If it is a real compile error, all nodes will fail. Not just the module sybase one.

ci:reopen

**Comment by shuyangzhou** [comment]
Looks like ci:reopen can not reopen manually closed pull? I will just resend a new one.

**Comment by shuyangzhou** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/44129

**Pull request closed without merging**
