### PR TITLE
Lps 57626

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@Ithildir hanging Gradle test executor?
See https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=3,label_exp=!master/12857//console

ci:retest

**Comment by Ithildir** [comment]
@shuyangzhou: maybe, difficult to know what it was doing. I'll work on the thread dump code today!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/29bbb3cc09...5d9fdc6955

**Comment by brianchandotcom** [comment]
@peterfellwock fyi for login portlet

**Pull request closed without merging**
