### PR TITLE
LPS-84119

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Related:
https://github.com/brianchandotcom/liferay-portal-ee/pull/25363
https://github.com/brianchandotcom/liferay-portal-ee/pull/25364
https://github.com/brianchandotcom/liferay-portal-ee/pull/25365

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/19418b346e...d98171ae82

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
ci:close

**Pull request closed without merging**
