### PR TITLE
ISSD-1364 Replace Blueprint

### PR DESCRIPTION
**Pull request by Andrefes565**

### CODE REVIEW

**Comment by Andrefes565** [comment]
ci:reopen

**Comment by Andrefes565** [comment]
ci:test:sf

**Comment by Andrefes565** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@Andrefes565 wrong solution. Talk to Nilton. I talked to him about it.

**Comment by Andrefes565** [comment]
ci:reopen

**Pull request closed without merging**
