### PR TITLE
LPS-98833 Baseline

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ee23c2658f...d487e4e2be

**Comment by brianchandotcom** [comment]
@epgarcia can you review my changes in upstream, specifically d487e4e2be0c4725ff5938e10fbe4af073f56b98

thx

**Comment by brianchandotcom** [comment]
@epgarcia perhaps you should rename 

REQUEST_PARAMETER

to

QUERY_STRING

or REQUEST_PARAMETERS

I don't like what it's named right now.. you can see the weirdness in d487e4e2be0c4725ff5938e10fbe4af073f56b98

thx

**Comment by epgarcia** [comment]
See #77665. Thanks

**Pull request closed without merging**
