### PR TITLE
LPS-84836 We cannot test for collection ID here since they are not the same in staging and in live

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @kyle-miho, @brianchiu

**Comment by jpince** [comment]
ci:close investigating failure in modules-integration

**Comment by jpince** [comment]
@jkappler I think it has a problem with this line https://github.com/brianchandotcom/liferay-portal/pull/63233/files#diff-0cd7d7dccd9b1c9349310b595ae5973aR12. CI is asking for `Please create marker file /opt/dev/projects/github/liferay-portal/modules/apps/export-import/export-import-test/.lfrbuild-portal` (see [console log](https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/187927//consoleText)), but I don't think that makes sense, because we only publish test utils, not test modules. When I look at [roles-admin-test/build.gradle](https://github.com/liferay/liferay-portal/blob/master/modules/apps/roles/roles-admin-test/build.gradle#L3) (which also contains a StagedModelDataHandlerTest), I notice that it only compiles the test util, not the actual test module. Can you please take a look and validate my conclusion?

**Comment by jkappler** [comment]
Hi @jpince, you're completely right. Resent here: https://github.com/brianchandotcom/liferay-portal/pull/63271

**Pull request closed without merging**
