### PR TITLE
LRAC-4405

### PR DESCRIPTION
**Pull request by shinnlok**

### CODE REVIEW

**Comment by shinnlok** [comment]
ci:reopen

**Comment by shinnlok** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5aceb67904...5a3586ff34

**Comment by brianchandotcom** [comment]
@shinnlok @rachaelkoestartyo see 5a3586ff

This gets tricky if we have a lot of companies on a system... this is iterating through everyone per message.

```
		for (long companyId : _portal.getCompanyIds()) {
			_process(companyId);
		}
```

May not scale.

**Pull request closed without merging**
