### PR TITLE
LPS-58992 Implement XStreamConfigurator for Document Library

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
not related errors, trying ci:retest

**Comment by matethurzo** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
We just fixed the Oracle installation errors (VMs had bad startup scripts).

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d6ddacb102...17e460f82b

**Pull request closed without merging**
