### PR TITLE
LPS-59004

### PR DESCRIPTION
**Pull request by natecavanaugh**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/76efb9b1f1...4b9f2fce0e

**Comment by brianchandotcom** [comment]
@jonmak08 the thing I don't like about this fix is that every portlet.vm ftl will have to have this same if else statement. It should almost be put into portletDisplay.getSomeNewMethod... that then does the same logic so the templates can remain a one liner.

@jonmak08 please send a follow up pull. Thx.

**Comment by jonmak08** [comment]
Hey @brianchandotcom,

I submitted a pull request to @natecavanaugh for moving this into the java class as requested.

New Pull Request: https://github.com/natecavanaugh/liferay-portal/pull/3573

Please let me know if you have any questions.  Thanks!

**Comment by jonmak08** [comment]
Hey @brianchandotcom,

The fix you requested to move this check into ```portlet_display.getPortletDisplayName()``` is made at https://github.com/natecavanaugh/liferay-portal/pull/3583.

Please let me know if you have any questions.  Thanks!

**Pull request closed without merging**
