### PR TITLE
LPS-59069 read the control panel properties from the PanelApp

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest (we had some bad DDM code that broke and slowed down CI, we just rolled it back, so we should get real resultsn ow)

Testing again.

**Comment by brianchandotcom** [comment]
One more time ci:retest

**Comment by brianchandotcom** [comment]
@juliocamarero this is a real test failure with the scanXmlLog. It doesn't happen with any other pulls, and it's happened many times on this pull. Please resend. Sorry!

**Comment by brianchandotcom** [comment]
@juliocamarero this is also another reason why I can't get rid of the scanXmlLog, in this case, since you modified PortletTracker, and the errors are all related to portlets, it's very useful information.

also, Shuyang fixed the other scanXmlLog issues that had to deal with Elasticsearch. Now, if you do see scanXmlLog, they are probably real.

**Pull request closed without merging**
