### PR TITLE
LPS-82331 Improve performance of ContextController.matches() calls in…

### PR DESCRIPTION
**Pull request by shuyangzhou**
… org.eclipse.equinox.http.servlet.jar. Generated from https://github.com/rotty3000/rt.equinox.bundles/pull/24

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6ba8630391...c089801411

**Comment by brianchandotcom** [comment]
@shuyangzhou should we third-party this so we have this saved in patches? What's the current scheme? Just a branch somewhere?

**Comment by shuyangzhou** [comment]
@brianchandotcom yes, just a branch. We have been doing this for years.

**Pull request closed without merging**
