### PR TITLE
LPS-74128 Fix registration of language ResourceBundles that was causing LanguageFilter not to find the correct language properties.

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest (Bad slaves spoiled the pull request test)

**Comment by lesliewong92** [comment]
ci:retest (Batches ran on bad jenkins server)

**Comment by arthurchan35** [comment]
ci:retest

**Comment by izaera** [comment]
ci:reopen
ci:retest

**Comment by izaera** [comment]
ci:retest

**Pull request closed without merging**
