### PR TITLE
LPS-159625 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-159625

This is only for master.

@veroglez

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure cases are unrelated to changes.
See https://github.com/liferay-echo/liferay-portal/pull/9283
❌ ci:test:stable - 26 out of 27 jobs passed
❌ ci:test:relevant - 174 out of 188 jobs passed in 2 hours 10 minutes

**Comment by veroglez** [comment]
Hi Brian! I asked to @Alec-Shay about rephrasing the language key sent here https://github.com/brianchandotcom/liferay-portal/pull/121441, and he suggested I use this one https://github.com/brianchandotcom/liferay-portal/pull/121603/commits/91fbdf79803bd9f21d74240d3af00cc774265bb8. Do you think this is better understood?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/179f93530e...c5487c8eed

**Pull request closed without merging**
