### PR TITLE
LPS-110781 Fix cleanBaseline task

### PR DESCRIPTION
**Pull request by petershin**
@vicnate5

### CODE REVIEW

**Comment by petershin** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d51dd78196...af0499db31

**Comment by brianchandotcom** [comment]
thank you @petershin can you add a test to prevent this in the future?

**Comment by petershin** [comment]
yes

**Pull request closed without merging**
