### PR TITLE
LPS-92211 Fix npm package

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:test:change-tracking

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ced85b6023...99630e4ecd

**Comment by brianchandotcom** [comment]
@matethurzo I rolled this back as it caused a compile error in upstream.

**Pull request closed without merging**
