### PR TITLE
LPS-55754 Extract Journal OSGi services to Journal Service module

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by juliocamarero** [comment]
:tada: :balloon:

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5c99792877...435f312ee3

**Comment by brianchandotcom** [comment]
@epgarcia please see upstream. I renamed a few folders and modified some Bnd files that I need you to double check, specifically, 435f312ee3364e5f1dbb449a5d308767378d8816

**Comment by epgarcia** [comment]
Hey @brianchandotcom, I've reviewed your changes and they look ok. Thanks!

**Pull request closed without merging**
