### PR TITLE
master-vw-445

### PR DESCRIPTION
**Pull request by vicnate5**
@jkappler @marcellustavares

Not needed in 7.0.x at this time

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by jkappler** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@jkappler can you resend this? I think I didn't bring it because it (or another module) broke semantic versioning.

Thanks.

**Pull request closed without merging**
