### PR TITLE
LPS-65693 SF

### PR DESCRIPTION
**Pull request by rotty3000**
Rebased! /cc @mhan810 @shuyangzhou @Ithildir @CAustin582 @lionah @jrhoun

### CODE REVIEW

**Comment by rotty3000** [comment]
it seems mostly due to the semver issue. @brianchandotcom did you notice the package com.liferay.portlet was modified and without incrementing the semantic version?

**Comment by rotty3000** [comment]
... and not in this PR... in some previously merged change.

**Comment by rotty3000** [comment]
ci:retest I removed the semver change

**Comment by rotty3000** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@rotty3000 the lpkg-startup-jdk7 one is real.
Seems the verifying does not include the target platform's indexes?
```
     [exec] 20:47:38,156 ERROR [localhost-startStop-1][LPKGDeployerImpl:151] Unable to deploy LPKG file /opt/dev/projects/github/liferay-portal/bundles/osgi/marketplace/social-networking.lpkg
     [exec] com.liferay.portal.lpkg.deployer.LPKGVerifyException: LPKG validation failed with {[missing requirement com.liferay.social.networking.api; version=2.0.2; type=osgi.bundle [caused by: Unable to resolve com.liferay.social.networking.api version=2.0.2: missing requirement com.liferay.expando.kernel.model; version=[1.0.0,2.0.0)]],[missing requirement com.liferay.social.networking.service; version=2.0.2; type=osgi.bundle [caused by: Unable to resolve com.liferay.social.networking.service version=2.0.2: missing requirement com.liferay.counter.kernel.service; version=[1.0.0,2.0.0)]],[missing requirement com.liferay.social.networking.web; version=1.0.4; type=osgi.bundle [caused by: Unable to resolve com.liferay.social.networking.web version=1.0.4: missing requirement com.liferay.asset.kernel.model; version=[1.0.0,2.0.0)]]}
     [exec] 	at com.liferay.portal.lpkg.deployer.internal.LPKGVerifierImpl.verify(LPKGVerifierImpl.java:97)
     [exec] 	at com.liferay.portal.lpkg.deployer.internal.LPKGDeployerImpl.deploy(LPKGDeployerImpl.java:164)
     [exec] 	at com.liferay.portal.lpkg.deployer.internal.LPKGDeployerImpl$1.visitFile(LPKGDeployerImpl.java:125)
     [exec] 	at com.liferay.portal.lpkg.deployer.internal.LPKGDeployerImpl$1.visitFile(LPKGDeployerImpl.java:109)
     [exec] 	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:135)
     [exec] 	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199)
     [exec] 	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:69)
     [exec] 	at java.nio.file.Files.walkFileTree(Files.java:2602)
     [exec] 	at java.nio.file.Files.walkFileTree(Files.java:2635)
     [exec] 	at com.liferay.portal.lpkg.deployer.internal.LPKGDeployerImpl.activate(LPKGDeployerImpl.java:107)
```

**Comment by rotty3000** [comment]
Sorry I should have deactivated the validation of the lpkg files. I forgot
about the test for it.

**Comment by brianchandotcom** [comment]
@rotty3000 I just fixed my com.liferay.portlet in upstream. Will rebase this tonight and send a clean pull upstream to test.

**Comment by brianchandotcom** [comment]
@rotty3000 rebased, and regenerated manifest, with no changes, testing at https://github.com/brianchandotcom/liferay-portal/pull/39647

**Pull request closed without merging**
