### PR TITLE
LPS-61420

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey Brian,

Reverting your commits as I don't agree with them (see my comment here: https://github.com/brianchandotcom/liferay-portal/pull/33908)

These one is really the same as (for example):
JSONWebServiceInvokerAction.java:350
GetSyncDLObjectUpdateHandler.java:82
and these look fine to me.

This one is just a bit more confusing because it has "new RenameClassRemapper(name, newName)" as one of the parameters.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c518c3c83c...26b147aee2

**Comment by brianchandotcom** [comment]
@hhuijser those 2 examples you gave are different because they actually set a var:

GetSyncContextEvent getSyncContextEvent = new GetSyncContextEvent(

BeanSerializer beanSerializer = new BeanSerializer(

When you do that, you can line it up with the declared var and know that all that code belongs to that new var.

But with:

```
			@Override
			public void visitInnerClass(
 				String name, String outerName, String innerName, int access) {
 			}
  
 		};
```

It makes it look that method belongs to RemappingClassAdapter when in reality it belongs to RenameClassRemapper

They key is that the closing }; lines up with either a declared var, or an anonymous class, but is indented properly so you don't get it confused.

Please resend? I didn't merge this in. Thx.

**Comment by brianchandotcom** [comment]
@hhuijser also, see c41d89b94af53b6b644a5eaeb012016ecdeca9b5 5fd703a1d30c4ab738aa7111136a233f41216d98 and 453855d6eb159d6aebf1eacd45c83d65d4cab3c9

I only did those 3, I'm going to leave it to you to automate it. The key is to show which class the method belongs to.

Thx.

**Pull request closed without merging**
