### PR TITLE
LPS-61179 Applying same pattern where possible

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @juliocamarero

**Comment by juliocamarero** [comment]
:+1:

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f141250efc...25fd9a3073

**Comment by brianchandotcom** [comment]
@sergiogonzalez @zsolah see my simplification at 25fd9a3073b4b7097cfdd3bb1b9afa0a65995c1d

**Pull request closed without merging**
