### PR TITLE
LPS-189587 Set context to null when an operation has been performed

### PR DESCRIPTION
**Pull request by ccorreagg**
Related issue: https://liferay.atlassian.net/browse/LPS-189587

The purpose of this PR is to reset the context of the `VulcanBatchEngineExportTaskResourceImpl` and `VulcanBatchEngineImportTaskResourceImpl` when an operation has been performed

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1ae4cb60d5...b7124045fe

**Comment by brianchandotcom** [comment]
@ccorreagg I reverted this. ResourceImpl is supposed to be thread safe???? Please resend.

**Comment by ccorreagg** [comment]
See https://github.com/liferay-headless/liferay-portal/pull/1350

**Pull request closed without merging**
