### PR TITLE
LPS-110695 Adjust container type and paddings

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
john-co

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8769806ef6...d64ca0ef73

**Pull request closed without merging**
