### PR TITLE
LPS-71948 Make SPA ignore download links

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:reopen

**Comment by adolfopa** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by adolfopa** [comment]
Will resend after fixing tests.

**Comment by brianchandotcom** [comment]
@adolfopa the ModulesStructureTest.testScanBuildScripts broke because you removed some files in your commit.

See https://github.com/brianchandotcom/liferay-portal/pull/49330/commits/691185f9a7082df36ad9f4777ac70c7580f7759f

You removed settings.gradle. I'm fixing it and merging it.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b2a2d1a9ae...f9f33aaa20

**Comment by adolfopa** [comment]
Thanks!

**Pull request closed without merging**
