### PR TITLE
LPS-71399 | master

### PR DESCRIPTION
**Pull request by vicnate5**
@diogo-lins @thiago-rocha

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:reopen

**Comment by vicnate5** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@vicnate5 @thiago-rocha this is an SF issue with code from this pull.

See comment above


```
format-source:
     [java] Loading file:/opt/dev/projects/github/liferay-portal/portal-impl/classes/system.properties
     [java] Loading file:/opt/dev/projects/github/liferay-portal/portal-kernel/test-classes/unit/system-ext.properties
     [java] Loading file:/opt/dev/projects/github/liferay-portal/util-java/test-classes/unit/system-ext.properties
     [java] /opt/dev/projects/github/liferay-portal/modules/apps/forms-and-workflow/dynamic-data-lists/dynamic-data-lists-form-web/src/main/resources/META-INF/resources/admin/js/form_builder_render_rule_condition.js
     [java] Exception in thread "main" com.liferay.source.formatter.SourceMismatchException: ./modules/apps/forms-and-workflow/dynamic-data-lists/dynamic-data-lists-form-web/src/main/resources/META-INF/resources/admin/js/form_builder_render_rule_condition.js expected:&lt;...nderer-field']
     [java] 	}
     [java] );[]> but was:&lt;...nderer-field']
     [java] 	}
     [java] );[
     [java] ]>
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor.processFormattedFile(BaseSourceProcessor.java:1247)
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor.format(BaseSourceProcessor.java:560)
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor$1.call(BaseSourceProcessor.java:123)
     [java] 	at com.liferay.source.formatter.BaseSourceProcessor$1.call(BaseSourceProcessor.java:118)
     [java] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:574: Java returned: 1
      [get] Getting: http://test-1-19/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/93915//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20170328222535873.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20170328222535873.txt
```

Please fix and resend. Thx.

**Comment by brandizzi** [comment]
ci:retest

**Comment by diogo-lins** [comment]
ci:reopen

**Comment by diogo-lins** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/25e1e6a099...a9b34f22b8

**Pull request closed without merging**
