### PR TITLE
LRQA-30892 Check for null description

### PR DESCRIPTION
**Pull request by pyoo47**
Please publish after merging.

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:stop

**Comment by brianchiu** [comment]
ci:reopen

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
@pyoo47 published.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a6b425ddd3...1dab6b06ca

**Comment by brianchandotcom** [comment]
@pyoo47 see 05af2436304d65f9c5b9309f1e1be6924c77a4b8

**Pull request closed without merging**
