### PR TITLE
Lps 87800

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/91cebab734...bfed4034dc

**Comment by brianchandotcom** [comment]
@mtambara please backport? Should cherry pick easily.

**Comment by mtambara** [comment]
Backport sent here: https://github.com/brianchandotcom/liferay-portal-ee/pull/22901

**Comment by mtambara** [comment]
I just sent it to 7.1.x, do you want it in 7.0.x also?

**Pull request closed without merging**
