### PR TITLE
LRQA-30504 | master

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-30504

See 7.0.x pull here: https://github.com/brianchandotcom/liferay-portal/pull/46826

cc @xbrianlee @anthony-chu

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@ithildir we need to automate this fix 9408e27a5be704c45b6d19b40841a46da29815fa (7.0.x doesn't have that step)

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by anthony-chu** [comment]
cc @sharonchoi

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
