### PR TITLE
LPS-156658 Keep file entry type permissions in sync with its ddm structure

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-156658
Original PR1 comment:

> Each DLFileEntryType is tied to a DDM structure, that holds the
> metadata definitions defined in the document type itself.
> 
> The upload forms (and most probably other code) checks the permissions
> on the DDM structure to determine if the fields may be viewed/entered
> by a user. So the permissions on the structure need to be sychronized
> with the DLFilEntryType.

Original PR2 comment:

> Hey @matthiasblaesing,
> 
> I've added a couple of commits on top of your changes. These are basically variable renames and other minor changes so that the PR conforms to our coding conventions.
> 
> Can you take a look at my changes to make sure everything is ok?
> 
> Thanks!

@brianchandotcom resending this pull directly to you since after a few retries we confirmed this pull is not related to any of the failing tests in https://github.com/liferay-lima/liferay-portal/pull/3623.

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0d9561c061...d5dbe3e5e5

**Comment by brianchandotcom** [comment]
@matthiasblaesing thank you very much!

@adolfopa just d5dbe3e5e51aa86f8c5cba36ef367fb570441425

**Comment by matthiasblaesing** [comment]
@brianchandotcom thanks for merging and @Jeremy-Ch  @adolfopa @Hanlf @AliciaGarciaGarcia thank you for review and help getting this in.

**Pull request closed without merging**
