### PR TITLE
LPD-6611 adding more tests for CETDeployerTest

### PR DESCRIPTION
**Pull request by thiago-buarqque**

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:reopen

**Comment by thiago-buarqque** [comment]
Adding tests based on https://github.com/brianchandotcom/liferay-portal/pull/147906#issuecomment-1984238514

@brianchandotcom, two comments:

1. I found an issue regarding the `CommerceCETDeployerImpl`, it is supposed to return the `ServiceRegistration`, who coded that forgot about it. There was also a SF issue there.
2. On the CETDeployerTest: I remember you saying to sort the test from simple asserts to complex ones. I sorted considering using the variable `randomURL` is more 'complex' than not using it. 
If I sorted without considering it, there would be an empty line after the first assert (`TYPE_COMMERCE_CHECKOUT_STEP`) to create the randomURL, and the last assert would not be using the `randomURL` variable. Idk, it just did not feel right, I'd like to hear your thoughts about it.

cc: @ethib137

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e0271b7bd8...2ac4fab4c2

**Comment by brianchandotcom** [comment]
@thiago-buarqque see 2ac4fab4c246ee06ae1f48e416379e64e1f073cc

Good job on fixing a bug that a test found!

**Pull request closed without merging**
