### PR TITLE
master-qa-20569

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LRQA-20569

@brianchandotcom 
I missed one search and replace from https://github.com/brianchandotcom/liferay-portal/pull/33645. Not sure why because I used a txt editor to do it. But either way, this should hopefully fix the last of the consistently occurring poshi failures in the PR tester.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
I jsut merged it in .. please watch the pull

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/75643b6027...01a8d37510

**Comment by brianchiu** [comment]
@brianchandotcom Yup. I'll keep an eye on it.

**Comment by brianchandotcom** [comment]
This is a lot of broken tests Bchiu!

--
Brian Chan
Chief Software Architect
Liferay, Inc.
Enterprise. Open Source. For Life.
(626) 806-1190

**Comment by brianchiu** [comment]
@brianchandotcom 
Alright. Let me look at this...

**Comment by brianchiu** [comment]
@brianchandotcom 
Something on the login page changed.

**Pull request closed without merging**
