### PR TITLE
LPS-64981 move tlds and properties out of web accessible directory

### PR DESCRIPTION
**Pull request by jbalsas**
Hey Brian, this is a followup for https://github.com/brianchandotcom/liferay-portal/pull/38648.

We're getting rid of some modules we no longer need with this new mechanism.

Thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jbalsas you didn't need that fake gradle cache. I merged in everything except for that commit.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e61678415d...1ca65c5e02

**Comment by brianchandotcom** [comment]
@jbalsas I"m glad we can get rid of all those additional modules!

**Comment by marcellustavares** [comment]
Thanks @jbalsas!

**Comment by jbalsas** [comment]
Thanks @brianchandotcom!! 

I thought the cache was needed for the CI, but I think I get now when it's needed. ☺️

**Pull request closed without merging**
