### PR TITLE
LPS-99415 Handle the case of missing AssetDisplayPageEntry records, when the asset still has a display page

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by john-co** [comment]
Just started analyzing :)

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a325fa8157...bc1e36aafc

**Comment by brianchandotcom** [comment]
@jkappler @vendeltoreki test?

See bc1e36aafc71a66bc0feed6f1ca4665c74c125c8

**Pull request closed without merging**
