### PR TITLE
LPS-85964 In Display Pages for Basic WC, content and Map language keys are not being translated

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by brianchiu** [comment]
ci:close

**Comment by brianchiu** [comment]
Will resend to BChan after fixing the tests.

**Comment by brianchiu** [comment]
Sent to BChan here:
https://github.com/brianchandotcom/liferay-portal/pull/66762

**Pull request closed without merging**
