### PR TITLE
LPS-106886 Add support for BCP47 language ids in fromLanguageId method in LocaleUtil

### PR DESCRIPTION
**Pull request by javierdearcos**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cc013002c4...30220d7e71

**Comment by brianchandotcom** [comment]
@javierdearcos @nhpatt I backported this all the way to 7.0.x.

See 30220d7e71bb8569cadea9152dfa55e3f1d7590e

**Comment by nhpatt** [comment]
Thanks!

**Comment by javierdearcos** [comment]
thank you

**Pull request closed without merging**
