### PR TITLE
 LPS-79480 Test 

### PR DESCRIPTION
**Pull request by topolik**
Hi Brian,

test for https://github.com/brianchandotcom/liferay-portal/pull/57261#issuecomment-382057710

Thanks.

### CODE REVIEW

**Comment by topolik** [comment]
ci:test

**Comment by topolik** [comment]
ci:reopen CI fails, not sure if you want to run tests again. The sent test itself works for me :)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a06b8e5118...1b2003392d

**Comment by brianchandotcom** [comment]
Thx @topolik !

**Pull request closed without merging**
