### PR TITLE
[Remove Stream/Optional usage] LPS-172199 Remove usage of Stream in module segments-web | part 3

### PR DESCRIPTION
**Pull request by dantewang**
FYI @shuyangzhou @tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ff9d8fd816...f5b6b5ae08

**Comment by brianchandotcom** [comment]
@W2jx @dantewang just f5b6b5a

**Comment by brianchandotcom** [comment]
@W2jx @dantewang j see f5b6b5ae08040697fed4c12474218c85f3819251

**Comment by W2jx** [comment]
I got it. Thank you.

**Pull request closed without merging**
