### PR TITLE
LPS-59194

### PR DESCRIPTION
**Pull request by topolik**
Hi Brian,

a regression fix caused by 1dc8917 in https://github.com/brianchandotcom/liferay-portal/pull/30836

Thank you.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d0a6971384...9d43340a5e

**Comment by brianchandotcom** [comment]
@juangon how come the UI tests you gave to @brianchiu didn't error out without this fix? Please update test-runtime-* portlets for this? Or are they unrelated?

**Comment by juangon** [comment]
Hi @brianchandotcom is unrelated, this case was LanguageServlet (https://issues.liferay.com/browse/LPS-59418).

**Comment by juangon** [comment]
To summarize, it was a corner case I didn't considered (when those requests came directly from a servlet without having other filters that wrap a ServletRequestWrapper)

**Comment by brianchandotcom** [comment]
Thx @juangon

**Pull request closed without merging**
