### PR TITLE
Lps 74490

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@shuyangzhou how come the sdk.version worked now?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e01f81a82e...ffd65537cb

**Comment by shuyangzhou** [comment]
@brianchandotcom the sdk is always downloaded with the correct version. The issue is https://github.com/brianchandotcom/liferay-portal/pull/51419/commits/7161e69adff160e385bd9ce22814801f4b460501#diff-45673ba8a3aee4df6072d3b5523a9182R14 overwrites the unzipped the sdk. Therefore we must fake gradle cache for the gradle.plugins and gradle.plugins.defaults to make sure it uses the right version of whip to do the overwrite.

**Pull request closed without merging**
