### PR TITLE
LPS-70865

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
@brianchandotcom the semver failures are not related to my change @ealonso might know what's causing it?

The other test failure is also unrelated

**Comment by matethurzo** [comment]
ci:reopen

**Comment by ealonso** [comment]
See: https://github.com/brianchandotcom/liferay-portal/pull/47617

**Comment by matethurzo** [comment]
Thanks @ealonso!

**Comment by brianchandotcom** [comment]
ci:retest 

Now that this is fixed in https://github.com/brianchandotcom/liferay-portal/pull/47657

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
See 2bd5c9d4f5fff3616966e69c1c60750aa9b64c7f

**Pull request closed without merging**
