### PR TITLE
LPS-105616 Create Organizations POST endpoints

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-105616](https://issues.liferay.com/browse/LPS-105616).<br><br>Hey Brian, this includes the POST endpoint with support for adding an organization with basic information and Addresses for the contact information. EmailAddress, Website, and Phone still need to be implemented.<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow

### CODE REVIEW

**Comment by drewbrokke** [comment]
cc @nhpatt

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/91bb210d31...044462c24c

**Comment by brianchandotcom** [comment]
argh.. I merged this.. but then just saw that tests are now broken:

```
Job Results:
741 Tests Passed.
3 Tests Failed.

AXIS_VARIABLE=0,label_exp=!master #101823
OrganizationResourceTest.testPostOrganization
java.lang.UnsupportedOperationException: This method needs to be implemented
	at com.liferay.headless.admin.user.resource.v1_0.test.BaseOrganizationResourceTestCase.testPostOrganization_addOrganization(BaseOrganizationResourceTestCase.java:499)
	at com.liferay.headless.admin.user.resource.v1_0.test.BaseOrganizationResourceTestCase.testPostOrganization(BaseOrganizationResourceTestCase.java:488)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$2.evaluate(TestExecutorRunnable.java:234)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
	at com.liferay.portal.kernel.test.rule.TimeoutTestRule$1.e...
SegmentResourceTest.testGraphQLGetSiteSegmentsPage
java.lang.NullPointerException
	at com.liferay.headless.admin.user.resource.v1_0.test.BaseSegmentResourceTestCase.testGraphQLGetSiteSegmentsPage(BaseSegmentResourceTestCase.java:324)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$2.evaluate(TestExecutorRunnable.java:234)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
	at com.liferay.portal.kernel.test.rule.TimeoutTestRule$1.evaluate(TimeoutTestRule.java:89)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:143)
	at o...
PortalLogAssertorTest.testScanXMLLog
junit.framework.AssertionFailedError: 
Exception while fetching data (/segments) : java.lang.NullPointerException
java.lang.RuntimeException: java.lang.NullPointerException
	at com.liferay.portal.vulcan.internal.graphql.servlet.GraphQLServletExtender$LiferayMethodDataFetcher.get(GraphQLServletExtender.java:1824)
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:258)
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:197)
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:72)
	at graphql.execution.Execution.executeOperation(Execution.java:160)
	at graphql.execution.Execution.execute(Execution.java:101)
	at graphql.GraphQL.execute(GraphQL.java:591)
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:521)
	at graphql.GraphQL.executeAsync(GraphQL.java:495)
	at graphql.GraphQL.execute(GraphQL.java:426)
	at graphql.servlet.GraphQLQueryInvoker.query(GraphQLQueryInvoker.java:102)
	at graphql.servlet.GraphQLQueryInvoker.query(GraphQLQueryInvoker.java:98)
	at graphql.servlet.GraphQLQueryInvoker.query(GraphQLQueryInvoker.java:44)
	at graphql.servlet.AbstractGraphQLHttpServlet.query(AbstractGraphQLHttpServlet.java:338)
	at graphql.servlet.AbstractGraphQLHttpServlet.lambda$init$4(AbstractGraphQLHttpServlet.java:212)
	at graphql.servlet.AbstractGraphQLHttpServlet.doRequest(AbstractGraphQLHttpServlet.java:309)
	at graphql.servlet.AbstractGraphQLHttpServlet.doRequestAsync(AbstractGraphQLHttpServlet...
```

Reverted everything in upstream. When you resend, can you just recherry pick the original commits (including my changes, please read them), don't just revert the revert.

Please fix tests and resend. Thx!

**Comment by brianchandotcom** [comment]
For the broken tests, see CI (wasn't due to my changes)

**Comment by drewbrokke** [comment]
Sorry @brianchandotcom. I keep forgetting about the regen adding methods that need to be implemented. That's my bad. I'll re-send with your changes, but I'm also going to add changes that remove the enum from the schema - that was a mistake on my part.

**Pull request closed without merging**
