### PR TITLE
LPS-77924 Updates clay to v2.0.0-rc.1

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jpince** [comment]
ci:retest

**Comment by jbalsas** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7ba3c7cd52...318ae8e9d7

**Pull request closed without merging**
