### PR TITLE
LPS-74024

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test

**Comment by matethurzo** [comment]
ci:reopen @brianchandotcom the source format problem is unrelated

**Comment by matethurzo** [comment]
no additional failed tests

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7eb57f3ee8...885524c49c

**Pull request closed without merging**
