### PR TITLE
master-qa-20445

### PR DESCRIPTION
**Pull request by vicnate5**
https://issues.liferay.com/browse/LRQA-20445

@brianchiu Fix for the calendar test that was regularly failing due to user index bug. I am re-adding the test to the PR tester.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Nice @vicnate5 I'm just merging this in without waiting for result...

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d6f7353d02...8827a002d5

**Comment by brianchandotcom** [comment]
@vicnate5 is anyone working on the user indexer bug?

**Comment by vicnate5** [comment]
@brianchandotcom it is assigned to Matt on Shuyang's team 
https://issues.liferay.com/browse/LPS-61194

**Comment by brianchiu** [comment]
@brianchandotcom @vicnate5 

@alee8888 has also been looking into it a little bit. I'll check up on it again tomorrow. We need to make sure this issue gains traction.

**Pull request closed without merging**
