### PR TITLE
LPS-101511 Baseline

### PR DESCRIPTION
**Pull request by marcellustavares**
@brianchandotcom, I sent you more information about this pull by email. Thanks

cc @darquesdev @dgarciasarai @epgarcia

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@preston-crary  email from @marcellustavares:

Hi Brian,

I understand your concern. Sorry I couldn't anticipate the needs for the analytics-API back then.

The reason for this change is due to some synchronization that needs to happen between analytics.js and segments-experiment-web for a/b testing to work.

segments-experiment-web introduces some context information such as experiment ID and variant ID. In our first iteration, I suggested to Eduardo to just grab the reference to the Analytics component and inject those variables (see https://github.com/liferay/liferay-portal/blob/master/modules/apps/segments/segments-experiment-web/src/main/resources/META-INF/resources/dynamic_include/top_head.jsp)

The problem with this approach is the loading order, segments-experiment-web may load after the portal top_head.jsp and the pageView event fired by the analytics.js (https://github.com/liferay/liferay-portal/blob/master/portal-web/docroot/html/common/themes/top_js.jspf#L496) go without the experiment context information.

We tried to hack with pure JS to prevent changes in the backend but all possible solutions proved to be unreliable.

So, we considered 3 options:

1. Adding Analytics JS context resolution as backend portal-kernel service and keep the analytics script the portal top_head.jsp.
2. Move Analytics JS to analytics-web module and reintroduce the need of the analytics-API for Analytics JS context resolution (adopted solution)
3. Add Analytics Context Contributor API to analytics-web and export this package (7.2 only) but probably SF will complain about this.

Let me know if you want to have a quick call about it.

Thanks

**Comment by brianchandotcom** [comment]
@marcellustavares I sent it to https://github.com/Preston-Crary/liferay-portal/pull/883

It doesn't feel right to me.. and I think @preston-crary would come up with a better solution.

**Comment by Preston-Crary** [comment]
@marcellustavares can this be fixed by setting a service.ranking property in AnalyticsTopHeadDynamicInclude? That controls the order of the includes.  If both of them have the same service ranking (which is how it is now), then they are sorted by loading order.

**Comment by marcellustavares** [comment]
Currently analytics.js is included in the top_js.jsp in the portal web. It's not even a dynamic include. 

The problem is that we want the pageview event fired by analytics.js to have the context info contributed by the segments module.

**Comment by Preston-Crary** [comment]
Then can we have https://github.com/liferay/liferay-portal/blob/master/modules/apps/segments/segments-experiment-web/src/main/java/com/liferay/segments/experiment/web/internal/servlet/taglib/SegmentsExperimentAnalyticsTopHeadJSPDynamicInclude.java#L78 use pre instead of post?

It's okay if it needs both.

**Comment by marcellustavares** [comment]
If it uses pre, the analytics.js may not be ready.

**Comment by Preston-Crary** [comment]
What part of it is not ready?

**Comment by Preston-Crary** [comment]
What makes it not being ready a problem?

**Comment by marcellustavares** [comment]
The Analytics component which is just created after the pre includes.

**Comment by marcellustavares** [comment]
If it's not ready, the segments module can't contribute with the required variables.

**Comment by Preston-Crary** [comment]
If we pull the analytics part into a dynamic include, like you did in the first commit then I think we can use pre / post to control component creation and the firing of the send event (pre for creation, post for sending) and configure the service.ranking to make sure segments is always between those calls.  Do you think that will work?

If that won't work please email me how I can test this locally so I can see the problem and get a better understanding of it and I'll take a look tomorrow.

**Comment by marcellustavares** [comment]
@shinnlok is there an AC instance Preston can easily connect to understand the issue?

**Pull request closed without merging**
