### PR TITLE
master-qa-17389

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LRQA-17839

This adds a category test to the PR tester. (To make sure https://issues.liferay.com/browse/LPS-58357 does not happen again.)

CC @jhendley

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@michaelhashimoto @kiyoshilee

What happened here?

```
BUILD FAILED
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-test-portal-acceptance-pullrequest.xml:279: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:3811: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:3853: Could not find 'test-portal-acceptance-pullrequest-source(master)' invocation url. FAILURE!
```

**Comment by brianchandotcom** [comment]
Not merging. Please resend @brianchiu

**Comment by brianchiu** [comment]
resent in:
https://github.com/brianchandotcom/liferay-portal/pull/30232

**Pull request closed without merging**
