### PR TITLE
LPS-84225 Auto SF

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by jkappler** [comment]
@brianchiu, @kyle-miho: It seems we have to change the poshi tests for reordering.....some locators maybe

@jpince: this pull fixes some poshi tests that are failing

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1d809e9c8d...2d93944d94

**Comment by brianchandotcom** [comment]
@jkappler see my minor change in upstream.

**Pull request closed without merging**
