### PR TITLE
LPS-50958 Preview for document changed in MS Office is not updated

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @brianchandotcom 

This is a pull request forwarded from https://github.com/IstvanD/liferay-portal/pull/10

Could you please review it?

Thank you.

Best regards,
István

### CODE REVIEW

**Comment by kiyoshilee** [comment]
@IstvanD in order for your pull request to be tested you will need to publicize your association with the liferay organization on your github profile. Please see this <a href="https://help.github.com/articles/publicizing-or-concealing-organization-membership/"> link</a> for details on how to do so.

**Comment by IstvanD** [comment]
Hi @kiyoshilee 

Thanks for the tip. I publicized my association with the organization.

**Comment by kiyoshilee** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0b914f761a...ab94fdd895

**Pull request closed without merging**
