### PR TITLE
LPS-69303 JSON WS Service Client should not throw communication exception on HTTP ERROR 40x, 50x (version manually increased - signatures same but content returned may affect consumers) - please publish to Nexus

### PR DESCRIPTION
**Pull request by igorbeslic**
Hi Brian please review... I moved logic from LCS client's implementation to base class. Thank you very much. @ivicac and @mladencikara this code was crucial for LCS client to work, you shouldn't delete it.

### CODE REVIEW

**Comment by igorbeslic** [comment]
ci:reopen

**Comment by jpince** [comment]
@igorbeslic semantic versioning issue
```
     [echo]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [echo] = ================================================== ========== ========== ========== ========== ==========
     [echo] * com.liferay.portal.kernel.util                     MINOR      7.11.0     7.11.0     7.12.0     VERSION INCREASE REQUIRED
```

**Comment by jpince** [comment]
ci:close

**Comment by jpince** [comment]
apologies, the semantic versioning failure was unrelated.

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f002d01a5c...377b2299d7

**Comment by brianchandotcom** [comment]
@igorbeslic I merged this pull but did NOT include your manual change to bnd.bnd.

You should never manually update it because it can be incorrect. In this case, there is no API change, so it should not be a minor version (second number) but should be a micro version change (last number), but even that is done automatically when we publish the file.

Basically, run

gradlew :apps:foundation:petra:petra-json-web-service-client:baseline

and only send the changes that are done automatically. Never touch bnd.bnd versions or package-info manually.

Thx.

**Comment by brianchandotcom** [comment]
@igorbeslic also see my SF in 377b2299d7bacbce9a212d1221bdb023c2e53700

**Comment by jpince** [comment]
ci:close

**Pull request closed without merging**
