### PR TITLE
LPS-58210 move responsability to the layout controller type

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Already reviewed by @JorgeFerrer.

@topolik could you please have a look? we have tried to explain the logic in the commits but please ping us if you have any question.

thanks!

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@juliocamarero consistent new failures for integration-*

Please resend.

**Comment by brianchandotcom** [comment]
Hmm... may not be your fault. Not sure how those bugs got there. Coordinating with shuyang.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ca7ca58f01...a5127e6e54

**Comment by brianchandotcom** [comment]
The broken tests were from https://github.com/brianchandotcom/liferay-portal/pull/30395 which I since reverted.

**Comment by topolik** [comment]
Looks good, thanks @juliocamarero!

-- tom +

**Pull request closed without merging**
