### PR TITLE
LPS-90450 Get portlets not only from the layout type but using portlet preferences as well to support portlets on the content pages

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by arboliveira** [comment]
@brianchandotcom Please do not merge.

@pavel-savinov The fix as proposed still needs changes to fulfill the intended use case. Please see my explanation at: https://issues.liferay.com/browse/LPS-90450?focusedCommentId=1725816&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1725816

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@arboliveira just read your comment.. and reverted.

**Comment by arboliveira** [comment]
Followed up by https://github.com/brianchandotcom/liferay-portal/pull/69810

**Pull request closed without merging**
