### PR TITLE
LPS-81714 Uses new openToast command to show spa notifications

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/975275db4d...eeac05e10a

**Comment by jpince** [comment]
@jbalsas had to revert this... https://github.com/liferay/liferay-portal/compare/90d6d646625954d790d4692b79edb6bf82ffdf65...bdb216addbe1fe490b469295e1ca608dd41f9011. It passed smoke for tomcat/mysql, but it's throwing console errors for all other app servers and databases :/. It's also visible in some of the logs for functional tests that failed here (e.g. [LocalFile.Forms#AddElementSetsWithTranslation](https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/190586//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Forms_AddElementSetsWithTranslation_)). @xbrianlee suggested it might throw the error on the slower stacks.
`JAVA_SCRIPT_ERROR: TypeError: this.timeoutAlert.close is not a function [http://localhost:8080/combo/?browserId=firefox&minifierType=&languageId=en_US&b=7100&t=1527885640915&/o/js/resolved-module/frontend-taglib-clay$clay-icon@2.1.4/lib/ClayIcon.soy.js&/o/js/resolved-module/frontend-taglib-clay$clay-icon@2.1.4/lib/ClayIcon.js&/o/js/resolved-module/frontend-taglib-clay$clay-component@2.1.4/lib/ClayComponent.js&/o/js/resolved-module/frontend-taglib-clay$clay-button@2.1.4/lib/ClayButton.soy.js&/o/js/resolved-module/frontend-taglib-clay$clay-button@2.1.4/lib/ClayButton.js&/o/js/resolved-module/frontend-taglib-clay$clay-alert@2.1.4/lib/ClayAlertBase.soy.js&/o/js/resolved-module/frontend-taglib-clay$clay-alert@2.1.4/lib/ClayAlertBase.js&/o/js/resolved-module/frontend-taglib-clay$clay-alert@2.1.4/lib/ClayAlert.soy.js&/o/js/resolved-module/frontend-taglib-clay$clay-alert@2.1.4/lib/ClayAlert.js&/o/js/resolved-module/frontend-taglib-clay$clay-alert@2.1.4/lib/ClayStripe.soy.js&/o/js/resolved-module/frontend-taglib-clay$clay-alert@2.1.4/lib/ClayStripe.js&/o/js/resolved-module/frontend-taglib-clay$clay-alert@2.1.4/lib/ClayToast.soy.js&/o/js/resolved-module/frontend-taglib-clay$clay-alert@2.1.4/lib/ClayToast.js&/o/js/resolved-module/frontend-taglib-clay$clay-alert@2.1.4/lib/all/alert.js&/o/js/resolved-module/frontend-js-web@2.0.0/liferay/toast/commands/OpenToast.es.js&/o/js/resolved-module/frontend-js-spa-web@2.0.0/liferay/surface/Surface.es.js&/o/js/resolved-module/frontend-js-spa-web@2.0.0/liferay/util/Utils.es.js&/o/js/resolved-module/frontend-js-spa-web@2.0.0/liferay/app/App.es.js&/o/js/resolved-module/frontend-js-spa-web@2.0.0/liferay/screen/RenderURLScreen.es.js&/o/js/resolved-module/frontend-js-spa-web@2.0.0/liferay/init.es.js:167]`
[Jenkins Log](https://test-1-1.liferay.com//userContent/jobs/test-portal-acceptance-upstream%28master%29/builds/4013/jenkins-report.html)

**Comment by jbalsas** [comment]
So sorry about that @jpince, @brianchandotcom! 😢 

I'll take a look at this as soon as possible, as this is a must for the release. Thanks for catching this so fast, I'll try to see if I can reproduce 👍

**Comment by jpince** [comment]
@jbalsas sounds good

**Pull request closed without merging**
