### PR TITLE
Lps 51464

### PR DESCRIPTION
**Pull request by shuyangzhou**
@michaelhashimoto @kiyoshilee, if this somehow affects QA's build processes (hope not), please let us know

@brianchandotcom for linux/unix users, this changes nothing, but for windows users, they should see some build time saving as it no longer forks new ant process during ant all. But if for any reason they see the previous jar locking issue again (we tried, could not reproduce on current master in windows VMs), please redirect them to us, we will figure out a fix for them.

When this is in, for all platforms, ant all is only one ant process, then we can proceed with the further JGit optimization.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@matethurzo if your build breaks, it's becasue of this windows change by Shuyang.. but it shouldn't. Just fyi.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ae39c32d6e...2e9c97a8c0

**Comment by brianchandotcom** [comment]
@willnewbury can you backport if necessary? I don't think we have any in ee-6.2.x or ee-6.1.x, but please double check. Thx.

**Comment by brianchandotcom** [comment]
@willnewbury actually, I just checked, we have to backport this. Please do so. Thx.

**Comment by matethurzo** [comment]
Thanks @brianchandotcom, on windows it's building perfectly. Also a little bit faster I'd say (couple of minutes minus), thanks for that @shuyangzhou!

**Pull request closed without merging**
