### PR TITLE
LPS-83376 Adding missing condition

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/67bed44457...de8133c17d

**Comment by brianchandotcom** [comment]
@4lejandrito please see my changes in upstream. I made quite a few. Thx.

@sergiogonzalez @4lejandrito I assume this is NOT to be backported since it looks like a new feature.

**Comment by 4lejandrito** [comment]
You're right @brianchandotcom, this is not to be backported. 

Thanks!

**Pull request closed without merging**
