### PR TITLE
Lps 63730

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:stop all ee db nodes are hanging now

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by sharonchoi** [comment]
The ApplicationdisplaytemplatesUsecase#AddRSSADTViaPortletConfiguration failure is unrelated and has been failing multiple pulls. 
https://testray.liferay.com/home/-/testray/case_results/40139533

Test has been disabled at head:
liferay@6fd2f84

WEM QA will look into the issue and restore the test LRQA-24557.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c7b023a09a...0aad064dca

**Pull request closed without merging**
