### PR TITLE
LPS-76116 Minor change to move the converter to internal package

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test

**Comment by matethurzo** [comment]
ci:reopen

**Comment by matethurzo** [comment]
@brianchandotcom failures are unrelated

**Comment by brianchandotcom** [comment]
@matethurzo I merged this, with minor wordsmith changes. Should we do this if and only if the DB is set to Sybase?

**Comment by matethurzo** [comment]
@brianchandotcom i think this is good for everything, this change will make the timestamp agnostic to what DB we use making the staging process a bit more robust

**Pull request closed without merging**
