### PR TITLE
COMMERCE-7080 + COMMERCE-7115 resolved conflicts

### PR DESCRIPTION
**Pull request by matijapetanjek**
Hi @brianchandotcom, I'm sending PR directly as it already passed tests https://github.com/brianchandotcom/liferay-portal/pull/106249.

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:reopen

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:reopen

**Comment by igorbeslic** [comment]
ci:test:sf

**Comment by igorbeslic** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ee1580e395...99b1c9e9d9

**Comment by brianchandotcom** [comment]
@igorbeslic @matijapetanjek I merged this, see 7c0e18e8

But you have transaction boundary errors in EditBatchPlannerPlanMVCActionCommand

PLease follow the pattern in PollsQuestionLocalServiceImpl and EditQuestionMVCActionCommand.java where we make all the updates in the service tier.

**Pull request closed without merging**
