### PR TITLE
LPS-128837

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
@pei-jung see https://github.com/brianchandotcom/liferay-portal/pull/102317/commits/af7bd2e73a8e5f2b97e4d8644baed49b4c5b53a7
That okay?

**Comment by pei-jung** [comment]
looks good, thanks @hhuijser!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/993984928a...993984928a

**Pull request closed without merging**
