### PR TITLE
LRQA-24088 Unit tests for StringUtil methods not tested yet

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by vicnate5** [comment]
Test failures are unrelated to this pull.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4b3d0a8f54...3b1ba04a03

**Comment by brianchandotcom** [comment]
Nice job @evannagayama on improving test coverage.

**Pull request closed without merging**
