### PR TITLE
LPS-91676 Revert "LPS-91163 Replace stream with forEach"

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @brianchandotcom, @shuyangzhou,

The 2 commits being reverted broke the expected behaviour of the code (See [LPS-91676](https://issues.liferay.com/browse/LPS-91676)). 

@shuyangzhou if there is a very good reason not to be using streams here we would like to know about it. For the moment we prefer to keep the old code that was working fine.

Thanks!

@adolfopa, @aliciagarciagarcia

**Comment by brianchandotcom** [comment]
@4lejandrito can you fix it using the new way (without using streams)?

The reason we went away from streams (performance according to SZ) and I found

```
	private static <E, T extends Throwable> Consumer<E> _toSafeConsumer(
		UnsafeConsumer<E, T> unsafeConsumer) {

		return (E e) -> {
			try {
				unsafeConsumer.accept(e);
			}
			catch (Throwable t) {
				ReflectionUtil.throwException(t);
			}
		};
	}

```

in EditEntryMVCActionCommand.java very ugly.

**Comment by shuyangzhou** [comment]
@4lejandrito the problem on the ticket can not be reproduced. I and @vicnate5 have both tried. Do you still see it on your side?

**Comment by 4lejandrito** [comment]
Hi @shuyangzhou 

I still reproduce it on my end, I will try again tomorrow. https://issues.liferay.com/browse/LPS-93526 is caused by this too and should be happening consistently.

**Comment by 4lejandrito** [comment]
Actually the original issue can't be caused by your changes, I linked it by mistake. [LPS-93526](https://issues.liferay.com/browse/LPS-93526) is the right one.

**Comment by 4lejandrito** [comment]
The cause is that we were calculating the intersection of a bunch of sets whereas now we are adding all the elements. See https://github.com/brianchandotcom/liferay-portal/commit/6de17a7cff050af4e22b53f776e5c21bb95e6822#diff-84b908d4ada31e4fbfa57cfdc9e324d8L91.

**Comment by shuyangzhou** [comment]
Ok, that one is real, sent fix here https://github.com/brianchandotcom/liferay-portal/pull/71038

**Comment by 4lejandrito** [comment]
Thanks @shuyangzhou!

**Pull request closed without merging**
