### PR TITLE
Commerce 10750

### PR DESCRIPTION
**Pull request by brianikim**
Resent from:
https://github.com/brianchandotcom/liferay-portal/pull/131718

### CODE REVIEW

**Comment by brianikim** [comment]
ci:reopen

**Comment by brianikim** [comment]
@brianchandotcom , only change was the rebase fix: https://github.com/brianchandotcom/liferay-portal/pull/131784/commits/b8458ac28396ab1d82f3143c350687ba1872783b that occurred because of this commit introduction 3 weeks ago: https://github.com/brianchandotcom/liferay-portal/commit/f6267f8347ba260b2bff4d5e8edf065e9c0732ee

**Comment by brianikim** [comment]
@brianchandotcom , let me know if you want this PR to go through regular ci:tests and resent that way. I know COMMERCE force-forwarded couple PRs in the past and had issues so we can go that route if you wish to be safe.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/32c7c92a1f...3478f9f887

**Comment by brianchandotcom** [comment]
@brianikim see minor changes in my origin. Thx.

**Pull request closed without merging**
