### PR TITLE
Lps 67565

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/971f1c2798...0fbfcb74c4

**Comment by brianchandotcom** [comment]
@topolik what about master-private?

@hhuijser can you review the commits in this pull? We need to auto enforce what @topolik just did.

**Comment by hhuijser** [comment]
@topolik, can you describe the rules you'd like in SF?

**Comment by topolik** [comment]
Hi @hhuijser, 

I think what Brian means are those 3 commits that relates how we parse portlet modes in OSGi portlets (https://github.com/liferay/liferay-portal/blob/451e1272e9e5e00b4f5f73971da48447cac52301/modules/apps/static/portal-osgi-web/portal-osgi-web-portlet-tracker/src/main/java/com/liferay/portal/osgi/web/portlet/tracker/internal/PortletTracker.java#L886-L914):

 * 86f5a42 ... `javax.portlet.supports.mime-type` is unknown property, we don't read it anywhere
 * aa3f31f ... we parse `javax.portlet.portlet-mode` but it has a strict syntax of `...=mime-type;mode` (and text/html is there by default)
 * ae557b8 ... config mode should be also declared

Thanks.

**Comment by topolik** [comment]
The master-private changes ... https://github.com/brianchandotcom/liferay-portal-ee/pull/26360

**Pull request closed without merging**
