### PR TITLE
LPS-92231 Add test

### PR DESCRIPTION
**Pull request by epgarcia**
@pavel-savinov @jkappler @ealonso

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:test:msb

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
ci:reopen

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/abef7fffa8...6d797286c3

**Pull request closed without merging**
