### PR TITLE
LPS-99003 New portal-search-elasticsearch7 module

### PR DESCRIPTION
**Pull request by BryanEngler**
⚠️ **ci:test:search - 20 out of 22 jobs passed** https://github.com/BryanEngler/liferay-portal/pull/391#issuecomment-517070501
✅ The only failures unique to this pull are also failing on the search-ci server https://search-ci.liferay.com/job/integration/lastCompletedBuild/testReport/

Author(s): @BryanEngler
Cc: @arboliveira @lipusz @xbrianlee @joshchong

NOTE:
This pr is for our new Elasticsearch 7 module. It contains the merge commit trick that we use to preserve the git history for the "new" files in the Elasticsearch 7 module. If you need to rebase the pr, these are the commands I use when rebasing:

`git rebase master --rebase-merges`

When the merge conflict happens:
`git commit -a --no-edit`
`git rebase --continue`

There should only be one merge conflict, but if any changes were made to the modules/apps/portal-search-elasticsearch6 directory from other prs before you merge this pr, it could cause additional merge conflicts. If that happens I can rebase onto those and resend.

I will also be sending prs for 7.2.x later on.

---
*[Story] Elasticsearch 7: Create new "inactive" module portal-search-elasticsearch7*
https://issues.liferay.com/browse/LPS-99003

### CODE REVIEW

**Comment by lipusz** [comment]
@BryanEngler for 7.2.x, will you set `Liferay-Releng-Bundle: ` to `false`?

**Comment by BryanEngler** [comment]
@lipusz ya for 7.2.x ill sync up with you and make sure we have everything covered

**Comment by brianchandotcom** [comment]
@BryanEngler not able to merge.. mass rebase conflicts. @arboliveira is this one of those where we have to merge right away without rebase?

**Comment by BryanEngler** [comment]
@brianchandotcom When i said "There should only be one merge conflict", i meant that the merge commit should be the only **commit** that generates a conflict, but in that one commit/conflict **all** of the _files_ will be conflicting... if its easier for me to just rebase and resend let me know when you want to do it

**Comment by brianchandotcom** [comment]
Yeah, can you rebase and resend?

**Comment by BryanEngler** [comment]
sure, on top of https://github.com/brianchandotcom/liferay-portal/commit/89c081f67ebc55042db2f3e323fa48b36e11628b or which sha?

**Comment by BryanEngler** [comment]
@brianchandotcom https://github.com/brianchandotcom/liferay-portal/pull/76468

**Pull request closed without merging**
