### PR TITLE
LPS-59341

### PR DESCRIPTION
**Pull request by Ithildir**
cc @hhuijser

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1ed6f604b3...9d886e7b0d

**Comment by brianchandotcom** [comment]
Hey Andrea, I didn't merge this in.. the fix doens't look right to me? Let's talk tomorrow for a better fix. Thx.

**Comment by hhuijser** [comment]
@Ithildir @brianchandotcom 

I agree that this fix is not the best. See email I sent earlier today...

**Comment by Ithildir** [comment]
Different approach sent to https://github.com/brianchandotcom/liferay-portal/pull/31495

**Pull request closed without merging**
