### PR TITLE
LPS-61420

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:retest

**Comment by jpince** [comment]
Hi @hhuijser, it looks like this may be a bug, as Bookmarks is no longer visible in the Product Menu or add panel.  We received the following error message after building on your branch, indicating that Bookmarks may not have deployed properly. https://gist.githubusercontent.com/austinchiang/3184d565f21d7e9221df/raw/ed112942ba681ed8ab684951715113880649285a/gistfile1.txt

**Comment by brianchandotcom** [comment]
@hhuijser please resend. Thx.

**Comment by hhuijser** [comment]
@Ithildir

The order for imports in bnd.bnd is important?
Look at the bnd.bnd in bookmarks... we're just ordering.
Maybe com.liferay.bookmarks.* needs to be after all the others with com.liferay.bookmars.?

**Comment by hhuijser** [comment]
Just tested and it seems that the .* indeed needs to come last, otherwise it complains about duplicates

**Pull request closed without merging**
