### PR TITLE
LRQA-25404 Implement Sybase data dump import logic.

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-25404

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 @michaelhashimoto how come these tomcats are taking so long to startup?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8fa7deb101...c42abc5dd4

**Comment by pyoo47** [comment]
Two of the failures above are database upgrade failures. @brianchiu has reported to me that these issues are sporadically failing.

Postgresql
```
[java] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.upgrade.UpgradeException: org.postgresql.util.PSQLException: ERROR: column "fileentryid" does not exist
     [java]   Position: 45
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:91)
     [java] 	at com.liferay.portal.upgrade.Pre7UpgradeProcess.upgrade(Pre7UpgradeProcess.java:42)
```

MySQL
```
[java] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.upgrade.UpgradeException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'fileEntryId' in 'where clause'
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:91)
```

The other two failures appear to be related to the changes that Hashi made to wait for the Tomcat startup complete line in the app server log. Hashi submitted a fix earlier today in an attempt to address this issue but it did not fix the problem. He's trying another approach now.

**Comment by brianchiu** [comment]
@brianchandotcom 
@pyoo47 
I was wrong about the failures being sporadic. I thought they were sporadic because there was a pull from earlier where I saw it pass and then fail. The failures do happen consistently because support for upgrading from 6.0.6 to master was removed.

**Comment by michaelhashimoto** [comment]
@pyoo47 @brianchandotcom 

Here's the fix that me and peter came up with:
https://github.com/brianchandotcom/liferay-portal/pull/40200

Basically we are going to avoid using the 'record' ant command, because it seems to be unstable.

Instead we are going to look at the 'catalina' logs provided by tomcat.

**Pull request closed without merging**
