### PR TITLE
LPS-71884

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:reopen

**Comment by adolfopa** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4fdb24159f...42d0332cca

**Comment by brianchandotcom** [comment]
@adolfopa please resend? Test failures seem legitimate.

**Pull request closed without merging**
