### PR TITLE
master-lps-58580

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LPS-58580

This is a resend of https://github.com/brianchandotcom/liferay-portal/pull/30273 that includes QA test fixes.

@marcellustavares @ctampoya @vicnate5

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@rafaprax please see my changes in upstream. Good job with this.

Thx for the review @marcellustavares please also see my changes. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/aa90ad226a...268ddf020a

**Pull request closed without merging**
