### PR TITLE
LPS-71002

### PR DESCRIPTION
**Pull request by matethurzo**
resent with rebase and added prefixes as discussed

for the LARTypeException I think the class name is straightforward and I haven't applied the the prefixes there.

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:reopen

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
@brianchandotcom seems like the failures are not valid.

**Comment by brianchandotcom** [comment]
@matethurzo I think LARTypeException.TYPE_* should still be done. I mean, we have a field called int type.

I'm ok with not prefixing if they were instances of LARTypeException. So LARTypeException.DUMMY could be a "new LARTypeException(xyz)."

Otherwise, we should prefix them for consistency. Thx.

**Pull request closed without merging**
