### PR TITLE
LPS-62735 Rename upgrade-related classes.

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/be384715b1...4549bf08eb

**Comment by brianchandotcom** [comment]
Thx @brandizzi !

**Comment by jpince** [comment]
@brandizzi I don't see the modules-integration test failures in other pulls, do you think they could have been caused by something here?
For example:
```
junit.framework.AssertionFailedError: 
Failed to connect to a valid mail server. Please make sure one is properly configured. Could not connect to SMTP host: localhost, port: 3241
	at com.liferay.portal.log.assertor.PortalLogAssertorTest.scanXMLLogFile(PortalLogAssertorTest.java:168)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:100)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:90)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXMLLog(PortalLogAssertorTest.java:88)
```

**Comment by brandizzi** [comment]
@jpince thanks for pointing out. Since Shuyang fixed that, I'll pay more attention to that later.

**Pull request closed without merging**
