### PR TITLE
Lps 145191 follow up 1

### PR DESCRIPTION
**Pull request by arthurchan35**
From https://github.com/brianchandotcom/liferay-portal/pull/116173
Removed deprecation

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@arthurchan35 please resend on top of https://github.com/arthurchan35/liferay-portal/pull/163

Don't remove the deprecation tag

Remove the method that should have been deprecated.

**Comment by arthurchan35** [comment]
Hey @brianchandotcom 
I am bit confused, does it mean we no longer do deprecation but removing methods straight from now on?

**Comment by brianchandotcom** [comment]
@arthurchan35 yes, for master / 7.4. It's been that for a few months now.

however, configs etc and other stuff that CUSTOMERS use need to be backwards compatible. No customer is expected to use that API.

**Pull request closed without merging**
