### PR TITLE
LPS-162006 Set Failed status on Notification Queue Entry

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-162006

### CODE REVIEW

**Comment by mateussgn** [comment]
Hey @brianchandotcom, I'm sending you directly because there was only [one unrelated failure](https://github.com/liferay-objects/liferay-portal/pull/1008#issuecomment-1237381984).

cc:@rodrigopaulino

**Comment by mateussgn** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fc5902292d...0a8cfd28da

**Comment by brianchandotcom** [comment]
@mateussgn see 0a8cfd28da85d9f89eb8df3e8d5611c284ea1386 thx

**Pull request closed without merging**
