### PR TITLE
LPS-91995 Fix after rebase

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by jpince** [comment]
@matethurzo @danielkocsis please see failure in `CTProcessLocalServiceTest.testAddCTProcess`, looks related
```
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at com.liferay.change.tracking.configuration.CTConfigurationRegistryUtil._getCTConfiguration(CTConfigurationRegistryUtil.java:118)
	at com.liferay.change.tracking.configuration.CTConfigurationRegistryUtil.getVersionEntityGroupId(CTConfigurationRegistryUtil.java:36)
	at com.liferay.change.tracking.internal.search.spi.model.index.contributor.CTEntryModelDocumentContributor._getGroupId(CTEntryModelDocumentContributor.java:77)
	at com.liferay.change.tracking.internal.search.spi.model.index.contributor.CTEntryModelDocumentContributor.contribute(CTEntryModelDocumentContributor.java:47)
	at com.liferay.change.tracking.internal.search.spi.model.index.contributor.CTEntryModelDocumentContributor.contribute(CTEntryModelDocumentContributor.java:36)
	at com.liferay.portal.search.internal.indexer.IndexerDocumentBuilderImpl.lambda$getDocument$1(IndexerDocumentBuilderImpl.java:57)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.liferay.portal.search.internal.indexer.IndexerDocumentBuilderImpl.getDocument(IndexerDocumentBuilderImpl.java:55)
	at com.liferay.portal.search.internal.indexer.IndexerWriterImpl.reindex(IndexerWriterImpl.java:241)
	at com.liferay.portal.search.internal.indexer.DefaultIndexer.reindex(DefaultIndexer.java:294)
	at com.liferay.portal.search.internal.indexer.DefaultIndexer.reindex(DefaultIndexer.java:52)
	at com.liferay.portal.search.IndexableAdvice.afterReturning(IndexableAdvice.java:104)
	at com.liferay.portal.spring.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:72)
	at com.liferay.portal.spring.aop.AopMethodInvocation.proceed(AopMethodInvocation.java:51)
	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:44)
	at com.sun.proxy.$Proxy883.addCTEntry(Unknown Source)
	at com.liferay.change.tracking.service.test.CTProcessLocalServiceTest.testAddCTProcess(CTProcessLocalServiceTest.java:95)
```

The test fails at `_ctEntryLocalService.addCTEntry(`, and this pull makes a change to `CTEntryLocalService.java` https://github.com/brianchandotcom/liferay-portal/pull/69837/files#diff-c5af3cf7e39e5ef87758fc75643d0828R85.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f42babb891...d7d9c35178

**Comment by brianchandotcom** [comment]
@matethurzo @danielkocsis is this right?

```
searchContext.setSorts();
```

Just minor updates in upstream from me.

**Comment by brianchandotcom** [comment]
@matethurzo you also removed a bunch of newly added methods like

getCollidingCTEntries

was that on purpose?

**Pull request closed without merging**
