### PR TITLE
LPS-55026 SF

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
@brianchandotcom, are these real failures?

**Comment by brianchandotcom** [comment]
They are real, but can be ignored since they are not related. We're working on fixing these.

**Comment by marcellustavares** [comment]
got it, thanks Brian

**Comment by brianchandotcom** [comment]
@marcellustavares please resend on top of https://github.com/marcellustavares/liferay-portal/pull/560

1.) We have 2 copies of every template file. See b*.tmpl

2.) We may have to fix this for other modules as well.

3.) Can you send one more commit to say that you applied all changes from liferay-plugins#f6c81638c8efe667adcb4d01914a11b37481a8a4 to liferay-plugins#xxxx

So that as we go back and forth, we're getting closer to whatever is in plugins master (all the bug fixes etc, don't want to lose them).

Thx

**Pull request closed without merging**
