### PR TITLE
LPS-63828 sf

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by sharonchoi** [comment]
@alee8888 poshi test failure for mongodb hook

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6f715e20d8...1175dc1b66

**Comment by brianchandotcom** [comment]
@gamerson can you see my changes in upstream (I made quite a few), especially 5f2cc01ef8b0ddee205f1228355459a06b04f075

Please send a follow up pull if needed. Thx.

**Pull request closed without merging**
