### PR TITLE
Lps 74738

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
Try the trick again

auto-close=\"false\"

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
@hhuijser please see https://github.com/brianchandotcom/liferay-portal/pull/51571/commits/f1d610ddfcf579e49508fea2c5846b6e5bd565d4, we will need a better way to do this checking. I am only doing this for now to get the SF checking passed. I need this pull to be merged to unblock my other tasks. Thanks!

**Comment by brianchandotcom** [comment]
@shuyangzhou can you resend without using a switch? Thx!

**Comment by shuyangzhou** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/51595

**Pull request closed without merging**
