### PR TITLE
LPS-74197 gradlew npmShrinkwrap - web experience

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7267045712...abcc8add2a

**Comment by brianchandotcom** [comment]
Please backport @ealonso thx

**Comment by ealonso** [comment]
Hey @brianchandotcom,

@Robert-Frampton is taking care about it https://issues.liferay.com/browse/LPS-74197?focusedCommentId=1095758&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1095758.

Regards,
Eudaldo.

**Pull request closed without merging**
