### PR TITLE
LPS-168742 Create Custom sidebar content for FreeMarker Template Editor

### PR DESCRIPTION
**Pull request by danvb112**
Related Issues:

https://issues.liferay.com/browse/LPS-168742
https://issues.liferay.com/browse/LPS-168331

### CODE REVIEW

**Comment by danvb112** [comment]
ci:reopen

**Comment by danvb112** [comment]
Hey @brianchandotcom , I'm submitting this PR directly after the original failed a lot in unrelated tests

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3f09f52938...017e5e6b1b

**Comment by brianchandotcom** [comment]
@naraandrade @danvb112 just 8d1fff01b2368c5ee3ee153f2b9f985ca8444bb9

**Pull request closed without merging**
