### PR TITLE
LPS-85458 Support for AND and OR

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
@jpince this pull will be closed and even blocked so that we can't reopen it later, can you please help us? (It happened here already: https://github.com/brianchandotcom/liferay-portal/pull/63279)
thank you!!

**Comment by jpince** [comment]
ci:reopen @juliocamarero sorry about this. I can't even figure out what change requires this semver bump... hopefully Brian will be able to fix it today.

**Comment by juliocamarero** [comment]
Thank you @jpince !!

**Comment by brianchandotcom** [comment]
@cgoncas @juliocamarero see b2d27ff8835c909dbdc89f02841d4c7538ddd329 and 55a9fe9d44027ed97e0dd32a7d619036e1a920eb (the latter I had fixed in earlier pulls already, fyi)

**Pull request closed without merging**
