### PR TITLE
LPS-69255 Use Petra adapter proxies instead of custom class

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by jpince** [comment]
@adolfopa Can you please take a look at this? It looks like it might be related to your change.
`[exec] org.gradle.api.GradleException: Could not copy MANIFEST.MF to '/opt/dev/projects/github/liferay-portal/modules/apps/collaboration/subscription/subscription-api/build/tmp/jar/MANIFEST.MF'.`

**Comment by jpince** [comment]
ci:close

**Comment by adolfopa** [comment]
Thanks for the heads up @jpince 

See https://github.com/brianchandotcom/liferay-portal/pull/46845

**Pull request closed without merging**
