### PR TITLE
LPS-69559 Shrink ES threadpools to their smallest size to reduce CI m…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…emory footprint

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:retest

Appended 2 more commits to further shrink ES threads numbers.

**Comment by shuyangzhou** [comment]
ci:retest
@pyoo47 what's this?

**Comment by pyoo47** [comment]
@shuyangzhou Looks like there was some kind of network outage. The top level build could not communicate with one of the downstream jenkins masters.

```
Caused by: java.net.UnknownHostException: test-1-10
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at java.net.Socket.connect(Socket.java:528)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:997)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:933)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:851)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1301)
	at com.liferay.jenkins.results.parser.JenkinsResultsParserUtil.toString(JenkinsResultsParserUtil.java:725)
	at com.liferay.jenkins.results.parser.JenkinsResultsParserUtil.toJSONObject(JenkinsResultsParserUtil.java:635)
	at com.liferay.jenkins.results.parser.BaseBuild.getBuildJSONObject(BaseBuild.java:604)
	at com.liferay.jenkins.results.parser.BaseBuild.getResult(BaseBuild.java:217)
	... 66 more
```

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
