### PR TITLE
LPS-104795 - Provide an entry variable with autocomplete when creating a custom template

### PR DESCRIPTION
**Pull request by thektan**
http://issues.liferay.com/browse/LPS-104795

Ran tests at https://github.com/thektan/liferay-portal/pull/89#issuecomment-557324270
✔️ ci:test:sf - 1 out of 1 jobs passed in 2 minutes 34 seconds 533 ms
❌ ci:test:search - 47 out of 50 jobs passed in 1 hour 21 minutes 37 seconds 632 ms

No related failures.

cc: @oliv-yu

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bde00e1d6a...c87f25f5dd

**Comment by brianchandotcom** [comment]
@BryanEngler @thektan can you guys fix the language keys in *-help in this module? They are not complete sentences. I reviewed them and quite a few are off. Thx.

**Comment by thektan** [comment]
@brianchandotcom Will do. I'll send a follow-up.

**Comment by thektan** [comment]
@rbohl I remembered you were recently looking at these Similar Results language keys. Did you already have in mind fixes to make these complete sentences? 

This PR also added 3 new language keys. 
```
document-entry=Document Entry
document-entry-help=Represents the document entry that is displayed through this template.
similar-results-display-context-help=Provides helper methods to retrieve the Similar Results widget configuration.
```

https://github.com/thektan/liferay-portal/blob/771961fe7eaf024cfb03bef9672abc8ff092e9f1/modules/dxp/apps/portal-search-similar-results/portal-search-similar-results-web/src/main/resources/content/Language.properties

**Comment by rbohl** [comment]
@thektan Yeah I was surprised they were ever merged in the first place since they're not full sentences ;)

In addition, I noticed that many of the keys are copy-pasted straight from Elastic's docs.

What's the best workflow? Do I create a LPS specifically for the lang keys and work directly in the repo? Do I use an existing ticket, like LPS-104795? Create a LRDOCS ticket? If I make a more substantial edit, who do I send the PR for dev review? If I do a more substantial edit for clarity, I want to make sure accuracy is preserved.

**Comment by thektan** [comment]
@rbohl A bug ticket should be appropriate for this. I went ahead and created one: https://issues.liferay.com/browse/LPS-104990

You can send me a PR for dev review and I'll double-check they make sense where they are used.

Thanks Russ!

**Pull request closed without merging**
