### PR TITLE
LPS-65529 Update gradle cache

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
I had to stop and retest this pull because a recent CI pull that got merged into upstream broke the PR tester. The source of this problem has been reverted.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@Ithildir

See

```

	filter {
		String line ->

		line.replace("typeof define == 'function'", "false && typeof define == 'function'")
	}
```

in build.gradle. Can you make sure this is acceptible? Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/46dcac0368...25ebe99e89

**Comment by Ithildir** [comment]
I pushed a very small SF at https://github.com/liferay/liferay-portal/commit/ec8e990fb0651ea629f1c1a6ea48ae7e7539034b.

**Comment by brianchandotcom** [comment]
@jbalsas see ec8e990fb0651ea629f1c1a6ea48ae7e7539034b

**Comment by jbalsas** [comment]
Thanks @brianchandotcom, @Ithildir!!

I actually copied from https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/frontend-js/frontend-js-web/build.gradle#L153... I guess we should SF that one as well. Looks like I picked the only different one 😅

**Comment by Ithildir** [comment]
Thank you @jbalsas, you're absolutely right! I pushed another SF: https://github.com/liferay/liferay-portal/commit/b40022029b9f878bc44d9f53791245c5b48432c0.

**Pull request closed without merging**
