### PR TITLE
LPS-75977

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-75977.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:reopen

**Comment by jbalsas** [comment]
ci:retest

**Comment by csababotos** [comment]
Hi Jonathan,

Could you please give us an update on this PR?

Regards, 
Csaba

**Comment by jonmak08** [comment]
Hey @csababotos,

This is already in @brianchandotcom's queue to review as this pull has already been sent to him.  Once it is reviewed, QA can test it and close out the LPS ticket and the backport process can begin.

Please let me know if you have any questions. Thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/12a03b402f...133c206cea

**Pull request closed without merging**
