### PR TITLE
LPS-74734 Fix typo in Roles Portlet language key

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-74734](https://issues.liferay.com/browse/LPS-74734).<br><br>/cc @pei-jung, @joshuacords, @CsabaTurcsan

### CODE REVIEW

**Comment by drewbrokke** [comment]
Hey @brianchandotcom, can we backport this one right away?

**Comment by brianchandotcom** [comment]
@drewbrokke yes...

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ec6453eef0...333a1afc25

**Comment by drewbrokke** [comment]
@brianchandotcom here's the context for the question: https://github.com/liferay/liferay-portal-ee/pull/2273#issuecomment-329797576

**Comment by brianchandotcom** [comment]
@drewbrokke you missed these.

dd1a89a545cc1dd51945c2fe41a5f9a4f783c83d

I backported it for you.

**Comment by drewbrokke** [comment]
Thanks!  Sorry about that - I assumed you would run a translation (since they were Automatic Copies).

**Pull request closed without merging**
