### PR TITLE
LPS-61520

### PR DESCRIPTION
**Pull request by danielkocsis**

### CODE REVIEW

**Comment by danielkocsis** [comment]
ci:retest

**Comment by danielkocsis** [comment]
The failures seems random, and none of those related to the change

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8bb9398722...e5c66e379e

**Comment by brianchandotcom** [comment]
@danielkocsis see e5c66e379eb8b16d4f76bca355638ce57fa34e42 thx

**Pull request closed without merging**
