### PR TITLE
LPS-59825 extract maps taglib

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @jbalsas

**Comment by juliocamarero** [comment]
:v:

**Comment by jbalsas** [comment]
:dancer:

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bbd676dc88...73e99ebc83

**Comment by brianchandotcom** [comment]
@juliocamarero @jbalsas please see my changes at 73e99ebc83f9d4bb2fbae6386619a3cf86ac5f3b

Thx.

**Pull request closed without merging**
