### PR TITLE
LPS-86914 Fix race conditions with ConfigurationAdmin and store tests.

### PR DESCRIPTION
**Pull request by Preston-Crary**
CC @shuyangzhou

@brianchandotcom This fixed the random NPE that happened on https://github.com/brianchandotcom/liferay-portal/pull/64859

### CODE REVIEW

**Comment by jpince** [comment]
@Preston-Crary more integration test failures...

cc/ @drewbrokke @vicnate5

**Comment by Preston-Crary** [comment]
@jpince sorry, I found a problem and made the mistake of thinking it was the problem I was looking for.  I should have a fix ready sometime today.

**Comment by jpince** [comment]
@Preston-Crary no worries, thank you!

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/64882

**Pull request closed without merging**
