### PR TITLE
Upgrade Process: Apply pattern to Lock Service and Kaleo Workflow Service (follow up pull)

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by migue** [comment]
Everything is okay, just retesting to get it green

ci:retest

**Comment by brianchandotcom** [comment]
@shuyangzhou can you see why we had this random scan log error? We didn't have many today, just this one.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7819760b5a...b1a0f18bae

**Comment by shuyangzhou** [comment]
@mtambara this is a tika parser error. Please check and fix it. I am out of office in the morning, will be back in the afternoon.

**Pull request closed without merging**
