### PR TITLE
LPS-72106

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/018b303331...534faaa639

**Comment by brianchandotcom** [comment]
@Preston-Crary please backport.

**Comment by Preston-Crary** [comment]
Backport:
https://github.com/brianchandotcom/liferay-portal-ee/pull/17506

**Pull request closed without merging**
