### PR TITLE
LPS-64538 Fix test

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/04c911bc3e...b0319daace

**Comment by brianchandotcom** [comment]
@brunobasto @marcellustavares please see my changes in upstream. thx

**Pull request closed without merging**
