### PR TITLE
LPS-63695 SEMVER

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by sharonchoi** [comment]
@brianchiu upgrade tests are failing due to warning, but it passes completely in the logger
@evannagayama poshi errors on web content and page templates

**Comment by brianwulbern** [comment]
@sharonchoi It looks like there was a module loading issue with AP-related modules for both of the WCM tests:

```
  [exec] 14:16:37,479 WARN  [fileinstall-/opt/dev/projects/github/liferay-portal/bundles/osgi/modules][org_apache_felix_fileinstall:102] Error while starting bundle: file:/opt/dev/projects/github/liferay-portal/bundles/osgi/modules/com.liferay.asset.publisher.web.jar 
     [exec] org.osgi.framework.BundleException: Could not resolve module: com.liferay.asset.publisher.web [200]
     [exec]   Unresolved requirement: Import-Package: com.liferay.portal.kernel.security.permission; version="[1.1.0,2.0.0)"
     [exec] 
     [exec] 	at org.eclipse.osgi.container.Module.start(Module.java:429)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1252)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1224)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:512)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:361)
     [exec] 	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:313)
```

See the full console [here](https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=0,label_exp=!master/25794//consoleFull)

**Comment by brianchiu** [comment]
For the upgrade tests, they failed because of this startup error (which looks to be the same issue that occurred for the WCM tests that failed).

```
     [exec] 14:16:51,973 ERROR [Framework Event Dispatcher: Equinox Container: 70415c8d-6fef-0015-15a8-fc9a505552b6][com_liferay_screens_service:96] FrameworkEvent ERROR 
     [exec] org.osgi.framework.BundleException: Could not resolve module: com.liferay.screens.service [316]
     [exec]   Unresolved requirement: Import-Package: com.liferay.asset.publisher.web.util; version="[1.0.0,2.0.0)"
     [exec]     -> Export-Package: com.liferay.asset.publisher.web.util; bundle-version="1.0.0"; bundle-symbolic-name="com.liferay.asset.publisher.web"; version="1.0.0"; uses:="com.liferay.asset.kernel.model,com.liferay.asset.kernel.service,com.liferay.asset.kernel.service.persistence,com.liferay.asset.kernel.util,com.liferay.asset.publisher.web.display.context,com.liferay.dynamic.data.mapping.util,com.liferay.portal.kernel.dao.search,com.liferay.portal.kernel.exception,com.liferay.portal.kernel.model,com.liferay.portal.kernel.portlet,com.liferay.portal.kernel.search,com.liferay.portal.kernel.security.permission,com.liferay.portal.kernel.service,com.liferay.portal.kernel.theme,javax.portlet"
     [exec]        com.liferay.asset.publisher.web [200]
     [exec]          Unresolved requirement: Import-Package: com.liferay.portal.kernel.security.permission; version="[1.1.0,2.0.0)"
     [exec] 
     [exec] 	at org.eclipse.osgi.container.Module.start(Module.java:429)
     [exec] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
     [exec] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
     [exec] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
     [exec] 	at org.eclipse.osgi.container.SystemModule.startWorker(SystemModule.java:242)
     [exec] 	at org.eclipse.osgi.container.Module.doStart(Module.java:566)
     [exec] 	at org.eclipse.osgi.container.Module.start(Module.java:434)
     [exec] 	at org.eclipse.osgi.container.SystemModule.start(SystemModule.java:172)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:421)
     [exec] 	at org.eclipse.osgi.launch.Equinox.start(Equinox.java:115)
     [exec] 	at com.liferay.portal.bootstrap.ModuleFrameworkImpl.startFramework(ModuleFrameworkImpl.java:391)
     [exec] 	at com.liferay.portal.module.framework.ModuleFrameworkUtilAdapter.startFramework(ModuleFrameworkUtilAdapter.java:93)
     [exec] 	at com.liferay.portal.spring.context.PortalContextLoaderListener.contextInitialized(PortalContextLoaderListener.java:259)
     [exec] 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812)
     [exec] 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255)
     [exec] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
     [exec] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
     [exec] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
     [exec] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
     [exec] 	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:585)
     [exec] 	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1794)
     [exec] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
     [exec] 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
     [exec] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [exec] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [exec] 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by rotty3000** [comment]
All, I've rebased and updated. I'll wait for one of you to trigger a retest.

**Comment by brianchiu** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@rotty3000 @topolik can you guys resend? CI gave weird results. Thanks.

**Comment by topolik** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/38485. Thanks.

**Pull request closed without merging**
