### PR TITLE
LPS-56383 Move delete temp images logic to module

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@epgarcia 

JournalServiceUpgrade should no longer depend on ReleaseLocalService since JournalServiceConfigurator depends on ReleaseLocalService

Can you make that minor change?

I went ahead and merged in your fix.  Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9025f1769f...ab33df856a

**Comment by epgarcia** [comment]
Hey Brian,

JournalServiceUpgrade still requires ReleaseLocalService to update the release number, but you're right in that we had a redundant dependency: Since JournalServiceUpgrade depends on JournalServiceConfigurator and this already depends on the portal complete startup (through setServletContext original.bean=*), the JournalServiceUpgrade doesn't need this last dependency. See brianchandotcom/liferay-portal/pull/27818.

Regards

**Pull request closed without merging**
