### PR TITLE
LPS-67820 Fix unit tests

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:reopen

**Comment by pyoo47** [comment]
This pull request appears to be exposing a bug in the pull request tester code. We are currently investigating the issue. **Please do not merge to upstream** until the issue is resolved.

**Comment by marcellustavares** [comment]
Thanks for letting me know @pyoo47

**Comment by pyoo47** [comment]
ci:close
I'm closing this pull to make sure it doesn't get merged until we've resolved the issue.

**Comment by pyoo47** [comment]
@marcellustavares We found the issue. There are a couple of new java files in this pull that have an incorrect file path.

liferay-portal/modules/apps/forms-and-workflow/dynamic-data-lists/dynamic-data-lists-form-web/src/test/java/**_com.liferay.dynamic.data.lists.form.web.internal.converter_**/DDLFormRulesToDDMFormRulesConverterTest.java

should be

liferay-portal/modules/apps/forms-and-workflow/dynamic-data-lists/dynamic-data-lists-form-web/src/test/java/**_com/liferay/dynamic/data/lists/form/web/internal/converter_**/DDLFormRulesToDDMFormRulesConverterTest.java

and

liferay-portal/modules/apps/forms-and-workflow/dynamic-data-lists/dynamic-data-lists-form-web/src/test/java/**_com.liferay.dynamic.data.lists.form.web.internal.converter_**/DDMFormRulesToDDLFormRulesConverterTest.java

should be

liferay-portal/modules/apps/forms-and-workflow/dynamic-data-lists/dynamic-data-lists-form-web/src/test/java/**_com/liferay/dynamic/data/lists/form/web/internal/converter_**/DDMFormRulesToDDLFormRulesConverterTest.java

You should correct these file paths and then resend.

**Comment by marcellustavares** [comment]
Thanks @pyoo47, how did you find out this was the issue? Regards

**Comment by marcellustavares** [comment]
Resent to https://github.com/brianchandotcom/liferay-portal/pull/43448

**Comment by kevin-yen** [comment]
@marcellustavares
From the error message we can figured out where the error occured.
`List getClassGrou . . . '' : fileName .substring ( fileName .indexOf ( "com" + File .separator ) , fileName .length ( ) - 4 )`
Which is in [build-test.xml (2375)](https://github.com/liferay/liferay-portal/blob/8f31593f1fd13acbce15565af047f5de31fc7d52/build-test.xml#L2375)
Two possibilities that will make that line throw an exception is either. 
1.  `fileName.indexOf("com" + File.separator)` returns an invalid index or
2.  `fileName() - 4` returns an invalid index
#1 seems more likely so I added a debug line that prints out fileName before that line is executed. I noticed that the last file before failing has an invalid filename.

**Comment by marcellustavares** [comment]
Thanks a lot for the detailed info @kevin-yen!

**Pull request closed without merging**
