### PR TITLE
Lps 117611

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/32ea220cef...a897b65fbb

**Comment by brianchandotcom** [comment]
@Preston-Crary the packages for portal-kernel/src/com/liferay/portal/kernel/internal/spring/transaction/ReadOnlyTransactionThreadLocal.java and portal-impl/test/unit/com/liferay/portal/spring/transaction/ReadOnlyTransactionThreadLocalTest.java don't seem to correlate fully.

Was that on purpose? Can you send me a pull to fix it? Thx.

**Comment by Preston-Crary** [comment]
Hi @brianchandotcom,

it's on purpose.  The ThreadLocal has to be in portal-kernel since it's used in BasePersistenceImpl, but I put the unit test in portal-impl so I could use DefaultTransactionExecutor and the other test classes in that package.  Otherwise, the test doesn't really prove much.

**Pull request closed without merging**
