### PR TITLE
Lps 69544

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
CC @alee8888

**Comment by shuyangzhou** [comment]
@dantewang @slnn I did the same thing for benchmark, please check the performance diff. Should be very small, but run it anyway. Thanks!

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by alee8888** [comment]
@brianchandotcom @shuyangzhou 
Can this please be backported to ee-7.0.x as well?

**Comment by brianchandotcom** [comment]
Yup. Backporting @alee8888

**Pull request closed without merging**
