### PR TITLE
COMMERCE-11766 Feature flag release order splitting and supplier account

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/COMMERCE-11768
https://liferay.atlassian.net/browse/COMMERCE-11766

Resent from here: https://github.com/brianchandotcom/liferay-portal/pull/137199

### CODE REVIEW

**Comment by smottal** [comment]
ci:reopen

**Comment by smottal** [comment]
Hi @brianchandotcom: I updated the descriptions of the two feature flags

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4e6d46bdde...6ca28548eb

**Comment by brianchandotcom** [comment]
@smottal see 09c2805ac8047808df819344ae9116e004698669

**Pull request closed without merging**
