### PR TITLE
LPS-191058 Translate and apply the request filter with the already existing API Endpoint filter in API Builder

### PR DESCRIPTION
**Pull request by ccorreagg**
See: https://github.com/brianchandotcom/liferay-portal/pull/138494, rebased with brianchandotcom/master

Related story: https://liferay.atlassian.net/browse/LPS-191058

---

The purpose of this PR is, given the query parameter `filter` in the API Builder JAX-RS resource, to translate that filter that the user understands (based on the API Properties of an API Schema defined) into a different one that Object's layer understand (based on the Object Definitions and Object Fields), having into account the equivalences that the API Application creator defined when the API Application was created.

So, once the filter query parameter is received, it is transformed into an `Expression`. The internal filter (API Endpoint filter), if exists, it is also transformed into an `Expression` and if both are available, then an Binary Operation with an `AND` operator is created and passed into the following service layers (DefaultObjectEntryManager).

The following interfaces have been added/modified:

- `EntityModelProvider`: An interface that is registered as an OSGi component and provides the Object Definition Entity Model associated to an Object Definition.
- `ObjectDefinitionFilterParser`: An interface that is registered as an OSGi component and parses the filter String based on the object definition (and the entity model) and returns the OData Expression created.
- `FilterPredicateFactory`: A new method has been added to get a Predicate based on a Expression (apart from the existing ones that they are based on a String filter).
- `ExpressionFactory`: A factory that exposes several methods to create different Expression types. With that interface and component registered in OSGi, it is not necessary to know the Expression's constructors.

The several classes have been implemented:
- `APISchemaEntityModel`: An `EntityModel` that returns the `EntityField`s with the property names of the API Schema properties, translating the internal `EntityModel` into a new one to be used to parse the filter that the user sent.
- `APIPropertyEntityField`: A class that extends `EntityField` to keep also the internal field name.
- `APISchemaTranslatorExpressionVisitor`: It is an OData Expression Visitor that, based on the EntityModel, translates all the properties from the external API Properties to the internal properties. That will transform the Expression created from the user filter query parameter into an Expression that Object's service layer understand.

How to test:
- Rebase with the latest master branch
- Deploy the `modules/apps/portal-odata/portal-odata-api` module
- Deploy the `modules/apps/portal-odata/portal-odata-impl` module
- Deploy the `modules/apps/object/object-rest-api` module
- Deploy the `modules/apps/object/object-service` module
- Deploy the `modules/apps/object/object-rest-impl` module
- Deploy the `modules/apps/headless/headless-builder/headless-builder-impl` module
- Execute the unit tests `APISchemaEntityModelTest` of the module `modules/apps/headless/headless-builder/headless-builder-impl` with the command `gw test --tests APISchemaEntityModelTest`
- Execute the integration tests `HeadlessBuilderResourceTest` of the module `modules/apps/headless/headless-builder/headless-builder-test` with the command `gw tI --tests HeadlessBuilderResourceTest`
- Execute the unit tests `ExpressionConvertImplTest` of the module `modules/apps/portal-odata/portal-odata-impl` with the command `gw test --tests ExpressionConvertImplTest`
- Execute the unit tests `ExpressionVisitorImplTest` of the module `modules/apps/portal-odata/portal-odata-impl` with the command `gw test --tests ExpressionVisitorImplTest`
- Execute the unit tests `FilterParserImplTest` of the module `modules/apps/portal-odata/portal-odata-impl` with the command `gw test --tests FilterParserImplTest`

---

NOTE: I will create a following-up PR with more integration tests

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ae1d07717c...19a2912118

**Comment by brianchandotcom** [comment]
@ccorreagg

1.) can you move

EntityModelProvider from com.liferay.object.rest.odata.entity.v1_0 into 

com.liferay.object.rest.odata.entity.v1_0.provider

Same for EntityModelProviderImpl and add provider to the package

2.) PredicateExpressionVisitorImpl.java should not import

import com.liferay.object.service.ObjectDefinitionLocalServiceUtil;

or

import com.liferay.object.service.ObjectRelationshipLocalServiceUtil;

Pass in the LocalService instead like how

import com.liferay.object.service.ObjectFieldLocalService

is being used already.

**Comment by ccorreagg** [comment]
Followed-up PR: https://github.com/brianchandotcom/liferay-portal/pull/138768

**Comment by ccorreagg** [comment]
The ServiceUtil issue will be managed in the task https://liferay.atlassian.net/browse/LPS-192594

**Pull request closed without merging**
