### PR TITLE
LPS-88484

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:test:search

@adolfopa A subset of these commits failed DL search tests in https://github.com/adolfopa/liferay-portal/pull/774#issuecomment-449229870. Running the Search suite as I'm not sure if the additional commits in this PR addressed the issue.

@brianchandotcom Please hold off on merging until this finishes running.

**Comment by jonathanmccann** [comment]
@adolfopa I'm thinking that these test failures are occurring because the reindexing now happens in a separate thread and the test's assertions are being run before the reindex is complete. Do you know if we have a defined way to wait for that to complete before continuing?

**Comment by xbrianlee** [comment]
ci:close

Closing this PR for now as these failures are resolved.

**Pull request closed without merging**
