### PR TITLE
LPS-64730 - Update Lexicon to 0.2.12

### PR DESCRIPTION
**Pull request by pat270**
Hey @brianchandotcom, not sure if this is the right way to do it, but I committed the new cache files and removed 2.0.0.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/25a0769096...c1be0243cc

**Comment by brianchandotcom** [comment]
@pat270 this is OK.. but next time you do that, make sure to call it a "FAKE" gradle cache.. I thought it was a real one and then ran into issues later when I realized it was a manually made jar.

**Comment by natecavanaugh** [comment]
@brianchandotcom Patrick and I aren't sure what any of that means.
What's a "fake" jar vs. a "real" one?

**Pull request closed without merging**
