### PR TITLE
LPS-56065 Portal Settings portlet to OSGI

### PR DESCRIPTION
**Pull request by philipjones03**
@peterfellwock fyi
@rotty3000 fyi

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/646cd0cf87...253a1edd2c

**Comment by brianchandotcom** [comment]
@philipjones03 

1.) Please check on main.css

2.) Move keys that are not used in core, and move them into the module

**Comment by philipjones03** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
