### PR TITLE
LRDOCS-2981

### PR DESCRIPTION
**Pull request by Ithildir**
cc @jhinkey

### CODE REVIEW

**Comment by jhinkey** [comment]
Thanks @Ithildir ! :-)

**Comment by Ithildir** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/22d073e286...2d052dcb85

**Comment by brianchandotcom** [comment]
@codyhoag see change logs? THx.

**Pull request closed without merging**
