### PR TITLE
Lps 104116

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bd8135bda3...b1b456f560

**Comment by brianchandotcom** [comment]
@jorgediaz-lr can you resend? For example, a jar may be abc-5rc1.jar, but the description should be 5 RC1.

So the algorithm right now is not right. This is true for alpha/beta etc. Please resend. Thx.

**Comment by jorgediaz-lr** [comment]
'Just

**Comment by jorgediaz-lr** [comment]
I have sent a new PR with a normalizeVersion logic, see: https://github.com/shuyangzhou/liferay-portal/pull/8481

**Pull request closed without merging**
