### PR TITLE
ISSD-1348 [Learn] Set article permissions

### PR DESCRIPTION
**Pull request by joseabelenda**
.

### CODE REVIEW

**Comment by joseabelenda** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
ci:reopen

**Comment by joseabelenda** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/60457bc567...6142a2fff6

**Pull request closed without merging**
