### PR TITLE
LRQA-24545 Add accceptance test to delete page and assert page tree

### PR DESCRIPTION
**Pull request by juliocamarero**
@evannagayama , now that we have fixed the issue, this test should pass 👍

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
I had to stop and retest this pull because a recent CI pull that got merged into upstream broke the PR tester. The source of this problem has been reverted.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2316dd9fbe...46dcac0368

**Pull request closed without merging**
