### PR TITLE
LPS-79709 Fix Windows build again

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5bfbcd9ebb...c83b48d0ba

**Comment by brianchandotcom** [comment]
@ithildir for you..

**Comment by brianchandotcom** [comment]
@petershin can you auto sort modules/apps/frontend-js/frontend-js-metal-web/.npmbridgerc

Thx

**Comment by petershin** [comment]
Sent a patch: https://github.com/brianchandotcom/liferay-portal/pull/59308

**Comment by izaera** [comment]
Thx guys. Let's see if this fixes it 🙏

**Pull request closed without merging**
