### PR TITLE
LPS-67165 Remove unnecessary dependencies

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
I'd say those failures aren't really related to this PR, but it's becoming more difficult to tell... @brianchandotcom, @kenjiheigel?

**Comment by jbalsas** [comment]
On a related note, 

> *If you believe this is a mistake please re-open this pull. This pull will no longer automatically close if this comment is available.

This is very misleading since I actually can't reopen the PR, and the linked article is simply a list of the tests that will auto-close the PR without any indication as to what they contain or how to diagnose and fix that...

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
@jbalsas, will let you know what I find. If it passes the retest right now, I can resend it for you to BChan.

**Comment by kenjiheigel** [comment]
Resent:
https://github.com/brianchandotcom/liferay-portal/pull/43101

**Pull request closed without merging**
