### PR TITLE
LPS-109525 Semver

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @brianchandotcom 

I've changed the field reference to a method reference (so that it is more explicit that we're not using that ref on purpose), and a comment that mentions the jira ticket. In the ticket, I wrote the following as a public comment:

> To keep backwards compatibility, I've kept some usages of ClassNameLocalServiceUtil. To make sure everything is initialized propertly, I've added dummy references to the service in the calling upgrades. Ideally, we would inject the service and use a reference, but that causes a breaking change.

Let me know if you think something else is needed.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3f8b349bbd...036a05f261

**Comment by brianchandotcom** [comment]
@adolfopa @SamZiemer please resend

add a new constructor to UpgradeDiscussionSubscriptionClassName

Deprecate the old constructor

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/86085

**Pull request closed without merging**
