### PR TITLE
LPS-77591 Get asset entries using the asset entry query, instead of calling a deprecated method

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by ealonso** [comment]
cc: @nhpatt @dgarciasarai

**Comment by nhpatt** [comment]
LGTM, @dgarciasarai is going to test it, that has used the method some days ago from xamarin

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
