### PR TITLE
LPS-67449 Will this work?

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
@brianchandotcom Thanks, it works!

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/91174ea8b9...31883c7cf8

**Comment by brianchandotcom** [comment]
@pavel-savinov I backported this since it's essentially an extension point.

**Pull request closed without merging**
