### PR TITLE
LPS-69178 Correct translations.

### PR DESCRIPTION
**Pull request by brandizzi**
Hello Brian. @marcellustavares is already informed about this. Thanks!

### CODE REVIEW

**Comment by marcellustavares** [comment]
@victnate5, this seems related to SF of one of our poshi tests.

**Comment by marcellustavares** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by vicnate5** [comment]
@marcellustavares yes, this was from a poshi change. it is fixed at head here: https://github.com/liferay/liferay-portal/commit/cfe77d6a370c791ee38ddf803ebb5d1123454100

**Pull request closed without merging**
