### PR TITLE
#Ping [See description] LPS-56237 

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey Brian,

The pull have different LPS number because they are all related but it's fine.

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @natecavanaugh

**Comment by brianchandotcom** [comment]
#pong reviewing...

**Comment by sergiogonzalez** [comment]
thanks @brianchandotcom

**Comment by brianchandotcom** [comment]
@sergiogonzalez can you resend on top of https://github.com/sergiogonzalez/liferay-portal/pull/2259

see my comments (I may have broken some tests too) Thx.

**Pull request closed without merging**
