### PR TITLE
LPS-83185 Documents breaking change

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @brianchandotcom!

This change introduces a breaking change as we no longer will escape the portlet description automatically. This was incorrect and causing problems.

I've discussed this with @topolik, who thinks the affected surface is small and with @antonio-ortega who agrees that based on how early in `7.1.x` we are it's preferable to break it before we get any clients in. See backport to `7.1.x` -> https://github.com/brianchandotcom/liferay-portal-ee/pull/21058

For `7.0.x`, we will send a custom backport if necessary, avoiding the breaking change.

Thanks!

### CODE REVIEW

**Comment by jpince** [comment]
ci:test

**Comment by jpince** [comment]
@jbalsas is this a real failure, or a fluke?
```
     [exec] FAIL test/liferay/portlet/events.es.js
     [exec]   ??? Console
     [exec] 
     [exec]     console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
     [exec]       Error: Uncaught [Error: expect(jest.fn()).toHaveBeenCalled()
     [exec]       
     [exec]       Expected mock function to have been called, but it was not called.]
     [exec]           at reportException (/opt/dev/projects/github/liferay-portal/modules/apps/frontend-js/frontend-js-web/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
     [exec]           at Timeout.callback [as _onTimeout] (/opt/dev/projects/github/liferay-portal/modules/apps/frontend-js/frontend-js-web/node_modules/jsdom/lib/jsdom/browser/Window.js:630:7)
     [exec]           at ontimeout (timers.js:482:11)
     [exec]           at tryOnTimeout (timers.js:317:5)
     [exec]           at Timer.listOnTimeout (timers.js:277:5) { Error: expect(jest.fn()).toHaveBeenCalled()
     [exec]       
     [exec]       Expected mock function to have been called, but it was not called.
     [exec]           at /opt/dev/projects/github/liferay-portal/modules/apps/frontend-js/frontend-js-web/test/liferay/portlet/events.es.js:605:31
     [exec]           at Timeout.callback [as _onTimeout] (/opt/dev/projects/github/liferay-portal/modules/apps/frontend-js/frontend-js-web/node_modules/jsdom/lib/jsdom/browser/Window.js:628:19)
     [exec]           at ontimeout (timers.js:482:11)
     [exec]           at tryOnTimeout (timers.js:317:5)
     [exec]           at Timer.listOnTimeout (timers.js:277:5) matcherResult: { message: [Function], pass: false } }
     [exec] 
     [exec]   ??? PortletHub ??? onStateChange without render data ??? is passed a type parameter with value "portlet.onStateChange"
     [exec] 
     [exec]     expect(jest.fn()).toHaveBeenCalled()
     [exec] 
     [exec]     Expected mock function to have been called, but it was not called.
     [exec] 
     [exec]       603 | 						setTimeout(
     [exec]       604 | 							() => {
     [exec]     > 605 | 								expect(onStateChange).toHaveBeenCalled();
     [exec]           | 								                      ^
     [exec]       606 | 								expect(onStateChange.mock.calls[0][0]).toEqual(eventType);
     [exec]       607 | 
     [exec]       608 | 								hubA.removeEventListener(handle);
     [exec] 
     [exec]       at test/liferay/portlet/events.es.js:605:31
     [exec]       at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:628:19)
   ```

**Comment by jbalsas** [comment]
Looks like a fluke, it's working fine locally 😢 

We'll take a look at this again asap!

**Comment by jbalsas** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@topolik this might be something you care about

**Pull request closed without merging**
