### PR TITLE
LPS-73684

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:reopen

**Comment by jpince** [comment]
@adolfopa modules-integration failures in mariadb and mysql look related, can you please take a look?
`java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.portal.increment.BufferedIncrementRunnable, message=Unable to persist buffered increment value:`
`com.liferay.document.library.kernel.service.DLFolderLocalService.updateLastPostDate(long,java.util.Date)@com.liferay.portlet.documentlibrary.service.impl.DLFolderLocalServiceImpl`

Here are the tests that failed in both batches:
com.liferay.document.library.service.test.DLAppServiceTest$WhenAddingAFileEntry.shouldSucceedWithNullBytes
com.liferay.document.library.service.test.DLAppServiceTest$WhenAddingAFileEntry.shouldSucceedWithNullFile
com.liferay.document.library.service.test.DLAppServiceTest$WhenAddingAFileEntry.shouldSucceedWithNullInputStream
com.liferay.document.library.service.test.DLFileVersionUpdateTest.testWithExtensionWithContent
com.liferay.document.library.service.test.DLFileVersionUpdateTest.testWithExtensionWithoutContent
com.liferay.document.library.service.test.DLFileVersionUpdateTest.testWithoutExtensionWithContent
com.liferay.document.library.service.test.DLFileVersionUpdateTest.testWithoutExtensionWithoutContent
com.liferay.message.boards.service.test.MBMessageLocalServiceTest.testAddMessageAttachment
com.liferay.message.boards.service.test.MBMessageLocalServiceTest.testDeleteAttachmentsWhenUpdatingMessageAndTrashDisabled
com.liferay.message.boards.service.test.MBMessageLocalServiceTest.testDeleteAttachmentsWhenUpdatingMessageAndTrashEnabled
com.liferay.message.boards.service.test.MBMessageLocalServiceTest.testDeleteMessageAttachment
com.liferay.repository.capabilities.test.TemporaryFileEntriesCapabilityTest.testDeleteExpiredTemporaryFileEntries

**Comment by jpince** [comment]
ci:close

**Comment by jpince** [comment]
ci:reopen I see these errors in other pulls, they are inconsistent

**Comment by brianchandotcom** [comment]
@adolfopa I don't see how this can work:

```
	public void deleteRepositoryFileShortcuts(long repositoryId)
		throws PortalException {

		long groupId = repositoryId;

		Repository repository = _repositoryLocalService.fetchRepository(
			repositoryId);

		if (repository != null) {
			groupId = repository.getGroupId();
		}

		ActionableDynamicQuery actionableDynamicQuery =
			dlFileShortcutLocalService.getActionableDynamicQuery();

		actionableDynamicQuery.setAddCriteriaMethod(
			dynamicQuery -> dynamicQuery.add(
				RestrictionsFactoryUtil.eq("repositoryId", repositoryId)));
		actionableDynamicQuery.setGroupId(groupId);
		actionableDynamicQuery.setPerformActionMethod(
			(DLFileShortcut fileShortcut) ->
				dlFileShortcutLocalService.deleteDLFileShortcut(fileShortcut));
```

You only call setters and never actually execute the actionable dynamic query. I don't see how the tests are passing? You must not be testing that case?

Please resend.

**Pull request closed without merging**
