### PR TITLE
LPS-170788 Filter object applications

### PR DESCRIPTION
**Pull request by LuismiBarcos**
Manually forwarding from https://github.com/liferay-headless/liferay-portal/pull/914

Original PR description:

## Purpose of the PR
Filtering the Object REST Applications created dynamically in the Liferay API Explorer.

When we have more than one instances, the objects created can be visible (only the name) among the different Liferay instances. This PR solves that.

### Before the PR
Instance 1: 
image

Instance 2:
image

### After the PR
Instance 1: image
Instance 2: 
image

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
ci:reopen

**Comment by LuismiBarcos** [comment]
cc/ @ccorreagg @4lejandrito

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1005a0d267...113713165c

**Comment by brianchandotcom** [comment]
@LuismiBarcos see changes in my origin.

Can you guys add some tests for this? Thx.

**Pull request closed without merging**
