### PR TITLE
LPS-56919

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-56919. 

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cbc3cdddc0...41a06b7a51

**Comment by pei-jung** [comment]
@ZoltanTakacs Could you backport this to 7.0.x? Thanks!

**Comment by ZoltanTakacs** [comment]
Hi @pei-jung,

The latest date for Milestone 7 backports was 8/14.
Please contact Joshua Kuo or Esther Sanz if you think that it's important to include in M7.

Thanks,
Zoltán

**Pull request closed without merging**
