### PR TITLE
LPS-66704 Fix NPE

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by nikki-pru** [comment]
This pull request addresses the Wiki NPEs that are affecting tests in the pull request tester.

**Comment by jpince** [comment]
@brianchandotcom looks good from a functional test perspective, please merge asap

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b12b2683c4...5aeba085ac

**Comment by brianchandotcom** [comment]
@sergiogonzalez @nikki-pru see 5aeba085ac4f2d04a024fc2748419138d94c04db

**Comment by brianchandotcom** [comment]
@sergiogonzalez @nikki-pru see 5aeba085ac4f2d04a024fc2748419138d94c04db

**Pull request closed without merging**
