### PR TITLE
LPS-77458 Apply new NavigationBar pattern to portal-instances-web

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test

**Comment by pei-jung** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@shuyangzhou I'm not able to replicate this compile error locally, but I think it has to do with one of your commits. Can you replicate?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/928b29a0bc...7615e0447b

**Comment by shuyangzhou** [comment]
@brianchandotcom I did not touch that class. And I can not reproduce it either. This looks like a build issue, @Ithildir any idea?

**Comment by shuyangzhou** [comment]
Oh, @petershin fixed it here a55a57b28059fcc59381649822576a5ef4b996f3, it was caused by adbddeba516dd455aef07a06237a21892e6d30b6.
However the real issue is in the test class itself, it is referencing an internal class in another module, which is fundamentally wrong. Let's ignore it for now, I bet we have a lot case like this, we need a systematical way to clean them up.

**Pull request closed without merging**
