### PR TITLE
LPS-63295 Do not update ExpandoColumn when it was not modified

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
@brianchandotcom - This one is running, and the results should be returning soon.

The 'source' job took 23 minutes so that backlogged this pull a bit. (This is the one that syncs with local git)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/37e4a3a6ef...e9dad5f38e

**Comment by brianchandotcom** [comment]
@migue @jorgediaz-lr I rolled back this fix. It doesn't seem right because *PersistenceImpl already checks to make sure all the fields are up to date before calling Hibernate.. so the root cause is somewhere else. Please resend. Thx.

**Pull request closed without merging**
