### PR TITLE
Fixes Test Failure caused by LPS-72285

### PR DESCRIPTION
**Pull request by mbowerman**
@brianchandotcom I'm sending this directly to you since the regression is causing all pull requests to automatically be closed right now.

@adolfopa Please let me know if there was a good reason for removing this file. Then maybe we can look into an alternative solution or rewriting the tests instead.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@mbowerman how did this pass CI before? Merging.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/37bbd6b331...e0fb600cd8

**Comment by mbowerman** [comment]
@brianchandotcom Not sure what you mean by that question. The pull request I referenced failed CI. Please see [this comment|https://github.com/brianchandotcom/liferay-portal/pull/48774#issuecomment-298936817]. If you scroll to the bottom of the comment, you will see that ModuleStructureTest.testScanBuildScripts failed with [the same failure I mentioned on the pull request](https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/111853//testReport/com.liferay.portal.modules/ModulesStructureTest/testScanBuildScripts).

If you're asking why that pull request was auto-closed due to modules-compile-jdk8 instead of due to unit-jdk8, then my guess is that as soon as one critical batch failure happens, it is reported immediately and the pull request is automatically closed. In this case, modules-compile-jdk8 failed before the unit-jdk8 failure was detected, so it only reported modules-compile-jdk8 as having failed. Of course, this is just speculation on my part; I have no idea if this is actually how it works or not, but this makes sense to me.

**Comment by jpince** [comment]
@mbowerman yes, that is exactly how it works :) The idea is that we would give feedback to the devs as soon as a critical batch fails, rather than waiting for all tests to finish and analyze which is the most "important" one. It's unfortunate when an issue like the modules-compile one slips in, but QA Engineering is constantly working to plug those holes. Thanks for your follow-up to resolve the failure.

**Comment by jpince** [comment]
@ithildir fyi, if you have any advice for this situation. See also https://github.com/brianchandotcom/liferay-portal/pull/48774#issuecomment-298973985

**Pull request closed without merging**
