### PR TITLE
LPS-68102 Form page options icon overlaps with progress bar line | master

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LPS-68102

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 no results?

**Comment by brianchandotcom** [comment]
@brianchiu I'm just going to risk this and trust you.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by pyoo47** [comment]
@brianchandotcom Looks like we had some kind of network outage. The curl command that was executed to update GitHub failed with the following error.

```
[beanshell] curl --data @/opt/dev/projects/github/liferay-jenkins-ee/github-data.json --header "Authorization: token 64abd1bdb03b908e013e497dc2c17ee3763b18b1" --request PATCH https://api.github.com/repos/brianchandotcom/liferay-portal/issues/comments/249741450
     [exec] 
     [exec] curl: (6) Couldn't resolve host 'api.github.com'
     [exec] 
     [exec] curl: (6) Couldn't resolve host 'api.github.com'
   [delete] Deleting: /opt/dev/projects/github/liferay-jenkins-ee/commands/20160926193141593

BUILD FAILED
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-test-portal-acceptance-pullrequest.xml:345: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:5948: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-github.xml:166: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-github.xml:111: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:557: exec returned: 6

Total time: 11 seconds
Build step 'Execute a set of scripts' marked build as failure
Finished: FAILURE
```

**Comment by brianchiu** [comment]
Got it.

Original results (from original pull) here:
https://github.com/brianchiu/liferay-portal/pull/1500

CC @inacionery

**Pull request closed without merging**
