### PR TITLE
LPS-88762

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jorgediaz-lr @adolfopa see  3419b96 thx.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by jorgediaz-lr** [comment]
Hi @brianchandotcom @adolfopa 

Your commit https://github.com/brianchandotcom/liferay-portal/commit/3419b9607df850f6ccdef96207624a747bc1fd4c changes code behavior because inside *_checkOutDLFileEntryModel* method, version is updated to PRIVATE_WORKING_COPY_VERSION, and we want to use old value for later check.

**Comment by jorgediaz-lr** [comment]
Update: I have talked with brian in person as he is in Madrid office :-)

**Pull request closed without merging**
