### PR TITLE
LPS-61318 Improve the user experience when using Portal Settings by applying Lexicon mockups

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@JorgeFerrer @evannagayama can you go over this pull from Jorge? He broke a Poshi test. Thx.

**Comment by JorgeFerrer** [comment]
Sorry about this guys. 

@evannagayama don't worry about this since this does not belong to your team and I'm sure Julio has enough tasks for you already.

I will resend the pull to @alee8888

**Comment by evannagayama** [comment]
Sounds good, thanks everyone!

**Pull request closed without merging**
