### PR TITLE
Lps 67079

### PR DESCRIPTION
**Pull request by shuyangzhou**
@dantewang @slnn performance check please.

@hhuijser is it possible to SF this?

### CODE REVIEW

**Comment by hhuijser** [comment]
@shuyangzhou, adding it to my todo list...

**Comment by hhuijser** [comment]
@shuyangzhou @Preston-Crary 

Can you close this pull?

I'll send a pull to Preston with the SF changes that autofixes this.
I also want to fix the inconsistent styling between <#assign ...> vs. <#assign ... /> first

**Comment by Preston-Crary** [comment]
@hhuijser Shuyang started vacation today, he's going to be out for several weeks.

@brianchandotcom Please close the pull and I'll incorporate Hugo's changes and resend.

**Comment by hhuijser** [comment]
See https://github.com/Preston-Crary/liferay-portal/pull/142

**Pull request closed without merging**
