### PR TITLE
LPS-69147 1975 London Theme

### PR DESCRIPTION
**Pull request by jbalsas**
Hey Brian!

This is the final theme of the series, 1975-London.

I've sent the BPR to @ZoltanTakacs [here](https://github.com/ZoltanTakacs/liferay-portal-ee/pull/2144)

Please, let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by jpince** [comment]
cc/ @kenjiheigel

**Comment by jpince** [comment]
ci:retest

**Comment by jbalsas** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
@jbalsas, looking into the lpkg failures.

**Comment by kenjiheigel** [comment]
I believe it's something in the ant scripts. I think it wasn't written to account for numbers in the package.json.

**Comment by kenjiheigel** [comment]
@jbalsas, retesting here: https://github.com/kenjiheigel/liferay-portal/pull/331. 

Will resend to BChan once I confirm the fix on CI.

**Comment by kenjiheigel** [comment]
Here's the error, for reference:
https://gist.github.com/kenjiheigel/52367878506262b80ac6d1b9186df84c

Resent to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/45087
https://github.com/brianchandotcom/liferay-portal-ee/pull/15227

**Pull request closed without merging**
