### PR TITLE
LPS-63782 Proper handling of database users with access to different schemas

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by migue** [comment]
@brandizzi I changed your module so we can reuse the functionality which is already implemented.

@mdelapenya we've talked a few times about this topic, and I think this should cover most of the scenarios

**Comment by brandizzi** [comment]
Great, thank you!

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
@migue I see the following two errors in the sybase batches in both runs:
`java.lang.AbstractMethodError: com.sybase.jdbc4.jdbc.SybConnection.getSchema()Ljava/lang/String;`
`com.liferay.portal.kernel.exception.NoSuchCompanyException: No Company exists with the key {webId=liferay.com}`
Not sure if they are caused by this pull, but I don't see them elsewhere.

**Comment by migue** [comment]
@jpince Seems that the JDBC Driver we're using for Sybase doesn't properly implement the JDBC spec. Could you please make a favour and double check the version of the driver we're using in the CI?

**Comment by jpince** [comment]
This is the information I got from QA Engineering, is this what you were looking for?
jConnect (TM) for JDBC(TM)/16.0 PL01 N-OFF (Build 27031)/P/EBF22531/JDK 1.6.0/jdbcmain/OPT/Thu Mar 20 11:14:13 PDT 2014

**Comment by migue** [comment]
Thanks!

I will handle this in our side (not sure there's a newer version of the driver available)

**Pull request closed without merging**
