### PR TITLE
LRQA-22246 Add slaveCount, testCount and total cpu time to performance data table.

### PR DESCRIPTION
**Pull request by pyoo47**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
@brianchiu Brian, here's an example of a pull request that I submitted where a Poshi test failed but then passed on ci:retest. I originally submitted this pull last night and retested it this morning.

**Comment by brianchiu** [comment]
@pyoo47 
I see it. The error for this one was one of these errors.

"Element not found in the cache - perhaps the page has changed since it was looked up"

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/52ae807078...785509db6d

**Comment by brianchandotcom** [comment]
@pyoo47 please see my changes in upstream.  I also published a new jar.

**Pull request closed without merging**
