### PR TITLE
LPS-98886 Adding A/B Testing Variants [NO BACKPORT]

### PR DESCRIPTION
**Pull request by epgarcia**
@brianchandotcom this is needed in order to start testing the A/B test visitor traffic split. Thanks!

@bryceosterhaus

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b1e706e85b...295ecfe7b2

**Comment by brianchandotcom** [comment]
@epgarcia can you see my changes in upstream? I only fixed a few in 570f17495296ce7be349d03dd83aee50dea026ea but I'd like you to fix the rest from this pull.

@jbalsas can we auto enforce 570f17495296ce7be349d03dd83aee50dea026ea in our lint?

Thx.

**Comment by dgarciasarai** [comment]
@andresfulla

**Comment by jbalsas** [comment]
Hey @brianchandotcom, yeah, we have https://github.com/liferay/eslint-config-liferay/issues/52 open to track this down and enforce!

**Pull request closed without merging**
