### PR TITLE
LPS-59167 Additional mappings for LiferayDocumentType via config admin and contributor interface

### PR DESCRIPTION
**Pull request by arboliveira**
Authors: @arturbr @arboliveira
Reviewer: @mhan810

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by alee8888** [comment]
@brianchandotcom 
The functional test CPUsersandorganizations#DeleteOrganization failure is due to a test fix I sent in yesterday and is not a bug. I am sending a PR to you soon to fix this.

**Comment by brianchandotcom** [comment]
@arboliveira please resend, this part doesn't look right:

```
				additionalConfigurations=\
					\ncluster.routing.allocation.disk.threshold_enabled: false\
					\ncluster.service.slow_task_logging_threshold: 600s\
					\nindex.indexing.slowlog.threshold.index.warn: 600s\
					\nindex.search.slowlog.threshold.fetch.warn: 600s\
					\nindex.search.slowlog.threshold.query.warn: 600s\
					\nmonitor.jvm.gc.old.warn: 600s\
					\nmonitor.jvm.gc.young.warn: 600s
				logExceptionsOnly=false
```

See how logExceptionsOnly is missing a \ after 600s. How does that work?

Can you make it look like

```
cluster.routing.allocation.disk.threshold_enabled: false\\n
```

after each line? Thx.

**Pull request closed without merging**
