### PR TITLE
LPS-106918 | master

### PR DESCRIPTION
**Pull request by MichaelPrigge**
https://issues.liferay.com/browse/LPS-106918

[LPS-86455](https://issues.liferay.com/browse/LPS-86455) created a new entity in the database. During the progress of the fix the name changed from DLFileEntryPreview to FileVersionPreview and ultimately settled on DLFileVersionPreview.

`DLFileEntryPreview > FileVersionPreview > DLFileVersionPreview`

The following [commit](https://github.com/liferay/liferay-portal-ee/commit/b58ecd48b4526d7deecce74738f5d0c2929f64c1#diff-81f2d2f7080d42bc5351fa07d28f9296R6) made the final name change.

Some of the old autogenerated classes were removed in [this commit](https://github.com/liferay/liferay-portal-ee/commit/5cb855d67bdaac2fddf900055c9e946b0fd01b73) after the name change mentioned above.

Finally the new replacement classes were generated [here](https://github.com/liferay/liferay-portal-ee/commit/f874c7ad4a9db4e8344733c377f27c0523a747c6).

Unfortunately [this commit](https://github.com/liferay/liferay-portal-ee/commit/5cb855d67bdaac2fddf900055c9e946b0fd01b73) missed removing the following no longer needed autogenerated classes:

> FileVersionPreview.java
> FileVersionPreviewLocalService.java
> FileVersionPreviewLocalServiceUtil.java
> FileVersionPreviewLocalServiceWrapper.java
> FileVersionPreviewModel.java
> FileVersionPreviewPersistence.java
> FileVersionPreviewSoap.java
> FileVersionPreviewUtil.java
> FileVersionPreviewWrapper.java

Please let me know if you have any questions or concerns. Thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@nhpatt can you fix:

```
Test Result (42 failures / +42)
com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXMLLog
com.liferay.headless.delivery.resource.v1_0.test.BlogPostingResourceTest.testGraphQLDeleteBlogPosting
com.liferay.headless.delivery.resource.v1_0.test.BlogPostingResourceTest.testGraphQLGetBlogPosting
com.liferay.headless.delivery.resource.v1_0.test.BlogPostingResourceTest.testGraphQLGetSiteBlogPostingsPage
com.liferay.headless.delivery.resource.v1_0.test.BlogPostingResourceTest.testGraphQLPostSiteBlogPosting
com.liferay.headless.delivery.resource.v1_0.test.CommentResourceTest.testGraphQLDeleteComment
com.liferay.headless.delivery.resource.v1_0.test.CommentResourceTest.testGraphQLGetComment
com.liferay.headless.delivery.resource.v1_0.test.ContentStructureResourceTest.testGraphQLGetContentStructure
com.liferay.headless.delivery.resource.v1_0.test.ContentStructureResourceTest.testGraphQLGetSiteContentStructuresPage
com.liferay.headless.delivery.resource.v1_0.test.DocumentFolderResourceTest.testGraphQLDeleteDocumentFolder
Show all failed tests >>>
```

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8fe8367004...6c4f4d8fd1

**Comment by nhpatt** [comment]
@brianchandotcom it's a security regression (https://issues.liferay.com/browse/LPS-106919), I've pinged Stian because I don't know exactly what security check they want to add. It was introduced in this PR: https://github.com/brianchandotcom/liferay-portal/pull/83001

I could send a PR to allow REST calls when contextPath == requestPath and urlIncludes == "*" if you want, but pretty sure security will change the implementation later.

**Comment by MichaelPrigge** [comment]
lbm:backport

**Pull request closed without merging**
