### PR TITLE
LPS-70692 Firebase Cloud Messaging support

### PR DESCRIPTION
**Pull request by brunofarache**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@shuyangzhou

```
java.util.ConcurrentModificationException
[junit] 	at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1207)
[junit] 	at java.util.TreeMap$EntryIterator.next(TreeMap.java:1243)
[junit] 	at java.util.TreeMap$EntryIterator.next(TreeMap.java:1238)
[junit] 	at java.util.TreeMap.buildFromSorted(TreeMap.java:2555)
[junit] 	at java.util.TreeMap.buildFromSorted(TreeMap.java:2504)
[junit] 	at java.util.TreeMap.(TreeMap.java:200)
[junit] 	at org.apache.felix.cm.impl.CaseInsensitiveDictionary.(CaseInsensitiveDictionary.java:62)
[junit] 	at org.apache.felix.cm.impl.CachingPersistenceManagerProxy.copy(CachingPersistenceManagerProxy.java:259)
[junit] 	at org.apache.felix.cm.impl.CachingPersistenceManagerProxy.getDictionaries(CachingPersistenceManagerProxy.java:155)
[junit] 	at org.apache.felix.cm.impl.ConfigurationManager.listConfigurations(ConfigurationManager.java:658)
[junit] 	at org.apache.felix.cm.impl.ConfigurationAdminImpl.listConfigurations(ConfigurationAdminImpl.java:185)
[junit] 	at org.apache.felix.scr.impl.manager.RegionConfigurationSupport.getConfigurationInfo(RegionConfigurationSupport.java:445)
[junit] 	at org.apache.felix.scr.impl.manager.RegionConfigurationSupport.configurationEvent(RegionConfigurationSupport.java:259)
[junit] 	at org.apache.felix.cm.impl.ConfigurationManager$FireConfigurationEvent.sendEvent(ConfigurationManager.java:2046)
[junit] 	at org.apache.felix.cm.impl.ConfigurationManager$FireConfigurationEvent.run(ConfigurationManager.java:2014)
[junit] 	at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:143)
[junit] 	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:110)
[junit] 	at java.lang.Thread.run(Thread.java:745)
[junit]
[junit]
[junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanOSGiLog(PortalLogAssertorTest.java:82)
[junit]
[junit]
```

I've seen this many times now.

**Comment by shuyangzhou** [comment]
@tinatian did we get anywhere on this? Let's focus on this one to give it a higher priority.

**Comment by tinatian** [comment]
@shuyangzhou  I almost finished the session filter and will go back on this soon.

Tina.

**Comment by brianchandotcom** [comment]
@brunofarache please see my changes in upstream. Thx.

**Comment by tinatian** [comment]
Hi @brianchandotcom @shuyangzhou ,

For the random ConcurrentModificationException, please see my fix here: https://github.com/shuyangzhou/liferay-portal/pull/3858

**Pull request closed without merging**
