### PR TITLE
LRQA-60677 Update tests

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by evannagayama** [comment]
Investigating functional failures, and will resend

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
looks like only the integration tests are failing. the last functional test failure was a fluke, I ran it locally and it passed.

**Comment by evannagayama** [comment]
@jkappler I'm not sure exactly what you intended to do with your poshi change?

**Comment by jkappler** [comment]
Hi @evannagayama, we removed a preference from Asset Publisher, so I removed that's why I updated that test, so it wouldn't look for it.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@evannagayama I think this is a real bug. Can you resend? Thx.

**Comment by evannagayama** [comment]
@brianchandotcom and @jkappler I think the functional test failing is a fluke.

I ran it locally and it passes. Also I pushed to BChiu here https://github.com/brianchiu/liferay-portal/pull/989 without changing anything and only the integration test fails. I'm not sure what to make of it?

**Comment by evannagayama** [comment]
@ealonso  @jkappler  
Please push this again. I believe it's failing because of a fluke in our functional tests and this pr https://github.com/brianchandotcom/liferay-portal/pull/32515 should fix that issue.

**Pull request closed without merging**
