### PR TITLE
LPS-73725 Liferay 7.0 user monograms (profile pictures) need to take account of regional customs surrounding names

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-73725](https://issues.liferay.com/browse/LPS-73725).<br><br>/cc @pei-jung, @jorgeferrer

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:retest

**Comment by alee8888** [comment]
This was a fluke, JBoss timed out on deployment of ROOT.war so portal never started. Doing a ci:retest.

`[exec] [0m[0m20:17:27,150 INFO  [org.jboss.as.server] (DeploymentScanner-threads - 2) WFLYSRV0009: Undeployed "ROOT.war" (runtime-name: "ROOT.war")
     [exec] [0m[0m20:17:27,156 INFO  [org.jboss.as.server.deployment.scanner] (DeploymentScanner-threads - 1) WFLYDS0004: Found ROOT.war in deployment directory. To trigger deployment create a file called ROOT.war.dodeploy`

**Comment by alee8888** [comment]
ci:retest

**Comment by drewbrokke** [comment]
@brianchandotcom is it possible for us to review this one today?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3452cbbaaf...6db20ba7cf

**Pull request closed without merging**
