### PR TITLE
LPS-64100 - As a developer, frontend modules should be organized and namespaced in modules/apps/foundation

### PR DESCRIPTION
**Pull request by mjbradford89**
Hey Brian,

Attached is another update for https://issues.liferay.com/browse/LPS-64100.

I believe I fixed the issues causing the failures, hopefully :sweat_smile: .

Please let me know if there are any issues.

Thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest just fixed upstream....

**Comment by brianchandotcom** [comment]
@mjbradford89 can you rebase and resend?

**Comment by mjbradford89** [comment]
sure, new pull here: https://github.com/brianchandotcom/liferay-portal/pull/37429

**Pull request closed without merging**
