### PR TITLE
LPS-127518 IBM S3 Store

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
Hi @brianchandotcom,

This is a proposal to add the the IBM S3 Store. I've been discussing it with @adolfopa and he is ok with it.

The 2 classes (the original and the new one) are almost identical apart from their names and package names. With these changes we will be autogenerating the `IBM` one from the original one with a simple set of replacements (see https://github.com/brianchandotcom/liferay-portal/pull/98629/commits/32c83380802e32ccb47d222fc92099e3b393f5ca and https://github.com/brianchandotcom/liferay-portal/pull/98629/commits/847d57ecfa7dbc378e7755b2081bc02c49dafb95).

With these approach we don't have to refactor the whole thing and we can keep fixing bugs in the original class and auto generate the IBM one. This saves us a lot of work and also gives us the option to diverge in the future if needed.

Please let me know what you think.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5860529bca...ba3d0b3c57

**Comment by brianchandotcom** [comment]
@adolfopa @4lejandrito this is super nice.

See 10d4ff7178adbb0cd327d979effe3d226b636732 f89bf50a9ee25abcbb8203b916588df250a91589 and ba3d0b3c57e9698c8d08f74e6b29823dc70e6764

I also fixed some bugs in dd80bc68e60f23f0d5e8ad201466e9a4bd2a3529 f8d26fb92945088f71b84f44aba2a99d2645efb4 and e54c1f5d725679d3590078133b473fcd61fc460b

@adolfopa Please send me a backport directly (bypass support) to 7.2.x. It has some minor changes due to how S3Store changed, but should be very easy as well.

@petershin can you review the changes in modules/apps/portal-store/portal-store-s3/build.gradle

**Comment by brianchandotcom** [comment]
@adolfopa @4lejandrito @petershin I also want to make one other change Peter.

When I run "gw clean", I want to delete IBMS3Store.java.

When I run "gw build/classes", I want to regenerate.

This ensures that if I make a change to S3Store.java, and I will never "forget" to regen. And this is fast anyways (copying a file).

**Comment by petershin** [comment]
@brianchandotcom - Sent a patch: https://github.com/petershin/liferay-portal/pull/1353

**Pull request closed without merging**
