### PR TITLE
Validator  javadoc

### PR DESCRIPTION
**Pull request by jhinkey**
cc/ @adamnagy @codyhoag

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@shuyangzhou this testScanXmlLog just came in.. and it's happening randomly now (should be an easy fix, can someone on your team take a look?)

Thx

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ab55564997...eee492327f

**Comment by shuyangzhou** [comment]
Ok, we will take care of it.

**Comment by Preston-Crary** [comment]
Pull to resolve the log assertion failure:
https://github.com/shuyangzhou/liferay-portal/pull/2342

**Pull request closed without merging**
