### PR TITLE
LPS-60355 Better check if the registration is there

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
/cc @rotty3000 @juangon @epgarcia @adolfopa 

this is the pull that disables `context.boot.delegation` in Equinox so no more resources are _leaked_ from `portal-impl.jar` without being properly exported and imported. 

@brianchandotcom, this pull also solves some pieces of code that were relying on those leaks to obtain resources from `portal-impl.jar`. 

Thank you guys for all your help!

**Comment by rotty3000** [comment]
FYI, I've spoken to the IBM's Equinox architect and they themselves have
this flag set this way in their servers.

+1

**Comment by rotty3000** [comment]
I don't get this... the tests are still running!!!!

**Comment by juangon** [comment]
Hmmm should we trigger the retest? For github check have failed although as Ray said jenkins tests are in queue.

**Comment by brianchandotcom** [comment]
@kiyoshilee can you give some insight into this?

**Comment by pyoo47** [comment]
ci:retest
The LoadBalancer bombed out while trying to update one of the recentJobs files.. I've seen this happen every once in a while but I'm not sure what's causing it. When the LoadBalancer wants to write the file, it thinks that it is not there but it seems like the file appears right before the new file is written which causes a FileAlreadyExistsException. For now, we should trigger the retest.

**Comment by brianchandotcom** [comment]
Retriggering based on recommendation from @pyoo47  ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by csierra** [comment]
Follow up https://github.com/brianchandotcom/liferay-portal/pull/35029

**Pull request closed without merging**
