### PR TITLE
LPS-153072 Create SF rule to replace unnecessary Gradle dependencies with "release.dxp.api"

### PR DESCRIPTION
**Pull request by kevhlee**
__Previous pull request:__
<https://github.com/brianchandotcom/liferay-portal/pull/121113>

__Notes:__
I've done the SF renames that you requested. I'm pretty sure I covered all of them, but let me know if that's not the case.

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a3b5fbf585...762167d65e

**Comment by brianchandotcom** [comment]
Beautiful @kevhlee see my change in 762167d65efdebf6dff5e038a49f247553efa76b

Also
```
compileOnly group: "org.osgi", name: "org.osgi.core", version: "6.0.0"
```

I think that's in the fat jar.

**Comment by kevhlee** [comment]
cc: @ling-alan-huang

**Pull request closed without merging**
