### PR TITLE
LRQA-57660 Ignore AppBuilder#RemoveFormViewFieldInObjectSidebar due to LPS-111624

### PR DESCRIPTION
**Pull request by alexcandidos**

### CODE REVIEW

**Comment by alexcandidos** [comment]
ci:reopen

**Comment by alexcandidos** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/370ccd93cc...7adcd9dffd

**Pull request closed without merging**
