### PR TITLE
LPS-58902 Cannot delete a site

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
CC: @ealonso

**Comment by jkappler** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9b87d7c0c3...82849142cc

**Pull request closed without merging**
