### PR TITLE
LPS-70814 We cannot acces to resources outside our scope

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @Alec-Shay,

It should be also backported as part of LPS-70814.

**Comment by jpince** [comment]
@ealonso semver error, can you please take a look?
```
     [exec] 10:27:50,422 WARN  [fileinstall-/opt/dev/projects/github/liferay-portal/bundles/osgi/modules][org_apache_felix_fileinstall:103] Error while starting bundle: file:/opt/dev/projects/github/liferay-portal/bundles/osgi/modules/com.liferay.layout.admin.web.jar 
     [exec] org.osgi.framework.BundleException: Could not resolve module: com.liferay.layout.admin.web [371]
     [exec]   Unresolved requirement: Import-Package: com.liferay.journal.model; version="[1.0.0,2.0.0)"
```
closing this pull

**Comment by jpince** [comment]
ci:close

**Comment by ealonso** [comment]
Resend: https://github.com/brianchandotcom/liferay-portal/pull/47269

**Comment by Alec-Shay** [comment]
@ealonso Will do, thanks for bringing this to my attention before I finished the backport

**Pull request closed without merging**
