### PR TITLE
LPS-88408 SF

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test:staging

**Comment by jpince** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6bdd3c165c...14152057de

**Comment by brianchandotcom** [comment]
@ajsampang67 @matethurzo see 14152057de3d394ca022ebda419e1d586a169e4a thx.

**Pull request closed without merging**
