### PR TITLE
[TS] LPS-161024

### PR DESCRIPTION
**Pull request by patriciajeanperez**
Manual forward from https://github.com/liferay-usm/liferay-portal/pull/711

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:reopen

**Comment by ChrisKian** [comment]
Hey @brianchandotcom,

That's correct, ABLE.COM and able.com can both exist in the DB before the fix.  However, the upgrade process will [attempt to change ABLE.COM to able.com](https://github.com/brianchandotcom/liferay-portal/pull/122732/files?diff=unified&w=0#diff-535516d5ee82a243e7b649f9eaa4ef187da37dda4ef488201c3a3f39d1ea8a82R47-R50), and if unsuccessful, will instead [delete the ABLE.COM entry](https://github.com/brianchandotcom/liferay-portal/pull/122732/files?diff=unified&w=0#diff-535516d5ee82a243e7b649f9eaa4ef187da37dda4ef488201c3a3f39d1ea8a82R54-R64).

We have a unique constraint on Virtualhost.hostname, so in your example converting ABLE.COM to able.com and attempting to save it will throw an error, resulting in the deletion of the ABLE.COM Virtualhost entry.  I figure this is acceptable, since ABLE.COM was never truly used to begin with and the user won't know the difference.

**Comment by ChrisKian** [comment]
Hey @brianchandotcom,

@bakayattila and I spoke and decided our situations are different, but at the very least, **_RedirectEntries should not be removed_**, since they can remove functionality for users.  A warning message and some new documentation on the matter should be enough.

For Virtualhost entries, non-lowercase hostnames are **_never used to begin with_**, with or without a lowercase counterpart already present.  This is because we perform the fetch **_after converting the hostname search string to lowercase_**.  Since non-lowercase virtualhosts are never fetched, deleting them won't impact functionality.

If you'd like uniformity, I can adjust the fix to warn the user like we do with Redirects.  This won't affect functionality, but will leave some bad data in the db.

**Comment by ChrisKian** [comment]
Also, Virtualhost entries point to areas within the portal.  If we remove an entry, it still can be navigated to and is available to users.

Redirect entries can point outside of the portal.  If we delete an entry, we may lose context to a URL, and it may be forgotten.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/297cea7466...700f04d4e2

**Comment by brianchandotcom** [comment]
@ChrisKian see changes in my origin to verify I didn't break anything. Thx.

**Comment by ChrisKian** [comment]
Looks good @brianchandotcom; everything still works as expected.

**Pull request closed without merging**
