### PR TITLE
LPS-100122 Wordsmith

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
This should work on top of @brianchandotcom origin, but not on top of liferay's because it still has missing commits.

@john-co, @jpince, could you advice on how to proceed?

**Comment by jpince** [comment]
ci:test:relevant

retesting, since the stable job just passed and synced to upstream

**Comment by jpince** [comment]
ci:reopen - passed compile, running test batches. 

Failed on the initial run because BChan/origin was not pushed to upstream, and this pull needed https://github.com/brianchandotcom/liferay-portal/commit/e9c48939fcee9df644008693e3f6b18160f38bf2.

**Comment by jpince** [comment]
@john-co a few more test failures that usual? :D can you please take a look?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c41dc5cf05...54735b45c3

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:test:bundle:norebase

**Comment by brianchandotcom** [comment]
@jbalsas major CI errors after bringing this in. Reverting in upstream.

**Comment by john-co** [comment]
Verified the following test failures manually on test bundle. 

1. It looks like dropdown menus don't appear when clicking on certain buttons such as:
- Add (+) button: ie web content, DM
- ellipsis next to an asset: ie blogs > ellipsis on a created blog card
Navigating to web content alone throws this stacktrace in devtools console:
image

2. Alert messages do not appear after creating:
- Site
- Blog
```
14-Oct-2019 21:18:50.576 WARNING [http-nio-8080-exec-3] com.google.template.soy.shared.restricted.Sanitizers.filterNormalizeUri |filterNormalizeUri received bad value 'javascript:Liferay.Sharing.share(34101, 39277, 'Share fast')'
```
image

**Comment by jbalsas** [comment]
Sorry about this, we forgot to remove an export :( 

See https://github.com/brianchandotcom/liferay-portal/pull/79545

**Pull request closed without merging**
