### PR TITLE
LPS-69161 Regen

### PR DESCRIPTION
**Pull request by marcellustavares**
cc @leoadb

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:reopen

**Comment by marcellustavares** [comment]
Same pull request, different results @jpince. Could you please help me with this?

https://github.com/marcellustavares/liferay-portal/pull/1850

**Comment by brianchandotcom** [comment]
@marcellustavares DTD issue, please resend.

**Comment by brianchandotcom** [comment]
@marcellustavares nvm, we fixed the DTD issue, it's a Gradle thing. Merging.

**Comment by brianchandotcom** [comment]
@marcellustavares this test failure is real though

https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/98035/

So not merging.

**Comment by vicnate5** [comment]
@marcellustavares 

I am unable to reproduce the failure locally.

The test ran on both your pulls, but only failed on one of them. 

https://github.com/brianchandotcom/liferay-portal/pull/47983 Result:
```
[exec] Unable to find npm-shrinkwrap.json for project ':apps:forms-and-workflow:dynamic-data-mapping:dynamic-data-mapping-type-options', using package.json instead
     [exec] Restoring node_modules of project ':apps:forms-and-workflow:dynamic-data-mapping:dynamic-data-mapping-type-options' from /root/.liferay/node-modules-cache/1057972111
     [exec] :apps:forms-and-workflow:dynamic-data-mapping:dynamic-data-mapping-type-options:gulpTest[12:16:57] Using gulpfile /opt/dev/projects/github/liferay-portal/modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-type-options/gulpfile.js
     [exec] [12:16:57] Starting 'test'...
     [exec] [12:16:57] Starting 'test:unit'...
     [exec] [32m30 03 2017 12:17:02.873:INFO [karma]: [39mKarma v1.5.0 server started at http://0.0.0.0:9876/
     [exec] [32m30 03 2017 12:17:02.875:INFO [launcher]: [39mLaunching browser Firefox with unlimited concurrency
     [exec] [32m30 03 2017 12:17:02.882:INFO [launcher]: [39mStarting browser Firefox
     [exec] [32m30 03 2017 12:17:06.714:INFO [Firefox 38.0.0 (Linux 0.0.0)]: [39mConnected on socket 22Ff6diQSyAtvJqjAAAA with id 34839372
     [exec] Firefox 38.0.0 (Linux 0.0.0): Executed 0 of 8 SUCCESS (0 secs / 0 secs)
     [exec] [1A[2KWARN: 'yui: NOT loaded: aui-autosize-deprecated'
     [exec] Firefox 38.0.0 (Linux 0.0.0): Executed 0 of 8 SUCCESS (0 secs / 0 secs)
     [exec] [1A[2KWARN: 'yui: NOT loaded: aui-autosize-deprecated'
     [exec] Firefox 38.0.0 (Linux 0.0.0): Executed 0 of 8 SUCCESS (0 secs / 0 secs)
     [exec] [1A[2KFirefox 38.0.0 (Linux 0.0.0): Executed 1 of 8 SUCCESS (0 secs / 0.112 secs)
     [exec] [1A[2KFirefox 38.0.0 (Linux 0.0.0): Executed 2 of 8 SUCCESS (0 secs / 0.309 secs)
     [exec] [1A[2KFirefox 38.0.0 (Linux 0.0.0): Executed 3 of 8 SUCCESS (0 secs / 0.481 secs)
     [exec] [1A[2KFirefox 38.0.0 (Linux 0.0.0): Executed 4 of 8 SUCCESS (0 secs / 0.512 secs)
     [exec] [1A[2KFirefox 38.0.0 (Linux 0.0.0): Executed 5 of 8 SUCCESS (0 secs / 0.577 secs)
     [exec] [1A[2KFirefox 38.0.0 (Linux 0.0.0) Liferay.DDM.Field.Options "after each" hook FAILED
     [exec] 	TypeError: r is null (node_modules/alloy-ui/build/node-core/node-core-min.js:1)
     [exec] Firefox 38.0.0 (Linux 0.0.0): Executed 6 of 8 (1 FAILED) (0 secs / 0.578 secs)
     [exec] [1A[2KFirefox 38.0.0 (Linux 0.0.0): Executed 6 of 8 (1 FAILED) (1.493 secs / 0.578 secs)
     [exec] Tests failed.
     [exec] [12:17:08] Finished 'test:unit' after 11 s
     [exec] [12:17:08] Finished 'test' after 11 s
```

https://github.com/marcellustavares/liferay-portal/pull/1850 Result:
```
[exec] Unable to find npm-shrinkwrap.json for project ':apps:forms-and-workflow:dynamic-data-mapping:dynamic-data-mapping-type-options', using package.json instead
     [exec] Restoring node_modules of project ':apps:forms-and-workflow:dynamic-data-mapping:dynamic-data-mapping-type-options' from /root/.liferay/node-modules-cache/1057972111
     [exec] :apps:forms-and-workflow:dynamic-data-mapping:dynamic-data-mapping-type-options:gulpTest[09:27:02] Using gulpfile /opt/dev/projects/github/liferay-portal/modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-type-options/gulpfile.js
     [exec] [09:27:02] Starting 'test'...
     [exec] [09:27:02] Starting 'test:unit'...
     [exec] [32m30 03 2017 09:27:08.339:INFO [karma]: [39mKarma v1.5.0 server started at http://0.0.0.0:9876/
     [exec] [32m30 03 2017 09:27:08.340:INFO [launcher]: [39mLaunching browser Firefox with unlimited concurrency
     [exec] [32m30 03 2017 09:27:08.351:INFO [launcher]: [39mStarting browser Firefox
     [exec] [32m30 03 2017 09:27:09.544:INFO [Firefox 38.0.0 (Linux 0.0.0)]: [39mConnected on socket 2MPQXo-S1sJ5IUPcAAAA with id 75246410
     [exec] Firefox 38.0.0 (Linux 0.0.0): Executed 0 of 8 SUCCESS (0 secs / 0 secs)
     [exec] [1A[2KWARN: 'yui: NOT loaded: aui-autosize-deprecated'
     [exec] Firefox 38.0.0 (Linux 0.0.0): Executed 0 of 8 SUCCESS (0 secs / 0 secs)
     [exec] [1A[2KWARN: 'yui: NOT loaded: aui-autosize-deprecated'
     [exec] Firefox 38.0.0 (Linux 0.0.0): Executed 0 of 8 SUCCESS (0 secs / 0 secs)
     [exec] [1A[2KFirefox 38.0.0 (Linux 0.0.0): Executed 1 of 8 SUCCESS (0 secs / 0.151 secs)
     [exec] [1A[2KFirefox 38.0.0 (Linux 0.0.0): Executed 2 of 8 SUCCESS (0 secs / 0.393 secs)
     [exec] [1A[2KFirefox 38.0.0 (Linux 0.0.0): Executed 3 of 8 SUCCESS (0 secs / 0.573 secs)
     [exec] [1A[2KFirefox 38.0.0 (Linux 0.0.0): Executed 4 of 8 SUCCESS (0 secs / 0.609 secs)
     [exec] [1A[2KFirefox 38.0.0 (Linux 0.0.0): Executed 5 of 8 SUCCESS (0 secs / 0.696 secs)
     [exec] [1A[2KFirefox 38.0.0 (Linux 0.0.0): Executed 6 of 8 SUCCESS (0 secs / 0.916 secs)
     [exec] [1A[2KFirefox 38.0.0 (Linux 0.0.0): Executed 7 of 8 SUCCESS (0 secs / 0.94 secs)
     [exec] [1A[2KFirefox 38.0.0 (Linux 0.0.0): Executed 8 of 8 SUCCESS (0 secs / 0.976 secs)
     [exec] [1A[2KFirefox 38.0.0 (Linux 0.0.0): Executed 8 of 8 SUCCESS (2.386 secs / 0.976 secs)
     [exec] [09:27:12] Finished 'test:unit' after 9.84 s
     [exec] [09:27:12] Finished 'test' after 9.84 s
```


@kenjiheigel @brunobasto Have we seen flakiness in tests like this before?

CC @jpince

**Comment by marcellustavares** [comment]
Thx @vicnate5, @brunobasto, could you please take a look at this? Could we have flaky tests at js unit tests?

Thanks

**Pull request closed without merging**
