### PR TITLE
LPS-55417 check null

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@gamerson  this is a root of a deepr problem no? shoudln't portletBag never be null?

@shuyangzhou is this from your recent portlet refactors? Please resend to make sure the root problem is solved. Thx.

**Comment by shuyangzhou** [comment]
This should be the long exist OSGi portlet register/unregister issue.

@gamerson please provide detailed way to reproduce it. @willnewbury make sure you can reproduce this.

I am actually out of office today, I will take a look tomorrow.

**Comment by gamerson** [comment]
@shuyangzhou @brianchandotcom @willnewbury

sure thing, its easy to reproduce:
1. start liferay master
2. clone blade repo: https://github.com/rotty3000/blade
3. go into the gradle/blade.portlet.ds folder
4. run gradew build
5. copy the build/libs/blade.portlet.ds-1.0.jar to ${liferay.home}/deploy
6. go into portal and add DS portlet to any page
7. verify it is correctly displayed
8. open telnet console on 11311
9. run: ```lb -s blade``` to find the bundle id of osgi portlet
10. run ```stop $id``` 
11. rerun```lb -s blade``` to make sure it stopped
12. go back to browser and refresh

you should see the same exception that is listed in LPS-55417 and every other portlet on page is also not shown either
expected thing you would see is the same messages as when WAR portlets are undeployed

Terry and I have debugged the code and it looks like OSGI portlet is correctly removing the portletBag from the pool during "stopping" of portlet.

Actually the war style portlets when they are "undeployed" those don't properly remove the portlet bag from the pool... the bag is still there actually which seems also wrong.

thanks guys for looking into this.

**Comment by willnewbury** [comment]
I followed the steps that you laid out here on the latest master and I cannot reproduce the error found in the LPS-55417 ticket, everything seems to be working. Namely, after stopping the bundle, the portlet merely pops up a message saying "This porltet has been undeployed. Please redeploy it or remove it from the page". All of the other portlets load correctly, and there is no output on the tomcat side.

**Comment by shuyangzhou** [comment]
I fixed it last night at https://github.com/brianchandotcom/liferay-portal/pull/26291 and CCed you, you did not see that?

**Comment by willnewbury** [comment]
Ah, I see, sorry for the mix up, ignore what I said

**Pull request closed without merging**
