### PR TITLE
LPS-99339 Standardize Ajax requests in frontend-js-aui-web (part2)

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test

**Comment by julien** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c94186fb76...be766b2df7

**Comment by brianchandotcom** [comment]
@julien this causes a real error (things don't compile), see error

:apps:frontend-js:frontend-js-aui-web:packageRunBuild

This was actually in the pull request log.

```
     [exec] > Task :apps:frontend-js:frontend-js-aui-web:packageRunBuild FAILED
     [exec] { SyntaxError: /opt/dev/projects/github/liferay-portal/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/poller.js: Identifier 'data' has already been declared (208:10)
     [exec] 
     [exec]   206 | 				var requestStr = JSON.stringify([_metaData].concat(data));
     [exec]   207 | 
     [exec] > 208 | 				const data = new URLSearchParams();
     [exec]       | 				      ^
     [exec]   209 | 				data.append('pollerRequest', requestStr);
     [exec]   210 | 
     [exec]   211 | 				Liferay.Util.fetch(_getSendUrl(), {
     [exec]     at Parser.raise (/opt/dev/projects/github/liferay-portal/modules/node_modules/@babel/parser/lib/index.js:6325:17)
     [exec]     at ScopeHandler.checkRedeclarationInScope (/opt/dev/projects/github/l
```

@jpince @jbalsas fyi

Please resend.

**Comment by julien** [comment]
@brianchandotcom thanks, I will resend.

**Pull request closed without merging**
