### PR TITLE
LPS-92099 Fix other paths affected by tab markup

### PR DESCRIPTION
**Pull request by jbalsas**
Hey Brian!

This is the last (I think) general UI change we'll be doing for this release. After this, only bug fixes.

Tests have been updated by @john-co. 

/cc @jpince

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a1d40a7f9f...fc866e6209

**Comment by brianchandotcom** [comment]
@jbalsas you need to fix this in master-private, I did a "git grep \"tabs nav-tabs-default\"" and I found a few use cases. Please send a follow up pull @jbalsas

**Comment by jbalsas** [comment]
on it @brianchandotcom!

**Comment by jbalsas** [comment]
See https://github.com/brianchandotcom/liferay-portal-ee/pull/23684#issuecomment-476851900

**Comment by jbalsas** [comment]
Hey @john-co, looks like some poshi locator might need some additional fixing?

**Pull request closed without merging**
