### PR TITLE
LPS-57049 Controller classes extraction to bundle

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
These test failures seem to be unrelated from the pull's changes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a9ef367626...3b6874e183

**Comment by brianchandotcom** [comment]
@matethurzo I merged this in.

Can you replace all of Dummy*, Bridge* in exportimport with ProxyFactory.newDummyInstance and newServiceTrackedInstance. It'll save a lot of code.

Thx.

**Pull request closed without merging**
