### PR TITLE
LPS-74879 Rename

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:stop https://loop.liferay.com/home/-/loop/feed/7636012

**Comment by pyoo47** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/83de2f28ff...8ffe6e62b1

**Pull request closed without merging**
