### PR TITLE
LPS-166565: Add mappings for text embeddings to avoid need to do full re-index

### PR DESCRIPTION
**Pull request by peerkar**
Follow up for https://github.com/brianchandotcom/liferay-portal/pull/129282#issuecomment-1405033914

### CODE REVIEW

**Comment by peerkar** [comment]
ci:reopen

**Comment by joshchong** [comment]
ci:test:search

**Comment by joshchong** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.

**Comment by brianchandotcom** [comment]
@peerkar see changes in my origin.

I think you should rename EmbeddingFieldCreationPortalInstanceLifecycleListener

It doesn't match text-embedding-dynamic-templates.json and it doesn't match your other recent changes.

Please send a follow up PR? Thx.

**Comment by peerkar** [comment]
Follow up: https://github.com/brianchandotcom/liferay-portal/pull/129336

**Pull request closed without merging**
