### PR TITLE
LRQA-62596 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRQA-62596

This is for master and 7.3.x. Thanks!

@austinchiang

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure task is not related to changes in PR.
See https://github.com/Tim-Cao/liferay-portal/pull/487
✔️ ci:test:stable - 14 out of 14 jobs passed
❌ ci:test:relevant - 73 out of 75 jobs passed in 1 hour 34 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/23eb8f71a4...62935cd354

**Comment by brianchandotcom** [comment]
@Tim-Cao I backported to 7.3.x

**Pull request closed without merging**
