### PR TITLE
LPS-76948 GroupServiceSettingsLocator will also get scoped configurations

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-76948](https://issues.liferay.com/browse/LPS-76948).<br><br>Hey Brian, this is a resend per your request here: https://github.com/brianchandotcom/liferay-portal/pull/54660#issuecomment-359998862.  I renamed the method to reflect the return value, and also moved a few variables to the base case, making them static where I could.  Let me know if you have any questions.<br><br>/cc @pei-jung, @JorgeFerrer, @stian-sigvartsen

### CODE REVIEW

**Comment by drewbrokke** [comment]
@jpince are these real failures?  They don't look related to me...

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/132da6bab6...962bad18cf

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0e091c8ed3...0b747f1836

**Comment by jpince** [comment]
@drewbrokke sorry it took a while to get back to you. Yes, those were unrelated. We've been having issues with Sybase reliability, and the other is a fluke that I haven't seen before.

**Comment by drewbrokke** [comment]
@jpince no worries, thanks for the update!

**Pull request closed without merging**
