### PR TITLE
LPS-169193 Adapt validation logic from _getFileEntry

### PR DESCRIPTION
**Pull request by WYZ-Issac**
Forwarded directly from https://github.com/liferay-lima/liferay-portal/pull/3766 since after a few retries we confirmed this pull is not related to any of the failing tests.

### CODE REVIEW

**Comment by WYZ-Issac** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7c08b8d1b0...038881872b

**Comment by brianchandotcom** [comment]
@WYZ-Issac integration test please.

**Comment by brianchandotcom** [comment]
@balazssk @WYZ-Issac I notified @balazssk via Slack to add an integration test. Thx.

**Pull request closed without merging**
