### PR TITLE
LPS-63703 Avoids having two forms with the same name on the same page

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6950f65953...a4a515ac94

**Comment by brianchiu** [comment]
@sharonchoi
This one is a fluke (since the other message boards tests passed). Can you investigate? It didn't successfully type into the "subject" field. So test might be going too fast.

**Comment by brianchiu** [comment]
ci:retest

**Comment by sharonchoi** [comment]
@brianchiu ok will do.

**Comment by sharonchoi** [comment]
Resent here:
https://github.com/brianchandotcom/liferay-portal/pull/36785

@brianchiu

**Pull request closed without merging**
