### PR TITLE
LPS-63908 Only expire versions that have both an expiration date and are older than the version which is expiring

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3bef72d8d1...216a1d4b08

**Comment by brianchandotcom** [comment]
@epgarcia fyi 216a1d4b08fc2354557f51d3ddf7a447a5f08fde

**Comment by xbrianlee** [comment]
Investigating the search functional test failure in [this ticket](https://issues.liferay.com/browse/LRQA-23023). The failure is most likely due to the test running too quickly.

**Comment by epgarcia** [comment]
@ZoltanTakacs

**Comment by ZoltanTakacs** [comment]
It's been merged to 7.0.x. 
Thank you!

**Pull request closed without merging**
