### PR TITLE
LPS-159649

### PR DESCRIPTION
**Pull request by suilin**
https://issues.liferay.com/browse/LPS-159649
https://issues.liferay.com/browse/LPS-161039
https://issues.liferay.com/browse/LPS-162832

### CODE REVIEW

**Comment by suilin** [comment]
ci:reopen

**Comment by suilin** [comment]
Failed to execute ci:forward due to LRCI-3235, so I send the PR directly.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f689b7ce41...1cbd235452

**Comment by brianchandotcom** [comment]
@david-truong @ctang3 see 8af69712ed51dd59e8d6d5c766ff4377b4ca6e08 b73d3aea7068b0995858bd8f235fd96311fa88b2 a036194cd55b115e8e70dbefef513115faa4ea27 0fcd35a6b02179199487602935412e47f52aa7bf and 861b8efb02295af44e50dd58d4d6fa1b3f980986

**Pull request closed without merging**
