### PR TITLE
WCM-626

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
Re-sent at https://github.com/brianchandotcom/liferay-portal/pull/40468.

**Comment by gamerson** [comment]
hey @Ithildir can you resend?  Peter says that WCM has been added to whitelist

**Comment by Ithildir** [comment]
I already did it: https://github.com/brianchandotcom/liferay-portal/pull/40470 :blush:

**Comment by gamerson** [comment]
Great!

On Fri, Jun 3, 2016 at 6:37 PM, Andrea Di Giorgi <notifications@github.com>
wrote:

> I already did it: #40470
> <https://github.com/brianchandotcom/liferay-portal/pull/40470> 😊
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/40467#issuecomment-223719141>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAkVFcomFwVUe2LQDSSym4r4_7K8Ic1dks5qILq_gaJpZM4ItuC5>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Pull request closed without merging**
