### PR TITLE
LPS-92876 Add soy context to the list of soy context

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
Just started reviewing :)

**Comment by sandrodw3** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchandotcom** [comment]
My bad @pavel-savinov !!! thank you

**Pull request closed without merging**
