### PR TITLE
LPS-86357 UserGroupServiceTest#testGetUserGroupsLikeName will fail if there are leftover UserGroups from another test case

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-86357](https://issues.liferay.com/browse/LPS-86357).<br><br>@jpince once this is backported it should fix the failures on 7.0.x<br><br>/cc @pei-jung @stsquared99 @alee8888

### CODE REVIEW

**Comment by drewbrokke** [comment]
@brianchandotcom see ci relevant test results here: https://github.com/drewbrokke/liferay-portal/pull/625#issuecomment-429169080

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by drewbrokke** [comment]
@jpince I believe that the failures are unrelated.  Can you confirm?

**Comment by jpince** [comment]
@drewbrokke POSHI failures are unrelated. Integration test failure seems unrelated, but I really can't be sure, as I don't see it failing this way anywhere else.

**Comment by drewbrokke** [comment]
I guess we can always try again to be sure :)

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@drewbrokke looks good. modules-int passed, and the unresolved requirements failures are in upstream.

**Comment by brianchandotcom** [comment]
@drewbrokke Org and Group have the same tests... to have UserGroup deviate like this isn't good.

Let's find a better way to consistently do this and we can have other tests follow our pattern. Let's talk on Monday for this. Not merging..

**Comment by drewbrokke** [comment]
@brianchandotcom the reason we don't do that with Org and Group is because we create a unique parent for each of them so it's not necessary to create a new company to scope them.  UserGroup doesn't have the same kind of hierarchy so a company is the best we can do.

**Comment by jpince** [comment]
@drewbrokke were you able to follow up on this?

**Comment by drewbrokke** [comment]
@jpince I've sent an email to Shuyang asking for help implementing these solutions.  We'll leave the test ignored for now until he's able to work on it.

**Pull request closed without merging**
