### PR TITLE
LPS-78506 Fix jsp compilation

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @boton @julien

**Comment by brianchandotcom** [comment]
@shuyangzhou see flaky MultiVMPool / lpkgcontroller test..

**Comment by shuyangzhou** [comment]
@mtambara please take a look.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b1d4e9656f...0baaf0a3d4

**Comment by brianchandotcom** [comment]
@sergiogonzalez @boton see  8e37c4220d4b27cddb51769777dcc76b50a00247 

thx

**Comment by brianchandotcom** [comment]
@sergiogonzalez If this is a fix for 7.1.x, please send a backport to support for 7.1.x (like our normal support workflow). I'm no longer auto backporting pulls like this.

@jhendley @liferay @zsoltbalogh FYI.

Merged into master only.

**Pull request closed without merging**
