### PR TITLE
LRQA-43608 Update Liferay Faces git commit references update

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-43608

### Related
* 7.0.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/21881
* 7.1.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/21882

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@stiemannkj1 @kevin-yen @stiemannkj1 see my changes in d9dbdaa183ade9b6030309af9ac79b524ab697d0 and 784b8bbf2b71e8337c09fe200b300127c3e0c4ce

**Comment by stiemannkj1** [comment]
@brianchandotcom, seems like this reordering change will break things: https://github.com/brianchandotcom/liferay-portal/commit/784b8bbf2b71e8337c09fe200b300127c3e0c4ce

From the way it's reordered it looks like the `<xmltask>` will attempt to replace the text of two different nodes with the value two properties:

```
						<xmltask
							dest="${liferay.faces.alloy.dir}/demo/alloy-showcase-webapp/pom.xml"
							source="${liferay.faces.alloy.dir}/demo/alloy-showcase-webapp/pom.xml"
						>
							<replace
								path="//*[local-name()='artifactId'][text()='com.liferay.faces.test.selenium']/../*[local-name()='version']/text()"
								withText="${liferay.faces.test.selenium.version}"
							/>
						</xmltask>
  						<xmltask dest="${liferay.faces.alloy.dir}/pom.xml" source="${liferay.faces.alloy.dir}/pom.xml">
 							<replace
 								path="//*[local-name()='liferay.faces.showcase.version']/text()"
 								withText="${liferay.faces.showcase.version}"
 							/>
 						</xmltask>
```

But the value of those two properties is not obtained until after the text replacement happens:

```
 						<xmltask source="${liferay.faces.showcase.dir}/jsf-showcase-webapp/pom.xml">
 							<copy
 								path="//*[local-name()='artifactId'][text()='com.liferay.faces.test.selenium']/../*[local-name()='version']/text()"
 								property="liferay.faces.test.selenium.version"
							/>
						</xmltask>
 						<xmltask
							dest="${liferay.faces.alloy.dir}/demo/alloy-showcase-webapp/pom.xml"
							source="${liferay.faces.alloy.dir}/demo/alloy-showcase-webapp/pom.xml"
						>
							<replace
								path="//*[local-name()='artifactId'][text()='com.liferay.faces.test.selenium']/../*[local-name()='version']/text()"
								withText="${liferay.faces.test.selenium.version}"
						<xmltask source="${liferay.faces.showcase.dir}/pom.xml">
							<copy
								path="/*[local-name()='project']/*[local-name()='version']/text()"
								property="liferay.faces.showcase.version"
							/>
						</xmltask>
```

So it looks like the text will be replaced with nothing which will cause the JSF tests to fail to compile. Can we avoid sorting these `<xmltasks>`? Or is there another better way to handle getting and replacing values in different xml files?

**Comment by stiemannkj1** [comment]
ci:stop

**Comment by stiemannkj1** [comment]
ci:test:jsf

**Pull request closed without merging**
