### PR TITLE
LPS-101973 Fail to save user info in Profile portlet

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-101973](https://issues.liferay.com/browse/LPS-101973).<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow

### CODE REVIEW

**Comment by drewbrokke** [comment]
cc @jbalsas

**Comment by patriciajeanperez** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@patriciajeanperez is there a reason you're running relevant again? It's already running here... https://test-1-3.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5983/jenkins-report.html

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/179f3cf035...e647c00074

**Pull request closed without merging**
