### PR TITLE
Revert "LPS-94229 Reads bodyCssClass from the queryString so portlets can send classes ahead of time"

### PR DESCRIPTION
**Pull request by brianchiu**
@jbalsas @brianchandotcom
[LPS-94229](https://issues.liferay.com/browse/LPS-94229) causes [LPS-94285](https://issues.liferay.com/browse/LPS-94285) (where many buttons are broken). Originally it also caused [LPS-94278](https://issues.liferay.com/browse/LPS-94278) but it seems LPS-94278 is fixed.

Original pull: https://github.com/brianchandotcom/liferay-portal/pull/71783

cc @ealonso

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7a853cbf48...a88df8618d

**Comment by brianchandotcom** [comment]
@brianchiu reverted... can you update the LPS tickets? thx.

@jbalsas fyi

**Comment by brianchiu** [comment]
@brianchandotcom Will do

**Comment by joshchong** [comment]
ci:test:bundle

**Pull request closed without merging**
