### PR TITLE
LPS-85701 SF

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c6dd7ccf73...a08e92e2fd

**Comment by brianchandotcom** [comment]
@pavel-savinov @ealonso minor change in a08e92e2fd03f3945ba3d40dde660e0f3b4b53d0

**Pull request closed without merging**
