### PR TITLE
LPS-65153 Redeploy of com.liferay.portal.search.elasticsearch makes Search unusable

### PR DESCRIPTION
**Pull request by arboliveira**
Authors: @arturbr @arboliveira
Reviewer: @arboliveira

### CODE REVIEW

**Comment by pyoo47** [comment]
Previous test failed due to a bug in CI. The bug has been fixed. ci:retest

**Comment by arboliveira** [comment]
Test failures seem unrelated.

**Comment by arboliveira** [comment]
Rebased on latest master. ci:retest

**Comment by arboliveira** [comment]
Rebased on latest master. I believe "FacetedSearcherTest.testSearchByKeywordsIgnoresInactiveSites" is a flaky test - if it's shown to be, I'll file a separate ticket to un-flake it.

ci:retest

**Pull request closed without merging**
