### PR TITLE
Lps 97328

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/77c449e544...d322af5cb1

**Comment by brianchandotcom** [comment]
@dantewang renamed to d322af5cb136227cae880207f923bbdd93d3a8bd

I also updated some keys in 6afcf83d3e98bd3691041f0db87cb2d6590a8488

**Comment by brianchandotcom** [comment]
@shuyangzhou I backported this to 7.1.x because they were all on file install 3.6.*

Can you verify my backport to 7.1.x (just this commit is a bit of a stretch 2e7127640bcae710c5b0b67295fdabbc0252ff56) because I bumped up several patch versions.. but I assume those should be safe.

**Comment by dantewang** [comment]
@brianchandotcom Got it, thanks!

**Comment by dantewang** [comment]
@brianchandotcom Hi Brian, could you generate language for osgi-felix-lang? I don't have access to online translation service api. Thanks!

**Pull request closed without merging**
