### PR TITLE
master-bc-1310

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LRQA-23893

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:stop

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7c5625e168...fdc4f01d64

**Comment by pyoo47** [comment]
@brianchandotcom Hashi and Leslie already made a change to fix this issue. The failure that you seeing above is the github message for the first pull request test that Hashi had stopped (which is why the top-level build states that it was aborted. There should be another GitHub message posted for the retest that Hashi initiated after he committed the fix.

**Pull request closed without merging**
