### PR TITLE
LPS-102367 Fix packageRunBuild for 7.2.x

### PR DESCRIPTION
**Pull request by petershin**
CI tests passed here: https://github.com/petershin/liferay-portal/pull/747#issuecomment-542791166

@jbalsas - the `jar` problem will still exist in `7.1.x` and `7.0.x` for projects that use an older version of `liferay-npm-scripts`.  I can look into providing the steps to reproduce the issue if its helpful

@wincent @john-co

### CODE REVIEW

**Comment by jbalsas** [comment]
> @jbalsas - the jar problem will still exist in 7.1.x and 7.0.x for projects that use an older version of liferay-npm-scripts. I can look into providing the steps to reproduce the issue if its helpful

We can look at updating `7.1.x` next. `7.0.x` is not on `liferay-npm-scripts`, so if we need to fix something there, we'll have to work with what's in there.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8d2aa319b1...f1b4b4f14c

**Comment by brianchandotcom** [comment]
@jbalsas @wincent hey guys, we only have one Gradle SDK, and that's shared across 7.0.x, 7.1.x, and 7.2.x, and master.

All of those are now pointing to the new SDK. I need you guys to send me pulls to 7.2.x and 7.1.x and 7.0.x asap or else it's going to hurt maintenance of the older branches.

@petershin fyi because this pull includes both Ant and JS changes.

**Comment by petershin** [comment]
@jbalsas - I'll send you a pull for `7.2.x`

**Comment by petershin** [comment]
https://github.com/jbalsas/liferay-portal-ee/pull/72
https://github.com/jbalsas/liferay-portal-ee/pull/73

**Pull request closed without merging**
