### PR TITLE
LPS-57354 The upload handlers shouldn't be specific to item selector because they are also used from other places (like the alloy editor when dragging and dropping a file). Therefore, I'd like to remove that dependency and convert them in something more agnostic.

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
cc/ @sergiogonzalez @robertoDiaz

**Comment by brianchandotcom** [comment]
@robertoDiaz can you resend? BlogImage*Exception doesn't match any of the exceptions in that dir.

If it's only used blogs-web, can we keep it there near BaseBlogsImageSelectorUploadHandler

Also, at the very least, it should be Blogs* and not Blog*

Thx

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Done here : https://github.com/brianchandotcom/liferay-portal/pull/28795

**Pull request closed without merging**
