### PR TITLE
LPS-164067 Display the Active and Inactive Labels in the Control Menu

### PR DESCRIPTION
**Pull request by Mikellorza**
Motivation
=======
As a marketer, I want to see the Active / Inactive labels while in view mode, so that I can easily understand the status of an experience I am currently viewing. 
[Link to story or ticket](https://issues.liferay.com/browse/LPS-154188)

Proposed Solution
========
Added Active / Inactive labels to the control menu in view mode.

image

Steps to Verify:
----------------
1-Go to People / Segment management.
2-Add some segments.
3-Go to a content page.
4-Add some experiences related to the same segment.
5-Order created experiences and you will see the labels.

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@Mikellorza I need CI or some form of documentation showing that manual QA approved this.

**Comment by Mikellorza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e5f08e9b0c...bd7aaadad6

**Comment by brianchandotcom** [comment]
My bad @Mikellorza I was looking for a comment from you and missed the GH reference.

**Pull request closed without merging**
