### PR TITLE
LPS-133200

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
Unrelated failures only: https://github.com/hhuijser/liferay-portal/pull/5682

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4a796f8b46...1ac1827468

**Comment by brianchandotcom** [comment]
Thx @hhuijser !

**Pull request closed without merging**
