### PR TITLE
LPS-75983 More SF

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test

**Comment by matethurzo** [comment]
unrelated ci error, sybase transaction log is almost full, due to that the build for sybase has been aborted

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0881a1b9a2...c0f35092b4

**Comment by brianchandotcom** [comment]
@matethurzo please see my changes in upstream. Thx.

**Pull request closed without merging**
