### PR TITLE
LPS-68568 - <aui:icon /> taglib outputs label HTML markup even when n…

### PR DESCRIPTION
**Pull request by pat270**
…othing is passed

https://issues.liferay.com/browse/LPS-68568

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest @pyoo47 what happened here?

**Comment by pyoo47** [comment]
@brianchandotcom This is a local-git failure that sometimes happens when there's heavy load. It basically comes from too many sockets have been opened too quickly and there hasn't been enough time that has passed for the used sockets to reset and become available again.

```
     [exec] + git push -f git@cloud-10-0-0-11:liferay/liferay-plugins.git master
     [exec] ssh: connect to host cloud-10-0-0-11 port 22: No buffer space available
     [exec] fatal: Could not read from remote repository.
```

**Comment by brianchiu** [comment]
All poshi failures are due to firefox connection issues.

QA Eng is looking into this. See: https://issues.liferay.com/browse/LRQA-28169

cc @michaelhashimoto @pyoo47

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/61c8d08b13...8095fc70fa

**Pull request closed without merging**
