### PR TITLE
master-qa-24836

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LRQA-25211
https://issues.liferay.com/browse/LRQA-24836

@brianchandotcom 
This switches our upgrade automation tests to use the new upgrade tool that Dave Truong created. 

However, in order for it to work, it needs to run on JDK8. @michaelhashimoto recommended to just move all of the tomcat mysql functional batches to use JDK8. I originally wanted to just move the tomcat mysql functional batches to use JDK8 first, but the old upgrade tool had issues with JDK8. So I had to send both of these at the same time in the same pull.

### CODE REVIEW

**Comment by brianchiu** [comment]
None of the failures are poshi related. But the modules integration failures might be flaky?

They passed here when I sent a pull to myself (same commits) for testing: https://github.com/brianchiu/liferay-portal/pull/1369

**Comment by brianchandotcom** [comment]
Thx @brianchiu for the comments/info

**Comment by brianchandotcom** [comment]
@brianchiu can you send a follow up pull and sort:

dir=${app.server.dir}
global.lib.dir=modules/com/liferay/portal/main
portal.dir=standalone/deployments/ROOT.war
extra.lib.dirs=modules/system/layers/base/javax/mail,modules/system/layers/base/javax/persistence,modules/

extra should go before global. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/65974c9509...2c008e48da

**Comment by vicnate5** [comment]
@brianchandotcom @brianchiu The reason for the properties being out of order is because it matches the order generated by the upgrade client.

**Pull request closed without merging**
