### PR TITLE
LPS-94287 change-tracking security audit

### PR DESCRIPTION
**Pull request by topolik**
Hi Brian,

https://issues.liferay.com/browse/LPS-94287

Thank you.

/cc @matethurzo

### CODE REVIEW

**Comment by matethurzo** [comment]
@topolik if i understand correctly this will only allow the omni admin to access the rest services? if that's the case it'll break the entire functionality.

**Comment by topolik** [comment]
@matethurzo Yup. You don't use permissions so any user can read & modify change lists. It's used only from admin portlets, right?

**Comment by matethurzo** [comment]
@topolik no, not only from admin portlets. Although I understand the motive, we can create a custom role for this and check for that. Or can you explain the reasons in more detail? @danielkocsis

**Comment by topolik** [comment]
So far you don't have any permissions around change lists. You have portlets and REST API. 
1, any power user can add change lists portlet to pages - fixed in  432e592
2, any user can call REST api and access/manipulate with changes lists - fixed in 9539eff

I believe it wasn't intended behavior so I made it safe. I'm not sure if we are going to release change lists but right now they are totally vulnerable.

I don't know your requirements guys but this cannot go into production :(

**Comment by topolik** [comment]
Looking at portlets the REST api is used only from admin portlets.

The site/user related portlets have empty view.jsp with `This is only a placeholder for what's later be added to the my change lists screen.`

So I guess you are going to implement that later anyway so you can improve the REST api together and for example check role or define permissions?

**Comment by topolik** [comment]
ci:test:testsuitehere:478cafc69595d43ccda9e18dd9bc8d2eef1574e0

**Comment by matethurzo** [comment]
@topolik if we create a custom role and restrict to that, that could work from your perspective?

**Comment by topolik** [comment]
@matethurzo Whatever suits your needs and won't leave it open to anybody. 

I leave up to you the decision what to do with this PR. Feel free to close it but make sure you can fix it before release please.

**Comment by yichenroy** [comment]
ci:stop
Invalid test suite

**Comment by topolik** [comment]
ci:reopen

**Comment by xbrianlee** [comment]
ci:test:relevant:478cafc69595d43ccda9e18dd9bc8d2eef1574e0

**Comment by brianchandotcom** [comment]
@topolik please resend since you and @matethurzo had a good discussion. Thx.

**Comment by topolik** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/73555

**Pull request closed without merging**
