### PR TITLE
LPS-165257 Add site permission

### PR DESCRIPTION
**Pull request by seltong**

### CODE REVIEW

**Comment by seltong** [comment]
ci:reopen

**Comment by seltong** [comment]
The ci relevant failures [here](https://github.com/liferay-objects/liferay-portal/pull/1257) are not related

**Comment by brianchandotcom** [comment]
@seltong can you add an integration test for this? Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b2159cfe53...a903834b42

**Comment by seltong** [comment]
Sure, I will add as soon as possible. Thx

**Pull request closed without merging**
