### PR TITLE
LPS-103516 Register ContextEntityModel regardless of the presence of contributors

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:lpkg

**Comment by jpince** [comment]
`lpkg-base-jdk8` and `lpkg-controller-jdk8` failures are unrelated, waiting to see if this passes `lpkg-release` and `lpkg-independence` [LPS-103411](https://issues.liferay.com/browse/LPS-103411)

**Comment by jpince** [comment]
this pull might also (or only) be needed to resolve all lpkg batch issues: https://github.com/shuyangzhou/liferay-portal/pull/8433

**Comment by jpince** [comment]
No segments errors :) lpkg failures are related to https://issues.liferay.com/browse/LPS-103477 and https://issues.liferay.com/browse/LPS-103476

**Comment by epgarcia** [comment]
Thanks @jpince ! @brianchandotcom if you could please review it, this will fix a blocker issue. Thx

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0d7f9c1df0...636678a91a

**Pull request closed without merging**
