### PR TITLE
LPS-100497 AB Test - Add delete menu option

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
@brianchandotcom @jpince I think the test error is unrelated to our changes. Could you please confirm? Thanks

**Comment by jpince** [comment]
@epgarcia yes, it's unrelated. The fix is here https://github.com/brianchandotcom/liferay-portal/pull/77746

**Comment by epgarcia** [comment]
@jpince Thanks!!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/aaacce92db...21b0c0ec45

**Pull request closed without merging**
