### PR TITLE
LRQA-44701 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-44701

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@austinchiang merged.. and I merged the other 2 pulls before this one.

Also, why is this master only? Looks like it's just reorganizing right? If they're already the same, you should try to keep them the same and only branch if you have to.

Thx.

**Comment by brianchandotcom** [comment]
@austinchiang basically, in general, deviate where you have to, and where you can keep things in sync, do so, because there is always a cost to divergence (and it's generally higher than keeping things in sync).

**Comment by brianchandotcom** [comment]
@austinchiang therefore, if you can (and the scenario fits), send me a backport to 7.1.x. Thx.

**Comment by austinchiang** [comment]
Thanks, yeah after double checking the scenario fits. Sent here: https://github.com/brianchandotcom/liferay-portal-ee/pull/22360

**Pull request closed without merging**
