### PR TITLE
LPS-62300

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@brianchandotcom I think this only on some functional servers?  This pull passed last night (without the pull renaming web context to *-web).

**Comment by brianchandotcom** [comment]
You can ignore that error.. merging this. It's a Gradle cache issue, I"ll fix it on my end.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/dcd0536355...26a8a48a6c

**Comment by brianchandotcom** [comment]
@mhan810 Sometimes Gradle misses things. The easiest way is to delete all of ".gradle" then run "git reset --hard HEAD" and then run "ant setup-sdk", then run "gradlew classes" in one of the modules and it'll download it again.

See 26a8a48a6c6a07a30a253083a03e7e2c4739c6cd

**Pull request closed without merging**
