### PR TITLE
Revert "LPS-91117 staging-bar-web This code wil never do anything"

### PR DESCRIPTION
**Pull request by matethurzo**
@markocikos reverting because the changes braking the staging configuration screen and causing a release blocker.

cc @jbalsas @jpince

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:relevant

**Comment by reizero00** [comment]
ci:test:bundle:norebase

**Comment by brianchiu** [comment]
ci:test:bundle

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
