### PR TITLE
LPS-202912 - Backend changes for new version section on Filters - Web Content

### PR DESCRIPTION
**Pull request by ruben-pulido**
Solved rebase conflict with Brian's remote in https://github.com/brianchandotcom/liferay-portal/pull/145334

//cc @ealonso

https://liferay.atlassian.net/browse/LPS-202912 - Backend changes for new version section on Filters - Web Content

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:reopen

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/26ada7c5b5...b0e7c80960

**Comment by brianchandotcom** [comment]
@ruben-pulido can you sort this somehow

```
		if (FeatureFlagManagerUtil.isEnabled("LPS-196768") &&
			!isTypeVersions() && !isSearch() && !isNavigationMine() &&
			!isNavigationRecent() && (getDDMStructureId() <= 0) &&
```

Thx

**Pull request closed without merging**
