### PR TITLE
COMMERCE-1278 & COMMERCE-1305 | master

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
[Commerce API Scrum board](https://issues.liferay.com/secure/RapidBoard.jspa?rapidView=3928)
----
Tickets:
- https://issues.liferay.com/browse/COMMERCE-1278
- https://issues.liferay.com/browse/COMMERCE-1305

/cc @marco-leo, @igorbeslic, @matijapetanjek

### CODE REVIEW

**Comment by ZoltanTakacs** [comment]
ci:reopen

**Comment by ZoltanTakacs** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@petershin @pyoo47 see weird CI error.

**Comment by brianchandotcom** [comment]
@ZoltanTakacs can you rename BaseDataStore

In general, Base* are abstract classes for us. Thx.

**Comment by ZoltanTakacs** [comment]
Resent on https://github.com/brianchandotcom/liferay-portal/pull/71723

**Pull request closed without merging**
