### PR TITLE
LPS-88848 Fix compile error on test

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f8baf6fd2b...de7958a571

**Comment by brianchandotcom** [comment]
@matethurzo @giros please see my renames and other changes in upstream. Thx.

**Comment by jpince** [comment]
@brianchiu @kyle-miho see Journal backend test failures. Please escalate to Mate and/or your product team if these are real failures.

**Comment by jpince** [comment]
ci:test:change-tracking testing command again, I see it in 
https://github.com/liferay/liferay-portal/blob/master/test.properties#L1385, and worked in the initial PR https://github.com/brianchandotcom/liferay-portal/pull/66015#issuecomment-448253587

**Pull request closed without merging**
