### PR TITLE
LPS-64092 Add hashCode too, so it is consistent with PMD

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by anthony-chu** [comment]
@pyoo47 PortalSmoke#Smoke completes successfully. Do you know why this posted as a failure?

**Comment by vicnate5** [comment]
@anthony-chu did you check the server log? Portal Smoke will register a failure if there is a console error.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0457980fbe...092be9433b

**Comment by brianchiu** [comment]
@brianchandotcom @anthony-chu Can you guys look into this? This looks like a real failure.

And @vicnate5 is correct. Even if the portal smoke test steps themselves pass, it will register as a failure if there is a console error.

And I see the following console error in the log during startup.
```
     [exec] 17:38:33,747 INFO  [localhost-startStop-1][ServiceComponentLocalServiceImpl:286] Running BackgroundTask SQL scripts
     [exec] 17:38:34,140 INFO  [elasticsearch[Firelord][clusterService#updateTask][T#1]][metadata:317] [Firelord] [liferay-0] update_mapping [LiferayDocumentType]
     [exec] 17:38:34,178 INFO  [elasticsearch[Firelord][clusterService#updateTask][T#1]][metadata:317] [Firelord] [liferay-0] update_mapping [LiferayDocumentType]
     [exec] 17:38:37,585 ERROR [liferay/background_task-2][ParallelDestination:55] Unable to process message {destinationName=liferay/background_task, response=null, responseDestinationName=null, responseId=null, payload=null, values={defaultLocale=en_US, groupId=0, companyId=20202, backgroundTaskId=28127}}
     [exec] com.liferay.portal.kernel.messaging.MessageListenerException: com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: {mvccVersion=0, backgroundTaskId=28127, groupId=0, companyId=0, userId=0, userName=, createDate=Thu Mar 17 17:38:36 GMT 2016, modifiedDate=Thu Mar 17 17:38:37 GMT 2016, name=reindexOnActivate#com.liferay.exportimport.kernel.model.ExportImportConfiguration, servletContextNames=, taskExecutorClassName=com.liferay.portal.search.internal.background.task.ReindexSingleIndexerBackgroundTaskExecutor, taskContextMap={deleteOnSuccess=true, className=com.liferay.exportimport.kernel.model.ExportImportConfiguration, companyIds=[J@1bb05e1, threadLocalValues={defaultLocale=en_US, clusterInvoke=true, groupId=0, principalName=null, siteDefaultLocale=null, companyId=20202, themeDisplayLocale=null}}, completed=true, completionDate=Thu Mar 17 17:38:37 GMT 2016, status=3, statusMessage=} is stale in comparison to {mvccVersion=1, backgroundTaskId=28127, groupId=0, companyId=0, userId=0, userName=, createDate=2016-03-17 17:38:36.98, modifiedDate=2016-03-17 17:38:37.307, name=reindexOnActivate#com.liferay.exportimport.kernel.model.ExportImportConfiguration, servletContextNames=, taskExecutorClassName=com.liferay.portal.search.internal.background.task.ReindexSingleIndexerBackgroundTaskExecutor, taskContextMap={deleteOnSuccess=true, className=com.liferay.exportimport.kernel.model.ExportImportConfiguration, companyIds=[Ljava.lang.Integer;@1f7debb, threadLocalValues={defaultLocale=en_US, groupId=0, clusterInvoke=true, principalName=null, siteDefaultLocale=null, companyId=20202, themeDisplayLocale=null}}, completed=false, completionDate=null, status=1, statusMessage=}
     [exec] 	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:32)
     [exec] 	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:74)
     [exec] 	at com.liferay.portal.kernel.messaging.ParallelDestination$1.run(ParallelDestination.java:52)
     [exec] 	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask._runTask(ThreadPoolExecutor.java:756)
     [exec] 	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask.run(ThreadPoolExecutor.java:667)
     [exec] 	at java.lang.Thread.run(Thread.java:745)
     [exec] Caused by: com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: {mvccVersion=0, backgroundTaskId=28127, groupId=0, companyId=0, userId=0, userName=, createDate=Thu Mar 17 17:38:36 GMT 2016, modifiedDate=Thu Mar 17 17:38:37 GMT 2016, name=reindexOnActivate#com.liferay.exportimport.kernel.model.ExportImportConfiguration, servletContextNames=, taskExecutorClassName=com.liferay.portal.search.internal.background.task.ReindexSingleIndexerBackgroundTaskExecutor, taskContextMap={deleteOnSuccess=true, className=com.liferay.exportimport.kernel.model.ExportImportConfiguration, companyIds=[J@1bb05e1, threadLocalValues={defaultLocale=en_US, clusterInvoke=true, groupId=0, principalName=null, siteDefaultLocale=null, companyId=20202, themeDisplayLocale=null}}, completed=true, completionDate=Thu Mar 17 17:38:37 GMT 2016, status=3, statusMessage=} is stale in comparison to {mvccVersion=1, backgroundTaskId=28127, groupId=0, companyId=0, userId=0, userName=, createDate=2016-03-17 17:38:36.98, modifiedDate=2016-03-17 17:38:37.307, name=reindexOnActivate#com.liferay.exportimport.kernel.model.ExportImportConfiguration, servletContextNames=, taskExecutorClassName=com.liferay.portal.search.internal.background.task.ReindexSingleIndexerBackgroundTaskExecutor, taskContextMap={deleteOnSuccess=true, className=com.liferay.exportimport.kernel.model.ExportImportConfiguration, companyIds=[Ljava.lang.Integer;@1f7debb, threadLocalValues={defaultLocale=en_US, groupId=0, clusterInvoke=true, principalName=null, siteDefaultLocale=null, companyId=20202, themeDisplayLocale=null}}, completed=false, completionDate=null, status=1, statusMessage=}
     [exec] 	at com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl.processException(BasePersistenceImpl.java:264)
     [exec] 	at com.liferay.portal.background.task.service.persistence.impl.BackgroundTaskPersistenceImpl.updateImpl(BackgroundTaskPersistenceImpl.java:8507)
     [exec] 	at com.liferay.portal.background.task.service.persistence.impl.BackgroundTaskPersistenceImpl.updateImpl(BackgroundTaskPersistenceImpl.java:72)
     [exec] 	at com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl.update(BasePersistenceImpl.java:345)
     [exec] 	at com.liferay.portal.background.task.service.impl.BackgroundTaskLocalServiceImpl.amendBackgroundTask(BackgroundTaskLocalServiceImpl.java:199)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:606)
     [exec] 	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:153)
     [exec] 	at com.liferay.portal.spring.transaction.DefaultTransactionExecutor.execute(DefaultTransactionExecutor.java:85)
     [exec] 	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:58)
     [exec] 	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:127)
     [exec] 	at com.liferay.portal.service.ServiceContextAdvice.invoke(ServiceContextAdvice.java:40)
     [exec] 	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:127)
     [exec] 	at com.liferay.portal.spring.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:56)
     [exec] 	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:127)
     [exec] 	at com.liferay.portal.spring.aop.ServiceBeanAopProxy.invoke(ServiceBeanAopProxy.java:173)
     [exec] 	at com.sun.proxy.$Proxy366.amendBackgroundTask(Unknown Source)
     [exec] 	at com.liferay.portal.background.task.internal.BackgroundTaskManagerImpl.amendBackgroundTask(BackgroundTaskManagerImpl.java:137)
     [exec] 	at com.liferay.portal.background.task.internal.messaging.BackgroundTaskMessageListener.doReceive(BackgroundTaskMessageListener.java:173)
     [exec] 	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:26)
     [exec] 	... 5 more
     [exec] Caused by: com.liferay.portal.kernel.dao.orm.ORMException: {mvccVersion=0, backgroundTaskId=28127, groupId=0, companyId=0, userId=0, userName=, createDate=Thu Mar 17 17:38:36 GMT 2016, modifiedDate=Thu Mar 17 17:38:37 GMT 2016, name=reindexOnActivate#com.liferay.exportimport.kernel.model.ExportImportConfiguration, servletContextNames=, taskExecutorClassName=com.liferay.portal.search.internal.background.task.ReindexSingleIndexerBackgroundTaskExecutor, taskContextMap={deleteOnSuccess=true, className=com.liferay.exportimport.kernel.model.ExportImportConfiguration, companyIds=[J@1bb05e1, threadLocalValues={defaultLocale=en_US, clusterInvoke=true, groupId=0, principalName=null, siteDefaultLocale=null, companyId=20202, themeDisplayLocale=null}}, completed=true, completionDate=Thu Mar 17 17:38:37 GMT 2016, status=3, statusMessage=} is stale in comparison to {mvccVersion=1, backgroundTaskId=28127, groupId=0, companyId=0, userId=0, userName=, createDate=2016-03-17 17:38:36.98, modifiedDate=2016-03-17 17:38:37.307, name=reindexOnActivate#com.liferay.exportimport.kernel.model.ExportImportConfiguration, servletContextNames=, taskExecutorClassName=com.liferay.portal.search.internal.background.task.ReindexSingleIndexerBackgroundTaskExecutor, taskContextMap={deleteOnSuccess=true, className=com.liferay.exportimport.kernel.model.ExportImportConfiguration, companyIds=[Ljava.lang.Integer;@1f7debb, threadLocalValues={defaultLocale=en_US, groupId=0, clusterInvoke=true, principalName=null, siteDefaultLocale=null, companyId=20202, themeDisplayLocale=null}}, completed=false, completionDate=null, status=1, statusMessage=}
     [exec] 	at com.liferay.portal.dao.orm.hibernate.ExceptionTranslator.translate(ExceptionTranslator.java:46)
     [exec] 	at com.liferay.portal.dao.orm.hibernate.SessionImpl.merge(SessionImpl.java:245)
     [exec] 	at com.liferay.portal.kernel.dao.orm.ClassLoaderSession.merge(ClassLoaderSession.java:410)
     [exec] 	at com.liferay.portal.background.task.service.persistence.impl.BackgroundTaskPersistenceImpl.updateImpl(BackgroundTaskPersistenceImpl.java:8503)
     [exec] 	... 25 more
     [exec] Caused by: org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect): [com.liferay.portal.background.task.model.impl.BackgroundTaskImpl#28127]
     [exec] 	at org.hibernate.event.def.DefaultMergeEventListener.entityIsDetached(DefaultMergeEventListener.java:485)
     [exec] 	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:255)
     [exec] 	at org.hibernate.event.def.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:84)
     [exec] 	at org.hibernate.impl.SessionImpl.fireMerge(SessionImpl.java:867)
     [exec] 	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:851)
     [exec] 	at org.hibernate.impl.SessionImpl.merge(SessionImpl.java:855)
     [exec] 	at com.liferay.portal.dao.orm.hibernate.SessionImpl.merge(SessionImpl.java:242)
     [exec] 	... 27 more
```

**Pull request closed without merging**
