### PR TITLE
LPS-97619

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sharing

**Comment by brianchandotcom** [comment]
@adolfopa lots of frontend test failures? Merged to master only.

**Comment by 4lejandrito** [comment]
Hi @brianchandotcom,

Those failures can't be possibly caused by these changes. We only changed integration tests code in this pull and those are functional failures. This is safe to backport.

We are investigating why the others failed.

Thanks!

**Comment by Hanlf** [comment]
Hi @4lejandrito,

These frontend test failures are not related to this pull, it is a testfix issue and has been fixed under LRQA-50207, no this issue at head now, thanks!

/cc @brianchandotcom

**Pull request closed without merging**
