### PR TITLE
LPS-68589 Move lang keys to portal since it is used by portal service

### PR DESCRIPTION
**Pull request by robertoDiaz**
To simplify the rebase I've fixup some SF commits from the original PR

### CODE REVIEW

**Comment by robertoDiaz** [comment]
cc/ @sergiogonzalez

**Comment by robertoDiaz** [comment]
Hey @brianchandotcom 

Did you find any problem with this pull? A customer is waiting for this changes in order to fix a bug, so could you to give priority to this??

Thanks in advance!!

**Comment by daledotshan** [comment]
Hey @brianchandotcom 
Do you have a chance to review this pull request? one Japanese customer is waiting for this fix.
Thanks,
Dale

**Comment by zsigmondrab** [comment]
Hi @brianchandotcom ,

we are waiting for this also.

Thank you,
Zsigmond

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6c10b4b5ac...4571b07a3c

**Pull request closed without merging**
