### PR TITLE
Lps 126920

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
@brianchandotcom we need someone to make a frontend change. In system setting UI updates, if the ```Map<String, Object> getOverrideProperties(String pid)``` contains the key, the UI should gray out and put a override note to prevent modification. We can talk about it in today's meet.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6f901f7d38...2fdb469a49

**Comment by brianchandotcom** [comment]
Got it.. bravo @shuyangzhou 

@drewbrokke need your help with the gray out!

@shuyangzhou in ConfigurationInvocationHandler.java, can we change:

```
		_overrideProperties =
			ConfigurationOverridePropertiesUtil.getOverrideProperties(
				clazz.getName());

		_configurationOverrideInstance =
			ConfigurationOverrideInstance.getConfigurationOverrideInstance(
				clazz, typedSettings);
```

to

```
		_configurationOverrideInstance =
			ConfigurationOverrideInstance.getConfigurationOverrideInstance(
				clazz, typedSettings);
		_overrideProperties =
			ConfigurationOverridePropertiesUtil.getOverrideProperties(
				clazz.getName());
```

I sorted it and got rid of the line break. Or does order matter (and hence you added the line break correctly to note that)? Please send a follow up pull if possible.

Please also review my changes in 2fdb469a49941be1f46a430f7a387607e3e79814 thx!

**Comment by shuyangzhou** [comment]
The order does not matter.
See https://github.com/brianchandotcom/liferay-portal/pull/98145

**Pull request closed without merging**
