### PR TITLE
LPS-58825 don't allow users to create control panel layouts

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @ealonso I added support for creating the control panel layout itself ;)

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@juliocamarero thanks for catching the error and resending it. I made some tiny changes in upstream. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f2f7aa24e3...ca7ca58f01

**Pull request closed without merging**
