### PR TITLE
LPS-192969 Add image size warning to ImageSelectorSize

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://liferay.atlassian.net/browse/LPS-192969

@p2kmgcl
cc @sandrodw3

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/13284

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5d54e1f46c...f2b2f5d762

**Comment by brianchandotcom** [comment]
@p2kmgcl see e7ae78f1ac44f59b477c5d37cba7787ed1214fed

**Pull request closed without merging**
