### PR TITLE
LRDOCS-9519 learn resources json files

### PR DESCRIPTION
**Pull request by jhinkey**

### CODE REVIEW

**Comment by jhinkey** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8faa11d92e...5683dbc1c4

**Comment by brianchandotcom** [comment]
@jhinkey see da92fd09aae75e56074f5455eab15713636a416a and 5683dbc1c46d9326a90bdb756b6d26040de86d91

**Comment by jhinkey** [comment]
Sounds good, Brian. I'll capture this in our guidelines. :-)

**Comment by brianchandotcom** [comment]
@jhinkey I added this for backwards compat 7c1b5dfe232e7244ebd93c9d94d9f1761f0aac4b

**Comment by brianchandotcom** [comment]
@jhinkey note that the backwards compat contains the deprecated flag for those keys 7c1b5dfe232e7244ebd93c9d94d9f1761f0aac4b

**Pull request closed without merging**
