### PR TITLE
LPS-117390 Remove this line since the module does not have tests

### PR DESCRIPTION
**Pull request by nikki-pru**
https://issues.liferay.com/browse/LPS-117390 

@brianchandotcom, this unblocks the sync to master. 
@p2kmgcl 
@john-co

Thanks

### CODE REVIEW

**Comment by nikki-pru** [comment]
ci:reopen

**Comment by nikki-pru** [comment]
ci:test:stable

**Comment by nikki-pru** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bcd1f419a4...0ca2f721fd

**Pull request closed without merging**
