### PR TITLE
SYNC-1679

### PR DESCRIPTION
**Pull request by shinnlok**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pyoo47 what happened here?

**Comment by pyoo47** [comment]
@brianchandotcom Looks like some kind of local-git failure. We made some changes recently to the way we call local-git so that corrupt local-git caches are deleted automatically when we encounter failures but it looks like something went wrong in this case and it froze then aborted.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
