### PR TITLE
LPS-98032 Apply JS-in-JSP formatting

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
(@brianchandotcom, SF error is just because I rebased against your origin to be able to resolve existing conflicts)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/630e3e47f6...38de83bde5

**Comment by brianchandotcom** [comment]
@jbalsas very nice. I merged this. I think we should backport since this is just SF. I reviewed the changes and there are no logic changes.

@wincent is there any way we can rewrite the JSP code so that we do not need "special cases"? I really dislike special cases if there is any way of getting around them. Thx.

**Comment by jbalsas** [comment]
I'd expect these not to cleanly cherry-pick already, so we will need to apply them manually, which I think it's also the way to do. We can work on that as soon as the other build changes settle in `7.2.x` liferay's origin

**Comment by wincent** [comment]
> @wincent is there any way we can rewrite the JSP code so that we do not need "special cases"? I really dislike special cases if there is any way of getting around them. Thx.

@brianchandotcom: Sure, I'll send a PR with a rewrite. The two problem files have patterns like this:

```
{
	id: '<portlet:namespace />editAsset',
	portletAjaxable: true,

	<c:choose>
		<c:when test="<%= redirect != null %>">
			redirect: '<%= HtmlUtil.escapeJS(redirect) %>'
		</c:when>
		<c:otherwise>
			refresh: '<%= portletDisplay.getId() %>'
		</c:otherwise>
	</c:choose>
}
```

The problem there is that when the tags are temporarily removed to turn it into JS for formatting, you're left with an invalid object (note the lack of trailing commas):

```
{
	id: '<portlet:namespace />editAsset',
	portletAjaxable: true,
	redirect: '<%= HtmlUtil.escapeJS(redirect) %>'
	refresh: '<%= portletDisplay.getId() %>'
}
```

We can't just put a trailing comma after both properties because IE 11 will crash if the last key-value pair has a comma.

They can be rewritten — with some redundancy — like this:

```
<c:choose>
	<c:when test="<%= redirect != null %>">
		Liferay.fire(
			'closeWindow',
			{
				id: '<portlet:namespace />editAsset',
				portletAjaxable: true,
				redirect: '<%= HtmlUtil.escapeJS(redirect) %>'
			}
		);
	</c:when>
	<c:otherwise>
		Liferay.fire(
			'closeWindow',
			{
				id: '<portlet:namespace />editAsset',
				portletAjaxable: true,
				refresh: '<%= portletDisplay.getId() %>'
			}
		);
	</c:otherwise>
</c:choose>
```

(or some other equivalent variant).

**Pull request closed without merging**
