### PR TITLE
LPS-140641 When building Blueprint, I can select an Asset Category for my element through the UI without collecting its ID manually

### PR DESCRIPTION
**Pull request by joshchong**
https://issues.liferay.com/browse/LPS-140641 When building Blueprint, I can select an Asset Category for my element through the UI without collecting its ID manually

Relies on the existing OOTB element by checking for the input type of "number"/"multiselect" and the presence of `asset_category_id(s)` as the field name, instead of specifying its own category selector input type (as mentioned in https://github.com/BryanEngler/liferay-portal/pull/665). For single selectors, this should be able to start saving the label and value of a category based on information from the autocomplete or the modal. 

Labels have also been updated to look like `Name (ID: 1234)`.

Screen Shot 2022-09-01 at 3 17 25 PM
Screen Shot 2022-09-01 at 3 22 27 PM

Tests passed here: https://github.com/liferay-search/liferay-portal/pull/542#issuecomment-1256632406
The failures are not related

@oliv-yu @thektan

### CODE REVIEW

**Comment by joshchong** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a2f23fbea2...1a52c56cef

**Comment by brianchandotcom** [comment]
@oliv-yu @thektan can you guys change validateRequired so this can be sorted?

```
								validateRequired(
									configValue,
									type,
									typeOptions.required,
									typeOptions.nullable,
									name
```

Thx

**Comment by lipusz** [comment]
Created https://issues.liferay.com/browse/LPS-163949 to track this extra task @oliv-yu

**Pull request closed without merging**
