### PR TITLE
LPS-107201 Revert "LPS-105881 Escapes user content as attribute on top of the JS escaping"

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
@jbalsas @antonio-ortega

**Comment by jbalsas** [comment]
Thanks @4lejandrito!! 

/cc @antonio-ortega, @csierra, @stian-sigvartsen, turns out that double escaping it breaks JS in other parts... we'll need to come up with a different plan for this issue :/

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f2f0ce5385...c977c67c6a

**Comment by topolik** [comment]
@4lejandrito @jbalsas 

For the record, this is the root cause: https://github.com/liferay/liferay-portal/blob/02369ff3dcc3e901fc5e6b17bc2db8807776bd6d/portal-web/docroot/html/taglib/ui/menu_item/page.jsp#L46

**Comment by topolik** [comment]
Please see https://github.com/jbalsas/liferay-portal/pull/2095.

**Pull request closed without merging**
