### PR TITLE
LPS-110601 DEFLAKE AssetPublisherExportImportTest

### PR DESCRIPTION
**Pull request by arboliveira**
(Started the Search test suite 9 hours ago, now running for the past 5 hours, still unfinished. Anyway this should be safe to merge: changed only one single test.)

https://github.com/arboliveira/liferay-portal/pull/814#issuecomment-603087919

----

@brianchandotcom @shuyangzhou I was able to confirm that the root cause in the overwhelming majority of flaky integration tests attributed to Search is actually an antipattern in test dependency initialization code that requires no changes in Search or Elasticsearch at all. This pull request demonstrates how to fix it in AssetPublisherExportImportTest, and I will send further pull requests to fix the other flukes assigned to Search presenting the same antipattern. Applying the best practice eliminated the 80%+ failure rate completely, across 25+ executions observed overnight in our controlled Search CI Server, using a branch cut last Friday March 20, non rebased since then, and no other changes applied. Please compare:

(Prior to fix)

https://search-ci.liferay.com/job/integration-flaky/116/testReport/junit/com.liferay.asset.publisher.lar.test/history/?start=25

(With fix applied)

https://search-ci.liferay.com/job/integration-flaky/116/testReport/com.liferay.asset.publisher.lar.test/history/

To the best of my analysis, LPS-110705 appears to be unnecessary to solve the Search flukes we’re diagnosing and fixing (with around-the-clock help from @xbrianlee and @joshchong) and my recommendation as best immediate course of action would be for it to be reverted. All the evidence I collected points to Elasticsearch behavior being just fine, and instead uninitialized component dependencies being the prevalent root cause. (As in, scenarios I analyzed with missing search results aren’t caused by Elasticsearch taking too long to index; instead the root cause is the test running in the absence of a dependency, which leads to data never even being created or sent to the search engine in the first place.)

----

_[Bug] AssetPublisherExportImportTest#testAnyDLFileEntryType failing inconsistently_
https://issues.liferay.com/browse/LPS-110601

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/72b96134e6...fde35fc534

**Comment by jpince** [comment]
@arboliveira @xbrianlee is this something we could enforce in SF?

**Comment by arboliveira** [comment]
@jpince Yes, in several stages. This particular fix addressed 2 separate antipatterns, with one different best practice for each. SF should be able to immediately address the "`Util` == Evil" antipattern, and it may even possible to automate the substitution with moderate effort. (Nicer on devs, since this is widespread.) But there is a different architectural antipattern I'm not sure how we would go about, regarding tests starting execution earlier than wiring can finish for components with multiple cardinality and tailor made trackers. This necessitates a separate discussion if we want to isolate best practices SF would be able to enforce.

**Comment by jpince** [comment]
ci:stop

**Comment by jpince** [comment]
@arboliveira @xbrianlee can you please create a ticket for the "`Util` == Evil" issue and send it to Hugo & Alan to implement? LPS / `Dev Tools > Source Formatter`

**Pull request closed without merging**
