### PR TITLE
LPS-59423 Remove RegistryUtil references

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bfa92284da...b2fff1087e

**Comment by brianchandotcom** [comment]
See b2fff1087e242215b3193c46535a27701ecf41b8 @leoadb

**Comment by leoadb** [comment]
Thanks @brianchandotcom

**Comment by brianchandotcom** [comment]
@leoadb also, see b6fd1910ae8baafede9b680505616081ac1cc47f

We shoudln't hide the exception

**Comment by leoadb** [comment]
@brianchandotcom Thanks again !!!

**Pull request closed without merging**
