### PR TITLE
LPS-62356 Regenerate

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/57d24b4101...56623a402a

**Comment by brianchandotcom** [comment]
@marcellustavares I merged this in, but you forgot to delete the resources on deleting the data provider. See DDMTemplateLocalServiceImpl and how it has 

		resourceLocalService.deleteResource(
			template.getCompanyId(), DDMTemplate.class.getName(),
			ResourceConstants.SCOPE_INDIVIDUAL, template.getTemplateId());

Can you send me a follow up pull to fix this? Thx.

**Comment by marcellustavares** [comment]
Thanks @brianchandotcom, I've sent the follow up at https://github.com/brianchandotcom/liferay-portal/pull/34812

**Pull request closed without merging**
