### PR TITLE
LPS-78518 Replace Translation Manager with new Lexicon localisation pattern in Web Content administration.

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test

**Comment by jkappler** [comment]
hi @anthony-chu. We replaced translation manager in journal in this PR. Just fyi. It shouldn't break any tests

**Comment by anthony-chu** [comment]
@jkappler it looks like one of our tests is failing from the localization change. i'm currently building the branch and looking into the failure. thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7e08ffb1b0...7c8a77e6a7

**Pull request closed without merging**
