### PR TITLE
LPS-101885 Fetching versions when needed

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
@jkappler

**Comment by john-co** [comment]
Just started analyzing :)

**Comment by john-co** [comment]
Failing testcase StagingUsecase#TrashEntryReferencePublishing is possibly related to this pull.

cc/ @austinchiang

**Comment by john-co** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
ci:test:relevant

Retesting, network issue is unrelated to the pull:
```ssh: Could not resolve hostname github.com: Name or service not known
fatal: Could not read from remote repository.
```

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a025888d84...a2621a7ff3

**Pull request closed without merging**
