### PR TITLE
LPS-65799

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
/cc @shuyangzhou

On my machine, thread.count=5 is the number with the best performance

**Comment by brianchandotcom** [comment]
Very nice @hhuijser :)

**Comment by brianchandotcom** [comment]
@hhuijser do we need to sync / update the source formatter properties in plugins SDK?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/386123a06c...29c3c77044

**Comment by hhuijser** [comment]
@brianchandotcom

Yup, think we need to make changes to build.properties in plugins as well.
Also, right now, this doesn't work for running SF via Gradle.
All on my todo list...

**Pull request closed without merging**
