### PR TITLE
LPS-178861 Show title of the section in the dataset views list page

### PR DESCRIPTION
**Pull request by chestofwonders**
Resent from https://github.com/brianchandotcom/liferay-portal/pull/139800

Line breaks have been added to

modules/apps/frontend-data-set/frontend-data-set-web/src/main/resources/META-INF/resources/styles/main.scss

following these criteria:

- After breaking the alphabetical order for import order needs
- After importing from a file path and before importing from folder path

### CODE REVIEW

**Comment by dsanz** [comment]
ci:reopen

**Comment by dsanz** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ae4aab5823...167f98eec6

**Comment by brianchandotcom** [comment]
Thx @chestofwonders 

@dsanz can we sort the vars in 

modules/apps/frontend-data-set/frontend-data-set-web/src/main/resources/META-INF/resources/styles/_variables.scss

even in groups. Right now, it seems random.

**Comment by dsanz** [comment]
Sure: https://github.com/brianchandotcom/liferay-portal/pull/140126

**Pull request closed without merging**
