### PR TITLE
LPS-73481 Add upgrade processes for next GA and next minor releases

### PR DESCRIPTION
**Pull request by achaparro**
From https://github.com/brianchandotcom/liferay-portal/pull/50132

Hi @brianchandotcom,

I have taken the @SamZiemer commit and I have added mine in the top.

Right now the only differences for the folder v7_0_3 in ee-7.0.x and master are the following ones:
```
diff /home/achaparro/code/ee-7.0.x/portal-impl/src/com/liferay/portal/upgrade/v7_0_3/ /home/achaparro/code/master/portal/portal-impl/src/com/liferay/portal/upgrade/v7_0_3
diff /home/achaparro/code/ee-7.0.x/portal-impl/src/com/liferay/portal/upgrade/v7_0_3/UpgradeGroup.java /home/achaparro/code/master/portal/portal-impl/src/com/liferay/portal/upgrade/v7_0_3/UpgradeGroup.java
37,38c37,38
<                               dbInspector.normalizeName("Group_"),
<                               dbInspector.normalizeName("groupKey"))) {
---
>                               normalizeName("Group_", databaseMetaData),
>                               normalizeName("groupKey", databaseMetaData))) {
```
This is normal since the improvement in dbInspector has not been backported yet.

```
diff /home/achaparro/code/ee-7.0.x/portal-impl/src/com/liferay/portal/upgrade/v7_0_3/UpgradeModules.java /home/achaparro/code/master/portal/portal-impl/src/com/liferay/portal/upgrade/v7_0_3/UpgradeModules.java
18c18
<  * @author Inácio Nery
---
>  * @author Shuyang Zhou
```
The author doesn't impact in the logic.

The problem now is that we have changed the minor version and we need to do something like we did here:
https://issues.liferay.com/browse/LPS-41972
(If not, the source formatter will fail like in the previous pull)

But I don't know if we have any ant or gradle task for it, could you help me on this?

Thanks.

### CODE REVIEW

**Comment by achaparro** [comment]
ci:reopen

**Comment by achaparro** [comment]
@brianchandotcom, the pull failed because of the new minor version, we need to modify all dtds, etc.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ffc32ae7f1...acb4a9df4b

**Comment by brianchandotcom** [comment]
Good job @achaparro 

This was very good.

**Comment by brianwulbern** [comment]
@achaparro the functional and integration tests are failing to startup after this (due to a portal startup failure), with the following error:

```
   [junit] 02:34:14,395 ERROR [localhost-startStop-1][MainServlet:271] java.lang.RuntimeException: You must first upgrade to Liferay Portal 7100
    [junit] java.lang.RuntimeException: You must first upgrade to Liferay Portal 7100
    [junit] 	at com.liferay.portal.tools.DBUpgrader.checkRequiredBuildNumber(DBUpgrader.java:85)
    [junit] 	at com.liferay.portal.events.StartupAction.doRun(StartupAction.java:190)
    [junit] 	at com.liferay.portal.events.StartupAction.run(StartupAction.java:85)
    [junit] 	at com.liferay.portal.servlet.MainServlet.processStartupEvents(MainServlet.java:1318)
    [junit] 	at com.liferay.portal.servlet.MainServlet.init(MainServlet.java:268)
    [junit] 	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
    [junit] 	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1238)
    [junit] 	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1151)
    [junit] 	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1038)
    [junit] 	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4997)
    [junit] 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5289)
    [junit] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
    [junit] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
    [junit] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
    [junit] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
    [junit] 	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:585)
    [junit] 	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1794)
    [junit] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    [junit] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    [junit] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    [junit] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    [junit] 	at java.lang.Thread.run(Thread.java:745)
    [junit] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.482 sec
```

Can you have a look at it when you get a chance?  Thanks!

cc/ @rotty3000

**Comment by achaparro** [comment]
Hi @brianwulbern,

We have set the new version in the core for future release, you should upgrade the database with the upgrade client before running the tests.

I'm on vacation, so my responses will be delayed.

Thanks!
@robertoDiaz
@rotty3000

**Comment by brianwulbern** [comment]
follow up pull to resolve db version to 7100: https://github.com/brianchandotcom/liferay-portal/pull/50255

**Comment by robertoDiaz** [comment]
new pr in https://github.com/brianchandotcom/liferay-portal/pull/50257

**Comment by brianchandotcom** [comment]
I rolled back all of this pull. I should have never merged this, but I somehow thought this pull had passed since it was open in my queue for quite a long time.

Please resend with fixing all of it.

fyi @robertoDiaz @brianwulbern @achaparro 

Thx.

**Comment by robertoDiaz** [comment]
Got it @brianchandotcom

**Pull request closed without merging**
