### PR TITLE
LPS-58679 Adapt templates to show the configuration items per category

### PR DESCRIPTION
**Pull request by JorgeFerrer**
Hey Brian,

This pull does the first part of the conversion of Config Admin (aka System Settings) to JSPs. If you can review this today I'll convert the code in the Portlet class to MVC commands tomorrow.

It also adds the functionality to navigate configuration objects through categories. Once this is in I will review all existing configuration objects to set them in the right category.

/cc @drewbrokke @pei-jung Just FYI

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@JorgeFerrer feel free to send the next set on top of https://github.com/JorgeFerrer/liferay-portal/pull/599

**Comment by JorgeFerrer** [comment]
Thanks!

**Pull request closed without merging**
