### PR TITLE
LPS-110533 Remove Geolocation field from Form Builder once it's not a field from Forms scope.

### PR DESCRIPTION
**Pull request by natocesarrego**

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4384725ed4...5caac06d98

**Comment by brianchandotcom** [comment]
@natocesarrego see a106f23

**Pull request closed without merging**
