### PR TITLE
LPS-72580 Account for path context

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
@brianchandotcom  I think the lpkg failure was a fluke? Not sure why it aborted

**Comment by jpince** [comment]
That batch is failing on all master PR's - I emailed Shuyang to take a look at it.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9c7a9e8a26...0417075935

**Pull request closed without merging**
