### PR TITLE
LPS-61535

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
the failures are unrelated they happen with totally different changes on other pull requests too

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4307bc3865...8bb3f4e96a

**Comment by brianchandotcom** [comment]
@matethurzo PoshiRunner.test[ExportImport#ExportImportSampleLARPortlet] - Poshi Report - Poshi Summary - Console Output could have been one of your pulls from yesterday?

**Pull request closed without merging**
