### PR TITLE
LPS-61008 Modified Service Builder to create a rules.sql file for use with PSQL databases

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@mbowerman I thought we went over this to use a differnet pattern? Was this an accidental resubmit or on purpose? Please email me. Thx.

**Comment by rotty3000** [comment]
Sorry the PR was still open on my end, so without having seen any
discussion on this I processed it!

On Fri, Jan 8, 2016 at 10:40 AM, Brian Chan <notifications@github.com>
wrote:

> Closed #34085
> <https://github.com/brianchandotcom/liferay-portal/pull/34085>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/34085#event-509536886>
> .
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by mbowerman** [comment]
I think what happened was that Ray was on PTO when this pull request was first submitted. Since he was on PTO, we forwarded it to Peter Fellwock instead, but we forgot to close the pull request in Ray's queue, so it stayed open.

**Pull request closed without merging**
