### PR TITLE
LPS-169369 Replace notificationTemplateId with ERC in ObjectAction

### PR DESCRIPTION
**Pull request by murilostodolni**
Related: https://issues.liferay.com/browse/LPS-169369

The failures in https://github.com/liferay-objects/liferay-portal/pull/1567#issuecomment-1366966393 are not related with this code.

### CODE REVIEW

**Comment by murilostodolni** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/417d264681...3738945fda

**Comment by brianchandotcom** [comment]
@murilostodolni see my comments in 3738945fda32e0c52483022d80c33cdb45aa778f

**Comment by murilostodolni** [comment]
I will be careful next time. Thank you @brianchandotcom

**Pull request closed without merging**
