### PR TITLE
LPS-76808 Fix test

### PR DESCRIPTION
**Pull request by rafaprax**
\\cc @pedroqueiroz94

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test

**Comment by jpince** [comment]
pushed upstream - passed testing in https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/715 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jpince** [comment]
ci:close <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jpince** [comment]
@rafaprax @pedroqueiroz94 thanks!

**Comment by rafaprax** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0548364aab...0548364aab

**Pull request closed without merging**
