### PR TITLE
LPS-108070 SameSite=Lax cookies fix for SAML - Fix test class & package names

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Following up on  https://github.com/brianchandotcom/liferay-portal/pull/84852#issuecomment-588002720

/cc @csierra

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/98e93944e4...632406edc0

**Comment by brianchandotcom** [comment]
very nice @stian-sigvartsen @csierra see 259461f and 632406e

**Comment by stian-sigvartsen** [comment]
Thanks @brianchandotcom !

**Comment by stian-sigvartsen** [comment]
lbm:backport

**Pull request closed without merging**
