### PR TITLE
Readonly.config

### PR DESCRIPTION
**Pull request by rotty3000**
There are many cases where one may wish for OSGi configuration to be read-only. For example any scenario where we don't want end users to be able to alter the configuration from the portal UI for any number of reasons.

The OSGi Configuration Admin supports this. We just need to manifest this ability through infrastructure.

The primary usage will be where a file visible to Liferay File Install is marked as not writable (e.g. `chmod -x file.config`) then the configuration will appear in the Admin UI as read-only (i.e. not editable). Configuration Admin itself will protect updates to the configuration and throw an error if this is attempted (though the UI would not make this option available.)

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:reopen

**Comment by rotty3000** [comment]
If this is not what you meant by *net new* then just let me know where to go from here.

**Comment by brianchandotcom** [comment]
@shuyangzhou @tinatian fyi this is for LXC

I also asked @rotty3000 to add some basic test coverage, nothing crazy

**Comment by shuyangzhou** [comment]
@rotty3000 please add some tests in modules/apps/static/portal-file-install/portal-file-install-test to assert the expected behaviors. That will help us understand the requirements and future maintaining.

**Comment by rotty3000** [comment]
Yup, will do! I'm just having issues running those locally, but I'll solve it.

**Pull request closed without merging**
