### PR TITLE
Pr/23 lps 54744

### PR DESCRIPTION
**Pull request by arbetts**
sending based on comment on: https://github.com/arbetts/liferay-portal/pull/23

0fb4c13: i changed the method names to what i thought would be more understandable

550ad02: @holatuwol helped me refactor the JSON manipulation into different objects. We thought this made things more understandable because the structure is now based on Type and not just JSONArrays.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@arbetts Great job on this fix! Please see my changes in upstream.

**Comment by brianchandotcom** [comment]
@arbetts rebase error, can you resend? Thx!

**Comment by arbetts** [comment]
@brianchandotcom 

rebased and sent to Jonathan for review

https://github.com/jonathanmccann/liferay-portal/pull/786

**Comment by arbetts** [comment]
ci:retest

**Pull request closed without merging**
