### PR TITLE
LPS-79327 Make packages and class names consistent

### PR DESCRIPTION
**Pull request by epgarcia**
@brianchandotcom 
I looked for some examples as references in the portal, but I noticed we have either plural (bookmarks, blogs, mentions) or singular (comment, invitation, asset), or mixed (social-activity-* & social-activities-*) for module and package names. 

Finally I decided to keep the app, the modules and the packages with "segments", as they're aimed to contain not only the segment entity, but also any other related classes (e.g. Individual, Rule). I renamed the SegmentService to SegmentsManager, as suggested. I also renamed the segments-asset-categories-demo(-test) modules to segments-asset-category-demo(-test), to avoid two plurals on the same name.

Now that the segments code is minimum is the best moment to refactor names, so please let me know if you'd change anything else.

Thanks! 

@juliocamarero

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@brianchandotcom I realize why we're not able to map this to our existing pattern.. 

Currently, it's Xyz (Workflow, Message Boards, Blogs, Journal, DDM, DDL, DL, etc.)

Xyz may be plural or singular, that part doesn't matter.

But then, XyzAbc, Abc is always singular (WorkflowTask, JournalArticle).

In our case, we're missing Abc. We just have "Segments" as Xyz, and "Segment" as Abc, hence the confusion.

Can you normalize and resend? Also, note 90c82305ad674721cd830b7e9e353aee7101cc68 was sent to me to fix CI.

**Comment by mhan810** [comment]
com.liferay.segmentation?

**Comment by epgarcia** [comment]
I like it, as long as we can have com.liferay.segmentation.Segment and not com.liferay.segmentation.SegmentationSegment.

**Comment by mhan810** [comment]
Agreed @brianchan let's go with that.  Segment is an understood term

**Pull request closed without merging**
