### PR TITLE
LPS-139284 Test coverage

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:reopen

**Comment by gabrielwas** [comment]
CI passed here https://github.com/liferay-objects/liferay-portal/pull/109

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7e5c09f55b...f46a818144

**Comment by brianchandotcom** [comment]
@gabrielwas see f46a8181449f703c66a85644ae39f4282827319e

**Pull request closed without merging**
