### PR TITLE
LPS-63101

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-63101.

NOTE: We are deprecating unused taglibs in portal for the release so we can remove them for the next release.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3f4461eb75...16cdd6b7bb

**Comment by brianchandotcom** [comment]
@jhinkey see fb4ad999f78831be7739ed12a0911303302876b8

Thx

**Comment by jhinkey** [comment]
Noted. Thanks.

@mwilliams2014 is updating the Taglib description guidelines to explain
how to describe deprecations.

On 2/10/2016 2:44 PM, Brian Chan wrote:
>
> @jhinkey <https://github.com/jhinkey> see fb4ad99
> <https://github.com/brianchandotcom/liferay-portal/commit/fb4ad999f78831be7739ed12a0911303302876b8>
>
> Thx
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/35886#issuecomment-182545704>.
>

-- 
Jim Hinkey
Sr. Knowledge Engineer
Liferay, Inc.
www.liferay.com <http://www.liferay.com>

Visit Us: www.liferay.com <http://www.liferay.com> | Like Us:
facebook.com/liferay <http://facebook.com/liferay> | Follow Us:
twitter.com/liferay <http://twitter.com/liferay>

**Pull request closed without merging**
