### PR TITLE
Lps 63617

### PR DESCRIPTION
**Pull request by shuyangzhou**
@mhan810 @migue @BrettSwaim, this is doing concurrent at Tables and ClassNames level, not table pagination yet.

Please run test to check how much this improves UpgradeKernelPackage's running time. If still necessary, we will continue with table pagination parallel running.

### CODE REVIEW

**Comment by migue** [comment]
This won't improve the performance (I did it early this morning and tested it). Most of this queries are doing  comparison "**like %xxx**" which is preventing the row level locking and, thus, getting the benefits of updating the tables in parallel

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8c88a4c17c...bb28cc41a5

**Comment by brianchandotcom** [comment]
@shuyangzhou I merged this in, but please see comment from @migue who says it most likely will not work. If he's right, please send me a revert. Thx.

**Comment by brianchandotcom** [comment]
@migue @shuyangzhou @Preston-Crary I rolled back this pull due to an error I found in https://github.com/brianchandotcom/liferay-portal/pull/36628

**Pull request closed without merging**
