### PR TITLE
LPS-78035 Remove FPA site navigation menu item type since we decided to maintain it as a Layout type for now

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test

**Comment by pavel-savinov** [comment]
cc @ealonso @JorgeFerrer

**Comment by anthony-chu** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8079e9d5df...af8c3b19f0

**Pull request closed without merging**
