### PR TITLE
Revert "LPS-99657 Class that implements ConfigurationModelListener should be in package *.configuration.persistence.listener"

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-51478

### CODE REVIEW

**Comment by austinchiang** [comment]
@brianchandotcom LPS-99657 caused about half of our upstream tests which use JSON to fail so I am reverting this pull.

**Comment by brianchandotcom** [comment]
@austinchiang I would normally quickly merge a revert like this. However, I published some new jars that were related to this pull, so reverting will be tricky.

@hhuijser can you see which ones are broken (likely there is a pattern to quickly fix those upstream tests)

@austinchiang can you give info to @hhuijser on what is breaking? Thx.

**Comment by austinchiang** [comment]
@hhuijser Two groups of tests are failing. One cannot find the path for [groupId](https://testray.liferay.com/reports/production/logs/test-1-1/1566039681204/test-portal-upstream(master)/770/functional-tomcat90-mysql57-jdk8/282/1/jenkins-console.txt.gz) and the other for [companyId](https://testray.liferay.com/reports/production/logs/test-1-1/1566039681204/test-portal-upstream(master)/770/functional-tomcat90-mysql57-jdk8/314/1/jenkins-console.txt.gz). In both cases the response to the cURL request is `"exception":"Access denied to com.liferay.portal.kernel.service.CompanyService#getCompanyByVirtualHost","throwable":"java.lang.SecurityException: Access denied to com.liferay.portal.kernel.service.CompanyService#getCompanyByVirtualHost","error":{"message":"Access denied to com.liferay.portal.kernel.service.CompanyService#getCompanyByVirtualHost","type":"java.lang.SecurityException"`

**Comment by jpince** [comment]
@hhuijser see also https://issues.liferay.com/browse/LPS-99959 for more examples

**Pull request closed without merging**
