### PR TITLE
LPS-95507 Fix out of memory issues on CI

### PR DESCRIPTION
**Pull request by petershin**
Please backport this fix to 7.0.x<br /><br />@timpak @jpince @lipusz

### CODE REVIEW

**Comment by lipusz** [comment]
Thanks Peter! :+1:

**Comment by jpince** [comment]
@lipusz is a fix also needed for 7.1.x?

**Comment by lipusz** [comment]
Hey Jason, @jpince 

Yes it is, based on @timpak's comment on https://issues.liferay.com/browse/LPS-95507?focusedCommentId=1833152&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1833152.

**Comment by jpince** [comment]
@petershin is this fix appropriate to backport to 7.1.x as well?

**Comment by petershin** [comment]
@jpince - Yup, `7,2,x`, `7.1.x`, and `7.0.x`

**Comment by jpince** [comment]
@petershin thanks!

**Comment by brianchandotcom** [comment]
Done, backported to all the way to 7.0.x and updated hashes.

**Pull request closed without merging**
