### PR TITLE
Logical Partitioning: Company provider infrastructure. No logical changes, just injecting a reference to the company provider in all the persistenes

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by migue** [comment]
@cgoncas Cris, FYI I will keep a on the pull in case we get some unexpected error.

Thanks a lot!

**Comment by brianchandotcom** [comment]
I'll fix the SF.. you can ignore that error.

**Comment by migue** [comment]
not sure why it complains, the file has already the copyright ...

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ff6f8d0903...10ead4258a

**Pull request closed without merging**
