### PR TITLE
LPS-97704 SF

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by victorg1991** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchandotcom** [comment]
lbm:backport @CsabaTurcsan @jpince @zsoltbalogh

**Comment by brianchandotcom** [comment]
@CsabaTurcsan @jpince @zsoltbalogh this one is tricky because LPS-97704 was already partially backported to 7.2.x.

**Pull request closed without merging**
