### PR TITLE
LPS-97221 Rename and sort parameters

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fef233a684...fe0b7abee8

**Comment by brianchandotcom** [comment]
@nhpatt see DataDefinitionResourceImpl.java#activate / deactivate and how it creates SPIDataRecordCollectionResource

Can you apply this pattern to SPICommentResource and SPIRatingResource

I think it's cleaner than how we have CommentResourceImpl#_getSPICommentResource()

and just use the @Activate annotation.

Thx @nhpatt

**Comment by brianchandotcom** [comment]
@nhpatt @leoadb @jeyvison I also renamed SPIDataRecordCollectionResource to CommonDataRecordCollectionResource

I'm thinking of renaming headless-common-spi to just headless-common and will rename most of *SPI* to *Common* in 

Going to sleep on it.

See 2635c45077ccb79f26fe605a1cd2b046f49ebdb0

@nhpatt for now, feel free to update CommentResourceImpl#_getSPICommentResource() still, since I'll probably do the change sometime tomorrow after I get your changes to usage of SPICommentResource and SPIRatingResource.

**Comment by nhpatt** [comment]
Sent here: https://github.com/brianchandotcom/liferay-portal/pull/75390 :)

**Pull request closed without merging**
