### PR TITLE
LPS-151552 Removing and re-adding account role permission makes Group Scope permission disappear

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LPS-151552

Manual forward from [liferay-usm#529](https://github.com/liferay-usm/liferay-portal/pull/529)

### CODE REVIEW

**Comment by epark18** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5a744295a0...519df84e8e

**Comment by brianchandotcom** [comment]
@epark18 we need a functional test for this

**Comment by brianchandotcom** [comment]
@drewbrokke @epark18  we need a functional test for this

**Pull request closed without merging**
