### PR TITLE
LPS-70669 FIX LanguageImpl returns every possible locale for groups in secondary companies, localized_title gets indexed into too many fields

### PR DESCRIPTION
**Pull request by arboliveira**
Authors: @jorgediaz-lr @rodrigopaulino
Reviewer: @arboliveira

https://issues.liferay.com/browse/LPS-70669

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:reopen

**Comment by arboliveira** [comment]
Unrelated failure: `XMLSourceProcessorTest.testCharactersBeforeDefinitionTag`

**Comment by arboliveira** [comment]
Unrelated failure: `XMLSourceProcessorTest.testCharactersBeforeDefinitionTag`

**Comment by brianchandotcom** [comment]
@arboliveira this is the right fix, but the test is in the wrong package. I mean, it doesn't have to do with "search" per se, and should be like HttpImplTest for HttpImpl.

Can you send it to @shuyangzhou following that pattern? Thx.

**Comment by arboliveira** [comment]
@shuyangzhou Can you help me find a good home for `LanguageAvailableLocalesTest`? It's a new Arquillian test, but I wouldn't know if there's already a module for integration tests intended to cover core infrastructure classes. Older tests for `LanguageImpl` are non-Arquillian, legacy style integration tests in `portal-impl/test/integration`. Should I rewrite the new test as such (no more `@Inject`) and move it there? Or is there an OSGi module for core infrastructure things that would accept `Language` and `Locale` related integration tests in its `-test` companion project?

**Comment by shuyangzhou** [comment]
@arboliveira it should simply go into LanguageImplTest. @Inject works in all integration tests, no matter it is portal-impl integration or arquillian integration.

**Pull request closed without merging**
