### PR TITLE
LPS-109728

### PR DESCRIPTION
**Pull request by p2kmgcl**
/cc @ealonso @victorg1991

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:test:relevant @yichenroy didn't initiate

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fbc0f2520a...bfb45fa0e7

**Comment by jpince** [comment]
ci:stop

**Comment by yichenroy** [comment]
There was network issue affecting all of CI, see more info on Slack: https://liferay.slack.com/archives/CL3TWSMHQ/p1583509586067800

**Comment by yichenroy** [comment]
ci:test:stable

Running stable test, there was a network outage last night affecting CI.

**Comment by jkappler** [comment]
ci:test:stable

**Pull request closed without merging**
