### PR TITLE
pull-request-2079

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for some of the documentation files in the `modules/sdk` folder.

I sent this to @lawrence-lee for review at https://github.com/lawrence-lee/liferay-portal/pull/115#issuecomment-496977066.  He has approved it.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@hhuijser can you SF this? Thx.

**Comment by jpince** [comment]
@blzaugg @jonmak08 is there a reason why we didn't create a real LPS ticket for this?

**Comment by blzaugg** [comment]
I wasn't sure if it was needed. I saw a pattern recently of misc fixes going through with LPS-0. That weren't related to a specific bug. No (apparent) bug was being addressed here, just cleanup.

**Comment by jpince** [comment]
@blzaugg yes, there are some commits that have gone in under LPS-0, but our preference is to have all commits linked to real tickets so the work can be tracked. For next time :)

**Pull request closed without merging**
