### PR TITLE
LPS-48156 Create an error taglib for PrincipalException

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @JorgeFerrer @natecavanaugh

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/85b8c6bfcc...44f31eb503

**Comment by brianchandotcom** [comment]
Great job @pei-jung can you also send me a pull for plugins master?

Thx

**Comment by pei-jung** [comment]
Hi Brian,

Pull for plugins master submitted to https://github.com/brianchandotcom/liferay-plugins/pull/4725. Thanks!

**Pull request closed without merging**
