### PR TITLE
LPS-75025 Card visible interaction icon

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @austinchiang @patriciajeanperez this pull includes a new Application Display Template for Blogs as cards. I sent it directly to Brian because it's a new ADT that doesn't have any impact in our tests. 
However, I think it would be good to add a functional test that ensures that this ADT works when there's a blog entry and the blogs portlet is configured to display this ADT. As long as it doesn't display any freemarker error we should be good.
Let me know if you guys have any questions.

**Comment by austinchiang** [comment]
Sounds good @sergiogonzalez , thanks!

**Comment by sergiogonzalez** [comment]
cc/ @ngaskill we should document this new Application Display Template in our official documentation for blogs. I have included a small description of the functionality as well as some limitations/requirements in the LPS ticket in the documentation section. Let me know if you have any question.

cc/ @austinchiang @patriciajeanperez

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/13c37e0c22...81e4a5d915

**Pull request closed without merging**
