### PR TITLE
Lps 86079 4

### PR DESCRIPTION
**Pull request by shuyangzhou**
Ok, fixed lpkg bundling leftover jars issue, now this is completely done, and I can sleep well :)

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@pyoo47 ?

**Comment by shuyangzhou** [comment]
ci:test

**Comment by pyoo47** [comment]
ci:test

**Comment by pyoo47** [comment]
@shuyangzhou Looks like there were network problems going on during the previous runs. When a failure occurs in the top level, downstream builds are automatically aborted to preserve resources.

**Comment by jpince** [comment]
ci:test

@pyoo47 `curl: (6) Could not resolve host: test-1-22; Unknown error`

**Comment by pyoo47** [comment]
Seems like network issues are sporadically happening still. I'll reach out to IT.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
