### PR TITLE
LPS-76164 Apply same logic and restriction to drag and drop upload in Documents and Media

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @robertoDiaz

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3afeeecf32...dd5c6fe9f6

**Pull request closed without merging**
