### PR TITLE
LPS-64006 Prevent success message of being overlapped by the search input

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
cc @marcellustavares

**Comment by leoadb** [comment]
cc @ZoltanTakacs

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4beb3af9a5...a86c603cec

**Comment by ZoltanTakacs** [comment]
Thank you @leoadb. It's been merged to 7.0.x.

Please note that the backport workflow has been changed for the RCs. 
For the details please see @jhendley 's email or refer to this [document](https://docs.google.com/document/d/1A-EoPvI1KDDpUH2PAlKmpgUDb_2RFM4iwpB_4loQHFk/edit).

Thank you,
Zoltán

**Pull request closed without merging**
