### PR TITLE
[See desc] LPS-68589 Rename to EscapableLocalizableFunction

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey Brian,

This is a resend of https://github.com/brianchandotcom/liferay-portal/pull/44603#issuecomment-259215821

The reason why we named it `EscapableLocalizableFunctionObject` was for consistency with the already existing `EscapableObject'. Your point of not naming it Object makes sense, so we have renamed it to `EscapableLocalizableFunction`. Let us know if that makes sense to you.

Thanks!

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @robertoDiaz

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@sergiogonzalez conflict with upstream, please resend? Thx.

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
rebased in https://github.com/brianchandotcom/liferay-portal/pull/44720

To simplify the rebase I've fixup some SF commits 

thx!!

**Pull request closed without merging**
