### PR TITLE
LPS-65135

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@Ithildir

There is a few bnd files that include @com.liferay.portal.kernel-*.jar!/com/liferay/portal/kernel/util/Validator.class, where I don't see calls to Validator.
Some of those I didn't touch, but I am too scared to remove stuff in *.bnd as those can be indirect calls?

portal-tools-upgrade-table-builder\bnd.bnd
portal-tools-wsdd-builder\bnd.bnd
tld-formatter\bnd.bnd

**Comment by hhuijser** [comment]
@brianchandotcom 

For Validator_IW.java, did you generate and then manually put those isNotNull methods back?
If so, those are going to disappear at some point, since they get removed every time you run ant build-iw (unless you remember to put them back every time).

Also, do we want to keep those there since the matching methods in Validator are gone?

**Comment by brianchandotcom** [comment]
@hhuijser 

NestedSetsTreeManagerTest.testMove
TestSuite.com.liferay.portal.kernel.service.persistence.impl.NestedSetsTreeManagerTest

Those seem real?

**Comment by brianchandotcom** [comment]
@hhuijser 

For now, when we regenerate, we have to manually add those 2 methods back. If we don't, we have baseline versioning /backwards compatibility issues :(

**Comment by Ithildir** [comment]
@hhuijser: exactly, they're probably indirect calls from another embedded util class!

**Comment by hhuijser** [comment]
@Ithildir 

So there is no way to know if we have unused imports there, is there?

**Comment by Ithildir** [comment]
I'm not sure, when I moved those tools out of the core I used a brute-force approach: trying to run it and seeing why it was breaking :disappointed:

**Comment by hhuijser** [comment]
Was afraid you'd say that... that's the same approach I have been using, which is very time consuming :(

**Pull request closed without merging**
