### PR TITLE
LPS-74544

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@izaera, can you take care of these: https://github.com/brianchandotcom/liferay-portal/pull/53611/commits/1a2882f98c85cbb605dc63264674d8dbe6c9888b

We only allow `*.java` files in `src/*/java`, see https://github.com/brianchandotcom/liferay-portal/pull/41321

**Comment by hhuijser** [comment]
ci:test

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
