### PR TITLE
LRQA-35749 | master

### PR DESCRIPTION
**Pull request by kmaria**
https://issues.liferay.com/browse/LRQA-35749

### CODE REVIEW

**Comment by brianwulbern** [comment]
@kmaria Looks like there was an issue with Nexus, will retest:

```
     [exec] :private:apps:portal-reports-engine:portal-reports-engine-console-web:compileJava FAILED
     [exec] Download http://repository.liferay.com/nexus/service/local/repo_groups/private/content/com/liferay/com.liferay.saml.api/1.1.0/com.liferay.saml.api-1.1.0.jar
     [exec] Note: /opt/dev/projects/github/liferay-portal/modules/private/apps/saml/saml-web/src/main/java/com/liferay/saml/web/internal/portlet/action/DefaultViewMVCRenderCommand.java uses unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] Note: Some input files use or override a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Could not resolve all files for configuration ':private:apps:portal-reports-engine:portal-reports-engine-console-web:compileClasspath'.
     [exec] > Could not download com.liferay.portal.reports.engine.console.api.jar (com.liferay:com.liferay.portal.reports.engine.console.api:2.0.0)
     [exec]    > Could not get resource 'http://repository.liferay.com/nexus/service/local/repo_groups/private/content/com/liferay/com.liferay.portal.reports.engine.console.api/2.0.0/com.liferay.portal.reports.engine.console.api-2.0.0.jar'.
     [exec]       > Could not GET 'http://repository.liferay.com/nexus/service/local/repo_groups/private/content/com/liferay/com.liferay.portal.reports.engine.console.api/2.0.0/com.liferay.portal.reports.engine.console.api-2.0.0.jar'. Received status code 502 from server: Bad Gateway
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':private:apps:portal-reports-engine:portal-reports-engine-console-web:compileClasspath'.
     [exec] 	at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$1.collectFiles(DefaultLenientConfiguration.java:130)
     [exec] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.doGetFiles(DefaultConfiguration.java:519)
     [exec] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getFiles(DefaultConfiguration.java:356)
     [exec] 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getFiles(Unknown Source)
     [exec] 	at org.gradle.api.internal.file.AbstractFileCollection.iterator(AbstractFileCollection.java:68)
```

**Comment by brianwulbern** [comment]
ci:retest

**Comment by jpince** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
