### PR TITLE
LPS-74628 Add petra-concurrent

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@rotty3000 this pull has some issues.
The major one is, it duplicates CentralizedThreadLocal, unlike other classes, it can not be duplicated. As that will no longer be "centralized". When its api being used for query and clear threadlocals, it needs to ensure all "centralized" threadlocals are included. In this case, the petra one is not aware of kernel one, and the kernel usage like https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/servlet/filters/threadlocal/ThreadLocalFilter.java#L39 is not aware of any petra ones, which will besically become a threadlocal leak.

Beside this pull just contains a single commit, although I can tell it does not include every class from the original package, and some classes are modified. It is better to keep those changes in the history so that in case something goes wrong, we can have an easy way to trace back.

We had some discussion about this months ago, however I never get a clean idea about the requirements behind this. And it is better to send these pulls to me rather than @brianchandotcom , after all most classes in those packages are mine. If anyone can catch refactor regression issues, that would be me.

**Comment by rotty3000** [comment]
This module is designed to be used completely stand alone, without the portal! Don't think of it as duplicating anything, since the goal is actually to make an implementation of concurrent that can be used outside the portal with full functionality. Note, several more similar modules are on their way to add the other aspects of concurrent which are not included here, such as petra-memory, petra-io, etc.

**Comment by rotty3000** [comment]
I will resend to you @shuyangzhou!

**Comment by shuyangzhou** [comment]
@rotty3000 I understand the part that "stand alone, without the portal", but it does not mean the Petra code is not used by portal, right? In case of that we will have leaking thread locals. From that perspective, it is an incompleted duplication of portal code which will not work properly.

**Comment by rotty3000** [comment]
@shuyangzhou can we move the discussion over the the PR I sent you?

**Pull request closed without merging**
