### PR TITLE
LPS-57644 update product menu markup

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @marcoscv-work @natecavanaugh

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@juliocamarero please resend, true smoke test error. Thx.

**Comment by brianchiu** [comment]
@juliocamarero @anthony-chu @brianwulbern @koor4356 

Based on poshi report, might be a test fix needed? I sent you all an email.

**Comment by brianwulbern** [comment]
@brianchiu I'll fetch his branch and checkout the locator for making a test fix.

**Comment by brianwulbern** [comment]
@brianchiu I updated my pull with the fix here: https://github.com/brianchiu/liferay-portal/pull/576

**Pull request closed without merging**
