### PR TITLE
master-lps-63560

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LPS-63560

### CODE REVIEW

**Comment by jkappler** [comment]
Thanks again @evannagayama!!!!

**Comment by pyoo47** [comment]
This build appears to have hung during the PR tester reset. I will abort and retest this after the reset is complete.

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/34a7f2353a...2ae82056b1

**Pull request closed without merging**
