### PR TITLE
LPS-55341

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @juliocamarero

Looks to me you simply missed a few, but can you please double check?

**Comment by juliocamarero** [comment]
yep, as long as it compiles, it is good! :+1:

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/38ca57af5b...eee4cca211

**Pull request closed without merging**
