### PR TITLE
LPS-74370 Rename

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by pyoo47** [comment]
ci:retest (due to a bad slave on test-1-3)

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3c40316b9a...2a418b1171

**Comment by brianchandotcom** [comment]
@ealonso @jkappler please see my changes in upstream. Thx.

**Pull request closed without merging**
