### PR TITLE
Lps 67078

### PR DESCRIPTION
**Pull request by shuyangzhou**
@migue @rotty3000 please read the ticket description https://issues.liferay.com/browse/LPS-67078,  it is quite long, as it is a complex issue, although it is only affecting CI env, so low priority.

My fix here is only a temp work around, but the test I created can be helpful for you to continue on a formal fix and preventing anything like this from happening again.

It is all about the bnd processing logic inside wab generator, we might need a configurable way to filter out some unwanted imports. I think it is better to be per wab bundle based, and embedded config info inside the wab war itself. Or any other way you guys see fit.

CC @mhan810

### CODE REVIEW

**Comment by shuyangzhou** [comment]
CC @Ithildir

**Comment by brianchandotcom** [comment]
@shuyangzhou can you resend? modules/test/** is for modules that power tests, not for tests themselves. Can you add to test to the WAB?

Thx.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/41457

**Comment by brianchandotcom** [comment]
@shuyangzhou I renamed the test and module.. see 4ec77460a10f55cbf26b7feb4b8f64ea4562b786

**Pull request closed without merging**
