### PR TITLE
LPS-98939 Publish layout

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4a980f1dbf...caf4e745c0

**Comment by brianchandotcom** [comment]
@preston-crary see revert by @ealonso

**Pull request closed without merging**
