### PR TITLE
LPS-59106 - Update Lexicon to 0.1.19

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-59106

Hey @brianchandotcom, @natecavanaugh asked me to send this directly to you. @mjbradford89 is blocked because of this.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3e179237d7...4779f3ce4e

**Comment by brianchandotcom** [comment]
@pat270 you forgot 4779f3ce4eb0b03c1f1976bfbf7cca278221c0da or else it won't build at all

**Comment by brianchandotcom** [comment]
Sorry, use this has instead 1e8ada75c1cca13c973564168ce06357d4e67cdc

**Comment by pat270** [comment]
@brianchandotcom, Sorry I completely spaced on that.

**Pull request closed without merging**
