### PR TITLE
LPD 26473

### PR DESCRIPTION
**Pull request by rotty3000**
- **LPD-26473 define a constant for default-service-account**
- **LPD-26473 oAuth2ApplicationHeadlessServer client extensions should default the user binding to the default-service-account**

### CODE REVIEW

**Comment by rotty3000** [comment]
cc @gamerson

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/387c0da87d...662928b3d7

**Comment by brianchandotcom** [comment]
@rotty3000 see 662928b3d7ed44f07ff7071387e76a006800c6c2 can I group the test like this? It passed for me.

See also adcb7d9c16b4d05c74a752efefe1dd7fcfcfdfa4

**Comment by rotty3000** [comment]
yes, that's fine!

**Pull request closed without merging**
