### PR TITLE
LPS-67914 Create Porygon Theme and Site Template

### PR DESCRIPTION
**Pull request by kenjiheigel**
@brianchandotcom, this is a resend of https://github.com/brianchandotcom/liferay-portal/pull/43394. It was failing due to the node-sass resource dependency that we're hosting (or rather not hosting) on mirrors. I've regenerated the npm shrinkwrap to match the version we're hosting on mirrors. Let me know if you have any questions. 

cc-ing: @jbalsas, @marcoscv-work

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:reopen

**Comment by brianchiu** [comment]
ci:close

**Comment by brianchiu** [comment]
@jbalsas @marcoscv-work 
CC @kenjiheigel 

Can you guys take a look into this? 

I have a pull here that's fairly recent that looks pretty clean compared to this one.
https://github.com/brianchandotcom/liferay-portal/pull/43499

There are a good number of backend test failures on this.

1 of the 8 smoke batches (oracle, but it usually doesn't fail) as well as 2 out of 6 of the upgrades batches (the mariaDB ones) failed with the following error:
````
     [exec] 23:00:19,070 ERROR [liferay/hot_deploy-1][SerialDestination:61] Unable to process message {destinationName=liferay/hot_deploy, response=null, responseDestinationName=null, responseId=null, payload=null, values={defaultLocale=en_US, companyId=20116, groupId=0, command=deploy, servletContextName=porygon-theme}}
     [exec] com.liferay.portal.kernel.messaging.MessageListenerException: com.liferay.exportimport.kernel.lar.PortletDataException: java.lang.NullPointerException
     [exec] 	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:32)
     [exec] 	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:74)
     [exec] 	at com.liferay.portal.kernel.messaging.SerialDestination$1.run(SerialDestination.java:58)
     [exec] 	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask._runTask(ThreadPoolExecutor.java:756)
     [exec] 	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask.run(ThreadPoolExecutor.java:667)
     [exec] 	at java.lang.Thread.run(Thread.java:745)
     [exec] Caused by: com.liferay.exportimport.kernel.lar.PortletDataException: java.lang.NullPointerException
     [exec] 	at com.liferay.exportimport.kernel.lar.BaseStagedModelDataHandler.importStagedModel(BaseStagedModelDataHandler.java:407)
     [exec] 	at com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil.importStagedModel(StagedModelDataHandlerUtil.java:367)
     [exec] 	at com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil.importStagedModel(StagedModelDataHandlerUtil.java:353)
     [exec] 	at com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil.doImportReferenceStagedModel(StagedModelDataHandlerUtil.java:400)
     [exec] 	at com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil.importReferenceStagedModel(StagedModelDataHandlerUtil.java:279)
     [exec] 	at com.liferay.exportimport.kernel.lar.BaseStagedModelDataHandler.importReferenceStagedModels(BaseStagedModelDataHandler.java:803)
     [exec] 	at com.liferay.exportimport.kernel.lar.BaseStagedModelDataHandler.importStagedModel(BaseStagedModelDataHandler.java:361)
     [exec] 	at com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil.importStagedModel(StagedModelDataHandlerUtil.java:367)
     [exec] 	at com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil.importStagedModel(StagedModelDataHandlerUtil.java:353)
     [exec] 	at com.liferay.journal.exportimport.data.handler.JournalPortletDataHandler.doImportData(JournalPortletDataHandler.java:339)
     [exec] 	at com.liferay.exportimport.kernel.lar.BasePortletDataHandler.importData(BasePortletDataHandler.java:372)
     [exec] 	at com.liferay.exportimport.controller.PortletImportController.importPortletData(PortletImportController.java:300)
     [exec] 	at com.liferay.exportimport.controller.PortletImportController.importPortletData(PortletImportController.java:792)
     [exec] 	at com.liferay.exportimport.controller.LayoutImportController.doImportFile(LayoutImportController.java:738)
     [exec] 	at com.liferay.exportimport.controller.LayoutImportController.importFile(LayoutImportController.java:224)
     [exec] 	at com.liferay.portlet.exportimport.service.impl.ExportImportLocalServiceImpl.importLayouts(ExportImportLocalServiceImpl.java:185)
     [exec] 	at com.liferay.portlet.exportimport.service.impl.ExportImportLocalServiceImpl.importLayouts(ExportImportLocalServiceImpl.java:217)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:497)
     [exec] 	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:153)
     [exec] 	at com.liferay.portal.spring.transaction.DefaultTransactionExecutor.execute(DefaultTransactionExecutor.java:85)
     [exec] 	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:58)
     [exec] 	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:127)
     [exec] 	at com.liferay.portal.spring.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:56)
     [exec] 	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:127)
     [exec] 	at com.liferay.portal.spring.aop.ServiceBeanAopProxy.invoke(ServiceBeanAopProxy.java:174)
     [exec] 	at com.sun.proxy.$Proxy96.importLayouts(Unknown Source)
     [exec] 	at com.liferay.exportimport.kernel.service.ExportImportLocalServiceUtil.importLayouts(ExportImportLocalServiceUtil.java:209)
     [exec] 	at com.liferay.exportimport.resources.importer.internal.util.LARImporter.importResources(LARImporter.java:89)
     [exec] 	at com.liferay.exportimport.resources.importer.internal.messaging.ResourcesImporterHotDeployMessageListener._importResources(ResourcesImporterHotDeployMessageListener.java:259)
     [exec] 	at com.liferay.exportimport.resources.importer.internal.messaging.ResourcesImporterHotDeployMessageListener.initialize(ResourcesImporterHotDeployMessageListener.java:150)
     [exec] 	at com.liferay.exportimport.resources.importer.internal.messaging.ResourcesImporterHotDeployMessageListener.onDeploy(ResourcesImporterHotDeployMessageListener.java:163)
     [exec] 	at com.liferay.portal.kernel.messaging.HotDeployMessageListener.doReceive(HotDeployMessageListener.java:55)
     [exec] 	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:26)
     [exec] 	... 5 more
     [exec] Caused by: java.lang.NullPointerException
     [exec] 	at com.liferay.layout.admin.web.internal.exportimport.data.handler.LayoutStagedModelDataHandler.doImportStagedModel(LayoutStagedModelDataHandler.java:348)
     [exec] 	at com.liferay.layout.admin.web.internal.exportimport.data.handler.LayoutStagedModelDataHandler.doImportStagedModel(LayoutStagedModelDataHandler.java:94)
     [exec] 	at com.liferay.exportimport.kernel.lar.BaseStagedModelDataHandler.importStagedModel(BaseStagedModelDataHandler.java:363)
     [exec] 	... 40 more
````

Console output here for full context on the exception:
https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=0,label_exp=!master/38366//console

**Comment by kenjiheigel** [comment]
Thanks @brianchiu, we'll look into this.

**Comment by jbalsas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
