### PR TITLE
LPS-62557  As a developer I would like to cleanup imagegallerydisplay

### PR DESCRIPTION
**Pull request by peterfellwock**

### CODE REVIEW

**Comment by peterfellwock** [comment]
fixed!

**Comment by peterfellwock** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/63e0da957b...9856a5f816

**Comment by brianchandotcom** [comment]
nice clean up work @peterfellwock !

**Pull request closed without merging**
