### PR TITLE
Lps 75188

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cf209aea6a...ee1a910981

**Comment by brianchandotcom** [comment]
@shuyangzhou can you backport? CP is not clean.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal-ee/pull/18472

**Pull request closed without merging**
