### PR TITLE
[TS] LPS-74827 FIX: When staging is enabled, site members cannot see content created by other users

### PR DESCRIPTION
**Pull request by arboliveira**
Authors: @yuhai @BryanEngler
Reviewers: @BryanEngler @arboliveira

https://issues.liferay.com/browse/LPS-74827 

@yuhai Our team explored some solutions and we tried a different approach. Instead of indexing the live site's groupId into the staged document, we will keep indexing the staging site's groupId as before; but now, the search query will also include the staging site's groupId alongside the live site's groupId, so the staged document can be matched. With this approach, we also determined it wasn't necessary to index groupRoleId values. If we follow now the ticket's "steps to reproduce"  we achieve the described expected behavior; but if you can think of a different use case that would break with this approach, please send me the steps to reproduce, or a red test case in the class we added to replicate the bug (`AssetSearcherStagingTest`.)

cc/ @topolik @matethurzo @hhuijser

----

@shuyangzhou Please be aware the new `AssetSearcherStagingTest` may be leaking `User` objects. We couldn't add `@DeleteAfterTestRun` to the `_users` field, as this leads to failure deleting the export-import background task.

https://github.com/arboliveira/liferay-portal/blob/996fc395befb648f1e48c6af6edfc9f8a10b3f3e/modules/apps/web-experience/asset/asset-test/src/testIntegration/java/com/liferay/asset/search/test/AssetSearcherStagingTest.java#L258

```
DeleteAfterTestRunTestCallback.afterMethod 
→ ModelListenerException: Unable to delete the process configuration for background task

caused by

com.liferay.exportimport.internal.model.listener.BackgroundTaskModelListener.onBeforeRemove 
→ NoSuchUserException: No User exists with the primary key
```

Could be related to local staging being enabled mid test? I noticed notifications being generated for the Test user.

https://github.com/arboliveira/liferay-portal/blob/996fc395befb648f1e48c6af6edfc9f8a10b3f3e/modules/apps/web-experience/asset/asset-test/src/testIntegration/java/com/liferay/asset/search/test/AssetSearcherStagingTest.java#L108

### CODE REVIEW

**Comment by yuhai** [comment]
Hi @arboliveira

Thanks for the detailed explanation regarding the fix. It works for me. 

Regards,
Hai

**Comment by yuhai** [comment]
ci:reopen

**Comment by yuhai** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
