### PR TITLE
LPS-196431 Move structure_about_us_section.json and tree.png

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:reopen

**Comment by ling-alan-huang** [comment]
Hey @MarinhoFeliphe @thaiscabrals Please see: https://github.com/ling-alan-huang/liferay-portal/pull/2438#issuecomment-1908612650

**Comment by MarinhoFeliphe** [comment]
Hello @ling-alan-huang, I'll take a look

**Pull request merged**
