### PR TITLE
LPS-76626

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by petershin** [comment]
@hhuijser 

When localization is enabled, SB creates a table called: `[$NAMESPACE$]_[$ENTITY_NAME$]Localization`

An example of a bad entity name is [`CampaignsEntry`](https://github.com/liferay/com-liferay-osb-faro-private/blob/7.0.x-private/osb-faro-campaigns-service/service.xml#L7-L36) which creates a table called `OSBFaro_CampaignsEntryLocalization`.  I think the `CampaignsEntry` name makes sense and I'm not sure what the devs would rename it to.

Several other subrepos have table names that exceed the 30 character limit and it seems like there haven't been any issues.

Would you recommend disabling this check for the affected subrepos?

**Comment by hhuijser** [comment]
@peterhin, the issue only occurs on Oracle. It would be interesting to test those subrepos with longer names on Oracle. Do you have bandwidth to look into that?

**Comment by petershin** [comment]
@hhuijser - Sure, will take a look and follow up with you  I'll disable the check for just the affected subrepos for now.  Let me know if you want me to hold off on disabling the check.

**Comment by hhuijser** [comment]
@petershin, sounds good. This pull should be good then.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
