### PR TITLE
LPS-93307 Recursively deploying demo-data-creator dependencies

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@4lejandrito please send these to @petershin

You have 2 afterEvalute and the code doesnt look consisten. I'm pinging @petershin this time.

Thx!

**Comment by 4lejandrito** [comment]
Ho @brianchandotcom,

Could you please merge the first commit then? It will be very useful for our front end devs tomorrow. 

I had a chat with @petershin and he will look into the second one in a few days when he has time. We can wait for that one.

Thanks!

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@4lejandrito this is too strange to merge in...

That marker file

modules/apps/users-admin/users-admin-api/.lfrbuild-portal

Tells portal that on "ant all" to deploy this.

modules/apps/users-admin/users-admin-demo
modules/apps/users-admin/users-admin-demo-data-creator-api

Do not have that file.

If I check in your build.gradle change, I'm essentially adding that marker file to all demo's. I don't know what ramification that will have when you run ci: test

If this is the behavior you want, then simply add the marker files in those directories, and then run a full ci: test in a branch and make sure it doesn't kill all frontend tests.

@petershin fyi

**Comment by 4lejandrito** [comment]
Hey @brianchandotcom,

I'm talking about https://github.com/brianchandotcom/liferay-portal/commit/f41a6c3aa26e10cafc127d97106aa00839a96b9b. I'm not adding any marker files there...

**Comment by 4lejandrito** [comment]
I resent that single commit in https://issues.liferay.com/browse/LPS-93307 to avoid confusion.

**Pull request closed without merging**
