### PR TITLE
LRQA-18824

### PR DESCRIPTION
**Pull request by pyoo47**
Resend of https://github.com/brianchandotcom/liferay-portal/pull/38084

https://issues.liferay.com/browse/LRQA-18824

We are implementing a new way to retrieve the build urls of downstream projects that does not rely on the shared drive. Using the shared drive has proven to be unreliable.

### CODE REVIEW

**Comment by kenjiheigel** [comment]
This appears to be an inconsistent failure after looking at the testray results for this test. It appears to be related to the SPA loading for too long, but we're not sure under what circumstances this occurs. We'll need to look into this more, but it seems that those failures are not related to this pull.

**Comment by pyoo47** [comment]
ci:retest

**Comment by sharonchoi** [comment]
Poshi failures should be fixed by https://github.com/brianchandotcom/liferay-portal/pull/38695

**Comment by pyoo47** [comment]
ci:retest

**Pull request closed without merging**
