### PR TITLE
LPS-86705

### PR DESCRIPTION
**Pull request by petershin**
@david-truong

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@mtambara see UserLocalServiceTest.testGetGroupUsers

Is that from your arquillian change?

**Comment by brianchandotcom** [comment]
Merged. Thank you.

**Comment by brianchandotcom** [comment]
@petershin @david-truong see my changes in 5d0950fc31f1734a5bfd4f145f23b3895d77ee44

**Comment by mtambara** [comment]
@brianchandotcom That wasn't me, looks like UserLocalServiceTest was failing before my changes went in

**Pull request closed without merging**
