### PR TITLE
LPS-98866 Do no print traces for upgrades twice

### PR DESCRIPTION
**Pull request by achaparro**
Hi @marianoalvarosaiz,

Thanks for the implementation of this because it's really complex. It was trying to understand the logic regarding the appender a few days ago and it was really hard. With your changes and the useful comments for every commit it has been much easier.

I have kept the pull as it was except three things:
- I have removed the new commands for the ReleaseManager. At least right now we don't want users to be able to select the ouput. Upgrades are already quite complext now and it's better to simplify API. We have it for verifiers and in four years I haven't heard someone using it.
- I prefer to call the upgradeExecutor [here](https://github.com/brianchandotcom/liferay-portal/pull/78649/commits/9df8f8786cd1f826d49ff792ad9ad86bcbe7feb9#diff-6fb597ad8065ce8ab63bb5eb49acd6eaR179) because we already have the upgradeInfos and it's better to keep the ReleaseManager commands only for manual executions from Gogo Console.
- I have tried to simplify [this API](https://github.com/brianchandotcom/liferay-portal/pull/78649/commits/c58f688edbbb863c535e20c1e7fb00f6f25245e9) because the UpgradeExecutor is enough complex now :-(

Please, let me know if you consider any of my assumptions wrong.

I have tested the pull in different ways and it seems to work, but, can you keep an eye for any regression and issue that can arise? I will be on vacation for two weeks and I won't be able to check it. If @brianchandotcom ask for any change, please, send directly to him.

Thanks again!

cc/ @Preston-Crary

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
Reviewed. No unique failures.

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by brianchandotcom** [comment]
@achaparro can you resend this when you're back from vacation, and send it first to @preston-crary or @shuyangzhou?  They're in the office, so you can talk to them about it too. Thx!

**Comment by marianoalvarosaiz** [comment]
see https://github.com/shuyangzhou/liferay-portal/pull/8330

**Pull request closed without merging**
