### PR TITLE
master-lps-60985

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LPS-60985

### CODE REVIEW

**Comment by evannagayama** [comment]
data-qa-id-content

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchiu** [comment]
@evannagayama 
See the poshi failures. All of them happen because they can't find the search button.

**Comment by evannagayama** [comment]
@brianchiu ah yeah because they haven't all been changed to lexicon. I'll put the old path back as an option. Thanks

**Pull request closed without merging**
