### PR TITLE
LPS-65946 We're evolving the schema, your services should depend on the proper version

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
@adolfopa it looks like this pull may have broken portal instances, see [this result](https://testray.liferay.com/home/-/testray/case_results/46615816?_1_WAR_testrayportlet_redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fruns%2F46615516%2Fdetails%3F_1_WAR_testrayportlet_testrayRunId%3D%26_1_WAR_testrayportlet_filterAssignedUserId%3D-1%26_1_WAR_testrayportlet_filterErrors%3D%26_1_WAR_testrayportlet_filterErrorsBlankOnly%3D%26_1_WAR_testrayportlet_filterIssues%3D%26_1_WAR_testrayportlet_filterIssuesBlankOnly%3D%26_1_WAR_testrayportlet_filterStatus%3D3%26_1_WAR_testrayportlet_filterName%3D%26_1_WAR_testrayportlet_filterPriority1%3Dfalse%26_1_WAR_testrayportlet_filterPriority2%3Dfalse%26_1_WAR_testrayportlet_filterPriority3%3Dfalse%26_1_WAR_testrayportlet_filterPriority4%3Dfalse%26_1_WAR_testrayportlet_filterPriority5%3Dfalse%26_1_WAR_testrayportlet_filterTestrayComponentId%3D-1%26_1_WAR_testrayportlet_testrayComponentId%3D%26_1_WAR_testrayportlet_tabs1%3Dall-cases%26_1_WAR_testrayportlet_cur%3D1%26_1_WAR_testrayportlet_delta%3D75%26_1_WAR_testrayportlet_keywords%3D%26_1_WAR_testrayportlet_advancedSearch%3Dfalse%26_1_WAR_testrayportlet_andOperator%3Dtrue%26_1_WAR_testrayportlet_orderByCol%3DstatusLabel%26_1_WAR_testrayportlet_orderByType%3Dasc), as the links above are broken

**Comment by kenjiheigel** [comment]
Looks like this error is being thrown: 
`Table 'lportal.SN_WallEntry' doesn't exist`

Here's the full stacktrace:
https://gist.github.com/kenjiheigel/55544ab97cccec48a738505923c99ca6

Steps to reproduce:
1. Add a portal instance
2. Delete the portal instance.

**Comment by brianchandotcom** [comment]
@adolfopa please resend. Thx.

**Pull request closed without merging**
