### PR TITLE
LRQA-62358 Expand existing license test batch to also smoke test Commerce

### PR DESCRIPTION
**Pull request by vicnate5**
Adds automation coverage on CI for the Commerce license activation. @tinatian @marco-leo @iovaneale

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:reopen

**Comment by vicnate5** [comment]
Also needed on 7.3.x

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c9d535a9be...af2be6bd6c

**Comment by brianchandotcom** [comment]
@vicnate5 I backported this to 7.3.x.

**Pull request closed without merging**
