### PR TITLE
LPS-84204 Having a staged site with web content is unstaged, missing references to a JournalArticle to that site doesn't work fine

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by jkappler** [comment]
@jpince, @brianchiu, this error is not happening in local master, can be from CI?

**Comment by jpince** [comment]
@jkappler yes, this is a known issue, sorry about this.

**Pull request closed without merging**
