### PR TITLE
LPS-55754 Extract Journal Tests to module

### PR DESCRIPTION
**Pull request by epgarcia**
All non-generated Journal Tests and all other tests that depend on Journal Services to add test data (LAR and Staging) are extracted into modules.

Generated tests (persistence) will be extracted alongside Journal Services next.

@juliocamarero
@matethurzo

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest (so random...)

**Comment by epgarcia** [comment]
ci:retest

**Comment by epgarcia** [comment]
ci:retest

**Pull request closed without merging**
