### PR TITLE
LPS-85765 Fix artifact url

### PR DESCRIPTION
**Pull request by petershin**
@CAustin582

### CODE REVIEW

**Comment by petershin** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cb03aa362d...5276299919

**Comment by brianchandotcom** [comment]
@petershin I backported this all the way to 7.0.x

**Comment by felix3508** [comment]
@brianchandotcom could you please apply this fix to 7.4.13.u15 branch? There is a bom build problem, see https://liferay.slack.com/archives/C01J8FA29NE/p1646635636127979

**Pull request closed without merging**
