### PR TITLE
LPS-97345 Avoid reinitialization of Charon with every HTTP request

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Hi Brian. Here's the fix we discussed to avoid unnecessary Charon reinitialization.

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1307548eda...2a9ee70c14

**Comment by brianchandotcom** [comment]
@stian-sigvartsen I'm not sure if we need tto account for the referencesr eloading dcb123da70c70008d40405c2126e3bd07ff990bc

@shuyangzhou can you take a look at this PR and my change? In origin.

**Comment by shuyangzhou** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/11301

**Pull request closed without merging**
