### PR TITLE
LPS-86717 Unable to retrieve request in serviceContext at service layer

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-86717](https://issues.liferay.com/browse/LPS-86717).<br><br>/cc @pei-jung @stsquared99 @alee8888

### CODE REVIEW

**Comment by drewbrokke** [comment]
cc @arthurchan35 @hhuijser

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5293410046...1331f53815

**Comment by brianchandotcom** [comment]
See 1331f53815030533347b8c79d752b0717facb535

**Comment by brianchandotcom** [comment]
@arthurchan35 please backport. Thx.

**Pull request closed without merging**
