### PR TITLE
LPS-60332 Apply Lexicon to AlloyEditor controls bar

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @sharonchoi, could you take a look at the failing poshi test? The button has the same id, so not sure what's making it fail...

**Comment by sharonchoi** [comment]
@jbalsas ok will do.

**Comment by brianchandotcom** [comment]
@sharonchoi please resend. Thx.

**Comment by sharonchoi** [comment]
@jbalsas @brianchandotcom resent here: https://github.com/brianchandotcom/liferay-portal/pull/33799

**Pull request closed without merging**
