### PR TITLE
OAUTH2-122 Admin portlet (part 1 of 2) resent 2

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Hi Brian. 

Discussed `ClientProfile` with @topolik again and agreed that it is a constant class, `GrantType` enum is already in the same `.constant` package. 

Can you please suggest an alternative if it is not acceptable?

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
Test failures unrelated

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8140153065...72423c13aa

**Comment by brianchandotcom** [comment]
@stian-sigvartsen ok, constant it is! Thanks guys. Please see my tiny changes in usptream. Thx.

**Comment by stian-sigvartsen** [comment]
Thanks @brianchandotcom . We're so very nearly there :)

**Pull request closed without merging**
