### PR TITLE
LPS-56944

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@mhan810 I assume order matters?

```
<util:constant static-field="com.liferay.portal.kernel.transaction.TransactionLifecycleNotifier.TRANSACTION_LIFECYCLE_LISTENER" />
				<util:constant static-field="com.liferay.portal.kernel.transaction.TransactionCommitCallbackUtil.TRANSACTION_LIFECYCLE_LISTENER" />
```

since that is not sorted.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8805cb6577...98ac32c93d

**Comment by mhan810** [comment]
Yep it matters



*From:* Brian Chan [mailto:notifications@github.com]
*Sent:* Wednesday, July 8, 2015 4:30 PM
*To:* brianchandotcom/liferay-portal
*Cc:* Michael Han
*Subject:* Re: [liferay-portal] LPS-56944 (#28087)



@mhan810 <https://github.com/mhan810> I assume order matters?

<util:constant static-field="com.liferay.portal.kernel.transaction.TransactionLifecycleNotifier.TRANSACTION_LIFECYCLE_LISTENER"
/>

                <util:constant
static-field="com.liferay.portal.kernel.transaction.TransactionCommitCallbackUtil.TRANSACTION_LIFECYCLE_LISTENER"
/>

since that is not sorted.

—
Reply to this email directly or view it on GitHub
<https://github.com/brianchandotcom/liferay-portal/pull/28087#issuecomment-119735857>
.

**Pull request closed without merging**
