### PR TITLE
LPS-103290

### PR DESCRIPTION
**Pull request by dejuknow**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5881f27d70...9958c46a83

**Comment by brianchandotcom** [comment]
@dejuknow I ported this all the way back to 7.0.x

**Comment by brianwulbern** [comment]
@brianchandotcom this pull has an error related to the change:
```
 [java] org.osgi.framework.BundleException: Could not resolve module: com.liferay.sync.service [702]
     [java]   Unresolved requirement: Import-Package: junit.framework
```

**Comment by brianchandotcom** [comment]
@dejuknow reverted for now.. I think you need to compileInclude junit or explicitly not include it in a list of dependencies (in bnd.bnd do an exclude of a package)

**Comment by brianchandotcom** [comment]
@dejuknow @brianwulbern see 

modules/apps/comment/comment-sanitizer/bnd.bnd

```
Import-Package:\
	!javax.annotation,\
	\
	!sun.misc,\
	\
	*
```

Something like that , but !junit.framework should fix it

**Pull request closed without merging**
