### PR TITLE
LPS-91859 Inline what's not reused

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7723298d2a...f539a22973

**Comment by brianchandotcom** [comment]
@victorlaerte @jeyvison @brunofarache please see my changes in upstream (I made quite a few. Bruno will be shocked, but Jeyvison will remember it was exactly what I similar to what I did for him a few weeks ago).

@victorlaerte I'm fairly sure broke this, but I wanted to name things very carefully:

```
		List<String> ddmFormFieldNames = Stream.of(
			ddmFormLayoutPage.getDDMFormLayoutRows()
		).flatMap(
			Collection::stream
		).map(
			DDMFormLayoutRow::getDDMFormLayoutColumns
		).flatMap(
			Collection::stream
		).map(
			DDMFormLayoutColumn::getDDMFormFieldNames
		).map(
			nestedDDMFormFieldNames -> _getNestedDDMFormFieldNames(
				nestedDDMFormFieldNames, ddmStructure)
		).flatMap(
			Collection::stream
		).collect(
			Collectors.toList()
		);
```

and

```
		return stream.filter(
			ddmFormField -> ddmFormFieldNames.contains(ddmFormField.getName())
		).map(
			ddmFormField -> transform(
				ddmFormField.getNestedDDMFormFields(),
				nestedDDMFormField -> nestedDDMFormField.getName())
		).map(
			nestedDDMFormFieldNames -> _getNestedDDMFormFieldNames(
				nestedDDMFormFieldNames, ddmStructure)
		).peek(
			nestedDDMFormFieldNames -> nestedDDMFormFieldNames.addAll(
				ddmFormFieldNames)
		).flatMap(
			Collection::stream
		).collect(
			Collectors.toList()
		);
```

I did not want to use formFieldName and ddmFormFieldName to mean different things. So I renamed one to nestedDDMFormFieldName, but I'm fairly sure I did it wrong. But it should be very easy for you to fix @victorlaerte 

Please send me a follow up pull @victorlaerte. Thx!

@jeyvison we need to start adding more tests.

**Comment by victorlaerte** [comment]
@brianchandotcom As soon as I finish my current task I'll go back to fix it. Thanks!

**Comment by victorlaerte** [comment]
@brianchandotcom just to understand, what were the criteria to use the set method for some attributes and direct attribution for others?

**Pull request closed without merging**
