### PR TITLE
Lps 68956

### PR DESCRIPTION
**Pull request by shuyangzhou**
@brianchandotcom this is the "portal compact" thing we talked a while ago for blogs' osgi extraction. With this, all blogs' deprecated code are moved out of portal-kernel/portal-impl into their own compact jars. From baseline point of view nothing really changes. Just jars got break down into pieces.

We added an ASM processing before packaging the compact jar. The process wipes out all business logic in the deprecated classes. We do this to reduce the dependencies from the deprecated code to the rest of the system, this will significantly lower the chance we run into unexpected breaking dependencies while refactoring the rest of the system in the future. Since we only wipe the method bodies, it is totally backward compatible from baseline's point of view. And this can also ensure all calls to old services are redirected to osgi services by those modular service wrappers, because if we missed anything, the ASMed classes will throw UnsupportedException right away to highlight the breaking bridges.

The only thing left for blogs in portal is the com.liferay.portlet.blogs.dependencies in portal-impl, it is not osgi related, and they are template files for settings. I will leave that to blogs or settings teams to clean up.

This should be good enough to be used as the template for all future osgi extraction process to follow, which allows us to move things out after releases in a backward compatible way.

Thanks @Ithildir for the gradle helps!

CC @mhan810 @sergiogonzalez

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest (not sure if smoke test for lpkg-startup is real or not)

**Comment by shuyangzhou** [comment]
@brianchandotcom this pull is fine, CI is loaded and aborting tests.

**Comment by shuyangzhou** [comment]
ci:retest

Look CI is off load now

**Comment by brianchandotcom** [comment]
Merged. Thank you.

**Comment by brianchandotcom** [comment]
@shuyangzhou portal-impl-compat/.lfrbuild-app-server-lib should not be there. It should go in ROOT/WEB-INF/lib like portal-impl.jar and not portal-kernel.jar. Can you send me a follow up pull?

@Ithildir can you review what is in upstream? What is .lfrbuild-releng-ignore for?

See build.properties and references to "1.0.0" jars. If we ever release / upload the compat jars, can you update build.gradle to auto update that file? See classpath.portal-impl-integration

Thx guys!

**Comment by brianchandotcom** [comment]
@tomwang2011 can you also send a backport to ee-7.0.x? Obviously, we don't need the actual changes to the blogs module, but I'd like everything else backported. I backported 7da670a75c26c293973cab057790172cd496bb18.

**Comment by Ithildir** [comment]
Sent at https://github.com/brianchandotcom/liferay-portal/pull/44750.

**Pull request closed without merging**
