### PR TITLE
LPS-74704 Site Role permissions on Global entries

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-74704](https://issues.liferay.com/browse/LPS-74704).<br><br>/cc @pei-jung, @ealonso, @cleydyr

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by drewbrokke** [comment]
ci:retest

**Comment by drewbrokke** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/aa81322721...052fedb9e2

**Pull request closed without merging**
