### PR TITLE
LPS-56669

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@mhan810 I noticed the service tracker change for TransactionLifecycleManager, it could potentially cause some problem, although in this case it should be fine.

The problem is, all TransactionLifecycleListener must run in certain orders, see base-spring.xml for bean "com.liferay.portal.transaction.TransactionLifecycleManagerInitializer", for example com.liferay.portal.spring.hibernate.LastSessionRecorderUtil.TRANSACTION_LIFECYCLE_LISTENER has to run before com.liferay.portal.kernel.cache.transactional.TransactionalPortalCacheHelper.TRANSACTION_LIFECYCLE_LISTENER which is a bug I just fixed in https://issues.liferay.com/browse/LPS-56352 at https://github.com/liferay/liferay-portal/commit/7fe730f94c6baa4c77c17cba0fb33ce7fb72059f

If we expose a service tracker for this, people might add in more TransactionLifecycleListener quietly in the future from modules, causing similar problems, which will be very difficult for figuring out the reason.

**Comment by mhan810** [comment]
ci:retest

**Comment by mhan810** [comment]
@brianchandotcom, Shuyang and I talked about it. This pr can go so that we
unblock the staging triage team. I'll go back and update the transaction
listener to remove the service tracker later this wk

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/47833a5a9b...6bee2b117a

**Pull request closed without merging**
