### PR TITLE
LPS-71624 It's probably better to return VARCHAR rather than null here if "String" is passed in

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by mbowerman** [comment]
What? What is that commit? That's not something I added

**Comment by mbowerman** [comment]
ci:reopen

**Comment by mbowerman** [comment]
@rotty3000 Please remove that weird commit and resubmit. Thanks.

**Comment by rotty3000** [comment]
ah sorry, strange that some of my WIP got mixed in..

**Comment by rotty3000** [comment]
ci:retest

**Pull request closed without merging**
