### PR TITLE
LPD-24967: Review & adapt tests using hard-coded test password - integration and POSHI tests in Headless

### PR DESCRIPTION
**Pull request by sergiojimcos**
**JIRA Related Ticket**
https://liferay.atlassian.net/browse/LPD-24967

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:reopen

**Comment by sergiojimcos** [comment]
Forwarded from: https://github.com/liferay-headless/liferay-portal/pull/2030

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3f0f7250cc...3e12708e08

**Comment by brianchandotcom** [comment]
@GaborKomaromi @sergiojimcos see 3e12708e

**Pull request closed without merging**
