### PR TITLE
LPS-79327 Extend tests

### PR DESCRIPTION
**Pull request by epgarcia**
Fixes the broken tests and extends the Meris API.

@juliocamarero
@JorgeFerrer
@mhan810

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:test

**Comment by epgarcia** [comment]
@brianchandotcom I think these test fails are not related to my changes.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a3b8be101f...f1f2531fe8

**Comment by brianchandotcom** [comment]
@epgarcia please see my changes in upstream.

I also moved meris into foundation. I'll have to do the same for analytics in order to fix https://github.com/liferay/liferay-portal/commit/22c81703aa66fdc7fbd023faaf9e0e348f579089#commitcomment-28574093

I'll do the latter hopefully later today. Thx.

**Pull request closed without merging**
