### PR TITLE
LPS-67027

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-67027.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by kenjiheigel** [comment]
@jonmak08, @brianchandotcom, this broke the functional tests for custom fields. 

CPCustomfields#AddCustomFieldUserBoolean
CPCustomfields#EditCustomFieldUserBoolean

**Comment by kenjiheigel** [comment]
Will send a test fix under this LPS.

**Comment by kenjiheigel** [comment]
Test fix sent here:
https://github.com/brianchandotcom/liferay-portal/pull/44025

**Pull request closed without merging**
