### PR TITLE
Lps 65693 integrity check

### PR DESCRIPTION
**Pull request by shuyangzhou**
@brianchandotcom with this pull, we have 2 more pieces left.

1) Putting index info into lpkg, I can add it in tomorrow.

2) We have a bug here, a major one, maybe @rotty3000 can help on this.
The target platform indexing is broken, as a matter of fact, it has never truly worked. The build time indexing is not complete, it misses a lot info(luckily those missing info are not really required by lpkgs, so they can still resolve).

But it is an issue now, because we need this integrity check to speed up startup. The build time generated target platform index does not match the runtime generated one. So it will force a runtime validation on the 1st bootup.

A workaround could be, in the packaging process, we bootup portal once, then capture the generated integrity.properties, rather than using the build time generated one.

@rotty3000, I am fairly certain, the difference only comes from system bundle capabilities capturing. The runtime one has a lot more than the command line one. I think it is due to we configure the framework differently. We have to make sure the command line one is outputting exactly the same thing as the runtime one to enable this build time integrity.properties generation. Can you do some digging on this?

CC @mhan810 @jhendley

### CODE REVIEW

**Comment by rotty3000** [comment]
@shuyangzhou you'll have to explain this to me more clearly.

**Comment by jpince** [comment]
@brianchandotcom no functional test failures

**Comment by pyoo47** [comment]
One of the tests froze and timed out due to the Freemarker taglib error.

**Comment by rotty3000** [comment]
the statement that the target platform indexing never worked is just plain
wrong!

**Comment by shuyangzhou** [comment]
Sorry, I only meant the the target platform indexing is not matching the runtime one, it does resolve everything else. I just don't know whether the missing pieces are important or not.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/91412cf83f...e10eb55bcd

**Pull request closed without merging**
