### PR TITLE
Fix ModulesStructureTest

### PR DESCRIPTION
**Pull request by Ithildir**
cc @kenjiheigel

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pyoo47 @Ithildir what happened here?

**Comment by Ithildir** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
@brianchandotcom @Ithildir, this is caused by a missing property in liferay-jenkins-ee. Will retest this once the jenkins changes are made.

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@kenjiheigel done.. my bad.

**Pull request closed without merging**
