### PR TITLE
LPS-105237 remove siteId from GraqhQL

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:test:sf

**Comment by nhpatt** [comment]
ci:test:sf

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e9a9b1025f...c524766124

**Comment by nhpatt** [comment]
Thanks!

**Comment by brianchandotcom** [comment]
@nhpatt backported.

**Pull request closed without merging**
