### PR TITLE
LRQA-25483 Consolidate the different usages of 'output.dir.name'

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRQA-25483

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6e03af71a7...47aca5e8e9

**Comment by kenjiheigel** [comment]
@michaelhashimoto @pyoo47, those three tests still fail with the taglib issue: 
https://gist.github.com/kenjiheigel/7d22ef1380216e5b06dac45d748ad780

It looks like it waited for Portal to start up (with the new changes to wait for the start up message) then in the process of it waiting for portal to be ready, the errors were thrown. Maybe this was triggered by the waitfor task?

**Comment by pyoo47** [comment]
I don't think so because the waitfor task doesn't start pinging portal until after the Portal startup message is found in the log.

**Comment by kenjiheigel** [comment]
Yeah, that's what's strange in the error output (I shortened the full error below). The server starts up fine (based on the message). Then it waits for the URL. The error doesn't happen til after the server starts and happens within https://github.com/liferay/liferay-portal/blob/master/build-test.xml#L3286-L3328  

     [exec] 25-May-2016 19:44:01.614 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 249052 ms
     [delete] Deleting: /opt/dev/projects/github/liferay-portal/app-server-log
     [echo] Waiting for http://localhost:8080/web/guest to load
     [exec] 19:44:12,731 ERROR [http-nio-8080-exec-1][FreeMarkerManager:193] Unable to add taglib liferay_product_navigation to context
     [exec] FreeMarker template error:
     [exec] freemarker.template.TemplateModelException: Error while loading tag library for URI "/META-INF/liferay-product-navigation.tld" from TLD location "servletContext:/META-INF/liferay-product-navigation.tld"; see cause exception.
     [exec] 	at freemarker.ext.jsp.TaglibFactory.get(TaglibFactory.java:260)
     ...
     [exec] Caused by: java.io.IOException: Resource not found: servletContext:/META-INF/liferay-product-navigation.tld
     [exec] 	at freemarker.ext.jsp.TaglibFactory$ServletContextTldLocation.newResourceNotFoundException(TaglibFactory.java:1249)
     [exec] 	at freemarker.ext.jsp.TaglibFactory$ServletContextTldLocation.getInputStream(TaglibFactory.java:1238)
     [exec] 	at freemarker.ext.jsp.TaglibFactory$Taglib.parseToTagsAndFunctions(TaglibFactory.java:1505)
     [exec] 	at freemarker.ext.jsp.TaglibFactory$Taglib.<init>(TaglibFactory.java:1490)
     [exec] 	at freemarker.ext.jsp.TaglibFactory.loadTaglib(TaglibFactory.java:846)
     [exec] 	at freemarker.ext.jsp.TaglibFactory.get(TaglibFactory.java:256)
     [exec] 	... 248 more
     [echo] http://localhost:8080/web/guest has loaded

**Pull request closed without merging**
