### PR TITLE
LPS-51819

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-51819](https://issues.liferay.com/browse/LPS-51819).<br><br>These are the commits adding a new method to the ListTypeService

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by drewbrokke** [comment]
@natecavanaugh, @JorgeFerrer, @pei-jung

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2b136d514d...b7a5e0497e

**Comment by brianchandotcom** [comment]
@drewbrokke @pei-jung please see my changes in upstream. Thx.

**Pull request closed without merging**
