### PR TITLE
LPS-85785 baseline

### PR DESCRIPTION
**Pull request by jeyvison**
although CI marked the failure in https://github.com/brianchandotcom/liferay-portal/pull/76471 as unique, it's happening for a long time in upstream so it's not caused by this PR.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jeyvison @IstvanD any way to do this without a breaking change to DDM?

**Comment by IstvanD** [comment]
Hi @brianchandotcom 

Due to the complexity of the issue, we couldn't come up with a solution that doesn't introduce API changes.
Before starting implementing, I raised a [PTR ticket](https://issues.liferay.com/browse/PTR-895) to discuss two alternatives with the SME, and we agreed that the current solution would be the most feasible.

Do you think the other approach would be better?

Thank you and best regards,
István

**Comment by IstvanD** [comment]
I'm including @jeyvison into the discussion.

**Comment by jeyvison** [comment]
Hi @IstvanD. He doesn't read the comments here after the PR is closed. I'll send it again and you can comment in the new PR

**Comment by IstvanD** [comment]
I see.
Thank you very much, @jeyvison !

**Pull request closed without merging**
