### PR TITLE
LPS-52222 apply Configuration UI to IP Geocoder Module

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@rotty300 Note that Julio did a mass change that undid your change a few days ago to all modules to make *Configuration follow get/set/is. He removed them all so it looks better in the UI. I think Julio is actually right.

@juliocamarero I published a snapshot for 1.0.2

**Comment by brianchandotcom** [comment]
@rotty3000 Note that Julio did a mass change that undid your change a few days ago to all modules to make *Configuration follow get/set/is. He removed them all so it looks better in the UI. I think Julio is actually right.

@juliocamarero I published a snapshot for 1.0.2

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/350b2796bc...ed05083a24

**Pull request closed without merging**
