### PR TITLE
LPS-105628 Fix tests

### PR DESCRIPTION
**Pull request by victorg1991**
@ealonso

### CODE REVIEW

**Comment by victorg1991** [comment]
rebased :)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a2813d27c5...8ada62a590

**Comment by brianchandotcom** [comment]
Merged.. should we fix this?

String parentItemId = ParamUtil.getString(actionRequest, "parentId");
String itemType = ParamUtil.getString(actionRequest, "type");

**Comment by brianchandotcom** [comment]
@wincent please fix test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8

**Comment by wincent** [comment]
Fix was: https://github.com/brianchandotcom/liferay-portal/pull/82223

**Pull request closed without merging**
