### PR TITLE
Lps 206285

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
Follow up, styles format fixed: https://github.com/brianchandotcom/liferay-portal/pull/146701#issuecomment-1914336059

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:open

**Comment by georgel-pop-lr** [comment]
ci:reopen

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@georgel-pop-lr this looks wrong?

```
const COMMON_CSS_STYLE = `
			.lfr-layout-structure-item-container {
				padding: 0;
			}
			
			.lfr-layout-structure-item-row { 
				overflow: hidden;
			}
			
			.portlet-borderless .portlet-content{
				padding: 0;
			}`;
```

**Pull request closed without merging**
