### PR TITLE
LPS-99231 Only log folder name validation during import

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/27b83321dd...c1a7c301d7

**Comment by brianchandotcom** [comment]
@jkappler see c1a7c30

**Comment by brianchandotcom** [comment]
@balazssk @jkappler see c1a7c301d7637bcfc45c3361f80c2501d205861a

**Pull request closed without merging**
