### PR TITLE
LPS-179883 Copy permissions on the new page when a Page is created with Copy Page

### PR DESCRIPTION
**Pull request by alessandromalves**
[Link to the story](https://issues.liferay.com/browse/LPS-177031)

### Motivation
Copy permissions on the new page when a Page is created with Copy Page

### Proposed Solution
Extract copy page to the api with copy permissions
Add new dropdown item contextual to use it in the item list of actions.

### Steps to Verify:
Open the Site Builder
Create a new Blanck Page called Page 1
Publish Page 1
Click on One Page Options Menu -> Permissions
Remove all the permissions for Guest
Click on One Page Options Menu -> Copy Page with Permissions
Name new page as Page 2
Verify that new permissions are similar to the copied page

### Notes
Integration test included.

cc.: @Mikellorza @ruben-pulido

### CODE REVIEW

**Comment by alessandromalves** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/11594

:x: ci:test:stable - 26 out of 27 jobs passed
:x: ci:test:relevant - 261 out of 303 jobs passed in 3 hours 11 minutes

**Comment by alessandromalves** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1781b9cb8e...df93e4284d

**Comment by brianchandotcom** [comment]
@Mikellorza @alessandromalves 

Can you send a follow up PR and update all the older patterns

```
	@Override
	public LayoutPageTemplateEntry copyLayoutPageTemplateEntry(
			long userId, long groupId, long layoutPageTemplateCollectionId,
			long layoutPageTemplateEntryId, ServiceContext serviceContext)
		throws Exception {
```

Notice how this is

long layoutPageTemplateEntryId

and not 

long sourceLayoutPageTemplateEntryId

Anywhere we have the method "copy" in a ServiceImpl should follow your new pattern.

Thx!

**Pull request closed without merging**
