### PR TITLE
LPS-85145

### PR DESCRIPTION
**Pull request by david-gutierrez-mesa**
cc/ p2kmgcl

### CODE REVIEW

**Comment by david-gutierrez-mesa** [comment]
Send directly since failing tests are not related.

✔️ ci:test:sf - 1 out of 1 jobs passed in 6 minutes
Click here for more details.
Base Branch:
Branch Name: [master](https://github.com/liferay/liferay-portal/tree/master)
Branch GIT ID: [aa708f440f00d3ed3f4b819036b8a8b30b6f2e31](https://github.com/liferay/liferay-portal/commit/aa708f440f00d3ed3f4b819036b8a8b30b6f2e31)

Sender Branch:
Branch Name: [pr/liferay-echo/10687](https://github.com/p2kmgcl/liferay-portal/tree/pr/liferay-echo/10687)
Branch GIT ID: [65a0ad62b68c3f70963b1514a853fa7e11f0c945](https://github.com/p2kmgcl/liferay-portal/commit/65a0ad62b68c3f70963b1514a853fa7e11f0c945)

1 out of 1jobs PASSED
1 Successful Jobs:
For more details click [here](https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/4422/jenkins-report.html).

**Comment by david-gutierrez-mesa** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/137677586b...f2222dee0a

**Comment by brianchandotcom** [comment]
@victorg1991  I temporarily reverted 13767758 and recomitted it in f2222dee to avoid the rebase errors in this PR

@p2kmgcl fyi

**Pull request closed without merging**
