### PR TITLE
LPS-84964 Fix Windows build

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@hhuijser can we SF enforce this? Thx.

**Comment by hhuijser** [comment]
@pedroqueiroz, what's the rule here? We shouldn't use single quotes in package.json?
What about these two:
https://github.com/liferay/liferay-portal/blob/master/modules/apps/analytics/analytics-client-js/package.json#L60
https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-web/package.json#L155

**Comment by pedroqueiroz** [comment]
Hey @hhuijser , I've followed the pattern of this commit: https://github.com/liferay/liferay-portal/commit/51a7bd08584c547ad6896b974110c6f38c3ecab8#diff-7603cee0b201a4202a31df645194cbaa.

I think @izaera and @jbalsas can answer your questions more properly.

Thanks, guys! :)

**Comment by jbalsas** [comment]
@izaera will remember better, but as far as I remember, it's just an issue about how the different OS shells explode and treat paths and globs...

We're working to simplify and generalize these now common build steps in Liferay Portal so we can deal with this from a single point.

**Comment by hhuijser** [comment]
@jbalsas @pedroqueiroz will leave things as is then, you guys figure it out :)

**Comment by izaera** [comment]
> as far as I remember, it's just an issue about how the different OS shells expand and deal with paths and globs...

Just to confirm that @jbalsas remembers it right 👍 :-)

**Pull request closed without merging**
