### PR TITLE
LPS-123758

### PR DESCRIPTION
**Pull request by hhuijser**
These did not get backported to 7.3.x

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
ci:test:sf

**Comment by hhuijser** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/13e8200594...6cbf0e73b1

**Pull request closed without merging**
