### PR TITLE
LPS-65125 Use default

### PR DESCRIPTION
**Pull request by shuyangzhou**
@brianchandotcom you need to publish com.liferay.portal.cache module to make the test work

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@shuyangzhou see 26cd548f7af6bdcbf1f78f789108333175d676c9

Is this a runtime requirement? At compile time, it didn't seem to need it?

**Comment by shuyangzhou** [comment]
Yes, it is a runtime requirement.

**Comment by brianchandotcom** [comment]
But if it's runtime.. changing build.gradle won't make a difference because that is a compile time thing?

**Comment by shuyangzhou** [comment]
It is an unit test failure, not integration test.

**Comment by brianchandotcom** [comment]
@shuyangzhou is it using reflection of some sort? My point is that it should still be a compile time failure and not a running unit test failure?

**Comment by shuyangzhou** [comment]
There was no api changes, only a method body logic change, so that with both old and new version, it compiles.

However, due to it is an unit test, it does not load its classpath from portal runtime, instead just using the compile time classpath(I think, at least debugger told me the unit test was using the jar version from build. gradle), so we have to make sure the compile classpath meets the need of unit tests behavior requirements.

**Comment by brianchandotcom** [comment]
Module compile time == good
Module run time == good

Unit test compile time == good
Unit test run time == bad

So that means unit test runtime must be using reflection? Otherwise, it would work. Right?

**Comment by shuyangzhou** [comment]
No, no reflections. Module runtime classpath is different from module unit classpath, that's the difference.

I will be in office in 5min, I will go talk to you.

**Pull request closed without merging**
