### PR TITLE
LPS-66063 Do not publish KB with DXP release

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by robertoDiaz** [comment]
cc / @sergiogonzalez

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/abb31ec8e4...2bd0ecf37e

**Comment by brianchandotcom** [comment]
@robertoDiaz see 2bd0ecf37ea843b03b0387df326ad2c86e301e87

**Pull request closed without merging**
