### PR TITLE
LPS-126295 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-126295

This is only for master.

@david-gutierrez-mesa
@alexcandidos

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure cases are unrelated to changes in PR.
See https://github.com/liferay-echo/liferay-portal/pull/3628
✔️ ci:test:stable - 9 out of 9 jobs passed
❌ ci:test:relevant - 22 out of 26 jobs passed in 4 hours 23 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/eec9bc6b98...eec9bc6b98

**Comment by brianchandotcom** [comment]
@brunoquei2105 Please review changes.

**Comment by brunoquei2105** [comment]
DataEngine.addfieldtoFieldGroup make more sense than DataEngine.addNestedField. Nice :) @Tim-Cao @brianchandotcom

**Pull request closed without merging**
