### PR TITLE
LPS-82998 update packageinfo

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:reopen

**Comment by izaera** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cdca0aff9a...c4659a155c

**Comment by brianchandotcom** [comment]
@izaera please see my changes in upstream. Thx.

**Pull request closed without merging**
