### PR TITLE
LPS-182093 Fix merge issue

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LPS-182093

Let stable finish running on this pull. If it's green, then it should fix the merge issues

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:reopen

**Comment by kenjiheigel** [comment]
ci:test:stable

**Comment by kenjiheigel** [comment]
ci:reopen

**Comment by kenjiheigel** [comment]
See result on https://github.com/kenjiheigel/liferay-portal/pull/1349

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/417691e994...417691e994

**Pull request closed without merging**
