### PR TITLE
LPS-99202 Set a relaxed range for fragment contributor

### PR DESCRIPTION
**Pull request by jkappler**
Hey @brianchandotcom, I don't like this too much, and have to find another way to solve this (I will most likely deprecate the base class). Any other change at this point would be a major or a braking change, and don't want to block fp1.

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by brianchandotcom** [comment]
@jkappler frontend tests broken?

**Comment by brianchandotcom** [comment]
ci:reopen nvm, I see another pull with it. But can we fix the poshi?

@jpince fyi

**Comment by jpince** [comment]
@kyle-miho see BChan's comment

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1d57562eb3...6ea7d2600c

**Comment by brianchandotcom** [comment]
@jkappler not ideal, but acceptable. I backported this to 7.2.x.

**Pull request closed without merging**
