### PR TITLE
LPS-84119

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
@petershin, SF failing here, but it's okay here: https://github.com/brianchandotcom/liferay-portal/pull/74962

**Comment by petershin** [comment]
@hhuijser - When a `source-formatter` file is touched, the `ci:test:sf` test behavior changes and it runs checks from all 3 formatters (`source-formatter`, `NPM`, and `Yarn`).

It looks like the `NPM` check failed and this may have been broken for awhile.  I think the `checkFormat` script from `package.json` needs to be changed or removed.  I'll check with Chema and Greg about it and may also send one pull to temporarily disable the `NPM` checks too.

```
P:\project\m\portal\modules\apps\analytics\analytics-client-js (11:20:34) [m-062604]
> cmd /c "P:\project\m\portal\build\node\node" "P:/project/m/portal/modules/yarn-1.13.0.js" "--production" "false" "run" "checkFormat" "--debug"
yarn run v1.13.0
$ liferay-npm-scripts check --debug
Checking formatting...
All matched files use Prettier code style!

Oops! Something went wrong! :(

ESLint: 5.16.0.
No files matching the pattern "{src,test}/**/*.es.js" were found.
Please check for typing mistakes in the pattern.
````

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
