### PR TITLE
LPS-64277 Remove source compat restriction

### PR DESCRIPTION
**Pull request by adolfopa**
@brianchandotcom This is the first in a series of pulls for KB. Here I'm moving the `markdown-converter` out of `util` so that it gets deployed automatically; As Knowledge Base is the only user of that module, putting it inside the `knowledge-base` group seems reasonable.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
@brianchandotcom, in case you haven't spotted it already. It appears the upgrade tests are failing due to: https://github.com/liferay/liferay-portal/commit/25dfe9953ff47b2c2c1a69c60edce291fd8df96b#diff-5754305bc7e1bf36376b1ec1d3d0f4baR396.

**Comment by brianchandotcom** [comment]
@kenjiheigel thx for the heads up.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/14ff163735...c76d85cbcb

**Comment by brianchandotcom** [comment]
Nice job @adolfopa :)

**Pull request closed without merging**
