### PR TITLE
[See Description] LPS-52968 - LPS-52591 Add links in Portlet Toolbars

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey Brian,

This pull includes 2 different LPS numbers: LPS-52968 creates a taglib (MenuTag) that is then used by   LPS-52591 to render items.

Please, see the commit log to see the purpose of the different classes.
1. PortletToolbar will be used by the theme templates to render the elements. Right now it only displays MenuItems although in the next pull it will also display a free HTML markup area. 
2. PortletToolbarContributor (I get the name from Eclipse project) will be implemented by the developers to contribute to the portlet toolbar by adding elements (menu items or html to the markup area)
3. PortletToolbarContributorLocator is in charge of locating the PortletToolbarContributor (we will provide a StrutsPortletToolbarContributorLocator and a MVCPortletToolbarContributorLocator)

Thanks!

BTW: I added 2 commits at the end to fix the tests :)

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/be1043adfe...a2756bab43

**Comment by brianchandotcom** [comment]
@sergiogonzalez please see my changes in upstream. Great job on this pull. It's very nice.

**Pull request closed without merging**
