### PR TITLE
LPS-62467 [Follow-up to fix a test] Fix clause. Collapsed equals !Extended

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Hey @brianchandotcom, this fixes the broken test in CI.

Thx!

**Comment by robertoDiaz** [comment]
cc /@sergiogonzalez @sharonchoi

**Comment by brianchandotcom** [comment]
Thx @robertoDiaz

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5ebc215c21...37c163be68

**Comment by sharonchoi** [comment]
@robertoDiaz sent in a revert for this pull here: https://github.com/brianchandotcom/liferay-portal/pull/35334

It causes more poshi failures than it fixed, sorry!

**Pull request closed without merging**
