### PR TITLE
LPS-96034 Apply new Portlet URL utilities in Users modules

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-96034](https://issues.liferay.com/browse/LPS-96034).<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @kresimir-coko @jbalsas

### CODE REVIEW

**Comment by drewbrokke** [comment]
@jbalsas not sure why the auto SF (last commit) undid the SF from the first commit, but I'll at least point it out.

**Comment by jbalsas** [comment]
Hey @drewbrokke, pretty sure you're using some old version of prettier. Could you check if you have some globally installed version in your machine that you're picking up when running the commands?

Prettier did [Stop breaking simple template literals](https://prettier.io/blog/2019/06/06/1.18.0.html#stop-breaking-simple-template-literals-5979-by-jwbay) in `1.18`.

**Comment by jbalsas** [comment]
Actually, I see it was @kresimir-coko, who did it in the first place, so pinging him to double check as well :)

**Comment by kresimir-coko** [comment]
Interesting @jbalsas , IIRC I didn't manually break the template literal but I'll check my Prettier version.

**Pull request closed without merging**
