### PR TITLE
LPS-70602 Regenerate npm-shrinkwrap.json (autogenerated)

### PR DESCRIPTION
**Pull request by robframpton**

### CODE REVIEW

**Comment by Robert-Frampton** [comment]
cc/ @Ithildir

**Comment by Ithildir** [comment]
ci:reopen

**Comment by Ithildir** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@Robert-Frampton @Ithildir I backported this.

**Pull request closed without merging**
