### PR TITLE
LPS-68243 Make ActionableDynamicQuery interval configurable

### PR DESCRIPTION
**Pull request by arboliveira**
Resending https://github.com/brianchandotcom/liferay-portal/pull/44168 to remedy rebase error.

Author: @daviddotzhang
Reviewer: @arboliveira

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@arboliveira not merging. This fix doesn't make sense. If one deployment needs 500 vs. 1000, why not change them all to 500? Perhaps someone else needs 500. Having them do the extra step of configuration doesn't make sense? Please resend.

**Comment by daledotshan** [comment]
Hey Brian, 
The root issue is that we use a list object to cache all the index object until the list size greater than or equals 10000, finally it cause out of memory issue

Here is the problematic code snippet in class IndexableActionableDynamicQuery
`public void addDocuments(Document... documents) throws PortalException {
		if (ArrayUtil.isEmpty(documents)) {
			return;
		}

		for (Document document : documents) {
			if (document != null) {
				_documents.add(document);
			}
		}

		long size = _documents.size();

		if (size >= getInterval()) {
			indexInterval();
		}
		else if ((size % _STATUS_INTERVAL) == 0) {
			sendStatusMessage(size);
		}
	}`

If you think change the in interval is not a right fix, how about to add new a property to control the cache size?

Thanks,
Dale

**Comment by arboliveira** [comment]
@daledotshan I'm looking into this again. Will get back to you in a few hours.

**Pull request closed without merging**
