### PR TITLE
LPS-71728

### PR DESCRIPTION
**Pull request by Ithildir**
Hi,
Please let this pull finish.

Thank you!

cc @jpince

### CODE REVIEW

**Comment by jpince** [comment]
Thanks @gamerson @Ithildir 

@brianchandotcom please merge and backport to ee-7.0.x, this resolves the CI failures there. thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/80e512057f...b936bd8878

**Comment by brianchandotcom** [comment]
@codyhoag fyi.

**Comment by vicnate5** [comment]
@Ithildir This was backported to ee-7.0.x, but the error we were seeing is still unresolved there.

`
WARN  [fileinstall-/opt/dev/projects/github/liferay-portal-ee-7.0.x/bundles/osgi/modules][com_liferay_portal_language_extender:103] Unable to handle liferay.resource.bundle; baseName="content.Language"; aggregate="(bundle.symbolic.name=com.liferay.journal.lang)" in com.liferay.journal.service
`

See https://github.com/brianchandotcom/liferay-portal-ee/pull/16898#issuecomment-298204298

**Comment by Ithildir** [comment]
Adding @gamerson, he's the one that worked on this feature.

**Comment by jpince** [comment]
cc/ @ginsonren @brianwulbern

**Pull request closed without merging**
