### PR TITLE
LPS-67191 Deploy theme with "ant all"

### PR DESCRIPTION
**Pull request by Ithildir**
cc @marcoscv-work

### CODE REVIEW

**Comment by Ithildir** [comment]
@marcoscv-work, I'm closing this pull because of this error:

```
Unable to process message {destinationName=liferay/hot_deploy, response=null, responseDestinationName=null, responseId=null, payload=null, values={companyId=0, groupId=0, command=deploy, servletContextName=westeros-bank-theme}}
com.liferay.portal.kernel.messaging.MessageListenerException: com.liferay.exportimport.kernel.lar.PortletDataException: com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: java.lang.IndexOutOfBoundsException: Index: 2, Size: 0
	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:32)
	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:74)
	at com.liferay.portal.kernel.messaging.SerialDestination$1.run(SerialDestination.java:58)
	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask._runTask(ThreadPoolExecutor.java:756)
	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask.run(ThreadPoolExecutor.java:667)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by marcoscv-work** [comment]
Hey @Ithildir I think that by the moment we should remove all themes from the ant all, because the .lar files will be generated for a stable version, so we cannot insure that won't have new importing errors. What do you think?

**Comment by Ithildir** [comment]
Hi @marcoscv-work!

You mean all the themes that contain LARs? Can you please do it and send the pull to Brian? You know way more than me about these themes! :blush: You just have to remove the `.lfrbuild-portal` files in the themes you think should not be published.

Thank you!

**Comment by marcoscv-work** [comment]
Hey @Ithildir , there are two types of themes, what are called "core themes": 

- _unstyled
- _styled
- classic
- admin
- profile
- dashboard

and others called "site themes" which have content in a site template, in a .lar. and they will be publish in Liferay marketplace:

- Product APP
- Westeros Bank
- London (soon)
- Porygon (soon)

I will speak with @jbalsas to decide if finally we will remove .lfrbuild-portal in "site themes" or not.

Thanks!

**Pull request closed without merging**
