### PR TITLE
LPS-168788 and LPS-169088 Add support to the id in the fragment's drop zone tags

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-168788
https://issues.liferay.com/browse/LPS-169088

@lfbesada

### CODE REVIEW

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/10354

:heavy_check_mark: ci:test:stable - 26 out of 26 jobs passed
:x: ci:test:relevant - 252 out of 303 jobs passed in 2 hours 40 minutes

**Comment by ozysouza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/677149adbc...ac0c1a2af5

**Comment by brianchandotcom** [comment]
Nicely done @lfbesada

**Pull request closed without merging**
