### PR TITLE
LPS-79017 Add the proper new category to those Configurations that still have a legacy category

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@JorgeFerrer can you resend on top of https://github.com/JorgeFerrer/liferay-portal/pull/849 ? Thx.

**Comment by JorgeFerrer** [comment]
Resent as https://github.com/brianchandotcom/liferay-portal/pull/56469

**Pull request closed without merging**
