### PR TITLE
LPD-18448 sort and refactor tests

### PR DESCRIPTION
**Pull request by manuelecastro**
Related issue: [LPD-18448](https://liferay.atlassian.net/browse/LPD-18448)

Increased the field values that can contain the result of SHA-384/hex mix (values that come from PasswordEncryptor.Encrypt()):

User - _password
PasswordTracker - _password
Ticket - _key

> Original comment:
> 
> Description:
> When using SHA-384 as encryption algorithm and hex as digest encoding, it generates a string that is over the size set for it on the database (75 characters).
> 
> Proposed solution:
> To solve this, I increased the password_ column size so it can support the SHA-384/Hex mix, which generates a 96 long string plus 9 characters from the prefix("{SHA-384}") resulting in a 105 characters string.
> 
> Original PR: https://github.com/liferay-appsec/liferay-portal/pull/1668 | https://github.com/liferay-appsec/liferay-portal/pull/1734

### CODE REVIEW

**Comment by manuelecastro** [comment]
ci:test:sf

**Comment by manuelecastro** [comment]
Hi @brianchandotcom !

Just committed the changes you asked earlier and I also did new suggestions for tests names. Let me know if there are any changes to be made. 

Thank you! :)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9675db3273...ecfbee9e2d

**Comment by brianchandotcom** [comment]
@manuelecastro this is good. It's much tighter and better organized. Good job.

**Pull request closed without merging**
