### PR TITLE
WCM-628

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
@juliocamarero can you resend on top of changes from @Ithildir 

Web-ContextPath: /report-_name_

We should namespace the web context path for content targeting.

This will ensure we don't conflict with modules from the "reports" team. Thx.

**Comment by Ithildir** [comment]
I sent the new template to https://github.com/juliocamarero/liferay-portal/pull/4182 and the unit tests to https://github.com/brianchandotcom/liferay-portal/pull/41167.

**Comment by ealonso** [comment]
Please see: https://github.com/brianchandotcom/liferay-portal/pull/41266

**Pull request closed without merging**
