### PR TITLE
LPS-100788 Bump Senna's version to latest

### PR DESCRIPTION
**Pull request by diegonvs**
/cc @jbalsas

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:sf

**Comment by jpince** [comment]
@john-co yarn `     [exec] Execution failed for task ':yarnInstallModules'.`

**Comment by jbalsas** [comment]
ci:close

**Comment by jbalsas** [comment]
will resend

**Pull request closed without merging**
