### PR TITLE
LPS-107374 - Extract all IE-specific CSS to its own module

### PR DESCRIPTION
**Pull request by julien**
@john-co these are the same changes reviewed here https://github.com/julien/liferay-portal/pull/232, that were sent to @brianchandotcom yesterday here https://github.com/brianchandotcom/liferay-portal/pull/85570 because they were breaking stable. 

If any suspicious CI error occur could you please have a look and tell us what we're doing wrong? 

/cc @marcoscv-work

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:bundle

**Comment by brianchandotcom** [comment]
@julien SF error.

**Comment by john-co** [comment]
testing locally with auto-SF: https://github.com/john-co/liferay-portal/pull/261

**Pull request closed without merging**
