### PR TITLE
LPS-157280 Allow multiple upgrade steps in core and apply get pre and post upgrades

### PR DESCRIPTION
**Pull request by LuisOrtiz89**
LPS-157280

### CODE REVIEW

**Comment by LuisOrtiz89** [comment]
ci:reopen

**Comment by LuisOrtiz89** [comment]
Failures on CI are not related.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/31a9d2d2b4...a333cd7345

**Comment by brianchandotcom** [comment]
Thx @LuisOrtiz89 @achaparro see changes in my origin. Thx.

**Pull request closed without merging**
