### PR TITLE
LPS-72477 Create module that automatically generates realistic users in order to have a more realistic scenarios for development & testing

### PR DESCRIPTION
**Pull request by pei-jung**
Hey Brian,

This is a resent of https://github.com/brianchandotcom/liferay-portal/pull/49032#issuecomment-303864272.

/cc @drewbrokke @jorgeferrer

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:reopen

**Comment by pei-jung** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3db34d787f...bb8e4d3367

**Comment by brianchandotcom** [comment]
@pei-jung I merged this, can you send me a backport to ee-7.0.x? Thx.

**Pull request closed without merging**
