### PR TITLE
LPS-99833

### PR DESCRIPTION
**Pull request by brunofarache**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/401a4285d7...355863113a

**Comment by brianchandotcom** [comment]
@brunofarache can you sort

```
import CustomObjectNavigationBar from './CustomObjectNavigationBar.es';
import ListApps from '../app/ListApps.es';
import EditFormView from '../form-view/EditFormView.es';
import ListFormViews from '../form-view/ListFormViews.es';
import EditTableView from '../table-view/EditTableView.es';
import ListTableViews from '../table-view/ListTableViews.es';
```
in modules/apps/app-builder/app-builder-web/src/main/resources/META-INF/resources/js/pages/custom-object/ViewCustomObject.es.js

@jbalsas @wincent can we auto enforce?

**Comment by wincent** [comment]
@brianchandotcom: Should be possible; [it's being tracked in this ticket](https://github.com/liferay/liferay-frontend-guidelines/issues/60).

**Comment by brunofarache** [comment]
@brianchandotcom there are many possibilities on how to sort imports (should we sort by the left hand expression, after the "from" keyword or before it?, etc) 

I will wait until our formatter does that for us.

**Pull request closed without merging**
