### PR TITLE
Upgrade Process: don't share connections accross threads

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by migue** [comment]
@brianchandotcom Resending this https://github.com/brianchandotcom/liferay-portal/pull/36770

No need to be a class level variable, but I added it because potentially, the subclasses could reuse the connection, so they don't need to open a new one. For now, there is only 2 subclases, and hope we don't need any more :). I am fine inline it if you like it more

Regarding the number of connections, we could, potentially, ran out of connections, but it is not likely to happen. Even if we run 1000 companies in parallel, not all of them are gonna be so huge ( many of them will finish way before) the connection pool is exhausted.

**Comment by migue** [comment]
Additionally, having a really huge number of companies in the same database is not a good idea

**Comment by brianchandotcom** [comment]
@migue can you resend this but limit the number of connections? The reason is that some of our clients use us the portal as a multitenant systme with thousands of companies. So we just need to limit the number of connections at a time.

**Comment by migue** [comment]
Thousands, in the same database? I've been using databases from big clients
and they have 2-3 companies, at most.

I can limit it, no problem, but doesn't seem a realistic scenario, does it?

**Pull request closed without merging**
