### PR TITLE
LPS-80976

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@arboliveira fyi lower lvl APIs.  Haven't moved the ElasticsearchIndexSearcher and ElasticsearchIndexWriter to use the new lower lvl APIs.  Too much risk to do it right now.  We'll use this API for other modules (e.g. audit)

**Comment by mhan810** [comment]
ci:stop

**Comment by jpince** [comment]
@michaelhashimoto @kenjiheigel @yichenroy bad slave?
```
[beanshell] 1 slaves failed to respond:
[beanshell] [cloud-10-0-110-214]
```

**Comment by jpince** [comment]
sorry, nevermind, didn't notice that Mike stopped the test

**Pull request closed without merging**
