### PR TITLE
LPS-192935

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://liferay.atlassian.net/browse/LPS-192935

@ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/13194

**Comment by ealonso** [comment]
Fix rebase and resend https://github.com/brianchandotcom/liferay-portal/pull/138980

**Comment by ealonso** [comment]
ci:close

**Pull request closed without merging**
