### PR TITLE
LPS-78897 Announcement portlet's titles wrongly translated to Finnish and Swedish

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test

**Comment by robertoDiaz** [comment]
cc/ @laszlopap 

Hi @sergiogonzalez I've pass this pr directly to Brian since the translations have been confirmed [here](https://issues.liferay.com/browse/LPP-29404?focusedCommentId=1266907&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1266907) and I guess that your finnish and swedish is as good as mine :)

**Comment by robertoDiaz** [comment]
ci:reopen

**Comment by robertoDiaz** [comment]
Errors are not related with the pr

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
