### PR TITLE
LPS-132180

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
Unrelated failures only: https://github.com/hhuijser/liferay-portal/pull/5659

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/96d851127f...149379d098

**Comment by brianchandotcom** [comment]
@hhuijser can you make setRedirect take PortletURL as an argument so we don't need to have

0cd7c40c

Thx!

**Pull request closed without merging**
