### PR TITLE
LPS-85097 mobile notification

### PR DESCRIPTION
**Pull request by javiergamarra**
/cc @dgarciasarai

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fa23089cef...f3b1c968b9

**Comment by brianchandotcom** [comment]
@nhpatt if you need this for 7.1.x, send me a pull, I think this is very safe.

**Comment by jpince** [comment]
@nhpatt @dgarciasarai this caused a semver failure. I will push a fix upstream.
```
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.workflow.constants              MINOR      1.0.0      1.0.0      1.1.0      VERSION INCREASE REQUIRED
     [exec] 	+   class      com.liferay.portal.workflow.constants.MyWorkflowTasksConstants
     [exec] 		+   field      NOTIFICATION_TYPE_MY_WORKFLOW_TASKS
     [exec] 			+   access     final
     [exec] 			+   access     static
     [exec] 			+   constant   0
     [exec] 			+   return     int
     [exec] 		+   method     <init>()
     [exec] 			+   return     void
     [exec] 		+   method     clone()
     [exec] 			+   access     protected
     [exec] 			+   return     java.lang.Object
     [exec] 		+   method     equals(java.lang.Object)
     [exec] 			+   return     boolean
     [exec] 		+   method     finalize()
     [exec] 			+   access     protected
     [exec] 			+   return     void
     [exec] 		+   method     hashCode()
     [exec] 			+   return     int
     [exec] 		+   method     toString()
     [exec] 			+   return     java.lang.String
```

**Comment by nhpatt** [comment]
Ups :'(

**Comment by dgarciasarai** [comment]
Sorry :(

**Pull request closed without merging**
