### PR TITLE
LPS-171486 "Preview in a new tab" option for pages does not load Client Extensions

### PR DESCRIPTION
**Pull request by Tim-Cao**
This is only for master.

https://issues.liferay.com/browse/LPS-171486

@lfbesada

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/10798

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fae4588d9b...8ff26e026d

**Comment by brianchandotcom** [comment]
@lfbesada see 8ff26e026d115bb0f7c4a7d9d286ecdde191bc93 just that one, my bad earlier!

**Pull request closed without merging**
