### PR TITLE
LPS-168833 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
This is only for master.

https://issues.liferay.com/browse/LPS-168833

@BarbaraCabrera
cc @sandrodw3

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/10999

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/085657dcab...73cda75632

**Comment by brianchandotcom** [comment]
@BarbaraCabrera For div, we do this: 7e536b67aa96f358b04ffbd57dfb8ca5347b6e9a

**Pull request closed without merging**
