### PR TITLE
Lps 139811

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d6d04e5eec...2a4627064c

**Comment by brianchandotcom** [comment]
@rotty3000 if it is NULL the second time, can it break business logic? The current code makes it look like we can set "permissionChecker" to something OTHER than PermissionChecker.

**Comment by brianchandotcom** [comment]
@rotty3000 I linked this weird behavior 9affef1e1faec26d59eb6d3bc178de5a666f29ab

**Comment by rotty3000** [comment]
@brianchandotcom no wehere in the sources to we deliberately put a different type for permissionChecker.

However, if you consider the exception:

```
2021-09-29 13:54:00.011 WARN  [PersistedQuartzSchedulerEngineInstance_Worker-1][LiferayJSONDeserializationWhitelist:50] Unable to deserialize com.liferay.portal.kernel.util.TransientValue due to security restrictions
Exception in thread "antivirus_destination-2" java.lang.ClassCastException: java.util.HashMap cannot be cast to com.liferay.portal.kernel.security.permission.PermissionChecker
	at com.liferay.portal.messaging.internal.MessageBusThreadLocalUtil.populateThreadLocalsFromMessage(MessageBusThreadLocalUtil.java:109)
	at com.liferay.portal.messaging.internal.SerialDestination$1.run(SerialDestination.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

What it looks like to me is that the message may have been deserialized from the quartz persistent store with the value `permissionChecker` instantiated as a HashMap rather than as a PermissionChecker.

**Comment by brianchandotcom** [comment]
@rotty3000 serializing it back would probably be a bad idea.

I'm curious about the cause.... because there may be other unserializable attributes we're shoving in there

**Comment by rotty3000** [comment]
I briefly discussed this with @tinatian and she wisely pointed out that any non-serializable placed in a `Message` is wrapped in a `TransientValue` [here](https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/messaging/Message.java#L225-L227). Then simple debugging showed that this happens when the `PermissionChecker` is added [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal/portal-messaging/src/main/java/com/liferay/portal/messaging/internal/MessageBusThreadLocalUtil.java#L54-L58)

Finally, if you wind up using such a message in a call to the scheduler, like so
```java
_schedulerEngineHelper.schedule(
	trigger, StorageType.PERSISTED, trigger.getJobName(),
	AsyncAntivirusConstants.ANTIVIRUS_DESTINATION,
	message, 0)
```
(which is not likely a very common case) the message is serialized. So the exception happens when the message is deserialized as mentioned earlier.

I think the small protection we put in place is good enough and the scenario is rare enough that we should be good here. I already figured in my code that I should avoid the issue entirely by making sure the message does not contain a `permissionChecker` (which I don't need in my use case.)

FYI, there does not appear to be any other non-serializable types added anywhere.

**Comment by rotty3000** [comment]
I almost think that scheduler use of Message argument should do something like:
```
for (Iterator<Entry<String, Object>> iterator = message.getValues().entrySet().iterator(); iterator.hasNext(); ) {
	Entry<String, Object> entry = iterator.next();
	Object value = entry.getValue();
	if (value instanceof TransientValue) {
		iterator.remove();
	}
}
```

**Pull request closed without merging**
