### PR TITLE
LPS-93427 portal-settings-authentication-ldap-web - removes LDAPSettingsWebKeys in favor of LDAPSettingsConstants

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-93427](https://issues.liferay.com/browse/LPS-93427).<br><br>This pull explodes the legacy Portal Settings form navigator into distinct entries inside the new Instance Settings portlet. Functional test fixes are included.<br><br>/cc @pei-jung @stsquared99 @alee8888 @ChrisKian @xbrianlee @Sharryxue @dejuknow

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by drewbrokke** [comment]
@jpince I reopened this one because I think I've seen these failures elsewhere. Is that correct?

**Comment by brianchandotcom** [comment]
@drewbrokke can you rename all the classes that

```
extends BaseEditCompanyPortalSettingsConfigurationScreenContributor
```

Should be XyzEditCompanyPortalSettingsConfigurationScreenContributor

I know, long... but consistent. Please resend. Thx.

**Comment by drewbrokke** [comment]
@brianchandotcom What if I just renamed the base class to something generic?

**Comment by drewbrokke** [comment]
Resent as https://github.com/brianchandotcom/liferay-portal/pull/71525

**Pull request closed without merging**
