### PR TITLE
LPS-165563 Add feature flag

### PR DESCRIPTION
**Pull request by seltong**

### CODE REVIEW

**Comment by seltong** [comment]
ci:reopen

**Comment by seltong** [comment]
The failures [here](https://github.com/liferay-objects/liferay-portal/pull/1206) are not related

**Comment by brianchandotcom** [comment]
@seltong there's no verb in

algorithm-that-derives-its-value-from-other-fields

```
algorithm-that-derives-its-value-from-other-fields=Algorithm that derives its value from other fields.
```

**Comment by seltong** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/124991

**Pull request closed without merging**
