### PR TITLE
LPS-113207 SF

### PR DESCRIPTION
**Pull request by rodrigocunhaa**

### CODE REVIEW

**Comment by rodrigocunhaa** [comment]
Forwarded from https://github.com/inacionery/liferay-portal/pull/663. The same reason as https://github.com/brianchandotcom/liferay-portal/pull/88624.

**Comment by rodrigocunhaa** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
WorkflowInstanceManagerUtil searchWorkflowInstances vs. search 

how do we come to that naming convention?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/88177b3542...8ff58f0825

**Comment by brianchandotcom** [comment]
@inacionery @rafaprax Looks good. I found the pattern where you copied this from. Looks good.

**Pull request closed without merging**
