### PR TITLE
LPS-100099 Standardize Ajax requests in calendar-web

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5fcaa2ce6c...8deefaeca1

**Comment by brianchandotcom** [comment]
@inacionery @julien see 8deefaeca14df699cc47c40ded1fe357a338c9d7

**Comment by julien** [comment]
@brianchandotcom thanks.

**Pull request closed without merging**
