### PR TITLE
LPS-193215 Add validation and add import strategies for import fragments process

### PR DESCRIPTION
**Pull request by Mikellorza**
Coming from : https://github.com/brianchandotcom/liferay-portal/pull/139705

https://liferay.atlassian.net/browse/LPS-193215

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:open

**Comment by Mikellorza** [comment]
ci:open

**Comment by Mikellorza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1307c0a04e...b868e9a79f

**Comment by brianchandotcom** [comment]
Wow @Mikellorza this is very good!

**Pull request closed without merging**
