### PR TITLE
LPS-64246 This needs to be synchronized

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
but we should definitely not be creating ServiceTrackers on a per request basis...

**Comment by csierra** [comment]
besides... opening a ServiceTracker already synchronizes on the framework... so we already have a global block by using ServiceTrackers

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/37617

**Comment by brianchandotcom** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/37617

**Pull request closed without merging**
