### PR TITLE
LPS-65540 Regen Bootstrap MF

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by epgarcia** [comment]
ci:retest

**Comment by sharonchoi** [comment]
@brianchandotcom PGTags tests are failing due to the following bug at head on master: https://issues.liferay.com/browse/LPS-66724

**Comment by epgarcia** [comment]
ci:retest

**Comment by epgarcia** [comment]
ci:retest

**Pull request closed without merging**
