### PR TITLE
LPS-75444 Rename to layout url

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@ealonso I think you only renamed one file and missed the other file? Please resend.

**Comment by ealonso** [comment]
Hey @balazssk,

IMHO, I think from frontend perspective is the same if we use one name of variable or other.

I did the rename for consistency with other places in the portal.

Regards,
Eudaldo.

**Comment by ealonso** [comment]
see: https://github.com/brianchandotcom/liferay-portal/pull/53019

**Comment by balazssk** [comment]
hi @ealonso ,

Yes, the name of the data-<variable> doesn't matter, however the value in this case differs.
In an example: when the template is evaluated,
regularURL would be "http://localhost:8080/group/blank/paper"
but
layoutURL would be "http://localhost:8080/group/blank/~/control_panel/manage?p_p_id=com_liferay_layout_admin_web_portlet_ [...](GroupPagesPortlet&p_p_lifecycle=0&p_p_state=maximized&_com_liferay_layout_admin_web_portlet_GroupPagesPortlet_redirect=%2Fgroup%2Fvideoa%2F%7E%2Fcontrol_panel%2Fmanage%3Fp_p_id%3Dcom_liferay_item_selector_web_portlet_ItemSelectorPortlet%26p_p_lifecycle%3D0%26p_p_state%3Dpop_up%26p_p_mode%3Dview%26_com_liferay_item_selector_web_portlet_ItemSelectorPortlet_0_json%3D%257B%2522desiredItemSelectorReturnTypes%2522%253A%2522com.liferay.item.selector.criteria.URLItemSelectorReturnType%2522%257D%26_com_liferay_item_selector_web_portlet_ItemSelectorPortlet_criteria%3Dcom.liferay.item.selector.criteria.file.criterion.FileItemSelectorCriterion%252Ccom.liferay.layout.item.selector.criterion.LayoutItemSelectorCriterion%26_com_liferay_item_selector_web_portlet_ItemSelectorPortlet_itemSelectedEventName%3D_com_liferay_journal_web_portlet_JournalPortlet_content_INSTANCE_osvfEditorselectDocument%26_com_liferay_item_selector_web_portlet_ItemSelectorPortlet_1_json%3D%257B%2522checkDisplayPage%2522%253Afalse%252C%2522desiredItemSelectorReturnTypes%2522%253A%2522com.liferay.item.selector.criteria.URLItemSelectorReturnType%2522%257D%26_com_liferay_item_selector_web_portlet_ItemSelectorPortlet_selectedTab%3DPrivate%2520Pages%26p_p_auth%3Dz0XXWlEc&_com_liferay_layout_admin_web_portlet_GroupPagesPortlet_groupId=35504&p_r_p_selPlid=35510&p_p_auth=HWcz8GTg)"

On master, the Editor gets a regularURL after the page selection, that is why I'd like to be consistent in adding that to the available data-attributes.
image

**Pull request closed without merging**
