### PR TITLE
LPS-64456 Fix argument

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by sharonchoi** [comment]
@brianchiu upgrade test failures due to https://issues.liferay.com/browse/LPS-64526
@kenjiheigel portal smoke failings due to https://issues.liferay.com/browse/LPS-64500

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@marcellustavares @leoadb please resend with ActionableDynamicQuery or this won't scale. Imagine if

List<ResourcePermission> resourcePermissions =
			_resourcePermissionLocalService.dynamicQuery(dynamicQuery);

returns a million rows. Thx.

**Comment by leoadb** [comment]
@marcellustavares I got this !!! Will resend.

**Pull request closed without merging**
