### PR TITLE
LPS-168771 - Migrate Role Permission Navigation to Clay Vertical Nav (rebased)

### LINKED ISSUE #5513: Vertical Nav overlaps items with long nested list
## Is there an example you can provide via codesandbox.com?
https://codesandbox.io/s/dazzling-antonelli-pklh9h?file=/src/items.js

## What are the steps to reproduce?
1. Navigate to the code sandbox
2. Expand `User` at the bottom.
3. Expand `Site and Asset Library Administration`.
4. Expand `Applications`.

## What is the expected result?
The items should not overlap.

**Actual Result:**
The Application and user items overlap one another.

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Manually forwarding because ci:forward fails on liferay-appsec/liferay-portal/pull/1108

---
https://issues.liferay.com/browse/LPS-168771

This PR seeks to solve accessibility issues that relate to the Role Permissions Navigation. Initially we wanted to only update the markup in the jsp, but this resulted in more complexity trying to keep the javascript working that depended on the old markup. As a result it made more sense to move towards the best option of using the Clay Vertical Nav component directly. 

What has changed:
- Due to it being React, there is a slight lag and the navigation loads slightly after the page.
- The old behavior had all panels open when filtering and all panels close when the filter input is emptied. ~~This is currently not possible with the Clay component.~~ All panels now open when filtering and when done filtering it reverts back to the initial state when loaded. This makes more sense to me than closing all the panels after filtering.
- ~~There is an existing bug with the Clay Vertical Nav that causes some children to overlap when multiple levels deep. This will be fixed [here](https://github.com/liferay/clay/issues/5513).~~ Fixed
- At some point the persistence after refresh of the currently selected item was lost. This PR adds that functionality back.

Since this is a larger rewrite I'm asking for additional testing by @john-co to make sure we don't have any regressions.

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@ethib137 I haven't seen this pattern before?

modules/apps/roles/roles-admin-web/src/main/java/com/liferay/roles/admin/web/internal/display/context/ClayVerticalNavItem.java

Can you resend without the new pattern? Thx.

@stian-sigvartsen fyi

**Comment by brianchandotcom** [comment]
```
git grep JsonInclude **Clay**.java
```

returns nothing

```
git ls-files **/display/context/**Clay**.java
```

only returns samples

@ethib137 @stian-sigvartsen @drewbrokke fyi

**Comment by brianchandotcom** [comment]
@ethib137 @drewbrokke can you guys resend with the map instead?

The map is more verbose, but less complicated in the long run. And we use the map pattern in lots of other places.

**Comment by ethib137** [comment]
Hey @brianchandotcom , sure no problem. Just to clarify, do you mean we should revert this [commit](https://github.com/brianchandotcom/liferay-portal/commit/0098e3864743d12aea6a88246a5c41fd95e7ac1c) so that all the navItems are created directly as JSONArrays and JSONObjects, or do you mean that the ClayVerticalNavItem class should be refactored to remove all the Jackson bindings?

**Comment by ethib137** [comment]
Resent with updates here: https://github.com/liferay-appsec/liferay-portal/pull/1179

**Pull request closed without merging**
