### PR TITLE
LPS-67460

### PR DESCRIPTION
**Pull request by Ithildir**
**_This pull will no longer automatically close if this comment is available. If you believe this is a mistake please re-open this pull by entering the following command as a comment.**_

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:reopen

**Comment by sharonchoi** [comment]
Test failures are due to FF connection error documented here: https://loop.liferay.com/home/-/loop/feed/3014232

**Comment by brianchandotcom** [comment]
@Ithildir @caustin582 see 902917a734d6721544443d5264cae6d098e3e96c

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
