### PR TITLE
LPS-71378 Update build.gradle

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
Pull request tests are not triggering automatically so I'm going to attempt to trigger them manually.

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:reopen

**Pull request closed without merging**
