### PR TITLE
LPS-75421

### PR DESCRIPTION
**Pull request by drewbrokke**
https://issues.liferay.com/browse/LPS-75421

Additional commit for LPS-75421.  We are not correctly iterating through organization-type groups, and thus we are not adding org users to the list of viewable contacts.

Please let me know if you have any questions.

### CODE REVIEW

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
ci:stop

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
@brianchandotcom looks good from a functional test perspective.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@drewbrokke @ChrisKian see 157acc2 thx.

**Pull request closed without merging**
