### PR TITLE
LPS-64769

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@Ithildir

Somehow this is much faster than using path.toRealPath()
Also, making sure to pass the original fileName, not the full path, because that would break stuff.

**Comment by brianchandotcom** [comment]
ci:stop (mster is broken,.. need to retest after)

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/90c2f42c54...fa4e28e665

**Pull request closed without merging**
