### PR TITLE
LPS-73460 SF

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9e5d2257ed...59432ddcd0

**Comment by brianchandotcom** [comment]
@ealonso see 59432ddcd086cc7916ac2e2c6076686f2f12379e

**Comment by brianchandotcom** [comment]
Woops. Link works now. See 59432ddcd086cc7916ac2e2c6076686f2f12379e

**Pull request closed without merging**
