### PR TITLE
LPS-71280 Initialize PermissionCheckerThreadLocal and PrincipalThreadLocal, copy from DLFileEntrySearchTest

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by ealonso** [comment]
ci:retest

**Comment by jpince** [comment]
@ealonso test failures with this error:
```
     [java] 12:27:31,143 ERROR [main][ModuleFrameworkImpl:1493] Unable to start bundle com.liferay.trash.test.util
     [java] org.osgi.framework.BundleException: Could not resolve module: com.liferay.trash.test.util [549]
     [java]   Unresolved requirement: Import-Package: com.liferay.portal.kernel.test.rule; version="[1.0.0,2.0.0)"
```
For some reason, this seems to pass on Tomcat, but it fails on all other app servers and on all modules-int* test batches. Can you please take another look?

closing this pull

**Comment by jpince** [comment]
ci:close

**Pull request closed without merging**
