### PR TITLE
LPS-80473 Navigation Menus do not limit max Length for its Name

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by brianchandotcom** [comment]
@shuyangzhou I think we have repeat AMImage*Test flaky tests.. can you take a look? Thx.

**Comment by brianchandotcom** [comment]
Merged

**Comment by shuyangzhou** [comment]
@mtambara please take a look

**Pull request closed without merging**
