### PR TITLE
LPS-78251 SF

### PR DESCRIPTION
**Pull request by jbalsas**
See tests -> https://github.com/jbalsas/liferay-portal/pull/1112#issuecomment-376630949

Hey @brianchandotcom, this adds the final UI-utils for applying the new ManagementToolbar pattern. We've tested it in several portlets already that will follow once we land this into master.

For performance reasons, after talking to @shuyangzhou and @rotty3000, we're basing our models out of `HashMaps` instead of full-blown classes.

Let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jbalsas  you'll notice we now have 2 classes called ThrowableConsumer that are very generic, but inside individual modules. I think they're the same and you'll want to move them out, possibly to kernel.

Please resend on top of https://github.com/jbalsas/liferay-portal/pull/1113

There are a few methods that didn't get renamed. Please review and resend. Thx.

**Comment by jbalsas** [comment]
Hey @brianchandotcom, I think this `ThrowableConsumer` is quite different in nature, in that it will catch the exceptions and throw a `RuntimeException` unlike the one from `apio`. It also has a different interface to be implemented.

@sergiogonzalez, should this have another name? Can you explain the differences?

**Comment by brianchandotcom** [comment]
@jbalsas can we coordinate with the apio team and at least name it differently? Thx.

**Comment by jbalsas** [comment]
Yes, I'll coordinate with them later today, figure out what this really is to name it properly and resend applying the missing fixes.

**Pull request closed without merging**
