### PR TITLE
LPS-136127 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-136127

This is only for master.

@victorg1991
@ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure case is unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/5319
✔️ ci:test:stable - 10 out of 10 jobs passed
❌ ci:test:relevant - 21 out of 25 jobs passed in 4 hours 24 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2756374a48...31af90bca3

**Comment by brianchandotcom** [comment]
Nicely done @victorg1991 @Tim-Cao

**Pull request closed without merging**
