### PR TITLE
WAB Support: add back Markeplace Apps deployment support

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by migue** [comment]
/cc @lionah

Ryan, here is the support of the marketplace once the old deployment mechanism has been completely removed. I've just tried to keep the old behaviour, forgive me if I've missed something, I've tried to do my best (I don't know the marketplace behaviour, sorry :) )

Now, you can deploy your lpkg files in 3 different manners:

* You can deploy your .lpkg file into the deploy folder
* You can deploy your .lpkg file into the osgi/modules (or whatever folder is being monitored by FileInstall) folder
* You can install your .lpkg file from the Gogo Shell. For example
    install lpkg:file:///path/to/my.lpgk
    install lpkg:http:///url.to/my.lpkg

Of course, feel free to modify anything you think is not correct or wrong.

**Comment by brianchandotcom** [comment]
ci:retest (for that extra commit)

**Comment by migue** [comment]
Unrelated ... ci:retest

**Comment by migue** [comment]
ci:retest

**Comment by migue** [comment]
Any of this 2 tests is related.

**Comment by jpince** [comment]
ci:retest @migue the deletewikinode test fix was submitted in https://github.com/brianchandotcom/liferay-portal/pull/36802, but the sourceformatter failure has been consistent across all retests. Probably due to b533fee since the first round of commits passed.

**Comment by migue** [comment]
Hi,

In this last commit I modified LiferayPackageInstaller.java (just not
throwing an exception) but the test is complaining about

org.junit.ComparisonFailure:
../../../modules/apps/platform/portal-configuration/portal-configuration-metatype/src/test/java/com/liferay/portal/configuration/metatype/util/ParameterMapUtilTest.java
expected:<...static final String [PARAMETER_MAP_STRING =
"PARAMETER_MAP";


How is this possibly related?


On 29 February 2016 at 23:13, Liferay Continuous Integration <
notifications@github.com> wrote:

> Build StartedJob Link:
>
> test-portal-acceptance-pullrequest(master)
> <https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest(master)/1049/>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/36802#issuecomment-190422107>
> .
>



-- 
Un saludo,

Migue

http://migue.github.io

**Comment by jpince** [comment]
@brianchandotcom this pull looks good now, please merge

cc/ @brianchiu @migue

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/12fc30ab21...4d393f30b0

**Comment by brianchandotcom** [comment]
@migue should those packages be in internal? I don't think anyone needs to reference them. Can you send me a follow up pull?

Thx.

**Comment by migue** [comment]
Brian, nobody can reference them, they're not being exported.

On 2 March 2016 at 00:39, Brian Chan <notifications@github.com> wrote:

> @migue <https://github.com/migue> should those packages be in internal? I
> don't think anyone needs to reference them. Can you send me a follow up
> pull?
>
> Thx.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/36802#issuecomment-190969419>
> .
>



-- 
Un saludo,

Migue

http://migue.github.io

**Pull request closed without merging**
