### PR TITLE
LPS-100896 Add common hooks to frontend-js-react-web

### PR DESCRIPTION
**Pull request by wincent**
There are some hooks that are so basic, common, and useful that we want to provide them in frontend-js-react-web. Some initial candidates I am thinking of:

- `usePrevious` (substitute for componentDidUpdate)
- `useMounted` (useful in async callbacks, so that you can check whether you are still mounted before firing off a set-state call)
- `useEventListener` (encapsulates common pattern of adding an event listener on mount and removing it on unmount)

We want to keep this list small and conservative to prevent it from becoming an infinite grab bag of hooks, but there are definitely some hooks (like the ones above) that are pretty uncontroversial.

### CODE REVIEW

**Comment by wincent** [comment]
I don't think the test failure is related; in the Poshi screenshot, I can see "pdated fragment text" (truncated).

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/189137e234...2eecacc383

**Comment by brianchandotcom** [comment]
@wincent you need to automate it so that any code we write uses the one from frontend-js-react or else ppl will still use their own.

**Comment by wincent** [comment]
Ticket for that here: https://issues.liferay.com/browse/LPS-101674

**Pull request closed without merging**
