### PR TITLE
Lps 72832

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@brianchandotcom sorry, forgot to update this test in the previous pull.

**Comment by shuyangzhou** [comment]
Pushed upstream to fix CI.

**Comment by jpince** [comment]
@shuyangzhou can you fix the SF issue? I think BChan already left for the day

`     [java] Add the string 'for ' to the previous literal string: ./modules/util/portal-tools-service-builder/src/main/java/com/liferay/portal/tools/service/builder/ServiceBuilder.java 5698`

https://github.com/liferay/liferay-portal/commit/6680a549983a0e0a0af11588d0d90ec0b49d9239#diff-afcd6a343881a50ebb6a12bb6d68b008R5698

**Comment by shuyangzhou** [comment]
@jpince  see https://github.com/brianchandotcom/liferay-portal/pull/49315 and pushed upstream

**Pull request closed without merging**
