### PR TITLE
LPS-109315 Use simple name

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by kenjiheigel** [comment]
Stable fails due to a test in modules-integration. The test failure is unrelated to this pull: 
* [com.liferay.blogs.search.test.BlogsEntryMultiLanguageSearchTest.testEnglishTitle](https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/370502/) failure is due to LPS-98318

**Comment by brianchandotcom** [comment]
@arboliveira @BryanEngler fyi on LPS-98318. Need you guys to fix it.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bc1ee456f9...22e7a4e278

**Comment by brianchandotcom** [comment]
@brianikim @adolfopa see 6ff86c9cbf8142731cfcaa94e4c1c1f08d49dd89

**Comment by brianchandotcom** [comment]
@adolfopa @brianikim also see 0bf9e2d60264edaafa459b1830f5de2496d3607d

**Pull request closed without merging**
