### PR TITLE
LPS-64336 JasperException thrown when trying to access a JSF taglib in a JSP (code review fixes)

### PR DESCRIPTION
**Pull request by rotty3000**
👍 @ngriffin7a

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f56fadaf19...8a2a488e07

**Comment by brianchandotcom** [comment]
@ngriffin7a nice job Neil. I made one change, in general, whenever we "fake" the Gradle cache, we put that in a separate commit since it's not real and I have to remove it when I do merge it in.

So I rewrote e8f8af2ff563f195aeb3fc125efe6768a9137418

and put it in 8a2a488e070b0d87894c20b76d1dc9d19a7fd8eb

**Comment by ngriffin7a** [comment]
@brianchandotcom Thanks. I'll be sure to remember to fake the Gradle cache in a separate commit next time :)

**Pull request closed without merging**
