### PR TITLE
LPS-70535 Introduce Portlet Shared Searches

### PR DESCRIPTION
**Pull request by arboliveira**
Authors: @rodrigopaulino @arboliveira
Reviewer: @mhan810

https://issues.liferay.com/browse/LPS-70535

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d28333a197...84683109aa

**Comment by brianchandotcom** [comment]
@arboliveira merged with minor changes in upstream. 

Is there a better name for SearchAwarePortlet?

I assumed it was a javax.portlet.Portlet. Can you rename it if you can think of a better name?

Thx.

**Comment by arboliveira** [comment]
Sure, will talk to the team and we'll come up with something clearer. Thank you Brian!!

**Pull request closed without merging**
