### PR TITLE
LPS-122483 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-122483

@ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure task is semantic versioning for com.liferay.portal.kernel.security.permission
See https://github.com/liferay-echo/liferay-portal/pull/2680
✔️ ci:test:stable - 14 out of 14 jobs passed
❌ ci:test:relevant - 51 out of 53 jobs passed in 1 hour 35 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/56386535d9...6642f99037

**Comment by brianchandotcom** [comment]
@ealonso I backported this to 7.3.x

**Pull request closed without merging**
