### PR TITLE
LPS-74104

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@Ithildir, still failing :(

**Comment by hhuijser** [comment]
@Ithildir, right now ```the source-format-jdk8``` passes because of your change.
However, ```modules-unit-jdk8``` is failing for the same reason.
I looked into it for a bit, but it's taking me too long to figure it out...

**Comment by Ithildir** [comment]
@hhuijser, I don't see a [`FAKE GRADLE CACHE`](https://github.com/brianchandotcom/liferay-portal/pull/50864#issuecomment-321620525) commit in this pull, right?

**Comment by hhuijser** [comment]
@Ithildir. You're right. I realized that was the problem. A ```FAKE GRADLE CACHE``` would have solved it

**Pull request closed without merging**
