### PR TITLE
LPS-70373 Adds creation of redirectURL if it not exist again

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
cc @jbalsas @carloslancha

**Comment by brianchandotcom** [comment]
@pyoo47 where are the results? all my pulls are this way.

**Comment by carloslancha** [comment]
@ealonso @pavel-savinov LGTM

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e0d9de7683...bc875ba8ef

**Pull request closed without merging**
