### PR TITLE
LPS-90508 build.gradle

### PR DESCRIPTION
**Pull request by ealonso**
Hey @brianchandotcom,

We are working on NPMResolverProvider duplication, but we want to have the other part on master.

I just sent the same pull without the last commit, we are going sent it when we have a solution for NPMResolverProvider.

Thanks!!

cc: @jbalsas

### CODE REVIEW

**Comment by ealonso** [comment]
cc: @brianchiu @kyle-miho

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
Re-running because of ci bug earlier

**Comment by brianchiu** [comment]
@ealonso There is a compile failure here. Can you take a look?

```
     [exec] > Task :apps:asset:asset-taglib:generateJSPJava FAILED
     [exec] org.apache.jasper.JasperException: file:/opt/dev/projects/github/liferay-portal/modules/apps/asset/asset-taglib/build/unzipped-jar/META-INF/resources/asset_tags_selector/init.jsp(17,57) PWC6188: The absolute uri: http://liferay.com/tld/soy cannot be resolved in either web.xml or the jar files deployed with this application
     [exec] 	at org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:92)
     [exec] 	at org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:378)
     [exec] 	at org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:172)
     [exec] 	at org.apache.jasper.compiler.TagLibraryInfoImpl.generateTLDLocation(TagLibraryInfoImpl.java:434)
     [exec] 	at org.apache.jasper.compiler.TagLibraryInfoImpl.<init>(TagLibraryInfoImpl.java:240)
     [exec] 	at org.apache.jasper.compiler.Parser.parseTaglibDirective(Parser.java:502)
     [exec] 	at org.apache.jasper.compiler.Parser.parseDirective(Parser.java:582)
     [exec] 	at org.apache.jasper.compiler.Parser.parseElements(Parser.java:1657)
     [exec] 	at org.apache.jasper.compiler.Parser.parse(Parser.java:185)
     [exec] 	at org.apache.jasper.compiler.ParserController.doParse(ParserController.java:244)
     [exec] 	at org.apache.jasper.compiler.ParserController.parse(ParserController.java:161)
     [exec] 	at org.apache.jasper.compiler.Parser.processIncludeDirective(Parser.java:394)
     [exec] 	at org.apache.jasper.compiler.Parser.parseIncludeDirective(Parser.java:431)
     [exec] 	at org.apache.jasper.compiler.Parser.parseDirective(Parser.java:574)
     [exec] 	at org.apache.jasper.compiler.Parser.parseElements(Parser.java:1657)
     [exec] 	at org.apache.jasper.compiler.Parser.parse(Parser.java:185)
     [exec] 	at org.apache.jasper.compiler.ParserController.doParse(ParserController.java:244)
     [exec] 	at org.apache.jasper.compiler.ParserController.parse(ParserController.java:145)
     [exec] 	at org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:212)
     [exec] 	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:451)
     [exec] 	at org.apache.jasper.JspC.processFile(JspC.java:1178)
     [exec] 	at org.apache.jasper.JspC.execute(JspC.java:1345)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at com.liferay.jasper.jspc.JspC._runWithClassPath(JspC.java:168)
     [exec] 	at com.liferay.jasper.jspc.JspC.main(JspC.java:46)
     [exec] Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
     [exec] 	at com.liferay.jasper.jspc.JspC.main(JspC.java:52)
     [exec] Caused by: java.lang.reflect.InvocationTargetException
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at com.liferay.jasper.jspc.JspC._runWithClassPath(JspC.java:168)
     [exec] 	at com.liferay.jasper.jspc.JspC.main(JspC.java:46)
     [exec] Caused by: org.apache.jasper.JasperException: file:/opt/dev/projects/github/liferay-portal/modules/apps/asset/asset-taglib/build/unzipped-jar/META-INF/resources/asset_tags_selector/page.jsp(17,0) file:/opt/dev/projects/github/liferay-portal/modules/apps/asset/asset-taglib/build/unzipped-jar/META-INF/resources/asset_tags_selector/init.jsp(17,57) PWC6188: The absolute uri: http://liferay.com/tld/soy cannot be resolved in either web.xml or the jar files deployed with this application
     [exec] 	at org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:81)
     [exec] 	at org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:376)
     [exec] 	at org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:143)
     [exec] 	at org.apache.jasper.compiler.Parser.processIncludeDirective(Parser.java:398)
     [exec] 	at org.apache.jasper.compiler.Parser.parseIncludeDirective(Parser.java:431)
     [exec] 	at org.apache.jasper.compiler.Parser.parseDirective(Parser.java:574)
     [exec] 	at org.apache.jasper.compiler.Parser.parseElements(Parser.java:1657)
     [exec] 	at org.apache.jasper.compiler.Parser.parse(Parser.java:185)
     [exec] 	at org.apache.jasper.compiler.ParserController.doParse(ParserController.java:244)
     [exec] 	at org.apache.jasper.compiler.ParserController.parse(ParserController.java:145)
     [exec] 	at org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:212)
     [exec] 	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:451)
     [exec] 	at org.apache.jasper.JspC.processFile(JspC.java:1178)
     [exec] 	at org.apache.jasper.JspC.execute(JspC.java:1345)
     [exec] 	... 6 more
     [exec] Caused by: org.apache.jasper.JasperException: file:/opt/dev/projects/github/liferay-portal/modules/apps/asset/asset-taglib/build/unzipped-jar/META-INF/resources/asset_tags_selector/init.jsp(17,57) PWC6188: The absolute uri: http://liferay.com/tld/soy cannot be resolved in either web.xml or the jar files deployed with this application
     [exec] 	at org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:92)
     [exec] 	at org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:378)
     [exec] 	at org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:172)
     [exec] 	at org.apache.jasper.compiler.TagLibraryInfoImpl.generateTLDLocation(TagLibraryInfoImpl.java:434)
     [exec] 	at org.apache.jasper.compiler.TagLibraryInfoImpl.<init>(TagLibraryInfoImpl.java:240)
     [exec] 	at org.apache.jasper.compiler.Parser.parseTaglibDirective(Parser.java:502)
     [exec] 	at org.apache.jasper.compiler.Parser.parseDirective(Parser.java:582)
     [exec] 	at org.apache.jasper.compiler.Parser.parseElements(Parser.java:1657)
     [exec] 	at org.apache.jasper.compiler.Parser.parse(Parser.java:185)
     [exec] 	at org.apache.jasper.compiler.ParserController.doParse(ParserController.java:244)
     [exec] 	at org.apache.jasper.compiler.ParserController.parse(ParserController.java:161)
     [exec] 	at org.apache.jasper.compiler.Parser.processIncludeDirective(Parser.java:394)
     [exec] 	... 16 more
```

```
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':apps:asset:asset-taglib:generateJSPJava'.
     [exec] > Process 'command '/opt/java/jdk1.8.0_121-x64/bin/java'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:asset:asset-taglib:generateJSPJava'.
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
     [exec] 	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
     [exec] 	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
     [exec] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
     [exec] 	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
     [exec] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
     [exec] 	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
     [exec] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
     [exec] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
     [exec] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
     [exec] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
     [exec] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
     [exec] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
     [exec] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
     [exec] 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
     [exec] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
     [exec] 	at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
     [exec] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
     [exec] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
     [exec] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
     [exec] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
     [exec] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
     [exec] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
     [exec] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
     [exec] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
     [exec] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
     [exec] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
     [exec] Caused by: org.gradle.process.internal.ExecException: Process 'command '/opt/java/jdk1.8.0_121-x64/bin/java'' finished with non-zero exit value 1
     [exec] 	at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:395)
     [exec] 	at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJavaExecAction.java:37)
     [exec] 	at org.gradle.api.tasks.JavaExec.exec(JavaExec.java:79)
     [exec] 	at com.liferay.gradle.plugins.jasper.jspc.CompileJSPTask.exec(CompileJSPTask.java:70)
     [exec] 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
     [exec] 	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
     [exec] 	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
     [exec] 	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
     [exec] 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:801)
     [exec] 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:768)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
     [exec] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
     [exec] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
     [exec] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
     [exec] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
     [exec] 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
     [exec] 	... 31 more
```

**Pull request closed without merging**
