### PR TITLE
LPS-57504 Rename params. API is confusing due the settings id is named as SERVICE_NAME. Service name is one of the possible values of the settingsId but not the only one (cherry picked from commit dedd58d)

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
I've checked the test failures. None of them seems to be related to the changes in this pull.

**Comment by JorgeFerrer** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@jkappler What's the relationship between ModuleConfiguration* and Configuration*

See modules/portal/portal-configuration-module/src/com/liferay/portal/configuration/module/ModuleConfigurationInvocationHandler.java

I'm not sure if it's returning a different thing or the same thing. We have lots of vars like configuration* or getConfiguration*?

Can you namespace or rename to clarify, or is it the best as is?

Please resend.

Thx. 
cc @JorgeFerrer

**Comment by JorgeFerrer** [comment]
Resent as https://github.com/brianchandotcom/liferay-portal/pull/28817

**Pull request closed without merging**
