### PR TITLE
Lps 67992

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@shuyangzhou @Preston-Crary this one has broken twice

LayoutRequestPortletContainerTest.testLayoutRequest

Only this pull.

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@brianchandotcom this is the know problem that @tinatian is working on. It is not caused by this pull.

**Comment by brianchandotcom** [comment]
@shuyangzhou @Preston-Crary please backport .Thx.

**Pull request closed without merging**
