### PR TITLE
master-qa-15734

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LRQA-15734

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@kenjiheigel @michaelhashimoto

This failure looks kind of weird. Poshi report doesn't show any steps having run. Poshi summary shows the steps having passed.

**Comment by kenjiheigel** [comment]
It appears as though PortalSmoke fails due to the same issue on another PR: 
https://github.com/brianchandotcom/liferay-portal/pull/29148

It appears to be due to the shutdown error issue ([LPS-57789](https://issues.liferay.com/browse/LPS-57789)), but we'll need to investigate why there's no test steps being generated.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b5a8cb3d46...7c8ae53764

**Pull request closed without merging**
