### PR TITLE
LPS-89670 Enabled old mapping logic

### PR DESCRIPTION
**Pull request by p2kmgcl**
/cc @ealonso
/cc @sandrodw3

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sandrodw3** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
