### PR TITLE
LPS-164449 Create Date and Modified Date are not working correctly when using HSQL Database Engine 2.3

### PR DESCRIPTION
**Pull request by thienquach87**
@brianchandotcom 
Here is the PR forwarded from https://github.com/liferay-objects/liferay-portal/pull/1338. It was passed review's Object team.
Please help review and leave your feedback.

Thanks,
Thien

### CODE REVIEW

**Comment by thienquach87** [comment]
ci:open

**Comment by thienquach87** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b84f042d72...275dec5507

**Comment by brianchandotcom** [comment]
@thienquach87 see changes in my origin. I kept your logic but mainly SF'd it.

**Comment by brianchandotcom** [comment]
@thienquach87 can you add an integration test for this? Thx.

**Pull request closed without merging**
