### PR TITLE
LPS-99142 the sendRedirect the last call

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
@brianchandotcom 
Thank you for pointing it out!!

**Comment by brianchandotcom** [comment]
Merged. Thank you.

**Comment by brianchandotcom** [comment]
@AliciaGarciaGarcia see my changes in upstream, quite a few. Thx.

**Comment by brianchandotcom** [comment]
lbm:backport @CsabaTurcsan @jpince @zsoltbalogh

**Pull request closed without merging**
