### PR TITLE
LPS-109535 Revert 8536cc3a043

### PR DESCRIPTION
**Pull request by brunofarache**

### CODE REVIEW

**Comment by brunofarache** [comment]
ci:test:forms

**Comment by brunofarache** [comment]
ci:test:relevant:app-builder

**Comment by brunofarache** [comment]
ci:test:app-builder

**Comment by brunofarache** [comment]
Hello @matuzalemsteles!

That PR broke App Builder and Forms: https://github.com/brianchandotcom/liferay-portal/pull/85429

I'm reverting your changes. Basically, `$localizedValue` can also be a map such as `{en_US: 'text'}` and you are considering it's always a list. I can show you on Monday and can make the right fix together. Had to rollback because we are closer to the release and this would be a blocker, this doesn't affect Journal as the feature flag is disabled by default.

That PR didn't pass in several Forms tests but it was merged anyways. Please, when changing the Form Builder stuff, run `ci:test:forms` or `ci:test:app-builder` and wait for tests results. You can talk to @cvanut to make sure there are no false negatives in the results.

cc'ing @wincent @victorg1991 @natocesarrego @carolmariaabb to reminder to run those tests too.

**Comment by matuzalemsteles** [comment]
hey @brunofarache yeah, I was converting this object via Metal, but I had forgotten about the server rendering, this was fixed and sent to @natocesarrego earlier today. https://github.com/natocesarrego/liferay-portal/pull/316

**Comment by brunofarache** [comment]
Closing this as @matuzalemsteles just told me this has been fixed by https://github.com/natocesarrego/liferay-portal/pull/316.

**Comment by wincent** [comment]
Thanks for the heads up @brunofarache. I explicitly did manual QA of app-builder when I sent that PR, but it just goes to show that I don't know the product well enough to actually realize when things are broken. And I didn't know about `ci:test:forms` or `ci:test:app-builder` — I'll make a note of those for next time.

**Comment by brunofarache** [comment]
thanks for taking your time to manually test it, @wincent!

the bug wasn’t so obvious to be found, had to edit an entry to show it up.

Forms was pretty broken though, as most of their tests were failing. I think it’s enough to run ci:test:forms since they have many more tests than we have in app builder.

**Comment by wincent** [comment]
I know this is a known problem, and people are working on it, but we obviously want to go towards a world in which:

- You shouldn't have to *know* when to run `ci:test:forms` (or anything but `ci:test:relevant`) — our heuristics should be robust enough to run tests when they are needed.
- CI is robust enough that, when tests do run and are red, it is a *clear* sign not to merge (unlike now, when the tests tend to flap so hard that it is difficult to distinguish between false positives and real issues).

@brunofarache: do you know which of those areas we fell down in on that PR? One or both?

**Comment by brunofarache** [comment]
Hey @wincent!

In the case of that specific PR, `ci:test:relevant` was enough to notice there was something wrong with Forms, we didn't have to do anything.

I mentioned `ci:test:forms` because I think it tests for more things than just `ci:test:relevant`. @cvanut can confirm that. We usually don't want to run this because it takes much longer than just the relevant tests.

**Pull request closed without merging**
