### PR TITLE
LPS-72583 Don't swallow exception cause

### PR DESCRIPTION
**Pull request by shuyangzhou**
@hhuijser anyway we can SF this?

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by hhuijser** [comment]
@shuyangzhou, logic is already in SF, but only applied to PortalException and SystemException (see LPS-36174)

**Comment by hhuijser** [comment]
Just a heads up. If we apply the logic to any exception, we have 1107 violations in portal.

**Comment by shuyangzhou** [comment]
@hhuijser how do I apply it to any exception?
We can try to clean them up as many as we can. But there must be some cases that we can not change, we need a way to ignore those manually.

**Comment by hhuijser** [comment]
@shuyangzhou 

Right now, we have PortalException/SystemException hardcode in the check. I quickly added a few lines to UnprocessedExceptionCheck to get the results for any Exception.

See https://gist.github.com/hhuijser/33f0bb3b300cb0fc0c74d38dd7c048d1#file-unprocessedexceptioncheck-java-L88-L94

**Comment by hhuijser** [comment]
FYI: https://gist.github.com/hhuijser/43a5168054ca72d93383c36de861308f

**Comment by hhuijser** [comment]
Let me know if this list includes false positives.

**Comment by shuyangzhou** [comment]
@hhuijser thanks! I will have someone from my team going through the list tomorrow.

**Comment by tomwang2011** [comment]
Hi @hhuijser can we filter the list with the following parameters: We want to look inside the catch block to see if it is throwing another exception.

For example: In `BlogsEntryLocalServiceImpl line 1656`, once we catch the IOException, instead of throw `new EntryCoverImageCropException()`, we should do `throw new EntryCoverImageCropException(ioe)`. 

Once we have a list of occurrences where the catch block is throwing a new exception and it does not use the caught exception in the try block, we will work on re-throwing the new exception with the caught exception's cause.

Thanks!

**Comment by hhuijser** [comment]
@tomwang2011 @shuyangzhou, I think that's doable. Will look into that.

**Pull request closed without merging**
