### PR TITLE
LRQA-62682 Add new property to properties list

### PR DESCRIPTION
**Pull request by vicnate5**
also for 7.3.x

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4fa75adee9...f3c8722308

**Comment by brianchandotcom** [comment]
@vicnate5 
I backported this to 7.3.x.

**Comment by brianchandotcom** [comment]
@vicnate5 can you send me a follow up pull?

```
         direct.deploy.enabled,\
        disable.commerce,
```

Can you rename 'disable.commerce' to

'commerce.enabled', see 'direct.deploy.enabled' and 'elastic.xpack.enabled'

**Pull request closed without merging**
