### PR TITLE
master-vw-402

### PR DESCRIPTION
**Pull request by vicnate5**
Thanks @inacionery!

cc @kenjiheigel @alee8888

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 this somehow didn't get triggered?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c9557d7d50...5b0737ce64

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:stop

**Pull request closed without merging**
