### PR TITLE
LPS-74672 SF

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @IstvanD @topolik

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop (this is good. .merging)

**Comment by brianchandotcom** [comment]
@sergiogonzalez can you resend on top of https://github.com/sergiogonzalez/liferay-portal/pull/4068

I searched for *AuthVerifierFilter* and most classes that implement this are in a different package. Can you resend after moving around packages? Just the same things I've mentioned for sharepoint-hook. Thx.

**Pull request closed without merging**
