### PR TITLE
LPS-145116 - Apply new icons API throughout DXP

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Follow up from: https://github.com/bryceosterhaus/liferay-portal/pull/83

Manual forward from https://github.com/liferay-frontend/liferay-portal/pull/2267

QA Approval: https://github.com/liferay-frontend/liferay-portal/pull/2267#issuecomment-1139449870

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fa29ab75a4...e3b7564bab

**Comment by brianchandotcom** [comment]
@bryceosterhaus I merged this! Thanks for this big PR! It's a nice change.

**Comment by brianchandotcom** [comment]
@bryceosterhaus I only made minor changes. See my origin.

**Pull request closed without merging**
