### PR TITLE
LPS-98399 Added highlighted state to Background Image Editables

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
@ealonso

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b73b795f10...18cad56d37

**Comment by brianchandotcom** [comment]
lbm:backport @CsabaTurcsan @jpince @zsoltbalogh

**Pull request closed without merging**
