### PR TITLE
Lps 72343

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
This pull doesn't seem to cause the spi-admin-portlet error... but that module hasn't been modified at head since March. https://github.com/liferay/liferay-portal-ee/commits/ee-7.0.x/modules/private/apps/spi

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/baa791bdb8...326d64c105

**Pull request closed without merging**
