### PR TITLE
LPS-82184 Use a prepared statement rather than running a query

### PR DESCRIPTION
**Pull request by achaparro**
cc/ @SamZiemer

### CODE REVIEW

**Comment by achaparro** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/55e7f49359...1d8639f9b9

**Comment by brianchandotcom** [comment]
@SamZiemer @achaparro are you sure it's supposed to be

```like ?```

Just double checking. Thx.

**Comment by achaparro** [comment]
Hi @brianchandotcom,

Using "=" with a clob type fails in some databases. We have to use like instead, in this case is not really problematic for two reasons:
- The tables affected are not large regarding the number of records.
- We don't use "%" at the beginning of the string to compare so the query will use the index if possible.

@SamZiemer, could you confirm that is the reason you removed the "like"?

Thanks!

**Comment by SamZiemer** [comment]
Hi @achaparro, @brianchandotcom Yes, those were the reasons to use like in this case.

**Pull request closed without merging**
