### PR TITLE
LPS-126326 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-126326

This is only for master.

@david-gutierrez-mesa
@alexcandidos

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure cases are unrelated to changes in PR.
See https://github.com/liferay-echo/liferay-portal/pull/3636
✔️ ci:test:stable - 9 out of 9 jobs passed
❌ ci:test:relevant - 23 out of 26 jobs passed in 3 hours 6 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e8f92b01e9...8e5650b861

**Comment by brianchandotcom** [comment]
@gleicelisbino Please review changes.

**Pull request closed without merging**
