### PR TITLE
[B] LPS-62989 Open service tracker map

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6bdba966e5...a2a216e8fb

**Comment by brianchandotcom** [comment]
@hhuijser can you enforce via SF "Never use com.liferay.registry.collections in modules"

**Comment by hhuijser** [comment]
@brianchandotcom @rotty3000 

This one has been in Ray's queue already for a while, but those couple of files that were using it were blocking it: https://github.com/rotty3000/liferay-portal/pull/1139

Looks like it's safe to commit now? Will have a look.

**Comment by hhuijser** [comment]
@rotty3000 

We still have two files in modules that are using com.liferay.registry.
When those are fixed, I can add the check to SF.

modules/apps/foundation/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/result/SearchResultManagerImpl.java
modules/core/jaxws-osgi-bridge/src/main/java/com/liferay/jaxws/osgi/bridge/Provider.java

**Comment by rotty3000** [comment]
@arboliveira @csierra could you please remove the usage of RegistryUtil in the cases mentioned by @hhuijser above? They are non-compliant and must be addressed!

**Comment by csierra** [comment]
Yup...

**Comment by csierra** [comment]
hey guys...

I am a bit absent minded today... after creating the patch I realized that this one *MUST* use the Registry because this is not run inside OSGi. This is actually the bridge that adapts the service loader to use a provider inside OSGi, but this is not deployed in the framework.

**Comment by rotty3000** [comment]
ok @hhuijser you then have to include this module as an exclusion from this compliance check.

**Comment by arboliveira** [comment]
@adolfopa Check this out: https://github.com/liferay/liferay-portal/blame/c08f9276c246229d9ec4d7d2fcc462e236720bfb/portal-impl/src/com/liferay/portal/search/SearchResultManagerImpl.java#L97-L135

Could you please look into this and remove the references to `com.liferay.registry` as per @rotty3000's request? Thanks!

**Comment by csierra** [comment]
mmmh... but that's inside `portal-impl`... isn't it? are we removing the references there too?

**Comment by arboliveira** [comment]
@csierra It was inside `portal-impl` back in May 2015 when @adolfopa worked on it... since then it's been moved to the `portal-search` OSGi module.

https://github.com/liferay/liferay-portal/blob/021d522b9a379ea9a809b7a4540e43298ea4d1b3/modules/apps/foundation/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/result/SearchResultManagerImpl.java#L122-L138

**Comment by csierra** [comment]
the link you sent was to portal-impl and that confounded me... I will :speak_no_evil: now

**Comment by arboliveira** [comment]
:trollface:

**Pull request closed without merging**
