### PR TITLE
LPS-90415 Vocabulary CRUD implementation

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
My bad.. I'll work on either renaming them all to *Supplier or find some annotation hint for jackson

See f61af1e for my consolidation of the _merge method.

**Comment by brianchandotcom** [comment]
@ruben-pulido I think we can use a JsonIgnore attribute

https://stackoverflow.com/questions/12595351/jersey-jackson-jsonignore-on-setter

Can you send me a quick curl to test it?

**Comment by ruben-pulido** [comment]
Hi @brianchandotcom

Here is a POST and a GET example:

```

**Comment by brianchandotcom** [comment]
See f95a2cbce69fd7c8244827b332d7079090eb1fce to c9436f0fac8d8cd2597c14f94da217ce18df82ee

Thanks for the curl commands. I was in the middle of splitting DTOs to interfaces and implementations, and was able to fix the issue with the set*Supplier in dea582e086f4ca5e3009a443d558b60683f014f7

**Pull request closed without merging**
