### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
Unrelated failures only: https://github.com/hhuijser/liferay-portal/pull/5624

**Comment by hhuijser** [comment]
@brianchandotcom, run `ant format-source-files -Dsource.formatter.commit.count=200` (or whatever number you want to use)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/591ce15d1c...58d5941e04

**Pull request closed without merging**
