### PR TITLE
Lps 141790

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
@brianchandotcom we have ran all related tests we could think about, and @kyle-miho checked the results here https://github.com/shuyangzhou/liferay-portal/pull/10459 , but this pull is still kind of a risky one. If you want to be safer, please merge it after the release is out.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8137a78f59...aec51ef637

**Comment by brianchandotcom** [comment]
@marianoalvarosaiz @shuyangzhou looks good to me.

**Pull request closed without merging**
