### PR TITLE
LPS-107131 Update liferay-npm-scripts to v18.0.0

### PR DESCRIPTION
**Pull request by wincent**
The principal motivating change here is to allow us to strip React propTypes in production, reducing the amount of code that we ship to the client.

In addition, a number of dependencies are updated (ESLint and Prettier updates), which will require us to apply formatting and a lint fix: I've split those into separate commits to make it clear exactly what changes are needed.

### CODE REVIEW

**Comment by wincent** [comment]
cc @jeyvison @brunobasto: There is a Prettier update in here which makes some pretty huge changes to an `app-builder-web` file (`ViewEntry.es.js`) due to an indentation change, but I don't see any recent activity from you guys in there so hopefully this won't cause any conflicts.

**Comment by brunobasto** [comment]
Thank you, @wincent!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/61382a5b58...4c7f858922

**Comment by brianchandotcom** [comment]
@wincent merging this.. trusting you that this is good.

**Pull request closed without merging**
