### PR TITLE
LPS-171583 Set the new configuration fields in a different fieldSet 

### PR DESCRIPTION
**Pull request by Tim-Cao**
This is only for master.

https://issues.liferay.com/browse/LPS-171583

@lfbesada

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/10677

**Comment by lfbesada** [comment]
Resent [here](https://github.com/liferay-echo/liferay-portal/pull/10686) fixing the conflicts

**Comment by lfbesada** [comment]
ci:close

**Pull request closed without merging**
