### PR TITLE
LPS-196591 Make available locked pages settings at site level

### PR DESCRIPTION
**Pull request by alessandromalves**
Resending again the PR because a rebase error when Brian tried to merge it. https://github.com/brianchandotcom/liferay-portal/pull/141893#issuecomment-1752177606

story: https://liferay.atlassian.net/browse/LPS-194241
subtask: https://liferay.atlassian.net/browse/LPS-196591

cc.: @Mikellorza

### CODE REVIEW

**Comment by alessandromalves** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/13945

✔️ ci:test:stable - 30 out of 30 jobs passed
❌ ci:test:relevant - 187 out of 203 jobs passed in 2 hours 29 minutes

**Comment by alessandromalves** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9b1d5bf0b4...5195598e0f

**Comment by brianchandotcom** [comment]
This was VERY good @Mikellorza you totally understand the patterns and applied them intuitively. GREAT job.

**Pull request closed without merging**
