### PR TITLE
LPS-102770 Matching on module web contexts should be by full path

### PR DESCRIPTION
**Pull request by csierra**
/cc @stian-sigvartsen @arthurchan35

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e86981e763...4365201ae7

**Comment by brianchandotcom** [comment]
@stian-sigvartsen test? thx.

**Comment by stian-sigvartsen** [comment]
Thanks @brianchandotcom . I will send a test

**Comment by brianchandotcom** [comment]
@stian-sigvartsen @csierra @nhpattI had to revert this because it causes a regression in upstream.

**Comment by stian-sigvartsen** [comment]
Thanks @brianchandotcom . We'll re-send soon.

**Pull request closed without merging**
