### PR TITLE
LPS-77331 Correct condition

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@shuyangzhou the test change you sent me yesterday is broken. See 

```
junit.framework.AssertionFailedError: expected:<[key1=
key3=null
]> but was:<[]>
	at com.liferay.portal.kernel.util.UnicodePropertiesTest.testSetBlankProperty(UnicodePropertiesTest.java:35)
```

**Comment by shuyangzhou** [comment]
@brianchandotcom I think you lost one commit when merging my pull, https://github.com/brianchandotcom/liferay-portal/pull/57018/commits/9c34f553e8ebad8c17a4e647c5d623b76e9c4f95 is not in master.

**Pull request closed without merging**
