### PR TITLE
LPS-75529 Get appropriate template language type

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@pavel-savinov I merged and backported this.. but the LPS ticket looks wrong?

**Comment by pavel-savinov** [comment]
@brianchandotcom Sorry, my typo... it was LPS-75**7**29

**Comment by pavel-savinov** [comment]
@brianchandotcom Reset with revert [here](https://github.com/brianchandotcom/liferay-portal/pull/52842). Thanks!

**Pull request closed without merging**
