### PR TITLE
Lps 68202

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
@tomwang2011 backport please, then ee's lpkg problem should be fixed.

**Comment by shuyangzhou** [comment]
ci:retest

@brianchandotcom force pushed to fix something in the last commit, please let the retest finish before merging.

**Comment by brianchandotcom** [comment]
@shuyangzhou merged and backported. Thx! @tomwang2011 this cherry picked cleanly.

**Pull request closed without merging**
