### PR TITLE
LPS-61088 Not needed

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e4dfaf1848...8acaec48df

**Comment by brianchandotcom** [comment]
@hhuijser can you SF enforce this? Thx.

**Comment by hhuijser** [comment]
@brianchandotcom @Ithildir 

We had this logic in place... looks like Shuyang reverted it: https://github.com/liferay/liferay-portal/commit/1a470aa1dd88dd7d89c086553476c7a811bb6c17

@shuyangzhou, what was the reason for reverting this?

**Comment by shuyangzhou** [comment]
@hhuijser It was breaking CI build, I reverted it here https://github.com/brianchandotcom/liferay-portal/pull/35460 , I CCed you, you probably missed the message.

**Comment by hhuijser** [comment]
@shuyangzhou 

Got it... thanks

**Pull request closed without merging**
