### PR TITLE
LPS-75049

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:stop

**Comment by Ithildir** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:stop (The wildfly dist build froze for some unknown reason)

**Comment by pyoo47** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:reopen

**Comment by Ithildir** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/52269.

**Pull request closed without merging**
