### PR TITLE
LPS-101013 Update welcome image 7.3

### PR DESCRIPTION
**Pull request by edalgrin**

### CODE REVIEW

**Comment by eduardoallegrini** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@pyoo47 @petershin what's going on with this DXP Documentum issue? I've seen it kill several pulls.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/47857ef6d8...71eec02379

**Comment by brianchandotcom** [comment]
@eduardoallegrini actually, I reverted this. Can you send me another photo?

Instead of an image of trees and nature, I want one of Alexandria the city.. or of papyrus or something related to Athanasius of Alexandria since this release is named after him.

I'm not looking for a photo that ppl can see and instantly recognize as Athanasius. That would be ugly. I want a photo that relates to but is not immediately identifiable. Not sure if that makes sense..  

So if it was for Luke Skywalker, we might show 2 suns since Tatooine has 2 suns..

Or of it was  Yoda, we might show a very up close image of his cane.. and you might not even know it was a cane at first pass.

Or if it was Anakin.. you might show a robot repair shop.

hope that makes sense. So for Athanasius (https://en.wikipedia.org/wiki/Athanasius_of_Alexandria) I thought of papyrus or something from that city.

Have fun! Send me a few images on Slack if you can't decide.

@jpince fyi you can give more guidance to @eduardoallegrini or the designer who picks this if they are confused.

**Comment by eduardoallegrini** [comment]
Hi @brianchandotcom , I'll ask the design team but I got what you mean

**Comment by jpince** [comment]
@brianchandotcom I asked for exactly what you told me, see the ticket [LPS-101013](https://issues.liferay.com/browse/LPS-101013). This is what @emiliano-cicero replied as the decision from the Design team:
> I tried to work with your proposal of Papyrus but couldn't find anything that could work as well as the mountains.
> Also, we're coming from 3 past releases with related mountain images and the idea from a design perspective is to keep the same subject until the 8.0 release where we could find a new theme.
> 
> The idea behind this new image is to include elements that remind of growth and product evolution, showing part of the land and the green trees for that purpose and keeping the mountains as a common element of stability in all the images. 
> 
> I also made sure to have this images reviewed from other design members that found it a good fit for the 7.3 release.

With that context, let us know if you still want them to pursue your idea. 
cc/ @victorvalle

**Comment by petershin** [comment]
@brianchandotcom - The failure look like its caused by a network hiccup.

```
Could not resolve all files for configuration ':dxp:apps:documentum:documentum-hook:ivyCopyIvyDependencies'.
[exec] > Could not download com.rsa.jsafe.jar (com.liferay:com.rsa.jsafe:3.6)
[exec]    > Could not get resource 'http://repository-cdn.liferay.com/nexus/service/local/repo_groups/private/content/com/liferay/com.rsa.jsafe/3.6/com.rsa.jsafe-3.6.jar'.
[exec]       > Read timed out
```

Would it be ok to create a `liferay-binaries-cache-ci-2020` private subrepo that contains all the files needed for building both CE/DXP projects?

**Comment by brianchandotcom** [comment]
@eduardoallegrini  140fd6092d2b4d41d7974c7db23b0321d7eb79e4

@petershin we're switching to a new Nexus soon so this problem should go away.

**Pull request closed without merging**
