### PR TITLE
LRQA-53550, LRQA-53712, LRQA-53614 | master

### PR DESCRIPTION
**Pull request by liulukiwi**
https://issues.liferay.com/browse/LRQA-53550
https://issues.liferay.com/browse/LRQA-53712
https://issues.liferay.com/browse/LRQA-53614

This is only for master, thanks!

cc @manoelcyreno

### CODE REVIEW

**Comment by liulukiwi** [comment]
No test changes needed :)

**Comment by liulukiwi** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/81055

**Comment by liulukiwi** [comment]
Reopen it, I don't intend to close this pull

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4e06a5cf6c...bf9e35f52f

**Pull request closed without merging**
