### PR TITLE
LPS-158781 Semver

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/35bf6524a0...6dc98d4baa

**Comment by brianchandotcom** [comment]
@MarinhoFeliphe in the future, if I do update the status, it won't trigger a model listener either.

You need to make it so it only doesn't do this when it's truly a new object.

**Comment by MarinhoFeliphe** [comment]
@brianchandotcom

I tested this scenario,

It will trigger properly the model listener if I change the workflow status,

[this line](https://github.com/brianchandotcom/liferay-portal/pull/124159/files#diff-7589fd6b7889e2cca3cb3194d8a3b63acbd83d37a8db6121c4b61443ccc262b3R159) solve it

**Comment by MarinhoFeliphe** [comment]
ci:reopen

**Pull request closed without merging**
