### PR TITLE
Upgrade Process: fix upgrade processes

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Thx @migue @matethurzo 

I made a tiny change and removed the constant, but otherwise, it's good.

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
@matethurzo can you also check out b336bd6e8a4663792892b75baff316be7a3263da

**Pull request closed without merging**
