### PR TITLE
LPS-183217 Add indexes to object relationship many-to-many dynamic tables

### PR DESCRIPTION
**Pull request by guilhermedcamacho**
CI [errors](https://github.com/liferay-objects/liferay-portal/pull/2084#issuecomment-1540628484) are not related.

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/696fd83f75...8c6d267b7b

**Comment by brianchandotcom** [comment]
@mateussgn just 8c6d267b

**Comment by mateussgn** [comment]
Thanks, @brianchandotcom!

**Pull request closed without merging**
