### PR TITLE
LPS-81270 Ignore site group id parameter in the friendly url routes

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@ealonso p_v_l_s_g_id needs to be added/recorded in PortalImpl if it's one of those p_* special params? If not, please rename it so it doesn't sound so global / portlet container / portal level.

Search for the word "reserved"

Thx

**Comment by ealonso** [comment]
@pavel-savinov

**Comment by pavel-savinov** [comment]
@brianchandotcom @ealonso It is reserved already. https://github.com/brianchandotcom/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/util/PortalImpl.java#L510

**Pull request closed without merging**
