### PR TITLE
LPS-66016 Portlets added to Nested Portlets are not carried over to 7.0

### PR DESCRIPTION
**Pull request by jkappler**
@brianchandotcom, I changed language keys to standardize name (although it was not related to nested portlets)

I sent myself the PR before resending and all the test passed.

### CODE REVIEW

**Comment by jkappler** [comment]
cc:/ @ealonso

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/541fe86c51...5ead92d6c2

**Comment by brianchandotcom** [comment]
@jkappler so strange that we had a language key error. I reverted your commit for that because SF didn't really need it. Not sure how that happened. (We should never rename a key to hack around things like this.)

**Comment by jkappler** [comment]
Hi @brianchandotcom, thanks, I'll keep that in mind

**Pull request closed without merging**
