### PR TITLE
LPS-62329 audio and video buttons for alloy editor for Journal

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @codyhoag :)

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7325efe1a7...f6961a00cd

**Comment by brianchandotcom** [comment]
@antoniopol06 @juliocamarero I found a bug in dfec8d2a8a91955fc8e0687c5f3f1a3b1e4157c4

Can you guys check my other changes in upstream? Thx.

**Pull request closed without merging**
