### PR TITLE
LPS-106424 regen

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/346ca8e075...b3b25d22cf

**Comment by brianchandotcom** [comment]
Wow @jeyvison @brunofarache this was so good. The only thing I did was I put all the generated code into one commit and I made it the first commit. Then I also ran baseline here 21ab666171c36fccf935e4473f42447c8d7f0bd6.

@nhpatt I'm hoping to 1.) merge i your permissions code and then 2.) have you remove it from here.

**Comment by brunofarache** [comment]
@nhpatt @brianchandotcom we prefer to replace with Javier's permission APIs ourselves. We would like to go through testing.

**Comment by nhpatt** [comment]
Ok! :)

**Pull request closed without merging**
