### PR TITLE
LPS-64908 fix duplicated success messages when deleting a page

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Hey @evannagayama, 

I wonder if this pull may break a functional test. Now, the user won't see the link to delete the last page of the guest site.

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8936ef5c07...b525cc43fe

**Comment by brianchandotcom** [comment]
@juliocamarero I made a few renames in upstream. Please review? Thx!

**Comment by evannagayama** [comment]
@juliocamarero I don't think we try to delete the last page, except for one test that tests you can't delete the last page on the Liferay site, so it seems to be ok.

**Comment by juliocamarero** [comment]
Great. Thanks @evannagayama !! the changes look good @brianchandotcom! Thank you!

**Pull request closed without merging**
