### PR TITLE
LPS-83949 Fix tests

### PR DESCRIPTION
**Pull request by izaera**
Originally sent as [#67873 (comment)](https://github.com/brianchandotcom/liferay-portal/pull/67873#issuecomment-462714194) but had to fix the tests 😬 .

> Hey @brianchandotcom, sorry for this big PR, but it was hard to send it in smaller chunks.

> This basically gets rid of a static `loader_js_modules` file that contained all the information about all the frontend modules in the system and replaces it for async and on-demand requests to resolve that from the server.

> This addresses both **security and performance** concerns.

> Please, let us know if there's anything you'd like us to change.

> Thanks!

### CODE REVIEW

**Comment by jpince** [comment]
@john-co this was autoclosed, should it be retested/reopened?

**Comment by john-co** [comment]
@jpince I'm going to rebase and retest.

**Comment by jpince** [comment]
@john-co ci commands will automatically rebase to head unless you tell it not to (I think if you don't want to rebase, you use ci:test:norebase)

**Comment by john-co** [comment]
ah good to know. Thanks!

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:reopen

**Comment by john-co** [comment]
ci:close

**Comment by izaera** [comment]
Hey guys, thank you very much for retesting 🙌 . I will continue with this on local to see what is failing exactly.

**Pull request closed without merging**
