### PR TITLE
LPS-78436

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@igorarouca, after this is in, you should be able to upgrade to use latest SF and also consolidate your suppressions files

**Comment by hhuijser** [comment]
@petershin

**Comment by hhuijser** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/42cfb0de6b...8c21e290ea

**Pull request closed without merging**
