### PR TITLE
LPS-77875

### PR DESCRIPTION
**Pull request by Ithildir**
Hi,
Please let this pull finish.

Thank you!

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:test

**Comment by Ithildir** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@Ithildir aren't the *-cdn urls just temporary?

**Comment by Ithildir** [comment]
Hi @brianchandotcom! I'm not sure, I'll ask 🤔

**Pull request closed without merging**
