### PR TITLE
LPS-54744 && LPS-59712

### PR DESCRIPTION
**Pull request by arbetts**
resending form: https://github.com/brianchandotcom/liferay-portal/pull/32273

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by arbetts** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e40316777e...7f83f79368

**Pull request closed without merging**
