### PR TITLE
LPS-101720 Update location

### PR DESCRIPTION
**Pull request by csierra**
/cc @arthurchan35

hi @brianchandotcom, 
here is another class from the MFA theme. I have updated it with some of the latest changes.

### CODE REVIEW

**Comment by csierra** [comment]
ci:reopen

**Comment by csierra** [comment]
ci:test:stable

**Comment by csierra** [comment]
hey @brianchandotcom, 
it looks like something unrelated is not compiling...

**Comment by brianchandotcom** [comment]
@csierra thx.. that was a bug by Javier that is fixed now in upstream.

Can you resend on top of: https://github.com/csierra/liferay-portal/pull/605

I found a few naming inconsistencies that should have been caught. See that pull.

Now I'm honing in on the usage of the word _email_ in your new code..

I stumbled on 

modules/dxp/apps/multi-factor-authentication/multi-factor-authentication-email-otp-web/src/main/resources/META-INF/resources/dependencies/email_multi_factor_authentication_email_otp_body.tmpl
modules/dxp/apps/multi-factor-authentication/multi-factor-authentication-email-otp-web/src/main/resources/META-INF/resources/dependencies/email_multi_factor_authentication_email_otp_subject.tmpl

Can you rename it to make it consistent with the usage of template files in journal-api, knowledge-base-api, etc.

Type:

git ls-files **email**.tmpl

your template files don't match their naming or package.

I'm also confused about how you're declaring some variables right now.. sometimes it's :

```
		String expectedOtp = (String)httpSession.getAttribute(
			MFAEmailOTPWebKeys.MFA_EMAIL_OTP);
```

sometimes it's

```
			httpSession.setAttribute(
				MFAEmailOTPWebKeys.MFA_EMAIL_OTP, generatedMFAEmailOTP);
```

See how the first one is not prefixed, but the second one is prefixed?

So little things like this makes it impossible for me to load the code into my brain.. and it's very disorienting.

Ok, with that said.. relax... breathe.. this is just code.. not a big deal. But, let's meet tomorrow morning early my time and I can screen share with you and you can see how I'm trying to mentally process this.

Perhaps once you see how I'm verifying/reviewing code line by line, then you can see where I'm getting confused and choked.

Thank you very much for your help @csierra

**Comment by csierra** [comment]
please see https://github.com/brianchandotcom/liferay-portal/pull/83750

**Pull request closed without merging**
