### PR TITLE
LRQA-50584 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LRQA-50584
7.2.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/27849

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/212a6c6d46...3f155d344f

**Comment by brianchandotcom** [comment]
@john-co @zhangyan0701 send me a follow up and sort the params please. Thx.

**Comment by zhangyan0701** [comment]
Sent the commit that sort the params:
master: [brianchandotcom/liferay-portal#81547](https://github.com/brianchandotcom/liferay-portal/pull/81547)
7.2.x: [brianchandotcom/liferay-portal-ee#27891](https://github.com/brianchandotcom/liferay-portal-ee/pull/27891)

**Comment by john-co** [comment]
Thanks @zhangyan0701!

**Pull request closed without merging**
