### PR TITLE
master-qa-61573

### PR DESCRIPTION
**Pull request by dellawang**
https://issues.liferay.com/browse/LRQA-61573
This is only for master.

@gaborlovasdotcom

### CODE REVIEW

**Comment by dellawang** [comment]
ci:reopen

**Comment by dellawang** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure case is not related to changes in PR.
See dellawang#130
✔️ ci:test:stable - 13 out of 13 jobs passed
❌ ci:test:relevant - 35 out of 37 jobs passed in 2 hours 53 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ae2b42b15a...29cf25b0f1

**Comment by brianchandotcom** [comment]
@dellawang I backported this to 7.3.x

**Pull request closed without merging**
