### PR TITLE
master-qa-20819

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-20819

### CODE REVIEW

**Comment by kenjiheigel** [comment]
@brianchiu, I added a new macro for the OSGi smoke tests, to consolidate the repeated steps. Let me know if you have any questions about it. I'm following the precedent of the Smoke.macro for PortalSmoke.testcase. Eventually I may combine/rename these OSGi test cases.

**Comment by kenjiheigel** [comment]
The failing test PGWiki#EditWikiFrontPage should be fixed by https://issues.liferay.com/browse/LRQA-20817 in https://github.com/brianchandotcom/liferay-portal/pull/33975

**Comment by brianchiu** [comment]
@kenjiheigel 
Sounds good. Thanks.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7679929fc1...06d2b76607

**Pull request closed without merging**
