### PR TITLE
LPS-92618.23 to dto

### PR DESCRIPTION
**Pull request by javiergamarra**
The easiest check is a simple string comparison if we don't return nulls in our serializer (that we shouldn't, either way).

Another quick option would be using jackson with tree or JsonNode (objectMapper.readTree(json1) .equals(objectMapper.readTree(json2)))

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@nhpatt can you resend on top of https://github.com/nhpatt/liferay-portal/pull/115

```
com.liferay.headless.admin.taxonomy.resource.v1_0.test.TaxonomyVocabularyResourceTest > testClientSerDesToJSON FAILED
    org.junit.ComparisonFailure: expected:<...:[{"required":false,["subtype":"AllAssetSubtypes","type":"AllAssetTypes"}],"description":"AYNXR5h2","name":"xIPlHf8V",]"siteId":38169}> but was:<...:[{"required":false,[ "subtype":"AllAssetSubtypes", "type":"AllAssetTypes"}], "description":"AYNXR5h2", "name":"xIPlHf8V", ]"siteId":38169}>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at com.liferay.headless.admin.taxonomy.resource.v1_0.test.BaseTaxonomyVocabularyResourceTestCase.testClientSerDesToJSON(BaseTaxonomyVocabularyResourceTestCase.java:175)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$2.evaluate(TestExecutorRunnable.java:181)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:79)
        at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:79)
        at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:79)
        at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:79)

```

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/152cf38af2...2d3027235f

**Comment by brianchandotcom** [comment]
Nvm... I had a bad branch.. I merged this and pushed it up. But I still think it's too brittle right now. For example, in the ser_des.ftl

```
if (sb.length() > 1) {
					sb.append(",");
				}

				sb.append("\"${propertyName}\":");

				<#if allSchemas[propertyType]??>
					sb.append(${propertyType}SerDes.toJSON(${schemaVarName}.get${propertyName?cap_first}()));
				<#else>
					<#if propertyType?contains("[]")>
						sb.append("[");

						for (int i = 0; i < ${schemaVarName}.get${propertyName?cap_first}().length; i++) {
							<#if stringUtil.equals(propertyType, "Date[]") || stringUtil.equals(propertyType, "String[]") || enumSchemas?keys?seq_contains(propertyType)>
								sb.append("\"");

								<#if stringUtil.equals(propertyType, "Date[]")>
									sb.append(liferayToJSONDateFormat.format(${schemaVarName}.get${propertyName?cap_first}()[i]));
								<#else>
									sb.append(${schemaVarName}.get${propertyName?cap_first}()[i]);
								</#if>

								sb.append("\"");
							<#elseif allSchemas[propertyType?remove_ending("[]")]??>
								sb.append(${propertyType?remove_ending("[]")}SerDes.toJSON(${schemaVarName}.get${propertyName?cap_first}()[i]));
							<#else>
								sb.append(${schemaVarName}.get${propertyName?cap_first}()[i]);
							</#if>

							if ((i + 1) < ${schemaVarName}.get${propertyName?cap_first}().length) {
								sb.append(", ");
```

Notice that we sometimes have "," and sometimes ", " (with a space). Can you make it work so we can always use ", " (with a space) Right now, if I change it, the test breaks. Thx. (Pushed upstream, please rebase and send a follow up pull).

**Comment by nhpatt** [comment]
Thanks! :)

**Pull request closed without merging**
