### PR TITLE
LPS-133987

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
Unrelated failures only: https://github.com/hhuijser/liferay-portal/pull/5664

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e5d8d366d5...b15d2c88c1

**Comment by brianchandotcom** [comment]
@ngriffin7a @hhuijser minor change in af9b92cffaadd0796260430af62fe1405fabed4d

**Pull request closed without merging**
