### PR TITLE
LPS-98731 bump to avoid CVE

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8394288e58...0e35b242dc

**Comment by brianchandotcom** [comment]
@nhpatt a better fix 

See 9074d1ea7ab7577c68cfaf0cdfdbd72d745ef676 and 330d02a2fa2370dd9fd717072311b046ada1e5d5

Next time master-private or commerce runs "gradlew formatSource", it'll up it for them.

**Comment by nhpatt** [comment]
@brianchandotcom pinged Hugo because of the sf error (didn't thought it was going to crash) but maybe it makes sense to do a revert until is fixed.

**Comment by brianchandotcom** [comment]
I fixed the SF.. it should be safe.

**Comment by nhpatt** [comment]
Thank you! :D Didn't know of the sf formatting to bump versions, pretty cool :)

**Pull request closed without merging**
