### PR TITLE
LPS-125556 regenerate after SF

### PR DESCRIPTION
**Pull request by javiergamarra**
CI failing because flaky tests: https://github.com/liferay-headless/liferay-portal/pull/527

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:reopen

**Comment by brianwulbern** [comment]
`SF` and `stable` have passed in https://github.com/liferay-headless/liferay-portal/pull/527

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/23d39a4175...13425d7fdd

**Comment by brianchandotcom** [comment]
@nhpatt my bad thx for fixing it

**Pull request closed without merging**
