### PR TITLE
LPS-78950 The isMale field in Users does not offer all the options that are often needed

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-78950](https://issues.liferay.com/browse/LPS-78950).

Hey @brianchandotcom, these are the 'soft' deprecation changes we discussed.

_relevant_ test results here: https://github.com/drewbrokke/liferay-portal/pull/703#issuecomment-450278176.  I checked out the functional test failures and they seem to be happening on other pulls too.
_upgrade_ test results here: https://github.com/drewbrokke/liferay-portal/pull/703#issuecomment-450283629.  The failures look the same as the ones we saw from the last pull I sent you.

/cc @pei-jung @stsquared99 @alee8888 @ChrisKian

### CODE REVIEW

**Comment by drewbrokke** [comment]
@jpince can I get some insight into this one?  I can't get it to fail locally.

**Comment by jpince** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jpince** [comment]
@petershin any thoughts on this? I was also unable to reproduce locally.

I noticed only 1.0.0 exists on Nexus, but I don't think that should affect a PR? https://repository-cdn.liferay.com/nexus/content/groups/public/com/liferay/com.liferay.portal.tools.sample.sql.builder/

**Comment by jpince** [comment]
cc/ @vicnate5

**Comment by drewbrokke** [comment]
@jpince am I safe to reopen?

**Comment by jpince** [comment]
@drewbrokke no, the same batch `modules-semantic-versioning-jdk8` failed in your test pull. The logs from that test have already been cleared so I can't see if it's the same error, but it's enough for me to prefer to keep this closed. Seeing the batch pass in another ci:test:relevant run would be the only other thing that would clear this up (besides Peter's ok).

**Comment by drewbrokke** [comment]
I'll send one to myself with a trivial change so we can get a baseline, no pun intended.

**Comment by drewbrokke** [comment]
@jpince test pull here: https://github.com/drewbrokke/liferay-portal/pull/708

**Comment by petershin** [comment]
@jpince - Sent a [pull](https://github.com/drewbrokke/liferay-portal/pull/709) to @drewbrokke which adds the missing artifact to the `.m2-tmp` directory

**Comment by jpince** [comment]
@petershin thank you!

**Pull request closed without merging**
