### PR TITLE
master-qa-25001

### PR DESCRIPTION
**Pull request by vicnate5**
https://issues.liferay.com/browse/LRQA-25001

This remove the Workflow test that is consistently failing on the PR tester due to bug https://issues.liferay.com/browse/LPS-65630

### CODE REVIEW

**Comment by brianchandotcom** [comment]
I merged this. .but @pyoo47 what's happening here?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0cec471d83...2c23220f79

**Comment by vicnate5** [comment]
cc @marcellustavares

**Comment by pyoo47** [comment]
ci:stop

**Comment by marcellustavares** [comment]
@vicnate5, I think this regression was caused by https://issues.liferay.com/browse/LPS-65319. Could you confirm that for me?

see https://github.com/brianchandotcom/liferay-portal/pull/39367

Thanks

**Comment by vicnate5** [comment]
@marcellustavares Reverting LPS-65319 doesn't fix the issue. This is caused by something else.

**Comment by marcellustavares** [comment]
Thanks @vicnate5!

**Pull request closed without merging**
