### PR TITLE
LPS-78772

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:test

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
@Ithildir here's the Smoke test failure, I doubt it has anything to do with your changes? `Element is not visible at "//span[contains(@data-search,'-Hello World') and contains(@class,'add-content-item')]"`, will retest the apio pull once this is merged

**Comment by Ithildir** [comment]
@jpince, yeah, I seriously doubt it's caused by this change!

**Comment by brianchandotcom** [comment]
Merged. Thank you.

**Pull request closed without merging**
