### PR TITLE
LPS-66139

### PR DESCRIPTION
**Pull request by Ithildir**
cc @michaelhashimoto

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@michaelhashimoto fyi this tests server startup too.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ddc1e1283b...9e6c64721b

**Comment by michaelhashimoto** [comment]
@pyoo47 - Here's the fix that we were talking about earlier today.

**Pull request closed without merging**
