### PR TITLE
LPS-71068 Remove unnecessary null checks

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @robertoDiaz

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
@sergiogonzalez I'm not sure if this is a real failure or not, but I don't see it in other pulls
```
     [exec] 21-Mar-2017 15:11:47.562 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log Initializing Spring root WebApplicationContext
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/jps_output
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/jstack_output
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:254: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:2694: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tck.xml:350: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tck.xml:271: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:9510: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:3277: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:3373: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:3696: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:3837: Unable to find startup message after 30 minutes.
     [echo] 2017-03-21 08:41:05
     [echo] Full thread dump Java HotSpot(TM) Server VM (25.51-b03 mixed mode):
     [echo] 
     [echo] "Attach Listener" #65 daemon prio=9 os_prio=0 tid=0x62c0d000 nid=0x5f81 waiting on condition [0x00000000]
     [echo]    java.lang.Thread.State: RUNNABLE
     [echo] 
     [echo] "Java2D Disposer" #62 daemon prio=10 os_prio=0 tid=0x610e8c00 nid=0x5a74 in Object.wait() [0x4f95c000]
     [echo]    java.lang.Thread.State: WAITING (on object monitor)
     [echo] 	at java.lang.Object.wait(Native Method)
     [echo] 	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
     [echo] 	- locked <0xa538db58> (a java.lang.ref.ReferenceQueue$Lock)
     [echo] 	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
     [echo] 	at sun.java2d.Disposer.run(Disposer.java:148)
     [echo] 	at java.lang.Thread.run(Thread.java:745)
     [echo] 
     [echo] "JMX OSGi Service State Event Dispatcher" #59 daemon prio=5 os_prio=0 tid=0x575fd000 nid=0x5a72 waiting on condition [0x4fafe000]
     [echo]    java.lang.Thread.State: WAITING (parking)
     [echo] 	at sun.misc.Unsafe.park(Native Method)
     [echo] 	- parking to wait for  <0x71e20c28> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
     [echo] 	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
     [echo] 	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
     [echo] 	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
     [echo] 	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
     [echo] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
     [echo] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [echo] 	at java.lang.Thread.run(Thread.java:745)
```
https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/93398/consoleFull

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by sergiogonzalez** [comment]
@jpince it seems that it was something unrelated to this pull thx!

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
