### PR TITLE
LPS-67151 Add Thai as language

### PR DESCRIPTION
**Pull request by wesleygong**

### CODE REVIEW

**Comment by ssmith353** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@ssmith353 @wesleygong you guys missed a bunch of keys?

See 6333f1ab45417bc80f906ec08be1ae7731c361c2

**Comment by brianchandotcom** [comment]
@ssmith353 @wesleygong you guys missed a bunch of keys?

See 6333f1ab45417bc80f906ec08be1ae7731c361c2

**Pull request closed without merging**
