### PR TITLE
LPS-152489: Wrong virtual instance is shown when data partitioning is…

### PR DESCRIPTION
**Pull request by petersimonyi**
Can you please review? https://issues.liferay.com/browse/LPS-152489 Thanks in advance!

### CODE REVIEW

**Comment by vicnate5** [comment]
@tinatian

**Comment by brianchandotcom** [comment]
@tinatian can we add a test for this too? thx.

**Comment by brianchandotcom** [comment]
@petersimonyi can you add a test for this and send it to @tinatian ? faster. We already have integration tests.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/455d78e28b...90337aa04b

**Pull request closed without merging**
