### PR TITLE
LPS-85791 Segmentation services (Segments version)

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d355973031...eb002fe880

**Comment by brianchandotcom** [comment]
@epgarcia I went with this pull instead of https://github.com/brianchandotcom/liferay-portal/pull/63568 because you prefer Segments over Meris. I think it's fine (because we have SegmentsEntry).

Should it be like "apps/dynamic-data-lists"

or

Should it be like "apps/dynamic-data-mapping"

Meaning, should this be "Segment" i.e. "Document Library" or "Segments" i.e. "Bookmarks" and "Blogs".

It's more art than science. I'm fine with either way, just wanted you to at least ponder :) Thx.

**Comment by epgarcia** [comment]
Hi @brianchandotcom, thanks for reviewing this so quickly, even though you've been traveling. I had the same question about the name (i.e. singular VS plural), and I liked "Segments" most. I would have chosen singular if the name had been "Segmentation" (as an uncountable concept, like "Document Library", "Commerce", "DD-Mapping"). But for countable I think plural is best.

Thanks for accepting the change. I liked Meris, but I put myself in the position of someone adding a dependency with these modules in the future. With this name, it's easier to identify what the modules are for.

**Comment by jpince** [comment]
@hhuijser can you please look into why SF didn't fail for this pull? https://github.com/brianchandotcom/liferay-portal/pull/63567/commits/c85be7b956cf2f9081f2bb1850f232745251a8a7#diff-e322c2e835f5c6f120f9085db61d9e4cR45
`     [java] 1: Incorrect order 'SegmentsEntry#finder': 'G_K' should come after 'G_A': ./modules/apps/segments/segments-service/service.xml (SourceCheck:XMLServiceFileCheck)`
@yichenroy can you please reply with the exact command we use in ci:test:sf for Hugo's reference? thanks!

**Comment by jpince** [comment]
@hhuijser nevermind, Eduardo thinks it failed because of Brian's SF https://github.com/brianchandotcom/liferay-portal/commit/1bb5a511f101d554c4888505d442320f8d94a140

**Comment by epgarcia** [comment]
@jpince This has happened to me dozens of times: I change fields sorting, but I forget finders. They have a particular sorting criteria (not necessarily alphabetical):

* first finders with logic names (e.g. findByNotAsset)
* then based on the number of columns (finders with less columns, first)
* for those with the same number of columns, the order is based on the order the columns of the entity are ordered

**Pull request closed without merging**
