### PR TITLE
LPS-80627 Make sure plugin listeners are called when navigating with SPA

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
@adolfopa @4lejandrito

We need to adapt our spark jobs in cerebro to use the new event names defined in https://github.com/brianchandotcom/liferay-portal/pull/58302/files#diff-1b7ec9d1b32543dec98cbea138cd6444.

`depthReached`
`blogViewed`
`blogClicked`

**Comment by 4lejandrito** [comment]
Hi @brunobasto,

Before you do the same for journal, please wait until https://github.com/brianchandotcom/liferay-portal/pull/58303 is merged.

Thanks!

**Comment by brunobasto** [comment]
Got it! Thanks

**Comment by brunobasto** [comment]
ci:test

**Comment by brunobasto** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6295c6acd0...71e49c006c

**Pull request closed without merging**
