### PR TITLE
LPS-73261

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jbalsas can we keep our format instead of using the default? Please resend. Thx.

**Comment by jbalsas** [comment]
Hey @brianchandotcom, I was looking into it, and I couldn't find a way to tell `npm` to stop formatting those files. If we don't ignore it, it's going to be showing changes everytime we compile a module. In npm-world, we have:
- **package.json**: This is the main file. It can be manually changed, although the tool will auto-format it. It preserves order and indentation, but it will add an extra endline that fights source formatter. @hhuijser, could we simply disable that rule for this file?
- **package-lock.json**: This is an internal, auto-generated file. No one should even look into it or change it manually. 
- **npm-shrinkwrap.json**: This is an internal, auto-generated file. No one should even look into it or change it manually.

My proposal would be:
- **Ignore internal** files: `package-lock.json` and `npm-shrinkwrap.json`
- **Disable some rules** for `package.json`

Does it make sense?

**Comment by hhuijser** [comment]
@jbalsas 
You can add to sourcechecks-suppressions.xml to exclude files.

**Comment by jbalsas** [comment]
Resent to https://github.com/hhuijser/liferay-portal/pull/2899 just disabling the whitespace rule in `package.json` files!

**Pull request closed without merging**
