### PR TITLE
Lps 89170

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@danielkocsis @shuyangzhou lots of functional tests broken.

@jpince fyi.

**Comment by jpince** [comment]
@brianchiu @kyle-miho this PR was closed due to excessive functional test failures. Can you retest once your fix is merged, or just reopen if it looks ok?

**Comment by kyle-miho** [comment]
ci:test

**Comment by brianchiu** [comment]
ci:test

**Comment by brianchiu** [comment]
cc @vicnate5 @anthony-chu @koor4356
I can't quite tell from the retest. There are some more core failures. Can you guys take a look? The WEM results are fine.

https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=477850720

**Comment by anthony-chu** [comment]
@shuyangzhou @danielkocsis

upgrades for sybase are failing to drop the old LayoutSet index, based on changes made [here](https://github.com/brianchandotcom/liferay-portal/pull/68260/files#diff-a2ac248a4db541e083e0c158dda33562). a warning this thrown, but there is no functional impact from this warning.

```
2019-02-20 00:22:38.442 WARN  [main][BaseDB:532] Cannot drop the index 'LayoutSet.IX_48550691', because it doesn't exist in the system catalogs.: drop index LayoutSet.IX_48550691;
```

**Pull request closed without merging**
