### PR TITLE
LPS-191513 Filter objectDefinition by objectFolderERC

### PR DESCRIPTION
**Pull request by murilostodolni**
The errors in original [PR](https://github.com/liferay-objects/liferay-portal/pull/2450) are not related. Thank you

### CODE REVIEW

**Comment by murilostodolni** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/40e6fb6657...a1c0dc6cfe

**Comment by brianchandotcom** [comment]
@murilostodolni please send a follow up PR and follow the pattern in

modules/apps/redirect/redirect-service/src/main/resources/com/liferay/redirect/internal/search/spi/settings/dependencies/additional-type-mappings.json

modules/apps/redirect/redirect-service/src/main/java/com/liferay/redirect/internal/search/spi/settings/RedirectIndexSettingsContributor.java

So move modules/apps/object/object-service/src/main/resources/META-INF/mappings/liferay-type-mappings.json

See also a1c0dc6c

Thx

**Comment by murilostodolni** [comment]
Got it. I'm on it.

**Pull request closed without merging**
