### PR TITLE
LPS-115709

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Only unrelated failure, see https://github.com/hhuijser/liferay-portal/pull/5132

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/736cdfd90e...4517872a4d

**Comment by brianchandotcom** [comment]
@hhuijser yeah.. we need to start cleaning up the Commerce SF.

Way too much ignored. I mean, we're even ignoring CopyrightCheck!

@marco-leo @dsitu ...

**Comment by marco-leo** [comment]
Hey Brian

Most of it is alrrady obsolete and cleaned

Need to clean that file

Marco Leo

**Pull request closed without merging**
