### PR TITLE
LPS-58688 Add missing dependencies

### PR DESCRIPTION
**Pull request by carloslancha**
cc @juliocamarero

### CODE REVIEW

**Comment by juliocamarero** [comment]
:+1:

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2c7acc8400...39001e5449

**Pull request closed without merging**
