### PR TITLE
LPS-81869 Rename app.bnd following Jorge's suggestion

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@nhpatt not merging... I don't see how Headless Apio conflicts with Apio Architect?

**Comment by nhpatt** [comment]
It's because this PR: https://github.com/brianchandotcom/liferay-portal/pull/59803/commits/9baaede732198c43bd0d12f3d4f6347f2010db50

**Comment by nhpatt** [comment]
Sorry for not explaining correctly, the name was changed to prevent a clash with apio architect before and Jorge prefers another name instead of Apio

**Comment by nhpatt** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@jorgeferrer @nhpatt 

Isn't DXP our commercial offering? We don't call it DXP for CE..

This is the CE branch?

Please resend.

**Comment by JorgeFerrer** [comment]
Good point. Since we are at it, "Headless" is not the best term for this package, since what is headless is the portal/platform, this App just adds Hypermedia REST APIs to make it a better headless. So the name should probably reflect just that role.

**Pull request closed without merging**
