### PR TITLE
LPS-64277 ant format-source

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
@adolfopa You forgot to run "ant setup-sdk" first, this will give you the latest SF. There are some upgrade connection usages that are not allowed now. Please resend.

**Comment by brianchandotcom** [comment]
@adolfopa also, make sure to pull from latest master before running "ant setup-sdk"

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/39165

Thanks!

**Pull request closed without merging**
