### PR TITLE
Lps 73238

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9e90004be5...c622ec62b1

**Comment by brianchandotcom** [comment]
@shuyangzhou  please backport. Thx.

**Comment by shuyangzhou** [comment]
@tomwang2011 backport please.

**Pull request closed without merging**
