### PR TITLE
LPS-75876

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-75876.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b5dabd958e...43f577585c

**Comment by brianchandotcom** [comment]
@Ithildir can you review the changes to build.gradle in upstream? Thx.

**Comment by Ithildir** [comment]
LGTM! 👍

**Pull request closed without merging**
