### PR TITLE
LPS-105723 SF

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
🤔 

The `test:relevant` suite is not looking so good right now, but I doubt it's related to this PR.

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
**Reviewed. Test failures are unrelated.** :heavy_check_mark: 

**Comparison Details:**
- flaky tests:
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=7&testrayRunIdB=945200990&testrayRunIdA=946311487&statusB=2

- fluke:
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=4&testrayRunIdB=945200990&testrayRunIdA=946311487&statusB=2

- A large number of test failures are pre-existing in the same base branch test run.
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=945200990&testrayRunIdA=946311487&statusB=3

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/41d2c388a0...1d469c48bd

**Pull request closed without merging**
