### PR TITLE
Lps 61006

### PR DESCRIPTION
**Pull request by shuyangzhou**
@rotty3000

This is the way how we want to continue the performance optimization when it crosses to external dependencies.

In this case you can see the actual changes at https://github.com/rotty3000/phidias/pull/5
As you can see it is very simple and obvious, and most likely you can merge it in and publish a new version very quickly, so doing this patching solution might look a bit overkilled. But this is just a demo start, we on purposely picked a simple change, there are more (and possibly more complex ones) on the way.

The goal is to unblock on our side when we do the optimization, as you know, unlike other type of issues, for performance issues in most cases, not until you kill the top bottleneck, you don't even know who is the second one.

So we need a very fast turn around, we need a way to adopt the change right away.

We will always send you pulls to the original repo, and generate the patch files from exactly the changes in the pulls. So when you merge in the changes in the original repo, you can just go back to master to drop off the matched patch file. But please keep the thrid-party patch module and the reference to the patched version. In the end of the optimization cycle, if you have merged in all the patches, we will drop off the patch module, and revert all usages to original references,

Hope this makes sense to you and you are ok with it.

Thanks

Shuyang

CC @mhan810

### CODE REVIEW

**Comment by rotty3000** [comment]
Thx @shuyangzhou, phidias 0.3.7 is released in maven central.

**Comment by rotty3000** [comment]
btw, who's going to make sure we drop the patched versions when they are
obsolete?

On Mon, Dec 7, 2015 at 5:58 PM, Raymond Auge <raymond.auge@liferay.com>
wrote:

> Thx @shuyangzhou, phidias 0.3.7 is released in maven central.
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by shuyangzhou** [comment]
Thanks @rotty3000 ! Once @brianchandotcom merges in this pull, I will remove the patch file and bump up the version number.

It can be either you or me, it is up to you. As long as I get a notice from you for the new release, if you don't update the reference, I will.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9db4b80c12...11c1d31196

**Pull request closed without merging**
