### PR TITLE
LPS-60604 Auto

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
@evannagayama, Could you take a look into the poshi errors?

@jbalsas, Could you check the new card taglibs?

@natecavanaugh, Could you check the css that I've added to the new taglibs?

Thanks!!!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8c87a87ab3...b3f5be73d0

**Comment by brianchandotcom** [comment]
@ealonso thx bro

**Comment by brianchandotcom** [comment]
@ealonso I didn't see any poshi errors.

**Pull request closed without merging**
