### PR TITLE
LPS-95881 - Update Clay version to v2.15.1

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by jpince** [comment]
@john-co

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@carloslancha what about master-private?

@hhuijser this is almost the same as my OSGi build.gradle version enforcement, except it's at the package.json level.

Can you talk to @carloslancha and @jbalsas so we enforce this via SF going forward?

**Comment by jbalsas** [comment]
Hey @brianchandotcom, this is enforced already via SF. If anyone attempts to set a different version than the official one (for metal-* and clay-* packages), SF will fail.

**Pull request closed without merging**
