### PR TITLE
LPS-60053 UncaughtExceptionHandler is called before thread death, do …

### PR DESCRIPTION
**Pull request by shuyangzhou**
…a post thread join to avoid asserting in the window time before the thread death.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@brianchiu unstable poshi test?

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9e0f141a40...8a39c4047b

**Comment by michaelhashimoto** [comment]
@brianchandotcom - that particular slave has a bad firefox.

See these 2 functional tests failed on this slave: <a href="https://test-1-9.liferay.com/computer/cloud-10-0-19-4/">cloud-10-0-19-4</a>
<ol>
<li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=PGBookmarks%23DeleteFolder,label_exp=!master/5728//consoleFull">PGBookmarks#DeleteFolder</a></li>
<li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=CPSitememberships%23RemoveMember,label_exp=!master/5790//consoleFull">CPSitememberships#RemoveMember</a></li>
</ol>

For the same reason:
<pre>org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/usr/bin/firefox) on port 7055; process output follows: 
Error: cannot open display: localhost:0

Build info: version: '2.47.1', revision: 'unknown', time: '2015-07-30 11:02:44'
System info: host: 'cloud-10-0-19-4.lax.liferay.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'i386', os.version: '2.6.32-042stab108.6', java.version: '1.7.0_79'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:134)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:276)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:116)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:221)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:216)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:212)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:129)
	at com.liferay.poshi.runner.selenium.FirefoxWebDriverImpl.<init>(FirefoxWebDriverImpl.java:33)
	at com.liferay.poshi.runner.selenium.SeleniumUtil._startSelenium(SeleniumUtil.java:76)
	at com.liferay.poshi.runner.selenium.SeleniumUtil.startSelenium(SeleniumUtil.java:29)</pre>

**Pull request closed without merging**
