### PR TITLE
LPS-76585 Rename dropdownItem vars to follow same pattern of navigationItems

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test

**Comment by michaelhashimoto** [comment]
ci:test

**Comment by michaelhashimoto** [comment]
ci:test

**Comment by michaelhashimoto** [comment]
ci:test

**Comment by michaelhashimoto** [comment]
ci:test

**Comment by michaelhashimoto** [comment]
ci:help

**Comment by michaelhashimoto** [comment]
ci:help

**Comment by brianchandotcom** [comment]
@carloslancha @jbalsas 

1.) Can you rename "managementtoolbars.jsp" since that doesn't follow our JSP naming convention.

2.) also, doesn't compile:

```
     [exec] Caused by: org.apache.jasper.JasperException: file:/home/brian/dev/projects/github/liferay-portal/modules/apps/foundation/frontend-taglib/frontend-taglib-clay-sample-web/build/unzipped-jar/META-INF/resources/partials/cards.jsp(63,2) PWC6131: Attribute stickerLabel invalid for tag image-card according to TLD
     [exec] 	at org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:81)
     [exec] 	at org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:376)
     [exec] 	at org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:204)
     [exec] 	at org.apache.jasper.compiler.Validator$ValidateVisitor.checkXmlAttributes(Validator.java:1223)
     [exec] 	at org.apache.jasper.compiler.Validator$ValidateVisitor.visit(Validator.java:859)
     [exec] 	at org.apache.jasper.compiler.Node$CustomTag.accept(Node.java:1502)
     [exec] 	at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2297)
     [exec] 	at org.apache.jasper.compiler.Node$Visitor.visitBody(Node.java:2347)
     [exec] 	at org.apache.jasper.compiler.Node$Visitor.visit(Node.java:2353)
     [exec] 	at org.apache.jasper.compiler.Node$Root.accept(Node.java:499)
     [exec] 	at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2297)
     [exec] 	at org.apache.jasper.compiler.Validator.validate(Validator.java:1890)
     [exec] 	at org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:223)
     [exec] 	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:451)
     [exec] 	at org.apache.jasper.JspC.processFile(JspC.java:1178)
     [exec] 	at org.apache.jasper.JspC.execute(JspC.java:1345)
     [exec] 	... 6 more
     [exec] :apps:foundation:frontend-taglib:frontend-taglib-chart:replaceSoyTranslation
     [exec] :apps:forms-and-workflow:dynamic-data-mapping:dynamic-data-mapping-data-provider-web:compileJSP
     [exec] :apps:foundation:frontend-taglib:frontend-taglib-clay-sample-web:generateJSPJava FAILED
     [exec] :apps:foundation:login:login-authentication-openid-web:jar UP-TO-DATE
     [exec] Note: /home/brian/dev/projects/github/liferay-portal/modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-data-provider-web/build/jspc/org/apache/jsp/view_jsp.java uses unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] [Export com.liferay.portal.security.sso.openid.connect,  has 1,  private references [com.nimbusds.openid.connect.sdk.rp], , Export com.nimbusds.jwt,  has 1,  private references [com.nimbusds.jose], , Export com.nimbusds.oauth2.sdk,  has 1,  private references [com.nimbusds.jose], , Export com.nimbusds.oauth2.sdk.assertions.jwt,  has 2,  private references [com.nimbusds.jose, com.nimbusds.jwt.proc], , Export com.nimbusds.oauth2.sdk.auth,  has 1,  private references [com.nimbusds.jose], , Export com.nimbusds.openid.c
```

Please resend on top of https://github.com/carloslancha/liferay-portal/pull/144

**Pull request closed without merging**
