### PR TITLE
LPS 181209

### PR DESCRIPTION
**Pull request by rotty3000**
- LPS-181209 Make WebIdToCompanyConfigurationPluginImpl more reliable
- LPS-181303 Update workspace to support instance settings client extension
- LPS-181738 Error logged from UnicodeProperties when deploying client extensions that contain array properties
- LPS-181327 Create a sample instance setting client extension

### CODE REVIEW

**Comment by rotty3000** [comment]
cc @gamerson @drewbrokke

**Comment by drewbrokke** [comment]
@rotty3000 did this run through the `gradle-plugins` suite already?

**Comment by rotty3000** [comment]
I'm checking CI here https://github.com/rotty3000/liferay-portal/pull/1500

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3854fa4053...f92b1e2940

**Pull request closed without merging**
