### PR TITLE
LPS-80927 Apply the language key transformation plugin to the appropriate *-uad modules

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-80927](https://issues.liferay.com/browse/LPS-80927).<br><br>Hey Brian, this applies the new language transformation to the appropriate UAD moduees.  It also removes language files from any modules that do not have displays in the UI.<br><br>/cc @pei-jung @Ithildir

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@drewbrokke do we need to add some .gitignores (will "ant all" create a bunch of files we ought not to check in?)

Thx

**Comment by drewbrokke** [comment]
@brianchandotcom to my knowledge the LangMerger plugin doesn't create any extra files in source, it just puts them in the jar.  I think that one issue on the other pull was a fluke.  In my testing I never had to re-delete the language files once the deletes were committed.

**Comment by Ithildir** [comment]
@brianchandotcom, @drewbrokke is right: the Gradle plugin writes in the `classes` directory, not in `src/main/resources`.

**Pull request closed without merging**
