### PR TITLE
LPS-171059 Update Partner Portal Site

### PR DESCRIPTION
**Pull request by nNilton**

### CODE REVIEW

**Comment by nNilton** [comment]
ci:reopen

**Comment by nNilton** [comment]
Unrelated Failures here https://github.com/pt-liferay-solutions/liferay-portal/pull/3052

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cbde3c598a...a667b9bf59

**Comment by brianchandotcom** [comment]
@nNilton we need to add an integration test for this. In our test, create a group with an extra one and make sure delete does its job.

@joseabelenda fyi

**Comment by brianchandotcom** [comment]
@jackelyneaquino see my comment above. We need an integration test. Thx.

**Pull request closed without merging**
