### PR TITLE
LPS-119653 avoid adding aggregation

### PR DESCRIPTION
**Pull request by javiergamarra**
Commerce needs it to regenerate and avoid waiting for a fixpack in a release and there is an issue with some flaky test in workflow.

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fae5c40edd...41d3b9303a

**Comment by brianchandotcom** [comment]
@nhpatt I regenerated to 7.2.x and 7.1.x

**Comment by nhpatt** [comment]
Thanks!

**Pull request closed without merging**
