### PR TITLE
Serializing documents

### PR DESCRIPTION
**Pull request by MumenTayyem**

### CODE REVIEW

**Comment by MumenTayyem** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ffc74596ec...f88705a40b

**Comment by brianchandotcom** [comment]
@MumenTayyem see 25902ad7acb48f1a5efee82f12bba3e547dd60b0 89f3a1b54c941468d73bf022b4914d37ad2041ab and f88705a40be76bf1616ffdb81f8bd1162eefce42

**Comment by MumenTayyem** [comment]
Thanks @brianchandotcom for the comments! will make sure to do the same for my next PRs.

**Pull request closed without merging**
