### PR TITLE
LPS-99238 Do not display the 'permission' button if the user does not have the appropriate permissions

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5eb22d574e...455eac9d8f

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by rafaprax** [comment]
Hey @brianchandotcom, Can I close this?

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@rafaprax my bad, forgot to hit close.

**Pull request closed without merging**
