### PR TITLE
LPS-76235 SF - Rename

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by brianchandotcom** [comment]
We have Web Experience, Journal, Web Content Management, do we have to add the word CMS now too?

Can we reuse another word?

@jorgeferrer fyi

Please resend @pavel-savinov @ealonso thx

**Comment by ealonso** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/55643

**Comment by brianchandotcom** [comment]
Can we rename: com.liferay.site.rest.api

to com.liferay.site.apio.api ?

com.liferay.site.rest.impl to

com.liferay.site.apio.impl

Thx!

**Comment by JorgeFerrer** [comment]
Hey Brian,

"Headless CMS" is the most common industry name. But in any case, I think we can call our own package in any way we want. 

What do you think of "headless-web-experience"?

**Comment by JorgeFerrer** [comment]
Nevermind, Eudaldo has just told me that he went with web-experience-apio. I'm find with that as an internal name as long as we don't use that name in the Marketplace.

**Pull request closed without merging**
