### PR TITLE
LPS-79000 Minor SF

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
@hhuijser this code throws an SF error however it seems weird: says we shouldn't import class from a different module, but there is not import from an other module. Checked other tag classes as well, they are using the ServletContextUtil class in the same way. I guess this is an SF error.

@brianchandotcom

**Comment by matethurzo** [comment]
ci:reopen

**Comment by jpince** [comment]
@petershin see Mate's comment above https://github.com/brianchandotcom/liferay-portal/pull/58690#issuecomment-390201884

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f2861002d3...81873381c1

**Comment by jpince** [comment]
@hhuijser I didn't realize Peter was on PTO yesterday, can you please look into this?

**Comment by hhuijser** [comment]
@jpince, I am on it

**Pull request closed without merging**
