### PR TITLE
LPS-85440 Semantic versioning

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by jpince** [comment]
@cgoncas can you please verify that these failures are unrelated to this pull?
```
StructuredContentApioTest.testStructuredContentsMatchesSelfLink
StructuredContentApioTest.testStructuredContentsExistsInContentSpaceEndpoint
StructuredContentApioTest.testContentSpaceLinkExistsInRootEndpoint
com.jayway.jsonpath.PathNotFoundException: Missing property in path $['_links']['content-space']
```

**Comment by jpince** [comment]
@cgoncas it's actually in upstream, probably introduced in https://github.com/brianchandotcom/liferay-portal/pull/63667. Can you please take a look?

**Comment by cgoncas** [comment]
Hey @jpince, I think they are not related, I have detected it just momments ago in master, and are caused because recent changes in content-space-apio-impl.

It is possible to execute structure-content test after changes in content-space?.

**Comment by cgoncas** [comment]
I am creating a new pull to fix the content-space issue in master

**Comment by cgoncas** [comment]
The pull that should fix this is: https://github.com/brianchandotcom/liferay-portal/pull/63725

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
