### PR TITLE
LPS-63044 Remove the link to add threads and categories entries from MB toolbar

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @sharonchoi same as https://github.com/brianchandotcom/liferay-portal/pull/35783 but for Message Boards

**Comment by brianchandotcom** [comment]
@sergiogonzalez please resend, poshi.

**Comment by sharonchoi** [comment]
@sergiogonzalez Will fix poshi tests here: https://issues.liferay.com/browse/LRQA-22036 Please expect a 1-3 day turnaround.

**Comment by sharonchoi** [comment]
Resend here: 
https://github.com/brianchandotcom/liferay-portal/pull/35832

**Pull request closed without merging**
