### PR TITLE
Lps 85135

### PR DESCRIPTION
**Pull request by shuyangzhou**
@vicnate5 high risk changes, this is changing minifier logic for aggregared js/css. Make sure we go through some frontend testing to confirm UI still looks good, thanks!

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@jpince can you check on those functional test failures? Let me know if they are real, if so, I will need manual reproduce steps, thanks!

**Comment by jpince** [comment]
@vicnate5 these are the tests already failing in upstream, can you please investigate any others?
CPDocumentsandmedia#MoveToRecycleBinDocument
CPCategories#DeleteVocabulary
CPDynamicdatalists#ImportLAR
CPSiteteams#AddSiteTeamRemoveUser
DynamicdatalistsUsecase#ViewRequiredNestedDocumentsAndMediaField
ExportImport#ExportImportPrivatePage
ExportImport#ExportImportValidation

**Comment by vicnate5** [comment]
Did some manual testing, will investigate the failing functional tests.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/428ac2d9ba...b1e738572e

**Comment by vicnate5** [comment]
This causes https://issues.liferay.com/browse/LPS-85173

CC @jpince @kmaria

**Comment by kmaria** [comment]
thank you @vicnate5

**Pull request closed without merging**
