### PR TITLE
Lps 75096

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by pyoo47** [comment]
ci:retest

**Comment by 4lejandrito** [comment]
Hi @shuyangzhou,

As I said in https://github.com/shuyangzhou/liferay-portal/pull/4970#issuecomment-334478109, I am afraid we can't go for this fix because the source formatter fails expecting the lazy attribute to be the first one (alphabetical order). 

I have modified service builder to ignore any attributes preceding `name`. Please see https://github.com/shuyangzhou/liferay-portal/pull/4996.

This one should be closed.

**Pull request closed without merging**
