### PR TITLE
Lps 70046

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@arboliveira fyi, lots of search errors this morning

@shuyangzhou fyi

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ae24e464e1...14e062a25f

**Comment by brianchandotcom** [comment]
@Preston-Crary see 14e062a25f630e4eab89ed3a6d887bb62d75764a

thx

**Pull request closed without merging**
