### PR TITLE
LPS-59291 SF

### PR DESCRIPTION
**Pull request by rafaprax**
cc @marcellustavares

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@rafaprax we've made lots of changes to UpgradeJournal. Can you resend? Rebase issues. Thx.

**Comment by rafaprax** [comment]
@brianchandotcom I'll do it now. Thx

**Pull request closed without merging**
