### PR TITLE
ISSD-1495 [Learn] Include Slack API call into the cron job java code.

### PR DESCRIPTION
**Pull request by abfranca**

### CODE REVIEW

**Comment by nNilton** [comment]
ci:close

**Comment by abfranca** [comment]
resent: https://github.com/is-solutions-delivery/liferay-portal/pull/5112

**Comment by nNilton** [comment]
ci:reopen

**Comment by nNilton** [comment]
ci:close

**Comment by nNilton** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/adb4d00e62...97f605c7f1

**Comment by brianchandotcom** [comment]
@abfranca @nNilton just 97f605c7f189079adacc935e5b7f75287313b2a1

**Pull request closed without merging**
