### PR TITLE
LRIT-20631 Groups use a different URL pattern than repositories

### PR DESCRIPTION
**Pull request by CAustin582**

### CODE REVIEW

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
Just started reviewing :)

**Comment by jpince** [comment]
@brianchandotcom @CAustin582 pushed to Brian Chan's origin: https://github.com/brianchandotcom/liferay-portal/commit/5ed8fd8a01f081c4805202579bf01b38f57b72ed

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f13cd6abdb...f13cd6abdb

**Pull request closed without merging**
