### PR TITLE
LPS-70761 Logo does not display on My Dashboard when a site template is used

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-70761](https://issues.liferay.com/browse/LPS-70761).<br><br>I included an auto-sf commit that is unrelated, mostly so we won't get any false SF CI failures.<br><br>/cc @pei-jung @ealonso @jorgeferrer

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@drewbrokke I backported this for you since it's a regression. @pei-jung

**Comment by drewbrokke** [comment]
Thanks, @brianchandotcom 👍

**Pull request closed without merging**
