### PR TITLE
LPS-62060 SF

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/33a8bc4194...898711f74a

**Comment by brianchandotcom** [comment]
@epgarcia see 898711f74aeb1fe16116b43a4db3dbae975cb242

Thx

**Comment by brianchandotcom** [comment]
@pavel-savinov after my changes.. this pull actually did nothing? Can you talk to @epgarcia 

I still find it weird cause I don't think this pull did anything.

**Comment by epgarcia** [comment]
Sorry, my bad. See brianchandotcom/liferay-portal/pull/34444

Thanks!

**Pull request closed without merging**
