### PR TITLE
LPS-89996 Allow users to quickly toggle the scope of reviewable data among instance, personal site, and regular sites

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-89996](https://issues.liferay.com/browse/LPS-89996).<br><br>/cc @pei-jung @stsquared99 @alee8888 @ChrisKian

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by drewbrokke** [comment]
The SF failure will be fixed by https://github.com/brianchandotcom/liferay-portal/pull/68154

**Comment by brianchandotcom** [comment]
@drewbrokke can you resend after modifying this method:

```
	public UADApplicationSummaryDisplay getUADApplicationSummaryDisplay(
		String applicationKey, long userId,
		List<UADDisplay> applicationUADDisplays, long[] groupIds) {

		UADApplicationSummaryDisplay uadApplicationSummaryDisplay =
			new UADApplicationSummaryDisplay();

		int count = getReviewableUADEntitiesCount(
			applicationUADDisplays.stream(), userId, groupIds);
```

the ordering of the params don't seem to fit with the rest of this class.

**Comment by drewbrokke** [comment]
Resent as https://github.com/brianchandotcom/liferay-portal/pull/68259

**Pull request closed without merging**
