### PR TITLE
Lps 70094

### PR DESCRIPTION
**Pull request by shuyangzhou**
@brianchandotcom support needs this to go into ee-7.0.x, should be a clean cherry-pick, thanks!

### CODE REVIEW

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Hmm... It passed first, then failed again. I don't think these failures are related to the new `module-log4j.xml`

**Comment by ZoltanTakacs** [comment]
@lipusz asked me to look at this PR. It's ok from us to have it on ee-7.0.x as well, it's an additional commit for the backported ones. 👍

**Comment by pyoo47** [comment]
ci:retest
There’s a bad slave that’s being used as a distribution node in the last test. It’s causing the rsync copy of the portal bundle to freeze until the build times out.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
