### PR TITLE
[See description] LPS-53841 LPS-53822 Improve language keys with PM

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey Brian there are 3 different LPS tickets in the same pull because they are all very related.

Thanks

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @ipeychev

**Comment by sergiogonzalez** [comment]
cc/ @robertoDiaz

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f64f0b6abc...b17eda25be

**Comment by brianchandotcom** [comment]
@sergiogonzalez minor changes in upstream. Thx.

**Pull request closed without merging**
