### PR TITLE
LPS-57580 - update MonitoringBottomDynamicInclude registry key

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c2a5156a26...0b6e524e7e

**Comment by kenjiheigel** [comment]
@ZoltanTakacs, can this be backported to the 7.0.x branch? This fixes an issue with all Look and Feel modals for every portlet ([LPS-57580](https://issues.liferay.com/browse/LPS-57580)). Thank you!

**Comment by ZoltanTakacs** [comment]
Hi @kenjiheigel,

Sure, we will do a re-sync with master on this Friday so it will be included in Milestone 7. Thanks for notifying me.

**Comment by kenjiheigel** [comment]
Thank you!

**Pull request closed without merging**
