### PR TITLE
LPS-60284

### PR DESCRIPTION
**Pull request by natecavanaugh**

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
@brianchandotcom - It looks like this particular ABORTED build happened because it timed out when trying to build the portal.

<pre>     [exec] :portal:portal-settings:autoUpdateXml SKIPPED
     [exec] :portal:portal-settings:deploy
     [exec] :portal:portal-template-soy:buildCSS UP-TO-DATE
     [exec] :portal:portal-template-soy:compileJava
     [exec] [Export org.quartz,  has 3,  private references [org.quartz.impl.matchers, org.quartz.spi, org.quartz.utils], , Export org.quartz.impl.triggers,  has 1,  private references [org.quartz.spi], ]
     [exec] :portal:portal-soap-extender:autoUpdateXml SKIPPED
     [exec] :portal:portal-soap-extender:deploy
     [exec] :portal:portal-template-velocity:buildCSS UP-TO-DATE
     [exec] :portal:portal-template-velocity:compileJava
     [exec] :portal:portal-scheduler-quartz:autoUpdateXml SKIPPED
     [exec] :portal:portal-scheduler-quartz:deploy
     [exec] :portal:portal-template-xsl:buildCSS UP-TO-DATE
     [exec] :portal:portal-template-xsl:compileJava
     [exec] :portal:portal-scripting-groovy:autoUpdateXml SKIPPED
     [exec] :portal:portal-scripting-groovy:deploy
     [exec] :portal:portal-upgrade:deploy
     [exec] :portal:portal-verify-extender:buildCSS UP-TO-DATE
Build timed out (after 120 minutes). Marking the build as aborted.
Build was aborted
Recording test results</pre>

For a full printout of this time out see this link.
https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=CPCategories%23EditSubcategory,label_exp=!master/13463//console

**Comment by brianchandotcom** [comment]
@Ithildir building on CI has been very slow lately, lots of hung builds.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4e054a94db...3467f5e69e

**Comment by michaelhashimoto** [comment]
We'll try to eventually post the ABORTED message instead of just a general message.
https://issues.liferay.com/browse/LRQA-19302

**Comment by Ithildir** [comment]
And I'm trying some code to show the Gradle thread dump if the build is aborted: https://github.com/Ithildir/liferay-portal/pull/124

**Pull request closed without merging**
