### PR TITLE
LPS-81011 rename web page elements to structured contents

### PR DESCRIPTION
**Pull request by javiergamarra**
/cc @eperezg

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@nhpatt there is a rebase conflict with what's in upstream already. Can you resend? Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bb3a56d0d8...0f812ea4ca

**Comment by brianchandotcom** [comment]
@nhpatt actually, my Git was able to resolve them... so I'm merging this.

**Comment by nhpatt** [comment]
Thanks :)

**Pull request closed without merging**
