### PR TITLE
LPS-91125 Fix sql script path

### PR DESCRIPTION
**Pull request by darquesdev**
CC: @epgarcia @ealonso @andresfulla

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:msb

**Comment by jpince** [comment]
ci:test:msb @brianchiu @kyle-miho

**Comment by darquesdev** [comment]
ci:reopen

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
