### PR TITLE
LRQA-21240 Remove assertion due to new UI

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by sharonchoi** [comment]
@brianchandotcom investigating the poshi failures, they seem to be intermittent due to the test running faster than portal can load, and not caused by the pr, will need to make fixes to the tests to make it more stable, just fyi.

**Comment by brianchandotcom** [comment]
@sharonchoi please pull this and resend to me. Thx.

**Comment by sharonchoi** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/34709

**Pull request closed without merging**
