### PR TITLE
LPS-67296 Exclude from SF

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:reopen

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
Hi @brianchandotcom, any update on this pull?

Thanks!

**Comment by mdelapenya** [comment]
Is there any thing I can do for it? Thanks

**Comment by mdelapenya** [comment]
Hi @brianchandotcom, what can I do for this pull to be merged?

**Comment by mdelapenya** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Hey @mdelapenya I started reviewing this today, almost done. Should have it tomorrow. Sorry!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9cf3f5bee5...9cc83ddc75

**Comment by brianchandotcom** [comment]
@mdelapenya I heavily refactored the code to reduce 1.) duplication in tests and 2.) weird usage of static vars and methods.

I did my best to maintain the spirit of what you were achieving.

Please send me a follow up pull for the rest of the dbs!

**Pull request closed without merging**
