### PR TITLE
LPS-103454 backURL is no needed

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Please fix stable error.

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by brookedalton** [comment]
ci:reopen

**Comment by brookedalton** [comment]
There is a test fix needed for a flakey ellipsis icon that caused the display page poshi failure https://issues.liferay.com/browse/LRQA-54097 
cc://@manoelcyreno

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/64e23329c5...ead893979d

**Comment by brianchandotcom** [comment]
@ealonso InfoEditURLProviderUtil should not be a static class like this that is also a @Component.. expensive wiring

Please just pass the reference you need.

**Pull request closed without merging**
