### PR TITLE
LPS-66281

### PR DESCRIPTION
**Pull request by Ithildir**
Hi,
Please let this pull finish! If everything is okay, can you please publish these modules?
- `css-builder`
- `gradle-plugins-css-builder`
- `gradle-plugins`

Thank you!

### CODE REVIEW

**Comment by jpince** [comment]
@brianchandotcom upgrades tests have a liferay error that we are looking into, looks good from a poshi perspective.

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
@brianchandotcom, there's a conflict in the fake Gradle cache for `gradle-plugins`, please tell me if you want me to fix it and resend the pull.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0504980746...d87e610ebf

**Pull request closed without merging**
