### PR TITLE
LPS-98906 auto sf

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by jeyvison** [comment]
Hey, @jorgediaz-lr . We're getting a unique failure in the PR. Can you please check it? Thanks.

**Comment by jorgediaz-lr** [comment]
I will have a look to it, @jeyvison 

Thank you

**Comment by jorgediaz-lr** [comment]
ci:reopen

**Comment by jorgediaz-lr** [comment]
Hi @jeyvison 

I have tested it and the unique failure is unrelated to my changes, so I have reopened the PR

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bb29dc8a1e...c7c3a9066c

**Pull request closed without merging**
