### PR TITLE
LPS-76486 SF

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by jpince** [comment]
ci:close

**Comment by jpince** [comment]
@ealonso @jkappler @pavel-savinov the test failure for `FragmentEntryProcessorEditableTest.testFragmentEntryProcessorEditable` looks consistent and I don't see it anywhere else, can you please look into it?

SF:
```
     [java] 7: Line starts with '0' tabs, but '2' tabs are expected: ./modules/apps/web-experience/fragment/fragment-api/src/main/java/com/liferay/fragment/util/FragmentEntryRenderUtil.java 76 (CheckStyle:IndentationCheck)
     [java] 8: Line starts with '0' tabs, but '3' tabs are expected: ./modules/apps/web-experience/fragment/fragment-api/src/main/java/com/liferay/fragment/util/FragmentEntryRenderUtil.java 77 (CheckStyle:IndentationCheck)
     [java] 9: Line starts with '0' tabs, but '3' tabs are expected: ./modules/apps/web-experience/fragment/fragment-api/src/main/java/com/liferay/fragment/util/FragmentEntryRenderUtil.java 78 (CheckStyle:IndentationCheck)
     [java] 10: Line starts with '0' tabs, but '3' tabs are expected: ./modules/apps/web-experience/fragment/fragment-api/src/main/java/com/liferay/fragment/util/FragmentEntryRenderUtil.java 79 (CheckStyle:IndentationCheck)
     [java] 11: Line starts with '0' tabs, but '2' tabs are expected: ./modules/apps/web-experience/fragment/fragment-api/src/main/java/com/liferay/fragment/util/FragmentEntryRenderUtil.java 80 (CheckStyle:IndentationCheck)
```

cc/ @anthony-chu

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
