### PR TITLE
LPS-91641 Add assertions for default display page

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LPS-91641

cc @ealonso

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:test:wem-msb

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchiu** [comment]
@ealonso 
Are those semantic versioning failures related to this? I feel like not because the original pull (https://github.com/brianchiu/liferay-portal/pull/1805) was fine.

**Comment by brianchiu** [comment]
@ealonso nvm.

@brianchandotcom 
All pulls are failing with these errors:
```
     [exec] org.osgi.framework.BundleException: Could not resolve module: com.liferay.portal.vulcan.impl [262]
     [exec]   Unresolved requirement: Import-Package: com.liferay.portal.vulcan.identifier
     [exec] 
     [exec] 	at org.eclipse.osgi.container.Module.start(Module.java:444)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:447)
     [exec] 	at com.liferay.portal.bootstrap.ModuleFrameworkImpl._startDynamicBundles(ModuleFrameworkImpl.java:1730)
     [exec] 	at com.liferay.portal.bootstrap.ModuleFrameworkImpl.startFramework(ModuleFrameworkImpl.java:410)
     [exec] 	at com.liferay.portal.module.framework.ModuleFrameworkUtilAdapter.startFramework(ModuleFrameworkUtilAdapter.java:100)
     [exec] 	at com.liferay.portal.spring.context.PortalContextLoaderListener.contextInitialized(PortalContextLoaderListener.java:314)
     [exec] 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4643)
     [exec] 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5109)
     [exec] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
     [exec] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:742)
     [exec] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:718)
     [exec] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:703)
     [exec] 	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:630)
     [exec] 	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1840)
     [exec] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
     [exec] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [exec] 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
     [exec] 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
     [exec] 	at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:525)
     [exec] 	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:424)
     [exec] 	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1585)
     [exec] 	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:308)
     [exec] 	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
     [exec] 	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:424)
     [exec] 	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:367)
     [exec] 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:966)
     [exec] 	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:839)
     [exec] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
     [exec] 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1427)
     [exec] 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1417)
     [exec] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [exec] 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
     [exec] 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
     [exec] 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:943)
     [exec] 	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:258)
     [exec] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
     [exec] 	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422)
     [exec] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
     [exec] 	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:770)
     [exec] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
     [exec] 	at org.apache.catalina.startup.Catalina.start(Catalina.java:682)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:350)
     [exec] 	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:492)
```

```
     [exec] org.osgi.framework.BundleException: Could not resolve module: com.liferay.headless.foundation.api [592]
     [exec]   Unresolved requirement: Import-Package: com.liferay.portal.vulcan.identifier
     [exec] 
     [exec] 	at org.eclipse.osgi.container.Module.start(Module.java:444)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:447)
     [exec] 	at com.liferay.portal.bootstrap.ModuleFrameworkImpl._startDynamicBundles(ModuleFrameworkImpl.java:1730)
     [exec] 	at com.liferay.portal.bootstrap.ModuleFrameworkImpl.startFramework(ModuleFrameworkImpl.java:410)
     [exec] 	at com.liferay.portal.module.framework.ModuleFrameworkUtilAdapter.startFramework(ModuleFrameworkUtilAdapter.java:100)
     [exec] 	at com.liferay.portal.spring.context.PortalContextLoaderListener.contextInitialized(PortalContextLoaderListener.java:314)
     [exec] 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4643)
     [exec] 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5109)
     [exec] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
     [exec] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:742)
     [exec] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:718)
     [exec] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:703)
     [exec] 	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:630)
     [exec] 	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1840)
     [exec] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
     [exec] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [exec] 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
     [exec] 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
     [exec] 	at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:525)
     [exec] 	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:424)
     [exec] 	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1585)
     [exec] 	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:308)
     [exec] 	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
     [exec] 	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:424)
     [exec] 	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:367)
     [exec] 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:966)
     [exec] 	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:839)
     [exec] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
     [exec] 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1427)
     [exec] 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1417)
     [exec] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [exec] 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
     [exec] 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
     [exec] 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:943)
     [exec] 	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:258)
     [exec] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
     [exec] 	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422)
     [exec] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
     [exec] 	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:770)
     [exec] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
     [exec] 	at org.apache.catalina.startup.Catalina.start(Catalina.java:682)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:350)
     [exec] 	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:492)
     [exec] 20:28:25,602 ERROR [main][ModuleFrameworkImpl:1741] Unable to start bundle com.liferay.headless.foundation.impl
     [exec] org.osgi.framework.BundleException: Could not resolve module: com.liferay.headless.foundation.impl [593]
     [exec]   Unresolved requirement: Import-Package: com.liferay.headless.foundation.dto.v1_0; version="[1.0.0,2.0.0)"
     [exec]     -> Export-Package: com.liferay.headless.foundation.dto.v1_0; bundle-symbolic-name="com.liferay.headless.foundation.api"; bundle-version="1.0.0"; version="1.0.0"; uses:="com.fasterxml.jackson.annotation,com.liferay.petra.function,graphql.annotations.annotationTypes,io.swagger.v3.oas.annotations.media,javax.validation.constraints,javax.xml.bind.annotation"
     [exec]        com.liferay.headless.foundation.api [592]
     [exec]          Unresolved requirement: Import-Package: com.liferay.portal.vulcan.identifier
     [exec]   Unresolved requirement: Import-Package: com.liferay.headless.foundation.resource.v1_0; version="[1.0.0,2.0.0)"
     [exec]     -> Export-Package: com.liferay.headless.foundation.resource.v1_0; bundle-symbolic-name="com.liferay.headless.foundation.api"; bundle-version="1.0.0"; version="1.0.0"; uses:="com.liferay.headless.foundation.dto.v1_0,com.liferay.portal.kernel.model,com.liferay.portal.kernel.search,com.liferay.portal.kernel.search.filter,com.liferay.portal.vulcan.identifier,com.liferay.portal.vulcan.pagination"
     [exec] 
     [exec] 	at org.eclipse.osgi.container.Module.start(Module.java:444)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:447)
     [exec] 	at com.liferay.portal.bootstrap.ModuleFrameworkImpl._startDynamicBundles(ModuleFrameworkImpl.java:1730)
     [exec] 	at com.liferay.portal.bootstrap.ModuleFrameworkImpl.startFramework(ModuleFrameworkImpl.java:410)
     [exec] 	at com.liferay.portal.module.framework.ModuleFrameworkUtilAdapter.startFramework(ModuleFrameworkUtilAdapter.java:100)
     [exec] 	at com.liferay.portal.spring.context.PortalContextLoaderListener.contextInitialized(PortalContextLoaderListener.java:314)
     [exec] 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4643)
     [exec] 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5109)
     [exec] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
     [exec] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:742)
     [exec] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:718)
     [exec] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:703)
     [exec] 	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:630)
     [exec] 	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1840)
     [exec] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
     [exec] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [exec] 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
     [exec] 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
     [exec] 	at org.apache.catalina.startup.HostConfig.deployDescriptors(HostConfig.java:525)
     [exec] 	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:424)
     [exec] 	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1585)
     [exec] 	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:308)
     [exec] 	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
     [exec] 	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:424)
     [exec] 	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:367)
     [exec] 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:966)
     [exec] 	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:839)
     [exec] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
     [exec] 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1427)
     [exec] 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1417)
     [exec] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [exec] 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
     [exec] 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
     [exec] 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:943)
     [exec] 	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:258)
     [exec] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
     [exec] 	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422)
     [exec] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
     [exec] 	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:770)
     [exec] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
     [exec] 	at org.apache.catalina.startup.Catalina.start(Catalina.java:682)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:350)
     [exec] 	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:492)
```

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@brianchiu I fixed the Vulcan export and baseline issues.

**Pull request closed without merging**
