### PR TITLE
LPS-95863 Format module's API definition

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jbalsas a lot of broken tests? Please resend.

**Comment by jbalsas** [comment]
That's weird... @john-co, can you analyze? I'll take a look on my own and resend.

Thanks for catching this, @brianchandotcom!

**Comment by jbalsas** [comment]
There were actually just 2 unique failures... going to try testing again

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Yeah, I think the failures are likely going to get fixed once https://github.com/brianchandotcom/liferay-portal/pull/77383 is upstream, because it will likely fix the calendar errors, so I'll retest again then and resend

**Comment by jbalsas** [comment]
ci:test:relevant

**Pull request closed without merging**
