### PR TITLE
Lps 74897

### PR DESCRIPTION
**Pull request by shuyangzhou**
Sorry, I had some weird rebase problem which cancels off the SF change to build.gradle. I had them all squashed into once commit for build.gradle, it should be fine this time.

@brianchandotcom please do a kernel release after merging, thanks!

@rotty3000 @jrao please see https://github.com/shuyangzhou/liferay-portal/commit/33e295bc6e98ce586a3bad01a3ad2bffbaa9d952 for how we avoid duplicating CentralizedThreadLocal. This is part2 of petra-lang, next step is to portal compat it, which has to happen after a new kernel release.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
@pyoo47 this pull failed on collecting results from slaves.
```
pullrequest%28master%29/start.properties
     [exec] 502
   [delete] Deleting: /opt/dev/projects/github/liferay-jenkins-ee/commands/20170929150244760
    [retry] Attempt [59]: error occurred; retrying after 30000 ms...
     [echo] curl --output /opt/dev/projects/github/liferay-jenkins-ee/json.data --silent --write-out %{http_code} http://cloud-10-0-0-31/osb-jenkins-web/map/test-1-14/test-portal-acceptance-pullrequest%28master%29/2104/test-portal-acceptance-pullrequest%28master%29/start.properties
     [exec] 502
   [delete] Deleting: /opt/dev/projects/github/liferay-jenkins-ee/commands/20170929150640292

BUILD FAILED
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-test-portal-acceptance-pullrequest.xml:1152: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:77: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:4634: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:4472: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:457: Task [sequential] failed after [60] attempts; giving up.
Error messages:
503
503
503
```

@brianchandotcom the previous pull only failed on SF https://github.com/brianchandotcom/liferay-portal/pull/51870, which is fixed here. This one is good to go

**Comment by michaelhashimoto** [comment]
ci:retest

@shuyangzhou @pyoo47 - I'm going to retest this one, JSON Temp Map died last night.

**Comment by shuyangzhou** [comment]
Rebased and resent at https://github.com/brianchandotcom/liferay-portal/pull/52014

**Pull request closed without merging**
