### PR TITLE
LPS-96704 baseline

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
@ealonso @jkappler @darquesdev

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a8cc39c973...056985a6c5

**Comment by brianchandotcom** [comment]
@achaparro @hhuijser see modules/apps/fragment/fragment-service/src/main/resources/com/liferay/fragment/internal/upgrade/v2_2_0/dependencies/update.sql

@victorg1991 @ruben-pulido I backported this to 7.2.x for you guys.

Thx.

**Pull request closed without merging**
