### PR TITLE
LPS-66697 (foundation) Remove unnecessary com.liferay.registry.api fr…

### PR DESCRIPTION
**Pull request by peterfellwock**
…om build.gradle in modules

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/16da9beadb...991b3cff08

**Comment by jpince** [comment]
@peterfellwock This pull had an SF failure in portal-messaging/build.gradle that was not visible in the github comment due to the other unrelated errors. (Note in the job summary that test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8 failed, this is the batch that the source formatter runs in) Can you please look into it?
```
org.junit.ComparisonFailure: ../../../modules/apps/foundation/portal/portal-messaging/build.gradle expected:<...", version: "1.3.0"
[]}> but was:<...", version: "1.3.0"
[
]}>
```

**Comment by peterfellwock** [comment]
@jpince I am not able to repro this problem. Is there a pull anywhere (except this one) that is causing this as well?

**Comment by jpince** [comment]
Looks like Julio had a pull already open to fix the issue, already committed in https://github.com/liferay/liferay-portal/commit/f3a4de93c7973af72ea115332a552ead216f7467

Thanks @juliocamarero!

**Pull request closed without merging**
