### PR TITLE
master-sc-450

### PR DESCRIPTION
**Pull request by sharonchoi**
https://issues.liferay.com/browse/LRQA-22092
https://issues.liferay.com/browse/LRQA-22080
https://issues.liferay.com/browse/LRQA-21987
https://issues.liferay.com/browse/LRQA-21984
https://issues.liferay.com/browse/LRQA-22090

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@sharonchoi I just merged this in, please send a follow up pull to fix PoshiRunner.test[PortalconfigurationUsecase#DefaultPortalLandingPage

if it's real. If not, disable it and find out why it broke. Thx

cc @brianchiu

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5c38cab9b7...572ed8f9a2

**Comment by sharonchoi** [comment]
Hmmm...test seems to be flaky, and should be potentially fixed by this incoming pull: https://github.com/evannagayama/liferay-portal/pull/532

@brianchandotcom @brianchiu

**Comment by brianchiu** [comment]
Yes. It will be fixed by https://github.com/evannagayama/liferay-portal/pull/532.

This issue is something systemic that affects all of our tests that add a site.

**Pull request closed without merging**
