### PR TITLE
LPS-96095

### PR DESCRIPTION
**Pull request by samuelkong**
@arthurchan35

### CODE REVIEW

**Comment by samuelkong** [comment]
ci:reopen

**Comment by samuelkong** [comment]
SF issues should be fixed after https://github.com/brianchandotcom/liferay-portal-ee/pull/24997/files is merged.

**Comment by jpince** [comment]
@lawrence-lee not sure if the `ProjectTemplateFilesTest` failure is related to this pull, but it's passing in upstream.

**Comment by lawrence-lee** [comment]
Good find! Thanks @jpince

@samuelkong & @arthurchan35, Please back out the changes to project-templates. We dont want these changes merged to master.

**Comment by lawrence-lee** [comment]
Also, is the plan to backport this to other branches?

**Comment by lawrence-lee** [comment]
ci:close for now

**Pull request closed without merging**
