### PR TITLE
Revert "LPS-60027 Export this listener because we need it"

### PR DESCRIPTION
**Pull request by csierra**
/cc @danielkocsis

### CODE REVIEW

**Comment by csierra** [comment]
ci:stop

**Comment by csierra** [comment]
ci:retest

**Comment by brianchiu** [comment]
The upgrade tests here failed because there was an error during startup on all 3 upgrade tests. This is specific to DB upgrade because other poshi tests did not fail.

```
     [exec] 17:34:46,766 ERROR [Framework Event Dispatcher: Equinox Container: 90850356-e707-0016-1e6c-ceee7662c704][com_liferay_exportimport_resources_importer:97] FrameworkEvent ERROR 
     [exec] org.osgi.framework.BundleException: Exception in com.liferay.exportimport.resources.importer.internal.ResourcesImporterBundleActivator.start() of bundle com.liferay.exportimport.resources.importer.
     [exec] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:795)
     [exec] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:724)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:951)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:328)
     [exec] 	at org.eclipse.osgi.container.Module.doStart(Module.java:566)
     [exec] 	at org.eclipse.osgi.container.Module.start(Module.java:434)
     [exec] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
     [exec] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
     [exec] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
     [exec] 	at org.eclipse.osgi.container.SystemModule.startWorker(SystemModule.java:242)
     [exec] 	at org.eclipse.osgi.container.Module.doStart(Module.java:566)
     [exec] 	at org.eclipse.osgi.container.Module.start(Module.java:434)
     [exec] 	at org.eclipse.osgi.container.SystemModule.start(SystemModule.java:172)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:421)
     [exec] 	at org.eclipse.osgi.launch.Equinox.start(Equinox.java:115)
     [exec] 	at com.liferay.portal.bootstrap.ModuleFrameworkImpl.startFramework(ModuleFrameworkImpl.java:394)
     [exec] 	at com.liferay.portal.module.framework.ModuleFrameworkUtilAdapter.startFramework(ModuleFrameworkUtilAdapter.java:93)
     [exec] 	at com.liferay.portal.spring.context.PortalContextLoaderListener.contextInitialized(PortalContextLoaderListener.java:259)
     [exec] 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812)
     [exec] 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255)
     [exec] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
     [exec] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
     [exec] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
     [exec] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
     [exec] 	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:585)
     [exec] 	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1794)
     [exec] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
     [exec] 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
     [exec] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [exec] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [exec] 	at java.lang.Thread.run(Thread.java:745)
     [exec] Caused by: java.lang.NullPointerException
     [exec] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.ungetService(ServiceRegistry.java:538)
     [exec] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.ungetService(BundleContextImpl.java:661)
     [exec] 	at com.liferay.exportimport.resources.importer.internal.ResourcesImporterBundleActivator.start(ResourcesImporterBundleActivator.java:60)
     [exec] 	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:774)
     [exec] 	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
     [exec] 	at java.security.AccessController.doPrivileged(Native Method)
     [exec] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:767)
     [exec] 	... 31 more
```

**Comment by csierra** [comment]
ci:retest

**Comment by csierra** [comment]
thanks @brianchiu... let's see now

**Comment by brianchandotcom** [comment]
@csierra you can ignore the KB related errors, but the rules engine one is real :( Please resend.

**Comment by brianchiu** [comment]
@csierra 
FYI your new commit did fix the DB Upgrade failures.

**Pull request closed without merging**
