### PR TITLE
LPS-103728 buildLang

### PR DESCRIPTION
**Pull request by 4lejandrito**
Hi @brianchandotcom,

We are happy for this to be published and included in GA2. It is disabled by default so there won't be any functional impact and it will allow us to iterate faster.

I've added a few fields (https://github.com/brianchandotcom/liferay-portal/pull/86198/commits/c351321db7f2a4f6df938d8bdc3cf11e55ecefba) that we will need for following stories to avoid unnecessary upgrades after the first publication.

I've also included [LPS-103728](https://issues.liferay.com/browse/LPS-103728) in this pull request since the changes overlap.

Thanks!

@adolfopa

### CODE REVIEW

**Comment by 4lejandrito** [comment]
@brianchandotcom failures don't seem related. @austinchiang can you help me verify?

**Comment by brianchandotcom** [comment]
@austinchiang please reopen pull if it is safe. Thx.

**Comment by austinchiang** [comment]
ci:reopen

**Comment by austinchiang** [comment]
@brianchandotcom reopened; test failures unrelated.

**Comment by brianchandotcom** [comment]
@4lejandrito this needs to match service.xml

```
	public RedirectEntry addRedirectEntry(
			long groupId, String destinationURL, String sourceURL,
			boolean temporary, Date expirationDate,
			ServiceContext serviceContext)
		throws PortalException {**
```

order is off. Please resend.

**Comment by 4lejandrito** [comment]
@brianchandotcom see https://github.com/brianchandotcom/liferay-portal/pull/86220.

**Pull request closed without merging**
