### PR TITLE
LPS-74631 Remove duplicated property key

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1af20e34ca...6c35399feb

**Comment by brianchandotcom** [comment]
@achaparro can you work with @mbowerman on this? I think this should go in 7_0_5 since 7_0_4 was already released and we can't go back in time. Thx.

**Comment by brianchandotcom** [comment]
@mbowerman @achaparro I did merge this in though.

**Comment by achaparro** [comment]
ok @brianchandotcom, this is the pull:
https://github.com/brianchandotcom/liferay-portal/pull/51920

**Pull request closed without merging**
