### PR TITLE
LPS-102672 Source formatting

### PR DESCRIPTION
**Pull request by brunofarache**

### CODE REVIEW

**Comment by brunofarache** [comment]
@brianchandotcom failures are not related to this PR. @leoadb @marcelabc are you looking into this already?

**Comment by leoadb** [comment]
@brunofarache I think Forms team is looking into it. Some of my pulls are also presenting the same errors. @natocesarrego

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/81567698f3...50c1c26116

**Comment by natocesarrego** [comment]
Hey @brunofarache and @leoadb,

Forms team is already aware of these failures and we'll try to address these issues ASAP.

Thanks.

**Pull request closed without merging**
