### PR TITLE
Lps 59076

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by hhuijser** [comment]
@brianchandotcom @shuyangzhou 

If we'd have rules on how to detect those, we can...
Shuyang, what would be the rule? Is it even that simple?

**Comment by shuyangzhou** [comment]
Technically we can do this,
1) Knowing what spring beans do we have in the current module.
		This can be done by checking spring extender header in bnd file + spring xml scaning. Totally doable.
2) Look into each spring bean, if you see @BeanReference, skip it, this is a good one. If you don't see any @BeanReference, this can a bad one. Totally doable.

3) Now it comes to the hard part...
	For example, by the standards in 1) and 2), the ShoppingPermission in my previous sample changes would be considered as a hit, it should be a @Component rather than a Spring bean, which is technically correct.
	But I changed it to Spring bean anyway, the reason is all its siblings ShoppingXYZPermission are spring beans, I thought we should change it too to keep things consistent.

@brianchandotcom, this is up to you, if you say, in cases like ShoppingPermission, make it @Component, even it does not look very consistent. Then @hhuijser the steps I just said is exactly what you need to do. Otherwise it is going to be very difficult to know from SF what is considered as a necessary tolerance for consistency, what is not...

**Comment by hhuijser** [comment]
Got it. That does seem doable (hopefully without slowing down SF too much...)

One thing we need to think about is how we communicate all of this to all the engineers.
I already had someone ask me what the SF warning "LPS-59076: Convert OSGi Component to Spring bean" means, so proper documentation would be good (otherwise I'll have lots of folks email me with that question...)

**Comment by shuyangzhou** [comment]
Yeah, I get that, I can see how people would get confused.
I think we should document it on the LPS tickets, and have SF print out the ticket number to the matched warning message, at least this will give them a way to read back.

**Comment by hhuijser** [comment]
Yup, I usually do that for those kind of warning, like this one.
Can you work on the documentation on LPS-59076?

**Comment by shuyangzhou** [comment]
I can, but I don't think I can explain it in the most clearest way, after all, english is not my 1st language.
Can you make it first? I can double check on your version, to correct things if there is anything not technically right.

**Comment by hhuijser** [comment]
I can draft something later

**Comment by hhuijser** [comment]
Actually, @peterfellwock, can you draft something (you explained the issue very clear in the email)?
After all, English is my second language as well :)

**Pull request closed without merging**
