### PR TITLE
CLDSVCS-74839 petra-json-web-service-client - Auto - baseline

### PR DESCRIPTION
**Pull request by ivicac**
Hi Brian,
can you also, please, release a new version of the petra-json-web-service-client(v4.1.0) as we are missing some public methods?

Best Regards

@igorbeslic

### CODE REVIEW

**Comment by ivicac** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9c1f23d308...a315c4bf80

**Comment by brianchandotcom** [comment]
@ivicac done, published a new jar for you.

**Comment by ivicac** [comment]
@brianchandotcom thank you

**Pull request closed without merging**
