### PR TITLE
LPS-78477 BigDecimal

### PR DESCRIPTION
**Pull request by Preston-Crary**
CC @marco-leo @shuyangzhou

@brianchandotcom we're planning on bringing over any relevant changes from the service builder plugin at a later time. There isn't much added value from having that plugin even with these changes so if you want to remove it now that should be fine too.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.

**Comment by brianchandotcom** [comment]
@zsoltbalogh I backported this because we're still figuring out how to split ServiceBuilder between master and 7.0.x.

**Comment by brianchandotcom** [comment]
@Preston-Crary please send me tests in separate pull. Thx.

**Comment by brianchandotcom** [comment]
@marcoleo fyi the feature is pushed to latest Gradle plugin.

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/56703

**Pull request closed without merging**
