### PR TITLE
LPS-140150 Rename file

### PR DESCRIPTION
**Pull request by kevenleone**

### CODE REVIEW

**Comment by kevenleone** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/00e01b73b9...c6a68bf0af

**Comment by brianchandotcom** [comment]
@kevenleone I merged this, but I cannot run "gw forceDeploy" without getting a node error.

If that works, then I can upload the jar so "gw deploy" works.

**Comment by kevenleone** [comment]
fixed here, @brianchandotcom https://github.com/brianchandotcom/liferay-portal/pull/110069

**Pull request closed without merging**
