### PR TITLE
LPS-61095

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@shuyangzhou fyi, this should resolve the dependency issue w/ portal.

**Comment by shuyangzhou** [comment]
Awesome!

**Comment by mhan810** [comment]
@brianchandotcom the SF breaks are due to removal of volatile keyword.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6a6f826292...ee4e777e86

**Pull request closed without merging**
