### PR TITLE
Prototype of Persistence Test in Polls Modules

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
First 2 commits are included in the pull https://github.com/brianchandotcom/liferay-portal/pull/23623, but they are need for this pull too.

To execute the persistente test of polls you need to follow these steps:

1) Provide a tomcat with liferay (follow the steps in https://www.liferay.com/es/web/manuel.delapenya/blog/-/blogs/-the-plugin-worked-on-my-computer-is-not-valid-anymore). 

   1.1) Execute: ant setup-arquillian

2) Install test modules in the osgi container:

    2.1) Before run tomcat, copy the JARs portal-test.jar and portal-test-infernal.jar inside the bundle/osgi/modules folder.

3) Uninstall the Poll Service module in tomcat.

4) Execute ant test inside the folder modules/apps/poll/poll-service.

We are working in an automatic solution for only execute "ant test" and that the test can be executed directly, but we need to work on that a little bit longer. For that solucion we need to develop a managed liferay tomcat.

Thanks!!!

@csierra, @migue, @shuyangzhou, @jorgeferrer

**Comment by shuyangzhou** [comment]
Thanks @csierra, I will start look into this today, will ping you if run into any problem.

**Comment by shuyangzhou** [comment]
The arquillian-extension-transactional-remote does not compile for me.

compile:
    [javac] Compiling 5 source files to /home/trunks/git/liferay-portal/modules/test/arquillian-extension-transactional-remote/classes
    [javac] /home/trunks/git/liferay-portal/modules/test/arquillian-extension-transactional-remote/src/com/liferay/arquillian/extension/transactional/internal/enricher/TransactionalLiferayAuxiliaryAppender.java:27: error: package org.jboss.osgi.metadata does not exist
    [javac] import org.jboss.osgi.metadata.OSGiManifestBuilder;
    [javac]                               ^
    [javac] /home/trunks/git/liferay-portal/modules/test/arquillian-extension-transactional-remote/src/com/liferay/arquillian/extension/transactional/internal/enricher/TransactionalLiferayAuxiliaryAppender.java:44: error: cannot find symbol
    [javac] 		final OSGiManifestBuilder builder = OSGiManifestBuilder.newInstance();
    [javac] 		      ^
    [javac]   symbol:   class OSGiManifestBuilder
    [javac]   location: class TransactionalLiferayAuxiliaryAppender
    [javac] /home/trunks/git/liferay-portal/modules/test/arquillian-extension-transactional-remote/src/com/liferay/arquillian/extension/transactional/internal/enricher/TransactionalLiferayAuxiliaryAppender.java:44: error: cannot find symbol
    [javac] 		final OSGiManifestBuilder builder = OSGiManifestBuilder.newInstance();
    [javac] 		                                    ^
    [javac]   symbol:   variable OSGiManifestBuilder
    [javac]   location: class TransactionalLiferayAuxiliaryAppender
    [javac] 3 errors

BUILD FAILED
/home/trunks/git/liferay-portal/tools/sdk/build-common.xml:2638: The following error occurred while executing this line:
: The following error occurred while executing this line:
/home/trunks/git/liferay-portal/tools/sdk/build-common.xml:1244: The following error occurred while executing this line:
: The following error occurred while executing this line:
/home/trunks/git/liferay-portal/tools/sdk/build-common.xml:1661: The following error occurred while executing this line:
: The following error occurred while executing this line:
/home/trunks/git/liferay-portal/modules/test/arquillian-extension-transactional-remote/build.xml:17: The following error occurred while executing this line:
/home/trunks/git/liferay-portal/tools/sdk/build-common.xml:518: The following error occurred while executing this line:
/home/trunks/git/liferay-portal/tools/sdk/build-common.xml:782: Compile failed; see the compiler error output for details.

Do I need any special settings for it?

**Comment by shuyangzhou** [comment]
Seems you missed : <dependency name="jbosgi-metadata" org="org.jboss.osgi.metadata" rev="4.0.0.CR1" /> in ivy.xml

Adding that works for me, I am not sure which version to use, I am just adding the latest one for now, please update the pull to fix this, thanks!

**Comment by cgoncas** [comment]
Sorry @shuyangzhou ,

   Now it is fixed.

Thanks for notice :)

**Comment by shuyangzhou** [comment]
When running the test, I am getting this error:

    [junit] Testcase: com.liferay.polls.service.persistence.test.PollsChoicePersistenceTest:	Caused an ERROR
    [junit] com/liferay/arquillian/extension/transactional/internal/util/TransactionalExecutor
    [junit] java.lang.NoClassDefFoundError: com/liferay/arquillian/extension/transactional/internal/util/TransactionalExecutor
    [junit] 	at com.liferay.arquillian.extension.transactional.internal.enricher.TransactionalLiferayAuxiliaryAppender.createAuxiliaryArchive(TransactionalLiferayAuxiliaryAppender.java:76)
    [junit] 	at org.jboss.arquillian.container.test.impl.client.deployment.DeploymentGenerator.loadAuxiliaryArchives(DeploymentGenerator.java:209)
    [junit] 	at org.jboss.arquillian.container.test.impl.client.deployment.DeploymentGenerator.buildTestableDeployments(DeploymentGenerator.java:160)
    [junit] 	at org.jboss.arquillian.container.test.impl.client.deployment.DeploymentGenerator.createTestableDeployments(DeploymentGenerator.java:148)
    [junit] 	at org.jboss.arquillian.container.test.impl.client.deployment.DeploymentGenerator.generateDeployment(DeploymentGenerator.java:85)
    [junit] 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
    [junit] 	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
    [junit] 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
    [junit] 	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:135)
    [junit] 	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:115)
    [junit] 	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
    [junit] 	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.execute(ContainerEventController.java:100)
    [junit] 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
    [junit] 	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
    [junit] 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
    [junit] 	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:65)
    [junit] 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
    [junit] 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
    [junit] 	at org.jboss.arquillian.test.impl.TestContextHandler.createClassContext(TestContextHandler.java:84)
    [junit] 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
    [junit] 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
    [junit] 	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:135)
    [junit] 	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:115)
    [junit] 	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeClass(EventTestRunnerAdaptor.java:80)
    [junit] 	at org.jboss.arquillian.junit.Arquillian$2.evaluate(Arquillian.java:182)
    [junit] 	at org.jboss.arquillian.junit.Arquillian.multiExecute(Arquillian.java:314)
    [junit] 	at org.jboss.arquillian.junit.Arquillian.access$100(Arquillian.java:46)
    [junit] 	at org.jboss.arquillian.junit.Arquillian$3.evaluate(Arquillian.java:199)
    [junit] 	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:147)
    [junit] Caused by: java.lang.ClassNotFoundException: com.liferay.arquillian.extension.transactional.internal.util.TransactionalExecutor
    [junit] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    [junit] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    [junit] 	at java.security.AccessController.doPrivileged(Native Method)
    [junit] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    [junit] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    [junit] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    [junit] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)



Any idea?

**Comment by shuyangzhou** [comment]
I guess you missed this commit from the other pull https://github.com/cgoncas/liferay-portal/commit/34d10498406bf45ce82e6f79c5a28442b5e425a7 , can you fix this?

**Comment by shuyangzhou** [comment]
the integration test does not declared dependency to module arquillian-extension-transactional, that's why it is failing.

**Comment by cgoncas** [comment]
Thanks @shuyangzhou, can you try change the ivy.xml and set the transitivity to true in the declararon of the library com.liferay.arquillian.extension.remote.transactional:

<dependency conf="test->default" name="com.liferay.arquillian.extension.remote.transactional" org="com.liferay" rev="latest.integration" transitive="true" />

**Comment by shuyangzhou** [comment]
Changed to < dependency name="com.liferay.arquillian.extension.transactional" org="com.liferay" rev="1.0.0-SNAPSHOT" transitive="true" / > in arquillian-extension-transactional-remote ivy.xml

Still same error.

Can you update the pull with the right fix?

**Comment by shuyangzhou** [comment]
I cherry picked that commit, it still does not work. I think when running test for modules, we are using the build xmls from sdk, not the portal ones, and your commit only changed the portal side build.xml, that's why it is not working.

Seems there are a lot of issues in this pull.

Can you try it locally on your side to make sure it is working, then resend, that will save time for both of us. Thanks!

**Comment by cgoncas** [comment]
Sorry @shuyangzhou , I can't make it fail on my computer :(. I Think it's a libs problem. Can you delete your folders .ivy/cache/com.liferay/com.liferay.arquillian.extension.remote.transactional/ .ivy/cache/com.liferay/com.liferay.arquillian.extension.transactional/ and publish in your local repo (ant publish-local-m2-snapshot) the extensions arquillian-extension-transactional and arquillian-extension-transactional-remote.

I'm creating a new user to clean all my environment, to try to reproduce the issue, but if you can try it would be great.

Thank you!!!

**Comment by cgoncas** [comment]
Now I can reproduce it, my local remote transactional lib its old sorry, i will fix it for your.  Thanks a lot :) @shuyangzhou.

**Comment by shuyangzhou** [comment]
Great, thanks! I will wait for your new pull to continue on this.

**Comment by cgoncas** [comment]
Try to downloaded it and clean all the .ivy/cache files. In my computer these files were unstaged and giving my problems :)

**Comment by shuyangzhou** [comment]
You mean I can try this pull now? You already made the change?

**Comment by cgoncas** [comment]
Yeahhh. After delete the cache i get the same error that you get. I add transitive=true and now it works, can you try it now?

**Comment by shuyangzhou** [comment]
Hmm, that error went away. But I got a new one:
If I delete osgi/modules/com.liferay.polls.service.jar, as you asked for it. I got this error.
    [junit] Testcase: com.liferay.polls.service.persistence.test.PollsChoicePersistenceTest:	Caused an ERROR
    [junit] Start of bundle with id 79 failed with message: Could not resolve module: com.liferay.polls.service [79]
    [junit]   Unresolved requirement: Import-Package: com.liferay.portal.test.randomizerbumpers
    [junit] 
    [junit] java.io.IOException: Start of bundle with id 79 failed with message: Could not resolve module: com.liferay.polls.service [79]
    [junit]   Unresolved requirement: Import-Package: com.liferay.portal.test.randomizerbumpers
    [junit] 
    [junit] 	at org.apache.aries.jmx.framework.Framework.startBundle(Framework.java:461)
    [junit] 	at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:112)
    [junit] 	at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:46)
    [junit] 	at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
    [junit] 	at com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138)
    [junit] 	at com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252)
    [junit] 	at javax.management.StandardMBean.invoke(StandardMBean.java:405)
    [junit] 	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
    [junit] 	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
    [junit] 	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1487)
    [junit] 	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:97)
    [junit] 	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1328)
    [junit] 	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1420)
    [junit] 	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:848)
    [junit] 	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:322)
    [junit] 	at sun.rmi.transport.Transport$1.run(Transport.java:177)
    [junit] 	at sun.rmi.transport.Transport$1.run(Transport.java:174)
    [junit] 	at java.security.AccessController.doPrivileged(Native Method)
    [junit] 	at sun.rmi.transport.Transport.serviceCall(Transport.java:173)
    [junit] 	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:556)
    [junit] 	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:811)
    [junit] 	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:670)
    [junit] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    [junit] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    [junit] 	at java.lang.Thread.run(Thread.java:745)
    [junit] Caused by: org.osgi.framework.BundleException: Could not resolve module: com.liferay.polls.service [79]
    [junit]   Unresolved requirement: Import-Package: com.liferay.portal.test.randomizerbumpers
    [junit] 
    [junit] 	at org.eclipse.osgi.container.Module.start(Module.java:434)
    [junit] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:392)
    [junit] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:411)
    [junit] 	at org.apache.aries.jmx.framework.Framework.startBundle(Framework.java:459)
    [junit] 
    [junit] 
    [junit] TEST com.liferay.polls.service.persistence.test.PollsChoicePersistenceTest FAILED


If I keep the osgi/modules/com.liferay.polls.service.jar, I got this:

    [junit] Testcase: com.liferay.polls.service.persistence.test.PollsChoicePersistenceTest:	Caused an ERROR
    [junit] Cannot deploy: 22e8d310-bf69-4056-9420-ad52a44097cf.jar
    [junit] org.jboss.arquillian.container.spi.client.container.DeploymentException: Cannot deploy: 22e8d310-bf69-4056-9420-ad52a44097cf.jar
    [junit] 	at org.jboss.arquillian.container.osgi.jmx.JMXDeployableContainer.deploy(JMXDeployableContainer.java:111)
    [junit] 	at com.liferay.arquillian.container.remote.LiferayRemoteDeployableContainer.deploy(LiferayRemoteDeployableContainer.java:40)
    [junit] 	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$3.call(ContainerDeployController.java:161)
    [junit] 	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$3.call(ContainerDeployController.java:128)
    [junit] 	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.executeOperation(ContainerDeployController.java:271)
    [junit] 	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.deploy(ContainerDeployController.java:127)
    [junit] 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
    [junit] 	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
    [junit] 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
    [junit] 	at org.jboss.arquillian.container.impl.client.ContainerDeploymentContextHandler.createDeploymentContext(ContainerDeploymentContextHandler.java:78)
    [junit] 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
    [junit] 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
    [junit] 	at org.jboss.arquillian.container.impl.client.ContainerDeploymentContextHandler.createContainerContext(ContainerDeploymentContextHandler.java:57)
    [junit] 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
    [junit] 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
    [junit] 	at org.jboss.arquillian.container.impl.client.container.DeploymentExceptionHandler.verifyExpectedExceptionDuringDeploy(DeploymentExceptionHandler.java:50)
    [junit] 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
    [junit] 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
    [junit] 	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:135)
    [junit] 	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:115)
    [junit] 	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
    [junit] 	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$1.perform(ContainerDeployController.java:95)
    [junit] 	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$1.perform(ContainerDeployController.java:80)
    [junit] 	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.forEachDeployment(ContainerDeployController.java:263)
    [junit] 	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.forEachManagedDeployment(ContainerDeployController.java:239)
    [junit] 	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.deployManaged(ContainerDeployController.java:79)
    [junit] 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
    [junit] 	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
    [junit] 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
    [junit] 	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:135)
    [junit] 	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:115)
    [junit] 	at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
    [junit] 	at org.jboss.arquillian.container.test.impl.client.ContainerEventController.execute(ContainerEventController.java:101)
    [junit] 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
    [junit] 	at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
    [junit] 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
    [junit] 	at org.jboss.arquillian.test.impl.TestContextHandler.createClassContext(TestContextHandler.java:84)
    [junit] 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
    [junit] 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
    [junit] 	at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:65)
    [junit] 	at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
    [junit] 	at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:88)
    [junit] 	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:135)
    [junit] 	at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:115)
    [junit] 	at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeClass(EventTestRunnerAdaptor.java:80)
    [junit] 	at org.jboss.arquillian.junit.Arquillian$2.evaluate(Arquillian.java:182)
    [junit] 	at org.jboss.arquillian.junit.Arquillian.multiExecute(Arquillian.java:314)
    [junit] 	at org.jboss.arquillian.junit.Arquillian.access$100(Arquillian.java:46)
    [junit] 	at org.jboss.arquillian.junit.Arquillian$3.evaluate(Arquillian.java:199)
    [junit] 	at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:147)
    [junit] Caused by: java.io.IOException: Installation of a bundle with location 22e8d310-bf69-4056-9420-ad52a44097cf.jar failed with the message: A bundle is already installed with the name "com.liferay.polls.service" and version "1.0.0"
    [junit] 	at org.apache.aries.jmx.framework.Framework.installBundleFromURL(Framework.java:152)
    [junit] 	at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:112)
    [junit] 	at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:46)
    [junit] 	at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
    [junit] 	at com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138)
    [junit] 	at com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252)
    [junit] 	at javax.management.StandardMBean.invoke(StandardMBean.java:405)
    [junit] 	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
    [junit] 	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
    [junit] 	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1487)
    [junit] 	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:97)
    [junit] 	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1328)
    [junit] 	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1420)
    [junit] 	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:848)
    [junit] 	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:322)
    [junit] 	at sun.rmi.transport.Transport$1.run(Transport.java:177)
    [junit] 	at sun.rmi.transport.Transport$1.run(Transport.java:174)
    [junit] 	at java.security.AccessController.doPrivileged(Native Method)
    [junit] 	at sun.rmi.transport.Transport.serviceCall(Transport.java:173)
    [junit] 	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:556)
    [junit] 	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:811)
    [junit] 	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:670)
    [junit] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    [junit] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    [junit] 	at java.lang.Thread.run(Thread.java:745)
    [junit] Caused by: org.osgi.framework.BundleException: A bundle is already installed with the name "com.liferay.polls.service" and version "1.0.0"
    [junit] 	at org.eclipse.osgi.container.ModuleContainer.install(ModuleContainer.java:254)
    [junit] 	at org.eclipse.osgi.storage.Storage.install(Storage.java:513)
    [junit] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.installBundle(BundleContextImpl.java:146)
    [junit] 	at org.apache.aries.jmx.framework.Framework.installBundleFromURL(Framework.java:149)
    [junit] 
    [junit] 
    [junit] TEST com.liferay.polls.service.persistence.test.PollsChoicePersistenceTest FAILED

Any idea?

**Comment by cgoncas** [comment]
Hey!!!

Have you installed as a module portal-test and portal-test-infernal???

portal-test exports this pacakge.

Can you connect to the osgi console of liferay and check if the module is installed?

Thanks!!

**Comment by cgoncas** [comment]
The other problem:

A bundle is already installed with the name "com.liferay.polls.s...

After execute the test, you should unistall de Poll Service bundle

**Comment by cgoncas** [comment]
My skype user is cristina.liferay. If you want we can configure your environment quickly using skype :).

**Comment by shuyangzhou** [comment]
Can you point me to the repo that you use to generate the commit https://github.com/cgoncas/liferay-portal/commit/3b056ffd3999c671de72626d38ec9cd97eeaf58c ?
I need to rewire some dependency to make my thing work. 

I tried https://github.com/arquillian/arquillian-extension-liferay, their code does not match your generated jars. Please let me know your repo, I will fork it, and if you have any local changes, please send pulls to me so that I can rebuild those jars, thanks!

**Comment by shuyangzhou** [comment]
And I need to upgrade arquillian to 1.1.6.Final release, want to check with you first to see whether it will rise any issue on your end.

**Pull request closed without merging**
