### PR TITLE
LRQA-29212, LRQA-29642 | master

### PR DESCRIPTION
**Pull request by vicnate5**
https://issues.liferay.com/browse/LRQA-29212
https://issues.liferay.com/browse/LRQA-29642
@sharonchoi

### CODE REVIEW

**Comment by vicnate5** [comment]
Sent to 70.x https://github.com/brianchandotcom/liferay-portal/pull/45400

**Comment by michaelhashimoto** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

https://loop.liferay.com/home/-/loop/feed/3506548

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by vicnate5** [comment]
ci:reopen

**Comment by vicnate5** [comment]
@brianchandotcom This only got merged to 7.0.x, could you merge to master as well?

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
