### PR TITLE
LPS-118554 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-118554

This is only for master.

@jkappler

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure task is not related to the change in PR.
See https://github.com/liferay-echo/liferay-portal/pull/1785
✔️ ci:test:stable - 21 out of 21 jobs passed
❌ ci:test:relevant - 44 out of 46 jobs passed in 3 hours 13 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/dbd687ea04...89c180e178

**Comment by brianchandotcom** [comment]
@Tim-Cao @jkappler see d6a1910

**Pull request closed without merging**
