### PR TITLE
Lps 72541

### PR DESCRIPTION
**Pull request by shuyangzhou**
@brianchandotcom this includes https://github.com/brianchandotcom/liferay-portal/pull/50147

CC @mdelapenya

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 what happened here?

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@shuyangzhou 

```
Do not import method 'com.liferay.portal.configuration.easyconf.ClassLoaderComponentConfiguration.decode', import class 'com.liferay.portal.configuration.easyconf.ClassLoaderComponentConfiguration' instead: ./portal-impl/test/unit/com/liferay/portal/configuration/easyconf/ClassLoaderComponentConfigurationTest.java 17
     [java] Exception in thread "main" java.lang.Exception: Do not import method 'com.liferay.portal.configuration.easyconf.ClassLoaderComponentConfiguration.decode', import class 'com.liferay.portal.configuration.easyconf.ClassLoaderComponentConfiguration' instead: ./portal-impl/test/unit/com/liferay/portal/configuration/easyconf/ClassLoaderComponentConfigurationTest.java 17
     [java] 
    
```

Please resend? Thx.

**Comment by shuyangzhou** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/50232

**Pull request closed without merging**
