### PR TITLE
LPS-81681 Add missing key

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
Based on the images on the LPS ticket, this is the wong key.

It always expects the searched for value to appear to the RIGHT of the key.

55 results for X

However, in Hebrew, it should appear on the left.

So it should be

X 55 results for

But the key doesn't deal with X, just 55.

Please resend key and JS/JSP usage.

**Comment by brianchandotcom** [comment]
@jbalsas see my comment above. Thx.

**Comment by jbalsas** [comment]
Hey @brianchandotcom, that's a nice catch, you're totally right... the key is as it is because the searchedValue has a different styling and isn't currently part of it... if we made it part of the key, we'd be forcing usages to pass in html markup to make sure it has the proper styling.

I think this is probably going to be a tradeoff between correctness and UX, where we definitely want correctness. 

We'll double check with @victorvalle and resend the proper key.

Thanks!

**Pull request closed without merging**
