### PR TITLE
LPS-46553

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
@sergiogonzalez @izaera 
Same pull than https://github.com/brianchandotcom/liferay-portal/pull/30646 but I have added an additional check to avoid adding the period when extension is empty.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/17e460f82b...191f00f06a

**Comment by brianchandotcom** [comment]
@jorgediaz-lr good job on this.

**Pull request closed without merging**
