### PR TITLE
Lps 89565

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@pyoo47 this dir was removed modules/apps/document-library/document-library-rest-impl/

So the Git dir is stale in CI.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cd7eb0fa7d...1bfc6590ff

**Comment by brianchandotcom** [comment]
@mtambara @shuyangzhou please see my renames in 1bfc659

**Pull request closed without merging**
