### PR TITLE
LPS-204048 Updates Feature Flag Title, Description, and Type

### PR DESCRIPTION
**Pull request by JamesAGarcia**
This PR updates the feature flag title, description, and type for LPS-196768.

cc. @ruben-pulido, @ealonso

### CODE REVIEW

**Comment by JamesAGarcia** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/beba2887d7...06988d8327

**Comment by brianchandotcom** [comment]
@JamesAGarcia not a big fan of "Also, ..." Can you send a follow up PR?

**Comment by JamesAGarcia** [comment]
Noted 👍🏼 

Follow-up PR: https://github.com/brianchandotcom/liferay-portal/pull/145553

**Pull request closed without merging**
