### PR TITLE
LPS-58591 Getting double add entry button on Asset publisher portlet

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@kiyoshilee see the many weird VM related errors.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c99dc7d413...2bda93a510

**Comment by brianchandotcom** [comment]
@daviddotzhang @juliocamarero does it matter if it's a HashSet vs. a LinkedHashSet? i.e. does order matter? If it does, please send a follow up pull @daviddotzhang

**Comment by juliocamarero** [comment]
@daviddotzhang it would actually be more consistent for end users if we use a LinkedHashSet. Could you please make that change? thanks a lot @brianchandotcom!

**Pull request closed without merging**
