### PR TITLE
LPD-15723

### PR DESCRIPTION
**Pull request by ChrisKian**
Forwarded directly from https://github.com/liferay-appsec/liferay-portal/pull/1658 since an unrelated SF error is blocking forwards.

Resent from https://github.com/ChrisKian/liferay-portal/pull/323 with https://github.com/brianchandotcom/liferay-portal/pull/147670#issuecomment-1971026475 added.

See diff here https://github.com/ChrisKian/liferay-portal/compare/afdd89672dc5c8177bdd0dab536a031a338826d2...13619c091bd1d0d0ad7acc38ed7f3c2cc9bc46cd

CC @Stian-sigvartsen

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:reopen

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:reopen

**Comment by ChrisKian** [comment]
ci:test

**Comment by ChrisKian** [comment]
ci:reopen

**Comment by ChrisKian** [comment]
The SF error which is preventing forwarding is happening elsewhere, if portal.properties is modified.  See https://github.com/brianchandotcom/liferay-portal/pull/147865

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/97e9a36acb...b4c4fdd9c8

**Comment by brianchandotcom** [comment]
@ChrisKian see 9aa56646 and b4c4fdd9

**Pull request closed without merging**
