### PR TITLE
LPS-63608 initial changes for the layouts tree improvements

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/522a5c500e...e19f5f6ba5

**Comment by brianchiu** [comment]
@juliocamarero 

That Page Templates test failure looks to be consistent. I'm removing it from the pr tester for now.

@evannagayama is looking into it.

**Comment by juliocamarero** [comment]
Thanks @brianchiu!

**Pull request closed without merging**
