### PR TITLE
LPS-76337 Assimilate portal-search-facet module into portal-search

### PR DESCRIPTION
**Pull request by arboliveira**
All classes in `portal-search-facet` are internal implementation; transferring to `portal-search`. The `portal-search-facet` module itself will be removed by LPS-76382 and won't be part of any 7.1 LPKG. (cc/ @shuyangzhou)

I named the package as plain `com.liferay.portal.search.internal.searcher` because`FacetedSearcherImpl` itself will soon be refactored into smaller classes (following the new indexer architecture from https://issues.liferay.com/browse/LPS-73604) and focus will be on its "searcher" aspect - every Searcher is already "faceted" by nature.

https://issues.liferay.com/browse/LPS-76337
https://issues.liferay.com/browse/LPS-76382

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:test

**Comment by arboliveira** [comment]
`FileImplExtractTest.testJpg` is unrelated.

ci:reopen

**Comment by arboliveira** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/eb2ea0e192...a3b54322a4

**Comment by brianchandotcom** [comment]
@arboliveira backkport if it makes sense. Thx.

**Pull request closed without merging**
