### PR TITLE
LPS-109565 Single activate method to avoid NPE

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a54b2a516b...a294363774

**Comment by brianchandotcom** [comment]
@pavel-savinov @ealonso see a294363

**Pull request closed without merging**
