### PR TITLE
Lps 61952 Upgrade

### PR DESCRIPTION
**Pull request by willnewbury**
This has the upgrade that we will be using for all of the split-package changes. When we get more packages done, we can just update the CLASS_NAMES field found in the upgrade with the upgrade targets.

### CODE REVIEW

**Comment by willnewbury** [comment]
@Preston-Crary @shuyangzhou

**Comment by brianchandotcom** [comment]
ci:retest just borrowing pull for results

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0e77cea759...fdec505cc3

**Comment by brianchandotcom** [comment]
@willnewbury I renamed the files. See upstream. Thx.

**Pull request closed without merging**
