### PR TITLE
[TS] LPS-72226 FIX: Lucene unfriendly tokens crash wildcard queries in Solr

### PR DESCRIPTION
**Pull request by arboliveira**
Authors: @BryanEngler @arboliveira
Reviewer: @arboliveira

https://issues.liferay.com/browse/LPS-72226

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@arboliveira please backport. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a717f4badc...20afcd0c40

**Pull request closed without merging**
