### PR TITLE
master | LPS-129270

### PR DESCRIPTION
**Pull request by Sharryxue**
https://issues.liferay.com/browse/LPS-129270

/cc @ChrisKian @pei-jung @patriciajeanperez

### CODE REVIEW

**Comment by Sharryxue** [comment]
ci:reopen

**Comment by Sharryxue** [comment]
This is a manually forward for [pei-jung/liferay-portal#806]( https://github.com/pei-jung/liferay-portal/pull/806), the related tests passed in original pr, but blocked forwarding by a CI issue.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cb920a2bd1...681017b513

**Comment by ChrisKian** [comment]
lbm:backport:7.2.x

**Pull request closed without merging**
