### PR TITLE
LPS-106124 Rename SLAProcess to SLAInstance

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
Hey @barrosdennys, these failures are real or flaky? Thanks!

**Comment by barrosdennys** [comment]
ci:test:bundle

**Comment by barrosdennys** [comment]
Hi @inacionery ,
Checking what you changed and what is failing, there is no indication that this PR has caused the issue. The same actions that are failing on the tests are performed by other passing tests ran on this same PR.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4b02d1e3f7...7caa5c8edf

**Pull request closed without merging**
