### PR TITLE
LPS-104321 friendly urls

### PR DESCRIPTION
**Pull request by javiergamarra**
-- reviewed test failing in previous PR, also pinged Adolfo, look unrelated.

### CODE REVIEW

**Comment by nhpatt** [comment]
Sent also here: https://github.com/brianchandotcom/liferay-portal/pull/85408 (just changed 255 to 254 in substring)

**Comment by nhpatt** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@nhpatt can you regenerate based on my changes in https://github.com/nhpatt/liferay-portal/pull/234

**Comment by nhpatt** [comment]
Will do! :)

**Pull request closed without merging**
