### PR TITLE
LPS-77425 Remove version constraints in Require-Capabilities

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
@jpince, this fixes the issues in upstream

**Comment by jpince** [comment]
ci:test:relevant

**Comment by petershin** [comment]
Sent a patch to fix the version ranges: https://github.com/brianchandotcom/liferay-portal/pull/72256

**Comment by petershin** [comment]
ci:close

**Comment by jpince** [comment]
@istvand @jkappler @petershin thank you!

**Comment by jpince** [comment]
oops, meant to thank @izaera :sweat_smile:

**Pull request closed without merging**
