### PR TITLE
LPS-73629 Also account for the radio type during validation by assigning the selected radio option as the field and making sure to reset the unselected radio options

### PR DESCRIPTION
**Pull request by marcellustavares**
cc @leoadb @rafaprax

### CODE REVIEW

**Comment by marcellustavares** [comment]
@brandizzi, @netonery please see the calendar test is failing on this pull.

**Comment by inacionery** [comment]
Hey @marcellustavares, 

There is already an issue for this https://issues.liferay.com/browse/LPS-73788

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d201463db5...796196531f

**Comment by marcellustavares** [comment]
Thanks @inacionery!

**Pull request closed without merging**
