### PR TITLE
LPS-74849

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Backport: https://github.com/brianchandotcom/liferay-portal-ee/pull/18572

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ef17ecdf2e...2199542f7f

**Pull request closed without merging**
