### PR TITLE
LPS-107688 Support exporting inline content introduced within fragment editable elements

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
//cc @ealonso

**Comment by ruben-pulido** [comment]
//cc @pavel-savinov

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/57f367d9f8...6b4d548017

**Comment by brianchandotcom** [comment]
@ruben-pulido see af9aa8554b10dc2e61969b4c76ba82b25702b299 9d0e7e4821f39809586da5bd448ad06c60c18718 and 6b4d5480171ea718879352388d095ec3085ca62a

**Pull request closed without merging**
