### PR TITLE
LPS-68619 BaseUpgradePortletPreferences refactor

### PR DESCRIPTION
**Pull request by achaparro**
See performance results here:
https://issues.liferay.com/browse/LPS-68619

@holatuwol @mtambara

### CODE REVIEW

**Comment by pyoo47** [comment]
QA Engineering is investigating this failure.

**Comment by jpince** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6aea8e8e5d...e7563bac43

**Comment by brianchandotcom** [comment]
@achaparro @holatuwol very nice guys.

**Pull request closed without merging**
