### PR TITLE
LPS-76773 Extract tag configuration to a DC and use the new configuration model

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
Hey @hhuijser, this is going to fail SF with the following message:

```
Duplicate MultiValueColumn: ./src/main/java/com/liferay/frontend/taglib/chart/model/MultiValueColumn.java
Duplicate addGroup: ./src/main/java/com/liferay/frontend/taglib/chart/model/combination/CombinationChartConfig.java
Duplicate TypedMultiValueColumn: ./src/main/java/com/liferay/frontend/taglib/chart/model/TypedMultiValueColumn.java
```

The method signatures are different. Could you check it out?

Thanks!

**Comment by hhuijser** [comment]
@jbalsas I'll have a look

**Comment by hhuijser** [comment]
@jbalsas, you should have a space after `...`

`public void addGroup(String...ids) {` 

should be 
`public void addGroup(String... ids) {`

If you can fix those, you should be fine. I'll make sure SF catches those next time.

**Comment by hhuijser** [comment]
fyi: https://github.com/brianchandotcom/liferay-portal/pull/54579

**Comment by jbalsas** [comment]
Thanks a lot for that, @hhuijser! Fixed and resent to https://github.com/brianchandotcom/liferay-portal/pull/54595

**Pull request closed without merging**
