### PR TITLE
 LRQA-38970 Store the commit history in the database to be read by the jenkins reports

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-38970

### CODE REVIEW

**Comment by yichenroy** [comment]
PR tests kicked off manually

**Comment by yichenroy** [comment]
Aborted duplicate pr test started by backlogged webhook.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0a2e630d86...1f01387a51

**Comment by brianchandotcom** [comment]
@pyoo47 published.

**Pull request closed without merging**
