### PR TITLE
LPS-76629 SF - Reorder parameters

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by ealonso** [comment]
ci:reopen

**Comment by ealonso** [comment]
ci:retest

**Comment by jpince** [comment]
@michaelhashimoto @yichenroy @kenjiheigel see first result for git fetch errors, and this one (I think in [integration-oracle](https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/137404/AXIS_VARIABLE=0,label_exp=!master/consoleFull)):
`    [junit] java.sql.SQLRecoverableException: IO Error: Connection reset`

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ad944406bb...5fff77746a

**Pull request closed without merging**
