### PR TITLE
LPS-94981 Fix compile error

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@shuyangzhou see this pull. I'm merging it since it seems simple.

**Comment by shuyangzhou** [comment]
@inacionery Don't upgrade bnd just for bad IDE project setup. Upgrading bnd is a very risky thing, we are trying to do it before release, but due to other workload, we might not be able to finish it.
Registry-api is a real module, it deserves its own project, just setup it that way, then the lib/developement/bnd.jar won't bother you.

**Comment by inacionery** [comment]
Hey @shuyangzhou,

I understand the risk of upgrading, but as it was only a compileOnly, and since the compileInclude is 3.2.0, I have seen no greater risks. The registry-api has its own project in my IDE, but the portal-master is using it as you can see here:
Screen Shot 2019-05-02 at 14 00 43
and without this change, portal-master does not compile in the IDE.

I'm sorry if it caused any issue, would you prefer that I send a revert?

Thanks!

**Comment by shuyangzhou** [comment]
No idea what that portal-master thing is, not an eclipse user. This is only an IDE problem, just leave it alone. If bandwidth allows, we will unify bnd version across codebase before release. If you search, you will see there are tons of other reference to bnd with different versions too, not just registry-api. And many many other libs too, we also have a plan to unify every lib versions across codebase too. But as there is very little value here, the task has a low priority.

**Comment by shuyangzhou** [comment]
@inacionery and the risk of this change is not due to the compileOnly, yes, it is always safe. But the java code change is changing the logic slightly in case of failures.

**Comment by arboliveira** [comment]
Created https://issues.liferay.com/browse/LPS-95006 to gather information and monitor for news

**Pull request closed without merging**
