### PR TITLE
OAUTH2-224 Fix & re-enable test

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
[OAUTH2-224](https://issues.liferay.com/browse/OAUTH2-224)
Fix and re-enable test following on from brianchandotcom/liferay-portal/pull/63379

/cc @topolik @csierra

### CODE REVIEW

**Comment by jpince** [comment]
@stian-sigvartsen thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3342a71155...18d512787b

**Comment by brianchandotcom** [comment]
@jpince I backported this.

**Comment by brianchandotcom** [comment]
@jpince the test was never ignored in 7.1.x, but the oauth stuff should be the same in both branches, so I backported the test fix.

**Comment by jpince** [comment]
@brianchandotcom correct, I didn't take the time to backport it since the
failure in 7.1.x wouldn't be visible to many people.

**Pull request closed without merging**
