### PR TITLE
LPS-66239 As a Password Policies admin I can view the list of users as a grid of icons or in a descriptive list display

### PR DESCRIPTION
**Pull request by alee8888**

### CODE REVIEW

**Comment by alee8888** [comment]
@pei-jung @natecavanaugh 
There were no Poshi functional test fixes needed for LPS-66239.

**Comment by brianchandotcom** [comment]
@jasonpince @brianchiu is this good to merge?

**Comment by brianchiu** [comment]
@brianchandotcom 
Yes this is safe to merge. All the failures right now are caused by these two bugs:
https://issues.liferay.com/browse/LPS-66764 (Andre sent a revert for this)
https://issues.liferay.com/browse/LPS-66769 (We are not yet sure what causes this)

CC @jpince

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b469e8d632...a2926320c8

**Pull request closed without merging**
