### PR TITLE
LPS-76524

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:test

**Comment by Ithildir** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@Ithildir when I go to liferay-portal/modules/sdk/project-templates and run:

$ ../../../gradlew uploadArchives -Dbuild.exclude.dirs=sdk/project-templates/project-templates

I get this failure:

```
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/brian/dev/projects/github/liferay-portal/modules/sdk/project-templates/project-templates-fragment/build.gradle' line: 3

* What went wrong:
A problem occurred evaluating project ':sdk:project-templates:project-templates-fragment'.
> Project with path ':sdk:project-templates:project-templates' could not be found in project ':sdk:project-templates:project-templates-fragment'.
```

Can you fix the script so I can do a mass upload? Merged. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f04926429e...67bdaec849

**Comment by Ithildir** [comment]
I sent a fix at https://github.com/brianchandotcom/liferay-portal/pull/53766.

**Pull request closed without merging**
