### PR TITLE
LPS-74544

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:test

**Comment by petershin** [comment]
@hhuijser - Sent pulls to update the subrepos:

https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/619

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@hhuijser not merging.. this pull breaks some JSPs. See start.jsp 

https://github.com/brianchandotcom/liferay-portal/pull/53952/commits/cef343095ab3ee98d6059622bb650e89f12ee14f

and how it removed an if check and broke logic.

**Pull request closed without merging**
