### PR TITLE
LPS-73016 showing error message for missing asset category

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brandizzi** [comment]
ci:retest

On Mon, Nov 6, 2017 at 5:08 PM, Adam Brandizzi <adam.brandizzi@liferay.com>
wrote:

> ci:reopen
>



-- 
Adam Victor Nazareth Brandizzi
Software Engineer

Liferay Inc.
Enterprise. Open Source. For Life
www.liferay.com

**Comment by linolaoj** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@kiyoshilee @pyoo47

see

```
Please upgrade to at least MySQL 5.6.4. The portal no longer supports older versions of MySQL.
    [junit] junit.framework.AssertionFailedError: 
    [junit] Please upgrade to at least MySQL 5.6.4. The portal no longer supports older versions of MySQL.
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest.scanXMLLogFile(PortalLogAssertorTest.java:168)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:100)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:90)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2670)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2742)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXMLLog(PortalLogAssertorTest.java:88)
    [junit] 

```

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/07093a53b3...48e66d1ef0

**Comment by kiyoshilee** [comment]
@brianchandotcom we're in the process of taking care of the MySQL issue. That specific slave has already been taken offline.

**Pull request closed without merging**
