### PR TITLE
LPS-78192

### PR DESCRIPTION
**Pull request by noahsherrillwork**
/cc @drewbrokke @pei-jung @willnewbury

### CODE REVIEW

**Comment by noahsherrillwork** [comment]
ci:test

**Comment by willnewbury** [comment]
I sent the wrong branch yesterday. Just made https://github.com/brianchandotcom/liferay-portal/pull/55604, which duplicates the differences made in this pull

**Comment by noahsherrillwork** [comment]
I will close this one then.

**Comment by noahsherrillwork** [comment]
ci:stop

**Pull request closed without merging**
