### PR TITLE
LPS-68168 Back button is missing when the search input is empty

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-68168](https://issues.liferay.com/browse/LPS-68168).<br><br>/cc @pei-jung @alee8888 @jorgeferrer

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:stop (Due to broken distribution node)

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
