### PR TITLE
LPS-79389 Not used

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @jpince

**Comment by jkappler** [comment]
ci:test

**Comment by jkappler** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@jkappler how are you finding these unused things? Via Eclipse or PMD?

**Comment by jkappler** [comment]
Hi @brianchandotcom. Normally I would find it through pmd, but in this case, @jpince told me about the issue

**Comment by jpince** [comment]
@brianchandotcom PMD was failing at head, so I reported the issue to Jürgen.

**Pull request closed without merging**
