### PR TITLE
LPS-55026 Fix tests

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
I think we can ignore those broken tests... I'm merging this in.

**Comment by marcellustavares** [comment]
k, thanks @brianchandotcom, I had to do a very weird dependency check on CheckBookingsMessageListener but I've talked to @mhan810 and he'll try to improve the SchedulerEntry registration later on.

**Comment by mhan810** [comment]
Hey @marcellustavares the listener should be depending on com.liferay.portal.model.Portlet.  I think you missed my last chat mesg :)

**Comment by marcellustavares** [comment]
I've changed that on this pull @mhan810 :) It's working now.

**Comment by marcellustavares** [comment]
The problem is that is very hard rt now to track the dependencies the SchedulerEntry depends on, we need to debug the code to actually check them :P

PortletApp is one of them, but I had to set the CalendarServiceConfigurator as dependency to make sure the tables were created.

**Comment by brianchandotcom** [comment]
Please resend on top of https://github.com/marcellustavares/liferay-portal/pull/584

1.) PortletPropsKeys is wrong (even Marketplace util is wrong, please fix that too)

2.) ActionKeys is wrong (see other portlets)

3.) Same with WebKeys (we should no longer extend, and please rename)

Thx

**Pull request closed without merging**
