### PR TITLE
LPS-98032 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LPS-98032

master-private: https://github.com/brianchandotcom/liferay-portal-ee/pull/27117

### CODE REVIEW

**Comment by john-co** [comment]
reopening https://github.com/brianchandotcom/liferay-portal/pull/79699

Test failures were unrelated. :heavy_check_mark:

**Comment by jbalsas** [comment]
Just rebased this and resent to https://github.com/brianchandotcom/liferay-portal/pull/79731 to give us one more chance today 😉

**Comment by jbalsas** [comment]
master-private still looks mergeable at https://github.com/brianchandotcom/liferay-portal-ee/pull/27117

**Comment by jbalsas** [comment]
ci:close

**Pull request closed without merging**
