### PR TITLE
LPS-92053 Regenerate

### PR DESCRIPTION
**Pull request by inacionery**
/cc @marcelabc

### CODE REVIEW

**Comment by jpince** [comment]
ci:close @inacionery the tests you are adding are broken...
example:
```
DocumentFolderResourceTest.testGetDocumentFolderDocumentFoldersPageWithSortInteger
java.lang.AssertionError: {"creator": {"familyName": "Test", "givenName": "Test", "id": 20130, "name": "Test Test", "profileURL": "/web/test"}, "dateCreated": "2019-05-30T14:57:31Z", "dateModified": "2019-05-30T14:57:31Z", "description": "H2dup6r2", "id": 41239, "name": "5Cu4yz7d", "numberOfDocumentFolders": 0, "numberOfDocuments": 0, "siteId": 41228} does not equal {"creator": {"familyName": "Test", "givenName": "Test", "id": 20130, "name": "Test Test", "profileURL": "/web/test"}, "dateCreated": "2019-05-30T14:57:31Z", "dateModified": "2019-05-30T14:57:31Z", "description": "QXZu1DbC", "id": 41235, "name": "NNsEYmRO", "numberOfDocumentFolders": 0, "numberOfDocuments": 0, "siteId": 41228}
```

**Comment by inacionery** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/73918

**Comment by jpince** [comment]
@inacionery thanks for investigating and resending. I try not to be very strict on what I close, but we're trying hard to make the GA1 build and need the upstream results to be as clean as possible. Thanks for understanding!

**Comment by inacionery** [comment]
No worries! Thanks!

**Pull request closed without merging**
