### PR TITLE
LRQA-46662

### PR DESCRIPTION
**Pull request by petershin**
@john-co

### CODE REVIEW

**Comment by jpince** [comment]
@lawrence-lee not sure if project-templates failure is related

**Comment by lawrence-lee** [comment]
> @lawrence-lee not sure if project-templates failure is related

Yes, its related to this particular PR. However, I think its just a test fix. I'll work on this and can send it over to Peter once its done.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9dc1a6cbe1...e9c7f08307

**Comment by lawrence-lee** [comment]
@petershin @jpince, So i'm not sure why in this instance CI didn't resolve mavenLocal to `.m2-tmp` instead of `.m2` The other tests seem to work fine. 

One thing that is weird is that this particular artifact has already been published, so I'm not sure if this has already been merged and the problem will just go away. 

But i've also made some improvements to the test here: https://github.com/petershin/liferay-portal/pull/412

**Pull request closed without merging**
