### PR TITLE
Auto Deployment: make sure only one auto deployer is executed

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by migue** [comment]
ci:retest

On 9 February 2016 at 09:05, Liferay Continuous Integration <
notifications@github.com> wrote:

> Some tests FAILED!
>
> Build Time: 45 minutes 4 seconds
> Base Branch:
>
> Branch Name: master
> <https://github.com/liferay/liferay-portal/tree/master>
> Branch GIT ID: 27100e316329b4454dc134705bdb3b88a87af2f7
> <https://github.com/liferay/liferay-portal/commit/27100e316329b4454dc134705bdb3b88a87af2f7>
> Job Summary:
>
>    - *test-portal-acceptance-pullrequest(master)
>    <https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest(master)/819/>*
>    - test-portal-acceptance-pullrequest-batch(master)/compile-jsp
>    <https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/26679/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat-hypersonic/0
>    <https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/22826/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat-mysql/0
>    <https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/18146/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat-mysql/1
>    <https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/26185/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat-mysql/2
>    <https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/21826/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat-mysql/3
>    <https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/14531/>
>    - *test-portal-acceptance-pullrequest-batch(master)/functional-tomcat-mysql/4
>    <https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/15903/>*
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat-mysql/5
>    <https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/15918/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat-mysql/6
>    <https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/14995/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat-mysql/7
>    <https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/15792/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat-mysql/8
>    <https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/23012/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/integration-hypersonic
>    <https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/18692/>
>    - test-portal-acceptance-pullrequest-batch(master)/integration-mysql
>    <https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/14286/>
>    -
>    test-portal-acceptance-pullrequest-batch(master)/integration-postgresql
>    <https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/26548/>
>    - *test-portal-acceptance-pullrequest-batch(master)/modules-integration-hypersonic
>    <https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/22756/>*
>    -
>    test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql
>    <https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/14397/>
>    - *test-portal-acceptance-pullrequest-batch(master)/modules-integration-postgresql
>    <https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/22719/>*
>    - test-portal-acceptance-pullrequest-batch(master)/modules-unit
>    <https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/26680/>
>    - test-portal-acceptance-pullrequest-batch(master)/plugins-compile
>    <https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/22828/>
>    - test-portal-acceptance-pullrequest-batch(master)/portal-web
>    <https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/22827/>
>    - test-portal-acceptance-pullrequest-batch(master)/ruby-sass-compiler
>    <https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/22829/>
>    - test-portal-acceptance-pullrequest-batch(master)/service-builder
>    <https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/18693/>
>    - test-portal-acceptance-pullrequest-batch(master)/tck
>    <https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/26549/>
>    - test-portal-acceptance-pullrequest-batch(master)/unit
>    <https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/14287/>
>    - test-portal-acceptance-pullrequest-source(master)
>    <https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-source(master)/994/>
>
> For more details click here
> <https://test-1-12.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/819/jenkins-report.html>
> .
> ------------------------------
> Failed Jobs:
>
>    1. test-portal-acceptance-pullrequest(master)
>    <https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest(master)/819/> Job
>    Results:
>
>    22 Jobs Passed.
>    4 Jobs Failed.
>
>    Completed with the status of FAILURE.
>
>    2.
>    test-portal-acceptance-pullrequest-batch(master)/functional-tomcat-mysql/4
>    <https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/15903/> Job
>    Results:
>
>    46 Tests Passed.
>    2 Tests Failed.
>    1. PoshiRunner.test[Calendar#DeleteEventRegular]
>       <https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=Calendar%23DeleteEventRegular,label_exp=!master/15903//testReport/com.liferay.poshi.runner/PoshiRunner/test_Calendar_DeleteEventRegular_>
>       - Poshi Report
>       <https://test-1-12.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/819/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=Calendar%23DeleteEventRegular,label_exp=!master/functional-tomcat-mysql/4/index.html>
>       - Poshi Summary
>       <https://test-1-12.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/819/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=Calendar%23DeleteEventRegular,label_exp=!master/functional-tomcat-mysql/4/summary.html>
>       - Console Output
>       <https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=Cal%20endar%23%20DeleteEventRegular,label_exp=!master/15903//console>
>       2. PoshiRunner.test[Calendar#SearchForOtherCalendars]
>       <https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=Calendar%23SearchForOtherCalendars,label_exp=!master/15903//testReport/com.liferay.poshi.runner/PoshiRunner/test_Calendar_SearchForOtherCalendars_>
>       - Poshi Report
>       <https://test-1-12.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/819/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=Calendar%23SearchForOtherCalendars,label_exp=!master/functional-tomcat-mysql/4/index.html>
>       - Poshi Summary
>       <https://test-1-12.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/819/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=Calendar%23SearchForOtherCalendars,label_exp=!master/functional-tomcat-mysql/4/summary.html>
>       - Console Output
>       <https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch%28ma%20ster%29/%20AXIS_VARIABLE=Calendar%23SearchForOtherCalendars,label_exp=!master/15903//console>
>    3.
>    test-portal-acceptance-pullrequest-batch(master)/modules-integration-hypersonic
>    <https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/22756/> Job
>    Results:
>
>    4263 Tests Passed.
>    2 Tests Failed.
>    1.
>       DLFileEntryTypeStagedModelDataHandlerTest.testCleanStagedModelDataHandler
>       <https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=11,label_exp=!master/22756//testReport/com.liferay.document.library.lar.test/DLFileEntryTypeStagedModelDataHandlerTest/testCleanStagedModelDataHandler>
>       2. PortalLogAssertorTest.testScanXMLLog
>       <https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=11,label_exp=!master/22756//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXMLLog>
>    4.
>    test-portal-acceptance-pullrequest-batch(master)/modules-integration-postgresql
>    <https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/22719/> Job
>    Results:
>
>    4262 Tests Passed.
>    3 Tests Failed.
>    1.
>       DLFileEntryTypeStagedModelDataHandlerTest.testCleanStagedModelDataHandler
>       <https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=11,label_exp=!master/22719//testReport/com.liferay.document.library.lar.test/DLFileEntryTypeStagedModelDataHandlerTest/testCleanStagedModelDataHandler>
>       2.
>       DLFileEntryTypeStagedModelDataHandlerTest.testStagedModelDataHandler
>       <https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=11,label_exp=!master/22719//testReport/com.liferay.document.library.lar.test/DLFileEntryTypeStagedModelDataHandlerTest/testStagedModelDataHandler>
>       3. PortalLogAssertorTest.testScanXMLLog
>       <https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=11,label_exp=!master/22719//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXMLLog>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/35757#issuecomment-181753231>
> .
>



-- 
Un saludo,

Migue

http://migue.github.io

**Comment by mdelapenya** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e4d957b5e8...f83cb62da4

**Comment by brianchandotcom** [comment]
Nice job on this very important refactor @mdelapenya 

See upstream for my mainly cosmetic changes.

**Pull request closed without merging**
