### PR TITLE
LPS-104540 | master

### PR DESCRIPTION
**Pull request by jpince**
https://issues.liferay.com/browse/LPS-104540

This is an update for LPS-104540.

@petershin I also updated the lp.version properties, can you please validate? I'm not sure what they do or why they weren't updated during your original set of changes, but seemed like they needed to say 7.3 :)

### CODE REVIEW

**Comment by petershin** [comment]
@jpince - Taking a look

**Comment by petershin** [comment]
@jpince - Running the `ci:test` suite to see if there's anything else that needs to be updated

**Comment by petershin** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9bd43b1e6e...51bafe06b8

**Comment by jpince** [comment]
@petershin I don't see any obvious or mass failures so I think it should be ok

**Pull request closed without merging**
