### PR TITLE
LPS-90212 Improve accessibility for screen readers

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
@brianchandotcom @john-co

This PR's tests depends of:
https://github.com/brianchandotcom/liferay-portal/pull/69249

**Comment by antonio-ortega** [comment]
ci:reopen

**Comment by antonio-ortega** [comment]
brianchandotcom#69368

**Comment by antonio-ortega** [comment]
ci:close

**Pull request closed without merging**
