### PR TITLE
master-sc-363

### PR DESCRIPTION
**Pull request by sharonchoi**
https://issues.liferay.com/browse/LRQA-21103
https://issues.liferay.com/browse/LRQA-21105

@brianchandotcom this pr should fix the intermittent failures on the pr-tester for this test  PGWiki#AddWikiFrontPageChildPageFormatHTML

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Very nice @austinchiang @sharonchoi !

**Comment by brianchandotcom** [comment]
@sergiogonzalez it was a poshi bug in wiki that's now fixed

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bfeb401864...7f8a841915

**Comment by sergiogonzalez** [comment]
Thanks @austinchiang @sharonchoi for fixing this :)

**Pull request closed without merging**
