### PR TITLE
LPS-64569 fix tests

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
Aside from a source format issue, which is fixed at https://github.com/brianchandotcom/liferay-portal/pull/38159/commits/758463531efd135eb9fdfe165e93d222aedfb82f the rest of the issues don't appear related to the changes.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by sharonchoi** [comment]
Test failed because page didn't finish loading before it tried to assert the next element in `<execute macro="User#editDetailsViaMyAccount">`

@evannagayama, should we add a pause/waitForElementPresent for this macro?

**Comment by evannagayama** [comment]
Thanks Sharon, this should be a fluke. I'll retest it and look into the issue.

**Comment by evannagayama** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@rotty3000 I merged this in, but for ServletContextHelperRegistrationImpl.java, the constructor and close methods seem inconsistent.

```
		_servletContextHelperServiceRegistration = createServletContextHelper(
			contextPath);

		_servletContextListenerServiceRegistration =
			createServletContextListener();

		registerServletContext();

```

vs

```
		_servletContextRegistration.unregister();

		_servletContextHelperServiceRegistration.unregister();

		_servletContextListenerServiceRegistration.unregister();
```

Can you go through those and either open / close them the same way, or the inverse way. It seems a bit random right now, and if there is some logic to it, it's not immediately obvious.

Thx @rotty3000

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8e651df773...45d9c2e974

**Comment by rotty3000** [comment]
There is logic to the order.

Please don't change it.

On Mon, Mar 28, 2016 at 10:19 PM, Brian Chan <notifications@github.com>
wrote:

> Closed #38159
> <https://github.com/brianchandotcom/liferay-portal/pull/38159>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/38159#event-606031791>
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Pull request closed without merging**
