### PR TITLE
LPS-73569

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@pyoo47 I"ve seen this error a few times now.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8a4fe4c18c...4a5f652c89

**Comment by pyoo47** [comment]
@brianchandotcom I think mirrors is having a problem providing the static json files that is used for the unit test. The load balancer code is unable to receive the json data for all of the masters so it gives up and picks the best choice out of what it was able to get (which is what it's supposed to do) but that will frequently mean that it picks a different master than what is expected.

```
     [exec]     Asserting sample test-1: Blacklist: 
     [exec]     Retrying http://mirrors-no-cache.lax.liferay.com/github.com/liferay/liferay-jenkins-results-parser-samples-ee/1/LoadBalancerUtilTest/test-1/test-1-6/computer/api/json%5Bqt%5Dtree=computer%5BdisplayName,idle,offline%5D in 5 seconds
     [exec]     Retrying http://mirrors-no-cache.lax.liferay.com/github.com/liferay/liferay-jenkins-results-parser-samples-ee/1/LoadBalancerUtilTest/test-1/test-1-7/computer/api/json%5Bqt%5Dtree=computer%5BdisplayName,idle,offline%5D in 5 seconds
     [exec]     Retrying http://mirrors-no-cache.lax.liferay.com/github.com/liferay/liferay-jenkins-results-parser-samples-ee/1/LoadBalancerUtilTest/test-1/test-1-8/computer/api/json%5Bqt%5Dtree=computer%5BdisplayName,idle,offline%5D in 5 seconds
     [exec]     Retrying http://mirrors-no-cache.lax.liferay.com/github.com/liferay/liferay-jenkins-results-parser-samples-ee/1/LoadBalancerUtilTest/test-1/test-1-9/computer/api/json%5Bqt%5Dtree=computer%5BdisplayName,idle,offline%5D in 5 seconds
     [exec]     Retrying http://mirrors-no-cache.lax.liferay.com/github.com/liferay/liferay-jenkins-results-parser-samples-ee/1/LoadBalancerUtilTest/test-1/test-1-11/computer/api/json%5Bqt%5Dtree=computer%5BdisplayName,idle,offline%5D in 5 seconds
     [exec]     Retrying http://mirrors-no-cache.lax.liferay.com/github.com/liferay/liferay-jenkins-results-parser-samples-ee/1/LoadBalancerUtilTest/test-1/test-1-17/computer/api/json%5Bqt%5Dtree=computer%5BdisplayName,idle,offline%5D in 5 secondsRetrying http://mirrors-no-cache.lax.liferay.com/github.com/liferay/liferay-jenkins-results-parser-samples-ee/1/LoadBalancerUtilTest/test-1/test-1-14/computer/api/json%5Bqt%5Dtree=computer%5BdisplayName,idle,offline%5D in 5 seconds
     [exec] 
     [exec]     Retrying http://mirrors-no-cache.lax.liferay.com/github.com/liferay/liferay-jenkins-results-parser-samples-ee/1/LoadBalancerUtilTest/test-1/test-1-12/computer/api/json%5Bqt%5Dtree=computer%5BdisplayName,idle,offline%5D in 5 seconds
     [exec]     Retrying http://mirrors-no-cache.lax.liferay.com/github.com/liferay/liferay-jenkins-results-parser-samples-ee/1/LoadBalancerUtilTest/test-1/test-1-15/computer/api/json%5Bqt%5Dtree=computer%5BdisplayName,idle,offline%5D in 5 seconds
     [exec]     Retrying http://mirrors-no-cache.lax.liferay.com/github.com/liferay/liferay-jenkins-results-parser-samples-ee/1/LoadBalancerUtilTest/test-1/test-1-1/queue/api/json%5Bqt%5Dtree=items%5Btask%5Bname%5D,why%5D in 5 seconds
     [exec]     Retrying http://mirrors-no-cache.lax.liferay.com/github.com/liferay/liferay-jenkins-results-parser-samples-ee/1/LoadBalancerUtilTest/test-1/test-1-18/computer/api/json%5Bqt%5Dtree=computer%5BdisplayName,idle,offline%5D in 5 seconds
     [exec]     Retrying http://mirrors-no-cache.lax.liferay.com/github.com/liferay/liferay-jenkins-results-parser-samples-ee/1/LoadBalancerUtilTest/test-1/test-1-10/computer/api/json%5Bqt%5Dtree=computer%5BdisplayName,idle,offline%5D in 5 seconds
     [exec]     Retrying http://mirrors-no-cache.lax.liferay.com/github.com/liferay/liferay-jenkins-results-parser-samples-ee/1/LoadBalancerUtilTest/test-1/test-1-19/computer/api/json%5Bqt%5Dtree=computer%5BdisplayName,idle,offline%5D in 5 seconds
     [exec]     Retrying http://mirrors-no-cache.lax.liferay.com/github.com/liferay/liferay-jenkins-results-parser-samples-ee/1/LoadBalancerUtilTest/test-1/test-1-2/queue/api/json%5Bqt%5Dtree=items%5Btask%5Bname%5D,why%5D in 5 seconds
     [exec]     test-1-20 : 78
     [exec]     test-1-5 : 50
     [exec]     test-1-3 : 36
     [exec]     test-1-4 : 33
     [exec]     test-1-16 : 23
     [exec] 
     [exec]     Most available master test-1-20 has 78 available slaves.
     [exec]     Got most available master URL in 10 seconds 31 ms
     [exec]      FAILED
     [exec] 
     [exec]     Actual message: 
     [exec]     http://test-1-20
     [exec] 
     [exec]     Expected message: 
     [exec]     http://test-1-14
```

**Pull request closed without merging**
