### PR TITLE
#Ping LPS-56703 Blogs Tests

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
cc/ @adolfopa @robertoDiaz

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/df4706276e...61deffd6ce

**Comment by brianchandotcom** [comment]
See 61deffd6ceab7342e5f61cb934f4ccab9b4972cb

**Pull request closed without merging**
