### PR TITLE
LPS-76089 Full Page Application should be instantiable

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LPS-76089

cc @ealonso @jkappler 

tested here: https://github.com/anthony-chu/liferay-portal/pull/370

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:test

**Comment by ealonso** [comment]
👏 👏 👏 👏

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/629c687dfb...c7edba9858

**Comment by brianchandotcom** [comment]
@ealonso @jkappler minor changes in upstream.

**Pull request closed without merging**
