### PR TITLE
LPS-160981 Validate pattern redirection configuration

### PR DESCRIPTION
**Pull request by adolfopa**
After enabling the feature flag and changing the config. annotation so that it generates the UI you'll get something similar to this:
image
Each entry is a pair of regex/replacement separated by blanks. The second example shows how to capture part of a friendly url and use it in the replacement ($1 will inject the value captured by group #1); for example "/abc/123" will be transformed in "/xyz/123".

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a622b83976...5d3b18ae3f

**Comment by brianchandotcom** [comment]
Thank you @adolfopa !!!

See changes in my origin.

**Comment by jverweijL** [comment]
Why is this under site-settings and not under 'Redirection'? @adolfopa

**Comment by adolfopa** [comment]
@jverweijL That's temporary; we'll move the configuration to the Redirections app in a future story. Adding it to the site settings made it possible to deliver the feature faster.

**Pull request closed without merging**
