### PR TITLE
OAUTH2-122 basics

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Hi Brian. I've tried to identify suitable existing patterns for the stuff you mentioned https://github.com/brianchandotcom/liferay-portal/pull/59292#issuecomment-393248024

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test

**Comment by topolik** [comment]
ci:reopen Failing on KaleoVersionDefinition missing resources

**Comment by brianchandotcom** [comment]
Hey @stian-sigvartsen I"m not sure why ClientProfile is in *.constants.

Usually, that package is reserved for *Constants classes.

also, will we have a *DisplayContext? It's strange to have a ModelHelper that is in a display.context.util. I assume that helper is for the DisplayContext object that isn't sent yet?

Please resend. Thx.

**Comment by stian-sigvartsen** [comment]
Thanks @brianchandotcom . ClientProfile is an enum so it is a constant? It exists so clients know what clientProfileIds refer to in SB service parameters.

The AuthorizationModelHelper is shared between two DisplayContexts as you suspected: 

- **OAuth2ConnectedApplicationsPortletDisplayContext** (in this pull)
- **AssignScopesModel** (which I will rename to AssignScopesDisplayContext following our comments on the other pull https://github.com/brianchandotcom/liferay-portal/pull/59292#issuecomment-393248024 

The role of the class is to transform a logical model on the backend into something that is renderable. This includes translating scope names and providing various set operations with other AuthorizationModelHelpers (add/subtract).

I'm not too happy with this name change from AuthorizationModel to AuthorizationModelHelper, because we will have display context methods like:

> public Map<AuthorizationModelHelper, Relations> getAuthorizationModelHelperRelationsMap(String applicationName)

I would much prefer a noun, but existing patterns (like DL) use Helper suffix for something similar.

Please can you advise what changes you want?

/cc @topolik @csierra

**Pull request closed without merging**
