### PR TITLE
LPS-131321 JSON Storage

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/357058950c...48d4fa211e

**Comment by brianchandotcom** [comment]
Very nice @Preston-Crary this was quite beautiful

I only made minor changes

**Comment by Preston-Crary** [comment]
Please see https://github.com/Preston-Crary/liferay-portal/pull/1396 for the follow up for jsonassert.

**Pull request closed without merging**
