### PR TITLE
master-sc-455

### PR DESCRIPTION
**Pull request by sharonchoi**
https://issues.liferay.com/browse/LRQA-22155
https://issues.liferay.com/browse/LPS-63117

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1b18eebfa1...1f5fc4c6c5

**Comment by brianchandotcom** [comment]
@sharonchoi I assume this is a fluke test that is broken, please dig in with @brianchiu

thx

**Comment by sharonchoi** [comment]
@brianchandotcom cc@brianchiu
Test should be fixed by this incoming pr: https://github.com/brianchandotcom/liferay-portal/pull/36125

**Comment by brianchiu** [comment]
@brianchandotcom 
Yep. This is a fluke. However the cause is something that many tests use (so it just manifested itself in this particular test). The fix will fix it for all tests.

**Pull request closed without merging**
