### PR TITLE
LPS-108286 Revert "LPS-108206 Remove bundler loaders from dynamic-data-mapping-form-field-type package.json"

### PR DESCRIPTION
**Pull request by natocesarrego**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@wincent fyi @natocesarrego please communicate with @wincent since he did this in 01cfbadfe2ff066638e24b11465c1206a3978590

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by natocesarrego** [comment]
Hey @brianchandotcom,

Before send you the pull request, I sent a message through Slack to @wincent and @jbalsas. 🙂 

Thanks a lot!

**Comment by wincent** [comment]
Thanks for taking action @natocesarrego, but this seems like the wrong fix @natocesarrego.

1. It adds back two `devDependencies` to the runtime `dependencies`.
2. At least one of those `devDependencies` was already available transitively (see in the `yarn.lock` [here](https://github.com/liferay/liferay-portal/blob/17be2e5be2d8df7472ff586681c80bf0f533f800/modules/yarn.lock#L11095))  (somehow `liferay-npm-bundler-loader-style-loader` is not and we should add it to the  `liferay-npm-bundler-preset-liferay-dev`) — you should never have to add `devDependencies` in liferay-portal (and we have lints against it), and adding stuff to `dependencies` as a way of running around the lint is not acceptable.
3. The version ranges are stale (should be 2.17.0), which will cause duplication in the `yarn.lock` when somebody runs `yarn` in their local repo.
4. You've remove `leaflet` from the `yarn.lock`, which may break things in other ways.

On Monday let's redo this with the missing style-loader dep added back the proper way.

**Comment by wincent** [comment]
Had a couple of bundler bugs to get sorted in order to actually finalize this, but the follow-up is now at: https://github.com/brianchandotcom/liferay-portal/pull/84226

In short, we shouldn't need to use style-loader any more, and we have lints in place to stop loader dependencies from accidentally creeping back in.

**Comment by wincent** [comment]
Correction: right link is https://github.com/brianchandotcom/liferay-portal/pull/84626

**Pull request closed without merging**
