### PR TITLE
LPS-59737 Display a message to administrators letting them know that the portal is currently reindexing

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
Reviewed by: @juliocamarero :tada::tada:

**Comment by juliocamarero** [comment]
:+1:

**Comment by jkappler** [comment]
ci:retest

**Comment by jkappler** [comment]
ci:retest

**Comment by jkappler** [comment]
Will send to @evannagayama, since there were some changes in css classes

**Pull request closed without merging**
