### PR TITLE
LPS-56746 Missing alter table

### PR DESCRIPTION
**Pull request by matethurzo**
cc @sergiogonzalez

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/008c4c9c9d...dca222dba8

**Comment by brianchandotcom** [comment]
@matethurzo not sure why the test results were so inconsistent

In any case, I merged it in and sorted your statement in 8108187cdaac53b2a58e1764b58e3485d7da4206

**Pull request closed without merging**
