### PR TITLE
LPS-70392

### PR DESCRIPTION
**Pull request by lionah**

### CODE REVIEW

**Comment by lionah** [comment]
cc: @yuhai @migue

It looks like the check was present in most of the upgrade classes. I added it to the only one that is missing. This should cover our bases so that any combo of older Liferay Portal and Marketplace can successfully upgrade to the latest.

Thanks!

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianwulbern** [comment]
Poshi test quarantined here: https://github.com/brianchandotcom/liferay-portal/pull/46894

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f4bf457867...f62791e9fc

**Pull request closed without merging**
