### PR TITLE
LPS-96358 Enable and disable result rankings

### PR DESCRIPTION
**Pull request by BryanEngler**
✅ **ci:test:search - 48 out of 48 jobs passed** https://github.com/BryanEngler/liferay-portal/pull/438#issuecomment-553605909

Author(s): @oliv-yu @thektan
Reviewer(s): @BryanEngler
Cc: @arboliveira

---
*[Story] As a Search Admin, I want to enable and disable rankings*
https://issues.liferay.com/browse/LPS-96358

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/65b5c16c13...13a2203e2e

**Comment by brianchandotcom** [comment]
@oliv-yu @thektan I saw this twice:

```
		<portlet:param name="keywords" value="<%= rankingEntryDisplayContext.getKeywords() %>" />
		<portlet:param name="inactive" value="<%= String.valueOf(rankingEntryDisplayContext.getInactive()) %>" />
```

Where inactive was last after keywords. Was that on purpose? Curious. If not, seems like you had the order based on grouping, and then you sorted the rest.

```
		<portlet:param name="mvcRenderCommandName" value="editResultsRankingEntry" />
		<portlet:param name="redirect" value="<%= currentURL %>" />
		<portlet:param name="resultsRankingUid" value="<%= rankingEntryDisplayContext.getUid() %>" />
		<portlet:param name="aliases" value="<%= rankingEntryDisplayContext.getAliases() %>" />
		<portlet:param name="companyId" value="<%= String.valueOf(themeDisplay.getCompanyId()) %>" />
		<portlet:param name="keywords" value="<%= rankingEntryDisplayContext.getKeywords() %>" />
		<portlet:param name="inactive" value="<%= String.valueOf(rankingEntryDisplayContext.getInactive()) %>" />
```

So not sure if inactive should go before or after keywords. Please send a follow up if it makes sense.

@BryanEngler

**Comment by thektan** [comment]
@brianchandotcom Thanks for catching that. `inactive` should be before `keywords` for correct alphabetical order. I'll send a follow-up.

cc @oliv-yu @BryanEngler

**Pull request closed without merging**
