### PR TITLE
LPS-78373 Fixing sort

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
@patriciajeanperez you might want to check this one too. Thanks!

**Comment by 4lejandrito** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/42a22a9270...f64dfbbf75

**Comment by brianchandotcom** [comment]
@4lejandrito see f64dfbbf75208391f4d31922ac6fbec58a23f79a

**Pull request closed without merging**
