### PR TITLE
LPS-74838 SF

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:reopen

**Comment by rafaprax** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@IstvanD @rafaprax we rarely use "stringHere" for request or session attributes. Please use WebKeys and resend. Thx.

**Comment by rafaprax** [comment]
resent at https://github.com/brianchandotcom/liferay-portal/pull/53005

**Pull request closed without merging**
