### PR TITLE
LPS-186272 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
This is only for master.

https://issues.liferay.com/browse/LPS-186272

@veroglez

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/12333

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@vendeltoreki @veroglez @Tim-Cao 

This looks off

```
const MillerColumnsColumn = ({
	columnItems = [],
	columnsContainer,
	isPrivateLayoutsEnabled,
	items,
	namespace,
	onItemDrop,
	onItemStayHover,
	parent,
	rtl,
	isSiteTemplate,
}) => {
```

Can you also change

```
friendly-url-conflict-site-page=The friendly URL of this page is conflicting with a friendly URL of a page in the site template, from which this site was created.
friendly-url-conflict-site-template-page=The friendly URL of this site template page is conflicting with a friendly URL of a page in a site that was created from this template.

```

to

```
friendly-url-conflict-site-page=The friendly URL of this page conflicts with a friendly URL of a page in the site template that was used to create this site.
friendly-url-conflict-site-template-page=The friendly URL of this site template page conflicts with a friendly URL of a page in a site that was created with this template.
```

BUT, I don't like this wording because I have to read it 3x to understand what's going on. If you can, please please simplify this riddle.

**Pull request closed without merging**
