### PR TITLE
LPS-52743 Remove unused method

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
I made sure to merge in your pulls first today in case of conflicts.

I caught a few more typos of your name here 69d821ddf75232466a269f4db83f2c1cf5063b4f

Thx Iván.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/aceea52bd9...69d821ddf7

**Comment by brianchandotcom** [comment]
I mass changed Ivan to Iván in plugins too.

**Comment by izaera** [comment]
:+1:  I will try to send you today the last PR regarding this change. It will settle down all the DC thingie, at last :-).

**Pull request closed without merging**
