### PR TITLE
LPS-66324

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@hhuijser can we add a test for JavaClass? thx.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by hhuijser** [comment]
@brianchandotcom 

A lot of the logic in JavaClass is being tested through  the tests in JavaSourceProcessorTest.
I can add some extra testing for the part where it parses the java source to create the set of JavaTerms.

**Pull request closed without merging**
