### PR TITLE
LPS-161630 Cache and reuse jsql parsed results.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/557d3aebbf...63f84c6a90

**Comment by brianchandotcom** [comment]
@shuyangzhou shouldn't it be portal.properties for ct.sql.transformer.cache.size ? Also see my changes in c70ba837 and 50011586 Thx SZ

@david-truong I backported this to 7.3.x

**Comment by shuyangzhou** [comment]
@brianchandotcom it can be a portal property, but there should rarely be a reason to change it. I am making it not quite visibly configurable just in case some special cases that needs a large cache size. Do you want to make it formally configurable?

**Comment by brianchandotcom** [comment]
@shuyangzhou can you make it a portal.property (no need to even document it), but let's make it official.

**Pull request closed without merging**
