### PR TITLE
LPS-69729 Private databases for SQLTransformer

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:reopen

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/97e405db35...5033f0f454

**Comment by brianchandotcom** [comment]
@mdelapenya I only merged in the tests for the new stuff. Is there any way not to duplicate / cut and paste all the tests? Perhaps have the old classes instance the new ones and ensure they are the same.

Thx.

**Comment by mdelapenya** [comment]
Hey @brianchandotcom, although the tests seem exactly equals, they are not: these SQLTransformer tests are present to test the old code (we never had those tests in place!), and the SQLTransformerLogic tests are there to unit test the new functionality. They have same assertions but with different implementation.

My intention is to remove the old ones once we apply the new pattern.

**Pull request closed without merging**
