### PR TITLE
LPS-106492 Create PageDefinitionValidatorTest

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
//cc @ealonso

**Comment by ruben-pulido** [comment]
//cc @jkappler

**Comment by ruben-pulido** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@ruben-pulido please resend, compile error (we may need to have my upstream sync before sending this to me)

**Pull request closed without merging**
