### PR TITLE
LPS-75289 Test SF.

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:reopen

**Comment by jpince** [comment]
@brianchandotcom looks good from a functional test perspective.

**Comment by brianchandotcom** [comment]
@brandizzi @linolaoj instead of "Subject" "You have been invited." Unless those words have to be those words, please resend with RandomTestUtil.randomString().

Thx

**Comment by linolaoj** [comment]
@brianchandotcom, here it is https://github.com/brianchandotcom/liferay-portal/pull/52691
Thanks!

**Pull request closed without merging**
