### PR TITLE
LPS-159094 Patch Xalan

### PR DESCRIPTION
**Pull request by dantewang**
@brianchandotcom Resend as per https://github.com/brianchandotcom/liferay-portal/pull/122393#issuecomment-1232230156, I'm able to build the patched jar by running 'gradlew commitCache' using this PR. cc @shuyangzhou @tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:reopen

**Comment by dantewang** [comment]
@brianchandotcom And this patched jar is going to be used on 7.3.x and prior, so it's not applied to master.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c8233fb698...2da40b193d

**Comment by brianchandotcom** [comment]
@dantewang my bad, I forgot to publish the SDK patcher part first. All good now.

**Pull request closed without merging**
