### PR TITLE
LRQA-24055 Implement OSGI module handling macrodefs for Patcher job.

### PR DESCRIPTION
**Pull request by pyoo47**
Resend of https://github.com/brianchandotcom/liferay-portal/pull/40622

https://issues.liferay.com/browse/LRQA-24614

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by kevin-yen** [comment]
ci:retest

**Comment by kevin-yen** [comment]
@pyoo47 @brianchandotcom Some of the axis failed because of the temp map. I'm going to try and ci:retest again

**Comment by kevin-yen** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
I think the source build failed because the branch was too far behind. I've rebased it now. ci:retest

**Comment by kevin-yen** [comment]
@pyoo47 @brianchandotcom 
this pull can be closed
https://github.com/brianchandotcom/liferay-portal/pull/40979

**Pull request closed without merging**
