### PR TITLE
LPS-77654 SF

### PR DESCRIPTION
**Pull request by achaparro**
cc/@marianoalvarosaiz

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@petershin just the SF error left!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f2b8a9f942...a3385c741b

**Comment by brianchandotcom** [comment]
@achaparro minor updates in upstream. Fyi.

**Pull request closed without merging**
