### PR TITLE
LPS-57385 create individual scope resource for root resource when it doesn't exist

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
reviewed by @JorgeFerrer

/cc @topolik
/cc @rotty3000

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/19cb6f130c...f01b605235

**Comment by brianchandotcom** [comment]
@pavel-savinov good job renaming the variable so that it makes more sense.

**Pull request closed without merging**
