### PR TITLE
LPS-161817 - Child content page of a Site created from a Site Template cannot be viewed or edited

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-161817

@ruben-pulido 
@lfbesada

### CODE REVIEW

**Comment by ozysouza** [comment]
ci:reopen

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR, seems to be related to [LPS-158474](https://issues.liferay.com/browse/LPS-158474)
See liferay-echo#7560
:x: ci:test:stable - 23 out of 24 jobs passed
:x: ci:test:relevant - 127 out of 184 jobs passed in 1 hour 37 minutes

**Comment by brianchandotcom** [comment]
@ruben-pulido 

In the validate method, you have:


```
		else if (!draft) {

			// Layout cannot become a child of a layout that is not sortable
			// because it is linked to a layout set prototype

			Layout layout = layoutPersistence.fetchByG_P_L(
				groupId, privateLayout, layoutId);
			Layout parentLayout = layoutPersistence.findByG_P_L(
				groupId, privateLayout, parentLayoutId);

			if (((layout == null) ||
				 Validator.isNull(layout.getSourcePrototypeLayoutUuid())) &&
				!SitesUtil.isLayoutSortable(parentLayout)) {

				throw new LayoutParentLayoutIdException(
					LayoutParentLayoutIdException.NOT_SORTABLE);
			}
		}
```

See how layout can be null? But you get the value of 'layout' via:

```
		Layout layout = layoutPersistence.findByG_P_L(
			groupId, privateLayout, layoutId);

		layoutLocalServiceHelper.validate(
			groupId, privateLayout, layoutId, parentLayoutId, name, type,
			layoutLocalServiceHelper.isDraftLayout(
				layout.getClassNameId(), layout.getClassPK(), type),
```

Which means we now have a scenario that cannot exist.

The solution is to make:

public boolean isDraftLayout(long classNameId, long classPK, String type) {

a private method.

You already have

Layout layout = layoutPersistence.fetchByG_P_L(

in the validate method. Use it to get the classNameId and classPK that you're passing in.

Please resend. Thx.

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
