### PR TITLE
LPS-107508 removing UTF-8 BOM if present

### PR DESCRIPTION
**Pull request by brunofarache**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6fd38e0f0e...e30a57142e

**Comment by brianchandotcom** [comment]
@linolaoj test? Thx.

**Comment by linolaoj** [comment]
@brianchandotcom , I'll include a test. Thanks!

**Comment by linolaoj** [comment]
Here it is https://github.com/brianchandotcom/liferay-portal/pull/84944

**Pull request closed without merging**
