### PR TITLE
LPS-146432 Organization segments used in Experiences are not updated after organization creation

### PR DESCRIPTION
**Pull request by jkappler**
Motivation
=======
This PR solves this bug related to the Segments
[LPS-146432](https://issues.liferay.com/browse/146432)

Proposed Solution
========
The proposed solution consist in not adding the userId to the search context. This is because we will only retrieve those elements created by the user

### CODE REVIEW

**Comment by jkappler** [comment]
@cgoncas

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fa06131695...b52ae8a1e6

**Comment by brianchandotcom** [comment]
@jkappler see b52ae8a1e6de223a45f92d28676195b7bf300d10

**Comment by brianchandotcom** [comment]
@cgoncas see b52ae8a1e6de223a45f92d28676195b7bf300d10

**Pull request closed without merging**
