### PR TITLE
LPS-149390 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-149390

This is only for master.

@georgel-pop-lr
cc @ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/7560
❌ ci:test:stable - 29 out of 34 jobs passed
❌ ci:test:relevant - 29 out of 35 jobs passed in 1 hour 56 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8d21684d58...875ac026f6

**Comment by brianchandotcom** [comment]
@georgel-pop-lr @Tim-Cao we need a test for this.

@georgel-pop-lr should it be an integration test?

or @Tim-Cao poshi?

**Comment by georgel-pop-lr** [comment]
> @georgel-pop-lr @Tim-Cao we need a test for this.
> 
> @georgel-pop-lr should it be an integration test?
> 
> or @Tim-Cao poshi?

Hi @brianchandotcom,

I don't think an integration test would help here.

Not sure if @Tim-Cao thinks that a poshi could help.

Let me know your thoughts.

Regards.

**Pull request closed without merging**
