### PR TITLE
LPS-85783 Semantic versioning

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
cc @ealonso

**Comment by jpince** [comment]
@pavel-savinov you're welcome, thanks for resolving the issues.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f1dcc48850...dd7d3cd4bc

**Comment by brianchandotcom** [comment]
@pavel-savinov I'm curious, what was the fix? The 2 pulls look almost identical to me. Can you send it to me in an email? Thx.

**Pull request closed without merging**
