### PR TITLE
LPS-66853

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@brianchandotcom, I doubt anyone is using the useProperties option, but we might as well at least make sure it does what it is supposed to do.

**Comment by jpince** [comment]
@hhuijser SF threw this error: `java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Unable to format ../../../tools/servers/tcat/tcat-init.groovy`

@brianchandotcom might need to wait on this pull

**Comment by jpince** [comment]
@brianchandotcom nevermind, the SF error I referenced is in other pulls, I'll try to track down the source. This pull does not introduce a new failure and should be safe to merge.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d0051d7620...4ff467baa9

**Pull request closed without merging**
