### PR TITLE
 LPS-161019 Enable Account Administrators to edit basic user info for users who have valid email addresses

### PR DESCRIPTION
**Pull request by patriciajeanperez**
This is an update for [LPS-161019](https://issues.liferay.com/browse/LPS-161019).

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
thanks @drewbrokke 

This was awesome. You wrote this way better than I could have.

Can you make one change and rename "Email" to "EmailAddress" i.e. in

domainOrEmail
String email

Everywhere in this PR?

Please resend on top of https://github.com/drewbrokke/liferay-portal/pull/1391

Just append your new commits without rewriting history (not worth the effort)

Thx

**Comment by brianchandotcom** [comment]
@drewbrokke same for class names too, should be XyzEmailAddressAbc and not XyzEmailAbc

**Comment by brianchandotcom** [comment]
@drewbrokke also, domainName

git grep "String domainName"

vs.

domain

**Pull request closed without merging**
