### PR TITLE
Lps 87152

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by vicnate5** [comment]
@shuyangzhou @jcampoy Regression on this pull, Fragments test also failed at https://github.com/shuyangzhou/liferay-portal/pull/7031.

@brianchiu I am not familiar with this test, would there be any easy steps to reproduce this manually?

**Comment by brianchiu** [comment]
@vicnate5 Yes. The test is failing where it clicks on the plus button when editing a content page. For whatever reason the fragments sidebar is not opening. Functionally it's similar to the plus button that expands the add widget/content sidebar on widget pages, except for content pages, it expands the fragments sidebar so you can add fragments.

To reproduce:
1. Navigate to Build > Pages
1. Click (+) button > Public Page > Content Page
1. Enter name for page
1. Click "Save"
1. Click (+) button in upper right

This SHOULD expand the fragments sidebar. If you aren't able to reproduce, maybe the test is moving too quickly...

**Comment by vicnate5** [comment]
I will check and file a ticket.

**Comment by shuyangzhou** [comment]
Reverted at https://github.com/brianchandotcom/liferay-portal/pull/64975

**Pull request closed without merging**
