### PR TITLE
Lps 195588 merge common permission 9 28 1

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/397284de8a...29b79fad98

**Comment by brianchandotcom** [comment]
@julschong see 29b79fad9845f2c53c86d96a17f83dd85153b6f1

@ling-alan-huang please enforce 29b79fad9845f2c53c86d96a17f83dd85153b6f1

@shuyangzhou fyi

**Comment by ling-alan-huang** [comment]
SF task: https://liferay.atlassian.net/browse/LPS-199168

**Pull request closed without merging**
