### PR TITLE
Upgrade Process: stronger sharding migration

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by vicnate5** [comment]
Unrelated Calendar failures. Due to time of day. I am sending a fix for this today.

**Comment by vicnate5** [comment]
Fix sent https://github.com/brianchandotcom/liferay-portal/pull/39526

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fd2c970f8c...e640a1cd31

**Comment by brianchandotcom** [comment]
@mdelapenya please see my changes in upstream. Thx.

**Pull request closed without merging**
