### PR TITLE
LPS-85721 New service methods for user data sync does not handle optional values

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-85721](https://issues.liferay.com/browse/LPS-85721).<br><br>Hey Brian, here are the test results from my last test run: https://github.com/drewbrokke/liferay-portal/pull/621#issuecomment-428768857<br><br>/cc @pei-jung @stsquared99 @alee8888 @jpince

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test

**Comment by drewbrokke** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/de7c630cf3...ec86942785

**Comment by jpince** [comment]
@drewbrokke can the ignore be reverted? https://github.com/liferay/liferay-portal/commit/f0ed8f92a82c9643a671ace785bdc6ce7907a666

**Pull request closed without merging**
