### PR TITLE
LPS-65466 Publishing article with Image or Geolocation fields doesn't redirect navigation to Web Content Admin

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:retest

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by sharonchoi** [comment]
@evannagayama @kenjiheigel there are tests failing when adding a site template and a user, due to a duplicate site/user already there.

**Comment by brianchandotcom** [comment]
@sharonchoi I assume it's not related?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/306598753a...f748ce2be0

**Pull request closed without merging**
