### PR TITLE
LPS-62341 Predefined Data Definitions are missing

### PR DESCRIPTION
**Pull request by marcellustavares**
cc @mhan810

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@marcellustavares I think this pull has the wrong commits. The LPS is different and was merged in a different commit. Can you resend? Thx.

**Comment by marcellustavares** [comment]
Thanks @brianchandotcom, it was merged by a different pull I guess. We're good.

**Pull request closed without merging**
