### PR TITLE
LPS-66426 Semantic versioning

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1527496f33...721c77290f

**Comment by brianchandotcom** [comment]
@rafaprax please review my changes in upstream? Thx.

**Comment by rafaprax** [comment]
Ok @brianchandotcom , I will see now. Thx

**Pull request closed without merging**
