### PR TITLE
LPS-66649 Export Inactive users is not working

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-66649](https://issues.liferay.com/browse/LPS-66649).<br><br>/cc @pei-jung @jorgeferrer

### CODE REVIEW

**Comment by drewbrokke** [comment]
@brianchandotcom the SF error comes from liferay-ui.tld, which is not part of this pull.  Looks like the attribute definitions are not alphabetized (`onClick` is out of order).

See https://github.com/drewbrokke/liferay-portal/blob/LPS-66649/modules/apps/foundation/frontend-taglib/frontend-taglib/src/main/resources/META-INF/liferay-frontend.tld#L432-L447.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b2aa705fcd...7041185662

**Comment by brianchandotcom** [comment]
Thx @drewbrokke

**Comment by jpince** [comment]
@drewbrokke @brianchandotcom the SF issue was solved by https://github.com/brianchandotcom/liferay-portal/pull/41507

**Pull request closed without merging**
