### PR TITLE
Lpd 25633 jdbc default parameters 2

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@slnn @victorhcunha see https://github.com/brianchandotcom/liferay-portal/pull/153547/commits/1003b5faa4ceb576c27442364257d5cf70f01030 once this pull is in, you can remove all jdbc parameters from benchmark repo. We are constructing the jdbc url with our own default values during DataSource creation now.

**Comment by slnn** [comment]
OK, got it

**Comment by brianchandotcom** [comment]
@shuyangzhou see changes in my origin. Thx

**Comment by shuyangzhou** [comment]
Thanks @brianchandotcom !

@brunofalc please follow up to push for the hotfix to the customer.

**Comment by slnn** [comment]
Remove all jdbc parameters from benchmark repo in https://github.com/dantewang/liferay-benchmark-ee/pull/736

**Pull request closed without merging**
