### PR TITLE
master-sc-300

### PR DESCRIPTION
**Pull request by sharonchoi**
https://issues.liferay.com/browse/LRQA-20622
https://issues.liferay.com/browse/LRQA-20314
https://issues.liferay.com/browse/LRQA-20123
https://issues.liferay.com/browse/LRQA-20570
https://issues.liferay.com/browse/LRQA-20621
https://issues.liferay.com/browse/LRQA-20125
https://issues.liferay.com/browse/LRQA-20482

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
<p>The Pull Request Tester will be down until <strong>December 28, 2015 @ 5:00 PM PDT</strong>.</p>

<p>See this <a href="https://issues.liferay.com/browse/LRQA-18839">JIRA Ticket</a> for more information.</p>

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest @michaelhashimoto is there a VM down?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/82733ea3ac...bb2ec9731a

**Pull request closed without merging**
