### PR TITLE
LPS-111235

### PR DESCRIPTION
**Pull request by tinatian**
Hi Brian,

Missing commits from https://github.com/tinatian/liferay-portal/pull/1802.

Sorry for the trouble.

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:reopen

**Comment by tinatian** [comment]
FYI @shuyangzhou

**Comment by vicnate5** [comment]
@CarlosBrichete FYI fixes Segments backend test regression

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6ea6de1339...f07096fd13

**Comment by brianchandotcom** [comment]
@jesseyeh-liferay I was not able to backport this to 7.2.x for you.  I backported the other changes by @yxingwu for this same ticket but will need you to send me backports for this pull to 7.2.x and beyond.

Can you also add enforcement in modules/source-formatter.properties

See source.check.GradleDependencyArtifactsCheck.renameArtifacts

**Pull request closed without merging**
