### PR TITLE
LPS-76372

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/21b64ad555...c53de55128

**Comment by brianchandotcom** [comment]
@matethurzo wow, good job with this. I assume it's to help drop the imports to 1 min? That I saw on your Twitter account?

Anyways, I changed priority to double from long (see my comments). And good job on the new pattern.

**Comment by brianchandotcom** [comment]
@matethurzo actually, was it a new pattern? I found stuff similar to it, but not exactly it. Thx.

**Comment by matethurzo** [comment]
@brianchandotcom not only this makes it that fast, but a series of performance changes. I'm working on a second asset related and then more in the pipeline

**Pull request closed without merging**
