### PR TITLE
LPS-74454 Autogenerated Build Service

### PR DESCRIPTION
**Pull request by brandizzi**
cc @joshuacords @natocesarrego

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brandizzi** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6aea524198...1aa5aff84a

**Pull request closed without merging**
