### PR TITLE
LPS-76055 Baseline

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test

**Comment by robertoDiaz** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/99b1245bcf...1fe305e377

**Comment by brianchandotcom** [comment]
@sergiogonzalez @robertoDiaz please see my changes in upstream. Thx.

**Pull request closed without merging**
