### PR TITLE
LPS-103676 Don't process empty/null values

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
@ealonso

**Comment by jonathanmccann** [comment]
@jkappler @knchau 

I don't believe this works for friendly URLs. Prior to the change entering `home` or another valid friendly URL for the embedded page's URL would work properly but now it's being changed to `http://home` which does not resolve.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2d5ec53c9a...e283b3c19a

**Comment by brianchandotcom** [comment]
@jkappler should we pull this to its own util class? Lots of duplicate logic in this pull. Also, after reading comments by @jonathanmccann , I'm reverting this.

Please resend.

**Pull request closed without merging**
