### PR TITLE
LPS-85456 SF - Iterate through the list

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
@brianchiu Could you please take a look? I think it would be great to have functional tests for content pages in staging, they were broken and we found it out by chance :)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6b0d7604e4...967f9c6d08

**Comment by brianchiu** [comment]
@pavel-savinov 
Yup. As an FYI we now have a some functional tests for content pages with staging!

See: https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/tests/enduser/wcm/contentpages/ContentPagesWithStaging.testcase

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
@pavel-savinov 
We ended up finding this: https://issues.liferay.com/browse/LPS-85770. After reverting one of your commits (this one: https://github.com/liferay/liferay-portal/commit/3a255499ce3e828c311576e6e7cf792647d5405c) the bug went away. Could you take a look?

**Pull request closed without merging**
