### PR TITLE
LPS-72151

### PR DESCRIPTION
**Pull request by lionah**

### CODE REVIEW

**Comment by lionah** [comment]
ci:reopen

**Comment by lionah** [comment]
ci:retest

**Comment by lionah** [comment]
Retesting, errors appear to be some other sort of failure.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ce8632d59b...1f770b32e8

**Comment by brianchandotcom** [comment]
@lionah I made some tiny changes in upstream. Please review.

**Pull request closed without merging**
