### PR TITLE
LPS-58414 fix logic permission for panelApps and panelCategories

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @matethurzo I have applied this change to the staging and export/import apps.

cc @marcellustavares I have applied this to the workflow definition panel app.

let me know if you have any question.

thanks!!

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest I just fixed the unrelated jspc error

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/48387f5b87...f965b5a94e

**Pull request closed without merging**
