### PR TITLE
LPS-109256 Build lang

### PR DESCRIPTION
**Pull request by adolfopa**
@brianchandotcom Regarding the SF errors, see discussion at https://github.com/brianchandotcom/liferay-portal/pull/85396.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@adolfopa rebase, please resend.

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/85464

**Pull request closed without merging**
