### PR TITLE
[Read Inside] LPS-107487 Improve Page Layout Architecture

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @brianchandotcom!

This is a semi-heavy refactor of some basic layout structure motivated by:
- ChangeTracking needs to add a custom menu bar on top of the Control Menu (/cc @stsquared99 )
- Common visual glitches in the handling of stacked menus on top

It does include a breaking change that I'd consider mild since it could affect:
- [Very Unlikely] Customers with a custom Control Panel Theme
- [Unlikely] Customers with a Custom Sticky Bar added using the `*ControlMenuEntry` API 

I'd venture this is a good change that we want to get in sooner rather than later, so waiting for the 7.4 cycle wouldn't be desirable and I can't think of a way we can make it happen in a less disruptive way.

@ryanschuhler, could you verify if this could affect the web team and your ability to upgrade? I think that could be a good reality-check...

/cc @ealonso, @JorgeFerrer, @AngeloYoun, @david-truong

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
I checked the `relevant` failures and it looks like they're caused by a real issue in upstream that @jkappler is likely fixing with https://github.com/brianchandotcom/liferay-portal/pull/84115

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7e1212c21c...6bcf5da92e

**Comment by ryanschuhler** [comment]
@jbalsas I don't think these changes will effect us either, we don't have customizations for the control panel (maybe just a few styles that we should probably remove anyways)

**Pull request closed without merging**
