### PR TITLE
OAUTH2-157 Language keys & translations (support right to left languages) - rebased 2

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Resent brianchandotcom/liferay-portal/pull/60651

Hi Brian. This mainly the rebase of brianchandotcom/liferay-portal#60549
@topolik requested some minor changes to the translations, but nothing to do with sentence structure. Thanks!

It is needed for the release.

/cc @sez11a

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
@brianchandotcom This poshi test is related but to sensitive to change. It is reliant on a dynamic element which is relabeled here. I will review the test with QA on Monday. I don't think it is a reason to delay merging

**Comment by stian-sigvartsen** [comment]
Hi @brianchandotcom . This pull has been around for a while (rebased twice). Just wondering if there is anything we can do to progress it? I'm concerned that current translations render really badly: `"Translations1., Translation2."`

/cc @jpince

**Comment by joshchong** [comment]
ci:close

**Comment by stian-sigvartsen** [comment]
@brianchandotcom we will rebase with the Poshi test fix included

/cc @joshchong

**Comment by joshchong** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/60808

**Pull request closed without merging**
