### PR TITLE
LPS-56154 Add null check

### PR DESCRIPTION
**Pull request by matethurzo**
@sergiogonzalez this pull request addresses a problem in wiki that the page resource does not keep it's uuid between publication processes.

@akosthurzo made this fix so it will do so.

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Can you resend on top of https://github.com/akosthurzo/liferay-portal/pull/47

1.) Check Journal since it may have the same problem

2.) See my changes to WikiServiceUpgrade, is that OK?

3.) Rename UpgradePageResourceGroupId to UpgradeWikiPageResource

4.) In UpgradeWikiPageResource, can we avoid using "wpr" and other vars? If we have to use a var, please spell it out "wikiPageResource", otherwise, just reference the table name.

Thx

**Pull request closed without merging**
