### PR TITLE
 LRQA-49026,  LRQA-48614 | master

### PR DESCRIPTION
**Pull request by liulukiwi**
https://issues.liferay.com/browse/LRQA-48614
https://issues.liferay.com/browse/LRQA-49026

This is only for master, thanks!
cc @brianchiu

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a8ff14b7e4...97692e28c7

**Comment by jpince** [comment]
@liulukiwi please resolve SF error
```
     [java] 1: ./portal-web/test/functional/com/liferay/portalweb/macros/WebContentNavigator.macro expected:<...b Content Display";
     [java] []
     [java] 		if (isSet(portlet...> but was:<...b Content Display";
     [java] [		]
     [java] 		if (isSet(portlet...>
```

**Comment by liulukiwi** [comment]
HI @jpince, it closed when the sf fails, so I sent it in another pull https://github.com/brianchandotcom/liferay-portal/pull/73226, I don't think this pull will be merged.

**Comment by liulukiwi** [comment]
sent it here:
https://github.com/brianchandotcom/liferay-portal/pull/73282

**Comment by jpince** [comment]
No problem, I understand. Thanks!

**Pull request closed without merging**
