### PR TITLE
LPS-66403 As a Roles Admin, I would like to see one entity at a time in the assignment page and popup

### PR DESCRIPTION
**Pull request by alee8888**

### CODE REVIEW

**Comment by alee8888** [comment]
@drewbrokke @pei-jung @natecavanaugh 
There were no Poshi functional test fixes needed for LPS-66403.

**Comment by brianchandotcom** [comment]
@jasonpince @brianchiu is this good to merge?

**Comment by brianchiu** [comment]
@brianchandotcom 
Yes this is safe to merge. All the failures right now are caused by these two bugs:
https://issues.liferay.com/browse/LPS-66764 (Andre sent a revert for this)
https://issues.liferay.com/browse/LPS-66769 (We are not yet sure what causes this)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4d5aea819e...820ac8d440

**Pull request closed without merging**
