### PR TITLE
LPS-113767 Remove redirect from unpublish icon

### PR DESCRIPTION
**Pull request by rodrigocunhaa**

### CODE REVIEW

**Comment by rodrigocunhaa** [comment]
Manual forwarded from https://github.com/inacionery/liferay-portal/pull/674. Same reason as https://github.com/brianchandotcom/liferay-portal/pull/88624.

**Comment by rodrigocunhaa** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/31946c22da...5c0d1b3eb8

**Comment by brianchandotcom** [comment]
@rodrigocunhaa please talk to the Search team and have them fix it..

**Comment by brianchandotcom** [comment]
@rodrigocunhaa I'm only willing to take pulls from QA to bypass as an exception.. not as the norm... this is getting to become the norm at this point.. please talk to Search or suppress flaky tests

**Comment by brianchandotcom** [comment]
@inacionery see my comments above.

**Comment by rodrigocunhaa** [comment]
Hi @brianchandotcom, I'll ignore the test and let them know.

**Comment by arboliveira** [comment]
@inacionery @rodrigocunhaa Fix on the way! https://github.com/arboliveira/liferay-portal/pull/838 (PortalLogAssertorTest "no such index" is https://issues.liferay.com/browse/LPS-113354)

**Pull request closed without merging**
