### PR TITLE
LPS-109391 Fixing attribute name

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:relevant

Restarting test, there was a network outage last night affecting CI.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7a9a0c5e35...258b2a0dd9

**Comment by brianchandotcom** [comment]
@jorgeferrer fyi.

@ambrinchaudhary @4lejandrito I found a very bad bug.

First, I sorted this (and this is why I care about details): e556d93bdc5ce103fc7874717561fb5ca59626a8

But SF complained and undid my sort: 258b2a0dd92394cd9b447b667653bde9f855bb19 

So I left it as is and told Hugo to fix SF thinking it was a bug in SF.

But then Hugo told me this! 5d9d5a8c2351b321d1a1f8de4f2f0b03a103a509

And now SF works properly 63dd7ea3c0e56f5d28b8f8986cae36e888e0d5ab

But that means the JSP was never fetching the right object!

```
<%
RatingsEntry ratingsEntry = (RatingsEntry)request.getAttribute("liferay-ratings:ratings:ratingsEntry");
RatingsStats ratingsStats = (RatingsStats)request.getAttribute("liferay-ratings:ratings:ratingsStats");
%>
```

That was typed wrong. Just fyi so we pay more attention to details. Cut and paste please. Thank you.

@hhuijser fyi

**Comment by 4lejandrito** [comment]
Thanks a lot @brianchandotcom. 

Since this is a new taglib that we are not using anywhere yet we didn't test every case. 

We'll be more careful next time.

**Pull request closed without merging**
