### PR TITLE
Lps 52665

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a054cd7f41...73f8770ab4

**Comment by brianchandotcom** [comment]
unit test?

**Comment by shuyangzhou** [comment]
@jonathanmccann please create 2 unit tests, one checks setting PropsKeys.LIFERAY_LIB_PORTAL_DIR system property does affect the value of PropsValues.LIFERAY_LIB_PORTAL_DIR, another checks RubyExecutor.initRubyGems(ServletContext) is search the right location for ruby-gems.jar

**Pull request closed without merging**
