### PR TITLE
LPS-71810 Change method to protected

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:reopen

**Comment by ambrinchaudhary** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@ambrinchaudhary please rename


JSONObject buttonCfg to JSONObject buttonCfgJSONObject

Please sort jsonObject.put("xyz" where we can to make it alphabetical.

Please resend. Thx.

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
see [https://github.com/brianchandotcom/liferay-portal/pull/48507](url)

**Pull request closed without merging**
