### PR TITLE
7.0.x-qa-27714

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-27714

### CODE REVIEW

**Comment by brianwulbern** [comment]
@brianchandotcom I only saw the Auto SF failure on the results for 7.0.x, so didn't commit anything for it on master.

**Comment by brianchandotcom** [comment]
Merged. Thx for the comments. No idea who caused the stray auto SF... Can you trace (in case something else was badly backported). At the very least, find out who caused it? Could be someone is manually backporting instead of cherry picking. Thx.

**Comment by brianwulbern** [comment]
Looking into it.

**Comment by brianwulbern** [comment]
@brianchandotcom Caused here: https://issues.liferay.com/browse/LRQA-27934 (https://github.com/brianchiu/liferay-portal/pull/1498).  It was a one-line change, that's probably why she thought it can be done w/o a cherry-pick.  But here's a case-in-point for why not.  I'll remind her not to manually backport.

**Pull request closed without merging**
