### PR TITLE
OAUTH2-157 Resent without language key changes

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Resending brianchandotcom/liferay-portal/pull/60358 without language key changes

/cc @csierra @topolik

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/34e0cede6b...1e430dd618

**Comment by brianchandotcom** [comment]
@natecavanaugh @hhuijser fyi, the CSS here is very inconsistently formatted:

```
	.badge-item.global-scope-alias-reference {
		color: $grayTextColor;
	}
	.hidden {
		display: none;
	}
	.inline {
		display: inline-block;
	}
	.list-group .list-group-title {
		font-weight: normal;
	}
	.panel-header .form-group {
		margin-bottom: 0;
	}
	.sheet .panel-group .panel-body {
		margin-bottom: 0;
	}
}

.portlet-oauth2-provider-authorize {
	.consent {
		.panel-body {
			padding: 1.25rem 1.25rem;
		}
		.user-icon, .app-icon {
			display: inline-block;
			height: 80px;
			margin-bottom: 1.25rem;
			position: relative;
			width: 80px;
		}

		.user-icon {
```

Notice the inconsistent use of line brakes after .

Can you guys add this to SF to auto SF? Either to Java SF check @hhuijser or to JS SF check @natecavanaugh

**Comment by natecavanaugh** [comment]
@brianchandotcom @hhujiser, both the warning and auto fix is there for the JS tool, but there are some that are still not able to be autofixed yet. I'll manually fix those and send a pull as discussed :)

**Comment by stian-sigvartsen** [comment]
@brianchandotcom Two of those failures are genuine. One of them was introduced on master after OAUTH2-157 so was missed. I am working on fixing both.

**Pull request closed without merging**
