### PR TITLE
LPS-55874 Fix tests

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
Comment

**Comment by marcellustavares** [comment]
comment again

**Comment by jpince** [comment]
@marcellustavares your last two commits say they were made on Mar 31, 2017 (in the future). Not sure if that is causing a problem?

**Comment by marcellustavares** [comment]
ci:close

**Comment by marcellustavares** [comment]
ci:stop

**Pull request closed without merging**
