### PR TITLE
LPS 118468 LPS 116663

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
Hi @brianchandotcom, I merged https://github.com/liferay-lima/liferay-portal/pull/557 and https://github.com/liferay-lima/liferay-portal/pull/562 on this one. Everything is passing but they're failing with because of an issue with the email server. @jpince recommended me to send directly to you while they investigate the issue.

Thanks!

**Comment by jpince** [comment]
@4lejandrito "recommended" is a strong word. I gave it as an _option_ that _you_ chose :grinning: 

choice

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/065bb41cd6...1e617ac8d5

**Pull request closed without merging**
