### PR TITLE
LPS-57558 persist the state of the product menu (open/closed)

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
@brianchiu @brianwulbern this will now have the product menu closed by default and therefore it might break many test failures. can you please keep an eye on this pull? thanks!

**Comment by juliocamarero** [comment]
@brianchiu @brianwulbern it does fail because now the product menu is closed. Do you want me to send the pull to you instead?

**Comment by brianwulbern** [comment]
@brianchiu @juliocamarero 

I sent the test fix with your commit here: https://github.com/brianchiu/liferay-portal/pull/578.

**Comment by brianchandotcom** [comment]
@juliocamarero please resend after you have the test fix in the pull? Thx.

**Pull request closed without merging**
