### PR TITLE
LPS-132180

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
@brianchandotcom regarding your comment here: https://github.com/brianchandotcom/liferay-portal/pull/103578#issuecomment-867093236

Adding a new method that takes `PortletURL` is not going to help because of the return type here: https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/portlet/LiferayPortletResponse.java#L78

I guess casting to `PortletURL` is a better solution than using `String.valueOf`

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/826a0e547c...c479ff5934

**Comment by brianchandotcom** [comment]
Any way to make it so

```
		).setRedirect(
			(PortletURL)_liferayPortletResponse.createRenderURL()
```

we don't even need to cast? I mean, can't we just expect 

T extends PortletURL & RenderURL

Thx

**Comment by brianchandotcom** [comment]
@hhuijser 

Any way to make it so

```
		).setRedirect(
			(PortletURL)_liferayPortletResponse.createRenderURL()
```

we don't even need to cast? I mean, can't we just expect 

T extends PortletURL & RenderURL

Thx

**Comment by hhuijser** [comment]
@brianchandotcom I tried that, but couldn't get it to work

**Pull request closed without merging**
