### PR TITLE
LPD-32072 Technical Task | Add ExternalReferenceCode to Document Types (Part 1) 

### PR DESCRIPTION
**Pull request by Mikellorza**
Sending again because of :  https://github.com/brianchandotcom/liferay-portal/pull/152947#issuecomment-2269637838

https://liferay.atlassian.net/browse/LPD-32072

# What is this trying to solve?

Add external reference code to dl file entry type to internal api.

# How am I fixing it?

Add external reference code to dl file entry type to internal api.

# How can you verify that it works?

Run the included tests

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@Mikellorza I don't understand why we have extra logic in DLFileEntryTypeServiceImpl.java:

```
		DLFileEntryType dlFileEntryType =
			dlFileEntryTypePersistence.fetchByERC_G(
				externalReferenceCode, groupId);

		if (dlFileEntryType == null) {
			return null;
		}

		if (dlFileEntryType.getFileEntryTypeId() ==
				DLFileEntryTypeConstants.FILE_ENTRY_TYPE_ID_BASIC_DOCUMENT) {

			return dlFileEntryType;
		}

		ModelResourcePermission<DLFileEntryType>
			dlFileEntryTypeModelResourcePermission =
				ModelResourcePermissionRegistryUtil.getModelResourcePermission(
					DLFileEntryType.class.getName());

		dlFileEntryTypeModelResourcePermission.check(
			getPermissionChecker(), dlFileEntryType, ActionKeys.VIEW);

		return dlFileEntryType;
```

I understand the permission check, but the other stuff should be delegated to the generated method.

Please resend.

**Comment by Mikellorza** [comment]
@brianchandotcom ,

we have some logic there because this is the same logic that already have in other methods like [this one](https://github.com/liferay/liferay-portal/blob/d043fdbb9a978ba46c4de6743bfda9db8ea750f1/portal-impl/src/com/liferay/portlet/documentlibrary/service/impl/DLFileEntryTypeServiceImpl.java#L127). 

The purpose of that is to return  DLFileEntryType with type id = DLFileEntryTypeConstants.FILE_ENTRY_TYPE_ID_BASIC_DOCUMENT without checking permissons.

I am reopening it.

**Comment by Mikellorza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/95e050481f...5901eb615f

**Pull request closed without merging**
