### PR TITLE
LPS-75359

### PR DESCRIPTION
**Pull request by Ithildir**
Hi,
Please let this pull finish.

Thank you!

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:reopen

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ecb6324e74...80dd4fd8d6

**Comment by brianchandotcom** [comment]
@Ithildir can you send me this for the other branches? Thx!

**Pull request closed without merging**
