### PR TITLE
LPS-74544

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Pull for 7.0.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/19140

**Comment by hhuijser** [comment]
ci:test

**Comment by xbrianlee** [comment]
`Authentication#TestLDAPConnectionAndEntries` failure is unrelated. Fixing it in LRQA-37122.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
