### PR TITLE
LPS-91291 Copy structure and preferences from page template to draft layout

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
@brianchiu The failures seem to be not related to the pull, I tried to reproduce in local and couldn't, but I'm not 100% sure. Could you please take a look?
Thanks!

**Comment by brianchiu** [comment]
@pavel-savinov I'm on it.

**Comment by brianchiu** [comment]
ci:close

**Comment by brianchiu** [comment]
My bad. One of the tests was a test update that slipped past me. I will resend with that fix. Otherwise, the failures are unrelated.

**Comment by brianchiu** [comment]
Resent here:
https://github.com/brianchandotcom/liferay-portal/pull/69535

**Pull request closed without merging**
