### PR TITLE
LPS-62530 Get the portletConfig using the portletName

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @juliocamarero

**Comment by juliocamarero** [comment]
:+1:

**Comment by brianchandotcom** [comment]
@pyoo47 why did this abort?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e164a5c48f...115346cc60

**Comment by pyoo47** [comment]
@brianchandotcom It looks like the timed out while fetching from local git.
```
     [exec] + [[ -n '' ]]
     [exec] + rm -f /opt/dev/projects/github/liferay-portal/.git/index.lock
     [exec] + rm -fr /opt/dev/projects/github/liferay-portal/.git/rebase-apply
     [exec] + git reset --hard
     [exec] + rm -f /opt/dev/projects/github/liferay-portal/.git/index.lock
     [exec] + rm -fr /opt/dev/projects/github/liferay-portal/.git/rebase-apply
     [exec] + git reset --hard
     [exec] HEAD is now at 002b5c4 LPS-60454 buildLang
     [exec] + git checkout -b temp-20160128050847480
     [exec] + git checkout -b temp-20160128050847480
     [exec] Switched to a new branch 'temp-20160128050847480'
     [exec] + sed -i /github.liferay.com/d /root/.ssh/known_hosts
     [exec] Switched to a new branch 'temp-20160128050847480'
     [exec] + sed -i /github.liferay.com/d /root/.ssh/known_hosts
     [exec] + git fetch -f git@github.liferay.com:liferay/liferay-portal.git pr-brianchandotcom-35115-115346cc60b88bca2ad3a8318a5e0ea51be83012:master-temp-20160128050048191
     [exec] + git fetch -f git@github.liferay.com:liferay/liferay-portal.git pr-brianchandotcom-35115-115346cc60b88bca2ad3a8318a5e0ea51be83012:master-temp-20160128050048191
     [exec] Warning: Permanently added 'github.liferay.com,10.0.0.12' (RSA) to the list of known hosts.
     [exec] Warning: Permanently added 'github.liferay.com,10.0.0.12' (RSA) to the list of known hosts.
Build timed out (after 120 minutes). Marking the build as aborted.
Build was aborted
```

**Comment by pyoo47** [comment]
ci:retest

**Pull request closed without merging**
