### PR TITLE
LPS-63794 SF

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by sharonchoi** [comment]
@brianchiu upgrade test failures due to https://issues.liferay.com/browse/LPS-64526
@kenjiheigel portal smoke failings due to https://issues.liferay.com/browse/LPS-64500

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/af61b8fb8a...6495b73443

**Pull request closed without merging**
