### PR TITLE
LPS-109260 Build lang

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/827de58cf5...5d59224446

**Comment by brianchandotcom** [comment]
@preston-crary see

modules/apps/depot/depot-service/src/main/java/com/liferay/depot/internal/service/DepotGroupLocalServiceWrapper.java

It looks heavy handed... I wonder if an AOP would be better here?

**Comment by Preston-Crary** [comment]
Guys, this is silly.  Just update GroupImpl.

**Comment by brianchandotcom** [comment]
@adolfopa I reverted this.. I'm more worried about the maintenance work.

See comment by @Preston-Crary

**Comment by Preston-Crary** [comment]
Just update GroupImpl like this:
```
	@Override
	public String getScopeDescriptiveName(ThemeDisplay themeDisplay)
		throws PortalException {

		if (getGroupId() == themeDisplay.getScopeGroupId()) {
			if (getType() == GroupConstants.TYPE_DEPOT) {
				return StringUtil.appendParentheticalSuffix(
					themeDisplay.translate("current-asset-library"),
					HtmlUtil.escape(
						getDescriptiveName(themeDisplay.getLocale())));
			}

			return StringUtil.appendParentheticalSuffix(
				themeDisplay.translate("current-site"),
				HtmlUtil.escape(getDescriptiveName(themeDisplay.getLocale())));
		}
		else if (isLayout() && (getClassPK() == themeDisplay.getPlid())) {
			return StringUtil.appendParentheticalSuffix(
				themeDisplay.translate("current-page"),
				HtmlUtil.escape(getDescriptiveName(themeDisplay.getLocale())));
		}
		else if (isLayoutPrototype()) {
			return themeDisplay.translate("default");
		}

		return HtmlUtil.escape(getDescriptiveName(themeDisplay.getLocale()));
	}

	@Override
	public String getScopeLabel(ThemeDisplay themeDisplay) {
		if (getType() == GroupConstants.TYPE_DEPOT) {
			if (getGroupId() == themeDisplay.getScopeGroupId()) {
				return "current-asset-library";
			}

			return "asset-library";
		}

		if (getGroupId() == themeDisplay.getScopeGroupId()) {
			return "current-site";
		}

		if (getGroupId() == themeDisplay.getCompanyGroupId()) {
			return "global";
		}

		if (isLayout()) {
			return "page";
		}

		Group scopeGroup = themeDisplay.getScopeGroup();

		if (scopeGroup.hasAncestor(getGroupId())) {
			return "parent-site";
		}
		else if (hasAncestor(scopeGroup.getGroupId())) {
			return "child-site";
		}

		return "site";
	}
```

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/85314

**Pull request closed without merging**
