### PR TITLE
LPS-113883 Modify case to adapt the current behavior

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/1120

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6bd82c181f...d74f4dfa2c

**Comment by brianchandotcom** [comment]
@p2kmgcl @ealonso @ruben-pulido see deeaa0e34ad57993aa281c65495c33f4ad3e35ca 292fcb17beaba6b7e8c73c5f8cb27562898dff7b and d74f4dfa2c865642b58ef1baaf9fb4b7151e1427

**Pull request closed without merging**
