### PR TITLE
LPS-68336 Apply lexicon class

### PR DESCRIPTION
**Pull request by marcellustavares**
cc @vicnate5 @brandizzi

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest - I think that the plugins git commit was not available yet in '[liferay-plugins:master](https://github.com/brianchandotcom/liferay-plugins/commits/master)'. We'll try running it again.

**Comment by michaelhashimoto** [comment]
@marcellustavares @jpince @brianchiu @pyoo47
This is failing because our 'git-commit-plugins' is referring to an 'ee-7.0.x' plugins sha instead of a 'master' plugins sha.

I'm sending an update to bchan here:
https://github.com/brianchandotcom/liferay-portal/pull/43400

**Comment by marcellustavares** [comment]
thanks @michaelhashimoto, should I resend this pull after your fix?

**Comment by michaelhashimoto** [comment]
@marcellustavares - you might be able to just run <b>ci&#58;retest</b> after it gets merged.

**Comment by marcellustavares** [comment]
ci:retest

**Comment by jpince** [comment]
@marcellustavares SF error 
```
The following language keys were used in multiple modules and have been consolidated, or they already existed in portal-impl\src\content\Language.properties:
upcoming-events=Upcoming Events
: portal-impl/src/content/Language.properties
```

**Comment by marcellustavares** [comment]
thx @jpince

**Comment by marcellustavares** [comment]
rebased and resent to https://github.com/brianchandotcom/liferay-portal/pull/43578

**Pull request closed without merging**
