### PR TITLE
LPS-85512 Update Contact > Opening Hours to match the given designs

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-85512](https://issues.liferay.com/browse/LPS-85512).<br><br>Resent on top of https://github.com/drewbrokke/liferay-portal/pull/610.  Updated inconsistent variable names at c2679181293e per your request at https://github.com/brianchandotcom/liferay-portal/pull/63827#issuecomment-427258396.<br><br>/cc @pei-jung @stsquared99 @alee8888

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by drewbrokke** [comment]
@brianchandotcom looks like some unrelated SF failures.

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
@brianchandotcom the functional test failures are expected. We will fix them in a future task.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/95c56195d2...5b96184c4f

**Comment by brianchandotcom** [comment]
@drewbrokke I made a few more changes in upstream, please review.

I"m still not fond of "entryId".. coming over to explain.

**Pull request closed without merging**
