### PR TITLE
[TS] LPS-172530 Root Folder configuration in the Document & Media widget is lost when searching

### PR DESCRIPTION
**Pull request by Hanlf**
The original PR comment:

> Hi Team,
> Here is the PR for fixing https://issues.liferay.com/browse/LPS-172530. The original PR(https://github.com/thienquach87/liferay-portal/pull/24) was passed my review.
> Please help review it and leave your comments.
> Thanks.
> 
> Notes:
> Since we are indexing the treePath to search in folders and the tree path of the folder includes its folderId, that's why the search folder will be shown in the result. The idea is to index the folders with the tree path without the folderId.
> 
> cc:@tototrinh
> 
> In this PR, I add an integration test for this LPS. This is reviewed in :https://github.com/liferay-lima/liferay-portal/pull/3907

@brianchandotcom  resending this pull directly to you since after a few retries we confirmed this pull is not related to any of the failing tests in https://github.com/liferay-lima/liferay-portal/pull/3931.

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@tototrinh this is strange

```
		List<String> treePathValues = new ArrayList<>(
			Arrays.asList(
				ArrayUtil.remove(
					StringUtil.split(dlFolder.getTreePath(), CharPool.SLASH),
					String.valueOf(dlFolder.getFolderId()))));
```

Just make the list, then remove it. You're making 3 instances here when it can just be 1.

**Comment by locpham97** [comment]
ci:reopen

**Comment by locpham97** [comment]
ci:close

**Pull request closed without merging**
