### PR TITLE
LPS-97256 Jodd

### PR DESCRIPTION
**Pull request by martamedio**

### CODE REVIEW

**Comment by xbrianlee** [comment]
@brianchandotcom Don't merge 7a948c5 since you've already resolved the semver issue in https://github.com/brianchandotcom/liferay-portal/commit/5b08c4abea7d9cc812c7be10722e21a51cb42866

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5d63739ef0...aad06b3751

**Comment by brianchandotcom** [comment]
@martamedio see 090deba5f15b955b684227de49d3ee6d9f00245a and aad06b37513be35e21ca762c01709872603c6824

**Comment by brianchandotcom** [comment]
@martamedio I made a mistake in 090deba5f15b955b684227de49d3ee6d9f00245a

Ignore that commit, but instead, look at aad06b37513be35e21ca762c01709872603c6824 and see my change to modules/source-formatter.properties

```
    source.check.gradle.dependency.artifacts.check.enforceVersionArtifacts=\
        biz.aQute.bnd:biz.aQute.bnd.annotation:4.2.0,\
        com.fasterxml.jackson.core:jackson-annotations:2.9.9,\
        com.fasterxml.jackson.core:jackson-core:2.9.9,\
        com.fasterxml.jackson.core:jackson-databind:2.9.9,\
        com.liferay:org.apache.felix.configadmin:1.9.8.LIFERAY-PATCHED-3,\
        com.liferay:org.hibernate.core:3.6.10.LIFERAY-PATCHED-5,\
        commons-fileupload:commons-fileupload:1.3.3,\
        org.jodd:jodd-bean:3.6.8,\
        org.jodd:jodd-core:3.6.8,\
        org.jodd:jodd-http:3.6.8,\
        org.jodd:jodd-json:3.6.8,\
        org.jsoup:jsoup:1.10.2,\
        org.osgi:org.osgi.annotation.versioning:1.1.0,\
        org.osgi:org.osgi.dto:1.1.0,\
        org.osgi:org.osgi.service.cm:1.5.0,\
        org.osgi:org.osgi.service.component:1.3.0,\
        org.osgi:org.osgi.service.component.annotations:1.3.0,\
        org.osgi:org.osgi.service.event:1.3.1,\
        org.osgi:org.osgi.service.http.whiteboard:1.0.0,\
        org.osgi:org.osgi.service.log:1.4.0,\
        org.osgi:org.osgi.service.metatype:1.3.0,\
        org.osgi:org.osgi.util.function:1.1.0,\
        org.osgi:org.osgi.util.promise:1.1.0,\
        org.osgi:osgi.core:6.0.0

```

That makes it so you can run 'ant format-source-bnd' in portal-impl and enforce versions.

**Comment by martamedio** [comment]
Got it! Thanks @brianchandotcom :blush:

**Pull request closed without merging**
