### PR TITLE
Lps 72505

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by vicnate5** [comment]
Functional test failed due to missing success message during the setup of the portal instance. If this was a real issue, it would have failed other tests.

**Comment by brianchandotcom** [comment]
Thx @vicnate5 can we find out the root cause of why the test was flaky? Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4aa5c92d48...f854df0598

**Comment by brianchandotcom** [comment]
@tinatian see f854df0598dd50fbcbea02337973565e89612e37

Thx.

**Comment by tinatian** [comment]
Thanks @brianchandotcom ! Could you please also release a new snapshot for portal so that I can update the usages in journal repo?

Tina

**Pull request closed without merging**
