### PR TITLE
LPS-91480 Rename journal to web content where it makes sense for the end user text. There are other places were we don't rename since it'' mostly for ADTs

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by jkappler** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
This error is sooo strange...

:apps:headless:headless-collaboration:headless-collaboration-impl works for me locally..

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2a451e9730...5707d0a44c

**Comment by jkappler** [comment]
hey @brianchandotcom, seems that a .lfrbuild-portal is missing, that's why it's failing

**Pull request closed without merging**
