### PR TITLE
LPS-63057 Persist display style in Site Teams

### PR DESCRIPTION
**Pull request by jkappler**
cc:/ @ealonso

### CODE REVIEW

**Comment by jkappler** [comment]
Hi @marcellustavares, @sergiogonzalez: we persisted the display view in most of our portlets (3 will be updated in another PR). Just FYI.

**Comment by pyoo47** [comment]
ci:retest

**Comment by jkappler** [comment]
@brianchandotcom, my commits are on top of https://github.com/brianchandotcom/liferay-portal/pull/37873 with rebase errors corrected

**Comment by sharonchoi** [comment]
@brianchiu upgrade test failures due to https://issues.liferay.com/browse/LPS-64526
@kenjiheigel portal smoke failings due to https://issues.liferay.com/browse/LPS-64500

**Comment by brianchandotcom** [comment]
@jkappler compile error, please resend. thx

**Pull request closed without merging**
