### PR TITLE
LPS-65535 show cancel button when editing a layout

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by pyoo47** [comment]
This PR Test failed due to a problem with the temp-map functionality. @brianchandotcom , please retest as needed. I would retest now but the load is currently high and I could just cause more of these problems.

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by pyoo47** [comment]
This pull has a few functional tests that appear to have frozen.
```
[exec] 00:10:33,889 ERROR [Start Level: Equinox Container: c0e59431-1f1e-0016-1204-e84426621620][DBManagerImpl:86] java.lang.IllegalArgumentException: Unsupported database type db2
     [exec] java.lang.IllegalArgumentException: Unsupported database type db2
     [exec] 	at com.liferay.portal.dao.db.DBManagerImpl.getDB(DBManagerImpl.java:113)
     [exec] 	at com.liferay.portal.dao.db.DBManagerImpl.getDB(DBManagerImpl.java:80)
     [exec] 	at com.liferay.portal.kernel.dao.db.DBManagerUtil.getDB(DBManagerUtil.java:27)
     [exec] 	at com.liferay.portal.configuration.persistence.ConfigurationPersistenceManager.buildSQL(ConfigurationPersistenceManager.java:214)
     [exec] 	at com.liferay.portal.configuration.persistence.ConfigurationPersistenceManager.prepareStatement(ConfigurationPersistenceManager.java:469)
     [exec] 	at com.liferay.portal.configuration.persistence.ConfigurationPersistenceManager.hasConfigurationTable(ConfigurationPersistenceManager.java:372)
     [exec] 	at com.liferay.portal.configuration.persistence.ConfigurationPersistenceManager.start(ConfigurationPersistenceManager.java:160)
     [exec] 	at com.liferay.portal.configuration.persistence.activator.ConfigurationPersistenceBundleActivator.start(ConfigurationPersistenceBundleActivator.java:63)
     [exec] 	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:774)
     [exec] 	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
     [exec] 	at java.security.AccessController.doPrivileged(Native Method)
     [exec] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:767)
     [exec] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:724)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:951)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:328)
     [exec] 	at org.eclipse.osgi.container.Module.doStart(Module.java:566)
     [exec] 	at org.eclipse.osgi.container.Module.start(Module.java:434)
     [exec] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
     [exec] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
     [exec] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
     [exec] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
     [exec] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
     [exec] 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
```

```
     [exec] 00:00:21,528 INFO  [Start Level: Equinox Container: 30bf62cb-1d1e-0016-130c-b9485e7b1349][BundleStartStopLogger:35] STARTED org.osgi.service.metatype_1.3.0.201505202024 [39]
     [exec] 00:00:21,528 INFO  [Start Level: Equinox Container: 30bf62cb-1d1e-0016-130c-b9485e7b1349][BundleStartStopLogger:35] STARTED com.liferay.osgi.util_3.0.1 [1]
     [exec] 00:00:21,534 INFO  [Start Level: Equinox Container: 30bf62cb-1d1e-0016-130c-b9485e7b1349][DBManagerImpl:74] Using dialect org.hibernate.dialect.SybaseDialect
     [exec] 00:00:21,535 ERROR [Start Level: Equinox Container: 30bf62cb-1d1e-0016-130c-b9485e7b1349][DBManagerImpl:86] java.lang.IllegalArgumentException: Unsupported database type sybase
     [exec] java.lang.IllegalArgumentException: Unsupported database type sybase
     [exec] 	at com.liferay.portal.dao.db.DBManagerImpl.getDB(DBManagerImpl.java:113)
     [exec] 	at com.liferay.portal.dao.db.DBManagerImpl.getDB(DBManagerImpl.java:81)
     [exec] 	at com.liferay.portal.kernel.dao.db.DBManagerUtil.getDB(DBManagerUtil.java:27)
     [exec] 	at com.liferay.portal.configuration.persistence.ConfigurationPersistenceManager.buildSQL(ConfigurationPersistenceManager.java:214)
     [exec] 	at com.liferay.portal.configuration.persistence.ConfigurationPersistenceManager.prepareStatement(ConfigurationPersistenceManager.java:469)
     [exec] 	at com.liferay.portal.configuration.persistence.ConfigurationPersistenceManager.hasConfigurationTable(ConfigurationPersistenceManager.java:372)
     [exec] 	at com.liferay.portal.configuration.persistence.ConfigurationPersistenceManager.start(ConfigurationPersistenceManager.java:160)
     [exec] 	at com.liferay.portal.configuration.persistence.activator.ConfigurationPersistenceBundleActivator.start(ConfigurationPersistenceBundleActivator.java:63)
     [exec] 	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:774)
     [exec] 	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
     [exec] 	at java.security.AccessController.doPrivileged(Native Method)
```

**Comment by juliocamarero** [comment]
ci:retest

**Comment by pyoo47** [comment]
I think this pull failed because of a bad response from GitHub. ci:retest

**Comment by brianchiu** [comment]
The 606 upgrade testcase failed this time because of this bug: https://issues.liferay.com/browse/LPS-65878

There is a console error that sometimes happens due to a race condition.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d162ab23af...0a56b33db1

**Pull request closed without merging**
