### PR TITLE
master-lps-57450

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LPS-57450
https://issues.liferay.com/browse/LRQA-16886

Hi Brian, these are the product menu commits from Eudaldo. We've committed our frontend test fixes on top.

CC @natecavanaugh 
CC @ealonso 
CC @kenjiheigel
CC @anthony-chu 
CC @brianwulbern 
CC @koor4356

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@ealonso @juliocamarero @natecavanaugh 

There are backend test failures?

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
Hi @juliocamarero,

The test failures look like legitimate test failures. Would you be able to provide insight on these failures?

**Comment by brianchiu** [comment]
I'm going to close this pull request because it's not passing the PR tester.

Please see the email that @lawrence-lee is sending regarding this.

@brianchandotcom
@ealonso
@juliocamarero
@anthony-chu
@brianwulbern
@koor4356
@natecavanaugh

**Comment by brianchandotcom** [comment]
DLFileEntrySearchTest.testSearchTikaRawMetadata is OK to ignore. It passed in modules-integration-oracle and mysql. I'll work with Shuyang on fixing it. This pull is good to go. I'll merge it in a bit.

**Comment by brianchiu** [comment]
Oh ok. I'll reopen this then.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8c416ff7c2...7ac31805f2

**Comment by brianchandotcom** [comment]
@ealonso great job on this pull!

Can you send me a follow up to remove this duplicated code in the themes:

```
	<script>
		AUI.$('#sidenavContainerId').sideNavigation(
			{
				gutter: '0',
				toggler: '#sidenavToggleId',
				type: 'fixed-push',
				typeMobile: 'fixed',
				width: '320px'
			}
		);
	</script>
```

We should move abstract this out. It's fragile otherwise.

cc @juliocamarero @brianchiu

**Comment by brianchandotcom** [comment]
@ealonso also, please see my changes in upstream. Thx

**Pull request closed without merging**
