### PR TITLE
LPS-115709

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
Reverting because it causes regression: https://issues.liferay.com/browse/LPS-123404

@ealonso, do you mind having a look?

**Comment by hhuijser** [comment]
@brianchandotcom please backport!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b811171f24...1231daf493

**Pull request closed without merging**
