### PR TITLE
LPS-81667 Apply multi threading moving JournalArticleImages to DL during the journal upgrade

### PR DESCRIPTION
**Pull request by achaparro**
Hey @shuyangzhou, we have applied multithreading in this upgrade because the logic allows it. The improvement has been huge, from almost one week to 6 hours and 20 minutes. I think we can apply it in other parts of the upgrade process, I will send you a pull if we can build like a framework for this.

Thanks.

cc/ @pavel-savinov @jorgediaz-lr

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test

**Comment by achaparro** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/465b54e6f3...c8b7c6996b

**Comment by brianchandotcom** [comment]
@achaparro minor change in 0631a2179536a85a4a32d59e74d9815567b76066

**Pull request closed without merging**
