### PR TITLE
LPS-84271 Remove bundlerepository

### PR DESCRIPTION
**Pull request by shuyangzhou**
This saves 3 sec. Now we are stably under 60s. Roughly 58s +/- 0.5sec. 6.2 is at 54s.
We still have a few big leads, if they all work out in the best way, it is possible get close to 50s. But lower the expectation, some might not work in the exact way we wish.
CC @mhan810

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@shuyangzhou woo hoo! The OSGi state fix, is that in already?

**Comment by brianchandotcom** [comment]
@shuyangzhou I merged in this pull without removing the old patched jar from modules/third-party just in case we ever have to release it in 7.0.x.

If you tell me I can backport this removal all the way to 7.0.x, then please send me another pull to master to remove the patched jar, and also send me a pull to 7.0.x. Otherwise, I'll keep the patched jar in third party here.

**Comment by brianchandotcom** [comment]
@shuyangzhou nvm, I just saw your comment in the LPS-84271 "This bundle has never really been used", so I'm backporting this all the way back to 7.0.x then.

**Comment by shuyangzhou** [comment]
Yes, we can reuse osgi/state now. And the measurement is already based on that. So for the next release, the release team needs to bootup the server once and save the hsql and osgi/state folder to carry them into the release bundle.
I am pretty sure it can be backported to 7.0.x, we never really use that bundle for anything, at least not out of box.

**Comment by jpince** [comment]
cc/ @alee8888

**Comment by jpince** [comment]
cc/ @caustin582 @jrhoun @reizero00 @ctampoya @nicolelau See Shuyang's last comment

**Comment by CAustin582** [comment]
@brianchandotcom see https://github.com/brianchandotcom/liferay-portal/pull/62009

**Pull request closed without merging**
