### PR TITLE
ISSD-26 Move dtd files before moving www to LXC

### PR DESCRIPTION
**Pull request by ryanschuhler**

### CODE REVIEW

**Comment by ryanschuhler** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a4cc9e3805...612d06e038

**Comment by brianchandotcom** [comment]
@ryanschuhler yey.... monorepo benefits.

**Comment by brianchandotcom** [comment]
@ling-alan-huang can you SF enforce 612d06e03822843403179931fd1a122de72ed8ba

**Pull request closed without merging**
