### PR TITLE
LPS-68471

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-68471.  We had to revert this deprecation and we forgot to remove the deprecation comments in the tld file.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
