### PR TITLE
LPS-89680 SF

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
cc @ealonso @p2kmgcl

**Comment by brianchandotcom** [comment]
@sandrodw3 this is poorly formatted:

```
	<div class="sidebar-mapping">
	<p class="text-secondary small pb-2">
	  {msg desc=""}you-can-select-here-the-content-source-for-this-display-page{/msg}.
	</p>

	{call com.liferay.layout.content.page.editor.web.SelectMappingTypeForm.render}
	  {param store: $store /}
	{/call}
	</div>
```

Can you fix all of the *.soy templates and resend. Thx

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
see: https://github.com/brianchandotcom/liferay-portal/pull/69505

**Pull request closed without merging**
