### PR TITLE
LPS-78823 Implement UAD for contacts entry

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @willnewbury @drewbrokke

### CODE REVIEW

**Comment by pei-jung** [comment]
Tests passed here https://github.com/pei-jung/liferay-portal/pull/270#issuecomment-374724413

**Comment by brianchandotcom** [comment]
@pei-jung I reverted the commit to modify ServiceBuilder to add a marker file. That's for our internal CI use. Community members and customers would never use it. We just need to know to manually add it.

Merged.

**Comment by brianchandotcom** [comment]
@pei-jung see 100f47e2733e9a51cec643be8b7a235182c6b5af can you apply else where? Thx.

**Comment by pei-jung** [comment]
Got it. Will send a follow-up pull to remove the unnecessary assignment.

**Pull request closed without merging**
