### PR TITLE
LPS-86009 Consistent typing.

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Thanks @Preston-Crary!

**Comment by jpince** [comment]
@patriciajeanperez @austinchiang

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c5791195df...207355ea90

**Comment by brianchandotcom** [comment]
Nicely done @4lejandrito and @Preston-Crary !

**Pull request closed without merging**
