### PR TITLE
Lps 69899

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
I backported this to ee-7.0.x and fixed a merge conflict. Please review that branch. Thx.

**Comment by shuyangzhou** [comment]
@Preston-Crary please double check on ee-7.0.x

**Comment by Preston-Crary** [comment]
@brianchandotcom @shuyangzhou I double checked, looks good.

**Pull request closed without merging**
