### PR TITLE
LPS-71164

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:reopen

**Comment by brianwulbern** [comment]
@hhuijser There was a slough of issues on master today, I don't _think_ these are related to your pull.  See [Loop topic](https://loop.liferay.com/web/guest/home/-/loop/topics/_PullRequestTester)

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
