### PR TITLE
LPS-70797 Adds .lfrbuild-portal marker

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/407cdd63ff...967307bce4

**Comment by brianchandotcom** [comment]
@jbalsas @Robert-Frampton why don't we make this a true OSGi module?

Merged.

**Comment by jbalsas** [comment]
Hey @brianchandotcom,

We can't currently make it an OSGi module because the extension mechanism is not supported. I've added a task to make it so as soon as possible. Once that's done, we'll update the module.

Thanks!

**Comment by jbalsas** [comment]
Backport sent to https://github.com/dustinryerson/liferay-portal-ee/pull/2910 to prepare for the release

**Pull request closed without merging**
