### PR TITLE
LPS-58790 

### PR DESCRIPTION
**Pull request by matethurzo**
cc @marcellustavares.

@brianchandotcom the first commit belongs to a different pull I've sent you: https://github.com/brianchandotcom/liferay-portal/pull/30341 but it's an important bugfix for here as well.

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2f1d8ad418...5361a22da0

**Comment by brianchandotcom** [comment]
@matethurzo see 5361a22da087bad80400414f621ab4ff5b294978

Thx

**Pull request closed without merging**
