### PR TITLE
LPS-68325 Task depends on npmInstall

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @ithildir, could you take a look at the gradle tasks? In this case, `npmInstall` is not being triggered even if both `package.json` and `npm-shrinkwrap.json` files are in there.

/cc @eduardolundgren, @mairatma, @brunobasto

**Comment by jbalsas** [comment]
@brianchandotcom, BPR sent to ee-7.0.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/14450

**Comment by jbalsas** [comment]
SourceFormatter issues have been pushed, thanks @sergiogonzalez

ci:reopen

**Comment by jbalsas** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@ithildir please review. Merged.

**Comment by Ithildir** [comment]
I sent a pull with a small SF at https://github.com/brianchandotcom/liferay-portal/pull/43397.

@jbalsas: `npmInstall` can't run by itself, some other task must depend on it in order for it to be part of the task graph. We added the dependency from `transpileJS`, but I don't remember if you wanted it also from `configJSModules`. Should I add it by default in the `gradle-plugins-js-module-config-generator`?

Thank you!

**Comment by jbalsas** [comment]
Hey @Ithildir, I thought we made it so `npmInstall` will always run if a `package.json` file was in the project... we shouldn't tie the task to any other, but simply to the existence of that file.

**Comment by Ithildir** [comment]
Unfortunately, that's not how Gradle works. You tell it what task you want, and it creates a task graph based on the dependencies we defined. I could make **ALL** the tasks depend on `npmInstall`, but it sounds overkill :confused: And it's easy to just add the dependency wherever it's needed.

**Comment by jbalsas** [comment]
we should have a general task depend on `npmInstall`, then... should be one of the first ones to run, since it's grabbing dependencies.

**Comment by brunobasto** [comment]
Can **compile** or **deploy** depend on it? But it only actually calls _npm install_ if there's a package.json file?

**Comment by Ithildir** [comment]
We can't make `deploy` depend on `npmInstall`. What if you want to only run `configJSModules`? You can do it if you want... and, if `deploy` depends on both `npmInstall` and `configJSModules`, but there's no dependency between the two, then Gradle doesn't know which one to execute first... so it can happen that `configJSModules` is executed before `npmInstall`.

Maybe I can add a dependency on all the Node tasks... what do you think?

**Comment by jbalsas** [comment]
That's not enough. We may simply want to grab some dependencies and move them somewhere before the `jar` task, no need for anything else to happen.

Let's start an email thread and discuss about it there 😉

**Pull request closed without merging**
