### PR TITLE
LPS-126407, LPS-126416 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-126407
https://issues.liferay.com/browse/LPS-126416

This is only for master.

@david-gutierrez-mesa
@alexcandidos

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure cases are unrelated to changes in PR.
See https://github.com/liferay-echo/liferay-portal/pull/3637
❌ ci:test:stable - 8 out of 9 jobs passed
❌ ci:test:relevant - 20 out of 25 jobs passed in 3 hours 8 minutes

**Comment by brianchandotcom** [comment]
@thaisfrota please review.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0452c78cb9...cedd4d39fa

**Pull request closed without merging**
