### PR TITLE
LPS-128259 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-128259

This is only for master.

@ruben-pulido
@ealonso
@jkappler

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure case is unrelated to changes in this PR.
See https://github.com/liferay-echo/liferay-portal/pull/4977
❌ ci:test:stable - 9 out of 10 jobs passed
❌ ci:test:relevant - 19 out of 23 jobs passed in 2 hours 5 minutes

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/70917c81bd...33cfb777aa

**Comment by brianchandotcom** [comment]
@jkappler minor changes in 47bf73b3ad67b4a2149944b2eee43b19b66177f9 and 33cfb777aa039add6a6fadfa00ffb8efab774ac2

**Pull request closed without merging**
