### PR TITLE
LPS-60679 DDM fields are not indexed for PT locales with Elasticsearch

### PR DESCRIPTION
**Pull request by arboliveira**
Author: @dacousalr 
Reviewer: @arboliveira

### CODE REVIEW

**Comment by arboliveira** [comment]
Rebasing on master right now, SF has been fixed there.

**Comment by arboliveira** [comment]
ci:retest

**Comment by arboliveira** [comment]
Hm, another SF error, different from the first -- also fixed in master. Rebasing again.

**Comment by arboliveira** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cd32aebc18...32f0007542

**Pull request closed without merging**
