### PR TITLE
[Sidecar]LPS-106592-LPS-103577

### PR DESCRIPTION
**Pull request by tinatian**
FYI @shuyangzhou @vicnate5 @arboliveira @jpince

### CODE REVIEW

**Comment by tinatian** [comment]
ci:open

**Comment by tinatian** [comment]
ci:reopen

**Comment by joshchong** [comment]
ci:close

I couldn't find test results for these changes anywhere so closing for now. Will run tests here and analyze.

**Comment by joshchong** [comment]
ci:test:sf

**Comment by joshchong** [comment]
Testing here: https://github.com/joshchong/liferay-portal/pull/266

**Pull request closed without merging**
