### PR TITLE
LPS-68937 As a developer I would like the twitter portlet available as an OSGI module

### PR DESCRIPTION
**Pull request by peterfellwock**
@shuyangzhou FYI

### CODE REVIEW

**Comment by peterfellwock** [comment]
ci:open

**Comment by peterfellwock** [comment]
ci:close

**Comment by jpince** [comment]
@peterfellwock 
```
java.lang.Exception: 
##
## 2 Liferay Exceptions were thrown
##

LIFERAY_ERROR: [com.liferay.twitter.util.TimelineProcessorUtil(2156)] The activate method has thrown an exception 
LIFERAY_ERROR: [com.liferay.twitter.util.TimelineProcessorUtil(2156)] Failed creating the component instance; see log for reason 
```

**Comment by peterfellwock** [comment]
@jpince looking into this, made some changes and sent to myself https://github.com/peterfellwock/liferay-portal/pull/256 I hate the wiring on the TimelineProcessorUtil

**Pull request closed without merging**
