### PR TITLE
LPS-65224 Use servlet qualified name

### PR DESCRIPTION
**Pull request by csierra**
/cc @marcellustavares

### CODE REVIEW

**Comment by csierra** [comment]
Hey @marcellustavares, 

we are using `CXFNonSpringServlet` since `CXFServlet` statically pulls a lot of Spring dependencies we don't need or use. Using `CXFServlet.class.getName()` tried to initialize the class and failed due to missing dependencies.

**Comment by marcellustavares** [comment]
thx for the info @csierra! 👍

**Comment by brianchandotcom** [comment]
Thank you so much @csierra !

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/821ba1b59d...dcd1d25d22

**Comment by csierra** [comment]
sure... no problem 👍

**Pull request closed without merging**
