### PR TITLE
LPS-64323 stick with immutable model

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b1a9e1523b...b60874efe7

**Comment by brianchandotcom** [comment]
@juangon can you resend the test portlet now, with PASSED / FAILED in the jsp?

See test-localized-portlet

Thx!

**Comment by brianchandotcom** [comment]
@juangon the test might be easier too.. see test-pacl-portlet as well.

**Comment by juangon** [comment]
@brianchandotcom I've sent test here: https://github.com/brianchandotcom/liferay-plugins/pull/5244

**Pull request closed without merging**
