### PR TITLE
LPS-57609 apply same pattern to all control panel urls in the portal and modules

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
@brianchandotcom @brianchiu I can't understand the latest error  :(

I understand that I am using a deprecated method (setRefererPlid) in edit_permissions.jsp, however that method was already there, I didn't change that line of code. And the method doesn't seem to be deprecated in PortletURLImpl.  can you help me?

thank you!!

**Comment by brianchandotcom** [comment]
It's cause it's not a LiferayPortletURL.

The method setRefererPlid is not part of PortletURL. Please resend? THx.

**Pull request closed without merging**
