### PR TITLE
LPS-88303 SF

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LPS-88303

This is for master only.

cc @jbalsas

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by kyle-miho** [comment]
ci:help

**Comment by kyle-miho** [comment]
ci:test:bundle

**Comment by pyoo47** [comment]
@kyle-miho FYI your test failed because Brian already deleted his pull request branch from his origin

**Pull request closed without merging**
