### PR TITLE
Lps 104348

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
'Just

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/510b8c1949...c4a81cc46e

**Comment by brianchandotcom** [comment]
@shuyangzhou I removed your constants in StringPool. I'm just not sure that is the right place to put it... it could go in HttpUtil or some other place. So for now, I kept it as free form text to remove dependencies.

**Comment by brianchandotcom** [comment]
@jorgediaz-lr fyi

**Pull request closed without merging**
