### PR TITLE
LPS-186262 Make explicit the initial upgrade step service tracker

### PR DESCRIPTION
**Pull request by achaparro**
cc/ @shuyangzhou @vicnate5

### CODE REVIEW

**Comment by achaparro** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/47da9bb8c1...eedce19605

**Comment by brianchandotcom** [comment]
@shuyangzhou @achaparro 

For 

```
	protected void deactivate() {
		_serviceTrackerMap.close();

		_initialUpgradeStepServiceTrackerMap.close();
	}
```

I changed it to 74f50fae95a693291228731ec0e672f908b7f6b1 is that ok?

Thx

**Comment by brianchandotcom** [comment]
@shuyangzhou @achaparro this hash 74f50fae95a693291228731ec0e672f908b7f6b1

**Comment by achaparro** [comment]
Yes @brianchandotcom, it is fine. Thx

**Pull request closed without merging**
