### PR TITLE
LRQA-32815 Store core POSHI functions as resources

### PR DESCRIPTION
**Pull request by pyoo47**
http://issues.liferay.com/browse/LRQA-32815

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@lesliewong92 @pyoo47 how come the core poshi functions ask for a SPA refresh? How is that needed for regular qa websites?

**Comment by pyoo47** [comment]
@brianchandotcom WaitForSPARefresh is used only by portal but it is designed to be do nothing when the function is invoked with non-portal pages. The same is true for assertLiferayErrors. Both of these functions are invoked by all the other functions so if we excluded them, Portal would have to override all of them. We chose to leave them in but in a way that would not interfere with non-portal pages.

CC: @lesliewong92 @brianchiu

**Comment by pyoo47** [comment]
@brianchandotcom After some additional thought, I think we could implement some kind of very basic inheritance model for functions that would allow Portal to extend the core functionality without being force to duplicate code. What do you think?

CC: @lesliewong92 @brianchiu

**Comment by brianchandotcom** [comment]
@pyoo47 yeah, that's better. It seems very wrong to have "core" functions.

Think of these functions like java.lang.

I could even see us putting them in dirs, like

resources/core/
resources/portal/ etc.

And the second dir would be a jar by itself.

So we could have com.liferay.poshu.runner.resources.portal as its own bundle.

**Pull request closed without merging**
