### PR TITLE
LPS-70807 SF

### PR DESCRIPTION
**Pull request by inacionery**
/cc @brandizzi @marcellustavares

### CODE REVIEW

**Comment by inacionery** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@pyoo47 what's going on ? Lots of slave issues?

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by pyoo47** [comment]
@brianchandotcom The failures where you see
```
[exec] Unable to fetch with GIT custom fetch.
```
are caused by the git fetch issue we talked about last week. We increased the timeout period this morning but it seems like it's still happening. I'll talk with Sam to see if there's anything more we can do.

**Pull request closed without merging**
