### PR TITLE
LPS-64629 Do not use ActionUtil.getMessageDisplay method in PortletConfigurationIcons. This method calls a method in service that increments the views and creates new activities

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by pyoo47** [comment]
This test was unable to generate the GitHub message but the jenkins report can be found [here](https://test-1-12.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1214/jenkins-report.html). 

The top-level result was FAILURE.

The Github message appears to have failed because it somehow received some invalid JSON from Jenkins so it threw an exception and died.

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f33f24969e...348b8d340f

**Pull request closed without merging**
