### PR TITLE
LPS-89373 Don't convert keywords to lowercase to support case-sensitive databases

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
@Preston-Crary Could you please take a look at https://github.com/brianchandotcom/liferay-portal/pull/67412/commits/992f6592b7cb8dec2dfadf98a4658072c57b17a0? Maybe it makes sense not convert keywords to lowercase by default to support case-sensitive DBs?

@kyle-miho Thanks! With these tests I discovered a very nice bug on my case-sensitive Postgres :)

/cc @ealonso

**Comment by kyle-miho** [comment]
@pavel-savinov Thanks for reviewing!

**Comment by Preston-Crary** [comment]
@pavel-savinov See the case-sensitive="false" attribute in the service.xml, this is why the persistence is using "lower(assetListEntry.title) LIKE ?" in the SQL.  You'll need to change that attribute and regenerate if you want the query to honor case.

**Comment by brianchandotcom** [comment]
Can you resend and use RandomTestUtil.randomString() as much as posisble? Thx.

git grep "randomString" **.java

**Comment by kyle-miho** [comment]
@brianchandotcom ahhh makes sense, that will definitely improve clarity too, I'll resend to @pavel-savinov

**Pull request closed without merging**
