### PR TITLE
LPS-159037 Expose binary content in the REST builder auto-generated client to use it for binary contents (as a zip folder)

### PR DESCRIPTION
**Pull request by ccorreagg**
PR forwarded manually from https://github.com/liferay-frontend/liferay-portal/pull/2573

---

There are some endpoints that returns binary content (application/octet-stream), as for example, the following one:

```
curl -X GET \
      'http://localhost:8080/o/headless-batch-engine/v1.0/import-task/1/content' \
      -u 'test@liferay.com:test' \
      --output myfile.zip
```
The response of that requests is the content of a ZIP file.

Currently, REST Builder is generating a client within the `<module-name>-client` module, with the following class `HttpResponse`:

```
public class HttpResponse {

	public String getContent() {
		return _content;
	}

	public String getMessage() {
		return _message;
	}

	public int getStatusCode() {
		return _statusCode;
	}

	[...]
}
```
As the content of the body is being parsed as a String, in the case where the body contains binary characters, they are being parsed as a String with certain encoding. That makes that parsing it back produces different binary characters from the original ones.

To provide a way to get the binary content, a new method has been created and the parsing process has been modified to keep the binary content unaltered:

```
public class HttpResponse {

	public byte[] getBinaryContent() {
		return _binaryContent;
	}

	public String getContent() {
		return _content;
	}

	[...]
}
```
That method might be used to get the binary content body returned. See the following example for the same endpoint:

```
ImportTaskResource.Builder builder = ImportTaskResource.builder();

importTaskResource = builder.authentication(
	"test@liferay.com", "test"
).locale(
	LocaleUtil.getDefault()
).build();

HttpInvoker.HttpResponse httpResponse =
	importTaskResource.getImportTaskContentHttpResponse(1L);

FileOutputStream fileOutputStream = new FileOutputStream("myfile.zip");

fileOutputStream.write(httpResponse.getBinaryContent());
fileOutputStream.flush();
fileOutputStream.close();
```

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/42ed6b4cd7...fcf6a8c88c

**Comment by brianchandotcom** [comment]
@ccorreagg see 1fce3efc088bbde1f07d8adfca0257c37c0441e9 and 4aba736f5f2656420d2e57fc3b71efa8f6e80949

**Comment by brianchandotcom** [comment]
@ccorreagg I'm also regenerating in older branches

**Pull request closed without merging**
