### PR TITLE
LPS-131631 buildLang

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:reopen

**Comment by guilhermedcamacho** [comment]
Sending it directly to you as requested in [comment](https://github.com/brianchandotcom/liferay-portal/pull/101698#issuecomment-840101008) of PR #101698 
cc: @marcelabc

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/64df8d6473...be425a3232

**Comment by brianchandotcom** [comment]
Thx @guilhermedcamacho @marcelabc I merged this to my origin.

**Comment by brianchandotcom** [comment]
Also...

```
	com.liferay.dynamic.data.mapping.validation,\
	com.liferay.dynamic.data.mapping.validator,\
```

Any way to remove this confusion?

**Comment by brianchandotcom** [comment]
Also...

```
	com.liferay.dynamic.data.mapping.validation,\
	com.liferay.dynamic.data.mapping.validator,\
```

Any way to remove this confusion?

@marcelabc @guilhermedcamacho fyi

**Pull request closed without merging**
