### PR TITLE
LPS-74837

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-74837.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
@brianchandotcom no unique failures, looks good from a functional test perspective

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/22490bfb7f...3751b48563

**Pull request closed without merging**
