### PR TITLE
LPS-65693 regenerate

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by pyoo47** [comment]
This pull request test has hit an intermittent modules-integration-sybase issue that causes the portal to fail to start up and then freeze. I'm aborting only those tests so that the rest of the pull request test can complete normally without having to wait for the sybase tests to timeout (after 2 hours).

**Comment by brianchandotcom** [comment]
Nice :) the other failures are unrelated! Thx @rotty3000 !!!

**Comment by brianchandotcom** [comment]
@pyoo47 how can we automatically time out those Sybase tests?  2 hour is a long time.

**Comment by pyoo47** [comment]
I think I know what the problem is and Sam helped me to resolve it. I am not expecting to see these Sybase timeout anymore.

**Comment by jpince** [comment]
only one functional test failure 606Upgrade, which is waiting on https://github.com/brianchandotcom/liferay-portal/pull/40215 to be merged.

**Comment by brianchandotcom** [comment]
Cool. Thx @pyoo47

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9e6c64721b...6b12e4c28c

**Comment by brianchandotcom** [comment]
@rotty3000 Pushed up! Please see/review my changes. Thx Ray!

**Pull request closed without merging**
