### PR TITLE
LPS-65135

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@shuyangzhou @brianchandotcom

See https://github.com/brianchandotcom/liferay-portal/pull/38848/commits/87cbd5838b7120bfdeb7804a4755fc44bf66e397

Very tricky NPE since Objects.equals(Object a, Object b) call a.equals(b)
We could have more of those, but no easy way to catch these right now...

**Comment by hhuijser** [comment]
ci:stop

**Comment by hhuijser** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
Yes, @hhuijser good catch, that's the only thing Objects.equals() is different from our Validator.equals(). And our logic is better. If not for the removing dependencies purpose, we would not make this change.

But back to topic, I think this is ok, the only case that we don't do the standard equals() logic is inside some private CacheKey classes. For example, PermissionCacheUtil.PermissionKey. In those cases, either Objects.equals() or Validator.equals() would be used.

This SimpleNestedSetsTreeNode case is special, I don't think it exists anywhere else. Basically I was assuming SimpleNestedSetsTreeNode is the same as those cache keys, but apparently not.

**Comment by hhuijser** [comment]
@shuyangzhou

I am doing a quick check to make sure all our equals methods are NPE proof.

**Comment by shuyangzhou** [comment]
Great, just make sure to let those "private static class *Key" classes go, as they are on purposely avoiding the null and instanceof checking. Everyone else should do the standard equals() logic.

**Comment by hhuijser** [comment]
Thanks @shuyangzhou

Already found a few... closing this one for now... will send another pull later.

**Comment by shuyangzhou** [comment]
Oh, really... can you send me some quick examples?

**Comment by hhuijser** [comment]
False alarm... all the cases I found seem private classes that are deliberate...

Reopening...

**Comment by shuyangzhou** [comment]
Ok, good :) We have been careful on those equals/hashcode, I am not confident enough to say they are all good, since you just caught one in the test :(
But as least for production code, the chance that we let a bad one slipping in is very low.

**Comment by hhuijser** [comment]
@shuyangzhou

Actually, what about HitsProcessorRegistryImpl.SortableHitsProcessor?

**Comment by shuyangzhou** [comment]
It looks good to me.
1) SortableHitsProcessor is private
2) It only works with _hitsProcessors which is a private collection, never talks to outside.
3) hitsProcessors is ConcurrentSkipListSet which does not allow null value.

I don't see how its equals() could be invoked with a null value or any object that is not type of SortableHitsProcessor.

**Comment by hhuijser** [comment]
Sounds good. thanks!

**Comment by brianchandotcom** [comment]
Bravo @hhuijser  :)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4e4c0b6141...e35b0f53dd

**Pull request closed without merging**
