### PR TITLE
LRQA-39439 | master

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-39439

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:test

**Comment by xbrianlee** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/718691496c...f99a6ae629

**Comment by brianchandotcom** [comment]
@xbrianlee Should we rename 

configure-kibana-* and configure-x-pack-security-*?

It's not immediately obvious why some are called

configure-elasticsearch-x-pack-security

and some are called

configure-x-pack-security-*

Thx

**Pull request closed without merging**
