### PR TITLE
LPS-81376 Localize autosave date

### PR DESCRIPTION
**Pull request by p2kmgcl**
/cc @pavel-savinov
/cc @ealonso

### CODE REVIEW

**Comment by p2kmgcl** [comment]
@brianchiu @kyle-miho could you check tests for this PR please?

**Comment by jpince** [comment]
ci:close US holiday today. Please reopen if this is urgent, otherwise they will take a look tomorrow

**Comment by kyle-miho** [comment]
ci:reopen

**Comment by kyle-miho** [comment]
@p2kmgcl I'm pretty sure the failing test was a flake. Checking again on ci:test:relevant to be sure.

**Pull request closed without merging**
