### PR TITLE
LPS-65505 Move the logic to view entries and use currentURL as the redirect param instead of the new url so it can preserve the parameter such as the delta or the cur.

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
I had to stop and retest this pull because a recent CI pull that got merged into upstream broke the PR tester. The source of this problem has been reverted.

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/25ebe99e89...df47a9e454

**Pull request closed without merging**
