### PR TITLE
LPS-138425 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-138425

This is only for master.

@victorg1991
@jkappler

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The semantic versioning is unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/5673
✔️ ci:test:stable - 10 out of 10 jobs passed
❌ ci:test:relevant - 21 out of 23 jobs passed in 1 hour 39 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/30012545a1...7c82c3269e

**Comment by brianchandotcom** [comment]
@jkappler see 082da0df90a5537cdf77b8a6ec97ddffc63b9a17

**Pull request closed without merging**
