### PR TITLE
Lps 74683

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pyoo47 no test results?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7cf3b24d74...3fa8d8490a

**Comment by brianchandotcom** [comment]
@tomwang2011 can you resend this? everything in petra should be petra-*

**Comment by brianchandotcom** [comment]
nvm, talked to @tomwang2011 he's going to send me a backport to 7.0.x

**Pull request closed without merging**
