### PR TITLE
master-sc-357

### PR DESCRIPTION
**Pull request by sharonchoi**
https://issues.liferay.com/browse/LRQA-21082
https://issues.liferay.com/browse/LRQA-20913
https://issues.liferay.com/browse/LRQA-21085
https://issues.liferay.com/browse/LRQA-21056
https://issues.liferay.com/browse/LRQA-21009
https://issues.liferay.com/browse/LRQA-21020
https://issues.liferay.com/browse/LRQA-20953
https://issues.liferay.com/browse/LRQA-21016
https://issues.liferay.com/browse/LRQA-21012
https://issues.liferay.com/browse/LRQA-21014

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
Aborted due to known start-up issue caused by https://github.com/brianchandotcom/liferay-portal/commit/d992d839572c70e1e93be6c97b1566069941a69f

After this <a href="https://github.com/brianchandotcom/liferay-portal/pull/34330">pull</a> is merged we can re-run this particular pull request.

Sorry for the inconvenience.

**Comment by michaelhashimoto** [comment]
Aborted due to known start-up issue caused by https://github.com/liferay/liferay-portal/commit/d992d839572c70e1e93be6c97b1566069941a69f

After this <a href="https://github.com/brianchandotcom/liferay-portal/pull/34330">pull</a> is merged please re-run this particular pull request.

Sorry for the inconvenience.

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/511826f73d...c4d8a0e609

**Pull request closed without merging**
