### PR TITLE
LPS-64588

### PR DESCRIPTION
**Pull request by Ithildir**
cc @marcoscv-work and @Robert-Frampton

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6717ac113c...f520a02d0f

**Comment by brianchandotcom** [comment]
@marcoscv-work I backported this to ee-7.0.x and 7.0.x. Can you update the exploded LARs in those branches to make sure they work? I'd like to see a minimal diff since it's all exploded now. Thanks!

**Comment by brianchandotcom** [comment]
@Ithildir somehow private.lar got added back in your pull. 

You added it in accidentally in ffe97182af228ecee3ae09aee2a3cd9599dbcfa5

I removed it in 13cb73af93aa986eab0ad869fba9ec1d92da7258

Fyi.

**Comment by brianchandotcom** [comment]
@marcoscv-work note the private.lar change by Andrea to product app. I need you to ensure it works in 7.0.x and ee-7.0.x. Thx.

**Comment by marcoscv-work** [comment]
@brianchandotcom @Ithildir thanks a lot guys, finally the solution looks great. I will add a commit and I will send PR changing the build-number to ensure they are working on ee-7.0.x / 7.0.x

**Pull request closed without merging**
