### PR TITLE
LPS-160143 Add simpler API for getURLViewInContext

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-160143

@balazssk 
@ruben-pulido

### CODE REVIEW

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See [liferay-echo#7560](https://github.com/liferay-echo/liferay-portal/pull/9464)

:heavy_check_mark: ci:test:stable - 27 out of 27 jobs passed
:x: ci:test:relevant - 539 out of 599 jobs passed in 2 hours 4 minutes

**Comment by ozysouza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@balazssk for master

```
	public default String getURLViewInContext(
			ThemeDisplay themeDisplay, String noSuchEntryRedirect)
		throws Exception {

		throw new UnsupportedOperationException(
			"This method needs to be implemented");
	}
```

should not be like this. A breaking change is fine. Please resend.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/02cb8411cc...841c6341b5

**Comment by brianchandotcom** [comment]
@balazssk I merged it, see 841c6341b50b3f82f56af3566e862d64e2966908 for master

**Pull request closed without merging**
