### PR TITLE
LPS-184003 Release FF for Objects and Page Builder Integration Enhancements

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-184003)

Adds metadata in portal.properties to convert LPS-176083 in a release feature flag

## Change summary:

* Adds metadata in portal.properties

## Test Scenario

* Deploy portal-impl for the current PR
* Start the portal
* Go to Applications Menu -> Instance Settings
* Click on Platform -> Feature Flags
* Click on Release Tab 
* You will see LPS-176083 listed

### CODE REVIEW

**Comment by jkappler** [comment]
ci:reopen

**Comment by jkappler** [comment]
@brianchandotcom, Mateo talked to our technical writer as you mentioned.
 
Thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5a96a07db9...b02f1b3937

**Comment by brianchandotcom** [comment]
Nice, just b02f1b3937969290630ec5ff13182b786622ee8b to match the other RFF @jkappler

**Pull request closed without merging**
