### PR TITLE
LPS-86245 Removing unthrown exceptions

### PR DESCRIPTION
**Pull request by 4lejandrito**
Follow up of https://github.com/brianchandotcom/liferay-portal/pull/63984#issuecomment-428643103 and https://github.com/brianchandotcom/liferay-portal/pull/63984#issuecomment-428643520.

I think `getSharingEntryObjectTitle` is still a valid name for that method. However having a look at that class again made me reconsider other names (see https://github.com/brianchandotcom/liferay-portal/pull/64033/commits/fc7d024a493ff23c60ed857412ccadbcee00b4e4).

Thanks!

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@cgoncas fyi StructuredContentNestedCollectionResourceFilteringTest

Can you fix this broken test? Thx.

**Pull request closed without merging**
