### PR TITLE
LPS-59105

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @topolik @robertoDiaz

**Comment by topolik** [comment]
Thanks @sergiogonzalez for the other places!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bed2f53ebf...53fb72238b

**Comment by brianchandotcom** [comment]
@topolik please resend on top of https://github.com/topolik/liferay-portal/pull/202

This pull has Poshi errors

**Pull request closed without merging**
