### PR TITLE
Lps 95330

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.

**Comment by brianchandotcom** [comment]
@petershin do we still need this in modules/build.gradle

```
ext {
	projectTemplateTokens = [
		"biz.aQute.bnd.version": "3.5.0",
		"com.liferay.ant.bnd.version": "2.0.52",
```

It's pointing to a really old version of ant.bnd. Can we get rid of that line?

**Comment by brianchandotcom** [comment]
@shuyangzhou I ported this all the way to 7.0.x

**Comment by petershin** [comment]
@brianchandotcom: Its still needed.  There's a few plugins that are being used by our Maven customers

**Pull request closed without merging**
