### PR TITLE
LPS-62787 add taglib and jstl dependencies to mvcportlet template

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:stop

**Comment by gamerson** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@gamerson published a new jar for you @AndyWu2015

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f6dbc4652b...76d578e39a

**Pull request closed without merging**
