### PR TITLE
LPS-86230 Remove plural from Roles when defining inline permissions

### PR DESCRIPTION
**Pull request by drewbrokke**
@drewbrokke 
[LPS-86230](https://issues.liferay.com/browse/LPS-86230)

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2680ed48d7...05d1e6b107

**Pull request closed without merging**
