### PR TITLE
LPS-67752 Semver

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by daviddotzhang** [comment]
ci:reopen

**Comment by dozeki** [comment]
@adolfopa @sergiogonzalez @daviddotzhang

**Comment by dozeki** [comment]
@adolfopa @daviddotzhang @sergiogonzalez Hello everyone, this is Daniel the RSM at the Japan office. I'd like to get a timeline of when we plan on getting this fix passed review and scheduled in the next fixpack, as we have kept our customer waiting for over 1 month trying to get this review. I understand we can't know for sure when this fix will go through but I'd like some kind of timeline to be able to tell our customer who's patience is starting to thin. May I get a timeline of when we expect the review to pass by today? Thank you

**Comment by adolfopa** [comment]
@dozeki Unless Brian finds something that needs fixing, this should be in master today; once merged, it will take around 1 day to get it backported to EE. See https://github.com/brianchandotcom/liferay-portal/pull/43949.

**Comment by dozeki** [comment]
@adolfopa Thank you so much for the quick response! Will be waiting for the good news :)

**Pull request closed without merging**
