### PR TITLE
LPS-63640 use ServletContext classloader when available

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by pyoo47** [comment]
Aborting this build so I can reset PR tester. I will retest this soon.

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest 2 hours and stil no result, so I'm retesting.

**Comment by rotty3000** [comment]
The pacl test pass here for me in reasonable time...

**Comment by brianchandotcom** [comment]
Hey @rotty3000 not sure why tests take 2 hours+ on this pull, but this is the only pull it's happening for... @pyoo47 can you help Ray debug  or point him in the right direction in case it's a CI only thing? May be it's just a bad pull vs code?

Thx. In any case, not merging until it's fixed or it'll essentially break CI.

**Pull request closed without merging**
