### PR TITLE
LPS-94691 SF

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by ealonso** [comment]
Hey @matethurzo,

You made some changes on 59e4e30 and it causes the pagination fails on journal structures, Could you please cc me on pulls that changes something on WCM stuff?

Regards,
Eudaldo.

**Comment by matethurzo** [comment]
sorry :( thanks @jkappler @ealonso

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@jkappler see e6ccd3c

The only time we call setTotal with a line break is if somehow it depends on our call to setResults (that happens sometimes because we call getStart() and getEnd()). But this is not one of those cases.

**Pull request closed without merging**
