### PR TITLE
LPD-16644 | LPD-17797: Improve the performance using the set(UnsafeSupplier) method by replacing any set(<Class>) usage of the setter DTO method

### PR DESCRIPTION
**Pull request by sergiojimcos**
## Motivation
Create a SF rule in order to use the `setUnsafeSupplier` instead of using the `set(<Class>)` DTO methods in liferay-portal. You can check the [gist](https://gist.github.com/ling-alan-huang/94f38f9a8be0892023bad4364bba7c51) where SF rule applies and fails.
cc/ @ling-alan-huang

**JIRA Related Ticket**
https://liferay.atlassian.net/browse/LPD-17797
https://liferay.atlassian.net/browse/LPD-16644

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:reopen

**Comment by sergiojimcos** [comment]
Conflicts solved from here: https://github.com/brianchandotcom/liferay-portal/pull/149075

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/678078c521...650807cac6

**Comment by sergiojimcos** [comment]
PR fixing a commit, sent here: https://github.com/brianchandotcom/liferay-portal/pull/149486

**Pull request closed without merging**
