### PR TITLE
LPS-57089 Let's close the tracker at the proper time. Destroy method is invoked by Spring at the time the Application Context is closed

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4b958491cd...1fdf6651bd

**Comment by brianchandotcom** [comment]
@pavel-savinov Can you help me fix an unstable test? You see how ResourceBundleTrackerTest broke 3 times in one pull, and then magically worked the next retest?

Now, they are breaking randomly in many pulls. It was introduced from this pull.

See https://github.com/brianchandotcom/liferay-portal/pull/28707 on how it's breaking randomly for others now.

 Thx

**Comment by shuyangzhou** [comment]
@pavel-savinov see my fix at https://github.com/brianchandotcom/liferay-portal/pull/28720

Basically it is a bug in ResourceBundleTracker.

Before the fix, we were basically selecting overriding ResourceBundles bases on hashcode ordering, which is totally irrelevant to the registering ordering, now after the fix, whoever is registered the latest will be picked up.

Since ServiceReference class does not have a hashcode, so it is basing on its object identifier which is actually based on memory address. So the order is totally random, with enough runs, we will for sure see both passes and failures.

For the long term solution, we'd better add in service ranking support for ResourceBundleTracker, but for this issue, let's keep things simple, just changing the random selecting logic to select the last registered one.

**Pull request closed without merging**
