### PR TITLE
Lps 59536

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bf441dc748...b6a43f9254

**Comment by brianchandotcom** [comment]
@tinatian can you send a follow up pull and rename Abstract*.java to Base*.java for all the cache stuff? Thx.

**Comment by tinatian** [comment]
OK, I will

**Comment by tinatian** [comment]
Done, please see https://github.com/brianchandotcom/liferay-portal/pull/31668

**Pull request closed without merging**
