### PR TITLE
LPS-73481 Setting 7.1.0 as current version in master

### PR DESCRIPTION
**Pull request by achaparro**
Hi @brianchandotcom,

I have updated all related configuration files manually, I have also tested it and I have been checking that all tests pass with the help of Roberto and Andrea.

However, the latest error that CI shows is something than I can't fix: 

```
Exception in thread "main" com.liferay.source.formatter.SourceMismatchException: 
./modules/private/apps/osb-ldn/osb-ldn-documentation-project/osb-ldn-documentation-project-index-web/src/main/resources/META-INF/friendly-url-routes/routes.xml
 
expected: iendly URL Routes 7.[1.0//EN" "http://www.liferay.com/dtd/liferay-friendly-url-routes_7_1]_0.dtd">
 
 but was:&lt;...iendly URL Routes 7.[0.0//EN" "http://www.liferay.com/dtd/liferay-friendly-url-routes_7_0]_0.dtd">
```

This normal because it has a reference to the old DTD. However the file belongs to the branch 7.0.x-private so can't do anything in this pull to avoid the error.

Could you help me to fix it? Do you think we can push this pull first and then fix other repos?

Thanks.

PS: I think we should consider to create a task to do all these things when we need a new release since it's really difficult to handle all changes and we can make a mistake easily.

Other related pulls:
https://github.com/liferay/com-liferay-dynamic-data-mapping/pull/348
https://github.com/liferay/com-liferay-journal/pull/429

cc/ @SamZiemer @robertoDiaz @Ithildir @CAustin582
@brianwulbern (if this pull is approved you should upgrade your database with the db upgrade client)

### CODE REVIEW

**Comment by achaparro** [comment]
ci:reopen

**Comment by brianwulbern** [comment]
fyi @vicnate5

**Comment by jpince** [comment]
@achaparro I think SF is requiring that this private module also be updated for this change:
https://github.com/liferay/liferay-portal-ee/blob/ee-7.0.x/modules/private/apps/osb-ldn/osb-ldn-documentation-project/osb-ldn-documentation-project-index-web/src/main/resources/META-INF/friendly-url-routes/routes.xml
this is because we are currently pulling the private modules from ee-7.0.x into master pulls. Later today, QA Engineering should be transitioning to pull master-private into master pulls. Since that module doesn't exist, SF should be happy. Can you please resend after that change is made?

**Comment by jpince** [comment]
ci:close

**Comment by achaparro** [comment]
Hi @jpince.

It's really likely that also fails with master-private because there are other fiiles referencing the old dtd like this one:
https://github.com/liferay/liferay-portal-ee/blob/master-private/modules/private/apps/commerce/commerce-cart-service/service.xml

It's was really hard to complete this pull and also rebase it every day (because of the gradle file versions). Please consider to push if the pull is ok since we need this change as soon as possible.

Thanks.

@brianchandotcom

**Comment by brianchandotcom** [comment]
ci:reopen (I'm going to look at this on Monday, assuming QA got it in the master-private change)

**Comment by brianchandotcom** [comment]
@achaparro See bc3adccfd0c64f6a125f2c73ce5069179dcba6c2 in 7.0.x

I think the first step is for us to disable the SF check that forces you to upgrade everything to 7.1.x for the DTD. I think we should allow all of 7.0.x.

@petershin and @hhuijser can you guys relax the SF rule for DTD versions to just be the major version?

Once that is in, @achaparro please fix rebase and resend? Should be a lot easier then. Thx.

**Pull request closed without merging**
