### PR TITLE
LPS-66853

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by jpince** [comment]
@hhuijser basecmis failures are unrelated, thanks for the other fixes.

**Comment by brianchandotcom** [comment]
@hhuijser not merging, I fixed it in d365e092aa22034f2eef9542b4cad6db97abfb64

**Comment by brianchandotcom** [comment]
@hhuijser merged.

**Pull request closed without merging**
