### PR TITLE
LPS-94502

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by jpince** [comment]
@patriciajeanperez @austinchiang @nikki-pru `This is tested with OpenOffice 2.3.x through 4.1.x.`
Seems like a really wide range to support?

**Comment by austinchiang** [comment]
See my comment (here )[https://issues.liferay.com/browse/LPS-94502?focusedCommentId=1791810&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1791810]

**Comment by jrao** [comment]
@jpince Good catch. Sent https://github.com/ChrisKian/liferay-portal/pull/135

**Pull request closed without merging**
