### PR TITLE
LPS-70041

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by daviddotzhang** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@hhuijser BundleSupportAntTest.testInitBundleTarProxyNonProxyHosts has broken twice, only in this pull. Please resend.

**Comment by jpince** [comment]
@hhuijser the test might have an issue, please resend after https://github.com/brianchandotcom/liferay-portal/pull/46260 has been merged.

**Comment by brianchandotcom** [comment]
@hhuijser I just saw  BundleSupportAntTest.testInitBundleTarProxyNonProxyHosts in

https://github.com/brianchandotcom/liferay-portal/pull/46259

I'm merging this pull and asking @shuyangzhou to look into BundleSupportAntTest.testInitBundleTarProxyNonProxyHosts 

Thx.

**Comment by brianchandotcom** [comment]
@hhuijser merged and backported.

**Pull request closed without merging**
