### PR TITLE
LPS-59078 Remove calls to *SeviceUtil in document library

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
thx @hhuijser for the notification about the tests :)

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f7235a2ffc...7c18375fc9

**Pull request closed without merging**
