### PR TITLE
LPS-152781 Fix instances of edited assertDropdownSelection macro

### PR DESCRIPTION
**Pull request by nikki-pru**
https://issues.liferay.com/browse/LPS-152781

This fixes the stable failures on master. See failure for [build #1229 on Slack](https://liferay.slack.com/archives/CLCD3DQLF/p1661820526603649).

The [macro was changed on this commit](https://github.com/brianchandotcom/liferay-portal/commit/3882380e9ed8f0df1351e81c0c7a11c20955c5c2).
cc @MathausC

### CODE REVIEW

**Comment by nikki-pru** [comment]
ci:Reopen

**Comment by nikki-pru** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:test:stable

**Comment by nikki-pru** [comment]
ci:reopen

**Comment by nikki-pru** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
