### PR TITLE
LPS-83992 Implement CDI requirements in Async

### PR DESCRIPTION
**Pull request by ngriffin7a**
@brianchandotcom This PR has already been reviewed by @shuyangzhou -- please review when you get an opportunity. Thanks, Neil

/cc @dantewang @ChiZelin @vsingleton @rotty3000 @stiemannkj1 @vicnate5

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cd1a7f91c7...facc32bf35

**Comment by brianchandotcom** [comment]
Thank you @ngriffin7a !!

**Comment by brianchandotcom** [comment]
Are we complete now for P3?

**Comment by ngriffin7a** [comment]
@brianchandotcom Yes! :) With this PR we are now 100% feature complete for Portlet 3.0!

Still a few things left on the TODO list though:
- Working on getting the V2 and V3 tests in the new Portlet 3.0 TCK passing in CI with reliability (Currently dealing with some Selenium weirdness).
- There is an important CDI bugfix PR that @rotty3000 sent last week:
https://github.com/shuyangzhou/liferay-portal/pull/6994
... but he needs to make some formatting fixes and resend. Gonna need that one backported to 7.1.x after you merge into master.

**Comment by ngriffin7a** [comment]
@brianchandotcom Forgot to mention that I am working on a "spring bean portlet" alternative to CDI. Stay tuned.

**Comment by rotty3000** [comment]
I'll try to complete my part tomorrow.

**Pull request closed without merging**
