### PR TITLE
LPS-90171 update test to new guest.allowed default

### PR DESCRIPTION
**Pull request by csierra**
/cc @topolik @stian-sigvartsen @petershin

### CODE REVIEW

**Comment by jpince** [comment]
@csierra @xbrianlee @joshchong see int test failure, I don't see this at head

**Comment by xbrianlee** [comment]
ci:close

@csierra Looks like we need a test fix here. Can you resubmit the PR with the fix?

@jpince Thanks for the mention!

**Comment by csierra** [comment]
looking into it because it worked in this https://github.com/brianchandotcom/liferay-portal/pull/67663 which contains this one

**Comment by csierra** [comment]
please see https://github.com/brianchandotcom/liferay-portal/pull/67670 @xbrianlee @jpince

**Pull request closed without merging**
