### PR TITLE
LPS-61099

### PR DESCRIPTION
**Pull request by Ithildir**
cc @pyoo47

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:retest

**Comment by pyoo47** [comment]
@Ithildir Thanks Andrea!

**Comment by vicnate5** [comment]
Failures not related to this change.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f04685efec...5c837e51af

**Pull request closed without merging**
