### PR TITLE
LPS-71117 Update Gradle to 3.5.1

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:reopen

**Comment by petershin** [comment]
Will rerun `ci:test` after https://github.com/brianchandotcom/liferay-portal/pull/63194 is merged

**Comment by petershin** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@petershin I ported it to 7.0 and 7.1, can you port it to ee-6.2. and 6.1 (I think we have Gradle wrapper there too)

And liferay-plugins as well. Thx!

**Pull request closed without merging**
