### PR TITLE
LPS-89262 Simplify and introduce exception

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test:change-tracking

**Comment by matethurzo** [comment]
ci:test:relevant

**Comment by matethurzo** [comment]
ci:reopen

**Comment by jpince** [comment]
@yichenroy @michaelhashimoto CI-related failures, but didn't result in generic error

**Comment by yichenroy** [comment]
ci:test:relevant

**Pull request closed without merging**
