### PR TITLE
LPS-69030, LPS-69528, LPS-69760, LRQA-30158 | 7.0.x

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LPS-69030
https://issues.liferay.com/browse/LPS-69528
https://issues.liferay.com/browse/LPS-69760
https://issues.liferay.com/browse/LRQA-30157

**This is 7.0 only**

cc @xbrianlee @jpince

### CODE REVIEW

**Comment by brianwulbern** [comment]
I've quarantined that failing test here: https://github.com/brianchandotcom/liferay-portal/pull/46173

Investigating...

**Comment by jpince** [comment]
@alee8888 @sharonchoi @vicnate5

**Comment by jpince** [comment]
@anthony-chu

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
