### PR TITLE
LPS-93114 Rename FragmentEntryTypeConstants as FragmentTypeConstants

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
cc: @JorgeFerrer

**Comment by brianchandotcom** [comment]
@ealonso @JorgeFerrer can you resend and call the class FragmentEntryConstants?

Why?

See FragmentCollectionContributorTrackerImpl

```
	private static final int[] _SUPPORTED_FRAGMENT_ENTRY_TYPES = {
		FragmentTypeConstants.TYPE_COMPONENT, FragmentTypeConstants.TYPE_SECTION
	};
```

And

The methods in FragmentTypeConstants (your name)

```
	public static final int TYPE_COMPONENT = 1;

	public static final String TYPE_COMPONENT_LABEL = "component";

	public static final int TYPE_SECTION = 0;

	public static final String TYPE_SECTION_LABEL = "section";

	public static int getTypeFromLabel(String label) {
		if (Objects.equals(TYPE_COMPONENT_LABEL, label)) {
			return TYPE_COMPONENT;
		}

		return TYPE_SECTION;
	}

	public static String getTypeLabel(int type) {
		if (type == TYPE_COMPONENT) {
			return TYPE_COMPONENT_LABEL;
		}

		return TYPE_SECTION_LABEL;
	}
```

It just looks so much like our other classes that belong to a model, and that this is that model's type.

If you disagree, then you need to at least make the current usages consistent.

Please resend. Thx.

**Comment by JorgeFerrer** [comment]
Hey Brian,
We believe it's better to say FragmentConstants instead of FragmentEntryConstants because a FragmentEntry represents an entry in the database and precisely that's just one type of fragment (static). The other type (dynamic) doesn't have an associated FragmentEntry.

We will look for other cases where it used to refer to fragment entry constants to make it consistent.

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
