### PR TITLE
Lps 74859 revert

### PR DESCRIPTION
**Pull request by tomwang2011**

### CODE REVIEW

**Comment by tomwang2011** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged.

**Comment by brianchandotcom** [comment]
@matethurzo This is a revert your pull for LPS-74859

**Comment by Preston-Crary** [comment]
@matethurzo, you need to put the constant in another package.  For this package even a minor version change is like a major change because so many modules have classes that extend/implement things in this package.

**Comment by matethurzo** [comment]
@Preston-Crary if you meant putting only the new constant somewhere else, I think fragmentation like this is a bad idea. Adding a constant should not has this kind of effect and this seems to be a case of bad design. the whole class should be somewhere else where it's not causing this effect.
if you meant the latter then take it like i haven't wrote anything :)

**Comment by Preston-Crary** [comment]
@matethurzo I agree, you could deprecate the whole constant class, move it and then add the new string.  You just won't be able to remove the duplication by extending the new constant class.  You can remove the whole class after you remove the usages by adding the old constant class to the portal-kernel-compat, that way it's still there in the jar but isn't in the source code.

The design is bad but we can't fix it without a major version change for portal-kernel.  I'm collecting a list of changes that we can make in order to reduce this problem so we can do all of them at once when we are ready.  I think we won't be ready for a long time though.

Hope that helps

**Pull request closed without merging**
