### PR TITLE
COMMERCE-345 Error handling in tLiferayOutput component

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
https://issues.liferay.com/browse/COMMERCE-345

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fa0d4a8963...90a469cb93

**Comment by brianchandotcom** [comment]
@ZoltanTakacs see 90a469c and 4de98f8 thx.

**Comment by ZoltanTakacs** [comment]
Thank you! I'll make more attention for the wording next time :)

**Pull request closed without merging**
