### PR TITLE
master-lps-65636

### PR DESCRIPTION
**Pull request by michaelhashimoto**
@hhuijser 

Here's the source formats you mention in this pull request:
https://github.com/brianchandotcom/liferay-portal/pull/39458

I also included a revert of https://github.com/brianchandotcom/liferay-portal/commit/e28ad7b35e72506b8b9c64e8386e08e80b75868a.

Thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@michaelhashimoto backport?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/14df678e87...1d84c921cb

**Comment by hhuijser** [comment]
Thanks @michaelhashimoto

**Comment by michaelhashimoto** [comment]
Backported here:
https://github.com/brianchandotcom/liferay-portal-ee/pull/13153
https://github.com/brianchandotcom/liferay-portal-ee/pull/13154
https://github.com/brianchandotcom/liferay-portal-ee/pull/13155
https://github.com/brianchandotcom/liferay-portal-ee/pull/13156

@brianchandotcom @hhuijser

**Pull request closed without merging**
