### PR TITLE
Lps 158311 8 4

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@dantewang I'm confused, are we sending 1 or more than 1?

```
	private void _sendUserNotification(
			BackgroundTask backgroundTask, long userId)
		throws PortalException {

		_userNotificationEventLocalService.sendUserNotificationEvents(
			userId, "BackgroundTask",
			UserNotificationDeliveryConstants.TYPE_WEBSITE, false,
			JSONUtil.put(
				"name", backgroundTask.getName()
			).put(
				"taskExecutorClassName",
				backgroundTask.getTaskExecutorClassName()
			));
	}
```

One is singular and the other is plural. Thx.

@shuyangzhou fyi

**Comment by dantewang** [comment]
ci:reopen

**Comment by dantewang** [comment]
@brianchandotcom Reopen based on the discussion:

> I'm sending 1, but that LocalService only has `sendUserNotificationEvents` methods.. And those methods are also creating and adding 1 `UserNotificationEvent` in each invocation.

```

	@Override
	public UserNotificationEvent sendUserNotificationEvents(
			long userId, String portletId, int deliveryType, boolean delivered,
			boolean actionRequired, JSONObject notificationEventJSONObject)
		throws PortalException {

		NotificationEvent notificationEvent =
			NotificationEventFactoryUtil.createNotificationEvent(
				System.currentTimeMillis(), portletId,
				notificationEventJSONObject);

		notificationEvent.setDeliveryType(deliveryType);

		UserNotificationEvent userNotificationEvent = addUserNotificationEvent(
			userId, delivered, actionRequired, notificationEvent);

		if (deliveryType == UserNotificationDeliveryConstants.TYPE_PUSH) {
			sendPushNotification(notificationEvent);
		}

		return userNotificationEvent;
	}
```

**Comment by dantewang** [comment]
cc @shuyangzhou

**Comment by rolandpakai** [comment]
Hi @shuyangzhou

could you please review this PR?

Thanks, Roland

**Comment by NimrodPapp** [comment]
Hi @brianchandotcom ,

Could you please check this PR? According to Dante Wang it got reopened based on your discussion.

Thank you,
Nimród

**Comment by brianchandotcom** [comment]
@dantewang 

1.) I think we should merge BackgroundTaskQueuingMessageListener, RemoveOnCompletionBackgroundTaskStatusMessageListener, and SendUserNotificationEventOnFailedBackgroundTaskStatusMessageListener into 1 listener.

We're adding unnecessary complexity.

2.) There's no portlet called BackgroundTask

```
/**
 * @author Dante Wang
 */
@Component(
	immediate = true, property = "javax.portlet.name=BackgroundTask",
	service = UserNotificationHandler.class
```

I'm weary of adding a new pattern.

Please resend on top of https://github.com/dantewang/liferay-portal/pull/2251

@NimrodPapp fyi.

**Pull request closed without merging**
