### PR TITLE
LPS-72077 Packageinfo

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by ealonso** [comment]
ci:retest

**Comment by jpince** [comment]
@ealonso consistent failures that I don't see in other pulls, looks like a semver issue `Unresolved requirement: Import-Package: com.liferay.portal.kernel.model; version="[1.0.0,1.1.0)"`
```
    [junit] 18:06:43,800 ERROR [localhost-startStop-1][ModuleFrameworkImpl:1503] Unable to start bundle com.liferay.portal.background.task.api
    [junit] org.osgi.framework.BundleException: Could not resolve module: com.liferay.portal.background.task.api [41]
    [junit]   Unresolved requirement: Import-Package: com.liferay.portal.kernel.model; version="[1.0.0,1.1.0)"
```
```
    [junit] 18:06:45,138 ERROR [localhost-startStop-1][ModuleFrameworkImpl:1503] Unable to start bundle com.liferay.portal.lock.api
    [junit] org.osgi.framework.BundleException: Could not resolve module: com.liferay.portal.lock.api [70]
    [junit]   Unresolved requirement: Import-Package: com.liferay.portal.kernel.model; version="[1.0.0,1.1.0)"
```
```
    [junit] 18:06:45,461 WARN  [fileinstall-/opt/dev/projects/github/liferay-portal/bundles/osgi/modules][org_apache_felix_fileinstall:103] Error while starting bundle: file:/opt/dev/projects/github/liferay-portal/bundles/osgi/modules/com.liferay.dynamic.data.mapping.io.jar 
    [junit] org.osgi.framework.BundleException: Could not resolve module: com.liferay.dynamic.data.mapping.io [258]
    [junit]   Unresolved requirement: Import-Package: com.liferay.dynamic.data.mapping.form.field.type; version="[1.0.0,2.0.0)"
    [junit]     -> Export-Package: com.liferay.dynamic.data.mapping.form.field.type; bundle-symbolic-name="com.liferay.dynamic.data.mapping.form.field.type"; bundle-version="2.1.0"; version="1.1.0"; uses:="com.liferay.dynamic.data.mapping.annotations,com.liferay.dynamic.data.mapping.model,com.liferay.dynamic.data.mapping.render,com.liferay.dynamic.data.mapping.storage,com.liferay.portal.kernel.exception,com.liferay.portal.kernel.template,javax.servlet.http"
    [junit]        com.liferay.dynamic.data.mapping.form.field.type [254]
    [junit]          Unresolved requirement: Import-Package: com.liferay.dynamic.data.mapping.annotations; version="[1.2.0,2.0.0)"
    [junit]            -> Export-Package: com.liferay.dynamic.data.mapping.annotations; bundle-symbolic-name="com.liferay.dynamic.data.mapping.api"; bundle-version="3.6.0"; version="1.2.0"
    [junit]               com.liferay.dynamic.data.mapping.api [246]
    [junit]                 Unresolved requirement: Import-Package: com.liferay.portal.kernel.model; version="[1.0.0,1.1.0)"
```
```
    [junit] 18:06:45,229 ERROR [localhost-startStop-1][ModuleFrameworkImpl:1503] Unable to start bundle com.liferay.portal.mobile.device.recognition.api
    [junit] org.osgi.framework.BundleException: Could not resolve module: com.liferay.portal.mobile.device.recognition.api [73]
    [junit]   Unresolved requirement: Import-Package: com.liferay.mobile.device.rules.action; version="[1.0.0,2.0.0)"
    [junit]     -> Export-Package: com.liferay.mobile.device.rules.action; bundle-symbolic-name="com.liferay.mobile.device.rules.api"; bundle-version="2.0.3"; version="1.0.1"; uses:="com.liferay.mobile.device.rules.model,com.liferay.portal.kernel.exception,javax.servlet.http"
    [junit]        com.liferay.mobile.device.rules.api [427]
    [junit]          Unresolved requirement: Import-Package: com.liferay.portal.kernel.model; version="[1.0.0,1.1.0)"
```
https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/106933/console

**Comment by jpince** [comment]
ci:close

**Pull request closed without merging**
