### PR TITLE
Lps 64225

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
CC @mhan810 @BrettSwaim @Preston-Crary

**Comment by sharonchoi** [comment]
@brianchiu

**Comment by sharonchoi** [comment]
Investigating, seems like Bookmarks tests are failing because Bookmarks portlet is missing from the Product panel.

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by sharonchoi** [comment]
@brianchiu, there are some upgrade tests registering as test failures, but there are only warnings in the logs.

**Comment by brianchiu** [comment]
Looking

**Comment by brianchiu** [comment]
@shuyangzhou 
Those upgrade tests failed because this error showed up post-upgrade when hitting localhost (just the welcome page).

```
     [exec] Loading jar:file:/opt/dev/projects/github/liferay-portal/bundles/tomcat-8.0.32/webapps/ROOT/WEB-INF/lib/portal-impl.jar!/system.properties
     [exec] Loading file:/opt/dev/projects/github/liferay-portal/bundles/tomcat-8.0.32/webapps/ROOT/WEB-INF/classes/system-ext.properties
     [exec] Loading jar:file:/opt/dev/projects/github/liferay-portal/bundles/tomcat-8.0.32/webapps/ROOT/WEB-INF/lib/portal-impl.jar!/portal.properties
     [exec] Loading file:/opt/dev/projects/github/liferay-portal/bundles/tomcat-8.0.32/webapps/ROOT/WEB-INF/classes/portal-ext.properties
     [exec] 22:45:53,042 ERROR [localhost-startStop-1][SecurityManagerUtil:60] Plugin security management is not enabled. Enable a security manager, then restart.
     [exec] 22:45:54,107 INFO  [localhost-startStop-1][HikariDataSource:93] HikariPool-0 - is starting.
     [exec] 22:45:54,450 INFO  [localhost-startStop-1][DialectDetector:75] Determine dialect for MySQL 5.6
     [exec] 22:45:54,465 INFO  [localhost-startStop-1][DialectDetector:148] Found dialect org.hibernate.dialect.MySQLDialect
     [exec] 22:45:55,553 INFO  [localhost-startStop-1][HikariDataSource:93] HikariPool-1 - is starting.
     [exec] 22:45:56,060 ERROR [Framework Event Dispatcher: Equinox Container: 20731482-36ea-0015-141a-db25612ec244][com_liferay_journal_terms_of_use:96] FrameworkEvent ERROR 
     [exec] org.osgi.framework.BundleException: Could not resolve module: com.liferay.journal.terms.of.use [151]
     [exec]   Unresolved requirement: Import-Package: com.liferay.portal.kernel.util; version="[7.0.0,7.1.0)"
     [exec] 
     [exec] 	at org.eclipse.osgi.container.Module.start(Module.java:429)
     [exec] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
     [exec] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
     [exec] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
     [exec] 	at org.eclipse.osgi.container.SystemModule.startWorker(SystemModule.java:242)
     [exec] 	at org.eclipse.osgi.container.Module.doStart(Module.java:566)
     [exec] 	at org.eclipse.osgi.container.Module.start(Module.java:434)
     [exec] 	at org.eclipse.osgi.container.SystemModule.start(SystemModule.java:172)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:421)
     [exec] 	at org.eclipse.osgi.launch.Equinox.start(Equinox.java:115)
     [exec] 	at com.liferay.portal.bootstrap.ModuleFrameworkImpl.startFramework(ModuleFrameworkImpl.java:390)
     [exec] 	at com.liferay.portal.module.framework.ModuleFrameworkUtilAdapter.startFramework(ModuleFrameworkUtilAdapter.java:93)
     [exec] 	at com.liferay.portal.spring.context.PortalContextLoaderListener.contextInitialized(PortalContextLoaderListener.java:256)
     [exec] 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812)
     [exec] 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255)
     [exec] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
     [exec] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
     [exec] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
     [exec] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
     [exec] 	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:585)
     [exec] 	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1794)
     [exec] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
     [exec] 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
     [exec] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [exec] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [exec] 	at java.lang.Thread.run(Thread.java:745)
     [exec] 14-Mar-2016 22:46:01.973 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log Initializing Spring root WebApplicationContext
     [exec] 22:46:15,343 INFO  [localhost-startStop-1][node:137] [Heimdall] version[2.2.0], pid[31700], build[8ff36d1/2016-01-27T13:32:39Z]
     [exec] 22:46:15,344 INFO  [localhost-startStop-1][node:139] [Heimdall] initializing ...
```

**Comment by brianchandotcom** [comment]
@shuyangzhou please resend this one as well? Broken tests. Thx.

**Comment by brianchiu** [comment]
CC @michaelhashimoto @pyoo47

Build failure on one of the functional test axes.
https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=3,label_exp=!master/24039/console

Snippet of the error:
```
deploy:
      [bnd] 1 ERRORS
      [bnd]  Failed to download plugin /opt/dev/projects/github/liferay-portal/util-bridges/../.bnd/ant-baseline-cache/com.liferay.util.bridges-2.0.0.jar from https://repository.liferay.com/nexus/content/repositories/liferay-releases-ce/com/liferay/portal/com.liferay.util.bridges/2.0.0/com.liferay.util.bridges-2.0.0.jar, error java.io.IOException: Server returned HTTP response code: 502 for URL: https://repository.liferay.com/nexus/content/repositories/liferay-releases-ce/com/liferay/portal/com.liferay.util.bridges/2.0.0/com.liferay.util.bridges-2.0.0.jar
      [bnd] /opt/dev/projects/github/liferay-portal/util-bridges/bnd.bnd: bnd failed
```

**Comment by brianchiu** [comment]
@sharonchoi 
Yep. The upgrade tests have server console assertions turned on (same with portal smoke).

**Pull request closed without merging**
