### PR TITLE
LPS-93427 Convert entries from legacy Instance Settings to be individual entries in Instance Settings

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-93427](https://issues.liferay.com/browse/LPS-93427).<br><br>This pull explodes the legacy Portal Settings form navigator into distinct entries inside the new Instance Settings portlet. Functional test fixes are included.<br><br>/cc @pei-jung @stsquared99 @alee8888 @ChrisKian @xbrianlee @Sharryxue

### CODE REVIEW

**Comment by drewbrokke** [comment]
cc @dejuknow

**Comment by drewbrokke** [comment]
Resent as https://github.com/brianchandotcom/liferay-portal/pull/71490

**Comment by brianchandotcom** [comment]
@drewbrokke please resend on top of https://github.com/drewbrokke/liferay-portal/pull/796

I see CMD_UPDATE_AUTH in 2 files.

WebKeys is reserved for request and session attribute keys only.

**Comment by drewbrokke** [comment]
Rename to `*Constants` instead?

**Pull request closed without merging**
