### PR TITLE
LPS-88284 Source Formatting

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test:staging

**Comment by matethurzo** [comment]
@jpince when it comes to staging related codes, the staging suite should run. i just caught a regression today with staging which was not indicated with relevant.
@brianchandotcom we are working on making the staging suite green once we achieve that, we want to keep it green, if someone will break it we will roll the change back

**Comment by jpince** [comment]
@matethurzo CI doesn't currently have this feature, but I agree that it should run under relevant. Can you  or @kmaria write an LRQA ticket under the `Engineering > Pull Request Tester` component? It would probably help to provide a path similar to the one in your custom test suites (e.g. [test.batch.class.names.includes[staging]](https://github.com/liferay/liferay-portal/blob/master/test.properties#L1688)) to identify what is "staging related code".

**Comment by matethurzo** [comment]
@jpince what i meant is that I already asked the leads to run the staging suite whenever they send a staging related pull. I know the PR tester doesn't have this feature yet, so this is our best shot so far.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/81bc9215de...7bb08d64ce

**Pull request closed without merging**
