### PR TITLE
LPS-103070 Copyright should not be added to those files, since those files are a piece of code that is injected in the page

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/dad597b43d...38b1a31126

**Comment by brianchandotcom** [comment]
@jbalsas @wincent fyi

not sure if your next run will undo change by @ealonso

**Comment by wincent** [comment]
Yeah, we just need to add these to the top-level `.eslintignore`. We actually chatted about this when we rolled out ESLint and knew that this would come up sooner or later.

**Comment by wincent** [comment]
Sent https://github.com/brianchandotcom/liferay-portal/pull/79477 to update the `.eslintignore`.

**Pull request closed without merging**
