### PR TITLE
LPS-104786 app.properties for Liferay Depot

### PR DESCRIPTION
**Pull request by carolmoreschi**

### CODE REVIEW

**Comment by carolmoreschi** [comment]
@jpince

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c19f871348...dcc8f99811

**Comment by brianchandotcom** [comment]
@carolmoreschi what about modules/apps/depot? I only see the DXP one.

**Comment by brianchandotcom** [comment]
@carolmoreschi I reverted this.. please resend with apps and dxp/apps thx

**Pull request closed without merging**
