### PR TITLE
[TS] LPS-167473

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-167473

@jcampoy

### CODE REVIEW

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/10160

:heavy_check_mark: ci:test:stable - 25 out of 25 jobs passed
:x: ci:test:relevant - 124 out of 169 jobs passed in 2 hours 29 minutes

**Comment by ozysouza** [comment]
ci:reopen

**Comment by ozysouza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2917c4eac2...5386fa96ac

**Pull request closed without merging**
