### PR TITLE
LPS-80387 Use prepared statement instead of runSQL

### PR DESCRIPTION
**Pull request by BryanEngler**
Follow up fix for https://github.com/brianchandotcom/liferay-portal/pull/60689

https://issues.liferay.com/browse/LPS-80387

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test

**Comment by arboliveira** [comment]
@xbrianlee `7.1-MustFix` -- this is actually a Blocker for Sybase.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by jpince** [comment]
Pushed upstream: https://github.com/liferay/liferay-portal/commit/9247eb9d908bfebe101448bcb8e85d2811c1456c

**Pull request closed without merging**
