### PR TITLE
LPS-147146 Update mapping tables to have companyId Not Nul

### PR DESCRIPTION
**Pull request by achaparro**
LPS-147146

### CODE REVIEW

**Comment by achaparro** [comment]
ci:reopen

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:reopen

**Comment by achaparro** [comment]
cc/ @luisortiz89

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/45b627042f...ecdc9241f3

**Pull request closed without merging**
