### PR TITLE
LPS-57254 LPS-56486 Rename "comments" to "comment"

### PR DESCRIPTION
**Pull request by adolfopa**
@brianchandotcom This PR contains two issues: LPS-57254 and LPS-56486. I'm sending them together to avoid rebase conflicts.

There are some references to "comments" in comment-comments-web, but they refer to the "Comments" portlet, and not the "comment" category or model, so I've left them untouched.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:retest

**Comment by adolfopa** [comment]
ci:retest

**Comment by adolfopa** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@adolfopa sorry, another rebase needed. I'll do yours earlier tomorrow. But one thing that I found odd was the comment-comments-web and the commet-comments-manager... I need to sit and think on that one.

Also, miguel sent me this https://github.com/brianchandotcom/liferay-portal/pull/28419

Which will now allow me to simply annotate a class and it'll be exposed via jsonws... not sure if that means we won't need the jaxws part... please resend for tomorrow and I'll review it earlier in the day. Sorry!

**Pull request closed without merging**
