### PR TITLE
LPS-76673

### PR DESCRIPTION
**Pull request by petershin**
Fix packageinfo<br /><br />@lanceji92674957

### CODE REVIEW

**Comment by petershin** [comment]
ci:test

**Comment by lanceji92674957** [comment]
@petershin thanks!

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
@petershin can you make the SF more message more clear in the future, or auto fix it via SF? Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6128c86902...b864808051

**Comment by petershin** [comment]
@brianchandotcom - Sent a fix to automatically delete bad packageinfo files: https://github.com/hhuijser/liferay-portal/pull/3133

**Pull request closed without merging**
