### PR TITLE
LPS-53627 create taglibs to select and render asset addons #pingpong

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Well, I better play #pingpong. On it right away.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4e6d6c149a...f44e9781a0

**Comment by brianchandotcom** [comment]
#pong @juliocamarero @jbalsas can you guys see my changes in upstream, and make a change I requested in 1132aa81ed903a4a0cdc399c2ceb60210d9a8a4f

Thx!

**Comment by juliocamarero** [comment]
Thanks a lot Brian! And sorry about the mistakes. We will send the js file tomorrow.

**Comment by brianchandotcom** [comment]
No problem, we're a team! Sorry it took so long to get it in as well. Hopefully, we can all speed this up going fwd. Thx @jbalsas @juliocamarero for all the help!

**Pull request closed without merging**
