### PR TITLE
LPS-102655 | LPS-103338 Apply

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fcd73500c7...e2cb57134a

**Comment by brianchandotcom** [comment]
@inacionery @rafaprax see e2cb57134aeb76ec2f760a264f9b5fd10c9315d0

**Comment by inacionery** [comment]
@brianchandotcom, thanks!

**Pull request closed without merging**
