### PR TITLE
LPS-108724 Extract JSON Schema validation to shared module

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
//cc @ealonso

**Comment by ruben-pulido** [comment]
//cc @jkappler

**Comment by brianchandotcom** [comment]
Yikes... please  resend. SF issue. Thx.

**Comment by brianchandotcom** [comment]
@ruben-pulido exporting should be allowed

```
Bundle-Name: Liferay Petra Mail
Bundle-SymbolicName: com.liferay.petra.mail
Bundle-Version: 4.0.2
Export-Package: com.liferay.petra.mail
```

So you must be exporting it differently. Please resend.

**Comment by jkappler** [comment]
Just started reviewing :)

**Pull request closed without merging**
