### PR TITLE
LPS-98322 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-98322

### CODE REVIEW

**Comment by kyle-miho** [comment]
Test failures were unrelated

**Comment by brianchandotcom** [comment]
@shuyangzhou see

```
!MESSAGE bundle com.liferay.asset.service:4.0.0 (395)[com.liferay.asset.service.persistence.impl.AssetEntryUsagePersistenceImpl(1693)] : The setSessionFactory method has thrown an exception
!STACK 0
java.util.ConcurrentModificationException
at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
at java.util.LinkedList$ListItr.next(LinkedList.java:888)
at org.apache.commons.configuration.CompositeConfiguration.getProperty(CompositeConfiguration.java:259)
at com.liferay.portal.configuration.ClassLoaderAggregateProperties.getProperty(ClassLoaderAggregateProperties.java:108)
at org.apache.commons.configuration.AbstractConfiguration.resolveContainerStore(AbstractConfiguration.java:1171)
at org.apache.commons.configuration.AbstractConfiguration.getString(AbstractConfiguration.java:1038)
at com.liferay.portal.configuration.ClassLoaderAggregateProperties.getString(ClassLoaderAggregateProperties.java:137)
at com.liferay.portal.configuration.ConfigurationImpl.get(ConfigurationImpl.java:189)
at com.liferay.portal.util.P...
```

Not sure if that's related to your concurrency changes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/defa9e59ff...206aeab386

**Comment by shuyangzhou** [comment]
@brianchandotcom this is a long exist issue, which should have been fixed by https://github.com/brianchandotcom/liferay-portal/pull/78446
@vicnate5 please confirm, when pull ran, the fix should not have been merged yet.

**Comment by vicnate5** [comment]
Confirmed. This PR test did not run with the fix included (78f33d929ebfd261784e7e32b3db51f5bf80312d)

**Pull request closed without merging**
