### PR TITLE
LRQA-60824, LRQA-60828, LRQA-60829 | master

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://issues.liferay.com/browse/LRQA-60824
https://issues.liferay.com/browse/LRQA-60828
https://issues.liferay.com/browse/LRQA-60829

Unquarantine tests, no need to run ci:forward.

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:reopen

**Comment by JoyceWang08211** [comment]
ci:test:sf

**Comment by JoyceWang08211** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/289a2a639d...7140e7629d

**Pull request closed without merging**
