### PR TITLE
LPS-88430 plid set to the correct portletDataContext

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test:staging

**Comment by matethurzo** [comment]
test failure seems unrelated @jpince can you confirm?

**Comment by jpince** [comment]
@matethurzo can't see how it could be, since Zoltan just made a change to an int test. That test has consistently passed in upstream for months, though, so really not sure why it failed. @kmaria can you look next week to make sure `LocalFile.StagingUsecaseWithOrganization#StagingOrganizations` is still passing in upstream?

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
