### PR TITLE
LPS-175513 Remove the property "verify.process.name" from verify processes and use bundleSymbolicName instead

### PR DESCRIPTION
**Pull request by susanchen3**
Manually forwarded as test failures are not related :heavy_check_mark: 

Original PR here: https://github.com/liferay-uniform/liferay-portal/pull/982

https://issues.liferay.com/browse/LPS-175513

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/efd565281e...03081bce22

**Comment by brianchandotcom** [comment]
@achaparro @susanchen3 please check my changes in 03081bce (I didn't test them)

**Comment by brianchandotcom** [comment]
@achaparro @susanchen3 longer hash is 03081bce228be39bcfb0b7c31a2712932f87b69f

**Pull request closed without merging**
