### PR TITLE
LPS-126465 [Data Engine Team] Create stubs for missing automation

### PR DESCRIPTION
**Pull request by emanuelfisilva**
[LPS-126465](https://issues.liferay.com/browse/LPS-126465) Creating stubs for Data Engine automation

### CODE REVIEW

**Comment by emanuelfisilva** [comment]
ci:reopen

**Comment by nikki-pru** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5e27aef338...5157208ac8

**Pull request closed without merging**
