### PR TITLE
LPS-149258

### PR DESCRIPTION
**Pull request by tinatian**
FYI @shuyangzhou

### CODE REVIEW

**Comment by tinatian** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7a35ee3698...165e40f407

**Comment by brianchandotcom** [comment]
Very nice @jeffwu0724

**Comment by jeffwu0724** [comment]
Thank you sir! :) @brianchandotcom

**Pull request closed without merging**
