### PR TITLE
LPS-72705

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by jpince** [comment]
ci:retest

**Comment by petershin** [comment]
ci:retest

**Comment by jpince** [comment]
ci:stop

**Comment by jpince** [comment]
SF failure is unrelated

**Comment by petershin** [comment]
@jpince: Is it ok to reopen this pull?

**Comment by jpince** [comment]
ci:stop

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
@petershin sorry, forgot that it was still closed. yes, this pull should be fine.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bf02775ec8...e435e82a93

**Pull request closed without merging**
