### PR TITLE
LPS-64908 fix duplicated success messages when deleting pages

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:stop

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
cc @jbalsas

**Comment by brianchandotcom** [comment]
@juliocamarero Still has those 4 test errors. Please resend.

**Comment by evannagayama** [comment]
@kenjiheigel portal instance setup issue?

**Pull request closed without merging**
