### PR TITLE
LPS-135156 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-135156

This is only for master.

@lfbesada

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure task is unrelated to this PR should be fixed by https://github.com/brianchandotcom/liferay-portal/commit/6cefec189c7a789f1d3f18fd695490a7fc6c3424
See https://github.com/liferay-echo/liferay-portal/pull/5830
❌ ci:test:stable - 9 out of 10 jobs passed
❌ ci:test:relevant - 21 out of 23 jobs passed in 1 hour 45 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3786ceb25d...df52cdb43e

**Comment by brianchandotcom** [comment]
@lfbesada see 143b7ea1612645170e06e0f0788f37fb30332439

**Pull request closed without merging**
