### PR TITLE
LPS-81537 Fix build

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:test

**Comment by izaera** [comment]
ci:reopen

**Comment by izaera** [comment]
@brianchandotcom this is failing as yesterday but for different tests, so I'll keep it open to see what happens (maybe today they are failures in common with upstream...)

**Comment by jpince** [comment]
@izaera everything looks good except JBoss smoke, there's a startup error. It's most likely a fluke (I'm really not sure), so if you don't think you caused this, it's probably fine.

```     [exec] [0m[0m15:00:21,935 INFO  [javax.enterprise.resource.webcontainer.jsf.config] (ServerService Thread Pool -- 85) Initializing Mojarra 2.2.13.SP4  for context ''
     [exec] [0m[31m15:02:56,778 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0348: Timeout after [480] seconds waiting for service container stability. Operation will roll back. Step that first updated the service container was 'add' at address '[
     [exec]     ("core-service" => "management"),
     [exec]     ("management-interface" => "http-interface")
     [exec] ]'
     [exec] [0m[31m15:03:01,808 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0190: Step handler org.jboss.as.server.DeployerChainAddHandler$FinalRuntimeStepHandler@5895d87b for operation add-deployer-chains at address [] failed handling operation rollback -- java.util.concurrent.TimeoutException: java.util.concurrent.TimeoutException
     [exec] 	at org.jboss.as.controller.OperationContextImpl.waitForRemovals(OperationContextImpl.java:522)
```
https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/219136/AXIS_VARIABLE=0,label_exp=!master/console

**Comment by brianchandotcom** [comment]
@jpince can you work to with @shuyangzhou to see what's going on with integration-* Thx

**Comment by brianchandotcom** [comment]
@izaera merged.

**Comment by shuyangzhou** [comment]
Those WikiNodeUADDisplayTest failures are real ones, we can find out what caused it.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/6287

**Comment by izaera** [comment]
Thx guys :-)

**Pull request closed without merging**
