### PR TITLE
LPS-68336 Manual revert of LPS-64206

### PR DESCRIPTION
**Pull request by marcellustavares**
Hi Brian, this is the backport for #44042

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by vicnate5** [comment]
This is for 7.0.x Some of the backend tests are broken but they are not related to this pull.

**Comment by brianchandotcom** [comment]
@marcellustavares too many things broken with this. Please resend. Thx.

**Comment by marcellustavares** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
