### PR TITLE
LPS-53734 UserImporterUtilTest Integration point test

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@shuyangzhou  I think this is broken from the CI?

**Comment by brianchandotcom** [comment]
@rotty3000 @peterfellwock 

See fix from @shuyangzhou in https://github.com/brianchandotcom/liferay-portal/pull/24985

It's quite how one bug is exposed by a test that has nothing to do with it. Good job everyone.

**Comment by brianchandotcom** [comment]
@peterfellwock please see my formatting changes in upstream. Lots of them :)

**Pull request closed without merging**
