### PR TITLE
LPS-51694 importing expando attributes

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:retest

**Comment by inacionery** [comment]
ci:reopen

**Comment by brandizzi** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cbca53e4c5...85a69bd868

**Comment by brianchandotcom** [comment]
@brandizzi please review my changes in upstream. Thx.

**Pull request closed without merging**
