### PR TITLE
LPS-56019

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
ci:retest

**Comment by mhan810** [comment]
@brianchandotcom the test all report green but we had to kill the build; might just be CI failure

**Comment by brianchandotcom** [comment]
@mhan810 I merged this in, but we have a bunch of deprecated code now.

See upstream for my changes. Can you also fix

1.) FacetedSearcher using addFacetClause 

2.) BaseRelatedEntryIndexer using

```
indexer.postProcessContextQuery(relatedQuery, searchContext);

			for (IndexerPostProcessor indexerPostProcessor :
					indexer.getIndexerPostProcessors()) {

				indexerPostProcessor.postProcessContextQuery(
					relatedQuery, searchContext);
			}
```

All of these are giving me warnings. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8ccca2e712...07e32b6f23

**Comment by mhan810** [comment]
I know, there's a lot more code coming.  This was just part 1 of a series



*From:* Brian Chan [mailto:notifications@github.com]
*Sent:* Tuesday, June 2, 2015 3:14 PM
*To:* brianchandotcom/liferay-portal
*Cc:* Michael Han
*Subject:* Re: [liferay-portal] LPS-56019 (#27007)



@mhan810 <https://github.com/mhan810> I merged this in, but we have a bunch
of deprecated code now.

See upstream for my changes. Can you also fix

1.) FacetedSearcher using addFacetClause

2.) BaseRelatedEntryIndexer using

indexer.postProcessContextQuery(relatedQuery, searchContext);



            for (IndexerPostProcessor indexerPostProcessor :

                    indexer.getIndexerPostProcessors()) {



                indexerPostProcessor.postProcessContextQuery(

                    relatedQuery, searchContext);

            }

All of these are giving me warnings. Thx.

--
Reply to this email directly or view it on GitHub
<https://github.com/brianchandotcom/liferay-portal/pull/27007#issuecomment-108083375>
.

**Pull request closed without merging**
