### PR TITLE
LPS-89658 StructuredContents and ContentStructures: List with pagination

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e8686016d5...3dfb4aaba0

**Comment by brianchandotcom** [comment]
Good job guys. We're still working on getting properties and more stuff generated...

@petershin fyi

**Pull request closed without merging**
