### PR TITLE
LPS-88183 persistence=false

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jeyvison  I don't know if this will help you with Data Engine, but I have a feeling it might. See this new flag.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/dcb5ae9ef9...4df894e687

**Comment by jeyvison** [comment]
thanks @brianchandotcom !

**Comment by Preston-Crary** [comment]
@jeyvison this is a new feature so if you're working with it and run into any edge cases I didn't cover please email me and I'll try to resolve them quickly.

**Comment by jeyvison** [comment]
Sure @Preston-Crary , Thanks a lot :)

**Pull request closed without merging**
