### PR TITLE
LPS-67079

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@hhuijser lots of errors? Please resend. Thx.

**Comment by hhuijser** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
@hhuijser, at first glance, looks like there's something wrong with the page layout:
image

Try adding a page, and navigating to the page (not through the Product Menu)

**Comment by hhuijser** [comment]
@Preston-Crary 
Do you have time to look into this?

**Comment by Preston-Crary** [comment]
@hhuijser yes, I'll look into it.

**Comment by Preston-Crary** [comment]
Please see https://github.com/hhuijser/liferay-portal/pull/2684

**Pull request closed without merging**
