### PR TITLE
LPS-83241 Remove table column styles, use Clay 2 table helper classes instead

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @brianchandotcom,

This is a big cross-cutting PR to fix some problems with tables across the product. It specially targets japanese (and similar locales) layout issues and small screen sizes.

We've run tests and collected most the involved teams go ahead at https://github.com/jbalsas/liferay-portal/pull/1455#issuecomment-422716410

Thanks!

PS: Awesome work, @pat270! 👏

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/25640d22e8...11a29c2a0e

**Comment by brianchandotcom** [comment]
@jbalsas Can you send a backport to support for 7.1.x(like our normal support workflow). This pull is big and has conflicts with 7.1.x already.

@jhendley @liferay @zsoltbalogh FYI.

Merged into master only.

**Comment by brianchandotcom** [comment]
@pat270 actually, can you do the backport? See my comment above. Thx.

**Pull request closed without merging**
