### PR TITLE
LPD-25643 Add draft object relationship when importing relationship object field

### PR DESCRIPTION
**Pull request by carolmariaabb**
Unrelated failures https://github.com/liferay-objects/liferay-portal/pull/3342#issuecomment-2109229410

### CODE REVIEW

**Comment by carolmariaabb** [comment]
I'm working on the integration test.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0e0f27f88e...df27c949b1

**Comment by marco-leo** [comment]
@carolmariaabb we should send the PR with the Integration tests

**Comment by marco-leo** [comment]
@carolmariaabb we should send the PR with the Integration tests

**Pull request closed without merging**
