### PR TITLE
LPS-157770 Sort languages alphabetically

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
FWD: https://github.com/fortunatomaldonado/liferay-portal/pull/31

Let me know if there are any questions or comments about this.

[LPS-157770](https://issues.liferay.com/browse/LPS-157770) Sort languages alphabetically before adding to Language Override list.

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:reopen

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2853469fde...7821b0de35

**Comment by brianchandotcom** [comment]
@fortunatomaldonado see bbf13ff9246c8a098ce848e5fe42f2cd8025a9a8 and  7821b0de355abf9ca2c00467be395753708f5ded

**Pull request closed without merging**
