### PR TITLE
LPS-84312 Removed unneeded redirect value

### PR DESCRIPTION
**Pull request by drewbrokke**

### CODE REVIEW

**Comment by drewbrokke** [comment]
cc @pei-jung

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@drewbrokke @stsquared99 see cdfc5eb26a3ef70449d93c3436cae6196a5fd1ea thx.

**Pull request closed without merging**
