### PR TITLE
LPS-155489 | master

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:reopen

**Comment by adolfopa** [comment]
Forwarded from https://github.com/liferay-lima/liferay-portal/pull/3272

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d68a41a378...22afd231fb

**Comment by brianchandotcom** [comment]
@adolfopa can you send me a follow up PR and sort

```
	public DefaultDLEditFileEntryDisplayContext(
		HttpServletRequest httpServletRequest,
		HttpServletResponse httpServletResponse,
		DLFileEntryType dlFileEntryType, DLValidator dlValidator,
		StorageEngine storageEngine, DDMBeanTranslator ddmBeanTranslator,
		DDMFormValuesFactory ddmFormValuesFactory) {

		this(
			httpServletRequest, dlFileEntryType, dlValidator, null,
			storageEngine, ddmBeanTranslator, ddmFormValuesFactory);
	}

	public DefaultDLEditFileEntryDisplayContext(
		HttpServletRequest httpServletRequest,
		HttpServletResponse httpServletResponse, DLValidator dlValidator,
		FileEntry fileEntry, StorageEngine storageEngine,
		DDMBeanTranslator ddmBeanTranslator,
		DDMFormValuesFactory ddmFormValuesFactory) {

```

and

```
	public BaseDLEditFileEntryDisplayContext(
		UUID uuid,
		DLEditFileEntryDisplayContext parentDLEditFileEntryDisplayContext,
		HttpServletRequest httpServletRequest,
		HttpServletResponse httpServletResponse,
		DLFileEntryType dlFileEntryType) {

		super(
			uuid, parentDLEditFileEntryDisplayContext, httpServletRequest,
			httpServletResponse);

		this.dlFileEntryType = dlFileEntryType;
	}

	public BaseDLEditFileEntryDisplayContext(
		UUID uuid,
		DLEditFileEntryDisplayContext parentDLEditFileEntryDisplayContext,
		HttpServletRequest httpServletRequest,
		HttpServletResponse httpServletResponse, FileEntry fileEntry) {

		super(
			uuid, parentDLEditFileEntryDisplayContext, httpServletRequest,
			httpServletResponse);
```

Sort the display contexts that we can sort in DL. Thx.

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/3449

**Pull request closed without merging**
