### PR TITLE
[TECHNICAL-SUPPORT] LPS-67230

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
A single upgrade test threw a NPE, which is odd. Retesting to see if it happens again.

**Comment by brianchandotcom** [comment]
@brandizzi CalendarSearcherTest.testExactPhraseMixedWithWords broke twice in PostgreSQL

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
