### PR TITLE
Improve language keys

### PR DESCRIPTION
**Pull request by jhinkey**
Improve Liferay Portal's Language Keys based on the new [Language Keys Guidelines](https://github.com/liferay/liferay-portal/blob/master/readme/7.0/LANGUAGE_KEY_GUIDELINES_EN.markdown) document.

/cc @codyhoag

https://issues.liferay.com/browse/LRDOCS-1158

### CODE REVIEW

**Comment by jhinkey** [comment]
I'll review the failures and re-send.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/612b2f2577...813963aeb9

**Comment by brianchandotcom** [comment]
@jhinkey you forgot to regenerate modules, see 74f40f1bbc8ffa19bfac4369007c52be661aacc8

**Comment by jhinkey** [comment]
Hi Brian. What's the command for regenerating the modules? Thanks!

On 8/3/2015 4:44 PM, Brian Chan wrote:
>
> @jhinkey <https://github.com/jhinkey> you forgot to regenerate
> modules, see 74f40f1
> <https://github.com/brianchandotcom/liferay-portal/commit/74f40f1bbc8ffa19bfac4369007c52be661aacc8>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/28906#issuecomment-127401936>.
>

-- 
Jim Hinkey
Sr. Knowledge Engineer
Liferay, Inc.
www.liferay.com <http://www.liferay.com>

*Liferay Symposium North America*
November 16-17, 2015 | Chicago, IL
www.liferay.com/northamerica2015 <http://www.liferay.com/northamerica2015>
---

Visit Us: www.liferay.com <http://www.liferay.com> | Like Us:
facebook.com/liferay <http://facebook.com/liferay> | Follow Us:
twitter.com/liferay <http://twitter.com/liferay>

**Comment by jhinkey** [comment]
@ZoltanTakacs please add to 7.0 for LRDOCS-1158. Thanks.

**Comment by ZoltanTakacs** [comment]
Hi @jhinkey,

Sure, we will do a re-sync with master on this Friday so it will be included in Milestone 7 as well as https://github.com/brianchandotcom/liferay-portal/pull/29035. Thanks for notifying me.

**Pull request closed without merging**
