### PR TITLE
LPS-104370 Test LDAP Connections

### PR DESCRIPTION
**Pull request by topolik**
Hi Brian,

https://github.com/brianchandotcom/liferay-portal/pull/80649#issuecomment-551227615:
> @topolik @stian-sigvartsen Like I said in the call today... this LPS has already been backported to 7.1.x
> We really need to use a new LPS or else it'll confuse support.

I couldn't find any commit in 7.1.x, 7.2.x or master that would indicate LPS-102777 was backported. The changes are not there and the ticket number isn't in any commit message.

To move things forward I did create a new ticket https://issues.liferay.com/browse/LPS-104370 Thanks.

/cc @stian-sigvartsen

----
_Original message from Stian:_

Review of stian-sigvartsen/pull/203

I have CI tested these changes on stian-sigvartsen/pull/205
In speaking with QA the ':apps:portal:portal-jmx-test:startTestableTomcat' is flaky and has been failing on other pull requests. The other failures don't look related.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3ec8fc84c1...de92f52abf

**Comment by brianchandotcom** [comment]
@topolik Your pull to me yesterday was https://github.com/brianchandotcom/liferay-portal/pull/80649

The pull says it was for LPS-102777 

But every commit was for LPS-102771 and I found them in 7.1.x as f366ed5432bb8ef1a97cb4dd3c917850d5836cb1 and 7.2.x as f366ed5432bb8ef1a97cb4dd3c917850d5836cb1

Which is why I was so confused.

@stian-sigvartsen you guys need to be careful with LPS ticket numbers. In any case, I've merged in this pull.

I did not touch LPS-102771 or LPS-102777

**Comment by topolik** [comment]
Thanks @brianchandotcom, very nice catch. Almost a biblical situation, now when you said that I can see it, you opened my eyes :)

**Comment by lipusz** [comment]
lbm:backport

**Pull request closed without merging**
