### PR TITLE
LPS-108231 Set restart-required to false for CCR

### PR DESCRIPTION
**Pull request by BryanEngler**
From tibor:
The SF error is expected: it happened on the previous PRs too where we set this property to false, we just need to tell Brian that we are confirming it's safe to set to false when sending to him.

See https://github.com/BryanEngler/liferay-portal/pull/477#issuecomment-583310684

Cc: @lipusz @xbrianlee @joshchong @dejuknow

---
*[Task] Set restart-required to false for Cross Cluster Replication and Similar Results*
https://issues.liferay.com/browse/LPS-108231

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Please fix SF and resend.

**Comment by BryanEngler** [comment]
@brianchandotcom according to tibor the SF error is expected (noted in the pr description) so i was under the impression it is something you handle. is that not the case?

**Comment by lipusz** [comment]
Yeah, same happened on
https://github.com/brianchandotcom/liferay-portal-ee/pull/27324.

The app.bnd description we have is telling that the SF error is intended
and we have to confirm that it is safe to set it to false.

Sent from mobile
--
Project Manager, Search & App Security SME @ Product Care

**Comment by lipusz** [comment]
https://docs.google.com/document/d/1VsBzfc1wRY0wT90XrCmRfAf_FCKNDzgjftr4CP1H46o/edit

Sent from mobile
--
Project Manager, Search & App Security SME @ Product Care

**Comment by lipusz** [comment]
@brianchandotcom See above :point_up:

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
Reopening so it can be merged. See my comments @brianchandotcom above for explanation.

Thanks!

/cc @dejuknow

**Comment by brianchandotcom** [comment]
Ok, this is strange..

@jpince Can we improve this process? It's hard for me to remember when to ignore what CI is telling me.

Merged.

**Comment by jpince** [comment]
@xbrianlee @vicnate5 BChan would like test(s) for this, please complete [LRQA-53836](https://issues.liferay.com/browse/LRQA-53836)/[LRQA-53174](https://issues.liferay.com/browse/LRQA-53174) as soon as possible.

@lipusz @BryanEngler please add an SF suppression for now. After QA adds the test, I'll work with Hugo to figure out how to get SF to allow restart-required = false based on the presence of the test.

**Comment by lipusz** [comment]
Testing SF suppression here: https://github.com/lipusz/liferay-portal/pull/298

**Comment by lipusz** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/84401

**Comment by vicnate5** [comment]
Relevant story ticket: https://issues.liferay.com/browse/LPS-104785

**Pull request closed without merging**
