### PR TITLE
LPD-8726 Feature Flag for Config Contributor client extension

### PR DESCRIPTION
**Pull request by JamesAGarcia**
Previous PR: https://github.com/liferay-frontend/liferay-portal/pull/3958

This PR adds the LPS-186870 description and title.

cc. @markocikos

### CODE REVIEW

**Comment by JamesAGarcia** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.

**Comment by brianchandotcom** [comment]
@JamesAGarcia @markocikos 

The hard part of this PR is that the client extension is called editor-config-contributor (super weird name).

Second, I"m not sure if there can only be 1 or if there can be many. I have a feeling it may be just 1.

Please vet out my change in 3eefa189d77e0d4759d3482f2f5a0d95f1ee8a57

**Comment by markocikos** [comment]
@JamesAGarcia @brianchandotcom 

There can be multiple client extensions affecting one editor usage. We collect URLs in [the editorTransformerURLs array](https://github.com/liferay/liferay-portal/blob/master/modules/apps/client-extension/client-extension-web/src/main/java/com/liferay/client/extension/web/internal/portlet/editor/config/contributor/CETEditorConfigContributor.java#L70-L85), and then resolve them all [in frontend](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/utils/client_extensions/loadClientExtensions.ts). One client extension can also affect multiple editor usages.

Naming was intentionally very technical. It reflects the `*EditorConfigContributor.java` files that are used to configure editors in backend. The properties of client extension will not make sense to somebody who is not familiar with how configuration works in  `EditorConfigContributor`s. `Editor Config Keys` and `Editor Names` are unclear when considered in isolation, and even `Portlet Names` requires very technical knowledge to input portlet IDs. This client extension is poor at being user friendly, to customize editors in a low code way. As far as I know, there are plans to add such a client extension later on. But, what this client extension offers a very convenient way to migrate to client extensions for somebody who already knows how `EditorConfigContributor`s work. It configures in the exact same way.

/cc @dsanz

**Comment by dsanz** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/147033

**Pull request closed without merging**
