### PR TITLE
LPS-189587 Pass the taskItemDelegateName value to the Batch Engine by using a method of the resource instead of injecting it as query parameter

### PR DESCRIPTION
**Pull request by ccorreagg**
Forwarded manually from: https://github.com/liferay-headless/liferay-portal/pull/1340

---

Related issue: https://liferay.atlassian.net/browse/LPS-189587

The purpose of this PR is to remove the injection of the `taskItemDelegateName` attribute as query parameter that is performed in the class `ObjectDefinitionIdContainerRequestFilter` and inject it via a resource method.

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6d130e3153...c53e55db9b

**Comment by brianchandotcom** [comment]
@ccorreagg 

is this intentional?

```
if (Validator.isBlank(_taskItemDelegateName)) {
```

Should it be '_taskItemDelegateName != null' or may be Validator.isNull ?

**Comment by ccorreagg** [comment]
Rollbacked as we will include all the changes in a new PR. See https://github.com/liferay-headless/liferay-portal/pull/1350

**Pull request closed without merging**
