### PR TITLE
LPS-54009 Remove some warnings due to generics

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@izaera please resend, test failure.

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchandotcom** [comment]
@robertoDiaz 
com.liferay.portal.modules.ModulesBuildScriptsTest.testScanBuildScripts
Missing modules/apps/document-library/document-library-item-selector-api/build.xml

junit.framework.AssertionFailedError: Missing modules/apps/document-library/document-library-item-selector-api/build.xml
	at com.liferay.portal.modules.ModulesBuildScriptsTest$1.preVisitDirectory(ModulesBuildScriptsTest.java:47)
	at com.liferay.portal.modules.ModulesBuildScriptsTest$1.preVisitDirectory(ModulesBuildScriptsTest.java:38)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:192)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:69)
	at java.nio.file.Files.walkFileTree(Files.java:2600)
	at java.nio.file.Files.walkFileTree(Files.java:2633)
	at com.liferay.portal.modules.ModulesBuildScriptsTest.te

Is not a false positive.

**Comment by robertoDiaz** [comment]
I'll recheck

**Pull request closed without merging**
