### PR TITLE
LPS-86079 Add the Aries CDI impl

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@pyoo47 how can it say that test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8 passed AND failed at the same time? Doesn't make sense?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c297e02536...200686cced

**Comment by yichenroy** [comment]
@brianchandotcom 
The failing test originated from a module not modified in this pullrequest, so it was not tested/reported in ci:test:relevant, the failure message originated from the full test suite via ci:test. 

cc @pyoo47

**Pull request closed without merging**
