### PR TITLE
Persistence Test

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
Hey Brian,

   It is needed that the extensions https://github.com/brianchandotcom/liferay-portal/pull/23621 and https://github.com/brianchandotcom/liferay-portal/pull/23621 are published in nexus, so the test of this pull doesn't fail.

@csierra, @shuyangzhou, @JorgeFerrer, @mdelapenya

Thanks in advance!

**Comment by shuyangzhou** [comment]
With https://github.com/brianchandotcom/liferay-portal/pull/23621 and this pull, can we run the integration tests in modules yet? If so, please provide instructions about how to run it, thanks!

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Pull request closed without merging**
