### PR TITLE
LPS-102503 Remove liferay-theme-es2015-hook

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jbalsas what will this do to backwards compat? for existing 7.2.x installations?

**Comment by jbalsas** [comment]
Yes, this is a final theme released to the marketplace. This is in fact a simpler solution that should work backwards without any issues.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cb6faafab3...6fb687336f

**Comment by brianchandotcom** [comment]
@marcoscv-work @wincent can I do this? 144e95f

Or is it better to leave it empty? Please resend if my commit is not good.

**Comment by wincent** [comment]
@brianchandotcom: you certainly can do it without any negative consequences.

The reason I did not is that in general, it is "safer" to do all manipulation of dependencies using `yarn add` or `yarn remove` — that way, we know for sure that the yarn.lock is always kept up to date. And it turns out that when you `yarn remove` the last dependency in a package, `yarn` keeps the empty dependencies object around.

**Pull request closed without merging**
