### PR TITLE
LPS-70222 Add a comparator so ServletContextListeners are always last in list

### PR DESCRIPTION
**Pull request by rotty3000**
@shuyangzhou please note this updated version of org.eclipse.equinox.http.servlet is built from HEAD of R4_5_maintance which includes are your fixes plus an additional fix by @juangon.

### CODE REVIEW

**Comment by juangon** [comment]
@brianchandotcom please can you backport it to 7.0.x? You know my last day would be on Friday, and backport process would require more than that just for a clean cherry-pick.
It's necessary so this affects Liferay Faces and need it to be in for 7 GA4.

/cc @vsingleton @ngriffin7a @stiemannkj1

**Comment by shuyangzhou** [comment]
@rotty3000 Thanks for the update!
@dantewang @slnn please run a regression test against this pull to make sure everything is still ok.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a7f29b6d36...c6ee6a3dea

**Comment by brianchandotcom** [comment]
Thx @juangon backported!

@rotty3000 @shuyangzhou fyi.

**Comment by juangon** [comment]
Hmm seems it isn't actually backported @brianchandotcom ?

**Pull request closed without merging**
