### PR TITLE
LPS-167608 HR_118 The description text field doesn't have any characters hints

### PR DESCRIPTION
**Pull request by ethib137**
Manually forwarding from https://github.com/liferay-frontend/liferay-portal/pull/3278 including minor wordsmithing.

Fixes:

https://issues.liferay.com/browse/LPS-167608
https://issues.liferay.com/browse/LPS-168281

### CODE REVIEW

**Comment by ethib137** [comment]
cc: @veroglez @bryceosterhaus

**Comment by ethib137** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8bd6fc0a22...d313ac7fda

**Comment by brianchandotcom** [comment]
@veroglez @ethib137 just d313ac7f

**Pull request closed without merging**
