### PR TITLE
LPS-161071 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-161071

This is only for master.

@victorg1991

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure cases are unrelated to changes.
See https://github.com/liferay-echo/liferay-portal/pull/9398
✔️ ci:test:stable - 26 out of 26 jobs passed
❌ ci:test:relevant - 46 out of 49 jobs passed in 1 hour 9 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f46e255d26...0c4b5d6c4d

**Comment by brianchandotcom** [comment]
@victorg1991 nice, just 0c4b5d6c4d098a3016deb4f737778b22d8609705

**Pull request closed without merging**
