### PR TITLE
LRQA-41726 | master

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LRQA-41726

/cc @austinchiang

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:reopen

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by liuxingye** [comment]
The SF failure is not related to my commits.

**Pull request closed without merging**
