### PR TITLE
LPS-79119

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @robertoDiaz,

Attached is an update for http://issues.liferay.com/browse/LPS-79119.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi guys,

We did fix this issue here https://github.com/marcoscv-work/liferay-portal/pull/89.

Is it still happening?

**Comment by 4lejandrito** [comment]
I have checked on Jira and I believe they are exact duplicates. I asked @austinchiang to verify it. 

We should close this pr, at least for now. Thanks @fortunatomaldonado!

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
