### PR TITLE
LPS-173926

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@tinatian @lfbesada can you two resend this?

This doesn't test the case when you have an exception and you did NOT set up a key.

In that case, it should default to "is-temporarily-unavailable"

Imagine if you tried to read "is-temporarily-unavailable[someOtherPorltetId]" it will just show the key right now.

Thx.

**Comment by lfbesada** [comment]
Hi @brianchandotcom 

I think this case is tested in the method testUncontrolledExceptionError

testUncontrolledExceptionError --> asserts the message is the default one, "is-temporarily-unavailable", when "is-temporarily-unavailable[portletId]" doesn't exist as a language key

testUncontrolledExceptionCustomizedError -->  asserts the message is the custom one, when "is-temporarily-unavailable[portletId]" exists as a language key

This development allows a portlet to customize its unhandled error message. It is based on taking advantage of the LanguageImpl fallback implemented [here](https://github.com/liferay/liferay-portal/blob/d076f63b4ae36b8cce79f0d4abcaddd46071d00b/portal-impl/src/com/liferay/portal/language/LanguageImpl.java#L959-L977). This fallback allows a key to be introduced indicating a context between brackets, if the key is found it will be used, otherwise the same key will be used but eliminating the part between brackets. This allows us to search for the specific key for that portlet and, if it is not there, the default one will be used as before.

cc: @tinatian 

Regards

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ce814b75e8...347368ca12

**Pull request closed without merging**
