### PR TITLE
LPS-97868 Action is for deletion, not for selection of translations

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f2d1304761...ef9dc89244

**Comment by brianchandotcom** [comment]
lbm:backport @CsabaTurcsan @jpince @zsoltbalogh

**Comment by jpince** [comment]
lbm:backport, to try and catch these additional 2 commits

**Comment by CsabaTurcsan** [comment]
lbm:backport

@jpince  I've added you to the allowed requesters list as it was Brian only. I've also added myself, so this comment will trigger LBM.

**Pull request closed without merging**
