### PR TITLE
LPS-83949 Point to new loader version to fix failing tests

### PR DESCRIPTION
**Pull request by izaera**
/CC @jbalsas

Hey @brianchandotcom, sorry for this big PR, but it was hard to send it in smaller chunks.

This basically gets rid of a static `loader_js_modules` file that contained all the information about all the frontend modules in the system and replaces it for async and on-demand requests to resolve that from the server.

This addresses both **security and performance** concerns.

Please, let us know if there's anything you'd like us to change.

Thanks!

### CODE REVIEW

**Comment by izaera** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@izaera are these safe to merge? Lots of frontend broken.

@jpince please give insight for this pull too.

**Comment by izaera** [comment]
This one should be safe. I did manual testing more than three times and fixed lots of errors. Also @john-co had a look at the last CI run and found some more errors that I fixed by reproducing the poshi tests manually. So, AFAIK, everything should be OK.

However, @jpince, if you can give it a look to make sure it would be great because it's a very sensitive PR.

Thx :-).

**Comment by jpince** [comment]
@izaera took a quick look, didn't see anything that looked concerning for the backend tests. Frontend tests are blocked by an unrelated POSHI test issue. So we will just have to trust John's analysis and you guys can follow up if there are any defects or test failures introduced.

**Comment by john-co** [comment]
@izaera, I don't see the failures related to your commits. All previous errors we looked at before have been resolved. As jpince said, most of the tests are blocked by unrelated POSHI issue. Should be resolved by WEM team when fix is merged.

**Comment by brianchandotcom** [comment]
@izaera ok, I took a look... code from outside contributors always take longer to merge in (especially if they do a lot)

Can you move *Servlet to the right package (same for the tests) Please check each class to make sure they are in the right place

Some of the *.json files are not formatted right.

Update to 5.0.0 is not needed (we already on 4.0.0). Please resend. Thx.

**Pull request closed without merging**
