### PR TITLE
LPS-55749

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-55749](https://issues.liferay.com/browse/LPS-55749).<br><br>Here's just a few of the files renamed.  If this works, I'll send the rest

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0f2f015fe3...51b9c6f26f

**Comment by brianchandotcom** [comment]
LPS-55749 != LPS-57749 just fyi.. :) cut and paste for the future to prevent these types of mistakes. The bad part is if it got into the git log... then it'd make tracing tickets hard.

Drew, can you also look at MessageBoardsPortlet.java vs. DDMPortlet and DDLPortlet.java..

**Comment by brianchandotcom** [comment]
Basically, our Portlet names are not consistent either.. let's rename them to make them consistent.

Thx

**Comment by drewbrokke** [comment]
I see that `MessageBoardsPortlet` is an expanded class name, but then has other classes like `MBPortletKeys`.  So we want to make all of them `*MBPortlet*`?

**Pull request closed without merging**
