### PR TITLE
LPS-53667 Logically equivalent using IN instead of OR chaining, having t...

### PR DESCRIPTION
**Pull request by shuyangzhou**
...wo loops isn't nessessary since LPS-43611 moved the logic that made them different

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Simple unit test? @Preston-Crary 

Just do it like StringUtilTest

Pass in a before and after and make sure they are the same.. prevent future self from breaking anything.

Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1ad5e0ff35...36386f3662

**Comment by Preston-Crary** [comment]
RoleServiceTest covers this.  I can add a unit test to cover other cases though.

**Comment by brianchandotcom** [comment]
Sure, more the merrier.

Thx @Preston-Crary

**Pull request closed without merging**
