### PR TITLE
LPS-91467 Link between site and role maintained even when role is deleted

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-91467](https://issues.liferay.com/browse/LPS-91467).<br><br>/cc @pei-jung @stsquared99 @alee8888 @ChrisKian

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
ci:test:relevant (I fixed something in upstream)

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by drewbrokke** [comment]
@brianchandotcom does this need to be rebased and resent?  I see the same functional test failures as on other pulls

**Comment by drewbrokke** [comment]
resent as https://github.com/brianchandotcom/liferay-portal/pull/70061

**Pull request closed without merging**
