### PR TITLE
LPS-64500 Update task cache

### PR DESCRIPTION
**Pull request by jbalsas**
Hey Brian!

For JS bundles, the `BundleVersion` in `bnd.bnd` should match the `version` in `package.json`. Otherwise, their js modules can never be loaded.

In theory, it should not be needed to add in the `bnd`, since our `NpmAnalyzerPlugin` did that for us, but if I understood correctly, with the current build system, other changes will need to happen for this to be valid again.

I'm just sending this as is, because portal is right now unstable and the spa feature is completely gone. We'd need a way to enforce these versions always match, either:
1. Remove from the `bnd.bnd` and rely on the `package.json` alone
2. Include some test (SourceFormatter?) to make sure those values match if both present

What do you think?

Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
Following @brunobasto's suggestion, @ithildir will at least make the build fail when in this type of modules the versions mismatch.

**Comment by sharonchoi** [comment]
@brianchiu upgrade failures due to https://issues.liferay.com/browse/LPS-64526

**Comment by brianchiu** [comment]
One of the upgrade failures occurs before it reaches the bug in LPS-64526.

The 6.2 to 7.0 upgrade test fails during the upgrade itself.
```
     [java] 18:33:22,802 INFO  [main][UpgradeProcess:97] Completed upgrade process com.liferay.portal.upgrade.UpgradeProcess_7_0_0 in 16416ms
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.exception.BulkException: {message = null
     [java] {com.liferay.portal.kernel.upgrade.UpgradeException:java.lang.NullPointerException, com.liferay.portal.kernel.upgrade.UpgradeException: java.lang.NullPointerException
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:91)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:115)
     [java] 	at com.liferay.portal.upgrade.UpgradeProcess_7_0_0$2.doRun(UpgradeProcess_7_0_0.java:94)
     [java] 	at com.liferay.portal.kernel.concurrent.ThrowableAwareRunnable.run(ThrowableAwareRunnable.java:37)
     [java] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
     [java] 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] Caused by: java.lang.NullPointerException
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.alter(UpgradeProcess.java:329)
     [java] 	at com.liferay.portal.upgrade.v7_0_0.UpgradeExpando.doUpgrade(UpgradeExpando.java:32)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:88)
     [java] 	... 8 more
     [java] }
     [java] {com.liferay.portal.kernel.upgrade.UpgradeException:java.lang.NullPointerException, com.liferay.portal.kernel.upgrade.UpgradeException: java.lang.NullPointerException
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:91)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:115)
     [java] 	at com.liferay.portal.upgrade.UpgradeProcess_7_0_0$4.doRun(UpgradeProcess_7_0_0.java:117)
     [java] 	at com.liferay.portal.kernel.concurrent.ThrowableAwareRunnable.run(ThrowableAwareRunnable.java:37)
     [java] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
     [java] 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] Caused by: java.lang.NullPointerException
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.alter(UpgradeProcess.java:329)
     [java] 	at com.liferay.portal.upgrade.v7_0_0.UpgradeDocumentLibrary.doUpgrade(UpgradeDocumentLibrary.java:110)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:88)
     [java] 	... 8 more
     [java] }
     [java] }
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:91)
     [java] 	at com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil._upgradeProcess(UpgradeProcessUtil.java:175)
     [java] 	at com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil.upgradeProcess(UpgradeProcessUtil.java:143)
     [java] 	at com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil.upgradeProcess(UpgradeProcessUtil.java:125)
     [java] 	at com.liferay.portal.events.StartupHelper.upgradeProcess(StartupHelper.java:164)
     [java] 	at com.liferay.portal.events.StartupHelperUtil.upgradeProcess(StartupHelperUtil.java:81)
     [java] 	at com.liferay.portal.tools.DBUpgrader.upgrade(DBUpgrader.java:158)
     [java] 	at com.liferay.portal.tools.DBUpgrader.main(DBUpgrader.java:96)
     [java] Caused by: com.liferay.portal.kernel.exception.BulkException: {message = null
     [java] {com.liferay.portal.kernel.upgrade.UpgradeException:java.lang.NullPointerException, com.liferay.portal.kernel.upgrade.UpgradeException: java.lang.NullPointerException
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:91)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:115)
     [java] 	at com.liferay.portal.upgrade.UpgradeProcess_7_0_0$2.doRun(UpgradeProcess_7_0_0.java:94)
     [java] 	at com.liferay.portal.kernel.concurrent.ThrowableAwareRunnable.run(ThrowableAwareRunnable.java:37)
     [java] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
     [java] 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] Caused by: java.lang.NullPointerException
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.alter(UpgradeProcess.java:329)
     [java] 	at com.liferay.portal.upgrade.v7_0_0.UpgradeExpando.doUpgrade(UpgradeExpando.java:32)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:88)
     [java] 	... 8 more
     [java] }
     [java] {com.liferay.portal.kernel.upgrade.UpgradeException:java.lang.NullPointerException, com.liferay.portal.kernel.upgrade.UpgradeException: java.lang.NullPointerException
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:91)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:115)
     [java] 	at com.liferay.portal.upgrade.UpgradeProcess_7_0_0$4.doRun(UpgradeProcess_7_0_0.java:117)
     [java] 	at com.liferay.portal.kernel.concurrent.ThrowableAwareRunnable.run(ThrowableAwareRunnable.java:37)
     [java] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
     [java] 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
     [java] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
     [java] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
     [java] 	at java.lang.Thread.run(Thread.java:745)
     [java] Caused by: java.lang.NullPointerException
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.alter(UpgradeProcess.java:329)
     [java] 	at com.liferay.portal.upgrade.v7_0_0.UpgradeDocumentLibrary.doUpgrade(UpgradeDocumentLibrary.java:110)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:88)
     [java] 	... 8 more
     [java] }
     [java] }
     [java] 	at com.liferay.portal.kernel.concurrent.ThrowableAwareRunnablesExecutorUtil.execute(ThrowableAwareRunnablesExecutorUtil.java:71)
     [java] 	at com.liferay.portal.upgrade.UpgradeProcess_7_0_0.doUpgrade(UpgradeProcess_7_0_0.java:148)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:88)
     [java] 	... 7 more
     [java] Java Result: 1
```

**Comment by brianchiu** [comment]
ci:retest

**Comment by csierra** [comment]
@jbalsas @rotty3000 can we make the build fail if we make the `NpmAnalyzerPlugin` fail if the versions mismatch?

**Comment by brianchandotcom** [comment]
@Ithildir Andrea will resend.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7b72871b13...a9da518ec9

**Pull request closed without merging**
