### PR TITLE
LPS-168308 Add Labels "X Variations" and "No Variations"

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-168308

@lfbesada

### CODE REVIEW

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/10260

:heavy_check_mark: ci:test:stable - 28 out of 28 jobs passed
:x: ci:test:relevant - 142 out of 150 jobs passed in 1 hour 16 minutes

**Comment by ozysouza** [comment]
ci:reopen

**Comment by lfbesada** [comment]
I will solve conflicts and resend

**Comment by brianchandotcom** [comment]
@lfbesada can you standardize the naming here

```
	public int getAssetListEntryVariationCount(AssetListEntry assetListEntry) {
		int numVariations =
			AssetListEntrySegmentsEntryRelLocalServiceUtil.
				getAssetListEntrySegmentsEntryRelsCount(
					assetListEntry.getAssetListEntryId());
```

assetListEntrySegmentsEntryRelsCount

vs.

assetListEntryVariationCount (should be at least xyzVariationsCount)

vs.

numVariations

Please resend. Let's go with the most technical name. Thx.

**Pull request closed without merging**
