### PR TITLE
LPS-55026 Minor SF

### PR DESCRIPTION
**Pull request by marcellustavares**
Hi Brian, this is the extraction of the calendar plugin. As soon it gets merged we'll remove the calendar from plugins repo.

The only point it's not clear to me is the naming we're using for the folderduring the UpgradeProcesses.

I left v1_0_0 but we're porting a plugin based on build number 4.

Let me know what you think, so we can update it if that's the case.

Thanks and sorry again for the long pull :disappointed:

### CODE REVIEW

**Comment by marcellustavares** [comment]
cc @brandizzi

**Comment by marcellustavares** [comment]
ci:retest

**Comment by marcellustavares** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@marcellustavares seems like a real failure to me. Please resend.

**Pull request closed without merging**
