### PR TITLE
LPS-93320 Always use friendly url resolvers to get url separators since each resolver can add/remove separators in runtime

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by jpince** [comment]
@brianchiu @kyle-miho POSHI failures

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@brianchiu @kyle-miho  please send me fixes for poshi asap (or disable the broken ones and then send them to me)

**Comment by kyle-miho** [comment]
@brianchandotcom @jpince  the poshi failures are unrelated

**Pull request closed without merging**
