### PR TITLE
LPS-87529 Content list API

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
Hi @brianchandotcom 
I've rebased the Content List API PR on top of https://github.com/brianchandotcom/liferay-portal/pull/70084 to make sure tests keep passing.
Common logic to convert a JournalArticle to a StructuredContent is now in a Util class.
For now assets of type StructuredContent, Document, Folder, KnowledgeBaseArticle and BlogPosting are supported.

**Comment by jpince** [comment]
ci:close @ruben-pulido it's because bookmarks is no longer bundled, see https://github.com/liferay/liferay-portal/blob/master/modules/apps/bookmarks/app.bnd#L3. so it will compile fine with ant all, but when it goes to build portal according to what's in the app.bnd (what will be released), it fails. Closing this pull until that dependency issue can be resolved/eliminated.

**Comment by ruben-pulido** [comment]
Thanks for the heads up @jpince! 
I'll remove the dependency to bookmarks and resend the PR.

**Comment by ruben-pulido** [comment]
@jpince Resent here without reference to bookmarks: https://github.com/brianchandotcom/liferay-portal/pull/70137

**Pull request closed without merging**
