### PR TITLE
LRQA-40204 Implement utility method to call ant macrodefs from within beanshell

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-40204

Please publish after merging

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@pyoo47 that failure is strange?

**Comment by brianchandotcom** [comment]
@pyoo47 minor SF in usptream.. published.

**Comment by michaelhashimoto** [comment]
@yichenroy and I are looking into this issue.

**Pull request closed without merging**
