### PR TITLE
LPS-86344 Using DLValidator fixName

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c7dd08d108...a86dc1f2ae

**Comment by brianchandotcom** [comment]
@4lejandrito @adolfopa see my changes in upstream. Thx.

**Pull request closed without merging**
