### PR TITLE
LPS-68672 Convert properties to components

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
@brianchandotcom we have moved to a different module the PropertiesTransformerListener but we don't really know what it is and if it is still relevant. It doesn't have any javadoc or documentation about what it does. It seems it was added to you in 2006... do you remember why? is this something we can remove now?

Thanks!

cc @pavel-savinov

**Comment by brianchandotcom** [comment]
@juliocamarero 

I keep getting

```
     [java] Bundle-Name: ./modules/apps/journal-properties-transformer-listener/journal-properties-transfomer-listener/bnd.bnd
     [java] Bundle-SymbolicName: ./modules/apps/journal-properties-transformer-listener/journal-properties-transfomer-listener/bnd.bnd
```

When I run the SF. I think the package or the app is inconsistent somewhere. Please resend on top of  https://github.com/juliocamarero/liferay-portal/pull/4214

Thx.

**Pull request closed without merging**
