### PR TITLE
LPS-109715 Updating tests

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@inacionery please also fix:

```
com.liferay.portal.workflow.metrics.rest.resource.v1_0.test.MetricResourceTest.testGetProcessMetric
com.liferay.portal.workflow.metrics.service.internal.search.index.test.SLAInstanceResultWorkflowMetricsIndexerTest.testReindex
com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXMLLog
```

**Comment by inacionery** [comment]
Hey @brianchandotcom,

I send the fix to https://github.com/BryanEngler/liferay-portal/pull/486

thanks!

**Comment by inacionery** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
