### PR TITLE
LPS-76970 Handle arrays, iterable objects, maps, JSONObjects and beans recursively calling getSoyMapValue instead of using JSON serialization/deserialization

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
@jorgediaz-lr Any idea of why is this failing? Apart from the SF test, of course...

**Comment by jorgediaz-lr** [comment]
That errors didn't appear in my previous pr: https://github.com/jorgediaz-lr/liferay-portal/pull/167

Nevertheless, I am going to have a look to them

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jpince** [comment]
ci:stop

**Comment by jpince** [comment]
@izaera @jorgediaz-lr hey guys, don't worry about the functional test failures, something got merged that caused all of these. So just fix the SF and then you should be fine :)

**Comment by jorgediaz-lr** [comment]
Thank you @jpince !

I will fix SF and resend

**Pull request closed without merging**
