### PR TITLE
LPS-72918

### PR DESCRIPTION
**Pull request by bawachhe**
https://issues.liferay.com/browse/LPS-72918

### CODE REVIEW

**Comment by bawachhe** [comment]
ci:reopen

**Comment by jpince** [comment]
@bawachhe here are the real failures, please resolve and resend.

[build-service](https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/122947/AXIS_VARIABLE=0,label_exp=!master/console) - need to regenerate some file(s)?

[unit-jdk8](https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/103298/AXIS_VARIABLE=0,label_exp=!master/testReport/junit/com.liferay.portal.modules/ModulesStructureTest/testScanIgnoreFiles/)
```
Incorrect modules/apps/tasks/.gitignore expected:<[!/tasks-portlet/docroot/WEB-INF/lib]> but was:<[**/docroot/WEB-INF/tld/
*.iml
.classpath
.gh.json
.gradle/
.idea/
.project
.sass-cache/
.settings/
bin/
build/
classes/
lib/
liferay-hook.xml.processed
node_modules/
npm-debug.log
test-classes/
test-coverage/
test-results/
tmp/]>
```

[build-wsdd](https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/69927/AXIS_VARIABLE=0,label_exp=!master/console) - can't find a bunch of symbols (scroll down 2/3 of the way in that console log)

**Comment by jpince** [comment]
ci:close

**Comment by bawachhe** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/49641

**Pull request closed without merging**
