### PR TITLE
LPS-73492 Fix configuration properties description key names

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@hhuijser another random error @petershin

**Comment by brianchandotcom** [comment]
@ithildir fyi

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/788ed5bf1e...f64cbf991b

**Pull request closed without merging**
