### PR TITLE
LPS-74409 Auto

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest (due to a bad slave on test-1-3)

**Comment by pyoo47** [comment]
ci:retest (due to a bad slave on test-1-3)

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Can you change all references to "template" to ddmTemplate in modules/apps/web-experience/asset/asset-display-template-web/src/main/resources/META-INF/resources/edit_asset_display_template_script.jspf

See 

```
DDMDisplay ddmDisplay = assetDisplayTemplateDisplayContext.getDDMDisplay();

DDMTemplate template = assetDisplayTemplateDisplayContext.getDDMTemplate();

```

We should keep

``lfr-template-editor-container
```

and

```
Map<String, TemplateVariableGroup> templateVariableGroups = TemplateContextHelper
```

Since those reference portal-impl/src/com/liferay/portal/template/TemplateContextHelper.java.

However, 

```
long templateHandlerClassNameId = ddmDisplay
```

Should probably be prefixed. Can you scour through them and prefix what makes the most sense? Thx @ealonso

**Pull request closed without merging**
