### PR TITLE
Lps 78194

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@shuyangzhou shouldn't we also remove modules/apps/wsrp**

I think WSRP related vars don't need to be deprecated. We can remove those and major version bump.

@ngriffin7a can you take care of that? Thx.

**Comment by shuyangzhou** [comment]
@brianchandotcom yes, I think we should remove those modules too. @ngriffin7a please do that, thanks!

**Comment by ngriffin7a** [comment]
@shuyangzhou @brianchandotcom Done, see: https://github.com/shuyangzhou/liferay-portal/pull/5963

**Pull request closed without merging**
