### PR TITLE
LRQA-43492, LRQA-43465 | master

### PR DESCRIPTION
**Pull request by GinsonRen**
https://issues.liferay.com/browse/LRQA-43492
https://issues.liferay.com/browse/LRQA-43465

7.1.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/21650

### CODE REVIEW

**Comment by GinsonRen** [comment]
ci:reopen

**Comment by GinsonRen** [comment]
ci:test:sf

**Comment by GinsonRen** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
