### PR TITLE
Lps 110705

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cb2d5f01d0...e807917db1

**Comment by brianchandotcom** [comment]
Great job @shuyangzhou ! Will we need this for ES 7?

@arboliveira @BryanEngler this should solve Search sync issues.

@inacionery fyi we removed all the retry asserts.

@victorware @xbrianlee fyi

**Comment by brianchandotcom** [comment]
@jpince fyi

**Comment by shuyangzhou** [comment]
@brianchandotcom not sure, ES7 might have internal changes that breaks this solution. Applying it to new version requires a new development process. We should defer it to when we have to.

**Comment by inacionery** [comment]
Hey @brianchandotcom,

Can this be backported to 7.2.x?

Thanks!

**Pull request closed without merging**
