### PR TITLE
LPS-103511 Apply linting and formatting to "modules/dxp"

### PR DESCRIPTION
**Pull request by wincent**
This replaces:

- https://github.com/brianchandotcom/liferay-portal/pull/79879
- https://github.com/brianchandotcom/liferay-portal/pull/79876
- https://github.com/brianchandotcom/liferay-portal/pull/79883

Ideally these would be separate but they are bound to conflict if not sent together.

So we have:

 - The segments-experiments changes (LPS-102764); plus a bunch of linting changes:
    - Sort class names in JSX `className` attributes.
    - Fix an import sorting edge case where "metal-dom" was sorting incorrectly before "metal".
    - Enable the no-restricted globals rule to prevent sketchy uses of esoteric implicit globals such as `event`.
    - Sets up linting for "modules/dxp" directories, including the application of the correct copyright headers.
- Fixes for test failures: [LPS-103485](https://issues.liferay.com/browse/LPS-103485) and [LPS-103487](https://issues.liferay.com/browse/LPS-103487).

### CODE REVIEW

**Comment by wincent** [comment]
@inacionery, @phcp: Please see https://github.com/brianchandotcom/liferay-portal/pull/79887/commits/c5c72e24820ce7cccae5e998955ce0a2d1cd167a — I had to disable tests in this specific file because they are hanging forever; I suspect that the move from "master-private" has changed the dependencies sufficiently that these are broken in a subtle way (although, I don't know if they were hanging previously). As a follow-up, can you take a look and see if you can get them passing in the new environment? In "master", we aren't using `react-test-renderer` at all, instead favoring `@testing-library/react`, so it might be a good time to migrate them over to that.

**Comment by inacionery** [comment]
Hey @wincent, 

the fix is since yesterday with @brianchandotcom https://github.com/brianchandotcom/liferay-portal/pull/79854, but he doesn't review it yet.

Thx!

**Comment by jpince** [comment]
@petershin same ReleaseInfo.java SF error above

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/67d92c2996...b44553ec2a

**Comment by brianchandotcom** [comment]
Beautiful @wincent ! Mega pulls are fine.

@inacionery can you resend https://github.com/brianchandotcom/liferay-portal/pull/79854 ? thx.

**Pull request closed without merging**
