### PR TITLE
LPS-65859 SF

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by pyoo47** [comment]
I aborted one of the axes because a sourceFormatter test froze.
```
   [exec] com.liferay.source.formatter.SourceFormatterTest > testSourceFormatter STARTED
     [exec] 
     [exec] com.liferay.source.formatter.SourceFormatterTest > testSourceFormatter STANDARD_OUT
     [exec]     Loading jar:file:/opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.impl/2.4.0/1a99d914d7515c820132ae505ee76ac047e47dbb/com.liferay.portal.impl-2.4.0.jar!/system.properties
     [exec]     Loading jar:file:/opt/dev/projects/github/liferay-portal/bundles/tomcat-8.0.32/webapps/ROOT/WEB-INF/lib/portal-impl.jar!/system.properties
```
@hhuijser Can you take a look at this issue? This appears to happen once in a while.

**Comment by brianchandotcom** [comment]
ci:retest @hhuijser can you fix the SF test freezing? Thx.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/26700dbaca...833fe77ba6

**Pull request closed without merging**
