### PR TITLE
LPS-63565 LanguageUtil.get(request) -> LanguageUtil.get(resourceBundle)

### PR DESCRIPTION
**Pull request by jbalsas**
@brianchandotcom  Here I replace usage of `LanguageUtil.get(request, key)` by `LanguageUtil.get(resourceBundle, key)` in core tag JSPs to avoid future problems with untranslated keys. Right now, there should be no visible effect in the portal, though

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jbalsas can you resend? Rebase error. Thx.

**Comment by juliocamarero** [comment]
Thank you @adolfopa @jbalsas !! :+1:

**Pull request closed without merging**
