### PR TITLE
LPS-68775 Update test

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
This error seems unrelated to the changes done in this pull

**Comment by pei-jung** [comment]
ci:reopen

**Comment by pei-jung** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1d08c68606...6e630a8576

**Comment by brianchandotcom** [comment]
@mdelapenya please send a backport to @ZoltanTakacs thx

**Pull request closed without merging**
