### PR TITLE
LPS-181757 Need to be protected in base class.

### PR DESCRIPTION
**Pull request by shuyangzhou**
@ ling-alan-huang can you add a SF check for this? For all base classes of Component(if the file contains @Reference, but it does not have @Component), all @Reference should be on protected fields, rather than private fields.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
@ling-alan-huang mis-typed a space in previous comment.

**Comment by ling-alan-huang** [comment]
I added to my todo list.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b76eb8915e...1867044b22

**Pull request closed without merging**
