### PR TITLE
LPS-71131

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
@brianchandotcom unrelated errors happening elsewhere too. tests were passing previously at me. reopening.

**Comment by matethurzo** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@matethurzo can you resend and only chain for Stream AFTER you've declared a Stream?

So this is OK:

```
Stream stream = xyz.stream();

stream.abc(
).
```

And you can just follow the Mockito pattern.

But

```

xyz.stream.abc(

```

Should be changed to first declare the Stream var.

Thx!

**Pull request closed without merging**
