### PR TITLE
LPS-92385 Test it.

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:reopen

**Comment by cgoncas** [comment]
@jpince looks like a problem unrelated with this pull :(

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8d50ba926d...a8951a543d

**Pull request closed without merging**
