### PR TITLE
LPS-106285 Regenerate WSDD since current ones cause ci stable failures

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
Hi @brianchandotcom,
"Relevant" tests fail on this pull randomly(since it has core changes - everything is relevant), I tested it a couple of times and every time different relevant tests fail.
Stable was failing before because of the WSDD changes (see https://github.com/brianchandotcom/liferay-portal/pull/82735/commits/108c6f77132c9cbc4ef27e6599af3fe640e7ee0b), but this test fails in current master as well.

@jpince just in case you have other pulls with core changes and PortalClientBuilderTest test failure.

/cc @ealonso @adolfopa

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ca1294050a...3f00974d0d

**Comment by brianchandotcom** [comment]
Thx @pavel-savinov !!

**Comment by jpince** [comment]
@pavel-savinov thanks. Just so you know, I'm not really working in CI much anymore unless someone asks for help on something specific (and I'm always happy to help!). If you have something specific to communicate to or request of QA, that's best done through #d-quality-assurance or Manoel/Carlos.

**Pull request closed without merging**
