### PR TITLE
LPS-59837 Dodge debris left behind by non-Search tests

### PR DESCRIPTION
**Pull request by arboliveira**
This fixes https://github.com/brianchandotcom/liferay-portal/pull/49274#issuecomment-305058549 and will likely prevent any flakiness of this kind in the future. Sorry about the disturbance but at least adding extra error information paid off. 😃  (https://github.com/brianchandotcom/liferay-portal/pull/49233#issue-231761708) Search tests will now filter only to groups created by themselves, ignoring leftover documents from tests elsewhere.

@Preston-Crary FYI. Apparently this may not be deleting the uploaded DLFileEntry objects post test:
https://github.com/liferay/liferay-portal/blob/9d29d91d159f6bc65ef15657d7d71560ca267ac7/modules/apps/collaboration/document-library/document-library-test/src/testIntegration/java/com/liferay/document/library/webdav/test/WebDAVLitmusBasicTest.java#L175-L176

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:reopen

**Comment by arboliveira** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@arboliveira can you email the collab team about the doc lib test error? It'd be nice if they fixed the root cause, otherwise, another flaky test will come up. Thx for fixing this.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2b5a67aa20...328132234a

**Pull request closed without merging**
