### PR TITLE
LPS-78886 Explore using type parameters in the UAD API

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-78886](https://issues.liferay.com/browse/LPS-78886).<br><br>Hey Brian, this reworks the UAD base implementations and API to move a lot of the repeated code into base classes that should be extended.  We will still use ServiceBuilder, but now the classes that are generated are very minimal, containing little to no actual logic.  That way we can change implementation details and debug without having to regen every time.  This also makes manual implementations much easier, if necessary.  It also removes the UADEntity interface from the API completely, which also makes the API much easier to implement in general.<br><br>/cc @pei-jung, @willnewbury, @dejuknow

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test

**Comment by drewbrokke** [comment]
@brianchandotcom please allow the tests to finish.

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@drewbrokke can you resend:

DynamicQueryUADEntityAggregator#getEntities should be renamed no? I know it's not returning a UADEntity, is it returning a BaseModel? Otherwise looks good.

**Comment by drewbrokke** [comment]
@brianchandotcom it's just implementing the method on the UADEntityAggregator interface.  I've done my best to remove `UADEntity` as a concept from the actual API, so `entity` should just refer to whatever object is being acted on.  The interface also has a `getEntity` method that returns type `T`, whereas the `getEntities` method returns a `List<T>`.  For our base implementation, it returns `<T extends BaseModel>`, but that is not necessarily the case when a developer implements the API themselves (or they didn't use Service Builder in the first place).

**Pull request closed without merging**
