### PR TITLE
LPS-67820 Update tests

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:retest

**Comment by marcellustavares** [comment]
@ctampoya, are these ddl tests flaky? or this error just happened on this pull?

Thanks

**Comment by ctampoya** [comment]
@marcellustavares Yes, those are the flaky tests. I disabled them from running on the PR tester yesterday. It was merged here https://github.com/brianchandotcom/liferay-portal/pull/43486

**Comment by marcellustavares** [comment]
Thx @ctampoya, I remember you mentioned to me, just wanted to confirm if those were the tests.

Regards,

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c6f56d63e7...453a8bf777

**Pull request closed without merging**
