### PR TITLE
LPS-77183

### PR DESCRIPTION
**Pull request by marco-leo**
//cc @drewbrokke @Ithildir

### CODE REVIEW

**Comment by marco-leo** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:retest

**Comment by drewbrokke** [comment]
cc @pei-jung

**Comment by marco-leo** [comment]
@jpince I really don't understand what wrong

**Comment by brianchandotcom** [comment]
ci:test @marco-leo upstream was broken, not your fault

**Comment by brianchandotcom** [comment]
@marco-leo doesn't compile:

```
for (String curType : OrganizationLocalServiceUtil.getTypes()) {
     [exec] 			 
```

**Pull request closed without merging**
