### PR TITLE
LPS-102388 json serialization

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/32eaf3c5af...8c97f7cd3d

**Comment by brianchandotcom** [comment]
@nhpatt I used Sublime to do a case sensitive sort in 370114351cb9601e846ebe3e23ae1d151f7e27ed

But  I was afraid that order matters, so I did e0b1a3d3225d2ce47c1cd5d148a959c14ad5c1ff

Can you send me a revert if order does not matter?

**Comment by brianchandotcom** [comment]
@nhpatt retyping this after pushing it up so the hashes are live:

I used Sublime to do a case sensitive sort in 370114351cb9601e846ebe3e23ae1d151f7e27ed

But I was afraid that order matters, so I did e0b1a3d3225d2ce47c1cd5d148a959c14ad5c1ff

Can you send me a revert if order does not matter?

**Comment by brianchandotcom** [comment]
@amosfong fixed now

**Comment by nhpatt** [comment]
Order does matter, but just in strange cases. I'll check if they make sense, given than we are also the ones doing the serializing.

**Comment by nhpatt** [comment]
Confirmed that order does matter.

**Pull request closed without merging**
