### PR TITLE
master-qa-25638

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-25638

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:stop

**Comment by austinchiang** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
@brianchandotcom, the three calendar tests fail due to a taglib not being loaded. https://issues.liferay.com/browse/LPS-65961. This issue is still occurring occasionally and we'll need to figure out another way to avoid or fix the issue.

**Comment by austinchiang** [comment]
@brianchandotcom This PR is a resend of https://github.com/brianchandotcom/liferay-portal/pull/40310 with a fix for the upgrades tests.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b4058c1ddd...4e03835a50

**Pull request closed without merging**
