### PR TITLE
LPS-102083 Set heading margin to 0

### PR DESCRIPTION
**Pull request by victorg1991**
@ealonso @sandrodw3

### CODE REVIEW

**Comment by victorg1991** [comment]
Hey @brianchandotcom Could you please backport this? This fixes some usability issues that we have detected in the last few days

Thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a6a34fae4f...d44994e1fa

**Comment by brianchandotcom** [comment]
@victorg1991 can you send me a follow up pull to sort

```
import {
	EDITABLE_FIELD_CONFIG_KEYS,
	EDITABLE_FRAGMENT_ENTRY_PROCESSOR,
	FLOATING_TOOLBAR_BUTTONS,
	FRAGMENTS_EDITOR_ITEM_TYPES,
	CREATE_PROCESSOR_EVENT_TYPES
```

in modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/js/components/fragment_entry_link/FragmentEditableField.es.js

@wincent @jbalsas auto enforce please?

@victorg1991 same with

```
import {
	FLOATING_TOOLBAR_BUTTONS,
	CREATE_PROCESSOR_EVENT_TYPES
```

in EditableRichTextFragmentProcessor.es.js

There are probably more.

**Comment by jbalsas** [comment]
Hey @brianchandotcom, we’re waiting for SP1 to send the changes for this. As soon as you give us the signal we’ll send the updates

**Pull request closed without merging**
