### PR TITLE
Lps 72768

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @Ithildir

@hhuijser can we SF this?

### CODE REVIEW

**Comment by Ithildir** [comment]
Thank you @shuyangzhou!!

cc @michaelhashimoto, @pyoo47

**Comment by shuyangzhou** [comment]
@brianchandotcom backport pull at https://github.com/brianchandotcom/liferay-portal-ee/pull/17214

**Comment by hhuijser** [comment]
@shuyangzhou, sure, what's the rule?

**Comment by shuyangzhou** [comment]
@hhuijser for any *Tei.java file, if you see a "private static final VariableInfo[]" field, wrap it into an inner "private static class Holder {" class, in order to defer the array elements' initialization.

**Comment by hhuijser** [comment]
Okay, sounds good

**Comment by shuyangzhou** [comment]
Thanks @hhuijser !

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4ddda05ce8...1fee2241ef

**Comment by brianchandotcom** [comment]
@hhuijser @shuyangzhou @Ithildir I renamed "Holder" to "Concealer" since it's more descriptive.

**Pull request closed without merging**
