### PR TITLE
LPS-77646 As a developer I would like a way to contribute custom actions to the user action menu

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @willnewbury @noahsherrillwork @JorgeFerrer

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test

**Comment by pei-jung** [comment]
ci:reopen

**Comment by drewbrokke** [comment]
@brianchandotcom the SF failure is happening in several places and is unrelated to this pull.  I forwarded a fix from @jpince to here: https://github.com/brianchandotcom/liferay-portal/pull/55174

**Comment by drewbrokke** [comment]
@brianchandotcom this is the new User Action Menu contributor API. There are no implementations in this pull, but we will immediately use this once it's merged for the UAD portlet (GDPR).

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6d9c40b6db...53cc0a506e

**Pull request closed without merging**
