### PR TITLE
Lps 85008

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by jpince** [comment]
@shuyangzhou @tinatian can you please look into the PMD failure? Not sure if it was caused by this pull.
```
     [echo] PMD VIOLATION: /opt/dev/projects/github/liferay-portal/portal-impl/test/unit/com/liferay/portal/kernel/dao/jdbc/AutoBatchPreparedStatementUtilTest.java:245 > Do not call Assert#fail improperly. (PMD Rule: AssertFailJUnitRule)
     [echo] 
     [echo] PMD VIOLATION: /opt/dev/projects/github/liferay-portal/portal-impl/test/unit/com/liferay/portal/kernel/dao/jdbc/AutoBatchPreparedStatementUtilTest.java:303 > Do not call Assert#fail improperly. (PMD Rule: AssertFailJUnitRule)
```

Shuyang asked @mtambara to take a look at the PMD test in [this pull](https://github.com/brianchandotcom/liferay-portal/pull/65105#issuecomment-440083326), was that fixed?

**Comment by mtambara** [comment]
@jpince The PMD failure is pre-existing, not caused by this pull. PMD test fix is still on the way

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c98fa477a8...8593a7d6a9

**Comment by brianchandotcom** [comment]
Thx @tinatian !

**Pull request closed without merging**
