### PR TITLE
LPS-56624 use the servlet context name instead of manufacturing one

### PR DESCRIPTION
**Pull request by igr**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@igorspasic I'm not sure why the CI is not triggering for this pull? See my other pulls, they all have test results, like:

https://github.com/brianchandotcom/liferay-portal/pull/27894

Try rebasing and then resending. Thx.

@kiyoshilee do you know why this pull is not testing?

**Comment by igorspasic** [comment]
I really don't have an idea.

**Comment by kiyoshilee** [comment]
This never triggered because the pull request was opened to the 6.2.x branch on liferay-portal. We only configured the pull request tester for the master branch of liferay-portal.

**Comment by brianchandotcom** [comment]
@igorspasic for liferay-portal, send to master.

For liferay-portal-ee, send to ee-6.2.x. We don't allow for just 6.2.x.

Thx

**Pull request closed without merging**
