### PR TITLE
LPS-125579 Adapt modules for new sass build process from npm-scripts (master only)

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Manual forward from https://github.com/liferay-frontend/liferay-portal/pull/680

Passing tests at https://github.com/liferay-frontend/liferay-portal/pull/680#issuecomment-757020293

This removes un-used gradle tasks and only runs buildCSS and copyCSS if the module is not using npm-scripts to build the frontend assets.

------------------------------------------

This is a follow up from https://github.com/liferay-frontend/liferay-portal/pull/617

- Updates npm-scripts to [36.8.0](https://github.com/liferay/liferay-frontend-projects/releases/tag/npm-scripts%2Fv36.8.0)
- Updates gradle plugins to only run the buildCSS and copyCSS tasks if the `build` npm script doesn't exist
- Removes any specified buildCSS and copyCSS tasks from modules that rely on npm-scripts

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/98d8251441...b8a1e218ff

**Comment by brianchandotcom** [comment]
@bryceosterhaus @petershin I assume master only and not for 7.3.x? If it's for other branches too, please backport.

**Comment by bryceosterhaus** [comment]
@brianchandotcom, yep master only. Thank you!

**Pull request closed without merging**
