### PR TITLE
LPS-127323 Deprecate old method

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:reopen

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:reopen

**Comment by rafaprax** [comment]
ci:test:sf ran here https://github.com/rafaprax/liferay-portal/pull/1089

**Comment by brianchandotcom** [comment]
public Collection<KaleoTaskAssignment> getTaskAssignments(

Same reason as before.

**Pull request closed without merging**
