### PR TITLE
LPS-91287 Create draft layout for content and asset display pages

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:relevant @kyle-miho @brianchiu please review retest results, I'm particularly concerned about these two 
`LayoutPageTemplateEntryStagedModelDataHandlerTest.testCleanStagedModelDataHandler`
`LayoutPageTemplateEntryStagedModelDataHandlerTest.testStagedModelDataHandler`

**Comment by kyle-miho** [comment]
ci:close

**Comment by kyle-miho** [comment]
ci:test:bundle

**Comment by kyle-miho** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by kyle-miho** [comment]
@pavel-savinov There may be an infinite recursive call here. https://github.com/brianchandotcom/liferay-portal/pull/68853/commits/38f3276374079c59952a9bd06c03bf805577ea5a

When adding an Asset Display Page or Content Page (for some reason Widget as well), the user gets stuck in the screen to add the page, likely because we may be calling addLayout() infinitely. This also affects multiple functional tests and the two integration tests Jason mentioned

`Caused by: com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: org.hibernate.exception.GenericJDBCException: Could not execute JDBC batch update
        at com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl.processException(BasePersistenceImpl.java:443)`
`Caused by: java.sql.BatchUpdateException: Lock wait timeout exceeded; try restarting transaction
        at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:2054)
        at com.mysql.jdbc.PreparedStatement.executeBatch(PreparedStatement.java:1467)
        at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:125)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)`

**Pull request closed without merging**
