### PR TITLE
master-qa-25876

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LRQA-25876

@brianchandotcom 
This resolves the remaining DB Upgrade failures in the PR tester.

I ran a test pull here (with only upgrade tests running) and it passed: https://github.com/brianchiu/liferay-portal/pull/1405

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
@brianchiu the root issue is that we're setting properties that we don't need to set... if it lists it, we should remove those properties, I'm merging this anyways, but ignoring the warning is not really  the right fix.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchiu** [comment]
@brianchandotcom 
Got it. Currently we use a regex to dynamically get those properties from here (in this case it's for 6.1 upgrade):
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/portal-legacy-6.1.properties

So we could either hardcode in our tests or maybe we can update that properties file.

@migue @alee8888 Do either of you have any thoughts?

**Comment by brianchiu** [comment]
Alright. Spoke with Brian about it, and we'll see if the tests pass without the properties. If they do, then we won't set them anymore.

**Pull request closed without merging**
