### PR TITLE
LPS-78137 Minor SF

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test

**Comment by matethurzo** [comment]
@brianchandotcom seems like a CI problem

**Comment by timpak** [comment]
@michaelhashimoto @yichenroy @kenjiheigel FYI possible CI problem

**Comment by pyoo47** [comment]
ci:test

**Comment by yichenroy** [comment]
One of the servers went down during the test causing the build to fail. Retesting.

ci:test

**Comment by yichenroy** [comment]
ci:test

**Comment by yichenroy** [comment]
ci:test (retesting due to CI being down)

**Comment by brianchandotcom** [comment]
@matethurzo @peterborkuti You use "listView" in the Java code and "listview" in the CSS code, can you resend based on whether you consider list view to be 2 words or 1 word like listview.

Thx

**Pull request closed without merging**
