### PR TITLE
LPS-127182 Execute SF to change all build.gradle files

### PR DESCRIPTION
**Pull request by vicnate5**
Tested at https://github.com/vicnate5/liferay-portal/pull/1628

### CODE REVIEW

**Comment by vicnate5** [comment]
@jkappler

**Comment by vicnate5** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6e513d5743...776ec11f84

**Comment by brianchandotcom** [comment]
@jkappler @vicnate5 btw, if you type "ant format-source-bnd" in portal-impl, it runs SF on a smaller subset of files and is faster.

I backported this all the way to 7.2.x.

**Pull request closed without merging**
