### PR TITLE
LPS-195040 (Tests) Unable to import custom object with multiselect picklist field because of ClassCastException

### PR DESCRIPTION
**Pull request by matijapetanjek**
Here is the fixed PR with [the correct test package](https://github.com/brianchandotcom/liferay-portal/pull/141003#issuecomment-1727773387). Sending directly because test already passed CI.

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/663662e391...513ee486c1

**Comment by brianchandotcom** [comment]
@matijapetanjek see changes in my origin. Please retest (I may have broken it)

**Comment by matijapetanjek** [comment]
True, makes sense to be random.

**Pull request closed without merging**
