### PR TITLE
LPS-78733 Update test

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
@kyle-miho could you please take a look to broken tests? I have other pulls waiting for it. I’ve changed the breadcrumb markup

**Comment by kyle-miho** [comment]
@ealonso looking at this now! will have in by eod

**Comment by kyle-miho** [comment]
ci:close

**Comment by kyle-miho** [comment]
@ealonso I am going to send you a pull request with the fixes soon. Not resending to BChan because the new taglib needs to be applied to Knowledge Base as well. This pull would cause 2 of their acceptance tests tof ail.

**Pull request closed without merging**
