### PR TITLE
LPS-65693 regenerate

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:stop (upstream had an issue)

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:stop

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:stop

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:stop the fix for copy was wrong but is not needed in this code anymore.

**Comment by rotty3000** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/40154

**Comment by pyoo47** [comment]
One of the jenkins servers crashed. ci:stop ci:retest

**Pull request closed without merging**
