### PR TITLE
LPS-80235 Add relationship resources

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@shuyangzhou we're getting close to getting this green again!

Can you check out the lpkg-startup error?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2489b96826...ab39252615

**Comment by brianchandotcom** [comment]
@matethurzo this is very very nice....

**Comment by shuyangzhou** [comment]
@brianchandotcom the lpkg-startup failure is from smoke test, QA needs to look into it. @alee8888 ?

**Comment by alee8888** [comment]
@shuyangzhou @brianchandotcom 
That smoke test failure is the same one that has been failing on Weblogic. We removed that here but this pull ran before it https://github.com/liferay/liferay-portal/commit/2489b96826704ac1d6ea783cd77e8fde5c32489c#diff-66d24afc65d5a682dc718d87a8b0adee.

**Pull request closed without merging**
