### PR TITLE
LPS-104938 Search admin active connections info

### PR DESCRIPTION
**Pull request by joshchong**
Tested in the following PR. All failures are unrelated. :heavy_check_mark:
<br>**ci:test:search** - 45 out of 50 jobs passed</br> https://github.com/joshchong/liferay-portal/pull/225#issuecomment-582682787
<br>**ci:test:search-es7** - 44 out of 51 jobs passed</br> https://github.com/joshchong/liferay-portal/pull/225#issuecomment-582697550
<br>**ci:test:search-solr** - 29 out of 35 jobs passed</br> https://github.com/joshchong/liferay-portal/pull/225#issuecomment-582693857

Authors: @BryanEngler @thektan @suilin @joshchong

<hr>

_[Story] As a Search Admin, I want to see connection info for currently active connections_
https://issues.liferay.com/browse/LPS-104938

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e0427abee8...0a4ec52971

**Comment by brianchandotcom** [comment]
@BryanEngler @thektan @arboliveira

See f89c693467968848b40ca1f753a65e067a2b9a45 and a5ea558600b1fa9a145ea516ca1ba74e2ff8c82d

This one is important 0a4ec52971bdf883817950a2fd904e009c5f29a4

I want to avoid breaking changes now that 7.3 GA1 is out. My fix should make it more accurate too.

Please send me a follow up pull if I'm wrong.

@csierra @jorgeferrer fyi based on what we talked about yesterday see 0a4ec52971bdf883817950a2fd904e009c5f29a4

**Comment by csierra** [comment]
hey @BryanEngler @thektan @arboliveira, 
is `SearchEngineInformation` in 0a4ec52 an extension point or is it considered an _internal_ interface just to be shared across our modules?

Thx.

Carlos.

**Comment by csierra** [comment]
hi again @BryanEngler @thektan @arboliveira,

do you expect `SearchEngineInformation` in 0a4ec52 be implemented by users?

Thx.

Carlos.

**Comment by BryanEngler** [comment]
hey @csierra 
i think the only case where SearchEngineInformation would be implemented by someone else is if they also implemented an entire connector to an alternate search engine, which ive never heard of anyone doing, and dont really expect anyone to do... so in theory it could be implemented, but in practice i would say it wont be. does that answer your question?

**Comment by csierra** [comment]
hey @BryanEngler, 
yes... so then annotating it with `@ProviderType` is the correct thing to do. 

Thx. 
Carlos.

**Pull request closed without merging**
