### PR TITLE
LPS-88665 Fix rebase removing import

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
Auto tagger tests fails are not unique to this pull.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0a07531f6c...33cb77a357

**Comment by brianchandotcom** [comment]
@Preston-Crary I had to roll this back because it caused issues in 7.0.x.

It bumped com.liferay.portal.kernel.model from 1.0.2 to 1.1.0, which breaks a lot of stuff. That package cannot be bumped even to a minor version because of BaseModel.

Please resend. Thx.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/7311

**Pull request closed without merging**
