### PR TITLE
LPS-65490

### PR DESCRIPTION
**Pull request by Ithildir**
cc @mikemanyoung

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5b79c9f4b0...1c1c36d77e

**Comment by mikemanyoung** [comment]
@Ithildir  for 40fe5b40 where did this functionality move to?

**Comment by Ithildir** [comment]
SF can't still understand old-style Ant plugins inside the `modules` directory, it tries to format "too much" (the `ClpSerializer` class, for example). I asked @hhuijser to fix it.

**Comment by mikemanyoung** [comment]
@Ithildir sorry pasted wrong hash, I meant 3d9d0d1

**Comment by Ithildir** [comment]
It has been moved in [`third-party/oasis-names-tc-wsrp`](https://github.com/liferay/liferay-portal/tree/master/modules/third-party/oasis-names-tc-wsrp), which Brian already published: https://repository.liferay.com/nexus/service/local/repositories/liferay-releases-ce/content/com/liferay/oasis.names.tc.wsrp/1.0.0/oasis.names.tc.wsrp-1.0.0.jar

**Pull request closed without merging**
