### PR TITLE
LPS-79566 Success Message Covers Management Toolbar

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LPS-79566

cc @jbalsas 
Chema, see my comment below.

### CODE REVIEW

**Comment by brianchiu** [comment]
@jbalsas 

So far I was able to find just one other thing that needs to be fixed. It has to do with DDL Display portlet. Most other things pass, and the remaining failures I think aren't worth holding up this pull.

Steps:
1. Add DDL Display Portlet
2. Click "Add List"
3. Enter a title and select a data definition
4. Click Save

The iframe will lock. See gif below:


@vicnate5
Some other workflow tests will fail.

@alee8888
The UIInfrastructure smoke test will fail.

**Comment by brianchiu** [comment]
cc @jpince

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f9860e0880...7d0d80f220

**Comment by vicnate5** [comment]
@jbalsas Ticket for the regression introduced by this pull https://issues.liferay.com/browse/LPS-81410

**Comment by jbalsas** [comment]
Thanks @vicnate5, I'll take a look asap!

**Pull request closed without merging**
