### PR TITLE
LPS-176921 Adapt _updateLocalizationTable so we can use the batch approach, and about user locale we should use this way to avoid issues when there is no themeDisplay

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4a933e1c52...509e5b1538

**Comment by brianchandotcom** [comment]
@MarinhoFeliphe see changes in my origin, in particular 6d86c0ec and I added some duplicate code in 36437f1b which we may want to move to another class.

**Comment by pedro-oliveira446** [comment]
Just starting reviewing :)

**Pull request closed without merging**
