### PR TITLE
LPS-108949 Update tests

### PR DESCRIPTION
**Pull request by dgarciasarai**
CI passing here https://github.com/dgarciasarai/liferay-portal/pull/167

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@dgarciasarai rebase error, please resend, sorry!

**Comment by dgarciasarai** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dgarciasarai** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/85399

**Pull request closed without merging**
