### PR TITLE
LPS-146669 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-146669

This is only for master.

@ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure test is unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/7329
❌ ci:test:stable - 21 out of 26 jobs passed
❌ ci:test:relevant - 21 out of 27 jobs passed in 2 hours 7 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/32fc7fa70f...c7d165c3f1

**Comment by brianchandotcom** [comment]
@ealonso @crodriguezy see c7d165c3f1ec364eaf60d28ec55c9e3a56484d02

**Pull request closed without merging**
