### PR TITLE
COMMERCE-549

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
https://issues.liferay.com/browse/COMMERCE-549

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d342aa2a97...148367bc20

**Comment by brianchandotcom** [comment]
@ZoltanTakacs please see my changes in upstream.

**Comment by ZoltanTakacs** [comment]
Thank you!

**Pull request closed without merging**
