### PR TITLE
LPS-58562 Tests for Embedded Portlets

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
Hi @brianchandotcom, is there anything we can do for this pull?

**Comment by jkappler** [comment]
Hi @brianchandotcom, let me also know if there's something I can do. I'm waiting for this to pass so I can add another test for one of the changes that I sent you at the start of the week.

Thanks!!

**Comment by brianchandotcom** [comment]
@mdelapenya can you see my changes to upstream and resend one of the tests? cc @jkappler

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9dd72b094c...340e216b49

**Pull request closed without merging**
