### PR TITLE
LRQA-58638 - Reenable related tests from LPS-113267

### PR DESCRIPTION
**Pull request by rodrigocunhaa**

### CODE REVIEW

**Comment by rodrigocunhaa** [comment]
Forwarded from https://github.com/rodrigocunhaa/liferay-portal/pull/57. The same reason as https://github.com/brianchandotcom/liferay-portal/pull/88624.

**Comment by rodrigocunhaa** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c507c5f402...254650dcbf

**Pull request closed without merging**
