### PR TITLE
LRQA-33825 Fetch cached branch from Local Git when available

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRQA-33825

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
@michaelhashimoto this doesn't compile, please resend

```
:test:jenkins-results-parser:compileJava
/home/brian/dev/projects/github/liferay-portal/modules/test/jenkins-results-parser/src/main/java/com/liferay/jenkins/results/parser/LocalGitSyncUtil.java:720: error: incompatible types: List<RemoteConfig> cannot be converted to RemoteConfig
                                                localGitRemoteConfigs);
                                                ^

```

**Comment by michaelhashimoto** [comment]
Fixed in this pull request:
https://github.com/brianchandotcom/liferay-portal/pull/50654

**Pull request closed without merging**
