### PR TITLE
Lps 79653

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@pyoo47 what is this?

**Comment by michaelhashimoto** [comment]
@brianchandotcom @pyoo47 @shuyangzhou - This is failing because we are trying to parse the `package.json` files to see if a particular module can run an `npmTest`, however there are some [package.json](https://github.com/liferay/liferay-portal/blob/master/modules/sdk/project-templates/project-templates-npm-angular-portlet/src/main/resources/archetype-resources/package.json) files that do not have valid JSON.


We have a fix ready that will continue if there is invalid JSON with this ticket:
https://issues.liferay.com/browse/LRQA-40710

However, those changes are not live yet.

**Comment by brianchandotcom** [comment]
@ngriffin7a I merged the change to master-private (I think that's fine)

But there were a lot of changes in this pull that I didn't find necessary. For example...

LPS-79653 Portlet 3.0: Upgrade to the Portlet 3.0.0 API (cast to PortletURL due to Portlet 3.0 changes to the MimeResponse.createRenderURL() method signature return value type)

and

LPS-79653 Portlet 3.0: Upgrade to the Portlet 3.0.0 API (cast to PortletURL due to Portlet 3.0 changes to the MimeResponse.createRenderURL() method signature return value type)

We have a lot (PortletURL)xyz

When we can just update navigationItem.setHref to have a new method so we dont' have a lot of casting and updates?

**Comment by shuyangzhou** [comment]
@hhuijser can we SF to make sure all those package.json files are valid? I think it could be as simple as just using the json parser to parse it, as long as the parser does not throw an exception, we are fine. We basically just need an earlier development/ci checkpoint for this kind of failure, and SF can explain the failure in a much cleaner way, rather than making people confuse this as a Jenkins failure.

**Comment by ngriffin7a** [comment]
@brianchandotcom I tried avoiding the cast to `PortletURL` but the problem is that NavigationItem.java also has a `setHref(String)` method and as long as that is there, the lambda expressions would get confused and not know which method to call. https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/servlet/taglib/util/NavigationItem.java#L59

**Comment by ngriffin7a** [comment]
@brianchandotcom Please consider merging. It has taken 2+ weeks to get this PR through CI and I can work more on the NavigationItem concern afterword. Need this merged so that I can send all subsequent PRs related to Portlet 3.0.

**Comment by jpince** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
Looks like we could just update the method to this to avoid updates to usages:
```
public void setHref(Object href) {
	put("href", href.toString());
}
```

**Comment by hhuijser** [comment]
@shuyangzhou, makes sense, I'll work on that

**Comment by ngriffin7a** [comment]
@Preston-Crary I think that will work, as long as it is the only `setHref` method. @brianchandotcom happy to refactor. Would prefer to do in a subsequent commit if you would permit that.

**Comment by hhuijser** [comment]
@shuyangzhou @pyoo47 @michaelhashimoto @Ithildir

List of invalid json:

```
Expected a ',' or '}' at 384 [character 57 line 15]: C:/github/liferay-portal/modules/sdk/project-templates/project-templates-npm-billboardjs-portlet/src/main/resources/archetype-resources/package.json (SourceCheck:JSONValidationCheck)
Expected a ',' or '}' at 405 [character 57 line 15]: C:/github/liferay-portal/modules/sdk/project-templates/project-templates-npm-isomorphic-portlet/src/main/resources/archetype-resources/package.json (SourceCheck:JSONValidationCheck)
Expected a ',' or '}' at 373 [character 57 line 15]: C:/github/liferay-portal/modules/sdk/project-templates/project-templates-npm-jquery-portlet/src/main/resources/archetype-resources/package.json (SourceCheck:JSONValidationCheck)
Expected a ',' or '}' at 1692 [character 64 line 57]: C:/github/liferay-portal/modules/sdk/project-templates/project-templates-npm-angular-portlet/src/main/resources/archetype-resources/package.json (SourceCheck:JSONValidationCheck)
Expected a ',' or '}' at 335 [character 57 line 12]: C:/github/liferay-portal/modules/sdk/project-templates/project-templates-npm-portlet/src/main/resources/archetype-resources/package.json (SourceCheck:JSONValidationCheck)
Expected a ',' or '}' at 633 [character 69 line 23]: C:/github/liferay-portal/modules/sdk/project-templates/project-templates-npm-metaljs-portlet/src/main/resources/archetype-resources/package.json (SourceCheck:JSONValidationCheck)
Expected a ',' or '}' at 434 [character 57 line 17]: C:/github/liferay-portal/modules/sdk/project-templates/project-templates-npm-react-portlet/src/main/resources/archetype-resources/package.json (SourceCheck:JSONValidationCheck)
Expected a ',' or '}' at 370 [character 57 line 15]: C:/github/liferay-portal/modules/sdk/project-templates/project-templates-npm-vuejs-portlet/src/main/resources/archetype-resources/package.json (SourceCheck:JSONValidationCheck)
```

**Comment by brianchandotcom** [comment]
@ngriffin7a sorry Neil :( Invalid JSON issue. Also, if casting is required, it can be dangerous because I've merged in other pulls that may have added changes to navigationItem since you last sent this.

Please resend it to me directly and I'll merge it asap. Sorry Neil!

**Comment by Ithildir** [comment]
@hhuijser, those are not real `package.json` files, but Velocity templates in Maven archetypes. I think @michaelhashimoto already talked to @gamerson about this.

**Comment by ngriffin7a** [comment]
@brianchandotcom Done, see: https://github.com/brianchandotcom/liferay-portal/pull/58442
/cc @shuyangzhou @jpince @Preston-Crary

**Comment by hhuijser** [comment]
@Ithildir, if I check for valid JSON, which files should I be skipping them?

**Comment by Ithildir** [comment]
All the ones in `modules/sdk/project-templates`.

**Comment by hhuijser** [comment]
@ngriffin7a @michaelhashimoto @pyoo47 @Ithildir @shuyangzhou, in the meantime, JSON validation has been added to SF as well: https://github.com/liferay/liferay-portal/commit/b5203499359bd39ad785cb1625a578225c84eafe

**Pull request closed without merging**
