### PR TITLE
LPS-86806

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by jpince** [comment]
ci:close @hhuijser can you please look into this PMD test failure? It fails on a file you changed.

`PMD VIOLATION: /opt/dev/projects/github/liferay-portal/portal-impl/test/integration/com/liferay/portal/verify/VerifyUUIDTest.java:309 > Do not call Assert#fail improperly. (PMD Rule: AssertFailJUnitRule)`

**Comment by hhuijser** [comment]
Last time that part of the code was changed was by @shuyangzhou here: https://github.com/liferay/liferay-portal/commit/00bcc8e22ba7a2f1404dc7d418d6914f89141c44#diff-5faf70e289ab378b8b86fb1947054eea

**Comment by hhuijser** [comment]
ci:reopen

**Comment by jpince** [comment]
@shuyangzhou or @petershin can you please look into the PMD failure?
`PMD VIOLATION: /opt/dev/projects/github/liferay-portal/portal-impl/test/integration/com/liferay/portal/verify/VerifyUUIDTest.java:309 > Do not call Assert#fail improperly. (PMD Rule: AssertFailJUnitRule)`

**Comment by brianchandotcom** [comment]
hey @hhuijser 

```
		VerifiableUUIDModel[] verifiableUUIDModels = new VerifiableUUIDModel
			[PropsValues.VERIFY_PROCESS_CONCURRENCY_THRESHOLD];
```

I think treating [ like ( is better.

Please resend. Thx.

**Comment by brianchandotcom** [comment]
ci:reopen (talked to Hugo), he likes [ to be different from ( since we can have multi dimensional arrays.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/998d631c42...53dc4986d9

**Pull request closed without merging**
