### PR TITLE
LPS-57077

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@brianchandotcom I look at the script and the test command only uses macrodefs and but we run ant compile for certain plugins which does call the compile script from the module.

**Comment by brianchandotcom** [comment]
@david-truong can you resend:

1.) the gitignore should be local to the module (not global).

2.) instead of readme.txt, have it read from a file with the paths. That way, people can always update that file instead of changing Java code (and it also makes it more obvious where to grab it, which serves the purpose of the readme.txt file).

Otherwise, this looks good. Thx bebe.

**Comment by david-truong** [comment]
@brianchandotcom what did you mean by 2?

I was just trying to show the gems included easily for when they view it on github:
https://github.com/david-truong/liferay-portal/tree/LPS-57077/modules/util/ruby-gems

**Comment by david-truong** [comment]
I generated the readme.txt.  I hope thats what you meant.

**Pull request closed without merging**
