### PR TITLE
LPS-172635 Copied a Master with a thumbnail in the staging site cause a failure in the publishing process

### PR DESCRIPTION
**Pull request by Tim-Cao**
This is only for master.

https://issues.liferay.com/browse/LPS-172635

@jkappler

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/11089

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bb680248d6...ea8c41ff41

**Comment by brianchandotcom** [comment]
@jkappler beautiful

**Pull request closed without merging**
