### PR TITLE
LPS-98844 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-98844
cc: @jkappler @pavel-savinov

### CODE REVIEW

**Comment by kyle-miho** [comment]
Hey @brianchandotcom I'm going to send some follow up integration tests to pavel, so the helper function in here is going to be re-used multiple times even though it is only used once here, and the same applies for the setup. This fixes an integration failure upstream, so Jurgen had me send the fix to you.

**Comment by kyle-miho** [comment]
cI:reopen

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c2e0209682...f318c1d705

**Comment by jkappler** [comment]
Thanks @kyle-miho!

**Pull request closed without merging**
