### PR TITLE
LPS-196283: Allow string fields to be passed as JSON or JSON-String format for WorkflowDefinition

### PR DESCRIPTION
**Pull request by sergiojimcos**
## Motivation
The aim of this PR is to create a mechanism in order to parsed different Data Structured as a Content in Workflow Definition. This formats are: `XML (String)`, `JSON` format and `JSON String` format. This structures will be parsed and deserialized in String Deserializer that will be annotated.

---
**What is new?**
- Create JSONStringStdDeserializer.
- Some changes in Yaml and Schema context to add some Getter and Setters to add the JsonCustomize deserializer for those properties that are going to be annotated with `x-json-string` annotation.
- Add new validation `BatchEngineImportTaskItemReaderUtil` to parse to String format those parameters whose contents are not in String format.
- Add some test cases for Workflow Definition API and Batch.

**Which modules hava to been deployed?**
- Deploy `portal-vulcan-api`
- Deploy `batch-engine-api`
- Deploy `headless-admin-workflow-api` and `headless-admin-workflow-impl`

**Related JIRA Ticket**
https://liferay.atlassian.net/browse/LPS-198504

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:reopen

**Comment by sergiojimcos** [comment]
Sent from here: https://github.com/liferay-headless/liferay-portal/pull/1580

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/65c9dcc814...58400c2909

**Comment by brianchandotcom** [comment]
@sergiojimcos can you 

1. Make sure x-json-string is ONLY available if rest-config.yaml has a bigger compat level?

compatibilityVersion:

This should not work in 7.3.x and older.

2. For

JSONMessageBodyReaderTest.java

change

xyz:hello

to

xyz: hello

Basically, add a space after every colon.

3. @rafaprax is going to now fix these 2 files

liferay-clarity-workspace/client-extensions/liferay-clarity-batch/batch/workflow-definition.batch-engine-data.json
liferay-sample-workspace/client-extensions/liferay-sample-batch/batch/workflow-definition.batch-engine-data.json

He will then write an upgrade to no longer store XML in "content" but store a JSON string

For you @sergiojimcos , IF content is a JSON string, on read, I want you to return JSON. That way, we encourage ppl via headless to use the new format.

**Pull request closed without merging**
