### PR TITLE
LPS-58330

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
/cc @shuyangzhou

This one I find more useful than source-format-local-changes.

If you execute ant format-source-latest-author, it will only SF the files in the commits of the latest author in your branch.

**Comment by shuyangzhou** [comment]
Yes, this is a very brilliant idea! Thanks @hhuijser !

**Comment by brianchandotcom** [comment]
Very nice @hhuijser  :)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/93ddaaa8c4...06496ad51c

**Pull request closed without merging**
