### PR TITLE
LPS-87930 Adding a WC via WCD fails to include JSP due to NPE, causing certain fields to be missing such as Scheduling / Related Assets

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:relevant @pyoo47

**Comment by jkappler** [comment]
@pavel-savinov, closing because we got unique error. 

cc @brianchiu

**Comment by brianchiu** [comment]
@jkappler @pavel-savinov I'm checking.

**Comment by brianchiu** [comment]
Hey @jkappler @pavel-savinov 

The reason the test failed is that web content structures do not appear in the structure admin page until after a search reindex. The structure will show up as an option when adding web content, but if you try to change structures within a web content, the created structures will not appear.

**Comment by brianchiu** [comment]
This issue is happening at head. See: https://issues.liferay.com/browse/LPS-87955

ci:reopen

**Comment by brianchiu** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e210632c63...c7a2c68213

**Pull request closed without merging**
