### PR TITLE
LPS-59672 Sort dependencies

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by jbalsas** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Sent to @Ithildir at https://github.com/Ithildir/liferay-portal/pull/160 to double check

Thx

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/33768.

**Pull request closed without merging**
