### PR TITLE
LPS-77912 No success message navigation menu item

### PR DESCRIPTION
**Pull request by p2kmgcl**
/cc @ealonso
/cc @pavel-savinov

### CODE REVIEW

**Comment by jpince** [comment]
ci:close @anthony-chu @brianchiu test fix needed

**Comment by brianchiu** [comment]
@jpince I'll take a look at this.

**Comment by ealonso** [comment]
Hey @brianchiu @jpince,

Any updates about this pull?

Regards,
Eudaldo.

cc @p2kmgcl @pavel-savinov

**Comment by brianchiu** [comment]
Hi @ealonso 
I gave some feedback to Pablo and Pavel on Friday. The reason why the test fail is because after clicking "Add" the frame just stays. They said they will take another look at it. I'll send you a message on slack so you can see it if you want.

cc @pavel-savinov @p2kmgcl

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
