### PR TITLE
LPS-72606

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by pyoo47** [comment]
Pull request tests are not triggering automatically so I'm going to attempt to trigger them manually.

**Comment by hhuijser** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
Thanks @hhuijser !

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1be0d38c0e...e7d4d864aa

**Pull request closed without merging**
