### PR TITLE
LPS-63867 Adds missing loader configiration in text field

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:retest

**Comment by brunobasto** [comment]
@vicnate5

ParagraphDDMFormFieldTypeSettingsTest.testCreateParagraphDDMFormFieldTypeSettingsDDMForm

This PR changes the paragraph field configuration to use an alloy editor now. Do we need to update the tests?

**Comment by vicnate5** [comment]
@brunobasto Looks like just the unit test needs to be updated. The poshi failure is unrelated.

**Comment by brunobasto** [comment]
Oh, I see. Thanks!

**Pull request closed without merging**
