### PR TITLE
LPS-70727 Simplify BodyContentWrapper to avoid chain wrapping to the …

### PR DESCRIPTION
**Pull request by shuyangzhou**
…dummy BodyContentImpl

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@pyoo47 @stsquared99 do we have bad slaves? See the SSH errors.

**Comment by stsquared99** [comment]
No, that's just cuz we load balance the git nodes. I think it just took too long, maybe random load or a particularly large fetch.

**Pull request closed without merging**
