### PR TITLE
LPS-170575 | Add Autom. test ClayAlertToast#DisappearsAfter5SecsWithoutActions

### PR DESCRIPTION
**Pull request by deborasoliveira**
Forwarded manually https://github.com/liferay-frontend/liferay-portal/pull/2943 
Relevant failures are not related.

---
**ClayAlertToast#DisappearsAfter5SecsWithoutActions**
**Test Plan**

- Given Clay Sample Portlet
- When a toast alert appears
- And no actions on alert
- Then the alert disappears after 5 secs

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-170575

### CODE REVIEW

**Comment by deborasoliveira** [comment]
ci:open

**Comment by deborasoliveira** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f3f84ce62b...5ead13141b

**Comment by brianchandotcom** [comment]
@deborasoliveira see 5ead13141bf12a9c28a1e1ca7bbace5c8c83b42b

**Pull request closed without merging**
