### PR TITLE
Lps 162804 9 14

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@tinatian can we make it so that if they don't regenerate, it'll still work? Thx.

**Comment by brianchandotcom** [comment]
@shuyangzhou see comment above. Thx.

**Comment by tinatian** [comment]
@brianchandotcom  This pull is a preparation step for adding support to populate finder cache manually, even if I have a way to do that part without generating, the second part (support to populate finder cache) will also need a re-generation, it is inevitable. I am wondering if any reason you do not want a re-generation?

**Comment by tinatian** [comment]
ci:reopen

**Comment by tinatian** [comment]
ci:close

**Pull request closed without merging**
