### PR TITLE
LPS-89710 Folder CRUD implementation and Client tests

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
@cgoncas @adolfopa

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0f98db0f21...753aed6b8d

**Comment by brianchandotcom** [comment]
@ruben-pulido I made a lot of changes based on improvements by @ahdezma to exception mappers.

See e3595a7754ef7f85c74cedad020e54b33a2c8807 and 491e514cb3fdade7c48b80577aad145ac1161004

Please test my changes @ruben-pulido 

@ahdezma I don't like:

```
		"osgi.jaxrs.name=Liferay.Vulcan.NoSuchModelExceptionMapper)",
		"osgi.jaxrs.extension.select=(osgi.jaxrs.name=Liferay.Vulcan.PaginationContextProvider)",
		"osgi.jaxrs.extension.select=(osgi.jaxrs.name=Liferay.Vulcan.PortalExceptionMapper)",
		"osgi.jaxrs.extension.select=(osgi.jaxrs.name=Liferay.Vulcan.PrincipalExceptionMapper)",
```

Does it work  if we just did Liferay.Vulcan.*ExceptionMapper. Can we wildcard it? Can you ping @csierra?

This would be better so I could just add new exception mappers without forcing people to regenerate. Thx.

@ruben-pulido I didn't merge in the tests yet. My goal is to generate a base for these, and then the dev would just extend the base test and override a few methods to give certain test fields. So much of this is templatable. Thx.

**Comment by ruben-pulido** [comment]
@brianchandotcom 
Thanks for applying the exception mappers.
I've tested your changes and haven't found any problem.

**Pull request closed without merging**
