### PR TITLE
LPS-65920 Chat Test build project

### PR DESCRIPTION
**Pull request by peterfellwock**
@brianchandotcom I ran chat-test testIntegration locally and they passed, let's see what ci says.

### CODE REVIEW

**Comment by kenjiheigel** [comment]
@peterfellwock, don't think CI likes it haha... So yeah, last I mentioned, we weren't planning to deploy the chat portlet in the build because it causes poshi test failures. We're open to re evaluating that if that's what you or a stakeholder of this wants. 

For now, @brianchandotcom, please don't merge this (at least not with chat as an included module in the build). If we want chat deployed in the build, we need to fix on the poshi end. It was decided not to, but to just have one test. We can discuss this more if necessary. 

cc-ing @jpince @joelhendley

**Comment by jpince** [comment]
@jhendley

**Comment by peterfellwock** [comment]
@brianchandotcom I spoke with @kenjiheigel and the issue is with Poshi and the nature of how Chat comes into the layout. @kenjiheigel said he will research a possible fix to Poshi to work with Chat. Closing pull, do not merge. Thank you.

**Comment by kenjiheigel** [comment]
For reference, I'll be trying to find a solution in this ticket:
https://issues.liferay.com/browse/LRQA-26743

**Pull request closed without merging**
