### PR TITLE
LPS-199540

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:reopen

**Comment by BryanEngler** [comment]
ci:test:sf

**Comment by BryanEngler** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@BryanEngler can you resend

```
			int numberOfDocsCollected = 0;
			int numberOfTotalDocsNeeded = end;
			int originalHitsLength = 0;
			int recalculatedHitsLength = 0;
```

So here we have numberXyz and then xyzLength

Previously, it was

```
			int amplifiedCount =
				_permissionFilteredSearchResultAccurateCountThreshold;
			double amplificationFactor = 1.0;
			int excludedDocsSize = 0;
			int filteredDocsCount = 0;
			int hitsSize = 0;
			int offset = 0;
			int searchCount = 0;
			long startTime = 0;
```

xyzCount and xyzSize so it was consisstent.

Please resend. Thx.

**Pull request closed without merging**
