### PR TITLE
LRQA-17279

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LRQA-17279.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by AngeloYoun** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by michaelhashimoto** [comment]
<p>The Pull Request Tester will be down until <strong>December 28, 2015 @ 5:00 PM PDT</strong>.</p>

<p>See this <a href="https://issues.liferay.com/browse/LRQA-18839">JIRA Ticket</a> for more information.</p>

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/62175236f4...491a89afc3

**Pull request closed without merging**
