### PR TITLE
LPS-93356 Use provider in user admin

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:reopen

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
@jpince I've followed the steps in the [Poshi test](https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/tests/enduser/workflow/WorkflowUser.testcase) but I haven't been able to reproduce the error. I'm not sure if it has to do with my changes. How could I confirm? Thanks

**Comment by jpince** [comment]
@epgarcia the test is failing in upstream, so I don't think the failure is related to your changes
https://issues.liferay.com/browse/LRQA-48252

**Comment by epgarcia** [comment]
Thanks @jpince!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8924fd8660...8d7ff9667a

**Pull request closed without merging**
