### PR TITLE
LPS-63190 add a setting to the theme to choose if the maximize/minimize icons are shown

### PR DESCRIPTION
**Pull request by juliocamarero**
Hi Brian,

we think the key should stay in the core since several themes are already using it and we want to encourage theme developers to add this to their themes also.

Please, let us know if you think otherwise.

thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Thx for the comment @juliocamarero 

I'm fine with leaving it in the core but just wanted to make sure you guys chose to do it (and it wasn't accidental).

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/92cbf0e001...ba79cd86c9

**Comment by brianchandotcom** [comment]
@juliocamarero I would rename it to Show Portlet Maximize/Minimize Links

vs. just Show Maximize/Minimize Links

so it fits with

Show Site Xyz

Can you send a follow up pull if you agree? If not , please email. Thx.

**Comment by juliocamarero** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/36508 :)

**Pull request closed without merging**
