### PR TITLE
LPS-138327 AWS Lambda Commerce Order Demo using simple gradle

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:reopen

**Comment by epgarcia** [comment]
Hi @brianchandotcom @gamerson, is this complete? Are you planning to merge it? I want to work on the equivalent example for GCP. Thanks!

**Comment by gamerson** [comment]
hey @epgarcia  I haven't heard from Bchan since I made the previous modifications.  I haven't tested the output of this project, I've only verified that the JAR that is output is exactly the same as the previous one.  So I would say this is a good template to base the GCP version on.

**Comment by epgarcia** [comment]
See #108029

**Pull request closed without merging**
