### PR TITLE
LPS-64316 Avoid resource leaks by removing usages of registry-api in portal-search module

### PR DESCRIPTION
**Pull request by arboliveira**
Author: @adolfopa 
Reviewer: @arboliveira

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by arboliveira** [comment]
Added fake Gradle cache.

ci:retest

**Comment by arboliveira** [comment]
Missed portal-test... updated portal-search to 3.0.2 in there as well

ci:retest

**Comment by arboliveira** [comment]
Test failures seem unrelated.

**Comment by vicnate5** [comment]
Test failures are unrelated to this pull.

**Comment by brianchandotcom** [comment]
@arboliveira please resend without using a fake cache. Instead, change to use a project dir dependency. search for "project" in build.gradle

Thx

**Pull request closed without merging**
