### PR TITLE
LRQA-51488 Quarantine flaky Workflow test

### PR DESCRIPTION
**Pull request by brianwulbern**
fyi @barrosdennys

### CODE REVIEW

**Comment by brianwulbern** [comment]
[WorkflowUser#CreateNewUserAccount](https://testray.liferay.com/home/-/testray/cases/865153023/view?delta=200&p_p_state=normal&orderByCol=createDate_sortable&orderByType=desc) has failed 3 times today on EE Pull Requests

**Comment by brianwulbern** [comment]
ci:reopen

**Comment by jpince** [comment]
Just started reviewing :)

**Comment by jpince** [comment]
Pushed to Brian Chan's origin
https://github.com/brianchandotcom/liferay-portal/commit/03e8a63c5df0409a376cf6bba5caf78e27988ef0

**Pull request closed without merging**
