### PR TITLE
LPS-67830 Allow administrators to configure captcha using System Settings, allowing export and import of configurations

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by pei-jung** [comment]
@xbrianlee can you take a look at the test failure? we might need to update the functional test.

**Comment by brianwulbern** [comment]
The test is failing because the captcha text verification field is required and not populated:

captcha_text_verification

**Comment by xbrianlee** [comment]
ci:close

@pei-jung Interesting...this test should have `maxChallenges` set to `1`. I'll retest this.

**Comment by xbrianlee** [comment]
Resent in https://github.com/brianchandotcom/liferay-portal/pull/47801.

**Pull request closed without merging**
