### PR TITLE
LPS-91996 Regen

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
@brianchandotcom This is only the renaming from AssetListEntryAssetEntryRel to AssetEntryAssetListEntryRel, without the other changes. I think it's better if you review this first, to make sure the naming and param sorting is correct. I'll then add my changes on top of this. 

Thanks!

@ealonso

**Comment by epgarcia** [comment]
ci:reopen

**Comment by epgarcia** [comment]
@brianchandotcom the CI error points to 

`Exception in thread "main" java.lang.NoClassDefFoundError: com/liferay/portal/kernel/util/NaturalOrderStringComparator
     [exec] 	at com.liferay.portal.tools.java.parser.JavaType.compareTo(JavaType.java:34)`

This does not have to do with my changes

**Comment by brianchandotcom** [comment]
@epgarcia regarding the Service Builder bug, it only happens in CI, because on CI, it uses the one on disk, and not the published Service Builder. The one on disk recently got updated to the latest Java Parser, which requires this in the Service Builder bnd to fix it dfb520a0330a40bb6d7bd6b6e389d78ae98c7639 (there's no way you would have known this, and I only know because Peter Shin fixed it for REST Builder... which had the same problem). Just fyi.

Ok, now I"m going to review your pull.

**Comment by brianchandotcom** [comment]
I'm soooooooo sorry @epgarcia 

I'm glad you did this in steps :(

I didn't look carefully to see we are inside asset-list-*

In that case, then AssetListEntry......AssetEntry...Rel is the right now. 

So let's just order the params to be

assetListEntryId, assetEntryId, segmentsEntryId 

My bad!

**Pull request closed without merging**
