### PR TITLE
LPS-162747

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
FYI @shuyangzhou

**Comment by tinatian** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e4cf314ce2...0fadd3c32b

**Comment by brianchandotcom** [comment]
@tinatian @yuhai just 0fadd3c

**Pull request closed without merging**
