### PR TITLE
LPS-78312

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@pyoo47, why can't I use Java 8 in SourceFormatter.

See https://github.com/brianchandotcom/liferay-portal/pull/55777/commits/d2f42bb6912dc567382ab0ad6206337e9d1f8dc1 and https://github.com/brianchandotcom/liferay-portal/pull/55735

**Comment by hhuijser** [comment]
@ci:test

**Comment by hhuijser** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a8623fc532...bd4630738d

**Pull request closed without merging**
