### PR TITLE
LPD-31818 Adding support for /any() in objects 

### PR DESCRIPTION
**Pull request by 4lejandrito**
https://liferay.atlassian.net/browse/LPD-31818

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3b6f1d86af...f4fd4fdf56

**Comment by brianchandotcom** [comment]
@4lejandrito just e1088ac2c877313102350218cde671ea99e6b433 and f4fd4fdf5621bec8231a2b6dbcf3b8beb0ac8604

**Comment by 4lejandrito** [comment]
Follow up: https://github.com/brianchandotcom/liferay-portal/pull/152528.

**Pull request closed without merging**
