### PR TITLE
LPD-25643 Update title object field name after updating all object fields

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/64edf886c9...fc5ce2d6d0

**Comment by marco-leo** [comment]
@carolmariaabb @brianchandotcom A test is required for those type of changes

**Comment by carolmariaabb** [comment]
@marco-leo the test is already under review: https://github.com/liferay-objects/liferay-portal/pull/3344

**Comment by brianchandotcom** [comment]
@marco-leo ah, yeah for this one she told me physically it was coming right after. I was OK with it.

**Pull request closed without merging**
