### PR TITLE
LPS-100020 remove unused filter

### PR DESCRIPTION
**Pull request by javiergamarra**
Filter is not needed anymore and is causing a security bug. Security already talked with Marco about it.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/524b4c99f0...594f36dee3

**Comment by nhpatt** [comment]
Thanks! I can do the backport to 7.1/7.2

**Comment by brianchandotcom** [comment]
I had to undo the merge...

headless-delivery/headless-delivery-impl/src/main/java/com/liferay/headless/delivery/internal/resource/v1_0/StructuredContentResourceImpl.java


		ThemeDisplay themeDisplay =
			(ThemeDisplay)contextHttpServletRequest.getAttribute(
				WebKeys.THEME_DISPLAY);


That will be null right? Please resend.

**Comment by nhpatt** [comment]
Not exactly, that one in filled by the server/that method, this filter was used just in commerce. But I'll double check.

**Pull request closed without merging**
