### PR TITLE
[7.4-only] LPS-102102, LPS-102114 and LPS-102109 - Remove compat-layer splitter, pager and progress-bars

### PR DESCRIPTION
**Pull request by marcoscv-work**
[7.4-only] - Only master
---
This PR removes:
- Splitter
- Tables
- Progress-bars

From the compatibility layer

--- 

## Previous PR::
https://github.com/liferay-frontend/liferay-portal/pull/580

---

To test the PR:

- Global smoke test along portal, tables, progress-bars, and pager should work fine with some possible visual difference, if we find out a difference, please report ita

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:reopen

**Comment by marcoscv-work** [comment]
Manuel forward since test failures are not related:
Original PR: https://github.com/liferay-frontend/liferay-portal/pull/590

cc @john-co

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/af6e0123bc...397dd12ee9

**Comment by brianchandotcom** [comment]
@marcoscv-work @eduardoallegrini see 4e52db7768f64528f551d263b6ff0e98c2977ff5

**Comment by eduardoallegrini** [comment]
Thanks @brianchandotcom and sorry for the inconvenience! We need this kind of changes but we'll pay more attention from now on, and make sure it doesn't break anything.

**Pull request closed without merging**
