### PR TITLE
LPS-76597 Change test batch sizes

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
@brianchandotcom - Please don't merge this until tomorrow morning, we need to cache these new axes within jenkins.

I'll let you know when it is okay to merge these changes.

Thanks!

**Comment by brianchandotcom** [comment]
@michaelhashimoto ok, please let me know when I can merge them. Thx.

**Comment by michaelhashimoto** [comment]
@brianchandotcom - these changes are ready to be merged, thanks! :+1:

**Comment by brianchandotcom** [comment]
Thx @michaelhashimoto !

**Pull request closed without merging**
