### PR TITLE
LPS-203320 Sitemap integration tests

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPS-203320

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:reopen

**Comment by lfbesada** [comment]
This PR was sent [here](https://github.com/brianchandotcom/liferay-portal/pull/145789) but, as the year changed, the SF found a copyright error because the year 2023. Therefore, I am resending, only the year of the copyright of the new test class have changed.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/64fbcb5cef...65827451f7

**Comment by brianchandotcom** [comment]
@lfbesada see 65827451f77b6b446249905723aafdef00559812

**Pull request closed without merging**
