### PR TITLE
LRDOCS-2547

### PR DESCRIPTION
**Pull request by Ithildir**
Hi!
Please see the pull comment at https://github.com/brianchandotcom/liferay-portal/pull/40009.

Thank you!

### CODE REVIEW

**Comment by pyoo47** [comment]
This PR Test has hung due to a problem in upstream that has been fixed. ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@jhinkey Can you update portal-impl and remove "build-liferay-doclet" and also remove lib/development/liferay-doclet.jar and switch to the standard Oracle CSS classes? It's less work for us in the long run.

Thx Jim!

**Comment by jhinkey** [comment]
Will do

**Pull request closed without merging**
