### PR TITLE
Lps 74694

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/84333076f6...1e6f2f24f2

**Comment by brianchandotcom** [comment]
@shuyangzhou can you send me a pull to backport this? THx.

**Comment by shuyangzhou** [comment]
@tomwang2011 backport please.

**Pull request closed without merging**
