### PR TITLE
Lps 81983

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@shuyangzhou can we just mass change all

com.liferay.petra.string.StringBundler

to

StringBundler

and remove the import to

com.liferay.portal.kernel.util.StringBundler

This is just for portal-web JSPs, I don't see how that would break.

Can you talk to @tomwang2011 to do it?

Thx

**Comment by shuyangzhou** [comment]
@brianchandotcom you mean replace kernel StringBundler with petra StringBundler in portal-web jsps only, right?
It will not work in some cases, we still have a bundle of taglib that uses kernel StringBundler as method signature level, they are not ready for the global switch yet.

**Pull request closed without merging**
