### PR TITLE
LPS-67326 - Calendar button-holder in Asset Publisher add dialog shouldn't be in middle of layout

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by vicnate5** [comment]
@brunobasto Calendar test failed. It might be related to this pull. Not sure yet if this needs a test fix or is a regression.

**Comment by brunobasto** [comment]
@vicnate5 I think it needs a test fix. Initially I thought this was a simple change, but now it makes sense that this needs a test fix because it changes the markup.

**Comment by vicnate5** [comment]
@brunobasto I will fix and resend.

**Comment by brunobasto** [comment]
Thank you!

**Pull request closed without merging**
