### PR TITLE
LRCI-1145 Revert auto SF

### PR DESCRIPTION
**Pull request by kenjiheigel**
@brianchandotcom, these were auto SF-ed locally, but cause issues in our PQL queries. 

@yichenroy, @michaelhashimoto

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:reopen

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:reopen

**Comment by kenjiheigel** [comment]
cc-ing: @ling-alan-huang

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9692795e0e...8aa787fc2f

**Pull request closed without merging**
