### PR TITLE
Lps 72928

### PR DESCRIPTION
**Pull request by shuyangzhou**
@mhan810 @david-truong @jhinkey this pull extra the spring-extender debug logic into its own module, as @brianchandotcom requested. All other osgi related debug logic will all go into modules/apps/foundation/portal-osgi-debug
As a result, the previous configuration file is renamed. But the logic remains the same, so @jhinkey please update the doc of this.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/feb25d22e4...6975dad7d4

**Comment by brianchandotcom** [comment]
@shuyangzhou please see my changes in upstream. Thx.

**Pull request closed without merging**
