### PR TITLE
LPS-76494 Properly timestamp js cache file

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@tinatian please apply the same thing to CSS caches.

**Comment by tinatian** [comment]
@shuyangzhou OK, I will

**Comment by tinatian** [comment]
@shuyangzhou Done, please see https://github.com/shuyangzhou/liferay-portal/pull/5807

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/64d408dbfc...56dda3008b

**Pull request closed without merging**
