### PR TITLE
LPS-105147 Apply Prettier formatting overrides in liferay-portal

### PR DESCRIPTION
**Pull request by wincent**
Via the new version of liferay-npm-scripts:

https://github.com/liferay/liferay-npm-tools/pull/365

### CODE REVIEW

**Comment by wincent** [comment]
@brianchandotcom: I've visually inspected this but (obviously) haven't seen a full CI run pass on this yet.

If you don't want to merge this tonight, I can easily re-roll it and send you a new version based on top of "master" in the morning.

Will figure out some editor shortcuts to share tomorrow.

**Comment by wincent** [comment]
Ironic SF failure is unrelated.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/642425ae40...bdcea0cdc3

**Comment by brianchandotcom** [comment]
@wincent merged, but can you also do this:

```
				const newVariants = variants.filter(variant => {
					if (variant.segmentsExperimentRelId !== variantId)
						return true;

					variantExperienceId = variant.segmentsExperienceId;
					return false;
				});
```

to

```
				const newVariants = variants.filter(
					variant => {
						if (variant.segmentsExperimentRelId !== variantId) {
							return true;
						}

						variantExperienceId = variant.segmentsExperienceId;

						return false;
					});
```

There was also a conflict, so I just ignored that file and pushed up the rest.

**Comment by wincent** [comment]
@brianchandotcom: Let's talk about that one for Christmas 2020... 😂

But seriously, that kind of change is quite a bit harder because it goes right to the heart of the wrapping algorithm which I was telling you about this evening — found the paper BTW; it's ["A prettier printer", by Philip Wadler (1992)](https://homepages.inf.ed.ac.uk/wadler/papers/prettier/prettier.pdf) — and I don't think we can do this without more invasive changes to Prettier's core (the implementation in this PR is non-invasive, because it is simple enough to operate as a post-processing step, outside of Prettier; I think doing this in post-processing would be a bit more error prone).

**Comment by wincent** [comment]
Having said that, at least one aspect of your suggested change would be easy to implement in ESLint, and it wouldn't conflict with Prettier (the requiring a blank line before the `return` statement). Made an issue for that here: https://github.com/liferay/eslint-config-liferay/issues/141

**Comment by wincent** [comment]
Oh, and requiring braces around conditional blocks is also already being tracked: https://github.com/liferay/eslint-config-liferay/issues/140

**Pull request closed without merging**
