### PR TITLE
LPS-89624 Adding a more obvious syntax to synchronize the wrapper with the service class

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test:change-tracking

**Comment by jpince** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f4b7c5cef7...452b74e77b

**Comment by brianchandotcom** [comment]
@danielkocsis @matethurzo see b991418 thx.

**Pull request closed without merging**
