### PR TITLE
LPS-183421

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@tinatian @noornajj type:

git grep -A 2 setExpandoBridgeAttributes **ServiceImpl.java

We almost always (for a long time, to fix another bug) call setExpandoBridgeAttributes BEFORE the update to persistence. This changes that pattern, but just for some. I don't think it's right. Please resend.

**Comment by noornajj** [comment]
Hi @brianchandotcom 

Can you please clarify what changes need to be made to the PR?
Are you saying that we need to find a different approach for the fix (since you're saying calling setExpandoBridgeAttributes before has been intentional to fix a bug)? Or just apply the change to the rest of the ServiceImpl classes?

Thank you
CC/ @tinatian

**Comment by brianchandotcom** [comment]
@noornajj I'm saying that the pattern has always been to call setExpandoBridgeAttributes BEFORE the update (persist). That's been the case for years. I don't remember exactly when that came in or why it came in, but that's the established pattern.

In this fix, you're changing the established pattern, but just for a few of the service impls and not all, so it seems wrong to me.

**Comment by brianchandotcom** [comment]
@noornajj @tinatian I found it

https://issues.liferay.com/browse/LPS-33180 (it even references https://github.com/brianchandotcom/liferay-portal/pull/9623) which made sure setExpandoBridgeAttributes is always called before update

and may be

https://issues.liferay.com/browse/LPP-16993

So I don't want to change that pattern now without breaking more stuff.

**Comment by noornajj** [comment]
Hi @brianchandotcom 

Thank you for looking up the tickets for me.
For [LPS-33180](https://issues.liferay.com/browse/LPS-33180), it doesn't really explain what the issue it's addressing. It just references following the pattern set by [LPS-32470](https://issues.liferay.com/browse/LPS-32470).
But I didn't see this pattern being established in [LPS-32470](https://issues.liferay.com/browse/LPS-32470), the PR shows that missing code to copy over expando was added. So, I'm a little confused there about the purpose of LPS-33180. 

Looking at the method setExpandoBridgeAttributes, it just uses the model's primaryKey to get the associated expando bridge. Logically, whether this is done before or after the model is updated shouldn't matter since the primaryKey will be the same and the model and the expando bridge are stored in separate tables. Unless I'm missing something here?

CC/ @tinatian

**Comment by david-truong** [comment]
ci:reopen

**Comment by david-truong** [comment]
@brianchandotcom we are attempting to keep this PR as small as possible so we can back port this fix for a customer.  we will have a follow up PR where we fix this issue portal wide and clean up all the code at once (move expando to its own module) that we will not back port.

@tinatian @noornajj

**Comment by david-truong** [comment]
@brianchandotcom we can also limit the scope further to only LayoutLocalServiceImpl (the customer issue) and not touch the rest of portal-impl if you prefer

**Comment by brianchandotcom** [comment]
@david-truong @tinatian @noornajj 

The problem is that we have an earlier ticket that explicitly moved setExpandoBridgeAttributes BEFORE update to fix a bug. Now we're moving it AFTER to fix another bug. And this pattern for BEFORE is everywhere.

To change the pattern here to AFTER will have unintended consequences. Some other model listener or TX will break.

I even listed the original tickets that forced this. May be they were not the right ones and there are other LPS tickets that explicitly state why it was done that way (I sure wish we had added an integration test for this back then but we didn't).

So  I need you guys to to 1.) tell me exactly why we moved it to BEFORE in the past, and why that's no longer an issue or 2.) find another way to fix it.

**Comment by brianchandotcom** [comment]
@david-truong @tinatian @noornajj I found it !!!

https://issues.liferay.com/browse/LPS-27515

66dbd2a0940e01935e73a6b979b18c6e14ca5b41

Now if you want me to change this, I will end up breaking LPS-27515.

**Comment by brianchandotcom** [comment]
@david-truong @tinatian @noornajj fyi, this hash 66dbd2a0940e01935e73a6b979b18c6e14ca5b41 only exists in liferay-portal-ee

See https://github.com/brianchandotcom/liferay-portal-ee/commit/66dbd2a0940e01935e73a6b979b18c6e14ca5b41

**Comment by brianchandotcom** [comment]
@david-truong @tinatian @noornajj I found even more. So LPS-27515 was a standardization because of LPS-6584. LPS-6584 was made because of LPS-9102

I merge this pattern in, and LPS-9102 and other things like it will all break.

**Comment by brianchandotcom** [comment]
How did I find this? I checked out ee-6.0.x on liferay-portal-ee. I then typed:

git grep setExpandoBridgeAttributes **ServiceImpl.java

It gave me:

```
portal-impl/src/com/liferay/portal/service/impl/OrganizationLocalServiceImpl.java
portal-impl/src/com/liferay/portal/service/impl/UserLocalServiceImpl.java
portal-impl/src/com/liferay/portlet/blogs/service/impl/BlogsEntryLocalServiceImpl.java
portal-impl/src/com/liferay/portlet/bookmarks/service/impl/BookmarksEntryLocalServiceImpl.java
portal-impl/src/com/liferay/portlet/bookmarks/service/impl/BookmarksFolderLocalServiceImpl.java
portal-impl/src/com/liferay/portlet/calendar/service/impl/CalEventLocalServiceImpl.java
portal-impl/src/com/liferay/portlet/documentlibrary/service/impl/DLFileEntryLocalServiceImpl.java
portal-impl/src/com/liferay/portlet/documentlibrary/service/impl/DLFolderLocalServiceImpl.java
portal-impl/src/com/liferay/portlet/imagegallery/service/impl/IGFolderLocalServiceImpl.java
portal-impl/src/com/liferay/portlet/imagegallery/service/impl/IGImageLocalServiceImpl.java

```
I then typed 'git blame' on every single file.

git blame portal-impl/src/com/liferay/portal/service/impl/OrganizationLocalServiceImpl.java > x.txt

I opened up x.txt and looked for the line setExpandoBridgeAttributes

That led me to 66dbd2a09 which led me to LPS-27515, but that was just the mass enforcement, not the original reason. I kept going...

git blame portal-impl/src/com/liferay/portlet/bookmarks/service/impl/BookmarksEntryLocalServiceImpl.java > x.txt

I opened up x.txt again for this file

led me to c77341afb8b7e48bd3c9dbcc17003ce7a2fb9254  which led me to LPS-6584

I quickly linked LPS-6584 to LPS-27515. That's the detective work I was expecting you to do (but it was hard, so please learn from this and apply it for the future).

**Comment by brianchandotcom** [comment]
@david-truong @tinatian @noornajj 

How did I find this? I checked out ee-6.0.x on liferay-portal-ee. I then typed:

git grep setExpandoBridgeAttributes **ServiceImpl.java

It gave me:

```
portal-impl/src/com/liferay/portal/service/impl/OrganizationLocalServiceImpl.java
portal-impl/src/com/liferay/portal/service/impl/UserLocalServiceImpl.java
portal-impl/src/com/liferay/portlet/blogs/service/impl/BlogsEntryLocalServiceImpl.java
portal-impl/src/com/liferay/portlet/bookmarks/service/impl/BookmarksEntryLocalServiceImpl.java
portal-impl/src/com/liferay/portlet/bookmarks/service/impl/BookmarksFolderLocalServiceImpl.java
portal-impl/src/com/liferay/portlet/calendar/service/impl/CalEventLocalServiceImpl.java
portal-impl/src/com/liferay/portlet/documentlibrary/service/impl/DLFileEntryLocalServiceImpl.java
portal-impl/src/com/liferay/portlet/documentlibrary/service/impl/DLFolderLocalServiceImpl.java
portal-impl/src/com/liferay/portlet/imagegallery/service/impl/IGFolderLocalServiceImpl.java
portal-impl/src/com/liferay/portlet/imagegallery/service/impl/IGImageLocalServiceImpl.java

```
I then typed 'git blame' on every single file.

git blame portal-impl/src/com/liferay/portal/service/impl/OrganizationLocalServiceImpl.java > x.txt

I opened up x.txt and looked for the line setExpandoBridgeAttributes

That led me to 66dbd2a09 which led me to LPS-27515, but that was just the mass enforcement, not the original reason. I kept going...

git blame portal-impl/src/com/liferay/portlet/bookmarks/service/impl/BookmarksEntryLocalServiceImpl.java > x.txt

I opened up x.txt again for this file

led me to c77341afb8b7e48bd3c9dbcc17003ce7a2fb9254  which led me to LPS-6584

I quickly linked LPS-6584 to LPS-27515. That's the detective work I was expecting you to do (but it was hard, so please learn from this and apply it for the future).

**Comment by david-truong** [comment]
@brianchandotcom thanks for the advice.  I will take a look at the different options and resend this.

**Pull request closed without merging**
