### PR TITLE
LPD-19838: Allow admins to set a picklist as a source for filtering data

### PR DESCRIPTION
**Pull request by chestofwonders**
Fix for: https://github.com/brianchandotcom/liferay-portal/pull/149986#issuecomment-2096497223

Reason: We don't need a description for the FF since it's a development FF, not a DXP setting

--------------------------------------------------------------------------------------------------------------

Task: https://liferay.atlassian.net/browse/LPD-19838

**Allow admins to set a picklist as a source for filtering data**

Feature Flag **LPD-10754** must be enabled for this feature

**Goal**

Improve Filters UI to differentiate between picklists and API sources for selection filters (AKA dynamic filters).
Current story's scope involves only picklists sources, but the code takes in consideration the next part of the epic:
https://liferay.atlassian.net/browse/LPD-16054
to make easier adding the new source

**UI Changes**

Note: Modal has been made bigger for the new inputs that will be added for API source

image

**Test Automation**

PR includes Filters POM and a helper for picklists creation and modification.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/30a16ed44b...347916b89a

**Comment by brianchandotcom** [comment]
@chestofwonders see bbf6e6c1a977f05550df135849e3b3683b2ac5ba

**Comment by brianchandotcom** [comment]
@chestofwonders this didn't compile so I had to revert it

```
     [echo] Execution failed for task ':apps:frontend-data-set:frontend-data-set-views-web:packageRunBuild'.
     [echo] > Process 'command '/home/me/dev/projects/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [echo] 
     [echo] * Try:
     [echo] > Run with --info or --debug option to get more log output.
     [echo] > Run with --scan to get full insights.
     [echo] > Get more help at https://help.gradle.org.
     [echo] 
     [echo] * Exception is:
     [echo] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:frontend-data-set:frontend-data-set-views-web:packageRunBuild'.
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:148)
     [echo] 	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:146)
     [echo] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:134)
     [echo] 	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
     [echo] 	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
     [echo] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)

```

**Comment by chestofwonders** [comment]
Continues in https://github.com/brianchandotcom/liferay-portal/pull/150090

**Pull request closed without merging**
