### PR TITLE
LPS-163590 - Update bundler and add package.json dependencies back in

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Manual Forward from: https://github.com/liferay-frontend/liferay-portal/pull/2753

@brianchandotcom, follow the PR conversation to see discussion on build time performance from this PR.

tldr;

> After a git clean -fdx, master was a little more than 1 minute faster
> Without Gradle cache only, master was 24s faster
> With all caches, master was 5s slower

Build times slightly increase, although these times may have been impacted by network speeds and thus making the time difference negligible.

I believe there are additional FE improvements we can make to ~increase~ decrease the build times as well.

Additionally, by adding these dependencies back in, our typescript generation should become more accurate.

Let me know if you have any questions/concerns

https://issues.liferay.com/browse/LPS-163590

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/010ecdabfa...b168c93a61

**Comment by brianchandotcom** [comment]
Thx @bryceosterhaus 

@natocesarrego  fyi! 

@ling-alan-huang we can probably remove JSONPackageJSONRedundantDependenciesCheck if the code here works and the paradigm has changed.

**Comment by natocesarrego** [comment]
Thanks for lettting me know, @brianchandotcom! :slightly_smiling_face: 

The build times shared by @bryceosterhaus were extracted on my machine by the script created by you, the `ant_all_benchmark.sh`. @bryceosterhaus shared this pull with me a few days ago. :smile: 

Thanks everybody!

**Comment by bryceosterhaus** [comment]
I additionally created this issue to investigate some other build time impacts from our frontend toolset, https://github.com/liferay/liferay-frontend-projects/issues/1026

**Pull request closed without merging**
