### PR TITLE
LPS-98032 Update liferay-npm-scripts to v12.0.0

### PR DESCRIPTION
**Pull request by wincent**
This version liferay-npm-scripts integrates a few things that make the PR pretty large:

- Formatting of JS in JSP.
- Additional lint rules to group and sort imports, ban a number of anti-patterns (dynamic requires, absolute imports etc), and enforce use of arrow functions and object spread.

[Ran the tests here](https://github.com/wincent/liferay-portal/pull/79) and they look pretty good.

> [ci:test:relevant - 95 out of 111 jobs passed in 2 hours 40 minutes 8 seconds 42 ms](https://github.com/wincent/liferay-portal/pull/79#issuecomment-543230151)

As this is quite large, please let me know whether you want to merge it or instead have me push to the upstream early in Central European time: we don't want to cause any unnecessary merge conflicts or rebase headaches.

### CODE REVIEW

**Comment by wincent** [comment]
cc @jbalsas

**Comment by wincent** [comment]
Deep-link to test results on other pull:

> [ci:test:relevant - 95 out of 111 jobs passed in 2 hours 40 minutes 8 seconds 42 ms](https://github.com/wincent/liferay-portal/pull/79#issuecomment-543230151)

**Comment by john-co** [comment]
ci:close

**Comment by john-co** [comment]
Closing since same regressions were verified described in https://github.com/wincent/liferay-portal-ee/pull/4#issuecomment-543270187

cc/ @wincent

**Pull request closed without merging**
