### PR TITLE
LPS-102511 Fix DataHandlers that set primary keys and not mvcc when c…

### PR DESCRIPTION
**Pull request by Preston-Crary**
…opying over the other columns.

@brianchandotcom you were right, there's quite a few of these.

CC @shuyangzhou @jkappler

### CODE REVIEW

**Comment by Preston-Crary** [comment]
@jkappler if you have any models that have mismatched primary key to model names I missed it in my search, I used `([A-Za-z]+)\.\s*set\1Id\(` to find these ones.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4b3374d3ce...15b4b80cf9

**Comment by brianchandotcom** [comment]
@hhuijser can we SF enforce this? Talk to @Preston-Crary related to MVCC change.

**Comment by jkappler** [comment]
thanks @Preston-Crary!

**Pull request closed without merging**
