### PR TITLE
LPS-55220

### PR DESCRIPTION
**Pull request by shinnlok**
@Ithildir

Can you verify that I didn't break anything of yours?

Thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/78fdb520fe...d2c8381a55

**Comment by brianchandotcom** [comment]
@shinnlok I merged this in, but can you explain the rhyme and reason behind when to use default->master etc via an email / wiki?

Thx.

**Comment by Ithildir** [comment]
Hi @shinnlok!
In `modules\util\javadoc-formatter` with `provided->master` for the 3 Gradle jars, I tried to do `ant clean compile`, but these 3 jars aren't downloaded and the build breaks :cry: 

Are you sure this is the correct approach? Those jars are dependencies for compilation, and so they should be downloaded by Ivy. But they should also appear with `<scope>provided</scope>` in the published pom.xml, because we already know they'll be available at runtime.

Please let me know, thanks!!

**Comment by shinnlok** [comment]
Can you run "ant setup-sdk" before trying to compile?

**Comment by Ithildir** [comment]
Hi @shinnlok!
You're right, looking at the commits you made for [LPS-55220](https://issues.liferay.com/browse/LPS-55220), I realized you changed the SDK. Now it seems to work! :blush:

**Pull request closed without merging**
