### PR TITLE
LRQA-60432 | master

### PR DESCRIPTION
**Pull request by vicnate5**
@manoelcyreno

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:reopen

**Comment by vicnate5** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6cb99ab9da...3725df4a59

**Pull request closed without merging**
