### PR TITLE
Lps 74964

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest is this related?

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by pyoo47** [comment]
ci:stop https://loop.liferay.com/home/-/loop/feed/7636012

**Comment by pyoo47** [comment]
ci:retest https://loop.liferay.com/home/-/loop/feed/7636012

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8f425a0c84...a5cc95fc53

**Pull request closed without merging**
