### PR TITLE
LRQA-18824 SF

### PR DESCRIPTION
**Pull request by pyoo47**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:stop - I just found an issue with a revision I made last night. I'm going to add one more commit to reverse it.

**Comment by pyoo47** [comment]
Please publish a new jenkins results parser jar after this is merged.

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
That last change was just a rewording of my commit comment.

**Comment by brianchandotcom** [comment]
Publishing a new version, will be up in 2 min

**Pull request closed without merging**
