### PR TITLE
LPS-90534 Improve custom field for text field input type

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @thektan @drewbrokke @stsquared99 @alee8888 @ChrisKian

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5e42a257d6...5232f91705

**Comment by brianchandotcom** [comment]
@pei-jung see upstream for my changes.

Are we working on fixing

```
	@ignore = "true"
	@priority = "5"
	test EditCustomFieldUserBoolean {
```
? Thx.

**Comment by pei-jung** [comment]
@brianchandotcom Unfortunately no. We don't have a test engineer allocated for our team, and we're not familiar with the poshi tests. We've talked to @jhendley about this, and he agreed to have us disable the failing tests for now until we get a QA or the bandwidth to learn the poshi syntax.

**Comment by pei-jung** [comment]
FYI, we did manual testing to make sure we cover the failing test before deactivating it.

**Pull request closed without merging**
