### PR TITLE
LPS-74171

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@Ithildir I'll need to fork our plugins SDK as well so that 7.0.x is 1.* and master is 2.* since Tomcat versions are different....

But what about changes here:

modules/sdk/gradle-plugins-test-integration/src/gradleTest/executable/build.gradle

That is not forked in 7.0.x.. can you resend?

Thx.

@jhendley fyi

**Comment by Ithildir** [comment]
ci:reopen

**Comment by Ithildir** [comment]
@brianchandotcom,
You can safely ignore `modules/sdk/gradle-plugins-test-integration/src/gradleTest/executable/build.gradle`, since it's just code for a Gradle test.

**Comment by brianchandotcom** [comment]
Merged. Thank you.

**Pull request closed without merging**
