### PR TITLE
LRQA-22572 Update publishToLive macro

### PR DESCRIPTION
**Pull request by matethurzo**
this is two LPS in one pull, because they depend on each other

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@brianchiu more?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c2ee8cb4d3...a55476760f

**Comment by brianchiu** [comment]
@brianchandotcom 
This one is safe to merge.

**Comment by brianwulbern** [comment]
@brianchiu @brianchandotcom 
Fixing that Poshi test issue here: https://issues.liferay.com/browse/LRQA-22763

**Pull request closed without merging**
