### PR TITLE
LPS-98855 Search bar

### PR DESCRIPTION
**Pull request by brunofarache**

### CODE REVIEW

**Comment by brunofarache** [comment]
ci:test:relevante

**Comment by brunofarache** [comment]
ci:test:relevant

**Comment by brunofarache** [comment]
@brianchandotcom failure not related to my PR. It's been fixed already by:

https://github.com/liferay/liferay-portal/commit/a13676a97260a4b0a58f6a2dcbf1680f9e1946e8#diff-18b4f543ba4021e70fab9b8bafe5c739

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/12ffe04c3f...beda2cb4bb

**Pull request closed without merging**
