### PR TITLE
Lrac 12449

### PR DESCRIPTION
**Pull request by riccardo-ferrari**

### CODE REVIEW

**Comment by riccardo-ferrari** [comment]
ci:test:reopen

**Comment by riccardo-ferrari** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a85d649aa6...e59531e2e7

**Comment by brianchandotcom** [comment]
@riccardo-ferrari please send a follow up PR based on my comments in 3066caba

See also 5c154d51 5c16f7a3 f35f98b8 cff8aeb2 and e59531e2 (I may have broken the test)

Thx

**Pull request closed without merging**
