### PR TITLE
LPS-77425

### PR DESCRIPTION
**Pull request by dejuknow**
Avoiding major version bump for sync-engine. Is this okay?

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8d4214a28d...60a01b7e01

**Comment by brianchandotcom** [comment]
@dejuknow See db2be6c

We may be able to just remove modules/apps/sync/** from master, and have you just work off of 7.0.x?

We don't really need it in master.

**Comment by dejuknow** [comment]
Do you mean modules/apps/sync/** or just modules/apps/sync/sync-engine?

Working off 7.0.x for sync-engine is fine, but Sync Connector will still be released for 7.1, so sync-api, sync-service, etc should stay in master?

**Comment by brianchandotcom** [comment]
Just modules/apps/sync/sync-engine

--
Brian Chan
Chief Software Architect
Liferay, Inc.
Enterprise. Open Source. For Life.
(626) 806-1190

**Pull request closed without merging**
