### PR TITLE
LPS-53432 Integration Test - Adapt test to support translations

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:restest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cf88e0ff42...24274a44e0

**Comment by brianchandotcom** [comment]
Please see my tiny changes in upstream. Thx.

**Comment by brianchandotcom** [comment]
@lipusz please double check our work. Thx.

**Pull request closed without merging**
