### PR TITLE
LPS-76585 SF

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchandotcom** [comment]
@carloslancha @jbalsas I like the usage of DropdownsItemList, thanks for copying that pattern.

But can you rename the vars as well?

DropdownItemList _actionItems

Should be

getActionDropdownItems

That follows our usage of NavigationItemList

Thx

**Comment by carloslancha** [comment]
Resent https://github.com/brianchandotcom/liferay-portal/pull/55607

**Pull request closed without merging**
