### PR TITLE
LPS-86914 Fix filter.

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by vicnate5** [comment]
@brianchandotcom Can you backport to 7.1.x?

**Comment by jpince** [comment]
@Preston-Crary see NPEs in UAD tests?

cc/ @drewbrokke

**Comment by Preston-Crary** [comment]
@jpince looking into it.

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/64866

**Comment by jpince** [comment]
@Preston-Crary can you please backport this? This looks like the only commit from this ticket that BChan did NOT auto-backport.

**Comment by jpince** [comment]
@Preston-Crary BChan backported it https://github.com/liferay/liferay-portal-ee/commit/bb60740b936de1f4edc99c701bacbe45c0e3d3f0

cc/ @CsabaTurcsan @gergelyszaz

**Pull request closed without merging**
