### PR TITLE
LRQA-58215 - Fix other flakys

### PR DESCRIPTION
**Pull request by rodrigocunhaa**

### CODE REVIEW

**Comment by rodrigocunhaa** [comment]
Forwarded from https://github.com/rodrigocunhaa/liferay-portal/pull/55. The same reason as https://github.com/brianchandotcom/liferay-portal/pull/88624.

**Comment by rodrigocunhaa** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c7af1f2de1...ae2a097523

**Pull request closed without merging**
