### PR TITLE
LPS-76024 Implement UAD for AnnouncementsFlag

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke, @noahsherrillwork, @willnewbury, @jorgeferrer

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pei-jung can I merge this right away? Did this pass anywhere?

**Comment by pei-jung** [comment]
ci:test

**Comment by pei-jung** [comment]
@brianchandotcom this has not been tested. Please let the test finish. Thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/efe7c2a4c9...37419cf8f5

**Comment by brianchandotcom** [comment]
Thx @pei-jung please see my changes in upstream. Thx.

**Pull request closed without merging**
