### PR TITLE
LPS-53774 Run unit tests before integration tests

### PR DESCRIPTION
**Pull request by shuyangzhou**
This is totally harmless, pull it ahead to reduce the noise.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
What about for plugins? Do we need to change the SDK?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/076c395df9...e7747251d0

**Comment by shuyangzhou** [comment]
We don't have to change the plugins one, but to be consistent, I think we should. Will send it.

**Comment by michaelhashimoto** [comment]
ci:retest

**Pull request closed without merging**
