### PR TITLE
LPS-88137 Add portlet namespace to componentIDs

### PR DESCRIPTION
**Pull request by p2kmgcl**
/cc @brianchiu
/cc @jkappler
/cc @ealonso

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test

**Comment by brianchiu** [comment]
Running a ci test because I want to confirm whether or not this fixes the fragments export import tests

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
