### PR TITLE
LPS-74368

### PR DESCRIPTION
**Pull request by Ithildir**
Hi,
Please let this pull finish.

Thank you!

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:reopen

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
@pyoo47, what is happening here?

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
@Ithildir Sorry Andrea, we had an unexpected side effect of deleting the ee-7.0.x acceptance upstream job that caused some of our unit tests to fail. I've temporarily restored the job so the test will no longer fail.

**Comment by Ithildir** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
