### PR TITLE
LPS-52679 Add ExtensionManager to SoapExtender

### PR DESCRIPTION
**Pull request by csierra**
@brianchandotcom changes in extensions are only reloaded when the CXF itself servlet is reloaded, since for CXF it makes not sense to "hot swap" extensions. So, basically, if extensions are added or removed while the tracker is active it does not respond by design. Only when the administrator reloads the component the changes in extensions will take place. Alas, any state that the servlet could have would be lost, that is why we wanted this to be an admin conscious decision to make.

### CODE REVIEW

**Comment by csierra** [comment]
:no_mouth: ?

**Comment by brianchandotcom** [comment]
Hey @csierra 

If there is a weird error, post a messge with the coimment "ci:retest" in it, and it will trigger another test. Sometimes, we have random test failures.

But , if you look at the current message, it still has a SF error. I'll go ahead and fix it for now.

Thx

**Comment by csierra** [comment]
Hey @brianchandotcom, 

that SourceFormat error... what does it mean? I have the same error locally and I don't know what is going on. I must be doing something wrong but I can't tell what...

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3f512db5e4...5f63321425

**Comment by brianchandotcom** [comment]
Hey @csierra 

It got thrown off by the {}

See 5f63321425b6339e58f86dc72487ab5d078a9c63

Was technically a bug in the SF. But this change makes it happy. You can always binary / search it and just go to portal-soap-extender and run "ant format-source" (very fast, like 1 second)

Thank you also for adding the removeExtension, because at least now I know it was on purpose.

Thx

**Pull request closed without merging**
