### PR TITLE
LPS-105759 buildRest

### PR DESCRIPTION
**Pull request by brunofarache**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bcfc8891e4...d40335f6b6

**Comment by brianchandotcom** [comment]
@brunofarache I made 4 commits to change things. Please see them in my origin.

**Comment by brunofarache** [comment]
@alexcandidos can you please check this poshi test results are valid?

**Comment by alexcandidos** [comment]
Hey @brunofarache , I think the poshi test results are valid :/

**Pull request closed without merging**
