### PR TITLE
LPS-97974 Fix test and baseline

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
@brianchandotcom @jpince Can you merge this one? It fixes a couple of issues with the test in CI. The other test failing (segments-staging related) must be failing in upstream, but probably they haven't been running due to these other issues. I'll research and fix the pending test issues in a separate PR.

Thanks

**Comment by jpince** [comment]
@epgarcia for int test failures, see [LPS-98333](https://issues.liferay.com/browse/LPS-98333), caused by [LPS-97705](https://issues.liferay.com/browse/LPS-97705). Probably affects all `*DataHandlerTest` int tests. @danielkocsis said he would look into it, but I'm not sure how much progress he made today.

**Comment by epgarcia** [comment]
@jpince thanks for the info. As for the issues fixed in this PR, they opened an LPS later today (See LPS-98410) but I had already sent the PR. I'll resolve the issue when this PR is merged. FYI the test compilation error was introduced by LPS-97974, so that's why I used that ID.

**Comment by jpince** [comment]
@epgarcia that's fine, thanks for following up on LPS-98410 also :+1:

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e40667f613...300de57b9e

**Pull request closed without merging**
