### PR TITLE
LPS-84225 baseline

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@shuyangzhou Not sure if this is random LPKG base failure. Please take a look. Thx!

**Comment by shuyangzhou** [comment]
@mtambara please take a look.

**Comment by mtambara** [comment]
@brianchandotcom @shuyangzhou LPKG base failure is unrelated

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e2dbbc7c46...a75b5d774a

**Comment by brianchandotcom** [comment]
@ealonso should 

```
<field name="data" type="String" />
```

be bigger?

@ealonso @jkappler See upstream for my changes. Thx.

**Pull request closed without merging**
