### PR TITLE
LPS-67303

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by jpince** [comment]
@shuyangzhou can you provide insight on what this pull needs? It had the same failures when it was sent earlier https://github.com/brianchandotcom/liferay-portal/pull/43883

Error in the lpkg tests:
`[echo] /opt/dev/projects/github/liferay-portal/modules/build-app.xml:362: Unable to load file: java.io.FileNotFoundException: /opt/dev/projects/github/liferay-portal/modules (Is a directory)
which refers to build-app.xml line 362:`

Here are lines 362-368 in build-app.xml:
```
        <loadproperties srcFile="${app.bnd.file}">
            <filterchain>
                <linecontains>
                    <contains value="Liferay-Releng-App-Title" />
                </linecontains>
            </filterchain>
        </loadproperties>
```

**Comment by shuyangzhou** [comment]
It is a lpkg packaging problem. @CAustin582 can you take a look?

**Comment by brianchandotcom** [comment]
ci:retest strange... don't see how his code could have caused this.

**Comment by jpince** [comment]
@migue we think the issue is in https://github.com/brianchandotcom/liferay-portal/pull/44351/commits/add4de484dbf06e845e8df90565f8c777d677eb8, where modules/apps/content-targeting is added as an empty directory.

The test runs ant [build-app-lpkg-all](https://github.com/liferay/liferay-portal/blob/master/modules/build-app.xml#L40) from the modules folder. From the [Jenkins Console Log](https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/37425/AXIS_VARIABLE=0,label_exp=!master/consoleFull), the Liferay CE Collaboration lpkg is successfully built
```
build-app-lpkg:
      [zip] Building zip: /opt/dev/projects/github/liferay-portal/bundles/osgi/marketplace/Liferay CE Collaboration.lpkg
```
It then proceeds to build the next app, which for your branch, is content-targeting:
```
check-current-branch:
     [echo] Current branch: master-temp-20161027223157069

checkout-public-modules-releng:

init-build-app:
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:256: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1115: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1342: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/modules/build-app.xml:48: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/modules/build-app.xml:50: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/modules/build-app.xml:362: Unable to load file: java.io.FileNotFoundException: /opt/dev/projects/github/liferay-portal/modules (Is a directory)
      [get] Getting: http://test-1-5/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/37425//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20161028055816021.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20161028055816021.txt
```
Because there is no app.bnd in this directory (it's empty) and the build script is not written to handle a situation like this, the build fails.

None of the other test batches try to build this app, which is why only lpkg tests are failing.

See [this gist](https://gist.github.com/jpince/59ad35d610db7b199e5832ccceae1fca) of how I was able to reproduce a similar error locally.

Thanks @caustin582 @shuyangzhou

**Comment by jpince** [comment]
ci:close

**Pull request closed without merging**
