### PR TITLE
LPS-101688 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-101688

### CODE REVIEW

**Comment by kyle-miho** [comment]
Reopening, SF is formatting this incorrectly.
```
		PageEditor.addFragment(
			collectionName = "Collection Name",
			fragmentName = "Text Fragment Example");
```
is the expected format and is performed elsewhere, but this new edition expects
```
		PageEditor.addFragment(
			collectionName = "Collection Name", fragmentName = "Text Fragment Example");
```
for some reason

**Comment by kenjiheigel** [comment]
@ling-alan-huang, any ideas about this?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fc56e3e220...5f436f32ad

**Comment by kenjiheigel** [comment]
SF fixed in: 
https://github.com/brianchandotcom/liferay-portal/pull/78590

**Pull request closed without merging**
