### PR TITLE
LPS-74263 SF

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e3c66a9618...6d6cf0c23c

**Comment by brianchandotcom** [comment]
@ealonso @samanzanedo how come it's not automated from the portal-model-hints.xml?

**Comment by ealonso** [comment]
Hey @brianchandotcom, 

This is because the virtual host is located in layoutSet and "site_url.jsp" is part of edit group form, so we set the model context to Group, as you can see in the line 34. It's not possible to get the restriction directly from portal-model-hints.xml for layoutSet if we set the context to Group.

**Pull request closed without merging**
