### PR TITLE
LPS-63057 Semantic version

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchiu** [comment]
@ealonso @brianchandotcom 

Upgrade failures are caused by message boards portlet becoming undeployed after an upgrade.

before1

The other failures are caused by message boards missing in the product menu.

before0

**Comment by brianchandotcom** [comment]
I'm retesting it here and rebased it locally to test at https://github.com/brianchandotcom/liferay-portal/pull/37731

**Comment by brianchandotcom** [comment]
@ealonso please resend? Looks like they may be real bugs.

**Pull request closed without merging**
