### PR TITLE
LRACs 15084 15086 15087

### PR DESCRIPTION
**Pull request by interaminense**
- LRAC-15084, LRAC-15086, LRAC-15087 create langs for AB and MAB tests
- LRAC-15084, LRAC-15086, LRAC-15087 update langs on SegmentsExperimentProductNavigationControlMenuEntry.java
- LRAC-15084, LRAC-15086, LRAC-15087 update modal to implement the Dynamic test option
- LRAC-15084, LRAC-15086, LRAC-15087 update request call to get the type of the test and display it in the sidepanel details
- LRAC-15084, LRAC-15086, LRAC-15087 update unit tests mock
- LRAC-15178 Create FF to display new feature
- LRAC-15176 Fix unit tests
- LRAC-15176 buildLang

### CODE REVIEW

**Comment by interaminense** [comment]
ci:reopen

**Comment by interaminense** [comment]
Hi @brianchandotcom this PR is the follow-up with changes your comment on this last PR https://github.com/brianchandotcom/liferay-portal/pull/144999?notification_referrer_id=NT_kwDOAMHIybM4Njg0MTIyMTczOjEyNjk5ODQ5#issuecomment-1845628518

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c044a33e02...210f287140

**Comment by brianchandotcom** [comment]
@interaminense see 27fef8591bc1d318da62c8398a9f9a97baf8c01d

**Pull request closed without merging**
