### PR TITLE
LPS-102120 Always shows filtered fields

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brunobasto** [comment]
Although in the same modules, failures seem unrelated to my changes.

**Comment by jeyvison** [comment]
Fix sent in https://github.com/brianchandotcom/liferay-portal/pull/78784

**Comment by brianchandotcom** [comment]
@jeyvison waiting for your fix :)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d3aad316b3...e31041d99e

**Pull request closed without merging**
