### PR TITLE
[NOT-FOR-GA5] LPS-117064, LPS-117066, LPS-117069, LPS-118298 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-117064
https://issues.liferay.com/browse/LPS-117066
https://issues.liferay.com/browse/LPS-117069
https://issues.liferay.com/browse/LPS-118298

This is only for master.

@sandrodw3
@pavel-savinov

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
I'm sending the PR directly with a [NOT-FOR-GA5] label reference to https://github.com/brianchandotcom/liferay-portal/pull/92639
All tasks passed in this PR. See https://github.com/liferay-echo/liferay-portal/pull/1868
✔️ ci:test:stable - 21 out of 21 jobs passed
✔️ ci:test:relevant - 88 out of 88 jobs passed in 1 hour 55 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f22523a329...16686cc31c

**Comment by brianchandotcom** [comment]
@pavel-savinov  @sandrodw3 please send a follow up pull. I merged this, but:

1.) CollectionLayoutStructureItem extends StyledLayoutStructureItem

Should be *StyledLayoutStructureItem extends StyledLayoutStructureItem

2.) See modules/apps/layout/layout-type-controller/layout-type-controller-portlet/src/main/java/com/liferay/layout/type/controller/portlet/internal/display/context/PortletLayoutDisplayContext.java

Not sorted

```
		if (styledLayoutStructureItem.getOpacity() != -1L) {
			styleSB.append("opacity: ");
			styleSB.append(styledLayoutStructureItem.getOpacity() / 100.0);
			styleSB.append(StringPool.SEMICOLON);
		}

		if (Validator.isNotNull(styledLayoutStructureItem.getTextColor())) {
			styleSB.append("color: ");
			styleSB.append(styledLayoutStructureItem.getTextColor());
			styleSB.append(StringPool.SEMICOLON);
		}

		if (Validator.isNotNull(styledLayoutStructureItem.getOverflow())) {
			styleSB.append("overflow: ");
```

It's not sorting by actual HTML or by Java method.. so it's weird.

3.) Please review my other changes in my origin.

Nicely done @Tim-Cao

**Pull request closed without merging**
