### PR TITLE
LPS-68449 Rename

### PR DESCRIPTION
**Pull request by marcellustavares**
cc @ChrisKian

### CODE REVIEW

**Comment by jpince** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@marcellustavares @ChrisKian see b61e8ab02e31205422e0110e34843ced7046a56f

**Pull request closed without merging**
