### PR TITLE
Revert "LPS-77168 Add columns to DDMFormInstanceVersion and DDMStructureVersion to be able to use staging"

### PR DESCRIPTION
**Pull request by rafaprax**
Hey @brianchandotcom,

we are working on to fix the staging issues related to the DDM. For now to avoid CI errors in all prs, we are reverting the pr that cause the issue.

Thx

\\cc @leoadb @inacionery @matethurzo

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/612e52a796...81debd2b88

**Comment by brianchandotcom** [comment]
@rafaprax next time, you can just send me a pull to disable the test, but this works too.

Thx!

**Comment by rafaprax** [comment]
Ok @brianchandotcom 
Thx

**Pull request closed without merging**
