### PR TITLE
LPS-100131 Rename TEMP_TABLE to TEMP_TABLE_ASSET_ENTRY

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ruben-pulido, @ealonso

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ef529ba466...2652f0481a

**Comment by brianchandotcom** [comment]
@vendeltoreki @jkappler please review my changes in 2652f0481a73d3936a8e6be25cb36eef3d77c974

Is there a test for this? If not, please add one.

**Comment by vendeltoreki** [comment]
@brianchandotcom @jkappler the changes look ok.

I will add tests for related asset queries ([LPS comment](https://issues.liferay.com/browse/LPS-100131?focusedCommentId=1952244&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1952244))

**Pull request closed without merging**
