### PR TITLE
LRDOCS-3144 Asset Publisher Javadoc

### PR DESCRIPTION
**Pull request by codyhoag**
/cc @pavel-savinov

### CODE REVIEW

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@codyhoag please backport the parts that can be backported. THx.

**Comment by codyhoag** [comment]
yeah, no problem. I'll send backports to Zoltan.

**Pull request closed without merging**
