### PR TITLE
Lps 63811

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@shuyangzhou can you resend? Rebase error, also, there are 29 consistent test failures I found in 2 pulls:

https://github.com/brianchandotcom/liferay-portal/pull/37155
https://github.com/brianchandotcom/liferay-portal/pull/37160

Can you take a look if you get a chance? I"m not sure if it's related to the portal-impl jar thing I did earlier today :(

Thx @shuyangzhou

**Comment by brianchandotcom** [comment]
@shuyangzhou I'm testing a rollback of a few commits I think are suspicous looking https://github.com/brianchandotcom/liferay-portal/pull/37162

**Comment by shuyangzhou** [comment]
Ok, I will check them

**Comment by shuyangzhou** [comment]
@brianchandotcom I think you are right on those commits, it should be them.

**Comment by shuyangzhou** [comment]
Yeah, it finished, looks good.

**Pull request closed without merging**
