### PR TITLE
LPS-62988 Fix wrong package reference

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/27e0baf716...a41de077ec

**Comment by brianchandotcom** [comment]
@hhuijser can you add SF to prevent this? Thx.

**Comment by hhuijser** [comment]
@rotty3000 @brianchandotcom 
How are we supposed to detect this?
Are we not supposed to use com.liferay.registry.ServiceReference in modules?

**Comment by rotty3000** [comment]
Correct!

The only class in the registry-api module that is safe for use in any
module is StringPlus.

I've been thinking of duplicating that class in com.liferay.osgi.util such
that modules that want to use it, can. It's likely that the modules using
StringPlus are also using the com.liferay.osgi.util module so it's not a
stretch.

**Comment by rotty3000** [comment]
To clarify, it should be ok to use registry-api in portal-bootstrap,
registry-impl and registry-test, but nowhere else (except for the
StringPlus class I mentioned).

On Thu, Feb 11, 2016 at 11:01 PM, Raymond Auge <raymond.auge@liferay.com>
wrote:

> Correct!
>
> The only class in the registry-api module that is safe for use in any
> module is StringPlus.
>
> I've been thinking of duplicating that class in com.liferay.osgi.util such
> that modules that want to use it, can. It's likely that the modules using
> StringPlus are also using the com.liferay.osgi.util module so it's not a
> stretch.
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by hhuijser** [comment]
Got it, thanks Ray!

**Comment by hhuijser** [comment]
@rotty3000 

What about test classes in modules/apps?
Right now we're ignoring test classes when we're checking for the use of com.liferay.registry.Registry(Util) in modules files (I also see quite a few uses of com.liferay.registry.ServiceReference in test files).

**Comment by rotty3000** [comment]
Those we could ignore too...  but it's kind of weak to use registry-api
there since there's lots of other better ways to do it. However, it's not
so critical. I'm more concerned with runtime issues. But to be honest it
would be better if it was not used except in the previous exceptions. I'll
let you decide if tests are excused or not (fixing them all could be a lot
of work).

**Comment by hhuijser** [comment]
I'll make it configurable... if there is someone who is really bored and is looking for stuff to do he/she can work on fixing those...

**Pull request closed without merging**
