### PR TITLE
LPS-171144 Implement backend of the new configuration fields

### PR DESCRIPTION
**Pull request by liulukiwi**
This is only for master.

https://issues.liferay.com/browse/LPS-171144

@lfbesada

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:reopen

**Comment by liulukiwi** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/10664

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1bd59b1770...7636a976e3

**Comment by brianchandotcom** [comment]
@lfbesada see 945cf1f7d9a2f04f11552578180c274f2b55ad23 and 7636a976e39cb7d755fb97d7a300cb170a560cff

**Pull request closed without merging**
