### PR TITLE
LPS-61474

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@mhan810 

For CASConstants,

```
	public static final String AUTH_ENABLED = "enabled";

	public static final String IMPORT_FROM_LDAP = "importFromLDAP";

	public static final String LOGIN_URL = "loginURL";

	public static final String LOGOUT_ON_SESSION_EXPIRATION =
		"logoutOnSessionExpiration";

	public static final String LOGOUT_URL = "logoutURL";

	public static final String NO_SUCH_USER_REDIRECT_URL =
		"noSuchUserRedirectURL";

	public static final String SERVER_NAME = "serverName";

	public static final String SERVER_URL = "serverURL";

	public static final String SERVICE_NAME =
		"com.liferay.portal.security.sso.cas";

	public static final String SERVICE_URL = "serviceURL";
```

There's no way to tell that "SERVICE_NAME" is not the same type as "SERVICE_URL".

For all these security constants, we should prefix all of the keys that are keys, with KEY_ or something like that.

Otherwise, as we add more, it gets messy.

Can you send me one big pull to prefix all the keys?

Thx Mike.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bc483401a4...d584262190

**Comment by brianchandotcom** [comment]
@mhan810 also, how come the CAS bnd contains dynamic imports but the NTML one doesn't?

**Comment by brianchandotcom** [comment]
@mhan810 also, KEY_* might be too generic. Is it a configuration key, a property key? etc.

**Comment by mhan810** [comment]
I'll move the keys to a diff constant class e.g. ConfigConstants or
something.

Sent from my mobile device.

**Pull request closed without merging**
