### PR TITLE
Lps 64932

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a1fcb12fe7...950f8208c1

**Comment by JorgeFerrer** [comment]
Hey @dantewang @shuyangzhou,

I think this should have been sent for review to the Collab team since they own this component and thus are responsible for their maintenance and bugs.

@sergiogonzalez, it might be a good idea for you guys to review it now.
@brianchandotcom what happened to the plan to enforce this type of reviews by the owners?

**Comment by shuyangzhou** [comment]
@JorgeFerrer this is just a SF level change, do we really want to add the review round trip even for this kind of basic changes?

**Comment by JorgeFerrer** [comment]
Hey Shuyang,

I think that would be best. 

On one side because doing source formatting has created bugs more often than we would like to.

But probably even more important is respecting ownership. A developer/team can only feel responsible for a piece of code if they know they have full control over it. If anyone else is making changes without him/her/them knowing the sense of control and thus ownership quickly gets diluted.
Makes sense?

**Pull request closed without merging**
