### PR TITLE
Lps 69661

### PR DESCRIPTION
**Pull request by shuyangzhou**
@hhuijser can you SF this, so that they don't grow back, thanks!

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b24db4c537...f99a193be1

**Comment by brianchandotcom** [comment]
@hhuijser can you SF prevent this.

@tinatian can you backport? See my tiny changes in upstream. Thanks!

**Comment by hhuijser** [comment]
Will add to SF

**Pull request closed without merging**
