### PR TITLE
LPS-62149 change control menu markup

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @asungutierrez

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest uno mas

**Comment by juliocamarero** [comment]
Hahahaha :smile: 

there seems to be a real failure, and I have a guess. I will debug tomorrow, thanks!

**Comment by brianchandotcom** [comment]
:) Ok, I'll close this pull for now then. Thanks @juliocamarero

**Pull request closed without merging**
