### PR TITLE
LRQA-19505 Implement load balancing logic for PR tester

### PR DESCRIPTION
**Pull request by pyoo47**
Each master is evaluated as follows

number of idle slaves
MINUS
number of items in the master's queue
MINUS
number of jobs that have been submitted to the master (via the load balancer) in the past 2 minutes (because it appears to take around this long for the jobs to register in the # of idle slaves).

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest (just borrowing this pull to test master)

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
https://github.com/pyoo47/liferay-portal/pull/8

**Pull request closed without merging**
