### PR TITLE
LPS-97971 Inject @Context with reflection 

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/45145eff8a...ac7c4607c7

**Comment by brianchandotcom** [comment]
@nhpatt backported to 7.1.x for you.

**Comment by brianchandotcom** [comment]
@shuyangzhou we drastically removed usage of @Context here.

**Comment by brianchandotcom** [comment]
@nhpatt can you type:

git grep -A 3 "@Context"

Can you remove all field level uses? We still have a few of those that are autogenerated.

Then, can we also figure out how to remove usage of method calls?

@Context Pagination pagination

Since we generate it anyways... the less we use of @Context the faster our boot up.

Thx!

**Comment by nhpatt** [comment]
There are a few due to OpenAPIResource (1 class per suite), I'll see if we can remove them.

**Pull request closed without merging**
