### PR TITLE
LPS-81926 Also hide default error message

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by jkappler** [comment]
ci:reopen

**Comment by jkappler** [comment]
@brianchiu, functional tests seem weird, and seems to be related to this PR. could you please take a look at it? Thanks

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchiu** [comment]
@jkappler 
Hopefully this is ok... those functional tests failed during setup because they could not add a user (see https://issues.liferay.com/browse/LPS-82301)

**Pull request closed without merging**
