### PR TITLE
LPS-74240

### PR DESCRIPTION
**Pull request by drewbrokke**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:reopen

**Comment by ling-alan-huang** [comment]
ci:retest

**Comment by ling-alan-huang** [comment]
The failures are not related to my changes.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/42b3e61a76...8e7141a733

**Pull request closed without merging**
