### PR TITLE
LPS-61176 when manually setting the type, the value is not obtained anymore from the context model

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @ealonso

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@evannagayama please resend. See poshi error. Thx.

**Comment by ealonso** [comment]
Hey @evannagayama,

I've rebase the pull and I send to you https://github.com/evannagayama/liferay-portal/pull/342

**Comment by evannagayama** [comment]
@brianchandotcom @ealonso Thanks we'll take care of it!

**Pull request closed without merging**
