### PR TITLE
LPS-71381 SF

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8a97965397...b00d728809

**Comment by brianchandotcom** [comment]
@arthurchan35 unit test please. Thx.

**Comment by brianchandotcom** [comment]
@arthurchan35 did you really mean LPS-71381? That ticket doesn't seem related. In any case, I went ahead and reopened that ticket and put it to resolved so QA can test against it. But it seems to me you may have used the wrong ticket.

**Comment by arthurchan35** [comment]
@brianchandotcom 
My apology, the last two SF commits are label with wrong ticket number LPS-71381, but the first 4 commits are with correct number LPS-73181.
I will go ahead and fix the commit info and send you a new pull request?
Is it okay?

**Comment by arthurchan35** [comment]
@brianchandotcom 
Just noticed it's merged.
Do we need to first revert those two SF commits?

**Comment by arthurchan35** [comment]
@brianchandotcom 
I reverted those two commits and recommit them with correct ticket number.
Here is the pull request: https://github.com/liferay/liferay-portal/pull/1663
Not sure if is the right procedure though.

**Comment by arthurchan35** [comment]
@brianchandotcom 
About the unit test.
Are you sure we want unit tests for impls in portal.model.impl package?
Because I dont see any unit test class for any of the impls there, or the directory itself does not exist.

**Pull request closed without merging**
