### PR TITLE
Talend - Input Component | master

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
[Commerce API Scrum board](https://issues.liferay.com/secure/RapidBoard.jspa?rapidView=3928)
----
Tickets: 
* https://issues.liferay.com/browse/COMMERCE-1304
* https://issues.liferay.com/browse/COMMERCE-1281
* https://issues.liferay.com/browse/COMMERCE-1332
* https://issues.liferay.com/browse/COMMERCE-1344

/cc @igorbeslic @matijapetanjek

### CODE REVIEW

**Comment by ZoltanTakacs** [comment]
Removed JavaDoc and forwarded to https://github.com/brianchandotcom/liferay-portal/pull/72204
@hhuijser do you happen to know what caused this Infinite loop in Source Formatter?

**Comment by igorbeslic** [comment]
Hi @ZoltanTakacs, why we still depend to jackson library?
I've just seen commit where we had got it back :) otherwise I would ask earlier :)

**Comment by ZoltanTakacs** [comment]
Hi @igorbeslic, 

Actually the `com.liferay.commerce.openapi.util` dependency had a transitive dependency for Jackson and I started to use it before Matija's send his work my way where he removed it.
- I've used Jackson to be able to parse JsonObject as a JsonNode as it has much more benefits and don't need to deal with low level things null checking/casting for handling JsonNode / ArrayNode / ValueNode related representations with the plain JsonObject so it was a safer solution from my side without need to hassle with the mentioned things.

Do you have any objection with using Jackson?

**Comment by igorbeslic** [comment]
This is late answer :) but had no time to answer earlier. No, no any objection. I didn't know we still have code that relies to it. Regarding to dependencies, our internal LCS team practice was that if we need only one class from jar, framework or API we do not use that api. Exception is case if we are in extreme hurry, so we close eyes, but later provide own implementation.

**Comment by hhuijser** [comment]
ci:test:sf

**Comment by hhuijser** [comment]
@ZoltanTakacs See https://github.com/brianchandotcom/liferay-portal/pull/72559

**Pull request closed without merging**
