### PR TITLE
master-qa-23282

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LRQA-23282

### CODE REVIEW

**Comment by brianchiu** [comment]
@michaelhashimoto @kiyoshilee

Second one I've seen. Is there something wrong with test-1-13? Same git issue on:
https://github.com/brianchandotcom/liferay-portal/pull/37723

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b04e145d0b...b9082b412d

**Comment by brianchiu** [comment]
@brianchandotcom 
I'm looking at the OSGiMongodbhook#MongoDBHookSmoke failure

**Comment by michaelhashimoto** [comment]
@brianchandotcom @pyoo47 @brianchiu @kiyoshilee
Here's a ticket for the corrupted github issue.
https://issues.liferay.com/browse/LRQA-23284

**Pull request closed without merging**
