### PR TITLE
LPS-176584

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue:https://issues.liferay.com/browse/LPS-176584

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:reopen

**Comment by p-albuquerque** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@p-albuquerque missing rename for _authorTermNameSuffixes

It's not a suffix

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3ace8bc137...850ad9225d

**Pull request closed without merging**
