### PR TITLE
LPS-78903 UsersAdminPortlet Users list - Export/Import option removed

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test

**Comment by matethurzo** [comment]
@brianchandotcom the failures seem unrelated, retesting

**Comment by matethurzo** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e21c5d6b02...47cd094554

**Pull request closed without merging**
