### PR TITLE
Lps 74651

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:retest

**Comment by tomwang2011** [comment]
ci:close

@brianchandotcom @shuyangzhou closing this for now, I will send a pull with all the deprecated classes in util-java for petra in 1 pull so we only need to publish once instead of publishing every time for each petra compat module, thanks!

**Comment by tomwang2011** [comment]
ci:stop

**Pull request closed without merging**
