### PR TITLE
LPS-69535 Poor Performance in edit_permissions.jsp when Loading Roles

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-69535](https://issues.liferay.com/browse/LPS-69535).<br><br>Hey Brian, this is a performance fix from support.  We looked into using DynamicQuery for this but we ended up needing the InlineSQLHelperUtil for permissioning.<br><br>/cc @pei-jung @mbowerman @jonathanmccann @shuyangzhou @jorgeferrer

### CODE REVIEW

**Comment by pei-jung** [comment]
Hey @brianchandotcom,

from @mbowerman 

> This is part of a larger set of fixes to improve the performance of loading a portlet's Permissions window when there are a large amount of roles. The full set of fixes contains modifications to edit_permissions.jsp which call the finder methods created here, but Julio asked me to break it up into two pull requests - one to the Roles team and one to the Portlet Configuration team. juliocamarero#4331.

**Comment by brianchandotcom** [comment]
@drewbrokke where is this used? I see a bunch of new methods.. but no modifications in usage. Merged.

**Comment by mbowerman** [comment]
Thanks @brianchandotcom! As @pei-jung mentioned, this is being broken up into two pull requests. The second pull request will have the usage of these methods.

Thanks also @pei-jung for all your work on this!

**Comment by drewbrokke** [comment]
@brianchandotcom my fault I neglected to include the larger picture.  Thanks @pei-jung and @mbowerman for clarifying! 👍

**Pull request closed without merging**
