### PR TITLE
[TS] LPS-86681 PasswordModifiedFilter check is unnecessary during impersonation

### PR DESCRIPTION
**Pull request by martamedio**
https://issues.liferay.com/browse/LPS-86681
cc/ @brianikim & @topolik

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@joshchong @xbrianlee can you please make sure the lpkg failure doesn't reoccur? The others should be fine.

**Comment by xbrianlee** [comment]
ci:reopen

The unique failure above passed in the previous relevant run. All other failures are failing in acceptance as well.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@martamedio @brianikim see d6d59c4 thx.

**Pull request closed without merging**
