### PR TITLE
LPS-72573 Incorrect error message displays for Web Form required field

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by vicnate5** [comment]
ci:reopen

**Comment by vicnate5** [comment]
@brianchandotcom I cannot find this commit in master upstream. Can this be merged?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4ed3cc692d...6d3784d225

**Comment by brianchandotcom** [comment]
@vicnate5 weird, I thought I merged it. My bad. Pushed it up now.

**Pull request closed without merging**
