### PR TITLE
LPS-174019 PATCH web content resets Tags metadata field

### PR DESCRIPTION
**Pull request by liulukiwi**
This is only for master.

https://issues.liferay.com/browse/LPS-174019

@jkappler

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:reopen

**Comment by liulukiwi** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/11002

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2cf020a39c...452c468f53

**Comment by brianchandotcom** [comment]
@Marina-Gouveia @jkappler see 452c468f53c7cca668cfd7e04db1d69f9b0eac43

**Pull request closed without merging**
