### PR TITLE
LPS-112464 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LPS-112464

cc/ @jbalsas

### CODE REVIEW

**Comment by john-co** [comment]
ci:reopen

**Comment by john-co** [comment]
Reviewed tests from https://github.com/jbalsas/liferay-portal/pull/2173. Test failures are unrelated. :heavy_check_mark:

:heavy_check_mark: ci:test:stable - 19 out of 19 jobs passed
:x: ci:test:relevant - 167 out of 170 jobs passed in 3 hours 2 minutes

modules-integration-mysql57-jdk8 is failing in upstream
SearchTuning#SearchWithSynonyms looks like a fluke

**Comment by brianchandotcom** [comment]
Sorry @jbalsas 

processCssClass(Set<String> className)

needs to be

processCssClasses(Set<String> cssClasses)

Please resend! Sorry!

**Comment by jbalsas** [comment]
It's okay @brianchandotcom, I know that, just not enough focus time yesterday...

Couldn't this be actually caught by SF? @hhuijser?

**Comment by hhuijser** [comment]
@jbalsas what exactly do you want SF to catch? The fact that we're passing a set with a singular object name?

**Comment by jbalsas** [comment]
Hey @hhuijser, one error here could've been

`processCssClass(Set className)` should be `processCssClass(Set cssClass)`.

Brian wasn't referring to that one, though, so maybe there's nothing to do here since `process*` is not a common pattern.

**Pull request closed without merging**
