### PR TITLE
LPS-80517

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:test

**Comment by jpince** [comment]
ci:test

**Comment by jpince** [comment]
@shuyanzhou is this a real failure? `junit.framework.AssertionFailedError: {level=ERROR, loggerName=com.liferay.portal.service.test.ServiceTestUtil, message=com.liferay.portal.kernel.exception.NoSuchCompanyException: No Company exists with the key {webId=liferay.com}`

**Comment by kenjiheigel** [comment]
@hhuijser, I think this causes a start up error which balloons the size of the console output, and crashes our CI build's JVM due the the large logs.. I've found this in start up errors:
https://gist.github.com/kenjiheigel/d471ebf42c8fff4a69dafb455e35aabc

The exception involves the NPMResolverServiceFactory class, which was modified by your changes in this pull. Maybe if you could review your changes to that file, and limit the amount of testing before running all of CI. 

We, in QA Eng, or someone on Portal QA can help with limiting your testing so that these changes don't get introduced into master, and so they don't end up crashing a CI centurion. 

@brianchiu, @jpince, @pyoo47

**Comment by kenjiheigel** [comment]
@shuyangzhou

**Comment by shuyangzhou** [comment]
@hhuijser all those field level Dynamic/Greedy, like https://github.com/brianchandotcom/liferay-portal/pull/58157/files#diff-958458df4bea24a4286be5af2e010924R119 , they need to be volatile(Remember that thread safety handling thing I mentioned earlier in the email, apparently SCR has it covered for at least this field case, but I doubt it covers the method case). Then the failure will go away. And you can just ant all and boot up locally, as long as locally you can boot up fine, CI would not complain this.

**Comment by hhuijser** [comment]
Hey @shuyangzhou 

So, this all from more than 2 years ago...

You opened LPS-59841 and here we added logic to SF to mark all those fields volatile: https://github.com/liferay/liferay-portal/commit/de7b09627324d1437f4b6f0b2b25d248f1668bfa

However... LPS-61896 was opened a bit later to pretty much revert that logic and do it the other way around: https://github.com/liferay/liferay-portal/commit/b8b1d1b786a7b26e361f29cdbd68946a986abe55

This was done after a long email thread with you, Ray and Miguel. Just sent you email with that thread.

**Pull request closed without merging**
