### PR TITLE
LPS-100948 remove compiler issue

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/aebc7793c0...9f9a967221

**Comment by brianchandotcom** [comment]
@nhpatt I merged this.. but I added this check because @inacionery was manually doing something like this.

Can we add this back in for the cases where it can work?

**Comment by brianchandotcom** [comment]
Or make the test more generic so it can work? If it's a long or int, do the test etc... thx @nhpatt

**Comment by nhpatt** [comment]
Will do! :)

**Pull request closed without merging**
