### PR TITLE
LPS-53183 Update dir and package name

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
ci:retest

**Comment by csierra** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e857270819...c7d176ec11

**Comment by brianchandotcom** [comment]
Please see my changes in upstream. Thx! @csierra

**Pull request closed without merging**
