### PR TITLE
[TOP PRIORITY] LPS-63194 Remove IconConfiguration factories [PING]

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Hey @marcellustavares, 

we have applied this change in the API of the PortletConfigurationIcons in your modules. Could you please review the commits related to your components to make sure we didn't break anything?

thanks a lot!

**Comment by juliocamarero** [comment]
Hey @sergiogonzalez, 

we have applied this change in the API of the PortletConfigurationIcons in your modules. Could you please review the commits related to your components to make sure we didn't break anything?

thanks a lot!

**Comment by juliocamarero** [comment]
Hey @lionah, 

we have applied this change in the API of the PortletConfigurationIcons in the Marketplace modules. Could you please review the commits related to your components to make sure we didn't break anything?

thanks a lot!

**Comment by juliocamarero** [comment]
Hey @drewbrokke @pei-jung @jorgeFerrer 

we have applied this change in the API of the PortletConfigurationIcons in your modules (users admin... etc). Could you please review the commits related to your components to make sure we didn't break anything?

thanks a lot!

**Comment by JorgeFerrer** [comment]
Great job, Julio. This is much simpler :+1: 

Now you just need to remove getWeight() (using serviceRanking instead) and rename PortletConfigurationIcon as PortletMenuEntry :)

**Comment by marcellustavares** [comment]
thanks @juliocamarero, we'll test that.

cc @rafaprax, @leoadb, @inacionery

**Comment by juliocamarero** [comment]
Hey @matethurzo,

we have applied this change in the API of the PortletConfigurationIcons in the Export/Import modules. Could you please review the commits related to your components to make sure we didn't break anything?

thanks a lot!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4985d110ca...bf5ace9c54

**Comment by brianchandotcom** [comment]
@juliocamarero good job on this! @ealonso 

Can you guys also send me a backport to portal ee-7.0.x? We have some ee specific modules that'll need this.

Thx.

**Comment by juliocamarero** [comment]
Hi Brian, 

I couldn't find any module affected in portal or plugins ee-7.0.x

thanks!

**Comment by marcellustavares** [comment]
Thanks @juliocamarero :+1:

**Pull request closed without merging**
