### PR TITLE
LPS-74849

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Related pull for 7.0.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/18453

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@hhuijser can you send me a pull for 7.0.x-private? and possibly master-private? Thx.

**Comment by hhuijser** [comment]
@brianchandotcom I am doing this one in stages. Right now, only portal-kernel. The private stuff will come later, probably at the very end.

**Pull request closed without merging**
