### PR TITLE
LPS-99073 Clear mapping values and fields when changing image source type

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4fac0faa7c...b2cd5e46ca

**Comment by brianchandotcom** [comment]
@ruben-pulido @sandrodw3 this was very good. Just one tiny change in b2cd5e4

**Comment by sandrodw3** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
