### PR TITLE
Lps 172295

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/97d3b96b2b...5638e69925

**Comment by brianchandotcom** [comment]
@shuyangzhou see my rename of LPS-X in 335199d297a37a7ae75e083defe2c8faa64f17b5 thx

**Comment by shuyangzhou** [comment]
Oops, sorry, I missed the renaming for it.

**Pull request closed without merging**
