### PR TITLE
Lps 84655

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:test

**Comment by austinchiang** [comment]
@brianchandotcom Please do not merge this pull yet. I am checking to see if this will cause any regressions because many functional tests failed on a related pull [here](https://github.com/austinchiang/liferay-portal/pull/309)

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
Woops! Sorry @austinchiang didn't see your comment til now, can you send me any ignores or pull fixes if it breaks stuff? Thx.

**Pull request closed without merging**
