### PR TITLE
LPS-58170 Fix classloading composition when using allowed classes from Freemarker templates

### PR DESCRIPTION
**Pull request by mdelapenya**
cc/ @migue

### CODE REVIEW

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
cc/ @ZoltanTakacs This pull should be added to RC

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c6561b786d...e1dc520b6c

**Comment by ZoltanTakacs** [comment]
Thank you @mdelapenya. It's been merged to 7.0.x.

Please note that the backport workflow has been changed for the RCs. 
For the details please see @jhendley 's email or refer to this [document](https://docs.google.com/document/d/1A-EoPvI1KDDpUH2PAlKmpgUDb_2RFM4iwpB_4loQHFk/edit).

Thank you,
Zoltán

**Pull request closed without merging**
