### PR TITLE
LPS-64379 SF

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cb09284a0f...6dddc13f0a

**Comment by evannagayama** [comment]
Looking into the poshi test failure

**Comment by evannagayama** [comment]
ci:retest

**Comment by sharonchoi** [comment]
@vicnate5 Workflow and forms poshi test failures

**Pull request closed without merging**
