### PR TITLE
LPS-56300 support for portlet configuration using a technology different to JSP (such as freemarker)

### PR DESCRIPTION
**Pull request by juliocamarero**
@marcellustavares I have applied the new pattern to the ddl portlets, could you please have a look? thanks!

### CODE REVIEW

**Comment by juliocamarero** [comment]
@sergiogonzalez I have applied the new pattern to the dl & collab portlets, could you please have a look? thanks!

**Comment by juliocamarero** [comment]
@epgarcia this will allow us to have configuration in the freemarker portlets of Audiente Targeting

**Comment by juliocamarero** [comment]
@codyhoag we probably want to document this in the dev guide for 7.0

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@juliocamarero please resend, real test failure. Thx

**Pull request closed without merging**
