### PR TITLE
Lps 81420

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c7192db35a...9fbd66de28

**Comment by brianchandotcom** [comment]
@shuyangzhou this didn't compile.. see my fix in upstream 97571310f27e7cff9e4259b292c9ab56c02c46be

@ngriffin7a @shuyangzhou I also made tons of tiny changes in upstream. Thank you so much for getting this done @ngriffin7a !

**Comment by brianchandotcom** [comment]
@ngriffin7a please review my changes. Thx.

**Comment by ngriffin7a** [comment]
@brianchandotcom @shuyangzhou I reviewed all the changes. Outstanding code review! Thanks so much. :)

**Comment by ngriffin7a** [comment]
@brianchandotcom @shuyangzhou Credit for the design of the RenderState JSON object goes to @ipeychev circa 2013. Congrats again Iliyan! The implementation just got merged! Great design! :) https://twitter.com/liferayfaces/status/545706602771140609

**Pull request closed without merging**
