### PR TITLE
LPS-102110 Old AUI component still brings in legacy classes which are the ones we're trying to replace and remove

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
SF seems to be failing due to either network connectivity or some other build error, but it's not even running :(

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6b0732d72b...919b8de39e

**Pull request closed without merging**
