### PR TITLE
LPS-73206

### PR DESCRIPTION
**Pull request by matethurzo**
hey @brianchandotcom the last commit is to suppress tests because we have found that there are bugs in different components. we have opened up tickets for those, and will be fixed during the staging triage:

- https://issues.liferay.com/browse/LPS-73398
- https://issues.liferay.com/browse/LPS-73397
- https://issues.liferay.com/browse/LPS-73399

once those are fixed, we'll re-enable the test. The fix is generic though and works for the rest of the components.

### CODE REVIEW

**Comment by matethurzo** [comment]
@brianchandotcom the failures are unrelated, the file the SF is complaining about hasn't been changed in this pull.

**Comment by matethurzo** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/87c5c8c1c6...70301a8f9b

**Comment by brianchandotcom** [comment]
@matethurzo thx for the explanation.

**Pull request closed without merging**
