### PR TITLE
LPS-62466 Fix macro to change info assertion for wiki page

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by sharonchoi** [comment]
hey @robertoDiaz this pull is missing some of my commits....I think you might have to refetch the branch I pushed to you because I force pushed additional changes under that commit.

**Comment by sharonchoi** [comment]
This commit should have these changes https://github.com/sharonchoi/liferay-portal/commit/e635a1b1ec691a27291a1606ff768deedec3bdaf

**Comment by brianchandotcom** [comment]
@sharonchoi please resend? Thx.

**Comment by sharonchoi** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/35087

**Pull request closed without merging**
