### PR TITLE
LPS-67772

### PR DESCRIPTION
**Pull request by Ithildir**
Hi @brianchandotcom!

I'm sending you this pull because @jpince told me `ModulesStructureTest` is constantly failing on `ee-7.0.x`. The reason is that the Journal subrepo has a `.gitattributes` file, but not `.soy` files. We need `.gitattributes` in order to force Unix line endings on Soy files because of a [bug](https://issues.liferay.com/browse/LPS-67772) in the Soy compiler that AFAIK hasn't been solved yet (@jbalsas, confirm?)

This pull simplifies the test so that every subrepo has to have the same `.gitattributes`. Do you think it's okay or we should manually delete the `.gitattributes` file of Journal in `ee-7.0.x`?

Thank you!

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:reopen

**Comment by jbalsas** [comment]
@Ithildir, yeah, this is still an ongoing issue... we've filed https://github.com/google/closure-templates/issues/111 and @mairatma has updated that info in [LPS-67772](https://issues.liferay.com/browse/LPS-67772).

We'll update the compiler as soon as it gets fixed.

**Comment by brianchandotcom** [comment]
@Ithildir this still breaks

com.liferay.portal.modules.ModulesStructureTest.testScanBuildScripts


Can you resend? Thx.

**Comment by Ithildir** [comment]
@brianchandotcom, it breaks because `modules/apps/adaptive-media/.gitattributes` is missing. Isn't that a read-only repo?

**Pull request closed without merging**
