### PR TITLE
LPS-106413 Moves to layout.type.controller package

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b02f6b35ab...9bd0987400

**Comment by brianchandotcom** [comment]
Very very well done @ealonso 

Thank you also for not losing the translations, and for modularizing the translations properly! Well done!

Just a minor javadoc change from me in 9bd098740008bee40b053138f84944adb04efe72

**Pull request closed without merging**
