### PR TITLE
LPS-108246 Updating tests

### PR DESCRIPTION
**Pull request by inacionery**
/cc @naraandrade

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:close

Will reopen this after further evaluation. 

modules-unit failure due to a jar that wasn't available. Asking IT to flush that from the squid. 
```
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':apps:document-library:document-library-web:compileTestJava'.
     [exec] > Could not resolve all files for configuration ':apps:document-library:document-library-web:testCompileClasspath'.
     [exec]    > Could not download assertj-core.jar (org.assertj:assertj-core:3.10.0)
     [exec]       > Could not get resource 'http://repository-cdn.liferay.com/nexus/content/groups/public/org/assertj/assertj-core/3.10.0/assertj-core-3.10.0.jar'.
     [exec]          > Premature end of Content-Length delimited message body (expected: 3964428; received: 236465
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:document-library:document-library-web:compileTestJava'.
     [exec] 	at 
```

This [modules-integration test failures](https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/369476/) may be related to this pull, but pending QA review: 
* com.liferay.depot.internal.search.test.DepotEntrySearchTest.testSearchBothWithPermissions
* com.liferay.portal.workflow.metrics.service.internal.search.index.test.SLAInstanceResultWorkflowMetricsIndexerTest.testReindex

**Comment by kenjiheigel** [comment]
@inacionery, @naraandrade, could you guys look into this?

com.liferay.portal.workflow.metrics.service.internal.search.index.test.SLAInstanceResultWorkflowMetricsIndexerTest.testReindex is unrelated and fails due to LPS-108756. 
com.liferay.depot.internal.search.test.DepotEntrySearchTest.testSearchBothWithPermissions is inconclusive. 

From QA:
> The PortalLogAssertorFailure looks Workflow related. It was thrown by com.liferay.portal.workflow.metrics.rest.resource.v1_0.test.InstanceResourceTest
> com.liferay.portal.workflow.kaleo.exception.NoSuchInstanceException: No KaleoInstance exists with the primary key 8121262661855977626

Here's the full stacktrace to that test: https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/369476/AXIS_VARIABLE=33,label_exp=!master/testReport/junit/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXMLLog/

Might be related to the change in https://github.com/brianchandotcom/liferay-portal/pull/85820/files#diff-77fd76b7519e1656450a23a6d59a74b4

**Comment by inacionery** [comment]
Hey @kenjiheigel,

These changes only affect the Workflow, so it is impossible to break the Search component, also the SLAInstanceResultWorkflowMetricsIndexerTest fail was fixed in the PR https://github.com/BryanEngler/liferay-portal/pull/486, just waiting the @BryanEngler review.

For me, these failures are again CI false positive.

Could you please reopen? This PR is blocking the delivery of a story.

Thanks!

**Comment by inacionery** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
