### PR TITLE
LPS-74384 Bump version

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:close

**Comment by vicnate5** [comment]
@brandizzi Weird CI results, I am closing until the retest comes back. Will reopen if it looks good.

**Comment by vicnate5** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/906e46a678...8df1a2e0be

**Pull request closed without merging**
