### PR TITLE
LPS-106277 Add cases to assert display correctly in specific content display fragment

### PR DESCRIPTION
**Pull request by manoelcyreno**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@manoelcyreno portal-web/test/functional/com/liferay/portalweb/dependencies/display-collection-name.zip/document-and-media/index.html does not match our other HTML either.

@hhuijser can you resend me this pull?

They fixed the one file I asked them to but ignored the other ones.

@Tim-Cao fyi

**Comment by hhuijser** [comment]
@Tim-Cao @manoelcyreno 

The issue is that SF is skipping the directory '/portal-web/test/functional/com/liferay/portalweb/dependencies/' (https://github.com/liferay/liferay-portal/blob/master/source-formatter.properties#L16)

You can see that if you remove that line for `source-formatter.properties` and run SF, the `json` and `html` are getting formatted nicely, but also a ton of other files are getting formatted (and some of them are a mess).

Can you guys work on this?
Run SF and check the files to make sure we're not breaking stuff. If there are files we really want to skip certain checks, let's use `source-formatter-suppressions.xml` instead.

You can send me the pull requests and I will review. Please send in batches and not one big pull with hundreds of changed files.

Let me know if you need more information.

Thanks!

**Comment by hhuijser** [comment]
Sent pull to Brian: https://github.com/brianchandotcom/liferay-portal/pull/82772

**Comment by brianchandotcom** [comment]
@manoelcyreno see https://github.com/brianchandotcom/liferay-portal/pull/82772

**Pull request closed without merging**
