### PR TITLE
LPS-71002

### PR DESCRIPTION
**Pull request by matethurzo**
rebased, added the final prefixes and noticed an unused constant

### CODE REVIEW

**Comment by matethurzo** [comment]
the failure is unrelated, reopening and retesting

**Comment by matethurzo** [comment]
ci:reopen

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
@brianchandotcom others have the same failures, it's not caused by this PR

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/74d67aab2b...ad473016b0

**Comment by brianchandotcom** [comment]
Thx @matethurzo see my changes in upstream. Thx.

**Pull request closed without merging**
