### PR TITLE
Upgrade Process: Running the upgrade process in 'offline mode' using a Shell Script

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by migue** [comment]
Everything seems to be ok, 
Retesting just in case ... ci:retest

**Comment by migue** [comment]
Not related but let's get the build green ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/819a101f0d...26cdc678be

**Comment by brianchandotcom** [comment]
@migue did a partial merge. Am going to send the Shell script for QA to review.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/58f9169c2f...9720d4bae2

**Comment by brianchandotcom** [comment]
@migue can you review my changes in 9720d4bae276470ea9c417c245f340e253b6d330 ? Thx.

**Pull request closed without merging**
