### PR TITLE
LPS-60255 Show only management bar when we have layout prototypes

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@ealonso poshi test failures.

**Comment by ealonso** [comment]
Hey @evannagayama,

We've changed the checkbox for a toggle-switch and I think this is the problem. Could you take a look into to this and update the test?

Thanks!!!

**Comment by evannagayama** [comment]
Thanks @ealonso, we'll fix it today. @koor4356, can you take a look and make test fixes? Thanks!

**Comment by koor4356** [comment]
@evannagayama, I've just pushed the test fixes to you.

https://github.com/evannagayama/liferay-portal/pull/224

**Pull request closed without merging**
