### PR TITLE
LPS-105361 Fixing css class name

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
@boton

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/104357bb1d...907af57f96

**Comment by brianchandotcom** [comment]
@4lejandrito can you chase down someone to fix

```
AXIS_VARIABLE=0,label_exp=!master #342764
LocalFile.ContentPageTemplates#DeletePageTemplate - Poshi Report - Poshi Summary - Console Output
```

**Comment by 4lejandrito** [comment]
@austinchiang

**Pull request closed without merging**
