### PR TITLE
LPS-54852 SEMVER

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
Seems we have timing related failures again. These failures are completely different than the first set.

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
These issues should go away after applying https://github.com/brianchandotcom/liferay-portal/pull/26544

**Comment by brianchandotcom** [comment]
ci:retest (should work after Ray's fix for portal-javascript)

**Comment by rotty3000** [comment]
rebased

**Comment by rotty3000** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@rotty3000 please resend? Seems like real issues here.

**Comment by rotty3000** [comment]
The issues are NOT related! The problem is caused by executing arbitrary other tests alongside PACL in a java asecurity enabled JVM.

**Comment by rotty3000** [comment]
PACL tests should be run in a JVM in isolation!

**Comment by rotty3000** [comment]
Can we either reopen this or tell me how to avoid the test from being executed along with the PACL tests.

**Comment by brianchandotcom** [comment]
Hey @rotty3000 

I reopened it, but @shuyangzhou made the PACL tests not run in its own isolated JVM because it helps us expose these issues. 99% of the time, he fixed them by fixing some other test that was "leaking" something.

@shuyangzhou can you point @rotty3000 in the right direction? Thx.

**Comment by shuyangzhou** [comment]
@rotty3000 you did fix a problem for the script engine in https://github.com/brianchandotcom/liferay-portal/pull/26544

And the current failures are different. (Not talking the latest ones, but the last PACL ones). If you look closer, you will see the PACL errors are not the same as the first ones.

And they are indeed caused by the changes in this pull, for example, a section of the errors:

    [junit] [PACLTestSuite]18:32:43,949 ERROR [fileinstall-/opt/dev/projects/github/liferay-portal/osgi/portal][com_liferay_blogs_ratings_definition:96] [com.liferay.blogs.ratings.definition.BlogsPortletRatingsDefinition] Cannot register Component 
    [junit] java.security.AccessControlException: access denied ("com.liferay.portal.security.pacl.PACLUtil$Permission" "getPACLPolicy")
    [junit] 	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:372)
    [junit] 	at java.security.AccessController.checkPermission(AccessController.java:559)
    [junit] 	at com.liferay.portal.security.pacl.PortalSecurityManagerImpl.checkPermission(PortalSecurityManagerImpl.java:301)
    [junit] 	at com.liferay.portal.security.pacl.PACLUtil.getPACLPolicy(PACLUtil.java:62)
    [junit] 	at com.liferay.portal.security.pacl.dao.jdbc.PACLDataSource.getConnection(PACLDataSource.java:46)
    [junit] 	at com.liferay.portal.dao.jdbc.util.DataSourceWrapper.getConnection(DataSourceWrapper.java:37)
    [junit] 	at org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy$LazyConnectionInvocationHandler.getTargetConnection(LazyConnectionDataSourceProxy.java:400)
    [junit] 	at org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy$LazyConnectionInvocationHandler.invoke(LazyConnectionDataSourceProxy.java:375)
    [junit] 	at com.sun.proxy.$Proxy18.prepareStatement(Unknown Source)
    [junit] 	at com.liferay.portal.configuration.persistence.ConfigurationPersistenceManager.getDictionaries(ConfigurationPersistenceManager.java:118)

It sourced from ConfigurationPersistenceManager, seems it is violating PACL DB accessing rules.

I am sure you will get the same error when you bootup portal with PACL on this pull.

And also all pacl tests are running in an isolation jvm. Just not forked by junit.

**Comment by brianchandotcom** [comment]
@rotty3000 I'm going to close this pull since Shuyang's previous comment shows it's an error from this pull. Thx.

**Comment by rotty3000** [comment]
I firmly disagree since we haven't even done any security development yet
in osgi AND we're NOT going to use PACL.

**Comment by shuyangzhou** [comment]
Then you should wipe out PACL first, otherwise the PACL tests will just block the way.
Want it or not, currently if you boot up portal with PACL on, it also loads OSGi. If the OSGi modules do not respect PACL's rules, PACL will simply reject them in the way how those tests are failing.

Same problem will happen in production env too, this is not a test/ci issue, it is OSGi and PACL don't like each other issue.
Since you pretty much own both components, it is really your call about what to do.

**Pull request closed without merging**
