### PR TITLE
LPS-87427 Using tag navigation to filter entries results in wrong number

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso, @dacousalr

**Comment by jkappler** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/35dc737c9f...c5791195df

**Comment by brianchandotcom** [comment]
@arthurchan35 we need to unit test or at least functional test this. Thx.

**Pull request closed without merging**
