### PR TITLE
LPS-92618.22 integer

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/addaa959be...9f410660fa

**Comment by brianchandotcom** [comment]
@nhpatt can you do the same for bulk and data-engine? Thx!

**Comment by brianchandotcom** [comment]
@ZoltanTakacs fyi for commerce

**Comment by nhpatt** [comment]
I went to change bulk and data-engine but they have any numbers :)

**Comment by ZoltanTakacs** [comment]
We always have the format if we used Number in spec so don't have `Number` as a java type in our code. Thanks for the heads-up!

**Pull request closed without merging**
