### PR TITLE
LPS-72669 Avoid the unnecessary heavy TrashUtil.isInTrash() call for …

### PR DESCRIPTION
**Pull request by shuyangzhou**
…DiscussionComment

### CODE REVIEW

**Comment by pyoo47** [comment]
Pull request tests are not triggering automatically so I'm going to attempt to trigger them manually.

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/53ec711fb7...90d1be6f36

**Comment by brianchandotcom** [comment]
@shuyangzhou please backport. Thx.

**Comment by shuyangzhou** [comment]
@tomwang2011 backport please, give this one a higher priority in the backport queue.

**Pull request closed without merging**
