### PR TITLE
LPS-61748 TEMP CI CACHE

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
FYI @Ithildir

**Comment by rotty3000** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@rotty3000 I made some minor SF and am testing it here as well https://github.com/brianchandotcom/liferay-portal/pull/34112

**Comment by brianchandotcom** [comment]
@rotty3000 same broken results in my pull too :(

**Pull request closed without merging**
