### PR TITLE
Lps 75610

### PR DESCRIPTION
**Pull request by shuyangzhou**
@brianchandotcom please don't back port this.

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/48e66d1ef0...7cf3b24d74

**Pull request closed without merging**
