### PR TITLE
LPS-63683 extract css from themes to the theme contributors

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Hey @matethurzo we have moved some code related to staging that was hardcoded in the themes (since the beginning of times) to a theme contributor of your module. Can you please review our changes?

thanks a lot!!

**Comment by matethurzo** [comment]
@juliocamarero Looks good to me, although I can see some CSS has been deleted from the staging bar, was that obsolete? I cannot see that anywhere being moved so I assume that's some junk or unnecessary code.

**Comment by juliocamarero** [comment]
@matethurzo it has been moved to the control menu since several control menu entries use it now (not only the staging bar). Let me know if you see something that wasn't moved there.

thanks a lot!

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@jkappler @juliocamarero @marcoscv-work 

please resend:

```
pe.printStackTrace();

this._customizationSettingsProductNavigationControlMenuEntry
```

are at least 2 issues. May have more.

Thx.

**Pull request closed without merging**
