### PR TITLE
LPS-106440 Check permissions to show or not show the dropdown menu

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@ealonso test failure, please resend.

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @Tim-Cao @liulukiwi,
Could you please take a look to the tests failures? I think we need to update the poshi tests.
Thanks!!

**Comment by liulukiwi** [comment]
Hi @ealonso ,
Those failures are more about LPS-106882, we'll keep fixing the poshi realted tests.

**Pull request closed without merging**
