### PR TITLE
LPS-59995

### PR DESCRIPTION
**Pull request by natecavanaugh**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
More poshi failures. Please talk to @brianchiu @marcoscv-work

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@natecavanaugh @marcoscv-work 

Something is weird about this. I ran one of the tests that failed and was unable to reproduce that error. The error that occurred for each of the failures was the same too.

If you look [here](https://test-1-17.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/269/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=PGBookmarks%23EditFolder,label_exp=!master/functional-tomcat-mysql/1/index.html) and click on the furthest down red exclamation mark...

The failure was on this step:
```
<execute function="AssertClick" locator1="DockbarAddpanelapplications#APPLICATIONS_TAB" value1="Applications" />
```

It's trying to click on the "Applications" tab, but based on the screenshots the tab is still there.

So then I looked at where the locator is stored (I first looked in DockbarAddpanelapplications.path, but didn't find it there, then I saw that it extended DockbarAddpanelcontent.path), which is [here](https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/tests/enduser/wcm/navigation/dockbar/block/action/DockbarAddpanelcontent.path#L48).

The locator "//ul[contains(@class,'nav-pills')]//li/a[contains(.,'Applications')]" works fine on that tab.

I ran a retest on this to see if the same result occurs again.

CC @michaelhashimoto

Hey Hashi, do you know what's up with this? When I look at the poshi report, the listed cause is this:
```
Error on line 4 of document  : The element type "event" must be terminated by the matching end-tag "</event>". Nested exception: The element type "event" must be terminated by the matching end-tag "</event>".
```

This doesn't look like a normal error readout and has nothing to do with the commits being tested.

**Comment by michaelhashimoto** [comment]
@brianchiu - This will eventually be fixed by this ticket:
https://issues.liferay.com/browse/LRQA-19196

**Pull request closed without merging**
