### PR TITLE
LPS-167469 Fix accessibility when using JAWS

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
Manually forward based on https://github.com/liferay-frontend/liferay-portal/pull/2838#issuecomment-1319015872

Comes from https://github.com/brianchandotcom/liferay-portal/pull/126477 

I had to force push as I realized that I needed to add `&nbsp;<liferay-ui:message key="use-tab-key-to-navigate" />` to all four existing `<liferay-ui:message key="intermediate-pages" />` 
Before: https://github.com/brianchandotcom/liferay-portal/pull/126477/commits/a0a45313f3bc5d4bd090bf64313c469650d2da4d
After: https://github.com/brianchandotcom/liferay-portal/commit/39f460e9a74735fa39a4d88c938a09cb3b1bd44c

If you think it needs to pass again the automatic tests, please let me know.

Thanks!

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2bff679365...cdd5e7af67

**Comment by brianchandotcom** [comment]
@georgel-pop-lr just 24d4c49c81b4d4d04a1add410523f06abcc5ae68

**Comment by georgel-pop-lr** [comment]
> @georgel-pop-lr just [24d4c49](https://github.com/brianchandotcom/liferay-portal/commit/24d4c49c81b4d4d04a1add410523f06abcc5ae68)



> @georgel-pop-lr just [24d4c49](https://github.com/brianchandotcom/liferay-portal/commit/24d4c49c81b4d4d04a1add410523f06abcc5ae68)

Thanks, then I would need to run [buildLang](https://github.com/brianchandotcom/liferay-portal/pull/126483/commits/3ea1efbafe61eea30db6239f54a98f29884c63c5) again?

**Pull request closed without merging**
