### PR TITLE
LRQA-59386 fix site navigation

### PR DESCRIPTION
**Pull request by rodrigocunhaa**

### CODE REVIEW

**Comment by rodrigocunhaa** [comment]
I'm manually forwarding it because the failures are not related and this commit fixes a lot of Poshi tests that were ignored.

**Comment by rodrigocunhaa** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/009c90ee86...69eae0e0d5

**Pull request closed without merging**
