### PR TITLE
Lps 55754

### PR DESCRIPTION
**Pull request by shuyangzhou**
This should at least make it compiles.
Not sure whether the tests will pass or not, since they are plain integration tests, moved out from portal-impl, there might be some relative dir issues, just have the CI run them first.

CC @epgarcia

### CODE REVIEW

**Comment by shuyangzhou** [comment]
On a second thought, those tests have to stay as arquillian ones, as it depends on other modules, however they are certainly broken now, and they should not use powermock at all, that is against the nature of arquillian tests. And the powermock osgi depencencies can not be resolved at all, as no one is providing them.

So my current pull is just fixing the compile issue and exclude lar-test from running on CI.

@epgarcia, you need to get rid of all powermock usage in those tests. And re-enable the lar-test on CI.

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/26977 to have a cleaner ci result log

**Comment by epgarcia** [comment]
Hi @shuyangzhou,

Thanks for fixing it. I worked with several branches to move these tests and I think something went wrong when merging the lar-tests with my changes for journal and staging. I'm sorry, 'll be more careful in the future. I'll rebase my original branch with the lar-tests (where I had all of them passing locally) and send a PR to @juliocamarero and @brianchandotcom to have these tests active ASAP.

Thanks again

**Pull request closed without merging**
