### PR TITLE
LPS-64093 SF

### PR DESCRIPTION
**Pull request by rotty3000**
/cc @juangon @ngriffin7a centralized all the web.xml and web-fragment parsing to the factory, now the context init params are set correctly, no duplication of logic

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@rotty3000 rebase error with one of your other pulls? Please resend. Thx.

**Pull request closed without merging**
