### PR TITLE
LPS-168565 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-168565

This is only for master.

@sandrodw3

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure case is unrelated to changes in this PR.
See https://github.com/liferay-echo/liferay-portal/pull/10416
ci:test:stable - 28 out of 28 jobs passed
ci:test:relevant - 68 out of 71 jobs passed in 1 hour 54 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3d07176a30...824c4e4fdc

**Comment by brianchandotcom** [comment]
@sandrodw3 see 5429671f5faf3655b276ea7755cf9ac25e58b54e @ling-alan-huang I thought SF enforce this?

**Pull request closed without merging**
