### PR TITLE
LPS-66237 As a user admin I can view the list of users and organizations as a grid of icons or in a descriptive list display within Users Admin

### PR DESCRIPTION
**Pull request by alee8888**

### CODE REVIEW

**Comment by alee8888** [comment]
@drewbrokke @natecavanaugh @pei-jung
There were breaking functional test fixes needed for LPS-66237. Thanks.

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bf3e19e581...b837f44111

**Pull request closed without merging**
