### PR TITLE
master-qa-28028

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LRQA-28028

This pull reverts changes made in #44132, which have been causing roles tests to fail.

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest - Failed due to broken distribution node.

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:close

**Comment by brianchiu** [comment]
@xbrianlee 
The broken tests are in 7.0 and not in master. Sorry I didn't pay attention to which branch you sent this to.

**Pull request closed without merging**
