### PR TITLE
LPS-87353 Update snapshots

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4081cdea69...e8e0e3584a

**Comment by brianchandotcom** [comment]
@jeyvison @gabrielwas see e8e0e3584a71d5e9e916879c8f1d4658b40551ef thx

**Comment by gabrielwas** [comment]
Hi @quanhuynhces! First, thank you for investigating this and for the detailed description! 
Do you have the code that fixes it? If yes, could you send this code to @liferay-forms so guys can review it?

Thank you again!

cc: @rodrigopaulino @carolmariaabb

**Comment by quanhuynhces** [comment]
Thank you @gabrielwas

**Pull request closed without merging**
