### PR TITLE
Lps 58662

### PR DESCRIPTION
**Pull request by shuyangzhou**
@brianchandotcom with this change, we can turn back on MySQL tests.

But the date milliseconds issue is still far away from finishing.

We need to completely remove the DateUtil.compareTo(Date date1, Date date2, boolean ignoreMilliseconds), DB.isSupportsDateMilliseconds() and their usage to be accurate on all time stamps processing and we will eventually eliminate all those annoying randomly failing time based tests.

And we just found out other dbs like sybase, db2 also have some sort of special rules for milliseconds processing, the rest of the clean up process might take a longer time. So I thought I would do them separately, to let MySQL tests back up running first.

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
@shuyangzhou - I'm going to reset the servers so I will re-run this pull request after it's done.

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@kiyoshilee what's wrong with the db2 servers?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6da3fe594b...07bffc2f63

**Comment by kiyoshilee** [comment]
@brianchandotcom Hashi saw the error in the Sybase test on Friday. He knows what the error is (.git/index.lock exists) and I think he made a ticket for it, but I'll check with him. I think this is the error you're referring to in db2, but if I'm wrong please let me know.

**Pull request closed without merging**
