### PR TITLE
LPS-56877

### PR DESCRIPTION
**Pull request by Ithildir**
cc @shuyangzhou

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f8069c6042...5cbbc74e84

**Comment by shuyangzhou** [comment]
@Ithildir This is not really fixing the problem see that https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=5,label_exp=!master/2663//testReport/com.liferay.bookmarks.social.test/BookmarksEntryActivityInterpreterTest/testActivityInterpreter

bookmarks-web is still not being loaded. Same failure as before.

**Comment by Ithildir** [comment]
Ok, I'll re-add the logs so at least we can see the web.xml...

**Comment by Ithildir** [comment]
Launched with logs: https://github.com/Ithildir/liferay-portal/pull/100

**Pull request closed without merging**
