### PR TITLE
LPS-169559 Add LIst Type Entries ERC on Local Service and Rest Layers

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-169559

### CODE REVIEW

**Comment by mateussgn** [comment]
Resending based on https://github.com/murilostodolni/liferay-portal/pull/10

**Comment by mateussgn** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3073d0a3d8...891c4c3ee9

**Comment by brianchandotcom** [comment]
Great job @mateussgn @guilhermedcamacho

**Pull request closed without merging**
