### PR TITLE
LRQA-51488 Run buildLang in apps/archived

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-51488

@brianchandotcom, I want to let any legacy strings that *would* sync with their master counterparts to cascade down to the legacy branches via our sync with Crowdin.  After a few days, I'll follow this pattern, sending in order (i.e. 7.2, 7.1, ...).  Thanks!

### CODE REVIEW

**Comment by Hanlf** [comment]
The writePoshiProperties failure will be fixed under LRQA-56705, thanks!

**Comment by brianwulbern** [comment]
stable will be fixed in https://github.com/brianchandotcom/liferay-portal/pull/86374

**Comment by brianchandotcom** [comment]
@brianwulbern there are a lot more merge conflicts than I would expect? And when I reverted some of the merge conflicts and reran the generator, nothing changed (which I was surprised about).

Can you rebase and resend? We have to merge right away.

**Comment by brianwulbern** [comment]
on it

**Comment by brianwulbern** [comment]
yeah, the merge conflicts pile up quickly from the scope of this.

**Comment by brianwulbern** [comment]
resent: https://github.com/brianchandotcom/liferay-portal/pull/86441

**Pull request closed without merging**
