### PR TITLE
Extract SSO from Portal Settings

### PR DESCRIPTION
**Pull request by topolik**
Hi Brian,

/cc @philipjones03 @stian-sigvartsen 

this is originally a regression bug fix for Portal Settings authentication JSPs. We changed SSO to use Settings API and therefore need to rewrite Portal Settings JSPs to use each module Configuration object. PropsValues don't work anymore :)

To avoid referencing each SSO module from portal-settings-web module we inverted the logic and inject the functionality from each SSO module into portal-settings-web.

This way Portal Settings is independent and works even if we stop OpenSSO OSGi module, for example.

---

This pull request contains 4 modules - NTLM, Facebook, OpenID, OpenSSO.

Each module commits are similar:
1, Move JSP from portal-settings-web into the respective module
2, Adapt the JSP to use Settings API and hook the JSP back into portal-settings-web as `DynamicInclude`, to be visible among the other authentication tabs
3, Using `MVCActionCommand` save the SSO JSP configuration
4, Move language keys used from JSP into the module
5, Inject language keys to be available for `PortalSettingsPortlet`, LanguageUtil/impl use always actual execution context portlet config to load the ResourceBundle

I'm sending it as one pull request because there are conflicts in portal.properties (`company.settings.form.authentication` key) and sometimes also in language files of Portal Settings.

Thank you.

---

https://issues.liferay.com/browse/LPS-59178 - NTLM
https://issues.liferay.com/browse/LPS-59180 - Facebook
https://issues.liferay.com/browse/LPS-59181 - OpenID
https://issues.liferay.com/browse/LPS-59182 - OpenSSO

### CODE REVIEW

**Comment by philipjones03** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
ci:retest

**Comment by topolik** [comment]
The test failures are unrelated.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@topolik I just talked to @philipjones03 

He's going to:

1.) create modules/portal/portal-resource-bundle which will contain a com.liferay.portal.resource.bundle.BaseResourceBundlePublisher

2.) he's going to resend me just the Facebook part based on this pull. And packages that are named "portal.settings.web.resource.bundle." he will rename to just "resource.bundle"

We got some exceptions on Windows due to the dreaded 255 path limit (exists even in Windows 7).

He will then rebase and resend to me.

Thx

**Comment by philipjones03** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
