### PR TITLE
LPS-110881 Adjust tooltip

### PR DESCRIPTION
**Pull request by rodrigocunhaa**

### CODE REVIEW

**Comment by rodrigocunhaa** [comment]
Manual forwarded from https://github.com/inacionery/liferay-portal/pull/671#issuecomment-628991118. Same as https://github.com/brianchandotcom/liferay-portal/pull/88624.

**Comment by rodrigocunhaa** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/99054c05d1...e225a7743d

**Pull request closed without merging**
