### PR TITLE
LPS-56383 Git Commit Plugins

### PR DESCRIPTION
**Pull request by epgarcia**
Hey Brian,

I'm getting random test errors with these changes, but none of them are related to Journal (I get PACL and Bootstrap ones). The only issue I actually have to fix is with the sharding configuration. I've temporarily disabled it but I'm working to have it fixed ASAP.

Could you please publish the journal-api and the journal-service libraries to the repository? Then I'll change the ivy files in the affected plugins to download them.

Thanks!

@juliocamarero

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:retest

**Comment by epgarcia** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by epgarcia** [comment]
Hey @brianchandotcom,

We still get those errors with PACL. I cannot tell if they are related or not to my changes.

@kiyoshilee maybe you can confirm if they are? 

Thanks!

**Comment by brianchandotcom** [comment]
ci:retest (I think they are.... not sure how)

**Comment by epgarcia** [comment]
Closed to resolve merge conflicts. See brianchandotcom/liferay-portal/pull/27563.

**Pull request closed without merging**
