### PR TITLE
LRCI-91 Release poshi runner 1.0.222

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRCI-91

### CODE REVIEW

**Comment by kenjiheigel** [comment]
Backports:
https://github.com/brianchandotcom/liferay-portal-ee/pull/23625 (7.1.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/23626 (7.0.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/23627 (ee-6.2.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/23628 (ee-6.2.10)
https://github.com/brianchandotcom/liferay-portal-ee/pull/23629 (ee-6.1.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/23630 (ee-6.1.30)

**Comment by kenjiheigel** [comment]
Backports: (The validation fixes are branch specific) 
https://github.com/brianchandotcom/liferay-portal-ee/pull/23631 (7.1.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/23632 (7.0.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/23633 (ee-6.2.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/23634 (ee-6.2.10)
https://github.com/brianchandotcom/liferay-portal-ee/pull/23635 (ee-6.1.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/23636 (ee-6.1.30)

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by kenjiheigel** [comment]
Thanks for merging. Not sure why this failed. Didn't know that the functional batch was part of the auto close rules? @yichenroy 

The failures are all in upstream though. 
https://testray.liferay.com/home/-/testray/runs/compare?formDate=1553226041157&testrayRunIdA=502879128&testrayRunIdB=503081082

**Pull request closed without merging**
