### PR TITLE
LPS-68497 Test .gitignore for Ant plugins if they're not in a Git repo

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
@pyoo47, can you please help me here? `ModulesStructureTest.testScanIgnoreFiles` is complaining that `modules/private/apps/spi/.gitignore` is missing, but the file [exists](https://github.com/liferay/liferay-portal-ee/blob/ee-7.0.x/modules/private/apps/spi/.gitignore) on `ee-7.0.x`. Maybe we exclude the `.gitignore` files when we merge the private modules into master?

**Comment by brianchandotcom** [comment]
@pyoo47 please help @Ithildir Thx.

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
@Ithildir The second run after my fix came back with a different error. You can see it [here](https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/32667/AXIS_VARIABLE=0,label_exp=!master/testReport/junit/com.liferay.portal.modules/ModulesStructureTest/testScanIgnoreFiles/).

**Comment by pyoo47** [comment]
ci:stop

**Pull request closed without merging**
