### PR TITLE
LPS-96802 Create read only grants independent of the aliases

### PR DESCRIPTION
**Pull request by csierra**
/cc @jpince @stian-sigvartsen

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3555b0c4cc...5d575165ca

**Comment by jpince** [comment]
@csierra there is still a related unresolved requirement error in the lpkg batch
```
    [junit] org.osgi.framework.BundleException: Could not resolve module: com.liferay.fragment.impl [585]
    [junit]   Unresolved requirement: Import-Package: com.liferay.oauth2.provider.constants; version="[1.0.0,2.0.0)"
    [junit] 
    [junit] 	at org.eclipse.osgi.container.Module.start(Module.java:444)
    [junit] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1682)
    [junit] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1662)
    [junit] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1624)
    [junit] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1555)
    [junit] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
    [junit] 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
    [junit] 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
    [junit] 17:31:06,923 ERROR [Framework Event Dispatcher: Equinox Container: baabf65a-e7d0-45ac-92cb-9b272deb3e80][Framework:108] Exiting the JVM 
    [junit] org.osgi.framework.BundleException: Could not resolve module: com.liferay.fragment.impl [585]
    [junit]   Unresolved requirement: Import-Package: com.liferay.oauth2.provider.constants; version="[1.0.0,2.0.0)"
    [junit] 
    [junit] 	at org.eclipse.osgi.container.Module.start(Module.java:444)
    [junit] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1682)
    [junit] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1662)
    [junit] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1624)
    [junit] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1555)
    [junit] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
    [junit] 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
    [junit] 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
```
@brianchiu @xbrianlee @vicnate5 not sure if this is also a race condition, since lpkg-controller passed

**Comment by csierra** [comment]
hey @brianchiu @xbrianlee, 
at first sight the code in this PR and related seems just fine. `fragment-impl` now depends on `oauth2-provider-api` and it looks like the test is trying to start the first without having installed the second. Would that make sense?

**Comment by vicnate5** [comment]
@mtambara is the lpkg-base batch loading modules differently?

**Comment by mtambara** [comment]
@vicnate5 lpkg-base only builds lpkgs that are part of collaboration, forms-and-workflow, foundation, and web-experience. No module in those suites should have dependencies on anything outside of those suites

**Comment by xbrianlee** [comment]
@brianchiu Can you have your devs look into this? Sounds like `fragment-impl` shouldn't depend on `auth2-provider-api`.

**Comment by brianchiu** [comment]
@xbrianlee @csierra @mtambara 
I've messaged my devs about this.

See: https://issues.liferay.com/browse/LPS-97048

**Pull request closed without merging**
