### PR TITLE
LPS-90078 Set default pagination delta

### PR DESCRIPTION
**Pull request by BryanEngler**
✔️ **ci:test:search - This pull contains no unique failures. 15 out of 17 jobs passed in 1 hour 18 minutes 40 seconds** https://github.com/BryanEngler/liferay-portal/pull/309#issuecomment-460888626

Author: @lipusz
Reviewer: @BryanEngler

[Bug] Search Results widget "Pagination Delta" default setting ignores search.container.page.default.delta
https://issues.liferay.com/browse/LPS-90078

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Guys.. this seems very wrong.. why are we tracking Props now? We've never had to do this before.... can't we jus call PropsUtil? Please resend.

**Comment by lipusz** [comment]
Actually, we are using PropsValues at many places in portal-search-web, so I didn't think we should make more changes.

@BryanEngler: what do you think?

**Comment by lipusz** [comment]
https://github.com/BryanEngler/liferay-portal/pull/310

**Comment by BryanEngler** [comment]
@arboliveira had requested that i inject the `Props` instead of using `PropsValues`. Ill talk to him about it

**Comment by arboliveira** [comment]
@BryanEngler please do as @brianchandotcom says. I'm filing a technical debt story to remove all usages of pre-OSGi properties, `Props`, `PropsUtil` and `PropsValues` from Search modules so we can do it later. Thanks.

**Pull request closed without merging**
