### PR TITLE
LPS-59304 Enable spa cache again and invalidate cache only when necessary

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by juliocamarero** [comment]
:+1:

**Comment by jbalsas** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c4e2f1db11...198b7660f2

**Comment by brianchandotcom** [comment]
Very nice @jbalsas

**Pull request closed without merging**
