### PR TITLE
LPS-61540 Add integration test for thread splitting with attachments

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 why did this hang? Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6d4c696cbd...c07ca81133

**Comment by brianchandotcom** [comment]
@sergiogonzalez @IstvanD please see my changes in upstream. Thx.

**Comment by pyoo47** [comment]
We've been seeing some Poshi tests hanging sporadically since yesterday but have not been able to determine the cause yet. It appears that Poshi runner is hanging in the middle of the test and then it times out. I'll let you know when we get to the bottom of this..

```
     [exec]     test.dependencies.dir.name=dependencies
     [exec]     test.name=ExportImport#ImportCorruptedFile
     [exec]     test.portal.instance=false
     [exec]     test.poshi.warnings.file.name=/opt/dev/projects/github/liferay-portal/poshi-warnings.xml
     [exec]     test.run.locally=false
     [exec]     test.skip.tear.down=true
     [exec]     testing.class.method=true
     [exec]     theme.ids=classic,controlpanel
     [exec]     timeout.explicit.wait=60
     [exec]     timeout.implicit.wait=3
     [exec]     vm.host=vm-1
     [exec] 
     [exec] 
     [exec]     ###
     [exec]     ### ExportImport#ImportCorruptedFile
     [exec]     ###
     [exec] 
     [exec] 
     [exec] com.liferay.poshi.runner.PoshiRunner > test[ExportImport#ImportCorruptedFile] STANDARD_OUT
     [exec]     Checking to see if TCat is enabled...
     [exec] 13:41:49,307 INFO  [elasticsearch[Union Jack][clusterService#updateTask][T#1]][metadata:452] [Union Jack] [20202] update_mapping [LiferayDocumentType]
Build timed out (after 120 minutes). Marking the build as aborted.
Build was aborted
Recording test results
```

**Comment by brianchandotcom** [comment]
Thx

--
Brian Chan
Chief Software Architect
Liferay, Inc.
Enterprise. Open Source. For Life.
(626) 806-1190

**Pull request closed without merging**
