### PR TITLE
LPS-63528 Convert Private Message Portlet to OSGI Module 

### PR DESCRIPTION
**Pull request by peterfellwock**

### CODE REVIEW

**Comment by peterfellwock** [comment]
@brianchandotcom both errors above are not related to private-messaging. LayoutImpl.java does show up in portal-impl\ format source.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f799092190...ed1105c44e

**Comment by brianchandotcom** [comment]
@peterfellwock can you send a follow up pull:

1.) Move PrivateMessagingUserNotificationHandler to web.notifications? Search *NotificationHandler*

2.) Can you move RoleConstants to model to match WikiPageConstants

Good job on this port.

fyi @jorgeferrer

**Comment by brianchandotcom** [comment]
@peterfellwock also, can you send me a pull to remove it from the plugins repo? Thx.

**Comment by peterfellwock** [comment]
@brianchandotcom YES!

**Pull request closed without merging**
