### PR TITLE
LPS-71804 Remove unused code

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
cc @jkappler @ealonso

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by anthony-chu** [comment]
ci:retest

**Comment by anthony-chu** [comment]
ci:retest

**Comment by anthony-chu** [comment]
ci:retest

**Comment by jpince** [comment]
ci:retest

**Comment by anthony-chu** [comment]
`CPPagetemplates#DeletePageTemplate` failure can be ignored; failing due to success message assertion when adding a portal instance.

**Comment by brianchandotcom** [comment]
@pavel-savinov can you rebase and resend? Thx.

**Pull request closed without merging**
