### PR TITLE
OAUTH2-124 Merge REST module to master (3)

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Resending brianchandotcom/liferay-portal/pull/57266 
(Missed one SF issue)

/cc @topolik @csierra

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test

**Comment by brianchandotcom** [comment]
ci:test

**Comment by brianchandotcom** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
ci:test trying one more time.. I think CI was flaky earlier...

**Comment by brianchandotcom** [comment]
@stian-sigvartsen can you resend on top of https://github.com/stian-sigvartsen/liferay-portal/pull/76

The constants in OAuth2ProviderRestEndpointConstants need to be prefixed

See how the values are all different?

```
	public static final String AUTHORIZATION_CODE_PKCE_GRANT =
		"authorization_code_pkce";

	public static final String CLIENT_REMOTE_ADDR =
		"CLIENT_REMOTE_ADDR_ADDRESS";

	public static final String CLIENT_REMOTE_HOST = "CLIENT_REMOTE_HOST";

	public static final String COMPANY_ID = "COMPANY_ID";

	public static final String FEATURE_PREFIX = "FEATURE-";

	public static final String FEATURES = "FEATURES";

	public static final String LIFERAY_OAUTH2_CLIENT_ID =
		"liferay.oauth2.client.id";

	public static final String LIFERAY_OAUTH2_ENDPOINT_PROVIDER =
		"liferay.oauth2.endpoint.provider";

	public static final String LIFERAY_OAUTH2_ENDPOINT_RESOURCE =
		"liferay.oauth2.endpoint.resource";

	public static final String TOKEN_INTROSPECTION_FEATURE =
		"token-introspection";
```

But they're not grouped in any meaningful way, so it's possible that they can conflict in the future.

So if they are statuses, prefix STATUS_*, if they are a property key, prefix with PROPERTY_KEY_*

etc.

I'm also going to look into

```
	at org.apache.axis.wsdl.fromJava.Types.writeTypeAndSubTypeForPart(Types.java:442)
     [exec] 	at org.apache.axis.wsdl.fromJava.Emitter.writePartToMessage(Emitter.java:1890)
     [exec] 	at org.apache.axis.wsdl.fromJava.Emitter.writeRequestMessage(Emitter.java:1486)
     [exec] 	at org.apache.axis.wsdl.fromJava.Emitter.writeMessages(Emitter.java:1106)
     [exec] 	at org.apache.axis.wsdl.fromJava.Emitter.writePortType(Emitter.java:1075)
     [exec] 	at org.apache.axis.wsdl.fromJava.Emitter.getWSDL(Emitter.java:484)
     [exec] 	at org.apache.axis.wsdl.fromJava.Emitter.emit(Emitter.java:331)
     [exec] 	at org.apache.axis.wsdl.fromJava.Emitter.emit(Emitter.java:430)
     [exec] 	at org.apache.axis.tools.ant.wsdl.Java2WsdlAntTask.execute(Java2WsdlAntTask.java:243)
     [exec] 	... 4 more
     [exec] Caused by: java.lang.ClassNotFoundException: javax.portlet.PortletResponse
     [exec] 	at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1374)
     [exec] 	at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1323)
     [exec] 	at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1076)
     [exec] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     [exec] 	
``` 

But that may be something generic that's broken with our wsdd right now.

**Comment by brianchandotcom** [comment]
@stian-sigvartsen the WSDD error was found in https://github.com/brianchandotcom/liferay-portal/pull/57288 as well. I fixed it in ad98893ade1bc943242592f9fd36e3c30d63fef8

**Comment by stian-sigvartsen** [comment]
@brianchandotcom thanks for resolving the WSDD error

**Pull request closed without merging**
