### PR TITLE
LPS-62643 Applying the Documents and Media lexicon icon when there's no thumbnail or preview available.

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Applying the Documents and Media lexicon icon when there's no thumbnail or preview available.

image

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @sharonchoi

**Comment by sergiogonzalez** [comment]
Hey @sharonchoi it seems that we need to update the tests because they are looking for a img tag with class document-thumbnail and that's no longer the case if it's not a image with a preview generated.
Can you take care of that?

**Comment by sharonchoi** [comment]
@sergiogonzalez ok will do.

**Comment by brianchandotcom** [comment]
@sharonchoi please resend to me. THx.

**Pull request closed without merging**
