### PR TITLE
LPS-80551 Escape elements

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@pyoo47 I've gotten a lot of these GH errors. What's going on?

**Comment by pyoo47** [comment]
@brianchandotcom I think I've fixed it.. there was a missing import statement in the beanshell. Not sure exactly why the problem didn't happen all the time..

**Comment by pyoo47** [comment]
ci:test:sf

**Pull request closed without merging**
