### PR TITLE
LPS-71281 adjust CSS to render cards tree view component correctly

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@pavel-savinov please resend

public JSONObject getLayoutsJSON()

needs to be 

public JSONObject getLayoutsJSONObject()

@hhuijser SF should have complained about this commit.

See modules/apps/web-experience/layout/layout-item-selector-web/src/main/java/com/liferay/layout/item/selector/web/internal/display/context/LayoutItemSelectorViewDisplayContext.java in this pull.

**Comment by hhuijser** [comment]
@brianchandotcom, it's only checking vars I think, I'll see if I can add method name checks as well

**Pull request closed without merging**
