### PR TITLE
LPS-67065

### PR DESCRIPTION
**Pull request by jpince**
https://issues.liferay.com/browse/LPS-67065

### CODE REVIEW

**Comment by jpince** [comment]
cc/@sharonchoi

**Comment by jpince** [comment]
@brianchandotcom Collab is going to quarantine the flaky messageboards test while they investigate. good to merge from a poshi perspective.

**Comment by jpince** [comment]
@kmaria reactivating staging tests

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d1e456bcfd...40848a2573

**Pull request closed without merging**
