### PR TITLE
LPS-97277 Fix performance when CT is disabled, later we will remove t…

### PR DESCRIPTION
**Pull request by Preston-Crary**
…he CT service wrappers so this performance issue won't be a problem when CT is enabled.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by vicnate5** [comment]
@Preston-Crary Looks like this causes a major regression https://issues.liferay.com/browse/LPS-97511

**Comment by brianchandotcom** [comment]
@vicnate5 I reverted this for now in master and 7.2.x

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/75027

**Pull request closed without merging**
