### PR TITLE
LPS-66860

### PR DESCRIPTION
**Pull request by Ithildir**
Hi!
@gamerson reviewed this, can you please publish new `gradle-template` and `gradle-plugins-workspace`?

Thank you!

cc @david-truong

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
@gamerson published for you.

@Ithildir fyi

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9388b56474...3c0fd9414e

**Comment by gamerson** [comment]
Thanks @brianchandotcom and @Ithildir for quick turnaround!

On Wed, Jun 29, 2016 at 4:53 PM, Brian Chan <notifications@github.com>
wrote:

> Closed #41131
> <https://github.com/brianchandotcom/liferay-portal/pull/41131>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/41131#event-708408596>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAkVFT19zCR8oZHXKOU0bNDJzoLYVGBjks5qQulcgaJpZM4JBgGt>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Pull request closed without merging**
