### PR TITLE
LPS-160790 Extract ContentDashboardItemSearchClassMapperTracker to Info Framework

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-160790

@jkappler

### CODE REVIEW

**Comment by ozysouza** [comment]
ci:reopen

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See [liferay-echo#7560](https://github.com/liferay-echo/liferay-portal/pull/9384)

:heavy_check_mark: ci:test:stable - 27 out of 27 jobs passed
:x: ci:test:relevant - 249 out of 287 jobs passed in 3 hours 22 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d0dee6b4f0...ef8b34ab80

**Comment by brianchandotcom** [comment]
@jkappler this is in the wrong package

```
package com.liferay.layout.content.page.editor.web.internal.util;

import com.liferay.info.search.InfoSearchClassMapperTracker;

import org.osgi.service.component.annotations.Component;
import org.osgi.service.component.annotations.Reference;

/**
 * @author Jürgen Kappler
 */
@Component(immediate = true, service = {})
public class InfoSearchClassMapperTrackerUtil {
```

Can you put it in com.liferay.layout.content.page.editor.web.internal.info.search

Same here:

```
package com.liferay.layout.taglib.internal.util;

import com.liferay.info.search.InfoSearchClassMapperTracker;

import org.osgi.service.component.annotations.Component;
import org.osgi.service.component.annotations.Reference;

/**
 * @author Jürgen Kappler
 */
@Component(immediate = true, service = {})
public class InfoSearchClassMapperTrackerUtil {
```

@jkappler bypass CI and send it to me directly. Thx.

**Pull request closed without merging**
