### PR TITLE
LRQA-58578 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LRQA-58578

### CODE REVIEW

**Comment by john-co** [comment]
ci:reopen

**Comment by john-co** [comment]
Needed to fix failing tests from Segmentation: https://issues.liferay.com/browse/LRQA-59061

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark:  

:heavy_check_mark: ci:test:stable - 19 out of 19 jobs passed
:x: ci:test:relevant - 129 out of 135 jobs passed in 3 hours 30 minutes

other test failures are not related, and will be addressed in follow up PR.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e3c9504217...3393b8a844

**Pull request closed without merging**
