### PR TITLE
LRCI-810 Fail on error for docker commands and use hostname for mysql readiness evaluation

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRCI-810

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:relevant:nocompile

**Comment by kenjiheigel** [comment]
@brianchandotcom, I fixed the 7.2.x, 7.1.x, and 7.0.x SF issues in those backport pulls. 

master SF pull: https://github.com/brianchandotcom/liferay-portal/pull/81238

Also, there's an issue with new CI and 6.2 & 6.1 SF. Will fix that tomorrow. 

Backports: 
https://github.com/brianchandotcom/liferay-portal-ee/pull/27763 (7.2.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/27764 (7.1.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/27765 (7.0.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/27759 (ee-6.2.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/27760 (ee-6.2.10)
https://github.com/brianchandotcom/liferay-portal-ee/pull/27761 (ee-6.1.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/27762 (ee-6.1.30)

**Comment by kenjiheigel** [comment]
@yichenroy, the top level bombed out. Let's take a look tomorrow.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c4c9ad18ac...4686ad1985

**Pull request closed without merging**
