### PR TITLE
LPS-59964 Remove icons from WCM apps in icon menus

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
@sergiogonzalez we have removed the icon for the permissions in the portlet option menu

**Comment by juliocamarero** [comment]
@marcellustavares we have removed the icosn for the portlet options menu in DDL

**Comment by juliocamarero** [comment]
ci:retest

**Comment by marcellustavares** [comment]
Thanks @juliocamarero

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5bc309671b...d871996c04

**Comment by juliocamarero** [comment]
@evannagagyma hopefully this doesn't break any test. This removes all the icons from the menus

**Pull request closed without merging**
