### PR TITLE
LPS-71549 SF

### PR DESCRIPTION
**Pull request by diogo-lins**
Fix this one (https://github.com/brianchandotcom/liferay-portal/pull/48024)

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 what's going on?

**Comment by jpince** [comment]
ci:retest

**Comment by pyoo47** [comment]
@brianchandotcom This failure is a race condition that happens when a checkout command issued at exactly the same time that upstream is being updated. This causes the local-git sync logic to fail to know when the checkout command is complete and it eventually times out. I'll be sending a fix for this problem soon.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/794e3dc506...98fe4c6c95

**Pull request closed without merging**
