### PR TITLE
Lps 106397 2

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@victorware is this safe to merge?

**Comment by vicnate5** [comment]
ci:close

**Comment by vicnate5** [comment]
@shuyangzhou Unit test failed here: https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/291091/AXIS_VARIABLE=1,label_exp=!master/testReport/junit/com.liferay.petra.sql.dsl.ast/SQLDSLTest/testSelectDistinctTable/

This failure is **new**, did not fail on the previous PR 
https://github.com/shuyangzhou/liferay-portal/pull/8769
https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/249296/AXIS_VARIABLE=1,label_exp=!master/testReport/com.liferay.petra.sql.dsl.ast/SQLDSLTest/testSelectDistinctTable/

CC @Preston-Crary

**Comment by Preston-Crary** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/83819/commits/7d81e81b92b68eb0c62b66d07cc64a330912c2e4 ?

**Comment by shuyangzhou** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/83868

**Pull request closed without merging**
