### PR TITLE
LPS-60249 Apply new lexicon design to Asset Categories Admin portlet

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/016c7381a1...06a4fbde53

**Comment by brianchandotcom** [comment]
@ealonso I renamed both to "bottom right" instead of "right bottom". That's how it's most frequently used in English.

**Comment by brianchandotcom** [comment]
@ealonso I updated asset-tags-admin as well.

**Pull request closed without merging**
