### PR TITLE
LPS-53183 Fix registry tests

### PR DESCRIPTION
**Pull request by csierra**
Hey @brianchandotcom @michaelhashimoto

The current SDK in master is starting an app server for these tests. This is totally unnecessary since these modules do not depend on portal. Actually they can't be run once the portal is started. 

We are using an arquillian OSGi container to run the tests. You can see that in the ivy.xml file. 

The app server is not making the tests fall (currently) but put an unnecessary extra time in the execution.

### CODE REVIEW

**Comment by csierra** [comment]
hey @brianchandotcom,

it seems it's complaining about one tests method which seems to be > 80

is that correct?

**Comment by csierra** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/da8c045239...8daf8a9bd5

**Comment by brianchandotcom** [comment]
added exclusion for that line in SF see 2b136d514d7da1a3d11d2d3dafeb408716cfbc79

Thx

**Comment by csierra** [comment]
Oh... I see... did not know about that. 

Thanks Brian.

**Pull request closed without merging**
