### PR TITLE
LPS-76420 Seems wrong but auto SF

### PR DESCRIPTION
**Pull request by matethurzo**
@brianchandotcom @hhuijser @jpince see https://github.com/brianchandotcom/liferay-portal/pull/60994/commits/4bc6e172f4cabd5dd6c17c52f8b9815fa24ec1cc

seems wrong but CI would close if not sent

71x: https://github.com/brianchandotcom/liferay-portal-ee/pull/20827

### CODE REVIEW

**Comment by jpince** [comment]
@petershin see Mate's Auto SF commit https://github.com/brianchandotcom/liferay-portal/pull/60994/commits/4bc6e172f4cabd5dd6c17c52f8b9815fa24ec1cc

**Comment by petershin** [comment]
Sent a patch to Brian: https://github.com/brianchandotcom/liferay-portal/pull/61005

**Comment by jpince** [comment]
@petershin can you please resend this pull without the unnecessary auto SF commit?

**Comment by jpince** [comment]
ci:close

**Comment by petershin** [comment]
@jpince - Resent the pull: https://github.com/brianchandotcom/liferay-portal/pull/61014

**Pull request closed without merging**
