### PR TITLE
LPS-128080 Add bundle to FreeMarkerBundleClassloader first, then upda…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…te taglib mappings to make sure resource file is found by FreeMarkerBundleClassloader

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f9f89416c1...19c1319bf8

**Comment by brianchandotcom** [comment]
@ivicac is this for you?

**Comment by ivicac** [comment]
@brianchandotcom I think yes, it is related to https://issues.liferay.com/browse/COMMERCE-5829

**Pull request closed without merging**
