### PR TITLE
LPS-102441 As a developer I want to provide configurable components which are scoped to Sites and not have to create a custom UI

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-102441](https://issues.liferay.com/browse/LPS-102441).<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @rotty3000 @JorgeFerrer

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1e02b1e10c...516e7ef0f4

**Comment by brianchandotcom** [comment]
@rotty3000 @drewbrokke this pull was super good.

@drewbrokke can you send a backport to 7.2.x?

@alee8888 can you make sure we have Poshi test coverage for this?

@jasonpince @victorware fyi I really want a net/ test for this.

**Comment by JorgeFerrer** [comment]
@brianchandotcom if this is backported it should be hidden and IMHO not considered a supported feature, because it will create confusion with the "other" Site Settings application. For 7.3, we need to work on merging the two.

**Comment by alee8888** [comment]
@patriciajeanperez can you please make sure we have test coverage for this?

**Pull request closed without merging**
