### PR TITLE
Lps 83036

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4b6df8e4de...f047c06201

**Comment by brianchandotcom** [comment]
@Preston-Crary I merged this, but something is off with the patch file.

See da962d562aa79a575d769caf1210eb5a06c2617b (auto generated), and I reverted it in f047c062011e82fdaa5dd676921368b4e44dc87d

It's as if the patch and the checked in files were different.

**Comment by brianchandotcom** [comment]
Repasting this since I forgot to push up

 @Preston-Crary I merged this, but something is off with the patch file.

See da962d562aa79a575d769caf1210eb5a06c2617b (auto generated), and I reverted it in f047c062011e82fdaa5dd676921368b4e44dc87d

It's as if the patch and the checked in files were different.

**Comment by Preston-Crary** [comment]
@brianchandotcom, yes I saw that too.  That patch file was from a different ticket and I didn't touch that file so I left the inconsistency.

**Pull request closed without merging**
