### PR TITLE
LPS-141702 Import OOTB Elements into new instance so Blueprint Editor can display them

### PR DESCRIPTION
**Pull request by arboliveira**
https://issues.liferay.com/browse/LPS-141702

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@arboliveira merged first 3 commits, hope to merge the last commit later today. Was busy with dev 24.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b6a90d65e8...94f4c0326d

**Comment by brianchandotcom** [comment]
@arboliveira see my many changes in https://github.com/brianchandotcom/liferay-portal/commits/94f4c0326d52654efbb7856867d05feae3a5f0b2

Please resend as an integration test.

I prefer unit tests because they are fast, but ONLY when the unit test is simple and it does not make the actual implementation  more complicated.

When the unit test has too many mocks, or the unit test requires the actual implementation to be confusing/complicated, then go for an integration test (even though they are slower to run).

I prefer simplicity over speed of tests.

@peerkar fyi

**Pull request closed without merging**
