### PR TITLE
LRQA-33826 Gradle tasks are not showing output when setting outputproperty

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRQA-33826

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:reopen

**Comment by pyoo47** [comment]
These failures were caused by a bad slave in CI that was picking up jobs and failing them immediately.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f12ae86515...54fc28417e

**Comment by brianchandotcom** [comment]
@michaelhashimoto see 8d819479c315163c18f5013fdf62b97acf06bfe5 thx

**Pull request closed without merging**
