### PR TITLE
LPS-75058 SF

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 how come there are no results? Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/de7e83163e...c4e31b162b

**Comment by pyoo47** [comment]
@brianchandotcom Looks like the build froze as it was compiling the results.. It could be a connection issue between the top level build and one of the downstream builds.

**Pull request closed without merging**
