### PR TITLE
LPS-195875 Test Scenarios Coverage | Backend

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://liferay.atlassian.net/browse/LPS-195875

@Mikellorza

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/13716

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e461fcc086...26bd26a832

**Comment by brianchandotcom** [comment]
@Mikellorza very nice!

**Pull request closed without merging**
