### PR TITLE
LPS-65598 Loan Calculator calculate incorrect values if years value i…

### PR DESCRIPTION
**Pull request by rahulmantri**
Fixed and committed the code (backport request for 6.2.x)

Test Env :
Application server – Tomcat 7
DB Server - MySQL 5.1
Browser – Chrome/Mozilla/IE

Note : @brianchandotcom - I a unable to find @Zoltán Takacs on github.

### CODE REVIEW

**Comment by jpince** [comment]
@rahulmantri thank you for revising this commit based on my feedback. please send this backport request to @zoltantakacs https://github.com/zoltantakacs/liferay-portal

**Comment by rahulmantri** [comment]
Hi Jason,

This has already been backported to 6.2.x version. However I couldn’t find Zoltan to send this backport to on Github and hence sent it to @brianchandotcom

Regards,
Rahul

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@ZoltanTakacs can you backport this?

Thx.

**Comment by brianchandotcom** [comment]
Nvm.. this is the backport

**Comment by brianchandotcom** [comment]
@ZoltanTakacs  I backported this for you... didn't realize this was the backport

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by ZoltanTakacs** [comment]
Thank you!

**Pull request closed without merging**
