### PR TITLE
LPS-56429 Wiki portlet is missing from the Page Templates

### PR DESCRIPTION
**Pull request by izaera**
/CC @jkappler

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
Thanks @michaelhashimoto , now it looks "normally broken" !

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@izaera Shuyang told me this pull has a real test failure (and I ran the pull many times, breaks for this pull even though it's green on upstream).

**Comment by jkappler** [comment]
@brianchandotcom will look into it, thx Brian

**Pull request closed without merging**
