### PR TITLE
LRQA-47104 | master

### PR DESCRIPTION
**Pull request by jpince**
https://issues.liferay.com/browse/LRQA-47104

This is part 1. I'm also looking into the other tests still listed in

### CODE REVIEW

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by jpince** [comment]
@brianwulbern @richiezhao @yunlinsun this may be good to backport to expose hidden tests, see https://issues.liferay.com/browse/LRQA-47104 and https://issues.liferay.com/browse/LPS-91419

**Comment by brianwulbern** [comment]
@jpince thanks for the heads up.  I'm not exactly sure whether we should blind backport these, or backport the logic.  If the former, we can go ahead with it (I just verified that [these folders](https://github.com/brianchandotcom/liferay-portal/pull/68910/commits/c8d808f0df77757fa590513e3c3b95edfff7b4f5) are removed on 7.1 as well) .  If the latter, I'm not sure how to find cases unique to 7.1 and 7.0.

**Comment by brianwulbern** [comment]
@jpince the other commit looks safe.  Went ahead and sent to BChan here: https://github.com/brianchandotcom/liferay-portal-ee/pull/23411

**Pull request closed without merging**
