### PR TITLE
LPD-36219 Explicit break down Locale into property map to avoid trigg…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…ering the heavy jodd.json.BeanSerializer

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@tinatian @vicnate5 please backport for LXC, thanks!

@victorhcunha please run a check for login case, thanks!

**Comment by victorhcunha** [comment]
Hi @shuyangzhou !
Here are the results for login test case:

Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | DB CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | --
Master Baseline | bfddf4d | 13107 | - | 281 | 1,1,1 | 95,95,94
PR | - | 12641 | -3.555352102 | 282 | 1,1,2 | 93,93,94

More details you can see in our [spreadsheet](https://docs.google.com/spreadsheets/d/1M6VK8GtY9kkv1EwhGW7vwrEENSzyT7zKz-wOh11ZHBo/edit?gid=114913795#gid=114913795).

**Comment by shuyangzhou** [comment]
@victorhcunha this is not expected, the change is completely avoiding the jodd java bean serializer, it should not cause regression. Please double check for noise.

**Comment by victorhcunha** [comment]
Sure! A new round is already in progress.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e08d8ed42c...ce66d83d96

**Comment by brianchandotcom** [comment]
@shuyangzhou just ce66d83d96684f48662b63de75c42578ef7b38b8

**Comment by victorhcunha** [comment]
Here are the new results for login test case:

Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | DB CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | --
Master Baseline | 83d6b8f | 13017 | - | 277 | 1,1,1 | 95,96,96
PR | - | 13466 | 3.449335484 | 271 | 1,3,1 | 94,94,95

Also see: https://github.com/brianchandotcom/liferay-portal/pull/154138

**Comment by shuyangzhou** [comment]
Thanks @victorhcunha !

**Pull request closed without merging**
