### PR TITLE
LRIS-25643

### PR DESCRIPTION
**Pull request by lionah**

### CODE REVIEW

**Comment by lionah** [comment]
@jpince real failure?

**Comment by lionah** [comment]
ci:reopen

**Comment by jpince** [comment]
@lionah @suprithas yes, please resolve
```
     [exec] Could not resolve all dependencies for configuration ':apps:foundation:portal-security:portal-security-wedeploy-auth-test:testIntegrationCompileClasspath'.
     [exec] > Could not find com.liferay:com.liferay.portal.security.wedeploy.auth.api:1.0.0.
     [exec]   Searched in the following locations:
     [exec]       file:/opt/dev/projects/github/liferay-portal/.m2/com/liferay/com.liferay.portal.security.wedeploy.auth.api/1.0.0/com.liferay.portal.security.wedeploy.auth.api-1.0.0.pom
     [exec]       file:/opt/dev/projects/github/liferay-portal/.m2/com/liferay/com.liferay.portal.security.wedeploy.auth.api/1.0.0/com.liferay.portal.security.wedeploy.auth.api-1.0.0.jar
     [exec]       http://repository.liferay.com/nexus/content/groups/public/com/liferay/com.liferay.portal.security.wedeploy.auth.api/1.0.0/com.liferay.portal.security.wedeploy.auth.api-1.0.0.pom
     [exec]       http://repository.liferay.com/nexus/content/groups/public/com/liferay/com.liferay.portal.security.wedeploy.auth.api/1.0.0/com.liferay.portal.security.wedeploy.auth.api-1.0.0.jar
     [exec]       http://repository.liferay.com/nexus/service/local/repo_groups/private/content/com/liferay/com.liferay.portal.security.wedeploy.auth.api/1.0.0/com.liferay.portal.security.wedeploy.auth.api-1.0.0.pom
     [exec]       http://repository.liferay.com/nexus/service/local/repo_groups/private/content/com/liferay/com.liferay.portal.security.wedeploy.auth.api/1.0.0/com.liferay.portal.security.wedeploy.auth.api-1.0.0.jar
     [exec]   Required by:
     [exec]       project :apps:foundation:portal-security:portal-security-wedeploy-auth-test
     [exec] > Could not find com.liferay:com.liferay.portal.security.wedeploy.auth.service:1.0.0.
     [exec]   Searched in the following locations:
     [exec]       file:/opt/dev/projects/github/liferay-portal/.m2/com/liferay/com.liferay.portal.security.wedeploy.auth.service/1.0.0/com.liferay.portal.security.wedeploy.auth.service-1.0.0.pom
     [exec]       file:/opt/dev/projects/github/liferay-portal/.m2/com/liferay/com.liferay.portal.security.wedeploy.auth.service/1.0.0/com.liferay.portal.security.wedeploy.auth.service-1.0.0.jar
     [exec]       http://repository.liferay.com/nexus/content/groups/public/com/liferay/com.liferay.portal.security.wedeploy.auth.service/1.0.0/com.liferay.portal.security.wedeploy.auth.service-1.0.0.pom
     [exec]       http://repository.liferay.com/nexus/content/groups/public/com/liferay/com.liferay.portal.security.wedeploy.auth.service/1.0.0/com.liferay.portal.security.wedeploy.auth.service-1.0.0.jar
     [exec]       http://repository.liferay.com/nexus/service/local/repo_groups/private/content/com/liferay/com.liferay.portal.security.wedeploy.auth.service/1.0.0/com.liferay.portal.security.wedeploy.auth.service-1.0.0.pom
     [exec]       http://repository.liferay.com/nexus/service/local/repo_groups/private/content/com/liferay/com.liferay.portal.security.wedeploy.auth.service/1.0.0/com.liferay.portal.security.wedeploy.auth.service-1.0.0.jar
     [exec]   Required by:
     [exec]       project :apps:foundation:portal-security:portal-security-wedeploy-auth-test
```

**Comment by jpince** [comment]
ci:close

**Pull request closed without merging**
