### PR TITLE
master-vw-414

### PR DESCRIPTION
**Pull request by vicnate5**
@brandizzi @brunobasto @achaparro @ctampoya

### CODE REVIEW

**Comment by vicnate5** [comment]
Sent to 7.0.x
https://github.com/brianchandotcom/liferay-portal/pull/41120

**Comment by vicnate5** [comment]
@achaparro I backported this to 7.0.x. The LPS commits do not backport cleanly into ee-6.2.x. Would you be able to take care of this?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/07f1e8c938...dfbecb96df

**Comment by achaparro** [comment]
Hey @vicnate5,

Ok, I will take care of the backport to ee-6.2.x, do I need to backport the poshi tests too?

Thanks.

**Comment by vicnate5** [comment]
@achaparro This change will cause test failures on the ee.6.2.x if we do not backport the test fixes as well. Unfortunately the test fixes will not backport cleanly with the ee-6.2.x test files right now. 

Once you backport the bug fix to your ee-6.2.x branch, can you send the branch to @brianwulbern? He will take care of backporting the test fixes and can then send everything together.

Thanks for your help!

**Comment by brianwulbern** [comment]
Thanks @vicnate5 and @achaparro !

**Pull request closed without merging**
