### PR TITLE
LPS-168341 Add collection variations popover in the page editor

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-168341

@lfbesada @sandrodw3

### CODE REVIEW

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See [liferay-echo#7560](https://github.com/liferay-echo/liferay-portal/pull/10400)

:heavy_check_mark: ci:test:stable - 28 out of 28 jobs passed
:x: ci:test:relevant - 234 out of 242 jobs passed in 2 hours 30 minutes

**Comment by ozysouza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cc416900e8...deaaa94a3b

**Comment by brianchandotcom** [comment]
@lfbesada just deaaa94a3bfd1bb6a8645a1fba0619a1d47af709

**Pull request closed without merging**
