### PR TITLE
LPS-88848 temp

### PR DESCRIPTION
**Pull request by giros**
@brianchandotcom this is temporary until https://issues.liferay.com/browse/LPS-89159 gets resolved. 

(https://issues.liferay.com/browse/LPS-88848 brought this to surface.)

cc @jpince @matethurzo

### CODE REVIEW

**Comment by jpince** [comment]
@shuyangzhou please see https://issues.liferay.com/browse/LPS-89159

**Comment by shuyangzhou** [comment]
That's expected and correct behavior, we won't change anything for it. Service wrapper is injected under the aop proxy, from OSGi point of view, it is a whole which can not be separated. If the test needs the inner one, it needs to unwrap it by itself. But that's also mean ripping off aop proxy which can hardly be correct in normal cases.

**Comment by jpince** [comment]
@giros please also note that a lot of integration tests are now throwing this error:
`ERROR [RMI TCP Connection(28)-127.0.0.1][CTManagerImpl:157] Unable to find user 0`
You can see this error in your previous pull https://github.com/brianchandotcom/liferay-portal/pull/66679#issuecomment-454082924 under `PortalLogAssertorTest.testScanXMLLog`, so I'm assuming LPS-88848 also caused these issues.
See also, [examples in upstream acceptance](https://test-1-23.liferay.com/job/test-portal-acceptance-upstream-batch(master)/22466/AXIS_VARIABLE=10,label_exp=!master/consoleFull)

cc/ @matethurzo @brianchiu @kyle-miho

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by jpince** [comment]
fyi @ealonso @jkappler @brianchiu @kyle-miho

**Comment by giros** [comment]
@jpince I'm working to resolve "Unable to find user 0" log messages, it's because some tests doesn't set up a user for their runtime, but change tracking requires one.

**Comment by joshchong** [comment]
Hey, @giros do you happen to have a ticket for the "Unable to find user 0" errors? The errors are occuring in some of our test jobs and we would like a way to track its progress. Thanks!

**Comment by jpince** [comment]
@joshchong I think he's continuing to work on it under LPS-88848 see https://github.com/giros/liferay-portal/pull/77, looks like it resolved the issue (just took 5 hours to run ci:test :disappointed:)

**Comment by joshchong** [comment]
Oh awesome thanks @jpince!

**Pull request closed without merging**
