### PR TITLE
LPS-73185 Fire events only when a video is playing.

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:reopen

**Comment by ambrinchaudhary** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@ealonso the DLApp test breaks very often (is flaky)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/374ddf6683...87b7e1f9a6

**Comment by brianchandotcom** [comment]
@ambrinchaudhary please see 87b7e1f9a67913a5c0bc0bb5eae4195cd0dab457

**Comment by ealonso** [comment]
Hey @brianchandotcom, 
Thanks for letting me know, I'm going to check it with @sergiogonzalez

**Pull request closed without merging**
