### PR TITLE
LPS-97020 Temporary uploaded files do not have the classNameId/classPK information, this information will be updated and reindexed once the referenced entry is saved

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by lipusz** [comment]
@arboliveira @BryanEngler fyi

**Comment by lipusz** [comment]
ci:test:search

**Comment by joshchong** [comment]
Regarding the DLFileEntryAttachmentSearchTest.testSearchIncludeAttachment failure, this is a known flaky test that is going to be resolved in [LPS-96399](https://issues.liferay.com/browse/LPS-96399).

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
