### PR TITLE
LPS-83008

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
Hi @hhuijser,

A few SF errors are shown, however they don't seem to be related, do you know why we are getting these errors?

Thanks.

**Comment by hhuijser** [comment]
@achaparro, whenever a pull touches files in the SF module, Jenkins does a SF test on all files, so it catches these SF violations on these unrelated files

**Comment by hhuijser** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
