### PR TITLE
LPS-46570 Lang keys

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b177c34356...cdf897ff74

**Comment by brianchandotcom** [comment]
@marcellustavares can you send a follow up pull

1.) Sort:

```
	<model-resource>
		<composite-model-name>
			<model-name>com.liferay.portlet.documentlibrary.model.DLFileEntryMetadata</model-name>
			<model-name>com.liferay.dynamic.data.mapping.model.DDMStructure</model-name>
		</composite-model-name>
```

Same for

```
	<model-resource>
		<composite-model-name>
			<model-name>com.liferay.journal.model.JournalArticle</model-name>
			<model-name>com.liferay.dynamic.data.mapping.model.DDMStructure</model-name>
		</composite-model-name>
```

and

```
	<model-resource>
		<composite-model-name>
			<model-name>com.liferay.journal.model.JournalArticle</model-name>
			<model-name>com.liferay.dynamic.data.mapping.model.DDMTemplate</model-name>
		</composite-model-name>
```

2.) Should *PermissionSupport go inside service.permission or *permission vs. util?

3.) Is the pattern checkAddStruturePermission new? I've never seen a checkXxx before? Or is that existing?

**Pull request closed without merging**
