### PR TITLE
LRQA-37340 Copy jenkins job config regen beanshell code into Java class

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-37340

Resend of https://github.com/brianchandotcom/liferay-portal/pull/56296

I've added a lot more cleanup of the code in order to simplify the renaming of the various methods and member attributes.

This pull request represents a first step towards moving the jenkins job config file regeneration logic into java. This pull copies the beanshell code into a java class and does some cleanup / reorganization. More drastic architectural changes are to follow in subsequent pull requests before we actually make the changeover so we can create job configurations by assembling config xml snippets.

CC: @cesar-polanco

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Please resend on top of https://github.com/pyoo47/liferay-portal/pull/571

Naming is still very inconsistent.

We have 

String propertyName = _getPropertyFromRegex(

and

_getGlobalPropertyValue(String property)

What is the difference between

String property, String propertyName, and PropertyValue? All 3 are used.

Why doesn't

public Map<String, String> generateJobConfig()

end with *Map like _getEnvironmentSlavesPropertiesMap() ?

Why doesn't

_generateJobListViewByParent(

end with *Element like 

Dom4JUtil.getNewElement

I caught incosistencies from the very beginning. Please see my changes, and rename vars and method names for consistency. 

Thx.

**Comment by brianchandotcom** [comment]
@cesar-polanco fyi

**Comment by pyoo47** [comment]
Resent https://github.com/brianchandotcom/liferay-portal/pull/56405

**Pull request closed without merging**
