### PR TITLE
LPS-91800 Build Lang

### PR DESCRIPTION
**Pull request by epgarcia**
Hi @brianchandotcom,

Please notice that we use "referrer" (the correct spelling), although the HTTP header is "referer" (it was historically misspelled).

Thanks

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/52614cc3ef...b86d1b601f

**Comment by brianchandotcom** [comment]
@epgarcia minor change in b86d1b601f0ec03c0b401940c9be6acca644d30a

yeah, that referrer and referer is so annoying! Can't believe they misspelled it in the spec....

**Pull request closed without merging**
