### PR TITLE
LPS-82000  A help reference link for public render parameter of portl…

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hi Sergio, it looks like configuration portlet is used for all portlets, not only for Blogs, but I don't know who's the owner and tested against blogs, so let me send this PR to you. Please let me know if you know appropriate person to send this PR to!

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @ealonso

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@yasuflatland-lf @sergiogonzalez see c0f897f029da310dd9efac2a8ab569534d76ec97

**Pull request closed without merging**
