### PR TITLE
LPS-156454 Fix broken test

### PR DESCRIPTION
**Pull request by seltong**

### CODE REVIEW

**Comment by seltong** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/269393859f...e0dff71276

**Comment by brianchandotcom** [comment]
@seltong I made some minor SF changes in my origin

Can you also modify ObjectFieldLocalServiceTest and add test coverage for _validateState and _validateDefaultValue

Thx

**Comment by seltong** [comment]
Yeah, I will create the tests to cover these scenarios in another task. I will send as soon as possible

Thx

**Pull request closed without merging**
