### PR TITLE
LRQA-60329 | master

### PR DESCRIPTION
**Pull request by vicnate5**
https://issues.liferay.com/browse/LRQA-60329

Backports
https://github.com/brianchandotcom/liferay-portal-ee/pull/31116
https://github.com/brianchandotcom/liferay-portal-ee/pull/31115
https://github.com/brianchandotcom/liferay-portal-ee/pull/31114

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:reopen

**Comment by vicnate5** [comment]
@pyoo47 This significantly increases log output for 1 specific poshi test. ([Example from 7.0.x](https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(7.0.x)/13556/AXIS_VARIABLE=0,label_exp=!master/consoleText)). If this becomes an issue, let me know. The test also only runs about 15 times per day per branch.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9b078daceb...dd39cdeffc

**Comment by brianchandotcom** [comment]
Thx @vicnate5 

@koor4356 please see changes by @vicnate5

**Pull request closed without merging**
