### PR TITLE
Revert LPS-90971 | master

### PR DESCRIPTION
**Pull request by vicnate5**
Confirmed with @Preston-Crary this ticket causes startup error at head (https://issues.liferay.com/browse/LPS-93625). This is blocking our integration tests. @matethurzo reverting to unblock other teams.

CC @jpince

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by brianchandotcom** [comment]
@matethurzo please resend.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0211340e61...1a6f067119

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by matethurzo** [comment]
@vicnate5 I don't see how rolling this back helped... The relevant suite has a compile error and the CI was literally down for days. That's not blocking the teams? @brianchandotcom

**Comment by vicnate5** [comment]
@matethurzo the compile error showing on this pull was fixed at head and merged in less than 30 mins from when it was introduced. CI was up and modules-integration-mysql57-jdk8 was failing on every PR during the US working day.

**Pull request closed without merging**
