### PR TITLE
Lps 75944

### PR DESCRIPTION
**Pull request by shuyangzhou**
@brianchandotcom this one can not be backported.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3b093228fc...6b90082d32

**Comment by brianchandotcom** [comment]
@Preston-Crary not removing from whitelist since it can't be backported..

@shuyangzhou why can't it be backported? It's just keys no?

**Comment by shuyangzhou** [comment]
@brianchandotcom 7.0.x is very much different from master on this module. It misses multiple backports. And I think the original developers who made those changes on purposely not did the backport.

**Comment by Preston-Crary** [comment]
@brianchandotcom see efcb57f.

**Pull request closed without merging**
