### PR TITLE
LPS-53404 Naming convention

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@michaelhashimoto @kiyoshilee Do you know why there are no test results? I tried retesting it already. Thx.

**Comment by kiyoshilee** [comment]
ci:retest

**Comment by kiyoshilee** [comment]
@brianchandotcom This is behaving in the same manner as https://github.com/brianchandotcom/liferay-portal/pull/24077#issuecomment-74582378. I'm not seeing the pull request triggering a job on the cohort at all.

**Comment by kiyoshilee** [comment]
@epgarcia  I believe you will need to publicly set on your profile that you belong to the Liferay organization. This was from Brian's email earlier:

We need everyone who wishes to have their pull requests tested by the CI server to publicly put on their GitHub profile that they belong to the Liferay org.

If you don't, then when you send a pull, the CI server will assume it's malicious and not test the pull. We have to use this public info so that our CI servers run with an unprivileged account.

For steps in how to do this please see this <a href="https://help.github.com/articles/publicizing-or-concealing-organization-membership/">link</a>.

After you have finished doing this please add a comment with ci:retest in order to retest this pull request.

**Comment by epgarcia** [comment]
ci:retest

**Comment by epgarcia** [comment]
Hi @kiyoshilee,

Sorry, recently I've been working with repositories other than liferay-portal, so I kind of procrastinated this. It seems it works now, but I have to rebase it. 

Thanks for your help and sorry for the inconvenience!

**Pull request closed without merging**
