### PR TITLE
LPS-99534 Enable css override

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Oh wow!! very nice.

**Comment by gamerson** [comment]
hey @mtambara   Can you give me an example of how this will work?  so show me the original request (and locadtion of the css file on the filesystem) and then how it looks once it is in the work folder?  so I know the relative path requirements?  I'll need that info for the tooling side.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ba2e7a6a0f...fc4eb93f85

**Comment by brianchandotcom** [comment]
@mtambara I noticed that most of our files are *.scss and a few are *.css (I suppose you're going to add scss next?)

Can you also backport (along with my changes) to 7.1.x and 7.0.x?

**Pull request closed without merging**
