### PR TITLE
Lps 60309

### PR DESCRIPTION
**Pull request by shuyangzhou**
@cgoncas this is the arquillian junit integration @ClassRule support you requested for, sorry for the long delay, I had it partially done quite a while ago, but I got distracted for other stuff lately, so just got it done now. You can try it out or just look at the tests in this pull to see how it works.

@brianchandotcom please publish the arquillian-extension-junit-bridge module, I think we should release it. We have tons of usage referring the current snapshot version now, once you publish it, I will update all the references.

Talking about releasing, @cgoncas and @csierra, have you guys released the liferay arquillian integration modules on your side? I was asking it in this pull https://github.com/brianchandotcom/liferay-portal/pull/31139 , please let me know if you have them released already, we need to update the usage in master.

Thanks

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@Ithildir we got a hit on the gradle build hanging with proper thread dump, see https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=4,label_exp=!master/3622//console, I paste the main thread here:
```
     [exec] "main" prio=10 tid=0xb6507800 nid=0x185 waiting on condition [0xb6899000]
     [exec]    java.lang.Thread.State: WAITING (parking)
     [exec] 	at sun.misc.Unsafe.park(Native Method)
     [exec] 	- parking to wait for  <0x3585f6a8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
     [exec] 	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
     [exec] 	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
     [exec] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.getTaskToExecute(DefaultTaskExecutionPlan.java:488)
     [exec] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:46)
     [exec] 	at org.gradle.execution.taskgraph.ParallelTaskPlanExecutor.process(ParallelTaskPlanExecutor.java:47)
     [exec] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
     [exec] 	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
     [exec] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
     [exec] 	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
     [exec] 	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
     [exec] 	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
     [exec] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
     [exec] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
     [exec] 	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
     [exec] 	at org.gradle.internal.Factories$1.create(Factories.java:22)
     [exec] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
     [exec] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
     [exec] 	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
     [exec] 	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
     [exec] 	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
     [exec] 	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
     [exec] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
     [exec] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
     [exec] 	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
     [exec] 	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
     [exec] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
     [exec] 	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
     [exec] 	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
     [exec] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
     [exec] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
     [exec] 	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
     [exec] 	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
     [exec] 	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
     [exec] 	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
     [exec] 	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
     [exec] 	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
     [exec] 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
     [exec] 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
     [exec] 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
     [exec] 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
     [exec] 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
     [exec] 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
     [exec] 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
     [exec] 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
     [exec] 	at org.gradle.launcher.Main.doAction(Main.java:33)
     [exec] 	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:606)
     [exec] 	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
     [exec] 	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
     [exec] 	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:606)
     [exec] 	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
     [exec] 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
     [exec] 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
hmm, we got another sybase issue on cloud-10-0-16-186 :
```
     [exec]      [echo] (1 row affected)
     [exec]      [echo] Resulting configuration value and memory use have not changed from previous
     [exec]      [echo] values: new configuration value datarows, previous value datarows.
     [exec]      [echo] (return status = 0)
     [exec]      [echo] Msg 1816, Level 16, State 1:
     [exec]      [echo] Server 'lportal', Line 1:
     [exec]      [echo] CREATE or ALTER DATABASE failed because the device 'master' has no space
     [exec]      [echo] available either for log or for data.
     [exec]      [echo] Msg 17421, Level 16, State 1:
     [exec]      [echo] Server 'lportal', Procedure 'sp_dboption', Line 379:
     [exec]      [echo] No such database -- run sp_helpdb to list databases.
     [exec]      [echo] (return status = 1)
     [exec]      [echo] Msg 17421, Level 16, State 1:
     [exec]      [echo] Server 'lportal', Procedure 'sp_dboption', Line 379:
     [exec]      [echo] No such database -- run sp_helpdb to list databases.
     [exec]      [echo] (return status = 1)
     [exec]    [delete] Deleting: /opt/dev/projects/github/liferay-portal/create-header.sql
```

Seems we are really running out of space, I will have @mtambara take a closer look tomorrow. But this has nothing to do with this pull.

**Comment by cgoncas** [comment]
Hey @shuyangzhou ,

We are still working in the new release, we need to add some new features, and test that everything works propertly. It is going to take a while.

Thanks!!!!

**Comment by shuyangzhou** [comment]
@cgoncas can you make a release just with the current code? It does not have to a stable release, you can call it alpha, beta or anything you prefer, even a time stamp will do it. We just need a fixed point, to avoid the floating snapshot version. Once you release the stable version, we can just bump up the version info to point to it.

**Comment by cgoncas** [comment]
Hey @shuyangzhou ,

   Yeah, we are working on the Alpha2 release, we only need to be sure that everything is working fine, so all the people outside and inside Liferay want to use it can do it.

   We need to know that everything works fine, we are working on that. And we hope to make the release really soon. We will notify you. Only wait a little bit more, please :(. Sorry for any inconvenience.

Thanks!!!!

**Comment by shuyangzhou** [comment]
Ok, that's fine. But it really does not have to this much trouble, we just need a fixed version over the floating snapshot. But since you are going to do the stable release soon, we can wait.

**Pull request closed without merging**
