### PR TITLE
LPS-105231 last page in graphql

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/58424ee3f5...630272eb94

**Comment by brianchandotcom** [comment]
@nhpatt you commited with LPS-105321 instead of LPS-105231

I fixed it for you.

**Comment by brianchandotcom** [comment]
@nhpatt In general, always cut and paste to avoid errors like this or else it could have very much confused support.

**Comment by nhpatt** [comment]
Thanks!

**Pull request closed without merging**
