### PR TITLE
LPS-93754 Make internal methods to be private

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/69cd4f3d96...7915c32414

**Comment by brianchandotcom** [comment]
@brunofarache all the pulls from Brazil are improving significantly. Keep up the good work with the peer reviews!

**Pull request closed without merging**
