### PR TITLE
LPS-70926 Move the resetAllPortlets call to the App context.

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0a160da96f...69d66fd7ad

**Comment by brianchandotcom** [comment]
@brunobasto see 69d66fd7addf87a0111e3155611432afd6a62025

**Comment by brunobasto** [comment]
Makes sense, @brianchandotcom! Thx!

**Pull request closed without merging**
