### PR TITLE
LPS-103420 structured content link

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by nhpatt** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/59710e2856...43c9bbc5f3

**Comment by brianchandotcom** [comment]
@nhpatt I backported this to 7.2 / 7.1 and added baseline fixes

**Comment by nhpatt** [comment]
Thanks! :)

**Pull request closed without merging**
