### PR TITLE
LPS-81098

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-81098.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/945a7a1eb7...ffb2cb73af

**Comment by brianchandotcom** [comment]
@jonmak08 this was closed because of an SF error.. click on

```
x ci:test:sf - 0 out of 1 jobs passed in 3 minutes 9 seconds 518 ms

Click here for more details.
```

above..

See ffb2cb73afc402c1aa8fd84a73ef4b3cb40ff213

**Comment by jonmak08** [comment]
Oh my fault @brianchandotcom.  I did not look carefully at the error, I just reopened it since I saw it was closed.

**Pull request closed without merging**
