### PR TITLE
LPS-57379 Renaming Settings API to Configuration API

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
@brianchandotcom, since the interface was renamed from SettingsIdMapping to ConfigurationPidMapping I changed all the classes that implemented it, and moved everything to the configuration package (instead of settings package). Also, I noticed that sometimes the classes where placed in the settings package and not settings.internal package, so I standardize all of that too (in the configuration.internal package)

**Comment by jkappler** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@jkappler I've had a tough time merging this in because I was afraid it'd mess up other ppl's pulls. I should be able to merge it in soon, since my major pulls are almost done now. Regardless of whether this pull passes, can you resend it to me for tomorrow (and apply any other new ones you need to modify based on today's pulls)

Thx @jkappler

**Comment by jkappler** [comment]
will rebase and resend

**Pull request closed without merging**
