### PR TITLE
LPS-75887 Fix compile error

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by jpince** [comment]
@ealonso PMD failure :(
`EditSiteNavigationMenuItemParentMVCActionCommand.java:66:	Avoid unused local variables such as 'serviceContext'.]`
all of the other failures look unrelated

**Comment by jpince** [comment]
ci:close

**Comment by ealonso** [comment]
Hey @jpince,

Thanks you very much for letting me know!!!

**Pull request closed without merging**
