### PR TITLE
LPS-163433 Unnecessary calls to JournalArticle.getContent, when we really need DDMFormValues objects

### PR DESCRIPTION
**Pull request by david-gutierrez-mesa**
https://issues.liferay.com/browse/LPS-163433

### CODE REVIEW

**Comment by david-gutierrez-mesa** [comment]
Send manually since [tests failing ](https://github.com/liferay-echo/liferay-portal/pull/9725#issuecomment-1257195112)are unrelated to PR:

✔️ ci:test:stable - 28 out of 28 jobs passed
❌ ci:test:relevant - 226 out of 241 jobs passed in 1 hour 35 minutes

SF here:
https://github.com/liferay-echo/liferay-portal/pull/9725#issuecomment-1257178979

**Comment by david-gutierrez-mesa** [comment]
cc @jorgediaz-lr @ealonso

**Comment by david-gutierrez-mesa** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e145642ed9...e4dae8fb16

**Comment by brianchandotcom** [comment]
@jorgediaz-lr just 42ce1ac591096d63395f912a320750557918b9d6

**Pull request closed without merging**
