### PR TITLE
LPS-71164

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@pyoo47 why did this flake once?

BuildTest.testGetGitHubMessage

**Comment by pyoo47** [comment]
@brianchandotcom It wasn't a flake. It was a problem that came up because the github comment that it was trying to compare to was deleted (Hashi was cleaning up his pull) I modified the test data so it will look at a different GitHub comment and marked it so Hashi knows not to delete it in the future.

**Pull request closed without merging**
