### PR TITLE
LPS-97429 SF

### PR DESCRIPTION
**Pull request by p2kmgcl**
Follow up from https://github.com/brianchandotcom/liferay-portal/pull/75474

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/556aa2178c...2cecb2c5a2

**Comment by brianchandotcom** [comment]
@jbalsas @wincent please automate, thx.

**Comment by wincent** [comment]
@brianchandotcom: https://issues.liferay.com/browse/LPS-98032 is the ticket for .soy linting. The linting that we had historically for .soy was pretty crude and didn't support param re-ordering. In terms of prioritization, we expect to see less .soy and more React over time, so we'll probably address other lint-related things before getting to this one.

**Pull request closed without merging**
