### PR TITLE
LPS-70712

### PR DESCRIPTION
**Pull request by matethurzo**
@brianchandotcom I renamed the method as you asked, but to something else what I thought describes the purpose more. The reason I wanted this longer naming is to avoid confusion with addClassedModel since it serves a different purpose.

These new methods in PDC are for single asset publication, we are registering them in the PDC to later on using in the ExportImportActionableDynamicQueries

### CODE REVIEW

**Comment by matethurzo** [comment]
the failure is unrelated

**Comment by matethurzo** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2e2c896b98...0cdb677d5c

**Comment by brianchandotcom** [comment]
Thx @matethurzo I'm fine with this longer name. I just wanted to avoid the "Entity" vs. "Model" confusion.

See my minor changes in upstream. Thx.

**Pull request closed without merging**
