### PR TITLE
LPS-67685 fix column length

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7f40032e31...ae8840e60d

**Comment by brianchandotcom** [comment]
@jkappler @juliocamarero please see my changes in upstream. Thx.

**Comment by juliocamarero** [comment]
Thanks @brianchandotcom! Wasn't there a rule about using StringBundler when we had to concatenate more than 3 strings?

**Pull request closed without merging**
