### PR TITLE
COMMERCE-7574 - refactor, substitute enum with Constants class #113244

### PR DESCRIPTION
**Pull request by matijapetanjek**

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:reopen

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@matijapetanjek I ended up going with https://github.com/brianchandotcom/liferay-portal/pull/113244 because it is nice to spell it out like that.

See my simplification in c2041e1559b27317fe82e250d35f0902b4c1b3c6

**Pull request closed without merging**
