### PR TITLE
LPS-64014 Include model

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @adolfopa @migue

**Comment by sergiogonzalez** [comment]
cc/ @juliocamarero

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4e205b1010...45a15e149b

**Comment by brianchandotcom** [comment]
@adolfopa what about:

import com.liferay.message.boards.kernel.model.MBMessage;
import com.liferay.message.boards.kernel.model.MBThread;

in 

portal-impl/src/com/liferay/portal/upgrade/v6_1_0/UpgradeSocial.java

I think you missed those.

**Comment by adolfopa** [comment]
Thanks @brianchandotcom . I've fixed those and a couple more I found in https://github.com/brianchandotcom/liferay-portal/pull/37319

**Comment by sergiogonzalez** [comment]
Please backport @ZoltanTakacs

**Comment by ZoltanTakacs** [comment]
Thank you @sergiogonzalez. It's been merged to 7.0.x.

Please note that the backport workflow has been changed for the RCs. 
For the details please see @jhendley 's email or refer to this [document](https://docs.google.com/document/d/1A-EoPvI1KDDpUH2PAlKmpgUDb_2RFM4iwpB_4loQHFk/edit).

Thank you,
Zoltán

**Comment by sergiogonzalez** [comment]
Thanks @ZoltanTakacs we'll follow that process from now and on

**Pull request closed without merging**
