### PR TITLE
LPS-81293 display message for site name length check

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@matethurzo "The name" sounds weird in English..

Can you talk to @codyhoag or someone else from the docs team so it sound better? Thx.

**Pull request closed without merging**
