### PR TITLE
LPS-69832 Remove the build project external references in DDL repo

### PR DESCRIPTION
**Pull request by rafaprax**
\cc @marcellustavares

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:reopen

**Comment by rafaprax** [comment]
ci:retest

**Comment by vicnate5** [comment]
The Forms poshi failure is a test issue. The test was just rewritten in https://github.com/brianchandotcom/liferay-portal/pull/46530 so it should be more stable after that is merged.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
