### PR TITLE
LPS-72227 SF

### PR DESCRIPTION
**Pull request by jbalsas**
Hey Brian,

This is an infrastructure task that updates our usage of metal-cli globally. Among other things, it will:
- Fail the build if the soy compilation fails (it wasn't doing it before)
- Work properly in Windows without eol encoding problems

I've made separate commits per module in case we spot some issue and I've sent it for testing in collab to @ambrinchaudhary and portlet-css-web to @ealonso.

I've also sent one to journal: liferay/com-liferay-journal#281 which already got merged.

The .gradle changes have been discussed with @ithildir.

Thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/727d2f67fd...b1beea3e22

**Comment by brianchandotcom** [comment]
@jbalsas can you send me a backport to ee-7.0.x? Can you also include the Journal changes since we're not using subrepos there?

Thx.

**Comment by jbalsas** [comment]
Hey @brianchandotcom, I didn't have time to go through this completely, since it didn't cherry-picked cleanly (depends on pending backports going through).

I'll work on it Wednesday after our long weekend :)

**Comment by jbalsas** [comment]
This finally went through in https://github.com/brianchandotcom/liferay-portal-ee/pull/17033. Thanks a lot @dustinryerson for the help!

**Pull request closed without merging**
