### PR TITLE
LPS-52594 gradle

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
@brianchandotcom The first failure is a bug in SF and the second I believe is unrelated.

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
I talked to @Ithildir and sent it to him https://github.com/Ithildir/liferay-portal/pull/2 

he will rebase and clean it up and send it to me in smaller chunks.

**Comment by rotty3000** [comment]
For what reason?

On Mon, Apr 20, 2015 at 5:40 PM, Brian Chan <notifications@github.com>
wrote:

> I talked to @Ithildir <https://github.com/Ithildir> and sent it to him
> Ithildir#2 <https://github.com/Ithildir/liferay-portal/pull/2>
>
> he will rebase and clean it up and send it to me in smaller chunks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/25739#issuecomment-94575820>
> .
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by brianchandotcom** [comment]
@rotty3000 Ray, I wanted Andrea to review your code so that he'd understand what you're doing since 1.) I want him to apply the same patterns you're using to the other SDK related stuff he's extracting and/have already extracted. 2.) he has more time than me and there was a rebase error and I wanted him to fix it to send to me 3.) he's dedicated just to this.

**Pull request closed without merging**
