### PR TITLE
LPS-45185 removing html from summary

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @matethurzo @kmaria

**Comment by evannagayama** [comment]
@sharonchoi PGAnnouncements test failure

**Comment by sharonchoi** [comment]
Ok, looking into it.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1f56190d0a...eda6eb6d48

**Comment by brianchandotcom** [comment]
@linolaoj Can you see if c0682998b8a2e300f3465d4d998c207272f921a5 looks OK?

**Comment by sharonchoi** [comment]
Resent with poshi fixes here: 
https://github.com/brianchandotcom/liferay-portal/pull/38439

**Comment by linolaoj** [comment]
Hi @brianchandotcom 
I tried to use new line but the text appears as a straight line, so it gets harder to read.

**Pull request closed without merging**
