### PR TITLE
LPS-79379 Fix errors due to stale data

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
See tests -> https://github.com/jbalsas/liferay-portal/pull/1136#issuecomment-379761054

**Comment by brianchandotcom** [comment]
@jbalsas if you do these types of renames, you need to keep things consistent:

Previously:

SoyMapData soyMapData = soyTemplate.getSoyMapData();

now it's no longer consistent

SoyTemplateRecord soyMapData = soyTemplate.getSoyMapData();

Same with:

		_injectedSoyMapData = new SoyTemplateRecord();
		_soyRecord = new SoyTemplateRecord();

Please rename consistently and resend.

Thx

**Comment by jbalsas** [comment]
Sorry about that @brianchandotcom, this was a huge refactor, it totally skipped my scan :(

@adolfopa, can you please take a look at these and resend? 

Thanks!

**Comment by adolfopa** [comment]
Sure

**Pull request closed without merging**
