### PR TITLE
LPS-78107 Move the Add Entry button in blogs to the right of the portlet title

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @jbalsas @marcoscv

**Comment by sergiogonzalez** [comment]
cc/ @austinchiang @patriciajeanperez this pulls moves the Add Entry button in Blogs to the portlet header. The funcionality is still the same, but we might need to update some paths in poshi tests.
Thanks guys!

**Comment by jbalsas** [comment]
LGTM! 👍

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
