### PR TITLE
LPS-108401 Create AccountRole GET and POST endpoints

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-108401](https://issues.liferay.com/browse/LPS-108401).<br><br>This updates the endpoint paths to match the component name based on your feedback here: https://github.com/brianchandotcom/liferay-portal/pull/85631#issuecomment-593668456<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:relevant - We aborted all master pull request jobs.  However, we decided to re-run all pulls in @brianchandotcom queue.

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c6a91e29c8...d9293a340a

**Comment by brianchandotcom** [comment]
@drewbrokke see 5111b781f0bb725793606533be317411bd7de2d9 (you should know this one already)

8f27b81f767e3164158483285fd4b27c25b55e9b is more art.. but close to the getRegionId issue I pointed out earlier (similar principle)

**Comment by drewbrokke** [comment]
@brianchandotcom re 5111b78, I somehow got the impression that there was an issue with the double-brace syntax. I'll keep using it going forward.

**Pull request closed without merging**
