### PR TITLE
Lps 74110

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@brianchandotcom this fixes the lpkg oom failure.

**Comment by shuyangzhou** [comment]
I pushed this to upstream to fix CI, @brianchandotcom later when you have time please release the gradle modules.
CC @Ithildir

**Comment by Ithildir** [comment]
Hi @brianchandotcom and @shuyangzhou,
I don't think we need to publish new Gradle plugins 😊 For now, I reverted the version changes in their `build.gradle`, so they're pointing to the old version of `ant-bnd`, the one without the OOM problem.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
