### PR TITLE
LPS-172811 asset-test-util: gw baseline

### PR DESCRIPTION
**Pull request by gustavolimav**
https://issues.liferay.com/browse/LPS-172811

Tests requested by bchan: https://github.com/brianchandotcom/liferay-portal/pull/129012#issuecomment-1399754577

Author: @gustavolimav
Reviewer: @joshuacords

Tested in: https://github.com/liferay-search/liferay-portal/pull/759
Failures are unrelated.

### CODE REVIEW

**Comment by gustavolimav** [comment]
ci:reopen

**Comment by ealonso** [comment]
ci:close

**Comment by ealonso** [comment]
Hey @gustavolimav @joshuacords,

Since asset-test-util is part of Echo modules, this pr should go through Echo user. If you have any question you can ping me on slack, but it is not the correct way of doing that.

Also, your fix for LPS-172811, was adding the logic in the wrong place, I've fixed as part of LPS-173554.

Regards,
Eudaldo

**Comment by gustavolimav** [comment]
@ealonso Sorry about that, next time we will do that in the right way! Thx for tracking that and fixing it in the correct way. I will take a look at your fixes to learn how to do that.

**Pull request closed without merging**
