### PR TITLE
LPS-59023

### PR DESCRIPTION
**Pull request by natecavanaugh**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pat270 breaks poshi test. Please work with @brianchiu to fix it and resend it to me. Thx.

**Comment by brianchiu** [comment]
@kenjiheigel
Can you take a look at this

**Comment by kenjiheigel** [comment]
Looking into it.

**Comment by kenjiheigel** [comment]
Pushed to BChiu:
https://github.com/brianchiu/liferay-portal/pull/811

**Comment by brianchiu** [comment]
@pat270 @kenjiheigel @natecavanaugh 
The fixes from Kenji's pull have passed review. Go ahead and resend with Kenji's fixes.

**Comment by brianchiu** [comment]
@pat270 @kenjiheigel @natecavanaugh 
Sounds good. I'll send it along.

**Pull request closed without merging**
