### PR TITLE
LPD-5169 - fixing typos and removing extra files

### PR DESCRIPTION
**Pull request by MumenTayyem**

### CODE REVIEW

**Comment by MumenTayyem** [comment]
ci:reopen

**Comment by MumenTayyem** [comment]
ci:test:sf

**Comment by MumenTayyem** [comment]
ci:test:sf

**Comment by MumenTayyem** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@MumenTayyem I think we need to prefix "Related Ticket" no? Please resend. Thx!

**Pull request closed without merging**
