### PR TITLE
LPS-78477 Service Builder Test

### PR DESCRIPTION
**Pull request by Preston-Crary**
CC @shuyangzhou

### CODE REVIEW

**Comment by Preston-Crary** [comment]
@matethurzo please see f095ac0

**Comment by matethurzo** [comment]
@Preston-Crary thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/88d6293f7c...743aee98ca

**Comment by brianchandotcom** [comment]
@ithildir can you undo efbbb44d288e35be6f76963e6b6c059a502d6ff9 ? Note you'll have to manually modify modules/util/portal-tools-service-builder-test-service/build.gradle

I think it has to do with how CI is interpreting .lfrbuild-ci

@Preston-Crary please see my changes in upstream. I made quite a few. Thx.

**Comment by Ithildir** [comment]
Sent fixes to https://github.com/brianchandotcom/liferay-portal/pull/56791.

**Pull request closed without merging**
