### PR TITLE
LPS-67510 regenerate service code

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
Adding Localization entity for FriendlyURLEntry in order to be able to have different friendly URLs for different locales.

cc @adolfopa

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by jpince** [comment]
@pavel-savinov these look like flukes, your pull should be ok

**Pull request closed without merging**
