### PR TITLE
LPS-64457 set the title for the whole page as the blog entry title. use also the subtitle

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6ce0157b11...5bfa31c9df

**Comment by sharonchoi** [comment]
@brianchiu upgrade test failures due to https://issues.liferay.com/browse/LPS-64526
@kenjiheigel portal smoke failings due to https://issues.liferay.com/browse/LPS-64500

**Pull request closed without merging**
