### PR TITLE
Upgrade Process: useful logging

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@sharonchoi can you look into this poshi error? https://github.com/brianchandotcom/liferay-portal/pull/32774

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d7df700dde...5d3fcbd1a2

**Comment by sharonchoi** [comment]
@brianchandotcom sure thing, already looking at it, it's potentially a bug.

**Comment by sharonchoi** [comment]
Hey @migue @brianchandotcom, the reason this poshi test fails is because of this bug I just filed: https://issues.liferay.com/browse/LPS-60875

CC'ing @evannagayama @brianwulbern as they work with Site Memberships more.

**Pull request closed without merging**
