### PR TITLE
LPS-69007 Use the portlet key instead of the service name for the p_p_id parameter

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@jpince random smoke test failure. I've seen it twice. Can you have someone dig in? Thx.

**Comment by jpince** [comment]
@shuyangzhou any thoughts on this? it's failing during the lpkg startup test

**Comment by shuyangzhou** [comment]
@jpince The smoke test in lpkg startup job is always randomly failing, we have seen this for a very long time. Someone from function test team should look into it. If it is a test issue, they can take care of it. If it is a production code issue, they can create a ticket with reproduce steps(does not have to be stably reproducable) and my team can take it over.

**Comment by jpince** [comment]
thanks, we will look into it.

**Comment by jpince** [comment]
This is being investigated under [LRQA-29003](https://issues.liferay.com/browse/LRQA-29003). So far, it has been narrowed down to an issue with AlloyEditor but has been difficult to reproduce.

**Comment by shuyangzhou** [comment]
Then most likely it is a frontend issue, you will have to reach out to frontend team for help.

**Pull request closed without merging**
