### PR TITLE
LPS-64334 Merge SO and core Activities portlets

### PR DESCRIPTION
**Pull request by cgoncas**
/cc @adolfopa

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by alee8888** [comment]
@brianchandotcom 
Still looking into the PR, can you please hold on merging this in?

**Comment by alee8888** [comment]
@cgoncas
I fetched your changes, rebased against master, and built the bundle. Both the Alerts and Announcements portlet are no longer there. Can you please recheck?

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
