### PR TITLE
LPD-6865 6874 6875 6869 6870 6871 test

### PR DESCRIPTION
**Pull request by istvansajtos**
Previous PR: https://github.com/brianchandotcom/liferay-portal/pull/148987

Hi @brianchandotcom ,

I've added [LPD-6870 Rename test method to correspond to DB entity](https://github.com/brianchandotcom/liferay-portal/commit/1b4480417c6ea2d567cbb54374c8a81e6c5ca05f) to address badly named method. I hope you like it.

Thank you!

cc @nikolettabuza

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:reopen

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@istvansajtos @nikolettabuza there's not entity named

LayoutUtilityPage

Guys, at this rate I"ll close this PR 100 times before I merge this. You have to apply the one issue I'm pointing out and apply it to every variable.

**Pull request closed without merging**
