### PR TITLE
Lps 65693 war wrapper tracking

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @jhendley

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 this pull didn't start with a weird error? See comment in this pull 

ci:retest

**Comment by pyoo47** [comment]
@brianchandotcom This error:
` [exec] Please make sure you have the correct access rights
     [exec] and the repository exists.
     [exec] + git push -f git@cloud-10-0-0-15:liferay/liferay-plugins.git master
     [exec] ssh: connect to host cloud-10-0-0-15 port 22: No buffer space available
     [exec] fatal: Could not read from remote repository.
`
Makes me believe that sshd on the local git server (which I'm assuming is running on cloud-10-0-0-15) is running out of memory. It could be because of the release testing there has been a high volume of tests being run. I saw similar errors when I was testing the file propagator. If I created and closed many ssh connections very quickly, I would eventually start encountering this error. I think if you bounce sshd, this problem goes away.

**Comment by brianchandotcom** [comment]
@pyoo47 can you let Sam know? Thx.

**Comment by pyoo47** [comment]
ci:retest I'm going to try one more time since I just saw another pull get started successfully.

**Comment by pyoo47** [comment]
It looks like it's working now. I let Sam know via Skype and I'll follow up with him in the office tomorrow.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
