### PR TITLE
LPS-67821 We never use micro versions for com.liferay.* provided to compile

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@hhuijser I really like the new modules/apps/foundation/frontend-taglib/frontend-taglib/bnd.bnd

See

```
Provide-Capability:\
	osgi.extender;\
		osgi.extender="jsp.taglib";\
		uri="http://liferay.com/tld/frontend";\
		version:Version="${Bundle-Version}",\
	soy;\
		type="frontend-taglib";\
		version:Version="${Bundle-Version}"
```

Can you auto SF so the really long lines in bnd.bnd follow this format?

Contrast with before:

```
Provide-Capability: osgi.extender;osgi.extender="jsp.taglib";uri="http://liferay.com/tld/frontend";version:Version="${Bundle-Version}"
```

@ealonso @carloslancha @jbalsas I made a bunch of Java changes in upstream. Please review.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/25bc4596a6...32419bb23e

**Comment by jbalsas** [comment]
Looks good to me @brianchandotcom. Thanks!

**Pull request closed without merging**
