### PR TITLE
LPS-175193 Fix classloading issue in ASMDelegateProxyFactory and its …

### PR DESCRIPTION
**Pull request by shuyangzhou**
…test. Low level infra code is very sensitive to logging. It could cause many classloading issues. Caused by a313b127

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
@vicnate5 can you make sure CI asserts the results for ASMDelegateProxyFactoryTest ? It has been failing for months. And I only knew it just now. It is an important enough test, which should always pass.

**Comment by vicnate5** [comment]
@shuyangzhou Failure was caught by CI and originally reported under https://issues.liferay.com/browse/LPS-162667. Component wasn't correct, so it was missing on ticket filters. We did [try to notify you on JIRA ](https://issues.liferay.com/browse/LPS-162667?focusedCommentId=2756610&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2756610). QA can work on our follow up game though.

**Comment by shuyangzhou** [comment]
I see, can we always add this to relevant batch? so that future breaking changes can be blocked out. I don't think unit tests are the bottleneck in relevant, right? We may need to do a round of failing unit tests fixing and just always run them from now on, they should be cheap enough.

**Comment by vicnate5** [comment]
Will have someone do the analysis and pursue this.

**Comment by shuyangzhou** [comment]
Thanks @vicnate5 !

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a036f7dc7e...52cb31b403

**Pull request closed without merging**
