### PR TITLE
[Backport to 7.1.x] LPS-85240 Checks to see if actionItems is set before attempting to update it. A default actionItems is not set because of liferay/clay#1178

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jbalsas backported for you.

**Comment by jbalsas** [comment]
Thanks a lot @brianchandotcom!

**Comment by jpince** [comment]
@jbalsas I think this caused a semver failure? Pushed a fix upstream https://github.com/liferay/liferay-portal/commit/78cfc3745c69a77cebbaca39e3844b749fd5668b
```
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.frontend.taglib.clay.servlet.taglib.soy MINOR      1.0.0      1.0.0      1.1.0      VERSION INCREASE REQUIRED
     [exec] 	<   class      com.liferay.frontend.taglib.clay.servlet.taglib.soy.ManagementToolbarTag
     [exec] 		+   method     setActionHandler(java.lang.String)
     [exec] 			+   return     void
```

**Comment by jpince** [comment]
actually it was this one https://github.com/brianchandotcom/liferay-portal/pull/62888. This just ran semver on the same module.

**Pull request closed without merging**
