### PR TITLE
LPS-73338 Rename attribute to showDisableCheckbox so it’s purpose is clear

### PR DESCRIPTION
**Pull request by robframpton**

### CODE REVIEW

**Comment by Robert-Frampton** [comment]
ci:retest

**Comment by JosemariaMunoz** [comment]
ci:reopen

**Comment by JosemariaMunoz** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8ac1aec833...17fc167300

**Pull request closed without merging**
