### PR TITLE
LPS-78088 Add test and make replacement more robust

### PR DESCRIPTION
**Pull request by izaera**
/cc @antonio-ortega

### CODE REVIEW

**Comment by izaera** [comment]
ci:test

**Comment by izaera** [comment]
The failing tests are not related to the PR, as far as I can see.

**Comment by timpak** [comment]
ci:close

**Comment by timpak** [comment]
@izaera 

Hi, could you please look into this SF error? Thanks!

     [java] 8: ./portal-impl/test/unit/com/liferay/portal/minifier/MinifierUtilTest.java expected:<...-1px / -1px - 1px);"[);
     [java] 
     [java] 		Assert.assertEquals(
     [java] 			"left:calc(-1px + -1px - -1px * -1px / -1px - 1px);", ]minifiedCss);
     [java] 	}
     [java] 
     [java] 	@...> but was:<...-1px / -1px - 1px);"[
     [java] 		);
     [java] 
     [java] 		Assert.assertEquals(
     [java] 			"left:calc(-1px + -1px - -1px * -1px / -1px - 1px);",
     [java] 			]minifiedCss);
     [java] 	}
     [java] 
     [java] 	@...>

**Pull request closed without merging**
