### PR TITLE
COMMERCE-4621 Fixed modal overridden display css attr

### PR DESCRIPTION
**Pull request by marco-leo**

### CODE REVIEW

**Comment by marco-leo** [comment]
ci:reopen

**Comment by marco-leo** [comment]
Test pass in https://github.com/liferay-commerce/liferay-portal/pull/53 , failure getting in that PR are not related.  Sending this as is a blocker issue for the build

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fc938c3f8f...f19dbfbd45

**Comment by brianchandotcom** [comment]
@marco-leo Doing this for now .. but the long term is to fix these bugs

```

Test Result (49 failures / +49)com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXMLLogcom.liferay.headless.commerce.admin.pricing.resource.v2_0.test.DiscountAccountGroupResourceTest.testGetDiscountByExternalReferenceCodeDiscountAccountGroupsPagecom.liferay.headless.commerce.admin.pricing.resource.v2_0.test.DiscountAccountGroupResourceTest.testGetDiscountIdDiscountAccountGroupsPagecom.liferay.headless.commerce.admin.pricing.resource.v2_0.test.DiscountAccountGroupResourceTest.testGraphQLDeleteDiscountAccountGroupcom.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXMLLogcom.liferay.commerce.internal.order.test.CommerceOrderHttpHelperImplTest.testGetCommerceOrderItemsQuantitycom.liferay.commerce.internal.search.test.CommerceOrderItemIndexerTest.testEmptyQuerycom.liferay.commerce.internal.util.test.CommerceShippingHelperTest.testGetDimensionscom.liferay.commerce.internal.util.test.CommerceShippingHelperTest.testGetWeightcom.liferay.commerce.order.engine.test.CommerceOrderEngineTest.testAutomaticallyTransitionOrderToCompletedShow all failed tests >>>
--

```

So we disable anything that is breaking on relevant and then go back and fix them. We also monitor weekly in our call how many things are disabled.

@jpince we need to explain the process to @marco-leo in our next call.

**Comment by marco-leo** [comment]
@brianchandotcom Jason already explained it, as we are trying to make pass al tests under this pr https://github.com/liferay-commerce/liferay-portal/pull/60. I just prefered to avoid to disable, in case it keeo failing we will disable it. Consider that 2 tests that fais are autogenerated from rest builder and a bug is opened to them

**Pull request closed without merging**
