### PR TITLE
LPS-169100 HRG_26 My Profile exist multiple heading

### PR DESCRIPTION
**Pull request by Tim-Cao**
This is only for master.

https://issues.liferay.com/browse/LPS-169100

@veroglez

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/11222

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4dcf1d9df8...ffa71cadc9

**Comment by brianchandotcom** [comment]
@ealonso @veroglez thanks for the proper fix!

**Pull request closed without merging**
