### PR TITLE
LPS-89723

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:reopen

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bd1740b0b4...003dcc044b

**Comment by brianchandotcom** [comment]
@victorg1991 @adolfopa I made a lot of changes in upstream... can you also resend the test? 

I want to generate them like we do for *PersistenceTest.java

At the very least, some of it should go in a portal-vulcan-test-util 

Please resend. Thx.

**Pull request closed without merging**
