### PR TITLE
LPS-74415 Move conversion from String to HTML to SoyHTMLContextValue constructor

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
cc @brunobasto

**Review by brunobasto — CHANGES_REQUESTED** [review]
Hey @leoadb, won't that cause a breaking change in baseline? We should be able to backport this fix if possible.

**Comment by leoadb** [comment]
ci:reopen

**Comment by leoadb** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ef14cf2b83...e425a154d5

**Pull request closed without merging**
