### PR TITLE
LPS-79686 Fixing selector

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test

**Comment by timpak** [comment]
@austinchiang @patriciajeanperez FYI this is going to affect a lot of functional test cases.

**Comment by patriciajeanperez** [comment]
Hey @4lejandrito, a lot of acceptance tests seem to fail. I'm going to close this pull and fix those tests before resending to Brian. Thanks!

**Comment by patriciajeanperez** [comment]
ci:close

**Comment by patriciajeanperez** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/57955

**Pull request closed without merging**
