### PR TITLE
LRQA-50074, LRQA-50420, LRQA-51045 | master

### PR DESCRIPTION
**Pull request by GinsonRen**
https://issues.liferay.com/browse/LRQA-50074
https://issues.liferay.com/browse/LRQA-50420
https://issues.liferay.com/browse/LRQA-51045

7.2.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/25738
7.1.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/25739
7.0.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/25740

### CODE REVIEW

**Comment by GinsonRen** [comment]
ci:reopen

**Comment by GinsonRen** [comment]
ci:test:sf

**Comment by GinsonRen** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8b529a1216...07a244fd83

**Pull request closed without merging**
