### PR TITLE
[Technical Support] LPS-85875 Do not delete the structure if it belongs to a different group

### PR DESCRIPTION
**Pull request by rafaprax**
Hi @rafaprax,

I just reviewed this pull request and it looks good to me. If you need any clarification, please ask @robertoDiaz.

Thanks.

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Please send a backport to support like our normal support workflow.

Merged into master only. Thank you.

@jhendley @liferay @zsoltbalogh FYI.

**Pull request closed without merging**
