### PR TITLE
LPS-65398 ImageEditor API and WEB modules

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @brianchandotcom, this is the first part of the new ImageEditor. On top of your changes, we have...
- Addressed Nate SF concerns
- Renamed Java method names and variables to make them consistent (thanks @adolfopa!)
- Renamed Soy and JS method names and variables to make them consistent
- Scanned through the jsdoc (not really sure which issues you saw there, though)

One thing to note is that `ImageEditorCapability` is an atomic concept. It is not the capability of having an ImageEditor, but a description of something our ImageEditor can do. Following that, we'll have:
- `BrightnessImageEditorCapability`
- `ContrastImageEditorCapability`
- `CropImageEditorCapability`
- `FilterImageEditorCapability`
- `RotateImageEditorCapability`
- ...

Once we have settled on the `api` and `web` modules, we'll be sending in all the `ImageEditorCapability` implementations as well as several integrations with Document Library, Item Selector and AlloyEditor.

Hope it makes more sense now

Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
ci:stop

**Comment by jbalsas** [comment]
ci:retest

**Comment by natecavanaugh** [comment]
@jbalsas 
The only other thing I forgot to mention is [the underscore suffix for private methods and properties](https://github.com/jbalsas/liferay-portal/blob/pr-520/modules/apps/foundation/frontend-image-editor/frontend-image-editor-web/src/main/resources/META-INF/resources/ImageEditor.es.js#L196).

It's a Google-ism that is only there because they write code in C (as well as Java and their other languages), but they do that because C reserves underscore prefixes for the compiler.

But for us, where 99% of our code uses the underscore prefix on the front and backend, it doesn't make much sense to adopt this convention simply for stylistic reasons (and it really seems to only serve to make private methods and properties harder to identify).

Could we remove that style for code in portal? What do you think?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c6a380f734...03a9828f4c

**Comment by brianchandotcom** [comment]
Very nice @jbalsas and @adolfopa !

**Comment by brianchandotcom** [comment]
@Ithildir fyi on Gradle changes

**Comment by jbalsas** [comment]
Hey @natecavanaugh, about the underscore notation, I was following `Senna.js` and `Metal.js` style guidelines since that's where our bulk of ES2015 code is. I'm fine if we want keep the old style guidelines for Portal, but that might make it harder to switch from Portal to the other projects. I can update the code in Portal with whatever we decide.

@eduardolundgren, what do you think?

**Pull request closed without merging**
