### PR TITLE
LPS-74110

### PR DESCRIPTION
**Pull request by Ithildir**
Hi,
Please let this pull finish.

Thank you!

### CODE REVIEW

**Comment by jpince** [comment]
@Ithildir please let shuyang know if this is safe to merge so he can push it upstream. thanks!

**Comment by Ithildir** [comment]
@jpince, this pull requires to publish new modules. If it's urgent, I can try to think of something that doesn't require any publishing, so it'll be easier to push upstream.

**Comment by jpince** [comment]
@Ithildir sorry, I meant after the tests have finished :)

**Comment by Ithildir** [comment]
ci:stop I sent this instead: https://github.com/shuyangzhou/liferay-portal/pull/4966

**Pull request closed without merging**
