### PR TITLE
OAUTH2-282 Scope translation missing after disabling or deleting corresponding SAP entry

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Reviewed https://github.com/stian-sigvartsen/liferay-portal/pull/173

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cb36be19cf...e32a5895b8

**Comment by brianchandotcom** [comment]
@stian-sigvartsen please backport to 7.2.x along with the other missing OAUTH tickets. Thx.

**Comment by brianchandotcom** [comment]
@jpince I didn't do lbm backport since it needs to point to my origin.

**Comment by stian-sigvartsen** [comment]
@brianchandotcom I'll be sending the backports tomorrow hopefully

**Pull request closed without merging**
