### PR TITLE
LPS-188415 Make endpoints response with their associated response Schema

### PR DESCRIPTION
**Pull request by LuismiBarcos**
Original description:

Related ticket -> [LPS-188415](https://liferay.atlassian.net/browse/LPS-188415)
____
## Dependencies
This PR should be sent once this [other PR](https://github.com/brianchandotcom/liferay-portal/pull/137231) would be merged

## Purpose of the PR
This PR adds the logic to response with the response schema associated with an endpoint in the Headless Builder REST Applications.

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@LuismiBarcos rebase error, please resend.

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/137697.

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/137702.

**Pull request closed without merging**
