### PR TITLE
LPS-76961 Missing language key in Fragment simple input modal

### PR DESCRIPTION
**Pull request by jkappler**
cc:// @ealonso

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test

**Comment by jkappler** [comment]
ci:reopen

**Comment by jpince** [comment]
@Ithildir I think I've seen this failure in modules-compile 2-3 times this week (not very frequently). Any idea what might be causing the flakiness?

` [exec] org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':util:portal-tools-wsdd-builder:compileClasspath'.`

**Comment by Ithildir** [comment]
@jpince: did it start failing only recently? Can you find out if it's failing always on the same slaves, or if it just fails randomly?

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@Ithildir is it trying to download somethiing from the Internet that should be cached?

**Comment by brianchandotcom** [comment]
@Ithildir perhaps some xsd or dtd?

**Comment by Ithildir** [comment]
Maybe! I fixed the cache for `test`, `sdk` and `util` modules at https://github.com/liferay/liferay-binaries-cache-2017/commit/e160365fb5896c1dc1074788e1675452261bfbbb.

**Comment by jpince** [comment]
@Ithildir, thanks! I'll keep track of future failures and let you know if I
see any trends

**Pull request closed without merging**
