### PR TITLE
Lps 71605

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0a7cf8df72...ed3963c5d9

**Comment by brianchandotcom** [comment]
@Preston-Crary please backport.

@hhuijser can you SF enforce this? it's a performance benefit if we use the new API.

Thx.

**Comment by shuyangzhou** [comment]
@hhuijser @brianchandotcom I think we might want to generalize this rule to be, not allowing our code to use our own deprecated code(class and method). @hhuijser do you think this is doable?

**Comment by Preston-Crary** [comment]
@brianchandotcom will backport after applying the change to DDM.

**Pull request closed without merging**
