### PR TITLE
LPS-128227 | Links inside liferay-ui:icon-menu should contain `dropdown-item` css class

### PR DESCRIPTION
**Pull request by john-co**
This is basically a different way to add `dropdown-item` classes to icons within icon menus to prevent the class from being accidentally set in icons causing the issue described in [Login Modal create account and forgot password links are styled incorrectly](https://issues.liferay.com/browse/LPS-128227)

wiki-portlet

### CODE REVIEW

**Comment by john-co** [comment]
cc/ @pat270 @jbalsas

**Comment by john-co** [comment]
ci:reopen

**Comment by john-co** [comment]
Manually forwarding since last 2 test run attempts encountered flaky issues. 
Reviewed. Test failures are unrelated. :heavy_check_mark: 

https://github.com/liferay-frontend/liferay-portal/pull/862#issuecomment-791402951

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/97c81548cc...a5d3735c0a

**Pull request closed without merging**
