### PR TITLE
LPS-77000

### PR DESCRIPTION
**Pull request by dejuknow**

### CODE REVIEW

**Comment by dejuknow** [comment]
I didn't remove/replace "public static void verify()", instead I just changed "protected void doVerify()" to be public. Did this to avoid major semver change from 1.4 -> 2.0. Let me know if I should remove the static method instead.

**Comment by dejuknow** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@dejuknow can you send me a backport to 7.0.x? It doesn't cherry pick cleanly because of LPS-75031 59e4fe56865686c6e1f83f763c932842a870db6e

**Comment by dejuknow** [comment]
7.0.x backport: https://github.com/brianchandotcom/liferay-portal-ee/pull/19207

**Pull request closed without merging**
