### PR TITLE
LPS-67383 use new folder selector for Journal Articles

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Hey @anthony-chu 

this changes the UI of the folder selector for Web Content Articles and folders. Not sure if it will break a functional test. Would you like us to add any qa-id?

Thanks!

folder

**Comment by anthony-chu** [comment]
ci:rest

**Comment by anthony-chu** [comment]
Thanks @juliocamarero for letting us know about this change! We're currently looking into the UI change to anticipate if an acceptance test will fail, since the first PR tester results didn't provide any visibility for frontend failures.

**Comment by anthony-chu** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d3217947c6...d07a1de5aa

**Comment by brianchandotcom** [comment]
@juliocamarero @anthony-chu I merged this in even though CI showed so many failures. I just assume it was some random CI issue? I can't imagine this pull breaking so much?

**Comment by anthony-chu** [comment]
cc @liulukiwki @GinsonRen @brianwulbern This change uses a UI similar to the product menu navigation panel to select folders to move web content to. Please let me know if you guys have any questions.

**Pull request closed without merging**
