### PR TITLE
LPS-63948 apply changes to WAB Extender and Portlet Tracker

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
this is an issue in CI

**Comment by brianchandotcom** [comment]
Yeah, just fixed the CI issue.. ci:retest

**Comment by rotty3000** [comment]
great fingers crossed

**Comment by brianchandotcom** [comment]
@rotty3000 I'll fix SF and merge..

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e43b86c2a3...04d4a815da

**Comment by brianchandotcom** [comment]
@rotty3000 can you send a follow up pull based on comments in 8e7b1484f5a8b5bd8eb1415e7b87749fb27bc6c3

Thx!

**Pull request closed without merging**
