### PR TITLE
Lps 57261

### PR DESCRIPTION
**Pull request by shuyangzhou**
This should fix all the missing session attributes related tickets. It has nothing to do with any "portlet container" level stuff. It is a bug inside org.eclipse.equinox.http.servlet.

What happened is, using the "Create a Blog without title" case as an example:

1) Create a blog entry with no title, of course it will fail with com.liferay.portlet.blogs.EntryTitleException
2) We save this error message into session inside com.liferay.blogs.web.portlet.action.EditEntryMVCActionCommand line 343 "SessionErrors.add(actionRequest, e.getClass())". At this moment, we are at portlet/servlet layer, we are actually directly saving the info as a session attribute through a few our wrappers into appserver's session object.
3) Later in com.liferay.taglib.ui.ErrorTag we try to get back the session attribute to show up proper failure message, but at this moment, we are at jsp layer where we use the org.eclipse.equinox.http.servlet lib, to be exact the current portlet session is backed by HttpSessionAdaptor, and that silly thing has the following body for "public Object getAttribute(String arg0)" :

```
    public Object getAttribute(String arg0) {
        Object result = session.getAttribute(attributePrefix + arg0);
        if (result instanceof HttpSessionAttributeWrapper) {
            result = ((HttpSessionAttributeWrapper) result).value;
        }
        return result;
    }
```

See the problem, it is unconditionally adding in a "attributePrefix" to the attribute name, as if it owns all attributes, which is so not true as the underneath appserver sesion has already been used and populated with attributes by previous portlet/servlet layer code (EditEntryMVCActionCommand), then of course the end result is we are missing all sorts of attributes.

I am fixing this by a thrid-party patch way, as we need this fix being merged immediately in order to solve all related tickets. The patch is very simple, just fallback to unnamespaced key to try again on missing.

@rotty3000 please take your time to talk to the OSGi guys to have them take in this fix. Then we can drop off this patch fix, move to use their fixed version.

@brianchandotcom, as you can see the build.xml for this patch module is a bit unusual, it is because the target org.eclipse.equinox.http.servlet jar does not exist in maven repo, so that I have to use our ivy repo to do the patch process, therefore the standard patch target does not work, I have to do it explicitly. Consider we will drop off this module after @rotty3000 gets it merged offically, it should not be a problem, let's just do it this way for now to get over the issues.

@lionah, I think this would fix your problem too, please double check.

CC @mhan810

### CODE REVIEW

**Comment by rotty3000** [comment]
Shuyang, just give me the fix and I'll apply it! I'm a committer on this
library!

On Wed, Aug 12, 2015 at 12:30 PM, Shuyang Zhou <notifications@github.com>
wrote:

> This should fix all the missing session attributes related tickets. It has
> nothing to do with any "portlet container" level stuff. It is a bug inside
> org.eclipse.equinox.http.servlet.
>
> What happened is, using the "Create a Blog without title" case as an
> example:
>
> 1) Create a blog entry with no title, of course it will fail with
> com.liferay.portlet.blogs.EntryTitleException
> 2) We save this error message into session inside
> com.liferay.blogs.web.portlet.action.EditEntryMVCActionCommand line 343
> "SessionErrors.add(actionRequest, e.getClass())". At this moment, we are at
> portlet/servlet layer, we are actually directly saving the info as a
> session attribute through a few our wrappers into appserver's session
> object.
> 3) Later in com.liferay.taglib.ui.ErrorTag we try to get back the session
> attribute to show up proper failure message, but at this moment, we are at
> jsp layer where we use the org.eclipse.equinox.http.servlet lib, to be
> exact the current portlet session is backed by HttpSessionAdaptor, and that
> silly thing has the following body for "public Object getAttribute(String
> arg0)" :
>
>     public Object getAttribute(String arg0) {
>         Object result = session.getAttribute(attributePrefix + arg0);
>         if (result instanceof HttpSessionAttributeWrapper) {
>             result = ((HttpSessionAttributeWrapper) result).value;
>         }
>         return result;
>     }
>
> See the problem, it is unconditionally adding in a "attributePrefix" to
> the attribute name, as if it owns all attributes, which is so not true as
> the underneath appserver sesion has already been used and populated with
> attributes by previous portlet/servlet layer code
> (EditEntryMVCActionCommand), then of course the end result is we are
> missing all sorts of attributes.
>
> I am fixing this by a thrid-party patch way, as we need this fix being
> merged immediately in order to solve all related tickets. The patch is very
> simple, just fallback to unnamespaced key to try again on missing.
>
> @rotty3000 <https://github.com/rotty3000> please take your time to talk
> to the OSGi guys to have them take in this fix. Then we can drop off this
> patch fix, move to use their fixed version.
>
> @brianchandotcom <https://github.com/brianchandotcom>, as you can see the
> build.xml for this patch module is a bit unusual, it is because the target
> org.eclipse.equinox.http.servlet jar does not exist in maven repo, so that
> I have to use our ivy repo to do the patch process, therefore the standard
> patch target does not work, I have to do it explicitly. Consider we will
> drop off this module after @rotty3000 <https://github.com/rotty3000> gets
> it merged offically, it should not be a problem, let's just do it this way
> for now to get over the issues.
>
> @lionah <https://github.com/lionah>, I think this would fix your problem
> too, please double check.
>
> CC @mhan810 <https://github.com/mhan810>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/brianchandotcom/liferay-portal/pull/29240
> Commit Summary
>
>    - LPS-57261 LPS-56630 Patch HttpSessionAdaptor to fix the broken
>    getAttribute() logic
>    - LPS-57261 LPS-56630 Make portal-wab-extender to use the patched
>    org.eclipse.equinox.http.servlet
>    - LPS-57261 LPS-56630 Ivy cache for CI, Brian please drop this after
>    you publish the patch module and re-populate the ivy cache.
>
> File Changes
>
>    - *A*
>    .ivy/cache/com.liferay/org.eclipse.equinox.http.servlet/ivy-1.2.1-SNAPSHOT.LIFERAY-PATCHED-1-SNAPSHOT.xml
>    <https://github.com/brianchandotcom/liferay-portal/pull/29240/files#diff-0>
>    (33)
>    - *A*
>    .ivy/cache/com.liferay/org.eclipse.equinox.http.servlet/ivy-1.2.1-SNAPSHOT.LIFERAY-PATCHED-1-SNAPSHOT.xml.original
>    <https://github.com/brianchandotcom/liferay-portal/pull/29240/files#diff-1>
>    (41)
>    - *A*
>    .ivy/cache/com.liferay/org.eclipse.equinox.http.servlet/ivydata-1.2.1-SNAPSHOT.LIFERAY-PATCHED-1-SNAPSHOT.properties
>    <https://github.com/brianchandotcom/liferay-portal/pull/29240/files#diff-2>
>    (15)
>    - *A*
>    .ivy/cache/com.liferay/org.eclipse.equinox.http.servlet/jars/org.eclipse.equinox.http.servlet-1.2.1-SNAPSHOT.LIFERAY-PATCHED-1-SNAPSHOT.jar
>    <https://github.com/brianchandotcom/liferay-portal/pull/29240/files#diff-3>
>    (0)
>    - *M* modules/portal/portal-wab-extender/ivy.xml
>    <https://github.com/brianchandotcom/liferay-portal/pull/29240/files#diff-4>
>    (2)
>    - *A* modules/third-party/org-eclipse-equinox-http-servlet/bnd.bnd
>    <https://github.com/brianchandotcom/liferay-portal/pull/29240/files#diff-5>
>    (3)
>    - *A* modules/third-party/org-eclipse-equinox-http-servlet/build.gradle
>    <https://github.com/brianchandotcom/liferay-portal/pull/29240/files#diff-6>
>    (0)
>    - *A* modules/third-party/org-eclipse-equinox-http-servlet/build.xml
>    <https://github.com/brianchandotcom/liferay-portal/pull/29240/files#diff-7>
>    (70)
>    - *A* modules/third-party/org-eclipse-equinox-http-servlet/ivy.xml
>    <https://github.com/brianchandotcom/liferay-portal/pull/29240/files#diff-8>
>    (22)
>    - *A*
>    modules/third-party/org-eclipse-equinox-http-servlet/patches/LPS-57261.diff
>    <https://github.com/brianchandotcom/liferay-portal/pull/29240/files#diff-9>
>    (25)
>    - *A*
>    modules/third-party/org-eclipse-equinox-http-servlet/src/org/eclipse/equinox/http/servlet/internal/servlet/HttpSessionAdaptor.java
>    <https://github.com/brianchandotcom/liferay-portal/pull/29240/files#diff-10>
>    (296)
>
> Patch Links:
>
>    - https://github.com/brianchandotcom/liferay-portal/pull/29240.patch
>    - https://github.com/brianchandotcom/liferay-portal/pull/29240.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/29240>.
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by rotty3000** [comment]
Please don't make a third party patch!

On Wed, Aug 12, 2015 at 12:33 PM, Raymond Auge <raymond.auge@liferay.com>
wrote:

> Shuyang, just give me the fix and I'll apply it! I'm a committer on this
> library!
>
> On Wed, Aug 12, 2015 at 12:30 PM, Shuyang Zhou <notifications@github.com>
> wrote:
>
>> This should fix all the missing session attributes related tickets. It
>> has nothing to do with any "portlet container" level stuff. It is a bug
>> inside org.eclipse.equinox.http.servlet.
>>
>> What happened is, using the "Create a Blog without title" case as an
>> example:
>>
>> 1) Create a blog entry with no title, of course it will fail with
>> com.liferay.portlet.blogs.EntryTitleException
>> 2) We save this error message into session inside
>> com.liferay.blogs.web.portlet.action.EditEntryMVCActionCommand line 343
>> "SessionErrors.add(actionRequest, e.getClass())". At this moment, we are at
>> portlet/servlet layer, we are actually directly saving the info as a
>> session attribute through a few our wrappers into appserver's session
>> object.
>> 3) Later in com.liferay.taglib.ui.ErrorTag we try to get back the session
>> attribute to show up proper failure message, but at this moment, we are at
>> jsp layer where we use the org.eclipse.equinox.http.servlet lib, to be
>> exact the current portlet session is backed by HttpSessionAdaptor, and that
>> silly thing has the following body for "public Object getAttribute(String
>> arg0)" :
>>
>>     public Object getAttribute(String arg0) {
>>         Object result = session.getAttribute(attributePrefix + arg0);
>>         if (result instanceof HttpSessionAttributeWrapper) {
>>             result = ((HttpSessionAttributeWrapper) result).value;
>>         }
>>         return result;
>>     }
>>
>> See the problem, it is unconditionally adding in a "attributePrefix" to
>> the attribute name, as if it owns all attributes, which is so not true as
>> the underneath appserver sesion has already been used and populated with
>> attributes by previous portlet/servlet layer code
>> (EditEntryMVCActionCommand), then of course the end result is we are
>> missing all sorts of attributes.
>>
>> I am fixing this by a thrid-party patch way, as we need this fix being
>> merged immediately in order to solve all related tickets. The patch is very
>> simple, just fallback to unnamespaced key to try again on missing.
>>
>> @rotty3000 <https://github.com/rotty3000> please take your time to talk
>> to the OSGi guys to have them take in this fix. Then we can drop off this
>> patch fix, move to use their fixed version.
>>
>> @brianchandotcom <https://github.com/brianchandotcom>, as you can see
>> the build.xml for this patch module is a bit unusual, it is because the
>> target org.eclipse.equinox.http.servlet jar does not exist in maven repo,
>> so that I have to use our ivy repo to do the patch process, therefore the
>> standard patch target does not work, I have to do it explicitly. Consider
>> we will drop off this module after @rotty3000
>> <https://github.com/rotty3000> gets it merged offically, it should not
>> be a problem, let's just do it this way for now to get over the issues.
>>
>> @lionah <https://github.com/lionah>, I think this would fix your problem
>> too, please double check.
>>
>> CC @mhan810 <https://github.com/mhan810>
>> ------------------------------
>> You can view, comment on, or merge this pull request online at:
>>
>>   https://github.com/brianchandotcom/liferay-portal/pull/29240
>> Commit Summary
>>
>>    - LPS-57261 LPS-56630 Patch HttpSessionAdaptor to fix the broken
>>    getAttribute() logic
>>    - LPS-57261 LPS-56630 Make portal-wab-extender to use the patched
>>    org.eclipse.equinox.http.servlet
>>    - LPS-57261 LPS-56630 Ivy cache for CI, Brian please drop this after
>>    you publish the patch module and re-populate the ivy cache.
>>
>> File Changes
>>
>>    - *A*
>>    .ivy/cache/com.liferay/org.eclipse.equinox.http.servlet/ivy-1.2.1-SNAPSHOT.LIFERAY-PATCHED-1-SNAPSHOT.xml
>>    <https://github.com/brianchandotcom/liferay-portal/pull/29240/files#diff-0>
>>    (33)
>>    - *A*
>>    .ivy/cache/com.liferay/org.eclipse.equinox.http.servlet/ivy-1.2.1-SNAPSHOT.LIFERAY-PATCHED-1-SNAPSHOT.xml.original
>>    <https://github.com/brianchandotcom/liferay-portal/pull/29240/files#diff-1>
>>    (41)
>>    - *A*
>>    .ivy/cache/com.liferay/org.eclipse.equinox.http.servlet/ivydata-1.2.1-SNAPSHOT.LIFERAY-PATCHED-1-SNAPSHOT.properties
>>    <https://github.com/brianchandotcom/liferay-portal/pull/29240/files#diff-2>
>>    (15)
>>    - *A*
>>    .ivy/cache/com.liferay/org.eclipse.equinox.http.servlet/jars/org.eclipse.equinox.http.servlet-1.2.1-SNAPSHOT.LIFERAY-PATCHED-1-SNAPSHOT.jar
>>    <https://github.com/brianchandotcom/liferay-portal/pull/29240/files#diff-3>
>>    (0)
>>    - *M* modules/portal/portal-wab-extender/ivy.xml
>>    <https://github.com/brianchandotcom/liferay-portal/pull/29240/files#diff-4>
>>    (2)
>>    - *A* modules/third-party/org-eclipse-equinox-http-servlet/bnd.bnd
>>    <https://github.com/brianchandotcom/liferay-portal/pull/29240/files#diff-5>
>>    (3)
>>    - *A*
>>    modules/third-party/org-eclipse-equinox-http-servlet/build.gradle
>>    <https://github.com/brianchandotcom/liferay-portal/pull/29240/files#diff-6>
>>    (0)
>>    - *A* modules/third-party/org-eclipse-equinox-http-servlet/build.xml
>>    <https://github.com/brianchandotcom/liferay-portal/pull/29240/files#diff-7>
>>    (70)
>>    - *A* modules/third-party/org-eclipse-equinox-http-servlet/ivy.xml
>>    <https://github.com/brianchandotcom/liferay-portal/pull/29240/files#diff-8>
>>    (22)
>>    - *A*
>>    modules/third-party/org-eclipse-equinox-http-servlet/patches/LPS-57261.diff
>>    <https://github.com/brianchandotcom/liferay-portal/pull/29240/files#diff-9>
>>    (25)
>>    - *A*
>>    modules/third-party/org-eclipse-equinox-http-servlet/src/org/eclipse/equinox/http/servlet/internal/servlet/HttpSessionAdaptor.java
>>    <https://github.com/brianchandotcom/liferay-portal/pull/29240/files#diff-10>
>>    (296)
>>
>> Patch Links:
>>
>>    - https://github.com/brianchandotcom/liferay-portal/pull/29240.patch
>>    - https://github.com/brianchandotcom/liferay-portal/pull/29240.diff
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/brianchandotcom/liferay-portal/pull/29240>.
>>
>
>
>
> --
> *Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
>  (@rotty3000)
> Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
>  (@Liferay)
> Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org>
> (@OSGiAlliance)
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by shuyangzhou** [comment]
The fix is in the LPS-57261.diff, 3 lines addition change, you can just copy and paste it out.

**Comment by brianchandotcom** [comment]
@rotty3000 I won't check in the patch.  If the test results for this pull is green, can you then make the match and send me a follow up pull with an OSGi fix, but do reference this pull for record keeping.

Thanks @shuyangzhou @rotty3000 !

**Comment by rotty3000** [comment]
Will do it right away.

On Wed, Aug 12, 2015 at 12:52 PM, Brian Chan <notifications@github.com>
wrote:

> @rotty3000 <https://github.com/rotty3000> I won't check in the patch. If
> the test results for this pull is green, can you then make the match and
> send me a follow up pull with an OSGi fix, but do reference this pull for
> record keeping.
>
> Thanks @shuyangzhou <https://github.com/shuyangzhou> @rotty3000
> <https://github.com/rotty3000> !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/29240#issuecomment-130368195>
> .
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by lionah** [comment]
:+1: Thanks @shuyangzhou @rotty3000

**Comment by brianchandotcom** [comment]
@rotty3000 I'm not going to merge this in, since you have a different fix. Going to close this pull.

**Pull request closed without merging**
