### PR TITLE
LPS-144888 Use Liferay as a local variable to avoid errors when use Remote App out of Liferay Portal

### PR DESCRIPTION
**Pull request by kevenleone**

### CODE REVIEW

**Comment by kevenleone** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html><details><summary>More details about: <b>LPS-144888 Use isSet() to check whether a variable was set instead of an old pattern by using contains("${xyz}", "{xyz}")</b>.</summary>
              <br />
              <table>
              <tr>
            <th>Title</th>
            <td><a target="_blank" href="https://issues.liferay.com/browse/LPS-144888">Use isSet() to check whether a variable was set instead of an old pattern by using contains("${xyz}", "{xyz}")</a></td>
        </tr>
              <tr>
            <th>Type</th>
            <td>Task</td>
        </tr>
              <tr>
            <th>Priority</th>
            <td>Minor</td>
        </tr>
              <tr>
            <th>Sub-Tasks</th>
            <td>No Sub-Tasks Opened</td>
        </tr>
              <tr>
            <th>Status</th>
            <td>In Review</td>
        </tr>
              <tr>
            <th>Assignee</th>
            <td>Brian Chan</td>
        </tr>
              <tr>
            <th>Reporter</th>
            <td>Alan Huang</td>
        </tr>
                </table>
          </details></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

1 file changed, 30 insertions(+), 29 deletions(-)

**Comment by kevenleone** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3e5f7f5653...7fddd3aaab

**Comment by brianchandotcom** [comment]
@kevenleone can you make sure the code that is outputted is prettified? If not, then change the shell script to output code that is prettified. Thx.

**Pull request closed without merging**
