### PR TITLE
LPS-53392

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-53392](https://issues.liferay.com/browse/LPS-53392).<br><br>/cc @pei-jung @jorgeferrer @achaparro @lipusz @ugurcancetin

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by drewbrokke** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by jpince** [comment]
@drewbrokke service-builder failed twice, can you please take a look?
`     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:shopping:shopping-service:buildService'.`

**Comment by brianchandotcom** [comment]
@drewbrokke please resend. SB test broken.

**Pull request closed without merging**
