### PR TITLE
LPS-119450 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-119450

This is only for master.

@ruben-pulido

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure case is caused by another regression issue not related to the changes in PR.
See https://github.com/liferay-echo/liferay-portal/pull/1946
✔️ ci:test:stable - 21 out of 21 jobs passed
❌ ci:test:relevant - 71 out of 76 jobs passed in 1 hour 44 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c40b76fa97...a9bfb0269f

**Comment by brianchandotcom** [comment]
@ruben-pulido see bd8b3a303ddf17944471c5363a53ca27b697fb53

**Pull request closed without merging**
