### PR TITLE
LPS-104427 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-104427

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:test:seo

**Comment by austinchiang** [comment]
ci:reopen

**Comment by austinchiang** [comment]
Failures don't look related

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/272955ddac...f6967e99d8

**Pull request closed without merging**
