### PR TITLE
LPS-191298 Remove AssetVocabularyFinder

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://liferay.atlassian.net/browse/LPS-191298

@jkappler

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/12964

**Comment by yunlinsun** [comment]
@Tim-Cao @jkappler , conflicts in this PR, please fix and resend.

**Comment by yunlinsun** [comment]
ci:close

**Pull request closed without merging**
