### PR TITLE
LRQA-62917 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRQA-62917

This is for master and 7.3.x. Thanks!

@david-gutierrez-mesa

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure cases are caused by https://issues.liferay.com/browse/LPS-123172
See https://github.com/Tim-Cao/liferay-portal/pull/507
✔️ ci:test:stable - 2 out of 2 jobs passed
❌ ci:test:relevant - 4 out of 6 jobs passed in 1 hour 36 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/be44399db5...1ae283de04

**Comment by brianchandotcom** [comment]
@Tim-Cao 
I backported this to 7.3.x.

**Pull request closed without merging**
