### PR TITLE
LPS-27599 As a web content admin, I can use "Sort by" menu to sort articles

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
Hi @brianchandotcom, we fixed most of the issues, but there's one we cannot fix at the moment. And that is frontend-theme-product-app. It's compatible with GA2 (but is in master) and uses the old model, so it throws an exception when importing the lar.

cc:/ @juliocamarero, @marcoscv-work, @anthony-chu

**Comment by brianchandotcom** [comment]
int-* and modules-int* are throwing CI errors, please resend. Thx.

**Comment by jpince** [comment]
@jkappler looks like Web Content might be broken
wc
```
     [exec] 15:22:51,772 ERROR [http-nio-8080-exec-10][JDBCExceptionReporter:234] Column 'name' in field list is ambiguous
     [exec] 15:22:51,781 ERROR [http-nio-8080-exec-10][PortletRequestDispatcherImpl:261] org.apache.jasper.JasperException: com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: org.hibernate.exception.ConstraintViolationException: could not execute query
     [exec] org.apache.jasper.JasperException: com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: org.hibernate.exception.ConstraintViolationException: could not execute query
     [exec] 	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:440)
     [exec] 	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473)
     [exec] 	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377)
     [exec] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
     [exec] 	at com.liferay.portal.osgi.web.servlet.jsp.compiler.JspServlet.service(JspServlet.java:408)
     [exec] 	at com.liferay.portal.osgi.web.servlet.jsp.compiler.JspServlet.service(JspServlet.java:419)
     [exec] 	at com.liferay.portal.osgi.web.servlet.context.helper.internal.JspServletWrapper.service(JspServletWrapper.java:70)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:50)
     [exec] 	at com.liferay.portal.osgi.web.servlet.context.helper.internal.ServletContextHelperRegistrationImpl$RestrictPortletServletRequestFilter.doFilter(ServletContextHelperRegistrationImpl.java:447)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.registration.FilterRegistration.doFilter(FilterRegistration.java:121)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:45)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:70)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:117)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48)
     [exec] 	at com.liferay.portlet.PortletRequestDispatcherImpl.dispatch(PortletRequestDispatcherImpl.java:252)
     [exec] 	at com.liferay.portlet.PortletRequestDispatcherImpl.include(PortletRequestDispatcherImpl.java:102)
     [exec] 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.include(MVCPortlet.java:556)
     [exec] 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.include(MVCPortlet.java:572)
     [exec] 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.doView(MVCPortlet.java:157)
     [exec] 	at com.liferay.portal.kernel.portlet.LiferayPortlet.doDispatch(LiferayPortlet.java:302)
     [exec] 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.doDispatch(MVCPortlet.java:471)
     [exec] 	at com.liferay.journal.web.internal.portlet.JournalPortlet.doDispatch(JournalPortlet.java:1146)
     [exec] 	at javax.portlet.GenericPortlet.render(GenericPortlet.java:262)
     [exec] 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.render(MVCPortlet.java:291)
     [exec] 	at com.liferay.journal.web.internal.portlet.JournalPortlet.render(JournalPortlet.java:478)
     [exec] 	at com.liferay.portlet.FilterChainImpl.doFilter(FilterChainImpl.java:103)
     [exec] 	at com.liferay.portlet.ScriptDataPortletFilter.doFilter(ScriptDataPortletFilter.java:57)
     [exec] 	at com.liferay.portlet.FilterChainImpl.doFilter(FilterChainImpl.java:100)
     [exec] 	at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:64)
     [exec] 	at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:105)
     [exec] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
     [exec] 	at com.liferay.portal.osgi.web.servlet.context.helper.internal.ServletContextHelperRegistrationImpl$PortletServletWrapper.service(ServletContextHelperRegistrationImpl.java:427)
     [exec] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:50)
     [exec] 	at com.liferay.portal.osgi.web.servlet.context.helper.internal.ServletContextHelperRegistrationImpl$RestrictPortletServletRequestFilter.doFilter(ServletContextHelperRegistrationImpl.java:447)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.registration.FilterRegistration.doFilter(FilterRegistration.java:121)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:45)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:70)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:117)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48)
     [exec] 	at com.liferay.portlet.InvokerPortletImpl.invoke(InvokerPortletImpl.java:529)
     [exec] 	at com.liferay.portlet.InvokerPortletImpl.invokeRender(InvokerPortletImpl.java:604)
     [exec] 	at com.liferay.portlet.InvokerPortletImpl.render(InvokerPortletImpl.java:391)
     [exec] 	at com.liferay.portal.monitoring.internal.portlet.MonitoringInvokerPortlet.render(MonitoringInvokerPortlet.java:261)
     [exec] 	at org.apache.jsp.html.portal.render_005fportlet_jsp._jspService(render_005fportlet_jsp.java:1539)
     [exec] 	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
     [exec] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
     [exec] 	at com.liferay.portal.servlet.DirectRequestDispatcher.include(DirectRequestDispatcher.java:64)
     [exec] 	at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.doDispatch(ClassLoaderRequestDispatcherWrapper.java:78)
     [exec] 	at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.include(ClassLoaderRequestDispatcherWrapper.java:53)
     [exec] 	at com.liferay.portlet.PortletContainerImpl._doRender(PortletContainerImpl.java:671)
     [exec] 	at com.liferay.portlet.PortletContainerImpl.render(PortletContainerImpl.java:145)
     [exec] 	at com.liferay.portlet.SecurityPortletContainerWrapper.render(SecurityPortletContainerWrapper.java:126)
     [exec] 	at com.liferay.portlet.RestrictPortletContainerWrapper.render(RestrictPortletContainerWrapper.java:126)
     [exec] 	at com.liferay.portal.kernel.portlet.PortletContainerUtil.render(PortletContainerUtil.java:155)
     [exec] 	at com.liferay.portal.layoutconfiguration.util.velocity.TemplateProcessor.processMax(TemplateProcessor.java:178)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:497)
     [exec] 	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:389)
     [exec] 	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:378)
     [exec] 	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:270)
     [exec] 	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:262)
     [exec] 	at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:342)
     [exec] 	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:336)
     [exec] 	at org.apache.velocity.Template.merge(Template.java:328)
     [exec] 	at org.apache.velocity.Template.merge(Template.java:235)
     [exec] 	at com.liferay.portal.template.velocity.internal.VelocityTemplate.processTemplate(VelocityTemplate.java:112)
     [exec] 	at com.liferay.portal.template.AbstractSingleResourceTemplate.processTemplate(AbstractSingleResourceTemplate.java:78)
     [exec] 	at com.liferay.portal.layoutconfiguration.util.RuntimePageImpl.doProcessTemplate(RuntimePageImpl.java:368)
     [exec] 	at com.liferay.portal.layoutconfiguration.util.RuntimePageImpl.doDispatch(RuntimePageImpl.java:286)
     [exec] 	at com.liferay.portal.layoutconfiguration.util.RuntimePageImpl.getProcessedTemplate(RuntimePageImpl.java:95)
     [exec] 	at com.liferay.portal.kernel.layoutconfiguration.util.RuntimePageUtil.getProcessedTemplate(RuntimePageUtil.java:37)
     [exec] 	at com.liferay.application.list.taglib.display.context.logic.PanelAppContentHelper.writeContent(PanelAppContentHelper.java:82)
     [exec] 	at org.apache.jsp.application_005fcontent.page_jsp._jspService(page_jsp.java:207)
     [exec] 	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111)
     [exec] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
     [exec] 	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:411)
     [exec] 	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473)
     [exec] 	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377)
     [exec] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
     [exec] 	at com.liferay.portal.osgi.web.servlet.jsp.compiler.JspServlet.service(JspServlet.java:408)
     [exec] 	at com.liferay.portal.osgi.web.servlet.jsp.compiler.JspServlet.service(JspServlet.java:419)
     [exec] 	at com.liferay.portal.osgi.web.servlet.context.helper.internal.JspServletWrapper.service(JspServletWrapper.java:70)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:50)
     [exec] 	at com.liferay.portal.osgi.web.servlet.context.helper.internal.ServletContextHelperRegistrationImpl$RestrictPortletServletRequestFilter.doFilter(ServletContextHelperRegistrationImpl.java:447)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.registration.FilterRegistration.doFilter(FilterRegistration.java:121)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:45)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:70)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:117)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48)
     [exec] 	at com.liferay.portal.servlet.DirectServletPathRegisterDispatcher.include(DirectServletPathRegisterDispatcher.java:67)
     [exec] 	at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.doDispatch(ClassLoaderRequestDispatcherWrapper.java:78)
     [exec] 	at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.include(ClassLoaderRequestDispatcherWrapper.java:53)
     [exec] 	at com.liferay.taglib.util.IncludeTag.includePage(IncludeTag.java:380)
     [exec] 	at com.liferay.taglib.util.IncludeTag.include(IncludeTag.java:362)
     [exec] 	at com.liferay.taglib.util.IncludeTag.doInclude(IncludeTag.java:206)
     [exec] 	at com.liferay.taglib.util.IncludeTag.doEndTag(IncludeTag.java:88)
     [exec] 	at org.apache.jsp.layout.view.control_005fpanel_jsp._jspService(control_005fpanel_jsp.java:125)
     [exec] 	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111)
     [exec] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
     [exec] 	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:411)
     [exec] 	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473)
     [exec] 	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377)
     [exec] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
     [exec] 	at com.liferay.portal.osgi.web.servlet.jsp.compiler.JspServlet.service(JspServlet.java:408)
     [exec] 	at com.liferay.portal.osgi.web.servlet.jsp.compiler.JspServlet.service(JspServlet.java:419)
     [exec] 	at com.liferay.portal.osgi.web.servlet.context.helper.internal.JspServletWrapper.service(JspServletWrapper.java:70)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:50)
     [exec] 	at com.liferay.portal.osgi.web.servlet.context.helper.internal.ServletContextHelperRegistrationImpl$RestrictPortletServletRequestFilter.doFilter(ServletContextHelperRegistrationImpl.java:447)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.registration.FilterRegistration.doFilter(FilterRegistration.java:121)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:45)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:70)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:117)
     [exec] 	at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48)
     [exec] 	at com.liferay.portal.kernel.model.impl.BaseLayoutTypeControllerImpl.includeLayoutContent(BaseLayoutTypeControllerImpl.java:102)
     [exec] 	at com.liferay.portal.model.impl.LayoutImpl.includeLayoutContent(LayoutImpl.java:869)
     [exec] 	at com.liferay.portal.kernel.model.LayoutWrapper.includeLayoutContent(LayoutWrapper.java:452)
     [exec] 	at com.liferay.portal.action.LayoutAction.processLayout(LayoutAction.java:339)
     [exec] 	at com.liferay.portal.action.LayoutAction.doExecute(LayoutAction.java:178)
     [exec] 	at com.liferay.portal.action.LayoutAction.execute(LayoutAction.java:75)
     [exec] 	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:425)
     [exec] 	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:228)
     [exec] 	at com.liferay.portal.struts.PortalRequestProcessor.process(PortalRequestProcessor.java:170)
     [exec] 	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1913)
     [exec] 	at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:449)
     [exec] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
     [exec] 	at com.liferay.portal.servlet.MainServlet.callParentService(MainServlet.java:568)
     [exec] 	at com.liferay.portal.servlet.MainServlet.service(MainServlet.java:545)
     [exec] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
     [exec] 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:119)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:142)
     [exec] 	at com.liferay.portal.monitoring.internal.servlet.filter.MonitoringFilter.processFilter(MonitoringFilter.java:180)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:112)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:142)
     [exec] 	at com.liferay.portal.servlet.filters.secure.SecureFilter.processFilter(SecureFilter.java:303)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:112)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilter.doFilter(InvokerFilter.java:115)
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
     [exec] 	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:720)
     [exec] 	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466)
     [exec] 	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:391)
     [exec] 	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318)
     [exec] 	at com.liferay.portal.servlet.FriendlyURLServlet.service(FriendlyURLServlet.java:172)
     [exec] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
     [exec] 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:119)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:142)
     [exec] 	at com.liferay.portal.monitoring.internal.servlet.filter.MonitoringFilter.processFilter(MonitoringFilter.java:180)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:112)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:188)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:96)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:142)
     [exec] 	at com.liferay.portal.security.sso.ntlm.internal.servlet.filter.NtlmPostFilter.processFilter(NtlmPostFilter.java:107)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:112)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:188)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:96)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:142)
     [exec] 	at com.liferay.portal.servlet.filters.strip.StripFilter.processFilter(StripFilter.java:336)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:112)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:142)
     [exec] 	at com.liferay.portal.servlet.filters.gzip.GZipFilter.processFilter(GZipFilter.java:125)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:112)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:142)
     [exec] 	at com.liferay.portal.servlet.filters.secure.SecureFilter.processFilter(SecureFilter.java:303)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:112)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:142)
     [exec] 	at com.liferay.portal.servlet.filters.i18n.I18nFilter.processFilter(I18nFilter.java:275)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:112)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:142)
     [exec] 	at com.liferay.portal.servlet.filters.etag.ETagFilter.processFilter(ETagFilter.java:86)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:112)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:142)
     [exec] 	at com.liferay.portal.servlet.filters.autologin.AutoLoginFilter.processFilter(AutoLoginFilter.java:268)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:112)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:142)
     [exec] 	at com.liferay.portal.sharepoint.SharepointFilter.processFilter(SharepointFilter.java:88)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:112)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.processFilter(BaseFilter.java:142)
     [exec] 	at com.liferay.portal.servlet.filters.virtualhost.VirtualHostFilter.processFilter(VirtualHostFilter.java:260)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:112)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:188)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:96)
     [exec] 	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
     [exec] 	at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
     [exec] 	at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
     [exec] 	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:394)
     [exec] 	at com.liferay.portal.servlet.filters.urlrewrite.UrlRewriteFilter.processFilter(UrlRewriteFilter.java:65)
     [exec] 	at com.liferay.portal.kernel.servlet.BaseFilter.doFilter(BaseFilter.java:48)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDoFilter(InvokerFilterChain.java:207)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:112)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:168)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:96)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:168)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:96)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:188)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:96)
     [exec] 	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilter.doFilter(InvokerFilter.java:115)
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
     [exec] 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
     [exec] 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
     [exec] 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
     [exec] 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
     [exec] 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
     [exec] 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
     [exec] 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
     [exec] 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
     [exec] 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
     [exec] 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
     [exec] 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
     [exec] 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
     [exec] 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
     [exec] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [exec] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [exec] 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
     [exec] 	at java.lang.Thread.run(Thread.java:745)
     [exec] Caused by: com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: org.hibernate.exception.ConstraintViolationException: could not execute query
```
See full console log: https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/23924/console

**Comment by jkappler** [comment]
Thanks @jpince!!! Will take a look at it, that issue didn't show up in my manual tests

**Pull request closed without merging**
