### PR TITLE
LPS-74838 Use the WebKeys pattern

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:reopen

**Comment by rafaprax** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/97bdc79c10...6ee5ac9457

**Comment by brianchandotcom** [comment]
@rafaprax see 6ee5ac9457b63306fda259f694b7b58aa630532c thx

**Comment by rafaprax** [comment]
Thx @brianchandotcom

**Pull request closed without merging**
