### PR TITLE
Lps 73606

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by jpince** [comment]
ci:close

**Comment by jpince** [comment]
closing this pull while I investigate the failure, happened in both pulls

**Comment by jpince** [comment]
@shuyangzhou I see this error thrown in the [console](https://testray.liferay.com/reports/production/logs/test-1-3/1501617132745/test-portal-acceptance-pullrequest(master)/2324/functional-tomcat80-mysql56-jdk8/14/0/jenkins-console.txt.gz), and this test is passing in all other pull requests.
`     [exec] 21:10:56,711 ERROR [http-nio-8080-exec-6][LiferayMethodExceptionEventHandler:54] Unable to execute method processMax {exception=com.liferay.portal.kernel.portlet.PortletContainerException: com.liferay.portal.kernel.portlet.PortletContainerException: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: -1, className=com.liferay.portal.layoutconfiguration.util.velocity.TemplateProcessor}`
`     [exec] com.liferay.portal.kernel.portlet.PortletContainerException: com.liferay.portal.kernel.portlet.PortletContainerException: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: -1`

**Comment by shuyangzhou** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/50697

https://github.com/brianchandotcom/liferay-portal/pull/50697/commits/35577dcf71ae93523527f623ebb80d89f800fac0 should have it fixed.

Thanks @jpince !

**Pull request closed without merging**
