### PR TITLE
LPS-86129 Removes temporary SF supression

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9b1d062fe0...ab725c28b4

**Comment by brianchandotcom** [comment]
Merged with minor changes in upstream @jbalsas @izaera 

@preston-crary can you take a look at

modules/apps/frontend-js/frontend-js-loader-modules-extender-api/src/main/java/com/liferay/frontend/js/loader/modules/extender/npm/NPMResolverUtil.java

you're either going to think it's genius.. or it will make you cringe. But I pushed them to do something like it because they were writing the same class over and over again.

Thx

**Comment by izaera** [comment]
> you're either going to think it's genius.. or it will make you cringe. But I pushed them to do something like it because they were writing the same class over and over again.

:thinking: 

I'm not sure what looks strange in that class. The only problem with NPMResolvers is that they are not tight to OSGi lifecyle but to web context lifecycles (they should not appear unless a web context and its related NPM objects have been instantiated). 

That said, the new NPMResolverUtil could be made to work without caring about the webcontext lifecycle because you can obtain everything from the OSGi bundle. But, given that we already have a tracker for the other model (webcontext+bundle+npm object) I thought reusing it would be easier and safer than making another isolated setup.

But if you think we can refine it I'm open to feedback. I can think of more ways to fix it but I'm not sure of the final goals (I know we want to simplify it, but I'm unsure of how) so it's difficult for me to decide between the alternatives... :-)

**Comment by Preston-Crary** [comment]
@izaera NPMResolvedPackageNameRegistrar seems backwards to me.  It's something the bundle needs but isn't available until the bundle is active, it should be the other way around.

The problem is we don't have a good way to handle OSGi services from web and taglib modules since they operate in a different worlds.

@shuyangzhou and I have an idea of something we can do to make referencing dependencies from web modules easier.  It'll take some time to be sure it will work and more time to implement but in the end it could fix the resolution problems and require less code in web modules.

**Comment by izaera** [comment]
@Preston-Crary It's not really the `Bundle` what it depends on, it's the processing of the bundle by the `NPMRegistry` so, even though the bundle needs the `NPMResolver` it cannot use it until it has been processed by the `NPMRegistry`. This may look unstable, but in real life it should not be a problem because all `NPMResolver` uses are done far after the bundle has loaded. But I agree that it can lead to problems in corner cases. 

Let me explain precisely what the `NPMResolver` does to see if we can think of something better.

What we need is to resolve an "npm module name" (which is something like `a-fancy-framework/bootstrap`) to make the first call to `Loader.require`. So, every time someone wants to run Javascript, the first `require` call is kind of an special bootstrap call that "introduces" you in the Javascript world.

Why is that call special? Because `a-fancy-framework/bootstrap` is not fully defined. If you see the module name, it is made of a package name (a-fancy-framework) and the path to the module JS file. But packages are not defined unless they have a version. So, what we need to get into the Javascript world is something like `a-fancy-framework@1.2.0/bootstrap` which, this time, is fully defined.

The first approach we did was to specify the version numbers directly. So, when we had (in a JSP for example) something like:

```
<aui:script require="a-fancy-framework/bootstrap"/> 
```

we wrote:

```
<aui:script require="a-fancy-framework@1.2.0/bootstrap"/>
```

The problem with this was that, whenever you changed the version number of `a-fancy-framework` you needed to change all you JSP files. Also, 99% of the time `a-fancy-framework` was, in reality, the name of the very same project that hosted the JSP (which is equal to the OSGi bundle name by our convention). So, it looked very redundant and error prone.

Then, we decided to introduce the `NPMResolver` to make these module resolutions easier. Because the module name `a-fancy-framework/bootstrap` may mean different things depending on what bundle you are (this is because bundle A may use, say, version 1.2.0 of `a-fancy-framework` and bundle B may use a different one, say `2.1.0`) `NPMResolver` instances are not a singleton, but created by an OSGi factory that assigns precisely one `NPMResolver` per OSGi bundle. This is important, because people tends to think that `NPMResolver` is a singleton when it is not. And also, again: it cannot be (at least in this universe ;-P).

After that, because `NPMResolver`s where all over the place we created the concept of `npmResolvedPackageName`, which is an implicit JSP variable containing the resolved package name of the OSGi bundle hosting the JSP file. Obviously, because you need to automagically infer the OSGi bundle from the JSP (to obtain the `NPMResolver`; remember you cannot resolve npm module names without an starting bundle) the mechanism for `npmResolvedPackageName` has to derive the OSGi bundle from the request (the only global thing it has access to). Thus, we made the `NPMResolverJSBundleTracker and the `NPMResolvedPackageNameRegistrar`, which are the objects that wait for:

1) the WebContext (to attach the `npmResolvedPackageName` variable to it so that it can be retrieved from the JSP)
2) the JSBundle (not the OSGi Bundle)

Only when both are ready, we can assign an `NPMResolver` to a `WebContext` because before that we cannot access the information needed to make the resolution.

This worked for 99% of the scenarios, but then it came the next problem. Even though 99% of the time you want to refer to a JS module inside the same bundle where your code (JSP or Java) lives, sometimes infrastructure code wants to load JS modules not from the infrastructure bundles, but from the bundles calling the infrastructure. Other times, infrastructure code wants to load JS modules from its own modules. And is is very probable that, in a single class of JSP, the infrastructure code wants to refer to both type of modules (the ones it owns, and the ones owned by the calling bundle).

This could have been done simply by injecting the infrastructure `NPMResolver` in the infrastructure bundle. That way, infrastructure code would use its own `NPMResolver` to resolve its own JS modules and the `npmResolvedPackageName` to resolve the caller's JS modules. But because we don't want to have `NPMResolver`s hanging around, I created the `NPMResolverUtil` which leverages the `NPMResolverJSBundleTracker` (but not the `NPMResolvedPackageNameRegistrar` because this time we don't need the `WebContext`) to get the `NPMResolver` associated to the calling bundle. 

Of course, if you call `NPMResolverUtil` just after OSGi has made the bundle available, but before `NPMRegistry` has processed it to create the `JSBundle` the util won't be able to acces the `NPMResolver` (as it is not yet created) and the call will fail. However this is unlikely, because the API is designed so that it is called when it is used, not in advance (though I admit that someone may be tempted to cache resolutions in static fields and his setup may break). But we can always add a note in Javadoc explaining the lifecycle and also, a warning is dumped to the console.

Hope this "short & light" explanation makes it clearer to understand.

P.S: there's another possibility we haven't explored, which is making `JSBundle`s true OSGi services so that we can attach their lifecycle to the rest of the other services. I didn't want to do that from the beginning because there are a lot of npm objects and thought it could overload OSGi, but we can give it a try if we see it may help. Also, there are not so much `JSBundle` objects for OSGi to cope with them. The real explosion comes with `JSPackage`s namespace in first place and then, `JSModule`s which is orders of magnitude bigger than the `JSBundle` namespace.

To make this last part clearer, what you have is:

```
OSGi bundle <-1-------1-> JSBundle <-1------n-> JSPackage <-1-------m-> JSModule
```

Where usually `1000 > n > 10` and `1000 > n > 1` (but it could vary a lot).

**Comment by Preston-Crary** [comment]
@izaera thanks for the explanation.

> Of course, if you call `NPMResolverUtil` just after OSGi has made the bundle available, but before `NPMRegistry` has processed it to create the `JSBundle` the util won't be able to acces the `NPMResolver` (as it is not yet created) and the call will fail.

This is the main part we don't like, and it's not unique to NPM.  Any statically accessed service used in a web module may have this problem.

Another part we don't like is "pulling" based registration because each time you need something you have to ask for it which takes some CPU time.  It's much better if we can find a "pushing" based solution where the client code is given what it needs to execute it's purpose.

This is a good enough solution for short term and I do not want you to resolve this specifically for NPMRegistry, we want to find a general solution for this problem that can be applied to many other services in web modules.  I don't want to go into the details of our plan because we're not sure it'll even work yet.

**Comment by izaera** [comment]
@Preston-Crary I see :-).

I've also been thinking about this issue a lot of times. Perhaps having something similar to OSGi DS but attached to the WebContexts would make it.

For example, one could declare what OSGi services need to be attached to the WebContext in the BND files, or in Java classes and then the deployer grabs them and injects them as attributes. It could also make sure that the WebContext does not start unless those services are present.

It's not a complete solution, but most of the time people just need singleton services for their JSPs and right now the portal is full of internal `*Provider` classes that store services in a static field just for that purpose. We are not even using dynamism.

My two cents...

**Comment by Preston-Crary** [comment]
@izaera that's very similar to our idea, the main difference is we are looking at preventing web bundles from starting unless they have all their requirements.

**Pull request closed without merging**
