### PR TITLE
LPS-68497 Autogenerated

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by adolfopa** [comment]
@sergiogonzalez This pull was automatically closed because of some unrelated SF errors in `portal-impl`. Can you ci:reopen it?

Thanks!

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by brianchiu** [comment]
Failing poshi tests are firefox connection issues.

QA Engineering is investigating right now. See: https://issues.liferay.com/browse/LRQA-28169

**Comment by brianchandotcom** [comment]
@adolfopa can you resend but add the relevant .lfrbuild-portal files? This way I know it still works if deployed. Thx.

**Pull request closed without merging**
