### PR TITLE
LPS-69259

### PR DESCRIPTION
**Pull request by Ithildir**
Hi,
Please let this pull finish.

Thank you!

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:reopen

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merging.

**Comment by brianchandotcom** [comment]
@Ithildir please backport to ee-6.2.x and ee-6.1.x. Thx.

**Comment by Ithildir** [comment]
Done at https://github.com/brianchandotcom/liferay-portal-ee/pull/15223 and https://github.com/brianchandotcom/liferay-portal-ee/pull/15224.

**Pull request closed without merging**
