### PR TITLE
LPS-79709 SF

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @brianchandotcom!

As @izaera is on PTO, I'm sending #58320 over with the following changes:
- `Liferay-Bridge-JS-Submodules` renamed as `Liferay-JS-Submodules-Bridge`
- `Liferay-Top-Head-Authenticated-JS-Resources` and `Liferay-Top-Head-JS-Resources` renamed to `Liferay-JS-Resources-Top-Head-Authenticated` and `Liferay-JS-Resources-Top-Head`
- Deprecated `Liferay-Export-JS-Submodules`. This is the only key that existed already in `7.0`. It has been replaced in all of our code by `Liferay-Bridge-JS-Submodules`, but renaming it would break existing customer code. We're now logging an error and forbidding any usage in our own code of this key moving forward (through source-formatter).

Let me know if you think there's anything else we should do for this one.

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jpince** [comment]
@jbalsas I think you're right. @petershin can you please take a look? [console](https://test-1-20.liferay.com/job/test-portal-source-format/17/console)

**Comment by petershin** [comment]
@jpince - I think the SF test should have failed on this pull https://github.com/brianchandotcom/liferay-portal/pull/58313.  Will take a closer look and patch SF

**Comment by petershin** [comment]
@jpince - In the meantime, sent a fix for CI: https://github.com/brianchandotcom/liferay-portal/pull/58399

**Comment by brianchiu** [comment]
ci:close

**Comment by brianchiu** [comment]
@jbalsas 
Could you take a look at this? Some of the functional tests failed inconsistently in your pull (we didn't see that inconsistency in any other pull) because the "submit" button for pages changed from capitalized to uncapitalized.

Here's a screenshot. We didn't see this happen in any other pull, but let us know if you're certain that your pull did not cause this and we'll figure out what to do then.

before0

**Comment by jbalsas** [comment]
Hey @brianchiu, that's a good catch! It's caused by a change in the build process that's currently skipping the localization of language keys in some templates.

Could you point me to the failing tests so I can check when I resend? 

Thanks!

**Comment by jbalsas** [comment]
Hey @ithildir, @brianchiu, I've just ran `gradlew deploy` on `frontend-js-web` and the `:apps:frontend-js:frontend-js-web:replaceSoyTranslation` task is being properly called, so the keys are properly translated.

Any idea as to under which circumstances this could be failing to do so?

**Comment by brianchiu** [comment]
@jbalsas 
The functional test you could run or check against is PortalSmoke#Smoke, we we have run on multiple environments. However, this is very strange. The PortalSmoke#Smoke test failed on tomcat in the "ci test relevant" run, but in tomcat it passed in the "ci test" run. It failed in the "ci test" run on tcserver. It also did not fail on other environments even though the same test ran.

I'm not too sure right now what to make of it if the gradle task is being properly called.

cc @jpince

**Comment by jbalsas** [comment]
I've talked to @ithildir offline. He'll take a look when he can, because I wasn't able to reproduce locally but he should have a better sense on the task order and dependencies, so we can reorg the soy translation task so it always runs.

**Pull request closed without merging**
