### PR TITLE
LPS-81944 Validate upgrade package using the major and minor versions

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test

**Comment by achaparro** [comment]
ci:test

**Comment by achaparro** [comment]
ci:retest

**Comment by achaparro** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:stop

**Comment by jpince** [comment]
ci:stop

**Comment by jpince** [comment]
failures look unrelated (consistent with failures in upstream)

@achaparro a few things:
1. Feel free to @mention me if you're not sure about test failures, I'm happy to take a look
1. ci:test and ci:retest run the same tests. so just pick one :)
1. I stopped the tests because the failures are consistent with upstream. Traffic has been really high this week so I don't want to retest unnecessarily.

**Comment by achaparro** [comment]
Hi @jpince,

I wanted to just send ci:reopen but I typed the test commands.

Sorry about this :-(

I will take into account what you said

Thanks.

**Comment by jpince** [comment]
@achaparro oh, that makes more sense! no problem, I know you are working
quickly and ci failures that are not yours don't help.

**Pull request closed without merging**
