### PR TITLE
LPS-62745 Fix transitive dependencies for portal-store

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
OK, these failures are not related because this PR https://github.com/rotty3000/liferay-portal/pull/1132 also failed and it's completely unrelated.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/88f198c017...5ebc215c21

**Comment by brianchandotcom** [comment]
@rotty3000 it was a cache issue where the squid/CDN doesn't always populate

Fixed in 5ebc215c2126e224c954fe965e86d6522a2b8b5f

**Comment by rotty3000** [comment]
Glad you solved it! :)

**Pull request closed without merging**
