### PR TITLE
LPS-72252

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by jpince** [comment]
@hhuijser how did this pass in master but fail to compile in ee-7.0.x? Let us know how we can improve the PR tester to prevent this kind of issue from slipping through in the future

cc/ @brianwulbern

**Comment by jpince** [comment]
Hm, I see the pull https://github.com/brianchandotcom/liferay-portal/pull/48681 passed in master, but modules-compile is failing in both master and ee-7.0.x... this is very strange. We'll have to look into this further on our end.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by jpince** [comment]
@hhuijser we talked to BChan about this, he needed to publish the module after changing the dependency. Thanks also for sending in this fix.

**Pull request closed without merging**
