### PR TITLE
LPS-69728 system.packages.extra.mf

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @adolfopa

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
@sergiogonzalez looks like the unit test was just flaky, but now there is a merge conflict with https://github.com/liferay/liferay-portal/commit/13259c7e53f5801818d7d7c7d326955cd949e96c :(

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7777672b54...cd4c397c3e

**Pull request closed without merging**
