### PR TITLE
LPS-74801 Create basic services to allow creation of page templates

### PR DESCRIPTION
**Pull request by jkappler**
cc:// @ealonso

### CODE REVIEW

**Comment by jkappler** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@jkappler @ealonso please see my changes in upstream. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b01b9fda27...60d1482e03

**Pull request closed without merging**
