### PR TITLE
LPS-165007 Add List Type External Reference Code Exception

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-165007

### CODE REVIEW

**Comment by mateussgn** [comment]
Tests already passed https://github.com/liferay-objects/liferay-portal/pull/1270

**Comment by mateussgn** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@mateussgn we're in the process of autogenerating all the DuplicateListTypeExternalReferenceCode classes. Please talk to @sergiojimcos

**Comment by gabrielwas** [comment]
@brianchandotcom could you please merge this PR until we reach Sergio? (Spain holiday today and Brazil holiday tomorrow).
This PR is blocking some validations form our side.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/68e78f9e02...c091457a39

**Pull request closed without merging**
