### PR TITLE
LPS-62833 Translation to Spanish

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest hmm...

**Comment by brianchandotcom** [comment]
@jhinkey @sez11a fyi this will affect documentation

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/aa619941be...7493f84576

**Comment by JorgeFerrer** [comment]
For the record, I also sent a pull to Jim changing the description: https://github.com/jhinkey/liferay-portal/pull/321

**Comment by brianchandotcom** [comment]
Thx @JorgeFerrer I was thinking more User Guide and other stuff as well. Thx.

**Pull request closed without merging**
