### PR TITLE
master-vw-518

### PR DESCRIPTION
**Pull request by vicnate5**
https://issues.liferay.com/browse/LRQA-26387

### CODE REVIEW

**Comment by vicnate5** [comment]
Sent to 7.0.x https://github.com/brianchandotcom/liferay-portal/pull/42550

**Comment by kenjiheigel** [comment]
I think something related to the SPA timeout and the POSHI timeout happened here. I'll look into this.

**Comment by kenjiheigel** [comment]
The issue isn't related to this pull though.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
