### PR TITLE
Lps 64056

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
CC @hhuijser please see https://github.com/shuyangzhou/liferay-portal/commit/525162629ab8e980930e14eb738a1d3598daece1

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c96ccf56ee...2e5eaf3c17

**Comment by brianchandotcom** [comment]
@hhuijser can you add the check to make sure we only use ConfigurableUtil and not aQute.bnd.annotation.metatype.Configurable

Thx

**Comment by shuyangzhou** [comment]
@Preston-Crary already added the check at https://github.com/brianchandotcom/liferay-portal/commit/6c76aa48fade9674e321b8c158a02230eb4fe4f8

**Pull request closed without merging**
