### PR TITLE
LPS-171459 Add documentation link to date field

### PR DESCRIPTION
**Pull request by alessandromalves**
This is only for master
https://issues.liferay.com/browse/LPS-171459
cc.: @DiegoHu97

### CODE REVIEW

**Comment by alessandromalves** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/10668

x ci:test:stable - 27 out of 28 jobs passed
x ci:test:relevant - 171 out of 179 jobs passed in 1 hour 22 minutes

**Comment by alessandromalves** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9cce5a7c2e...a2dccee89b

**Comment by brianchandotcom** [comment]
@DiegoHu97 see ad61406fafe7924a440250f634e99c0dbb94d634 and a2dccee89b578cf764cc6bf288fc33d24a7fe759

**Pull request closed without merging**
