### PR TITLE
LRQA-18967 (2nd pull) Followup rename of FailedJobMessageUtil

### PR DESCRIPTION
**Pull request by pyoo47**
I also inserted some logic to prevent GithubJobMessageUtilTest from throwing an exception when attempting to download a source job.

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
i got these ones unstuck. One of our servers was causing this to stall.

Results should be up soon.

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/358bd216bd...9e2195cecc

**Comment by brianchandotcom** [comment]
@pyoo47 I renamed it to GitHub*, not Github*.

**Pull request closed without merging**
