### PR TITLE
LPS-58329 Increase timeout for Wildfly deployment scanner

### PR DESCRIPTION
**Pull request by alee8888**

### CODE REVIEW

**Comment by alee8888** [comment]
@brianchandotcom 
After discussing with @mhan810 we need to increase the deployment scanner another 60 seconds because we believe Wildfly is shutting down the webapp before deployment is finished which is causing the random Wildfly errors we have been seeing on the PR tester.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b62b7a73e1...48e421f698

**Comment by alee8888** [comment]
@ZoltanTakacs Can you please backport?

**Comment by sharonchoi** [comment]
investigating poshi failures: https://issues.liferay.com/browse/LRQA-22762

**Pull request closed without merging**
