### PR TITLE
pull-request-125

### PR DESCRIPTION
**Pull request by mikemanyoung**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by lawrence-lee** [comment]
Hey @brianchandotcom and @brianchiu, I think these errors are related to LPS-50479. LPS-50479 did not go through the pull request tester and therefore wasn't caught by CI.

**Comment by brianchiu** [comment]
@lawrence-lee @brianchandotcom 

Looking at this pull, Shuyang is fixing them.
https://github.com/brianchandotcom/liferay-portal/pull/23211

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c1d6364333...265abaf3a5

**Pull request closed without merging**
