### PR TITLE
LPS-75320 Move MBUserStats into module

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/837a099ed0...404aeea9be

**Comment by brianchandotcom** [comment]
Bravo @adolfopa @sergiogonzalez 

Can you guys backport 21ad70d53d7ebf719398aca8a6b7dc400f54a1aa and 832d4007087e2fff996ecd8ac672f67f2f3d2ec3 to 7.0.x since those are bug fixes?

I also backported the test change in 62e44af8b14f5091af3f451c7d3052d1d22a5df2 just to simplify things in the future.

Thx

**Comment by brianchandotcom** [comment]
@adolfopa @sergiogonzalez I just saw that a bunch of tests broke from this pull.. sorry, need to revert! Please resend.

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/693eb2aac0...693eb2aac0

**Comment by brianchandotcom** [comment]
@pyoo47 how come this only ran 81 jobs? What about all the modules-int* tests? In any case, I'm merging this... but smells fishy..

**Comment by brianchandotcom** [comment]
@pyoo47 I know why it did that.. 

@sergiogonzalez can you resend this? Basically, the "ci:retest" tested nothing, because the commits were already in and reverted, so it saw no changes, hence, it only tested functional tests.

Perhaps you can squash all the commits into one, or resend the pull. I want to be careful with this one because it showed modules-int* errors previously. I have a feeling it really is causing an error.

**Pull request closed without merging**
