### PR TITLE
LPS-74323 SF

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:reopen

**Comment by vicnate5** [comment]
ci:retest

**Comment by jpince** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a5536418c8...cd4fe0a102

**Pull request closed without merging**
