### PR TITLE
LPS-58575 Use Bundle by default but allow overriding

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by csierra** [comment]
ci:retest

**Comment by csierra** [comment]
@marcellustavares 

these errors are not related to this are they?

**Comment by marcellustavares** [comment]
I don't think so @csierra, CI is unstable today.

**Comment by csierra** [comment]
:pensive:

**Comment by brianchandotcom** [comment]
@marcellustavares this pull is good, except for the naming of "ServiceRegistrations"

It's very confusing to have a class called ServiceRegistrations with a List<ServiceRegistration> serviceRegistrations

Please resend. Thx.

**Comment by csierra** [comment]
I'll change it and resend

**Comment by marcellustavares** [comment]
Thanks @csierra

**Comment by csierra** [comment]
please see https://github.com/brianchandotcom/liferay-portal/pull/35483

Thx guys!

**Pull request closed without merging**
