### PR TITLE
Lps 74115

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
More upgrade client class path issue. @mhan810 @david-truong @achaparro

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bee7da1663...8c59baa4f2

**Comment by brianchandotcom** [comment]
@tinatian @shuyangzhou see 8c59baa4f236aa3dcdcbca8f67e912b766e19ad5

thx

**Pull request closed without merging**
