### PR TITLE
LPS-148292 Temporarily ignore test classes that are causing other integration tests to fail due to bad cleanup

### PR DESCRIPTION
**Pull request by vicnate5**
@achaparro This is causing cascading failures in integration tests https://issues.liferay.com/browse/LPS-148292

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bbfc8a6bf3...be901cca03

**Comment by brianchandotcom** [comment]
@achaparro is DataGuard not on for this test? please coordinate with SZ to see why DataGuard is not working.

@shuyangzhou probably because it's going through multiple databases?

**Comment by shuyangzhou** [comment]
@achaparro Not sure what is failing. But DataGuard works at hibernate level, DatabasePartition works at jdbc level. Depending on the test logic, it is very possible they mismatch each other causing leftovers.

I need reproduce steps to understand what is not cleaned up.

**Pull request closed without merging**
