### PR TITLE
LPS-68672 Manually copy translations for Social Networking

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @jonathanmccann

**Comment by kenjiheigel** [comment]
Not sure what happened.. but I think some of the builds timed out.

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@jonathanmccann here's a script I wrote so I don't have to manually do it. I called it merge_language_properties.sh

```
#!/bin/sh

DESTINATION_DIR=~/dev/projects/github/liferay-portal/modules/apps/web-experience-management/staging/staging-lang/src/main/resources/content

SOURCE_DIRS=(portal-impl/src/content)

for SOURCE_DIR in ${SOURCE_DIRS[@]}
do
	SOURCE_DIR=~/dev/projects/github/liferay-portal/${SOURCE_DIR}

	for file in ${SOURCE_DIR}/Language_*.properties
	do
		fileName="${file##*/}"

		echo "" >> ${DESTINATION_DIR}/${fileName}

		cat ${DESTINATION_DIR}/${fileName} ${SOURCE_DIR}/${fileName} > ${DESTINATION_DIR}/${fileName}.new

		mv ${DESTINATION_DIR}/${fileName}.new ${DESTINATION_DIR}/${fileName}
	done
done
```

After I run it, I then run "ant builld-lang" or "gradlew buildLang" on the respect components to remove the left overs.

**Comment by jonathanmccann** [comment]
Thanks for the script!

**Pull request closed without merging**
