### PR TITLE
[TECHNICAL-SUPPORT] LPS-73961

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @mbowerman

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 what happened here, looks like master tried connecting to a dead slave?

**Comment by brianchandotcom** [comment]
Merged.

**Comment by brianchandotcom** [comment]
@mbowerman @jonathanmccann wow, I remeber writing that description 15 years ago.. when there was still dial up

**Comment by pyoo47** [comment]
@brianchandotcom All the slaves on test-1-9 disconnected and wouldn't reconnect until we restarted the jenkins master.

**Pull request closed without merging**
