### PR TITLE
Lps 74849

### PR DESCRIPTION
**Pull request by shuyangzhou**
@hhuijser not sure how can you SF this?

@brianchandotcom please release a new kernel, so that I can apply it to journal.
And we can squash this release into the petra kernel release.

### CODE REVIEW

**Comment by hhuijser** [comment]
@shuyangzhou

Just to make sure my understanding of this new method is correct.

We could use this in following cases:

1. Chained concats with 3 values

Example: https://github.com/liferay/liferay-portal/blob/master/modules/apps/collaboration/document-library/document-library-web/src/main/java/com/liferay/document/library/web/internal/portlet/action/GetFileActionHelper.java#L210-L211

2. Use of `+` operator with more than 3 values

Example: https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/upgrade/v6_1_0/UpgradeImageGallery.java#L949-L951

3. Straightforward StringBundler operations of the following format:
```
StringBundler sb = new StringBundler(4);

sb.append(a);
sb.append(b;
sb.append(c);
sb.append(d);

String s = sb.toString();
```

**Comment by shuyangzhou** [comment]
@hhuijser the difference is about array creation. The new method is using varargs, which is actually a syntax sugar for auto array creation.
So the key point is, if you don't already have a SB object and you have all the Strings available, the new method is better. (Because you can save a SB object creation)
However if you already have a SB object, that means you already have an internal array, it will be wasteful to let var-args create another one. So just append every String into the exist SB.

But when it comes to 1 ~3 strings, a plain concat() is still the best, no need to change to use the new method.

For your example, 1) does not need a change. 2) needs the change, 3) also needs the change (since you have a,b,c,d all available already)

**Comment by hhuijser** [comment]
Understood, thanks @shuyangzhou

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/01bf3894a9...db55dd6dce

**Pull request closed without merging**
