### PR TITLE
LPS-118979 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-118979

This is only for master.

@pavel-savinov

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure case is not related to changes in PR.
See https://github.com/liferay-echo/liferay-portal/pull/1905
✔️ ci:test:stable - 21 out of 21 jobs passed
❌ ci:test:relevant - 103 out of 105 jobs passed in 1 hour 47 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/dfba5b02c8...4326b520cc

**Comment by brianchandotcom** [comment]
@pavel-savinov see 4326b520

**Pull request closed without merging**
