### PR TITLE
[TS] LPS-93033 Increase the character limit for the clientIP column in the AUDIT_AUDITEVENT table from 75 to 255

### PR DESCRIPTION
**Pull request by achaparro**
cc/ @peterpetrekanics @ericyanLr

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:test:upgrade @vicnate5 please run ci:test:relevant if needed

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/271492d866...4ff5828730

**Pull request closed without merging**
