### PR TITLE
LPS-70564 | master

### PR DESCRIPTION
**Pull request by vicnate5**
@diogo-lins

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@thiago-rocha @diogo-lins 
Entries in 

modules/apps/forms-and-workflow/dynamic-data-lists/dynamic-data-lists-form-web/src/main/java/com/liferay/dynamic/data/lists/form/web/internal/display/context/util/DDMExpressionFunctionMetadataHelper.java

Used to be sorted, but not anymore. Please resend.

**Comment by vicnate5** [comment]
@leoadb

**Comment by leoadb** [comment]
@diogo-lins @rafaprax could you help me with this? Thanks!

**Comment by leoadb** [comment]
@vicnate5 Thanks to let me know!

**Comment by rafaprax** [comment]
resent https://github.com/brianchandotcom/liferay-portal/pull/48742

**Pull request closed without merging**
