### PR TITLE
LPS-68934 buildLang

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@marcellustavares test failures in CI. Please resend.

SourceFormatterTest.testSourceFormatter

**Comment by marcellustavares** [comment]
resent to https://github.com/brianchandotcom/liferay-portal/pull/44360

**Pull request closed without merging**
