### PR TITLE
LPS-61420

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:retest

**Comment by hhuijser** [comment]
@Ithildir, not sure what's going on here... code you added is triggering the fail: 9155af17edb54c10be961a327c298dfa66fc32bd, but I don't really know what part of my changes is causing that...

**Comment by Ithildir** [comment]
Hi @hhuijser!
It's because you changed the `.ftl` files in `frontend-theme-user`, and so CI is trying to build the theme again. We use the Gulp [liferay-theme-tasks](https://github.com/liferay/liferay-theme-tasks) to build themes, but CI can't run Node because of bandwidth problems.

Just run `gradlew assemble` in `modules/apps/platform/frontend/frontend-theme`, this should regenerate the `.task-cache` dirs :blush:

**Comment by brianchandotcom** [comment]
@hhuijser please resend? Thx.

**Pull request closed without merging**
