### PR TITLE
LPS-61297

### PR DESCRIPTION
**Pull request by mikakoivisto**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9caf334942...cd8cc73f90

**Comment by brianchandotcom** [comment]
@sharonchoi @brianchiu can you look into this random Recyclebin  bug? I've seen it a few times now.

**Comment by brianchiu** [comment]
@sharonchoi
Can you look into this? It "feels" like the test is moving too fast. It's supposed to be in the document folder already when it tries the click the plus sign, but based on screenshots it's still on at doc and med root.

**Comment by sharonchoi** [comment]
@brianchandotcom @brianchiu sure, will do.

**Comment by sharonchoi** [comment]
Pushed: https://github.com/brianchandotcom/liferay-portal/pull/33339

**Pull request closed without merging**
