### PR TITLE
Lps 61895

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/59d209fb01...2d71f7332f

**Comment by shuyangzhou** [comment]
@brianchandotcom have you publish the new version of ServiceBuilder? It needs to be published and used, otherwise the SB test will fail for other pulls.

**Comment by brianchandotcom** [comment]
oh.. no. I ahven't.
 on it now.

**Comment by brianchandotcom** [comment]
Done. Pushed up.

**Pull request closed without merging**
