### PR TITLE
LPS-93031

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by SamZiemer** [comment]
Hi @adolfopa, in your commit here: https://github.com/brianchandotcom/liferay-portal/pull/70690/commits/dbe5219c3a82962699f0ea09c08cde346e417879 there are some issues.

#1 https://github.com/brianchandotcom/liferay-portal/pull/70690/commits/dbe5219c3a82962699f0ea09c08cde346e417879#diff-a7f27e83f72447d20af42b5bcaebb4d8R105 You are testing to see if user is null, but the object name is owner, not user.

#2 https://github.com/brianchandotcom/liferay-portal/pull/70690/commits/dbe5219c3a82962699f0ea09c08cde346e417879#diff-fd376cea64b69f9f915fdf85b6aa161cR42 and https://github.com/brianchandotcom/liferay-portal/pull/70690/commits/dbe5219c3a82962699f0ea09c08cde346e417879#diff-5e62bf38d0661a0fa03db258c6b21f54R256 I initially went with this route, however, the serviceContext has a companyId of 0, so this will always throw an error when attempting to get the default user for companyId = 0. The only thing we have at this stage that has a companyId is the group.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@adolfopa @SamZiemer I decided not to merge this after reading the commetns by @SamZiemer 

Please resend @adolfopa thx.

**Comment by adolfopa** [comment]
Sorry for the mess @SamZiemer 

See https://github.com/brianchandotcom/liferay-portal/pull/70887

**Pull request closed without merging**
