### PR TITLE
LPS-76972 Packageinfo

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@ealonso I haven't seen this error anywhere else? @petershin?

Can you resend @ealonso

**Comment by petershin** [comment]
@brianchandotcom - I've never seen this before.  I asked QA to take a look too.

**Comment by michaelhashimoto** [comment]
Hi @ealonso @petershin @brianchandotcom,

After looking into this a little bit we found that it is likely due to this class:
[modules/apps/web-experience/fragment/fragment-entry-processor/fragment-entry-processor-editable-test/src/testIntegration/java/com.liferay.fragment.entry.processor.editable.test/FragmentEntryProcessorEditableTest.java](https://github.com/ealonso/liferay-portal/blob/1cedff62144a7120521d048ad8844a880788e24c/modules/apps/web-experience/fragment/fragment-entry-processor/fragment-entry-processor-editable-test/src/testIntegration/java/com.liferay.fragment.entry.processor.editable.test/FragmentEntryProcessorEditableTest.java)

Specifically the folder named: **com.liferay.fragment.entry.processor.editable.test**

It is due to the logic that we use to break up the integration tests into groups found here:
https://github.com/liferay/liferay-portal/blob/81b2dff/build-test.xml#L2699

We are currently looking for "com/" to find the class name, and since the first folder doesn't equal "com" it is throwing a StringIndexOutOfBoundsException. 

Please let me know if you have any questions.

Thanks!

**Comment by ealonso** [comment]
Hey @petershin @michaelhashimoto @brianchandotcom,

Thnaks for your work, it was my mistake, I fixed it and resend here: https://github.com/brianchandotcom/liferay-portal/pull/54320

Regards,
Eudaldo.

**Pull request closed without merging**
