### PR TITLE
LPS-102456 Set the mvcc version to avoid stale object state exception.

### PR DESCRIPTION
**Pull request by jkappler**
Hey @brianchandotcom, same fix as LPS-102076

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso, @Preston-Crary

**Comment by jkappler** [comment]
cc:// @jpince

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/292cf18687...ef02195dcd

**Comment by brianchandotcom** [comment]
awesome!

**Pull request closed without merging**
