### PR TITLE
LPS-70529 | master

### PR DESCRIPTION
**Pull request by vicnate5**
@thiago-rocha @diogo-lins

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:reopen

**Comment by vicnate5** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@thiago-rocha this seems out of place

```
 * @param actions
 * @param conditions
 * @param deleteIcon
 * @param logicalOperator
 * @param plusIcon
 * @param strings
 * @param invalid
```

Please resend? Thx.

**Comment by thiago-rocha** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/47382

**Pull request closed without merging**
