### PR TITLE
LPS-142380 Use ReflectionUtil to keep the exception instead of wrapping it in a RuntimeException; in this change's case, the UI won't be able to show the error message if the exception is rethrown as RuntimeException.

### PR DESCRIPTION
**Pull request by jgarcialr**
- LPS-142380 Add validation in ExpandoColumnLocalServiceImpl
- LPS-142380 Add test
- LPS-142380 Use proper method to add the attribute with default value to make sure validation is executed before creating the value
- LPS-142380 Show error message on UI
- LPS-142380 buildLang
- LPS-142380 SV
- LPS-142380 SF, inline
- LPS-142380 SF, remove unnecessary try-rethrow
- LPS-142380 Use ReflectionUtil to keep the exception instead of wrapping it in a RuntimeException; in this change's case, the UI won't be able to show the error message if the exception is rethrown as RuntimeException.
- LPS-142380 SV

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@crodriguezy @jgarcialr ok, this is better

But now, let's remove the default constructor for ValueDataException

I only want static classes inside ValueDataException

Thx

**Comment by jgarcialr** [comment]
Hi @brianchandotcom ,

Following the pattern, I'll make the constructor private as in UserEmailAddressException.

I'll test and resend the PR

**Comment by crodriguezy** [comment]
Next PR: https://github.com/brianchandotcom/liferay-portal/pull/122803

**Pull request closed without merging**
