### PR TITLE
LPS-52534

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
This one should be better :)

**Comment by hhuijser** [comment]
Hey @shinnlok,

Hmm, okay. Does that mean we should exclude any logic in SF that is JDK7 specific for certain modules?

**Comment by hhuijser** [comment]
Why do we keep io-delta compatible with 1.6?

**Comment by shinnlok** [comment]
The dependency has to be compatible with 1.6 because 6.2 uses it. Some of our vms are still on 1.6.

**Pull request closed without merging**
