### PR TITLE
LPS-113598 Deprecate `Liferay.Widget`

### PR DESCRIPTION
**Pull request by wincent**
Manual forward from: https://github.com/wincent/liferay-portal/pull/299

[CI failed spuriously](https://github.com/wincent/liferay-portal/pull/299#issuecomment-634588795) there, but obviously unrelated because this is a comment-only change.

Original message follows.

---

There are currently no usages of `Liferay.Widget` so mark this file as deprecated.

Confirmed this by searching with `git grep -w Liferay.Widget` and `git grep -w liferay-widget`, and used `git log -G'\bLiferay.Widget\b' -p` to determine that the last actual usage was removed in cad2339833.

### CODE REVIEW

**Comment by wincent** [comment]
ci:reopen

**Comment by wincent** [comment]
cc @julien

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9836a0a358...5c16576804

**Pull request closed without merging**
