### PR TITLE
LPD-24836

### PR DESCRIPTION
**Pull request by tinatian**
FYI @shuyangzhou

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c8f62791b2...415db5d398

**Comment by brianchandotcom** [comment]
@tinatian @julschong this included a breaking change bnd.bnd change. Don't we need to add that special commit? So SF doesn't break?

**Comment by marco-leo** [comment]
@brianchandotcom yes it does. We should have an SF rule for this

**Comment by brianchandotcom** [comment]
@marco-leo we have an SF rule for this, but the recent CI "conservation" of resources removed it.

**Comment by marco-leo** [comment]
We have to add it back. @pyoo47

**Comment by julschong** [comment]
@brianchandotcom Hi Brian,
breaking change commits were added in these two moving commits: [bba1303](https://github.com/brianchandotcom/liferay-portal/pull/150468/commits/bba1303e117a746068afb0404ee1989031f52f8a) and [9627a15](https://github.com/brianchandotcom/liferay-portal/pull/150468/commits/9627a15d1d663e1bb6095c4fc42b94c4e6c51c8e)
Is this what you are referring to?

**Comment by brianchandotcom** [comment]
@julschong my bad. I see it now.

False alarm @pyoo47 @marco-leo

**Pull request closed without merging**
