### PR TITLE
LPS-160370 DB Partitioning: disable cache for system company

### PR DESCRIPTION
**Pull request by achaparro**
@tinatian I added a test to cover the new use case. Sent to Brian since it is critical in LXC in this moment

### CODE REVIEW

**Comment by achaparro** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@achaparro I sent this to @shuyangzhou at https://github.com/shuyangzhou/liferay-portal/pull/10800

Disabling the system company seems like it could have some performance issues.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3854188c49...fd2f0e7010

**Comment by brianchandotcom** [comment]
@achaparro my bad. I see that @tinatian is on this.

BUT, I want to make sure we are now fixing all those cases so that we can remove Tina's hack in f5ef55545e7886c665caa186a1da150dbbc9e12d because this is going to hurt performance. Thx.

**Pull request closed without merging**
