### PR TITLE
LPS-96738 version endpoints

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f717e37ac2...a1a9991d01

**Comment by brianchandotcom** [comment]
@nhpatt see upstream for my changes thx.

**Comment by brianchandotcom** [comment]
@nhpatt No way to support both versions hey?

**Comment by nhpatt** [comment]
Thanks! :)

@brianchandotcom I discussed it with Pablo (we could just expose one endpoint per version or add the version as a property) but it doesn't fit GraphQL versioning (basically don't ever update versions). GraphQL versioning has to be incremental so exposing the latest method seems the best fit.

**Pull request closed without merging**
