### PR TITLE
LPS-165185 Clone all inner values

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-165185

@victorg1991

### CODE REVIEW

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/9865

:heavy_check_mark: ci:test:stable - 27 out of 27 jobs passed
:x: ci:test:relevant - 124 out of 169 jobs passed in 1 hour 42 minutes

**Comment by ozysouza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/569bdc90f1...92161bfdbc

**Comment by brianchandotcom** [comment]
@victorg1991  see b36f88ec7896e840190018ca27b0af60f66cb92c

**Pull request closed without merging**
