### PR TITLE
LPS-121753 Drop IE support from build in backportable way

### PR DESCRIPTION
**Pull request by wincent**
Rebase of: https://github.com/brianchandotcom/liferay-portal/pull/95335 (to solve a merge conflict)

Ran `ci:test:sf` (it is complaining about a `.java` file I didn't touch, so I ignored that), skipped the other CI. The only commit that needed redoing was this one, so I eyeballed the before and after to confirm the changes are equivalent:

- Original version (from #95335): https://github.com/brianchandotcom/liferay-portal/pull/95335/commits/4d1e81056311349af406c3b7586403c36368b73d
- Updated version (from this PR): https://github.com/brianchandotcom/liferay-portal/commit/ec39b00fe6ce20092450f277eda1fa35e10647f6

---

> Forwarded from: [liferay-frontend#447](https://github.com/liferay-frontend/liferay-portal/pull/447) (Took 1 `ci:forward` attempt in 2 hours 59 minutes)
> 
> @wincent
> @liferay-frontend
> 
> Original pull request comment:
> This is a copy of [liferay-frontend#441](https://github.com/liferay-frontend/liferay-portal/pull/441) because for some reason, the pull request tester appears to be ignoring commands on it. Going to try again here...
> 
> > ℹ️ Believe it or not, **this one is safe to backport to 7.3** because we have implemented branch-specific behavior as described [in this PR](https://github.com/liferay/liferay-frontend-projects/pull/214).
> 
> Previously, we used to transpile all of our ".js" files to be ES5 compatible. That's a very old standard (5.1 was finalized in 2011), and goes significantly beyond what we strictly needed to in order to meet the requirements of our compatibility matrix.
> 
> In this commit, we not only drop support for IE, but we make our Babel config very strictly match exactly what is in the compatibility matrix. As an example of the gains, take frontend-js-web as an example, we see this change strip off about 1,305 lines of code, and 69,752 characters (pre-gzip):
> 
> Before:
> 
> ```
> $ cloc build/node/packageRunBuild/resources
> 
> -------------------------------------------------------------------------------
> Language                     files          blank        comment           code
> -------------------------------------------------------------------------------
> JavaScript                     139           1589           2345           8142
> 
> $ wc build/node/packageRunBuild/**/*.js | tail -1
>    12005   44520  580077 total
> ```
> 
> After:
> 
> ```
> $ cloc build/node/packageRunBuild/resources
> 
> -------------------------------------------------------------------------------
> Language                     files          blank        comment           code
> -------------------------------------------------------------------------------
> JavaScript                     139           1407           2529           6836
> 
> $ wc build/node/packageRunBuild/**/*.js | tail -1
>    10701   39260  510325 total
> ```
> 
> Here is a concrete example of a file, `side_navigation.es.js`:
> 
> * Before: https://gist.github.com/wincent/be6203a1e3032251a8974bcc633d3751
> * After: https://gist.github.com/wincent/b2b073003ce91b9256e1b86bbb1b8ac2
> * Diff: https://gist.github.com/wincent/408131bf38c070b10574e976930ad0aa
> 
> The major version bump in `@liferay/npm-scripts` is because in a very narrow _technical_ sense, it is a "breaking change" (ironically, only on 7.4). This is because it requires us to add one .babelrc.js for the benefit of analytics-client-js where we continue to want IE support to be in place, even though it lives on 7.4. The file will be harmless no-op on 7.3, so nothing will break on it.
> 
> [Release notes for `@liferay/npm-scripts` v34.0.0](https://github.com/liferay/liferay-frontend-projects/releases/tag/npm-scripts%2Fv34.0.0)
> 
> Why so many commits? These correspond to manual changes that were made in response to testing. We had over 360 places where we were using `const` variables before declaring them. This worked before because Babel turned them all into `var`, which doesn't care about the so-called "Temporal Dead Zone". But now that the browser is seeing all these `const`, the use-before-definition sloppiness turns into a `ReferenceError`. So I turned on the ESLint `no-use-before-define` rule and then went hunting down all the errors, and made one commit per OSGi module just in case anything goes wrong (ie. so that we can do a granular revert of the affected module).
> 
> ### ✔️ ci:test:stable - 14 out of 14 jobs passed
> ### ✔️ ci:test:relevant - 211 out of 215 jobs passed in 2 hours 56 minutes
> Click here for more details.
> ### ✔️ ci:test:sf - 1 out of 1 jobs passed in 5 minutes
> Click here for more details.

### CODE REVIEW

**Comment by wincent** [comment]
Waiting for the bot to autoclose this one so I can `ci:reopen` it, but it must be asleep... 💤

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/af2be6bd6c...d3c0d99e0d

**Comment by brianchandotcom** [comment]
Haa.. the bot must be asleep @pyoo47 ?

I merged this @wincent

**Comment by brianchandotcom** [comment]
@wincent not backported of course.

**Comment by wincent** [comment]
@brianchandotcom: This one actually is safe to backport. `@liferay/npm-scripts` will only apply the "no-IE" build settings on 7.4/master, and continue using the "legacy" settings on older branches.

All the "fix no-use-before-define violations" commits are safe to backport too, although you could drop any of them that don't apply cleanly. The fix lint warnings that are turned on on 7.4/master, but they won't change the functionality of the code on older branches.

**Pull request closed without merging**
