### PR TITLE
LPS-92942 Revert 1099077d76de999aeaa96c31acc913efd86ed305, set new template id only when already got old template columns configuration, because old columns settings depend on the template id property

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@pavel-savinov can you add a test?

@hhuijser see SF that broke logic. Thx.

**Pull request closed without merging**
