### PR TITLE
LPS-71615 SF

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
@brianchandotcom Could you please take a look at this pull? Test fails have nothing to deal with since they all passed on https://github.com/ealonso/liferay-portal/pull/860
Thanks!

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@ealonso @pavel-savinov this looks good, but can you resend with a few minor changes

1.) Rename groupFriendlyURLInstance to groupFriendlyURL in FriendlyURLServlet (compiled file for me)

2.) Let's rename GroupFriendlyURL to SiteFriendlyURL since it's now in the "site" package.

I searched for all service.xml in modules/** and the modules all start with a prefix, with the exception of Chat. So let's follow the majority and not Chat in this case.

Thx guys. This is much better than modifying core.

**Pull request closed without merging**
