### PR TITLE
LPS-110536 Using custom empty results message

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
sf failures not related

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/87b471fdb6...9aec7893b2

**Comment by brianchandotcom** [comment]
@4lejandrito can you send a follow up pull and rephrase "Great job!" That sounds like we're in kindergarten. Can you make it more professional and to the point. Also see 9aec7893b27c40cf3aeee87905eaaa99191d9544. Thx.

**Pull request closed without merging**
