### PR TITLE
LPS-94161 As a Developer, I can implement Index Definitions for automatic creation of application driven indexes

### PR DESCRIPTION
**Pull request by arboliveira**
**❌ ci:test:search - 17 out of 19 jobs passed in 1 hour 23 minutes 12 seconds 633 ms**
https://github.com/arboliveira/liferay-portal/pull/726#issuecomment-484380531

----

1 failure, but not really; this pull actually introduces a brand new API module, `portal-search-elasticsearch6-spi` with extension points. I assume `baseline` can only be satisfied after the first  snapshot gets published? Let me know if there's any steps I should take on my side.

```
     [exec] Execution failed for task ':apps:portal-search-elasticsearch6:portal-search-elasticsearch6-spi:baseline'.
     [exec] > Could not resolve all files for configuration ':apps:portal-search-elasticsearch6:portal-search-elasticsearch6-spi:baseline'.
     [exec]    > Could not find any matches for com.liferay:com.liferay.portal.search.elasticsearch6.spi:(,3.0.0) as no versions of com.liferay:com.liferay.portal.search.elasticsearch6.spi are available.
```

----

_[Story] As a Developer, I can implement Index Definitions for automatic creation of application driven indexes_
https://issues.liferay.com/browse/LPS-94161

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:reopen

**Comment by jpince** [comment]
@arboliveira the snapshot is created during ant all, so this is a real error. The issue is you need to start with version `1.0.0` in bnd.bnd https://github.com/brianchandotcom/liferay-portal/pull/71831/files#diff-1624b2dbe587171e3279e7eb505bed63R3

How do I know this? Jorge did the exact same thing when he added site-buildings-site-initializer
fix here: https://github.com/brianchandotcom/liferay-portal/pull/69897/commits/6281a358d7e3aad4c549afe65ef4f8ca91f82a90

Why does it need to start with `1.0.0`? I have no idea. I just searched my email for `in: sent "Could not resolve all files for configuration"` because it sounded like an error that someone else had to fix.

cc/ @xbrianlee @joshchong

**Comment by xbrianlee** [comment]
ci:close

...for the reason above

**Comment by arboliveira** [comment]
😃 Thank you @jpince, spot on!!

**Pull request closed without merging**
