### PR TITLE
LPS-121824 Diverge 7.3.x | master

### PR DESCRIPTION
**Pull request by jpince**
https://issues.liferay.com/browse/LPS-121824

Tested [here](https://github.com/jpince/liferay-portal/pull/159#issuecomment-705257880), no blocking issues identified by QA

### CODE REVIEW

**Comment by vicnate5** [comment]
@jpince The upgrade failures on https://github.com/jpince/liferay-portal/pull/159#issuecomment-705257880 are gonna block Stable merge.

**Comment by achaparro** [comment]
Hey @jpince @petershin,

Do you know how to replace the "@release.info.build@" in the ReleaseInfo file? I am getting errors starting up the server due to the version in the release table is still 7310.

I have executed dxp profile too.

Thx

**Comment by petershin** [comment]
@jpince - The commit below is needed because it depends on the changes in `master-private`

https://github.com/jpince/liferay-portal/pull/160/commits/8526a76685e5ff91a7aed07b5c2297a4b2e5abcc

**Comment by petershin** [comment]
If there's time, https://github.com/petershin/liferay-portal/pull/1246 should be merged into `master` before this is reviewed.

It wasn't forwarded yesterday due to an unrelated regression issue that caused the CI test to fail.

**Comment by jpince** [comment]
@achaparro see https://github.com/brianchandotcom/liferay-portal/pull/94886

**Comment by achaparro** [comment]
Hey @jpince @vicnate5 @petershin,

I was able to run the bundle with the new changes locally I can't reproduce it, the tests passed:
image
image

If fails, it means that the registration of the upgrade processes is not working well but that shouldn't be affected by these changes. Maybe this can happen due to a race condition depending on when the modules are loaded.

In order to see if this is a real issue:
- Can you provide more details about how the tests were executed in the CI? (I started up the server with a fresh database and executed the tests)
- Did the tests failed always after these changes or just from time to time?

In case it helps, I also remember that test testUpgradeRegistryFollowsShortestPath wasn't really stable in the past.

Please, provide the whole information here and I will check it tomorrow.

Thanks.

**Pull request closed without merging**
