### PR TITLE
Lpd 26376

### PR DESCRIPTION
**Pull request by shuyangzhou**
@tinatian @vicnate5 please backport for LXC, thanks!

@victorhcunha @slnn this needs to run login check. It is expected to drop ES server CPU and network usages, while improving portal side throughput too. Please make sure the baseline is head master that includes all recent changes.

### CODE REVIEW

**Comment by slnn** [comment]
Hi @victorhcunha

When record test result, please also compare the cpu usage of ES server, you can get it  from /es/logs/elasticsearch-vmstat.log, pick the value of us like what we do for portal CPU usage, and also  compare the value in /es/logs/elasticsearch-ifstat.log


Lily

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f91e641cde...1238262883

**Comment by victorhcunha** [comment]
Hi @shuyangzhou !

Here are the results for Login testcase
Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | DB CPU Usage (%) | ES CPU Usage (%) | ES-ifstat-KB/s in | ES-ifstat-KB/s out
-- | -- | -- | -- | -- | -- | -- | -- | --
Baseline | 3bf3c56 | 8010 |   | 262 | 10,9,9 | 10,11,8 | 765.95 , 751.21, 757.61 | 412.77, 404.99, 408.28
PR | - | 8217 | 2.584269663 | 269 | 9,9,9 | 7,7,8 | 615.60, 609.25, 608.96 | 339.45, 335.73, 336.05

More details you can see in our [spreadsheet](https://docs.google.com/spreadsheets/d/1M6VK8GtY9kkv1EwhGW7vwrEENSzyT7zKz-wOh11ZHBo/edit#gid=395211958) 

cc @slnn @titokenzo

**Comment by shuyangzhou** [comment]
Thanks @victorhcunha !

**Pull request closed without merging**
