### PR TITLE
LPS-77842

### PR DESCRIPTION
**Pull request by Alec-Shay**
Resent from https://github.com/brianchandotcom/liferay-portal/pull/55552

We left out the version change to portal-impl because it looks like it isn't needed to regenerate the new SQL after all. If there is a problem with leaving it out like this though, please let us know and we can try to go through 7.0.x first instead, and revise the documentation again.

Thank you.

### CODE REVIEW

**Comment by Alec-Shay** [comment]
ci:test

**Comment by yichenroy** [comment]
ci:test (previous build was started on a bad server)

**Comment by Alec-Shay** [comment]
ci:reopen

**Comment by pyoo47** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/486fb6731a...a9fc78473c

**Pull request closed without merging**
