### PR TITLE
LPS-66125

### PR DESCRIPTION
**Pull request by natecavanaugh**
/cc @bryanengler

### CODE REVIEW

**Comment by BryanEngler** [comment]
hey nate, just wondering if the placement of the quotes matter? i had:

`-d title='' \`
vs
`-F "title=" \`

looks like your commit might change this so just wanted to make sure it was intended?

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by natecavanaugh** [comment]
@BryanEngler Sorry for the delay, I'm just now reviewing my pr notifications.

Can you explain the part you mean?
(I get `-F  title=''`, but are you getting something else?)

**Comment by BryanEngler** [comment]
no worries, i tested with your commit and everything is fine. i was just looking at some curl documentation and they were showing double quotes surrounding the key and value for multipart requests so thats how i wrote the fix. but your changes converted it to single quotes only around the value for multipart requests so i just wasnt sure if that would break it, but it doesnt so everything is good.

**Pull request closed without merging**
