### PR TITLE
LPS-58442 improve accessibility and documentation of add-menu taglib

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
@marcoscv-work we have dome some accessibility improvements to the add button. can you have a look? thanks!

**Comment by juliocamarero** [comment]
@jhinkey we have added some documentation here. thanks!

**Comment by juliocamarero** [comment]
cc @jbalsas

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/debfe6c382...d27ad8f51e

**Comment by brianchandotcom** [comment]
See https://issues.liferay.com/browse/LRDOCS-1860

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
