### PR TITLE
LPS-75480

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @jbalsas,

Attached is an update for http://issues.liferay.com/browse/LPS-75480.  I sent this to you since @ambrinchaudhary said she is going to be out.  Feel free to forward this to whoever would be reviewing frontend pull for WCM.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:reopen

**Comment by jbalsas** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
