### PR TITLE
LPS-64279 Initializes proper Layout handler

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by sharonchoi** [comment]
@evannagayama there is a poshi failure with asserting something in the product menu

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
I believe this is the issue: https://issues.liferay.com/browse/LPS-64239. Retesting to make sure.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7ed2ad714d...03bd8a8765

**Pull request closed without merging**
