### PR TITLE
LPS-145138 Read locale id submitted from client side, and apply to search and title (asset renderer)

### PR DESCRIPTION
**Pull request by arboliveira**
https://issues.liferay.com/browse/LPS-145138

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/81803d2bee...ec81849c9f

**Comment by brianchandotcom** [comment]
@arboliveira can you resend with "languageId" so it matches LocaleUtil.fromLanguageId(generalConfiguration.getLocaleId())

Thx

**Comment by brianchandotcom** [comment]
@arboliveira nvm, I did the rename in 30aa8948b2e256790990e52ec707208dd4504765. Please revert if you think I'm wrong

**Pull request closed without merging**
