### PR TITLE
LPS-84119

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:reopen

**Comment by ling-alan-huang** [comment]
SF failures are not related to this pull request.

**Comment by brianchandotcom** [comment]
Can you resend:

Private-Package: com.liferay.portal.remote.json.web.service.extender.test.internal.*

internal is already private, so we should never have to specify private-package

**Comment by ling-alan-huang** [comment]
> internal is already private, so we should never have to specify private-package

Hi @brianchandotcom,

I looked at the history of `BNDImportsCheck.java`.

We assumed Internal packages as private: https://github.com/liferay/liferay-portal/commit/84ee994b7af5e550982b7cee0530380bf82576a9

But we don't check if the modules are in `*-test`: https://github.com/liferay/liferay-portal/commit/776bcd96cd7b45e8ed219358869ef883e0a7712b

My changes `modules/apps/portal-remote/portal-remote-json-web-service-extender-test/bnd.bnd` is in `*-test`

We can find the similar one here: https://github.com/liferay/liferay-portal/blob/master/modules/apps/oauth2-provider/oauth2-provider-test/bnd.bnd

Thanks.

**Pull request closed without merging**
