### PR TITLE
Lps 60705

### PR DESCRIPTION
**Pull request by shuyangzhou**
@JorgeFerrer your pull is fine, just you got an obsoleted build for system.packages.extra.mf

Make sure you always rebase/ant all first before generating it.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@brianchandotcom we need a new test to ensure people don't accidentally commit in system.packages.extra.mf from old source to overwrite the one from current source. Same style as SB and PortalClientBuilder tests.

**Comment by JorgeFerrer** [comment]
Awesome. Thanks Shuyang!

I'll keep your advice in mind next time I regenerate that file.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d7a62c171e...a78ebe8758

**Comment by brianchandotcom** [comment]
@JorgeFerrer I made a few fixes/changes in upstream. Fyi.

**Comment by JorgeFerrer** [comment]
Thanks @brianchandotcom, the changes look good

**Pull request closed without merging**
