### PR TITLE
LPS-83174 rename author to creator, we shouldn't be using author prop…

### PR DESCRIPTION
**Pull request by javiergamarra**
…erty and use creator instead

### CODE REVIEW

**Comment by nhpatt** [comment]
We can send a PR to 7.1 with the cherry pick if you want :)

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@nhpatt I'll CP

**Comment by nhpatt** [comment]
Thanks :)

**Pull request closed without merging**
