### PR TITLE
LPS-55798 SF

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:retest

**Comment by izaera** [comment]
Previous failures are due to an error in master.

**Comment by izaera** [comment]
ci:retest

**Comment by izaera** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/01a8136f32...581c7875ef

**Pull request closed without merging**
