### PR TITLE
LPS-98325 Add missing import for HashMapBuilder in LayoutMultiLanguageSearchTest

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
@ealonso

**Comment by yichenroy** [comment]
ci:test:relevant
Failure due to network outage.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fead94b580...19da305372

**Comment by brianchandotcom** [comment]
@jkappler see 19da305

**Pull request closed without merging**
