### PR TITLE
LPS-68779 Don't generate sqls for deprecated entity

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @sergiogonzalez @mhan810

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 what happened here?

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by pyoo47** [comment]
@brianchandotcom We've been observing some freezing on test-1-4. This appears to be related. This particular failure makes me think that there's something going on with the shared drive.

```
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:4281: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:4288: java.io.FileNotFoundException: /mnt/mfs-ssd1-10.0.10/jenkins/test-1-4/opt/java/jenkins/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/877/test-portal-acceptance-pullrequest-batch(master)/compile-jsp-jdk8/test.jenkins.properties (Input/output error)
```

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
