### PR TITLE
LPS-107135 Disable flakey JS tests in portal-workflow-kaleo-designer-web

### PR DESCRIPTION
**Pull request by wincent**
These tests pass fine when run locally:

https://gist.github.com/wincent/ca3c84a4b75ea07aad002d99f311fca8

but we've seen them blow up in multiple CI runs at this point (all due to timeouts); some examples:

- https://github.com/brianchandotcom/liferay-portal/pull/83324
- https://github.com/brianchandotcom/liferay-portal/pull/83270
- https://github.com/brianchandotcom/liferay-portal/pull/83312

Let's disable them to reduce noise and investigate separately.

### CODE REVIEW

**Comment by wincent** [comment]
cc:

- @john-co just so that you're aware that this one is disabled.
- @inacionery as last person to touch the tests in this project.

**Comment by inacionery** [comment]
Hey @wincent ,

This flakey has been going on for some time. I believe it has to do with the CI slowness. 

Can we increase the karma timeout, since 2 seconds is not enough in the CI? Instead of disabling the tests?

Thanks!

**Comment by wincent** [comment]
Yeah, 2s is pretty darn low, but would be nice to get an opinion from somebody knowledgeable about our CI infrastructure before doing that.

At the moment this test takes about 8s (overall) for me. If we increase the timeout, then obviously the upper bound on the total runtime in CI will go up. I don't think 8s is particularly slow compared to some of our other test suites, but I also don't know whether we have a target range that we try to keep things under. Maybe @austinchiang knows?

Can I suggest that we disable this for now to stop the immediate noise, and if you want to experiment with some different timeout values, see it passing, and re-enable then feel free to do so?

**Comment by barrosdennys** [comment]
Hi @wincent 
I also agree with @inacionery that we should try to increase the timeout before disabling the tests. 

@kenjiheigel @pyoo47 what do you think?

**Comment by austinchiang** [comment]
@wincent thanks for mentioning me but I don't have the answer to your question. I think @pyoo47 or @yichenroy should have a better understanding

**Comment by inacionery** [comment]
Hey @wincent,

Could you please close this PR?

I sent a PR to increase the timeout https://github.com/brianchandotcom/liferay-portal/pull/83349

Thanks!

**Comment by yichenroy** [comment]
Hi @wincent, the CI machines are not particularly fast and often run multiple processes at the same time. I agree with increasing the timeout maybe even upwards to 1 minute and then decreasing it to find a better balance.
 
-CI Team

**Comment by brianchandotcom** [comment]
Ok, I merged in the increased timeout for now from @inacionery 
Not merging this one for now.. if it's still flaky then we can remove it.

**Pull request closed without merging**
