### PR TITLE
LPS-74325

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-74325.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:reopen

**Comment by jonmak08** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a814e3887a...600b818e38

**Comment by brianchandotcom** [comment]
@alexandervalencia @jonmak08 see 7c76756b88541f18a6bba5572e55b818f92d4fd6

**Pull request closed without merging**
