### PR TITLE
LRQA-30908 Bug fixes

### PR DESCRIPTION
**Pull request by pyoo47**
We discovered that the source-format failures are coming from a bug in jgit rebases. I've reworked the code to use regular git (via command-line) to perform rebases.

I've also fixed an intermittent bug that causes checkout failures.  This bug fixes a race condition that happens when a checkout command issued at exactly the same time that upstream is being updated. This prevents local-git sync logic from knowing when the checkout command is complete so it waits until it eventually times out.

Please publish a new com.liferay.jenkins.results.parser.jar after merging this pull request.

### CODE REVIEW

**Comment by pyoo47** [comment]
@hhuijser @kenjiheigel @michaelhashimoto - I think this pull request will fix the source-format issues.

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4241f2f37b...d9ef16e210

**Comment by brianchandotcom** [comment]
@pyoo47 published a new jar for you.

**Comment by hhuijser** [comment]
@pyoo47 thanks for figuring that out!

**Pull request closed without merging**
