### PR TITLE
OAUTH2-111 Update JavaDoc

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by topolik** [comment]
ci:test

SF may fail due to SPI exporting packages, depends on https://github.com/brianchandotcom/liferay-portal/pull/55685

**Comment by topolik** [comment]
ci:reopen

**Comment by topolik** [comment]
@brianchandotcom Should we add OAUTH2 into ci.properties for the test to run? Inside this PR or a new one? Thanks.

**Comment by brianchandotcom** [comment]
Can you resend:

com.liferay.oauth2.provider.scope.spi.applicationdescriptor,\
	com.liferay.oauth2.provider.scope.spi.prefixhandler,\
	com.liferay.oauth2.provider.scope.spi.scopedescriptor,\
	com.liferay.oauth2.provider.scope.spi.scopefinder,\
	com.liferay.oauth2.provider.scope.spi.scopemapper,\
	com.liferay.oauth2.provider.scope.spi.scopematcher

packages should be per word, "prefix.handler", "application.descriptor" etc.

I added OAUTH2 to CI.

**Comment by csierra** [comment]
please see https://github.com/brianchandotcom/liferay-portal/pull/55736

Thx!

**Comment by csierra** [comment]
please see https://github.com/brianchandotcom/liferay-portal/pull/55737

**Pull request closed without merging**
