### PR TITLE
Lps 76150

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by anthony-chu** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@tomwang2011 rebase error, can you resend?

**Comment by shuyangzhou** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/53901

**Pull request closed without merging**
