### PR TITLE
LPS-67821 SF

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
@ealonso @carloslancha please resend, this is not right in build.gradle

```
dependencies {
	provided group: "com.liferay", name: "com.liferay.frontend.taglib.soy", version: "1.0.3"
	provided group: "com.liferay", name: "com.liferay.portal.template.soy", version: "2.2.1"
```

@hhuijser how come SF didn't auto catch that as an error?

We enver use minor versions for compiles.

Please resend. Thx.

**Comment by brianchandotcom** [comment]
@ealonso @carloslancha @hhuijser

I meant "micro", not minor. For com.liferay.* provided, we should never have to do micro.

And when we choose minor, we use the lowest required number.

**Pull request closed without merging**
