### PR TITLE
LPS-85342 SF (auto-generated)

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Hi @jpince,

The failures don't seem related to our changes.

**Comment by jpince** [comment]
@4lejandrito yes, 2nd retest looks good (unique test failures are flukes). Thanks for asking.

**Comment by brianchandotcom** [comment]
@boton @jbalsas can we sort:

```
function openToast(
	{
		message = '',
		title = Liferay.Language.get('success'),
		type = 'success',
		events = {}
	} = {}
) {
```

If so, please send me a follow up pull. Thx.

**Pull request closed without merging**
