### PR TITLE
LPS-65310

### PR DESCRIPTION
**Pull request by natecavanaugh**
Heya Brian, we weren't sure about if we need to send this to 7.0.x as well (or for which changes or pulls we should send over to that branch as well).

If you can let us know, we can send a pull to that repo as well.

Thanks Brian :)

### CODE REVIEW

**Comment by natecavanaugh** [comment]
ci:stop

**Comment by natecavanaugh** [comment]
Stopped CI, as I forgot to regen the task-cache, will push as soon as it's done building.

**Comment by natecavanaugh** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pat270 can you resend since it conflicts with another pull that updates to Lexicon 1.0.4.

Thx.

**Pull request closed without merging**
