### PR TITLE
Lps 171716

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1709a69e71...11fea499ef

**Comment by brianchandotcom** [comment]
@shuyangzhou I assume order matters here?

```
		bundleContext.registerService(
			Props.class, props, _getProperties(props, Props.class.getName()));

		bundleContext.registerService(
			ProcessExecutor.class, new LocalProcessExecutor(), null);
```

If not, can you sort it and remove the line break? Thx

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128099

**Pull request closed without merging**
