### PR TITLE
LPS-84719 Using the new interface

### PR DESCRIPTION
**Pull request by 4lejandrito**
Follow up of https://github.com/brianchandotcom/liferay-portal/pull/62353#issuecomment-415100449.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:close @4lejandrito semver due to https://github.com/brianchandotcom/liferay-portal/pull/62383/files#diff-89a8f8ffeb951b04e12ce180c2b19be6R21
```
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.petra.function                         MINOR      1.0.0      1.0.0      1.1.0      VERSION INCREASE REQUIRED
     [exec] 	+   interface  com.liferay.petra.function.UnsafeRunnable
     [exec] 		+   access     abstract
     [exec] 		+   method     run()
     [exec] 			+   access     abstract
     [exec] 			+   return     void
     [exec] 		+   annotated  java.lang.FunctionalInterface
```

**Comment by 4lejandrito** [comment]
Hi @jpince,

See https://github.com/brianchandotcom/liferay-portal/pull/62433.

**Pull request closed without merging**
