### PR TITLE
Master | LRQA-57878

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LRQA-57878

Hi @brianchandotcom , only remove quarantine properties from the tests, so I push it to you directly.

cc/ @austinchiang

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:reopen

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/03d32400f0...7de2aa049d

**Pull request closed without merging**
