### PR TITLE
LPS-62718

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by mhan810** [comment]
@brianchandotcom presume unrelated since it had tested successfully earlier here: https://github.com/mhan810/liferay-portal/pull/1000

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c8838096c6...f1ed47af2c

**Comment by brianchandotcom** [comment]
@mhan810 I kept the deploy to osgi/portal

All the portal/** jars and portal-**/** go to osgi/portal

Is that OK?

**Pull request closed without merging**
