### PR TITLE
LPS-63408 modularize property to hightlight portlets

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
cc @sergiogonzalez

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b85718e19c...1ff83ab445

**Comment by brianchandotcom** [comment]
@juliocamarero isn't your logic in PortletCategoryComparator wrong?

Or does the order of highlighted categories not matter? We're grouping them all together, but not sorting them once they're grouped. You may need to send a fix for this. Thx.

**Pull request closed without merging**
