### PR TITLE
master-lps-62270

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LRQA-21473

### CODE REVIEW

**Comment by brianwulbern** [comment]
@brianchandotcom @evannagayama 

I've checked with Collab team about the failing test.  It has a clean [history](https://testray.liferay.com/home/-/testray/case_results/35883667?_1_WAR_testrayportlet_redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fruns%2F35879223%2Fdetails%3F_1_WAR_testrayportlet_testrayRunId%3D%26_1_WAR_testrayportlet_filterAssignedUserId%3D%26_1_WAR_testrayportlet_filterComments%3D%26_1_WAR_testrayportlet_filterCommentsBlankOnly%3D%26_1_WAR_testrayportlet_filterDefects%3D%26_1_WAR_testrayportlet_filterDefectsBlankOnly%3D%26_1_WAR_testrayportlet_filterStatus%3D%26_1_WAR_testrayportlet_filterName%3D%26_1_WAR_testrayportlet_filterPriority1%3D%26_1_WAR_testrayportlet_filterPriority2%3D%26_1_WAR_testrayportlet_filterPriority3%3D%26_1_WAR_testrayportlet_filterPriority4%3D%26_1_WAR_testrayportlet_filterPriority5%3D%26_1_WAR_testrayportlet_filterTestrayComponentId%3D%26_1_WAR_testrayportlet_testrayTeamId%3D0%26_1_WAR_testrayportlet_testrayComponentId%3D%26_1_WAR_testrayportlet_tabs1%3Dall-cases%26_1_WAR_testrayportlet_cur%3D1%26_1_WAR_testrayportlet_delta%3D75%26_1_WAR_testrayportlet_keywords%3D%26_1_WAR_testrayportlet_advancedSearch%3Dfalse%26_1_WAR_testrayportlet_andOperator%3Dtrue%26_1_WAR_testrayportlet_orderByCol%3DstatusLabel%26_1_WAR_testrayportlet_orderByType%3Dasc), and the changes in this pull don't impact that test.

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
Added the test to our monitoring spreadsheet

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/292c82004b...f629f4463c

**Pull request closed without merging**
