### PR TITLE
LPS-54852 don't need this anymore

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@rotty3000 how come we're writing native SQL? I know we had to do that for perf reasons for Counter at one point, but to make it work across clusters in many DB's, we had to do lots of work for that.

Is there any way we can use our generated persistence for this? It'd save a lot of testing across databases. Thx @rotty3000 

Can you resend with an explanation or resend using the generated SB tier? Thx.

**Comment by rotty3000** [comment]
We can't use the generated for this because it's lower in the stack.

Please reopen and merge.

- Ray (mobile)

**Comment by rotty3000** [comment]
Brian this persistence takes effect way earlier in the init process than
everything else which comes out of the spring context of the portal, so it
can't use hibernate.

On Mon, Jul 27, 2015 at 8:22 AM, Raymond Auge <raymond.auge@liferay.com>
wrote:

> We can't use the generated for this because it's lower in the stack.
>
> Please reopen and merge.
>
> - Ray (mobile)
> On Jul 26, 2015 6:24 PM, "Brian Chan" <notifications@github.com> wrote:
>
>> Closed #28605
>> <https://github.com/brianchandotcom/liferay-portal/pull/28605>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/brianchandotcom/liferay-portal/pull/28605#event-365610003>
>> .
>>
>


-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by rotty3000** [comment]
Furthermore, the cluster stuff was not missed, it's coming. It's a
completely separate module.

On Tue, Jul 28, 2015 at 9:56 AM, Raymond Auge <raymond.auge@liferay.com>
wrote:

> Brian this persistence takes effect way earlier in the init process than
> everything else which comes out of the spring context of the portal, so it
> can't use hibernate.
>
> On Mon, Jul 27, 2015 at 8:22 AM, Raymond Auge <raymond.auge@liferay.com>
> wrote:
>
>> We can't use the generated for this because it's lower in the stack.
>>
>> Please reopen and merge.
>>
>> - Ray (mobile)
>> On Jul 26, 2015 6:24 PM, "Brian Chan" <notifications@github.com> wrote:
>>
>>> Closed #28605
>>> <https://github.com/brianchandotcom/liferay-portal/pull/28605>.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/brianchandotcom/liferay-portal/pull/28605#event-365610003>
>>> .
>>>
>>
>
>
> --
> *Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
>  (@rotty3000)
> Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
>  (@Liferay)
> Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org>
> (@OSGiAlliance)
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Pull request closed without merging**
