### PR TITLE
LPS-69993 system.packages.extra

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7f3a695fc1...2a318a820b

**Comment by brianchandotcom** [comment]
@sergiogonzalez I made both commits LPS-69993. Easier to backport in the future if necessary. I didn't use 	LPS-67993.

**Pull request closed without merging**
