### PR TITLE
LPS-89898 Adds versions as label

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
cc: cc: @brianchiu @kyle-miho

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
Re-running because of ci bug and also build failure from earlier

**Comment by brianchiu** [comment]
@ealonso There is a compile failure in this pull. Can you take a look?

```
     [exec] > Task :apps:journal:journal-web:compileJSP
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/journal/journal-web/build/jspc/org/apache/jsp/view_005fmore_005fmenu_005fitems_jsp.java:552: error: cannot find symbol
     [exec]       _jspx_th_clay_management$1toolbar_0.setDisplayContext( new JournalViewMoreMenuItemsManagementToolbarDisplayContext(liferayPortletRequest, liferayPortletReponse, request, journalViewMoreMenuItemsDisplayContext) );
     [exec]                                                                                                                                                 ^
     [exec]   symbol:   variable liferayPortletReponse
     [exec]   location: class view_005fmore_005fmenu_005fitems_jsp
     [exec] 
     [exec] > Task :apps:journal:journal-web:compileJSP FAILED
```

**Pull request closed without merging**
