### PR TITLE
LPS-71271

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
Sent to https://github.com/liferay/com-liferay-document-library/pull/1

**Comment by jpince** [comment]
SF is rejecting `name: "com.liferay.frontend.taglib", version: "default"`
Here's the error:
`     [java] Do not use 'default' version for 'com.liferay.frontend.taglib': ./modules/apps/knowledge-base/knowledge-base-web/build.gradle 8`
`     [java] Do not use 'default' version for 'com.liferay.frontend.taglib': ./modules/apps/collaboration/wiki/wiki-web/build.gradle 7`

Closing this pull.

**Comment by jpince** [comment]
ci:close

**Pull request closed without merging**
