### PR TITLE
Lps 86040

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fbc69e7081...48112e1019

**Comment by brianchandotcom** [comment]
@mtambara @shuyangzhou see 2d6eb8b2782e8182d683dad36cffd59228ca574e and 48112e101906d5c09d5a4a6dbbe385e6444c0ee1

**Pull request closed without merging**
