### PR TITLE
LPS-109782 SF

### PR DESCRIPTION
**Pull request by manoelcyreno**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
<tr><td rowspan="1" colspan="3">ABTest</td></tr>

**Comment by brianchandotcom** [comment]
```
<tr><td rowspan="1" colspan="3">ABTest</td></tr>
```

That one is off.

**Comment by manoelcyreno** [comment]
About the name of the ABTest.path file, I'm using the example of the:
- ExportImport.path
- CKEditor.path

About the name of the *ABTest.testcase, I'm using the example of the:
- PGDocumentsandmedia.testcase
- StagingDMWithVariation.testcase

About the "component-name = "portal-ab-test"", I'm using the example of the:
- RolesandpermissionsUsecase.testcase
- CPUsergroups.testcase

About use the "/" in the testray.main.component.name, I'm using the example of the:
- ExportImport.testcase
- ExportTemplate.testcase
- ImportErrorMessages.testcase

Thanks for all the advice.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cdb0523d47...9965f0a7aa

**Comment by brianchandotcom** [comment]
@manoelcyreno perfect. Thank you!

**Pull request closed without merging**
