### PR TITLE
LPS-64247 Move test condition to the correct place

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
cc @marcellustavares

**Comment by marcellustavares** [comment]
:+1:

**Comment by marcellustavares** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/375c5920bd...7ae10313d2

**Pull request closed without merging**
