### PR TITLE
Lps 63617

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
CC @mhan810

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3ac07669cf...8ccd2f09aa

**Comment by brianchandotcom** [comment]
@shuyangzhou 

modules/apps/business-productivity/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/upgrade/v1_0_0/UpgradeDynamicDataMapping.java

and UpgradePostgreSQL didn't rebase properly. I skipped those changes and merged in the rest. Can you resend those 2 classes?

**Comment by shuyangzhou** [comment]
@brianchandotcom when I rebase the branch I sent to you, there are many conflicts, you sure there are only those 2 conflicts?

@tinatian please rebase and recheck all changes, thanks!

**Pull request closed without merging**
