### PR TITLE
LPS-64100 - As a developer, frontend modules should be organized and namespaced in modules/apps/foundation

### PR DESCRIPTION
**Pull request by mjbradford89**
Hey Brian,

Attached is an update for https://issues.liferay.com/browse/LPS-64100.

I'm not familiar with what that `.gitrepo` file in the last commit.  But I deleted it with the rest of the frontend folder.  Not sure if ones need to be added in each new frontend-\* dir, but I can add them in if needed.

There is a chance this will also fail some CI tests that will need to be adjusted, but we'll see.

Please let me know if there are any issues.

Thanks!

### CODE REVIEW

**Comment by mjbradford89** [comment]
shoot, there is already a conflict.  I will rebase and force push

**Comment by mjbradford89** [comment]
ci:retest

**Comment by mjbradford89** [comment]
I think at least a couple of these failures are legitimate.  looking into them

**Comment by brianchandotcom** [comment]
@mjbradford89 please fix and resend? Thx.

**Pull request closed without merging**
