### PR TITLE
LPS-67200 SF

### PR DESCRIPTION
**Pull request by jbalsas**
/cc @brunobasto

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jbalsas please resend on top of https://github.com/jbalsas/liferay-portal/pull/643

service = Object.class

is generally a bad idea, because then I can't screen them by type. Please make a new type.

**Comment by jbalsas** [comment]
Hey @brianchandotcom, this was a conscious decision took by @migue. We're trying to avoid coupling those modules to the `spa-web` module or any derivate of it, so that's why we went with `Object.class` instead of a typed object in there.

Can you think of a better way out?

Thanks!

**Comment by brianchandotcom** [comment]
@jbalsas I just talked to @migue 

I thought Object.class was a mistake and didn't realize that you had worked with him on it. He knows OSGi better than me, so I'm going to merge this in later today.

**Comment by brianchandotcom** [comment]
@jbalsas merged. See upstream for my changes. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7bb30b8eaa...60662b69a6

**Comment by jbalsas** [comment]
Changes look good, thanks a lot @brianchandotcom !!

**Pull request closed without merging**
