### PR TITLE
LPS-98953 | Standardize Ajax requests in change-tracking modules

### PR DESCRIPTION
**Pull request by stsquared99**
CC @markocikos

@stsquared99 can you check this to see if there's any problems?

Thanks!

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:close

**Comment by Preston-Crary** [comment]
@stsquared99 looks like the SF failure is related to the changes.

**Comment by stsquared99** [comment]
@Preston-Crary On it, thanks

**Comment by stsquared99** [comment]
resent as https://github.com/brianchandotcom/liferay-portal/pull/77012

**Pull request closed without merging**
