### PR TITLE
LPS-100754 Update to liferay-npm-scripts v20.0.0

### PR DESCRIPTION
**Pull request by wincent**
v20.0.0 lints SCSS files using the stylelint project (in addition to the purely cosmetic formatting -- using Prettier -- that we were already doing).

Follow-up commits apply the autofixes and then the manual fixes so as to make clear what is changing.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f60524b6a5...322d24e2ab

**Comment by brianchandotcom** [comment]
@wincent can you change:

```
		//
		// Temporary workaround to allow tooltip to activate on entire icon.
		// https://github.com/liferay/clay/issues/2640
		//
```

to

```

		// Temporary workaround to allow tooltip to activate on entire icon.
		// https://github.com/liferay/clay/issues/2640

``

That's our usual standard. And can we enforce? Thx.

**Comment by wincent** [comment]
Updated comment formatting: https://github.com/brianchandotcom/liferay-portal/pull/83694

I implemented auto-enforcement in https://github.com/liferay/liferay-npm-tools/pull/353, so that will go in the next time we update liferay-npm-scripts.

**Comment by john-co** [comment]
Hi @wincent,

The js-unit tests did run on CI [here](https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/355078/AXIS_VARIABLE=0,label_exp=!master/console), but unfortunately the import failures were not registered as unstable/failures on CI. We're working with CI team and @petershin on [a fix](https://issues.liferay.com/browse/LRCI-952) for this so we can keep presenting meaningful js-unit errors on the test summary. But because we don't want instability issues like this to go unnoticed, I will get [a temporoary fix in](https://issues.liferay.com/browse/LRQA-55216). This will make the CI test result just mark the whole js-unit test batch as a failure.

js-unit-jdk8 test batch is included in test suites such as [`ci test`](https://github.com/liferay/liferay-portal/blob/master/test.properties) and [`ci test relevant` ](https://github.com/liferay/liferay-portal/blob/master/test.properties#L2338)

cc/ @yichenroy

**Pull request closed without merging**
