### PR TITLE
LPS-60177

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
ci:retest

**Comment by mhan810** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/018275a2d5...e70732ebae

**Comment by brianchandotcom** [comment]
@willnewbury testMyAccountPortlet broken in case you need log

**Pull request closed without merging**
