### PR TITLE
LPS-164130 Fix: Canonical URLs contain duplicate locales on Display page when using locale.prepend.friendly.url.style=2

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-164130

@lfbesada

### CODE REVIEW

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/9796

:x: ci:test:stable - 25 out of 27 jobs passed
:x: ci:test:relevant - 110 out of 168 jobs passed in 2 hours 47 minutes

**Comment by ozysouza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ae3c66d56f...a978eba1cc

**Comment by brianchandotcom** [comment]
@lfbesada can we add an integration test for this?

git ls-files **PortalImpl**Test*

I want to make sure we never regress. Thx.

**Pull request closed without merging**
