### PR TITLE
LPS-66265 Initialize ClassPathUtil for DBUpgrader

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchiu** [comment]
@brianchandotcom 
I tested this together with Shuyang and confirmed that it does fix https://issues.liferay.com/browse/LPS-66265.

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
@pyoo47 this seemed to hang

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@shuyangzhou I noticed a pattern.

Every time you call:

ClassPathUtil.initializeClassPaths

It's around:

InitUtil.init*

See DBUpgrader.java, PortalContextLoaderListener.java, LiferayIntegrationTestRule.java and PACLTestRule.java

Can we move the logic into InitUtil?

Thx.

**Comment by brianchandotcom** [comment]
@shuyangzhou also, in 3 cases, you call ClassPathUtil.initializeClassPaths before InitUtil.init*

But in PortalContextLoaderListener you don't. Can you move it up so it's before InitUtil.init if we can't move the logic out into InitUtil (so that usage is at least patternized). Thx!

**Pull request closed without merging**
