### PR TITLE
LPS-106886

### PR DESCRIPTION
**Pull request by javiergamarra**
Convention is _LocaleMap_ => _Map<Locale, String>_ and _I18nMap_ => _Map<String, String>_ when the key is a locale, to fill DTOs like this:
```
name_i18n = LocalizedMapUtil.getI18nMap(
  dtoConverterContext.isAcceptAllLanguages(),
  assetCategory.getTitleMap());
```

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:relevant - We aborted all master pull request jobs.  However, we decided to re-run all pulls in @brianchandotcom queue.

**Comment by nhpatt** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
ci:test:stable

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/051405045b...fb6ab019ad

**Comment by brianchandotcom** [comment]
@nhpatt @javierdearcos please backport to 7.2.x and 7.1.x with my changes. I made quite a few. Thx.

**Comment by nhpatt** [comment]
Thanks!

**Comment by javierdearcos** [comment]
ok, thank you

**Pull request closed without merging**
