### PR TITLE
Lps 72541

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
CC @mdelapenya

**Comment by mdelapenya** [comment]
@shuyangzhou, I talked with support team about this pull, and they add some concerns about the portal properties for a specific company.

Will this PR support that? We did not take it into account as initial requirements.

cc/ @jcampoy @eperezg

**Comment by shuyangzhou** [comment]
@mdelapenya do you mean the "include-and-override=portal-${easyconf:companyId}.properties" part? If so, then it is no. That was not part of the requirement. the current solution is applying the env override at the last (after the ext, company id and external-properties override or any other file based override) which is what the requirements asked, so that the env variables always beat the file config.

**Comment by brianchandotcom** [comment]
@mdelapenya am I supposed to merge this?

**Comment by mdelapenya** [comment]
Hey @brianchandotcom, I talked with support, and they think it's fine to merge, since it's well-documented (maybe as a limitation).

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/506709a02a...45071a6e7e

**Pull request closed without merging**
