### PR TITLE
LPS-126639, LPS-126640, LPS-126661 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-126639
https://issues.liferay.com/browse/LPS-126640
https://issues.liferay.com/browse/LPS-126661

This is only for master.

@david-gutierrez-mesa

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Thank you @Tim-Cao !

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4a78fc5bd5...84efb24c8f

**Pull request closed without merging**
