### PR TITLE
LPS-82864 Create a new remote UserService method to retrieve paginated users that are members of a user group

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-82864](https://issues.liferay.com/browse/LPS-82864).<br><br>Hey Brian, this adds a basic test case for each of the "get*Users" methods we dealt with in the previous pulls.<br><br>/cc @pei-jung

### CODE REVIEW

**Comment by drewbrokke** [comment]
Hey Brian, please allow these tests to finish

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@drewbrokke can you backport the test for me? Thx. Sorry, forgot to wait!

**Comment by brianchandotcom** [comment]
@drewbrokke I just need it for 7.0.x. I backported it to 7.0.x already.

**Comment by drewbrokke** [comment]
No worries - it passed locally, just wanted to be sure :)

**Pull request closed without merging**
