### PR TITLE
LPS-66969

### PR DESCRIPTION
**Pull request by matethurzo**
@jorgeferrer

### CODE REVIEW

**Comment by brianchandotcom** [comment]
com.liferay.exportimport.resources.importer.test.ResourcesImporterTest.testResourcesImport is broken.

see https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/19323/

Thx @matethurzo

**Comment by brianchandotcom** [comment]
@matethurzo I found the same error in another pull https://github.com/brianchandotcom/liferay-portal/pull/41735

So may be it's not your fault. I'm going to merge in anyways. Can you still try to fix that test bug though? Thx.

**Comment by matethurzo** [comment]
@brianchandotcom i was testing it locally and it was working properly. tomorrow I'll check the test failure though, thanks for letting me know. and for merging the pull.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5b41bf2f89...3e5d9fbde1

**Pull request closed without merging**
