### PR TITLE
Lps 73353 Add jacoco support

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
For developers local code coverage usage:

For unit test(including portal unit, module unit and portal-impl integration), just add -Djunit.code.coverage=true to your test command.
For module integration(aka Arquillian test), there are 2 ways.
a) If you want to start tomcat manually, start it this way: "./catalina.sh jacoco run", then you can just run tests as you normally do
b) If you want gradle to start the tomcat for you, run the test this way :
gw testIntegration --tests YourTest --Dapp.server.start.executable.arg.line="jacoco run"
Once your finish all your tests, to generate the report, run "ant generate-code-coverage-report" from project root. The report will be dumped at ${project.dir}/jacoco/html-report.

**Comment by tinatian** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@ithildir can you review this pull and send it to me? Thx.

**Comment by Ithildir** [comment]
@tinatian, I reviewed your pull and sent it to https://github.com/brianchandotcom/liferay-portal/pull/50504.

**Pull request closed without merging**
