### PR TITLE
LPS-64870 Clean up inclusion of com.liferay.util.Finite* into modules

### PR DESCRIPTION
**Pull request by peterfellwock**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest the failure wasn't you.. CI is flaky (@pyoo47 it happened again)

**Comment by peterfellwock** [comment]
@brianchandotcom I just get happy when its not my fault.

**Comment by brianchandotcom** [comment]
hey @peterfellwock Sorry about the miscommunication, but  Finite*Stack is too general to go just in journal. I can see putting CC and State in Shopping (those are at least related).

Finite* should go in petra.

Thx

**Comment by brianchandotcom** [comment]
@peterfellwock may be petra-collections?

**Pull request closed without merging**
