### PR TITLE
LPS-102700 Fix deprecated bnd glob pattern

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:reopen

**Comment by petershin** [comment]
@pyoo47 - Is this a known `CI` issue?

**Comment by pyoo47** [comment]
@petershin This should not be happening.. looking into it. 
CC: @yichentsai

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fe05702fdc...d053607cfb

**Comment by yichenroy** [comment]
@petershin 
Commenting for reference, it was because the branch is rebased off of Brian's origin which included changes not yet in uptream that modified the .gitrepo file, so the pr tester detected it as a change in this branch.

**Comment by yichentsai** [comment]
> @petershin This should not be happening.. looking into it.
> CC: @yichentsai

I think you tagged the wrong person.

**Pull request closed without merging**
