### PR TITLE
LPS-58550 App view select is no needed anymore in journal

### PR DESCRIPTION
**Pull request by ealonso**
cc: @natecavanaugh, @jbalsas, @carloslancha

### CODE REVIEW

**Comment by ealonso** [comment]
@brianwulbern

I cannot reproduce the smoke test manually, Could you help me?

Regards,
Eudaldo.

**Comment by brianwulbern** [comment]
@ealonso, @juliocamarero: added it here, too https://github.com/brianchiu/liferay-portal/pull/740

@brianchiu, this is the same change as the other one (a longer pause) - can you just push one to BChan, then if it passes, we'll reference that the longer pause fixes both of Eudaldo's pulls.  Thanks!

**Comment by brianchandotcom** [comment]
@ealonso poshi test failure.

**Comment by brianchiu** [comment]
@ealonso 
See comment here for explanation as to why we think this failed: https://github.com/brianchandotcom/liferay-portal/pull/30251#issuecomment-141136547

I can resend this for you.

**Comment by brianchiu** [comment]
Resent in:
https://github.com/brianchandotcom/liferay-portal/pull/30279

**Pull request closed without merging**
