### PR TITLE
LPS-165696 Remove unused service

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
CC @guilhermedcamacho

**Comment by shuyangzhou** [comment]
CC @vicnate5

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/68a8f070a2...6eedf995d9

**Pull request closed without merging**
