### PR TITLE
LRQA-72184 Auto SF

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5d31a30b49...a8d371a7de

**Comment by brianchandotcom** [comment]
@koor4356 @vicnate5 any way to change

Pause(locator1 = "10000");

to wait for a log statement?

**Comment by vicnate5** [comment]
@koor4356 Can you try to modify the test to use `waitForConsoleTextPresent`? This should remove our need to pause. See FileInstall#UninstallWarOffline

**Comment by koor4356** [comment]
Okay, will take a look. Thanks!

**Comment by koor4356** [comment]
Update is sent here: https://github.com/vicnate5/liferay-portal/pull/1964

**Pull request closed without merging**
