### PR TITLE
LPS-60834 Lexicon pagination shows always on the bottom. We should ignore this property, otherwise we might end up with no pagination at all

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
Hey @evannagayama or @sharonchoi, could any of you please take a look at the poshi errors?

**Comment by sharonchoi** [comment]
Hey @jbalsas, sure will do. Already looking at this test RecyclebinUsecase#RestoreDMDocumentFromFolderCP for https://github.com/brianchandotcom/liferay-portal/pull/32731#issuecomment-160680427

**Comment by jbalsas** [comment]
Thanks! then it might no be related to either PR?

**Comment by sharonchoi** [comment]
I also just realized @evannagayama is in Spain, and he might have more insight to CPSitememberships#RemoveMember. The DM test that is failing needs to be fixed, will send in a PR for that soon.

**Comment by sharonchoi** [comment]
@jbalsas Just pushed in a test fix for RecyclebinUsecase#RestoreDMDocumentFromFolderCP here https://github.com/brianchandotcom/liferay-portal/pull/32757

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
Thanks a lot, @sharonchoi! Evan had left already when I wrote, so I'll make sure to look into the other poshi with him tomorrow if it persists

**Comment by brianchandotcom** [comment]
@sharonchoi can you resend to me? Thx.

**Comment by sharonchoi** [comment]
Hey @jbalsas @brianchandotcom, the reason this poshi test fails is because of this bug I just filed: https://issues.liferay.com/browse/LPS-60875

CC'ing @evannagayama @brianwulbern as they work with Site Memberships more.

**Pull request closed without merging**
