### PR TITLE
LPS-65014 Adds hello-soy implementation.

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:stop @brunobasto There's a problem with the jenkins script that seems to causing this pull to hang.

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by brunobasto** [comment]
ci:retest

**Comment by brunobasto** [comment]
Rebased with latest master to see if tests are fixed.

**Comment by brunobasto** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/38735

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9e5642215a...ab6d63be5c

**Comment by brianchandotcom** [comment]
@brunobasto  Please see upstream for my changes. Thx!

**Comment by brunobasto** [comment]
Thanks, @brianchandotcom

**Pull request closed without merging**
