### PR TITLE
LPS-60707 sourceFileName should be the one of current file version.

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0b376d722b...9b1a653217

**Comment by brianchandotcom** [comment]
@zxdgoal @adolfopa test?

**Comment by zxdgoal** [comment]
Hey Brian 

We did it here : https://github.com/liferay/liferay-portal/commit/5f50f672f78c57b9f24cfe676b02889f76453869

**Pull request closed without merging**
