### PR TITLE
LPS-163762

### PR DESCRIPTION
**Pull request by rijema**
Hi Brian! Opening this PR as requested by the Form Team. Please see: https://github.com/liferay-forms/liferay-portal/pull/1967#issuecomment-1270640012

LPS: https://issues.liferay.com/browse/LPS-163762

Regards,
Richard.

### CODE REVIEW

**Comment by rijema** [comment]
ci:reopen

**Comment by rijema** [comment]
ci:test:sf

**Comment by rijema** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a40df96eb7...42f572f2a9

**Pull request closed without merging**
