### PR TITLE
LPS-62430 - Set default to "/message_boards/view" if nothing is passed.

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jbalsas @jonmak08 poshi error.

**Comment by jonmak08** [comment]
I will look at this issue and resend.

**Comment by jbalsas** [comment]
I sent it to myself this morning and all tests passed, so it might be a
spurious error... you can check my prs to verify. Maybe retest this one?

**Comment by jonmak08** [comment]
Yea, I sent this to myself again to retest.  New Pull Request: https://github.com/jonmak08/liferay-portal/pull/1469

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/brianchandotcom/liferay-portal/pull/35895

**Comment by jonmak08** [comment]
Seems like the previous error was inaccurate.

**Pull request closed without merging**
