### PR TITLE
LPS-81517 Buildlang

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@pavel-savinov interesting.. I'm surprised you couldn't reuse LayoutNameException, or add a field to it.. but had to create a LayoutNameLengthException.. I'm OK with it.. but would prefer to reuse the exception if possible. Otherwise, if others followed your pattern, we'd have 10x more exceptions than today.

**Comment by brianchandotcom** [comment]
For example.. see LayoutTypeException @pavel-savinov, you would have made that 4 different exceptions.

**Comment by brianchandotcom** [comment]
Actually, rolling this back.. thinking about this more and I think you need to follow the LayoutTypeException strategy, please resend @pavel-savinov

**Comment by ealonso** [comment]
@brianchandotcom @pavel-savinov see: https://github.com/brianchandotcom/liferay-portal/pull/59309

**Pull request closed without merging**
