### PR TITLE
LPS-61568

### PR DESCRIPTION
**Pull request by natecavanaugh**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@fernandosouza @brunobasto please resend, see PoshiRunner.test[Forms#PreviewAndPublishForm

**Comment by brunobasto** [comment]
@vicnate5, I think we need to update the tests for this one.

**Comment by marcellustavares** [comment]
Guess it's a real regression @brunobasto.

**Comment by marcellustavares** [comment]
@brunobasto is right, we need to update the tests. I've forwarded to https://github.com/vicnate5/liferay-portal/pull/233

**Pull request closed without merging**
