### PR TITLE
LPS-98587 Use new Asset Selector in FloatingToolbar itemSelectorField component

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
@ealonso

**Comment by ealonso** [comment]
ci:close

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3af48d2b27...10e4ba85db

**Comment by brianchandotcom** [comment]
@sandrodw3 I backported this to 7.2.x

**Comment by brianchandotcom** [comment]
lbm:backport @CsabaTurcsan @jpince @zsoltbalogh

@sandrodw3 I had to revert the backport from 7.2.x because it was causing a compile error.

```
> Task :apps:layout:layout-content-page-editor-web:npmRunBuild
yarn run v1.13.0
warning package.json: No license field
$ liferay-npm-scripts build
Using NODE_ENV: production
Compiling soy
Error in plugin 'metal-tools-soy'
Message:
    Compile error:
errors during Soy compilation
src/main/resources/META-INF/resources/js/components/floating_toolbar/fragment_configuration/field_types/ItemSelectorField.soy:31: error: Type mismatch on param field: expected: [label: string, name: string, type: string, typeOptions: [validValues: list<[label: string, value: string]>]], actual: [label: string, name: string, type: string, typeOptions: [validValues: list<string>]].
				{param field: $field /}
Finished compiling soy
    ^
1 error
```

Leaving it to you.

**Comment by sandrodw3** [comment]
@brianchandotcom this commits depend on LPS-98494 (https://github.com/liferay/liferay-portal-ee/pull/15458). When that backport is complete I'll send you another pull backporting LPS-98587.

**Pull request closed without merging**
