### PR TITLE
Upgrade Process: fix upgrade processes

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jpince** [comment]
ci:retest

**Comment by brianchiu** [comment]
@migue 
All the tests failed on this pull because it caused an error during portal startup. I saw this same error on this pull
https://github.com/migue/liferay-portal/pull/812 with the same commits. I haven't seen this error on any of the other pulls, so I believe the error was caused by the commits in this pull.

```
     [exec] 14:34:47,919 ERROR [Framework Event Dispatcher: Equinox Container: 407d8221-cf28-0016-1153-a65b7f0afd67][com_liferay_portal_lpkg_deployer:97] FrameworkEvent ERROR 
     [exec] org.osgi.framework.BundleException: Could not resolve module: com.liferay.portal.lpkg.deployer [6]
     [exec]   Unresolved requirement: Import-Package: com.liferay.portal.kernel.module.framework; version="[1.2.0,2.0.0)"
     [exec] 
     [exec] 	at org.eclipse.osgi.container.Module.start(Module.java:429)
     [exec] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
     [exec] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
     [exec] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
     [exec] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
     [exec] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
     [exec] 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
     [exec] 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
     [exec] 14:34:47,920 ERROR [Framework Event Dispatcher: Equinox Container: 407d8221-cf28-0016-1153-a65b7f0afd67][com_liferay_portal_lpkg_deployer:112] Exiting the JVM 
     [exec] org.osgi.framework.BundleException: Could not resolve module: com.liferay.portal.lpkg.deployer [6]
     [exec]   Unresolved requirement: Import-Package: com.liferay.portal.kernel.module.framework; version="[1.2.0,2.0.0)"
     [exec] 
     [exec] 	at org.eclipse.osgi.container.Module.start(Module.java:429)
     [exec] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
     [exec] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
     [exec] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
     [exec] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
     [exec] 	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
     [exec] 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
     [exec] 	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
```

**Comment by brianchiu** [comment]
Oh. Didn't realize you had already resent it here:
https://github.com/brianchandotcom/liferay-portal/pull/40409

**Pull request closed without merging**
