### PR TITLE
LPS-61796 Add unit tests

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
@juliocamarero, could you please review this? We had to change the UpgradeJournal because there're some chars we don't allow in ddm structure field names anymore such as punctuation or spaces.

Thanks

**Comment by marcellustavares** [comment]
We'll add some integration tests DDM/Journal upgrade later on. We'll send you the pulls. Thanks

cc @inacionery

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9a770395f1...c01baf6b32

**Pull request closed without merging**
