### PR TITLE
LPS-70797 SF

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @hhuijser, do we really need a `.gitignore` in this folder? I think @Robert-Frampton removed it because it shouldn't affect the module can you clarify this for us, please?

**Comment by hhuijser** [comment]
@Ithildir, can you help out @jbalsas?

you added all the .gitignore files as part of LPS-68131.
What's the rule exactly? I assume you didn't manually create all those files?

**Comment by Ithildir** [comment]
Hi @jbalsas,
The `ModulesStructureTest` doesn't support layout templates yet. I'll work on fixing it today 😊

**Comment by Ithildir** [comment]
Done: https://github.com/brianchandotcom/liferay-portal/pull/48979

**Comment by jbalsas** [comment]
ci:reopen

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
Awesome, thanks a lot @hhuijser, @Ithildir!! 🎉

**Comment by jbalsas** [comment]
I just realized this is missing the `.lfrbuild-portal` marker. Will resend

**Pull request closed without merging**
