### PR TITLE
LPS-75332 As a developer I can use DDM forms annotations to control how the configuration forms will be displayed

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @jorgeferrer

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by pei-jung** [comment]
ci:reopen

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
PortalSmokeUpgrade#ViewPortalSmokeArchive623 is failing due to an inconsistent Elasticsearch issue during portal startup.

We're investigating it here:
https://issues.liferay.com/browse/LRQA-35988

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/08658e697f...065eca9995

**Pull request closed without merging**
