### PR TITLE
LPS-65897

### PR DESCRIPTION
**Pull request by topolik**
Hi Brian,

https://issues.liferay.com/browse/LPS-65897

Thanks.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/21303f2469...63bc63ad93

**Comment by brianchandotcom** [comment]
@topolik please see my changes in upstream. I went ahead and backported this one for you. Didn't want to overwhelm you with backports in one day :)

**Comment by brianchandotcom** [comment]
@topolik can backport to other non 7.1.x branches, and also test my change? Just cosmetic. Thx.

**Comment by topolik** [comment]
Thanks @brianchandotcom! :D

Yes, I can backport, was designed to cherry-pick cleanly.

**Pull request closed without merging**
