### PR TITLE
LPS-103126 Set the mode param only when it's present in the config

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
@john, is it possible these failures are related? It's currently hard to tell :(

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/298c6b2fe5...60bdba36aa

**Comment by brianchandotcom** [comment]
@john-co I assume it's safe.

@jbalsas you tagged @john which is not our @john-co

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark:

PortalSmokeUpgrade#ViewPortalSmokeArchive70106 test failure looks like a fluke.

/cc @brianchandotcom

**Pull request closed without merging**
