### PR TITLE
LPS-73525

### PR DESCRIPTION
**Pull request by Ithildir**
Hi,
Please let this pull finish.

Thank you!

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:reopen

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
@tinatian, do you know why this is failing?

**Comment by tinatian** [comment]
@Ithildir Seems irrelevant to this pull, other pull fails on same error, let's try one more time

**Comment by tinatian** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop This was due to an upgrade issue that has since been rolled back.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f6466d3ab0...c308d0f8e4

**Comment by brianchandotcom** [comment]
@codyhoag fyi

**Pull request closed without merging**
