### PR TITLE
LPS-69899

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:reopen

**Comment by Ithildir** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@Ithildir @shuyangzhou @Preston-Crary @tomwang2011 this is very very very good.

But, I'd like this sent to me in 2 pieces.

First, I would like to get just the plumbing for this to work, with one taglib as an example that is already deprecated in 7.0.x.

I'd like to backport the plumbing along with the same example that can be cherry picked cleanly in 7.0.x.

Then send me the rest. As much as possible, I'd like to backport this. It should be 100% binary compatible since it literally is using the old stuff.

What's the status on the blogs-compat stuff? I don't think that "plumbing" has ever gone back to 7.0.x, but it should, even if the jars are not deployed.

Thx @shuyanghzou

**Comment by Preston-Crary** [comment]
Only thing that isn't plumbing is c009f91.  I can resend without that commit.

**Comment by tomwang2011** [comment]
As for the blogs-compat stuff, I will backport the portal-tools-portal-compat-bytecode-transformer (ASM) module to EE-7.0.x and leave out the blogs-compat module as EE-7.0.x doesn't have the same logic. Later on when we have new compat modules they can be backported directly to use the portal-tools-portal-compat-bytecode-transformer.

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/46294

**Pull request closed without merging**
