### PR TITLE
LPS-61501 extract control menu as a taglib  [PING]

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1b0c6d0c63...65af4b5955

**Comment by brianchandotcom** [comment]
Thx @juliocamarero

**Pull request closed without merging**
