### PR TITLE
LRQA-62432 Add portlet to test Alert Toast Message

### PR DESCRIPTION
**Pull request by zhangyan0701**
Resend https://github.com/brianchandotcom/liferay-portal/pull/100705 with updated portlet name.

Original pull request comment:
https://issues.liferay.com/browse/LRQA-62432

The portlet is to be used for testing Clay Toast Alert in Poshi tests.

This is how it looks like after deploying to a page:
112480219-c2fc3080-8db0-11eb-82cf-15a9c6f8c5d3

### CODE REVIEW

**Comment by zhangyan0701** [comment]
SF test passed in https://github.com/zhangyan0701/liferay-portal/pull/267#issuecomment-818560918.

Relevant tests passed in the original pull request: https://github.com/liferay-frontend/liferay-portal/pull/937#issuecomment-817723098.

**Comment by zhangyan0701** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@zhangyan0701 you can just follow modules/dxp/apps/multi-factor-authentication/multi-factor-authentication-sample/bnd.bnd

but call your sample-web since it's a web. It doesn't need to be in a test subdir.

**Comment by zhangyan0701** [comment]
Resend in: https://github.com/brianchandotcom/liferay-portal/pull/100884

**Pull request closed without merging**
