### PR TITLE
LRDOCS-2841

### PR DESCRIPTION
**Pull request by Ithildir**
This is the same pull as https://github.com/brianchandotcom/liferay-portal/pull/43000, I don't know why it was closed :confused:

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
<p auto-close="false"><strong><em>*If you believe this is a mistake please re-open this pull. This pull will no longer automatically close if this comment is available.</em></strong></p>

**Comment by michaelhashimoto** [comment]
ci:stop

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
not merging..

We should only support

modules/.releng ? Let's talk about this tomorrow @Ithildir

**Pull request closed without merging**
