### PR TITLE
master-bc-962

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LRQA-19372
https://issues.liferay.com/browse/LRQA-19371

### CODE REVIEW

**Comment by brianchiu** [comment]
@michaelhashimoto
Is there an easy way to read what failed?

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
Basically what happened is the matrix job failed because the server it was running on ran out of memory:
https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/13722/console

This is a very specific weird issue that will happen when a particular slave just runs out of memory.

But this failure did not really effect any of the actual tests.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4d90f6a523...8f81048a77

**Pull request closed without merging**
