### PR TITLE
LPS-188415 Make endpoints response with their associated response Schema

### PR DESCRIPTION
**Pull request by 4lejandrito**
Follow up from https://github.com/brianchandotcom/liferay-portal/pull/137480.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@LuismiBarcos @4lejandrito name here does not match

```
	public List<Map<String, Object>> getAPIApplicationSchemaPropertyValueMap(
			long companyId, APIApplication.Endpoint endpoint)
		throws Exception {

		...

		List<Map<String, Object>> entities = new ArrayList<>();

		return entities;

```

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/137747.

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/137747/commits/ce8f6895a22ab486a505664e9fba618c12f4ceb0

**Pull request closed without merging**
