### PR TITLE
LPS-68288 Save settings on Field value change

### PR DESCRIPTION
**Pull request by marcellustavares**
cc @vicnate5

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:close

**Comment by vicnate5** [comment]
@marcellustavares There is still a potential issue here. The test failure shows that the Form entry might not have saved successfully when using a data provider. I can look into it.

**Comment by marcellustavares** [comment]
thx @vicnate5, can I assign the ticket to you?

**Comment by marcellustavares** [comment]
nvm, you just did :)

**Comment by vicnate5** [comment]
Resent with poshi fix
https://github.com/brianchandotcom/liferay-portal/pull/44245

**Pull request closed without merging**
