### PR TITLE
LPS-61914 Move management-bar-sort to the same jsp where management-bar is so it can inherit whether the management bar is disabled or not

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pyoo47 @ithildir what's going on with NPM?

**Comment by Ithildir** [comment]
ci:retest

**Comment by pyoo47** [comment]
@brianchandotcom Andrea determined that the NPM failure turned out to be a corrupted download of the sass compiler. We think this was a fluke one-time occurrence.

**Comment by austinchiang** [comment]
The failing poshi test will be quarantined in https://issues.liferay.com/browse/LRQA-27555

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
