### PR TITLE
COMMERCE-12755

### PR DESCRIPTION
**Pull request by alessiorendina**
Re-sent directly from https://github.com/brianchandotcom/liferay-portal/pull/145718 fixing the issues highlighted [here](https://github.com/brianchandotcom/liferay-portal/pull/145718#issuecomment-1870338669)

https://liferay.atlassian.net/browse/COMMERCE-12755

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c4c22569de...9fef250c54

**Comment by brianchandotcom** [comment]
@alessiorendina Merry Christmas :)

**Comment by alessiorendina** [comment]
@brianchandotcom eheh merry Christmas to you as well :)

**Pull request closed without merging**
