### PR TITLE
LPS-93431 Upgrade versionUserId as LONG when needed

### PR DESCRIPTION
**Pull request by achaparro**
Hey @ChrisKian,

This is the pull request pending from a few weeks ago. Please take a look at this:
https://github.com/brianchandotcom/liferay-portal/pull/74852/commits/bf0401fd490990db3662fdf5d891dbd9be844ce2

Thanks!

### CODE REVIEW

**Comment by jpince** [comment]
@vicnate5 please review upgrade test results, they look different from the NPE at head
```
     [exec] 22-Jun-2019 16:57:45.505 SEVERE [main] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class [com.liferay.portal.spring.context.PortalContextLoaderListener]
     [exec]  java.lang.RuntimeException: java.lang.IllegalStateException: Module has been uninstalled.
```

**Comment by vicnate5** [comment]
Failures are not related to this change, but fixes for it should have gone in under LPS-96739 yesterday. I will re-run.

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/12dcee7287...1275b2a326

**Pull request closed without merging**
