### PR TITLE
LPS-136606 auto SF

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:reopen

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:reopen

**Comment by gabrielwas** [comment]
@nhpatt FYI

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f1bfcd8064...2e63fc7e1e

**Pull request closed without merging**
