### PR TITLE
LPS-73481 Set 7.1 version in master

### PR DESCRIPTION
**Pull request by achaparro**
CI tests will fail until the following pull is approved:
https://github.com/liferay/com-liferay-commerce-private/pull/196

### CODE REVIEW

**Comment by jpince** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
ci:retest (just to be safe)

**Comment by anthony-chu** [comment]
ci:retest

**Comment by jpince** [comment]
@achaparro unit test failure was because another liferay-plugin-package.properties file was added. I sent the extra commit needed: https://github.com/brianchandotcom/liferay-portal/pull/51825

@lawrence-lee fyi

**Comment by jpince** [comment]
@achaparro looks like Brian is gone for the day (I was hoping he would still be here so he could merge both), maybe it would be better to squash my change into your commit and resend?

**Pull request closed without merging**
