### PR TITLE
LPS-59069 read the control panel properties from the PanelApp

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Good job @juliocamarero did you have to make any real changes to fix the scan log?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5def1ceb3e...a08aa360a2

**Comment by juliocamarero** [comment]
@brianchandotcom yes, there was a test that has to be updated, I reduced the log level for now. Since that will need some time and this was an urgent fix I sent me a pull request with the right solution and the test but that will go after devcon :)

https://github.com/juliocamarero/liferay-portal/pull/3696

**Comment by brianchandotcom** [comment]
Got it. Thx Julio. Have fun at Devcon! Wish I could be there!

--
Brian Chan
Chief Software Architect
Liferay, Inc.
Enterprise. Open Source. For Life.
(626) 806-1190

**Pull request closed without merging**
