### PR TITLE
LPS-61738

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@shuyangzhou I've seen testMyAccountPortlet break twice now. Both random. It's new.

**Comment by shuyangzhou** [comment]
@willnewbury please take over this issue.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5c34e7a603...ca17d47bc0

**Comment by brianchandotcom** [comment]
@matethurzo see ca17d47bc0bd3cff20349b63b7788857b00b4b68 Thx.

**Pull request closed without merging**
