### PR TITLE
LPS-61514 Roles checkAll checkbox in define permissions is no longer there

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-61514](https://issues.liferay.com/browse/LPS-61514).<br><br>/cc @xbrianlee @alee8888 @pei-jung

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@drewbrokke compile error? Please rsend.

**Comment by brianchandotcom** [comment]
nvm.. unrelated

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c885d090d1...67f5dd6f5f

**Comment by brianchiu** [comment]
@drewbrokke 
Hey Drew, we've rolled this back because we think it may have caused blogs roles frontend test failures you see in the result.

Can you resend?

**Comment by drewbrokke** [comment]
@brianchiu sure thing.  I'm good to just resend as-is?

**Comment by xbrianlee** [comment]
@drewbrokke I fixed the failing CPRolesPGBlogs tests in alee8888#93. @alee8888 will submit your changes along with mine to BChan.

**Comment by drewbrokke** [comment]
Thanks @xbrianlee!

**Pull request closed without merging**
