### PR TITLE
LPS-74651

### PR DESCRIPTION
**Pull request by Ithildir**
Hi,
Please let this pull finish.

Thank you!

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@Ithildir you need to remove this line, as the jar is no longer there.
https://github.com/liferay/liferay-portal/blob/master/tools/servers/jboss/modules/module.xml#L5

**Comment by brianchandotcom** [comment]
@Ithildir waiting for you to resend. Thx.

**Comment by Ithildir** [comment]
ci:stop

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/51637.

**Pull request closed without merging**
