### PR TITLE
LPS-60249 Adds navigation filter

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@brianchiu Poshi error.. can you work on getting it fixed and sending it, or it may be a true failure @ealonso 

Thx

**Comment by brianchiu** [comment]
@brianwulbern @evannagayama
Can you guys look into this

**Comment by brianchiu** [comment]
nevermind. I'll look at it since they are both gone for the day.

**Comment by brianchiu** [comment]
This has been resent in: https://github.com/brianchandotcom/liferay-portal/pull/32061

* The test failure seems to have been caused by https://issues.liferay.com/browse/LRQA-19152, which is a random error that Hashi is currently working on fixing.
* I wasn't able to reproduce locally the source formatter error from the original. However, there is another source formatter error that will happen right now that will be fixed by https://github.com/brianchandotcom/liferay-portal/pull/32060

**Pull request closed without merging**
