### PR TITLE
 LPS-172389 Use https://www.antlr.org/ in order to read AC grammar

### PR DESCRIPTION
**Pull request by cgoncas**
Original PR: https://github.com/liferay-tango/liferay-portal/pull/3224.

Failing tests are not related with this PR.

Motivation
=======
View AC Event Segments in DXP. We intent to visualize the Event Segment Criteria of AC Segments in DXP Segments Editor.

To do so, the first requirement is to be able to read AC grammar.

[Link to story or ticket](https://issues.liferay.com/browse/LPS-171785))
[Link to substory](https://issues.liferay.com/browse/LPS-172389))

Proposed Solution
========
AC Grammar is described here:

https://liferay.atlassian.net/wiki/spaces/ENGAC/pages/1958478097/Custom+QueryBuilder+Language+FilterStringToQueryBuilder+Documentation

And in an ANTTLR file in https://github.com/brianchandotcom/com-liferay-osb-asah-private/blob/f3fdbee4f11b639acc4045bfb2d3cdf937be860c/osb-asah-filter-parser/src/main/antlr/com/liferay/osb/asah/common/filterexpression/parser/FilterExpression.g4

We have added this FilterExpression.g4 file to the segments-asah-connector module, in order to be able to read this grammar.

Steps to Verify:
----------------
Currently there is no integration/functional tests for these changes, we will do it in a separate PR.

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:reopen

**Comment by cgoncas** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@cgoncas can you send this to @petershin to have him approve the Gradle changes first.

Can you also change the header to add "@generated" , then you don't need modules/dxp/apps/segments/segments-asah-connector/src/main/java/com/liferay/segments/asah/connector/internal/expression/parser/source_formatter.ignore

**Comment by cgoncas** [comment]
Continues in https://github.com/liferay-tango/liferay-portal/pull/3225

**Pull request closed without merging**
