### PR TITLE
LPS-66853

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 no results here either?

**Comment by pyoo47** [comment]
@brianchandotcom This is the same failure as https://github.com/brianchandotcom/liferay-portal/pull/43463#issuecomment-249766955

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@pyoo47 can you work with Sam to find out why it's happening?

**Pull request closed without merging**
