### PR TITLE
LPS-79679

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by jpince** [comment]
@hhuijser @petershin can you please look into the failures in master-private?
```
     [java] 1: ./modules/private/apps/portal-security-audit/portal-security-audit-web/build.gradle expected:&lt;...mpileOnly project(":[apps:portal-security-audit:portal-security-audit-storage-api")
     [java] 	compileOnly project(":core:petra:petra-lang]")
     [java] }
     [java] 
     [java] mergeLang {
     [java] 	s...> but was:&lt;...mpileOnly project(":[core:petra:petra-lang")
     [java] 	compileOnly project(":apps:portal-security-audit:portal-security-audit-storage-api]")
     [java] }
     [java] 
     [java] mergeLang {
     [java] 	s...>
     [java] 2: ./modules/util/source-formatter/src/main/java/com/liferay/source/formatter/checks/BNDBundleInformationCheck.java expected:&lt;...dsWith("-import") ||[ ]moduleName.contains(...> but was:&lt;...dsWith("-import") ||[
     [java] 			]moduleName.contains(...>
```

**Comment by petershin** [comment]
@jpince Sent patches to Brian: 

[brianchandotcom/liferay-portal#59590](https://github.com/brianchandotcom/liferay-portal/pull/59590)
https://github.com/brianchandotcom/liferay-portal-ee/pull/20368

**Comment by jpince** [comment]
@petershin thanks!

**Pull request closed without merging**
