### PR TITLE
LPS-62482

### PR DESCRIPTION
**Pull request by vicnate5**
@marcellustavares resend of https://github.com/brianchandotcom/liferay-portal/pull/35662

### CODE REVIEW

**Comment by lesliewong92** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
rebase error, please resend.

**Comment by vicnate5** [comment]
Forwarded to @marcellustavares for correct rebase
https://github.com/marcellustavares/liferay-portal/pull/1171

**Comment by marcellustavares** [comment]
Resent to https://github.com/brianchandotcom/liferay-portal/pull/35742

**Pull request closed without merging**
