### PR TITLE
Revert "Revert "LPS-53855 Regen""

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by rotty3000** [comment]
I'm looking at why these are failing. The last is for sure a bug in the test case because this is a unit test. There's not even a osgi runtime there!

**Comment by rotty3000** [comment]
ok, I think I figured it out!

will update the PR shortly.

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Just an SF error! :)

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a07bf0a214...33e515770b

**Pull request closed without merging**
