### PR TITLE
master-lps-58466

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LPS-58466

For these commits, Albert is updating the websphere properties.
- He changed "portal.war.dir" to be "portal.war.name" because the property represents an actual war file and not a directory
- He created a generic "app.server.${app.server.type}.portal.war.name" and put it in with the rest of the generic app server properties in build-common.xml. Let us know if it shouldn't go here.
- He consolidated the portal.war logic for glassfish and websphere because there is duplicate logic there

This is a resend of:
https://github.com/brianchandotcom/liferay-portal/pull/30116

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@brianchandotcom 

The LayoutImplTest.testIsTypePortletReturnsFalse shouldn't have anything to do with this pull.

That test is also failing on these pulls.
https://github.com/brianchandotcom/liferay-portal/pull/30124
https://github.com/brianchandotcom/liferay-portal/pull/30123

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/50c75890d4...a722e488aa

**Comment by brianchandotcom** [comment]
Nice job @alee8888

**Pull request closed without merging**
