### PR TITLE
LPS-72218 build.gradle

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:reopen

**Comment by ealonso** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2cfe8b9be8...616d25a701

**Comment by brianchandotcom** [comment]
@ealonso please apply 616d25a70161b15e924a3d8c1f0df047361faa1d to the original deprecated methods if appropriate. Thx

**Pull request closed without merging**
