### PR TITLE
LPS-58895 fix versions comparator

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
fyi @sergiogonzalez

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
@brianchiu @michaelhashimoto can you help me find out what is wrong with this pull? all the tests seem to be SUCCESSFUL but the summary says FAILURE. thank you!!

**Comment by kiyoshilee** [comment]
@juliocamarero it's a memory issue on the slave that this is running on. As the job progresses, it eventually runs into a java.lang.OutOfMemoryError. Miguel ran into this as well. I believe now that the shell scripts are in place, we're going to try to optimize this more in order to minimize the memory issues.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/535e9be3b8...d8b90510ec

**Pull request closed without merging**
