### PR TITLE
LPS-68886 Refactoring

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@ithildir Soy cache issue here? Or just TLD?

**Comment by brianchandotcom** [comment]
Much better @leoadb @marcellustavares 

Thanks guys.

**Comment by Ithildir** [comment]
@brianchandotcom, it's still the TLD download error. I asked @stsquared99, but it appears Squid is working correctly. Should I just disable the validation on CI?

**Pull request closed without merging**
