### PR TITLE
master-qa-53662

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-53662

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/95680a4c23...6888bf2d43

**Comment by brianchandotcom** [comment]
@melodywu I merged these because we're having some crazy CI network issues right now

**Pull request closed without merging**
