### PR TITLE
LPS-103843

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by jpince** [comment]
@hhuijser thanks!

@xbrianlee replacing with a specific suppression rather than ignoring the check.

@xbrianlee @austinchiang @john-co actual SF errors at head (PR with changes to the SF tool runs a full SF)

@yichenroy `ci:test:ci:test:sf` in the GH message, but it looks like it still runs fine (so probably just a typo somewhere?)

**Comment by yichenroy** [comment]
@jpince thanks for catching it, we'll fix it as soon as possible, luckily it doesn't seem to be affecting test results.

**Comment by john-co** [comment]
Thanks @jpince, I sent a possible SF fix only for frontend-js-web in https://github.com/jbalsas/liferay-portal/pull/2001

**Comment by hhuijser** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cc9ced2f1e...fc8b499c54

**Comment by jpince** [comment]
@hhuijser known issue https://issues.liferay.com/browse/LPS-101690

**Pull request closed without merging**
