### PR TITLE
LPS-91056 Regen

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/92380392e6...4b88a3646e

**Comment by brianchandotcom** [comment]
@epgarcia @darquesdev see minor changes in upstream. Thx.

**Pull request closed without merging**
