### PR TITLE
LPS-74773 Email verification email is blank if user's language is not English

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @adolfopa

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@pei-jung this is the wrong fix...

Search for

```if (value == null) {```

We do that check everywhere in this class.

With this change, my usage of MapUtil somewhere else, with "null" or "" will suddenly behave differently. We need a different fix for this.

Please resend. Thx.

**Comment by pei-jung** [comment]
Hey @brianchandotcom,

This is a regression bug caused by an extraction. The method `getWithFallbackKey` was introduced in this [commit](https://github.com/sergiogonzalez/liferay-portal/pull/3617/commits/0c47774307ff2613a5ad9a5f3dd7928a0aa2baaa) to remove duplicate logic in `UserLocalServiceImpl` and `SubscriptionSender`, and it's only used in those two classes.

The original logic uses the `Validator` class to check for null:

```
if (localizedValueMap == null) {		
	return defaultValue;		
}		

String value = localizedValueMap.get(locale);		

if (Validator.isNotNull(value)) {		
	return value;		
}		

Locale defaultLocale = LocaleUtil.getDefault();		

return localizedValueMap.get(defaultLocale);
```

When it's extracted out to `MapUtil`, it only checks for null object:

```
if (map == null) {
	return null;
}

V value = map.get(key);

if (value != null) {
	return value;
}

return map.get(fallbackKey);
```

I'll check with @adolfopa and resend.

**Comment by adolfopa** [comment]
@pei-jung Why not use `GetterUtil` like in `SubscriptionSender`?
```
	private String _getLocalizedValue(
		Map<Locale, String> localizedValueMap, Locale locale,
		String defaultValue) {

		return GetterUtil.get(
			MapUtil.getWithFallbackKey(
				localizedValueMap, locale, LocaleUtil.getDefault()),
			defaultValue);
	}
```
I agree with Brian in that all MapUtil methods should behave in the same way wrt null values. I think the real problem is that, unlike in `SubscriptionSender`, we didn't use `GetterUtil` in `UserLocalService`.

**Comment by pei-jung** [comment]
Hey @adolfopa,

Thanks for the suggestion, but using `GetterUtil` does not fix the issue because [`GetterUtil.get`](https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/util/GetterUtil.java#L622-L635) also checks for the null object only and not "" or "null". If `MapUtil.getWithFallbackKey` returns an empty string, `GetterUtil` will return the empty string and not the expected default value.

If we want to keep all MapUtil methods to behave the same way wrt to null values, then in order to fix the issue, we'll have to do a different "getWithFallbackKey" in `UserLocalService` since `MapUtil` doesn't provide what it needs. In other words, we'll need to add back the `_getLocalizedValue` method that was removed in this [commit](https://github.com/sergiogonzalez/liferay-portal/pull/3617/commits/0c47774307ff2613a5ad9a5f3dd7928a0aa2baaa). What do you think?

**Pull request closed without merging**
