### PR TITLE
LPD-18577 Create ScriptManagmentConfiguration component and GroovyScriptUses Modal

### PR DESCRIPTION
**Pull request by danvb112**
Related Issues: 

https://liferay.atlassian.net/browse/LPD-18577
https://liferay.atlassian.net/browse/LPD-18576
https://liferay.atlassian.net/browse/LPD-18578
https://liferay.atlassian.net/browse/LPD-18579

Hey @brianchandotcom, We've reworked the language keys you asked for [here](https://github.com/brianchandotcom/liferay-portal/pull/148464#issuecomment-2017029174), please let me know if there's anything that still doesn't make sense to you

### CODE REVIEW

**Comment by danvb112** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Rename "Liferay DXP" to "Liferay" (this will not work for CE)

Rename "Liferay instance" to "virtual instance"

Rename instance-admin to something else.

Please avoid using new words that are currently not used. Search for Language.properties. I'll compare every term you use with terms in Language.properties, and if I see new terms, the PR will get rejected.

**Comment by brianchandotcom** [comment]
@danvb112 see my comment above.

**Comment by danvb112** [comment]
Sent to: https://github.com/brianchandotcom/liferay-portal/pull/148566

**Pull request closed without merging**
