### PR TITLE
Lps 71298

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@shuyangzhou can you resend

_permissioCache

typo

Can you also call it permissionsMap? I don't want ppl to think it's a *Cache object. 

Thx.

**Comment by shuyangzhou** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/47609

**Pull request closed without merging**
