### PR TITLE
LPS-184766 inline equinox http

### PR DESCRIPTION
**Pull request by tinatian**
FYI @shuyangzhou

### CODE REVIEW

**Comment by tinatian** [comment]
ci:reopen

**Comment by dantewang** [comment]
@tinatian Conflicts, I'll rebase and resend to Brian. 

cc @shuyangzhou

**Comment by dantewang** [comment]
ci:close

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/136380

**Pull request closed without merging**
