### PR TITLE
LRQA-57048 | master

### PR DESCRIPTION
**Pull request by vicnate5**
https://issues.liferay.com/browse/LRQA-57048

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
ci:reopen

**Comment by jpince** [comment]
@lawrence-lee

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7a8b847a3f...39bb6f89ef

**Pull request closed without merging**
