### PR TITLE
master-qa-20639

### PR DESCRIPTION
**Pull request by alee8888**
https://issues.liferay.com/browse/LRQA-20639
https://issues.liferay.com/browse/LRQA-19206

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by alee8888** [comment]
@brianchandotcom 
That error should be fixed in the PR Shuyang sent you here:
https://github.com/brianchandotcom/liferay-portal/pull/33752

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/21113ba63b...84414924e0

**Pull request closed without merging**
