### PR TITLE
POSHI-353 Read in poshi-ext.properties before resolving dependencies

### PR DESCRIPTION
**Pull request by CalumR23**
https://issues.liferay.com/browse/POSHI-353
Kenji said this should be good to merge:
https://github.com/kenjiheigel/liferay-portal/pull/1064

### CODE REVIEW

**Comment by CalumR23** [comment]
ci:reopen

**Comment by CalumR23** [comment]
ci:test:sf

**Comment by CalumR23** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d166c60577...5c2971ecdb

**Pull request closed without merging**
