### PR TITLE
LPS-109291 add aria-hidden="true" attribute to the containing form element

### PR DESCRIPTION
**Pull request by antonio-ortega**
/cc @NemethNorbert

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/37efa31b53...db3b0e2eae

**Comment by brianchandotcom** [comment]
@antonio-ortega @NemethNorbert need to sort things. See db3b0e2

**Pull request closed without merging**
