### PR TITLE
LPD-24168

### PR DESCRIPTION
**Pull request by matijapetanjek**
Backport of https://github.com/brianchandotcom/liferay-portal/pull/150986

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
Matija backports go to `liferay-portal-ee` repo. In this case to the `release-2024.q2` branch.

**Comment by 4lejandrito** [comment]
ci:close

**Comment by 4lejandrito** [comment]
See an example https://github.com/liferay/liferay-portal-ee/pull/33158.

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Sure, this works @4lejandrito

**Pull request closed without merging**
