### PR TITLE
LPS-96730 Rename separator

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
@pavel-savinov

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/327f68acef...e08886e2b6

**Comment by brianchandotcom** [comment]
@epgarcia obviously, not backported. All you.

**Comment by brianchandotcom** [comment]
lbm:backport @jpince fyi

**Comment by epgarcia** [comment]
Thanks @brianchandotcom !

**Pull request closed without merging**
