### PR TITLE
LPS-73009 SF.

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brandizzi** [comment]
@daviddotzhang @hhuijser here is the PR. Sorry for the delay, I had to make some adjustments and, most of all, CI was a bit unreliable.

**Comment by brianchandotcom** [comment]
ci:retest (3 flakes is a bit high, testing again)

**Comment by brianchandotcom** [comment]
@adolfopa @sergiogonzalez these failures are from Adaptive Media flakiness.

```
Portal log assert failure, see above log for more information: 
com.liferay.adaptive.media.exception.AdaptiveMediaRuntimeException$IOException: com.liferay.document.library.kernel.exception.NoSuchFileException: {companyId=20111, repositoryId=35958, fileName=8, cause=java.io.FileNotFoundException: /opt/dev/projects/github/liferay-portal/bundles/data/document_library/20111/35958/8/1.0 (No such file or directory)}
com.liferay.adaptive.media.exception.AdaptiveMediaRuntimeException$IOException: com.liferay.document.library.kernel.exception.NoSuchFileException: {companyId=20111, repositoryId=35958, fileName=8, cause=java.io.FileNotFoundException: /opt/dev/projects/github/liferay-portal/bundles/data/document_library/20111/35958/8/1.0 (No such file or directory)}
	at com.liferay.adaptive.media.image.internal.util.ImageProcessor._getInputStream(ImageProcessor.java:74)
	at com.liferay.adaptive.media.image.internal.util.ImageProcessor.lambda$scaleImage$7(ImageProcessor.java:55)
	at com.liferay.adaptive.media.image.internal.util.ImageProcessor$$Lambda$167/12063245.get(Unknown Source)
	at com.liferay.adaptive.media.image.internal.processor.util.TiffOrientationTransformer.transform(TiffOrientationTransformer.java:63)
	at com.liferay.adaptive.media.image.internal.util.ImageProcessor.scaleImage(ImageProcessor.java:54)
	at com.liferay.adaptive.media.image.internal.processor.AdaptiveMediaImageProcessorImpl.process(AdaptiveMediaImageProcessorImpl.java:110)
	at com.liferay.adaptive.media.image.internal.processor.AdaptiveMediaImageProcessorImpl.lambda$process$47(AdaptiveMediaImageProcessorImpl.java:78)
	at com.liferay.adaptive.media.image.internal.processor.AdaptiveMediaImageProcessorImpl$$Lambda$165/1809447.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.liferay.adaptive.media.image.internal.processor.AdaptiveMediaImageProcessorImpl.process(AdaptiveMediaImageProcessorImpl.java:77)
	at com.liferay.adaptive.media.image.internal.processor.AdaptiveMediaImageProcessorImpl.process(AdaptiveMediaImageProcessorImpl.java:42)
	at com.liferay.adaptive.media.internal.messaging.AdaptiveMediaProcessorCommand$2.execute(AdaptiveMediaProcessorCommand.java:44)
	at com.liferay.adaptive.media.internal.messaging.AdaptiveMediaMessageListener.doReceive(AdaptiveMediaMessageListener.java:81)
	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:26)
	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:74)
	at com.liferay.portal.kernel.messaging.SerialDestination$1.run(SerialDestination.java:58)
	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask._runTask(ThreadPoolExecutor.java:756)
	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask.run(ThreadPoolExecutor.java:667)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.liferay.document.library.kernel.exception.NoSuchFileException: {companyId=20111, repositoryId=35958, fileName=8, cause=java.io.FileNotFoundException: /opt/dev/projects/github/liferay-portal/bundles/data/document_library/20111/35958/8/1.0 (No such file or directory)}
	at com.liferay.portal.store.file.system.FileSystemStore.getFileAsStream(FileSystemStore.java:277)
	at com.liferay.portal.store.ignore.duplicates.wrapper.internal.IgnoreDuplicatesStore.getFileAsStream(IgnoreDuplicatesStore.java:198)
	at com.liferay.portal.store.safe.file.name.wrapper.internal.SafeFileNameStore.getFileAsStream(SafeFileNameStore.java:259)
	at com.liferay.portlet.documentlibrary.store.DLStoreImpl.getFileAsStream(DLStoreImpl.java:320)
	at com.liferay.document.library.kernel.store.DLStoreUtil.getFileAsStream(DLStoreUtil.java:407)
	at com.liferay.portlet.documentlibrary.service.impl.DLFileEntryLocalServiceImpl.getFileAsStream(DLFileEntryLocalServiceImpl.java:1200)
	at com.liferay.portlet.documentlibrary.service.impl.DLFileEntryLocalServiceImpl.getFileAsStream(DLFileEntryLocalServiceImpl.java:1183)
	at sun.reflect.GeneratedMethodAccessor1892.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:163)
	at com.liferay.portal.spring.transaction.DefaultTransactionExecutor.execute(DefaultTransactionExecutor.java:54)
	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:58)
	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:137)
	at com.liferay.portal.spring.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:56)
	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:137)
	at com.liferay.portal.spring.aop.ServiceBeanAopProxy.invoke(ServiceBeanAopProxy.java:169)
	at com.sun.proxy.$Proxy108.getFileAsStream(Unknown Source)
	at com.liferay.document.library.kernel.service.DLFileEntryLocalServiceUtil.getFileAsStream(DLFileEntryLocalServiceUtil.java:545)
	at com.liferay.portlet.documentlibrary.model.impl.DLFileVersionImpl.getContentStream(DLFileVersionImpl.java:60)
	at com.liferay.portal.repository.liferayrepository.model.LiferayFileVersion.getContentStream(LiferayFileVersion.java:106)
	at com.liferay.adaptive.media.image.internal.util.ImageProcessor._getInputStream(ImageProcessor.java:71)
	... 18 more
Caused by: java.io.FileNotFoundException: /opt/dev/projects/github/liferay-portal/bundles/data/document_library/20111/35958/8/1.0 (No such file or directo
```

**Comment by brianchandotcom** [comment]
Merged. Minor SF in upstream @brandizzi

**Pull request closed without merging**
