### PR TITLE
LRQA-40056 Support nested properties in mirrors-get parameters

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-40056

Please publish mirrors-get after merging.

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@jpince what's up with the LocalFilePortal Smoke test failures. Can you review ?Thx.

**Comment by brianchandotcom** [comment]
@pyoo47 see 

I published a new version.

**Pull request closed without merging**
