### PR TITLE
LPS-68572 Make a copy of the map first so the original map remains unmodified and can be reused

### PR DESCRIPTION
**Pull request by rotty3000**
Looks good!

### CODE REVIEW

**Comment by jpince** [comment]
@rotty3000 @mbowerman not sure if these failures are related to this pull. If not, please refer test failures to Shuyang/Matt Tambara

PACLAggregateTest.testPACLTests
```
com.liferay.portal.kernel.process.TerminationProcessException: Subprocess terminated with exit code 134
```
PermissionCheckerTest.testIsGroupOwnerWithOwnerUser
```
Thread Thread[com.liferay.portal.kernel.process.local.LocalProcessExecutor-1,1,] caught concurrent failure: java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.portal.kernel.process.local.LocalProcessExecutor, message=Dumping content of corrupted object input stream to /tmp/corrupted-stream-dump-14767149489573586744529923340729.log
java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.portal.kernel.process.local.LocalProcessExecutor, message=Dumping content of corrupted object input stream to /tmp/corrupted-stream-dump-14767149489573586744529923340729.log
	at com.liferay.portal.test.rule.LogAssertionAppender.append(LogAssertionAppender.java:61)
	at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
	at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
	at org.apache.log4j.Category.callAppenders(Category.java:206)
	at org.apache.log4j.Category.forcedLog(Category.java:391)
	at org.apache.log4j.Category.log(Category.java:856)
	at com.liferay.portal.log.Log4jLogImpl.error(Log4jLogImpl.java:54)
	at com.liferay.portal.kernel.log.LogWrapper.error(LogWrapper.java:69)
	at com.liferay.portal.kernel.process.local.LocalProcessExecutor$SubprocessReactor.call(LocalProcessExecutor.java:381)
	at com.liferay.portal.kernel.process.local.LocalProcessExecutor$SubprocessReactor.call(LocalProcessExecutor.java:262)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask._runTask(ThreadPoolExecutor.java:756)
	at com.liferay.portal.kernel.concurrent.ThreadPoolExecutor$WorkerTask.run(ThreadPoolExecutor.java:667)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.StreamCorruptedException: invalid type code: 23
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1379)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at com.liferay.portal.kernel.process.local.LocalProcessExecutor$SubprocessReactor.call(LocalProcessExecutor.java:329)
	... 5 more
```
RepositoryTest.testFileEntriesAreDeletedWhenDeletingAllRepositories
```
java.lang.AssertionError: {level=ERROR, loggerName=org.hibernate.jdbc.AbstractBatcher, message=Exception executing batch: 
Stacktrace

com.liferay.portal.kernel.exception.SystemException: java.lang.AssertionError: {level=ERROR, loggerName=org.hibernate.jdbc.AbstractBatcher, message=Exception executing batch: 
	at com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery.doPerformActions(DefaultActionableDynamicQuery.java:341)
	at com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery.performActions(DefaultActionableDynamicQuery.java:85)
	at com.liferay.portlet.documentlibrary.service.impl.DLFileEntryLocalServiceImpl.deleteFileEntries(DLFileEntryLocalServiceImpl.java:719)
	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:153)
	at com.liferay.portal.spring.transaction.DefaultTransactionExecutor.execute(DefaultTransactionExecutor.java:54)
	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:58)
	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:127)
	at com.liferay.portal.spring.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:56)
	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:127)
	at com.liferay.portal.spring.aop.ServiceBeanAopProxy.invoke(ServiceBeanAopProxy.java:174)
	at com.sun.proxy.$Proxy104.deleteFileEntries(Unknown Source)
	at com.liferay.portlet.documentlibrary.service.impl.DLFolderLocalServiceImpl.deleteFolderDependencies(DLFolderLocalServiceImpl.java:1242)
	at com.liferay.portlet.documentlibrary.service.impl.DLFolderLocalServiceImpl.deleteAllByRepository(DLFolderLocalServiceImpl.java:207)
	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:153)
	at com.liferay.portal.spring.transaction.DefaultTransactionExecutor.execute(DefaultTransactionExecutor.java:54)
	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:58)
	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:127)
	at com.liferay.portal.spring.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:56)
	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:127)
	at com.liferay.portal.spring.aop.ServiceBeanAopProxy.invoke(ServiceBeanAopProxy.java:174)
	at com.sun.proxy.$Proxy131.deleteAllByRepository(Unknown Source)
	at com.liferay.portal.repository.liferayrepository.LiferayLocalRepository.deleteAll(LiferayLocalRepository.java:210)
	at com.liferay.portal.repository.util.LocalRepositoryWrapper.deleteAll(LocalRepositoryWrapper.java:118)
	at com.liferay.portal.repository.util.LocalRepositoryWrapper.deleteAll(LocalRepositoryWrapper.java:118)
	at com.liferay.portal.repository.util.LocalRepositoryWrapper.deleteAll(LocalRepositoryWrapper.java:118)
	at com.liferay.portal.repository.capabilities.CapabilityLocalRepository.deleteAll(CapabilityLocalRepository.java:182)
	at com.liferay.portlet.documentlibrary.service.impl.DLAppLocalServiceImpl.deleteRepository(DLAppLocalServiceImpl.java:1379)
	at com.liferay.portlet.documentlibrary.service.impl.DLAppLocalServiceImpl.deleteAllRepositories(DLAppLocalServiceImpl.java:400)
	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:153)
	at com.liferay.portal.spring.transaction.DefaultTransactionExecutor.execute(DefaultTransactionExecutor.java:54)
	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:58)
	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:127)
	at com.liferay.portal.spring.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:56)
	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:127)
	at com.liferay.portal.spring.aop.ServiceBeanAopProxy.invoke(ServiceBeanAopProxy.java:174)
	at com.sun.proxy.$Proxy108.deleteAllRepositories(Unknown Source)
	at com.liferay.document.library.kernel.service.DLAppLocalServiceUtil.deleteAllRepositories(DLAppLocalServiceUtil.java:629)
	at com.liferay.portal.repository.RepositoryTest.testFileEntriesAreDeletedWhenDeletingAllRepositories(RepositoryTest.java:161)
	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:61)
	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:61)
	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:61)
	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:61)
	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:61)
	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:61)
	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:61)
	at com.liferay.portal.test.rule.LiferayIntegrationTestRule$1$1.evaluate(LiferayIntegrationTestRule.java:141)
	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:61)
	at com.liferay.portal.kernel.test.rule.BaseTestRule$1.evaluate(BaseTestRule.java:61)
	at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:81)
	at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:81)
	at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:81)
	at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:81)
	at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:81)
	at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:81)
	at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:81)
	at com.liferay.portal.test.rule.LiferayIntegrationTestRule$1$1.evaluate(LiferayIntegrationTestRule.java:141)
	at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:81)
	at com.liferay.portal.kernel.test.rule.BaseTestRule$2.evaluate(BaseTestRule.java:81)
```

**Comment by rotty3000** [comment]
It's highly improbable that the failures are related (not impossible mind
you..)

**Comment by jpince** [comment]
thanks Ray. @shuyangzhou @matttambara can you look into these backend failures? potential flaky tests

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@mbowerman see 00b3f849df8a231529fa19044f3b91073b5a9b85

**Pull request closed without merging**
