### PR TITLE
LPS-61243 Implement validateImportedStagedModel method for BlogsEntryStagedModelDataHandlerTest

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5839ca0cc0...7a33d99658

**Pull request closed without merging**
