### PR TITLE
LPD-21229 & LPD-19057 Followup

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@izaera 
```
	Make a third party NPM package (jQuery) available to other JavaScript code running in DXP using a JavaScript import maps entry client extension.

```

sounds weird because it talks about itself as a client extension. None of the other client extensions do that. I'm partially merging this PR.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/530f581b3a...c4bee6856a

**Comment by izaera** [comment]
Follow up -> https://github.com/brianchandotcom/liferay-portal/pull/149374

**Pull request closed without merging**
