### PR TITLE
LPS-73140 SF

### PR DESCRIPTION
**Pull request by jbalsas**
/cc @brunobasto, @juliocamarero

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:close

@jbalsas @brunobasto 
Something in this PR is still causing integration test batches to timeout. The total test execution time is more than double that of other PRs sent around this time.

**Comment by jbalsas** [comment]
Hey @xbrianlee, is this still about SF? Can you please help us figure out what's the problem? It's really hard for us to figure it out from here 😢

**Comment by xbrianlee** [comment]
@jbalsas 
This isn't related to the SF problem.
I've tweaked some test properties in [this run](https://github.com/xbrianlee/liferay-portal/pull/95) for the failed test batches to try to diagnose the problem.

**Comment by xbrianlee** [comment]
@jbalsas @brunobasto 
We figured out that the execution time is high because some tests are being triggered at the latter half of the 4 hours. Although the same number of server hours are being used for both this PR and other normal 2 hour PRs, the total execution time is higher on this one.
We'll continue to run tests tonight to determine the feasibility of merging these changes.

Thanks for your patience! 😄

**Comment by jbalsas** [comment]
Thanks a lot @xbrianlee! Let us know if there's anything we can do to help!

**Comment by xbrianlee** [comment]
@brunobasto @jbalsas 
Is there any way we can break up these commits to test if there's a problematic one? My last test run when there was low CI server usage still took 2.5 hours (I'd expect this number to be below 2 hours).
Also we're running these commits on an isolated CI environment and comparing them to a PR with no changes to gather execution time metrics. I'll keep you guys posted on the results!

**Comment by xbrianlee** [comment]
^ Disregard

**Pull request closed without merging**
