### PR TITLE
LPS-146203 Test

### PR DESCRIPTION
**Pull request by mbowerman**

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/969d464682...56e9fafd5e

**Comment by brianchandotcom** [comment]
Beautiful. Thanks @mbowerman !

**Pull request closed without merging**
