### PR TITLE
LPS-102649 Show pages tree sidebar

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5e646afffc...aea0454f71

**Comment by brianchandotcom** [comment]
@pavel-savinov I merged this, but I still don't like

x-results-more-refine-keywords={0} result(s) more, refine keywords.

There is no verb in that sentence.

Perhaps:

There are 55 results. Refine keywords to xyz.

I put "xyz" because I'm not sure what the sentence means. Please send a follow up pull to fix it.

**Comment by brianchandotcom** [comment]
@pavel-savinov I reverted this just now because it breaks upgrade tests. See Slack.

**Pull request closed without merging**
