### PR TITLE
LPS-72687 Delete users

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:reopen

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
cc @adolfopa

**Comment by brianchandotcom** [comment]
Great job @ealonso 

@tomwang2011 I literally see this e387e5dc2f401c88a57451dedaebff876e7f46ad everywhere.

@shuyangzhou can you work with @tomwang2011 to annotate this pattern?

Thx.

**Comment by brianchandotcom** [comment]
@tomwang2011 @shuyangzhou I just pushed up e387e5dc2f401c88a57451dedaebff876e7f46ad

**Pull request closed without merging**
