### PR TITLE
LPS-85301 Simplify template to prevent error statements in the console

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
@jpince Latest commit (https://github.com/brianchandotcom/liferay-portal/pull/64552/commits/c871edd70293ab4fa2b314298b290464de8b60a9) should prevent the errors  in the console. 

Thanks for letting me know!

**Comment by brianchandotcom** [comment]
@ruben-pulido real bug. Please resend.

**Comment by ruben-pulido** [comment]
Hi @brianchandotcom

The [test failure](https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/249570/testReport/com.liferay.structured.content.apio.internal.architect.resource.test/StructuredContentNestedCollectionResourceFilteringTest/testGetPageItemsFilterByStructureField/) is unrelated to the changes in this PR. 

StructuredContentNestedCollectionResourceFilteringTest/testGetPageItemsFilterByStructureField is failing intermittently. We'll look into making this test robust.
@cgoncas @juliocamarero

**Comment by jpince** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@ruben-pulido can you resend after stabilizing the test? It's very hard for me to tell what is a real error and what is a flaky test.. thx.

**Comment by ruben-pulido** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/64582

**Pull request closed without merging**
