### PR TITLE
Lps 66047

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by AngeloJ** [comment]
ci:retest

**Comment by AngeloJ** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:stop

**Comment by Preston-Crary** [comment]
Asked @mbowerman to look into the test failures, the ViewTagCloudIncrease test is failing because of a NoSuchResourceActionException.

**Comment by mbowerman** [comment]
@Preston-Crary The problem because the way asset.xml is written doesn't work with the change I made to delete obsoleted resource actions. If you look inside asset.xml, you see:

	<model-resource>
		<model-name>com.liferay.asset</model-name>
		<portlet-ref>
			<portlet-name>com_liferay_asset_tags_admin_web_portlet_AssetTagsAdminPortlet</portlet-name>
		</portlet-ref>
		<root>true</root>
		<weight>1</weight>
		<permissions>
			<supports>
				<action-key>ADD_TAG</action-key>
			</supports>
			<site-member-defaults />
			<guest-defaults />
			<guest-unsupported>
				<action-key>ADD_TAG</action-key>
			</guest-unsupported>
		</permissions>
	</model-resource>

and then later on...

	<model-resource>
		<model-name>com.liferay.asset</model-name>
		<portlet-ref>
			<portlet-name>com_liferay_asset_categories_admin_web_portlet_AssetCategoriesAdminPortlet</portlet-name>
		</portlet-ref>
		<root>true</root>
		<weight>1</weight>
		<permissions>
			<supports>
				<action-key>ADD_CATEGORY</action-key>
				<action-key>ADD_VOCABULARY</action-key>
			</supports>
			<site-member-defaults />
			<guest-defaults />
			<guest-unsupported>
				<action-key>ADD_CATEGORY</action-key>
				<action-key>ADD_VOCABULARY</action-key>
			</guest-unsupported>
		</permissions>
	</model-resource>

Since they are in separate instances inside the xml, we first add the ADD_TAG action for the first instance of model-name=com.liferay.asset, but then we decide that it's obsolete once we get to the second instance which no longer has it, so we delete it. It looks like they are in separate instances because the portlet-name is different. I'll have to do a bit more testing to determine if this can be fixed by a simple change in the xml or if it's going to be trickier.

**Comment by mbowerman** [comment]
@Preston-Crary I sent you another pull request here: https://github.com/Preston-Crary/liferay-portal/pull/139

**Pull request closed without merging**
