### PR TITLE
LPS-55874 SF

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:reopen

**Comment by marcellustavares** [comment]
@jpince could you please double check this pull? I'm not sure if it's related to my changes.

Thanks

**Comment by jpince** [comment]
Unrelated, see https://loop.liferay.com/home/-/loop/feed/4429965

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
