### PR TITLE
LPS-121862

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-121862.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:reopen

**Comment by jonmak08** [comment]
All test failures were unrelated.  A manual forward was approved.  See https://github.com/jonmak08/liferay-portal/pull/2136#issuecomment-799838583.

**Comment by brianchandotcom** [comment]
@jonmak08 can you resolve the LPS tickets for me? Too many. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6f31f01835...8b0550186f

**Pull request closed without merging**
