### PR TITLE
LPS-96376 Update to liferay-npm-scripts v2.1.0 (prettier)

### PR DESCRIPTION
**Pull request by wincent**
We've now updated liferay-npm-scripts to use Prettier (https://prettier.io/) for JS source formatting. This commit updates our dependency and runs `yarn format` on every project that has a "package.json" file, as well as from the top level "modules/" folder to cover everything else.

I used [this Bash](https://gist.github.com/wincent/6eb84ca6e5f7185eb8049e4bd04805f7) script to find all the package.json files that have a "liferay-npm-scripts format" key, and run `yarn format` from those places, verifying that they work if run independently.

Note that because "modules/" has such a package.json file, this means that I effectively confirmed that formatted everything from the top-level as works as well.

I had to add a three "npmscripts.config.js" files to locations where we either don't have any JS source files (and therefore have to instruct Prettier to not run), or where we need to pass a special glob (this is the case at "modules/" because we want to format everything, even JS that may not have a corresponding "package.json" file, but we want to exclude stuff under "classes/"). Includes a `.prettierrc.js` config file which should be picked up by most people's editors. This merely exposes the definitive config from liferay-npm-scripts.

I deleted some malformed files that were test fixtures and which Prettier would otherwise reject; these actually became unreferenced in 8e62321471f6b7d373 anyway:

- modules/apps/frontend-js/frontend-js-loader-modules-extender/src/test/resources/com/liferay/frontend/js/loader/modules/extender/internal/dependencies/config1.js
- modules/apps/frontend-js/frontend-js-loader-modules-extender/src/test/resources/com/liferay/frontend/js/loader/modules/extender/internal/dependencies/config2.js
- modules/apps/frontend-js/frontend-js-loader-modules-extender/src/test/resources/com/liferay/frontend/js/loader/modules/extender/internal/dependencies/empty.js
- modules/apps/frontend-js/frontend-js-loader-modules-extender/src/test/resources/com/liferay/frontend/js/loader/modules/extender/internal/dependencies/malformed.js

I also removed non-standard ESLint config from a couple of places (segments-web and analytics-client-js). All of this is going to go through liferay-npm-scripts, where we will configure it in such a way that it leaves the formatting-related aspects to prettier and only deals with non-presentational code issues.

Excluding modules/test/poshi-runner because otherwise the bot complains
with:

    error: Illegal change to a pull-only subdir modules/test/poshi-runner.

### CODE REVIEW

**Comment by wincent** [comment]
ci:reopen

I believe the SF failures are likely not caused by this diff (they all apply to "build.gradle") files, which I don't believe this PR should affect in any way.

**Comment by john-co** [comment]
ci:test:bundle

**Comment by brianchandotcom** [comment]
Merged.. but I should have waited...

Asking @petershin to fix.

**Comment by wincent** [comment]
Thanks @brianchandotcom. Thanks @petershin: I'll be on Slack in a bit if you need help sorting out any issues.

**Comment by john-co** [comment]
functional test failures are not related to pull.

**Pull request closed without merging**
