### PR TITLE
LPS-188912 New ant task format-source-change-copyrights

### PR DESCRIPTION
**Pull request by ling-alan-huang**
In `CopyrightFormatter.java`, it will replace copyrights with default year 2000.
When we run ant `format-source-current-branch` and it sees it's a new file, it will force the current year.

### CODE REVIEW

**Comment by silverhook** [comment]
I cannot really review it from a technical PoV, but having all pre-existing files carry the year 2000 and start using and enforcing the correct year from now on, sounds like a good compromise to me.

**Comment by yunlinsun** [comment]
Hi @ling-alan-huang ,
Conflicts in this branch. Please fix and resend. Thanks

**Comment by yunlinsun** [comment]
ci:close

**Comment by ling-alan-huang** [comment]
Resent https://github.com/brianchandotcom/liferay-portal/pull/138115

**Pull request closed without merging**
