### PR TITLE
Lps 98426

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4d847453d5...34f3c786d0

**Comment by brianchandotcom** [comment]
@Preston-Crary I still found a lot of modules in *-service that have both aop.api and spring.extender.api references. Is that bad? If so, can you send me a pull to remove? Thx.

**Comment by Preston-Crary** [comment]
@brianchandotcom it can be.  I'll send a follow up pull.  @dantewang @ChiZelin @yuhai make sure for the rest of the migrations to remove the spring.extender.api from the build.gradle see e609649dff20eb8dd7b7309cc1c0713e1f0de534.

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/76171

**Pull request closed without merging**
