### PR TITLE
7.0.x-qa-28836

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-28831 / https://issues.liferay.com/browse/LPS-59837
https://issues.liferay.com/browse/LRQA-28834 / https://issues.liferay.com/browse/LPS-69070
https://issues.liferay.com/browse/LRQA-28836 / https://issues.liferay.com/browse/LPS-64793
https://issues.liferay.com/browse/LRQA-29104 / https://issues.liferay.com/browse/LPS-68693
https://issues.liferay.com/browse/LRQA-29107 / https://issues.liferay.com/browse/LPS-66386
https://issues.liferay.com/browse/LRQA-29108 / https://issues.liferay.com/browse/LPS-66355
https://issues.liferay.com/browse/LRQA-29109 / https://issues.liferay.com/browse/LPS-44455
https://issues.liferay.com/browse/LRQA-29111 / https://issues.liferay.com/browse/LPS-68962

**This is 7.0 only**

cc @brianchiu @jpince @alee8888 @anthony-chu @kenjiheigel @sharonchoi @vicnate5

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@brianchandotcom added an Auto SF commit.  `ant source-format-local-changes` didn't catch these changes, but 'ant format-source' did.

Apparently if the comment closing comes with a space after the end-tag, like:
```
</command> -->
```
then the formatter wants a new line.  Otherwise, if it's:
```
</command>-->
```
then it's happy.

**Comment by brianwulbern** [comment]
We should be able to just revert each of these commits when the associated bugs get fixed.  So to keep this clean and 'revertable', I just resent it here:
https://github.com/brianchandotcom/liferay-portal/pull/44810

**Comment by jpince** [comment]
@hhuijser please see Brian Wulbern's comment in https://github.com/brianchandotcom/liferay-portal/pull/44808#issuecomment-260862683. Not sure if ant format-source-current-branch has the same shortcoming.

**Comment by hhuijser** [comment]
@jpince @brianwulbern 
You probably don't want to use ant format-source-local-changes too much... it only formats files that have been modified, but not ones that have been committed.

ant format-source-current-branch is the one you want.

**Comment by brianwulbern** [comment]
Cool, thanks Hugo.

**Comment by hhuijser** [comment]
No problem. I don't even really know why I added that one. Thinking about it more, it does seem pretty useless :)

**Pull request closed without merging**
