### PR TITLE
LPS-171654 Create object aggregation fields after creating object relationships

### PR DESCRIPTION
**Pull request by seltong**

### CODE REVIEW

**Comment by seltong** [comment]
ci:reopen

**Comment by seltong** [comment]
The failures [here](https://github.com/liferay-objects/liferay-portal/pull/1806) are not related

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ef4de5b33b...6bcf792800

**Comment by brianchandotcom** [comment]
@seltong see 6bcf7928008dc93c8c46cb5db53976c5978aad0b

**Pull request closed without merging**
