### PR TITLE
LPS-58592 Getting double entries for web contents on Asset publisher portlet in staging

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
@ZoltanTakacs can you please backport this? thanks!

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
@zxdgoal there is a functional test failing. Not sure if this is a bug created by the pull or that we need to update the test. 

@evannagayama, can you help us? We are trying to identify the issue here: https://test-1-11.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/483/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=WebcontentpublicationUsecase%23AssetPublisherSiteAndGlobalScopeAccessibility,label_exp=!master/functional-tomcat-mysql/3/summary.html

If that page "Asset Publisher Page" is a regular page, then we have a bug to fix in this pull. If the page is a page template then we need to update the test, can you help us?


thanks!

**Comment by brianchandotcom** [comment]
@evannagayama please resend to me. Thx.

**Pull request closed without merging**
