### PR TITLE
LPS-153324 Add System Objects relationship endpoints

### PR DESCRIPTION
**Pull request by 4lejandrito**
https://github.com/liferay-frontend/liferay-portal/pull/2646#issue-1342091109

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/122301

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@LuismiBarcos @4lejandrito 

git ls-files **ResourceImpl.java

They are all singular.

ProcessResourceImpl
FormStructureResourceImpl

etc.

So ObjectRelationshipsResourceHelper.java and ObjectRelationshipsResourceImpl.java should be singular. Please resend (bypass CI) thx.

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/122317

**Pull request closed without merging**
