### PR TITLE
LPS-56190

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e4c5f61e69...1b79f30312

**Comment by brianchandotcom** [comment]
@mhan810 can you send me the ones for ee-7.0.x specific portlets? Thx Mike.

**Comment by brianchandotcom** [comment]
@mhan810 actually, I dont think there are any...

**Comment by mhan810** [comment]
I'll confirm tomorrow but don't think so

Sent from my mobile device.

**Comment by mhan810** [comment]
All good, no additional ones in ee-7.0.x plugins

**Pull request closed without merging**
