### PR TITLE
LPS-58327 Add tests

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@adolfopa I merged in everything except the tests. Can you format the XML and resend it to me? Like how we do all of our other XML. I know it's just a test, but still. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ba360861c3...19ccb852c8

**Pull request closed without merging**
