### PR TITLE
LPS-66534 Image Editor Capability Process Testing

### PR DESCRIPTION
**Pull request by kenjiheigel**
Resend of the frontend javascript testing of Image Editor components: https://github.com/brianchandotcom/liferay-portal/pull/43498.

cc-ing: @jbalsas, @brunobasto, @jonmak08

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest (I want to see how long it takes)

**Comment by brianchandotcom** [comment]
@kenjiheigel since this is the first of its kind. I'm going to ask @ithildir to review the Gradle and then send it to @natecavanaugh for the JS. Thx.

**Comment by kenjiheigel** [comment]
Thanks @brianchandotcom!

**Comment by jbalsas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
