### PR TITLE
LPS-63675 Only ID and name of each element should be clickable and both of them should be bold

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
cc @vicnate5

**Comment by vicnate5** [comment]
@marcellustavares The main issue on this pull is something we are seeing randomly the last day or so. The tests are taking too long to assert the success messages in the portal and they are disappearing before the assert can be made. I am looking into a solution right now.

**Comment by marcellustavares** [comment]
thx @vicnate5, I've fwd this pull to you.

**Comment by vicnate5** [comment]
Sent fix. will rebase your pull to me. https://github.com/brianchandotcom/liferay-portal/pull/36671

**Pull request closed without merging**
