### PR TITLE
LPS-195348 Take into account rel and url when resolving the editable

### PR DESCRIPTION
**Pull request by rafaellajordao**
https://liferay.atlassian.net/browse/LPS-195348

cc/ @ealonso @victorg1991

### CODE REVIEW

**Comment by rafaellajordao** [comment]
ci:reopen

**Comment by rafaellajordao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/13637
✔️ ci:test:stable - 30 out of 30 jobs passed
❌ ci:test:relevant - 178 out of 198 jobs passed in 4 hours 40 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/aa60ee1d11...b0f18bbcdc

**Comment by brianchandotcom** [comment]
@ealonso see b0f18bbcdc3e572df8d66acec202914349b2e11e

**Pull request closed without merging**
