### PR TITLE
LPS 189386

### PR DESCRIPTION
**Pull request by rotty3000**
- LPS-189386 Liferay ticket workspace
- LPS-189386 Liferay ticket projects and client-extension.yaml files

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:reopen

**Comment by rotty3000** [comment]
cc @gamerson @ipeychev

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1aa6450146...99d9782dd5

**Comment by brianchandotcom** [comment]
@rotty3000 see changes in my origin. Thx.

**Pull request closed without merging**
