### PR TITLE
LPS-98968 SF

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:reopen

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bb61188eb3...a450b7bea7

**Comment by brianchandotcom** [comment]
My bad @achaparro merged.

**Comment by achaparro** [comment]
No worries @brianchandotcom, I don't know if there is any way to try to prevent these cases with SF:
https://github.com/brianchandotcom/liferay-portal/pull/76418/commits/a0d78197cdaf4b835c973901cacaa30531d65511

@hhuijser

**Pull request closed without merging**
