### PR TITLE
Lps 174464

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by 111Anna** [comment]
Hi @shuyangzhou , I checked the pull on CE and DXP, there also no regression appeared.

Here are test results:

CE
Portal Version|GitId|Average Startup (ms)|%|Average Shutdown (ms)|%|Open File|Thread Create|Open Prepared Statement|Open SQL
--|--| --|--|--|--|--|--|--|--|
Baseline| 6005c85e2| 23022.3 |- |3264.6|-| 1833 | 101 | 498| 1007 |
Baseline + PR-129875| - |  22894.6 |0.6%| 3257.3|-0.2%| 1833 | 100 | 504 | 1007 |

DXP
Portal Version|GitId|Average Startup (ms)|%|Average Shutdown (ms)|%|Open File|Thread Create|Open Prepared Statement|Open SQL
--|--| --|--|--|--|--|--|--|--|
Baseline| 6005c85e2| 24986 |- |3925.3|-| 1989 | 114| 560| 1095 |
Baseline + PR-129875| - |  25040 | -0.2%| 3893.3|0.8%| 1989 | 114 | 560 | 1096|

**Comment by shuyangzhou** [comment]
thanks @111Anna !

**Comment by izaera** [comment]
:thinking: This PR won't work because OSGi services implementing `NPMRegistryUpdatesListener` cannot depend on `NPMRegistry` (see [the docs](https://github.com/liferay/liferay-portal/blob/659c411d7f3f98272f58d52e9be87bb7f340d4ba/modules/apps/frontend-js/frontend-js-loader-modules-extender-api/src/main/java/com/liferay/frontend/js/loader/modules/extender/npm/NPMRegistryUpdatesListener.java#L21)).

That's why we used a `ServiceTracker` before. To avoid the deadlock.

The rest looks good to me. There's a problem in [this line](https://github.com/brianchandotcom/liferay-portal/pull/129875/commits/71687de9953571c91bab57d0d1796e8c2bc529b1#diff-c097ee93cf5ca2770d443c1f8c92638928099cf458aeda6494cc6e278fa01ac8R69) too, but that was in the original PR too, so I'll fix it and send a follow-up. Will link it here when it's available, in case it can cause conflicts...

**Comment by izaera** [comment]
Additionally, I think it can also fail and leave things in an inconsistent state because [the line that sets `_state` to `null`](https://github.com/brianchandotcom/liferay-portal/pull/129875/commits/71687de9953571c91bab57d0d1796e8c2bc529b1#diff-c097ee93cf5ca2770d443c1f8c92638928099cf458aeda6494cc6e278fa01ac8R74) can be invoked several times in burst and then the [part where we set it back to non-null again](https://github.com/brianchandotcom/liferay-portal/pull/129875/commits/71687de9953571c91bab57d0d1796e8c2bc529b1#diff-c097ee93cf5ca2770d443c1f8c92638928099cf458aeda6494cc6e278fa01ac8R166-R177) does not guarantee that the `_state` will be set to the last valid value (reflecting the real state of the `NPMRegistry` after the multiple updates).

This didn't happen in the original PR because the `onAfterUpdate` updated the `_state` variable eagerly.

I'm gonna try moving the hash computation to the `NPMRegistry` and make it lazy as in here so that we get the best of both worlds.

It may also help to get rid of the `ServiceTracker`...

**Comment by izaera** [comment]
To make the previous comment clearer, the race condition happens in [line 173](https://github.com/brianchandotcom/liferay-portal/pull/129875/commits/71687de9953571c91bab57d0d1796e8c2bc529b1#diff-c097ee93cf5ca2770d443c1f8c92638928099cf458aeda6494cc6e278fa01ac8R173). 

If the line 171 is executed and sets `state` to a value, then the `NPMRegistry` is updated and invokes [line 74](https://github.com/brianchandotcom/liferay-portal/pull/129875/commits/71687de9953571c91bab57d0d1796e8c2bc529b1#diff-c097ee93cf5ca2770d443c1f8c92638928099cf458aeda6494cc6e278fa01ac8R74), then executions continues with [line 174](https://github.com/brianchandotcom/liferay-portal/pull/129875/commits/71687de9953571c91bab57d0d1796e8c2bc529b1#diff-c097ee93cf5ca2770d443c1f8c92638928099cf458aeda6494cc6e278fa01ac8R174), the `_state` will be set to an obsolete value and never be modified again until another deployment/change in `NPMRegistry` happens.

**Comment by izaera** [comment]
> I'm gonna try moving the hash computation to the NPMRegistry and make it lazy as in here so that we get the best of both worlds.

Another solution can be synchronizing [line 74](https://github.com/brianchandotcom/liferay-portal/pull/129875/commits/71687de9953571c91bab57d0d1796e8c2bc529b1#diff-c097ee93cf5ca2770d443c1f8c92638928099cf458aeda6494cc6e278fa01ac8R74), but since internalizing the hash in `NPMRegistry` may simplify the `ServiceTracker` thing I'm going to try that first.

**Comment by izaera** [comment]
OK, resent (with modifications) as -> https://github.com/brianchandotcom/liferay-portal/pull/129910

Feel free to close this and continue working on top of that if necessary :+1:

**Comment by shuyangzhou** [comment]
@izaera this doc https://github.com/liferay/liferay-portal/blob/659c411d7f3f98272f58d52e9be87bb7f340d4ba/modules/apps/frontend-js/frontend-js-loader-modules-extender-api/src/main/java/com/liferay/frontend/js/loader/modules/extender/npm/NPMRegistryUpdatesListener.java#L21 is a false statement, NPMRegistryUpdatesListener can depend on NPMRegistry just fine. There is no circular dependency here.

The state invalid state statement is also not true, the state is calculated in a pulling style. In case a race happen, next pull will recalculate.

**Comment by shuyangzhou** [comment]
@izaera since you merge the "state" calculation into NPMRegistryImpl, the previous arguments won't matter anymore, as both code have been removed. 
But because of this, the NPMRegistryUpdatesListener support should be removed together, since there is no more NPMRegistryUpdatesListener left. We should not keep the tracking logic for some non-existing thing.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129921

**Comment by izaera** [comment]
Yeah, I'm quite happy with removing `NPMRegistryUpdatesListener`. It was always a very problematic feature :roll_eyes: .

**Comment by izaera** [comment]
>The state invalid state statement is also not true, the state is calculated in a pulling style. In case a race happen, next pull will recalculate.

Not really, as I explained above:

> If the line 171 is executed and sets state to a value, then the NPMRegistry is updated and invokes [line 74](https://github.com/brianchandotcom/liferay-portal/pull/129875/commits/71687de9953571c91bab57d0d1796e8c2bc529b1#diff-c097ee93cf5ca2770d443c1f8c92638928099cf458aeda6494cc6e278fa01ac8R74), then executions continues with [line 174](https://github.com/brianchandotcom/liferay-portal/pull/129875/commits/71687de9953571c91bab57d0d1796e8c2bc529b1#diff-c097ee93cf5ca2770d443c1f8c92638928099cf458aeda6494cc6e278fa01ac8R174), the _state will be set to an obsolete value (LATEST - 1) and never be modified again until another deployment/change in NPMRegistry happens.

So it's not a problem that there won't be `state`. It's a problem that the `state` will hold obsolete information because the `_state = null` statement is not synchronized and can happen in the middle of the state and the NPMRegistry.

The root cause of the problem is that we are assuming that the `NPMRegistry` has an immutable state everywhere in the portal, when it really updates itself internally whenever a deploy/undeploy happens or someone updates a fragment. Thus, any transactional work we may do outside of it (but using it) can fail if, in the middle of the transactional block, the NPMRegistry decides to update itself.

In other words, any transactional action which has more than one call to `NPMRegistry` can find a different state in each of those calls, which can lead to unpredictable behaviour. For example, this can happen in the middle of a resolution (an invocation of the `/js_resolve_modules` servlet) or while we are calculating the hash from outside of the NPMRegistry (internalizing that computation makes it transactional which fixes the problem).

We have not seen any error like this in the past because it's very improbable and most likely wouldn't be reproducible. However, now we are going to cache resolutions forever (in the CDN layer, not DXP) so we'd better make sure that they are right, otherwise, if one of them fails, it will fail for everybody forever (at least until they deploy/undeploy something,  modify a fragment, or someone cleans the CDN). Additionally, the problem will probably be quite hard to diagnose and fix for support.

I'm now working on a follow-up PR to make module resolutions use the state belonging to the hash value with which they were invoked. Basically I'm taking a snapshot of the NPMRegistry state for each hash (the JSModulesCache) and using it. That way, if the NPMRegistry updates itself, the resolution will still use the previous state.

There's also an issue with fragments (NPMRegistryUpdate) which directly modify the NPMRegistry, IINM. I need to change that to use snapshots too, so that updates are transactional actions too. I'll CC you @shuyangzhou in that PR, in case you are curious or can find something that needs to be changed :-) .

**Comment by izaera** [comment]
Regarding:

> this doc https://github.com/liferay/liferay-portal/blob/659c411d7f3f98272f58d52e9be87bb7f340d4ba/modules/apps/frontend-js/frontend-js-loader-modules-extender-api/src/main/java/com/liferay/frontend/js/loader/modules/extender/npm/NPMRegistryUpdatesListener.java#L21 is a false statement, NPMRegistryUpdatesListener can depend on NPMRegistry just fine. There is no circular dependency here.

It was true in the past. I know because I added it the second time I was hit by that problem in the debugger :sweat_smile: .

However, I saw yesterday that the `NPMRegistry` [is not notifying the listeners on activation](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-loader-modules-extender/src/main/java/com/liferay/frontend/js/loader/modules/extender/internal/npm/NPMRegistryImpl.java#L329) so maybe that was changed and fixed it. TBH I didn't investigate it in depth because, as you said, we stopped using it for the hash computation :shrug:

**Pull request closed without merging**
