### PR TITLE
LPS-78459

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@petershin

**Comment by hhuijser** [comment]
ci:test

**Comment by hhuijser** [comment]
ci:reopen

**Comment by timpak** [comment]
ci:close

**Comment by timpak** [comment]
ci:retest

**Comment by timpak** [comment]
Hey @hhuijser 

I'm retesting this because of the modules-compile failure. If it passes, I'll re-open it. If it fails again, could you please take a look into it?

**Comment by timpak** [comment]
ci:reopen

**Comment by timpak** [comment]
@hhuijser the modules-compile failure appears to be a fluke since it is not seen on the second test. The other failures are not related to the changes made. 

@brianchandotcom please review

**Comment by petershin** [comment]
@hhuijser - Cool, this will make it easier for devs to add suppressions  :smile:

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
