### PR TITLE
LPS-83920

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@petershin I'm merging this in for now, but can you make a file like

.lfrbuild-releng-ignore

But call it .lfrbuild-releng-skip-update-file-versions

If it exists in modules/aspectj/aspectj-arquillian-failure, then it'll be ignored

If it exists in modules/aspectj, then it should recurse down (just like .lfrbuild-releng-ignore)

Then just send it to me but cc @Ithildir 

Thx!

**Comment by brianchandotcom** [comment]
@codyhoag fyi

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bf707937ec...37bc916ce8

**Comment by Ithildir** [comment]
@petershin, I think you can reuse the method called `getRootDir`.

**Comment by petershin** [comment]
@Ithildir - Appreciate the tip! Will take a look

**Pull request closed without merging**
