### PR TITLE
LPS-86806

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Will send a backport for this

**Comment by brianchandotcom** [comment]
@pyoo47 how come nothing got triggered?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9f7dbf0be5...d9946390de

**Comment by brianchandotcom** [comment]
Merged.. usually, *Table.java files are generated, not sure why those were not.. but still merging.. not worth digging into.

**Pull request closed without merging**
