### PR TITLE
Master | LRQA-46802, LRQA-46808

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LRQA-46802
https://issues.liferay.com/browse/LRQA-46808

Master only issue, thanks!

cc/ @brianchiu

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@brianwulbern

aef38b127de8749ff316b16ac068d6cd1ffa8036 doesn't look like the rest of our stuff

Please talk to @Hanlf thx

Merged.

@brianchiu fyi

**Comment by brianwulbern** [comment]
@brianchandotcom thanks for the heads up.  Yvonne is fixing that instance, and others that she's come across.

@kenjiheigel, is it feasible (or desirable) to have macro calls taking in two or more vars wrap to a new line via a SF rule?  So push [this](https://github.com/brianchandotcom/liferay-portal/commit/aef38b127de8749ff316b16ac068d6cd1ffa8036#diff-a0fe6e6e4335c34ab23c6b1619204ce6R69) into [this form](https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/macros/DMDocument.macro#L1234-L1238)

**Comment by kenjiheigel** [comment]
@brianwulbern, yeah that's currently in the SF requests actually. Not sure when it will happen, but it's in the queue.

**Pull request closed without merging**
