### PR TITLE
LPS-56692

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by david-truong** [comment]
ci:retest

**Comment by david-truong** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@david-truong can you resend? It's mainly just source formatting.. still lots of inconsistencies.

1.) Avoid chaining.

2.) Fix tabbing and spacing.

I'm quite swamped and it'll make it easier for me to merge if you took note of those little things. Otherwise, pull looks great. Thx @david-truong

**Pull request closed without merging**
