### PR TITLE
JSONWS Infra: proper publication of service wrapped using the ServiceWrapper ability

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by migue** [comment]
ci:retest

**Comment by migue** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/757c7a36f7...05a5eb21fa

**Comment by brianchandotcom** [comment]
@migue see 05a5eb21faf4898e6bf3d65d2720d60c67031315

Compare SpringJSONWebServiceScannerStrategy with JSONWebServiceScannerStrategy

Note how those 2 classes are almost the same, except for how "scan" calls the "isInterfaceMethod" method?

Can you double check to make sure that is on purpose? thx.

**Pull request closed without merging**
