### PR TITLE
LPS-147251, LPS-147252, LPS-147253, LPS-146986, LPS-148717, LPS-146976 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-147251
https://issues.liferay.com/browse/LPS-147252
https://issues.liferay.com/browse/LPS-147253
https://issues.liferay.com/browse/LPS-146986
https://issues.liferay.com/browse/LPS-148717
https://issues.liferay.com/browse/LPS-146976

This is only for master.

@lfbesada
@ruben-pulido
@sandrodw3

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure test is unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/7553
❌ ci:test:stable - 30 out of 33 jobs passed
❌ ci:test:relevant - 30 out of 34 jobs passed in 2 hours 32 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/323e2b3abc...eca770e847

**Comment by brianchandotcom** [comment]
@lfbesada see 309a1cb7a5afc888e33df55a2f9f41f0df3c9e98 can you also update the LPS tickets? Thx.

**Pull request closed without merging**
