### PR TITLE
LPS-96805 Implement testGetRolesPage

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
//cc @nhpatt <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchandotcom** [comment]
@ruben-pulido can we do a quick call tomorrow? I want to merge this in but just had a few questions:

For BaseFormResourceTestCase.java

```
	@Test
	public void testPostFormEvaluateContext() throws Exception {
		Assert.assertTrue(true);
	}

	@Test
	public void testPostFormFormDocument() throws Exception {
		Assert.assertTrue(true);
	}
```

That got removed?

I'm trying to fully understand your notion of "subentity". See you on Skype/Slack tomorrow? Thx.

**Comment by brianchandotcom** [comment]
Also, for RoleResourceTest, can you add @Override to the right methods, and why can't we use @DeleteAfterTestRun to delete _user and _roles?

Thx.

**Comment by ruben-pulido** [comment]
Hi @brianchandotcom!

I've added the missing @overrride and resent.

We can over your questions over the phone. Ping me in slack

**Comment by ruben-pulido** [comment]
Using @DeleteAfterTestRun for _roles results in the following Exception being thrown:

```com.liferay.headless.admin.user.resource.v1_0.test.RoleResourceTest > testGetRolesPage FAILED
    java.lang.IllegalArgumentException: Unable to annotate field private java.util.List com.liferay.headless.admin.user.resource.v
1_0.test.RoleResourceTest._roles because it is not a collection of type com.liferay.portal.kernel.model.PersistedModel```

**Pull request closed without merging**
