### PR TITLE
LPS-157670 Recover missing logic to upgrade from 6.1

### PR DESCRIPTION
**Pull request by achaparro**
LPS-157670-upgrades6.1

### CODE REVIEW

**Comment by achaparro** [comment]
ci:reopen

**Comment by achaparro** [comment]
The test that failed here:
https://github.com/liferay-uniform/liferay-portal/pull/486#issuecomment-1179582630

can be reproduced locally without the changes.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a173a7bc3c...a18fcf7be2

**Comment by brianchandotcom** [comment]
Thx @achaparro !!!

**Comment by brianchandotcom** [comment]
@achaparro can you resend this? The first commit had the wrong LPS. Also, stable would not sync after your change, see

https://test-1-16.liferay.com//userContent/jobs/test-portal-testsuite-upstream%28master%29/builds/1054/jenkins-report.html

```
Error Message
 Portal log assert failure, see above log for more information:  Required upgrades in modules are pending. Run the upgrade process or type upgrade:checkAll in the Gogo shell to get more information.
Stacktrace
junit.framework.AssertionFailedError: 
	at com.liferay.portal.log.assertor.PortalLogAssertorTest.scanXMLLogFile(PortalLogAssertorTest.java:171)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:98)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:88)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXMLLog(PortalLogAssertorTest.java:86)
```

Can you fix it and resend? Thx.

**Pull request closed without merging**
