### PR TITLE
COMMERCE-6327 | master

### PR DESCRIPTION
**Pull request by timpak**
https://issues.liferay.com/browse/COMMERCE-6327

### CODE REVIEW

**Comment by timpak** [comment]
ci:reopen

**Comment by timpak** [comment]
@brianchandotcom this will fix the stable failure on master

**Comment by kenjiheigel** [comment]
Merged to BChan's origin.
https://github.com/brianchandotcom/liferay-portal/commit/6d64d6aba3f4d1080233fbffb7bb26491d996e86

**Comment by kenjiheigel** [comment]
ci:close

**Pull request closed without merging**
