### PR TITLE
LPS-85239 Replace AUI._.unescape for Liferay.Util.unescape

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test

**Comment by jpince** [comment]
@john-co fyi. Also, I don't know if any of these POSHI failures are caused by this pull.

**Comment by brianchandotcom** [comment]
@jpince @john-co can you test this more thoroughly and resend, I have a feeling the test errors are real.

**Comment by john-co** [comment]
ci:reopen

**Comment by john-co** [comment]
@brianchandotcom the failing tests are the same compared to upstream. The code passes automation acceptance testing.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
