### PR TITLE
LPS-79271 Source Formatting

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
@alee8888, @jpince can you guys take a look at this, please? Thanks!

**Comment by alee8888** [comment]
@jbalsas @jpince
The PortalSmoke functional test failure was a fluke, CI could connect to Firefox. QAE is aware of this and looking into it.

For the semantic versioning issue, QAE actually pushed in a fix for it in https://issues.liferay.com/browse/LRQA-39970 so I am going to retest your pull.

**Comment by jbalsas** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7744ca52ab...34a204db37

**Pull request closed without merging**
