### PR TITLE
LPS-74101

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@brianchiu @nicolelau fyi

**Comment by jpince** [comment]
@mhan810 SF failure, and wedeploy backend tests are failing...

**Comment by jpince** [comment]
```
     [java] Exception in thread "main" com.liferay.source.formatter.SourceMismatchException: ./modules/apps/portal-security-wedeploy-auth/portal-security-wedeploy-auth-test/build.gradle expected:&lt;..., version: "1.0.7"
     [java] }[]> but was:&lt;..., version: "1.0.7"
     [java] }[
     [java] ]>
```
and
`java.io.IOException: Start of bundle with id 661 failed with message: Could not resolve module: com.liferay.portal.security.wedeploy.auth.test [661]`
`Unresolved requirement: Import-Package: com.liferay.portal.security.wedeploy.auth.exception`

**Comment by nicolelau** [comment]
@mhan810 - If you haven't already, can you please resend today? We need this changed by tomorrow morning before we cut FP28. Thank you!

**Pull request closed without merging**
