### PR TITLE
LPS-91286 Fix integration test

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso, @brianchiu

**Comment by jkappler** [comment]
@brianchiu, the tests that were failing yesterday were not caused by the commits in this PR. seems it was something else

**Comment by jkappler** [comment]
ci:reopen

**Comment by jkappler** [comment]
ci:retest

**Comment by brianchiu** [comment]
@brianchandotcom This pull is the same as https://github.com/brianchandotcom/liferay-portal/pull/69062 (where you asked if it was safe to merge).

The commits were tested here: 
https://github.com/brianchiu/liferay-portal/pull/1804#issuecomment-470108093

The only unique failure from that ci test relevant run is actually a result of a message boards regression (https://issues.liferay.com/browse/LPS-91608). So this one is safe.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b35a04756a...aa240dc85c

**Comment by brianchandotcom** [comment]
@jkappler @pavel-savinov one minor change in aa240dc85c31cc26a1f6b3fc338eb3fa3d2acbf8

**Pull request closed without merging**
