### PR TITLE
LPS-100891 Updates app-builder-web to use react:component instead of custom script

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:retest

**Comment by brunobasto** [comment]
ci:stop

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/83ba15e4ff...4967e32113

**Comment by brianchandotcom** [comment]
@brunobasto see 4967e32113277070d1d946943b08f28c1dde199b

**Pull request closed without merging**
