### PR TITLE
LPS-63655

### PR DESCRIPTION
**Pull request by natecavanaugh**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 see weird error

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/dabc8983e9...dbc780b915

**Comment by brianchandotcom** [comment]
@pei-jung see 2a28b2477b49315c9dfc2fc17f5b7a7f07a39804 thx

**Comment by pyoo47** [comment]
The weird error here is occurring because there appears to be a strange race condition here. The slave is trying to read its own console log file but when it attempts to access it via http, Jenkins is reporting file not found. This is the first time we've seen this happen we are looking to see if we can find a way to read the file via the file system instead of using http.

**Pull request closed without merging**
