### PR TITLE
[TECHNICAL-SUPPORT] LPS-73857

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by ChrisKian** [comment]
Test errors look unrelated.  Also, [the previous PR](https://github.com/sergiogonzalez/liferay-portal/issues/3952) had no errors.

**Comment by ChrisKian** [comment]
ci:reopen

**Comment by ChrisKian** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest - A Jenkins master had to be restarted.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3911e1acf3...c64d47bb72

**Comment by brianchandotcom** [comment]
@sergiogonzalez @ChrisKian @jonathanmccann

Instead of

```
		try {
			String thumbnailFilePath = getThumbnailFilePath(
				groupId, fileEntryId, fileVersionId, thumbnailType, index);

			DLStoreUtil.deleteDirectory(
				companyId, REPOSITORY_ID, thumbnailFilePath);

			DLStoreUtil.deleteFile(companyId, REPOSITORY_ID, thumbnailFilePath);
		}
		catch (Exception e) {
		}
```
Shouldn't the fix be?

```
		String thumbnailFilePath = getThumbnailFilePath(
			groupId, fileEntryId, fileVersionId, thumbnailType, index);

		try {
			DLStoreUtil.deleteDirectory(
				companyId, REPOSITORY_ID, thumbnailFilePath);
		}
		catch (Exception e) {
		}

		try {
			DLStoreUtil.deleteFile(companyId, REPOSITORY_ID, thumbnailFilePath);
		}
		catch (Exception e) {
		}

```

Please send a follow up pull if I'm right. Thx.

**Comment by ChrisKian** [comment]
Hey @brianchandotcom,

If we attempt to delete a directory but cannot find one, the portal will not throw an error.  This is because we [retrieve a list of matching directories before trying to remove anything](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/documentlibrary/service/persistence/impl/DLContentPersistenceImpl.java#L1794), so we aren't doing a blind deletion.  In fact, we run through the deleteDirectory() method call two other times with different index names, and usually nothing is deleted.  Chances are, anything which would throw an error during deleteDirectory() would also throw the same error during deleteFile().

If anything, the deleteFile() method should be outside of any try/catch due to it's [validation](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/documentlibrary/store/DLStoreImpl.java#L223).  However, I prefer the method call within the try and empty catch because trying to remove something which should already be removed as an extra precaution isn't something we should throw exceptions over.

Let me know what you think, and I can make any revisions as needed.  Thanks!

**Pull request closed without merging**
