### PR TITLE
Lps 68289 56

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@tinatian can you backport to ee-7.0.x for me? This  does not cherry pick. Thx.

**Comment by tinatian** [comment]
Sure, I will.

**Comment by tinatian** [comment]
@brianchandotcom  Please see backport here: https://github.com/brianchandotcom/liferay-portal-ee/pull/15184

**Pull request closed without merging**
