### PR TITLE
LPS-68421 This is no longer necessary

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by vicnate5** [comment]
Hey @sergiogonzalez 

This issue with the pull requests is no longer occuring, but there doesn't seem to be a way to reopen the pulls affected by it. Could you rebase & resend this pull request?

Thanks!

**Comment by Alec-Shay** [comment]
@sergiogonzalez Hi again,

Just bringing this up as another reminder as we're still waiting on the pull request so we can backport it to 7.0.x. Can you re-send this? Thanks!

**Comment by sergiogonzalez** [comment]
Resent here https://github.com/brianchandotcom/liferay-portal/pull/43664

**Pull request closed without merging**
