### PR TITLE
LPS-77239 Using pattern from LPS-77555

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-77239

### CODE REVIEW

**Comment by austinchiang** [comment]
Please do not merge until the PR tester is done running. Thanks!

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by austinchiang** [comment]
ci:test

**Comment by austinchiang** [comment]
Functional test failures are unrelated to this pull.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/58f2792b45...86446af4aa

**Pull request closed without merging**
