### PR TITLE
LPS-79026 Moves component destroy logic into the component registry for a more centralized control

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:test:relevant (@julien, we need to comment that flaky portlethub test)

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by jpince** [comment]
@jbalsas @julien see ignore for the test failure caused by this pull https://github.com/liferay/liferay-portal/commit/6600832be4b71208f7a7cc12462574e546085aa2

**Pull request closed without merging**
