### PR TITLE
master-lps-58550

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LPS-58550

I'm sending this on behalf of @ealonso since the original pull had a poshi failure (https://github.com/brianchandotcom/liferay-portal/pull/30249). The poshi smoke test should be stable now.

cc: @natecavanaugh, @jbalsas, @carloslancha, @brianwulbern

### CODE REVIEW

**Comment by brianchiu** [comment]
Closing this.

@ealonso @brianwulbern
Based on the poshi report, it can't click on the vertical ellipsis next to category. Screenshot shows that it's there though. So probably a test fix?

BWul, can you look into this and resend to me?
https://test-1-14.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/86/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=CPCategories%23AddCategory,label_exp=!master/functional-tomcat-mysql/0/index.html

**Comment by ealonso** [comment]
Hey @brianwulbern,

Could you take a look to the broken test? and send the pull to Brian Chan, again,

Thanks!!!

**Comment by brianwulbern** [comment]
I'm looking into it.

**Comment by brianwulbern** [comment]
Ok, @ealonso @brianchiu 

This should fix the issue: https://github.com/brianchiu/liferay-portal/pull/746

**Comment by brianchiu** [comment]
Resent in:
https://github.com/brianchandotcom/liferay-portal/pull/30297

**Pull request closed without merging**
