### PR TITLE
LPS-65741

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by sharonchoi** [comment]
Virtual instance error, @kenjiheigel will investigate more.

**Comment by brianchandotcom** [comment]
@jbalsas fyi, no longer need to manually include package.json

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/aeef2e1460...43556ca22b

**Comment by jbalsas** [comment]
Awesome! Thanks a lot!

**Pull request closed without merging**
