### PR TITLE
LPS-63951 Fix version

### PR DESCRIPTION
**Pull request by ealonso**
Hey @brianchandotcom,

I've tried to follow the steps on https://loop.liferay.com/home/-/loop/feed/1331196 to use the local version built from the portal-kernel directory, but I always get a compile error. Do you know if I'm doing something wrong?

Thanks.

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @brianchandotcom,

I've added two more commit to this pull request, because I need the *DisplayContext to fix the issue regarding LPS-59296

Regards,
Eudaldo.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@ealonso it's failing because you're trying to convert a

"long to an int"

It finds the new API method, it's just that the new API doesn't work.

Please resend.

**Comment by brianchandotcom** [comment]
@ealonso I ended up merging  just f2433d757add150164855e35dec8a73d29d69eba and 094b962aff6626422967b678aea3f6dd245184c5 for now. I"ll also publish a new jar so you can just use it.

**Pull request closed without merging**
