### PR TITLE
LPS-74100 Possible SQLIntegrityConstraintViolationException when trying to update a company-scoped or group-scoped permission

### PR DESCRIPTION
**Pull request by topolik**
Hi Brian,

https://issues.liferay.com/browse/LPS-74100

/cc @mbowerman

### CODE REVIEW

**Comment by mbowerman** [comment]
Hey @topolik,

Is it safe to assume that the resource Block Id column will be named "resourceBlockId"? I know that is the case for all of Liferay's tables, but couldn't a customer theoretically implement a customization that names that column to something else?

**Comment by topolik** [comment]
Hi @mbowerman,

we don't use foreign keys so we have no way of knowing for sure. We must rely on convention.

It's safe for ServiceBuilder. ServiceBuilder recognizes `PermissionedModel` based on the `resourceBlockId`. You also presumed the entity is always PermissionedModel and there is always LocalService for the model. 

And I doubt there are some custom implementations anyway,

**Comment by mbowerman** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@topolik @mbowerman I'm hesitant to merge in any fixes for Resource Block since we're about to deprecate it. Can you send it to @Preston-Crary and cc @shuyangzhou? See LPS-74143

Thx

**Comment by mbowerman** [comment]
Thanks @brianchandotcom. The pull request has been forwarded to Preston at https://github.com/Preston-Crary/liferay-portal/pull/383.

**Pull request closed without merging**
