### PR TITLE
LPS-96029 Implement assertValid in BlogPostingImageResourceTest

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
@nhpatt

**Comment by brianchandotcom** [comment]
@ruben-pulido this test method name seems wrong too?

AssetDisplayPageHelperTest#testAssetHasDefaultDisplayPage and other method names seem off too?

Not sure about the other test method names in AssetDisplayPageFormProcessorTest. Please resend? Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/91b1b2b64d...aa32b5999a

**Comment by brianchandotcom** [comment]
Thx @ruben-pulido !

1.) Only one change from me in aa32b5999a8ea368cbfcad6d66f7b1db5cbef9b1

2.) For next steps, can you modify src/main/resources/com/liferay/portal/tools/rest/builder/dependencies/base_resource_test_case.ftl

See

Assert.assertTrue(true)

Can you change them to 

Assert.assertTrue(false)

Then regenerate. This will now bubble up all tests that are not truly passing.

For example, when I regenerated

headless-admin-user-test/src/testIntegration/java/com/liferay/headless/admin/user/resource/v1_0/test/BaseRoleResourceTestCase.java

Then it bubbled up that I forgot to implement one of the methods. I'd like to slowly start implementing all of them (just send me the *Test fixes for now). Once you say it's good, then send me a pull where you simply change the generator to modify all *TestCase.java since you already fixed all the missing implementations.

Thx @ruben-pulido ! @nhpatt fyi

**Pull request closed without merging**
