### PR TITLE
LPS-96070

### PR DESCRIPTION
**Pull request by petershin**
Hi Brian,

The `build` script in the [`package.json`](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-builder/package.json#L107) for dynamic-data-mapping-form-builder isn't standard and is causing problems w the Gradle cache.

As a workaround, this pull disables the caching behavior for `npmRunBuild`.  I think this can be done a different way that will make it more robust that won't require any changes from the front-end team

@john-co

### CODE REVIEW

**Comment by john-co** [comment]
Thanks Peter!

cc/ @jeyvison, @brunobasto, @reizero00

**Comment by brianchandotcom** [comment]
@petershin won't this slow the 'ant all' process?

@jbalsas fyi

**Comment by jeyvison** [comment]
> Hi Brian,
> 
> The `build` script in the [`package.json`](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-builder/package.json#L107) for dynamic-data-mapping-form-builder isn't standard and is causing problems w the Gradle cache.
> 
> As a workaround, this pull disables the caching behavior for `npmRunBuild`. I think this can be done a different way that will make it more robust that won't require any changes from the front-end team
> 
> @john-co

Thanks @petershin !

**Comment by brunobasto** [comment]
> Hi Brian,
> 
> The `build` script in the [`package.json`](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-builder/package.json#L107) for dynamic-data-mapping-form-builder isn't standard and is causing problems w the Gradle cache.
> 
> As a workaround, this pull disables the caching behavior for `npmRunBuild`. I think this can be done a different way that will make it more robust that won't require any changes from the front-end team
> 
> @john-co

I will be sending a PR to make that package.json more standard as soon I can test it with latest master. I have a PR from @jbalsas already. Only problem is that I'm having problems building master.

**Comment by brianchandotcom** [comment]
@petershin going to close this since @brunobasto will fix it the right way.

**Pull request closed without merging**
