### PR TITLE
LPS-144128

### PR DESCRIPTION
**Pull request by lipusz**
Please merge. Thanks!

/cc @dantewang

### CODE REVIEW

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
:white_check_mark: `ci:test:relevant`: https://github.com/lipusz/liferay-portal/pull/332#issuecomment-997215795

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fe7fbb4648...b6c038fb40

**Pull request closed without merging**
