### PR TITLE
LPS-90077 Add tests

### PR DESCRIPTION
**Pull request by cgoncas**
Hey @brianchandotcom,

What do you think about add at least the integration tests for the provider?

This is a very sensible piece of code and probably won't change in the future.

Thanks!

### CODE REVIEW

**Comment by cgoncas** [comment]
@jpince I think the failing test it is not related to this pull.

**Comment by jpince** [comment]
ci:test:relevant 

@brianchiu @kyle-miho not sure if we should be concerned about this failure in friendly-url? I was not able to reproduce with the gradle command. The latest build at head just started at 12 PM https://test-1-1.liferay.com/job/test-portal-acceptance-upstream(master)/5561/console

**Comment by kyle-miho** [comment]
@jpince The compile error should be at head

**Comment by kyle-miho** [comment]
https://github.com/liferay/liferay-portal/commit/1be43ff1ee15de6e1893b0de2322ae2cebb85a87#diff-99a5ca2d4c458e337a805769626cf721

**Comment by kyle-miho** [comment]
@jpince  It shouldn't appear again, I think it was upstream, but fixed by: https://github.com/liferay/liferay-portal/commit/6f383727caabb8186ba2eae76b3620409f999a48#diff-99a5ca2d4c458e337a805769626cf721

**Comment by jpince** [comment]
@kyle-miho thanks

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cb1c0d1e40...d1e98666fa

**Comment by brianchandotcom** [comment]
Merged, see my changes in upstream? Thx.

**Comment by brianchandotcom** [comment]
@cgoncas I made quite a few :)

**Pull request closed without merging**
