### PR TITLE
master-qa-28524

### PR DESCRIPTION
**Pull request by vicnate5**
One of our workflow forms tests has proven to be unstable the last couple days. Putting the test in quarantine until we can figure out what is happening. CC @jpince @brianchiu

@marcellustavares This test covers the case of https://issues.liferay.com/browse/LPS-65270. It will still be running on the PR tester, only the failure will not display on the github comment.

### CODE REVIEW

**Comment by vicnate5** [comment]
This only applies to master

**Comment by michaelhashimoto** [comment]
ci:retest - Failed due to broken distribution node.

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
