### PR TITLE
LPS-64383 bump

### PR DESCRIPTION
**Pull request by marcellustavares**
Hi Brian, should I regenerate the `system.packages.extra.mf`?

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:retest

**Comment by pyoo47** [comment]
@marcellustavares @brianchandotcom This pull keeps failing because the top-level build is running out of heap space. I think the toString cache is growing too big. I am working on a code change that will limit the cache size. For this pull, please refer to the jenkins report to see the PR test results:

https://test-1-16.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1384/jenkins-report.html

**Comment by pyoo47** [comment]
I'm going to test my fix for the memory issue with this pull. Please disregard any results that follow this comment.

**Comment by marcellustavares** [comment]
resent to https://github.com/rotty3000/liferay-portal/pull/1191

**Pull request closed without merging**
