### PR TITLE
LPS-105972 Remove configuration property for using initials for user portrait

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-105972](https://issues.liferay.com/browse/LPS-105972).<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:relevant - We aborted all master pull request jobs.  However, we decided to re-run all pulls in @brianchandotcom queue.

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8c606f44cf...d996c9b3c7

**Pull request closed without merging**
