### PR TITLE
LPS-71280 Initialize PermissionCheckerThreadLocal and PrincipalThreadLocal, copy from DLFileEntrySearchTest

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by ealonso** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Pull request closed without merging**
