### PR TITLE
ISSITES-5782 Add basic translations to accomodate sync process to Journal Properties Transformer Listener

### PR DESCRIPTION
**Pull request by willnewbury**

### CODE REVIEW

**Comment by willnewbury** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@willnewbury wrong repo?

**Comment by willnewbury** [comment]
I'm mirroring pulls that were merged for this a while back for ticket https://issues.liferay.com/browse/ISOPS-151. This is for the purposes of fixing the translation sync process, we need actual translations in bundle.properties in these specific branches. It's been a while since I've sent a pull directly, is this the wrong way to do it now?

**Comment by willnewbury** [comment]
@brianchandotcom see pulls like [this](https://github.com/brianchandotcom/liferay-portal/pull/97838) for when we did this previously

**Pull request closed without merging**
