### PR TITLE
LPS-146762 Fix error in client module generated by REST Builder

### PR DESCRIPTION
**Pull request by javierdearcos**
We have a generation error when there is an endpoint that support multiple request content bodies including Multipart

Avoid compilation error checking if the current method is the one that has the multipartBody parameter and so is the one handling the Multipart request body type

Once the PR is merged I will send again the Headless Batch Engine client generation that was affected by this issue.

Sending directly to you to unblock Technical Writers with the client generation

### CODE REVIEW

**Comment by javierdearcos** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/077a71bb87...61c4b26dd8

**Comment by brianchandotcom** [comment]
@javierdearcos I regenerated the headless-batch-engine-client so we're good. thank you!

**Comment by javierdearcos** [comment]
Thank you very much Brian

**Pull request closed without merging**
