### PR TITLE
LPS-60104 deploy IP Geocoder by default so that other modules don't need to deploy its dependencies also

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @sergiogonzalez @adolfopa

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3aed15dfa9...57ae834cab

**Comment by brianchandotcom** [comment]
@juliocamarero this is a good library to have by default too. And it doesn't eat up much.

**Pull request closed without merging**
