### PR TITLE
Lps 72911

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
CC @mhan810 @rotty3000

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
@tinatian please update the ticket to state that session replication now needs this new portal property to work properly, so that QA knows how to test it.

And @alee8888 once this ticket passes QA, please communicate it to document team, as customers need to know this.

**Comment by tinatian** [comment]
@shuyangzhou Sure, already updated the ticket.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f5c99d189d...89e51986b0

**Comment by brianchandotcom** [comment]
@tinatian merged. Please backport (with my changes in upstream). Thx.

**Comment by jorgediaz-lr** [comment]
@tinatian I have backported master code to ee-7.0.x branch but following error is produced: 
`java.io.InvalidClassException: com.liferay.portal.kernel.io.SerializableObjectWrapper; no valid constructor`
more info see: https://issues.liferay.com/browse/LPS-72911?focusedCommentId=1057181&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1057181

**Pull request closed without merging**
