### PR TITLE
LPS-79539 - London theme removed

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @brianchandotcom, just some context. 

Out of the 4 marketplace themes we had for `7.0`, we've already updated 3 and we've decided to discontinue this one.

Based on the feedback we've got, we think this is the least useful. By deleting it, we can focus and improve the existing ones (and others that are coming down the pipeline in the near future).

Hope that makes sense.

Thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Makes sense to me.

**Comment by jpince** [comment]
@jbalsas removed POSHI test here: https://github.com/liferay/liferay-portal/commit/1e98c84994b3062dc67b12530349fd41d3012fd5. Please Albert and I know if you make further themes-related changes in the future so we can update the tests accordingly. Thanks!

**Comment by jbalsas** [comment]
Sorry @jpince, I forgot we actually had a test for this 😢

**Comment by jpince** [comment]
@jbalsas it's ok, I don't expect you to remember what we have tests for, and we have no documentation for this, so we can be doing a better job of communicating as well! BChan suggested next time to look through all of portal code for "London"... it's a very specific case though, so I'm not sure if there are similar cases where this would apply.

**Pull request closed without merging**
