### PR TITLE
LPS-134363, LPS-134673 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-134363
https://issues.liferay.com/browse/LPS-134673

This is only for master.

@ruben-pulido
@ealonso
@jkappler
@veroglez

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure case is unrelated to changes in this PR.
See https://github.com/liferay-echo/liferay-portal/pull/4996
✔️ ci:test:stable - 10 out of 10 jobs passed
❌ ci:test:relevant - 21 out of 25 jobs passed in 1 hour 52 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/27264db4a2...87ac2da335

**Comment by brianchandotcom** [comment]
Glad to see you back @ruben-pulido :)

**Pull request closed without merging**
