### PR TITLE
master-en-681

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LRQA-24040

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 what happened here?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/31f64af953...0dc03321c4

**Comment by pyoo47** [comment]
This one failed while creating the Jenkins report because there was a timeout while retrieving a json file. This could be because of the intermittent jenkins freezing issue we've been seeing although this is the first time I've seen a timeout like this.

```
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:1070: Sourced file: inline evaluation of: `` 				 					import com.liferay.jenkins.results.parser.JenkinsResultsParserUtil;   . . . '' : Typed variable declaration : Method Invocation JenkinsResultsParserUtil.toJSONObject : at Line: 103 : in file: inline evaluation of: `` 				 					import com.liferay.jenkins.results.parser.JenkinsResultsParserUtil;   . . . '' : JenkinsResultsParserUtil .toJSONObject ( JenkinsResultsParserUtil .getLocalURL ( jenkinsJobURL + "/api/json" ) ) 

Target exception: java.net.ConnectException: Connection timed out

	at bsh.BSHMethodInvocation.eval(Unknown Source)
	at bsh.BSHPrimaryExpression.eval(Unknown Source)
```

@michaelhashimoto

**Comment by michaelhashimoto** [comment]
@pyoo47 @brianchandotcom - this is a similar issue to the one found here:
https://github.com/brianchandotcom/liferay-portal/pull/38436#issuecomment-204438573

Yesterday (3/29/16) the test-1-17, test-1-18, test-1-19, & test-1-20 went down.

Sam Tran was able to fix it last night he said:
> the nic on that host malfunctioned, rebooting the host
> they're back online now

**Pull request closed without merging**
