### PR TITLE
LPS-66040 Update gradle dependency since there are methods that use version 2.2.0 portal-kernel

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@inacionery I didn't merge this, because your changes to missing Gradle dependencies didn't seem to be necessary? I mean, lpkg-packager-test was green even without your change?

Did you run into a local compile error that doesn't show up in CI? How do you know it's needed? Please paste the error in the LPS or in the pull to show me why it's needed. Please resend. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/43ad9f86ee...6e03af71a7

**Comment by brianchandotcom** [comment]
@inacionery ok, Andrea told me that you found it via Eclipse, so just merging this in.

**Comment by inacionery** [comment]
@brianchandotcom Thx. :smile:

**Pull request closed without merging**
