### PR TITLE
LPS-58444 Extract portal-settings-web cas.jsp into portal-security-sso-cas module

### PR DESCRIPTION
**Pull request by topolik**
Hi Brian,

with Mike we added the things from here https://github.com/brianchandotcom/liferay-portal/pull/31140#issuecomment-148886148 + fixed some minor issues.

Last 4 commits are the update from the last time.

Thank you.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@topolik see test failures, it's happened a few times now. Please resend.

**Comment by mhan810** [comment]
Hey @brianchandotcom I think it's an issue w/ the CI environment and not the PR.  I reran the same PR after rebasing my branch to master:
https://github.com/mhan810/liferay-portal/pull/798

Everything came back green there.

**Comment by mhan810** [comment]
Actually, I realized Tomas was changing some behavior as well, let me check in w/ Tomas and Jorge before we attempt to merge.

**Comment by topolik** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/31236, thank you.

**Pull request closed without merging**
