### PR TITLE
LPS-80123 Generate base implementations and extending implementations for UADExporter

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke @willnewbury

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@jasonpince what's up with the frontend errors.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/17b2703d07...5ac4d5886f

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
