### PR TITLE
LPS-61694 My organizations should only display the organizations that the user belongs to

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @jorgeferrer @drewbrokke

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6df53372df...5d25c94981

**Comment by brianchandotcom** [comment]
@pei-jung can portal-impl/src/com/liferay/portlet/usersadmin/search/* go in the module? Other modules that need it should be able to use the module's class no? Seems weird you're adding a core class that only a module uses.

Can you send a follow up pull and move out some of those search classes? Thx.

**Comment by pei-jung** [comment]
Hey @brianchandotcom,

Most of the search classes need to stay in core since they're used in core (ie. portal-web/docroot/html/common/init.jsp). I cleaned up two classes that are no longer used and moved the checker class that only used in the module to the module's folder. Here is the pull: https://github.com/brianchandotcom/liferay-portal/pull/34917. Thanks!

**Pull request closed without merging**
