### PR TITLE
LPS-91883 IllegalArgumentException with <script>alert(123);</script> in custom field name

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-91883](https://issues.liferay.com/browse/LPS-91883).<br><br>/cc @pei-jung @stsquared99 @alee8888 @ChrisKian @dejuknow

### CODE REVIEW

**Comment by drewbrokke** [comment]
@jpince I don't think these failures are related.  Can you confirm?

**Comment by jpince** [comment]
@drewbrokke looks ok to me, none of the failures seem related.

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@drewbrokke @pei-jung see c2b9b211c0c2d419094bfffa2a38ca317985f865

**Pull request closed without merging**
