### PR TITLE
COMMERCE-299

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
https://issues.liferay.com/browse/COMMERCE-299

Hi Brian,

I made the changes were suggested in https://github.com/brianchandotcom/liferay-portal/pull/56331#issuecomment-374410568

Thanks for reviewing and for the suggestions! :) 

Best,
Zoli

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1f0e4fb9b0...e2c708a7e0

**Comment by brianchandotcom** [comment]
@ZoltanTakacs see my minor changes in upstream. Thx.

**Comment by ZoltanTakacs** [comment]
Thank you!

**Pull request closed without merging**
