### PR TITLE
LPS-148720 | master

### PR DESCRIPTION
**Pull request by liulukiwi**
https://issues.liferay.com/browse/LPS-148720

cc @david-gutierrez-mesa

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci failed twice for unreleated issue, so I send it to you dirrectly, please merge this, thanks!

**Comment by liulukiwi** [comment]
ci:open

**Comment by liulukiwi** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6366a2ea2d...134774433f

**Pull request closed without merging**
