### PR TITLE
LPS-79709 Makes sure replaceSoyTranslation happens after building files

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @brianchandotcon, this is a resend of https://github.com/brianchandotcom/liferay-portal/pull/58397. Please let the tests finish!

> As @izaera is on PTO, I'm sending #58320 over with the following changes:
> - `Liferay-Bridge-JS-Submodules` renamed as `Liferay-JS-Submodules-Bridge`
> - `Liferay-Top-Head-Authenticated-JS-Resources` and `Liferay-Top-Head-JS-Resources` renamed to `Liferay-JS-Resources-Top-Head-Authenticated` and `Liferay-JS-Resources-Top-Head`
> - Deprecated `Liferay-Export-JS-Submodules`. This is the only key that existed already in `7.0`. It has been replaced in all of our code by `Liferay-Bridge-JS-Submodules`, but renaming it would break existing customer code. We're now logging an error and forbidding any usage in our own code of this key moving forward (through source-formatter).
> 
> Let me know if you think there's anything else we should do for this one.

@brianchiu, could you please monitor this and verify the inconsistent failures are fixed?

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@jpince should I merge this?

**Comment by jbalsas** [comment]
failures don't seem related... @brianchiu, @jpince, are we good to go here?

**Comment by jpince** [comment]
@brianchandotcom these are all known errors, please review and merge

**Comment by jbalsas** [comment]
Hey @brianchandotcom, is there something here you'd like us to change? We need this in to apply then new build tooling to the rest of modules ahead of the release. 

Please, let me know if there's anything else you feel should be done here.

Thanks!

**Comment by jbalsas** [comment]
Just in case, I've rebased and resent to https://github.com/brianchandotcom/liferay-portal/pull/58739. I'll run the tests there.

**Pull request closed without merging**
