### PR TITLE
LPS-167545 Fix control menu markup and move it to a java class

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-167545

@victorg1991

### CODE REVIEW

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/10216

:heavy_check_mark: ci:test:stable - 28 out of 28 jobs passed
:x: ci:test:relevant - 124 out of 134 jobs passed in 3 hours 24 minutes

**Comment by ozysouza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/dd12c76e37...858e69a577

**Comment by brianchandotcom** [comment]
@victorg1991 just 858e69a57748f4b46d424f2f1e44ff7835aed458 thx

**Pull request closed without merging**
