### PR TITLE
LPS-79364 UADEntityDisplay - Change "getUADEntityType*" methods to "getType*"

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-79364](https://issues.liferay.com/browse/LPS-79364).<br><br>Hey Brian, this removes "UADEntity" from the method names in UADEntityDisplay and all its implementations, var names, SB method names, etc.  It does not rename any classes or files.<br><br>/cc @pei-jung @willnewbury

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test

**Comment by drewbrokke** [comment]
@brianchandotcom please allow the tests to finish.

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by drewbrokke** [comment]
ci:test

**Comment by kevin-yen** [comment]
ci:test
There's a issue in CI that we just fixed. We're re-testing affected pulls

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cd6aaccc5b...5dfd640161

**Pull request closed without merging**
