### PR TITLE
LPS-88468 Delete unused API

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by cgoncas** [comment]
Hey @jpince , this pull is green, but was the one that break the test, can you review why this happened?

**Comment by jpince** [comment]
@michaelhashimoto @yichenroy @kenjiheigel this pull deleted a bunch of files in headless-apio, but didn't actually run the tests for that module, just the default `DeclarativeServiceDependencyManagerTest` and `SpringExtenderDependencyManagerTest`. Can you please make sure CI run tests for modules when files are removed?

**Comment by yichenroy** [comment]
@jpince
We'll send the change to consider removed files soon.
 
Relevant ticket: https://issues.liferay.com/browse/LRQA-45606

**Pull request closed without merging**
