### PR TITLE
LPS-107757 Rename variables of type Map so they end with Map

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
//cc @ealonso

**Comment by ruben-pulido** [comment]
//cc @jkappler

**Comment by brianchandotcom** [comment]
@jkappler how come one is called

layout_page_template/export_layout_page_template_entry

the other is called

layout_page_template/import

Is that intentional? Same with ImportMVCActionCommand vs. ExportLayoutPageTemplateEntriesMVCResourceCommand

Please resend.

**Comment by jkappler** [comment]
Just started reviewing :)

**Pull request closed without merging**
