### PR TITLE
LPS-65775 keep previous behavior changed by LPS-62873

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by kenjiheigel** [comment]
Failures are unrelated to this pull. Failing functional tests have been disabled in liferay@897964d^...03e5cb7.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4068a7f606...b5fe97268d

**Pull request closed without merging**
