### PR TITLE
LPS-99058 Format file size

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/13f8b552d4...a29b154406

**Comment by brianchandotcom** [comment]
@hhuijser see

```
{
	"ignore": [
		"**/image_selector.js",
		"**/config.js"
	]
}
```

in modules/apps/item-selector/item-selector-taglib/.npmbundlerrc

Can you sort the ignores? @wincent @jbalsas fyi

**Comment by hhuijser** [comment]
@ling-alan-huang, can you work on this?

**Comment by ling-alan-huang** [comment]
@hhuijser, I added to to-do list.

**Pull request closed without merging**
