### PR TITLE
LPS-65193

### PR DESCRIPTION
**Pull request by danielkocsis**

### CODE REVIEW

**Comment by danielkocsis** [comment]
ci:retest

**Comment by sharonchoi** [comment]
@brianchiu 606Upgrade#View606DataArchive appears to be failing due to a console exception thrown, but the test passes: https://testray.liferay.com/home/-/testray/case_results/46606184?_1_WAR_testrayportlet_redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fruns%2F46605613%2Fdetails%3F_1_WAR_testrayportlet_testrayRunId%3D%26_1_WAR_testrayportlet_filterAssignedUserId%3D%26_1_WAR_testrayportlet_filterErrors%3D%26_1_WAR_testrayportlet_filterErrorsBlankOnly%3D%26_1_WAR_testrayportlet_filterIssues%3D%26_1_WAR_testrayportlet_filterIssuesBlankOnly%3D%26_1_WAR_testrayportlet_filterStatus%3D%26_1_WAR_testrayportlet_filterName%3D%26_1_WAR_testrayportlet_filterPriority1%3D%26_1_WAR_testrayportlet_filterPriority2%3D%26_1_WAR_testrayportlet_filterPriority3%3D%26_1_WAR_testrayportlet_filterPriority4%3D%26_1_WAR_testrayportlet_filterPriority5%3D%26_1_WAR_testrayportlet_filterTestrayComponentId%3D%26_1_WAR_testrayportlet_testrayComponentId%3D%26_1_WAR_testrayportlet_tabs1%3Dall-cases%26_1_WAR_testrayportlet_cur%3D1%26_1_WAR_testrayportlet_delta%3D75%26_1_WAR_testrayportlet_keywords%3D%26_1_WAR_testrayportlet_advancedSearch%3Dfalse%26_1_WAR_testrayportlet_andOperator%3Dtrue%26_1_WAR_testrayportlet_orderByCol%3DstatusLabel%26_1_WAR_testrayportlet_orderByType%3Dasc

`java.lang.Exception:  ## ## 141 Liferay Exceptions were thrown ##  LIFERAY_ERROR: [com.liferay.portal.search.internal.SearchEngineHelperImpl(157)] The addSearchEngineConfigurator method has thrown an exception  LIFERAY_ERROR: Unable to add taglib liferay_layout to context LIFERAY_ERROR: Unable to add taglib liferay_layout to context LIFERAY_ERROR: Unable to add taglib liferay_layout to context LIFERAY_ERROR: Unable to add taglib liferay_layout to context LIFERAY_ERROR: Unable to add taglib liferay_layout to context LIFERAY_ERROR: Unable to add taglib liferay_layout to context LIFERAY_ERROR: Unable to add taglib liferay_layout to context LIFERAY_ERROR: Unable to add taglib liferay_layout to context LIFERAY_ERROR: Unable to add taglib liferay_layout to context LIFERAY_ERROR: Unable to add taglib liferay_layout to context LIFERAY_ERROR: Unable to add taglib liferay_layout to context LIFERAY_ERROR: Unable to add taglib liferay_layout to context LIFERAY_ERROR: Unable to add taglib liferay_layout to context LIFERAY_ERROR: Unable to add taglib liferay_layout to context LIFERAY_ERROR: Unable to add taglib liferay_layout to context LIFERAY_ERROR: Unable to add taglib liferay_layout to context LIFERAY_ERROR: Unable to add taglib liferay_layout to context LIFERAY_ERROR: Unable to add taglib liferay_layout to context LIFERAY_ERROR: Unable to add taglib liferay_layout to context LIFERAY_ERROR: Unable to add taglib liferay_layout to context LIFERAY_ERROR: Unable to add taglib liferay_layout to context LIFERAY_ERROR: Unable to add taglib liferay_layout to context LIFERAY_ERROR: Unable to add taglib liferay_layout to context LIFERAY_ERROR: Unable to add taglib liferay_layout to context LIFERAY_ERROR: Unable to add taglib liferay_layout to context LIFERAY_ERROR: Unable to add taglib liferay_layout to c`

**Comment by kenjiheigel** [comment]
@brianchandotcom, the failure Sharon found is unrelated, and is caused by this issue: https://issues.liferay.com/browse/LPS-65969. This is ok to merge.

**Comment by danielkocsis** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7cda9bef61...a46cb7b15b

**Comment by brianchandotcom** [comment]
@danielkocsis please see my changes in upstream. I renamed a few old things.

**Pull request closed without merging**
