### PR TITLE
LPS-54575 SF

### PR DESCRIPTION
**Pull request by marcellustavares**
cc @epgarcia, @rotty3000

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@marcellustavares this may be a real test failure.

**Comment by marcellustavares** [comment]
k, will resend. thx

**Comment by marcellustavares** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/16db5f6084...c0dbf61df5

**Pull request closed without merging**
