### PR TITLE
LPS-62139 Sort

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/81834bad52...0f40481b5b

**Comment by brianchandotcom** [comment]
@marcellustavares @inacionery nice job guys

**Comment by inacionery** [comment]
:smiley:

**Pull request closed without merging**
