### PR TITLE
Lps 69939

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@dantewang @slnn performance check please

CC @brunobasto

**Comment by shuyangzhou** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/45885 with lib version change

**Comment by brianchandotcom** [comment]
@shuyangzhou I see the Journal* failure for Sybase here and in https://github.com/brianchandotcom/liferay-portal/pull/45882

Can you take a look? And happy new year :)

**Comment by shuyangzhou** [comment]
@tinatian please take care of this tomorrow. It is a configuration issue, we are running out of some sort of cache space.
"     [exec] Caused by: com.sybase.jdbc4.jdbc.SybSQLException: There is not enough procedure cache to run this procedure, trigger, or SQL batch. Retry later, or ask your SA to reconfigure ASE with more procedure cache."

Find the sybase doc to see what we can tweak for this, thanks!

**Pull request closed without merging**
