### PR TITLE
LPS-90038 Always use resource primary key to fetch corresponding asset entry

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by jkappler** [comment]
ci:reopen

**Comment by jkappler** [comment]
ci:retest

**Comment by jkappler** [comment]
Closing for now @brianchiu

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:relevant:norebase

**Comment by brianchiu** [comment]
@jkappler 
Maybe take a look at this one? Those integration test failures look like they're related.

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
@jkappler @pavel-savinov 
I'm going to reopen this. No unique failures :)

**Comment by brianchiu** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
