### PR TITLE
LPS-98370 Add integration test for fragmentEntryLink with no fragmentEntry

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7eb0f49690...62ed43a5b7

**Comment by brianchandotcom** [comment]
@kyle-miho I backported this for you.

**Comment by kyle-miho** [comment]
@brianchandotcom  thanks!

**Pull request closed without merging**
