### PR TITLE
LPS-65946 We're evolving the schema, your services should depend on the proper version

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
PGAnnouncements seems broken with this pull @adolfopa 

Please resend.

**Comment by adolfopa** [comment]
@brianchandotcom I cannot access the test results, the DNS doesn't resolve the test-1-1 hostname. Can you ping someone to take a look at it?

Thanks!

**Comment by adolfopa** [comment]
Finally, I was able to get the logs thanks to @sharonchoi. See https://github.com/brianchandotcom/liferay-portal/pull/40127

**Pull request closed without merging**
