### PR TITLE
LPS-169938 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-169938

This is only for master.

@victorg1991
cc @sandrodw3

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure case is unrelated to changes in this PR.
See https://github.com/liferay-echo/liferay-portal/pull/10507
ci:test:stable - 27 out of 27 jobs passed
ci:test:relevant - 97 out of 109 jobs passed in 1 hour 49 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2e08883c80...d091dab161

**Comment by brianchandotcom** [comment]
@Tim-Cao See 82ae81d8e571b618ac6a8267e8dd9f886bc44bc2 and d091dab161f7fcada1e661caaa724dcaf4191bb5

**Pull request closed without merging**
