### PR TITLE
LPS-89548 Remove jQuery from microblogs-web

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jbalsas js-unit failure. Can you take a look?

@adolfopa merged.

**Comment by jbalsas** [comment]
Hey @brianchandotcom, yeah, I saw this one failing with @john-co yesterday. It's actually a Forms issue... @brunobasto, this has been failing for at least some days, could you guys take a look, please?

**Comment by brunobasto** [comment]
on it now!

**Comment by john-co** [comment]
@brunobasto I plan to temporarily turn off js-unit-jdk8 test batch from ci-relevant so it doesn't pollute pr-tester results. https://issues.liferay.com/browse/LRQA-46551

Please include turning this back on with the fix. Thank you.

cc/ @jbalsas

**Comment by vicnate5** [comment]
@john-co it is too risky to disable the whole batch, find a way to disable only the affect test(s) or module.

cc @jpince

**Comment by john-co** [comment]
temporarily turned off specific failing modules here: https://github.com/brianchandotcom/liferay-portal/pull/67500

**Pull request closed without merging**
