### PR TITLE
LPS-77249 Do not include script when there's no analytics key set

### PR DESCRIPTION
**Pull request by marcellustavares**
cc @inacionery @jbalsas, @brunobasto

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:test

**Comment by inacionery** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@marcellustavares please see my tiny changes in upstream. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/54609ae4c8...38e6fc7195

**Comment by marcellustavares** [comment]
thx @brianchandotcom!

**Pull request closed without merging**
