### PR TITLE
LPS-77291 SF

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@petershin can you fix the SF issues in upstream? Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/48a14da52c...e44622bde1

**Comment by petershin** [comment]
@brianchandotcom - Sent fixes: https://github.com/brianchandotcom/liferay-portal/pull/54647

**Pull request closed without merging**
