### PR TITLE
LPS-62450 Sitemap.xml performance

### PR DESCRIPTION
**Pull request by Preston-Crary**
Hey Brian,

I updated the build.gradle to use the default portal kernel version a3d058e.  Let me know if there is some other way I'm supposed to resolve the build failure.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
I did not add/change PropsValues.BLOGS_IMAGE_MAX_SIZE.

**Comment by brianchandotcom** [comment]
I just fixed those PropsValues errors.. so please ignore.

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@Preston-Crary using "default" was the right way. That tells me to publish a new one, and I'll update it to use the new version number.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/87750e8d45...0ab1ec1d20

**Comment by brianchandotcom** [comment]
@Preston-Crary see 89e2e7bebbd2214caa600094e79570f20b7821e0 

I'm not a big fan of switch statements

**Pull request closed without merging**
