### PR TITLE
LPD-6663 Add PostgreSQL support for schema Validator

### PR DESCRIPTION
**Pull request by achaparro**
Tests passed in https://github.com/liferay-uniform/liferay-portal/pull/1736

cc/ @marianoalvarosaiz

### CODE REVIEW

**Comment by achaparro** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/283f50dc06...7475bf2505

**Comment by brianchandotcom** [comment]
@marianoalvarosaiz @achaparro I made a lot of changes in my origin. Please test.

**Comment by marianoalvarosaiz** [comment]
@brianchandotcom I've tested it and it works.

**Pull request closed without merging**
