### PR TITLE
Lps 77632

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@gregory-bretall doesn't that make the API look weird? If you look at the BrowserSniffer class, they are all isXyz, none of them are isXyzSomeVersion

We also have a getRevision / getVersion method. Why don't we use those instead?

**Comment by gregory-bretall** [comment]
Hi @brianchandotcom thanks for catching that, I made a change to the fix to just use getVersion and the pre-existing isIe method instead. Would you like me to resend the change directly to you or back through the normal reviews process?

**Comment by gregory-bretall** [comment]
Resent to @shuyangzhou in https://github.com/shuyangzhou/liferay-portal/pull/5758

**Pull request closed without merging**
