### PR TITLE
LPS-157951 Check plugin class loader first, then fall back to the cla…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…ss loader of portlet class. It is possible that the portlet class is a bean portlet which comes from another bundle.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@tinatian can you add a test for this? Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e94b41587a...45249a7dad

**Comment by brianchandotcom** [comment]
@tinatian may be add his portlet in https://issues.liferay.com/browse/LPS-157951 to modules/test so we can more easily test this. Thx.

**Pull request closed without merging**
