### PR TITLE
LPS-64500

### PR DESCRIPTION
**Pull request by Ithildir**
I added the version check to `gradle-plugins`, not to `ant-bnd` like I originally planned: unfortunately, the [Gradle plugin](https://github.com/TomDmitriev/gradle-bundle-plugin/) we're using to invoke Bnd doesn't make it possible to fail a build from a Bnd plugin.

cc @jbalsas

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey Andrea, thanks a lot for working on this!

I just have one concern. If I'm reading it correctly, the `checkVersion` test will actually force all bundles with a `package.json` file to forcibly have a `BundleVersion` in their `bnd.bnd` file, right? 

This renders this [code in NpmAnalyzerPlugin](https://github.com/jbalsas/liferay-portal/blob/master/modules/sdk/ant-bnd/src/main/java/com/liferay/ant/bnd/npm/NpmAnalyzerPlugin.java#L362-L380) unreachable, since the check will prevent us from ever getting there.

I imagine it probably makes no sense that `project.getVersion()` returns `null`, but maybe we could add that check as well so future frontend cases are not prevented by this.

Does it make sense? What do you think?

**Comment by Ithildir** [comment]
Hi!
A Gradle project always has a version, it [can't](https://docs.gradle.org/current/dsl/org.gradle.api.Project.html#org.gradle.api.Project:version) be null. If there is no `Bundle-Version` or an explicit assignment in the Gradle script, the version will be `unspecified`.

Anyway, the plugin we use to invoke Bnd [assigns](https://github.com/TomDmitriev/gradle-bundle-plugin/blob/master/src/main/groovy/org/dm/gradle/plugins/bundle/BundleUtils.groovy#L90) the bundle version to `project.version` if a `Bundle-Version` has not been specified. And I think this is really what prevents that code in `NpmAnalyzerPlugin` to be reachable.

**Comment by jbalsas** [comment]
So, this probably stopped working the moment we moved to `gradle`, right? If by using our build system this is necessarily like this, then we probably need to update the [documentation](https://github.com/mwilliams2014/liferay-docs/blob/LRDOCS-1852-L7JS/develop/tutorials/articles/javascript/01-using-es2015.markdown) we had regarding this to make sure there's no confusion.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6255bd770d...8f95af54e3

**Pull request closed without merging**
