### PR TITLE
LPS-79424 SF

### PR DESCRIPTION
**Pull request by marcellustavares**
cc @brunobasto

### CODE REVIEW

**Comment by marcellustavares** [comment]
c:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/59a35d0f98...0f55c1d58c

**Comment by brianchandotcom** [comment]
@marcellustavares I fixed a typo in 0f55c1d58c2c1c084be7cd0853e7873f8b41c1bf

Can you also update PortalImplCanonicalURLTest.java?

Thx.

**Comment by marcellustavares** [comment]
Thx @brianchandotcom! I''ll send a follow up with the test case.

**Pull request closed without merging**
