### PR TITLE
LPS-59186

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@marcellustavares, @epgarcia fyi

**Comment by mhan810** [comment]
@kenjiheigel, @alee8888 fyi

**Comment by mhan810** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
@mhan810, there's some issues with the PR tester atm. At first glance it seems like there may be some actual errors but it's hard to tell cause of the aborted jobs. I'll run the tests again to see if we can get cleaner results.

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
@mhan810, it looks like there's an exception being thrown on start up:
https://gist.github.com/kenjiheigel/07f77df1f9af89606cc7
Here's the full output from the integration tests:
https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/14430/consoleFull

I fetched your branch and reproduced the start up error that is thrown in the integration test. 

There's also some source formatter issues:
https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/14377/AXIS_VARIABLE=2,label_exp=!master/testReport/junit/com.liferay.source.formatter/SourceFormatterTest/testSourceFormatter/

**Comment by mhan810** [comment]
Yep I saw the integration issues will be addressing tonight.  It's not from
this committing but rather from the 54926 one.

Sent from my mobile device.

**Comment by brianchandotcom** [comment]
@mhan810 please resend? Thx.

**Pull request closed without merging**
