### PR TITLE
LPS-63670 Sort attributes

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a11e391a4f...1576d288aa

**Comment by brianchiu** [comment]
@vicnate5 

There are a couple of screenshots here that seem to indicate there is a bug (or something randomly didn't deploy properly). But they're only on the workflow tests? Can you take a look?

1. Navigation Menu portlet undeployed

before2

2. Workflow portlet temporarily unavailable

after4

CC @brianchandotcom

**Comment by vicnate5** [comment]
@brianchiu It only occurs on the 3 tests here (1 is not workflow) https://test-1-19.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/992/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=5,label_exp=!master/functional-tomcat8-mysql56-jdk7/5/

This is a 3 test group on the same server. @kenjiheigel have you seen random deployment issues on the portal instances before?

**Comment by brianchiu** [comment]
CC @michaelhashimoto @pyoo47

**Comment by brianchiu** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
It looks like group 5, axis 5, the following error occurs:
https://gist.github.com/kenjiheigel/94bbfb796a177bc78a52
which may be related to these failures:
WorkflowadminPGPagecomments#ApprovePageCommentPG
PoshiRunner.test[WorkflowadminUsecase#AddDDLRecordWithDoubleApproverDefinition

Seems like it was a random deployment issue with OSGi... but not sure what the root cause is. Strange that it only occurred on that one server though. 

WorkflowadminUsecase#DeactivateAndDeleteUploadedDefinition is in another axis (another server) and fails from the success message.

**Comment by vicnate5** [comment]
@marcellustavares is going to take a look at the DDM slack-trace that occurred, he said he knows what the issue is.

@kenjiheigel @brianchiu @michaelhashimoto @pyoo47. It is very odd this occurred only once though.

The success message fix was sent at https://github.com/brianchandotcom/liferay-portal/pull/36671

**Comment by marcellustavares** [comment]
I've filed a ticket https://issues.liferay.com/browse/LPS-63696

**Pull request closed without merging**
