### PR TITLE
LRAC-4945

### PR DESCRIPTION
**Pull request by shinnlok**

### CODE REVIEW

**Comment by shinnlok** [comment]
ci:reopen

**Comment by shinnlok** [comment]
i think it's failing because liferay/liferay-portal isn't synced?

**Comment by brianchandotcom** [comment]
It's cause I overwrote upstream with a force push because of an error earlier.. I'll merge this.

**Comment by brianchandotcom** [comment]
Can you resend and call it

AnalyticsUsersManager (since it's an instanceable class) 

move it to web.internal.user

Also, run "ant setup-sdk" to use the latest SF which spells out exception names (Exception exception) vs. (Exception e).

Thx.

**Pull request closed without merging**
