### PR TITLE
LPS-69508 Update AlloyEditor version to 1.3.0

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
cc @jbalsas

**Comment by brianchandotcom** [comment]
@pyoo47 fyi broken slave?

Merged.

**Comment by brianchandotcom** [comment]
@ambrinchaudhary please backport. Thx.

**Comment by pyoo47** [comment]
@brianchandotcom Yes, it was a broken slave. It's been taken offline and I will send it to Sam to be rebuilt.

**Pull request closed without merging**
