### PR TITLE
LPS-112999 Fix test

### PR DESCRIPTION
**Pull request by javierdearcos**
This reverts commit 50da3c43fd4e6b2e3d4d51a75d87d0a457559943.

The order is needed to evaluate the type of error properly

### CODE REVIEW

**Comment by javierdearcos** [comment]
ci:reopen

**Comment by javierdearcos** [comment]
Good morning Brian,

I found a problem with some refactoring of the task you made.

I send you the PR directly to you to be more agile because it may be a blocking issue to other teams and to our own team tasks.

I will made the fix as part of the backports in 7.1 and 7.2

Thank you very much. Have a nice day

**Comment by nhpatt** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
ci:reopen

**Comment by jpince** [comment]
Just started reviewing :)

**Comment by jpince** [comment]
Pushed to BChan's origin https://github.com/brianchandotcom/liferay-portal/commit/1382c30839aa9fb7e772d9b03fb993fda74c6e18

**Pull request closed without merging**
