### PR TITLE
LPS-6241 git-commit-plugins

### PR DESCRIPTION
**Pull request by adolfopa**
See also https://github.com/brianchandotcom/liferay-plugins/pull/5132

### CODE REVIEW

**Comment by adolfopa** [comment]
@daviddotzhang @hhuijser @sergiogonzalez @csierra

**Comment by adolfopa** [comment]
ci:retest

**Comment by adolfopa** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@adolfopa please resend? See "AdminActivityInterpreter extends BaseSocialActivityInterpreter" jsp error

**Pull request closed without merging**
