### PR TITLE
LPS-109250 Using remote calls

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
@adolfopa

**Comment by 4lejandrito** [comment]
ci:test:stable

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4ff1fdaf2f...ec627e50a0

**Comment by brianchandotcom** [comment]
@Preston-Crary @4lejandrito @jpince this looks good to me.

Good job team!

**Comment by topolik** [comment]
Hi guys, this is not enough. @Preston-Crary You missed the parts of calling the wrapped checker from inside AdvancedPermissionChecker ... https://github.com/brianchandotcom/liferay-portal/pull/85401/commits/dd71fb14e495bf9166b600ad8c8a759e1962f40a This should have go though the AppSec team review again.

**Comment by Preston-Crary** [comment]
@topolik that's not really how a wrapper should work.  A wrapper should delegate to the default impl, not the other way around.  If we need something different then we should use a different pattern.  If we need to reuse some of the logic in the wrapper then we should extract that logic into some other Util or instance for the wrapper to call.

**Comment by Preston-Crary** [comment]
@topolik, I would have rather have spent the time to discuss with you guys about the problem but was under pressure to get something out quickly.

**Comment by csierra** [comment]
> @topolik that's not really how a wrapper should work. A wrapper should delegate to the default impl, not the other way around. If we need something different then we should use a different pattern. If we need to reuse some of the AdvancedPermissionChecker logic in the wrapper then we should extract that logic into some other Util or instance for the wrapper to call.

hey @Preston-Crary, I believe you are reading our pull upside down. The wrapper that we sent *IS delegating* the calls to the _wrapped_ impl (default impl as you put it, normally `AdvancedPermissionChecker`), as it should be as you point out. But if you look into `AdvancedPermissionChecker` it is making calls to *other* methods of the `PermissionChecker` interface using `this` pointer, and that is wrong, because it skips the wrapper logic. The same thing goes for the staging wrapper and the depot wrapper. In order to fix this we are providing the fully wrapped instance so the implementations can correctly call to other methods and get the wrapped logic. If I recall correctly Service Builder is implemented in a similar way. 

Carlos.

**Comment by Preston-Crary** [comment]
@csierra I modeled this after the [decorator pattern](https://en.wikipedia.org/wiki/Decorator_pattern) exactly how the service builder does it.  A decorator should not modify the behavior of what it is wrapping.  If we need something like that then we can make it using a different pattern.

**Comment by jpince** [comment]
Hey guys, would this be better to discuss over a call sometime? Then maybe you can come to an agreement on the right solution and decide on next steps. @topolik @csierra @Preston-Crary

**Pull request closed without merging**
