### PR TITLE
LPS-71164

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/64b6ed77b2...31beb0c061

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
