### PR TITLE
LRQA-31527, LRQA-31515 | master

### PR DESCRIPTION
**Pull request by sharonchoi**
https://issues.liferay.com/browse/LRQA-31515
https://issues.liferay.com/browse/LRQA-31527

ee-7.0.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/16525

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
