### PR TITLE
LRQA-39077 Add ability to control Github labels in a pull request test

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-39077

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@shuyangzhou can you review this HBM Spring error? I think it was from a pull you sent a few days ago.

**Comment by shuyangzhou** [comment]
@brianchandotcom there are a lot of errors here, but I don't see a hbm spring error. Which one are you referring?

**Pull request closed without merging**
