### PR TITLE
LPS-57742 Fix misspell

### PR DESCRIPTION
**Pull request by izaera**
@brianchandotcom This PR worked perfectly when sent to me (I only added a change in a JSP attribute). The CI hates me :'-(.

See originating PR here: https://github.com/izaera/liferay-portal/pull/139

### CODE REVIEW

**Comment by izaera** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@izaera we can ignore this cluster test. Shuyang knows about the failure and we're working on a fix. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0b2f98164f...985be468b3

**Comment by brianchandotcom** [comment]
Hi @philipjones03 

Good job on the pull.

Please see my changes in upstream. I did find lots of unnecessary code, so we should be careful about that next time.

Thank you.

**Comment by brianchandotcom** [comment]
@izaera please see my changes as well, it'll make you a better reviewer. Thanks bro.

**Comment by brianchandotcom** [comment]
@izaera also, the last commit you did for this pull, I had to rename, because the LPS was for KB and not related. I rewrote it locally before pushing it up.

**Comment by izaera** [comment]
:+1:

**Pull request closed without merging**
