### PR TITLE
COMMERCE-5304 manual forward (CI approved) - include dispatch-lang (backport to 7.3)

### PR DESCRIPTION
**Pull request by igorbeslic**

### CODE REVIEW

**Comment by igorbeslic** [comment]
ci:open

**Comment by igorbeslic** [comment]
ci:help

**Comment by igorbeslic** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/074d516983...71d7570c6f

**Pull request closed without merging**
