### PR TITLE
LPS-107874 Update endpoint to accept time range and interval

### PR DESCRIPTION
**Pull request by darquesdev**
@dgarciasarai @ealonso

### CODE REVIEW

**Comment by dgarciasarai** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
ci:test: relevant

**Comment by brianchandotcom** [comment]
@darquesdev can you resend and retest stable? Thx.

**Comment by darquesdev** [comment]
ci:test:stable

**Comment by dgarciasarai** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dgarciasarai** [comment]
Resent: https://github.com/brianchandotcom/liferay-portal/pulls

**Pull request closed without merging**
