### PR TITLE
LPS-110473 Reactivate backend tests

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-110473](https://issues.liferay.com/browse/LPS-110473).<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
@nhpatt In order to get some of these tests to pass, I had to manually override the test cases to make some changes. Would it be possible to incorporate these changes into the generated test code?

e4225825b4a4: If the field is an email field, be sure the random value is in a valid email address format. Otherwise the service layer throws an exception and the test fails.

bb602be5bc81 and e139736e9906: "accountId" is a required path paramter, so the GraphQL query must also include it, or else no results are returned.

**Comment by drewbrokke** [comment]
@brianchandotcom this pull reactivates the disabled tests found in `account-rest-test`. There are others found in the `headless-admin-user-test` module that I will fix in a later PR.

**Comment by brianchandotcom** [comment]
@drewbrokke it seems like you're copying a lot of generated code? Any way to add interceptors in the generated code to make your tests simpler? Please resend.

**Comment by drewbrokke** [comment]
Hey Brian, you’re correct that I’m copying a lot of generated code, because I don’t have the necessary interceptors at this point. I left a comment for Javier at https://github.com/brianchandotcom/liferay-portal/pull/86621#issuecomment-601772565  regarding the reasons I had to copy the code.

**Pull request closed without merging**
