### PR TITLE
LPS-57658

### PR DESCRIPTION
**Pull request by izaera**
@brianchandotcom I'm afraid CI is broken. This PR was sent to me by Sergio and nothing failed. In fact, it just adds a condition to an if in a JSP, it's totally impossible that that breaks the tests.

Also, the LPS-57728 pulls are failing inconsistently since last week and it looks like a CI error too (the ones failing with the scan xml log).

### CODE REVIEW

**Comment by izaera** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9f15f7d4d9...bf9b4c02ee

**Comment by brianchandotcom** [comment]
@izaera yeah, we had some issues with the slaves not connected. IT told me it's fixed now. Thx.

**Comment by izaera** [comment]
@ZoltanTakacs this fix should go into M7

**Pull request closed without merging**
