### PR TITLE
Lps 73602

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by laszlopap** [comment]
ci:reopen

**Comment by laszlopap** [comment]
Hi @shuyangzhou , @brianchandotcom ,
this pull request was closed by Jenkins, but the commit did not cause the issue which caused Jenkins to close it. Could you reopen and review it please?

Thanks,
László

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by pyoo47** [comment]
@laszlopap @shuyangzhou - These failures were caused by a bad slave in CI that was picking up jobs and failing them immediately.

**Comment by shuyangzhou** [comment]
@pyoo47 can we find a way to not close pulls that failed by CI causes?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2ec03ad4be...c44c2cfe08

**Pull request closed without merging**
