### PR TITLE
LPS-65546 Cleanup shopping bnd

### PR DESCRIPTION
**Pull request by peterfellwock**

### CODE REVIEW

**Comment by peterfellwock** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
merging..

is 

```
[Export com.liferay.shopping.service.impl,  has 1,  private references [com.liferay.shopping.service.base], ]
[Export com.liferay.shopping.service.impl,  has 1,  private references [com.liferay.shopping.service.base], ]
```

OK?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4105f9b2ab...67566750c3

**Comment by peterfellwock** [comment]
Yes it should be OK.

**Pull request closed without merging**
