### PR TITLE
LPS-78135 Provide API and Tag for clay:geomap

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/035486682b...06a8260860

**Comment by brianchandotcom** [comment]
@julien please see my changes in upstream. Thx.

**Comment by julien** [comment]
@brianchandotcom looks good to me. Thanks.

**Pull request closed without merging**
