### PR TITLE
Lps 102798

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6351f0b21f...1a41c65a6a

**Comment by brianchandotcom** [comment]
@pavel-savinov fyi

**Comment by brianchandotcom** [comment]
@epgarcia see proper fix from @shuyangzhou

**Comment by epgarcia** [comment]
Thanks @brianchandotcom and @shuyangzhou for the review. However, I'm afraid that with your fix, the support for non-instanceable portlets in different page experiences was lost (see https://issues.liferay.com/browse/LPS-106351).

**Comment by arboliveira** [comment]
@epgarcia @pavel-savinov @shuyangzhou Top embedded Search Bar was also affected. Please see my comments here: https://issues.liferay.com/browse/LPS-106351?focusedCommentId=2046798&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2046798 Thanks!

**Pull request closed without merging**
