### PR TITLE
LPS-88949 Set selected plid explicitly since we don't have it as a public render parameter anymore

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by ealonso** [comment]
cc: @kyle-miho, @brianchiu

**Comment by brianchiu** [comment]
Thanks @ealonso. Taking a look.

**Comment by brianchiu** [comment]
One of those failures may be legitimate.

**Comment by brianchiu** [comment]
ci:close

**Comment by brianchiu** [comment]
@pavel-savinov Can you take a look?
This pull did have a legitimate failure (caught by WidgetPagesUseCase#SitesPrivatePagesPermissions).

The problem is that private pages are added to public pages.

**Pull request closed without merging**
