### PR TITLE
LPS-65793

### PR DESCRIPTION
**Pull request by juangon**
Second attempt from https://github.com/brianchandotcom/liferay-portal/pull/44498. Hope now it looks better.

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@juangon please see upstream for my changes. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c4aeeba717...24c857e902

**Pull request closed without merging**
