### PR TITLE
LRQA-62752 Explicitly set appserver types where this test can run on instead of being arbitrary

### PR DESCRIPTION
**Pull request by vicnate5**
This can go back to 7.2.x

### CODE REVIEW

**Comment by vicnate5** [comment]
Sent last commit to 7.1.x only https://github.com/brianchandotcom/liferay-portal-ee/pull/32404

**Comment by vicnate5** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/98b6885c8f...67a4f63148

**Comment by brianchandotcom** [comment]
@vicnate5 I backported this to 7.3.x and 7.2.x

**Pull request closed without merging**
