### PR TITLE
LPS-93299 Autogenerated

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:reopen

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b8e0eafd8e...3c2608df8e

**Comment by brianchandotcom** [comment]
@victorg1991 see upstream for my changes.

**Pull request closed without merging**
