### PR TITLE
LPS-66534 Image Editor Capability Process Testing

### PR DESCRIPTION
**Pull request by jbalsas**
Hey Brian,

This is PR adds an initial set of frontend unit tests for the different image processing capabilities we currently have. The main goal is to test and document the expected behaviours of the image editing capabilities.

This is meant to serve as a starting point for frontend tests in portal. We'll be running them manually for now and start working with @kenjiheigel on creating the required infrastructure to integrate them in the CI as soon as possible. 

Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:retest

**Comment by jpince** [comment]
@brianchandotcom failures are unrelated, good to merge from a poshi perspective.

**Comment by jbalsas** [comment]
rebased and pushed

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
Hey @brianchandotcom, I'm closing this one for now. Based on the latest Gradle changes regarding Front-End we did in https://github.com/brianchandotcom/liferay-portal/pull/42698 I'll work with @kenjiheigel to send a fully integrated PR for only one test to set the base for this.

Thanks!

**Pull request closed without merging**
