### PR TITLE
LPS-186526

### PR DESCRIPTION
**Pull request by ealonso**
Execute baseline for failing module and manual forward, since other tests failures are unrelated see: https://github.com/liferay-echo/liferay-portal/pull/12344#issuecomment-1581949119

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6ead924495...d154c73a98

**Comment by brianchandotcom** [comment]
@ealonso just d154c73a98c5a78096e104d1cf0615152cfa2da5

@ling-alan-huang please SF enforce

**Comment by ling-alan-huang** [comment]
SF fix: https://github.com/brianchandotcom/liferay-portal/pull/136589

**Pull request closed without merging**
