### PR TITLE
LPS-98169 Submit new comments to backend

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5323d9ae12...da52e1b495

**Comment by brianchandotcom** [comment]
lbm:backport 

@p2kmgcl @victorg1991 I was not able to cherry pick this for you.

@jbalsas @wincent 7.2.x is starting to diverge even more now.

**Comment by wincent** [comment]
@p2kmgcl, @andresfulla: I sent https://github.com/brianchandotcom/liferay-portal/pull/75800 as a follow-up, because we don't need (and shouldn't have) lint suppressions in the layout-content-page-editor-web files from now on.

**Pull request closed without merging**
