### PR TITLE
LPS-65716

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0367d16746...319fc17189

**Comment by brianchandotcom** [comment]
@hhuijser I defaulted it to 80.. see 64aba26a7011f83730145a75a64708ce5d4af6bb

Also, we should change?

```
"> 80: "
```

And why is

```
		_maxLineLength = GetterUtil.getInteger(
			System.getProperty("source.formatter.max.line.length"), 80);

```

before

```
		_addMissingDeprecationReleaseVersion = GetterUtil.getBoolean(
			getProperty("add.missing.deprecation.release.version"));
```

**Comment by hhuijser** [comment]
@brianchandotcom

Sent pull for the warning message.

_maxLineLength is property in build.properties, where all the others are from source-formatter.properties, so kept em in different groups...

**Pull request closed without merging**
