### PR TITLE
LPS-152611 baseline

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-152611

@ealonso

### CODE REVIEW

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/10277

:heavy_check_mark: ci:test:stable - 26 out of 26 jobs passed
:x: ci:test:relevant - 311 out of 365 jobs passed in 4 hours 26 minutes

**Comment by ozysouza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f0fcd00117...7378aacc4a

**Comment by brianchandotcom** [comment]
Thx @ealonso just 7378aacc4aeea948019388b77d042ac45703c0e8

**Comment by brianchandotcom** [comment]
@ealonso nice job on this big refactor

**Pull request closed without merging**
