### PR TITLE
LPS-115522 build service

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:reopen

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:reopen

**Comment by reizero00** [comment]
@brianchandotcom 

Hey Brian this is to fix a blockage in stable on upstream. buildService needed to be rerun before merging and @achaparro takes care of it here.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d081fe51e0...1af45e3e31

**Comment by brianchandotcom** [comment]
thx @achaparro my bad!

**Pull request closed without merging**
