### PR TITLE
LRQA-36280, LRQA-36512, LRQA-35364 | master

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-35364

cc @austinchiang see 319dcd4

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:retest

**Comment by anthony-chu** [comment]
@brianchandotcom please let this pull request test finish.

**Comment by anthony-chu** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0f7928a08b...924fbc4e63

**Pull request closed without merging**
