### PR TITLE
LPS-72930 ExportLayoutsMVCActionCommand now uses the enhanced logic from Helper class

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by jpince** [comment]
ci:stop

**Comment by jpince** [comment]
ci:retest

**Comment by laszlopap** [comment]
Hello @jpince ,

Could you please re-test or merge this? (i think the jenkins fails are not connected to the PR)

**Comment by janditibi** [comment]
ci:reopen

**Comment by matethurzo** [comment]
@laszlopap there are multiple export/import related failures in the pull. can you please investigate them? thanks

**Comment by laszlopap** [comment]
ci:reopen

**Comment by laszlopap** [comment]
ci:retest

**Comment by zsigmondrab** [comment]
ci:reopen

**Comment by zsigmondrab** [comment]
I checked the thrown ci errors and the are irrelevant as they came at other pull requests also at time of sending which didn't contain any staging related modifications.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9a9d9a99d8...d5a6e98b7b

**Comment by brianchandotcom** [comment]
@matethurzo please check my changes in upstream? Thx.

**Pull request closed without merging**
