### PR TITLE
LPS-81950 LayoutSiteNavigationMenuItem fix

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by zoltancsaszi** [comment]
ci:reopen

**Comment by zoltancsaszi** [comment]
ci:retest

**Comment by zoltancsaszi** [comment]
Poshi test failed, because product menu closed while tests were running.

**Comment by matethurzo** [comment]
@brianchandotcom previous error didn't occur probably CI hiccup

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@zoltancsaszi @matethurzo this is good enough 8336e6c thx

**Pull request closed without merging**
