### PR TITLE
LPS-64144 we shouldn't use the service.ranking for ordering lists

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
We have applied this change to all your components: @marcellustavares, @sergiogonzalez, @drewbrokke, @jorgeFerrer, @peijung, @lionah, @arboliveira

**Comment by juliocamarero** [comment]
@marcullustavares @sergiogonzalez if you are using the service ranking in other frameworks for ordering lists we should apply this change also. thanks!

**Comment by marcellustavares** [comment]
Thanks @juliocamarero

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/77c4fe3d73...2d101092a4

**Pull request closed without merging**
