### PR TITLE
LPS-62268 Improve scope selector look and feel

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@Ithildir I've been getting this "PermissionChecker permissionChecker " compile error randomly. Can you look into it? I don't see it locally. I think it may have to do with the Gradle parallel task.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by Ithildir** [comment]
Looking into it!

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/067125d832...38a89948f6

**Pull request closed without merging**
