### PR TITLE
[TECHNICAL-SUPPORT] LPS-76229

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @ericyanLr @rotty3000

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by jpince** [comment]
Ci:reopen

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bca1454e13...26163e3160

**Comment by brianchandotcom** [comment]
Nice job @ericyanLr and @jonathanmccann

**Pull request closed without merging**
