### PR TITLE
LRQA-39462 Add max axis sizes and globs for different batches | master

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRQA-39462

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test

**Comment by michaelhashimoto** [comment]
ci:reopen

**Comment by michaelhashimoto** [comment]
@brianchandotcom - This should be safe to merge, this is needed to fix the modules-integration/modules-unit tests.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
