### PR TITLE
LPS-57286 Moves panel apps to sites

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8c171f74b6...a1521de3ca

**Comment by brianchandotcom** [comment]
@ealonso please see 2b60eb1b4272ad15829597c382ce1d3d883a8810

If what I did is wrong, please rename the var and have the constant value match the var name.

Thx

**Pull request closed without merging**
