### PR TITLE
LCD 36867

### PR DESCRIPTION
**Pull request by rotty3000**
- **LCD-36867 correct predicates**
- **LCD-36867 enable logging the result of every operation**
- **LCD-36867 sort**
- **LCD-36867 improve debug logs**
- **LCD-36867 implement better change detection**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:reopen

**Comment by rotty3000** [comment]
@brianchandotcom this is critical and we need it backported to quarterlies.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e372086b54...8cc9399dd0

**Comment by brianchandotcom** [comment]
@rotty3000 see changes in my origin. Thx.

**Pull request closed without merging**
