### PR TITLE
Lps 71383

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
Missing path should be fixed here: https://github.com/brianchandotcom/liferay-portal/pull/47726

**Comment by brianwulbern** [comment]
I couldn't load the poshi report, but there's a missing success message assertion in the log.

cc @jpince

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@tinatian can you see my changes and send me a backport to ee-7.0.x (there are specific themes there).

Thx!

**Comment by tinatian** [comment]
For backport to ee-7.0.x, please see https://github.com/brianchandotcom/liferay-portal-ee/pull/16372

**Pull request closed without merging**
