### PR TITLE
LPS-161509 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-161509

This is only for master.

@ruben-pulido
cc @ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure cases are unrelated to changes.
See https://github.com/liferay-echo/liferay-portal/pull/9579
❌ ci:test:stable - 26 out of 27 jobs passed
❌ ci:test:relevant - 258 out of 314 jobs passed in 3 hours 13 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0a4b3b23c3...05d8d0c4b2

**Comment by brianchandotcom** [comment]
@ruben-pulido just 24734291878245b5a70c837864a833f7357b1114

**Pull request closed without merging**
