### PR TITLE
Lps 76789

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@shuyangzhou rebase error, please resend? Sorry!

**Comment by lanceji92674957** [comment]
@shuyangzhou working on it

**Comment by shuyangzhou** [comment]
Thanks @lanceji92674957 ! You can send it to @brianchandotcom directly.

**Comment by lanceji92674957** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/54227

cc @shuyangzhou

**Pull request closed without merging**
