### PR TITLE
LPS-78826

### PR DESCRIPTION
**Pull request by marco-leo**
Bug fixes. Adding missing setters.

### CODE REVIEW

**Comment by marco-leo** [comment]
ci:test

**Comment by marco-leo** [comment]
@brianchandotcom the errors are really not related with my pull

**Comment by ealonso** [comment]
ci:reopen

**Comment by marco-leo** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ae273dded1...19305172aa

**Pull request closed without merging**
