### PR TITLE
Lps 54321

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@mtambara backport please, thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d5fb549139...4582e80690

**Comment by brianchandotcom** [comment]
@willnewbury can you review and retest with my changes? Thx!

**Comment by willnewbury** [comment]
@brianchandotcom changes don't seem to break anything

**Pull request closed without merging**
