### PR TITLE
LPS-56537 - Extract frontend-editors-web to individual editor modules

### PR DESCRIPTION
**Pull request by mjbradford89**
Hey Brian,

Attached is another update for https://issues.liferay.com/browse/LPS-56537.

PortalWebResources editor constants have been namespaced, packages have been changed from 'editors' to 'editor', migration commits have been condensed, and a few other namespacing changes have been made since the last pull.

I also had to reorganize all the commits to make it easier for you to review (it was getting out of hand with the renames).

Please let me know if there are any more issues.

Thanks!

Edit:
@jbalsas @brianchandotcom 
As for moving our third party resources out of portal-web, I'm all for it.  But I think it should be done on a different ticket than this one.  If you agree Brian, I will create a few tasks under https://issues.liferay.com/browse/LPS-54472 for those changes. Thanks!

### CODE REVIEW

**Comment by mjbradford89** [comment]
Shucks. I will fix the SF issue and retest.

**Comment by mjbradford89** [comment]
ci:retest

**Comment by mjbradford89** [comment]
ci:retest

**Comment by mjbradford89** [comment]
ci:retest

**Comment by mjbradford89** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ff71dd4f3f...1500077080

**Comment by brianchandotcom** [comment]
1.) change them all to just diffs

2.) andrea, please review all build.gradle inside frontend-editor/**

3.) Rename getCKEditorPath to getEditorCKEditorPath

4.) Move language keys to frontend-editor-lang module, which we want it to never deploy.

**Comment by mjbradford89** [comment]
new pull for remaining changes: https://github.com/brianchandotcom/liferay-portal/pull/31253

Hey @jbalsas, I also created a task for moving third-party resources to modules: https://issues.liferay.com/browse/LPS-59672.  I'm planning on working on that after the frontend-editor-lang module.

Thanks!

**Pull request closed without merging**
