### PR TITLE
Lps 69919

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@mhan810 this is the long overdue integration test for sb module external datasource support you asked months ago, sorry for the delay.

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3c0d86b178...362b59cae0

**Comment by brianchandotcom** [comment]
@ithildir can you make sure that "build-services" in portal-impl will ultimately also regenerate this new module in test?

thx

**Comment by Ithildir** [comment]
@brianchandotcom, it should do it already, since `build-services` calls the `buildService` Gradle task in the whole `modules` directory. BTW, I sent https://github.com/brianchandotcom/liferay-portal/pull/51138 to regenerate the services in this new module: last night, one of my pulls was closed because of that, so maybe they're out-of-sync.

**Pull request closed without merging**
