### PR TITLE
LPS-108500 delete no necessary sticker-static class

### PR DESCRIPTION
**Pull request by edalgrin**
/cc @boton @AliciaGarciaGarcia

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:test:relevant @yichenroy tests didn't initiate?

**Comment by yichenroy** [comment]
@jpince looks like it was a network issue. 
The github webhook never received signals from this pull request (no CI bot comment when the pull request is opened).

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/85fedd3f47...44cec26c13

**Pull request closed without merging**
