### PR TITLE
LRQA-45313 ReleaseInfo 7.2.10 build number

### PR DESCRIPTION
**Pull request by CAustin582**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Not merging, I don't think we'll need this for 7.2. Ask @amosfong thx.

**Comment by jpince** [comment]
ci:reopen @brianchandotcom even if we don't need it for licensing, we still need this for the text in the log during startup, which would look something like this:

`Starting Liferay DXP 7.2.10 GA1 (Mueller / Build 7210 / January 7, 2019)`

It's "7210" from the line above that I'm talking about

**Comment by brianchandotcom** [comment]
Talk to Amos.... it'll just be Liferay DXP 7.2.0 GA1

**Comment by jpince** [comment]
ci:reopen @amosfong Brian said we won't be doing single core for this release (he said "common core" which means two separate bundles for CE & DXP)

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
