### PR TITLE
LPS-109082 Test layout with row is converted to PageDefinition correctly

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
//cc @ealonso

**Comment by ruben-pulido** [comment]
//cc @jkappler

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b4baafc775...b094ce2a31

**Comment by brianchandotcom** [comment]
@ruben-pulido see b094ce2

**Pull request closed without merging**
