### PR TITLE
master-qa-19408

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-19408

### CODE REVIEW

**Comment by kenjiheigel** [comment]
@brianchandotcom, this will fix the failing Poshi test: WorkflowadminMyworkflowtasks#ResubmitTaskByDetails that began with https://github.com/brianchandotcom/liferay-portal/pull/32082

**Comment by brianchandotcom** [comment]
Woops. My bad. Thanks for fixing it @kenjiheigel

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7993fc72da...ca0dd660b7

**Comment by kenjiheigel** [comment]
Thanks @brianchandotcom 

Do you think you could look at these pulls of mine you closed, as they failed from this test? 
https://github.com/brianchandotcom/liferay-portal/pull/32104
https://github.com/brianchandotcom/liferay-portal/pull/32107

Or I can send another pull if you like, but would rather not flood the PR tester resources.

**Pull request closed without merging**
