### PR TITLE
Lps 59828

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @hhuijser

### CODE REVIEW

**Comment by hhuijser** [comment]
@shuyangzhou 
Very nice, thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/baa5aabbf1...6ed823aa1d

**Comment by brianchandotcom** [comment]
@shuyangzhou @hhuijser can we make it always follow the CalendarWebUpgrade format?

```
@Component(
	immediate = true,
	service = {CalendarWebUpgrade.class, UpgradeStepRegistrator.class}
)
````

Seems more dummy proof to always declare both no? @shuyangzhou if so, can you tell @hhuijser to do it? Thx.

**Comment by shuyangzhou** [comment]
Quite the opposite, I think we should get rid of the CalendarWebUpgrade case. I did not have the time to look into it. I am sure there are ways to make it go away. It does not make sense that everyone else does not need it, only it does.

I am currently trying my best to clear out my task queue so that I can move on to performance optimization next week. @hhuijser can you look into it? I dont really know the new upgrade framework for modules, but it bet there is something there can help. If you got stuck I can check it sometime later, but it will be after next week. I have to push my team on the optimization next week.

**Comment by brianchandotcom** [comment]
All you Hugo :)

--
Brian Chan
Chief Software Architect
Liferay, Inc.
Enterprise. Open Source. For Life.
(626) 806-1190

**Comment by hhuijser** [comment]
@shuyangzhou 

Looks like CalendarPortlet.java was left out when for LPS-59412. Will work on that

**Comment by hhuijser** [comment]
See https://github.com/mdelapenya/liferay-portal/pull/489

**Comment by shuyangzhou** [comment]
Thanks @hhuijser !

**Pull request closed without merging**
