### PR TITLE
LPS-65414 SF

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by evannagayama** [comment]
portal instance issue not related to pr

**Comment by evannagayama** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2d60ce782f...9de7b413a1

**Comment by brianchandotcom** [comment]
@juliocamarero @BryanEngler baseline was broken, see my fix in 36bc3191cd82d7c27845d79f5189ad1dec14804f

**Pull request closed without merging**
