### PR TITLE
LPS-108953 Remove serialize settings form method from init.jsp

### PR DESCRIPTION
**Pull request by natocesarrego**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/93b8d8e1b5...aaac0fe2d7

**Comment by brianchandotcom** [comment]
@natocesarrego @carolmariaabb Oli 4c7474a si nao tem razao, de me um novo pull request.

**Comment by carolmariaabb** [comment]
> @natocesarrego @carolmariaabb Oli [4c7474a](https://github.com/brianchandotcom/liferay-portal/commit/4c7474ad3e9b9d3bc536f44c8514ba7bf2a44b3c) se nao tem razao, de me um novo pull request.

@brianchandotcom [98709c8](https://github.com/natocesarrego/liferay-portal/commit/98709c8129c222943e914ef735c1ce2473a90029) is necessary because of [LPS-107349](https://issues.liferay.com/browse/LPS-107349). For some reason [4c7474a](https://github.com/brianchandotcom/liferay-portal/commit/4c7474ad3e9b9d3bc536f44c8514ba7bf2a44b3c) is causing [LPS-107349](https://issues.liferay.com/browse/LPS-107349). Thanks.

**Comment by natocesarrego** [comment]
@carolmariaabb, can you please send a new pull request reverting Brian's changes? On the description of the new pull, please add the explanation shared by you here.

Thanks.

**Comment by natocesarrego** [comment]
@carolmariaabb, you can use the LPS-108953 to create this new pull. 😉

**Pull request closed without merging**
