### PR TITLE
LPS-141119 portal-search-web: Set IP address to search context for SXP

### PR DESCRIPTION
**Pull request by peerkar**
This satisfies the need for now, but Blueprint options widget has to duplicate the logic. Maybe some others in the future, too.

In long term I'd thus like to consider a solution like https://liferay.slack.com/archives/C02E73PDR70/p1639433966277000?thread_ts=1639051538.269500&cid=C02E73PDR70:

-  Extend PortletSharedSearchRequestImpl to support multiple SharedSearchContributors per portlet
- Implement a single SXPSharedSearchRequestImpl wired to any number of widgets needed,  to contribute IP address now and possible any other SXP required attributes in the future

This will however require reorganizing and exposing OOTB search widget preferences classes and portlet name constants to sxp-web, so it's maybe better to postpone for now. @lipusz , @arboliveira if you are ok with this, maybe we could ticketize this for the future?

### CODE REVIEW

**Comment by lipusz** [comment]
Hi @peerkar 

Can you please create a Task ticket for this under the Backlog Epic https://issues.liferay.com/browse/LPS-118988? We can groom and split-it into multiple items later. I'd ask you to file it by yourself as I'm not completely sure what I should capture as a summary/description for this. :-) 

Thanks!

**Comment by lipusz** [comment]
Maybe this could be merged and submitted alongside with https://github.com/peerkar/liferay-portal/pull/7. First I got confused by the ticket number as it is for the options widget, but then I remembered you wrote it earlier that it'd need a change for the IP address stuff.

**Comment by lipusz** [comment]
Ok, I'm still confused: this PR is for the LLSO widget, but it's under the Blueprints Options widget story. @peerkar Is that intentional?

**Comment by lipusz** [comment]
I believe it should be under [LPS-143522](https://issues.liferay.com/browse/LPS-143522).

**Comment by peerkar** [comment]
Yes, my mistake

**Comment by peerkar** [comment]
@lipusz waiting for Andre's comments before creating new tickets.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5886eae9ea...cab94ac9a7

**Comment by brianchandotcom** [comment]
@peerkar see my rename in cab94ac9a7e522f97e7354ec86827b909110eed3

**Pull request closed without merging**
