### PR TITLE
LPS-161704 Add GET system relationship endpoint to API Explorer 

### PR DESCRIPTION
**Pull request by 4lejandrito**
Hi @brianchandotcom,

This PR adds the open api spec for the dynamic relationship endpoints. See an example for the properties (houses) of a user:

Screenshot 2022-09-07 at 15 54 26

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
I've added the schema for the custom object.
Screenshot 2022-09-07 at 15 54 26

**Comment by brianchandotcom** [comment]
@4lejandrito conflict with https://github.com/brianchandotcom/liferay-portal/pull/122765

@LuismiBarcos please resend. Thx.

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122770.

**Pull request closed without merging**
