### PR TITLE
master-vw-200

### PR DESCRIPTION
**Pull request by vicnate5**
@marcellustavares @rafaprax added poshi fixes for https://github.com/vicnate5/liferay-portal/pull/198

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/572ed8f9a2...31362d5813

**Comment by brianchandotcom** [comment]
@vicnate5 can you check out AddDocument? I went ahead and merged this in.

cc @brianchiu

**Comment by vicnate5** [comment]
@brianchiu failure is due to "element not found" as I reported here: https://issues.liferay.com/browse/LRQA-21925

**Comment by brianchiu** [comment]
CC @sharonchoi

**Comment by austinchiang** [comment]
This issue will be fixed here: https://issues.liferay.com/browse/LRQA-21924

**Pull request closed without merging**
