### PR TITLE
Lps 74513

### PR DESCRIPTION
**Pull request by shuyangzhou**
QA alert, this is a risky change, need manual tests for LPS-70534 and LPS-61210 on both Linux and Windows.
@alee8888 @jpince

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@hhuijser @petershin need help with SF error, happening on every pull.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4100dc9b5c...e01f81a82e

**Comment by brianchandotcom** [comment]
@shuyangzhou I"m not backporting this since you said it was risky. Please send this to support to backport via a Gauntlet? Thx.

**Comment by shuyangzhou** [comment]
@brianchandotcom this could only possibly break something on windows with some weird properties settings. Gauntlet won't catch anything from this. QA's manual testing is the only protection we have.
@tomwang2011 please add this to backport queue, once QA gives us green light, we proceed with the backport.

**Comment by shuyangzhou** [comment]
@alee8888 @jpince any updates? We are waiting on QA's confirm before backporting it.

**Comment by jpince** [comment]
@shuyangzhou sorry this got forgotten last week, Albert's team will test this.

**Pull request closed without merging**
