### PR TITLE
master-vw-569

### PR DESCRIPTION
**Pull request by vicnate5**
Resend of https://github.com/brianchandotcom/liferay-portal/pull/44146

@diogo-lins @brunobasto

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest - Failed due to broken distribution node.

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
