### PR TITLE
LPS-83801 SF

### PR DESCRIPTION
**Pull request by csierra**
/cc @topolik

### CODE REVIEW

**Comment by topolik** [comment]
@csierra Why SF didn't fail for https://github.com/brianchandotcom/liferay-portal/pull/62230/commits/7a0070d635f8faa5113ced278037ee0768cf1e15 ?

**Comment by csierra** [comment]
> Why SF didn't fail for 7a0070d ?

because it actually did it...

**Comment by brianchandotcom** [comment]
@csierra @topolik can you guys send this to @shuyangzhou I'm afraid it'll affect performance. Thx.

**Comment by brianchandotcom** [comment]
@csierra @topolik nvm, I sent it to @shuyangzhou here https://github.com/shuyangzhou/liferay-portal/pull/6644

**Pull request closed without merging**
