### PR TITLE
LPS-105609 Make App Builder use Data Engine V2

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d575a945fa...7fac4c77ba

**Comment by brianchandotcom** [comment]
@jeyvison @leoadb see 7fac4c77baa75c8d429ffd7c35211025296fc4ed

**Pull request closed without merging**
