### PR TITLE
LPS-104530 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-104530
https://issues.liferay.com/browse/LRQA-53587

### CODE REVIEW

**Comment by adolfopa** [comment]
Hey @brianchandotcom 

AFAIK none of these components need to be immediate. Removing this should have no side effects but it may improve startup times very marginally.

Thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8628e9f434...6d2145ca6c

**Comment by brianchandotcom** [comment]
@preston-crary fyi 743455aa37f43d0b6fbdf68581b7b4f4f84b03a5 @shuyangzhou

**Comment by shuyangzhou** [comment]
Can not say for all the components got changed, since I did not check them all, but at least most of them are having active service tracker collecting them. So having immediate or not, is not going to make any difference. It should not hurt anything, but won't help anything either.

**Pull request closed without merging**
