### PR TITLE
LPS-69675

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:reopen

**Comment by ChrisKian** [comment]
ci:retest

**Comment by jpince** [comment]
Hey guys, ResourceActionsException is no longer used, so I think it needs to be removed per SF. https://github.com/brianchandotcom/liferay-portal/pull/47793/files#diff-e072d38e571c98809431d2a623ee6250R21

@hhuijser is there a way that the exceptions within SourceMismatchException can be more specific? I feel like there are a number of different errors (line breaks, unused import, etc.) that fall under this general exception.

**Comment by jpince** [comment]
ci:close

**Comment by SamZiemer** [comment]
resent here: https://github.com/brianchandotcom/liferay-portal/pull/47934

**Pull request closed without merging**
