### PR TITLE
LPS-72754 Prefix and Suffix aren't stored nor displayed when guest creates account

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-72754](https://issues.liferay.com/browse/LPS-72754).<br><br>Hey Brian, since we are abstracting the prefix/suffixId logic in 0ce7004, we should do the same in users-admin-web (this is where the logic was taken from in the first place).

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Thx @drewbrokke !

**Comment by brianchandotcom** [comment]
@drewbrokke can you make

https://github.com/brianchandotcom/liferay-portal/commit/0ce70048bd27fafb8153960b35f7b396922bb228

private too instead of protected? Please send me a pull for that. Thx.

**Comment by drewbrokke** [comment]
Yup.  https://github.com/brianchandotcom/liferay-portal/pull/49415

**Pull request closed without merging**
