### PR TITLE
LPS-67515 Fix issue when exporting/importing blogs via LAR

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
@marcos-cv this fixes the impediment for adding blog entries in a theme lar.

**Comment by sergiogonzalez** [comment]
cc/ @matethurzo I'd appreciate if you can review my changes, although I think that they are pretty straightforward since it's almost the same logic as in Wiki.

**Comment by sergiogonzalez** [comment]
cc/ @adolfopa @robertoDiaz

**Comment by sergiogonzalez** [comment]
Backport requested here https://github.com/ZoltanTakacs/liferay-portal-ee/pull/1684

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a19cccbb6c...d1892e72d3

**Comment by matethurzo** [comment]
@sergiogonzalez even though it's been merged, I've checked it and it looks good, thanks!

**Pull request closed without merging**
