### PR TITLE
LPS-101084 Apply view count service to AssetEntry

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/177f9ba78d...402ef95218

**Comment by brianchandotcom** [comment]
@stsquared99 can you send a follow up pull and sort:

```
	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			ViewCountManager.class, ViewCountEntryLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}
```

Or does order matter?

@hhuijser can you standardize our thread names? It's all over the place. Type:

git grep -A 5 "new Thread("


From

```
			Thread thread = new Thread(
				futureTask, "Inner view count incrementer");
```

We name our threads inconsistently. Please enforce a pattern. Thx!

**Comment by Preston-Crary** [comment]
@brianchandotcom order doesn't matter, it's safe to sort them.

**Comment by stsquared99** [comment]
@brianchandotcom sent here: https://github.com/brianchandotcom/liferay-portal/pull/80847

**Pull request closed without merging**
