### PR TITLE
LPS-169672

### PR DESCRIPTION
**Pull request by dsanz**
Hi @brianchandotcom I'm resending this from https://github.com/dsanz/liferay-portal/pull/78 with the new rephrased sentences, checked with PM and Design.

I've also rebased from latest master where we recently merged Bryce's changes about the SVG extensions, so the "regen" commit and some other minor conflicts were solved.

Previous PR: https://github.com/brianchandotcom/liferay-portal/pull/127584

### CODE REVIEW

**Comment by dsanz** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@edalgrin @dsanz we can't have URLs in the Language keys like this.

```
<a href="https://learn.liferay.com/dxp/latest/en/building-applications/remote-apps/understanding-remote-app-types.html#using-the-custom-element-type" target="_blank">
```

The translators can mess this up. We have to pass it in. And ideally, we need to use the Liferay Learn taglib or Liferay Learn Util files.

Trace modules/apps/learn/learn-api/src/main/java/com/liferay/learn/LearnMessageUtil.java

Also, use lower case for things like "custom element" instead of "Custom Element" when in a sentence. 

I use a car to go to the supermarket.

Not:

I use a Car to go to the Supermarket.

**Comment by dsanz** [comment]
Let me take a look at that Brian

**Comment by edalgrin** [comment]
> @edalgrin @dsanz we can't have URLs in the Language keys like this.
> 
> ```
> <a href="https://learn.liferay.com/dxp/latest/en/building-applications/remote-apps/understanding-remote-app-types.html#using-the-custom-element-type" target="_blank">
> ```
> 
> The translators can mess this up. We have to pass it in. And ideally, we need to use the Liferay Learn taglib or Liferay Learn Util files.
> 
> Trace modules/apps/learn/learn-api/src/main/java/com/liferay/learn/LearnMessageUtil.java
> 
> Also, use lower case for things like "custom element" instead of "Custom Element" when in a sentence.
> 
> I use a car to go to the supermarket.
> 
> Not:
> 
> I use a Car to go to the Supermarket.

We might have sent you the wrong commit, we changed that at some point, taking a look!

**Comment by dsanz** [comment]
Probably I skipped this when rebasing and merging conflicts.

Anyway, please see https://github.com/brianchandotcom/liferay-portal/pull/127864 with the new changes

**Pull request closed without merging**
