### PR TITLE
LPS-76628 & LPS-76686 Upgrade typeSettings properties with portletIds

### PR DESCRIPTION
**Pull request by achaparro**
cc/ @marianoalvarosaiz @ealonso

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test

**Comment by achaparro** [comment]
ci:reopen

**Comment by achaparro** [comment]
It seems that other pulls fail for the same reason:
https://github.com/brianchandotcom/liferay-portal/pull/53913

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@achaparro see ba0fa5b0d7595195ee3408244ccddf08e7e30bb3 thx

**Pull request closed without merging**
