### PR TITLE
LPS-139107 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-139107

This is only for master.

@vicnate5

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. No need to run ci:test:relevant. Additionally, ci:test:sf passed. Poshi validation passed and Case passed on local.
See https://github.com/liferay-echo/liferay-portal/pull/5840
✔️ ci:test:sf - 1 out of 1 jobs passed in 2 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e7c23a1742...103980493c

**Comment by brianchandotcom** [comment]
@Tim-Cao nice!

**Pull request closed without merging**
