### PR TITLE
LPD-19861 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://issues.liferay.com/browse/LPD-19861

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
The formatting for the "purpose" text is very strange.

```
Previously stored the current workspace to determine the correct Zendesk help widget tier; no longer used.
```

Send me everything but that text so we can make progress in this PR.

Thx

**Comment by brianchandotcom** [comment]
@marcosapmf see my comments above.

**Comment by marcosapmf** [comment]
resent to https://github.com/brianchandotcom/liferay-portal/pull/149033

**Pull request closed without merging**
