### PR TITLE
Lps 96978 2

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8542282dae...77d988e9a7

**Comment by brianchandotcom** [comment]
@leoadb @jeyvison @brunofarache fyi on DDM change

**Comment by jpince** [comment]
@mtambara can you please look into this test failure?
```
     [exec] > Task :apps:dynamic-data-mapping:dynamic-data-mapping-validator:compileTestJava FAILED
     [exec] 
...
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/dynamic-data-mapping/dynamic-data-mapping-validator/src/test/java/com/liferay/dynamic/data/mapping/validator/internal/DDMFormValuesValidatorTest.java:772: error: <anonymous com.liferay.dynamic.data.mapping.validator.internal.DDMFormValuesValidatorTest$1> is not abstract and does not override abstract method getDDMExpressionFunctionFactories(Set<String>) in DDMExpressionFunctionTracker
     [exec] 			new DDMExpressionFunctionTracker() {
     [exec] 		
```

cc/ @alexcandidos

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/74889

**Pull request closed without merging**
