### PR TITLE
master-bc-3505

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LRQA-13902

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/49ea4b0e9a...85740db2c5

**Comment by brianchandotcom** [comment]
Guys, we can't ignore this. This is a bug.... please talk to Eudaldo and Julio about this.

**Comment by brianchandotcom** [comment]
@brianchiu @brianwulbern please resend. This is a real bug.

**Comment by brianchiu** [comment]
@brianchandotcom 

Got it. Looks like Eudaldo has sent a pull for it.

https://github.com/brianchandotcom/liferay-portal/pull/24499

**Pull request closed without merging**
