### PR TITLE
COMMERCE-11517

### PR DESCRIPTION
**Pull request by brianikim**
Resent from: https://github.com/brianchandotcom/liferay-portal/pull/137428

@brianchandotcom 

`    "/account-groups/by-external-reference-code/{accountExternalReferenceCode}/accounts/by-external-reference-code/{externalReferenceCode}":`

### CODE REVIEW

**Comment by brianikim** [comment]
ci:reopen

**Comment by brianikim** [comment]
@brianchandotcom , thank you for the feedbacks on the previous PRs. Let me know if anything else is needed in this before it can be merged.

**Comment by brianchandotcom** [comment]
Ok, let's do this

1.) Modify rest-config.yaml and add 

forcePredictableOperationId: true

2.) Modify rest-openapi.yaml and change

/accounts/by-externalReferenceCode/

to

/accounts/by-external-reference-code/

3.) Regen, this will cause a lot of Java ResourceImpl and ResourceTest to break. The good news is that you just have to rename the methods and they should be easy to fix.

Please do that and resend. Thx!

**Comment by brianchandotcom** [comment]
@brianikim actually, it may be easier to split this PR up into 2 PRs.

The first PR should to just add forcePredictableOperationId, and then regen / rename (under a different PR)

And then send this one PR afterward.

**Pull request closed without merging**
