### PR TITLE
LPS-88137 Fragment Collections cannot be imported when there's no collection

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso, @brianchiu

**Comment by jkappler** [comment]
@brianchiu, no unique failures in the PR from what I see

**Comment by brianchiu** [comment]
@jkappler Yup. No unique failures. And more importantly, the content pages tests (which this pull is supposed to fix) passed!

https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=442021754

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f070eb618c...d000016776

**Pull request closed without merging**
