### PR TITLE
LPS-149278 zip slip vulnerability in uncompress util

### PR DESCRIPTION
**Pull request by wcao20170619**
follow-up [#115287](https://github.com/brianchandotcom/liferay-portal/pull/115287) 

https://issues.liferay.com/browse/LPS-149278

### CODE REVIEW

**Comment by wcao20170619** [comment]
ci:reopen

**Comment by BryanEngler** [comment]
@wcao20170619

**Comment by BryanEngler** [comment]
@wcao20170619 
i think brian meant rename like this?

testTar.gz -> test.gz
test.zip -> test.zip (no change)
testZipSlip.zip -> test_slip.zip

**Comment by wcao20170619** [comment]
I didn't look at them closely. My bad! thank you @BryanEngler

**Pull request closed without merging**
