### PR TITLE
LPS-104999 Editing a system role can be confusing since the difference between a key and a title is not clearly explained.

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-104999](https://issues.liferay.com/browse/LPS-104999).
This is an update for [LPS-105001](https://issues.liferay.com/browse/LPS-105001).

One additional update for [LPS-99914](https://issues.liferay.com/browse/LPS-99914) included as well.

/cc @pei-jung @alee8888 @ChrisKian @dejuknow

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cecf131df4...a4ed032dce

**Comment by brianchandotcom** [comment]
@drewbrokke LPS-99914 doesn't point anywhere? It throws an error in JIRA.

Also, see RolesAdminPortletDataHandlerTest.checkManifestSummaryReferrerClassNames

I merged but have doubts...

**Comment by drewbrokke** [comment]
@brianchandotcom LPS-99914 was deleted but I don't think it was supposed to happen. It's a ticket I worked on previously.

**Pull request closed without merging**
