### PR TITLE
LPS-81837 7.1 Upgrades Organization - Avatar image not saved after upgrade on MySQL5.7, SQLServer2016, and Oracle12.2

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-81837](https://issues.liferay.com/browse/LPS-81837).<br><br>/cc @pei-jung @stsquared99 @alee8888 @ChrisKian

From @ChrisKian:

https://issues.liferay.com/browse/LPS-81837

The difference between how we store org logos is between 62x and 7010, in which we add the "logoId" column to the Organization_ table.  So, 62x and lower, we are actually storing the logoId in the LayoutSet table, under both the public and private pages (it's a different logoId for each, but it points to the same image).  And in 7010 and up, we store it in the Organization_ table under the "logoId" column.

I chose to only include this fix as a 7.0 upgrade process because once the DB has been upgraded to 7000 and up, there is no way to know for sure if the user intended to set a logo for their org or for the layoutSet of their org.  This is because post 7000, the logoId field in the layoutSet table (which was previously used for the org's logo), is now used for the public/private layoutSet's logo.  In the off chance a user wants their layoutSets to have logos but not their org, we would mess that up.

The fix itself is pretty straight-forward.  We grab the logoId and groupId from the layoutSet table whenever the logoId is present and we are dealing with a public layoutSet (to avoid duplication).  Next, we match that groupId to the classPK (or organizationId) from the Group_ table, and lastly we take the classPK match it to the Organization_ table, and insert the logoId.  After that, the logo is successfully found.

Please let me know if you have any questions.

### CODE REVIEW

**Comment by drewbrokke** [comment]
@ChrisKian looks like we're still running into a semver issue here.  Can you take a look?

**Comment by ChrisKian** [comment]
Looks like it's using an older version to do the api comparison.  You can see the [latest version is now 2.0.0](https://github.com/liferay/liferay-portal/commit/772d5acf8795af71798439192623eb6735234dfa), not 1.13.0 anymore.
I'll reopen and try retesting; maybe CI will use an updated portal-impl.jar file.

**Comment by ChrisKian** [comment]
ci:reopen

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@brianchandotcom is that semver failure not going to be an issue in upstream?

**Comment by drewbrokke** [comment]
@jpince

**Comment by jpince** [comment]
@drewbrokke thanks, was just starting to look for the cause of this

@ChrisKian I recommend retesting after force pushing changes to a branch.

**Comment by vicnate5** [comment]
@drewbrokke @ChrisKian Causes https://issues.liferay.com/browse/LPS-88240

When touching upgrades, it would be a good practice to run `ci:test:upgrade` to run additional upgrade tests on the changes. The base `ci:test` only checks mysql upgrades.

**Pull request closed without merging**
