### PR TITLE
LPS-55754 Include lar-test again

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by epgarcia** [comment]
We've fixed and included the lar tests again. I've extracted part of the Mocks with the same pattern as for Journal (i.e. Using the real BookmarksEntry classes instead of Mocks as dependency of the lar-test with bookmarks. For other Mocks it's more complicated and I'll need the help of the E/I team. In the meantime I solved the dependencies with Mockito to have then working.

@brianchandotcom 
@shuyangzhou

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@shuyangzhou fyi for lar-test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/15fd03b946...a9e42bd57d

**Pull request closed without merging**
