### PR TITLE
LPS-106959 buildLang

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
//cc @ealonso

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d166f2374d...b7f1561d00

**Comment by brianchandotcom** [comment]
@ruben-pulido see 448a5dd4686d2a6281653673bc7d3f85a6e022bf

**Comment by ruben-pulido** [comment]
> @ruben-pulido see [448a5dd](https://github.com/brianchandotcom/liferay-portal/commit/448a5dd4686d2a6281653673bc7d3f85a6e022bf)

Hi @brianchandotcom
The "preview-and-convert-to-content-page=Preview and convert to Content Page" language key is being used as a label for an action item (similarly to "convert-to-content-page=Convert to Content Page".
Shouldn't it not end in full stop and use Content Page instead of content page?

**Pull request closed without merging**
