### PR TITLE
LRDOCS-3221 Breaking Change Reorg

### PR DESCRIPTION
**Pull request by codyhoag**
These are the changes that were discussed by @jhinkey and I.

https://issues.liferay.com/browse/LRDOCS-3221

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@codyhoag we can't get rid of the 7.0 one. If you do a git log on the 7.0. read me, (Shopping for example) had some breaking changes and that is as separate MP app that will get backported to 7.0.x and released in the 7.0 timeline. So in some sense, 7.0 is fluid.

**Comment by brianchandotcom** [comment]
@codyhoag can you compare the 7.0.x 7.0 breaking changes with the master 7.0 breaking changes? They should be in sync. Thx.

**Comment by jhinkey** [comment]
@brianchandotcom - For 7.0 breaking changes, let's only put them in breaking changes in the 7.0.x branch. Let's focus master's breaking changes on 7.1. Cody will comment on the Shopping breaking change.

**Comment by codyhoag** [comment]
I contacted @drewbrokke (the original author) about the Shopping breaking change, and he told me the Shopping change should reside in the 7.1 doc. I was going to move that commit to the 7.1 doc, and once that was done, the `master` and `7.0.x` Breaking Changes for 7.0 will be in sync.

**Pull request closed without merging**
