### PR TITLE
LPS-75250 Update paths for getting the files

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
cc: @jkappler

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7e45580013...120769fc7f

**Comment by brianchandotcom** [comment]
@ealonso please see my changes in upstream. Thx.

**Pull request closed without merging**
