### PR TITLE
LPS-69436 Baseline

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:reopen

**Comment by ambrinchaudhary** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@ambrinchaudhary 

provided group: "com.liferay", name: "com.liferay.frontend.taglib.soy", version: "1.0.3"

should be

provided group: "com.liferay", name: "com.liferay.frontend.taglib.soy", version: "1.0.0"

@hhuijser can you use SF to prevent micro versions like this?

I also don't see why

modules/apps/collaboration/blogs/blogs-web/build.gradle
modules/apps/collaboration/message-boards/message-boards-web/build.gradle
modules/apps/web-experience/asset/asset-publisher-web/build.gradle

needed to be modified since the additonal compile time dependency is not used?

Please resend. Thx.

**Comment by ambrinchaudhary** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/47930

**Pull request closed without merging**
