### PR TITLE
Lps 73594

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by drewbrokke** [comment]
cc @yuhai

**Comment by drewbrokke** [comment]
@shuyangzhou these failures might be related
They're all complaining about the user avatar not being visible.

**Comment by shuyangzhou** [comment]
@drewbrokke ok, then I am closing this pull, can look into it to see what is going on?

**Comment by drewbrokke** [comment]
Yup, I can do that

**Comment by drewbrokke** [comment]
@alee8888 @xbrianlee are these failures isolated to this case, or are they showing up elsewhere?

**Comment by xbrianlee** [comment]
@drewbrokke Those test failures were caused by https://github.com/brianchandotcom/liferay-portal/pull/50502. Those commits have since been reverted, so those test failures should not occur anymore.

**Comment by drewbrokke** [comment]
Thanks @xbrianlee 👍 

@shuyangzhou would you mind to rebase and re-send?  Thanks!

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c6e76c64a4...8809146b93

**Pull request closed without merging**
