### PR TITLE
LPS-102549 portal-search-admin-web: Update FieldMappings component to react

### PR DESCRIPTION
**Pull request by thektan**
https://issues.liferay.com/browse/LPS-102549

Resent from https://github.com/brianchandotcom/liferay-portal/pull/80548#issue-336936749 to fix SF.

### CODE REVIEW

**Comment by thektan** [comment]
Test failure in https://github.com/brianchandotcom/liferay-portal/pull/80558#issuecomment-550045962 doesn't look related.

@joshchong

**Comment by brianchandotcom** [comment]
@shuyangzhou can you ask @Mtambara to review

```
     [exec] * What went wrong:
     [exec] Execution failed for task ':apps:portal:portal-jmx-test:startTestableTomcat'.
     [exec] > Timeout while waiting for the application server
     [exec] 
     [exec] * Try:
 
```

This happens a lot.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6116fbcf92...4327c43469

**Comment by shuyangzhou** [comment]
This has been fixed by https://github.com/brianchandotcom/liferay-portal/pull/80549

**Pull request closed without merging**
