### PR TITLE
LPS-92341 Exceptions library specific must not cross boundaries of engine neutral Search modules

### PR DESCRIPTION
**Pull request by arboliveira**
@brianchandotcom This is a critical fix to solve pull requests upstream often getting stuck and timing out after 3 hours. cc/ @xbrianlee @joshchong

@rafaprax @inacionery After this fix you'll see a large number of tests breaking with a legitimate problem that was masked by the aforementioned issue. In tests that create a company on the fly and then delete it, apparently the index or related documents are gone before `KaleoTaskModelListener` has a chance to delete them. Possibly the search engine exception can be safely caught and discarded in this case.

```
     [exec]     java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.portal.workflow.metrics.internal.model.listener.KaleoTaskModelListener, message=java.lang.RuntimeException: org.elasticsearch.index.engine.DocumentMissingException: [workflow-metrics-tasks/RoboPANNRL22NoQ4W3B-Ww][[workflow-metrics-tasks][0]] DocumentMissingException[[WorkflowMetricsTaskType][WorkflowMetricsTask_PORTLET_c73fec27d813a665bdcbbbb847c65a3dc9407e090328f7a4e3a6913e0142d891]: document missing]
     [exec]         at com.liferay.portal.workflow.metrics.internal.model.listener.KaleoTaskModelListener.onAfterRemove(KaleoTaskModelListener.java:54)
     [exec]         at com.liferay.portal.workflow.kaleo.service.persistence.impl.KaleoTaskPersistenceImpl.removeByCompanyId(KaleoTaskPersistenceImpl.java:532)
     [exec]         at com.liferay.portal.workflow.kaleo.service.impl.KaleoTaskLocalServiceImpl.deleteCompanyKaleoTasks(KaleoTaskLocalServiceImpl.java:89)
     [exec]         at com.liferay.portal.workflow.kaleo.runtime.internal.manager.DefaultPortalKaleoManager.deleteKaleoData(DefaultPortalKaleoManager.java:61)
     [exec]         at com.liferay.portal.workflow.kaleo.internal.model.listener.CompanyModelListener.onAfterRemove(CompanyModelListener.java:37)
     [exec]         at com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl.remove(BasePersistenceImpl.java:473)
     [exec]         at com.liferay.portal.service.impl.CompanyLocalServiceImpl.doDeleteCompany(CompanyLocalServiceImpl.java:1338)
```

**❌ ci:test:search - 14 out of 17 jobs passed in 1 hour 19 minutes 24 seconds 985 ms**
https://github.com/arboliveira/liferay-portal/pull/691#issuecomment-474733570

Branch `master` is contaminated.

----

```
     [exec] Execution failed for task ':private:apps:portal-workflow:portal-workflow-metrics-web:npmRunTest'.
     [exec] > java.io.IOException: Process '[/opt/dev/projects/github/liferay-portal/build/node/bin/node, /opt/dev/projects/github/liferay-portal/build/node/lib/node_modules/npm/bin/npm-cli.js, --loglevel, warn, --production, false, --progress, true, --registry, http://mirrors.lax.liferay.com:4873, run-script, test]' finished with non-zero exit value 1
```

Reported fixed by https://github.com/brianchandotcom/liferay-portal-ee/pull/23579

----

```
junit.framework.AssertionFailedError: 
Unable to register portal instance {mvccVersion=1, companyId=20100, accountId=20102, webId=liferay.com, key=JixuHt+TvWD3pkH4Al74qQ==, mx=liferay.com, homeURL=, logoId=0, system=false, maxUsers=0, active=true}
com.liferay.portal.kernel.exception.NoSuchResourceActionException: There are no actions associated with the resource com.liferay.dynamic.data.mapping.model.DDMStructure-com.liferay.portal.workflow.kaleo.forms.model.KaleoProcess
```

Startup logs seem to suggest this is unrelated to Search.  @rafaprax @inacionery

---

_[Bug] LPS-92341 Exceptions library specific must not cross boundaries of engine neutral Search modules_
https://issues.liferay.com/browse/LPS-92341

### CODE REVIEW

**Comment by inacionery** [comment]
Hey @arboliveira,

This first issue was corrected by https://github.com/brianchandotcom/liferay-portal-ee/pull/23583

Thx!

**Comment by arboliveira** [comment]
ci:reopen

**Comment by arboliveira** [comment]
@brianchandotcom Unrelated to this pull: 

```
     [exec] Execution failed for task ':apps:change-tracking:change-tracking-change-lists-web:npmRunBuild'.
     [exec] > Soy compile error
```

**Comment by brianchandotcom** [comment]
@arboliveira see 146950272f5e15bd6b816ff0abe66dc6aa53e96f d44d95c695d73984685d5367c60b188ff281068b and ced85b60231bee87b8033e61f47745a41808f48c

The test and the usage do not match up, please fix.

**Comment by arboliveira** [comment]
@brianchandotcom Exception instantiation logic in `ElasticsearchSearchEngineAdapterImpl` vs `SearchEngineAdapterTest` must be slightly different, for a good reason. The former is in a module where library exceptions are present in the class loader, so it's okay to invoke `runtimeException.toString()`. The latter is in the test framework's module, where the library isn't present, so `throwable.toString()` crashes with a `ClassNotFoundException` -- the safe alternative here is `throwable.getMessage()`. Deliberate intention is to have the test framework fail the test cleanly when a library exception escapes, while still reporting its original stacktrace so we can locate the throw point within the OSGi module. But for this we need to replace the library exception with a test framework safe doppelgänger, otherwise test framework crashes with `ClassNotFoundException` and hangs for 3 hours. (The very symptom we're fixing in this pull.)

**Pull request closed without merging**
