### PR TITLE
LPS-54815 lib

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Service Builder... free at last, free at last!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d0a4cca724...2dcdac9934

**Comment by brianchandotcom** [comment]
@rotty3000 I also went ahead and pushed it up the SDK and changed even core to use the published module... see upstream for my changes. Thx!

**Comment by rotty3000** [comment]
Will do, I should be sending in the tests and plugins by tomorrow.

On Wed, Apr 15, 2015 at 5:46 PM, Brian Chan <notifications@github.com>
wrote:

> @rotty3000 <https://github.com/rotty3000> I also went ahead and pushed it
> up the SDK and changed even core to use the published module... see
> upstream for my changes. Thx!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/25656#issuecomment-93578186>
> .
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Pull request closed without merging**
