### PR TITLE
LPD-15603 Get portalURL variable from http request

### PR DESCRIPTION
**Pull request by devpedrotavares**
Follow up on: https://github.com/brianchandotcom/liferay-portal/pull/146937

### CODE REVIEW

**Comment by devpedrotavares** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Hey @devpedrotavares 

Let's do this. See PortalSessionThreadLocal. Make one called PortalRequestThreadLocal.java

```
		PortalSessionThreadLocal.setHttpSession(
			httpServletRequest.getSession());
```

and

```
PortalSessionThreadLocal.setHttpServletRequest(
```

Let's make this global. I have a feeling everyone will want this.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3f0c816a2a...759dc9e442

**Comment by brianchandotcom** [comment]
@devpedrotavares I ended up not using https://github.com/brianchandotcom/liferay-portal/pull/147032 and I went with your PR here. I was just afraid of modifying MainServlet. If we do need the http servlet request in more than one place in the future, then we'll consolidate it.

**Pull request closed without merging**
