### PR TITLE
LRQA-53382 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LRQA-53382
7.2.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/28135

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/94250c6ac7...1501d946b7

**Comment by brianchandotcom** [comment]
@john-co I backported this to 7.2.x

PLease send to 7.1.x or 7.0.x if relevant.

**Comment by brianchandotcom** [comment]
Woops @john-co 7.2.x didn't cherry pick, can you send me a pull to 7.2.x too? Thx.

**Comment by john-co** [comment]
7.2.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/28135

**Comment by john-co** [comment]
Hi @brianwulbern, can you backport this to 7.1.x and other affected legacy branches?

**Comment by brianwulbern** [comment]
@john-co yep, sure thing.

**Pull request closed without merging**
