### PR TITLE
LPS-189313

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@MarinhoFeliphe 

protected PortalCache<Long, ArrayList<String>> portalCache;

should be List and not ArrayList

Please resend

**Comment by MarinhoFeliphe** [comment]
Hey @brianchandotcom, thanks for your review!

We can't do this because List is not Serializable,

By the way, we already have another [this place](https://github.com/liferay/liferay-portal/blob/5f11801b7c52bd641d23053a447fec853497a775/modules/apps/portal-workflow/portal-workflow-kaleo-runtime-impl/src/main/java/com/liferay/portal/workflow/kaleo/runtime/internal/cache/KaleoTaskScriptedAssignmentCache.java#L58) in liferay-portal using ArrayList as value of PortalCache.

**Comment by MarinhoFeliphe** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
I thought only the KEY needs to be serializable?

See

```
public interface PortalCache<K extends Serializable, V> {
```

The other one is round too then.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8bd42d7ddf...f17065b475

**Pull request closed without merging**
