### PR TITLE
LPS-108966 Build lang

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
@ealonso

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/31c059f094...b0f66de72e

**Comment by brianchandotcom** [comment]
@jkappler see 36c2139

**Comment by brianchandotcom** [comment]
@jkappler see d87cd0e265ad988765042265405054ab49b2eb6f

**Pull request closed without merging**
