### PR TITLE
LPS-108148 Create groupKeys for LayoutPageTemplateCollection and LayoutPageTemplateEntry models

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
//cc @ealonso

**Comment by ruben-pulido** [comment]
//cc @jkappler

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/482e99eaec...8841bff69c

**Comment by brianchandotcom** [comment]
Very nice @ruben-pulido

**Comment by brianchandotcom** [comment]
and @jkappler !

**Pull request closed without merging**
