### PR TITLE
LPS-60908 A form can be displayed in Form portlet even if it has not been published

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@marcellustavares

**Comment by marcellustavares** [comment]
:+1:

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5a8a8e7a6e...79da486b96

**Comment by brianchandotcom** [comment]
@leoadb @marcellustavares please see my changes to DDLRecordSet

**Pull request closed without merging**
