### PR TITLE
LPS-96718 - SF

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by jpince** [comment]
@carloslancha a lot of POSHI tests are failing with this error
`java.lang.Exception: Element is not present at "//div[contains(@class,'contextual-sidebar-visible')]"`
image

It looks like the Web Content sidebar isn't visible when you first open WC Admin (not sure if this is intentional?)

@john-co @brianchiu @kyle-miho seems likely to cause many POSHI test failures.

**Comment by john-co** [comment]
ci:close

**Comment by john-co** [comment]
closing to discuss the issue with WEM team. Fails portal smoke tests as well.

**Comment by john-co** [comment]
I verified with the ci bundle manually that the user is not able to see the sidebar when creating a web content. Also the user is not able to Publish or Save a Web Content article through UI - Clicking on Publish or Save Draft does not do anything.

@carloslancha, please send a PR to me when fix is ready so I can review the tests prior to sending to BChan. Please reach out to WEM team if collaboration is needed to resolve the issue. Thank you.

cc/ @jbalsas, @brianchiu, @kyle-miho, @jpince

**Comment by john-co** [comment]
FWIW, the issue seems very similar to https://issues.liferay.com/browse/LPS-96615

**Comment by brianchiu** [comment]
It is also similar to https://issues.liferay.com/browse/LPS-96771. The properties sidebar definitely needs to be opening on its own, otherwise we won't be able to add web content through the UI.

**Comment by john-co** [comment]
Ah yes, https://issues.liferay.com/browse/LPS-96771 is the exact steps of how to reproduce it. Thanks!

**Comment by carloslancha** [comment]
Sent fixed https://github.com/john-co/liferay-portal/pull/143

**Pull request closed without merging**
