### PR TITLE
LPS-64398 Multiple selection for all Facets, in portal-search instead of portal-kernel

### PR DESCRIPTION
**Pull request by arboliveira**
Resend of https://github.com/brianchandotcom/liferay-portal/pull/59504#issuecomment-394066244, fixing the one true test failure in the `ci test relevant` set.

cc/ @xbrianlee This is one of our high profile fixes in New Search, and prerequisite for our last pending feature. (Smart Facet Selections)

cc/ @brandizzi Please check: https://github.com/brianchandotcom/liferay-portal/pull/59504#issuecomment-394066033, https://github.com/brianchandotcom/liferay-portal/pull/59460#pullrequestreview-125358649

Authors: @BryanEngler @wcao20170619 @dylan-rebelak 
Reviewer: @arboliveira

https://issues.liferay.com/browse/LPS-64398
https://issues.liferay.com/browse/LPS-76678
https://issues.liferay.com/browse/LPS-76679
https://issues.liferay.com/browse/LPS-73169

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:reopen

@brianchandotcom The `NullPointerException` at `SearchResultsPortletTest` is not related to this pull. It was introduced yesterday, by https://github.com/brianchandotcom/liferay-portal/pull/59460#pullrequestreview-125358649. @brandizzi will handle it. (https://github.com/brianchandotcom/liferay-portal/pull/59504#issuecomment-394066033)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/29c6f8dc6f...3c65738500

**Comment by brianchandotcom** [comment]
@arboliveira I only modified LPS-64398 since the other LPS tickets didn't have Git commits in this pull. I'll let you handle the other LPS tickets.

@brandizzi need a fix bro!

**Comment by brandizzi** [comment]
Fix under CI test [here](https://github.com/brianchandotcom/liferay-portal/pull/59508#issuecomment-394090289).

**Pull request closed without merging**
