### PR TITLE
LPS-91002 Rename entryId to assetId

### PR DESCRIPTION
**Pull request by marcellustavares**
cc @interaminense

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4f4b044291...c0701d1128

**Comment by brianchandotcom** [comment]
@marcellustavares it's strange that in Asah, you renamed custom to customAsset,

but here, you still have it as custom.

There's inconsistency in how you're naming things... I merged it, but you should fix it or else it's going to give us technical debt.

Contrast:

```
	BLOG("blog"), CUSTOM("customAsset"), DOCUMENT("document"), FORM("form"),
	JOURNAL("journal"), PAGE("page");
```

With blogs.js, custom.js, documents.js, and forms.js..

It doesn't look right. Please fix.

**Comment by marcellustavares** [comment]
Thanks @brianchandotcom! just sent you a follow up to https://github.com/brianchandotcom/com-liferay-osb-asah-private/pull/1189

**Pull request closed without merging**
