### PR TITLE
LPS-68415 Adds Soy TemplateRendererTag

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brunobasto** [comment]
Hey @brianchandotcom,

About the SF failing test, I have no control over the method name since its
implementing a native Java interface.

**Comment by brunobasto** [comment]
ci:reopen

**Comment by jbalsas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchandotcom** [comment]
See https://github.com/hhuijser/liferay-portal/pull/2724

@hhuijser will resend.

**Pull request closed without merging**
