### PR TITLE
LPS-55740 Upgrade Struts to 1.3.10

### PR DESCRIPTION
**Pull request by samuelkong**
/cc @yxingwu

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by samuelkong** [comment]
Brian, thanks for starting the retest. 
FYI: The test ran successfully earlier when yuxing sent it me. See https://github.com/samuelkong/liferay-portal/pull/693

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5cdb5198fb...6bab34ac6b

**Comment by brianchandotcom** [comment]
Nice job @yxingwu

**Pull request closed without merging**
