### PR TITLE
LPS-81093 Retrieving the subscriptionIds from document.getElementById

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by jonmak08** [comment]
Hey @brianchandotcom and @4lejandrito,

I will update https://github.com/brianchandotcom/liferay-portal/pull/58973/commits/52cac80f3349a4c1293e3ba28607a1cd80926f4c to use ```form.querySelector``` since ```subscriptionIds``` is within the form.

I will resend a new pull to @brianchandotcom, so this can be closed.

Please let me know if you have any questions. Thanks!

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/brianchandotcom/liferay-portal/pull/58995

**Comment by jonmak08** [comment]
ci:close

**Pull request closed without merging**
