### PR TITLE
LPS-101450 Minor changes are revertible but required

### PR DESCRIPTION
**Pull request by achaparro**
cc/ @vicnate5

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@achaparro is this safe for me to merge?

**Comment by achaparro** [comment]
Yes, @brianchandotcom, in fact it's required for the SP1. I have tested it with @vicnate5.

We can talk tomorrow if you prefer it.

Have a good night.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e01e946617...e467430d24

**Comment by brianchandotcom** [comment]
@achaparro I backported this to 7.2.x

Not sure if you should go farther back, if so, please send me a backport.

**Pull request closed without merging**
