### PR TITLE
LPS-61748 log classpath and resources in info

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
FYI @Ithildir

**Comment by rotty3000** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/20e01cf6f6...fb1c9c169a

**Comment by brianchandotcom** [comment]
@rotty3000 I think I caught a bug in 39531189eaa7bfaf28de9e59ffafd69ecb81ac86

See upstream for my changes.

@Ithildir please review my changes in upstream. Thx.

**Pull request closed without merging**
