### PR TITLE
LPS-111235

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b16d62966b...09ac300286

**Comment by brianchandotcom** [comment]
@hhuijser I had to revert this because it caused master not to sync :(

@jpince told me about it.

Republishing SF.

**Comment by brianchandotcom** [comment]
@hhuijser I also reverted 1cea938a and 92362d0a
@hhuijser can you work with @yxingwu to resend me those 2 commits and fix SF (with passing tests)

Thx!

**Pull request closed without merging**
