### PR TITLE
LPS-151265-LPS-151267 key version auto generation and upgrade process

### PR DESCRIPTION
**Pull request by wcao20170619**
https://issues.liferay.com/browse/LPS-151265
https://issues.liferay.com/browse/LPS-151267

continued from https://github.com/brianchandotcom/liferay-portal/pull/117517

### CODE REVIEW

**Comment by wcao20170619** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@wcao20170619 is the "key" essentially an ERC?

Shouldn't it be a friendly human readable key (unique per company)?

If we're constantly generating a new key on every update, what's the point?

The logic still doesn't make much sense?

**Comment by lipusz** [comment]
Hi @brianchandotcom 

We are going to add a human readable "key" for the OOTB elements on another ticket, similar to how default DDM Structures work (`structureKey`). For custom elements and blueprints, this will be a generated ID (similar to `DDMSLSI#addStructure`).

Regarding the usage of the `key` in Blueprints: the idea was that they key can remain the same across environments so if it would be a better choice to support cases like Remote Staging or when an Blueprint is imported to a new environment manually. See @peerkar's comment on the spike investigation we did in https://issues.liferay.com/browse/LPS-147776?focusedCommentId=2651500&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2651500.

Regards,
Tibor

/cc @wcao20170619

**Comment by peerkar** [comment]
The main purpose of key property is the transportability of Blueprints, Elements and configurations having references to them between environments and in remote staging environments. ID based references are hard to manage.

As an example of real world use case: one of our big customers is starting to use Blueprints, is having a 4 environment publishing pipeline and several other development environments. They are also using remote staging.

**Pull request closed without merging**
