### PR TITLE
LPS-98246 Only calculate availableTemplates when configurationValues changed

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
cc: @victorg1991

**Comment by victorg1991** [comment]
Hey @brianchandotcom @jpince
Failures are not related to this PR, you can see the exact same test failures in this PR: https://github.com/victorg1991/liferay-portal/pull/51

**Comment by brianchandotcom** [comment]
@victorg1991 can you resend:

```
package com.liferay.blogs.web.internal.info.renderer;

import com.liferay.blogs.model.BlogsEntry;
import com.liferay.info.item.renderer.InfoItemRenderer;
```

New class does not follow class it implements. SHould be *.info.item.renderer.*

THx.

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
