### PR TITLE
Lps 77485

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by jpince** [comment]
@vsingleton see Shuyang's SF fix

**Comment by vsingleton** [comment]
@shuyangzhou and @jpince ... thanks.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0bd6127077...cd687f82fc

**Comment by brianchandotcom** [comment]
@vsingleton see cd687f82fcc5c9feeee0257c9732ae4c5a82997f thx

**Pull request closed without merging**
