### PR TITLE
LPS-64093

### PR DESCRIPTION
**Pull request by juangon**
Hi @brianchandotcom. I think I've cleaned up all names and made the changes you asked.

Hopefully now it has more consistent naming.

Thanks!

/cc @rotty3000 @vsingleton

### CODE REVIEW

**Comment by juangon** [comment]
ci:retest

**Comment by juangon** [comment]
ci:retest

**Comment by juangon** [comment]
oh man I've fixed two conflicts in 3 hours...

**Comment by juangon** [comment]
ci:stop

**Comment by juangon** [comment]
ci:retest

**Comment by rotty3000** [comment]
these are completely unrelated, I saw the example same ones in another of my PRs

**Comment by juangon** [comment]
ci:retest

**Comment by juangon** [comment]
4th time I had to rebase :-( .

**Comment by juangon** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/073883ecfb...de29e0d3b8

**Comment by brianchandotcom** [comment]
@juangon please see my many changes in upstream! Thanks for all the help!

**Comment by juangon** [comment]
thanks @brianchandotcom :+1:

**Pull request closed without merging**
