### PR TITLE
LPS-71641

### PR DESCRIPTION
**Pull request by matethurzo**
re-sending

comment from the original pull

@brianchandotcom this is the first pull in a series of refactoring to composition. this serves more flexibility on a longer run, and I'll add the changes gradually.

bookmarks is used as an example, by the end of the user story the BookmarksPDH will implement the PDH interface and won't extend the BasePDH.

cc @adolfopa

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:reopen

**Comment by matethurzo** [comment]
@brianchandotcom just run the source formatter locally and there is one error but not in this code

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/25a2570e17...794e3dc506

**Comment by brianchandotcom** [comment]
Thx @matethurzo

**Pull request closed without merging**
