### PR TITLE
LPS-68916 Simplify and remove unnecessary work

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @adolfopa

**Comment by brianchandotcom** [comment]
@kiyoshilee @michaelhashimoto fyi  empty ${jstack.output}

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@adolfopa see 41a693fb8056028177c432f5f7cd851e2c6763c6

@kiyoshilee @michaelhashimoto how come compile JSP didn't catch this error?

**Pull request closed without merging**
