### PR TITLE
LPS-94028 Remove contributed collections since everything will be handled by basic component and basic section

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by jkappler** [comment]
cc:// @kyle-miho, @brianchiu

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/dc455b14e6...44d3749288

**Comment by brianchandotcom** [comment]
@jkappler 44d37492886ef51b9a9e8306a86ea5f636f9c545 can you apply to it to all Fragments? Should be easy. Thx.

**Pull request closed without merging**
