### PR TITLE
LPD-36494 add playwright test to the language client extension

### PR DESCRIPTION
**Pull request by thiago-buarqque**
Resending from https://github.com/brianchandotcom/liferay-portal/pull/155313. Making the sample have variations of languages.

--------

Coming from https://github.com/liferay-platform-experience/liferay-portal/pull/754 and https://github.com/kenjiheigel/liferay-portal/pull/1752

[Brian asked](https://github.com/brianchandotcom/liferay-portal/pull/155009#issuecomment-2405637671) to add a playwright test for the language cx and to rewrite the README file.

[As requested](https://github.com/brianchandotcom/liferay-portal/commit/cfd0f7c5721a8f2e5a99b6dedd752cd8f0e2e83a), I made the README file less wordy.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@thiago-buarqque great, you just exposed a bug.

I want this to work "without" the portal-ext.properties. Do that "busy" work for me automatically.

Detect the Language files and auto set it. Why make a dev do this unnecessary robotic step? Make a robot do it.

@drewbrokke please work with Thiago to fix this.

**Comment by ethib137** [comment]
Hey @brianchandotcom I think it is problematic to assume that because a language file with a certain locale exists that the portal admins want that language to be enabled. There are a couple reasons. First, `buildLang` generates language files for all locales by default. I doubt that devs usually delete locales they don't want to use all the time. They likely just leave it, since up until now, it wouldn't have negative effect. Second, when a site is in the process of adding or removing a locale, it's also likely the locales of the language.properties would not align with the available locales in the portal. Finally, even if the locale is not available in the portal currently, this client extension will still deploy it and add it to the database. Once an admin decides to make the locale visible in the portal the localized translations will be present. Therefore, I think the current behavior is safer and more intuitive for our users since it's not changing existing behaviors they would already be familiar with.

**Comment by brianchandotcom** [comment]
@ethib137 reopening while chewing on what you wrote. What you wrote seems to make sense.

Weighing forcing the dev to do "extra" work vs. automatically doing thihngs that ought not to be done.

**Comment by ethib137** [comment]
Thanks @brianchandotcom 

> Finally, even if the locale is not available in the portal currently, this client extension will still deploy it and add it to the database.

UPDATE: I was wrong... This part is not currently the behavior. Apparently, right now it will only import locales that are enabled in the portal. It's a small change to make sure translations are always added to the database though, so if you think this behavior would be better we can easily make that happen.

**Comment by ethib137** [comment]
@brianchandotcom is there still anything blocking this?

**Comment by brianchandotcom** [comment]
@thiago-buarqque @drewbrokke @ethib137 also,

````
../gradlew buildLang
````

failed for me

```
$ ../gradlew buildLang

FAILURE: Build failed with an exception.

* What went wrong:
Task 'buildLang' not found in project ':language'.

* Try:
> Run gradlew tasks to get a list of available tasks.
> For more on name expansion, please refer to https://docs.gradle.org/8.5/userguide/command_line_interface.html#sec:name_abbreviation in the Gradle documentation.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.5/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 765ms
```

I literally followed the README, and the readme instructions were wrong. What's the point of a readme that is wrong? It's better to have no readme than a wrong readme.

Fix it. Thx.

**Comment by thiago-buarqque** [comment]
@brianchandotcom The README isn't wrong, you ran the wrong command

It's 

```
../gradlew :buildLang
```

not 

```
../gradlew buildLang
```

**Comment by thiago-buarqque** [comment]
> This is confusing to someone who just grabs liferay-sample-workspace, sees the language folder, and then is very confused why his languages aren't showing up. They have no idea about the tests.
>
>The change to portal-ext.properties must happen in the workspace, not the test.

@brianchandotcom  That was the reason why I removed the language variations that are not default to a Liferay instance. That way we would make the test easier since we use a brand new instance, and would be highly probable that the customer would still have those languages enabled. If not, they will get a message saying.

```
"Language ID "$language_id" is not one of the available language IDs: $availableLanguageIds"
```

**Comment by thiago-buarqque** [comment]
@brianchandotcom regarding why the command is `../gradlew :buildLang` and not `../gradlew buildLang`:

The buildLang task requires a subfolder to hold the translations. Since you asked us to change the tree from

```
| root
| -- language
| ----- lang
```

to

```
| root
| -- language
```

it means the `language` folder is that subdirectory. That is, the `root` is the Gradle project that will run the `buildLang` task. That's what `:` means.

**Pull request closed without merging**
