### PR TITLE
LPS-93080 Remove component annotation

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @jorgeFerrer, @ealonso, @kyle-miho

**Comment by jkappler** [comment]
@brianchandotcom, checking the test that is failing, it looks to be layout related, so it doesn't seem to be caused by this PR

**Comment by brianchandotcom** [comment]
Just saw this after I already merged https://github.com/brianchandotcom/liferay-portal/pull/70450

**Comment by brianchandotcom** [comment]
@jorgeferrer fyi

**Pull request closed without merging**
