### PR TITLE
LPS-70092

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:stop

**Comment by Ithildir** [comment]
I think the `npm-shrinkwrap.json` has a SF problem, re-sent at https://github.com/brianchandotcom/liferay-portal/pull/46162.

@brunobasto, please use `gradlew npmShrinkwrap` to generate formatted shrinkwraps 😊

**Comment by brunobasto** [comment]
I though I had run `gradlew formatSource`.. anyway, thanks @Ithildir, I didn't know about `gradlew npmShrinkwrap`.

**Comment by Ithildir** [comment]
AFAIK SF doesn't format `.json` files. `gradlew npmShrinkwrap` not only produces a formatter `npm-shrinkwrap.json` (so it's easier to see the diffs), but also it removes a couple of incompatible packages. It's mostly for themes, but for consistency it's better to use it every time 😊

**Pull request closed without merging**
