### PR TITLE
LPS-55262 Remove Apache Felix web console from build

### PR DESCRIPTION
**Pull request by philipjones03**

### CODE REVIEW

**Comment by philipjones03** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
<p>The Pull Request Tester will be down until <strong>December 28, 2015 @ 5:00 PM PDT</strong>.</p>

<p>See this <a href="https://issues.liferay.com/browse/LRQA-18839">JIRA Ticket</a> for more information.</p>

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3ff5b25fa8...a388e3d2a3

**Pull request closed without merging**
