### PR TITLE
LPS-54985 SF

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@csierra 

Can you resend? I mentioned in my earlier pull why I rejected it because ServiceReferenceMappers should be in registry-api.

When you resend the pull, please either link this new pull to the old pull (where you may have commented), or put your reply in the new pull.

Thx.

**Comment by brianchandotcom** [comment]
@csierra 

I dug and found your comment here https://github.com/brianchandotcom/liferay-portal/pull/26261

Do we have to have the one in portal-service? Can that be in the registry-api as well? I don't see anything in that class that uses any code in portal-service? Thx.

**Comment by csierra** [comment]
hey @brianchandotcom, 

thanks for looking for the comment, I missed the link sorry :disappointed: 

The Adaptor and the Function types are types in portal-service. We can't make the registry-api depend on portal-service, that's why I have to put them there. It is not mandatory to have ServiceReferenceMappers in portal-service, but those types already exist there and can be useful. The problem is that they can never be in registry-api AFAIK.

**Comment by csierra** [comment]
please see https://github.com/brianchandotcom/liferay-portal/pull/26406

**Pull request closed without merging**
