### PR TITLE
LPS-98325 As a developer I have an API to bulk convert all or several selected widget pages of a site into Content Pages

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
//cc @ealonso

**Comment by ruben-pulido** [comment]
//cc @jkappler

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bb602cd4c5...61a94a7659

**Comment by brianchandotcom** [comment]
@ruben-pulido please see my changes in upstream. Thx.

**Pull request closed without merging**
