### PR TITLE
[TS] LPS-79480 doAsUserId param added to the external URLs when page type is link to URL

### PR DESCRIPTION
**Pull request by topolik**
Hi Brian,

https://issues.liferay.com/browse/LPS-79480

Thanks.

/cc @rolandpakai @lipusz

### CODE REVIEW

**Comment by topolik** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d540b8129f...c954db89d7

**Comment by brianchandotcom** [comment]
Can we add a test for this? Thx.

**Comment by brianchandotcom** [comment]
@topolik see PortalImplTest.java or PortalImpl*Test.java

Thx

**Comment by topolik** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/57308. Thanks.

**Pull request closed without merging**
