### PR TITLE
Lps 74281

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/05ef8d0619...faa7f7f132

**Comment by brianchandotcom** [comment]
@shuyangzhou @Preston-Crary please backport, not able to CP.

**Comment by Preston-Crary** [comment]
Backport:
https://github.com/brianchandotcom/liferay-portal-ee/pull/18459

**Pull request closed without merging**
