### PR TITLE
Alternative solution for https://github.com/brianchandotcom/liferay-portal/pull/23945

### PR DESCRIPTION
**Pull request by cgoncas**
Hey @shuyangzhou ,
- We add the "Arquillian JUnit custom Liferay runner" to the Junit Bridge extension, as it is not possible to use the JUnit bridge extension without this runner.
- As Shuyang prefers not to use the Arquillian Junit Container, we have  converted the JUnit Bridge to a Arquillian Custom Junit Container, so the JUnit dependencies are not packaged anymore inside the extension, and can be consumed for an external Bundle (as portla-test).

Thanks in advance,

@csierra @jorgeferrer

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:restest

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@shuyangzhou made some changes in https://github.com/brianchandotcom/liferay-portal/pull/24440

Waiting for results.

**Pull request closed without merging**
