### PR TITLE
LPS-68485

### PR DESCRIPTION
**Pull request by Ithildir**
cc @jonmak08

### CODE REVIEW

**Comment by jonmak08** [comment]
Thanks @Ithildir!

**Comment by vicnate5** [comment]
Workflow test failure unrelated. Fix sent at https://github.com/brianchandotcom/liferay-portal/pull/43608

**Comment by jrhoun** [comment]
@vicnate5 thanks :)

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@brianchandotcom 
We want to get a second look at the lpkg startup batch failure.

CC @jpince @brianchiu @jeffreyyang @brunobasto @jbalsas @jrhoun @jhendley

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
