### PR TITLE
LPS-64193 formatting

### PR DESCRIPTION
**Pull request by jhinkey**
cc/ @rbohl, @marcellustavares

### CODE REVIEW

**Comment by marcellustavares** [comment]
Thanks @jhinkey @rbohl :+1:

**Comment by jhinkey** [comment]
@marcellustavares - the CI server is reporting compilation errors.

**Comment by marcellustavares** [comment]
I can fix and resend @jhinkey, would you mind sending the pull to me? 

Thanks

**Comment by jhinkey** [comment]
Here it is https://github.com/marcellustavares/liferay-portal/pull/1325

Thanks

On 3/28/2016 5:41 PM, Marcellus Tavares wrote:
>
> I can fix and resend @jhinkey <https://github.com/jhinkey>, would you
> mind sending the pull to me?
>
> Thanks
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/38199#issuecomment-202591651>
>

-- 
Jim Hinkey
Sr. Knowledge Engineer
Liferay, Inc.
www.liferay.com <http://www.liferay.com>

Visit Us: www.liferay.com <http://www.liferay.com> | Like Us:
facebook.com/liferay <http://facebook.com/liferay> | Follow Us:
twitter.com/liferay <http://twitter.com/liferay>

**Pull request closed without merging**
