### PR TITLE
LPS-86123 Regenerate lock files

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:relevant

@jbalsas this failure seems related?
```
     [exec] src/main/resources/META-INF/resources/Navigation.soy.js -> classes/META-INF/resources/Navigation.soy.js
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/hello-soy/hello-soy-navigation-web/node_modules/liferay-npm-bundler/lib/config/index.js:360
     [exec] 			throw err;
     [exec] 			^
     [exec] 
     [exec] SyntaxError: Unexpected token } in JSON at position 187
     [exec]     at JSON.parse (<anonymous>)
     [exec]     at readJsonSync (/opt/dev/projects/github/liferay-portal/modules/apps/hello-soy/hello-soy-navigation-web/node_modules/read-json-sync/index.js:10:15)
     [exec]     at loadConfig (/opt/dev/projects/github/liferay-portal/modules/apps/hello-soy/hello-soy-navigation-web/node_modules/liferay-npm-bundler/lib/config/index.js:357:52)
     [exec]     at Object.<anonymous> (/opt/dev/projects/github/liferay-portal/modules/apps/hello-soy/hello-soy-navigation-web/node_modules/liferay-npm-bundler/lib/config/index.js:73:1)
     [exec]     at Module._compile (module.js:652:30)
     [exec]     at Object.Module._extensions..js (module.js:663:10)
     [exec]     at Module.load (module.js:565:32)
     [exec]     at tryModuleLoad (module.js:505:12)
     [exec]     at Function.Module._load (module.js:497:3)
     [exec]     at Module.require (module.js:596:17)
     [exec] npm ERR! code ELIFECYCLE
     [exec] npm ERR! errno 1
     [exec] npm ERR! hello-soy-navigation-web@3.0.0 build: `npm run build:soy && npm run compile && liferay-npm-bundler && npm run cleanSoy`
     [exec] npm ERR! Exit status 1
     [exec] npm ERR! 
     [exec] npm ERR! Failed at the hello-soy-navigation-web@3.0.0 build script.
```

**Comment by jpince** [comment]
@yichenroy @michaelhashimoto this pull should have auto-closed for a compile error, see above

**Comment by jbalsas** [comment]
It sure does, @jpince, I think I missed a `,` in the SF commit.

@diegonvs, can you fix that json in the `.npmbundlerrc` and resend, please?

**Comment by jpince** [comment]
ci:close

**Comment by jpince** [comment]
ci:stop @jbalsas thanks!

**Comment by michaelhashimoto** [comment]
@jpince - Ahh. I never uncommented it after turning it off because of this issue:
https://issues.liferay.com/browse/LRQA-45288

I fixed the autoclose rules here:
https://github.com/liferay/liferay-jenkins-ee/commit/cdeb58a3190734cc89387616a0a8df3fa45b66f5

**Comment by diegonvs** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
