### PR TITLE
LPS-102884 Methods to retrieve segmented content

### PR DESCRIPTION
**Pull request by epgarcia**
@ealonso

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
ci:test:close

**Comment by darquesdev** [comment]
Please, don't review this PR, instead review https://github.com/brianchandotcom/liferay-portal/pull/80588

**Comment by epgarcia** [comment]
See #80588

**Pull request closed without merging**
