### PR TITLE
LPS-92053 Override getEntityFields for resources with creator schema

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
These failures are already happening, appeared as unique to me because I am adding more tests, but the cause is not related to this PR.

**Comment by jpince** [comment]
@inacionery failures will be fixed later today by @nhpatt

**Comment by nhpatt** [comment]
Most of them should be fixed here: https://github.com/brianchandotcom/liferay-portal/pull/73969

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by inacionery** [comment]
ci:test:relevant

**Comment by inacionery** [comment]
Forwarded to https://github.com/brianchandotcom/liferay-portal/pull/74043 to fix rebase issue

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ce2ae791aa...4c15764680

**Pull request closed without merging**
