### PR TITLE
LPS-153121

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPS-153121

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:forward

**Comment by magjed4289** [comment]
ci:reopen

**Comment by magjed4289** [comment]
ci:forward

**Comment by magjed4289** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c520d000ee...da584f803e

**Comment by brianchandotcom** [comment]
Nice thx @magjed4289

**Pull request closed without merging**
