### PR TITLE
master-qa-17332

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LRQA-17332
https://issues.liferay.com/browse/LPS-57789

@brianchandotcom 
This one should address the 'hikari' error causing portal smoke test failures (from LPS-57789).

### CODE REVIEW

**Comment by brianchiu** [comment]
@brianchandotcom 

I would like to run the PR tester a couple times on this to be sure before you merge.

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@brianchandotcom 
Alright. I think this is good.

**Comment by brianchandotcom** [comment]
@brianchiu please ensure Dante fixes this. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/26a3d3df15...58e347c15b

**Comment by brianchandotcom** [comment]
@mjbradford89 fyi

**Comment by brianchiu** [comment]
@brianchandotcom 
Yeah, I'll make sure it gets fixed.

**Comment by brianchiu** [comment]
The pull with the submitted fix is here:
https://github.com/brianchandotcom/liferay-portal/pull/29183

**Pull request closed without merging**
