### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
Only unrelated test failure. See https://github.com/hhuijser/liferay-portal/pull/4944

Been trying to get this one forwarded for over a week :(

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6f54e8a498...468e3d3b97

**Comment by brianchandotcom** [comment]
@hhuijser I backported this to 7.3.x.

**Pull request closed without merging**
