### PR TITLE
LPS-66698 Update workspace to use GA2

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
@Ithildir I merged, but can you resend? I'm not able to publish.

```
The Test.testSrcDirs property has been deprecated and is scheduled to be removed in Gradle 3.0. Support for TestNG Javadoc annotations will be removed in Gradle 3.0.
:sdk:gradle-plugins-workspace:compileJava
/Users/brian/dev/projects/github/liferay-portal/modules/sdk/gradle-plugins-workspace/src/main/java/com/liferay/gradle/plugins/workspace/util/GradleUtil.java:37: error: incompatible types
                DynamicObject dynamicObject = DynamicObjectUtil.asDynamicObject(object);
                                                                               ^
  required: org.gradle.api.internal.DynamicObject
  found:    org.gradle.internal.metaobject.DynamicObject
/Users/brian/dev/projects/github/liferay-portal/modules/sdk/gradle-plugins-workspace/src/main/java/com/liferay/gradle/plugins/workspace/util/GradleUtil.java:39: error: cannot find symbol
                if (!dynamicObject.hasProperty(name)) {
                                  ^
  symbol:   method hasProperty(String)
  location: variable dynamicObject of type DynamicObject
/Users/brian/dev/projects/github/liferay-portal/modules/sdk/gradle-plugins-workspace/src/main/java/com/liferay/gradle/plugins/workspace/util/GradleUtil.java:43: error: cannot find symbol
                Object value = dynamicObject.getProperty(name);
                                            ^
  symbol:   method getProperty(String)
  location: variable dynamicObject of type DynamicObject
Note: /Users/brian/dev/projects/github/liferay-portal/modules/sdk/gradle-plugins-workspace/src/main/java/com/liferay/gradle/plugins/workspace/util/GradleUtil.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 errors
```

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/45603bd0dd...741fd95fd2

**Comment by Ithildir** [comment]
I sent a fix at https://github.com/brianchandotcom/liferay-portal/pull/40855.

**Pull request closed without merging**
