### PR TITLE
LPS-91859 Add Form Strucuture Resorce to Forms Headless API

### PR DESCRIPTION
**Pull request by victorlaerte**

### CODE REVIEW

**Comment by victorlaerte** [comment]
@brianchandotcom all the changes request in last PR are done, but https://github.com/brianchandotcom/liferay-portal/pull/70529/commits/b13b954ee18e667879c4ed7ed3bee7cc6f4c0b6d is still needed

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/84c22a1ebd...8c8ff9549c

**Comment by brianchandotcom** [comment]
@nhpatt guys.. this pull doesn't make any sense to me.

I closed it earlier because it added a dependency to Gson that was never used. We still have unused 

compileOnly group: "javax.portlet", name: "portlet-api", version: "3.0.0"

I don't see it imported anywhere. I removed it and things compiled fine.

I also don't understand the change to the generated test case. @victorlaerte please consult with @nhpatt before resending it to me.

@nhpatt in the interest of moving things forward, I committed your yaml change, and your regeneration. But I need @victorlaerte to send the rest.

**Comment by victorlaerte** [comment]
@brianchandotcom I'll fix the `build.gradle` file because as I split all the work I have done to send you in more than one PR this commit ended up getting nonsense. I'll fix and resend.

About the test case, I already consulted @nhpatt and he asked me to ping @petershin about it, but we will talk again tomorrow. Thanks.

**Comment by brianchandotcom** [comment]
@nhpatt I found out why the test case is broken.. it's not from a bad test.. it's from a bad openapi.yaml

It's because you're doing a put for object A when the test is for object B...

Please fix the openapi.yaml and the test will work @victorlaerte fyi

I had to revert it in upstream.

**Pull request closed without merging**
