### PR TITLE
LPS-60502

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@JorgeFerrer

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchandotcom** [comment]
@mhan810 please resend with fix from @JorgeFerrer since he says this pull is bad.

**Comment by mhan810** [comment]
Brian I already pushed up the changes on the same pull.  can you reopen?

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
No worries Mike. I will resend this with some stuff on top of it that I was working on.

**Pull request closed without merging**
