### PR TITLE
LPS-85887 Fix Broken test in master

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by jpince** [comment]
@cgoncas weird errors, not sure if they're caused by headless-apio code or something else
```
     [exec] com.liferay.structured.content.apio.internal.architect.resource.test.StructuredContentNestedCollectionResourceTest > testGetJournalArticleWrapperFilterByPermission STARTED
     [exec] java.lang.reflect.InvocationTargetException
...
     [exec] Caused by: com.liferay.portal.kernel.security.auth.PrincipalException$MustHavePermission: User 39653 must have VIEW permission for com.liferay.journal.model.JournalArticle 39638
```
```
     [exec] com.liferay.structured.content.apio.client.test.StructuredContentApioTest > testStructuredContentsMatchesSelfLink STARTED
     [exec] 16:00:22,100 ERROR [http-nio-8080-exec-6][ErrorUtil:79] Unknown column name groupName
     [exec] Unknown column name groupName
     [exec] 
     [exec] com.liferay.structured.content.apio.client.test.StructuredContentApioTest > testStructuredContentsMatchesSelfLink FAILED
     [exec]     Server returned status 500 and content {
     [exec]       "statusCode" : 500,
     [exec]       "title" : "Internal Server Error"
     [exec]     }
```
```
     [exec] com.liferay.structured.content.apio.client.test.StructuredContentApioTest > testStructuredContentsExistsInContentSpaceEndpoint STARTED
     [exec] 16:00:22,478 ERROR [http-nio-8080-exec-8][ErrorUtil:79] Unknown column name groupName
     [exec] Unknown column name groupName
     [exec] 
     [exec] com.liferay.structured.content.apio.client.test.StructuredContentApioTest > testStructuredContentsExistsInContentSpaceEndpoint FAILED
     [exec]     Server returned status 500 and content {
     [exec]       "statusCode" : 500,
     [exec]       "title" : "Internal Server Error"
     [exec]     }
```
https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/106555/consoleFull

**Comment by cgoncas** [comment]
Ok, let me check :)

**Comment by cgoncas** [comment]
The 500 internal Server Error erros are going to be fixed with the pull: https://github.com/brianchandotcom/liferay-portal/pull/63747

**Comment by cgoncas** [comment]
Tomorrow I will take a look to the log error, a ExceptionLogger should be added i think  :)

**Comment by jpince** [comment]
sounds good, thanks!

**Pull request closed without merging**
