### PR TITLE
LRQA-26003 Add an MD5 check to ensure quality of downloaded files

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRQA-26003

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by sharonchoi** [comment]
Tags tests are failing due to bug, unrelated to this pull: https://issues.liferay.com/browse/LPS-66724
And Message Boards test failure is a fluke, as the test ran too quickly before the thread finished publishing, and is not reproducible locally.

**Comment by michaelhashimoto** [comment]
ci:retest

**Pull request closed without merging**
