### PR TITLE
Lps 74897

### PR DESCRIPTION
**Pull request by shuyangzhou**
@brianchandotcom please release petra-lang 1.0.0 after merge this. I need to add petra-lang dependency on subrepo first, before starting to apply its usages. It has to be done by this order, because if we apply on core first, all subrepo's jspc will break, due the transitive dependencies util-taglib -> kernel -> petra-lang .

### CODE REVIEW

**Comment by shuyangzhou** [comment]
this pull has passed CI last night at https://github.com/shuyangzhou/liferay-portal/pull/4900, feel free to skip the test if you want.

**Comment by shuyangzhou** [comment]
CC @rotty3000 @jrao this is part 1 of petra-lang, there will be part2 and part3, which will eventually remove the duplication of CentralizedThreadLocal. Then everyone will be using the one from petra-lang.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/81e023367c...796f972896

**Comment by brianchandotcom** [comment]
@shuyangzhou published!

**Comment by shuyangzhou** [comment]
Thanks @brianchandotcom !

**Pull request closed without merging**
