### PR TITLE
[DON'T MERGE TILL TESTS PASS] LPS-91287 Don't index system layouts since they are hidden

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
Hi @brianchandotcom, please don't merge it till the tests pass. Thanks!

/cc @ealonso @brianchiu

**Comment by brianchiu** [comment]
ci:close

**Comment by brianchiu** [comment]
ci:test:bundle

**Comment by brianchiu** [comment]
ci:test:wem-msb

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:relevang

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
@pavel-savinov I'm sorry. This error has affected both of the ci test relevant runs. I'm running it again but I'll be off before the results come back.
```
Could not resolve module: com.liferay.fragment.web
```

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
@brianchiu Last test:relevant failure is not relevant for sure(Elasticsearch remote cluster test). But we finally decided to pass it one-by-one, started with LPS-91286 here: https://github.com/brianchandotcom/liferay-portal/pull/69030 and then I'll send LPS-91287 separately. Thanks a lot for your help on this.

**Comment by brianchiu** [comment]
@pavel-savinov Got it.

That elastic search remote cluster test is actually failing because of this: https://issues.liferay.com/browse/LPS-91608.  The test adds a message boards post. So that failure is unrelated.

**Pull request closed without merging**
