### PR TITLE
LPS-69436 Flags taglib as metal component

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Hey Brian,

this is what you commented in the previous PR, and which I have resolved in this one:

> 
>     provided group: "com.liferay", name: "com.liferay.frontend.taglib.soy", version: "1.0.3"
>     should be
>     provided group: "com.liferay", name: "com.liferay.frontend.taglib.soy", version: "1.0.0"
>     I also don't see why
>     modules/apps/collaboration/blogs/blogs-web/build.gradle
>     modules/apps/collaboration/message-boards/message-boards-web/build.gradle
>     modules/apps/web-experience/asset/asset-publisher-web/build.gradle
>     needed to be modified since the additonal compile time dependency is not used?
>     Please resend. Thx.

The dependency is needed because otherwise we get errors in CI, you can see them here: https://github.com/brianchandotcom/liferay-portal/pull/47930

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/47931

**Comment by ambrinchaudhary** [comment]
ci:retest

**Comment by ambrinchaudhary** [comment]
@sergiogonzalez @jbalsas

**Comment by brianchandotcom** [comment]
@shuyangzhou @preston-crary can you explain why we need the exact micro version? I thought we were always supposed to go with just minor?

**Comment by brianchandotcom** [comment]
Nvm, I see that your last commit put it back to 1.0.0. Reviewing it now.

**Comment by brianchandotcom** [comment]
@ambrinchaudhary we need to fix the root CI issue. If we have to modify blogs-web, and add

provided group: "com.liferay", name: "com.liferay.frontend.taglib.soy", version: "1.0.0"

for this to work, then that means any 3rd party module would now suddenly break as well unless it was recompiled with this dependency. That doesn't make sense. We need to fix the root cause. Please resend.

**Pull request closed without merging**
