### PR TITLE
LRQA-37340 Copy jenkins job config regen beanshell code into Java class

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-37340

Resend of https://github.com/brianchandotcom/liferay-portal/pull/56406

This pull request represents a first step towards moving the jenkins job config file regeneration logic into java. This pull copies the beanshell code into a java class and does some cleanup / reorganization. More drastic architectural changes are to follow in subsequent pull requests before we actually make the changeover so we can create job configurations by assembling config xml snippets.

CC: @cesar-polanco

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test

**Comment by pyoo47** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@shuyangzhou this just snuck in

```
com.liferay.portal.kernel.service.persistence.impl.PersistenceNestedSetsTreeManager is not fully covered
```
Can you assign this to someone to fix? Thx.

**Comment by brianchandotcom** [comment]
@pyoo47 sorry to be nit picky...

```
environmentSlavesPropertiesMap = _getEnvironmentSlavesMap
```
This is in the constructor...

I'm just trying to hammer in attention to detail. The design is great.

**Comment by brianchandotcom** [comment]
@pyoo47 I'm really trying to merge this in.. so made some progress here:

https://github.com/pyoo47/liferay-portal/pull/573

Please resend on top of that pull. The design is good, it's just the naming is still sloppy. I know you're capable of naming things well! You can do this.

**Comment by shuyangzhou** [comment]
@brianchandotcom it is caused by https://github.com/brianchandotcom/liferay-portal/pull/56417, you need to revert that pull.

**Comment by pyoo47** [comment]
@brianchandotcom This pull request was just intended as an initial step towards reorganizing all the jenkins job config file generation logic. The idea was to move the main portion of the config file generation logic out of bean shell and into java first. The overall architecture of the code is nowhere near where I want it to be yet, I just wanted to move it over and clean it up as an exercise to understand it better so we can come up with a better architecture. I've been talking with Cesar about breaking out of the procedural approach that we have now. Breaking the problem down by using more classes will create context for simpler and clearer names.

**Comment by pyoo47** [comment]
Resent https://github.com/brianchandotcom/liferay-portal/pull/56494

**Pull request closed without merging**
