### PR TITLE
LPS-82094 kb

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/81aa45af4b...f3e4983846

**Comment by brianchandotcom** [comment]
@nhpatt nice.. minor changes upstream.

**Comment by nhpatt** [comment]
Thanks!

**Comment by nhpatt** [comment]
ci:stop

**Pull request closed without merging**
