### PR TITLE
LPS-74839 petra-json-ws - reorganize exceptions and bug fixes

### PR DESCRIPTION
**Pull request by igorbeslic**
Hi Brian please review changes. @ivicac

### CODE REVIEW

**Comment by jpince** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by ivicac** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@igorbeslic @ivicac see acffab829d5d695860d4dbd765eecd261903b523 2809bca4942f2227d0f2bc4fca8ed0371e366b5f and cee2934ecebfdb7493295e9c74d7d03f245a170c

thx.

**Pull request closed without merging**
