### PR TITLE
LPD-41430 Follow up

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPD-41430

### CODE REVIEW

**Comment by p-albuquerque** [comment]
Requested here: https://github.com/brianchandotcom/liferay-portal/pull/156404

**Comment by p-albuquerque** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/dd491371bc...d3a5cb901b

**Comment by brianchandotcom** [comment]
@p-albuquerque see changes in my origin.

**Comment by samuelromeiro** [comment]
New follow-up: https://github.com/liferay-bpm/liferay-portal/pull/3924

**Pull request closed without merging**
