### PR TITLE
LPS-103898 Update tests

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@hhuijser how come test:sf is testing everything and not just a subset of files?

@pyoo47 this is making test SF take a lot longer... something is off.

**Comment by brianchandotcom** [comment]
See https://github.com/ealonso/liferay-portal/pull/2627

**Comment by hhuijser** [comment]
@pyoo47 @brianchandotcom looks like it only happened for this pull... looking into it

**Comment by hhuijser** [comment]
ci:test:sf

**Comment by hhuijser** [comment]
Weird, only happened that one time...

**Comment by hhuijser** [comment]
@pyoo47 could it be that the following code showed files in `modules/util/source-formatter` because `liferay/liferay-portal` and `brianchandotcom/liferay-portal` were out of sync at the moment of testing?
https://github.com/liferay/liferay-portal/blob/master/build-test-batch.xml#L5882-L5886

**Pull request closed without merging**
