### PR TITLE
LRQA-25727 Implement DB2 legacy database restore logic.

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-25727

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@brianchandotcom 
From a poshi perspective, this pull is safe to merge.

Sybase upgrade failures will go away after the commits from this pull make it into source. (I saw that you closed it but I don't see the commits in source.)
https://github.com/brianchandotcom/liferay-portal/pull/40477

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/372d97717c...c4a5bc0b6c

**Comment by brianchandotcom** [comment]
@pyoo47 the spacing was a bit off, please see 2fff3f553a85684dde067519693143054d812c21 and c4a5bc0b6c45dbf7800807d3e372f4b22a85d31c

Thx.

**Pull request closed without merging**
