### PR TITLE
[TS] LPS-176530 Web content assets are not anonymized when the user data is deleted

### PR DESCRIPTION
**Pull request by alessandromalves**
This is only for master
https://issues.liferay.com/browse/LPS-176530
cc.: @IstvanD @ealonso

### CODE REVIEW

**Comment by alessandromalves** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/11281

**Comment by alessandromalves** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/df9b4871f7...cfee1e3354

**Comment by brianchandotcom** [comment]
@IstvanD see 9379c771dd9b61a65cfc5f76b413de2b49c75a7e

**Pull request closed without merging**
