### PR TITLE
LPS-67449 use default friendly URL normalizer in case when service is not available

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
@brianchandotcom We really need this mix here. The problem is that when we execute core upgrade and verify process, there is no application context registered, it goes after the upgrade(see https://github.com/brianchandotcom/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/tools/DBUpgrader.java#L104). In this case we have to use old-style approach with setter.
So, we need [this line](https://github.com/pavel-savinov/liferay-portal/blob/0e89cb1c926b3559b48e2305c3a88d66bb42e191/portal-impl/src/META-INF/util-spring.xml#L365) to regiter our bean as an OSGi service during app context registration, and [this](https://github.com/pavel-savinov/liferay-portal/blob/0e89cb1c926b3559b48e2305c3a88d66bb42e191/portal-impl/src/META-INF/util-spring.xml#L366) to be able to use FriendlyURLNormalizer in upgrades and verify processes.
And further we register the context and use FriendlyURLNormalizer as an OSGi service with service tracker.
Does it make sense? Could you please take a look once again?

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
The same tests fail on all the PRs, pretty sure that they are unrelated :)

**Comment by brianchandotcom** [comment]
See https://github.com/pavel-savinov/liferay-portal/pull/110

**Pull request closed without merging**
