### PR TITLE
LRQA-42550 | master

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LRQA-42550

/cc @austinchiang

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:reopen

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
ci:reopen

**Comment by liuxingye** [comment]
The sf issue is not related to my commit.

**Comment by jpince** [comment]
ci:test:sf

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
