### PR TITLE
LPS-80517

### PR DESCRIPTION
**Pull request by tinatian**
cc @shuyangzhou @hhuijser

### CODE REVIEW

**Comment by hhuijser** [comment]
@tinatian it says there are failures unique to this pull?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5bc0a7d508...467fc9250e

**Comment by brianchandotcom** [comment]
Thanks @tinatian @hhuijser !

@hhuijser are you going to send me changes to 7.0.x?

**Comment by hhuijser** [comment]
@brianchandotcom, yup

**Pull request closed without merging**
