### PR TITLE
LPS-43918

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2a6788957f...de46ec651e

**Comment by brianchandotcom** [comment]
@hhuijser can you update ServiceBuilder with more @Deprecated and @deprecated for *Persistence*, see ad1cea9ac249103ed34ad3684023eb231bc388f2

Thx

**Comment by hhuijser** [comment]
@brianchandotcom 

Skipped those on purpose for now as I wasn't sure if it was okay to simply take the tags/annotations from 
EntityImpl.java and propagate those to the persistence files.

**Comment by brianchandotcom** [comment]
Yes, it's safe to

Thx

**Pull request closed without merging**
