### PR TITLE
LPS-53432 Add help comment - @Brian: feel free to delete this commit if you think it's useless

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/761b0ab4a5...6dbeb74e4d

**Comment by brianchandotcom** [comment]
@lipusz I did remove the comment and moved the logic to its own method. Can you add a test? It would better highlight why that is needed, better than a comment.

Thx!

**Comment by lipusz** [comment]
OK. Thank you.

I initially added test for this: https://github.com/ealonso/liferay-portal/pull/339

**Comment by lipusz** [comment]
Will send once we fixed the failures.

**Pull request closed without merging**
