### PR TITLE
LPS-68336 Add upgrade process

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
modules-unit still broken. Please resend.

**Comment by brianchandotcom** [comment]
Oh, nvm, that's unrelated... and it's for 7.0.x.

**Comment by brianchandotcom** [comment]
@marcellustavares merged. Please send a follow up pull and add lfrbuild-portal file.

**Comment by marcellustavares** [comment]
sent to https://github.com/brianchandotcom/liferay-portal/pull/43834

**Comment by marcellustavares** [comment]
thx Brian

**Pull request closed without merging**
