### PR TITLE
LPS-67023

### PR DESCRIPTION
**Pull request by Ithildir**
Hi,
Please let this pull finish.

Thanks!

@codyhoag: would you please review the changelogs? Thank you!

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/778ad042eb...b2409f861f

**Comment by brianchandotcom** [comment]
@Ithildir in the future, we should split up the Gradle changes from the ticket, because I backported the Gradle changes and not the bug fix, and support will find it difficult to sift through everything.

**Comment by jbalsas** [comment]
Hey @brianchandotcom, having mixed the changes is probably my fault, since I sent it to Andrea when I saw room for improvement for the Front-End related tasks...

I agree that we should split it up in the past. In any case, I was already planning to open a BPR for the bug and send the backport request as well since it has been reported several times by some clients. Hopefully, that would make this a little bit less confusing for support.

I'll be creating the BPR ticket, testing and sending the backported fix on monday.

Thanks!

**Pull request closed without merging**
