### PR TITLE
LPS-65842 Use direct service reference instead passing thru the proxy

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
@vicnate5 are those real?

**Comment by vicnate5** [comment]
@marcellustavares I am not familiar with these integration tests

**Comment by marcellustavares** [comment]
Thanks @vicnate5,

**Comment by brianchandotcom** [comment]
@marcellustavares those look real to me. Every single one is breaking. Please resend.

**Pull request closed without merging**
