### PR TITLE
Lps 68289 59

### PR DESCRIPTION
**Pull request by shuyangzhou**
@Ithildir please see https://github.com/brianchandotcom/liferay-portal/commit/b8a5c58cdce3aa8bbfbcb57053e37bc8216c7b84 , please move it to java code. Thanks!

@brianchandotcom this is trying to figure out when the annoying arquillian broken connection happens, what portal is doing, to provide us more context info to figure out a solution.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
RubySassCompilerTest.testCompileFile error seems real. Please resend @shuyangzhou

**Comment by shuyangzhou** [comment]
ci:reopen , no, it is not caused by this pull.

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
It was an OOM failure, and since Hugo bumped up the heap size for SF test, it should automatically fixed this too.

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@ithildir please see changes to this pull for modules/build.gradle

merged.

**Comment by Ithildir** [comment]
@shuyangzhou and @Preston-Crary, I sent a pull to move https://github.com/liferay/liferay-portal/commit/2660b33bf7daee763b4ea87167af4eb1b03a3157 to Java: https://github.com/brianchandotcom/liferay-portal/pull/45247

**Comment by shuyangzhou** [comment]
Thanks @Ithildir !

**Pull request closed without merging**
