### PR TITLE
 LPS-164464 buildLang

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-164464

@BarbaraCabrera 
@ealonso

### CODE REVIEW

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. There is a failure related to SF on the PR but it is related to this conversation on [slack](https://liferay.slack.com/archives/C04D8HMEF/p1664430958845789), some files were modified after the ant all.

**Comment by ozysouza** [comment]
:heavy_check_mark: ci:test:stable - 28 out of 28 jobs passed
:x: ci:test:relevant - 174 out of 181 jobs passed in 3 hours 40 minutes

**Comment by ozysouza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e717a2d54e...b1e3210d30

**Pull request closed without merging**
