### PR TITLE
LRQA-71707 | master

### PR DESCRIPTION
**Pull request by bbqbronson**
https://issues.liferay.com/browse/LRQA-71707

### CODE REVIEW

**Comment by bronsonsoda** [comment]
ci:open

**Comment by bronsonsoda** [comment]
ci:open

**Comment by bronsonsoda** [comment]
ci:reopen

**Comment by bronsonsoda** [comment]
ci:test:sf

**Comment by bronsonsoda** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f19f186b8e...a7f6f522c8

**Pull request closed without merging**
