### PR TITLE
LPS-107055 use new keys

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
@ealonso

**Comment by brianchandotcom** [comment]
@victorg1991 can you get someone to fix those Poshi tests.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/562a6b0218...29839f16b5

**Comment by ealonso** [comment]
Hey @brianchandotcom,

The tests that appears below "unique for this pull" are the same from other pulls: see https://github.com/brianchandotcom/liferay-portal/pull/83273

**Comment by ealonso** [comment]
Hey @liulukiwi @Tim-Cao,

Could you please fix those tests failures?

Thanks!!

**Comment by Tim-Cao** [comment]
Hey @ealonso , those case are caused by https://issues.liferay.com/browse/LPS-106882

**Pull request closed without merging**
