### PR TITLE
LPS-68497 Create .lfrbuild-portal files

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pyoo47 I need help with testing this build. What's going on with Local Git?

**Comment by pyoo47** [comment]
@brianchandotcom I spoke with Sam and he told me that the issue is with GitHub. This is the reason why he created git custom fetch in the first place. Sometimes, GitHub doesn't respond quickly enough so we abort instead of keeping the connection open forever. I think we just have to keep retrying the pull until it works.

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by pyoo47** [comment]
@michaelhashimoto Can you take a look at this pull? It keeps failing because of what looks like Github issues but other liferay-portal pulls have been working. We've retried this too many times for this to be a coincidence..

**Comment by michaelhashimoto** [comment]
@adolfopa @brianchandotcom @pyoo47 
I think there was a combination of things that went wrong on this pull.

1. There was a compilation error. ([link](https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-dist(master)/AXIS_VARIABLE=tomcat,label_exp=!master/280/console))
2. There was a Local Git failure.
3. There was a bug in jenkins. ([LRQA-28233](https://issues.liferay.com/browse/LRQA-28233), [pull](https://github.com/brianchandotcom/liferay-jenkins-ee/pull/1850)

@adolfopa - Can you look into this error?  Sorry for the confusion.  Thanks!

**Comment by brianchandotcom** [comment]
@adolfopa please resend. Thx.

**Pull request closed without merging**
