### PR TITLE
Lps 72954

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest (@pyoo47 what happened?)

**Comment by pyoo47** [comment]
@brianchandotcom It bombed out because of the GitHub outage yesterday evening. It failed to get a response from GitHub while trying to post the GitHub message.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a270776de1...7d511edff5

**Pull request closed without merging**
