### PR TITLE
Lps 73562

### PR DESCRIPTION
**Pull request by shuyangzhou**
@mhan810 @david-truong this is the bundle blacklist implementation.

@jhinkey we need to document this feature, please see the ticket for usage info. In case you have questions, feel free to ping @mtambara for them.

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:retest

**Comment by jhinkey** [comment]
Thank you Shuyang. The doc ticket is https://issues.liferay.com/browse/LRDOCS-3934.

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/51153

**Pull request closed without merging**
