### PR TITLE
LPS-92739 Updates snapshots

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/64dee62972...056bda5d7d

**Comment by jpince** [comment]
@john-co this looks similar to the error @brunobasto posted about in Slack? https://liferayproductdev.slack.com/archives/C04D8HMEF/p1558727085007800

cc/ @alexcandidos

**Comment by jeyvison** [comment]
@jpince. I Believe it's the same but we didn't touch segments in this pull. 

@jonh-co can you help us with this ?

**Comment by reizero00** [comment]
@manoelcyreno

**Comment by reizero00** [comment]
ci:test:ec2b3a679e784fd2bc0434fb5d7a0a08165f071e:norebase

**Comment by reizero00** [comment]
I'm running these changes against a "stable" SHA to see if it comes out clean. This way we can fix or revert the changes that caused the segmentation problem in a different PR. Fingers crossed

**Comment by reizero00** [comment]
Bruno sent a pull here to fix it :)

https://github.com/brianchandotcom/liferay-portal/pull/73716

**Comment by brunobasto** [comment]
I suspect the compile failure on segments might have been cause by poor resolution of conflicts on my end when rebasing Chema's PR with master. So the failure is probably unique to this PR

**Pull request closed without merging**
