### PR TITLE
LPS-80126 Create AnonymousUserConfiguration

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-80126](https://issues.liferay.com/browse/LPS-80126).<br><br>Hey Brian, this is a resend of https://github.com/brianchandotcom/liferay-portal/pull/57722 that fixes the log assertion failures.  Please allow the tests to finish.<br><br>/cc @pei-jung @willnewbury

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test

**Comment by drewbrokke** [comment]
@brianchandotcom this pull doesn't touch anything in `blogs-*`.  It is `user-associated-web` only.

**Comment by drewbrokke** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3377b50820...76b0679e76

**Comment by brianchandotcom** [comment]
@drewbrokke please see my changes in upstream. Thx.

**Pull request closed without merging**
