### PR TITLE
LPS-70865 Minor fallback mechanism we use lot of places during staging

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
@brianchandotcom my change has nothing to do with the semver errors. I've added a test, and changed implementation, no semantic errors for my code.

**Comment by matethurzo** [comment]
ci:reopen

**Comment by matethurzo** [comment]
@brianchandotcom the tests are also unrelated

**Comment by marcellustavares** [comment]
Poshi tests should be fixed at https://github.com/brianchandotcom/liferay-portal/pull/47539

**Comment by brianchandotcom** [comment]
@matethurzo semantic failure is related no? Please resend.

**Comment by matethurzo** [comment]
@brianchandotcom the previous comment was about that, they are unrelated.

**Comment by matethurzo** [comment]
@brianchandotcom resending anyway

**Pull request closed without merging**
