### PR TITLE
LPS-63721 fix scroll when closing simulation panel

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pyoo47 this one hung too randomly

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c12e165d5e...bca722d2cd

**Comment by pyoo47** [comment]
@brianchandotcom Seems like we are seeing many incidences of buildURLs not being returned by downstream jobs lately. Perhaps there are some hiccups with the shared drive? In any case, we are working on a new way of retrieving the downstream jobs buildURLs that should prevent this from happening. [LRQA-18824](https://issues.liferay.com/browse/LRQA-18824)

**Pull request closed without merging**
