### PR TITLE
LPS-65495 master

### PR DESCRIPTION
**Pull request by akosthurzo**
resending - changed portal-impl version in build.gradle of staging-bar-web

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
I had to stop and retest this pull because a recent CI pull that got merged into upstream broke the PR tester. The source of this problem has been reverted.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@akosthurzo 

can you rename

staging.disable.live.site.locking

to

staging.live.group.locking.enabled

That matches the existing key

staging.live.group.remote.staging.enabled

in a more consistent fashion.

Thx.

**Pull request closed without merging**
