### PR TITLE
LPS-57562 Support for apps to Display the number notification in the product menu

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
@evannagayama can you help us with these failures? we haven't changed the UI in this pull... (at least on purpose...) and we can't reproduce the issue manually...

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@evannagayama please fix and resend? Thx.

**Comment by evannagayama** [comment]
@juliocamarero, there are rebase errors. Can you please rebase it and send me this pull request? Thanks

**Pull request closed without merging**
