### PR TITLE
LPD-35429 BatchEngineBrokerTest test fix

### PR DESCRIPTION
**Pull request by 4lejandrito**
https://liferay.atlassian.net/browse/LPD-35381

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/17b73a4394...b3dedd42fe

**Comment by brianchandotcom** [comment]
@4lejandrito any way to tab this?

```
<p>
  <img alt="""""""" height=""""202"""" src=""""http://localhost:8080/image/company_logo"""">
</p>
```

**Comment by 4lejandrito** [comment]
As discussed, we use the same format from the export output. So it must stay that way.

**Pull request closed without merging**
