### PR TITLE
LRQA-24284, LRQA-31106, LRQA-30958 | master

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-24284
https://issues.liferay.com/browse/LRQA-30958
https://issues.liferay.com/browse/LRQA-31106

@brianchandotcom These changes are **master-only**. Thanks!

cc @kenjiheigel @alee8888 @vicnate5 @sharonchoi @brianchiu @jpince

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fc17d2db83...9114991ab4

**Comment by kenjiheigel** [comment]
@anthony-chu, thanks for getting this in!

@anthony-chu, @brianchiu, @jpince, @brianwulbern, could we also backport this to ee-7.0.x? It would be helpful to have this on the ee-7.0.x branch because the hot fix and fix pack builds use that test base, which flood the CI servers' queue from time to time. Thanks!

**Comment by jpince** [comment]
@brianwulbern can you/auto team work on backporting this when you have time?

**Comment by brianwulbern** [comment]
@anthony-chu @kenjiheigel @jpince Yep, we can get to it.

**Comment by brianwulbern** [comment]
See https://github.com/brianchandotcom/liferay-portal-ee/pull/16819

**Pull request closed without merging**
