### PR TITLE
Lps 75330

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
@brianchandotcom we need an asset-api release after this merge, a snapshot is fine. Thanks!

**Comment by brianchandotcom** [comment]
@shuyangzhou can you resend? Rebase error. Thx.

**Comment by shuyangzhou** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/52834

**Pull request closed without merging**
