### PR TITLE
Lps 86938

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
Testing backport. this fix will be needed in 7.1.x
https://github.com/vicnate5/liferay-portal-ee/pull/138

**Comment by vicnate5** [comment]
@jpince

**Comment by vicnate5** [comment]
@brianchandotcom Test results look good on Master and 7.1.x. Please backport.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
