### PR TITLE
LPS-73119 As a developer, I would like to have a way to temporarily set OSGi Configuration values in a test

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-73119](https://issues.liferay.com/browse/LPS-73119).<br><br>/cc @pei-jung, @shuyangzhou

### CODE REVIEW

**Comment by drewbrokke** [comment]
cc @jonathanmccann FYI - this is the util I need for our integration test

**Comment by jpince** [comment]
ci:retest

**Comment by drewbrokke** [comment]
@brianchandotcom is there any chance you can review this soon, or even today?  I have a another large pull request in ready to submit that depends on this one. Just let me know :)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/897aa8c926...b2918ff15a

**Pull request closed without merging**
