### PR TITLE
LPS-147252, LPS-147253, LPS-146976 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-147252
https://issues.liferay.com/browse/LPS-147253
https://issues.liferay.com/browse/LPS-146976

This is only for master.

@lfbesada
@sandrodw3

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/7434
❌ ci:test:stable - 27 out of 32 jobs passed
❌ ci:test:relevant - 27 out of 33 jobs passed in 1 hour 38 minutes

**Comment by lfbesada** [comment]
ci:close

**Comment by lfbesada** [comment]
This pull request is On Hold.

**Pull request closed without merging**
