### PR TITLE
LPS-59858

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@Ithildir is this googlecode.jsontoken a gradle cache error? I don't see it locally. Can you double check? Thx.

ci:retest

**Comment by Ithildir** [comment]
Yes, it seems some POMs were missing, I sent them in https://github.com/brianchandotcom/liferay-portal/pull/32379.

**Comment by david-truong** [comment]
@jbalsas this is the fix for the RTL issue

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0ada66f4b0...fe158c8ccc

**Pull request closed without merging**
