### PR TITLE
LPS-134669 New tool to validate DB Partition schemas

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:reopen

**Comment by achaparro** [comment]
Forwarded manually, see https://github.com/achaparro/liferay-portal/pull/938#issuecomment-869833162

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@achaparro will resend.

**Pull request closed without merging**
