### PR TITLE
Lps 100598

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
CC @ericyanLr

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0a273981c6...1c96fdaffa

**Comment by brianchandotcom** [comment]
@mtambara I"m not backporting this... if it's a bug fix, send me a pull for 7.2.x (code is the same and should cherry pick neatly)

**Comment by mtambara** [comment]
Backport sent at https://github.com/brianchandotcom/liferay-portal-ee/pull/27082

**Pull request closed without merging**
