### PR TITLE
LPS-93652 We now have OSGi 6 on the class path during compileTestInte…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…gration. Fix the compile by upgrading.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@hhuijser I really want a pull updating all of our build.gradle dependencies so they have the same version.. or even if we don't do it for all, we should do it for as many lines as possible

**Comment by shuyangzhou** [comment]
Not sure whether gradle can do this or not. I think we should introduce a placeholder version like "global". When using that, let gradle refer to a global property file to look up the globally defined version for this dependency. We should still allow developer setting specific version just to handle special case. But at least with this "global" thing, we can easily tell, which dependency is trying to be a special case, which simply does not care.

**Comment by Preston-Crary** [comment]
@shuyangzhou and if we had something like that we wouldn't have to update 100+ files when we upgrade some jar, that would be great.

**Pull request closed without merging**
