### PR TITLE
LPS-62012 Use selector instead of button

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@juliocamarero is this cut and paste code from somewhere?

```
private String _getClassName(String className) {
	int pos = className.indexOf(AssetUtil.CLASSNAME_SEPARATOR);

	if (pos != -1) {
		className = className.substring(0, pos);
	}

	return className;
}

private String _getMessage(String className, Locale locale) {
	String message = null;

	int pos = className.indexOf(AssetUtil.CLASSNAME_SEPARATOR);

	if (pos != -1) {
		message = className.substring(pos + AssetUtil.CLASSNAME_SEPARATOR.length());

		className = className.substring(0, pos);
	}

	AssetRendererFactory<?> assetRendererFactory = AssetRendererFactoryRegistryUtil.getAssetRendererFactoryByClassName(className);

	if (pos == -1) {
		message = assetRendererFactory.getTypeName(locale);
	}

	return message;
}

private String _getURL(long groupId, long plid, PortletURL addPortletURL) {
	addPortletURL.setParameter("hideDefaultSuccessMessage", Boolean.TRUE.toString());
	addPortletURL.setParameter("groupId", String.valueOf(groupId));
	addPortletURL.setParameter("showHeader", Boolean.FALSE.toString());

	String addPortletURLString = addPortletURL.toString();

	addPortletURLString = HttpUtil.addParameter(addPortletURLString, "refererPlid", plid);

	return addPortletURLString;
}
```

Feels like it is.. probably should go in a common util

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/353c72d4e8...d453e1eb3e

**Comment by epgarcia** [comment]
I moved the duplicated logic to AssetUtil. Please see brianchandotcom/liferay-portal/pull/36163.

Thanks!

**Pull request closed without merging**
