### PR TITLE
LPS-52679 auto SF

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
hey @brianchandotcom, 

this was a tough one. I had to bisect to find out the issues so I squashed the changes interleaved with yours in order to make this work. 

The tests are already working with your changes, but there are some sortings that can be done, like reordering the parameters of callback methods because they are not recognized as those anymore or the initialization of the configuration. 

Bests.

**Comment by csierra** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx. See email.

**Pull request closed without merging**
