### PR TITLE
LPS-105606 Update liferay-npm-scripts to v16.0.0

### PR DESCRIPTION
**Pull request by wincent**
Main motivation here is to move us onto the latest release of eslint-config-liferay:

https://github.com/liferay/eslint-config-liferay/releases/tag/v14.0.0

This switches our defaults over to assume React, enabling us to delete a bunch of repetitive configuration files and replace them with a small number of configurations that opt-in to old-school Metal semantics.

### CODE REVIEW

**Comment by wincent** [comment]
Note that this release was based off of v15.0.0 (the last known-good release); it **doesn't** include the problematic changes that led the v15.1.0 update to be reverted in https://github.com/brianchandotcom/liferay-portal/pull/81770; @izaera is investigating the root cause of that one separately.

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
ci:test:bundle

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8f5111ed45...b8ff0a44a1

**Pull request closed without merging**
