### PR TITLE
Breaking changes

### PR DESCRIPTION
**Pull request by jhinkey**
cc/ @inacionery, @rbohl, @codyhoag

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0993fd5e20...bc0a7ef554

**Comment by brianchiu** [comment]
@alee8888 @michaelhashimoto

Do you know why wildfly failed on this one?

The error looks very much like the one described in: https://issues.liferay.com/browse/LRQA-22624

```
     [exec] [0m[33m16:01:01,249 WARN  [org.jboss.as.ee] (MSC service thread 1-4) WFLYEE0007: Not installing optional component org.springframework.web.context.request.async.StandardServletAsyncWebRequest due to an exception (enable DEBUG log level to see the cause)
     [exec] [0m[31m16:05:52,608 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0348: Timeout after [300] seconds waiting for service container stability. Operation will roll back. Step that first updated the service container was 'add' at address '[
     [exec]     ("core-service" => "management"),
     [exec]     ("management-interface" => "http-interface")
     [exec] ]'
     [exec] [0m[31m16:05:57,611 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0190: Step handler org.jboss.as.server.DeployerChainAddHandler$FinalRuntimeStepHandler@ed04c9 for operation {"operation" => "add-deployer-chains","address" => []} at address [] failed handling operation rollback -- java.util.concurrent.TimeoutException: java.util.concurrent.TimeoutException
     [exec] 	at org.jboss.as.controller.OperationContextImpl.waitForRemovals(OperationContextImpl.java:511)
     [exec] 	at org.jboss.as.controller.AbstractOperationContext$Step.handleResult(AbstractOperationContext.java:1369)
     [exec] 	at org.jboss.as.controller.AbstractOperationContext$Step.finalizeInternal(AbstractOperationContext.java:1328)
     [exec] 	at org.jboss.as.controller.AbstractOperationContext$Step.finalizeStep(AbstractOperationContext.java:1301)
     [exec] 	at org.jboss.as.controller.AbstractOperationContext$Step.access$300(AbstractOperationContext.java:1185)
     [exec] 	at org.jboss.as.controller.AbstractOperationContext.executeResultHandlerPhase(AbstractOperationContext.java:767)
     [exec] 	at org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:644)
     [exec] 	at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:370)
     [exec] 	at org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1344)
     [exec] 	at org.jboss.as.controller.ModelControllerImpl.boot(ModelControllerImpl.java:485)
     [exec] 	at org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:387)
     [exec] 	at org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:349)
     [exec] 	at org.jboss.as.server.ServerService.boot(ServerService.java:392)
     [exec] 	at org.jboss.as.server.ServerService.boot(ServerService.java:365)
     [exec] 	at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:299)
     [exec] 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by michaelhashimoto** [comment]
@brianchiu - I don't think that's the same one, I think @alee8888 fixed that one before by increasing the timeout.

**Comment by alee8888** [comment]
@brianchiu @michaelhashimoto 
This is a separate issue. It looks like the portal war is exceeding the blocking timeout of 300 seconds. I have created the following bug ticket to track any progrss.
https://issues.liferay.com/browse/LPS-64716

**Pull request closed without merging**
