### PR TITLE
LPS-126215, LPS-126225, LPS-126317, LPS-126318, LPS-126325 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-126215
https://issues.liferay.com/browse/LPS-126225
https://issues.liferay.com/browse/LPS-126317
https://issues.liferay.com/browse/LPS-126318
https://issues.liferay.com/browse/LPS-126325

This is only for master.

@david-gutierrez-mesa
@alexcandidos

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure cases are unrelated to changes in PR.
See https://github.com/liferay-echo/liferay-portal/pull/3668
✔️ ci:test:stable - 9 out of 9 jobs passed
❌ ci:test:relevant - 22 out of 26 jobs passed in 2 hours 6 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/19d993d6e3...99e03ebb04

**Comment by brianchandotcom** [comment]
@antonioalmeidab @gabrielargomes @gleicelisbino @danvb112 fyi

**Pull request closed without merging**
