### PR TITLE
LPS-74571 

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-74571
https://github.com/brianchandotcom/liferay-portal/pull/51843#issuecomment-333678287

/cc @Robert-Frampton @jbalsas

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:reopen

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
ci:reopen

**Comment by vicnate5** [comment]
`lpkg-override-jdk8` test is also failing at head. Not related to this pull

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
Looks good from a testing standpoint. No failures related to this pull.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0ba7859279...232ea8d89d

**Pull request closed without merging**
