### PR TITLE
LRCI-3781 Update how data is pulled from spring & remove job position

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://liferay.atlassian.net/browse/LRCI-3781

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:reopen

**Comment by michaelhashimoto** [comment]
I added changes based off of this comment:
https://github.com/brianchandotcom/liferay-portal/pull/140486#issuecomment-1711899127

I only ran SF & compile locally:
https://github.com/pyoo47/liferay-portal/pull/2777#issuecomment-1711948710

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/46629a5cf6...e7dfd14b12

**Comment by brianchandotcom** [comment]
@michaelhashimoto see e7dfd14b126b379741e1ffab5ffa61be643b31d3

**Pull request closed without merging**
