### PR TITLE
LPS-63834 Coalesce the indexer requests in indexer request buffer for better search engine performance

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-63834](https://issues.liferay.com/browse/LPS-63834).<br><br>/cc @mhan810 @jorgeferrer @pei-jung @arbetts

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:retest

**Comment by mhan810** [comment]
@drewbrokke ack please do not make the field _FORCE_SYNC in cc1b88f static final.  We need that value to be different for each instance of the IndexerRequest.  This will cause a different bug

**Comment by drewbrokke** [comment]
@mhan810 just updated the branch. See d66b905. Thanks for catching that.

**Comment by mhan810** [comment]
Looks good :)

**Comment by brianchandotcom** [comment]
Merged. THx.

**Pull request closed without merging**
