### PR TITLE
Lps 55690

### PR DESCRIPTION
**Pull request by shuyangzhou**
@hhuijser, please see https://github.com/brianchandotcom/liferay-portal/commit/14f0090a93ad168b54156a07b54207f38554a7d7, we should SF this. Basically preventing people from using org.testng.Assert completely, we should always use org.junit.Assert

@mhan810, I had to exclude org.apache.xmlbeans.\* for portal-scripting-javascript, as it is failing to be resolved. See https://github.com/brianchandotcom/liferay-portal/commit/6c36a8f6f6d4423f345f7d47801457128623bcd8

@brianchandotcom, about https://github.com/brianchandotcom/liferay-portal/commit/63e756b2cadecfa520be71a301e957b4a6a19b81, test class name has to match the test being tested. That's how CodeCoverageAssertor automatically looking up which class to assert coverage. The DefaultDynamicDataSourceAdviceTest was failing because of can not find "DefaultDynamicDataSourceAdvice"

And also, I am not sure what has changed in SDK build script recently, you might (a good chance) to see the CI ant build process run OOM on perm space. Since I will eventually get to the sdk build script optimization (after finishing the portal side, hopefully some time next week), can we simply bump up the CI ANT_OPTS for now to do 512MB for perm, 2048MB for Xmx, currently it is "-Xmx1024m -XX:MaxPermSize=384m". Otherwise, CI will get tons of random OOM errors when people start to send pulls.

### CODE REVIEW

**Comment by mhan810** [comment]
Hey Shuyang, the JavaScript module fix was in an earlier pull

Sent from my mobile device.

**Comment by shuyangzhou** [comment]
Ah, OK, I did not see that pull :)

**Comment by mhan810** [comment]
Hehe same for the CodeCoverage one ;)

Sent from my mobile device.

**Comment by brianchandotcom** [comment]
@shuyangzhou should I pull this in ? It breaks build?

**Comment by shuyangzhou** [comment]
Both this build and https://github.com/brianchandotcom/liferay-portal/pull/26567#issuecomment-102883099 are caused by the ant process OOM. We need to bump up the ant heap size on CI servers. Otherwise we will have a lot these kind of random errors.

**Comment by shuyangzhou** [comment]
@kiyoshilee should have the perm space bumped up to 512mb, let's try again. We have enabled heap dump on oom for ant, if it still happens with 512mb, we might have a leak somewhere. Then I will need dig into it right away.

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ugh, ci retest does not seem working on closed pull, will resend a new one.

**Comment by shuyangzhou** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/26591

**Pull request closed without merging**
