### PR TITLE
LPS-100223 Make sure namespace is initialized before using it

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
/CC @leoadb There's a commit modifying `DataLayoutBuilderTag`. I assumed it is OK, but just wanted to notify you so that you can make sure I don't break anything :-)

**Comment by leoadb** [comment]
@izaera It seems ok to me. Thanks to let me know.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/104d2daf12...87bfb6376c

**Comment by brianchandotcom** [comment]
@izaera see c9f38516de116dca72fb87aaae90a8bcb870b88b and d9265e189ecc2198bf44a1cc18c67d3571c0c794

I auto SF'd in 87bfb6376c1843b7315611cd936d3a406b607ada

**Pull request closed without merging**
