### PR TITLE
LPS-100197 SF

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by brianchandotcom** [comment]
This is strange.. I"lll try it locally.

**Comment by brianchandotcom** [comment]
@marcoscv-work weird rebase error. please resend.

**Comment by marcoscv-work** [comment]
Resend here:
https://github.com/brianchandotcom/liferay-portal/pull/77776

**Pull request closed without merging**
