### PR TITLE
LPS-108884

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
ci:test:sf

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1a8cd34661...0b0586089d

**Comment by brianchandotcom** [comment]
Very nice. Thank you @hhuijser 

Can you backpor LPS-108884 to 7.2.x, 7.1.x, and 7.0.x without breaking changes? Thx!

**Pull request closed without merging**
