### PR TITLE
master-qa-19152

### PR DESCRIPTION
**Pull request by michaelhashimoto**
http://issues.liferay.com/browse/LRQA-19152

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9c421c79d1...76290824bc

**Comment by lawrence-lee** [comment]
@evannagayama Can you please look into this Poshi Test Failure? I've seen this test fail a few times now.

**Comment by evannagayama** [comment]
@lawrence-lee  and @sharonchoi,

bookmarks is actually part of collab now. thanks

**Comment by sharonchoi** [comment]
@evannagayama @lawrence-lee https://issues.liferay.com/browse/LRQA-19306 Investigating now.

**Pull request closed without merging**
