### PR TITLE
LRQA-30298 | master

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-30298

See 7.0 pull here: https://github.com/brianchandotcom/liferay-portal/pull/46898

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:retest

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ec460ad1a3...44db4c4c1c

**Pull request closed without merging**
