### PR TITLE
Shard Tool: basic support

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by migue** [comment]
ci:retest

**Comment by migue** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@migue this pull is good but I didn't get a chance to review it today.

**Comment by mdelapenya** [comment]
Hi @brianchandotcom, anything that we can do for this pull?

Thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6e8c30274b...804d17c4c7

**Comment by brianchandotcom** [comment]
@mdelapenya please see my changes in upstream (lots of them)

Also, we're duplicating some logic between this and our UpgradeTable where we also export things to a file. See UpgradeTable#getTempFileName

our ConvertProcess logic also has similar logic where it uses UpgradeTable to export stuff to a file. You should check out that logic to at least make sure they're consistent. Thx @migue @mdelapenya

**Pull request closed without merging**
