### PR TITLE
LPS-159991 | master

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
Forwarded from https://github.com/liferay-lima/liferay-portal/pull/3416

**Comment by adolfopa** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/900be1f03c...0bf645a809

**Comment by brianchandotcom** [comment]
@adolfopa @quanhuynhces I had to revert this because it caused a circular dependency

See https://test-1-30.liferay.com/job/test-portal-testsuite-upstream-downstream(master)/65858/console

```testScanXMLLog(com.liferay.portal.log.assertor.PortalLogAssertorTest):	FAILED
    [junit] 
    [junit] Portal log assert failure, see above log for more information: 
    [junit] bundle com.liferay.contacts.web:5.0.36 (955)[com.liferay.contacts.web.internal.portlet.MembersPortlet(9032)] : findField: Suitable but non-accessible field _userNotificationEventLocalService in class com.liferay.contacts.web.internal.portlet.ContactsCenterPortlet, subclass of component class com.liferay.contacts.web.internal.portlet.MembersPortlet
    [junit] junit.framework.AssertionFailedError: 
    [junit] bundle com.liferay.contacts.web:5.0.36 (955)[com.liferay.contacts.web.internal.portlet.MembersPortlet(9032)] : findField: Suitable but non-accessible field _userNotificationEventLocalService in class com.liferay.contacts.web.internal.portlet.ContactsCenterPortlet, subclass of component class com.liferay.contacts.web.internal.portlet.MembersPortlet
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest.scanXMLLogFile(PortalLogAssertorTest.java:171)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:98)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:88)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2670)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2742)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXMLLog(PortalLogAssertorTest.java:86)
    [junit] 
    [junit] ```

**Pull request closed without merging**
