### PR TITLE
LPS-125034 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-125034

This is only for master.

@p2kmgcl
@ruben-pulido

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure task is unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/6569
✔️ ci:test:stable - 11 out of 11 jobs passed
❌ ci:test:relevant - 24 out of 29 jobs passed in 1 hour 32 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/02db61a9b3...f2fb020e2c

**Comment by brianchandotcom** [comment]
@ruben-pulido @p2kmgcl can you guys send me a follow up PR and remove the old / unused

FragmentEntryLocalServiceImpl#addFragmentEntry and 
FragmentEntryServiceImpl#addFragmentEntry

Breaking change is OK.

**Pull request closed without merging**
