### PR TITLE
Get upgrade optimized connection

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@michaelhashimoto hashi?

**Comment by brianchandotcom** [comment]
@shuyangzhou Closing this.. I think you didn't mean to send it to me.

**Comment by michaelhashimoto** [comment]
@brianchandotcom - I think it's a rebase error. :+1:

**Pull request closed without merging**
