### PR TITLE
LRQA-50259 | master

### PR DESCRIPTION
**Pull request by vicnate5**
Adding basic upgrades testing to 'stable' job

Backport https://github.com/brianchandotcom/liferay-portal-ee/pull/25601

### CODE REVIEW

**Comment by vicnate5** [comment]
@pyoo47

**Comment by michaelhashimoto** [comment]
ci:test:stable

**Comment by vicnate5** [comment]
@michaelhashimoto Been testing here: https://github.com/vicnate5/liferay-portal/pull/1234

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b7baf62adc...fc762dc9e1

**Pull request closed without merging**
