### PR TITLE
LPS-81944 Validate upgrade package using the major and minor versions

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test

**Comment by achaparro** [comment]
ci:close

**Comment by achaparro** [comment]
ci:reopen

**Comment by achaparro** [comment]
errors unrelated

**Comment by jpince** [comment]
@achaparro this won't reopen because you already resent https://github.com/brianchandotcom/liferay-portal/pull/59754

**Comment by achaparro** [comment]
Yeah, I realized about that after trying to reopen it.

Thanks @jpince

**Pull request closed without merging**
