### PR TITLE
LPS-127668 LPS-127672 Layout reports details backend

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
Hi @brianchandotcom,

I just fixed the titles and the code as requested in https://github.com/brianchandotcom/liferay-portal/pull/101691#issuecomment-840001286.

Thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d7845cde2d...192fe6227d

**Comment by brianchandotcom** [comment]
@4lejandrito I merged this with minor changes in 7c21c7e2 and d44574b5

But can you fix 

```
		Assert.assertEquals(
			"{\"total\":\"100\",\"details\":[{\"total\":\"100\"," +
				"\"key\":\"title\"}],\"key\":\"seo\"}",
			layoutReportsIssue.toString());
```

There's no guarantee the order will be the way you have it. Can you make the toString have a predictable (and pretty format), then you can ensure the test will always work.

**Comment by 4lejandrito** [comment]
Hi @brianchandotcom,

See https://github.com/liferay-tango/liferay-portal/pull/1176.

**Pull request closed without merging**
