### PR TITLE
LPS-62396

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
ci:retest

**Comment by mhan810** [comment]
@brianchandotcom the PortletRequestDispatcherImplTest failure should be unrelated.  The prior tests have passed with only SF failures

**Comment by juangon** [comment]
yeah @mhan810 I've got the fix pushing in few minutes

**Comment by juangon** [comment]
This should fix it: https://github.com/juliocamarero/liferay-portal/pull/3992

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cc3b3be811...11d7cc649b

**Pull request closed without merging**
