### PR TITLE
LPS-98198

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@petershin, is this okay? https://github.com/brianchandotcom/liferay-portal/pull/75668/commits/b7f6b8a41038e3a266a8992024d123e1dcaf046f

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9faa5bc545...2b55a617d0

**Comment by brianchandotcom** [comment]
@petershin I merged the change from @hhuijser but won't publish sdk/ant-bnd until you give me the thumbs up (I wonder if we can just remove all exports for ant-bnd)

**Comment by brianchandotcom** [comment]
@petershin see my touch up in 4ab7b5b5f8657dd30f83435c060d39a2d2d2c158

**Pull request closed without merging**
