### PR TITLE
LPS-59287 Use services instead of SQL in Journal Service Upgrades

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
@ZoltanTakacs can you please backport this? thanks!

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
@sergiogonzalez I have changed a method in the AddDefaultDocumentLibraryStructuresAction to reuse that logic in our upgrades. Can you have a look?

thanks!

**Comment by brianchandotcom** [comment]
ci:retest (didn't seem to compile)

**Comment by brianchandotcom** [comment]
@juliocamarero I don't think this compiles... please resend. Thx.

**Pull request closed without merging**
