### PR TITLE
LPS-66213 system.packages.extra.mf

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by jpince** [comment]
@brianchandotcom one functional test failure due to a build error/fluke, should be safe to merge.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4eff0b02bd...15397168fe

**Comment by brianchandotcom** [comment]
@sergiogonzalez @adolfopa I cleaned up this pull quite a bit. Please see e0105b8dc26e32df9f6b205cf3c0bf1e3e4a84f2

@adolfopa can you review/retest?

Thx!

**Comment by adolfopa** [comment]
@brianchandotcom everything seems fine, I've tested it with an empty database and upgrading from a 7.0.0 GA1.

**Pull request closed without merging**
