### PR TITLE
LPS-71773 Facets: selection of an item should not hide all other possible selections

### PR DESCRIPTION
**Pull request by arboliveira**
@mhan810 Sending this before the new Facet Portlets. This allows for the new checkboxes with multiple selection of facet values. Also helps with choosing scope "this site" vs "all sites" from the search bar.

https://issues.liferay.com/browse/LPS-71773

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci: reopen

The failures above are unrelated to this pull. I'm following up with the Frontend team about the PortalLogAssertorTest failure.

**Comment by xbrianlee** [comment]
ci:reopen

The failures above are unrelated to this pull. I'm following up with the Frontend team about the PortalLogAssertorTest failure.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1176dc13cc...180060a92c

**Comment by brianchandotcom** [comment]
@arboliveira see 180060a92c825499351b1f0dc3daaf9d62ed690e 

thx.

**Pull request closed without merging**
