### PR TITLE
[Impedibug] LPS-171426 Already relate object entry, when it creation screen came from a Relationship Tab

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-171426

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a4f79e8683...7e3d90b809

**Comment by brianchandotcom** [comment]
@p-albuquerque I found your logic for _getRelationshipValueMap very very strange. I completely  removed it/simplified it. Please review my logic.

See my many changes in the log https://github.com/brianchandotcom/liferay-portal/commits/7e3d90b8

**Comment by brianchandotcom** [comment]
@p-albuquerque Ok, I just saw its usage in form.jsp and readded it in da2f7440e540c9febdfbc4dd783a8a76ef8439e2

That method is very ugly. Please revert that and redo it. We should never rely on a "toString" of a Map. The toString impls are subject to change.

Please send a follow up PR. Thx @p-albuquerque

**Pull request closed without merging**
