### PR TITLE
LPS-85848 Moving back to sharing-api

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @brianchandotcom,

@sergiogonzalez moved the code to the new web-api module based on [portal-search-web-api](https://github.com/liferay/liferay-portal/tree/master/modules/apps/portal-search/portal-search-web-api). I have moved it back to sharing-api anyway.

Thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d4ccd5bbe2...743dc2c689

**Comment by brianchandotcom** [comment]
Interesting.. I didn't see modules/apps/portal-search/portal-search-web-api/bnd.bnd earlier.

Go ahead and send me a pull for sharing.web.api in another pull? I'd like to show that to @shuyangzhou and see what he thinks.

Thx

**Comment by 4lejandrito** [comment]
Hi @brianchandotcom,

I was out of the office today. Will get this done tomorrow morning.

Thanks!

**Comment by 4lejandrito** [comment]
There you go https://github.com/brianchandotcom/liferay-portal/pull/63770.

**Pull request closed without merging**
