### PR TITLE
LPS-161704 Fix query including a parenthesis when OR is executed

### PR DESCRIPTION
**Pull request by 4lejandrito**
This PR contains the code to fix the query that gets the object relationship based on the object id and the relationship name

**Before the PR**:

The query returned randomly one of the relationships of the object

```
select * from ObjectRelationship
where ObjectRelationship.reverse = ?
and ObjectRelationship.name = ?
and ObjectRelationship.objectDefinitionId1 = ?
or ObjectRelationship.objectDefinitionId2 = ?
```

**After the PR**:

The query returns the desired relationship

```
select * from ObjectRelationship
where ObjectRelationship.reverse = ?
and ObjectRelationship.name = ?
and (ObjectRelationship.objectDefinitionId1 = ? or ObjectRelationship.objectDefinitionId2 = ?)
```

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b362c6808d...ec1ec313ff

**Comment by brianchandotcom** [comment]
@4lejandrito @ccorreagg see 784640b22821052a47e8da3c4aa2cd5c78aa34c8

**Pull request closed without merging**
