### PR TITLE
LPS-79694 Cancel AlloyEditor enter keypress for text editables

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by jpince** [comment]
ci:close @brianchiu @anthony-chu please verify test failures and reopen if this is good to go

**Comment by ealonso** [comment]
@jpince The same for those

**Comment by jkappler** [comment]
ci:reopen

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@jpince, again, the issues are of the fix that was merged.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a18adef171...8b895e0415

**Pull request closed without merging**
