### PR TITLE
LPS-110068 When asking explicitly for depot groups, never show the breadcrumb

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@inacionery please fix https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/363268/AXIS_VARIABLE=0,label_exp=!master/testReport/junit/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_PortalSmokeUpgrade_ViewPortalSmokeArchive621021_/

```
LIFERAY_ERROR: Unable to initialize My Account panel permissions for portlet com_liferay_portal_workflow_web_internal_portlet_UserWorkflowPortlet in company 10155


	at com.liferay.poshi.runner.selenium.LiferaySeleniumHelper.assertNoPoshiWarnings(LiferaySeleniumHelper.java:298)
	at com.liferay.poshi.runner.PoshiRunner.test(PoshiRunner.java:182)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	
```

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f6daa00cf7...2731cb93f2

**Comment by brianchandotcom** [comment]
@hhuijser can you talk to @wincent about enforcing 2731cb93f23919bffa7b6dd9a8d250e0a5cb924b

Since you already have the algorithm for Java.

In short, if you declare a var, add a line break before using it. This shows order of requirements better.

**Comment by wincent** [comment]
I created https://github.com/liferay/eslint-config-liferay/issues/160 to enforce this. If there are any nuances to this @hhuijser can you please comment there? I think should be possible to enforce using ESLint in way that conflicts with neither Prettier nor other ESLint rules.

**Comment by inacionery** [comment]
Hey @brianchandotcom, this error is a race condition, maybe @shuyangzhou can help us with that?

**Comment by hhuijser** [comment]
@wincent the logic in SF is all sitting here: https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/java/com/liferay/source/formatter/checkstyle/checks/MissingEmptyLineCheck.java

It's not super straight forward reading that, since it's a checkstyle check

**Comment by wincent** [comment]
Thanks @hhuijser. I took a quick look at it and have made a note of it so that I can refer to it — I'll let you know if I have any questions.

**Pull request closed without merging**
