### PR TITLE
LPS-69661 Use portal service reference instead of PortalUtil, includes SF to prevent new usages

### PR DESCRIPTION
**Pull request by tomwang2011**
CC @hhuijser

Hi Brian, this is the resend of https://github.com/brianchandotcom/liferay-portal/pull/48323 after fixing the integration test, thanks!

### CODE REVIEW

**Comment by tomwang2011** [comment]
ci:reopen the failures should not be caused by this pull, will retest, thanks!

**Comment by tomwang2011** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5e839dc175...a412a30b07

**Comment by brianchandotcom** [comment]
@tomwang2011 I cherry picked anything that I could. Can you verify ee-7.0.x? Thx.

**Comment by tomwang2011** [comment]
Hi @brianchandotcom, I think there are a few commits on CE side that needs to be backported to prevent SF errors thrown by this change, I will backport those soon, thanks!

**Pull request closed without merging**
