### PR TITLE
LPS-47199 include draft articles from the owner when viewing the web content administration --> please read description (aware of broken tests)

### PR DESCRIPTION
**Pull request by juliocamarero**
@brianchandotcom Could you please have a look even when the tests are broken? We don't want to spend time fixing them if this is not the approach you want us to follow.

@brianchandotcom let us know if you like this pattern so that it can be applied to the other apps. Otherwise, let us know other pattern to follow and @moltam89 will take care of it.

thanks!

cc @arbetts

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@juliocamarero I didn't get a chance to look at this til late, I'll find @arbetts tomorrow to go over this with him. Thx.

**Comment by juliocamarero** [comment]
Thanks Brian!

@arbetts please post here all the conclusions from your conversation with Brian so that @moltam89 can work on it.

thank!

**Comment by arbetts** [comment]
@brianchandotcom i'm in the office now and can go over this whenever you have time

@juliocamarero @moltam89 I will post the conclusions here

**Comment by arbetts** [comment]
@juliocamarero @moltam89

just discussed this with @brianchandotcom 

conclusion:
1) I will fix this issue for Journal and Wiki by using the customSQLUtil so that it can be applied elsewhere.
2) if there are other assets that need this fix then let me know and i will apply it to those as well.

**Comment by arbetts** [comment]
@juliocamarero @moltam89 @brianchandotcom 

After looking at the pull again and @moltam89 comments on his pull to @juliocamarero It looks like we need to just apply this to wiki and then we can move forward.

in my original pull and the discussion that followed I did not realize that Eudaldo had already added it to the CustomSQLUtil (my mistake).

@juliocamarero are there other assets that need this fix besides journal and wiki?

**Comment by juliocamarero** [comment]
I tend to think DL and Bookmarks could also be affected by this. (Not sure though since you can't create draft files in DL). @sergiogonzalez, can you let us know what you think? (ping me if you are not sure what this is about)

**Comment by arbetts** [comment]
@juliocamarero 

new pull that applies fix to wiki as well as journal

https://github.com/juliocamarero/liferay-portal/pull/3475

**Pull request closed without merging**
