### PR TITLE
LPS-51814 Ant setup-eclipse

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2e9fcbfb61...23aecb9cfa

**Comment by brianchandotcom** [comment]
@marcellustavares Please see my minor changes. Thx.

**Comment by marcellustavares** [comment]
Thanks @brianchandotcom

**Pull request closed without merging**
