### PR TITLE
LPS-73734 Add the operation to get Latest Workflow Definitions by Company

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:stop

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/78abc42d86...7c0bc7f613

**Comment by brianchandotcom** [comment]
@inacionery please see my changes in upstream. Thx.

**Comment by inacionery** [comment]
Thx!

**Pull request closed without merging**
