### PR TITLE
LPS-67399 Add test for search

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pei-jung can you resend using dynamic query instead? I'm not a big fan of the naming of the finders and the new methods. See my comments in 

https://github.com/brianchandotcom/liferay-portal/pull/42851

Applies to this pull too. Thx.

**Comment by pei-jung** [comment]
Hey @brianchandotcom,

I couldn't find a way to create a UNION query with dynamic query. Looks like for dynamic query, I have to query organizations and users separately and then merge them manually. Can you give me an example on how this is done with dynamic query?

**Comment by JorgeFerrer** [comment]
@brianchandotcom are you sure you want to use Dynamic Queries? 
I also dislike the manipulation of SQL but that's the way this same type of query is implemented in other places such as in Document Library's method to return folders and documents.

**Comment by JorgeFerrer** [comment]
@pei-jung What is the status of these code changes?

**Comment by pei-jung** [comment]
@JorgeFerrer: still waiting on Brian. I'll follow up with him.

**Comment by pei-jung** [comment]
Hi @brianchandotcom,

When you get a chance, can we go over this together?

**Pull request closed without merging**
