### PR TITLE
LPS-76857 Create display context for user

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-76857](https://issues.liferay.com/browse/LPS-76857).<br><br>/cc @pei-jung

### CODE REVIEW

**Comment by drewbrokke** [comment]
Hey @brianchandotcom, this is a technical task that sets us up to take on a large set of tickets going forward.

**Comment by drewbrokke** [comment]
ci:test

**Comment by drewbrokke** [comment]
@alee8888 these failures look unrelated, but can you verify?

**Comment by drewbrokke** [comment]
ci:retest

**Comment by pei-jung** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0b7cd6c404...8d5f5a1383

**Comment by brianchandotcom** [comment]
@drewbrokke @pei-jung see 8d5f5a13834649f7468120dff5770b918d04de56 thx

**Pull request closed without merging**
