### PR TITLE
LPS-74544

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Pull for 7.0.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/18964

@petershin

**Comment by hhuijser** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Wow @hhuijser 

@shuyangzhou look at what Hugo added!

**Comment by shuyangzhou** [comment]
Nice! Thanks @hhuijser !

**Comment by hhuijser** [comment]
@brianchandotcom @shuyangzhou, just a heads up, SF is not smart enough to figure out the capacity when there are any `for` or `while` loops involved. So those cases are skipped.

**Comment by shuyangzhou** [comment]
@hhuijser Yeah, I figured, no way to get those right. This can still catch some really stupid mistakes.

**Pull request closed without merging**
