### PR TITLE
LPS-58975 Fix translation issues when displayed in Asset Publisher

### PR DESCRIPTION
**Pull request by adolfopa**
Hi @brianchandotcom,

I've talked with @juliocamarero about this and he prefers my approach, so I've reverted his commits and rebased my pull on top of that.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8766df0c9c...3374cbc9a3

**Comment by brianchandotcom** [comment]
@hhuijser can you sort taglib defineObject calls? See 28bf7b6839a387634280ef4113eba4a17f85fbf4 I'd like to do all the liferay ones and then the portlet one going forward.

@adolfopa nice job.

1.) Can you extend liferay-frontend:defineObjects to also implicity set

```
WindowState windowState = liferayPortletRequest.getWindowState();

PortletURL currentURLObj = PortletURLUtil.getCurrent(liferayPortletRequest, liferayPortletResponse);

String currentURL = currentURLObj.toString();
```

2.) Also, you do this a lot:

```
			ResourceBundle resourceBundle =
				TagResourceBundleUtil.getResourceBundle(pageContext);
```
Most of our taglibs already extend one of our base tag classes (the ones that do not, we could add it), and then we can make "pageContextResourceBundle" an implicit var and make it part of our taglib lifecycle. This may be overengineering.. but we may have other implicit things to add later. I'll leave this one up to you.

3.) Also, will you be sending more cases where we can remove setting the resource bundle manually, or did you get them all?

Thx.

**Comment by adolfopa** [comment]
@brianchandotcom I'll take care of (1) and (2). About (3), there are a couple of occurrences that I didn't replace here; I'll send those changes along other fixes for the aui: tags.

Thanks!

**Pull request closed without merging**
