### PR TITLE
Lpd 26725

### PR DESCRIPTION
**Pull request by shuyangzhou**
@tinatian @vicnate5 please backport for LXC, thanks!

@victorhcunha @slnn, please run check for login/DL/MB, pay attention to DB usage, ES usage and overall session count. sql log profile is needed for login test case, thanks!

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@victorhcunha make sure the baseline you use includes change from https://github.com/brianchandotcom/liferay-portal/pull/150594

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/270c2a8b33...9e69bcc2d9

**Comment by brianchandotcom** [comment]
@shuyangzhou see tiny changes in ff1bdad6 and 9e69bcc2

**Comment by slnn** [comment]
Hi @victorhcunha
Please finish tests for Login and DL firstly then setup up tests for MB.
When you setup tests for MB, please follow this guide:

**Comment by slnn** [comment]
Hi @victorhcunha

Please finish the tests for Login and DL firstly then setup tests for MB.

Here are steps for the setup of MB:

If we do not have an available db for test case MB, please generate db firstly then start testing:

1. Update portal master
2. Update benchmark master
3. Apply the benchmark-ext.properties for MB, the configuration file you can try this one: https://gist.github.com/slnn/c239172f6b04713d4785c3dce948a1b8
4. Run `ant all-database` under benchmark project to build db for MB
5. Run` ant reload-warmup-database all-portal start-visualvm all-grinder all-sample stop -Dskip.build.portal=true`  to start a test for MB;  Note: here we can skip the build for portal as portal has been built on step 4

If we  have an available db for test case MB, just start a test:

1. Update portal master
2. Update benchmark master
3. Apply the benchmark-ext.properties for MB, the configuration file you can try this one:https://gist.github.com/slnn/c239172f6b04713d4785c3dce948a1b8
4. Run `ant reload-warmup-database all-portal start-visualvm all-grinder all-sample stop` to start a test for MB; Please make sure do not skip building portal here for MB, as the build of benchmark will apply necessary changes on portal for testing before calling the ant all of portal

Lily

**Comment by slnn** [comment]
Hi @victorhcunha

Please increase the pressure of Portal to reach its limits, here are the steps on Login:

1. Switch to the baseline version that you used for portal
2. Apply the benchmark-ext.properties that you used for Login to benchmark project
3. From the baseline test result zip (log-LPD-26597-pr-150594-login-2024-05-23-13-13-27-d8d4b6e6fa491280e5c2a74faf9650f63e0431d1.zip) you uploaded, we can get these:
The initial pressure is 5000, please see the value of `grinder.agent.new.thread.model.init.permits` in benchmark-ext.properties, as we enable the adjustment automation of Grinder, please see the value of `grinder.agent.new.thread.model.auto.adjust.enabled` then the final instant pressure (session count) is 8423, please see the last sample in grinder.log, the test step login's meantime is also good, however, the CPU usage of portal server is about 86% ~ 87% during the tests, so please increase the value of `grinder.agent.new.thread.model.init.permits` then run a runtime performance test, check the meantime and the CPU usage of portal server, you need to find the threshold value for `grinder.agent.new.thread.model.init.permits` which means that you can not increase the pressure otherwise you will see a worse meantime
4. Use the value that got in step3 to rerun tests on baseline and pr


Please also do same thing on test case DL and MB.

By the way, you do not need to rerun SQL logs for Login


Thanks
Lily

**Comment by victorhcunha** [comment]
Hi @shuyangzhou !
Here are the new results for login and DL test cases:

**Login**
Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | DB CPU Usage (%) | Portal CPU Usage (%) | ES CPU Usage (%)
-- | -- | -- | -- | -- | -- | -- | --
Baseline | 441c0d6 | 8228 | - | 281 | 9,9,9 | 87,88,85 | 7,8,8
PR | - | 8749 | 6.332036947 | 277 | 5,6,5 | 88,87,87 | 4,5,4


**DocumentLibrary**
Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | Mean Time of Add DL File | DB CPU Usage (%) | Portal CPU Usage (%) | ES CPU Usage (%)
-- | -- | -- | -- | -- | -- | -- | -- | --
Baseline | 441c0d6 | 7467 | - | 255 | 399 | 8,8,8 | 86,89,85 | 4,7,4
PR | - | 7692 | 3.013258337 | 259 | 435 | 8,8,8 | 85,86,85 | 2,3,2

More details you can see in our [spreadsheet](https://docs.google.com/spreadsheets/d/1M6VK8GtY9kkv1EwhGW7vwrEENSzyT7zKz-wOh11ZHBo/edit#gid=1688906183)
About the new configs for  increased pressure you can see [here](https://docs.google.com/spreadsheets/d/1yQMPJPJ-9zFWkpqCs1QnP1C4qoi5pIrxhPHe9ZwSDNo/edit#gid=0) 

The MB test case is still running.

**Comment by victorhcunha** [comment]
Hi @shuyangzhou 
Here are results for MB

Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | Mean Time of Add MB Thread | DB CPU Usage (%) | Portal CPU Usage (%) | ES CPU Usage (%)
-- | -- | -- | -- | -- | -- | -- | -- | --
Baseline | 441c0d6 | 6812 | - | 3240 | 2470 | 40,48,58 | 95,87,76 | 4,6,4
PR | - | 6888 | 1.115678215 | 2850 | 2650 | 37,64,69 | 89,81,68 | 3,3,4

More details you can see in the same [spreadsheet](https://docs.google.com/spreadsheets/d/1M6VK8GtY9kkv1EwhGW7vwrEENSzyT7zKz-wOh11ZHBo/edit#gid=1688906183)

We are increasing the pressure for MB test case, about it, you can see in [Increase Pressure - MB](https://docs.google.com/spreadsheets/d/1EyfQ2J0MN5lr5pxCWwv5DeInGsW40X3dd5kk4n-U9GA/edit#gid=0)

**Pull request closed without merging**
