### PR TITLE
Lps 201985

### PR DESCRIPTION
**Pull request by shuyangzhou**
@111Anna datapoints before/after, thanks!

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c14b4a864e...8db8f41881

**Comment by 111Anna** [comment]
> @111Anna the data looks a bit off, is the heap size one from automated capturing?

yeah, I tested the PR with automated today.

**Comment by shuyangzhou** [comment]
See the slack thread, is the automation having the 5s delay? Is so it must be removed.

**Comment by 111Anna** [comment]
@shuyangzhou   I retest the  **heap dump** with automation and no any delay .

Here are test results:

**CE:**
Portal Version |GitId | Average Startup (ms) | % | Average Shutdown (ms) | % | Open File |Thread Create |Open Prepared Statement |Open Query|Open SQL|Open service tracker|Open bundle tracker |ACTIVE | SATISFIED|Objects | shallow size (MB) |retained size (MB)
-- | -- | -- | -- | -- | -- | -- | -- | -- | --|--|--|--|--|--|--|--|--
Before-LPS-201985 | c14b4a86 |12299.6| - | 2395.6 | - | 1408 | 76 | 64 | 96|771|5446|33| 2828|8314| 7176304 |471 |471
LPS-201985|8db8f41| 12267.3 | 0.26% | 2401.6 | 0.25% |  1408| 76| 64 |96| 771|5447|33|2827|8322| 7176812 |397|397

**DXP:**
Portal Version | GitId | Average Startup (ms) | % | Average Shutdown (ms) | % | Open File |Thread Create |Open Prepared Statement |Open Query|Open SQL|Open service tracker|Open bundle tracker |ACTIVE | SATISFIED|Objects | shallow size (MB) |retained size (MB)
-- | -- | -- | -- | -- | -- | -- | -- | -- | --|--|--|--|--|--|--|--|--
Before-LPS-201985 | c14b4a86 |12749.6| - | 2882.3| - | 1529 | 78 | 64 | 96|838|5902|33|3057 |8931| 7592914 |489|489
LPS-201985 | 8db8f41 | 12675.3 | 0.58% |  2819| 0.52% | 1529 |77 | 64 |96|839 |5900|33|3056|8932|7497007  |404|404

**Pull request closed without merging**
