### PR TITLE
LPS-95067

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
@Preston-Crary, will you fix those two violations in `master-private`?

```
[java] 1: ServiceTrackerFactory.open(Class clazz) is deprecated since it leaks ServiceTrackers, see LPS-95067: ./modules/private/apps/saml/saml-api/src/main/java/com/liferay/saml/runtime/configuration/SamlProviderConfigurationHelperUtil.java 69 (SourceCheck:JavaServiceTrackerFactoryCheck)
[java] 2: ServiceTrackerFactory.open(Class clazz) is deprecated since it leaks ServiceTrackers, see LPS-95067: ./modules/private/apps/saml/saml-web/src/main/java/com/liferay/saml/web/internal/util/NameIdTypeValuesUtilHelper.java 32 (SourceCheck:JavaServiceTrackerFactoryCheck)
```

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by Preston-Crary** [comment]
@hhuijser see https://github.com/shuyangzhou/liferay-portal-ee/pull/470

**Pull request closed without merging**
