### PR TITLE
LPS-91420

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@shuyangzhou, I assumed the order of the annotations matters for this one: https://github.com/brianchandotcom/liferay-portal/pull/70000/commits/6645e21f19829e9a9ab990053a3a8ef1512085aa

**Comment by hhuijser** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by shuyangzhou** [comment]
@hhuijser between the Method and Mix, yes, order matters. But the Override is not. You can just run the test, as long as it is not broken, any sort will be fine.

**Comment by hhuijser** [comment]
Thanks @shuyangzhou, I can remove that comment then, just wanted to double check with you

**Pull request closed without merging**
