### PR TITLE
master-qa-32665

### PR DESCRIPTION
**Pull request by kiyoshilee**
https://issues.liferay.com/browse/LRQA-32665

### CODE REVIEW

**Comment by kiyoshilee** [comment]
@brianchandotcom can you backport this to 7.0.x? I sent a pull to liferay-portal-ee/7.0.x but that autoclosed (see https://github.com/brianchandotcom/liferay-portal-ee/pull/18090). I understand Sam is changing the validation scripts though.

**Comment by kiyoshilee** [comment]
ci:retest

**Comment by kiyoshilee** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/be8a90ab9e...da4df6975c

**Pull request closed without merging**
