### PR TITLE
Database support: upgrade to 7.0.3

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
@migue @brianchandotcom 

Do you have any update about this LPS-67652?

We need to commit this to master in order to backport related LPS-66133 and LPS-67652

**Comment by jorgediaz-lr** [comment]
@brianchandotcom 

We need to commit this pull in master in order to be able to backport LPS-66599 and LPS-66133 as they have upgrade process (https://github.com/brianchandotcom/liferay-portal-ee/pull/14090)

@migue  @achaparro

**Comment by brianchandotcom** [comment]
Thx @jorgediaz-lr 

I forgot about this pull. Thank you for sending this!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4fe735ff84...5dd36142d5

**Pull request closed without merging**
