### PR TITLE
LPS-72830

### PR DESCRIPTION
**Pull request by Ithildir**
@juliocamarero, you can replace the Gradle code for this task in your subrepos with something like this in `build-ext.gradle`:

```gradle
import com.liferay.gradle.plugins.defaults.tasks.CheckOSGiBundleStateTask

task checkOSGiBundlesStates(type: CheckOSGiBundleStateTask)
```

It will do the same thing: failing the build if at least one non-fragment bundle is not `ACTIVE`.

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@arboliveira I think that's your test :( I temporarily disabled it 03053198ebe8a6da22bc96c58be045a306d8ebea

See https://github.com/brianchandotcom/liferay-portal/pull/49271

Can you send me a pull to fix the test?

**Comment by arboliveira** [comment]
@brianchandotcom Looking into it!

**Comment by brianchandotcom** [comment]
@codyhoag fyi.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by juliocamarero** [comment]
Hey @Ithildir 

is this released yet? It still doesn't work for us... see this pull: https://github.com/liferay/com-liferay-osb-faro-site-touchpoints-private/pull/130

Thank you!!

**Pull request closed without merging**
