### PR TITLE
LPS-89547 buildLang

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test:change-tracking

**Comment by matethurzo** [comment]
the test fails seems to be CI problems

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3786553760...382befa22a

**Comment by brianchandotcom** [comment]
@matethurzo  please see  my renames in upstream. Thx.

**Pull request closed without merging**
