### PR TITLE
[TS] LPS-173082 SAML stuck in redirect loop with site virtual host

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Hi Brian. I'm forwarding this directly because the CI test failures on liferay-appsec/liferay-portal/pull/982 are unrelated.

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:reopen

**Comment by jpince** [comment]
@stian-sigvartsen thank you for your work on this!

**Comment by brianchandotcom** [comment]
@stian-sigvartsen 

git grep "extends BaseSamlPortalFilter"

Can you rename all these classes to XyzSamlPortalFilter?

This new servlet filter name "Assertion Consumer Service Filter" and the class name seem to not match the rest of the saml filters as well.

**Comment by stian-sigvartsen** [comment]
ci:reopen

**Pull request closed without merging**
