### PR TITLE
LPS-70367 Fix discussion jsps not being included from LPS-69899.

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by jbalsas** [comment]
Hey @Preston-Crary, could you please take a look and backport this to `ee-7.0.x` if needed?

Thanks!

**Comment by Preston-Crary** [comment]
@jbalsas, it's not needed. That line didn't apply to 7.0.x.

**Comment by jbalsas** [comment]
Hey @Preston-Crary, could you double check? https://issues.liferay.com/browse/LPS-70367 is marked as a regression last known to work in `FP-10`, so that should indicate that a backport is needed...

**Comment by Preston-Crary** [comment]
@jbalsas, I did double check. That line doesn't exist in ee-7.0.x, so there's nothing to backport.  That ticket was created in January so maybe that has something to do with using FP-10 as the last working version?

@anthony-chu, does https://issues.liferay.com/browse/LPS-70367 effect ee-7.0.x?

**Comment by jbalsas** [comment]
Thanks a lot @Preston-Crary!

**Comment by anthony-chu** [comment]
Hey @Preston-Crary and @jbalsas, LPS-70367 doesn't affect ee-7.0.x, as the "Subscribe to Comments" link and comment editor are present.
image

**Comment by Preston-Crary** [comment]
@anthony-chu, awesome, thanks for the sanity check!

**Pull request closed without merging**
