### PR TITLE
LPS-60321 Apply new lexicon design to site templates

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @evannagayama,

I think this pull could break some poshi test, Could you take a look into this? 

I think we could have the same problem that we have on page templates for "active" checkbox

Thanks!!!

**Comment by evannagayama** [comment]
Thanks Eudaldo, @koor4356 can you take a look at this and make test fixes? Thanks

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by koor4356** [comment]
@evannagayama , I just sent you pr for the test fixes.

https://github.com/evannagayama/liferay-portal/pull/236

**Pull request closed without merging**
