### PR TITLE
LPS-69234

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-69234.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
@brianchandotcom, not sure why poshi tests have become flaky today.. Will bring this up with QA team leads tomorrow to address this.

**Comment by brianchandotcom** [comment]
@kenjiheigel I assume these were just flaky since PGSitesdirectory#DisplayStyleOptions didn't break the first time.

**Comment by brianchandotcom** [comment]
@omarzzn3 @dustinryerson 

"Session expires in {0}" needs to be a sentence or a book title. I added a period to make it a sentence.

**Comment by brianchandotcom** [comment]
@dustinryerson is it better to say:

Session expires in X.

Or

Session will expire in X.

Please send an updated pull if you feel the latter is better.

**Comment by dustinryerson** [comment]
@brianchandotcom I used `Session expires in X` so that when the browser tab is full size (vs. a smaller size when many tabs are open) the full countdown timer will show on the tab. `Session will expire in X.` sounds good as well but I think the extra text will push the seconds section of the timer off the tab. It's a small detail but I thought users would appreciate being able to see the full timer.

**Pull request closed without merging**
