### PR TITLE
LPS-77561

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a672c90db0...58c6558a47

**Comment by brianchandotcom** [comment]
@topolik is this a security hole? ever increasing map that can kill the server's memory?

@izaera merged..

**Comment by izaera** [comment]
@topolik @brianchandotcom the map should be limited in size, but it is true that if the object being "serialized" is very big, it can lead to a DoS attack (though it would be originated by trusted code; I don't know if that makes any difference for us).

The problem here is that we need to serialize "something" to be injected in the templates. And that "something" may be anything, even an 80GB object. But, from my point of view, saying that this is a security problem is like saying that doing this inside a portlet is a security hole:

```
char[] a = new char[1000*1000*1000];
```

In the end is the responsibility of the developer not to break the portal with his developments :-).

**Comment by topolik** [comment]
@brianchandotcom Thanks for heads up.

@izaera Developers are responsible but must be watched ;) There can be "special cases" where developer are not aware they are doing something wrong like this one where we add everything from params into the template's map: https://github.com/topolik/liferay-portal/blob/a3870fc9f57d6d77e41952aa812b2f7934a95766/modules/apps/foundation/portal-portlet-bridge/portal-portlet-bridge-soy/src/main/java/com/liferay/portal/portlet/bridge/soy/SoyPortlet.java#L293-L318  

@izaera There are limits for param values, but still, can JSON serialization multiple the content size?

Other than that, if we don't cache the template, there should be no ever increasing map.

**Comment by izaera** [comment]
@topolik:

> @izaera There are limits for param values, but still, can JSON serialization multiple the content size?

The JSON serialization is used as an intermediate tool: we first serialize, then deserialize to convert everything to a map in an easy way. We tried to use BeanUtils, but it gave some problems and decided to resort to the old way of doing it.

Also, JSON memory usage should be linearly proportional to the Java objects being serialized, so it can be considered equivalent.

Said that, of course we use more memory than the initial, because we are converting a graph of java objects to a Map and we are using JSON in the middle, so we should expect to approximately multiply by 3 the intermediate memory usage. But then, the templates are not cached, so they are used once and discarded and that memory returns to pool.

Conclusion: we could make the algorithm more memory efficient but I don't see any need to do that now. In the end, any algorithm in the portal uses CPU and memory and it is (nearly) always possible to make algorithms more efficient but one has to stop somewhere :-D.

If, in the future, we see evidence of some other problem because of this we can change it. But it has been always like that and didn't seem to give any problem...

**Comment by topolik** [comment]
Thanks @izaera !

**Pull request closed without merging**
