### PR TITLE
Lps 93992

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:reopen

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Hi @jpince, could you confirm/deny the test failures relevancy to this pull?  I would greatly appreciate it.

**Comment by jpince** [comment]
@brianchiu @vicnate5 @patriciajeanperez request to take a look at the POSHI failures. Can you please take a quick look?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/75bf402bdb...f622bb96ce

**Comment by vicnate5** [comment]
No unique functional failures here.

**Pull request closed without merging**
