### PR TITLE
LPS-205268 Remove JSOUP usage from AM

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPS-205268

Remove jsoup usage to improve performance.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:reopen

**Comment by adolfopa** [comment]
Sending to you directly; the original pull failed due to a simple rebase issue.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0f9d2ca548...0517a8710a

**Comment by brianchandotcom** [comment]
@adolfopa see 938b269bb317b112f0f97eb2ed5ea80ee1cbb047

**Pull request closed without merging**
