### PR TITLE
LPS-75614 Sets group id to the url when we are selecting site roles

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:reopen

**Comment by ealonso** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5195ab5402...b0da459579

**Pull request closed without merging**
