### PR TITLE
#ping2 LPS-57672 User Statistics Web OSGI

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @izaera

**Comment by brianchandotcom** [comment]
@sergiogonzalez I rebased, no need to rebase. Thx.

**Comment by brianchandotcom** [comment]
@jkappler @sergiogonzalez none of the recent portlets you guys have migrated tie the Portlet to the Upgrade.

Can you guys fix them all? See AmazonRankingsPortlet

Then compare *Portlet.java in modules (the ones you guys did and the ones you didn't)

Can you fix them all and make sure that the portlet depends on the upgrade?

Thx

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/44e03a8ffe...25f1ba1619

**Comment by brianchandotcom** [comment]
@jkappler @sergiogonzalez please see my other changes in upstream. Thx.

**Pull request closed without merging**
