### PR TITLE
LPS-178463 Pages configuration

### PR DESCRIPTION
**Pull request by Tim-Cao**
This is only for master.

https://issues.liferay.com/browse/LPS-178463

@sandrodw3
@DiegoHu97

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/11713

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/564d9a5e5c...23d7bd1885

**Comment by brianchandotcom** [comment]
@sandrodw3 see 01735607a47cc5f76d65bc83a3e31873de905f87 and resend a follow PR if I got it wrong.

**Pull request closed without merging**
