### PR TITLE
LPS-59413 Migrate all User & Configuration Upgrades to implement the UpgradeStepRegistrator

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-59413](https://issues.liferay.com/browse/LPS-59413).<br><br>

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f0024c77da...b913c65e31

**Comment by brianchandotcom** [comment]
Good job @drewbrokke You've got mechanics.... this sounds simple, but it's actually rare...

**Comment by drewbrokke** [comment]
Thanks @brianchandotcom!

**Pull request closed without merging**
