### PR TITLE
LPS-63472 Use table-responsive wrapper

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@sergiogonzalez I think the tests are unrelated, I just pinged @brianchiu

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/41c6cbf07e...282bbe23db

**Comment by brianchiu** [comment]
@evannagayama
@brianwulbern
@koor4356

Can you guys look at this? Both failures are the same failure but it looks like a test fix (not sure if it's flaky or consistent at this point).

**Comment by brianchiu** [comment]
Judging from later pulls (links below), this is probably not a flaky test failure.

The 623 Upgrade test is failing due to a bug.

The other 2 tests are likely UI changes.
https://github.com/brianchandotcom/liferay-portal/pull/36510
https://github.com/brianchandotcom/liferay-portal/pull/36520

**Pull request closed without merging**
