### PR TITLE
LPS-85585 Pages are not visible after selecting fjord template

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by jkappler** [comment]
@brianchiu, integration tests that were failing last week are fixed in this PR

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9c2559d55e...7a02b68d7c

**Comment by brianchandotcom** [comment]
@jkappler is this master only? If it needs to be backported, please send me a backport.

**Comment by jkappler** [comment]
hey @brianchandotcom, it's master only. So no need to backport it. 

Thanks!

**Pull request closed without merging**
