### PR TITLE
LPS-60556

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/268a418f45...298b03e38c

**Comment by brianchandotcom** [comment]
@migue @jorgeferrer @shuyangzhou fyi, Hugo's ingenious SF rule make our OSGi stuff even more stable

**Comment by shuyangzhou** [comment]
Hehe, I see this the pull that conflicted with the shopping pull :) This is a good one, that's a good call to automatically add the unbind. Thanks @hhuijser !

**Comment by JorgeFerrer** [comment]
Very nice @hhuijser

**Pull request closed without merging**
