### PR TITLE
LPS-138643, LRQA-70591 | master

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LPS-138643
https://issues.liferay.com/browse/LRQA-70591

Test Results:
- [✔️ ci:test:stable - 10 out of 10 jobs passed](https://github.com/xbrianlee/liferay-portal/pull/636#issuecomment-936918522)
- [❌ ci:test:relevant - 21 out of 23 jobs passed in 2 hours 59 minutes](https://github.com/xbrianlee/liferay-portal/pull/636#issuecomment-936918522)
- [✔️ ci:test:sf - 1 out of 1 jobs passed in 2 minutes](https://github.com/xbrianlee/liferay-portal/pull/636#issuecomment-936569454)
Integration test failure for `ci:test:relevant` is not related to these changes

### CODE REVIEW

**Comment by xbrianlee** [comment]
cI:reopen

**Comment by xbrianlee** [comment]
ci:reopen

**Comment by lipusz** [comment]
@brianchandotcom 

Hello Brian,

When merging, can you please remove the `.lfrbuild-release-src` from `search-experiences`? If you prefer a separate ticket I can do that tomorrow.

We'll add it back later.

Thank you!

**Comment by brianchandotcom** [comment]
@lipusz removed in 0a94705b713a6296f0345fb1918cab29416da2eb

**Pull request closed without merging**
