### PR TITLE
LPS-50604 Follow bookmarks' pattern for notification handler

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ad8a65ec65...4ed6142ca7

**Comment by brianchandotcom** [comment]
Hey @izaera 

I merged this in, but there are 3 things I need you to work on

1.) CleanUpSubscriptionMessageListener, shouldn't be something I duplicate for every portlet. Since it's scanning that whole table, I want to have one message listener do it and have portlets register the logic in there. It'll scale more.

2.) AssetEntryLocalServiceImpl used to delete stale data in Wiki. It doens't do that anymore. You commented it out but didn't actually readd the logic (that I know of).

3.) WikiServiceConfigurator is different from polls and bookmarks (has Spring reference), is that intentional?

**Comment by izaera** [comment]
Hi @brianchandotcom:

Regarding your comment:

1) I will have a look at it and see if I can extract a common factor.

2) I have told @ealonso about this and he will take care of it. It doesn't make too much sense to readd that code again as it does not make too much sense.

3) I guess bookmarks is wrong. That reference makes WikiServiceConfigurator wait until the portlet is fully deployed to start its activation code. @migue told me to add it. If it does not make sense any more we can remove it, or add it to bookmarks.

**Pull request closed without merging**
