### PR TITLE
Lps 75330

### PR DESCRIPTION
**Pull request by shuyangzhou**
@brianchandotcom , @mtambara will do the backport for  this.

### CODE REVIEW

**Comment by mtambara** [comment]
@brianchandotcom asset-service looks very different between CE and EE, it doesn't make sense to backport this.

**Comment by jpince** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@shuyangzhou @mtambara can you resend with a pull to 7.0.x and master? Why? I don't want to push a fake gradle cache to upstream, so I need a way to publish it in 7.0.x first.

**Comment by shuyangzhou** [comment]
@mtambara backport the osgi util changes to 7.0.x for release, leave the rest to be master only, as they can not be backported.

**Pull request closed without merging**
