### PR TITLE
LPS-105791 | master

### PR DESCRIPTION
**Pull request by john-co**
https://issues.liferay.com/browse/LPS-105791

### CODE REVIEW

**Comment by john-co** [comment]
Reviewed `ci test` results from https://github.com/john-co/liferay-portal/pull/224. Test failures are unrelated. :heavy_check_mark: 

However, there is still a risk that this could potentially break portal involving npm modules after merging. FI team will be able to clean up minor failures after the merge. It may be possible that nothing breaks, but we're not sure so we'll need to keep an eye out after this merge. Please revert if there are catastrophic failures.

/cc @jpince @jbalsas

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/02c261bf67...ec31dd17f3

**Comment by izaera** [comment]
Thx guys @john-co @brianchandotcom :-)

**Pull request closed without merging**
