### PR TITLE
LPS-193234 Make ResourceAction a partitioned control table

### PR DESCRIPTION
**Pull request by john-co**
Manually forwarded due to issues with `ci:stable`. Test failures [not related](https://github.com/liferay-uniform/liferay-portal/pull/1433#issuecomment-1736350634).
cc/ @LuisOrtiz89 

----

[original message]
@achaparro I changed the calls to keep the order of the service.xml and the LPS number for that commit.

### CODE REVIEW

**Comment by john-co** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/30589cfb70...3354f66b7d

**Comment by brianchandotcom** [comment]
@LuisOrtiz89 @achaparro see 3354f66b7db68da1df06288ba132bbdc8e6e522d

**Comment by achaparro** [comment]
cc/ @shuyangzhou

**Pull request closed without merging**
