### PR TITLE
LPS-86335 Autogenerated

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f25360cdb8...893ecff55b

**Comment by brianchandotcom** [comment]
@preston-crary is *.security.permission.* the path we're moving everything toward?

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/65188

**Pull request closed without merging**
