### PR TITLE
LPS-59896 My Sites show members as 'null' for organization sites

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-59896](https://issues.liferay.com/browse/LPS-59896).<br><br>/cc @jorgeferrer @daledotshan @daviddotzhang @pei-jung

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by drewbrokke** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1ff809dc4b...4d52907cb0

**Pull request closed without merging**
