### PR TITLE
LPS-98416

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@brianchandotcom, you'll need to publish both `java-parser` and `source-formatter`

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
Related pulls:
https://github.com/brianchandotcom/liferay-portal-ee/pull/25484
https://github.com/brianchandotcom/liferay-portal-ee/pull/25485

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1671eac618...e40667f613

**Pull request closed without merging**
