### PR TITLE
LPS-69771 Use JOIN to join rows and WHERE to filter rows we really want.

### PR DESCRIPTION
**Pull request by brandizzi**
cc @marianoalvarosaiz.

### CODE REVIEW

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
Unrelated test failures @Ithildir

**Comment by brandizzi** [comment]
Note to @natocesarrego:

Renato, this is a "master" version of this pull from @marianoalvarosaiz: https://github.com/brandizzi/liferay-plugins-ee/pull/36/ I noticed that the same upgrade process exist in both master and ee-6.2.x, but they are slightly different. Once this fix is merged, could you backport it to ee-6.2.x? I'll forward you Mariano's PR so you can work on top of it.

Thanks!

**Comment by brianchandotcom** [comment]
@brandizzi please see my changes in upstream. Thx.

**Comment by natocesarrego** [comment]
Hi @brandizzi,

I'll put it on my queue, ok?

Thanks.

**Pull request closed without merging**
