### PR TITLE
LPS-186609 Adds required parameters to the request when status page is shown though error

### PR DESCRIPTION
**Pull request by alessandromalves**
https://issues.liferay.com/browse/LPS-186609

cc.: @lfbesada @jkappler

### CODE REVIEW

**Comment by alessandromalves** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/12336

:heavy_check_mark: ci:test:stable - 30 out of 30 jobs passed
:x: ci:test:relevant - 245 out of 307 jobs passed in 3 hours 4 minutes

**Comment by alessandromalves** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/aa42446200...2c75878edb

**Comment by brianchandotcom** [comment]
@jkappler @lfbesada see 9283978301d5fc9550d4186fa1b282a9021e24a8

**Pull request closed without merging**
