### PR TITLE
LPS-55072 SF

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/44b8e840cf...543f42de25

**Comment by brianchandotcom** [comment]
@linolaoj @marcellustavares @epgarcia minor SF in upstream. See 38897718bfebecb9cb71e0ba4e3f0177e711ea7a

Thx

**Pull request closed without merging**
