### PR TITLE
LPS-70229 SF

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @4lejandrito

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@sergiogonzalez can you resend? LPS-70229 is already backported to ee-7.0.x.

I'm afraid of merging this to master with the same ticket, otherwise support may not know to backport it.

**Comment by sergiogonzalez** [comment]
Hey @brianchandotcom I resent it here https://github.com/brianchandotcom/liferay-portal/pull/47598

**Pull request closed without merging**
