### PR TITLE
LRQA-44003 | master

### PR DESCRIPTION
**Pull request by patriciajeanperez**
https://issues.liferay.com/browse/LRQA-44003

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
Hi @pedroqueiroz and @jpince, this pull is a follow up on https://github.com/rafaprax/liferay-portal/pull/879. It simplifies the username locator and can be used in both Blogs and Calendar event comments.

**Comment by jpince** [comment]
cc/ @alexcandidos

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by pedroqueiroz** [comment]
Thanks, @patriciajeanperez ! :)

**Pull request closed without merging**
