### PR TITLE
LPS-56373

### PR DESCRIPTION
**Pull request by matethurzo**
cc @sergiogonzalez

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@LeventeHudak please resend, no need for upgrade table (just like other pull). You can try it out.

Deploy the module, without the column. Regen, and then redeploy, you'll see the column show up.

**Comment by LeventeHudak** [comment]
Hi @brianchandotcom, will do! Sending it back right away!

**Pull request closed without merging**
