### PR TITLE
LPS-75085

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-75085.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 what happened here? Can you retest when it's possible to?

**Comment by pyoo47** [comment]
@brianchandotcom There's been some instability in the new local-git synch code. I've sent you a pull that I think will stabilize it. Please review and merge as soon as you can. https://github.com/brianchandotcom/liferay-portal/pull/51988

**Comment by jonmak08** [comment]
I'll resend.

**Comment by pyoo47** [comment]
@jonmak08 The test is running.. you don't need to resend

**Comment by pyoo47** [comment]
ci:stop Jon is resending because he needs to add commits.

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/brianchandotcom/liferay-portal/pull/51993

**Pull request closed without merging**
