### PR TITLE
LPS-64713 Rounding logic changed between JDK7 and JDK8

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e1dcc6d274...84e885c61d

**Comment by brianchandotcom** [comment]
Wow. That rounding difference is strange....

**Comment by shuyangzhou** [comment]
That was a bug in jdk7 fixed by jdk8. It is not backward compatible:(

**Pull request closed without merging**
