### PR TITLE
LPS-127344 skip flaky test

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:open

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@nhpatt you need to type "ci:reopen", not "ci:open"

I only saw this because of Slack.

**Comment by nhpatt** [comment]
@brianchandotcom Ups sorry, my bad, I usually use ci:reopen, this time I don't know what I was thinking.

**Pull request closed without merging**
