### PR TITLE
LPS-63730 Simplify

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @csierra

### CODE REVIEW

**Comment by csierra** [comment]
hey guys... now that you are into this... can you tell why were we using a static map to hold the `ready` state? One of the changes I made is to `synchronize` over `this` instance just to make sure the portlet can't be unset while it is being set, but I still don't know why we are using a static map to hold the states.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/dfebfd1db4...329ff19df3

**Comment by brianchandotcom** [comment]
@shuyangzhou see comment by @csierra thx.

**Comment by shuyangzhou** [comment]
@csierra Not really sure what you are asking.
If the map is not static, how can you get the logic done?

It can not be a non-static map obviously, that means every PortletImpl will have a copy of that map.
It can not be a non-static boolean field either, as for instanceable portlets, only their root PortletImpls track whether they are ready or not.

Without the static map, how would you want to fulfill the logic? (One possible way could be linking all instanceable PortletImpl objects back to their root PortletImpl object, then it can be just a boolean field. But to me that's a lot of extra work, and affecting the Portlet api in a negative way by adding hierarchy)

**Comment by csierra** [comment]
Hey @shuyangzhou, 

thanks for the explanation. If for the instanceable portlets only their root PortletImpls track whether they are ready or not, but any instance can be used to change that shared state, then the pull I sent is wrong. 

please see the follow up pull https://github.com/brianchandotcom/liferay-portal/pull/38797

this should achieve the proper isolation while avoiding the former global lock.

Thank you for you help!

**Pull request closed without merging**
