### PR TITLE
master

### PR DESCRIPTION
**Pull request by amosfong**
ok, trying again

### CODE REVIEW

**Comment by kiyoshilee** [comment]
@amosfong this pull has failures on all the module-integration tests. They all failed for the same reason:

<pre>
Error Message

Portal log assert failure, see above log for more information: 
Error while starting bundle: file:/opt/dev/projects/github/liferay-portal/bundles/osgi/modules/com.liferay.marketplace.store.web.jar 
org.osgi.framework.BundleException: Could not resolve module: com.liferay.marketplace.store.web [282]
  Unresolved requirement: Import-Package: com.liferay.portal.license.util

	at org.eclipse.osgi.container.Module.start(Module.java:429)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1252)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1224)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:512)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:361)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:313)
Stacktrace

junit.framework.AssertionFailedError: 
Error while starting bundle: file:/opt/dev/projects/github/liferay-portal/bundles/osgi/modules/com.liferay.marketplace.store.web.jar 
org.osgi.framework.BundleException: Could not resolve module: com.liferay.marketplace.store.web [282]
  Unresolved requirement: Import-Package: com.liferay.portal.license.util

	at org.eclipse.osgi.container.Module.start(Module.java:429)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1252)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1224)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:512)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:361)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:313)

	at com.liferay.portal.log.assertor.PortalLogAssertorTest.scanXmlLogFile(PortalLogAssertorTest.java:136)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:68)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:58)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:135)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:199)
	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:69)
	at java.nio.file.Files.walkFileTree(Files.java:2602)
	at java.nio.file.Files.walkFileTree(Files.java:2635)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXmlLog(PortalLogAssertorTest.java:56)</pre>

There was an error on the pullrequest tester that prevented it from posting this error, sorry about the inconvenience.

**Comment by kiyoshilee** [comment]
Hey Amos,

I'm' not sure, that might be a decision Brian would make.

**Comment by lionah** [comment]
@amosfong I forgot what we agreed that we'd do.

Right now we've listed it incorrectly as an export but that won't help resolve the import issue.

**Comment by amosfong** [comment]
We can move LicenseUtil to portal.kernel.license... package, and then it will be available to you as a core service.

@lionah

**Comment by amosfong** [comment]
I can include that move in this PR and resend, then you should be fine

**Comment by lionah** [comment]
@amosfong Thanks, also please remove the useless export in `marketplace-store-web`...

**Pull request closed without merging**
