### PR TITLE
LPS-50660 SF

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brandizzi** [comment]
Hey @brianchandotcom, @marcellustavares already took a look on this code, so I'm sending it directly to you.

Thanks!

**Comment by marcellustavares** [comment]
cc @juliocamarero

**Comment by juliocamarero** [comment]
:+1:

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7e0deae344...0b27e6155e

**Pull request closed without merging**
