### PR TITLE
LPS-74544 Auto sort lang keys

### PR DESCRIPTION
**Pull request by petershin**
Hi Brian,

The existing `build-lang` task sorts keys. To keep things fast, the new check only sorts `Language.properties` files that don't have generated `Language_*.properties` files (for example fa22b37).

@hhuijser

### CODE REVIEW

**Comment by petershin** [comment]
ci:reopen

**Comment by petershin** [comment]
@pyoo47

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by pyoo47** [comment]
@petershin Thanks for pointing out the problem. I've implemented a fix.

**Pull request closed without merging**
