### PR TITLE
LPS-57347 resolution of the same-name resources from different portlets

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
fyi @csierra

**Comment by juliocamarero** [comment]
@ZoltanTakacs can we add this one to 7.0.x ?

it is a quite critical issue, thanks!

**Comment by ZoltanTakacs** [comment]
Hey @juliocamarero thanks for notifying me. 

I'll add this to M7 along with https://github.com/brianchandotcom/liferay-portal/pull/28868 & https://github.com/brianchandotcom/liferay-portal/pull/28869 when get committed to master.

Thank you,
Zoltán

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/348836cc3c...3039479c99

**Pull request closed without merging**
