### PR TITLE
LPS-85177 Build lang

### PR DESCRIPTION
**Pull request by rafaprax**
//cc @brianikim

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b85cbb20d8...63912b7ede

**Comment by brianchandotcom** [comment]
@rafaprax Please send a backport to support for 7.1.x (like our normal support workflow). I'm no longer auto backporting pulls like this.

@jhendley @liferay @zsoltbalogh FYI.

Merged into master only.

**Comment by rafaprax** [comment]
Ok @brianchandotcom

**Comment by rafaprax** [comment]
sent at https://github.com/liferay/liferay-portal-ee/pull/9791

**Pull request closed without merging**
