### PR TITLE
Lps 73667

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bb939bf253...1492118976

**Comment by brianchandotcom** [comment]
@mdelapenya @shuyangzhou please see my changes in upstream. Thx.

**Comment by mdelapenya** [comment]
Thanks for the review, we need to document this new behaviour

PS: I thought that we were good with the lambda @shuyangzhou :(

**Comment by shuyangzhou** [comment]
@mdelapenya this is not about lambdas or not, it is about simplicity and over design. This is a very simple requirement, it can be done by a single private method. It does not need those fancy decoration which is complex for human to read and slow for machine to run. I explained to you we should solve the problem in the most straight forward way first, then start to talk about whether those "irrelevant" parts are needed at all. In this case they are really not needed.

**Pull request closed without merging**
