### PR TITLE
LPS-97498 Add full-sentence descriptions to frontend ignore files

### PR DESCRIPTION
**Pull request by wincent**
This commit fleshes out the comments in the .eslintignore and .prettierignore files.

I tried to model it on the portal.properties style, with one notable difference: we cannot indent the lines to make the sections stand out because both Prettier and ESLint are whitespaces-sensitive, treating any leading whitespace as part of the glob patterns (which doesn't make any sense, but it's not something we can realistically change).

### CODE REVIEW

**Comment by wincent** [comment]
@brianchandotcom: This is the follow-up to [your comment](https://github.com/brianchandotcom/liferay-portal/pull/75020#issuecomment-506430527) on #75020. Let me know if this is something like what you had in mind.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@wincent see 80aedd1a54d6237ff81927a7598c3bf85a3f6e25

**Comment by wincent** [comment]
Got it, thanks @brianchandotcom.

**Pull request closed without merging**
