### PR TITLE
LPS-204467: Allow some Object Entry fields that must not be forbidden

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What is new?**
- Update some constants to use the Object Definition API and manage Object Entry REST Application name
- Update FieldTable to update those fields and switch to bussinessType

**JIRA Ticket**
https://liferay.atlassian.net/browse/LPS-204467

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:reopen

**Comment by sergiojimcos** [comment]
Forwarded from here: https://github.com/liferay-headless/liferay-portal/pull/1779

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9a29691c71...49eb1aa64f

**Comment by brianchandotcom** [comment]
@sergiojimcos @4lejandrito does order matter here?

```
		_setBatchUnsupportedFormats(objectDefinitionSchemaProperties);

		_setListEntryRef(schemas);

		_setReadOnlyProperties(schemas);
```

I assume no, so I just removed the line breaks since it seems sorted. See 3a954e1a

If I'm wrong, please readd the line breaks.

**Pull request closed without merging**
