### PR TITLE
LPS-58997 Ant build lang

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@robertoDiaz @peterfellwock what about the implicit "resourceBundle" var?

I thought we had that done?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bc7ef87878...cda29eeecf

**Comment by robertoDiaz** [comment]
Hey @brianchandotcom, we tried to do this but we found some problems related with how to get the right resource bundle classpath.

I think it's the same problem that @peterfellwock found, but currently I'm not involved in this.

@peterfellwock, whats the status of this??

**Comment by peterfellwock** [comment]
@robertoDiaz lets work together on this, our last conversation was about the Spanish team adding it to the list of things to fix, maybe make it into a taglib (please dont).

**Comment by sergiogonzalez** [comment]
Hey @peterfellwock right now we are really busy with bug fixing and including some mandatory features that needs to be in 7 before it's out, so I'm afraid that we don't have time to help you with this right now. 
Actually, I think that it would be better if somebody in the platform team with more experience with resourceBundles helps you with this story, but I'm not sure who might be the right person. I know @shuyangzhou did a lot of things with Language as well as @csierra

**Pull request closed without merging**
