### PR TITLE
LRQA-18967 - Extract getFailedJobMessage into Java and create junit tests

### PR DESCRIPTION
**Pull request by pyoo47**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pyoo47 I"ll merge this pull as it is now. If you make further changes, please wait / or send in a new pull. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.

**Pull request closed without merging**
