### PR TITLE
LPS-73786 Use PreparedStatement instead

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @NorbertKocsis

**Comment by jpince** [comment]
@NorbertKocsis @sergiogonzalez closing this pull for the following exception:
`     [java] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.upgrade.UpgradeException: java.sql.SQLSyntaxErrorException: Table 'lportal.counter' doesn't exist`
I see this same error in the previous pull https://github.com/sergiogonzalez/liferay-portal/pull/3948. Please resend.

**Comment by jpince** [comment]
ci:close

**Comment by NorbertKocsis** [comment]
Hi @jpince ,

In which test exactly did you find this? I can't see it.

Br,
Norbert

**Comment by jpince** [comment]
@NorbertKocsis This only happens in the upgrade tests
functional-upgrade-jboss70-mysql56-jdk8/0
https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/93609/consoleFull

functional-upgrade-tomcat80-mariadb100-jdk8/0
https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/144917/consoleFull

**Pull request closed without merging**
