### PR TITLE
LPS-58854 Use EmptyOnClickRowChecker instead

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
@brianwulbern, @evannagayama, could you take a look at the failing tests? I fixed the compilation errors, but the tests still fail. I think I've also seen them fail on other pulls, so maybe there's something wrong with those.

**Comment by brianchandotcom** [comment]
@brianwulbern, @evannagayama can you guys resend? Thx.

**Comment by brianwulbern** [comment]
Chema's new pull submitted here: https://github.com/brianchandotcom/liferay-portal/pull/32492.

**Pull request closed without merging**
