### PR TITLE
LPS-76346 SF

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by jpince** [comment]
@ealonso See [SF error](https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/60880//consoleText), looks like [import com.liferay.portal.kernel.util.Validator](https://github.com/brianchandotcom/liferay-portal/pull/55066/files#diff-eaf91e4e524622e9fa8fb427b3f99335R34) was added but is not used?

**Comment by jpince** [comment]
@petershin @hhuijser stacktrace is awfully long if that one line is the only problem (but maybe I'm missing something else?)

**Comment by petershin** [comment]
@jpince - SF is complaining about two issues in this file.

It found an [unused import](https://github.com/brianchandotcom/liferay-portal/pull/55066/files#diff-eaf91e4e524622e9fa8fb427b3f99335R34) and also an [unneeded white space](https://github.com/brianchandotcom/liferay-portal/pull/55066/files#diff-eaf91e4e524622e9fa8fb427b3f99335R109).

**Comment by jpince** [comment]
@petershin thanks!

**Pull request closed without merging**
