### PR TITLE
LPS-102705 Add tests

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b37cc6621b...9cc279750b

**Comment by brianchandotcom** [comment]
@adolfopa I merged this, but the order of the mocks seems to be in a random order (I can't find the rationale)

```
		Mockito.when(
			_fileEntry.getModel()
		).thenReturn(
			Mockito.mock(DLFileEntry.class)
		);

		Mockito.when(
			_fileEntry.getFileVersion()
		).thenReturn(
			Mockito.mock(FileVersion.class)
		);

		Mockito.when(
			_ddmStructureLocalService.getClassStructures(
				Mockito.anyLong(), Mockito.anyLong(),
				Mockito.any(OrderByComparator.class))
		).thenReturn(
			Collections.singletonList(Mockito.mock(DDMStructure.class))
		);

		Mockito.when(
			_dlFileEntryMetadataLocalService.fetchFileEntryMetadata(
				Mockito.anyLong(), Mockito.anyLong())
		).thenReturn(
			_dlFileEntryMetadata
		);

		Mockito.when(
			_storageEngine.getDDMFormValues(Mockito.anyLong())
		).thenReturn(
			_ddmFormValues
		);

		Mockito.when(
			_ddmFormValues.getDDMFormFieldValuesMap()
		).thenReturn(
			Collections.singletonMap(
				"TIFF_IMAGE_LENGTH",
				Collections.singletonList(_ddmFormFieldValue))
		);

		Mockito.when(
			_ddmFormFieldValue.getValue()
		).thenReturn(
			_value
		);

		String expectedValue = StringUtil.randomString();

		Mockito.when(
			_value.getString(Mockito.any(Locale.class))
		).thenReturn(
			expectedValue
		);
```

**Pull request closed without merging**
