### PR TITLE
LPS-166664 Make the sidebar Page Content panel more accessible

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-166664

@veroglez

### CODE REVIEW

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See [liferay-echo#7560](https://github.com/liferay-echo/liferay-portal/pull/10067)

:heavy_check_mark: ci:test:stable - 28 out of 28 jobs passed
:x: ci:test:relevant - 198 out of 203 jobs passed in 1 hour 34 minutes

**Comment by ozysouza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9cea1ecf39...55b6c749e7

**Comment by brianchandotcom** [comment]
@veroglez see my fix in cbf4443bcdfe231f81e7cf0d932ba3b7f2a48ac5

@ozysouza fyi

**Pull request closed without merging**
