### PR TITLE
LPS-66016 Update upgrade process for nested portlets

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jkappler lots of test failures. Please resend.

**Comment by evannagayama** [comment]
Somehow a web content change got through the pr tester. The locator for a web content title was changed to name. This affecting all pr's. We're fixing it here: https://issues.liferay.com/browse/LRQA-25478

**Comment by evannagayama** [comment]
@jkappler @brianchandotcom  somehow this issue got through and now we can't add a web content article https://issues.liferay.com/browse/LPS-66067

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Pull request closed without merging**
