### PR TITLE
[READ DESCRIPTION] LPS-68326 Enable frontend JS tests

### PR DESCRIPTION
**Pull request by jbalsas**
Hey Brian!

This is the first PR that establishes the guidelines we want for any upcoming FrontEnd code. This has been agreed upfront with @eduardolundgren and @brunobasto. All new code (and this PR in particular) should adhere to:
- [x] Green set of tests running (`gulp test`)
- [x] 100% test coverage (`gulp test:coverage`)
- [x] No linting errors (`gulp lint`)
- [x] Autoformated, no format changes (`gulp format`)
- [ ] ~~Below complexity metrics threshold (`gulp complexity`).~~ (currently unavailable).
- [x] Code completely documented following the [Annotating JavaScript for the Closure Compiler](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler) best practices and [usejsdoc](http://usejsdoc.org/) patterns

Unit tests are already integrated in the Jenkins CI thanks to @kenjiheigel. We'll figure out how to best integrate the rest of metrics as well.

Please, let us know if you have any doubts.

Thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Thx guys.

@ithildir can you review modules/apps/foundation/frontend-js/frontend-js-web/build.gradle and send me an update if needed?

 @kenjiheigel can you send me a pull to auto close portal-frontend-js-jdk8 if the batch seems stable (give it a day or 2 worth of pulls).

@jbalsas can you send me a backport so we at least have this infrastructure in place.

Thx everyone.

**Comment by Ithildir** [comment]
Done: https://github.com/brianchandotcom/liferay-portal/pull/44202

**Comment by kenjiheigel** [comment]
K, I'll keep an eye on the results.

**Comment by kenjiheigel** [comment]
The results have been clean from what I've checked. Hashi has sent a pull to add this to the auto close list. 
https://github.com/brianchandotcom/liferay-jenkins-ee/pull/1893

Re: backports, the [build script](https://github.com/liferay/liferay-portal/blob/39458b8/build-test-batch.xml#L1798-L1830) and [test properties](https://github.com/liferay/liferay-portal/blob/39458b8/test.properties#L995) changes necessary are already added. If the correct build.gradle and package.json updates are made, tests should run on the 7.0 branches. 

Chema will check potentially backporting package.json changes though.

**Comment by jbalsas** [comment]
I've sent the infrastructure backport to https://github.com/brianchandotcom/liferay-portal-ee/pull/14889. @kenjiheigel, could you double check to make sure I didn't miss anything?

Thanks!

**Pull request closed without merging**
