### PR TITLE
LPS-59561 Resource URL for /portlet.properties is null

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
Thanks for this one @csierra :+1::tada::tada:

**Comment by csierra** [comment]
does it work? :open_mouth: 

:stuck_out_tongue_closed_eyes:

**Comment by jkappler** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8d4b7a479a...c619f257d4

**Comment by brianchandotcom** [comment]
@jkappler @csierra test? Thx.

**Comment by csierra** [comment]
yup... please see https://github.com/brianchandotcom/liferay-portal/pull/32801

**Pull request closed without merging**
