### PR TITLE
LPS-66075 SF

### PR DESCRIPTION
**Pull request by brandizzi**

### CODE REVIEW

**Comment by brandizzi** [comment]
cc @marcellustavares.

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pyoo47 what happened here? hung?

**Comment by pyoo47** [comment]
Looks the the Freemarker taglib problem is still giving us trouble despite the changes that Hashi has made. I've got a plan to at least prevent it from crashing the top-level build. I'll send you a pull later that should prevent the top-level build from choking on the large log files.

@kenjiheigel @michaelhashimoto

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/50592dfd04...2330a42699

**Pull request closed without merging**
