### PR TITLE
LRQA-36041 BUG - Use ParallelExecutor to ensure that all threads have completed before moving on

### PR DESCRIPTION
**Pull request by pyoo47**
Please publish after merging

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@pyoo47 why would we need to test this?

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by pyoo47** [comment]
@brianchandotcom I figured you would want to at least see that it passed source formatting

**Comment by brianchandotcom** [comment]
@pyoo47 I'm assuming you ran it locally... (takes 2 minutes on your machine) vs the cost of 300+ vms for 3 hours?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b9d3c02e62...61cb2f2a49

**Pull request closed without merging**
