### PR TITLE
LPS-59249

### PR DESCRIPTION
**Pull request by natecavanaugh**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pat270 breaks CI tests please talk to @brianchiu

**Comment by brianchiu** [comment]
CC @kenjiheigel

**Comment by kenjiheigel** [comment]
Looking into it.

**Comment by kenjiheigel** [comment]
Sorry @pat270, some of these tests are actually failing, so it's not a test fix. 

Here's some use cases that I reproduced manually on this branch (that were tested in the PR tester): 
1. Add Web Content, and then try to edit (the content has disappeared)
2. Add Web Content, then search for it (it doesn't come up)
3. Links are missing from DDL record tables: https://test-1-8.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/1504/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=CPDynamicdatalists%23EditBooleanFieldFieldLabel,label_exp=!master/functional-tomcat-mysql/1/screenshots/before2.jpg
4. Add Web Content, add a WCD to page, and select the WC (content does not display)

I think it boils down to two main issues. Links not appearing in DDM tables, and Web Content not publishing correctly. It's probably because their forms use some of the inputs you updated? I can show you more tomorrow.

**Pull request closed without merging**
