### PR TITLE
LPS-55800 SF

### PR DESCRIPTION
**Pull request by marcellustavares**
cc @rafaprax

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@marcellustavares I think there was miscommunication:

taglib uri="http://liferay.com/tld/liferay-ddm" prefix="liferay-ddm" %><%@
taglib uri="http://liferay.com/tld/portlet" prefix="liferay-portlet" %><%@
taglib uri="http://liferay.com/tld/theme" prefix="liferay-theme" %><%@
taglib uri="http://liferay.com/tld/ui" prefix="liferay-ui" %>

It should stil be http://liferay.com/tld/ddm

But the file should be liferay-ddm.tld. SEe portlet, theme, ui, etc.

Please resend? Also, sort bnd.bnd attributes that you guys added. Required-Capability should go before Web-ContextPath

Thx

**Comment by leoadb** [comment]
@marcellustavares I just did that. I sent you another pull request. Thanks.

**Comment by marcellustavares** [comment]
Thx @leoadb, I was about to do it :)

**Comment by marcellustavares** [comment]
Resent to https://github.com/brianchandotcom/liferay-portal/pull/28675

**Pull request closed without merging**
