### PR TITLE
LPS-89415 Do not create the resource impl file if the resource has no methods

### PR DESCRIPTION
**Pull request by petershin**
@jpince

### CODE REVIEW

**Comment by nhpatt** [comment]
👏 :)

**Comment by jpince** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@petershin @nhpatt this is a better fix e3776c5c3204bb939ba3d36ef23d78cd42b5d746, see regen 6a45089163d43bef58ffe205cbd73b90878718ad

**Pull request closed without merging**
