### PR TITLE
LPS-94966

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@hhuijser can we SF enforce this?

@drewbrokke @pei-jung can you apply this to your modules?

**Comment by drewbrokke** [comment]
@brianchandotcom I just double-checked this, and we will not be able to use this for our use-cases.  As of right now this is only seems applicable when you are requiring a JS component from the same module where it's defined.  @jbalsas is this a correct assessment, or is there another way to use this constant?

**Comment by jbalsas** [comment]
Hey @adolfopa, @boton, this should be a relative path. `aui:script require="..."` should already be namespacing the package name and version when necessary.

@drewbrokke, not sure what are your use cases. This constant is not really needed anymore, but you're right in that it is only to be consumed within the same module. Sharing across modules requires that either the module defines a globally accessible alias or that the consumer knows the version. We're exploring ways to make this automatic by npm-links or some similar construct.

**Pull request closed without merging**
