### PR TITLE
LPS-60016 Making it a sentence

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a44ea0d11f...38c41fd340

**Comment by brianchandotcom** [comment]
@brunobasto can you send a follow up pull:

In bnd.bnd

Rename

Web-ContextPath: /ddm

to

Web-ContextPath: /dynamic-data-mapping

Some are the long form, and some are the short form right now. I'd like it all consistent. Same for DDL.

Thx.

**Comment by brunobasto** [comment]
hey @brianchandotcom 

Sent at https://github.com/brianchandotcom/liferay-portal/pull/31716

Thanks!

**Pull request closed without merging**
