### PR TITLE
COMMERCE-276

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@ZoltanTakacs can you take this pull and resend it to me after making these changes:

1.) Fix the formatting in the XML files.

2.) Rename Abstract* to Base* (where Talend allows it). I've always used the Base* pattern to mean Abstract* since it's a shorter word.

Thx

**Comment by Ithildir** [comment]
@ZoltanTakacs, I already formatted the XML files and the Javadocs in [my branch](https://github.com/Ithildir/liferay-portal/tree/COMMERCE-276-pr859).

**Comment by ZoltanTakacs** [comment]
Thank you @Ithildir ! I'll make the changes regarding the rename from Abstract* to Base* where possible based off of [your branch|https://github.com/Ithildir/liferay-portal/tree/COMMERCE-276-pr859] where you fixed the XML and Javadocs :) Thanks a lot for your help!

**Pull request closed without merging**
