### PR TITLE
LPS-73070 SF

### PR DESCRIPTION
**Pull request by jpince**
https://issues.liferay.com/browse/LPS-73070

@hhuijser @petershin BChan's change in https://github.com/liferay/liferay-portal/commit/a0b6eae40181c2d80a6f046da814232ddce3c1f0 was made yesterday, but pulls are still failing (e.g. https://github.com/brianchandotcom/liferay-portal/pull/51426). It looks like CI is using the right git hash with his change, could this be an issue with SF?

@jbalsas fyi, both files in autogenerated commit https://github.com/liferay/liferay-portal/commit/5516983aaccfd3b922d71b5a7ed13eab6294cde1 had a newline at the end :)

### CODE REVIEW

**Comment by jpince** [comment]
pushed upstream: https://github.com/liferay/liferay-portal/commit/addf97550ca27970bc87c2aa43082de8007b4017

**Comment by jbalsas** [comment]
@jpince, `package-lock` files used to be ignored. Maybe this [change](https://github.com/liferay/liferay-portal/commit/b90d343680c7b8d524e9810d5bc1005d4db03afa#diff-06be11168843ef8700e117c72d8f765b) has something to do :/

**Comment by petershin** [comment]
@jbalsas - Yes, you're right.  Since npm will overwrite those files everytime, I'll send a pull to revert those changes

**Comment by brianchandotcom** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@jpince peter sent me a revert so this should be fixed now.

**Pull request closed without merging**
