### PR TITLE
LPS-70650

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-70650.

Missed a source formatting on this commit.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jpince** [comment]
@yichenroy missed one? :) https://issues.liferay.com/browse/LRQA-34315
`The JRE was not found in directory /opt/java/jdk1.8.0_51. (JAVA_HOME)`

**Comment by jpince** [comment]
@brianchandotcom the weblogic issue is known, this pull is good to merge

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/03dac3dfea...7db0bbf881

**Comment by yichenroy** [comment]
@jpince the update files weren't propagated correctly, will run the propagator again.

**Pull request closed without merging**
