### PR TITLE
LPS-145351 Need to reindex the updates

### PR DESCRIPTION
**Pull request by marcelabc**
Related issue: https://issues.liferay.com/browse/LPS-145351

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:open

**Comment by marcelabc** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Wow! Thank you @marcelabc !

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ada2d0b537...d5994a92bf

**Pull request closed without merging**
