### PR TITLE
[TS] LPS-69762 Unable to include .tpl file in a layout template (regression)

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
/cc @lipusz @topolik

### CODE REVIEW

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@stian-sigvartsen please resend. Lots of CI failures.

**Comment by lipusz** [comment]
Realized we forgot to update system.packages.mf. Did and send for testing. https://github.com/lipusz/liferay-portal/pull/159

Will resend once it passed CI.

**Comment by lipusz** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/46192

**Pull request closed without merging**
