### PR TITLE
LPS-84292 Fix References

### PR DESCRIPTION
**Pull request by jeyvison**

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:reopen

**Comment by jeyvison** [comment]
The same error does not happen when i run '**ci:test:relevant'** on my repo so i believe it's not related.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bf0b36de01...180d89ccaa

**Comment by brianchandotcom** [comment]
@jeyvison @leoadb nice job guys. This was a very good refactor.

**Comment by brianchandotcom** [comment]
@jeyvison @leoadb also,  this is for master only, not backported to 7.1.x

**Comment by brianchandotcom** [comment]
@jeyvison @leoadb service builder complaint in this pull is real, I fixed it in 8e3eb4231d03070768cc3ddbfd9d87422bc1ca68

I ran 

gradlew :apps:dynamic-data-mapping:dynamic-data-mapping-service:buildService

**Pull request closed without merging**
