### PR TITLE
LPS-68947 Allow to pass function references only and check if they exist at runtime

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:stop

**Comment by jbalsas** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@jbalsas please send to @ZoltanTakacs

thx

**Comment by jbalsas** [comment]
Done! 

https://github.com/ZoltanTakacs/liferay-portal-ee/pull/2044

**Pull request closed without merging**
