### PR TITLE
Commerce 1067 34

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c3ff71e0b4...6dd80ac107

**Comment by ivicac** [comment]
@brianchandotcom I do care about the order. The thing is that in cases where I just need to rename methods or fields, I rely on SF, meaning, just do renaming and run SF. But, obviously, I shouldn't. It seems for this case there is a bug in SF. It doesn't sort methods in an interface. 
@hhuijser can you please check why SF doesn't sort methods in https://github.com/liferay/liferay-portal/blob/master/modules/apps/batch-engine/batch-engine-api/src/main/java/com/liferay/batch/engine/configuration/BatchEngineTaskConfiguration.java.
I manually sorted them here https://github.com/brianchandotcom/liferay-portal/pull/81357.

P.S. @brianchandotcom I don't agree that everything should be alphabetically sorted(except som SB related calls) but as that is the rule I am trying to stick with it.

**Comment by hhuijser** [comment]
@ivicac SF skips *Configuration.java files that have the `Meta.OCD` annotation on purpose.
The reason is that the UI is autogenerated from the *Configuration interfaces automatically and it keeps the order of the methods in that interface.

**Comment by ivicac** [comment]
thx @hhuijser

**Pull request closed without merging**
