### PR TITLE
LPS-57212 Decouple Journal/DDM upgrade processes

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by marcellustavares** [comment]
ci:retest

**Comment by marcellustavares** [comment]
hi @brianchandotcom, it seems I cannot access any of those reports. I'm getting connection refused.

I'll test locally by test name to check if they're passing.

Thx

**Comment by marcellustavares** [comment]
Resubmitted to https://github.com/brianchandotcom/liferay-portal/pull/28406

**Pull request closed without merging**
