### PR TITLE
LPS-203761 Page tree is not showing an error message when trying to move a non first pageable page

### PR DESCRIPTION
**Pull request by liulukiwi**
https://liferay.atlassian.net/browse/LPS-203761

@liulukiwi

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:reopen

**Comment by liulukiwi** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/14847

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/32dd835965...d91be4008f

**Comment by brianchandotcom** [comment]
@ling-alan-huang please enforce d91be4008feb5fe9be5cb45d8b5cf6c7089cc1d4

**Pull request closed without merging**
