### PR TITLE
LPS-67768 Annotate specific browser LPS for reference

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jpince** [comment]
@jbalsas a lot of unit test failures unique to this pull. Some of the errors:
```
java.lang.IllegalStateException: An error occurred executing build with args '-Dhttp.proxyHost=squid.lax.liferay.com -Dhttp.proxyPort=3128 :backend-integration-service:buildService' in directory '/tmp/junit3989452755029312001/backend-integration'
java.lang.IllegalStateException: An error occurred executing build with args '-Dhttp.proxyHost=squid.lax.liferay.com -Dhttp.proxyPort=3128 :guestbook-service:buildService' in directory '/tmp/junit1744602609130888170/guestbook'
java.lang.IllegalStateException: An error occurred executing build with args '-Dhttp.proxyHost=squid.lax.liferay.com -Dhttp.proxyPort=3128 :build' in directory '/tmp/junit6936586529631063027/foo'
```
See the detailed results here: https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/39117/ (I got here by clicking on test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8 in the github comment above)

@brianchandotcom please do not merge

**Comment by jbalsas** [comment]
Hey @jpince, this PR only changes one `.js` file... I really don't see how this could cause any of these:

```
java.lang.IllegalStateException: An error occurred executing build with args '-Dhttp.proxyHost=squid.lax.liferay.com -Dhttp.proxyPort=3128 :backend-integration-service:buildService' in directory '/tmp/junit3989452755029312001/backend-integration'
java.lang.IllegalStateException: An error occurred executing build with args '-Dhttp.proxyHost=squid.lax.liferay.com -Dhttp.proxyPort=3128 :guestbook-service:buildService' in directory '/tmp/junit1744602609130888170/guestbook'
java.lang.IllegalStateException: An error occurred executing build with args '-Dhttp.proxyHost=squid.lax.liferay.com -Dhttp.proxyPort=3128 :build' in directory '/tmp/junit6936586529631063027/foo'
```

Should we retest?

**Comment by jpince** [comment]
@jbalsas you are correct:
[7:55:05 AM] Lawrence Lee: his pull has nothing to do with the project templates test
[7:55:25 AM] Lawrence Lee: the project templates test failed likely because of a network outage
[7:55:38 AM] Lawrence Lee: Caused by: java.net.UnknownHostException: downloads.gradle.org
Thanks @lawrence-lee

ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by Ithildir** [comment]
Hi @jpince and @lawrence-lee, I sent a pull to Brian with a fix: https://github.com/brianchandotcom/liferay-portal/pull/43163

**Pull request closed without merging**
