### PR TITLE
LPS-78308

### PR DESCRIPTION
**Pull request by petershin**
@hhuijser

### CODE REVIEW

**Comment by petershin** [comment]
ci:test

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test

**Comment by petershin** [comment]
ci:open

**Comment by petershin** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/037088380d...4dff3af031

**Comment by hhuijser** [comment]
@petershin, will you work on fixing all the violations in watson?

**Comment by hhuijser** [comment]
nvm, I see you already did :)

**Pull request closed without merging**
