### PR TITLE
LPS-80145 Increase line number

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/35c82c2ca8...81614516d1

**Comment by brianchandotcom** [comment]
@ealonso we haven't had to add a new p_l_* var in a long long long time.. but I suppose this is necessary for the new WEM. Trusting you on this!

**Pull request closed without merging**
