### PR TITLE
LPS-65388 User with permission to VIEW users cannot view it

### PR DESCRIPTION
**Pull request by pei-jung**
Hi @brianchandotcom,

This is the test for https://github.com/brianchandotcom/liferay-portal/pull/39257.

### CODE REVIEW

**Comment by kenjiheigel** [comment]
Failures are unrelated to this pull. Failing functional tests have been disabled in liferay@897964d^...03e5cb7.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/47fa9a6bee...b801076e88

**Comment by brianchandotcom** [comment]
@pei-jung can you resend? This test shoudln't be in UserLocalServiceUtil;, but it should be in UserPermission*Test

Thx

**Comment by pei-jung** [comment]
PR resent as https://github.com/brianchandotcom/liferay-portal/pull/39842.

**Pull request closed without merging**
