### PR TITLE
LPS-74879 We don't need to expose this class

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by jpince** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c2f554b1bd...a8e645e811

**Comment by brianchandotcom** [comment]
@ealonso I merged this, but I think you should rename

edit_menu.jsp
DeleteMenuMVCActionCommand.java
EditMenuMVCActionCommand.java

and namespace them. Can you send me a follow up pull? Thx. @ealonso

**Pull request closed without merging**
