### PR TITLE
LPS-90293 In case of Documents the FileEntryTypeId is stored instead of the StructureId

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by jpince** [comment]
@pavel-savinov @moltam89 int test console errors, can you please take a look?
```
     [exec] com.liferay.asset.list.staging.test.AssetListEntryStagingTest > testPublishCreateAssetListWithSegments STARTED
     [exec] 
     [exec] 08:35:45,703 ERROR [com.liferay.asset.list.test-executor-thread][UnicodeProperties:119] Invalid property on line 7eMLmd83
     [exec] Invalid property on line 7eMLmd83
     [exec] 
...
     [exec] com.liferay.asset.list.staging.test.AssetListEntryStagingTest > testPublishDeleteAssetListWithSegments STARTED
     [exec] 
     [exec] 08:35:48,525 ERROR [com.liferay.asset.list.test-executor-thread][UnicodeProperties:119] Invalid property on line XyZMBgq0
     [exec] Invalid property on line XyZMBgq0
```
cc/ @brianchiu @kyle-miho

**Comment by moltam89** [comment]
I think this should solve the issue with the console errors.

https://github.com/pavel-savinov/liferay-portal/pull/360

**Comment by jpince** [comment]
@kyle-miho @brianchiu @pavel-savinov do you want to cherry-pick Tamas' change with these commits and test? And/or send them all to BChan together?

**Comment by pavel-savinov** [comment]
@jpince @kyle-miho @brianchiu @moltam89 Reset here: https://github.com/brianchandotcom/liferay-portal/pull/73402

Thanks guys!

**Pull request closed without merging**
