### PR TITLE
LPS-72152

### PR DESCRIPTION
**Pull request by Ithildir**
Hi,
Please let this pull finish.

Thank you!

cc @Robert-Frampton

### CODE REVIEW

**Comment by jpince** [comment]
@Ithildir @robert-frampton @jbalsas error in modules-compile:
`     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:foundation:frontend-js:frontend-js-web:npmInstall'.`
is this an issue?

**Comment by jpince** [comment]
the db2/hypersonic/postgre issues are unrelated.

**Comment by jbalsas** [comment]
Hey @jpince, that definitely looks like an issue :(

**Comment by jpince** [comment]
ok, sorry!

**Comment by jpince** [comment]
ci:close

**Pull request closed without merging**
