### PR TITLE
LPS-84119

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by jpince** [comment]
@hhuijser these test failure look related
int - all tests in BlogsEntrySharingTest failing:
```
java.util.NoSuchElementException
	at java.util.Collections$EmptyIterator.next(Collections.java:4189)
	at com.liferay.sharing.test.util.BaseSharingTestCase._getServiceReference(BaseSharingTestCase.java:920)
	at com.liferay.sharing.test.util.BaseSharingTestCase._getPermissionSQLContributor(BaseSharingTestCase.java:904)
	at com.liferay.sharing.test.util.BaseSharingTestCase.setUp(BaseSharingTestCase.java:110)
```

modules-unit test compile failure:
```
      [exec] /opt/dev/projects/github/liferay-portal/modules/apps/user-associated-data/user-associated-data-web/src/test/java/com/liferay/user/associated/data/web/internal/display/DummyEntryUADDisplay.java:20: error: DummyEntryUADDisplay is not abstract and does not override abstract method isInTrash(DummyEntry) in UADDisplay
     [exec] public class DummyEntryUADDisplay extends DummyUADDisplay<DummyEntry> {
     [exec]        ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/user-associated-data/user-associated-data-web/src/test/java/com/liferay/user/associated/data/web/internal/display/DummyContainerUADDisplay.java:25: error: DummyContainerUADDisplay is not abstract and does not override abstract method isInTrash(DummyContainer) in UADDisplay
     [exec] public class DummyContainerUADDisplay extends DummyUADDisplay<DummyContainer> {
     [exec]        ^
     [exec] Note: /opt/dev/projects/github/liferay-portal/modules/apps/user-associated-data/user-associated-data-web/src/test/java/com/liferay/user/associated/data/web/internal/display/DummyService.java uses unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 2 errors
     [exec] 
     [exec] > Task :apps:user-associated-data:user-associated-data-web:compileTestJava FAILED
```

@patriciajeanperez I believe `user-associated-data` is owned by USM, close this ticket if your team would like the test compile failure to be fixed before merging.
cc/ @hanlf

**Comment by jpince** [comment]
@hanlf updated the above comment, the same BlogsEntrySharingTest failure is present in some batches in [this pull](https://github.com/brianchandotcom/liferay-portal/pull/75068#issuecomment-506677363). So this is probably a flaky test. 
```
java.util.NoSuchElementException
	at java.util.Collections$EmptyIterator.next(Collections.java:4189)
	at com.liferay.sharing.test.util.BaseSharingTestCase._getServiceReference(BaseSharingTestCase.java:920)
	at com.liferay.sharing.test.util.BaseSharingTestCase._getPermissionSQLContributor(BaseSharingTestCase.java:904)
	at com.liferay.sharing.test.util.BaseSharingTestCase.setUp(BaseSharingTestCase.java:110)
```
cc/ @timpak in case you come across this. Collab can investigate and file a ticket.

**Comment by jpince** [comment]
failures are unrelated, already exist in usptream

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by Hanlf** [comment]
Thanks @jpince !
Here is the ticket about BlogsEntrySharingTest failure: https://issues.liferay.com/browse/LPS-97619

**Pull request closed without merging**
