### PR TITLE
LPS-69247

### PR DESCRIPTION
**Pull request by Ithildir**
Rebased on top of https://github.com/brianchandotcom/liferay-portal/pull/56720 to avoid conflicts.

cc @CAustin582

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:test

**Comment by Ithildir** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@codyhoag fyi changelog Thx

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/42bef0bee8...b5f30eb844

**Pull request closed without merging**
