### PR TITLE
LPS-74728 Pass the fieldSetClassNameId to the form-builder taglib

### PR DESCRIPTION
**Pull request by rafaprax**
\cc @leoadb @vicnate

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Lots of modules-int errors? Please resend.

**Comment by rafaprax** [comment]
Hey @vicnate5, are these errors related to this pr? Could you help me to understand the report?

Thx

**Comment by rafaprax** [comment]
resent at https://github.com/brianchandotcom/liferay-portal/pull/52497

**Pull request closed without merging**
