### PR TITLE
LPS-77432

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-77432

Note that there is a "fake gradle cache" commit. I'd originally had it without the LPS ticket number on https://github.com/brianchandotcom/liferay-portal/pull/55398

This is also a re-send of https://github.com/brianchandotcom/liferay-portal/pull/55429 where I forgot that `build.gradle` also needs to satisfy source formatting rules.

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@holatuwol please resend based on our emails. Thx.

**Comment by IstvanD** [comment]
Hello,

I wanted to inquire if the pull request of the newest version of the solution has sent.

Thank you and best regards,
István

**Comment by holatuwol** [comment]
@IstvanD: Not yet, I will send it today.

**Comment by IstvanD** [comment]
Many thanks @holatuwol !

**Pull request closed without merging**
