### PR TITLE
LRIS-25643

### PR DESCRIPTION
**Pull request by lionah**

### CODE REVIEW

**Comment by lionah** [comment]
ci:reopen

**Comment by lionah** [comment]
@jpince, me?

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
hard for me to say, I'm not familiar with backend tests. It is suspicious that the same test failed on all modules-int* batches (and I don't see this in other pulls), but your results are also stale. So let the retest tell all...

**Comment by jpince** [comment]
oh, the failure in modules-int* is definitely yours
WeDeployAuthAppPersistenceTest.classMethod
`java.io.IOException: Start of bundle with id 630 failed with message: Could not resolve module: com.liferay.portal.security.wedeploy.auth.test [630]
  Unresolved requirement: Import-Package: com.liferay.portal.security.wedeploy.auth.exception`

**Comment by jpince** [comment]
ci:close

**Pull request closed without merging**
