### PR TITLE
Lps 71925

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
CC @Ithildir @jpince

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@Preston-Crary I want to simplify this with a mega hack by keeping all the changes in BasePersistenceImpl.

1.) Rename getDBColumnNames to a private method called _getDBColumnNamesMap

2.) That method should call getModelClass() already available in BasePersistenceImpl.

Via reflection, read, "TABLE_COLUMNS" and grab the DB column names.

Create a new instance. Call toString(). Parse the JSON for the column names. Order will allow you to pair them up.

Cache this map as a private variable.

3.) Use this new method in BasePersistenceImpl#getColumnName

No build.gradle changes and no regeneration!

Thx.

**Comment by brianchandotcom** [comment]
@Preston-Crary I just realized that getModelClass returns the interface, but you can still use the naming convention and figure out the Impl, and it should be in the same class loader as the PersistenceImpl itself, so you should be able to load it. Yes, mega hack.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/4133

**Pull request closed without merging**
