### PR TITLE
LPS-126415 Fix Rebase

### PR DESCRIPTION
**Pull request by david-gutierrez-mesa**
Rebase from #98305

### CODE REVIEW

**Comment by david-gutierrez-mesa** [comment]
Rebase from #98305

**Comment by david-gutierrez-mesa** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/89aae6b0f6...0f586fc987

**Comment by brianchandotcom** [comment]
@victortrajano fyi. please review changes.

**Pull request closed without merging**
