### PR TITLE
LPS-54586 - Run gradlew buildSystemPackagesExtraManifest

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by daviddotzhang** [comment]
ci:retest

**Comment by daviddotzhang** [comment]
Hi Brian,

Could you kindly set this a high priority ?

Thanks,
David.

**Comment by brianchandotcom** [comment]
portal-kernel/src/com/liferay/portal/kernel/repository/packageinfo changed from 7.1.0 to 8.0.0

You can't introduce a breaking change. Please resend @adolfopa @daviddotzhang

**Comment by daviddotzhang** [comment]
@adolfopa , could you help me  on this ?

**Pull request closed without merging**
