### PR TITLE
LPS-66028

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by sharonchoi** [comment]
investigating poshi failures

**Comment by sharonchoi** [comment]
@kenjiheigel for CPWiki#EditWikiNode and ExportImport#ExportImportSiteWithChangedSiteDefaultLanguage and DynamicdatalistsUsecase#AddRecordWithRepeatableTextField there is a freemarker error, where it's unable to load the product menu taglib:
`  [exec]     ###
     [exec]     ### CPWiki#EditWikiNode
     [exec]     ###
     [exec] 
     [exec] 17:57:09,592 ERROR [http-nio-8080-exec-2][FreeMarkerManager:193] Unable to add taglib liferay_product_navigation to context
     [exec] FreeMarker template error:
     [exec] freemarker.template.TemplateModelException: Error while loading tag library for URI "/META-INF/liferay-product-navigation.tld" from TLD location "servletContext:/META-INF/liferay-product-navigation.tld"; see cause exception.
     [exec] 	at freemarker.ext.jsp.TaglibFactory.get(TaglibFactory.java:260)
     [exec] 	at com.liferay.portal.template.freemarker.FreeMarkerManager$TaglibFactoryWrapper.get(FreeMarkerManager.java:633)
     [exec] 	at com.liferay.portal.template.freemarker.FreeMarkerManager.addTaglibSupport(FreeMarkerManager.java:190)
     [exec] 	at com.liferay.taglib.util.ThemeUtil.doIncludeFTL(ThemeUtil.java:274)
     [exec] 	at com.liferay.taglib.util.ThemeUtil.doDispatch(ThemeUtil.java:157)
     [exec] 	at com.liferay.taglib.util.ThemeUtil.includeFTL(ThemeUtil.java:100)
     [exec] 	at com.liferay.taglib.util.ThemeUtil.include(ThemeUtil.java:82)
     [exec] 	at com.liferay.taglib.theme.WrapPortletTag.doEndTag(WrapPortletTag.java:101)
     [exec] 	at org.apache.jsp.html.common.themes.portlet_jsp._jspService(portlet_jsp.java:4337)
     [exec] 	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
     [exec] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
     [exec] 	at com.liferay.portal.servlet.DirectRequestDispatcher.include(DirectRequestDispatcher.java:64)
     [exec] 	at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.doDispatch(ClassLoaderRequestDispatcherWrapper.java:78)
     [exec] 	at `

For CPSitememberships#OrganizationsView is failing from an elastic search error:
`     [exec]     ###
     [exec]     ### CPSitememberships#OrganizationsView
     [exec]     ###
     [exec] 
     [exec] 
     [exec] com.liferay.poshi.runner.PoshiRunner > test[CPSitememberships#OrganizationsView] STANDARD_OUT
     [exec]     Checking to see if TCat is enabled...
     [exec] 17:53:58,662 INFO  [elasticsearch[Gargoyle][clusterService#updateTask][T#1]][metadata:317] [Gargoyle] [liferay-20116] update_mapping [LiferayDocumentType]
     [exec] 17:53:58,666 INFO  [elasticsearch[Gargoyle][clusterService#updateTask][T#1]][metadata:317] [Gargoyle] [liferay-20116] update_mapping [LiferayDocumentType]
     [exec]     5987 Launcher
     [exec]     13764 Jps
     [exec]     12837 GradleWrapperMain
     [exec]     12873 GradleWorkerMain
     [exec]     12378 Bootstrap
     [exec]     Bootstrap PID: 12378
     [exec]     2016-05-23 10:56:15
     [exec]     Full thread dump Java HotSpot(TM) Server VM (25.51-b03 mixed mode):
     [exec] 
     [exec]     "Attach Listener" #279 daemon prio=9 os_prio=0 tid=0x62c02000 nid=0x35ee waiting on condition [0x00000000]
     [exec]        java.lang.Thread.State: RUNNABLE
     [exec] 
     [exec]        Locked ownable synchronizers:
     [exec]     	- None
     [exec] 
     [exec]     "elasticsearch[Gargoyle][suggest][T#3]" #278 daemon prio=5 os_prio=0 tid=0x5731cc00 nid=0x3575 waiting on condition [0x3f0c3000]
     [exec]        java.lang.Thread.State: WAITING (parking)
     [exec]     	at sun.misc.Unsafe.park(Native Method)
     [exec]     	- parking to wait for  <0x7244ecd0> (a java.util.concurrent.LinkedTransferQueue)
     [exec]     	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
     [exec]     	at java.util.concurrent.LinkedTransferQueue.awaitMatch(LinkedTransferQueue.java:737)
     [exec]     	at java.util.concurrent.LinkedTransferQueue.xfer(LinkedTransferQueue.java:647)
     [exec]     	at java.util.concurrent.LinkedTransferQueue.take(LinkedTransferQueue.java:1265)
     [exec]     	at org.elasticsearch.common.util.concurrent.SizeBlockingQueue.take(SizeBlockingQueue.java:161)
     [exec]     	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
     [exec]     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
     [exec]     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [exec]     	at java.lang.Thread.run(Thread.java:745)
     [exec] 
     [exec]        Locked ownable synchronizers:
     [exec]     	- None
     [exec] `

**Comment by sharonchoi** [comment]
ci:retest

**Comment by sharonchoi** [comment]
ci:stop

@brianchandotcom this pull is good to merge.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
