### PR TITLE
master-qa-16080

### PR DESCRIPTION
**Pull request by michaelhashimoto**
http://issues.liferay.com/browse/LRQA-16080

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cbc5ab2f9b...a197d3a616

**Comment by brianchandotcom** [comment]
@michaelhashimoto what about poshi? dont' we have to copy this over?

**Comment by brianchandotcom** [comment]
@michaelhashimoto also, see my changes in 527da2a9cef92090972d625a9deb00cc8cc15216 Thx

**Comment by michaelhashimoto** [comment]
@brianchandotcom - I copied this one over from poshi runner.  I'll make the SF you made in here in Poshi Runner too.

**Pull request closed without merging**
