### PR TITLE
LPS-50933 - fix redirections of language portlet

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by kiyoshilee** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:restest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by kiyoshilee** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4028414de1...762d278e63

**Pull request closed without merging**
