### PR TITLE
LPS-91420

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@brianchandotcom, I'll take care of any backports

**Comment by hhuijser** [comment]
@ci:reopen

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
Did I break PortalPreferencesImplTest?

**Comment by brianchandotcom** [comment]
@hhuijser regarding PortalPreferencesImplTest (may be?)

I'm publishing a new java parser/SF util.

**Pull request closed without merging**
