### PR TITLE
COMMERCE-5483 commcerce-shop-by-diagram 1 of 5

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
resend of this https://github.com/liferay-commerce/liferay-portal/pull/1300 , just fixed the commit author.

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:reopen

**Comment by andrea-ale-sbarra** [comment]
@garofalog to follow up, thanks!

**Comment by brianchandotcom** [comment]
@andrea-ale-sbarra this is a very strange file name

modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-web/test/dev/public/js/static-env-utils.js

Has someone else from frontend reviewed to make sure the code here adheres to our standards?

Same here

modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-web/src/main/resources/META-INF/resources/style/icons.svg

and

git ls-files **/style/**.scss

This is the first time I've ever seen a style directory.

Same for the content in 

modules/dxp/apps/commerce/commerce-shop-by-diagram/commerce-shop-by-diagram-web/test/dev/public/index.html

In general, please make sure @garofalog is not inventing any new patterns. Everything he does out to follow an existing pattern. Thx.

**Comment by garofalog** [comment]
Hello @brianchandotcom,
there are these files because we decided to divide the Diagram functionality in five different prs. Every pr it's made by the same kind of functionalities linked together, documented in our user stories. We are making this to cut all the functionalities in different and more reviewable prs. We need icon file, html file and scss file to keep developing all the frontend part before we wrap it all in a jsp component and at the same time have can test all the real apis endpoint. We should remove all the static env files before step 4 of 5, when the module should be ready and startable. We have been addressing this issue lately trying to find a common solution to be able to easily develop frontend components following the liferay patterns.  For this reason at this time this module it's hidden from liferay startable modules.

**Comment by brianchandotcom** [comment]
@garofalog I'm fine with those files, I'm just saying they have to be named and in the same directory as our existing code.

**Comment by brianchandotcom** [comment]
@garofalog when I say existing code, I mean existing patterns. - vs. _ etc. Or /css/ vs. /style/

I'm not even sure what they are, but they don't smell the same as our existing JS / HTML code.

**Pull request closed without merging**
