### PR TITLE
LPS-57728 Tie all existing OSGi portlets to their upgrade process

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:retest

**Comment by izaera** [comment]
ci:retest

**Comment by izaera** [comment]
@brianchandotcom I have run tests once again because failures are totally inconsistent. Also, I don't get any errors in local so I don't see any way to reproduce the failures and/or fix them from here. What is exactly scanLog testing? The PR doesn't change anything apart from service dependencies. Nothing should fail.

**Comment by brianchandotcom** [comment]
@izaera too many scan log errors. Please resend.

**Pull request closed without merging**
