### PR TITLE
LPS-138137 - Update @liferay/npm-scripts

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Manual forward from https://github.com/liferay-frontend/liferay-portal/pull/1413

QA sign off: https://github.com/liferay-frontend/liferay-portal/pull/1413#issuecomment-908505122

-----

Jira: https://issues.liferay.com/browse/LPS-138137

This updates theme-tasks to properly handle RTL conversion for `translate`

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:open

**Comment by bryceosterhaus** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/738d8e63b4...66ec6b0ca1

**Comment by brianchandotcom** [comment]
@kevenleone see changes by @bryceosterhaus

**Pull request closed without merging**
