### PR TITLE
LPS-60355 We can't know which packages we need to import in advance

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d3e95bb8f1...d8a25cfe13

**Comment by brianchandotcom** [comment]
@csierra can you see if 7fe9559820f42e46db1f5f3cd76c387b6ca64c37 works? I simplified it.

**Comment by csierra** [comment]
Looks like it works!

**Pull request closed without merging**
