### PR TITLE
LPS-71378 SF

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
cc @marcellustavares @vicnate5

**Comment by leoadb** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ca382cdbc6...0a7142433f

**Comment by brianchandotcom** [comment]
@leoadb can you see my changes in upstream and apply them else where ? Merged. Thx.

**Pull request closed without merging**
