### PR TITLE
LPS-197143

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:reopen

**Comment by marianoalvarosaiz** [comment]
QA Tests OK: https://github.com/liferay-uniform/liferay-portal/pull/1461#issuecomment-1751477726

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3f610aea9c...28247c09cf

**Comment by brianchandotcom** [comment]
@marianoalvarosaiz see changes in my origin.

**Pull request closed without merging**
