### PR TITLE
LPS-74083

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by yuhai** [comment]
ci:reopen

**Comment by yuhai** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@yuhai can you resend?

1.) avoid

```
do {
}
while (true)
```

I think

```
while (true) {
}
```

Would have been just fine.

2.) Can you have @hhuijser go over the comments? They don't make much sense (grammatically).

Thx!

**Comment by matethurzo** [comment]
hey @brianchandotcom is there any reason for us avoiding do while statements?

i developed that part, so I can rewrite it too.

also the comment part is my bad, sorry :(

**Pull request closed without merging**
