### PR TITLE
LRQA-57119 Reducing the relevant test scope of DDM, DDL and DE projects

### PR DESCRIPTION
**Pull request by alexcandidos**

### CODE REVIEW

**Comment by alexcandidos** [comment]
ci:reopen

**Comment by alexcandidos** [comment]
FYI @leoadb .

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/af0499db31...525a093cd0

**Comment by brianchandotcom** [comment]
@victorware fyi

**Comment by alexcandidos** [comment]
@vicnate5 fyi... ;)

**Pull request closed without merging**
