### PR TITLE
Lps 113779

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7f1f27f7b0...3778f8decf

**Comment by brianchandotcom** [comment]
@nhpatt I backported this to 7.1.x

**Comment by nhpatt** [comment]
Thanks!

**Pull request closed without merging**
