### PR TITLE
LPS-96637 update library that fixes a bug that allows us to remove so…

### PR DESCRIPTION
**Pull request by javiergamarra**
…me custom code

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@nhpatt yey! We contributed to GraphQL :) Good job!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/097f0f3236...57706198c7

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by nhpatt** [comment]
Thanks! :D

**Pull request closed without merging**
