### PR TITLE
LPS-173768 Allow the users to define the default utility page for each type in site initializer 

### PR DESCRIPTION
**Pull request by Tim-Cao**
This is only for master.

https://issues.liferay.com/browse/LPS-173768

@jkappler

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/10935

**Comment by jkappler** [comment]
will fix conflicts and resend

**Comment by jkappler** [comment]
ci:close

**Pull request closed without merging**
