### PR TITLE
LPS-59564 Fix path for compileJSP

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@juliocamarero @drewbrokke this is why the JSP errors weren't showing. Good job fixing it @Ithildir

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/669bee92f2...55330c8137

**Comment by brianchandotcom** [comment]
@juliocamarero I fixed your JSPC error from LPS-59564 55330c8137ad4a3b574c159e28c2991cbeac17d3

Can you review? It was picked up once we fixed jspc compile errors from this pull.

**Comment by juliocamarero** [comment]
@brianchandotcom thanks a lot! We sent you another pull with the review: https://github.com/brianchandotcom/liferay-portal/pull/32070

**Pull request closed without merging**
