### PR TITLE
LPS-69144 SF

### PR DESCRIPTION
**Pull request by marcellustavares**
cc @leoadb

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@marcellustavares merged... fixed Ci issue in upstream.

**Comment by marcellustavares** [comment]
thx @brianchandotcom

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/dbae8cb33c...2ac3aa5f85

**Comment by brianchandotcom** [comment]
@marcellustavares see 2ac3aa5f853a5ebee0121b2fbb0c60c831d167e4 @leoadb

**Pull request closed without merging**
