### PR TITLE
LPS-56702 Apply new settings framework in Web Content Service and Web Content Administration OSGI Modules

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @jkappler

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d73a3ab69e...a2aa6a7858

**Comment by brianchandotcom** [comment]
@jkappler 

1.) can you make the *.tmpl change (removal of br) everywhere?

2.) See a2aa6a78589ac13f5168845beee53338d7991d74 I'm not sure if my change is right.

**Pull request closed without merging**
