### PR TITLE
LPS-54098 Make sure that the components are inmediate so they are included even if the module is deployed later

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Thx @sergiogonzalez @cgoncas ! Mucho gracias.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b5cb3b9cfd...dc5c49ce72

**Pull request closed without merging**
