### PR TITLE
master-qa-20324

### PR DESCRIPTION
**Pull request by michaelhashimoto**
http://issues.liferay.com/browse/LRQA-20324

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2969e684a5...f2b4d5141c

**Comment by brianchandotcom** [comment]
@michaelhashimoto @kevin-yen please review my changes in upstream. Thx.

**Comment by brianchandotcom** [comment]
@michaelhashimoto @kevin-yen I had to disable it for now, when I run "ant format-source", I get this:

/Users/brian/dev/projects/github/liferay-portal/portal-impl/build.xml:14: The following error occurred while executing this line:
/Users/brian/dev/projects/github/liferay-portal/build-common-java.xml:4: The following error occurred while executing this line:
/Users/brian/dev/projects/github/liferay-portal/build-common.xml:94: java.lang.ClassCircularityError: java/lang/String
	at com.liferay.ant.build.logger.LiferayBuildLogger.messageLogged(LiferayBuildLogger.java:43)
	at org.apache.tools.ant.Project.fireMessageLoggedEvent(Project.java:2248)
	at org.apache.tools.ant.Project.fireMessageLogged(Project.java:2284)
	at org.apache.tools.ant.Project.log(Project.java:467)
	at org.apache.tools.ant.Project.log(Project.java:456)
	at org.apache.tools.ant.AntClassLoader.log(AntClassLoader.java:401)
	at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1073)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at com.liferay.ant.build.logger.LiferayBuildLoggerInstallerTask.execute(LiferayBuildLoggerInstallerTask.java:54)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.helper.ProjectHelper2.parse(ProjectHelper2.java:169)
	at org.apache.tools.ant.taskdefs.ImportTask.importResource(ImportTask.java:222)
	at org.apache.tools.ant.taskdefs.ImportTask.execute(ImportTask.java:163)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.helper.ProjectHelper2.parse(ProjectHelper2.java:169)
	at org.apache.tools.ant.taskdefs.ImportTask.importResource(ImportTask.java:222)
	at org.apache.tools.ant.taskdefs.ImportTask.execute(ImportTask.java:163)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.helper.ProjectHelper2.parse(ProjectHelper2.java:180)
	at org.apache.tools.ant.ProjectHelper.configureProject(ProjectHelper.java:93)
	at org.apache.tools.ant.Main.runBuild(Main.java:826)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

**Pull request closed without merging**
