### PR TITLE
Lps 59425

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @topolik there is no logic change, just rewriting to not use regex. Just FYI, in case you see something that's odd.

@dantewang @slnn, performance check please.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@shuyangzhou can you backport this to ee-6.2.x? The original ticket had it all the way to 6.2. I backported it to 7.0 already. Thx.

**Comment by shuyangzhou** [comment]
@tomwang2011 add this to your list, we have to list out all performance improvements we made since last week, most of them should be back ported.

**Comment by topolik** [comment]
Good job! Thanks :)

**Pull request closed without merging**
