### PR TITLE
LPS-87167 Apply to sample

### PR DESCRIPTION
**Pull request by epgarcia**
Hi @brianchandotcom,

Thanks for your feedback in #72972#issuecomment-491312193. I think that "ODataSearchAdapter" might be a good name, since we're adapting OData search to Liferay Search here. What do you think?

### CODE REVIEW

**Comment by jpince** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
@jpince the error with the jsdoc is unrelated to my changes, and it's fixed by this other PR: #brianchandotcom/liferay-portal/pull/73020

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@epgarcia sorry I didn't get to it today. Can you resend and reorder:

```
	public Hits search(
			long companyId, String filterString, String className,
			EntityModel entityModel, FilterParser filterParser, Locale locale,
			int start, int end)
		throws PortalException;

	public int searchCount(
			long companyId, String filterString, String className,
			EntityModel entityModel, FilterParser filterParser, Locale locale)
		throws PortalException;
```


to

```
	public Hits search(
			long companyId, FilterParser filterParser, String filterString, String className,
			EntityModel entityModel, Locale locale,
			int start, int end)
		throws PortalException;

	public int searchCount(
			long companyId, FilterParser filterParser, String filterString, String className,
			EntityModel entityModel, Locale locale)
		throws PortalException;
```

Thx!

**Comment by epgarcia** [comment]
@brianchandotcom no problem, see #73152. Thanks

**Pull request closed without merging**
