### PR TITLE
LPS-57450 Show product menu only when the setup user is complete

### PR DESCRIPTION
**Pull request by juliocamarero**
cc @ealonso

### CODE REVIEW

**Comment by juliocamarero** [comment]
@ZoltanTakacs can we add this one to 7.0.x ?

it is a bug in the product menu, thanks!

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@ealonso please resend. Logic should be in the menu itself or in the macro definition. Otherwise, each theme is duplicating logic. Thx @juliocamarero

**Pull request closed without merging**
