### PR TITLE
LPS-63730 Minimize synchronization to avoid deadlocks

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
ci:retest

**Comment by csierra** [comment]
is this failure related to my fix?

**Comment by brianchandotcom** [comment]
@csierra no it's not, looks like KB is not compiling as a plugin.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7825119a3b...9ce0739dce

**Comment by shuyangzhou** [comment]
@csierra Can you explain a bit about the race condition you are fixing?
The fix seems more complex than it should be, but I can only be sure, if I understand what you are dealing with.

**Comment by michaelhashimoto** [comment]
@brianchandotcom @pyoo47 @kiyoshilee

I'm going to re-run this one w/ 'set -x' to show which commands are running.

Hopefully this will give us more insight into what is happening.

**Comment by csierra** [comment]
hey @shuyangzhou,

the problem I found happened because inside the synchronized block we were registering a service. This borrows the thread that registers the service to do all the work derived of the registration of that service. Other threads may also change the readyness of any portlet, such as fileinstall or gogo shell, and those will block regardless of the portlet they are changing. This may lead to a deadlock since we can't foresee the amount of work that is going to be done in `registerService(Portlet.class,...)`. I actually managed to deadlock the portal easily while using hypersonic (which seems very restrictive with respect to locks). I understand that the isolation is only needed when two threads are trying to modify the same `rootPortletId`. I know hypersonic is not for production use, but I guess it can happen with any other resource, so I preferred to remove the global lock.

**Comment by shuyangzhou** [comment]
I am confused. Is the deadlock a jvm deadlock or database deadlock? How is hsql playing any part of it, while you are doing jvm level locking?

**Comment by csierra** [comment]
A jvm deadlock. Hypersonic seems to lock a table when the first session modifies a table. If a second session tries to modify that table it is held until the first session commits the transaction. If, by chance, the first session thread from the DB perspective is also the second thread from the `setReady` perspective we have a deadlock, because both threads are waiting for each other forever.

**Comment by shuyangzhou** [comment]
I am even lost. You said jvm deadlock. But it happens inside HSQL, so it is a db deadlock.

Just because HSQL lives inside the same jvm as portal, it does not make a db deadlock a jvm deadlock.

If this is really a db deadlock, then this entire locking solution inside jvm is wrong. It must be solved at db level. Because other dbs might have the same issue, and other DBs are real ones than can be used in cluster, then the jvm level locking won't fix anything.

**Comment by csierra** [comment]
it happens both inside HSQL and `setReady`.

One thread starts a session and inserts data into a table, later that thread tries to `setReady` a portlet. Another thread is setting a portlet ready, so it has the lock, as a result of setting the portlet ready it registers a service of type `Portlet.class` into the OSGi registry. This unchains a cascade of operations, including the thread trying to modify the same table as the first one. Thus locking in the table. Since the first thread is waiting on the lock in `setReady` and the second is waiting on the lock on the table we have a jvm deadlock. 

It does not need to be HSQLDB. It can happen with any other synchronized resource. I just discovered this because of HSQLDB, but it will happen with any other resource.

**Comment by shuyangzhou** [comment]
Now I think I know what's going on.

I did not realize there was a synchronized block there before your changes. I thought you added it.

See https://github.com/csierra/liferay-portal/pull/221

Please test to confirm whether it fixes the problem or not, if it does, please forward it to @brianchandotcom

**Pull request closed without merging**
