### PR TITLE
LPS-177563

### PR DESCRIPTION
**Pull request by Tim-Cao**
This is only for master.

https://issues.liferay.com/browse/LPS-177563

@ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/11383

**Comment by ealonso** [comment]
FYI: @achaparro

**Comment by brianchandotcom** [comment]
-150k lines of code is nice..... @ealonso

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b6c0c05339...67a25a697d

**Pull request closed without merging**
