### PR TITLE
LPS-173447 - Add theme spritemap client extension examples for sample-workspace

### PR DESCRIPTION
**Pull request by bryceosterhaus**
rebased from original PR: https://github.com/brianchandotcom/liferay-portal/pull/131870

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:reopen

**Comment by bryceosterhaus** [comment]
Hey @brianchandotcom, is there anything else needed here for this sample?

**Comment by brianchandotcom** [comment]
@bryceosterhaus will resend based on our call.

**Comment by dsanz** [comment]
Final pr: https://github.com/brianchandotcom/liferay-portal/pull/132303

**Pull request closed without merging**
