### PR TITLE
LPS-76165 Auto

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
@brianchandotcom Resent from https://github.com/brianchandotcom/liferay-portal/pull/53536 using Gradle to copy external resources.

@Ithildir Could you please take a look at LPS-76165 Copy resources from Flying Saucer core library because I'm not an expert in Gradle scripts.

cc @ealonso

**Comment by Ithildir** [comment]
Hi @pavel-savinov! I can take care of it once it's merged 😊

**Comment by brianchandotcom** [comment]
ci:test

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
1.) HtmlPreviewConstants needs to follow the pattern in RulesEngineConstants or KaleoRuntimeDestinationNames. Right now, you're creating a new pattern.

2.) For service.xml, the package is html.preview. Therefore, all entities must be HtmlPreview*, they cannot BE HtmlPreview. So HtmlPreviewEntry, or HtmlPreviewCollection, etc. We've gone over this pattern before @ealonso .

3.) InvalidMimeTypeException will need to be renamed as well.

Please resend. Thx.

**Pull request closed without merging**
