### PR TITLE
LPS-176210

### PR DESCRIPTION
**Pull request by tinatian**
FYI @shuyangzhou, this is the pull to remove counter data source. Tested start up and daily tests, no performance regression.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c60a14e061...d62a5dd08d

**Comment by shuyangzhou** [comment]
@tinatian please clean up all the counter datasource configuration info in build-test.xml. they start with "jdbc.counter." Like these https://github.com/liferay/liferay-portal/blob/master/build-test.xml#L632-L635

**Comment by shuyangzhou** [comment]
And those properties should be added to VerifyProperties too.

**Pull request closed without merging**
