### PR TITLE
LPS-166798 Object definitions were leaking to other Companies on the OAuth Scopes Page

### PR DESCRIPTION
**Pull request by mbowerman**
Manually forwarding due to unrelated ci failures based on @carolmariaabb's comment [here](https://github.com/liferay-objects/liferay-portal/pull/1276#issuecomment-1293622786).

https://issues.liferay.com/browse/LPS-166798

Sets the `companyId` property to take advantage of the existing filter on companyId in the OAuth Service Tracker [here](https://github.com/liferay/liferay-portal/blob/05589ddef153203dbdbff32dc459afac2f90963d/modules/apps/oauth2-provider/oauth2-provider-scope-impl/src/main/java/com/liferay/oauth2/provider/scope/internal/liferay/ScopedServiceTrackerMapFactoryImpl.java#L101)

Also see this comment that I left on the original pull request:

> Hi @gabrielwas,
> 
> We had a "companyId" pattern already that was being used by the OAuth module.
> 
> When I did [LPS-163914](https://issues.liferay.com/browse/LPS-163914) a few weeks ago, I added it as "company.id" instead of "companyId", because I wasn't aware of the existing "companyId" pattern at that time (and "company.id" seemed to match better with the other property names which were period-delimited).
> 
> We probably should standardize them at some point.

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:reopen

**Comment by carolmariaabb** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@mbowerman can you send a follow up PR and change "companyId" to "company.id" (meaning, change OAuth and all of its usages)

Thx!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/68a5dcca2a...9655002e89

**Pull request closed without merging**
