### PR TITLE
LPS-65406 ImageEditor Integration with item_selector

### PR DESCRIPTION
**Pull request by jbalsas**
Hey Brian,

This adds the necessary infrastructure for the future integrations with the `ImageEditor`. It also adds the minimum basic integration with the `ItemSelector`.

Thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/acea5d0b51...23281a7ff4

**Comment by brianchandotcom** [comment]
@jbalsas can you send a follow up pull and rename "editItemUrl" to "editItemURL"

Let's have it match "entityURL"

Thx.

**Comment by jbalsas** [comment]
Hey @brianchandotcom, followup sent to https://github.com/brianchandotcom/liferay-portal/pull/39500

Thanks!

**Pull request closed without merging**
