### PR TITLE
LPS-78136 Throws exception instead use try/catch block

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test

**Comment by timpak** [comment]
ci:close

**Comment by timpak** [comment]
hi @rafaprax, could you look into this please? Thanks!

     [exec] :apps:forms-and-workflow:dynamic-data-mapping:dynamic-data-mapping-form-web:compileJava FAILED
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-form-web/src/main/java/com/liferay/dynamic/data/mapping/form/web/internal/display/context/DDMFormAdminDisplayContext.java:594: error: unreported exception PortalException; must be caught or declared to be thrown
     [exec] 		return DDMFormInstancePermission.contains(
     [exec] 		                                         ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-form-web/src/main/java/com/liferay/dynamic/data/mapping/form/web/internal/display/context/DDMFormAdminDisplayContext.java:600: error: unreported exception PortalException; must be caught or declared to be thrown
     [exec] 		return DDMFormInstancePermission.contains(
     [exec] 		                                         ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-form-web/src/main/java/com/liferay/dynamic/data/mapping/form/web/internal/display/context/DDMFormAdminDisplayContext.java:606: error: unreported exception PortalException; must be caught or declared to be thrown
     [exec] 		return DDMFormInstancePermission.contains(
     [exec] 		                                         ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-form-web/src/main/java/com/liferay/dynamic/data/mapping/form/web/internal/display/context/DDMFormAdminDisplayContext.java:612: error: unreported exception PortalException; must be caught or declared to be thrown
     [exec] 		return DDMFormInstancePermission.contains(
     [exec] 		                                         ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-form-web/src/main/java/com/liferay/dynamic/data/mapping/form/web/internal/display/context/DDMFormAdminDisplayContext.java:618: error: unreported exception PortalException; must be caught or declared to be thrown
     [exec] 		return DDMFormInstancePermission.contains(
     [exec] 		                                         ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-form-web/src/main/java/com/liferay/dynamic/data/mapping/form/web/internal/display/context/DDMFormAdminDisplayContext.java:638: error: unreported exception PortalException; must be caught or declared to be thrown
     [exec] 		return DDMFormInstancePermission.contains(
     [exec] 		                                         ^

**Comment by rafaprax** [comment]
@timpak I'm going to take a look at this. Thx

**Pull request closed without merging**
