### PR TITLE
LPD-41445 Update app.bnd-localization for OpenSearch (Prep for Marketplace release)

### PR DESCRIPTION
**Pull request by lipusz**
https://liferay.atlassian.net/browse/LPD-41445

Hi Brian,

This has been wordsmith-ed by @rbohl :+1: Sending directly as I could not make it through CI on https://github.com/liferay-search/liferay-portal/pull/1557.

Thanks,
Tibor

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf

**Comment by brianchandotcom** [comment]
@lipusz the wording here is a mouthful. Please simplify. It doesn't sound right. You're saying too much.

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
@brianchandotcom That's similar to what we have in the Solr connector. I'd like to keep it as-is if possible. See https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-search-solr8/app.bnd-localization/bundle.properties

**Comment by brianchandotcom** [comment]
@lipusz I saw that, but this new one sounds off. The Solr one sounds right.

**Comment by lipusz** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/156789

**Pull request closed without merging**
