### PR TITLE
LPS-110763 Merge to the proper json object

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:reopen

**Comment by vicnate5** [comment]
@brianchandotcom fix for issue blocking upstream merge

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/703090de05...2219f42b33

**Pull request closed without merging**
