### PR TITLE
newMethods

### PR DESCRIPTION
**Pull request by wesleyroberts**

### CODE REVIEW

**Comment by wesleyroberts** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
ci:reopen

**Comment by wesleyroberts** [comment]
ci:test:sf

**Comment by brianchandotcom** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c0532b8e3c...a49c34d09d

**Pull request closed without merging**
