### PR TITLE
LPS-72221 Allow extension Gradle file in subrepo's settings.gradle

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:reopen

**Comment by pyoo47** [comment]
ci:stop

**Comment by Ithildir** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7a79ba3707...d9e9984484

**Pull request closed without merging**
