### PR TITLE
LPS-170159 Replace PUT request with PATCH request

### PR DESCRIPTION
**Pull request by devpedrotavares**
The errors in this [PR](https://github.com/liferay-objects/liferay-portal/pull/1655) are not related.

### CODE REVIEW

**Comment by devpedrotavares** [comment]
ci:open

**Comment by devpedrotavares** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e8d670a81d...41a3f0b71a

**Comment by brianchandotcom** [comment]
@devpedrotavares I merged this for now, but we actually have a bug with REST builder, you should not have had to override patchScopeScopeKeyByExternalReferenceCode

Can your team fix REST builder @4lejandrito, see this PR

BaseObjectEntryResourceImpl was generated 

```
	public ObjectEntry patchScopeScopeKeyByExternalReferenceCode(
			@io.swagger.v3.oas.annotations.Parameter(hidden = true)
			@javax.validation.constraints.NotNull
			@javax.ws.rs.PathParam("scopeKey")
			String scopeKey,
			@io.swagger.v3.oas.annotations.Parameter(hidden = true)
			@javax.validation.constraints.NotNull
			@javax.ws.rs.PathParam("externalReferenceCode")
			String externalReferenceCode,
			ObjectEntry objectEntry)
		throws Exception {

		ObjectEntry existingObjectEntry = getByExternalReferenceCode(scopeKey);
```

But it should have generated

```
	@Override
	public ObjectEntry patchScopeScopeKeyByExternalReferenceCode(
			String scopeKey, String externalReferenceCode,
			ObjectEntry objectEntry)
		throws Exception {

		ObjectEntry existingObjectEntry =
			getScopeScopeKeyByExternalReferenceCode(
				scopeKey, externalReferenceCode);
```

We manually overrode it in f34960a7

But we need a better fix.

Thx.

**Comment by carolmariaabb** [comment]
Hi @brianchandotcom, we already have a bug created for this  https://issues.liferay.com/browse/LPS-173450 and @4lejandrito is aware of this.

**Pull request closed without merging**
