### PR TITLE
LPS-84836 Not needed

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @kyle-miho, @ealonso

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/db4db5c4fd...c171b69997

**Comment by brianchandotcom** [comment]
@jkappler just a test.. I backported it for you.

**Comment by jkappler** [comment]
Thanks @brianchandotcom !

**Pull request closed without merging**
