### PR TITLE
LPS-85998 Baseline

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @adolfopa

**Comment by sergiogonzalez** [comment]
Hey @marcellustavares @ealonso @dejuknow @adolfopa 
I have updated some of the methods regarding permissions in some of the services in the components you own. No logic changes should be done in your services. This is the commit that changes it: https://github.com/brianchandotcom/liferay-portal/pull/64228/commits/b6d14acca0969df676dd8cd8012cdb0301534258
Please take a look at it and let @adolfopa know if there's anything wrong.
Thanks!

**Comment by marcellustavares** [comment]
cc @leoadb @rafaprax @pedroqueiroz

**Comment by sergiogonzalez** [comment]
Hey @jpince can you please confirm if the failure tests are related to this pull?
Thanks
cc/ @adolfopa

**Comment by jpince** [comment]
ci:reopen @sergiogonzalez looks ok as far as I can tell.

@leoadb @rafaprax @pedroqueiroz @alexcandidos I cannot analyze F&W POSHI test failures in pulls like this because there are too many failures in upstream, and I don't have time to keep track of them all. Are you guys going to fix these?
Same with this one https://github.com/brianchandotcom/liferay-portal/pull/64218

**Comment by brianchandotcom** [comment]
Wow @sergiogonzalez @adolfopa this is a nice and significant change. Not backporting of course. Merged.

**Comment by brianchandotcom** [comment]
@codyhoag fyi

**Pull request closed without merging**
