### PR TITLE
LPS-59076

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey Brian,

We only have a few cases left where we need to fix use @Reference instead of calling *ServiceUtil. However, it always takes a week or so for those to get reviewed and everything and by the time we have fixed those, new ones have been committed.

Introducing a temporary property, so we only ignore the ones that still need to be fixed (instead of skipping the check all together), so we don't end up with new incorrect ones all the time.

**Comment by hhuijser** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Thx @hhuijser

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e7b15ff0a7...e03bdb2e63

**Pull request closed without merging**
