### PR TITLE
Shard Tool: basic support

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by migue** [comment]
Not related, this is a completely independent module

ci:retest

**Comment by brianchandotcom** [comment]
@mdelapenya @migue portalImplLocale test failure is real. Please resend.

**Comment by mdelapenya** [comment]
We are not using nor changing portal code, it's a completely independent module with no relation to portal...

How could this be?

**Comment by migue** [comment]
Already ping you in Slack ... look at my message please!

On 13 January 2016 at 18:21, Manuel de la Peña <notifications@github.com>
wrote:

> We are not using nor changing portal code, it's a completely independent
> module with no relation to portal...
>
> How could this be?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/34306#issuecomment-171370034>
> .
>



-- 
Un saludo,

Migue

http://migue.github.io

**Pull request closed without merging**
