### PR TITLE
LPS-84717 Sort API

### PR DESCRIPTION
**Pull request by javiergamarra**
Rename following recommendations in https://github.com/brianchandotcom/liferay-portal/pull/62514/

/cc @cgoncas

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.

View just my changes: https://github.com/brianchandotcom/liferay-portal/compare/nhpatt:b0ac007f14...8b9f314e5e
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/519d1f2ed0...8b9f314e5e

**Comment by brianchandotcom** [comment]
@nhpatt thank you for getting back to me so quickly !

@cgoncas @nhpatt please see my changes in upstream. Please learn from them so I don't have to make those changes again. It's a lot of work for me. Thanks!

**Comment by nhpatt** [comment]
Thanks for reviewing it so quickly, we'll check the changes throughly. Thanks again for your time :)

**Comment by brianchandotcom** [comment]
@nhpatt sorry these headless-apio pulls are taking longer.. part of it is that you're now a very good dev, but you're still weak in enforcing what you already know.

So it's one skill to know, it's another skill to be able to enforce/teach. So my job is to teach you to teach in how you review other people's pulls. Once you learn that, then I can smile and relax :)

**Pull request closed without merging**
