### PR TITLE
LPS-77425 Remove project templates from 7.0.x, we're not forking them

### PR DESCRIPTION
**Pull request by Ithildir**
Hi,
Please let this pull finish.

Thank you!

cc @david-truong, @gamerson

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:test

**Comment by michaelhashimoto** [comment]
@Ithildir - I retested these ones, it failed prior to testing for some reason. :(

Here's the 2 retests:
https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest(7.0.x)/

**Comment by Ithildir** [comment]
@michaelhashimoto, can you please point me at the error log? Unfortunately I still get lost in Jenkins 😅 
Could it be because I'm completely removing the `sdk` dir from `7.0.x`?

**Comment by michaelhashimoto** [comment]
@Ithildir - Ohh I see it.. It's because this should be sent to 'liferay-portal-ee' since it's a 7.0.x branch. :)

**Comment by Ithildir** [comment]
Thank you @michaelhashimoto! I resent it at https://github.com/brianchandotcom/liferay-portal-ee/pull/19590.

**Pull request closed without merging**
