### PR TITLE
LPS-160242

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:reopen

**Comment by marianoalvarosaiz** [comment]
Approved and passed tests in https://github.com/liferay-forms/liferay-portal/pull/1940

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3d3d656ed0...fa06131695

**Comment by brianchandotcom** [comment]
@marianoalvarosaiz very nice, no changes from me.

**Comment by marianoalvarosaiz** [comment]
Thanks @brianchandotcom

**Pull request closed without merging**
