### PR TITLE
LPS-80517

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:test

**Comment by hhuijser** [comment]
@brianchandotcom, let's make sure the tests are not failing first!

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:reopen

**Comment by tinatian** [comment]
ci:reopen

**Comment by tinatian** [comment]
Seems the modules-compile-jdk8 failure is caused by this pull, close and check

**Comment by tinatian** [comment]
ci:close

**Comment by tinatian** [comment]
Fix modules-compile-jdk8 and resend at https://github.com/brianchandotcom/liferay-portal/pull/58649

**Pull request closed without merging**
