### PR TITLE
LPS-62595

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/faae39c8f4...905a754b8c

**Comment by brianchandotcom** [comment]
@juliocamarero please see my changes in upstream. Thx.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/35522

**Pull request closed without merging**
