### PR TITLE
LRAC-14336 Create side panel for terminated tests

### PR DESCRIPTION
**Pull request by liulukiwi**
https://liferay.atlassian.net/browse/LRAC-14336

@interaminense

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:reopen

**Comment by liulukiwi** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/13455

**Comment by brianchandotcom** [comment]
@interaminense language keys need to be titles or sentences. Please resend.

**Comment by interaminense** [comment]
Resent to https://github.com/brianchandotcom/liferay-portal/pull/140365

**Pull request closed without merging**
