### PR TITLE
LPS-151303 Adds the theme display to the request when is needed

### PR DESCRIPTION
**Pull request by lfbesada**
Hi @brianchandotcom 
This pull request is the same that https://github.com/brianchandotcom/liferay-portal/pull/115991 I just fixed the rebase error. See: https://github.com/brianchandotcom/liferay-portal/pull/115991#issuecomment-1095690303
Could you please review it?
Thank you very much!
Regards

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
On it.. it's 2 am!!! @lfbesada

**Comment by brianchandotcom** [comment]
Merged. Thx @lfbesada !!!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bc10aff5c6...29509a8830

**Pull request closed without merging**
