### PR TITLE
LPS-74570 Use SessionMessages from within our example portlet

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by brunobasto** [comment]
Hey @pavel-savinov, was this merged? I noticed this issue https://issues.liferay.com/browse/LPS-74570 is still open and I can reproduce it on master.liferay.com

**Comment by pavel-savinov** [comment]
@brunobasto https://github.com/brianchandotcom/liferay-portal/pull/51919
Sorry for delay.

**Comment by brunobasto** [comment]
No problem! Thanks!

**Pull request closed without merging**
