### PR TITLE
LPS-50604 SF

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
@brianchandotcom I have fixed some tests, but I'm still missing the solution for SampleSQLBuilderTest.testGenerateAndInsertSampleSQL.

I'll try  to have a look at it with Miguel tomorrow (https://github.com/migue/liferay-portal/pull/408).

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by izaera** [comment]
@brianchandotcom I don't know what this pull has to do with the one from @rotty3000, but I'm going to push force the fixes for the test and rebase again on master. If the CI approves it, I'll leave it open so that you can merge it.

**Comment by izaera** [comment]
ci:retest

**Comment by izaera** [comment]
@brianchandotcom OK. This is finally working. The reason you are getting a test failure is because until you have merged https://github.com/brianchandotcom/liferay-portal/pull/23330 and published a new Spring Extender as requested by @migue by mail, that test will fail.

If you can, please merge the other pull, publish the Extender, and run the CI again on this pull to make sure nothing else is broken. And if it works, we are nearly finished (I hope) :-).

**Comment by brianchandotcom** [comment]
Closing because of https://github.com/brianchandotcom/liferay-portal/pull/23357

**Pull request closed without merging**
