### PR TITLE
LPS-84680 Fill/Read AssetType.

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by jpince** [comment]
@cgoncas I don't see these int test failures at head, can you please take a look?

**Comment by jpince** [comment]
@cgoncas now I'm not sure, as `FolderResourceTest` is failing with a NPE at head and not even running tests. so I'm not sure what's going on with this pull. I'll copy you on an email

**Comment by jpince** [comment]
confirmed these errors are in upstream, this pull is good

**Comment by brianchandotcom** [comment]
@jpince I"ll work on the FolderResourceTest NPE (can you skype me a link)

@petershin can you fix the generator based on what @cgoncas needs

**Comment by petershin** [comment]
@brianchandotcom - Sent to Cristina: https://github.com/cgoncas/liferay-portal/pull/376

**Pull request closed without merging**
