### PR TITLE
LPS-93157 buildRest

### PR DESCRIPTION
**Pull request by jeyvison**
See https://github.com/nhpatt/liferay-portal/pull/148

cc/ @nhpatt

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@jeyvison this was added by @inacionery 

I'm 90% sure that if I bring this in, this will break portal-workflow-metrics

Please consult with him and test it on portal-workflow-metrics and then resend it to me.

Thx.

**Comment by inacionery** [comment]
Hey @brianchandotcom,

Thank you for letting me know! I have tested these changes and the tests are passing!

/cc @jeyvison @gabrielwas

**Comment by jeyvison** [comment]
Thanks @inacionery!

@gabrielwas , can you please resend it directly to @brianchandotcom ?

**Pull request closed without merging**
