### PR TITLE
LPS-59837

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@brianchandotcom please don't close ticket, this is part 1 of 2

**Comment by mhan810** [comment]
@brianchandotcom don't believe this is related

**Comment by mhan810** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/584965da37...75835392e9

**Pull request closed without merging**
