### PR TITLE
LPS-92243 Update section columns on mouseup

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by jpince** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4c9e1115ff...90d3644806

**Comment by brianchandotcom** [comment]
@p2kmgcl  @sandrodw3 see 90d3644806a0cdd5a722761e1546ff6f94460997 thx.

**Pull request closed without merging**
