### PR TITLE
LPS-91295 Support OpenNLP in Journal

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @brianchandotcom 

We're going to simplify the configuration for all text autotaggers, so this will change a little bit -- basically, the AutoTagger interfaces will no longer refer to the configuration in their signatures.  We'll send that in a different pull request.

Thanks!

/cc @cgoncas

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:reopen

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@adolfopa can you resend? Rebase error, thx.

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/71175

**Pull request closed without merging**
