### PR TITLE
Fix to Pull request for LPS-52990

### PR DESCRIPTION
**Pull request by willnewbury**
The reason why this pull was failing in previous iterations was that regeneration of wsdds had not correctly modified wsdds, particularly server-config.wsdd. The portalClientBuilderTest attempts to retrieve these wsdds causing the error seen on the CI server. Running build-wsdd-portlet-dynamicdatamapping correctly updates the wsdds, solving this problem. 

@shuyangzhou @brianchandotcom @marcellustavares @mtambara

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a41a4921d8...d2c14c0822

**Comment by brianchandotcom** [comment]
@willnewbury great job figuring this out

@marcellustavares thx for the pull. Please see @willnewbury 's tiny change

Thx everyone

**Comment by marcellustavares** [comment]
Thanks @willnewbury!

**Comment by willnewbury** [comment]
Since everyone is thanking me, I feel like I should give credit to @mtambara. We debugged concurrently and he came up with the final solution.

**Pull request closed without merging**
