### PR TITLE
LPS-102555 SF (auto-generated)

### PR DESCRIPTION
**Pull request by jbalsas**
/cc @john-co

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:reopen

**Comment by jbalsas** [comment]
Hey @john-co, could you please look into this? Failure seems unrelated

**Comment by jbalsas** [comment]
ci:test

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

Comparison:
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=925408217&testrayRunIdA=926896156&statusB=2
Mostly flukes and flakiness

The source-format-jdk8 failure is unrelated, same issue is observed in latest upstream:
```
     [java] java.lang.Exception: Found 2 formatting issues:
     [java] 1: ./modules/apps/item-selector/item-selector-test/src/testFunctional/tests/ImageSelector.testcase expected:<...r.gotoSelectFile();
     [java] []
     [java] 		ItemSelector.goto...> but was:<...r.gotoSelectFile();
     [java] [		]
     [java] 		ItemSelector.goto...>
     [java] 2: ./modules/sdk/project-templates/project-templates-service-builder/src/test/java/com/liferay/project/templates/service/builder/ProjectTemplatesServiceBuilderTest.java expected:<...ge=com.test.sample",[
     [java] 			"-DliferayVersion=7.0.6");
```
https://test-1-15.liferay.com/job/test-portal-acceptance-upstream-batch(master)/AXIS_VARIABLE=0,label_exp=!master/34266/console

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cc4a7b877b...3f88df863a

**Pull request closed without merging**
