### PR TITLE
LPS-174616: Add createBatch action on all missing endpoints of Headless Delivery

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What is new?**
- Add `createBatch` action in all missing endpoints of Headless Delivery
- Changes in: `getMessageBoardThreadMessageBoardMessagesPage`, `getMessageBoardSectionMessageBoardThreadsPage`, `getSiteBlogPostingImagesPage`, `getMessageBoardThreadMessageBoardAttachmentsPage`, `getMessageBoardMessageMessageBoardAttachmentsPage`, `getKnowledgeBaseFolderKnowledgeBaseArticlesPage`, `getStructuredContentFolderStructuredContentsPage`, `getDocumentFolderDocumentsPage`, `getWikiPageWikiPageAttachmentsPage`.

**JIRA Tickets:**
https://issues.liferay.com/browse/LPS-175143
https://issues.liferay.com/browse/LPS-175144
https://issues.liferay.com/browse/LPS-174617
https://issues.liferay.com/browse/LPS-174614
https://issues.liferay.com/browse/LPS-174615
https://issues.liferay.com/browse/LPS-174613
https://issues.liferay.com/browse/LPS-175135
https://issues.liferay.com/browse/LPS-174612
https://issues.liferay.com/browse/LPS-174616
https://issues.liferay.com/browse/LPS-174610

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:reopen

**Comment by sergiojimcos** [comment]
Mnaul forward from: https://github.com/liferay-headless/liferay-portal/pull/1009

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f146a84092...2d67882912

**Comment by brianchandotcom** [comment]
@sergiojimcos should we autogenerate this as a var that the ResourceImpls can reference?

**Pull request closed without merging**
