### PR TITLE
[B]  LPS-63951 Uses the new version

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 another build hung.. we're getting a lot of these

**Comment by xbrianlee** [comment]
Investigating the search functional test failure in [this ticket](https://issues.liferay.com/browse/LRQA-23023). The failure is most likely due to the test running too quickly.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/55ebb5e6c2...71b15b5241

**Comment by brianchandotcom** [comment]
@ealonso why dont' you change getTotal to return a long too? Or is that not our pattern? I merged this as is.

Please see my changes in upstream. Thx.

**Comment by pyoo47** [comment]
@brianchandotcom These failures appear to be happening because portal is sometimes failing to start up. We have code that is supposed to timeout this situation and fail the build in 15 minutes but for some reason, it's not working here. We are going to try to add some debug code to figure out what's going on and we are going to try to take a jstack so we Shuyang and figure out why portal didn't start up. We've opened a ticket for this. [LRQA-22397](https://issues.liferay.com/browse/LRQA-22397)

**Comment by ealonso** [comment]
@brianchandotcom I've sent a pull https://github.com/brianchandotcom/liferay-portal/pull/37536 making it consistent with portal. We always return an int in count methods

**Pull request closed without merging**
