### PR TITLE
LPS-87289 Fix reading time calculate for blogs in Analytics JS Client

### PR DESCRIPTION
**Pull request by interaminense**

### CODE REVIEW

**Comment by interaminense** [comment]
ci:reopen

**Comment by interaminense** [comment]
ci:retest

**Comment by jpince** [comment]
@interaminense this is the actual failure, looks like it fails the test you wrote?
```
     [exec] [1A[2K[31mHeadlessChrome 0.0.0 (Linux 0.0.0) getDepth from a element should return the depth number from a element when the element was seen in half FAILED[39m
     [exec] 	AssertionError: expected 46 to equal 50
     [exec] 	    at Context.<anonymous> (webpack:///test/utils/scroll.test.js:57:46 <- test.webpack.js:19053:58)
     [exec] HeadlessChrome 0.0.0 (Linux 0.0.0): Executed 33 of 36[31m (1 FAILED)[39m (0 secs / 2.257 secs)
     [exec] HeadlessChrome 0.0.0 (Linux 0.0.0) getDepth from a element should return the depth number from a element when the element was seen in half FAILED
     [exec] 	AssertionError: expected 46 to equal 50
     [exec] 	    at Context.<anonymous> (webpack:///test/utils/scroll.test.js:57:46 <- test.webpack.js:19053:58)
     [exec] [1A[2KHeadlessChrome 0.0.0 (Linux 0.0.0): Executed 34 of 36[31m (1 FAILED)[39m (0 secs / 2.262 secs)
     [exec] [1A[2K[31mHeadlessChrome 0.0.0 (Linux 0.0.0) getDepth from a page should return the depth number from page when the element was seen in half FAILED[39m
     [exec] 	AssertionError: expected 49 to equal 50
     [exec] 	    at Context.<anonymous> (webpack:///test/utils/scroll.test.js:87:31 <- test.webpack.js:19083:43)
     [exec] HeadlessChrome 0.0.0 (Linux 0.0.0): Executed 35 of 36[31m (2 FAILED)[39m (0 secs / 2.266 secs)
     [exec] HeadlessChrome 0.0.0 (Linux 0.0.0) getDepth from a page should return the depth number from page when the element was seen in half FAILED
     [exec] 	AssertionError: expected 49 to equal 50
     [exec] 	    at Context.<anonymous> (webpack:///test/utils/scroll.test.js:87:31 <- test.webpack.js:19083:43)
     [exec] [1A[2KHeadlessChrome 0.0.0 (Linux 0.0.0): Executed 36 of 36[31m (2 FAILED)[39m (0 secs / 2.27 secs)
     [exec] [1A[2KHeadlessChrome 0.0.0 (Linux 0.0.0): Executed 36 of 36[31m (2 FAILED)[39m (2.389 secs / 2.27 secs)
```

**Comment by brianchandotcom** [comment]
@interaminense can you fix the SF for stuff like this?

```
		if (element) {
			if (top > 0) {
				value = (visibleArea - top) / height;
			} else {
				value = visibleArea / (height + top);
			}
		} else {
			value = (top + visibleArea) / height;
		}
```

We don't do if else like this. 

@jbalsas fyi. Can you coordinate with @brunobasto @brunofarache or whoever else from Brazil? Thx!

**Comment by jpince** [comment]
@interaminense do you have a fix for the frontend-js error? It's now failing in master and 7.1.x.

**Comment by interaminense** [comment]
@brianchandotcom I'll send the PR to @brunobasto before I send it to you. @jpince I'm fixing the test errors. Thanks

**Comment by jpince** [comment]
@interaminense thank you!

**Pull request closed without merging**
