### PR TITLE
LPS-61140 Add missing require

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
Aborted due to known start-up issue caused by https://github.com/brianchandotcom/liferay-portal/commit/d992d839572c70e1e93be6c97b1566069941a69f

After this <a href="https://github.com/brianchandotcom/liferay-portal/pull/34330">pull</a> is merged we can re-run this particular pull request.

Sorry for the inconvenience.

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@carloslancha PoshiRunner.test[PasswordpoliciesUsecase#ViewUserAccountLockout] - Poshi Report - Poshi Summary - Console Output

that one may be real. Please resend.

**Pull request closed without merging**
