### PR TITLE
LPS-61767

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/beaf4ba8f6...1feb207335

**Comment by brianchandotcom** [comment]
@caustin Greg currently has his own repo here: https://liferay-test-01.ci.cloudbees.com/job/liferay-bundle-publishing/lastSuccessfulBuild/artifact/build/m2_repo/com/liferay/portal-tomcat-bundle/7.0-ce-b2-20160105152151933/

See modules/sdk/gradle-plugins-workspace/src/main/resources/META-INF/liferay-workspace/gradle.properties

Can you move it to our own repo? Let's not depend on a third party (imagine if we release this and somehow cloudbees goes down or bans us). Let's use our own repo which is backed by our CDN.

@gamerson @david-truong good @Ithildir job guys!

@mhan810 fyi

**Comment by brianchandotcom** [comment]
@CAustin582

**Pull request closed without merging**
