### PR TITLE
LPS-79982

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-79982

Resend of https://github.com/brianchandotcom/liferay-portal/pull/57756

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test

**Comment by ctampoya** [comment]
@holatuwol Can you take a look at the semantic versioning error please

**Comment by holatuwol** [comment]
ci:reopen

**Comment by holatuwol** [comment]
Never mind, the revert from https://github.com/brianchandotcom/liferay-portal/pull/57781 causes this to fail. I'll resubmit again.

**Pull request closed without merging**
