### PR TITLE
LPS-67914 Wordsmith

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @ithildir, @kenjiheigel, could you please take a look at this build failure? I tested on a clean environment on my machine and it is building properly...

**Comment by Ithildir** [comment]
For some reasons I can't open the Jenkins report of this pull :sob:

**Comment by Ithildir** [comment]
Ok, I think I found the reason:

> Cannot download "http://mirrors.lax.liferay.com/github.com/sass/node-sass/releases/download/v3.8.0/linux-ia32-48_binding.node"

Apparentely, this new theme uses node-sass 3.8.0, while yesterday we cached the latest one used by all the other themes, 3.10.0. The post-install script can't find the file, then it tries to compile it and fails.

@stsquared99: can you please cache the assets of node-sass 3.8.0?

Thank you!

**Comment by jpince** [comment]
@Ithildir thanks!

**Comment by brianchandotcom** [comment]
@Ithildir shouldn't we try to all use the same version of node-sass where possible? @jbalsas Thx.

Please resend.

**Pull request closed without merging**
