### PR TITLE
LPS-174324 Add dropTables command to UpgradeProcessFactory

### PR DESCRIPTION
**Pull request by achaparro**
- LPS-174324 Uses method since it already check if the table exist
- LPS-174324 Adds new method in Factory to allow deleting tables
- LPS-174324 Uses new method and delete no needed classes
- LPS-174324 Changes drop table action from doUpgrade method to getPostUpgradeSteps
- LPS-174324 Add _getTablesUpgradeInfo method to UpgradeProcessFactory class
- LPS-174324 Add testDropTable, testDropNonexistentTable and testDropTables methods
- LPS-174324 Add DROP_TABLE_IF_EXISTS in tearDown method in BaseDBProcessTest
- LPS-174324 Baseline
- LPS-174324 SF
- LPS-174324 Fix typo
- LPS-174324 Do not repeat logic
- LPS-174324 Consistency
- LPS-174324 Manual SF

### CODE REVIEW

**Comment by achaparro** [comment]
ci:close

**Comment by achaparro** [comment]
ci:reopen

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:close

**Comment by achaparro** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/81abb2e75e...4531c3ad16

**Comment by brianchandotcom** [comment]
@achaparro just 301f26f9b1f3e2a4ca43d2ee72172038e29c7fee

**Pull request closed without merging**
