### PR TITLE
LPS-77250

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:test

**Comment by Ithildir** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@Ithildir can you resend this? Remember that gradle-plugins is synced between master and 7.0.x. This will work for master but break for 7.0.x, so you need to make the plugin smart enough to support both.

Fyi @jbalsas

**Comment by jbalsas** [comment]
Hey @brianchandotcom, this should be good to go. The code we are changing was added for future components that would be prefixed with `lexicon-` but that we ended prefixing with `clay-` instead. 

The current code in the plugin has no effect, as there isn't any component with soy templates that follows that pattern, whereas we do have the ones with clay. We can add both, but it would be a useless extra configuration setting.

**Comment by Ithildir** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Thx @jbalsas ! thanks for verifying

**Comment by Ithildir** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/54485.

**Pull request closed without merging**
