### PR TITLE
LPS-175809 remove ObjectEntries when a site is deleted

### PR DESCRIPTION
**Pull request by carolmariaabb**
Unrelated failures [here](https://github.com/liferay-objects/liferay-portal/pull/1765#issuecomment-1442443678)

/cc @jgarcialr

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ab80363d33...2398462aaa

**Comment by brianchandotcom** [comment]
@jgarcialr @carolmariaabb see e3107c0419c9ef341053253c73fc482ac2e62245

**Comment by brianchandotcom** [comment]
@carolmariaabb can you see where those methods are used and remove any unncessary try catches too? See e3107c0419c9ef341053253c73fc482ac2e62245 and 2398462aaa3ba3c645db8d72ff42dc7dac9fb1bb

**Pull request closed without merging**
