### PR TITLE
LPS-158088 Validate System Objects

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**
Hi @brianchandotcom,

The fails displayed [here](https://github.com/liferay-zulu/liferay-portal/pull/295) are not related.

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
Resent here #120908

**Comment by MarinhoFeliphe** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/dc143fbb4d...724cef34fa

**Comment by brianchandotcom** [comment]
@seltong @MarinhoFeliphe just 724cef34fa20db392168a94c500577f85387d1a3

Great job guys!

**Pull request closed without merging**
