### PR TITLE
LPS-109842, LPS-109845

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-109842
https://issues.liferay.com/browse/LPS-109845

### CODE REVIEW

**Comment by adolfopa** [comment]
/cc @jbalsas

@brianchandotcom This PR tries to reduce the impact of Soy template processing on the build time. The idea is to reduce the number of modules with Soy templates, so that as few as possible JVM processes are launched.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bb07eaffd9...f0a529c8d8

**Comment by brianchandotcom** [comment]
@adolfopa very clever with ImageEditorCapabilityActivator!

**Comment by shuyangzhou** [comment]
@slnn this should reduce a few soy compiler JVM, please confirm.

**Comment by slnn** [comment]
Hi @shuyangzhou 

Here are test results of this pull:



From test results the soy compiler execution times by Pids is reduced by the pull.

Portal Version | Git Id | GradleWorkerMain | soy-2017-04-23-SoyToIncrementalDomSrcCompiler.jar | GradleWrapperMain | GradleDaemon | Launcher
-- | -- | -- | -- | -- | -- | --
BaseLine | 53f565f | 24 | 19 | 21 | 1 | 1
PR | 6f759d0 | 24 | 12 | 21 | 1 | 1

Regards
Lily

**Pull request closed without merging**
