### PR TITLE
LPS-75321 Makes fields private

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by ealonso** [comment]
Hey @anthony-chu,

Do you know why Breadcrumb#DisableShowPage is broken?

Thanks!!
Eudaldo

**Comment by ealonso** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e354c874f6...58b5bc0450

**Pull request closed without merging**
