### PR TITLE
LPS-70294 Unit test

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@brunobasto @marcellustavares

**Comment by leoadb** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@leoadb please resend, conflicts with https://github.com/brianchandotcom/liferay-portal/pull/46407

**Comment by leoadb** [comment]
@diogo-lins Can you please rebase and resend to me ?

**Comment by diogo-lins** [comment]
@leoadb Ok, no problem

**Pull request closed without merging**
