### PR TITLE
LPS-90254 Make System Settings portlet renderable at different scopes

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-90254](https://issues.liferay.com/browse/LPS-90254).
This is an update for [LPS-92507](https://issues.liferay.com/browse/LPS-92507).

/cc @pei-jung @stsquared99 @alee8888 @ChrisKian

------

@brianchandotcom I removed the Cleaner class

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
ci:test:relevant (I fixed something in upstream)

**Comment by drewbrokke** [comment]
resent as https://github.com/brianchandotcom/liferay-portal/pull/70059

**Pull request closed without merging**
