### PR TITLE
Lps 52618

### PR DESCRIPTION
**Pull request by shuyangzhou**
cc @mhan810 Fixed the windows ant exclusion issue.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
The BaseIntrabandTest is a random failure, will take a closer look later, rerun the build.

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/76cbcf29d5...b2e6dfd8b9

**Pull request closed without merging**
