### PR TITLE
LPS-94003 Upgrade to version 5.2.2.RELEASE of the Spring Framework

### PR DESCRIPTION
**Pull request by ngriffin7a**
@brianchandotcom Shuyang asked me to rebase this PR against your master origin in order to resolve a conflict that was not yet present upstream. It's all rebased and should be mergeable now. Thanks!

/cc @shuyangzhou @vicnate5

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:reopen

**Comment by vicnate5** [comment]
@ngriffin7a TCK failure? this did not occur in our previous testing.
```
     [exec] Testing: V2DispatcherTests4_SPEC2_19_ForwardJSPAction_invoke3
     [exec]    Exception occurred: Expected condition failed: waiting for visibility of element located by By.id: V2DispatcherTests4_SPEC2_19_ForwardJSPAction_invoke3-result (tried for 5 second(s) with 500 milliseconds interval)
     [exec]       diagnostic url = http://localhost:8080/web/guest/home?p_p_state=maximized&p_p_mode=view&refererPlid=31&saveLastPath=false&_com_liferay_login_web_portlet_LoginPortlet_mvcRenderCommandName=%2Flogin%2Flogin&p_p_id=com_liferay_login_web_portlet_LoginPortlet&p_p_lifecycle=0&_com_liferay_login_web_portlet_LoginPortlet_redirect=%2Fgroup%2Fportlet-tck%2Fv2dispatchertests4%3Fp_p_id%3DDispatcherTests4_SPEC2_19_ForwardJSPAction_WAR_tckV2DispatcherTests4%26p_p_lifecycle%3D1%26p_p_state%3Dnormal%26p_p_mode%3Dview%26p_auth%3DKWxtWgxD
     [exec]    before test.
     [exec]    execute test.
     [exec]    Access page, link found: true, page===V2DispatcherTests4===
     [exec]    TC elements already on page: true, tcname===V2DispatcherTests4_SPEC2_19_ForwardJSPAction_invoke3===
     [exec]    Setup link found: false
     [exec]    Async elements found: false
     [exec]    Clickable link found: true
     [exec] Testing: V2DispatcherTests4_SPEC2_19_ForwardJSPEvent_invoke3
     [exec] login: found userid and password fields
```

**Comment by ngriffin7a** [comment]
@vicnate5 Can we re-run the TCK tests? I never saw this before when running sending PRs to myself.

**Comment by vicnate5** [comment]
ci:test:tck

**Comment by brianchandotcom** [comment]
@vicnate5 let me know if this is safe to merge. Thx.

**Comment by vicnate5** [comment]
@brianchandotcom This looks safe.

There is a some flakiness with the TCK tests. But it is also seen in upstream (https://testray.liferay.com/reports/production/logs/test-1-1/1578431508358/test-portal-acceptance-upstream(master)/7005/tck-jdk8/0/jenkins-console.txt.gz)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/63b91db99b...204dd33a40

**Comment by brianchandotcom** [comment]
@ngriffin7a merged, please send follow up package change. Thx!

**Pull request closed without merging**
