### PR TITLE
LPS-72866 Don't delete contents of external repositories

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pyoo47 what happened here?

**Comment by pyoo47** [comment]
@brianchandotcom The repository was corrupt in a way we haven't seen before. It manages to pass verification even though it doesn't really work. I've created a ticket to update our verification logic to catch this problem. https://issues.liferay.com/browse/LRQA-33001

**Comment by adolfopa** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fa0e83cf5b...2ee3167d85

**Pull request closed without merging**
