### PR TITLE
master-vw-542

### PR DESCRIPTION
**Pull request by vicnate5**
@gregory-bretall @brandizzi

### CODE REVIEW

**Comment by pyoo47** [comment]
This PR Test failed because of the network outage. ci:retest

**Comment by pyoo47** [comment]
PR Test failed because temp-map service issue - ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
