### PR TITLE
LPS-69726 Unit tests for field specific Query Builders: Title, Description, Substring

### PR DESCRIPTION
**Pull request by arboliveira**
Author: @rodrigopaulino 
Reviewer: @arboliveira

https://issues.liferay.com/browse/LPS-69726

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:reopen

Unrelated test failures. Fix for this random failure already submitted for review: https://github.com/brianchandotcom/liferay-portal/pull/45564

**Comment by arboliveira** [comment]
Unrelated test failures. Fix for this random failure already submitted for review: https://github.com/brianchandotcom/liferay-portal/pull/45564

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@shuyangzhou can you review this pull? I'm not sure if we have the unit-util pattern yet or if you had another pattern to accomplish this same task. Thanks @shuyangzhou

**Comment by shuyangzhou** [comment]
@arboliveira I took a quick look, only for the structure not the logic. We don't have this test-unit-util thing, we only do xyz-test-util, which is shared by both unit and integration tests. For example, portal-cache-test-util is used by unit tests, and blogs-test-util is used by integration test.

I think structure wise you could just as simple as rename the module, then this should be good.

**Pull request closed without merging**
