### PR TITLE
LPS-77225 Apply new NavigationBar pattern to roles-admin-web

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @drewbrokke, @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@ealonso @jkappler I ignored FragmentEntryServiceTest.testAddFragmentEntryWithVoidHTMLElements for now in 7414f77bc9cfbc50c21c1f8b20605c9a8b60810c

Please fix!

**Comment by brianchandotcom** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@pei-jung come find me tomorrow? I find the usage of  _getTabNames and _getTabsURLMap very weird. Thx

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cf9b794315...a672c90db0

**Pull request closed without merging**
