### PR TITLE
LPS-54852 LPS-55650

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@rotty3000 any idea on the PMD error?

**Comment by rotty3000** [comment]
I don't even know what PMD is!

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/51b9c6f26f...c62b4cdcb2

**Pull request closed without merging**
