### PR TITLE
LPS-60971 Apply lexicon styles to edit folder

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
So weird... the poshi test failure.

**Comment by vicnate5** [comment]
@ealonso @brianchandotcom Looks like the poshi test is failing due to a regression. Workflow dropdown select is missing when trying to edit folder.

**Comment by brianchandotcom** [comment]
@vicnate5 is that due to a regression in this pull or another pull?

**Comment by vicnate5** [comment]
@brianchandotcom this pull

**Comment by brianchandotcom** [comment]
@ealonso please resend. Thx.

**Pull request closed without merging**
