### PR TITLE
LPS-104540 Update to 7.3

### PR DESCRIPTION
**Pull request by petershin**
Tests passed here: https://github.com/petershin/liferay-portal/pull/796#issuecomment-554460374

Pull for `master-private`: https://github.com/brianchandotcom/liferay-portal-ee/pull/27644

@jpince @lawrence-lee @john-co

### CODE REVIEW

**Comment by jpince** [comment]
@petershin @john-co thank you!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/dfea4be678...6a2542572c

**Comment by jpince** [comment]
@xbrianlee @joshchong
```
LocalFile.OAuth2#AddAndEditOAuthSAPEntries
java.lang.Exception: JSON-WS call failed to return Portal version
```
Is this failure related to the portal version change?

**Comment by joshchong** [comment]
@jpince, yes this just requires a test fix which I created a ticket for here:
https://issues.liferay.com/browse/LRQA-53726
Thanks for catching this!

**Pull request closed without merging**
