### PR TITLE
LPS-57882 Rename to ServiceWrapper

### PR DESCRIPTION
**Pull request by marcellustavares**
Hey Brian, I've renamed to ServiceWrapper but I'm still not sure if this would be the best choice :)

This utility is still not used in the portal but I'll reference it in my next pull request.

Thanks a lot!

cc @csierra

### CODE REVIEW

**Comment by brianchandotcom** [comment]
I like the name @marcellustavares 
I didn't have time to merge it in today but will do it tomorrow.

Thx

**Comment by marcellustavares** [comment]
nice, thx @brianchandotcom

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/476aa5bacd...c2b50cf302

**Comment by brianchandotcom** [comment]
@csierra @marcellustavares please see my changes in upstream. Thx.

**Pull request closed without merging**
