### PR TITLE
LPS-136256 Use PortletURLBuilder

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bd22eb608e...2d31554040

**Comment by brianchandotcom** [comment]
@gabrielwas merged, but I have some doubts:

1.) SCREEN_NAVIGATION_KEY_OBJECT_DEFINITION

This is singular, but in BaseObjectDefinitionsScreenNavigationEntry.

I assume BaseObjectDefinitionsScreenNavigationEntry shows a LIST, where as SCREEN_NAVIGATION_KEY_OBJECT_DEFINITION is for ONE because of how it's used in edit_object_definition.jsp?

2.) See also my other changes in my origin. Quite a few tiny ones.

@marco-leo fyi 

@gabrielwas thanks for the pull!

**Comment by gabrielwas** [comment]
@guilhermedcamacho fyi

**Comment by gabrielwas** [comment]
@brianchandotcom 

1.) BaseObjectDefinitionsScreenNavigationEntry will provide base implementations for both "edit" pages (edit_object_definition and edit_object_field). Thats why it is prefixed with ObjectDefinitions (it belongs to ObjectDefinitionsPortlet environment).

thanks for merging it

**Pull request closed without merging**
