### PR TITLE
LPS-54889

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
Brian, shouldn't be a real failure since plugins has already been updated to remove the reference to StringDistanceCalculatorUtil

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/24b7bc7dc3...df0d4fb79d

**Comment by brianchandotcom** [comment]
Hey Mike, this is fixed in portal master 7f27790cc72c13c2f51d4099590f64bdc9a9e718

where I flag that the portal now is hitched to plugins of that rev.

**Comment by brianchandotcom** [comment]
Test 7f27790cc72c13c2f51d4099590f64bdc9a9e718

**Comment by brianchandotcom** [comment]
Hey Mike, this is fixed in portal master 7f27790cc72c13c2f51d4099590f64bdc9a9e718

where I flag that the portal now is hitched to plugins of that rev.

**Pull request closed without merging**
