### PR TITLE
LPS-139008 Object Action Settings

### PR DESCRIPTION
**Pull request by carolmariaabb**

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fb419ab38c...d36e44ff75

**Comment by brianchandotcom** [comment]
@carolmariaabb @marco-leo merged! Thanks Carolina!

See d36e44ff754047cf27b16d90b5106a445b91d8f5

**Pull request closed without merging**
