### PR TITLE
LPS-19571 Fix SF and properly set system feature flags.

### PR DESCRIPTION
**Pull request by ethib137**
Fixing SF issue caused by https://github.com/brianchandotcom/liferay-portal/pull/147810

@joseabelenda https://liferay.atlassian.net/wiki/spaces/ENGR/pages/1604714779/Feature+Flags#System-scoped-feature-flags

### CODE REVIEW

**Comment by ethib137** [comment]
ci:reopen

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:reopen

**Comment by ethib137** [comment]
Tested that it passes SF [here](https://github.com/ethib137/liferay-portal/pull/342).

**Comment by joseabelenda** [comment]
Thank you @ethib137

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c3167471b8...ad9a632ce3

**Pull request closed without merging**
