### PR TITLE
LPS-79186

### PR DESCRIPTION
**Pull request by Ithildir**
Hi,
Please let this pull finish.

Thank you!

https://github.com/brianchandotcom/liferay-portal/commit/56187f0010220ee6ad317b2555bf5d22598b467a and https://github.com/brianchandotcom/liferay-portal/commit/f15973a628f24d28a7d8c059478d886cd0cd3381 can be back-ported, since they won't do anything on 7.0.x branches.

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:test

**Comment by brianchandotcom** [comment]
ci:test

**Comment by Ithildir** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/42be8ab8fe...333749d5ee

**Pull request closed without merging**
