### PR TITLE
LPS-66709 READMEs and change logs

### PR DESCRIPTION
**Pull request by codyhoag**
/cc @Ithildir

### CODE REVIEW

**Comment by jpince** [comment]
@codyhoag @Ithildir it seems like those axes failes due to a shutdown issue, probably a CI issue unrelated to this pull.

However, I did see a lot of failures like this while perusing the stacktrace:
```
     [exec] com.liferay.portal.remote.axis.extender.client.test.AxisExtenderTest STANDARD_ERROR
     [exec]     SLF4J: Class path contains multiple SLF4J bindings.
     [exec]     SLF4J: Found binding in [jar:file:/opt/dev/projects/github/liferay-portal/bundles/tomcat-8.0.32/webapps/ROOT/WEB-INF/lib/util-slf4j.jar!/org/slf4j/impl/StaticLoggerBinder.class]
     [exec]     SLF4J: Found binding in [jar:file:/opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-log4j12/1.5.11/c3fbec782ff5fc7fa50cfeeb67502ded9efd58d9/slf4j-log4j12-1.5.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
     [exec]     SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
     [exec]     SLF4J: Actual binding is of type [com.liferay.util.sl4fj.LiferayLoggerFactory]
```
Not sure if that's caused by this pull or those have always been there https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3983/AXIS_VARIABLE=5,label_exp=!master/consoleFull

**Comment by codyhoag** [comment]
@jpince this pull only makes changes to Markdown files (README and CHANGELOG), so the CI issues should be unrelated to this.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by jpince** [comment]
@codyhoag agreed, it was more to see if Andrea thinks we needed to do something about those errors going forward.

**Comment by Ithildir** [comment]
@jpince, we always had those, I don't think they're a problem..

**Comment by jpince** [comment]
Thanks @Ithildir!

**Pull request closed without merging**
