### PR TITLE
LPS-56383 Avoid NPE due to race condition when loading cache configuration.

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
The failed test is fixed at https://github.com/brianchandotcom/liferay-portal/pull/27681, this pull should be fine.

**Comment by brianchandotcom** [comment]
ci:retest (testing something with CI, so I will merge in this pull)

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/68b30b4622...8bc3169246

**Pull request closed without merging**
