### PR TITLE
LPS-59133

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-59133.  I ran the errors by @kenjiheigel and the QA team and the package start up issue did not occur after a retest.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by kenjiheigel** [comment]
@brianchandotcom, this is an example of some of the test failures that I mentioned to you just now. Will let you know when we figure out the cause.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@jonmak08 SF error

```
format-source-current-branch:

format-source:
     [java] Loading file:/Users/brian/dev/projects/github/liferay-portal/portal-impl/classes/system.properties
     [java] missing language key: share-this-application-on-any-website: ./modules/apps/web-experience/portlet-configuration/portlet-configuration-web/src/main/resources/META-INF/resources/edit_sharing.jsp
```

Please resend.

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/brianchandotcom/liferay-portal/pull/42619

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/brianchandotcom/liferay-portal/pull/42696

**Pull request closed without merging**
