### PR TITLE
Lps 154557 fix 2

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2f9b7dc95c...d92f0f95ac

**Comment by brianchandotcom** [comment]
@vendeltoreki @shuyangzhou @dantewang see d92f0f95ac11b912af6f247709d06381218b6abf

**Comment by brianchandotcom** [comment]
@vendeltoreki @shuyangzhou @dantewang I decided to show the exception messages by default as that is more helpful. See 8133ad688f325a8b73813119341877067cea6224

**Pull request closed without merging**
