### PR TITLE
LPS-68934 buildLang

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by vicnate5** [comment]
@marcellustavares I sent a 7.0.x pull as well (https://github.com/brianchandotcom/liferay-portal/pull/44415) It isn't showing the same failures as here. Could you take another look?

**Comment by marcellustavares** [comment]
@vicnate5, I cant understand what could be failing on this. I've just renamed the portlet title.

**Comment by marcellustavares** [comment]
ci:reopen

**Comment by marcellustavares** [comment]
ci:retest

**Comment by marcellustavares** [comment]
hi @pyoo47, could you help me with this pull? I'm not sure why it's failing.

Thx

**Comment by pyoo47** [comment]
@marcellustavares I've discussed this with Victor and Jason and we agreed that these failures match to what's currently failing in ee-7.0.x so Victor will resend this pull in ee-7.0.x.

**Comment by marcellustavares** [comment]
Thanks @pyoo47!

**Comment by vicnate5** [comment]
@pyoo47 @marcellustavares Sent to ee-7.0.x
https://github.com/brianchandotcom/liferay-portal-ee/pull/14933

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
