### PR TITLE
LPS-73651 SF

### PR DESCRIPTION
**Pull request by rafaprax**
\cc @leoadb

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:reopen

**Comment by rafaprax** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b10882c771...bfea6c22e7

**Pull request closed without merging**
