### PR TITLE
LRCI-1039 When deleting docker containers, ensure they are also removed from the node's docker network

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRCI-1039

@pyoo47

### CODE REVIEW

**Comment by kenjiheigel** [comment]
Backports:
https://github.com/brianchandotcom/liferay-portal-ee/pull/29115 (7.2.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/29116 (7.1.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/29117 (7.0.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/29118 (ee-6.2.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/29119 (ee-6.2.10)
https://github.com/brianchandotcom/liferay-portal-ee/pull/29120 (ee-6.1.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/29121 (ee-6.1.30)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e2eedd889f...46c3a5d312

**Comment by brianchandotcom** [comment]
@kenjiheigel see a387bf2 I'll backport my change.

**Comment by brianchandotcom** [comment]
@kenjiheigel I mentioned https://github.com/brianchandotcom/liferay-portal/commit/a387bf2c82ee95e7d88723c41465dc2141a7f231 in this pull, so I would have expected you to apply it in liferay-jenkins-ee as well. I just did it in https://github.com/liferay/liferay-jenkins-ee/commit/0680876d0dafc5c883dcbbaef831539e038ad492

**Pull request closed without merging**
