### PR TITLE
LPS-69113 Fix tracker filter

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@jbalsas backported!

**Comment by jbalsas** [comment]
great, thanks a lot! ☺️

**Comment by jbalsas** [comment]
hey @brianchandotcom, @hhuijser, this simple issue caused all RTL to fail. Could we enforce this through `SourceFormatter` so inside `filterString` or similar there's no spaces around the `=` signs?

**Comment by hhuijser** [comment]
@jbalsas, I added it to my todo list. Right now, lots of stuff on my plate, so it might take a while...

**Comment by hhuijser** [comment]
@jbalsas do you mind opening a new LPS ticket for this that describes the issue and why exactly we should not use spaces in those filters?

**Comment by jbalsas** [comment]
Hey @hhuijser, I've opened https://issues.liferay.com/browse/LPS-70526 with the description and some explanation. It seems the filter is space sensitive, and that's that :)

**Pull request closed without merging**
