### PR TITLE
LPS-167597 Update portletId following to CETDeployer that any non-word character on ERC should be replaced to underline

### PR DESCRIPTION
**Pull request by ces-binhtran**
Manually forwarded: https://github.com/liferay-frontend/liferay-portal/pull/2884
> ###  ci:test:stable - 28 out of 28 jobs passed
> ###  ci:test:relevant - 49 out of 52 jobs passed in 1 hour 17 minutes
> Click here for more details.
> ##### Test bundle downloads:
> * [liferay-portal-bundle-tomcat.tar.gz](https://files.liferay.com/private/bundles/test-1-32/jobs/test-portal-acceptance-pullrequest(master)/builds/7180/liferay-portal-bundle-tomcat.tar.gz) (mirrors: [dlc](http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-32/jobs/test-portal-acceptance-pullrequest(master)/builds/7180/liferay-portal-bundle-tomcat.tar.gz), [lax](http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-32/jobs/test-portal-acceptance-pullrequest(master)/builds/7180/liferay-portal-bundle-tomcat.tar.gz))

Hi @brianchandotcom, I updated the fix as a new upgrade process, please help to review. 
Thank you.

cc: @izaera

### CODE REVIEW

**Comment by binhtran92** [comment]
ci:reopen

**Comment by holatuwol** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@ces-binhtran @holatuwol ok, thanks for the AWESOME explanation.

1.) Refactor

```
	public static String replaceNonwordCharacterToUnderline(
		String externalReferenceCode) {
```

to

````
	public static String normalizeExternalReferenceCodeForPortletId(
		String externalReferenceCode) {

````

2.) Rename

com.liferay.client.extension.web.internal.upgrade.v3_0_0 to

com.liferay.client.extension.web.internal.upgrade.v3_0_1

Add the fix.

Turn

```
		registry.register(
			"2.0.0", "3.0.0",
			new com.liferay.client.extension.web.internal.upgrade.v3_0_0.
				UpgradePortletId());
```
to

```
		registry.register(
			"2.0.0", "3.0.0",
			new DummyUpgradeStep());
```

3.) UpgradePortletIdTest.java should not have 

_replaceNonwordCharacterToUnderline

We want to hard code the expected to actual values - essentially documenting the expected behavior

4.) Just call the test method "testDoUpgrade". Avoid setUp and tearDown since there's only 1 test.

Thx

**Comment by holatuwol** [comment]
@brianchandotcom Yes, it's something we can abstract out to a base class.

**Comment by brianchandotcom** [comment]
@holatuwol please do the abstract in a follow up ticket. Thx.

**Pull request closed without merging**
