### PR TITLE
master-qa-27622

### PR DESCRIPTION
**Pull request by sharonchoi**
https://issues.liferay.com/browse/LRQA-27622

@brianchandotcom This pull should fix the compile error for POSHI tests happening at head, that was merged from this pull: https://github.com/brianchandotcom/liferay-portal/pull/44445

@alee8888 @xbrianlee

### CODE REVIEW

**Comment by jpince** [comment]
Thanks @sharonchoi!

cc/ @brianchiu

**Comment by jpince** [comment]
@brianchandotcom please merge ASAP. Thanks!

**Comment by kenjiheigel** [comment]
Pushed upstream:
https://github.com/liferay/liferay-portal/commit/6bfc5d2168c98c3826875ddee1de881829a3959c

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
