### PR TITLE
LPS-54824 Move CustomAttributesDisplay classes to journal-web module, since they are registered by portletId

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@epgarcia please see my changes for this LPS to make it match bookmarks.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/da6d5bb2b5...41cd38fdd8

**Comment by epgarcia** [comment]
Hi @brianchandotcom,

Thanks for the changes. Actually I wasn't sure if we wanted to have compound names in packages (i.e. customattributes instead of custom or custom.attributes). This pattern only affects modules so far, since in non-modularized portlets the CustomAttributesDisplay classes do not have any specific package, but now we have a reference for future extractions.

Regards

**Pull request closed without merging**
