### PR TITLE
Lps 124713

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@Preston-Crary the change to service_util includes a requirement for dsl. That would break older versions. Can you resend with compatibility? Thx! Sooooo good to see pulls from you man!

**Comment by brianchandotcom** [comment]
@shuyangzhou fyi on compat issues. See comment above.

**Comment by brianchandotcom** [comment]
@Preston-Crary @shuyangzhou nvm, Preston said it's safe since the unused imports will be removed by SF. Merging.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/29b66b764d...5b26c01081

**Pull request closed without merging**
