### PR TITLE
LPS-86121 Ignores AUI modules from babel too. Babel will at least add the 'use strict' pragma, which can cause other code depending on global access to this to fail

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jpince** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@koor4356 please look into new POSHI test failures?

cc/ @vicnate5

**Comment by koor4356** [comment]
@jpince @vicnate5, I analyzed this PR results and I find out that these tests failures are not specific to this PR. They are already failing on other pull requests.

**Comment by jbalsas** [comment]
ci:reopen

**Pull request closed without merging**
