### PR TITLE
LPS-78886 Explore using type parameters in the UAD API

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-78886](https://issues.liferay.com/browse/LPS-78886).<br><br>Hey Brian, this is a resend per your request here: https://github.com/brianchandotcom/liferay-portal/pull/56723.  Please allow the tests to finish.<br><br>/cc @pei-jung @willnewbury

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@drewbrokke is this right?

```
public class UADEntity<T> {

	public UADEntity(T entity, Serializable primKeyObj, String uadRegistryKey) {
		_entity = entity;
		_primKeyObj = primKeyObj;
		_uadRegistryKey = uadRegistryKey;
	}

	public T getEntity() {
		return _entity;
	}
```

Can you also rename primKeyObj to primKey everywhere? I only used the differentiation for code that happens to have both, in our case, it's always a Serializable.

Thx.

**Comment by drewbrokke** [comment]
@brianchandotcom I left it in the case of UADEntity because I didn't have a better idea of what to call the "getEntity" method.  Since it's a data class, it follows the pattern of "get{FieldName}".  I thought it would be weird to have `T t` as a parameter, then have getT or something like it as a getter method name.

**Comment by drewbrokke** [comment]
> Can you also rename primKeyObj to primKey everywhere? I only used the differentiation for code that happens to have both, in our case, it's always a Serializable.

Yeah I can do that.  I might actually just change it to `primaryKey` to be more descriptive from an API perspective.

**Pull request closed without merging**
