### PR TITLE
Lps 65510

### PR DESCRIPTION
**Pull request by shuyangzhou**
@mtambara if @brianchandotcom is ok with the solution, please apply it to EE too.

@michaelhashimoto there are 2 ways to configure profiles.
1) system-ext.properties
portal.profiles=CE,EE,bundle symbolic names

2) portal-ext.properties
module.framework.properties.portal.profiles=CE,EE,bundle symbolic names

portal-ext.properties takes higher priority than system-ext.properties

CE and EE are 2 buildin common profiles. bundle symbolic names are supported too.

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
I had to stop and retest this pull because a recent CI pull that got merged into upstream broke the PR tester. The source of this problem has been reverted.

**Comment by michaelhashimoto** [comment]
ci:retest

**Pull request closed without merging**
