### PR TITLE
LPS-76842 Add a new field nameTreePath to the Organization Indexed document

### PR DESCRIPTION
**Pull request by marco-leo**
Resend Pull with Bug fixes

/cc @pei-jung @drewbrokke @arboliveira @jpince.

### CODE REVIEW

**Comment by marco-leo** [comment]
ci:test

**Comment by brianchandotcom** [comment]
ci:retest @michaelhashimoto what happened here?

**Comment by marco-leo** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@marco-leo see 2f10c365250467b86614bce5ca2c389754af5ca8 

@pei-jung please backport if it's a bug in 7.0.x.

**Comment by pei-jung** [comment]
@brianchandotcom this is a request from the commerce team to have the option to sort and search organization tree path with organization names. We don't need to backport this.

**Pull request closed without merging**
