### PR TITLE
LPS-99198 HttpHeaders now do not have language id value

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
Hey @andre.oliveira 
You know if there were some change on Search that made this happens

Thanks

// @4lejandrito

**Comment by xbrianlee** [comment]
@AliciaGarciaGarcia I believe this test failure was caused by https://issues.liferay.com/browse/LPS-98549

Range: https://github.com/liferay/liferay-portal/compare/4a980f1dbf0b972ec5df9f7cb7bafe5a91863853...b23bce7275c0bd25ff2afcd22064955daa6ed67a

**Comment by xbrianlee** [comment]
ci:test:search

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0cd2f3bc71...bf69d7c0f6

**Pull request closed without merging**
