### PR TITLE
LPS-94470 Fix tests

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:test

**Comment by epgarcia** [comment]
@jpince the build is failing, but I tested locally and this change should fix the AT upgrade tests for all the dbs.

**Comment by epgarcia** [comment]
ci:test

**Comment by jpince** [comment]
ci:test:relevant @epgarcia thanks for letting me know about the compile failure!

**Comment by epgarcia** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
