### PR TITLE
LRQA-36001 & LRQA-37339

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-36001
https://issues.liferay.com/browse/LRQA-37339

Please publish after merging

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/76a3b4e851...215648755d

**Comment by brianchandotcom** [comment]
@pyoo47 published..

You forgot to do this 3247214e71aa453fe7c075047f2815923bd91c20 even though you did this d518b1e9e5cc8cdaade6caeec2f721e16da06cab

fyi @cesar-polanco

**Pull request closed without merging**
