### PR TITLE
LPS-65790 - Product Menu, Info Panel and other side navs should use open class

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-65790

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 what happened here?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bf652bca21...f3ef3e571b

**Comment by pyoo47** [comment]
@brianchandotcom This is the Portal Freemarker taglib issue again.

**Comment by brianchandotcom** [comment]
Can you come explain to me about the FM issue? Thx.

**Pull request closed without merging**
