### PR TITLE
Lps 182109

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @achaparro

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
@brianchandotcom , Alberto will follow up to see whether certain pre/post steps are necessary to be split out explicitly.

**Comment by achaparro** [comment]
ci:close

**Comment by achaparro** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/525b211de2...874336ef8e

**Pull request closed without merging**
