### PR TITLE
OAUTH2-124 Merge REST module to master (4)

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Implemented feedback from brianchandotcom/liferay-portal/pull/57270
Please consider if 5e85411 is necessary. Thanks! :)

/cc @topolik @csierra

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test

**Comment by stian-sigvartsen** [comment]
ci:reopen

**Comment by stian-sigvartsen** [comment]
@brianchandotcom The failures don't appear to be related to this pull

**Comment by brianchandotcom** [comment]
@stian-sigvartsen can you resend on top of 

Is it possible to break up this big pull to smaller pulls? It's very tiring for me to constantly review this over and over again because of simple mistakes. I usually get through all my pull requests (this is the only pull I've had issues with).

In this case, 

```
public class AnnotationRequestScopeChecker
	implements RequestScopeCheckerFilter {
```

Needs to be renamed to AnnotationRequestScopeCheckerFilter.

Same for AnnotationRequestScopeCheckerTest.

One big pull can take months to merge... (which sucks), where as a big pull can get broken down into 10 small pulls and merged in 5-10 days. That's how I work with @ealonso

Please resend on top of https://github.com/stian-sigvartsen/liferay-portal/pull/79

This pull is so close, but I am very discouraged when I find mistakes that I've already fixed in other parts of the code. Please fix.

Thanks.

**Comment by brianchandotcom** [comment]
@mhan810 fyi, please see my comment above. Thx.

**Pull request closed without merging**
