### PR TITLE
LPD-19996 Sort

### PR DESCRIPTION
**Pull request by kevenleone**

### CODE REVIEW

**Comment by kevenleone** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@amosfong can you review this

I think that workspaces/liferay-marketplace-workspace/client-extensions/liferay-marketplace-etc-spring-boot/src/main/java/com/liferay/marketplace/util/AuthorizationUtil.java is something already available in client-extension-util-spring-boot.

I've also seen you do some things like this so I think @kevenleone may be duplicating some code. Please take this PR and help him. Thx.

**Comment by amosfong** [comment]
Hey Brian, showed Keven an example he can follow for DXP auth tokens. He'll update the PR

Also created https://liferay.atlassian.net/browse/LPD-20570 for updating the oauthmanager to handle requests to other system's oauth too

**Comment by kevenleone** [comment]
Thank you both!

I'll send another PR with the changes

**Pull request closed without merging**
