### PR TITLE
LPS-75319 Upgrading class names

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pyoo47 where are the test results?

**Comment by pyoo47** [comment]
@brianchandotcom Seems to be still running.. maybe it's frozen? I'm going to give it another 10 minutes...

**Comment by pyoo47** [comment]
@brianchandotcom It's running really slow for some reason but it's definitely not frozen. I think we just need to wait it out.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchiu** [comment]
@4lejandrito 
All the tests failed because there's a portal startup error. It's not happening on other pulls so maybe see if there's something in your pull that's causing it?

Here's the startup error.
```
     [exec] 04:41:10,067 ERROR [localhost-startStop-1][DBUpgrader:253] Unable to execute verify process: com.liferay.portal.verify.VerifyException: java.lang.Exception: Verification error: com.liferay.portal.verify.VerifyUUID
     [exec] com.liferay.portal.verify.VerifyException: com.liferay.portal.verify.VerifyException: java.lang.Exception: Verification error: com.liferay.portal.verify.VerifyUUID
     [exec] 	at com.liferay.portal.verify.VerifyProcess.verify(VerifyProcess.java:75)
     [exec] 	at com.liferay.portal.verify.VerifyProcessUtil._verifyProcess(VerifyProcessUtil.java:113)
     [exec] 	at com.liferay.portal.verify.VerifyProcessUtil._verifyProcess(VerifyProcessUtil.java:78)
     [exec] 	at com.liferay.portal.verify.VerifyProcessUtil.verifyProcess(VerifyProcessUtil.java:47)
     [exec] 	at com.liferay.portal.events.StartupHelper.verifyProcess(StartupHelper.java:182)
     [exec] 	at com.liferay.portal.events.StartupHelperUtil.verifyProcess(StartupHelperUtil.java:87)
     [exec] 	at com.liferay.portal.tools.DBUpgrader.verify(DBUpgrader.java:247)
     [exec] 	at com.liferay.portal.events.StartupAction.doRun(StartupAction.java:243)
     [exec] 	at com.liferay.portal.events.StartupAction.run(StartupAction.java:85)
     [exec] 	at com.liferay.portal.servlet.MainServlet.processStartupEvents(MainServlet.java:1333)
     [exec] 	at com.liferay.portal.servlet.MainServlet.init(MainServlet.java:269)
     [exec] 	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
     [exec] 	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1238)
     [exec] 	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1151)
     [exec] 	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1038)
     [exec] 	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4997)
     [exec] 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5289)
     [exec] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
     [exec] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
     [exec] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
     [exec] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
     [exec] 	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:585)
     [exec] 	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1794)
     [exec] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
     [exec] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [exec] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [exec] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [exec] 	at java.lang.Thread.run(Thread.java:745)
     [exec] Caused by: com.liferay.portal.verify.VerifyException: java.lang.Exception: Verification error: com.liferay.portal.verify.VerifyUUID
     [exec] 	at com.liferay.portal.verify.VerifyProcess.verify(VerifyProcess.java:75)
     [exec] 	at com.liferay.portal.verify.VerifyProcess.verify(VerifyProcess.java:92)
     [exec] 	at com.liferay.portal.verify.VerifyProcessSuite.doVerify(VerifyProcessSuite.java:30)
     [exec] 	at com.liferay.portal.verify.VerifyProcess.verify(VerifyProcess.java:72)
     [exec] 	... 27 more
     [exec] Caused by: java.lang.Exception: Verification error: com.liferay.portal.verify.VerifyUUID
     [exec] 	at com.liferay.portal.verify.VerifyProcess.doVerify(VerifyProcess.java:124)
     [exec] 	at com.liferay.portal.verify.VerifyUUID.doVerify(VerifyUUID.java:74)
     [exec] 	at com.liferay.portal.verify.VerifyUUID.doVerify(VerifyUUID.java:56)
     [exec] 	at com.liferay.portal.verify.VerifyProcess.verify(VerifyProcess.java:72)
     [exec] 	... 30 more
     [exec] Caused by: java.util.concurrent.ExecutionException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'lportal.MBThreadFlag' doesn't exist
     [exec] 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
     [exec] 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
     [exec] 	at com.liferay.portal.verify.VerifyProcess$$Lambda$97/31644960.accept(Unknown Source)
     [exec] 	at com.liferay.petra.function.UnsafeConsumer.accept(UnsafeConsumer.java:42)
     [exec] 	at com.liferay.petra.function.UnsafeConsumer.accept(UnsafeConsumer.java:30)
     [exec] 	at com.liferay.portal.verify.VerifyProcess.doVerify(VerifyProcess.java:117)
     [exec] 	... 33 more
     [exec] Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'lportal.MBThreadFlag' doesn't exist
     [exec] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
     [exec] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
     [exec] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
     [exec] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
     [exec] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
     [exec] 	at com.mysql.jdbc.Util.getInstance(Util.java:386)
     [exec] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1053)
     [exec] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4120)
     [exec] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4052)
     [exec] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2503)
     [exec] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2664)
     [exec] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2794)
     [exec] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
     [exec] 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2322)
     [exec] 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
     [exec] 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
     [exec] 	at com.liferay.portal.verify.VerifyUUID.verifyUUID(VerifyUUID.java:96)
     [exec] 	at com.liferay.portal.verify.VerifyUUID$VerifyUUIDCallable.call(VerifyUUID.java:118)
     [exec] 	at com.liferay.portal.verify.VerifyUUID$VerifyUUIDCallable.call(VerifyUUID.java:114)
     [exec] 	... 4 more
     [exec] 04:41:10,071 ERROR [localhost-startStop-1][MainServlet:272] com.liferay.portal.kernel.events.ActionException: com.liferay.portal.verify.VerifyException: com.liferay.portal.verify.VerifyException: java.lang.Exception: Verification error: com.liferay.portal.verify.VerifyUUID
     [exec] com.liferay.portal.kernel.events.ActionException: com.liferay.portal.verify.VerifyException: com.liferay.portal.verify.VerifyException: java.lang.Exception: Verification error: com.liferay.portal.verify.VerifyUUID
     [exec] 	at com.liferay.portal.events.StartupAction.run(StartupAction.java:91)
     [exec] 	at com.liferay.portal.servlet.MainServlet.processStartupEvents(MainServlet.java:1333)
     [exec] 	at com.liferay.portal.servlet.MainServlet.init(MainServlet.java:269)
     [exec] 	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
     [exec] 	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1238)
     [exec] 	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1151)
     [exec] 	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1038)
     [exec] 	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4997)
     [exec] 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5289)
     [exec] 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
     [exec] 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
     [exec] 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
     [exec] 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
     [exec] 	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:585)
     [exec] 	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1794)
     [exec] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
     [exec] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [exec] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [exec] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [exec] 	at java.lang.Thread.run(Thread.java:745)
     [exec] Caused by: com.liferay.portal.verify.VerifyException: com.liferay.portal.verify.VerifyException: java.lang.Exception: Verification error: com.liferay.portal.verify.VerifyUUID
     [exec] 	at com.liferay.portal.verify.VerifyProcess.verify(VerifyProcess.java:75)
     [exec] 	at com.liferay.portal.verify.VerifyProcessUtil._verifyProcess(VerifyProcessUtil.java:113)
     [exec] 	at com.liferay.portal.verify.VerifyProcessUtil._verifyProcess(VerifyProcessUtil.java:78)
     [exec] 	at com.liferay.portal.verify.VerifyProcessUtil.verifyProcess(VerifyProcessUtil.java:47)
     [exec] 	at com.liferay.portal.events.StartupHelper.verifyProcess(StartupHelper.java:182)
     [exec] 	at com.liferay.portal.events.StartupHelperUtil.verifyProcess(StartupHelperUtil.java:87)
     [exec] 	at com.liferay.portal.tools.DBUpgrader.verify(DBUpgrader.java:247)
     [exec] 	at com.liferay.portal.events.StartupAction.doRun(StartupAction.java:243)
     [exec] 	at com.liferay.portal.events.StartupAction.run(StartupAction.java:85)
     [exec] 	... 19 more
     [exec] Caused by: com.liferay.portal.verify.VerifyException: java.lang.Exception: Verification error: com.liferay.portal.verify.VerifyUUID
     [exec] 	at com.liferay.portal.verify.VerifyProcess.verify(VerifyProcess.java:75)
     [exec] 	at com.liferay.portal.verify.VerifyProcess.verify(VerifyProcess.java:92)
     [exec] 	at com.liferay.portal.verify.VerifyProcessSuite.doVerify(VerifyProcessSuite.java:30)
     [exec] 	at com.liferay.portal.verify.VerifyProcess.verify(VerifyProcess.java:72)
     [exec] 	... 27 more
     [exec] Caused by: java.lang.Exception: Verification error: com.liferay.portal.verify.VerifyUUID
     [exec] 	at com.liferay.portal.verify.VerifyProcess.doVerify(VerifyProcess.java:124)
     [exec] 	at com.liferay.portal.verify.VerifyUUID.doVerify(VerifyUUID.java:74)
     [exec] 	at com.liferay.portal.verify.VerifyUUID.doVerify(VerifyUUID.java:56)
     [exec] 	at com.liferay.portal.verify.VerifyProcess.verify(VerifyProcess.java:72)
     [exec] 	... 30 more
     [exec] Caused by: java.util.concurrent.ExecutionException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'lportal.MBThreadFlag' doesn't exist
     [exec] 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
     [exec] 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
     [exec] 	at com.liferay.portal.verify.VerifyProcess$$Lambda$97/31644960.accept(Unknown Source)
     [exec] 	at com.liferay.petra.function.UnsafeConsumer.accept(UnsafeConsumer.java:42)
     [exec] 	at com.liferay.petra.function.UnsafeConsumer.accept(UnsafeConsumer.java:30)
     [exec] 	at com.liferay.portal.verify.VerifyProcess.doVerify(VerifyProcess.java:117)
     [exec] 	... 33 more
     [exec] Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'lportal.MBThreadFlag' doesn't exist
     [exec] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
     [exec] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
     [exec] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
     [exec] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
     [exec] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
     [exec] 	at com.mysql.jdbc.Util.getInstance(Util.java:386)
     [exec] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1053)
     [exec] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4120)
     [exec] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4052)
     [exec] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2503)
     [exec] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2664)
     [exec] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2794)
     [exec] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
     [exec] 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2322)
     [exec] 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
     [exec] 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
     [exec] 	at com.liferay.portal.verify.VerifyUUID.verifyUUID(VerifyUUID.java:96)
     [exec] 	at com.liferay.portal.verify.VerifyUUID$VerifyUUIDCallable.call(VerifyUUID.java:118)
     [exec] 	at com.liferay.portal.verify.VerifyUUID$VerifyUUIDCallable.call(VerifyUUID.java:114)
     [exec] 	... 4 more
     [exec] Stopping the server due to unexpected startup errors
```

**Comment by brianchiu** [comment]
ci:close

**Comment by 4lejandrito** [comment]
Hi @brianchiu, 

Looks like you're right :) I'll fix and resend.

Thanks!

**Pull request closed without merging**
