### PR TITLE
LPS-60985 add title to all button items to make sure screen readers will read them

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @ealonso

**Comment by juliocamarero** [comment]
@sergiogonzalez @marcellustavares I have applied this to your apps too. Could you please have a look?

thank you!

**Comment by brianchandotcom** [comment]
@juliocamarero please resend? poshi. Or send to evan, thx.

**Comment by juliocamarero** [comment]
I think it's a random failure https://github.com/brianchandotcom/liferay-portal/pull/32933

**Pull request closed without merging**
