### PR TITLE
[TS] LPS-194720

### PR DESCRIPTION
**Pull request by MirnaGama**
Pull request resent on top of https://github.com/MirnaGama/liferay-portal/pull/9
 
> Original pull request comment:
> 
> ### Reproduction steps:
> 1. Setup DXP environment with a fake SMTP service
> 2. Configure the standard ‘out of the box’ Multi Factor One Time Password
>    For this, first check if it is not disabled at Control Panel > System Settings > Security > Multi-Factor Authentication (If it is unchecked, then it is enabled)
>    Then navigate to Control Panel > Instance Settings > Security > Multi-Factor Authentication > Multi-Factor Authentication and Email One-Time Password Configuration
> 3. Navigate to Time-Based One-Time Password Configuration option > Enable and Save
> 4. Navigate to User Profile Menu > Account Settings > Multi-Factor Authentication tab > Connect the user with an authenticator app (e.g. Google Authenticator) - use the QR code or the Shared Secret > After paired, enter the time based code to the portal
>    _Checkpoint:_ if it is successful, you will see a huge red info container after the page re-render itself
>    To make sure it is working > Log out > Log in, and use the authenticator app for the time-based code
> 5. If it is working, log out again > At logging in, select Forgot Password > Fill out the necessary information
> 6. Receive 'Forgot Password' email
> 7. Select the link in the email beware the "dot" (.) at the end of the link, set up new password > Submit
> 
> **Results:**
 _Expected:_ The user is redirected to the login page to be able to sign in, after the password change.
  _Actual:_ The user is not redirected to the login page to be able to sign in after the password change. They just got auto signed in to the portal.
> 
> ### Implementation details:
> * Create a Java filter in a web module. This filter is executed when the request arrives, that is to say, when the password update request arrives (when we paste the url from the mail in the browser). At this time, we can check if MFA is enabled and add a parameter in the request.
> * When the password update is executed (UpdatePasswordAction.java), the Java filter will have already been executed, so it should be enough to try to retrieve the parameter and if it exists, not to execute the login
>

### CODE REVIEW

**Comment by MirnaGama** [comment]
ci:reopen

**Comment by MirnaGama** [comment]
ci:test:sf

**Comment by MirnaGama** [comment]
ci:test:relevant

**Comment by MirnaGama** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/24a650dd07...a9fad0adf0

**Pull request closed without merging**
