### PR TITLE
LPS-65613 Get name from entry

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/00bac43e97...df9cba236c

**Comment by brianchandotcom** [comment]
@pyoo47 why are these all randomly failing at 6 minutes? It's happened twice now... at least.

**Comment by brianchandotcom** [comment]
@adolfopa This may be a better fix

See comments in acea5d0b51056c5cf54763c298b7745e43c09a2b

Thx

**Pull request closed without merging**
