### PR TITLE
Lps 108311

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6c187c1058...a755f4401d

**Comment by brianchandotcom** [comment]
@riccardo-ferrari @ivicac I backported this to 7.1.x.

**Comment by ivicac** [comment]
thx @brianchandotcom

**Comment by riccardo-ferrari** [comment]
much appreciated @brianchandotcom

**Pull request closed without merging**
