### PR TITLE
LRQA-51488 Fix typo

### PR DESCRIPTION
**Pull request by brianwulbern**
@brianchandotcom This is just a typo fix, so I don't want to run ci:forward repeatedly to finally make it forward.  It already [passed everything](https://github.com/brianwulbern/liferay-portal/pull/268#issuecomment-616281959) except for a failure in common with head.

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c34fcbcb8e...43db0c4d85

**Comment by brianchandotcom** [comment]
@brianwulbern sounds good.

**Comment by brianchandotcom** [comment]
@brianwulbern I regenerated in c3fe9f2af73a694df4351498ce242f0da18bbe33 and backported all the way to 7.1.x.

**Pull request closed without merging**
