### PR TITLE
LPS-83331

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @brianchandotcom,

There's an SF error due to the usage of ServiceContext in an
interface. The implementation is in a `-service` module and the
interface in an `-api` one; this last one is failing because the
package is not called `service`.

Could we make an exception to the rule here? I don't think this
interface belongs to the service package (it is a simple helper), and
we cannot remote the ServiceContext from the signature -- it calls
some DL services that require it.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:open

**Comment by adolfopa** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:close @adolfopa the SF error is related.

**Comment by sergiogonzalez** [comment]
ci:open

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by jpince** [comment]
@adolfopa @sergiogonzalez very sorry about this, I should have read the description Adolfo wrote.

cc/ @petershin can you please talk to Brian about this today? they are making these changes because Brian asked them to.

**Comment by petershin** [comment]
@jpince - Sure, will follow up with Brian

**Comment by brianchandotcom** [comment]
hey @adolfopa the requirement to not allow any new "serviceContext" ones for APIs came from @jorgeferrer

He wanted to ensure that required params were explicit and not hidden in a big object.

Also, see BackgroundTaskManager and WorkflowDefinitionManager, we generally avoid *.manager.*

Can you resend this to me with just the *-api module. I want to move things around easier and get that right first.

I went ahead and merged in the extension point in 5144021d369c58551c116a97cb912a13cdedf33f (and even backported that part)

Please resend the api to me first. Thx.

**Pull request closed without merging**
