### PR TITLE
LPS-107756 Don't export description if it is empty

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
//cc @ealonso

**Comment by ruben-pulido** [comment]
//cc @jkappler

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by brianchandotcom** [comment]
Can you resend:

FragmentExportImportConstants

	public static final String FILE_NAME_COLLECTION_CONFIG = "collection.json";

	public static final String FILE_NAME_FRAGMENT_CONFIG = "fragment.json";

LayoutPageTemplateExportImportConstants

	public static final String FILE_NAME_COLLECTION_CONFIG =
		"page-template-collection.json";

	public static final String FILE_NAME_PAGE_TEMPLATE_CONFIG =
		"page-template.json";

Can you reconcile these names? They don't seem consistent to me. One matches the fille name, the other does not. Please resend. Thx.

**Comment by jkappler** [comment]
Just started reviewing :)

**Pull request closed without merging**
