### PR TITLE
LPS-105404 Buildlang

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@inacionery fyi

```
Duplicate entry '20096-com.liferay.portal.workflow.kaleo.designer-4-com.liferay.p' for key 'IX_A9FF4B2C'
	at com.liferay.portal.log.assertor.PortalLogAssertorTest.scanXMLLogFile(PortalLogAssertorTest.java:172)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:98)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:88)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	
```

**Comment by brianchandotcom** [comment]
@pavel-savinov can you resend on top of https://github.com/pavel-savinov/liferay-portal/pull/470

LayoutConversionPreviewMVCActionCommand.java should start with a verb

Update*

Preview*

Add* etc.

also, see b4e6c47f643c2930e68efef1cbb62acf96a453cd

**Comment by inacionery** [comment]
Hey @brianchandotcom,

We created this issue https://issues.liferay.com/browse/LPS-105888 to track it.

Thanks!

**Pull request closed without merging**
