### PR TITLE
master-vw-357

### PR DESCRIPTION
**Pull request by vicnate5**
@brunobasto @leoadb @fernandosouza @pedroqueiroz94

### CODE REVIEW

**Comment by pedroqueiroz94** [comment]
Awesome, @vicnate5 . Thanks. =)

**Comment by sharonchoi** [comment]
@brianchandotcom, the errors found here are unrelated, and are caused by these two issues: https://issues.liferay.com/browse/LPS-65969 and https://issues.liferay.com/browse/LPS-65878. This is ok to merge.

@brianchiu @kenjiheigel just FYI, 612Upgrade#View612DataArchive is failing as well due to `java.lang.Exception:  ## ## 1 Liferay Exception was thrown ##  LIFERAY_ERROR: [com.liferay.portal.search.internal.SearchEngineHelperImpl(158)] The addSearchEngineConfigurator method has thrown an exception `

**Comment by brianchandotcom** [comment]
@pedroqueiroz94 @fernandosouza @brunobasto please see my changes in upstream. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b89468dfb9...2db43526cf

**Comment by brianchandotcom** [comment]
@shuyangzhou can you work with @tinatian to fix SearchEngineHelperImpl. The restart issue in https://issues.liferay.com/browse/LPS-65878 makes it so tests are flaky. Thx.

**Comment by tinatian** [comment]
Hi @brianchandotcom and @shuyangzhou,

The fix is done, but need to be merged after LPS-65896 is merged. Since the restarting of cluster related bundles also have same problems with restarting of cache related bundles.

Tina.

**Pull request closed without merging**
