### PR TITLE
LPS-86806

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@brianchandotcom, I'll backport this

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
@brianchandotcom, please update `git-commit-portal-private`

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@hhuijser updated hash

**Pull request closed without merging**
