### PR TITLE
Axis Support: don't bundle the .wsdd files, will be provided by a fragment

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by migue** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@migue please ignore test error, that's random. fyi @brianchiu

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/12d8561911...3fca582f66

**Comment by brianchiu** [comment]
@alee8888 @brianxlee

In the first failure - there was a console error for wildfly
```
java.io.FileNotFoundException: /opt/dev/projects/github/liferay-portal/bundles/wildfly-10.0.0/standalone/tmp/ROOT.war/proxytemp/hc_16594999/sprite/images/user-vertical-images_sprite.properties (No such file or directory)
```

CPCustomfields#AddCustomFieldUserBoolean failure looks to be random. Can you guys check?

**Comment by alee8888** [comment]
@brianchiu @xbrianlee
I opened the following LRQA ticket to look into this (https://issues.liferay.com/browse/LRQA-23007). I have not seen this error before and it is not a known issue. I also tried running the test locally in a clean Wildfly bundle and running using build-test-wildfly.xml to run the test and could not reproduce.

I will investigate more into this if I see this error again.

**Pull request closed without merging**
