### PR TITLE
LPS-70058

### PR DESCRIPTION
**Pull request by lionah**
Added column for some new DB feature that relies on companyId column

### CODE REVIEW

**Comment by jpince** [comment]
@lionah this one's yours
```
     [java] Add the string '(uuid_, ' to the previous literal string: ./modules/apps/marketplace/marketplace-service/src/main/java/com/liferay/marketplace/internal/upgrade/v2_0_1/UpgradeModule.java 35
     [java] Add the string 'moduleId ' to the previous literal string: ./modules/apps/marketplace/marketplace-service/src/main/java/com/liferay/marketplace/internal/upgrade/v2_0_1/UpgradeModule.java 48
     [java] Exception in thread "main" java.lang.Exception: Add the string '(uuid_, ' to the previous literal string: ./modules/apps/marketplace/marketplace-service/src/main/java/com/liferay/marketplace/internal/upgrade/v2_0_1/UpgradeModule.java 35
     [java] Add the string 'moduleId ' to the previous literal string: ./modules/apps/marketplace/marketplace-service/src/main/java/com/liferay/marketplace/internal/upgrade/v2_0_1/UpgradeModule.java 48
```
http://test-1-18/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/75169//consoleText

**Comment by lionah** [comment]
yep already resent https://github.com/brianchandotcom/liferay-portal/pull/46069, thanks @jpince

**Comment by lionah** [comment]
@jpince does CI run a different SFer? This was not thrown prior to me sending this pull locally.

**Comment by jpince** [comment]
I don't think so? But SF is a black box to me, that's a better question for @hhuijser

**Comment by hhuijser** [comment]
@lionah @jpince 
As far as I know CI does not run a different version of SF. Only thing I can think of that you running older version of SF?

**Pull request closed without merging**
