### PR TITLE
LPS-74881 SF

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:reopen

**Comment by brunobasto** [comment]
Failures don't look related.

@xbrianlee can you confirm?

Thx

**Comment by xbrianlee** [comment]
@brunobasto Yup, these failures are unrelated to your changes 👍

**Comment by brunobasto** [comment]
Awesome! Thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/79bccb506c...c2db4a737d

**Pull request closed without merging**
