### PR TITLE
LPS-57777 Solr: 15 seconds before docs available with example solrconfig.xml

### PR DESCRIPTION
**Pull request by arboliveira**
Author: @arboliveira
Reviewer: @mhan810

Fixed mistake caused test failures in original https://github.com/brianchandotcom/liferay-portal/pull/29269, hoping there aren't any others :sweat_smile:

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Nice job @arboliveira  :)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/549f19cdfc...94d354a396

**Comment by brianchandotcom** [comment]
@arboliveira please see my changes in upstream.

@shuyangzhou fyi on search test fixes.

**Comment by brianchandotcom** [comment]
@arboliveira does this affect the Cluster tests that are ignored? Is this a prerequisite to fixing those? Thx.

**Comment by arboliveira** [comment]
@brianchandotcom Not related to the ignored Cluster tests, had already been working on the Solr stuff for a while before they came up. There is however a common underlying principle: asserting slow search engine operations that can't be reliably force sync'd (increase of cluster size in Elasticsearch, or, any update command in Solr at all ever since we dropped forced commits a few months ago) so I'm hoping a common solution is possible. Gonna contact @shuyangzhou to understand why would Elasticsearch in CI behave unusually slow as of lately.

**Comment by shuyangzhou** [comment]
@arboliveira why are you removing all the @ sync? Now tests start to fail again. See https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=4,label_exp=!master/5216/testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXmlLog/

The @ sync is not just for search. And if you really want to remove @ sync, you should not keep the SynchronousDestinationTestRule.INSTANCE still in use.

**Pull request closed without merging**
