### PR TITLE
LPS-68072 Automatically convert WYSIWYG portlet instances to Web Content Display instance

### PR DESCRIPTION
**Pull request by peterfellwock**
@brianchandotcom @shuyangzhou moved to modules/apps/journal-wysiwyg-upgrade

### CODE REVIEW

**Comment by peterfellwock** [comment]
ci:reopen

**Comment by peterfellwock** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@peterfellwock all Wysiwyg should be WYSIWYG (I mentioned that when I closed the pull earlier).

**Pull request closed without merging**
