### PR TITLE
LPS-167597 Update portletId following to CETDeployer that any non-word character on ERC should be replaced to underline

### PR DESCRIPTION
**Pull request by ces-binhtran**
Manually forward because of unrelated failures
The PR was tested here: https://github.com/liferay-frontend/liferay-portal/pull/2855

### CODE REVIEW

**Comment by binhtran92** [comment]
ci:reopen

**Comment by binhtran92** [comment]
Hi @brianchandotcom , could you help to review this PR? 
It is related to the [LPP-47079](https://issues.liferay.com/browse/LPP-47079) with high priority.

**Comment by brianchandotcom** [comment]
@binhtran92 this fix does'nt make sense? 1.) If I already ran the upgrade, then this will never run. 2.) This only fixes existing data and not the GUI which I assume could create the wrong data in the future?

**Comment by binhtran92** [comment]
Hi @brianchandotcom ,
1. This could be introduced as a new upgrade process but from what I understand the portlet name never registers with the raw externalReferenceCode, checking the history, it always formats with the underline character [CETDeployerImpl.java#L118-L127](https://github.com/brianchandotcom/liferay-portal/blob/master/modules/apps/client-extension/client-extension-web/src/main/java/com/liferay/client/extension/web/internal/type/deployer/CETDeployerImpl.java#L118-L127). So I believe the queries on this upgrade process doesn't take effect.
2. The portletId is generated by concatenating between the **prefix_companyId_erc** on the CETDeployer, I don't see any GUI relevant. 

As this ticket is a bit urgent then I need your guidance to understand what is expected so that I can deliver a better solution for the customer.

Thank you.

**Pull request closed without merging**
