### PR TITLE
LPS-80777 Auto

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pavel-savinov 

```
	public LayoutPageTemplateEntry addLayoutPageTemplateEntry(
			long userId, long groupId, long layoutPageTemplateCollectionId,
			String name, int type, long[] fragmentEntryIds, int status,
			long layoutPrototypeId, ServiceContext serviceContext)

```

the location of layoutPrototypeId doesn't match in service.xml

```
layoutPageTemplateEntry.setLayoutPrototypeId(layoutPrototypeId);
```

doesn't match either

@ealonso please resend.

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/58578

**Comment by ealonso** [comment]
cc: @pavel-savinov @jkappler

**Pull request closed without merging**
