### PR TITLE
LPS-133987 Revert

### PR DESCRIPTION
**Pull request by tinatian**
Hi Brian,
This is the root cause of random unsatisfied component issue, let's revert it for now, I will work on my fix and see if it can be fixed, and send this and the fix back.

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7aa7fa23f8...3bc7eaf3ac

**Comment by brianchandotcom** [comment]
@shuyangzhou @ngriffin7a fyi for now.

**Comment by brianchandotcom** [comment]
@shuyangzhou @ngriffin7a fyi for now.

@tinatian , I know what it is!

I'ts my fault it's becuase I modified ReleaseInfo.

See https://github.com/brianchandotcom/liferay-portal/pull/103800/commits/2c0db6dd57f73b57935e6f52a96850799976e4bd

I'm recommiting this, but without my accidental changes to ReleaseInfo.

**Pull request closed without merging**
