### PR TITLE
LPS-105228 extensability vulcan

### PR DESCRIPTION
**Pull request by javiergamarra**
--rebased

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ad96f7d7cb...a51000397d

**Comment by brianchandotcom** [comment]
@nhpatt beautiful...

See my tiny changes in 97405dfd5ffbb39fd2b2cbbbbc0248bcdd11cc8c and a51000397d32e1eae7e3fc2148529f1204c27e06

Can you backport to 7.2.x and 7.1.x for me?

When you backport, follow the pattern in modules/apps/asset/asset-categories-service/moved-packages.txt

You can say that "com.liferay.headless.delivery.dto.v1_0.converter" got "moved" to prevent a major breaking change in 7.2.x and 7.1.x. It's OK in this case since we're the only ones consuming it.

**Comment by brianchandotcom** [comment]
Oh, also 9d3a211

**Comment by nhpatt** [comment]
Done!

**Pull request closed without merging**
