### PR TITLE
LPS-56182 SF

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@marcellustavares this is good. I'll merge it in.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/78775aeedc...48b055f5d1

**Comment by brianchandotcom** [comment]
```
	private static final ServiceTracker
		<DDMFormJSONSerializer, DDMFormJSONSerializer> _serviceTracker;

	static {
		Bundle bundle = FrameworkUtil.getBundle(
			DDMFormJSONSerializerUtil.class);

		_serviceTracker = new ServiceTracker<>(
			bundle.getBundleContext(), DDMFormJSONSerializer.class, null);

		_serviceTracker.open();
	}
```

I feel like that can be one line of code if we added a ServiceTrackerUtil to modules/util/osgi-util.

Do you mind adding a helper util class/method and then switching all of our existing modules to using that anytime we service? It'd save a lot of code.

Thx @marcellustavares

**Pull request closed without merging**
