### PR TITLE
LPS-163003 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-163003

This is only for master.

@JavierMoral
cc @ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure cases are unrelated to changes.
See https://github.com/liferay-echo/liferay-portal/pull/9620
❌ ci:test:stable - 27 out of 28 jobs passed
❌ ci:test:relevant - 152 out of 168 jobs passed in 2 hours 24 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/de6fd2bc48...b61144dc96

**Comment by brianchandotcom** [comment]
@JavierMoral see c19681e8945741c878825e06573be925c23972e7 and b61144dc96b1a1eeb3119080dd14d9cd67906307

**Pull request closed without merging**
