### PR TITLE
LPS-68898 Improve code comment to clarity that the export is for the Group-scoped embedded portlets only

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/eb6813dcba...4c71682fcb

**Comment by brianchandotcom** [comment]
@ealonso @JorgeFerrer can we add a test? See 4c71682fcb853a0f0a0520433c801d733815bf5c as well.

Thx.

**Comment by ealonso** [comment]
@brianchandotcom, @JorgeFerrer 

Sure, I'm going to add a new test for this.

**Comment by ealonso** [comment]
Hey @JorgeFerrer, @brianchandotcom,

Here is the pull request with the test: https://github.com/brianchandotcom/liferay-portal/pull/46217

**Pull request closed without merging**
