### PR TITLE
LPS-66396

### PR DESCRIPTION
**Pull request by Ithildir**
cc @david-truong

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7298c881b5...c4c77ca822

**Comment by brianchandotcom** [comment]
@codyhoag please see change log in upstream. Thx.

**Pull request closed without merging**
