### PR TITLE
LPS-65810

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by sharonchoi** [comment]
POSHI failure due to https://issues.liferay.com/browse/LPS-65843 introduced through https://github.com/brianchandotcom/liferay-portal/pull/39741

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1a7d58360d...34840a1cb2

**Comment by brianchandotcom** [comment]
@hhuijser can you enforce the bnd changes in this pull? We want to avoid .* of packages and force ppl to list them out as a best practice.

@Ithildir the polls-api baseline is actually an error in baseline. We changed a String value for a polls portlet key, and we actually want to force a new version even though baseline doesn't think it's necessary.

**Comment by hhuijser** [comment]
@brianchandotcom 
We use a lot of wildcards in *.bnd.
Do we want to allow for third party?

@Ithildir, I can send a pull with the SF check to you?

**Comment by Ithildir** [comment]
Hi @hhuijser! In this pull, I only removed the `.*` for `com.liferay` packages... You can send me the pull, absolutely! :blush:

**Pull request closed without merging**
