### PR TITLE
LPS-48156 Introduce ConfigurationException class (first part)

### PR DESCRIPTION
**Pull request by pei-jung**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pei-jung Can we talk about the name ConfigurationException? It's weird to me. We have a Configuration class, but this doesn't seem to have anything to do with it.

PrincipalException matches PrincipalBean and PrincipalThreadLocal

But ConfigurationException doesn't seem to match anything?

**Comment by pei-jung** [comment]
Sure. Let me know when you're available so we can talk about this.

**Pull request closed without merging**
