### PR TITLE
LPS-142517 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-142517

This is only for master.

@ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure cases are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/7818
❌ ci:test:stable - 38 out of 44 jobs passed
❌ ci:test:relevant - 38 out of 45 jobs passed in 2 hours 8 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d935102bcb...0bbaa7a4cd

**Comment by brianchandotcom** [comment]
@Tim-Cao @ealonso see also b4a7a296d838dc5be1c45be6646a1380a384cc70

**Pull request closed without merging**
