### PR TITLE
LPS-73481 Set 7.1 as Liferay version in master

### PR DESCRIPTION
**Pull request by achaparro**
Depends on https://github.com/brianchandotcom/liferay-portal-ee/pull/18244

### CODE REVIEW

**Comment by achaparro** [comment]
ci:stop

**Comment by achaparro** [comment]
ci:retest

**Comment by jpince** [comment]
ci:close

**Comment by jpince** [comment]
same failures as https://github.com/brianchandotcom/liferay-portal/pull/50888#issuecomment-321819318, investigating

**Comment by brianchandotcom** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
I think once we link it to master-private it should work.

**Comment by xbrianlee** [comment]
Test failures should be fixed after https://github.com/brianchandotcom/liferay-plugins/pull/5403

**Comment by achaparro** [comment]
That's it!

Thanks @xbrianlee !

**Comment by brianchandotcom** [comment]
@achaparro 

I only partially merged your changes.

1.) The main thing is that I do not want to update the DTD headers unless we have to. It's like if we deployed a web.xml pointing to servlet 2.3, but the app server supported 2.4. It should still work and it's OK.

In your next pull, I would like you to fix liferay-plugin-package.properties and all relevant xml files in:

liferay-portal: master, master-private, 7.0.x, 7.0.x-private
liferay-plugins: master, 7.0.x-private (since we don't have master-private and 7.0.x yet).
 
If the current file says:

liferay-version=7.0.0+

Change it to:

liferay-version=7.0.0+,7.1.0+

Do the same logic when it's <version> for XML files.

For private, it should say:

liferay-version=7.0.10+

Change it to

liferay-version=7.0.10+,7.1.10+

2.) Regarding exploded-test-theme.zip, it should also contain the extra compatibility so the same file can work for both branches. 

3.) Once that's all done, then you should be able to send me a pull updating portal master's actual version. And you can revert 8d143c54c791d65eed4872a7d500d1e0045bf7e1. This allows us to lazy change this instead of sending a big commit.

Thx

**Comment by brianchandotcom** [comment]
@jpince @xbrianlee fyi.

**Pull request closed without merging**
