### PR TITLE
LPS-55591 Extract UsersAdmin and MyAccount portlets to OSGi

### PR DESCRIPTION
**Pull request by pei-jung**
/cc @jorgeferrer @drewbrokke

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1b2167bb4e...89c01a6024

**Comment by brianchandotcom** [comment]
Hi @pei-jung 

1.) Regarding db9a68bab213621c222e46f099a010e48d5c1fb4

When you move the others out of core, make sure that those copy in this css file via bnd so we have less code duplication. Thx

2.) Same for f7f3257e8f380826b5740a17d7a4cfa899ec9485

These types of things were linked for a reason. We need to find a way to not lose those links. Please write down these commits, and we need to revisit them, and use bnd to copy a local version to this module. Or better yet, make that common code a taglib.

3.) For 6009b94475ac59750b41ee725fa6cfb70087784f

Look at Language_cs.properties. Because you did a rename and then a regen, you lost all the translations. I fixed it in 

d95b12469e1b7f2bc7ade03223a049d5ad151969 and 204367e6304a426142ca651d04173d2c52bef0bc

4.) portletId != portletNamespace

See 71a0ec6dbbbe924fd3ede35c2632cf95ea9bf401 and 5895956a41d1d1876ca44fd59c5846cc48442685

5.) When I run "ant build-lang" in users-admin-web, I get a lot of duplicate keys. Language keys that are used by more tha one module should be in core. Imagine the Chinese translator, they would have to translate the same key in many modules. That would be painful. I explained the same thing to Drew. 

```
$ ant build-lang
Buildfile: /Users/brian/dev/projects/github/liferay-portal/modules/apps/users-admin/users-admin-web/build.xml

build-lang:

build-lang-cmd:
     [java] Loading jar:file:/Users/brian/dev/bundles/master/tomcat-7.0.62/webapps/ROOT/WEB-INF/lib/portal-impl.jar!/system.properties
     [java] Duplicate key a-user-with-that-open-id-already-exists
     [java] Duplicate key add-user
     [java] Duplicate key add-x
     [java] Duplicate key additional-email-addresses
     [java] Duplicate key are-you-sure-you-want-to-delete-this
     [java] Duplicate key assign-members
     [java] Duplicate key assign-users
  ...
     [copy] Copying 1 file to /Users/brian/dev/projects/github/liferay-portal/modules/apps/users-admin/users-admin-web/src/content
```

6.) I'm very impressed with this pull. You did a great job. The commit log and the changes were very easy to read. They make sense, and I know this extraction was a difficult task! Bravo.

**Comment by pei-jung** [comment]
Thanks, Brian. Regarding duplicate keys, that makes sense. I'll remove them and send you a pull for it.

**Pull request closed without merging**
