### PR TITLE
LPS-74615 Upgrade license manager web for current DXP users

### PR DESCRIPTION
**Pull request by achaparro**
Hi @daviddotzhang,

Thank you for your work, it solves the issue. Please, check my modifications since they call to BaseUpgradePortletId to cover all table modifications.

Let me know if everything is ok.

Also, please, backport all the commits related to LPS-74615 once Brian approves this one. I will try to get that this fix is included in the fix pack 40.

Cheers!

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test

**Comment by achaparro** [comment]
ci:reopen

**Comment by achaparro** [comment]
The error doesn't be related

**Comment by achaparro** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c60a551ceb...46979a3d8a

**Comment by brianchandotcom** [comment]
@achaparro see 46979a3d8a13e64468713bcd2d461d1c895a5217

**Pull request closed without merging**
