### PR TITLE
LPS-64319 system.packages.extra.mf

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @adolfopa

**Comment by sharonchoi** [comment]
investigating, please do not merge, there may be a bug.

**Comment by sharonchoi** [comment]
@brianchandotcom PGTags tests are failing due to the following bug at head on master: https://issues.liferay.com/browse/LPS-66724

**Comment by brianchandotcom** [comment]
@sergiogonzalez can you resend?  Want to make sure it's not a bug (also have a rebase issue). Thanks.

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/41076

**Pull request closed without merging**
