### PR TITLE
LPS-102092 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-102092

### CODE REVIEW

**Comment by kyle-miho** [comment]
Fixes Portal Smoke failure in stable
https://github.com/brianchandotcom/liferay-portal/pull/81374
cc: @jbalsas

**Comment by kyle-miho** [comment]
ci test relevant failed since this is more up to date than upstream, can't rebase off of liferay otherwise there will be a merge conflict

**Comment by kyle-miho** [comment]
ci:test:relevant:norebase

**Comment by kyle-miho** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
@eduardoallegrini @jbalsas fyi this fixes a bug you guys introduced.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/eb9ea6a5ca...d34f044e5b

**Comment by eduardoallegrini** [comment]
Thank you

**Pull request closed without merging**
