### PR TITLE
LRQA-68958 | master

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LRQA-68958

### CODE REVIEW

**Comment by epark18** [comment]
ci:reopen

**Comment by epark18** [comment]
ci:test:sf

**Comment by epark18** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/953e386879...997cf54fe8

**Comment by brianchandotcom** [comment]
@epark18 see 45f8bf90b24540474c8e2ea3ba6324d8b4e26c92

**Pull request closed without merging**
