### PR TITLE
LPS-135551

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@interaminense @gabrielwas can you take a look at this PR? My biggest confusion is over edit_object_definition.jsp and view_object_definition.jsp. They both seem like edit to me?

The naming of EditObjectDefinitionDisplayContext for view_object_definition.jsp threw me off.

Let's chat about this tomorrow.

@marco-leo fyi

**Comment by brianchandotcom** [comment]
ci:reopen

**Comment by marco-leo** [comment]
@brianchandotcom for the UI I tryied to respect the existing code, but I think in portal we have better pattern for this, will send an example in couple of mins

**Comment by marco-leo** [comment]
sent to https://github.com/brianchandotcom/liferay-portal/pull/105987

**Comment by marco-leo** [comment]
ci:close

**Pull request closed without merging**
