### PR TITLE
LPS-116042 Update portal-search-elasticsearch6 app.bnd

### PR DESCRIPTION
**Pull request by joshchong**
https://issues.liferay.com/browse/LPS-116042

### CODE REVIEW

**Comment by joshchong** [comment]
ci:test:sf

**Comment by joshchong** [comment]
@jpince Can you take a quick look at these changes? Two that I'm unsure of are `Liferay-Releng-Deprecated` and `Liferay-Releng-Marketplace` which I tried to set to true and false respectively but SF was complaining due to these rules: [bnd_suite_check.markdown](https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/checks/bnd_suite_check.markdown)

If things look good, we can reopen this PR.

**Comment by jpince** [comment]
@joshchong looks good, I will reopen this pull. 

Releng-Marketplace can continue to be true, no harm in that. This is kindof an obsolete property anyways.

Related to Releng-Deprecated, the Search team should have a separate conversation about what to do with the code:

1. The es6 modules will continue to be published, unless the team adds the `.lfrbuild-releng-ignore` file. This is not a problem for me and Brian Chan, but maybe Andre cares about this.
1. The es6 code could be moved to the archived folder, or just deleted. I think since we're upgrading to a new version and we don't plan on supporting es6 for 7.3, then no deprecation process is needed (either in app.bnd, archived folder, or anywhere else). 

Let me know if you have any questions. Thanks again!

**Comment by joshchong** [comment]
ci:test:sf

**Comment by joshchong** [comment]
ci:reopen

**Comment by joshchong** [comment]
ok got it thanks @jpince! FYI @arboliveira see Jason's comment above.

**Comment by jpince** [comment]
@joshchong just test with sf locally. On a quick glance, it looked ok, but never hurts to check :)

**Comment by joshchong** [comment]
@jpince haha yeah I did, but I was just wanted to double check since sometimes results differ on CI. I ended up testing it in a self PR and it passed:
https://github.com/joshchong/liferay-portal/pull/325#issuecomment-648430141

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/131008c4bc...d22c0819f0

**Comment by brianchandotcom** [comment]
@joshchong ok.. I'm merging, if things don't sync, please send me a revert.

**Pull request closed without merging**
