### PR TITLE
LPS-65693 SF

### PR DESCRIPTION
**Pull request by rotty3000**
Second attempt /cc @alee8888

### CODE REVIEW

**Comment by rotty3000** [comment]
ok, at least we have results.... I'll clean up!

**Comment by brianchandotcom** [comment]
Nice!

**Comment by brianchandotcom** [comment]
@rotty3000 CI has lots of failures upstream right now that are known, so as long as the lpgk-startup-jdk7 batch works, we should be good.

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/40124

**Pull request closed without merging**
