### PR TITLE
LPS-91420

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@brianchandotcom, these are the cases that are skipped: https://github.com/brianchandotcom/liferay-portal/pull/68800/commits/976d5b673794314020f812d1c765d0fad259fef4

**Comment by hhuijser** [comment]
@brianchandotcom don't (try to) backport anything, I'll take care of it

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
ci:test:sf

**Comment by hhuijser** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@hhuijser see 136c1f32399f8e06b7b8ad8b4b286291878e16de

**Pull request closed without merging**
