### PR TITLE
Lps 96018

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @slnn

### CODE REVIEW

**Comment by jpince** [comment]
@vicnate5 looks like a widespread change, not sure how significant

**Comment by vicnate5** [comment]
ci:test:documents

**Comment by vicnate5** [comment]
Test failures not related.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1d7b4ddafd...f61be25e0d

**Comment by brianchandotcom** [comment]
@shuyangzhou can you resend? For the ServiceBuilder apply, I need an easy way for this to work for older versions. That means if it's 7_2_0 or below, inline that helper method (generate it) or else it'll be an upgrade nightmare for implementors.

Thx.

**Comment by shuyangzhou** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/73697

**Pull request closed without merging**
