### PR TITLE
LPS-86006 Uses right constant

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchiu** [comment]
Alright. We're looking.

**Comment by brianchiu** [comment]
ci:reopen

**Comment by brianchiu** [comment]
All those failures are happening in upstream.
* Navigation menus failure fix is here: https://github.com/brianchandotcom/liferay-portal/pull/64459
* We'll have fix the ADT failure.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7076cfe563...39386682c8

**Pull request closed without merging**
