### PR TITLE
LPS-69279 Use recursion from DEFAULT_PLID to avoid database updates for each top level layouts

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Hey @matethurzo 

this change affects mainly staging. Can you please double check? 

@kmaria this may change the selected nodes in the three of publication of pages.

Thank you!

**Comment by juliocamarero** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8ec9164572...fe01b9be67

**Comment by matethurzo** [comment]
@juliocamarero @moltam89 looks good, thanks!

**Pull request closed without merging**
