### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Only unrelated failure, see https://github.com/hhuijser/liferay-portal/pull/5134

**Comment by hhuijser** [comment]
@marco-leo this one addresses https://github.com/liferay/liferay-portal/commit/75a599a0c17ea04a21cf00aed7ff28ec9fc361a6

However, a lot of SF checks are completely disabled for all commerce files, see https://github.com/liferay/liferay-portal/blob/master/modules/apps/commerce/source-formatter-suppressions.xml
We have all lines with `files=".*"`, can you have someone in your team have a look at this, and see if we can start applying these checks to commerce?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/edaa64cb57...736cdfd90e

**Comment by brianchandotcom** [comment]
@hhuijser I didn't backport any of the last few SF pulls from you, feel free to send me 7.3.x pulls as you see fit. Diverged too much now.

**Comment by brianchandotcom** [comment]
@marco-leo we need to start undoing the .* suppressions! I know we did it just to get it into master.. but time to clean them up.

@dsitu please help start cleaning this up.

@hhuijser can you also start cleaning them up for them? I want to you to start the clean up process as well in case the Commerce team is too busy to clean up their older code. Please coordinate with @dsitu

**Pull request closed without merging**
