### PR TITLE
LPS-168385 HR_326 SR is announcing the "Back icon" as "Back link" on add new custom field page

### PR DESCRIPTION
**Pull request by Tim-Cao**
This is only for master.

https://issues.liferay.com/browse/LPS-168385

@veroglez

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/11223

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/64ca02acaa...7452a2d294

**Comment by brianchandotcom** [comment]
@ealonso @veroglez bravo for understanding our weird grammar of backURL vs. urlBack

Props.

**Pull request closed without merging**
