### PR TITLE
LPS-75323

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:reopen (@shuyangzhou modules-unit is flaky right now)

**Comment by brianchandotcom** [comment]
@hhuijser can you resend this?

     adaptive-media-image-service,     chat/chat-service,  

has lots of white spaces in the excludes.

Also, will this excludes check work for 7.0.x too? Don't want to backport and then get an issue. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f4b9324b02...20ecf36e78

**Comment by shuyangzhou** [comment]
Fixed at https://github.com/brianchandotcom/liferay-portal/pull/52421

**Pull request closed without merging**
