### PR TITLE
LPS-107669 Remove Karma usage from portal-workflow-kaleo-designer-web

### PR DESCRIPTION
**Pull request by wincent**
This is task 2 of 3 necessary to remove Karma from all of liferay-portal (IFI-1371), and moves us from the brittle Karma-based test infrastructure to the Jest.

Collateral benefit of this change: test run time drops from 6.5 seconds to 4 seconds.

Some "hackery" was needed to force the Alloy dependencies to play nicely in the Jest environment; this is visible in the pre-test setup.js file and in the `beforeEach()` setup callbacks.

### CODE REVIEW

**Comment by wincent** [comment]
cc @inacionery

**Comment by wincent** [comment]
Going to close this and bundle it together with the changes for LPS-107734; that way I can clean out all traces of Karma in one go without any rebase errors.

**Comment by wincent** [comment]
Ha, actually no; I realized I still have a few more tests to port for LPS-107734 and may not finish them all today so I may as well leave this one open.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c6f10913d7...2538abe75e

**Pull request closed without merging**
