### PR TITLE
LPS-65291

### PR DESCRIPTION
**Pull request by ChrisKian**
Sending to you as per @sergiogonzalez's request.

https://issues.liferay.com/browse/LPS-65291

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:retest

**Comment by AngeloJ** [comment]
ci:retest

**Comment by ChrisKian** [comment]
Hi @brianchandotcom,

These failing tests seem to have nothing to do with my changes.  The errors deal with missing dependencies on modules and unable to delete resourcePermissions; my changes only affect blogs.

Thanks!

**Comment by brianchandotcom** [comment]
@ChrisKian can you resend? Lots of changes in upstream since. Thx.

**Comment by ChrisKian** [comment]
Resubmitted here: https://github.com/brianchandotcom/liferay-portal/pull/41279

**Comment by sergiogonzalez** [comment]
Thanks @ChrisKian

**Pull request closed without merging**
