### PR TITLE
LPS-128125 Run baseline task for frontend-js-loader-modules-extender-api

### PR DESCRIPTION
**Pull request by wincent**
Manual forward from https://github.com/liferay-frontend/liferay-portal/pull/828 seeing as we see multiple PRs with the same obviously unrelated "unique" failure:

- https://github.com/liferay-frontend/liferay-portal/pull/828#issuecomment-784155909
- https://github.com/liferay-frontend/liferay-portal/pull/828#issuecomment-784211180
- https://github.com/liferay-frontend/liferay-portal/pull/830#issuecomment-784196923
- https://github.com/liferay-frontend/liferay-portal/pull/829#issuecomment-784199514

Original description follows.

---

ie. `cd modules/apps/frontend-js/frontend-js-loader-modules-extender-api && gradlew baseline`

### CODE REVIEW

**Comment by wincent** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@pyoo47 fyi, see this comment.

@wincent for baseline, feel free to group the PRs together and send it to me in one pull directly (bypassing CI).

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bdcabb5e4a...99954724cb

**Comment by wincent** [comment]
> @wincent for baseline, feel free to group the PRs together and send it to me in one pull directly (bypassing CI).

Got it, will bear that in mind for future batches (although we're separately looking into why these were out of sync in the first place, so hopefully there won't be any batches...).

**Pull request closed without merging**
