### PR TITLE
LPS 159595

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-159595 

Tested here:https://github.com/Kvale1733/liferay-portal/pull/184
cc: @vicnate

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2c3f4be6fb...592273d0c5

**Comment by brianchandotcom** [comment]
@kyle-miho yikes, no way around a pause? a wait for instead?

**Comment by kyle-miho** [comment]
@brianchandotcom there doesnt seem to be something to wait for that we can depend on, it seems to be something hidden within weblogic itself thats causing the race condition

**Pull request closed without merging**
