### PR TITLE
LPS-76945 Create a ConfigurationListener to track configurations registered with a scoped PID string

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-76945](https://issues.liferay.com/browse/LPS-76945).<br><br>Resent per https://github.com/brianchandotcom/liferay-portal/pull/54222#issuecomment-356490870<br><br>/cc @pei-jung, @jorgeferrer, @stian-sigvartsen

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test

**Comment by drewbrokke** [comment]
@alee8888 is this a one-off failure?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/aa6d801a66...d5ffbc4e8f

**Comment by brianchandotcom** [comment]
@drewbrokke see d5ffbc4e8f5542a1b84627be1ef8f08777d21be6

Can you apply it to your recent pulls that may have an equals method? Thx.

**Comment by drewbrokke** [comment]
@brianchandotcom as far as I remember I don't think my other pulls have overridden an equals method, but I'll double-check.

**Pull request closed without merging**
