### PR TITLE
LPS-134739 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-134739

This is only for master.

@bakayattila
@ruben-pulido

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure case is unrelated to changes in this PR.
See https://github.com/liferay-echo/liferay-portal/pull/5003
❌ ci:test:stable - 8 out of 9 jobs passed
❌ ci:test:relevant - 18 out of 21 jobs passed in 3 hours 46 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1c12ce3032...3c3afcd614

**Comment by brianchandotcom** [comment]
@bakayattila please send a follow up integration test. Thx!

**Pull request closed without merging**
