### PR TITLE
LPS-63317 Disable elements on select view

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
cc:
@jbalsas
@jorgeFerrer, @pei-jung: please check my changes on 689184f, cfc44ed

**Comment by jbalsas** [comment]
LGTM

**Comment by ealonso** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@brianchiu random test failure

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/123afba128...f8b5528d36

**Comment by brianchandotcom** [comment]
@ealonso please see my changes in upstream. Thx.

**Comment by brianchiu** [comment]
@sharonchoi
See PGBlogs#EditBlogsEntryComment

**Pull request closed without merging**
