### PR TITLE
LPS-63730 SF

### PR DESCRIPTION
**Pull request by rotty3000**
nice @csierra!

### CODE REVIEW

**Comment by achaparro** [comment]
thanks @csierra!

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
@rotty3000 @brianchandotcom @stsquared99 @pyoo47

<ul>
<li>Some jobs aborted because the 'Liferay' <a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=5,label_exp=!master/16741/console">tomcat bundle never started</a> which lead to a timeout error.</li>
<li>Some jobs aborted because the <a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/19920/AXIS_VARIABLE=2,label_exp=!master/console">test execution never completed</a> which lead to a timeout error.</li>
</ul>

**Comment by brianchandotcom** [comment]
@rotty3000 please resend? We're checking the other pull https://github.com/brianchandotcom/liferay-portal/pull/36726 too now

**Comment by csierra** [comment]
Is this caused by the new thread? If so I can have a look at it @rotty3000 @brianchandotcom

**Comment by csierra** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/36798

**Pull request closed without merging**
