### PR TITLE
LPS-94618 Remove since there is no real implementation at the moment

### PR DESCRIPTION
**Pull request by jkappler**
Hey @brianchandotcom, had to change interface again...sorry. I'll take care of backporting this

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso, @jorgeferrer, @kyle-miho, @brianchiu

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a20a77e278...4af999db2d

**Comment by brianchandotcom** [comment]
@jkappler see upstream 32c622590518bb775098aca1ed59251c7e93cb28 and 4af999db2d03cf6d0f3f7b7bf6a3dbd86859d40a

I backported it for you.

**Pull request closed without merging**
