### PR TITLE
Lps 58877

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@michaelhashimoto what is this?

**Comment by shuyangzhou** [comment]
And @michaelhashimoto, either the tests are not running at all or the jenkins-report.html no longer gets updated, for example, see https://test-1-9.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/200/jenkins-report.html, it has been like this for quite a while.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@Preston-Crary can you resend on top of https://github.com/Preston-Crary/liferay-portal/pull/50

XyzFinderImpl should return Xyz.

So those joins should be in AssetEntryFinderImpl, and not the other way around. It should be joinDLFE_ByAssetEntry (use DLFE instead of FE since this is in a different package)

Thx

**Pull request closed without merging**
