### PR TITLE
LPS 153326 response

### PR DESCRIPTION
**Pull request by 4lejandrito**
https://github.com/liferay-headless/liferay-portal/pull/730

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cde20f0c45...73e851c526

**Comment by brianchandotcom** [comment]
@4lejandrito please send me a revert for 73e851c5 if my change is bad. Thx.

**Comment by 4lejandrito** [comment]
It's ok to sort it 👍

**Pull request closed without merging**
