### PR TITLE
LPS-106886 Add support to create and update localize content in one r…

### PR DESCRIPTION
**Pull request by javiergamarra**
…equest in Headless Admin Taxonomy API

### CODE REVIEW

**Comment by nhpatt** [comment]
Sent here: https://github.com/nhpatt/liferay-portal/pull/230

**Comment by nhpatt** [comment]
Thx!

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
I typed:

git grep localizedMap

and 

git grep localeMap

Both returned vars that contradict the new naming in LocalizedMapUtil

Please come up with a new name that does not contradict existing names.

Look at portal-kernel/src/com/liferay/portal/kernel/util/LocalizationUtil.java along with other classes for ideas.

**Pull request closed without merging**
