### PR TITLE
LPS-171382 Add Remove Thumbnail for Utility Pages

### PR DESCRIPTION
**Pull request by liulukiwi**
This is only for master.

https://issues.liferay.com/browse/LPS-171382

@lfbesada

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:reopen

**Comment by liulukiwi** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/10696

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4637e6842c...41c3717784

**Comment by brianchandotcom** [comment]
@lfbesada see 41c371778451cdfa2731b296335f1cd6a2673364

**Pull request closed without merging**
