### PR TITLE
LPS-107688 Support exporting inline content introduced within fragment editable elements

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
//cc @ealonso

**Comment by ruben-pulido** [comment]
//cc @pavel-savinov

**Comment by brianchandotcom** [comment]
@ruben-pulido please resend:

```
id = textId;

						setFragmentLink(
							() -> {
								JSONObject configJSONObject =
									textJSONObject.getJSONObject("config");

								if (configJSONObject.isNull("href")) {
									return null;
								}

								return new FragmentLink() {
									{
										value = new InlineLink() {
											{
												href =
													configJSONObject.getString(
														"href");
											}
										};

										setTarget(
											() -> {
												String target =
													configJSONObject.getString(
														"target");

												if (Validator.isNull(target)) {
													return null;
												}

												return Target.create(
													StringUtil.
														upperCaseFirstLetter(
															target.substring(
																1)));
											});
									}
								};
							});

						String type = editableTypes.getOrDefault(
							textId, "text");

						if (Objects.equals(type, "image")) {
							value = new FragmentContentFieldImage() {
								{
									fragmentImage = new FragmentImage() {
										{
											title =
												HashMapBuilder.
													<String, Object>put(
														"value_i18n",
														_toLocaleMap(
															textJSONObject,
															"title")
													).build();

											url =
												HashMapBuilder.
													<String, Object>put(
														"value_i18n",
														_toLocaleMap(
															textJSONObject,
															"url")
													).build();
										}
									};
								}
							};
						}
						else {
							value = new FragmentContentFieldText() {
								{
									text = new InlineValue() {
										{
											value_i18n = _toLocaleMap(
												textJSONObject);
										}
									};
								}
							};
						}
```

we usuall call:

xyz1 = abc1;
xyz2 = abc2;

setHello1(
setHello2(

**Comment by brianchandotcom** [comment]
also, for

value = new FragmentContentFieldImage(

change it to

setValue(

and put the if else logic inside the method.

and make a new method called toFragmentContentField since it's getting too nested

**Comment by ruben-pulido** [comment]
Feedback incorporated in https://github.com/brianchandotcom/liferay-portal/pull/84420

**Pull request closed without merging**
