### PR TITLE
LPS-103074 Adding build.gradle

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @brianchandotcom this goes on top https://github.com/brianchandotcom/liferay-portal/pull/79446.

**Comment by brianchandotcom** [comment]
1.) 

Can you rename and move

modules/apps/depot/depot-web/src/main/java/com/liferay/depot/web/internal/util/DepotAdminGroupSearchProvider.java

to

modules/apps/depot/depot-web/src/main/java/com/liferay/depot/web/internal/users/admin/search/GroupSearchProvider.java

Can you also deprecate modules/apps/site/site-api/src/main/java/com/liferay/site/util/GroupSearchProvider.java

and copy it to

modules/apps/site/site-api/src/main/java/com/liferay/site/users/admin/search/GroupSearchProvider.java (this should be in a different LPS linked to this LPS)

2.) DepotEntryVerticalCard.java

catch (Exception e) {}

debug log please so we don't squash stuff

3.) EditDepotEntryMVCActionCommand.java, do we need to popServiceContext after pushing?

4.) For DepotEntryNameException, are you planning to have more things than MustNotBeNull? If not, then just delete DepotEntryNameException (and rerun gradlew buildService) and use the default generated one. See my commit d763fce2325a62074aa59d6a059d880a9143cee7

Please resend on top of https://github.com/4lejandrito/liferay-portal/pull/333

**Comment by 4lejandrito** [comment]
Hey @brianchandotcom,

When you say `users` in `modules/apps/depot/depot-web/src/main/java/com/liferay/depot/web/internal/users/admin/search/GroupSearchProvider.java` do you mean `sites`? The search provider is not related to users.

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/79506.

**Pull request closed without merging**
