### PR TITLE
LPS-61938 Use correct mvcCommandName

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 what happened here?

**Comment by brianchandotcom** [comment]
@sergiogonzalez @pyoo47 I'm just going to merge this in. Please see what's wrong with the CI for this. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5318b3637e...7ceb0857ff

**Comment by pyoo47** [comment]
@brianchandotcom This is a case where the build-url file was never generated. We are in the process of implementing a more reliable way to return the build-url from a downstream job. The pull request for the change is currently in Hashi's review queue. This looks a little different because in this case, it happened with the source job, which is very early in the build process. When the build fails early in the process like this, the Jenkins report looks almost blank.

**Pull request closed without merging**
