### PR TITLE
Lps 70451

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by arboliveira** [comment]
@shuyangzhou @tomwang2011 @brianchandotcom Can't locally `ant all` anymore. Bisected and narrowed it down to the commits in this pull request. Error as follows.

`taskdef A class needed by class org.apache.axis.tools.ant.axis.AdminClientTask cannot be found: javax/xml/rpc/ServiceException`

```
BUILD FAILED
/Users/arbo/git/liferay-portal/build.xml:4: The following error occurred while executing this line:
/Users/arbo/git/liferay-portal/build-common.xml:80: taskdef A class needed by class org.apache.axis.tools.ant.axis.AdminClientTask cannot be found: javax/xml/rpc/ServiceException
 using the classloader AntClassLoader[/Users/arbo/git/liferay-portal/lib/development/activation.jar:[....]
```

**Comment by tomwang2011** [comment]
@arboliveira can you try to run "git clean -dfx" inside your .gradle directory and see if this still occurs? thanks!

**Comment by arboliveira** [comment]
Does not work for me.

```
cd .gradle
git clean -dfx
cd ..
ant all
```

`/Users/arbo/git/liferay-portal/build-common.xml:80: taskdef A class needed by class org.apache.axis.tools.ant.axis.AdminClientTask cannot be found: javax/xml/rpc/ServiceException`

**Comment by arboliveira** [comment]
However, **this** worked:

```
cd lib
git clean -dfx
cd ..
ant all
```

Got `ant all` running now, thanks!

**Comment by arboliveira** [comment]
https://issues.liferay.com/browse/LPS-72117?focusedCommentId=1020441&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1020441

**Comment by shuyangzhou** [comment]
@arboliveira yeah, the issue is axis-ant.jar and jaxrpc.jar have inter dependencies. And your local repo does not have jaxrpc.jar, but still have axis-ant.jar causing the ant task fails to be defined. The simplest fix could be removing axis-ant.jar and rerun ant setup-libs.
We will add some lib folder integrity verifying logic, and automatically fix it in case of inconsistent state.

**Pull request closed without merging**
