### PR TITLE
master-sc-463

### PR DESCRIPTION
**Pull request by sharonchoi**
https://issues.liferay.com/browse/LRQA-22124
https://issues.liferay.com/browse/LPS-60671

cc @robertoDiaz

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@sharonchoi rebase error, can you resend? Thx.

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
Hey @sharonchoi, 

Rebase errors are in https://github.com/sharonchoi/liferay-portal/commit/3eabb32813bde1d4fd727c0d18c381b57e585e0c, could you handle this?? 

Thanks!!

**Comment by sharonchoi** [comment]
Resent: https://github.com/brianchandotcom/liferay-portal/pull/36304

**Pull request closed without merging**
