### PR TITLE
LPS-60218 S3 Store does not throw NoSuchFileException when updating/moving a file that does not exist

### PR DESCRIPTION
**Pull request by mdelapenya**
cc/ @ehan @preston-crary

### CODE REVIEW

**Comment by Preston-Crary** [comment]
@mdelapenya Shouldn't the fix be to throw the exception? The base test case is saying we should and the test failure is that we are not.

**Comment by mdelapenya** [comment]
Yeah, I tried that approach first, checking this here (https://github.com/mdelapenya/liferay-portal/blob/LPS-60218-fix-s3-store-when-file-does-not-exist/modules/portal-store/portal-store-s3/src/main/java/com/liferay/portal/store/s3/S3Store.java#L605):
```java
List<S3ObjectSummary> oldS3ObjectSummaries = getS3ObjectSummaries(oldPrefix);

if (!oldS3ObjectSummaries.isEmpty()) {
	throw new NoSuchFileException(
		"S3 object not found when moving files from " +
			oldPrefix + " to " + newPrefix);
}
```
But then executed the tests again, and more tests failed, because the move method is invoked from more places, where a NoSuchFileException is captured.

These tests failed:
```java
com.liferay.portal.store.s3.test.S3StoreTest > testUpdateFileWithNewRepositoryId FAILED
    com.liferay.portlet.documentlibrary.NoSuchFileException: S3 object not found when moving files from 21048/21049/KwGNMgek to 21048/21050/KwGNMgek
com.liferay.portal.store.s3.test.S3StoreTest > testUpdateFileWithNewRepositoryIdNoSuchFileException FAILED
    java.lang.AssertionError: Expected exception: com.liferay.portlet.documentlibrary.NoSuchFileException
com.liferay.portal.store.s3.test.S3StoreTest > testUpdateFileVersionWithNewFileName FAILED
    com.liferay.portlet.documentlibrary.NoSuchFileException: S3 object not found when moving files from 21100/21101/HNhpGmCG to 21100/21101/lTrxzGDN
com.liferay.portal.store.s3.test.S3StoreTest > testUpdateFileWithNewFileNameNoSuchFileException FAILED
    java.lang.AssertionError: Expected exception: com.liferay.portlet.documentlibrary.NoSuchFileException
com.liferay.portal.store.s3.test.S3StoreTest > testUpdateFileWithNewFileName FAILED
    com.liferay.portlet.documentlibrary.NoSuchFileException: S3 object not found when moving files from 21108/21109/ARcd7l2D to 21108/21109/nslNAuCK
```
In fact, those tests that actually moved an existing file to a different place (renaming or changing parent and that name does not exist)

That's why I cc'ed you in this pull, to open a debate :)

**Comment by Preston-Crary** [comment]
The simplest fix is just to have the following in those methods:

    if (!hasFile(companyId, repositoryId, fileName)) {
        throw new NoSuchFileException(companyId, repositoryId, fileName);
    }

However, there may be a better way using the moveObjects method.

**Comment by mdelapenya** [comment]
I'm open to changes :) Would you mind taking care of this pull and resend to Brian then?

**Comment by Preston-Crary** [comment]
Sorry, I'm working on some other tasks right now.  However, I think the simple fix should work since that's how it was when I initially fixed this.

@shuyangzhou is there a way we can have automated testing for the CMISStore and S3Store? Both of these require extra configuration and have Assume statements in the setUpClass methods so they do not fail because of configuration. But that means the CI never has them run.

**Comment by mdelapenya** [comment]
Maybe in a separated job, with CMIS/S3 configured by default. The problem with the S3 is that it will be using AWS credentials and potentially hosting files there, that could cost money. I've launched several times the test suite for S3 and it deletes everything, but who knows if changes are coming...

I'd suggest investigating a S3 mock library (https://issues.liferay.com/browse/LPS-55868)

**Comment by shuyangzhou** [comment]
We will just have to mock it, we should not reach to the real store from tests, that will create a network dependency which never ends up stable. The mock one must be all in memory.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b9998f4394...95fd44dc30

**Comment by brianchandotcom** [comment]
@mdelapenya you added two tests with different method names, but the body / content of those tests are identical?

**Comment by Preston-Crary** [comment]
@brianchandotcom can you please revert this? These tests override actual failing tests.

**Comment by mdelapenya** [comment]
@brianchandotcom Did you revert the source formatting? S3 tests will be broken otherwise.

Thanks!

**Pull request closed without merging**
