### PR TITLE
LPS-110425, LPS-111600 | master

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LPS-110425
https://issues.liferay.com/browse/LPS-111600

### CODE REVIEW

**Comment by xbrianlee** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
ci:reopen

**Comment by xbrianlee** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
ci:reopen

**Comment by xbrianlee** [comment]
ci:test:sf

**Comment by xbrianlee** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianwulbern** [comment]
Ignored some more here: https://github.com/brianchandotcom/liferay-portal/pull/89001

**Pull request closed without merging**
