### PR TITLE
LPS-101582 If the bundle has a fragment, recompile jsps

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d46cfaed35...cc0f127b6e

**Comment by brianchandotcom** [comment]
@mtambara I backported this all the way to 7.1.x

**Comment by brianchandotcom** [comment]
@mtambara can you send me a pull for 7.0.x?

**Comment by mtambara** [comment]
Backport sent at https://github.com/brianchandotcom/liferay-portal-ee/pull/26893

**Pull request closed without merging**
