### PR TITLE
LPS-126213 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-126213

This is only for master.

@david-gutierrez-mesa
@alexcandidos

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure cases are unrelated to changes in PR.
See https://github.com/liferay-echo/liferay-portal/pull/3633
❌ ci:test:stable - 7 out of 9 jobs passed
❌ ci:test:relevant - 18 out of 25 jobs passed in 3 hours 8 minutes

**Comment by brianchandotcom** [comment]
@gleicelisbino Please review changes.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8e5650b861...d6cf7ea3c6

**Comment by gleicelisbino** [comment]
Thanks, @brianchandotcom  . I will see the changes now.

**Pull request closed without merging**
