### PR TITLE
master-qa-14420

### PR DESCRIPTION
**Pull request by michaelhashimoto**
http://issues.liferay.com/browse/LRQA-14420

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9a56d28be5...486480f4a0

**Comment by brianchandotcom** [comment]
@lesliewong92 @michaelhashimoto is
```
			sb.append(_getLineItemText("tag-type", attributeName));
			sb.append(_getLineItemText("misc", "="));
			sb.append(_getLineItemText("misc quote", "\""));
			sb.append(_getLineItemText("name", attribute.getValue()));
			sb.append(_getLineItemText("misc quote", "\""));

```

sorted in some logical or alphabetical order?

**Comment by michaelhashimoto** [comment]
@brianchandotcom - this is a logical order, they are representative of HTML elements.

**Comment by brianchandotcom** [comment]
Ok. Thx.

--
Brian Chan
Chief Software Architect
Liferay, Inc.
Enterprise. Open Source. For Life.
(626) 806-1190

On Wed, Apr 15, 2015 at 8:40 PM, Michael Hashimoto <notifications@github.com

**Pull request closed without merging**
