### PR TITLE
LPS-61026 Readd TLD

### PR DESCRIPTION
**Pull request by codyhoag**

### CODE REVIEW

**Comment by codyhoag** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@codyhoag I can't merge this in..

@Brian-Hart your fix in 5ab5b305e6b1a73da2b1caf03fedae17921ae3de is getting overwritten by this pull. Why?

You modified a generated file. So when @codyhoag generated util-taglib/src/META-INF/liferay-aui.tld after modifying util-taglib/src/com/liferay/taglib/liferay-aui.xml, your changes disappeared.

I need you to send in a fix.

@petershin I also need a test like our service builder check to ensure people don't modify generated files.

@Brian-Hart please talk to @codyhoag and resend.
i
Thx!

**Comment by jonmak08** [comment]
Changes from @Brian-Hart are resent at https://github.com/brianchandotcom/liferay-portal/pull/62648.

**Pull request closed without merging**
