### PR TITLE
LPS-58685

### PR DESCRIPTION
**Pull request by matethurzo**
cc: @juliocamarero, @sergiogonzalez, @brandizzi

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/85fa94d90d...8cf5147511

**Pull request closed without merging**
