### PR TITLE
LPS-97429 Use lastSaveDate to allow publishing

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LPS-97429

Passed testing here: https://github.com/brianchiu/liferay-portal/pull/2000

cc @p2kmgcl

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@p2kmgcl @pavel-savinov new language key should be a sentence or a title. See 17d8af0a016426e9fa295740c9ebcc5dec7658ca

@jbalsas @wincent @p2kmgcl Can this be sorted? It looks semi random right now.

```
	{@param? _handleDiscardDraft: any}
	{@param? _handleToggleContextualSidebarButtonClick: any}
	{@param? classPK: ?}
	{@param? defaultSegmentsExperienceId: string }
	{@param? discardDraftRedirectURL: string}
	{@param? discardDraftURL: string}
	{@param? draft: bool}
	{@param? lastSaveDate: string}
	{@param? _online: bool}
	{@param? portletNamespace: string}
	{@param? publishURL: string}
```

See FragmentsEditorToolbar.soy

@wincent Please auto enforce.

**Comment by p2kmgcl** [comment]
@brianchandotcom sure, resending this morning

**Comment by wincent** [comment]
@brianchandotcom: Created https://issues.liferay.com/browse/LPS-98032 to track Soy-related linting. First need to be sure that there's no order-sensitivity with respect to `@param` declarations, as far as I know, [the only constraint is](https://github.com/google/closure-templates/blob/master/documentation/reference/templates.md):

> Parameter declarations must come first in the template, preceding all other template content.

**Comment by p2kmgcl** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
