### PR TITLE
LPS-64536 remove obsolete portlets when syncing layout and layoutPrototype

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by sharonchoi** [comment]
@evannagayama @kenjiheigel poshi test failed at setting up portal instance

**Comment by sharonchoi** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
@brianchandotcom  - I re-ran this pull request here:
https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest(master)/1214/

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7f4cd0576e...988ceec2c9

**Comment by brianchandotcom** [comment]
@arbetts I renamed it from "obsolete" to "unreferenced".

**Pull request closed without merging**
