### PR TITLE
LPS-66359 Fix jspc

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @adolfopa

**Comment by anthony-chu** [comment]
The failure of `PGWiki#AddWikiFrontPageChildPageFormatHTML` is due to a change in the markup for the configuration panel and will require a test fix: [LRQA-26601](https://issues.liferay.com/browse/LRQA-26601).

**Comment by sharonchoi** [comment]
@brianchandotcom @sergiogonzalez @adolfopa I fetched this branch and resent the pull with your commits here: https://github.com/brianchandotcom/liferay-portal/pull/41547

Could someone please close this pull out? Thanks! :)

**Comment by brianchandotcom** [comment]
@adolfopa this fix seems wrong?

id='<%= renderResponse.getNamespace() + "customFields" %>'

We are essentially double namespacing them because they are already namespaced?

In portal-web/docroot/html/taglib/init.jsp

```
String namespace = AUIUtil.getNamespace(portletRequest, portletResponse);

if (Validator.isNull(namespace)) {
	namespace = AUIUtil.getNamespace(request);
}
```

That is picked up in start.jsp

```
<fieldset class="fieldset <%= cssClass %>" <%= Validator.isNotNull(id) ? "id=\"" + namespace + id + "\"" : StringPool.BLANK %> <%= InlineUtil.buildDynamicAttributes(dynamicAttributes) %>>
```

So it should already be namespaced?

Something seems wrong here. Please resend. I know we've used this pattern for a few fixes already but I think those may be wrong too

**Pull request closed without merging**
