### PR TITLE
LPS-158711 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-158711

This is only for master.

@BarbaraCabrera
cc @lfbesada

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure cases are unrelated to changes.
See https://github.com/liferay-echo/liferay-portal/pull/9405
✔️ ci:test:stable - 27 out of 27 jobs passed
❌ ci:test:relevant - 966 out of 1054 jobs passed in 6 hours 8 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d76509d47b...30f3954510

**Comment by brianchandotcom** [comment]
@BarbaraCabrera see 30f3954510a8057e996e088bd904680bdd9963c6

**Comment by BarbaraCabrera** [comment]
Thank you! 😄

**Pull request closed without merging**
