### PR TITLE
LPS-102645 React treeview

### PR DESCRIPTION
**Pull request by wincent**
Rebased resend of https://github.com/brianchandotcom/liferay-portal/pull/81432 because stable failures look unrelated.

### CODE REVIEW

**Comment by wincent** [comment]
@zhangyan0701: If you're able, would you be able to check the stable failures on that other PR (#81432) to see if my assessment is correct?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/215006da18...102353a2dc

**Comment by zhangyan0701** [comment]
@wincent Yes, I will take a look at the stable failures today.

**Comment by zhangyan0701** [comment]
The stable failures on [#84230](https://github.com/brianchandotcom/liferay-portal/pull/81432) were unrelated. And the stable test passed in this pr.

**Pull request closed without merging**
