### PR TITLE
LPS-56692

### PR DESCRIPTION
**Pull request by david-truong**

### CODE REVIEW

**Comment by david-truong** [comment]
@brianchandotcom can we use the final version of sass-compiler-api 2.0 instead of snapshot?

**Comment by david-truong** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by david-truong** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@david-truong where did the tests for the source maps come from? They look very similar to the ones that were downloaded (and autogenerated from our perspective)

Were they hand written or copied? if copied, it'd be best to script how they were copied. Meanwhile, I'll publish a 2.0.0 for the sass-compiler-api. Please resend. Thx.

**Comment by david-truong** [comment]
Handwritten because I couldn't find any tests out there so I just wrote
them to match the existing styles

On Thu, Sep 10, 2015 at 10:42 PM, Brian Chan <notifications@github.com>
wrote:

> Closed #29949
> <https://github.com/brianchandotcom/liferay-portal/pull/29949>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/29949#event-406701832>
> .
>



-- 
David Truong
Product Manager
david.truong@liferay.com
Liferay, Inc

**Pull request closed without merging**
