### PR TITLE
LPS-52815 support for merging tags from different pages

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:restest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@ealonso @jkappler @juliocamarero 

I fixed a potential NPE. Please double check in 99eadbce160b3e3888a14bc88d31b5b5f5ed0675

Thx

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3970da34b1...99eadbce16

**Pull request closed without merging**
