### PR TITLE
LPS-171011 Fix warnings when creating a company and accesing to CompanyThreadLocal from other threads

### PR DESCRIPTION
**Pull request by lucasperj**
Issue link: [LPS-171011](https://issues.liferay.com/browse/LPS-171011)
Original PR: https://github.com/liferay-uniform/liferay-portal/pull/845

### CODE REVIEW

**Comment by lucasperj** [comment]
ci:reopen

**Comment by lucasperj** [comment]
Forwarding manually cause the failures on the original PR are not related. 

CC/ @achaparro @shuyangzhou @vicnate5

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ffedbed5b7...db842988c2

**Comment by brianchandotcom** [comment]
@lucasperj @achaparro please add a test for this (even if it only breaks once in a while). Ideally, we can simulate the race condition, but if not, breaking once in a while is better than not having tests.

**Pull request closed without merging**
