### PR TITLE
LPS-68845

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-68845.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
This is still running. Only 4 batches remain.
http://test-1-4/job/test-portal-acceptance-pullrequest-batch%28master%29/52223/
http://test-1-4/job/test-portal-acceptance-pullrequest-batch%28master%29/52226/
http://test-1-4/job/test-portal-acceptance-pullrequest-batch%28master%29/52225/
http://test-1-4/job/test-portal-acceptance-pullrequest-batch%28master%29/52224/

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
