### PR TITLE
LPS-110306 | master

### PR DESCRIPTION
**Pull request by jpince**
https://issues.liferay.com/browse/LPS-110306

Releasing OAuth2 as a core/required app per discussion today. @csierra @xbrianlee @zsigmondrab

7.2.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/29581
7.1.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/29543

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e8c1a016a6...c1a82c5409

**Comment by jpince** [comment]
@patriciajeanperez @cvanut I doubt this error in PortalSmoke is related to the pull. Race condition? Related to an existing bug?

```
     [exec] 17:31:12,354 ERROR [main][UserPersonalSitePermissions:78] Unable to initialize user personal site permissions for portlet com_liferay_polls_web_portlet_PollsPortlet in company 20097
     [exec] com.liferay.portal.kernel.exception.NoSuchResourceActionException: com.liferay.polls#PERMISSIONS
     [exec] 	at com.liferay.portal.service.impl.ResourceActionLocalServiceImpl.getResourceAction(ResourceActionLocalServiceImpl.java:322)
```

@xbrianlee OAuth2 test failure - flaky spa issue? network? No response needed, just data for you.

**Comment by xbrianlee** [comment]
[LRCI-1048](https://issues.liferay.com/browse/LRCI-1048) is still happening unfortunately

**Comment by patriciajeanperez** [comment]
A race condition, @jpince. Team will look into it. Thanks!

**Pull request closed without merging**
