### PR TITLE
LPS-69271

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@michaelhashimoto can you check if this works okay for linux? Pretty sure it's not a platform thing, but it doesn't hurt to double check :)

**Comment by jpince** [comment]
@kenjiheigel

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by michaelhashimoto** [comment]
@hhuijser - I tested it in Linux and it worked as expected.  Thanks for all your help Hugo! :D

**Pull request closed without merging**
