### PR TITLE
LPS-59436 SF

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by jbalsas** [comment]
Hey @brianchandotcom, I reran the tests on my user first (https://github.com/jbalsas/liferay-portal/pull/268) and only the integration tests remained.

Hopefully that'll be the result of this pass as well :)

**Comment by jbalsas** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@carloslancha poshi error @evannagayama not sure who shoudl review this on the QA side to fix the Poshi. Thx.

**Comment by evannagayama** [comment]
@carloslancha @jbalsas 
Please push this again. I believe it's failing because of a fluke in our functional tests and this pr https://github.com/brianchandotcom/liferay-portal/pull/32515 should fix that issue.

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
