### PR TITLE
LPS-59508 add individual scope resource if it does not exist to ensure the same behaviour of permission checker in all the cases

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Very good job on this Pavel!

/cc @juliocamarero

**Comment by juliocamarero** [comment]
:clap: :clap: :clap:

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/50b0891bb1...23cc7587e1

**Comment by brianchandotcom** [comment]
@pavel-savinov can we add an integration test for this? Thanks!

**Pull request closed without merging**
