### PR TITLE
[7.4-only] LPS-121976 Delete temporary clay:*-card-v2 tags

### PR DESCRIPTION
**Pull request by markocikos**
Fixes: https://issues.liferay.com/browse/LPS-121976

This is the last task in the [cards update epic](https://issues.liferay.com/browse/LPS-121933). :tada: 

We are deleting temporary v2 tags and old unused tag classes.

@julien @carloslancha

### CODE REVIEW

**Comment by markocikos** [comment]
ci:reopen

**Comment by markocikos** [comment]
Original PR: https://github.com/liferay-frontend/liferay-portal/pull/605

Manually forwarded because 
1. First CI failure in https://github.com/liferay-frontend/liferay-portal/pull/605#issuecomment-742480787 is caused by incorrect kernel version in master
2. Second CI failure in https://github.com/liferay-frontend/liferay-portal/pull/605#issuecomment-742546769 is unrelated

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d746e4d70c...5365b46d1c

**Comment by brianchandotcom** [comment]
Woohoo @markocikos @jbalsas thx

**Pull request closed without merging**
