### PR TITLE
LPS-59671 Apply Lexicon pattern to User Groups portlet

### PR DESCRIPTION
**Pull request by alee8888**

### CODE REVIEW

**Comment by alee8888** [comment]
@brianchandotcom @pei-jung @natecavanaugh

This is a resend of the following PR that combines functional test fixes for LPS-59671:
https://github.com/brianchandotcom/liferay-portal/pull/34277

**Comment by alee8888** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pyoo47 this one hung too

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1d414cec2d...f522506e1d

**Pull request closed without merging**
