### PR TITLE
LPS-60541 SF

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @sergiogonzalez

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
Hey @brianchandotcom, @sergiogonzalez, we keep getting test errors but I don't think they're related. Looks like the CI is somehow unstable today :(

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8e6b39d86d...f65ad925df

**Pull request closed without merging**
