### PR TITLE
LPS-153766 Add commons-compress due to JenkinsResultsParserUtil ant usage

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1216f1483f...7ff481d405

**Comment by brianchandotcom** [comment]
@vicnate5 you checked with @shuyangzhou right? I think he just removed commons-compress right?

**Comment by shuyangzhou** [comment]
yeah, Victor did. This is only adding it back to lib/development, not lib/portal. It is fine.

**Pull request closed without merging**
