### PR TITLE
Lps 181133

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fb8f5f7871...5a6c6302bf

**Comment by brianchandotcom** [comment]
@ling-alan-huang can you SF enforce this fix by @shuyangzhou ? (if possible)

**Comment by shuyangzhou** [comment]
@ling-alan-huang before this change we are blindly publishing every osgi configuration as osgi service, no matter anyone asking for it or not. Some of them are used, like https://github.com/brianchandotcom/liferay-portal/pull/133035/commits/7b597e3e5bb6fec69205f5762ecc1cf666fc5e28#diff-3f43617c3d499f12fe7dd3050bc8df1fa5bfaffae4b5d4f269316e10c8ec2f4aR2347 , others are simply left as orphans.

This pull removed the unconditional publication, each component whom needs the configuration needs to get it in the standard way, like https://github.com/brianchandotcom/liferay-portal/pull/133035/commits/7b597e3e5bb6fec69205f5762ecc1cf666fc5e28#diff-3f43617c3d499f12fe7dd3050bc8df1fa5bfaffae4b5d4f269316e10c8ec2f4aR1211

The SF rule should catch any attempting of referencing osgi configuration as service. But even without the SF rule, this change is strong enough to protect itself, since whoever tries to do this will end up having an unresolved component which would be caught by CI anyway.

**Pull request closed without merging**
