### PR TITLE
LPS-77324 Prefer const instead of let

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@ealonso can you fix your AssetLink error? thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2a4a7a66fb...e262a97c0f

**Comment by brianchandotcom** [comment]
@p2kmgcl @pavel-savinov the if else statements in the .es.js do not conform to our JS standards. Please send a follow up pull and fix them.

@jbalsas we need to start implementing the CSF soon.

**Comment by jbalsas** [comment]
@brianchandotcom, we will implement csf here right after this PR. @p2kgmcl is already on it!

**Comment by p2kmgcl** [comment]
@brianchandotcom @jbalsas yes, the next PR will be done with the new csf, and then I will check everything else :)

**Pull request closed without merging**
