### PR TITLE
LPS-71382 Allow administrators to configure OpenOffice using System Settings, allowing export and import of configurations

### PR DESCRIPTION
**Pull request by alee8888**
@brianchandotcom @pei-jung 
This is a resend of https://github.com/brianchandotcom/liferay-portal/pull/48483 that had rebase errors.

### CODE REVIEW

**Comment by alee8888** [comment]
ci:reopen

**Comment by alee8888** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@alee8888  can you rebase and resend? Thx.

**Comment by pei-jung** [comment]
rebased and resent here https://github.com/brianchandotcom/liferay-portal/pull/48636.

**Pull request closed without merging**
