### PR TITLE
LPS-44217 Auto SF

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by jpince** [comment]
@austinchiang @liuxingye a lot of functional test failures, not sure if they're related.

**Comment by brianchandotcom** [comment]
@adolfopa @austinchiang can you guys resend? Functional test failures.. not sure if it's safe. Thx.

**Comment by austinchiang** [comment]
The functional failures here are similar to those in https://github.com/brianchandotcom/liferay-portal/pull/80271, which was merged. So I think they are unrelated. I'm double checking [here](https://github.com/austinchiang/liferay-portal/pull/549)

**Pull request closed without merging**
