### PR TITLE
LPS-98186 Update packageinfo

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9682483815...9ee6bfaf3d

**Comment by brianchandotcom** [comment]
@leoadb @jeyvison see my changes in upstream.. if you had made these changes (all the same patterns as *ResourceImpl), I would have been able to merge it faster.

@brunofarache fyi.

**Comment by brianchandotcom** [comment]
@leoadb @jeyvison I backported this to 7.2.x.

**Pull request closed without merging**
