### PR TITLE
LPS-205216 Missing argument for formatting expression

### PR DESCRIPTION
**Pull request by LuisOrtiz89**

### CODE REVIEW

**Comment by LuisOrtiz89** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@LuisOrtiz89 can you send a follow up PR and for

```
		return String.format(
			"DISPATCH_GROUP_%07d@%d", dispatchTrigger.getDispatchTriggerId(),
			dispatchTrigger.getCompanyId());
	}

	private String _getJobName(DispatchTrigger dispatchTrigger) {
		return String.format(
			"DISPATCH_JOB_%07d@%d", dispatchTrigger.getDispatchTriggerId(),
			dispatchTrigger.getCompanyId());
```

Use StringBundler.concat instead

Thx

**Comment by kevhlee** [comment]
Hey @brianchandotcom, can you clarify what you mean by apply `StringBundler.concat()`? I do not see how that method can be applied in the case you're referring to.

**Comment by brianchandotcom** [comment]
@LuisOrtiz89 @kevhlee I prefer

StringBundler.concat("hello", var1, "blah", var2) 

vs.

String.format("hello%1blah%2, var1, var2) 

It's way harder to read.

**Comment by kevhlee** [comment]
@brianchandotcom Okay, I think I understand what you're saying. I will send a follow-up PR.

**Pull request merged**
