### PR TITLE
LPS-183651 Rename copy methods of ServiceImpl classes to follow source/target pattern

### PR DESCRIPTION
**Pull request by alessandromalves**
PR with SF requested from Brian in this PR: https://github.com/brianchandotcom/liferay-portal/pull/132924#issuecomment-1498812258

Task: https://issues.liferay.com/browse/LPS-181166
Subtask: https://issues.liferay.com/browse/LPS-183651

cc.: @Mikellorza

### CODE REVIEW

**Comment by alessandromalves** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/11959

:heavy_check_mark: ci:test:stable - 29 out of 29 jobs passed
:x: ci:test:relevant - 466 out of 513 jobs passed in 3 hours 22 minutes

**Comment by alessandromalves** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/36977d0224...93b209da10

**Comment by brianchandotcom** [comment]
@Mikellorza impressive!

**Pull request closed without merging**
