### PR TITLE
LPS-76626

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:test

**Comment by Ithildir** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@Ithildir can you resend change logs? Thx.

**Comment by brianchandotcom** [comment]
@petershin can you update all the individual gradle.properties that were hacked to use an older version of SBuilder to use the latest version? Thx!

**Comment by petershin** [comment]
Sent pulls to update the gradle.properties files:

https://github.com/brianchandotcom/liferay-portal-ee/pull/19144
https://github.com/brianchandotcom/com-liferay-osb-lcs-private/pull/102
https://github.com/liferay/com-liferay-osb-faro-private/pull/265

@brianchandotcom

**Comment by petershin** [comment]
Talked to Shuyang about fixing this a better way

**Pull request closed without merging**
