### PR TITLE
Lps 92429

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@shuyangzhou I think that broken jsp error came from you and @preston-crary changing the taglibs.. I'm going to try and fix it right now.

**Comment by shuyangzhou** [comment]
Reverted at https://github.com/brianchandotcom/liferay-portal/pull/70248

**Pull request closed without merging**
