### PR TITLE
LPS-80332 Update collaboration & forms-and-workflow

### PR DESCRIPTION
**Pull request by petershin**
Please let the tests finish

@mtambara

### CODE REVIEW

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
ci:reopen

**Comment by petershin** [comment]
ci:reopen

**Comment by petershin** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1f3c5b152b...50f0f8c549

**Comment by petershin** [comment]
@brianchandotcom - I'm able to run `ant all` locally.  t looks like it was fixed by this [commit](https://github.com/liferay/liferay-portal/commit/226094bce8).

**Pull request closed without merging**
