### PR TITLE
LPS-196493 (Un)Publishing on every node in the cluster

### PR DESCRIPTION
**Pull request by 4lejandrito**
https://liferay.atlassian.net/browse/LPS-196493.

This PR makes the publication of apps work across nodes of a cluster.

How to test? I don't know yet.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
@brianchandotcom we tested this locally with QA @magjed4289 and she is now working on an automated test. It works!

**Comment by brianchandotcom** [comment]
@4lejandrito I just looked a this more deeply, I think the code should be in 

APIApplicationPublisher itself (even though the current one works with Util)

I'm sending this to @shuyangzhou

**Comment by 4lejandrito** [comment]
Agree. See https://github.com/shuyangzhou/liferay-portal/pull/11228.

**Pull request closed without merging**
