### PR TITLE
LPS-174464 Implement improvements on performance of resolve modules servlet URL generation

### PR DESCRIPTION
**Pull request by izaera**
This is an alternative to https://github.com/liferay-frontend/liferay-portal/pull/3023, similar to the first PR we sent and was rolled back.

However, this time, the SHA-1 computation only takes 50-90 ms for a vanilla DXP installation. This huge enhancement is due to having hashed a lot of duplicate data in the first PR because of the use recursivity in the code computing the hash.

----

Manual forward of https://github.com/liferay-frontend/liferay-portal/pull/3030 as per https://github.com/liferay-frontend/liferay-portal/pull/3030#issuecomment-1419784743

### CODE REVIEW

**Comment by izaera** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a02be620f3...e7f5b59573

**Comment by brianchandotcom** [comment]
@izaera is this sortable?

```
public, max-age=31536000, immutable
```

If so, please send a follow up PR to sort it (if not , no worries)

See e7f5b595

@shuyangzhou fyi on this.

**Comment by shuyangzhou** [comment]
@111anna please run a regression check for this pull, thanks!

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129875 . All overhead during startup has been removed, the initialization only happen on the during first hit and NPMRegistry updating.

**Comment by 111Anna** [comment]
Hi @shuyangzhou, Here are the startup test results, there no regression appeared.


CE
Portal Version|GitId|Average Startup (ms)|%|Average Shutdown (ms)|%|Open File|Thread Create|Open Prepared Statement|Open SQL
--|--| --|--|--|--|--|--|--|--|
Baseline| 631b009| 22740.3 |- |3274.3|-| 1833 | 101 | 504| 1008 |
Baseline + PR-129834| - |  23022.3 |-1.2%| 3264.6|0.3%| 1833 | 101 | 498 | 1007 |


DXP
Portal Version|GitId|Average Startup (ms)|%|Average Shutdown (ms)|%|Open File|Thread Create|Open Prepared Statement|Open SQL
--|--| --|--|--|--|--|--|--|--|
Baseline| 631b009| 25050 |- |3865|-| 1989 | 115| 556| 1097 |
Baseline + PR-129834| - |  24986 | 0.3%| 3925.3|-1.5%| 1989 | 114 | 560 | 1095 |

**Comment by shuyangzhou** [comment]
@111Anna please check the new follow up pull too, thanks!

**Comment by 111Anna** [comment]
> @111Anna please check the new follow up pull too, thanks!

OK, I'm running it.

**Pull request closed without merging**
