### PR TITLE
LPS-66292

### PR DESCRIPTION
**Pull request by danielkocsis**

### CODE REVIEW

**Comment by danielkocsis** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f6388612d9...9caf271320

**Comment by brianchandotcom** [comment]
@danielkocsis see 92e33c6f5e8722dd83a57e75cb2e0856c855419a

Thx.

**Comment by brianchandotcom** [comment]
@danielkocsis see 92e33c6f5e8722dd83a57e75cb2e0856c855419a (with proper link now)

**Comment by brianchandotcom** [comment]
@danielkocsis See 9caf2713209637413c45c35a130477c6cec57108 (I had the wrong ref)

**Pull request closed without merging**
