### PR TITLE
master-qa-22571-1

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-22387
https://issues.liferay.com/browse/LRQA-22571

### CODE REVIEW

**Comment by kenjiheigel** [comment]
These test failures are unrelated. 

The following tests are failing due to a bug that was introduced: [LPS-63710](https://issues.liferay.com/browse/LPS-63710)
PGWiki#DeleteWikiFrontPage
PGMediagallery#DeleteFolderDocument
PGMediagallery#EditFolderDocument
WorkflowadminCPWebcontent#AddWebContentCP
WorkflowadminCPWebcontent#ApproveInWebContentFolderWithParentFolderSingleApproverWorkflowCP
WorkflowadminMysubmissions#WithdrawTaskAssignedToMeByActions

These have been removed from upstream temporarily and will be added again once [LPS-63710](https://issues.liferay.com/browse/LPS-63710) has been fixed:
https://github.com/liferay/liferay-portal/commit/3e1f823eacc4855d051613f07e91569f76cfb691

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
Retesting after rebase to make sure that no failures occur after BChiu's removal of the failing tests: https://github.com/liferay/liferay-portal/commit/3e1f823eacc4855d051613f07e91569f76cfb691

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3e1f823eac...12c5de8eef

**Pull request closed without merging**
