### PR TITLE
LPS-164881 - Object form validation does not show custom error validation message

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-164881

@ruben-pulido

### CODE REVIEW

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/10184

:x: ci:test:stable - 26 out of 27 jobs passed
:x: ci:test:relevant - 102 out of 113 jobs passed in 1 hour 38 minutes

**Comment by ozysouza** [comment]
ci:reopen

**Comment by ozysouza** [comment]
ci:reopen

**Comment by ealonso** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
ci:close

**Pull request closed without merging**
