### PR TITLE
LPS-92465

### PR DESCRIPTION
**Pull request by topolik**
Hi Brian,

https://issues.liferay.com/browse/LPS-92465
https://issues.liferay.com/browse/OAUTH2-255

Thank you.

/cc @csierra

### CODE REVIEW

**Comment by topolik** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@xbrianlee @joshchong see POSHI failure

int test failures - not sure about CORS test, the others look unrelated

**Comment by xbrianlee** [comment]
@topolik The POSHI failures exist upstream. We're working on resolving them.
CORS tests are the only ones we're worried about.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d4a723b59d...233d87833d

**Pull request closed without merging**
