### PR TITLE
LPS-72464 Use ServiceProxyFactory in UserBagFactoryUtil.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/89b65d6285...08efb9680d

**Comment by brianchandotcom** [comment]
@shuyangzhou see random test failure?

**Comment by brianchandotcom** [comment]
@jpince is ExportImport#ExportImportSampleLARPortlet  this random or real?

**Comment by shuyangzhou** [comment]
@brianchandotcom this looks like a race condition, import xstream deserialization racing with the deserializer's registeration. Basically we try to use a deserializer that has not been registered yet(or for whatever reason, it got un-registered)

@mtambara please take a look when you are back tomorrow.

**Comment by vicnate5** [comment]
@shuyangzhou @mtambara According to the test history, this is randomly failing on PRs today, but has a clean history before today.

CC @jpince

**Comment by jpince** [comment]
FYI @kmaria @matethurzo Shuyang's team will look into this today, but so you are aware.

@kmaria if this test is still flaky at head, can you send me a pull to quarantine? I'll push it up when I get in.

**Pull request closed without merging**
