### PR TITLE
LPD-37767 | Fix SQLDSLTest failure "DSLFunctionFactoryUtil is not fully covered

### PR DESCRIPTION
**Pull request by 4lejandrito**
**What's changed?**

When fixing [LPD-37767](https://liferay.atlassian.net/browse/LPD-37767), unit tets was not created for `DSLFunctionFactoryUtil.truncateToSeconds`. Causing the following failure at SQLDSLTest:

> classMethod: java.lang.AssertionError: com.liferay.petra.sql.dsl.DSLFunctionFactoryUtil is not fully covered

The test has been adapted for the new method.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by tinatian** [comment]
@dannielraposo Could you please close your pull before we come to a conclusion how this is going to proceed?

**Comment by tinatian** [comment]
@brianchandotcom This pull has not been reviewed by core infra but all the changes are modifying core infra classes.

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/155050.

**Pull request closed without merging**
