### PR TITLE
LPS-76955

### PR DESCRIPTION
**Pull request by SpencerWoo**
https://issues.liferay.com/browse/LPS-76955

Carlos has reviewed these changes

### CODE REVIEW

**Comment by SpencerWoo** [comment]
ci:test

**Comment by jpince** [comment]
ci:close

**Comment by jpince** [comment]
@SpencerWoo @csierra SF error. @petershin I would have expected their implementation to be correct, the SF suggestion is quite long (way more than 80 chars/line, or whatever the standard is). Can you please look into this?

**Comment by petershin** [comment]
@jpince - The 80 character limit per line rule isn't applicable for jsps.

As an example see [portal-web/docroot/html/taglib/ui/input_localized/page.jsp#L105](https://github.com/liferay/liferay-portal/blob/master/portal-web/docroot/html/taglib/ui/input_localized/page.jsp#L105)

**Comment by SpencerWoo** [comment]
Added SF change and resent https://github.com/brianchandotcom/liferay-portal/pull/55861

**Pull request closed without merging**
