### PR TITLE
LPS-90491 SF

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test:change-tracking

**Comment by matethurzo** [comment]
ci:test:change-tracking

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ca18bc6187...25fb468b75

**Comment by brianchandotcom** [comment]
@matethurzo merged, see 25fb468. compile error not related.

**Pull request closed without merging**
