### PR TITLE
LPS-107114 Add entity id as filterable property in APIs

### PR DESCRIPTION
**Pull request by javiergamarra**
Use factory in headless-common. Creates a mapping between id (public name) and entryClassPK, that's why the method is called createEntityFieldsMapWithEntityId.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/eb0f786f5f...3fd0dfc70c

**Comment by brianchandotcom** [comment]
@javierdearcos my bad, see 3fd0dfc70cba50296b01310790ca00837f5d90b8

@nhpatt I just went for the create method since all this logic is for headless-**

So we don't need to mention "id"

**Comment by brianchandotcom** [comment]
@javierdearcos can you help me backport this to 7.1.x? I did it for 7.2.x

**Comment by javierdearcos** [comment]
Sure. Just made the PR with the backport to 7.1.x

**Pull request closed without merging**
