### PR TITLE
LPS-84119

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@brianchandotcom, tested in my own queue. There is a semver issue that shows up, but not related

**Comment by hhuijser** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e1506e510a...571c89db55

**Comment by hhuijser** [comment]
@pyoo47 @michaelhashimoto

Anything we can do about these `LocalFile` failures showing up in every single pull?
Looks like we simply ignore these anyway, and whenever there are more than 5 failures, it's easy to miss out on 'real' failures, since you have to dig into the logs to find em...

**Comment by pyoo47** [comment]
@hhuijser I think those failures have been fixed. This pull from 2 hours ago doesn't have them: https://github.com/brianchandotcom/liferay-portal/pull/75661.

**Comment by hhuijser** [comment]
@pyoo47 probably not.
Those failures been showing up inconsistently (around 80% of the time or so) in my pulls for a long time now...
Will tag you when I see a new one

**Comment by pyoo47** [comment]
@hhuijser If you see it again, you should reach out to Timothy Pak. He's taking over Jason Pince's role in working to resolve test failures in CI. My team and I work on the CI infrastructure itself. I would rather have Timothy validate that it isn't a problem with the test before attempting to make changes to the infrastructure to fix it.

**Comment by hhuijser** [comment]
Sounds good, will do

**Pull request closed without merging**
