### PR TITLE
Lps 151272 4 12 1

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by vicnate5** [comment]
@brianchandotcom Release blocker fix.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/21ce86a623...501c4bd889

**Comment by brianchandotcom** [comment]
Thx for fixing this @tinatian @shuyangzhou !

**Pull request closed without merging**
