### PR TITLE
LPS-75849 Temporary ignore inherited test in failing tests

### PR DESCRIPTION
**Pull request by jpince**
/cc @drewbrokke

### CODE REVIEW

**Comment by jpince** [comment]
'/cc <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jpince** [comment]
@pei-jung thanks!

**Comment by pei-jung** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:reopen

-- 
Jason Pince
Lead Test Engineer


Liferay Inc. | 1400 Montefino Avenue, Diamond Bar, CA 91765 USA |
877-543-3729 <(877)%20543-3729>
_____________________________________________________________________

*Confidentiality Notice:* This e-mail message, including any attachments,
is for the sole use of the intended recipient(s) and may contain
confidential and privileged information. Any unauthorized review, use,
copying, disclosure or distribution is prohibited. If you are not the
intended recipient, please contact the sender by reply e-mail and destroy
all copies of the original message.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b6f3d2d5b6...017d121380

**Pull request closed without merging**
