### PR TITLE
LPD-19212: Add OpenSearch connector app metadata

### PR DESCRIPTION
**Pull request by peerkar**
https://liferay.atlassian.net/browse/LPD-19212

### CODE REVIEW

**Comment by peerkar** [comment]
ci:reopen

**Comment by peerkar** [comment]
Resending

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ddc15ef1f2...917999795f

**Comment by brianchandotcom** [comment]
@peerkar see 917999795f85373a338f8edfacb1e352ce400d07

Can you verify my changes.

**Comment by peerkar** [comment]
@brianchandotcom the connector has been developed against version 2.8.0, so I'd say 2.8.0+.

@lipusz can you also please comment on the wording?

**Comment by lipusz** [comment]
It's fine. We can update the wording when we'll actually be about to release this. :+1:

**Pull request closed without merging**
