### PR TITLE
LPS-76586 Close success message if present

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-36939

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test

**Comment by koor4356** [comment]
Anthony is out on PTO and Jason has approved to send this pr.

**Comment by koor4356** [comment]
ci:retest

**Comment by koor4356** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
