### PR TITLE
LPS-68877 Source Formatting

### PR DESCRIPTION
**Pull request by marcellustavares**
thx @gregory-bretall @jonathanmccann

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by ChrisKian** [comment]
ci:reopen

**Comment by ChrisKian** [comment]
ci:retest

**Comment by vicnate5** [comment]
@marcellustavares Looks like the due date didn't get updated correctly in Workflow Tasks

**Comment by vicnate5** [comment]
ci:close

**Comment by vicnate5** [comment]
@gregory-bretall @jonathanmccann We have an end to end test that is failing on this pull.
The test fails to successfully update the due date for a workflow tasks.

Steps used by the test to reproduce:
1. Go to Liferay Site > Configuration > Workflow Configuration
2. Enable Single Approver workflow for Blogs
3. Add new blogs entry
4. Submit for Publication
5. Go to My Workflow Tasks
6. Click on Blogs task kebab menu
7. Click "Update Due Date"
8. Change date and time to a future date
9. Click "Done"
10. Assert due date in the workflow tasks table

Would it be possible for one of you to take another look at this?

**Comment by gregory-bretall** [comment]
I'm looking into it right now, I'll get back as soon as possible with my findings.

**Comment by vicnate5** [comment]
Thanks @gregory-bretall!

**Comment by gregory-bretall** [comment]
I've been working on this issue for the past few hours and have figured out what is causing it.  The original behavior of MyWorkflowTasks involved appending the content, moving it from its original location into the pop-up window.  However, I removed this behavior by simply copying the content instead of moving it to allow for the pop-up windows to be destroyed without destroying the content.  This has had the unintended side effect of causing the Due Date window's changes to not be saved (the assign pop-ups don't care as they are not storing information on the page that is user-inputted).  

To address this issue I have been working on an approach that will allow me to copy back the changes made by the user to the static data on the page, allowing for both the destruction of the modal pop-up and keeping the changes.  

I should be able to finish this fix on Monday as I'm taking PTO tomorrow, but I would greatly appreciate any feedback on whether or not this sounds like the correct approach and any ways in which you think this could be properly achieved.  

Thanks.

**Comment by marcellustavares** [comment]
thx for the update @gregory-bretall!

**Comment by gregory-bretall** [comment]
I just finished fixing the above mentioned issue and made a new commit addressing it.  Who should I resend the pull request to?

**Comment by jonathanmccann** [comment]
@gregory-bretall Send it back through the normal workflow.

**Pull request closed without merging**
