### PR TITLE
LPS-90415,LPS-90144 Fix SF failures

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
CC @jpince @vicnate5

**Comment by brianchandotcom** [comment]
@stsquared99 can you fix the reference we still have to "automatically-anonymize-data-that-does-not-require-review" ? See fix by @Preston-Crary

**Comment by brianchandotcom** [comment]
@stsquared99 nvm, I fixed it in 5771199

**Comment by stsquared99** [comment]
@brianchandotcom Oy, thank you Brian

**Pull request closed without merging**
