### PR TITLE
LPS-65786 SF

### PR DESCRIPTION
**Pull request by rotty3000**
Let's see what happens with this.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@peterfellwock merged.

@ithildir Can you review modules/apps/wsrp/wsrp-service/build.gradle

Do we have to do this for every module with WSDD? Seems repetitive? Can you talk to @peterfellwock and find out why we need to do this. Thx.

**Comment by brianchandotcom** [comment]
@peterfellwock does this mean we can remove the "Ignore" from the WSRP persistence tests, and remove the build-services hack?

**Comment by peterfellwock** [comment]
@brianchandotcom In regards to build.gradle @ithildir helped me add this logic a while ago, this will not only build the fragmented wsrp-wsdd jar it will also deploy it. WSRP does not work without the fragmented wsrp jar.

@brianchandotcom In regards to the WSRP tests, I will grab and send myself a pull to make sure it passes. Just like I sent @shuyangzhou https://github.com/shuyangzhou/liferay-portal/pull/3390  Once this passes I will send you a pull for it.

@brianchandotcom and lastly I will send you a pull containing the cleanup of wsdl files, just like sent @shuyangzhou https://github.com/shuyangzhou/liferay-portal/pull/3388

**Comment by peterfellwock** [comment]
@brianchandotcom this fix by @rotty3000 will stop WSRP from triggering the PortletTracker exception during shutdown, and in theory yes we could remove the Ignore(s) in the WSRP tests, I sent myself this pull to confirm https://github.com/peterfellwock/liferay-portal/pull/252 

Also @brianchandotcom this will now make WSRP part of the deployment because it included the build triggers https://github.com/brianchandotcom/liferay-portal/pull/44495/commits/dae1df2ba078ef2b9df9e14d372815ae4fcd2ed6

**Comment by shuyangzhou** [comment]
@rotty3000 you did not fix the issue, but created a new issue, with your change at https://github.com/brianchandotcom/liferay-portal/pull/44495/commits/c5bba69b426d332e4dbe396e7be586d3daf56d13
WSRPConsumerPortlet no longer loads.
Check that yourself with gogo, run:
```
g! dm wtf
1 missing dependencies found.
-------------------------------------
The following service(s) are missing: 
 * com.liferay.portal.kernel.model.Portlet (javax.portlet.name=com_liferay_wsrp_portlet_WSRPConsumerPortlet) is not found in the service registry
```
Undo your change to WSRPConsumerPortlet the component will load again.
This is exactly the same circular dependencies issue we talked and solved months ago. 

We can not let DS component to use @Reference to refer to Spring extender service within the same module.

@hhuijser I thought we SF checked on this, how is this pull passed the checked ?

And @rotty3000 @Reference should not be applied to static fields right? See https://github.com/brianchandotcom/liferay-portal/pull/44495/commits/c5bba69b426d332e4dbe396e7be586d3daf56d13#diff-47fc5aeb9810c85c71ddbc79104628dbR2159 and https://github.com/brianchandotcom/liferay-portal/pull/44495/commits/c5bba69b426d332e4dbe396e7be586d3daf56d13#diff-47fc5aeb9810c85c71ddbc79104628dbR2161

**Comment by brianchandotcom** [comment]
@rotty3000 @peterfellwock I rolled this back because @shuyangzhou just Skyped me that the portlet no longer loads. Please resend. Thx.

**Comment by peterfellwock** [comment]
@brianchandotcom @rotty3000 I will take a look first thing tomorrow morning

**Comment by rotty3000** [comment]
Please don't do anything here I've already solved the issues. Everything is
working. Please wait for my PR.

**Pull request closed without merging**
