### PR TITLE
LPS-44960

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@brianchandotcom hey Brian, can you flush the cache for the nexus cdn?  I suspect we have a bad guice.jar in there:

Exception: invalid literal/lengths set
      [bnd]  Invalid class file com/google/inject/internal/util/$Maps.class (java.util.zip.ZipException: invalid literal/lengths set)
      [bnd]  Exception: 117
      [bnd]  Invalid class file com/google/inject/internal/util/$NullOutputException.class (java.lang.ArrayIndexOutOfBoundsException: 117)
      [bnd]  Exception: 25903
      [bnd]  Invalid class file com/google/inject/internal/util/$Nullable.class (java.lang.ArrayIndexOutOfBoundsException: 25903)
      [bnd]  Exception: malformed input around byte 1
      [bnd]  Invalid class file com/google/inject/internal/util/$ObjectArrays.class (java.io.UTFDataFormatException: malformed input around byte 1)
      [bnd]  Exception: invalid bit length repeat
      [bnd]  Invalid class file com/google/inject/internal/util/$Objects.class (java.util.zip.ZipException: invalid bit length repeat)
      [bnd]  Exception: invalid literal/lengths set
      [bnd]  Invalid class file com/google/inject/internal/util/$Preconditions.class (java.util.zip.ZipException: invalid literal/lengths set)

**Comment by brianchandotcom** [comment]
ci:retest

Flushed CDN cache. Retrying.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/aa2764ce28...7c6c910704

**Comment by brianchandotcom** [comment]
@mhan810 can you review my changes? I made quite a few. Thx.

**Pull request closed without merging**
