### PR TITLE
COMMERCE-12431 Feature flag description

### PR DESCRIPTION
**Pull request by JamesAGarcia**
Sent as follow up of https://github.com/brianchandotcom/liferay-portal/pull/143961

This PR updates the feature flag description for COMMERCE-12431. Let me know if this is what you had in mind.

cc. @smottal

### CODE REVIEW

**Comment by JamesAGarcia** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@JamesAGarcia beautiful

**Comment by smottal** [comment]
Hi @brianchandotcom, in the description there is Organization Management widget but the widget is called Organization Management **Chart**. Let me know if we need to update the description with the "full name". Thx

**Comment by brianchandotcom** [comment]
@smottal please send me a follow up PR (direct)

**Comment by JamesAGarcia** [comment]
Hello there, @smottal, I just wanted to clarify this comment:

> in the description there is Organization Management widget but the widget is called Organization Management Chart.

Is the Organization Management widget being renamed in the UI? Or is this feature referring to a different widget?

In general, we recommend using the widget's name in the UI to avoid confusion.

**Comment by smottal** [comment]
Hi @JamesAGarcia, sorry, you're right, I was relying on the text provided to me by my PO. But at this point I think we should change the title of the feature flag because it reports `feature.flag.COMMERCE-12192.title=Organization Management Chart Enhancements`. What do you think?

**Comment by JamesAGarcia** [comment]
@smottal, just got back from PTO. 

Yes, updating the title would make sense. Either of these would work:
Organization Management Enhancements
Organization Management Widget Enhancements

**Pull request merged**
