### PR TITLE
LPS-62977 Simplify

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by jpince** [comment]
@brianchandotcom these look like real failures, please do not merge

**Comment by brianchandotcom** [comment]
@sergiogonzalez please resend. THx.

**Comment by jpince** [comment]
@pavel-savinov @sergiogonzalez it looks like these failures are unique to this pull... either the page is not correctly redirected after the content is saved, or the user cannot save the content they are trying to add.

Example:
1. Click on this link: [CPBookmarks#AddBookmark Failure](https://testray.liferay.com/reports/production//logs/test-1-18/1471890113166/test-portal-acceptance-pullrequest%28master%29/491/functional-tomcat8-mysql56-jdk8/18/1/CPBookmarks_AddBookmark/index.html.gz)
2. Click on the exclamation point in the triangle (top right) to go to the step where the test failed. 
3. Notice the step immediately prior clicks on "Save" (PortletEntry#Save), but the screenshot shows that portal did NOT navigate away from the Bookmark creation page, indicating that either the redirect or the process to save is broken. The same occurs for other portlets where the test will click "Save" or "Publish", then try to do something else.

Portlets across portal are affected, for example, Bookmarks, DM, Forms, ADT, Calendar, and Message Boards.

**Comment by pavel-savinov** [comment]
@jpince @brianchandotcom The original pull (https://github.com/sergiogonzalez/liferay-portal/pull/3387) does not break the tests and it seems to be just a coincidence. @sergiogonzalez could you please take a look once again?

**Comment by sergiogonzalez** [comment]
We have resent it here https://github.com/brianchandotcom/liferay-portal/pull/42531

**Pull request closed without merging**
