### PR TITLE
LPS-96727 Replace metal-uri with URL

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ede4eb3966...3a27d2e3b1

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:test:bundle:norebase

**Pull request closed without merging**
