### PR TITLE
LPS-69159 Add plid and scopeGroupId to RSS link for blogs

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
@sergiogonzalez there was a bug in CI, we're fixing it  now. Merged.

**Pull request closed without merging**
