### PR TITLE
LPS-78939 Removing social bookmarks analytics from blogs

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@petershin can you fix this:

```
junit.framework.AssertionFailedError: Forbidden modules/private/apps/portal-search-elasticsearch6-xpack-security/gradle.properties
	at com.liferay.portal.modules.ModulesStructureTest$1.preVisitDirectory(ModulesStructureTest.java:123)
	at com.liferay.portal.modules.ModulesStructureTest$1.preVisitDirectory(ModulesStructureTest.java:88)
	at java.nio.file.Files.walkFileTree(Files.java:2677)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.liferay.portal.modules.ModulesStructureTest.testScanBuildScripts(ModulesStructureTest.java:86)
```

**Comment by brianchandotcom** [comment]
@4lejandrito type:

git grep top_head **Analytics**DynamicInclude.java

and you'll see all the examples.

**Comment by petershin** [comment]
@brianchandotcom - Sent fixes: https://github.com/brianchandotcom/liferay-portal-ee/pull/19618

**Pull request closed without merging**
