### PR TITLE
LPS 121457 final sort

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
Hi @brianchandotcom,

I moved the `lastPublishDate` at the end.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4b1b85775d...1181556af2

**Comment by brianchandotcom** [comment]
@4lejandrito see 1181556af2e71af7289b269dc91825a12fa3ffb1

I did NOT backport this to 7.3.x

**Pull request closed without merging**
