### PR TITLE
LPS-100926 Set non proxy hosts as part of dummy proxy setting

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-100926

### CODE REVIEW

**Comment by austinchiang** [comment]
cc @4lejandrito @yichenroy

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7b1074dc7e...10ec5cf1ce

**Comment by brianchandotcom** [comment]
@4lejandrito I backported this since it's mainly tests.

See fe489fe6bc44f98e2bf329416c453ea509d7e1cd 8f9f1a1b1b94f2c17e96e5f9f0a76b3c870316ce 8fbf284b2bf09ddcd1ecb40b629f70215a862623 and  10ec5cf1ceca44b1a7a2cbfbcec67988022fcd59

Thx

**Pull request closed without merging**
