### PR TITLE
LPS-172127 LPS-178524 [FE] Update "Aggregation Field" tooltip text and add help text

### PR DESCRIPTION
**Pull request by thektan**
**Story:** https://issues.liferay.com/browse/LPS-172127
**Subtask:** https://issues.liferay.com/browse/LPS-178524

---

- Manually forwarding from https://github.com/liferay-search/liferay-portal/pull/871, no related failures

---
**Original comment:**

> ### Screenshots
> 
> Screenshot 2023-03-30 at 2 44 31 PM
> ("Learn more." link will appear once learn-resources module is published)

### CODE REVIEW

**Comment by thektan** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0026e78c86...bfde0495de

**Comment by brianchandotcom** [comment]
@thektan see 634cbad0a7397760572884359e201b53ceafc712

As a user, I'd be upset that I'd have to go find the documentation. We should really like to it (perhaps use the Learn taglib/JSON)

Please send a follow up PR. Thx.

**Comment by thektan** [comment]
@brianchandotcom There is a "Learn more." doc link at the end of the help text below the input already.

> Follow the steps in the documentation to use object and web content structure fields. [Learn more.](https://learn.liferay.com/dxp/latest/en/using-search/search-pages-and-widgets/search-facets/custom-facet.html)

The `learn-resources` module would need to be published again for it to appear. Is this something that would need to be mentioned for you to re-publish in PRs or would the `learn-resources` module be automatically re-published.

**Pull request closed without merging**
