### PR TITLE
LPS-78860 Language selection in instance setting does not preserve ordering no more

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test

**Comment by NorbertKocsis** [comment]
Hi!

@arthurchan35 asked me to check this and I think if we want to go this way we should also order the right side, as it's in the order defined in the property right now.

And my idea was to get left list from the typesettings instead of using LanguageUtil. That way we could preserve the order. Or we could extend LanguageUtil's API but I don't like the idea as the order doesn't matter anywhere else.

Br,
Norbert

**Comment by arthurchan35** [comment]
@NorbertKocsis,
I am not sure I understand your first paragraph, I was going to make left list not orderable and same as right list, that they are always order by alphanumerical. Are you saying you want to make the right list orderable?

For your second comment, I have no problem with it. If you think it's a better solution, go ahead close this pull request.

**Comment by arthurchan35** [comment]
@jkappler 
I talked to Norbert, we agree to switch to his proposal, so I am closing the pr.

Thanks

**Comment by arthurchan35** [comment]
ci:close

**Comment by arthurchan35** [comment]
Talked to Norbert, we agreed to switch to his proposal.

**Pull request closed without merging**
