### PR TITLE
LPS-71909 Fix tests

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:retest

**Comment by leoadb** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3793427d78...5568b1957b

**Comment by brianchandotcom** [comment]
@leoadb see 5568b1957b5bfff86779f2ea38b65f1482d041b3

**Pull request closed without merging**
