### PR TITLE
LPS-116730 - Update @clayui dependencies

### PR DESCRIPTION
**Pull request by jbalsas**
Manual forward of https://github.com/liferay-frontend/liferay-portal/pull/83

Last [test run](https://github.com/liferay-frontend/liferay-portal/pull/83#issuecomment-660269766)
✔️ ci:test:stable - 20 out of 20 jobs passed
❌ ci:test:relevant - 174 out of 188 jobs passed in 2 hours 14 minutes

> the unique test failures seem unrelated. Raised the issues to qa-ci  https://liferay.slack.com/archives/CL3TWSMHQ/p1595012127092300

--- 

Update the following dependencies

~@clayui/autocomplete@3.1.6,
@clayui/breadcrumb@3.2.2, 
@clayui/card@3.2.3, 
@clayui/color-picker@3.2.6, 
@clayui/css@3.14.0, 
@clayui/data-provider@3.2.1, 
@clayui/date-picker@3.4.1, 
@clayui/drop-down@3.4.5, 
@clayui/list@3.2.7, 
@clayui/localized-input@3.1.2, 
@clayui/multi-select@3.5.6, 
@clayui/multi-step-nav@3.2.2, 
@clayui/nav@3.2.1, 
@clayui/navigation-bar@3.2.0, 
@clayui/pagination-bar@3.1.6, 
@clayui/pagination@3.2.2, 
@clayui/panel@3.2.2, 
@clayui/popover@3.4.2, 
@clayui/shared@3.1.3, 
@clayui/tabs@3.2.2, 
@clayui/time-picker@3.1.5, 
@clayui/tooltip@3.3.2,~

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3dbd7638c7...4382f0ad16

**Comment by brianchandotcom** [comment]
@jbalsas follow up to sort:

````
@import 'components/_carousel';
@import 'components/_jumbotron';
@import 'components/_toasts';
@import 'components/_spinners';
```

@wincent please enforce sorting

Also, what happened to modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-field-type/src/main/resources/META-INF/resources/DatePicker/DatePicker.es.js

The "else if {" is off?

@bryceosterhaus fyi

**Comment by jbalsas** [comment]
Hey @pat270, can you take a look to see if those can be sorted or split them otherwise?

@bryceosterhaus is on PTO, so I'll followup with the DDM else-if thing. This happens because we deviate away from the default formatting, so depending on your toolchain, things different plugins will format different things 😭 

/cc @wincent, just fyi

**Comment by wincent** [comment]
About the `@import` sorting we have to be careful, because changing the order can change the behavior; so we do the thing where we use blank lines to force ordering (ie. we sort within each group, but never across groups). [This is the lint rule here](https://github.com/liferay/liferay-npm-tools/blob/master/packages/liferay-npm-scripts/src/scripts/lint/stylelint/plugins/sort-imports.js).

We have [tests for that](https://github.com/liferay/liferay-npm-tools/blob/619371ae92d58665ec2196b33ab0117dc05343db/packages/liferay-npm-scripts/test/scripts/lint/stylelint/plugins/sort-imports.js), so I'm relatively confident that it works. The fact that the `else if {` was also wrong makes me think that somehow the source formatter wasn't properly run on these changes at some point. 

> depending on your toolchain, things different plugins will format different things

While it's true that you might run a formatter in VSCode or Vim etc that behaves a certain way, running `gradlew formatSource` (or `yarn format`) should always produce the right result. We saw `ci:test:sf` [pass here](https://github.com/liferay-frontend/liferay-portal/pull/83#issuecomment-655172980), but you can see several force-pushes _after_ that which introduced the bad formatting (eg. compare [before](https://github.com/liferay-frontend/liferay-portal/blob/d416d4a30b1152a0335d8c61b03f7e8d426e5fe1/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-field-type/src/main/resources/META-INF/resources/DatePicker/DatePicker.es.js) and [after](https://github.com/bryceosterhaus/liferay-portal/blob/1df38a6f35f71076e30c839d0219a22f75d67d58/modules/apps/dynamic-data-mapping/dynamic-data-mapping-form-field-type/src/main/resources/META-INF/resources/DatePicker/DatePicker.es.js)), and we didn't run `ci:test:sf` after that, so I think everything is working as intended at the infra level.

**Comment by jbalsas** [comment]
> While it's true that you might run a formatter in VSCode or Vim etc that behaves a certain way, running gradlew formatSource (or yarn format) should always produce the right result. We saw ci:test:sf pass here, but you can see several force-pushes after that, one of which introduced the bad formatting (eg. compare before and after), and we didn't run ci:test:sf after that, so I think everything is working as intended at the infra level.

Yeah, I'm pretty sure that was it... since `SF` was green and had been failing in general on friday, we just piggybacked on one earlier run. Maybe `ci:forward` should've re-run `sf`... 

/cc @kenjiheigel

**Comment by wincent** [comment]
> Maybe `ci:forward` should've re-run `sf`...

This was a manual forward though.

**Comment by jbalsas** [comment]
Ugh, you're right 🙈

**Comment by pat270** [comment]
@jbalsas That group can be sorted. I'll update in Clay CSS.

**Pull request closed without merging**
