### PR TITLE
LRQA-58838 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-58838

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@austinchiang shouldn't we still test deprecated apps? Until they are gone?

I don't like this policy of not testing deprecated apps.  I'm merging this.. but

@vicnate5 @jpince can you guys explain to me why we're not testing deprecated apps?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/93d94a51e8...32d61030fd

**Comment by austinchiang** [comment]
Hey @brianchandotcom In the case of Documentum, it was a standalone Marketplace app that was already deprecated since 7.2 (the last released version was 7.1). Our tests for the app have since been disabled (which is part of the reason why the disabled test count for Lima is higher than other teams) because we're not doing any support or maintenance work for it. So I don't think it makes sense to keep those tests around. There is a possibility that existing customers using the app in legacy versions may find bugs, so we are not planning to remove tests on those branches for that reason.

**Pull request closed without merging**
