### PR TITLE
Lps 68778

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @sergiogonzalez @mhan810

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
@michaelhashimoto and @pyoo47 same DB issue here.

**Comment by shuyangzhou** [comment]
This is the portal-ext.properties echo result from a node of modules-integration-hypersonic20-jdk8
```

prepare-portal-ext-properties:
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/portal-impl/src/portal-ext.properties
     [echo] 
     [echo] ##
     [echo] ## /opt/dev/projects/github/liferay-portal/bundles/tomcat-8.0.32/webapps/ROOT/WEB-INF/classes/portal-ext.properties
     [echo] ##
     [echo] 
     [echo] 
     [echo] 
     [echo] liferay.home=/opt/dev/projects/github/liferay-portal/bundles
     [echo] 
     [echo] plugin.notifications.enabled=false
     [echo] 
     [echo] jdbc.default.jndi.name=
     [echo] 
     [echo] jdbc.default.driverClassName=com.mysql.jdbc.Driver
     [echo] jdbc.default.url=jdbc:mysql://localhost/lportal?characterEncoding=UTF-8&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&useFastDateParsing=false&useUnicode=true
     [echo] jdbc.default.username=root
     [echo] jdbc.default.password=
     [echo] 
     [echo] captcha.max.challenges=-1
     [echo] 
     [echo] browser.launcher.url=
     [echo] 
     [echo] index.on.startup=true
     [echo] 
     [echo] setup.wizard.enabled=false
     [echo] 
     [echo] mail.session.jndi.name=
     [echo] 
     [echo] sprite.root.dir=/tmp/sprite
     [echo] 
     [echo] axis.servlet.hosts.allowed=
     [echo] 
     [echo] tunnel.servlet.hosts.allowed=
     [echo] 
     [echo] module.framework.properties.osgi.console=11312
     [echo] 
     [echo] module.framework.properties.osgi.console=11312
```

It says jdbc.default.driverClassName=com.mysql.jdbc.Driver. There must be an issue in the post distribution "fixing" logic, it is not "fixed" to become a hypersonic20 node.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
