### PR TITLE
OAUTH2-124 Merge REST module to master

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Hi Brian. This new REST module has been through reviews by both @topolik & @csierra, I have simply chunked the commits. Thanks! :)

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test

**Comment by stian-sigvartsen** [comment]
ci:retest

**Comment by stian-sigvartsen** [comment]
@brianchandotcom Apologies, Will fix the artificial dependency issue and re-test with CI on my fork before sending again...

**Comment by brianchandotcom** [comment]
@stian-sigvartsen can you resend on top of https://github.com/stian-sigvartsen/liferay-portal/pull/75

Better yet, please read my changes, and apply them to the other Java files. It'll make merging in your next pull a lot faster. Those are simple small things that I've made note of before.

I had only gone through about 25% of the files.

Thanks.

**Comment by stian-sigvartsen** [comment]
Thanks @brianchandotcom , will do!

**Pull request closed without merging**
