### PR TITLE
LPS-68848 SF

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:stop

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
@brianchandotcom the slim-runtime _module_ must use `RegistryUtil`. It's deployed into `WEB-INF/lib` and implements some functions from the core.

Someone will have to fix source formatter plugin to accept this!

**Comment by jpince** [comment]
@rotty3000 could you send this pull to @hhuijser before asking for it to be committed to source? That way we can keep the PR Tester green :)

**Pull request closed without merging**
