### PR TITLE
LPS-96987 SF

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@achaparro can you resend and rename TEMP to TEMP_TABLE (I really dislike using short words in case someone else used it somewehre). Type: git grep TEMP_TABLE

for l1 can you rename to layout1, and l2 can you rename to layout2?

Thx

**Comment by brianchandotcom** [comment]
@achaparro also, what's the status of LPS-82804

Is that getting backported to 7.2.x? I haven't seen a pull yet

**Comment by achaparro** [comment]
Hey @brianchandotcom,

Ok we will send these pulls tomorrow:
1. The backport of  LPS-82804 to 7.2.x (liferay user)
2. This pull with TEMP_TABLE as table name to you

Thanks.

cc/ @SamZiemer @chanmj96

**Comment by SamZiemer** [comment]
Forwarded here: https://github.com/brianchandotcom/liferay-portal/pull/75243

**Pull request closed without merging**
