### PR TITLE
Lps 185647 redo

### PR DESCRIPTION
**Pull request by shuyangzhou**
@mbowerman @achaparro I went ahead redoing this fix without integration anything to hibernate. DB partition is a feature that should only integration at jdbc and higher logic level, it should not do anything to plug into hibernate.

To keep the history clean, I reverted all your previous commits. At least they are not needed to fix the issue on the ticket. If you still think part of the change is needed for some other reasons, please send me a followup with explanation of why they are needed.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6692fc76db...9deabd4196

**Comment by brianchandotcom** [comment]
@shuyangzhou thanks!!!

**Comment by mbowerman** [comment]
@shuyangzhou @brianchandotcom This is not going to work. This will fix [LPS-185647](https://liferay.atlassian.net/browse/LPS-185647) but it is going to re-break [LPS-184771](https://liferay.atlassian.net/browse/LPS-184771) because that one is not going through CompanyLocalServiceImpl.forEachCompanyId.

We actually originally tried an approach similar to this, but putting it in CompanyThreadLocal.setCompanyId (because that is the correct place to put it, that ensures that the session actually is synced every time we leave the company scope). However, we couldn't get this to work because CompanyThreadLocal is in portal-kernel and we don't have information about the Session from there.

**Comment by shuyangzhou** [comment]
That should be treated as a completely different issue. The original commits were all on LPS-185647. This redo is only meant for fixing that.
As for LPS-184771 I don't really understand the steps. @vicnate5 can you interpret it a bit for me?

**Comment by mbowerman** [comment]
@shuyangzhou I don't understand why it should be treated as a completely different issue. Both issues occur because the Session gets flushed after we switch the companyId of the CompanyThreadLocal. We need a way to either (1) automatically flush the session before the CompanyThreadLocal is changed, or (2) Switch back to the correct companyId when flushing the Session.

You tried to implement solution (1) here but it only works when the CompanyThreadLocal is switched by calling `forEachCompanyId`. However, there are other ways to switch the CompanyThreadLocal besides calling `forEachCompanyId`, and it doesn't fix those.

We originally tried to implement solution (1) by flushing the Session during the `CompanyThreadLocal#_setCompanyId` method; however, we found this to be impossible as we couldn't access the session from within portal-kernel code.

Therefore we switched to Solution (2) as we found this to be possible.

The reason that we want to implement either Solution (1) or Solution (2) is because it will not only fix these two bugs that we have so far discovered ([LPS-185647](https://liferay.atlassian.net/browse/LPS-185647) and [LPS-184771](https://liferay.atlassian.net/browse/LPS-184771)), but it will _also_ fix many similar bugs that likely exist but have not yet been discovered. Any time that we call CompanyThreadLocal.setCompanyId, which happens many places throughout the code, there is a possibility that this Session flushing issue might occur. Fixing it only in the `portal-impl` places does not work as a generalized solution to fix the problem everywhere that this bug might occur.

There is more that I can say about why I believe it is very important for us to proactively fix/prevent database partitioning bugs before they get detected, but I am not sure how much I can say on a public forum like GitHub.

**Comment by shuyangzhou** [comment]
@mbowerman until your last message I know there is a different ticket LPS-184771 and it is not linked on https://liferay.atlassian.net/browse/LPS-185647 either.

I don't really understand the step in LPS-184771 , "deploy an oAuthApplicationHeadlessServer client extension to dev" what does this mean?
And when you say "we couldn't access the session from within portal-kernel code" that is just not true. We sure have access to it, portal-kernel and portal-impl are the same thing at runtime, they are sibling jars loaded by the same classloader.

I can fix LPS-184771 too, as long as I can understand what the steps is really saying.

Again, as I said on https://github.com/liferay-core-infra/liferay-portal/pull/4946#issuecomment-1624158888 spreading DB partition logic into hibernate integration is not acceptable, that is fundamentally wrong from design point of view.

**Comment by shuyangzhou** [comment]
@mbowerman I made a blind fix based on what you said about LPS-184771 See https://github.com/shuyangzhou/liferay-portal/pull/11122

@vicnate5 could you re-test both LPS-185647 and LPS-184771 on the new pull? If it fixes both of them I don't need to know how to test LPS-184771, otherwise please break down that step into something I could understand, thanks!

**Comment by mbowerman** [comment]
@shuyangzhou Thank you, your latest fix looks good to me. This is what we wanted to do originally but couldn't figure out how (we were trying to access the Hibernate Session object directly, but couldn't figure out how from portal-kernel code).

With regards to LPS-184771, I just use the steps on the linked LPP to test, because they're better-written/more descriptive. They also provide an existing Client Extension that you can use for testing there. Anyway I can test it tomorrow morning when I get into the office. I'm pretty sure your fix should fix it though.

**Comment by shuyangzhou** [comment]
@mbowerman @vicnate5 this is the lastest one https://github.com/shuyangzhou/liferay-portal/pull/11124
The previous one broke something. Due to the fact for some reason we have code that switching companyId with the current threadlocal companyId, basically the switch does nothing!!!

These CompanyThreadLocal swapping code is getting out of control. But anyway, I update the sync logic to only run when db partition is enabled and the company id has switched for real.

**Pull request closed without merging**
