### PR TITLE
LPS-86461 Do not allow portlets to startup if major and minor upgrade changes have not been executed 

### PR DESCRIPTION
**Pull request by achaparro**
Thanks @yuhai @anthony-chu for the collaboration.

cc/ @dantewang @dacousalr

### CODE REVIEW

**Comment by achaparro** [comment]
Hey @anthony-chu,

I have checked the issue and it's a bit strange since the exception says that a DDMStructure does not exist. If my changes were wrong we should get that the portlet DDM is not available or something similar. I am going to launch the whole suite of tests to verify possible errors.

Thanks.

**Comment by achaparro** [comment]
ci:test

**Comment by anthony-chu** [comment]
@achaparro

i took a look at master locally and on testray, and it looks like this issue is present there as well. i created a regression ticket for it here ([LPS-88699](https://issues.liferay.com/browse/LPS-88699)).

**Comment by brianchandotcom** [comment]
@anthony-chu I assume this is safe for me to merge?

**Comment by achaparro** [comment]
Hey @brianchandotcom,

I tried to do what you suggest but it is not possible with LDAP filters, **<** is not available, only **<=** :-(

Here you have some documentation about it:
https://stackoverflow.com/questions/9309726/strict-less-than-operator-in-ldap-search-filter
https://tools.ietf.org/html/rfc4511#section-4.5
https://osgi.org/javadoc/r2/org/osgi/framework/Filter.html

Please, let me know your thoughts.

Thanks

**Comment by brianchandotcom** [comment]
Wow. Please reopen then. Thx

**Comment by achaparro** [comment]
ci:reopen

**Comment by achaparro** [comment]
Resent:
https://github.com/brianchandotcom/liferay-portal/pull/66222

**Pull request closed without merging**
