### PR TITLE
Pull request 137430 commerce 11738

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
resend of this https://github.com/brianchandotcom/liferay-portal/pull/137430 on top of https://github.com/andrea-ale-sbarra/liferay-portal/pull/39

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c641fd6996...c54dfc42e3

**Comment by brianchandotcom** [comment]
@andrea-ale-sbarra just c54dfc42

**Comment by andrea-ale-sbarra** [comment]
thank you @brianchandotcom

**Pull request closed without merging**
