### PR TITLE
LPS-79000

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@matethurzo
The reason SF complains about this one (while the ones in other *Tag.java files are fine) is because class `PublishEntityMenuItemTag` is in module `modules/apps/web-experience/export-import` while the internal class `ServletContextUtil` that is used is in `modules/apps/export-import`

All the other cases, the `*Tag` class and `ServletContextUtil` are located in the same module

I suppressed the SF warning. Can you fix it.

Thanks!

/cc @jpince

**Comment by jpince** [comment]
ci:close <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jpince** [comment]
pushed upstream https://github.com/liferay/liferay-portal/commit/6e07ccbb18327d2354018274678bceacbd5d39c0 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jpince** [comment]
@matethurzo can you please resolve the issue and remove the suppression when you have time?

**Comment by matethurzo** [comment]
@hhuijser @jpince sorry I don't understand. The ```PublishEntityMenuItemTag``` is in ```modules/apps/export-import/export-import-changeset-taglib```not in ```modules/apps/web-experience/export-import```.

The ```ServletContextUtil``` class also it's in this exact same module ```import com.liferay.exportimport.changeset.taglib.internal.servlet.ServletContextUtil;``` like in all other taglibs.

So I cannot really fix this, as they are in the same module.

**Comment by hhuijser** [comment]
Hey @matethurzo, sorry for the late response.

The file that SF is complaining about is NOT the `PublishEntityMenuItemTag` in `modules/apps/export-import`, but the one in `modules/apps/web-experience/export-import`. Apparently we have that file in those two locations.

Both classes import the internal class `ServletContextUtil`, which is in `modules/apps/export-import`

**Comment by matethurzo** [comment]
@petershin you seem to have moved the export-import modules to the new locations. Why did you leave pieces of the code in the old location? it seems like it's causing SF errors, and also it's duplicated code.

**Comment by petershin** [comment]
Hi @matethurzo, it looks like the files were added on 944b2db436c4f061ead0736c6bcd871b7335f148.

@zoltancsaszi, it looks like a few files were added to the `web-experience` instead of `export-import`.  When you have time, can you take a look and move them to the new location?

**Pull request closed without merging**
