### PR TITLE
LPS-68448

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-68448.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @ithildir, this was supposed to be enforced by the build... it seems like it's doing it for `package.json` but not for `npm-shrinkwrap.json`... could you update the gradle tasks so this doesn't happen again in the future, please?

Thanks for figuring this out, guys!

**Comment by Ithildir** [comment]
Sorry, nobody told me we need to update the version in `npm-shrinkwrap.json` as well 😞

**Comment by jbalsas** [comment]
No worries, @Ithildir! I'll check next week in which point this becomes an issue (since we should be using the `package.json` file for everything that has to do with configuration), but better stay consistent now that we can have it.

**Comment by Ithildir** [comment]
I sent a pull with all the versions fixed and the build changes at https://github.com/brianchandotcom/liferay-portal/pull/43590.

**Comment by kenjiheigel** [comment]
The functional test failure is unrelated. It failed due to a VNC issue which caused Firefox to fail to load. I've let QA Engineering know.

**Comment by jonmak08** [comment]
We can probably close this in favor of https://github.com/brianchandotcom/liferay-portal/pull/43590.

**Comment by brianchiu** [comment]
ci:close

**Comment by brianchiu** [comment]
I've closed this per @jonmak08

**Pull request closed without merging**
