### PR TITLE
LPS-89507 Cannot delete a site based off of a Site Template that contains a Page Template

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
thanks for this one @jonathanmccann, @dacousalr!

**Comment by jkappler** [comment]
@brianchiu, we don't allow the creation of widget page templates in site templates anymore

cc:// @ealonso

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@dacousalr @jonathanmccann @jkappler good job keeping the order of service.xml in the upgrade classes.

**Pull request closed without merging**
