### PR TITLE
LPS-92323 This class is also specific to DM and has no effect

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-92323

### CODE REVIEW

**Comment by patriciajeanperez** [comment]
ci:close

**Comment by patriciajeanperez** [comment]
Closing due to [test failures](https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/255646/)

**Comment by patriciajeanperez** [comment]
Failures are workflow related and not caused by these changes. Reopening

**Comment by patriciajeanperez** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/429c2c4b45...19d82e65bd

**Pull request closed without merging**
