### PR TITLE
LPS-62787 fix cdn url

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:retest

**Comment by gamerson** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1a9ed1c64e...08649a5be8

**Comment by brianchandotcom** [comment]
@gamerson I published a new jar.

**Pull request closed without merging**
