### PR TITLE
LPS-106088 Do not ignore App builder during release

### PR DESCRIPTION
**Pull request by jeyvison**
Cc: @jpince @leoadb

### CODE REVIEW

**Comment by jeyvison** [comment]
Failures are not unique

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e055541372...2dabdc42f7

**Comment by brianchandotcom** [comment]
@brunofarache @jeyvison can you guys fix this:

ARIABLE=0,label_exp=!master #346193
LocalFile.AppBuilder#CreateRemoveUpdateDeleteEntriesOfStandaloneApp - Poshi Report - Poshi Summary - Console Output
LocalFile.AppBuilder#CreateRemoveUpdateDeleteEntriesOfWidgetApp - Poshi Report - Poshi Summary - Console Output
LocalFile.AppBuilder#PublishAppAsWidgetAndSubmitEntry - Poshi Report - Poshi Summary - Console Output

**Comment by brunofarache** [comment]
@alexcandidos it’s happening frequently.

**Comment by alexcandidos** [comment]
Hey @brunofarache , this failures are not flaky. It is probably happening due to code changes that were merged on this PR https://github.com/brianchandotcom/liferay-portal/pull/82111. Since there the tests are failing. 

There is no fix to be made on the scripts. 

I think the changes you sent through PR https://github.com/brianchandotcom/liferay-portal/pull/82177 (closed by you before merging) or probably this one https://github.com/brianchandotcom/liferay-portal/pull/82230 (merged 8hs ago) were supposed to fix this issue that is causing these 3 scripts fail, as we can see these 3 scripts passed. 

As the relevant was performed on this PR https://github.com/brianchandotcom/liferay-portal/pull/82234 before the https://github.com/brianchandotcom/liferay-portal/pull/82230 be merged, the tests were still failing. 

Thanks!

**Pull request closed without merging**
