### PR TITLE
LPS-112926 | master

### PR DESCRIPTION
**Pull request by vicnate5**
Resolves unit test blocker at head. Forwarded from https://github.com/brunofarache/liferay-portal/pull/259

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:reopen

**Comment by vicnate5** [comment]
Closing, possible regression on this PR.

**Comment by vicnate5** [comment]
Reviewed failure with App Builder QA, this is OK to merge.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4d1da465b2...1d24bc5282

**Pull request closed without merging**
