### PR TITLE
LPS-98031 Unused constant

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/418a8c561c...9fce4289e3

**Comment by brianchandotcom** [comment]
lbm:backport @CsabaTurcsan @jpince @zsoltbalogh

**Comment by brianchandotcom** [comment]
@pavel-savinov I had to rever this commit in upstream because it broke the build:

```
> Task :apps:layout:layout-content-page-editor-web:processResources
> Task :apps:layout:layout-content-page-editor-web:downloadNode SKIPPED
> Task :apps:layout:layout-content-page-editor-web:expandJSCompileDependencies UP-TO-DATE
> Task :apps:layout:layout-content-page-editor-web:npmInstall SKIPPED

> Task :apps:layout:layout-content-page-editor-web:npmRunBuild
yarn run v1.13.0
warning package.json: No license field
$ liferay-npm-scripts build
Using NODE_ENV: production
Compiling soy
Error in plugin 'metal-tools-soy'
Message:
    Compile error:
errors during Soy compilation
src/main/resources/META-INF/resources/js/components/floating_toolbar/link/FloatingToolbarLinkPanel.soy:185: error: Undefined template 'com.liferay.layout.content.page.editor.web.FloatingToolbarMappingPanel.assetSelect'.
			{call com.liferay.layout.content.page.editor.web.FloatingToolbarMappingPanel.assetSelect}
   ^
1 error
```

That means it probably worked when you sent this, but since then, someone else changed that same JS file that  made it so your changes do not work ( though there was no conflict).

@jpince @kyle-miho

**Comment by kyle-miho** [comment]
@pavel-savinov https://github.com/brianchandotcom/liferay-portal/commit/3e05165787874e7f838c33b27616eec456959e9d#diff-dd1315a3ec54805a30bd61c720f61af2
the assetSelect template was removed here in this commit. Because i think they both run tests based off of upstream, and they were both in bchans origin, they both passed, however they conflict with each other.

**Comment by kyle-miho** [comment]
can you update it to use com.liferay.layout.content.page.editor.web.AssetSelector.render if thats the new used method? @sandrodw3

**Pull request closed without merging**
