### PR TITLE
LPS-104415 regen

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
@brianchandotcom  in this pull I am bumping REST api version due to: 
    - Scoping data definition by Company instead of Site
    - classNameId should be internal. I am using the concept of a content space for a data engine. We need this in order to separate data definition created for App Builder, Web Content, Forms, etc...
    - I've simplied permission checking. We only need to check against access permission. The clients of data engine should create their own permissions

Request executors are business components. I've applied this approach in order to move business logic from Resources to those executors, so we 
can inject in normal Java classes without the need to do a REST call. This approach is the same as what we have in SearchEngineAdapter.

I've implemented only a few methods of Resources just to give you a heads up of what we are trying to do. If it looks fine to you then we can send the other methods next.

I talked to @mhan810 about this. 

cc @brunofarache @jeyvison

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by leoadb** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@leoadb will resend.

**Pull request closed without merging**
