### PR TITLE
LPS-27113 Support ADT in Navigation Portlet

### PR DESCRIPTION
**Pull request by epgarcia**
@jkappler 
@marcellustavares

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by epgarcia** [comment]
ci:retest

**Comment by epgarcia** [comment]
ci:retest

**Comment by epgarcia** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@epgarcia please resend on top of https://github.com/epgarcia/liferay-portal/pull/387 thx

**Pull request closed without merging**
