### PR TITLE
App Servers Support: Proper Wildfly configuration

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by jpince** [comment]
@brianchandotcom looks good from a functional test perspective, please merge for DXP release.

**Comment by jpince** [comment]
@migue do you think this will also solve LPS-66596?

**Comment by migue** [comment]
@jpince I don't think so; according to the error reported in the ticket seems that the command line we're trying to execute is too long. This is a limitation of operating system (Windows)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/74aa3829c7...d0dc23ac19

**Comment by brianchandotcom** [comment]
@migue @jpince minor tweak in 73fa205a94fca7b44f2e158b2344f44ecdc02255

**Comment by brianchandotcom** [comment]
@migue link works now 73fa205a94fca7b44f2e158b2344f44ecdc02255

**Pull request closed without merging**
