### PR TITLE
LPS-106514 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-106514

### CODE REVIEW

**Comment by kyle-miho** [comment]
cc: @ealonso @jkappler

**Comment by kyle-miho** [comment]
Fixes stable PortalSmoke#Smoke failure, language key wasnt being translated since layout.types.portlet= was on the same line of another language key that shouldn't have been there

**Comment by kyle-miho** [comment]
This is rebased to brianchandotcom/liferay-portal and not liferay/liferay-portal so it will automatically fail the ci build

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2ae0f1a13d...07031187e1

**Pull request closed without merging**
