### PR TITLE
LPS-180399 It is more accurate to use _portal.getServletContextName()

### PR DESCRIPTION
**Pull request by mbowerman**
rather than StringPool.BLANK here. _portal.getServletContextName() should work for all application servers, whereas StringPool.BLANK does not (for example, WebSphere).

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:reopen

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Great job @mbowerman this looks right to me.

**Pull request closed without merging**
