### PR TITLE
LPS-93888 Use the className and classPK of the layout associated with the layoutPageTemplateEntry

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
Thanks @kyle-miho!

**Comment by jpince** [comment]
@john-co see theme/clay error above. Probably not related to the pull (int test fix), but strange that it happened twice in one PR. Didn't see it in any other PRs this morning

**Comment by john-co** [comment]
ci:test:bundle

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by jpince** [comment]
@john-co other occurrences of the frontend-theme-admin:npmRunBuild failure:
https://github.com/brianchandotcom/liferay-portal/pull/71458#issuecomment-482579339
https://github.com/brianchandotcom/liferay-portal/pull/71457#issuecomment-482574599
those are the only examples that I've seen this morning

**Pull request closed without merging**
