### PR TITLE
LPS-85785

### PR DESCRIPTION
**Pull request by brunofarache**
@brianchandotcom I ran tests twice in different PRs and the poshi tests related to Forms are not showing up anymore, I asked @alexcandidos to check if it's an intermittent failure or not, or if it was happening before and it was fixed.

### CODE REVIEW

**Comment by alexcandidos** [comment]
@brunofarache regarding the failures that happened in the previous is PR (https://github.com/brianchandotcom/liferay-portal/pull/76882)... one of them is a known issue that is only happening on CI (FormRules#ConfigureAutofillRule) and the another one (Forms#PreviewAndPublishForm) seems to be a flaky test result based on the test history (it is passing in upstream but we can find it failing sometimes in the test history (https://testray.liferay.com/home/-/testray/case_results/727057159/history?tab=result&hideFilterPin=true). 
And it passed in the latest PR you sent to me (https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=727255928&testrayTeamId=438902480&testrayComponentId=438903295)

Let's see the results here.

**Comment by alexcandidos** [comment]
hi @brunofarache , according to the last test results, only the known issue is failing (FormRules#ConfigureAutofillRule). The test (Forms#PreviewAndPublishForm) passed. I'm temporarily removing (https://github.com/brianchandotcom/liferay-portal/pull/76925) the known issue from Acceptance test routine to avoid noise when running relevant. When we figure out how to fix (FormRules#ConfigureAutofillRule) we add it back.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9819ea16e7...4ca47d4b22

**Comment by brianchandotcom** [comment]
@brunofarache @alexcandidos please see my changes in upstream.

**Comment by brianchandotcom** [comment]
@IstvanD see my changes in upstream. Thx.

**Comment by brianchandotcom** [comment]
lbm:backport @CsabaTurcsan @jpince @zsoltbalogh

**Comment by IstvanD** [comment]
Hi @brianchandotcom thank you for committing.

**Pull request closed without merging**
