### PR TITLE
[FEEDBACK] LPS-93844 add transactioncontainerfilter

### PR DESCRIPTION
**Pull request by javiergamarra**
I've not found a way of accessing commit()/rollback() directly without using DefaultTransactionExecutor and to be able to create it I need a PlatformTransactionManager that I'm getting through reflection. I'm sure there is a better way to do this.

I'm also not sure if the threadlocal is needed or would be enough (and safer) passing several properties in the ContainerRequestContext.

Updated with some small renames and a test to check it works.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
This is soooooooo good. I'll send this to Shuyang and Preston next week.

**Comment by jpince** [comment]
@nhpatt can you please look into this int test failure?
```
     [exec] com.liferay.headless.delivery.resource.v1_0.test.BlogPostingImageResourceTest > testPostSiteBlogPostingImageUsesTransation STARTED
     [exec] 
     [exec] 00:00:01,789 ERROR [com.liferay.headless.delivery.resource.v1_0.test.BlogPostingImageResourceTest-executor-thread][BaseBlogPostingImageResourceTestCase:651] Unable to process HTTP response: Invalid file name *,?
     [exec] com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Invalid': was expecting 'null', 'true', 'false' or NaN
     [exec]  at [Source: (String)"Invalid file name *,?"; line: 1, column: 8]
     [exec] 	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
     [exec] 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:703)
     [exec] 	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2853)
     [exec] 	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2831)
     [exec] 	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._matchToken(ReaderBasedJsonParser.java:2612)
     [exec] 	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1883)
     [exec] 	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:757)
     [exec] 	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4141)
     [exec] 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4000)
     [exec] 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
     [exec] 	at com.liferay.headless.delivery.resource.v1_0.test.BaseBlogPostingImageResourceTestCase.invokePostSiteBlogPostingImage(BaseBlogPostingImageResourceTestCase.java:648)
     [exec] 	at com.liferay.headless.delivery.resource.v1_0.test.BaseBlogPostingImageResourceTestCase.testPostSiteBlogPostingImage_addBlogPostingImage(BaseBlogPostingImageResourceTestCase.java:611)
     [exec] 	at com.liferay.headless.delivery.resource.v1_0.test.BlogPostingImageResourceTest.testPostSiteBlogPostingImageUsesTransation(BlogPostingImageResourceTest.java:60)
```
https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/285475/AXIS_VARIABLE=0,label_exp=!master/consoleFull

**Comment by nhpatt** [comment]
It was on purpose but I suppose it logs something... and that fails the build. I will look into an alternative.

**Comment by nhpatt** [comment]
@jpince fixed in another PR that I'll send after I investigate the ones in the email :)

**Comment by jpince** [comment]
@nhpatt merge conflict

**Comment by nhpatt** [comment]
It's just for feedback @jpince, once received I can rebase it.

**Pull request closed without merging**
