### PR TITLE
LPS-83418 Semver

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@pedroqueiroz SF had an error

[java] Missing Web-ContextPath, see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/documentation/bnd_bundle_information.markdown: ./modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/bnd.bnd (SourceCheck:BNDWebContextPathCheck)


Fixed in 93ea46dcf4bc0734a0be3d187bc47459bf18b6a7

@petershin not sure how this passed the SF check in CI. Pull from upstream and remove my fix in 93ea46dcf4bc0734a0be3d187bc47459bf18b6a7 and run "ant format-source" and it'll run into the error.

**Comment by pedroqueiroz** [comment]
Thanks, @brianchandotcom !

**Comment by petershin** [comment]
@brianchandotcom - Looking into it.

**Comment by petershin** [comment]
Hi @brianchandotcom,

The `ci:test:sf` task only checks files that are added or modified in the pull.  The [dynamic-data-mapping-service/bnd.bnd](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/bnd.bnd) wasn't modified so SF didn't run any checks on the file.

It looks like the bug was introduced on https://github.com/brianchandotcom/liferay-portal/pull/61345.  The `ci:test:sf` task didn't catch it there either because of the same reason above.

**Pull request closed without merging**
