### PR TITLE
LPS-56857 clear default success message in case when adding entity in popup

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
Hi @brianchandotcom, 
in accordance with the discussion in mail about PR #32307 just resending the pull. MVCActionCommand works only within the action phase and we need to clear the message on render/resource phase.

**Comment by juliocamarero** [comment]
:+1:

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pavel-savinov sorry about this, but what about MVCResourceCommand and MVCRenderCommand?

The goal is that MVC*Command  had a lot of the functionality of MVCPortlet, and we have to split it from one to the other. Please resend.

**Pull request closed without merging**
