### PR TITLE
LPS-63690 Gradle cache

### PR DESCRIPTION
**Pull request by brunobasto**
/cc @kenjiheigel @mjbradford89

### CODE REVIEW

**Comment by brunobasto** [comment]
@vicnate5 Are those known failures for Calendar?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ec71959ffe...b442856949

**Comment by brianchandotcom** [comment]
@brunobasto Yes.. and they only happen during certain parts of the day..

@vicnate5 can you guys make those tests more robust? thx.

**Comment by brunobasto** [comment]
Thx,  @brianchandotcom

**Pull request closed without merging**
