### PR TITLE
LPS-57577 For CI bump all elasticsearch warn time threshold to 600s.

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/60640652d2...6399b82398

**Comment by brianchandotcom** [comment]
@shuyangzhou will this fix DLFileEntrySearchTest.testSearchTikaRawMetadata too, or just the random scan logs?

Thx

**Comment by brianchandotcom** [comment]
Also, @shuyangzhou why 10 minutes, why not 10 seconds, or 60 seconds?

10 minutes is kind of long no? Thx.

**Comment by shuyangzhou** [comment]
No, this has nothing to do with DLFileEntrySearchTest.testSearchTikaRawMetadata, it looks like a real failure from yesterday's OSGi changes.

I tried 10s, it failed again. I did not try 1min, it is highly possible fails too. 10mins is kind of too long, but it still fails, then it really means something is wrong, we will have to take actions on it.

**Pull request closed without merging**
