### PR TITLE
LPS-92219 Make regular users see other group members on autocomplete

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
Hey @pei-jung, I've made a little change to the UserLocalService class, adding an overload to `searchSocial`  so that we can sort the autocomplete results.

**Comment by adolfopa** [comment]
ci:reopen

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
