### PR TITLE
LPS-57268

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@hhuijser can you do the same thing, but not require the line break?

public void testGetServiceWithServiceTra vs.

public void
testGetServiceWithServiceTra

Thx

**Comment by brianchandotcom** [comment]
@hhuijser also, is this limited to tests?

**Comment by hhuijser** [comment]
@brianchandotcom 

This is not limited to tests?
You saying you prefer on one line?:
public void veryLongName

**Comment by hhuijser** [comment]
Hey @brianchandotcom 

Not requiring that line break will be a bit more complicated with the current code.
Also, I simply looked at what we are doing right now as it looks like that we do that line break already all over the place right now...

See:
     [java] ./modules/apps/wiki/wiki-test/test/integration/com/liferay/wiki/trash/test/WikiPageDependentsTrashHandlerTest.java:450
     [java] ./modules/apps/wiki/wiki-test/test/integration/com/liferay/wiki/trash/test/WikiPageDependentsTrashHandlerTest.java:567
     [java] ./modules/apps/wiki/wiki-test/test/integration/com/liferay/wiki/trash/test/WikiPageDependentsTrashHandlerTest.java:656
     [java] ./modules/apps/wiki/wiki-test/test/integration/com/liferay/wiki/trash/test/WikiPageDependentsTrashHandlerTest.java:678
     [java] ./modules/apps/wiki/wiki-test/test/integration/com/liferay/wiki/trash/test/WikiPageDependentsTrashHandlerTest.java:775
     [java] ./modules/util/osgi-util/test/integration/com/liferay/osgi/util/test/ReflectionServiceTrackerTest.java:166
     [java] ./portal-impl/test/integration/com/liferay/portal/service/PortletPreferencesLocalServiceTest.java:618
     [java] ./portal-impl/test/integration/com/liferay/portal/service/PortletPreferencesLocalServiceTest.java:659
     [java] ./portal-impl/test/integration/com/liferay/portal/service/PortletPreferencesLocalServiceTest.java:706
     [java] ./portal-impl/test/integration/com/liferay/portal/service/PortletPreferencesLocalServiceTest.java:747
     [java] ./portal-impl/test/integration/com/liferay/portal/service/PortletPreferencesLocalServiceTest.java:884
     [java] ./portal-impl/test/integration/com/liferay/portal/service/PortletPreferencesLocalServiceTest.java:903
     [java] ./portal-impl/test/integration/com/liferay/portal/service/PortletPreferencesLocalServiceTest.java:992
     [java] ./portal-impl/test/integration/com/liferay/portal/util/PortalImplCanonicalURLTest.java:246
     [java] ./portal-impl/test/integration/com/liferay/portal/util/PortalImplCanonicalURLTest.java:277
     [java] ./portal-impl/test/integration/com/liferay/portal/util/PortalImplLocalizedFriendlyURLTest.java:463
     [java] ./portal-impl/test/integration/com/liferay/portal/util/PortalImplLocalizedFriendlyURLTest.java:472
     [java] ./portal-impl/test/integration/com/liferay/portal/util/PortalImplLocalizedFriendlyURLTest.java:499
     [java] ./portal-impl/test/integration/com/liferay/portal/util/PortalImplLocalizedFriendlyURLTest.java:508
     [java] ./portal-impl/test/integration/com/liferay/portal/util/PortalImplLocalizedFriendlyURLTest.java:533
     [java] ./portal-impl/test/integration/com/liferay/portal/util/PortalImplLocalizedFriendlyURLTest.java:542
     [java] ./portal-impl/test/integration/com/liferay/portlet/documentlibrary/service/persistence/DLFileEntryFinderTest.java:498
     [java] ./portal-impl/test/integration/com/liferay/portlet/documentlibrary/service/persistence/DLFileEntryFinderTest.java:514
     [java] ./portal-impl/test/integration/com/liferay/portlet/documentlibrary/service/persistence/DLFileEntryFinderTest.java:650
     [java] ./portal-impl/test/integration/com/liferay/portlet/documentlibrary/service/persistence/DLFileEntryFinderTest.java:666
     [java] ./portal-impl/test/integration/com/liferay/portlet/documentlibrary/service/persistence/DLFileEntryFinderTest.java:682
     [java] ./portal-impl/test/integration/com/liferay/portlet/documentlibrary/service/persistence/DLFileEntryFinderTest.java:698
     [java] ./portal-impl/test/integration/com/liferay/portlet/documentlibrary/service/persistence/DLFileEntryFinderTest.java:874
     [java] ./portal-impl/test/integration/com/liferay/portlet/documentlibrary/service/persistence/DLFileEntryFinderTest.java:890
     [java] ./portal-impl/test/integration/com/liferay/portlet/documentlibrary/service/persistence/DLFileEntryFinderTest.java:906
     [java] ./portal-impl/test/integration/com/liferay/portlet/documentlibrary/service/persistence/DLFileEntryFinderTest.java:922
     [java] ./portal-test-internal/src/com/liferay/portlet/subscriptions/test/BaseSubscriptionContainerModelTestCase.java:46
     [java] ./portal-test-internal/src/com/liferay/portlet/subscriptions/test/BaseSubscriptionContainerModelTestCase.java:64
     [java] ./portal-test-internal/src/com/liferay/portlet/subscriptions/test/BaseSubscriptionContainerModelTestCase.java:83
     [java] ./portal-test-internal/src/com/liferay/portlet/subscriptions/test/BaseSubscriptionContainerModelTestCase.java:101
     [java] ./portal-test-internal/src/com/liferay/portlet/subscriptions/test/BaseSubscriptionContainerModelTestCase.java:119
     [java] ./portal-test-internal/src/com/liferay/portlet/subscriptions/test/BaseSubscriptionRootContainerModelTestCase.java:30
     [java] ./portal-test-internal/src/com/liferay/portlet/subscriptions/test/BaseSubscriptionRootContainerModelTestCase.java:45
     [java] ./portal-test-internal/src/com/liferay/portlet/subscriptions/test/BaseSubscriptionRootContainerModelTestCase.java:58
     [java] ./portal-test-internal/src/com/liferay/portlet/subscriptions/test/BaseSubscriptionRootContainerModelTestCase.java:76
     [java] ./portal-test-internal/src/com/liferay/portlet/subscriptions/test/BaseSubscriptionRootContainerModelTestCase.java:94
     [java] ./portal-test-internal/src/com/liferay/portlet/subscriptions/test/BaseSubscriptionRootContainerModelTestCase.java:109

**Pull request closed without merging**
