### PR TITLE
LPS-68289 The incoming Throwable could be from system classloader.

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @mtambara

@tomwang2011 backport please.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@pyoo47 ?

ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@tomwang2011 I backported. this was easy.

**Pull request closed without merging**
