### PR TITLE
LPS-52139 SF manual

### PR DESCRIPTION
**Pull request by rotty3000**
@izaera I converted document-library-google-docs to use an embedded freemarker library. Can you verify that everything still works? I didn't know how to test it.

### CODE REVIEW

**Comment by rotty3000** [comment]
fixing...

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
I sent this pull to @izaera and wanted him to test before I merged it in. Can we automate the question from @rotty3000  ?

Thx

**Comment by rotty3000** [comment]
Automating the question doesn't make sense because it's not a code change,
just a library dependency change.

**Comment by brianchandotcom** [comment]
Sorry, "automating the question" was a bad way of saying it, I meant adding a test to ensure the template would load properly, regardless of which framework we used to load it..

**Pull request closed without merging**
