### PR TITLE
LPS-76009

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@matethurzo bravo!

**Comment by brianchandotcom** [comment]
@matethurzo please backport? Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a2c9a1b60c...7df8667df2

**Comment by matethurzo** [comment]
@brianchandotcom there is one more pull related to these set of tests, after we'll backport. thanks!

**Pull request closed without merging**
