### PR TITLE
COMMERCE-5268 added successful product image

### PR DESCRIPTION
**Pull request by garofalog**
Manual forward from:
https://github.com/liferay-commerce/liferay-portal/pull/427

### CODE REVIEW

**Comment by garofalog** [comment]
ci:test:sf

**Comment by garofalog** [comment]
ci:test:relevant

**Comment by garofalog** [comment]
ci:reopen

**Comment by garofalog** [comment]
ci:test:sf

**Comment by garofalog** [comment]
ci:test:relevant

**Comment by garofalog** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c0f527c7e7...58a1c6e79b

**Comment by brianchandotcom** [comment]
@garofalog 
I backported this to 7.3.x.

**Pull request closed without merging**
