### PR TITLE
Lps 62450

### PR DESCRIPTION
**Pull request by shuyangzhou**
@brianchandotcom please drop https://github.com/brianchandotcom/liferay-portal/commit/19cd7e348ae680e158c9a046bc8b41a7c30020da after you publishing the portal-kernel 1.0.4 release, that commit is only for CI.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@Preston-Crary @shuyangzhou it's too late for these types of changes..

portal.kernel is frozen now.

If you want to make this type of change, we need to make a new com.liferay.string.util that is in foundation and then you use it, like bnd-util.

I've released too many modules now, and if I were to bring this in, it'd take even longer to redo the whole process.

**Comment by shuyangzhou** [comment]
@brianchandotcom there will be a lot more changes like this as we resume the optimization process. As you know we have not really spent much time on this. If we won't be able make this type of global changes, most likely we won't be able to make enough progress on the optimization to bring it back to 6.2 level.

If we do create a new module, still we have to apply usages everywhere right? How is that different from changing kernel? And it will confuse people a lot as we will have 2 StringUtils.

CC @mhan810

**Comment by brianchandotcom** [comment]
The problem is that once this ships... we can't keep updating portal-kernel like that. Let's talk about this tomorrow....

**Comment by brianchandotcom** [comment]
@mhan810 I talked to @shuyangzhou 

I'm going to merge this in. We're going to release a new portal-kernel 2.0.0, going forward, we will enforce semantic versioning. Shuyang can change and add,but not remove.

**Comment by mhan810** [comment]
@brianchandotcom will call you later.  We have some others that we may have as well (just found out from search this morning)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d54eec8852...938776566d

**Pull request closed without merging**
