### PR TITLE
LPS-69491 Visibility

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by jpince** [comment]
@marcellustavares semver issue
```
     [exec] org.osgi.framework.BundleException: Could not resolve module: com.liferay.exportimport.resources.importer [273]
     [exec]   Unresolved requirement: Import-Package: com.liferay.journal.configuration; version="[1.0.0,2.0.0)"
     [exec]     -> Export-Package: com.liferay.journal.configuration; bundle-symbolic-name="com.liferay.journal.service"; bundle-version="4.0.0"; version="1.1.0"; uses:="aQute.bnd.annotation.metatype,com.liferay.portal.configuration.metatype.annotations,com.liferay.portal.kernel.configuration,com.liferay.portal.kernel.settings"
     [exec]        com.liferay.journal.service [351]
     [exec]          Unresolved requirement: Import-Package: com.liferay.dynamic.data.mapping.util.impl; version="[1.0.0,2.0.0)"
```
```
     [exec] 12:23:46,124 WARN  [fileinstall-/opt/dev/projects/github/liferay-portal/bundles/osgi/modules][org_apache_felix_fileinstall:103] Error while starting bundle: file:/opt/dev/projects/github/liferay-portal/bundles/osgi/modules/com.liferay.journal.service.jar 
     [exec] org.osgi.framework.BundleException: Could not resolve module: com.liferay.journal.service [351]
     [exec]   Unresolved requirement: Import-Package: com.liferay.dynamic.data.mapping.util.impl; version="[1.0.0,2.0.0)"
```

**Comment by marcellustavares** [comment]
thx @jpince, how did you find this log? :)

**Comment by jpince** [comment]
Click on the link next to the roman numeral, then "Console Output"

Not very intuitive right now, QA Engineering is working on transforming the backend that generates the github comment so they can have more options to make it more user-friendly in the future.

I'll send a gif to you in a separate email.

**Comment by marcellustavares** [comment]
thanks a lot @jpince 👍

**Pull request closed without merging**
