### PR TITLE
LPS-60980 Configuration

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchiu** [comment]
@brianchandotcom 
I'm starting to see that particular error (OrganizationsView) fairly often in the PR tester. I think that it's a portal bug, but is inconsistent. Out of several tries I was able to reproduce the issue manually once. I'm going to try a couple more things, and then I'll talk to someone on Shuyang's team.

**Comment by brianchandotcom** [comment]
ci:retest (@brianchiu, let @shuyangzhou know)

Thx

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5d1a585e68...b8d2f9e53f

**Pull request closed without merging**
