### PR TITLE
LPS-105712 Remove jquery usages

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
ci:reopen

**Comment by yichenroy** [comment]
ci:test:relevant 

Restarting test, build timed out due to high load:
`/opt/dev/projects/github/liferay-portal/build-test-batch.xml:3330: Parallel execution timed out
`

**Comment by brianchandotcom** [comment]
@inacionery see MetricResourceTest.testGetProcessMetric

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/495ffb521b...7d70f80df2

**Pull request closed without merging**
