### PR TITLE
LPS-64282 Move to correct package

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Test failure is unrelated...

**Comment by brianchandotcom** [comment]
@marcellustavares @brunobasto 

See modules/apps/foundation/portal-security-sso/portal-security-sso-ntlm/src/main/java/com/liferay/portal/security/sso/ntlm/internal/servlet/filter/NtlmPostFilter.java

I moved DDMDataProviderFilter.java too to servlet.filter.*

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c929529d77...7b5a090a75

**Comment by marcellustavares** [comment]
Thanks @brianchandotcom

**Pull request closed without merging**
