### PR TITLE
LPS-65336

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by gamerson** [comment]
@brianchandotcom I updated the package suffix on the controlmenuentry.  But the rest of the templates are so generic that its hard to make correct package suffixes.  However, as we get more specfic templates we can ensure they have sensible package suffixes.

**Comment by brianchandotcom** [comment]
Portlet should always go in *.portlet

We can do that one right? ci:stop

**Comment by gamerson** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
@gamerson I merged this.. can you send a follow up pull for other things like *Portlet. See how we patternize things very well in core for the package names. Thx!

**Comment by brianchandotcom** [comment]
@gamerson I'm also publishing a new gradle template for you right now.

**Pull request closed without merging**
