### PR TITLE
LPS-198393 Add currentDate in expression builder and notification general terms

### PR DESCRIPTION
**Pull request by murilostodolni**
Original PR: https://github.com/liferay-objects/liferay-portal/pull/2728

### CODE REVIEW

**Comment by murilostodolni** [comment]
ci:reopen

**Comment by carolmariaabb** [comment]
ci:close

**Comment by murilostodolni** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@murilostodolni 0 changes from me. Great job.

**Pull request closed without merging**
