### PR TITLE
LPS-98072 buildTagLib

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b0f66de72e...e4aba76ad8

**Comment by pyoo47** [comment]
ci:test:sf

**Pull request closed without merging**
