### PR TITLE
LPS-57585 git-commit-plugins

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:retest

**Comment by matethurzo** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6d685b35ff...a12431638b

**Comment by brianchandotcom** [comment]
@matethurzo I also had to update ServiceBuilder to fix @Override 

Please see upstream. Thx.

**Pull request closed without merging**
