### PR TITLE
LPS-69546 Folder Search Facet: extract code from JSP to reusable Display Contexts

### PR DESCRIPTION
**Pull request by arboliveira**
Re-sending to address https://github.com/brianchandotcom/liferay-portal/pull/45340#issuecomment-265539170.
Interface name is now `FolderTitleLookup`, no longer `FolderTitleFinder`.

Author: @linolaoj 
Reviewer: @arboliveira

https://issues.liferay.com/browse/LPS-69546

### CODE REVIEW

**Comment by arboliveira** [comment]
Unrelated test failures. Showing up in several pull requests: https://github.com/brianchandotcom/liferay-portal/pulls?utf8=%E2%9C%93&q=is%3Apr%20WikiAttachmentCreoleEditorConfigContributorTest

ci:reopen

**Comment by arboliveira** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:retest

**Comment by arboliveira** [comment]
Unrelated test failures. Showing up in several pull requests: https://github.com/brianchandotcom/liferay-portal/pulls?utf8=✓&q=DataSourceFactoryImplTest%20created%3A>%3D2016-12-01

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
