### PR TITLE
LPS-87590 Add Kazakh as a Community Language

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-87590](https://issues.liferay.com/browse/LPS-87590).<br><br>This should fix the SF error at https://github.com/brianchandotcom/liferay-portal/pull/65995#issuecomment-448027057<br><br>/cc @pei-jung @stsquared99 @alee8888 @ChrisKian

### CODE REVIEW

**Comment by drewbrokke** [comment]
cc @jpince

**Comment by brianchandotcom** [comment]
@drewbrokke I pushed it up after I ran SF locally too.

**Comment by drewbrokke** [comment]
Thanks @brianchandotcom. Looks like I even missed something with this pull.  I'm off today.

**Comment by jpince** [comment]
@drewbrokke hopefully this was the other thing you missed?
```
compile-common-jsp:
     [echo] Dec 17, 2018 11:02:54 PM org.apache.tomcat.util.digester.Digester endElement
     [echo] SEVERE: End event threw exception
     [echo] java.lang.reflect.InvocationTargetException
     [echo] 	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
     [echo] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [echo] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [echo] 	at org.apache.tomcat.util.IntrospectionUtils.callMethodN(IntrospectionUtils.java:391)
     [echo] 	at org.apache.tomcat.util.descriptor.web.CallMethodMultiRule.end(WebRuleSet.java:1045)
     [echo] 	at org.apache.tomcat.util.digester.Digester.endElement(Digester.java:944)
     [echo] 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
     [echo] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
     [echo] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
     [echo] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
     [echo] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
     [echo] 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
     [echo] 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
     [echo] 	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
     [echo] 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
     [echo] 	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
     [echo] 	at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1439)
     [echo] 	at org.apache.tomcat.util.descriptor.web.WebXmlParser.parseWebXml(WebXmlParser.java:119)
     [echo] 	at org.apache.tomcat.util.descriptor.web.WebXmlParser.parseWebXml(WebXmlParser.java:85)
     [echo] 	at org.apache.jasper.servlet.JspCServletContext.buildMergedWebXml(JspCServletContext.java:148)
     [echo] 	at org.apache.jasper.servlet.JspCServletContext.<init>(JspCServletContext.java:134)
     [echo] 	at org.apache.jasper.JspC.initServletContext(JspC.java:1604)
     [echo] 	at org.apache.jasper.JspC.execute(JspC.java:1438)
     [echo] 	at org.apache.jasper.JspC.main(JspC.java:286)
     [echo] Caused by: java.lang.IllegalArgumentException: The servlets named [I18n Servlet] and [I18n Servlet] are both mapped to the url-pattern [/kk/*] which is not permitted
     [echo] 	at org.apache.tomcat.util.descriptor.web.WebXml.addServletMappingDecoded(WebXml.java:329)
     [echo] 	at org.apache.tomcat.util.descriptor.web.WebXml.addServletMapping(WebXml.java:322)
     [echo] 	... 24 more
     [echo] 
     [echo] Dec 17, 2018 11:02:54 PM org.apache.tomcat.util.descriptor.web.WebXmlParser parseWebXml
     [echo] SEVERE: Parse error in application web.xml file at [file:/opt/dev/projects/github/liferay-portal/portal-web/docroot/WEB-INF/web.xml]
     [echo] org.xml.sax.SAXParseException; systemId: file:/opt/dev/projects/github/liferay-portal/portal-web/docroot/WEB-INF/web.xml; lineNumber: 655; columnNumber: 20; Error at (655, 20) : The servlets named [I18n Servlet] and [I18n Servlet] are both mapped to the url-pattern [/kk/*] which is not permitted
     [echo] 	at org.apache.tomcat.util.digester.Digester.createSAXException(Digester.java:1862)
     [echo] 	at org.apache.tomcat.util.digester.Digester.createSAXException(Digester.java:1894)
     [echo] 	at org.apache.tomcat.util.digester.Digester.endElement(Digester.java:947)
     [echo] 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
     [echo] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
     [echo] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
     [echo] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
     [echo] 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
     [echo] 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
     [echo] 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
     [echo] 	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
     [echo] 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
     [echo] 	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
     [echo] 	at org.apache.tomcat.util.digester.Digester.parse(Digester.java:1439)
     [echo] 	at org.apache.tomcat.util.descriptor.web.WebXmlParser.parseWebXml(WebXmlParser.java:119)
     [echo] 	at org.apache.tomcat.util.descriptor.web.WebXmlParser.parseWebXml(WebXmlParser.java:85)
     [echo] 	at org.apache.jasper.servlet.JspCServletContext.buildMergedWebXml(JspCServletContext.java:148)
     [echo] 	at org.apache.jasper.servlet.JspCServletContext.<init>(JspCServletContext.java:134)
     [echo] 	at org.apache.jasper.JspC.initServletContext(JspC.java:1604)
     [echo] 	at org.apache.jasper.JspC.execute(JspC.java:1438)
     [echo] 	at org.apache.jasper.JspC.main(JspC.java:286)
     [echo] Caused by: java.lang.IllegalArgumentException: The servlets named [I18n Servlet] and [I18n Servlet] are both mapped to the url-pattern [/kk/*] which is not permitted
     [echo] 	at org.apache.tomcat.util.descriptor.web.WebXml.addServletMappingDecoded(WebXml.java:329)
     [echo] 	at org.apache.tomcat.util.descriptor.web.WebXml.addServletMapping(WebXml.java:322)
     [echo] 	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
     [echo] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [echo] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [echo] 	at org.apache.tomcat.util.IntrospectionUtils.callMethodN(IntrospectionUtils.java:391)
     [echo] 	at org.apache.tomcat.util.descriptor.web.CallMethodMultiRule.end(WebRuleSet.java:1045)
     [echo] 	at org.apache.tomcat.util.digester.Digester.endElement(Digester.java:944)
     [echo] 	... 18 more
```

**Comment by jpince** [comment]
@drewbrokke nevermind, looks like CI rebased your change on top of Brian's (so it had kk/* twice in that file)

**Pull request closed without merging**
