### PR TITLE
LPS-102645 Adds .lfrbuild-portal marker to deploy the module automatically

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by wincent** [comment]
Thanks @jbalsas.

**Comment by sandrodw3** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchandotcom** [comment]
Please resend, stable errors.

**Comment by brianchandotcom** [comment]
@wincent @sandrodw3 fyi

**Comment by wincent** [comment]
Those look unrelated to me so I'm going to rebase and see if we get a clean run on that.

**Pull request closed without merging**
