### PR TITLE
LPS-91627 license

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d6b2652888...252b4603d3

**Comment by brianchandotcom** [comment]
@nhpatt hmm.. this doesn't make sense, our customers wouldn't be Apache... we need to make this configurable. Can you make it so the info is grabbed from rest-config.yaml? Not merged, please resend. Thx.

**Comment by brianchandotcom** [comment]
@nhpatt also, for our implementation, don't give it a default. If the license is set (and in our case, we'll set it to LGPL etc) then it'll use that info and shove it in the generated license. For customers, they probably won't set it since it's all internal.

**Comment by nhpatt** [comment]
@brianchandotcom sorry, I forgot to mention that I discussed this with Matija Šuklje and it's the license for the OpenAPI.yaml file, not the code. But it's true that customers may want to change the license, I'll make if configurable. But for us, should be Apache 2.0, that's the license Matija prefers for this (and it's the most common). Code would be LGPL.

**Pull request closed without merging**
