### PR TITLE
Lps 69809

### PR DESCRIPTION
**Pull request by shuyangzhou**
@dantewang @slnn performance check please.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@shuyangzhou can you resend this? They lose the ability to customize the JSP now.

Can you ensure that if they put in the file of "end.jsp" that it will pick that up? Is this an optimization that loses some extensibility? Please resend. Thx.

**Comment by brianchandotcom** [comment]
I'll merge this one in.

**Comment by brianchandotcom** [comment]
Merged.

**Pull request closed without merging**
