### PR TITLE
LPS-93440 Using the new instance settings for microsoft cognitive services auto tagger

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:reopen

Failures related to workflow.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8b17e400b3...d8f5123e04

**Comment by brianchandotcom** [comment]
Very very nice.

**Comment by brianchandotcom** [comment]
This caused a compileJSP error I fixed it in f02ad11

Search team caught it because their CI was working https://search-ci.liferay.com/job/integration/654/console

**Comment by 4lejandrito** [comment]
Sorry! 

If only `gw deploy` were the same as `gw compileJsp deploy`... 

From now on `alias deploy="gw compileJsp deploy"`.

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/70951#issuecomment-480389129.

**Pull request closed without merging**
