### PR TITLE
LPS-105204 Add tooltip lang keys

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@petershin I've gotten this a lot

```
ProjectTemplatesTest.testCompareGradlePluginVersions
org.junit.ComparisonFailure: com.liferay.plugin versions do not match expected:<4.4.[86]> but was:<4.4.[91]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at
```

Can you take a look? Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e22b1ea033...4bb4d7e4f8

**Comment by petershin** [comment]
@lawrence-lee will send a patch

**Comment by petershin** [comment]
@brianchandotcom - Jason Pince is looking into whether QA can send an email to notify Lawrence of this type of failure automatically in the future

**Pull request closed without merging**
