### PR TITLE
LPS-69996 Fields should be volatile to ensure memory visibility.

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
cc @tinatian

**Comment by tinatian** [comment]
cc @shuyangzhou

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@tinatian please backport. Thx.

**Comment by brianchandotcom** [comment]
@tinatian @4lejandrito not merging. @shuyangzhou told me to revert.

**Pull request closed without merging**
