### PR TITLE
LPS-73481 Set 7.1.0 in master

### PR DESCRIPTION
**Pull request by achaparro**
It depends on:
https://github.com/brianchandotcom/liferay-plugins/pull/5404
https://github.com/brianchandotcom/liferay-portal-ee/pull/18287

### CODE REVIEW

**Comment by achaparro** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:close

**Comment by jpince** [comment]
investigating this error: `You must first upgrade to Liferay Portal 7100`

**Comment by achaparro** [comment]
Hi @jpince,

It seems that you are using an already created database for the tests, could it be? You would need to upgrade it with the db upgade client first.

Thanks.

@brianchandotcom

**Comment by achaparro** [comment]
My fault, see this:
https://github.com/brianchandotcom/liferay-portal/pull/51561

Thanks!

**Pull request closed without merging**
