### PR TITLE
LPS-65685

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by vicnate5** [comment]
@hhuijser @brianchandotcom The Calendar portlet is missing on this pull

**Comment by vicnate5** [comment]
after0

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d638b4db66...ee5ce29e61

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by vicnate5** [comment]
Same issue on retest. The Calendar portlet is not listed under the list of Applications to add to a page.

**Comment by brianchandotcom** [comment]
@hhuijser this causes real calendar issues.. please resend.

**Pull request closed without merging**
