### PR TITLE
LPS-155911 Move ScriptData implementation to OSGi land

### PR DESCRIPTION
**Pull request by izaera**
This is a resend of [#122939](https://github.com/brianchandotcom/liferay-portal/pull/122939)

----

Replies to some parts of review [#122939 (comment) ](https://github.com/brianchandotcom/liferay-portal/pull/122939#issuecomment-1243591252) follow:

>    1.) Is this file purposefully ugly?
>
>    modules/apps/frontend-taglib/frontend-taglib/src/test/resources/com/liferay/frontend/taglib/servlet/taglib/dependencies/component_tag.html
>
>    To test compression?

That file is the output of our infrastructure. It usually goes inside the HTML we send to the browser, that's why it is minified so much. We keep some line feeds when dumping the output so that it can be debugged more easily in the browser if anything happens, but we minimize formatting as much as possible to save bandwidth and space.

----

>    The JSP/JS changes like ... are they required?

Yes. They are part of this LPS as most of the refactors in the PR because if we don't change them, we introduce bugs due to the semantics of JS modules vs the old JS scripts. So, I'm keeping the same LPS number for them.

### CODE REVIEW

**Comment by izaera** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/97f6bb30a4...4778aaf633

**Comment by brianchandotcom** [comment]
@izaera I merged this to master.

1.) Can you sort the constructors for AMDRequire and ESImport

2.) Can you review my renames of "variables" vs. "aliases"? I'm not sure if it's right. Thx.

**Comment by izaera** [comment]
> 2.) Can you review my renames of "variables" vs. "aliases"? I'm not sure if it's right. Thx.

@brianchandotcom An alias is a variable so I think you can use `alias` or `variable` interchangeably in the part of the code you changed. I think your refactor is OK because, IINM, we tend to maintain the original designation of things. So, `String alias = amdRequire.getAlias();` is an alias even if it can be used as a variable later. :+1:

**Comment by izaera** [comment]
OK, I see what happened. I used `variable` because we rely on `VariableUtil` to generate aliases. But we refer to `alias` all throughout the code (`AMDRequire`) so everything is `alias`, not `variable`, as you said :+1:

**Pull request closed without merging**
