### PR TITLE
LPS-86144 baseline

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by jpince** [comment]
@kyle-miho @brianchiu failure in `Search#SearchGlobalTemplateSmoke` looks like it might be related?

**Comment by kyle-miho** [comment]
looking

**Comment by kyle-miho** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/069aa30c5a...781411193b

**Comment by kyle-miho** [comment]
@jpince couldn't reproduce this locally, likely something intermittent in ci

**Comment by brianchiu** [comment]
@jpince @kyle-miho 
This is the issue where the search global template does not show up.
https://issues.liferay.com/browse/LPS-87886

I thought we had taken care of it. We should keep an eye to see if it happens again.

cc @jkappler

**Pull request closed without merging**
