### PR TITLE
LPS-62982 Regenerate

### PR DESCRIPTION
**Pull request by epgarcia**
@ealonso
@juliocamarero

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:retest

**Comment by sharonchoi** [comment]
@evannagayama potential poshi error with ADT templates

**Comment by brianwulbern** [comment]
@sharonchoi working on the ADT fixes here: https://issues.liferay.com/browse/LRQA-23647

**Comment by brianchandotcom** [comment]
Rebase error, please resend. Thx.

**Pull request closed without merging**
