### PR TITLE
LPS-71624 It's probably better to return VARCHAR rather than null here if "String" is passed in

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by mbowerman** [comment]
@brianchandotcom Is it important that the companyId remains first in the mapping table? Or could I just rerun the service builder and resubmit?

**Comment by rotty3000** [comment]
@mbowerman the problem here is probably that you used a HashMap which lost the ordering of the fields. You maybe should change it for a `LinkedHashMap`. Can you send an updated PR with this change and let's see if the tests pass.

**Comment by mbowerman** [comment]
@rotty3000 OK sounds good, I will send you an updated pull.

**Comment by mbowerman** [comment]
@rotty3000 Please see https://github.com/rotty3000/liferay-portal/pull/1296. Thanks!

**Pull request closed without merging**
