### PR TITLE
LPS-63970 remove portlet key not used anymore

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c6bbf03280...9c992f4ad0

**Comment by brianchandotcom** [comment]
@juliocamarero fixed 404 9c992f4ad01bc48d28cc9adf5cbca05e433bd244

**Comment by juliocamarero** [comment]
Thank you Brian!

**Pull request closed without merging**
