### PR TITLE
[TECHNICAL-SUPPORT] LPS-87050

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Reviewed by @topolik here - https://github.com/topolik/liferay-portal/pull/657

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@jonathanmccann see 8d352e0bf0de8f50d64933cc2b253040c160b235 for backwards compatibility (imagine if people forked our JSP or custom GS code that mimicked our code).

**Comment by brianchandotcom** [comment]
@jonathanmccann one more change in 7a88646 to have less code.

**Pull request closed without merging**
