### PR TITLE
LPS-99174 Remove configuration, css, html and js paths from fragment.json for recently added fragments

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
//cc @ealonso <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ruben-pulido** [comment]
//cc @jkappler <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4811a6d51b...5e9115d248

**Comment by brianchandotcom** [comment]
@jkappler @ruben-pulido see 5e9115d248fcf26f8ac242504c9bcfe9da24ab2c

I like this refactor. Good job.

**Pull request closed without merging**
