### PR TITLE
LPS-73084 Added separation between scripts in display_settings

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by pyoo47** [comment]
ci:retest (Slave ran out of disk space)

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@ealonso don't we need to namespace this?

<div id="languageWarning"></div>

Or at least prefix it with something Liferay specific? Out in the wild, someone may already be using that id.

Thx.

**Comment by brianchandotcom** [comment]
Please resend @ealonso thx

**Pull request closed without merging**
