### PR TITLE
LPS-64681 Consolidate unzip-weblogic-original into unzip-weblogic

### PR DESCRIPTION
**Pull request by alee8888**

### CODE REVIEW

**Comment by alee8888** [comment]
@brianchandotcom 
The reason I consolidated unzip-weblogic-original into unzip-weblogic and removed the custom zip logic into unzip-weblogic-custom is for two reasons:

1. QA test engineers who run the Weblogic build scripts will actually download the custom zip file and their build will fail because the custom zip files paths are set to the CI slave.
2. Since unzip-weblogic-custom is only used for CI, it made sense to just have all the custom logic there. That way, prepare-test-bundle can just call unzip-weblogic-custom.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b55d27328a...f902634746

**Comment by brianchandotcom** [comment]
@alee8888 your pull ticket doesn't match your commit ticket again. fyi.

**Comment by alee8888** [comment]
@brianchandotcom 
I apologize Brian, there really is no excuse on something this simple. I will make sure this will not happen again. Thank you again for catching this.

**Pull request closed without merging**
