### PR TITLE
LPD-22383 Use ConfigurationTestUtil instead of ConfigurationProvider to avoid intermittent fails

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a5acbeac1f...a8a644a073

**Comment by brianchandotcom** [comment]
@MarinhoFeliphe see a8a644a073582aa062dea6a2d2e99a3514e4bc48

**Comment by MarinhoFeliphe** [comment]
@brianchandotcom I believe it was incremented automatically

**Pull request closed without merging**
