### PR TITLE
LPS-94602 Use original/actual naming convention

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:close

**Comment by jkappler** [comment]
ci:reopen

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/810fe670a6...6cd828bbaf

**Comment by brianchandotcom** [comment]
@jkappler @kyle-miho See 6cd828bbafa7d3a4021be81e0927d32bc029ca03

**Pull request closed without merging**
