### PR TITLE
LPD-18252: Allow using the keyword type subfield of nested DDM fields in the Custom Facet widget

### PR DESCRIPTION
**Pull request by peerkar**
https://liferay.atlassian.net/browse/LPD-18252

### CODE REVIEW

**Comment by peerkar** [comment]
ci:reopen

**Comment by lipusz** [comment]
@peerkar Shouldn't we need to make the same change to /search and the Sort and Custom Filter widgets, too?

**Comment by lipusz** [comment]
So basically everywhere we have the same nested field handling logic.

**Comment by lipusz** [comment]
Also, what about the same in Objects entries (`nestedFieldArray`)?

**Comment by brianchandotcom** [comment]
@peerkar integration test?

**Comment by peerkar** [comment]
@lipusz:
- Sort Widget: the ICU collation is exactly for sorting. What would be the use case of using the subfield?
- Custom Filter Widget: This syntax is anyways not allowed there -> no impact
- Objects: Not sure if Objects index like that. Quick test: no

**Comment by peerkar** [comment]
@brianchandotcom : I didn't see it necessary for this explicit addition because it doesn't in my opinion really change anything in regard to coverage of the existing tests which are at the connector level anyways. But, I'll add a send a follow up with a scenario for this.

**Pull request merged**
