### PR TITLE
LPS-74544

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@shuyangzhou, can you have a look at the ones that I excluded: https://github.com/brianchandotcom/liferay-portal/pull/54578/commits/d4500d146eb4083901d9bc4f14669dce1f4bab46

I am too scared to touch your code :)

**Comment by hhuijser** [comment]
ci:test

**Comment by shuyangzhou** [comment]
@hhuijser the one in ObjectGraphUtilTest has to be excluded. The other 3 are ok to add the static, thanks!

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
