### PR TITLE
Upgrade Process: concurrent execution for portlet preference upgrades

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by migue** [comment]
ci:retest

**Comment by sharonchoi** [comment]
@brianchiu upgrade test failures due to https://issues.liferay.com/browse/LPS-64526
@kenjiheigel portal smoke failings due to https://issues.liferay.com/browse/LPS-64500

**Comment by brianchandotcom** [comment]
Rebase error, please resend. Thx.

**Pull request closed without merging**
