### PR TITLE
LPS-110752 Create new openModal utility and apply it to segments-web

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @brianchandotcom, sending this directly after several days struggling to see green in tests. Everytime we quarantine one, another 3 fail...

This PR:
- Creates a new `openModal` utility to update Modal patterns in DXP
- It applies it only to one place in `segments-web` module (so only tests there or in `frontend-js-web` should be suspects...)

See analysis [here](https://github.com/wincent/liferay-portal/pull/190)

Could you please push this directly? That's what @manoelcyreno suggested.

/cc @john-co, @manoelcyreno, @dgarciasarai, @markocikos, @wincent

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:reopen

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
Ok, I guess the bot won't even let me run the tests on it.

**Comment by wincent** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ff259322e0...fcac68220e

**Pull request closed without merging**
