### PR TITLE
LRQA-28491 & LRQA-28597 Fix ClassCastException in Build model & Reinvocation issues.

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-28491
https://issues.liferay.com/browse/LRQA-28597

Please publish a new com.liferay.jenkins.results.parser.jar after merging.

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/bf42da43d9...deec4d5979

**Comment by brianchandotcom** [comment]
@pyoo47 see d8c691bbd96b5ff824c559a5aa9214887b0be61b

**Pull request closed without merging**
