### PR TITLE
LPS-59223 SF

### PR DESCRIPTION
**Pull request by izaera**
/CC @sergiogonzalez

### CODE REVIEW

**Comment by izaera** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/dca8303cfa...bf33598614

**Comment by brianchandotcom** [comment]
@izaera @sergiogonzalez please see my changes in https://github.com/brianchandotcom/liferay-portal/pull/31459

**Comment by brianchandotcom** [comment]
@izaera can you double check my work as well? Thx.

**Comment by izaera** [comment]
:+1:

**Pull request closed without merging**
