### PR TITLE
LPS-77659 Rename to isShow

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/58c6558a47...7411b4bb33

**Comment by brianchandotcom** [comment]
@pavel-savinov @ealonso see 7411b4b thx

**Pull request closed without merging**
