### PR TITLE
Fix Data Migrator

### PR DESCRIPTION
**Pull request by cgoncas**
/cc @migue

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by evannagayama** [comment]
@cgoncas @brianchandotcom seems like a random error unrelated to the pr: https://issues.liferay.com/browse/LPS-65961

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:stop

**Comment by cgoncas** [comment]
ci:retest

**Comment by cgoncas** [comment]
ci:retest

**Comment by jpince** [comment]
@brianchandotcom poshi failures due to sybase errors that we are looking into, and an unrelated jenkins failure. Good from a functional test perspective.

**Comment by cgoncas** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@cgoncas I didn't merge this because of the changes to mail-portlet (it's no longer in the deprecated folder) and it was weird that we're checking in the portal-impl jar files. It should use reflection instead to fetch the running ones?

Can we also break this up into smaller pulls? Imagine if we had to do this once all the repos are split... how would we execute this change then?

Thx.

**Pull request closed without merging**
