### PR TITLE
LPS-75377 As a System Administrator I can browse the available system settings following a semantic organization that facilitates finding configurations by browsing

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LPS-75377

Ran acceptance tests in https://github.com/xbrianlee/liferay-portal/pull/184

### CODE REVIEW

**Comment by xbrianlee** [comment]
@anthony-chu @austinchiang @vicnate5 @alee8888
This PR for the System Settings redesign affects tests from all your components. We've tried to mitigate all acceptance and non-acceptance test failures.

**Comment by JorgeFerrer** [comment]
Hey @anthony-chu @austinchiang @vicnate5 @alee8888, 
If this is affecting some tests we might want to evaluate whether those tests are testing something that's already being tested. I don't think that each portlet should tests its own System Settings configuration since it's the same for all. If what the test is doing is changing some configuration in preparation for the real test I think we should find a way to do that preparation under the hood, instead of through the UI. That will be faster and easier to maintain.

Let me know if I can help with this. I will be in LA since Wednesday.

**Comment by vicnate5** [comment]
Because the System Settings UI uses input fields from Forms, the Forms team has a test that does configuration only to check the UI behavior (`Forms#EditAllFormFieldsTypesUsedBySystemSettings`). I agree that we generally should not test the configuration values by using the UI.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d61d2c54b7...8f1da11b9e

**Comment by brianchandotcom** [comment]
@JorgeFerrer @pei-jung can you rename:

CategoryMVCRenderCommand.java to VerbCategoryMVCRenderCommand.java. If you look at all other classes in that package, they all start with a verb, in fact, almost all *MVCRenderCommands start with a verb).

Thanks.

**Comment by JorgeFerrer** [comment]
Yup, I'll take of it

**Pull request closed without merging**
