### PR TITLE
Lps 100565

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a3b524a0ff...d951a819f3

**Comment by brianchandotcom** [comment]
@shuyangzhou can you send me a backport for 7.1.x and 7.0.x?

@preston-crary does this mean your pull for ServiceBuilder useFinderCache can go back in? If so, please send me a follow up pull.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal-ee/pull/26325 and https://github.com/brianchandotcom/liferay-portal-ee/pull/26326

**Comment by Preston-Crary** [comment]
@brianchandotcom not yet.  There's still another bug like this one that we will need to understand and fix before we can remove the useFinderCache arg.

**Pull request closed without merging**
