### PR TITLE
LPS-68921

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:reopen

**Comment by Ithildir** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@Ithildir I know what this is .. on it.

**Comment by brianchandotcom** [comment]
@Ithildir it was the transaction manager from @shuyangzhou

@shuyangzhou can you send a fix?

**Comment by shuyangzhou** [comment]
@brianchandotcom the failure is from copied ee private module, have you synced with the ee pull I sent?

**Pull request closed without merging**
