### PR TITLE
LPS-166701 Uses is Dialog instead of a custom jsp

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-166701

@ealonso

### CODE REVIEW

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/10065

:x: ci:test:stable - 27 out of 28 jobs passed
:x: ci:test:relevant - 602 out of 640 jobs passed in 2 hours 32 minutes

**Comment by ozysouza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/db3167fa0e...233f41f9a5

**Comment by brianchandotcom** [comment]
@ealonso just 233f41f9a52e795eaf1b425aec61a6e5d9ec7b94

we have this pattern already

git grep "Buffer\"" **.jsp**

**Pull request closed without merging**
