### PR TITLE
Lps 69987

### PR DESCRIPTION
**Pull request by shuyangzhou**
Resend of https://github.com/brianchandotcom/liferay-portal/pull/45959

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/73de448cb9...c7bfb7fc84

**Comment by brianchandotcom** [comment]
@shuyangzhou please backport. thx.

**Comment by shuyangzhou** [comment]
@tomwang2011 backport please

**Pull request closed without merging**
