### PR TITLE
LPS-95442 Fix compileTestIntegration

### PR DESCRIPTION
**Pull request by petershin**
Hi Brian, these changes fix the `compileTestIntegrationJava` task. It creates the `test-classes` directory.

Sent pulls to backport the fix to 7.2.x and 7.1.x

https://github.com/brianchandotcom/liferay-portal-ee/pull/24507
https://github.com/brianchandotcom/liferay-portal-ee/pull/24508

@rotty3000 @shuyangzhou @jpince

### CODE REVIEW

**Comment by jpince** [comment]
cc/ @vicnate5

**Comment by brianchandotcom** [comment]
Thank you @rotty3000 !

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/02f243e528...ca2165c3bc

**Pull request closed without merging**
