### PR TITLE
LPS-161531 LPS-176755 [BE] Support language keys in label and helpText

### PR DESCRIPTION
**Pull request by thektan**
**Story:** https://issues.liferay.com/browse/LPS-161531
**Subtask:** https://issues.liferay.com/browse/LPS-176755, https://issues.liferay.com/browse/LPS-176756
**Test Fix:** https://issues.liferay.com/browse/LPS-179631

Follow-up from https://github.com/brianchandotcom/liferay-portal/pull/132520#issuecomment-1487751795:
- Fixed `A geopoint field.` -> `Enter a geopoint field.`.

### CODE REVIEW

**Comment by thektan** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c24ebcb347...7a8f3a8458

**Comment by brianchandotcom** [comment]
@peerkar @thektan see 47b2fc9af7f7f0cd5f5dbcc431f4bd6f80a2f4ed

Do we need an upgrade?

**Comment by thektan** [comment]
@brianchandotcom Existing blueprint and elements will still work as-is but we do have an upgrade process in the works to change out-of-the-box element labels and help text into language keys so they will get localized. https://issues.liferay.com/browse/LPS-176884

**Pull request closed without merging**
