### PR TITLE
LPS-111832 Improve error logs

### PR DESCRIPTION
**Pull request by rodrigocunhaa**

### CODE REVIEW

**Comment by rodrigocunhaa** [comment]
Forwarded from https://github.com/inacionery/liferay-portal/pull/655. All the related tests passed. The not unique failing test is from Search team (https://issues.liferay.com/browse/LPS-113354).

cc: @xbrianlee

**Comment by rodrigocunhaa** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4716cb79f4...6148a5caf8

**Pull request closed without merging**
