### PR TITLE
Lps 74272

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8b47bfa6d9...1ca97b32ff

**Comment by brianchandotcom** [comment]
@dacousalr @Preston-Crary this should have been a new LPS because LPS-74272 is already backported to 7.0.x. In any case, it cherry picked cleanly so I did it right away. Otherwise, it'd be hard to keep track of.

**Comment by jpince** [comment]
@petershin @hhuijser the changes passed in the previous pull 5 days ago [#5552](https://github.com/shuyangzhou/liferay-portal/pull/5552) but are failing at head (see below). Was this due to a change in SF?
```
     [java] Use import statement instead of Fully Qualified Name for 'com.liferay.portal.kernel.util.PropsKeys: ./portal-impl/test/integration/com/liferay/portal/util/PortalImplAlternateURLTest.java 75
     [java] Use import statement instead of Fully Qualified Name for 'com.liferay.portal.kernel.util.PropsKeys: ./portal-impl/test/integration/com/liferay/portal/util/PortalImplAlternateURLTest.java 246
     [java] Use import statement instead of Fully Qualified Name for 'com.liferay.portal.kernel.util.PropsKeys: ./portal-impl/test/integration/com/liferay/portal/util/PortalImplCanonicalURLTest.java 82
     [java] Use import statement instead of Fully Qualified Name for 'com.liferay.portal.kernel.util.PropsKeys: ./portal-impl/test/integration/com/liferay/portal/util/PortalImplCanonicalURLTest.java 475
```
[SF Console Log](https://test-1-5.liferay.com/job/test-portal-acceptance-upstream-batch(master)/AXIS_VARIABLE=0,label_exp=!master/16757/console) - from latest upstream acceptance run

**Comment by petershin** [comment]
@jpince - Yup.  Sent a fix to Brian: https://github.com/brianchandotcom/liferay-portal/pull/54394

**Comment by hhuijser** [comment]
@jpince, those files were committed 5 days ago, but only pushed upstream earlier today...

**Pull request closed without merging**
