### PR TITLE
LPS-169003 Migrate Staging tree to new ClayTreeView component

### PR DESCRIPTION
**Pull request by vendeltoreki**
* Forwarding: https://github.com/liferay-staging/liferay-portal/pull/201
* No regressions found by QA: https://github.com/liferay-staging/liferay-portal/pull/201#issuecomment-1363645022
* Rebased, conflict with https://github.com/liferay/liferay-portal/commit/b43bbb8bf92c47cb8c80602e2b9e9e4e6dea5099 resolved in https://github.com/brianchandotcom/liferay-portal/commit/3e9e377db66d9991b880ef80fb7d4ba8e148530a

cc: @sandrodw3 , @JoyceWang08211

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
"RETURN_LAYOUTS_AS_ARRAY" in 

```
		_httpServletRequest.setAttribute(
			"RETURN_LAYOUTS_AS_ARRAY", Boolean.TRUE);
```

Can we use constants?

@sandrodw3 @vendeltoreki @ealonso please resend. Thx.

**Comment by brianchandotcom** [comment]
See ProductNavigationProductMenuWebKeys.java which has the constant defined already fyi

@vendeltoreki @ealonso @sandrodw3

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5cfb3f0528...f5c9b80086

**Comment by brianchandotcom** [comment]
Just f5c9b800860a48754660b4c06e47091345543bb8 

I merged this after talking to @ealonso 

@vendeltoreki @sandrodw3 fyi

**Pull request closed without merging**
