### PR TITLE
LPS-108462 Change structure of the generated zip file, so that it takes into account frament collection/entry keys

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
//cc @ealonso

**Comment by ruben-pulido** [comment]
//cc @jkappler

**Comment by ruben-pulido** [comment]
//cc @ealonso

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f1979891ba...886f3048fe

**Pull request closed without merging**
