### PR TITLE
Breaking changes

### PR DESCRIPTION
**Pull request by jhinkey**
/cc @codyhoag

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a238a9abae...0705905e64

**Comment by brianchandotcom** [comment]
@brianchiu tests unstable?

**Comment by brianchiu** [comment]
Hrm... this error is weird. The screenshot shows that there are things missing portal (the details tab). The test was trying to click on the details tab to modify the user display settings from editing a user.

after2

**Comment by brianchandotcom** [comment]
Can you ask @shuyangzhou

I have a feeling some OSGi module didn't load.

**Comment by brianchiu** [comment]
Yea. I'll ask @shuyangzhou

**Comment by shuyangzhou** [comment]
This is actually a frontend bug,when we click the Test user link, browser sends out 2 requests to server, creating an unnecessary race condition for creating the same AnnouncementsDelivery entry, therefore violating the DB unique index.

I will try to find a frontend developer to take over this issue.

**Comment by brianchiu** [comment]
To give more context to whoever works on this, I've uploaded videos to this ticket of the exact steps the test was taking. https://issues.liferay.com/browse/LRQA-19231

The Test user link from Shuyang's comment is from clicking the Test user link in Users and Organizations to edit the Test Test user.

**Pull request closed without merging**
