### PR TITLE
master-qa-13415

### PR DESCRIPTION
**Pull request by michaelhashimoto**
http://issues.liferay.com/browse/LIFERAYQA-13415

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Hashi, do we still need b62334c289ce6d653e1f4c9c7ca75cf03bd6fdac ?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/63f2714c73...a14cf24dd1

**Comment by michaelhashimoto** [comment]
@brianchandotcom - yeah. i'd still need to make some edits before we can remove that change. I can remove it when it's ready.

Thanks!

**Pull request closed without merging**
