### PR TITLE
LPS-64021 "apps"

### PR DESCRIPTION
**Pull request by Ithildir**
Hi!
Please let this pull finish, I'm running more or less the same one on another branch and it seems things are working now... but I want to be absolutely sure! :sweat_smile: 

Can you also please publish a new `source-formatter`? cc @hhuijser

Thank you!

### CODE REVIEW

**Comment by sharonchoi** [comment]
@brianchiu

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
@Ithildir 
Just checking into this. The old versions of Liferay have the sign in portlet on the welcome page so the test typed into the wrong one. I'm pretty sure this is a test update and not a problem with your pull.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/40d0599896...0fcabca29c

**Pull request closed without merging**
