### PR TITLE
LPS-178924 Not needed

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@seltong @MarinhoFeliphe 

1.) I see _evaluateParentObjectAuthor, but I don't see what an "Object" is. Is it an ObjectDefinition or an ObjectField?

I also don't see a getParentObjectDefiinitionId() or getParentObjectFieldId(), so I don't know what Parent means either.

2.) Rename _matchesAuthorTermName to _isAuthorTermName

3.) Avoid

User user = GuestOrUserUtil.getGuestOrUser();

user.getLocale()

Instead, do

ThemeDisplay themeDisplay = // grab it from the resourceRequest

themeDisplay.getLocale()

Thx

**Comment by brianchandotcom** [comment]
ci:reopen previous PR comment was from the wrong PR, but I do need help with the tests here as well.

**Comment by seltong** [comment]
ci:close

**Pull request closed without merging**
