### PR TITLE
LPS-54269 avoid wrapping exceptions needlessly

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
@Preston-Crary @sergiogonzalez would be a good time to start extracting store impls.

**Comment by brianchandotcom** [comment]
@Preston-Crary 

I don't want to go down that route because things used to be that way. We'd have very very long exception signatures like

throws XyzException, AbcException, etc etc.

Since then, we've truncated everything to just Portal or SystemException.

**Comment by JorgeFerrer** [comment]
Hey Brian,

If there are very long exception signatures then that means that the exceptions didn't have the right hierarchy or the method was trying to do too much.

Returning PortalException just hides the problem and makes the API harder to use since it doesn't have any semantics. We are suffering already quite a bit from that pattern which hides a lot of useful information so I fully support Preston's efforts to move away from that pattern. 

Thoughts?

**Comment by Preston-Crary** [comment]
@brianchandotcom @JorgeFerrer 

Should I resend this without the interface changes then? I could leave the implementations throwing the specific exceptions or change them back to PortalException.

The main things I think we should keep are the changes to the S3Store (before it wasn't throwing NoSuchFileExceptions when it should have) and removing exceptions from delete and hasFile methods.

**Comment by Preston-Crary** [comment]
https://github.com/JorgeFerrer/liferay-portal/pull/519

**Pull request closed without merging**
