### PR TITLE
Lps 65385 modules

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@shuyangzhou still has 12 test failures :(

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/01b2678957...8bad8cb6d6

**Comment by shuyangzhou** [comment]
@brianchandotcom I am outside now, won't be back until night. I will take care od them tonight.

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/39830, that should fix it.

**Pull request closed without merging**
