### PR TITLE
LRDOCS-1674 Fix jsp precompile error

### PR DESCRIPTION
**Pull request by kenjiheigel**
This will fix a jsp precompile error on jonas

### CODE REVIEW

**Comment by kenjiheigel** [comment]
cc-ing: @mwilliams2014, @jhinkey

**Comment by mwilliams2014** [comment]
Thanks Kenji. Sorry about that. I'm not sure how it got through.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/eb58f1f01f...bb4bfafe24

**Comment by kenjiheigel** [comment]
No worries Michael!

**Pull request closed without merging**
