### PR TITLE
COMMERCE-471

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0a0cd24a56...14490e9e48

**Comment by brianchandotcom** [comment]
@ZoltanTakacs please see my changes in upstream. Can you also rename these:

```
	public Property<Boolean> anonymousLogin = PropertyFactory.newBoolean(
		"anonymousLogin");
	public Property<Integer> connectTimeout = PropertyFactory.newInteger(
		"connectTimeout", _CONNECT_TIMEOUT);
	public Property<String> endpoint = PropertyFactory.newString("endpoint");
	public Property<Boolean> followRedirects = PropertyFactory.newBoolean(
		"followRedirects");
	public Property<Boolean> forceHttps = PropertyFactory.newBoolean(
		"forceHttps");
	public Property<Integer> itemsPerPage = PropertyFactory.newInteger(
		"itemsPerPage", _ITEMS_PER_PAGE);
	public Property<LoginType> loginType = PropertyFactory.newEnum(
		"loginType", LoginType.class).setRequired();
	public Property<String> name = PropertyFactory.newString(
		"name").setRequired();
	public Property<String> password =
```

All Property should be *Property

Please send me a follow up pull directly.

Thx.

@Ithildir fyi

**Comment by Ithildir** [comment]
Hi @brianchandotcom,
I wasn't sure about those, in case Talend uses reflection to get the field names 🤔

**Comment by ZoltanTakacs** [comment]
Yes @Ithildir is right, in this case the methods should be also updated because of the reflection Talend uses, before / after a property is changed on the UI. I'll send a follow-up PR soon. Thanks!

**Pull request closed without merging**
