### PR TITLE
App Servers: Jonas build

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by mdelapenya** [comment]
cc/ @Ithildir

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
Seems not related...

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5a0d07dda8...8a9e632f1b

**Comment by brianchandotcom** [comment]
@Ithildir I published a new jar. can you send me a  pull for the new gradle-plugins usage? Thx.

**Pull request closed without merging**
