### PR TITLE
LPS-54640 update existing tests to use the same access pattern

### PR DESCRIPTION
**Pull request by rotty3000**
@mhan810 @shuyangzhou fyi.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@rotty3000 This will break fabric, it is not OSGi aware.
Can you hold off changing any fabric related things?

**Comment by rotty3000** [comment]
Can you explain how it will break fabric?

**Comment by shuyangzhou** [comment]
it is not OSGi aware, no one is going to set up the Registry.

**Comment by rotty3000** [comment]
I ran your tests and they were fine.

**Comment by shuyangzhou** [comment]
it is not covered by that test. It does not even run in portal jvm.

**Comment by rotty3000** [comment]
Where is fabric running?

**Comment by rotty3000** [comment]
Why is the code in portal-impl?

**Comment by shuyangzhou** [comment]
A remote machine, a different jvm.

**Comment by shuyangzhou** [comment]
It is not completed yet, it will be moved out.

**Comment by rotty3000** [comment]
So only the `JMXProxyUtil`?

**Comment by shuyangzhou** [comment]
right

**Comment by rotty3000** [comment]
there I took that stuff out of the PR

**Comment by shuyangzhou** [comment]
Also the DataSourceFactoryImplTest.java, even though it works, it is just adding unnecessary complexity.
What's the point to create and populate the Registry, just that it can be used? While the MBeanServer is actually just sitting there ready to be used.

I get you know to standardized the access to MBeanServer, but it is still needed to be under a reasonable context, and DataSourceFactoryImplTest is not such a context.

**Comment by rotty3000** [comment]
because on some app servers we need to potentially change the MBeanServer,
and just getting the platform one all over the place is incorrect.

On Mon, Mar 30, 2015 at 11:31 PM, Shuyang Zhou <notifications@github.com>
wrote:

> Also the DataSourceFactoryImplTest.java, even though it works, it is just
> adding unnecessary complexity.
> What's the point to create and populate the Registry, just that it can be
> used? While the MBeanServer is actually just sitting there ready to be used.
>
> I get you know to standardized the access to MBeanServer, but it is still
> needed to be under a reasonable context, and DataSourceFactoryImplTest is
> not such a context.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/25272#issuecomment-87921640>
> .
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by shuyangzhou** [comment]
It is an unit test, it runs in its own junit jvm. Not related to any app server.

**Comment by rotty3000** [comment]
This way we can change everyone from one place.

**Comment by rotty3000** [comment]
uhmm, if the consumer is using the registry,. then the test must configure
the registry.

On Mon, Mar 30, 2015 at 11:36 PM, Raymond Auge <raymond.auge@liferay.com>
wrote:

> This way we can change everyone from one place.
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by shuyangzhou** [comment]
You can not change for the test, it does not even load any OSGI infrastructure that does the change.

The only reason it needs the MBeanServer is to check hikari 's runtime properties, which only exist in the junit jvm.

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
You're right about the data source test.. I thought it was playing down into the tomcat JMX connection pool settings. I'll remove that as well.

**Comment by shuyangzhou** [comment]
Ok, thanks, everything else looks good to me after a quick overview!

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:retest

**Pull request closed without merging**
