### PR TITLE
Lps 55159

### PR DESCRIPTION
**Pull request by shuyangzhou**
@cgoncas and @mdelapenya after this pull, we are technically detached from cobertura for our agent. But I still need to spend some time on some further clean up. Feel free to continue with your work, just if you are going to change some build script on the portal side, please let me review first, as it might conflict with my further changes (build script in sdk is irrelevant, you can change anything you like)

### CODE REVIEW

**Comment by willnewbury** [comment]
ci:retest

**Comment by willnewbury** [comment]
We are looking into this problem, it is not related to this build

**Comment by brianchandotcom** [comment]
@shuyangzhou 

1.) in build-common.xml we still reference 

<sysproperty key="net.sourceforge.cobertura.datafile" file="test-coverage/@{test.type}/cobertura.ser" />

is that OK?

2.) "-Djava.net.preferIPv4Stack=true" is in NewEnvTestRule but not in LocalProcessExecutorTest. Is that on purpose?

Same with liferay.mode=test

We also still have a lot of net.sourceforge.cobertura.datafile references

Thx.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
