### PR TITLE
[TS] LPS-69480 (Fixed sorting)

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-69480

Hi Brian,

Related to https://github.com/brianchandotcom/liferay-portal/pull/45620#issuecomment-268105260.

Br,
Tibor

----
Author: @amadeafejes
Reviewers: @NorbertKocsis, @Preston-Crary, @lipu

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:reopen

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by lipusz** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/45669

**Pull request closed without merging**
