### PR TITLE
LRQA-22142 Remove unnecessary escaping of console output snippets

### PR DESCRIPTION
**Pull request by pyoo47**

### CODE REVIEW

**Comment by kenjiheigel** [comment]
I think this got introduced with:
#35992

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cae4cb928c...e7e7270bb1

**Pull request closed without merging**
