### PR TITLE
LPS-64488 Update Websphere 8.5.5 to Fix Pack 9 and IBM JDK 8

### PR DESCRIPTION
**Pull request by alee8888**

### CODE REVIEW

**Comment by alee8888** [comment]
@david-truong @migue
Here is the updates to get Websphere working on Fix Pack 9 and IBM JDK 8.

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1332f201e3...c1d099071c

**Comment by brianchandotcom** [comment]
@alee8888 see my sorting in c1d099071c84881fb647761bdc02021aea20a956 Thx

**Pull request closed without merging**
