### PR TITLE
LPS-79709 SF

### PR DESCRIPTION
**Pull request by izaera**
This is part 2 of https://github.com/brianchandotcom/liferay-portal/pull/58739#issuecomment-391146446

@brianchandotcom Please see comments below because some CI failures look inocuous.

### CODE REVIEW

**Comment by izaera** [comment]
ci:reopen

**Comment by izaera** [comment]
The SF test is due to a change in BNDSourceUtil

**Comment by izaera** [comment]
ci:test

**Comment by jpince** [comment]
@petershin can you please follow up on the SF failure?

**Comment by jpince** [comment]
@vicnate5 weird startup error in the MariaDB batch. Not sure if this is worth investigating, haven't seen this anywhere else.
```   [exec] 11:48:06,586 INFO  [main][UpgradeProcess:103] Failed upgrade process com.liferay.portal.workflow.kaleo.designer.web.internal.upgrade.v1_0_1.UpgradeKaleoDefinitionVersion in 57ms
     [exec] INFO - Failed upgrade process com.liferay.portal.workflow.kaleo.designer.web.internal.upgrade.v1_0_1.UpgradeKaleoDefinitionVersion in 57ms
     [exec] 11:48:06,601 ERROR [main][com_liferay_portal_upgrade_impl:97] Invocation to listener threw exception 
     [exec] java.lang.RuntimeException: com.liferay.portal.kernel.upgrade.UpgradeException: java.lang.NullPointerException
```
https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/240068/consoleFull

@alee8888 I am concerned about this error, not sure if it's limited to this pull
`     [exec] 11:58:09,071 WARN  [http-nio-8080-exec-5][ThemeLocalServiceImpl:230] No theme found for specified theme id userdashboard_WAR_userdashboardtheme. Returning the default theme.`
https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/217327/AXIS_VARIABLE=0,label_exp=!master/consoleFull
https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/240068/consoleFull

**Comment by jpince** [comment]
@vicnate5 @alee8888 see [latest upstream run](https://testray.liferay.com/home/-/testray/case_results/index?delta=200&p_p_state=normal&orderByCol=testrayComponentName_sortable&orderByType=desc&testrayBuildId=330088118&testrayComponentId=84207674&statuses=3), both of these errors are there

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f0e2ec3757...d9f5cff274

**Comment by brianchandotcom** [comment]
@izaera please see my changes in d9f5cff thx.

**Comment by petershin** [comment]
@jpince - Following up with Peter Yoo to trouble shoot the SF error

**Comment by vicnate5** [comment]
@jpince There is a real upgrade issue https://issues.liferay.com/browse/LPS-81520. Will only affect master-private or master+private modules as we have on the CI.

**Comment by jpince** [comment]
cc/ @kenduenwald @john-co see my comment above re: upgrades https://github.com/brianchandotcom/liferay-portal/pull/59049#issuecomment-392078395

**Pull request closed without merging**
