### PR TITLE
LPS-70900 Incorrect MB post author initials in Search portlet results

### PR DESCRIPTION
**Pull request by arboliveira**
Author: @linolaoj 
Reviewer: @arboliveira

https://issues.liferay.com/browse/LPS-70900

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:reopen

**Comment by ChrisKian** [comment]
ci:retest

**Comment by arboliveira** [comment]
Failures appear to be unrelated.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3c3886ef63...5fb8476934

**Pull request closed without merging**
