### PR TITLE
Lps 75010

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
@dantewang can you take a look at the random failing test? Thanks!

**Comment by dantewang** [comment]
@shuyangzhou Does this test fail at `DataSourceFactoryImplTest.java:234` every time it fails?

**Comment by shuyangzhou** [comment]
@dantewang not sure, I did not pay attention to that, I just noticed this has failed a few times.

**Comment by tomwang2011** [comment]
ci:close rebase conflicts.

**Pull request closed without merging**
