### PR TITLE
LPS-58655

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Weird poshi test error 

ci:retest

**Comment by Ithildir** [comment]
Hi @brianchandotcom! Isn't this [same problem](https://github.com/brianchandotcom/liferay-portal/pull/30237#issuecomment-140936880), maybe?

**Comment by brianchandotcom** [comment]
Possibly. But they upped the time out already.

@brianchiu see this error too. May be it's better now that Shuyang disabled parallel rendering. See https://github.com/brianchandotcom/liferay-portal/pull/30292

**Comment by brianchiu** [comment]
@brianchandotcom 
Dang... that's already a 1 and a half minute timeout. I filed a ticket (https://issues.liferay.com/browse/LPS-58750) because even manually/locally the web content portlet seems to take abnormally longer than the other portlets to load.

But I'll keep an eye on it. If even after Shuyang turned off parallel rendering it still happens, we'll see if we can come up with another solution.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3e3151a678...29c4b01b9c

**Pull request closed without merging**
