### PR TITLE
COMMERCE-2820 resolve Mulesoft SonarQube issues

### PR DESCRIPTION
**Pull request by igorbeslic**
Hi Brian please merge. Thank you very much! @matijapetanjek

### CODE REVIEW

**Comment by igorbeslic** [comment]
ci:test:sf

**Comment by igorbeslic** [comment]
ci:test:relevant

**Comment by igorbeslic** [comment]
ci:test:stable

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fff1a6daa5...f2a1d12546

**Comment by brianchandotcom** [comment]
@hhuijser why do we need both

modules/etl/mulesoft/source-formatter-suppressions.xml

and

modules/etl/mulesoft/source-formatter.properties

Can you get rid of one? And if we have to have both, can we sort

modules/etl/mulesoft/source-formatter.properties

Thx.

**Pull request closed without merging**
