### PR TITLE
LPS-80193 SF

### PR DESCRIPTION
**Pull request by achaparro**
@ricardocousolr

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test

**Comment by achaparro** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f02c7d7a37...b7f9adb5bb

**Comment by brianchandotcom** [comment]
@achaparro are the strings "trimmed" already? if not, you'll end up with

update x fromy; ;

with a space in between the ;

**Pull request closed without merging**
