### PR TITLE
LPS-71620 Remove `Semantic` and rename Representor to ModelRepresentorMapper

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3adf863d1f...6b4d87d27a

**Comment by brianchandotcom** [comment]
@JorgeFerrer @ahdezma see 6b4d87d27a404b0b2a389d5a42a9b709be843dda

**Comment by JorgeFerrer** [comment]
Thanks for catching that Brian!

**Pull request closed without merging**
