### PR TITLE
LPS-71243 Uses ServiceUtil to create the trash entry

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@shuyangzhou did you guys help with this?

**Comment by ealonso** [comment]
Hey @brianchandotcom,

@shuyangzhou wrote me this comment in the original pull:

> @ealonso I talked with Brian. I think you misunderstood what he asked :) We don't need a clean cut for all trash kernel packages, as they are not all ready yet.
> 
> But some of the packages should already have no references to them. Like the "com.liferay.portlet.trash.service.impl", and maybe someone else too. Brian just wants those to go into portal compact, so that we can ensure nobody can touch those java files. As long as there are no reference to them, you won't run into any compile errors.
> 
> Please resend me the pull with only moving those clean packages into portal compact, thanks!

So, I've checked the packages without references and I sent the pull directly to you. But if you prefer I can send it to @shuyangzhou first.

Regards,
Eudaldo

**Comment by shuyangzhou** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/50065

**Comment by brianchandotcom** [comment]
@ealonso closed in favor of https://github.com/brianchandotcom/liferay-portal/pull/50065

**Pull request closed without merging**
