### PR TITLE
LPS-100144 Remove unnecessary css

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by brianchandotcom** [comment]
@ambrinchaudhary sorry, still has rebase issues.

**Comment by ambrinchaudhary** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/79798

**Comment by ambrinchaudhary** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/79799

**Pull request closed without merging**
