### PR TITLE
LPS-72780 Prevent undefined value from being pushed to array

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@ithildir we're downloading gems at runtime? See error.

**Comment by brianchandotcom** [comment]
@ithildir can we ensure the gems download is at least going through squid?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1470242420...aa9cc09be7

**Pull request closed without merging**
