### PR TITLE
[Log4J] LPS-125550 rebased

### PR DESCRIPTION
**Pull request by dantewang**
Rebased https://github.com/brianchandotcom/liferay-portal/pull/100200 on top of https://github.com/brianchandotcom/liferay-portal/commit/9fa764bc82c1cc92681b37aa5fb3b21ac7cf8d71. I excluded the plugin-ee repo reference commit according to https://github.com/brianchandotcom/liferay-plugins-ee/pull/24131#issuecomment-805308153.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:reopen

**Comment by dantewang** [comment]
cc @shuyangzhou @tinatian @yuhai

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5e5cbcde16...d2ef40418c

**Comment by brianchandotcom** [comment]
@dantewang please validate my change d2ef40418ce3307cd37eae49336da23ffba6dfcb is correct.

Do we still use "log4j.configure.on.startup" ?

**Comment by shuyangzhou** [comment]
@brianchandotcom "log4j.configure.on.startup" is "used", in a weird way... it is default to be true. If you disable it, we will end up not loading portal-log4j.xml, then every logger will default to log4j's default root logger. Not really sure why we have such logic, it was added before svn. It seems like we are providing a way to allow portal to startup in case of broken portal-log4j.xml. But I think it will probably be better to always load portal-log4j.xml, and if it is broken just fix it.

**Pull request closed without merging**
