### PR TITLE
LPS-92392 Regen

### PR DESCRIPTION
**Pull request by epgarcia**
@brianchandotcom Back then we decided to add an entity to represent the default segment (i.e. anyone) because you could select it to define how the page looks like for any user that does not belong to a segment. Since we introduced the concept of "experience", there's no longer need for the default segment entity. This simplifies the code and prevents issues like LPS-92871.

### CODE REVIEW

**Comment by epgarcia** [comment]
@darquesdev @andresfulla @ealonso

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ade7e63d26...121a40bbbb

**Comment by brianchandotcom** [comment]
@epgarcia see my changes in upstream... I've gone more toward functions and chainings the past few months....

**Comment by epgarcia** [comment]
@brianchandotcom Thanks for the promt review and for the changes. Looks better this way. Only, I'm not sure if we can move the logic to obtain the default segment name to the ContentPageLayoutEditorDisplayContext (see 72adce1761b459ce131cba8897cee49aa6e53782#diff-99167aa157822e05c8181ab3896e8d7bR143), as the resource bundle might not be accesible here. Let me check it if it works this way, and if not I'll send a follow-up PR with the fix.

**Comment by epgarcia** [comment]
@brianchandotcom Ok, the resourceBundle is that of the SegmentsConstants.class, so it's working fine. Thanks once again!

**Pull request closed without merging**
