### PR TITLE
[7.4 Only] LPS-119134, LPS-122478, LRQA-62587 Remove Solr Completely

### PR DESCRIPTION
**Pull request by BryanEngler**
manually sending the pr because forward is blocked by a SF failure https://issues.liferay.com/browse/LRQA-62652

### CODE REVIEW

**Comment by BryanEngler** [comment]
ci:test:relevant

**Comment by BryanEngler** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7550305d45...b91811c4d7

**Pull request closed without merging**
