### PR TITLE
LPS-74231

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@yuhai can you readd? Add a protected method in BaseCompanySettingsVerifyProcess

protected void putIfNotNull(dictionary, ....) {
}

Please resend. Thx. Fyi @mhan810

**Comment by hhuijser** [comment]
Hey @brianchandotcom. I told Hai the same thing (https://github.com/hhuijser/liferay-portal/pull/2992).
I changed my mind though for the sake of compatibility. If we do this, newer version of the modules won't work with older version of portal-impl?

What do you think?

**Comment by brianchandotcom** [comment]
it'll work @hhuijser 

We're adding a new protected method with an implementation. It requires a .1 increment. Change it to use project dependencies vs. the hard coded version and it should work.

**Comment by hhuijser** [comment]
Okay, will send you a pull for that.

**Pull request closed without merging**
