### PR TITLE
Translations spread from portal to modules 20151016111424

### PR DESCRIPTION
**Pull request by dsanz**
Hi @brianchandotcom 

Here is an special pull. It comes from Pootle and processed by my scripts.

The reason for doing this is that pootle was not updated for a while. Therefore the "portal" project had all portal translations as we used to have before modules existed. People continued translating that project in pootle while our engineers were splitting the code into modules. In that process, translations were splitted too, but were taken from current portal sources, not from pootle. 

Soon, I'll provision all translations projects into pootle corresponding to the new modules. I'll do this automatically from the source code, therefore the scripts will upload to pootle all valid translations coming from the code. This means that current "portal" project will become much smaller.

James Falkner realized that, as a result, people's work on pootle for the portal project would be lost, as that information exists only in the pootle DB, more specifically, in the (still monolithic) "Portal" translation project. 

Here's what I implemented in the scripts to get this PR done:
1. Export current production portal project into a set of Language*.properties files
2. Loop through all modules having a Language.properties file
3. For each locale, get the untranslated keys and see if they are translated in the Lang files coming from step one. If they are, copy the translation into the module's lang file
4. Commit everything (first commit in this PR)
5. ant/gradle build lang (second commit in this PR)

Once these changes are in master, I'll launch the auto-provisioning process, which takes the freshest master, computes the set of projects and populates pootle with them, including translations. As a result, a bunch of new projects will show up in translate.liferay.com having all existing translations in them. This will save a lot of work to translators.

Please let me know if you have any question about this PR.

Thanks for your time Brian
Daniel.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Great job @dsanz 

I'm trying also to make your life easier by ensuring that keys are only in one module. So if there are duplicate keys, we'll make a separate common lang module.

Thx Daniel

cc @rotty3000

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/079680d7a9...ebfa62a479

**Comment by brianchandotcom** [comment]
also dnaiel, should we use a real LPS next time vs. LPS-000 ?

**Comment by dsanz** [comment]
Thx Brian,

I chose to use LPS-00000 because a bot blocked PR w/o LPS reference.

Once I provision all projects, we'll be having regular, periodic syncs automatically triggered. For those there is no easy way to create LPS unless scripts are enhanced to interact with JIRA.

So for now the sync tool just prepends that code. It's not optimal, but I focused on closing the circle first.

Thx

**Pull request closed without merging**
