### PR TITLE
[Rename Classes] LPS-167594 in module product-navigation,template,portal-workflow,analytics

### PR DESCRIPTION
**Pull request by dantewang**
FYI @shuyangzhou @tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1f2757d792...dc1aee0f8a

**Comment by brianchandotcom** [comment]
@JanisZhang @dantewang see db1ba55

**Comment by brianchandotcom** [comment]
@JanisZhang @dantewang please fix others like db1ba55

**Pull request closed without merging**
