### PR TITLE
LPS-68476 KB article navigation icons are too close to the text

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by jpince** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/01f2757189...85473ec6d8

**Comment by brianchandotcom** [comment]
@sergiogonzalez @adolfopa nbsp's are very bad for blind people because it constantly reads it out for them. See 85473ec6d80d55094431f021045122b4088b25fc to achieve the same thing.

**Pull request closed without merging**
