### PR TITLE
LPD-28802 Send email notification to user invited to a publication

### PR DESCRIPTION
**Pull request by brookedalton**
Resent from https://github.com/brianchandotcom/liferay-portal/pull/152712#issuecomment-2256755913 after updating tmpl files to match existing patterns

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@brookedalton 

we also have portal-kernel/src/com/liferay/portal/kernel/model/UserNotificationDeliveryConstants.java.TYPE_EMAIL ?

Why can't we send it that way ?

**Comment by brookedalton** [comment]
ci:reopen

**Comment by brookedalton** [comment]
Hi @brianchandotcom, I'm not exactly sure what you mean but I am using [UserNotificationDeliveryConstants.TYPE_EMAIL](https://github.com/brianchandotcom/liferay-portal/pull/152768/commits/793b002ab56c41344c4283dbf13907cd77ad0066) in the notification definition.

**Comment by brianchandotcom** [comment]
@brookedalton ok, after seeing it more deeply, I mean this:

See modules/apps/portal-workflow/portal-workflow-kaleo-runtime-impl/src/main/java/com/liferay/portal/workflow/kaleo/runtime/internal/notification/EmailNotificationSender.java

I searched for:

```
git grep "UserNotificationDeliveryConstants.TYPE_EMAIL"
```

To see how it was used.

We have:

```
			notificationEvent.setDeliveryType(
				UserNotificationDeliveryConstants.TYPE_WEBSITE);
```

So I assumed you could set delivery type to email and it would send it, instead of you manaully sending it.

See also modules/apps/message-boards/message-boards-web/src/main/java/com/liferay/message/boards/web/internal/notifications/MBAddEntryUserNotificationDefinition.java

How do those send emails? Don't they "leverage" the framework instead of manually sending the email?

**Comment by brookedalton** [comment]
Hi @brianchandotcom, 
The EmailNotificationSender.java file in portal-workflow extends a [BaseNotificationSender](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-workflow/portal-workflow-kaleo-runtime-api/src/main/java/com/liferay/portal/workflow/kaleo/runtime/notification/BaseNotificationSender.java) that is specific to workflow 

For
```
notificationEvent.setDeliveryType(
  UserNotificationDeliveryConstants.TYPE_WEBSITE);
```
I couldn't find an example in portal that has notificationEvent.setDeliveryType with type Email but I believe it is used for registering the notification to allow users to configure their notification settings

MBAddEntryUserNotificationDefinition.java uses a subscription sender to send their emails [MBMessageLocalServiceImpl.java](https://github.com/liferay/liferay-portal/blob/master/modules/apps/message-boards/message-boards-service/src/main/java/com/liferay/message/boards/service/impl/MBMessageLocalServiceImpl.java#L2397) but Publications does not use subscribers

I was trying to look at other components and it seems like a lot use the subscriptionSender framework ([asset publisher](https://github.com/liferay/liferay-portal/blob/master/modules/apps/asset/asset-publisher-web/src/main/java/com/liferay/asset/publisher/web/internal/scheduler/helper/AssetEntriesCheckerHelper.java#L432) , [web content](https://github.com/liferay/liferay-portal/blob/master/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleLocalServiceImpl.java#L6931))

**Pull request closed without merging**
