### PR TITLE
LPS-162527 Adds override

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-162527

@BarbaraCabrera 
@ealonso

### CODE REVIEW

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/9624

:heavy_check_mark: ci:test:stable - 25 out of 25 jobs passed
:x: ci:test:relevant - 112 out of 118 jobs passed in 5 hours 15 minutes

**Comment by ozysouza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a1215a9899...74bc3c40cc

**Comment by brianchandotcom** [comment]
@BarbaraCabrera @ealonso see a2de771ee2039c311aef839f79e2096433857c75

**Pull request closed without merging**
