### PR TITLE
LPS-93163 SF

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3e32e88322...ca9d5ddeff

**Comment by brianchandotcom** [comment]
@brunobasto please review my changes from c551a324ab4dd0b61863cdfe81b16a571c3d2bf7 to ca9d5ddeff8039a10996fdfd2fc68fd3a2e12338 thx.

**Comment by brianchandotcom** [comment]
@alexcandidos please verify I didn't break anything, I hope your automated tests catch my changes! If not, they should! thx.

**Comment by brunobasto** [comment]
Got it @brianchandotcom. Personal notes for lessons learned:
From c551a324ab4dd0b61863cdfe81b16a571c3d2bf7: Inline single method call when there's only one call to it.
From b4772ebad6247bcd2e156fc4224f6d941a4d067b: Inline null comparison instead of storing to a boolean variable
From 8fefa38c1ac7558ce2ff4db5cbf68c704e1fe9fe: Sort alphabetically when there's no reason not to do so.
From 166cf7ddb8e098d27b1b55f7c208533dc493be80: Odd variable name, with odd type for what it does.
From ca9d5ddeff8039a10996fdfd2fc68fd3a2e12338: Sort attribute value and inline single method call.

Thx!

**Pull request closed without merging**
