### PR TITLE
LRQA-30908 Compensate for missing primary branch

### PR DESCRIPTION
**Pull request by pyoo47**
The debug statements that I added in my previous pull request helped me to discover that the HEAD ref not found error and the cannot checkout branch error are somewhat related. The HEAD ref not found error occurs when I try to create a new branch when the currently checked out branch doesn't exist.

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:stop - Source build got stuck on a github api call.

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9c0779ff3c...1805467018

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
@pyoo47 come see me please, see 1805467018718f71fe8a9efda9cde32c21e2ae34

**Pull request closed without merging**
