### PR TITLE
LRQA-18824

### PR DESCRIPTION
**Pull request by pyoo47**
Resend of https://github.com/brianchandotcom/liferay-portal/pull/37632#issuecomment-200014039

https://issues.liferay.com/browse/LRQA-18824

Major refactoring to change "job" to "build"

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by kevin-yen** [comment]
ci:retest

**Comment by kevin-yen** [comment]
ci:retest

**Comment by pyoo47** [comment]
Will resubmit after rebasing

**Pull request closed without merging**
