### PR TITLE
LPS-109392 | master

### PR DESCRIPTION
**Pull request by brookedalton**

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:open

**Comment by brookedalton** [comment]
ci:reopen

**Comment by jpince** [comment]
Just started reviewing :)

**Comment by jpince** [comment]
@brookedalton thanks! Pushed to Brian Chan's origin https://github.com/brianchandotcom/liferay-portal/commit/6e6ca7755e891e7604a88f8076e13edf8196d9e0

This is a follow up to #87063, fixing a compile error caused by https://github.com/brianchandotcom/liferay-portal/commit/5e49ef5afe8f32b9570782df138ca7f6e0ea1ac1

**Pull request closed without merging**
