### PR TITLE
Lps 54094

### PR DESCRIPTION
**Pull request by shuyangzhou**
@brianchandotcom This pull contains #24607, #24613 and #24614 to show the result as a whole.

Just like LPS-54091, LPS-54094 is still not fixing the root problem, however it addes another defense layer for concurrent deployments' race condition.

The thing is we should never ever trying the create the same ClassName/ResourceAction concurrently, but for some reason, we are constantly doing it right now. Creating tons of race conditions.

In LPS-54094, I added a protection retry on unique index failure, which most likely will be caused by this concurrent same ClassName/ResourceAction creation. So that one thread will win, the rest will refetch the winner's result and move on, just leaving an annoying error log from DefaultTransactionExecutor, but nothing would fail from it.

We really should dig down to the root to fix this weird concurrent deployment process to the same bundle. I will keep looking into it next week.

Still the 2 known random failing reasons, ExportImportLifecycleEventTest and JSONWebServiceActionsManagerImpl would become the top ones you see most. I will take care of them in next week.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@brianchandotcom This has happened a couple times, CI is hanging at some clean up process:

clean-up-admin-portal-repository:
     [exec] From github.com:brianchandotcom/liferay-portal
     [exec]  * [new branch]      temp-test-1-3-ee-1425779416 -> pr/temp-test-1-3-ee-1425779416
     [exec]  * [new branch]      temp-test-1-4-ee-1425779414 -> pr/temp-test-1-4-ee-1425779414
     [exec]  * [new branch]      temp-test-1-5-ee-1425779416 -> pr/temp-test-1-5-ee-1425779416
     [exec]  * [new branch]      temp-test-1-6-ee-1425779420 -> pr/temp-test-1-6-ee-1425779420
     [exec] error: unable to delete 'temp-test-1-1-ee-1425758203': remote ref does not exist
     [exec] error: failed to push some refs to 'git@github.com:brianchandotcom/liferay-portal.git'
     [exec] error: unable to delete 'temp-test-1-1-ee-1425761984': remote ref does not exist
     [exec] error: failed to push some refs to 'git@github.com:brianchandotcom/liferay-portal.git'
     [exec] To git@github.com:brianchandotcom/liferay-portal.git
     [exec]  - [deleted]         temp-test-1-1-ee-1425762514
     [exec] error: unable to delete 'temp-test-1-2-ee-1425758206': remote ref does not exist
     [exec] error: failed to push some refs to 'git@github.com:brianchandotcom/liferay-portal.git'
     [exec] error: unable to delete 'temp-test-1-2-ee-1425762017': remote ref does not exist
     [exec] error: failed to push some refs to 'git@github.com:brianchandotcom/liferay-portal.git'
     [exec] To git@github.com:brianchandotcom/liferay-portal.git
     [exec]  - [deleted]         temp-test-1-2-ee-1425762833
     [exec] error: unable to delete 'temp-test-1-3-ee-1425757675': remote ref does not exist
     [exec] error: failed to push some refs to 'git@github.com:brianchandotcom/liferay-portal.git'
     [exec] error: unable to delete 'temp-test-1-3-ee-1425758211': remote ref does not exist
     [exec] error: failed to push some refs to 'git@github.com:brianchandotcom/liferay-portal.git'
     [exec] error: unable to delete 'temp-test-1-3-ee-1425762267': remote ref does not exist
     [exec] error: failed to push some refs to 'git@github.com:brianchandotcom/liferay-portal.git'
     [exec] To git@github.com:brianchandotcom/liferay-portal.git
     [exec]  - [deleted]         temp-test-1-3-ee-1425764669
     [exec] error: unable to delete 'temp-test-1-4-ee-1425757674': remote ref does not exist
     [exec] error: failed to push some refs to 'git@github.com:brianchandotcom/liferay-portal.git'
     [exec] error: unable to delete 'temp-test-1-4-ee-1425758209': remote ref does not exist
     [exec] error: failed to push some refs to 'git@github.com:brianchandotcom/liferay-portal.git'
     [exec] error: unable to delete 'temp-test-1-4-ee-1425762073': remote ref does not exist
     [exec] error: failed to push some refs to 'git@github.com:brianchandotcom/liferay-portal.git'
     [exec] To git@github.com:brianchandotcom/liferay-portal.git
     [exec]  - [deleted]         temp-test-1-4-ee-1425764663
     [exec] error: unable to delete 'temp-test-1-5-ee-1425757677': remote ref does not exist
     [exec] error: failed to push some refs to 'git@github.com:brianchandotcom/liferay-portal.git'
     [exec] error: unable to delete 'temp-test-1-5-ee-1425758208': remote ref does not exist
     [exec] error: failed to push some refs to 'git@github.com:brianchandotcom/liferay-portal.git'
     [exec] error: unable to delete 'temp-test-1-5-ee-1425762274': remote ref does not exist
     [exec] error: failed to push some refs to 'git@github.com:brianchandotcom/liferay-portal.git'
     [exec] To git@github.com:brianchandotcom/liferay-portal.git
     [exec]  - [deleted]         temp-test-1-6-ee-1425757676
     [exec] To git@github.com:brianchandotcom/liferay-portal.git
     [exec]  - [deleted]         temp-test-1-6-ee-1425759433

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
This error is caused by JSONWebServiceActionsManagerImpl's random npe, it is safe to be merged.

JSONWebServiceActionsManagerImpl has became such a painful problem, can not wait any longer, I will deal with it first thing tomorrow.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/94c14f1305...9410ef9c8e

**Comment by brianchandotcom** [comment]
Thank you so much Shuyang... no one else here would have been able to do this Shuyang... bravo!

**Pull request closed without merging**
