### PR TITLE
LPS-74544

### PR DESCRIPTION
**Pull request by petershin**
@jpince @hhuijser

### CODE REVIEW

**Comment by petershin** [comment]
ci:test

**Comment by hhuijser** [comment]
@petershin , were these modified after my commits?

**Comment by petershin** [comment]
@hhuijser - They were modified 5 days ago:

https://github.com/liferay/liferay-portal/commits/master/portal-impl/test/integration/com/liferay/portal/util/PortalImplAlternateURLTest.java

https://github.com/liferay/liferay-portal/commits/master/portal-impl/test/integration/com/liferay/portal/util/PortalImplCanonicalURLTest.java

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by hhuijser** [comment]
@petershin, that was confusing... committed 5 days ago, but only pushed upstream about 8 hours ago :)

**Comment by petershin** [comment]
@hhuijser - With the timezone difference, there's usually a gap between when you send your pulls and they're merged to upstream.  Pulls sent during that gap can be missed.  :worried:

I'm usually in the office while you're sleep though, so if I happen to catch it, I'll cc you and @jpince on any fixes.

**Pull request closed without merging**
