### PR TITLE
LPS-173157

### PR DESCRIPTION
**Pull request by tinatian**
FYI @shuyangzhou

### CODE REVIEW

**Comment by yuhai** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/95b5f60083...7fcfcd5921

**Comment by brianchandotcom** [comment]
@tinatian @yuhai can you resend and make the package 

com.liferay.fragment.internal.file.install

and

com.liferay.batch.engine.internal.file.install

to match com.liferay.portal.file.install.FileInstaller

Thx

**Comment by yuhai** [comment]
resend it to https://github.com/brianchandotcom/liferay-portal/pull/130696

**Pull request closed without merging**
