### PR TITLE
LPS-84450 buildService

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by jpince** [comment]
ci:stop

**Comment by jpince** [comment]
ci:test:relevant @inacionery update to git-commit-portal-private made in upstream just after you sent this :)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c246ebd968...d668aa1778

**Comment by brianchandotcom** [comment]
@inacionery did you intend "Long userId" vs "long userId"

Merged.

**Comment by inacionery** [comment]
Hey @brianchandotcom 

It was intentional.

Thx!

**Pull request closed without merging**
