### PR TITLE
LPS-65896

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@juliocamarero, @sergiogonzalez, @marcellustavares fyi, minor adjustments to your components to remove usage of MultiVM and SingleVMPoolUtils

**Comment by pyoo47** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchiu** [comment]
The upgrades failure happened because of https://issues.liferay.com/browse/LPS-65961, a bug that happens randomly and also not very often.

**Comment by pyoo47** [comment]
ci:retest

**Comment by jpince** [comment]
ci:retest

**Comment by mhan810** [comment]
will rebase and resend

**Pull request closed without merging**
