### PR TITLE
LPS-67049 cache

### PR DESCRIPTION
**Pull request by Ithildir**
cc @tomwang2011

### CODE REVIEW

**Comment by tomwang2011** [comment]
Hi @Ithildir for future reference, is there something I need to set to download the POM file during compiling/deploying? It did not download automatically like the jar file.

**Comment by Ithildir** [comment]
Sometimes it happens because the Gradle cache (the `liferay-portal/.gradle` dir) already has some information about the POM: when Gradle downloads a dependency, it converts the POM into an Ivy file (which we don't commit because it's machine-specific). Then, if a dependency is requested again and the POM is missing from the cache, Gradle does not download the POM.

The approach I use is to completely clean the `.gradle` dir with `git clean -dfx`, run `ant setup-sdk` and then run `gradlew jar` on the module with the dependency you want to commit.

**Comment by tomwang2011** [comment]
Thanks for the explanation @Ithildir!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f10fb74c39...213b7dba50

**Pull request closed without merging**
