### PR TITLE
LPS-174013 Move the implementation to the proper collection provider

### PR DESCRIPTION
**Pull request by Tim-Cao**
This is only for master.

https://issues.liferay.com/browse/LPS-174013

@lfbesada

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/11091

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ea8c41ff41...cdaf151f1c

**Comment by brianchandotcom** [comment]
Very nice @lfbesada just cdaf151f1c3759237e27ea96dda921dd0fb0d1a6

**Pull request closed without merging**
