### PR TITLE
Lps 72928

### PR DESCRIPTION
**Pull request by shuyangzhou**
Resent of https://github.com/brianchandotcom/liferay-portal/pull/50186 with SF fix
@david-truong @anitaderiane @mhan810

@hhuijser "ant format-source-local-changes" and "ant format-source-current-branch" does not pick the all the affected files, for example in https://github.com/brianchandotcom/liferay-portal/pull/50186, I had an issue in the module-log4j.xml. I normally run "ant format-source-local-changes" locally, which did not find the problem, until CI runs the whole thing which breaks of course. Can we fix this?

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:stop

**Comment by michaelhashimoto** [comment]
ci:retest - There was a CI outage recently, see this slack post for more information:
https://liferayeng.slack.com/archives/C19PWQ74J/p1499712491340859

**Comment by hhuijser** [comment]
@shuyangzhou I'll look into that

**Comment by brianchandotcom** [comment]
@shuyangzhou please resend, rebase error. Thx.

**Comment by shuyangzhou** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/50231

**Pull request closed without merging**
