### PR TITLE
LPS-98277 Sort properties and use double quotes in JSX

### PR DESCRIPTION
**Pull request by wincent**
As requested here:

https://github.com/brianchandotcom/liferay-portal/pull/75741#issuecomment-511581392

- The use of double quotes in JSX property names comes via Prettier and will apply to all ".js" files.
- The sorting of properties comes via ESLint, and therefore only applies to "modern" (ie. ".es.js" files).

Included in the liferay-npm-scripts v4.11.0 update are:

- We now bundle `@testing-libary/user-event` in our development dependencies, which will make it easy to write user-focused tests.
- A fix for a regression in which we weren't able to use `async`/`await` in tests.

### CODE REVIEW

**Comment by wincent** [comment]
@brianchandotcom: I'm hoping there won't be any merge/rebase conflicts in this one. It touches "only" 62 files, but is the kind of automated thing that I would push directly in the AM (Spain time); however it seems that I don't have push access to your fork after all.

This touches 4 files in modules/apps/layout/layout-content-page-editor-web, which as we discussed [over here](https://github.com/brianchandotcom/liferay-portal/pull/75691#issuecomment-511487011), probably won't backport to "7.2.x". I am going to send a separate 7.2.x PR that will basically be identical to this, but omitting those files.

@andresfulla: this is the PR that makes `@testing-library/user-event` available in liferay-portal.

@brunofarache: this is the PR that makes `async`/`await` work in liferay-portal tests again.

**Comment by wincent** [comment]
PR for the 7.2.x branch is here: https://github.com/brianchandotcom/liferay-portal/pull/75766

**Comment by wincent** [comment]
New PR for the 7.2.x branch: https://github.com/brianchandotcom/liferay-portal-ee/pull/25432

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ea256c48da...097f0f3236

**Comment by wincent** [comment]
"master-private" analog of this PR: https://github.com/brianchandotcom/liferay-portal-ee/pull/25447

**Pull request closed without merging**
