### PR TITLE
Lps 74553

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ba603507ae...a8b218b667

**Comment by brianchandotcom** [comment]
@shuyangzhou please send a backport to the support team. Thx.

**Comment by shuyangzhou** [comment]
@tomwang2011 back port please.

**Pull request closed without merging**
