### PR TITLE
LPS-66598 SF

### PR DESCRIPTION
**Pull request by marcellustavares**
cc @rafaprax

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@marcellustavares isn't this the wrong fix? We already released the module?

**Comment by brianchandotcom** [comment]
@marcellustavares please resend. Thx.

**Comment by marcellustavares** [comment]
@rafaprax, could you please take a look at this?

**Comment by rafaprax** [comment]
fixed and resent https://github.com/brianchandotcom/liferay-portal/pull/41540

**Pull request closed without merging**
