### PR TITLE
LPS-159214 Fix misuse of aui:button taglib api resulting in incorrect styles being applied to buttons.

### PR DESCRIPTION
**Pull request by ethib137**
Manually forwarding due to ci forward fail: https://github.com/liferay-frontend/liferay-portal/pull/2583

### CODE REVIEW

**Comment by ethib137** [comment]
ci:reopen

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e0dde80ded...cf5b9e0c59

**Pull request closed without merging**
