### PR TITLE
LPS-97745 Invert condition

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
Again, thanks for this @JosemariaMunoz!

cc:// @ealonso

**Comment by JosemariaMunoz** [comment]
Thanks to you @jkappler!! It is a pleasure! 👍

**Comment by brianchandotcom** [comment]
@jkappler rebase error, can you resend? Thx.

**Comment by jkappler** [comment]
Just started reviewing :)

**Pull request closed without merging**
