### PR TITLE
[PLS DO NOT BACKPORT] LPS-83501 Merge field types into a single bundle

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:retest

**Comment by brunobasto** [comment]
ci:reopen

**Comment by brunobasto** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/618923d930...f43db0a124

**Pull request closed without merging**
