### PR TITLE
LPS-183485: Headless search API changes

### PR DESCRIPTION
**Pull request by peerkar**
Original PR: https://github.com/brianchandotcom/liferay-portal/pull/137077

### CODE REVIEW

**Comment by peerkar** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3f8633ed8f...f7eec47662

**Comment by brianchandotcom** [comment]
@peerkar 1.) can we change

```
	private String[] _toArray(String csvString) {
		if (Validator.isBlank(csvString)) {
			return new String[0];
		}

		csvString = StringUtil.trim(csvString);

		return csvString.split("\\s*,\\s*");
	}
```

to

StringUtil.split ?

2.) SearchPage is fine. I didn't understand it earlier.

See changes in my origin. Thx @peerkar !

**Comment by peerkar** [comment]
@brianchandotcom 

> 1.) can we change to StringUtil.split ?

It looked to me, it does not support regex as delimiter(?)

**Pull request closed without merging**
