### PR TITLE
LPS-102573 Inline actions

### PR DESCRIPTION
**Pull request by javierdearcos**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.

**Comment by brianchandotcom** [comment]
@javierdearcos see my changes in upstream. I'd like you to send me 2 follow up pulls:

1.) Can you remove

headless-common-spi/src/main/java/com/liferay/headless/common/spi/resource/SPICommentResource.java

I don't mind if there is a breaking change. It's only used internally for 

headless-delivery/headless-delivery-impl/src/main/java/com/liferay/headless/delivery/internal/resource/v1_0/CommentResourceImpl.java

Anything that uses it, move it into headless-delivery-impl directly.

2.) Type:

git grep "private Page<" **ResourceImpl*.java

Can you sort all those method parameters alphabetically? I just wanted it all sorted to match SearchUttil.java

When you send it, can you notify @hhuijser with that commit and on that pull. I want him to then auto SF enforce that change you're doing. In fact, there are probably 10-12 methods like that. Purposefully do all but 1 or 2. I want to test Hugo's script to make sure it catches the rest.

See my origin for my other changes. Thank you!

**Comment by brianchandotcom** [comment]
@javierdearcos please backport as you see fit.

**Comment by javierdearcos** [comment]
Ok. Sorry, today I was all day fighting with some bugs. Tomorrow I make the two tasks you mentioned.

Thank you

**Pull request closed without merging**
