### PR TITLE
LPS-76779 Increases version (baseline)

### PR DESCRIPTION
**Pull request by robframpton**

### CODE REVIEW

**Comment by Robert-Frampton** [comment]
ci:test

**Comment by jpince** [comment]
@Robert-Frampton semver. I think it wants you to back up [/frontend/taglib/servlet/taglib/soy/packageinfo](https://github.com/brianchandotcom/liferay-portal/pull/55404/commits/5920b9f5e4dbb15079866620cd8d3ae74106fdc8#diff-5198886ec973abc5eccb7fab382c95f2L1) to 1.1 (though I was not aware semver allowed for version decreases)

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal/pull/55418.

**Comment by Robert-Frampton** [comment]
Thanks @Ithildir!

**Pull request closed without merging**
