### PR TITLE
LPS-107869 Bump CKEditor plugin versions to 4.13.1

### PR DESCRIPTION
**Pull request by wincent**
This should have been done as part of 7876e94f4845c, but I just noticed it was out-of-sync while an unrelated task led me to the build.gradle file.

We should rework this so that falling out of sync like this isn't possible (for example, maybe we could derive the version number from the one in the package.json file), but I will need to loop in some help from somebody who knows more about Gradle than I do, so just sending this immediate fix for now.

### CODE REVIEW

**Comment by wincent** [comment]
cc @markocikos

> We should rework this so that falling out of sync like this isn't possible (for example, maybe we could derive the version number from the one in the package.json file), but I will need to loop in some help from somebody who knows more about Gradle than I do, so just sending this immediate fix for now.

@jbalsas: can you give me a pointer for who to ask about the proposed changes to the Gradle file? Specifically, we'd want to:

1. Read the version of "liferay-ckeditor" [from the package.json file](https://github.com/liferay/liferay-portal/blob/3f4502ca3f108494b444c1d82598dbe5b8e34bda/modules/apps/frontend-editor/frontend-editor-ckeditor-web/package.json#L4); eg ""4.13.1-liferay.1"
2. Strip off the `-liferay*` suffix to get the actual CKEditor version (ie. "4.13.1").
3. Use that instead of the hand-coded version number in the `build.gradle`.

**Comment by jbalsas** [comment]
Hey @wincent, since we always bring these additional plugins in... wouldn't it make sense to bundle them in our `liferay-ckeditor` distribution? That way we can handle this in our build scripts over there, keep it in sync with our updates, remove the additional `.gradle` manipulation here and provide an ootb complete solution.

**Comment by wincent** [comment]
@jbalsas: Let me look into that and report back. If it can be done it sure would be cleaner.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b097146a99...6212858a59

**Comment by brianchandotcom** [comment]
@wincent @jbalsas glad you guys are on this.

**Comment by wincent** [comment]
Just to close the loop here somewhat: [this is the change in liferay-ckeditor](https://github.com/liferay/liferay-ckeditor/pull/39) that bundles those plug-ins. Once that's tested I'll cut a release and update the liferay-portal version from "4.13.1-liferay.1" to "4.13.1-liferay.2", at which point we can strip out the related bits of the build.gradle (funnily enough, [not for the first time](https://github.com/brianchandotcom/liferay-portal/pulls?utf8=%E2%9C%93&q=is%3Apr+LPS-73369)).

**Comment by wincent** [comment]
See: https://github.com/brianchandotcom/liferay-portal/pull/84613

**Pull request closed without merging**
