### PR TITLE
LPS-71982 Removes leftovers from transpilation from Soy to JavaScript

### PR DESCRIPTION
**Pull request by brunobasto**
/cc @pedroqueiroz @clovisdasilvaneto

### CODE REVIEW

**Comment by brunobasto** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@ithildir I merged this, but I found a strange pattern, type

git grep "includeresource: package.json"

```
modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-form-builder/bnd.bnd:-includeresource: package.json
modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-form-renderer/bnd.bnd:-includeresource: package.json
modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-type-captcha/bnd.bnd:-includeresource: package.json
modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-type-checkbox-multiple/bnd.bnd:-includeresource: package.json
modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-type-checkbox/bnd.bnd:-includeresource: package.json
modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-type-date/bnd.bnd:-includeresource: package.json
modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-type-document-library/bnd.bnd:-includeresource: package.json
modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-type-editor/bnd.bnd:-includeresource: package.json
modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-type-fieldset/bnd.bnd:-includeresource: package.json
modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-type-grid/bnd.bnd:-includeresource: package.json
modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-type-key-value/bnd.bnd:-includeresource: package.json
modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-type-numeric/bnd.bnd:-includeresource: package.json
modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-type-options/bnd.bnd:-includeresource: package.json
modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-type-paragraph/bnd.bnd:-includeresource: package.json
modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-type-password/bnd.bnd:-includeresource: package.json
modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-type-radio/bnd.bnd:-includeresource: package.json
modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-type-select/bnd.bnd:-includeresource: package.json
modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-type-text/bnd.bnd:-includeresource: package.json
modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-type-validation/bnd.bnd:-includeresource: package.json
modules/sdk/project-templates/project-templates-soy-portlet/src/main/resources/archetype-resources/bnd.bnd:-includeresource: package.json
```

That doesn't seem right to me.. I'd expect it to auto include that file already if it was needed.

@pedroqueiroz are you sure we need to include package.json at runtime?

**Comment by pedroqueiroz** [comment]
@brunobasto , do you have the answer for @brianchandotcom 's question? Thanks!

**Comment by pedroqueiroz** [comment]
Sure thing: https://github.com/brianchandotcom/liferay-portal/pull/57337

**Pull request closed without merging**
