### PR TITLE
LPS-65991

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by sharonchoi** [comment]
investigating poshi errors.

**Comment by sharonchoi** [comment]
@brianchandotcom please do not merge
@sergiogonzalez There are missing language keys for the buttons on DM portlet, please see screenshot here:
after0

**Comment by brianchandotcom** [comment]
@sergiogonzalez please resend. Thx.

**Pull request closed without merging**
