### PR TITLE
LPS-57564 build URLs using the right mechanism and support for 2 links per page

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @jbalsas this is the change we talked about for the {selPlid}

(I hope this doesn't conflict with your pull)

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
fyi @jbalsas @carloslancha

**Comment by juliocamarero** [comment]
cc @ealonso

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9ebfb8bf9a...91a82d76b7

**Pull request closed without merging**
