### PR TITLE
LPS-80335 Use cover image url, and if not available, use small image

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by jpince** [comment]
ci:close

**Comment by jpince** [comment]
@austinchiang @patriciajeanperez looks like this might break blogs, please investigate

image

**Comment by patriciajeanperez** [comment]
Hi @sergiogonzalez, this pull breaks our tests that add multiple blog entries. "Blogs is temporarily unavailable" displays when there are more than one blog entry, and a user tries to navigate to the first entry. Please take a look. Thanks!

**Comment by sergiogonzalez** [comment]
Thanks @jpince and @patriciajeanperez for letting me know about this bug so fast. I have just resent the right one here https://github.com/brianchandotcom/liferay-portal/pull/58299

**Pull request closed without merging**
