### PR TITLE
LPS-76927 Avoid the execution of the macrodef for portal-data-release.sql with if:set

### PR DESCRIPTION
**Pull request by achaparro**
from:
brianchandotcom/liferay-portal-ee#19919

@brianwulbern

@brianchandotcom, please backport it to 7.0.x and 7.0.x-private if you can.

Thanks.

### CODE REVIEW

**Comment by achaparro** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianwulbern** [comment]
@achaparro @brianchandotcom note after this commit, we met the same issue described in [LPS-79752](https://issues.liferay.com/browse/LPS-79752).  I triggered the [EE Development](https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=61201829) run on 7.0.x-private (at https://github.com/liferay/liferay-portal-ee/commit/79e5708a868665036e05ecab7ca5a4960bf37ac3) attests to the startup error

**Comment by achaparro** [comment]
Hi @brianwulbern,

take into account that the proposed solution works only in ant 1.9.3 and higher, see:
https://bz.apache.org/bugzilla/show_bug.cgi?id=55885

Could you verify that?

Thanks.

**Comment by brianwulbern** [comment]
I'll check with @liuxingye when he comes in.  I can't find the ANT version defined anywhere in Jenkins configuration, so I'm just trying a run locally on my 1.9.8.  At any rate, tests on Jenkins won't run if the [Smoke test](https://testray.liferay.com/home/-/testray/case_results/270419628) fails.  So the Development and Gauntlet runs aren't getting past the failing Smoke test now.

@pyoo47, @michaelhashimoto, can you guys confirm the ANT version we run on our Jenkins servers?

cc @jpince @ctampoya

**Comment by achaparro** [comment]
Thanks @brianwulbern, please share the results you get in your local environment when your tests are finished.

**Comment by michaelhashimoto** [comment]
@brianwulbern - We are using the following version of ant on jenkins:
<pre>root@cloud-10-0-13-58:~> ant -version
Apache Ant(TM) version 1.9.4 compiled on April 29 2014</pre>

Please let us know if you have any other questions.  Thanks!

**Pull request closed without merging**
