### PR TITLE
LRQA-62407 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRQA-62407

This is only for master.

@david-gutierrez-mesa

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure case is not related to changes in PR.
See https://github.com/Tim-Cao/liferay-portal/pull/479
✔️ ci:test:stable - 7 out of 7 jobs passed
❌ ci:test:relevant - 28 out of 31 jobs passed in 1 hour 49 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5b335a225c...651a70c8c5

**Comment by brianchandotcom** [comment]
@Tim-Cao I backported this to 7.3.x

**Comment by Tim-Cao** [comment]
@brianchandotcom
I met issues when I backport to 7.3.x.
See https://github.com/Tim-Cao/liferay-portal-ee/pull/20 and https://github.com/brianchandotcom/liferay-portal-ee/pull/31821

**Comment by brianchandotcom** [comment]
@Tim-Cao it shoudln't auto close for you but should work like 7.2.x, we'll need to fix it.

@jpince knows about it and we should have it fixed by tomorrow.

Both need to work. You should be able to run ci forward, and/or send it to me directly.

**Comment by Tim-Cao** [comment]
Thanks

**Pull request closed without merging**
