### PR TITLE
Lps 54097

### PR DESCRIPTION
**Pull request by shuyangzhou**
@brianchandotcom This includes https://github.com/brianchandotcom/liferay-portal/pull/24618 to show the result as a whole.

CC @igorspasic I went ahead to make the fix to JSONWebServiceActionsManagerImpl, as it has became the top random failing reason in CI testing. Please double check my changes to make sure I did not break anything. Thanks!

CC @hhuijser, please see my last commit, it is for JSONWebServiceActionsManagerImpl line 164, "return new ArrayList<JSONWebServiceActionMapping>(jsonWebServiceActionConfigs);" We can not apply diamond operator here, as the actual type is expected type's sub-class, the generic auto capturing will catch the sub-class for <> causing compile error, we have to supply exact type here manually to help javac understand what is going on. This is a common case, we need a fix from SF. Please take a look on it, let me know if you need any more explanation, thanks!

### CODE REVIEW

**Comment by shuyangzhou** [comment]
CC @michaelhashimoto CI hangs on test-portal-acceptance-pullrequest-source(master) again see https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-source%28master%29/32/console, this has been happening a lot, can you do some digging to see what is going on? Thanks!

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by igorspasic** [comment]
Very nice! This actually also cleans up things, as we dont need a binary search any more, but just a ` Map<String, List<JSONWebServiceActionConfig>>`. Thank you @shuyangzhou sorry for not being able to reply earlier, i was flying back from other office!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cfe811bd77...12f2903cd6

**Comment by hhuijser** [comment]
Hey @shuyangzhou 

I am aware of this problem.

If you look at the other 4 excluded files in source-formatter.properties, you see that all of those are excluded for the same reason.
The problem is that with the way SF works now, it's impossible to catch this. For this case (JSONWebServiceActionsManagerImpl.java), it still would be somehow doable (although already very difficult), because jsonWebServiceActionConfigs is created within that method.
However, when the collection that is passed to the constructor is a global variable or (even worse, as we have in CMISRepository.java: 728-729) we retrieve it from a method, there is really no way to detect that.

So, we have two options:
1. We disable auto applying diamond operator for any case where a collection is passed in the constructor.
2. We leave as is and exclude using source-formatter.properties.

**Comment by shuyangzhou** [comment]
Sure, let's keep it excluded then. It's no big deal :)

**Pull request closed without merging**
