### PR TITLE
LRQA-52270 Create VerifyAllItemsFilterFromMetrics

### PR DESCRIPTION
**Pull request by barrosdennys**

### CODE REVIEW

**Comment by jpince** [comment]
@austinchiang fyi, change to Blogs#teardowncp. I know teardown failures don't always show up in testray

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/186aec6b07...40312c3628

**Comment by brianchandotcom** [comment]
@barrosdennys @austinchinag I still merged this because @jpince didn't tell me not to.

**Comment by brianchandotcom** [comment]
@barrosdennys see 8d7f65d

**Pull request closed without merging**
