### PR TITLE
LPS-72347

### PR DESCRIPTION
**Pull request by matethurzo**
hey @brianchandotcom we needed the last commit: https://github.com/brianchandotcom/liferay-portal/pull/50481/commits/8ab29a482ee51fdb39ebd75a4f47a46221b04f4e

because there is an actual bug in the baseline, and it's generating breaking changes while it shouldn't. @rotty3000 is working on fixing it, once he has that we will be rolling the last commit back.

Thanks!

### CODE REVIEW

**Comment by matethurzo** [comment]
@brianchandotcom the SF error is unrelated

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/dc32b2db6c...5cb0b3cd3d

**Comment by brianchandotcom** [comment]
@matethurzo @danielkocsis I backported this for you guys.

**Comment by matethurzo** [comment]
thanks @brianchandotcom

**Pull request closed without merging**
