### PR TITLE
LPS-77727 DDM Service exports

### PR DESCRIPTION
**Pull request by Preston-Crary**
@shuyangzhou this completes DDM service exports refactoring see cd30d5f

@topolik this applies the new model resource permission pattern to DDM

@rafaprax overall it looked good to me, please double check 1ce54bf...cd30d5f.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by Preston-Crary** [comment]
Didn't check modules private before doing 3cf1113.

@rafaprax please reapply f7fe282...cd30d5f once modules private has been updated.

Please see https://github.com/brianchandotcom/liferay-portal/pull/57056

**Comment by rafaprax** [comment]
ci:reopen

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
ci:close

**Pull request closed without merging**
