### PR TITLE
LPS-184016 - Update for new FDS Filter client extension

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Hey @brianchandotcom this is a follow up from what we talked about earlier today.

The other changes I talked about with the samples and refresh script can be found here, 
https://github.com/liferay-frontend/liferay-portal/pull/3467. I am just waiting on CI for that

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
ci:reopen

**Comment by bryceosterhaus** [comment]
wrong branch

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/96cb1fc2d1...ea8a771cd3

**Comment by brianchandotcom** [comment]
@bryceosterhaus see 705c10213488df33bc53b2cef37aefa7c08ba9d3 can you also fill out ea8a771cd306835e6a86be0c548f068a06c2d8f5

**Comment by brianchandotcom** [comment]
@bryceosterhaus my bad, wrong hashes. See 6bc4684fd3901ee78054b2c4d9ded131af1041f9 and 3f12cff4a3e3f84a784c6387929e2a747111419e

**Pull request closed without merging**
