### PR TITLE
LPS-152541 BindSegmentsCompanyConfigurationMVCActionCommandTest

### PR DESCRIPTION
**Pull request by jkappler**
- LPS-152541 Added test for newly created ActionCommand
- LPS-152541 Make test more resilient by setting the configuration for a new company, and also deleting it before every run. Also, change so that we get the configuration just like we do in SegmentsConfigurationProviderImpl
- LPS-152541 Simplify by using CompanyConfigurationTemporarySwapper

### CODE REVIEW

**Comment by jkappler** [comment]
ci:reopen

**Comment by jkappler** [comment]
Relevant tests passed, please see https://github.com/liferay-tango/liferay-portal/pull/2703

**Comment by jkappler** [comment]
@cgoncas

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/450ae3a3d2...686e31a24a

**Comment by brianchandotcom** [comment]
@YurenaC @jkappler see c831177e468a61df3d061abadfc98a3922fe2507 b34ce30a4e271f521f80abb15864e7d0ff60e9b5 and 686e31a24a6615aa5be87466ec095e6f4e13b4e9

**Pull request closed without merging**
