### PR TITLE
LPS-79257

### PR DESCRIPTION
**Pull request by matethurzo**
@ealonso as discussed earlier we have developed single asset publish for journal - articles and folders.

the actual journal change is minimal, we tried to develop as many APIs as we could. If you have any questions let us know!

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test

**Comment by jpince** [comment]
ci:retest

**Comment by jpince** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d7ed2b8799...9617ddf318

**Pull request closed without merging**
