### PR TITLE
LPS-60894 Make string representation of Query instances more informative for debugging purposes

### PR DESCRIPTION
**Pull request by arboliveira**
Re-sending, addressing https://github.com/brianchandotcom/liferay-portal/pull/45861#issuecomment-269733495. Sorted all keys in toString methods, adding the className as a key like the others. Thanks!

(Curious.... any reason there isn't a simple, concise `StringUtil.concat` varargs method?)

`return StringUtil.concat("{className=", className, ", queryTerm=", _queryTerm, "}");`

Author: @Preston-Crary 
Reviewer: @arboliveira

cc @brandizzi

https://issues.liferay.com/browse/LPS-60894

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:reopen

Unrelated Sybase failures.

`com.sybase.jdbc4.jdbc.SybSQLException: There is not enough procedure cache to run this procedure, trigger, or SQL batch. Retry later, or ask your SA to reconfigure ASE with more procedure cache.`

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@shuyangzhou see how in this same pull the Journal test broke once for Sybase but passed the other time. Very flaky?

**Comment by brianchandotcom** [comment]
@juliocamarero Sybase test for Journal is flaky. See this pull and my comment to @shuyangzhou 

I've seen the Sybaes Journal test break a few times in other pulls too.

**Comment by juliocamarero** [comment]
cc @ealonso

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/357ed46fca...50d83d6da2

**Comment by brianchandotcom** [comment]
@arboliveira thanks! Please backport as you see fit.

**Comment by brianchandotcom** [comment]
@arboliveira I went ahead and backported since it's a CI issue and cherry picks nicely.

**Pull request closed without merging**
