### PR TITLE
LPS-74374 SF

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@shuyangzhou SecureXMLFactoryProviderImplTest.testNewXMLInputFactory is breaking consistently now with an OOM

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b7b0818545...9c42657c07

**Comment by brianchandotcom** [comment]
@jbalsas please see my changes in upstream. Thx.

**Comment by jbalsas** [comment]
Looks good! Thanks @brianchandotcom!

**Pull request closed without merging**
