### PR TITLE
LPS-92553 Baseline

### PR DESCRIPTION
**Pull request by jkappler**
Hey @brianchandotcom, as I mentioned yesterday, I was trying to change the classes to Asset*Info*Display... but it will break backwards compatibility with 7.1. 

Also, we are going to refactor this to remove getClassTypeFields in a follow up pull. But we didn't want to lose backwards compatibility so we left it like this for the moment

Thanks

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by brianchandotcom** [comment]
@jkappler I'm looking at this some more.. let's just break backwards compat? It's really only used internally

Type: "git grep AssetDisplayField"

Sorry, please resend! Thx.

**Comment by brianchandotcom** [comment]
Skype me? brianchan_dot_com

**Comment by brianchandotcom** [comment]
modules/apps/asset/asset-display-api/bnd.bnd is already a 2.0.0

Let's kill that module and make a new

asset-info-display-api which will be a 1.0.0

**Pull request closed without merging**
