### PR TITLE
LPS-67509 support for UTF-8 friendly URL for pages

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
@anthony-chu is this bug real? we now allow to create friendly urls for pages with characters such as: ñ, á, 昨... etc

**Comment by anthony-chu** [comment]
@juliocamarero I think this might be a validation issue with poshi. I'll take a look into it. @brianchandotcom This is safe to merge.

**Comment by anthony-chu** [comment]
@liulukiwi @GinsonRen @brianwulbern @koor4356 This allows friendlyURLs with utf8 character encoding.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3f9ae2a21d...4132b7efb5

**Comment by shuyangzhou** [comment]
This is going to hurt performance, the logic should not be done this way, it can be simpler. And it is missing the upgrade support to fix exist database data.
@Preston-Crary is going to send out a follow up change to fix the performance issue, we will leave the upgrade logic to @jkappler @stian-sigvartsen and @juliocamarero 

Next time for a complex algorithm change, please loop us in first to do a performance evaluation before sending it to @brianchandotcom .

**Comment by juliocamarero** [comment]
Hey @shuyangzhou 

there is probably a miscommunication or misunderstanding here since that is what we did :)
we have sent you an email about it, thank you!

**Comment by shuyangzhou** [comment]
Yes, thanks @juliocamarero , just replied, please check the email.

**Pull request closed without merging**
