### PR TITLE
LPS-98489 Show edited label when comments are edited

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
@p2kmgcl 
@4lejandrito

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5945a59125...27c74b7601

**Comment by brianchandotcom** [comment]
@victorg1991 please send me a backport. Thx.

**Comment by brianchandotcom** [comment]
@4lejandro fyi, I asked @victorg1991 for a backport since it does not CP

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal-ee/pull/25585.

@brianchandotcom, @victorg1991, @p2kmgcl.

**Pull request closed without merging**
