### PR TITLE
LPS-65385

### PR DESCRIPTION
**Pull request by Ithildir**
Hi Brian and @shuyangzhou!

I found this PMD violation in master:

> java.lang.AssertionError: [projects/github/liferay-portal/modules/util/pmd/../../../modules/apps/foundation/portal/portal-split-packages-test/src/testIntegration/java/com/liferay/portal/split/packages/test/SplitPackagesTest.java:151: Do not call Assert#fail improperly.]

I'm not sure this is the best way to fix it...

### CODE REVIEW

**Comment by shuyangzhou** [comment]
Ugh, it should be moving the entire if condition block into the Assert.assertFalse().

**Comment by Ithildir** [comment]
It thought it too... but isn't it way too long?

**Comment by shuyangzhou** [comment]
That's what the PMD rule is expecting. But anyway, use a variable works too. I am ok with either way. Thanks @Ithildir !

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
