### PR TITLE
LPS-74672 Move ImageRequestTokenUtil to the same package as DocumentHTMLProcessor

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Hey @IstvanD can you verify I didn't break anything with the package renaming?
Thanks!

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a959317d66...b88d087e46

**Comment by brianchandotcom** [comment]
@ithildir can you review modules/apps/collaboration/document-library/document-library-document-conversion/build.gradle

@sergiogonzalez beautiful. Thx.

**Comment by Ithildir** [comment]
`modules/apps/collaboration/document-library/document-library-document-conversion/build.gradle` looks good to me 👍

**Pull request closed without merging**
