### PR TITLE
LPS-66064

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
I think it fails because the EE modules still use `-liferay-includeresource`. Please tell me when EE is synced, so I can send you the `bnd.bnd` changes.

Thank you!

**Comment by brianchandotcom** [comment]
ci:retest (I synced ee-7.0.x modules)

**Comment by brianchandotcom** [comment]
@pyoo47 can you investigate this? thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c42abc5dd4...9e55f3667b

**Comment by pyoo47** [comment]
I tracked this down to a single axis that for some reason timed out. The log doesn't show any failures. It appears to have been in the middle of building the bundle when it timed out. I can only speculate that the VM froze for some reason that was external to the ant build.

```
    [exec] :core:registry-api:classes
     [exec] 
     [exec] BUILD SUCCESSFUL
     [exec] 
     [exec] Total time: 18.709 secs
     [exec] 

compile:
     [copy] Copying 363 files to /opt/dev/projects/github/liferay-portal/portal-kernel/classes
    [javac] Compiling 4208 source files to /opt/dev/projects/github/liferay-portal/portal-kernel/classes
Build timed out (after 120 minutes). Marking the build as aborted.
Build was aborted
Recording test results
Liferay patched class hudson.tasks.junit.JUnitResultArchiver
```


https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/7026/AXIS_VARIABLE=5,label_exp=!master/consoleFull

**Pull request closed without merging**
