### PR TITLE
LPS-56383 Move verifyLayout logic to module

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
Real bug, go to the build log see the full tomcat output dump for more info.

**Comment by brianchandotcom** [comment]
@epgarcia please resend. See Shuyang's comment. Thx.

**Pull request closed without merging**
