### PR TITLE
LRQA-52830 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-52830

### CODE REVIEW

**Comment by kyle-miho** [comment]
@JoyceWang08211 fyi, you missed one so i removed it for you

@brianchandotcom this test needs to be temporarily ignored due to a bug causing this to fail, this is causing a lot of upstream noise. https://issues.liferay.com/browse/LPS-84715

**Comment by JoyceWang08211** [comment]
@kyle-miho Thanks for the fix.

**Comment by brianchandotcom** [comment]
Thx @kyle-miho

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/76f1d31095...2f9c70b939

**Pull request closed without merging**
