### PR TITLE
LPS-71326 Search portlet issues 3 identical sets of search queries per search

### PR DESCRIPTION
**Pull request by arboliveira**
Author: @ehan 
Reviewer: @arboliveira

https://issues.liferay.com/browse/LPS-71326

### CODE REVIEW

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@arboliveira can you see how we usually cache display context objects? Don't we usually put them in *Constants.

If you see an instance of that, please follow that. If none, then let's follow the pattern from @ehan and we'll use the class name.

Merged.

**Comment by arboliveira** [comment]
Will do, thanks Brian!

**Pull request closed without merging**
