### PR TITLE
LPS-82343

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
@jpince, don't think I am causing the failures... only adding category titles to language files

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@hhuijser not merging, modules shoudln't have categories. PLease resend.

**Comment by jpince** [comment]
@hhuijser yes, errors look unrelated

**Pull request closed without merging**
