### PR TITLE
LRQA-39312 Build Object Model changes for test-source-format

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-39312

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test

**Comment by pyoo47** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c8d39d5166...d6c36457ad

**Comment by brianchandotcom** [comment]
@pyoo47 published.

**Pull request closed without merging**
