### PR TITLE
LPS-71842 Update bnd.bnd to mimic the already existing portal-scripting-groovy

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
Not merging, per @mhan810

**Comment by mhan810** [comment]
@ChrisKian @rotty3000 we shouldn't pull all the scripting engines into JS.  All of our scripts should be using Groovy instead of JS.

We don't want to bring Ruby, JS, etc into the engine.  The guidance for customers should be for them to install other engines if they need.

**Comment by rotty3000** [comment]
Wasn't this change only repo structuring?

**Comment by brianchandotcom** [comment]
@rotty3000 by moving it to foundation, it'll be included as part of the release.

@mhan810 wants it purely as a Marketplace download. I think we just need to tell the Marketplace team to upload it and for ppl to download it @ChrisKian

**Comment by rotty3000** [comment]
If we don't want to deploy these by default, don't add a profile marker file to the modules. All they need to do is remove the `.lfrbuild-portal` files.

**Comment by brianchandotcom** [comment]
If they remove the .lfrbuild-portal but put it inside the foundation dir, there will be no way to release them on Marketplace.

Marketplace assumes a directory with one "app.bnd". Foundation already has an app.bnd. We could change it, but it would be a lot of work.

**Comment by rotty3000** [comment]
got it!

**Pull request closed without merging**
