### PR TITLE
LPS-86199 Master Only | master

### PR DESCRIPTION
**Pull request by vicnate5**
Master only https://issues.liferay.com/browse/LPS-86199

### CODE REVIEW

**Comment by yichenroy** [comment]
PR tests kicked off manually

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@vicnate5 should there even be NPM tests in 7.1.x? We still have them there right now.. but seems a bit stale.

**Comment by vicnate5** [comment]
Will take care of the stale tests

**Pull request closed without merging**
