### PR TITLE
LPS-95815 Enhance error reporting

### PR DESCRIPTION
**Pull request by izaera**
Comments regarding CI testing:

> The compilation failure is very strange because I ran an `ant all` to test the feature and everything went well... :thinking: 

> Also, I haven't touched that part.

### CODE REVIEW

**Comment by izaera** [comment]
ci:test

**Comment by izaera** [comment]
The compilation failure is very strange because I ran an `ant all` to test the feature and everything went well... :thinking:

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8e53073122...b9c97043ef

**Comment by brianchandotcom** [comment]
Oh yeah.. that one was @ealonso but we've since fixed it.

**Pull request closed without merging**
