### PR TITLE
LPS-91307 Upgrade UserGroup.name field to 255

### PR DESCRIPTION
**Pull request by achaparro**
cc/ @jonathanmccann

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
Errors in test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/5 seem not to be related. The new upgrade process passed succesfully and the error is related to DDM.

cc/ @jonathanmccann

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@achaparro @jonathanmccann can you guys fix:

```
	<target name="build-upgrade-table">
		<if>
			<not>
				<equals arg1="${upgrade.table.dir}" arg2="" />
			</not>
			<then>
				<antcall target="prepare-upgrade-table" />

				<path id="upgrade.table.builder.classpath">
					<fileset
						dir="${sdk.dir}/dependencies/com.liferay.portal.tools.upgrade.table.builder/lib"
						includes="*.jar"
					/>
				</path>

				<java
					classname="com.liferay.portal.tools.upgrade.table.builder.UpgradeTableBuilder"
					classpathref="upgrade.table.builder.classpath"
					fork="true"
					newenvironment="true"
				>
					<arg value="upgrade.base.dir=." />
					<arg value="upgrade.osgi.module=false" />
					<arg value="upgrade.release.info.file=../portal-kernel/src/com/liferay/portal/kernel/util/ReleaseInfo.java" />
					<arg value="upgrade.table.dir=${upgrade.table.dir}" />
				</java>
			</then>
		</if>
	</target>
```

in build.xml? Right now, I have to know to run 

```
build-upgrade-table -Dupgrade.table.dir=src/com/liferay/portal/upgrade/v7_1_x/util/
```

It should know to do it automatically for all the upgrade 7_*x dirs right?

Or at least do it for the version prior to what I'm currently on.

Merged, but we need to make the usage of build.xml more dummy proof. Thx.

**Comment by achaparro** [comment]
Hey @jonathanmccann, can you take care of it? If not, I can try to get some time next week.

Thanks.

**Pull request closed without merging**
