### PR TITLE
LPS-65375 when creating new versions of journal articles, ensure the version is higher than the one in live too

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @matethurzo fyi

**Comment by matethurzo** [comment]
@jorgediaz-lr @juliocamarero have you considered remote staging? the livegroup in that case will fall back to the staging site, so that might require some extra attention

**Comment by jorgediaz-lr** [comment]
@matethurzo in case of remote staging we cannot easily obtain that information without calling remote server.
The root issue of this LPS are inconsistent data from Liferay 6.0 upgrades, but it is a corner case for new contents created at 7.0.
As this issue is a corner case and it is very difficult to retrieve remote data, we decided to fix only Staging Local.

**Comment by matethurzo** [comment]
@jorgediaz-lr ok I was thinking that might be the case. I just wanted to make sure that the solution is not making regression for remote staging. Thanks for the explanation

**Comment by jorgediaz-lr** [comment]
In case of remote staging *group.getLiveGroupId();* will return zero and the live version will be ignored

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0e9def3e0b...52f4dcd81d

**Comment by brianchandotcom** [comment]
@jorgediaz-lr I made a bunch of changes on upstream. Please review. thx.

**Pull request closed without merging**
