### PR TITLE
LPS-72285 Search fails in Documents and Media

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by jpince** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2a655569e5...7c5af9277b

**Comment by mbowerman** [comment]
@brianchandotcom @jpince The deletion of settings.gradle in https://github.com/brianchandotcom/liferay-portal/commit/7c5af9277b58fe088622ecaf2700efedb3304ede appears to be causing [this test failure](https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/111915/testReport/com.liferay.portal.modules/ModulesStructureTest/testScanBuildScripts/), which is causing pull requests to be automatically closed. Can we please get that file added back in?

**Comment by mbowerman** [comment]
@brianchandotcom @jpince @adolfopa Please see https://github.com/brianchandotcom/liferay-portal/pull/48783

**Pull request closed without merging**
