### PR TITLE
LPS-61491 Forward to the uppercase locale also when the friendly URL is invalid

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/66109fd739...b2e400355c

**Comment by brianchandotcom** [comment]
@giros can we add a test for this? Thx.

**Comment by brianchandotcom** [comment]
@giros we already have many tests for this class and for URLs, so it should be just adding a method to an existing test.

**Comment by giros** [comment]
I'll work on it, thanks Brian!

**Pull request closed without merging**
