### PR TITLE
LPS-62918 revert the change: holding response in tags causes extensio…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…n of response lifecycle, which results in much heavier old generation GC

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@shuyangzhou we're having random test failures with Journal.. I think it may have to do with some tests "shifting" so they were green and suddely started breaking. If you have time, can you take a look? Feel free to just push up (otherwise EU will send me lots of broken pulls)

Thx

**Comment by brianchandotcom** [comment]
Here's a sample https://github.com/brianchandotcom/liferay-portal/pull/36422

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1ff83ab445...675cc19a14

**Comment by shuyangzhou** [comment]
Sure, I will be out of office tomorrow, but I will try to get them fix tonight.

**Pull request closed without merging**
