### PR TITLE
LPS-89202 Move debug message to exception and wordsmith

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:relevant @brianchiu @kyle-miho

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/13ef14527b...80a2bab6d5

**Pull request closed without merging**
