### PR TITLE
LPS-70058

### PR DESCRIPTION
**Pull request by lionah**
Add for new DB sharding feature based on companyId. Possible backport for 7.0.x if it can be added without messing up version numbers. Will not back port to other versions.

### CODE REVIEW

**Comment by lionah** [comment]
@jpince, could you take a look at this one? I'm not sure what the failure is here.

**Comment by lionah** [comment]
ci:retest

**Comment by lionah** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@lionah just your pulls bro...

**Comment by jpince** [comment]
@lionah sorry, I should have looked at this more closely earlier. you have a semver issue with marketplace-service, maybe you forgot to change a reference from group to project?
```
     [exec] 01:58:30,235 WARN  [fileinstall-/opt/dev/projects/github/liferay-portal/bundles/osgi/modules][org_apache_felix_fileinstall:103] Error while starting bundle: file:/opt/dev/projects/github/liferay-portal/bundles/osgi/modules/com.liferay.marketplace.store.web.jar 
     [exec] org.osgi.framework.BundleException: Could not resolve module: com.liferay.marketplace.store.web [400]
     [exec]   Unresolved requirement: Import-Package: com.liferay.marketplace.service; version="[3.0.0,4.0.0)"
```

**Comment by lionah** [comment]
No problem @jpince. But where did you find that line its no where here...

**Pull request closed without merging**
