### PR TITLE
LPS-63735 add missing models in the verify process

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @migue

**Comment by juliocamarero** [comment]
fyi @epgarcia

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2eec633088...6b8d903e00

**Pull request closed without merging**
