### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
fyi @izaera

**Comment by hhuijser** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1483588ec3...c18342e34d

**Comment by izaera** [comment]
@hhuijser I'm not maintaining this any more as I'm in the frontend infra team. CCying @adolfopa.

**Pull request closed without merging**
