### PR TITLE
LPS-78665 Apply it for all upgrades in this module. WARN is enough in this case

### PR DESCRIPTION
**Pull request by achaparro**
Hi @mbowerman,

Please, take a look at the changes, taking into account your comment in https://issues.liferay.com/browse/LPS-78665:

> What we can do instead of throwing an Exception, is simply configure the Web Content Display Portlet on the page to point to an invalid resourcePrimKey (such as -1). This will cause the Web Content Display portlet to not display any Web Content, which is the same behavior that was occurring in the pre-upgrade environment. Additionally, we can log a warning to let the user know that the Web Content that the page is pointing to could not be found.

What we need is to configure an empty WCD portlet, so it is enough to store empty preferences.

Let me know if you see any drawback to this

Thanks!

cc/@SamZiemer

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test

**Comment by achaparro** [comment]
ci:close

@mbowerman I will think more about your pull tomorrow. I guess you want that the WCD shows "the article is not longer available, please select another one" right?

**Comment by achaparro** [comment]
ci:close

**Comment by mbowerman** [comment]
Hi @achaparro,

Yeah, that was my idea. Maybe storing a null portletPreferences makes more sense though. I didn't know about the legacy records.

**Comment by achaparro** [comment]
Pull request sent, please see:
https://github.com/brianchandotcom/liferay-portal/pull/56192

**Pull request closed without merging**
