### PR TITLE
Lps 75609

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@brianchandotcom please don't backport this.

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2651a46c40...4ea3e9fb12

**Comment by brianchandotcom** [comment]
@mtambara can you send me backport to 7.0.x? Thx. @shuyangzhou

**Comment by shuyangzhou** [comment]
@brianchandotcom this one is not supposed to be backported.

**Comment by shuyangzhou** [comment]
Wait, this module seems have never been released. Does that mean we can backport it?

**Comment by mtambara** [comment]
@brianchandotcom It looks like the document library conversion module doesn't exist in 7.0.x, so I won't backport this change

**Pull request closed without merging**
