### PR TITLE
LPS-54927 SF

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@marcellustavares test SF error, and doesn't rebase. Please resend. Thx.

**Comment by marcellustavares** [comment]
Resent to https://github.com/brianchandotcom/liferay-portal/pull/26484

Thanks

**Pull request closed without merging**
