### PR TITLE
master-vw-496

### PR DESCRIPTION
**Pull request by vicnate5**
@brandizzi

### CODE REVIEW

**Comment by vicnate5** [comment]
Poshi failures due to https://issues.liferay.com/browse/LPS-67594

**Comment by brianchandotcom** [comment]
@vicnate5 do we have an ETA for fixing those poshi errors from LPS-67594?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/aab5ab3f0d...05343c0ad8

**Comment by vicnate5** [comment]
@brianchandotcom Here is the temp fix https://github.com/brianchandotcom/liferay-portal/pull/42333. It is a regression, not a poshi issue.

**Pull request closed without merging**
