### PR TITLE
LPS-77502 Makes add_menu dropdown appear below the button

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ccb42e283d...2febf8a2a5

**Comment by brianchandotcom** [comment]
Nice job @jbalsas !

**Comment by brianchandotcom** [comment]
@jbalsas can you imagine if we had to do this and these were all subrepos?

**Comment by jbalsas** [comment]
I can imagine @brianchandotcom, yeah... luckily we just need to imagine it 😂

**Pull request closed without merging**
