### PR TITLE
LPS-79234

### PR DESCRIPTION
**Pull request by Ithildir**
Hi,
Please let this pull finish. Also, can you please publish a new `gradle-plugins-workspace`?

Thank you!

cc @timpak, @gamerson

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:test

**Comment by Ithildir** [comment]
ci:reopen

**Comment by Ithildir** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@Ithildir done, published new gradle-plugins-workspace.

**Pull request closed without merging**
