### PR TITLE
LPS-69537 buildLang

### PR DESCRIPTION
**Pull request by marcellustavares**
cc @fernandosouza

### CODE REVIEW

**Comment by vicnate5** [comment]
Needs a poshi update

**Comment by marcellustavares** [comment]
@vicnate5, can you get from my branch?

**Comment by marcellustavares** [comment]
ci:close

**Comment by vicnate5** [comment]
@marcellustavares yes

**Comment by vicnate5** [comment]
Resent with test fix: https://github.com/brianchandotcom/liferay-portal/pull/45426

**Pull request closed without merging**
