### PR TITLE
LPS-75289 using random string

### PR DESCRIPTION
**Pull request by linolaoj**
cc: @brandizzi

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 all my pulls are breaking, any idea why? @ithildir can you talk to @caustin582?

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2abf0701a5...29a350d210

**Comment by brianchandotcom** [comment]
@linolaoj do you have to use "Subject" or can that be random too? Please send a follow up pull if it can. Merged what you sent me. Thx.

**Comment by linolaoj** [comment]
@brianchandotcom, we have to use "Subject" on MailServiceTestUtil.getMailMessages because it is a header name from the mail message.
Thanks!

**Pull request closed without merging**
