### PR TITLE
LRQA-59120 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRQA-59120

This is only for master.

@manoelcyreno

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
Revert commits to resolve conflict since someone fix them earlier. See https://github.com/brianchandotcom/liferay-portal/pull/89593

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources more than they already are, I'm sending the PR directly.
See https://github.com/Tim-Cao/liferay-portal/pull/230 Failure task is probably caused by other reason not related to poshi tests.
✔️ ci:test:stable - 19 out of 19 jobs passed
❌ ci:test:relevant - 73 out of 75 jobs passed in 1 hour 57 minutes

**Comment by jpince** [comment]
Just started reviewing :)

**Comment by jpince** [comment]
@Tim-Cao merge conflict when I tried to manually cherry-pick this onto Brian Chan's origin, can you please look into it?
```
CONFLICT (content): Merge conflict in modules/dxp/apps/portal-workflow/portal-workflow-metrics-test/src/testFunctional/macros/WorkflowMetrics.macro
error: could not apply 73b0b16f40ef... LRQA-59120 Modify macros to navigate to site scope apps
```
It might be a conflict with https://github.com/brianchandotcom/liferay-portal/pull/89584 that I'm trying to merge right now, but I'm not sure.

**Comment by Tim-Cao** [comment]
@jpince It's weird. I've added revert commit to resolve that issue. See https://github.com/brianchandotcom/liferay-portal/pull/89595/commits/d64ca5ad2dab42aec09303d51e2b7a748b363f22

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
