### PR TITLE
LPS-77111

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@brianchandotcom, don't even try cherry-picking the last 2 commits to 7.0.x
I'll send you a pull request for the backport: brianchandotcom/liferay-portal-ee#19180

**Comment by hhuijser** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3598ffe657...1da60c796a

**Comment by brianchandotcom** [comment]
Thx @hhuijser  :) for the backport help.

**Pull request closed without merging**
