### PR TITLE
LPS-97278,LPS-97533,LPS-97537 Change Tracking

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:test @Preston-Crary I think those are real errors in CI...

**Comment by Preston-Crary** [comment]
Hi @vicnate5,

can you help with this one?  We really want to get this one in but only if it's safe.  Some of the test failures looked like they is something wrong with the CI and didn't fail on the 2nd test run.  I'm not great at reading the functional test results and it's difficult for me to look at upstream results from Hungary.

PortletTitleTest is not caused by this.
RenderFragmentEntryStrutsActionTest should not be caused by this change.
Bundle blacklist has nothing to do with our changes.
DBInspectorTest shouldn't be affected either.
BlogsEntrySharingTest only failed on some batches.
ModuleBuildAutoUpgradeTest also should not be breaking from these changes.
SF was passing locally.

That leaves the functional test failures that I'm not sure about.  If they are caused by this can you close this pull and post the steps here so the staging team can debug the failure while I'm on PTO next week?

Thanks!

**Comment by brianchandotcom** [comment]
@vicnate5 can you let @Preston-Crary  know if it's safe?

@Preston-Crary I didn't want to merge it while you were on vacation. Also, conflict error. Please resend when you're back. Thx!

**Comment by vicnate5** [comment]
@kmaria @danielkocsis Can someone on the team rebase this week?

The only functional failure that worries me is https://testray.liferay.com/home/-/testray/case_results/648467869 as change list did not activate in this case. It might be good to rebase and re-run the tests.

CC @Preston-Crary

**Comment by Preston-Crary** [comment]
@danielkocsis functional test failure is just asserting that the success message pops up when enabling change tracking? Did you guys get a chance to double check that yet?

**Comment by vicnate5** [comment]
@Preston-Crary rebased and re-tested here https://github.com/danielkocsis/liferay-portal/pull/841

Results were good.

**Comment by danielkocsis** [comment]
Hi @Preston-Crary,

actually the preferences local service change made this behaviour change, because before the refactor the default value of this setting was manually set to true, but after the default value is the default value of boolean which is false. We might need to adjust this later.

thanks,
Daniel

**Comment by Preston-Crary** [comment]
@vicnate5 thanks for your help on this

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/75430

**Pull request closed without merging**
