### PR TITLE
Lps 58039

### PR DESCRIPTION
**Pull request by shuyangzhou**
@mhan810 @alee8888

This is more like a workaround, but it is an once for all solution. We have a lot of lazily created resource on the first hit. In case of concurrent hits on startup, there is a good chance we see some tx got rollback in the console, which is technically correct, but giving users a very bad first impression. Because there are too many of similar situations, it is impractical to fix them one by one.

The solution is, in a StartupAction, we register an one time only filter. It behaves as a gate keeper to ensure no concurrent hits for the first hit. After the first hit is done, it releases all blocked concurrent hitters and unregister itself, so after the initial hit there will be no further runtime performance price to pay for doing this.

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/738dabee95...b8dc7273e8

**Comment by brianchandotcom** [comment]
@mtambara your first commit had the wrong LPS-58093 vs. LPS-58039 (cut and paste is your friend)

@shuyangzhou any way for this to have been in its own module?

**Comment by shuyangzhou** [comment]
Yes, it can be. I just wanted to keep it simple. If you want it be pulled out, I can have @mtambara on it tomorrow.

**Pull request closed without merging**
