### PR TITLE
LPS-65936 Replace usages of Social Office theme

### PR DESCRIPTION
**Pull request by adolfopa**
@brianchandotcom This is an extra module that provides a GoGo command to execute optional cleanup actions for Social Office. We're not including these in the upgrade because some users may choose to execute different actions (or not execute them at all).

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
Rebased and push-forced.

**Comment by adolfopa** [comment]
ci:retest

**Comment by adolfopa** [comment]
Rebased and removed some logic that wasn't deemed necessary. ci:retest

**Comment by JorgeFerrer** [comment]
@adolfopa @sergiogonzalez I talk to Brian about this and he mentions he is confused with the naming of the modules and apps. Maybe I can help you review the names.

**Comment by brianchandotcom** [comment]
@adolfopa the confusing thing for me was,

app is named "Social Office"  (but it's not really SO, but just the upgrade)

But the module and class names are also different. One is SOUpgrade, the other is SOOptionalUpgrade. So is it optional or not?

I think you should rename the app itself to "social-office-upgrade" and then show in the command line they are all optional.

Also, I find it weird they are called "action". Can you look at our other shells and see what we call them? We have another module with shell customizations in it already and I'd like all of them to fit some common pattern.

Thx!

**Pull request closed without merging**
