### PR TITLE
LPS-98533 Similar Results Widget

### PR DESCRIPTION
**Pull request by arboliveira**
**❌ ci:test:search - 44 out of 46 jobs passed in 1 hour 22 minutes 288 ms**
https://github.com/arboliveira/liferay-portal/pull/782#issuecomment-547078980

*This pull contains no unique failures.*

----

Authors: @wcao20170619 @thektan @arboliveira
Reviewer: @arboliveira

_[Story] Similar Results Widget_
https://issues.liferay.com/browse/LPS-98533

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1388ce80ec...4374f01c8c

**Comment by brianchandotcom** [comment]
Woooo smells so nice  @arboliveira  Good job.

**Comment by brandizzi** [comment]
lpm:backport

**Comment by brandizzi** [comment]
lbm:backport

**Pull request closed without merging**
