### PR TITLE
LPS-86806

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@brianchandotcom, please publish `java-parser` and `SF`

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
SF failure can be ignored 'JavaIfStatement` has been removed on latest SF already

**Comment by brianchandotcom** [comment]
Published. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/43bc4822b2...17cf7d5beb

**Pull request closed without merging**
