### PR TITLE
LPS-93194 Refactor exeptions to avoid confusion with service builder generated exceptions

### PR DESCRIPTION
**Pull request by matethurzo**
@brianchandotcom did the wordsmith and refactored the exceptions so they are not confused with the SB ones cc @danielkocsis

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test:change-tracking

**Comment by matethurzo** [comment]
ci:reopen

**Comment by matethurzo** [comment]
compile error is unrelated

**Comment by brianchandotcom** [comment]
@matethurzo the problem with your naming scheme is that CT* is what a service builder error exception is expected to be.

For example, in modules/apps/knowledge-base/knowledge-base-service/service.xml

```
	<exceptions>
		<exception>DuplicateKBFolderName</exception>
		<exception>InvalidKBFolderName</exception>
		<exception>KBArticleContent</exception>
		<exception>KBArticleImport</exception>
		<exception>KBArticleParent</exception>
		<exception>KBArticlePriority</exception>
		<exception>KBArticleSourceURL</exception>
		<exception>KBArticleStatus</exception>
		<exception>KBArticleTitle</exception>
		<exception>KBArticleUrlTitle</exception>
		<exception>KBCommentContent</exception>
		<exception>KBFolderParent</exception>
		<exception>KBTemplateContent</exception>
		<exception>KBTemplateTitle</exception>
		<exception>NoSuchKBArticleSelector</exception>
	</exceptions>
```

And even in your own code, as I tried to point out last time, even in this latest pull, you have DuplicateCTEntry (note CT)

```
	<exceptions>
		<exception>CollectionDescription</exception>
		<exception>CollectionName</exception>
		<exception>DuplicateCTEntry</exception>
	</exceptions>
```

So I'm expecting your ServiceBuilder exceptions to be *CT* just as we do it for *KB* for knowledge-base.

The same is true for modules/apps/segments/segments-service/service.xml

```
	<exceptions>
		<exception>RequiredSegmentsEntry</exception>
		<exception>SegmentsEntryCriteria</exception>
		<exception>SegmentsEntryKey</exception>
		<exception>SegmentsExperiencePriority</exception>
	</exceptions>
```

For your non Service Builder exceptions, they really need to go in a separate package to not be lumped in with the generated Service Builder ones.. or share the exceptions or come up with a naming scheme that clearly separates them.

Suppose you call your other exceptions SomethingException. Then you could have AaaSomethingException or BbbSomethingException so long as *SomethingException is never confused with a *CT*Exception* that we would expect a Service Builder exception to be. Please resend. Thx.

**Comment by brianchandotcom** [comment]
@danielkocsis in case @matethurzo is out on vacation. Please resend based on my comments in this pull. 


@danielkocsis you may also want to reference https://github.com/brianchandotcom/liferay-portal/pull/72680 for history.

**Pull request closed without merging**
