### PR TITLE
[TS] LPS-162351 | Page configuration does not save after the default language of the site was changed

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-162351

@bakayattila

### CODE REVIEW

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See [liferay-echo#7560](https://github.com/liferay-echo/liferay-portal/pull/9552)

:heavy_check_mark: ci:test:stable - 26 out of 26 jobs passed
:x: ci:test:relevant - 128 out of 184 jobs passed in 1 hour 27 minutes

**Comment by ozysouza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8348d5be83...4eeb75ab6a

**Comment by brianchandotcom** [comment]
@bakayattila @ozysouza add an integration test please. Someone added that block of code for a reason. I don't want them to readd it without breaking your test.

**Pull request closed without merging**
