### PR TITLE
LPS-71267 | master

### PR DESCRIPTION
**Pull request by sharonchoi**
https://issues.liferay.com/browse/LPS-71267

cc: @daviddotzhang @sergiogonzalez

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@sharonchoi master only?

**Comment by sharonchoi** [comment]
@brianchandotcom no, we will send a backport via the BPR process, as this pull includes a bug fix, in addition to the test fix

cc: @daviddotzhang @sergiogonzalez

**Pull request closed without merging**
