### PR TITLE
LPS-95199 Buildlang

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
/cc @JorgeFerrer @jkappler

@jpince thanks for the semver alert, a copy-paste error, it is a completely new module and there could be no 3.0.0 version, fixed.

**Comment by brianchandotcom** [comment]
Merged. Thank you.

**Comment by brianchandotcom** [comment]
@pavel-savinov I made a ton of changes. Please review tomorrow. I'm waiting one day to publish since this is a new module. Thx.

**Comment by brianchandotcom** [comment]
@pavel-savinov sorry, I meant: please review my changes in upstream. And if I did something wrong, send me your changes by tomorrow. I'm hoping to publish these modules tomorrow.

**Pull request closed without merging**
