### PR TITLE
LPS-62685 buildSoy

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e4a2c7e628...6ff508789d

**Comment by brianchandotcom** [comment]
@leoadb see e4b85f0da1f6e2e9c40f0efef011633b0baf92ba

I had made this same change to your other Soy templates. Thx.

**Pull request closed without merging**
