### PR TITLE
LPS-70056 Updates shrinkwrap.json to use the latest version of Senna

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@ithildir what's happening here with ProjectTemplatesTest.testBuildTemplateServiceBuilderNestedPath?

Merged.

**Comment by jbalsas** [comment]
Thanks a lot, @brianchandotcom! I just sent the backport to @ZoltanTacaks: https://github.com/ZoltanTakacs/liferay-portal-ee/pull/2422

**Comment by brianchandotcom** [comment]
@jbalsas I merged in the backport already. Fyi @ZoltanTacaks

**Comment by jbalsas** [comment]
Even better! Thanks!

**Comment by Ithildir** [comment]
I'll look into it! @gamerson, have you seen this failure already?

**Comment by gamerson** [comment]
@Ithildir looks like the FooPersistanceImpl.java is slightly different between gradle and maven.  I will take a look.

**Pull request closed without merging**
