### PR TITLE
LCD-14683 - Use the ${id} for the package name in package.json.

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c9c1274d75...fd755099fb

**Comment by brianchandotcom** [comment]
@gamerson I just published client-extension-type-api 5.0.3 which has this change.

**Comment by brianchandotcom** [comment]
@ethib137 I just published client-extension-type-api 5.0.3 which has this change.

**Pull request closed without merging**
