### PR TITLE
Lps 59479

### PR DESCRIPTION
**Pull request by shuyangzhou**
@brianchandotcom we have seen this revert fixed all the random issues 2 times, but to be safe, please let it finish again time before you merge it.

CC @Ithildir

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@brianchandotcom that is the super slow 20+ mins timeout test. We are good here.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9f71716190...10e698e67c

**Comment by brianchandotcom** [comment]
@shuyangzhou can you email @rotty3000 to explain why we had to roll this back? and then let Manuel and Cristina to use a real version so we can track the changes, and then for them to fix this? Thx.

**Comment by shuyangzhou** [comment]
@brianchandotcom this issue is not finished yet, we still need @Ithildir to put in the fix for arquillian-extension-junit-bridge/build.gradle. And we do have some real bugs need to be fixed which are currently being hidden in a real bad way (we just catch the exception and swallow it in a lot of places).

I will try to get everything on my side done tomorrow, and hopefully @Ithildir can make https://github.com/brianchandotcom/liferay-portal/pull/31083 working too, then I will send an email to everyone that is involved, and then Spain can just simply continue their upgrade, otherwise they will run into the same problems again and stuck there.

**Comment by Ithildir** [comment]
I sent a fixed version of the pull at https://github.com/brianchandotcom/liferay-portal/pull/31087, there was a typo :cry: 

I think I found the version of the `org.arquillian.liferay` artifact that works, they are the ones published on 07/28. But unfortunately, I couldn't force the snapshot version in Gradle for one of them, because it's required not through a normal dependency, but it's the parent POM of the other ones. And so far I haven't found a way in Gradle to replace that type of dependency. I guess we really need a release for those artifacts.

**Pull request closed without merging**
