### PR TITLE
master-lps-57928

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LPS-57928

@brianchandotcom 
This is a resend of https://github.com/brianchandotcom/liferay-portal/pull/29392 that includes test fixes from QA.

CC @pat270 @juliocamarero @brianwulbern

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3becf7648d...1eda83ea3a

**Comment by brianchandotcom** [comment]
@natecavanaugh can you see modules/apps/product-menu/product-menu-web/src/META-INF/resources/css/main.css and see if that looks right? Thx.

**Comment by natecavanaugh** [comment]
Sent the SF here: https://github.com/brianchandotcom/liferay-portal/pull/29415

Thanks for the heads up Brian :)

**Comment by juliocamarero** [comment]
Thanks a lot @brianchiu and @brianwulbern!! :+1:

**Pull request closed without merging**
