### PR TITLE
LPS-67352

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@brianchandotcom, if there are others you can think of, let me know and I can add (see VariableNameCheck._ALL_CAPS_STRINGS)

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
Test failure caused by changes to bnd in liferay@471e1dd

**Comment by jpince** [comment]
@brianchandotcom please see Hugo's comment, SF batch is failing for everyone's pulls in master

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
