### PR TITLE
LPS-109064 Show create composition button only in case when corresponding configuration property is set

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pavel-savinov is this real?

```
https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/241756/AXIS_VARIABLE=0,label_exp=!master/testReport/junit/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_PortalSmokeUpgrade_ViewPortalSmokeArchiveAutoUpgrade730_/
```

Please resend

```
java.lang.Exception: Element is present at "//html[contains(@class,'lfr-spa-loading')]"
Stacktrace
java.lang.Exception: Element is present at "//html[contains(@class,'lfr-spa-loading')]"
	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl$Condition.assertTrue(BaseWebDriverImpl.java:4421)
	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl$Condition.waitFor(BaseWebDriverImpl.java:4456)
	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl.waitForElementNotPresent(BaseWebDriverImpl.java:3161)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.liferay.poshi.runner.PoshiRunnerExecutor$1.call(PoshiRunnerExecutor.java:1198)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Ask Mano?

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by pavel-savinov** [comment]
@brianchandotcom Not related, stable passed [here](https://github.com/pavel-savinov/liferay-portal/pull/524) with exactly the same branch.

/cc @ealonso

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1699988578...7bed0390f2

**Pull request closed without merging**
