### PR TITLE
LPS-128441 [Test] Indexer clauses: characterization tests // LPS-116243 [Test] Title indexed in triplicate distorts scores across multiple asset types: characterization tests

### PR DESCRIPTION
**Pull request by arboliveira**
https://issues.liferay.com/browse/LPS-128441
https://issues.liferay.com/browse/LPS-116243

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:reopen

**Comment by arboliveira** [comment]
Manually forwarded because `ci:forward` reported only a single, known, rare, unrelated test failure. ✔️

`javax.net.ssl.SSLException: Unsupported record version Unknown-0.0`

https://github.com/liferay-search/liferay-portal/pull/101#issuecomment-797156275

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2a6f84d303...f8c0d4daa0

**Comment by brianchandotcom** [comment]
@arboliveira see f8c0d4daa02fe7cdec6612b1da560e139d224281

master only.

**Pull request closed without merging**
