### PR TITLE
Lps 76927

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@pyoo47 what happened here?

**Comment by brianchandotcom** [comment]
@shuyangzhou  it was a real SF issue, fixed in ad866fd

@pyoo47 fyi. thx

**Comment by shuyangzhou** [comment]
@brianchandotcom I don't see your sf commit in upstream, I sent you a sf pull at https://github.com/brianchandotcom/liferay-portal/pull/57389

**Pull request closed without merging**
