### PR TITLE
Lps 75578

### PR DESCRIPTION
**Pull request by shuyangzhou**
@pavel-savinov this change has caused tons of different CI failures. Please fix them and resend.

### CODE REVIEW

**Comment by pavel-savinov** [comment]
@shuyangzhou There is a PR already to fix that: https://github.com/brianchandotcom/liferay-portal/pull/53656

**Comment by shuyangzhou** [comment]
@pavel-savinov  No, it is not working, see those modules integration failures, they are still there.

**Comment by shuyangzhou** [comment]
ci:test

**Comment by Preston-Crary** [comment]
@pavel-savinov there's a ConstraintViolationException being thrown after you call PortletFileRepositoryUtil.addPortletFileEntry() in HtmlPreviewGeneratorMessageListener.doReceive().

**Comment by pavel-savinov** [comment]
@Preston-Crary @shuyangzhou 
Could we pass https://github.com/brianchandotcom/liferay-portal/pull/53667 instead?
Just to avoid reverting everything.

**Comment by shuyangzhou** [comment]
synchronized on such a big block of code is a very bad thing, if you need that it just means some logic is really wrong in the code. It should be fixed in a proper way without using synchronized, plus, we don't really know that will fix everything.

Our goal here is to make CI green again asap. You can resend your change after that, that way you know the base is clean, if your pull still fails, you know for sure it has problems. Otherwise there will just be a lot of noise.

**Comment by pavel-savinov** [comment]
@shuyangzhou Ok.

**Comment by shuyangzhou** [comment]
Pushed upstream at https://github.com/liferay/liferay-portal/commit/00b9853570a5cd2a45b2ede3b275570b81079a60

**Pull request closed without merging**
