### PR TITLE
LPS-75830 Add tests

### PR DESCRIPTION
**Pull request by rafaprax**
\cc @linolaoj @jeyvison

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/53c7f05b3b...bd710a2a88

**Comment by brianchandotcom** [comment]
@rafaprax see my changes in bd710a2a885905fbd89bd16c4e4403d7105e09c4? Thx.

**Comment by rafaprax** [comment]
Thx @brianchandotcom

**Pull request closed without merging**
