### PR TITLE
LPS-62098 Default site role associations are not applied to the user

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-62098](https://issues.liferay.com/browse/LPS-62098).<br><br>/cc @jorgeferrer @pei-jung

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/32776e8c4a...f104925f79

**Pull request closed without merging**
