### PR TITLE
LPS-84119

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@shuyangzhou, what about lists?
Example: https://github.com/liferay/liferay-portal/blob/master/modules/apps/asset/asset-browser-web/src/main/java/com/liferay/asset/browser/web/internal/search/AssetBrowserSearch.java#L34-L42

**Comment by hhuijser** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
@hhuijser for list, it depends on whether it is readonly. For readonly ones, just do Arrays.asList(...), for modifiable ones, we have to wrap Arrays.asList(...) up with a real list.
The example here is a really BAD one. It is a public non-final field. It can technically be modified via many crazy ways. Although in our current codebase, we only read from it.
So for this example, make the field private final first (luckily the class is in internal package), then just do Arrays.asList(...).

**Comment by hhuijser** [comment]
ci:close

**Comment by shuyangzhou** [comment]
ci:reopen

@hhuijser not your fault, see https://github.com/brianchandotcom/liferay-portal/pull/62193#issuecomment-413768554

**Comment by hhuijser** [comment]
@shuyang, I closed because (after your comments) I wasn't so sure if this one is right: https://github.com/brianchandotcom/liferay-portal/pull/62206/files#diff-9f76b8359c6ec02e3aee69512f9e61baL43-L62

That is non-final

**Comment by brianchandotcom** [comment]
@hhuijser please resend. Thx.

**Comment by pyoo47** [comment]
@shuyangzhou @hhuijser I'm testing a possible fix for this issue here: https://github.com/pyoo47/liferay-portal/pull/749

**Pull request closed without merging**
