### PR TITLE
7.0.x-qa-28678

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-28678 / https://issues.liferay.com/browse/LPS-65630
https://issues.liferay.com/browse/LRQA-28679 / https://issues.liferay.com/browse/LPS-68375
https://issues.liferay.com/browse/LRQA-28680 / https://issues.liferay.com/browse/LPS-66598
https://issues.liferay.com/browse/LRQA-28682 / https://issues.liferay.com/browse/LPS-68008
https://issues.liferay.com/browse/LRQA-28683 / https://issues.liferay.com/browse/LPS-68480
https://issues.liferay.com/browse/LRQA-28684 / https://issues.liferay.com/browse/LPS-67593
https://issues.liferay.com/browse/LRQA-28685 / https://issues.liferay.com/browse/LPS-68607

@brianchandotcom - this is **7.0 only**

cc @alee8888 @kenjiheigel @vicnate5 @kmaria @sharonchoi

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@brianwulbern in the future, can we just add a "ignore=true" flag? So much cleaner than removing the whole thing.

@michaelhashimoto fyi

Merged.

**Comment by michaelhashimoto** [comment]
@brianchandotcom 
* I'm going to add portal-web to the auto-close list.
* WebLogic had an issue before, but it should be fixed now.

**Comment by brianchiu** [comment]
@brianchandotcom 
I see it. We currently don't have the "ignore=true" flag, so we'll stick to commenting tests out for now instead of deleting them altogether.

Hashi opened a ticket here: https://issues.liferay.com/browse/LRQA-28702

**Comment by brianwulbern** [comment]
@brianchandotcom @brianchiu 
Got it, will comment tests out until we have the "ignore=true" feature to use.

**Pull request closed without merging**
