### PR TITLE
[SF] LPS-177352 Add a new SF property to enable/disable formatting from JavaParser

### PR DESCRIPTION
**Pull request by kevhlee**
__Ticket:__ <https://issues.liferay.com/browse/LPS-177352>

Tested and reviewed [here](https://github.com/ling-alan-huang/liferay-portal/pull/1703), unrelated failures.

This pull request adds a new SF property for enabling/disabling formatting of Java and JSP files from `JavaParser`. By default, SF runs JavaParser to format Java/JSP code. However, it applies a specific Java code styling that users may not want (namely, customers and clients). Thus, users should be allowed to enable/disable JavaParser when executing SF.

### CODE REVIEW

**Comment by kevhlee** [comment]
ci:reopen

**Comment by kevhlee** [comment]
Hey @brianchandotcom,

For context, I made this PR for the Hotel team. Turning off Java/JSP auto-formatting is important for Hotel because they do not want to enforce Liferay's custom styling. Currently, SF auto-formats by default without the option to be turned off. It would be tedious for the Hotel team to not include formatting changes when upgrading codebases.

**Comment by kevhlee** [comment]
cc: @nicolas-sss, @natocesarrego

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/10ad2ed9f9...b7cd898f4d

**Pull request closed without merging**
