### PR TITLE
LPS-57450 Allow Site Administrators to configure the search scope of the search portlet

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @natecavanaugh @marcoscv-work @ealonso

**Comment by brianchandotcom** [comment]
@juliocamarero @jkappler I fixed a real jspc error. See test error log in pull. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f440cd0aba...01715b277e

**Comment by brianchandotcom** [comment]
@juliocamarero @jkappler also, half the commits in this pull had the wrong LPS.

**Pull request closed without merging**
