### PR TITLE
OAUTH2-42

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
[OAUTH2-42](https://issues.liferay.com/browse/OAUTH2-42)

@csierra reviewed these tests as part of stian-sigvartsen/liferay-portal/pull/119

/cc @topolik

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@shuyangzhou @mtambara @Preston-Crary lpkg tests broken

**Comment by brianchandotcom** [comment]
@stian-sigvartsen 

```
Function<Response, T> codeParser
```

Needs to be *Function

URI location 

should be

URI uri

Please resend. Thx.

**Comment by stian-sigvartsen** [comment]
Thanks Brian, this makes it more consistent 👍 
Please see brianchandotcom/liferay-portal/pull/62534

**Pull request closed without merging**
