### PR TITLE
LPS-100867 regenerate

### PR DESCRIPTION
**Pull request by inacionery**
/cc @nhpatt

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/11e3b9f0f2...71745daa8f

**Comment by brianchandotcom** [comment]
@nhpatt I merged this and it's my origin

Can you review this as well? It looks OK to me.

**Comment by nhpatt** [comment]
Reviewing right now... code looks fine (thanks for adding Integer support, removing the comma (query is valid with it though) and making Id optional.

Going to check our tests and be back in a bit.

**Comment by nhpatt** [comment]
@brianchandotcom I've sent a follow up here (https://github.com/brianchandotcom/liferay-portal/pull/78046) returning the id if available to be able to be used by the next tests.

**Pull request closed without merging**
