### PR TITLE
LPS-77263 Use <strong> if the thread has been updated since last time it was read

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/58cd4720ed...c1cfc50527

**Comment by brianchandotcom** [comment]
@sergiogonzalez why is setBold no longer honored? @jbalsas? See this pull. Thx.

**Comment by jbalsas** [comment]
Hey @brianchandotcom, I assumed this might've been lost sometime in the past. We should've been using the `resultRow.isBold` method for something, but I can't find any usages in current code.

**Pull request closed without merging**
