### PR TITLE
LPS-69730

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@brianchandotcom, I didn't run SB since the tests would break.
Will need to republish SB module and run SB.

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
Hey @brianchandotcom

This one fails the tests because on Jenkins, SF gets compiled before portal-kernel, so the changes to TextFormatter are not getting applied to SF, which results in a NPE.

I tested and it is okay to merge.

After you:
1. ant all
2. publish SF
3. publish SB
4. run SB and commit

everything should be good.

**Comment by brianchandotcom** [comment]
Ok. will do.

**Comment by brianchandotcom** [comment]
@hhuijser I did everything you asked, but locally, I get

```
     [java] Missing language key 'trackback-u-r-l': ./modules/apps/collaboration/blogs/blogs-web/src/main/resources/META-INF/resources/blogs/view_entry.jsp
     [java] Missing language key 'web-dav-u-r-l': ./modules/apps/collaboration/document-library/document-library-web/src/main/resources/META-INF/resources/document_library/access_from_desktop.jsp
     [java] Missing language key 'web-dav-u-r-l': ./modules/apps/collaboration/document-library/document-library-web/src/main/resources/META-INF/resources/document_library/info_panel.jsp
     [java] Missing language key 'web-dav-u-r-l': ./modules/apps/collaboration/document-library/document-library-web/src/main/resources/META-INF/resources/document_library/view_file_entry.jsp
     [java] Missing language key 'web-dav-u-r-l': ./modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/edit_structure.jsp
     [java] Missing language key 'web-dav-u-r-l': ./modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/edit_template.jsp
     [java] Missing language key 'callback-u-r-l': ./modules/apps/web-experience/portlet-configuration/portlet-configuration-web/src/main/resources/META-INF/resources/edit_sharing.jsp
     [java] Missing language key 'netvibes-widget-u-r-l': ./modules/apps/web-experience/portlet-configuration/portlet-configuration-web/src/main/resources/META-INF/resources/edit_sharing.jsp
     [java] Missing language key 'opensocial-gadget-u-r-l': ./modules/apps/web-experience/portlet-configuration/portlet-configuration-web/src/main/resources/META-INF/resources/edit_sharing.jsp
     [java] Missing language key 'web-dav-u-r-l': ./portal-web/docroot/html/taglib/ui/webdav/page.jsp
```

I also regenerated ServiceBuilder but I didn't see any changes.

I pushed it upstream anyways in case it's just code that needs to change (and not SF itself). Please send me a follow up pull?

Thx

**Pull request closed without merging**
