### PR TITLE
COMMERCE-6405 Commerce media resolver vulnerability issue

### PR DESCRIPTION
**Pull request by alessiorendina**
Hey @brianchandotcom,
Sending the requested changes.
Thanks,
Alessio

### CODE REVIEW

**Comment by Commando18** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cbf7855a22...9d8d6e64c5

**Comment by brianchandotcom** [comment]
@Commando18 please see my other changes, thx!

**Comment by Commando18** [comment]
@brianchandotcom thank you, I'll pay more attention to those formatting rules! :+1:

**Pull request closed without merging**
