### PR TITLE
Revert "LPS-150092 Same thing"

### PR DESCRIPTION
**Pull request by arthurchan35**
Hey @brianchandotcom 

We have to explicitly return null in this case, because there is some legacy issue with the configuration page that there will be empty configuration entry that is supposed to have a default value.

If we return empty string, the converted configuration entry will also contain empty value, but if we return null, the localService has logic to give a default value.

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@arthurchan35 

return String.valueOf(properties.get(key));

will return null

String.valueOf(null) == null

properties.get(key) with a missing key == null

Please test.

**Comment by arthurchan35** [comment]
Hey @brianchandotcom ,
what I meant was:

when properties.get(key) = ""
String.valueOf("") will be ""

but what we want is:
when properties.get(key) = ""
return null.

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/27002a5970...6f6a9bedd3

**Pull request closed without merging**
