### PR TITLE
Upgrade Process: Adapt some verifiers

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by migue** [comment]
ci:retest

**Comment by migue** [comment]
Not related, but let's try to get the build green ci:retest

**Comment by migue** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/dec36163e4...26bcd0750d

**Pull request closed without merging**
