### PR TITLE
COMMERCE 8650 5

### PR DESCRIPTION
**Pull request by ivicac**
master

### CODE REVIEW

**Comment by ivicac** [comment]
ci:reopen

**Comment by ivicac** [comment]
ci:open

**Comment by ivicac** [comment]
ci:reopen

**Comment by ivicac** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/79a9cca9f1...37a301e1e0

**Pull request closed without merging**
