### PR TITLE
LPS-68117 Move bookmarks tests

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by matethurzo** [comment]
not related failure ci:reopen

**Comment by matethurzo** [comment]
ci:reopen

**Comment by brianchiu** [comment]
Failing poshi tests are firefox connection issues.

QA Engineering is investigating right now. See: https://issues.liferay.com/browse/LRQA-28169

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
