### PR TITLE
Lps 193392 using download src backup

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a1ab9e04a9...2c81817dd6

**Comment by brianchandotcom** [comment]
@petershin can you review modules/third-party/org-hsqldb/build.gradle 

it looks slightly off

@jeffwu0724 @shuyangzhou fyi

**Comment by brianchandotcom** [comment]
@jeffwu0724 does this 16a22052d9d1fe1c8004409ccad8eb9fa10c3748 change your logic? if so, please send me a revert / fix.

**Comment by jeffwu0724** [comment]
Hi @brianchandotcom ,

1. https://github.com/brianchandotcom/liferay-portal/commit/16a22052d9d1fe1c8004409ccad8eb9fa10c3748 **did not change the logic**, and I  built the jar locally with these changes, and it **worked as expected**. 
2. This build.gradle looks different from others because, we need to recompile all hsql source files with jdk 8 and turn on debug-info without adding all the source files. Therefore, I download all the sources files in a temp dir, compile them with jdk 8 and debug-info, and  replace the original jar with these new files.

**Pull request closed without merging**
