### PR TITLE
LPS-71620 Create the basic code structure for Liferay Vulcan

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by JorgeFerrer** [comment]
ci:reopen

**Comment by JorgeFerrer** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@JorgeFerrer the comment on this pull stated this twice:

```
Exception in thread "main" java.lang.Exception: Incorrect Bundle-Name 'Liferay Vulcan Core API': ./modules/apps/vulcan/vulcan-api/bnd.bnd
     [java] Incorrect Bundle-SymbolicName 'com.liferay.vulcan': ./modules/apps/vulcan/vulcan-api/bnd.bnd
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:280)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:183)
     [echo] The following error occurred while executing this line:
```

We need to find a way so ppl can read it and comprehend it.

Fixing it right now

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/85c17784c3...3c49b2f226

**Comment by brianchandotcom** [comment]
@JorgeFerrer please see my changes in usptream. Quite a few. Let's talk about them over lunch. T hx.

**Pull request closed without merging**
