### PR TITLE
Lps 187404 2

### PR DESCRIPTION
**Pull request by shuyangzhou**
@ling-alan-huang can you add a SF check for this?
Basically "Liferay-Require-SchemaVersion" and "Liferay-Service" in bnd.bnd can only be used for modules with service.xml that contains real entities. If the module does not contain service.xml or the service.xml only contains empty entity with no columns, the bnd.bnd should not use those 2 headers.

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/7dfe361bcb...5b6bc4dec8

**Comment by ling-alan-huang** [comment]
@shuyangzhou Can I also apply this SF rule to 7.x?

**Comment by shuyangzhou** [comment]
Yes, it should work. But please go through CI to make sure.

**Pull request closed without merging**
