### PR TITLE
[RAYLIFE] LPS-146886 Rename site-initializer-raylife module to site-initializer-raylife-d2c

### PR DESCRIPTION
**Pull request by kevenleone**
@brianchandotcom as we spoke about renaming the `site-initializer-raylife` to `site-initializer-raylife-d2c`

Publishing the React is needed.

Also, I fixed this issue here:
https://github.com/brianchandotcom/liferay-portal/pull/114206

### CODE REVIEW

**Comment by kevenleone** [comment]
ci:open

**Comment by kevenleone** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a739e7ea9c...fc3372e125

**Comment by brianchandotcom** [comment]
@kevenleone I think

site-initializer-raylife-d2c-react

should be site-initializer-raylife-d2c-remote-app right? to be consistent? for modules/apps/site-initializer/site-initializer-raylife/extra/remote-app/package.json

Can you send me a follow up PR and also make sure all of our remote apps follow this (testray, osb customer portal etc).

**Comment by kevenleone** [comment]
It makes sense, thanks!

https://github.com/brianchandotcom/liferay-portal/pull/114246

**Pull request closed without merging**
