### PR TITLE
LPS-99867 portal-search-tuning-rankings-web: Show correct icons.

### PR DESCRIPTION
**Pull request by brandizzi**
<h3>:heavy_check_mark: ci:test:search - 48 out of 48 jobs passed in 2 hours 20 minutes 42 seconds 208 ms</h3>

That is new :)

https://github.com/brandizzi/liferay-portal/pull/859#issuecomment-553620884

Author: oliv-yu
Reviewer: @thektan @brandizzi

[Bug] Result Rankings: Each search result shows a blank thumbnail icon
https://issues.liferay.com/browse/LPS-99867

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/eee0fb8752...da7d5e9dde

**Comment by brianchandotcom** [comment]
Bravo @oliv-yu !

**Comment by brianchandotcom** [comment]
@oliv-yu can you make all the protected methods in

modules/dxp/apps/portal-search-tuning/portal-search-tuning-rankings-web/src/main/java/com/liferay/portal/search/tuning/rankings/web/internal/results/builder/RankingJSONBuilder.java

private? I don't see a reason for them to be protected.

Thx

**Comment by oliv-yu** [comment]
@brianchandotcom Sure! Created https://issues.liferay.com/browse/LPS-104604 to address this change and any updates it may cause with formatting.

**Comment by oliv-yu** [comment]
lbm:backport

**Pull request closed without merging**
