### PR TITLE
LPS-59212 apply generic type for performActionMethod to non-generated classes

### PR DESCRIPTION
**Pull request by rotty3000**
@arbetts can you document this in BREAKING_CHANGES.markdown? @brianchandotcom can you make sure to release a new SB bundle? Thx All!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/91cf967c82...e40a56ffde

**Comment by brianchandotcom** [comment]
@arbetts can you send me a pull for master and ee-7.0.x? Thx.

**Comment by arbetts** [comment]
@rotty3000 

isn't this backwards compatible because of java type erasure? so why do i need to update BREAKING_CHANGES?

**Comment by rotty3000** [comment]
Because the API generated is public, and by changing the type in the
methods it's broken for existing clients.

On Fri, Oct 16, 2015 at 12:14 PM, Andrew Betts <notifications@github.com>
wrote:

> @rotty3000 <https://github.com/rotty3000>
>
> isn't this backwards compatible because of java type erasure? so why do i
> need to update BREAKING_CHANGES?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/31068#issuecomment-148757811>
> .
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by arbetts** [comment]
@rotty3000 What do I put in BREAKING_CHANGES? 

i'm sorry, but i don't think I understand the issue.

the change adds a type parameter to the PerformActionMethod interface, which is a public inner interface of the ActionableDynamicQuery interface. If someone had already implemented the PerformActionMethod interface their method would look something like 

```java
new ActionableDynamicQuery.PerformActionMethod() {
	@Override
	public void performAction(Object object)
		throws PortalException {
		
		BookmarksEntry stagedModel = (BookmarksEntry)object;

			StagedModelDataHandlerUtil.exportStagedModel(portletDataContext,
				stagedModel);
		}
	};
```

this shouldn't break because if they implement the interface and leave off the type parameter, it defaults to Object.

I'm sure there is something i'm missing here.

**Comment by rotty3000** [comment]
I think you're right! So we're good, thanks!

On Fri, Oct 16, 2015 at 2:06 PM, Andrew Betts <notifications@github.com>
wrote:

> @rotty3000 <https://github.com/rotty3000> What do I put in
> BREAKING_CHANGES?
>
> i'm sorry, but i don't think I understand the issue.
>
> the change adds a type parameter to the PerformActionMethod interface,
> which is a public inner interface of the ActionableDynamicQuery interface.
> If someone had already implemented the PerformActionMethod interface their
> method would look something like
>
> new ActionableDynamicQuery.PerformActionMethod() {
>     @Override
>     public void performAction(Object object)
>         throws PortalException {
>
>         BookmarksEntry stagedModel = (BookmarksEntry)object;
>
>             StagedModelDataHandlerUtil.exportStagedModel(portletDataContext,
>                 stagedModel);
>         }
>     };
>
> this shouldn't break because if they implement the interface and leave off
> the type parameter, it defaults to Object.
>
> I'm sure there is something i'm missing here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianchandotcom/liferay-portal/pull/31068#issuecomment-148787874>
> .
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by arbetts** [comment]
@brianchandotcom 

do you mean master and ee-7.0.x for plugins?

the pull is here for that https://github.com/rotty3000/liferay-plugins/pull/67

**Pull request closed without merging**
