### PR TITLE
Lps 75609

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@mtambara 

Please put OpenOfficeConfigurationScanner in an internal package if it's not exported. Thx.

**Comment by brianchandotcom** [comment]
@mtambara please resend. Thx.

**Comment by shuyangzhou** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/52675

**Pull request closed without merging**
