### PR TITLE
LPS-102883 Bump org.bouncycastle libs to 1.61

### PR DESCRIPTION
**Pull request by BryanEngler**
⚠️ **ci:test:search - 45 out of 48 jobs passed** https://github.com/BryanEngler/liferay-portal/pull/437#issuecomment-553437856
✅ The only failures unique to this pull are not caused by this pr, confirmed by @xbrianlee

Author(s): @lipusz
Reviewer(s): @BryanEngler
Cc: @arboliveira

---
*[Bug] Security vulnerability in Bouncy Castle Provider 1.45 (Elasticsearch connectors)*
https://issues.liferay.com/browse/LPS-102883

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2014ae9980...65b5c16c13

**Comment by lipusz** [comment]
lbm:backport

**Comment by xbrianlee** [comment]
FYI this was already backported to 7.2
https://github.com/liferay/liferay-portal-ee/compare/d0dacb815b204ca96bf4b504bc2c76407a6eaceb%5E...2a181023ddf6465981a67400ba192e3754e34aa5

**Comment by lipusz** [comment]
Oh, thanks @xbrianlee! 👍

Sent from mobile
--
Project Manager, Search & App Security SME @ Product Care

**Pull request closed without merging**
