### PR TITLE
LPS-65501 Move tmpl to resources

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @adolfopa

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
I had to stop and retest this pull because a recent CI pull that got merged into upstream broke the PR tester. The source of this problem has been reverted.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/df47a9e454...12030e76c1

**Pull request closed without merging**
