### PR TITLE
LPS-101720 Auto SF

### PR DESCRIPTION
**Pull request by csierra**
/cc @topolik @martamedio @arthurchan35

### CODE REVIEW

**Comment by csierra** [comment]
ci:retest

**Comment by csierra** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@csierra can you resend (sorry it took so long to review, just small stuff):

1.) EmailOTPConfiguration emailOTPConfiguration = (EmailOTPConfiguration)request.getAttribute("emailOTPConfiguration");

request/session attributes are usually in *WebKeys*

2.) EmailOTPMFAChecker emailOtpMfaChecker

var name is wrong

3.) HttpSession session

var name should be httpSession

4.) MFAVerifyMVCRenderCommand.java does not start with a verb.

What's making this pull difficult is that there are lots of one-off changes that are different from existing code.. and for no real purpose.. so it makes reviewing line by line very tedious.

5.) I don't know why MFAPortletURLFactory is in a constants package. If at all possible, avoid this factory class if it's only used internally.

6.) We're making a lot of @Component that is only used internally... avoid it and use class instantiation unless you really do it need it for wiring.

Please resend. Thx.

**Comment by csierra** [comment]
please see https://github.com/brianchandotcom/liferay-portal/pull/82163

Thx!

**Pull request closed without merging**
