### PR TITLE
LPS-70043 Adding OSGi command to list possible configurations

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
\cc @adolfopa

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/77ff707481...46a7dff951

**Comment by brianchandotcom** [comment]
See 46a7dff951361374376f0d4df7a2b37bda8c0d51

**Pull request closed without merging**
