### PR TITLE
LPS-65627  Add  'modules/apps/adaptive-media/.gitrepo'

### PR DESCRIPTION
**Pull request by stsquared99**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0569ab5a9a...e0c3411d6a

**Comment by stsquared99** [comment]
ci:stop

**Comment by stsquared99** [comment]
ci:stop

**Pull request closed without merging**
