### PR TITLE
LPS-78050

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@brianchandotcom, you should be able to cherry pick everything except for https://github.com/brianchandotcom/liferay-portal/pull/55917/commits/7575e7174672410bcf4238d0a73a2fe1e9e658f8 and https://github.com/brianchandotcom/liferay-portal/pull/55917/commits/77bc60db34ab80cd728cd3c09a3dd94089afacfd

I sent a pull request to 7.0.x for those two commits: https://github.com/brianchandotcom/liferay-portal-ee/pull/19524

**Comment by hhuijser** [comment]
ci:test

**Comment by hhuijser** [comment]
@petershin, looks like https://github.com/brianchandotcom/liferay-portal/pull/55917/commits/77bc60db34ab80cd728cd3c09a3dd94089afacfd (which is a auto SF commit) broke the tests? Can you have a look?

**Comment by petershin** [comment]
@hhuijser - Sent a fix: https://github.com/tomwang2011/liferay-portal/pull/473

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
