### PR TITLE
LPS-82389 buildLang

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ad5f954562...ae490ef013

**Comment by jpince** [comment]
@ealonso I believe this pull caused the following failures. I ignored the tests in https://github.com/liferay/liferay-portal/commit/34f45df. Can you please take a look?

ExportedMissingReferenceExportImportTest.testMissingDummy
ExportedMissingReferenceExportImportTest.testMissingLayout
```
     [exec] com.liferay.exportimport.test.ExportedMissingReferenceExportImportTest > testMissingDummy FAILED
     [exec]     java.lang.AssertionError: com.liferay.portal.xml.NodeList@7d7495d7
     [exec]         at org.junit.Assert.fail(Assert.java:88)
     [exec]         at org.junit.Assert.assertTrue(Assert.java:41)
     [exec]         at org.junit.Assert.assertFalse(Assert.java:64)
     [exec]         at com.liferay.exportimport.test.ExportedMissingReferenceExportImportTest.assertMissingReferences(ExportedMissingReferenceExportImportTest.java:202)
     [exec]         at com.liferay.exportimport.test.ExportedMissingReferenceExportImportTest.testMissingDummy(ExportedMissingReferenceExportImportTest.java:160)
```
https://test-1-4.liferay.com/job/test-portal-acceptance-upstream-batch(master)/24314/AXIS_VARIABLE=8,label_exp=!master/consoleFull

**Comment by ealonso** [comment]
Hey @jpince,

My changes on that pull only affects frontend, nothing related with test integration. So, it should be another pull request.

Regards,
Eudaldo

**Pull request closed without merging**
