### PR TITLE
LPS-105495 | LPS-110335 Add TransactionCommitCallbackUtil to prevent StaleObjectStateException

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by inacionery** [comment]
Hey @barrosdennys and @rodrigocunhaa 

Do we have a ticket to fix this flaw WorkflowMetrics#ViewWorkloadByAssigneeCard?

Thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b03fcd47d3...f50ede5915

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f50ede5915...f50ede5915

**Comment by rodrigocunhaa** [comment]
Hi @inacionery 

I've just created a ticket for that ([LRQA-56734](https://issues.liferay.com/browse/LRQA-56734)) and I will fix it today.

Thanks!

**Comment by inacionery** [comment]
Thank you @rodrigocunhaa

**Pull request closed without merging**
