### PR TITLE
LPS-69161 Regen

### PR DESCRIPTION
**Pull request by marcellustavares**
cc @leoadb

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:stop

**Comment by marcellustavares** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
ci:retest (I just fixed the SF in upstream)

**Comment by leoadb** [comment]
ci:retest

**Comment by jpince** [comment]
ci:stop

**Comment by jpince** [comment]
@leoadb @marcellustavares see failure in lpkg-release
`com.liferay.portal.kernel.workflow.WorkflowException: com.liferay.portal.workflow.kaleo.exception.NoSuchDefinitionVersionException: No KaleoDefinitionVersion exists with the key {companyId=20113, name=Single Approver, version=1.0}`

also in smoke:
`LIFERAY_ERROR: Unable to process message {destinationName=liferay/kaleo_definition, response=null, responseDestinationName=null, responseId=null, payload=null, values={name=Single Approver, serviceContext=com.liferay.portal.kernel.service.ServiceContext@12ebde3, version=1, command=create}}`

**Comment by brianchandotcom** [comment]
@jpince how did these errors sneak in? They're not in 7.0.x and I don't recall merging in anything that showed this in the pull results.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cc21f77664...d7a0c5689a

**Comment by brianchandotcom** [comment]
@marcellustavares see d7a0c5689a1a59058065d05d9da10f6797220fac

**Comment by marcellustavares** [comment]
@jpince let me know if you find when this error started to happen

**Comment by jpince** [comment]
Fix here:
https://github.com/liferay/com-liferay-portal-workflow/pull/43
https://github.com/liferay/liferay-portal/pull/1277

**Comment by shuyangzhou** [comment]
All changes reverted at https://github.com/brianchandotcom/liferay-portal/pull/47964 and pushed upstream already.

**Pull request closed without merging**
