### PR TITLE
LPS-178222 Allow use modifiable system object in ObjectsDataProvider. The method name contains ByModifiable because another method already exists with the same types of parameters

### PR DESCRIPTION
**Pull request by seltong**

### CODE REVIEW

**Comment by seltong** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6277854706...9697670659

**Comment by brianchandotcom** [comment]
@seltong see changes in my origin. T hx

**Comment by brianchandotcom** [comment]
@seltong fyi my changes it match getSystemObjectDefinitions in that same class.

**Pull request closed without merging**
