### PR TITLE
LPS-64675 Support passing custom src as a request attribute.

### PR DESCRIPTION
**Pull request by epgarcia**
@natecavanaugh
@juliocamarero

### CODE REVIEW

**Comment by juliocamarero** [comment]
:+1:

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5741fbf1b9...a694b5ff51

**Comment by brianchandotcom** [comment]
@epgarcia interesting new pattern.. I decided to use :ext as the extension

see 0e3b8ad32f93ab0efb6bd1745b92bf477d93baef

**Comment by epgarcia** [comment]
Thanks @brianchandotcom! :ext looks better :+1:

**Pull request closed without merging**
