### PR TITLE
LPS-55355 fix portlet keys

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
It's green! @rotty3000 @peterfellwock

**Comment by rotty3000** [comment]
Finally!

**Comment by peterfellwock** [comment]
I am literally crying right now.

**Comment by brianchandotcom** [comment]
Merged. Thank you.

**Comment by brianchandotcom** [comment]
@peterfellwock Good job for this. Please send a follow up pull.

1.) 5cba644e029b2100121c197a2264387afc62a4e3 removed logic that would remove Shopping data when a group or user is deleted. See UserModelListener and GroupModelListener in calendar-service.

2.) 368142e85c1bc9e37719a07aaa7896e86a362a38 has the wrong portlet id. See bookmarks-web on how we fully namespace it.

3.) ShoppingGroupServiceSettingsOverride and ShoppingGroupServiceSettingsOverrideImpl both have the same constants declared. Please check with other existing use cases. If no one is using the static constants except the impl, keep it private.

4.) You removed 2 tests in 0212e59699d536383082c75baca4d6df8daa444c that should not have been removed. See BookmarksEntryPermissionCheckerTest .

5.) portlet.properties custom.sql.configs= doesn't match any of our other portlets

6.) We don't have any *ConfigurationActionImpl*. They're named something else.

**Pull request closed without merging**
