### PR TITLE
LPS-68979 Use task property instead of hard-coded path

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
@kenjiheigel, @Ithildir, could you please take a look at these issues?

**Comment by jbalsas** [comment]
@Ithildir mentioned there's something wrong in master with the tasks... will resend once it's fixed.

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
@jbalsas, we're looking into this now. Will keep you posted!

**Comment by kenjiheigel** [comment]
ci:retest

**Pull request closed without merging**
