### PR TITLE
LPS-57681 Update Test

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@csierra I merged in some of the commits from this pull and pushed it upstream, but not all. Still working on the rest.

**Comment by csierra** [comment]
Hey Brian!

how is it going? may I help you with anything on this pull?

If you think it could be helpful we could make a skype call to talk about any concerns you might have.

OTOH @jorgeferrer told me about sending you the working branch Miguel and I were holding with the rest of the progress. I believe that might not be helpful in this moment, but the contrary, so I would rather help merging this and then talk about the rest of the details. 

Bests!

**Comment by brianchandotcom** [comment]
hey @csierra 

I tried my best to merge this in, but ran into several issues. They're mainly dealing with naming and clarity.

1.) Can you rename "Upgrade" to something else? We have UpgradeProcess, UpgradeInfo, etc.  Just a plain old "Upgrade" is too nonspecific.

2.) Can you rename modules/portal/portal-upgrade/src/com/liferay/portal/upgrade/constants/UpgradeWhiteboardConstants.java

I don't see why it's called Whiteboard? Whiteboard is a pattern no?

3.) portal-service/src/com/liferay/portal/DatabaseContext.java should go in somewhere inside com.liferay.portal.kernel.dao, or dao.jdbc, or dao.db

4.) portal-service/src/com/liferay/portal/DatabaseProcessContext.java Same for this class. What is a "DatabaseProcess" if it was inside the kernel.dao. subpackage. "Process" needs to make sense there too. I know what you're doing with that class, but what that class is called in its home package needs to make sense too. Otherwise, seeing an OutputStream bundled with it makes no sense on its own.

If it doesn't make sense there, and is only used inside Upgrade, then may be it should go in the upgrade package?

5.) Also, we generally avoid *.api in the actual package name. Since there is an com.liferay.portal.upgrade.internal.*

Anything inside com.liferay.portal.upgrade that is not internal, is considered the API. See com.liferay.portal.search.elasticsearch and compare it with com.liferay.portal.search.elasticsearch.internal.

I merged in a few commits that I think made sense. See upstream for my chagnes.

Thx @csierra 

Can you aim to send me a pull by tomorrow morning my time? That way, I can take a quick look and get back to you by end of day my time. At the very least, if we ping each other once a day with pulls, we'll get through this faster than if our pulls took multiple days. I'll prioritize all your pulls first until Upgrade is done.

Thx.

**Comment by csierra** [comment]
please see https://github.com/brianchandotcom/liferay-portal/pull/29723

**Pull request closed without merging**
