### PR TITLE
OAUTH2-124  Merge REST module to master (5)

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Hi Brian. Thanks for merging the bits that you were already comfortable with. 
Here's a small pull request as per your comment https://github.com/stian-sigvartsen/liferay-portal/pull/79#issuecomment-382884713 which makes sense. 

Commit e5018bc contains Oauth2ProviderRestEndpointConstants identical to my previous pull request https://github.com/brianchandotcom/liferay-portal/pull/57324/commits/5e854117be45d6cfc2fd7706686790fd3a6fbe7f (I think it changed as your requested?). 

Commit 4fc7a16 is the same for LiferayOAuthDataProvider, however the commits following it are further improvements.

/cc @topolik @csierra

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Errors unrelated.. I'm on this. Thx @stian-sigvartsen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/61b93f9e8d...174ad9676d

**Comment by brianchandotcom** [comment]
@stian-sigvartsen Please see my changes in upstream.... I made my changes very tiny so you can get a sense of what I'm looking for. 

Also, regarding OAuth2ProviderRestEndpointConstants.PROPERTY_KEY_CLIENT_* and PROPERTY_KEY_*

Why are the values so different in syntax?  Some are all upper case, some have periods, some have dashes?

The point is to group them together.

I'm thinking you may have just put all properties together, and that some are used for Object X, and some for Object Y. I'm trying to segregate usage so nothing is ever clobbered.

The different syntax tells me something is wrong. Please send a follow up pull to fix that. Thx.

**Comment by stian-sigvartsen** [comment]
Thanks @brianchandotcom . I've checked that we can safely change the values of but one constant: "authorization_code_pkce". This follows a CXF convention. So I have changed the others to meet this convention and also used dots for hierarchical relationships. Hope you like it.

**Pull request closed without merging**
