### PR TITLE
LPS-92284 / LPS-91413

### PR DESCRIPTION
**Pull request by adolfopa**
https://issues.liferay.com/browse/LPS-92284
https://issues.liferay.com/browse/LPS-91413

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:reopen

**Comment by patriciajeanperez** [comment]
ci:close

**Comment by patriciajeanperez** [comment]
Hey @ChrisKian, @adolfopa sent me a new pull here: https://github.com/patriciajeanperez/liferay-portal/pull/176 to look into the failures caused by this pull.

It looks like it's causing this:
https://gist.githubusercontent.com/patriciajeanperez/fa1a7d6d58205ef7c5314e1680f7a13b/raw/8285b423c8928c7b52c0f9382844aaf0facd76b0/gistfile1.txt

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/70834

Thanks a lot @patriciajeanperez !

**Pull request closed without merging**
