### PR TITLE
Lps 199018

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by shuyangzhou** [comment]
@111Anna once this is in upstream, make sure to have data points before/after this change in our daily monitoring log, thanks!

**Comment by 111Anna** [comment]
OK 

> @111Anna once this is in upstream, make sure to have data points before/after this change in our daily monitoring log, thanks!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/42c733f790...9c9f538b7c

**Pull request closed without merging**
