### PR TITLE
Upgrade Process: run in parallalel the ugprade SQL scripts

### PR DESCRIPTION
**Pull request by migue**
cc @mhan810 I am burning some CPU cycles on the database side, some DBA Admin is gonna hate me :D

### CODE REVIEW

**Comment by mhan810** [comment]
@shuyangzhou FYI, this is to help speed up upgrade schema.

**Comment by migue** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@migue can you resend with *-* instead of *_* to match existing SQL delimiter.

Also, when you run "ant build-db" now, the output SQL is not valid. Some db admins refuse to allow a program to run SQL but prefer to run it manually, so we still need to translate it properly.

We can fix it by making DBBuilder take a flag pattern instead of a hard coded file name.

Thx @migue

**Comment by Preston-Crary** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/2638

**Pull request closed without merging**
