### PR TITLE
LPS-76566 IllegalArgumentException throws when adding a webcontent with geolocation field

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by izaera** [comment]
ci:retest

**Comment by izaera** [comment]
@alee8888 @jpince Can you please check what is happening here? We have ran ant all in local and everything worked right.

**Comment by jpince** [comment]
@izaera this is what I see, sorry I can't be more helpful than this :(
```
     [exec] Could not resolve all dependencies for configuration ':apps:foundation:map:map-google-maps:compileClasspath'.
     [exec] > Could not find com.liferay:com.liferay.frontend.js.loader.modules.extender:1.1.0.
```
@Ithildir any ideas?

**Comment by Ithildir** [comment]
AFAIK `com.liferay:com.liferay.frontend.js.loader.modules.extender:1.1.0` is not published. @izaera, where did you find it?

**Comment by jbalsas** [comment]
resent to https://github.com/brianchandotcom/liferay-portal/pull/53929

**Pull request closed without merging**
