### PR TITLE
[PUSHED TO UPSTREAM] LPS-56451 Fix deployment of search-web module

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @marcellustavares

**Comment by marcellustavares** [comment]
hey @sergiogonzalez, sorry about that.

I think we should include @${app.server.lib.portal.dir}/util-java.jar!/com/liferay/util/xml/XMLutil.class instead shouldn't we?

The class is still being used by SearchUtil.

**Comment by epgarcia** [comment]
Hi @marcellustavares,

I've updated the bnd so that it's the same as for journal-test and portal-wab-generator. Could you please check it and make any changes you consider necessary? marcellustavares/liferay-portal/pull/553

Thanks!

**Comment by marcellustavares** [comment]
Hi @epgarcia, @sergiogonzalez , can we close this pull?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f1e4079182...f1e4079182

**Pull request closed without merging**
