### PR TITLE
Lps 77177

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/46f0b5ad85...e491ffe330

**Comment by brianchandotcom** [comment]
@shuyangzhou I have this saved on a local branch, but I can't push this up to master until you send me a backport to 7.0.x because I need to publish a real version of the API jar from 7.0.x. Once I have that, then I can merge this pull into master.

**Comment by shuyangzhou** [comment]
@tomwang2011 please backport this, thanks!

**Pull request closed without merging**
