### PR TITLE
[StringBundler] LPS-84181

### PR DESCRIPTION
**Pull request by ChiZelin**
@tinatian 
@dantewang

### CODE REVIEW

**Comment by ChiZelin** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9c332ad565...d2bca9a6e0

**Comment by brianchandotcom** [comment]
@ChiZelin you can't change stuff in poshi-runner

/opt/dev/projects/github/liferay-subrepo-tools/bin/git-lpush -b master -o b8495cee2dacda1ec772fadf7b65cb5acd3b2013 -s 64fd2e95a9b5f6381a40f50b0137a77b777e8788 -r liferay-portal -v
master: Verifying.
error: Illegal change to a pull-only subdir modules/test/poshi-runner.

it's a read only subrepo. because it has a .gitrepo file in there set to read from com-liferay-poshi-runner (modify that repo and send me a pull there).

Please resend.

**Comment by ChiZelin** [comment]
Hi @brianchandotcom I haven't changed stuff in poshi-runner in this PR.

**Comment by ChiZelin** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@ChiZelin can you resend clean? I want to get some test results. Thx.

**Pull request closed without merging**
