### PR TITLE
LPS-53279 Replace ReservedUserEmailAddressException with inner class of UserEmailAddressException

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/04ea1949b9...4a3253a305

**Comment by mdelapenya** [comment]
This pull should have broken 3 tests, sending the fix here: https://github.com/brianchandotcom/liferay-portal/pull/23905

**Pull request closed without merging**
