### PR TITLE
LPS-59124 We must call getPrimKey to get the groupId instead of getPrimaryKey

### PR DESCRIPTION
**Pull request by JorgeFerrer**
/cc @sergiogonzalez

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
@brianchandotcom Good example of room for improvement in terms of naming: What's the difference between getPrimKey() and getPrimaryKey()

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ae4020812b...f73b304df6

**Comment by brianchandotcom** [comment]
agreed... getPrimKey is specific to that table.

getPrimaryKey is the generated primary key of every entity.

**Comment by brianchandotcom** [comment]
@JorgeFerrer @achaparro Can you add a test Alberto? Stuff like this should fail otherwise. Thx.

**Comment by achaparro** [comment]
Hi @brianchandotcom,

I can take care of that but I think that this is more related to develop an automated tool to check common issues during code modifications than doing it as a test. I have solved several bugs lately which we could have avoided with that kind of tool, for example (apart from the current issue):
https://github.com/liferay/liferay-portal/commit/e5598a88ae727b04d9a523f180d856845ec179dc
https://github.com/liferay/liferay-portal/commit/754bf87c83f0c0b73e58fc391dca99d7a168aff4
https://github.com/liferay/liferay-portal/commit/ac9e8378ede5c1799c74c9a8f3b631f209f524f2

Please, let me know in order to to work in one way or another.

Thanks!

@JorgeFerrer

**Pull request closed without merging**
