### PR TITLE
LPS-38116 SF

### PR DESCRIPTION
**Pull request by topolik**
Hi Brian,

Fix for https://issues.liferay.com/browse/LPS-38116 for master. It should be already commited in 6.0. and 6.1

Thank you.

/cc @NorbertKocsis, @lipusz

### CODE REVIEW

**Comment by lipusz** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f2caf73222...1e9c8388c7

**Comment by brianchandotcom** [comment]
@topolik @lipusz can you send it to ee-6.2.x too? Thx.

**Comment by lipusz** [comment]
Hi Brian @brianchandotcom 

Sure, the backport ticket has been created, so you should get this for 62x soon.

Regards,
Tibor

**Pull request closed without merging**
