### PR TITLE
LPS-60861

### PR DESCRIPTION
**Pull request by samuelkong**
cc @yxingwu

### CODE REVIEW

**Comment by samuelkong** [comment]
I think the CI error is correct since we are making changes to service builder. Please let us know if we're missing something. Thanks.

**Comment by brianchandotcom** [comment]
@samuelkong no worries, I regened it.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3a5461e62c...b7287596fe

**Comment by brianchandotcom** [comment]
See b7287596feeb2a20008d43f3cd70a1310ba6baa9

**Pull request closed without merging**
