### PR TITLE
LRQA-35135, LRQA-35136 | master

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-35135
https://issues.liferay.com/browse/LRQA-35136

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:reopen

**Comment by anthony-chu** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest https://loop.liferay.com/home/-/loop/feed/7636012

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a0342b21a1...ce6b767945

**Pull request closed without merging**
