### PR TITLE
LPS-96698 javadoc

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/11aa50f9df...3c441a726a

**Comment by brianchandotcom** [comment]
@nhpatt I simplified it a bit in upstream. Can you apply my pattern for the REST endpoints too?

**Comment by brianchandotcom** [comment]
@nhpatt I also sorted vars...

**Comment by nhpatt** [comment]
Thanks! Will apply it to REST endpoints.

**Pull request closed without merging**
