### PR TITLE
LPS-103574 SF

### PR DESCRIPTION
**Pull request by matuzalemsteles**
Hey @brianchandotcom After talking to @wincent we are going with the idea of ​​just adding `eslint-disable` at the file level to lessen the noise in mixed React and Metal modules.

#80006

### CODE REVIEW

**Comment by brianchandotcom** [comment]
But why are we disabling it? Why not change the code to follow what eslint recommends?

**Comment by matuzalemsteles** [comment]
@brianchandotcom like me and @wincent pointed out in the other PR (https://github.com/brianchandotcom/liferay-portal/pull/80006#issuecomment-547345847), this rule only makes for React. These files are components of Metal.js which in turn both support `this.refs` but in React this has been deprecated in favor of a new API but this is not true for Metal.js. This module is mixed, we have Metal components and React the idea that this number of Metal components in this module will decrease.

**Comment by wincent** [comment]
We should probably prioritize doing https://github.com/liferay/eslint-config-liferay/issues/107 (ie. making "react" the default preset) sooner rather than later, along with implementing [this suggestion](https://github.com/liferay/eslint-config-liferay/issues/107#issuecomment-547346276) (ie. creating a custom fork of the "no-string-refs" rule) to reduce the noise in mixed Metal/React modules like this one. I should be able to get onto this shortly.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e4f42e7a25...a7290539df

**Pull request closed without merging**
