### PR TITLE
LPS-91343 | master

### PR DESCRIPTION
**Pull request by jpince**
@brianchandotcom @petershin this doesn't look right, Brian just made what looks like SF changes and it's asking for a minor version increase. Can you please take a look? https://github.com/liferay/liferay-portal/commit/cbac3d5ef1c88d24ed26566252702fe534c2cf67#diff-9dc367c2c7e85511bb789e040a421404R44

here's the error: https://test-1-11.liferay.com/job/test-portal-acceptance-upstream-batch(master)/36766/AXIS_VARIABLE=7,label_exp=!master/console
```
     [exec] > Task :apps:blogs:blogs-api:baseline FAILED
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.blogs.service                          MINOR      1.0.2      1.0.1      1.1.0      VERSION INCREASE REQUIRED
     [exec] 	<   class      com.liferay.blogs.service.BlogsEntryServiceUtil
     [exec] 		+   method     addAttachmentsFolder(long)
     [exec] 			+   access     static
     [exec] 			+   return     com.liferay.portal.kernel.repository.model.Folder
     [exec] 	<   class      com.liferay.blogs.service.BlogsEntryServiceWrapper
     [exec] 		+   method     addAttachmentsFolder(long)
     [exec] 			+   return     com.liferay.portal.kernel.repository.model.Folder
     [exec] 	<   interface  com.liferay.blogs.service.BlogsEntryService
     [exec] 		+   method     addAttachmentsFolder(long)
     [exec] 			+   access     abstract
     [exec] 			+   return     com.liferay.portal.kernel.repository.model.Folder
     [exec] 		-   annotated  com.liferay.portal.kernel.spring.osgi.OSGiBeanProperties
     [exec] 			-   property   property.0='json.web.service.context.name=blogs'
     [exec] 			-   property   property.1='json.web.service.context.path=BlogsEntry'
     [exec] 			-   property   service.0=com.liferay.blogs.service.BlogsEntryService
     [exec] 	-   version    1.0.1
     [exec] 	+   version    1.0.2
```

### CODE REVIEW

**Comment by petershin** [comment]
@jpince - It's bumping the version because of the changes made here: https://github.com/liferay/liferay-portal/commit/b6953f94

**Comment by jpince** [comment]
@petershin thanks, will resend

**Comment by jpince** [comment]
resent https://github.com/brianchandotcom/liferay-portal/pull/68780

**Comment by jpince** [comment]
ci:stop

**Pull request closed without merging**
