### PR TITLE
LPS-155536 Adjust condition so it works with layout page template entries

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-155536

@victorg1991

### CODE REVIEW

**Comment by ozysouza** [comment]
ci:reopen

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See [liferay-echo#7560](https://github.com/liferay-echo/liferay-portal/pull/9453)

:heavy_check_mark: ci:test:stable - 27 out of 27 jobs passed
:x: ci:test:relevant - 187 out of 197 jobs passed in 2 hours 24 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2c7c71ef37...751cbbb469

**Comment by brianchandotcom** [comment]
@victorg1991 see e30c14350f2959512377f1a70390a4563d22aea9

**Pull request closed without merging**
