### PR TITLE
LPS-78892 Lexicon patterns adjustments

### PR DESCRIPTION
**Pull request by alee8888**
@brianchandotcom @marcoscv @jbalsas
This includes Poshi test fixes and the commit for LPS-78892 to capitalized portlet titles.

### CODE REVIEW

**Comment by alee8888** [comment]
ci:test

**Comment by alee8888** [comment]
ci:open

**Comment by alee8888** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
