### PR TITLE
LPS-65957 Rename method to make its semantics more clear

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/79b9ecd2a9...dc2772529c

**Comment by brianchandotcom** [comment]
@drewbrokke @JorgeFerrer see 07f2a280801d75cf614fb9695d1c80b81e5a4ffe thx

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/98fad7c07d...fe43dacb16

**Comment by brianchandotcom** [comment]
Wrong hash, see fe43dacb1619b9a8f4f44812c4c072d3adcfa4b3

**Comment by JorgeFerrer** [comment]
The new method name looks good.

Thanks Brian

**Pull request closed without merging**
