### PR TITLE
LPS-96290

### PR DESCRIPTION
**Pull request by petershin**
@gamerson

### CODE REVIEW

**Comment by petershin** [comment]
@pyoo47 - Do you know if Julien Castelain created an IT ticket for to update mirrors?

The `ckEditor` editor dependency was updated here: [liferay@5b2ae37](https://github.com/liferay/liferay-portal/commit/5b2ae3732d96f7f0dec6d35cb4de99f9d389c248#diff-7a74683753f4f84a9bbdfa7873a1dfd4R11)

**Comment by pyoo47** [comment]
@petershin I forgot to ask him to do it whenever he updates the dependency. I got IT to add it to mirrors so we should be good to go now.

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/33e6608687...c50b220209

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
