### PR TITLE
LPS-138945 Increase retry assert time to 10 seconds

### PR DESCRIPTION
**Pull request by anabuchmann**
Story: [LPS-138937](https://issues.liferay.com/browse/LPS-138937)

--------------------------------------------------
Hi Brian! I'm sending this manually because the CI is unstable. The failures are not related: https://github.com/liferay-workflow/liferay-portal/pull/528#issuecomment-919345297

### CODE REVIEW

**Comment by anabuchmann** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ee5cce65b4...77e8bc8e02

**Comment by brianchandotcom** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/107143/commits/b3a8ff41ad2ca0928bd25b0aa60554479ac7d6f7 it sure seems like a bug.

@shuyangzhou this seems very wrong.

**Comment by brianchandotcom** [comment]
@anabuchmann @naraandrade @MarinhoFeliphe see proper fix in https://github.com/brianchandotcom/liferay-portal/pull/107161

Thanks @shuyangzhou

**Pull request closed without merging**
