### PR TITLE
LPS-84919 Uses new portlet provider to select journal ddmtemplates

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @kyle-miho, @brianchiu,

Could you please take a look to the poshi error? I think we need to change the button selector, like you did for structures.

Regards,
Eudaldo

**Comment by brianchiu** [comment]
@ealonso I'm on it. I'll submit it to BChan with changes.

**Comment by brianchiu** [comment]
ci:close

**Comment by brianchiu** [comment]
Hi @ealonso 
Here's are some problems I've found with your pull. Could you take a look when you have a chance?

1. (This is the one that causes the poshi test failure) The confirmation box that says "Selecting a new structure deletes all unsaved content. Do you want to proceed?" no longer shows up. Is this intentional? I feel like it should still be there. Below is a screenshot of what it normally would be like.confirmation

2. The delete icon for templates changes back to what it was before https://issues.liferay.com/browse/LPS-84549, but this does not follow the lexicon pattern. In your pull it looks like this: 
icon reverted backIn master right now it looks like this: correct icon

3. The "Save and Continue" button is gone. save and continue missing Normally it would between the "Save" and "Cancel" buttons like here: save and continue

4. Clicking Save doesn't redirect properly. It redirects to the new template creation screen.save does not redirect

5. The back button does not work. back button does not work

6. The cancel button does not work. cancel does not work

**Comment by ealonso** [comment]
Hey @brianchiu, @kyle-miho

1. This message doesn't make sense here, because we are not changing the content, we are selecting a structure for the template, and you can select one the first time, you can not select a new one if you have one selected.
2. Fixed
3. We've decided to removes "save and continue" button, to make it consistent with web content and web content structure form
4. Fixed
5. Fixed
6. Fixed

I'm sending the new pull request to Brian: https://github.com/brianchandotcom/liferay-portal/pull/62671

**Comment by brianchiu** [comment]
Hey @ealonso 
I also found these bugs. I'm not entirely sure but they might be related to your changes.
https://issues.liferay.com/browse/LPS-85079
https://issues.liferay.com/browse/LPS-85078
https://issues.liferay.com/browse/LPS-85077

**Comment by ealonso** [comment]
Hey @brianchiu, 

Thanks a lot for letting me know, here the pulls request to fix the problems

- https://issues.liferay.com/browse/LPS-85079 -> https://github.com/brianchandotcom/liferay-portal/pull/62733
- https://issues.liferay.com/browse/LPS-85078 -> https://github.com/brianchandotcom/liferay-portal/pull/62735
- https://issues.liferay.com/browse/LPS-85077 -> https://github.com/brianchandotcom/liferay-portal/pull/62736

Please, let me know if you find more bugs.

**Pull request closed without merging**
