### PR TITLE
LPS-82974 Take remote staging into account

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by jkappler** [comment]
Sent to 7.1.x https://github.com/brianchandotcom/liferay-portal-ee/pull/20701

**Comment by jkappler** [comment]
cc:// @brianchiu

**Comment by jkappler** [comment]
he @brianchiu, @jpince, I'm seeing this weird issue with baseline in this PR, and I'm also seeing it in another PR. I tried to check in my local and everything works correctly. Would you happen to know if it's a generalized issue? Let me know please. Thanks

**Comment by brianchiu** [comment]
@jkappler 
I don't think the baseline issue is being caused by your pull specifically, because I also see it here: https://github.com/brianchandotcom/liferay-portal/pull/60836.

However, I'm not seeing it on any other pull besides yours and Eudaldo's.

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
