### PR TITLE
LPS-101393 | master

### PR DESCRIPTION
**Pull request by Sharryxue**
https://issues.liferay.com/browse/LPS-101393

/ cc @patriciajeanperez

Commits are only for master. Thanks

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/495341c7c2...78eb93ea68

**Comment by brianchandotcom** [comment]
@kylemiho @Sharryxue @victorware can we have these new tests in modules/apps/account?

Would make it much easier for me to know what should be backported or not. Thx.

**Comment by kyle-miho** [comment]
@brianchandotcom my liferay github name is kyle-miho, kylemiho is my personal github, so i may miss some of these notifications. I just talked to Roy and Kenji about having poshi being able to read tests from modules/apps/*.

**Comment by patriciajeanperez** [comment]
Thanks @kyle-miho, I can take care of it. @Sharryxue

**Pull request closed without merging**
