### PR TITLE
master-qa-21205

### PR DESCRIPTION
**Pull request by alee8888**
https://issues.liferay.com/browse/LRQA-21205

### CODE REVIEW

**Comment by alee8888** [comment]
@brianchandotcom 
This fixes the functional test (CPUsersandorganizations#AddUser) that has been failing the PR tester the past day.

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fb0288f81a...5e1bb16f45

**Comment by brianchandotcom** [comment]
@alee8888 @pyoo47 SF error https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/21420/testReport/com.liferay.source.formatter/SourceFormatterTest/testSourceFormatter/

I checked in the SF issue.

**Pull request closed without merging**
