### PR TITLE
LPS-59194 master

### PR DESCRIPTION
**Pull request by juangon**
Hi @brianchandotcom, this is a bad regression for Weblogic servers reproduced in 6.2.x. I couldn't test in Weblogic using master as this issue block its testing (https://issues.liferay.com/browse/LPS-44866), but we will add the same fix for master for consistency.
Reviewed by @topolik too.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jhendley @brianchiu fyi

@juangon is this easy to catch in WL, or is it hard to catch ? I"m pushing QA to start adding all app servers to test each PR, and to catch things like ths.

**Comment by brianchandotcom** [comment]
@shuyangzhou random test failure here.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6b951ff8aa...b4ac5f93dc

**Comment by juangon** [comment]
@brianchandotcom it should be easy to reproduce, just try to execute any action from a plugin (or an action from a runtime portlet). Steps are in LPS.
/cc @jhendley @brianchiu

**Comment by brianchandotcom** [comment]
@brianchiu please add a functional test for this. Thx.

cc @jhendley

**Comment by brianchiu** [comment]
@brianchandotcom 
Sure thing.

**Comment by shuyangzhou** [comment]
Fix for SQLTest see https://github.com/brianchandotcom/liferay-portal/pull/30855

**Comment by juangon** [comment]
New test portlets here: https://github.com/brianchandotcom/liferay-plugins/pull/4961

**Pull request closed without merging**
