### PR TITLE
Lps 58444

### PR DESCRIPTION
**Pull request by shuyangzhou**
@topolik I kept your tests and make sure my changes pass it, but please double check to make sure I did not break any logic for you.

@slnn and @dantewang, I had @tomwang2011 ran the performance regression tests already, it should be back to the baseline. But please double check that on your side too.

### CODE REVIEW

**Comment by slnn** [comment]
Hi all,
@shuyangzhou  @dantewang @topolik
Double check this pull with the performance regression tests, it made the performance back to the baseline on our side.
Thanks!

**Comment by shuyangzhou** [comment]
Thanks @slnn !

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9c7ab9d7aa...9bbdc6ac73

**Comment by topolik** [comment]
Works correctly. Thanks @shuyangzhou!

**Comment by shuyangzhou** [comment]
Thanks for the checking @topolik !

**Pull request closed without merging**
