### PR TITLE
LPS-80332 Update forms-and-workflow

### PR DESCRIPTION
**Pull request by petershin**
See comments in https://github.com/brianchandotcom/liferay-portal/pull/57879#issuecomment-385993456

### CODE REVIEW

**Comment by petershin** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/3e7f679efc...a0f05a77a5

**Comment by brianchandotcom** [comment]
@petershin I want to cry because the commit logs were so beautiful... thank you!

**Comment by brianchandotcom** [comment]
@petershin what about master-private? Can you fix that as well? Thx.

**Pull request closed without merging**
