### PR TITLE
Lpd 36500

### PR DESCRIPTION
**Pull request by shuyangzhou**
@brianchandotcom this needs to be published with JDK17, it won't work with JDK8. We need to consume this jar once we start to handle runtime jsp compile. For now we just need it to be published on nexus.

CC @petershin @vicnate5 @wesleygong

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@petershin I tried publishing this with JDK 17 and it didn't work.

```
> Task :third-party:javax-portlet:compileJava NO-SOURCE
> Task :third-party:javax-portlet:copyLibs SKIPPED
> Task :third-party:javax-portlet:copyCSS SKIPPED
> Task :third-party:javax-portlet:buildCSS SKIPPED
> Task :third-party:javax-portlet:processResources NO-SOURCE
> Task :third-party:javax-portlet:classes UP-TO-DATE
> Task :third-party:javax-portlet:generatePomFileForMavenPublication
> Task :third-party:javax-portlet:generateJSPJava NO-SOURCE
> Task :third-party:javax-portlet:compileJSP SKIPPED
> Task :third-party:javax-portlet:zipZippableResources UP-TO-DATE
> Task :third-party:javax-portlet:jar
> Task :third-party:javax-portlet:generateMetadataFileForMavenPublication FAILED
> Task :third-party:javax-portlet:autoUpdateXml SKIPPED

> Task :third-party:javax-portlet:jarTransformed
Copyright (c) Contributors to the Eclipse Foundation
org.eclipse.transformer.cli.JakartaTransformerCLI Version [ 1.0.0 ]



FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':third-party:javax-portlet:generateMetadataFileForMavenPublication'.
> java.io.FileNotFoundException: /home/me/dev/projects/liferay-portal/tools/sdk/dist/javax.portlet-3.0.1.JAKARTA_LIFERAY-PATCHED-1.jar (No such file or directory)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 21s
3 actionable tasks: 3 executed

```

@shuyangzhou fyi

**Comment by shuyangzhou** [comment]
@brianchandotcom can you try to run gw installCache ? does that work for you?

**Comment by wesleygong** [comment]
cc @drewbrokke

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d0fe917f08...05a6642da9

**Comment by brianchandotcom** [comment]
@petershin @drewbrokke I was able to publish after removing the line 05a6642da9b87cffe85a6f4939324c7fbd3555f1

and then I ran "gw installCache" prior to publishing.

@petershin @drewbrokke please send a long term fix. Thx.

**Comment by shuyangzhou** [comment]
@brianchandotcom you can just remove that line. I added that to avoid the eclipse-transformer complain. When it sees existing file with that output name, it complains. With it removed, as long as you run gw clean before publish, you won't run into out of date jar publication.

**Pull request closed without merging**
