### PR TITLE
LPS-73536

### PR DESCRIPTION
**Pull request by Ithildir**
cc @EddieOlson

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:stop

**Comment by michaelhashimoto** [comment]
ci:retest - There was a CI outage recently, see this slack post for more information:
https://liferayeng.slack.com/archives/C19PWQ74J/p1499712491340859

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ccfb8e83e8...e49a46a663

**Comment by brianchandotcom** [comment]
@Ithildir can you send me the pull to make this XML file the same across master-private and 7.0.x-private? Thx.

**Comment by Ithildir** [comment]
Done: https://github.com/brianchandotcom/liferay-portal-ee/pull/17703

**Pull request closed without merging**
