### PR TITLE
LPS-94999

### PR DESCRIPTION
**Pull request by petershin**
@david-truong

### CODE REVIEW

**Comment by petershin** [comment]
ci:reopen

**Comment by jpince** [comment]
@petershin @david-truong these failures look related? Not sure if it just means Brian has to publish.
modules-unit
```
     [exec] > Task :util:css-builder:writeMavenSettings
     [exec] Using http://repository-cdn.liferay.com/nexus/content/groups/public as custom repository and squid.lax.liferay.com:3128 as proxy for Maven invocations in project ':util:css-builder'.
     [exec] [main] ERROR org.apache.maven.cli.MavenCli - Failed to execute goal on project com.liferay.css.builder: Could not resolve dependencies for project com.liferay:com.liferay.css.builder:maven-plugin:3.0.0: Could not find artifact com.liferay:com.liferay.sass.compiler.ruby:jar:2.0.5 in default (http://repository-cdn.liferay.com/nexus/content/groups/public) -> [Help 1]
     [exec] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project com.liferay.css.builder: Could not resolve dependencies for project com.liferay:com.liferay.css.builder:maven-plugin:3.0.0: Could not find artifact com.liferay:com.liferay.sass.compiler.ruby:jar:2.0.5 in default (http://repository-cdn.liferay.com/nexus/content/groups/public)
```
https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/290414/AXIS_VARIABLE=0,label_exp=!master/console

project-templates
```
     [exec] com.liferay.project.templates.ProjectTemplatesTest > testBuildTemplateWarMVCPortletInWorkspace FAILED
     [exec]     org.gradle.testkit.runner.UnexpectedBuildFailure: Unexpected build execution failure in /tmp/junit3069406570006383569/gradle/WarMVCPortlet with arguments [--stacktrace, -Dhttp.proxyHost=squid.lax.liferay.com, -Dhttp.proxyPort=3128, :build]
     [exec] 
     [exec]     Output:
     [exec] 
     [exec]     > Task :buildCSS FAILED
     [exec]     Was passed main parameter 'sass.append.css.import.timestamps=true' but no main parameter was defined in your arg class
     [exec]     Usage: java -jar com.liferay.css.builder-3.0.0.jar [options]
     [exec]       Options:
     [exec]         --append-css-import-timestamps
     [exec]           Whether to append the current timestamp to the URLs in the @import CSS 
     [exec]           at-rules. 
     [exec]           Default: true
     [exec]         --base-dir
     [exec]           The base directory that contains the SCSS files to compile.
     [exec]           Default: src/META-INF/resources
     [exec]         --compiler
     [exec]           The type of Sass compiler to use. Supported values are "jni" and "ruby". 
     [exec]           The Ruby Sass compiler requires "com.liferay.sass.compiler.ruby.jar", 
     [exec]           "com.liferay.ruby.gems.jar", and "jruby-complete.jar" to be added to the 
     [exec]           classpath. 
     [exec]           Default: jni
     [exec]         --dir-names
     [exec]           The name of the directories, relative to base directory, which contain 
     [exec]           the SCSS files to compile. All sub-directories are searched for SCSS 
     [exec]           files as well.
     [exec]           Default: [/]
     [exec]         --excludes
     [exec]           The SCSS file patterns to exclude from compiling.
     [exec]           Default: [**/_diffs/**, **/.sass-cache*/**, **/.sass_cache_*/**, **/_sass_cache_*/**, **/_styled/**, **/_unstyled/**, **/css/aui/**, **/css/clay/**, **/tmp/**]
     [exec]         --generate-source-map
     [exec]           Whether to generate source maps for easier debugging.
     [exec]           Default: false
     [exec]         -h, --help
     [exec]           Print this message.
     [exec]         --import-paths
     [exec]           The import directories of Sass libraries.
     [exec]         --output-dir
     [exec]           The name of the sub-directories where the SCSS files are compiled to. 
     [exec]           For each directory that contains SCSS files, a sub-directory with this 
     [exec]           name is created.
     [exec]           Default: .sass-cache/
     [exec]         --precision
     [exec]           The numeric precision of numbers in Sass.
     [exec]           Default: 9
     [exec]         --rtl-excluded-path-regexps
     [exec]           The SCSS file patterns to exclude when converting for right-to-left 
     [exec]           (RTL) support.
     [exec]           Default: []
```
https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/166374/AXIS_VARIABLE=0,label_exp=!master/consoleFull

**Comment by david-truong** [comment]
@jpince yes we need to update the gradleTests

**Comment by jpince** [comment]
@petershin merge conflict (not sure if Brian can/will resolve it himself)

@lawrence-lee see ProjectTemplatesTest failure (not merged yet)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/35bec2e8bf...a193dbf535

**Pull request closed without merging**
