### PR TITLE
Lps 189602

### PR DESCRIPTION
**Pull request by Tim-Cao**
@ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/12781

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2ec77908a8...2066d9b4a8

**Comment by brianchandotcom** [comment]
@ealonso @Mikellorza see 2066d9b4a8ac6633bb4b37fb24cddf4cceff89d1 and 816a28efd0f9b11cf5d8cef6297436829b647836

**Pull request closed without merging**
