### PR TITLE
Lps 84374

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @marianoalvarosaiz @holatuwol @mtambara

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c25d5bbacf...fa1d0d42da

**Comment by brianchandotcom** [comment]
@tinatian can you verify my change in fa1d0d42da2b826e04d34353335c207a756442d6 doesn't break tests? If it does, please send me a pull to fix it. Thx.

**Comment by tinatian** [comment]
@brianchandotcom That change won't break any test.

**Pull request closed without merging**
