### PR TITLE
LPS-65842 Use direct service reference instead passing thru the proxy

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest since it froze last time

**Comment by brianchandotcom** [comment]
ci:stop (upstream had an issue)

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@marcellustavares all of modules-integration seems broken. Can you resend? Thx.

**Comment by marcellustavares** [comment]
Resent to https://github.com/brianchandotcom/liferay-portal/pull/40269

**Pull request closed without merging**
