### PR TITLE
LPS-56383 Make ServiceConfigurators and ServiceUpgrade consistent

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@epgarcia I think there are some bugs. Can you resend? Thx.

**Comment by epgarcia** [comment]
I fixed it, see brianchandotcom/liferay-portal/pull/27898.

Thanks!

**Pull request closed without merging**
