### PR TITLE
LRQA-33417 | master

### PR DESCRIPTION
**Pull request by brianchiu**
https://issues.liferay.com/browse/LRQA-33417

@kenjiheigel
This makes all the description elements the same.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchiu** [comment]
cc @brianwulbern

Could you backport this to ee-7.0.x?

**Comment by brianwulbern** [comment]
@brianchiu yep, will do.

**Comment by brianwulbern** [comment]
See ee-7.0.x here: https://github.com/brianchandotcom/liferay-portal-ee/pull/17600

**Pull request closed without merging**
