### PR TITLE
Lps 52586

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
CC @tmoreira2020

**Comment by brianchandotcom** [comment]
Any way we can remove the dependency of another jar into versions.xml? Ideally, I'd like it to, on startup, if it sees that the "jar" for hikari is misisng, download it from our CDN. We already do this for the mysql.jar, so it's definitely possible.

Thx.

**Comment by brianchandotcom** [comment]
So our "properties" shhould be smart enough to have another line for a url to a jar... etc. Thx. That way, this can scale for any connection pool we have.

**Comment by shuyangzhou** [comment]
@brianchandotcom always down from our CDN or maven repo? We don't have this jar(or any other jdbc pool jars) in our CDN, right?

@dantewang See DataSourceFactoryImpl.testClassForName() that's where do the download for mysql.jar, try to follow that example to auto download the current configured jdbc pool jar(if it is not already there)

**Comment by brianchandotcom** [comment]
Correct, right now, we don't have it in our CDN, but just use a URL that
works and eventually we'll put in the CDN url.

--
Brian Chan
Chief Software Architect
Liferay, Inc.
Enterprise. Open Source. For Life.
(626) 806-1190

**Comment by dantewang** [comment]
Got it. I'll try to download from Hikari's maven repo.

**Pull request closed without merging**
