### PR TITLE
LPS-108574 Display depot groups inside the role Define Permissions tab

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-108574](https://issues.liferay.com/browse/LPS-108574).<br><br>This updates the package names per you request in https://github.com/brianchandotcom/liferay-portal/pull/84705#issuecomment-586510825.<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez @4lejandrito

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Thanks a lot @drewbrokke!

**Comment by 4lejandrito** [comment]
Hi @drewbrokke, is there any reason why this was closed?

Thanks!

**Comment by drewbrokke** [comment]
@4lejandrito When I originally sent it there were merge conflicts that I wasn't getting locally. I'll resend right away this morning.

**Comment by drewbrokke** [comment]
resent as https://github.com/brianchandotcom/liferay-portal/pull/84839

**Comment by 4lejandrito** [comment]
Cool, thanks a lot!

**Pull request closed without merging**
