### PR TITLE
LPS-69661

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
/cc @tomwang2011 @shuyangzhou

We have about 120 violations.
You can get them by adding "tom.wang.flag=true" in source-formatter.properties.

After you have fixed the violations, you can revert https://github.com/brianchandotcom/liferay-portal/pull/49080/commits/261f06cca118e75e619f8fab980fd6612173c1e6

**Comment by hhuijser** [comment]
ci:reopen

**Comment by pyoo47** [comment]
ci:retest - https://loop.liferay.com/home/-/loop/feed/5383061

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
