### PR TITLE
LPD-28282 Disable CacheFilter by default. LanguageFilter is overlappi…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…ng most its filter target with CacheFilter, and LanguageFilter on purposely disabled pacge caching, which is making CacheFilter really useless.

@tinatian @vicnate5 please backport for LXC, thanks!

@victorhcunha please run a check for login, thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ec8cddf6ff...7af5ad9bc0

**Comment by victorhcunha** [comment]
Hi @shuyangzhou !
Here are the results for login test case:

Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | DB CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | --
Baseline | 0028e9e | 10207 | - | 278 | 3,3,3 | 94,94,93
PR | - | 9767 | -4.310767121 | 280 | 3,3,4 | 93,94.93

More details you can see in our [spreadsheet](https://docs.google.com/spreadsheets/d/1M6VK8GtY9kkv1EwhGW7vwrEENSzyT7zKz-wOh11ZHBo/edit#gid=2080751240) 
I will re-run the baseline test due to this variation in the result (compared to the daily results) and then will update the spreadsheet with the new round result.

**Comment by victorhcunha** [comment]
Hi @shuyangzhou !
Here are the results of a new round of login test case:


Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | DB CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | --
Baseline | 0028e9e | 10073 | - | 284 | 3,3,3 | 93,93,04
PR | - | 9761 | -3.09738906 | 274 | 4,3,3 | 94,93,93

The baseline was also run again (this is the same as daily monitoring)
More details you can see in our [spreadsheet](https://docs.google.com/spreadsheets/d/1M6VK8GtY9kkv1EwhGW7vwrEENSzyT7zKz-wOh11ZHBo/edit#gid=2080751240)

**Comment by shuyangzhou** [comment]
Hmm, this makes me really worrying about the test accuracy. In our test, the cache filter's `com.liferay.portal.servlet.filters.cache.CacheUtil` portalcache hit ratio is always 0, since none of our test URLs are cacheable. But the cachefilter has to prepare for the cache key no matter what, so it is pure waste. Removing it should be pure improvement at least for our login test. @slnn can you check the results to see whether there is something weird?

**Comment by slnn** [comment]
OK, got it

**Comment by slnn** [comment]
Hi @shuyangzhou 

I have checked the test result that @victorhcunha uploaded, I did not find something weird,  the  `com.liferay.portal.servlet.filters.cache.CacheFilter=false` should take effect in our tests because ehcache-jmx.htm did not contain any cache usage statistics about `com.liferay.portal.servlet.filters.cache.CacheUtil` on the result of pr.

Victor ran tests on main2 env,  but main2 env is not free, I used main3 env to recheck, as this pull request only changes the default value of `com.liferay.portal.servlet.filters.cache.CacheFilter`  in portal.properties from true to false, I run two tests: one is just set com.liferay.portal.servlet.filters.cache.CacheFilter=false in portal-ext.properties to override the default value(Test2), another just applies the pr and then rebuild the bundle(Test3), from test results I can see the improvement in disabling the CacheFilter is not big, but I do not see a regression.

Test | Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | DB CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | -- | --
Test 1 | Baseline(Enable Cache Filter) | 0028e9e | 10224 | - | 294 | 3,3,3 | 95,95,92
Test 2 | Disable Cache Filter by Apply com.liferay.portal.servlet.filters.cache.CacheFilter=false in portal-ext.properties of benchmark project to override the default value in portal.properties | 0028e9e | 10457 | 2.278951487 | 298 | 3,3,3 | 94,95,92
Test 3 | PR | - | 10301 | 0.7531298905 | 236 | 3,3,3 | 94,94,93


For details please see https://docs.google.com/spreadsheets/d/1M6VK8GtY9kkv1EwhGW7vwrEENSzyT7zKz-wOh11ZHBo/edit?usp=sharing

Regards
Lily

**Comment by shuyangzhou** [comment]
Ok, I don't expect this to be a big improvement. But it is a pure improvement, can not cause performance regression. I guess the current NUC system is still generating too much noise :(

**Pull request closed without merging**
