### PR TITLE
LPS-68836 buildLang

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by vicnate5** [comment]
@ealonso Portal does not start with this pull. Could you take another look?

```
12:14:14,272 ERROR [localhost-startStop-1][ModuleFrameworkImpl:1475] Unable to start bundle com.liferay.portal.background.task.api
     [exec] org.osgi.framework.BundleException: Could not resolve module: com.liferay.portal.background.task.api [40]
     [exec]   Unresolved requirement: Import-Package: com.liferay.portal.kernel.model; version="[1.0.0,1.1.0)"
```

**Comment by vicnate5** [comment]
ci:close

**Comment by brianchandotcom** [comment]
@ealonso these failures are real. Please resend. Thx.

**Pull request closed without merging**
