### PR TITLE
LPS-63357

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@mhan810 those 6 + 1 broken tests are known. Bchiu is going to disable it for now, some markup changed.

**Comment by mhan810** [comment]
@brianchandotcom sweet, once you merge this one i can send the next dependent

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2d85c4d425...65c6f38469

**Pull request closed without merging**
