### PR TITLE
LPS-124394, LRQA-64155 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-124394
https://issues.liferay.com/browse/LRQA-64155

This is only for master.

@ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure case is a unstable one not related to changes in PR.
Reported in https://issues.liferay.com/browse/LRQA-64155
See https://github.com/liferay-echo/liferay-portal/pull/3394
✔️ ci:test:stable - 9 out of 9 jobs passed
❌ ci:test:relevant - 23 out of 25 jobs passed in 2 hours 2 minutes

**Comment by jkappler** [comment]
@nhpatt, fyi

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/574783063c...664322860d

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
