### PR TITLE
LRDOCS-3643

### PR DESCRIPTION
**Pull request by Ithildir**
cc @jhinkey and @mwilliams2014

### CODE REVIEW

**Comment by jhinkey** [comment]
That's great, @Ithildir !

**Comment by mwilliams2014** [comment]
Awesome! Thx @Ithildir !

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8122064b77...dd83f4fbde

**Comment by brianchandotcom** [comment]
@codyhoag fyi.

**Pull request closed without merging**
