### PR TITLE
LPS-155715 

### PR DESCRIPTION
**Pull request by tinatian**
Hi @brianchandotcom , 
Rebase https://github.com/brianchandotcom/liferay-portal/pull/121144.
I do not understand your comment at https://github.com/brianchandotcom/liferay-portal/pull/121144#issuecomment-1203073266, this is needed because I am going to depend on ShardedModel to decide which type of cache you are going to use.

Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@tinatian see my comments in https://github.com/brianchandotcom/liferay-portal/pull/121144#issuecomment-1207205773

**Comment by tinatian** [comment]
@brianchandotcom reopen, please see comments at https://github.com/brianchandotcom/liferay-portal/pull/121144#issuecomment-1208733611

**Comment by tinatian** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Ahhhhh.. my bad @tinatian I didn't see https://github.com/brianchandotcom/liferay-portal/commit/3128928d85568fb05c898ee555f022290d0ddf95

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/01601a45d1...43524a75b2

**Pull request closed without merging**
