### PR TITLE
LPS-91855 SF

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c4ea20b643...87c02f3456

**Comment by brianchandotcom** [comment]
@JorgeFerrer this is in upstream now... see my changes (mainly cosmetic) except for one real memory leak ceaa1f2506ac718caeb79ad24c2b344eea0dffe0

Please verify my fix and changes. thx.

**Comment by JorgeFerrer** [comment]
Thanks Brian. I went over all the changes and they make sense.

**Pull request closed without merging**
