### PR TITLE
LPS-86298 SF

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by jpince** [comment]
@brianchandotcom PMD passed, everything else of concern looks network-related (IT)

**Comment by brianchandotcom** [comment]
@4lejandrito I made some changes and sent them to https://github.com/Preston-Crary/liferay-portal/pull/610

I don't understand your changes to PortalCapabilityLocatorImpl as deeply as @preston-crary knows this stuff. Sending it to him for review.

**Pull request closed without merging**
