### PR TITLE
LPS-90124

### PR DESCRIPTION
**Pull request by amosfong**
Please backport to 7.2 and 7.1, thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@amosfong merged...

@jpince we need to fix these tests ..

**Comment by brianchandotcom** [comment]
@amosfong I didn't backprot to 7.0.x.. just 7.1 and 7.2

**Comment by jpince** [comment]
@brianchandotcom yes, one of our goals for Beta is to have 100% passing acceptance tests.

**Comment by jpince** [comment]
@wesleygong @ctampoya sigar.jar removed in 7.1.x & master.

**Comment by wesleygong** [comment]
thanks @jpince!

**Pull request closed without merging**
