### PR TITLE
LPS-67914 Theme is broken on Windows, exclude it for now

### PR DESCRIPTION
**Pull request by Ithildir**
Hi Brian,
The new `frontend-theme-porygon` cannot be built on Windows because of a problem in the autogenerated `npm-shrinkwrap.json`. Instead of fixing the file manually, I'm going to write a Gradle task people can call to generate it correctly.

Thank you!

cc @jbalsas and @marcoscv-work

**_This pull will no longer automatically close if this comment is available. If you believe this is a mistake please re-open this pull by entering the following command as a comment.**_

### CODE REVIEW

**Comment by jbalsas** [comment]
👍 thanks!

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
