### PR TITLE
LPS-95476 Port side-navigation.js jQuery plugin from Clay to vanilla JS

### PR DESCRIPTION
**Pull request by wincent**
~Three~ Four main things going on here:

- LPS-95476, the main one, is porting the `sideNavigation()` jQuery plugin to vanilla JS.
- LPS-95477 is including a copy of the old plug-in for users who have the frontend-js-jquery-web module active, for backwards compatiblity.
- LPS-95479 does the same for `collapsibleSearch()`.
- LPS-95728 makes copies of bootstrap.js and popper.js available to users of frontend-js-jquery-web.

In effect, there should be no change for anybody who has the frontend-js-jquery-web module activated (and it is by default), but all of our internal instances of side navigation will be running on the new implementation. Shipping these as one PR because they go logically together.

To see the delta between the jQuery version of the plugin and the final version, see [this diff](https://github.com/wincent/liferay-portal/compare/ab73366...wincent/LPS-95476/remove-jquery-side-nav-plugin#diff-f58585e56fdb4bffd19330b0c33c9883).

The plug-in is several years old and has accumulated a bunch of configurability and two parallel internal implementations (the "simple" one and the standard one). It is used in a bunch of subtly different ways throughout liferay-portal. As such, this is a very conservative port, aimed to preserve the original behavior as exactly as possible. I didn't do any aggressive (AKA risky) refactoring. I broke it up into small commits so if you are wondering why something got deleted or changed you can generally find an explanation in the commit messages. I was also able to use this granularity to bisect problems during development. I made [these notes](https://gist.github.com/wincent/437ff6d84a481b0c985589a74ee73d88) to summarize what I learned.

### CODE REVIEW

**Comment by wincent** [comment]
@brianchandotcom, feel free to squash if you think that's appropriate. Lots of commits here because I needed to test each step individually to have confidence in the change.

**Comment by wincent** [comment]
ci:reopen

I didn't touch the file with the SF error — it probably just checked that file because I made changes in the module — so I am re-opening this one. I'd prefer to leave Java formatting changes like this one to someone with more expertise. 😁

**Comment by wincent** [comment]
I believe the "test:relevant" failure is unrelated.

**Comment by brianchandotcom** [comment]
Thx @wincent (sorry CI was so unstable today, I screwed it up late last night - hope to fix it by end of my day today)

I merged this as is.

@jbalsas @wincent we have *-*.js and *_*.js that's exposed in this pull.

Can we decide on one and stick to it? Or at least have some discernible pattern (I can't see one right now)

Thx.

**Comment by wincent** [comment]
Good catch @brianchandotcom. Thanks. The pattern is supposed to be underscores. Those ones with the hyphen snuck in at the end because they were copied from the clay-css project , where the convention is the the opposite.

I'll send a PR tomorrow that changes the names to use underscores be consistent.

(In the longer term, I'd like to talk to @jbalsas about changing the names in all of our projects to be the same, and specifically, I'd suggest that we follow (what seems to me to be) the Java pattern, where each file name reflects the main class defined inside it. So in the case of `SideNavigation`, that would mean `SideNavigation.js` etc.)

**Comment by jbalsas** [comment]
Hey @brianchandotcom, the `-` where indeed an oversight when porting over the plugins (which in jquery world use that naming strategy).

@wincent, the pattern we are following (or should be) is: 
- Camel case for files that export a class after the class` name
- Snake  case for files that export pure functions after the function name

I've created https://github.com/liferay/liferay-frontend-guidelines/issues/4 so we go over this and document this internally for the future

**Comment by wincent** [comment]
Follow-up for the non-conforming names is: https://github.com/brianchandotcom/liferay-portal/pull/74126

**Pull request closed without merging**
