### PR TITLE
Remove unnecessary Gradle dependencies

### PR DESCRIPTION
**Pull request by Ithildir**
Hi,
Please let this pull finish.

Thank you!

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:reopen

**Comment by Ithildir** [comment]
The semver error is fixed at https://github.com/brianchandotcom/liferay-portal/pull/49397.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@Ithildir can you backport for the ones that are necessary? Thx.

**Comment by Ithildir** [comment]
Done: https://github.com/brianchandotcom/liferay-portal/pull/49432

**Pull request closed without merging**
