### PR TITLE
LPS-112136 Update jQuery to v3.5.0

### PR DESCRIPTION
**Pull request by wincent**
This is a manual forward of https://github.com/wincent/liferay-portal/pull/217

That pull [contains no unique failures](https://github.com/wincent/liferay-portal/pull/217#issuecomment-617510974).  Once [LRCI-1208](https://issues.liferay.com/browse/LRCI-1208) is implemented, we will be able to forward such pulls using `ci:forward`, but for now, @john-co [suggests](https://github.com/wincent/liferay-portal/pull/211#issuecomment-617321115) that we forward manually, so I'm trying to do that now.

Original PR message follows:

---

Needed for a security fix

Release notes: [https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/](https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/) 

Since this is a security fix, we (frontend infra) will also need to backport this to `7.2.x` once it's merged into `master` and support will backport to `7.1.x` and `7.0.x`

According to the release notes, 

> The main change in this release is a security fix, and it’s possible you will need to change your own code to adapt. 

This doesn't directly affect DXP, because jQuery is no longer used internally, but it may require code changes in customer code in the unlikely event that they rely on the old behavior of `jQuery.htmlPrefilter`.

---

cc @julien

### CODE REVIEW

**Comment by wincent** [comment]
ci:reopen

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/886fba4cc5...d6f29d8742

**Pull request closed without merging**
