### PR TITLE
LPS-80982 Status labels should be all caps (ex: "DONE" instead of "Done")

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-80982](https://issues.liferay.com/browse/LPS-80982).<br><br>/cc @pei-jung @dejuknow

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@drewbrokke @dejuknow are you sure you want all CAPS? So ugly that way... We don't do all caps anywhere else..

**Comment by drewbrokke** [comment]
@brianchandotcom it matches the UX design we were given - if there's an inconsistency it needs to be brought to their attention.

**Comment by drewbrokke** [comment]
cc @victorvalle please see Brian's comment: https://github.com/brianchandotcom/liferay-portal/pull/59018#issuecomment-391869283

**Comment by victorvalle** [comment]
@brianchandotcom we use CAPS in small labels. The reason to do that is because the font-size is small, 10px, which in lowercase would be hard to read and incur in accessibility errors. CAPS have more "body" in are easy to read. 

We use CAPS in other places only for hierarchy purposes. We use them in sections as form sections of first and second level. And, we use them in table, list and card sections.

On the other hand, we are removing CAPS from the breadcrumb that is not a normal place where to use them. The aforementioned ones are good practices.

**Pull request closed without merging**
