### PR TITLE
LPS-92085

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Reverting old fix as it's causing regressions. If the old issue still exists (can't really remember what exactly was going on there), will fix both problems properly.

**Comment by brianikim** [comment]
Hello @brianchandotcom ,

Can this be reopened and retested if need be? The failures do not look related.

Sincerely,
Brian I. Kim

**Comment by hhuijser** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
