### PR TITLE
LPS-92584 buildLang

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchiu** [comment]
ci:test:relevant:norebase

**Comment by brianchiu** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@sandrodw3 

-- Unmapped --

The -- 

should be part of the UI and not part of the translation...

It's going to be -- in any language. Please fix and resend.

**Pull request closed without merging**
