### PR TITLE
LPS-159772 baseline

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-159772

@ealonso

### CODE REVIEW

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See [liferay-echo#7560](https://github.com/liferay-echo/liferay-portal/pull/9626)

:heavy_check_mark: ci:test:stable - 28 out of 28 jobs passed
:x: ci:test:relevant - 186 out of 192 jobs passed in 2 hours 41 minutes

**Comment by ozysouza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/28999bd5ec...79f2bdc83e

**Comment by brianchandotcom** [comment]
@ealonso @ozysouza just 79f2bdc83e5eefae92f4a059ae2bfc5d570e52dd thx

**Pull request closed without merging**
