### PR TITLE
LPS-86549

### PR DESCRIPTION
**Pull request by petershin**
@gamerson

### CODE REVIEW

**Comment by gamerson** [comment]
cc @lawrence-lee  I've bumped the project template tokens, that may conflict with one of your PRs.

**Comment by brianchandotcom** [comment]
@petershin @gamerson merged.

**Comment by brianchandotcom** [comment]
@codyhoag fyi

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/41a1d3c45a...814d04d267

**Pull request closed without merging**
