### PR TITLE
LPS-88809 Support Context-based segment criteria

### PR DESCRIPTION
**Pull request by epgarcia**
@darquesdev

### CODE REVIEW

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
reviewed ;)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/05fb404b14...47e7af22ac

**Comment by brianchandotcom** [comment]
@epgarcia please see my changes in upstream. Thx.

**Pull request closed without merging**
