### PR TITLE
SYNC-1722

### PR DESCRIPTION
**Pull request by mikemanyoung**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@pyoo47 what happened here?

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a5868edee2...8cc78cebda

**Comment by pyoo47** [comment]
@brianchandotcom This failed because the LoadBalancer service returned and empty result. I've never seen this happen before. This was probably a fluke incident.

**Pull request closed without merging**
