### PR TITLE
LPS-67830 Allow administrators to configure captcha using System Settings, allowing export and import of configurations

### PR DESCRIPTION
**Pull request by xbrianlee**
https://issues.liferay.com/browse/LPS-67830
https://issues.liferay.com/browse/LRQA-30920

### CODE REVIEW

**Comment by pei-jung** [comment]
Hi @brianchandotcom,

Can you review this when you get a chance? Thanks!

**Comment by xbrianlee** [comment]
Closing this pull. Will resend.

**Comment by xbrianlee** [comment]
Resent in https://github.com/brianchandotcom/liferay-portal/pull/48055.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e8ca6e6555...33f9875c10

**Comment by brianchandotcom** [comment]
@pei-jung 

1.) *Url, to *URL

**Pull request closed without merging**
