### PR TITLE
LPS-62210

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@pyoo47 and here too..

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6d703ca406...4b3d0a8f54

**Comment by brianchandotcom** [comment]
@csierra see upstream for my changes.

**Pull request closed without merging**
