### PR TITLE
LPS-96198 Remove descriptions per Brian's request

### PR DESCRIPTION
**Pull request by matethurzo**
@brianchandotcom based on this request: https://github.com/brianchandotcom/liferay-portal/pull/74015#issuecomment-498520246

1) moved everything to rest-api, rest-client, rest-impl, rest-test respectively, applied renames
2) removed descriptions from openapi yaml
3) reworked exceptions following headless-delivery - using exception mappers

cc @danielkocsis

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/54822ba5f5...3ea4465c37

**Comment by brianchandotcom** [comment]
@matethurzo see upstream for my changes (please resend based on my comments)

@preston-crary can you review the usage of:

```
	@Reference(
		cardinality = ReferenceCardinality.MULTIPLE,
		policy = ReferencePolicy.DYNAMIC, unbind = "_removeCTConfiguration"
	)
	private void _addCTConfiguration(CTConfiguration<?, ?> ctConfiguration) {
		_ctConfigurations.add(ctConfiguration);
	}
```

in SettingsResourceImpl (merged upstream, but I think you have a new simpler pattern)

@nhpatt please review modules/apps/change-tracking/change-tracking-rest-impl/rest-openapi.yaml (it looks OK to me but I'd feel much happier if you put your expert eye on it)

Thx.

**Comment by nhpatt** [comment]
Reviewed, everything is fine, asking some doubts on slack :)

**Comment by Preston-Crary** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/74148

**Pull request closed without merging**
