### PR TITLE
Lps 171229

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/432852e6d8...fce1ac4c43

**Comment by brianchandotcom** [comment]
@shuyangzhou can you resend this PR? it conflicts with the revert in https://github.com/brianchandotcom/liferay-portal/pull/127702

**Comment by shuyangzhou** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/127734

**Pull request closed without merging**
