### PR TITLE
LPS-56537 - Extract frontend-editors-web to individual editor modules

### PR DESCRIPTION
**Pull request by mjbradford89**
Hey Brian,

Attached is an update for https://issues.liferay.com/browse/LPS-56537.

Please let me know if there are any issues.

Thanks!

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@mjbradford89 let's go over this on Monday, still has a few issues. Thx.

**Comment by jbalsas** [comment]
Hey @brianchandotcom, @mjbradford89!

Since we're on this... could you consider moving the vendor/third-party dependencies out from `portal-web/third-party` and into the specific modules? This way, we won't have to do it and change the build of those modules afterwards to update them. 

In addition, there's some stuff in the `frontend-js-web` that should be moved to some of these editor modules. I can take care of that after this done.

Thanks!

**Comment by brianchandotcom** [comment]
@jbalsas I just talked to @mjbradford89 about something else, so he'll fix that first, and get this pull out of the way.

Then, @mjbradford89 please go over the request from @jbalsas 

Thx guys.

**Comment by jbalsas** [comment]
@brianchandotcom sounds good, thanks a lot!

**Comment by mjbradford89** [comment]
new pull: https://github.com/brianchandotcom/liferay-portal/pull/31184

**Pull request closed without merging**
