### PR TITLE
LPS-71288 Baseline

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@ealonso this doesn't look right? One is a major breaking change, and the other is a minor change. Can we add the necessary deprecated calls to prevent a major change? Thx.

**Comment by brianchandotcom** [comment]
To be more clear @ealonso 

modules/apps/collaboration/blogs/blogs-service/bnd.bnd went from 1.1.1 to 1.2.0

yet modules/apps/collaboration/blogs/blogs-service/src/main/resources/com/liferay/blogs/util/packageinfo went from 1.0.0 to 2.0.0

That's weird.

Thx.

**Comment by ealonso** [comment]
Hey @4lejandrito,

Could you please take a look at it?

Thanks!!

**Comment by 4lejandrito** [comment]
Hi @brianchandotcom and @ealonso,

Is it possible that baseline, in master, is checking against the published jars in `ee-7.0.x`? 

I realized this error started happening since https://github.com/brianchandotcom/liferay-portal-ee/pull/16550 went through. When backporting that story I noticed that the structure of the module (blogs-service) was quite different to the one in master. The package `com.liferay.blogs.util` wasn't even exported in the `bnd.bnd` (it is on master) so I exported it just with the class we needed. 

The error that baseline is throwing complains about several classes and methods being new, but they were already there... I suspect that is because it is checking against the new jars published from `ee-7.0.x`. If that is the case, I didn't know that was the way it worked and it will probably need a fix to put both master and ee-7.0.x version numbers back in sync. 

I'll have a chat with @adolfopa too.

**Comment by 4lejandrito** [comment]
For reference, these are the changes in master and ee-7.0.x:

Original PR in master: https://github.com/brianchandotcom/liferay-portal/pull/47598
Backport: https://github.com/brianchandotcom/liferay-portal-ee/pull/16550

**Comment by 4lejandrito** [comment]
The problem is I made a mistake when backporting the story. I didn't notice that one of the classes (`com/liferay/blogs/util/BlogsEntryAttachmentFileEntryReference`) was in a different package in `ee-7.0.x` (`com/liferay/portlet/blogs/BlogsEntryAttachmentFileEntryReference`). This causes the signature of one of the exposed methods to mismatch. I will fix it in `ee-7.0.x` and once the change is published this should not happen again.

**Comment by 4lejandrito** [comment]
Fix here: https://github.com/adolfopa/liferay-portal/pull/519

**Pull request closed without merging**
