### PR TITLE
master-qa-25103

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-25103

### CODE REVIEW

**Comment by kenjiheigel** [comment]
@brianchandotcom @brianchiu, this is another attempt to reduce the random portal instance issues. I believe the actual cause to be something related to either portal or possibly the environment of the servers. As these issues have not been reproducible consistently on CI, nor reproducible at all manually, the changes in this pull will attempt to work around the failures.

**Comment by brianchandotcom** [comment]
@kenjiheigel can you come explain this to me? thx.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/35f13ec702...8e6aacbcd3

**Comment by kenjiheigel** [comment]
@brianchandotcom 
Summary of what we talked about (for reference): 
* The new macro is used for the test infrastructure (less strict, more widely used). The existing macro is used to actually test portal instances functionality (more strict, less widely used). 
* The problem isn't solved with this, and we will need to collaborate with Shuyang or another developer at some point to pinpoint the actual issue. We'll focus on debugging the actual issue in [LPS-65733](https://issues.liferay.com/browse/LPS-65733) and [LRQA-25151](https://issues.liferay.com/browse/LRQA-25151)

**Pull request closed without merging**
