### PR TITLE
LPS-65153 Redeploy of com.liferay.portal.search.elasticsearch makes Search unusable

### PR DESCRIPTION
**Pull request by arboliveira**
Addressed https://github.com/brianchandotcom/liferay-portal/pull/39587#issuecomment-219487721.
- `AssertUtils` moved to `com.liferay.portal.search.test.util`
- Method that returns `Path[]` is now called `getInstalledPluginsPaths()`

Authors: @arturbr @arboliveira
Reviewer: @arboliveira

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:stop (CI was messed up)

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by arboliveira** [comment]
Rebased on latest master. Test failures seemed unrelated.

ci:retest

**Comment by arboliveira** [comment]
Test failures seem unrelated.

**Comment by arboliveira** [comment]
Rebased on latest master.

ci:retest

**Comment by arboliveira** [comment]
Test failures are unrelated.

**Comment by brianchandotcom** [comment]
@arboliveira same with

"String pluginsPath"

Please rename that to String pluginsPathString..

That same class has a "Path xyzPath"

There may be others, please review all var names so they are obvious.

Thx.

**Pull request closed without merging**
