### PR TITLE
LPS-75143 build.gradle

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:open

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/afb5778580...ef326a931b

**Comment by brianchandotcom** [comment]
@ealonso will asset-publisher-service eventually include service.xml? If not, you should rename that module. Thx.

**Pull request closed without merging**
