### PR TITLE
LPS-181759 Support for SQL triggers

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f49620985f...8ec9e1d195

**Comment by brianchandotcom** [comment]
@kevhlee @achaparro please review my changes. I may have broken stuff.

**Comment by kevhlee** [comment]
Hey @brianchandotcom, commit 9b6f492b5c3f1fc06a14ea738c4842654568fe89 will cause the `DB.syncTables()` to fail for Postgres (the trigger function needs to be created first). We will send a pull request to fix this.

**Comment by kevhlee** [comment]
Hey @brianchandotcom, commit c3d8de97e39d1975aebac8efd9f70a2d69de8240 is also problematic 😅. `_createTriggerFunction()` is called before we construct the trigger function statement using the `StringBundler` (in other words, we are constructing a trigger function that does nothing). We would need `_createTrigger()` and `_createTriggerFunction()` after all `StringBundler` code.

**Pull request closed without merging**
