### PR TITLE
LPS-93507 Poshi Script SF: Braces that are in the wrong line

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LPS-93507

@hhuijser, @ling-alan-huang

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:reopen

**Comment by ling-alan-huang** [comment]
Reopened, SF failures are not related to this pull request.

**Comment by ling-alan-huang** [comment]
All test failures are not related to my changes.

**Comment by brianchandotcom** [comment]
Very nice :)

**Pull request closed without merging**
