### PR TITLE
LPS-81596 SF

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@alinedoleron can you resend this one? Rebase error. Thx.

**Comment by brianchandotcom** [comment]
@alinedoleron nvm, I reverted the changes from https://github.com/brianchandotcom/liferay-portal/pull/59948 and merged in this one. We're good to go now.

**Comment by alinedoleron** [comment]
ok, @brianchandotcom. Thank you!

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
