### PR TITLE
LRQA-25026 Move some methods used for matrix plugin workaround into JenkinsResultsParserUtil.

### PR DESCRIPTION
**Pull request by pyoo47**
There are some methods that I wrote in beanshell for the Matrix plugin bug workaround that I think belongs in JenkinsResultsParserUtil. I've also used some of these methods to simplify the implementation of the FilePropagator class so that we no longer need to create a shell script file when executing the ssh rsync commands.

**Please publish a new jenkins results parser jar after merging this pull.**

### CODE REVIEW

**Comment by brianchiu** [comment]
Poshi test failures are unrelated (same two failures happened here: https://github.com/brianchandotcom/liferay-portal/pull/39640)

@vicnate5
Can you look into those failures?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2c731b9faf...aeef2e1460

**Comment by brianchandotcom** [comment]
@pyoo47 published...

**Comment by vicnate5** [comment]
@brianchiu I am looking into this. It seems to be a regression as the portal is throwing error:
```
com.liferay.portal.security.service.access.policy.exception.NoSuchEntryException: No SAPEntry exists with the key {companyId=32618, name=SYNC_TOKEN}
```

**Pull request closed without merging**
