### PR TITLE
LPS-52658 SF

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
oops wrong update

**Comment by rotty3000** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/d530f72b73...146e46efb0

**Comment by brianchandotcom** [comment]
@rotty3000 I applied it to asset-tags-admin-web 146e46efb06d18e18f5f8c87e3315d24b3ec1485

Can you review that.

also, I see that this is not applied for bookmarks-web, polls-web, and wiki-web, just wanted to confirm that was intentional.

Thx

**Comment by rotty3000** [comment]
>
> @rotty3000 <https://github.com/rotty3000> I applied it to
> asset-tags-admin-web 146e46e
> <https://github.com/brianchandotcom/liferay-portal/commit/146e46efb06d18e18f5f8c87e3315d24b3ec1485>
>
> Can you review that.
>
Done!

> also, I see that this is not applied for bookmarks-web, polls-web, and
> wiki-web, just wanted to confirm that was intentional.
>
This last was intentional since I had not tested this change with these,
and they should work the old way. However, I've tested a similar change and
will forward it with an additional set of changes.

**Pull request closed without merging**
