### PR TITLE
LPS-58412 support for storing the priority of web content articles

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @planetsizebrain

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
PortalClientBuilderTest.testPortalClientBuilder is a real test failure. Please resend. Thx.

**Comment by planetsizebrain** [comment]
@juliocamarero @brianchandotcom is this a result of my changes and something I can help with fixing?

**Comment by juliocamarero** [comment]
Don't worry Jan, I will make sure this gets merged :)

I already fixed that problem and resent on Friday but there were some issues with the CI, so I am resending again here today: https://github.com/brianchandotcom/liferay-portal/pull/30095

thanks a lot!

**Pull request closed without merging**
