### PR TITLE
LPS-75140 SF - Use lambda

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/c1ccae957a...b346f828a4

**Comment by brianchandotcom** [comment]
@sergiogonzalez I had to run SF for it. See b346f828a4c21a72d3b8409eee7fdd5b966b4903

Thx.

**Comment by brianwulbern** [comment]
fixed and resent https://github.com/brianchandotcom/liferay-portal/pull/52300

**Pull request closed without merging**
