### PR TITLE
LPS-63466 Rename Site Users for Site Members 

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by jkappler** [comment]
@evannagayama, could you please check the last two commits? We had to do some changes in the tests since a label was changed in control menu. We updated the locators accordingly and also changed the name of the macro, to reflect that it was Members related and not Users

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1ea2a3c1d2...193bdac2f6

**Comment by evannagayama** [comment]
@jkappler it looks perfect. Thanks for making the test fixes!!! :+1:

**Pull request closed without merging**
