### PR TITLE
Lps 72113

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
CC @rotty3000

**Comment by Preston-Crary** [comment]
@shuyangzhou did you mean to close this?

**Comment by shuyangzhou** [comment]
No, I did not mean that, must be a mistake somehow.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6842a79905...334c2babe0

**Pull request closed without merging**
