### PR TITLE
LRQA-43984 | master

### PR DESCRIPTION
**Pull request by jpince**
https://issues.liferay.com/browse/LRQA-43984
@brianchandotcom I will only backport the ignore for `SystemEventTest.java`, `StagingGroupHelperTest.java` is passing in 7.1.x.

@matethurzo ignoring these tests, will try to narrow down a root cause today.

### CODE REVIEW

**Comment by jpince** [comment]
@kmaria

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by jpince** [comment]
ci:stop

**Comment by jpince** [comment]
@kmaria @matethurzo `SystemEventTest` was failing in the pull you sent to remove the ignores, https://github.com/brianchandotcom/liferay-portal/pull/63855#issuecomment-427434792. Can you please look into these again?

I'm still trying to figure out what caused the `StagingGroupHelperTest.java` failures.

**Comment by jpince** [comment]
@jhendley @jrhoun @reizero00

**Pull request closed without merging**
