### PR TITLE
LPS-96187 Fix language change when using display pages

### PR DESCRIPTION
**Pull request by marco-leo**

### CODE REVIEW

**Comment by marco-leo** [comment]
Hi @brianchandotcom we will need to backport this, as in need for a commerce customer waiting for the fix.

**Comment by jpince** [comment]
@pavel-savinov @jkappler fyi

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ab4a67f2cb...03a7ff238f

**Comment by brianchandotcom** [comment]
@brianchiu please make an automated test for this. Thx.

**Comment by brianchandotcom** [comment]
@marco-leo done, backported to 7.1.x. Will be in the next FP.

**Pull request closed without merging**
