### PR TITLE
Lps 70451

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by brianwulbern** [comment]
Looks like the same missing file failure as described here: https://github.com/brianchandotcom/liferay-portal/pull/47429#issuecomment-285222315

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@tomwang2011 please send me a backport. Thx.

**Pull request closed without merging**
