### PR TITLE
LPS-65030

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by brianchiu** [comment]
@vicnate5
Can you look into these? 3 tests failed (not just the 1).

https://testray.liferay.com/home/-/testray/runs/39849082?_1_WAR_testrayportlet_testrayTeamId=1235217

**Comment by vicnate5** [comment]
Yes. I can look into this right now

**Comment by vicnate5** [comment]
@brianchiu Forms failure may have been a fluke, or something related to portal instances. I was unable to reproduce it locally.

**Comment by vicnate5** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/89067f6b7f...992de1f1ca

**Pull request closed without merging**
