### PR TITLE
LPS-77095 Pass the httpServletRequest to the getRequiredFieldsWarningMessageHTML method instead of the ddmFormRenderingContext

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@rafaprax rebase error, please resend. Thx.

**Comment by rafaprax** [comment]
@pedroqueiroz Could you please rebase and resend this one? Thx

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Resent at https://github.com/brianchandotcom/liferay-portal/pull/55977.

**Pull request closed without merging**
