### PR TITLE
LPS-122403 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by brianwulbern**
Tested on https://github.com/brianwulbern/liferay-portal/pull/286

cc @petershin

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:reopen (already tested)

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1aec6852d3...0f0be8d20c

**Comment by brianchandotcom** [comment]
@brianwulbern I regenerated language keys all the way back to 7.0.x.

**Comment by brianwulbern** [comment]
Thanks, @brianchandotcom!

**Pull request closed without merging**
