### PR TITLE
LPS-102577 generate batch annotations

### PR DESCRIPTION
**Pull request by javiergamarra**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@nhpatt let's chat tomorrow about it? I was hoping to "batch" everything implicitly.. without ever having to modify the YAML file.

**Comment by nhpatt** [comment]
Ok!

**Comment by brianchandotcom** [comment]
@nhpatt please resend after talking to @marcoleo thx!

**Comment by nhpatt** [comment]
Will do :)

**Pull request closed without merging**
