### PR TITLE
LPS-97526 Fix errors

### PR DESCRIPTION
**Pull request by wincent**
Fixes the errors reported here:

https://github.com/brianchandotcom/liferay-portal/pull/75660#issuecomment-511035136

Specifically:

- Missing `@returns` tag values.
- `<>`/`</>` shorthand syntax for `<React.Fragment>`/`</React.Fragment>` which is causing some as-yet-undetermined tool to choke.

I'm trying to identify the tool which isn't happy with the shorthand and if I can't find or upgrade it I'll add a lint to prevent shorthand usage.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0fb3fcead4...c6bf0aa30f

**Comment by brianchandotcom** [comment]
Yes @wincent please find the tool that can't do the shorthand so we can go back to it (shorthand is much prettier.. no pun intended),

Then, let's enforce shorthand is ALWAYS used and ban the longhand.

**Comment by brianchandotcom** [comment]
@wincent this does not cherry pick to 7.2.x (I don't think 7.2.x needs it, but I need you to verify/double check)

To speed things up, make sure to use git worktree so you don't have to keep doing git checkout of branches (you'll end up having to have a dedicated dir just for 7.2.x since I need your help more in 7.2.x as the branches diverge)

**Comment by wincent** [comment]
> I don't think 7.2.x needs it, but I need you to verify/double check

@brianchandotcom: yes, that is correct. I checked with @andresfulla, who added these files originally. All the new work in React on layout-content-page-editor isn't being backported at this time. Mentioning @epgarcia as well because I believe he is familiar with the plans, and @jbalsas who wants to be aware of which things are being backported and which aren't.

I'll set up a 7.2 worktree in any case, and will see if I can split PRs so that backportable and not-backportable bits don't get mixed together in the same PRs.

**Comment by wincent** [comment]
> Yes @wincent please find the tool that can't do the shorthand so we can go back to it (shorthand is much prettier.. no pun intended),
> 
> Then, let's enforce shorthand is ALWAYS used and ban the longhand.

So, I isolated the tool that was choking on the shorthand. It's jsdoc v3.5.5. If we upgrade to v3.6.3 we'll be able to handle shorthand and I can add auto-enforcement on top of that. I sent [this PR](https://github.com/petershin/liferay-portal/pull/587) to @petershin because I am not sure how to properly test the update to the Gradle JSDoc plugin.

**Comment by wincent** [comment]
> Then, let's enforce shorthand is ALWAYS used and ban the longhand.

Follow-up that does this is: https://github.com/brianchandotcom/liferay-portal/pull/76756

**Pull request closed without merging**
