### PR TITLE
LPS-143278 Refining the DXP Cloud Setup Step to Finalize

### PR DESCRIPTION
**Pull request by joseabelenda**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@joseabelenda @kevenleone @jairmedeiros rebase error, please resend? Thx.

**Comment by jairmedeiros** [comment]
Just starting reviewing :)

**Comment by joseabelenda** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
duplicate of https://github.com/brianchandotcom/liferay-portal/pull/110822

**Pull request closed without merging**
