### PR TITLE
LPS-82850 Fixes bus leaks

### PR DESCRIPTION
**Pull request by csierra**
/cc @topolik @CAustin582 @Ithildir @jpince
hey... we have found a memory leak in a wrong interaction with CXF 3.2.4
This update solves it. Could we please cache this snapshot?
sorry for the noise... but it is best we have caught this now

### CODE REVIEW

**Comment by csierra** [comment]
ci:stop

**Comment by csierra** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@ithildir can you cache it and resend it to me? Thx.

**Comment by Ithildir** [comment]
Sent to https://github.com/csierra/liferay-portal/pull/433.

**Pull request closed without merging**
