### PR TITLE
LPS-57816 Properly name the group of document library

### PR DESCRIPTION
**Pull request by ipeychev**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/6047e30262...1e68a18e2e

**Comment by brianchandotcom** [comment]
@ipeychev I sorted it in 1e68a18e2eed2b315c45b5d6d6687ceafbe954e7 

Can you double check my work? Thx.

**Comment by ipeychev** [comment]
@brianchandotcom 

Yeah, Brian, that sorting should be OK, thanks!

**Pull request closed without merging**
