### PR TITLE
LPS-64679 Add gradle dependencies

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4388f162c8...7b691eb958

**Pull request closed without merging**
