### PR TITLE
LPS-82261 ServiceBuilder DTD Version parsing

### PR DESCRIPTION
**Pull request by Preston-Crary**
Thanks @tomwang2011 for your help!

@brianchandotcom, I skipped the service.xml files inside modules/sdk since I'm not sure we want to change them and they were not modified by the previous commits.

CC @shuyangzhou

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8c80f8e16c...0d6a8c7cff

**Comment by brianchandotcom** [comment]
@dougwong this fixes your issue..

**Comment by jpince** [comment]
@Preston-Crary I think you forgot to rebuild services after committing? See https://github.com/liferay/liferay-portal/compare/7ed1f184db13111a46759a43f4fc363b7ba017bd...5d1585f6e3af8fade2fa9c84ce1cbe31dccb43f3

**Comment by Preston-Crary** [comment]
@jpince yes.  I thought I updated all the service.xml files, but it looks like some of them are using 6.2 versions of the DTDs.

**Pull request closed without merging**
