### PR TITLE
Lps 71745

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by tomwang2011** [comment]
CC @drewbrokke

Hi Brian, during 80bcc3a812c04d6169ffad7c8556501f75ff2b4e an older version of `DLProcessorRegistryImpl` that did not contain the `destroy()` method was copied to modules. In 0e92d2ee00a825810648484ea598477389a341c1 I added back the `destroy()` logic in the `deactivate` logic, thanks!

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@tomwang2011 please see my changes in upstream. I cherry picked them to 7.0.x.

**Comment by drewbrokke** [comment]
@tomwang2011 thank you for catching this!

**Pull request closed without merging**
