### PR TITLE
LPS-60972

### PR DESCRIPTION
**Pull request by Ithildir**
Hi!
Can you please publish the new `gradle-plugins`?

Thank you! :blush:

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
<p>The Pull Request Tester will be down until <strong>December 28, 2015 @ 5:00 PM PDT</strong>.</p>

<p>See this <a href="https://issues.liferay.com/browse/LRQA-18839">JIRA Ticket</a> for more information.</p>

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/98ef41a802...da96af578c

**Comment by brianchandotcom** [comment]
@Ithildir published a new one.

**Pull request closed without merging**
