### PR TITLE
Lps 63652

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
CC @mhan810

**Comment by mhan810** [comment]
@migue fyi

**Comment by migue** [comment]
Nice

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4f802bb362...86ad98629a

**Comment by brianchandotcom** [comment]
@hhuijser can you SF enforce this new pattern? Thx. Upgrade classes should never have the string "alter table " or "alter_column_type " in it.

Thx.

**Comment by shuyangzhou** [comment]
alter_column_name too.

**Comment by hhuijser** [comment]
@shuyangzhou 

We still have like 50 cases of "alter table * drop/add"
Is there a reason those are not changed or do we simply still need to do those?

**Comment by shuyangzhou** [comment]
They are not doing the upgradeTable() fallback, therefore can not apply to them,

**Pull request closed without merging**
