### PR TITLE
LPS-68268 SF

### PR DESCRIPTION
**Pull request by marcellustavares**
cc @inacionery

### CODE REVIEW

**Comment by inacionery** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@pyoo47 fyi

**Comment by pyoo47** [comment]
@brianchandotcom I think this was a fluke. There was a communications failure between the master and the slave.
```
[EnvInject] - [ERROR] - [EnvInject] - [ERROR] - Problems occurs on injecting env vars as a build step: java.io.IOException: remote file operation failed: /opt/dev/projects/github/liferay-jenkins-ee at hudson.remoting.Channel@3320b6d3:cloud-10-0-17-16
```

**Pull request closed without merging**
