### PR TITLE
LRQA-28693 Create a mirrors-get custom Ant task

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-28693

This pull also implements

https://issues.liferay.com/browse/LRQA-25155
LRQA-25155 Modify mirrors-get macrodef to not prepend with '`http://mirrors.lax.liferay.com`' if it already exists.

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:reopen

Failures are caused by bundle distribution nodes running out of space.

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/65164363b0...5b852b4c6b

**Pull request closed without merging**
