### PR TITLE
LRQA-39789 Add ability to set the status within the PullRequest

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-39789

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/deede2bc6f...c4413ed5c0

**Pull request closed without merging**
