### PR TITLE
LPS-107537 Missing robots tab for the display page templates

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Thanks @pavel-savinov!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5e80fadbb8...e8e98d623c

**Pull request closed without merging**
