### PR TITLE
LPS-67807 Avoid duplicates

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @ealonso

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@adolfopa does predictable order matter? If so, you should use a LinkedHashSet.

Please send a follow up pull if that matters. Thx.

**Comment by adolfopa** [comment]
@brianchandotcom The list is sorted afterwards, so the initial order doesn't matter. @juliocamarero is there any circumstance in which the initial order matters?

**Comment by juliocamarero** [comment]
@adolfopa @brianchandotcom . No, the only order that matters is the one definded by the "weight" of each element and we use a comparator to sort them by that. thanks!

**Pull request closed without merging**
