### PR TITLE
LPS-106538 Implement adding OrgLabor through the Organization POST endpoint

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-106538](https://issues.liferay.com/browse/LPS-106538).<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow

### CODE REVIEW

**Comment by drewbrokke** [comment]
@brianchandotcom I rebased onto the commits for LPS-106538 from your branch, and resolved the merge conflicts locally. Not sure why there are rebase conflicts on this pull.

**Comment by drewbrokke** [comment]
ci:close to fix SF issues

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fc23b471f5...442288a762

**Comment by brianchandotcom** [comment]
@drewbrokke see ed37c029bcc43f4f251d34c7af7fc2603f5195e8 and 9900689f91038cd84eae259f9135d1aab8395d0a

**Comment by brianchandotcom** [comment]
@drewbrokke please make sure tests pass.

**Pull request closed without merging**
