### PR TITLE
Objects Automated Test - LPS-145709, LPS-145717 | master

### PR DESCRIPTION
**Pull request by andreefarias**
https://issues.liferay.com/browse/LPS-145709
https://issues.liferay.com/browse/LPS-145717

### CODE REVIEW

**Comment by andreefarias** [comment]
ci:reopen

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by rodrigocunhaa** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/acf72621ff...32c3ddf1e1

**Pull request closed without merging**
