### PR TITLE
LPS-65535 redirect to the page updated with a success message after a page is modified

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @evannagayama. I wonder if this may break any functional test.

Now, when the user edits a page and clicks on save, if there are no errors, the user is redirected to the page she just modified.

**Comment by evannagayama** [comment]
@juliocamarero I think it should be ok. We usually navigate to the next action after editing a page. There's a small chance we have some assertions of the configuration right after editing, but it should be easy to fix.

**Comment by juliocamarero** [comment]
Thanks!! 👍

**Comment by pyoo47** [comment]
This PR Test failed due to a problem with the temp-map functionality. @brianchandotcom , please retest as needed. I would retest now but the load is currently high and I could just cause more of these problems.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by juliocamarero** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/40017

**Pull request closed without merging**
