### PR TITLE
LPS-117884 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-117884

This is only for master.

@JorgeFerrer

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure task is not related to changes in PR.
See https://github.com/liferay-echo/liferay-portal/pull/1674
✔️ ci:test:stable - 21 out of 21 jobs passed
❌ ci:test:relevant - 82 out of 86 jobs passed in 1 hour 60 minutes

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/82f1753fa7...5b6bf15ce3

**Comment by brianchandotcom** [comment]
@JorgeFerrer I made a lot of tiny naming changes. Please review. Thx.

**Comment by JorgeFerrer** [comment]
Thanks Brian!
The changes look good. Will keep them in mind for next pulls.

**Pull request closed without merging**
