### PR TITLE
Lps 61952 sb exceptions

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
@brianchandotcom this is only a preparation pull to push all SB exceptions into their own packages, the renaming changes will come after this.

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/ec24164c07...d9e4e1c4fd

**Comment by brianchandotcom** [comment]
@shuyangzhou it's green now, and i pushed up your changes, but it may be broken in upstream because of other pulls I merged in prior to merging this. But those should be easy to fix. I'll be on the lookout.

**Pull request closed without merging**
