### PR TITLE
LPS-110763 Restrict all logic change to createRequiredDefaultTypeMapp…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…ings() to prevent side affect.

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:reopen

**Comment by vicnate5** [comment]
@brianchandotcom unit test fix

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f5f86f0ee1...879afc8093

**Comment by brianchandotcom** [comment]
@arboliveira

**Pull request closed without merging**
