### PR TITLE
LRQA-64641 Set property so portal startup does not check for the now missing commerce license

### PR DESCRIPTION
**Pull request by vicnate5**

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:reopen

**Comment by vicnate5** [comment]
tested at https://github.com/vicnate5/liferay-portal/pull/1686

**Comment by vicnate5** [comment]
backports https://github.com/brianchandotcom/liferay-portal-ee/pull/33683

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5cfe361ff8...30003d9fb0

**Pull request closed without merging**
