### PR TITLE
LPS-72918

### PR DESCRIPTION
**Pull request by bawachhe**
https://issues.liferay.com/browse/LPS-72918

### CODE REVIEW

**Comment by bawachhe** [comment]
ci:reopen

**Comment by jpince** [comment]
@bawachhe compile failure for the tasks module

Also, `[echo] /opt/dev/projects/github/liferay-portal/modules/build-app.xml:418: Unable to load file: java.io.FileNotFoundException: /opt/dev/projects/github/liferay-portal/modules (Is a directory)` is a consistent failure in the lpkg tests. Maybe @ithildir or @shuyangzhou can help?

**Comment by jpince** [comment]
ci:close

**Comment by bawachhe** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/49663

**Pull request closed without merging**
