### PR TITLE
LPS-197156 Add Copy with permissions for Master Pages

### PR DESCRIPTION
**Pull request by alessandromalves**
## Motivation

Add options for copy with and without permissions in the dropdown for Master Pages and Display Pages

[Link to ticket](https://liferay.atlassian.net/browse/LPS-197156)
[Link to ticket](https://liferay.atlassian.net/browse/LPS-196851)

## Test scenario 1 
1. Create a new Master Page.
2. Change the permissions for this Master Page.
3. Make a Copy with permissions and a copy without them. Check that they are copied or not depending on the case.

https://github.com/liferay-echo/liferay-portal/assets/93203423/932986a5-82f0-45a3-a229-b591ab885002

## Test scenario 1 
1. Create a new Display Page.
2. Change the permissions for this Display Page.
3. Make a Copy with permissions and a copy without them. Check that they are copied or not depending on the case.

https://github.com/liferay-echo/liferay-portal/assets/93203423/c0e96ef8-b14b-44cd-9990-d0065ab9c490

cc.: @BarbaraCabrera

### CODE REVIEW

**Comment by alessandromalves** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/13920

✔️ ci:test:stable - 30 out of 30 jobs passed
❌ ci:test:relevant - 267 out of 325 jobs passed in 4 hours 48 minutes

**Comment by alessandromalves** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/510e69c174...5139b6e9ee

**Comment by brianchandotcom** [comment]
@BarbaraCabrera just 5139b6e9eee6090a8b7b3c5f79912e6f09349c6f

**Pull request closed without merging**
