### PR TITLE
LPS-52490 SF

### PR DESCRIPTION
**Pull request by pablocp**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
<h1>Some tests FAILED!</h1>
<h1>See the following links for more information.</h1>
* https://test-1-2.liferay.com/job/test-portal-pullrequest(master)/193/
* https://test-1-2.liferay.com/job/test-portal-pullrequest-githubpost-start(master)/190/
* https://test-1-2.liferay.com/job/test-portal-pullrequest-source(master)/189/
* https://test-1-2.liferay.com/job/test-portal-pullrequest-backend(master)/189/
* https://test-1-2.liferay.com/job/test-portal-pullrequest-plugins(master)/119/
* https://test-1-2.liferay.com/job/test-portal-pullrequest-githubpost-stop(master)/189/

<h1>1 Failures.</h1>
<a href="https://test-1-2.liferay.com/job/test-portal-pullrequest-backend(master)/189/testReport/">Test Report</a>

@pablocp - The error for this source format was too big to post.  See below link for failure details:

https://test-1-2.liferay.com/job/test-portal-pullrequest-backend(master)/189/group=8,label_exp=!test-1-2/testReport/junit/com.liferay.portal.tools.sourceformatter/SourceFormatterTest/testSourceFormatter/

@brianchandotcom - We'll update our github comment script for this case as well.

https://issues.liferay.com/browse/LIFERAYQA-12836

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/fb9ceefb49...1d6a3231e3

**Comment by brianchandotcom** [comment]
@marcellustavares  I went ahead and merged it since the SF error had nothing to do with this ticket.

Can you also rename *test-data.json" to just *.json". I think that isn't needed since you have other "*fied*.json" that doesn't say it's a test.

@michaelhashimoto we should still fix the github pull request commands to post the proper error.

Thx

**Pull request closed without merging**
