### PR TITLE
LPS-98400 SF

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1aaabba283...e4ffff4e63

**Comment by brianchandotcom** [comment]
lbm:backport @CsabaTurcsan @jpince @zsoltbalogh

**Comment by brianchandotcom** [comment]
@victorg1991 I backported this for you.

**Pull request closed without merging**
