### PR TITLE
WCM-1390

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/WCM-1390.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by ctampoya** [comment]
Thank you @jonmak08!

@brianchandotcom this is the fix for the WCM issue that is blocking FP33 release.

**Comment by brianchandotcom** [comment]
@jonmak08 I need you to send me a backport to 7.0.x asap. Thx.

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Pull request closed without merging**
