### PR TITLE
LPS-93945 SF

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by jpince** [comment]
@kyle-miho @brianchiu @p2kmgcl int test failure looks like it might be related?
```
FragmentEntryProcessorEditableTest.testFragmentEntryProcessorEditableCSSMediaQuery 

org.junit.ComparisonFailure: expected:<...t {background-color:[ red;padding: 2em;} @media (min-width: 768px) {.growing-box-fragment {background-color: blue;padding: ]10em;}}> but was:<...t {background-color:[red;padding:2em;} @media (min-width: 768px) {.growing-box-fragment {background-color:blue;padding:]10em;}}>
```

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by kyle-miho** [comment]
Investigating

**Pull request closed without merging**
