### PR TITLE
COMMERCE-471 - SF

### PR DESCRIPTION
**Pull request by ZoltanTakacs**
Hi @brianchandotcom,

It's the follow up PR for [COMMERCE-471](https://issues.liferay.com/browse/COMMERCE-471) https://github.com/brianchandotcom/liferay-portal/pull/60151#issuecomment-396790413

Please let me know if I need to do further refinements.

Thank you,
Zoli

### CODE REVIEW

**Comment by ZoltanTakacs** [comment]
ci:test:sf

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by ZoltanTakacs** [comment]
Hi @brianchandotcom , unfortunately we cannot do this in Talend as it must be named identically to the instance name.
See https://github.com/Talend/components/wiki/5.-Component-Properties#properties

**Pull request closed without merging**
