### PR TITLE
LPS-104672 Update Clay2 packages to 2.19.0

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b8d6905497...c5b12e4fbe

**Comment by jbalsas** [comment]
Hey @john-co, `ci:test:relevant` looks awful here... but looked good during our previous runs at https://github.com/jbalsas/liferay-portal/pull/2053#issuecomment-558812356 and https://github.com/jbalsas/liferay-portal/pull/2053#issuecomment-558815736... could you please take a look? If that many failures are caused by this, we should immediately revert.

I didn't see major issues in a quick smoke test I run, but just to double-check.

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
a good chunk of these tests should be fixed by https://github.com/brianchandotcom/liferay-portal/pull/81420

**Pull request closed without merging**
