### PR TITLE
LPS-86806

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@brianchandotcom, can you publish `source-formatter` and `java-parser`?
After that I can add some tests for this?

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
@cgoncas, this should solve this issue: https://github.com/brianchandotcom/liferay-portal-ee/pull/25531#issuecomment-513958414

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/2baf5f0634...947c482600

**Comment by brianchandotcom** [comment]
@hhuijser published.

**Pull request closed without merging**
