### PR TITLE
LPS-54728 fix issue with XSL locale transformer

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
@hudakl @giros could you please review my changes? I think they are mostly SF. As I refactored the loops I realized before it was going from the last element to the first one and now I am going in the opposite order... do you know if there is any reason for this? or is it just legacy code?

**Comment by juliocamarero** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@juliocamarero @hudakl @giros looks like a real test failure. Please resend.

**Pull request closed without merging**
