### PR TITLE
LPS-63740

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:stop

**Comment by hhuijser** [comment]
@brianchandotcom 

SFTest failing on file in modules/private? I don't see that on my end?

org.junit.ComparisonFailure: ../../../modules/private/apps/foundation/portal/portal-dao-db/src/main/java/com/liferay/portal/dao/db/OracleDB.java

**Comment by brianchandotcom** [comment]
@hhuijser Go to ee-7.0.x. We're copying those modules at test time. Resend? Thx.

**Comment by hhuijser** [comment]
@brianchandotcom

But that means we should exclude those from SF on master, since those files are not there when running a regular SF (outside of testing)?

**Comment by hhuijser** [comment]
@brianchandotcom 

Never mind, I just saw your comment on the other pull... So should I sent this entire fix on ee-7.0.x first then?
I can't only send the Auto SF for ee-7.0.x as that would always break the SF Test?

**Pull request closed without merging**
