### PR TITLE
LPS-166126 Testray TestFlow DispatchTrigger and Testray AutoFill Dispatch Trigger

### PR DESCRIPTION
**Pull request by nNilton**

### CODE REVIEW

**Comment by nNilton** [comment]
ci:reopen

**Comment by nNilton** [comment]
Unrelated failures here https://github.com/pt-liferay-solutions/liferay-portal/pull/2985

**Comment by joelrocha68** [comment]
Just starting reviewing :)

**Comment by joelrocha68** [comment]
Just starting reviewing :)

**Pull request closed without merging**
