### PR TITLE
LPS-63638 Use your ServletContext to find the ContextPath of web resources

### PR DESCRIPTION
**Pull request by rotty3000**
/cc @sergiogonzalez

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/85e550f90a...a354093bf5

**Comment by juangon** [comment]
Hi @rotty3000 , maybe something like this is needed for this change? https://github.com/brunobasto/liferay-portal/commit/b289d4e6d8c88b7feafb69bbc9ba3b8ce6ec03e5

**Comment by rotty3000** [comment]
yes, we should absolutely never use a string for the context.

**Comment by sergiogonzalez** [comment]
thanks for the fix @rotty3000 :+1:

**Pull request closed without merging**
