### PR TITLE
LPS-65802 Fix invalid relational operator

### PR DESCRIPTION
**Pull request by marcellustavares**
cc @inacionery @topolik

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by rafaprax** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@marcellustavares this has been stuck for a long time, can you rebase and resend? Thx.

**Comment by marcellustavares** [comment]
Resent to https://github.com/brianchandotcom/liferay-portal/pull/42808

**Pull request closed without merging**
