### PR TITLE
LPS-63650

### PR DESCRIPTION
**Pull request by natecavanaugh**

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:retest

**Comment by pyoo47** [comment]
I've aborted brian's retest because of PR tester reset.

**Comment by pyoo47** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/84f7738143...3c7761d9f1

**Pull request closed without merging**
