### PR TITLE
LPS-55928

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
@brianchandotcom there are interface changes and classes being moved.  However, most of the breaking changes are to interfaces that were added since 6.2 has released.  The others are changes that really are internal to our Indexer implementations and no one would use them (especially since this area of the product is not documented at all).  That's why I opted to remove as opposed to deprecate.

**Comment by mhan810** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/af1608461f...54d0508f7e

**Comment by brianchandotcom** [comment]
@mhan810 

A commit in this pull https://github.com/mhan810/liferay-portal/commit/fee504126e52998e9f1d0bc43bad07778bcad3dd

conflicted with a7e9290cd24a019393f46b7f374c0c997311e828 from @izaera

I did my best to "merge" the conflict based on what I think is right. please double check.

@marcellustavares please see new DDMStructureIndexer in this pull. It may affect how you pull out DDM. I'm not a big fan of putting DDM stuff in the general search package. Just fyi.

Thx

**Comment by mhan810** [comment]
Merge looks ok to me.

**Comment by izaera** [comment]
Looks good for me too. As long as we use FileEntry instead of DLFileEntry to communicate between indexers, everything should be fine. :-)

**Pull request closed without merging**
