### PR TITLE
LPS-57210 MDR web

### PR DESCRIPTION
**Pull request by matethurzo**
Renamed the constant class and fixed the language properties

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/e32a3c68be...e0d1bf7701

**Comment by brianchandotcom** [comment]
@matethurzo please see my changes in upstream. Thx.

**Comment by brianchandotcom** [comment]
@matethurzo I made a lot of changes ... thx

**Pull request closed without merging**
