### PR TITLE
LPS-99178 Adds new contributed component based on an editable of type HTML

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:// @ealonso

**Comment by jkappler** [comment]
ci:close

**Comment by jkappler** [comment]
ci:reopen

**Comment by wincent** [comment]
Just to provide context here Prettier is going to add a newline at the end of every JS file it touches. The file you fixed in f3f11bbac3fb, @brianchandotcom, won't be touched by Prettier only because it [is ignored via .prettierignore](https://github.com/liferay/liferay-portal/blob/2e0862286535b794943a0b519da71f7bff312691/modules/.prettierignore#L40).

In addition to having a newline character at the end-of-file, the reason it has a trailing *blank line* is that any file with copyright headers auto-inserted has the headers followed by a blank line to separate them from the rest of the content (this is achieved by including a trailing blank line in [the header template](https://github.com/liferay/liferay-portal/blob/2e0862286535b794943a0b519da71f7bff312691/modules/copyright.js)). That /fragments/heading/index.js file is effectively a sample, which is why it has no content (and why it is ignored by Prettier). It only has the header in there at all because we did a one-time bulk run over all JS files with ESLint to add headers (in 2d20e9fa0d739bf1b901e1af6a38da71a50e894d). We're not currently linting ".js" files (just ".es.js" files), which is why ESLint isn't touching that file and putting the blank line back.

**Pull request closed without merging**
