### PR TITLE
LPS-96050 Document tests for POST, PUT and PATCH comparing JSON and content

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by jpince** [comment]
@ruben-pulido @nhpatt not sure if these failures are related to these pull, but I haven't seen them in upstream
https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/166362/AXIS_VARIABLE=1,label_exp=!master/consoleFull
```
DocumentResourceTest.testClientSerDesToDTO
java.lang.IllegalArgumentException: Unsupported field name viewableByAsString
	at com.liferay.headless.delivery.client.serdes.v1_0.DocumentSerDes$DocumentJSONParser.setField(DocumentSerDes.java:696)
	at com.liferay.headless.delivery.client.serdes.v1_0.DocumentSerDes$DocumentJSONParser.setField(DocumentSerDes.java:545)
	at com.liferay.headless.delivery.client.json.BaseJSONParser.parseToDTO(BaseJSONParser.java:85)
	at com.liferay.headless.delivery.client.serdes.v1_0.DocumentSerDes.toDTO(DocumentSerDes.java:45)
	at com.liferay.headless.delivery.resource.v1_0.test.BaseDocumentResourceTestCase.testClientSerDesToDTO(BaseDocumentResourceTestCase.java:125)
```

```
DocumentResourceTest.testClientSerDesToJSON
java.lang.AssertionError: expected:<{"contentUrl":"FWSh9GSh","dateCreated":"2019-05-23T15:09:08Z","dateModified":"2019-05-23T15:09:08Z","description":"aJycnsXW","documentFolderId":7100238337345415323,"encodingFormat":"EKzfpSCF","fileExtension":"JZJkgmJE","id":3092239709618432747,"sizeInBytes":4034490482004030653,"title":"5HgrPGK2","viewableBy":"ANYONE","viewableByAsString":"Anyone"}> but was:<{"contentUrl":"FWSh9GSh","dateCreated":"2019-05-23T15:09:08Z","dateModified":"2019-05-23T15:09:08Z","description":"aJycnsXW","documentFolderId":7100238337345415323,"encodingFormat":"EKzfpSCF","fileExtension":"JZJkgmJE","id":3092239709618432747,"sizeInBytes":4034490482004030653,"title":"5HgrPGK2","viewableBy":"Anyone"}>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.liferay.headless.delivery.resource.v1_0.test.BaseDocumentResourceTestCase.testClientSerDesToJSON(BaseDocumentResourceTestCase.java:146)
```

**Comment by nhpatt** [comment]
Pretty sure they are @ruben-pulido

**Comment by ruben-pulido** [comment]
Thanks for the heads up @jpince. I'm looking into it

**Comment by ruben-pulido** [comment]
Resent https://github.com/brianchandotcom/liferay-portal/pull/73676

**Pull request closed without merging**
