### PR TITLE
[7.4-only] LPS-123894 - container-fluid-1280 fix

### PR DESCRIPTION
**Pull request by marcoscv-work**
Manual forward from:
https://github.com/liferay-frontend/liferay-portal/pull/539

---

This PR fixes some alignation problems with the old class 'container-fluid-1280':

image

---

For testing:

- Go to content & data > web content

### CODE REVIEW

**Comment by marcoscv-work** [comment]
Manual forward since test fails are not related to PR:

https://github.com/liferay-frontend/liferay-portal/pull/539#issuecomment-733584232

**Comment by marcoscv-work** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@marcoscv-work master only.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/79426ef97d...73d0fb00f2

**Pull request closed without merging**
