### PR TITLE
LPS-91876

### PR DESCRIPTION
**Pull request by andresfulla**
@darquesdev @epgarcia

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:msb

**Comment by andresfulla** [comment]
ci:reopen

**Comment by andresfulla** [comment]
ci:test:relevant

**Comment by andresfulla** [comment]
ci:test:msb

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/90d05f0db3...8a03c18921

**Pull request closed without merging**
