### PR TITLE
LPS-126399 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-126399

This is only for master.

@david-gutierrez-mesa
@alexcandidos

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure cases are unrelated to changes in PR.
See https://github.com/liferay-echo/liferay-portal/pull/3630
✔️ ci:test:stable - 9 out of 9 jobs passed
❌ ci:test:relevant - 22 out of 25 jobs passed in 2 hours 13 minutes

**Comment by brianchandotcom** [comment]
@gleicelisbino please review.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/47775b3cbf...0452c78cb9

**Comment by gleicelisbino** [comment]
Thank you, @brianchandotcom . I will see the changes now!

**Pull request closed without merging**
