### PR TITLE
LPS-102884 When the user edit the control variant, the content of the variant is replaced

### PR DESCRIPTION
**Pull request by darquesdev**
@ealonso @ruben-pulido @andresfulla

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:stable

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@darquesdev rebase error, can you resend. thx.

**Pull request closed without merging**
