### PR TITLE
LPS-71074 Rename package to match bundle symbolic name

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@adolfopa please backport. Thx.

**Comment by adolfopa** [comment]
Hey @brianchandotcom 

I don't think this needs to be backported to EE. In ee-7.0.x the BlogsTestUtil class is in portal-test (not in a module), and in this case the package name follows the conventions for test util classes in the core.

If you want me to rename it anyway, ping me and I'll send you a pull.

Thanks!

**Pull request closed without merging**
