### PR TITLE
[TECHNICAL-SUPPORT] LPS-85952

### PR DESCRIPTION
**Pull request by rafaprax**
/cc @brianikim 

Notes from Brian:

> https://issues.liferay.com/browse/LPS-85952
> 
> My PR from #499 that links https://issues.liferay.com/browse/LPS-85600 is not correct. Although LPS-85600 is related to LPS-85952, they are two separate bugs.
> 
> The issue here is that whenever you try to save a form with its page name and description filled in and you fail any form validation checks during the submit, the page will refresh and the form content will be reset for page names and descriptions.
> 
> The fix is to ensure that we pass in localizedDescription and localizedTitle to the back-end as page name and description are handled under the mentioned two specific variable names.
> 
> Please let me know if you have any questions. Thanks.
> 
> Sincerely,
> Brian Kim

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:test:relevant (Jenkins master crash)

**Comment by brianikim** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/b5f7e368b6...b48f8ed5ad

**Comment by brianchandotcom** [comment]
@rafaprax please send a backport to 7.1.x. Thx.

**Pull request closed without merging**
