### PR TITLE
LPS-68989 WAB bundles needs to search resources in /META-INF/resources too

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@juangon isn't

```
			catch (IOException ioe) {
			}
```

a bad idea?

@hhuijser is going through and removing all swallowed exceptions.

@juangon can you send me a follow up and at least add a debug? or something else.

Thx.

**Comment by hhuijser** [comment]
@brianchandotcom @juangon right now, SF only complains about unswallowed exceptions that extend PortalException or SystemException.

@Preston-Crary @shuyangzhou do we want to check for any type of exception, at some point?

**Comment by shuyangzhou** [comment]
Yes @hhuijser , eventually, when we have the bandwidth for it, not going to happen anytime soon.

**Comment by hhuijser** [comment]
Just FYI, we have a little over 1100 cases in master that we'd need to fix...

**Comment by shuyangzhou** [comment]
Ok, that's a lot, but I was preparing for worse. That's ok, we will get to them eventually. Thanks @hhuijser !

**Comment by juangon** [comment]
@brianchandotcom @hhuijser @shuyangzhou  yep, as I didn't want to change the API, and the following version increase etc, I looked through Liferay and saw other cases like here: https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/portal/portal-spring-extender/src/main/java/com/liferay/portal/spring/extender/internal/classloader/BundleResolverClassLoader.java#L80-L88 and here: https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/portal-template/portal-template-freemarker/src/main/java/com/liferay/portal/template/freemarker/internal/FreeMarkerBundleClassloader.java#L65-L75. I am not a fan of swallowing exceptions, but I think in this specific case, even throwing it, it wouldn't be possible to take any action for recovering. Maybe an error log would be fine. I let that decision to you.

**Comment by Preston-Crary** [comment]
@juangon Please review this documentation https://issues.liferay.com/browse/LPS-36174?focusedCommentId=882129#comment-882129 if you're not sure how to handle an exception.  I think the best thing to do in this case is log a warning or maybe throw an unchecked exception depending on how serious you think this failure would be to the rest of the system.

**Comment by juangon** [comment]
Sent here: https://github.com/brianchandotcom/liferay-portal/pull/44552

**Comment by juangon** [comment]
In final review here: https://github.com/brianchandotcom/liferay-portal/pull/44967

**Pull request closed without merging**
