### PR TITLE
Lpd 27238

### PR DESCRIPTION
**Pull request by shuyangzhou**
@tiantian @vicnate5 please backport for LXC, thanks!

@victorhcunha please run a check for login case, thanks!

CC @slnn

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f8ec9331f9...5b2084e8fc

**Comment by victorhcunha** [comment]
Hi @shuyangzhou !
Here are the results for login testcase:


Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | DB CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | --
Baseline | 501f884 | 10088 |   | 299 | 3,3,4 | 93,94,93
PR | - | 9571 | -5.124900872 | 299 | 4,4,3 | 93,93,93

More details you can see in our [spreadsheet](https://docs.google.com/spreadsheets/d/1M6VK8GtY9kkv1EwhGW7vwrEENSzyT7zKz-wOh11ZHBo/edit#gid=1876253640)

**Comment by shuyangzhou** [comment]
@victorhcunha this result is not expected, this change should be a pure improvement, since it removes all monitoring activity for out of box settings. Please rerun it to confirm.

**Comment by victorhcunha** [comment]
Sure! I will do another round.

**Comment by victorhcunha** [comment]
@shuyangzhou 
here are the new results for login test case:


Portal Version | Git Id | Session Count | Session Count Change (%) | Mean Time of Login | DB CPU Usage (%) | Portal CPU Usage (%)
-- | -- | -- | -- | -- | -- | --
Baseline | 501f884 | 9516 | - | 295 | 3,5,3 | 93,93,92
PR | - | 9894 | 3.972257251 | 290 | 3,4,3 | 92,95,93

More details you can see in our [spreadsheet](https://docs.google.com/spreadsheets/d/1M6VK8GtY9kkv1EwhGW7vwrEENSzyT7zKz-wOh11ZHBo/edit#gid=1876253640)

**Comment by shuyangzhou** [comment]
Ok, this looks reasonable, I think your previous baseline was off for some reason.

**Pull request closed without merging**
