### PR TITLE
LRQA-48481 | master

### PR DESCRIPTION
**Pull request by vicnate5**
https://issues.liferay.com/browse/LRQA-48481

@tinatian

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@vicnate5 I want us to employ a new pattern (I'm merging in it this time only)

For binary files like this jar, functional/com/liferay/portalweb/dependencies/com.liferay.cluster.test.module.7.2.jar

Create a directory called

functional/com/liferay/portalweb/dependencies/com.liferay.cluster.test.module.7.2.jar/

And explode what you want into it. THEN, from your script, call that dir, but pass in something that says, zip it up.

@michaelhashimoto @brianchiu please enforce and provide help for this.

@jhendley fyi

**Comment by vicnate5** [comment]
@brianchandotcom This will be handled by https://issues.liferay.com/browse/LRCI-176

**Comment by joshchong** [comment]
The dependency jar change was implemented in:
https://issues.liferay.com/browse/LRCI-253

**Comment by kenjiheigel** [comment]
@vicnate5, @joshchong, the new Poshi release has this implemented in uploadCommonFile now, so you can start updating archives, or adding them.

**Pull request closed without merging**
