### PR TITLE
LPS-64200 error messages in login shouldn't overlap the fields

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @jbalsas @natecavanaugh @marcoscv-work

**Comment by brianchandotcom** [comment]
@pyoo47 what's up with these errors?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4645bad872...584f957907

**Comment by pyoo47** [comment]
The code snippet here is actually correct. The error that you're seeing here is occurring in the "upgrade-legacy-database" target. There is a step where ant directs the slave to telnet back to itself (localhost) on port 11311 and for some reason, it's timing out looking for the string "g!" in the telnet response.

```
[echo] /opt/dev/projects/github/liferay-portal/build-test.xml:7769: Response timed-out waiting for "g!"
```
This line is from the code snippet above (4th from the bottom).

**Comment by brianchiu** [comment]
@pyoo47 @brianchandotcom 
Yes. In this case, for some reason it is timing out. I'm not entirely sure if it's a portal bug or not right now. But @alee8888 will ask some devs if it's ever possible for gogo shell to not start up after an upgrade finishes.

We are tracking the occurrences of this here:
https://issues.liferay.com/browse/LRQA-23082

**Pull request closed without merging**
