### PR TITLE
LPS-60085 SF

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:retest (this one has been taking all day, retesting it)

**Comment by rotty3000** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/211ec1caff...1efb4f638e

**Comment by brianchandotcom** [comment]
Great job @mjbradford89 !

**Pull request closed without merging**
