### PR TITLE
LPS-62932 Include user-theme module

### PR DESCRIPTION
**Pull request by CAustin582**
Requested by @JorgeFerrer

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
:+1:

**Comment by brianchandotcom** [comment]
@CAustin582 what about product-app-theme?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9464275227...c29f8256e9

**Comment by CAustin582** [comment]
Jorge says product-app-theme isn't ready yet and might only go into EE

**Pull request closed without merging**
