### PR TITLE
LPS-70058

### PR DESCRIPTION
**Pull request by lionah**

### CODE REVIEW

**Comment by lionah** [comment]
🙏

**Comment by lionah** [comment]
🎉

**Comment by brianchandotcom** [comment]
@lionah I backported this for you, cherry picked cleanly to 7.0.x

**Comment by brianchandotcom** [comment]
@lionah actually, I take that back. If you want it backported to 7.0.x, please send me a pull. I think for some LPKG reasons you may need the API to not change.

**Pull request closed without merging**
