### PR TITLE
Lps 195730

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/71fbc54e6a...9f460cea6b

**Comment by brianchandotcom** [comment]
@shuyangzhou was this on purpose?

```
	@Override
	public User addDefaultServiceAccountUser(long companyId)
		throws PortalException {
...
		return userLocalService.updateUser(defaultServiceAccountUser);
	}
```

It's the local service calling the local service. Can you send me a follow up? Thx.

**Comment by shuyangzhou** [comment]
@brianchandotcom Yes, it is on purpose for triggering indexing.

**Pull request closed without merging**
