### PR TITLE
Lps 80938

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:reopen

**Comment by mtambara** [comment]
ci:test

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/280c10c3c0...9115d89332

**Comment by brianchandotcom** [comment]
@mtambara please backport this..

build-app.xml and build-test-batch.xml should be identical for LPKG related stuff in 7.0.x and master.

**Comment by mtambara** [comment]
Backport sent at https://github.com/brianchandotcom/liferay-portal-ee/pull/20196

**Pull request closed without merging**
