### PR TITLE
LPS-85326

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brianchandotcom,

Attached is an update for http://issues.liferay.com/browse/LPS-85326.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:reopen

**Comment by jonmak08** [comment]
ci:retest

**Comment by jpince** [comment]
ci:test

**Comment by brianchandotcom** [comment]
@jonmak08  I backported to 7.1.x for you. Please send for 7.0.x. Thx.

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/liferay/liferay-portal-ee/pull/10011

**Pull request closed without merging**
