### PR TITLE
LPS-61460 Move navigation to the selector in Bookmarks and DL

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @sharonchoi

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@sergiogonzalez consistently failing Poshi test. @evannagayama can you follow up or send it to the right person? may be @vicnate5 ?

**Comment by evannagayama** [comment]
@brianchandotcom @sergiogonzalez our team will take care of it, thanks!

**Comment by evannagayama** [comment]
@brianchandotcom our team will take care of it.
@sergiogonzalez could you send me a pull request with these changes? We'll fix the functional test then push it to BChan. Thanks

**Pull request closed without merging**
