### PR TITLE
LPS-74640 Rename

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
ci:stop

**Comment by jpince** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/0b70cfed0a...f76aadcade

**Comment by brianchandotcom** [comment]
@ealonso @jkappler 

Much better name! I never liked "Modern Site Building" as it would sound strange in a few years. I really like the word Fragment.

Good job guys.

**Pull request closed without merging**
