### PR TITLE
LPS-103069 Match with layoutData

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
cc: @victorg1991

**Comment by ealonso** [comment]
ci:reopen

**Comment by victorg1991** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by victorg1991** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
