### PR TITLE
LPS-144542 Add TaskNode Test

### PR DESCRIPTION
**Pull request by lucasperj**

### CODE REVIEW

**Comment by lucasperj** [comment]
ci:reopen

**Comment by lucasperj** [comment]
Hi Brian! I'm sending this manually because the failures are not related with the changes. Ran the fail test locally and manually. Thank you.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/5c05022a8f...b990bc16fa

**Comment by brianchandotcom** [comment]
@jotascript see 15467471f38dc25b23e3a200c602d93ce22441f2

**Pull request closed without merging**
