### PR TITLE
LPS 131312 10 4

### PR DESCRIPTION
**Pull request by kyle-miho**

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:reopen

**Comment by kyle-miho** [comment]
@vicnate5

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/cd04a6c509...7e1ac3b907

**Comment by brianchandotcom** [comment]
thx @kyle-miho just 7e1ac3b907f404670ba500cbf1ab27ef30f2457d

**Comment by brianchandotcom** [comment]
@kyle-miho I made more changes in my origin. Please review.

**Pull request closed without merging**
