### PR TITLE
LPS-166427 | LPS-166622 New related assets collection provider - assets with categories in the same vocabularies

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-166427

@jkappler

### CODE REVIEW

**Comment by ozysouza** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure tests are unrelated to this PR.
See https://github.com/liferay-echo/liferay-portal/pull/10039

:heavy_check_mark: ci:test:stable - 26 out of 26 jobs passed
:x: ci:test:relevant - 228 out of 275 jobs passed in 4 hours 41 minutes

**Comment by ozysouza** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1097722f16...ee44076930

**Comment by brianchandotcom** [comment]
@jkappler see ee4407693091b9b6786ce175985314f579ef4836

**Pull request closed without merging**
