### PR TITLE
LPS-92335 Disable testSearchCommentsByKeywords for more entities which also don't support comments

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-92335

Follow-up- on https://github.com/brianchandotcom/liferay-portal/pull/69794#issuecomment-474993023.

Sorry about the additional changes. I should have run CI twice maybe to catch these earlier.

Regards,
Tibor

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
`BlogsEntrySearchTest.testSearchCommentsByKeywords` is expected to still fail, Cristina is working on the required search changes for blogs on https://issues.liferay.com/browse/LPS-92385.

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
Error is also on upstream.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/4e7079b629...f0378d9c7d

**Comment by brianchandotcom** [comment]
Thx @lipusz

**Pull request closed without merging**
