### PR TITLE
LPS-86836 Setup for sub-jvms

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @dantewang @tinatian

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@shuyangzhou I see that every time we set Properties, we have to set HtmlUtil. Shouldn't this be moved to a util class?

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/8752c7f7c8...ebc08bd6e6

**Comment by shuyangzhou** [comment]
@brianchandotcom This is only needed when we init log4j, due to that escape call added earlier.
@tinatian @dantewang, I can see this could get a lot more annoying later. Can we use the jdk url encoder? Or the worst case, we just copy over the escape method into the Log4jUtil as a private method to avoid this dependency.

**Comment by brianchandotcom** [comment]
yes, I'd rather just use the JDK URLEncoder so we don't have this dependency. @shuyangzhou @tinatian @dantewang

**Comment by dantewang** [comment]
@shuyangzhou It's escaping a string to avoid illegal characters that breaks the structure of the XML, not encoding URLs. The methods used has dependencies to other methods in `HtmlImpl`, so copying it may result in more than half of `HtmlImpl` to be copied.

Alternative ways may be modifying the XML content with the help of XML API, or programmatically add the log rollers.

@tinatian @brianchandotcom

**Pull request closed without merging**
