### PR TITLE
LPS-120856 Rename "Change Lists" to "Publications"

### PR DESCRIPTION
**Pull request by Preston-Crary**
Please see https://github.com/Preston-Crary/liferay-portal/pull/1228#issuecomment-702464409 for why I'm sending this one directly.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/15a2331990...3ec7c6e5d0

**Comment by brianchandotcom** [comment]
@Preston-Crary can you sort these (they used to be before the rename)

```
	public PublicationsManagementToolbarDisplayContext(
		PublicationsDisplayContext publicationsDisplayContext,
		HttpServletRequest httpServletRequest,
		LiferayPortletRequest liferayPortletRequest,
		LiferayPortletResponse liferayPortletResponse,
		SearchContainer<CTCollection> searchContainer) {
```

Quite a few like these. I merged in the pull though to save time.

Thx.

**Comment by Preston-Crary** [comment]
Please see https://github.com/Preston-Crary/liferay-portal/pull/1231

**Pull request closed without merging**
