### PR TITLE
LPS-105791 Rollback to fix build issue on Windows

### PR DESCRIPTION
**Pull request by petershin**
Hi @izaera, I reverted this change b/c the task below was failing on Windows

```
gw :apps:frontend-js:frontend-js-web:packageRunBuild
```

Please recommit it after running `ant all` on a Windows machine.

### CODE REVIEW

**Comment by petershin** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a0e357f156...6eb87212d4

**Comment by brianchandotcom** [comment]
@wincent @jbalsas fyi windows issue

**Comment by jbalsas** [comment]
Thanks @brianchandotcom, I already reached out to @manoelcyreno and @kenjiheigel to see if we can either get some CIs on windows to test build changes before getting to you. 

We'll work on this again next week and double check on Windows before resubmitting :(

**Pull request closed without merging**
