### PR TITLE
LPS-195344 buildlang

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://liferay.atlassian.net/browse/LPS-195344

@victorg1991

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. Failure cases are unrelated to changes in this PR.

See https://github.com/liferay-echo/liferay-portal/pull/13577

**Comment by victorg1991** [comment]
Hey @Tim-Cao I've already sent the pr, sorry I didn't update the other pr

**Comment by victorg1991** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/140391

**Comment by victorg1991** [comment]
ci:close

**Pull request closed without merging**
