### PR TITLE
Upgrade Release: convert buildNumber from Int to String

### PR DESCRIPTION
**Pull request by migue**

### CODE REVIEW

**Comment by csierra** [comment]
Hey @brianchandotcom,

is there anything I can do to help with this?

Bests!

**Comment by csierra** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@migue @csierra sent long email regarding this pull. Closing for now.

**Comment by brianchandotcom** [comment]
@csierra I did merge in a few things for this pull. See upstream LPS-57681.

**Pull request closed without merging**
