### PR TITLE
LPS-57681 Update Test

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
hey @brianchandotcom,

sorry this took me so long. It is a lousy excuse but I had a lot of trouble getting the build to work. 
I think I addressed all your concerns in https://github.com/brianchandotcom/liferay-portal/pull/29608

Regarding DatabaseProccessContext and DatabaseContext, I intend to also use them in the Verifiers, together with the OuputStream providers. 

I hope you like this one more. 

Bests.

**Comment by csierra** [comment]
ci:retest

**Comment by csierra** [comment]
hey @brianchandotcom, 

I see some changes here https://github.com/liferay/liferay-portal-ee/commit/d08fa019c62016ba5a74a3df3ed228b9f48dd770 in the email Kenji sent that I have not taken into account cos they were not in master (such us `RunnableUtil`) Do you want me to close this pull and add those to my branch?? Or you were planning to readd those on top of my pull? Just tell me whatever is easier for you...

Thx

**Comment by brianchandotcom** [comment]
@csierra I forgot to push upstream, the changes that I had made yesterday. I'll try and rebase this on top of mine and see what conflicted. Sorry!

**Comment by csierra** [comment]
@brianchandotcom no worries, just let me know if you need me to do that... as I said before... whatever is handier for you...

Bests

**Comment by brianchandotcom** [comment]
@csierra This rebases cleanly. The code is much more straightforward now and makes a lot of sense. I should have it in soon.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/56929bafe5...99f70a9e81

**Comment by brianchandotcom** [comment]
@csierra please see my changes in upstream. Thx!

**Pull request closed without merging**
