### PR TITLE
LPS-53722 Rename getXXXGroupServiceSettingsProvider() methods to getGroupServiceSettingsProvider(). Do the same for getXXXPortletInstanceSettingsProvider(). This is to simplify naming.

### PR DESCRIPTION
**Pull request by izaera**
@brianchandotcom Regarding your comment from yesterday:

It is possible that WikiWebSettingsProvider returns more than one PortletInstanceSettingsProvider. Right now we are sharing the same WikiPortletInstanceSettings across all portlets in Wiki (wiki, wiki_admin and wiki_display) but in the future we should split them in three.

But... if we do that, we should totally split concerns between the three portlets, and then we shouldn't have the WikiWebSettingsProvider class any more, so I've implemented your proposed change to simplify naming of variables in the future.

Cheers,
Ivan

### CODE REVIEW

**Comment by izaera** [comment]
ci:retest

**Comment by izaera** [comment]
SF doesn't complain in my machine..
 
cat-crying

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@izaera 

I get the same error running locally

Parsing error while retrieving java terms modules/apps/wiki/wiki-service/src/com/liferay/wiki/service/settings/WikiServiceSettingsProvider.java

not sure what you did that to that class that is different from all other Java classes we have (try binary search /cut and paste to find out what you broke)

And then please resend then.

**Pull request closed without merging**
