### PR TITLE
LPS-109082 Test layout with fragment containing an HTML editable is converted to PageDefinition correctly

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
//cc @ealonso

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
//cc @jkappler

**Comment by brianchandotcom** [comment]
@ruben-pulido rebase error, please resend.

**Pull request closed without merging**
