### PR TITLE
LPS-71868 NavItem

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by brianchandotcom** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/dbb804cbc2...b45d7d1b0f

**Comment by brianchandotcom** [comment]
@Preston-Crary can you backport this? Thx.

**Comment by Preston-Crary** [comment]
Yes, putting it on the list.  I should be able have it early next week.

**Comment by Preston-Crary** [comment]
Backport https://github.com/brianchandotcom/liferay-portal-ee/pull/16732

**Pull request closed without merging**
