### PR TITLE
LPS-64246 WeakHashMap is HashMap, it is not thread safe.

### PR DESCRIPTION
**Pull request by shuyangzhou**
CC @csierra this is caused by https://github.com/liferay/liferay-portal/commit/1372a7e6ea23244c93245c568dc0759a3b45d9d6

CC @michaelhashimoto

### CODE REVIEW

**Comment by shuyangzhou** [comment]
Hmm, miss the 2nd commit.

ci:retest

**Comment by michaelhashimoto** [comment]
@brianchandotcom @pyoo47 @lesliewong92

This pull request should fix the stale portal startup process that was causing the 2 hour timeouts on some of our pull requests. ([LRQA-22397](https://issues.liferay.com/browse/LRQA-22397))

**Comment by brianchandotcom** [comment]
Oh wow.. good job @shuyangzhou !

**Comment by brianchandotcom** [comment]
@michaelhashimoto am I waiting for a second CI post? If not, can you retest this pull? Thx.

**Comment by shuyangzhou** [comment]
@brianchandotcom that's actually the 2nd test's results, some dependency is missing for the registry-test module. It is a standard arquillian test module, not ours, which won't be easy.

**Comment by brianchandotcom** [comment]
:( Ok, I'll close this then for your resend.

**Comment by csierra** [comment]
yeah... sure enough it is not a `ConcurrentHashMap`... I don't know this has slipped my mind. I am embarrassed :anguished:

**Pull request closed without merging**
