### PR TITLE
LPS-74880 - Fix blog new entry alignment

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:reopen

**Comment by jbalsas** [comment]
ci:stop

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/f300a6fd80...e32404059a

**Pull request closed without merging**
