### PR TITLE
LPS-142557 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-142557

This is only for master.

@ruben-pulido
cc @ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
In order to not clog up ci resources, I'm sending the PR directly. The failure case is unrelated to this PR.
https://github.com/liferay-echo/liferay-portal/pull/6778
✔️ ci:test:stable - 11 out of 11 jobs passed
❌ ci:test:relevant - 25 out of 29 jobs passed in 2 hours 27 minutes

**Comment by brianchandotcom** [comment]
@ruben-pulido sorry! my bad for causing the NPE!

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/14c3c7ecb3...56065ca6f3

**Pull request closed without merging**
