### PR TITLE
LPS-104242 SEO must be enabled by default

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/9d1534239d...ef825c86be

**Comment by brianchandotcom** [comment]
@jkappler see

test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8
Job Results:
734 Tests Passed.
1 Test Failed.

AXIS_VARIABLE=0,label_exp=!master #342422
reducers.layoutDataReducer REMOVE_ITEM removes an item from layoutData.items

**Comment by jkappler** [comment]
looking into it @brianchandotcom

**Comment by jkappler** [comment]
Integration test sent here by @ruben-pulido: https://github.com/brianchandotcom/liferay-portal/pull/81638

**Pull request closed without merging**
