### PR TITLE
LRQA-19302

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:retest

**Comment by Ithildir** [comment]
ci:retest

**Comment by brianchandotcom** [comment]
@Ithildir can you send me a backport for ee-6.2.x / ee-6.1.x? Thx. I'm merging this in since it looks good except for the SF.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/a85c7d2e06...0ada66f4b0

**Comment by brianchandotcom** [comment]
@Ithildir it's kind of weird that you have to declare the same version number twice. 2.8.LIFERAY-PATCHED-2 and that they have to be identical across both bnd files right?

**Comment by Ithildir** [comment]
Sent to https://github.com/brianchandotcom/liferay-portal-ee/pull/12012 and https://github.com/brianchandotcom/liferay-portal-ee/pull/12013

**Pull request closed without merging**
