### PR TITLE
Lps 68837

### PR DESCRIPTION
**Pull request by shuyangzhou**
@csierra the ModuleApplicationContextExtender one is caused by your change at https://github.com/liferay/liferay-portal/commit/707eff5bb8e9982603f3ce6127b9cc5150cda036#diff-c9de604f83680e726415e80187dae375R268

@adolfopa the DLValidatorImpl one is caused by your change at https://github.com/brianchandotcom/liferay-portal/commit/0d84ba0450ed106108e103282c75dc0b7098ec7d#diff-0c0e5d135a90363687356b8cec20a97eR157

@cgoncas the ServiceComponentLocalServiceTest one is caused by your change at https://github.com/brianchandotcom/liferay-portal/commit/eb529b47a179c8f795f005db2396659648484a52#diff-84d3bcf9713460f032c7f41c0988afe4R249

@hhuijser can we try to add some SF check for swallowed exceptions like this?

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:retest

**Comment by csierra** [comment]
👍

**Comment by pyoo47** [comment]
This is still running. Only 2 batches remain
http://test-1-14/job/test-portal-acceptance-pullrequest-batch%28master%29/52039/
http://test-1-11/job/test-portal-acceptance-pullrequest-batch%28master%29/51233/

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/392fe8bd9d...026d4374f3

**Comment by brianchandotcom** [comment]
Thx @shuyangzhou 

I backported this.

**Pull request closed without merging**
