### PR TITLE
LPS-84117

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
@brianchandotcom, should be okay after publishing this

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by brianchandotcom** [comment]
@hhuijser I wasn't able to publish :( When I ran

gradlew uploadArchive

in source-formatter, I get this:

```
Configuration on demand is an incubating feature.
:util:source-formatter:compileJava
POM relocation to an other version number is not fully supported in Gradle : xml-apis:xml-apis:2.0.2 relocated to xml-apis:xml-apis:1.0.b2.
Please update your dependency to directly use the correct version 'xml-apis:xml-apis:1.0.b2'.
Resolution will only pick dependencies of the relocated element.  Artifacts and other metadata will be ignored.
:util:source-formatter:compileJava UP-TO-DATE
:util:source-formatter:writeMavenSettings UP-TO-DATE
:util:source-formatter:buildPluginDescriptor
[main] ERROR org.apache.maven.cli.MavenCli - Failed to execute goal org.apache.maven.plugins:maven-plugin-plugin:3.4:descriptor (default-cli) on project com.liferay.source.formatter: Execution default-cli of goal org.apache.maven.plugins:maven-plugin-plugin:3.4:descriptor failed. RuntimeException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-plugin-plugin:3.4:descriptor (default-cli) on project com.liferay.source.formatter: Execution default-cli of goal org.apache.maven.plugins:maven-plugin-plugin:3.4:descriptor failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:188)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.apache.maven.plugins:maven-plugin-plugin:3.4:descriptor failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 13 more
Caused by: java.lang.RuntimeException
        at org.objectweb.asm.FieldVisitor.visitTypeAnnotation(Unknown Source)
        at org.objectweb.asm.ClassReader.a(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.apache.maven.tools.plugin.extractor.annotations.scanner.DefaultMojoAnnotationsScanner.analyzeClassStream(DefaultMojoAnnotationsScanner.java:202)
        at org.apache.maven.tools.plugin.extractor.annotations.scanner.DefaultMojoAnnotationsScanner.scanArchive(DefaultMojoAnnotationsScanner.java:139)
        at org.apache.maven.tools.plugin.extractor.annotations.scanner.DefaultMojoAnnotationsScanner.scan(DefaultMojoAnnotationsScanner.java:108)
        at org.apache.maven.tools.plugin.extractor.annotations.scanner.DefaultMojoAnnotationsScanner.scan(DefaultMojoAnnotationsScanner.java:75)
        at org.apache.maven.tools.plugin.extractor.annotations.JavaAnnotationsMojoDescriptorExtractor.scanAnnotations(JavaAnnotationsMojoDescriptorExtractor.java:124)
        at org.apache.maven.tools.plugin.extractor.annotations.JavaAnnotationsMojoDescriptorExtractor.execute(JavaAnnotationsMojoDescriptorExtractor.java:103)
        at org.apache.maven.tools.plugin.scanner.DefaultMojoScanner.populatePluginDescriptor(DefaultMojoScanner.java:96)
        at org.apache.maven.plugin.plugin.AbstractGeneratorMojo.execute(AbstractGeneratorMojo.java:245)
        at org.apache.maven.plugin.plugin.DescriptorGeneratorMojo.execute(DescriptorGeneratorMojo.java:90)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 14 more
[main] ERROR org.apache.maven.cli.MavenCli - 
[main] ERROR org.apache.maven.cli.MavenCli - Re-run Maven using the -X switch to enable full debug logging.
[main] ERROR org.apache.maven.cli.MavenCli - 
[main] ERROR org.apache.maven.cli.MavenCli - For more information about the errors and possible solutions, please read the following articles:
[main] ERROR org.apache.maven.cli.MavenCli - [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
:util:source-formatter:buildPluginDescriptor FAILED
:util:source-formatter:formatXML
:util:source-formatter:formatSource
/home/brian/dev/projects/github/liferay-portal/modules/util/source-formatter/src/main/resources/META-INF/maven/com.liferay/com.liferay.source.formatter/plugin-help.xml (SourceCheck:XMLEmptyLinesCheck)
/home/brian/dev/projects/github/liferay-portal/modules/util/source-formatter/src/main/resources/META-INF/maven/plugin.xml (SourceCheck:XMLEmptyLinesCheck)
/home/brian/dev/projects/github/liferay-portal/modules/util/source-formatter/src/main/resources/checkstyle-alloy-mvc.xml (SourceCheck:XMLEmptyLinesCheck)
/home/brian/dev/projects/github/liferay-portal/modules/util/source-formatter/src/main/resources/checkstyle-alloy-mvc.xml (SourceCheck:XMLTagAttributesCheck)
/home/brian/dev/projects/github/liferay-portal/modules/util/source-formatter/src/main/resources/checkstyle.xml (SourceCheck:XMLEmptyLinesCheck)
/home/brian/dev/projects/github/liferay-portal/modules/util/source-formatter/src/main/resources/checkstyle.xml (SourceCheck:XMLTagAttributesCheck)
                                /home/brian/dev/projects/github/liferay-portal/modules/util/source-formatter/src/main/resources/sourcechecks.xml (SourceCheck:XMLEmptyLinesCheck)
/home/brian/dev/projects/github/liferay-portal/modules/util/source-formatter/src/main/resources/sourcechecks.xml (SourceCheck:XMLTagAttributesCheck)
                                                                                                                                Processing checks: 6% completed
FAILURE: Build failed with an exception.

```

@petershin can you look into this?

**Comment by brianchandotcom** [comment]
@hhuijser not merging for now since I can't publish it.

**Comment by brianchandotcom** [comment]
@hhuijser I verified I only get this error AFTER merging your changes, without them, I can publish.

**Comment by hhuijser** [comment]
@brianchandotcom @petershin, I am on it

**Comment by hhuijser** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/61856

**Pull request closed without merging**
