### PR TITLE
LPS-72792 User may sort options in editing mode

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
ci:reopen

**Comment by brianchandotcom** [comment]
@shuyangzhou @mtambara I've seen these errors a few times now.

@arboliveira fyi

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-portal/compare/1239eaa510...d1a5263218

**Comment by shuyangzhou** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/49916

**Pull request closed without merging**
